### PR TITLE
otel: Avoid excessive memory allocations if not configured

### LINKED ISSUE #49075: Memory leak
### Description

Hi,

About 2 days ago, I upgraded our production servers to the latest docker version (27.4.0). Since then, the docker daemon of all servers is eating memory like candy and getting killed by the oom killer once every couple hours. The result is not pretty.

I collected pprof output from the running docker daemon. They all look the across all servers. Here is a typical example:

```
mathieu@Host-001:~/$ go tool pprof -top ./heap-dump-de1-2-2024-12-12-10-56 
File: dockerd
Build ID: 64214f994238df60afd9aa8c14b0322a8fc3412a
Type: inuse_space
Time: Dec 12, 2024 at 10:56am (CET)
Showing nodes accounting for 3326.65MB, 99.71% of 3336.46MB total
Dropped 142 nodes (cum <= 16.68MB)
      flat  flat%   sum%        cum   cum%
 2440.59MB 73.15% 73.15%  2440.59MB 73.15%  github.com/moby/buildkit/util/tracing/detect.(*TraceRecorder).ExportSpans
  502.54MB 15.06% 88.21%   502.54MB 15.06%  go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).interfaceArrayToEventArray (inline)
  383.52MB 11.49% 99.71%   383.52MB 11.49%  go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).SetAttributes
         0     0% 99.71%  2942.62MB 88.20%  github.com/containerd/containerd/tracing.(*Span).End (inline)
         0     0% 99.71%   383.52MB 11.49%  github.com/containerd/containerd/tracing.(*Span).SetAttributes (inline)
         0     0% 99.71%  3326.15MB 99.69%  github.com/docker/docker/daemon/logger/loggerutils.(*LogFile).readLogsLocked
         0     0% 99.71%  3326.15MB 99.69%  github.com/docker/docker/daemon/logger/loggerutils.(*follow).Do
         0     0% 99.71%  3326.15MB 99.69%  github.com/docker/docker/daemon/logger/loggerutils.(*follow).forward
         0     0% 99.71%  3326.15MB 99.69%  github.com/docker/docker/daemon/logger/loggerutils.(*forwarder).Do
         0     0% 99.71%  3326.15MB 99.69%  github.com/docker/docker/daemon/logger/loggerutils.(*forwarder).Do.func1
         0     0% 99.71%  2943.12MB 88.21%  go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End
         0     0% 99.71%   502.54MB 15.06%  go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).snapshot
         0     0% 99.71%  2440.59MB 73.15%  go.opentelemetry.io/otel/sdk/trace.(*simpleSpanProcessor).OnEnd
```

The above points to otel as the likely source of a memory leak. So far, I have been unable to find a way to disable this tracing to revert to a sane(r) setup in production.

### Reproduce

Unfortunatly, I am not able share the list of containers and images needed to reproduce this. I would be happy to collect more data if needed.

### Expected behavior

Dockerd uses much less memory.

### docker version

```bash
Client: Docker Engine - Community
 Version:    27.4.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.19.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.31.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 24
  Running: 6
  Paused: 0
  Stopped: 18
 Images: 8
 Server Version: 27.4.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 88bf19b2105c8b17560993bee28a01ddc2f97182
 runc version: v1.2.2-0-g7cb3632
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-18-cloud-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 6.625GiB
 Name: hive-prod-node-de1-2
 ID: c7645856-eac3-4fdb-b1de-f1bf7ff5b355
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    27.4.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.19.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.31.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 24
  Running: 6
  Paused: 0
  Stopped: 18
 Images: 8
 Server Version: 27.4.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 88bf19b2105c8b17560993bee28a01ddc2f97182
 runc version: v1.2.2-0-g7cb3632
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-18-cloud-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 6.625GiB
 Name: hive-prod-node-de1-2
 ID: c7645856-eac3-4fdb-b1de-f1bf7ff5b355
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

root@prod-node-de2-1:/home/debian# cat /etc/docker/daemon.json 
{
  "log-driver": "json-file",
  "log-opts": {
    "max-file": "5",
    "max-size": "10m"
  }
}

### PR DESCRIPTION
**Pull request by vvoland**
- fixes: https://github.com/moby/moby/issues/49075
- relates to https://github.com/moby/moby/pull/47983

Use noop tracer provider if the OTEL exporter is not configured. This makes the OTEL tracing avoid doing unneeded memory allocations for spans which aren't going to be exported anywhere anyway.

**- How to verify it**
```bash
#!/bin/sh

docker run -d --rm -it --name leak alpine sh -c 'while true; do date; done'

for i in $(seq 0 4); do
    docker logs -f leak >/dev/null &
done


watch -d ps -C dockerd -o rss=

docker rm -f leak

wait
```

Before this patch, the RSS grows significantly over time, in proportion to the amount of running `docker logs -f`.
After the patch, the RSS stays around the same level.

**- Description for the changelog**
```markdown changelog
Fix excessive memory allocations when OTEL is not configured.
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by vvoland** [comment]
FYI, looks like it doesn't need a 26.1 and 25.0 backport - the old buildkit's `detect` implementation did return a noop tracer exporter in such case:
https://github.com/moby/moby/blob/7d991b6e42d04416805114a12bf84c338cb947e6/vendor/github.com/moby/buildkit/util/tracing/detect/detect.go#L92

File: cmd/dockerd/daemon.go [hunk 1]
```diff
@@ -360,8 +362,10 @@ func (cli *daemonCLI) start(ctx context.Context) (err error) {
 		return errors.Wrap(err, "shutting down due to ServeAPI error")
 	}
 
-	if err := tp.Shutdown(context.Background()); err != nil {
-		log.G(ctx).WithError(err).Error("Failed to shutdown OTEL tracing")
+	if otelShutdown != nil {
+		if err := otelShutdown(context.WithoutCancel(ctx)); err != nil {
+			log.G(ctx).WithError(err).Error("Failed to shutdown OTEL tracing")
+		}
 	}
```
Comment (thaJeztah) [inline cmd/dockerd/daemon.go:369]: Not important; wondering if we should make `newTracerProvider` always return a "closer" function that's already wired up, so that we can just;

```go
tp, otelShutdown := newTracerProvider(ctx)
defer otelShutdown()
```

File: cmd/dockerd/daemon.go [hunk 2]
```diff
@@ -391,18 +395,24 @@ func setOTLPProtoDefault() {
...
 		sdktrace.WithSyncer(detect.Recorder),
 	}
 
-	if exp, err := detect.NewSpanExporter(ctx); err != nil {
+	exp, err := detect.NewSpanExporter(ctx)
+	if err != nil {
 		log.G(ctx).WithError(err).Warn("Failed to initialize tracing, skipping")
-	} else if !detect.IsNoneSpanExporter(exp) {
-		opts = append(opts, sdktrace.WithBatcher(exp))
+		return noop.NewTracerProvider(), nil
```
Comment (thaJeztah) [inline cmd/dockerd/daemon.go:407]: Curious, as the basic issue is quite similar; would it make sense to apply the workaround in the same location as we did for that previous OTEL memory leak, or is it not possible to set them up in the same location? (sorry didn't look in-depth, mostly considering that it would be nice to have such workarounds close together);

- https://github.com/moby/moby/pull/48690

File: cmd/dockerd/daemon.go (hunk 1 above)
Comment (vvoland) [reply cmd/dockerd/daemon.go:369]: We can't use `defer` here, because that would get executed after the final `Daemon shutdown complete` message 😅 

https://github.com/moby/moby/blob/adbf9a25835e0291937c9730089c26f9be84dc0d/cmd/dockerd/daemon.go#L371

I wouldn't bother with that tbh. Except maybe make the cleanup function a non-nil so the caller doesn't have to bother with a nil check.
Also, storing context in a closure isn't really the best practice, and it should be up to the caller to pass a desired context.

File: cmd/dockerd/daemon.go (hunk 2 above)
Comment (vvoland) [reply cmd/dockerd/daemon.go:407]: This one is not really a workaround for the OTEL itself. It fixes our code which created and set a full-fledged tracer provider with no export target, rather than just NOT calling `SetTracerProvider` at all, or explicitly setting it to a noop provider.

File: cmd/dockerd/daemon.go (hunk 1 above)
Comment (vvoland) [reply cmd/dockerd/daemon.go]: Removed the nil cleanup func

Comment (thaJeztah) [reply cmd/dockerd/daemon.go]: > We can't use defer here, because that would get executed after the final Daemon shutdown complete message 

Heh, yeah, I thought about that part, but chose to ignore that fact 😇 😉 

> Also, storing context in a closure isn't really the best practice, and it should be up to the caller to pass a desired context.

That's a good point!

> Removed the nil cleanup func

Thanks!

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by cpuguy83 — APPROVED** [review]

**Comment by vvoland** [comment]
Hmmm, looks like this breaks `TestBuildkitHistoryTracePropagation` outside of GHA (where an OTEL isn't configured for the integration tests)

**Comment by thaJeztah** [comment]
Missed a file / change somewhere @vvoland 

```
92.72 cmd/dockerd/daemon.go:249:49: not enough arguments in call to otelutil.NewTracerProvider
```

**Review by laurazard — APPROVED** [review]
LGTM

**Review by dmcgowan — APPROVED** [review]

**Review by thaJeztah — APPROVED** [review]
still LGTM
