### PR TITLE
don't allow deleting the image of running containers

### LINKED ISSUE #13261: overlay backend allows rmi on in-use layers
We switched to overlay yesterday and are already seeing non-deterministic problem with the filesystem backend, across multiple containers and teams. Linux 4.0.2, docker 1.6.0, ext4 filesystem.  I initially thought this might be #11012, but since that was reported against XFS originally I decided to open my own issue.

We run Docker containers for our CI builds.  Immediately after we migrated to the overlay storage driver, we started to see problems:
```
++ cut -d . -f 1
./../otpl-deploy-scripts/bin/otpl-deploy: line 218: cut: command not found
```
```
[Step 2/5] jetbrains.buildServer.agent.runner.CannotBuildCommandLineException: Unable to find java executable at: /usr/lib/jvm/java-8-openjdk-amd64/bin/java
    at jetbrains.buildServer.agent.runner.JavaCommandLineBuilder.buildPath2Java(JavaCommandLineBuilder.java:155)
    at jetbrains.buildServer.agent.runner.JavaCommandLineBuilder.build(JavaCommandLineBuilder.java:107)
```

Trying to enter the container, something is clearly fucked:
```
root@mesos-slave8-qa-uswest2:~# docker exec -it 0adffe3c5da6 /bin/bash
bash-4.3# ls
bash: ls: command not found
bash-4.3# echo *
*
bash-4.3# pwd
/
bash-4.3# /bin/ls
bash: /bin/ls: No such file or directory
bash-4.3# /bin/*
bash: /bin/*: No such file or directory
bash-4.3# find .
.
bash-4.3# bash  # NOTE HOW THIS SUCCEEDS
bash-4.3# exit
bash-4.3# ps
bash-4.3# find /bin/bash
/bin/bash
bash-4.3# find /bin
/bin
```

Looking from the outside in:
```
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay# cd 0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83# ls
lower-id  merged  upper  work
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83# ls merged/
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83# ls upper/
dev  etc  home  mnt  run  tmp  var
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83# find work
work
work/work
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83# find merged
merged
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83# find merged/
merged/
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83# ls merged/
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83# find upper
upper
upper/.dockerenv
upper/.dockerinit
upper/etc
upper/etc/hosts
upper/etc/mtab
...
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83# ls -lh merged/bin/bash
-rwxr-xr-x 0 root root 998K Oct  7  2014 merged/bin/bash
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83# ls -lh merged/bin/
total 0
```

I looked at the mapping, and wonder if it's something related to the absence of a `root` directory:

```
root@mesos-slave8-qa-uswest2:~# cat /proc/mounts  | grep 0adf
overlay /mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83/merged overlay rw,relatime,lowerdir=/mnt/docker/overlay/914daaa4ae3ecae1966c92ef38c62835f5f81fd75ae544409d099345e958c93a/root,upperdir=/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83/upper,workdir=/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83/work 0 0

root@mesos-slave8-qa-uswest2:/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83# ls
lower-id  merged  upper  work
```

```
root@mesos-slave8-qa-uswest2:/# docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64

root@mesos-slave8-qa-uswest2:/# docker info
Containers: 40
Images: 360
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 4.0.2
Operating System: Ubuntu 14.04.2 LTS
CPUs: 8
Total Memory: 29.45 GiB
Name: mesos-slave8-qa-uswest2
ID: NMLO:YQYU:3N53:LTCK:CBGB:LYIH:GHTZ:Y5ME:UIUZ:4IKD:VUWQ:BN2L
WARNING: No swap limit support

root@mesos-slave8-qa-uswest2:~# uname -a
Linux mesos-slave8-qa-uswest2 4.0.2 #1 SMP Tue May 12 23:29:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by mountkin**
Try to fix #13261

The problem described in #13261 can be reproduced with the following script:

``` bash
#!/bin/bash
# Build 2 images for testing.
echo -e "FROM busybox\nRUN echo a"|docker build -t test1 -
echo -e "FROM busybox\nRUN echo b"|docker build -t test2 -

# First let's start a long-running container.
docker run -d test1 sleep 300

# Create another container and force remove its image.
docker run --name=TEST2 test2 true
docker rmi -f test2

# At this point the images of any running containers that were created
# before TEST2 can be removed regardless of the -f flag.
docker rmi test1
```

The problem was introduced by #9204.

### CODE REVIEW

File: integration-cli/docker_cli_rmi_test.go [hunk 1]
```diff
@@ -268,3 +268,43 @@ func (s *DockerSuite) TestRmiBlank(c *check.C) {
...
+		dockerFile := fmt.Sprintf("FROM busybox\nMAINTAINER %s\nRUN echo %s\n", name, name)
+		cmd.Stdin = strings.NewReader(dockerFile)
+
+		if out, _, err := runCommandWithOutput(cmd); err != nil {
+			c.Fatalf("Could not build %s: %s, %v", name, out, err)
+		}
+	}
+
+	// Create a long-running container.
+	cmd := exec.Command(dockerBinary, "run", "-d", images[0], "sleep", "300")
```
Comment (cpuguy83) [inline integration-cli/docker_cli_rmi_test.go]: Please use `dockerCmd` here.

File: integration-cli/docker_cli_rmi_test.go [hunk 2]
```diff
@@ -268,3 +268,43 @@ func (s *DockerSuite) TestRmiBlank(c *check.C) {
 		c.Fatalf("Expected error message not generated: %s", out)
 	}
 }
+
+func (s *DockerSuite) TestRmiContainerImageNotFound(c *check.C) {
+	// Build 2 image for testing.
+	images := []string{"test1", "test2"}
+	for _, name := range images {
+		cmd := exec.Command(dockerBinary, "build", "--no-cache", "-t", name, "-")
```
Comment (cpuguy83) [inline integration-cli/docker_cli_rmi_test.go]: You can use the `buildImage` helper here, from `docker_utils.go`

File: integration-cli/docker_cli_rmi_test.go (hunk 1 above)
Comment (cpuguy83) [inline integration-cli/docker_cli_rmi_test.go]: And for the sake of over-communicating, should use `dockerCmd` in all the cases below as well.

Comment (cpuguy83) [inline integration-cli/docker_cli_rmi_test.go]: Use `top` instead of `sleep 300`

File: integration-cli/docker_cli_rmi_test.go [hunk 3]
```diff
@@ -268,3 +268,33 @@ func (s *DockerSuite) TestRmiBlank(c *check.C) {
...
+
+	// Create a stopped container, and then force remove its image.
+	_, status = dockerCmd(c, "run", imageNames[1], "true")
+	c.Assert(status, check.Equals, 0)
+	_, status = dockerCmd(c, "rmi", "-f", imageIds[1])
+	c.Assert(status, check.Equals, 0)
+
+	// Try to remove the image of the running container and see if it fails
+	// as expected.
+	out, _, err := runCommandWithOutput(exec.Command(dockerBinary, "rmi", "-f", imageIds[0]))
```
Comment (mountkin) [inline integration-cli/docker_cli_rmi_test.go]: @cpuguy83 `dockerCmd` asserts that the command must success, but here the `rmi -f` is expected to fail, so I kept using `runCommandWithOutput`

**Comment by cpuguy83** [comment]
@icecrime I think this is a bug since we should not be able to remove an image of a running container (which I hit late last week myself).
Definitely +1 from me.

**Comment by mountkin** [comment]
ping @jfrazelle @vbatts @crosbymichael

File: integration-cli/docker_cli_rmi_test.go [hunk 4]
```diff
@@ -268,3 +268,33 @@ func (s *DockerSuite) TestRmiBlank(c *check.C) {
...
+	imageIds := make([]string, 2)
+	for i, name := range imageNames {
+		dockerfile := fmt.Sprintf("FROM busybox\nMAINTAINER %s\nRUN echo %s\n", name, name)
+		id, err := buildImage(name, dockerfile, false)
+		c.Assert(err, check.IsNil)
+		imageIds[i] = id
+	}
+
+	// Create a long-running container.
+	_, status := dockerCmd(c, "run", "-d", imageNames[0], "top")
```
Comment (cpuguy83) [inline integration-cli/docker_cli_rmi_test.go]: Status will always be zero here because `dockerCmd` will fail the test immediately otherwise.

File: integration-cli/docker_cli_rmi_test.go [hunk 5]
```diff
@@ -268,3 +268,33 @@ func (s *DockerSuite) TestRmiBlank(c *check.C) {
...
+	c.Assert(status, check.Equals, 0)
+
+	// Create a stopped container, and then force remove its image.
+	_, status = dockerCmd(c, "run", imageNames[1], "true")
```
Comment (cpuguy83) [inline integration-cli/docker_cli_rmi_test.go]: Same on status

File: integration-cli/docker_cli_rmi_test.go [hunk 6]
```diff
@@ -268,3 +268,33 @@ func (s *DockerSuite) TestRmiBlank(c *check.C) {
...
+	c.Assert(status, check.Equals, 0)
+	_, status = dockerCmd(c, "rmi", "-f", imageIds[1])
```
Comment (cpuguy83) [inline integration-cli/docker_cli_rmi_test.go]: Same on status

File: integration-cli/docker_cli_rmi_test.go (hunk 3 above)
Comment (cpuguy83) [inline integration-cli/docker_cli_rmi_test.go]: Thanks, this is fine.

**Comment by mountkin** [comment]
@cpuguy83  the unnecessary status check is removed.

**Comment by cpuguy83** [comment]
LGTM

**Comment by calavera** [comment]
LGMT

**Comment by thaJeztah** [comment]
Thanks @mountkin !
