### PR TITLE
Better error message for invalid unix socket format

### LINKED ISSUE #18521: wrong daemon error message
When you use a directory instead of a socket in the `docker daemon -H` flag, the error message could be improved.

```
$ mkdir /tmp/test
$ sudo ./bundles/1.10.0-dev/binary/docker-1.10.0-dev daemon  -H unix:///tmp/test
FATA[0000] is a directory
```

### PR DESCRIPTION
**Pull request by WeiZhang555**
Close #18521 

Give more meaningful error prompts when user try to bind a directory as
unix socket.

New message printed:

```
$ sudo docker daemon -H unix:///tmp/test
FATA[0000] Error Unlink /tmp/test: is a directory 
```

Signed-off-by: Zhang Wei zhangwei555@huawei.com

### CODE REVIEW

**Comment by cpuguy83** [comment]
This might be better handled either by the caller inspecting the error, or providing a wrapped error (instead of just the error text) so that people can handle the error properly.

**Comment by WeiZhang555** [comment]
@cpuguy83 How about this one?  Any suggestion?

File: api/server/server_unix.go [hunk 1]
```diff
@@ -38,6 +39,9 @@ func (s *Server) newServer(proto, addr string) ([]*HTTPServer, error) {
 	case "unix":
 		l, err := sockets.NewUnixSocket(addr, s.cfg.SocketGroup)
 		if err != nil {
+			if strings.Contains(err.Error(), "is a directory") {
```
Comment (cpuguy83) [inline api/server/server_unix.go]: I think we can simplify this.
Instead of looking into the error like this, we can do:
`return nil, fmt.Errorf("can't create unix socket %s: %v, addr, err)`

**Comment by WeiZhang555** [comment]
@cpuguy83 code updated, please take a look, thank you! :smile:

**Comment by cpuguy83** [comment]
LGTM if janky is good.

**Comment by cpuguy83** [comment]
:+1:

**Comment by thaJeztah** [comment]
LGTM, and all green \o/ thanks!
