### PR TITLE
devmapper: prevent libdevmapper from deleting /dev/mapper/docker-xxx symbolic links in RemoveDeviceDeferred

### LINKED ISSUE #24671: docker races with udev on device symlink handling when dm.use_deferred_removal is enabled
As I commented on  #4036, docker(actually libdevicemapper used by docker) may race with udev on device symlink creating/deleting when `dm.use_deferred_removal` is turned on , and it eventually leads to a `docker start/diff` fail.Following is the reproducing procedure:

# docker info
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.11.1
Storage Driver: devicemapper
 Pool Name: docker-252:1-58724678-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 883.9 MB
 Data Space Total: 107.4 GB
 Data Space Available: 35.03 GB
 Metadata Space Used: 2.146 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.86 GiB
Name: jzl-dev0010
ID: U4ZX:62TO:YRGL:CNDH:6UZN:VNYX:3R2W:ZCWF:4TJS:54BS:O4AK:NLYY
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

# way to reproduce
## make sure all containers  removed

```
# NOTE!!! this command is dangerous, don't execute it on any non-experimental node.
docker rm -f  `docker ps -aq`
```
## get image ready
a `busybox` image would be sufficient, `docker pull busybox`

## get script ready
A Python script is needed to eagerly detect and open any docker created non-init  dm devices:

```python
import os
import time

while True:
    try:
        for line in os.listdir('/dev/mapper'):
            if 'init' in line:continue
            if len(line) >= 80:
                filename=os.path.join('/dev/mapper/',line)
                f = open(filename)
        print 'got it %s' % filename
        time.sleep(3*10**7)
    except Exception:
        pass
```

## make sure all container or image related dm devices removed
run `dmsetup info` to list all dm devices on your node, and run `dmsetup remove <name>` to remove all devices whose name starts with `docker-` and ends with a uuid or `<uuid>-init`, such as `docker-252:1-58724678-3c96b9d15c41b49816eab1faaa0cb6eaa7cdffe5decd45f2bd48ae72f32e16f5`

## run the script and reproduce the issue
following is one sample of my reproducing logs:

```bash
# docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
# dmsetup info
Name:              docker-252:1-58724678-pool
State:             ACTIVE
Read Ahead:        8192
Tables present:    LIVE
Open count:        0
Event number:      0
Major, minor:      253, 0
Number of targets: 1

# python opendm.py &
[1] 3757
# cid=`docker create -it busybox sh`
got it /dev/mapper/docker-252:1-58724678-097a341a6a5f17cc86f9d83ebdff35b8da86fd8ab6d614ac8445f3fabe1d6e25
# docker diff $cid
# docker start $cid
Error response from daemon: open /dev/mapper/docker-252:1-58724678-097a341a6a5f17cc86f9d83ebdff35b8da86fd8ab6d614ac8445f3fabe1d6e25: no such file or directory
Error: failed to start containers: d3cbd8f86704136511b5d4cfdafeb1398a46f962ff9af7389ec7368f8472433e
```

the essential commands are:
```bash
python opendm.py &
docker diff $cid
docker start $cid
```

## get the corrupted container back to normal
```bash
# kill %1
# dmsetup remove docker-252:1-58724678-097a341a6a5f17cc86f9d83ebdff35b8da86fd8ab6d614ac8445f3fabe1d6e25
[1]+  Terminated              python opendm.py
# ls /dev/dm-*
/dev/dm-0
# ls /dev/mapper/
control  docker-252:1-58724678-pool
# docker start $cid
d3cbd8f86704136511b5d4cfdafeb1398a46f962ff9af7389ec7368f8472433e
```

the essential operations to recover the container include:
1. kill the background process `python opendm.py`
2. remove the container's dm device.

### PR DESCRIPTION
**Pull request by jizhilong**
**\- What I did**
Fixes #24671 by preventing libdevmapper from deleting `/dev/mapper/docker-xxxxx` links when `dm.use_deferred_remove` is enabled.

In the original implementation, libdevmapper will delete the symbolic link even if the device removal is deferred by the kernel, which will leave the device being exist but the symbolic link being lost, and docker will fail to activate and mount the device again.

By preventing libdevmapper from doing this, and leave all symlink handling to udev, `/dev/mapper/docker-xxx` link's lifecycle will always be synced with the corresponding `/dev/dm-x` device.

**\- How I did it**
I did it by set a dm task cookie and a `DmUdevDisableLibraryFallback` task flag, liddevmapper will check these two variables to see if it need to delete the symlink by itself([ref](https://git.fedorahosted.org/cgit/lvm2.git/tree/libdm/ioctl/libdm-iface.c#n2025)).

**\- How to verify it**
please refer to the **way to produce** section in #24671 

**\- Description for the changelog**
devicemapper: Fix the issue that device symlinks may get lost when `dm.use_deferred_removal` is enabled. [#24740](https://github.com/docker/docker/pull/24740)

### CODE REVIEW

**Comment by rhvgoyal** [comment]
Thanks @jizhilong for fixing this issue.

LGTM

File: pkg/devicemapper/devmapper.go [hunk 1]
```diff
@@ -358,6 +358,15 @@ func RemoveDeviceDeferred(name string) error {
 		return ErrTaskDeferredRemove
 	}
 
+	// cookie needed here, or else libdevmapper will disable udev dm rules
+	// and delete the symlink under /dev/maper, even the device removal is deferred
```
Comment (shishir-a412ed) [inline pkg/devicemapper/devmapper.go]: small nit `/dev/maper` should be `/dev/mapper`. Otherwise LGTM.

**Comment by jizhilong** [comment]
@shishir-a412ed typo fixed and pr branch rebased.

**Comment by jizhilong** [comment]
@shishir-a412ed @rhvgoyal 
I  noticed only setting a task cookie is not enough to prevent libdevmapper from deleting `/dev/mapper/dodkcer-xxxx` symlinks by itself, we should also add a `DmUdevDisableLibraryFallback` flag to the dm task.
I made a new commit for `DmUdevDisableLibraryFallback` and pushed to the PR branch, should I also update the title and the content of the PR?

File: pkg/devicemapper/devmapper.go [hunk 2]
```diff
@@ -358,12 +358,16 @@ func RemoveDeviceDeferred(name string) error {
...
 	}
 
-	// cookie needed here, or else libdevmapper will disable udev dm rules
-	// and delete the symlink under /dev/mapper, even the device removal is deferred
-	// by the kernel, but no need to call UdevWait on the cookie after task.run,
-	// since deferred device removal is an asynchronous api call.
+	// set a task cookie and disable library fallback, or else libdevmapper will
+	// disable udev dm rules and delete the symlink under /dev/mapper by itself,
+	// no matter the removal is executed immediately or deferred by the kernel.
+	// Calling UdevWait on the cookie after task.run is not necessary, since deferred
```
Comment (jizhilong) [inline pkg/devicemapper/devmapper.go]: semaphore leak observed in my development environment, I think it is caused by not calling 'UdevWait'.So, plz DONT merge this PR for now!

**Comment by thaJeztah** [comment]
ping @rhvgoyal PR is updated, ptal

**Comment by LK4D4** [comment]
ping @rhvgoyal

**Comment by crosbymichael** [comment]
LGTM

@rhvgoyal can you check the latest change one last time and i'll merge if it looks good to you.

**Comment by rhvgoyal** [comment]
@jizhilong disabling library fallback seems odd. I think library does some actions if it detects that udev has not done its job. So if udev is working properly and symlink is deleted when device is gone, library wil not try to cleanup that symlink at all.

Can you please dive deeper into this and provide a good explanation of what is happening.

**Comment by jizhilong** [comment]
@rhvgoyal you are 'partially' right, but libdevmapper will not always check udev is working properly, it depends on whether a cookie is set in the dm_task and `DM_UDEV_DISABLE_LIBRARY_FALLBACK` is turned on or not.

here is the [code snippets](https://git.fedorahosted.org/cgit/lvm2.git/tree/libdm/ioctl/libdm-iface.c#n2021) libdevmapper used to determine whether it should check udev's work and whether it should rely on udev to complete the node operations.

```C
    /*
     * Are we expecting a udev operation to occur that we need to check for?
     */
    check_udev = dmt->cookie_set &&
             !(dmt->event_nr >> DM_UDEV_FLAGS_SHIFT &
               DM_UDEV_DISABLE_DM_RULES_FLAG);

    rely_on_udev = dmt->cookie_set ? (dmt->event_nr >> DM_UDEV_FLAGS_SHIFT &
                      DM_UDEV_DISABLE_LIBRARY_FALLBACK) : 0;
```

so there are three key flags influencing the following code path,

- `dmt->cookie_set`, a flag indicating a cookie is set in the `dm_task` structure or not, which is  totally and directly determined by the library user.
- `DM_UDEV_DISABLE_DM_RULES_FLAG`,  indicates whether udev rules are disabled or not, which can be set explicitly set by the library user(not happen in our scenario) **OR** inferred  by libdevmapper by checking the presence of dm cookie, without dm cookie provided, `DM_UDEV_DISABLE_DM_RULES_FLAG` will always be set, following is the corresponding [code snippets](https://git.fedorahosted.org/cgit/lvm2.git/tree/libdm/ioctl/libdm-iface.c#n1770):

```C
	ioctl_with_uevent = dmt->type == DM_DEVICE_RESUME ||
			    dmt->type == DM_DEVICE_REMOVE ||
			    dmt->type == DM_DEVICE_RENAME;

	if (ioctl_with_uevent && dm_cookie_supported()) {
		/*
		 * Always mark events coming from libdevmapper as
		 * "primary sourced". This is needed to distinguish
		 * any spurious events so we can act appropriately.
		 * This needs to be applied even when udev_sync is
		 * not used because udev flags could be used alone.
		 */
		dmi->event_nr |= DM_UDEV_PRIMARY_SOURCE_FLAG <<
				 DM_UDEV_FLAGS_SHIFT;

		/*
		 * Prevent udev vs. libdevmapper race when processing nodes
		 * and symlinks. This can happen when the udev rules are
		 * installed and udev synchronisation code is enabled in
		 * libdevmapper but the software using libdevmapper does not
		 * make use of it (by not calling dm_task_set_cookie before).
		 * We need to instruct the udev rules not to be applied at
		 * all in this situation so we can gracefully fallback to
		 * libdevmapper's node and symlink creation code.
		 */
		if (!dmt->cookie_set && dm_udev_get_sync_support()) {
			log_debug_activation("Cookie value is not set while trying to call %s "
					     "ioctl. Please, consider using libdevmapper's udev "
					     "synchronisation interface or disable it explicitly "
					     "by calling dm_udev_set_sync_support(0).",
					     dmt->type == DM_DEVICE_RESUME ? "DM_DEVICE_RESUME" :
					     dmt->type == DM_DEVICE_REMOVE ? "DM_DEVICE_REMOVE" :
									     "DM_DEVICE_RENAME");
			log_debug_activation("Switching off device-mapper and all subsystem related "
					     "udev rules. Falling back to libdevmapper node creation.");
			/*
			 * Disable general dm and subsystem rules but keep
			 * dm disk rules if not flagged out explicitly before.
			 * We need /dev/disk content for the software that expects it.
			*/
			dmi->event_nr |= (DM_UDEV_DISABLE_DM_RULES_FLAG |
					  DM_UDEV_DISABLE_SUBSYSTEM_RULES_FLAG) <<
					 DM_UDEV_FLAGS_SHIFT;
		}
	}
```
- `DM_UDEV_DISABLE_LIBRARY_FALLBACK`, which can be explicitly set by the library user.

for a conclution, the value of `check_udev` and `rely_on_udev` will be eventually determined by the value of `cookie_set` and ` DM_UDEV_DISABLE_LIBRARY_FALLBACK`:

      | cookie_set==true | cookie_set == false
----|-----------------|---------------------
 DM_UDEV_DISABLE_LIBRARY_FALLBACK=true|check_udev==true     rely_on_udev==true|check_udev==false     rely_on_udev==false
 DM_UDEV_DISABLE_LIBRARY_FALLBACK=false|check_udev==true     rely_on_udev==false|check_udev==false     rely_on_udev==false


if `rely_on_udev` is true, libdevmapper wil bypass node operations, and udev will delete the symlink when kernel execute the deferred removal eventually.If `rely_on_dev` is false, libdevmapper will try to delete the symlink with no regarding to it's a deferred `DM_DEV_REMOVE` or immediate `DM_DEV_REMOVE`,[code](https://git.fedorahosted.org/cgit/lvm2.git/tree/libdm/ioctl/libdm-iface.c#n2036):

```C
	case DM_DEVICE_REMOVE:
		/* FIXME Kernel needs to fill in dmi->name */
		if (dev_name && !rely_on_udev)
			rm_dev_node(dev_name, check_udev, rely_on_udev);
		break;
```

so, if we don't set a cookie or don't explictly set `DM_UDEV_DISABLE_LIBRARY_FALLBACK`, `rely_on_udev` will always be true, and libdevmapper will always try to delete symlinks, even if the actual node removal was deferred by the kernel.

with the reproducint script I provided in #24671, this issue can be reproduced, and a `strace -e trace=unlink` on the docker damon process confirmed my hypothesis that docker daemon(libdevmapper) will delete symlinks by itself.

I do think this should a issue of libdevmapper, it should check the status of the dm node, if it is in a state of deferred remove, the symbolic link deletion should also be delayed. But since libdevmapper impacts a lot of applications and we can bypass it without much code change, it is better to do the fix in docker for now. 

BTW, this issue will rarely happen if there are no other process having races with docker daemon on devices under /dev/mapper(we saw it because we'are starting and stopping containers at quite a high rate)

File: pkg/devicemapper/devmapper.go [hunk 3]
```diff
@@ -361,15 +361,13 @@ func RemoveDeviceDeferred(name string) error {
...
-	// Calling UdevWait on the cookie after task.run is not necessary, since deferred
-	// device removal is an asynchronous api call.
 	var cookie uint
 	var flags uint16
 	flags = DmUdevDisableLibraryFallback
-
 	if err := task.setCookie(&cookie, flags); err != nil {
 		return fmt.Errorf("devicemapper: Can not set cookie: %s", err)
 	}
+	defer UdevWait(&cookie)
```
Comment (rhvgoyal) [inline pkg/devicemapper/devmapper.go]: If you wait for cookie to complete, will we not wait till udev actually as removed the device and symlink? If yes, then deferred removal does not mean anything. If no, then it bags the question, what's the point of waiting on cookie. just to clean it up?

Comment (jizhilong) [inline pkg/devicemapper/devmapper.go]: libdevmapper use system-v semaphore for synchronization with udev, and the cookie(which is a random string generated when dm_task_set_cookie get called) is used as the semaphore's id.Before libdevmapper do the `ioctl` syscall, it first create a semaphore with the cookie as id, and increment it by one, after the syscall, it checks `ioctl`'s return value to see whether a `DM_UEVENT_GENERATED_FLAG`, if not set, libdevmapper knows there is no need to wait for udev completing its job, so it will decrement the semaphore immediately, if set, libdevmapper knows there is a udev event generated by kernel, and udev have some work to do for that event.When udev catches that event, it (I guess) will increment the semaphore first and do its jobs against udev rules, and finally decrement the semaphore.What libdevmapper actually do in `dm_udev_wait` is undo its semaphore increment first, and repeatedly wait for the semaphore's value decrements to zero.

For our case, if the target device is not busy, the kernel will remove it immediately, which acts the same as a normal remove operation, so call `UdevWait` totally make sense. When the device is busy, kernel will mark the device as deferred remove, and no udev event generated, the semaphore's value will be decremented right after the `ioctl` syscall, and what `UdevWait` do later is merely nothing but cleaning up the semaphore.

**Comment by rhvgoyal** [comment]
cc @gibarian

**Comment by rhvgoyal** [comment]
cc @prajnoha

**Comment by rhvgoyal** [comment]
@jizhilong Ok, your reasoning sounds good given current code. I talked to libdm developer @prajnoha and he said that he will add some code so that device node symlink re-appears when deferred device removal is cancelled. But as it will take some time for fix to be available and show up in various distros, in the mean time it makes sense to keep your patches.

Can you please merge all 3 patches in to one. Provide a very good changelong explaining libdm behavior and what are we doing in short term. I want to make sure important points are captured so that we are not confused later. And some of those points should be captured in code so that a developer later can read it and understand this special case.

**Comment by jizhilong** [comment]
@rhvgoyal commits squashed/rebased, and I also updated the `ChangeLog` section in the PR description.I inserted several comments trying to explain why we should set a cookie and set the `DmUdevDisableLibraryFallback` flag, I'm not quite sure if they are clear enough or are those comments redundant since we have linked to this PR in the commit message.Anyway, feel free to ping me for any suggestions, thanks for your reviewing.

**Comment by crosbymichael** [comment]
@jizhilong thanks for the quick update

**Comment by crosbymichael** [comment]
LGTM

**Comment by rhvgoyal** [comment]
@crosbymichael Can this fix be backported to 1.12?

**Comment by crosbymichael** [comment]
@rhvgoyal if we do another patch release we could backport it.  We already released 1.12.1 and i'm not sure if we should consider this a priority 0 where we need to do a 1.12.2 release.  

What do you think?

**Comment by rhvgoyal** [comment]
@crosbymichael I agree that this can be included if you decide to 1.12.2. Given deferred removal is not enabled by default and its a race condition, I would not consider this patch alone to be reason for 1.12.2

**Comment by crosbymichael** [comment]
@rhvgoyal ok, thanks.  If we end up doing another patch release we can backport this change.
