### PR TITLE
fix incorect login client credential save when the registry is the default docker registry

### LINKED ISSUE #30779: docker login with a wrong path.
**Description**

docker@default-online:~$ docker login index.docker.io/namespace
Username: hyzhou
Password:
Login Succeeded

I provided the registry for user. Some people say they are already login but can not pull the they private image. In the end, we find the user login with a domain and path.

If docker can refuse the login, when login url like this.

**Describe the results you received:**

Login Succeeded

**Describe the results you expected:**

Login Faild

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
docker@default-online:~$ docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
docker@default-online:~$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 16
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.27-boot2docker
Operating System: Boot2Docker 1.12.3 (TCL 7.2); HEAD : 7fc7575 - Thu Oct 27 17:23:17 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8 MiB
Name: default-online
ID: LXGY:ZWCS:I6JU:QJGI:6VDP:VYDW:W75W:WUO7:YYO5:TO2D:ZDHF:B4IE
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 23
 System Time: 2017-02-07T08:29:55.299882751Z
 EventsListeners: 0
Username: hyzhou
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by krasi-georgiev**
closes #30779

- What I did
compare the user login url with the default registry and if the same just ignore

- How I did it
parsing the url using url.Parse and compare it with the default docker registry
- How to verify it
docker login index.docker.io
docker login docker.io

in the ~/.docker/config.json
before the fix the login will succeed , but docker pull/push for private images will fail as  the saved auth is not saved as the default docker registry url

"auths": {
"index.docker.io": {
"auth": "xxxxxxx"
}
}

after the fix any url that is the default docker registry will be saved properly so it can be used with docker push/pull for private images

"auths": {
"https://index.docker.io/v1/": {
"auth": "xxxxxxxx"
}
}

some more discussions
https://github.com/docker/docker/pull/30831

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
@aaronlehmann please review this one. I think I improved it a bit.

File: cli/command/registry/login.go [hunk 1]
```diff
@@ -50,7 +52,18 @@ func runLogin(dockerCli *command.DockerCli, opts loginOptions) error {
...
 	if opts.serverAddress != "" {
-		serverAddress = opts.serverAddress
+		// when a user supplied login url is the default docker registry save the credentials under the default docker registry domain
+		// without this the login will succeed ,but docker pull/push will fail
+		u, _ := url.Parse(opts.serverAddress)
+		if u.Host == "" {
+			// handle urls without schema for backward compatibility and pass the integration tests
+			u, _ = url.Parse("http://" + opts.serverAddress)
+		}
+		if strings.Contains(authServer, u.Host) {
```
Comment (aaronlehmann) [inline cli/command/registry/login.go]: This doesn't seem defensive enough. Consider if the user tries to `docker login` to `ocker.io` or `d`. Maybe we should go back to the check from the previous PR.

Comment (krasi-georgiev) [inline cli/command/registry/login.go]: yes you are right , I will need to think more

**Comment by krasi-georgiev** [comment]
It should be ok this time , I think I tested all scenarios and it behaves as expected.

**Comment by dmcgowan** [comment]
We do not want to allow exposing the underlying default registry hostname to the users via the `docker login` command. Docker login is intended to take in a registry domain, for a private registry this is the first part of the image name which is used on push and pull. For the default registry, there are special rules that allow the domain namespace to be omitted and it is the default for login when no registry namespace is specified. Because of this, we must consider `docker login index.docker.io` to be invalid as we have defined the default namespace to be `docker.io`.  If a login is successful, it should only be applied to images with the same prefix, so `index.docker.io` could be used for `index.docker.io/user/image`. However `index.docker.io/user/image` is not considered a supported registry endpoint and therefore we do not support that as a valid name. 

Additionally, the presence of the string `https://index.docker.io/v1/` inside the config.json only exists for backwards compatibility. The correct string should be `docker.io`, but we have been reluctant in making such a change that is largely cosmetic and potentially problematic for users.  We also should not make an attempt to parse the auth server value or match it against the user input.

I think there may still be a needed fix here to properly allow `docker login docker.io`. Even though it is implied it should not produce a different result than `docker login`. The value to match against could be found at https://github.com/docker/docker/blob/master/registry/config.go#L37.

**Comment by krasi-georgiev** [comment]
@dmcgowan thanks for stepping in. 

don't quite understand your explanation , could you maybe suggest how to address this bug?
do you mean I should return an error when user tries to login to docker.io or index.docker.io ?

my idea was to simply ignore the user input if it matches the default docker registry and just save the credentials against the docker registry.

**Comment by dmcgowan** [comment]
@krasi-georgiev the only default we expose is `docker.io`, doing a `docker login index.docker.io` is not supported and we do not need to define the behavior of that or any other subdomain of `docker.io`. If `docker login index.docker.io` succeeds, but push/pull fails, that is not a bug since it is not supported. Doing `docker login docker.io` should be equivalent to `docker login` and if you want to update this PR to allow that, then we can keep it open.

**Comment by krasi-georgiev** [comment]
ok , I will change it.

on a side note if docker login index.docker.io succeeds wouldn't it be confusing why docker push/pull fails after a successful  login ?

**Comment by dmcgowan** [comment]
@krasi-georgiev thanks

> wouldn't it be confusing

Unfortunately `docker login index.docker.io` succeeding doesn't tell us much except that a 200 was received from either an endpoint at "/v1/users/" or "/v2/" at that domain. There is no other negotiation that happens which guarantees that the endpoint is a valid registry. If there is documentation that hints at logging in with that domain it should be changed, otherwise not much we should do about bad information or suggestions. This is one of those situations where we can't really be stricter generally without breaking existing registries and it is not desired to add more special cases for the default registry to account for potential misunderstandings (for example the same would be true of `docker login registry-1.docker.io`).

**Comment by krasi-georgiev** [comment]
@dmcgowan  I see your point
what about if change the code to return an error if the user is trying to use any subdomain.docker.io or docker.io

something like:
If you want to login to the default docker registry don't add any url after docker login ....

it is really bugging me that a login can succeed , but you can't pull/push

**Comment by krasi-georgiev** [comment]
@dmcgowan - please have a look now

**Comment by dmcgowan** [comment]
> what about if change the code to return an error if the user is trying to use any subdomain.docker.io or docker.io

Just check `docker.io`, we may have valid test registries as subdomains that we to use. No parsing needed to get the host only, paths are also not supported here.

**Comment by krasi-georgiev** [comment]
@dmcgowan sorry I didn't understand what you mean.

**Comment by dmcgowan** [comment]
`if opts.serverAddress != "" && opts.serverAddress != "docker.io"`, all other input should be treated as before

**Comment by krasi-georgiev** [comment]
@dmcgowan not sure why my logic was wrong , but I changed it how you suggested.

it doesn't fix the original bug report though

**Comment by dmcgowan** [comment]
@krasi-georgiev this part of the code should not be parsing the given user input as a URL when the intended input is a domain (as defined here https://godoc.org/github.com/docker/distribution/reference). While I don't consider `docker login docker.io/reponame` as correct input, if passing in a path is currently allowed then you can made an additional change to support the prefix "docker.io/". 

As for the original issue, this will close it as `index.docker.io` is not a supported registry namespace.

**Comment by krasi-georgiev** [comment]
@dmcgowan thanks for the additional info
from what I gathered the user input should be a valid domain, but the client doesn't currently verify this.

I will leave it at that as I changed the PR too many times now, so if needed will come back to it later when I have more motivation :)

please merge it as it is.

> support the prefix "docker.io/".

not sure what did you mean here

**Comment by krasi-georgiev** [comment]
@dmcgowan - is there still any issue with the pull request ?

**Comment by dmcgowan** [comment]
LGTM

**Comment by krasi-georgiev** [comment]
@thaJeztah do you know who should confirm the merge ?

**Review by AkihiroSuda — APPROVED** [review]
LGTM
