### PR TITLE
Carry Fix docker inspect container only reports last assigned information

### LINKED ISSUE #17352: docker inspect container only reports last assigned IP
The container info should return `NetworkSettings` as an array --- one for each network the container belongs to.  Right now, `NetworkSettings` appears to be only holding the last assigned values.  For example, I created a container it appears on the default bridge with an ip of : 172.17.0.2.  After attaching the container to a second network, only the IPAddress for the second network is visible to inspection.

### PR DESCRIPTION
**Pull request by tiborvass**
Fixes #17352
Closes #17360 

Ping @calavera

### CODE REVIEW

File: api/types/versions/v1p21/types.go [hunk 1]
```diff
@@ -0,0 +1,28 @@
+// Package v1p21 provides specific API types for the API version 1, patch 21.
```
Comment (calavera) [inline api/types/versions/v1p21/types.go]: we can remove this whole file :fire: :metal:

**Comment by calavera** [comment]
Code LGTM. Waiting to see what janky thinks about it.

**Comment by tiborvass** [comment]
CI has issues, we need to run the tests locally

File: integration-cli/docker_utils.go [hunk 2]
```diff
@@ -782,13 +782,13 @@ func dockerCmdInDirWithTimeout(timeout time.Duration, path string, args ...strin
...
-func findContainerIP(c *check.C, id string, vargs ...string) string {
-	out, _ := dockerCmd(c, "inspect", "--format='{{ .NetworkSettings.IPAddress }}'", id)
+func findContainerIP(c *check.C, id string, network string) string {
+	out, _ := dockerCmd(c, "inspect", fmt.Sprintf("--format='{{ .NetworkSettings.Networks.%s.IPAddress }}'", network), id)
 	return strings.Trim(out, " \r\n'")
 }
 
 func (d *Daemon) findContainerIP(id string) string {
-	return findContainerIP(d.c, id, "--host", d.sock())
+	return findContainerIP(d.c, id, "--host")
```
Comment (coolljt0725) [inline integration-cli/docker_utils.go]: @tiborvass  Busy this day, get no time to read the notes from the github.  
`return findContainerIP(d.c, id, "--host")` should be `return findContainerIP(d.c, id, "bridge")`
Sorry for my mistake in my PR, don't know why CI got green on my PR

Comment (thaJeztah) [inline integration-cli/docker_utils.go]: Thanks so much for looking @coolljt0725, and no need to apologize (that's where reviews are for, we're all human!)

Comment (coolljt0725) [inline integration-cli/docker_utils.go]: @thaJeztah   thanks
@tiborvass   After investigating why `return findContainerIP(d.c, id, "--host")` unexpectedly make CI green and found that we can't call `findContainerIP` in ` func (d *Daemon) findContainerIP(id string)` because `findContainerIP` connect to the daemon start by `.integration-daemon-start`, we should connect the daemon `d` here, so I think the correct fix here is
<pre><code>func (d *Daemon) findContainerIP(id string) string {
        out, _ := d.Cmd("inspect", fmt.Sprintf("--format='{{ .NetworkSettings.Networks.bridge.IPAddress }}'"), id)
        return strings.Trim(out, " \r\n'")
}
</code></pre>
correct me if I'm wrong :-)

Comment (tiborvass) [inline integration-cli/docker_utils.go]:
```diff
diff --git a/integration-cli/docker_utils.go b/integration-cli/docker_utils.go
index 67627af..850ad2e 100644
--- a/integration-cli/docker_utils.go
+++ b/integration-cli/docker_utils.go
@@ -783,12 +783,19 @@ func dockerCmdInDirWithTimeout(timeout time.Duration, path string, args ...strin
 }
 
 func findContainerIP(c *check.C, id string, network string) string {
-	out, _ := dockerCmd(c, "inspect", fmt.Sprintf("--format='{{ .NetworkSettings.Networks.%s.IPAddress }}'", network), id)
+	out, err := dockerCmd(c, "inspect", fmt.Sprintf("--format='{{ .NetworkSettings.Networks.%s.IPAddress }}'", network), id)
+	if err != nil {
+		c.Warn(err)
+	}
 	return strings.Trim(out, " \r\n'")
 }
 
 func (d *Daemon) findContainerIP(id string) string {
-	return findContainerIP(d.c, id, "--host")
+	out, err := d.Cmd("inspect", fmt.Sprintf("--format='{{ .NetworkSettings.Networks.bridge.IPAddress }}'"), id)
+	if err != nil {
+		d.c.Warn(err)
+	}
+	return strings.TrimSpace(out)
 }
 
 func getContainerCount() (int, error) {

```

@calavera @coolljt0725 does this sound ok to you guys ?

Comment (calavera) [inline integration-cli/docker_utils.go]: lgtm

Comment (vdemeester) [inline integration-cli/docker_utils.go]: @tiborvass `err` will be an int in `findContainerIP` with `0` as value (or it will fail the test if an error occured). You probably want to use `out, _, err := dockerCmdWithError(…)` instead.

Comment (runcom) [inline integration-cli/docker_utils.go]: that if err != nil (from dockerCmd) won't compile (cannot convert nil to type int) I think @vdemeester

Comment (vdemeester) [inline integration-cli/docker_utils.go]: @runcom Yeah even that :sweat_smile: :stuck_out_tongue_closed_eyes:

**Comment by tiborvass** [comment]
@vdemeester @runcom @calavera @coolljt0725 fixed thank you

**Comment by calavera** [comment]
@tiborvass it looks like `c.Warn` does not exist:

```
docker_utils.go:1010: c.Warn undefined (type *check.C has no field or method Warn)
```

**Comment by calavera** [comment]
@tiborvass you need this patch:

```diff
diff --git c/integration-cli/docker_utils.go i/integration-cli/docker_utils.go
index 8aea980..581766d 100644
--- c/integration-cli/docker_utils.go
+++ i/integration-cli/docker_utils.go
@@ -785,7 +785,7 @@ func dockerCmdInDirWithTimeout(timeout time.Duration, path string, args ...strin
 func findContainerIP(c *check.C, id string, network string) string {
        out, _, err := dockerCmdWithError(c, "inspect", fmt.Sprintf("--format='{{ .NetworkSettings.Networks.%s.IPAddress }}'", network), id)
        if err != nil {
-               c.Warn(err)
+               c.Log(err)
        }
        return strings.Trim(out, " \r\n'")
 }
@@ -793,7 +793,7 @@ func findContainerIP(c *check.C, id string, network string) string {
 func (d *Daemon) findContainerIP(id string) string {
        out, err := d.Cmd("inspect", fmt.Sprintf("--format='{{ .NetworkSettings.Networks.bridge.IPAddress }}'"), id)
        if err != nil {
-               d.c.Warn(err)
+               d.c.Log(err)
        }
        return strings.TrimSpace(out)
 }
```

**Comment by tiborvass** [comment]
@calavera yes thank you I noticed it while rebasing :)

File: integration-cli/docker_utils.go [hunk 3]
```diff
@@ -782,13 +782,17 @@ func dockerCmdInDirWithTimeout(timeout time.Duration, path string, args ...strin
...
 	return strings.Trim(out, " \r\n'")
 }
 
 func (d *Daemon) findContainerIP(id string) string {
-	return findContainerIP(d.c, id, "--host", d.sock())
+	out, err := d.Cmd("inspect", fmt.Sprintf("--format='{{ .NetworkSettings.Networks.bridge.IPAddress }}'"), id)
+	if err != nil {
+		d.c.Log(err)
+	}
+	return strings.Trim(out, " \r\n'")
```
Comment (tiborvass) [inline integration-cli/docker_utils.go]: @calavera note that i just took what was at line 787

**Comment by calavera** [comment]
LGTM

**Comment by tiborvass** [comment]
putting merge label, since it already got okays in the pr this is carrying.

File: daemon/container_unix.go [hunk 4]
```diff
@@ -88,15 +88,25 @@ func (container *Container) setupLinkedContainers() ([]string, error) {
 		return nil, err
 	}
 
+	bridgeSettings := container.NetworkSettings.Networks["bridge"]
+	if bridgeSettings == nil {
+		return nil, nil
```
Comment (tiborvass) [inline daemon/container_unix.go]: @calavera @mavenugo this is the line i just changed, it doesnt error out now.

File: daemon/container_unix.go [hunk 5]
```diff
@@ -88,15 +88,25 @@ func (container *Container) setupLinkedContainers() ([]string, error) {
...
+
 	if len(children) > 0 {
 		for linkAlias, child := range children {
 			if !child.IsRunning() {
 				return nil, derr.ErrorCodeLinkNotRunning.WithArgs(child.Name, linkAlias)
 			}
 
+			childBridgeSettings := child.NetworkSettings.Networks["bridge"]
+			if childBridgeSettings == nil {
+				return nil, fmt.Errorf("container %d not attached to default bridge network", child.ID)
```
Comment (tiborvass) [inline daemon/container_unix.go]: here, we do, because child has to be attached to bridge network. Not even sure how this would be possible, but if it is, we should error out.

File: daemon/container_unix.go [hunk 6]
```diff
@@ -583,12 +594,8 @@ func (container *Container) buildSandboxOptions(n libnetwork.Network) ([]libnetw
 
 func isLinkable(child *Container) bool {
 	// A container is linkable only if it belongs to the default network
-	for _, nw := range child.NetworkSettings.Networks {
-		if nw == "bridge" {
-			return true
-		}
-	}
-	return false
+	_, ok := child.NetworkSettings.Networks["bridge"]
```
Comment (tiborvass) [inline daemon/container_unix.go]: @mrjana this is my change after rebasing on top of #17230

File: daemon/inspect.go [hunk 7]
```diff
@@ -151,3 +166,30 @@ func (daemon *Daemon) VolumeInspect(name string) (*types.Volume, error) {
 	}
 	return volumeToAPIType(v), nil
 }
+
+func getBackwardsCompatibleNetworkSettings(settings *network.Settings) *v1p20.NetworkSettings {
```
Comment (mrjana) [inline daemon/inspect.go]: @tiborvass Is this intentional to only show the bridge network settings(if container is connected to default bridge network) in the backward compatible fields? What will be the values of these fields if the container is connected to a non-default network and only to that network? My reading of the code says that these fields will be empty in that case because we have removed the initialization of  backward compatible fields in `container.NetworkSettings`

Comment (tiborvass) [inline daemon/inspect.go]: @mrjana correct. But aren't non-default networks a new thing in 1.9 anyway?

Comment (mrjana) [inline daemon/inspect.go]: Yes, but if some use did  the following:
```
docker run --net=somenetwork -d busybox
docker inspect --format '{{.NetworkSettings.IPAddress}}' <container_id>
```
it will return an empty value. Is that acceptable?
Or are you trying to deprecate the old fields this way? 

P.S: this will affect not just a overlay network but also a regular bridge network which is non-default

Comment (tiborvass) [inline daemon/inspect.go]: @mrjana it shouldn't because `docker inspect` will talk API v1.21. This would only be the case if they did it through the API directly with a version < 1.21. But with that API they can't create new networks anyways.

Comment (tiborvass) [inline daemon/inspect.go]: So if you used the inspect command you described, it will fail because there is no such IPAddress field on API 1.21.

Comment (mrjana) [inline daemon/inspect.go]: @tiborvaas Looks like for the client using v1.21 they don't even see these old fields which means they are deprecated for v1.21. For older clients they will be empty if somebody used a non-default network but those older clients cannot even create a non-default network. So I am good with this. Thanks for the clarification.

**Comment by calavera** [comment]
@tiborvass 

```
docker_cli_links_test.go:140:
    c.Fatal(err)
... Error: failed to inspect container one: Template parsing error: template: :1:18: executing "" at <.NetworkSettings.IPA...>: IPAddress is not a field of struct type *types.NetworkSettings
```

**Comment by tiborvass** [comment]
@calavera fixed

**Comment by mrjana** [comment]
changes LGTM. Let's wait for the CI to become green

**Comment by tiborvass** [comment]
@mrjana CI has issues, please test locally

**Comment by calavera** [comment]
LGTM. We're going to open a PR in docker-py to fix the functional suite.

Merging.

**Comment by tiborvass** [comment]
Ping @dnephin @aanand @shin- @abronan @vieux @aluzzardi this requires an API update.

**Comment by tiborvass** [comment]
@thaJeztah removing changelog, since it's part of the new networking feature which is already in the changelog.
