### PR TITLE
Don’t stop daemon on migration hard failure

### LINKED ISSUE #20147: "graph ID does not exist" after upgrading to Docker 1.10.0
After upgrade from Docker 1.9.1 to 1.10.0 docker daemon fails to start with:

```
DEBU[0000] docker group found. gid: 999                 
DEBU[0000] Server created for HTTP on unix (/var/run/docker.sock) 
DEBU[0000] Using default logging driver json-file       
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] could not get checksum for "11421c362701030998085de69fbef501e4c16f91c2f008d820124808a4ddfe48" with tar-split: "open /var/lib/docker/graph/11421c362701030998085de69fbef501e4c16f91c2f008d820124808a4
ddfe48/tar-data.json.gz: no such file or directory" 
DEBU[0000] could not get checksum for "061ea850f8e9bb47a04edf49c745c94a21dbb1a8bbced6bcd857c5fc699bc9a7" with tar-split: "open /var/lib/docker/graph/061ea850f8e9bb47a04edf49c745c94a21dbb1a8bbced6bcd857c5fc69
9bc9a7/tar-data.json.gz: no such file or directory" 
DEBU[0000] could not get checksum for "139b1e2bbc4a79b9c26243c8e87dade698c0e96968ca27ab11d96b2599def1b9" with tar-split: "open /var/lib/docker/graph/139b1e2bbc4a79b9c26243c8e87dade698c0e96968ca27ab11d96b2599
def1b9/tar-data.json.gz: no such file or directory" 
DEBU[0000] could not get checksum for "16dff810564c38f3197482e0300b4464ef737b1ff1280da8aca28fa4dc7e1d42" with tar-split: "open /var/lib/docker/graph/16dff810564c38f3197482e0300b4464ef737b1ff1280da8aca28fa4dc
7e1d42/tar-data.json.gz: no such file or directory" 
DEBU[0000] could not get checksum for "2103b00b3fdf1d26a86aded36ae73c1c425def0f779a6e69073b3b77377df348" with tar-split: "open /var/lib/docker/graph/2103b00b3fdf1d26a86aded36ae73c1c425def0f779a6e69073b3b7737
7df348/tar-data.json.gz: no such file or directory" 
DEBU[0000] could not get checksum for "29460ac934423a55802fcad24856827050697b4a9f33550bd93c82762fb6db8f" with tar-split: "open /var/lib/docker/graph/29460ac934423a55802fcad24856827050697b4a9f33550bd93c82762f
b6db8f/tar-data.json.gz: no such file or directory" 
DEBU[0000] could not get checksum for "0e57c609ffa9cf52d8e508554c2ca1e9af5a5dea226615ff58c421abfd4622d0" with tar-split: "stat /var/lib/docker/overlay/0e57c609ffa9cf52d8e508554c2ca1e9af5a5dea226615ff58c421ab
fd4622d0: no such file or directory" 
ERRO[0000] could not calculate checksum for "0e57c609ffa9cf52d8e508554c2ca1e9af5a5dea226615ff58c421abfd4622d0", "stat /var/lib/docker/overlay/0e57c609ffa9cf52d8e508554c2ca1e9af5a5dea226615ff58c421abfd4622d0:
 no such file or directory" 
DEBU[0000] layer 0e57c609ffa9cf52d8e508554c2ca1e9af5a5dea226615ff58c421abfd4622d0 took 0.00 seconds 
DEBU[0000] could not get checksum for "2daa80c72053337852233976b180d7aed5bc663c16d752156db428ead492073a" with tar-split: "open /var/lib/docker/graph/2daa80c72053337852233976b180d7aed5bc663c16d752156db428ead4
92073a/tar-data.json.gz: no such file or directory" 
ERRO[0000] could not calculate checksum for "2daa80c72053337852233976b180d7aed5bc663c16d752156db428ead492073a", "stat /var/lib/docker/overlay/2daa80c72053337852233976b180d7aed5bc663c16d752156db428ead492073a:
 no such file or directory" 
DEBU[0000] layer 2daa80c72053337852233976b180d7aed5bc663c16d752156db428ead492073a took 0.00 seconds 
DEBU[0000] could not get checksum for "306f4c89df6c1a547a4956cceeb070d838f5130190db70786ab55fa73ac83d03" with tar-split: "open /var/lib/docker/graph/306f4c89df6c1a547a4956cceeb070d838f5130190db70786ab55fa73a
c83d03/tar-data.json.gz: no such file or directory" 
ERRO[0000] could not calculate checksum for "306f4c89df6c1a547a4956cceeb070d838f5130190db70786ab55fa73ac83d03", "stat /var/lib/docker/overlay/306f4c89df6c1a547a4956cceeb070d838f5130190db70786ab55fa73ac83d03:
 no such file or directory" 

...

ERRO[0000] could not calculate checksum for "a26ec929cf27ba58caeb03672e0df9f20cbba6d3ae4fda4b77142eba38f300c9", "stat /var/lib/docker/overlay/a26ec929cf27ba58caeb03672e0df9f20cbba6d3ae4fda4b77142eba38f300c9:
 no such file or directory" 
DEBU[0000] layer a26ec929cf27ba58caeb03672e0df9f20cbba6d3ae4fda4b77142eba38f300c9 took 0.01 seconds 
ERRO[0000] could not calculate checksum for "9c33ab3dcc5c4e77ddfe08514232726758946c99a54f0609b9cf2919a16cacf8", "stat /var/lib/docker/overlay/9c33ab3dcc5c4e77ddfe08514232726758946c99a54f0609b9cf2919a16cacf8:
 no such file or directory" 
DEBU[0000] layer 9c33ab3dcc5c4e77ddfe08514232726758946c99a54f0609b9cf2919a16cacf8 took 0.01 seconds 
ERRO[0000] migration failed for f0dde87450ec8236a64aebd3e8b499fe2772fca5e837ecbfa97bd8ae380c605e, err: open /var/lib/docker/graph/f0dde87450ec8236a64aebd3e8b499fe2772fca5e837ecbfa97bd8ae380c605e/.migration-d
iffid: no such file or directory 
ERRO[0000] migration failed for 76b658ecb5644a4aca23b35de695803ad2e223da087d4f8015016021bd970169, err: open /var/lib/docker/graph/f0dde87450ec8236a64aebd3e8b499fe2772fca5e837ecbfa97bd8ae380c605e/.migration-d
iffid: no such file or directory 
ERRO[0000] migration failed for 4faa69f72743ce3a18508e840ff84598952fc05bd1de5fd54c6bc0f8ca835884, err: open /var/lib/docker/graph/f0dde87450ec8236a64aebd3e8b499fe2772fca5e837ecbfa97bd8ae380c605e/.migration-d
iffid: no such file or directory 
ERRO[0000] migration failed for 2103b00b3fdf1d26a86aded36ae73c1c425def0f779a6e69073b3b77377df348, err: open /var/lib/docker/graph/f0dde87450ec8236a64aebd3e8b499fe2772fca5e837ecbfa97bd8ae380c605e/.migration-d
iffid: no such file or directory 
ERRO[0000] migration failed for 51d14176e2627d70c2b15c7eb383119400bd095f2a866963c9daba104881fb5e, err: open /var/lib/docker/graph/f0dde87450ec8236a64aebd3e8b499fe2772fca5e837ecbfa97bd8ae380c605e/.migration-d
iffid: no such file or directory 
ERRO[0000] migration failed for 061ea850f8e9bb47a04edf49c745c94a21dbb1a8bbced6bcd857c5fc699bc9a7, err: open /var/lib/docker/graph/f0dde87450ec8236a64aebd3e8b499fe2772fca5e837ecbfa97bd8ae380c605e/.migration-d
iffid: no such file or directory 
ERRO[0000] migration failed for 72893ec31c4c6e0f7cbaa186c60fb624721ef4137aeeac56caf83bb2745dbc63, err: open /var/lib/docker/graph/72893ec31c4c6e0f7cbaa186c60fb624721ef4137aeeac56caf83bb2745dbc63/.migration-d
iffid: no such file or directory 

...

ERRO[0000] migration failed for b20334cbcde19e825e48cec618a8be745e253e3c59df013ff1cf8eedf4c382e3, err: open /var/lib/docker/graph/83e4dde6b9cfddf46b75a07ec8d65ad87a748b98cf27de7d5b3298c1f3455ae4/.migration-d
iffid: no such file or directory 
ERRO[0000] migration failed for 139b1e2bbc4a79b9c26243c8e87dade698c0e96968ca27ab11d96b2599def1b9, err: open /var/lib/docker/graph/83e4dde6b9cfddf46b75a07ec8d65ad87a748b98cf27de7d5b3298c1f3455ae4/.migration-d
iffid: no such file or directory 
ERRO[0000] migration failed for 9c33ab3dcc5c4e77ddfe08514232726758946c99a54f0609b9cf2919a16cacf8, err: open /var/lib/docker/graph/83e4dde6b9cfddf46b75a07ec8d65ad87a748b98cf27de7d5b3298c1f3455ae4/.migration-d
iffid: no such file or directory 
ERRO[0000] migration failed for f9dc6fc192ce12a2a77fa13624554795af97e8b5031ca9e31fc2e9e2a85c283c, err: open /var/lib/docker/graph/83e4dde6b9cfddf46b75a07ec8d65ad87a748b98cf27de7d5b3298c1f3455ae4/.migration-d
iffid: no such file or directory 
ERRO[0000] migrate container error: open /var/lib/docker/containers/07369a90b03c3a2abf4f567b7b51a22eab45ec6b00d7320b6843a0d52abc839b/config.json: no such file or directory 
DEBU[0000] Cleaning up old shm/mqueue mounts: start.    
FATA[0000] Error starting daemon: graph ID does not exist
```
(complete log: https://gist.github.com/rutsky/f8ed4e04b79063f1c7db)

First start of Docker after upgrading to 1.10.0 were terminated several times using `service stop docker`/`service start docker`.

I'm using Ubuntu 14.04 64-bit, with Linux 4.2.0 and `--storage-driver=overlay`.
Docker version: `Docker version 1.10.0, build 590d5108`
Docker info: unavailable (daemon fails to start)

Any idea why this happens and how this can be fixed?

### PR DESCRIPTION
**Pull request by tonistiigi**
Also changes missing storage layer for container
RWLayer to a soft failure.

Fixes #20147 

Soft failure: migration of image/container is skipped
Hard failure: migration stops

Signed-off-by: Tonis Tiigi tonistiigi@gmail.com

### CODE REVIEW

File: daemon/daemon.go [hunk 1]
```diff
@@ -748,7 +748,7 @@ func NewDaemon(config *Config, registryService *registry.Service) (daemon *Daemo
 
 	migrationStart := time.Now()
 	if err := v1.Migrate(config.Root, graphDriver, d.layerStore, d.imageStore, referenceStore, distributionMetadataStore); err != nil {
-		return nil, err
+		logrus.Errorf("Graph migration failed: %q. Your old graph data was found to be too inconsitent for upgrading to content-addressable storage. Some of the old data was probably not upgraded. We recommend starting over with a clean storage directory if possible.", err)
```
Comment (aaronlehmann) [inline daemon/daemon.go]: `s/inconsitent/inconsistent/`

**Comment by cpuguy83** [comment]
LGTM

**Comment by calavera** [comment]
LGTM

**Comment by dmcgowan** [comment]
LGTM
