### PR TITLE
image/save: Derive Descriptor from actual tar archive

### LINKED ISSUE #47072: [v25 rc.2] `docker save` produces OCI layer descriptors with wrong blob size
### Description

In Docker v25.0.0-rc.2, `docker save` produces OCI layer descriptors with wrong blob size

### Reproduce

```console
$ cat Dockerfile
FROM busybox
RUN touch /hello

$ docker build -t foo .

$ docker save foo | tar x

$ jq . < index.json
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.index.v1+json",
  "manifests": [
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:b1b61595abd3588ec527b85f4bd2e5d629c7e37c50cee2cf6fe7813e9cdfc442",
      "size": 602,
      "annotations": {
        "io.containerd.image.name": "docker.io/library/foo:latest",
        "org.opencontainers.image.ref.name": "latest"
      },
      "platform": {
        "architecture": "amd64",
        "os": "linux"
      }
    }
  ]
}

$ jq . < blobs/sha256/b1b61595abd3588ec527b85f4bd2e5d629c7e37c50cee2cf6fe7813e9cdfc442 
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.manifest.v1+json",
  "config": {
    "mediaType": "application/vnd.oci.image.config.v1+json",
    "digest": "sha256:50b221c61002bfcb637ca771adc59472159032633750dfb372d65917fc784c08",
    "size": 797,
    "platform": {
      "architecture": "amd64",
      "os": "linux"
    }
  },
  "layers": [
    {
      "mediaType": "application/vnd.oci.image.layer.v1.tar",
      "digest": "sha256:82ae998286b2bba64ce571578647adcabef93d53867748d6046cc844ff193a83",
      "size": 4261566
    },
    {
      "mediaType": "application/vnd.oci.image.layer.v1.tar",
      "digest": "sha256:d9c12d943195f3cc0cbbf7223bc0b4cabe8be8655ca072c7bee9de45b3021f5b",
      "size": 4261566
    }
  ]
}

$  ls -l blobs/sha256/82ae998286b2bba64ce571578647adcabef93d53867748d6046cc844ff193a83 blobs/sha256/d9c12d943195f3cc0cbbf7223bc0b4cabe8be8655ca072c7bee9de45b3021f5b 
-rw-r--r--    1 root     root       4492288 Jan 13 07:04 blobs/sha256/82ae998286b2bba64ce571578647adcabef93d53867748d6046cc844ff193a83
-rw-r--r--    1 root     root          3072 Jan 13 07:04 blobs/sha256/d9c12d943195f3cc0cbbf7223bc0b4cabe8be8655ca072c7bee9de45b3021f5b
```

### Expected behavior

The layer blob size must be accurate

### docker version

```bash
Client:
 Version:           25.0.0-rc.2
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        1fc6ef9
 Built:             Fri Jan 12 21:50:24 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.0-rc.2
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       608238e
  Built:            Fri Jan 12 21:26:18 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.12
  GitCommit:        71909c1814c544ac47ab91d2e8b84718e517bb99
 runc:
  Version:          1.1.11
  GitCommit:        v1.1.11-0-g4bccb38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    25.0.0-rc.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/local/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.0
    Path:     /usr/local/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 25.0.0-rc.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 71909c1814c544ac47ab91d2e8b84718e517bb99
 runc version: v1.1.11-0-g4bccb38
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-91-generic
 Operating System: Alpine Linux v3.19 (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.814GiB
 Name: 12dc4511aa27
 ID: 4cd0ff22-572c-4bee-8cf1-265e4769fc04
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by vvoland**
- fixes: https://github.com/moby/moby/issues/47072
- follow up to: https://github.com/moby/moby/pull/47068

Graphdriver layer size is the sum of the individual files size (like `du -s`), not the tar archive (`tar | wc -c`). The layer descriptor in OCI manifest specifies the byte size of the tar archive. Use the total bytes read returned by `io.Copy` to populate the `Size` field.

Also set the digest to the actual digest of the tar archive.

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: image/tarexport/save.go [hunk 1]
```diff
@@ -38,6 +38,7 @@ type saveSession struct {
 	images      map[image.ID]*imageDescriptor
 	savedLayers map[string]struct{}
 	diffIDPaths map[layer.DiffID]string // cache every diffID blob to avoid duplicates
+	diffIDDescs map[layer.DiffID]distribution.Descriptor
```
Comment (rumpl) [inline image/tarexport/save.go:41]: I'm kinda failing to understand why we need this map

Comment (vvoland) [reply image/tarexport/save.go:41]: We need it because `saveLayer` [doesn't read and save the tar archive if it was alread saved during this session](https://github.com/moby/moby/blob/33b5a5813b805aaba28c06ee1a8aa5b1f2435a1d/image/tarexport/save.go#L485).

So in this case we need to remember the generated descriptor and return it for any subsequent calls.

File: image/tarexport/save.go [hunk 2]
```diff
@@ -516,20 +522,21 @@ func (s *saveSession) saveLayer(id layer.ChainID, legacyImg image.V1Image, creat
 		}
 
 		s.diffIDPaths[l.DiffID()] = layerPath
-		s.savedLayers[legacyImg.ID] = struct{}{}
```
Comment (rumpl) [inline image/tarexport/save.go:519]: We don't need `savedLayers` any more?

File: image/tarexport/save.go (hunk 1 above)
Comment (rumpl) [reply image/tarexport/save.go:41]: Gotcha!

File: image/tarexport/save.go (hunk 2 above)
Comment (vvoland) [reply image/tarexport/save.go:519]: Whoops, restored. I didn't intend to remove it in this PR (it _could_ be deleted though, but that's out of scope here).

Comment (rumpl) [reply image/tarexport/save.go:519]: Hm, maybe we _do_ want to remove the saved layers, there is [this test](https://github.com/moby/moby/blob/33b5a5813b805aaba28c06ee1a8aa5b1f2435a1d/image/tarexport/save.go#L454) on top, don't we want to test `diffIDDescs` at the beginning and return that desc if it exists? Right now it will return an empty desc for already saved layers

Comment (vvoland) [reply image/tarexport/save.go:519]: Removed unused maps and refactored the function to better distinguish between saved image (Config) and saved layer (diff tar archive).

File: image/tarexport/save.go [hunk 3]
```diff
@@ -36,8 +38,8 @@ type saveSession struct {
 	*tarexporter
 	outDir      string
 	images      map[image.ID]*imageDescriptor
-	savedLayers map[string]struct{}
-	diffIDPaths map[layer.DiffID]string // cache every diffID blob to avoid duplicates
+	savedLayers map[layer.DiffID]distribution.Descriptor
+	savedImages map[string]struct{}
```
Comment (rumpl) [inline image/tarexport/save.go:42]: nit: `savedImages` is used in `saveConfig`, you might want to give these the same name

**Review by rumpl — APPROVED** [review]

File: image/tarexport/save.go (hunk 3 above)
Comment (vvoland) [reply image/tarexport/save.go]: Done

**Comment by thaJeztah** [comment]
Discussed this one on slack; this PR fixes the issue that was reported; most of the code changes are "moving" code, and this should have no direct impact on consumers of the "non-OCI" (legacy layout).


Let me bring this one in in to fix the regression 👍
