### PR TITLE
Devmapper fixes for cookie generation and error reporting (fixes  #33050)

### LINKED ISSUE #33050: Segmentation Fault pulling image with direct-lvm in dm_task_run
**Description**

**Steps to reproduce the issue:**
1. Install Docker 17.04
2. Install Gitlab Runner using the `docker` backend
3. See segmentation faults when running builds

**Describe the results you received:**

```
atal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7fbb0000001d pc=0x7fbbcc088b03]
runtime stack:
runtime.throw(0x190e239, 0x2a)
        /usr/lib/go/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
        /usr/lib/go/src/runtime/signal_unix.go:274 +0x2db
goroutine 1795 [syscall, locked to thread]:
runtime.cgocall(0x14ade40, 0xc421766b60, 0x190aec0)
        /usr/lib/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc421766b20 sp=0xc421766ae0
github.com/docker/docker/pkg/devicemapper._C2func_dm_task_run(0x7fbbb4029af0, 0x7fbb00000000, 0x0, 0x0)
        github.com/docker/docker/pkg/devicemapper/_obj/_cgo_gotypes.go:95 +0x68 fp=0xc421766b60 sp=0xc421766b20
github.com/docker/docker/pkg/devicemapper.dmTaskRunFct.func1(0x7fbbb4029af0, 0xc4207e25d0, 0xc421766bf8, 0x18)
        /build/docker/src/docker/.gopath/src/github.com/docker/docker/pkg/devicemapper/devmapper_wrapper.go:96 +0x60 fp=0xc421766b98 sp=0xc421766b60
github.com/docker/docker/pkg/devicemapper.dmTaskRunFct(0x7fbbb4029af0, 0xc4207e25a0)
        /build/docker/src/docker/.gopath/src/github.com/docker/docker/pkg/devicemapper/devmapper_wrapper.go:96 +0x2b fp=0xc421766bc8 sp=0xc421766b98
github.com/docker/docker/pkg/devicemapper.(*Task).run(0xc4202fa3b8, 0x19477f8, 0xc420cb6ea0)
        /build/docker/src/docker/.gopath/src/github.com/docker/docker/pkg/devicemapper/devmapper.go:155 +0x35 fp=0xc421766be8 sp=0xc421766bc8
github.com/docker/docker/pkg/devicemapper.activateDevice(0xc4208f93e0, 0x1b, 0xc421951720, 0x50, 0x150, 0x280000000, 0x0, 0x0, 0x0, 0x0)
        /build/docker/src/docker/.gopath/src/github.com/docker/docker/pkg/devicemapper/devmapper.go:767 +0x4ad fp=0xc421766d20 sp=0xc421766be8
github.com/docker/docker/pkg/devicemapper.ActivateDevice(0xc4208f93e0, 0x1b, 0xc421951720, 0x50, 0x150, 0x280000000, 0x1b, 0xc420949520)
        /build/docker/src/docker/.gopath/src/github.com/docker/docker/pkg/devicemapper/devmapper.go:732 +0x79 fp=0xc421766d80 sp=0xc421766d20
github.com/docker/docker/daemon/graphdriver/devmapper.(*DeviceSet).activateDeviceIfNeeded(0xc4205056c0, 0xc420ecc780, 0xc420505600, 0xc420ecc780, 0x0)
        /build/docker/src/docker/.gopath/src/github.com/docker/docker/daemon/graphdriver/devmapper/deviceset.go:536 +0x277 fp=0xc421766e30 sp=0xc421766d80
github.com/docker/docker/daemon/graphdriver/devmapper.(*DeviceSet).MountDevice(0xc4205056c0, 0xc422331300, 0x40, 0xc420365880, 0x61, 0x0, 0x0, 0x0, 0x0)
        /build/docker/src/docker/.gopath/src/github.com/docker/docker/daemon/graphdriver/devmapper/deviceset.go:2349 +0x156 fp=0xc421766f80 sp=0xc421766e30
github.com/docker/docker/daemon/graphdriver/devmapper.(*Driver).Get(0xc420216600, 0xc422331300, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /build/docker/src/docker/.gopath/src/github.com/docker/docker/daemon/graphdriver/devmapper/driver.go:197 +0x40d fp=0xc421767130 sp=0xc421766f80
github.com/docker/docker/daemon/graphdriver.(*NaiveDiffDriver).Get(0xc4204d0380, 0xc422331300, 0x40, 0x0, 0x0, 0x414c62, 0xc4219d57a0, 0x30, 0x28)
        <autogenerated>:30 +0x75 fp=0xc421767188 sp=0xc421767130
github.com/docker/docker/layer.(*referencedRWLayer).Mount(0xc420126e80, 0x0, 0x0, 0xc4219d57a0, 0x0, 0x0, 0x0)
        /build/docker/src/docker/.gopath/src/github.com/docker/docker/layer/mounted_layer.go:92 +0x67 fp=0xc4217671e0 sp=0xc421767188
github.com/docker/docker/daemon.(*Daemon).Mount(0xc420306800, 0xc420f7e400, 0xc4217672f0, 0xc420152780)
        /build/docker/src/docker/.gopath/src/github.com/docker/docker/daemon/daemon.go:851 +0x61 fp=0xc4217672c0 sp=0xc4217671e0
github.com/docker/docker/daemon.(*Daemon).conditionalMountOnStart(0xc420306800, 0xc420f7e400, 0xc4217675f0, 0xc420f7e400)
        /build/docker/src/docker/.gopath/src/github.com/docker/docker/daemon/daemon_unix.go:1146 +0x35 fp=0xc4217672f0 sp=0xc4217672c0
github.com/docker/docker/daemon.(*Daemon).containerStart(0xc420306800, 0xc420f7e400, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0)
        /build/docker/src/docker/.gopath/src/github.com/docker/docker/daemon/start.go:136 +0x1c8 fp=0xc4217675b8 sp=0xc4217672f0
github.com/docker/docker/daemon.(*Daemon).ContainerStart(0xc420306800, 0xc420224477, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4154b8, 0x10)
        /build/docker/src/docker/.gopath/src/github.com/docker/docker/daemon/start.go:86 +0x195 fp=0xc421767678 sp=0xc4217675b8
github.com/docker/docker/api/server/router/container.(*containerRouter).postContainersStart(0xc420dd2100, 0x7fbbccafc0d0, 0xc4219d4180, 0x2460aa0, 0xc421600ee0, 0xc4229ac100, 0xc4219d4090, 0x18c5356, 0x5)
        /build/docker/src/docker/.gopath/src/github.com/docker/docker/api/server/router/container/container_routes.go:161 +0x268 fp=0xc421767720 sp=0xc421767678
github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.postContainersStart)-fm(0x7fbbccafc0d0, 0xc4219d4180, 0x2460aa0, 0xc421600ee0, 0xc4229ac100, 0xc4219d4090, 0x7fbbccafc0d0, 0xc4219d4180)
        /build/docker/src/docker/.gopath/src/github.com/docker/docker/api/server/router/container/container.go:60 +0x69 fp=0xc421767778 sp=0xc421767720
github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1(0x7fbbccafc0d0, 0xc4219d4180, 0x2460aa0, 0xc421600ee0, 0xc4229ac100, 0xc4219d4090, 0x7fbbccafc0d0, 0xc4219d4180)
        /build/docker/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware/experimental.go:27 +0xd8 fp=0xc4217677e0 sp=0xc421767778
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x7fbbccafc0d0, 0xc4219d4150, 0x2460aa0, 0xc421600ee0, 0xc4229ac100, 0xc4219d4090, 0xc4217679f0, 0x42f476)
        /build/docker/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware/version.go:48 +0x55d fp=0xc421767908 sp=0xc4217677e0
github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1(0x7fbbccafc0d0, 0xc4219d4150, 0x2460aa0, 0xc421600ee0, 0xc4229ac100, 0xc4219d4090, 0x7fbbccafc0d0, 0xc4219d4150)
        /build/docker/src/docker/.gopath/src/github.com/docker/docker/pkg/authorization/middleware.go:43 +0x7bf fp=0xc421767ab8 sp=0xc421767908
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x2460aa0, 0xc421600ee0, 0xc4229ac100)
        /build/docker/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:140 +0x220 fp=0xc421767bc0 sp=0xc421767ab8
net/http.HandlerFunc.ServeHTTP(0xc420e5ae60, 0x2460aa0, 0xc421600ee0, 0xc4229ac100)
        /usr/lib/go/src/net/http/server.go:1942 +0x44 fp=0xc421767be8 sp=0xc421767bc0
github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420152640, 0x2460aa0, 0xc421600ee0, 0xc4229ac100)
        /build/docker/src/docker/.gopath/src/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:103 +0x255 fp=0xc421767cd8 sp=0xc421767be8
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc42108ba00, 0x2460aa0, 0xc421600ee0, 0xc4229ac100)
        /build/docker/src/docker/.gopath/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x70 fp=0xc421767d10 sp=0xc421767cd8
net/http.serverHandler.ServeHTTP(0xc4200af810, 0x2460aa0, 0xc421600ee0, 0xc4229ac100)
        /usr/lib/go/src/net/http/server.go:2568 +0x92 fp=0xc421767d58 sp=0xc421767d10
net/http.(*conn).serve(0xc420ff32c0, 0x24625e0, 0xc421f75480)
        /usr/lib/go/src/net/http/server.go:1825 +0x612 fp=0xc421767fc8 sp=0xc421767d58
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc421767fd0 sp=0xc421767fc8
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:2668 +0x2ce
goroutine 1 [chan receive, 92 minutes]:
main.(*DaemonCli).start(0xc420175140, 0x0, 0x18e68a1, 0x17, 0xc42006f400, 0xc420064eb0, 0xc4204885a0, 0x0, 0x0)
        /build/docker/src/docker/.gopath/src/github.com/docker/docker/cmd/dockerd/daemon.go:330 +0x18ba
main.runDaemon(0x0, 0x18e68a1, 0x17, 0xc42006f400, 0xc420064eb0, 0xc4204885a0, 0x2, 0x0)
        /build/docker/src/docker/.gopath/src/github.com/docker/docker/cmd/dockerd/docker.go:86 +0x8c
main.newDaemonCommand.func1(0xc42009e480, 0xc420124ea0, 0x0, 0x2, 0x0, 0x0)
        /build/docker/src/docker/.gopath/src/github.com/docker/docker/cmd/dockerd/docker.go:42 +0x6f
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0xc42009e480, 0xc420010250, 0x2, 0x2, 0xc42009e480, 0xc420010250)
        /build/docker/src/docker/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:646 +0x44e
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42009e480, 0x16ac500, 0x1, 0xc4201218a0)
        /build/docker/src/docker/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:742 +0x349
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42009e480, 0xc4201218a0, 0x0)
        /build/docker/src/docker/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:695 +0x2b
main.main()
        /build/docker/src/docker/.gopath/src/github.com/docker/docker/cmd/dockerd/docker.go:106 +0xe6
```

**Describe the results you expected:**

Clean running builds

**Additional information you deem important (e.g. issue happens only occasionally):**

Seems that the Go code for pulling an image is crashing when GitLab runner pulls an image. It doesn't occur every time. There is [gitlab-org/gitlab-ci-multi-runner#2408](https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/2408) bug on GitLab Runner

**Output of `docker version`:**

```
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.8
 Git commit:   4845c567eb
 Built:        Sat Apr  8 18:55:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.8
 Git commit:   4845c567eb
 Built:        Sat Apr  8 18:55:45 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.8
 Git commit:   4845c567eb
 Built:        Sat Apr  8 18:55:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.8
 Git commit:   4845c567eb
 Built:        Sat Apr  8 18:55:45 2017
 OS/Arch:      linux/amd64
 Experimental: false
[matt-clarkson@tower ~]$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.04.0-ce
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 20.45MB
 Data Space Total: 254.5GB
 Data Space Available: 254.5GB
 Metadata Space Used: 323.6kB
 Metadata Space Total: 2.676GB
 Metadata Space Available: 2.676GB
 Thin Pool Minimum Free Space: 25.45GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.139 (2017-04-13)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: 
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.10.13-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.751GiB
Name: tower
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

 * Arch Linux x86_64
 * Tested on both Intel NUC and Intel Xeon server

### PR DESCRIPTION
**Pull request by nhorman**
**- In attempting to run openshift on power I continually ran into the segmentation violation described in issue 33050**

**- Just run openshift on power.  Normal operation was enough to quickly trigger a set of lvm operations that resulted in the crash mentioned in issue 33050**

**- No exact steps, typically booting openshift on power was enough to trigger the error**

**- Ensure that cookie generation for dm_task_run is unique, and error reporting is robust**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @rhvgoyal @cpuguy83 PTAL

File: pkg/devicemapper/devmapper.go [hunk 1]
```diff
@@ -257,7 +257,7 @@ func (t *Task) getNextTarget(next unsafe.Pointer) (nextPtr unsafe.Pointer, start
 // UdevWait waits for any processes that are waiting for udev to complete the specified cookie.
 func UdevWait(cookie *uint) error {
 	if res := DmUdevWait(*cookie); res != 1 {
-		logrus.Debugf("devicemapper: Failed to wait on udev cookie %d", *cookie)
+		logrus.Debugf("devicemapper: Failed to wait on udev cookie %d, %d", *cookie, res)
```
Comment (rhvgoyal) [inline pkg/devicemapper/devmapper.go]: Neil, curious if libdevmapper is returning something useful in res. If yes, sure, logging that might help.

Also will it make sense to log this as either warning or error message instead of debug message?

**Comment by rhvgoyal** [comment]
Neil, I don't understand the second patch. Given cookie variable is on stack and we call UdevWait() in same function, how it will be reused before UdevWait() finishes.

**Comment by rhvgoyal** [comment]
@nhorman So these patches fix the issue you were facing?

File: pkg/devicemapper/devmapper.go [hunk 2]
```diff
@@ -342,7 +341,7 @@ func RemoveDevice(name string) error {
 		return fmt.Errorf("devicemapper: Error running RemoveDevice %s", err)
 	}
 
-	return nil
+	return UdevWait(cookie)
```
Comment (rhvgoyal) [inline pkg/devicemapper/devmapper.go]: Capturing error code from UdevWait() makes sense. I think you could still use defer UdevWait() but to capture error you will have to use named error variable and in deferred function set that named error variable from return of UdeWait(). That means this will require a wrapper around UdevWait().

Docker developers typically like to use "defer" instead over inline calls. But I am fine with either.

**Comment by rhvgoyal** [comment]
So what's the root cause of the problem. Capturing return code of UdevWait() can't be problem as panic is happening before that in dm_task_run(). So allocating cookie on heap (instead of stack) fixed the issue. If yes, its not clear how.

File: pkg/devicemapper/devmapper.go (hunk 2 above)
Comment (nhorman) [inline pkg/devicemapper/devmapper.go]: I understand that docker developers like to use defer, but I assert that theres no need for it here.  If the goal is to capture any error from UdevWait and return it to the calling function, then I'm not sure why its worth blocking on a deferred function, when its more direct to just wait for the completion inline.

**Comment by nhorman** [comment]
The problem is that golang doesn't guarantee that deferred statements will be run in the same context as the function itself (i.e. it might be a different thread).  That means that the stack might return and reuse a stack address for a new cookie.  And yes, this has solved the problem for me.  Whereas openshift was crashing on boot freqently for me previously, with this patch set, it stays up consistently now

**Comment by rhvgoyal** [comment]
@nhorman So this means that one can not pass address of a variable on stack as parameter to a deferred function?

**Comment by rhvgoyal** [comment]
When I do search, I see some examples where people talk about passing stack pointers to deferred functions.

http://stackoverflow.com/questions/28893586/golang-defer-clarification

**Comment by rhvgoyal** [comment]
Anyway, if having cookie on heap instead of stack fixes the issue, I am fine with that. 

Only nit I have is that may be we can continue to use defer for udevwait and use named error values and update err from deferred function?

**Comment by rhvgoyal** [comment]
Hopefully that does not change function signature and any existing pkg users are not broken.

**Comment by rhvgoyal** [comment]
Also with existing patches, if you have inlined all UdevWait() and not using defer, then there is no need to move cookie to heap?

So either we need to move cookie to heap and continue to use deferred UdevWait() and named error variable. Or we need to inline UdevWait() and continue to use cookie on stack. Looks like we will not need both?

**Comment by cpuguy83** [comment]
Should we run with `runtime.LockOSThread()`?

**Comment by rhvgoyal** [comment]
Read quickly about LockOSThread(). Looks like moving cookie to heap will result in less complex code. So I would rather move cookie to heap instead.

File: pkg/devicemapper/devmapper.go (hunk 2 above)
Comment (rhvgoyal) [inline pkg/devicemapper/devmapper.go]: If you are waiting inline for UdevWait(), do we still need to move cookie to heap? Looks like stack will still be around as we are waiting for UdevWait() inline.

**Comment by nhorman** [comment]
agreed

**Comment by nhorman** [comment]
regarding the need for both changes, in thinking about it, no likely both are not needed for the sake of the bug fix.  Given the choice, I would suggest the movement of UdevWait, as it allows the capture and return of the error while also making the cookie unique.  If we move the cookie value to the heap, then we don't get the error capture.  Shall I respin the patch and open a new pull request?

**Comment by rhvgoyal** [comment]
@nhorman Thinking more about it. Given this subtle behavior that passing pointers to variables on stack to deferred function can lead to interesting crashes, I think moving cookie to heap makes lot of sense. I am afraid that somebody will commit a patch sometime saying hey why not make UdevWait() as defer function and break cookie stuff again. It will at-least reduce the possibility of somebody breaking it again.

To capture return UdevWait() return code is important too. So we could either go with your existing implementation of using inline UdevWait() or use deferred UdevWait() with named error variable. I am fine with any. (Until and unless docker developers think otherwise).  

For me, I care more about making sure future code changes don't introduce stack variable issue again. So I will have another close at the existing PR again and see if I can spot anything else.

**Comment by rhvgoyal** [comment]
LGTM

I think I am fine with this PR as it is. Thanks Neil.

**Comment by thaJeztah** [comment]
Thank you for reviewing @rhvgoyal !

@cpuguy83 LGTY?

**Review by cpuguy83 — APPROVED** [review]
LGTM

File: pkg/devicemapper/devmapper.go (hunk 1 above)
Comment (nhorman) [inline pkg/devicemapper/devmapper.go]: I'm not really sure what the change your suggesting here does

Comment (cpuguy83) [inline pkg/devicemapper/devmapper.go]: It just formats the log better.

**Review by dmcgowan — APPROVED** [review]
LGTM

**Comment by rhvgoyal** [comment]
@runcom we will need these fixes.
