### PR TITLE
Make Docker automatically update hostname for Swarm node

### LINKED ISSUE #27173: Swarm mode reports invalid hostname if hostname is changed after Docker daemon is started
**Description**

If the hostname of a machine is changed before Docker is started and after swarm mode is enabled, Swarm mode seems to report the old (invalid) hostname.

**Steps to reproduce the issue:**

You dupe this fairly simply with `docker-machine` and two node cluster (probably even with one really).

First `create`.  Machine sets host name according to machine name automatically.  And Docker is started on these machines of course.

Then change host name on created machines.

Then start swarm init / join.

Here's a little script you can use to dupe if you want.  You should see that `hostname` command will report the correct set hostname when executed after the middle steps to set it FWIW.

``` console
docker-machine create -d virtualbox manager
docker-machine create -d virtualbox worker
docker-machine ssh worker 'sudo hostname baz && sudo sed -i "s/worker/baz/g" /etc/hosts && echo baz | sudo tee /etc/hostname'
docker-machine ssh manager 'sudo hostname quux && sudo sed -i "s/manager/quux/g" /etc/hosts && echo quux | sudo tee /etc/hostname'
docker-machine ssh manager docker swarm init --advertise-addr eth1
docker-machine ssh worker docker swarm join --token $(docker-machine ssh manager docker swarm join-token -q worker) $(docker-machine ip manager):2377
docker-machine ssh manager docker node ls
```

Cool, the hostname was set before swarm mode was initiated, so the new hostnames should be propagated when the swarm is started, right?

`docker node ls` reports the old values though.  These should say `quux` and `baz` for hostname.

```
$ docker-machine ssh manager docker node ls
ID                           HOSTNAME  STATUS  AVAILABILITY  MANAGER STATUS
3of2on83v5orfuozfqpnq00ul *  manager   Ready   Active        Leader
5usitwuan5g1n7l8drx15kue9    worker    Ready   Active
```

**Describe the results you received:**

Hostname is not reported correctly.

**Describe the results you expected:**

Hostname is reported correctly.

**Additional info**

If Docker daemon is restarted _before_ the Swarm initialization steps it seems to report the hostnames correctly.

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

(I seem to have duped this with `1.12.2-rc2` as well though)

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null bridge host
Swarm: active
 NodeID: 3of2on83v5orfuozfqpnq00ul
 Is Manager: true
 ClusterID: eqisp01jd77ahunfx80asdwez
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.99.105
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.17-boot2docker
Operating System: Boot2Docker 1.12.1 (TCL 7.2); HEAD : ef7d0b4 - Thu Aug 18 21:18:06 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: quux
ID: M7Q6:DORB:VZZB:WCJO:LVIG:247Y:BQCV:FZGH:VRMN:Y77H:XKA5:PECS
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 32
 Goroutines: 124
 System Time: 2016-10-05T23:37:30.070842443Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8
```

**Cute animal photo**

Ladies and gentlemen, I present to you, the Hostname Corgi.

image

Thanks.

cc @aluzzardi @stevvooe @aaronlehmann FYI

### PR DESCRIPTION
**Pull request by nishanttotla**
Signed-off-by: Nishant Totla <nishanttotla@gmail.com>

**- What I did**
Fix #27173

**- How I did it**
The Swarm node config (`swarmnode.Config`) sets hostname and passes it to the node object, which in turn initializes hostname for the agent object. SwarmKit design makes sure that agent hostname always overrides what is reported by the machine. Currently, since the agent hostname is set at the time of node creation, any updates (reported in the future) are automatically discarded.

This PR ensures that the agent hostname is not set by Docker, and instead picked up from the hostname reported by the machine. As a result, SwarmKit's dynamic node update ticker picks up hostname changes and reports the correct hostname in `docker node ls` and `docker node inspect`.

**- How to verify it**
Start a single node Swarm, and check the hostname reported as part of `docker node ls`. Then change the machine hostname, and run `docker node ls` again.

**- Description for the changelog**
Automatically update Swarm node name when machine hostname changes

### CODE REVIEW

**Comment by nishanttotla** [comment]
@stevvooe as you mentioned in earlier discussion, this targets the root cause of the problem, rather than break SwarmKit abstraction.

cc @aaronlehmann @nathanleclaire

File: daemon/cluster/noderunner.go [hunk 1]
```diff
@@ -95,7 +95,7 @@ func (n *nodeRunner) start(conf nodeStartConfig) error {
 	}
 
 	swarmnodeConfig := swarmnode.Config{
-		Hostname:           n.cluster.config.Name,
+		Hostname:           "",
```
Comment (thaJeztah) [inline daemon/cluster/noderunner.go]: Maybe this line can be removed entirely? (strings default to `""`)

**Comment by stevvooe** [comment]
LGTM

**Comment by aaronlehmann** [comment]
Should we remove the `Hostname` field completely?

**Comment by nishanttotla** [comment]
@aaronlehmann @thaJeztah removed the field, and added a comment.

**Comment by aaronlehmann** [comment]
What I meant to ask was whether the `Hostname` field should be removed upstream, in swarmkit. If Docker shouldn't be using it, I'm not sure there's any point to having it.

**Comment by nishanttotla** [comment]
@aaronlehmann in Docker Swarm mode, this field is not useful at all, but one reason to keep it is that it might be useful in the future, as described in https://github.com/docker/swarmkit/pull/1687#issuecomment-255899323

**Comment by aaronlehmann** [comment]
LGTM
