### PR TITLE
Fix missing Init Binary in docker info output

### LINKED ISSUE #32314: Init Binary no longer set in output of docker info
I noticed that `Init Binary` is no longer set in the output of `docker info` in docker 17.04 (and master).

This issue was introduced in https://github.com/docker/docker/pull/29673, which changes https://github.com/docker/docker/commit/db63f9370e26d725357c703cbaf9ab63cc7b6d0a#diff-d188edf2153ada0e6eee0a51db09b1fcL88 to https://github.com/docker/docker/commit/db63f9370e26d725357c703cbaf9ab63cc7b6d0a#diff-49f3d9765e66ddfa37dc814625477699R69, as a result, causing `v.InitBinary` to be empty (https://github.com/docker/docker/blob/d9c4261964fc4c93d2e34de650a33936ebbf7f9c/daemon/info_unix.go#L28)

/cc @vdemeester

### PR DESCRIPTION
**Pull request by darkowlzz**
- Moved DefaultInitBinary from daemon/daemon.go to
daemon/config/config.go since it's a daemon config and is referred in
config package files.
- Added condition in GetInitPath to check for any explicitly configured
DefaultInitBinary. If not, the default value of DefaultInitBinary is
returned.
- Changed all references of DefaultInitBinary to refer to the variable
from new location.
- Added TestCommonUnixGetInitPath to test for the values of
DefaultInitBinary.

Fixes #32314

Signed-off-by: Sunny Gogoi <indiasuny000@gmail.com>

**- What I did**

Added the missing Init Binary info in `docker info` output.

**- How I did it**

Details are in commit body.

**- How to verify it**

Verify by running `docker info` and checking the value of `Init Binary` in the output.

**- Description for the changelog**

Fix missing Init Binary in docker info output.

**- A picture of a cute animal (not mandatory but encouraged)**

cute animal

### CODE REVIEW

File: daemon/config/config_common_unix_test.go [hunk 1]
```diff
@@ -41,3 +41,29 @@ func TestCommonUnixValidateConfigurationErrors(t *testing.T) {
...
+				CommonUnixConfig: CommonUnixConfig{
+					DefaultInitBinary: "foo-init-bin",
+				},
+			},
+			expectedInitPath: "foo-init-bin",
+		},
+		{
+			config:           &Config{},
+			expectedInitPath: "docker-init",
+		},
```
Comment (thaJeztah) [inline daemon/config/config_common_unix_test.go]: Perhaps we should have a test-case where `InitPath` is set as well?

Comment (darkowlzz) [inline daemon/config/config_common_unix_test.go]: @thaJeztah yep, missed that out :)

Comment (darkowlzz) [inline daemon/config/config_common_unix_test.go]: @thaJeztah Added that too.

**Review by vdemeester — APPROVED** [review]
LGTM 🦁
/cc @mlaventure

File: daemon/config/config_common_unix_test.go (hunk 1 above)
Comment (thaJeztah) [inline daemon/config/config_common_unix_test.go]: oh, I'm gonna be a PITA; can you add one with _both_ `InitPath` and `DefaultInitBinary` set, so that we test that `InitPath` correctly overrides `DefaultInitBinary`?

And when you added that, can you "squash" your commits, so that there's only a single commit in this PR? 😅

**Review by thaJeztah — CHANGES_REQUESTED** [review]
left one more question, but LGTM once that's done!

Thanks so much for picking this up!

File: daemon/config/config_common_unix_test.go (hunk 1 above)
Comment (darkowlzz) [inline daemon/config/config_common_unix_test.go]: @thaJeztah lol! that's alright 😁 Added another test-case and squashed the commits.

Comment (thaJeztah) [inline daemon/config/config_common_unix_test.go]: Perfect, thank you so much!

**Review by thaJeztah — APPROVED** [review]
LGTM (if green 😅)

Thank you!
