### PR TITLE
reuse same code for setting pipes in run/exec

### LINKED ISSUE #12546: docker exec -i hangs after command has exited
There is an apparent regression in the behaviour of Docker 1.6 when using `-i` with `exec`:
````
vagrant@ubuntu-14:~/weave$ docker run -di busybox
1b91aa935eac5471b4030594fb30b86471107a60c705385b3ef7310ec4e3bcf4
vagrant@ubuntu-14:~/weave$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
1b91aa935eac        busybox:latest      "/bin/sh"           2 seconds ago       Up 2 seconds                            condescending_fermat
vagrant@ubuntu-14:~/weave$ docker exec 1b91aa935eac true # this works fine
vagrant@ubuntu-14:~/weave$ echo $?
0
vagrant@ubuntu-14:~/weave$ docker exec -i 1b91aa935eac true # this hangs until you hit ENTER

vagrant@ubuntu-14:~/weave$ echo $?
255
````

### PR DESCRIPTION
**Pull request by dqminh**
Fixes https://github.com/docker/docker/issues/12546

The command's stdin pipe has to be an *os.File, otherwise bad things happen. This tries to reuse some code of `run` to setup the pipes because `run` code path already took care of that.

### CODE REVIEW

**Comment by LK4D4** [comment]
LGTM
Thanks

**Comment by dqminh** [comment]
@cpuguy83 posted some test code here https://gist.github.com/cpuguy83/b98f4da1207b9b4ed82b and this has not passed his test yet. I'm still finding out why.

**Comment by dqminh** [comment]
@LK4D4 @cpuguy83 i added a test that simulates the case better. It creates a pty and set that as stdin/out/err of the command ( so it behaves similar to starting the command inside a term ). The exec test then fails without the fix, and passes with it.

File: integration-cli/docker_cli_exec_test.go [hunk 1]
```diff
@@ -43,37 +46,31 @@ func (s *DockerSuite) TestExecInteractiveStdinClose(c *check.C) {
 	if err != nil {
 		c.Fatal(err)
 	}
-
 	contId := strings.TrimSpace(out)
 
-	returnchan := make(chan struct{})
+	cmd := exec.Command(dockerBinary, "exec", "-i", contId, "echo", "-n", "hello")
+	p, err := pty.Start(cmd)
```
Comment (cpuguy83) [inline integration-cli/docker_cli_exec_test.go]: This is causing a failure on Windows... but seems like something we should be testing on Windows too.

cc @ahmetalpbalkan

Comment (ahmetalpbalkan) [inline integration-cli/docker_cli_exec_test.go]: We  extracted tests that has kr/pty into _unix.go files b/c pty does a lot of unix stuff to control the terminal and none of those stuff exists on windows (pkg doesnt even compile on windows). I don't think we can easily run kr/pty on windows @cpuguy83 but folks working on engine may come up with a solution there.

Comment (cpuguy83) [inline integration-cli/docker_cli_exec_test.go]: If we don't have a way to do this today (even not using kr/pty), then yeah, let's move to _unix.go

Comment (dqminh) [inline integration-cli/docker_cli_exec_test.go]: i will move this to `_unix.go` first, just to make sure that it passes the current CI tests.

Comment (ahmetalpbalkan) [inline integration-cli/docker_cli_exec_test.go]: It looks to me like this test can be written without kr/pty using exec.Cmd.

**Comment by cpuguy83** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM
