### PR TITLE
Fix implicit DeviceMapper selection

### LINKED ISSUE #14035: Ubuntu 15.04 vivid can not start docker 1.7.0
```
root@vagrant-ubuntu-vivid-64:/var/lib/docker/devicemapper# service docker status -l
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2015-06-19 07:31:16 UTC; 12s ago
     Docs: https://docs.docker.com
  Process: 6704 ExecStart=/usr/bin/docker -d -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 6704 (code=exited, status=1/FAILURE)

Jun 19 07:31:16 vagrant-ubuntu-vivid-64 systemd[1]: Started Docker Application Container Engine.
Jun 19 07:31:16 vagrant-ubuntu-vivid-64 systemd[1]: Starting Docker Application Container Engine...
Jun 19 07:31:16 vagrant-ubuntu-vivid-64 docker[6704]: time="2015-06-19T07:31:16.596667126Z" level=error msg="Udev sync is not supported. This will lead to unexpected behavior, data loss and errors. For more information, see https://docs.doc...age-driver-option"
Jun 19 07:31:16 vagrant-ubuntu-vivid-64 docker[6704]: time="2015-06-19T07:31:16.596752652Z" level=error msg="[graphdriver] prior storage driver \"devicemapper\" failed: driver not supported"
Jun 19 07:31:16 vagrant-ubuntu-vivid-64 docker[6704]: time="2015-06-19T07:31:16.596788016Z" level=fatal msg="Error starting daemon: error initializing graphdriver: driver not supported"
Jun 19 07:31:16 vagrant-ubuntu-vivid-64 systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Jun 19 07:31:16 vagrant-ubuntu-vivid-64 systemd[1]: Unit docker.service entered failed state.
Jun 19 07:31:16 vagrant-ubuntu-vivid-64 systemd[1]: docker.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

```
I am using vagrant , with ubuntu 15.04

### PR DESCRIPTION
**Pull request by calavera**
DeviceMapper must be explicitly selected because the Docker binary might not be linked to the right devmapper library.

With this change, Docker fails fast if the driver detection finds the devicemapper directory but the driver is not the default option.
It also makes Docker to fail fast if it detects two driver root directories.
The option `override_udev_sync_check` doesn't make sense anymore, since the user must be explicit to select devicemapper, so it's being removed.

Fixes #14035

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

File: daemon/graphdriver/driver.go [hunk 1]
```diff
@@ -114,30 +115,34 @@ func New(root string, options []string) (driver Driver, err error) {
 
 	// Guess for prior driver
 	priorDrivers := scanPriorDrivers(root)
+	if _, ok := priorDrivers["devicemapper"]; ok && len(DefaultDriver) == 0 {
+		return nil, ErrImplicitDeviceMapper
```
Comment (icecrime) [inline daemon/graphdriver/driver.go]: I'm not sure it's true in all cases: if you are on a RedHat system with a dynamically linked binary, I think it's fine having an automatic election of `devicemapper`.

Comment (calavera) [inline daemon/graphdriver/driver.go]: I changed it to fail only if the binary was statically compiled.

File: daemon/graphdriver/driver.go [hunk 2]
```diff
@@ -114,30 +116,37 @@ func New(root string, options []string) (driver Driver, err error) {
 
 	// Guess for prior driver
 	priorDrivers := scanPriorDrivers(root)
+
+	_, ok := priorDrivers["devicemapper"]
+	// Do not allow devicemapper when it's not explicit and the Docker binary was built statically.
+	if ok && len(DefaultDriver) == 0 && dockerversion.IAMSTATIC == "true" {
```
Comment (icecrime) [inline daemon/graphdriver/driver.go]: Isn't `len(DefaultDriver) == 0` necessarily true in this code path? It seems that if it wasn't, we would have returned above in line 113, no?

File: daemon/graphdriver/driver.go [hunk 3]
```diff
@@ -167,30 +176,23 @@ func New(root string, options []string) (driver Driver, err error) {
...
-func checkPriorDriver(name, root string) error {
-	priorDrivers := []string{}
-	for _, prior := range scanPriorDrivers(root) {
-		if prior != name && prior != "vfs" {
-			if _, err := os.Stat(filepath.Join(root, prior)); err == nil {
-				priorDrivers = append(priorDrivers, prior)
-			}
-		}
+func multipleDriversError(root string, drivers map[string]string) error {
+	names := make([]string, len(drivers))
```
Comment (LK4D4) [inline daemon/graphdriver/driver.go]: I think it's better to use `var names []string` and `append` here for readability.

Comment (calavera) [inline daemon/graphdriver/driver.go]: yes, but we don't need to allocate N slices when we know the length we want.

File: daemon/graphdriver/driver.go (hunk 2 above)
Comment (calavera) [inline daemon/graphdriver/driver.go]: oh, that's correct. Fixing.

File: daemon/graphdriver/driver.go (hunk 3 above)
Comment (LK4D4) [inline daemon/graphdriver/driver.go]: performance is not nearly an issue here :) readability always should be priority
you can allocate `names := make([]string, 0, len(drivers))` and use append, but I'm sure nobody will notice difference between `var names []string` and `make([]string, 2)`

Comment (calavera) [inline daemon/graphdriver/driver.go]: fixed.

**Comment by thaJeztah** [comment]
ping @vbatts and @rhvgoyal (I think) :-)

**Comment by rhvgoyal** [comment]
@calavera 

I am not sure what's the purpose of this patch.  For dynamic binary case, a user should not have to select devicemapper explicitly.

Those who are complaining about docker not starting over upgrade, that was deliberate. People have been using static binaries with devicemapper driver and it was broken. Docker 1.6 allowed it and @vbatts and others wanted users to move away from it.

That's the reason in 1.7, docker will fail (instead of continuing) by default. And that's what everybody is running into. This is by design and not an error.

Those who are running into issues, solution is not to downgrade to 1.6. But one of the following.

- Now you know that static binary will not work reliably with devicemapper driver. So save your work,
  and switch to a different driver.

- If you can live with devicemapper unreliability with static binary and just want your working setup as
you had in 1.6, simply specify --storage-opt dm.override_udev_sync_check=true and restart docker daemon.

Note: IIRC, I had opposed failing by default because that would break existing users over upgrade. And that's what precisely is happening. But people had argued that we don't want people to continue to use already broken setups hence we want to break these systems over upgrade and let users opt-in for a broken system or switch to a different driver. 

So all this is intentional folks.

**Comment by calavera** [comment]
@rhvgoyal The intention here is to be more clear about why docker is failing to start. This is what's going to happen with this change:

1 - Case where you're running a dynamic binary, you have the devicemapper directory and you don't select the driver: Everything is okay, we select devicemapper and move forward.
2 - Case where you're running a static binary, you have the devicemapper directory and you don't select a driver: Not cool, we fail and ask the user to select devicemapper explicitly. **NOTE** the error message is not good enough, will fix.
3 - Case where you're running a static binary and you select the driver explicitly: Your problem, since you're explicitly selecting the driver. We only log a message in the daemon log.

So instead of asking people to set another flag ` --storage-opt dm.override_udev_sync_check=true`, we just let them go for it when they set the storage driver explicitly.

Is this clear enough @icecrime?

**Comment by calavera** [comment]
I added `using a statically linked binary` to the beginning of the error message to be more clear about the issue.

**Comment by rhvgoyal** [comment]
@calavera 

Please read through this conversation when udev sync flag patch was merged.

https://github.com/docker/docker/pull/11412

I think it is pretty clear that what's the intention and what's the behavior. User either needs to pass a flag to continue with old broken behavior or move to a different driver.

What's not clear here?

**Comment by rhvgoyal** [comment]
@calavera 

Users need to set --storage-opt dm.override_udev_sync_check=true only in two cases, when using static docker binary.

- Either they have selected devicemapper storage driver specifically.
- Or, they had been using devicemapper storage driver and have upgraded to 1.7.

And in both the cases, it is reasonable to ask user to acknowledge that their current setup is broken and still they want to continue to use it and hence they need to opt-in using this flag.

**Comment by calavera** [comment]
> I think it is pretty clear that what's the intention and what's the behavior. User either needs to pass a flag to continue with old broken behavior or move to a different driver.

No, the intention is not clear, neither the behavior, and that's the main problem that people have.

Requiring people to use `docker -d --storage-opt dm.override_udev_sync_check=true` is confusing because that storage option is specific to a driver that they didn't select. Requiring people to use `docker -d --storage-diver devicemapper` is understandable because they make a explicit decision to use a driver.

**Comment by rhvgoyal** [comment]
@calavera 

People are forced to use it only if they had been using devicemapper previously. As docker selected it. and it is a broken configuraiton.

If you are starting docker fresh, devicemapper might not be selected at all as it is so low in priority table. Even if it is selected, initialization will fail and docker will move on to overlay.

So people need to specify udev sync flag, only if they decide to use devicemapper. And that's happening only in upgrade case where docker is imposing devicemapper as that's the prior used driver.

**Comment by rhvgoyal** [comment]
@calavera 

IOW, docker -d --storage-opt dm.override_udev_sync_check=true is corner case. Where user has not selected a graph driver but docker is forcing devicemapper as that's the one which was being used before upgrade. And hence user needs to specify this.

That's the whole intention of this flag. Try to bring broken configurations to user's notice. Otherwise a user will complain, hey I did not specify a graph driver and docker imposed a broken driver on me. Despite the fact that docker knows configuration is broken, it simply put a log in journal and moved on.

Those who are not upgrading should not be running into this issue.

**Comment by calavera** [comment]
@rhvgoyal I understand that. Users don't. It's easy to explain that they need to set the driver than to explain that the need to set an option for a driver they didn't select.

**Comment by rhvgoyal** [comment]
@calavera 

Ok, after your patch, what's going to change? If 1.6 was using devicemapper and a user upgrades to 1.7.1, what will he/she see? Lets discuss the semantics first. I don't even fully understand what your patch is doing.

**Comment by thaJeztah** [comment]
My initial stance at this;

- IIRC, the `dm.override_udev_sync_check` is only a **temporary** flag, giving users a "grace period"; a chance to either switch drivers, or install a non-statically built docker to keep using devicemapper. Plans were to *remove* that flag (in 1.8) and no longer allowing users to use devicemapper at *all* without udev sync (@vbatts please confirm if I'm right here)
- The flag "sucks", and it *should be*, because running without Udev sync can (if I understand correctly) lead to nasty things, *including* data-corruption, which sucks even more :-) After all, I don't think anyone would expect (e.g.) their anti-virus software issuing a message "Virus detected in xxx press OK to continue", just because that's the easy way.
- *Not* requiring the flag, would put switching to a malfunctioning driver at the same "level" as Docker not being able to automatically decide which driver to use (if multiple graph dirs were found); I don't think that's correct; it's a different "level" and should be a very deliberate choice to pick that driver (given that it is flawed without udev sync)


What I *do* agree on with @calavera is that;

- We should have been more communicative on this change; there should be a big warning and clear(er) instructions in the release notes and documentation, explaining what this (error) means, and  how to migrate or upgrade Docker in such case (we can still add this?), also giving a clear notice that such setup will **not** be supported in 1.8
- We should make it easier to obtain dynamically linked Docker builds; if I'm not mistaken, the only way currently is to build yourself. That's *bad*, I don't think we can expect people *using* Docker to also be able to build it themselves.


Just my opinion :-)

**Comment by rhvgoyal** [comment]
@thaJeztah 

RedHat is shipping dynamically built docker in fedora, rhel, atomic, centos. So distributions should be able to ship dynamically built docker for their users.

**Comment by rhvgoyal** [comment]
@thaJeztah 

I agree that better documentation and communication is the key whenever we decide to *break* existing working setup.

**Comment by thaJeztah** [comment]
@rhvgoyal 

> RedHat is shipping dynamically built docker in fedora, rhel, atomic, centos. So distributions should be able to ship dynamically built docker for their users.

True, problem is that;
- Other distros don't (or might not)
- We give instructions for installing the *docker* maintained versions (and don't provide dynamically built vanilla docker). I'm not sure Docker should be pointing people to RedHat maintained versions, because we cannot provide support for those (willing to exchange thoughts on that)

**Comment by calavera** [comment]
> If 1.6 was using devicemapper and a user upgrades to 1.7.1, what will he/she see

the user will see an error saying `using devicemapper with a statically linked binary. Devicemapper must be explicitly loaded with --storage-option <DRIVER> or used with a dynamically linked binary`

**Comment by rhvgoyal** [comment]
On Wed, Jul 01, 2015 at 12:48:14PM -0700, David Calavera wrote:
> > If 1.6 was using devicemapper and a user upgrades to 1.7.1, what will he/she see
> 
> the user will see an error saying `using devicemapper with a statically linked binary. Devicemapper must be explicitly loaded with --storage-option <DRIVER> or used with a dynamically linked binary`
> 

Ok, so basically failure will still happen over upgrade just that user
will have pass in a "-s devicemapper" instead of "--storage-opt dm.foo=true".

That's not much different from current semantics.

**Comment by calavera** [comment]
> This error should happen only if we have selected devicemapper as prior driver. And not before that.

That's exactly when it happens. After gathering the info about the prior drivers.

**Comment by icecrime** [comment]
I think I'm with @calavera on that one. Right now, `dm.override_udev_sync_check=false` is a "proxy" to say "my setup is broken but I know what I'm doing": we might as well ask for `--storage=devicemapper` and produce a warning.

**Comment by rhvgoyal** [comment]
On Wed, Jul 01, 2015 at 01:52:18PM -0700, Arnaud Porterie wrote:
> I think I'm with @calavera on that one. Right now, `dm.override_udev_sync_check=false` is a "proxy" to say "my setup is broken but I know what I'm doing": we might as well ask for `--storage=devicemapper` and produce a warning.
> 

I am not opposed to the idea either. So basically explicitly specifying
-s devicemapper will automatically imply override udev sync check.

Vivek

**Comment by icecrime** [comment]
Yes: instead of asking for an obscure flag that will be hard to explain for end-user, we are basically telling them "Docker will never silently pick devicemapper on Ubuntu for you".

**Comment by rhvgoyal** [comment]
On Wed, Jul 01, 2015 at 01:59:54PM -0700, Arnaud Porterie wrote:
> Yes: instead of asking for an obscure flag that will be hard to explain for end-user, we are basically telling them "Docker will never silently pick devicemapper on Ubuntu for you".

What about the case of fresh install of statically linked dokcer. Will
it fail and force user to specify -s devicemapper or will use it if
aufs, btrfs, zfs are not available?

File: daemon/graphdriver/driver.go [hunk 4]
```diff
@@ -22,9 +23,10 @@ var (
 	// All registred drivers
 	drivers map[string]InitFunc
 
-	ErrNotSupported   = errors.New("driver not supported")
-	ErrPrerequisites  = errors.New("prerequisites for driver not satisfied (wrong filesystem?)")
-	ErrIncompatibleFS = fmt.Errorf("backing file system is unsupported for this graph driver")
+	ErrNotSupported         = errors.New("driver not supported")
+	ErrPrerequisites        = errors.New("prerequisites for driver not satisfied (wrong filesystem?)")
+	ErrIncompatibleFS       = fmt.Errorf("backing file system is unsupported for this graph driver")
+	ErrImplicitDeviceMapper = fmt.Errorf("using devicemapper with a statically linked binary. Devicemapper must be explicitly loaded with --storage-option <DRIVER> or used with a dynamically linked binary")
```
Comment (icecrime) [inline daemon/graphdriver/driver.go]: I would make this more explicit.

> `devicemapper` storage driver cannot reliably be used with a statically linked docker binary: please either pick a different storage driver, install a dynamically linked docker binary, or force this unreliable setup anyway by specifying `--storage-driver=devicemapper`

**Comment by rhvgoyal** [comment]
@icecrime I like your error message. 

So we need to do few things.

- Make sure above message is displayed both for the case of fresh install and prior driver selection.
- If we are enforcing that there is only one prior driver directory, then there is no need to though priority
  list after scanning for prior drivers. Anywhere there is one. Use it.

**Comment by calavera** [comment]
> Make sure above message is displayed both for the case of fresh install and prior driver selection.

agreed

> If we are enforcing that there is only one prior driver directory, then there is no need to though priority list after scanning for prior drivers. Anywhere there is one. Use it.

we've been doing this for a really long time, but the code is a mess.

File: daemon/graphdriver/driver.go (hunk 4 above)
Comment (calavera) [inline daemon/graphdriver/driver.go]: :+1:

**Comment by calavera** [comment]
I made the changes suggested by @icecrime and @rhvgoyal

**Comment by icecrime** [comment]
```
--- FAIL: TestDevmapperSetup (0.00s)
	graphtest.go:76: graphdriver: devicemapper storage driver cannot reliably be used with a statically linked docker binary: please either pick a different storage driver, install a dynamically linked docker binary, or force this unreliable setup anyway by specifying --storage-driver=devicemapper
	graphtest.go:80: devicemapper storage driver cannot reliably be used with a statically linked docker binary: please either pick a different storage driver, install a dynamically linked docker binary, or force this unreliable setup anyway by specifying --storage-driver=devicemapper
--- FAIL: TestDevmapperCreateEmpty (0.00s)
	graphtest.go:76: graphdriver: devicemapper storage driver cannot reliably be used with a statically linked docker binary: please either pick a different storage driver, install a dynamically linked docker binary, or force this unreliable setup anyway by specifying --storage-driver=devicemapper
	graphtest.go:80: devicemapper storage driver cannot reliably be used with a statically linked docker binary: please either pick a different storage driver, install a dynamically linked docker binary, or force this unreliable setup anyway by specifying --storage-driver=devicemapper
--- FAIL: TestDevmapperCreateBase (0.00s)
	graphtest.go:76: graphdriver: devicemapper storage driver cannot reliably be used with a statically linked docker binary: please either pick a different storage driver, install a dynamically linked docker binary, or force this unreliable setup anyway by specifying --storage-driver=devicemapper
	graphtest.go:80: devicemapper storage driver cannot reliably be used with a statically linked docker binary: please either pick a different storage driver, install a dynamically linked docker binary, or force this unreliable setup anyway by specifying --storage-driver=devicemapper
--- FAIL: TestDevmapperCreateSnap (0.00s)
	graphtest.go:76: graphdriver: devicemapper storage driver cannot reliably be used with a statically linked docker binary: please either pick a different storage driver, install a dynamically linked docker binary, or force this unreliable setup anyway by specifying --storage-driver=devicemapper
	graphtest.go:80: devicemapper storage driver cannot reliably be used with a statically linked docker binary: please either pick a different storage driver, install a dynamically linked docker binary, or force this unreliable setup anyway by specifying --storage-driver=devicemapper
```

**Comment by calavera** [comment]
@icecrime dunno why they fail, that's correct :trollface:

**Comment by calavera** [comment]
@icecrime they should be fixed now.

**Comment by calavera** [comment]
@rhvgoyal I made those changes. Thanks for the feedback!

**Comment by LK4D4** [comment]
LGTM

**Comment by icecrime** [comment]
Tested locally, I think the output makes sense (I hope it will be clearer to the users at least...).

Thanks, LGTM.

**Comment by icecrime** [comment]
Overriding docs review as I believe this is essentially a rollback of a previously added parameter.

**Comment by calavera** [comment]
Cherry picked into #14264

**Comment by thaJeztah** [comment]
@icecrime is the plan to keep "allowing" running without udev sync support, or will it be a hard failure in a future version? If so, should that be announced / part of the roadmap?

**Comment by icecrime** [comment]
@thaJeztah Honestly, I'm inclined to think this is a good final situation: it's breaking enough, and explicit enough.

**Comment by rhvgoyal** [comment]
Right now following is the behavior.

- If you are starting static docker fresh, then it will choose overlay. There should not be any error message about devicemapper. It will simply skip devicemapper.

- If devicemapper was being used as prior driver then over upgrade it will fail to start and will ask user to explicitly specify devicemapper driver.

Either way, if user forces use of devicemapper with static binary, it is running without udev sync support. libdm needs static libudev for it to work but systemd project does not allow static libudev.

**Comment by thaJeztah** [comment]
@icecrime alright, let's see how this works out then; we can always evaluate if too many people run into problems

**Comment by rhvgoyal** [comment]
So after this change, how does devicemapper testing on docker work? If I generate PR, do we make sure it works with devicemapper backend otherwise CI fails?
