### PR TITLE
libnet: create DNS records on sbJoin (if not agent node)

### LINKED ISSUE #51491: DNS resolution broken after `docker swarm init` (29.0.0)
### Description

After upgrading to docker 29.0.0, I noticed that internal DNS resolution is broken after doing a `docker swarm init`.

When doing `docker swarm leave --force`, the DNS resolution works again.

### Reproduce

```
$ docker network create test
$ docker run --rm --network test --name test alpine sh -c 'apk add -q bind-tools && dig test +noall +question +answer'
;test.				IN	A
test.			600	IN	A	172.19.0.2

$ docker swarm init

$ docker run --rm --network test --name test alpine sh -c 'apk add -q bind-tools && dig test +noall +question +answer'
;test.				IN	A

$ docker swarm leave --force

$ docker run --rm --network test --name test alpine sh -c 'apk add -q bind-tools && dig test +noall +question +answer'
;test.				IN	A
test.			600	IN	A	172.19.0.2
```

### Expected behavior

Internal DNS resolution should always work.

### docker version

```bash
Client:
 Version:           29.0.0
 API version:       1.52
 Go version:        go1.25.4
 Git commit:        3d4129b
 Built:             Mon Nov 10 21:45:29 2025
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          29.0.0
  API version:      1.52 (minimum version 1.44)
  Go version:       go1.25.4
  Git commit:       d105562
  Built:            Mon Nov 10 21:47:52 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v2.1.5
  GitCommit:        fcd43222d6b07379a4be9786bda52438f0dd16a1
 runc:
  Version:          1.3.3
  GitCommit:        v1.3.3-0-gd842d77
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    29.0.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.29.1
    Path:     /usr/local/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.40.3
    Path:     /usr/local/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 29.0.0
 Storage Driver: overlayfs
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 CDI spec directories:
  /etc/cdi
  /var/run/cdi
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: fcd43222d6b07379a4be9786bda52438f0dd16a1
 runc version: v1.3.3-0-gd842d77
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.14.0-35-generic
 Operating System: Alpine Linux v3.22 (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 22
 Total Memory: 62.24GiB
 Name: aa7318b19ff9
 ID: c4ce3115-7dfc-4b58-bb9a-f5d9a4b28be6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
  ::1/128
 Live Restore Enabled: false
 Product License: Community Engine
 Firewall Backend: iptables
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by akerouanton**
- Fixes https://github.com/moby/moby/issues/51491
- Related to https://github.com/moby/moby/pull/48971

**- What I did**

Commit https://github.com/moby/moby/commit/a8b9eff902903246aed22a0e49fbc713abcb6a94 removed a call to Network.updateSvcRecord from Network.createEndpoint on the grounds that:

> all callers of Network.createEndpoint follow up with an Endpoint.Join, which also sets up the DNS entry.

However, the original call in Network.createEndpoint was gated by:

```golang
if !n.getController().isSwarmNode() || n.Scope() != scope.Swarm || !n.driverIsMultihost() {
	n.updateSvcRecord(context.WithoutCancel(ctx), ep, true)
}
```

whereas the call in Endpoint.sbJoin() (invoked by Endpoint.Join()) is gated by:

```golang
if !n.getController().isAgent() {
    if !n.getController().isSwarmNode() || n.Scope() != scope.Swarm || !n.driverIsMultihost() {
	    n.updateSvcRecord(context.WithoutCancel(ctx), ep, true)
    }
}
```

As a result, once a node has joined a Swarm cluster, no DNS entries are created for non swarm-scoped networks.

Change the condition used by `sbJoin` to match the original condition used in `createEndpoint`, and add an integration test.

**- Human readable description for the release notes**

```markdown changelog
Fix a bug preventing DNS resolution of containers attached to non swarm-scoped networks once the node has joined a Swarm cluster
```

### CODE REVIEW

**Review by vvoland — APPROVED** [review]
SGTM if green

**Review by corhere — APPROVED** [review]

**Review by robmry — APPROVED** [review]
LGTM - thank you.

I think the bug is the `isAgent` check in `sbJoin` (now `populateNetworkResources`). But, as discussed, we don't currently have enough swarm tests or the nerve to change anything.

**Comment by akerouanton** [comment]
> I think the bug is the isAgent check in sbJoin (now populateNetworkResources). But, as discussed, we don't currently have enough swarm tests or the nerve to change anything.

After looking at the CI failure (which was a mysterious test suite hang caused by a missing `-c1` in the ping invocation), I realized that re-introducing `updateSvcRecord` in `createEndpoint` would require a call to `updateSvcRecord(…, isAdd = false)` in `populateNetworkResourcesOS`.

I ended up implementing your suggestion — remove the `isAgent` check in `sbJoin`.

File: integration/networking/bridge_linux_test.go [hunk 1]
```diff
@@ -2032,3 +2032,30 @@ func TestLegacyLinksEnvVars(t *testing.T) {
...
+// a node has joined a Swarm cluster.
+//
+// Regression test for https://github.com/moby/moby/issues/51491.
+func TestDNSNamesForNonSwarmScopedNetworks(t *testing.T) {
+	ctx := setupTest(t)
+
+	d := daemon.New(t)
+	d.StartAndSwarmInit(ctx, t)
+	defer d.Stop(t)
+	defer d.SwarmLeave(ctx, t, true)
```
Comment (robmry) [inline integration/networking/bridge_linux_test.go]: Nit/question - does this do anything after the `Stop`? (Probably no need to `SwarmLeave` at all, as it's a throw-away daemon?)

**Review by robmry — APPROVED** [review]

File: integration/networking/bridge_linux_test.go (hunk 1 above)
Comment (akerouanton) [reply integration/networking/bridge_linux_test.go]: Right, it's a throw-away daemon so it does nothing. I can remove it if you prefer (once I get a green run of the CI).

**Review by corhere — APPROVED** [review]
