### PR TITLE
Validate `--ip` and `--ip6` for `docker create`

### LINKED ISSUE #25863: --ip=<ipaddr> gracefully accepts hostname but doesn't perform DNS lookup
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Output of `docker version`:**

Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

**Output of `docker info`:**

Containers: 31
 Running: 3
 Paused: 0
 Stopped: 28
Images: 173
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: vg--docker-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 87.72 GB
 Data Space Total: 399.7 GB
 Data Space Available: 312 GB
 Metadata Space Used: 20.87 MB
 Metadata Space Total: 1.002 GB
 Metadata Space Available: 981.6 MB
 Thin Pool Minimum Free Space: 39.97 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge macvlan overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: Red Hat Enterprise Linux
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 125.6 GiB
ID: LUER:C2ZN:EIWN:YK5C:TY2L:AZEH:5JBV:FCCY:TRPK:EY2U:KVIB:ODZK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**

OS: RHEL 7.2
Kernel: Linux 3.10.0-327.22.2.el7.x86_64

Using the new MACVLAN driver

**Steps to reproduce the issue:**
1. Run docker run command with basic required arguments on some image and --net=<some configured docker network> --ip=<hostname>
2. Exec into container and run "ip addr" and validate that the eth0 interface takes the zero address of in the subnet rather than the expected DNS mapped IP

**Describe the results you received:**
Container starts gracefully without issue, yet cannot connect/communicate with container externally other than through docker daemon client. 

**Describe the results you expected:**
If the new MACVLAN driver support cannot accept a domain hostname as --ip parameter argument, should run validation on the given argument and return error upon invalid format.

### PR DESCRIPTION
**Pull request by yongtang**
**\- What I did**

This fix tries to fix the issue raised in #25863 where `--ip` value is not validated for `docker create`. As a result, the IP address passed by `--ip` is not used for `docker create` (ignored silently).

**\- How I did it**

This fix adds validation in the daemon so that `--ip` and  `--ip6` are properly validated for `docker create`.

**\- How to verify it**

An integration test has been added to cover the changes.

**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**

This fix fixes #25863.

Signed-off-by: Yong Tang yong.tang.github@outlook.com

### CODE REVIEW

File: daemon/create.go [hunk 1]
```diff
@@ -244,8 +245,22 @@ func (daemon *Daemon) mergeAndVerifyConfig(config *containertypes.Config, img *i
 }
 
 // Checks if the client set configurations for more than one network while creating a container
+// Also checks if the IPAMConfig is valid
 func (daemon *Daemon) verifyNetworkingConfig(nwConfig *networktypes.NetworkingConfig) error {
-	if nwConfig == nil || len(nwConfig.EndpointsConfig) <= 1 {
+	if nwConfig == nil || len(nwConfig.EndpointsConfig) == 0 {
+		return nil
+	}
+	if len(nwConfig.EndpointsConfig) == 1 {
```
Comment (cpuguy83) [inline daemon/create.go]: Why `==  1` and then a `for`?

Comment (yongtang) [inline daemon/create.go]: If `> 1` then it will be an error condition (more than one endpointsConfig) which falls below to Ln 266 - 271.

On the other hand since `nwConfig.EndpointsConfig` is a map so I am using `for` to get the value of the map (though it can only have one key-value).

File: daemon/create.go [hunk 2]
```diff
@@ -244,8 +245,22 @@ func (daemon *Daemon) mergeAndVerifyConfig(config *containertypes.Config, img *i
...
+		for _, v := range nwConfig.EndpointsConfig {
+			if v.IPAMConfig != nil {
+				if v.IPAMConfig.IPv4Address != "" && net.ParseIP(v.IPAMConfig.IPv4Address).To4() == nil {
+					return errors.NewBadRequestError(fmt.Errorf("Container cannot be connected to invalid IPv4 address: %s", v.IPAMConfig.IPv4Address))
```
Comment (cpuguy83) [inline daemon/create.go]: I'd change the message to just `invalid IPv4 address: %s`
Also, error messages should always start lower-cased.

File: daemon/create.go [hunk 3]
```diff
@@ -244,8 +245,22 @@ func (daemon *Daemon) mergeAndVerifyConfig(config *containertypes.Config, img *i
...
+				}
+				if v.IPAMConfig.IPv6Address != "" && net.ParseIP(v.IPAMConfig.IPv6Address).To16() == nil {
+					return errors.NewBadRequestError(fmt.Errorf("Container cannot be connected to invalid IPv6 address: %s", v.IPAMConfig.IPv6Address))
```
Comment (cpuguy83) [inline daemon/create.go]: Same comment as above.

File: integration-cli/docker_cli_network_unix_test.go [hunk 4]
```diff
@@ -1710,3 +1710,20 @@ func (s *DockerNetworkSuite) TestDockerNetworkFlagAlias(c *check.C) {
...
+	assertNwIsAvailable(c, "mynet")
+
+	_, _, err = dockerCmdWithError("run", "-d", "--name", "mynet0", "--net=mynet", "--ip", "172.28.99.88", "--ip6", "2001:db8:1234::9988", "busybox", "top")
+	c.Assert(err, check.IsNil)
+	c.Assert(waitRun("mynet0"), check.IsNil)
+	verifyIPAddressConfig(c, "mynet0", "mynet", "172.28.99.88", "2001:db8:1234::9988")
+	verifyIPAddresses(c, "mynet0", "mynet", "172.28.99.88", "2001:db8:1234::9988")
+
+	_, _, err = dockerCmdWithError("run", "--net=mynet", "--ip", "mynet_ip", "--ip6", "2001:db8:1234::9999", "busybox", "top")
+	c.Assert(err.Error(), checker.Contains, "Container cannot be connected to invalid IPv4 address")
```
Comment (cpuguy83) [inline integration-cli/docker_cli_network_unix_test.go]: Need to update these error checks after updating the ones above.

**Comment by cpuguy83** [comment]
Couple of nits.
Thanks @yongtang

**Comment by yongtang** [comment]
Thanks @cpuguy83. The comments have been addressed and the pull request has been updated. Please let me know if there are any additional issues.

**Comment by cpuguy83** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐯
@yongtang This will need a small note on `docker_remote_api.md` in `v1.25 API Changes` though 👼

**Comment by yongtang** [comment]
Thanks @vdemeester. The pull request has been updated with documentation update. Please let me know if there are any additional issues.

**Comment by vdemeester** [comment]
docs LGTM 🐸

**Comment by justincormack** [comment]
Needs a rebase

**Comment by yongtang** [comment]
Thanks @justincormack. The pull request has been rebased. Let me know if there are any other issues.

**Comment by cpuguy83** [comment]
docs LGTM

File: daemon/create.go [hunk 5]
```diff
@@ -244,8 +245,22 @@ func (daemon *Daemon) mergeAndVerifyConfig(config *containertypes.Config, img *i
...
+	if nwConfig == nil || len(nwConfig.EndpointsConfig) == 0 {
+		return nil
+	}
+	if len(nwConfig.EndpointsConfig) == 1 {
+		for _, v := range nwConfig.EndpointsConfig {
+			if v.IPAMConfig != nil {
+				if v.IPAMConfig.IPv4Address != "" && net.ParseIP(v.IPAMConfig.IPv4Address).To4() == nil {
+					return errors.NewBadRequestError(fmt.Errorf("invalid IPv4 address: %s", v.IPAMConfig.IPv4Address))
+				}
+				if v.IPAMConfig.IPv6Address != "" && net.ParseIP(v.IPAMConfig.IPv6Address).To16() == nil {
```
Comment (aboch) [inline daemon/create.go]: `To16() == nil` check to state a valid IPv6 address cannot be used as equivalent of `To4() == nil` to state a valid IPv4 address.
For an IPv4 address, `To16()` returns the IPv4-in-IPv6 notation of that address, it does not return `nil`.

Also, in this case `To16()` will never return `nil` because it is run on the result of `ParseIP()` which in this context is assumed to always return a valid IP address (given no nil check is run on the result of `ParseIP()`).

Comment (yongtang) [inline daemon/create.go]: Thanks @aboch for pointing that out. Let me take a look and create a pull request to address this issue.
