### PR TITLE
Make sure log pipes are closed

### LINKED ISSUE #13014: Docker logs --follow leaks goroutines/memory
It seems that each `docker logs -f <container>` adds 5 new goroutines to docker daemon. If this command (or request to docker remote api) is repeated constantly, docker starts to leak goroutines and memory. Somehow these goroutines are not cleaned up even after waiting for over 30 minutes.

Docker version: 1.3.3 - 1.6.0

Steps to reproduce:
1. run `docker logs -f <container>` multiple times 

Actual results:
Docker daemon goroutines (and memory) keeps going up.

Expected results:
Docker daemon cleans up goroutines

### PR DESCRIPTION
**Pull request by cpuguy83**
Fixes #13014 (mostly)

Pipes are still not closed (and goroutines leaked) if neither pipe is
used.

### CODE REVIEW

**Comment by vieux** [comment]
ping @LK4D4 :D

File: daemon/logs.go [hunk 1]
```diff
@@ -125,38 +126,53 @@ func (daemon *Daemon) ContainerLogs(name string, config *ContainerLogsConfig) er
...
-
-		for err := range errors {
-			if err != nil {
-				logrus.Errorf("%s", err)
+		select {
+		case err = <-stdoutErr:
+			if stderrPipe != nil {
+				stderrPipe.Close()
+			}
+			<-stderrErr
```
Comment (LK4D4) [inline daemon/logs.go]: Wouldn't you wait here forever if there wasn't config.UseStderr?

Comment (cpuguy83) [inline daemon/logs.go]: yep, will fix.

File: daemon/logs.go [hunk 2]
```diff
@@ -125,38 +126,53 @@ func (daemon *Daemon) ContainerLogs(name string, config *ContainerLogsConfig) er
 			}
 		}
 	}
+
 	if config.Follow && container.IsRunning() {
-		errors := make(chan error, 2)
-		wg := sync.WaitGroup{}
+		var (
```
Comment (LK4D4) [inline daemon/logs.go]: I hate this block, err already exists. instead of `stdoutPipe` better to use value from config. chans can be just :=

File: daemon/logs.go [hunk 3]
```diff
@@ -125,38 +126,53 @@ func (daemon *Daemon) ContainerLogs(name string, config *ContainerLogsConfig) er
...
 		if config.UseStdout {
-			wg.Add(1)
-			stdoutPipe := container.StdoutLogPipe()
+			stdoutPipe = container.StdoutLogPipe()
 			defer stdoutPipe.Close()
 			go func() {
-				errors <- jsonlog.WriteLog(stdoutPipe, outStream, format)
-				wg.Done()
+				logrus.Debug("logs: stdout stream begin")
+				stdoutErr <- jsonlog.WriteLog(stdoutPipe, outStream, format)
```
Comment (LK4D4) [inline daemon/logs.go]: What if error would be read from another channel and you will be locked here forever?

Comment (cpuguy83) [inline daemon/logs.go]: If error is read from another channel then the pipe will be closed and this will return.

Comment (LK4D4) [inline daemon/logs.go]: makes sense

**Comment by cpuguy83** [comment]
@LK4D4 updated

**Comment by LK4D4** [comment]
@cpuguy83 You can write test for this I think with checking `Goroutines` from info. Feel free to say, that you don't want :)

**Comment by cpuguy83** [comment]
@LK4D4 test added.

**Comment by LK4D4** [comment]
@cpuguy83 Lol, sorry, I waited for jenkins and forgot about PR. Need rebase.

**Comment by cpuguy83** [comment]
Rebased

**Comment by LK4D4** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM
