### PR TITLE
Remove read index that causes dead lock.

### LINKED ISSUE #15087: 1.8.0-dev sporadic hang on extracting layer
Discovered while testing #15040 

Sporadically while pulling `docker.io/library/golang`, after all layers are downloaded and all other layers are extracted, the layer `124e2127157f` will just fail to ever extract. This results in the `docker pull golang` just sitting with:
```bash
vbatts@noyee ~ (master) $ docker pull golang
latest: Pulling from library/golang
902b87aaaec9: Pull complete
9a61b6b1315e: Pull complete
1ff9f26f09fb: Pull complete
607e965985c1: Pull complete
0f5121dd42a6: Pull complete
8d38711ccc0d: Pull complete
8ddc08289e1a: Pull complete
d86979befb72: Pull complete
b279b4aae826: Pull complete
63e9d2557cd7: Pull complete
8fb45e60e014: Pull complete
141b650c3281: Pull complete
69c177f0c117: Pull complete
124e2127157f: Download complete
```
Daemon logs:
```
INFO[0003] POST /v1.20/images/create?fromImage=golang%3Alatest
DEBU[0003] Trying to pull golang from https://registry-1.docker.io v2
DEBU[0003] Fetched 1 base graphs at 2015-07-28 11:46:51.24307595 -0400 EDT
DEBU[0003] Reloaded graph with 3 grants expiring at 2017-03-22 19:04:46.713978458 +0000 UTC
DEBU[0003] Pulling tag from V2 registry: "latest"
DEBU[0004] Key check result: verified
INFO[0004] Image manifest for golang:latest has been verified
DEBU[0004] pulling blob "sha256:4d2e9ae40c411dd421f35dd20c133152bed21f8f9b903ba265a5d77c69a79edc" to 902b87aaaec929e80541486828959f14fa061f529ad7f37ab300d4ef9f3a0dbf
DEBU[0004] pulling blob "sha256:8b04aafd7cd87aa98ed28895e8e7b3bd5ad40510743c4e60387b40e8bfcf3cfb" to 607e965985c11e6a23270feec487908aeaa9af763d24a2986866a41537770c8c
DEBU[0004] pulling blob "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" to 9a61b6b1315e6b457c31a03346ab94486a2f5397f4a82219bee01eead1c34c2e
DEBU[0004] pulling blob "sha256:4b3ef98bba76f91973a5012430d7901c46e95f7b64e4c099c692f4bc022f9368" to 8ddc08289e1a9e4413633bcc969369954a4d4605f56801428986e3b0b358446f
DEBU[0004] pulling blob "sha256:c97c75d2d42e2684a0cd767391a01e423c2a157709cb6509823fb2219307bc42" to 0f5121dd42a613481a72899ea1ac4620a909427cf81bc9edff59a2b85c8fc73f
DEBU[0004] pulling blob "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" to 8d38711ccc0dfe0af69a22969209f6b4002d5bfc87961508411ea777a2c5a276
DEBU[0004] pulling blob "sha256:ddf532273b60e90431d7630711d2a31b1ab73424d88c4569fd6c793a173cdae0" to 124e2127157f398735e5888601e8b02cf832e037ef951317bc0a4f6256723d7b
DEBU[0004] pulling blob "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" to 8fb45e60e014d834ddb7aac0adf9985a35359b47f84aedc48b272b8662bdd528
DEBU[0004] pulling blob "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" to 141b650c3281e7559e1bddacb7ae4db1af79c269cdc69545cf9f78bc7f322fae
DEBU[0004] pulling blob "sha256:edee0288d3569721eddc9be4744290964d865aa1df38e3df691d281e1fc6b95a" to d86979befb725994b1c58c8340b3313f7b3118bf60c40972d520a43b2ea35f7f
DEBU[0004] pulling blob "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" to 69c177f0c117c1ea8c4593b4fbfa7affb4096f7abc751c9d818721bfdea087bb
DEBU[0004] pulling blob "sha256:ea2a9399d365a1e5f01829dcc49030e4e6ec6b686247141f11dd1da015a7cbea" to 63e9d2557cd7fb600e8739cb930c6db63af6f54bc6b25778bb7848b1facb5d6b
DEBU[0004] pulling blob "sha256:7c8152785df568006148a08519717d0de6a6bdfed18d0d599213d9124950746c" to 1ff9f26f09fb1bc7b5955c269b1042429e86d7891c653f52f3e48f1e0365d7df
DEBU[0004] pulling blob "sha256:ddf532273b60e90431d7630711d2a31b1ab73424d88c4569fd6c793a173cdae0" to 124e2127157f398735e5888601e8b02cf832e037ef951317bc0a4f6256723d7b
DEBU[0004] pulling blob "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" to b279b4aae82666b6c5bfc01e18efe5a8ba93627b20334b8c45d874d8dfe3a979
DEBU[0004] Downloaded 8d38711ccc0dfe0af69a22969209f6b4002d5bfc87961508411ea777a2c5a276 to tempfile /home/docker/tmp/GetImageBlob789439028
DEBU[0004] Downloaded 69c177f0c117c1ea8c4593b4fbfa7affb4096f7abc751c9d818721bfdea087bb to tempfile /home/docker/tmp/GetImageBlob476951015
DEBU[0004] Downloaded 141b650c3281e7559e1bddacb7ae4db1af79c269cdc69545cf9f78bc7f322fae to tempfile /home/docker/tmp/GetImageBlob431704365
DEBU[0004] Downloaded b279b4aae82666b6c5bfc01e18efe5a8ba93627b20334b8c45d874d8dfe3a979 to tempfile /home/docker/tmp/GetImageBlob249347676
DEBU[0004] Downloaded 63e9d2557cd7fb600e8739cb930c6db63af6f54bc6b25778bb7848b1facb5d6b to tempfile /home/docker/tmp/GetImageBlob262252570
DEBU[0004] Downloaded 9a61b6b1315e6b457c31a03346ab94486a2f5397f4a82219bee01eead1c34c2e to tempfile /home/docker/tmp/GetImageBlob875333215
DEBU[0004] Downloaded 124e2127157f398735e5888601e8b02cf832e037ef951317bc0a4f6256723d7b to tempfile /home/docker/tmp/GetImageBlob062742019
DEBU[0004] Downloaded 8fb45e60e014d834ddb7aac0adf9985a35359b47f84aedc48b272b8662bdd528 to tempfile /home/docker/tmp/GetImageBlob082811270
DEBU[0006] Downloaded 8ddc08289e1a9e4413633bcc969369954a4d4605f56801428986e3b0b358446f to tempfile /home/docker/tmp/GetImageBlob213008946
DEBU[0007] Downloaded 1ff9f26f09fb1bc7b5955c269b1042429e86d7891c653f52f3e48f1e0365d7df to tempfile /home/docker/tmp/GetImageBlob590454449
DEBU[0007] Downloaded d86979befb725994b1c58c8340b3313f7b3118bf60c40972d520a43b2ea35f7f to tempfile /home/docker/tmp/GetImageBlob542231208
DEBU[0008] Downloaded 0f5121dd42a613481a72899ea1ac4620a909427cf81bc9edff59a2b85c8fc73f to tempfile /home/docker/tmp/GetImageBlob798060009
DEBU[0008] Downloaded 902b87aaaec929e80541486828959f14fa061f529ad7f37ab300d4ef9f3a0dbf to tempfile /home/docker/tmp/GetImageBlob099768037
DEBU[0008] Start untar layer
DEBU[0009] Downloaded 607e965985c11e6a23270feec487908aeaa9af763d24a2986866a41537770c8c to tempfile /home/docker/tmp/GetImageBlob869225728
DEBU[0014] Untar time: 6.02553522s
```

I tested current master (3a7b4230b2af1d44897499fee3c18f6b8e6ecde0) and the commit _before_ tar-split was introduced (c328e0c8274ab7b988e8c279f447a1074e3b0631). The behavior is exhibited on both, so it is unrelated to tar-split.

```bash
vbatts@noyee ~ (master) $ docker version
Client:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.5beta2
 Git commit:   c328e0c
 Built:        Tue Jul 28 14:58:30 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.5beta2
 Git commit:   c328e0c
 Built:        Tue Jul 28 14:58:30 UTC 2015
 OS/Arch:      linux/amd64
vbatts@noyee ~ (master) $ docker info
Containers: 0
Images: 24
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.6-300.fc22.x86_64
Operating System: Fedora 22 (Twenty Two)
CPUs: 4
Total Memory: 7.081 GiB
Name: noyee.usersys.redhat.com
ID: EOK5:2MLO:KGVZ:UCYR:N3H3:SBE4:2IPK:VAHK:4U6F:VO4G:FR2K:M5W3
Debug mode (server): true
File Descriptors: 13
Goroutines: 30
System Time: 2015-07-28T11:43:43.52049014-04:00
EventsListeners: 0
Init SHA1: c801c701ea1dc09fdb7a7188952dbd8b0abcba86
Init Path: /home/vbatts/src/docker/docker/bundles/1.8.0-dev/dynbinary/dockerinit
Docker Root Dir: /home/docker
Username: vbatts
Registry: https://index.docker.io/v1/
```

### LINKED ISSUE #15195: Deadlock when deleting images
When I run `docker rmi $(docker images -q -f dangling=true)` on one terminal while at the same time call the image list API via `curl -v http://127.0.0.1:2375/images/json` on another terminal, the daemon seems to be running into a dead lock.
```
goroutine 139 [semacquire, 60 minutes]:
sync.(*RWMutex).RLock(0xc2082d7e00)
	/usr/local/go/src/sync/rwmutex.go:36 +0x5f
github.com/docker/docker/pkg/truncindex.(*TruncIndex).Get(0xc2082d7e00, 0xc208410580, 0x40, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/pkg/truncindex/truncindex.go:111 +0x12b
github.com/docker/docker/graph.(*Graph).Get(0xc20817cb80, 0xc208410580, 0x40, 0xc2092074c0, 0x0, 0x0)
	/go/src/github.com/docker/docker/graph/graph.go:173 +0x69

......

goroutine 230 [semacquire, 60 minutes]:
sync.(*RWMutex).Lock(0xc2082d7e00)
    /usr/local/go/src/sync/rwmutex.go:87 +0xa4
github.com/docker/docker/pkg/truncindex.(*TruncIndex).Delete(0xc2082d7e00, 0xc209947640, 0x40, 0x0, 0x0) 
    /go/src/github.com/docker/docker/pkg/truncindex/truncindex.go:80 +0x56
github.com/docker/docker/graph.(*Graph).Delete(0xc20817cb80, 0xc2093ed100, 0x40, 0x0, 0x0) 
    /go/src/github.com/docker/docker/graph/graph.go:360 +0x125
github.com/docker/docker/daemon.(*Daemon).imgDeleteHelper(0xc2080efce0, 0xc20888fb45, 0xc, 0xc2093e02a0, 0x1, 0x0, 0x0) 
    /go/src/github.com/docker/docker/daemon/image_delete.go:120 +0xea5
github.com/docker/docker/daemon.(*Daemon).ImageDelete(0xc2080efce0, 0xc20888fb45, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0) 
    /go/src/github.com/docker/docker/daemon/image_delete.go:19 +0x122
github.com/docker/docker/api/server.(*Server).deleteImages(0xc208035300, 0xc20888fb39, 0x4, 0x7fb50589f038, 0xc208701540, 0xc208eff6c0, 0xc20888fcb0, 0x0, 0x0)
```

The full stack via pprof is here https://gist.github.com/mountkin/079210d66370ed99bc03
I also encountered another deadlock while I ran `docker build` on one terminal and call the image list API on another terminal.

After bisecting I found before cc955ae73c8aa234e0c41bdb65f111be79b32b90 everything is ok.

I'm not sure if this is related to @vbatts's issue #15087 

---
To make @GordonTheTurtle happy,
docker info
```
Containers: 26
Images: 933
Storage Driver: aufs
 Root Dir: /root/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1028
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 2
Total Memory: 994 MiB
Name: local-dev
ID: LD3D:36J2:EXD2:2TA6:DJYU:ZLPK:W3BS:VHHH:VFA2:URJD:OID6:QJ2Y
Debug mode (server): true
File Descriptors: 31
Goroutines: 52
System Time: 2015-07-31T14:46:00.021003093+08:00
EventsListeners: 0
Init SHA1: 
Init Path: /usr/bin/docker
Docker Root Dir: /root/docker
Username: csphere
Registry: https://index.docker.io/v1/
```

docker version
```
Client:
 Version:      1.8.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   500a314
 Built:        Fri Jul 31 06:45:08 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   500a314
 Built:        Fri Jul 31 06:45:08 UTC 2015
 OS/Arch:      linux/amd64
```

uname-a
```
Linux local-dev 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

### LINKED ISSUE #15205: [1.8.0-rc1] docker-engine deadlocks under concurrent operations
## Summary

Under a workload that we find common on our build nodes, Docker Engine will block irrecoverably after some amount of time.

## System Info

```
$ docker info
Client:
 Version:      1.8.0-rc1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   4f1c66a
 Built:        Sat Jul 25 05:54:28 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.0-rc1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   4f1c66a
 Built:        Sat Jul 25 05:54:28 UTC 2015
 OS/Arch:      linux/amd64
```

```
$ uname -r
3.18.8-031808-generic
```

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"
```

```
$ ps -axo command | grep '[d]ocker daemon'
/usr/bin/docker daemon --graph='/u/lib/docker' --host='unix:///var/run/docker.sock' --restart=false --host=127.0.0.1:4445 --storage-driver='overlay' --debug --dns=172.17.42.1 --dns=8.8.8.8
```

## To reproduce

*26c8 is a Shopify image – large, on the order of 1GB, with >50k files. This may or may not be important, but it likely influences the amount of time spent in a deadlock-prone mutex region.*

```
docker run -it --entrypoint=/bin/bash --rm=false 26c8 -l
# (get back image ID of be5)
```

#### Terminal 1

```
while [ 1 ] ; do a=$(docker commit be5); docker rmi $a; done
```

#### Terminal 2

```
while [ 1 ] ; do a=$(docker commit be5); docker rmi $a; done
```

#### Terminal 3

```
while [ 1 ] ; do docker run --entrypoint=/bin/true --rm=true 26c8 -l; echo .; done
```

#### Terminal 4

```
while [ 1 ] ; do time docker inspect --format=. 26c8; done
```

## Expected Result

Everything chugs along, possibly slowing down due to heavy load.

## Actual Result

After some variable amount of time, typically on the order of 1-3 minutes, the
jobs in all terminals lock up, presumably in the daemon.  Many or most new
types of API access will not return. `docker ps` continues to work.

## Backtrace during hang

https://gist.github.com/burke/0f8f3d46166fa09d24ec

### PR DESCRIPTION
**Pull request by calavera**
Let the iterator to lock the index when it needs it.

Tests provided by @mountkin.

Fixes #15195 
Fixes #15087
Fixes #15205

/cc @vbatts

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

File: integration-cli/graph_deadlock_test.go [hunk 1]
```diff
@@ -0,0 +1,90 @@
...
+	go func() {
+		_, err := buildImage("dummy", dockerfile, false)
+		c.Assert(err, check.IsNil)
+		close(ch)
+	}()
+
+	go func() {
+		<-time.After(5 * time.Minute)
+		_, out, err := sockRequest("GET", "/debug/pprof/goroutine?debug=2", nil)
+		c.Assert(err, check.IsNil)
```
Comment (LK4D4) [inline integration-cli/graph_deadlock_test.go]: Nor fatal, nor asset should be in goroutines.

File: integration-cli/graph_deadlock_test.go [hunk 2]
```diff
@@ -0,0 +1,90 @@
...
+	`
+	ch := make(chan struct{})
+	go func() {
+		_, err := buildImage("dummy", dockerfile, false)
+		c.Assert(err, check.IsNil)
+		close(ch)
+	}()
+
+	go func() {
+		<-time.After(5 * time.Minute)
```
Comment (LK4D4) [inline integration-cli/graph_deadlock_test.go]: Isn't it too big timeout for this?

Comment (calavera) [inline integration-cli/graph_deadlock_test.go]: yeah, I only copy/pasted the tests to make sure this changed fixed the issue. Setting a shorter timeout.

**Comment by vbatts** [comment]
LGTM and it does fix #15087 for me

**Comment by vbatts** [comment]
\o/

**Comment by burke** [comment]
:100: Fixes #15205 also, thanks!

File: integration-cli/graph_deadlock_test.go [hunk 3]
```diff
@@ -0,0 +1,76 @@
...
+	ch := make(chan struct{})
+	go func() {
+		dockerCmd(c, "rmi", id)
+		close(ch)
+	}()
+
+	for i := 0; i < 100; i++ {
+		dockerCmd(c, "images")
+	}
+	<-ch
```
Comment (LK4D4) [inline integration-cli/graph_deadlock_test.go]: I don't get this trick :)

File: integration-cli/graph_deadlock_test.go [hunk 4]
```diff
@@ -0,0 +1,76 @@
...
+	RUN ps -ef >/ps4.txt
+	RUN ps -ef >/ps5.txt
+	RUN ps -ef >/ps6.txt
+	`
+	id, err := buildImage("dummy", dockerfile, false)
+	c.Assert(err, check.IsNil)
+
+	ch := make(chan struct{})
+	go func() {
+		dockerCmd(c, "rmi", id)
```
Comment (LK4D4) [inline integration-cli/graph_deadlock_test.go]: here you call `Assert` inside goroutine, test will pass even eve there will be error there

File: integration-cli/graph_deadlock_test.go (hunk 3 above)
Comment (calavera) [inline integration-cli/graph_deadlock_test.go]: me neither.

Comment (burke) [inline integration-cli/graph_deadlock_test.go]: It's just making sure that the `rmi` is complete before moving on, equivalent to

```
wg.Add(1)
go func() {
  rmi
  wg.Done()
}()

for things { stuff }
wg.Wait()
```

Otherwise if the `rmi` deadlocked the function would return anyway and not care.

**Comment by LK4D4** [comment]
I think both tests doing it wrong. You should run `images` goroutine first and only then call `rmi` and `build`.

File: integration-cli/graph_deadlock_test.go [hunk 5]
```diff
@@ -0,0 +1,76 @@
...
+	var err error
+	go func() {
+		_, err = buildImage("dummy", dockerfile, false)
+		close(ch)
+	}()
+
+	for i := 0; i < 100; i++ {
+		dockerCmd(c, "images")
+	}
+	<-ch
```
Comment (LK4D4) [inline integration-cli/graph_deadlock_test.go]: here should be timeout I think

File: integration-cli/graph_deadlock_test.go (hunk 4 above)
Comment (mountkin) [inline integration-cli/graph_deadlock_test.go]: This is just testing the deadlock, I think other errors can be ignored here.
Or if it really matters we can call dockerCmdWithError and return the error through a channel and check it outside of the routine.

**Comment by mountkin** [comment]
https://github.com/mountkin/docker/commit/83c6e4e49d1c8567c9e4e296bf86727210dc4935 Here is another fix but I'm unable to test it with my phone.

**Comment by calavera** [comment]
@LK4D4 can you check the tests now?

**Comment by LK4D4** [comment]
Whatever :) Tests hanged on my machine. I should ask, do we really want to add 3 minutes(or possibly eternity) to test just to test this deadlock? :)

**Comment by calavera** [comment]
@LK4D4 probably not, but maybe we don't need to create those 50 images either.

**Comment by tiborvass** [comment]
LGTM, because `trie` doesn't need to be guarded, it's just set once at creation and never reset anywhere.

**Comment by calavera** [comment]
two LGTM already from maintainers. Merging! :tada:

**Comment by calavera** [comment]
cherry picked into #15091
