### PR TITLE
volume: mask password in cifs mount error messages

### LINKED ISSUE #905: Error message may leak credentials used for mounting
I opened https://github.com/hashicorp/nomad/issues/12296 because we observed that nomad logs would openly display credentials used for (cifs) mounts when the mounting failed (e.g. because of a mistyped server path) and was told that the error is from go-dockerclient, so that it might make sense to discuss the problem here as well.

When we're trying to mount a server share into a docker container with options like
```
{
    "device": "//servername.organization.lan/share/path/does/not/exist/",
    "o": "addr=servername.organization.lan,_netdev,iocharset=utf8,noperm,uid=0,gid=0,username=${MOUNT_USERNAME},password=${MOUNT_PASSWORD},domain=org_domain",
    "type": "cifs"
}
```
the error message looks like
```
error while mounting volume '/var/lib/docker/volumes/mount_input_3f6a4f51-3b97-2b0a-3dc1-f14cad6a5bb9/_data':
failed to mount local volume:
mount //servername.organization.lan/share/path/does/not/exist/:/var/lib/docker/volumes/mount_input_3f6a4f51-3b97-2b0a-3dc1-f14cad6a5bb9/_data,
data: addr=11.22.33.44,_netdev,iocharset=utf8,noperm,uid=0,gid=0,username=secret_user,password=secret_password_in_plaintext,domain=org_domain: no such file or directory
```
for example.  (I added a few linebreaks this time in order to make the output easier to read, since the important part is at the end of the rather long message.)

I think everyone would be happy if there was an alternative way to specify the password (via a file, for instance) so that it does not appear in the options in the first place.  A colleague looked into this, but as far as I understood him, the way the mounting currently happens via a syscall does not allow this option (which seems to be handled by `mount.cifs` client-side, usually.)

### LINKED ISSUE #12296: Mount secrets are revealed in log messages
### Nomad version
v1.0.4 (from web interface)

### Issue
We run a nomad cluster in which it is possible to run data science jobs that access private data via custom mounts, the secrets for which are stored in Vault.  The vault secret and the mount password are properly hidden during normal operation, but we offer a way for users to type in custom mount paths into a form, and mistyping a path results in a mount error.

**The mount error which is visible in the nomad web UI visibly displays the secret.**

### Reproduction steps
* Make credentials for a cifs mount accessible via Vault (the mount does not have to exist, since we want to provoke an error anyhow).
* Set up a job with a custom mount (snippet from job description given below), in which the UNC source path is misspelt.
* Run job (which should fail to set up).
* Observe mount error in logs available via the web UI.
```
"mount": [
              {
                "target": "/private_input",
                "type": "volume",
                "volume_options": [
                  {
                    "driver_config": [
                      {
                        "options": [
                          {
                            "device": "//servername.organization.lan/share/path/does/not/exist/",
                            "o": "addr=servername.organization.lan,_netdev,iocharset=utf8,noperm,uid=0,gid=0,username=${MOUNT_USERNAME},password=${MOUNT_PASSWORD},domain=org_domain",
                            "type": "cifs"
                          }
                        ],
                        "name": "local"
                      }
                    ]
                  }
                ],
                "source": "some_volume_name"
              },
```

#### Expected Result
The logged mount error should censor the secret, and/or an alternative way to specify the secret should be available.

(Alas, we learned that the `credentials=/path/to/file` is a feature of mount.cifs, and not of the underlying kernel module, which nomad talks to via sysctls.)

#### Actual Result
The log contains a line such as
```
Failed to start container 9acd605a012f83f2a40841151608c5ff9657e10bc168bc085eed3ddc5253fbaa: API error (500): error while mounting volume '/var/lib/docker/volumes/mount_input_3f6a4f51-3b97-2b0a-3dc1-f14cad6a5bb9/_data': failed to mount local volume: mount //servername.organization.lan/share/path/does/not/exist/:/var/lib/docker/volumes/mount_input_3f6a4f51-3b97-2b0a-3dc1-f14cad6a5bb9/_data, data: addr=11.22.33.44,_netdev,iocharset=utf8,noperm,uid=0,gid=0,username=secret_user,password=secret_password_in_plaintext,domain=org_domain: no such file or directory
```

### Job file (if appropriate)
Our setup is quite complex and the jobs are created on the fly via the Rest API, so I find it very difficult to provide a full example, which would not work in other contexts anyhow. I hope the above part of the job definition helps to understand the issue well enough.

(I consider this to be a security-relevant bug, but decided for public posting, because it requires a fairly special setup such as ours to cause problems. It does not seem to be exploitable by an attacker, but may cause problems with credentials leaked by accident through errors which just happen.)

### LINKED ISSUE #43596: CIFS passwords in user facing error messages
**Description**

For cifs mounts, sensitive passwords might be leaked in user facing error messages.
This is the case when, e.g., using hashicorp's nomad with secret credentials from vault (For details, please refer to https://github.com/hashicorp/nomad/issues/12296 and https://github.com/fsouza/go-dockerclient/issues/905).
While this is kind of a security issue, it's not really one as the credentials would be accessible via inspect, debug logs, or, if not using docker, in fstab anyways.

**Steps to reproduce the issue:**
1. Create a cifs volume, the exact parameters do not matter, they should contain a password and be wrong, however:
    ```console
    $ docker volume create --driver local --opt type=cifs --opt "o=username=shoeffner,password=supersecretpassword,iocharset=utf8,file_mode=0777,dir_mode=0777" --opt device=//192.168.1.2/Public cifstest
    ```
2. Mount the volume:
    ```console
    $ docker run --rm -it -v cifstest:/themnt busybox bash
    docker: Error response from daemon: error while mounting volume '/var/lib/docker/volumes/cifstest/_data': failed to mount local volume: mount //192.168.1.2/Public:/var/lib/docker/volumes/cifstest/_data, data: username=shoeffner,password=supersecretpassword,iocharset=utf8,file_mode=0777,dir_mode=0777: permission denied.
    ```

**Describe the results you received:**
See above, the password is printed.

**Describe the results you expected:**
The password is masked.

**Output of `docker version`:**
```
Client:
 Cloud integration: v1.0.24
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:49:20 2022
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.8.1 (78998)
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:46:14 2022
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.5.0)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 5
  Running: 4
  Paused: 0
  Stopped: 1
 Images: 75
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.104-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 5.805GiB
 Name: docker-desktop
 ID: Y73E:KR3O:P4QW:7L24:EPPL:5TCD:Y5CZ:OLLL:4GDX:F2L5:BLIT:ZRDK
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 73
  Goroutines: 68
  System Time: 2022-05-13T15:37:23.358481893Z
  EventsListeners: 4
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Happens on Linux, macOS. Windows does not allow to even attempt to use cifs mounts (though I tried when testing my fix).

### PR DESCRIPTION
**Pull request by shoeffner**
In managed environment (such as Nomad clusters), users are not always
supposed to see credentials used to mount volumes.
However, if errors occur (most commonly, misspelled mount paths), the
error messages will output the full mount command -- which might contain
a username and a password in the case of CIFS mounts.

This PR detects password=... when error messages are wrapped and masks
them with ********.

Closes https://github.com/fsouza/go-dockerclient/issues/905.
Closes https://github.com/hashicorp/nomad/issues/12296.
Closes https://github.com/moby/moby/issues/43596.

Signed-off-by: Sebastian Höffner <sebastian.hoeffner@mevis.fraunhofer.de>

**- What I did**
In the error handler for cifs mounts, `password=...` will be masked with `********` in user facing error messages.

**- How I did it**
- Added `func getPassword(opts string) string` in line with `getAddr` (could potentially be refactored into something such as `func getOption(opt string, opts string) string`)
- Added unit tests for getPassword
- Replaced `password=[detectedPassword]` with `password=********`

**- How to verify it**
Was:
```console
$ docker volume create --driver local --opt type=cifs --opt "o=username=shoeffner,password=supersecretpassword,iocharset=utf8,file_mode=0777,dir_mode=0777" --opt device=//192.168.1.2/Public cifstest
$ docker run --rm -it -v cifstest:/themnt busybox bash
docker: Error response from daemon: error while mounting volume '/var/lib/docker/volumes/cifstest/_data': failed to mount local volume: mount //192.168.1.2/Public:/var/lib/docker/volumes/cifstest/_data, data: username=shoeffner,password=supersecretpassword,iocharset=utf8,file_mode=0777,dir_mode=0777: permission denied.
```
Is:
```console
$ docker volume create --driver local --opt type=cifs --opt "o=username=shoeffner,password=supersecretpassword,iocharset=utf8,file_mode=0777,dir_mode=0777" --opt device=//192.168.1.2/Public cifstest
$ docker run --rm -it -v cifstest:/themnt busybox bash
docker: Error response from daemon: error while mounting volume '/var/lib/docker/volumes/cifstest/_data': failed to mount local volume: mount //192.168.1.2/Public:/var/lib/docker/volumes/cifstest/_data, data: username=shoeffner,password=********,iocharset=utf8,file_mode=0777,dir_mode=0777: permission denied.
```

**- Description for the changelog**

Passwords in user facing error messages for CIFS mounts are masked.

**- A picture of a cute animal (not mandatory but encouraged)**

image
https://www.pexels.com/photo/cold-nature-cute-ice-52509/

### CODE REVIEW

File: volume/local/local_unix.go [hunk 1]
```diff
@@ -141,6 +141,9 @@ func (v *localVolume) mount() error {
 			}
 			mountOpts = strings.Replace(mountOpts, "addr="+addrValue, "addr="+ipAddr.String(), 1)
 		}
+		if password := getPassword(v.opts.MountOpts); password != "" {
+			mountOpts = strings.Replace(mountOpts, "password="+password, "password=********", 1)
+		}
 	}
 	err := mount.Mount(v.opts.MountDevice, v.path, v.opts.MountType, mountOpts)
```
Comment (thaJeztah) [inline volume/local/local_unix.go:148]: Doesn't this remove the actual password from the options used to mount?

**Comment by shoeffner** [comment]
Well, this is embarrassing now :D
You are right, I thought this was an error handler, but misread the
function signature. I only tested the "broken" case and didn't realize I
broke the functionality...
Let me get back at this, it's probably possible to do the replace on the
err.

**Comment by thaJeztah** [comment]
I'm also wondering if these options would still be leaking in other ways (e.g., would `mount` show them? `docker volume inspect` ?) -I haven't checked, but mostly thinking out loud. Passing a password as command line arg is, erm, well, never ideal.

So, I'm ok with fixing the error, but it still somewhat tapers over the issue 😅

**Comment by shoeffner** [comment]
You are completely right that it will still be possible to use `inspect`, and there are many other ways. But in the particular use case in https://github.com/hashicorp/nomad/issues/12296#issue-1169667160, the user will only see `username=${MOUNT_USERNAME},password=${MOUNT_PASSWORD}` in their configuration; Nomad will fill those environment variables with secrets from Vault. Thus, in normal (successful) operation, a user will never see those parameters. But if they got some options wrong, most often this happens with the path they want to mount, this will be logged very prominently in the Nomad web UI. And of course, requesting support, users will copy, screenshot, etc. those errors without further thinking, accidentally leaking the passwords to various chats, forums, etc...

So while this will not help to stop nefarious actors from stealing credentials, it will make the surface for unintentional copying slightly smaller – in the case of Nomad it should almost vanish.

For me, this was the most obvious solution to fix this, but now that you question this, I checked the docs (https://linux.die.net/man/8/mount.cifs) and it seems to be possible to provide a credentials file: `credentials=...`. Maybe that might actually be a better solution than "hiding" the fact that the password is still readable. Do you happen to know if that works with docker, and if that file should be on the host system or inside the container?

I updated the code to replace the password inside the error message instead of the oroginal mount options. However, if you think the clean solution is to use the credentials file (and it is somehow possible), then it is perfectly fine to not move forward with this PR.

**Comment by hmeine** [comment]
I think another colleague looked into passing the credentials via files at first, but IIUC, credential files are handled by the `mount` tool itself, not actually supported by the kernel. (I don't know, maybe it would give rise to a different set of issues if the syscall handler would have to read files for the credentials. OTOH mounting is not exactly functionality that can entirely ignore filesystems…)

**Comment by thaJeztah** [comment]
> it seems to be possible to provide a credentials file: credentials=....

>  think another colleague looked into passing the credentials via files at first, but IIUC, credential files are handled by the mount tool itself, not actually supported by the kernel. 

Yes, correct; I think there's some existing discussions around that; the docker daemon uses a plain mount, and won't use the mount tool / helpers. (Also see the discussion in https://github.com/docker/cli/issues/2802, but there may be other tickets discussing that)

File: volume/local/local_unix.go [hunk 2]
```diff
@@ -143,6 +143,11 @@ func (v *localVolume) mount() error {
 		}
 	}
 	err := mount.Mount(v.opts.MountDevice, v.path, v.opts.MountType, mountOpts)
+	if err != nil {
+		if password := getPassword(v.opts.MountOpts); password != "" {
+			err = errors.New(strings.Replace(err.Error(), "password="+password, "password=********", 1))
+		}
```
Comment (thaJeztah) [inline volume/local/local_unix.go:149]: The only concern I have with this, is that this can hide the underlying error-type, which would prevent detecting (e.g.) `errors.Is(err, fs.NotExist)`.

It looks like currently we don't do any detection of error-types, and consider any error to be a "500" (internal server error) (probably not correct either for this case 🤔 but that's a separate issue); https://github.com/moby/moby/blob/4cac624fefefb7bb6640f205587d0dc0a9651b27/volume/local/local.go#L315-L317

Let me at least get some eyes from @cpuguy83 on this as well

**Review by thaJeztah — APPROVED** [review]
LGTM

discussed this in the maintainers meeting, and there were no big concerns with masking the original error

File: volume/local/local.go [hunk 3]
```diff
@@ -366,3 +366,15 @@ func getAddress(opts string) string {
...
+func getPassword(opts string) string {
+	optsList := strings.Split(opts, ",")
+	for i := 0; i < len(optsList); i++ {
+		if strings.HasPrefix(optsList[i], "password=") {
+			passwd := strings.SplitN(optsList[i], "=", 2)[1]
+			return passwd
+		}
+	}
+	return ""
+}
```
Comment (tianon) [inline volume/local/local.go:380]: I was concerned about this implementation, but in `mount.cifs` we have the following delightful gem: :see_no_evil: :heart:

```
              Note  that  a  password  which  contains the delimiter character
              (i.e. a comma ',') will fail to be parsed correctly on the  com‐
              mand  line. However, the same password defined in the PASSWD en‐
              vironment variable or via a credentials file (see below) or  en‐
              tered at the password prompt will be read correctly.
```

**Review by tianon — APPROVED** [review]
It seems a little bit hacky, but overall sane/simple enough IMO :+1: :smile:

**Comment by thaJeztah** [comment]
> It seems a little bit hacky, but overall sane/simple enough IMO 👍 

This could would only be hit in case of an error, so while (perhaps) optimisations could be made, it won't affect the regular code paths, so I think that's fine.


let's get this one in 👍

**Comment by shoeffner** [comment]
Sure, if there is a way to keep the original error type, I will gladly
change that.
I think I copied the error.New from somewhere else in the code base, I'll
take a look later today if it's handled there.
