### PR TITLE
Fix misleading defaults for service create/update

### LINKED ISSUE #29291: Misleading default for --replicas
The help text for `--replicas` on `service update` and `service create` says the default is "none".

```
      --replicas uint                    Number of tasks (default none)
```

In fact, creating a replicated service without `--replicas` uses 1 replica, not zero as this description might suggest.

### PR DESCRIPTION
**Pull request by yongtang**
**- What I did**

This fix tries to address the issue raised in #29291 where the output of `--replicas`, `--restart-delay`, `--restart-max-attempts`, and `--stop-grace-period` in `service create/update`:
```
      --replicas uint                    Number of tasks (default none)
...
      --restart-delay duration           Delay between restart attempts (ns|us|ms|s|m|h) (default none)
      --restart-max-attempts uint        Maximum number of restarts before giving up (default none)
...
      --stop-grace-period duration       Time to wait before force killing a container (ns|us|ms|s|m|h) (default none)
```
are misleading. For example, user might incorrectly assume the number of replicas would be `0` (`none`) by default, while the actual default is `1`.

The issue comes from the fact that some of the default values are from daemon and it is not possible for client to find out the default value.

In this case, it might be better to just simply not displaying `(default none)`.

**- How I did it**

This fix set a `noDefaultValue bool` in `Uint64Opt` so that it is possible to switch on/off the output of `(default none)` for `Uint64Opt`. This fix also sets `noDefaultValue bool` in `DurationOpt` in a similar fashion.

New Output:
```
      --replicas uint                    Number of tasks
...
      --restart-delay duration           Delay between restart attempts (ns|us|ms|s|m|h)
      --restart-max-attempts uint        Maximum number of restarts before giving up
...
      --stop-grace-period duration       Time to wait before force killing a container (ns|us|ms|s|m|h)
```

The docs has been updated. Note the docs for help output of `service create/update` is out of sync with the current master. This fix replace with the update to date help output.

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

world-s-cutest-kitten

This fix fixes #29291.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by aaronlehmann** [comment]
LGTM

I think we should do the same for `--restart-delay`, `--restart-max-attempts`, and `--stop-grace-period`.

That can be a separate PR if you want.

**Comment by yongtang** [comment]
Thanks @aaronlehmann. The PR has been updated.

**Comment by aaronlehmann** [comment]
Thanks. Mind updating the PR summary/description?

**Comment by yongtang** [comment]
Thanks @aaronlehmann. Done.

**Comment by aaronlehmann** [comment]
I changed the summary so it's not specific to `--replicas` anymore.

LGTM

This also makes the help output a bit easier to read.

My only hesitation is that I wonder if we should have `defaultValue bool` instead of `noDefaultValue bool`. But I don't have strong feelings about this.

File: cli/command/service/opts.go [hunk 1]
```diff
@@ -64,7 +64,8 @@ func (d *PositiveDurationOpt) Set(s string) error {
 // DurationOpt is an option type for time.Duration that uses a pointer. This
 // allows us to get nil values outside, instead of defaulting to 0
 type DurationOpt struct {
-	value *time.Duration
+	value          *time.Duration
+	noDefaultValue bool
```
Comment (thaJeztah) [inline cli/command/service/opts.go]: perhaps `hideDefaultValue`? @aaronlehmann ?

Comment (aaronlehmann) [inline cli/command/service/opts.go]: That's fine with me.

**Comment by yongtang** [comment]
Thanks @aaronlehmann @thaJeztah The PR has been updated.

File: cli/command/service/opts.go [hunk 2]
```diff
@@ -114,6 +124,10 @@ func (i *Uint64Opt) String() string {
 	if i.value != nil {
 		return fmt.Sprintf("%v", *i.value)
 	}
+	if i.hideDefaultValue {
+		// Not display `(default none)`
+		return ""
+	}
```
Comment (dnephin) [inline cli/command/service/opts.go]: It seems like we'll always want this as the default value. Maybe instead of a flag we should just default to `""` in all cases instead of `"none"`?

**Comment by yongtang** [comment]
Thanks @dnephin for the review. Currently there are 3 more flags in `docker service create/update` that still use `none`:
```
      --health-interval duration         Time between running the check (ns|us|ms|s|m|h) (default none)
      --health-timeout duration          Maximum time to allow one check to run (ns|us|ms|s|m|h) (default none)
      --restart-window duration          Window used to evaluate the restart policy (ns|us|ms|s|m|h) (default none)`
```

/cc @aaronlehmann

**Comment by aaronlehmann** [comment]
I would be okay with removing `(default none)` from those remaining flags, but it is not technically wrong in those cases.

**Comment by yongtang** [comment]
Thanks @aaronlehmann @dnephin. The PR has been updated.

**Comment by aaronlehmann** [comment]
LGTM

File: docs/reference/commandline/service_create.md [hunk 3]
```diff
@@ -47,16 +47,16 @@ Options:
       --name string                      Service name
       --network list                     Network attachments (default [])
       --no-healthcheck                   Disable any container-specified HEALTHCHECK
-  -p, --publish list                     Publish a port as a node port (default [])
-      --replicas uint                    Number of tasks (default none)
+  -p, --publish port                     Publish a port as a node port
```
Comment (thaJeztah) [inline docs/reference/commandline/service_create.md]: Should we change this one to show "list" as well (not in this PR) @dnephin? We may want to find a way to express which flags can be set multiple times

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by dnephin — APPROVED** [review]
LGTM

**Comment by aaronlehmann** [comment]
Should we consider backporting this to a 1.13 patch release? I noticed that 1.13 still has the confusing `(default none)` in the help output.

**Comment by vieux** [comment]
@aaronlehmann done

**Comment by aaronlehmann** [comment]
@vieux: Thanks!
