### PR TITLE
Only set up an L3-ipvlan's default route when it's the gateway endpoint

### LINKED ISSUE #48576: Containers connected to both non-internal IPvlan L3 and Bridge networks cannot be started (error setting interface routes to ["0.0.0.0/0"])
### Description

Attempting to start a container connected to both an IPvlan L3 network and a Bridge network yields the error shown below, and does not start the container. This does not occur if either of the networks are created with `--internal`.

Likely due to both networks wanting to set a default route in different ways?

### Reproduce

1. Create an IPvlan network:
`docker network create -d ipvlan --subnet 10.80.0.0/24 --gateway 10.80.0.254 -o ipvlan_mode=l3 -o parent=eth0 applications_network`
2. Create a Bridge network:
`docker network create -d bridge komodo`
3. Attempt to start a container using both networks:
`docker run -it --rm --network applications_network --network komodo alpine`
4. Error message will show something similar to:
`docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: failed to add interface veth7f672f9 to sandbox: error setting interface "veth7f672f9" routes to ["0.0.0.0/0"]: file exists: unknown.`

Attempting to attach the container to the network after it has been started with a single network also fails:
- Starting with IPvlan, connecting to Bridge:
`Error response from daemon: failed to set gateway while updating gateway: file exists`
- Starting with Bridge, connecting to IPvlan:
`Error response from daemon: failed to add interface veth4e022de to sandbox: error setting interface "veth4e022de" routes to ["0.0.0.0/0"]: file exists`

Note that creating either network with `--internal` will allow the container to run:
1. Create an internal IPvlan or Bridge network:
  a. `docker network create -d ipvlan --subnet 10.80.0.0/24 --gateway 10.80.0.254 -o ipvlan_mode=l3 -o parent=eth0 --internal applications_network`, OR
  b. `docker network create -d bridge --internal komodo`
2. Create the respective other network without the internal flag.
3. Start a container using both networks:
`docker run -it --rm --network applications_network --network komodo alpine`

Edit: Just realised `gateway` was unnecessary for l3 ipvlans. Issue remains without it.

Routes from the container with IPvlan set to internal:
```
/ # ip route
default via 10.64.0.1 dev eth0
10.64.0.0/22 dev eth0 scope link  src 10.64.0.2
10.80.0.0/24 dev eth1 scope link  src 10.80.0.1
/ # route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.64.0.1       0.0.0.0         UG    0      0        0 eth0
10.64.0.0       0.0.0.0         255.255.252.0   U     0      0        0 eth0
10.80.0.0       0.0.0.0         255.255.255.0   U     0      0        0 eth1
```

Routes from the container with Bridge set to internal:
```
/ # ip route
default dev eth0 scope link
10.64.0.0/22 dev eth1 scope link  src 10.64.0.2
10.80.0.0/24 dev eth0 scope link  src 10.80.0.1
/ # route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         0.0.0.0         0.0.0.0         U     0      0        0 eth0
10.64.0.0       0.0.0.0         255.255.252.0   U     0      0        0 eth1
10.80.0.0       0.0.0.0         255.255.255.0   U     0      0        0 eth0
```

In all cases, a static route was correctly created for `10.80.0.0/24` in the router, if that matters.

### Expected behavior

The container will be connected to both networks.

The planned usecase was having a reverse proxy accessible to LAN with an IPvlan network, and joining it to the many bridge networks that the applications are connected to.

### docker version

```bash
Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:41:11 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:41:11 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.22
  GitCommit:        7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc:
  Version:          1.1.14
  GitCommit:        v1.1.14-0-g2c9f560
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.12-1-pve
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 18GiB
 Name: lxc-dockerapps
 ID: 88159cb8-d8eb-4840-8d83-965124243221
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true
 Default Address Pools:
   Base: 10.64.0.0/12, Size: 22
```

### Additional Info

The system is a priviliged LXC running on a Proxmox host, but I also tested this issue on a fresh Debian VM with the same outcome.

### PR DESCRIPTION
**Pull request by robmry**
**- What I did**

- fixes https://github.com/moby/moby/issues/48576

It wasn't possible to connect a container to a layer-3 ipvlan network as well as a bridge networks ... because they both had their own ideas about how to set up a default route.

See https://github.com/moby/moby/issues/48576#issuecomment-2418979480 for the analysis.

**- How I did it**

- Made libnetwork understand that an Interface route with destination 0.0.0.0/:: is equivalent to a default gateway.
  - `getGatewayEndpoint` includes `routes` as well as gateways in its search.
  - Include those routes in the ordering over Endpoints that's used to select a gateway.
- Only set up connected default routes when the ipvlan network is selected as the container's gateway.
  - Don't apply those routes when joining the endpoint to a sandbox.
  - Add/remove the routes when configuring the gateway endpoint.

**- How to verify it**

New integration test.

**- Description for the changelog**
```markdown changelog
- fixed an issue that meant a container could not be attached to an L3 ipvlan at the same time as other network types
```

### CODE REVIEW

File: libnetwork/default_gateway.go [hunk 1]
```diff
@@ -189,8 +189,7 @@ func selectGatewayEndpoint(endpoints []*Endpoint) (ep4, ep6 *Endpoint) {
 		if ep.getNetwork().Type() == "null" || ep.getNetwork().Type() == "host" {
 			continue
 		}
-		gw4 := len(ep.Gateway()) != 0
-		gw6 := len(ep.GatewayIPv6()) != 0
+		gw4, gw6 := ep.hasGatewayOrDefaultRoute()
 		if gw4 && gw6 {
 			return ep, ep
```
Comment (thaJeztah) [inline libnetwork/default_gateway.go:194]: In this branch, we unconditionally return `ep`, but the branches below, we only return `ep` if `ep4` or `ep6` is nil; that's correct?

File: libnetwork/sandbox_linux.go [hunk 2]
```diff
@@ -90,14 +90,26 @@ func (sb *Sandbox) updateGateway(ep4, ep6 *Endpoint) error {
...
 
-		if err := osSbox.SetGateway(joinInfo.gw); err != nil {
-			return fmt.Errorf("failed to set gateway while updating gateway: %v", err)
+		if joinInfo.gw != nil {
+			if err := osSbox.SetGateway(joinInfo.gw); err != nil {
+				return fmt.Errorf("failed to set gateway while updating gateway: %v", err)
+			}
+		} else {
+			if err := osSbox.SetDefaultRouteIPv4(ep4.iface.srcName); err != nil {
+				return fmt.Errorf("failed to set IPv4 default route while updating gateway: %v", err)
```
Comment (thaJeztah) [inline libnetwork/sandbox_linux.go:111]: Wondering if (part of) decorating the error should be in `SetDefaultRoute` and `SetGateway`, in that case, the caller of this `Sandbox,updateGateway` could just use a general decoration, instead of having to repeat the "while updating gateway" everywhere 🤔;


```go
if err := sb.updateGateway(gwepAfter4, gwepAfter6); err != nil {
	return fmt.Errorf("updating gateway: %w", err)
}
```

File: libnetwork/osl/route_linux.go [hunk 3]
```diff
@@ -3,6 +3,7 @@ package osl
 import (
 	"fmt"
 	"net"
+	"slices"
```
Comment (thaJeztah) [inline libnetwork/osl/route_linux.go:6]: can you add a `//go:build` in this file? Similar to https://github.com/moby/moby/blob/ca0e6af56c0601eead2f03b16aa83cd1f59946df/daemon/daemon_unix.go#L1-L3

File: integration/network/network_linux_test.go [hunk 4]
```diff
@@ -387,9 +388,83 @@ func checkCtrRoutes(t *testing.T, ctx context.Context, apiClient client.APIClien
...
+// ipvlan network as well as a bridge ... the bridge network will set up a
+// default gateway, if selected as the gateway endpoint. The ipvlan driver sets
+// up a connected route to 0.0.0.0 or [::], a route via a specific interface with
+// no next-hop address (because the next-hop address can't be ARP'd to determine
+// the interface). These two types of route cannot be set up at the same time.
+// So, the ipvlan's route must be treated like the default gateway and only get
+// set up when the ipvlan is selected as the gateway endpoint.
+// Regression test for https://github.com/moby/moby/issues/48576
+func TestMixL3IPVlanAndBridge(t *testing.T) {
+	skip.If(t, testEnv.DaemonInfo.OSType == "windows", "no ipvlan on Windows")
```
Comment (thaJeztah) [inline integration/network/network_linux_test.go:408]: Perhaps (not for this PR) we should add a utility to check whether the daemon supports `network-driver X`; `docker info` should return this, so we could use that for detecting instead of based on platform;

```bash
docker info --format='{{ json .Plugins.Network }}'
["bridge","host","ipvlan","macvlan","null","overlay"]
```

**Review by akerouanton — APPROVED** [review]
Beside @thaJeztah's comments, LGTM.

File: libnetwork/default_gateway.go (hunk 1 above)
Comment (robmry) [reply libnetwork/default_gateway.go]: Not changed in this PR, but yes - so that the first dual-stack network in the list is selected ... if there are only single-stack networks, it's searching for the first IPv4 and the first IPv6 endpoints.

Now gateway-priority is plumbed in, it's probably surprising that a dual-stack endpoints take priority over single stack endpoints with higher priorities. (But that's unrelated to this change.)

I'll add comments to the code saying that.

File: libnetwork/sandbox_linux.go (hunk 2 above)
Comment (robmry) [reply libnetwork/sandbox_linux.go]: Done.

File: libnetwork/osl/route_linux.go (hunk 3 above)
Comment (robmry) [reply libnetwork/osl/route_linux.go:9]: Done.

**Review by thaJeztah — APPROVED** [review]
LGTM (ci looks just an intermittent failure and needs a kick after it completes)
