### PR TITLE
Fix regression in handling of NotFound err during startup ENGCORE-929

### LINKED ISSUE #548: After updating Docker(Win10) and after PC restart all containers cannot be stopped or started
After updating Docker(Win10) and after PC restart all containers cannot work. You cannot stop it or run it again. It just stays there  and do nothing.
ERROR:
docker container error: an error occurred while sending the request. unable to connect to the remote server a connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

Note: i have changed the ip address of container and everithing is fine when i inspect container. But it cannot be stopped

### LINKED ISSUE #4463: Containers don't restart with docker service (2.1)
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 12CD9B90-4858-4838-9983-BD5D447BBC56/20190807123239

### Expected behavior
When the docker service is restarted, containers with an always restart policy are restarted.

### Actual behavior
When the docker service is restarted, container with an always restart policy are in an Exited status.

### Information

  - Windows Version: Windows 10 Pro 1903 Build 18362.175
  - Docker Desktop Version: 2.1.0.0 (36874)
  - Experimental Features:
    - On - Windows and Linux containers affected
    - Off - Windows containers affected, Linux containers behave as expected

This looks to be an issue restricted to the Windows daemon based on observations with Experimental Features.

Going through the logs, this stuck out at me:
```
[07:07:52.895][WindowsDaemon     ][Info   ] debug: Sending kill signal 15 to container 6baa8ec6084e8f9379bece4c0e8356012a7cfbb0f606cac32350e1ae27dc5b11
[07:07:52.895][WindowsDaemon     ][Info   ] debug: Signal() [process=init pid=306 signal=15 module=libcontainerd namespace=moby container=6baa8ec6084e8f9379bece4c0e8356012a7cfbb0f606cac32350e1ae27dc5b11]
[07:07:52.895][WindowsDaemon     ][Info   ] debug: hcsshim::ComputeSystem::Shutdown - Begin Operation [cid=6baa8ec6084e8f9379bece4c0e8356012a7cfbb0f606cac32350e1ae27dc5b11]
[07:07:52.908][WindowsDaemon     ][Info   ] debug: hcsshim::ComputeSystem::Shutdown - End Operation - Success [cid=6baa8ec6084e8f9379bece4c0e8356012a7cfbb0f606cac32350e1ae27dc5b11]
[07:08:22.908][WindowsDaemon     ][Info   ] Container 6baa8ec6084e8f9379bece4c0e8356012a7cfbb0f606cac32350e1ae27dc5b11 failed to exit within 30 seconds of signal 15 - using the force
[07:08:22.908][WindowsDaemon     ][Info   ] debug: Sending kill signal 9 to container 6baa8ec6084e8f9379bece4c0e8356012a7cfbb0f606cac32350e1ae27dc5b11
```

I'm also suspicious that this is related to #4399 and #4056, but I don't seem to get logs on system shutdown.

#### Experimental Features On - Windows and Linux containers
  1. run `docker run -d --restart always alpine watch ps -ef` to start a linux container
  1. run `docker run -d --restart always mcr.microsoft.com/windows/nanoserver:1903 ping -t localhost` to start a windows container
  1. If you run `docker ps`, you'll see the containers are up and running
  1. restart docker
  1. If you run `docker ps -a`, you'll see the containers are not running, but are in an exited state

#### Experimental Features Off - Windows Containers
  1. run `docker run -d --restart always mcr.microsoft.com/windows/nanoserver:1903 ping -t localhost` to start a windows container
  1. If you run `docker ps`, you'll see the containers are up and running
  1. restart docker
  1. If you run `docker ps -a`, you'll see the container is not running, but is in an exited state

#### Experimental Features Off - Linux Containers
  1. run `docker run -d --restart always alpine watch ps -ef` to start a linux container
  1. If you run `docker ps`, you'll see the containers are up and running
  1. restart docker
  1. If you run `docker ps -a`, you'll see the container is still running

### LINKED ISSUE #39623: After Windows Server 2019 boot containers not starting
**Description**

Windows Server 2019 does not start containers automatically on boot, even though the containers have been started with --restart always parameter.

**Steps to reproduce the issue:**

1. Open up elevated PowerShell.
2. Create a custom Docker network (driver nat), named blaa.
3. Run a container like this: docker run -d --restart always --name testcontainer -p 8080:80 mcr.microsoft.com/windows/servercore:ltsc2019.
4. Execute Restart-Computer.
When the machine starts up, execute docker ps.

**Describe the results you received:**
docker ps shows that no containers are running.

**Describe the results you expected:**
docker ps lists the container named testcontainer.

**Additional information you deem important (e.g. issue happens only occasionally):**
Happens all the time.

Windows Event Log shows errors like this:
Failed to delete container 80e440a586087ed6dd1bf14bb152061eadf15d5343a2dcf6b5b2dd14e0ad98fd from containerd [error=no such container]

**Output of `docker version`:**

```
Client: Docker Engine - Enterprise
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        f660560464
 Built:             07/25/2019 20:59:52
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.0
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.5
  Git commit:       87b1f470ad
  Built:            07/16/2019 23:39:21
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
PS C:\Users\Administrator> docker info
Client:
 Debug Mode: false
 Plugins:
  cluster: Manage Docker clusters (Docker Inc., v1.0.1)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 19.03.0
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics l2bridge l2tunnel nat null overlay transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Standard Version 1809 (OS Build 17763.615)
 OSType: windows
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.95GiB
 Name: 14450hostserveu
 ID: IJUZ:NS4Z:QY3W:DGOK:TTC4:6ZYV:Z4GW:QWS4:OFDV:XWCF:JUGI:PWW7
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Username: sevitechq
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Windows Server 2019 (Version 1809)

The same stuff worked in a older Windows Server 2016 environment (with a much older docker version).

I guess this is related to this issue:
https://github.com/moby/moby/issues/38911

I also tried this, but this should already be fixed :/ 
https://github.com/moby/moby/issues/33542

My workaround (which only work in some scenarios): Use a scheduled task to start all stopped contains like this:

    docker start $(docker ps -a -q -f status=exited)

### LINKED ISSUE #39742: Cannot kill a container on Windows Server 2019 running Docker 19.03.1
This is what I get in Application Event Log
```
debug: Sending kill signal 9 to container d94306d2d22a2b45d9f581f99bae6ac8b4fe249f95e4cfb7bf68890ab506fc2c
debug: container kill failed because of 'container not found' or 'no such process' [error=no such container container=d94306d2d22a2b45d9f581f99bae6ac8b4fe249f95e4cfb7bf68890ab506fc2c action=kill]
```

but `docker inspect` returns

```
[
    {
        "Id": "d94306d2d22a2b45d9f581f99bae6ac8b4fe249f95e4cfb7bf68890ab506fc2c",
        "Created": "2019-08-06T09:11:04.7342164Z",
        "Path": "cmd /S /C cmd /c ping -t localhost",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 9980,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2019-08-06T09:11:08.345674Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:99db41e70c8ba3064fa18bb92e6312008ae677d094a5fe52348502d13345568c",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "LogPath": "C:\\ProgramData\\docker\\containers\\d94306d2d22a2b45d9f581f99bae6ac8b4fe249f95e4cfb7bf68890ab506fc2c\\d94306d2d22a2b45d9f581f99bae6ac8b4fe249f95e4cfb7bf68890ab506fc2c-json.log",
        "Name": "/k8s_POD_submission-check-5c4f587ddf-s9lmr_submission-check_003a6b97-e6e3-4af5-9ef7-86a5e63ca817_0",
        "RestartCount": 0,
        "Driver": "windowsfilter",
        "Platform": "windows",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "none",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": -998,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "process",
            "CpuShares": 2,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": null,
            "ReadonlyPaths": null
        },
        "GraphDriver": {
            "Data": {
                "dir": "C:\\ProgramData\\docker\\windowsfilter\\d94306d2d22a2b45d9f581f99bae6ac8b4fe249f95e4cfb7bf68890ab506fc2c"
            },
            "Name": "windowsfilter"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "submission-check-5c4f587ddf-s9lmr",
            "Domainname": "",
            "User": "ContainerUser",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": [
                "cmd /S /C cmd /c ping -t localhost"
            ],
            "ArgsEscaped": true,
            "Image": "kubeletwin/pause",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "annotation.kubernetes.io/config.seen": "2019-08-06T02:11:04.1232578-07:00",
                "annotation.kubernetes.io/config.source": "api",
                "app": "submission-check",
                "io.kubernetes.container.name": "POD",
                "io.kubernetes.docker.type": "podsandbox",
                "io.kubernetes.pod.name": "submission-check-5c4f587ddf-s9lmr",
                "io.kubernetes.pod.namespace": "submission-check",
                "io.kubernetes.pod.uid": "003a6b97-e6e3-4af5-9ef7-86a5e63ca817",
                "pod-template-hash": "5c4f587ddf"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "d94306d2d22a2b45d9f581f99bae6ac8b4fe249f95e4cfb7bf68890ab506fc2c",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "d94306d2d22a2b45d9f581f99bae6ac8b4fe249f95e4cfb7bf68890ab506fc2c",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "none": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "8d5951599b7811fb09070ca3e673dba40cd947d0509d02018b6a43d2ce970036",
                    "EndpointID": "e9ae0c0c119451bd447cf7ad3a556cca822d4039b935b7798f6d47301669c415",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]

```

```
Client: Docker Engine - Enterprise
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        f660560464
 Built:             07/25/2019 20:59:52
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.5
  Git commit:       f660560464
  Built:            07/25/2019 20:57:41
  OS/Arch:          windows/amd64
  Experimental:     false
```

### PR DESCRIPTION
**Pull request by ddebroy**
**- What I did**
Address a regression during daemon startup introduced in https://github.com/moby/moby/pull/38931.

fixes https://github.com/moby/moby/issues/39623
fixes https://github.com/moby/moby/issues/39742
fixes https://github.com/docker/for-win/issues/4463
fixes https://github.com/microsoft/navcontainerhelper/issues/548

**- How I did it**
Added (back) proper handling of NotFound err

**- How to verify it**
Start a container in Windows like: 
```
docker run -d --restart always --name testcontainer --network nat -p 8080:80 mcr.microsoft.com/windows/servercore:ltsc2019 ping -t 127.0.0.1
```
and Restart-Computer.
After reboot, make sure container comes back up properly and is not a zombie.

**- Description for the changelog**
Fix regression in reboot of Windows daemon

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: daemon/daemon.go [hunk 1]
```diff
@@ -336,7 +336,7 @@ func (daemon *Daemon) restore() error {
 			}
 			if !alive && process != nil {
 				ec, exitedAt, err = process.Delete(context.Background())
-				if err != nil {
+				if err != nil  && !errdefs.IsNotFound(err) {
```
Comment (thaJeztah) [inline daemon/daemon.go]:
```suggestion
				if err != nil && !errdefs.IsNotFound(err) {
```

**Review by thaJeztah — CHANGES_REQUESTED** [review]
change looks good but linting is failing;

```
23:55:13 Congratulations!  All commits are properly signed with the DCO!
23:56:27 daemon/daemon.go:1::warning: file is not gofmted with -s (gofmt)
23:56:27 daemon/daemon.go:1::warning: file is not goimported (goimports)
```

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
backport: https://github.com/docker/engine/pull/317

**Review by kolyshkin — APPROVED** [review]
LGTM

**Review by StefanScherer — APPROVED** [review]
LGTM
retested with the NAV container example on Windows 10 with Docker Desktop.

**Comment by thaJeztah** [comment]
all green 💚 - merging
