### PR TITLE
Fixes for `service update` of Args

### LINKED ISSUE #23923: "docker service update" awkward for updating command arguments
It looks like if I want to update a service's command from `echo abc def` to `echo abc xyz`, I need to run `docker service update servicename --arg abc --arg xyz`. Inserting `--arg` before each argument doesn't feel right - if I have a command with lots of args, this is going to be really cumbersome and look weird. Could this be done with positional arguments at the end of the command like `docker service create`?

cc @vieux @dnephin

### LINKED ISSUE #23924: "docker service update" does not update commands/args properly
Running master (`86d5c7e759e099b2662770be82cf9248ab0df5ba`).

I had a service running `top` with no arguments. When I ran `docker service update 533yymyth264 --command sleep --arg 1000`, it updated the service definition as follows:

```
                "ContainerSpec": {
                    "Image": "busybox",
                    "Command": [
                        "1000"
                    ],
                    "Args": [
                        "top"
                    ]
                },
```

This doesn't look right - I'd expect the following:

```
                "ContainerSpec": {
                    "Image": "busybox",
                    "Command": [
                        "sleep"
                    ],
                    "Args": [
                        "1000"
                    ]
                },
```

Before I updated the service, the `ContainerSpec` was:

```
                "ContainerSpec": {
                    "Image": "busybox",
                    "Args": [
                        "top"
                    ]
                },
```

(Why was `Args` set to top rather than `Command`?)

cc @vieux @dnephin

### PR DESCRIPTION
**Pull request by dnephin**
Fixes #23924 by setting `Args` properly instead of setting `Command`

Removed from this PR: ~~Fixes #23923 - `args` (previously `arg`) and `comand` now accept a single string instead of a slice. So `--args "echo 100"` works instead of `--arg echo --arg 100`~~

### CODE REVIEW

File: api/client/service/update.go [hunk 1]
```diff
@@ -157,10 +152,7 @@ func updateService(spec *swarm.ServiceSpec, flags *pflag.FlagSet) error {
 		updateDurationOpt((flagRestartWindow), task.RestartPolicy.Window)
 	}
 
-	if flags.Changed(flagConstraint) {
-		task.Placement = &swarm.Placement{}
-		updateSlice(flagConstraint, &task.Placement.Constraints)
-	}
+	// TODO: Constraints fied in a differe branch
```
Comment (aaronlehmann) [inline api/client/service/update.go]: ?

File: api/client/service/update.go [hunk 2]
```diff
@@ -30,8 +31,8 @@ func newUpdateCommand(dockerCli *client.DockerCli) *cobra.Command {
 
 	flags := cmd.Flags()
 	flags.String("image", "", "Service image tag")
-	flags.StringSlice("command", []string{}, "Service command")
-	flags.StringSlice("arg", []string{}, "Service command args")
+	flags.String("command", "", "Service command")
+	flags.String("args", "", "Service command args")
```
Comment (aaronlehmann) [inline api/client/service/update.go]: I'm not thrilled about `args` being a flat string that we do our own lexing on, but I don't really have a better suggestion. At least this is a big improvement from the current approach. The downside is that users will have to double-escape anything that needs escaping.

Comment (aaronlehmann) [inline api/client/service/update.go]: Also, the inconsistency with `service create` may be confusing. But again, I don't have a better suggestion. We could consider treating extra arguments that aren't associated with a flag as a replacement command/args, but this might be very unintuitive for other reasons (I pass an extra arg to `docker service update` by accident, and instead of getting an error, the command line for my service is overwritten...).

File: api/client/service/update.go [hunk 3]
```diff
@@ -122,8 +117,8 @@ func updateService(spec *swarm.ServiceSpec, flags *pflag.FlagSet) error {
 	updateString(flagName, &spec.Name)
 	updateLabels(flags, &spec.Labels)
 	updateString("image", &cspec.Image)
-	updateSlice("command", &cspec.Command)
-	updateSlice("arg", &cspec.Command)
+	updateStringToSlice(flags, "command", &cspec.Command)
```
Comment (aaronlehmann) [inline api/client/service/update.go]: I'm confused about why `command` is defined in the API as a slice rather than a string. What actually happens if I specify multiple commands?

File: api/client/service/update_test.go [hunk 4]
```diff
@@ -0,0 +1,23 @@
...
+	"testing"
+
+	"github.com/docker/docker/pkg/testutil/assert"
+	"github.com/docker/engine-api/types/swarm"
+)
+
+func TestUpdateServiceCommandAndArgs(t *testing.T) {
+	flags := newUpdateCommand(nil).Flags()
+	flags.Set("command", "the new command")
+	flags.Set("args", "the new args")
```
Comment (aaronlehmann) [inline api/client/service/update_test.go]: It might be good to throw a little escaping into the test case to make sure it's handled properly.

File: api/client/service/update.go (hunk 2 above)
Comment (dnephin) [inline api/client/service/update.go]: Yes, it's going to be pretty annoying if you need to quote things in the command. It's not a perfect solution, but it feels like the best option right now. 

> We could consider treating extra arguments that aren't associated with a flag as a replacement command/args, but this might be very unintuitive for other reasons

Ya, for one it's still going to be inconsistent with `service create`, because the first positional arg to `create` is the image not the command. I'm pretty sure we don't want to force the image as a positional in `update`.

File: api/client/service/update.go (hunk 3 above)
Comment (dnephin) [inline api/client/service/update.go]: It splits command into entrypoint/cmd (https://github.com/docker/swarmkit/blob/b4644d8/agent/exec/container/container.go#L95-L108), which is effectively just using it as the entrypoint.

File: api/client/service/update.go (hunk 1 above)
Comment (dnephin) [inline api/client/service/update.go]: Fixed in #23773

I didn't want to repeat the fix here (because it depends on other changes), and I was removing `updateSlice()`, so I left this as a TODO for now. It's going to conflict when I go to merge them, so I shouldn't miss it later.

File: api/client/service/update_test.go (hunk 4 above)
Comment (dnephin) [inline api/client/service/update_test.go]: good idea

**Comment by mgoelzer** [comment]
ping @aluzzardi

File: api/client/service/update.go (hunk 3 above)
Comment (aaronlehmann) [inline api/client/service/update.go]: So is the result of `--command "cat file1" --args "file2 file3"` the command line `cat file1 file2 file3`? If so, this concatenation seems a bit strange, and I wonder if we should disallow combinations like this (unless it's done this way for consistency with existing Docker behavior).

Comment (dnephin) [inline api/client/service/update.go]: No, swarmkit would actually end up with the command line `cat file1`. If command is set, it ignores args entirely.

Comment (aaronlehmann) [inline api/client/service/update.go]: That makes even less sense to me :confused:

Comment (dnephin) [inline api/client/service/update.go]: I'm just following what swarmkit supports. I think it would make more sense for swarmkit to return to the entrypoint/command behaviour we have with `docker run`.

I don't want to introduce a third way of resolving these here, and attempting to restore the old behaviour in the cli doesn't feel right either.

Comment (aaronlehmann) [inline api/client/service/update.go]: ping @stevvooe - Is this the behavior you had in mind for `command` / `args`?

**Comment by dnephin** [comment]
The experimental failure is a timeout after all the tests pass, so I don't think it's related

File: api/client/service/update.go (hunk 3 above)
Comment (stevvooe) [inline api/client/service/update.go]: > Is this the behavior you had in mind for command / args?

This is the correct behavior and allows backwards compat with entrypoint/cmd.

`Command` and `Args` are simply vectors of string, as is supported in any shell. A `Command` may have arguments that come along with it. Imagine `["myapp", "serve"]` as being a possible entrypoint in an image. When we execute a containers, we effectively append `Args` to `Command`. So, the actual command becomes ` `["myapp", "serve", "args"]`, if `Args` is `["args"]`.

> I'm just following what swarmkit supports. I think it would make more sense for swarmkit to return to the entrypoint/command behaviour we have with docker run.

`Command`/`Args` _is_ the correct approach and is an industry standard. _Every other orchestration_ system does it like this.

File: api/client/service/update.go (hunk 2 above)
Comment (stevvooe) [inline api/client/service/update.go]: I have major concerns for shell interpretation. In fact, it is possible that we removed this exact dependency at one time or another because of this issue.

File: api/client/service/update.go (hunk 3 above)
Comment (aaronlehmann) [inline api/client/service/update.go]: So it sounds like the current behavior:

> If command is set, it ignores args entirely.

...is *not* what you have in mind.

Comment (dnephin) [inline api/client/service/update.go]: I based that statement off of what [I see in swarmkit](https://github.com/docker/swarmkit/blob/b4644d8/agent/exec/container/container.go#L95-L108). I'm not seeing any command + args.

The cli just passes through what the user sets for those values.

The cli does

File: api/client/service/update.go (hunk 2 above)
Comment (dnephin) [inline api/client/service/update.go]: Do you have an alternative suggestion?

Comment (dnephin) [inline api/client/service/update.go]: Also, what are the major concerns?

File: api/client/service/update.go (hunk 3 above)
Comment (stevvooe) [inline api/client/service/update.go]: @aaronlehmann Apologies.

Let's speak in code:

```go
func FromCommandArgs(command, args []string) (entrypoint, cmd []string) {
  if len(command) == 0 {
    // when no command is provided, we just set everything as cmd.
    // subtle: if entrypoint on image is empty, promote args
    return nil, args
  }
  
  // We can do either of the following here
  return command[:1], command[1:] // this is currently implemented
  // Or this
  return command, args // I am not sure about this because entrypoint is confusing.
  // Or this
  return command[:1], append(command[1:], args...)
}
```

However, I think defining these in terms of entrypoint and cmd is just continuing the madness, so let's repeat the definitions:

- `Command` - the full command and arguments.
- `Args` - The arguments to a command, possibly with the command itself.

For use with Docker CLI, only `Args` should be used, unless attempting to override entrypoint.

Comment (stevvooe) [inline api/client/service/update.go]: There may be some require fixes in swarmkit, but in general, this mapping is quite simple, albeit subtle.

**Comment by dnephin** [comment]
I've removed all the controversial stuff from this PR. It's now just the minimal fix for #23924, a unit test, and some minor changes to make the args of the  `update()` methods more consistent.

I can open another PR to deal with the entrypoint vs cmd issue and setting `--arg x --arg y` vs `--args "x y" when we decide what we want.

**Comment by aaronlehmann** [comment]
LGTM

And I'm in favor of another PR to fix those issues.

**Comment by vdemeester** [comment]
LGTM 🐸
