### PR TITLE
Accurately reflect the canonical casing of `API-Version` and `OS-Type` headers

### LINKED ISSUE #49046: API docs incorrectly suggest the api version header is not canonicalised: `API-Version`
### Description

The `ping` endpoint docs suggest the api version response header is:

`API-Version`

It is in fact canonical:

```
curl --unix-socket /var/run/docker.sock -i http://localhost/_ping
HTTP/1.1 200 OK
Api-Version: 1.44
```

`Api-Version` is the correct canonical format that headers should use and the docs could be updated to reflect this.

https://docs.docker.com/reference/api/engine/version/v1.44/#tag/System/operation/SystemVersion

### Reproduce

Check the docs 

### Expected behavior

_No response_

### docker version

```bash
1.44
```

### docker info

```bash
N/a
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by maggie44**
Go automatically canonicalises HTTP headers, meaning the string `API-Version` passed as a header has always been returned as `Api-Version`. Similarly, `OSType` is returned as `Ostype`.

This commit updates the documentation to reflect this behaviour and modifies the codebase to ensure that input strings are aligned with their canonical output values.

```markdown changelog
Update docs and code to reflect Go’s automatic canonicalisation of Api-Version and Ostype headers.
```

Closes: https://github.com/moby/moby/issues/49046#issuecomment-2525113278

### CODE REVIEW

File: api/server/middleware/version.go [hunk 1]
```diff
@@ -67,8 +67,8 @@ func (e versionUnsupportedError) InvalidParameter() {}
 func (v VersionMiddleware) WrapHandler(handler func(ctx context.Context, w http.ResponseWriter, r *http.Request, vars map[string]string) error) func(ctx context.Context, w http.ResponseWriter, r *http.Request, vars map[string]string) error {
 	return func(ctx context.Context, w http.ResponseWriter, r *http.Request, vars map[string]string) error {
 		w.Header().Set("Server", fmt.Sprintf("Docker/%s (%s)", v.serverVersion, runtime.GOOS))
-		w.Header().Set("API-Version", v.defaultAPIVersion)
-		w.Header().Set("OSType", runtime.GOOS)
+		w.Header().Set("Api-Version", v.defaultAPIVersion)
+		w.Header().Set("Ostype", runtime.GOOS)
```
Comment (thaJeztah) [inline api/server/middleware/version.go:71]: For others  reviewing; I suggested changing these to match the normalised  version.  Effectively these  parts of the change are a "no-op", but explicitly setting the headers in  the normalised form (instead of them implicitly being normalised by Go stdlib) reduces confusion.

As a follow-up to this PR I want to have  a  peek if we could define consts for this  (on which we could document why they're capitalised as they are), but I have not yet looked at the impact of that (i.e.; where to best put the const without that resulting in cumbersome imports / inter-package dependencies).

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by laurazard — APPROVED** [review]
LGTM
