### PR TITLE
Release the network attachment on allocation failure

### LINKED ISSUE #31066: phantom task preventing overlay network deletion after ip allocation fails
**Description**

```
$ docker network create -d overlay --attachable --subnet 10.1.0.0/24 testnet
$ docker run -d --net testnet --ip 10.1.0.10 alpine sleep 10000
37041d28214e1e31c24ba3ee7c2e9355200d2757262c5277703902f3d398210b
$ docker run -d --net testnet --ip 10.1.0.10 alpine sleep 10000
264114d0771ce129c5edf07c68457d6c93d811f8d86640488148dec0051f3a2d
docker: Error response from daemon: attaching to network failed, make sure your network options are correct and check manager logs: context deadline exceeded.
$ docker rm -f 37041d28214e1e31c24ba3ee7c2e9355200d2757262c5277703902f3d398210b
37041d28214e1e31c24ba3ee7c2e9355200d2757262c5277703902f3d398210b
$ docker network rm testnet
Error response from daemon: rpc error: code = 9 desc = network 3r26lzd4vrxedijc5yhb9gbrg is in use by task qug9pv2plrgpq3wg5z2p9qck2
```

**Steps to reproduce the issue:**
see above

**Describe the results you received:**
see above (can't delete network except by leaving swarm)

**Describe the results you expected:**
to be able to delete the network

**Additional information you deem important (e.g. issue happens only occasionally):**
100% reproducible, probably all the way back to 1.12-cs, but I haven't checked.

**Output of `docker version`:**

```
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.4
 Git commit:   bf6eb85
 Built:        Tue Dec 27 22:23:51 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.14.0-dev
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.4
 Git commit:   bf6eb85
 Built:        Tue Dec 27 22:23:51 2016
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 15
 Running: 12
 Paused: 0
 Stopped: 3
Images: 1759
Server Version: 1.14.0-dev
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: rj3ec6cfcpxh3en3khckwsjs4
 Is Manager: true
 ClusterID: tomgh3xkbjch7hfeusyuep2du
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  External CAs:
    cfssl: https://172.17.0.1:12381/api/v1/cfssl/sign
 Node Address: 172.17.0.1
 Manager Addresses:
  172.17.0.1:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.8.17
Operating System: NixOS 17.03.git.6378f62 (Gorilla)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.53 GiB
Name: thisisfine
ID: 4XB6:RAOL:2UT7:W3TT:JBSR:ILHC:LREA:HUVU:5U7V:TI7E:WUT2:WQTS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 151
 Goroutines: 269
 System Time: 2017-02-15T16:55:57.360924072-08:00
 EventsListeners: 2
Username: viktorstanchev
Registry: https://index.docker.io/v1/
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Experimental: false
Insecure Registries:
 172.17.0.1:3001
 172.17.0.1:443
 172.17.0.1:444
 172.17.0.1:445
 172.17.0.1
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

### PR DESCRIPTION
**Pull request by aboch**
- otherwise the attachment task will stay in store and
  consume IP addressess and there is no way to remove it.

Fixes #31066

**- A picture of a cute animal (not mandatory but encouraged)**

vez

### CODE REVIEW

**Review by mavenugo — APPROVED** [review]
Thanks @aboch @vikstrous 

LGTM

File: daemon/cluster/networks.go [hunk 1]
```diff
@@ -178,16 +178,29 @@ func (c *Cluster) AttachNetwork(target string, containerID string, addresses []s
...
 	case <-ctx.Done():
+		release()
 		return nil, fmt.Errorf("attaching to network failed, make sure your network options are correct and check manager logs: %v", ctx.Err())
 	}
 
 	c.mu.Lock()
 	c.attachers[aKey].config = config
 	c.mu.Unlock()
+
+	logrus.Debugf("Successfully allocated resources on network %s with tid %s", target, taskID)
```
Comment (allencloud) [inline daemon/cluster/networks.go]: Thanks @aboch 
Could you change `tid` to `task id`?
Since I think tid may be not so readable.

Comment (aboch) [inline daemon/cluster/networks.go]: Thanks. I will also change the existing log from which I got the `tid`.
Updated, PTAL.

Comment (allencloud) [inline daemon/cluster/networks.go]: Thanks. It couldn't be better. 😄

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by aboch** [comment]
Please hold on on merging

**Comment by thaJeztah** [comment]
cherry-picked through https://github.com/docker/docker/pull/31138
