### PR TITLE
Fix sanitize URL bug on layer upload

### LINKED ISSUE #15875: Layer Upload broken due to URL sanitization bug
Under certain proxy configurations, where a relative url is encountered in Location fields, blob uploads may not be resolvable. The cli will report "blob upload unknown" and not provide much else.

There are more details here: https://github.com/docker/distribution/issues/928#issuecomment-135235658.

We need to get a fix in distribution and update the client in docker.

cc @dmcgowan

### PR DESCRIPTION
**Pull request by dmcgowan**
Update the distribution version to include sanitize URL fix

Fixes #15875 

_Where are the tests?_
This fixes a bug with some private registry configurations which cannot be easily replicated in the integration tests. However this change is unit tested in the distribution repository (https://github.com/docker/distribution/blob/docker/1.8/registry/client/repository_test.go#L861).

### CODE REVIEW

File: Dockerfile [hunk 1]
```diff
@@ -128,7 +128,7 @@ RUN git clone https://github.com/golang/lint.git /go/src/github.com/golang/lint
 RUN gem install --no-rdoc --no-ri fpm --version 1.3.2
 
 # Install registry
-ENV REGISTRY_COMMIT 2317f721a3d8428215a2b65da4ae85212ed473b4
+ENV REGISTRY_COMMIT ec87e9b6971d831f0eff752ddb54fb64693e51cd
```
Comment (stevvooe) [inline Dockerfile]: Can you make a not about the branch this is from? I know we aren't using master since master has the `schema1` package.

File: hack/vendor.sh [hunk 2]
```diff
@@ -35,7 +35,7 @@ clone git github.com/coreos/go-etcd v2.0.0
 clone git github.com/hashicorp/consul v0.5.2
 
 # get graph and distribution packages
-clone git github.com/docker/distribution 7dc8d4a26b689bd4892f2f2322dbce0b7119d686
+clone git github.com/docker/distribution ec87e9b6971d831f0eff752ddb54fb64693e51cd
```
Comment (stevvooe) [inline hack/vendor.sh]: Can you make a not about the branch this is from? I know we aren't using master since master has the `schema1` package.

**Comment by stevvooe** [comment]
LGTM

Please add the note about where this branch is.

**Comment by calavera** [comment]
LGTM

**Comment by calavera** [comment]
Cherry picked into #15809
