### PR TITLE
Fix rmi by ID untagging image on error

### LINKED ISSUE #18873: `docker rmi ID` untags image even if there is a running container that is using it
## Description of problem:

1. Using `docker rmi` with ID as argument untags image even if there is a running container that is used by this image
2. As result it marks that image as dangling

## docker version:

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:06:12 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:06:12 UTC 2015
 OS/Arch:      linux/amd64
```

## docker info:

```
Containers: 5
Images: 47
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 57
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-0.bpo.4-amd64
Operating System: Debian GNU/Linux 7 (wheezy)
CPUs: 8
Total Memory: 31.35 GiB
Name: [... cut ...]
ID: BHQB:3N5X:46IT:BLJI:QQOA:IYVH:4H3K:CV57:VTT3:5S5W:U3NC:OJRK
WARNING: No memory limit support
WARNING: No swap limit support
```

## uname -a

```
Linux hostname 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt11-1~bpo70+1 (2015-06-08) x86_64 GNU/Linux
```

## Steps to reproduce

1. run any container, ex: `docker run -it busybox`
2. run `docker rmi IMAGE_ID`

## Actual Results:

`docker images`:

```
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
<none>              <none>              ac6a7980c6c2        2 weeks ago         1.113 MB
```

`docker ps`:

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                      NAMES
3b46060d3c2f        ac6a7980c6c2        "sh"                     3 minutes ago       Up 3 minutes                                   trusting_raman
```

## Expected Results:

`docker images`:

```
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
busybox             latest              ac6a7980c6c2        2 weeks ago         1.113 MB
```

`docker ps`:

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                      NAMES
3b46060d3c2f        busybox             "sh"                     12 seconds ago      Up 11 seconds                                  trusting_raman
```

In my understanding running this command should return and error and do not untag the image.

## Additional info:

The error received while trying to remove the image by id is correct:

```
$ docker rmi ac6a7980c6c2
Error response from daemon: conflict: unable to delete ac6a7980c6c2 (cannot be forced) - image is being used by running container 3b46060d3c2f
Error: failed to remove images: [ac6a7980c6c2]
```

However - docker still untags this image making it dangling (which I believe shouldn't happen, because it's still used image) - it can be filtered by `docker images -f dangling=true`:

```
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
<none>              <none>              ac6a7980c6c2        2 weeks ago         1.113 MB
```

This causes couple issues when cleaning up old non-used images by "well-known" script `docker rmi $(docker images -qf)`

Also: I found out that this is not happening when:
1. Using rmi with IMAGE_NAME
2. Having same image with multiple tags

### PR DESCRIPTION
**Pull request by tonistiigi**
Do not untag image if it would later get a hard conflict because of running containers.

Fixes #18873

Signed-off-by: Tonis Tiigi tonistiigi@gmail.com

### CODE REVIEW

**Comment by aaronlehmann** [comment]
Should this be allowed with `-f`? Not sure that would make sense, but just checking.

Also, it's probably worth factoring these few lines into a function, since they are duplicated from above.

**Comment by tonistiigi** [comment]
@aaronlehmann So you would want to untag when force is specified (as the deletion will fail anyway because running containers is a hard conflict)? Seems unlikely that any use would expect this to happen.

**Comment by aaronlehmann** [comment]
I agree it probably isn't intuitive, just checking to see if that would match previous behavior. I noticed that if you rmi a tag with -f, it will remove the tag even if there's a hard conflict.

File: daemon/image_delete.go [hunk 1]
```diff
@@ -102,6 +102,10 @@ func (daemon *Daemon) ImageDelete(imageRef string, force, prune bool) ([]types.I
 		// remove that reference.
 		// FIXME: Is this the behavior we want?
 		if len(repoRefs) == 1 {
+			if conflict := daemon.checkImageDeleteConflict(imgID, force); conflict != nil {
```
Comment (aaronlehmann) [inline daemon/image_delete.go]: I don't think this is correct because unless `force` is true, `daemon.checkImageDeleteConflict` will always return a soft conflict (because `len(repoRefs) == 1`). I think this needs to check for:

- a hard conflict
- if `force` is false, a stopped container using the image

It probably makes sense to refactor `checkImageDeleteHardConflict` and `checkImageDeleteSoftConflict` a bit to make this easier.

File: daemon/image_delete.go [hunk 2]
```diff
@@ -312,9 +316,9 @@ func (daemon *Daemon) checkImageDeleteHardConflict(imgID image.ID) *imageDeleteC
 	return nil
 }
 
-func (daemon *Daemon) checkImageDeleteSoftConflict(imgID image.ID) *imageDeleteConflict {
+func (daemon *Daemon) checkImageDeleteSoftConflict(imgID image.ID, ingroreRefConflict bool) *imageDeleteConflict {
```
Comment (aaronlehmann) [inline daemon/image_delete.go]: typo: should be `ignoreRefConflict`

**Comment by aaronlehmann** [comment]
LGTM

I wasn't thrilled about adding another flag to the conflict checking functions, so @tonistiigi is going to open a followup PR to clean up these functions by unifying them into a single function that takes a bitmask controlling its behavior. We decided that it would be easiest for this PR to only include the bug fix, and then for the cleanup to come separately.

**Comment by jfrazelle** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM
