### PR TITLE
Relative symlinks don't work with --device argument

### LINKED ISSUE #22271: Relative symlinks don't work with --device argument
Support for `--device` following (absolute) symlinks was added in #20684 (fix for issue #13840)

However this doesn't work if the symlink's target is a relative path. Since udev (one of the main reasons for this feature IMO) only generates relative path symlinks this isn't very usable currently.

The problem is that https://github.com/yongtang/docker/blob/master/daemon/container_operations_unix.go#L314 blindly assumes that the symlink target is absolute.

Example:

```
$ ls -l /dev/ttyACM1
crw-rw---- 1 root dialout 166, 1 Apr 23 15:37 /dev/ttyACM1

$ ls -l /dev/somealias
lrwxrwxrwx 1 root root 7 Apr 23 15:37 /dev/somealias -> ttyACM1

$ docker run --rm -it --device /dev/somealias:/dev/something alpine /bin/bash
docker: Error response from daemon: linux runtime spec devices: error gathering device information while adding custom device "/dev/somealias": lstat ttyACM1: no such file or directory.
```

### PR DESCRIPTION
**Pull request by yongtang**
**\- What I did**

This fix tries to address the issue raised in #22271 where relative symlinks don't work with --device argument.

**\- How I did it**

Previously, the symlinks in --device was implemneted (#20684) with `os.Readlink()` which does not resolve if the linked target is a relative path. In this fix, `filepath.EvalSymlinks()` has been used which will reolve correctly with relative paths.

**\- How to verify it**

An additional test case has been added to the existing `TestRunDeviceSymlink` to cover changes in this fix.

**\- A picture of a cute animal (not mandatory but encouraged)**

This fix is related to #13840 and #20684, #22271.
This fix fixes #22271.

Signed-off-by: Yong Tang yong.tang.github@outlook.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
@mlaventure we may want to consider including this in 1.11.1 (the follow symlinks is a new addition in 1.11.0)

File: integration-cli/docker_cli_run_unix_test.go [hunk 1]
```diff
@@ -1048,6 +1048,12 @@ func (s *DockerSuite) TestRunDeviceSymlink(c *check.C) {
 	err = os.Symlink(tmpFile, symFile)
 	c.Assert(err, checker.IsNil)
 
+	// Create a symbolic link to /dev/zero, this time with a relative path (#22271)
+	err = os.Symlink("zero", "/dev/symzero")
+	// We need to remove this symbolic link here as it is created in /dev/, not temporary directory as above
+	defer os.Remove("/dev/symzero")
+	c.Assert(err, checker.IsNil)
```
Comment (tiborvass) [inline integration-cli/docker_cli_run_unix_test.go]: Does os.Symlink error out if /dev/symzero already exists? if so, i dont think we should error out, because it is not impossible that the defer won't run in some weird cases. We could just print the error though and move on.

**Comment by tiborvass** [comment]
I'm not opposed to this PR, in fact I don't even see why we wouldn't follow absolute symlinks too.

File: integration-cli/docker_cli_run_unix_test.go (hunk 1 above)
Comment (yongtang) [inline integration-cli/docker_cli_run_unix_test.go]: Thanks @tiborvass just updated the pull request. Let me know if there are any other issues.

**Comment by vdemeester** [comment]
Same thought as @tiborvass so LGTM 🐼

**Comment by coolljt0725** [comment]
LGTM

File: integration-cli/docker_cli_run_unix_test.go [hunk 2]
```diff
@@ -1048,6 +1048,14 @@ func (s *DockerSuite) TestRunDeviceSymlink(c *check.C) {
...
 	c.Assert(err, checker.IsNil)
 
+	// Create a symbolic link to /dev/zero, this time with a relative path (#22271)
+	err = os.Symlink("zero", "/dev/symzero")
+	// We need to remove this symbolic link here as it is created in /dev/, not temporary directory as above
+	defer os.Remove("/dev/symzero")
+	if err != nil {
+		fmt.Fprintln(os.Stderr, "WARNING: /dev/symzero creation failed")
+	}
+
```
Comment (coolljt0725) [inline integration-cli/docker_cli_run_unix_test.go]: should `defer os.Remove("/dev/symzero")` below the `if err != nil` check?

**Comment by tiborvass** [comment]
LGTM
