### PR TITLE
don't use canceled context to send KILL signal to healthcheck process

### LINKED ISSUE #43737: dockerd doesn't kill healthcheck processes after timeout
**Description**

dockerd already has logic to gracefully stop healthcheck processes after timeout ([/daemon/exec.go#L277-L291](https://github.com/moby/moby/blob/v20.10.17/daemon/exec.go#L277-L291)).

But it seems completely broken because of using canceled context in `daemon.containerd.SignalProcess()` call ([/daemon/exec.go#L279](https://github.com/moby/moby/blob/v20.10.17/daemon/exec.go#L279)). `SignalProcess()` just returns `context canceled` error and does nothing.

**Steps to reproduce the issue:**

1. Create `Dockerfile`:
    ```
    FROM ubuntu:22.04

    HEALTHCHECK --interval=5s --timeout=5s \
       CMD ["sleep", "3600"]

    CMD ["sleep", "infinity"]
    ```
2. Build image:
    ```
    docker build --tag=healthcheck-test .
    ```
3. Start container:
    ```
    docker run -d --rm --name=healthcheck-test healthcheck-test
    ```
4. Wait some health intervals:
    ```
    sleep 30
    ```
5. Check processes in the container:
    ```
    docker exec healthcheck-test ps axuf
    ```

* Cleanup:
    ```
    docker rm --force healthcheck-test # remove container
    docker rmi healthcheck-test # remove image
    ```

**Describe the results you received:**

More then one `sleep 3600` processes:

```
$ docker build --tag=healthcheck-test .
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM ubuntu:22.04
 ---> 27941809078c
Step 2/3 : HEALTHCHECK --interval=5s --timeout=5s    CMD ["sleep", "3600"]
 ---> Running in 248a9dcfaa6f
Removing intermediate container 248a9dcfaa6f
 ---> 16d09d0a1b09
Step 3/3 : CMD ["sleep", "infinity"]
 ---> Running in 55ef832b3170
Removing intermediate container 55ef832b3170
 ---> 7e8b71425a0a
Successfully built 7e8b71425a0a
Successfully tagged healthcheck-test:latest
$ docker run -d --rm --name=healthcheck-test healthcheck-test
41e8e2eb21d0bdd485e647c6ec1273474b19ba616d284d48d53ea607edd96841
$ sleep 30
$ docker exec healthcheck-test ps axuf
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root          25  0.0  0.0   7060  1664 ?        Rs   12:01   0:00 ps axuf
root          19  0.2  0.0   2788  1036 ?        Ss   12:01   0:00 sleep 3600
root          13  0.0  0.0   2788  1036 ?        Ss   12:00   0:00 sleep 3600
root           7  0.0  0.0   2788  1056 ?        Ss   12:00   0:00 sleep 3600
root           1  0.0  0.0   2788  1108 ?        Ss   12:00   0:00 sleep infinity
```

**Describe the results you expected:**

Zero or one `sleep 3600` process:

```
$ docker exec healthcheck-test ps axuf
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root          25  0.0  0.0   7060  1664 ?        Rs   12:01   0:00 ps axuf
root          19  0.2  0.0   2788  1036 ?        Ss   12:01   0:00 sleep 3600
root           1  0.0  0.0   2788  1108 ?        Ss   12:00   0:00 sleep infinity
```

**Additional information you deem important (e.g. issue happens only occasionally):**

N/A

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:02:57 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:03 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 10
  Running: 1
  Paused: 0
  Stopped: 9
 Images: 119
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.13.0-51-generic
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.34GiB
 Name: uk-ubnt-61
 ID: BXVR:65LG:FDYH:IX7Q:U2LT:LQI6:P5B5:ZFEG:EIMS:WPWM:D3ND:RN4H
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 90
  Goroutines: 74
  System Time: 2022-06-22T15:03:06.064800737+03:00
  EventsListeners: 0
 Username: 2gis
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  docker-hub.2gis.ru:5444
  127.0.0.0/8
 Registry Mirrors:
  https://docker-registry-proxy.2gis.io/
 Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

N/A

### PR DESCRIPTION
**Pull request by ndeloof**
**- What I did**
send KILL signal to healthcheck process when the context is canceled (timeout)
- closes #43737

**- How I did it**
Use a background context to send KILL signal

**- How to verify it**
see reproduction scenario on #43737

**- Description for the changelog**
fix healthcheck process termination on timeout

**- A picture of a cute animal (not mandatory but encouraged)**
image

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Comment by thaJeztah** [comment]
do we want a test for this? Or too complicated to set one up?

**Comment by thaJeztah** [comment]
I don't think the failure was related, so I kicked CI again, but posting here in case there's a flaky test at hand that we're not tracking yet;

```
=== RUN   TestDockerSwarmSuite/TestAPISwarmServicesMultipleAgents
    docker_api_swarm_service_test.go:100: [d7f46e9e54ee1] joining swarm manager [d451e1c460ace]@0.0.0.0:2477, swarm listen addr 0.0.0.0:2478
    docker_api_swarm_service_test.go:101: [d285f6cd0aebd] joining swarm manager [d451e1c460ace]@0.0.0.0:2477, swarm listen addr 0.0.0.0:2479
    docker_api_swarm_service_test.go:122: timeout hit after 30s: output: "4adc199e5240\n13ecfed699f5\n", output: "5547cb8d033b\n97e5710958e7\nb9aa8d4c5a86\n3440eeecbb60\n8fabde17fa91\n"
    poll.go:125: assertion failed: error is not nil: exit status 1
    check_test.go:611: [d7f46e9e54ee1] daemon is not started
    --- FAIL: TestDockerSwarmSuite/TestAPISwarmServicesMultipleAgents (60.05s)
```

**Review by cpuguy83 — DISMISSED** [review]

File: integration/container/health_test.go [hunk 1]
```diff
@@ -93,6 +93,32 @@ while true; do sleep 1; done
...
+// TestHealthCheckProcessKilled verifies that health-checks exec get killed on time-out.
+func TestHealthCheckProcessKilled(t *testing.T) {
+	skip.If(t, testEnv.OSType == "windows", "FIXME")
+	defer setupTest(t)()
+	ctx := context.Background()
+	client := testEnv.APIClient()
+
+	cID := container.Run(ctx, t, client, func(c *container.TestContainerConfig) {
+		c.Config.Healthcheck = &containertypes.HealthConfig{
+			Test:     []string{"CMD-SHELL", "sleep 30"},
```
[the remark this answers is not in the document]
Comment (ndeloof) [reply integration/container/health_test.go:105]: unfortunately, healthcheck output when interrupted is not captured to be reported by inspect, and replaced by a gerenic timeout message:
```json
            "Health": {
                "Status": "unhealthy",
                "Log": [
                    {
                        "Start": "2022-06-24T08:59:46.200205085Z",
                        "End": "2022-06-24T08:59:47.203354127Z",
                        "ExitCode": -1,
                        "Output": "Health check exceeded timeout (1s)"
                    },
```
This would require the `exec` logic to change, so that it captures the killed process output even in such circumstances. Would this be fine?

[the remark this answers is not in the document]
Comment (thaJeztah) [reply integration/container/health_test.go:105]: If the question is; is it ok to add addition text to `Output`,  good question; I'm not aware of any code parsing the output; AFAIK, it's intended purely as "additional info", but the description is a bit ambiguous; https://github.com/moby/moby/blob/c0069b83bce03d1dd1ac2c04bd309f0641bc8114/api/types/types.go#L400


Do we capture the output if the HealthCheck _is_ successful? (e.g. if a successful health check would print `OK`, is that output returned?)

So we could either;

- include both: `Health check exceeded timeout (1s): <output>`
- Or _only_ include `<output>` (which would be a closer match to the description, but I guess the timeout information is still useful

Perhaps we need to update the description of the field to better clarify what the expectation is;

- for success
- on error (is it the raw error output? other output?)

File: integration/container/testdata/health/go.mod [hunk 2]
```diff
@@ -0,0 +1,3 @@
+module github.com/docker/docker/integration/container/testdata/health
+
+go 1.17
```
Comment (thaJeztah) [inline integration/container/testdata/health/go.mod:3]: This one is no longer needed, correct?

**Review by thaJeztah — CHANGES_REQUESTED** [review]

File: integration/container/health_test.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (cpuguy83) [reply integration/container/health_test.go]: Oh right this could be more difficult than just capturing the output because we won't know when the command is completed (or if it ever will).

**Comment by thaJeztah** [comment]
Something failing;

```
=== RUN   TestHealthCheckProcessKilled
    health_test.go:111: timeout hit after 10s: waiting for a new container healthcheck
--- FAIL: TestHealthCheckProcessKilled (11.40s)
```

File: daemon/health.go [hunk 3]
```diff
@@ -136,9 +136,16 @@ func (p *cmdProbe) run(ctx context.Context, d *Daemon, cntr *container.Container
 		// Wait for probe to exit (it might take a while to respond to the TERM
 		// signal and we don't want dying probes to pile up).
 		<-execErr
+		out := output.String()
+		var msg string
+		if len(out) > 0 {
+			msg = fmt.Sprintf("Health check exceeded timeout (%v):\n%s", probeTimeout, out)
```
Comment (thaJeztah) [inline daemon/health.go:142]: Before I forget to ask; I see this adds a newline before the output; was there a specific reason for that? Or was it more readable if the output contained multiple lines (e.g.)?

Was wondering if it'd be more readable (assuming single line output) to have it on the same line (`..exceeded timeout(): <output>`) to look more like a regular error message, but perhaps that didn't work well, so thought I'd ask

Comment (ndeloof) [reply daemon/health.go:142]: no specific reason, feels more natural for me to add timeout message as a separate line, then command output

File: daemon/exec.go [hunk 4]
```diff
@@ -292,16 +293,15 @@ func (daemon *Daemon) ContainerExecStart(ctx context.Context, name string, optio
...
-		timeout := time.NewTimer(termProcessTimeout)
-		defer timeout.Stop()
+		daemon.containerd.SignalProcess(sigCtx, c.ID, name, signal.SignalMap["TERM"])
 
 		select {
-		case <-timeout.C:
+		case <-sigCtx.Done():
 			logrus.Infof("Container %v, process %v failed to exit within %v of signal TERM - using the force", c.ID, name, termProcessTimeout)
-			daemon.containerd.SignalProcess(ctx, c.ID, name, signal.SignalMap["KILL"])
+			daemon.containerd.SignalProcess(context.Background(), c.ID, name, signal.SignalMap["KILL"])
```
Comment (corhere) [inline daemon/exec.go:304]: `SignalProcess` sends an RPC, therefore could potentially hang for a long time if things go wrong. Some timeout might be appropriate?

I wish execs were terminated by calling a method rather than by canceling a context. A caller would then be able to pass a dedicated context just for the termination operation instead of having to hardcode some policy into the `ContainerExecStart` implementation.

**Review by corhere — DISMISSED** [review]

File: daemon/exec.go (hunk 4 above)
Comment (ndeloof) [reply daemon/exec.go:304]: Makes sense to me to use a timeout here, but which value to use? `termProcessTimeout` applies to target process to terminate, not internal communication delays.

About global design, I agree use of a cancelable context here to stop exec is not very pleasant, considering the significant amount of additional API calls involved.

**Comment by ndeloof** [comment]
I'm stuck here with test failing on CI
`health_test.go:112: timeout hit after 10s: waiting for container healthcheck logs`

File: daemon/exec.go [hunk 5]
```diff
@@ -293,15 +296,14 @@ func (daemon *Daemon) ContainerExecStart(ctx context.Context, name string, optio
 	select {
 	case <-ctx.Done():
 		logrus.Debugf("Sending TERM signal to process %v in container %v", name, c.ID)
-		daemon.containerd.SignalProcess(ctx, c.ID, name, signal.SignalMap["TERM"])
+		daemon.containerd.SignalProcess(context.Background(), c.ID, name, signal.SignalMap["TERM"])
 
 		timeout := time.NewTimer(termProcessTimeout)
```
Comment (vvoland) [inline daemon/exec.go:301]: Process has 10s to process the SIGTERM - in the test case SIGTERM is just ignored, so this will have to wait 10 seconds.

File: integration/container/health_test.go [hunk 6]
```diff
@@ -93,6 +94,42 @@ while true; do sleep 1; done
...
+
+	cID := container.Run(ctx, t, client, func(c *container.TestContainerConfig) {
+		c.Config.Healthcheck = &containertypes.HealthConfig{
+			Test:     []string{"CMD-SHELL", "sh -c 'trap \"echo SIGTERM\" 15; while true; do true; done;'"},
+			Interval: 100 * time.Millisecond,
+			Timeout:  50 * time.Millisecond,
+			Retries:  1,
+		}
+	})
+	poll.WaitOn(t, pollForHealthCheckLog(ctx, client, cID, "Health check exceeded timeout (50ms):\nSIGTERM\n"))
```
Comment (vvoland) [inline integration/container/health_test.go:112]: And the default timeout for poll.WaitOn is 10s :) So the SIGKILL isn't sent, because the test ends first.
This could be fixed by increasing the timeout here, but that means that the test will take 10s to finish... 🤔

File: daemon/exec.go (hunk 5 above)
Comment (ndeloof) [reply daemon/exec.go:301]: Oh, so obvious I didn't saw it... thanks

File: integration/container/health_test.go [hunk 7]
```diff
@@ -93,6 +94,41 @@ while true; do sleep 1; done
...
+// TestHealthCheckProcessKilled verifies that health-checks exec get killed on time-out.
+func TestHealthCheckProcessKilled(t *testing.T) {
+	skip.If(t, testEnv.OSType == "windows", "FIXME")
+	defer setupTest(t)()
+	ctx := context.Background()
+	client := testEnv.APIClient()
+
+	cID := container.Run(ctx, t, client, func(c *container.TestContainerConfig) {
+		c.Config.Healthcheck = &containertypes.HealthConfig{
+			Test:     []string{"CMD-SHELL", "sh -c 'trap \"echo SIGTERM\" 15; while true; do true; done;'"},
```
[the remark this answers is not in the document]
Comment (corhere) [reply integration/container/health_test.go:106]: I'm not so sure it's that `sleep` is blocking signals. I suspect that what's actually happening is busybox `ash` waits for the `sleep` subprocess to exit before executing the trap, [matching the behaviour of `bash`](https://www.gnu.org/software/bash/manual/html_node/Signals.html#:~:text=If%20Bash%20is,trap%20is%20executed.), and the daemon is only sending the signals to the topmost shell process so the `sleep` subprocess is never sent a signal.

Maybe something like this would work?
```sh
trap "echo SIGTERM" 15
sleep 30 &
pid=$!
while jobs %% >/dev/null; do wait $pid; done
```
I tested this interactively in `library/busybox:latest` and it seems to work, though the background job leaks.

Although, if it really is the case that the trap is not executing because the shell is waiting for the `sleep` command to complete, running `usleep` in a loop would effectively "poll" for the trapped signals with an upper-bound latency of the duration of the `usleep` command. No fancy stuff with background jobs required!
```suggestion
			Test:     []string{"CMD-SHELL", "sh -c 'trap \"echo SIGTERM\" 15; while true; do usleep 50000; done;'"},
```

File: daemon/exec.go (hunk 4 above)
Comment (corhere) [reply daemon/exec.go:306]: I'd pick a timeout value which is large enough to never be hit when containerd is responsive, accounting for potentially massive network latencies, but which is not actually forever so that requests to an unresponsive containerd (or a [slowloris](https://en.wikipedia.org/wiki/Slowloris_(computer_security)) honeypot masquerading as a containerd) don't leak resources indefinitely. How does 30 seconds each sound?

**Review by thaJeztah — CHANGES_REQUESTED** [review]

**Comment by thaJeztah** [comment]
@ndeloof @corhere while reviewing, I was playing a bit with some options; I opened them as https://github.com/ndeloof/docker/pull/2

First commit of that branch moves the timeout to ExecConfig
Second commit changes the timeout for health-checks to a fixed (but short) value; I picked 0.5 seconds, but open to discussion for that.

Feedback / thoughts welcome 😅

File: daemon/exec.go [hunk 8]
```diff
@@ -293,15 +296,22 @@ func (daemon *Daemon) ContainerExecStart(ctx context.Context, name string, optio
...
-		daemon.containerd.SignalProcess(ctx, c.ID, name, signal.SignalMap["TERM"])
+		sigCtx, cancelFunc := context.WithTimeout(context.Background(), 30*time.Second)
+		defer cancelFunc()
+		daemon.containerd.SignalProcess(sigCtx, c.ID, name, signal.SignalMap["TERM"])
 
-		timeout := time.NewTimer(termProcessTimeout)
+		wait := termProcessTimeout
+		if ec.StopTimeout != nil {
+			wait = *ec.StopTimeout
+		}
```
Comment (corhere) [inline daemon/exec.go:306]: If we're making the timeout configurable anyway, what do you think of dropping the arbitrary default value and leave it entirely up to the caller to dictate the policy? I'm thinking along the lines of [mirroring this proposal for `os/exec`](https://github.com/golang/go/issues/50436) which defaults to insta-kill on cancel while allowing for both the graceful-terminate signal and timeout to be configured.

Comment (corhere) [reply daemon/exec.go:306]: To clarify, I am not suggesting we expose any features to users. My line of thinking is that the API handler `func (*containerRouter) postContainerExecCreate` would be a more appropriate place to dictate the stop-timeout policy for execs created via the API, even if it is the existing hardcoded `termProcessTimeout` policy, just like how `cmdProbe` now dictates the policy for health-check execs. The obvious implementation would require adding a `StopTimeout` field to `types.ExecConfig`, though tagging it <tt>\`json:"-"\`</tt> would keep it from being exposed in the Engine API, just like its analogue in `container.HealthConfig`.

File: daemon/health.go [hunk 9]
```diff
@@ -81,6 +81,8 @@ func (p *cmdProbe) run(ctx context.Context, d *Daemon, cntr *container.Container
 	execConfig.Privileged = false
 	execConfig.User = cntr.Config.User
 	execConfig.WorkingDir = cntr.Config.WorkingDir
+	// health checks don't get the full 10 seconds timeout for a .
```
Comment (thaJeztah) [inline daemon/health.go:84]: whoops; looks like I was still writing here but didn't finish that before opening https://github.com/ndeloof/docker/pull/2

Trying to recall what I wanted to write here; I guess something about stopping gracefully.

```go
// health checks don't get the full 10 seconds timeout to stop gracefully.
```

File: daemon/exec.go (hunk 8 above)
Comment (thaJeztah) [reply daemon/exec.go:306]: Not 100% sure if those defaults should make its way into the API endpoint, but perhaps in `Daemon.ContainerExecCreate()`, as that's where the exec config is created (and to match what I did for the health check) https://github.com/moby/moby/blob/4eb1c5bd52afa08595d9a082a9ba05c81f79be07/daemon/exec.go#L98

That way the code here (`ContainerExecStart`) wouldn't have to bother with checking if all options are there, and just consume the exec-config as stored. Perhaps make `exec.NewConfig()` accept options so that we don't have the awkward code in both locations to first do a `exec.NewConfig()`, and then having to manually manipulate it to set all the other options.

Given that the health check code doesn't use the endpoint, nor `Daemon.ContainerExecCreate()`, I think that would also be fine to do separately though 🤔 WDYT?

Comment (ndeloof) [reply daemon/exec.go:306]: I totally agree default values should be handled while initializing struct, vs checking for nil to apply defaults.
Constructors is one of the language feature I miss the most writing Go. I'd be happy we rely on `NewXX` initializer pattern everywhere possible

Comment (thaJeztah) [reply daemon/exec.go:306]: > I totally agree default values should be handled while initializing struct, vs checking for nil to apply defaults.

I should note that it's not always possible to do so when constructing things; some default should be "baked" into a struct, whereas some other defaults may have to be evaluated at runtime (e.g. if option X isn't set, take the current default as configured in the environment and/or daemon configuration).

But I agree that having a canonical location to where defaults are set (_where possible_) is good. Currently there's too many places where defaults are set, which means you often have to drill through a lot of code to figure out where they're set.

Comment (thaJeztah) [reply daemon/exec.go:306]: ^^ we should not increase the scope of this PR too much though; I haven't checked yet what would be needed, but I'd still be fine to tackle that in a follow-up (more "improve exec in general, not just for health-check").

Perhaps just moving this to `ContainerExecCreate()` would work though;

```go
if ec.StopTimeout != nil {
	wait = *ec.StopTimeout
}
```

Which could be just a line added here; https://github.com/moby/moby/blob/4eb1c5bd52afa08595d9a082a9ba05c81f79be07/daemon/exec.go#L128


```go
execConfig.StopTimeout = termProcessTimeout
```

File: daemon/health.go [hunk 10]
```diff
@@ -81,6 +81,11 @@ func (p *cmdProbe) run(ctx context.Context, d *Daemon, cntr *container.Container
 	execConfig.Privileged = false
 	execConfig.User = cntr.Config.User
 	execConfig.WorkingDir = cntr.Config.WorkingDir
+	// health checks don't get the full 10 seconds timeout to stop gracefully.
+	execConfig.StopTimeout = 500 * time.Millisecond
+	if cntr.Config.Healthcheck.StopTimeout != 0 {
+		execConfig.StopTimeout = cntr.Config.Healthcheck.StopTimeout
+	}
```
Comment (thaJeztah) [inline daemon/health.go:88]: Wondering why you added this back in your last push; is this only to make the test run faster (50 ms instead of 500)? Otherwise we can omit the changes to the `Healthcheck` type

Comment (thaJeztah) [reply daemon/health.go:88]: Gave it a quick try, and it seems to work, but let me know if you had a specific reason for this 😅 https://github.com/ndeloof/docker/pull/3

Comment (ndeloof) [reply daemon/health.go:88]: yes, goal is to keep test fast. Not being able to control timing demonstrate lack of design for testability imho

Comment (thaJeztah) [reply daemon/health.go:88]: Not everything has to be configurable; we could make the fixed value shorter of course; not sure if saving half a second for a test warrants a change to an exported struct though (if it's only used in a test)

**Comment by corhere** [comment]
The code to terminate health check execs gracefully has been broken [since v17.11](https://github.com/moby/moby/commit/ddae20c032058a0fd42c34c2e9750ee8f6296ac8#diff-73eee5ff6da257cc3f90a10ff07f4d47e02e7999e317f4ce0bb9eab7f662193fR263), nearly five years ago! The "statute of limitations" has arguably expired on the feature and so we have an opportunity to change the behaviour. The graceful termination code in `ContainerExecStart` is only used by health checks (the exec API handler calls `ContainerExecStart` with the background context) so we could replace it with whatever other behaviour we wanted. Kubernetes exec probes with cri-containerd send `SIGKILL` immediately upon timeout; we could do the same. That would both simplify the implementation and speed up test runs by half a second. @thaJeztah mentioned during today's maintainer meeting that he might take that on in an alternative PR so you may want to with him to avoid duplicating work.

**Review by olljanat — APPROVED** [review]
I can confirm that issue #43737 does not exist on Windows with HCS v1 but will appear there when containerd mode is enabled and this fix looks working fine on there too.

LGTM

**Comment by corhere** [comment]
@thaJeztah @cpuguy83 @tianon PTAL

**Comment by thaJeztah** [comment]
CRIU repo down again? Let me give it another kick

```
failed to load cache key: Get "https://download.opensuse.org/repositories/devel:/tools:/criu/Debian_11/Release.key": dial tcp 195.135.221.134:443: i/o timeout
script returned exit code 1
```

File: daemon/health.go [hunk 11]
```diff
@@ -133,12 +133,19 @@ func (p *cmdProbe) run(ctx context.Context, d *Daemon, cntr *container.Container
...
 		cancelProbe()
 		logrus.WithContext(ctx).Debugf("Health check for container %s taking too long", cntr.ID)
-		// Wait for probe to exit (it might take a while to respond to the TERM
-		// signal and we don't want dying probes to pile up).
+		// Wait for probe to exit (it might take some time to call containerd to kill
+		// the process and we don't want dying probes to pile up).
 		<-execErr
+		out := output.String()
+		var msg string
+		if len(out) > 0 {
```
Comment (thaJeztah) [inline daemon/health.go:141]: Oh, since you need to update for the other bit; perhaps also make the `out` variable local here (slightly clearer to indicate it's not used elsewhere);
```suggestion

		var msg string
		if out := output.String(); len(out) > 0 {
```

Comment (thaJeztah) [reply daemon/health.go:141]: 👇 oh, and perhaps you have thoughts on the newline as well; I'm not _really_ tried to it, mostly wondering if using a space instead of a newline would be more "standard" (and possibly ease grep-ing for failed checks combined with output - not sure)

**Review by thaJeztah — CHANGES_REQUESTED** [review]
@corhere looks like there's a small issue (pointed out); also left two suggestions for consideration.

Do we want to keep the commits separate? (mostly looking at the test, which is only added in the second commit 😅

**Comment by thaJeztah** [comment]
> mostly looking at the test, which is only added in the second commit

I think the `output` was added for the original change where we needed the output to see if the trap was called; from that perspective, it's not needed anymore to test the fix, so I _think_ we could have a basic test in the first commit (if we want to backport to 20.10), and make the second commit an "enhancement" commit (to include the output), which could be in 22.06; WDYT?

**Comment by thaJeztah** [comment]
@corhere I pushed a branch making that split; let me know if that looks good to you (if so, I could push to this PR); https://github.com/moby/moby/compare/master...thaJeztah:healthcheck_timeout_split?expand=1

**Comment by corhere** [comment]
@thaJeztah your branch LGTM; push away! I have no strong feelings either way regarding the newline in the timeout msg.

**Comment by thaJeztah** [comment]
pushed 👍

**Comment by thaJeztah** [comment]
hm... did I miss a change on Windows? It's passing on Linux, but fails on Windows;

```
=== Failed
=== FAIL: github.com/docker/docker/integration/container TestHealthCheckProcessKilled (3.23s)
    health_test.go:111: polling check failed: expected "Health check exceeded timeout (50ms): logs logs logs\n", got "Health check exceeded timeout (50ms)"
```

Let me check 🤔

**Comment by thaJeztah** [comment]
I guess `output.String()` is empty on Windows for some reason.

Given that (as mentioned above) capturing the logs is not essential for the fix, perhaps I should just move it to a separate follow-up PR; let me do so

**Comment by thaJeztah** [comment]
This is weird; it's as if Windows is running an older commit before the quote was fixed;

```
=== FAIL: github.com/docker/docker/integration/container TestHealthCheckProcessKilled (unknown)
    health_test.go:111: polling check failed: expected "Health check exceeded timeout (50ms)", got "60': line 1: syntax error: unterminated quoted string\n"
coverage: [no statements]
panic: test timed out after 1h0m0s
```

At least, I don't see anything wrong looking at this 🤔;

```go
Test:     []string{"CMD-SHELL", `sh -c 'sleep 60'`},
```

**Comment by thaJeztah** [comment]
I guess `CMD-SHELL` already runs with a shell, so we can probably omit the `sh -c` 🤔

**Comment by thaJeztah** [comment]
```
github.com/docker/docker/integration/container TestHealthCheckProcessKilled (16.06s)
    main_test.go:32: assertion failed: error is not nil: Error response from daemon: Could not kill running container 8147d85d217100444d4d50c351608743d6448fd8f9b200cc1a9491a4d83a1b32, cannot remove - tried to kill container, but did not receive an exit event: failed to remove 8147d85d217100444d4d50c351608743d6448fd8f9b200cc1a9491a4d83a1b32

File: integration/container/health_test.go [hunk 12]
```diff
@@ -93,6 +94,44 @@ while true; do sleep 1; done
...
+			Test:     []string{"CMD-SHELL", "sleep 60"},
+			Interval: 100 * time.Millisecond,
+			Timeout:  50 * time.Millisecond,
+			Retries:  1,
+		}
+	})
+	poll.WaitOn(t, pollForHealthCheckLog(ctx, apiClient, cID, "Health check exceeded timeout (50ms)"))
+
+	err := apiClient.ContainerKill(ctx, cID, "SIGKILL")
+	assert.NilError(t, err)
```
Comment (thaJeztah) [inline integration/container/health_test.go:114]: Let's try if this helps with the cleanup step on Windows 🤞

**Comment by thaJeztah** [comment]
https://github.com/moby/moby/pull/43739#discussion_r950687752

> Let's try if this helps with the cleanup step on Windows 🤞

Unfortunately; that didn't help, only shifting / repeating the problem;

```
=== FAIL: github.com/docker/docker/integration/container TestHealthCheckProcessKilled (27.95s)
    health_test.go:114: assertion failed: error is not nil: Error response from daemon: Cannot kill container: d5e1f84f4dbb83aac2623d972592089575ed8a3917e9d8ddaa487b423938c461: tried to kill container, but did not receive an exit event
    main_test.go:32: assertion failed: error is not nil: Error response from daemon: Could not kill running container d5e1f84f4dbb83aac2623d972592089575ed8a3917e9d8ddaa487b423938c461, cannot remove - tried to kill container, but did not receive an exit event: failed to remove d5e1f84f4dbb83aac2623d972592089575ed8a3917e9d8ddaa487b423938c461
```

So it looks like on Windows, the health check causes an issue with stopping the container (?). Of course the question is; was that already the case (but not tested before?), or is there an issue in the implementation here? (Perhaps an issue with signal handling / incorrect signals for Windows, idk)

File: integration/container/health_test.go [hunk 13]
```diff
@@ -93,6 +94,44 @@ while true; do sleep 1; done
...
 
+// TestHealthCheckProcessKilled verifies that health-checks exec get killed on time-out.
+func TestHealthCheckProcessKilled(t *testing.T) {
+	defer setupTest(t)()
+	ctx := context.Background()
+	apiClient := testEnv.APIClient()
+
+	cID := container.Run(ctx, t, apiClient, func(c *container.TestContainerConfig) {
+		c.Config.Healthcheck = &containertypes.HealthConfig{
+			Test:     []string{"CMD", "sleep", "60"},
```
Comment (thaJeztah) [inline integration/container/health_test.go:105]: Other attempt; trying `CMD ["sleep", "60"]` instead of starting `sleep` in a shell.

**Comment by thaJeztah** [comment]
However, on Windows 2019 and Windows 2022 running with containerd, `TestHealthCheckProcessKilled` times out; wondering if this could be related to something like https://github.com/containerd/containerd/issues/5067

```
=== Failed
=== FAIL: github.com/docker/docker/integration/container TestHealthCheckProcessKilled (unknown)
coverage: [no statements]
panic: test timed out after 1h0m0s

goroutine 199 [running]:
testing.(*M).startAlarm.func1()
	C:/hostedtoolcache/windows/go/1.18.5/x64/src/testing/testing.go:2029 +0x8e
created by time.goFunc
	C:/hostedtoolcache/windows/go/1.18.5/x64/src/time/sleep.go:176 +0x32
	...
```

File: integration/container/health_test.go [hunk 14]
```diff
@@ -93,6 +94,44 @@ while true; do sleep 1; done
...
 
+// TestHealthCheckProcessKilled verifies that health-checks exec get killed on time-out.
+func TestHealthCheckProcessKilled(t *testing.T) {
+	defer setupTest(t)()
+	ctx := context.Background()
+	apiClient := testEnv.APIClient()
+
+	cID := container.Run(ctx, t, apiClient, func(c *container.TestContainerConfig) {
+		c.Config.Healthcheck = &containertypes.HealthConfig{
+			Test:     []string{"CMD-SHELL", `sh -c "sleep 60"`},
```
[the remark this answers is not in the document]
Comment (corhere) [reply integration/container/health_test.go:105]: Relevant CI logs: [builtin](https://github.com/moby/moby/runs/7949749461?check_suite_focus=true#step:21:2952), [`containerd-shim-runhcs-v1`](https://github.com/moby/moby/runs/7949748914?check_suite_focus=true#step:19:2368)

In both cases, the `CommandLine` string ultimately passed into the Win32API `CreateProcess` is
```
cmd /S /C "sh -c \"sleep 60\""
```

After lots of research and experimentation on a Windows box... my head hurts. Here's what I know so far:
- A Windows process' command and arguments are passed in as a single string, which is the string specified in the `CommandLine` passed into `CreateProcess`.
- Each process parses its own command line. Not all processes use the same algorithm.
  - As a corollary,`cmd.exe` does not tokenize its subprocess' command lines for them.
- `cmd.exe /S /C` follows some arcane rules, but the gist is that everything following the `/C` is taken literally as a command line, with one exception: if the first non-whitespace character following the `/C` is a double-quote character, the command line is modified by dropping that character and the last double-quote character in the remaining command-line.

Putting that all together:
`cmd /S /C "sh -c \"sleep 60\""` is equivalent to interactively running
```
C:\> sh -c \"sleep 60\"
```
Executing that command results in `CreateProcess()` being called with `CommandLine` set to `sh -c \"sleep 60\"`.

The Windows C Runtime parses the `CommandLine` `sh -c \"sleep 60\"` into the argv
```
argv[0] = sh
argv[1] = -c
argv[2] = \"sleep
argv[3] = 60\"
```
and busybox ash gets very confused.

The ultimate issue is that `cmdProbe` is incorrectly escaping the shell command line in a manner which the Windows C runtime would parse as a single argument, expecting `cmd.exe /S /C` to act like `sh -c` and consume the next argv as its argument. But `cmd.exe` does not unescape the argument.

https://github.com/containerd/containerd/issues/5067 is very related to the above, but I don't think it has to do with the timeouts you saw. (My guess is that the timeouts have something to do with `sleep.exe` not existing.)

**Comment by thaJeztah** [comment]
windows 2022 / containerd;

```
=== FAIL: github.com/docker/docker/integration/container TestHealthCheckProcessKilled (15.43s)
    main_test.go:32: assertion failed: error is not nil: Error response from daemon: Could not kill running container d4a736c61017160c76188113089560575c359d42db1ff5b6e2e18838002a985d, cannot remove - tried to kill container, but did not receive an exit event: failed to remove d4a736c61017160c76188113089560575c359d42db1ff5b6e2e18838002a985d

File: integration/container/health_test.go [hunk 15]
```diff
@@ -93,6 +94,42 @@ while true; do sleep 1; done
 	poll.WaitOn(t, pollForHealthStatus(ctxPoll, client, id, "healthy"), poll.WithDelay(100*time.Millisecond))
 }
 
+// TestHealthCheckProcessKilled verifies that health-checks exec get killed on time-out.
+func TestHealthCheckProcessKilled(t *testing.T) {
+	skip.If(t, testEnv.RuntimeIsWindowsContainerd(), "FIXME: Broken on Windows + containerd combination")
```
Comment (thaJeztah) [inline integration/container/health_test.go:99]: I added a `skip` for now.

File: integration/container/health_test.go (hunk 14 above)
[the remark this answers is not in the document]
Comment (thaJeztah) [reply integration/container/health_test.go]: I recall I tested various combinations; any of them would fail on at least _one_ combination 😞 

I tried running `sleep` as main process itself;

```
[]string{"CMD", "sleep",  "60"},
```

Which would be the equivalent of the default command we set for "sleep" containers; https://github.com/moby/moby/blob/7b9275c0da707b030e62c96b679a976f31f929d3/integration-cli/test_vars_test.go#L6-L9

Tried running it as child process of `sh`;

```
[]string{"CMD", "sh", "-c", "sleep 60"},
```

Tried passing it as single string, but I think Linux wasn't a fan of that

```
[]string{"CMD-SHELL", `sh -c "sleep 60`},
```


And the original one (which (like above), and if I'm not mistaken, would run `sh` as child process of `cmd`, so that didn't feel right);

```
[]string{"CMD-SHELL", "sh", "-c", "sleep 60"},
```

[the remark this answers is not in the document]
Comment (thaJeztah) [reply integration/container/health_test.go]: One thing I wonder is if the Busybox image should also be updated to set the `SHELL` to `/bin/sh`; currently it doesn't, which means that (in Dockerfiles), the default shell would still be `cmd` or `powershell` (depending on the base image)

[the remark this answers is not in the document]
Comment (thaJeztah) [reply integration/container/health_test.go]: Also wondering if `exec.Config` needs to have a `CommandLine` property added; it just occurred to me that we have that for the container's main process, but don't have it for `exec` 🤔 https://github.com/moby/moby/blob/2646beac875eaf69930387d04fceca89e93d1da1/vendor/github.com/opencontainers/runtime-spec/specs-go/config.go#L41-L43

[the remark this answers is not in the document]
Comment (corhere) [reply integration/container/health_test.go]: > One thing I wonder is if the Busybox image should also be updated to set the `SHELL` to `/bin/sh`

> Also wondering if `exec.Config` needs to have a `CommandLine` property added

Both excellent ideas I wholeheartedly support!

**Comment by thaJeztah** [comment]
Some unrelated failures; not sure I've seen this one before, but doesn't look related at least (kicked CI once more)

```
=== FAIL: github.com/docker/docker/integration-cli TestDockerCLIPsSuite/TestPsListContainersFilterID (19.48s)
    check_test.go:402: assertion failed: error is not nil: Error response from daemon: Could not kill running container a617f7b8cf70de3b92c7e740bcd129fba04c00d86457b93fb434379dc9b7cae5, cannot remove - tried to kill container, but did not receive an exit event: failed to remove a617f7b8cf70de3b92c7e740bcd129fba04c00d86457b93fb434379dc9b7cae5
    --- FAIL: TestDockerCLIPsSuite/TestPsListContainersFilterID (19.48s)
```

**Review by thaJeztah — APPROVED** [review]
It's greeeen!

LGTM

**Review by tianon — APPROVED** [review]

**Comment by thaJeztah** [comment]
Alright, let's get this one in
