### PR TITLE
Fix panic on starting exec more than once

### LINKED ISSUE #19362: Docker daemon crashes after a sequence of API calls
After a sequence of API calls related to execs Docker daemon crashes with a panic.

`docker version`:
```
% docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5
 Built:        Sat Nov 21 00:48:57 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:
```
% docker info
Containers: 2
Images: 72
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 76
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: vdocker
ID: AX4W:Z2PE:OHDD:SMJK:PH5C:U4GR:WVNK:5YFF:N476:W6NW:NAKK:2KSM
Debug mode (server): true
 File Descriptors: 13
 Goroutines: 19
 System Time: 2016-01-15T14:08:27.509022642Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

However, I've also reproduced this problem on an Amazon Linux VM (can't access it now), also with Docker 1.9.1.

`uname -a`:

```
% uname -a
Darwin qplex.local 14.5.0 Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64 x86_64
% docker-machine ssh vdocker uname -a
Linux vdocker 4.1.13-boot2docker #1 SMP Fri Nov 20 19:05:50 UTC 2015 x86_64 GNU/Linux
```

Steps to reproduce:

1\. Create a simple container which does nothing:
```
% docker run -d ubuntu:latest bash -c "while true; do sleep 10s; done"
d243ec78bdc3b61655dbc8da993c662b462ac9b8fb478655023130f8d62c113d
```

2\. Invoke an API call to create an exec with a simple command:
```
% http --verify=no --cert $HOME/.docker/machine/machines/vdocker/cert.pem --cert-key $HOME/.docker/machine/machines/vdocker/key.pem POST https://192.168.99.100:2376/containers/d243ec78bdc3b61655dbc8da993c662b462ac9b8fb478655023130f8d62c113d/exec AttachStdin:=false AttachStdout:=true AttachStderr:=true Tty:=false Cmd:='["test", "-e", "/createme"]'
HTTP/1.1 201 Created
Content-Length: 74
Content-Type: application/json
Date: Fri, 15 Jan 2016 14:12:40 GMT
Server: Docker/1.9.1 (linux)

{
    "Id": "2c2c3dcc47bdd91f038b054a86faf3671fb2e08ce82ce74f4848b57068d3b77e"
}
```

3\. Start the newly created exec through the API:
```
% http --verify=no --cert $HOME/.docker/machine/machines/vdocker/cert.pem --cert-key $HOME/.docker/machine/machines/vdocker/key.pem POST https://192.168.99.100:2376/exec/2c2c3dcc47bdd91f038b054a86faf3671fb2e08ce82ce74f4848b57068d3b77e/start Detach:=false Tty:=false
HTTP/1.1 200 OK
Content-Type: application/vnd.docker.raw-stream
```
Docker appears intact:
```
% docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
d243ec78bdc3        ubuntu:latest       "bash -c 'while true;"   2 minutes ago       Up 2 minutes                            hopeful_visvesvaraya
```

4\. Start the same command again:
```
% http --verify=no --cert $HOME/.docker/machine/machines/vdocker/cert.pem --cert-key $HOME/.docker/machine/machines/vdocker/key.pem POST https://192.168.99.100:2376/exec/2c2c3dcc47bdd91f038b054a86faf3671fb2e08ce82ce74f4848b57068d3b77e/start Detach:=false Tty:=false
HTTP/1.1 200 OK
Content-Type: application/vnd.docker.raw-stream
```
Docker is now down:
```
% docker ps
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

Log file contains the following messages:
```
time="2016-01-15T14:14:05.080977771Z" level=debug msg="Calling POST /exec/2c2c3dcc47bdd91f038b054a86faf3671fb2e08ce82ce74f4848b57068d3b77e/start"
time="2016-01-15T14:14:05.081603096Z" level=info msg="POST /exec/2c2c3dcc47bdd91f038b054a86faf3671fb2e08ce82ce74f4848b57068d3b77e/start"
time="2016-01-15T14:14:05.081852263Z" level=debug msg="starting exec command 2c2c3dcc47bdd91f038b054a86faf3671fb2e08ce82ce74f4848b57068d3b77e in container d243ec78bdc3b61655dbc8da993c662b462ac9b8fb4786550
time="2016-01-15T14:14:05.081982354Z" level=debug msg="attach: stdout: begin"
time="2016-01-15T14:14:05.082009897Z" level=debug msg="attach: stderr: begin"
panic: close of closed channel
```

Full log is available [here](https://gist.github.com/netvl/d4f9d11a1ccc81b5bc19).

Naturally, I expected Docker not to crash.

This scenario actually worked some time ago, but I can only say for certain that it stopped working around a month ago.

### PR DESCRIPTION
**Pull request by cpuguy83**
Issue was caused when exec is tarted, exits, then stated again.
In this case, `Close` is called twice, which closes a channel twice.

Changes execConfig.ExitCode to a pointer so we can test if the it has
been set or not.
This allows us to return early when the exec has already been run.

Fixes #19362

### CODE REVIEW

File: integration-cli/docker_api_exec_test.go [hunk 1]
```diff
@@ -108,6 +99,30 @@ func (s *DockerSuite) TestExecAPIStartBackwardsCompatible(c *check.C) {
 	c.Assert(resp.StatusCode, checker.Equals, http.StatusOK, comment)
 }
 
+// #19362
```
Comment (thaJeztah) [inline integration-cli/docker_api_exec_test.go]: perhaps this should have a short description and the full URL to the issue (in case code is moved around or read outside of github)

**Comment by calavera** [comment]
LGTM

File: integration-cli/docker_api_exec_test.go (hunk 1 above)
Comment (calavera) [inline integration-cli/docker_api_exec_test.go]: is it even necessary? git blame can give you the commit and you can trace that back to the PR and issue in github.

**Comment by runcom** [comment]
LGTM

File: integration-cli/docker_api_exec_test.go (hunk 1 above)
Comment (thaJeztah) [inline integration-cli/docker_api_exec_test.go]: See it as a nit, but in general I think code should not have to rely on GitHub in order to get the information needed.

**Comment by estesp** [comment]
LGTM
