### PR TITLE
Flag Addition: --type flag added for docker inspect command

### LINKED ISSUE #12483: "docker inspect" can't reach the image JSON when there is a same name container running.
Description of problem:
When there is a image named, for instance "rhel7" and a container is also has the same name, then "docker inspect rhel7" only shows containers json, the command can't reach the image's scope. 

Version-Release number of selected component (if applicable):
docker-1.6.0-2.el7.x86_64

How reproducible:
100%

Steps to Reproduce:
1.
# docker images
REPOSITORY                                    TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
registry.access.redhat.com/rhel7              latest              10acc31def5d        10 weeks ago        154.1 MB

#docker run --name rhel7 rhel7 /bin/bash
# docker ps -a
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS                   PORTS               NAMES
d4ac50753fe4        rhel7:latest        "/bin/bash"            2 hours ago         Exited (0) 2 hours ago                       rhel7            

2.
#docker inspect rhel7
Debug log:(reach the container, then return)
DEBU[0026] Calling GET /containers/json                 
INFO[0026] GET /v1.18/containers/json?all=1             
INFO[0026] +job containers()                            
INFO[0026] -job containers() = OK (0)                   
DEBU[0064] Calling GET /containers/{name:.*}/json       
INFO[0064] GET /v1.18/containers/rhel7/json             
INFO[0064] +job container_inspect(rhel7)                
INFO[0064] -job container_inspect(rhel7) = OK (0) 

Otherwise, after delete the container,
(fail to find the container then continue to reach the image and return

DEBU[0106] Calling GET /containers/{name:.*}/json       
INFO[0106] GET /v1.18/containers/rhel7/json             
INFO[0106] +job container_inspect(rhel7)                
no such id: rhel7
INFO[0106] -job container_inspect(rhel7) = ERR (1)      
ERRO[0106] Handler for GET /containers/{name:.*}/json returned error: no such id: rhel7 
ERRO[0106] HTTP Error: statusCode=404 no such id: rhel7 
DEBU[0106] Calling GET /images/{name:.*}/json           
INFO[0106] GET /v1.18/images/rhel7/json                 
INFO[0106] +job image_inspect(rhel7)                    
INFO[0106] -job image_inspect(rhel7) = OK (0)

### PR DESCRIPTION
**Pull request by shishir-a412ed**
Fixes #12483 

Signed-off-by: Shishir Mahajan shishir.mahajan@redhat.com

### CODE REVIEW

**Comment by jfrazelle** [comment]
why two flags its not really scalable...

**Comment by calavera** [comment]
I'm :-1: to the solution, but I acknowledge the problem.

There are a couple possibilities that might be better suitable to solve the problem:

1. Since we acknowledge that a container and an image can have the same name, we can argue that we should always perform the two calls. This is probably the easier solution, 0 flags needed. We can be slightly fancy and try to detect whether the argument is a container id or not, and only send the container request in the first case.

2. If we don't want to send two requests every time, we can add a `--all` flag and do what I propose in 1 when the flag is enabled.

**Comment by shishir-a412ed** [comment]
@calavera 
we contemplated that option but we felt it can present an awful lot of information to user.
e.g. `docker inspect --all arg1 arg2 arg3 ..... argN` can show `N * 2` JSON to the user, whereas all user wanted was to see the image JSON which were being shadowed by the container JSON, since they shared the same name.

**Comment by cpuguy83** [comment]
What if we do `--image` and `--container`, but make them both true by default.

**Comment by jfrazelle** [comment]
No 2 flags!!!

**Comment by cpuguy83** [comment]
Ok, `--type`

**Comment by duglin** [comment]
oh man, can we please consider just adding a new command: `docker inspecti ...` like we have `docker rmi ...`.  I'm not thrilled with just adding an 'i' to the end of the command but at least we're consistent and it would then be very clear what we're talking about.

**Comment by rhatdan** [comment]
I don't really understand the argument against two arguments.  It is not like the docker inspect has a whole ton of options now.  Originally we were going to use just --image-only, but then why couldn't you ask for only container matches.  

Bottom line is we have bug reports from people trying to look at images with the same name as a container, and we want a simple way for the users to be able to examine them without having to understand where to search for the UUid field in a container json file.
  
I actually hate rmi versus rm, but I guess that somewhat follows the standard of rm versus rmdir. 

If we went with this behaviour we should break existing behaviour for consistency.  

This seems like a simple fix, but simple fixes often bring out Bike Shedding arguments.

**Comment by jfrazelle** [comment]
It's a UI decision I know the struggle with it being the same name but two
flags is imo dumb and doesn't scale

**Comment by shishir-a412ed** [comment]
@jfrazelle what do you mean by `2 flags doesn't scale` ? 
Can you give an example or scenario ?

**Comment by rhatdan** [comment]
Not sure how adding additional commands scales better then adding options. I would argue the exact opposite.

**Comment by jfrazelle** [comment]
Adding 2 flags that are super specific to 1 thing is "not scalable" because
now if you inspect anything other than images or containers in docker, whoa
look we need to add a new flag for that too

But honestly I don't want to fight about this, do what you want, see what
happens when users think docker is hard to use because we have a bajillion
flags, each one does 1 thing

**Comment by jfrazelle** [comment]
Also I'm definitely -1 on a inspecti, rmi is awful and we should not go
down that road again, the only ok example given here was --type because at
least we can add more things to inspect in the future without a new flag
for each one

**Comment by shishir-a412ed** [comment]
@jfrazelle
 boolean flags are binary {true/false, 0/1} in nature. If that is your concern, then @cpuguy83 suggested `--type` flag which would be a string flag and can take all kind of values.

I understand your concern and its a valid one, but IMHO `docker inspect` really doesn't have that many flags to begin with. n the use-case is legitimate.

**Comment by rhatdan** [comment]
I am fine with --type=image or --type=container.

**Comment by duglin** [comment]
The only way a new flag helps, IMO, is if its mandatory. W/o it being required we’re then
still left with the current mess of the code guessing as to what the user intended to take action
on.  That’s just a horrible design. While “rmi” and “inspecti” are not my favorite things, 
at least its unambiguous and no room for confusion.

Ideally, I would have preferred if we had “docker container inspect” and “docker image inspect”
but that’s another discussion.

**Comment by jfrazelle** [comment]
I think there is a real use case for adding a flag for this, I've hit numerous times w my irssi container

**Comment by shishir-a412ed** [comment]
@jfrazelle @calavera @rhatdan 
I have updated the code and docs.

**Comment by jfrazelle** [comment]
design LGTM thanks

**Comment by thaJeztah** [comment]
> Ideally, I would have preferred if we had “docker container inspect” and “docker image inspect”
but that’s another discussion

I created an issue for that once here; https://github.com/docker/docker/issues/8829

But on-topic; what's the status on this? Is the `--type=` an acceptable solution?

**Comment by calavera** [comment]
design LGTM. Moving to code review.

File: contrib/completion/bash/docker [hunk 1]
```diff
@@ -514,14 +514,14 @@ _docker_info() {
 
 _docker_inspect() {
 	case "$prev" in
-		--format|-f)
+		--format|-f|--type)
```
Comment (albers) [inline contrib/completion/bash/docker]: Completion should be more specific here, i.e. complete to `image` and `container` instead of accepting any input. Here's an [example](https://github.com/docker/docker/blob/master/contrib/completion/bash/docker#L223).

File: api/client/inspect.go [hunk 2]
```diff
@@ -18,42 +18,72 @@ import (
...
+
+		}
+
+		if !isContainer {
 			obj, _, err = readBody(cli.call("GET", "/images/"+name+"/json", nil, nil))
 			isImage = true
 			if err != nil {
 				if strings.Contains(err.Error(), "No such") {
-					fmt.Fprintf(cli.err, "Error: No such image or container: %s\n", name)
+					fmt.Fprintf(cli.err, "Error: No such image: %s\n", name)
```
Comment (duglin) [inline api/client/inspect.go]: I think this will change the output people see today if they don't specify `--type`, so we can't do that.
You may need to change the message based on the presence of `--type=image`.

File: api/client/inspect.go [hunk 3]
```diff
@@ -18,42 +18,72 @@ import (
...
+						fmt.Fprintf(cli.err, "%s", err)
+					}
+					status = 1
+					continue
+				}
+			}
+
+		}
+
+		if !isContainer {
```
Comment (duglin) [inline api/client/inspect.go]: Minor thing, but I would prefer to remove the `isContainer` flag and just change this line to:
```
if *inspectType == "" || *inspectType == "image" {
```
Just less levels of indirection to follow.

Comment (duglin) [inline api/client/inspect.go]: And I guess you'd need to check for `obj != nil`

**Comment by duglin** [comment]
Need some testcases.

**Comment by rhatdan** [comment]
@shishir-a412ed  Can you see about adding some test cases.

File: api/client/inspect.go (hunk 3 above)
Comment (shishir-a412ed) [inline api/client/inspect.go]: @duglin I cannot change that to, `if *inspectType == "" || *inspectType == "image" {`
because then in the default behavior it will go for both container and image JSON {will show the image JSON only in the output), which will change the existing behavior.

There is no `obj != nil` check in the existing upstream code. Would you like me to add this additional check ?

File: api/client/inspect.go (hunk 2 above)
Comment (shishir-a412ed) [inline api/client/inspect.go]: Sounds reasonable. Will fix this.

File: api/client/inspect.go (hunk 3 above)
Comment (duglin) [inline api/client/inspect.go]: I'm not following, if it was:
```
if obj == nil && (*inspectType == "" || *inspectType == "image")
```
then it'll only go into the 'image' logic if the 'container' logic didn't find it, right?

Comment (shishir-a412ed) [inline api/client/inspect.go]: @duglin Sorry I was reading it as two independent conditions ! I have made the changes.

**Comment by shishir-a412ed** [comment]
@duglin @rhatdan I have added the test cases.

File: contrib/completion/bash/docker (hunk 1 above)
Comment (shishir-a412ed) [inline contrib/completion/bash/docker]: @albers I have fixed the bash completion part.

**Comment by albers** [comment]
Bash completion LGTM.

File: api/client/inspect.go [hunk 4]
```diff
@@ -18,42 +18,68 @@ import (
...
 	if *tmplStr != "" {
-		var err error
 		if tmpl, err = template.New("").Funcs(funcMap).Parse(*tmplStr); err != nil {
 			return StatusError{StatusCode: 64,
 				Status: "Template parsing error: " + err.Error()}
 		}
 	}
 
+	if *inspectType != "" && *inspectType != "container" && *inspectType != "image" {
+		return fmt.Errorf("%s is not a valid value for --type", *inspectType)
```
Comment (duglin) [inline api/client/inspect.go]: s/%s/%q/ just add quotes around it.

File: docs/reference/commandline/cli.md [hunk 5]
```diff
@@ -1552,6 +1552,8 @@ ensure we know how your setup is configured.
     Return low-level information on a container or image
 
       -f, --format=""    Format the output using the given go template
+      --type=""		 Return JSON for specified type, permissible values are 
+			 image or container
```
Comment (duglin) [inline docs/reference/commandline/cli.md]: Try to fix the alignment by using spaces instead of tabs.

File: integration-cli/docker_cli_inspect_test.go [hunk 6]
```diff
@@ -38,6 +38,95 @@ func (s *DockerSuite) TestInspectInt64(c *check.C) {
...
+
+	formatStr := fmt.Sprintf("--format='{{.State.Running}}'")
+	inspectCmd := exec.Command(dockerBinary, "inspect", "--type=container", formatStr, "busybox")
+
+	out, exitCode, err := runCommandWithOutput(inspectCmd)
+	if exitCode != 0 || err != nil {
+		c.Fatalf("failed to inspect container: %s, %v", out, err)
+	}
+
+	if out != "true\n" {
```
Comment (duglin) [inline integration-cli/docker_cli_inspect_test.go]: if you change the "docker run" from "true" to "top" then the container will be in a running state.
Another option is to just look for a line in the output that is specific to containers and won't be there for images - like "State"

File: integration-cli/docker_cli_inspect_test.go [hunk 7]
```diff
@@ -38,6 +38,95 @@ func (s *DockerSuite) TestInspectInt64(c *check.C) {
...
+		c.Fatal("not a container JSON")
+	}
```
Comment (duglin) [inline integration-cli/docker_cli_inspect_test.go]: as part of this test I think it would be good to add:
- another variant that uses "--type=image" to make sure it doesn't grab the container with the same name
- another variant that doesn't use "--type" at all to make sure it picks up the container

File: integration-cli/docker_cli_inspect_test.go [hunk 8]
```diff
@@ -38,6 +38,95 @@ func (s *DockerSuite) TestInspectInt64(c *check.C) {
...
+
+	inspectCmd := exec.Command(dockerBinary, "inspect", "--type=image", "busybox")
+
+	_, exitCode, err := runCommandWithOutput(inspectCmd)
+	if exitCode != 0 || err != nil {
+		c.Fatalf("failed to inspect image: %s, %v", out, err)
+	}
+}
+
```
Comment (duglin) [inline integration-cli/docker_cli_inspect_test.go]: would be good to add a failing testing to make sure we catch "--type=foo"

File: man/docker-inspect.1.md [hunk 9]
```diff
@@ -24,8 +24,85 @@ each result.
 **-f**, **--format**=""
     Format the output using the given go template.
 
+**--type**=""
+    Return JSON for specified type, permissible values are image or container
```
Comment (duglin) [inline man/docker-inspect.1.md]: wrap "image" and "container" with quotes

File: man/docker-inspect.1.md [hunk 10]
```diff
@@ -24,8 +24,85 @@ each result.
 **-f**, **--format**=""
     Format the output using the given go template.
 
+**--type**=""
```
Comment (duglin) [inline man/docker-inspect.1.md]: perhaps:
```
**--type**=*container*|*image*
```

**Comment by shishir-a412ed** [comment]
@duglin I have made the changes. Let me know if this looks good.

**Comment by shishir-a412ed** [comment]
@duglin @calavera @thaJeztah @jfrazelle Is the jenky error related to this PR ?

**Comment by thaJeztah** [comment]
No, it's not (see https://github.com/docker/docker/issues/13996), I'll restart janky.

**Comment by shishir-a412ed** [comment]
@thaJeztah I usually re-kick jenky myself ... by doing a pseudo commit and force push.
but this one was not going away, so thought I should ask.

Thanks for the information.

**Comment by shishir-a412ed** [comment]
@duglin any updates on this PR ?

**Comment by calavera** [comment]
LGTM

**Comment by duglin** [comment]
@shishir-a412ed sorry for the delay - been a bit busy - will review now...

**Comment by duglin** [comment]
code LGTM but I think there are other docs that might need to modified.  For example, cli.md
Moving to docs review
ping @moxiegirl

**Comment by shishir-a412ed** [comment]
@moxiegirl @duglin any updates on this one ?

File: man/docker-inspect.1.md [hunk 11]
```diff
@@ -24,8 +24,85 @@ each result.
 **-f**, **--format**=""
     Format the output using the given go template.
 
+**--type**=*container*|*image*
+    Return JSON for specified type, permissible values are "image" or "container"
+
 # EXAMPLES
 
+## Getting information on an image where image name conflict with the container name.
```
Comment (moxiegirl) [inline man/docker-inspect.1.md]: Please remove the ## indicating a heading and just leave this as a sentence.

**Comment by moxiegirl** [comment]
@shishir-a412ed Thanks the reminder.  Remove the heading hashes on that sentence and LGTM

File: integration-cli/docker_cli_inspect_test.go [hunk 12]
```diff
@@ -38,6 +38,125 @@ func (s *DockerSuite) TestInspectInt64(c *check.C) {
 	}
 }
 
+func (s *DockerSuite) TestInspectDefault(c *check.C) {
+
+	/*
+		        Both the container and image are named busybox. docker inspect will fetch the container JSON.
```
Comment (thaJeztah) [inline integration-cli/docker_cli_inspect_test.go]: The indentation of this comment (and Some other comments in this PR) looks off / weird. Are you perhaps mixing tabs and spaces?

Also (afaik) we mostly use `//` for these, not `/* ...*/`

(Not really docs related, but I noticed this when reading over the PR)

File: man/docker-inspect.1.md [hunk 13]
```diff
@@ -24,8 +24,85 @@ each result.
...
+## e,g both image and container are named rhel7.
+
+   $ docker inspect --type=image rhel7
+   [
```
Comment (thaJeztah) [inline man/docker-inspect.1.md]: I wonder if we need a full output example in this case to demonstrate this flag, because a full example of the output is already included below and is not the important bit here. I would be okay with "cutting" the output, e.g.

```
[
{
  "Id": "fe01a428b9d9de35d29531e9994157978e8c48fa693e1bf1d221dffbbb67b170",
  "Parent": "10acc31def5d6f249b548e01e8ffbaccfd61af0240c17315a7ad393d022c5ca2"
  ....
```

It also looks like the indentation is not 4 spaces, causing it not to be rendered as a code-block (see https://github.com/shishir-a412ed/docker/blob/docker_inspect_issue/man/docker-inspect.1.md)

File: man/docker-inspect.1.md [hunk 14]
```diff
@@ -24,8 +24,85 @@ each result.
 **-f**, **--format**=""
     Format the output using the given go template.
 
+**--type**=*container*|*image*
```
Comment (thaJeztah) [inline man/docker-inspect.1.md]: This flag also has to be added to the synopsis above; https://github.com/docker/docker/pull/13187/files#diff-49f81c25974e6fe4a56f32e78378faa2R10

File: man/docker-inspect.1.md (hunk 13 above)
Comment (thaJeztah) [inline man/docker-inspect.1.md]: Speaking of that, it looks like the existing output on https://github.com/docker/docker/pull/13187/files#diff-49f81c25974e6fe4a56f32e78378faa2R111 also isn't indented with 4 spaces, causing it to not show as code.

That should probably go in a separate PR, but it would be awesome if your could fix that while working on this document :-)

**Comment by thaJeztah** [comment]
Thanks @shishir-a412ed ! Added some comments inline.

Also, this needs documentation in the online reference as well; https://github.com/docker/docker/blob/master/docs/reference/commandline/inspect.md

**Comment by shishir-a412ed** [comment]
@moxiegirl @thaJeztah I have made the changes. 
Let me know if I missed anything.

File: man/docker-inspect.1.md [hunk 15]
```diff
@@ -24,14 +25,29 @@ each result.
...
+    Return JSON for specified type, permissible values are "image" or "container"
+
 # EXAMPLES
 
+Getting information on an image where image name conflict with the container name.
+e,g both image and container are named rhel7.
```
Comment (thaJeztah) [inline man/docker-inspect.1.md]: Really minor; some dots/comma's are incorrect here. *But I'm okay with leaving that for someone else to fix.*

Think it should be;
```Markdown
Getting information on an image where image name conflict with the container name, 
e.g., both image and container are named rhel7.
```

File: man/docker-inspect.1.md [hunk 16]
```diff
@@ -24,14 +25,29 @@ each result.
...
+    }
+    ]
+
 ## Getting information on a container
 
 To get information on a container use its ID or instance name:
 
     $ docker inspect d2cc496561d6
-[{
+    [{
```
Comment (thaJeztah) [inline man/docker-inspect.1.md]: Thanks for fixing these!

**Comment by thaJeztah** [comment]
LGTM, thanks for being patient, @shishir-a412ed, I know it took a while! 

ping @moxiegirl

File: man/docker-inspect.1.md (hunk 15 above)
Comment (shishir-a412ed) [inline man/docker-inspect.1.md]: Fixed.

**Comment by thaJeztah** [comment]
Kicked experimental build, ready to merge if that passes

**Comment by shishir-a412ed** [comment]
@thaJeztah Sounds good !

**Comment by thaJeztah** [comment]
\o/ merged!

**Comment by rhatdan** [comment]
Woo Hoo
