### PR TITLE
Fix lease management during pull and export

### LINKED ISSUE #48909: Containerd snapshotter saves layers that can't be cleared easily
### Description

I have the following enabled on my machine for docker:

  "features": {
    "containerd-snapshotter": true
  }

If I do a pull and cancel it part way through it will save the layers.
If I never complete this pull the data will persist under /contianerd/io.containerd.snapshotter.v1.overlayfs and /containerd/io.containerd.content.v1.content
Running commands like docker system prune -a or docker image prune -a do not work for removing this data and there doesn't seem to be any way to manually trigger garbage collection of these files.
Additionally I tried to see if I could find anything related to these files through ctr images, ctr leases, and ctr snapshots with no luck.

Was told this is the best place for this bug here:
https://github.com/containerd/containerd/issues/10548
https://github.com/docker/cli/issues/5315

### Reproduce

1. Enable snapshotter for docker with code block from description.
2. Note reported usage of docker images with docker system df
3. docker pull <any_image>
4. Cancel the pull before it completes, but after some layers have been pulled and extracted.
5. Confirm with docker system df (or du) that the usage has increased.
6. Confirm new data is unable to be removed through normal commands (or even through gc over time)

### Expected behavior

Have some way of clearing this data without running an rm command on the directory.
Either through ctr or docker; or if garbage collection cleans it up then a way to manually force that data to be removed.

### docker version

```bash
Client: Docker Engine - Community
Version:           27.1.1
API version:       1.46
Go version:        go1.21.12
Git commit:        6312585
Built:             Tue Jul 23 19:57:01 2024
OS/Arch:           linux/amd64
Context:           default

Server: Docker Engine - Community
Engine:
 Version:          27.1.1
 API version:      1.46 (minimum version 1.24)
 Go version:       go1.21.12
 Git commit:       cc13f95
 Built:            Tue Jul 23 19:57:01 2024
 OS/Arch:          linux/amd64
 Experimental:     true
containerd:
 Version:          1.7.19
 GitCommit:        2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
runc:
 Version:          1.7.19
 GitCommit:        v1.1.13-0-g58aa920
docker-init:
 Version:          0.19.0
 GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    27.1.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 27.1.1
 Storage Driver: overlayfs
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.5.0-44-generic
 Operating System: Ubuntu 22.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 20
 Total Memory: 62.46GiB
 Name:
 ID: 797409c4-1056-4a1f-946d-93f3a7004068
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: true
 Insecure Registries:
  localhost:5000
 Live Restore Enabled: false
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by dmcgowan**
Ensure that leases have a reasonable expiration and are cleaned up during prune

Currently it seems some leases could be leaked as they were created with no expiration and their removal could fail due to using a canceled context.

- Fixes #48909

**- Description for the changelog**

```markdown changelog
containerd image-store: fix partially pulled images not being garbage-collected [moby#48910](https://github.com/moby/moby/pull/48910)
```

### CODE REVIEW

File: daemon/containerd/image_prune.go [hunk 1]
```diff
@@ -60,6 +61,22 @@ func (i *ImageService) ImagesPrune(ctx context.Context, fltrs filters.Args) (*im
...
+	}
+	for i, lease := range pullLeases {
+		opts := []leases.DeleteOpt{}
+		if i == len(pullLeases)-1 {
+			opts = append(opts, leases.SynchronousDelete)
+		}
+		if err := leaseManager.Delete(ctx, lease, opts...); err != nil {
+			return nil, err
+		}
+	}
```
Comment (vvoland) [inline daemon/containerd/image_prune.go:78]: For a follow up - not sure how feasible that is, but it would be nice if we'd be able to determine how much disk space was freed.

**Review by vvoland — APPROVED** [review]
LGTM, thanks!

File: daemon/containerd/image_pull.go [hunk 2]
```diff
@@ -40,6 +40,27 @@ func (i *ImageService) PullImage(ctx context.Context, baseRef reference.Named, p
 	}()
 	out := streamformatter.NewJSONProgressOutput(outStream, false)
 
+	// How long downloaded content will be held after cancellation
+	expireAt := time.Now().Add(8 * time.Hour)
+	ctx, done, err := i.client.WithLease(ctx,
+		leases.WithRandomID(),
+		leases.WithLabels(map[string]string{
+			"moby/action.pull":        baseRef.String(),
```
Comment (thaJeztah) [inline daemon/containerd/image_pull.go:48]: Should we have a `const` for this one? (currently only used in two places, but not sure if we (should) / will be using the same label in other locations? Do we know if BuildKit also sets such labels, and if these are things we should align?

File: daemon/containerd/image_pull.go [hunk 3]
```diff
@@ -40,6 +40,27 @@ func (i *ImageService) PullImage(ctx context.Context, baseRef reference.Named, p
...
+			"containerd.io/gc.expire": expireAt.Format(time.RFC3339),
```
Comment (thaJeztah) [inline daemon/containerd/image_pull.go:49]: Hm... I was surprised that these were not exported as either a `const` or as a utility in containerd; should they be? https://github.com/moby/moby/blob/803534fb4e784d3e6bef9846d64ce4960ad1ec80/vendor/github.com/containerd/containerd/metadata/gc.go#L60-L65

I see containerd v2 added some extra documentation to some of these to outline the required format for values set; https://github.com/containerd/containerd/blob/f0ebbd3c8a662656b458e7e1cca059a690d557a7/core/metadata/gc.go#L69-L76

```go
	// labelGCExpire indicates that an object is collectible after the
	// provided time. For image objects, this makes them available to
	// garbage collect when expired, when not provided, image objects
	// are root objects that never expire. For non-root objects such
	// as content or snapshots, these objects will be treated like
	// root objects before their expiration.
	// Expected format is RFC 3339
	labelGCExpire = []byte("containerd.io/gc.expire")
```


So maybe a utility could make most sense;

- `leases.WithGCExpireAt(time.Time)` (or something) to make sure it's in the correct format
- Some of the other ones may require a specific format as well, so _perhaps_ could require a utility as well to validate (instead of a plain `const` for the right label)?

**Review by thaJeztah — APPROVED** [review]
overall LGTM

left some comments; nothing _really_ blocking (I think), but possibly some for follow-ups. The timeout is the one I'm wondering if we should shorten as part of this PR (but open to input).

File: daemon/containerd/image_exporter.go [hunk 4]
```diff
@@ -68,19 +68,18 @@ func (i *ImageService) ExportImage(ctx context.Context, names []string, platform
...
 
-	leasesManager := i.client.LeasesService()
-	lease, err := leasesManager.Create(ctx, leases.WithRandomID())
+	ctx, done, err := i.client.WithLease(ctx)
 	if err != nil {
 		return errdefs.System(err)
 	}
 	defer func() {
-		if err := leasesManager.Delete(ctx, lease); err != nil {
+		if err := done(context.WithoutCancel(ctx)); err != nil {
```
[the remark this answers is not in the document]
Comment (dmcgowan) [reply daemon/containerd/image_exporter.go:76]: In the export case there really isn't a need to hold onto anything since even if the operation is canceled, it will need to restart from the beginning on retry. For the pull case, a cancel may want to keep progress so the context error could be respected. We could make this more explicit and check for a context error rather than let the function error from it.

File: daemon/containerd/image_pull.go (hunk 3 above)
Comment (dmcgowan) [reply daemon/containerd/image_pull.go:49]: There is a utility, here it is just to be specific. There is no logic around it though and the format doesn't change, seemed cleaner to just clearly see the labels that are getting set.

File: daemon/containerd/image_pull.go [hunk 5]
```diff
@@ -40,6 +40,27 @@ func (i *ImageService) PullImage(ctx context.Context, baseRef reference.Named, p
 	}()
 	out := streamformatter.NewJSONProgressOutput(outStream, false)
 
+	// How long downloaded content will be held after cancellation
+	expireAt := time.Now().Add(8 * time.Hour)
```
[the remark this answers is not in the document]
Comment (dmcgowan) [reply daemon/containerd/image_pull.go:44]: It should for partial downloads of the blobs. Any partially unpacked snapshotters should be discarded as I believe we always use a unique identifier for unpack.

I'm adding a const. We can make this configurable as well in the future if we want and make a smaller value. With it static, it really has to cover the upper bound of possible pull times.

File: daemon/containerd/image_pull.go (hunk 3 above)
Comment (thaJeztah) [reply daemon/containerd/image_pull.go:51]: Oh, I see there's indeed a `WithExpiration`; https://github.com/moby/moby/blob/113d3cecea2c0a6181c34489888a8a89de4e1961/vendor/github.com/containerd/containerd/leases/lease.go#L81-L91


Yeah, mostly looking that using a consistent approach may help finding related things. In this case, I just checked where we're setting these, and I found these;

```bash
git grep '\.WithExpiration' -- ':!vendor'
builder/builder-next/adapters/containerimage/pull.go:   ctx, done, err := leaseutil.WithLease(ctx, p.is.LeaseManager, leases.WithExpiration(5*time.Minute), leaseutil.MakeTemporary)
daemon/containerd/image_builder.go:     ctx, _, err := i.client.WithLease(ctx, leases.WithRandomID(), leases.WithExpiration(1*time.Hour))
daemon/containerd/image_builder.go:             leases.WithExpiration(time.Hour*24),
daemon/containerd/image_builder.go:     ctx, release, err := i.client.WithLease(ctx, leases.WithRandomID(), leases.WithExpiration(1*time.Hour))
daemon/containerd/image_commit.go:      ctx, release, err := i.client.WithLease(ctx, leases.WithRandomID(), leases.WithExpiration(1*time.Hour))
daemon/images/image_pull.go:            leases.WithExpiration(24 * time.Hour),
```

Interestingly it looks like for non-containerd image-pulls, we still use 24 hours, but a different label; https://github.com/moby/moby/blob/113d3cecea2c0a6181c34489888a8a89de4e1961/daemon/images/image_pull.go#L118-L125

And for classic builder with containerd as well, and again with a different label; https://github.com/moby/moby/blob/113d3cecea2c0a6181c34489888a8a89de4e1961/daemon/containerd/image_builder.go#L235-L241


Perhaps those should be corrected as well?

Comment (dmcgowan) [reply daemon/containerd/image_pull.go]: I'm not going to touch the ones outside of daemon/containerd for now, those might be worth looking but not related to the issues we are seeing with the containerd integration. I added a `withLease` method to our own image service that will add the labels and logic that is consistent with pruning.

**Comment by dmcgowan** [comment]
Looks unrelated, can someone kick the re-run?
```
=== Failed
=== FAIL: github.com/docker/docker/integration/networking TestPortMappedHairpinWindows (12.48s)
    nat_windows_test.go:108: assertion failed: error is not nil: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.48/containers/7a294dab5fdc253f624b2e5202567ade53acdda4394217cb4fd71888e0994404/start": context deadline exceeded
    panic.go:629: assertion failed: error is not nil: Error response from daemon: error while removing network: network clientnet id 1afe2b3927c272b4aea4d92b6b95345f031e76ad126f8651a6af134f10da0483 has active endpoints

DONE 14 tests, 9 skipped, 1 failure in 33.137s
```

File: daemon/containerd/leases.go [hunk 6]
```diff
@@ -0,0 +1,51 @@
...
+			pruneLeaseLabel: "true",
+			expireLabel:     expireAt.Format(time.RFC3339),
+		}))
+	if err != nil {
+		return ctx, func() {}, err
+	}
+
+	ctx = leases.WithLease(ctx, l.ID)
+	return ctx, func() {
+		if ctx.Err() != nil {
```
Comment (cpuguy83) [inline daemon/containerd/leases.go:39]: This seems racey.  Seems like we should always use `context.WithoutCancel` regardless of if the context is cancelled.

File: daemon/containerd/leases.go [hunk 7]
```diff
@@ -0,0 +1,51 @@
...
+)
+
+const (
+	leaseExpireDuration = 8 * time.Hour
+	expireLabel         = "containerd.io/gc.expire" // Copied from containerd
+	pruneLeaseLabel     = "moby/prune.images"
+	pruneLeaseFilter    = `labels."moby/prune.images"`
+)
+
+func (i *ImageService) withLease(ctx context.Context, cancellable bool) (context.Context, func(), error) {
```
Comment (cpuguy83) [inline daemon/containerd/leases.go:18]: Can you help me understand the reason one would set `cancellable` to true?

**Review by cpuguy83 — CHANGES_REQUESTED** [review]

File: daemon/containerd/leases.go (hunk 7 above)
Comment (dmcgowan) [reply daemon/containerd/leases.go:18]: Resumable pull

File: daemon/containerd/leases.go (hunk 6 above)
Comment (dmcgowan) [reply daemon/containerd/leases.go]: Updated

**Review by cpuguy83 — APPROVED** [review]

**Comment by vvoland** [comment]
```
    build_userns_linux_test.go:132: run produced invalid output: "", expected "/bin/sleep cap_net_bind_service=eip"
--- FAIL: TestBuildUserNamespaceValidateCapabilitiesAreV2 (15.97s)
```

Looks like this test became flaky recently 🤔

**Comment by thaJeztah** [comment]
@vvoland yeah, I think it's one of the tests that became flaky related to the runc 1.2 updates, and there were some remaining patches that didn't get merged (not sure if all of them were good though); https://github.com/moby/moby/pull/48160#issuecomment-2237801422

**Comment by thaJeztah** [comment]
- opened https://github.com/moby/moby/pull/48940 to apply some of those patches that weren't merged

File: daemon/containerd/image_pull.go [hunk 8]
```diff
@@ -89,14 +94,7 @@ func (i *ImageService) pullTag(ctx context.Context, ref reference.Named, platfor
 	var outNewImg containerd.Image
 
 	if oldImage.Target.Digest != "" {
-		// Lease the old image content to prevent it from being garbage collected until we keep it as dangling image.
```
[the remark this answers is not in the document]
Comment (dmcgowan) [reply daemon/containerd/image_pull.go:92]: I could add a comment to the `withLease` function, but that is the whole point of the lease, it seems redundant to describe what a lease is everywhere it is used.

[the remark this answers is not in the document]
Comment (thaJeztah) [reply daemon/containerd/image_pull.go:92]: Yeah, this one felt like it added additional context to why we're holding on to the _old_ image (which may not be immediately obvious).

**Review by thaJeztah — APPROVED** [review]
LGTM
