### PR TITLE
Rootless setup: check for module nf_tables

### LINKED ISSUE #49020: RHEL/CentOS Stream 10 does not include the iptables kernel module
### Description

iptables is deprecated in RHEL 9, and the iptables kernel module not included in RHEL 10: https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/9.0_release_notes/deprecated_functionality#deprecated-functionality_networking

When setting up rootless Docker, it is necessary to use ` --skip-iptables` with `dockerd-rootless-setuptool.sh`.

### Reproduce

1. Install Docker Engine CE on EL 10 using the binary download
2. Run `dockerd-rootless-setuptool.sh install`
3. Observe Docker warning and instructions about missing iptables

```
[ERROR] Missing system requirements. Run the following commands to
[ERROR] install the requirements and run this tool again.
[ERROR] Alternatively iptables checks can be disabled with --skip-iptables .

########## BEGIN ##########
sudo sh -eux <<EOF
# Load ip_tables module
modprobe ip_tables
EOF
########## END ##########
```

### Expected behavior

_No response_

### docker version

```bash
Client:
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:39:44 2024
 OS/Arch:           linux/amd64
 Context:           rootless
Cannot connect to the Docker daemon at unix:///run/user/1000/docker.sock. Is the docker daemon running?
```

### docker info

```bash
Client:
 Version:    27.3.1
 Context:    rootless
 Debug Mode: false

Server:
ERROR: Cannot connect to the Docker daemon at unix:///run/user/1000/docker.sock. Is the docker daemon running?
errors pretty printing info
```

### Additional Info

```bash
$ cat /etc/os-release | grep platform
PLATFORM_ID="platform:el10"
```

```bash
$ dnf list installed | grep iptables
iptables-libs.x86_64                                 1.8.10-8.el10                         @System 
iptables-nft.x86_64                                  1.8.10-8.el10                         @System 
iptables-services.noarch                             1.8.10-8.el10                         @System 
iptables-utils.x86_64                                1.8.10-8.el10                         @System
```

### PR DESCRIPTION
**Pull request by robmry**
**- What I did**

- fix https://github.com/moby/moby/issues/49020

CentOS 10 uses `iptables-nft` by default, and doesn't have kernel module ip_tables - so `dockerd-rootless-setuptool.sh` reports that the module is missing. It suggests installing it (which isn't needed), or using `--skip-iptables` (which disables iptables in daemon config).

**- How I did it**

Unless the `iptables --version` command reports `legacy`, check for kernel module `nf_tables` instead of `ip_tables`.

**- How to verify it**

Ran the install script on a CentOS Stream 10 VM, it worked normally with these changes.

(Not tested on RHEL10 as I don't have a license.)

On a Debian host, where I could switch between `iptables-nft` and `iptables-legacy` - with kernel module `ip_tables` unloaded ("rlk_setup.sh" was my modified version of the script) ...

```
robm@debian:~$ /usr/sbin/iptables --version
iptables v1.8.9 (legacy)
robm@debian:~$ ./rlk_setup.sh install
[ERROR] Missing system requirements. Run the following commands to
[ERROR] install the requirements and run this tool again.
[ERROR] Alternatively iptables checks can be disabled with --skip-iptables .

########## BEGIN ##########
sudo sh -eux <<EOF
# Load ip_tables module
modprobe ip_tables
EOF
########## END ##########
```

Switched to iptables-nft, with `ip_tables` still not loaded, then ...
```
robm@debian:~$ /usr/sbin/iptables --version
iptables v1.8.9 (nf_tables)
robm@debian:~$ ./rlk_setup.sh install
[INFO] Creating /home/robm/.config/systemd/user/docker.service
[INFO] starting systemd service docker.service
...
```

**- Human readable description for the release notes**

```markdown changelog
- Fix an issue preventing rootless Docker setup on a host with no `ip_tables` kernel module.
```

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]

File: contrib/dockerd-rootless-setuptool.sh [hunk 1]
```diff
@@ -143,7 +143,11 @@ init() {
 
 	# instruction: iptables dependency check
 	faced_iptables_error=""
-	if ! command -v iptables > /dev/null 2>&1 && [ ! -f /sbin/iptables ] && [ ! -f /usr/sbin/iptables ]; then
+	iptables_command=$(PATH=$PATH:/sbin:/usr/sbin command -v iptables 2> /dev/null) || :
+	iptables_version=""
+	if [ -n "$iptables_command" ]; then
+		iptables_version=$($iptables_command --version 2> /dev/null) || :
```
Comment (thaJeztah) [inline contrib/dockerd-rootless-setuptool.sh:149]: Actually; so `iptables_version` is only used to set `iptables_module`, correct? In that case, we could just put all here? Or won't that work?

```suggestion
	# Many OSs now use iptables-nft by default so, check for module nf_tables by default. But,
	# if "iptables --version" worked and reported "legacy", check for module ip_tables instead.
	iptables_module="nf_tables"
	iptables_command=$(PATH=$PATH:/sbin:/usr/sbin command -v iptables 2> /dev/null) || :
	if [ -n "$iptables_command" ]; then
		iptables_version=$($iptables_command --version 2> /dev/null) || :
		case $iptables_version in
			*legacy*) iptables_module="ip_tables" ;;
		esac
```

Comment (robmry) [reply contrib/dockerd-rootless-setuptool.sh:149]: The first block (`instruction: iptables dependency check`) is working out whether there's an `iptables` command, and the second block (`instruction: ip_tables module dependency check`) works out whether the kernel module is loaded.

So, I thought it was best for the second block to use the command the first block found - rather than finding the command again, but maybe a bit differently.

If that makes sense (?) ... I'll swap the grep for case, as you suggest above.

File: contrib/dockerd-rootless-setuptool.sh [hunk 2]
```diff
@@ -178,14 +182,20 @@ init() {
 	fi
 
 	# instruction: ip_tables module dependency check
-	if ! grep -q ip_tables /proc/modules 2> /dev/null && ! grep -q ip_tables /lib/modules/$(uname -r)/modules.builtin 2> /dev/null; then
+	# Many OSs now use iptables-nft by default so, check for module nf_tables by default. But,
+	# if "iptables --version" worked and reported "legacy", check for module ip_tables instead.
+	iptables_module="nf_tables"
+	if [ -n "$(echo $iptables_version | grep "legacy" 2> /dev/null)" ]; then
+		iptables_module="ip_tables"
+	fi
```
[the remark this answers is not in the document]
Comment (robmry) [reply contrib/dockerd-rootless-setuptool.sh]: Done - thank you.

File: contrib/dockerd-rootless-setuptool.sh (hunk 1 above)
Comment (robmry) [reply contrib/dockerd-rootless-setuptool.sh:149]: I've taken option 1 ... can update again if needed!

File: contrib/dockerd-rootless-setuptool.sh (hunk 2 above)
[the remark this answers is not in the document]
Comment (robmry) [reply contrib/dockerd-rootless-setuptool.sh]: Un-done - now it's option 2!

File: contrib/dockerd-rootless-setuptool.sh (hunk 1 above)
Comment (robmry) [reply contrib/dockerd-rootless-setuptool.sh]: Sorry - misread, this is the first block ... done now.

**Review by tianon — APPROVED** [review]
Seems fine to me :+1:

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

File: contrib/dockerd-rootless-setuptool.sh (hunk 2 above)
[the remark this answers is not in the document]
Comment (thaJeztah) [reply contrib/dockerd-rootless-setuptool.sh]: Thanks! Yes, I wrote one, then wrote the other comment, it was possibly a bit confusing; we got there in the end ❤️

File: contrib/dockerd-rootless-setuptool.sh [hunk 3]
```diff
@@ -143,7 +143,15 @@ init() {
...
+	# Many OSs now use iptables-nft by default so, check for module nf_tables by default. But,
+	# if "iptables --version" worked and reported "legacy", check for module ip_tables instead.
+	iptables_module="nf_tables"
+	iptables_command=$(PATH=$PATH:/sbin:/usr/sbin command -v iptables 2> /dev/null) || :
+	if [ -n "$iptables_command" ]; then
+		iptables_version=$($iptables_command --version 2> /dev/null) || :
+		case $iptables_version in
+			*legacy*) iptables_module="ip_tables" ;;
+		esac
 		faced_iptables_error=1
```
Comment (vvoland) [inline contrib/dockerd-rootless-setuptool.sh:155]: This sets `faced_iptables_error=1` even when iptables are available

Comment (vvoland) [reply contrib/dockerd-rootless-setuptool.sh:155]:
```
$ iptables --version
iptables v1.8.10 (nf_tables)
```

```
$ curl https://get.docker.com/rootless | sh -
[ERROR] Missing system requirements. Run the following commands to
[ERROR] install the requirements and run this tool again.
[ERROR] Alternatively iptables checks can be disabled with --skip-iptables .
```

Comment (vvoland) [reply contrib/dockerd-rootless-setuptool.sh:155]: cc @robmry
