### PR TITLE
c8d/legacybuilder: Assorted fixes 

### LINKED ISSUE #46194: containerd integration: Subsequent `COPY` instructions causes error on the first build attempt
### Description

When Dockerfile contains more than one `COPY` instruction it fails to build on the first try.
Only happens with legacy builder with containerd integration enabled.

### Reproduce

Dockerfile:
```Dockerfile
FROM busybox
COPY foo /foo
COPY baz /bar/quux/baz
```

```bash
$ echo world>foo
$ echo hello>baz
$ DOCKER_BUILDKIT=0 docker build .
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            BuildKit is currently disabled; enable it by removing the DOCKER_BUILDKIT=0
            environment-variable.

Sending build context to Docker daemon  4.096kB
Step 1/3 : FROM busybox
3fbc63216742: Download complete
1fa89c01cd04: Download complete
fc9db2894f4e: Download complete
8a0af25e8c2e: Download complete
 ---> 3fbc63216742
Step 2/3 : COPY foo /foo
 ---> 67cfe2ee6818
Step 3/3 : COPY baz /bar/quux/baz
failed to prepare snapshot: parent snapshot sha256:194b19e7685f7fcdd0d248fe7a8aa0e992c2e87b604cf4817bf3ce34a1521cff does not exist: not found
```

Now, try for the second time:
```bash
$ DOCKER_BUILDKIT=0 docker build .
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            BuildKit is currently disabled; enable it by removing the DOCKER_BUILDKIT=0
            environment-variable.

Sending build context to Docker daemon  4.096kB
Step 1/3 : FROM busybox
 ---> 3fbc63216742
Step 2/3 : COPY foo /foo
 ---> Using cache
 ---> 67cfe2ee6818
Step 3/3 : COPY baz /bar/quux/baz
 ---> 2d2ac2987f47
Successfully built 2d2ac2987f47
```

### Expected behavior

Image should be built on the first attempt.

### docker version

```bash
master @ e0da5cb9291982a4c7b3c6b0642eeced4ba9f8ac
```

### docker info

```bash
-
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by vvoland**
- Requires: https://github.com/moby/moby/pull/46313

- Closes: https://github.com/moby/moby/issues/46194

**- What I did**
- Fixed `failed to prepare snapshot: parent snapshot <digest> does not exist: not found` error
- Removed unused mount of the rolayer snapshot
- Fixed `mismatched image rootfs and manifest layers` when producing a new image with an empty diff (empty layer was added to the manifest when it was intentionally not being added in the config)
- Replaced 1 hour leases with actual leases that are deleted when `Release` is called on ro/rw layer

**- How I did it**
- See commits

**- How to verify it**
Integrations tests with c8d enabled

```diff
 === FAIL: amd64.integration-cli TestDockerCLIBuildSuite (308.65s)

- DONE 250 tests, 13 skipped, 41 failures in 314.721s
+ DONE 250 tests, 13 skipped, 20 failures in 310.432s
```

**- Description for the changelog**
```release-notes
- containerd-integration: Fix legacy builder build errors when multiple COPY/ADD instructions are used
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: daemon/containerd/image_builder.go [hunk 1]
```diff
@@ -268,27 +316,45 @@ type rwlayer struct {
...
+	lease, err := leaseSnapshot(ctx, lm, rw.snapshotter, key)
+	if err != nil {
+		return nil, err
+	}
+
 	err = snapshotter.Commit(ctx, key, rw.key)
 	if err != nil && !cerrdefs.IsAlreadyExists(err) {
 		return nil, err
 	}
+	defer func() {
```
Comment (rumpl) [inline daemon/containerd/image_builder.go:344]: Why didn't you stick with the `client.WithLease` that returns a cleanup function? Also I think you can only remove the lease and the snapshot will be GC'd automatically for you

Comment (vvoland) [reply daemon/containerd/image_builder.go:344]: Ah, right, removed the manual snapshot removal (which would be incorrect and cause used snapshot by other layer to be removed if the snapshot already exists, but later operation fails).

There are 2 separate leases created here:
1. Long lived (created by `leaseSnapshot`) that's removed in the `Release`.
2. Short lived - this one is only to hold the content created by `rootfs.CreateDiff` and released when this function exits and the resource is attached to the long lived lease.

The reason for having them both is because sometimes the content was GC'd before the `lm.AddResource` got called (which I believe was the reason to have the fixed 1h leases in the initial implementation). And we can't add the lease upfront like with the snapshot, because we don't know what digest the diff archive will have.

File: daemon/containerd/image_commit.go [hunk 2]
```diff
@@ -117,7 +117,19 @@ func (i *ImageService) CommitImage(ctx context.Context, cc backend.CommitConfig)
...
+
+	c8dImg, err := i.NewImageManifest(ctx, img, commitManifestDesc)
+	if err != nil {
+		return id, err
+	}
+	if err := c8dImg.Unpack(ctx, container.Driver); err != nil {
+		if !cerrdefs.IsAlreadyExists(err) {
+			return id, fmt.Errorf("failed to unpack image: %w", err)
+		}
+	}
```
[the remark this answers is not in the document]
Comment (vvoland) [reply daemon/containerd/image_commit.go]: We're committing a running container into an image which is a copy of the base image with an additional layer (archive of the container's RW layer).

We can't reuse the snapshot because the unpacked snapshot we have here is an RW layer (active snapshot) of the container (with the ID of the container), and for the image we need to have a non-RW (committed snapshot) with the ID matching the ChainID of the new image (BaseImageChainID | NewLayerDiffID).

I don't think we can avoid this, as we can't just `Commit` the RW layer snapshot into a new snapshot, because that would delete  it.
I don't think that's a problem though, as we don't really unpack all the image layers (because their snapshots already exists as the base image of the container had to be unpacked), just the last layer we just created from the container diff.

File: daemon/containerd/image_builder.go [hunk 3]
```diff
@@ -200,7 +200,7 @@ func newROLayerForImage(ctx context.Context, imgDesc *ocispec.Descriptor, i *Ima
 		key:                key,
 		c:                  i.client,
 		snapshotter:        i.snapshotter,
-		diffID:             digest.Digest(parent),
+		diffID:             "",
 		contentStoreDigest: "",
```
[the remark this answers is not in the document]
Comment (vvoland) [reply daemon/containerd/image_builder.go]: I explicitly kept it, because that's the desired value due to the nature of the read-only layer. It also stops you from wondering in the future if this was omitted on purpose or by accident 😄

File: daemon/containerd/image_builder.go [hunk 4]
```diff
@@ -193,11 +193,10 @@ func newROLayerForImage(ctx context.Context, imgDesc *ocispec.Descriptor, i *Ima
 		return nil, err
 	}
 
-	key := stringid.GenerateRandomID()
-	parent := identity.ChainID(diffIDs).String()
+	imageSnapshotID := identity.ChainID(diffIDs).String()
```
[the remark this answers is not in the document]
Comment (vvoland) [reply daemon/containerd/image_builder.go:198]: Ah yes, I wanted to refactor this also, but didn't want to add any more commits to this PR. I'd leave this for a follow up.

File: daemon/containerd/image_builder.go (hunk 1 above)
Comment (vvoland) [reply daemon/containerd/image_builder.go:337]: That's true, fixed.

File: daemon/containerd/image_commit.go [hunk 5]
```diff
@@ -117,16 +117,10 @@ func (i *ImageService) CommitImage(ctx context.Context, cc backend.CommitConfig)
...
-	if err != nil {
-		return id, err
-	}
-	if err := c8dImg.Unpack(ctx, container.Driver); err != nil {
-		if !cerrdefs.IsAlreadyExists(err) {
-			return id, fmt.Errorf("failed to unpack image: %w", err)
-		}
+	id := image.ID(img.Target.Digest)
+	if err := i.unpackImage(ctx, container.Driver, img, commitManifestDesc); err != nil {
+		return id, fmt.Errorf("failed to unpack image: %w", err)
```
[the remark this answers is not in the document]
Comment (vvoland) [reply daemon/containerd/image_commit.go]: Swapped the commits. I prefer them separate to not mix refactor (having a common `unpackImage` implementation) with the behavior change (adding unpack to commit).

File: daemon/containerd/image_commit.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (thaJeztah) [reply daemon/containerd/image_commit.go:130]: > We can't reuse the snapshot because the unpacked snapshot we have here is an RW layer

Oh, good point yes, forgot about that for a minute.

File: daemon/containerd/image_builder.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (thaJeztah) [reply daemon/containerd/image_builder.go:198]: Yes, that's fine; it was mostly me looking "why are we reading (and unmarshaling) that config _again_ ?", so I thought I'd ask (perhaps there was a good reason we couldn't reuse the existing `img` var, or it was not a fully "hydrated" struct).

File: daemon/containerd/image_commit.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (thaJeztah) [reply daemon/containerd/image_commit.go]: Thanks! Yes, separate commits makes sense (I just noticed we were adding new code, and directly replacing it, so swapping makes sense 👍)

**Review by rumpl — APPROVED** [review]

File: daemon/containerd/image_builder.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (thaJeztah) [reply daemon/containerd/image_builder.go]: Gotcha! Should we leave a `// comment` after both of them to document that? ("must be empty, because ...") ? Without a comment, I can see myself (or others) removing those lines some day in the future.

File: daemon/containerd/image_builder.go [hunk 6]
```diff
@@ -193,23 +192,55 @@ func newROLayerForImage(ctx context.Context, imgDesc *ocispec.Descriptor, i *Ima
...
 	}, nil
 }
 
+func leaseSnapshot(ctx context.Context, lm leases.Manager, snapshotter string, snapshotID string) (leases.Lease, error) {
+	if snapshotID == "" {
+		return leases.Lease{}, nil
+	}
+
+	id := "legacybuilder_" + stringid.GenerateRandomID()
+	lease, err := lm.Create(ctx, leases.WithID(id), leases.WithExpiration(time.Hour*24))
```
[the remark this answers is not in the document]
Comment (vvoland) [reply daemon/containerd/image_builder.go:222]: I chose name prefix thinking it would be more discoverable when looking at `ctr leases list`, but I see that it also shows labels:

```bash
$ ctr leases ls
ID                                                               CREATED AT           LABELS
bc32e760dbfdd3d6c00f153f362f2695a1514154f5f03ec10a53b8915764171e 2023-09-07T07:33:10Z -
```

So using a label here would also be fine.

File: daemon/containerd/image_import.go [hunk 7]
```diff
@@ -313,18 +314,20 @@ func (i *ImageService) saveImage(ctx context.Context, img images.Image) error {
 	return nil
 }
 
-// unpackImage unpacks the image into the snapshotter.
-func (i *ImageService) unpackImage(ctx context.Context, img images.Image, platform ocispec.Platform) error {
-	c8dImg := containerd.NewImageWithPlatform(i.client, img, platforms.Only(platform))
-	unpacked, err := c8dImg.IsUnpacked(ctx, i.snapshotter)
+// unpackImage unpacks the platform specific manifest of a image into the snapshotter.
```
[the remark this answers is not in the document]
Comment (vvoland) [reply daemon/containerd/image_import.go]: Done.

File: daemon/containerd/image_commit.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (vvoland) [reply daemon/containerd/image_commit.go]: Changed, although I'm not really a fan of increasing line density 😄

File: daemon/containerd/image_builder.go [hunk 8]
```diff
@@ -193,23 +192,55 @@ func newROLayerForImage(ctx context.Context, imgDesc *ocispec.Descriptor, i *Ima
...
+	}
+
+	r := leases.Resource{
+		ID:   snapshotID,
+		Type: "snapshots/" + snapshotter,
+	}
+
+	if err := lm.AddResource(ctx, lease, r); err != nil {
+		return leases.Lease{}, fmt.Errorf("failed to add snapshot resource %s to lease %s: %w", snapshotID, lease.ID, err)
+	}
```
[the remark this answers is not in the document]
Comment (vvoland) [reply daemon/containerd/image_builder.go]: Done

File: daemon/containerd/image_builder.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (vvoland) [reply daemon/containerd/image_builder.go]: Changed to label.

File: daemon/containerd/image_builder.go [hunk 9]
```diff
@@ -224,22 +255,36 @@ func (rl *rolayer) DiffID() layer.DiffID {
 }
 
 func (rl *rolayer) Release() error {
+	if rl.lease.ID != "" {
```
[the remark this answers is not in the document]
Comment (vvoland) [reply daemon/containerd/image_builder.go]: Changed to pointer.

File: daemon/containerd/image_commit.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (thaJeztah) [reply daemon/containerd/image_commit.go]: Yeah, also get where you're coming from. My thinking here is that there's two fairly common scenarios;

"conditionally return error"

For example;

```go
if _, err = f.Readdirnames(1); err == io.EOF {
	return nil
}
```

"always return, but ignore specific errors"

```go
foo, err := someThing()
if err != nil {
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	return err
}
```

I think in most cases we only break up the "if" for the second one, and the first one to be treated more of a single check (check the error type, if any)

File: daemon/containerd/image_commit.go [hunk 10]
```diff
@@ -117,7 +117,17 @@ func (i *ImageService) CommitImage(ctx context.Context, cc backend.CommitConfig)
...
 	}
-	return image.ID(img.Target.Digest), nil
+	id := image.ID(img.Target.Digest)
+
+	c8dImg, err := i.NewImageManifest(ctx, img, commitManifestDesc)
+	if err != nil {
+		return id, err
+	}
+	if err := c8dImg.Unpack(ctx, container.Driver); err != nil && !cerrdefs.IsAlreadyExists(err) {
+		return id, fmt.Errorf("failed to unpack image: %w", err)
```
Comment (thaJeztah) [inline daemon/containerd/image_commit.go:127]: not a blocker, but just noticing this; should we return an empty `id` in both of these cases? (as we're now returning an `id` _AND_ and `error`)?

File: daemon/containerd/image_builder.go [hunk 11]
```diff
@@ -192,23 +191,59 @@ func newROLayerForImage(ctx context.Context, imgDesc *ocispec.Descriptor, i *Ima
...
+		snapshotter:        snapshotter,
 		diffID:             "", // Image RO layer doesn't have a diff.
 		contentStoreDigest: "",
+		lease:              &lease,
 	}, nil
 }
 
+func leaseSnapshot(ctx context.Context, lm leases.Manager, snapshotter string, snapshotID string) (leases.Lease, error) {
+	if snapshotID == "" {
+		return leases.Lease{}, nil
```
Comment (thaJeztah) [inline daemon/containerd/image_builder.go:217]: I wonder if this is correct now, because we never return `nil`, so the idea of `lease` being `nil` ("there's no lease") may not apply now?

Should we change the signature of this function to return a pointer?

```go
func leaseSnapshot(ctx context.Context, lm leases.Manager, snapshotter string, snapshotID string) (*leases.Lease, error) {
	if snapshotID == "" {
		return nil, nil
```

File: daemon/containerd/image_builder.go [hunk 12]
```diff
@@ -223,22 +258,36 @@ func (rl *rolayer) DiffID() layer.DiffID {
 }
 
 func (rl *rolayer) Release() error {
+	if rl.lease != nil {
```
Comment (thaJeztah) [inline daemon/containerd/image_builder.go:263]: (This was the "never nil" I was referring to above)

File: daemon/containerd/image_builder.go [hunk 13]
```diff
@@ -440,20 +442,32 @@ func (i *ImageService) CreateImage(ctx context.Context, config []byte, parent st
...
+			return nil, err
+		}
+
+		layers = append(layers,
+			ocispec.Descriptor{
+				MediaType: containerdimages.MediaTypeDockerSchema2LayerGzip,
+				Digest:    layerDigest,
+				Size:      info.Size,
+			},
+		)
```
Comment (thaJeztah) [inline daemon/containerd/image_builder.go:469]: Oh, Guess this change got lost somewhere along the way (not a blocker, but I think you modified it in an earlier iteration);

```suggestion
		layers = append(layers, ocispec.Descriptor{
			MediaType: containerdimages.MediaTypeDockerSchema2LayerGzip,
			Digest:    layerDigest,
			Size:      info.Size,
		})
```

File: daemon/containerd/image_builder.go [hunk 14]
```diff
@@ -307,22 +372,33 @@ func (rw *rwlayer) Commit() (builder.ROLayer, error) {
...
-		return err
+	if rw.lease != nil {
+		lm := rw.c.LeasesService()
+		err := lm.Delete(context.TODO(), *rw.lease)
+		if err != nil {
+			log.G(context.TODO()).WithError(err).Warn("failed to delete lease when releasing RWLayer")
+		} else {
+			rw.lease = nil
+		}
 	}
```
Comment (thaJeztah) [inline daemon/containerd/image_builder.go:403]: sorry, one more question; I see here we're releasing the lease, _after_ which we try to do the unmounting and removing (which may fail).

- Are there any consequences of releasing the lease _before_ we perform those actions?
- Should releasing be done afterwards? (which could be in a defer)
- And (not sure) should it only be released on "success" or also on "error" ?

File: daemon/containerd/image_builder.go [hunk 15]
```diff
@@ -307,22 +372,33 @@ func (rw *rwlayer) Commit() (builder.ROLayer, error) {
...
-
 	if rw.root == "" { // nothing to release
 		return nil
 	}
```
Comment (thaJeztah) [inline daemon/containerd/image_builder.go:406]: Definitely not a blocker, and only update if other changes are needed (slightly related to the above); 

Would we ever have a lease if there's no `root` ? If not then I'd consider putting this one as first condition of the function, as it's a very clear "return early, we're done".

File: daemon/containerd/image_builder.go (hunk 11 above)
Comment (vvoland) [reply daemon/containerd/image_builder.go:217]: Ah right, good catch!

File: daemon/containerd/image_builder.go (hunk 14 above)
Comment (vvoland) [reply daemon/containerd/image_builder.go:403]: Ah, good catch. Yes, the lease should be performed later.

File: daemon/containerd/image_commit.go (hunk 10 above)
Comment (thaJeztah) [reply daemon/containerd/image_commit.go:127]: > IMO, considering that this function is a bit "lower-level", returning both a non-empty id and a non-nil error is consistent with what happened.

Yeah, it's not a blocker for sure. Mostly trying to avoid some code, somewhere ignoring the error, and depending on just the `id`.

> Potentially this could be a non-hard error depending on the use case. For example when doing the docker commit, unpacking failure could be still "fixable".

Maybe the function has too many responsibilities (i.e., it's not fully atomic, and "part of it" can fail).

Either way; not important, but mostly something I noticed. It may be one to keep in the back of our mind for improving in future.

**Comment by vvoland** [comment]
Applied suggestions from @thaJeztah and removed the "short-lived lease" usage in favor of just creating a ctx with a lease attached (so the c8d calls that result in creating a snapshot/content automatically add them to the lease). Thanks @dmcgowan for the hint!

File: daemon/containerd/image_builder.go [hunk 16]
```diff
@@ -194,23 +194,46 @@ func newROLayerForImage(ctx context.Context, imgDesc *ocispec.Descriptor, i *Ima
...
 		diffID:             "", // Image RO layer doesn't have a diff.
 		contentStoreDigest: "",
+		lease:              &lease,
 	}, nil
 }
 
+func createLease(ctx context.Context, lm leases.Manager) (context.Context, leases.Lease, error) {
+	lease, err := lm.Create(ctx,
+		leases.WithExpiration(time.Hour*24),
+		leases.WithLabels(map[string]string{
```
Comment (thaJeztah) [inline daemon/containerd/image_builder.go:221]: Think I'm gonna contribute a `leases.WithLabel(name, value string)` 😅 - I think that'd be nice to have (not having to construct a `map[string]string` to set a single label)

File: daemon/containerd/image_builder.go [hunk 17]
```diff
@@ -194,46 +195,47 @@ func newROLayerForImage(ctx context.Context, imgDesc *ocispec.Descriptor, i *Ima
...
+			"org.mobyproject.lease.classicbuilder": "true",
+		}),
+	)
+	if err != nil {
+		return nil, leases.Lease{}, fmt.Errorf("failed to create a lease for snapshot: %w", err)
```
Comment (thaJeztah) [inline daemon/containerd/image_builder.go:226]: Bit of a nit, but curious if there was a specific reason you didn't use a pointer return for the lease (to allow returning an explicit `nil` on failure)

File: daemon/containerd/image_builder.go [hunk 18]
```diff
@@ -248,41 +250,36 @@ func (rl *rolayer) DiffID() layer.DiffID {
...
+	key := stringid.GenerateRandomID()
+
+	ctx, lease, err := createLease(context.TODO(), rl.c.LeasesService())
 	if err != nil {
-		return nil, fmt.Errorf("failed to create lease for commit: %w", err)
+		return nil, err
 	}
+	defer func() {
+		if outErr != nil {
+			if err := rl.c.LeasesService().Delete(ctx, lease); err != nil {
```
Comment (thaJeztah) [inline daemon/containerd/image_builder.go:276]: Really silly question, but do you know why we need _both_ the `context` _and_ the lease, if the context has the lease(ID) attached?

File: daemon/containerd/image_builder.go (hunk 16 above)
Comment (thaJeztah) [reply daemon/containerd/image_builder.go:221]: - opened https://github.com/containerd/containerd/pull/9083 😄

File: daemon/containerd/image_builder.go (hunk 17 above)
Comment (vvoland) [reply daemon/containerd/image_builder.go:226]: To save the caller from dereferencing the Lease pointer (which won't be nil anyway if the function returns a nil error). This function doesn't return a nil error with an empty lease, so there's no need to have the ability to encode an empty lease here.

File: daemon/containerd/image_builder.go (hunk 18 above)
Comment (vvoland) [reply daemon/containerd/image_builder.go:276]: The lease is attached to the context, but is not tied to the lifetime of the context.
`Delete` deletes the specified lease and doesn't consider the lease attached to the context as a target of the operation.
The context here is just for the `Delete` operation and is not related to the lease itself.

File: daemon/containerd/image_builder.go (hunk 17 above)
Comment (thaJeztah) [reply daemon/containerd/image_builder.go:226]: Oh! Right; I was focusing on this specific case, where we needed a pointer;

```go
		lease:              &lease,
```

But didn't look at the other cases. Gotcha; makes sense 😄

**Review by thaJeztah — APPROVED** [review]
🙈 thought I already LGTM'd

But LGTM 😄

File: daemon/containerd/image_builder.go (hunk 18 above)
Comment (vvoland) [reply daemon/containerd/image_builder.go:276]: There's really only one way - `LeasesService.Delete`, it's just that in the usual case (`containerd.Client.WithLease`) the `Delete` is just hidden inside the cleanup function: https://github.com/containerd/containerd/blob/d015c99b2ec990c914a4b4546ec10d61cd947ab0/lease.go#L52
