### PR TITLE
Fix daemon not cleaned up w/ live restore enabled

### LINKED ISSUE #24350: Daemon live-restore doesnt perform mount cleanup on stopped containers.
**Output of `docker version`:**
```
Client:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.2
 Git commit:   c014c9d-unsupported
 Built:        Tue Jul  5 22:43:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.2
 Git commit:   c014c9d-unsupported
 Built:        Tue Jul  5 22:43:08 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
root@42a2dc1cb163:/go/src/github.com/docker/docker# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0-dev
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: overlay bridge null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 3.19.0-59-generic
Operating System: Debian GNU/Linux 8 (jessie) (containerized)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.38 GiB
Name: 42a2dc1cb163
ID: CB7M:RAGQ:G6KH:KX3R:VWWH:NGK2:L2SQ:SIGP:GM5S:DEWD:R57I:INL5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 23
 System Time: 2016-07-05T22:45:35.036304639Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Steps to reproduce the issue:**
1. Run a daemon integration test involving live-restore. Ex. TestCleanupMountsAfterDaemonCrash
2. Once test passes, delete the output "bundles" directory. 

**Describe the results you received:**
Removing the directory fails with
"rm: cannot remove 'bundles/1.12.0-dev/test-integration-cli/d67573768/root/overlay': Device or resource busy" message.

**Describe the results you expected:**
Removing directory should have no errors.

**Additional information you deem important (e.g. issue happens only occasionally):**
There should be a clean shutdown of stopped containers in the live-restore case. daemon/daemon.go Shutdown() returns right away for live-restore. It should handle the case of stopped containers, by unmounting through layerStore.

### PR DESCRIPTION
**Pull request by cpuguy83**
This patch makes sure daemon resources are cleaned up on shutdown if
there are no running containers.

Fixes #24350

### CODE REVIEW

**Comment by thaJeztah** [comment]
Experimental hitting a flaky test;  https://github.com/docker/docker/issues/24203
https://jenkins.dockerproject.org/job/Docker-PRs-experimental/20998/console

**Comment by thaJeztah** [comment]
LGTM

File: daemon/daemon.go [hunk 1]
```diff
@@ -652,8 +652,12 @@ func (daemon *Daemon) Shutdown() error {
 	// Keep mounts and networking running on daemon shutdown if
 	// we are to keep containers running and restore them.
 	if daemon.configStore.LiveRestore {
-		return nil
+		// check if there are any running containers, if none we should do some cleanup
+		if ls, err := daemon.Containers(&types.ContainerListOptions{}); len(ls) != 0 || err != nil {
```
Comment (runcom) [inline daemon/daemon.go]: isn't less expensive to call `daemon.containers.List()` then `daemon.Containers(...)`? I can see much stuff going on with `daemon.Containers(...)` - like filters even if you're providing an empty list option

**Comment by runcom** [comment]
just a question, LGTM otherwise

**Comment by anusha-ragunathan** [comment]
If there is a mix of running and stopped containers during daemon shutdown, dont we still want the stopped container mounts to be unmounted and other cleanup performed?

**Comment by cpuguy83** [comment]
@anusha-ragunathan The stopped containers will already be unmounted.
The issue you saw was with the root grpahdriver mount.

**Comment by anusha-ragunathan** [comment]
Yes, the graph driver mount is what I'm referring to.

File: daemon/daemon.go (hunk 1 above)
Comment (cpuguy83) [inline daemon/daemon.go]: daemon.containers.List will have to be manually filtered anyway.

**Comment by cpuguy83** [comment]
@anusha-ragunathan If there are running containers, we can't unmount the root graph mount.
All the other mounts are already gone.

**Comment by anusha-ragunathan** [comment]
layerStore.Cleanup calls the graphdriver's Cleanup method, which is:
- an *extra* call for any leftover container unmounts. Container unmounts already happen as part of daemon.Cleanup
- the main call for the root graphdriver mount. 
Thanks for the clarification, @cpuguy83 

LGTM.

**Comment by tonistiigi** [comment]
LGTM
