### PR TITLE
nftables: never enable IP forwarding on the host

### LINKED ISSUE #50566: nftables: IP forwarding, and filter-FORWARD policy
### Description

Docker needs to enable IP Forwarding for its bridge networks - that potentially turns an unsuspecting host into a router, which is particularly important when it has multiple interfaces. So, when Docker enables IP forwarding, it also sets the iptables/nftables "filter forward" policy to "drop" - Docker's container-related traffic is explicitly allowed, and everything else (packets between host interfaces etc) will be dropped.

But, if IP forwarding is enabled when Docker starts, it may mean other services running on the host need it enabled, and the drop policy is likely to break them. So, it doesn't set the "drop" policy.

_Before https://github.com/moby/moby/pull/48594, Docker always set the policy to "drop" for IPv6. But, when we enabled ip6tables by default, that broke things for people. So, we currently do the same thing for IPv6 as we've done forever for IPv4 - only set the policy to "drop" if the daemon enabled forwarding._

_As "forwarding already enabled" is a poor way to guess at whether the policy should be "drop", https://github.com/moby/moby/pull/48594 also added daemon config option `--ip-forward-no-drop` to tell it not to set the policy._

The issue for nftables is with daemon restarts ...

With iptables, a daemon restart re-creates all of Docker's rules. But, because iptables only has one set of tables/chains, that doesn't reset the filter-FORWARD policy. So, unless the user does-something, if Docker set the policy to drop it stays that way.

But, with nftables, the filter-FORWARD policy belongs to a chain in Docker's own table - which gets a complete reset on daemon restart. When the table is reconstructed, its filter-FORWARD policy becomes "accept". It then stays that way because an earlier incarnation of the daemon already enabled IP forwarding in the kernel.

Similarly, when switching from iptables to nftables ...

The nftables filter-FORWARD policy doesn't get set to drop, because Docker enabled IP forwarding while it was running with iptables. To make things worse, the iptables policy gets left at "drop" ... but the iptables chains no longer have exceptions for published ports, the nftables chains have those exceptions. So, the iptables (iptables-nft) policy drops traffic for published ports.

(The upgrade case could probably be documented away, but not the daemon restart issue.)

### Reproduce

See description.

### Expected behavior

_No response_

### docker version

```bash
Latest master (pre-29.0.0).
```

### docker info

```bash
Dev build.
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by robmry**
**- What I did**

- fix https://github.com/moby/moby/issues/50566
- replaces https://github.com/moby/moby/pull/50576
- replaces https://github.com/moby/moby/pull/50634

When Docker is using iptables and it enables IP forwarding, unless daemon option `--ip-forward-no-drop` is true, it sets the iptables filter-FORWARD policy to DROP.

When running with nftables - don't do that, raise an error if forwarding is needed but not enabled, unless `--ip-forward=false`.

On a host without IPv4 forwarding enabled, nftables firewall backend, and other settings at defaults - the daemon will fail to start when it tries to create the default bridge. It will fail to restore other networks, but those errors are only logged, not sure why. In other cases, for example `--bridge=none` or creating an IPv6 network when IPv6 global forwarding is disabled, network creation will fail with an error.

Log a warning when migrating from iptables to nftables when the iptables policy is DROP, because it'll drop packets that have been accepted by nftables rules (so, for example, published ports won't work).

_In 29.0, nftables is opt-in, and will be documented as "experimental". So, if we get push-back on this or come up with better ideas, we'll be able to change it._

_Docs will need an update to say it's the user's responsibility to update their firewall rules to block unwanted forwarding between non-Docker network interfaces._

**- How I did it**

- The first two commits are tidy-up - only nftabler needs an iptables cleaner, and only the iptabler (now) needs a method to set the filter-FORWARD policy. So, use those types directly in the bridge driver when needed.
- Raise the error when using nftables and forwarding is not enabled, and update tests.
- Log a warning about the iptables policy on migration to nftables.
- Enable IP forwarding in rootlesskit's netns, before starting the daemon.
- Update `check-config.sh` to report on the IP forwarding sysctls.

**- How to verify it**

- Start Docker with IP forwarding disabled and --firewall-backend=iptables - check the filter-FORWARD policies are DROP.
- Start Docker again with --firewall-backend=nftables, check logs for a warning about the iptables policy, for example ...
```
WARN[2025-08-06T13:26:03.383667797Z] Network traffic for published ports may be dropped, iptables chain FORWARD has policy DROP.  ipv=ipv4
```
- Disable IP forwarding, restart with nftables, check the daemon fails with an error ...
```
failed to start daemon: Error initializing network controller: error creating default "bridge" network: IPv4 forwarding is disabled: check your host's firewalling and set sysctl net.ipv4.ip_forward=1, or disable this check using daemon option --ip-forward=false
```
- With rootless Docker, checked a dual-stack bridge network was created ok with nftables (and wasn't without the sysctls in this PR), and that port publishing worked.

And, updated tests.

**- Human readable description for the release notes**
```markdown changelog
- nftables: Docker will not enable IP forwarding on the host. If forwarding is needed by a bridge network, but not enabled, daemon startup or network creation will fail with an error. You must either enable forwarding and ensure firewall rules are in place to prevent unwanted forwarding between non-Docker interfaces. Or, use daemon option `--ip-forward=false` to disable the check, but some bridge network functionality including port forwarding may not work. See [Engine Docs](https://docs.docker.com/engine/network/firewall-nftables) for more information about migration from iptables to nftables.
```

### CODE REVIEW

**Comment by robmry** [comment]
@AkihiroSuda - one of the commits here enables the IP forwarding sysctls in rootlesskit's netns ...

With `--firewall-backend=nftables` (which will eventually become the default), this PR makes it the user's job to configure their kernel as an installation step.

The dockerd-rootless change here enables forwarding whether using iptables or nftables. I don't think there's any harm in that, there aren't any non-Docker interfaces to forward between (apart from the netns's main `tap0` interface, which needs forwarding enabled for port publishing to work anyway). It means Docker with iptables won't set a default DROP policy on the FORWARD chain, but I think that's also ok as there's no non-Docker traffic to forward.

Not sure whether I've put the sysctl commands in the best place?

File: daemon/libnetwork/drivers/bridge/internal/nftabler/nftabler.go [hunk 1]
```diff
@@ -101,7 +101,7 @@ func (nft *nftabler) FilterForwardDrop(ctx context.Context, ipv firewaller.IPVer
 }
```
Comment (akerouanton) [inline daemon/libnetwork/drivers/bridge/internal/nftabler/nftabler.go]: `FilterForwardDrop` receiver isn't updated, so this commit and the next one are currently broken.

**Review by akerouanton — APPROVED** [review]
One nit, otherwise LGTM. Thanks!

**Review by austinvazquez — APPROVED** [review]
Changes LGTM on green CI run. At a glance, the current failures are all related to known flaky test or unknown CI issue.

**Comment by austinvazquez** [comment]
Needs rebase for CI fixes, then g2g. 👍🏼

File: daemon/libnetwork/drivers/bridge/bridge_linux.go [hunk 2]
```diff
@@ -556,7 +556,7 @@ var newFirewaller = func(ctx context.Context, config firewaller.Config) (firewal
 		// cleaner can't clean up network or port-specific rules that may have been added
 		// to iptables built-in chains. So, if cleanup is needed, give the cleaner to
 		// the nftabler. Then, it'll use it to delete old rules as networks are restored.
-		fw.(firewaller.FirewallCleanerSetter).SetFirewallCleaner(iptabler.NewCleaner(ctx, config))
+		fw.SetFirewallCleaner(iptabler.NewCleaner(ctx, config))
```
Comment (thaJeztah) [inline daemon/libnetwork/drivers/bridge/bridge_linux.go:559]: Not for this PR, just that my curiosity led me there; this looks to be the only place where we call `fw.SetFirewallCleaner` to a _non nil_ value, and the constructor is above.

Which made me curious if this should be done as part of the constructor, possibly with a `DisableCleaner()`, `DestroyCleaner`, `StopCleaning()` (or whatever) on the `Nftabler` type.

File: daemon/libnetwork/drivers/bridge/setup_bridgenetfiltering.go [hunk 3]
```diff
@@ -91,7 +91,7 @@ func enableBridgeNetFiltering(nfParam string) (retErr error) {
 func getKernelBoolParam(path string) (bool, error) {
 	line, err := os.ReadFile(path)
 	if err != nil {
-		return false, err
+		return false, fmt.Errorf("reading '%s': %w", path, err)
```
Comment (thaJeztah) [inline daemon/libnetwork/drivers/bridge/setup_bridgenetfiltering.go]: Curious; was information missing in the error, or did you pre-emptively add this? Because `os.ReadFile` (and other file operations from stdlib) _should_ usually return a `fs.PathError` / `os.PathError`, which already decorates the error with "Op" (e.g. `open` ), `Path`, and the error; https://github.com/golang/go/blob/768c51e368e05739854c1413fdf7fd129d01e482/src/io/fs/fs.go#L250-L255


```go
// PathError records an error and the operation and file path that caused it.
type PathError struct {
    Op   string
    Path string
    Err  error
}
```

File: daemon/libnetwork/drivers/bridge/setup_ip_forwarding_test.go [hunk 4]
```diff
@@ -14,19 +14,20 @@ import (
...
+	ffDrop6 bool
 }
 
 // FilterForwardDrop is part of interface [firewaller.Firewaller]. Just enough to check
 // it was called with the expected IPVersion.
-func (f *ffdTestFirewaller) FilterForwardDrop(_ context.Context, ipv firewaller.IPVersion) error {
-	f.ffd = ipv
+func (f *ffDropper) FilterForwardDrop(_ context.Context, ipv firewaller.IPVersion) error {
+	switch ipv {
+	case firewaller.IPv4:
```
Comment (thaJeztah) [inline daemon/libnetwork/drivers/bridge/setup_ip_forwarding_test.go:26]: Ah! The _other_ `IPVersion` type 😂 

Not for this PR, but it got me curious; is this always either/or, or could be "both"? Considering that the _other_ type has that as an option (so if it could set both values at once); https://github.com/moby/moby/blob/0b1b5bf13d7ee0f198c41e439747fb2b522b543d/daemon/libnetwork/types/types.go#L17-L23

**Review by thaJeztah — APPROVED** [review]
code looks sane to me; left some ramblings (as usual). Not merging as I wasn't sure if you wanted additional review from Cory

LGTM

File: daemon/libnetwork/drivers/bridge/bridge_linux.go (hunk 2 above)
Comment (robmry) [reply daemon/libnetwork/drivers/bridge/bridge_linux.go:559]: As soon as I get a chance - I'll keep the cleaner in the bridge driver so the firewaller implementation(s) don't need to call it (review comment from @akerouanton) ... it's a bit simpler this way, because the current firewaller has all the context for deleting old rules, the bridge driver will need to fish it out somehow. But, Albin's right, if we ever add a new firewaller it shouldn't really need to call the cleaner itself.

File: daemon/libnetwork/drivers/bridge/setup_bridgenetfiltering.go (hunk 3 above)
Comment (robmry) [reply daemon/libnetwork/drivers/bridge/setup_bridgenetfiltering.go]: Oh, probably preemptive - I'll get rid of it.

File: daemon/libnetwork/drivers/bridge/setup_ip_forwarding_test.go (hunk 4 above)
Comment (robmry) [reply daemon/libnetwork/drivers/bridge/setup_ip_forwarding_test.go:26]: For the firewaller, it's always either/or ... with iptables/ip6tables the rules are always separate. I decided to keep it that way in nftables too (although it has an `inet` type as well as `ip`/`ip6`, so one table can deal with both families).

But, for us, there's not much advantage in trying to combine them. The rules for bridge networks can be configured quite differently for v4/v6 ... for example, NAT for v4 and direct routing for v6.
