### PR TITLE
Move layer mount refcounts to mountedLayer

### LINKED ISSUE #9665: docker 1.4 and "Driver aufs failed to remove root filesystem",  "device or resource busy"
I don't think I saw this under docker 1.3.x on aufs (boot2docker on OSX), though I have with devicemapper on centos server. Got this error after upgrading docker server, retrying the `fig up` worked. 

I use `brew` and my docker client is still 1.3.2. Just saw the warning in the log below, I guess that's not really supported? I'll try upgrading docker client manually.

```
$ docker version
Client version: 1.3.2
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 39fa2fa
OS/Arch (client): darwin/amd64
Server version: 1.4.0
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 4595d4f
```
```
$ fig -f dns-fig.yml -p dns up -d
Recreating dns_hardfile_1...
Recreating dns_dnsmasq_1...
Cannot destroy container 07ba11ca55a87ec6556a27007dd56a42da370ed8d78b34aed2f573266e9dd727: Driver aufs failed to remove root filesystem 07ba11ca55a87ec6556a27007dd56a42da370ed8d78b34aed2f573266e9dd727: rename /mnt/sda1/var/lib/docker/aufs/mnt/07ba11ca55a87ec6556a27007dd56a42da370ed8d78b34aed2f573266e9dd727 /mnt/sda1/var/lib/docker/aufs/mnt/07ba11ca55a87ec6556a27007dd56a42da370ed8d78b34aed2f573266e9dd727-removing: device or resource busy
```

```
time="2014-12-14T20:21:27Z" level="info" msg="Container 07ba11ca55a87ec6556a27007dd56a42da370ed8d78b34aed2f573266e9dd727 failed to exit within 10 seconds of SIGTERM - using the force" 
time="2014-12-14T20:21:27Z" level="debug" msg="Sending 9 to 07ba11ca55a87ec6556a27007dd56a42da370ed8d78b34aed2f573266e9dd727" 
time="2014-12-14T20:21:28Z" level="info" msg="+job log(die, 07ba11ca55a87ec6556a27007dd56a42da370ed8d78b34aed2f573266e9dd727, dns_dnsmasq:latest)" 
time="2014-12-14T20:21:28Z" level="info" msg="-job log(die, 07ba11ca55a87ec6556a27007dd56a42da370ed8d78b34aed2f573266e9dd727, dns_dnsmasq:latest) = OK (0)" 
time="2014-12-14T20:21:28Z" level="info" msg="+job release_interface(07ba11ca55a87ec6556a27007dd56a42da370ed8d78b34aed2f573266e9dd727)"
...
time="2014-12-14T20:21:29Z" level="debug" msg="Calling DELETE /containers/{name:.*}" 
time="2014-12-14T20:21:29Z" level="info" msg="DELETE /v1.12/containers/07ba11ca55a87ec6556a27007dd56a42da370ed8d78b34aed2f573266e9dd727?link=False&force=False&v=False" 
time="2014-12-14T20:21:29Z" level="info" msg="+job rm(07ba11ca55a87ec6556a27007dd56a42da370ed8d78b34aed2f573266e9dd727)" 
Cannot destroy container 07ba11ca55a87ec6556a27007dd56a42da370ed8d78b34aed2f573266e9dd727: Driver aufs failed to remove root filesystem 07ba11ca55a87ec6556a27007dd56a42da370ed8d78b34aed2f573266e9dd727: r
ename /mnt/sda1/var/lib/docker/aufs/mnt/07ba11ca55a87ec6556a27007dd56a42da370ed8d78b34aed2f573266e9dd727 /mnt/sda1/var/lib/docker/aufs/mnt/07ba11ca55a87ec6556a27007dd56a42da370ed8d78b34aed2f573266e9dd727
-removing: device or resource busy
time="2014-12-14T20:21:29Z" level="info" msg="-job rm(07ba11ca55a87ec6556a27007dd56a42da370ed8d78b34aed2f573266e9dd727) = ERR (1)" 
time="2014-12-14T20:21:29Z" level="error" msg="Handler for DELETE /containers/{name:.*} returned error: Cannot destroy container 07ba11ca55a87ec6556a27007dd56a42da370ed8d78b34aed2f573266e9dd727: Driver a
ufs failed to remove root filesystem 07ba11ca55a87ec6556a27007dd56a42da370ed8d78b34aed2f573266e9dd727: rename /mnt/sda1/var/lib/docker/aufs/mnt/07ba11ca55a87ec6556a27007dd56a42da370ed8d78b34aed2f573266e9
dd727 /mnt/sda1/var/lib/docker/aufs/mnt/07ba11ca55a87ec6556a27007dd56a42da370ed8d78b34aed2f573266e9dd727-removing: device or resource busy" 
time="2014-12-14T20:21:29Z" level="error" msg="HTTP Error: statusCode=500 Cannot destroy container 07ba11ca55a87ec6556a27007dd56a42da370ed8d78b34aed2f573266e9dd727: Driver aufs failed to remove root file
system 07ba11ca55a87ec6556a27007dd56a42da370ed8d78b34aed2f573266e9dd727: rename /mnt/sda1/var/lib/docker/aufs/mnt/07ba11ca55a87ec6556a27007dd56a42da370ed8d78b34aed2f573266e9dd727 /mnt/sda1/var/lib/docker
/aufs/mnt/07ba11ca55a87ec6556a27007dd56a42da370ed8d78b34aed2f573266e9dd727-removing: device or resource busy" 
time="2014-12-14T20:24:15Z" level="debug" msg="Calling POST /containers/{name:.*}/exec" 
time="2014-12-14T20:24:15Z" level="info" msg="POST /v1.15/containers/dns_dnsmasq_1/exec" 
time="2014-12-14T20:24:15Z" level="debug" msg="Warning: client and server don't have the same version (client: 1.3.2, server: 1.4.0)"
```

### PR DESCRIPTION
**Pull request by cpuguy83**
Instead of implementing refcounts at each graphdriver, implement this in
the layer package which is what the engine actually interacts with now.
This means interacting directly with the graphdriver is no longer
explicitly safe with regard to Get/Put calls being refcounted.

This will be needed for the containerd integration, where containers are not killed on startup (and thus mounts will still exist) but refcounts are 0. There is still work to do after this to actually re-populate mount counts after a daemon restart, but this is not necessary before containerd.

Fixes #9665

### CODE REVIEW

**Comment by cpuguy83** [comment]
ping @anusha-ragunathan @tonistiigi 

I've done a fair amount of testing with this on aufs.
Also have run tests with overlay and devicemapper (on loopback) but not as extensively.
Still needs testing with zfs.

**Comment by cpuguy83** [comment]
Awesome, glad I had CI run this since it found some locking issues.

**Comment by aaronlehmann** [comment]
ping @dmcgowan

File: layer/mounted_layer.go [hunk 1]
```diff
@@ -131,8 +131,11 @@ func (rl *referencedRWLayer) Mount(mountLabel string) (string, error) {
 		return "", ErrLayerNotRetained
 	}
 
-	rl.activityCount++
-	return rl.mountedLayer.Mount(mountLabel)
+	m, err := rl.mountedLayer.Mount(mountLabel)
```
Comment (tonistiigi) [inline layer/mounted_layer.go]: Not sure I fully understand this logic. Shouldn't we call mount only if `activityCount == 0` and unmount if `activityCount == 1`.

Comment (cpuguy83) [inline layer/mounted_layer.go]: You're right, fixed the Mount call. Unmount is already following this logic.

File: layer/mounted_layer.go [hunk 2]
```diff
@@ -146,6 +156,13 @@ func (rl *referencedRWLayer) Unmount() error {
 		return ErrLayerNotRetained
 	}
 	rl.activityCount--
+	if rl.activityCount > 0 {
+		return ErrActiveMount
```
Comment (dmcgowan) [inline layer/mounted_layer.go]: Is the intention that this error would be ignored by the caller? Seems odd that increasing the activity beyond 1 can be done without throwing an error but decreasing it back down to one would involve handing this error. What information does the caller need about the mount state after calling this function, is it relevant that it is still mounted or not? ...assuming the caller is properly calling an Unmount for every corresponding Mount.

Comment (cpuguy83) [inline layer/mounted_layer.go]: you're right, this information is probably not needed for Unmount.

Comment (cpuguy83) [inline layer/mounted_layer.go]: Likewise, do you think we really need to return `ErrNotMounted` when it's already 0?
We shouldn't get to that point, but...

**Comment by cpuguy83** [comment]
oy vey, what happened now.

File: daemon/graphdriver/aufs/aufs.go [hunk 3]
```diff
@@ -64,21 +65,13 @@ func init() {
...
-	root       string
-	uidMaps    []idtools.IDMap
-	gidMaps    []idtools.IDMap
-	sync.Mutex // Protects concurrent modification to active
-	active     map[string]*data
+	root          string
+	uidMaps       []idtools.IDMap
+	gidMaps       []idtools.IDMap
+	pathCacheLock sync.Mutex
+	pathCache     map[string]string
```
Comment (dmcgowan) [inline daemon/graphdriver/aufs/aufs.go]: I don't see where this `pathCache` is actually storing any data. Seems to only be saving a couple `path.Join` calls, but at the expense of a lock and map lookup.

File: daemon/graphdriver/aufs/aufs.go [hunk 4]
```diff
@@ -259,108 +250,91 @@ func (a *Driver) createDirsFor(id string) error {
...
 	// the whole tree.
-	for _, p := range tmpDirs {
-		realPath := path.Join(a.rootPath(), p, id)
-		tmpPath := path.Join(a.rootPath(), p, fmt.Sprintf("%s-removing", id))
-		if err := os.Rename(realPath, tmpPath); err != nil && !os.IsNotExist(err) {
-			return err
-		}
-		defer os.RemoveAll(tmpPath)
+	tmpMntPath := path.Join(a.mntPath(), fmt.Sprintf("%s-removing", id))
+	if err := os.Rename(a.getMountpoint(id), tmpMntPath); err != nil && !os.IsNotExist(err) {
```
Comment (dmcgowan) [inline daemon/graphdriver/aufs/aufs.go]: could you just use `mountpoint` instead of `a.getMountpoint(id)`, neither the id or mount location could change in between.

**Comment by dmcgowan** [comment]
Design :+1:

File: daemon/graphdriver/aufs/aufs.go (hunk 4 above)
Comment (cpuguy83) [inline daemon/graphdriver/aufs/aufs.go]: good point. Originally was doing this because we had to read the parents to determine if the path should be mounted or not... but `Get` implicitly means that it should be mounted, and therefore an `mnt`. I'll make this change.

File: daemon/graphdriver/aufs/aufs.go (hunk 3 above)
Comment (cpuguy83) [inline daemon/graphdriver/aufs/aufs.go]: Really, it's saving us from having to determine if the layer has any parents wherever we are accessing it.

**Comment by cpuguy83** [comment]
updated

**Comment by cpuguy83** [comment]
Also I took `[WIP]` off, but would really appreciate if someone with btrfs and zfs can run the full test suite.

ping @calavera @vbatts

File: daemon/graphdriver/aufs/aufs.go (hunk 3 above)
Comment (dmcgowan) [inline daemon/graphdriver/aufs/aufs.go]: I see, it is saving a call to `getParentLayerPaths` which is indeed a non-cheap operation. Thanks :smile:

**Comment by dmcgowan** [comment]
layer store LGTM

File: daemon/graphdriver/overlay/overlay.go [hunk 5]
```diff
@@ -374,47 +359,39 @@ func (d *Driver) Get(id string, mountLabel string) (string, error) {
...
+		d.pathCache[id] = mountpoint
+		d.pathCacheLock.Unlock()
 	}
 
-	defer delete(d.active, id)
-	if mount.mounted {
-		err := syscall.Unmount(mount.path, 0)
-		if err != nil {
+	var err error
+	if mounted, err := mount.Mounted(mountpoint); mounted || err != nil {
```
Comment (anusha-ragunathan) [inline daemon/graphdriver/overlay/overlay.go]: mount.Mounted is an expensive file parse operation. Can we use statfs to perform a O(1) lookup of the mount point?

File: daemon/graphdriver/zfs/zfs.go [hunk 6]
```diff
@@ -335,48 +316,29 @@ func (d *Driver) Get(id, mountLabel string) (string, error) {
...
-			}
-		}
-		return nil
-	}
-
-	mnt.count--
-	if mnt.count > 0 {
-		return nil
+	mountpoint := d.mountPath(id)
+	mounted, err := mount.Mounted(mountpoint)
```
Comment (anusha-ragunathan) [inline daemon/graphdriver/zfs/zfs.go]: Again, use of mount.Mounted is expensive.

File: daemon/graphdriver/devmapper/deviceset.go [hunk 7]
```diff
@@ -2098,30 +2086,34 @@ func (devices *DeviceSet) Shutdown() error {
...
-			devices.Lock()
-			if err := devices.deactivateDevice(info); err != nil {
-				logrus.Debugf("devmapper: Shutdown deactivate %s , error: %s", info.Hash, err)
+		if !info.IsDir() {
+			return nil
+		}
+
+		for _, mnt := range mounts {
+			if mnt.Mountpoint == p {
+				if err := syscall.Unmount(p, syscall.MNT_DETACH); err != nil {
```
Comment (anusha-ragunathan) [inline daemon/graphdriver/devmapper/deviceset.go]: The unmount should be followed by a deactivateDevice(). Why was this removed?

Comment (cpuguy83) [inline daemon/graphdriver/devmapper/deviceset.go]: good catch, fixed!

**Comment by cpuguy83** [comment]
Updated and all :green_heart:

**Comment by vbatts** [comment]
with no other idea of what your changes are, i've run `make test` on commit 9d4c668 with a btrfs and linux 4.4.4 kernel. All passed.

**Comment by calavera** [comment]
running tests on ZFS right now. Will report back in a few minutes.

**Comment by cpuguy83** [comment]
Thanks @vbatts @calavera  :heart:

**Comment by calavera** [comment]
LGTM

**Comment by thaJeztah** [comment]
@vbatts now that you tested it, you #dibs'd it and have to review it as well, no escape :smiling_imp:

**Comment by icecrime** [comment]
I think @tonistiigi wants to have a quick look before merging.

**Comment by cpuguy83** [comment]
Really don't want to be the guy that messed up Docker 1.11 :)

File: daemon/graphdriver/overlay/overlay.go [hunk 8]
```diff
@@ -374,47 +358,39 @@ func (d *Driver) Get(id string, mountLabel string) (string, error) {
...
+		d.pathCache[id] = mountpoint
+		d.pathCacheLock.Unlock()
 	}
 
-	defer delete(d.active, id)
-	if mount.mounted {
-		err := syscall.Unmount(mount.path, 0)
-		if err != nil {
+	var err error
+	if mounted, err := graphdriver.Mounted(graphdriver.FsMagicOverlay, mountpoint); mounted || err != nil {
```
Comment (tonistiigi) [inline daemon/graphdriver/overlay/overlay.go]: Can we also call this for `Get` like we do in `aufs`. If I'm reading this correctly then second mount in overlay would just mount again, while in aufs it would give an error. Maybe correct way would just be to ignore the second mount if we can detect it.

**Comment by icecrime** [comment]
@cpuguy83 Someone has to ;-)

**Comment by anusha-ragunathan** [comment]
The windows graphdriver has refcounting logic for active mounts. daemon/graphdriver/windows/windows.go

**Comment by anusha-ragunathan** [comment]
Also, the generic graphdriver unit test (graphdriver_test.go) needs an update.

File: daemon/graphdriver/devmapper/deviceset.go [hunk 9]
```diff
@@ -2098,30 +2086,43 @@ func (devices *DeviceSet) Shutdown() error {
...
+	if err := filepath.Walk(path.Join(home, "mnt"), func(p string, info os.FileInfo, err error) error {
+		if err != nil {
+			return err
+		}
+		if !info.IsDir() {
+			return nil
+		}
+
+		if mounted[p] {
+			if err := syscall.Unmount(p, syscall.MNT_DETACH); err != nil {
```
Comment (anusha-ragunathan) [inline daemon/graphdriver/devmapper/deviceset.go]: Leave comment about MNT_DETACH untouched. It's applicable and useful.

File: daemon/graphdriver/overlay/overlay.go (hunk 8 above)
Comment (cpuguy83) [inline daemon/graphdriver/overlay/overlay.go]: Sure. Ultimately we shouldn't get to this point since the layer count should already be incremented so we don't reach the need for checking if it's mounted, but it certainly won't hurt.

Not sure if/how I can do that for Windows.

**Comment by cpuguy83** [comment]
ping @swernli 
In the Windows graphdriver, in `Diff` you are using the ref count in the graphdriver to determine if the layer is "prepared". Is there some other way to determine that?

**Comment by swernli** [comment]
@cpuguy83 Not really... the main goal of that check was to know if the layer we are exporting is mounted from the point of view of the rest of docker.  We know what state we need the layer to be in and the code could just force into that state, but we don't know if when the export is finished the layer should be left mounted or not.  If you can make the guarantee that Diff will only ever be run on mounted layers, then we can simplify the code to always return it to the mounted state (which is both activated and prepared).  If not, then you'll need to provide some other indication to Diff whether or not the target layer is mounted.

**Comment by cpuguy83** [comment]
Ok, I pushed changes for the Windows graphdriver.

I'm assuming that if calling `Diff` or `Changes` against a layer, the only time it would happen **while the layer is mounted** is against `mountedLayer` (or in the updated case, `mountedRWlayer`). So on Windows I'll just do a `Put` and a `defer Get` around the call to `Diff` and `Changes`... does that make sense.
Are these assumptions just plain wrong?

Is there any case where you'd be making calls to a `mountedLayer` that isn't mounted?

**Comment by cpuguy83** [comment]
also, I believe on Windows it won't allow `export` while the container is running (and thus mounted) anyway.

**Comment by LK4D4** [comment]
@cpuguy83 Compilation fails on CI

**Comment by swernli** [comment]
@cpuguy83 Unfortunately, those changes won't work for Windows as written.  The pattern you mention in your comment is not what our storage infrastructure needs; <code>Get</code> results in a layer that is active and prepared, but our <code>exportLayer</code> requires that the layer be active but NOT prepared.  So essentially, it needs to be half mounted, or export will fail.  That is why the previous behavior was to call <code> UnpreppareLayer </code> with a <code> defer PrepareLayer </code> if the layer was already mounted, and <code> ActivateLayer </code> with a <code>defer DeactivateLayer </code> if the layer was not mounted.

As I mentioned before, if we can guarantee that a given layer will either always be mounted when Diff is called or never be mounted when diff is called, we can simplify to one of those cases.  Otherwise, the Windows graphdiver will need to be given additional information to determine which of those code paths to take.

**Comment by swernli** [comment]
@cpuguy83 The same is true for <code>Changes</code>, where the layer must be active but not prepared.

**Comment by icecrime** [comment]
```
18:49:00 Building: bundles/1.11.0-dev/cross/windows/amd64/docker-1.11.0-dev.exe
18:49:12 # github.com/docker/docker/layer
18:49:12 layer/mounted_layer_windows.go:14: rl.MountID undefined (type *referencedRWLayer has no field or method MountID)
18:49:12 layer/mounted_layer_windows.go:15: not enough arguments to return
18:49:12 layer/mounted_layer_windows.go:17: rl.layerstore undefined (type *referencedRWLayer has no field or method layerstore)
18:49:12 layer/mounted_layer_windows.go:28: rl.MountID undefined (type *referencedRWLayer has no field or method MountID)
18:49:12 layer/mounted_layer_windows.go:29: not enough arguments to return
18:49:12 layer/mounted_layer_windows.go:31: rl.layerstore undefined (type *referencedRWLayer has no field or method layerstore)
18:49:12 layer/mounted_layer_windows.go:34: too many arguments in call to rl.mountedLayer.Changes
```

**Comment by cpuguy83** [comment]
@swernli ok, I changed this to, in addition to unmounting from the mounted_layer, to also call `ActivateLayer` in Diff and Changes.

I'm going to try and get tp4 running in a VM here, I didn't have much luck before.

**Comment by swernli** [comment]
@cpuguy83 Ok, that looks good.  The comment you added about not being called on a mounted layer on <code>Changes</code> would be helpful on <code>Diff</code> as well, to make clear that it also has the same expectation.

File: layer/mounted_layer_windows.go [hunk 10]
```diff
@@ -0,0 +1,35 @@
+package layer
+
+import (
+	"io"
+
+	"github.com/docker/docker/pkg/archive"
+)
+
+func (rl *referencedRWLayer) TarStream() (io.ReadCloser, error) {
```
Comment (cpuguy83) [inline layer/mounted_layer_windows.go]: Wondering if we should make this error out instead of trying to unmount/mount. Seems dangerous.

File: layer/mounted_layer_windows.go [hunk 11]
```diff
@@ -0,0 +1,35 @@
...
+		if err := rl.layerStore.driver.Put(rl.mountID); err != nil {
+			return nil, err
+		}
+		defer rl.layerStore.driver.Get(rl.mountID, string(rl.parent.ChainID()))
+	}
+
+	return rl.mountedLayer.TarStream()
+}
+
+func (rl *referencedRWLayer) Changes() ([]archive.Change, error) {
```
Comment (cpuguy83) [inline layer/mounted_layer_windows.go]: Same as above.

**Comment by cpuguy83** [comment]
@swernli Updated the comment

@tonistiigi Can you confirm my assumptions above: https://github.com/docker/docker/pull/21107#issuecomment-197625353

**Comment by tonistiigi** [comment]
@cpuguy83 Assumption about the `Diff/Changes` should be correct. Before they were also called on push but not after layerstore.

**Comment by icecrime** [comment]
Restore seems to be an issue for networking, we might be better off not taking this for 1.11 (cc @mavenugo)

**Comment by mavenugo** [comment]
@icecrime is this PR related to the restore discussion ?

**Comment by icecrime** [comment]
No sorry, it's orthogonal.

**Comment by cpuguy83** [comment]
This also seems to fix issues with `EBUSY` errors when removing containers. This is because the refcount is just wrong in cases where the daemon was killed while the layer was still mounted.

**Comment by thaJeztah** [comment]
Looks like WindowsTP4 is failing https://jenkins.dockerproject.org/job/Docker-PRs-WoW-TP4/3260/console

**Comment by cpuguy83** [comment]
Errors look unrelated.

**Comment by thaJeztah** [comment]
Let me restart WindowsTP4. Given that the panic was in `TestMountAndRegister` I thought there could be relation. Copying here just in case

```
02:13:00 --- FAIL: TestMountAndRegister (0.01s)
02:13:00 panic: runtime error: invalid memory address or nil pointer dereference [recovered]
02:13:00 	panic: runtime error: invalid memory address or nil pointer dereference
02:13:00 [signal 0xc0000005 code=0x1 addr=0x0 pc=0x49b549]
02:13:00 
02:13:00 goroutine 9 [running]:
02:13:00 panic(0x6a08e0, 0xc08200c080)
02:13:00 	c:/go/src/runtime/panic.go:464 +0x3f4
02:13:00 testing.tRunner.func1(0xc08208aab0)
02:13:00 	c:/go/src/testing/testing.go:467 +0x199
02:13:00 panic(0x6a08e0, 0xc08200c080)
02:13:00 	c:/go/src/runtime/panic.go:426 +0x4f7
02:13:00 github.com/docker/docker/layer.(*roLayer).ChainID(0x0, 0xc0820078c0, 0x40)
02:13:00 	github.com/docker/docker/layer/_test/_obj_test/ro_layer.go:55 +0x29
02:13:00 github.com/docker/docker/layer.(*referencedRWLayer).TarStream(0xc0820097e0, 0x0, 0x0, 0x0, 0x0)
02:13:00 	github.com/docker/docker/layer/_test/_obj_test/mounted_layer_windows.go:21 +0x19d
02:13:00 github.com/docker/docker/layer.createLayer(0x934b10, 0xc082007840, 0x0, 0x0, 0xc0820094a0, 0x0, 0x0, 0x0, 0x0)
02:13:00 	c:/go/src/github.com/docker/docker/layer/layer_test.go:101 +0x21f
02:13:00 github.com/docker/docker/layer.TestMountAndRegister(0xc08208aab0)
02:13:00 	c:/go/src/github.com/docker/docker/layer/layer_test.go:274 +0x27c
02:13:00 testing.tRunner(0xc08208aab0, 0x855d08)
02:13:00 	c:/go/src/testing/testing.go:473 +0x9f
02:13:00 created by testing.RunTests
02:13:00 	c:/go/src/testing/testing.go:582 +0x899
02:13:00 FAIL	github.com/docker/docker/layer	0.040s
```

**Comment by cpuguy83** [comment]
Ah I didn't see that one.


Brian Goff

**Comment by thaJeztah** [comment]
Still some failures on windowsTP4;

```
15:46:42 ?   	github.com/docker/docker/image/v1	[no test files]
15:46:42 --- FAIL: TestMountAndRegister (0.00s)
15:46:42 	layer_test.go:276: not support on this platform
15:46:42 --- FAIL: TestRegisterExistingLayer (0.01s)
15:46:42 	layer_test.go:699: not support on this platform
15:46:42 FAIL
```

**Comment by cpuguy83** [comment]
@thaJeztah thanks, working on it. Unfortunately the only way I can test windows currently is to push to CI.

**Comment by cpuguy83** [comment]
This is a bad assumption in the test, btw, that the prior version of the windows graphdriver happily complied with, even though it wasn't really correct to do so (and the daemon prevented it from happening higher up in the stack anyway).

**Comment by cpuguy83** [comment]
@swernli Can you check the current behavior for the Windows side?

**Comment by swernli** [comment]
@cpuguy83 I'm building your branch now to try some basic testing on Windows.

**Comment by swernli** [comment]
@cpuguy83 Commit of a container into an image is failing on Windows with these changes.  Unfortunately, it looks like it's due to exactly what we were worried about: exporting a read/write layer happens while the layer is mounted, so it's failing at the new check that you added which tries to prevent Diff or Changes from being called on a mounted layer.

This has also exposed a bug in the daemon code (<code>func (daemon *Daemon) exportContainerRw(container *container.Container) (archive.Archive, error)</code>) where it performs a Mount, but if TarStream returns an error the function returns without dismounting, leaving the container in a state where it can't be deleted.

**Comment by swernli** [comment]
@cpuguy83 It looks like we had the assumption backwards; most code calls Diff and Changes with the layer mounted, not the other way around.  I changed the code to expect a mounted layer in Diff and Changes, inverted the check you added in mounted_layer_windows.go, and added the bug fix for exportContainerRw, and it seems to work with basic tested.  You can find my modifications here:
https://github.com/Microsoft/docker/tree/sjw/one_ctr_to_rule_them_all

You may still need to update your tests with the new assumptions, and I'm not sure this covers all code paths, but at least for commit the expectation seems to be that the caller mounts the layer first.  If it helps, this requirement that the layer be half mounted (Active but not Prepared) for exportLayer in the Windows graphdriver is only true for r/w layers.  For read-only layers, activate/prepare/deactive/unprepared operations are no-ops.

**Comment by cpuguy83** [comment]
@swernli The issue is, I don't want to modify the layer state unless the layer is not mounted because I would expect that to cause problems for the container.
If this is not a problem for the container than great.

Note that the Linux graphdrivers don't care if the layer is mounted or not, so these should be Windows only changes.

**Comment by swernli** [comment]
@cpuguy83 Yup, agreed.  The changes in the branch I linked to are only in the Windows driver and in mounted_layer_windows.go, with one minor bugfix in exportContainerRw that is applicable to both Linux and Windows.  Since on Windows we don't support commit or export of a running container (which is blocked farther up), and the modifications to the mounted layer are all handled inside of our graphdriver, the behavior should be consistent with the goals you have.

Take a look at the commit I made on top of your changes (https://github.com/Microsoft/docker/commit/ac932c079e35f8f3459d9b63405431e6be71e2d8) and you'll see what I mean.

**Comment by cpuguy83** [comment]
Updated this to fix tp4 issues, and tp4 CI is finally running through :)

This still shows 1.11 milestone, but do let me know if we don't want to pull this in for 1.11 as I'd like to at least patch the `EBUSY` issues for 1.11 since I know what's causing them now.

**Comment by tonistiigi** [comment]
LGTM

We will do a follow-up for the live restore feature that also saves `ml.path` to disk and adds reference count to `mountedLayer.Mount` (these updates are not needed for `v1.11`).

**Comment by cpuguy83** [comment]
`FAIL: docker_cli_run_test.go:4225: DockerSuite.TestRunAttachFailedNoLeak` on tp4 -- I assume this is a flakey one?

**Comment by anusha-ragunathan** [comment]
To clarify, live restore requires "saves ml.path to disk". However "add reference count to mountedLayer.Mount" is optional given that there's only one callsite to GetRWLayer in both cases of regular daemon start and restore daemon path.

**Comment by cpuguy83** [comment]
And for some reason GH didn't get a notification about janky's state?
image

Finished but says it's still running (and has been this way for awhile).
