### PR TITLE
vendor: docker/libnetwork b3507428be5b458cb0e2b4086b13531fb0706e46

### LINKED ISSUE #2607: IPv4 and IPv6 addresses are not bound by default anymore
After the change in #2604, specifically the change:

>     1. Allocate either a IPv4 and/or IPv6 Port Binding (HostIP, HostPort, ContainerIP,  ContainerPort) based on the input and system parameters
>     2. Update the userland proxy as well as dummy proxy (inside port mapper) to specifically listen to either the IPv4 or IPv6 network

The docker containers will no longer respond to an IPv6 address when bound to `0.0.0.0`. While this change probably makes sense because the container is not actually seeing the IPv4 request and is seeing the proxy's address instead (i.e. `172.18.0.1`) this will be unexpected to a user.

This seems to likely be the problem mentioned in the following comments on #2604

> This looks like a breaking change since until now `docker-proxy` has been binding to both `v4` and `v6` addresses if both are available on the system which I believe made sense.
> 
> @vin01 in https://github.com/moby/libnetwork/issues/2604#issuecomment-754599371

> According to the Changelog [1] this is the only network related change in 20.10.2.
> Now my IPv6 port forwarding is completely broken.
> Downgrading to 20.10.1 fixed it.
> 
> There are no docker-proxy processes started. 20.10.1 starts a process for each port-forwarding.
> 
> Example:
> 
> ```
> sudo docker run \
>     --hostname gitlab \
>     --env 'GITLAB_PORT=443' \
>     --env 'GITLAB_HTTPS=true' \
>     --publish [<ip>]:2222:22 \
>     --publish [<ip>]:8080:80 \
>     --publish [<ip>]:8443:443 \
>     --name gitlab \
>     --restart always \
>     --volume /srv/gitlab/config:/etc/gitlab:Z \
>     --volume /srv/gitlab/logs:/var/log/gitlab:Z \
>     --volume /srv/gitlab/data:/var/opt/gitlab:Z \
>     gitlab/gitlab-ce:latest
> ```
> 
> [1] https://docs.docker.com/engine/release-notes/
>
> @fbezdeka in https://github.com/moby/libnetwork/pull/2604#issuecomment-754724482

and

> I confirm, I have the same problem
> 
> @pokotiV in https://github.com/moby/libnetwork/pull/2604#issuecomment-754769381

While I _did_ see docker-proxy processes when running `systemctl status docker`

```
/usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 443 -container-ip 172.18.0.2 -container-port 443
/usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 80 -container-ip 172.18.0.2 -container-port 80
``` 

I was getting a connection refused by NGINX. Rolling back to `20.10.1` (removing #2604) does change this to be what I expect. For the long term I will look at properly exposing IPv6 addresses, but this probably should have not surprised users without at least a deprecation warning.

### LINKED ISSUE #41858: IPv6 is no longer proxied by default anymore
**Description**

IPv6 is no longer proxied by default as of 20.10.2 (#41805). This is expanded in greater detail in https://github.com/moby/libnetwork/issues/2607, but downgrading to 20.10.1 will restore the previous behavior. This change should be either documented or fixed to not surprise users.

**Steps to reproduce the issue:**

1. Bind NGINX with published ports `--publish 443:443` and get "IPv6 support" (proxy is just accepting any address and proxying to the container. This may be abusing the proxy, but it works.)
2. Upgrade to Docker 20.10.2 and now IPv6 is broken and curl returns "Connection refused"

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:43 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       f001486
  Built:            Tue Dec 15 04:32:52 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 22
  Running: 22
  Paused: 0
  Stopped: 0
 Images: 14
 Server Version: 20.10.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1034-aws
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.786GiB
 Name: web1.dev.internal.nexleaf.org
 ID: 7G37:MVZI:VTVY:Q5UJ:CDA6:UKRI:7PF7:LLM6:YFAR:LTZR:6AQ4:Y7ZF
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No blkio weight support
WARNING: No blkio weight_device support
```

### LINKED ISSUE #41861: Docker uses 'iptables' instead of 'ip6tables' for IPv6 NAT rule, crashes
**Description**

I'm trying to enable IPv6 NAT for the default bridge network. If the `ip6tables` daemon option is enabled, Docker tries to add an IPv6 NAT rule using `iptables`, which fails because `ip6tables` should be used instead.

**Steps to reproduce the issue:**

1. Update `/etc/docker/daemon.json`:
```json
{
    "experimental": true,
    "ipv6": true,
    "ip6tables": true,
    "fixed-cidr-v6": "fd9e:63ac:6dcd::/48"
}
```
2. Restart Docker: `sudo systemctl stop docker; sudo ip link del docker0; sudo systemctl start docker`
3. Docker daemon crashed during start.

```
# sudo journalctl -u docker
dockerd[11587]: failed to start daemon: Error initializing network controller: Error creating default "bridge" network: Failed to Setup IP tables: Unable to enable NAT rule:  (COMMAND_FAILED: '/usr/sbin/iptables -w10 -t nat -I POSTROUTING -s fd9e:63ac:6dcd::/48 ! -o docker0 -j MASQUERADE' failed: iptables v1.8.5 (legacy): invalid mask `48' specified
```

**Describe the results you received:**

Docker tries to run the following command, which fails and Docker crashes:

```
/usr/sbin/iptables -w10 -t nat -I POSTROUTING -s fd9e:63ac:6dcd::/48 ! -o docker0 -j MASQUERADE
```

**Describe the results you expected:**

Docker should run the command using `ip6tables` instead:

```
/usr/sbin/ip6tables -w10 -t nat -I POSTROUTING -s fd9e:63ac:6dcd::/48 ! -o docker0 -j MASQUERADE
```

**Additional information you deem important (e.g. issue happens only occasionally):**

If I remove the `ip6tables` option from `daemon.json`, restart Docker and run the fixed command from above (using `ip6tables`), IPv6 NAT works:

```
➜ docker run --rm -it alpine ping -c 4 2606:4700:4700::1111
PING 2606:4700:4700::1111 (2606:4700:4700::1111): 56 data bytes
64 bytes from 2606:4700:4700::1111: seq=0 ttl=63 time=5.24 ms
64 bytes from 2606:4700:4700::1111: seq=1 ttl=63 time=5.40 ms
64 bytes from 2606:4700:4700::1111: seq=2 ttl=63 time=5.44 ms
64 bytes from 2606:4700:4700::1111: seq=3 ttl=63 time=5.46 ms

--- fde0:8899:8672:1::1 ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max = 5.236/5.381/5.456 ms
```

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:18:35 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:44 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 13
 Server Version: 20.10.2
 Storage Driver: btrfs
  Build Version: Btrfs v5.9 
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.9.16-200.fc33.x86_64
 Operating System: Fedora 33 (Workstation Edition)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 39.07GiB
 Name: ping
 ID: S5VU:MHDD:7D2V:YPGW:IOU2:AUQG:DMYS:IJ3Y:IRZD:5MWB:DBV4:PRR2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 100.96.0.0/16, Size: 24

WARNING: No kernel memory TCP limit support
WARNING: No oom kill disable support
WARNING: Support for cgroup v2 is experimental
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical (Notebook)

### PR DESCRIPTION
**Pull request by thaJeztah**
also somewhat related to https://github.com/moby/moby/issues/28589, which discusses the "implicit" binding of IPv6

depends on:

- [x] https://github.com/moby/moby/pull/42021 Update rootlesskit to v0.13.1 to fix handling of IPv6 addresses
    - [x] https://github.com/rootless-containers/rootlesskit/pull/213 Refactor ParsePortSpec to handle IPv6 addresses, and improve validation
- [x] https://github.com/moby/moby/pull/42050 CI: update tests to be more resilient against CLI output format and for libnetwork changes
- [x] ~https://github.com/moby/moby/pull/42102~ https://github.com/moby/moby/pull/42179 update rootlesskit to v0.14.0
    - [x] https://github.com/rootless-containers/rootlesskit/pull/232 Port API: support specifying IP version explicitly ("tcp4", "tcp6")

full diff: https://github.com/docker/libnetwork/compare/fa125a3512ee0f6187721c88582bf8c4378bd4d7...b3507428be5b458cb0e2b4086b13531fb0706e46

- fixed IPv6 iptables rules for enabled firewalld (https://github.com/moby/libnetwork/pull/2609)
    - fixes https://github.com/moby/moby/issues/41861 "Docker uses 'iptables' instead of 'ip6tables' for IPv6 NAT rule, crashes" 
- Fix regression in https://github.com/moby/libnetwork/pull/2608
    - introduced in "Fix IPv6 Port Forwarding for the Bridge Driver" (https://github.com/moby/libnetwork/pull/2604)
    - fixes https://github.com/moby/libnetwork/issues/2607 "IPv4 and IPv6 addresses are not bound by default anymore"
    - fixes https://github.com/moby/moby/issues/41858 "IPv6 is no longer proxied by default anymore"
- Use hostIP to decide on Portmapper version (https://github.com/moby/libnetwork/pull/2616)
    - fixes docker-proxy not being stopped correctly

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
@arkodg PTAL; can you check if I have the correct "fixes" in place or if I missed any / linked the wrong ones?

**Comment by thaJeztah** [comment]
Lots of failures; look related / legit failures;

```
=== FAIL: arm64.integration.container TestNetworkLoopbackNat (0.28s)
    nat_test.go:66: assertion failed: error is not nil: Error response from daemon: driver failed programming external connectivity on endpoint server-TestNetworkLoopbackNat (5a4eaaf3ff84ad959dc875a4829767a89dd3da6bc472e3f6feba32241b54d982): Bind for :::8080 failed: port is already allocated
```

```
=== RUN   TestNetworkLocalhostTCPNat
--- FAIL: TestNetworkLocalhostTCPNat (0.15s)
    nat_test.go:48: assertion failed: error is not nil: Error response from daemon: driver failed programming external connectivity on endpoint server-TestNetworkLocalhostTCPNat (09844ee44b347259889cac7df6f0a9ac78af25af4a690166d4e404eed2d01845): Error starting userland proxy: error while calling PortManager.AddPort(): listen tcp: address :::8081: too many colons in address
```

```
=== RUN   TestDockerSuite/TestPortExposeHostBinding
    --- FAIL: TestDockerSuite/TestPortExposeHostBinding (0.54s)
        docker_cli_port_test.go:314: assertion failed: expression is false: err == nil: out: 0.0.0.0:49153
            :::49153
```

```
=== RUN   TestDockerSuite/TestPortHostBinding
   --- FAIL: TestDockerSuite/TestPortHostBinding (0.53s)
       docker_cli_port_test.go:293: assertion failed: error is not nil: different size lists 0.0.0.0:9876
           :::9876
           , 2, 1
```

```
=== RUN   TestDockerSuite/TestPsNotShowPortsOfStoppedContainer
    --- FAIL: TestDockerSuite/TestPsNotShowPortsOfStoppedContainer (0.50s)
        docker_cli_ps_test.go:603: assertion failed: :::5000->5000/tcp (fields[len(fields)-2] string) != 0.0.0.0:5000->5000/tcp (expected string): Expected: 0.0.0.0:5000->5000/tcp, got: :::5000->5000/tcp
```

```
=== RUN   TestDockerSuite/TestRunAllocatePortInReservedRange
    --- FAIL: TestDockerSuite/TestRunAllocatePortInReservedRange (0.80s)
        docker_cli_run_test.go:2071: invalid port, got: 49155
            , error: strconv.ParseInt: parsing "49155\n": invalid syntax
```

```
=== RUN   TestDockerSuite/TestRunAllowPortRangeThroughExpose
    --- FAIL: TestDockerSuite/TestRunAllowPortRangeThroughExpose (0.71s)
        docker_cli_run_test.go:2282: Port is not mapped for the port 3000/tcp
```

**Comment by thaJeztah** [comment]
@bboehmke PTAL

**Comment by bboehmke** [comment]
1. failure:
```
=== FAIL: arm64.integration.container TestNetworkLoopbackNat (0.28s)
    nat_test.go:66: assertion failed: error is not nil: Error response from daemon: driver failed programming external connectivity on endpoint server-TestNetworkLoopbackNat (5a4eaaf3ff84ad959dc875a4829767a89dd3da6bc472e3f6feba32241b54d982): Bind for :::8080 failed: port is already allocated
```
is caused because the `docker-proxy` process for IPv6 is not removed after the container is stopped.

I think this is caused because the `releasePort` selects the wrong portMapper.

On creation the `bnd.IP` is used: https://github.com/moby/libnetwork/blob/master/drivers/bridge/port_mapping.go#L142
On release the `bnd.HostIP` is used: https://github.com/moby/libnetwork/blob/master/drivers/bridge/port_mapping.go#L212

For the IPv6 userland proxy the `bnd.HostIP` is `::` and the `bnd.IP` is a IPv4.

**Comment by bboehmke** [comment]
failure 3
```
=== RUN   TestDockerSuite/TestPortExposeHostBinding
    --- FAIL: TestDockerSuite/TestPortExposeHostBinding (0.54s)
        docker_cli_port_test.go:314: assertion failed: expression is false: err == nil: out: 0.0.0.0:49153
            :::49153
```
failure 4
```
=== RUN   TestDockerSuite/TestPortHostBinding
   --- FAIL: TestDockerSuite/TestPortHostBinding (0.53s)
       docker_cli_port_test.go:293: assertion failed: error is not nil: different size lists 0.0.0.0:9876
           :::9876
           , 2, 1
```
failure 5
```
=== RUN   TestDockerSuite/TestPsNotShowPortsOfStoppedContainer
    --- FAIL: TestDockerSuite/TestPsNotShowPortsOfStoppedContainer (0.50s)
        docker_cli_ps_test.go:603: assertion failed: :::5000->5000/tcp (fields[len(fields)-2] string) != 0.0.0.0:5000->5000/tcp (expected string): Expected: 0.0.0.0:5000->5000/tcp, got: :::5000->5000/tcp
```

I think they are caused because the container now also shows the IPv6 publish (previously only IPv4).
Here an example:
```
root@docker-test:~# docker ps
CONTAINER ID   IMAGE     COMMAND                  CREATED         STATUS         PORTS                               NAMES
2eea9954bb0a   nginx     "/docker-entrypoint.…"   9 seconds ago   Up 8 seconds   0.0.0.0:80->80/tcp, :::80->80/tcp   nginx_test
```

**Comment by bboehmke** [comment]
failure 7:
```
=== RUN   TestDockerSuite/TestRunAllowPortRangeThroughExpose
    --- FAIL: TestDockerSuite/TestRunAllowPortRangeThroughExpose (0.71s)
        docker_cli_run_test.go:2282: Port is not mapped for the port 3000/tcp
```
similar to the ones before but this time it expects that the binding is only correct if there is exactly one binding:
https://github.com/moby/moby/blob/master/integration-cli/docker_cli_run_test.go#L2281

The inspect output would look like this:
```json
            "Ports": {
                "80/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "80"
                    },
                    {
                        "HostIp": "::",
                        "HostPort": "80"
                    }
                ]
            },

```

**Comment by bboehmke** [comment]
Sadly for the second one I have no idea what is going on.
Maybe it is also related to the first one but I can not test this locally because the integration test is not running on my system.

Sadly I don't think I will have the time to fix this on my one in the next days. 
But at least I hope this information helps to fix the issues/tests.

**Comment by arkodg** [comment]
thanks for triaging the issues @bboehmke !
@thaJeztah can you please include https://github.com/moby/libnetwork/pull/2616 in this PR ?

The port bindings have now been split up into 2 - for ipv4 and ipv6
1. This helps set up port mapping using `iptables` for ipv4 bindings and `ip6tables` for ipv6 bindings in a cleaner way
2. earlier a binding using something like `-p 3000:3000` set up 2 bindings if using `userland-proxy` and 1 if using
`iptables` .
3. To resolve the tests failures, we can either look for 2 bindings - for `0.0.0.0` and `::` or disable userland proxy & ipv6

**Comment by thaJeztah** [comment]
> The port bindings have now been split up into 2 - for ipv4 and ipv6

Looks like we should at least mention that in the changelog. Also /cc @simonferquel @djs55 as I think Docker Desktop makes use of that information to setup networking

**Comment by thaJeztah** [comment]
> @thaJeztah can you please include moby/libnetwork#2616 in this PR ?

updated the commit to include that PR. Will have a look later at fixing the tests

**Comment by thaJeztah** [comment]
Looks like this failure is an issue in rootless kit;

```
=== RUN   TestNetworkNat
--- FAIL: TestNetworkNat (0.22s)
    nat_test.go:30: assertion failed: error is not nil: Error response from daemon: driver failed programming external connectivity on endpoint server-TestNetworkNat (65cc966cfc2fd79fcfaf0063f3afa7174e8854ce9dfce04e7f9cd4cd0b1e0268): Error starting userland proxy: error while calling PortManager.AddPort(): listen tcp: address :::8080: too many colons in address
```

Probably somewhere in this function, which doesn't look to be handling IPv6 addresses; https://github.com/rootless-containers/rootlesskit/blob/27c9611a3931149dd91fabd2d559140c351bf36f/pkg/port/portutil/portutil.go#L13-L15

**Comment by thaJeztah** [comment]
I thought I'd have a look at the rootless kit code (thought; replace with the go-connections code used in Docker and Libnetwork), but I think this change; https://github.com/rootless-containers/rootlesskit/pull/207 is problematic; the "port spec" string format is already ambiguous in docker (`[ip-address]:[port or port-range]:[port or port-range][/protocol]`), but could still be handled (knowing that `port` or `port-range` would always be either "empty", "integer", or "integer-integer"). Having _two_ IP addresses in the format makes things a lot more complicated if IPv6 is added to the equation (using `[]` could somewhat help for `::`, but `[::]`, or `2001:db8::1` I think would still be problematic.
Can (for now) probably work around it by making sure we use the IPv4 for that test. (test also looks to not put `[]` around IPv6 addresses, which probably should, as its `<ip>:<port>`)

**Comment by thaJeztah** [comment]
moved to 'draft', pending https://github.com/moby/moby/pull/42050

**Comment by thaJeztah** [comment]
Getting close; ppc64le failure is unrelated (need to create a ticket for that), but rootless failure looks related, and fails on 3 tests;

```
=== FAIL: amd64.integration.container TestNetworkNat (0.23s)
    nat_test.go:30: assertion failed: error is not nil: Error response from daemon:
    driver failed programming external connectivity on endpoint server-TestNetworkNat (cc45c612eb285bb1b52152305cf3d155ee7c547e2d1967575b4bc271d3be81f3):
    Error starting userland proxy:
    error while calling PortManager.AddPort(): listen tcp 0.0.0.0:8080: bind: address already in use

=== FAIL: amd64.integration.container TestNetworkLocalhostTCPNat (0.13s)
    nat_test.go:48: assertion failed: error is not nil: Error response from daemon:
    driver failed programming external connectivity on endpoint server-TestNetworkLocalhostTCPNat (90323fcd8d614dfd8cdc69df6727dd9d9a54911c7a12db548adef4e31bbb42cb):
    Error starting userland proxy:
    error while calling PortManager.AddPort(): listen tcp 0.0.0.0:8081: bind: address already in use

=== FAIL: amd64.integration.container TestNetworkLoopbackNat (0.13s)
    nat_test.go:66: assertion failed: error is not nil: Error response from daemon:
    driver failed programming external connectivity on endpoint server-TestNetworkLoopbackNat (81d16c3d777b5723524da166ecb20e04f7305a1415499fd579035f7ca201916c):
    Error starting userland proxy:
    error while calling PortManager.AddPort(): listen tcp 0.0.0.0:8080: bind: address already in use
```

Wondering if it's an issue in rootless kit (failing to distinguish `[::]:8080` from `0.0.0.0:8080`, or libnetwork not releasing the port (but in that case, I'd expect it to fail in non-rootless as well)

**Comment by thaJeztah** [comment]
@AkihiroSuda do you have an idea what causes the failure on rootless? (port already in use)? Could it be it's somewhere conflating ipv4 and ipv6 (and trying to bind twice on ipv4?).

I tried checking if the ports were in use at the start of the tests (they weren't), so it happens when starting the container that's starred in the test)

**Comment by AkihiroSuda** [comment]
```console
$ docker --context=rootless run --rm -p 8080:80 nginx:alpine
docker: Error response from daemon: driver failed programming external connectivity on endpoint vigorous_archimedes (8ca94868817b1f0398ae1c96aa4caa3eedc60753b826797ce164fa33a159a966): Error starting userland proxy: error while calling PortManager.AddPort(): listen tcp 0.0.0.0:8080: bind: address already in use.
```

```console
$ sudo execsnoop.bt 
Attaching 2 probes...
TIME(ms)   PID   ARGS
22491      43131 docker --context=rootless run --rm -p 8080:80 nginx:alpine
22542      43141 /sbin/iptables --wait -t nat -C DOCKER -p tcp -d 0/0 --dport 8080 -j DNAT --to-destination 172.17.0.2:80
22545      43142 /sbin/iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 8080 -j DNAT --to-destination 172.17.0.2:80
22547      43143 /sbin/iptables --wait -t filter -C DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport
22548      43144 /sbin/iptables --wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport
22550      43145 /sbin/iptables --wait -t nat -C POSTROUTING -p tcp -s 172.17.0.2 -d 172.17.0.2 --dport 80 -j MASQUERADE
22551      43146 /sbin/iptables --wait -t nat -A POSTROUTING -p tcp -s 172.17.0.2 -d 172.17.0.2 --dport 80 -j MASQUERADE
22553      43147 /usr/local/bin/rootlesskit-docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 8080 -container-ip 172.17.0.2 -container-port 80
22555      43152 docker-proxy -container-ip 172.17.0.2 -container-port 80 -host-ip 127.0.0.1 -host-port 8080 -proto tcp
22556      43160 /usr/local/bin/rootlesskit-docker-proxy -proto tcp -host-ip :: -host-port 8080 -container-ip 172.17.0.2 -container-port 80
22564      43167 /sbin/iptables --wait -t nat -C DOCKER -p tcp -d 0/0 --dport 8080 -j DNAT --to-destination 172.17.0.2:80
22568      43168 /sbin/iptables --wait -t nat -D DOCKER -p tcp -d 0/0 --dport 8080 -j DNAT --to-destination 172.17.0.2:80
22571      43169 /sbin/iptables --wait -t filter -C DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport
22573      43170 /sbin/iptables --wait -t filter -D DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport
22574      43171 /sbin/iptables --wait -t nat -C POSTROUTING -p tcp -s 172.17.0.2 -d 172.17.0.2 --dport 80 -j MASQUERADE
22576      43172 /sbin/iptables --wait -t nat -D POSTROUTING -p tcp -s 172.17.0.2 -d 172.17.0.2 --dport 80 -j MASQUERADE
```

`rootlesskit-docker-proxy` is unexpectedly called twice:
```
/usr/local/bin/rootlesskit-docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 8080 -container-ip 172.17.0.2 -container-port 80
/usr/local/bin/rootlesskit-docker-proxy -proto tcp -host-ip :: -host-port 8080 -container-ip 172.17.0.2 -container-port 80
```

Seems a bug on libnetwork side.

**Comment by arkodg** [comment]
@AkihiroSuda the behavior in libnetwork has recently changed to spawn a separate `docker-proxy` process for each port binding type - ipv4 & ipv6, this might look non optimal when in userland-proxy mode, but enables creating  correct port forwarding rules for `ipv4` and `ipv6` bindings using `iptables` & `ip6tables` respectively

**Comment by AkihiroSuda** [comment]
Opened https://github.com/rootless-containers/rootlesskit/issues/231 for discussion

**Comment by AkihiroSuda** [comment]
Please try this version of RootlessKit: https://github.com/rootless-containers/rootlesskit/pull/232

**Comment by thaJeztah** [comment]
included https://github.com/moby/moby/pull/42102 to test

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
Rebased; this should be ready for review: @AkihiroSuda @tonistiigi @tiborvass @cpuguy83 ptal

File: integration-cli/docker_cli_port_test.go [hunk 1]
```diff
@@ -161,7 +175,7 @@ func assertPortList(c *testing.T, out string, expected []string) error {
 	// of the CLI used an incorrect output format for mappings on IPv6 addresses
 	// for example, "80/tcp -> :::80" instead of "80/tcp -> [::]:80".
 	oldFormat := func(mapping string) string {
-		old := strings.Replace(mapping, "-> [", "-> ", 1)
+		old := strings.Replace(mapping, "[", "", 1)
```
Comment (thaJeztah) [inline integration-cli/docker_cli_port_test.go:178]: I made the normalisation too strict in https://github.com/moby/moby/pull/42050, and forgot the "expected" format was sometimes passed as a "full" format (`80/tcp -> [::]:80`), and sometimes only the mapping (`[::]:80`); pushed this fix as a separate commit in this PR, but I can move to a separate PR if we think that makes more sense

**Comment by thaJeztah** [comment]
ok this is all green now; also prepared a draft backport for 20.10 https://github.com/moby/moby/pull/42205

**Review by tiborvass — APPROVED** [review]
