### PR TITLE
Fix integration-cli daemon restart with user namespaces enabled

### LINKED ISSUE #17472: userns: containers will not restart if started with --restart always
daemon logs:

```
time="2015-10-29T05:53:21Z" level=warning msg="Running experimental build" 
time="2015-10-29T05:53:21.347580825Z" level=debug msg="docker group found. gid: 999" 
time="2015-10-29T05:53:21.347602142Z" level=debug msg="Server created for HTTP on unix (/go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/docker.sock)" 
time="2015-10-29T05:53:21.347837765Z" level=info msg="API listen on /go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/docker.sock" 
time="2015-10-29T05:53:21.347869738Z" level=info msg="User namespaces: ID ranges will be mapped to subuid/subgid ranges of: dockremap:dockremap" 
time="2015-10-29T05:53:21.348005849Z" level=debug msg="Creating actual daemon root: /go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536" 
time="2015-10-29T05:53:21.348145278Z" level=debug msg="[graphdriver] trying provided driver \"vfs\"" 
time="2015-10-29T05:53:21.348204597Z" level=debug msg="Using graph driver vfs" 
time="2015-10-29T05:53:21.348213953Z" level=debug msg="Using default logging driver json-file" 
time="2015-10-29T05:53:21.348258293Z" level=debug msg="Creating images graph" 
time="2015-10-29T05:53:21.348330889Z" level=debug msg="Restored 0 elements" 
time="2015-10-29T05:53:21.348520120Z" level=debug msg="Creating repository list" 
time="2015-10-29T05:53:21.348584768Z" level=debug msg="Option DefaultDriver: bridge" 
time="2015-10-29T05:53:21.348593309Z" level=debug msg="Option DefaultNetwork: bridge" 
time="2015-10-29T05:53:21.349706235Z" level=warning msg="Running modprobe bridge br_netfilter failed with message: modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/4.2.5-fsociety/modules.dep.bin'\nmodprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/4.2.5-fsociety/modules.dep.bin'\n, error: exit status 1" 
time="2015-10-29T05:53:21.350548917Z" level=warning msg="Running modprobe nf_nat failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/4.2.5-fsociety/modules.dep.bin'`, error: exit status 1" 
time="2015-10-29T05:53:21.350610501Z" level=debug msg="Fail to initialize firewalld: Failed to connect to D-Bus system bus: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory, using raw iptables instead" 
time="2015-10-29T05:53:21.351503456Z" level=debug msg="/sbin/iptables, [--wait -t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]" 
time="2015-10-29T05:53:21.352361096Z" level=debug msg="/sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER]" 
time="2015-10-29T05:53:21.353177209Z" level=debug msg="/sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER]" 
time="2015-10-29T05:53:21.354030722Z" level=debug msg="/sbin/iptables, [--wait -t nat -D PREROUTING]" 
time="2015-10-29T05:53:21.354806558Z" level=debug msg="/sbin/iptables, [--wait -t nat -D OUTPUT]" 
time="2015-10-29T05:53:21.355621041Z" level=debug msg="/sbin/iptables, [--wait -t nat -F DOCKER]" 
time="2015-10-29T05:53:21.356393524Z" level=debug msg="/sbin/iptables, [--wait -t nat -X DOCKER]" 
time="2015-10-29T05:53:21.513943874Z" level=debug msg="/sbin/iptables, [--wait -t nat -n -L DOCKER]" 
time="2015-10-29T05:53:21.515213194Z" level=debug msg="/sbin/iptables, [--wait -t nat -N DOCKER]" 
time="2015-10-29T05:53:21.516824457Z" level=debug msg="/sbin/iptables, [--wait -t filter -n -L DOCKER]" 
time="2015-10-29T05:53:21.518562638Z" level=debug msg="Registering ipam provider: default" 
time="2015-10-29T05:53:21.589164291Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.18.0.1/16. Daemon option --bip can be used to set a preferred IP address" 
time="2015-10-29T05:53:21.589214904Z" level=debug msg="Allocating IPv4 pools for network bridge (9dc5f015b9ea058bf78689bcd88e9bc7351d28840299e3535d26cfaa73422258)" 
time="2015-10-29T05:53:21.589235191Z" level=debug msg="RequestPool(LocalDefault, 172.18.0.1/16, , map[], false)" 
time="2015-10-29T05:53:21.766446928Z" level=debug msg="RequestAddress(LocalDefault/172.18.0.0/16, 172.18.0.1, map[])" 
time="2015-10-29T05:53:21.800577551Z" level=debug msg="/sbin/iptables, [--wait -t nat -C POSTROUTING -s 172.18.0.0/16 ! -o docker0 -j MASQUERADE]" 
time="2015-10-29T05:53:21.801771521Z" level=debug msg="/sbin/iptables, [--wait -D FORWARD -i docker0 -o docker0 -j DROP]" 
time="2015-10-29T05:53:21.802601266Z" level=debug msg="/sbin/iptables, [--wait -t filter -C FORWARD -i docker0 -o docker0 -j ACCEPT]" 
time="2015-10-29T05:53:21.803447627Z" level=debug msg="/sbin/iptables, [--wait -t filter -C FORWARD -i docker0 ! -o docker0 -j ACCEPT]" 
time="2015-10-29T05:53:21.804268830Z" level=debug msg="/sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT]" 
time="2015-10-29T05:53:21.805139925Z" level=debug msg="/sbin/iptables, [--wait -t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]" 
time="2015-10-29T05:53:21.806814499Z" level=debug msg="/sbin/iptables, [--wait -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]" 
time="2015-10-29T05:53:21.807700939Z" level=debug msg="/sbin/iptables, [--wait -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8]" 
time="2015-10-29T05:53:21.809359691Z" level=debug msg="/sbin/iptables, [--wait -t nat -A OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8]" 
time="2015-10-29T05:53:21.810260302Z" level=debug msg="/sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -j DOCKER]" 
time="2015-10-29T05:53:22.024991166Z" level=debug msg="Cleaning up old shm/mqueue mounts: start." 
time="2015-10-29T05:53:22.025242731Z" level=debug msg="Cleaning up old shm/mqueue mounts: done." 
time="2015-10-29T05:53:22.025488369Z" level=info msg="Daemon has completed initialization" 
time="2015-10-29T05:53:22.025524515Z" level=info msg="Docker daemon" commit=44da861-dirty execdriver=native-0.2 graphdriver=vfs version=1.9.0-dev 
time="2015-10-29T05:53:22.027646122Z" level=debug msg="Registering routers" 
time="2015-10-29T05:53:22.027704384Z" level=debug msg="Registering HEAD, /containers/{name:.*}/archive" 
time="2015-10-29T05:53:22.028047102Z" level=debug msg="Registering OPTIONS, /" 
time="2015-10-29T05:53:22.028197827Z" level=debug msg="Registering GET, /_ping" 
time="2015-10-29T05:53:22.028361552Z" level=debug msg="Registering GET, /events" 
time="2015-10-29T05:53:22.028544146Z" level=debug msg="Registering GET, /info" 
time="2015-10-29T05:53:22.028701692Z" level=debug msg="Registering GET, /version" 
time="2015-10-29T05:53:22.028877817Z" level=debug msg="Registering GET, /images/json" 
time="2015-10-29T05:53:22.029137141Z" level=debug msg="Registering GET, /images/search" 
time="2015-10-29T05:53:22.029493419Z" level=debug msg="Registering GET, /images/get" 
time="2015-10-29T05:53:22.029856330Z" level=debug msg="Registering GET, /images/{name:.*}/get" 
time="2015-10-29T05:53:22.030370759Z" level=debug msg="Registering GET, /images/{name:.*}/history" 
time="2015-10-29T05:53:22.030782012Z" level=debug msg="Registering GET, /images/{name:.*}/json" 
time="2015-10-29T05:53:22.031051210Z" level=debug msg="Registering GET, /containers/json" 
time="2015-10-29T05:53:22.032600909Z" level=debug msg="Registering GET, /containers/{name:.*}/export" 
time="2015-10-29T05:53:22.032956729Z" level=debug msg="Registering GET, /containers/{name:.*}/changes" 
time="2015-10-29T05:53:22.033346573Z" level=debug msg="Registering GET, /containers/{name:.*}/json" 
time="2015-10-29T05:53:22.033658710Z" level=debug msg="Registering GET, /containers/{name:.*}/top" 
time="2015-10-29T05:53:22.033975686Z" level=debug msg="Registering GET, /containers/{name:.*}/logs" 
time="2015-10-29T05:53:22.034279455Z" level=debug msg="Registering GET, /containers/{name:.*}/stats" 
time="2015-10-29T05:53:22.034595356Z" level=debug msg="Registering GET, /containers/{name:.*}/attach/ws" 
time="2015-10-29T05:53:22.034977392Z" level=debug msg="Registering GET, /exec/{id:.*}/json" 
time="2015-10-29T05:53:22.035689998Z" level=debug msg="Registering GET, /containers/{name:.*}/archive" 
time="2015-10-29T05:53:22.036230814Z" level=debug msg="Registering GET, /volumes" 
time="2015-10-29T05:53:22.036332984Z" level=debug msg="Registering GET, /volumes/{name:.*}" 
time="2015-10-29T05:53:22.036478635Z" level=debug msg="Registering POST, /auth" 
time="2015-10-29T05:53:22.036560141Z" level=debug msg="Registering POST, /commit" 
time="2015-10-29T05:53:22.036625835Z" level=debug msg="Registering POST, /build" 
time="2015-10-29T05:53:22.036680184Z" level=debug msg="Registering POST, /images/create" 
time="2015-10-29T05:53:22.036748048Z" level=debug msg="Registering POST, /images/load" 
time="2015-10-29T05:53:22.036806063Z" level=debug msg="Registering POST, /images/{name:.*}/push" 
time="2015-10-29T05:53:22.036893598Z" level=debug msg="Registering POST, /images/{name:.*}/tag" 
time="2015-10-29T05:53:22.036970253Z" level=debug msg="Registering POST, /containers/create" 
time="2015-10-29T05:53:22.037039295Z" level=debug msg="Registering POST, /containers/{name:.*}/kill" 
time="2015-10-29T05:53:22.037123711Z" level=debug msg="Registering POST, /containers/{name:.*}/pause" 
time="2015-10-29T05:53:22.037268436Z" level=debug msg="Registering POST, /containers/{name:.*}/unpause" 
time="2015-10-29T05:53:22.037412003Z" level=debug msg="Registering POST, /containers/{name:.*}/restart" 
time="2015-10-29T05:53:22.037561144Z" level=debug msg="Registering POST, /containers/{name:.*}/start" 
time="2015-10-29T05:53:22.037695028Z" level=debug msg="Registering POST, /containers/{name:.*}/stop" 
time="2015-10-29T05:53:22.037840344Z" level=debug msg="Registering POST, /containers/{name:.*}/wait" 
time="2015-10-29T05:53:22.037979768Z" level=debug msg="Registering POST, /containers/{name:.*}/resize" 
time="2015-10-29T05:53:22.038130033Z" level=debug msg="Registering POST, /containers/{name:.*}/attach" 
time="2015-10-29T05:53:22.038273461Z" level=debug msg="Registering POST, /containers/{name:.*}/copy" 
time="2015-10-29T05:53:22.038419242Z" level=debug msg="Registering POST, /containers/{name:.*}/exec" 
time="2015-10-29T05:53:22.038550424Z" level=debug msg="Registering POST, /exec/{name:.*}/start" 
time="2015-10-29T05:53:22.038693952Z" level=debug msg="Registering POST, /exec/{name:.*}/resize" 
time="2015-10-29T05:53:22.038802587Z" level=debug msg="Registering POST, /containers/{name:.*}/rename" 
time="2015-10-29T05:53:22.038888711Z" level=debug msg="Registering POST, /volumes/create" 
time="2015-10-29T05:53:22.038948560Z" level=debug msg="Registering PUT, /containers/{name:.*}/archive" 
time="2015-10-29T05:53:22.039028175Z" level=debug msg="Registering DELETE, /containers/{name:.*}" 
time="2015-10-29T05:53:22.039140754Z" level=debug msg="Registering DELETE, /images/{name:.*}" 
time="2015-10-29T05:53:22.039218561Z" level=debug msg="Registering DELETE, /volumes/{name:.*}" 
time="2015-10-29T05:53:22.039296624Z" level=debug msg="Registering GET, /networks" 
time="2015-10-29T05:53:22.039347752Z" level=debug msg="Registering GET, /networks/{id:.*}" 
time="2015-10-29T05:53:22.039421565Z" level=debug msg="Registering POST, /networks/create" 
time="2015-10-29T05:53:22.039495605Z" level=debug msg="Registering POST, /networks/{id:.*}/connect" 
time="2015-10-29T05:53:22.039580923Z" level=debug msg="Registering POST, /networks/{id:.*}/disconnect" 
time="2015-10-29T05:53:22.039674470Z" level=debug msg="Registering DELETE, /networks/{id:.*}" 
time="2015-10-29T05:53:22.040020127Z" level=debug msg="Calling GET /_ping" 
time="2015-10-29T05:53:22.040038332Z" level=info msg="GET /_ping" 
time="2015-10-29T05:53:22.040462592Z" level=debug msg="Calling GET /info" 
time="2015-10-29T05:53:22.040484693Z" level=info msg="GET /info" 
time="2015-10-29T05:53:22.105677184Z" level=debug msg="Calling POST /v1.22/images/load" 
time="2015-10-29T05:53:22.105713058Z" level=info msg="POST /v1.22/images/load" 
time="2015-10-29T05:53:22.129056312Z" level=debug msg="Loading cfa753dfea5e68a24366dfba16e6edf573daa447abf65bc11619c1a98a3aff54" 
time="2015-10-29T05:53:22.129591328Z" level=debug msg="Start untar layer" 
time="2015-10-29T05:53:22.176260680Z" level=debug msg="Untar time: 0.046656842000000004s" 
time="2015-10-29T05:53:22.177086487Z" level=debug msg="Completed processing cfa753dfea5e68a24366dfba16e6edf573daa447abf65bc11619c1a98a3aff54" 
time="2015-10-29T05:53:22.177128501Z" level=debug msg="Loading d7057cb020844f245031d27b76cb18af05db1cc3a96a29fa7777af75f5ac91a3" 
time="2015-10-29T05:53:22.177403807Z" level=debug msg="Creating dest directory: /go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536/vfs/dir/d7057cb020844f245031d27b76cb18af05db1cc3a96a29fa7777af75f5ac91a3" 
time="2015-10-29T05:53:22.177422299Z" level=debug msg="Calling TarUntar(/go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536/vfs/dir/cfa753dfea5e68a24366dfba16e6edf573daa447abf65bc11619c1a98a3aff54, /go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536/vfs/dir/d7057cb020844f245031d27b76cb18af05db1cc3a96a29fa7777af75f5ac91a3)" 
time="2015-10-29T05:53:22.177436838Z" level=debug msg="TarUntar(/go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536/vfs/dir/cfa753dfea5e68a24366dfba16e6edf573daa447abf65bc11619c1a98a3aff54 /go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536/vfs/dir/d7057cb020844f245031d27b76cb18af05db1cc3a96a29fa7777af75f5ac91a3)" 
time="2015-10-29T05:53:22.211205231Z" level=debug msg="Start untar layer" 
time="2015-10-29T05:53:22.233816936Z" level=debug msg="Untar time: 0.022606650000000002s" 
time="2015-10-29T05:53:22.234143951Z" level=debug msg="Completed processing d7057cb020844f245031d27b76cb18af05db1cc3a96a29fa7777af75f5ac91a3" 
time="2015-10-29T05:53:22.262278695Z" level=debug msg="Calling POST /v1.22/containers/create" 
time="2015-10-29T05:53:22.262588460Z" level=debug msg="form data: map[\"AttachStdout\":%!q(bool=false) \"HostConfig\":map[\"MemoryReservation\":%!q(float64=0) \"CpuPeriod\":%!q(float64=0) \"CpusetCpus\":\"\" \"CpuQuota\":%!q(float64=0) \"Dns\":<nil> \"VolumesFrom\":<nil> \"UTSMode\":\"\" \"ContainerIDFile\":\"\" \"GroupAdd\":<nil> \"LxcConf\":[] \"BlkioWeight\":%!q(float64=0) \"DnsOptions\":<nil> \"CgroupParent\":\"\" \"Binds\":<nil> \"IpcMode\":\"\" \"CpuShares\":%!q(float64=0) \"PublishAllPorts\":%!q(bool=false) \"Devices\":[] \"PidMode\":\"\" \"CapAdd\":<nil> \"Ulimits\":<nil> \"MemorySwappiness\":%!q(float64=-1) \"ReadonlyRootfs\":%!q(bool=false) \"LogConfig\":map[\"Type\":\"\" \"Config\":map[]] \"SecurityOpt\":<nil> \"Privileged\":%!q(bool=false) \"Links\":<nil> \"DnsSearch\":<nil> \"RestartPolicy\":map[\"Name\":\"always\" \"MaximumRetryCount\":%!q(float64=0)] \"OomKillDisable\":%!q(bool=false) \"CpusetMems\":\"\" \"PortBindings\":map[\"80/tcp\":[map[\"HostIp\":\"\" \"HostPort\":\"\"]]] \"ExtraHosts\":<nil> \"MemorySwap\":%!q(float64=0) \"KernelMemory\":%!q(float64=0) \"NetworkMode\":\"default\" \"CapDrop\":<nil> \"ConsoleSize\":[%!q(float64=0) %!q(float64=0)] \"VolumeDriver\":\"\" \"Memory\":%!q(float64=0)] \"AttachStdin\":%!q(bool=false) \"User\":\"\" \"StdinOnce\":%!q(bool=false) \"Image\":\"busybox:latest\" \"OnBuild\":<nil> \"Domainname\":\"\" \"Env\":[] \"WorkingDir\":\"\" \"StopSignal\":\"SIGTERM\" \"Tty\":%!q(bool=false) \"AttachStderr\":%!q(bool=false) \"ExposedPorts\":map[\"80/tcp\":map[]] \"OpenStdin\":%!q(bool=false) \"Cmd\":[\"top\"] \"Volumes\":map[] \"Entrypoint\":<nil> \"Labels\":map[] \"Hostname\":\"\"]" 
time="2015-10-29T05:53:22.262628736Z" level=info msg="POST /v1.22/containers/create?name=top1" 
time="2015-10-29T05:53:22.337432168Z" level=debug msg="Creating dest directory: /go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536/vfs/dir/8b672c663113e2480cb636775da8b068f66d0976cc3cd9761e72d14adaab4c53-init" 
time="2015-10-29T05:53:22.337467397Z" level=debug msg="Calling TarUntar(/go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536/vfs/dir/d7057cb020844f245031d27b76cb18af05db1cc3a96a29fa7777af75f5ac91a3, /go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536/vfs/dir/8b672c663113e2480cb636775da8b068f66d0976cc3cd9761e72d14adaab4c53-init)" 
time="2015-10-29T05:53:22.337490320Z" level=debug msg="TarUntar(/go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536/vfs/dir/d7057cb020844f245031d27b76cb18af05db1cc3a96a29fa7777af75f5ac91a3 /go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536/vfs/dir/8b672c663113e2480cb636775da8b068f66d0976cc3cd9761e72d14adaab4c53-init)" 
time="2015-10-29T05:53:22.371778504Z" level=debug msg="Creating dest directory: /go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536/vfs/dir/8b672c663113e2480cb636775da8b068f66d0976cc3cd9761e72d14adaab4c53" 
time="2015-10-29T05:53:22.371815399Z" level=debug msg="Calling TarUntar(/go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536/vfs/dir/8b672c663113e2480cb636775da8b068f66d0976cc3cd9761e72d14adaab4c53-init, /go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536/vfs/dir/8b672c663113e2480cb636775da8b068f66d0976cc3cd9761e72d14adaab4c53)" 
time="2015-10-29T05:53:22.371830035Z" level=debug msg="TarUntar(/go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536/vfs/dir/8b672c663113e2480cb636775da8b068f66d0976cc3cd9761e72d14adaab4c53-init /go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536/vfs/dir/8b672c663113e2480cb636775da8b068f66d0976cc3cd9761e72d14adaab4c53)" 
time="2015-10-29T05:53:22.412539948Z" level=debug msg="Calling POST /v1.22/containers/8b672c663113e2480cb636775da8b068f66d0976cc3cd9761e72d14adaab4c53/start" 
time="2015-10-29T05:53:22.412580036Z" level=info msg="POST /v1.22/containers/8b672c663113e2480cb636775da8b068f66d0976cc3cd9761e72d14adaab4c53/start" 
time="2015-10-29T05:53:22.439862164Z" level=debug msg="Assigning addresses for endpoint top1's interface on network bridge" 
time="2015-10-29T05:53:22.439916231Z" level=debug msg="RequestAddress(LocalDefault/172.18.0.0/16, <nil>, map[])" 
time="2015-10-29T05:53:22.494531205Z" level=debug msg="/sbin/iptables, [--wait -t nat -A DOCKER -p tcp -d 0/0 --dport 32768 -j DNAT --to-destination 172.18.0.2:80 ! -i docker0]" 
time="2015-10-29T05:53:22.496878206Z" level=debug msg="/sbin/iptables, [--wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.18.0.2 --dport 80 -j ACCEPT]" 
time="2015-10-29T05:53:22.499150984Z" level=debug msg="/sbin/iptables, [--wait -t nat -A POSTROUTING -p tcp -s 172.18.0.2 -d 172.18.0.2 --dport 80 -j MASQUERADE]" 
time="2015-10-29T05:53:22.795008967Z" level=info msg="Processing signal 'interrupt'" 
time="2015-10-29T05:53:22.795151008Z" level=debug msg="starting clean shutdown of all containers..." 
time="2015-10-29T05:53:22.795196231Z" level=debug msg="stopping 8b672c663113e2480cb636775da8b068f66d0976cc3cd9761e72d14adaab4c53" 
time="2015-10-29T05:53:22.795222638Z" level=debug msg="Sending 15 to 8b672c663113e2480cb636775da8b068f66d0976cc3cd9761e72d14adaab4c53" 
time="2015-10-29T05:53:23.007626165Z" level=debug msg="/sbin/iptables, [--wait -t nat -D DOCKER -p tcp -d 0/0 --dport 32768 -j DNAT --to-destination 172.18.0.2:80 ! -i docker0]" 
time="2015-10-29T05:53:23.009257245Z" level=debug msg="/sbin/iptables, [--wait -t filter -D DOCKER ! -i docker0 -o docker0 -p tcp -d 172.18.0.2 --dport 80 -j ACCEPT]" 
time="2015-10-29T05:53:23.010593900Z" level=debug msg="/sbin/iptables, [--wait -t nat -D POSTROUTING -p tcp -s 172.18.0.2 -d 172.18.0.2 --dport 80 -j MASQUERADE]" 
time="2015-10-29T05:53:23.031205165Z" level=debug msg="Releasing addresses for endpoint top1's interface on network bridge" 
time="2015-10-29T05:53:23.031254226Z" level=debug msg="ReleaseAddress(LocalDefault/172.18.0.0/16, 172.18.0.2)" 
time="2015-10-29T05:53:23.143641017Z" level=debug msg="container stopped 8b672c663113e2480cb636775da8b068f66d0976cc3cd9761e72d14adaab4c53" 
time="2015-10-29T05:53:23.143829583Z" level=debug msg="Cleaning up old shm/mqueue mounts: start." 
time="2015-10-29T05:53:23.143997315Z" level=debug msg="Unix socket /var/lib/docker/network/files/dcbfc5e3667dc398fe7246ea048bb231a2765995b3bcceec183bfdb7564a35f4.sock doesnt exist. cannot accept client connections" 
time="2015-10-29T05:53:23.144051800Z" level=debug msg="Cleaning up old shm/mqueue mounts: done." 
time="2015-10-29T05:53:23.144077494Z" level=debug msg="Clean shutdown succeeded" 
time="2015-10-29T05:53:23Z" level=warning msg="Running experimental build" 
time="2015-10-29T05:53:23.166117958Z" level=debug msg="docker group found. gid: 999" 
time="2015-10-29T05:53:23.166139127Z" level=debug msg="Server created for HTTP on unix (/go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/docker.sock)" 
time="2015-10-29T05:53:23.166363059Z" level=info msg="API listen on /go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/docker.sock" 
time="2015-10-29T05:53:23.166425114Z" level=info msg="User namespaces: ID ranges will be mapped to subuid/subgid ranges of: dockremap:dockremap" 
time="2015-10-29T05:53:23.166666685Z" level=debug msg="Creating actual daemon root: /go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536/165536.165536" 
time="2015-10-29T05:53:23.166806256Z" level=debug msg="[graphdriver] trying provided driver \"vfs\"" 
time="2015-10-29T05:53:23.166863140Z" level=debug msg="Using graph driver vfs" 
time="2015-10-29T05:53:23.166872923Z" level=debug msg="Using default logging driver json-file" 
time="2015-10-29T05:53:23.166927122Z" level=debug msg="Creating images graph" 
time="2015-10-29T05:53:23.166998613Z" level=debug msg="Restored 0 elements" 
time="2015-10-29T05:53:23.167199988Z" level=debug msg="Creating repository list" 
time="2015-10-29T05:53:23.167266000Z" level=debug msg="Option DefaultDriver: bridge" 
time="2015-10-29T05:53:23.167274774Z" level=debug msg="Option DefaultNetwork: bridge" 
time="2015-10-29T05:53:23.168374494Z" level=warning msg="Running modprobe bridge br_netfilter failed with message: modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/4.2.5-fsociety/modules.dep.bin'\nmodprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/4.2.5-fsociety/modules.dep.bin'\n, error: exit status 1" 
time="2015-10-29T05:53:23.169290217Z" level=warning msg="Running modprobe nf_nat failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/4.2.5-fsociety/modules.dep.bin'`, error: exit status 1" 
time="2015-10-29T05:53:23.169356772Z" level=debug msg="Fail to initialize firewalld: Failed to connect to D-Bus system bus: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory, using raw iptables instead" 
time="2015-10-29T05:53:23.170303295Z" level=debug msg="/sbin/iptables, [--wait -t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]" 
time="2015-10-29T05:53:23.171204142Z" level=debug msg="/sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER]" 
time="2015-10-29T05:53:23.172189831Z" level=debug msg="/sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER]" 
time="2015-10-29T05:53:23.173017128Z" level=debug msg="/sbin/iptables, [--wait -t nat -D PREROUTING]" 
time="2015-10-29T05:53:23.173746668Z" level=debug msg="/sbin/iptables, [--wait -t nat -D OUTPUT]" 
time="2015-10-29T05:53:23.174540195Z" level=debug msg="/sbin/iptables, [--wait -t nat -F DOCKER]" 
time="2015-10-29T05:53:23.175377731Z" level=debug msg="/sbin/iptables, [--wait -t nat -X DOCKER]" 
time="2015-10-29T05:53:23.210374083Z" level=debug msg="/sbin/iptables, [--wait -t nat -n -L DOCKER]" 
time="2015-10-29T05:53:23.211449974Z" level=debug msg="/sbin/iptables, [--wait -t nat -N DOCKER]" 
time="2015-10-29T05:53:23.212327301Z" level=debug msg="/sbin/iptables, [--wait -t filter -n -L DOCKER]" 
time="2015-10-29T05:53:23.213215247Z" level=debug msg="Registering ipam provider: default" 
time="2015-10-29T05:53:23.300147175Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.18.0.1/16. Daemon option --bip can be used to set a preferred IP address" 
time="2015-10-29T05:53:23.300197294Z" level=debug msg="Allocating IPv4 pools for network bridge (9fe8ee81b4e9c5bd3dbc9ad74f428ca8623028c5da16a84745c155398427581b)" 
time="2015-10-29T05:53:23.300213983Z" level=debug msg="RequestPool(LocalDefault, 172.18.0.1/16, , map[], false)" 
time="2015-10-29T05:53:23.517903581Z" level=debug msg="RequestAddress(LocalDefault/172.18.0.0/16, 172.18.0.1, map[])" 
time="2015-10-29T05:53:23.554505288Z" level=debug msg="/sbin/iptables, [--wait -t nat -C POSTROUTING -s 172.18.0.0/16 ! -o docker0 -j MASQUERADE]" 
time="2015-10-29T05:53:23.555642841Z" level=debug msg="/sbin/iptables, [--wait -D FORWARD -i docker0 -o docker0 -j DROP]" 
time="2015-10-29T05:53:23.556441506Z" level=debug msg="/sbin/iptables, [--wait -t filter -C FORWARD -i docker0 -o docker0 -j ACCEPT]" 
time="2015-10-29T05:53:23.557256457Z" level=debug msg="/sbin/iptables, [--wait -t filter -C FORWARD -i docker0 ! -o docker0 -j ACCEPT]" 
time="2015-10-29T05:53:23.558081404Z" level=debug msg="/sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT]" 
time="2015-10-29T05:53:23.558943975Z" level=debug msg="/sbin/iptables, [--wait -t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]" 
time="2015-10-29T05:53:23.560643808Z" level=debug msg="/sbin/iptables, [--wait -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]" 
time="2015-10-29T05:53:23.562055673Z" level=debug msg="/sbin/iptables, [--wait -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8]" 
time="2015-10-29T05:53:23.564691146Z" level=debug msg="/sbin/iptables, [--wait -t nat -A OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8]" 
time="2015-10-29T05:53:23.566220340Z" level=debug msg="/sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -j DOCKER]" 
time="2015-10-29T05:53:23.804027375Z" level=debug msg="Cleaning up old shm/mqueue mounts: start." 
time="2015-10-29T05:53:23.804190652Z" level=debug msg="Cleaning up old shm/mqueue mounts: done." 
time="2015-10-29T05:53:23.804580689Z" level=info msg="Daemon has completed initialization" 
time="2015-10-29T05:53:23.804668618Z" level=info msg="Docker daemon" commit=44da861-dirty execdriver=native-0.2 graphdriver=vfs version=1.9.0-dev 
time="2015-10-29T05:53:23.806732254Z" level=debug msg="Registering routers" 
time="2015-10-29T05:53:23.806759205Z" level=debug msg="Registering HEAD, /containers/{name:.*}/archive" 
time="2015-10-29T05:53:23.807604998Z" level=debug msg="Registering OPTIONS, /" 
time="2015-10-29T05:53:23.808042535Z" level=debug msg="Registering GET, /_ping" 
time="2015-10-29T05:53:23.808443000Z" level=debug msg="Registering GET, /events" 
time="2015-10-29T05:53:23.808905765Z" level=debug msg="Registering GET, /info" 
time="2015-10-29T05:53:23.809051590Z" level=debug msg="Registering GET, /version" 
time="2015-10-29T05:53:23.809428197Z" level=debug msg="Registering GET, /images/json" 
time="2015-10-29T05:53:23.809607725Z" level=debug msg="Registering GET, /images/search" 
time="2015-10-29T05:53:23.809995637Z" level=debug msg="Registering GET, /images/get" 
time="2015-10-29T05:53:23.810287375Z" level=debug msg="Registering GET, /images/{name:.*}/get" 
time="2015-10-29T05:53:23.810568335Z" level=debug msg="Registering GET, /images/{name:.*}/history" 
time="2015-10-29T05:53:23.811036752Z" level=debug msg="Registering GET, /images/{name:.*}/json" 
time="2015-10-29T05:53:23.811476021Z" level=debug msg="Registering GET, /containers/json" 
time="2015-10-29T05:53:23.811706151Z" level=debug msg="Registering GET, /containers/{name:.*}/export" 
time="2015-10-29T05:53:23.812001242Z" level=debug msg="Registering GET, /containers/{name:.*}/changes" 
time="2015-10-29T05:53:23.812410549Z" level=debug msg="Registering GET, /containers/{name:.*}/json" 
time="2015-10-29T05:53:23.812810344Z" level=debug msg="Registering GET, /containers/{name:.*}/top" 
time="2015-10-29T05:53:23.813208967Z" level=debug msg="Registering GET, /containers/{name:.*}/logs" 
time="2015-10-29T05:53:23.813932747Z" level=debug msg="Registering GET, /containers/{name:.*}/stats" 
time="2015-10-29T05:53:23.814469282Z" level=debug msg="Registering GET, /containers/{name:.*}/attach/ws" 
time="2015-10-29T05:53:23.818000903Z" level=debug msg="Registering GET, /exec/{id:.*}/json" 
time="2015-10-29T05:53:23.818171684Z" level=debug msg="Registering GET, /containers/{name:.*}/archive" 
time="2015-10-29T05:53:23.818579880Z" level=debug msg="Registering GET, /volumes" 
time="2015-10-29T05:53:23.818677826Z" level=debug msg="Registering GET, /volumes/{name:.*}" 
time="2015-10-29T05:53:23.818780566Z" level=debug msg="Registering POST, /auth" 
time="2015-10-29T05:53:23.818841832Z" level=debug msg="Registering POST, /commit" 
time="2015-10-29T05:53:23.818923924Z" level=debug msg="Registering POST, /build" 
time="2015-10-29T05:53:23.819001310Z" level=debug msg="Registering POST, /images/create" 
time="2015-10-29T05:53:23.819062325Z" level=debug msg="Registering POST, /images/load" 
time="2015-10-29T05:53:23.819129322Z" level=debug msg="Registering POST, /images/{name:.*}/push" 
time="2015-10-29T05:53:23.819207180Z" level=debug msg="Registering POST, /images/{name:.*}/tag" 
time="2015-10-29T05:53:23.819276303Z" level=debug msg="Registering POST, /containers/create" 
time="2015-10-29T05:53:23.819339617Z" level=debug msg="Registering POST, /containers/{name:.*}/kill" 
time="2015-10-29T05:53:23.819418180Z" level=debug msg="Registering POST, /containers/{name:.*}/pause" 
time="2015-10-29T05:53:23.819492622Z" level=debug msg="Registering POST, /containers/{name:.*}/unpause" 
time="2015-10-29T05:53:23.819571303Z" level=debug msg="Registering POST, /containers/{name:.*}/restart" 
time="2015-10-29T05:53:23.819650619Z" level=debug msg="Registering POST, /containers/{name:.*}/start" 
time="2015-10-29T05:53:23.819726990Z" level=debug msg="Registering POST, /containers/{name:.*}/stop" 
time="2015-10-29T05:53:23.819823360Z" level=debug msg="Registering POST, /containers/{name:.*}/wait" 
time="2015-10-29T05:53:23.819898582Z" level=debug msg="Registering POST, /containers/{name:.*}/resize" 
time="2015-10-29T05:53:23.819978332Z" level=debug msg="Registering POST, /containers/{name:.*}/attach" 
time="2015-10-29T05:53:23.820057291Z" level=debug msg="Registering POST, /containers/{name:.*}/copy" 
time="2015-10-29T05:53:23.820130347Z" level=debug msg="Registering POST, /containers/{name:.*}/exec" 
time="2015-10-29T05:53:23.820205394Z" level=debug msg="Registering POST, /exec/{name:.*}/start" 
time="2015-10-29T05:53:23.820275409Z" level=debug msg="Registering POST, /exec/{name:.*}/resize" 
time="2015-10-29T05:53:23.820344215Z" level=debug msg="Registering POST, /containers/{name:.*}/rename" 
time="2015-10-29T05:53:23.820423803Z" level=debug msg="Registering POST, /volumes/create" 
time="2015-10-29T05:53:23.820482211Z" level=debug msg="Registering PUT, /containers/{name:.*}/archive" 
time="2015-10-29T05:53:23.820578145Z" level=debug msg="Registering DELETE, /containers/{name:.*}" 
time="2015-10-29T05:53:23.820653106Z" level=debug msg="Registering DELETE, /images/{name:.*}" 
time="2015-10-29T05:53:23.820735783Z" level=debug msg="Registering DELETE, /volumes/{name:.*}" 
time="2015-10-29T05:53:23.820812998Z" level=debug msg="Registering GET, /networks" 
time="2015-10-29T05:53:23.820863219Z" level=debug msg="Registering GET, /networks/{id:.*}" 
time="2015-10-29T05:53:23.820938969Z" level=debug msg="Registering POST, /networks/create" 
time="2015-10-29T05:53:23.821001969Z" level=debug msg="Registering POST, /networks/{id:.*}/connect" 
time="2015-10-29T05:53:23.821092241Z" level=debug msg="Registering POST, /networks/{id:.*}/disconnect" 
time="2015-10-29T05:53:23.821172354Z" level=debug msg="Registering DELETE, /networks/{id:.*}" 
time="2015-10-29T05:53:23.821451468Z" level=debug msg="Calling GET /_ping" 
time="2015-10-29T05:53:23.821489468Z" level=info msg="GET /_ping" 
time="2015-10-29T05:53:23.821838409Z" level=debug msg="Calling GET /info" 
time="2015-10-29T05:53:23.821853918Z" level=info msg="GET /info" 
time="2015-10-29T05:53:23.847821271Z" level=debug msg="Calling GET /v1.22/containers/top1/json" 
time="2015-10-29T05:53:23.847853880Z" level=info msg="GET /v1.22/containers/top1/json" 
time="2015-10-29T05:53:23.847989174Z" level=error msg="Handler for GET /v1.22/containers/top1/json returned error: no such id: top1" 
time="2015-10-29T05:53:23.848010174Z" level=error msg="HTTP Error" err="no such id: top1" statusCode=404 
time="2015-10-29T05:53:23.848160074Z" level=debug msg="Calling GET /v1.22/images/top1/json" 
time="2015-10-29T05:53:23.848181549Z" level=info m
time="2015-10-29T05:53:21Z" level=warning msg="Running experimental build" 
time="2015-10-29T05:53:21.347580825Z" level=debug msg="docker group found. gid: 999" 
time="2015-10-29T05:53:21.347602142Z" level=debug msg="Server created for HTTP on unix (/go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/docker.sock)" 
time="2015-10-29T05:53:21.347837765Z" level=info msg="API listen on /go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/docker.sock" 
time="2015-10-29T05:53:21.347869738Z" level=info msg="User namespaces: ID ranges will be mapped to subuid/subgid ranges of: dockremap:dockremap" 
time="2015-10-29T05:53:21.348005849Z" level=debug msg="Creating actual daemon root: /go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536" 
time="2015-10-29T05:53:21.348145278Z" level=debug msg="[graphdriver] trying provided driver \"vfs\"" 
time="2015-10-29T05:53:21.348204597Z" level=debug msg="Using graph driver vfs" 
time="2015-10-29T05:53:21.348213953Z" level=debug msg="Using default logging driver json-file" 
time="2015-10-29T05:53:21.348258293Z" level=debug msg="Creating images graph" 
time="2015-10-29T05:53:21.348330889Z" level=debug msg="Restored 0 elements" 
time="2015-10-29T05:53:21.348520120Z" level=debug msg="Creating repository list" 
time="2015-10-29T05:53:21.348584768Z" level=debug msg="Option DefaultDriver: bridge" 
time="2015-10-29T05:53:21.348593309Z" level=debug msg="Option DefaultNetwork: bridge" 
time="2015-10-29T05:53:21.349706235Z" level=warning msg="Running modprobe bridge br_netfilter failed with message: modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/4.2.5-fsociety/modules.dep.bin'\nmodprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/4.2.5-fsociety/modules.dep.bin'\n, error: exit status 1" 
time="2015-10-29T05:53:21.350548917Z" level=warning msg="Running modprobe nf_nat failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/4.2.5-fsociety/modules.dep.bin'`, error: exit status 1" 
time="2015-10-29T05:53:21.350610501Z" level=debug msg="Fail to initialize firewalld: Failed to connect to D-Bus system bus: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory, using raw iptables instead" 
time="2015-10-29T05:53:21.351503456Z" level=debug msg="/sbin/iptables, [--wait -t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]" 
time="2015-10-29T05:53:21.352361096Z" level=debug msg="/sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER]" 
time="2015-10-29T05:53:21.353177209Z" level=debug msg="/sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER]" 
time="2015-10-29T05:53:21.354030722Z" level=debug msg="/sbin/iptables, [--wait -t nat -D PREROUTING]" 
time="2015-10-29T05:53:21.354806558Z" level=debug msg="/sbin/iptables, [--wait -t nat -D OUTPUT]" 
time="2015-10-29T05:53:21.355621041Z" level=debug msg="/sbin/iptables, [--wait -t nat -F DOCKER]" 
time="2015-10-29T05:53:21.356393524Z" level=debug msg="/sbin/iptables, [--wait -t nat -X DOCKER]" 
time="2015-10-29T05:53:21.513943874Z" level=debug msg="/sbin/iptables, [--wait -t nat -n -L DOCKER]" 
time="2015-10-29T05:53:21.515213194Z" level=debug msg="/sbin/iptables, [--wait -t nat -N DOCKER]" 
time="2015-10-29T05:53:21.516824457Z" level=debug msg="/sbin/iptables, [--wait -t filter -n -L DOCKER]" 
time="2015-10-29T05:53:21.518562638Z" level=debug msg="Registering ipam provider: default" 
time="2015-10-29T05:53:21.589164291Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.18.0.1/16. Daemon option --bip can be used to set a preferred IP address" 
time="2015-10-29T05:53:21.589214904Z" level=debug msg="Allocating IPv4 pools for network bridge (9dc5f015b9ea058bf78689bcd88e9bc7351d28840299e3535d26cfaa73422258)" 
time="2015-10-29T05:53:21.589235191Z" level=debug msg="RequestPool(LocalDefault, 172.18.0.1/16, , map[], false)" 
time="2015-10-29T05:53:21.766446928Z" level=debug msg="RequestAddress(LocalDefault/172.18.0.0/16, 172.18.0.1, map[])" 
time="2015-10-29T05:53:21.800577551Z" level=debug msg="/sbin/iptables, [--wait -t nat -C POSTROUTING -s 172.18.0.0/16 ! -o docker0 -j MASQUERADE]" 
time="2015-10-29T05:53:21.801771521Z" level=debug msg="/sbin/iptables, [--wait -D FORWARD -i docker0 -o docker0 -j DROP]" 
time="2015-10-29T05:53:21.802601266Z" level=debug msg="/sbin/iptables, [--wait -t filter -C FORWARD -i docker0 -o docker0 -j ACCEPT]" 
time="2015-10-29T05:53:21.803447627Z" level=debug msg="/sbin/iptables, [--wait -t filter -C FORWARD -i docker0 ! -o docker0 -j ACCEPT]" 
time="2015-10-29T05:53:21.804268830Z" level=debug msg="/sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT]" 
time="2015-10-29T05:53:21.805139925Z" level=debug msg="/sbin/iptables, [--wait -t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]" 
time="2015-10-29T05:53:21.806814499Z" level=debug msg="/sbin/iptables, [--wait -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]" 
time="2015-10-29T05:53:21.807700939Z" level=debug msg="/sbin/iptables, [--wait -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8]" 
time="2015-10-29T05:53:21.809359691Z" level=debug msg="/sbin/iptables, [--wait -t nat -A OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8]" 
time="2015-10-29T05:53:21.810260302Z" level=debug msg="/sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -j DOCKER]" 
time="2015-10-29T05:53:22.024991166Z" level=debug msg="Cleaning up old shm/mqueue mounts: start." 
time="2015-10-29T05:53:22.025242731Z" level=debug msg="Cleaning up old shm/mqueue mounts: done." 
time="2015-10-29T05:53:22.025488369Z" level=info msg="Daemon has completed initialization" 
time="2015-10-29T05:53:22.025524515Z" level=info msg="Docker daemon" commit=44da861-dirty execdriver=native-0.2 graphdriver=vfs version=1.9.0-dev 
time="2015-10-29T05:53:22.027646122Z" level=debug msg="Registering routers" 
time="2015-10-29T05:53:22.027704384Z" level=debug msg="Registering HEAD, /containers/{name:.*}/archive" 
time="2015-10-29T05:53:22.028047102Z" level=debug msg="Registering OPTIONS, /" 
time="2015-10-29T05:53:22.028197827Z" level=debug msg="Registering GET, /_ping" 
time="2015-10-29T05:53:22.028361552Z" level=debug msg="Registering GET, /events" 
time="2015-10-29T05:53:22.028544146Z" level=debug msg="Registering GET, /info" 
time="2015-10-29T05:53:22.028701692Z" level=debug msg="Registering GET, /version" 
time="2015-10-29T05:53:22.028877817Z" level=debug msg="Registering GET, /images/json" 
time="2015-10-29T05:53:22.029137141Z" level=debug msg="Registering GET, /images/search" 
time="2015-10-29T05:53:22.029493419Z" level=debug msg="Registering GET, /images/get" 
time="2015-10-29T05:53:22.029856330Z" level=debug msg="Registering GET, /images/{name:.*}/get" 
time="2015-10-29T05:53:22.030370759Z" level=debug msg="Registering GET, /images/{name:.*}/history" 
time="2015-10-29T05:53:22.030782012Z" level=debug msg="Registering GET, /images/{name:.*}/json" 
time="2015-10-29T05:53:22.031051210Z" level=debug msg="Registering GET, /containers/json" 
time="2015-10-29T05:53:22.032600909Z" level=debug msg="Registering GET, /containers/{name:.*}/export" 
time="2015-10-29T05:53:22.032956729Z" level=debug msg="Registering GET, /containers/{name:.*}/changes" 
time="2015-10-29T05:53:22.033346573Z" level=debug msg="Registering GET, /containers/{name:.*}/json" 
time="2015-10-29T05:53:22.033658710Z" level=debug msg="Registering GET, /containers/{name:.*}/top" 
time="2015-10-29T05:53:22.033975686Z" level=debug msg="Registering GET, /containers/{name:.*}/logs" 
time="2015-10-29T05:53:22.034279455Z" level=debug msg="Registering GET, /containers/{name:.*}/stats" 
time="2015-10-29T05:53:22.034595356Z" level=debug msg="Registering GET, /containers/{name:.*}/attach/ws" 
time="2015-10-29T05:53:22.034977392Z" level=debug msg="Registering GET, /exec/{id:.*}/json" 
time="2015-10-29T05:53:22.035689998Z" level=debug msg="Registering GET, /containers/{name:.*}/archive" 
time="2015-10-29T05:53:22.036230814Z" level=debug msg="Registering GET, /volumes" 
time="2015-10-29T05:53:22.036332984Z" level=debug msg="Registering GET, /volumes/{name:.*}" 
time="2015-10-29T05:53:22.036478635Z" level=debug msg="Registering POST, /auth" 
time="2015-10-29T05:53:22.036560141Z" level=debug msg="Registering POST, /commit" 
time="2015-10-29T05:53:22.036625835Z" level=debug msg="Registering POST, /build" 
time="2015-10-29T05:53:22.036680184Z" level=debug msg="Registering POST, /images/create" 
time="2015-10-29T05:53:22.036748048Z" level=debug msg="Registering POST, /images/load" 
time="2015-10-29T05:53:22.036806063Z" level=debug msg="Registering POST, /images/{name:.*}/push" 
time="2015-10-29T05:53:22.036893598Z" level=debug msg="Registering POST, /images/{name:.*}/tag" 
time="2015-10-29T05:53:22.036970253Z" level=debug msg="Registering POST, /containers/create" 
time="2015-10-29T05:53:22.037039295Z" level=debug msg="Registering POST, /containers/{name:.*}/kill" 
time="2015-10-29T05:53:22.037123711Z" level=debug msg="Registering POST, /containers/{name:.*}/pause" 
time="2015-10-29T05:53:22.037268436Z" level=debug msg="Registering POST, /containers/{name:.*}/unpause" 
time="2015-10-29T05:53:22.037412003Z" level=debug msg="Registering POST, /containers/{name:.*}/restart" 
time="2015-10-29T05:53:22.037561144Z" level=debug msg="Registering POST, /containers/{name:.*}/start" 
time="2015-10-29T05:53:22.037695028Z" level=debug msg="Registering POST, /containers/{name:.*}/stop" 
time="2015-10-29T05:53:22.037840344Z" level=debug msg="Registering POST, /containers/{name:.*}/wait" 
time="2015-10-29T05:53:22.037979768Z" level=debug msg="Registering POST, /containers/{name:.*}/resize" 
time="2015-10-29T05:53:22.038130033Z" level=debug msg="Registering POST, /containers/{name:.*}/attach" 
time="2015-10-29T05:53:22.038273461Z" level=debug msg="Registering POST, /containers/{name:.*}/copy" 
time="2015-10-29T05:53:22.038419242Z" level=debug msg="Registering POST, /containers/{name:.*}/exec" 
time="2015-10-29T05:53:22.038550424Z" level=debug msg="Registering POST, /exec/{name:.*}/start" 
time="2015-10-29T05:53:22.038693952Z" level=debug msg="Registering POST, /exec/{name:.*}/resize" 
time="2015-10-29T05:53:22.038802587Z" level=debug msg="Registering POST, /containers/{name:.*}/rename" 
time="2015-10-29T05:53:22.038888711Z" level=debug msg="Registering POST, /volumes/create" 
time="2015-10-29T05:53:22.038948560Z" level=debug msg="Registering PUT, /containers/{name:.*}/archive" 
time="2015-10-29T05:53:22.039028175Z" level=debug msg="Registering DELETE, /containers/{name:.*}" 
time="2015-10-29T05:53:22.039140754Z" level=debug msg="Registering DELETE, /images/{name:.*}" 
time="2015-10-29T05:53:22.039218561Z" level=debug msg="Registering DELETE, /volumes/{name:.*}" 
time="2015-10-29T05:53:22.039296624Z" level=debug msg="Registering GET, /networks" 
time="2015-10-29T05:53:22.039347752Z" level=debug msg="Registering GET, /networks/{id:.*}" 
time="2015-10-29T05:53:22.039421565Z" level=debug msg="Registering POST, /networks/create" 
time="2015-10-29T05:53:22.039495605Z" level=debug msg="Registering POST, /networks/{id:.*}/connect" 
time="2015-10-29T05:53:22.039580923Z" level=debug msg="Registering POST, /networks/{id:.*}/disconnect" 
time="2015-10-29T05:53:22.039674470Z" level=debug msg="Registering DELETE, /networks/{id:.*}" 
time="2015-10-29T05:53:22.040020127Z" level=debug msg="Calling GET /_ping" 
time="2015-10-29T05:53:22.040038332Z" level=info msg="GET /_ping" 
time="2015-10-29T05:53:22.040462592Z" level=debug msg="Calling GET /info" 
time="2015-10-29T05:53:22.040484693Z" level=info msg="GET /info" 
time="2015-10-29T05:53:22.105677184Z" level=debug msg="Calling POST /v1.22/images/load" 
time="2015-10-29T05:53:22.105713058Z" level=info msg="POST /v1.22/images/load" 
time="2015-10-29T05:53:22.129056312Z" level=debug msg="Loading cfa753dfea5e68a24366dfba16e6edf573daa447abf65bc11619c1a98a3aff54" 
time="2015-10-29T05:53:22.129591328Z" level=debug msg="Start untar layer" 
time="2015-10-29T05:53:22.176260680Z" level=debug msg="Untar time: 0.046656842000000004s" 
time="2015-10-29T05:53:22.177086487Z" level=debug msg="Completed processing cfa753dfea5e68a24366dfba16e6edf573daa447abf65bc11619c1a98a3aff54" 
time="2015-10-29T05:53:22.177128501Z" level=debug msg="Loading d7057cb020844f245031d27b76cb18af05db1cc3a96a29fa7777af75f5ac91a3" 
time="2015-10-29T05:53:22.177403807Z" level=debug msg="Creating dest directory: /go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536/vfs/dir/d7057cb020844f245031d27b76cb18af05db1cc3a96a29fa7777af75f5ac91a3" 
time="2015-10-29T05:53:22.177422299Z" level=debug msg="Calling TarUntar(/go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536/vfs/dir/cfa753dfea5e68a24366dfba16e6edf573daa447abf65bc11619c1a98a3aff54, /go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536/vfs/dir/d7057cb020844f245031d27b76cb18af05db1cc3a96a29fa7777af75f5ac91a3)" 
time="2015-10-29T05:53:22.177436838Z" level=debug msg="TarUntar(/go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536/vfs/dir/cfa753dfea5e68a24366dfba16e6edf573daa447abf65bc11619c1a98a3aff54 /go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536/vfs/dir/d7057cb020844f245031d27b76cb18af05db1cc3a96a29fa7777af75f5ac91a3)" 
time="2015-10-29T05:53:22.211205231Z" level=debug msg="Start untar layer" 
time="2015-10-29T05:53:22.233816936Z" level=debug msg="Untar time: 0.022606650000000002s" 
time="2015-10-29T05:53:22.234143951Z" level=debug msg="Completed processing d7057cb020844f245031d27b76cb18af05db1cc3a96a29fa7777af75f5ac91a3" 
time="2015-10-29T05:53:22.262278695Z" level=debug msg="Calling POST /v1.22/containers/create" 
time="2015-10-29T05:53:22.262588460Z" level=debug msg="form data: map[\"AttachStdout\":%!q(bool=false) \"HostConfig\":map[\"MemoryReservation\":%!q(float64=0) \"CpuPeriod\":%!q(float64=0) \"CpusetCpus\":\"\" \"CpuQuota\":%!q(float64=0) \"Dns\":<nil> \"VolumesFrom\":<nil> \"UTSMode\":\"\" \"ContainerIDFile\":\"\" \"GroupAdd\":<nil> \"LxcConf\":[] \"BlkioWeight\":%!q(float64=0) \"DnsOptions\":<nil> \"CgroupParent\":\"\" \"Binds\":<nil> \"IpcMode\":\"\" \"CpuShares\":%!q(float64=0) \"PublishAllPorts\":%!q(bool=false) \"Devices\":[] \"PidMode\":\"\" \"CapAdd\":<nil> \"Ulimits\":<nil> \"MemorySwappiness\":%!q(float64=-1) \"ReadonlyRootfs\":%!q(bool=false) \"LogConfig\":map[\"Type\":\"\" \"Config\":map[]] \"SecurityOpt\":<nil> \"Privileged\":%!q(bool=false) \"Links\":<nil> \"DnsSearch\":<nil> \"RestartPolicy\":map[\"Name\":\"always\" \"MaximumRetryCount\":%!q(float64=0)] \"OomKillDisable\":%!q(bool=false) \"CpusetMems\":\"\" \"PortBindings\":map[\"80/tcp\":[map[\"HostIp\":\"\" \"HostPort\":\"\"]]] \"ExtraHosts\":<nil> \"MemorySwap\":%!q(float64=0) \"KernelMemory\":%!q(float64=0) \"NetworkMode\":\"default\" \"CapDrop\":<nil> \"ConsoleSize\":[%!q(float64=0) %!q(float64=0)] \"VolumeDriver\":\"\" \"Memory\":%!q(float64=0)] \"AttachStdin\":%!q(bool=false) \"User\":\"\" \"StdinOnce\":%!q(bool=false) \"Image\":\"busybox:latest\" \"OnBuild\":<nil> \"Domainname\":\"\" \"Env\":[] \"WorkingDir\":\"\" \"StopSignal\":\"SIGTERM\" \"Tty\":%!q(bool=false) \"AttachStderr\":%!q(bool=false) \"ExposedPorts\":map[\"80/tcp\":map[]] \"OpenStdin\":%!q(bool=false) \"Cmd\":[\"top\"] \"Volumes\":map[] \"Entrypoint\":<nil> \"Labels\":map[] \"Hostname\":\"\"]" 
time="2015-10-29T05:53:22.262628736Z" level=info msg="POST /v1.22/containers/create?name=top1" 
time="2015-10-29T05:53:22.337432168Z" level=debug msg="Creating dest directory: /go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536/vfs/dir/8b672c663113e2480cb636775da8b068f66d0976cc3cd9761e72d14adaab4c53-init" 
time="2015-10-29T05:53:22.337467397Z" level=debug msg="Calling TarUntar(/go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536/vfs/dir/d7057cb020844f245031d27b76cb18af05db1cc3a96a29fa7777af75f5ac91a3, /go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536/vfs/dir/8b672c663113e2480cb636775da8b068f66d0976cc3cd9761e72d14adaab4c53-init)" 
time="2015-10-29T05:53:22.337490320Z" level=debug msg="TarUntar(/go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536/vfs/dir/d7057cb020844f245031d27b76cb18af05db1cc3a96a29fa7777af75f5ac91a3 /go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536/vfs/dir/8b672c663113e2480cb636775da8b068f66d0976cc3cd9761e72d14adaab4c53-init)" 
time="2015-10-29T05:53:22.371778504Z" level=debug msg="Creating dest directory: /go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536/vfs/dir/8b672c663113e2480cb636775da8b068f66d0976cc3cd9761e72d14adaab4c53" 
time="2015-10-29T05:53:22.371815399Z" level=debug msg="Calling TarUntar(/go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536/vfs/dir/8b672c663113e2480cb636775da8b068f66d0976cc3cd9761e72d14adaab4c53-init, /go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536/vfs/dir/8b672c663113e2480cb636775da8b068f66d0976cc3cd9761e72d14adaab4c53)" 
time="2015-10-29T05:53:22.371830035Z" level=debug msg="TarUntar(/go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536/vfs/dir/8b672c663113e2480cb636775da8b068f66d0976cc3cd9761e72d14adaab4c53-init /go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536/vfs/dir/8b672c663113e2480cb636775da8b068f66d0976cc3cd9761e72d14adaab4c53)" 
time="2015-10-29T05:53:22.412539948Z" level=debug msg="Calling POST /v1.22/containers/8b672c663113e2480cb636775da8b068f66d0976cc3cd9761e72d14adaab4c53/start" 
time="2015-10-29T05:53:22.412580036Z" level=info msg="POST /v1.22/containers/8b672c663113e2480cb636775da8b068f66d0976cc3cd9761e72d14adaab4c53/start" 
time="2015-10-29T05:53:22.439862164Z" level=debug msg="Assigning addresses for endpoint top1's interface on network bridge" 
time="2015-10-29T05:53:22.439916231Z" level=debug msg="RequestAddress(LocalDefault/172.18.0.0/16, <nil>, map[])" 
time="2015-10-29T05:53:22.494531205Z" level=debug msg="/sbin/iptables, [--wait -t nat -A DOCKER -p tcp -d 0/0 --dport 32768 -j DNAT --to-destination 172.18.0.2:80 ! -i docker0]" 
time="2015-10-29T05:53:22.496878206Z" level=debug msg="/sbin/iptables, [--wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.18.0.2 --dport 80 -j ACCEPT]" 
time="2015-10-29T05:53:22.499150984Z" level=debug msg="/sbin/iptables, [--wait -t nat -A POSTROUTING -p tcp -s 172.18.0.2 -d 172.18.0.2 --dport 80 -j MASQUERADE]" 
time="2015-10-29T05:53:22.795008967Z" level=info msg="Processing signal 'interrupt'" 
time="2015-10-29T05:53:22.795151008Z" level=debug msg="starting clean shutdown of all containers..." 
time="2015-10-29T05:53:22.795196231Z" level=debug msg="stopping 8b672c663113e2480cb636775da8b068f66d0976cc3cd9761e72d14adaab4c53" 
time="2015-10-29T05:53:22.795222638Z" level=debug msg="Sending 15 to 8b672c663113e2480cb636775da8b068f66d0976cc3cd9761e72d14adaab4c53" 
time="2015-10-29T05:53:23.007626165Z" level=debug msg="/sbin/iptables, [--wait -t nat -D DOCKER -p tcp -d 0/0 --dport 32768 -j DNAT --to-destination 172.18.0.2:80 ! -i docker0]" 
time="2015-10-29T05:53:23.009257245Z" level=debug msg="/sbin/iptables, [--wait -t filter -D DOCKER ! -i docker0 -o docker0 -p tcp -d 172.18.0.2 --dport 80 -j ACCEPT]" 
time="2015-10-29T05:53:23.010593900Z" level=debug msg="/sbin/iptables, [--wait -t nat -D POSTROUTING -p tcp -s 172.18.0.2 -d 172.18.0.2 --dport 80 -j MASQUERADE]" 
time="2015-10-29T05:53:23.031205165Z" level=debug msg="Releasing addresses for endpoint top1's interface on network bridge" 
time="2015-10-29T05:53:23.031254226Z" level=debug msg="ReleaseAddress(LocalDefault/172.18.0.0/16, 172.18.0.2)" 
time="2015-10-29T05:53:23.143641017Z" level=debug msg="container stopped 8b672c663113e2480cb636775da8b068f66d0976cc3cd9761e72d14adaab4c53" 
time="2015-10-29T05:53:23.143829583Z" level=debug msg="Cleaning up old shm/mqueue mounts: start." 
time="2015-10-29T05:53:23.143997315Z" level=debug msg="Unix socket /var/lib/docker/network/files/dcbfc5e3667dc398fe7246ea048bb231a2765995b3bcceec183bfdb7564a35f4.sock doesnt exist. cannot accept client connections" 
time="2015-10-29T05:53:23.144051800Z" level=debug msg="Cleaning up old shm/mqueue mounts: done." 
time="2015-10-29T05:53:23.144077494Z" level=debug msg="Clean shutdown succeeded" 
time="2015-10-29T05:53:23Z" level=warning msg="Running experimental build" 
time="2015-10-29T05:53:23.166117958Z" level=debug msg="docker group found. gid: 999" 
time="2015-10-29T05:53:23.166139127Z" level=debug msg="Server created for HTTP on unix (/go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/docker.sock)" 
time="2015-10-29T05:53:23.166363059Z" level=info msg="API listen on /go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/docker.sock" 
time="2015-10-29T05:53:23.166425114Z" level=info msg="User namespaces: ID ranges will be mapped to subuid/subgid ranges of: dockremap:dockremap" 
time="2015-10-29T05:53:23.166666685Z" level=debug msg="Creating actual daemon root: /go/src/github.com/docker/docker/bundles/1.9.0-dev/test-integration-cli/d27197898/root/165536.165536/165536.165536" 
time="2015-10-29T05:53:23.166806256Z" level=debug msg="[graphdriver] trying provided driver \"vfs\"" 
time="2015-10-29T05:53:23.166863140Z" level=debug msg="Using graph driver vfs" 
time="2015-10-29T05:53:23.166872923Z" level=debug msg="Using default logging driver json-file" 
time="2015-10-29T05:53:23.166927122Z" level=debug msg="Creating images graph" 
time="2015-10-29T05:53:23.166998613Z" level=debug msg="Restored 0 elements" 
time="2015-10-29T05:53:23.167199988Z" level=debug msg="Creating repository list" 
time="2015-10-29T05:53:23.167266000Z" level=debug msg="Option DefaultDriver: bridge" 
time="2015-10-29T05:53:23.167274774Z" level=debug msg="Option DefaultNetwork: bridge" 
time="2015-10-29T05:53:23.168374494Z" level=warning msg="Running modprobe bridge br_netfilter failed with message: modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/4.2.5-fsociety/modules.dep.bin'\nmodprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/4.2.5-fsociety/modules.dep.bin'\n, error: exit status 1" 
time="2015-10-29T05:53:23.169290217Z" level=warning msg="Running modprobe nf_nat failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/4.2.5-fsociety/modules.dep.bin'`, error: exit status 1" 
time="2015-10-29T05:53:23.169356772Z" level=debug msg="Fail to initialize firewalld: Failed to connect to D-Bus system bus: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory, using raw iptables instead" 
time="2015-10-29T05:53:23.170303295Z" level=debug msg="/sbin/iptables, [--wait -t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]" 
time="2015-10-29T05:53:23.171204142Z" level=debug msg="/sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER]" 
time="2015-10-29T05:53:23.172189831Z" level=debug msg="/sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER]" 
time="2015-10-29T05:53:23.173017128Z" level=debug msg="/sbin/iptables, [--wait -t nat -D PREROUTING]" 
time="2015-10-29T05:53:23.173746668Z" level=debug msg="/sbin/iptables, [--wait -t nat -D OUTPUT]" 
time="2015-10-29T05:53:23.174540195Z" level=debug msg="/sbin/iptables, [--wait -t nat -F DOCKER]" 
time="2015-10-29T05:53:23.175377731Z" level=debug msg="/sbin/iptables, [--wait -t nat -X DOCKER]" 
time="2015-10-29T05:53:23.210374083Z" level=debug msg="/sbin/iptables, [--wait -t nat -n -L DOCKER]" 
time="2015-10-29T05:53:23.211449974Z" level=debug msg="/sbin/iptables, [--wait -t nat -N DOCKER]" 
time="2015-10-29T05:53:23.212327301Z" level=debug msg="/sbin/iptables, [--wait -t filter -n -L DOCKER]" 
time="2015-10-29T05:53:23.213215247Z" level=debug msg="Registering ipam provider: default" 
time="2015-10-29T05:53:23.300147175Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.18.0.1/16. Daemon option --bip can be used to set a preferred IP address" 
time="2015-10-29T05:53:23.300197294Z" level=debug msg="Allocating IPv4 pools for network bridge (9fe8ee81b4e9c5bd3dbc9ad74f428ca8623028c5da16a84745c155398427581b)" 
time="2015-10-29T05:53:23.300213983Z" level=debug msg="RequestPool(LocalDefault, 172.18.0.1/16, , map[], false)" 
time="2015-10-29T05:53:23.517903581Z" level=debug msg="RequestAddress(LocalDefault/172.18.0.0/16, 172.18.0.1, map[])" 
time="2015-10-29T05:53:23.554505288Z" level=debug msg="/sbin/iptables, [--wait -t nat -C POSTROUTING -s 172.18.0.0/16 ! -o docker0 -j MASQUERADE]" 
time="2015-10-29T05:53:23.555642841Z" level=debug msg="/sbin/iptables, [--wait -D FORWARD -i docker0 -o docker0 -j DROP]" 
time="2015-10-29T05:53:23.556441506Z" level=debug msg="/sbin/iptables, [--wait -t filter -C FORWARD -i docker0 -o docker0 -j ACCEPT]" 
time="2015-10-29T05:53:23.557256457Z" level=debug msg="/sbin/iptables, [--wait -t filter -C FORWARD -i docker0 ! -o docker0 -j ACCEPT]" 
time="2015-10-29T05:53:23.558081404Z" level=debug msg="/sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT]" 
time="2015-10-29T05:53:23.558943975Z" level=debug msg="/sbin/iptables, [--wait -t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]" 
time="2015-10-29T05:53:23.560643808Z" level=debug msg="/sbin/iptables, [--wait -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]" 
time="2015-10-29T05:53:23.562055673Z" level=debug msg="/sbin/iptables, [--wait -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8]" 
time="2015-10-29T05:53:23.564691146Z" level=debug msg="/sbin/iptables, [--wait -t nat -A OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8]" 
time="2015-10-29T05:53:23.566220340Z" level=debug msg="/sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -j DOCKER]" 
time="2015-10-29T05:53:23.804027375Z" level=debug msg="Cleaning up old shm/mqueue mounts: start." 
time="2015-10-29T05:53:23.804190652Z" level=debug msg="Cleaning up old shm/mqueue mounts: done." 
time="2015-10-29T05:53:23.804580689Z" level=info msg="Daemon has completed initialization" 
time="2015-10-29T05:53:23.804668618Z" level=info msg="Docker daemon" commit=44da861-dirty execdriver=native-0.2 graphdriver=vfs version=1.9.0-dev 
time="2015-10-29T05:53:23.806732254Z" level=debug msg="Registering routers" 
time="2015-10-29T05:53:23.806759205Z" level=debug msg="Registering HEAD, /containers/{name:.*}/archive" 
time="2015-10-29T05:53:23.807604998Z" level=debug msg="Registering OPTIONS, /" 
time="2015-10-29T05:53:23.808042535Z" level=debug msg="Registering GET, /_ping" 
time="2015-10-29T05:53:23.808443000Z" level=debug msg="Registering GET, /events" 
time="2015-10-29T05:53:23.808905765Z" level=debug msg="Registering GET, /info" 
time="2015-10-29T05:53:23.809051590Z" level=debug msg="Registering GET, /version" 
time="2015-10-29T05:53:23.809428197Z" level=debug msg="Registering GET, /images/json" 
time="2015-10-29T05:53:23.809607725Z" level=debug msg="Registering GET, /images/search" 
time="2015-10-29T05:53:23.809995637Z" level=debug msg="Registering GET, /images/get" 
time="2015-10-29T05:53:23.810287375Z" level=debug msg="Registering GET, /images/{name:.*}/get" 
time="2015-10-29T05:53:23.810568335Z" level=debug msg="Registering GET, /images/{name:.*}/history" 
time="2015-10-29T05:53:23.811036752Z" level=debug msg="Registering GET, /images/{name:.*}/json" 
time="2015-10-29T05:53:23.811476021Z" level=debug msg="Registering GET, /containers/json" 
time="2015-10-29T05:53:23.811706151Z" level=debug msg="Registering GET, /containers/{name:.*}/export" 
time="2015-10-29T05:53:23.812001242Z" level=debug msg="Registering GET, /containers/{name:.*}/changes" 
time="2015-10-29T05:53:23.812410549Z" level=debug msg="Registering GET, /containers/{name:.*}/json" 
time="2015-10-29T05:53:23.812810344Z" level=debug msg="Registering GET, /containers/{name:.*}/top" 
time="2015-10-29T05:53:23.813208967Z" level=debug msg="Registering GET, /containers/{name:.*}/logs" 
time="2015-10-29T05:53:23.813932747Z" level=debug msg="Registering GET, /containers/{name:.*}/stats" 
time="2015-10-29T05:53:23.814469282Z" level=debug msg="Registering GET, /containers/{name:.*}/attach/ws" 
time="2015-10-29T05:53:23.818000903Z" level=debug msg="Registering GET, /exec/{id:.*}/json" 
time="2015-10-29T05:53:23.818171684Z" level=debug msg="Registering GET, /containers/{name:.*}/archive" 
time="2015-10-29T05:53:23.818579880Z" level=debug msg="Registering GET, /volumes" 
time="2015-10-29T05:53:23.818677826Z" level=debug msg="Registering GET, /volumes/{name:.*}" 
time="2015-10-29T05:53:23.818780566Z" level=debug msg="Registering POST, /auth" 
time="2015-10-29T05:53:23.818841832Z" level=debug msg="Registering POST, /commit" 
time="2015-10-29T05:53:23.818923924Z" level=debug msg="Registering POST, /build" 
time="2015-10-29T05:53:23.819001310Z" level=debug msg="Registering POST, /images/create" 
time="2015-10-29T05:53:23.819062325Z" level=debug msg="Registering POST, /images/load" 
time="2015-10-29T05:53:23.819129322Z" level=debug msg="Registering POST, /images/{name:.*}/push" 
time="2015-10-29T05:53:23.819207180Z" level=debug msg="Registering POST, /images/{name:.*}/tag" 
time="2015-10-29T05:53:23.819276303Z" level=debug msg="Registering POST, /containers/create" 
time="2015-10-29T05:53:23.819339617Z" level=debug msg="Registering POST, /containers/{name:.*}/kill" 
time="2015-10-29T05:53:23.819418180Z" level=debug msg="Registering POST, /containers/{name:.*}/pause" 
time="2015-10-29T05:53:23.819492622Z" level=debug msg="Registering POST, /containers/{name:.*}/unpause" 
time="2015-10-29T05:53:23.819571303Z" level=debug msg="Registering POST, /containers/{name:.*}/restart" 
time="2015-10-29T05:53:23.819650619Z" level=debug msg="Registering POST, /containers/{name:.*}/start" 
time="2015-10-29T05:53:23.819726990Z" level=debug msg="Registering POST, /containers/{name:.*}/stop" 
time="2015-10-29T05:53:23.819823360Z" level=debug msg="Registering POST, /containers/{name:.*}/wait" 
time="2015-10-29T05:53:23.819898582Z" level=debug msg="Registering POST, /containers/{name:.*}/resize" 
time="2015-10-29T05:53:23.819978332Z" level=debug msg="Registering POST, /containers/{name:.*}/attach" 
time="2015-10-29T05:53:23.820057291Z" level=debug msg="Registering POST, /containers/{name:.*}/copy" 
time="2015-10-29T05:53:23.820130347Z" level=debug msg="Registering POST, /containers/{name:.*}/exec" 
time="2015-10-29T05:53:23.820205394Z" level=debug msg="Registering POST, /exec/{name:.*}/start" 
time="2015-10-29T05:53:23.820275409Z" level=debug msg="Registering POST, /exec/{name:.*}/resize" 
time="2015-10-29T05:53:23.820344215Z" level=debug msg="Registering POST, /containers/{name:.*}/rename" 
time="2015-10-29T05:53:23.820423803Z" level=debug msg="Registering POST, /volumes/create" 
time="2015-10-29T05:53:23.820482211Z" level=debug msg="Registering PUT, /containers/{name:.*}/archive" 
time="2015-10-29T05:53:23.820578145Z" level=debug msg="Registering DELETE, /containers/{name:.*}" 
time="2015-10-29T05:53:23.820653106Z" level=debug msg="Registering DELETE, /images/{name:.*}" 
time="2015-10-29T05:53:23.820735783Z" level=debug msg="Registering DELETE, /volumes/{name:.*}" 
time="2015-10-29T05:53:23.820812998Z" level=debug msg="Registering GET, /networks" 
time="2015-10-29T05:53:23.820863219Z" level=debug msg="Registering GET, /networks/{id:.*}" 
time="2015-10-29T05:53:23.820938969Z" level=debug msg="Registering POST, /networks/create" 
time="2015-10-29T05:53:23.821001969Z" level=debug msg="Registering POST, /networks/{id:.*}/connect" 
time="2015-10-29T05:53:23.821092241Z" level=debug msg="Registering POST, /networks/{id:.*}/disconnect" 
time="2015-10-29T05:53:23.821172354Z" level=debug msg="Registering DELETE, /networks/{id:.*}" 
time="2015-10-29T05:53:23.821451468Z" level=debug msg="Calling GET /_ping" 
time="2015-10-29T05:53:23.821489468Z" level=info msg="GET /_ping" 
time="2015-10-29T05:53:23.821838409Z" level=debug msg="Calling GET /info" 
time="2015-10-29T05:53:23.821853918Z" level=info msg="GET /info" 
time="2015-10-29T05:53:23.847821271Z" level=debug msg="Calling GET /v1.22/containers/top1/json" 
time="2015-10-29T05:53:23.847853880Z" level=info msg="GET /v1.22/containers/top1/json" 
time="2015-10-29T05:53:23.847989174Z" level=error msg="Handler for GET /v1.22/containers/top1/json returned error: no such id: top1" 
time="2015-10-29T05:53:23.848010174Z" level=error msg="HTTP Error" err="no such id: top1" statusCode=404 
time="2015-10-29T05:53:23.848160074Z" level=debug msg="Calling GET /v1.22/images/top1/json" 
time="2015-10-29T05:53:23.848181549Z" level=info msg="GET /v1.22/images/top1/json" 
time="2015-10-29T05:53:23.848243216Z" level=error msg="Handler for GET /v1.22/images/top1/json returned error: No such image: top1" 
time="2015-10-29T05:53:23.848261797Z" level=error msg="HTTP Error" err="No such image: top1" statusCode=404 
time="2015-10-29T05:53:23.853920674Z" level=info msg="Processing signal 'interrupt'" 
time="2015-10-29T05:53:23.854029677Z" level=debug msg="starting clean shutdown of all containers..." 
time="2015-10-29T05:53:23.854107656Z" level=debug msg="Cleaning up old shm/mqueue mounts: start." 
time="2015-10-29T05:53:23.854223885Z" level=debug msg="Unix socket /var/lib/docker/network/files/a05e46e4c5fdff5a467b9f92b8edb285d4f5b679c90cb1686d9d3d97a8fae7b9.sock doesnt exist. cannot accept client connections" 
time="2015-10-29T05:53:23.854275725Z" level=debug msg="Cleaning up old shm/mqueue mounts: done." 
time="2015-10-29T05:53:23.854289721Z" level=debug msg="Clean shutdown succeeded" 

```

### PR DESCRIPTION
**Pull request by estesp**
Fixes: #17472

The `d.root` dir is resolved to the full path to the graph dir after the
daemon starts, but on restart, should be set back to the parent (without
the "<uid>.<gid>" ending) so that it uses/resolves to the same graphdir
on restart.

Docker-DCO-1.1-Signed-off-by: Phil Estes estesp@linux.vnet.ibm.com (github: estesp)

### CODE REVIEW

File: integration-cli/docker_utils.go [hunk 1]
```diff
@@ -386,6 +386,14 @@ out2:
 // Restart will restart the daemon by first stopping it and then starting it.
 func (d *Daemon) Restart(arg ...string) error {
 	d.Stop()
+	// in the case of tests running a user namespace-enabled daemon, we have resolved
+	// d.root to be the actual final path of the graph dir after the "uid.gid" of
+	// remapped root is added--we need to subtract it from the path before calling
+	// start or else we will continue making subdirectories rather than truly restarting
+	// with the same location/root:
+	if root := os.Getenv("DOCKER_REMAP_ROOT"); root != "" {
+		d.root = filepath.Clean(filepath.Join(d.root, ".."))
```
Comment (calavera) [inline integration-cli/docker_utils.go]: is `filepath.Dir` what you're looking for here?

https://golang.org/pkg/path/filepath/#Dir

Comment (estesp) [inline integration-cli/docker_utils.go]: Oh man..of course.  I blame a week of conference travel for rotting my programming brain :)  Updated..PTAL

**Comment by calavera** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM
