### PR TITLE
Output network attachment task information

### LINKED ISSUE #26548: Attaching a container to a swarm-mode overlay network panics and breaks the /tasks API
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

On the current master, attaching a container to an overlay network that is created with the `--attachable` flag results in an interface conversion panic. All further calls to the `/tasks` API return a 0-byte response.

**Steps to reproduce the issue:**

On a machine with a curl version greater than 7.40:

1. `docker swarm init`
2. `docker network create --driver overlay --attachable overnet`
3. `curl --unix-socket /var/run/docker.sock -X GET "http:/tasks"`
4. `docker run -d --net overnet alpine ping docker.com`
5. `curl --unix-socket /var/run/docker.sock -X GET "http:/tasks"`
6. Obtain the daemon logs

**Describe the results you received:**

The curl operation of step 3 returns an empty JSON array: `[]`
However, the curl operation of step 5 returns: `curl: (52) Empty reply from server`

During step 6, the following excerpt is at the tail of the daemon logs:
```
time="2016-09-13T23:16:30.296338157Z" level=debug msg="Calling GET /tasks"                                                                                                                                                                                           
2016-09-13 23:16:30.296879 I | http: panic serving @: interface conversion: api.isTaskSpec_Runtime is *api.TaskSpec_Attachment, not *api.TaskSpec_Container                                                                                                          
goroutine 720 [running]:                                                                                                                                                                                                                                             
net/http.(*conn).serve.func1(0xc4210c4880)                                                                                                                                                                                                                           
        /usr/local/go/src/net/http/server.go:1491 +0x12a                                                                                                                                                                                                             
panic(0x15d30a0, 0xc420b5c240)                                                                                                                                                                                                                                       
        /usr/local/go/src/runtime/panic.go:458 +0x243                                                                                                                                                                                                                
github.com/docker/docker/daemon/cluster/convert.TaskFromGRPC(0xc420d56d40, 0x19, 0x16, 0xc420dc7830, 0xc420dc7840, 0x21e07e0, 0xc420023d00, 0x0, 0x0, 0x0, ...)                                                                                                      
        /go/src/github.com/docker/docker/daemon/cluster/convert/task.go:13 +0xb1f                                                                                                                                                                                    
github.com/docker/docker/daemon/cluster.(*Cluster).GetTasks(0xc420136c60, 0xc420cef830, 0x0, 0x0, 0x0, 0x0, 0x0)                                                                                                                                                     
        /go/src/github.com/docker/docker/daemon/cluster/cluster.go:1160 +0x2df                                                                                                                                                                                       
github.com/docker/docker/api/server/router/swarm.(*swarmRouter).getTasks(0xc42072ced0, 0x21e5a20, 0xc420cef7a0, 0x21e23e0, 0xc420477450, 0xc4211c41e0, 0xc420cef560, 0xc420dc7001, 0xc420cef7a0)                                                                     
        /go/src/github.com/docker/docker/api/server/router/swarm/cluster_routes.go:244 +0xa5                                                                                                                                                                         
github.com/docker/docker/api/server/router/swarm.(*swarmRouter).(github.com/docker/docker/api/server/router/swarm.getTasks)-fm(0x21e5a20, 0xc420cef7a0, 0x21e23e0, 0xc420477450, 0xc4211c41e0, 0xc420cef560, 0x19, 0x4)                                              
        /go/src/github.com/docker/docker/api/server/router/swarm/cluster.go:41 +0x69                                                                                                                                                                                 
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x21e5a20, 0xc420cef620, 0x21e23e0, 0xc420477450, 0xc4211c41e0, 0xc420cef560, 0xc420022018, 0x21cdea0)                                                                            
        /go/src/github.com/docker/docker/api/server/middleware/version.go:56 +0x73c                                                                                                                                                                                  
github.com/docker/docker/api/server/middleware.UserAgentMiddleware.WrapHandler.func1(0x21e59a0, 0xc42000ede0, 0x21e23e0, 0xc420477450, 0xc4211c41e0, 0xc420cef560, 0x0, 0x0)                                                                                         
        /go/src/github.com/docker/docker/api/server/middleware/user_agent.go:45 +0x272                                                                                                                                                                               
github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1(0x21e59a0, 0xc42000ede0, 0x21e23e0, 0xc420477450, 0xc4211c41e0, 0xc420cef560, 0x756ea10ff59386, 0xc4211f8a10)                                                                             
        /go/src/github.com/docker/docker/pkg/authorization/middleware.go:34 +0x7ad                                                                                                                                                                                   
github.com/docker/docker/api/server/middleware.DebugRequestMiddleware.func1(0x21e59a0, 0xc42000ede0, 0x21e23e0, 0xc420477450, 0xc4211c41e0, 0xc420cef560, 0xc4211f8bb0, 0x8)                                                                                         
        /go/src/github.com/docker/docker/api/server/middleware/debug.go:22 +0x1a3                                                                                                                                                                                    
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x21e23e0, 0xc420477450, 0xc4211c41e0)                                                                                                                                                           
        /go/src/github.com/docker/docker/api/server/server.go:139 +0xc5                                                                                                                                                                                              
net/http.HandlerFunc.ServeHTTP(0xc42046f620, 0x21e23e0, 0xc420477450, 0xc4211c41e0)                                                                                                                                                                                  
        /usr/local/go/src/net/http/server.go:1726 +0x44                                                                                                                                                                                                              
github.com/gorilla/mux.(*Router).ServeHTTP(0xc4203b0320, 0x21e23e0, 0xc420477450, 0xc4211c41e0)                                                                                                                                                                      
        /go/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux/mux.go:103 +0x255                                                                                                                                                                         
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc4206e1640, 0x21e23e0, 0xc420477450, 0xc4211c41e0)                                                                                                                                                  
        /go/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x70                                                                                                                                                                                       
net/http.serverHandler.ServeHTTP(0xc4203c4800, 0x21e23e0, 0xc420477450, 0xc4211c41e0)                                                                                                                                                                                
        /usr/local/go/src/net/http/server.go:2202 +0x7d                                                                                                                                                                                                              
net/http.(*conn).serve(0xc4210c4880, 0x21e3ea0, 0xc420b55600)                                                                                                                                                                                                        
        /usr/local/go/src/net/http/server.go:1579 +0x4b7                                                                                                                                                                                                             
created by net/http.(*Server).Serve                                                                                                                                                                                                                                  
        /usr/local/go/src/net/http/server.go:2293 +0x44d
```

**Describe the results you expected:**

I expected an empty JSON response of `[]` for both invocations of the `/tasks` API, and no panic recorded in the daemon logs.

**Additional information you deem important (e.g. issue happens only occasionally):**

I have been able to reproduce this issue deterministically.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   9b0aacc
 Built:        Tue Sep 13 22:40:49 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   9b0aacc
 Built:        Tue Sep 13 22:40:49 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 11
Server Version: 1.13.0-dev
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 38
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host null overlay overlay
Swarm: active
 NodeID: 6mr6x6f6bmlnt206m4gtrm34p
 Is Manager: true
 ClusterID: 7dw9ufwexwd21ur8ygma5hoaw
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.122.234
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.18-boot2docker
Operating System: Boot2Docker 1.12.1 (TCL 7.2); master : a87fba7 - Tue Sep 13 23:04:59 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: node12
ID: QWTZ:RSHH:W7GZ:OLOC:OJNC:BQ76:RSH4:4AEM:X5ZA:TBR3:7G4T:LV4E
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 41
 Goroutines: 132
 System Time: 2016-09-13T23:26:06.503477393Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=kvm
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This was replicated both on an AWS m1.medium VM, running kernel version 3.16, and on a custom-built boot2docker VM running `Linux 4.4.18-boot2docker`

### LINKED ISSUE #36498: Overlay network is in use by a task that does not exist
**Description**

On our docker swarm cluster, we have some overlay networks that can't be deleted, because they appearently are in use by a task. I can't find the task, though.

**Steps to reproduce the issue:**

I don't know how to reproduce the issue. The networks have been created by docker-compose on a legacy swarm that is running on top of this docker swarm cluster. Usually this works fine, we just have 6 networks that were created that way, that can't be deleted anymore.

**Describe the results you received:**
```
[root@XXX ~]# docker network rm gerrit8837_default
Error response from daemon: rpc error: code = FailedPrecondition desc = network n4iawrsr18263xbqznepzu9r5 is in use by task 1yf3gempke5fpr0kvt1g3t82k
[root@XXX ~]# docker inspect 1yf3gempke5fpr0kvt1g3t82k
[
    {
        "ID": "",
        "Version": {},
        "CreatedAt": "0001-01-01T00:00:00Z",
        "UpdatedAt": "0001-01-01T00:00:00Z",
        "Labels": null,
        "Spec": {
            "ForceUpdate": 0
        },
        "Status": {
            "Timestamp": "0001-01-01T00:00:00Z",
            "ContainerStatus": {},
            "PortStatus": {}
        }
    }
]

```

**Describe the results you expected:**

i would expect either the network to be deleted, or at least some information in the inspect command about the task.

**Additional information you deem important (e.g. issue happens only occasionally):**

```
[root@XXX ~]# docker inspect gerrit8837_default
[
    {
        "Name": "gerrit8837_default",
        "Id": "n4iawrsr18263xbqznepzu9r5",
        "Created": "0001-01-01T00:00:00Z",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "",
            "Options": null,
            "Config": null
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": null,
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4102"
        },
        "Labels": {
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "gerrit8837"
        }
    }
]
```

**Output of `docker version`:**

```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:10:14 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:46 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**

```
Containers: 8
 Running: 8
 Paused: 0
 Stopped: 0
Images: 443
Server Version: 17.12.0-ce
Storage Driver: devicemapper
 Pool Name: docker-253:6-29360274-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Udev Sync Supported: true
 Data file: /dev/vgdocker/data
 Metadata file: /dev/vgdocker/metadata
 Data Space Used: 52.51GB
 Data Space Total: 102GB
 Data Space Available: 49.49GB
 Metadata Space Used: 56.38MB
 Metadata Space Total: 5.365GB
 Metadata Space Available: 5.308GB
 Thin Pool Minimum Free Space: 10.2GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 20pg5xwvfaann32pgdiobbhyn
 Is Manager: true
 ClusterID: jn2hmqyygkoacfwzwmk12fkdr
 Managers: 4
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 1
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.57.84.129
 Manager Addresses:
  XXX.XXX.XXX.135:2377
  XXX.XXX.XXX.136:2377
  XXX.XXX.XXX.180:2377
  XXX.XXX.XXX.181:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.11.6.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.51GiB
Name: XXX.example.com
ID: OHTV:LUXF:W2CD:NT7D:KC6M:3HO5:PSYJ:7YF7:SMYK:WRCQ:4LCE:OYOM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: http://web-proxy.emea.example.com:8080/
HTTPS Proxy: http://web-proxy.emea.example.com:8080/
No Proxy: example.com
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by dperny**
**- What I did**
Network attachment tasks are phony tasks created in swarmkit to deal with unmanaged containers attached to swarmkit. Before this change, attempting `docker inspect` on the task id of a network attachment task would result in an empty task object. After this change, a full task object is returned

Fixes #26548 the correct way.
Fixes https://github.com/moby/moby/issues/36498

**- How I did it**
Adds functionality to parse and return network attachment spec information.

**- How to verify it**
1. Create a network like `docker network create --driver overlay --attachable testnet`
1. Attach a container like `docker run -d --network testnet nginx`
1. Try to delete the network `docker network rm testnet`. Note that it will return an error because the network is in use, and that error will include a task id.
1. `docker inspect` the task id from the previous spec.

Before this change, the output of the inspect will be an empty task.
After this change, the output will be a full task object, including the ID of the container that this task represents.

**- Description for the changelog**

Running `docker inspect` on network attachment tasks now returns a full task object

### CODE REVIEW

**Comment by dperny** [comment]
Failure are unrelated to the PR.

**Comment by dperny** [comment]
🎉  It's green 🎉

File: api/types/swarm/task.go [hunk 1]
```diff
@@ -56,10 +56,12 @@ type Task struct {
...
 type TaskSpec struct {
-	// ContainerSpec and PluginSpec are mutually exclusive.
+	// ContainerSpec, AttachmentSpec and PluginSpec are mutually exclusive.
 	// PluginSpec will only be used when the `Runtime` field is set to `plugin`
-	ContainerSpec *ContainerSpec      `json:",omitempty"`
-	PluginSpec    *runtime.PluginSpec `json:",omitempty"`
+	// AttachmentSpec will be used when the `Runtime` field is set to `attachment`
+	ContainerSpec         *ContainerSpec         `json:",omitempty"`
+	PluginSpec            *runtime.PluginSpec    `json:",omitempty"`
+	NetworkAttachmentSpec *NetworkAttachmentSpec `json:",omitempty"`
```
Comment (cpuguy83) [inline api/types/swarm/task.go]: I think we may need to error out on swarm create/update if it includes a NetworkAttachmentSpec?

**Comment by cpuguy83** [comment]
Putting this in design review as it's an API change with a few potential implications.

File: api/types/swarm/task.go (hunk 1 above)
Comment (thaJeztah) [reply api/types/swarm/task.go]: Should we have a separate type for inspect vs create? I know we're reusing some types at various locations (sometimes resulting in information being shown that happens to be there, but is not needed)

Comment (cpuguy83) [reply api/types/swarm/task.go]: I don't think a separate type is such a good idea. This is the task spec, having the task spec in the inspect output I think is hugely important.

**Comment by thaJeztah** [comment]
@dperny would it be possible to have the error message show the _container id_ instead of the task if it's a container that's attached to the network?

**Comment by thaJeztah** [comment]
Discussing with @cpuguy83 and @vieux, and moving to code review again

**Comment by thaJeztah** [comment]
Also needs an update to the swagger.yml

**Comment by dperny** [comment]
Does not need an update for creation and deletion, because it will already fail with an appropriate error, see: https://github.com/moby/moby/blob/master/daemon/cluster/convert/service.go#L202-L203

**Comment by dperny** [comment]
@cpuguy83 updated to prevent write operations with network attachment runtime specs. Also fixed some edge cases in runtime type conversion in the process.

**Comment by thaJeztah** [comment]
CI failing on a godoc;

```
20:38:37 daemon/cluster/convert/service.go:20:2:warning: comment on exported var ErrMismatchedRuntime should be of the form "ErrMismatchedRuntime ..." (golint)

**Comment by dperny** [comment]
rebased.

File: daemon/cluster/convert/service.go [hunk 2]
```diff
@@ -198,6 +203,21 @@ func ServiceSpecToGRPC(s types.ServiceSpec) (swarmapi.ServiceSpec, error) {
 					},
 				},
 			}
+		} else {
+			return swarmapi.ServiceSpec{}, ErrMismatchedRuntime
+		}
+	case types.RuntimeNetworkAttachment:
+		// agree to parse this runtime type, but it's not actually valid to
+		// create a service with this runtime type. but that logic is someone
```
Comment (thaJeztah) [inline daemon/cluster/convert/service.go]: whose responsibility is it? do we check for this situation? (because this looks to be the code you referred to to produce a proper error in https://github.com/moby/moby/pull/35246#issuecomment-340541386)

Comment (thaJeztah) [reply daemon/cluster/convert/service.go]: ping @dperny ^^

**Comment by dperny** [comment]
Thanks for the reminder @thaJeztah. I've fixed your comment and rebased. Sorry about the poor attention.

**Review by thaJeztah — APPROVED** [review]
LGTM, but can you also add a note in the API version history; https://github.com/moby/moby/blob/master/docs/api/version-history.md ?

File: api/types/swarm/task.go [hunk 3]
```diff
@@ -56,10 +56,12 @@ type Task struct {
 
 // TaskSpec represents the spec of a task.
 type TaskSpec struct {
-	// ContainerSpec and PluginSpec are mutually exclusive.
+	// ContainerSpec, AttachmentSpec and PluginSpec are mutually exclusive.
```
Comment (thaJeztah) [inline api/types/swarm/task.go]: s/AttachmentSpec/NetworkAttachmentSpec/`

File: api/types/swarm/task.go [hunk 4]
```diff
@@ -56,10 +56,12 @@ type Task struct {
...
 	// PluginSpec will only be used when the `Runtime` field is set to `plugin`
-	ContainerSpec *ContainerSpec      `json:",omitempty"`
-	PluginSpec    *runtime.PluginSpec `json:",omitempty"`
+	// AttachmentSpec will be used when the `Runtime` field is set to `attachment`
```
Comment (thaJeztah) [inline api/types/swarm/task.go]: s/AttachmentSpec/NetworkAttachmentSpec/`

File: api/swagger.yaml [hunk 5]
```diff
@@ -2683,6 +2683,13 @@ definitions:
               - "default"
               - "process"
               - "hyperv"
+      NetworkAttachmentSpec:
+        description: "Read-only spec type for non-swarm containers attached to swarm overlay networks"
```
Comment (thaJeztah) [inline api/swagger.yaml]: Think we can use a common description for these being mutually exclusive (let me add a commit to address that)

**Review by thaJeztah — CHANGES_REQUESTED** [review]
Saw some other nits; let me rebase this one, and make those changes

File: api/swagger.yaml [hunk 6]
```diff
@@ -2688,6 +2704,22 @@ definitions:
...
+        description: |
+          Read-only spec type for non-swarm containers attached to swarm overlay
+          networks.
+
+          <p><br /></p>
+
+          > **Note**: ContainerSpec, NetworkAttachmentSpec, and PluginSpec are
+          > mutually exclusive. PluginSpec is only used when the Runtime field
+          > is set to `plugin`. NetworkAttachmentSpec is used when the Runtime
+          > field is set to `attachment`.
```
Comment (thaJeztah) [inline api/swagger.yaml]: @dperny I took this description from the type godoc; let me know if you think these look correct

**Comment by thaJeztah** [comment]
Arf... Windows cleanup script before CI started hung

```
21:40:19 INFO: Nuke-Everything...
21:40:19 INFO: Container count on control daemon to delete is 0
01:00:14 Build timed out (after 200 minutes). Marking the build as failed.
```

**Review by boaz0 — APPROVED** [review]
Code LGTM

**Comment by thaJeztah** [comment]
oh... hm, just realised the API version itself wasn't bumped yet 😓 - there's a couple PR's adding new things to the API (https://github.com/moby/moby/pull/36914, https://github.com/moby/moby/pull/37043, https://github.com/moby/moby/pull/36720), so it would be a race which one got merged first :joy: - given that this one's green now, I can also do it in a follow-up

**Review by thaJeztah — APPROVED** [review]
LGTM'ing because I addressed my earlier comments, but I'm obviously biased now, so need other reviewers :joy:

**Review by vdemeester — APPROVED** [review]
SGTM :tiger: 
On the API update, we're probably gonna bump the API number on an external PR :angel:

**Review by cpuguy83 — APPROVED** [review]
LGTM
