### PR TITLE
API return network-list if no network-name or id is provided

### LINKED ISSUE #24595: `GET /networks/` inspects the bridge network
**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.2
 Git commit:   906c1dc
 Built:        Fri Jun 17 16:48:48 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.2
 Git commit:   906c1dc
 Built:        Fri Jun 17 16:48:48 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: active
 NodeID: cjz9ffldhgrc2r5v4zj5vvmbi
 IsManager: Yes
 Managers: 1
 Nodes: 1
 CACertHash: sha256:9e85419452564689e7f8a5c72069ae4abe7a7e1ff48958a024e1451cc7c89d7a
Runtimes: default
Default Runtime: default
Security Options: apparmor seccomp
Kernel Version: 4.2.0-23-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: manager1
ID: 7SAZ:IYHI:XB25:GMRN:OLUS:ERHX:4LAL:2S7A:KLYS:EDL6:GAZM:PQGX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 35
 Goroutines: 109
 System Time: 2016-07-13T11:34:31.825999312-07:00
 EventsListeners: 0
Username: mikegoelzer
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Virtualbox

**Steps to reproduce the issue:**
```
$ curl --unix-socket /var/run/docker.sock http:/networks/ | jq .
```

**Describe the results you received:**
```
{
  "Name": "bridge",
  "Id": "63eb8a3bd519a737a1eadaa5143dd89ee832be08c8370f94a8c9f1dc7f7affde",
  "Scope": "local",
  "Driver": "bridge",
  "EnableIPv6": false,
  "IPAM": {
    "Driver": "default",
    "Options": null,
    "Config": [
      {
        "Subnet": "172.17.0.0/16",
        "Gateway": "172.17.0.1"
      }
    ]
  },
  "Internal": false,
  "Containers": {},
  "Options": {
    "com.docker.network.bridge.default_bridge": "true",
    "com.docker.network.bridge.enable_icc": "true",
    "com.docker.network.bridge.enable_ip_masquerade": "true",
    "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
    "com.docker.network.bridge.name": "docker0",
    "com.docker.network.driver.mtu": "1500"
  },
  "Labels": {}
}
```

**Describe the results you expected:**
I would either expect an error (because I am trying to inspect a network with an empty name) or a list of all networks (if it ignores the trailing slash).

**Additional information you deem important (e.g. issue happens only occasionally):**
Swarm mode is enabled

### PR DESCRIPTION
**Pull request by thaJeztah**
When calling the `/networks/` endpoint (with a trailing slash), the default network was returned.

This changes the endpoint to return the list of networks instead.

Also updated the description for GetNetworkByName to
explain that the "default" network is returned if
no name or id is provided.

closes https://github.com/docker/docker/issues/24595

### CODE REVIEW

**Comment by thaJeztah** [comment]
Note that I also tried a different approach, and changing the route; https://github.com/docker/docker/blob/v1.12.0-rc4/api/server/router/network/network.go#L33-L34

```patch
diff --git a/api/server/router/network/network.go b/api/server/router/network/network.go
index 8688c3e..45548b5 100644
--- a/api/server/router/network/network.go
+++ b/api/server/router/network/network.go
@@ -31,7 +31,7 @@ func (r *networkRouter) initRoutes() {
        r.routes = []router.Route{
                // GET
                router.NewGetRoute("/networks", r.getNetworksList),
-               router.NewGetRoute("/networks/{id:.*}", r.getNetwork),
+               router.NewGetRoute("/networks/{id:.+}", r.getNetwork),
                // POST
                router.NewPostRoute("/networks/create", r.postNetworkCreate),
                router.NewPostRoute("/networks/{id:.*}/connect", r.postNetworkConnect),
```

This gives a different result (a 404 error with a "page not found"); perhaps doing that would break more clients that look for the return message, so I didn't use that;

```
/ # curl -sv --unix-socket /var/run/docker.sock http:/networks/
*   Trying /var/run/docker.sock...
* Connected to http (/var/run/docker.sock) port 80 (#0)
> GET /networks/ HTTP/1.1
> Host: http
> User-Agent: curl/7.49.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Type: application/json
< Date: Thu, 14 Jul 2016 12:38:29 GMT
< Content-Length: 29
<
{"message":"page not found"}
* Connection #0 to host http left intact
```

So I'm open to suggestions what the better approach is :smile:

ping @mgoelzer @aboch

File: api/server/router/network/network_routes.go [hunk 1]
```diff
@@ -56,6 +56,10 @@ func (n *networkRouter) getNetwork(ctx context.Context, w http.ResponseWriter, r
 		return err
 	}
 
+	if vars["id"] == "" {
+		return libnetwork.ErrNoSuchNetwork(vars["id"])
```
Comment (thaJeztah) [inline api/server/router/network/network_routes.go]: we could use 

```golang
libnetwork.ErrNoSuchNetwork("(empty string)")
```

to be more explicit

**Comment by justincormack** [comment]
cc @bfirsh who obsesses details of API behaviour...

**Comment by bfirsh** [comment]
:+1:

Changing the route to `.+` seems neater but for consistency with other routes your approach seems best.

Are `POST /networks/id/connect`, `/networks/id/disconnect`, `DELETE /networks/id` affected by this too?

**Comment by thaJeztah** [comment]
> Are POST /networks/id/connect, /networks/id/disconnect, DELETE /networks/id affected by this too?

@bfirsh I'll check, but looking at those I think we can change those to `../{id:.+}/disconnect`, as I don't think supporting `/network//disconnect` would make a lot of sense (having a standard 404 for those should be okay). I'll check those

File: api/server/router/network/network_routes.go (hunk 1 above)
Comment (cpuguy83) [inline api/server/router/network/network_routes.go]: I feel like this should be an impossibility.

Comment (thaJeztah) [inline api/server/router/network/network_routes.go]: See the repro case at the top; probably not possible through the CLI, but it's possible to get there when directly using the API

Comment (cpuguy83) [inline api/server/router/network/network_routes.go]: Changing to `{id}` instead of `{id:.*}` seems to do the trick.

Comment (thaJeztah) [inline api/server/router/network/network_routes.go]: @cpuguy83 yes, see above (https://github.com/docker/docker/pull/24634#issuecomment-232663451), but that would change the response from the current error (if an invalid name is provided); I wasn't sure if we wanted to risk that. Also see https://github.com/docker/docker/pull/24634#issuecomment-232722602

Comment (cpuguy83) [inline api/server/router/network/network_routes.go]: We can just add an explicit route for the trailing slash:
```
router.NewGetRoute("/networks/", r.getNetworksList),
```

Displaying the bridge inspect for `/networks/` is a bug.

**Comment by LK4D4** [comment]
@thaJeztah what's up here?

**Comment by thaJeztah** [comment]
I think we can merge, but perhaps @cpuguy83 wants the other approach

**Comment by vdemeester** [comment]
I do agree with @cpuguy83 on that one

> We can just add an explicit route for the trailing slash:
> ```
> router.NewGetRoute("/networks/", r.getNetworksList),
> ```
> 
> Displaying the bridge inspect for `/networks/` is a bug.

**Comment by thaJeztah** [comment]
Updated the PR to make `/networks` and `/networks/` return the same results

**Comment by thaJeztah** [comment]
ping @cpuguy83 @vdemeester PTAL

**Review by vdemeester — APPROVED** [review]
LGTM :frog:

**Comment by thaJeztah** [comment]
rebased. ping @cpuguy83 PTAL

**Comment by cpuguy83** [comment]
LGTM

**Comment by thaJeztah** [comment]
rebased (again) 😅

**Comment by thaJeztah** [comment]
boo, flaky test?

```
20:08:46 ----------------------------------------------------------------------
20:08:46 FAIL: docker_cli_attach_unix_test.go:18: DockerSuite.TestAttachClosedOnContainerStop
20:08:46 
20:08:46 docker_cli_attach_unix_test.go:51:
20:08:46     c.Assert(err, check.IsNil)
20:08:46 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc4204f20a0), Stderr:[]uint8(nil)} ("exit status 1")
20:08:46 
20:08:47 
```
