### PR TITLE
daemon/graphdriver/overlay2: set TarOptions.InUserNS for native differ (fix "failed to Lchown "/dev/console")

### LINKED ISSUE #1497: Docker Pull Fails in Rootless "failed to register layer: failed to Lchown "/dev/console" for UID 0, GID 0: lchown /dev/console: no such file or directory"
Hey folks!

I am trying to pull the mysql:8.2.0 / mysql:latest image in rootless docker

Expected behavior:
- Pull goes through

actual behavior:
```failed to register layer: failed to Lchown "/dev/console" for UID 0, GID 0: lchown /dev/console: no such file or directory```

subuid:
docker-admin:100000:65536

subgid:
docker-admin:100000:65536

Outpout of Docker Version:
```
Client: Docker Engine - Community
 Version:           27.0.1
 API version:       1.46
 Go version:        go1.21.11
 Git commit:        7fafd33
 Built:             Mon Jun 24 14:58:03 2024
 OS/Arch:           linux/amd64
 Context:           rootless

Server: Docker Engine - Community
 Engine:
  Version:          27.0.1
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       ff1e2c0
  Built:            Mon Jun 24 14:58:03 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.33
  GitCommit:        d2d58213f83a351ca8f528a95fbd145f5654e957
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
 rootlesskit:
  Version:          2.0.2
  ApiVersion:       1.1.1
  NetworkDriver:    slirp4netns
  PortDriver:       builtin
  StateDir:         /run/user/1000/dockerd-rootless
 slirp4netns:
  Version:          1.2.1
  GitCommit:        09e31e92fa3d2a1d3ca261adaeb012c8d75a8194
  
```

Output of docker info:
```
Client: Docker Engine - Community
 Version:    27.0.1
 Context:    rootless
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.15.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.28.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 5
  Running: 5
  Paused: 0
  Stopped: 0
 Images: 8
 Server Version: 27.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d2d58213f83a351ca8f528a95fbd145f5654e957
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  rootless
  cgroupns
 Kernel Version: 6.8.0-35-generic
 Operating System: Ubuntu 24.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.731GiB
 Name: sf-docker1
 ID: 002f2b39-30a0-4a59-b858-68615345db5d
 Docker Root Dir: /home/docker-admin/.local/share/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No cpuset support
WARNING: No io.weight support
WARNING: No io.weight (per device) support
WARNING: No io.max (rbps) support
WARNING: No io.max (wbps) support
WARNING: No io.max (riops) support
WARNING: No io.max (wiops) support
```

### LINKED ISSUE #48064: [27.0 regression] Docker Pull Fails in Rootless "failed to register layer: failed to Lchown "/dev/console"
### Description

With the release of v27, we're unable to pull a certain image from Docker Hub:

```
failed to register layer: failed to Lchown "/dev/console" for UID 0, GID 0: lchown /dev/console: no such file or directory
```

In addition, when trying to use a registry mirror, we get the following error even though the mirror isn't listening on `443` (it is on localhost however):

```
Get "https://registry-1.docker.io/v2/": dial tcp 127.0.0.1:443: connect: connection refused
```

### Reproduce

1. Install `docker-ce:5:27.0.1-1~debian.12~bookworm` in a rootless mode (I haven't tested normal mode)
2. `docker pull mysql:8.0.33-oracle`

### Expected behavior

The image should be able to pulled.

### docker version

```bash
Client: Docker Engine - Community
 Version:           27.0.1
 API version:       1.46
 Go version:        go1.21.11
 Git commit:        7fafd33
 Built:             Mon Jun 24 14:58:05 2024
 OS/Arch:           linux/amd64
 Context:           rootless

Server: Docker Engine - Community
 Engine:
  Version:          27.0.1
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       ff1e2c0
  Built:            Mon Jun 24 14:58:05 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.18
  GitCommit:        ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
 runc:
  Version:          1.7.18
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
 rootlesskit:
  Version:          2.0.2
  ApiVersion:       1.1.1
  NetworkDriver:    slirp4netns
  PortDriver:       builtin
  StateDir:         /run/user/999/dockerd-rootless
 slirp4netns:
  Version:          1.2.0
  GitCommit:        656041d45cfca7a4176f6b7eed9e4fe6c11e8383
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    27.0.1
 Context:    rootless
WARNING: No cpuset support
WARNING: No io.weight support
 Debug Mode: false
WARNING: No io.weight (per device) support
WARNING: No io.max (rbps) support
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.15.1
WARNING: No io.max (wbps) support
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
WARNING: No io.max (riops) support
  compose: Docker Compose (Docker Inc.)
WARNING: No io.max (wiops) support
    Version:  v2.28.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 8
 Server Version: 27.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  rootless
  cgroupns
 Kernel Version: 6.1.0-21-cloud-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.63GiB
 Name: packer
 ID: bbe714f9-4b00-4010-9c93-0cabbbe25a84
 Docker Root Dir: /var/lib/buildkite-agent/.local/share/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by thaJeztah**
- fixes https://github.com/moby/moby/issues/48064
- fixes https://github.com/docker/for-linux/issues/1497
- relates to / introduced in https://github.com/moby/moby/pull/47605

### pkg/archive: getWhiteoutConverter: don't error with userns enabled

Since 838047a1f5bf47aa65eb6901a20abdb5ab9b640a, the overlayWhiteoutConverter
is supported with userns enabled, so we no longer need this check.

### pkg/archive: handleTarTypeBlockCharFifo: don't discard EPERM errors

This function was discarding EPERM errors if it detected that userns was
enabled; move such checks to the caller-site, so that they can decide
how to handle the error (which, in case of userns may be to log and ignore).

### pkg/archive: createTarFile: consistently use the same value for userns

createTarFile accepts a opts (TarOptions) argument to specify whether
userns is enabled; whe should consider always detecting locally, but
at least make sure we're consistently working with the same value within
this function.

### daemon/graphdriver/overlay2: set TarOptions.InUserNS for native differ

Commits b2fd67de77be8692ff343d26a9819a3c42ef8c2f (and the follow-up commit
f6b80253b8bfc04b9a6ef0e6bd73e44d36778046) updated doesSupportNativeDiff to
detect whether the host can support native overlay diffing with userns
enabled.

As a result, [useNaiveDiff] would now return "false" in cases where it
previously would return "true" (and thus skip). However, [overlay2],
unlike [fuse-overlay] did not take user namespaces into account, when
using the native differ, and it therefore did not set the InUserNS option
in TarOptions.

As a result pkg/archive.createTarFile would attempt tocreate [device-nodes]
through [handleTarTypeBlockCharFifo] which would fail, but the resulting
error `EPERM` would be discarded, and `createTarFile` would not return
early, therefor attempting to [os.LChown] the missing file, ultimately
resulting in an error:

    failed to Lchown "/dev/console" for UID 0, GID 0: lchown /dev/console: no such file or directory

This patch fixes the missing option in overlay.

[useNaiveDiff]: https://github.com/moby/moby/blob/47eebd718f332f29a38455b61ee879ced5bc219b/daemon/graphdriver/overlay2/overlay.go#L248-L256
[overlay2]: https://github.com/moby/moby/blob/47eebd718f332f29a38455b61ee879ced5bc219b/daemon/graphdriver/overlay2/overlay.go#L684-L689
[fuse-overlay]: https://github.com/moby/moby/blob/47eebd718f332f29a38455b61ee879ced5bc219b/daemon/graphdriver/fuse-overlayfs/fuseoverlayfs.go#L456-L462
[device-nodes]: https://github.com/moby/moby/blob/ff1e2c0de72a1bbbe4cdbe1558da57d327899df5/pkg/archive/archive.go#L713-L720
[handleTarTypeBlockCharFifo]: https://github.com/moby/moby/blob/47eebd718f332f29a38455b61ee879ced5bc219b/pkg/archive/archive_unix.go#L110-L114
[os.LChown]: https://github.com/moby/moby/blob/ff1e2c0de72a1bbbe4cdbe1558da57d327899df5/pkg/archive/archive.go#L762-L773

**- Description for the changelog**

```markdown changelog
Fix "fail to register layer: failed to Lchown" errors when trying to pull an image with rootless enabled on a system that supports native overlay with user-namespaces.
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: pkg/archive/archive.go [hunk 1]
```diff
@@ -722,6 +724,11 @@ func createTarFile(path, extractDir string, hdr *tar.Header, reader io.Reader, o
 	case tar.TypeFifo:
 		// Handle this is an OS-specific way
 		if err := handleTarTypeBlockCharFifo(hdr, path); err != nil {
+			if inUserns && errors.Is(err, syscall.EPERM) {
+				// In most cases, cannot create a fifo if running in user namespace
```
Comment (dmcgowan) [inline pkg/archive/archive.go:728]: Beside the previous code stumbled into this, is Fifo really something we don't expect to be working. In containerd we don't skip Fifo for user namespaces.

**Review by dmcgowan — APPROVED** [review]

File: pkg/archive/archive.go (hunk 1 above)
Comment (thaJeztah) [reply pkg/archive/archive.go:728]: I went a bit back-and-forth on both of these;

- changed all of `TypeFifo`,  `TypeBlock`, and `TypeChar` to try optimistically (but log the error on failure); this in the line of thought "who knows? one day it may work?"
- or the reverse; anticipating it won't work, so skip for `useNs`

In the end, I decided to keep the current behavior for now, but perhaps that's something we should revisit, WDYT?

Comment (dmcgowan) [reply pkg/archive/archive.go:728]: I think keep current behavior is right for the scope of this. Just the behavior difference was sticking out more so wanted to mention it.

Comment (thaJeztah) [reply pkg/archive/archive.go:728]: Yup, same! It also was a bit my motivation for moving the error-handling out of `handleTarTypeBlockCharFifo` - I wanted to make it more visible / explicit where we're ignoring errors.

**Review by corhere — APPROVED** [review]

**Comment by thaJeztah** [comment]
I'll bring this one in, and move the backport out of draft.
