### PR TITLE
Fix `DockerNetworkInternalMode` issue

### LINKED ISSUE #35963: Networking related bugs in the latest busybox image on x86?
**Description**
Since the PR #35929 always makes the test case `TestDockerNetworkInternalMode` failed on amd64 and arm{32,64} platforms, so I decide to dig into what the root cause is. After some investigation, I found an interesting scenario:
For the latest busybox 1.27, the `ping` command between 2 busybox container daemons will not succeed. See the below steps for more detail.

**Steps to reproduce the issue:**
1.  pull the 1.27.2 busybox images with `docker pull busybox:latest@sha256:bbc3a03235220b170ba48a157dd097dd1379299370e1ed99ce976df0355d24f0`, the image id is `6ad733544a63`
2. pull the 1.26 busybox images with `docker pull busybox:latest@sha256:32f093055929dbc23dec4d03e09dfe971f5973a9ca5cf059cbfb644c206aa83f`, the image id is `00f017a8c2a6` 
3. According to the testing steps in  `TestDockerNetworkInternalMode`, I input below commands:
3.a  `docker network create --driver=bridge --internal internal`
3.b  Launch 4 busybox docker daemons:
```
      `docker run -d --net=internal --name=first-1.27 6ad733544a63 top`
      `docker run -d --net=internal --name=second-1.27 6ad733544a63 top`
      `docker run -d --net=internal --name=first-1.26  00f017a8c2a6 top`
      `docker run -d --net=internal --name=second-1.26  00f017a8c2a6 top`
```
3.c  `ping` between 2 daemons (both are the same version of busybox):
```
# docker exec second-1.26 ping -c1 first-1.26
PING first2 (172.18.0.6): 56 data bytes
64 bytes from 172.18.0.6: seq=0 ttl=64 time=0.069 ms
--- first2 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss

# docker exec second-1.27 ping -c1 first-1.27
ping: bad address 'first-1.27'
```
**Describe the results you received:**
`ping` command fails between 2 busybox damons with 1.27 version

**Describe the results you expected:**
`ping` command should be success between 2 busybox damons with 1.27 version like version 1.26 is. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.07.0-dev
 API version:  1.31
 Go version:   go1.8.3
 Git commit:   2eac0bb7
 Built:        Thu Jul 20 06:11:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      dev
 API version:  1.36 (minimum version 1.12)
 Go version:   go1.9.2
 Git commit:   d4240db
 Built:        Tue Jan  9 06:52:01 2018
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 8
 Running: 7
 Paused: 0
 Stopped: 1
Images: 73
Server Version: dev
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.11.7
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 11.66GiB
Name: dennis-ws
ID: RNF4:PMNH:GSJ7:ATEN:PHVN:D5OE:RHLD:HCR5:XLKB:7IKW:DDXB:3OZ4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: arm64b
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by arm64b**
This PR include:
1. Unify the frozen image of `busybox` to the multi-arch `glibc` version on all available arches, and remove the temp workaround to address the compatible issue on `amd64` introduced by PR #35929, which made a trade-off to use the old version `busybox` on `amd64` order to bypass the `TestDockerNetworkInternalMode` test case failure, but this issue can be reproduced repeatedly on our local `arm64` servers. 

2. Fix the failure issue of test case `TestDockerNetworkInternalMode` on both `amd64` and `arm{32,64}` arches. The root cause is current `busybox:latest` image is literally `busybox:uclibc` while not `busybox:glibc` [1].

[1].  https://github.com/docker-library/official-images/blob/c85c21613ee36a8c7f80ea3a78cd373337709d02/library/busybox#L47 

closes #35963 

**- What I did**
Fix the failure of test case `DockerNetworkInternalMode` 
**- How I did it**
Use `busybox:glibc` instead of `busybox:latest`
**- How to verify it**
`make test-integration`
**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM 🐯

**Comment by vdemeester** [comment]
Hum, build failure on janky and experimental

```
06:42:39 FAIL: docker_api_swarm_test.go:911: DockerSwarmSuite.TestAPISwarmHealthcheckNone
06:42:39 
06:42:39 [da557da986325] waiting for daemon to start
06:42:39 [da557da986325] daemon started
06:42:39 
06:42:39 docker_api_swarm_test.go:933:
06:42:39     c.Assert(err, checker.IsNil, check.Commentf(out))
06:42:39 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc42077f900), Stderr:[]uint8(nil)} ("exit status 1")
06:42:39 ... ping: bad address 'top'
06:42:39 
06:42:39 
06:42:39 [da557da986325] exiting daemon
```

**Comment by arm64b** [comment]
Hello @vdemeester , just checked the CI results, seems we need to change `busybox:latest` to `busybox:glibc` for all the network related test cases, I am forcing an update push and see the result🤗

File: integration-cli/docker_cli_network_unix_test.go [hunk 1]
```diff
@@ -1643,9 +1643,13 @@ func (s *DockerSuite) TestDockerNetworkInternalMode(c *check.C) {
...
 
-	dockerCmd(c, "run", "-d", "--net=internal", "--name=first", "busybox", "top")
+	// Current `busybox:latest` is literally `busybox:uclibc` on amd64 and arm{32,64}, refer to:
+	// https://github.com/docker-library/official-images/blob/c85c21613ee36a8c7f80ea3a78cd373337709d02/library/busybox#L47
+	// `busybox:uclibc` image will result in this test case fail like "ping: bad address"
+	// We narrow down this issue to `busybox:latest` and keep track this with the comment here
+	dockerCmd(c, "run", "-d", "--net=internal", "--name=first", "busybox:glibc", "top")
 	c.Assert(waitRun("first"), check.IsNil)
-	dockerCmd(c, "run", "-d", "--net=internal", "--name=second", "busybox", "top")
+	dockerCmd(c, "run", "-d", "--net=internal", "--name=second", "busybox:glibc", "top")
```
Comment (thaJeztah) [inline integration-cli/docker_cli_network_unix_test.go]: If we need the `glibc` version of busybox; should it be included in the frozen images?

**Review by thaJeztah — CHANGES_REQUESTED** [review]

File: integration-cli/docker_cli_network_unix_test.go (hunk 1 above)
Comment (arm64b) [reply integration-cli/docker_cli_network_unix_test.go]: Ah, absolutely I have no objection to add the `busybox:glibc` into the frozen images if we really have somehow subtle requirements to point the `busybox:latest` to the `uclibc` version meaning this will not be changed in the future. If the answer is yes, then I am glad to add the `glibc` version as frozen image...

Comment (arm64b) [reply integration-cli/docker_cli_network_unix_test.go]: Hmm, I also remember that the `busybox:latest` point to `uclibc` only happens on `amd64` and `arm{32,64}` architectures, that's why the `powerpc` and `s390x` feel comfortable with this changes 😄 IIRC, @tianon perfer to use `busybox:glibc` instead of `busybox:latest` as the frozen images since he is pretty sure `glibc` version is available on all the necessary architectures.

IMO we can use `glibc` version (not frozen, just as this PR's) as interim solution if no side-effect (e.g, all the CI passed) in case of `latest` --> `uclibc` on `amd64` and `arm64` is volatile, but if there's some unknown reason the `latest` --> `uclibc` is mandatory on `{amd, arm}64`, then we can think about to make `glibc` as frozen image

**Comment by arm64b** [comment]
Oops, according to the CI, I have to confess that just replace the `busybox:latest` with `busybox:glibc` is not a good idea. So I decide to switch to frozen way 😵

**Comment by arm64b** [comment]
The last working day before the upcoming one-week public holiday🤗 I've frozen the `busybox:glibc` image (re-tagged as `busybox:latest`) into the container.  @vdemeester , @thaJeztah , @tianon and @dnephin , feel free to give the comment/feedback, I will handle it after the holiday if any.  I think current method is a reasonable way to address the issue, let's see the CI result (please help to rebuild it if obviously flaky ones 👼) . Thanks you all!! 🥇

**Review by vdemeester — COMMENTED** [review]
SGTM

**Review by dnephin — APPROVED** [review]
LGTM

**Comment by tianon** [comment]
Long term I think it'd be better to simply use `busybox:glibc` explicitly (in the `Dockerfile`, in that loading function, and in all the tests) instead of re-tagging it as `busybox:latest`, but this should be fine.

LGTM

**Comment by thaJeztah** [comment]
Oh, right, hm, my first thought was to _add_ the `glibc` variant as an extra  frozen image, then the tests that needed it could use that version. Updating _all_ tests would be a bit disruptive I guess;

```bash
git grep busybox | wc -l
1999
```

File: Dockerfile [hunk 2]
```diff
@@ -168,10 +168,9 @@ RUN echo "source $PWD/hack/make/.integration-test-helpers" >> /etc/bash.bashrc
 
 # Get useful and necessary Hub images so we can "docker load" locally instead of pulling
 COPY contrib/download-frozen-image-v2.sh /go/src/github.com/docker/docker/contrib/
-# TODO: when issue #35963 fixed, we can upgrade the busybox to multi-arch
 RUN ./contrib/download-frozen-image-v2.sh /docker-frozen-images \
 	buildpack-deps:jessie@sha256:dd86dced7c9cd2a724e779730f0a53f93b7ef42228d4344b25ce9a42a1486251 \
-	busybox:latest@sha256:32f093055929dbc23dec4d03e09dfe971f5973a9ca5cf059cbfb644c206aa83f \
+	busybox:1.27-glibc@sha256:8c8f261a462eead45ab8e610d3e8f7a1e4fd1cd9bed5bc0a0c386784ab105d8e \
```
Comment (thaJeztah) [inline Dockerfile]: @tianon are all these images now multi-arch? If so, we could unify these (perhaps even have a single Dockerfile for all arch's)

**Review by thaJeztah — APPROVED** [review]
So, yes, I think "explicit" would be a bit cleaner; could you do a follow up after your vacation?

LGTM

**Comment by thaJeztah** [comment]
And Happy New Year 🎉

File: Dockerfile (hunk 2 above)
Comment (tianon) [reply Dockerfile]: Yes, absolutely -- I'd love to finally see a single `Dockerfile` for all architectures! :smile: :+1:

**Comment by tianon** [comment]
I would definitely be +1 to instead pulling both `busybox:latest` _and_ `busybox:glibc` and only using `busybox:glibc` in the problematic tests, but the re-tagging `busybox:glibc` as `busybox:latest` does strike me as hacky.

File: Dockerfile (hunk 2 above)
Comment (arm64b) [reply Dockerfile]: Ah, I will +1 absolutely for this 👍  As the 1st step I can see is to merge the `Dockerfile.aarch64` into the `Dockerfile` as an experiment, then the firework is burning... 😄

**Comment by arm64b** [comment]
>So, yes, I think "explicit" would be a bit cleaner; could you do a follow up after your vacation?
>I would definitely be +1 ...

Absolutely! I will push another PR try to make the "explicit" happy. But keep in mind that, if we have a workable `busybox:latest`, then all those in one box is not necessary. Now since we can't tell it's a moby or `busybox` image issue (will be a very time-consuming process probably), so comes the reason why the codes we are now 💫
