### PR TITLE
c8d/builder: Fix missing `image tag` event with BuildKit

### LINKED ISSUE #45405: c8d: Send image events when building an image
### Description

With the containerd integration we are using buildkit's `exporterimage` to save the image, this exporter doesn't send out any image events, we need to wrap this exporter and add the `tag` event when an image is exported by buildkit.

### Reproduce

1. run `docker events`
2. build an image `docker build -t test .`

### Expected behavior

You should see an event in the terminal where you ran `docker events`

### docker version

```bash
Happens on `master` with the `containerd-snapshotter` feature enabled
```

### docker info

```bash
Happens on `master` with the `containerd-snapshotter` feature enabled
```

### Additional Info

Related: https://github.com/moby/moby/pull/45404

_No response_

### PR DESCRIPTION
**Pull request by vvoland**
The builder `Named` callback was not called with the containerd image store integration enabled and BuildKit due to wrong `imageexporter` output key being used.

We have a test `TestBuildEmitsEvents` that should have detected the bug, but it wasn't actually working because the CLI version used in the `integration-cli` doesn't support BuildKit.

**- How to verify it**
`TestBuildEmitsEvents`

**- Human readable description for the release notes**

```markdown changelog
containerd image store: Fix `image tag` event not being emitted when building with BuildKit.
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: integration-cli/docker_cli_build_test.go [hunk 1]
```diff
@@ -6247,7 +6255,7 @@ func (s *DockerCLIBuildSuite) TestBuildEmitsEvents(t *testing.T) {
 						"--since", before.Format(time.RFC3339),
 					),
 					cli.WithTimeout(time.Millisecond*300),
-					cli.WithEnvironmentVariables("DOCKER_API_VERSION=v1.46"), // FIXME(thaJeztah): integration-cli runs docker CLI 17.06; we're "upgrading" the API version to a version it doesn't support here ;)
+					cli.WithEnvironmentVariables("DOCKER_API_VERSION=v1.46"), // FIXME(thaJeztah): integration-cli runs docker CLI 18.06; we're "upgrading" the API version to a version it doesn't support here ;)
```
Comment (vvoland) [inline integration-cli/docker_cli_build_test.go:6258]: Note: We should also have a non-integration-cli version of this test.

Opened a ticket for that: https://github.com/moby/moby/issues/49679

File: builder/builder-next/exporter/wrapper.go [hunk 2]
```diff
@@ -82,7 +82,7 @@ func (i *imageExporterInstanceWrapper) Export(ctx context.Context, src *exporter
 	}
 
 	if i.callbacks.Named != nil {
-		for _, name := range strings.Split(out[string(exptypes.OptKeyName)], ",") {
+		for _, name := range strings.Split(out["image.name"], ",") {
```
Comment (jsternberg) [inline builder/builder-next/exporter/wrapper.go:85]: Can you also check that this key exists and is non-empty?

We also recently added a constant to buildkit for this because we noticed this wasn't working properly. The constant was added in https://github.com/moby/buildkit/pull/5862. If it's possible to use that, it would be preferred. Otherwise a note that the exported constant should be used when buildkit is updated.

**Review by jsternberg — CHANGES_REQUESTED** [review]

File: builder/builder-next/exporter/wrapper.go (hunk 2 above)
Comment (vvoland) [reply builder/builder-next/exporter/wrapper.go]: Thanks, done

**Review by jsternberg — APPROVED** [review]

**Review by tonistiigi — APPROVED** [review]

**Review by thaJeztah — APPROVED** [review]
LGTM
