### PR TITLE
Fix multiple `COPY --from` in multistage builds

### LINKED ISSUE #33974: This multistage Dockerfile almost always results in `layer does not exist` error
**Description**

The following Dockerfile almost always results in `layer does not exist` error:

```dockerfile
FROM golang:1.8-alpine AS go-build-base
ENV PATH=/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV GOPATH=/go
RUN apk add --no-cache g++ linux-headers
RUN apk add --no-cache git make

FROM alpine:latest AS runc-git
RUN apk add --no-cache git
RUN git clone https://github.com/opencontainers/runc.git /go/src/github.com/opencontainers/runc
WORKDIR /go/src/github.com/opencontainers/runc
RUN git checkout -q v1.0.0-rc3

FROM go-build-base AS runc
COPY --from=runc-git /go /go
WORKDIR /go/src/github.com/opencontainers/runc
RUN go build -o /usr/bin/runc ./

FROM alpine:latest AS buildkit-git
RUN apk add --no-cache git
RUN git clone https://github.com/moby/buildkit.git /go/src/github.com/moby/buildkit
WORKDIR /go/src/github.com/moby/buildkit
# Jul 5, 2017
RUN git checkout -q 8e2267320e0fb2b6ae3d22b3d999f6377b7b8758

FROM go-build-base AS buildkit-src
COPY --from=buildkit-git /go /go
WORKDIR /go/src/github.com/moby/buildkit

FROM buildkit-src AS buildd-standalone
RUN go build -o /bin/buildd-standalone -tags standalone ./cmd/buildd

FROM buildkit-src AS buildctl
RUN go build -o /bin/buildctl ./cmd/buildctl

FROM alpine:latest
COPY --from=buildctl /bin/buildctl /bin
COPY --from=runc /usr/bin/runc /bin
COPY --from=buildd-standalone /bin/buildd-standalone /bin
RUN ls -l /bin
```

**Steps to reproduce the issue:**
1.  (Optional step for ensuring clean environment)Stop the daemon, do `rm -rf /var/lib/docker`, and start the daemon
2. Do `docker build --no-cache .`

**Describe the results you received:**

```
...
Step 20/31 : FROM go-build-base AS buildkit-src
 ---> f234db884287                                        
Step 21/31 : COPY --from=buildkit-git /go /go  
failed to export image: failed to create image: failed to get layer sha256:102ac1be15dcaef8e5bdade6e75c71b6ec76a67eb9555987aaa5460dd2b7d3b2:
layer does not exist
```

**Describe the results you expected:**

No error

**Additional information you deem important (e.g. issue happens only occasionally):**

- When it fails, it seems always failing at `Step 21/31 : COPY --from=buildkit-git /go /go`
- Happens on both overlay2 and aufs. So should not be related to graph driver.
- `docker build .` sometimes succeeds but never seen successful `docker build --no-cache`.

**Output of `docker version`:**

```
Client:
 Version:      unknown-version
 API version:  1.31
 Go version:   go1.8
 Git commit:   e672589e
 Built:        Thu Jul  6 06:23:30 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-dev
 API version:  1.31 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   9d95740db
 Built:        Thu Jul  6 05:14:08 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 35
Server Version: 17.06.0-dev
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 3addd840653146c90a254301d6c3a663c7fd6429
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-26-generic
Operating System: Ubuntu 17.04
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 29.45GiB
Name: ws01
ID: SN3T:CNK6:JKQD:54CY:XKF2:BRX3:CIRU:DQBT:6DVZ:VWQ2:Q5ET:F23L
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 26
 Goroutines: 43
 System Time: 2017-07-06T06:52:16.093390156Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

cc @tonistiigi

### PR DESCRIPTION
**Pull request by dnephin**
Fixes #33974

I remember thinking it was strange that this pointer was being re-used, but for some reason it seemed to work with the old code. The RootFS was being mutated, so using the cached image reference was causing it to have the wrong DiffIDs.

### CODE REVIEW

File: image/image.go [hunk 1]
```diff
@@ -140,7 +140,10 @@ func NewChildImage(img *Image, child ChildConfig, platform string) *Image {
 	rootFS := img.RootFS
 	if rootFS == nil {
 		rootFS = NewRootFS()
+	} else {
+		rootFS = CloneRootFS(img.RootFS)
```
Comment (tonistiigi) [inline image/image.go]: nit: I think `.Clone()` method is more common in these cases.

**Review by tonistiigi — COMMENTED** [review]
Could we have an intergration test as well with the check for the original regression

**Comment by dnephin** [comment]
We can't write an integration test for every trivial case. I do not think this warrants another slow integration test.

File: image/image.go (hunk 1 above)
Comment (dnephin) [inline image/image.go]: changed to `Clone()`

**Comment by tonistiigi** [comment]
I disagree. Ensuring that we don't reintroduce bugs we have once made is the least we can do. The fact that this was not discovered during a review is a clear sign that our test suite has holes in this specific area. I don't see any technical reason for not adding it as well.

**Comment by dnephin** [comment]
> Ensuring that we don't reintroduce bugs we have once made is the least we can do. The fact that this was not discovered during a review is a clear sign that our test suite has holes in this specific area. 

Exactly. That's why I added a test!  

Integration tests are for testing integration of components. End-to-end tests are for testing features. This regression is neither. I think a unit test is appropriate here.

Adding unnecessarily integration tests slows down the dev/test cycle, which is already way too slow right now.

File: image/image_test.go [hunk 2]
```diff
@@ -51,3 +53,38 @@ func TestMarshalKeyOrder(t *testing.T) {
 		t.Fatal("invalid key order in JSON: ", string(b))
 	}
 }
+
+func TestNewChildImage(t *testing.T) {
```
Comment (thaJeztah) [inline image/image_test.go]: Can you add a description what this test is testing for (describing the bug we're fixing)? Trying to make sure we keep the context, even if the test is refactored in future - we had some of those recently, where the intent of the test was no longer clear, and the test did no longer even test the original reason it was added

File: image/image.go [hunk 3]
```diff
@@ -140,7 +140,10 @@ func NewChildImage(img *Image, child ChildConfig, platform string) *Image {
 	rootFS := img.RootFS
 	if rootFS == nil {
 		rootFS = NewRootFS()
+	} else {
+		rootFS = img.RootFS.Clone()
 	}
+
```
Comment (AkihiroSuda) [inline image/image.go]: The initial vallue of `rootFS` seems unused (`rootfs := img.RootFS`)

Probably the following code would be better
```
var rootFS <type>
if img.RootFS == nil {
  rootFS = NewRootFS()
} else {
  rootFS = img.RootFS.Clone()
}
```

Comment (dnephin) [inline image/image.go]: Thanks! fixed

File: image/image_test.go (hunk 2 above)
Comment (dnephin) [inline image/image_test.go]: Yes, I agree this is very important. I think we've lost track of what most tests are supposed to be testing.

I really prefer when a test describes the functionality and the test case instead of being too specific about a previous bug. Bugs are hard to describe and aren't really meaningful in many context, but features or conditions should retain their meaning.

I'm also a fan of keeping the description in the test name. The format I try to use for test names is:

```
Test<Unit name><Condition>()
```

Where unit name is the function name or struct and function name, and the condition is the branch within the function being tested. I think this format makes it really easy to identify what is being tested.

I've updated the test name to be `TestNewChildImageFromImageWithRootFS` which I think is an accurate description of this test. It's not really a test specific to the bug as it tests more than just a single field, but it does fail without the fix, so still works as a regression test.

Comment (thaJeztah) [inline image/image_test.go]: Thanks!

**Review by AkihiroSuda — APPROVED** [review]
LGTM if green

**Review by yongtang — APPROVED** [review]
LGTM

I also tested the patch locally and it works as expected.

**Comment by thaJeztah** [comment]
This is not an issue in docker 17.06 (https://github.com/moby/moby/issues/33974#issuecomment-313353335), only on master /17.07-dev
