### PR TITLE
docker info: silence unhandleable warnings

### LINKED ISSUE #41790: No kernel memory TCP limit & oom kill disable support
## Fresh Install of Docker 20.10 Rootless shows 2 Warnings in `docker info`

I'm running Ubuntu `20.04.1`

``` BASH
cat /etc/os-release
---
   1   │ NAME="Ubuntu"
   2   │ VERSION="20.04.1 LTS (Focal Fossa)"
   3   │ ID=ubuntu
   4   │ ID_LIKE=debian
   5   │ PRETTY_NAME="Ubuntu 20.04.1 LTS"
   6   │ VERSION_ID="20.04"
   7   │ HOME_URL="https://www.ubuntu.com/"
   8   │ SUPPORT_URL="https://help.ubuntu.com/"
   9   │ BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
  10   │ PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
  11   │ VERSION_CODENAME=focal
  12   │ UBUNTU_CODENAME=focal
```

with a fresh install of Docker release `20.10`. When looking at `docker info`

``` BASH
Client:
 Context:    rootless
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: 455pa82xhsbncapz4xrsvxbix
  Is Manager: true
  ClusterID: jnwlvtrtip63brg2pytlejggu
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.65.3
  Manager Addresses:
   192.168.65.3:2377
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  rootless
  cgroupns
 Kernel Version: 5.4.0-58-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.775GiB
 Name: itbsd
 ID: WCKE:YRNK:PITP:G345:T3KJ:IMZH:2N7L:Y5YP:FFLO:MLZW:CFD7:ZMGU
 Docker Root Dir: /home/notroot/.local/share/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: No kernel memory TCP limit support
WARNING: No oom kill disable support
WARNING: Support for cgroup v2 is experimental
``` 

**Steps to reproduce the issue:**
1. Use Ubuntu 20.04 and cGroups v2
2. Install rootless Docker with the install script

**Describe the results you received:**

2 Warnings that should not be there(?)

**Describe the results you expected:**

No warnings

**Additional information you deem important (e.g. issue happens only occasionally):**

I've looked through Google and the issue tracker and cannot find a solution. I refuse to believe the `5.4.0-58-generic` kernel is not capable of what the warning say. What did I miss?

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        7287ab3
 Built:             Tue Dec  8 18:54:00 2020
 OS/Arch:           linux/amd64
 Context:           rootless
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       eeddea2
  Built:            Tue Dec  8 18:58:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on a virtual private server (8GB RAM, 4vCores)

Thanks in advance!:)

### PR DESCRIPTION
**Pull request by AkihiroSuda**
fixes https://github.com/moby/moby/issues/41790

**- What I did**

The following warnings in `docker info` are now discarded, because there is no action user can actually take.

On cgroup v1:
- "WARNING: No blkio weight support"
- "WARNING: No blkio weight_device support"

On cgroup v2:
- "WARNING: No kernel memory TCP limit support"
- "WARNING: No oom kill disable support"

`docker run` still prints warnings when the missing feature is being attempted to use.

**- How I did it**

See the code

**- How to verify it**
Run `docker info`

**- Description for the changelog**

docker info: silence unhandleable warnings

**- A picture of a cute animal (not mandatory but encouraged)**

:penguin:

### CODE REVIEW

File: daemon/info_unix.go [hunk 1]
```diff
@@ -122,10 +126,13 @@ func (daemon *Daemon) fillPlatformInfo(v *types.Info, sysInfo *sysinfo.SysInfo)
 			v.Warnings = append(v.Warnings, "WARNING: Support for cgroup v2 is experimental")
 		}
 		// TODO add fields for these options in types.Info
-		if !sysInfo.BlkioWeight {
+		if !sysInfo.BlkioWeight && v.CgroupVersion == "2" {
+			// blkio weight is not available on cgroup v1 since kernel 5.0.
+			// Warning is not printed on cgroup v1, because there is no action user can take.
+			// On cgroup v2, blkio weight is implemented using io.weight
 			v.Warnings = append(v.Warnings, "WARNING: No blkio weight support")
```
Comment (thaJeztah) [inline daemon/info_unix.go:133]: Do we need to update the warnings to match the new cgroup? (ok for a follow-up)

**Review by thaJeztah — APPROVED** [review]
LGTM

File: daemon/info_unix.go (hunk 1 above)
Comment (AkihiroSuda) [reply daemon/info_unix.go:133]: updated

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Review by cpuguy83 — APPROVED** [review]
LGTM
