### PR TITLE
Registry host configuration cleanup

### LINKED ISSUE #47240: Docker 25 cannot use unsecured private s3 registry
### Description

Docker v25 is confused when pulling images through unsecured registry and all pulls end in failure.

My unsecured registry on loopback (127.0.01) is using S3 in secured mode (`secure: true`) so that while loopback traffic is unencrypted, the registry "talks" to S3 over https.

In logs, the registry urls all indicate `url=https:/127.0.0.1:5000/...` even though the loopback registry does not serve over TLS. 
The pull ends in failure with `failed to copy: httpReadSeeker: failed to open: failed to do request: Get "https://[url to a blob]": dial tcp 52.217.75.76:80 i/o timeout`.
Note that it is trying to connect to port 80 when it should use 443.

(`52.217.75.76` is the IP of `s3-1-w.amazonaws.com`).

When setting up a dummy self-signed certificate and making the loopback registry use TLS instead, then everything starts working as expected.

This seems related, or at least similar, to #36263 .
This too seems similar. https://github.com/docker/buildx/issues/2030

### Reproduce

1. Use docker-distribute to setup a S3 backed registry listening on loopback 127.0.0.1:5000. Be sure to enable `secure: true` in the storage.s3 section
2. Try to pull an image with docker v25 through the local registry, `docker pull 127.0.0.1:5000/some_image`.

Switch to secured registry to make it work
1. Update the `http.addr` for the registry to "localhost:5000"
1. Generate a self signed certificate for "localhost" and update the docker-distribute config to have a TLS section (see https://github.com/wking/docker-distribution/blob/master/docs/configuration.md for more info)
 	``` yaml
        http:
            addr: localhost:5000
            tls:
                certificate: /path/to/x509/locahost.crt
                key: /path/to/x509/locahost.key
        ```
3. Pull the same image `docker pull localhost:5000/some_image` and it now works

### Expected behavior

docker pull should function with unsecured private registries just as well as with secured registries.

### docker version

```bash
Client:
 Version:           20.10.24+dfsg1
 API version:       1.41
 Go version:        go1.19.8
 Git commit:        297e128
 Built:             Thu May 18 08:38:34 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          v25.0.0
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.21.6
  Git commit:       311b9ff0aa93aa55880e1e5f8871c4fb69583426
  Built:            Fri Jan 26 20:46:21 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20~ds1
  GitCommit:        1.6.20~ds1-1+b1
 runc:
  Version:          1.1.5+ds1
  GitCommit:        1.1.5+ds1-1+b1
 docker-init:
  Version:          0.19.0
  GitCommit:
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: v25.0.0
 Storage Driver: overlayfs
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1.6.20~ds1-1+b1
 runc version: 1.1.5+ds1-1+b1
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-15-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 7.753GiB
 Name: bookworm
 ID: e432cf75-f542-4c5c-99a2-7c5fc146ce5c
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by dmcgowan**
First commit copies the resolver code from buildkit with fix for insecure registries and could be backported.
Second commit cleans up the resolve logic using containerd's host config.

### CODE REVIEW

**Comment by thaJeztah** [comment]
Couple of failures that look related. Could be that the test was written for a specific error output though (these are the integration-cli tests, which use a fixed, old version of the CLI), or perhaps we're missing some conversion for errors returned :thinking:

```
=== Failed
=== FAIL: amd64.integration-cli TestDockerRegistryAuthHtpasswdSuite/TestBuildFromAuthenticatedRegistry (0.34s)
    docker_cli_build_test.go:4988: assertion failed: 
        Command:  /usr/local/cli-integration/docker push 127.0.0.1:5000/baseimage
        ExitCode: 1
        Error:    exit status 1
        Stdout:   The push refers to repository [127.0.0.1:5000/baseimage]
        76df9210b28c: Waiting
        
        Stderr:   unexpected status from HEAD request to http://127.0.0.1:5000/v2/baseimage/blobs/sha256:76df9210b28cbd4bc127844914d0a23937ed213048dc6289b2a2d4f7d675c75e: 401 Unauthorized
        
        
        Failures:
        ExitCode was 1 expected 0
        Expected no error
    check_test.go:532: [da6a45cfad359] daemon is not started
    --- FAIL: TestDockerRegistryAuthHtpasswdSuite/TestBuildFromAuthenticatedRegistry (0.34s)

=== FAIL: amd64.integration-cli TestDockerRegistryAuthHtpasswdSuite/TestBuildWithExternalAuth (0.31s)
    docker_cli_build_test.go:5024: assertion failed: 
        Command:  /usr/local/cli-integration/docker --config /tmp/integration-cli-1513645647 push 127.0.0.1:5000/dockercli/busybox:authtest
        ExitCode: 1
        Error:    exit status 1
        Stdout:   The push refers to repository [127.0.0.1:5000/dockercli/busybox]
        76df9210b28c: Waiting
        
        Stderr:   unexpected status from HEAD request to http://127.0.0.1:5000/v2/dockercli/busybox/blobs/sha256:76df9210b28cbd4bc127844914d0a23937ed213048dc6289b2a2d4f7d675c75e: 401 Unauthorized
        
        
        Failures:
        ExitCode was 1 expected 0
        Expected no error
    check_test.go:532: [d254f721c0d6c] daemon is not started
    --- FAIL: TestDockerRegistryAuthHtpasswdSuite/TestBuildWithExternalAuth (0.31s)

=== FAIL: amd64.integration-cli TestDockerRegistryAuthHtpasswdSuite/TestLogoutWithExternalAuth (0.87s)
    docker_cli_logout_test.go:53: assertion failed: error is not nil: exit status 1
    --- FAIL: TestDockerRegistryAuthHtpasswdSuite/TestLogoutWithExternalAuth (0.87s)

=== FAIL: amd64.integration-cli TestDockerRegistryAuthHtpasswdSuite/TestPullWithExternalAuth (0.29s)
    docker_cli_pull_local_test.go:439: assertion failed: 
        Command:  /usr/local/cli-integration/docker --config /tmp/integration-cli-2597430029 push 127.0.0.1:5000/dockercli/busybox:authtest
        ExitCode: 1
        Error:    exit status 1
        Stdout:   The push refers to repository [127.0.0.1:5000/dockercli/busybox]
        76df9210b28c: Waiting
        
        Stderr:   unexpected status from HEAD request to http://127.0.0.1:5000/v2/dockercli/busybox/blobs/sha256:1c35c441208254cb7c3844ba95a96485388cef9ccc0646d562c7fc026e04c807: 401 Unauthorized
        
        
        Failures:
        ExitCode was 1 expected 0
        Expected no error
    check_test.go:532: [d37782d3d4dbc] daemon is not started
    --- FAIL: TestDockerRegistryAuthHtpasswdSuite/TestPullWithExternalAuth (0.29s)

=== FAIL: amd64.integration-cli TestDockerRegistryAuthHtpasswdSuite/TestPullWithExternalAuthLoginWithScheme (0.29s)
    docker_cli_pull_local_test.go:397: assertion failed: 
        Command:  /usr/local/cli-integration/docker --config /tmp/integration-cli-846080656 push 127.0.0.1:5000/dockercli/busybox:authtest
        ExitCode: 1
        Error:    exit status 1
        Stdout:   The push refers to repository [127.0.0.1:5000/dockercli/busybox]
        76df9210b28c: Waiting
        
        Stderr:   unexpected status from HEAD request to http://127.0.0.1:5000/v2/dockercli/busybox/blobs/sha256:1c35c441208254cb7c3844ba95a96485388cef9ccc0646d562c7fc026e04c807: 401 Unauthorized
        
        
        Failures:
        ExitCode was 1 expected 0
        Expected no error
    check_test.go:532: [df1a930ceacf0] daemon is not started
    --- FAIL: TestDockerRegistryAuthHtpasswdSuite/TestPullWithExternalAuthLoginWithScheme (0.29s)

=== FAIL: amd64.integration-cli TestDockerRegistryAuthHtpasswdSuite/TestPushNoCredentialsNoRetry (0.17s)
    docker_cli_push_test.go:225: assertion failed: expression is false: strings.Contains(out, "no basic auth credentials")
    check_test.go:532: [da543621fde40] daemon is not started
    --- FAIL: TestDockerRegistryAuthHtpasswdSuite/TestPushNoCredentialsNoRetry (0.17s)

=== FAIL: amd64.integration-cli TestDockerRegistryAuthHtpasswdSuite (2.88s)
```

File: daemon/hosts.go [hunk 1]
```diff
@@ -0,0 +1,296 @@
...
+	fallback bool
+}
+
+func (f *httpFallback) RoundTrip(r *http.Request) (*http.Response, error) {
+	if !f.fallback {
+		resp, err := f.super.RoundTrip(r)
+		var tlsErr tls.RecordHeaderError
+		if errors.As(err, &tlsErr) && string(tlsErr.RecordHeader[:]) == "HTTP/" {
+			// Server gave HTTP response to HTTPS client
+			f.fallback = true
```
Comment (vvoland) [inline daemon/hosts.go]: I think we also need https://github.com/moby/buildkit/pull/4613 here?

**Comment by dmcgowan** [comment]
Marked this as ready to go. I fixed the authorizer with the containerd image service resolver. The other failures now don't seem related, look like flakes.

File: daemon/hosts.go [hunk 2]
```diff
@@ -0,0 +1,171 @@
...
+				t.TLSClientConfig = c
+			}
+		}
+		if daemon.registryService.IsInsecureRegistry(hosts[i].Host) {
+			if t.TLSClientConfig != nil {
+				isLocalhost, err := docker.MatchLocalhost(hosts[i].Host)
+				if err != nil {
+					continue
+				}
+				if isLocalhost {
```
Comment (vvoland) [inline daemon/hosts.go:103]: Won't this make only the localhost insecure registries use the http fallback?
Also, shouldn't localhost registries should always use the http fallback by default, even if they're not explicitly an insecure registry?

Comment (thaJeztah) [reply daemon/hosts.go:103]: Didn't look at this PR in-depth, but I think we have some code somewhere that automatically adds localhost (more factually; the loopback range) as insecure), so it's possible that it's already automatically configured as insecure before we hit this code (????);

```
Insecure Registries:
  127.0.0.0/8
```

(Now wondering if that should also include the IPv6 loopback address `::1` , but I guess that's a separate topic).

Comment (thaJeztah) [reply daemon/hosts.go:103]: @dmcgowan could you have a look?

Comment (dmcgowan) [reply daemon/hosts.go:103]: > Won't this make only the localhost insecure registries use the http fallback?

It was intentional here to only use this for localhost since stepping down from insecure TLS to HTTP on localhost does not have the same implications as non-localhost. Although to keep the functionality the same in regards to the existing ambiguity over the meaning of "insecure" this could be applied to all hosts. In that case an empty TLS config would need to be generated if not set still to match existing logic I think.

I need to find a better approach for skipping over the legacy config, currently it checks for a nil configuration but I don't believe that is ever nil. Ideally the new (and less ambiguous) configuration files can be used without hitting the legacy merge logic when no legacy configuration is provided.

> Also, shouldn't localhost registries should always use the http fallback by default, even if they're not explicitly an insecure registry?

I think that is up to the default configuration, as @thaJeztah mentioned, localhost is added by default. (see https://github.com/moby/moby/blob/master/registry/config.go#L187).

> Now wondering if that should also include the IPv6 loopback address ::1 , but I guess that's a separate topic

Probably wouldn't hurt to add as a default, we should just make sure the behavior is the same with the new configuration and deprecate the old one.

**Comment by dmcgowan** [comment]
There is a pending fix for the http handler on the containerd side that we can wait for in 1.7 before updating this one.

Also on another look I'm not sure checking for the service config being nil as the switch to merge in the legacy config is sufficient, especially if the legacy config is allowing for a more loose handling of "insecure" for non-localhost registries.

**Comment by dmcgowan** [comment]
Pushed an update the fixes I mentioned.

As for the containerd fix, we need to handle TLS handshake timeouts (see https://github.com/containerd/containerd/issues/10014). Although the current version we have also has this issue, so it might not be a blocker for taking this change in. There will be a followup regardless.

File: daemon/hosts.go [hunk 3]
```diff
@@ -0,0 +1,166 @@
...
+	sc := daemon.registryService.ServiceConfig()
+	if host == "docker.io" && len(sc.Mirrors) > 0 {
+		var mirrorHosts []docker.RegistryHost
+		for _, mirror := range sc.Mirrors {
+			h := hosts[0]
+			h.Capabilities = docker.HostCapabilityPull | docker.HostCapabilityResolve
+
+			u, err := url.Parse(mirror)
+			if err != nil || u.Host == "" {
+				u, err = url.Parse(fmt.Sprintf("//%s", mirror))
```
Comment (thaJeztah) [inline daemon/hosts.go:60]: should this one use `//:` (with a colon)? if the intent is to make sure if has a scheme.

Also for this, we may as well skip the Sprintf, and just concat the strings

File: daemon/hosts.go [hunk 4]
```diff
@@ -0,0 +1,166 @@
...
+			}
+			if err == nil && u.Host != "" {
+				h.Host = u.Host
+				h.Path = strings.TrimRight(u.Path, "/")
```
Comment (thaJeztah) [inline daemon/hosts.go:64]: Would `u.Path` ever have multiple trailing slashes (after parsing?) if not, and it will always be one, then perhaps this should be TrimSuffix https://pkg.go.dev/strings#TrimSuffix

File: daemon/hosts.go [hunk 5]
```diff
@@ -0,0 +1,166 @@
...
+				if !strings.HasSuffix(h.Path, defaultPath) {
```
Comment (thaJeztah) [inline daemon/hosts.go:65]: This part is confusing (but maybe I need to dig in more to grasp); we check if the path _ends_ with default path, and if not we _prepend_ the default path. Maybe it could use a short comment

File: daemon/hosts.go [hunk 6]
```diff
@@ -0,0 +1,166 @@
...
+				return nil, errors.Wrapf(err, "unable to get system cert pool")
+			}
+		}
+		tc.RootCAs = systemPool
+	}
+
+	for _, p := range rootCAs {
+		dt, err := os.ReadFile(p)
+		if err != nil {
+			return nil, errors.Wrapf(err, "failed to read %s", p)
```
Comment (thaJeztah) [inline daemon/hosts.go:153]: It's quite likely that `os.Readfile` already returns a `os.PathError`, which includes the path of the file as part of it, so we may not need to add the path again when wrapping; see https://pkg.go.dev/os#ReadFile

File: daemon/hosts.go [hunk 7]
```diff
@@ -0,0 +1,166 @@
...
+		Certificate string
+		Key         string
+	}
+	var (
+		rootCAs  []string
+		keyPairs []keyPair
+	)
+	for _, f := range fs {
+		if strings.HasSuffix(f.Name(), ".crt") {
+			rootCAs = append(rootCAs, filepath.Join(d, f.Name()))
```
Comment (thaJeztah) [inline daemon/hosts.go:125]: I think we're missing a `continue` here, otherwise we fall through to evaluate the next `if` below.

But perhaps worth considering using a switch and `filepath.Ext` https://pkg.go.dev/path/filepath#Ext to get the file extension once.

File: daemon/hosts.go (hunk 3 above)
Comment (dmcgowan) [reply daemon/hosts.go:60]: This is what buildkit was doing but I agree it is not the approach done elsewhere. In containerd normally we parse as `dummy://%s` to extract a host and path.

The original code is https://github.com/moby/buildkit/blob/master/util/resolver/utils.go but it could use more unit testing.

Comment (thaJeztah) [reply daemon/hosts.go:60]: oh! wrote the colon in the wrong place 🙈

Hmm, actually maybe it was correct; scheme-less URL may not need the colon?

Comment (dmcgowan) [reply daemon/hosts.go]: The original logic was throwing away the scheme however that does not match how the mirror string was originally be used. Updated to parse with "dummy" scheme and override the scheme when provided. As it is now it will always use https even when explicitly setting the scheme. Also added a unit tests for this section so we can just add test cases to ensure it behaves as expected.

File: daemon/hosts.go (hunk 5 above)
Comment (dmcgowan) [reply daemon/hosts.go]: Updated this logic to _mostly_ match the original mirror logic. Seems the original mirror logic didn't check the suffix just unconditionally added "/v2". Updated to add at the end.

There have been different ideas around what the provided endpoint path should mean, some want it as a repository subpath and others as a root prefix. Here just going to add at the end now and mentioned in a comment since this is just for compatibility with the existing mirror strings. Using the new host configuration from containerd allows much flexibility for users to specify whatever they want without us trying to override what they set.

File: daemon/hosts.go (hunk 4 above)
Comment (dmcgowan) [reply daemon/hosts.go]: It is needed to trim but updated to TrimSuffix

**Review by vvoland — APPROVED** [review]
LGTM; left one small nit in test

**Review by vvoland — APPROVED** [review]
LGTM
@thaJeztah PTAL

**Comment by vvoland** [comment]
Rerunning CI

**Comment by vvoland** [comment]
Ah, looks like there's a linter error:
```
 daemon/hosts.go:16: File is not `goimports`-ed (goimports)
	cerrdefs "github.com/containerd/errdefs"
```
