### PR TITLE
Wait for discovery on container start error

### LINKED ISSUE #22486: race conditions with restart policies and overlay networks in docker 1.11.0-1.11.1
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 102
 Running: 4
 Paused: 0
 Stopped: 98
Images: 2
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 209
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host overlay bridge null
Kernel Version: 3.13.0-74-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.676 GiB
Name: ip-172-31-33-160
ID: TZXF:QIZJ:QFMJ:VAJ2:C6VT:DOHB:H5JA:CKLG:37RZ:4XTR:FSA2:4UY7
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 33
 Goroutines: 83
 System Time: 2016-05-03T21:06:23.420006922Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Cluster store: etcd://172.17.0.1:2050
Cluster advertise: 172.17.0.1:12376
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS Ubuntu 14.04 with `curl https://get.docker.com/ | sudo sh`

**Steps to reproduce the issue:**
1. Create ubuntu 14.04 vm on AWS
2. This is my cleaned up bash history:
```
curl https://get.docker.com | sudo sh
sudo docker run -d --name etcd -p 2050:2050 --restart always quay.io/coreos/etcd:v2.2.4 --advertise-client-urls http://172.17.0.1:2050 --listen-client-urls http://0.0.0.0:2050 --debug
sudo cat <<EOF | sudo tee /etc/docker/daemon.json
{       
        "debug": true,
        "cluster-advertise": "172.17.0.1:12376",
        "cluster-store": "etcd://172.17.0.1:2050"
}
EOF
sudo kill -HUP $(cat /run/docker.pid)
sudo docker network create -d overlay ol
for i in $(seq 0 10); do sudo docker run -d -t --net ol --restart always --name test$i alpine sh; done
sudo docker ps
sudo service docker restart
sudo docker ps
```
I ran it with 100 containers last time, but it should work with 10. If it doesn't, run more containers.

**Describe the results you received:**
Some of the containers failed to start with the following error:
```
$ docker inspect test18 | grep Error
            "Error": "network ol not found",
```
They were in a "stopped" state instead of a "restarting" state.

**Describe the results you expected:**
I expected the containers to start successfully

**Additional information you deem important (e.g. issue happens only occasionally):**
This seems to be a race condition during start up that happens only when using an etcd in a docker container on the same machine with overlay networking.

### PR DESCRIPTION
**Pull request by cpuguy83**
**\- What I did**
Allow the `cluster-store` to run in a container and start reliably on daemon restart.

**\- How I did it**
On the first container start, if an error is encountered wait for discovery to finish initialization.
This allows a containerized K/V store to come up while the failed container waits for the discovery service to reach the K/V store and be ready, then attempting to start again.

**\- How to verify it**
1. Start a fresh daemon.
2. `docker run -d --name etcd --net=host --restart=always quay.io/coreos/etcd`
3. Restart the daemon with cluster opts, set the k/v store to `etcd://127.0.0.1`
4. `docker network create -d overlay test`
5. `docker run -d --name test --restart=always --net=test busybox top`
6. restart the daemon

**Note**: There seems to be an issue in docker-in-docker where a net namespace is leaked causing a `file exists` error when it tries to start the `test` container after daemon restart, but that is orthogonal to this PR.

**\- Description for the changelog**

Fixes issues with restarting containers after a daemon restart for containers using networks which require the cluster store when the cluster store is containerized

Fixes #22486

### CODE REVIEW

File: daemon/daemon.go [hunk 1]
```diff
@@ -380,8 +380,22 @@ func (daemon *Daemon) restore() error {
 					}
 				}
 			}
+
 			if err := daemon.containerStart(c); err != nil {
```
Comment (cpuguy83) [inline daemon/daemon.go]: Right now libnetwork only returns a `fmt.Errorf` error, it would be nice to have a typed error that we could check instead of assuming a discovery issue

Comment (mavenugo) [inline daemon/daemon.go]: I think instead of even trying to start a container and fail, we should check for `NetworkByName` for all the networks that the container is configured with. If the call returns `ErrNoSuchNetwork`, then we can wait for discovery event.

This will make the check more explicit and also not even try to start the container until the store is up for name lookup.

**Comment by vikstrous** [comment]
This seems to work for me. It really speeds up start up times.

**Comment by cpuguy83** [comment]
Updated with @mavenugo's suggestion.

File: daemon/daemon.go [hunk 2]
```diff
@@ -380,8 +380,13 @@ func (daemon *Daemon) restore() error {
 					}
 				}
 			}
+
+			// Make sure networks are available before starting
+			daemon.waitForNetworks(c)
 			if err := daemon.containerStart(c); err != nil {
-				logrus.Errorf("Failed to start container %s: %s", c.ID, err)
+				if err != nil {
```
Comment (LK4D4) [inline daemon/daemon.go]: I don't understand this trick

Comment (cpuguy83) [inline daemon/daemon.go]: Remnant of a previous iteration.
Will remove.

Comment (cpuguy83) [inline daemon/daemon.go]: fixed

File: daemon/discovery.go [hunk 3]
```diff
@@ -87,32 +93,35 @@ func initDiscovery(backendAddress, advertiseAddress string, clusterOpts map[stri
...
-			d.registerAddr(address)
+		case <-t.C:
+			if err := d.backend.Register(address); err != nil {
+				log.Warnf("Registering as %q in discovery failed: %v", address, err)
+			} else {
+				if !readyChanClosed {
+					close(d.readyCh)
+					readyChanClosed = true
+					t.Stop()
+					t = d.ticker
```
Comment (mavenugo) [inline daemon/discovery.go]: If the store is unreachable during the daemon restart (for any reason), will the ticker will be aggressively set for 500 msec for ever ? I think we should a timeout after which, it should go to normal default/user-configured heartbeat timer.

Comment (cpuguy83) [inline daemon/discovery.go]: Updated

**Comment by mavenugo** [comment]
Thanks @cpuguy83. LGTM.

@vikstrous can you please try this patch and confirm if it handles your scenario ?

**Comment by vikstrous** [comment]
I tried to apply this patch on docker 1.11 and after doing a restart some of my containers failed to start with `"Error": "network dtr-ol not found"`

**Comment by vikstrous** [comment]
My testing was wrong. It works as expected now.

**Comment by mavenugo** [comment]
@cpuguy83 I tried the patch multiple times and it works as advertised. I also think the 60 seconds timeout for the restart-policy is reasonable in order for the KV container to come up.

LGTM

**Comment by tiborvass** [comment]
I'm not fond of the long timeout, but I understand we need a fix.
LGTM
