### PR TITLE
idtools don't chown if not needed

### LINKED ISSUE #35002: Bind mount nfs file share into user container fails
We have an nfs share with permissions set for a certain user. The host's root user is not supposed to and currently does not have access to the share. 

The command 
````
docker run --rm -it -v /mnt/nfsshare/dir:/home/myuser/dir -u $UID:$GID myimg /bin/bash
````
fails with 
````
docker: Error response from daemon: error while creating mount source path '/mnt/nfsshare/dir': mkdir /mnt/nfsshare/dir: permission denied.
````
This error disappears when we temporarily enable our root user to have access to the nfs share. It seems to me that we should not need to have root access to the share in order to spin up the container. Are we missing something? 

**Output of `docker version`:**

```
[SWISS+jonb4@EADL0114 fineng]$ docker version
Client:
 Version:      17.07.0-ce-rc2
 API version:  1.31
 Go version:   go1.8.3
 Git commit:   36ce605
 Built:        Mon Aug  7 23:43:46 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.07.0-ce-rc2
 API version:  1.31 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   36ce605
 Built:        Mon Aug  7 23:45:07 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 14
 Running: 14
 Paused: 0
 Stopped: 0
Images: 213
Server Version: 17.07.0-ce-rc2
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3kB
 Base Device Size: 107.4GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 199.8GB
 Data Space Total: 522.3GB
 Data Space Available: 322.5GB
 Metadata Space Used: 24.2MB
 Metadata Space Total: 5.495GB
 Metadata Space Available: 5.47GB
 Thin Pool Minimum Free Space: 52.23GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 3addd840653146c90a254301d6c3a663c7fd6429
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.21.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 125.7GiB
Name: EADL0114
ID: HVP3:FUFH:XYJF:TBTJ:BNFC:HHTV:FOVO:2P5V:ZPWB:XHQU:XGIC:7JTH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://techproxy-cez-q.slcloud.ch:8080
Https Proxy: https://techproxy-cez-q.slcloud.ch:8080
No Proxy: localhost,127.0.0.0/8,eadl0114.slcloud.ch
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### PR DESCRIPTION
**Pull request by cpuguy83**
In some cases (e.g. NFS), a chown may technically be a no-op but still
return `EPERM`, so only call `chown` when necessary.

This is particularly problematic for docker users bind-mounting an NFS
share into a container.

This is an attempt to fix #35002

### CODE REVIEW

File: pkg/idtools/idtools_unix.go [hunk 1]
```diff
@@ -60,9 +71,17 @@ func mkdirAs(path string, mode os.FileMode, ownerUID, ownerGID int, mkAll, chown
...
 	// didn't exist when we called MkdirAll
 	for _, pathComponent := range paths {
-		if err := os.Chown(pathComponent, ownerUID, ownerGID); err != nil {
+		// Normally a Chown is a no-op if uid/gid match, but in some cases this can still cause an error, e.g. if the
+		// dir is on an NFS share, so don't call chown unless we absolutely must.
+		stat, err := system.Stat(pathComponent)
+		if err != nil {
 			return err
 		}
+		if stat.UID() != uint32(ownerUID) || stat.GID() != uint32(ownerGID) {
```
Comment (fntlnz) [inline pkg/idtools/idtools_unix.go]: Another option could be to implement a own `Chown` (or with a similar name) under `system` so that other places could benefit using a more "safe" version of chown.
Also there are cases where the chown is even repeated (for other uid, gid), like

https://github.com/cpuguy83/docker/blob/32a6db4c971910aefca04b1c9609a19549ca0342/daemon/container_operations_unix.go#L307

You might say, that kind of files is not usually on something like nfs so no problem there but to get a more consistent behavior in my opinion a better solution is to have the check at `chown` level directly

Comment (cpuguy83) [reply pkg/idtools/idtools_unix.go]: I was a little averse to implementing our own chown, but since we're already importing system here and also have this pattern elsewhere, it's likely an good thing to do.

File: pkg/idtools/idtools_unix.go [hunk 2]
```diff
@@ -26,14 +26,25 @@ func mkdirAs(path string, mode os.FileMode, ownerUID, ownerGID int, mkAll, chown
 	// so that we can chown all of them properly at the end.  If chownExisting is false, we won't
 	// chown the full directory path if it exists
 	var paths []string
```
Comment (dnephin) [inline pkg/idtools/idtools_unix.go]: `paths` isn't used until line 47 below, so this should be moved to immediately before it's used.

File: pkg/idtools/idtools_unix.go (hunk 1 above)
Comment (dnephin) [reply pkg/idtools/idtools_unix.go]: Even a `lazyChown()` that isn't exported could be used here and above instead of checking uid/gid twice. It would also remove the duplicate comment.

**Comment by cpuguy83** [comment]
Updated

**Review by dnephin — APPROVED** [review]
LGTM

**Review by yongtang — APPROVED** [review]
LGTM
