### PR TITLE
Fix for Daemon crashing when wildcards are used for COPY/ADD

### LINKED ISSUE #12267: COPY *.somefile.conf makes dockerd *crash* during docker build
A simple Dockerfile:

```COPY *.somefile.conf somefile.conf```

makes my dockerd (1.5.0 , boot2docker) crash consistently

### PR DESCRIPTION
**Pull request by duglin**
in the filename and the command itself

Closes #12267

Signed-off-by: Doug Davis dug@us.ibm.com

### CODE REVIEW

**Comment by cpuguy83** [comment]
This seems like it fixes a very strange use case... why would someone use an actual `*` in the name of a file?

**Comment by LK4D4** [comment]
Lol, I hate recursive functions.

**Comment by duglin** [comment]
@cpuguy83 to make life interesting? :-)

File: integration-cli/docker_cli_build_test.go [hunk 1]
```diff
@@ -1246,6 +1246,33 @@ func TestBuildCopyWildcardNoFind(t *testing.T) {
...
+func TestBuildCopyWildcardInName(t *testing.T) {
+	name := "testcopywildcardinname"
+	defer deleteImages(name)
+	ctx, err := fakeContext(`FROM busybox
+	COPY *.txt /tmp/
+	RUN [ "$(cat /tmp/\*.txt)" = 'hi there' ]
+	`, map[string]string{"*.txt": "hi there"})
+
+	if err != nil {
+		// Normally we would do t.Fatal(err) here but given that
```
Comment (crosbymichael) [inline integration-cli/docker_cli_build_test.go]: I'm not sure this is the best way.  This is such a weird usecase and it would seem that this test would pass if there was a regression.  Could we check the type of error returned for known filesystems that don't support `*`

Comment (duglin) [inline integration-cli/docker_cli_build_test.go]: @crosbymichael this "if" is just checking the setup of the fake context, not actually running the build.
If this step fails then a TON of other tests will fail because there's something seriously wrong with our test environment that we can't even create a dir/tree/files.

If you want what I could do is split this - build the context first and the use context.Add() to add this one special file and then we know that if _that_ fails it must be due to _just_ the * in the name. 

Thoughts?

File: integration-cli/docker_cli_build_test.go [hunk 2]
```diff
@@ -1202,6 +1202,31 @@ func (s *DockerSuite) TestBuildCopyWildcardNoFind(c *check.C) {
...
+	`, map[string]string{"*.txt": "hi there"})
+
+	if err != nil {
+		// Normally we would do c.Fatal(err) here but given that
+		// the odds of this failing are so rare, it must be because
+		// the OS we're running the client on doesn't support * in
+		// filenames (like windows).  So, instead of failing the test
+		// just let it pass. Then we don't need to explicitly
+		// say which OSs this works on or not.
+		return
```
Comment (jfrazelle) [inline integration-cli/docker_cli_build_test.go]: can we do a log tho just in case sorry

Comment (duglin) [inline integration-cli/docker_cli_build_test.go]: do we have logs in the tests?  I can do a fmt.Print if you want and if windows folks are ok with the clutter in their test output.  Just let me know.

Comment (duglin) [inline integration-cli/docker_cli_build_test.go]: ping @jfrazelle

**Comment by icecrime** [comment]
LGTM, but needs rebase!

**Comment by duglin** [comment]
rebased

**Comment by jfrazelle** [comment]
LGTM
