### PR TITLE
make node ps default to self in swarm node

### LINKED ISSUE #25175: docker node ps should default to self
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.3
 Git commit:   8a8a63a-unsupported
 Built:        Thu Jul 28 15:23:27 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.3
 Git commit:   8a8a63a-unsupported
 Built:        Thu Jul 28 15:23:27 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: active
 NodeID: a7i6cb03rgaz37pqvo2gl4dix
 Is Manager: true
 ClusterID: 96vqx7jf90bmgy6w94e9dfwk6
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot interval: 10000
  Heartbeat tick: 1
  Election tick: 3
 Dispatcher:
  Heartbeat period: 5 seconds
 CA configuration:
  Expiry duration: 3 months
 Node Address: 172.17.0.4
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Debian GNU/Linux 8 (jessie) (containerized)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: 116dcd914b19
ID: 62MN:QJ4K:JXSX:BHHJ:4S3J:MZWB:S66X:KWTQ:SCLL:LEBA:SVNZ:L6GJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 28
 Goroutines: 109
 System Time: 2016-07-28T15:48:00.487328339Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. `docker swarm init`
2. `docker node ps`

**Describe the results you received:**

```
$ docker node ps
"docker node ps" requires exactly 1 argument(s).
See 'docker node ps --help'.

Usage:  docker node ps [OPTIONS] self|NODE

List tasks running on a node
```

**Describe the results you expected:**

```
$ docker node ps self
ID  NAME  IMAGE  NODE  DESIRED STATE  CURRENT STATE  ERROR
```

I find myself every time forgetting you need `self` because that's not how `docker ps` works and 99% of the time I want self so at least to me it seems to indicate self should be default. Anyone else feel the same?

### PR DESCRIPTION
**Pull request by allencloud**
**\- What I did**
1. change function name: `newPSCommand` into `newPsCommand`, `runPS` into `runPs` to keep consistency
2. make command `docker node ps` default to list tasks on itself. fix #25175
3. modify some related docs.

**\- How I did it**

**\- How to verify it**

**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**

Signed-off-by: allencloud allen.sun@daocloud.io

### CODE REVIEW

**Comment by vieux** [comment]
I like this change, /cc @aluzzardi @stevvooe

**Comment by stevvooe** [comment]
Let's just be clear here: this will only _ever_ work on manager nodes. I want to avoid the confusion that may come with running this command on a worker node and not getting output.

This also reinforces the unfortunate illusion that the docker client _always_ runs from a node. Without arguments, connecting over HTTP, this will display the processes for the node to which the HTTP connection is made. In general, this is slightly confusing but I am not sure if we can get away from that.

**Comment by allencloud** [comment]
@stevvooe @vieux 
Thanks for your feedback.
First, I think no matter `docker node ps` or `docker node ps self`, users can always misuse this command on a work node. So, I think we should add some instruction about manager in the command description.

Second, I agree that self argument is really confusing if a user uses HTTP.

**Comment by allencloud** [comment]
Any update? @vieux @stevvooe @aluzzardi 
Currently I do not think `SELF` is a good choice in the docker CLI side.

**Comment by thaJeztah** [comment]
Should this default be set daemon-side, and not in the client?

**Comment by stevvooe** [comment]
> Should this default be set daemon-side, and not in the client?

No, this should be all client-side. The daemon should avoid dealing in these niceties in case we want to change it in the future.

LGTM

I'd like to hear what @dnephin @aanand have to say here.

**Comment by dnephin** [comment]
LGTM

File: api/client/node/ps.go [hunk 1]
```diff
@@ -18,16 +18,20 @@ type psOptions struct {
...
-		Use:   "ps [OPTIONS] self|NODE",
-		Short: "List tasks running on a node",
-		Args:  cli.ExactArgs(1),
+		Use:   "ps [OPTIONS] [NODE]",
+		Short: "List tasks running on a node, default to self",
+		Args:  cli.RequiresRangeArgs(0, 1),
 		RunE: func(cmd *cobra.Command, args []string) error {
-			opts.nodeID = args[0]
-			return runPS(dockerCli, opts)
+			if len(args) == 0 {
```
Comment (crosbymichael) [inline api/client/node/ps.go]: We usually try to avoid if else.  You can do this by:

```go
opts.NodeID = args[0]
if len(args) == 0 {
    opts.NodeID = "self"
}
```

Comment (allencloud) [inline api/client/node/ps.go]: @crosbymichael 
I was wondering if len(args) == 0, there is no data in slice, then args[0] will throw an error.
So I chose to judge first.

Comment (stevvooe) [inline api/client/node/ps.go]: @allencloud Use a switch:

```go
switch len(args) {
case 0: opts.NodeID = "self"
case 1: opts.NodeID = args[0]
default: return err
}
```

Comment (allencloud) [inline api/client/node/ps.go]: Actually, I misunderstood @crosbymichael. I prefer 
```
opts.NodeID = args[0]
if len(args) == 0 {
    opts.NodeID = "self"
}
```
As we already use `Args:  cli.RequiresRangeArgs(0, 1)`, I think it's no need to use a switch. WDYT? @stevvooe

**Comment by allencloud** [comment]
Any update ? @vieux @stevvooe @dnephin @thaJeztah @crosbymichael

File: docs/reference/commandline/index.md [hunk 2]
```diff
@@ -115,7 +115,7 @@ read the [`dockerd`](dockerd.md) reference page.
 | [node demote](node_demote.md) | Demotes an existing manager so that it is no longer a manager |
 | [node inspect](node_inspect.md) | Inspect a node in the swarm                |
 | [node update](node_update.md) | Update attributes for a node                 |
-| [node ps](node_ps.md) | List tasks running on a node                   |
+| [node ps](node_ps.md) | List tasks running on a node, default to self                   |
```
Comment (thaJeztah) [inline docs/reference/commandline/index.md]: s/default to/defaults to/

File: docs/reference/commandline/node_ps.md [hunk 3]
```diff
@@ -12,9 +12,9 @@ parent = "smn_cli"
 # node ps
 
 ```markdown
-Usage:  docker node ps [OPTIONS] self|NODE
+Usage:  docker node ps [OPTIONS] [NODE]
 
-List tasks running on a node
+List tasks running on a node, default to self
```
Comment (thaJeztah) [inline docs/reference/commandline/node_ps.md]: s/default to/defaults to/

Comment (thaJeztah) [inline docs/reference/commandline/node_ps.md]: Or perhaps "if no node is specified, defaults to the current node"

File: api/client/node/ps.go [hunk 4]
```diff
@@ -18,16 +18,20 @@ type psOptions struct {
...
 
 	cmd := &cobra.Command{
-		Use:   "ps [OPTIONS] self|NODE",
-		Short: "List tasks running on a node",
-		Args:  cli.ExactArgs(1),
+		Use:   "ps [OPTIONS] [NODE]",
+		Short: "List tasks running on a node, default to self",
+		Args:  cli.RequiresRangeArgs(0, 1),
 		RunE: func(cmd *cobra.Command, args []string) error {
 			opts.nodeID = args[0]
```
Comment (dnephin) [inline api/client/node/ps.go]: This will panic if args is `[]string{}`, right?

File: docs/reference/commandline/index.md (hunk 2 above)
Comment (thaJeztah) [inline docs/reference/commandline/index.md]: Actually, I think we can remove `, default to self` here, because this is only an overview of links.

File: api/client/node/ps.go (hunk 1 above)
Comment (allencloud) [inline api/client/node/ps.go]: I turned back to `if else`, as my original reason.

File: api/client/node/ps.go (hunk 4 above)
Comment (allencloud) [inline api/client/node/ps.go]: I think so, I turned back to `if else`. Sorry for my bothering brought to you.

**Comment by vdemeester** [comment]
code LGTM 🐮

File: api/client/node/ps.go (hunk 1 above)
Comment (cpuguy83) [inline api/client/node/ps.go]:
```
opts.NodeID = "self"
if len(args) != 0 {
  opts.NodeID = args[0]
}
```

**Comment by cpuguy83** [comment]
One nit (else is horrible)... but LGTM
Moving to docs review.

File: api/client/node/ps.go (hunk 1 above)
Comment (allencloud) [inline api/client/node/ps.go]: Thanks @cpuguy83 
Updated that. I think the way suggested is much better.

**Comment by vdemeester** [comment]
docs LGTM 🐸

File: contrib/completion/zsh/_docker [hunk 5]
```diff
@@ -788,7 +788,7 @@ __docker_node_commands() {
         "ls:List nodes in the swarm"
         "promote:Promote a node as manager in the swarm"
         "rm:Remove one or more nodes from the swarm"
-        "ps:List tasks running on a node"
```
Comment (yanheven) [inline contrib/completion/zsh/_docker]: I prefer: defaults to current node

File: contrib/completion/zsh/_docker [hunk 6]
```diff
@@ -788,7 +788,7 @@ __docker_node_commands() {
...
+        "ps:List tasks running on a node, defaults to self"
```
Comment (yanheven) [inline contrib/completion/zsh/_docker]: I prefer: defaults to current node

**Comment by stevvooe** [comment]
LGTM

Could we follow this up with a PR to make it easy to provide several nodes?

**Comment by allencloud** [comment]
@stevvooe 
Sorry for my not following you by `make it easy to provide several nodes`？ Could you explain more on that?
Thanks a lot.

**Comment by stevvooe** [comment]
@allencloud `docker node ps node-1 node-2 node-3`

**Comment by allencloud** [comment]
@stevvooe 
I can try to do that.
With another brand new PR after this merged in,
or with a following commit in this old PR?

**Comment by stevvooe** [comment]
@allencloud Another PR, please. Let's get this one merged.

**Comment by allencloud** [comment]
@stevvooe  Thanks. OK , I will do that after merged.

File: contrib/completion/zsh/_docker (hunk 6 above)
Comment (yanheven) [inline contrib/completion/zsh/_docker]: defaults to current node

Comment (allencloud) [inline contrib/completion/zsh/_docker]: Thanks for your advice. @yanheven
@stevvooe @thaJeztah WDYT?
And both are OK for me.

Comment (stevvooe) [inline contrib/completion/zsh/_docker]: "current node" for some definition of "current node".

This is going to list tasks for the node on which the request ingresses the engine-api and would be limited to manager nodes. This is probably okay.

Comment (allencloud) [inline contrib/completion/zsh/_docker]: Thanks @stevvooe @yanheven . Updated.

**Comment by allencloud** [comment]
PTAL @stevvooe @vdemeester @dnephin 
Could we merge this, and follow this with another PR?

**Comment by dnephin** [comment]
LGTM
