### PR TITLE
logger: copy to log driver's bufsize, fixes #34887

### LINKED ISSUE #34887: awslogs driver doesn't handle Partial messages
**Description**

When log lines exceed the internal copier buffer size of [16K](https://github.com/moby/moby/blob/5c10698d5c5223f9cb49704124be592e3d39d0df/daemon/logger/copier.go#L13), the copier chunks the message and flags the message as a Partial line and expects that the log driver would perform any necessary work to reassemble. The awslogs driver does not have this capability today and treats each message, regardless of Partial status, as an entire line. I propose we introduce one of the following solutions:

1. Partial handling in the awslogs driver and buffer the line internally up to CloudWatch Logs' limits.

2. Sized Loggers that may indicate a different buffer size is desired by the backing log driver so that larger lines may be delivered to the driver without chunking.

Solution 1 (#34889) maintains the current copier behavior wherein the drivers must reconstruct log lines as appropriate to their uses. Each line is buffered in the driver and uses an expanding slice up to its maximum (which is enforced and handled correctly already).

Solution 2 (#34888) allows the driver to indicate to the copier that a larger buffer should be used. This enables the driver to perform less partial line reconstruction work without granting unbounded memory consumption and leads to a smaller number of buffer allocations needed.

**Steps to reproduce the issue:**

1. Log a long log line (>16K bytes) to the awslogs driver (using it as [documented](https://docs.docker.com/engine/admin/logging/awslogs/)).
2. Check CloudWatch Logs and see multiple entries for the single long line.

**Describe the results you received:**

When logging a line longer than the logger buffer size of 16K, the line is split into chunks of 16K.

**Describe the results you expected:** 

I expected to see a single line as a single event up to the [CloudWatch Logs service limit](https://github.com/moby/moby/blob/5c10698d5c5223f9cb49704124be592e3d39d0df/daemon/logger/awslogs/cloudwatchlogs.go#L46) for the event payload.

**Additional information you deem important (e.g. issue happens only
occasionally):**

This behavior still remains in the `github.com/moby/moby/daemon/logger/awslogs` package today and both solutions were recently rebased.

**Output of `docker version`:**

Using development instance to swap out daemons, this is from [master](https://github.com/moby/moby/commit/c5c0702a4d523071b3e41a13c233b6ec9e261b06) :

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   7392c3b/17.03.2-ce
 Built:        Wed Aug  9 22:45:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-dev
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   c5c0702a4
 Built:        Mon Sep 18 19:16:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

Using development instance to swap out daemons, this is from [master](https://github.com/moby/moby/commit/c5c0702a4d523071b3e41a13c233b6ec9e261b06) :

```
Containers: 30
 Running: 5
 Paused: 0
 Stopped: 25
Images: 2
Server Version: 17.06.0-dev
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3kB
 Base Device Size: 10.74GB
 Backing Filesystem: ext4
 Data file: 
 Metadata file: 
 Data Space Used: 1.35GB
 Data Space Total: 23.35GB
 Data Space Available: 22GB
 Metadata Space Used: 1.528MB
 Metadata Space Total: 25.17MB
 Metadata Space Available: 23.64MB
 Thin Pool Minimum Free Space: 2.335GB
 Udev Sync Supported: false
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.137 (2016-11-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 1c81e2a794c6e26a4c650142ae8893c47f619764
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.43-17.38.amzn1.x86_64
Operating System: Amazon Linux AMI 2017.03
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: ip-172-31-29-173
ID: JXKV:VXGJ:UNDH:T6GD:S4I2:VKY7:S5Q7:7ZPM:BZ7R:4EH3:K4BR:HY7A
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS EC2 Instance: t2.small

### PR DESCRIPTION
**Pull request by jahkeup**
Log drivers may have an internal buffer size that can be accommodated
by the copier as it is more effective to buffer and send fewer though
larger messages that the log driver can consume.

This eliminates the need for Partial handling for drivers that do not
support the concept (ie: awslogs, which can only have events up to
service limits).

**- What I did**

I added an interface to the logger package that allows drivers to specify a buffer size for the copier to use for buffering reads.

**- How I did it**

I added a single function interface that allows drivers to indicate what the size is that should be used, and called them `SizedLogger`'s.

**- How to verify it**

`go test` includes a test case to verify that when this interface is implemented that the driver's will receive larger message buffers. See #34887 for use case and steps to reproduce.

**- Description for the changelog**

log drivers can now specify buffer size for buffering container log output

### CODE REVIEW

**Comment by samuelkarp** [comment]
> daemon/logger/logger.go:84:6:warning: exported type SizedLogger should have comment or be unexported (golint)

Can you fix the golint failure?

**Comment by crassirostris** [comment]
I suggest to implement a more generic approach: https://github.com/moby/moby/pull/34913

More context in https://github.com/moby/moby/issues/34855, in short -- the ability to set the log size for all log drivers is important and is a superset of the functionality of this PR. Are you fine with that?

**Comment by samuelkarp** [comment]
@crassirostris It doesn't make sense to have the max size be user-configurable for the awslogs driver.  The max size here is driven by the CloudWatch Logs API and is not expected to change for different users.

**Comment by crassirostris** [comment]
@samuelkarp You can specify this limit together with specifying the logging driver type

But I see the argument. Can we make these two efforts work together then? E.g. user-defined limit > plugin-defined limit > default limit

**Comment by samuelkarp** [comment]
> You can specify this limit together with specifying the logging driver type

Yes, but you shouldn't have to.

> Can we make these two efforts work together then? E.g. user-defined limit > plugin-defined limit > default limit

I think that would make sense, though I'd argue that a user-defined limit > driver-defined limit should be an error.

**Comment by crassirostris** [comment]
> I think that would make sense, though I'd argue that a user-defined limit > driver-defined limit should be an error.

Makes sense to me also

**Review by cpuguy83 — COMMENTED** [review]
This seems reasonable. At least allows the log driver to dictate the buffer size since it'll be buffering anyway.

What about if people want to specify a custom buffer size?

**Comment by crassirostris** [comment]
> What about if people want to specify a custom buffer size?

There are three options:

1. Driver takes precedence over user-defined limit
1. User-defined limit takes precedence over driver
1. They're mutually exclusive

I think 3. is the most robust approach: it's not possible to break a driver by
setting a limit manually as in 1. and at the same time user will have a clear
expectation that their user-defined limit will not be actually applied as in 2.

**Comment by jahkeup** [comment]
@cpuguy83 thanks for taking a look.

> What about if people want to specify a custom buffer size?

I'm not sold on the thought that end users should be able to specify the internal buffer size instead of configuring their driver. The internal buffer size should be based on the implementation and dependencies of the log drivers themselves. However, I would like to see more appropriate buffers sizes used for Messages and I believe this should be handled by the drivers themselves as need to allow drivers to decide how best (and when) to allow user defined size limits. 

Option 3, where users may also specify a buffer size, would prohibit users from specifying a custom buffer size at all if `SizedLogger` is widely adopted. Instead, it makes more sense for drivers to handle this user defined value themselves and surface the user's value when appropriate (eg: `json-file` can pass on the user's custom buffer size when it returns the `BufSize` or return a driver defined default size). If the drivers choose to allow this then they can select a value that makes sense in their respective contexts. In the context of the `awslogs` driver, the buffer size doesn't make sense to be larger, or smaller for that matter - thus users should not be allowed to configure the value at all.

**Comment by crassirostris** [comment]
@jahkeup 

> I'm not sold on the thought that end users should be able to specify the internal buffer size instead of configuring their driver.

Example: logging agent (e.g. fluentd) consuming `json-file`, `journald` or `syslog`. The actual destination of the logging agent may have different limits in different deployments with the same driver. While it's possible to setup in in a per-driver fashion, it results in duplication and is not logical: in `aws` case the driver itself dictates the max line length, but in the setup with a logging agent those requirements come from the outside of Docker ecosystem in general and from outside of log driver in particular.

> If the drivers choose to allow this then they can select a value that makes sense in their respective contexts

Problem is, some drivers do not have this context and can work with any line. As I mentioned earlier, requirements come from the setup, not from the driver

> users should not be allowed to configure the value at all

And that is why I agree that those options should be mutually exclusive

**Comment by jahkeup** [comment]
@crassirostris , in a way we are speaking of the same goal - users should be able to influence their logging drivers and this ultimately will directly or indirectly configure this internal buffer. As for how that is handled: I don't think that users should be able to directly configure the internal buffer's size. I would prefer to see the `--log-opt`, the one you've proposed, handled by individual drivers once `BufSize` is adopted to enable validation and interpretation of the provided user value in the context of each driver rather than at a global level. If it remains on the global level we would have to err on the side of caution for every driver. 

Option 3, enumerated above, is the most sensible in my opinion. However, the topic should be revisited if/when drivers begin to require different handling of user specified size. Until then, I agree that mutually exclusive user-provided-size/`BufSize` is sufficient to support the majority of the drivers today.

**Comment by crassirostris** [comment]
@jahkeup 

> However, the topic should be revisited if/when drivers begin to require different handling of user specified size.

Fully agree

**Review by cpuguy83 — APPROVED** [review]
Design OK for me.
Would love to hear from another maintainer.

**Review by aaronlehmann — APPROVED** [review]

**Comment by thaJeztah** [comment]
ping @vieux could you have a look?

**Comment by mlaventure** [comment]
I personally prefer this approach to #34913

**Comment by cpuguy83** [comment]
Let's move this to code review.
Thanks!

File: daemon/logger/copier_test.go [hunk 1]
```diff
@@ -205,6 +224,43 @@ func TestCopierSlow(t *testing.T) {
...
+	}
+
+	c := NewCopier(map[string]io.Reader{"stdout": &stdout}, sizedLogger)
+	c.Run()
+	wait := make(chan struct{})
+	go func() {
+		c.Wait()
+		close(wait)
+	}()
+	c.Close()
```
Comment (cpuguy83) [inline daemon/logger/copier_test.go]: I'm not sure this is safe.

Comment (cpuguy83) [reply daemon/logger/copier_test.go]: Maybe for `stdout` we can use an `io.Pipe` and copy into it from a goroutine. Once the goroutine is done we know the copier is done.

**Review by cpuguy83 — CHANGES_REQUESTED** [review]

File: daemon/logger/copier_test.go (hunk 1 above)
Comment (jahkeup) [reply daemon/logger/copier_test.go]: Good catch! This could instead better conform to its sibling tests:

```go
c := NewCopier(...)
c.Run()
defer c.Close()
wait := make(chan struct{})
go func() {
	c.Wait()
	close(wait)
}()
select {
case <-time.After(150 * time.Millisecond):
	t.Fatal("Copier failed to do its work in 1 second")
case <-wait:
}

```

If this isn't sensible I'm happy to clean this up using an `io.Pipe`.

Comment (cpuguy83) [reply daemon/logger/copier_test.go]: I think a pipe would be better here otherwise we're just assuming that after some small period of time everything is done, which can lead to a flakey test.

Comment (jahkeup) [reply daemon/logger/copier_test.go]: Gotcha, I'll update this as soon as I have cycles to spare.

File: daemon/logger/copier_test.go [hunk 2]
```diff
@@ -205,6 +223,37 @@ func TestCopierSlow(t *testing.T) {
...
+
+	logbuf := bytes.NewBufferString(strings.Repeat(".", sizedLogger.BufSize()*2))
+	rd, wr := io.Pipe()
+	c := NewCopier(map[string]io.Reader{"stdout": rd}, sizedLogger)
+	c.Run()
+	go func() {
+		io.Copy(wr, logbuf)
+		c.Close()
+	}()
+
```
Comment (cpuguy83) [inline daemon/logger/copier_test.go]: This needs a copier.Wait, I think?

Comment (jahkeup) [reply daemon/logger/copier_test.go]: Yes it certainly does, one sec.

Comment (jahkeup) [reply daemon/logger/copier_test.go]: This change was left out of the update I pushed, my apologies. I've updated the code now with the Wait to ensure the copy jobs are finished.

**Comment by thaJeztah** [comment]
@cpuguy83 PR was updated, PTAL

File: daemon/logger/copier_test.go [hunk 3]
```diff
@@ -205,6 +223,38 @@ func TestCopierSlow(t *testing.T) {
...
+	var jsonBuf bytes.Buffer
+	sizedLogger := &TestSizedLoggerJSON{Encoder: json.NewEncoder(&jsonBuf)}
+
+	logbuf := bytes.NewBufferString(strings.Repeat(".", sizedLogger.BufSize()*2))
+	rd, wr := io.Pipe()
+	c := NewCopier(map[string]io.Reader{"stdout": rd}, sizedLogger)
+	c.Run()
+	go func() {
+		io.Copy(wr, logbuf)
+		c.Wait()
```
Comment (cpuguy83) [inline daemon/logger/copier_test.go]: We need this outside of the goroutine, I think?
Otherwise it will (potentially) decode from the buffer and get an EOF before it's really done.

Comment (jahkeup) [reply daemon/logger/copier_test.go]: We may need a Wait both in the goroutine and outside of it to ensure the Copier doesn't close early while reading the data from the pipe. I think there's the possibility that during the read, given the right size and read offsets, that the Copier could check the closed status of the Copier and cease reading from the pipe input (shouldn't be tickled in this test case but is a point to note). I will add the Wait outside the goroutine as well and see if I can easily cause the test to fail.

Comment (cpuguy83) [reply daemon/logger/copier_test.go]: Alternatively we could ditch the buffer and read directly from the pipe below.

Comment (jahkeup) [reply daemon/logger/copier_test.go]: I'm not sure I follow you on that, can you elaborate some more?

Comment (cpuguy83) [reply daemon/logger/copier_test.go]: Sorry, forget about that. I brain-farted on what we were doing here.

Comment (jahkeup) [reply daemon/logger/copier_test.go]: I believe I've found a more robust and simpler approach. I've pushed that change now. @cpuguy83 PTAL.

File: daemon/logger/copier_test.go [hunk 4]
```diff
@@ -205,6 +223,35 @@ func TestCopierSlow(t *testing.T) {
...
+	c.Run()
+	// Wait for Copier to finish writing to the buffered logger.
+	c.Wait()
+	c.Close()
+
+	dec := json.NewDecoder(&jsonBuf)
+	for {
+		var msg Message
+		if err := dec.Decode(&msg); err != nil {
+			if err == io.EOF {
```
Comment (cpuguy83) [inline daemon/logger/copier_test.go]: If there's nothing in the buffer this will just EOF but could be that the implementation is broken.
Maybe a check to make sure we got the messages we expected.

File: daemon/logger/copier_test.go (hunk 3 above)
Comment (cpuguy83) [reply daemon/logger/copier_test.go]: Oh yes, much simpler.

File: daemon/logger/copier_test.go (hunk 4 above)
Comment (jahkeup) [reply daemon/logger/copier_test.go]: Agreed, I've added a check for the number of messages that are expected and received.

**Comment by thaJeztah** [comment]
@jahkeup looks like CI (golint) is failing;

```
21:58:12 daemon/logger/copier_test.go:254:3:warning: should replace recvdMsgs += 1 with recvdMsgs++ (golint)
21:58:12 Build step 'Execute shell' marked build as failure
```

File: daemon/logger/copier.go [hunk 5]
```diff
@@ -44,7 +49,14 @@ func (c *Copier) Run() {
 
 func (c *Copier) copySrc(name string, src io.Reader) {
 	defer c.copyJobs.Done()
-	buf := make([]byte, bufSize)
+
+	var buf []byte
+	if sizedLogger, ok := c.dst.(SizedLogger); ok {
+		buf = make([]byte, sizedLogger.BufSize())
+	} else {
+		buf = make([]byte, defaultBufSize)
```
Comment (ripcurld0) [inline daemon/logger/copier.go]: I think it would be more readable to make this:

```Go
bufSize := defaultBufSize
if sizedLogger, ok := c.dst.(SizedLogger); ok {
  bufSize = sizedLogger.BufSize()
}
buf := make([]byte, bufSize) 
```

**Review by cpuguy83 — APPROVED** [review]
LGTM with lint fixes (assuming CI passes)

**Comment by thaJeztah** [comment]
looks like https://github.com/moby/moby/pull/34888#issuecomment-340459518 needs a minor update to make CI pass; @jahkeup could you update that? I think plans are to cut off 17.11-rc1 today

**Comment by jahkeup** [comment]
@theJeztah I'll get changes made and pushed ASAP.

File: daemon/logger/copier.go (hunk 5 above)
Comment (jahkeup) [reply daemon/logger/copier.go]: I like it. I'll change and test (with the other requested changes).

**Review by thaJeztah — APPROVED** [review]
LGTM if green, thanks!

**Comment by jahkeup** [comment]
Hooray, thanks all!

**Comment by bitsofinfo** [comment]
Is this available now in any docker release?

**Comment by thaJeztah** [comment]
This was merged 5 months ago, so likely in docker 17.10, or 17.11 and up

**Comment by bitsofinfo** [comment]
@thaJeztah @crassirostris @cpuguy83 

So we are using `json-file` but still having this issue

I'm a bit lost as to where to go to get some help w/ this 16k issue and how it affects the json-file driver or where to fix the problem or what is the status of this with regards to a roadmap for support on this being added?

We are ingesting (and failing) ModSecurity audit logs from many containers which are often > 16k 

https://github.com/elastic/beats/issues/6605

**Comment by thaJeztah** [comment]
@bitsofinfo first of all, note that the files generated by the json-file logging driver are not intended for external consumption. Having said the above; would it help if the json-file logging driver would set the "Partial" field in the generated files? Also see https://github.com/moby/moby/pull/35831

If that would be a solution for your use-case, perhaps you could open a separate issue for that

**Comment by ruflin** [comment]
@thaJeztah New issue is here https://github.com/moby/moby/issues/36777 for further discussion. See my comment there.
