### PR TITLE
Fix partial manifest push

### LINKED ISSUE #15536: Broken multiple tag push
When pushing multiple tags, layers which exist in multiple tags get excluded after the first tag is pushed.

Caused by `layersSeen` not being reset for each tag push.
https://github.com/docker/docker/commit/810d3b2642d4a82dc186d6eff8c2e487ee624bc5

### PR DESCRIPTION
**Pull request by icecrime**
Rather than working around the issue, we suggest to revert the problematic PR, and drop the optimization of not pushing the same layer twice.
- Revert #14484
- Keep the updated regression test introduced in #15539

Fixes #15536.

### CODE REVIEW

**Comment by jfrazelle** [comment]
LGTM, tested locally, I prefer this fix to the other.

**Comment by diogomonica** [comment]
Seems like the quickest way to solve this particular issue. LGTM.

**Comment by NathanMcCauley** [comment]
Test could be slightly better, but this looks right. LGTM

**Comment by icecrime** [comment]
I agree the test is not ideal, but it does fail on master without the other commit.

**Comment by jfrazelle** [comment]
Tests all pass merging

File: integration-cli/docker_cli_push_test.go [hunk 1]
```diff
@@ -61,6 +61,40 @@ func (s *DockerRegistrySuite) TestPushMultipleTags(c *check.C) {
...
+	}
+
+	out2, _ := dockerCmd(c, "pull", repoTag2)
+	if strings.Contains(out2, "Tag t2 not found") {
+		c.Fatalf("Unable to pull pushed image: %s", out1)
+	}
+	var out2Lines []string
+	for _, outputLine := range strings.Split(out2, "\n") {
+		if strings.Contains(outputLine, imageAlreadyExists) {
+			out1Lines = append(out1Lines, outputLine)
```
Comment (kolyshkin) [inline integration-cli/docker_cli_push_test.go]: Here `out1Lines` should actually be `out2Lines`, so I am not quite sure what this test case was testing
