### PR TITLE
Detect overlay2 support on pre-4.0 kernels

### LINKED ISSUE #34368: Allow overlay2 on 7.4 kernel 3.10.0-693.el7.x86_64 or higher?
Allow the uses of overlay2 in the 3.10.0-693.el7.x86_64 kernel now that Redhat officially supports it?

https://github.com/moby/moby/blob/1009e6a40b295187e038b67e184e9c0384d95538/daemon/graphdriver/overlay2/overlay.go#L136-L141

**Steps to reproduce the issue:**
1. Install docker-ce 17.0.6 on rhel 7.4
2. `echo -e "{ \"storage-driver\": \"overlay2\" }" > /etc/docker/daemon.json; systemctl restart docker`

**Describe the results you received:**
Docker should restart.

**Describe the results you expected:**
Docker doesn't support overlay2 on rhel 7.4.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

[root@rhel74 ~]# docker -v
Docker version 17.06.0-ce

**Additional environment details (AWS, VirtualBox, physical, etc.):**
vmware fusion. also tested on aws.

### PR DESCRIPTION
**Pull request by thaJeztah**
fixes https://github.com/moby/moby/issues/34368

The overlay2 storage-driver requires multiple lower dir support for overlayFs. Support for this feature was added in kernel 4.x, but some distros (RHEL 7.4, CentOS 7.4) ship with an older kernel with this feature backported.

This patch adds feature-detection for multiple lower dirs, and will perform this feature-detection on pre-4.x kernels with overlayFS support.

With this patch applied, daemons running on a kernel with multiple lower dir support will now select "overlay2" as storage-driver, instead of falling back to "overlay".

**- Description for the changelog**

```Markdown
+ Add support for `overlay2` storage driver on CentOS/RHEL 7.4 [moby/moby#35527](https://github.com/moby/moby/pull/35527)
```

### CODE REVIEW

**Comment by thaJeztah** [comment]
@kolyshkin @friism @dmcgowan I think this os roughly what's needed, but would need testing, and can use some eyes; opened this so that we can discuss

File: daemon/graphdriver/overlay2/overlay.go [hunk 1]
```diff
@@ -179,6 +173,17 @@ func Init(home string, options []string, uidMaps, gidMaps []idtools.IDMap) (grap
 		return nil, err
 	}
 
+	if kernel.CompareKernelVersion(*v, kernel.VersionInfo{Kernel: 4, Major: 0, Minor: 0}) < 0 {
+		if !opts.overrideKernelCheck {
```
Comment (dmcgowan) [inline daemon/graphdriver/overlay2/overlay.go]: Logic is reversed, should be `if opts.overrideKernelCheck`

File: daemon/graphdriver/overlay2/check.go [hunk 2]
```diff
@@ -100,3 +100,48 @@ func doesSupportNativeDiff(d string) error {
...
+	if err := os.Mkdir(filepath.Join(td, "work"), 0755); err != nil {
+		return err
+	}
+	if err := os.Mkdir(filepath.Join(td, "merged"), 0755); err != nil {
+		return err
+	}
+
+	opts := fmt.Sprintf("lowerdir=%s:%s,upperdir=%s,workdir=%s", path.Join(td, "lower2"), path.Join(td, "lower1"), path.Join(td, "upper"), path.Join(td, "work"))
+	if err := unix.Mount("overlay", filepath.Join(td, "merged"), "overlay", 0, opts); err != nil {
+		return errors.Wrap(err, "failed to mount overlay")
```
Comment (dmcgowan) [inline daemon/graphdriver/overlay2/check.go]: What is the error that gets returned when it is not supported?

**Review by dmcgowan — CHANGES_REQUESTED** [review]

**Review by kolyshkin — CHANGES_REQUESTED** [review]

File: daemon/graphdriver/overlay2/overlay.go (hunk 1 above)
Comment (thaJeztah) [reply daemon/graphdriver/overlay2/overlay.go]: Oh! Yes, last-minute change before I pushed, thought to keep the Warning in place so made it an if/else; updating

File: daemon/graphdriver/overlay2/check.go [hunk 3]
```diff
@@ -100,3 +100,48 @@ func doesSupportNativeDiff(d string) error {
...
+	}
+	if err := os.Mkdir(filepath.Join(td, "upper"), 0755); err != nil {
+		return err
+	}
+	if err := os.Mkdir(filepath.Join(td, "work"), 0755); err != nil {
+		return err
+	}
+	if err := os.Mkdir(filepath.Join(td, "merged"), 0755); err != nil {
+		return err
+	}
```
[the remark this answers is not in the document]
Comment (thaJeztah) [reply daemon/graphdriver/overlay2/check.go]: Yes, I like that (I used the other check in this file as a starting point, but that looks better 👍)

File: daemon/graphdriver/overlay2/check.go (hunk 2 above)
Comment (thaJeztah) [reply daemon/graphdriver/overlay2/check.go]: I saw @kolyshkin tested this;

CentOS version | Kernel version | Compile date | Error
--- | --- | --- | ---
7.1 | 3.10.0-229.1.2.el7.x86_64 | ? | failed to mount overlay: invalid argument
7.1 | 3.10.0-229.20.1.el7.x86_64 | ? | failed to mount overlay: invalid argument
7.2 | 3.10.0-327.el7.x86_64 | Nov 19 2015 | nil
7.2 | 3.10.0-327.36.3.el7.x86_64 | Oct 24 2016 | nil
7.3 | 3.10.0-514.26.2.el7.x86_64 | Jul 4 2017  | nil

**Review by dmcgowan — APPROVED** [review]
LGTM

File: daemon/graphdriver/overlay2/check.go [hunk 4]
```diff
@@ -100,3 +100,35 @@ func doesSupportNativeDiff(d string) error {
...
 	return nil
 }
+
+// supportsMultipleLowerDir checks if the system supports multiple lowerdirs,
+// which is required for the overlay2 driver. On 4.x kernels, multiple lowerdirs
+// are always available (so this check isn't needed), and backported to RHEL and
+// CentOS 3.x kernels (3.10.0-693.el7.x86_64 and up). This function is to detect
+// support on those kernels, without doing a kernel version compare.
+func supportsMultipleLowerDir(d string) error {
+	td, err := ioutil.TempDir(d, "multiple-lowerdir-check")
```
Comment (andrewhsu) [inline daemon/graphdriver/overlay2/check.go]: @kolyshkin curious to know if this was tested with selinux enabled? just wanted to make sure the writing to tmp works.

**Comment by kolyshkin** [comment]
> curious to know if this was tested with selinux enabled? just wanted to make sure the writing to tmp works.

@andrewhsu good question! I did my checks on the box with selinux disabled, but by looking at the code I see that directories are created under the graphdriver "home" dir which should succeed as long as docker+selinux is confgured properly.

The above is purely theoretical though; I'll do some real checks

**Comment by kolyshkin** [comment]
Oops
```
Nov 28 04:37:42 kir-ce71 dockerd[669]: time="2017-11-28T04:37:42.349701814Z" level=debug msg="Multiple lower dirs not supported: stat /var/lib/docker/overlay2: no such file or directory"
```

I guess we should either do something like
```diff
-                         if err := supportsMultipleLowerDir(home); err != nil {
+                        if err := supportsMultipleLowerDir(filepath.Dir(home)); err != nil {
```

or move the creation of the driver home to above this check (and make sure to remove the dir on error path). I like the former version more.

**Comment by thaJeztah** [comment]
@kolyshkin looking at the code, if `/var/lib/docker` (`--data-root`) isn't there yet, how does the check for `fsmagic` work in this case? 

```go
fsMagic, err := graphdriver.GetFSMagic(home)
```

**Comment by thaJeztah** [comment]
Oh, never mind that takes the parent directory

**Comment by thaJeztah** [comment]
@kolyshkin updated; could you check with SELinux? (given that it now will check `/var/lib` instead of `/var/lib/docker`).

Alternatively, we should create `/var/lib/docker` before the graphdriver checks are performed

**Comment by kolyshkin** [comment]
> (given that it now will check /var/lib instead of /var/lib/docker)

By looking at the code, it seems it is checking `/var/lib/docker` (as it is a parent dir of driver's home, `/var/lib/docker/overlay2`).

Anyway, it works!

**Comment by kolyshkin** [comment]
The test to start dockerd was done
- on a CentOS 7.4 machine with kernel downgraded to 3.10.0-327.el7.x86_64
- with selinux turned on
- with /var/lib/docker removed

## A relevant quote from the logs

Nov 29 02:46:02 kir-ce71 dockerd[7988]: time="2017-11-29T02:46:02.898726143Z" level=info msg="Loading containers: done."
Nov 29 02:46:02 kir-ce71 dockerd[7988]: time="2017-11-29T02:46:02.905776790Z" level=warning msg="Not using native diff for overlay2, this may cause degraded performance for building images: opaque flag erroneously copied up, consider update to kernel 4.8 or later to fix"
Nov 29 02:46:02 kir-ce71 dockerd[7988]: time="2017-11-29T02:46:02.915391003Z" level=info msg="Docker daemon" commit=bb370f5 graphdriver(s)=overlay2 version=dev
Nov 29 02:46:02 kir-ce71 dockerd[7988]: time="2017-11-29T02:46:02.915733174Z" level=info msg="Daemon has completed initialization"

## Test sequence:
```
# systemctl stop docker
# mv /var/lib/docker{,-moved}
# systemctl start docker
```

## System info:
```
# uname -a
Linux kir-ce71 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@kir-ce71 ~]# selinuxenabled ; echo $?
0
```

**Review by kolyshkin — APPROVED** [review]
LGTM (IANAM)

**Review by vieux — APPROVED** [review]
LGTM
