### PR TITLE
return err when both two service modes in request

### LINKED ISSUE #26642: docker allows both global and replicated mode in api request
**Description**
I send a service create request in postman `192.168.0.104:2375/services/create`, with the request body, in the request body both `replicated` and `global` modes are set which seems unreasonable:
```
{
        "EndpointSpec": {},
        "UpdateConfig": {
            "Parallelism": 1
        },
        "Mode": {
            "Replicated": {
                "Replicas": 1
            },
            "Global":{}
        },
        "TaskTemplate": {
            "RestartPolicy": {
                "Window": 0,
                "MaxAttempts": 0
            },
            "Placement": {
                "Constraints": []
            },
            "ContainerSpec": {
                "Labels": {
                    "io.daocloud.dce.authz.owner": "admin",
                    "io.daocloud.group": "hadoop-cluster"
                },
                "Command": [],
                "User": "",
                "Env": [
                    "HADOOP_RM_HOST=cluster01resourcemanager01"
                ],
                "Image": "ubuntu:14.04",
                "Args": [
                    "sleep",
                    "100000"
                ],
                "Dir": ""
            },
            "Resources": {
                "Reservation": {},
                "Limits": {
                    "MemoryBytes": 0,
                    "NanoCpus": 0
                }
            },
            "LogDriver": {
                "Name": "json-file",
                "Options": {}
            }
        }
    }
```

while dockerd returns `201(created)`, and 
```
{
  "ID": "0qo1kox2zmi6lch1guha42dxy"
}
```
And this service is global mode.

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
```
{
  "ID": "0qo1kox2zmi6lch1guha42dxy"
}
```

**Describe the results you expected:**
Get an error telling user this is illegal.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
root@ubuntu:~# docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
root@ubuntu:~# docker info
Containers: 88
 Running: 19
 Paused: 0
 Stopped: 69
Images: 52
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 614
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: macvlan bridge host null overlay
Swarm: active
 NodeID: bwhn25sl7f3ajxqn0m8dpv825
 Is Manager: true
 ClusterID: b680epf619kiccm7lswsmd1ux
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.0.104
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: ubuntu
ID: HRBI:EV6M:3NAC:CXZ3:BDS7:UOKL:PD6Y:ZCK4:V3PF:V7MR:CU2Y:3LGG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 109
 Goroutines: 366
 System Time: 2016-09-16T06:03:40.474643369+08:00
 EventsListeners: 18
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by allencloud**
fixes #26642 

**\- What I did**
When validating service mode in dockerd, if both service modes `replicated` and `global` are set, return an error to tell user instead of creating a global mode service.

**\- How I did it**

**\- How to verify it**

**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**

Signed-off-by: allencloud allen.sun@daocloud.io

### CODE REVIEW

File: daemon/cluster/convert/service.go [hunk 1]
```diff
@@ -185,7 +185,11 @@ func ServiceSpecToGRPC(s types.ServiceSpec) (swarmapi.ServiceSpec, error) {
 		}
 	}
 
-	//Mode
+	// Mode
+	if s.Mode.Global != nil && s.Mode.Replicated != nil {
+		return swarmapi.ServiceSpec{}, fmt.Errorf("Can not specify both replicated mode and global mode")
```
Comment (aaronlehmann) [inline daemon/cluster/convert/service.go]: For consistency with other error messages:

```
cannot specify both replicated mode and global mode
```

Comment (allencloud) [inline daemon/cluster/convert/service.go]: Thanks @aaronlehmann . updated.

**Comment by aaronlehmann** [comment]
LGTM

**Comment by stevvooe** [comment]
LGTM
