### PR TITLE
Sort output of `docker ps --filter` with order by creation time

### LINKED ISSUE #25374: Docker 1.12 ps filter result is non-deterministic
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS - Ubuntu 14.04 LTS

**Steps to reproduce the issue:**
1. Have more than one container running with a similar name (e.g. `xyz-abc`, `xyz-123`)
2. Run `docker ps -q -f name=xyz`

**Describe the results you received:**

Containers are listed in random order; rerunning the `docker ps` command in step 2 repeatedly returns different results

**Describe the results you expected:**

To see the containers listed in reverse created order, as they are in `docker ps`.

**Additional information you deem important (e.g. issue happens only occasionally):**

There's no way to sort the results by created date, is there?

### PR DESCRIPTION
**Pull request by yongtang**
**\- What I did**

This fix tries to address the issue raised in #25374 where the output of `docker ps --filter` is in random order and not deterministic.

**\- How I did it**

This fix sorts the list of containers by creation time so that the output is deterministic.

**\- How to verify it**

An integration test has been added.

**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**

This fix fixes #25374.

Signed-off-by: Yong Tang yong.tang.github@outlook.com

### CODE REVIEW

File: integration-cli/docker_cli_ps_test.go [hunk 1]
```diff
@@ -864,3 +864,37 @@ func (s *DockerSuite) TestPsListContainersFilterNetwork(c *check.C) {
...
+
+	name3 := "789-abc"
+	out, err = runSleepingContainer(c, "--name", name3)
+	c.Assert(err, checker.NotNil)
+	c.Assert(strings.TrimSpace(out), checker.Not(checker.Equals), "")
+
+	name4 := "789-123"
+	out, err = runSleepingContainer(c, "--name", name4)
+	c.Assert(err, checker.NotNil)
+	c.Assert(strings.TrimSpace(out), checker.Not(checker.Equals), "")
```
Comment (zhanghan177) [inline integration-cli/docker_cli_ps_test.go]: Do you need the above code from
>name3 := "789-abc"
...
\<above_line\>

?

Comment (yongtang) [inline integration-cli/docker_cli_ps_test.go]: @zhanghan177 the above is for the scenario where you have more containers overall than the filtered containers output (we are testing `ps -f name=xyz` in the following)

File: integration-cli/docker_cli_ps_test.go [hunk 2]
```diff
@@ -864,3 +864,37 @@ func (s *DockerSuite) TestPsListContainersFilterNetwork(c *check.C) {
...
+
+	// Run multiple time should have the same result
+	out, err = dockerCmd(c, "ps", "-q", "-f", "name=xyz")
```
Comment (thaJeztah) [inline integration-cli/docker_cli_ps_test.go]: nit: perhaps add `--no-trunc`, and use the full ID's?

File: daemon/list.go [hunk 3]
```diff
@@ -166,6 +176,10 @@ func (daemon *Daemon) reduceContainers(config *types.ContainerListOptions, reduc
 	// end up locking and querying many more containers than intended
 	containerList := daemon.filterByNameIDMatches(ctx)
 
+	// We have to do the sort here as types.Container's Created can only
+	// give us Creation time  in second
+	sort.Sort(sort.Reverse(byContainerCreated(containerList)))
```
Comment (thaJeztah) [inline daemon/list.go]: Given that the containers *only* get out of order if the list is filtered by Name (or ID) in `filterByNameIDMatches`, I think this should be moved to line 162 (before `return cntrs`)

Comment (thaJeztah) [inline daemon/list.go]: e.g.

```golang
	// Restore sort-order after filtering
	sort.Sort(sort.Reverse(byContainerCreated(cntrs)))
```

**Comment by thaJeztah** [comment]
Thanks @yongtang; left some comments/suggestions, but works good otherwise

File: integration-cli/docker_cli_ps_test.go (hunk 2 above)
Comment (yongtang) [inline integration-cli/docker_cli_ps_test.go]: Thanks @thaJeztah! I forgot there is `--no-trunc` for `docker ps`.

File: daemon/list.go (hunk 3 above)
Comment (yongtang) [inline daemon/list.go]: Thanks @thaJeztah. Let me update the PR shortly.

**Comment by yongtang** [comment]
@thaJeztah The pull request has been updated. Please let me know if there are any issues.

**Comment by thaJeztah** [comment]
Awesome! LGTM

ping @estesp @vdemeester PTAL

**Comment by vdemeester** [comment]
LGTM :cat:

**Comment by thaJeztah** [comment]
Added this to the 1.12.1 milestone as this is a regression introduced in 1.12 (through https://github.com/docker/docker/pull/23084)
