### PR TITLE
Fix v28 regression `protocol "tcp" is not supported by the RootlessKit port driver "slirp4netns"`

### LINKED ISSUE #49499: v28 regression: `protocol "tcp" is not supported by the RootlessKit port driver "slirp4netns", discarding request for "[::]:8080"`
### Description

`DOCKERD_ROOTLESS_ROOTLESSKIT_PORT_DRIVER=slirp4netns` no longer works with Docker v28.0.0.
```console
$ docker run -p 8080:80 nginx:alpine
docker: Error response from daemon: driver failed programming external connectivity on endpoint hungry_darwin (57b84dd9bada5b76efdeb749a36675ead1cd67c2eab22912b0ea48b9839fdb08): protocol "tcp" is not supported by the RootlessKit port driver "slirp4netns", discarding request for "[::]:8080"

Run 'docker run --help' for more information
```

### Reproduce

```bash
dockerd-rootless-setuptool.sh install
```
`docker run -p` still works here, but it fails after setting `DOCKERD_ROOTLESS_ROOTLESSKIT_PORT_DRIVER=slirp4netns`

```bash
mkdir -p ~/.config/systemd/user/docker.service.d
cat <<EOF > ~/.config/systemd/user/docker.service.d/override.conf
[Service]
Environment="DOCKERD_ROOTLESS_ROOTLESSKIT_PORT_DRIVER=slirp4netns"
EOF
systemctl --user daemon-reload 
systemctl --user restart docker
```

### Expected behavior

It should still work

### docker version

```bash
$ docker version
Client: Docker Engine - Community
 Version:           28.0.0
 API version:       1.48
 Go version:        go1.23.6
 Git commit:        f9ced58
 Built:             Wed Feb 19 22:11:33 2025
 OS/Arch:           linux/arm64
 Context:           rootless

Server: Docker Engine - Community
 Engine:
  Version:          28.0.0
  API version:      1.48 (minimum version 1.24)
  Go version:       go1.23.6
  Git commit:       af898ab
  Built:            Wed Feb 19 22:11:33 2025
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.7.25
  GitCommit:        bcc810d6b9066471b0b6fa75f557a15a1cbf31bb
 runc:
  Version:          1.2.4
  GitCommit:        v1.2.4-0-g6c52b3f
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
 rootlesskit:
  Version:          2.3.2
  ApiVersion:       1.1.1
  NetworkDriver:    slirp4netns
  PortDriver:       slirp4netns
  StateDir:         /run/user/501/dockerd-rootless
 slirp4netns:
  Version:          1.2.1
  GitCommit:        09e31e92fa3d2a1d3ca261adaeb012c8d75a8194
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    28.0.0
 Context:    rootless
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.33.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 5
  Running: 0
  Paused: 0
  Stopped: 5
 Images: 1
 Server Version: 28.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: bcc810d6b9066471b0b6fa75f557a15a1cbf31bb
 runc version: v1.2.4-0-g6c52b3f
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  rootless
  cgroupns
 Kernel Version: 6.8.0-51-generic
 Operating System: Ubuntu 24.04.1 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.814GiB
 Name: lima-docker
 ID: ea17e0ba-f1e8-4d02-8576-21a1f620e4d3
 Docker Root Dir: /home/suda.linux/.local/share/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
```

### Workaround

Downgrade Docker to v27.5

```bash
sudo apt-get install docker-ce=5:27.5.1-1~ubuntu.24.04~noble docker-ce-rootless-extras=5:27.5.1-1~ubuntu.24.04~noble docker-ce-cli=5:27.5.0-1~ubuntu.24.04~noble
systemctl --user restart docker
```

### PR DESCRIPTION
**Pull request by AkihiroSuda**
**- What I did**

Fixed #49499

`DOCKERD_ROOTLESS_ROOTLESSKIT_PORT_DRIVER=slirp4netns` was broken since f1e0746c08bf4daa3d9dba6dc6bf6ae928db7ea (PR 48132, v28).

**- How I did it**

Followed the behavior of https://github.com/rootless-containers/rootlesskit/blob/v2.3.2/cmd/rootlesskit-docker-proxy/main.go#L196-L204 (used until Docker v27)

**- How to verify it**

```
dockerd-rootless-setuptool.sh install

mkdir -p ~/.config/systemd/user/docker.service.d
cat <<EOF > ~/.config/systemd/user/docker.service.d/override.conf
[Service]
Environment="DOCKERD_ROOTLESS_ROOTLESSKIT_PORT_DRIVER=slirp4netns"
EOF
systemctl --user daemon-reload 
systemctl --user restart docker

docker run -p 8080:80 nginx:alpine
```

**- Human readable description for the release notes**

```markdown changelog
Fix v28 regression `protocol "tcp" is not supported by the RootlessKit port driver "slirp4netns"`
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: libnetwork/drivers/bridge/port_mapping_linux.go [hunk 1]
```diff
@@ -208,7 +220,7 @@ func (n *bridgeNetwork) addPortMappings(
 		somaxconn = -1 // silently capped to "/proc/sys/net/core/somaxconn"
 	}
 	for i := range bindings {
-		if bindings[i].boundSocket == nil {
+		if bindings[i].boundSocket == nil || bindings[i].rootlesskitUnsupported {
```
Comment (thaJeztah) [inline libnetwork/drivers/bridge/port_mapping_linux.go:223]: Silly question; would either removing the binding, or setting that `boundSocket` to nil in the loop further up work? (It's probably fine for now, but trying to see if there's options to handle this gracefully without adding another a new property that may need to be handled elsewhere as well; The `bindings` are returned by this function, so could we have other codepaths that now would have to be made aware "but if this propertiy is set, you must skip XYZ)?

Comment (AkihiroSuda) [reply libnetwork/drivers/bridge/port_mapping_linux.go:223]: I'm nots sure. These seem to be different concepts.

File: libnetwork/drivers/bridge/internal/rlkclient/rootlesskit_client_linux.go [hunk 2]
```diff
@@ -128,10 +139,11 @@ func (c *PortDriverClient) AddPort(
...
 		// Most users are using "builtin" port driver and will not see this warning.
-		return nil, fmt.Errorf("protocol %q is not supported by the RootlessKit port driver %q, discarding request for %q",
-			proto,
-			c.portDriverName,
-			net.JoinHostPort(hostIP.String(), strconv.Itoa(hostPort)))
+		err := &ProtocolUnsupportedError{
+			apiProto:       apiProto,
+			portDriverName: c.portDriverName,
+		}
+		return nil, err
```
Comment (thaJeztah) [inline libnetwork/drivers/bridge/internal/rlkclient/rootlesskit_client_linux.go:146]: Related to that; I see at the start of this function we have logic for if there's no portdriverclient, in which case we return a stub remover func;

```
return func() error { return nil }, nil
```


(again, just exploring what would make "we tried to map the port, weren't able to, but it's ok to skip this port" fit into existing logic)

**Review by robmry — APPROVED** [review]
LGTM - thank you @AkihiroSuda.

File: libnetwork/drivers/bridge/port_mapping_linux.go (hunk 1 above)
Comment (robmry) [reply libnetwork/drivers/bridge/port_mapping_linux.go:223]: Perhaps we can do something else later but, for a 28.0 patch, I think this is simple and safe - minimal change to the existing logic.

Comment (thaJeztah) [reply libnetwork/drivers/bridge/port_mapping_linux.go:223]: Yes, that's fair. It's currently scoped to just a few locations; mostly commenting as we had some other cases where we added some additional properties, and over time that introduced complexity because of special-casing that could've been deducted from other information (and through that becoming a "not so special" case)

**Comment by thaJeztah** [comment]
OH! One last question; we _do_ install rootlesskit in our dev-container; any idea why CI didn’t catch the issue, or are we not running a test that tries? https://github.com/moby/moby/blob/459686bbea46f0a50bc81850603dc399271c078b/Dockerfile#L363

**Comment by AkihiroSuda** [comment]
DOCKERD_ROOTLESS_ROOTLESSKIT_PORT_DRIVER=slirp4netns is not covered in the CI.
Defaults to the "bultin" driver.

**Comment by thaJeztah** [comment]
Ah, gotcha, thanks! Probably something we should look at if we could add a stage for that? (For after this)

**Review by thaJeztah — APPROVED** [review]
LGTM
