### PR TITLE
Fix ChTimes to prevent setting times past the Unix Max Time

### LINKED ISSUE #17451: Docker unit test TestChtimes fails on 32bit ARM server
Description of problem:
When running the Docker unit tests on an ARM 32bit server I get the following error

```
19:54:43 + go test -test.timeout=120m github.com/docker/docker/pkg/system
19:54:44 --- FAIL: TestChtimes (0.00s)
19:54:44 	chtimes_test.go:86: Expected: 2242-03-16 12:56:31 +0000 UTC, got: 1969-12-31 23:59:59 +0000 UTC
19:54:44 --- FAIL: TestChtimesLinux (0.00s)
19:54:44 	chtimes_unix_test.go:77: Expected: 2242-03-16 12:56:31 +0000 UTC, got: 1969-12-31 23:59:59 +0000 UTC
19:54:44 FAIL
19:54:44 coverage: 45.3% of statements
19:54:44 
19:54:44 Tests failed: ./pkg/system
```
It seems like these tests were introduced with the following commit https://github.com/docker/docker/commit/40b77af234319f02029368732249c2de0babb380

Testing this from the current docker/docker master branch with 1.9.0-dev.

@darrenstahlmsft Why exactly are you using 33 in "unixEpochTime.Add((1<<33 - 1) * time.Second)"?

`docker version`:
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2-dirty
OS/Arch (client): linux/arm
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2-dirty
OS/Arch (server): linux/arm

`docker info`:
Containers: 1
Images: 46
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 48
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 4.2.5-260
Operating System: Ubuntu 15.04
CPUs: 4
Total Memory: 1.974 GiB
Name: scw-01
ID: 6PUR:TCAR:3PF3:6BKA:DWFL:PQS6:2JMH:XUTO:BLZF:JTRK:M4QK:LPFZ

`uname -a`:
Linux scw-01 4.2.5-260 #1 SMP Tue Oct 27 13:32:30 UTC 2015 armv7l armv7l armv7l GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
Scaleway ARM Server, physical

Steps to Reproduce:
1. make test-unit
2.
3.

Actual Results:
1969-12-31 23:59:59 +0000 UTC

Expected Results:
2242-03-16 12:56:31 +0000 UTC

### PR DESCRIPTION
**Pull request by darstahl**
Signed-off-by: Darren Stahl darst@microsoft.com

This should fix #17451

### CODE REVIEW

**Comment by phemmer** [comment]
This isn't correct though. My system is quite happy to set a timestamp of `1<<33 - 1`. In fact it goes quite higher than that too (not sure how far though).

**Comment by darrenstahlmsft** [comment]
Time above 1<<32 - 1 are undefined behavior. It depends on the system.

**Comment by phemmer** [comment]
That's kinda my point. The function shouldn't force an arbitrary limit just because it's not supported universally.
And after trial, my system goes up to 2262-04-11 23:59:59, where as this caps the value at 2106-02-07 06:28:15. A 156 year difference.

How about we either have platform-specific max values. Or if the function encounters an error, have it drop the value until it finds the max (and cache it).

**Comment by darrenstahlmsft** [comment]
@Govinda-Fichtner Can you test this to see if it fixes the unit test on ARM32? I can't seem to get a repro on any systems I test.

@phemmer I've updated the PR to hopefully preserve the maximum range of time and fix the issue.

File: pkg/system/chtimes.go [hunk 1]
```diff
@@ -8,8 +8,8 @@ import (
 // Chtimes changes the access time and modified time of a file at the given path
 func Chtimes(name string, atime time.Time, mtime time.Time) error {
 	unixMinTime := time.Unix(0, 0)
-	// The max Unix time is 33 bits set
-	unixMaxTime := unixMinTime.Add((1<<33 - 1) * time.Second)
+	// The max Unix time is 63 bits set
+	unixMaxTime := time.Unix(0, 1<<63-1)
```
Comment (StefanScherer) [inline pkg/system/chtimes.go]: The second parameter of time.Unix(secs, nsecs) is for nanoseconds. I don't know if this is a valid timestamp with 0 seconds + a too big number for the nanoseconds.

Comment (darrenstahlmsft) [inline pkg/system/chtimes.go]: From the golang time package, "It is valid to pass nsec outside the range [0, 999999999]". The function does the correct conversions to seconds and nanoseconds by design. 

Note: I've got another change to be made here to solve the bug, just trying to set up a machine to repro the bug to test it.

**Comment by StefanScherer** [comment]
OK. But the maximum nanoseconds is not the max unix time.

I'm playing with some different values both on my Mac and on a Raspberry Pi.

Sample code `chtimes.go`

```golang
package main

import (
	"fmt"
	"os"
	"time"
)

func Chtimes(name string, atime time.Time, mtime time.Time) error {
	f, err := os.Create(name)
	defer f.Close()
	if err != nil {
		return err
	}

	if err := os.Chtimes(name, atime, mtime); err != nil {
		return err
	}

	return nil
}

func main() {
	test0_1 := time.Unix(0, 1<<1-1)
	fmt.Println("test0_1", test0_1)
	Chtimes("test0_1.txt", test0_1, test0_1)

	test0_2 := time.Unix(0, 1<<2-1)
	fmt.Println("test0_2", test0_2)
	Chtimes("test0_2.txt", test0_2, test0_2)

	test0_31 := time.Unix(0, 1<<31-1)
	fmt.Println("test0_31", test0_31)
	Chtimes("test0_31.txt", test0_31, test0_31)

	test0_32 := time.Unix(0, 1<<32-1)
	fmt.Println("test0_32", test0_32)
	Chtimes("test0_32.txt", test0_32, test0_32)

	test0_33 := time.Unix(0, 1<<33-1)
	fmt.Println("test0_33", test0_33)
	Chtimes("test0_33.txt", test0_33, test0_33)

	test0_62 := time.Unix(0, 1<<62-1)
	fmt.Println("test0_62", test0_62)
	Chtimes("test0_62.txt", test0_62, test0_62)

	test0_63 := time.Unix(0, 1<<63-1)
	fmt.Println("test0_63", test0_63)
	Chtimes("test0_63.txt", test0_63, test0_63)

	test31_0 := time.Unix(1<<31-1, 0)
	fmt.Println("test31_0", test31_0)
	Chtimes("test31_0.txt", test31_0, test31_0)

	test32_0 := time.Unix(1<<32-1, 0)
	fmt.Println("test32_0", test32_0)
	Chtimes("test32_0.txt", test32_0, test32_0)

	test33_0 := time.Unix(1<<33-1, 0)
	fmt.Println("test33_0", test33_0)
	Chtimes("test33_0.txt", test33_0, test33_0)

	test34_0 := time.Unix(1<<34-1, 0)
	fmt.Println("test34_0", test34_0)
	Chtimes("test34_0.txt", test34_0, test34_0)

	test35_0 := time.Unix(1<<35-1, 0)
	fmt.Println("test35_0", test35_0)
	Chtimes("test35_0.txt", test35_0, test35_0)

	test63_0 := time.Unix(1<<63-1, 0)
	fmt.Println("test63_0", test63_0)
	Chtimes("test63_0.txt", test63_0, test63_0)
}
```

## Mac

```
$ ./chtimes 
test0_1 1970-01-01 01:00:00.000000001 +0100 CET
test0_2 1970-01-01 01:00:00.000000003 +0100 CET
test0_31 1970-01-01 01:00:02.147483647 +0100 CET
test0_32 1970-01-01 01:00:04.294967295 +0100 CET
test0_33 1970-01-01 01:00:08.589934591 +0100 CET
test0_62 2116-02-21 00:53:38.427387903 +0100 CET
test0_63 2262-04-12 00:47:16.854775807 +0100 CET
test31_0 2038-01-19 04:14:07 +0100 CET
test32_0 2106-02-07 07:28:15 +0100 CET
test33_0 2242-03-16 13:56:31 +0100 CET
test34_0 2514-05-30 02:53:03 +0100 CET
test35_0 3058-10-26 04:46:07 +0100 CET
test63_0 292277026596-12-04 16:30:07 +0100 CET
~/code/chtimes
$ ls -l
total 3808
-rwxr-xr-x  1 stefan  staff  1944592 Nov  2 23:56 chtimes
-rw-r--r--  1 stefan  staff     1790 Nov  2 23:56 chtimes.go
-rw-r--r--  1 stefan  staff        0 Jan  1  1970 test0_1.txt
-rw-r--r--  1 stefan  staff        0 Jan  1  1970 test0_2.txt
-rw-r--r--  1 stefan  staff        0 Jan  1  1970 test0_31.txt
-rw-r--r--  1 stefan  staff        0 Jan  1  1970 test0_32.txt
-rw-r--r--  1 stefan  staff        0 Jan  1  1970 test0_33.txt
-rw-r--r--  1 stefan  staff        0 Feb 21  2116 test0_62.txt
-rw-r--r--  1 stefan  staff        0 Sep 21  1677 test0_63.txt
-rw-r--r--  1 stefan  staff        0 Jan 19  2038 test31_0.txt
-rw-r--r--  1 stefan  staff        0 Feb  7  2106 test32_0.txt
-rw-r--r--  1 stefan  staff        0 Mar 16  2242 test33_0.txt
-rw-r--r--  1 stefan  staff        0 Nov  9  1929 test34_0.txt
-rw-r--r--  1 stefan  staff        0 Sep 16  1889 test35_0.txt
-rw-r--r--  1 stefan  staff        0 Jan  1  1970 test63_0.txt
```

## Raspberry Pi

```
root@c6fefe155c00:/code/chtimes# ./chtimes 
test0_1 1970-01-01 00:00:00.000000001 +0000 UTC
test0_2 1970-01-01 00:00:00.000000003 +0000 UTC
test0_31 1970-01-01 00:00:02.147483647 +0000 UTC
test0_32 1970-01-01 00:00:04.294967295 +0000 UTC
test0_33 1970-01-01 00:00:08.589934591 +0000 UTC
test0_62 2116-02-20 23:53:38.427387903 +0000 UTC
test0_63 2262-04-11 23:47:16.854775807 +0000 UTC
test31_0 2038-01-19 03:14:07 +0000 UTC
test32_0 2106-02-07 06:28:15 +0000 UTC
test33_0 2242-03-16 12:56:31 +0000 UTC
test34_0 2514-05-30 01:53:03 +0000 UTC
test35_0 3058-10-26 03:46:07 +0000 UTC
test63_0 219250468-12-04 15:30:07 +0000 UTC
root@c6fefe155c00:/code/chtimes# ls -l
total 1896
-rwxr-xr-x 1 root root 1937360 Nov  2 22:59 chtimes
-rw-r--r-- 1 root root    1790 Nov  2 22:59 chtimes.go
-rw-r--r-- 1 root root       0 Jan  1  1970 test0_1.txt
-rw-r--r-- 1 root root       0 Jan  1  1970 test0_2.txt
-rw-r--r-- 1 root root       0 Jan  1  1970 test0_31.txt
-rw-r--r-- 1 root root       0 Jan  1  1970 test0_32.txt
-rw-r--r-- 1 root root       0 Jan  1  1970 test0_33.txt
-rw-r--r-- 1 root root       0 Jan 14  1980 test0_62.txt
-rw-r--r-- 1 root root       0 Jan 27  1990 test0_63.txt
-rw-r--r-- 1 root root       0 Jan 19  2038 test31_0.txt
-rw-r--r-- 1 root root       0 Dec 31  1969 test32_0.txt
-rw-r--r-- 1 root root       0 Dec 31  1969 test33_0.txt
-rw-r--r-- 1 root root       0 Nov  2 22:59 test34_0.txt
-rw-r--r-- 1 root root       0 Nov  2 22:59 test35_0.txt
-rw-r--r-- 1 root root       0 Dec 31  1969 test63_0.txt
```

The underlying filesystem may truncate or round the values to a less precise time unit. If there is an error, it will be of type *PathError.

I don't have a solution but I think adding an own logic when to clip the atime and mtime doesn't really help here as it depens on platform/filesystem etc.

**Comment by darrenstahlmsft** [comment]
I did some testing too, and found that for some values outside the 64 bits of nanoseconds a *PathError is returned due to an invalid time.

It took some digging into the implementation of Chtimes, but it turns out that they use time.UnixNano, which is commented as "The result is undefined if the Unix time in nanoseconds cannot be represented by an int64". For this reason, I think that using 63 bits set (int64 max) on nanoseconds is the correct thing to do to limit the time on a 64 bit system. On a 32 system that uses a 32 bit Timespec, I think the correct thing to do is to limit to int32 max.

If we want to avoid this, we would need to implement a platform specific version of Chtimes instead of using Golang's. Or fix Golang...

What do you think?

**Comment by StefanScherer** [comment]
The max file timestamp I can produce on RPi and Scaleway is `time.Unix(1<<31-1, 0)` (Jan 19 2038) and on Linux 64bit machines you are right it is `time.Unix(0, 1<<63-1)` (Apr 11 2262) and on Mac I have to create it in a slightly different way with about `time.Parse("2006-Jan-02", "2262-Apr-11")`. That's with golang.

Thanks for digging into golang's Chtime. It seems that golang limits the Chtime on 64bit machine. Using `touch` you can produce later timestamps.

```
$ touch -t 350010161000 ./try
$ ls -l try
-rw-r--r-- 1 root root 0 Oct 16  3500 try
```

This doesn't work on 32bit ARM machines, the limit is also 2038.

**Comment by darrenstahlmsft** [comment]
@StefanScherer I'm not sure I understand what you mean by
> on Mac I have to create it in a slightly different way with about  time.Parse("2006-Jan-02", "2262-Apr-11") 

Does this mean that ```time.Unix(0, 1<<63-1)``` does not work on Mac? My latest PR is tested on 32 and 64 bit Linux/Windows, but I don't have a Mac. Can you clarify please?

**Comment by StefanScherer** [comment]
@darrenstahlmsft in the output shown above the timestamp`test0_63 := time.Unix(0, 1<<63-1)` changes the file timestamp on a Mac to

```
-rw-r--r--  1 stefan  staff        0 Sep 21  1677 test0_63.txt
```

shown with `ls -l`. Crazy as you can't create such a file timestamp with `touch`, but timestamps far in the future:

```
$ touch -t 167710161000 ./try
touch: out of range or illegal time specification: [[CC]YY]MMDDhhmm[.SS]
~/code/chtimes
$ touch -t 350010161000 ./try
~/code/chtimes
$ ls -l try
-rw-r--r--  1 stefan  staff  0 Oct 16  3500 try
```

We are running into strange edge cases with this.

I tried to reach the max file timestamp on a Mac and ended up with this test code:


```golang
$ cat chtimes.go 
package main

import (
	"fmt"
	"os"
	"time"
)

func Chtimes(name string, atime time.Time, mtime time.Time) error {
	f, err := os.Create(name)
	defer f.Close()
	if err != nil {
		return err
	}

	if err := os.Chtimes(name, atime, mtime); err != nil {
		return err
	}

	return nil
}

func main() {
	test0_62 := time.Unix(0, 1<<62-1)
	fmt.Println("test0_62", test0_62)
	Chtimes("test0_62.txt", test0_62, test0_62)

	test0_63 := time.Unix(0, 1<<63-1)
	fmt.Println("test0_63", test0_63)
	Chtimes("test0_63.txt", test0_63, test0_63)

	test0_63_1000 := time.Unix(0, 1<<63-1000)
	fmt.Println("test0_63_1000", test0_63_1000)
	Chtimes("test0_63_1000.txt", test0_63_1000, test0_63_1000)

	test0_63_999 := time.Unix(0, 1<<63-999)
	fmt.Println("test0_63_999", test0_63_999)
	Chtimes("test0_63_999.txt", test0_63_999, test0_63_999)

        t22620411, _ := time.Parse("2006-Jan-02", "2262-Apr-11")
	fmt.Println("t22620411", t22620411)
	Chtimes("t22620411.txt", t22620411, t22620411)

        t22620412, _ := time.Parse("2006-Jan-02", "2262-Apr-12")
	fmt.Println("t22620412", t22620412)
	Chtimes("t22620412.txt", t22620412, t22620412)
}
```

which creates these files:

```
$ ls -l *.txt
-rw-r--r--  1 stefan  staff  0 Apr 11  2262 t22620411.txt
-rw-r--r--  1 stefan  staff  0 Sep 21  1677 t22620412.txt
-rw-r--r--  1 stefan  staff  0 Feb 21  2116 test0_62.txt
-rw-r--r--  1 stefan  staff  0 Sep 21  1677 test0_63.txt
-rw-r--r--  1 stefan  staff  0 Apr 12  2262 test0_63_1000.txt
-rw-r--r--  1 stefan  staff  0 Sep 21  1677 test0_63_999.txt
```

So the maximum on a Mac is `time.Unix(0, 1<<63-1000)` at least with go1.4.2 installed.

**Comment by StefanScherer** [comment]
Another test in a vmwarefusion docker-machine on a Mac creates correct timestamps for all three files:

```
root@e7c782f29bb3:/code/chtimes# ls -l *.txt
-rw-r--r-- 1 501 dialout 0 Apr 11  2262 t22620411.txt
-rw-r--r-- 1 501 dialout 0 Nov  4 07:55 t22620412.txt
-rw-r--r-- 1 501 dialout 0 Feb 20  2116 test0_62.txt
-rw-r--r-- 1 501 dialout 0 Apr 11  2262 test0_63.txt
-rw-r--r-- 1 501 dialout 0 Apr 11  2262 test0_63_1000.txt
-rw-r--r-- 1 501 dialout 0 Apr 11  2262 test0_63_999.txt
```

and this is still on the Mac filesystem as I'm running a container with `docker run -it -v $(pwd):/code golang bash`to share the current dir with the docker-machine. Even on the Mac the timestamps look good:

```
$ ls -l *.txt
-rw-r--r--  1 stefan  staff  0 Apr 11  2262 t22620411.txt
-rw-r--r--  1 stefan  staff  0 Nov  4 08:55 t22620412.txt
-rw-r--r--  1 stefan  staff  0 Feb 21  2116 test0_62.txt
-rw-r--r--  1 stefan  staff  0 Apr 12  2262 test0_63.txt
-rw-r--r--  1 stefan  staff  0 Apr 12  2262 test0_63_1000.txt
-rw-r--r--  1 stefan  staff  0 Apr 12  2262 test0_63_999.txt
```

I've updated to go 1.5.1 on the Mac and run the test locally again, but still the timestamps differ:

```
 $ ls -l *.txt
-rw-r--r--  1 stefan  staff  0 Apr 11  2262 t22620411.txt
-rw-r--r--  1 stefan  staff  0 Sep 21  1677 t22620412.txt
-rw-r--r--  1 stefan  staff  0 Feb 21  2116 test0_62.txt
-rw-r--r--  1 stefan  staff  0 Sep 21  1677 test0_63.txt
-rw-r--r--  1 stefan  staff  0 Apr 12  2262 test0_63_1000.txt
-rw-r--r--  1 stefan  staff  0 Sep 21  1677 test0_63_999.txt
```

Very interesting exploring such edge cases, but which problem we try to solve with this unit test? :smile:

**Comment by darrenstahlmsft** [comment]
@StefanScherer The goal of this test was to ensure that Chtimes prevents timestamps that passed the maximum for the platform and either caused an exception, or wrapped around in time (and messed with any modified time based caching). I'm fine to rip the unit test out, since it will not likely manifest in anything until 2262. (Though I think the fix for 32 bit timespecs should be merged)

**Comment by StefanScherer** [comment]
@darrenstahlmsft In the meantime we managed to make all unit tests work on 32bit ARM and could send a PR. But I won't cry if the unit test is removed again. So feel free and decide what would be the best for this project.

**Comment by darrenstahlmsft** [comment]
I've removed the testing of the upper limits of time, since that seems to be too platform dependent for me to make this unit test reliable. This should fix 32 bit timespecs regardless though.

**Comment by StefanScherer** [comment]
@darrenstahlmsft I'll check it and give you feedback.

**Comment by StefanScherer** [comment]
@darrenstahlmsft This PR fixes the `make test-unit` on a Scaleway 32bit ARM server. Just tested it with the PR #17803 for initial ARM support.

LGTM

File: pkg/system/chtimes.go [hunk 2]
```diff
@@ -2,14 +2,23 @@ package system
...
 	"time"
+	"unsafe"
 )
 
 // Chtimes changes the access time and modified time of a file at the given path
 func Chtimes(name string, atime time.Time, mtime time.Time) error {
 	unixMinTime := time.Unix(0, 0)
-	// The max Unix time is 33 bits set
-	unixMaxTime := unixMinTime.Add((1<<33 - 1) * time.Second)
+	var unixMaxTime time.Time
```
Comment (LK4D4) [inline pkg/system/chtimes.go]: Looks like this can be moved to pkg-level and then reused in tests as well. WDYT?

**Comment by LK4D4** [comment]
design makes sense for me
ping @docker/core-maintainers

File: pkg/system/chtimes.go (hunk 2 above)
Comment (darrenstahlmsft) [inline pkg/system/chtimes.go]: Yeah, that makes sense. Will do.

File: pkg/system/chtimes.go [hunk 3]
```diff
@@ -2,14 +2,28 @@ package system
...
 import (
 	"os"
+	"syscall"
 	"time"
+	"unsafe"
 )
 
+// maxTime returns the maximum time that can be set by os.Chtimes on this platform
+// 64 bit Timespec supports up to 2262 and 32 bit Timespec supports up to 2038
+func maxTime() time.Time {
```
Comment (tiborvass) [inline pkg/system/chtimes.go]: @darrenstahlmsft would prefer to make this a var, set via `init()`.

Comment (darrenstahlmsft) [inline pkg/system/chtimes.go]: Ah, that is how to do that. I was wasn't sure if ```init()``` was the correct place for that or not. Will do.

File: pkg/system/chtimes.go [hunk 4]
```diff
@@ -2,14 +2,28 @@ package system
...
+
+	// This is a 32 bit timespec
+	return time.Unix(1<<31-1, 0)
+}
+
 // Chtimes changes the access time and modified time of a file at the given path
 func Chtimes(name string, atime time.Time, mtime time.Time) error {
 	unixMinTime := time.Unix(0, 0)
-	// The max Unix time is 33 bits set
-	unixMaxTime := unixMinTime.Add((1<<33 - 1) * time.Second)
```
Comment (tiborvass) [inline pkg/system/chtimes.go]: Any ideas why 33?

Comment (darrenstahlmsft) [inline pkg/system/chtimes.go]: I was on the edge of the undefined behavior caused by having more than int64 max nanoseconds when using ```.UnixNano()```. 33 bits of seconds resulted in just less than int64 max nanoseconds, and 34 bits of seconds overflowed.

It turns out that Golang's ```os.Chtimes()``` limits it to int64 max (63 bits) nanoseconds (instead of seconds) on 64 bit Timespecs and int32 max seconds on 32 bit Timespecs. This PR fixes my incorrect assumptions about maximum time values.

Comment (tiborvass) [inline pkg/system/chtimes.go]: thanks for clarifying

File: pkg/system/chtimes.go (hunk 3 above)
Comment (tiborvass) [inline pkg/system/chtimes.go]: Ping @darrenstahlmsft

**Comment by StefanScherer** [comment]
ping @darrenstahlmsft I had started a regression test with your latest commit 318ad1c and it works fine on ARM and helps to fix the last problem with `make test-unit` on ARM. Thanks!

**Comment by LK4D4** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Comment by StefanScherer** [comment]
Thanks. A regression test with `make test-unit` now works out of the box. Another step for #17802 ;-)

**Comment by DieterReuter** [comment]
Thanks guys, this helps us a lot to get the official ARM support realized in Docker upstream! :+1:
