### PR TITLE
not export errors and forbid leave without --force when unlocked

### LINKED ISSUE #29059: Easily docker swarm leave when swarm unlocked, unreasonable
**Description**

I found that when I use `--autolock` to init a swarm and restart dockerd, after the two steps, I can easily leave the swarm. This seems some kind unreasonable.

In my original thought, it is better to unlock the Swarm first, then allow admin to make this node leave swarm.

**Steps to reproduce the issue:**
1. `docker init --autolock`
2. `service docker restart`
3. `docker swarm leave`

**Describe the results you received:**
```
root@ubuntu:~/test# docker swarm leave
Node left the swarm.
```

**Describe the results you expected:**
```
root@ubuntu:~/test# docker swarm leave
Node has been locked. Please unlock it first.
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
root@ubuntu:~/test# docker version
Client:
 Version:      1.13.0-rc2
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   1f9b3ef
 Built:        Wed Nov 23 06:24:33 2016
 OS/Arch:      linux/amd64

Server:
 Version:             1.13.0-rc2
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          1f9b3ef
 Built:               Wed Nov 23 06:24:33 2016
 OS/Arch:             linux/amd64
 Experimental:        false
```

**Output of `docker info`:**

```
root@ubuntu:~/test# docker info
Containers: 14
 Running: 0
 Paused: 0
 Stopped: 14
Images: 52
Server Version: 1.13.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 329
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: ubuntu
ID: HRBI:EV6M:3NAC:CXZ3:BDS7:UOKL:PD6Y:ZCK4:V3PF:V7MR:CU2Y:3LGG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 14
 Goroutines: 26
 System Time: 2016-11-30T13:52:26.656821307+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by allencloud**
fixes https://github.com/docker/docker/issues/29059

This PR forbids `docker swarm leave` easily when swarm is locked. 

**- What I did**
1. leave when locked returns a specified error;
2. do not export errors in cluster.go

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

Signed-off-by: allencloud <allen.sun@daocloud.io>

### CODE REVIEW

File: daemon/cluster/cluster.go [hunk 1]
```diff
@@ -664,15 +664,14 @@ func (c *Cluster) Leave(force bool) error {
 	node := c.node
 	if node == nil {
 		if c.locked {
-			c.locked = false
-			c.lastNodeConfig = nil
 			c.Unlock()
-		} else if c.err == ErrSwarmCertificatesExpired {
+			return errSwarmLocked
```
Comment (allencloud) [inline daemon/cluster/cluster.go]: PS: Here is my key code for returning error locked.

Comment (allencloud) [inline daemon/cluster/cluster.go]: PS, here is my key code to return errSwarmLocked when leaving a locked swarm

**Comment by tonistiigi** [comment]
I don't think this would be the correct behavior. Leave is a local operation and means shutting node down and clearing state. You can do it when you have access to the node, doesn't matter if you know the key or not. Maybe should use `--force` but that would for completely different reasons. @cyli @diogomonica

**Comment by aaronlehmann** [comment]
We should probably require `--force` when the node is locked because we can't know if it's a situation where leaving would be dangerous (i.e. a single manager).

**Comment by tonistiigi** [comment]
@aaronlehmann We detect the single manager for running nodes only so this doesn't only apply to locking. If the node is down it is already out of raft consensus and removing it should not make raft more unstable.

**Comment by aaronlehmann** [comment]
I'm talking about this case:

```
# docker swarm init --autolock
<do stuff>
<restart daemon>
# docker swarm leave     # <-- data loss
```

**Comment by diogomonica** [comment]
Agreed with @aaronlehmann

**Comment by allencloud** [comment]
Thanks @tonistiigi @aaronlehmann @diogomonica 
My concern is that it may be not so  reasonable for user to leave a locked swarm. It is so casual that maybe data loss happens like @aaronlehmann mentions.

I agree that `--force` is a good choice , so I try to return an error like this:
`fmt.Errorf("Swarm is encrypted and locked. Leaving swarm without `--force` may cause data loss. Please unlock it first or use `--force` to ignore this message")`

PTAL

**Comment by aaronlehmann** [comment]
The `TestSwarmLeaveLocked` test is timing out.

File: daemon/cluster/cluster.go [hunk 2]
```diff
@@ -666,16 +666,22 @@ func (c *Cluster) Leave(force bool) error {
...
-			return ErrNoSwarm
+			return errNoSwarm
 		}
 	} else {
 		if node.Manager() != nil && !force {
+			if c.locked {
+				// when swarm manager is locked and Leave action is without --force
+				// return error to not allow action Leave
+				c.Unlock()
+				return fmt.Errorf("Swarm is encrypted and locked. Leaving swarm without `--force` may cause data loss. Please unlock it first or use `--force` to ignore this message")
```
Comment (aaronlehmann) [inline daemon/cluster/cluster.go]: Add a period at the end, after "message".

File: daemon/cluster/cluster.go [hunk 3]
```diff
@@ -666,16 +666,22 @@ func (c *Cluster) Leave(force bool) error {
 		if c.locked {
 			c.locked = false
 			c.lastNodeConfig = nil
-			c.Unlock()
```
Comment (allencloud) [inline daemon/cluster/cluster.go]: Oh, my mistake. Added it again.

File: daemon/cluster/cluster.go (hunk 2 above)
Comment (tonistiigi) [inline daemon/cluster/cluster.go]: This message is bit confusing. It seems to imply that there is no data loss if `--force` is used. I'd skip the `Leaving swarm without `--force` may cause data loss.` part.

Comment (allencloud) [inline daemon/cluster/cluster.go]: Thanks, my friends. Now added a period. And skip that `Leaving swarm without --force may cause data loss.` I feel a bit confused as well.

**Comment by allencloud** [comment]
Updated the PR, and PTAL @tonistiigi @aaronlehmann

**Comment by aaronlehmann** [comment]
LGTM

**Comment by tonistiigi** [comment]
@allencloud LGTM but needs rebase

**Comment by diogomonica** [comment]
LGTM

**Comment by allencloud** [comment]
rebased and updated, PTAL @tonistiigi @aaronlehmann

**Comment by cpuguy83** [comment]
2 LGTM's + LGTM after rebase.
Merging.
