### PR TITLE
Integration-cli: change daemon id generation from time to rand

### LINKED ISSUE #24805: Flaky test: DockerSwarmSuite.TestApiSwarmServicesStateReporting
Seen on power, but looks like a general test issue.
```sh
10:55:32 FAIL: docker_api_swarm_test.go:374: DockerSwarmSuite.TestApiSwarmServicesStateReporting
10:55:32 
10:55:32 [d68464000] waiting for daemon to start
10:55:32 [d68464000] daemon started
10:55:32 [d23430000] waiting for daemon to start
10:55:32 [d23430000] daemon started
10:55:32 docker_api_swarm_test.go:380:
10:55:32     d2 := s.AddDaemon(c, true, true)
10:55:32 check_test.go:221:
10:55:32     c.Assert(d.Join(swarm.JoinRequest{
10:55:32         RemoteAddrs: []string{s.daemons[0].listenAddr},
10:55:32         Manager:     manager}), check.IsNil)
10:55:32 ... value *errors.errorString = &errors.errorString{s:"joining swarm: invalid statuscode 406, \"{\\\"message\\\":\\\"This node is already part of a Swarm cluster. Use \\\\\\\"docker swarm leave\\\\\\\" to leave this cluster and join another one.\\\"}\\n\""} ("joining swarm: invalid statuscode 406, \"{\\\"message\\\":\\\"This node is already part of a Swarm cluster. Use \\\\\\\"docker swarm leave\\\\\\\" to leave this cluster and join another one.\\\"}\\n\"")
10:55:32 
10:55:32 [d68464000] exiting daemon
```

### PR DESCRIPTION
**Pull request by tophj-ibm**
Fixes #24805

Changes test daemon id generation from using time.Now().UnixNano() to using
crypto rand.Read(). This is because of a go bug (fixed upstream for 1.8)
on ppc64le and s390x where time.Now().UnixNano() would not actually
return nanosecond precision, so initializing consecutive daemons sometimes
would result in them having the same id.

Signed-off-by: Christopher Jones tophj@linux.vnet.ibm.com

ping @tonistiigi 

time dog

### CODE REVIEW

File: integration-cli/daemon.go [hunk 1]
```diff
@@ -61,7 +63,11 @@ func NewDaemon(c *check.C) *Daemon {
 	err := os.MkdirAll(daemonSockRoot, 0700)
 	c.Assert(err, checker.IsNil, check.Commentf("could not create daemon socket root"))
 
-	id := fmt.Sprintf("d%d", time.Now().UnixNano()%100000000)
+	randomBytes := make([]byte, 8)
+	_, err = rand.Read(randomBytes)
+	c.Assert(err, checker.IsNil, check.Commentf("could not read bytes in daemon id generation"))
+	id := fmt.Sprintf("d%d", binary.BigEndian.Uint64(randomBytes)%100000000)
```
Comment (tonistiigi) [inline integration-cli/daemon.go]: nit: just `hex.EncodeToString()` would be simpler here. I don't think there is any reason this should be a number. It's even bad atm when finding the logs because the IDs have different lengths.

Comment (cpuguy83) [inline integration-cli/daemon.go]: Why not use stringid?

Comment (tophj-ibm) [inline integration-cli/daemon.go]: Didn't know about stringId, but that looks like it should do exactly what I want

**Comment by tophj-ibm** [comment]
updated to use the shortID from stringid. The ID is now 13 characters long as opposed to 9 characters long, but I didn't see where that should matter.

**Comment by tonistiigi** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM
