### PR TITLE
 Reload daemon even if "/etc/docker/daemon.json" does not exist

### LINKED ISSUE #35114: Daemon config reloading fails and recovers without config file
**Description**

When one sends `SIGHUP` to `dockerd` and the daemon's config file (usually `/etc/docker/daemon.json`) does not exist, an error is emitted to the logs and the reload does not occur.

**Steps to reproduce the issue:**
1. Start `dockerd` without a config file (config 0)
2. Create `/etc/docker/daemon.json` and populate it with some new configuration
3. Send `SIGHUP` to `dockerd` and notice the new configuration is picked up (config 1)
4. Delete `/etc/docker/daemon.json`
5. Send `SIGHUP` to `dockerd` and notice that the configuration does not change (config 1)

**Describe the results you received:**

Missing config file is allowed when starting daemon but not when reloading configuration.

**Describe the results you expected:**

Missing config file is allowed when starting daemon and when reloading configuration.

Edit: occurs in Docker 17.06, Docker 17.09, etc.

### PR DESCRIPTION
**Pull request by boaz0**
**- What I did**

closes #35114

Before this commit if `--config-file` wasn't set the daemon would use the default configuration file which is `/etc/docker/daemon.json`.

When attempting to reload the daemon if that file didn't exist and error message would display.

This behaviour is changed in a way that if the default configuration file does not exist, the daemon will use an empty configuration which later will be reloaded using the `reload` function given as an
argument in `Reload`.

However, if the `--config-file` flag was set and the file was removed or renamed an error message
will be displayed and no reload will be done.

**- How I did it**

* Add a check when `err != nil` in the `Reload` function.
* Add unit tests in `daemon/config/config_test.go`

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: daemon/config/config.go [hunk 1]
```diff
@@ -244,7 +245,10 @@ func Reload(configFile string, flags *pflag.FlagSet, reload func(*Config)) error
 	logrus.Infof("Got signal to reload configuration, reloading from: %s", configFile)
 	newConfig, err := getConflictFreeConfiguration(configFile, flags)
 	if err != nil {
-		return err
+		if flags.Changed("config-file") || !os.IsNotExist(err) {
+			return fmt.Errorf("unable to configure the Docker daemon with file %s: %v", configFile, err)
+		}
+		return nil
```
Comment (dsheets) [inline daemon/config/config.go]: If a config file is not specified and does not exist, I believe the configuration should still be reloaded. It looks like this simply returns success in this case without reloading the configuration (i.e. resetting whatever used to be in the config that has now been deleted, ensuring flags are obeyed, etc).

Comment (ripcurld0) [reply daemon/config/config.go]: Hey @dsheets ,
Thank you for the review but I probably miss something. 😕 
If `/etc/docker/daemon.json` (which is the default configuration file) doesn't exist or was removed, then there are no changes available, so what is needed to be reloaded.

😀

Comment (dsheets) [reply daemon/config/config.go]: From #35114:

1. Start `dockerd` without a config file (config 0)
2. Create `/etc/docker/daemon.json` and populate it with some new configuration
3. Send `SIGHUP` to `dockerd` and notice the new configuration is picked up (config 1)
4. Delete `/etc/docker/daemon.json`
5. Send `SIGHUP` to `dockerd` and notice that the configuration does not change (config 1)

I believe this reproduction will have the same behavior with your patch. In particular, step 4 changes the configuration by removing the configuration file and, after step 5, the configuration should revert to "config 0" as was used in step 1.

Comment (ripcurld0) [reply daemon/config/config.go]: Oh I got it. There should be a default configuration if the `/etc/docker/daemon.json` doesn't exist and no other configuration file was given.
Right?

Comment (dsheets) [reply daemon/config/config.go]: Yes, that's correct.

Comment (ripcurld0) [reply daemon/config/config.go]: Thanks! I am going to work on this change.

Comment (thaJeztah) [reply daemon/config/config.go]: Yes, we should probably have something like;

- start daemon
- create `daemon.json` and reload
- check the configuration was updated
- remove `daemon.json` and reload
- check the configuration was reverted to the original settings

One interesting bit would be; what should happen to settings that are not live-reloadable but were present in the `daemon.json`? (perhaps we already take those into account)

Comment (dsheets) [reply daemon/config/config.go]: I believe that fields that are not reloadable are simply ignored. See <https://github.com/moby/moby/blob/master/daemon/reload.go#L13>.

**Comment by crosbymichael** [comment]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!
