### PR TITLE
Revert "Temporarily disable CAP_PERFMON, CAP_BPF, and CAP_CHECKPOINT_RESTORE

### LINKED ISSUE #42601: Unable to create containers with CAP_PERFMON/CAP_BPF/CAP_CHECKPOINT_RESTORE
Hello,
When I'm trying to start a new container with added capability of perfmon/bpf/checkpoint_restore I'm getting an "unknown capability" error even tho it says in the docker 20.10 [release notes](https://docs.docker.com/engine/release-notes/#runtime-2) that it should be supported.

Steps to reproduce the issue:
 docker run --rm --cap-add perfmon nginx bash

The output:
docker: Error response from daemon: invalid CapAdd: unknown capability: "CAP_PERFMON".

Running on: ```Linux ubuntu 5.11.0, Ubuntu 20.10```

docker version:
```
Client: Docker Engine - Community
 Version:           20.10.4
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        d3cb89e
 Built:             Thu Feb 25 07:05:39 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:53 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Thanks!

### PR DESCRIPTION
**Pull request by thaJeztah**
fixes https://github.com/moby/moby/issues/42601

## Revert "Temporarily disable CAP_PERFMON, CAP_BPF, and CAP_CHECKPOINT_RESTORE"

Now that runc v1.0.0-rc93 is used, we can revert this temporary workaround

This reverts commit a38b96b8cdc4d345a050b417c4c492b75329e5a6 (https://github.com/moby/moby/pull/41563).

relates to:

- https://github.com/moby/moby/issues/41562 [20.10 beta] Unknown capability "CAP_PERFMON" on Linux 5.8.14
- https://github.com/kubernetes-sigs/kind/issues/2058 [master] kube-proxy doesn't start up due to "apply caps: operation not permitted" error
- https://github.com/opencontainers/runtime-spec/issues/1071 

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: oci/caps/utils.go [hunk 1]
```diff
@@ -16,18 +16,6 @@ func init() {
...
-		// capabilities on privileged (or CAP_ALL) containers on Kernel 5.8 and up.
-		// While these kernels support these capabilities, the current release of
-		// runc ships with an older version of /gocapability/capability, and does
-		// not know about them, causing an error to be produced.
-		//
-		// FIXME remove once https://github.com/opencontainers/runc/commit/6dfbe9b80707b1ca188255e8def15263348e0f9a
-		//       is included in a runc release and once we stop supporting containerd 1.3.x
-		//       (which ships with runc v1.0.0-rc92)
-		last = capability.CAP_AUDIT_READ
-	}
```
Comment (AkihiroSuda) [inline oci/caps/utils.go:30]: This will break dind (Docker 21 in Docker 20.10). I still think https://github.com/containerd/containerd/pull/5017 is the right approach.

**Comment by AkihiroSuda** [comment]
What's current status?

File: oci/caps/utils.go (hunk 1 above)
Comment (AkihiroSuda) [reply oci/caps/utils.go:30]: (Might be fine for runc >= rc94, though, as runc >= rc94 does not raise error on unknown caps https://github.com/opencontainers/runc/pull/2854)

**Comment by thaJeztah** [comment]
> What's current status?

I rebased to trigger CI again. I think this one should be fine now that we're on runc > rc94, correct?

**Comment by thaJeztah** [comment]
Failure is unrelated; `TestCreateParallel ` tracked through https://github.com/moby/moby/issues/42582

```

[2021-07-19T08:35:11.641Z] === Failed
[2021-07-19T08:35:11.641Z] === FAIL: libnetwork/drivers/bridge TestCreateParallel (0.73s)
[2021-07-19T08:35:11.641Z] time="2021-07-19T08:32:14Z" level=warning msg="bridge store not initialized. kv object docker/network/v1.0/bridge/net87/ is not added to the store"
[2021-07-19T08:35:11.641Z] time="2021-07-19T08:32:15Z" level=warning msg="bridge store not initialized. kv object docker/network/v1.0/bridge/net51/ is not added to the store"
[2021-07-19T08:35:11.641Z]     bridge_test.go:1133: Success should be 1 instead: 2
```

**Comment by thaJeztah** [comment]
hmpf

```
RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: the remote end hung up unexpectedly
fatal: early EOF
``

**Comment by thaJeztah** [comment]
@AkihiroSuda @cpuguy83 PTAL

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Failure is unrelated, but looks like that one is flaky as well

```
 === FAIL: libnetwork/networkdb TestNetworkDBNodeJoinLeaveIteration (5.81s)
[2021-07-29T18:12:43.071Z]     networkdb_test.go:511: Network existence verification failed
[2021-07-29T18:12:43.071Z]     networkdb_test.go:513: The networkNodes list has to have be 2 instead of 1 - [8518394491d6]
```

**Comment by thaJeztah** [comment]
Opened https://github.com/moby/moby/issues/42698 to track that one

**Review by justincormack — APPROVED** [review]

**Comment by mqasimsarfraz** [comment]
@thaJeztah @cpuguy83 any thoughts on [above](https://github.com/moby/moby/pull/42011#issuecomment-1245460005)?

**Comment by ymanton** [comment]
CRIU has merged patches to use CAP_CHECKPOINT_RESTORE in https://github.com/checkpoint-restore/criu/pull/1930. This allows us to build images containing checkpointed processes that can be restored in containers with far fewer privileges and capabilities. The benefits here are much faster startup and reduced time to first response.

Podman and others support it, so it would really be nice to have Docker support in stable releases finally.
