### PR TITLE
builder-next/prune: Handle `until` filter timestamps

### LINKED ISSUE #40253: timestamps don't work in docker system prune's 'until' filter
I found this issue(https://github.com/docker/cli/issues/2071) in the cli repository but tracked the source of the issue here. I'm just going to copy/paste the original issue description as its still relevant. 

> **Description**
> 
> The [documentation for `docker system prune` on 19.03](https://docs.docker.com/engine/reference/commandline/system_prune/) states that the `until` filter supports timestamps, but it doesn't work.
> 
> **Steps to reproduce the issue:**
> 
>     1. Run `docker system prune --force --all --filter "until=2006-01-02T15:04:05"`
> 
> 
> **Describe the results you received:**
> 
> ```
> Error response from daemon: failed to prune build cache: "until" filter expects a duration (e.g., '24h'): time: unknown unit - in duration 2006-01-02T15:04:05
> ```
> 
> **Describe the results you expected:**
> The prune to work with the timestamp.
> 
> **Output of `docker version`:**
> 
> ```
> Client: Docker Engine - Community
>  Version:           19.03.1
>  API version:       1.40
>  Go version:        go1.12.5
>  Git commit:        74b1e89
>  Built:             Thu Jul 25 21:22:03 2019
>  OS/Arch:           linux/amd64
>  Experimental:      false
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          19.03.1
>   API version:      1.40 (minimum version 1.12)
>   Go version:       go1.12.5
>   Git commit:       74b1e89
>   Built:            Thu Jul 25 21:20:35 2019
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.2.6
>   GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
>  runc:
>   Version:          1.0.0-rc8
>   GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
>  docker-init:
>   Version:          0.18.0
>   GitCommit:        fec3683
> ```
> 
> **Output of `docker info`:**
> 
> ```
> Client:
>  Debug Mode: false
> 
> Server:
>  Containers: 42
>   Running: 0
>   Paused: 0
>   Stopped: 42
>  Images: 144
>  Server Version: 19.03.1
>  Storage Driver: aufs
>   Root Dir: /var/lib/docker/aufs
>   Backing Filesystem: extfs
>   Dirs: 611
>   Dirperm1 Supported: true
>  Logging Driver: json-file
>  Cgroup Driver: cgroupfs
>  Plugins:
>   Volume: local
>   Network: bridge host ipvlan macvlan null overlay
>   Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
>  Swarm: inactive
>  Runtimes: runc
>  Default Runtime: runc
>  Init Binary: docker-init
>  containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
>  runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
>  init version: fec3683
>  Security Options:
>   apparmor
>   seccomp
>    Profile: default
>  Kernel Version: 4.19.0-5-amd64
>  Operating System: Debian GNU/Linux 10 (buster)
>  OSType: linux
>  Architecture: x86_64
>  CPUs: 12
>  Total Memory: 15.62GiB
>  Name: server123
>  ID: ZSS4:GQ3D:IWCX:FTWI:WBPU:7X4W:AMW7:6JWJ:ISPK:PSBG:HZXH:J6MU
>  Docker Root Dir: /var/lib/docker
>  Debug Mode: false
>  Registry: https://index.docker.io/v1/
>  Labels:
>  Experimental: false
>  Insecure Registries:
>   127.0.0.0/8
>  Live Restore Enabled: false
> 
> WARNING: the aufs storage-driver is deprecated, and will be removed in a future release.
> ```

### PR DESCRIPTION
**Pull request by vvoland**
- Fixes: https://github.com/moby/moby/issues/40253
- supersedes https://github.com/moby/moby/pull/40254

Fixes `docker system prune --filter until=<timestamp>`.
`docker system prune` claims to support "until" filter for timestamps, but it doesn't work because builder "until" filter only supports duration.
Use the same filter parsing logic and then convert the timestamp to a relative "keep-duration" supported by buildkit.

Also, fixed untyped errors returned when filter isn't a valid value:
```
DEBU[2023-04-07T11:27:28.111736050Z] FIXME: Got an API for which error does not match any expected type!!!: parsing time "202dfsfddf3-04-08" as "2006-01-02": cannot parse "202dfsfddf3-04-08" as "2006"  error_type="*time.ParseError" module=api
ERRO[2023-04-07T11:27:28.111806259Z] Handler for POST /v1.41/containers/prune returned error: parsing time "202dfsfddf3-04-08" as "2006-01-02": cannot parse "202dfsfddf3-04-08" as "2006"
```

**- How to verify it**
<details>
<summary>Spoiler</summary>

```bash
# Before
$ docker system prune --filter until=2023-04-07
WARNING! This will remove:
  - all stopped containers
  - all networks not used by at least one container
  - all dangling images
  - all dangling build cache

  Items to be pruned will be filtered with:
  - until=2023-04-07

Are you sure you want to continue? [y/N] y
Error response from daemon: failed to prune build cache: "until" filter expects a duration (e.g., '24h'): time: unknown unit "-" in duration "2023-04-07"

# After
$ echo 'FROM alpine' | docker buildx build -q -t asdf -
sha256:c41833b44d910632b415cd89a9cdaa4d62c9725dc56c99a7ddadafd6719960f9

$ docker rmi asdf
Untagged: asdf:latest
Deleted: sha256:13fdf3c19db4214ef2013388e22461ec089d6c8fd6d1c84fe8ba31680aff19b0

# prune until start of today (excluding last build)
$ docker system prune --filter until=2023-04-07
WARNING! This will remove:
  - all stopped containers
  - all networks not used by at least one container
  - all dangling images
  - all dangling build cache

  Items to be pruned will be filtered with:
  - until=2023-04-07

Are you sure you want to continue? [y/N] y
Total reclaimed space: 0B

# prune until next day (including last build)
$ docker system prune --filter until=2023-04-08
WARNING! This will remove:
  - all stopped containers
  - all networks not used by at least one container
  - all dangling images
  - all dangling build cache

  Items to be pruned will be filtered with:
  - until=2023-04-08

Are you sure you want to continue? [y/N] y
Deleted build cache objects:
np1jrw1al2rfmu6cmr7tsnbbh
o0cl7w0jcsruz9dnwkr2epf9l
4wtlnw56cddubj3tqka67o4z2

Total reclaimed space: 12B
```

</details>

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**
dudubox

### CODE REVIEW

File: builder/builder-next/builder.go [hunk 1]
```diff
@@ -14,6 +14,7 @@ import (
 	"github.com/containerd/containerd/remotes/docker"
 	"github.com/docker/docker/api/types"
 	"github.com/docker/docker/api/types/backend"
+	apitime "github.com/docker/docker/api/types/time"
```
Comment (thaJeztah) [inline builder/builder-next/builder.go:17]: can you use `timetypes` for this one? Looks like that's currently the alias we use everywhere.

**Review by thaJeztah — APPROVED** [review]
LGTM after updating the import alias 😅

**Comment by thaJeztah** [comment]
Oh, perhaps you can update the swagger to mention the new accepted options;
https://github.com/moby/moby/blob/5b1282c708df9ec164f2d0897d469df9a93ab142/api/swagger.yaml#L8232

and update it with the same description as `containers/prune`;
https://github.com/moby/moby/blob/5b1282c708df9ec164f2d0897d469df9a93ab142/api/swagger.yaml#L7952

File: builder/builder-next/builder.go (hunk 1 above)
Comment (vvoland) [reply builder/builder-next/builder.go]: Ah yes, I remember I wanted to check how this package is aliased in other places but forgot 🙈 
Fixed, thanks!

File: api/swagger.yaml [hunk 2]
```diff
@@ -8229,7 +8229,7 @@ paths:
 
             Available filters:
 
-            - `until=<duration>`: duration relative to daemon's time, during which build cache was not used, in Go's duration format (e.g., '24h')
+            - `until=<timestamp>` Prune build cache which wasn't used before this timestamp. The `<timestamp>` can be Unix timestamps, date formatted timestamps, or Go duration strings (e.g. `10m`, `1h30m`) computed relative to the daemon machine’s time.
```
Comment (thaJeztah) [inline api/swagger.yaml:8232]: Need to have a closer look, but the description is a bit confusing; it's removing cache "older than" `until`, right?

Comment (vvoland) [reply api/swagger.yaml:8232]: Yes, all cache that was last used before the `until` time is deleted.

Comment (thaJeztah) [reply api/swagger.yaml:8232]: @dvdksn do you have good suggestions for the description? (I'm failing to come up with a good one right now 😓 😅)

Comment (tianon) [reply api/swagger.yaml:8232]: Something like "remove all cache older than `<timestamp>`" (with the existing note description of format for `<timestamp>`)?

File: api/swagger.yaml [hunk 3]
```diff
@@ -8226,7 +8226,7 @@ paths:
 
             Available filters:
 
-            - `until=<duration>`: duration relative to daemon's time, during which build cache was not used, in Go's duration format (e.g., '24h')
+            - `until=<timestamp>` remove cache older than `<timestamp>`. The `<timestamp>` can be Unix timestamps, date formatted timestamps, or Go duration strings (e.g. `10m`, `1h30m`) computed relative to the daemon machine’s time.
```
Comment (corhere) [inline api/swagger.yaml:8229]:
```suggestion
            - `until=<timestamp>` remove cache older than `<timestamp>`. The `<timestamp>` can be Unix timestamps, date formatted timestamps, or Go duration strings (e.g. `10m`, `1h30m`) computed relative to the daemon's local time.
```

File: builder/builder-next/builder.go [hunk 4]
```diff
@@ -53,6 +54,14 @@ func (e errConflictFilter) Error() string {
 
 func (errConflictFilter) InvalidParameter() {}
 
+type errInvalidFilterValue struct {
+	err error
+}
+
+func (e errInvalidFilterValue) Error() string { return e.err.Error() }
```
Comment (corhere) [inline builder/builder-next/builder.go:61]: ⛳ 
```suggestion
	error
}
```

**Review by corhere — APPROVED** [review]

**Comment by tianon** [comment]
```console
#23 69.66 # github.com/docker/docker/builder/builder-next
#23 69.66 builder/builder-next/builder.go:639:5: unknown field err in struct literal of type errInvalidFilterValue
#23 69.66 builder/builder-next/builder.go:645:5: unknown field err in struct literal of type errInvalidFilterValue
```

:eyes: (related to @corhere's suggestion, I think?)

File: api/swagger.yaml (hunk 2 above)
Comment (dvdksn) [reply api/swagger.yaml]: "Remove cache older than" sgtm!

I guess we could update container/prune to use the same language (remove instead of prune, in the description)

**Review by thaJeztah — APPROVED** [review]
LGTM
