### PR TITLE
Choose default-cgroup parent by cgroup driver

### LINKED ISSUE #19140: Systemd cgroups don't work
```
docker run -it --rm busybox
docker: Error response from daemon: Cannot start container 7de93d77778179628252cc4fd58b8559ed675fc7a8e1f448a888acf3179e1154: [9] System error: Invalid unit name '/docker'.
```
I have systemd-228 and kernel 4.3.3

### PR DESCRIPTION
**Pull request by LK4D4**
It's "/docker" for cgroupfs and "system.slice" for systemd.

Fix #19140

### CODE REVIEW

**Comment by mrunalp** [comment]
:+1:

**Comment by mrunalp** [comment]
I think this is cleaner as we process the parent at a higher level.

**Comment by calavera** [comment]
LGTM

File: daemon/execdriver/native/template/default_template_linux.go [hunk 1]
```diff
@@ -40,7 +37,8 @@ func New() *configs.Config {
 			{Type: "NEWUSER"},
 		}),
 		Cgroups: &configs.Cgroup{
-			Parent: "/docker",
+			Parent:      "/docker",
```
Comment (hqhq) [inline daemon/execdriver/native/template/default_template_linux.go]: Maybe there is no point we set it to "/docker" here anymore, since we will always override it, and it feels wired to set `Parent=/docker` and `ScopePrefix=docker` in the same time and same place, because they will never work together.
What about just set `Parent: ""` here?

And one more comment need to be fixed:
```
diff --git a/daemon/execdriver/driver_unix.go b/daemon/execdriver/driver_unix.go
index eedd8ac..b2a3d30 100644
--- a/daemon/execdriver/driver_unix.go
+++ b/daemon/execdriver/driver_unix.go
@@ -150,7 +150,7 @@ func InitContainer(c *Command) *configs.Config {
        // check to see if we are running in ramdisk to disable pivot root
        container.NoPivotRoot = os.Getenv("DOCKER_RAMDISK") != ""

-       // Default parent cgroup is "docker". Override if required.
+       // Override it if required.
        if c.CgroupParent != "" {
                container.Cgroups.Parent = c.CgroupParent
        }
```

**Comment by hqhq** [comment]
One minor tip in the comment, otherwise looks good.

**Comment by dqminh** [comment]
LGTM

File: daemon/execdriver/native/template/default_template_linux.go (hunk 1 above)
Comment (LK4D4) [inline daemon/execdriver/native/template/default_template_linux.go]: Yup, thanks!

File: daemon/container_operations_unix.go [hunk 2]
```diff
@@ -241,6 +242,20 @@ func (daemon *Daemon) populateCommand(c *container.Container, env []string) erro
 	}
 	uidMap, gidMap := daemon.GetUIDGIDMaps()
 
+	defaultCgroupParent := "/docker"
+	if daemon.configStore.CgroupParent != "" {
+		defaultCgroupParent = daemon.configStore.CgroupParent
+	} else {
+		for _, option := range daemon.configStore.ExecOptions {
+			key, val, err := parsers.ParseKeyValueOpt(option)
+			if err != nil || key != "native.cgroupdriver" {
```
Comment (anusha-ragunathan) [inline daemon/container_operations_unix.go]: It's better to perform case in-sensitive compare here like in NewDriver().

**Comment by LK4D4** [comment]
@anusha-ragunathan Fixed!

**Comment by anusha-ragunathan** [comment]
LGTM!

**Comment by thaJeztah** [comment]
docs LGTM (feel free to merge if code is good, docs will still be enhanced separately)

**Comment by jfrazelle** [comment]
LGTM
