### PR TITLE
info: unset cgroup-related fields when CgroupDriver == none

### LINKED ISSUE #42151: info: MemoryLimit, CPUShares, PIdsLimit, ..., should be shown as `false` when CgroupDriver == none (i.e. rootless cgroup v1)
**Description**

`docker info --format {{ json . }}`  should not show `MemoryLimit`, `CPUShares`, `PidsLimit` to be true when `CgroupDriver` is `none` (i.e. rootless cgroup v1)

**Steps to reproduce the issue:**
1. Boot the host with cgroup v1
2. `dockerd-rootless-setuptool.sh install`
3. `docker info --format {{ json. }}`

**Describe the results you received:**
```json
{
...
  "MemoryLimit": true,
  "SwapLimit": true,
  "KernelMemory": true,
  "KernelMemoryTCP": true,
  "CpuCfsPeriod": true,
  "CpuCfsQuota": true,
  "CPUShares": true,
  "CPUSet": true,
  "PidsLimit": true,
...
  "CgroupDriver": "none",
...
}
```

**Describe the results you expected:**
These should be false

**Output of `docker version`:**

```
Client:
 Version:           20.10.0-dev
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        d3c36a2a7
 Built:             Mon Mar 15 04:15:07 2021
 OS/Arch:           linux/amd64
 Context:           rootless
 Experimental:      true

Server:
 Engine:
  Version:          dev
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4735a0c84f
  Built:            Mon Mar 15 04:13:59 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.5.0-beta.3-62-gecb881e5e
  GitCommit:        ecb881e5e6e3ea77721865c5bb1d61725579fd54
 runc:
  Version:          1.0.0-rc93+dev
  GitCommit:        249bca0a1316129dcd5bd38b5d75572274181cb5
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    rootless
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-45-gc9f02c3)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: dev
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: none
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ecb881e5e6e3ea77721865c5bb1d61725579fd54
 runc version: 249bca0a1316129dcd5bd38b5d75572274181cb5
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  rootless
 Kernel Version: 5.11.0-051100-generic
 Operating System: Ubuntu 20.10
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.6GiB
 Name: suda-ws01
 ID: CWVR:KJQU:3CNT:IJF7:FMME:22Y7:GKFW:AFKJ:IVLQ:JOVW:3KZY:S25M
 Docker Root Dir: /home/suda/.local/share/docker
 Debug Mode: false
 Username: akihirosuda
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: Running in rootless-mode without cgroups. To enable cgroups in rootless-mode, you need to boot the system in cgroup v2 mode.
```

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Fix #42151 

**- What I did**
unset cgroup-related fields when CgroupDriver == none

**- How I did it**
Modified `daemon/info_unix.goP

**- How to verify it**

- Boot the host with cgroup v1
- `dockerd-rootless-setuptool.sh install`
- `docker info --format {{ json. }}`

```json
{
...
  "MemoryLimit": false,
  "SwapLimit": false,
  "KernelMemory": false,
  "KernelMemoryTCP": false,
  "CpuCfsPeriod": false,
  "CpuCfsQuota": false,
  "CPUShares": false,
  "CPUSet": false,
  "PidsLimit": false,
...
  "CgroupDriver": "none",
...
}
```

**- Description for the changelog**

info: unset cgroup-related fields when CgroupDriver == none

**- A picture of a cute animal (not mandatory but encouraged)**

:penguin:

### CODE REVIEW

File: daemon/info_unix.go [hunk 1]
```diff
@@ -25,16 +25,18 @@ func (daemon *Daemon) fillPlatformInfo(v *types.Info, sysInfo *sysinfo.SysInfo)
...
-	v.KernelMemory = sysInfo.KernelMemory
-	v.KernelMemoryTCP = sysInfo.KernelMemoryTCP
-	v.OomKillDisable = sysInfo.OomKillDisable
-	v.CPUCfsPeriod = sysInfo.CPUCfs
-	v.CPUCfsQuota = sysInfo.CPUCfs
-	v.CPUShares = sysInfo.CPUShares
-	v.CPUSet = sysInfo.Cpuset
-	v.PidsLimit = sysInfo.PidsLimit
+	if v.CgroupDriver != cgroupNoneDriver {
+		v.MemoryLimit = sysInfo.MemoryLimit
```
Comment (thaJeztah) [inline daemon/info_unix.go:29]: Why does `sysInfo` return `true`? Shouldn't the fix be done there if it's returning incorrect info?

Comment (thaJeztah) [reply daemon/info_unix.go:29]: @AkihiroSuda ^^

Comment (AkihiroSuda) [reply daemon/info_unix.go:29]: Because `sysInfo` is not aware of the cgroup driver.

We could modify (in a separate PR) `sysInfo` to return true only when we can grant write permission, the value needs to be negated to false when `v.CgroupDriver==cgroupNoneDriver`.

**Review by thaJeztah — APPROVED** [review]
LGTM

but left a comment on tracking the follow-up

**Review by tianon — APPROVED** [review]
