### PR TITLE
Fix container mount cleanup issues

### LINKED ISSUE #21618: [1.11-rc2] odd evalSymlinksInScope warning
I see this message on daemon start/stop and it seems quite odd, like something isn't working as it should.

    WARN[0005] 520ad5f2af7b7032a26f26870d982d3015c603dd06bc414d151e5a8bd9594553 cleanup: Failed to umount volumes: evalSymlinksInScope: /lib/modules is not in /home/darren 

The folder `/lib/modules` is from a container that is launched with `-v /lib/modules:/lib/modules` and `/home/darren` is the current working directory of the Docker daemon.  Why would it be evaluating this?

### PR DESCRIPTION
**Pull request by tonistiigi**
- Refactor generic and path based cleanup functions into a single function.
- Include aufs and zfs mounts in the mounts cleanup.
- Containers that receive exit event on restore don't require manual cleanup
- Make "missing sandbox id" message a warning because currently sandboxes are always cleared on startup. libnetwork#975
- Don't unmount volumes for containers that don't have base path. Shouldn't be needed after #21372

fixes #21618

@mlaventure 

Signed-off-by: Tonis Tiigi tonistiigi@gmail.com

### CODE REVIEW

**Comment by mlaventure** [comment]
Looks good.

**Comment by calavera** [comment]
LGTM

File: daemon/daemon_linux.go [hunk 1]
```diff
@@ -28,91 +28,52 @@ func (daemon *Daemon) cleanupMountsFromReaderByID(reader io.Reader, id string, u
...
-		return err
-	}
-
-	if len(errors) > 0 {
-		return fmt.Errorf("Error cleaningup mounts:\n%v", strings.Join(errors, "\n"))
-	}
-
-	logrus.Debugf("Cleaning up old container shm/mqueue/rootfs mounts: done.")
-	return nil
+	return
```
Comment (aaronlehmann) [inline daemon/daemon_linux.go]: Having an array of printf format strings scares me a little. Printf is easy enough to screw up normally, but with the patterns defined separately, static analysis tools like `go vet` won't be able to check for the right number of and type of arguments.

I think we could do this imperatively without complicating the code:

```go
var patterns []string
if id == "" {
	id = "[0-9a-f]{64}"
	patterns = append(patterns, "containers/"+id+"/shm")
}
patterns = append(patterns, "aufs/mnt/"+id+"$", "overlay/"+id+"/merged$", "zfs/graph/"+id+"$")
for _, p := range patterns {
	r, err := regexp.Compile(p)
	if err == nil {
		regexps = append(regexps, r)
	}
}
```

File: daemon/daemon_linux.go [hunk 2]
```diff
@@ -28,91 +28,52 @@ func (daemon *Daemon) cleanupMountsFromReaderByID(reader io.Reader, id string, u
...
-			mnt := fields[4]
-			if strings.HasSuffix(mnt, shmSuffix) || strings.HasSuffix(mnt, mergedSuffix) {
-				logrus.Debugf("Unmounting %v", mnt)
-				if err := unmount(mnt); err != nil {
-					logrus.Error(err)
-					errors = append(errors, err.Error())
+		if fields := strings.Fields(sc.Text()); len(fields) >= 4 {
+			if mnt := fields[4]; strings.HasPrefix(mnt, daemon.root) {
+				for _, p := range regexps {
+					if p.Match([]byte(mnt)) {
```
Comment (aaronlehmann) [inline daemon/daemon_linux.go]: Use `p.MatchString`?

Comment (calavera) [inline daemon/daemon_linux.go]: agreed

**Comment by tonistiigi** [comment]
@aaronlehmann PTAL

**Comment by aaronlehmann** [comment]
LGTM

**Comment by thaJeztah** [comment]
Looks like build is failing; https://jenkins.dockerproject.org/job/Docker-PRs-gccgo/4020/console

```
23:57:20 # github.com/docker/docker/daemon
23:57:20 daemon/daemon_linux_test.go:62:3: error: reference to undefined field or method 'cleanupMountsFromReader'
23:57:20   d.cleanupMountsFromReader(strings.NewReader(mountsFixture), unmount)
23:57:20    ^
23:57:20 daemon/daemon_linux_test.go:100:3: error: reference to undefined field or method 'cleanupMountsFromReader'
23:57:20   d.cleanupMountsFromReader(strings.NewReader(mountInfo), unmount)
23:57:20    ^
23:57:20 FAIL	github.com/docker/docker/daemon [build failed]
```

**Comment by thaJeztah** [comment]
all green, and two LGTM's, merging
