### PR TITLE
do not turn post-processing on for linux-cgo terminals

### LINKED ISSUE #15373: regression terminal drawing on 1.7.1
Description of problem:

Garbled emacs displayed when running inside a docker container (using -t -i) with multiple panes (windows). The corruption is fixed after resizing the terminal (or pressing ctrl+l). The bug was introduced with 1.7.0 and persists into 1.7.1. 

I should add that this makes emacs and possibly other console based applications unusable.

Broken (checked 1.7.0 and 1.7.1)
broken

Good (checked 1.3.2 and 1.6.2)
good

`docker version`:
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64

`docker info`:
Containers: 1
Images: 247
Storage Driver: devicemapper
 Pool Name: docker-254:3-12587682-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 66.91 GB
 Data Space Total: 107.4 GB
 Data Space Available: 40.46 GB
 Metadata Space Used: 52.62 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.095 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.102 (2015-07-07)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.3-1-ARCH
Operating System: Arch Linux
CPUs: 8
Total Memory: 62.86 GiB
ID: XEB2:FX7X:USNE:7ZIE:X44P:NL2F:XS7B:MWY2:MOIF:VJ4C:2A6R:GXZL
Registry: https://index.docker.io/v1/

`uname -a`:
Linux  4.1.3-1-ARCH #1 SMP PREEMPT Wed Jul 22 20:37:12 CEST 2015 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
physical

How reproducible:
100%

Steps to Reproduce:
1. have ubuntu 04.14 container with emacs installed (emacs version does not matter)
2. run bash inside container with "-t -i"
3. start emacs
4. open new vertical pane: C-x 3
corruption happens
5. press Ctrl+l
corruption resolves

Actual Results:
Corruption

Expected Results:
No Corruption

Additional info:

### PR DESCRIPTION
**Pull request by MHBauer**
- fixes #15373
-  #20043 is dup with similar problem

essentially undoes 05a8de46853f8b3534ca6d0cb03121ae214e8a34. The code that was printing messages does not seem to exist anymore. I don't see any debug output at all.

@cpuguy83 @LK4D4 @icecrime @estesp @coolljt0725 y'all looked at the previous change.

### CODE REVIEW

**Comment by coolljt0725** [comment]
This change LGTM, after some searching, I agree we should not set `post-processing` for raw terminal, it would cause unexpected behavior, sorry for didn't realize this at that time.

But we should also fix the problem describe in the previous change, those messages missing, but there  may be other debug messages add in future. After some debuging, I think this can be fixed in  `holdHijackedConnection`, I'm working on a PR

**Comment by jhowardmsft** [comment]
Not clear if this win2lin failure is real or transient: Restarting it anyway.

```
19:25:13 ----------------------------------------------------------------------
19:25:13 FAIL: docker_cli_run_test.go:3910: DockerSuite.TestRunNonExistingCmd
19:25:13 
19:25:13 docker_cli_run_test.go:3916:
19:25:13     c.Fatalf("Run non-existing command should have errored with exit code 127, but we got exit: %d, State.ExitCode: %s", exit, stateExitCode)
19:25:13 ... Error: Run non-existing command should have errored with exit code 127, but we got exit: 125, State.ExitCode: -1 cantstart: Cannot start container 01a32c166eb8b968592f8350b180d1339e1c4cef64195350f399c29627a1c601: [10] System error: invalid character 'b' looking for beginning of value
19:25:13 
19:25:13 
19:25:14 
19:25:14 ----------------------------------------------------------------------
```

File: pkg/term/term.go [hunk 1]
```diff
@@ -127,6 +127,7 @@ func handleInterrupt(fd uintptr, state *State) {
 	go func() {
 		_ = <-sigchan
 		RestoreTerminal(fd, state)
+		// why is this here?
```
Comment (calavera) [inline pkg/term/term.go]: this is historic code that probably doesn't belong here anymore.

**Comment by calavera** [comment]
it sounds reasonable.

LGTM

File: pkg/term/term.go (hunk 1 above)
Comment (MHBauer) [inline pkg/term/term.go]: Forgot I left that in there. Should I nuke the exit? I don't think it's a problem that we restore the terminal twice.

Comment (calavera) [inline pkg/term/term.go]: go for it!

**Comment by tiborvass** [comment]
LGTM
