### PR TITLE
Fix parsing of user/group during copy operation

### LINKED ISSUE #12467: [BUG] Watch can't copy host file to container when user: "1000:1000" (UID:GID format) was used
### Description

Docs says: `user: Username or UID (format: <name|uid>[:<group|gid>])`
But when use `user: "1000:1000"` (full format with GID) directive in service, for node.js for example, `docker compose watch` can't do a sync.

```
app-1  | 
app-1  | > docker compose up -w@0.0.1 start
app-1  | > node src/server.js
app-1  | 
app-1  | Server started
        ⦿ Watch enabled
        ⦿ Syncing service "app" after 1 changes were detected
WARN[0034] Error handling changed files for service app: 1 error occurred:
        * copying files to d0cd914abc7d54b63c4f131f12ff104e8b3d3ec6ec9041a44ea9bbe2cceffc7b: 
        * Error response from daemon: getent unable to find entry "1000:1000" in passwd databasetch
```

But when `user:` directive is disabled, or short format used (`user: "1000"`), copying works fine.

### Steps To Reproduce

Use a simple repo to reproduce a bug [test-docker-compose-watch-bug](https://github.com/baboo35/test-docker-compose-watch-bug)

### Compose Version

```Text
Docker Compose version v2.30.3 (or 2.32 in 2nd case)
```

### Docker Environment

```Text
Client:
 Version:    27.4.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.18.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.30.3
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 5
  Running: 2
  Paused: 0
  Stopped: 3
 Images: 7
 Server Version: 27.4.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 88bf19b2105c8b17560993bee28a01ddc2f97182
 runc version: 
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-51-generic
 Operating System: Ubuntu Core 22
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.768GiB
 Name: notebook
 ID: deccbf28-7b36-44e2-8f67-5240cfa211cd
 Docker Root Dir: /var/snap/docker/common/var-lib-docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

I've tested this bug on kde neon desktop (docker compose installed through snapd edge channel) and on ubuntu server 22.04 (fresh upgraded), both tries to get the Watch to work was failed. Error message dive me onto the learn about getent from passwd. And of course `getent passwd "1000:1000"` has no effect, while `getent passwd "1000"` returns correct answer. That's why `user: "1000"` works fine:
```
docker compose exec -it app getent passwd "1000"
node:x:1000:1000:Linux User,,,:/home/node:/bin/sh
```

But, `user: "1000:1000:` is correct format by documentation. And this is good format, when we speak about copying files from container to host (correct GID on files as result).

Maybe to handle value of user before to get it to getent function? Trim it through colon, for example, if colon exists.

### LINKED ISSUE #34142: docker cp looks up user on the host instead of in container
While looking at https://github.com/moby/moby/pull/34099, I noticed that the `cp` command looks up the container's user from the _host_, not from inside the container;

Note that this example is done on docker 17.06.0, which has the `-a` option "flipped"

To reproduce;

Prepare; create a directory, and a file to copy to the container;

```bash
mkdir cp-bug && cd cp-bug
echo "foobar" > test-file.txt
```

Build an image, containing a user/group `bar`/`bar` with `uid/gid` `2020`;

```bash
docker build -t cp-bug -<<EOF
FROM busybox
RUN addgroup -g 2020 bar && adduser -D -u 2020 -G bar bar 
EOF
```

Create a container, using `--user bar`, and copy the file into the container;

```bash
docker create --name showit --user bar cp-bug ls -lan /
docker cp -a test-file.txt showit:/
```

An error is printed;

```
Error response from daemon: getent unable to find entry "bar" in passwd database
```

Now, create a "bar/bar" user/group **on the host**, with `uid/gid` `1010`;

```bash
echo "bar:x:1010:1010:Foo Bar,,,:/home/bar:/bin/sh" >> /etc/passwd
echo "bar:x:1010:" >> /etc/group
```

Create another container, copy the file, and view the file permissions;

```bash
docker create --name showit2 --user bar cp-bug ls -lan /
docker cp -a test-file.txt showit2:/
docker start showit2 && docker logs showit2

# cleanup
docker stop showit2 && docker rm showit2
```

```
total 48
drwxr-xr-x   20 0        0             4096 Jul 17 16:56 .
drwxr-xr-x   20 0        0             4096 Jul 17 16:56 ..
-rwxr-xr-x    1 0        0                0 Jul 17 16:56 .dockerenv
drwxr-xr-x    2 0        0            12288 Jun 15 00:40 bin
drwxr-xr-x    5 0        0              340 Jul 17 16:56 dev
drwxr-xr-x    2 0        0             4096 Jul 17 16:56 etc
drwxr-xr-x    3 65534    65534         4096 Jul 17 16:46 home
dr-xr-xr-x  140 0        0                0 Jul 17 16:56 proc
drwxr-xr-x    2 0        0             4096 Jun 15 00:40 root
dr-xr-xr-x   13 0        0                0 Jul 17 16:56 sys
-rw-r--r--    1 1010     1010             7 Jul 17 16:46 test-file.txt
drwxrwxrwt    2 0        0             4096 Jun 15 00:40 tmp
drwxr-xr-x    3 0        0             4096 Jun 15 00:40 usr
drwxr-xr-x    4 0        0             4096 Jun 15 00:40 var
```

No error is printed, and the `uid` / `gid` of the _host_ is used inside the container (`uid/gid` `1010` instead of `2020`)

ping @erikh @jlhawn PTAL

FWIW, there's other issues in this functionality that I was looking into (I'll probably open separate issues for those);

- `docker cp` is only able to parse `--user <username>`, not `<username>:<groupname>`
- `docker cp` does not work with `--user <uid>:<gid>` (numeric values), as it always attempts to lookup the user

### LINKED ISSUE #49213: Adding GID to Dockerfile breaks Docker compose watch functionality
### Description

If a Dockerfile uses the `USER` keyword with both a UID and GID like `0:0`, Config.User gets set to `0:0`.  If using watch to update files, the file update then fails with `getent unable to find entry "0:0" in passwd database`.  This is presumably because it tries to look up the user using getent with `0:0` which doesn't match any records.

This could presumably be fixed by either populating Config.User with the UID alone, or having the watch functionality extract the UID and use that to look up the user.  I'm unsure which is more appropriate.

### Reproduce

1. create these files (I'd attach them, but .yaml and .sh files are prohibited):
=== Dockerfile ===
FROM alpine

COPY --chown=0:0 files .

USER 0

CMD [ "sh", "start.sh" ]
=== docker-compose.yaml ===
services:
  gidtest:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: files
          target: /
=== files/start.sh ===
#!/bin/sh

last=0

while true; do
	cur=`stat -c %Y test`

	if test $cur -ne $last
	then
		ls -l test
		last=$cur
		sleep 5
	fi
done
=== files/test ===
foo

2. docker compose up
3. Click "w" to enable watch
4. edit files/test
5. Receive error response from daemon

### Expected behavior

The updated file should be propagated into the container without errors

### docker version

```bash
Client:
 Version:           27.4.0
 API version:       1.47
 Go version:        go1.22.10
 Git commit:        bde2b89
 Built:             Sat Dec  7 10:35:43 2024
 OS/Arch:           darwin/amd64
 Context:           desktop-linux

Server: Docker Desktop 4.37.1 (178610)
 Engine:
  Version:          27.4.0
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.10
  Git commit:       92a8393
  Built:            Sat Dec  7 10:38:57 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.21
  GitCommit:        472731909fa34bd7bc9c087e4c27943f9835f111
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    27.4.0
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  ai: Ask Gordon - Docker Agent (Docker Inc.)
    Version:  v0.5.1
    Path:     /Users/johnrehwinkel/.docker/cli-plugins/docker-ai
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.19.2-desktop.1
    Path:     /Users/johnrehwinkel/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.31.0-desktop.2
    Path:     /Users/johnrehwinkel/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.37
    Path:     /Users/johnrehwinkel/.docker/cli-plugins/docker-debug
  desktop: Docker Desktop commands (Beta) (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/johnrehwinkel/.docker/cli-plugins/docker-desktop
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /Users/johnrehwinkel/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.27
    Path:     /Users/johnrehwinkel/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     /Users/johnrehwinkel/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.4.0
    Path:     /Users/johnrehwinkel/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/johnrehwinkel/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.15.1
    Path:     /Users/johnrehwinkel/.docker/cli-plugins/docker-scout

Server:
 Containers: 8
  Running: 7
  Paused: 0
  Stopped: 1
 Images: 104
 Server Version: 27.4.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 CDI spec directories:
  /etc/cdi
  /var/run/cdi
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 472731909fa34bd7bc9c087e4c27943f9835f111
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.10.14-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 7.655GiB
 Name: docker-desktop
 ID: 3f67f719-e4e8-4817-801b-c6e5537164b5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///Users/johnrehwinkel/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by thaJeztah**
relates to 

- https://github.com/moby/moby/pull/34099
- fixes https://github.com/moby/moby/issues/34142
- fixes https://github.com/moby/moby/issues/49213
- fixes https://github.com/docker/compose/issues/12467
- relates to https://github.com/moby/moby/pull/28923

If a container was started with

- a numeric uid
- both a user and group (username:groupname)
- uid and gid (uid:gid)

The copy action failed, because the "username:groupname"
was looked up using getent.

This patch;

- splits `user` and `group` before looking up
- if numeric `uid` or `gid` is used and lookup fails,
  the `uid` / `gid` is used as-is

### CODE REVIEW

File: daemon/archive_tarcopyoptions_unix.go [hunk 1]
```diff
@@ -12,14 +16,77 @@ func (daemon *Daemon) tarCopyOptions(container *container.Container, noOverwrite
...
 	}, nil
 }
+
+// getUIDGID resolves the UID and GID of a given user and, optionally, group.
+//
+// usergrp is a username or uid, and optional group, in the format `user[:group]`.
+// Both `user` and `group` can be provided as an `uid` / `gid`, so the following
+// formats are supported:
+//
+//   username            - valid username from /etc/passwd
```
Comment (AkihiroSuda) [inline daemon/archive_tarcopyoptions_unix.go]: /etc/passwd -> getent(1)?

Comment (thaJeztah) [inline daemon/archive_tarcopyoptions_unix.go]: ah, yes, perhaps I should change that; I started writing for this PR, but found https://github.com/moby/moby/blob/c8a2596d676a815cc17162f178869be4aeb4b301/daemon/daemon_unix.go#L941-L951, so copied parts from that

I'm not sure what approach should be taken though if the user needs to come from within the container (where `getent` may not be available, such as in a `busybox` container) - that's why I kept it as "WIP"

Comment (thaJeztah) [inline daemon/archive_tarcopyoptions_unix.go]: updated 👍

**Comment by aaronlehmann** [comment]
@AkihiroSuda, does this look good now?

**Comment by AkihiroSuda** [comment]
getent - > typically getent? (Sorry for going back and forth)

**Comment by AkihiroSuda** [comment]
Is this still WIP?

**Comment by thaJeztah** [comment]
let me remove "WIP", code itself should be generally ok (not sure how to test this, without the test becoming dependent on the host)

I think I made this `WIP` because it only resolves the parsing issue, and not the fact that this looks up the user/group from the host (https://github.com/moby/moby/issues/34142). 


> getent - > typically getent? (Sorry for going back and forth)

Oh, can you be more specific; happy to update but wasn't sure what you meant / where you wanted to have that updated 😄

File: daemon/archive.go [hunk 2]
```diff
@@ -277,7 +277,7 @@ func (daemon *Daemon) containerExtractToDir(container *container.Container, path
 
 	options := daemon.defaultTarCopyOptions(noOverwriteDirNonDir)
 
-	if copyUIDGID {
+	if !copyUIDGID {
```
Comment (thaJeztah) [inline daemon/archive.go]: oh, need to remove this one as that's part of https://github.com/moby/moby/pull/34099, so don't merge as-is

Comment (thaJeztah) [inline daemon/archive.go]: removed

**Comment by runcom** [comment]
any update on this?

**Comment by olljanat** [comment]
@thaJeztah this one needs to be rebased

**Comment by olljanat** [comment]
Derek add label: status/failing-ci

**Review by tonistiigi — APPROVED** [review]

**Comment by olljanat** [comment]
Derek add label: rebuild/*

**Comment by thaJeztah** [comment]
rebased to trigger CI again for a fresh run

**Review by cpuguy83 — DISMISSED** [review]
LGTM

**Review by cpuguy83 — DISMISSED** [review]
Can you write an integration test for these cases?

File: daemon/archive_tarcopyoptions_unix.go [hunk 3]
```diff
@@ -14,15 +18,73 @@ func (daemon *Daemon) tarCopyOptions(container *container.Container, noOverwrite
 		return daemon.defaultTarCopyOptions(noOverwriteDirNonDir), nil
 	}
 
-	user, err := idtools.LookupUser(container.Config.User)
+	uid, gid, err := getUIDGID(container.Config.User)
```
Comment (corhere) [inline daemon/archive_tarcopyoptions_unix.go:21]: UID and GID should be resolved from within the container if we want to fix #34142. There's already a function which parses a user[:group] string and resolves it to UID/GID inside the container: [`getUser`](https://github.com/moby/moby/blob/83b51522df43866e39f7c757a6ab84ef4050eeb3/daemon/oci_linux.go#L184-L212). It does delegate to libcontainer/user, though. There's also the [`WithUser`](https://pkg.go.dev/github.com/containerd/containerd/oci#WithUser) function in containerd, though it would be a bit awkward to use here.

File: daemon/archive_tarcopyoptions_unix.go [hunk 4]
```diff
@@ -3,25 +3,133 @@
...
+		groupID, groupName = getIDOrName(groupNameOrID)
+	)
+	if userName == "" && hasGroup && groupName == "" {
+		// UID/GID passed; nothing to look up.
+		return userID, groupID, nil
+	}
+
+	usr, err := lookupUser(ctr, userNameOrID)
+	if err != nil {
+		return 0, 0, errors.Wrapf(err, "failed to look up user %q in container: %w", userNameOrID)
```
Comment (thaJeztah) [inline daemon/archive_tarcopyoptions_unix.go:64]: Ah, forgot to remove the `%w` when I swapped to errors.Wrapf;

```
daemon/archive_tarcopyoptions_unix.go:64:16: github.com/docker/docker/vendor/github.com/pkg/errors.Wrapf format %w reads arg #2, but call has 1 arg
daemon/archive_tarcopyoptions_unix.go:73:16: github.com/docker/docker/vendor/github.com/pkg/errors.Wrapf format %w reads arg #2, but call has 1 arg
```

File: daemon/archive_tarcopyoptions_unix.go [hunk 5]
```diff
@@ -3,25 +3,133 @@
...
+		if userName != "" {
+			return entry.Name == userName
+		}
+		return entry.Uid == userID
+	})
+	if err != nil {
+		return user.User{}, err
+	}
+	if len(users) == 0 {
+		return user.User{}, errors.New("no group found")
```
Comment (vvoland) [inline daemon/archive_tarcopyoptions_unix.go:106]:
```suggestion
		return user.User{}, errors.New("no user found")
```

**Review by vvoland — APPROVED** [review]

File: daemon/archive_tarcopyoptions_unix.go (hunk 5 above)
Comment (thaJeztah) [reply daemon/archive_tarcopyoptions_unix.go]: Ah, thanks! Fixed; also rebased

**Comment by thaJeztah** [comment]
Hm... something weird happening, and I need to figure out what's causing this; lookup won't work currently, because it can't find the file in the container's rootFs,  but when reading it, it ... is there?

```bash
docker run -dit --network=none --name foo --user=mail:users busybox
a15916812f63745ca5e0cf8d504525d8b8e6b44bd585974460bd9e580d6e1318

docker cp -a foo.txt foo:/tmp/
Successfully copied 1.54kB to foo:/tmp/
Error response from daemon: failed to look up user "mail" in container: open /var/lib/docker/overlay2/36d730a67b0897ee7afd31c9d333208442fe4d947e4449ee6c72b756618fb49b/merged/etc/passwd: no such file or directory

cat /var/lib/docker/overlay2/36d730a67b0897ee7afd31c9d333208442fe4d947e4449ee6c72b756618fb49b/merged/etc/passwd
root:x:0:0:root:/root:/bin/sh
daemon:x:1:1:daemon:/usr/sbin:/bin/false
bin:x:2:2:bin:/bin:/bin/false
sys:x:3:3:sys:/dev:/bin/false
sync:x:4:100:sync:/bin:/bin/sync
mail:x:8:8:mail:/var/spool/mail:/bin/false
www-data:x:33:33:www-data:/var/www:/bin/false
operator:x:37:37:Operator:/var:/bin/false
nobody:x:65534:65534:nobody:/home:/bin/false
```

**Comment by thaJeztah** [comment]
DOH!!!

So... half of these changes is no longer needed. Or even _MOST_ of these. Because the code was rewritten elsewhere to now  properly execute within the container's filesystem; https://github.com/moby/moby/blob/033f97519cded22411eb279a6866be12dd8c8745/daemon/archive_unix.go#L100-L110

So all the "lookup resource path" is no longer needed  🙈

**Review by vvoland — APPROVED** [review]

**Comment by thaJeztah** [comment]
Let me  bring  this one in; thx!
