### PR TITLE
Fix setting swaplimit=true without checking memory.swap.max

### LINKED ISSUE #41926: [cgroup2] docker info: `SwapLimit = true` is set without checking
**Description**

https://github.com/moby/moby/blob/v20.10.2/pkg/sysinfo/cgroup2_linux.go#L69-L84

`info.SwapLimit = true` should be set only if `memory.swap.max` exists.

When the swap support is present (with `swapaccount=1` in kernel cmdline), `memory.swap.max` appears in a non-top cgroup.
i.e., `/sys/fs/cgroup/${dockerd_cgroup}/memory.swap.max` appears, but `/sys/fs/cgroup/memory.swap.max` does not appear (unless we are in dind)

Related: https://github.com/containers/podman/pull/8197/files

** `docker version` **
20.10.2

### PR DESCRIPTION
**Pull request by jmguzik**
**- What I did**
fixes #41926

**- How I did it**
Added one condition to moby/pkg/sysinfo/cgroup2_linux.go 

**- How to verify it**
Actually, I wanted to create unit tests for this one. The problem is certain files must be present on FS, so I see 2 solutions:
1) use mocks (of os.Stat for example)
2) since part of the path is passed as an argument, choose a different dir for tests (eg /tmp?)

I do not know what is the common practice in the project (1st PR), so I decided just to simply open a PR and ask.

**- Description for the changelog**

Fixes setting swaplimit=true without checking memory.swap.max

**- A picture of a cute animal (not mandatory but encouraged)**
Another time :)

### CODE REVIEW

**Comment by jmguzik** [comment]
cc @AkihiroSuda as issue author

File: pkg/sysinfo/cgroup2_linux.go [hunk 1]
```diff
@@ -66,15 +67,20 @@ func newV2(quiet bool, opts *opts) *SysInfo {
 	return sysInfo
 }
 
-func applyMemoryCgroupInfoV2(info *SysInfo, controllers map[string]struct{}, _ string) []string {
+func applyMemoryCgroupInfoV2(info *SysInfo, controllers map[string]struct{}, dirPath string) []string {
```
Comment (AkihiroSuda) [inline pkg/sysinfo/cgroup2_linux.go:70]: dirPath can be like "/sys/fs/cgroup", but we need to check the existence of `/sys/fs/cgroup/${dockerd_cgroup}/memory.swap.max`, not `/sys/fs/cgroup/memory.swap.max`, because `/sys/fs/cgroup/memory.swap.max never appears.

**Review by AkihiroSuda — CHANGES_REQUESTED** [review]
Please see the comment

File: pkg/sysinfo/cgroup2_linux.go (hunk 1 above)
Comment (jmguzik) [reply pkg/sysinfo/cgroup2_linux.go:70]: You are right, I missed that. I changed the logic a little bit but inside the function.

File: pkg/sysinfo/cgroup2_linux.go [hunk 2]
```diff
@@ -66,15 +67,22 @@ func newV2(quiet bool, opts *opts) *SysInfo {
...
 	var warnings []string
 	if _, ok := controllers["memory"]; !ok {
 		warnings = append(warnings, "Unable to find memory controller")
 		return warnings
 	}
 
+	info.SwapLimit = false
+	if "/sys/fs/cgroup" != path.Clean(dirPath) {
```
Comment (jmguzik) [inline pkg/sysinfo/cgroup2_linux.go:78]: Actually, if `/sys/fs/cgroup/memory.swap.max` never appears, this check right now could be that `path.Join(dirPath, "memory.swap.max")` exists, without checking that we are in the group. Let me know what you think

Comment (AkihiroSuda) [reply pkg/sysinfo/cgroup2_linux.go:78]: This does not work when dirPath == /sys/fs/cgroup

Comment (jmguzik) [reply pkg/sysinfo/cgroup2_linux.go:78]: Right now if /sys/fs/cgroup then it is assumed upper function did not deliver /sys/fs/cgroup/${dockerd_cgroup}/ and info.SwapLimit = false defaults to false. Is that wrong?

File: pkg/sysinfo/cgroup2_linux.go (hunk 1 above)
Comment (jmguzik) [reply pkg/sysinfo/cgroup2_linux.go:70]: Is there a possibility that `/sys/fs/cgroup/memory.swap.max` will appear? If yes, is it then relevant to check for this use-case?

Comment (AkihiroSuda) [reply pkg/sysinfo/cgroup2_linux.go:70]: > Is there a possibility that /sys/fs/cgroup/memory.swap.max will appear? 

Yes `/sys/fs/cgroup/memory.swap.max` can appear when the daemon is running inside a cgroup namespace (i.e., dind), but we never need to check `/sys/fs/cgroup/memory.swap.max`

File: pkg/sysinfo/cgroup2_linux.go (hunk 2 above)
Comment (AkihiroSuda) [reply pkg/sysinfo/cgroup2_linux.go:78]: The caller never pass "/sys/fs/cgroup/${dockerd_cgroup}". (See `git grep WithCgroup2GroupPath`).

So we need to detect the cgroup of the daemon by ourselves, regardless to the value of `dirPath`.

Comment (jmguzik) [reply pkg/sysinfo/cgroup2_linux.go:78]: > The caller never pass "/sys/fs/cgroup/${dockerd_cgroup}". (See git grep WithCgroup2GroupPath).

Sorry, I thought `g` in the caller is the added part that will complement the path with the group. 
Sysinfo can be used in a package that does not belong to dockerd, so /proc/self/cgroup is not the option here, am I right?

Comment (AkihiroSuda) [reply pkg/sysinfo/cgroup2_linux.go:78]: I think we can safely use /proc/self/cgroup here

File: pkg/sysinfo/cgroup2_linux.go [hunk 3]
```diff
@@ -66,6 +69,29 @@ func newV2(quiet bool, opts *opts) *SysInfo {
 	return sysInfo
 }
 
+func getSwapLimit() bool {
```
Comment (jmguzik) [inline pkg/sysinfo/cgroup2_linux.go:72]: @AkihiroSuda I hope this one is better now. I have tested the logic over several distros and it seems to be working. Let me know what you think.

File: pkg/sysinfo/cgroup2_linux.go [hunk 4]
```diff
@@ -66,6 +69,29 @@ func newV2(quiet bool, opts *opts) *SysInfo {
...
+		return false
+	}
+
+	g, found := groups[""]
+	if !found {
+		return false
+	}
+
+	g = path.Clean(g)
+	if g == "." || g == "/" {
```
Comment (AkihiroSuda) [inline pkg/sysinfo/cgroup2_linux.go:84]: - How can g be "."?
- When g is "/", we are in a cgroup namespace, so we should check /sys/fs/cgroup/memory.swap.max

**Review by AkihiroSuda — CHANGES_REQUESTED** [review]
Thanks, but we need to support dind case (g="/", in a cgroup namespace)

File: pkg/sysinfo/cgroup2_linux.go [hunk 5]
```diff
@@ -74,7 +100,7 @@ func applyMemoryCgroupInfoV2(info *SysInfo, controllers map[string]struct{}, _ s
 	}
 
 	info.MemoryLimit = true
-	info.SwapLimit = true
+	info.SwapLimit = getSwapLimit()
```
Comment (AkihiroSuda) [inline pkg/sysinfo/cgroup2_linux.go:103]: nit: function name should be like getSwapLimitV2()

File: pkg/sysinfo/cgroup2_linux.go (hunk 4 above)
Comment (jmguzik) [reply pkg/sysinfo/cgroup2_linux.go:84]: - If g is empty, clean colapses it to ".". I understand empty would be some kind of a bug, so collapsing to "." should be treated as a bug
- Regarding second comment, wasn't sure. I will remove that one.

Comment (jmguzik) [reply pkg/sysinfo/cgroup2_linux.go:84]: To make things more visible I could first check if g == "" and then do a Clean. I think "" is the only case when Clean collapses to "."

**Review by AkihiroSuda — APPROVED** [review]
LGTM, thanks

**Comment by jmguzik** [comment]
I feel ci problems are not related to this issue, but anyway, rebase?

**Comment by thaJeztah** [comment]
restarted CI

File: pkg/sysinfo/cgroup2_linux.go [hunk 6]
```diff
@@ -66,6 +69,25 @@ func newV2(quiet bool, opts *opts) *SysInfo {
...
+		return false
+	}
+
+	g := groups[""]
+	if g == "" {
+		return false
+	}
+
+	g = path.Clean(g)
+	cGroupPath := filepath.Join("/sys/fs/cgroup", g, "memory.swap.max")
```
Comment (thaJeztah) [inline pkg/sysinfo/cgroup2_linux.go:84]: Given that this is linux-only, this should probably use `path.Join()` instead of `filepath.Join()` (also prevents the extra import being added

File: pkg/sysinfo/cgroup2_linux.go [hunk 7]
```diff
@@ -66,6 +69,25 @@ func newV2(quiet bool, opts *opts) *SysInfo {
...
+	if err != nil {
+		return false
+	}
+
+	g := groups[""]
+	if g == "" {
+		return false
+	}
+
+	g = path.Clean(g)
```
Comment (thaJeztah) [inline pkg/sysinfo/cgroup2_linux.go:83]: was the extra `path.Clean()` needed here?

from the docs; https://golang.org/pkg/path/#Join

> Join joins any number of path elements into a single path, separating them with slashes. Empty elements are ignored. **The result is Cleaned.**

File: pkg/sysinfo/cgroup2_linux.go [hunk 8]
```diff
@@ -66,6 +69,25 @@ func newV2(quiet bool, opts *opts) *SysInfo {
 	return sysInfo
 }
 
+func getSwapLimitV2() bool {
+	groups, err := cgroups.ParseCgroupFile("/proc/self/cgroup")
```
Comment (thaJeztah) [inline pkg/sysinfo/cgroup2_linux.go:73]: @AkihiroSuda I'm a bit confused why we need to use libcontainer cgroups here; does containerd cgroups not provide this info? We're already passing that one here;  https://github.com/moby/moby/blob/46cdcd206c56172b95ba5c77b827a722dab426c5/pkg/sysinfo/cgroup2_linux.go#L24

(if it doesn't provide this info, should we fix that there?

**Review by thaJeztah — CHANGES_REQUESTED** [review]

File: pkg/sysinfo/cgroup2_linux.go (hunk 7 above)
Comment (jmguzik) [reply pkg/sysinfo/cgroup2_linux.go:83]: Maybe it is not needed. I can remove this one.

File: pkg/sysinfo/cgroup2_linux.go (hunk 6 above)
Comment (jmguzik) [reply pkg/sysinfo/cgroup2_linux.go:84]: ok

File: pkg/sysinfo/cgroup2_linux.go (hunk 8 above)
Comment (jmguzik) [reply pkg/sysinfo/cgroup2_linux.go:72]: > The caller never pass "/sys/fs/cgroup/${dockerd_cgroup}". (See `git grep WithCgroup2GroupPath`).
> 
> So we need to detect the cgroup of the daemon by ourselves, regardless to the value of `dirPath`.

Quote from resolved conversations

**Comment by jmguzik** [comment]
@thaJeztah @AkihiroSuda how the situation looks like with this change? CI failures are unrelated.

**Review by AkihiroSuda — APPROVED** [review]

**Comment by AkihiroSuda** [comment]
@thaJeztah PTAL?

**Comment by AkihiroSuda** [comment]
ping @thaJeztah @tiborvass @cpuguy83

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by AkihiroSuda** [comment]
s390x failures are unrelated.
Merging.
https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-42071/16/tests

**Comment by AkihiroSuda** [comment]
CI seems to have to be green 😞 

@thaJeztah Can we relax "Merging is blocked" feature?

**Comment by AkihiroSuda** [comment]
@jmguzik Could you rebase? It will perhaps make Ci green.

**Comment by thaJeztah** [comment]
I kicked CI

Failures:

`TestConcurrencyNoWait` tracked by https://github.com/moby/moby/issues/42458

```
=== RUN   TestConcurrencyNoWait
--- FAIL: TestConcurrencyNoWait (0.13s)
    iptables_test.go:217:  (iptables failed: iptables -t nat -A DOCKEREST -p tcp -d 192.168.1.1 --dport 1234 -j DNAT --to-destination 172.17.0.1:4321 ! -i lo: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
         (exit status 4))
```

`TestNetworkDBIslands` tracked by https://github.com/moby/moby/issues/42459

```
=== RUN   TestNetworkDBIslands
...
networkdb_test.go:864: timeout hit after 2m0s: node5:Waiting for all nodes to cleanly leave, left: 2, failed nodes: 1
```

`TestPortMappingV6Config`: created tracking issue https://github.com/moby/moby/issues/42468

```
=== RUN   TestPortMappingV6Config
time="2021-06-04T05:10:59Z" level=warning msg="Running modprobe bridge br_netfilter failed with message: , error: exec: \"modprobe\": executable file not found in $PATH"
time="2021-06-04T05:10:59Z" level=warning msg="running inside docker container, ignoring missing kernel params: open /proc/sys/net/bridge/bridge-nf-call-iptables: no such file or directory"
time="2021-06-04T05:10:59Z" level=warning msg="bridge store not initialized. kv object docker/network/v1.0/bridge/dummy/ is not added to the store"
time="2021-06-04T05:10:59Z" level=warning msg="bridge store not initialized. kv object docker/network/v1.0/bridge-endpoint/ep1/ is not added to the store"
time="2021-06-04T05:11:00Z" level=warning msg="bridge store not initialized. kv object docker/network/v1.0/bridge-endpoint/ep1/ is not added to the store"
--- FAIL: TestPortMappingV6Config (0.92s)
    port_mapping_test.go:157: Failed to store the port bindings into the sandbox info. Found: [{udp 172.19.0.11 400 0.0.0.0 54000 54000} {tcp 172.19.0.11 500 0.0.0.0 65000 65000} {sctp 172.19.0.11 500 0.0.0.0 65000 65000}]
```

**Review by thaJeztah — APPROVED** [review]
LGTM (sorry, looks like I forgot to submit)

I created https://github.com/moby/moby/issues/42452 to discuss/track follow-ups on the libcontainer/cgroups discussion

**Comment by thaJeztah** [comment]
All green, except for the `TestNetworkDBIslands` test, which is known to be flaky; merging this one; thanks!

**Comment by AkihiroSuda** [comment]
Cherry-pick: https://github.com/moby/moby/pull/42479
