### PR TITLE
Sort the labels passed from `build --labels`

### LINKED ISSUE #29619: labels assigned in inconsistent/random order via `docker build --label`
**Description**

It appears the _ordering_  of multiple `--label` options passed to `docker build` is strangely random and not preserved -- so if we run the **same** `docker build` command multiple times, we can get different images. 

This is mucking up the build cache and creating superfluous layers/images -- which is slowing builds when multiple labels are passed via the cli.

**Steps to reproduce the issue:**

The more`--label` options passed, the easier it is to repeat. I'll demonstrate with 5 labels, running the command 9 times, using the same Dockerfile.

1.  Create simple Dockerfile

```sh
echo "FROM debian:jessie" > Dockerfile
```

2. build an image, passing labels via the cli 

```sh
docker build -t labeltest \
  --label=org.a="cli-a" \
  --label=org.b="cli-b" \
  --label=org.c="cli-c" \
  --label=org.d="cli-d" \
  --label=org.e="cli-e" \
  .
```

3. run the same build command over and over

```sh

build/image(){
  docker build -t labeltest \
    --label=org.a="cli-a" \
    --label=org.b="cli-b" \
    --label=org.c="cli-c" \
    --label=org.d="cli-d" \
    --label=org.e="cli-e" \
    .
}

for i in {1..9}; do
  echo "## build attempt $i , $(build/image | grep LABEL)"
done
```

**Describe the results you received:**

```
## build attempt 1 , Step 2 : LABEL "org.c" "cli-c" "org.d" "cli-d" "org.e" "cli-e" "org.a" "cli-a" "org.b" "cli-b"
## build attempt 2 , Step 2 : LABEL "org.e" "cli-e" "org.a" "cli-a" "org.b" "cli-b" "org.c" "cli-c" "org.d" "cli-d"
## build attempt 3 , Step 2 : LABEL "org.c" "cli-c" "org.d" "cli-d" "org.e" "cli-e" "org.a" "cli-a" "org.b" "cli-b"
## build attempt 4 , Step 2 : LABEL "org.d" "cli-d" "org.e" "cli-e" "org.a" "cli-a" "org.b" "cli-b" "org.c" "cli-c"
## build attempt 5 , Step 2 : LABEL "org.d" "cli-d" "org.e" "cli-e" "org.a" "cli-a" "org.b" "cli-b" "org.c" "cli-c"
## build attempt 6 , Step 2 : LABEL "org.a" "cli-a" "org.b" "cli-b" "org.c" "cli-c" "org.d" "cli-d" "org.e" "cli-e"
## build attempt 7 , Step 2 : LABEL "org.a" "cli-a" "org.b" "cli-b" "org.c" "cli-c" "org.d" "cli-d" "org.e" "cli-e"
## build attempt 8 , Step 2 : LABEL "org.b" "cli-b" "org.c" "cli-c" "org.d" "cli-d" "org.e" "cli-e" "org.a" "cli-a"
## build attempt 9 , Step 2 : LABEL "org.b" "cli-b" "org.c" "cli-c" "org.d" "cli-d" "org.e" "cli-e" "org.a" "cli-a"
```

You'll see the LABEL step is inconsistent, and it creates a new layer because of the changed ordering.

**Describe the results you expected:**

The LABEL to remain consistent, so we don't randomly create new layers/images.

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.7.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 19:42:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7
 Git commit:   23cf638
 Built:        Fri Aug 19 02:03:02 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 91
 Running: 0
 Paused: 0
 Stopped: 91
Images: 1049
Server Version: 1.12.1
Storage Driver: overlay
 Backing Filesystem: f2fs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.7.2-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.747 GiB
Name: hartford
ID: KVIO:FKIX:BTN6:RAMN:W5TV:3IB3:2NCV:NYDB:L37L:OHZ5:3IOH:O444
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: briceburg
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

bare metal arch linux

### PR DESCRIPTION
**Pull request by yongtang**
**- What I did**

This fix tries to fix the issue in #29619 where labels passed from `build --labels` are not sorted.
As a result, if multiple labels have been passed, each `docker build --labels A=A --labels B=B --labels C=C` run will generate different layers.

**- How I did it**

This fix fixes the issue by sort the Labels before they are concatenated to `LABEL ...`.

**- How to verify it**

An integration test has been added to cover the changes

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

cute-kitten-865-10-400x250

This fix fixes #29619.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

File: integration-cli/docker_cli_build_test.go [hunk 1]
```diff
@@ -7357,3 +7357,19 @@ func (s *DockerSuite) TestBuildWindowsEnvCaseInsensitive(c *check.C) {
 		c.Fatalf("Case insensitive environment variables on Windows failed. Got %s", res)
 	}
 }
+
+func (s *DockerSuite) TestBuildLabelsArgs(c *check.C) {
```
Comment (AkihiroSuda) [inline integration-cli/docker_cli_build_test.go]: Probably this can be moved to UT, but I think it is ok to keep this IT at the moment.

File: builder/dockerfile/builder.go [hunk 2]
```diff
@@ -234,9 +235,16 @@ func (b *Builder) build(stdout io.Writer, stderr io.Writer, out io.Writer) (stri
 	}
 
 	if len(b.options.Labels) > 0 {
-		line := "LABEL "
+		var labels []string
 		for k, v := range b.options.Labels {
-			line += fmt.Sprintf("%q='%s' ", k, v)
+			labels = append(labels, fmt.Sprintf("%q='%s' ", k, v))
```
Comment (yongtang) [inline builder/dockerfile/builder.go]: Thanks. Done.

File: integration-cli/docker_cli_build_test.go (hunk 1 above)
Comment (yongtang) [inline integration-cli/docker_cli_build_test.go]: Thanks @AkihiroSuda. In #29619 the issue was only triggered by `docker build --label A=A --label B=B ...` through command line. `LABEL` inside Dockerfile directly will not trigger the issue. So I think it probably make sense to have a IT for it.

**Review by cpuguy83 — APPROVED** [review]
LGTM

File: integration-cli/docker_cli_build_test.go (hunk 1 above)
Comment (dnephin) [inline integration-cli/docker_cli_build_test.go]: I agree this should really be a unit test.  Every bug is technically invoked from either the CLI or API, but I don't think that necessarily warrants an integration test. Integration tests are great for catching regressions where the bug was because of an integration between two components.

In this case the bug seems to be in a single component, so it could be tested directly.

A rule I like to follow is that if a function is hard to unit test, it's a good sign the function should be refactored in a way that makes it easier to test. Functions that are hard to test are often hard to re-use as well.  Since this function is 100 lines long, it is difficult to test the behaviour in isolation. It might not be a bad idea to split it up, making it easier to test.

**Comment by tonistiigi** [comment]
LGTM

**Comment by yongtang** [comment]
Thanks @AkihiroSuda @dnephin. The PR has been updated with unit test. The `build()` has been decomposed into `processLabels()` as `build()` will invoke the daemon to compete the whole build.

Please take a look.

**Review by dnephin — APPROVED** [review]
LGTM!

**Review by cpuguy83 — APPROVED** [review]

**Comment by cpuguy83** [comment]
```
builder/dockerfile/builder_test.go:39: missing argument for Fatalf("%s"): format reads arg 1, have only 0 args
```

**Comment by yongtang** [comment]
Thanks @cpuguy83 The PR has been updated.

File: builder/dockerfile/builder_test.go [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+	d := parser.Directive{}
+	parser.SetEscapeToken(parser.DefaultEscapeToken, &d)
+	n, err := parser.Parse(strings.NewReader(dockerfile), &d)
+	if err != nil {
+		t.Fatalf("Error when parsing Dockerfile: %s", err)
+	}
+
+	options := &types.ImageBuildOptions{
+		Labels: map[string]string{
+			"org.a": "cli-a",
```
Comment (briceburg) [inline builder/dockerfile/builder_test.go]: you may want to put the labels in out-of-order to test sording actually works. e.g. org.c, org.a, org.d, ...

Comment (thaJeztah) [inline builder/dockerfile/builder_test.go]: For clarity, yes I agree.

In practice, it won't make a difference, because Go always randomizes map order; see https://nathanleclaire.com/blog/2014/04/27/a-surprising-feature-of-golang-that-colored-me-impressed/

Comment (yongtang) [inline builder/dockerfile/builder_test.go]: @briceburg The map is always randomized:
```
ubuntu@ubuntu:~/tmp$ cat main.go 
package main

import (
	"fmt"
)

func main() {
	labels := map[string]string{
		"org.a": "cli-a",
		"org.b": "cli-b",
		"org.c": "cli-c",
		"org.d": "cli-d",
		"org.e": "cli-e",
	}
	for k, v := range labels {
		fmt.Println(k, v)
	}
}

ubuntu@ubuntu:~/tmp$ 
ubuntu@ubuntu:~/tmp$ go run main.go 
org.a cli-a
org.b cli-b
org.c cli-c
org.d cli-d
org.e cli-e
ubuntu@ubuntu:~/tmp$ go run main.go 
org.e cli-e
org.a cli-a
org.b cli-b
org.c cli-c
org.d cli-d
ubuntu@ubuntu:~/tmp$ go run main.go 
org.d cli-d
org.e cli-e
org.a cli-a
org.b cli-b
org.c cli-c
ubuntu@ubuntu:~/tmp$ go run main.go 
org.b cli-b
org.c cli-c
org.d cli-d
org.e cli-e
org.a cli-a
ubuntu@ubuntu:~/tmp$
```

I updated the PR to shuffle the order though to make it clear though.

Comment (briceburg) [inline builder/dockerfile/builder_test.go]: Yes, totally unnecessary but perhaps more clear to a gomature like myself. boy do I have a lot to learn! :smile: 

Many thanks for sharing, and for jumping on the label issue so quickly!  It's inspiring to witness this project work.

**Comment by coolljt0725** [comment]
@yongtang  some tests failed

**Comment by yongtang** [comment]
Thanks @coolljt0725 I tested locally and those tests passed. Think it might be flaky. Added an issue #29663 and will keep an eye on it.
