### PR TITLE
fix blockThreshold full deadlock bug

### LINKED ISSUE #41941: Container in an incorrect 'UP' status
**Description**
I observe that the Contianer is in the UP state and the task (from ctr task list) is in the STOPPED state.
Container:
image
Task:
image

**Describe the results you received:**
the exec stdio file is still there.
image

the docker can not deal 'tasks/exit' event.
image
and write stdout stuck in cond.Wait(), The initial reason is that the length exceeds the BlockThreshold.
image

**Describe the results you expected:**
Delete the container correctly.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:27:04 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:25:42 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 154
  Running: 109
  Paused: 0
  Stopped: 45
 Images: 62
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.14.105-19-0008
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 62.41GiB
 Name: vm-2-42-centos
 ID: 7ZD5:3KAS:KRHV:JVXS:WADR:R2AZ:TQ47:BFPB:M6ZH:BWU2:MAIS:RPQY
 Docker Root Dir: /data/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
 Live Restore Enabled: true
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by ningmingxiao**
fixes https://github.com/moby/moby/issues/41941

Signed-off-by: ningmingxiao <ning.mingxiao@zte.com.cn>
 **Description**
if bp.bufLen == 0 ,bp.wait.Wait() will block in func (bp *BytesPipe) Read(p []byte) (n int, err error)
then if bp.bufLen >= blockThreshold in func (bp *BytesPipe) Write(p []byte) (int, error) will block at bp.wait.Wait()
there are two bp.wait.Wait() will hang

**How I reappear it**
pkg/ioutils/bytespipe.go 
1.change blockThreshold =1000 maxCap=1000, which  will easily reappear
2. go build main.go

```
package main

import (
	"fmt"
	"io/ioutil"
)

func log(){
	b, err := ioutil.ReadFile("/var/log/messages")
	if err != nil {
		fmt.Print(err)
	}
	fmt.Println(string(b))
}

func main() {
	log()
}
```
3.put main file at /var/log/ on host , messages' size is more than 10m

4.docker run -v /var/:/var/ --log-driver=none -itd busybox /bin/sh
5. docker attach container
6. cd /var/log/ and run ./main
then kill -s SIGUSR1 $(pidof dockerd) to print stack ,it will appear hang
if use my commit it will not appear

**- How I did it**
I add a  readBlock at BytesPipe struct
to check whether bp.wait.Wait()  at
 func (bp *BytesPipe) Read(p []byte) (n int, err error)

### CODE REVIEW

**Comment by ningmingxiao** [comment]
fix https://github.com/moby/moby/issues/41941

**Comment by AkihiroSuda** [comment]
How to test this?

**Comment by ningmingxiao** [comment]
I'm tinking how to test it

**Comment by ningmingxiao** [comment]
1.change blockThreshold =1000,
2.  go build main.go  
```
package main

import (
	"fmt"
	"io/ioutil"
)

func log(){
	b, err := ioutil.ReadFile("/var/log/messages")
	if err != nil {
		fmt.Print(err)
	}
	fmt.Println(string(b))
}

func main() {
	log()
}
```
3.put main file at /var/log/  on host , messages is  bigfile about 10m

4.docker run  -v /var/:/var/ -itd busybox  /bin/sh
5. docker attach container
6. cd /var/log/ and run ./main 
then kill -s SIGUSR1  $(pidof dockerd) to print stack ,it will appear hang
if user  my commit it will not appear

**Comment by ningmingxiao** [comment]
if  bp.bufLen == 0  bp.wait.Wait() will block at func (bp *BytesPipe) Read(p []byte) (n int, err error) 
then  if   bp.bufLen >= blockThreshold in  func (bp *BytesPipe) Write(p []byte) (int, error)  will block at  bp.wait.Wait()
there are two  bp.wait.Wait() will hang

**Comment by ningmingxiao** [comment]
hi,@thaJeztah  plz review my code,thanks

**Comment by ningmingxiao** [comment]
hi,plz review my code thank you, @AkihiroSuda

**Comment by ningmingxiao** [comment]
plz review my code @crosbymichael  @Brian Goff

**Review by corhere — APPROVED** [review]
I'm convinced this fix is correct. I've rebased the PR and added a regression test.

@neersighted @thaJeztah PTAL. I think we should backport this fix all the way back to 20.10, given how many new issues have been filed lately which appear to have this deadlock as their root cause.

File: pkg/ioutils/bytespipe.go [hunk 1]
```diff
@@ -85,6 +86,10 @@ loop0:
 
 		// make sure the buffer doesn't grow too big from this write
 		for bp.bufLen >= blockThreshold {
+			if bp.readBlock {
+				bp.wait.Broadcast()
+				bp.readBlock = false
```
Comment (aaronlehmann) [inline pkg/ioutils/bytespipe.go:91]: I don't think it makes a functional difference, but I would move this line to after the `bp.wait.Wait()` call in `Read`, for symmetry and because there are other code paths that can unblock `Read`. As written, this can cause some extra calls to `Broadcast`, which doesn't matter much.

**Review by aaronlehmann — APPROVED** [review]
LGTM

File: pkg/ioutils/bytespipe.go (hunk 1 above)
Comment (ningmingxiao) [reply pkg/ioutils/bytespipe.go]: done,thank you

**Review by neersighted — APPROVED** [review]
Holding my nose a bit, but I don't see a good way to clean this up without investing a lot of time to re-implement this code from first-principles, and that's very much diminishing returns.
