### PR TITLE
Fix regression in parsing capabilities

### LINKED ISSUE #14318: /containers/create no longer accepts a string for CapAdd or CapDrop
Similarly to #14170, sending a string for `CapAdd` or `CapDrop` when creating a container with a Docker 1.7.0 daemon results in an unmarshaling error.

Assuming a Docker daemon at `http://docker`:

```
$ curl -X POST http://docker/v1.19/images/create?fromImage=busybox > /dev/null

$ curl -X POST -H 'Content-Type: application/json' http://docker/v1.19/containers/create -d '{"Image": "busybox", "Cmd": "/bin/true", "HostConfig": {"CapAdd": ["NET_ADMIN"]} }'
{"Id":"c145aca6ba8f2f08b1865f5ae031cdb7dffe163b4d9e750d603146ee1cfc6861","Warnings":null}

$ curl -X POST -H 'Content-Type: application/json' http://docker/v1.19/containers/create -d '{"Image": "busybox", "Cmd": "/bin/true", "HostConfig": {"CapAdd": "NET_ADMIN"} }'
json: cannot unmarshal string into Go value of type []string
```

### PR DESCRIPTION
**Pull request by runcom**
Fixes #14318 
I'm doing a follow up pr in a moment or tomorrow to abstract `CapList`, `EntryPoint` and `Command` (for now) instead of redefining all those equal methods on them
everything was working before because of `GetenvList` https://github.com/docker/docker/blob/v1.6.2/runconfig/hostconfig.go#L206

Signed-off-by: Antonio Murdaca runcom@linux.com

### CODE REVIEW

**Comment by runcom** [comment]
ping @LK4D4 @cpuguy83 @calavera

File: daemon/container_linux.go [hunk 1]
```diff
@@ -297,8 +297,8 @@ func populateCommand(c *Container, env []string) error {
 		Resources:          resources,
 		AllowedDevices:     allowedDevices,
 		AutoCreatedDevices: autoCreatedDevices,
-		CapAdd:             c.hostConfig.CapAdd,
-		CapDrop:            c.hostConfig.CapDrop,
+		CapAdd:             c.hostConfig.CapAdd.Slice(),
```
Comment (runcom) [inline daemon/container_linux.go]: reason behind not changing the type in `execdriver.Command` is because I didn't want to modify it since it will eventually be deleted along whole execdriver, I can change it tho if you prefer

Comment (calavera) [inline daemon/container_linux.go]: I think this looks good enough for the release

**Comment by calavera** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Comment by calavera** [comment]
Cherry picked into #14264

**Comment by runcom** [comment]
@calavera I don't see this commit in #14264, isn't this for 1.7.1?
