### PR TITLE
Fix flaky TestServiceWithDefaultAddressPoolInit

### LINKED ISSUE #38514: Flaky test: TestServiceWithDefaultAddressPoolInit
This error looks to happened at least three times on experimental on PRs:
- #38138
- #38487
- #38490
And at least once on Janky:
- #38527
```
17:19:20 === RUN   TestServiceWithDefaultAddressPoolInit
17:19:21 --- FAIL: TestServiceWithDefaultAddressPoolInit (1.28s)
17:19:21     daemon.go:296: [d38c8a3f9fff9] waiting for daemon to start
17:19:21     daemon.go:328: [d38c8a3f9fff9] daemon started
17:19:21     service_test.go:420: TestServiceWithDefaultAddressPoolInit: NetworkInspect: {Name:saanvisthiraTestServiceWithDefaultAddressPoolInit ID:2e1jfqltui460afgk05cgwr5r Created:2019-01-08 17:19:21.726166875 +0000 UTC Scope:swarm Driver: EnableIPv6:false IPAM:{Driver: Options:map[] Config:[]} Internal:false Attachable:false Ingress:false ConfigFrom:{Network:} ConfigOnly:false Containers:map[] Options:map[] Labels:map[] Peers:[] Services:map[]}
17:19:21     service_test.go:421: assertion failed: expression is false: len(out.IPAM.Config) > 0
```

### PR DESCRIPTION
**Pull request by arkodg**
fixes https://github.com/moby/moby/issues/38514 Flaky test: TestServiceWithDefaultAddressPoolInit

This commit replaces serviceRunningCount with
swarm.RunningTasksCount to accurately check if the
service is running with the accurate number of instances
or not. serviceRunningCount was only checking the ServiceList
and was not checking if the tasks were running or not

This adds a safe barrier to execute docker network inspect
commands for overlay networks which get created
asynchronously via swarmkit

Signed-off-by: Arko Dasgupta <arko.dasgupta@docker.com>

### CODE REVIEW

**Comment by arkodg** [comment]
@thaJeztah any idea why the test case is failing ?
I removed all the SwarmLeave calls but I still see `Calling POST /v1.41/swarm/leave?force=1"` which is causing the service to not start

**Comment by arkodg** [comment]
and changing the order of the operation breaks the next test `TestServiceWithDataPathPortInit`

**Comment by thaJeztah** [comment]
is there a manager that failed to stop perhaps?

```
error is not nil: Error response from daemon: manager stopped: failed to listen on remote API address: listen tcp 0.0.0.0:2477: bind: address already in use: initializing swarm

**Comment by kolyshkin** [comment]
> bind: address already in use

Means someone is already listening on this port. Not sure what it means in this exact context.

**Comment by arkodg** [comment]
Derek add label: rebuild/windows*

**Comment by arkodg** [comment]
Derek add label: rebuild/powerpc

**Comment by arkodg** [comment]
PTAL @thaJeztah

**Comment by arkodg** [comment]
Derek add label: rebuild/*

**Review by thaJeztah — CHANGES_REQUESTED** [review]
Whoops; had some pending comments; let me submit those and have another look later

File: integration/network/service_test.go [hunk 1]
```diff
@@ -329,6 +315,63 @@ func noServices(ctx context.Context, client client.ServiceAPIClient) func(log po
...
+	err = cli.ServiceRemove(ctx, serviceID)
+	poll.WaitOn(t, noServices(ctx, cli), swarm.ServicePoll)
+	poll.WaitOn(t, swarm.NoTasks(ctx, cli), swarm.ServicePoll)
+	assert.NilError(t, err)
+	err = cli.NetworkRemove(ctx, overlayID)
+	assert.NilError(t, err)
+	d.SwarmLeave(t, true)
+	d.Stop(t)
+
+	// Clean up , set it back to original one to make sure other tests don't fail
```
Comment (thaJeztah) [inline integration/network/service_test.go]: One more question; would not setting this back cause problems (e.g. if this test fails?) should we `defer` this? 

(Not urgent for this PR, just wondering)

File: integration/network/service_test.go [hunk 2]
```diff
@@ -337,105 +380,63 @@ func TestServiceWithDataPathPortInit(t *testing.T) {
...
 	d.SwarmLeave(t, true)
 	d.Stop(t)
 
 	// Clean up , set it back to original one to make sure other tests don't fail
 	// call without datapath port option.
 	ops = []func(*daemon.Daemon){}
 	d = swarm.NewSwarm(t, testEnv, ops...)
-	c = d.NewClientT(t)
-
+	nc := d.NewClientT(t)
```
Comment (thaJeztah) [inline integration/network/service_test.go]: was there a reason for using a new variable here?

File: integration/network/service_test.go [hunk 3]
```diff
@@ -337,105 +380,63 @@ func TestServiceWithDataPathPortInit(t *testing.T) {
...
 	assert.Equal(t, info.Swarm.Cluster.DataPathPort, datapathPort)
-	err := c.ServiceRemove(context.Background(), serviceID)
+	err := c.ServiceRemove(ctx, serviceID)
 	assert.NilError(t, err)
+	poll.WaitOn(t, noServices(ctx, c), swarm.ServicePoll)
+	poll.WaitOn(t, swarm.NoTasks(ctx, c), swarm.ServicePoll)
+	err = c.NetworkRemove(ctx, overlayID)
+	assert.NilError(t, err)
+	c.Close()
 	d.SwarmLeave(t, true)
```
Comment (thaJeztah) [inline integration/network/service_test.go]: Wondering if we should log the error if `d.SwarmLeave` fails

**Review by thaJeztah — CHANGES_REQUESTED** [review]
overall looks good; could you have a look at my comments, and move the function back to its old position (which makes it easier to double-check I didn't miss anything)

File: integration/network/service_test.go (hunk 2 above)
Comment (arkodg) [reply integration/network/service_test.go]: client is tied to `daemon` (swarm.NewSwarm) so I assumed if a new object was created a new client has to. be instantiated as well

File: integration/network/service_test.go (hunk 3 above)
Comment (arkodg) [reply integration/network/service_test.go]: ACK

File: integration/network/service_test.go [hunk 4]
```diff
@@ -329,6 +315,63 @@ func noServices(ctx context.Context, client client.ServiceAPIClient) func(log po
...
+	poll.WaitOn(t, swarm.NoTasks(ctx, cli), swarm.ServicePoll)
+	assert.NilError(t, err)
+	err = cli.NetworkRemove(ctx, overlayID)
+	assert.NilError(t, err)
+	d.SwarmLeave(t, true)
+	d.Stop(t)
+
+	// Clean up , set it back to original one to make sure other tests don't fail
+	ipAddr = []string{"10.0.0.0/8"}
+	ops = append(ops, daemon.WithSwarmDefaultAddrPool(ipAddr))
```
[the remark this answers is not in the document]
Comment (arkodg) [reply integration/network/service_test.go]: ACK

File: integration/network/service_test.go [hunk 5]
```diff
@@ -329,6 +315,63 @@ func noServices(ctx context.Context, client client.ServiceAPIClient) func(log po
...
 }
 
+func TestServiceWithDefaultAddressPoolInit(t *testing.T) {
+	skip.If(t, testEnv.OSType == "windows")
+	defer setupTest(t)()
+	var ops = []func(*daemon.Daemon){}
+	ipAddr := []string{"20.20.0.0/16"}
+	ops = append(ops, daemon.WithSwarmDefaultAddrPool(ipAddr))
+	ops = append(ops, daemon.WithSwarmDefaultAddrPoolSubnetSize(24))
+	d := swarm.NewSwarm(t, testEnv, ops...)
```
[the remark this answers is not in the document]
Comment (arkodg) [reply integration/network/service_test.go]: ACK

File: integration/network/service_test.go [hunk 6]
```diff
@@ -329,6 +315,63 @@ func noServices(ctx context.Context, client client.ServiceAPIClient) func(log po
 	}
 }
 
+func TestServiceWithDefaultAddressPoolInit(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (arkodg) [reply integration/network/service_test.go]: ACK

File: integration/network/service_test.go (hunk 1 above)
Comment (arkodg) [reply integration/network/service_test.go]: Cleaned it up :)

**Comment by arkodg** [comment]
Derek add label: rebuild/windowsRS1

**Comment by arkodg** [comment]
Derek add label: rebuild/windowsRS1

File: integration/network/service_test.go [hunk 7]
```diff
@@ -333,76 +319,84 @@ func TestServiceWithDataPathPortInit(t *testing.T) {
...
-	poll.WaitOn(t, serviceRunningCount(c, serviceID, instances), swarm.ServicePoll)
+	poll.WaitOn(t, swarm.RunningTasksCount(nc, serviceID, instances), swarm.ServicePoll)
 
 	info = d.Info(t)
 	var defaultDataPathPort uint32 = 4789
 	assert.Equal(t, info.Swarm.Cluster.DataPathPort, defaultDataPathPort)
-	err = c.ServiceRemove(context.Background(), serviceID)
+	err = nc.ServiceRemove(ctx, serviceID)
+	assert.NilError(t, err)
+	assert.NilError(t, err)
```
Comment (thaJeztah) [inline integration/network/service_test.go]: looks like there's one too many asserts here

File: integration/network/service_test.go [hunk 8]
```diff
@@ -333,76 +319,84 @@ func TestServiceWithDataPathPortInit(t *testing.T) {
...
 	// Create a overlay network
-	name = "saanvisthira" + t.Name()
-	network.CreateNoError(context.Background(), t, c, name,
+	name = "not-saanvisthira" + t.Name()
+	overlayID = network.CreateNoError(ctx, t, nc, name,
 		network.WithDriver("overlay"))
 
 	serviceID = swarm.CreateService(t, d,
 		swarm.ServiceWithReplicas(instances),
+		swarm.ServiceWithName(name),
```
Comment (thaJeztah) [inline integration/network/service_test.go]: looks like we don't need the servicename?

File: integration/network/service_test.go [hunk 9]
```diff
@@ -333,76 +319,84 @@ func TestServiceWithDataPathPortInit(t *testing.T) {
...
+	assert.NilError(t, err)
+	poll.WaitOn(t, noServices(ctx, c), swarm.ServicePoll)
+	poll.WaitOn(t, swarm.NoTasks(ctx, c), swarm.ServicePoll)
+	err = c.NetworkRemove(ctx, overlayID)
+	assert.NilError(t, err)
+	c.Close()
+	err = d.SwarmLeave(t, true)
 	assert.NilError(t, err)
-	d.SwarmLeave(t, true)
 	d.Stop(t)
```
Comment (thaJeztah) [inline integration/network/service_test.go]: is there something cleaning up / stopping this daemon if the test fails before this? otherwise we might want to consider adding a `defer d.Stop(t)` directly after creating the daemon

File: integration/network/service_test.go [hunk 10]
```diff
@@ -333,76 +319,84 @@ func TestServiceWithDataPathPortInit(t *testing.T) {
...
+	assert.NilError(t, err)
+	assert.NilError(t, err)
+	poll.WaitOn(t, noServices(ctx, nc), swarm.ServicePoll)
+	poll.WaitOn(t, swarm.NoTasks(ctx, nc), swarm.ServicePoll)
+	err = nc.NetworkRemove(ctx, overlayID)
+	assert.NilError(t, err)
+	err = d.SwarmLeave(t, true)
 	assert.NilError(t, err)
-	d.SwarmLeave(t, true)
 	defer d.Stop(t)
```
Comment (thaJeztah) [inline integration/network/service_test.go]: same question about `d.Stop` here

File: integration/network/service_test.go [hunk 11]
```diff
@@ -415,27 +409,25 @@ func TestServiceWithDefaultAddressPoolInit(t *testing.T) {
...
-	d.SwarmLeave(t, true)
-	d.Stop(t)
-
-	// Clean up , set it back to original one to make sure other tests don't fail
-	ipAddr = []string{"10.0.0.0/8"}
-	ops = append(ops, daemon.WithSwarmDefaultAddrPool(ipAddr))
-	ops = append(ops, daemon.WithSwarmDefaultAddrPoolSubnetSize(24))
-	d = swarm.NewSwarm(t, testEnv, ops...)
-	d.SwarmLeave(t, true)
 	defer d.Stop(t)
```
Comment (thaJeztah) [inline integration/network/service_test.go]: this should be directly after `d := swarm.NewSwarm(..)` higher up

File: integration/network/service_test.go (hunk 2 above)
Comment (thaJeztah) [reply integration/network/service_test.go]: True; it was more that the first client is no longer used at this point, so you can reuse the `c` variable (same as the `d` variable is reused here

**Review by thaJeztah — CHANGES_REQUESTED** [review]

File: integration/network/service_test.go (hunk 2 above)
Comment (arkodg) [reply integration/network/service_test.go]: have to call `defer` twice so using two different variables

File: integration/network/service_test.go (hunk 8 above)
Comment (arkodg) [reply integration/network/service_test.go]: keeping it for similar search debuggability in logs

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Comment by arkodg** [comment]
PTAL @kolyshkin

**Comment by thaJeztah** [comment]
@tiborvass PTAL

**Comment by thaJeztah** [comment]
ping @tiborvass @kolyshkin PTAL 🤗

**Review by tiborvass — APPROVED** [review]
