### PR TITLE
Fix gitconfig dependency in pkg/gitutils.TestCheckoutGit

### LINKED ISSUE #23152: pkg/gitutils.TestCheckoutGit fails depending on gitconfig core.autocrlf
**Steps to reproduce the issue:**
```
$ git config --get core.autocrlf
$ go test ./pkg/gitutils
```
Tested with 4a7715c9783627ecc194dac8502a684f40a9d0bd

**Describe the results you received:**

OS|core.autocrlf|Result
---|---|---
Linux|true|FAIL
Linux|false/unset|PASS
Windows|true|PASS
Windows|false/unset|FAIL

failure message:
```
--- FAIL: TestCheckoutGit (0.04s)
        gitutils_test.go:201: Expected FROM scratch
                EXPOSE 5000, was FROM scratch
                EXPOSE 5000
FAIL
```

**Describe the results you expected:**
It should not fail.

**Additional information you deem important (e.g. issue happens only occasionally)**
* Found in PR #22930, which is an attempt to simplify go test in hack/*. The PR uses `env -i` for `test-unit` as well as for `test-integration`, so it disables some git-related environment variable.

* The cause of the issue is obvious: `eol` is not properly set : https://github.com/docker/docker/blob/4a7715c9783627ecc194dac8502a684f40a9d0bd/pkg/gitutils/gitutils_test.go#L80

### PR DESCRIPTION
**Pull request by AkihiroSuda**
**\- What I did**
Fix #23152: pkg/gitutils.TestCheckoutGit fails depending on gitconfig core.autocrlf

**\- How I did it**
Checked the value of core.autocrlf

**\- How to verify it**
Do `go test ./pkg/gitutils` on the following environments.

| OS | core.autocrlf |
| --- | --- |
| Linux | true |
| Linux | false |
| Linux | input |
| Linux | (unset) |
| Windows | true |
| Windows | false |
| Windows | input |
| Windows | (unset) |

Signed-off-by: Akihiro Suda suda.akihiro@lab.ntt.co.jp

---

Maybe we should better call explicitly `gitWithinDir(gitDir, "config", "core.autocrlf", someValue)` rather than checking the global config.
I can update PR if so.

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM

File: pkg/gitutils/gitutils_test.go [hunk 1]
```diff
@@ -70,15 +71,33 @@ func TestCloneArgsStripFragment(t *testing.T) {
 	}
 }
 
+func gitGetConfig(name string) (string, error) {
+	b, err := git([]string{"config", "--get", name}...)
+	if err != nil {
+		return "", err
+	}
+	return strings.Trim(string(b), "\r\n"), err
```
Comment (runcom) [inline pkg/gitutils/gitutils_test.go]: use `strings.TrimSpace`

File: pkg/gitutils/gitutils_test.go [hunk 2]
```diff
@@ -70,15 +71,33 @@ func TestCloneArgsStripFragment(t *testing.T) {
...
+
 func TestCheckoutGit(t *testing.T) {
 	root, err := ioutil.TempDir("", "docker-build-git-checkout")
 	if err != nil {
 		t.Fatal(err)
 	}
 	defer os.RemoveAll(root)
 
+	autocrlf, err := gitGetConfig("core.autocrlf")
+	if err != nil {
```
Comment (runcom) [inline pkg/gitutils/gitutils_test.go]: this `err` check isn't needed, nor it's needed to return an error from `gitGetConfig` since you're just interested in empty or non empty string. You can ignore the error in `gitGetConfig` and just return either `""` or `true|false` and use it here directly w/o this check.

File: pkg/gitutils/gitutils_test.go (hunk 1 above)
Comment (AkihiroSuda) [inline pkg/gitutils/gitutils_test.go]: Thank you for the comment. Done.

File: pkg/gitutils/gitutils_test.go (hunk 2 above)
Comment (AkihiroSuda) [inline pkg/gitutils/gitutils_test.go]: Done

**Comment by vdemeester** [comment]
LGTM :+1:
