### PR TITLE
Consider hardlinks in image size.

### LINKED ISSUE #9283: `docker images` virtual size wrong concerning hardlinks
If you have image layers that include hardlinks, then the virtual size sums each file regardless, so the size will appear larger than the image is on disk, and larger than the tar archive will be.

https://github.com/docker/docker/pull/8984 attempted to fix, but there were complications.

### PR DESCRIPTION
**Pull request by pydima**
Fixes #9283. Based on #8984. This patch fixes behavior when image size calculation
didn't consider hardlinks.

Signed-off-by: Dmitry Vorobev dimahabr@gmail.com

### CODE REVIEW

File: pkg/archive/changes_windows.go [hunk 1]
```diff
@@ -18,3 +20,15 @@ func statDifferent(oldStat *system.StatT, newStat *system.StatT) bool {
 func (info *FileInfo) isDir() bool {
 	return info.parent == nil || info.stat.IsDir()
 }
+
+// GetInode returns inode number from os.FileInfo object
+func GetInode(fi os.FileInfo) (inode uint64) {
+	// do nothing, Windows doesn't support hardlinks
```
Comment (LK4D4) [inline pkg/archive/changes_windows.go]: Weird comment, fucntion about Inode :)

File: pkg/archive/changes_unix.go [hunk 2]
```diff
@@ -25,3 +26,21 @@ func statDifferent(oldStat *system.StatT, newStat *system.StatT) bool {
 func (info *FileInfo) isDir() bool {
 	return info.parent == nil || info.stat.Mode()&syscall.S_IFDIR != 0
 }
+
+// GetInode returns inode number from os.FileInfo object
+func GetInode(fi os.FileInfo) (inode uint64) {
```
Comment (LK4D4) [inline pkg/archive/changes_unix.go]: I think this functions should be private.

File: pkg/archive/changes_unix.go [hunk 3]
```diff
@@ -25,3 +26,21 @@ func statDifferent(oldStat *system.StatT, newStat *system.StatT) bool {
...
+	s, _ := fi.Sys().(*syscall.Stat_t)
+	inode = uint64(s.Ino)
+	return
+}
+
+// IsHardlink detects if os.FileInfo object is hardlink or not
+func IsHardlink(fi os.FileInfo) bool {
+	switch sys := fi.Sys().(type) {
+	case *syscall.Stat_t:
+		if fi.Mode().IsRegular() && sys.Nlink > 1 {
```
Comment (LK4D4) [inline pkg/archive/changes_unix.go]: I wonder what's point of `fi.Mode().IsRegular()` check?

Comment (pydima) [inline pkg/archive/changes_unix.go]: If it's a regular file and has more than 1 link - it's a hard link. IsRegular checks mainly that it's not a directory.

File: pkg/archive/changes_unix.go (hunk 2 above)
Comment (pydima) [inline pkg/archive/changes_unix.go]: Yeah, I agree.

File: pkg/archive/changes_unix.go (hunk 3 above)
Comment (LK4D4) [inline pkg/archive/changes_unix.go]: But directory can't have `Nlink > 0`. But unix sockets can, so I think it's excluding real hardlinks.

Comment (LK4D4) [inline pkg/archive/changes_unix.go]: `> 1` of course :)

Comment (pydima) [inline pkg/archive/changes_unix.go]: Well I'm not sure, but probably directory can. For example - we have a directory 'test' and in this directory we have one link on directory itself '.' , both 'test' and '.' have the same indode. But I'm not sure will be Nlink > 0 in this case.

Comment (LK4D4) [inline pkg/archive/changes_unix.go]: You're right probably, maybe `!fi.IsDir()` then?

Comment (pydima) [inline pkg/archive/changes_unix.go]: What about unix sockets in this case? :)

Comment (LK4D4) [inline pkg/archive/changes_unix.go]: Actually probably directories makes no sense to count twice too.

**Comment by LK4D4** [comment]
I think that if inode number is same, then it's hardlink and it makes sense to exclude it from size. So `Nlink` check maybe is redundant.

File: pkg/archive/changes_unix.go (hunk 3 above)
Comment (pydima) [inline pkg/archive/changes_unix.go]: We don't count them at all. In ChangesSize function we have condition - '!fileInfo.IsDir()'

File: pkg/archive/changes_windows.go (hunk 1 above)
Comment (pydima) [inline pkg/archive/changes_windows.go]: Will fix :)

File: pkg/archive/changes_unix.go (hunk 3 above)
Comment (LK4D4) [inline pkg/archive/changes_unix.go]: then I think `IsRegular` isn't needed.

File: pkg/archive/changes_unix.go [hunk 4]
```diff
@@ -25,3 +26,21 @@ func statDifferent(oldStat *system.StatT, newStat *system.StatT) bool {
...
+
+// GetInode returns inode number from os.FileInfo object
+func GetInode(fi os.FileInfo) (inode uint64) {
+	s, _ := fi.Sys().(*syscall.Stat_t)
+	inode = uint64(s.Ino)
+	return
+}
+
+// IsHardlink detects if os.FileInfo object is hardlink or not
+func IsHardlink(fi os.FileInfo) bool {
```
Comment (LK4D4) [inline pkg/archive/changes_unix.go]: maybe `hasLinks` or `hasHardlinks`?

File: pkg/archive/changes_unix.go [hunk 5]
```diff
@@ -25,3 +26,21 @@ func statDifferent(oldStat *system.StatT, newStat *system.StatT) bool {
...
+	switch sys := fi.Sys().(type) {
```
Comment (LK4D4) [inline pkg/archive/changes_unix.go]: maybe it's better to use notation from previous func:
```
return fi.Sys().(*syscall.Stat).Nlink > 1
```

File: pkg/archive/changes_unix.go (hunk 4 above)
Comment (pydima) [inline pkg/archive/changes_unix.go]: Yeah, will fix.

**Comment by pydima** [comment]
@LK4D4 Have made some fixes according to your comments.

File: pkg/archive/changes_unix.go [hunk 6]
```diff
@@ -25,3 +26,14 @@ func statDifferent(oldStat *system.StatT, newStat *system.StatT) bool {
...
 }
+
+func getIno(fi os.FileInfo) (inode uint64) {
+	s, _ := fi.Sys().(*syscall.Stat_t)
+	inode = uint64(s.Ino)
+	return
+}
+
+// HasHardlinks detects if os.FileInfo object is hardlink or not
+func HasHardlinks(fi os.FileInfo) bool {
```
Comment (LK4D4) [inline pkg/archive/changes_unix.go]: should be private :)

File: pkg/archive/changes_unix.go [hunk 7]
```diff
@@ -25,3 +26,14 @@ func statDifferent(oldStat *system.StatT, newStat *system.StatT) bool {
 func (info *FileInfo) isDir() bool {
 	return info.parent == nil || info.stat.Mode()&syscall.S_IFDIR != 0
 }
+
+func getIno(fi os.FileInfo) (inode uint64) {
+	s, _ := fi.Sys().(*syscall.Stat_t)
```
Comment (LK4D4) [inline pkg/archive/changes_unix.go]: can be `return uint64(fi.Sys().(*syscall.Stat_t).Ino`. It's already uint64 and you don't need named return argument.

File: pkg/archive/changes.go [hunk 8]
```diff
@@ -328,13 +328,29 @@ func ChangesDirs(newDir, oldDir string) ([]Change, error) {
...
+		size int64
+		sf   = make(map[uint64]struct{})
+	)
 	for _, change := range changes {
 		if change.Kind == ChangeModify || change.Kind == ChangeAdd {
 			file := filepath.Join(newDir, change.Path)
-			fileInfo, _ := os.Lstat(file)
+			fileInfo, err := os.Lstat(file)
+			if err != nil {
+				logrus.Debugf("Can not stat %q: %s", file, err)
```
Comment (LK4D4) [inline pkg/archive/changes.go]: It's sorta weird, let's make it `Errorf`, but actually this function should return error.

**Comment by pydima** [comment]
@LK4D4 Updated PR according to your comments.

File: pkg/archive/changes_unix.go [hunk 9]
```diff
@@ -25,3 +26,11 @@ func statDifferent(oldStat *system.StatT, newStat *system.StatT) bool {
 func (info *FileInfo) isDir() bool {
 	return info.parent == nil || info.stat.Mode()&syscall.S_IFDIR != 0
 }
+
+func getIno(fi os.FileInfo) (inode uint64) {
```
Comment (LK4D4) [inline pkg/archive/changes_unix.go]: no need in named return

**Comment by pydima** [comment]
@LK4D4 Fixed.

File: pkg/archive/changes_unix.go [hunk 10]
```diff
@@ -25,3 +26,11 @@ func statDifferent(oldStat *system.StatT, newStat *system.StatT) bool {
 func (info *FileInfo) isDir() bool {
 	return info.parent == nil || info.stat.Mode()&syscall.S_IFDIR != 0
 }
+
+func getIno(fi os.FileInfo) uint64 {
+	return uint64(fi.Sys().(*syscall.Stat_t).Ino)
```
Comment (LK4D4) [inline pkg/archive/changes_unix.go]: It's already `unit64` I think.

Comment (pydima) [inline pkg/archive/changes_unix.go]: I think no, I got ```pkg/archive/changes_unix.go:31: cannot use fi.Sys().(*syscall.Stat_t).Ino (type uint32) as type uint64 in return argument```

Comment (LK4D4) [inline pkg/archive/changes_unix.go]: Funny, probably it depends on os or arch.

**Comment by LK4D4** [comment]
LGTM

**Comment by pydima** [comment]
@LK4D4 I returned ```IsRegular()``` check in archive.go:255, because I removed this check from hasHardLinks function.

File: pkg/archive/changes_unix.go (hunk 10 above)
Comment (vbatts) [inline pkg/archive/changes_unix.go]: @LK4D4 it is arch/platform sensitive. Safest to cast it like this.

File: pkg/archive/changes_unix.go [hunk 11]
```diff
@@ -25,3 +26,11 @@ func statDifferent(oldStat *system.StatT, newStat *system.StatT) bool {
...
+}
+
+func hasHardlinks(fi os.FileInfo) bool {
+	return fi.Sys().(*syscall.Stat_t).Nlink > 1
```
Comment (vbatts) [inline pkg/archive/changes_unix.go]: i'm staring at pondering on whether there would be issues, but i think we'll be fine.
Overlayfs, will basically always be `> 1`, so the `seen[]` will grow more on that storage backend. But i'm trying to remember also when nlink would be above 1 :-\

I think we'll be fine

**Comment by vbatts** [comment]
LGTM

Wish for future feature, I would love to see Size (virtual) and Size (allocated). Since that same `syscall.Stat_t` can give you `stat.Blksize * stat.Blocks`. Especially for these block level CoW storage, you could see the potential savings very clearly.

File: pkg/archive/archive.go [hunk 12]
```diff
@@ -245,14 +245,14 @@ func (ta *tarAppender) addTarFile(path, name string) error {
...
-	nlink, inode, err := setHeaderForSpecialDevice(hdr, ta, name, fi.Sys())
+	inode, err := setHeaderForSpecialDevice(hdr, ta, name, fi.Sys())
 	if err != nil {
 		return err
 	}
 
 	// if it's a regular file and has more than 1 link,
 	// it's hardlinked, so set the type flag accordingly
-	if fi.Mode().IsRegular() && nlink > 1 {
+	if fi.Mode().IsRegular() && hasHardlinks(fi) {
```
Comment (LK4D4) [inline pkg/archive/archive.go]: I still don't understand. ping @vbatts 
Not only regular files can has hardlinks.

Comment (LK4D4) [inline pkg/archive/archive.go]: However I'm still ok with changes, just want to clarify for me.

Comment (vbatts) [inline pkg/archive/archive.go]: true. IIRC only directories can not have hardlinks. The size of sockets and symlinks would just be like 4k. So, not terribly skewed for size.

**Comment by pydima** [comment]
@LK4D4 @vbatts I've removed ```IsRegular``` check and changed it with ```!IsDir``` in archive.go:255

**Comment by vbatts** [comment]
Nicely. LGTM

**Comment by LK4D4** [comment]
@vbatts we can merge then, I think.
