### PR TITLE
Do not fail when a container is being removed and we request its delete again.

### LINKED ISSUE #17170: 1.9: trying to delete a container that is already being deleted
In 1.9 we are seeing these errors quite a bit:

`500 Server Error: Internal Server Error ("Failed to set container state to RemovalInProgress: ALREADYREMOVING")`

I believe we are trying to delete a container that we previously had already tried to delete.  It seems to me that if I try to delete something that is already removing, it shouldn't fail but succeed.  Either return success or wait until the container deletes.

I'm not sure what changed in 1.9, but this happens more frequently.  I will investigate more.

### PR DESCRIPTION
**Pull request by calavera**
Abort the process and return a success response, letting the original
request finish its job.

Fixes #17170

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by runcom** [comment]
wasn't this happening in 1.8?

**Comment by calavera** [comment]
@runcom I'm pretty sure it does happen on 1.8 too, but it's still a bug. I'm okay with not adding it to the release too, it's up to @tiborvass

File: daemon/delete.go [hunk 1]
```diff
@@ -76,22 +76,20 @@ func (daemon *Daemon) rm(container *Container, forceRemove bool) (err error) {
 		}
 	}
 
-	// stop collection of stats for the container regardless
-	// if stats are currently getting collected.
-	daemon.statsCollector.stopCollection(container)
-
-	element := daemon.containers.Get(container.ID)
```
Comment (calavera) [inline daemon/delete.go]: this check was inherited from when the delete method was not thread safe, long long time ago :scream:

File: daemon/delete.go [hunk 2]
```diff
@@ -76,22 +76,20 @@ func (daemon *Daemon) rm(container *Container, forceRemove bool) (err error) {
 		}
 	}
 
-	// stop collection of stats for the container regardless
-	// if stats are currently getting collected.
-	daemon.statsCollector.stopCollection(container)
```
Comment (calavera) [inline daemon/delete.go]: I moved this after setting the removal state because there is no point to try to stop collecting stats from a container that has already being marked for removal. This never failed though because in that case, `stopCollection` is a noop.

**Comment by runcom** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM just waiting for userns to pass

**Comment by tiborvass** [comment]
@calavera if i just run your test without the fix I have a panic:

```
--- FAIL: TestContainerDoubleDelete (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5506a9]

goroutine 25 [running]:
testing.func·006()
	/usr/local/go/src/testing/testing.go:441 +0x181
github.com/docker/docker/daemon.(*statsCollector).stopCollection(0x0, 0xc208537400)
	github.com/docker/docker/daemon/_test/_obj_test/stats_collector_unix.go:66 +0xe9
github.com/docker/docker/daemon.(*Daemon).rm(0xc208033540, 0xc208537400, 0x1, 0x0, 0x0)
	github.com/docker/docker/daemon/_test/_obj_test/delete.go:105 +0x2d3
github.com/docker/docker/daemon.TestContainerDoubleDelete(0xc208570fc0)
	/go/src/github.com/docker/docker/daemon/delete_test.go:36 +0x485
testing.tRunner(0xc208570fc0, 0x19d9cf8)
	/usr/local/go/src/testing/testing.go:447 +0xbf
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:555 +0xa8b

goroutine 1 [chan receive]:
testing.RunTests(0x1436658, 0x19d9bc0, 0x12, 0x12, 0x19e6a01)
	/usr/local/go/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0xc20813e780, 0x1a10be0)
	/usr/local/go/src/testing/testing.go:485 +0x6c
main.main()
	github.com/docker/docker/daemon/_test/_testmain.go:238 +0x291

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 6 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 16 [chan receive]:
database/sql.(*DB).connectionOpener(0xc2080cbcc0)
	/usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:452 +0x31c
```
