### PR TITLE
validate extraHosts in daemon side

### LINKED ISSUE #31378: Throw error instead of http panic when extra hosts are malformed
**Description**

Server panic when extra hosts are malformed

**Steps to reproduce the issue:**
1. Create a container with the following config:

```
{
       "Hostname": "",
       "Domainname": "",
       "User": "",
       "AttachStdin": false,
       "AttachStdout": true,
       "AttachStderr": true,
       "Tty": false,
       "OpenStdin": false,
       "StdinOnce": false,
       "Env": [
               "FOO=bar",
               "BAZ=quux"
       ],
       "Cmd": [
               "date"
       ],
       "Entrypoint": "",
       "Image": "alpine",
       "Labels": {
               "com.example.vendor": "Acme",
               "com.example.license": "GPL",
               "com.example.version": "1.0"
       },
       "Volumes": {
         "/volumes/data": {}
       },
       "WorkingDir": "",
       "NetworkDisabled": false,
       "MacAddress": "12:34:56:78:9a:bc",
       "ExposedPorts": {
               "22/tcp": {}
       },
       "StopSignal": "SIGTERM",
       "HostConfig": {
         "Binds": ["/tmp:/tmp"],
         "PortBindings": { "22/tcp": [{ "HostPort": "11022" }] },
         "PublishAllPorts": false,
         "Privileged": false,
         "ReadonlyRootfs": false,
         "Dns": ["8.8.8.8"],
         "DnsOptions": [""],
         "DnsSearch": [""],
         "ExtraHosts": ["host,ip"],
         "NetworkMode": "bridge",
         "Devices": [],
         "Sysctls": { "net.ipv4.ip_forward": "1" },
         "Ulimits": [{}],
         "LogConfig": { "Type": "json-file", "Config": {} },
         "SecurityOpt": [],
         "StorageOpt": {},
         "CgroupParent": "",
         "VolumeDriver": "",
         "ShmSize": 67108864
      },
      "NetworkingConfig": {
          "EndpointsConfig": {
          }
      }
  }
```

Note invalid `"ExtraHosts": ["host,ip"]`

2. Start this container

**Describe the results you received:**

The following error is shown:

`error during connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.26/containers/d8c655aa31d3/start: EOF
`
**Describe the results you expected:**

A user friendly message indicating the reason of such a failure

**Additional information you deem important (e.g. issue happens only occasionally):**

http panic instead of a proper error handling:

```
http: panic serving @: runtime error: index out of range
                                                       goroutine 5720 [running]:
                                                       net/http.(*conn).serve.func1(0xc421cbd380)
                                                               /usr/lib/golang/src/net/http/server.go:1491 +0x12a
                                                       panic(0x15dad40, 0xc420010090)
                                                               /usr/lib/golang/src/runtime/panic.go:458 +0x243
                                                       github.com/docker/docker/daemon.(*Daemon).buildSandboxOptions(0xc420093ba0, 0xc420494f00, 0x222d9c0, 0xc4219aef00, 0x222c0c0, 0xc421908840, 0x0)
                                                               /builddir/build/BUILD/docker-047e51b797564227b0bf26f3aa448f563bea5c71/_build/src/github.com/docker/docker/daemon/container_operations.go:121 +0xd
ed
                                                       github.com/docker/docker/daemon.(*Daemon).connectToNetwork(0xc420093ba0, 0xc420494f00, 0xc420f70540, 0x2a, 0xc421d7ef00, 0x0, 0x0, 0x0)
                                                               /builddir/build/BUILD/docker-047e51b797564227b0bf26f3aa448f563bea5c71/_build/src/github.com/docker/docker/daemon/container_operations.go:590 +0x7
9a
                                                       github.com/docker/docker/daemon.(*Daemon).allocateNetwork(0xc420093ba0, 0xc420494f00, 0x58ce00, 0xc4221131e0)
                                                               /builddir/build/BUILD/docker-047e51b797564227b0bf26f3aa448f563bea5c71/_build/src/github.com/docker/docker/daemon/container_operations.go:426 +0x2
7d
                                                       github.com/docker/docker/daemon.(*Daemon).initializeNetworking(0xc420093ba0, 0xc420494f00, 0x0, 0x0)
                                                               /builddir/build/BUILD/docker-047e51b797564227b0bf26f3aa448f563bea5c71/_build/src/github.com/docker/docker/daemon/container_operations.go:703 +0x2
a5

```

**Output of `docker version`:**

```
Server Version: 1.12.5
Storage Driver: devicemapper
 Pool Name: VolGroup01-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 3.692 GB
 Data Space Total: 329.4 GB
 Data Space Available: 325.7 GB
 Metadata Space Used: 1.606 MB
 Metadata Space Total: 1.074 GB
 Metadata Space Available: 1.072 GB
 Thin Pool Minimum Free Space: 32.94 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge null host overlay
 Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp
Kernel Version: 3.10.0-514.6.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 8
Total Memory: 62.75 GiB
Name: denatb3dhcod02
ID: D7GF:EZNF:2ZZA:64UO:JYY4:L2NL:4SLH:BLTX:ON2E:5V2S:NSDQ:LLZ5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://registry.access.redhat.com/v1/
Insecure Registries:
 127.0.0.0/8
Registries: registry.access.redhat.com (secure), docker.io (secure)

```

### PR DESCRIPTION
**Pull request by allencloud**
Signed-off-by: allencloud <allen.sun@daocloud.io>

fixes https://github.com/docker/docker/issues/31378

**- What I did**
1. add validation for extraHosts in daemon side when creating a container;
2  add validation for extraHosts in buildSandboxOptions to prevent the remaining container with run extraHost from being started again 

I think the extraHost has already covered in UNIT test of https://github.com/docker/docker/blob/master/opts/hosts_test.go#L151-L164 , then no integration test added.

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by thaJeztah — DISMISSED** [review]
~~LGTM~~ see below

**Comment by thaJeztah** [comment]
Windows is failing;
```
13:34:47 # github.com/docker/docker/daemon
13:34:47 ..\..\daemon\container.go:260: multiple-value opts.ValidateExtraHost() in single-value context
```

File: daemon/container.go [hunk 1]
```diff
@@ -256,6 +256,12 @@ func (daemon *Daemon) verifyContainerSettings(hostConfig *containertypes.HostCon
 		return nil, fmt.Errorf("can't create 'AutoRemove' container with restart policy")
 	}
 
+	for _, extraHost := range hostConfig.ExtraHosts {
+		if err := opts.ValidateExtraHost(extraHost); err != nil {
```
Comment (thaJeztah) [inline daemon/container.go]: Should probably be

```go
if _, err := ......
```

**Review by thaJeztah — CHANGES_REQUESTED** [review]

File: daemon/container_operations.go [hunk 2]
```diff
@@ -118,6 +118,9 @@ func (daemon *Daemon) buildSandboxOptions(container *container.Container) ([]lib
 	for _, extraHost := range container.HostConfig.ExtraHosts {
 		// allow IPv6 addresses in extra hosts; only split on first ":"
 		parts := strings.SplitN(extraHost, ":", 2)
+		if len(parts) != 2 {
```
Comment (AkihiroSuda) [inline daemon/container_operations.go]: why not use `opts.ValidateExtraHost` here?

File: daemon/container.go (hunk 1 above)
Comment (allencloud) [inline daemon/container.go]: Oh, this validation still returns the original input string, sorry for my mistake. Updated.

File: daemon/container_operations.go (hunk 2 above)
Comment (allencloud) [inline daemon/container_operations.go]: Yeah, `opts.ValidateExtraHost` also validates whether the IP is valid, not only bad format.

**Comment by allencloud** [comment]
Yeah, I think it is flaky test. PTAL @thaJeztah

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐸
