### PR TITLE
Fix conflicting container name producing 400 error instead of 409

### LINKED ISSUE #35021: Create container with duplicated name returns 400 instead of 409
**Description**
Creating containers with duplicated name used to return a 409 HTTP response, however, since 17.09 release it now returns a 400 response breaking compatibility for API users. 

**Steps to reproduce the issue:**
1. Create a container `docker create --name c1 busybox`
2. Run `curl -v -XPOST -H"Content-Type: application/json" -d'{"Image":"busybox"}' http://localhost:2375/containers/create?name=c1`

**Describe the results you received:**

The HTTP response will be 400 Bad Request.

**Describe the results you expected:**

Prior to 17.09 the response would be 409 Conflict

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 7
 Running: 6
 Paused: 0
 Stopped: 1
Images: 18
Server Version: 17.09.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 55
 Dirperm1 Supported: true
Logging Driver: syslog
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: ug3ojsrrreyxeq63nbwyikv3f
 Is Manager: true
 ClusterID: n2efj7ylwed1onrdxy0sp4dp1
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.50.4
 Manager Addresses:
  192.168.50.4:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 2.915GiB
Name: vagrant
ID: QCSK:UDNT:AMC2:P6TV:M4LV:UZQE:7Z2W:TEHN:VJ75:YQTG:QIBD:TYJC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 85
 Goroutines: 180
 System Time: 2017-09-28T14:10:12.894604072Z
 EventsListeners: 1
Username: cezarsa
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.1:5000
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Virtualbox

### PR DESCRIPTION
**Pull request by thaJeztah**
fixes https://github.com/moby/moby/issues/35021

Commit ebcb7d6b406fe50ea9a237c73004d75884184c33 (https://github.com/moby/moby/pull/34188) removed string checking
for error messages, in favor of typed errors.

In this change, the status code for conflicting container  names
changed from 409 to 400 (validationError).

This patch add a `conflictError`, changing the status code to
409 as it was in older versions.

With this change applied, the correct 409 status is returned:

```bash
$ docker create --name c1 busybox
```

```bash
$ curl --unix-socket /var/run/docker.sock -v -XPOST -H"Content-Type: application/json" -d'{"Image":"busybox"}' http://localhost/containers/create?name=c1
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying /var/run/docker.sock...
* Connected to localhost (/var/run/docker.sock) port 80 (#0)
> POST /containers/create?name=c1 HTTP/1.1
> Host: localhost
> User-Agent: curl/7.52.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 19
>
* upload completely sent off: 19 out of 19 bytes
< HTTP/1.1 409 Conflict
< Api-Version: 1.33
< Content-Type: application/json
< Docker-Experimental: false
< Ostype: linux
< Server: Docker/17.06.0-dev (linux)
< Date: Thu, 28 Sep 2017 15:07:23 GMT
< Content-Length: 229
<
{"message":"Conflict. The container name \"/c1\" is already in use by container \"ed2efdc806c1883954e677eb9ab8cbc7e286c9c5934ef6724fd5d93c56744923\". You have to remove (or rename) that container to be able to reuse that name."}
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
```

**- Description for the changelog**

```Markdown
Fix API returning 400 status code instead of 409 for conflicting container names [moby/moby#35022](https://github.com/moby/moby/pull/35022)
```

ping @cpuguy83 PTAL

### CODE REVIEW

**Review by boaz0 — APPROVED** [review]
LGTM :+1:

File: daemon/errors.go [hunk 1]
```diff
@@ -64,6 +64,20 @@ func errExecPaused(id string) error {
 	return stateConflictError{cause}
 }
 
+type conflictError struct {
```
Comment (cpuguy83) [inline daemon/errors.go]: Maybe we can use a dedicated error for name conflict instead of introducing a new generic conflict?

**Comment by thaJeztah** [comment]
Updated, PTAL

File: daemon/names.go [hunk 2]
```diff
@@ -69,7 +69,7 @@ func (daemon *Daemon) reserveName(id, name string) (string, error) {
 				logrus.Errorf("got unexpected error while looking up reserved name: %v", err)
 				return "", err
 			}
-			return "", validationError{errors.Errorf("Conflict. The container name %q is already in use by container %q. You have to remove (or rename) that container to be able to reuse that name.", name, id)}
+			return "", nameConflictError{errors.Errorf("Conflict. The container name %q is already in use by container %q. You have to remove (or rename) that container to be able to reuse that name.", name, id)}
```
Comment (cpuguy83) [inline daemon/names.go]: Almost, but we don't need the wrapped `errors.Errorf` here.
We can generate the message in the `Error()` function and store the conflicting name and ID in the error struct.

Comment (thaJeztah) [reply daemon/names.go]: Ah! Got it; wasn't sure to what extend you wanted to differentiate from a plain conflictError

**Review by cpuguy83 — APPROVED** [review]
LGTM!

**Review by yongtang — APPROVED** [review]
LGTM, Thanks!
