### PR TITLE
Validate volume names for the local driver.

### LINKED ISSUE #16132: Volumes: relative host-path creates named volumes
While reviewing a PR (https://github.com/docker/docker/pull/16100#issuecomment-138455740), I discovered that using a *relative* path as host path, will create a named volume, instead of erroring out or creating a bind-mounted volume.

To reproduce;

```bash
docker run -v ./:/foobar ubuntu
```

Then inspect the container;

    "Mounts": [
        {
            "Name": "./",
            "Source": "/var/lib/docker/volumes/_data",
            "Destination": "/foobar",
            "Driver": "local",
            "Mode": "z",
            "RW": true
        }
    ],

From the inspect, it's visible that a volume named `"./"` is created

Note that using `-v ~/:/foobar` *does work*;

    "Mounts": [
        {
            "Source": "/root",
            "Destination": "/foobar",
            "Mode": "",
            "RW": true
        }
    ],

**Expected result**

Docker producing an error

I think we should (at least, for now) only allow `[a-zA-Z0-9][a-zA-Z0-9_.-]+` for volume-names, anything else should produce an error.

**Actual result**

Docker created a volume named `"./"`

docker version
```
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   8562c42
 Built:        Sat Sep  5 12:34:19 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   8562c42
 Built:        Sat Sep  5 12:34:19 UTC 2015
 OS/Arch:      linux/amd64
```

docker info
```
Containers: 16
Images: 579
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 620
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-61-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 994 MiB
Name: [REDACTED]
ID: [REDACTED]
```

### PR DESCRIPTION
**Pull request by calavera**
Closes #16132
Closes #16140

### CODE REVIEW

**Comment by tiborvass** [comment]
LGTM

File: volume/local/local_test.go [hunk 1]
```diff
@@ -79,3 +79,45 @@ func TestInitializeWithVolumes(t *testing.T) {
...
+		{"name", true},
+		{"name-with-dash", true},
+		{"name_with_underscore", true},
+		{"name/with/slash", false},
+		{"name/with/../../slash", false},
+		{"./name", false},
+		{"../name", false},
+		{"./", false},
+		{"../", false},
+		{"~", false},
```
Comment (cpuguy83) [inline volume/local/local_test.go]: This case is going to fail - http://play.golang.org/p/AuXgGnTXTd

**Comment by tiborvass** [comment]
not fond of having it in `utils` package, but since we need this for 1.9 it's fine for now.

File: volume/local/local_test.go (hunk 1 above)
Comment (calavera) [inline volume/local/local_test.go]: I changed the regexp to match the container names, this should work now.

File: volume/local/local_test.go [hunk 2]
```diff
@@ -79,3 +79,46 @@ func TestInitializeWithVolumes(t *testing.T) {
...
+		"name-with-dash":        true,
+		"name_with_underscore":  true,
+		"name/with/slash":       false,
+		"name/with/../../slash": false,
+		"./name":                false,
+		"../name":               false,
+		"./":                    false,
+		"../":                   false,
+		"~":                     false,
+		".":                     false,
```
Comment (cpuguy83) [inline volume/local/local_test.go]: How about `..`?
Possible `...`?

**Comment by vdemeester** [comment]
@calavera Why the `utils` package ? It's only related to package `volume` for now right ; so it could be in the `volume` package. As @tiborvass not fond of a `utils` package.. you can put anything in there :stuck_out_tongue_closed_eyes:.

**Comment by calavera** [comment]
I'm not fond of that package either, that's not the only file there, fwiw, we already have a bunch of things in that utils package. I'm open to suggestions but I didn't want to introduce a new package only for this.

File: volume/local/local_test.go (hunk 2 above)
Comment (calavera) [inline volume/local/local_test.go]: the regular expression doesn't allow anything that doesn't start with `a-zA-Z0-9`, so testing that it's not a `.` covers those cases too.

Comment (cpuguy83) [inline volume/local/local_test.go]: But the test is to verify that we do indeed reject certain patterns, this should be independent of the implementation.

**Comment by vdemeester** [comment]
@calavera ohh for real.. never saw the package lol.. need to open my eyes more :smile_cat:.
Then I'm with @tiborvass, let's go with it for 1.9.0 and maybe create an issue on "cleaning / moving things out of `utils` package" :wink:

File: volume/local/local_test.go (hunk 2 above)
Comment (vdemeester) [inline volume/local/local_test.go]: I agree with @cpuguy83 :sweat_smile:

File: errors/daemon.go [hunk 3]
```diff
@@ -385,6 +385,14 @@ var (
 		HTTPStatusCode: http.StatusInternalServerError,
 	})
 
+	// ErrorCodeVolumeName is generated when the name of named volume isn't valid.
+	ErrorCodeVolumeName = errcode.Register(errGroup, errcode.ErrorDescriptor{
+		Value:          "VOLUMENAME",
+		Message:        "%s includes invalid characters for a local volume name, only %s are allowed",
+		Description:    "The name of volume is invalid",
+		HTTPStatusCode: http.StatusInternalServerError,
```
Comment (thaJeztah) [inline errors/daemon.go]: status `400 Bad request` is probably more appropriate here. 5XX errors are really for "server made a 'whoopsie'"

Comment (duglin) [inline errors/daemon.go]: either is fine because at some point (after the errcode disucssions) we'll be looking at each error and making sure it has the right status code.  But getting it to be 400 now is good :-)

**Comment by thaJeztah** [comment]
Thanks @calavera! LGTM. Only concern: how do we handle migration of existing volumes that are no longer valid?

Also: lets keep the discussion open for loosening up and being less restrictive after 1.9

**Comment by thaJeztah** [comment]
oh, after looking at the error code that is (no real show-stopper, but `4XX` seems more appropriate)

File: volume/local/local_test.go (hunk 2 above)
Comment (calavera) [inline volume/local/local_test.go]: I just added those tests. Can you take another look?

**Comment by tiborvass** [comment]
thanks for addressing the issues @calavera

**Comment by cpuguy83** [comment]
Will run these tests locally

**Comment by thaJeztah** [comment]
Added impact/changelog; do we need a mention in "deprecations" to tell people that some volume names are no longer valid?

**Comment by cpuguy83** [comment]
Tests are good locally.
LGTM

@thaJeztah for the merge if docs are needed.

**Comment by thaJeztah** [comment]
@calavera I think we should add a mention to https://github.com/docker/docker/blob/master/docs/misc/deprecated.md so that people are aware that this changed, wdyt?

**Comment by calavera** [comment]
@thaJeztah this is not a feature change or improvement, this is a bug fix from my point of view, it should go into the bug fixes section in the backlog.

**Comment by thaJeztah** [comment]
@calavera cool :+1:

**Comment by tiborvass** [comment]
Removing impact/changelog since `volume` top level command is introduced in 1.9
