### PR TITLE
Check tmpfs mounts before create anon volume

### LINKED ISSUE #40446: --tmpfs creates and mounts anonymous volume from disk instead of volume in memory
**Description**

When `docker run` is used with `--tmpfs /some/path` option to mount temporary volume, it creates anonymous volume on disk and mounts it as `/some/path`.

This is different from using `--mount type=tmpfs,dst=/some/path` which works fine and creates this volume in memory.

According to documentation at https://docs.docker.com/storage/tmpfs/ 
> Differences between --tmpfs and --mount behavior
>     The --tmpfs flag does not allow you to specify any configurable options.
>     The --tmpfs flag cannot be used with swarm services. You must use --mount

there should be no such difference whether `--tmpfs` or `--mount type=tmpfs` is used.

**Steps to reproduce the issue:**

1. No volumes at the beginning
```bash
$ docker volume ls
DRIVER              VOLUME NAME
```

2. Start container image using `--tmpsf `to mount /var/log/mysql
```
$ docker run --name trep-db-percona --mount 'src=trep-percona,dst=/var/lib/mysql' --tmpfs /var/log/mysql -e MYSQL_DATABASE=trep -e MYSQL_ROOT_PASSWORD=rootpass -e MYSQL_USER=trepuser -e MYSQL_PASSWORD=userpass -e CLUSTER_NAME=localcluster -e CLUSTER_JOIN='' -p 3306:3306 percona/percona-xtradb-cluster:5.7.16
```

3. Now docker has created two volumes: trep-percona which is as expected, and spurious anonymous volume 940d...:
```bash
$ docker volume ls
DRIVER              VOLUME NAME
local               940dca35f84957e3fe08a0b2dd5be6d0b8fc0dcbee6d087a6cc24aff637d2dcd
local               trep-percona
```

4. This anonymous volume is mounted as /var/log/mysql. Look at the Mounts node, there is twice "Type": "volume":

```bash
$ docker inspect trep-db-percona 
```
```json
[
    {
        "Id": "001be99d0c5dd3fc2277cb09771acb5826ee6c82534ace93c1f307f012629cba",
        "Created": "2020-02-02T11:36:34.203735533Z",
        "Path": "/entrypoint.sh",
        "Args": [
            ""
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 12508,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2020-02-02T11:36:34.856434235Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:2d5de32cddebb77eac95cad23ac3045aaf99dedaa0f74f09019061a512dc5bbf",
        "ResolvConfPath": "/var/lib/docker/containers/001be99d0c5dd3fc2277cb09771acb5826ee6c82534ace93c1f307f012629cba/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/001be99d0c5dd3fc2277cb09771acb5826ee6c82534ace93c1f307f012629cba/hostname",
        "HostsPath": "/var/lib/docker/containers/001be99d0c5dd3fc2277cb09771acb5826ee6c82534ace93c1f307f012629cba/hosts",
        "LogPath": "/var/lib/docker/containers/001be99d0c5dd3fc2277cb09771acb5826ee6c82534ace93c1f307f012629cba/001be99d0c5dd3fc2277cb09771acb5826ee6c82534ace93c1f307f012629cba-json.log",
        "Name": "/trep-db-percona",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "3306/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "3306"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "Tmpfs": {
                "/var/log/mysql": ""
            },
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "Mounts": [
                {
                    "Type": "volume",
                    "Source": "trep-percona",
                    "Target": "/var/lib/mysql"
                }
            ],
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/a184bab89b50587f42194a1f9ce51f52f667c55e27f1bf0295161525a90826a8-init/diff:/var/lib/docker/overlay2/b721cb2047012b7f9ead3ca7dbef04b98aa982ca354a60b4c8d6d35340d79673/diff:/var/lib/docker/overlay2/c8ff30c15d6770ce2c60196030106de2560516e2c1883f30c5210dcddc3dea33/diff:/var/lib/docker/overlay2/5267303d676febb172d628ad62d509194d1510e04c26eea1bd5dc0e0a76a4d1f/diff:/var/lib/docker/overlay2/dac179a6577374d5291f58c39a79eb9122bc2069f76389704af1f23ee407f6e4/diff:/var/lib/docker/overlay2/c21470ea680355990a11526b0994b7d64f6ed1db8cd783331736db0ddbbb5b90/diff:/var/lib/docker/overlay2/9c76c7d80ee9b82bc560457292c57844255e6ce806190aa039ed520eb0b0a46a/diff:/var/lib/docker/overlay2/945e7c7bc01e93b8f862c09b0f6442046ecd82205348a10975846c4f2b145830/diff:/var/lib/docker/overlay2/d5b4e672b7572fc50ea15d37b51b35daa2f6ba86654dcd7f724ff1f385ff0fec/diff:/var/lib/docker/overlay2/69575327f04553bb9dbe82d90a20276188a019c7cdb45d7c6ad8d35832af4ebf/diff:/var/lib/docker/overlay2/23dd2c8cc18fba4a3e3298012c94d1a249a38e9cdebb05d74523003662770351/diff:/var/lib/docker/overlay2/5f3667c90f2211bf61a9ffa2af1b9552e3d877bf1b1fd0e7b3d5e4690740ccc9/diff:/var/lib/docker/overlay2/2b298cd82f4d9d869dae9538a8d19d213f9a7678e7cee3fdc719dc4b13133343/diff:/var/lib/docker/overlay2/41c757520c684e454920b1664ff592893ace1cd14152ce1c4ad5c60c1e40b407/diff",
                "MergedDir": "/var/lib/docker/overlay2/a184bab89b50587f42194a1f9ce51f52f667c55e27f1bf0295161525a90826a8/merged",
                "UpperDir": "/var/lib/docker/overlay2/a184bab89b50587f42194a1f9ce51f52f667c55e27f1bf0295161525a90826a8/diff",
                "WorkDir": "/var/lib/docker/overlay2/a184bab89b50587f42194a1f9ce51f52f667c55e27f1bf0295161525a90826a8/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "volume",
                "Name": "trep-percona",
                "Source": "/var/lib/docker/volumes/trep-percona/_data",
                "Destination": "/var/lib/mysql",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "940dca35f84957e3fe08a0b2dd5be6d0b8fc0dcbee6d087a6cc24aff637d2dcd",
                "Source": "/var/lib/docker/volumes/940dca35f84957e3fe08a0b2dd5be6d0b8fc0dcbee6d087a6cc24aff637d2dcd/_data",
                "Destination": "/var/log/mysql",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "001be99d0c5d",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "3306/tcp": {},
                "4567/tcp": {},
                "4568/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "MYSQL_PASSWORD=userpass",
                "CLUSTER_NAME=localcluster",
                "CLUSTER_JOIN=",
                "MYSQL_DATABASE=trep",
                "MYSQL_ROOT_PASSWORD=rootpass",
                "MYSQL_USER=trepuser",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "PERCONA_MAJOR=5.7",
                "PERCONA_VERSION=5.7.16-27.19-1.jessie",
                "DEBIAN_FRONTEND=noninteractive"
            ],
            "Cmd": [
                ""
            ],
            "Image": "percona/percona-xtradb-cluster:5.7.16",
            "Volumes": {
                "/var/lib/mysql": {},
                "/var/log/mysql": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "com.percona.package": "Percona XtraDB Cluster",
                "com.percona.version": "5.7",
                "vendor": "Percona"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "3812e62c95f9c868fb5ffdb56dce8661c10a149125299ba806d6245e27eb1c97",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "3306/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "3306"
                    }
                ],
                "4567/tcp": null,
                "4568/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/3812e62c95f9",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "31d98c46bcb8bdec240515f46bb9a8f4e3ed1d914c9b7a39037b3c013dd9fa83",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "1039099e8c44a91de63141f315ee1ba3cbb43b29fdeb09510c98c0452ad94e9f",
                    "EndpointID": "31d98c46bcb8bdec240515f46bb9a8f4e3ed1d914c9b7a39037b3c013dd9fa83",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]
```
**Describe the results you received:**
I noticed that temporary mount is backed by on-disk volume.

**Describe the results you expected:**
I expected temporary mount to be backed by in-memory volume. 

**Additional information you deem important:**

The same operation but performed with `--mount type=tmpfs` gives correct results:

1. No volumes at the beginning:
```bash
docker volume ls
DRIVER              VOLUME NAME
```

2. Start container, this time I will use `--mount type=tmpfs` option to mount /var/log/mysql volume:
```bash
docker run --name trep-db-percona --mount 'src=trep-percona,dst=/var/lib/mysql' --mount 'type=tmpfs,dst=/var/log/mysql' -e MYSQL_DATABASE=trep -e MYSQL_ROOT_PASSWORD=rootpass -e MYSQL_USER=trepuser -e MYSQL_PASSWORD=userpass -e CLUSTER_NAME=localcluster -e CLUSTER_JOIN='' -p 3306:3306 percona/percona-xtradb-cluster:5.7.16
```

3. Now, there is only one named container as expected:
```bash
docker volume ls
DRIVER              VOLUME NAME
local               trep-percona
```

4. And outcome of `docker container inspect` is different. Notice that in Mounts node there is one "Type": "volume" item and one "Type": "tmpfs" item:
```bash
$ docker inspect trep-db-percona 
```
```json
[
    {
        "Id": "3f867d862f7aaacd6555e695667b7773843df66aa1a0788392897bc31c375427",
        "Created": "2020-02-02T11:44:20.73903035Z",
        "Path": "/entrypoint.sh",
        "Args": [
            ""
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 13329,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2020-02-02T11:44:21.453368745Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:2d5de32cddebb77eac95cad23ac3045aaf99dedaa0f74f09019061a512dc5bbf",
        "ResolvConfPath": "/var/lib/docker/containers/3f867d862f7aaacd6555e695667b7773843df66aa1a0788392897bc31c375427/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/3f867d862f7aaacd6555e695667b7773843df66aa1a0788392897bc31c375427/hostname",
        "HostsPath": "/var/lib/docker/containers/3f867d862f7aaacd6555e695667b7773843df66aa1a0788392897bc31c375427/hosts",
        "LogPath": "/var/lib/docker/containers/3f867d862f7aaacd6555e695667b7773843df66aa1a0788392897bc31c375427/3f867d862f7aaacd6555e695667b7773843df66aa1a0788392897bc31c375427-json.log",
        "Name": "/trep-db-percona",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "3306/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "3306"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "Mounts": [
                {
                    "Type": "volume",
                    "Source": "trep-percona",
                    "Target": "/var/lib/mysql"
                },
                {
                    "Type": "tmpfs",
                    "Target": "/var/log/mysql"
                }
            ],
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/3d676c5ffc09523c4cc8183e743026ec8a6563ce007e376903db9cd859f521d3-init/diff:/var/lib/docker/overlay2/b721cb2047012b7f9ead3ca7dbef04b98aa982ca354a60b4c8d6d35340d79673/diff:/var/lib/docker/overlay2/c8ff30c15d6770ce2c60196030106de2560516e2c1883f30c5210dcddc3dea33/diff:/var/lib/docker/overlay2/5267303d676febb172d628ad62d509194d1510e04c26eea1bd5dc0e0a76a4d1f/diff:/var/lib/docker/overlay2/dac179a6577374d5291f58c39a79eb9122bc2069f76389704af1f23ee407f6e4/diff:/var/lib/docker/overlay2/c21470ea680355990a11526b0994b7d64f6ed1db8cd783331736db0ddbbb5b90/diff:/var/lib/docker/overlay2/9c76c7d80ee9b82bc560457292c57844255e6ce806190aa039ed520eb0b0a46a/diff:/var/lib/docker/overlay2/945e7c7bc01e93b8f862c09b0f6442046ecd82205348a10975846c4f2b145830/diff:/var/lib/docker/overlay2/d5b4e672b7572fc50ea15d37b51b35daa2f6ba86654dcd7f724ff1f385ff0fec/diff:/var/lib/docker/overlay2/69575327f04553bb9dbe82d90a20276188a019c7cdb45d7c6ad8d35832af4ebf/diff:/var/lib/docker/overlay2/23dd2c8cc18fba4a3e3298012c94d1a249a38e9cdebb05d74523003662770351/diff:/var/lib/docker/overlay2/5f3667c90f2211bf61a9ffa2af1b9552e3d877bf1b1fd0e7b3d5e4690740ccc9/diff:/var/lib/docker/overlay2/2b298cd82f4d9d869dae9538a8d19d213f9a7678e7cee3fdc719dc4b13133343/diff:/var/lib/docker/overlay2/41c757520c684e454920b1664ff592893ace1cd14152ce1c4ad5c60c1e40b407/diff",
                "MergedDir": "/var/lib/docker/overlay2/3d676c5ffc09523c4cc8183e743026ec8a6563ce007e376903db9cd859f521d3/merged",
                "UpperDir": "/var/lib/docker/overlay2/3d676c5ffc09523c4cc8183e743026ec8a6563ce007e376903db9cd859f521d3/diff",
                "WorkDir": "/var/lib/docker/overlay2/3d676c5ffc09523c4cc8183e743026ec8a6563ce007e376903db9cd859f521d3/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "volume",
                "Name": "trep-percona",
                "Source": "/var/lib/docker/volumes/trep-percona/_data",
                "Destination": "/var/lib/mysql",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "tmpfs",
                "Source": "",
                "Destination": "/var/log/mysql",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "3f867d862f7a",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "3306/tcp": {},
                "4567/tcp": {},
                "4568/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "MYSQL_PASSWORD=userpass",
                "CLUSTER_NAME=localcluster",
                "CLUSTER_JOIN=",
                "MYSQL_DATABASE=trep",
                "MYSQL_ROOT_PASSWORD=rootpass",
                "MYSQL_USER=trepuser",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "PERCONA_MAJOR=5.7",
                "PERCONA_VERSION=5.7.16-27.19-1.jessie",
                "DEBIAN_FRONTEND=noninteractive"
            ],
            "Cmd": [
                ""
            ],
            "Image": "percona/percona-xtradb-cluster:5.7.16",
            "Volumes": {
                "/var/lib/mysql": {},
                "/var/log/mysql": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "com.percona.package": "Percona XtraDB Cluster",
                "com.percona.version": "5.7",
                "vendor": "Percona"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "b74c2e1574f15469dad342656a0f9399ad08125b8c8f86e27b843faf85dae516",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "3306/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "3306"
                    }
                ],
                "4567/tcp": null,
                "4568/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/b74c2e1574f1",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "95cf908558e6b9787e7367f6b5aed2d5794c0204c88253ab3e332ba67daed5c9",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "1039099e8c44a91de63141f315ee1ba3cbb43b29fdeb09510c98c0452ad94e9f",
                    "EndpointID": "95cf908558e6b9787e7367f6b5aed2d5794c0204c88253ab3e332ba67daed5c9",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 1
  Paused: 0
  Stopped: 3
 Images: 44
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-76-generic
 Operating System: Linux Mint 19.3
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.28GiB
 Name: Cichacz
 ID: 5CM2:ZEGS:V4VP:B65E:P7VO:VVX5:LT6R:73PD:LKQS:OGVH:F6KE:AFAX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by cpuguy83**
This makes sure that things like `--tmpfs` mounts over an anonymous
volume don't create volumes unnecessarily.
One method only checks mountpoints, the other checks both mountpoints
and tmpfs... the usage of these should likely be consolidated.

Ideally, processing for `--tmpfs` mounts would get merged in with the
rest of the mount parsing. I opted not to do that for this change so the
fix is minimal and can potentially be backported with fewer changes of
breaking things.
Merging the mount processing for tmpfs can be handled in a followup.

Fixes #40446

### CODE REVIEW

File: integration/container/create_test.go [hunk 1]
```diff
@@ -534,3 +534,40 @@ func TestCreateWithInvalidHealthcheckParams(t *testing.T) {
...
+// https://github.com/moby/moby/issues/40446
+func TestCreateTmpfsOverrideAnonymousVolume(t *testing.T) {
+	skip.If(t, testEnv.DaemonInfo.OSType == "windows", "windows does not support tmpfs")
+	defer setupTest(t)()
+	client := testEnv.APIClient()
+	ctx := context.Background()
+
+	id := ctr.Create(ctx, t, client,
+		ctr.WithVolume("/foo"),
+		ctr.WithTmpfs("/foo"),
```
Comment (thaJeztah) [inline integration/container/create_test.go]: Can you add a case where the tpmfs has `:options` set?

File: integration/container/create_test.go [hunk 2]
```diff
@@ -534,3 +534,40 @@ func TestCreateWithInvalidHealthcheckParams(t *testing.T) {
...
+		ctr.WithCmd("/bin/sh", "-c", "mount | grep '/foo' | grep tmpfs"),
+	)
+
+	inspect, err := client.ContainerInspect(ctx, id)
+	assert.NilError(t, err)
+	// tmpfs do not currently get added to inspect.Mounts
```
Comment (thaJeztah) [inline integration/container/create_test.go]: Should we create a tracking issue to convert them to the new API?

**Review by thaJeztah — CHANGES_REQUESTED** [review]

File: integration/container/create_test.go (hunk 1 above)
Comment (cpuguy83) [reply integration/container/create_test.go]: Udated.

File: integration/container/create_test.go (hunk 2 above)
Comment (cpuguy83) [reply integration/container/create_test.go]: https://github.com/moby/moby/issues/40454

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Comment by mkobylarz** [comment]
Thank you, @cpuguy83 !

**Review by AkihiroSuda — APPROVED** [review]

**Comment by AkihiroSuda** [comment]
Needs cherry-pick?

**Comment by raffig** [comment]
Thanks @cpuguy83!

**Comment by cpuguy83** [comment]
Cherry-pick PR https://github.com/moby/moby/pull/40477
