### PR TITLE
Disable HTML escaping for JSON in formatter

### LINKED ISSUE #32120: docker container ls --format="{{ json .Ports }}" incorrectly encoding \u003e instead of ">"
Discovered format={{ json . }}
https://docs.docker.com/engine/admin/formatting/#json

The port mappings are incorrectly [en|de]coded

E.g.
```
"0.0.0.0:8080-\u003e8080/tcp"
```
Instead of
```
"0.0.0.0:8080->8080/tcp"
```
**Repro**

```
docker container ls --format="{{ json .Ports }}"
docker ps --format="{{ json .Ports }}
```

**Describe the results you received:**

String include unicode (`\u003e`) instead of "`>`"
```
"0.0.0.0:9000-\u003e9000/tcp"
"0.0.0.0:8080-\u003e8080/tcp"
```

**Describe the results you expected:**

jq works as expected
```
docker container ls --format="{{ json . }}" | jq .Ports
"0.0.0.0:9000->9000/tcp"
"0.0.0.0:8080->8080/tcp"
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
docker info
Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 16
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 118
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: [REDACTED]
 Is Manager: true
 ClusterID: [REDACTED]
 Managers: 1
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.1.156
 Manager Addresses:
  192.168.1.156:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-66-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.31 GiB
Name: [REDACTED]
ID: [REDACTED]
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: [REDACTED]
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by boaz0**
closes #32120 

**- What I did**
Marshal values to JSON without HTML escaping characters such as `<` and `>`. 

**- How I did it**
I set HTML escaping in the JSON encoder to `false` using `SetEscapeHTML`.

This is very similar to https://github.com/docker/docker/pull/27139/commits/d1d505fa701bfe28a59afee8158994cf33ef043c and https://github.com/docker/docker/pull/27060/commits/0fa20ad13b0b5c6d1bf8a8285717c07697d079ba.

**- How to verify it**
```bash
$ TESTDIRS='pkg/templates' TESTFLAGS='-test.run ^TestParseJSONFunctions$' hack/make.sh test-unit
```

### CODE REVIEW

**Review by vdemeester — COMMENTED** [review]
/cc @AkihiroSuda @cpuguy83 @dnephin @runcom @icecrime 
This would mean dropping go 1.6 support

**Review by dnephin — APPROVED** [review]
LGTM

File: integration-cli/docker_cli_ps_test.go [hunk 1]
```diff
@@ -643,6 +643,16 @@ func (s *DockerSuite) TestPsDefaultFormatAndQuiet(c *check.C) {
 	c.Assert(id, checker.HasPrefix, strings.TrimSpace(out), check.Commentf("Expected to print only the container id, got %v\n", out))
 }
 
+// #32120
+func (s *DockerSuite) TestPsPortsJSON(c *check.C) {
+	dockerCmd(c, "run", "-d", "--name", "ps_json_ports_1", "-p", "9787:9787", "busybox", "top")
+	dockerCmd(c, "run", "-d", "--name", "ps_json_ports_2", "-p", "9788:9788", "busybox", "top")
+	out, _ := dockerCmd(c, "ps", "--format", "{{json .Ports}}")
+	expected := "\"0.0.0.0:9788->9788/tcp\"\n\"0.0.0.0:9787->9787/tcp\"\n"
```
Comment (AkihiroSuda) [inline integration-cli/docker_cli_ps_test.go]: Do we guarantee this sorting order?

Comment (ripcurld0) [inline integration-cli/docker_cli_ps_test.go]: @AkihiroSuda no we don't. I will fix that. 😊 
Thanks for the helpful feedback.

**Comment by thaJeztah** [comment]
If we don't want to drop Go 1.6; a similar approach as https://github.com/docker/docker/pull/27139 could be considered

**Comment by justincormack** [comment]
Go 1.6 is out of security support now, so i think we could drop support.

**Comment by ripcurld0** [comment]
power-pc failed due to [this](https://github.com/docker/docker/issues/32159) flaky test and windows failed due to an infra(?) problem:
```bash
re-exec error: exit status 1: output: BackupWrite 
      \\?\D:\CI\CI-0954488c8\daemon\windowsfilter\8c0[...]4a9\Files\Windows\SysWOW64\d3d11.dll:
      There is not enough space on the disk.
```

**Review by thaJeztah — APPROVED** [review]
LGTM
