### PR TITLE
Need to create bind mount volume if it does not exist.

### LINKED ISSUE #17262: Docker volumes using the :z or :Z flag don't create the folder on the dockerd host
I have a bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1274210 that is reporting that SELinux volume options "z" & "Z" do not act the same way as "ro", "rw".  In that if  you specify a non existent directory
in the docker run/create command, docker creates the directory when using "ro", "rw", while it fails with an error in the "z", "Z" case.

I believe that creating the directory in the case of bind mounts is a bug, since this could lead to unexpected behaviour and even leave users confused when they have a simple typo.

docker run -v /var/lib/mariedb:/var/lib/mariadb ... 

For example could potentially end up with a directory on the host that was not expected.  Forcing the user to do a `mkdir /var/lib/mariadb` does not seem to onerous. 

If the "ro"/"rw" behaviour is the expected, I will submit a patch to fix the SELinux issues.

### PR DESCRIPTION
**Pull request by rhatdan**
In order to be consistent on creation of volumes for bind mounts
we need to create the source directory if it does not exist and the
user specified he wants it relabeled.

Can not do this lower down the stack, since we are not passing in the
mode fields.

Fixes #17262

Signed-off-by: Dan Walsh dwalsh@redhat.com

### CODE REVIEW

**Comment by rhatdan** [comment]
Fixes https://github.com/docker/docker/issues/17262

**Comment by runcom** [comment]
ping @cpuguy83

File: daemon/volumes.go [hunk 1]
```diff
@@ -138,6 +139,14 @@ func (daemon *Daemon) registerMountPoints(container *container.Container, hostCo
 		}
 
 		if label.RelabelNeeded(bind.Mode) {
+			if _, err := os.Stat(bind.Source); err != nil {
```
Comment (crosbymichael) [inline daemon/volumes.go]: You can skip the stat and just mkdirall on the source.  It will not error if it already exists right?

Comment (rhatdan) [inline daemon/volumes.go]: This code was taken from the volume.go.  If MkdirAll, according to the comment there.

```
	// system.MkdirAll() produces an error if m.Source exists and is a file (not a directory),
	// so first check if the path does not exist
```
So I guess if you volume mount a directory over a file, this could cause an issue.

**Comment by rhatdan** [comment]
Fixed to remove os.Status call, but still handle the case where the source is file and not a directory.

File: daemon/volumes.go (hunk 1 above)
Comment (thaJeztah) [inline daemon/volumes.go]: Ah, yes, tripped over that one (also thought the stat was redundant), so I added that comment.
If the same comment applies here; could you add that comment here as well, to prevent others from tripping over it?

**Comment by rhatdan** [comment]
@thaJeztah I don't think we need the comment any longer if the current patch is approved.  Basically do the MkdirsPath and only report error if !ENOTDIR.  So that files can be volume mounted in.  If everyone approves we could make same change in volume.go and eliminate the stat.

**Comment by thaJeztah** [comment]
nice! yes, definitely

**Comment by crosbymichael** [comment]
LGTM

**Comment by cpuguy83** [comment]
This is now creating in two places.
Also mode should be available where we are currently doing the creation.

File: daemon/volumes.go [hunk 2]
```diff
@@ -138,6 +139,13 @@ func (daemon *Daemon) registerMountPoints(container *container.Container, hostCo
 		}
 
 		if label.RelabelNeeded(bind.Mode) {
+			if err := os.MkdirAll(bind.Source, 0755); err != nil {
```
Comment (cpuguy83) [inline daemon/volumes.go]: Why `os` instead of `system`?

Comment (rhatdan) [inline daemon/volumes.go]: Os was already imported, system was not and after reading system, it looked like it just called os, but I have no problem switching to it, if you want.  What does system do that os does not?

**Comment by rhatdan** [comment]
Combined the two code paths together.  But I had to pass in the MountLabel to m.Setup(). Other option would be to add mounLabel to the MountPoint Struct?  @cpuguy83 would you prefer that?

**Comment by cpuguy83** [comment]
LGTM
