### PR TITLE
c8d/history: Fix non-native platforms

### LINKED ISSUE #50851: docker history for freshly built image on non-native platform fails with snapshot does not exist
### Description

It seems like `docker history` is now failing on some Apple Silicon Macs when dealing with cross platform image builds.

It does not affect every cross-platform build on macOS, but it seems like factory resetting Docker does not fix it.

### Reproduce

```bash
$ cat > Dockerfile <<EOF
FROM alpine:latest
RUN true
EOF

$ docker build --platform linux/amd64 --tag foo .
# ...

$ docker history foo
Error response from daemon: NotFound: snapshot sha256:4255a31fce07994aab3563b4c65ac4159547cdacf72916e1528f4a4fcc97ab97 does not exist: not found

$ docker history --platform linux/amd64 foo
Error response from daemon: NotFound: snapshot sha256:4255a31fce07994aab3563b4c65ac4159547cdacf72916e1528f4a4fcc97ab97 does not exist: not found
```

### Expected behavior

`docker history` should not fail.

### docker version

```bash
Client:
 Version:           28.3.2
 API version:       1.51
 Go version:        go1.24.5
 Git commit:        578ccf6
 Built:             Wed Jul  9 16:12:57 2025
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.44.3 (202357)
 Engine:
  Version:          28.3.2
  API version:      1.51 (minimum version 1.24)
  Go version:       go1.24.5
  Git commit:       e77ff99
  Built:            Wed Jul  9 16:13:56 2025
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.7.27
  GitCommit:        05044ec0a9a75232cad458027ca83437aae3f4da
 runc:
  Version:          1.2.5
  GitCommit:        v1.2.5-0-g59923ef
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    28.3.2
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  ai: Docker AI Agent - Ask Gordon (Docker Inc.)
    Version:  v1.9.11
    Path:     /Users/josh/.docker/cli-plugins/docker-ai
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.26.1-desktop.1
    Path:     /Users/josh/.docker/cli-plugins/docker-buildx
  cloud: Docker Cloud (Docker Inc.)
    Version:  v0.4.18
    Path:     /Users/josh/.docker/cli-plugins/docker-cloud
  compose: Docker Compose (Docker Inc.)
    Version:  v2.39.1-desktop.1
    Path:     /Users/josh/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.42
    Path:     /Users/josh/.docker/cli-plugins/docker-debug
  desktop: Docker Desktop commands (Docker Inc.)
    Version:  v0.2.0
    Path:     /Users/josh/.docker/cli-plugins/docker-desktop
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.29
    Path:     /Users/josh/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.4.0
    Path:     /Users/josh/.docker/cli-plugins/docker-init
  mcp: Docker MCP Plugin (Docker Inc.)
    Version:  v0.13.0
    Path:     /Users/josh/.docker/cli-plugins/docker-mcp
  model: Docker Model Runner (EXPERIMENTAL) (Docker Inc.)
    Version:  v0.1.36
    Path:     /Users/josh/.docker/cli-plugins/docker-model
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/josh/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.18.2
    Path:     /Users/josh/.docker/cli-plugins/docker-scout

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 28.3.2
 Storage Driver: overlayfs
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 CDI spec directories:
  /etc/cdi
  /var/run/cdi
 Discovered Devices:
  cdi: docker.com/gpu=webgpu
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
```

### Additional Info

This is on an Apple Silicon MacBook running macOS Sequoia 15.6.1.

It is reproducible even after uninstalling and reinstalling Docker Desktop.

### PR DESCRIPTION
**Pull request by vvoland**
- fixes: https://github.com/moby/moby/issues/50851

When building a non-native platform, it's not unpacked by default.
History tries to read the disk usage of all the layer and it doesn't handle missing snapshots gracefully. 
This patch fixes this.        

```markdown changelog
containerd image store: Fix `docker history` failing with `snapshot X does not exist` when calling on a non-native image that was built locally
```

### CODE REVIEW

**Comment by vvoland** [comment]
FWIW, I think `history` should show the size of the distributable layers, not the unpacked snapshot size. I will open a follow up PR with a proposal.

**Comment by thaJeztah** [comment]
Looks like we still have the check for the alias in place; causing linting to fail;

```
daemon/containerd/image_history.go:9:2: import "github.com/containerd/errdefs" imported without alias but must be with alias "cerrdefs" according to config (importas)
	"github.com/containerd/errdefs"
	^
```

File: integration/internal/build/build.go [hunk 1]
```diff
@@ -43,10 +41,18 @@ func GetImageIDFromBody(t *testing.T, body io.Reader) string {
...
+		var br build.Result
+		if err := json.Unmarshal(*jm.Aux, &br); err == nil {
+			if br.ID == "" {
+				continue
+			}
+			id = br.ID
+			break
+		}
 	}
 	io.Copy(io.Discard, body)
```
Comment (thaJeztah) [inline integration/internal/build/build.go]: If you still need to update; while we're updating; perhaps also explicitly discard the error;

```go
	_, _ = io.Copy(io.Discard, body)
```

File: integration/internal/build/build.go [hunk 2]
```diff
@@ -29,12 +29,10 @@ func Do(ctx context.Context, t *testing.T, apiClient client.APIClient, buildCtx
 
 // GetImageIDFromBody reads the image ID from the build response body.
 func GetImageIDFromBody(t *testing.T, body io.Reader) string {
-	var (
-		jm  jsonmessage.JSONMessage
-		br  build.Result
-		dec = json.NewDecoder(body)
-	)
+	var id string
+	dec := json.NewDecoder(body)
```
Comment (thaJeztah) [inline integration/internal/build/build.go]: Not for this PR, but this is one of the cases where we need to look what type to use; this is produced by https://github.com/moby/moby/blob/578ce11a56f566c607b56f1e10ebeeb400024f98/api/pkg/streamformatter/streamformatter.go#L17-L22

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by vvoland** [comment]
Huh, looks like the test fails on regular `test-integration`:
https://github.com/moby/moby/actions/runs/17381769258/job/49340781652?pr=50867#step:7:2546

but passes on both explicit graphdriver & snapshotter test-integrations:
https://github.com/moby/moby/actions/runs/17381769251/job/49340824197?pr=50867#step:8:2190

**Comment by vvoland** [comment]
Oh, looks like the `arm64 test-integration` doesn't setup the qemu, so it's not able to build a non-native image:
```
exec /bin/sh: exec format error
```

Trying out with `docker/setup-qemu-action@v3`, if it doesn't work, I'll just skip it when running this workflow

**Review by austinvazquez — APPROVED** [review]
LGTM
