### PR TITLE
try to modprobe bridge

### LINKED ISSUE #12177: Docker installation script sometimes doesn't work (Ubuntu)
I just experimented that after provisioning an Ubuntu 14.04 VM on cloud providers like Azure or Google, running the documented official installation command

    sudo wget -qO- https://get.docker.com/ | sh

gets stuck at installation step and **does not always successfully start docker daemon**. 

Impact looks like as follows:

* Out of 15 newly provisioned Azure VMs, 3 got stuck installing docker.
* Out of 200 newly provisioned GCE VMs, 3 got stuck installing docker.
* This is probably also causing provisioning problems in docker-machine as it also uses the same command to install docker. (historically we've seen Azure VMs provisioned with docker-machine getting stuck at apt-get step)

## Repro:

1. Provision an Ubuntu VM VM and ssh in ASAP.
2. Run the command above before running anything else.
3. This reproes only on the first run ever after booting.

## Symptoms

**Symptom 1**: Installation output gets stuck at `sudo -E sh -c sleep 3; apt-get update; apt-get install -y -q lxc-docker` step:

```
[...]
Unpacking cgroup-lite (1.9) ...
Selecting previously unselected package lxc-docker-1.5.0.
Preparing to unpack .../lxc-docker-1.5.0_1.5.0_amd64.deb ...
Unpacking lxc-docker-1.5.0 (1.5.0) ...
Selecting previously unselected package lxc-docker.
Preparing to unpack .../lxc-docker_1.5.0_amd64.deb ...
Unpacking lxc-docker (1.5.0) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up aufs-tools (1:3.2+20130722-1.1) ...
Setting up liberror-perl (0.17-1.1) ...
Setting up git-man (1:1.9.1-1ubuntu0.1) ...
Setting up git (1:1.9.1-1ubuntu0.1) ...
Setting up cgroup-lite (1.9) ...
cgroup-lite start/running
Setting up lxc-docker-1.5.0 (1.5.0) ...

<--(get stuck here forever)
```

**Symptom 2**: `pstree -u -a`, it appears that `start docker` got stuck and **hangs forever**.

```
$ pstree -u -a
init
[...]
  ├─sshd -D
  │   ├─sshd
  │   │   └─sshd,alp
  │   │       └─bash -c time sudo wget -qO- https://get.docker.com/ | sh
  │   │           └─sh
  │   │               └─sudo,root -E sh -c sleep 3; apt-get update; apt-get install -y -q lxc-docker
  │   │                   └─sh -c sleep 3; apt-get update; apt-get install -y -q lxc-docker
  │   │                       └─apt-get install -y -q lxc-docker
  │   │                           └─dpkg --status-fd 24 --configure aufs-tools:amd64 liberror-perl:all git-man:all git:amd64 cgroup-lite:all lxc-docker-1.5.0:amd64 lxc-docker:amd64
  │   │                               └─lxc-docker-1.5. /var/lib/dpkg/info/lxc-docker-1.5.0.postinst configure
  │   │                                   └─start docker
  │   └─sshd
  │       └─sshd,alp
  │           └─bash
  │               └─pstree -u -a
[...]
  ├─systemd-udevd --daemon
  ├─upstart-file-br --daemon
  ├─upstart-socket- --daemon
  └─upstart-udev-br --daemon
```

**Symptom 3**:  `sudo cat /var/log/upstart/docker.log | head`. Starting docker daemon fails with different errors at different cloud providers but it keeps trying forever without any success and log file just keeps growing

> On Azure:

```sh
$ sudo cat /var/log/upstart/docker.log | head
INFO[0000] +job serveapi(unix:///var/run/docker.sock)
INFO[0000] +job init_networkdriver()
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
no such device
INFO[0000] -job init_networkdriver() = ERR (1)
FATA[0000] no such device
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
(keeps going on, no success)
```

> On GCE:

``` sh
$ sudo cat /var/log/upstart/docker.log | head
Waiting for /var/run/docker.sock
INFO[0000] +job serveapi(unix:///var/run/docker.sock)
INFO[0000] +job init_networkdriver()
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
invalid argument
INFO[0000] -job init_networkdriver() = ERR (1)
FATA[0000] invalid argument
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
```

Issue is reported earlier at boot2docker repo: 
* https://github.com/boot2docker/boot2docker/issues/745
* https://github.com/boot2docker/boot2docker/issues/713

I will now test it with `test.docker.com` instead of `get.docker.com` and measure its success rate as well.

cc: @jfrazelle @johngossman @SvenDowideit @ehazlett

### PR DESCRIPTION
**Pull request by jessfraz**
fix #12177

### CODE REVIEW

File: daemon/networkdriver/bridge/driver.go [hunk 1]
```diff
@@ -113,6 +114,11 @@ func InitDriver(config *Config) error {
 		addrsv6    []net.Addr
 		bridgeIPv6 = "fe80::1/64"
 	)
+
+	// try to modprobe bridge first
+	// see gh#12177
+	exec.Command("modprobe", "bridge").Run()
```
Comment (LK4D4) [inline daemon/networkdriver/bridge/driver.go]: how about `nf_nat`?

Comment (jfrazelle) [inline daemon/networkdriver/bridge/driver.go]: why not? I will add ;)

**Comment by LK4D4** [comment]
LGTM

**Comment by gossmanster** [comment]
May I suggest we also pull in some of the better error messages from https://github.com/docker/docker/pull/12300

so if it keeps happening anyway we have visibility?

And I believe  https://github.com/docker/docker/pull/11945 will handle the upstart script getting in a loop if the bridge fails again

**Comment by estesp** [comment]
I'm ok with this, I guess because we can't only fix it in upstart if this is really a consistent problem for the system state where bridge.ko isn't loaded at docker daemon start time on certain kernels/distros or whatever weird fluke is causing this in those environments.  Would be nice to solve in a clearer way, but I agree for the moment this is good enough.

LGTM

File: daemon/networkdriver/bridge/driver.go [hunk 2]
```diff
@@ -113,6 +114,11 @@ func InitDriver(config *Config) error {
 		addrsv6    []net.Addr
 		bridgeIPv6 = "fe80::1/64"
 	)
+
+	// try to modprobe bridge first
+	// see gh#12177
+	exec.Command("modprobe", "bridge", "nf_nat").Run()
```
Comment (crosbymichael) [inline daemon/networkdriver/bridge/driver.go]: maybe since this is such a weird issue that we are fixing, it might be a good idea to log the error ( along with stderr ) for this command with `logrus.Error` incase something else get weird we can see that this call failed.

Comment (jfrazelle) [inline daemon/networkdriver/bridge/driver.go]: cool

**Comment by jfrazelle** [comment]
updated

**Comment by jfrazelle** [comment]
can confirm it works on GCE with above patch

**Comment by cpuguy83** [comment]
LGTM

File: daemon/networkdriver/bridge/driver.go [hunk 3]
```diff
@@ -113,6 +114,13 @@ func InitDriver(config *Config) error {
 		addrsv6    []net.Addr
 		bridgeIPv6 = "fe80::1/64"
 	)
+
+	// try to modprobe bridge first
+	// see gh#12177
+	if out, err := exec.Command("modprobe", "bridge", "nf_nat").Output(); err != nil {
+		logrus.Errorf("Running modprobe bridge nf_nat failed with message: %s, error: %v", out, err)
```
Comment (icecrime) [inline daemon/networkdriver/bridge/driver.go]: I'd `Warnf` rather than `Errorf` but that's a nit.

**Comment by icecrime** [comment]
LGTM

File: daemon/networkdriver/bridge/driver.go (hunk 3 above)
Comment (jfrazelle) [inline daemon/networkdriver/bridge/driver.go]: Will swap tomorrow makes sense

Comment (ibuildthecloud) [inline daemon/networkdriver/bridge/driver.go]: I was testing error conditions and ran into this oddity on my machine (Ubunut 14.10).  The following prints ok

    sudo modprobe bridge asdf && echo ok

Maybe you should do two separate modprobes?

Comment (ibuildthecloud) [inline daemon/networkdriver/bridge/driver.go]: According to man, things after the modulename are arguments... I swear I've loaded multiple modules from the same command line.  Now completely lost..

File: daemon/networkdriver/bridge/driver.go [hunk 4]
```diff
@@ -113,6 +114,13 @@ func InitDriver(config *Config) error {
 		addrsv6    []net.Addr
 		bridgeIPv6 = "fe80::1/64"
 	)
+
+	// try to modprobe bridge first
+	// see gh#12177
+	if out, err := exec.Command("modprobe", "bridge", "nf_nat").Output(); err != nil {
```
Comment (DieterReuter) [inline daemon/networkdriver/bridge/driver.go]: @ibuildthecloud is absolute right.
To load the kernel modules `bridge` and `nf_nat` you have to invoke `modprobe bridge` and `modprobe nf_nat` as two seperate commands. With this implementation here only `bridge` will be loaded and the string "nf_nat" will be sent as a module option while loading the `bridge` module. 
For more details about using `modprobe` I strongly recommend to read the [man pages](http://linux.die.net/man/8/modprobe).

File: daemon/networkdriver/bridge/driver.go (hunk 3 above)
Comment (mh0rst) [inline daemon/networkdriver/bridge/driver.go]: Use the -a (insert all) option.
```
$ sudo modprobe -v -a test1 test2
libkmod: ERROR ../libkmod/libkmod.c:505 kmod_lookup_alias_from_builtin_file: could not open builtin file '/lib/modules/2.6.32-042stab092.3/modules.builtin.bin'
WARNING: Module test1 not found.
libkmod: ERROR ../libkmod/libkmod.c:505 kmod_lookup_alias_from_builtin_file: could not open builtin file '/lib/modules/2.6.32-042stab092.3/modules.builtin.bin'
WARNING: Module test2 not found.
```

Comment (jfrazelle) [inline daemon/networkdriver/bridge/driver.go]: Is this a kernel version thing because I specifically read the man pages
before doing this

Comment (jfrazelle) [inline daemon/networkdriver/bridge/driver.go]: I see modprobe modulename... But I'm on 4.0.0

Comment (jfrazelle) [inline daemon/networkdriver/bridge/driver.go]: Seeing as this worked on the GCE server to fix the problem tho I do not
think we needed nf nat then

Comment (jfrazelle) [inline daemon/networkdriver/bridge/driver.go]: I'll update in a bit

**Comment by jfrazelle** [comment]
updated ptal

**Comment by estesp** [comment]
thx @jfrazelle , with the `-a` I think the concerns around module name versus parameter is solved. **LGTM**!

**Comment by cpuguy83** [comment]
LGTM
