### PR TITLE
Lock all calls to hcsshim to prevent close races

### LINKED ISSUE #24004: Windows: StdIn being closed when the handle is no longer valid
This bug is for tracking purposes.

**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.2
 Git commit:   cccfe63
 Built:        Mon Jun 27 11:49:16 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.2
 Git commit:   cccfe63
 Built:        Mon Jun 27 11:49:16 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 7
Server Version: 1.12.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Security Options:
Kernel Version: 10.0 14367 (14367.1000.amd64fre.rs1_onecore_container_hyp.160614-1704)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 1.61 GiB
Name: WIN-V571EC4DS8B
ID: GEHF:KDWU:3MPT:EIZ6:X7CY:QO4V:5P6O:I6UQ:USWL:TBL4:ZP6C:NGOJ
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows

**Steps to reproduce the issue:**
1. docker run -i --rm windowsservercore cmd
2. >exit

**Describe the results you received:**
Error appears in log:
```
time="2016-06-27T12:50:18.678035800-07:00" level=error msg="process 6896 in container ade1ce2f92ad8d6a7d81ee428ba78a7b47a95665e39ee7590ae0e6318df6526c CloseStdin failed in Win32: The handle is invalid. (0x6)"
```

**Describe the results you expected:**
No error

### PR DESCRIPTION
**Pull request by darstahl**
closes #24004

GREEN WINDOWS CI COUNT: 10

**\- What I did**

Fixed many instances of using an invalid handle when calling into hcsshim from libcontainerd.

**\- How I did it**
- Fixed the locks used in Windows libcontainerd to keep the state of the handle in line with the stored container/process object
- Fixed a race when stopping a container. It might stop between the check if it is running and the signal to stop, so on an error stopping the container, recheck if it is running. This fix is the same as found in `Kill()`
- Used a second handle to the process to close stdin when the client side pipe is closed, so that it does not need to be synchronized with the other process modify calls

**\- How to verify it**

Running CI no longer produces invalid handle errors in the hyper-v compute logs.

**\- Description for the changelog**

Fixed invalid handle errors on Windows daemon

Signed-off-by: Darren Stahl darst@microsoft.com

### CODE REVIEW

**Comment by jhowardmsft** [comment]
Tentative LGTM pending lots of CI runs :wink:. Nice that it also fixes the deletion in the container map which as I mentioned I just found too :smile:

**Comment by darrenstahlmsft** [comment]
10 green CI runs, this is ready for review on my end :+1:

**Comment by jhowardmsft** [comment]
LGTM.

File: libcontainerd/process_windows.go [hunk 1]
```diff
@@ -63,26 +65,24 @@ func (w *delToBsWriter) Write(b []byte) (int, error) {
...
-	return stdin.Process.CloseStdin()
-}
+		// We do not need to lock container ID here, even though
+		// we are calling into hcsshim. This is safe, because the
+		// only place that closes this process handle is this method.
+		err := process.CloseStdin()
+		if err != nil && !hcsshim.IsNotExist(err) {
+			// This error will occur if the compute system is currently shutting down
+			if perr, ok := err.(*hcsshim.ProcessError); ok && perr.Err != hcsshim.ErrVmcomputeOperationInvalidState {
+				logrus.Error(err)
```
Comment (cpuguy83) [inline libcontainerd/process_windows.go]: Can we either return an error or log the error, but not both?

**Comment by cpuguy83** [comment]
ping @mlaventure

File: libcontainerd/process_windows.go (hunk 1 above)
Comment (darrenstahlmsft) [inline libcontainerd/process_windows.go]: The caller (`AttachStreams` in monitor.go) ignores errors returned from calls to `Close()`, but the errors found by logging them have proven valuable to finding bugs in this area. I'd like to have this logged somewhere. I can either change this to a Debug rather than Error, or all `Close()` errors in AttachStreams. WDYT?

File: daemon/stop.go [hunk 2]
```diff
@@ -46,9 +46,24 @@ func (daemon *Daemon) containerStop(container *container.Container, seconds int)
...
+		// its probably because its already stopped. Meaning, between
+		// the time of the IsRunning() call above and now it stopped.
+		// Also, since the err return will be environment specific we can't
+		// look for any particular (common) error that would indicate
+		// that the process is already dead vs something else going wrong.
+		// So, instead we'll give it up to 2 more seconds to complete and if
+		// by that time the container is still running, then the error
+		// we got is probably valid and so we return it to the caller.
+		if container.IsRunning() {
+			container.WaitStop(2 * time.Second)
```
Comment (mlaventure) [inline daemon/stop.go]: You could call `container.WaitStop` directly and if it returns an error, trigger a force kill.

WDYT?

Comment (darrenstahlmsft) [inline daemon/stop.go]: Yep, that makes sense. I'll make the change here and in `Kill()` (Where I found this pattern used first)

File: libcontainerd/process_windows.go (hunk 1 above)
Comment (darrenstahlmsft) [inline libcontainerd/process_windows.go]: Removed logging from here, and moved it to daemon/monitor.go. (Which previously just ignored errors)

**Comment by darrenstahlmsft** [comment]
Made the requested changes. Anyone else wanna take a look?

**Comment by darrenstahlmsft** [comment]
Noticing some restart failures in CI. I'm attempting to repro locally, currently without success

**Comment by jhowardmsft** [comment]
@darrenstahlmsft Is this successful now with no concerns?

**Comment by darrenstahlmsft** [comment]
Yeah, the failures seen were flaky tests not related to this.

**Review by mlaventure — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
ping @jhowardmsft ready to merge?

**Comment by jhowardmsft** [comment]
Yup :). LGTM.
