### PR TITLE
Fix awslogs driver repeating last event - #34292

### LINKED ISSUE #34292: awslogs driver repeating last event
I'm running Docker 17.06.0-ce on Ubuntu 16.04 (on AWS) and have noticed that the `awslogs` logdriver is endlessly re-logging the last received event. As a repro, I am running the following simple Flask app:

```
from flask import Flask
app = Flask(__name__)

@app.route("/")
def hello():
        return "Hello World!"

if __name__ == '__main__':
    app.run(host='0.0.0.0')
```

with the following `Dockerfile`:

```
FROM python:3.6-slim

RUN pip install flask
ADD app.py app.py
CMD ["python", "app.py"]
```

and the following `docker-compose.yaml`:

```
version: "2"

services:
  flask:
    build: .
    image: pgflask
    ports:
      - 5010:5000
    logging:
       driver: awslogs
       options:
         awslogs-region: "us-west-2"
         awslogs-group: "flask_loggroup"
         awslogs-stream: "flask_stream"
         awslogs-datetime-format: "%Y-%m-%d %H:%M:%S"
```

After `curl localhost:5010`, I see the following in my AWS CloudWatch console:

image

**NOTE:** the `Running on http://...` message is from the Flask app startup and is also repeated.

I've tried using `syslog` and `json-file` log drivers but have not seen this behavior locally which leads me to believe there's an issue with `awslogs`. Any thoughts?? I really appreciate your help!

Docker Info:

`docker info`

```
Containers: 104
 Running: 1
 Paused: 0
 Stopped: 103
Images: 505
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 473
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1013-aws
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.952GiB
Name: ip-10-0-2-147
ID: KWYK:BVW4:YJAS:2WC7:6F5X:FHDH:HE3J:FE7V:VR7X:UCCP:7HFC:YMOC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

### PR DESCRIPTION
**Pull request by mixja**
Signed-off-by: Justin Menga <justin.menga@gmail.com>

**- What I did**

Fixes #34292

**- How I did it**

Ensure event buffer used for storing log events is properly flushed

**- How to verify it**

The modifications to the test case in this PR fail with the old code and pass with the new code.

See #34292 for details on how to replicate the issue (I have verified this is no longer an issue with this PR)

**- Description for the changelog**

Fix awslogs driver repeating last event

**- A picture of a cute animal (not mandatory but encouraged)**

scared-bug

### CODE REVIEW

**Comment by mixja** [comment]
cc @samuelkarp

**Review by samuelkarp — APPROVED** [review]
LGTM.  Thanks for fixing this!

File: daemon/logger/awslogs/cloudwatchlogs_test.go [hunk 1]
```diff
@@ -641,14 +641,28 @@ func TestCollectBatchMultilinePatternMaxEventAge(t *testing.T) {
 	})
 
 	// Fire ticker batchPublishFrequency seconds later
-	ticks <- time.Now().Add(batchPublishFrequency * time.Second)
+	ticks <- time.Now().Add(batchPublishFrequency + time.Second)
```
Comment (thaJeztah) [inline daemon/logger/awslogs/cloudwatchlogs_test.go]: Is this correct? The comment leads me to believe it should be "* time.Second";

     // Fire ticker batchPublishFrequency seconds later

Comment (samuelkarp) [inline daemon/logger/awslogs/cloudwatchlogs_test.go]: `batchPublishFrequency` is already a `time.Duration` (see line 40 in cloudwatchlogs.go), so the existing code was an error.

Comment (thaJeztah) [inline daemon/logger/awslogs/cloudwatchlogs_test.go]: ah, makes sense (reading on my phone)

**Review by thaJeztah — APPROVED** [review]
LGTM

ping @cpuguy83 PTAL

**Review by yongtang — APPROVED** [review]
LGTM. Thanks for the fix!

**Comment by yongtang** [comment]
All Jenkins tests passed. Merging.

**Comment by samuelkarp** [comment]
@yongtang @thaJeztah Would this be cherry-picked into Docker 17.06.1-ce?

**Comment by thaJeztah** [comment]
I opened an issue internally to consider backporting it yes. Not sure yet if it makes 17.06.1, otherwise it could be included in a .2 release.
