### PR TITLE
Fix TestBuildCancelationKillsSleep to not fail on Windows

### LINKED ISSUE #11625: fix TestBuildCancelationKillsSleep so it passes on windows
**Problem**

TestBuildCancelationKillsSleep does not pass on windows because of events races and times on remote host being different

**Solution**

Use the time from `/info` to make the test pass on windows.

### PR DESCRIPTION
**Pull request by runcom**
Fixes: #11625

Signed-off-by: Antonio Murdaca me@runcom.ninja

### CODE REVIEW

File: integration-cli/docker_cli_build_test.go [hunk 1]
```diff
@@ -1964,7 +1964,7 @@ func TestBuildForceRm(t *testing.T) {
 // * Wait for docker events to emit a dying event.
 func TestBuildCancelationKillsSleep(t *testing.T) {
 	// TODO(jfrazelle): Make this work on Windows.
-	testRequires(t, SameHostDaemon)
+	//testRequires(t, SameHostDaemon)
```
Comment (duglin) [inline integration-cli/docker_cli_build_test.go]: If this works, you should just remove this line

File: integration-cli/docker_cli_build_test.go [hunk 2]
```diff
@@ -1986,8 +1986,7 @@ func TestBuildCancelationKillsSleep(t *testing.T) {
 	eventStart := make(chan struct{})
 	eventDie := make(chan struct{})
 
-	// Start one second ago, to avoid rounding problems
-	startEpoch := time.Now().Add(-1 * time.Second)
+	startEpoch := daemonTime(t).Unix()
```
Comment (duglin) [inline integration-cli/docker_cli_build_test.go]: Any reason we don't need the "one second ago" part of this?

File: integration-cli/docker_cli_build_test.go (hunk 1 above)
Comment (runcom) [inline integration-cli/docker_cli_build_test.go]: @duglin yes I just pushed to see what's happening on Windows, I'm not sure it works btw

File: integration-cli/docker_cli_build_test.go (hunk 2 above)
Comment (runcom) [inline integration-cli/docker_cli_build_test.go]: Because https://github.com/docker/docker/pull/12090/files#diff-9e07f7c1f4d16eb428d628f85ee1a6f1R417
there isn't need for -1 there and I think here isn't needed too. This just need a refactor to prevent races.

Comment (duglin) [inline integration-cli/docker_cli_build_test.go]: I can understand that using daemonTime() would reduce the race stuff, but I was wondering about the "...to avoid rounding problems" part of the comment.  Not sure if the reason they wrote that goes away once we get the time from the daemon.  @pwaller  ?

Comment (runcom) [inline integration-cli/docker_cli_build_test.go]: @duglin I don't know what deamonTime has to do with race stuff, I'm almost done fixing the race in this test btw

**Comment by runcom** [comment]
test isn't racy anymore but yet:
```
--- FAIL: TestBuildCancelationKillsSleep (0.44s)
	docker_cli_build_test.go:2074: wait failed during build run: *exec.ExitError exit status 1
	docker_cli_build_test.go:2021: docker events had bad exit status: exit status 1
```

**Comment by LK4D4** [comment]
@runcom Hmm, error seems legit for me. You're killing events, so it exits with -1. WDYT about using until for streaming autoexit? Or you can try send `SIGTERM`.

**Comment by runcom** [comment]
@LK4D4 that's ok but why the same test goes well on janky, I just don't understand this.. Also I don't know why who wrote the test in the beginning was looking to check !IsKilled(err)

**Comment by LK4D4** [comment]
@runcom Maybe windows `cmd` has different signals and all stuff.

**Comment by pwaller** [comment]
> @LK4D4 that's ok but why the same test goes well on janky, I just 
don't understand this.. Also I don't know why who wrote the test in the 
beginning was looking to check !IsKilled(err)

The idea of the test was to check in as many ways as possible that the 
reason for the death was because we signalled it.

File: integration-cli/docker_cli_build_test.go [hunk 3]
```diff
@@ -1977,26 +1973,20 @@ func TestBuildCancelationKillsSleep(t *testing.T) {
 	}
 	defer ctx.Close()
 
-	var wg sync.WaitGroup
-	defer wg.Wait()
-
```
Comment (pwaller) [inline integration-cli/docker_cli_build_test.go]: I would be interested to hear the reasoning behind removing the waitgroup. My reasoning behind having it was to ensure that if the goroutine did not close for some reason due to future modifications to the code, it would block, and goroutine leakage could be detected. I use this pattern in this manner to specify that I really want this goroutine not to last longer than the calling scope, and if it does it should be detected by someone, because the caller will block at that wait.

```go
var wg sync.WaitGroup
defer wg.Wait()
wg.Add(1)
go func() { 
  defer wg.Done()
  ...
}()
```

File: integration-cli/docker_cli_build_test.go [hunk 4]
```diff
@@ -2042,11 +2025,33 @@ func TestBuildCancelationKillsSleep(t *testing.T) {
...
+				break
+			}
+		}
+	}()
+
+	select {
+	case <-time.After(30 * time.Second):
+		t.Fatal("failed to find a container id in build output")
+	case <-found:
+		// everthing's ok
```
Comment (pwaller) [inline integration-cli/docker_cli_build_test.go]: Minor typo

Comment (runcom) [inline integration-cli/docker_cli_build_test.go]: thanks @pwaller

**Comment by LK4D4** [comment]
@pwaller It failing on windows, because `Signaled` always return false on windows I think

File: integration-cli/docker_cli_build_test.go (hunk 3 above)
Comment (runcom) [inline integration-cli/docker_cli_build_test.go]: Haven't thought about that, I thought was to better synchronize the goroutine with the external context and thought that wouldn't be needed anymore. Cool, I'll add that back then.

**Comment by runcom** [comment]
would just `status.Signal() == os.Kill` detect we killed the buildCmd and sinse `os.Kill` works on Windows too the test will pass?

File: integration-cli/docker_cli_build_test.go [hunk 5]
```diff
@@ -1977,26 +1977,23 @@ func TestBuildCancelationKillsSleep(t *testing.T) {
...
+	// Goroutine responsible for watching start/die events from `docker events`
 	go func() {
 		defer wg.Done()
-
 		// Watch for events since epoch.
-		eventsCmd := exec.Command(dockerBinary, "events",
-			"-since", fmt.Sprint(startEpoch.Unix()))
+		eventsCmd := exec.Command(
+			dockerBinary, "events",
+			"--since", string(startEpoch))
```
Comment (LK4D4) [inline integration-cli/docker_cli_build_test.go]: Look at #12125

Comment (runcom) [inline integration-cli/docker_cli_build_test.go]: Roger that

**Comment by runcom** [comment]
@LK4D4 @pwaller Since both `WaitStatus.Signal()` and `WaitStatus.Signaled()` aren't intentionally implemented on Windows I added a condition to check whether the `ExitStatus()` is not equal to zero or not..In tests and especially this we do kill the process so we can be relatively sure the bad exit status is because we killed it. The other option would be not to run this test on windows (as it was before)

**Comment by LK4D4** [comment]
@runcom I think it is better to run it on windows.

**Comment by runcom** [comment]
alright then, with the `ExitStatus() != 0` now passes on Windows

**Comment by jfrazelle** [comment]
sorrrry rebase :(

**Comment by runcom** [comment]
@jfrazelle done

**Comment by jfrazelle** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM
