### PR TITLE
fix #11094 - Allow 'docker import' to load from local files

### LINKED ISSUE #11094: Allow 'docker import' to load from local files
The docker import mechanism allows loading from a pipe, but while this works, is not obvious to many users. Furthermore, not all users understand working with pipes.

Instead, users have reported attempting (and failing) to use a file:/// url.

### PR DESCRIPTION
**Pull request by gcuisinier**
I've modified `docker` import to add "-i" option like `docker load`.
This one allow both local file or http URL.

I kept the compatibility with the old way, but deprecate it if it's ok for you.
Test is added, and doc updated

closes #11094

Signed-off-by: Gildas Cuisinier gildas.cuisinier@gcuisinier.net

### CODE REVIEW

File: api/client/import.go [hunk 1]
```diff
@@ -16,30 +18,68 @@ import (
...
+		v                 = url.Values{}
 	)
+	if *infile != "" {
+
+		repository = cmd.Arg(0)
+
+		if strings.HasPrefix(*infile, "http://") || strings.HasPrefix(*infile, "https://") {
+			src = *infile
+			input = nil
+		} else if strings.HasPrefix(*infile, "file://") {
```
Comment (duglin) [inline api/client/import.go]: I'd prefer to not support file:// unless our other cmds do too and I don't think they do.

File: api/client/import.go [hunk 2]
```diff
@@ -16,30 +18,68 @@ import (
...
+				return err
+			}
+		}
+
+	} else {
+		repository = cmd.Arg(0)
+		src = "-"
+
+		if cmd.NArg() > 1 || strings.HasPrefix(cmd.Arg(0), "http://") || strings.HasPrefix(cmd.Arg(0), "https://") {
+			fmt.Fprintf(cli.err, "[DEPRECATED] The format 'URL|- [REPOSITORY[:TAG]]' has been deprecated. Please use [-i URL] [REPOSITORY[:TAG]]\n")
```
Comment (duglin) [inline api/client/import.go]: Why is this deprecated?

File: api/client/import.go (hunk 1 above)
Comment (duglin) [inline api/client/import.go]: I should add, I'm not fond of the file:// format. While its possible to reference local files that way, I don't really think its natural for people to do so when typing on the cmd line.  If we were in a situation where we had a whole like of URLs to process, or URLs were the main way to represent a resource, then I think it might make sense from a consistency perspective, but I doubt most people would naturally prefer to type `file://foo.tar` over just `foo.tar`

File: api/client/import.go (hunk 2 above)
Comment (duglin) [inline api/client/import.go]: Actually, the more I look at this the more reversed it seems :-)
You're adding `-i` and moving normal http(s) references under that.  It seems to me that if you wanted to push people towards using a URL for everything (which I assume is why you want to use file://) then we shouldn't have a `-i` at all and the normal URL variant should just support `file://`. 

I would actually prefer to NOT have a -i at all and just have the syntax be:
```
docker import file|URL|- [REPOSITORY[:TAG]]
```
And assume that if it doesn't start with `http(s)://` , or its not `-`, then its must be a local file.

**Comment by gcuisinier** [comment]
Hi,

My first proposal was indeed in this way by just adding support of "file://" url ( see https://github.com/gcuisinier/docker/commit/ade6041082475e18cec7db84bb53ec0cff8982ee ).


@runcom told me that it could be interesting to have "docker import" working like "docker load"
And so I've adapted by adding "-i" parameter.
That's explains my proposal of deprecation.


But if you prefer to not align `docker load` and `docker import`, I could easily adapt my first proposal to the syntax 
`docker import file|URL|- [REPOSITORY[:TAG]]`

**Comment by duglin** [comment]
@gcuisinier well, before you revamp it yet again (sorry) let's wait and see what others think. I tend to prefer to align with how people would expect things to work if they knew nothing about docker and since most commands, when referencing a local file, wouldn't use file:// that's why I questioned it.

**Comment by runcom** [comment]
@duglin @gcuisinier mine was just an idea in the issue thread just to tell my opinion as a user, sorry if you worked on that :(

**Comment by gcuisinier** [comment]
@runcom No problem, your idea was interesting, and that's don't take a lot of time to adapt :-)

@duglin No prob, I've two separate branch for proposal 1 and 2. The adaptation ( file://path/to/file to path/to/file ) takes me 2min.

**Comment by gcuisinier** [comment]
@duglin I've adapted the code here : https://github.com/gcuisinier/docker/tree/11094-allow-import-from-file

**Comment by duglin** [comment]
@gcuisinier do we need a defer to close the file?  Not sure but I bet it can't hurt.  You may want to make sure the order of the params (file|URL|-) are the same in all doc spots.
Aside from that it looks good to me.

**Comment by gcuisinier** [comment]
Indeed, closing file couldn't be bad.
And doc is fixed too

**Comment by gcuisinier** [comment]
Do you want me to update this PR or create another one base on the other branch ?

**Comment by duglin** [comment]
@gcuisinier just update this PR by `--amend`ing your current commit,that way its still just one.

File: docs/man/docker-import.1.md [hunk 3]
```diff
@@ -8,7 +8,7 @@ docker-import - Create an empty filesystem image and import the contents of the
 **docker import**
 [**-c**|**--change**[= []**]]
 [**--help**]
-URL|- [REPOSITORY[:TAG]]
+URL|file|- [REPOSITORY[:TAG]]
```
Comment (duglin) [inline docs/man/docker-import.1.md]: put file first

File: integration-cli/docker_cli_import_test.go [hunk 4]
```diff
@@ -41,3 +42,49 @@ func TestImportDisplay(t *testing.T) {
...
+	runCmd := exec.Command(dockerBinary, "run", "-d", "busybox", "true")
+	out, _, err := runCommandWithOutput(runCmd)
+	if err != nil {
+		t.Fatal("failed to create a container", out, err)
+	}
+	cleanedContainerID := stripTrailingCharacters(out)
+	defer deleteContainer(cleanedContainerID)
+
+	runCmd = exec.Command(dockerBinary, "export", cleanedContainerID)
+	out, _, err = runCommandWithOutput(runCmd)
```
Comment (duglin) [inline integration-cli/docker_cli_import_test.go]: This scares me a little to potentially put a ton of data into a string.  It might be better to just redirect stdout of the cmd directly to the file as part of executing t.

File: integration-cli/docker_cli_import_test.go [hunk 5]
```diff
@@ -41,3 +42,49 @@ func TestImportDisplay(t *testing.T) {
 
 	logDone("import - display is fine, imported image runs")
 }
+
+func TestImportFile(t *testing.T) {
+	runCmd := exec.Command(dockerBinary, "run", "-d", "busybox", "true")
```
Comment (duglin) [inline integration-cli/docker_cli_import_test.go]: this could be racey. I would suggest that you make it: `docker run --name bb busybox true` and then use `docker export bb` instead of the container ID.

**Comment by gcuisinier** [comment]
I've fix the test.
Redirect output directly in Cmd is not possible. I've created a new helper function in utils that save the output to file.

I've fix the doc too

**Comment by gcuisinier** [comment]
Is it good or do you need me to fix others things?

File: docs/sources/reference/commandline/cli.md [hunk 6]
```diff
@@ -1279,9 +1279,10 @@ NOTE: Docker will warn you if any containers exist that are using these untagged
       -c, --change=[]     Apply specified Dockerfile instructions while importing the image
 
 URLs must start with `http` and point to a single file archive (.tar,
-.tar.gz, .tgz, .bzip, .tar.xz, or .txz) containing a root filesystem. If
-you would like to import from a local directory or archive, you can use
+.tar.gz, .tgz, .bzip, .tar.xz, or .txz) containing a root filesystem.
+If you would like to import from a local directory or archive, you can use
 the `-` parameter to take the data from `STDIN`.
+You can also have URL that point to a local file relative to the docker client.
```
Comment (duglin) [inline docs/sources/reference/commandline/cli.md]: s/URL that/it/

File: integration-cli/utils.go [hunk 7]
```diff
@@ -62,6 +63,19 @@ func runCommandWithOutput(cmd *exec.Cmd) (output string, exitCode int, err error
 	return
 }
 
+func runCommandWithOutputWriteToFile(cmd *exec.Cmd, outputfile *os.File) (exitCode int, err error) {
```
Comment (duglin) [inline integration-cli/utils.go]: This func probably isn't needed since I think you can just do:
cmd.Stdout = ...writer to file...

**Comment by duglin** [comment]
@gcuisinier did you want to address the comments?

**Comment by duglin** [comment]
You'll need to change the integration-cli tests to use the new testing infrastructure.

**Comment by gcuisinier** [comment]
@duglin I will fix these points this weekend, ok for you ?

**Comment by duglin** [comment]
@gcuisinier yup just wanted to make sure you were still interested

**Comment by gcuisinier** [comment]
Always interested :-)

File: api/client/import.go [hunk 8]
```diff
@@ -52,6 +54,15 @@ func (cli *DockerCli) CmdImport(args ...string) error {
 
 	if src == "-" {
 		in = cli.in
+	} else if !strings.HasPrefix(src, "http://") && !strings.HasPrefix(src, "https://") {
```
Comment (icecrime) [inline api/client/import.go]: Can we replace this line with `else if !urilutil.IsURL(src) {`?

File: api/client/import.go [hunk 9]
```diff
@@ -52,6 +54,15 @@ func (cli *DockerCli) CmdImport(args ...string) error {
...
+		v.Set("fromSrc", "-")
+		file, err := os.Open(src)
+		defer file.Close()
+		in = file
+		if err != nil {
```
Comment (icecrime) [inline api/client/import.go]: Just for readability purpose, I'd rather see that test right after the call to `os.Open` (and we don't even have to defer `file.Close()` if `err != nil` anyways).

**Comment by icecrime** [comment]
@gcuisinier Thanks for the contribution! I added two more comments after review.

**Comment by gcuisinier** [comment]
Is it ok for you ?

**Comment by runcom** [comment]
@gcuisinier would you address @icecrime's comments? Thanks!

**Comment by gcuisinier** [comment]
Oops, I've forgot to add files in git before commit ..

File: integration-cli/docker_cli_import_test.go [hunk 10]
```diff
@@ -39,3 +42,50 @@ func (s *DockerSuite) TestImportDisplay(c *check.C) {
...
+	temporaryFile, err := ioutil.TempFile("", "exportImportTest")
+	if err != nil {
+		c.Fatal("failed to create temporary file", "", err)
+	}
+
+	runCmd = exec.Command(dockerBinary, "export", "test-import")
+	runCmd.Stdout = bufio.NewWriter(temporaryFile)
+
+	_, err = runCommand(runCmd)
+	//_, err = runCommandWithOutputWriteToFile(runCmd, temporaryFile)
```
Comment (calavera) [inline integration-cli/docker_cli_import_test.go]: can you remove this comment, please?

**Comment by calavera** [comment]
just a minor comment, but code LGTM.

**Comment by gcuisinier** [comment]
done.

**Comment by calavera** [comment]
waiting for other maintainer before moving it to docs review.

/cc @duglin, @LK4D4, @jfrazelle

**Comment by runcom** [comment]
code LGTM overall (am I missing something or the pr title is wrong?)

**Comment by gcuisinier** [comment]
Indeed, it is not aligned with the implementation.
I change it to the issue title.

**Comment by duglin** [comment]
One very minor thing, and sorry for taking so long to get back to you, can you add a negative test - one where the input file is missing?  Just to make sure we fail and generate an error msg, and return a non-zero rc.
Other than that it looks good.

**Comment by gcuisinier** [comment]
What's wrong in the windows build ?
I don't have Windows to test, so I'am not able to reproduce locally.

**Comment by runcom** [comment]
@gcuisinier seems not to be related with your work here, it's rebuilding now

File: integration-cli/docker_cli_import_test.go [hunk 11]
```diff
@@ -39,3 +42,60 @@ func (s *DockerSuite) TestImportDisplay(c *check.C) {
...
+	out, _, err = runCommandWithOutput(runCmd)
+	if err != nil {
+		c.Fatal("failed to import a container", out, err)
+	}
+
+	if n := strings.Count(out, "\n"); n != 1 {
+		c.Fatalf("display is messed up: %d '\\n' instead of 1:\n%s", n, out)
+	}
+	image := strings.TrimSpace(out)
+	defer deleteImages(image)
```
Comment (runcom) [inline integration-cli/docker_cli_import_test.go]: you can delete this defer as the suite takes care of deleting images here https://github.com/docker/docker/blob/master/integration-cli/check_test.go#L37

**Comment by gcuisinier** [comment]
@runcom It's fixed

**Comment by runcom** [comment]
@gcuisinier now yep

File: integration-cli/docker_cli_import_test.go [hunk 12]
```diff
@@ -39,3 +42,59 @@ func (s *DockerSuite) TestImportDisplay(c *check.C) {
...
+	if out != "" {
+		c.Fatalf("command output should've been nothing, was %q", out)
+	}
+
+}
+
+func (s *DockerSuite) TestImportFileNonExistentFile(c *check.C) {
+
+	runCmd := exec.Command(dockerBinary, "import", "non-existent-file")
+	_, exitCode, _ := runCommandWithOutput(runCmd)
```
Comment (runcom) [inline integration-cli/docker_cli_import_test.go]: Please check error here

Comment (runcom) [inline integration-cli/docker_cli_import_test.go]: And remove empty line please :D

File: integration-cli/docker_cli_import_test.go [hunk 13]
```diff
@@ -39,3 +42,59 @@ func (s *DockerSuite) TestImportDisplay(c *check.C) {
...
+
+	temporaryFile, err := ioutil.TempFile("", "exportImportTest")
+	if err != nil {
+		c.Fatal("failed to create temporary file", "", err)
+	}
+
+	runCmd = exec.Command(dockerBinary, "export", "test-import")
+	runCmd.Stdout = bufio.NewWriter(temporaryFile)
+
+	_, err = runCommand(runCmd)
```
Comment (duglin) [inline integration-cli/docker_cli_import_test.go]: on all of these where you have:
```
_, err = runCommand(...)
```
you only check `err` and not the exit code, I think you should check both because `err` will just be non-nil if its not able to start the command. If the cmd itself has a non-zero exitCode 'err' will be nil.  Granted something later on in you test will probably fail but we should catch things sooner.
Just doing:
```
ec, err = ...
if ec !=0 || err != nil {
...
}
```
should cover it

File: integration-cli/docker_cli_import_test.go [hunk 14]
```diff
@@ -39,3 +42,59 @@ func (s *DockerSuite) TestImportDisplay(c *check.C) {
...
+
+	if out != "" {
+		c.Fatalf("command output should've been nothing, was %q", out)
+	}
+
+}
+
+func (s *DockerSuite) TestImportFileNonExistentFile(c *check.C) {
+
+	runCmd := exec.Command(dockerBinary, "import", "non-existent-file")
```
Comment (duglin) [inline integration-cli/docker_cli_import_test.go]: Can you do me a favor?  In this test change `non-existent-file` to `example.com/myImage.tar`. This should still fail the same way but I want to make sure that we **never** interpret this string as a URL.  Prior to this PR all strings would be passed to the daemon as a URL and it would try to download from it.  So this PR does change this behavior, but I'm in favor of it.  However, I think we need to add a test for it (by using a string that almost looks like a url, but isnt').
Also, add a comment to mentioning all of this so that people know why you picked such a url-ish filename.

**Comment by duglin** [comment]
Just a few minor comments, overall its looking good.

A question for other maintainers....  this PR will change how `docker import` works in some cases.
If someone wrote:
```
docker import example.com/foo.tar
```
then it will fail saying that "example.com/foo.tar" file can not be found.  Before this PR that string would be assumed to be a url and passed to the server for downloading.

While this is a change in current behavior, I actually think the old way was a bug. To assume any string was a url (even something like "hello") is pretty odd.  When combined with the new ability to now import from a local file w/o having to redirect stdin to point to the file (which feels like a hack) I think this is the right thing to do.  However, I did want to bring up this point so other maintainer so they can weigh in.

/ping @crosbymichael @jfrazelle @tiborvass @LK4D4

File: integration-cli/docker_cli_import_test.go [hunk 15]
```diff
@@ -29,8 +32,52 @@ func (s *DockerSuite) TestImportDisplay(c *check.C) {
...
+	if out != "" {
+		c.Fatalf("command output should've been nothing, was %q", out)
+	}
+
+}
+
+func (s *DockerSuite) TestImportFile(c *check.C) {
+	runCmd := exec.Command(dockerBinary, "run", "--name", "test-import", "busybox", "true")
+	out, ec, err := runCommandWithOutput(runCmd)
+	if ec != 0 || err != nil {
```
Comment (duglin) [inline integration-cli/docker_cli_import_test.go]: I apologize for this - I totally misread the code in runCommandWithOutput() and was corrected on this in another PR, apparently err can't be nil if ec != 0, so what you had originally (just checking err) is good enough.  Really sorry for my mistake.

Comment (gcuisinier) [inline integration-cli/docker_cli_import_test.go]: Only for runCommandWithOutput? Or for runCommand too?

Comment (duglin) [inline integration-cli/docker_cli_import_test.go]: It looks like its the same for both.

**Comment by calavera** [comment]
> I think this is the right thing to do.

I agree, if it doesn't look like a url, it's not a url, therefore it should be considered a path in the file system and fail if it doesn't exist.

File: docs/sources/reference/commandline/cli.md [hunk 16]
```diff
@@ -1447,6 +1448,10 @@ Import to docker via pipe and `STDIN`.
 
     $ sudo tar -c . | docker import - exampleimagedir
 
+**Import from a local directory with local file url:**
```
Comment (duglin) [inline docs/sources/reference/commandline/cli.md]: remove "url"

File: integration-cli/docker_cli_import_test.go [hunk 17]
```diff
@@ -50,3 +53,56 @@ func (s *DockerSuite) TestImportBadURL(c *check.C) {
...
+	temporaryFile, err := ioutil.TempFile("", "exportImportTest")
+	if err != nil {
+		c.Fatal("failed to create temporary file", "", err)
+	}
+
+	runCmd = exec.Command(dockerBinary, "export", "test-import")
+	runCmd.Stdout = bufio.NewWriter(temporaryFile)
+
+	_, err = runCommand(runCmd)
+	defer os.Remove(temporaryFile.Name())
```
Comment (duglin) [inline integration-cli/docker_cli_import_test.go]: I think this should be after line 67, right after the temp file is created.

**Comment by duglin** [comment]
two very minor comments - but LGTM
ping @LK4D4 @tiborvass

File: integration-cli/docker_cli_import_test.go (hunk 13 above)
Comment (cpuguy83) [inline integration-cli/docker_cli_import_test.go]: but err is always not nil if ec is not 0.

**Comment by cpuguy83** [comment]
LGTM moving to docs review

**Comment by SvenDowideit** [comment]
Docs LGTM. If you do revisit this due to other feedback, I'd mention your new local file before the `-` STDIN method. - noice!

File: docs/sources/reference/commandline/cli.md [hunk 18]
```diff
@@ -1447,6 +1448,10 @@ Import to docker via pipe and `STDIN`.
 
     $ sudo tar -c . | docker import - exampleimagedir
 
+**Import from a local directory with local file:**
+
+    $ sudo docker import /local/path/to/exampleimage.tgz exampleimagedir
```
Comment (thaJeztah) [inline docs/sources/reference/commandline/cli.md]: Possibly I don't understand this correctly, but what is the purpose of `exampleimagedir` here?

Also "Import from a local directory with a local file" is confusing to me; what is the "directory"? Could it be just "Import from a local file"?

**Comment by thaJeztah** [comment]
I added some comments on the docs.

Wrt the change in behavior (https://github.com/docker/docker/pull/11907#issuecomment-101864577), I don't think that should be a problem, because the current examples in the documentation use `http://...`. Anyone using URLs without using `http(s)://` is relying on undocumented behaviour.

File: docs/sources/reference/commandline/cli.md [hunk 19]
```diff
@@ -1420,9 +1420,10 @@ NOTE: Docker will warn you if any containers exist that are using these untagged
       -c, --change=[]     Apply specified Dockerfile instructions while importing the image
 
 URLs must start with `http` and point to a single file archive (.tar,
-.tar.gz, .tgz, .bzip, .tar.xz, or .txz) containing a root filesystem. If
-you would like to import from a local directory or archive, you can use
+.tar.gz, .tgz, .bzip, .tar.xz, or .txz) containing a root filesystem.
+If you would like to import from a local directory or archive, you can use
 the `-` parameter to take the data from `STDIN`.
```
Comment (SvenDowideit) [inline docs/sources/reference/commandline/cli.md]: I'd flip these - adding this functionality makes using `-` the exception case

File: docs/sources/reference/commandline/cli.md (hunk 18 above)
Comment (SvenDowideit) [inline docs/sources/reference/commandline/cli.md]: y, I also don't grok - in the context of `docker import [OPTIONS] URL|- [REPOSITORY[:TAG]]`

**Comment by gcuisinier** [comment]
Ok, I will correct the PR asap.
Thanks for feedbacks

**Comment by duglin** [comment]
ping @moxiegirl @fredlf

File: docs/man/docker-import.1.md [hunk 20]
```diff
@@ -35,6 +35,11 @@ Import to docker via pipe and stdin:
 
     # cat exampleimage.tgz | docker import - example/imagelocal
 
+Import to docker from local file
```
Comment (moxiegirl) [inline docs/man/docker-import.1.md]: Import to a Docker container from a local file.

Comment (duglin) [inline docs/man/docker-import.1.md]: s/container/image.

File: docs/sources/reference/commandline/cli.md [hunk 21]
```diff
@@ -1443,10 +1443,9 @@ NOTE: Docker will warn you if any containers exist that are using these untagged
 
       -c, --change=[]     Apply specified Dockerfile instructions while importing the image
 
-URLs must start with `http` and point to a single file archive (.tar,
-.tar.gz, .tgz, .bzip, .tar.xz, or .txz) containing a root filesystem. If
-you would like to import from a local directory or archive, you can use
-the `-` parameter to take the data from `STDIN`.
+You can import a single file archive (.tar, .tar.gz, .tgz, .bzip, .tar.xz, or .txz) containing a root filesystem from a local file relative to the docker client.
```
Comment (moxiegirl) [inline docs/sources/reference/commandline/cli.md]: This sentence is very difficult to parse.  There are too many ideas embedded in the chained prepositions. Break them out.

---> https://gist.github.com/moxiegirl/51e5d83f7d45915879b8

You can specify a `URL` or `-` (dash) to take data directly from STDIN. The `URL` can point to an archive (.tar, .tar.gz, .tgz, .bzip, .tar.xz, or .txz) containing a fileystem or to an individual file on the Docker host.  If you specify an archive, Docker untars it in the container relative to the `/` (root). If you specify an individual file, you must specify the full path within the host. To import from a remote location, specify a `URI` that beings with the `http://` protocol.

**Comment by gcuisinier** [comment]
Is it ok ?

**Comment by duglin** [comment]
rebase needed

File: docs/sources/reference/commandline/cli.md [hunk 22]
```diff
@@ -1457,10 +1457,8 @@ NOTE: Docker will warn you if any containers exist that are using these untagged
 
       -c, --change=[]     Apply specified Dockerfile instructions while importing the image
 
-URLs must start with `http` and point to a single file archive (.tar,
-.tar.gz, .tgz, .bzip, .tar.xz, or .txz) containing a root filesystem. If
-you would like to import from a local directory or archive, you can use
-the `-` parameter to take the data from `STDIN`.
+You can specify a URL or - (dash) to take data directly from STDIN. The URL can point to an archive (.tar, .tar.gz, .tgz, .bzip, .tar.xz, or .txz) containing a fileystem or to an individual file on the Docker host. If you specify an archive, Docker untars it in the container relative to the / (root). If you specify an individual file, you must specify the full path within the host. To import from a remote location, specify a URI that beings with the http:// protocol.
+
```
Comment (thaJeztah) [inline docs/sources/reference/commandline/cli.md]: Looks like you lost the formatting when copying @moxiegirl's gist;

```Markdown
You can specify a `URL` or `-` (dash) to take data directly from `STDIN`. The
`URL` can point to an archive (.tar, .tar.gz, .tgz, .bzip, .tar.xz, or .txz)
containing a fileystem or to an individual file on the Docker host.  If you
specify an archive, Docker untars it in the container relative to the `/`
(root). If you specify an individual file, you must specify the full path within
the host. To import from a remote location, specify a `URI` that begins with the
`http://` or `https://` protocol.
```

(I slightly modified the text, added `https://` for completeness and wrapped to 80-chars)

**Comment by thaJeztah** [comment]
Thanks, @gcuisinier I added a comment inline; if you can update the text and rebase (all docs were moved from `docs/sources` to `docs` and man pages are now in the `man` directory (outside of docs))

**Comment by gcuisinier** [comment]
Rebased and text updated.


Does the failure of the experimental build is blocking for the PR ?

**Comment by thaJeztah** [comment]
Thanks, LGTM

ping @fredlf @jamtur01 @moxiegirl @SvenDowideit PTAL

**Comment by jamtur01** [comment]
Docs LGTM

**Comment by thaJeztah** [comment]
And it's merged! thanks

**Comment by gcuisinier** [comment]
Happy to help :-)

**Comment by vdemeester** [comment]
@thaJeztah Maybe we should add ``impact/changelog`` label on this (even though it's a small change).

**Comment by thaJeztah** [comment]
@vdemeester thanks, yes. Hm was this in the 1.7 release already, or for 1.8?

**Comment by vdemeester** [comment]
I don't see it in the man page of 1.7.x so I'm pretty sure the "bump pr(s)" where already done and it did not make it for 1.7.x (that's why my comment :stuck_out_tongue:.

**Comment by thaJeztah** [comment]
@vdemeester it's sometimes hard to keep track which was / is part of which release

@calavera want me to add this to the milestone, to keep track easier?
