### PR TITLE
libnetwork/networkdb: make TestNetworkDBIslands not flaky

### LINKED ISSUE #42459: Flaky test: libnetwork/TestNetworkDBIslands
This test was already known to be flaky in the libnetwork repo:

It's also _extremely_ noisy, printing TONS of debug messages (something we should look at)

```
[2021-06-03T19:29:33.244Z] === Failed
[2021-06-03T19:29:33.244Z] === FAIL: libnetwork/networkdb TestNetworkDBIslands (123.95s)
```

The long version:

<details>

```
[2021-06-03T19:29:33.244Z] === Failed
[2021-06-03T19:29:33.244Z] === FAIL: libnetwork/networkdb TestNetworkDBIslands (123.95s)
[2021-06-03T19:29:33.244Z] time="2021-06-03T19:26:51Z" level=info msg="New memberlist node - Node:node1 will use memberlist nodeID:56c74dc5d33e with config:&{NodeID:56c74dc5d33e Hostname:node1 BindAddr:0.0.0.0 AdvertiseAddr: BindPort:10033 Keys:[] PacketBufferSize:1400 reapEntryInterval:1800000000000 reapNetworkInterval:1825000000000 StatsPrintPeriod:5m0s HealthPrintPeriod:1m0s}"
[2021-06-03T19:29:33.244Z] time="2021-06-03T19:26:51Z" level=info msg="Node 56c74dc5d33e/172.17.0.2, joined gossip cluster"
[2021-06-03T19:29:33.244Z] time="2021-06-03T19:26:51Z" level=info msg="Node 56c74dc5d33e/172.17.0.2, added to nodes list"
[2021-06-03T19:29:33.244Z] time="2021-06-03T19:26:51Z" level=info msg="New memberlist node - Node:node2 will use memberlist nodeID:5749c6ed183d with config:&{NodeID:5749c6ed183d Hostname:node2 BindAddr:0.0.0.0 AdvertiseAddr: BindPort:10034 Keys:[] PacketBufferSize:1400 reapEntryInterval:1800000000000 reapNetworkInterval:1825000000000 StatsPrintPeriod:5m0s HealthPrintPeriod:1m0s}"
[2021-06-03T19:29:33.244Z] time="2021-06-03T19:26:51Z" level=info msg="Node 5749c6ed183d/172.17.0.2, joined gossip cluster"
[2021-06-03T19:29:33.244Z] time="2021-06-03T19:26:51Z" level=info msg="Node 5749c6ed183d/172.17.0.2, added to nodes list"
[2021-06-03T19:29:33.244Z] time="2021-06-03T19:26:51Z" level=info msg="The new bootstrap node list is:[localhost:10033]"
[2021-06-03T19:29:33.244Z] time="2021-06-03T19:26:51Z" level=debug msg="memberlist: Initiating push/pull sync with: [::1]:10033"
[2021-06-03T19:29:33.244Z] time="2021-06-03T19:26:51Z" level=debug msg="memberlist: Stream connection from=[::1]:44798"
[2021-06-03T19:29:33.244Z] time="2021-06-03T19:26:51Z" level=info msg="Node 5749c6ed183d/172.17.0.2, joined gossip cluster"
[2021-06-03T19:29:33.244Z] time="2021-06-03T19:26:51Z" level=info msg="Node 5749c6ed183d/172.17.0.2, added to nodes list"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:51Z" level=info msg="Node 56c74dc5d33e/172.17.0.2, joined gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:51Z" level=info msg="Node 56c74dc5d33e/172.17.0.2, added to nodes list"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:51Z" level=debug msg="memberlist: Initiating push/pull sync with: 127.0.0.1:10033"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:51Z" level=debug msg="memberlist: Stream connection from=127.0.0.1:38100"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:51Z" level=info msg="New memberlist node - Node:node3 will use memberlist nodeID:54db19a11b90 with config:&{NodeID:54db19a11b90 Hostname:node3 BindAddr:0.0.0.0 AdvertiseAddr: BindPort:10035 Keys:[] PacketBufferSize:1400 reapEntryInterval:1800000000000 reapNetworkInterval:1825000000000 StatsPrintPeriod:5m0s HealthPrintPeriod:1m0s}"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:51Z" level=info msg="Node 54db19a11b90/172.17.0.2, joined gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:51Z" level=info msg="Node 54db19a11b90/172.17.0.2, added to nodes list"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:51Z" level=info msg="The new bootstrap node list is:[localhost:10034]"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:51Z" level=debug msg="memberlist: Initiating push/pull sync with: [::1]:10034"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:51Z" level=debug msg="memberlist: Stream connection from=[::1]:46812"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:51Z" level=info msg="Node 54db19a11b90/172.17.0.2, joined gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:51Z" level=info msg="Node 54db19a11b90/172.17.0.2, added to nodes list"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:51Z" level=info msg="Node 56c74dc5d33e/172.17.0.2, joined gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:51Z" level=info msg="Node 56c74dc5d33e/172.17.0.2, added to nodes list"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:51Z" level=info msg="Node 5749c6ed183d/172.17.0.2, joined gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:51Z" level=info msg="Node 5749c6ed183d/172.17.0.2, added to nodes list"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:51Z" level=debug msg="memberlist: Initiating push/pull sync with: 127.0.0.1:10034"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:51Z" level=debug msg="memberlist: Stream connection from=127.0.0.1:36616"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="Node 54db19a11b90/172.17.0.2, joined gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="Node 54db19a11b90/172.17.0.2, added to nodes list"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="New memberlist node - Node:node4 will use memberlist nodeID:45c5804ddf45 with config:&{NodeID:45c5804ddf45 Hostname:node4 BindAddr:0.0.0.0 AdvertiseAddr: BindPort:10036 Keys:[] PacketBufferSize:1400 reapEntryInterval:1800000000000 reapNetworkInterval:1825000000000 StatsPrintPeriod:5m0s HealthPrintPeriod:1m0s}"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="Node 45c5804ddf45/172.17.0.2, joined gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="Node 45c5804ddf45/172.17.0.2, added to nodes list"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="The new bootstrap node list is:[localhost:10035]"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=debug msg="memberlist: Initiating push/pull sync with: [::1]:10035"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=debug msg="memberlist: Stream connection from=[::1]:45736"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="Node 45c5804ddf45/172.17.0.2, joined gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="Node 45c5804ddf45/172.17.0.2, added to nodes list"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="Node 5749c6ed183d/172.17.0.2, joined gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="Node 5749c6ed183d/172.17.0.2, added to nodes list"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="Node 54db19a11b90/172.17.0.2, joined gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="Node 54db19a11b90/172.17.0.2, added to nodes list"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="Node 56c74dc5d33e/172.17.0.2, joined gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="Node 56c74dc5d33e/172.17.0.2, added to nodes list"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=debug msg="memberlist: Initiating push/pull sync with: 127.0.0.1:10035"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=debug msg="memberlist: Stream connection from=127.0.0.1:54628"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="Node 45c5804ddf45/172.17.0.2, joined gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="Node 45c5804ddf45/172.17.0.2, added to nodes list"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="Node 45c5804ddf45/172.17.0.2, joined gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="Node 45c5804ddf45/172.17.0.2, added to nodes list"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="New memberlist node - Node:node5 will use memberlist nodeID:c146e536a053 with config:&{NodeID:c146e536a053 Hostname:node5 BindAddr:0.0.0.0 AdvertiseAddr: BindPort:10037 Keys:[] PacketBufferSize:1400 reapEntryInterval:1800000000000 reapNetworkInterval:1825000000000 StatsPrintPeriod:5m0s HealthPrintPeriod:1m0s}"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="Node c146e536a053/172.17.0.2, joined gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="Node c146e536a053/172.17.0.2, added to nodes list"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="The new bootstrap node list is:[localhost:10036]"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=debug msg="memberlist: Initiating push/pull sync with: [::1]:10036"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=debug msg="memberlist: Stream connection from=[::1]:35958"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="Node c146e536a053/172.17.0.2, joined gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="Node c146e536a053/172.17.0.2, added to nodes list"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="Node 5749c6ed183d/172.17.0.2, joined gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="Node 5749c6ed183d/172.17.0.2, added to nodes list"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="Node 56c74dc5d33e/172.17.0.2, joined gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="Node 56c74dc5d33e/172.17.0.2, added to nodes list"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="Node 45c5804ddf45/172.17.0.2, joined gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="Node 45c5804ddf45/172.17.0.2, added to nodes list"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="Node 54db19a11b90/172.17.0.2, joined gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="Node 54db19a11b90/172.17.0.2, added to nodes list"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=debug msg="memberlist: Initiating push/pull sync with: 127.0.0.1:10036"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=debug msg="memberlist: Stream connection from=127.0.0.1:43224"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="Node c146e536a053/172.17.0.2, joined gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="Node c146e536a053/172.17.0.2, added to nodes list"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="Node c146e536a053/172.17.0.2, joined gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:52Z" level=info msg="Node c146e536a053/172.17.0.2, added to nodes list"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:53Z" level=info msg="Node c146e536a053/172.17.0.2, joined gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:53Z" level=info msg="Node c146e536a053/172.17.0.2, added to nodes list"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:53Z" level=info msg="The new bootstrap node list is:[172.17.0.2:10033 172.17.0.2:10034 172.17.0.2:10035]"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:53Z" level=debug msg="memberlist: Initiating push/pull sync with: 172.17.0.2:10033"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:53Z" level=debug msg="memberlist: Stream connection from=172.17.0.2:40982"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:53Z" level=debug msg="memberlist: Stream connection from=172.17.0.2:35820"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:53Z" level=debug msg="memberlist: Initiating push/pull sync with: 172.17.0.2:10034"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:53Z" level=debug msg="memberlist: Initiating push/pull sync with: 172.17.0.2:10035"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:53Z" level=debug msg="memberlist: Stream connection from=172.17.0.2:39868"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:53Z" level=info msg="The new bootstrap node list is:[172.17.0.2:10033 172.17.0.2:10034 172.17.0.2:10035]"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:53Z" level=debug msg="memberlist: Initiating push/pull sync with: 172.17.0.2:10033"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:53Z" level=debug msg="memberlist: Stream connection from=172.17.0.2:40988"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:53Z" level=debug msg="memberlist: Initiating push/pull sync with: 172.17.0.2:10034"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:53Z" level=debug msg="memberlist: Stream connection from=172.17.0.2:35826"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:53Z" level=debug msg="memberlist: Initiating push/pull sync with: 172.17.0.2:10035"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:53Z" level=debug msg="memberlist: Stream connection from=172.17.0.2:39874"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:53Z" level=info msg="node 0 leaving"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:53Z" level=info msg="Node 56c74dc5d33e change state NodeActive --> NodeLeft"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:53Z" level=info msg="Node 56c74dc5d33e change state NodeActive --> NodeLeft"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:53Z" level=info msg="Node 56c74dc5d33e change state NodeActive --> NodeLeft"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:53Z" level=info msg="node5(c146e536a053): Node leave event for 56c74dc5d33e/172.17.0.2"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:53Z" level=info msg="node2(5749c6ed183d): Node leave event for 56c74dc5d33e/172.17.0.2"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:53Z" level=info msg="node3(54db19a11b90): Node leave event for 56c74dc5d33e/172.17.0.2"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:53Z" level=info msg="Node 56c74dc5d33e change state NodeActive --> NodeLeft"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:53Z" level=info msg="node1(56c74dc5d33e): Node leave event for 56c74dc5d33e/172.17.0.2"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:53Z" level=info msg="Node 56c74dc5d33e change state NodeActive --> NodeLeft"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:53Z" level=info msg="node4(45c5804ddf45): Node leave event for 56c74dc5d33e/172.17.0.2"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:53Z" level=info msg="Node 56c74dc5d33e/172.17.0.2, left gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:53Z" level=info msg="Node 56c74dc5d33e/172.17.0.2, left gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:53Z" level=info msg="Node 56c74dc5d33e/172.17.0.2, left gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:53Z" level=info msg="Node 56c74dc5d33e/172.17.0.2, left gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:53Z" level=info msg="Node 56c74dc5d33e/172.17.0.2, left gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:54Z" level=info msg="node 1 leaving"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:54Z" level=info msg="Node 5749c6ed183d change state NodeActive --> NodeLeft"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:54Z" level=info msg="node3(54db19a11b90): Node leave event for 5749c6ed183d/172.17.0.2"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:54Z" level=info msg="Node 5749c6ed183d/172.17.0.2, left gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:54Z" level=info msg="Node 5749c6ed183d change state NodeActive --> NodeFailed"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:54Z" level=info msg="Node 5749c6ed183d/172.17.0.2, added to failed nodes list"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:54Z" level=info msg="Node 5749c6ed183d change state NodeActive --> NodeLeft"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:54Z" level=info msg="node4(45c5804ddf45): Node leave event for 5749c6ed183d/172.17.0.2"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:54Z" level=info msg="Node 5749c6ed183d change state NodeActive --> NodeLeft"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:54Z" level=info msg="node5(c146e536a053): Node leave event for 5749c6ed183d/172.17.0.2"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:54Z" level=error msg="node: 5749c6ed183d is unknown to memberlist"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:54Z" level=info msg="Node 5749c6ed183d/172.17.0.2, left gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:54Z" level=info msg="Node 5749c6ed183d/172.17.0.2, left gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:54Z" level=info msg="Node 5749c6ed183d/172.17.0.2, left gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:54Z" level=info msg="node 2 leaving"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:54Z" level=info msg="Node 54db19a11b90 change state NodeActive --> NodeLeft"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:54Z" level=info msg="node5(c146e536a053): Node leave event for 54db19a11b90/172.17.0.2"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:54Z" level=debug msg="memberlist: Failed ping: c146e536a053 (timeout reached)"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:54Z" level=warning msg="memberlist: Failed to send indirect ping: write udp [::]:10033->172.17.0.2:10036: use of closed network connection"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:54Z" level=warning msg="memberlist: Failed to send indirect ping: write udp [::]:10033->172.17.0.2:10035: use of closed network connection"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:54Z" level=warning msg="memberlist: Failed to send indirect ping: write udp [::]:10033->172.17.0.2:10034: use of closed network connection"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:54Z" level=debug msg="memberlist: Stream connection from=172.17.0.2:35324"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:54Z" level=info msg="Node 54db19a11b90 change state NodeActive --> NodeLeft"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:54Z" level=info msg="node3(54db19a11b90): Node leave event for 54db19a11b90/172.17.0.2"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:54Z" level=info msg="Node 54db19a11b90/172.17.0.2, left gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:54Z" level=info msg="Node 54db19a11b90/172.17.0.2, left gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:54Z" level=info msg="Node 54db19a11b90/172.17.0.2, left gossip cluster"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:54Z" level=info msg="Node 54db19a11b90 change state NodeActive --> NodeFailed"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:54Z" level=info msg="Node 54db19a11b90/172.17.0.2, added to failed nodes list"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:54Z" level=error msg="node: 54db19a11b90 is unknown to memberlist"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:55Z" level=warning msg="memberlist: Was able to connect to c146e536a053 but other probes failed, network may be misconfigured"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:55Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:55Z" level=debug msg="memberlist: Failed ping: 45c5804ddf45 (timeout reached)"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:55Z" level=warning msg="memberlist: Failed to send indirect ping: write udp [::]:10035->172.17.0.2:10037: use of closed network connection"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:55Z" level=debug msg="memberlist: Stream connection from=172.17.0.2:57022"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:55Z" level=warning msg="memberlist: Was able to connect to 45c5804ddf45 but other probes failed, network may be misconfigured"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:56Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:57Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:58Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:26:59Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:27:00Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:27:01Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:27:02Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:27:03Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:27:04Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:27:05Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:27:06Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:27:07Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:27:08Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:27:09Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:27:10Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:27:11Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:27:12Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:27:13Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:27:14Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:27:15Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:27:16Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:27:17Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:27:18Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:27:19Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:27:20Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:27:21Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:27:22Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:27:23Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:27:24Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:27:25Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:27:26Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:27:27Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:27:28Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:27:28Z" level=debug msg="memberlist: Initiating push/pull sync with: 172.17.0.2:10037"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:27:28Z" level=debug msg="memberlist: Stream connection from=172.17.0.2:35396"
[2021-06-03T19:29:33.245Z] time="2021-06-03T19:27:29Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:30Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:31Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:32Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:33Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:34Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:35Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:36Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:37Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:38Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:39Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:40Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:41Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:42Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:43Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:44Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:45Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:46Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:47Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:48Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:49Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:49Z" level=debug msg="memberlist: Initiating push/pull sync with: 172.17.0.2:10036"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:49Z" level=debug msg="memberlist: Stream connection from=172.17.0.2:57134"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:50Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:51Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:52Z" level=debug msg="rejoinClusterBootStrap, calling cluster join with bootStrap [172.17.0.2:10033 172.17.0.2:10034 172.17.0.2:10035]"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:52Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:52Z" level=debug msg="rejoinClusterBootStrap, calling cluster join with bootStrap [172.17.0.2:10033 172.17.0.2:10034 172.17.0.2:10035]"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:53Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:53Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:53Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:53Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:53Z" level=error msg="Failed to join memberlist [172.17.0.2:10033 172.17.0.2:10034 172.17.0.2:10035] on retry: 3 errors occurred:\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused\n\n"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:53Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:53Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:53Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:53Z" level=error msg="Failed to join memberlist [172.17.0.2:10033 172.17.0.2:10034 172.17.0.2:10035] on retry: 3 errors occurred:\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused\n\n"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:54Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:54Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:54Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:54Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:54Z" level=error msg="Failed to join memberlist [172.17.0.2:10033 172.17.0.2:10034 172.17.0.2:10035] on retry: 3 errors occurred:\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused\n\n"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:54Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:54Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:54Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:54Z" level=error msg="Failed to join memberlist [172.17.0.2:10033 172.17.0.2:10034 172.17.0.2:10035] on retry: 3 errors occurred:\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused\n\n"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:55Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:55Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:55Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:55Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:55Z" level=error msg="Failed to join memberlist [172.17.0.2:10033 172.17.0.2:10034 172.17.0.2:10035] on retry: 3 errors occurred:\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused\n\n"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:55Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:55Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:55Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:55Z" level=error msg="Failed to join memberlist [172.17.0.2:10033 172.17.0.2:10034 172.17.0.2:10035] on retry: 3 errors occurred:\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused\n\n"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:56Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:56Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:56Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:56Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:56Z" level=error msg="Failed to join memberlist [172.17.0.2:10033 172.17.0.2:10034 172.17.0.2:10035] on retry: 3 errors occurred:\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused\n\n"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:56Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:56Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:56Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:56Z" level=error msg="Failed to join memberlist [172.17.0.2:10033 172.17.0.2:10034 172.17.0.2:10035] on retry: 3 errors occurred:\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused\n\n"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:57Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:57Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:57Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:57Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:57Z" level=error msg="Failed to join memberlist [172.17.0.2:10033 172.17.0.2:10034 172.17.0.2:10035] on retry: 3 errors occurred:\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused\n\n"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:57Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:57Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:57Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:57Z" level=error msg="Failed to join memberlist [172.17.0.2:10033 172.17.0.2:10034 172.17.0.2:10035] on retry: 3 errors occurred:\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused\n\n"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:58Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:58Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:58Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:58Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:58Z" level=error msg="Failed to join memberlist [172.17.0.2:10033 172.17.0.2:10034 172.17.0.2:10035] on retry: 3 errors occurred:\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused\n\n"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:58Z" level=debug msg="memberlist: Initiating push/pull sync with: 172.17.0.2:10037"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:58Z" level=debug msg="memberlist: Stream connection from=172.17.0.2:35526"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:58Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:58Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:58Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:58Z" level=error msg="Failed to join memberlist [172.17.0.2:10033 172.17.0.2:10034 172.17.0.2:10035] on retry: 3 errors occurred:\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused\n\n"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:59Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:59Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:59Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:59Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:59Z" level=error msg="Failed to join memberlist [172.17.0.2:10033 172.17.0.2:10034 172.17.0.2:10035] on retry: 3 errors occurred:\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused\n\n"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:59Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:59Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:59Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:27:59Z" level=error msg="Failed to join memberlist [172.17.0.2:10033 172.17.0.2:10034 172.17.0.2:10035] on retry: 3 errors occurred:\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused\n\n"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:28:00Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:28:00Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:28:00Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:28:00Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:28:00Z" level=error msg="Failed to join memberlist [172.17.0.2:10033 172.17.0.2:10034 172.17.0.2:10035] on retry: 3 errors occurred:\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused\n\n"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:28:00Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:28:00Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:28:00Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:28:00Z" level=error msg="Failed to join memberlist [172.17.0.2:10033 172.17.0.2:10034 172.17.0.2:10035] on retry: 3 errors occurred:\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused\n\n"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:28:01Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:28:01Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:28:01Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:28:01Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:28:01Z" level=error msg="Failed to join memberlist [172.17.0.2:10033 172.17.0.2:10034 172.17.0.2:10035] on retry: 3 errors occurred:\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused\n\n"
[2021-06-03T19:29:33.246Z] time="2021-06-03T19:28:01Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:01Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:01Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:01Z" level=error msg="Failed to join memberlist [172.17.0.2:10033 172.17.0.2:10034 172.17.0.2:10035] on retry: 3 errors occurred:\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused\n\n"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:02Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:02Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:02Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:02Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:02Z" level=error msg="Failed to join memberlist [172.17.0.2:10033 172.17.0.2:10034 172.17.0.2:10035] on retry: 3 errors occurred:\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused\n\n"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:02Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:02Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:02Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:02Z" level=error msg="Failed to join memberlist [172.17.0.2:10033 172.17.0.2:10034 172.17.0.2:10035] on retry: 3 errors occurred:\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused\n\n"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:03Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:04Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:05Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:06Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:07Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:08Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:09Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:10Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:11Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:12Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:13Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:14Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:15Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:16Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:17Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:18Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:19Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:19Z" level=debug msg="memberlist: Initiating push/pull sync with: 172.17.0.2:10036"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:19Z" level=debug msg="memberlist: Stream connection from=172.17.0.2:57318"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:20Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:21Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:22Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:23Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:24Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:25Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:26Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:27Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:28Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:28Z" level=debug msg="memberlist: Initiating push/pull sync with: 172.17.0.2:10037"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:28Z" level=debug msg="memberlist: Stream connection from=172.17.0.2:35644"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:29Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:30Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:31Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:32Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:33Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:34Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:35Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:36Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:37Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:38Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:39Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:40Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:41Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:42Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:43Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:44Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:45Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:46Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:47Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:48Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:49Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:49Z" level=debug msg="memberlist: Initiating push/pull sync with: 172.17.0.2:10036"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:49Z" level=debug msg="memberlist: Stream connection from=172.17.0.2:57382"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:50Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:51Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:52Z" level=debug msg="rejoinClusterBootStrap, calling cluster join with bootStrap [172.17.0.2:10033 172.17.0.2:10034 172.17.0.2:10035]"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:52Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:52Z" level=debug msg="rejoinClusterBootStrap, calling cluster join with bootStrap [172.17.0.2:10033 172.17.0.2:10034 172.17.0.2:10035]"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:53Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:53Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:53Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:53Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:53Z" level=error msg="Failed to join memberlist [172.17.0.2:10033 172.17.0.2:10034 172.17.0.2:10035] on retry: 3 errors occurred:\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused\n\n"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:53Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:53Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:53Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:53Z" level=error msg="Failed to join memberlist [172.17.0.2:10033 172.17.0.2:10034 172.17.0.2:10035] on retry: 3 errors occurred:\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused\n\n"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:54Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:54Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:54Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:54Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:54Z" level=error msg="Failed to join memberlist [172.17.0.2:10033 172.17.0.2:10034 172.17.0.2:10035] on retry: 3 errors occurred:\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused\n\n"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:54Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:54Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:54Z" level=debug msg="memberlist: Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused"
[2021-06-03T19:29:33.247Z] time="2021-06-03T19:28:54Z" level=error msg="Failed to join memberlist [172.17.0.2:10033 172.17.0.2:10034 172.17.0.2:10035] on retry: 3 errors occurred:\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10033: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10034: connect: connection refused\n\t* Failed to join 172.17.0.2: dial tcp 172.17.0.2:10035: connect: connection refused\n\n"
[2021-06-03T19:29:33.247Z]     networkdb_test.go:827: Re-joining: 3
[2021-06-03T19:29:33.247Z]     networkdb_test.go:827: Re-joining: 4
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.247Z]     networkdb_test.go:859: node5: OK
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.247Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.247Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 56c74dc5d33e left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:850: node4: Node 5749c6ed183d left
[2021-06-03T19:29:33.248Z]     networkdb_test.go:853: node4: Node 54db19a11b90 failed
[2021-06-03T19:29:33.248Z]     networkdb_test.go:864: timeout hit after 2m0s: node4:Waiting for all nodes to cleanly leave, left: 2, failed nodes: 1
```
</details>

### PR DESCRIPTION
**Pull request by corhere**
**- What I did**
- Fixes #42459 

**- How I did it**
I identified a bug in the rejoin logic that TestNetworkDBIslands is supposed to be validating which only manifests in tests as that is the only time where more than one node can be advertising the same IP address, only differing by port. I updated the logic to use both the IP address and port number when identifying nodes so that it behaves the same in tests as in production. I also updated the test itself to be more tolerant of nodes being spuriously marked as failed.

**- How to verify it**
`go test -count=...`

**- Human readable description for the release notes**

```markdown changelog

```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: libnetwork/networkdb/cluster.go [hunk 1]
```diff
@@ -296,17 +297,22 @@ func (nDB *NetworkDB) rejoinClusterBootStrap() {
 	bootStrapIPs := make([]string, 0, len(nDB.bootStrapIP))
 	for _, bootIP := range nDB.bootStrapIP {
 		// bootstrap IPs are usually IP:port from the Join
-		var bootstrapIP net.IP
-		ipStr, _, err := net.SplitHostPort(bootIP)
+		bootstrapIP, err := netip.ParseAddrPort(bootIP)
```
Comment (thaJeztah) [inline libnetwork/networkdb/cluster.go:300]: TIL `netip.ParseAddrPort`, nice!

(Looks like it only is for `ip-address:port`, not `hostname:port` though, so I guess in many of our cases, we'd still need `net.SplitHostPort` or variants thereof)

**Comment by thaJeztah** [comment]
Had to kick CI because GitHub was mis-behaving.

This one is unrelated (also known flaky test);

```
=== FAIL: github.com/docker/docker/integration/networking TestFlakyPortMappedHairpinWindows (13.19s)
    nat_windows_test.go:110: assertion failed: error is not nil: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.51/containers/40851ef9e2d5547472cea9120b7399a533fcec0b200119986b448189fbabc510/start": context deadline exceeded
    panic.go:636: assertion failed: error is not nil: Error response from daemon: error while removing network: network clientnet has active endpoints (name:"quirky_wilbur" id:"4c0041f5bd55")
```

**Review by vvoland — APPROVED** [review]
LGTM, thanks!

**Review by thaJeztah — APPROVED** [review]
LGTM
