### PR TITLE
cluster: Allow reentrant calls to methods during shutdown

### LINKED ISSUE #32173: [Flaky Test] DockerSwarmSuite.TearDown
This is failing pretty consistently on arm. /cc @aaronlehmann @aboch 

```
23:43:51 ----------------------------------------------------------------------
23:43:51 FAIL: check_test.go:353: DockerSwarmSuite.TearDownTest
23:43:51 
23:43:51 unmount of /tmp/docker-execroot/d84fa846414ee/netns failed: invalid argument
23:43:51 unmount of /tmp/docker-execroot/d84fa846414ee/netns failed: no such file or directory
23:43:51 check_test.go:358:
23:43:51     d.Stop(c)
23:43:51 daemon/daemon.go:392:
23:43:51     t.Fatalf("Error while stopping the daemon %s : %v", d.id, err)
23:43:51 ... Error: Error while stopping the daemon d4f89393cf6cd : exit status 130
23:43:51 
23:43:51 
23:43:51 ----------------------------------------------------------------------
23:43:51 PANIC: docker_api_swarm_test.go:316: DockerSwarmSuite.TestAPISwarmRaftQuorum
23:43:51 
23:43:51 [d84fa846414ee] waiting for daemon to start
23:43:51 [d84fa846414ee] daemon started
23:43:51 
23:43:51 [d4f89393cf6cd] waiting for daemon to start
23:43:51 [d4f89393cf6cd] daemon started
23:43:51 
23:43:51 [d491a1864e62c] waiting for daemon to start
23:43:51 [d491a1864e62c] daemon started
23:43:51 
23:43:51 [d4f89393cf6cd] exiting daemon
23:43:51 [d491a1864e62c] exiting daemon
23:43:51 [d4f89393cf6cd] waiting for daemon to start
23:43:51 [d4f89393cf6cd] daemon started
23:43:51 
23:43:51 [d84fa846414ee] exiting daemon
23:43:51 [d4f89393cf6cd] daemon started
23:43:51 Attempt #2: daemon is still running with pid 387
23:43:51 Attempt #3: daemon is still running with pid 387
23:43:51 Attempt #4: daemon is still running with pid 387
23:43:51 [d4f89393cf6cd] exiting daemon
23:43:51 ... Panic: Fixture has panicked (see related PANIC)
23:43:51 
23:43:51 ----------------------------------------------------------------------
```

### LINKED ISSUE #32441: Swarm/networking deadlock when shutting down daemon
This was discovered in a CI run on #32283. We don't think it's related to the changes in that PR.

See the stack traces in https://gist.github.com/aboch/ed05184c21313f98d62748ac4c74718f

Stopping the swarm node times out because the agent main loop is wedged and `agent.Leave` times out. This is a stack trace of the agent main loop:

```
goroutine 146 [semacquire]:
sync.runtime_Semacquire(0xc42000aff0)
	/usr/local/go/src/runtime/sema.go:47 +0x38
sync.(*Mutex).Lock(0xc42000afec)
	/usr/local/go/src/sync/mutex.go:85 +0x2f8
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).getStores(0xc42000af00, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/store.go:76 +0x58
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).getNetworksFromStore(0xc42000af00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/store.go:145 +0x60
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).Networks(0xc42000af00, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:868 +0x50
github.com/docker/docker/daemon.(*Daemon).GetNetworkDriverList(0xc420496200, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/network.go:459 +0x368
github.com/docker/docker/daemon.(*Daemon).showPluginsInfo(0xc420496200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/info.go:176 +0x64
github.com/docker/docker/daemon.(*Daemon).SystemInfo(0xc420496200, 0xc42001d502, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/info.go:101 +0x840
github.com/docker/docker/daemon/cluster/executor/container.(*executor).Describe(0xc420e72760, 0x3fff9e4a08e0, 0xc420a758c0, 0x9, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/cluster/executor/container/executor.go:34 +0x60
github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.(*Agent).nodeDescriptionWithHostname(0xc420eb6dc0, 0x3fff9e4a08e0, 0xc420a758c0, 0x1, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/agent.go:521 +0x6c
github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.(*Agent).run(0xc420eb6dc0, 0x3fff9e4a08e0, 0xc420a758c0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/agent.go:314 +0x15fc
created by github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.(*Agent).Start.func1
	/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/agent.go:79 +0x84
```

It can't get the controller lock because it's held by this goroutine, that's trying to get the cluster lock:

```
goroutine 467 [semacquire]:
sync.runtime_Semacquire(0xc42007186c)
	/usr/local/go/src/runtime/sema.go:47 +0x38
sync.(*RWMutex).RLock(0xc420071860)
	/usr/local/go/src/sync/rwmutex.go:43 +0x9c
github.com/docker/docker/daemon/cluster.(*Cluster).IsAgent(0xc420071860, 0x117ba000)
	/go/src/github.com/docker/docker/daemon/cluster/cluster.go:240 +0x48
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).isAgent(0xc42000af00, 0xc42000af00)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:638 +0x110
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*network).driver(0xc4210a9e00, 0x1, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/network.go:767 +0xe0
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*network).addEndpoint(0xc4210a9e00, 0xc421705e40, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/network.go:875 +0x44
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*network).CreateEndpoint(0xc4210a9e00, 0xc420fc11d1, 0x21, 0xc4217311a0, 0x4, 0x4, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/network.go:950 +0xabc
github.com/docker/docker/daemon.(*Daemon).connectToNetwork(0xc420496200, 0xc4207bd400, 0x1164b5f6, 0x6, 0xc421714480, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container_operations.go:735 +0x668
github.com/docker/docker/daemon.(*Daemon).allocateNetwork(0xc420496200, 0xc4207bd400, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container_operations.go:526 +0x378
github.com/docker/docker/daemon.(*Daemon).initializeNetworking(0xc420496200, 0xc4207bd400, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container_operations.go:903 +0x3d0
github.com/docker/docker/daemon.(*Daemon).containerStart(0xc420496200, 0xc4207bd400, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/start.go:140 +0x1f4
github.com/docker/docker/daemon.(*Daemon).ContainerStart(0xc420496200, 0xc421764000, 0x21, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/start.go:86 +0x5d4
github.com/docker/docker/daemon/cluster/executor/container.(*containerAdapter).start(0xc421085830, 0x3fff9e4d62b8, 0xc420d77640, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/cluster/executor/container/adapter.go:285 +0xd8
github.com/docker/docker/daemon/cluster/executor/container.(*controller).Start(0xc420f264b0, 0x3fff9e4d62b8, 0xc420d77640, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/cluster/executor/container/controller.go:189 +0x164
github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/exec.Do(0x3fff9e4d62b8, 0xc420d77640, 0xc4210a9b00, 0x11fdf000, 0xc420f264b0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/exec/controller.go:314 +0x720
github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.(*taskManager).run.func2(0x3fff9e4a08e0, 0xc420f2b140, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/task.go:134 +0x290
github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.runctx(0x3fff9e4a08e0, 0xc420f2b140, 0xc420eafb00, 0xc420f60300, 0xc420d776c0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/helpers.go:9 +0x50
created by github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.(*taskManager).run
	/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/task.go:150 +0x51c
```

cc @aboch @tonistiigi

### PR DESCRIPTION
**Pull request by aaronlehmann**
The agent sometimes calls into libnetwork code that in turn calls `(*Cluster).IsAgent` and `(*Cluster).IsManager`. These can cause the node shutdown process to time out, since they wait for a lock that is held by `Cleanup`.

It turns out `c.mu` doesn't need to be held while calling `Stop`. Holding `controlMutex` is sufficient. Also, `(*nodeRunner).Stop` must release `nodeRunner`'s `mu` during the node shutdown process, otherwise the same call into Cluster would be blocked on this lock instead.

Unsure if this should target 17.05. It's probably not a big deal in practice, since it only seems to happen on engine shutdown and leaving a swarm cluster. But it seems to affect CI a lot recently, so there might be value in including it for more stable tests and less uncertainty.

Fixes #32441
Fixes #32173

cc @tonistiigi

### CODE REVIEW

**Comment by aaronlehmann** [comment]
Before we merge this, let's rebuild several times and confirm that it seems to fix the random swarm test failures on teardown.

File: daemon/cluster/swarm.go [hunk 1]
```diff
@@ -25,19 +25,15 @@ import (
 func (c *Cluster) Init(req types.InitRequest) (string, error) {
 	c.controlMutex.Lock()
 	defer c.controlMutex.Unlock()
-	c.mu.Lock()
 	if c.nr != nil {
 		if req.ForceNewCluster {
 			if err := c.nr.Stop(); err != nil {
```
Comment (tonistiigi) [inline daemon/cluster/swarm.go]: I know it is ugly but can we take a `c.mu.Lock()` temporary here so that we wait for API handlers to finish up.

File: daemon/cluster/cluster.go [hunk 2]
```diff
@@ -345,11 +344,19 @@ func (c *Cluster) Cleanup() {
 			}
 		}
 	}
+
+	// Release the lock before stopping the node, so that calls back into
+	// Cluster during the shutdown process do not hang.
+	c.mu.Unlock()
```
Comment (tonistiigi) [inline daemon/cluster/cluster.go]: Nothing in the block above seems to use `c.mu` so this could be combined with the other unlock in line 334

Comment (aaronlehmann) [inline daemon/cluster/cluster.go]: "currentNodeState should not be called without a read lock"

But I moved the unlock just below that.

File: daemon/cluster/swarm.go (hunk 1 above)
Comment (aaronlehmann) [inline daemon/cluster/swarm.go]: Added

File: daemon/cluster/cluster.go [hunk 3]
```diff
@@ -334,8 +334,9 @@ func (c *Cluster) Cleanup() {
 		c.mu.Unlock()
 		return
 	}
-	defer c.mu.Unlock()
 	state := c.currentNodeState()
+	c.mu.Unlock()
```
Comment (aboch) [inline daemon/cluster/cluster.go]: I saw the comment about "currentNodeState should not be called without a read lock", but I do not understand it.
I believe that was added just because `c.currentNodeState()` will call `c.nr.State()`, so to make sure the `c.nr` won't change in between.
If possible we should avoid to hold locks around function executions.

I think we should change the code here to
```
c.mu.Lock()
node := c.nr
c.mu.Unlock()
...
state := nr.State()
```

File: daemon/cluster/swarm.go [hunk 4]
```diff
@@ -325,9 +326,10 @@ func (c *Cluster) Leave(force bool) error {
 
 	state := c.currentNodeState()
 
+	c.mu.Unlock()
```
Comment (aboch) [inline daemon/cluster/swarm.go]: same here, we should only get nr under lock, then call `state:=nr.State()`

File: daemon/cluster/swarm.go [hunk 5]
```diff
@@ -25,19 +25,20 @@ import (
 func (c *Cluster) Init(req types.InitRequest) (string, error) {
 	c.controlMutex.Lock()
 	defer c.controlMutex.Unlock()
-	c.mu.Lock()
```
Comment (aboch) [inline daemon/cluster/swarm.go]: given we remove the big mu.Lock section here, which is good, but then we should acquire `nr:=c.nr` under lock and then use `nr` throughout this function. otherwise now we freely use `c.nr` with the potential risk it gets modified in between.

Or is there an implicit assurance `c.nr` cannot be modified because we hold the `c.controlMutex.Lock()` ? 
If that is true, then it should have been true in Cleanup() as well.

Comment (tonistiigi) [inline daemon/cluster/swarm.go]: `c.nr` only changes when `c.controlMutex` is being held so there is no need to check for that. It is only for synchronization to the functions that take `c.mu.RLock()`. Although using local var might help readability.

Comment (aaronlehmann) [inline daemon/cluster/swarm.go]: > Or is there an implicit assurance `c.nr` cannot be modified because we hold the `c.controlMutex.Lock()`?

Yes, that's correct.

File: daemon/cluster/cluster.go (hunk 3 above)
Comment (aaronlehmann) [inline daemon/cluster/cluster.go]: I've updated the PR to avoid acquiring `c.mu` to read `c.nr` or call `c.currentNodeState` when `controlMutex` is already held. PTAL.

Comment (tonistiigi) [inline daemon/cluster/cluster.go]: After removing the locks, https://github.com/docker/docker/pull/32449/files#diff-12d2a05186062a2b8f2fb8c09adac4a1R30 now applies to leave/cleanup. I think it's better to cancel handlers gracefully. That means either doing the temp lock in these places or reverting this and adding comment that we are locking `c.nr` to make sure there is nothing holding readlocks.

Comment (aaronlehmann) [inline daemon/cluster/cluster.go]: I've removed the latest commit in response to this comment. I think holding the lock here for an extra function call is slightly less confusing than acquiring the lock and releasing it right away. However if people think the alternative would be clearer or safer, I'm happy to switch to that.

**Comment by aaronlehmann** [comment]
experimental test failure seems unrelated (https://jenkins.dockerproject.org/job/Docker-PRs-experimental/32781/console):

```
18:22:51 FAIL: check_test.go:95: DockerSuite.TearDownTest
18:22:51 
18:22:51 check_test.go:96:
18:22:51     testEnv.Clean(c, dockerBinary)
18:22:51 environment/clean.go:63:
18:22:51     t.Fatalf("error removing containers %v : %v (%s)", containers, result.Error, result.Combined())
18:22:51 ... Error: error removing containers [c39cbac06669] : exit status 1 (Error response from daemon: removal of container c39cbac06669 is already in progress
18:22:51 )
18:22:51 
18:22:51 
18:22:51 ----------------------------------------------------------------------
18:22:51 PANIC: docker_cli_run_test.go:4135: DockerSuite.TestRunRmAndWait
18:22:51 
18:22:51 ... Panic: Fixture has panicked (see related PANIC)
```

`powerpc` CI hit #26601 (https://jenkins.dockerproject.org/job/Docker-PRs-powerpc/1579/console)

Rebuilding both

**Comment by aaronlehmann** [comment]
The arm failure also turns out to be unrelated. #32490 is related to tracking this down.

@aboch: Are you happy with this PR as is? I tried removing more uses of `c.mu` as you suggested, but it turns out that those locks have a side effect of waiting waiting for other API calls to finish before leaving the swarm or cleaning up, so I ended up adding them back.

**Comment by aboch** [comment]
Yeah, kind of worried about these side waiting  effects of the lock.
But given this is mostly for the CI fix, it looks good to me as is.
Thanks

**Review by vdemeester — APPROVED** [review]
LGTM 🦁 
/cc @vieux @cpuguy83 @tonistiigi

**Review by tonistiigi — APPROVED** [review]
