### PR TITLE
libnet/ipams/default: introduce a linear allocator

### LINKED ISSUE #2612: splitNetworks leaking memory?
Doing a heap anaylsis of dockerd, I noticed that `splitNetworks` is holding on to memory unexpectedly:

```
root@03aaeddd73f2:/go/src/github.com/docker/docker# go tool pprof --inuse_space --lines http://127.0.0.1:80/debug/pprof/heap
Fetching profile over HTTP from http://127.0.0.1:80/debug/pprof/heap
DEBU[2021-01-14T18:49:40.287720452Z] Calling GET /debug/pprof/heap                
Saved profile in /root/pprof/pprof.dockerd.alloc_objects.alloc_space.inuse_objects.inuse_space.008.pb.gz
File: dockerd
Build ID: 5f027b8acdeb123c3ad701993a92522c1f689ee1
Type: inuse_space
Time: Jan 14, 2021 at 6:49pm (UTC)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 1834.63kB, 100% of 1834.63kB total
Showing top 10 nodes out of 25
      flat  flat%   sum%        cum   cum%
  809.97kB 44.15% 44.15%   809.97kB 44.15%  github.com/docker/docker/vendor/github.com/docker/libnetwork/ipamutils.splitNetworks /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/ipamutils/utils.go:104
```

This relates to this line: https://github.com/moby/libnetwork/blob/fa125a3512ee0f6187721c88582bf8c4378bd4d7/ipamutils/utils.go#L104

### LINKED ISSUE #40275: IPv6 address pool subnet smaller than /80 causes dockerd to consume all available RAM
**Description**

It is documented that IPv6 pool "should" be at least /80 so that MAC address can fit in the last 48 bits.

Using a default-address-pools size larger than 80 causes dockerd to consume too much RAM - the longer the prefix (smaller subnet), the more RAM dockerd will use:
- At /81 - /90 range the RAM usage increase is negligible in the range of few GB.
- At /94 - /96 range the RAM usage is in the tens to hundreds of GB.

The pool prefix length could be set to larger by 80 by a typing error or a mistake and if this leads to dockerd consuming copious amounts of RAM will cause the administrator to possibly lose time troubleshooting the situation.

It looks like prefix length like /96 is totally unusable and dockerd should refuse to start instead of starting to allocate ridiculous amounts of RAM.

At minimum a warning message should be printed.

**Steps to reproduce the issue:**
1. Set IPv6 address pool prefix length longer than 80:
```
  "default-address-pools": [
    { "base": "192.0.2.0/16", "size": 24 },
    { "base": "2001:db8:1:1f00::/64", "size": 96 }
  ],
```
2. Start Docker.
3. Watch the server grind to a halt and kernel OOM killer being invoked.

**Describe the results you received:**
dockerd consumes very large amounts of RAM (tens of GB).

**Describe the results you expected:**
Either IPv6 pool prefix lengths longer than 80 should work, or dockerd should refuse start with a configuration that cannot be used.

At minimum a warning message should be printed for prefix lengths longer than 80.

The documentation does not mention the RAM usage effect either:
```
The subnet for Docker containers should at least have a size of /80, so that an IPv6 address can end with the container’s MAC address and you prevent NDP neighbor cache invalidation issues in the Docker layer.
```

**Additional information you deem important (e.g. issue happens only occasionally):**
100% reproducible.

**Output of `docker version`:**

```
Docker version 19.03.5, build 633a0ea
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: fluentd
 Cgroup Driver: systemd
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
  selinux
 Kernel Version: 3.10.0-1062.4.3.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 47.15GiB
 Name: docker.domain
 ID: xxx
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### LINKED ISSUE #42801: splitNetwork and addIntToIP fails for IPv6 addresses on /64+ size pools
**Description**

When attempting to create the pools for IPv6 addresses ranges, the output of `splitNetwork` produces the same CIDR N times rather than the N different CIDRs if the output network size is >= 64 bits. This is due to the value passed to `addIntToIP` being a 64 bit int, which is insufficient to contain the required value to offset IPv6 ranges.

**Steps to reproduce the issue:**

1. Add an IPv6 range to `default-address-pools` in config and enable IPv6.

For example:
```
   "default-address-pools": [
      < IPv4 pools >
      {
        "base": "fd00:0000:0000::/48",
        "size": 64
      }
    ]
```

2. Attempt to create two IPv6 networks, the second will fail with `could not find an available, non-overlapping IPv6 address pool among the defaults to assign to the network`, suggesting there is only one pool available

**Describe the results you received:**

Only a single IPv6 pool is available per entry in `default-address-pools`

**Describe the results you expected:**

The output of splitting `fd00:0000:0000::/48` into `/64` networks should yield `2^16` pools, not one.

**Additional information you deem important (e.g. issue happens only occasionally):**

This is caused by [`splitNetwork` and `addIntToIP`](https://github.com/moby/moby/blob/8684f482e4cb84fee269d8e91176ca8e1afcc218/libnetwork/ipamutils/utils.go#L92-L135), which works OK for IPv4 but fails for IPv6 networks of `/64` or larger due to the `ordinal` argument to  `addIntToIP` being a 64 bit int, which ends up being zero when using a `/64` or larger. Crucially, the statement `uint(i<<s)` yields zero here, since `s > 64`

For example, `fmt.Println(splitNetworks([]*NetworkToSplit{{"fd00:0000:0000::/48", 50}}))` yields the same CIDR repeated 4 times rather than 4 separate CIDRs:

```
[fd00::/50 fd00::/50 fd00::/50 fd00::/50]
```

To fix this, those two functions need to be amended to allow values up to 128 bits to be added to an IP, perhaps with an `ordinalUpper` and `ordinalLower` as two 64 bit uints.

I believe this issue may be the underlying cause of https://github.com/moby/moby/issues/41438

**Output of `docker version`:**

```
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.11.6
 Git commit:        4c52b90
 Built:             Sun, 21 Feb 2021 18:18:35 +0100
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.6
  Git commit:       4c52b90
  Built:            Sun Feb 21 17:18:35 2021
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 27
 Running: 27
 Paused: 0
 Stopped: 0
Images: 31
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 1.0.0~rc6+dfsg1-3
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.19.0-14-amd64
Operating System: Debian GNU/Linux 10 (buster)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.4GiB
Name: 
ID: GXW4:VDGE:BS4J:AY3S:5DHN:COS3:TCUC:JOBN:KRPG:V6MW:YO37:A2GO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 191
 Goroutines: 192
 System Time: 2021-08-30T22:44:47.757633368Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
None

### PR DESCRIPTION
**Pull request by akerouanton**
- Close https://github.com/moby/moby/issues/40275
- Close https://github.com/moby/moby/issues/42801
- Close https://github.com/moby/libnetwork/issues/2612
- Supersede / Close https://github.com/moby/moby/pull/43033
- Stacked on top of https://github.com/moby/moby/pull/47727

**- What I did**

This previous allocator was subnetting address pools eagerly when the daemon started, and would then just iterate over that list whenever RequestPool was called. This was leading to high memory usage whenever IPv6 pools were configured with a target subnet size too different from the pools prefix size.

For instance: pool = fd00::/8, target size = /64 -- 2 ^ (64-8) subnets would be generated upfront. This would take approx. 9 * 10^18 bits -- way too much for any human computer in 2024.

Another noteworthy issue, the previous implementation was allocating a subnet, and then in another layer was checking whether the allocation was conflicting with some 'reserved networks'. If so, the allocation would be retried, etc... To make it worse, 'reserved networks' would be recomputed on every iteration. This is totally ineffective as there could be 'reserved networks' that fully overlap a given address pool (or many!).

To fix this issue, a new field `Exclude` is added to `RequestPool`. It's up to each driver to take it into account. Since we don't know whether this retry loop is useful for some remote IPAM driver, it's reimplemented bug-for-bug directly in the remote driver.

The new allocator uses a linear-search algorithm. It takes advantage of all lists (predefined pools, allocated subnets and reserved networks) being sorted and logically combines 'allocated' and 'reserved' through a 'double cursor' to iterate on both lists at the same time while preserving the total order. At the same time, it iterates over 'predefined' pools and looks for the first empty space that would be a good fit.

Currently, the size of the allocated subnet is still dictated by each 'predefined' pools. We should consider hardcoding that size instead, and let users specify what subnet size they want. This wasn't possible before as the subnets were generated upfront. This new allocator should be able to deal with this easily.

The method used for static allocation has been updated to make sure the ascending order of 'allocated' is preserved. It's bug-for-bug compatible with the previous implementation.

One consequence of this new algorithm is that we don't keep track of where the last allocation happened, we just allocate the first free subnet we find.

Before:

- Allocate: 10.0.1.0/24, 10.0.2.0/24 ; Deallocate: 10.0.1.0/24 ; Allocate 10.0.3.0/24.

Now, the 3rd allocation would yield 10.0.1.0/24 once again.

As it doesn't change the semantics of the allocator, there's no reason to worry about that.

Finally, about 'reserved networks'. The heuristics we use are now properly documented. It was discovered that we don't check routes for IPv6 allocations -- this can't be changed because there's no such thing as on-link routes for IPv6.

(Kudos to Rob Murray for coming up with the linear-search idea.)

**- How to verify it**

CI -- a bunch of tests have been added, some have been rewritten.

Or manually by creating, deleting and re-creating networks.

**- Description for the changelog**

```markdown changelog
- Introduce a new subnet allocator that can deal with IPv6 address pools of any size
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: libnetwork/internal/netiputil/netiputil.go [hunk 1]
```diff
@@ -59,3 +59,32 @@ func AddrPortFromNet(addr net.Addr) netip.AddrPort {
 	}
 	return netip.AddrPort{}
 }
+
+// LastAddr returns the last address of prefix 'p'.
+func LastAddr(p netip.Prefix) netip.Addr {
+	return ipbits.Add(ipbits.Sub(p.Addr(), 1, 0), 1, uint(p.Addr().BitLen()-p.Bits()))
```
Comment (corhere) [inline libnetwork/internal/netiputil/netiputil.go:65]:
```suggestion
	return ipbits.Add(p.Addr().Prev(), 1, uint(p.Addr().BitLen()-p.Bits()))
```

**Review by robmry — APPROVED** [review]
LGTM!

**Comment by akerouanton** [comment]
@corhere Please make sure this won't break Swarm in any way (eg. when a new leader is elected, etc...).

**Review by robmry — APPROVED** [review]

File: libnetwork/ipams/defaultipam/address_space.go [hunk 2]
```diff
@@ -2,29 +2,54 @@ package defaultipam
...
+	var discarded int
+	for i, imax := 0, len(predefined); i < imax; i++ {
+		p := predefined[i-discarded]
+		if last != nil && last.Overlaps(p.Base) {
+			predefined = slices.Delete(predefined, i-discarded, i-discarded+1)
+			discarded++
+			continue
+		}
+		last = p
+	}
```
Comment (corhere) [inline libnetwork/ipams/defaultipam/address_space.go:51]: Since the `slices` package is already being used, may as well take full advantage.
```suggestion
	predefined = slices.CompactFunc(predefined, func(last, p *ipamutils.NetworkToSplit) bool {
		return last.Overlaps(p.Base)
	})
```

**Review by corhere — COMMENTED** [review]
Review WIP; I haven't even finished with address_space.go. I'll be back tomorrow.

File: libnetwork/ipams/defaultipam/allocator.go [hunk 3]
```diff
@@ -98,19 +90,23 @@ func NewAllocator(lcAs, glAs []*net.IPNet) (*Allocator, error) {
...
+		if !n.Base.IsValid() || n.Size == 0 {
+			return []*ipamutils.NetworkToSplit{}, []*ipamutils.NetworkToSplit{}, fmt.Errorf("network at index %d (%v) is not in canonical form", i, n)
+		}
+		if n.Base.Bits() > n.Size {
+			return []*ipamutils.NetworkToSplit{}, []*ipamutils.NetworkToSplit{}, fmt.Errorf("network at index %d (%v) has a smaller prefix (/%d) than the target size of that pool (/%d)", i, n, n.Base.Bits(), n.Size)
 		}
 
-		if p.Addr().Is4() {
-			v4 = append(v4, p)
+		n.Base = netip.PrefixFrom(n.Base.Addr().Unmap(), n.Base.Bits()).Masked()
```
Comment (corhere) [inline libnetwork/ipams/defaultipam/allocator.go:104]:
```suggestion
		n.Base, _ = n.Base.Addr().Unmap().Prefix(n.Base.Bits())
```

**Review by corhere — COMMENTED** [review]
The new allocator should work fine with Swarm. The CNM network allocator replays allocations as static assignments if there is an existing allocation in the Swarm state. https://github.com/moby/moby/blob/4554d871d70bd055a0faa3ed595419ec4dc50406/libnetwork/cnmallocator/networkallocator.go#L866-L873

File: libnetwork/ipams/defaultipam/address_space.go (hunk 2 above)
Comment (akerouanton) [reply libnetwork/ipams/defaultipam/address_space.go:51]: `slices.CompactFunc` works a bit differently. It expects a strict equality as it doesn't compare to the last non-duplicate found, but to 'current-1'. If you have the following subnets:

1. `10.0.0.0/8`
2. `10.0.0.0/16`
3. `10.10.0.0/16`

It tries to compare s1 == s2, and then s2 == s3. That's not what we want.

Comment (corhere) [reply libnetwork/ipams/defaultipam/address_space.go:51]: That's too bad. I don't like that `slices.Delete` is being called in a loop:
> Delete is O(len(s)-i)

Therefore the worst case time complexity is O(N^2).

[It is doable in O(len(predefined)) time.](https://go.dev/wiki/SliceTricks#in-place-deduplicate-comparable)

File: libnetwork/ipams/defaultipam/structures_test.go [hunk 4]
```diff
@@ -0,0 +1,32 @@
...
+
+import (
+	"net/netip"
+	"testing"
+
+	"github.com/docker/docker/libnetwork/internal/netiputil"
+	"gotest.tools/v3/assert"
+)
+
+func TestDoubleCursor(t *testing.T) {
```
Comment (corhere) [inline libnetwork/ipams/defaultipam/structures_test.go:11]:
```suggestion
func TestMergeIter(t *testing.T) {
```

File: libnetwork/netutils/utils_linux.go [hunk 5]
```diff
@@ -5,34 +5,98 @@
...
+	return reserved
+}
+
+// queryOnLinkRoutes returns a list of on-link routes available on the host.
+// Only IPv4 prefixes are returned as there's no such thing as on-link
+// routes for IPv6.
+func queryOnLinkRoutes() []netip.Prefix {
+	family := netlink.FAMILY_V4
+
+	routes, err := ns.NlHandle().RouteList(nil, family)
```
Comment (corhere) [inline libnetwork/netutils/utils_linux.go:85]:
```suggestion
	routes, err := ns.NlHandle().RouteList(nil, netlink.FAMILY_V4)
```

File: libnetwork/ipams/defaultipam/address_space.go (hunk 2 above)
Comment (akerouanton) [reply libnetwork/ipams/defaultipam/address_space.go]: Yeah, at first I thought `predefined` wouldn't be filled with that many entries to really matter. But better safe than sorry, I guess. That's now fixed.

File: libnetwork/ipams/defaultipam/address_space.go [hunk 6]
```diff
@@ -2,36 +2,64 @@ package defaultipam
...
+		if predefined[j].Overlaps(predefined[i].Base) {
+			continue
+		}
+		j++
+		predefined[j] = predefined[i]
+	}
+
+	if len(predefined) > j {
+		j++
+	}
```
Comment (corhere) [inline libnetwork/ipams/defaultipam/address_space.go:52]: Any nonzero pointers in the backing array between `predefined[j:len(predefined)]` are considered alive references for GC purposes, even after reslicing. The tail of the slice needs to be zeroed out to avoid a memory leak.

```suggestion
	}
	clear(predefined[j:len(predefined)])
```

File: libnetwork/drivers/bridge/bridge_linux_test.go [hunk 7]
```diff
@@ -194,17 +197,21 @@ func compareBindings(a, b []types.PortBinding) bool {
 	return true
 }
 
+var a, _ = defaultipam.NewAllocator(ipamutils.GetLocalScopeDefaultNetworks(), nil)
```
Comment (corhere) [inline libnetwork/drivers/bridge/bridge_linux_test.go:200]: Why is this allocator package-scoped? It doesn't look like `getIPv4Data` used to have any (local) state which carried between tests, so why change it? None of the allocations are released; is there not a risk of running out?

**Review by corhere — APPROVED** [review]

**Review by robmry — APPROVED** [review]
