### PR TITLE
Fix download-frozen-image-v2

### LINKED ISSUE #50655: CI is broken on loading / using frozen images on x86
### Description

relates to:

- https://github.com/moby/moby/pull/50292#issuecomment-3161847227
- https://github.com/moby/moby/pull/50645#issuecomment-3161726006

CI appears to be broken w.r.t. the frozen images; could be either some path issue, or something else (could newer Dockerfile front-end use the new fancy sub-variants for x86 for example? `TARGETVARIANT`); https://github.com/moby/moby/blob/28df7815149571b3d3d32e26c32462a03b5b9d17/Dockerfile#L110-L120

Docker info doesn't show those;

```
   Kernel Version: 6.11.0-1018-azure
   Operating System: Ubuntu 24.04.2 LTS
   OSType: linux
   Architecture: x86_64
```

Integration tests;

```
Building test suite binary /go/src/github.com/docker/docker/integration/service/test.main
Building test suite binary /go/src/github.com/docker/docker/integration/session/test.main
Building test suite binary /go/src/github.com/docker/docker/integration/system/test.main
Building test suite binary /go/src/github.com/docker/docker/integration/volume/test.main
---> Making bundle: .integration-daemon-start (in bundles/test-integration)
Using test binary /usr/local/cli-integration/docker
# DOCKER_EXPERIMENTAL is set: starting daemon with experimental features enabled! 
Starting apparmor (via systemctl): apparmor.service.
Starting dockerd
INFO: Waiting for daemon to start...

Running integration-test (iteration 1)
Running /go/src/github.com/docker/docker/integration/build (amd64.docker.docker.integration.build) flags=-test.v -test.timeout=10m   -test.coverprofile=/go/src/github.com/docker/docker/bundles/test-integration/amd64-docker-docker-integration-build-coverage.out
panic: error loading frozen images: unable to resolve platform: unexpected end of JSON input

goroutine 1 [running, locked to thread]:
github.com/moby/moby/v2/integration/build.TestMain(0xc0000ce5a0)
	/go/src/github.com/docker/docker/integration/build/main_test.go:38 +0x1e9
main.main()
	_testmain.go:97 +0xa8

goroutine 12 [runnable]:
runtime.goexit1()
	/usr/local/go/src/runtime/proc.go:4313 +0x9d
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1701 +0x6
created by go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp.(*client).contextWithStop in goroutine 7
	/go/src/github.com/docker/docker/vendor/go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp/client.go:382 +0xe5

goroutine 15 [IO wait]:
internal/poll.runtime_pollWait(0x7f895dfe8ed0, 0x72)
	/usr/local/go/src/runtime/netpoll.go:351 +0x85
internal/poll.(*pollDesc).wait(0xc00022d680?, 0xc00051d000?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00022d680, {0xc00051d000, 0x1000, 0x1000})
	/usr/local/go/src/internal/poll/fd_unix.go:165 +0x27a
net.(*netFD).Read(0xc00022d680, {0xc00051d000?, 0x408494?, 0x0?})
	/usr/local/go/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc00019a7c8, {0xc00051d000?, 0x40828f?, 0xc0005536e0?})
	/usr/local/go/src/net/net.go:194 +0x45
net/http.(*persistConn).Read(0xc0005505a0, {0xc00051d000?, 0x7f49c5?, 0x15c7500?})
	/usr/local/go/src/net/http/transport.go:2122 +0x47
bufio.(*Reader).fill(0xc00055c180)
	/usr/local/go/src/bufio/bufio.go:113 +0x103
bufio.(*Reader).Peek(0xc00055c180, 0x1)
	/usr/local/go/src/bufio/bufio.go:152 +0x53
net/http.(*persistConn).readLoop(0xc0005505a0)
	/usr/local/go/src/net/http/transport.go:2275 +0x172
created by net/http.(*Transport).dialConn in goroutine 13
	/usr/local/go/src/net/http/transport.go:1944 +0x174f

goroutine 16 [select]:
net/http.(*persistConn).writeLoop(0xc0005505a0)
	/usr/local/go/src/net/http/transport.go:2590 +0xe7
created by net/http.(*Transport).dialConn in goroutine 13
	/usr/local/go/src/net/http/transport.go:1945 +0x17a5

=== Failed
```

Tests;

```
=== RUN   TestBuildUserNamespaceValidateCapabilitiesAreV2
Loaded image: busybox:latest
Loaded image: busybox:glibc
Loaded image: debian:bookworm-slim
Error unpacking image debian:bookworm-slim: apply layer error for "docker.io/library/debian:bookworm-slim": wrong diff id calculated on extraction "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
Loaded image: hello-world:latest
Loaded image: arm32v7/hello-world:latest
Loaded image: hello-world:amd64
Loaded image: hello-world:arm64
    build_userns_linux_test.go:77: assertion failed: error is not nil: apply layer error for "": wrong diff id calculated on extraction "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
--- FAIL: TestBuildUserNamespaceValidateCapabilitiesAreV2 (0.89s)
FAIL
```

Error looks to come from containerd vendor; not sure why the `i.Name()` is empty, but maybe that's expected https://github.com/moby/moby/blob/0aa8fe0bf949cbccab74414cb091728854be0d7d/vendor/github.com/containerd/containerd/v2/client/image.go#L335-L338

Also see https://github.com/moby/moby/pull/50292#issuecomment-3161847227

### PR DESCRIPTION
**Pull request by vvoland**
- fixes: https://github.com/moby/moby/issues/50655
- duplicated by / closes https://github.com/moby/moby/pull/50663
- closes https://github.com/moby/moby/pull/50658
- closes https://github.com/moby/moby/pull/50656

## download-frozen-image-v2: Use curl -L
    
Passing the Auth to the redirected location was fixed in curl 7.58: https://curl.se/changes.html#7_58_0 so we no longer need the extra handling and can just use `-L` to let curl handle redirects.
    

## download-frozen-image-v2: handle 307 responses without decimal
    
Correctly parse HTTP response that doesn't contain an HTTP version with a decimal place:

```
< HTTP/2 307
```

The previous version would only match strings like `HTTP/2.0 307`.

### CODE REVIEW

**Comment by crazy-max** [comment]
Ah we are rate-limited https://github.com/moby/moby/actions/runs/16813272998/job/47623886544?pr=50662#step:8:463 :man_facepalming:

**Review by crazy-max — APPROVED** [review]

File: contrib/download-frozen-image-v2.sh [hunk 1]
```diff
@@ -72,30 +72,11 @@ fetch_blob() {
...
-			echo >&2 "error: failed fetching '$image' blob '$digest'"
-			echo "$curlHeaders" | head -1 >&2
-			return 1
-		fi
-
-		curl -fSL "${curlArgs[@]}" \
-			"$blobRedirect" \
-			-o "$targetFile"
-	fi
+	curl -L -S "${curlArgs[@]}" \
```
Comment (thaJeztah) [inline contrib/download-frozen-image-v2.sh:75]: We can use `-fsSL` now then I think? (like the other ones); doing so prevents capturing garbage if there's a failure (`-f` does a "fail fast" - preventing output to be captured on failure, and `-s` runs "silent" (but prints errors if they happen due to the other ones).

Comment (thaJeztah) [reply contrib/download-frozen-image-v2.sh:75]: (fine for a follow-up though)

**Review by austinvazquez — APPROVED** [review]

File: contrib/download-frozen-image-v2.sh (hunk 1 above)
Comment (yosifkit) [reply contrib/download-frozen-image-v2.sh:75]: Should probably also drop the `-D-` to not dump headers to `stdout`.

Comment (thaJeztah) [reply contrib/download-frozen-image-v2.sh:75]: Yes, I was eyeing some of that as well, and got confused "are we capturing `stdout` here, or are we outputting to a file?

But it was a long day, and this fixed the immediate problem, so I left that for "let's look into that later; we now know the cause of the problem, and it's for our own CI only, so let's fix that first".


(contributions welcome though if you want to dig in! <3)
