### PR TITLE
fix conversion of anonymous volumes in compose-file

### LINKED ISSUE #29512: docker stack deploy fails on anonymous volumes
**Description**

`docker stack deploy` fail to deploy a `docker-compose.yml` file if it defines an anonymous volume for a service.

**Steps to reproduce the issue:**

Create this compose file, and try to deploy it;

```yaml
version: "3.0"
services:
  main:
    image: nginx:alpine
    volumes:
      - "/foo/bar"
```

```bash
$ cat > docker-compose.yml <<EOF
version: "3.0"
services:
  main:
    image: nginx:alpine
    volumes:
      - "/foo/bar"
EOF

$ docker stack deploy --compose-file=docker-compose.yml foo

Creating network foo_default
undefined volume:
```

**Describe the results you received:**

An error;

```
undefined volume:
```

**Describe the results you expected:**

The compose-file to be deployed

**Additional information you deem important (e.g. issue happens only occasionally):**

The error seems to happen during the conversion from classic "volume" notation to a "mount" specification;
https://github.com/docker/docker/blob/914a72541fecfc2e4312015befb7200dd05f4462/cli/compose/convert/volume.go#L61

**Output of `docker version`:**

Tested / reproduced on current master 4436a59

```
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.4
 Git commit:   4436a59
 Built:        Sun Dec 18 15:17:03 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.14.0-dev
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.4
 Git commit:   4436a59
 Built:        Sun Dec 18 15:17:03 2016
 OS/Arch:      linux/amd64
 Experimental: false
```

### PR DESCRIPTION
**Pull request by thaJeztah**
the `convertVolumeToMount()` function did not take
anonymous volumes into account when converting
volume specifications to bind-mounts.

this resulted in the conversion to try to
look up an empty "source" volume, which
lead to an error;

    undefined volume:

this patch distinguishes "anonymous"
volumes from bind-mounts and named-volumes,
and skips further processing if no source
is defined (i.e. the volume is "anonymous").

fixes https://github.com/docker/docker/issues/29512

**- What I did**

Updated `convertVolumeToMount() to take anonymous volumes into account

**- How I did it**

Behind my computer, in pyjamas

**- How to verify it**

Deploy a docker-compose file that uses an anonymous volume, and verify that no error is produced, and the service is running afterwards;

```bash
$ cat > docker-compose.yml <<EOF
version: "3.0"
services:
  main:
    image: nginx:alpine
    volumes:
      - "/foo/bar"
EOF

$ docker stack deploy --compose-file=docker-compose.yml foo
Creating network foo_default
Creating service foo_main

$  docker service ps foo_main
ID            NAME        IMAGE         NODE          DESIRED STATE  CURRENT STATE           ERROR  PORTS
sr0u5f6vqjhr  foo_main.1  nginx:alpine  5945fab4e8ad  Running        Running 54 seconds ago
```

**- Description for the changelog**

Not needed; this functionality is new in 1.13

**- A picture of a cute animal (not mandatory but encouraged)**

mouse

### CODE REVIEW

File: cli/compose/convert/volume.go [hunk 1]
```diff
@@ -42,7 +42,15 @@ func convertVolumeToMount(volumeSpec string, stackVolumes volumes, namespace Nam
 	case 1:
 		target = parts[0]
 	default:
-		return mount.Mount{}, fmt.Errorf("invald volume: %s", volumeSpec)
+		return mount.Mount{}, fmt.Errorf("invalid volume: %s", volumeSpec)
+	}
+
+	if source == "" {
```
Comment (thaJeztah) [inline cli/compose/convert/volume.go]: actuall, just thinking; should we check `len(parts)` here as well, to invalidate `-v :/foo/bar`?

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

File: cli/compose/convert/volume.go [hunk 2]
```diff
@@ -41,8 +47,14 @@ func convertVolumeToMount(volumeSpec string, stackVolumes volumes, namespace Nam
 		target = parts[1]
 	case 1:
 		target = parts[0]
-	default:
-		return mount.Mount{}, fmt.Errorf("invald volume: %s", volumeSpec)
```
Comment (thaJeztah) [inline cli/compose/convert/volume.go]: This didn't validate anything, because `SplitN` is used, so there can never be more than 3 parts, and an empty string will still be 1 part

**Comment by thaJeztah** [comment]
Added a second commit with simple validation and a unit test for that

**Review by dnephin — APPROVED** [review]
LGTM

**Comment by dnephin** [comment]
If we cherry-pick this into 1.13 I suggest we take #29003 along with it, or it's not going to merge.

**Comment by thaJeztah** [comment]
Good point; if not, we should have a or against the 1.13 branch i guess

**Comment by thaJeztah** [comment]
"cherry picked" through https://github.com/docker/docker/pull/29859
