### PR TITLE
Set Composefile WorkingDir to dirname of the composefile.

### LINKED ISSUE #32452: secrets file not relative to compose file location
**Description**

When configuring secrets in compose file v3, the file: path is not resolved relative to location of the compose file. The secrets file path is resolved relative to the current directory from where the command is executed. This is inconsistent with how other paths in compose file are resolved (e.g., volume paths or context paths).

**Steps to reproduce the issue:**
1. Create compose v3 file with `secrets.<name>.file = <secret file path>`
2. Run `docker stack deploy --compose-file=<compose file path> <stack>` from a different directory than where the compose file is located
3. Observe error `open <secret file path>: The system cannot find the path specified.`
4. Run `docker stack deploy --compose-file=<compose file path> <stack>` from the same directory as compose file
5. Observe no error.

**Describe the results you received:**
`open <secret file path>: The system cannot find the path specified.`
when running `docker stack deploy` with a compose file in a different directory and the secret file located relative to the compose file.

**Describe the results you expected:**
`docker stack deploy` resolves secret file relative to compose file.

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 16
 Running: 0
 Paused: 0
 Stopped: 16
Images: 2552
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1877
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: p75loi3w18lwn81e5vls76da3
 Is Manager: true
 ClusterID: ub5bn35up6w8n5wrpm21p2wky
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.65.2
 Manager Addresses:
  192.168.65.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.12-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934 GiB
Name: moby
ID: BVXG:BRUM:3JDA:5JYQ:O2UQ:C5RW:NNVK:ROR5:B64Z:XZWN:CLHE:WVA2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker for Windows, Hyper-V isolation, moby host

### PR DESCRIPTION
**Pull request by dnephin**
Fixes #32452

### CODE REVIEW

File: cli/command/stack/deploy_composefile.go [hunk 1]
```diff
@@ -17,10 +17,11 @@ import (
 	dockerclient "github.com/docker/docker/client"
 	"github.com/pkg/errors"
 	"golang.org/x/net/context"
+	"path/filepath"
```
Comment (vdemeester) [inline cli/command/stack/deploy_composefile.go]: nit: should be above 👼

**Review by vdemeester — APPROVED** [review]
LGTM 👼
Might be breaking some user assumptions (cc @thaJeztah) but it make it consistent with `docker-compose` behaviour

File: cli/command/stack/deploy_composefile_test.go [hunk 2]
```diff
@@ -0,0 +1,26 @@
+package stack
+
+import (
+	"github.com/docker/docker/pkg/testutil/assert"
+	"github.com/docker/docker/pkg/testutil/tempfile"
+	"os"
+	"path/filepath"
```
Comment (cpuguy83) [inline cli/command/stack/deploy_composefile_test.go]: no goimports?

Comment (dnephin) [inline cli/command/stack/deploy_composefile_test.go]: I don't think goimports understands our "two sections" style of imports, I wish it did, because I don't think this is something we should have to do manually. It just sorts them alphabetically. I have goimports run as a pre-commit hook.

Comment (cpuguy83) [inline cli/command/stack/deploy_composefile_test.go]: It does it for me?

**Comment by dnephin** [comment]
Ping.

Build is green. This is a small change to fix compatibility with docker-compose

**Review by tonistiigi — APPROVED** [review]
LGTM
