### PR TITLE
PublishAllPorts: don't crash with nil PortBindings

### LINKED ISSUE #51620: panic: "assignment to entry in nil map" in daemon/network.go during start with PublishAllPorts=true
### Description

I encountered a hard crash (panic) in the Docker Daemon `dockerd` when starting a container. The crash occurs specifically when a container is configured with `PublishAllPorts: true` (equivalent to `-P`) but `PortBindings` is passed as `null` in the JSON payload.

This was discovered using the Rust `testcontainers` library (which creates the container via API with `PortBindings: null`), but it implies a regression in how the daemon handles nil maps during the start sequence. The CLI works fine (likely because it initializes the map as empty `{}` rather than `null`).

The API connection is severed (`EOF`), and the `dockerd` process crashes/restarts.

### Reproduce

```
#!/bin/bash
docker pull redis:latest > /dev/null 2>&1

# 1. Create Container (PortBindings: null)
ID=$(curl -s --unix-socket /var/run/docker.sock \
  -H "Content-Type: application/json" \
  -X POST http://localhost/v1.52/containers/create \
  -d '{
    "Image": "redis:latest",
    "ExposedPorts": { "6379/tcp": {} },
    "HostConfig": { "PublishAllPorts": true, "PortBindings": null }
  }' | jq -r .Id)

echo "Created Container: $ID"

curl -v --unix-socket /var/run/docker.sock \
  -X POST "http://localhost/v1.52/containers/$ID/start"
```
Run this script and then check `journalctl -u docker -n 50`, you will see the panic.

### Expected behavior

At the very least it should not cause the daemon to panic. This did NOT panic prior to 29.x.
The daemon should handle `PortBindings: null` gracefully (treating it as an empty map) when `PublishAllPorts` is true.

### docker version

```bash
Client: Docker Engine - Community
 Version:           29.1.1
 API version:       1.52
 Go version:        go1.25.4
 Git commit:        0aedba5
 Built:             Fri Nov 28 11:36:27 2025
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          29.1.1
  API version:      1.52 (minimum version 1.44)
  Go version:       go1.25.4
  Git commit:       9a84135
  Built:            Fri Nov 28 11:33:12 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v2.2.0
  GitCommit:        1c4457e00facac03ce1d75f7b6777a7a851e5c41
 runc:
  Version:          1.3.4
  GitCommit:        v1.3.4-0-gd6d73eb8
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    29.1.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.30.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.40.3
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 5
  Running: 0
  Paused: 0
  Stopped: 5
 Images: 4
 Server Version: 29.1.1
 Storage Driver: overlay2
  Backing Filesystem: btrfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 CDI spec directories:
  /etc/cdi
  /var/run/cdi
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1c4457e00facac03ce1d75f7b6777a7a851e5c41
 runc version: v1.3.4-0-gd6d73eb8
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.17.8-300.fc43.x86_64
 Operating System: Fedora Linux 43 (Workstation Edition)
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.26GiB
 Name: fedora
 ID: ce3fad9b-7915-4ad6-b531-d5081f3b1d23
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
 Firewall Backend: iptables+firewalld
```

#### Log Output

```
Nov 29 02:19:09 fedora dockerd[60398]: 2025/11/29 02:19:09 http: panic serving @: assignment to entry in nil map
Nov 29 02:19:09 fedora dockerd[60398]: goroutine 884 [running]:
Nov 29 02:19:09 fedora dockerd[60398]: net/http.(*conn).serve.func1()
Nov 29 02:19:09 fedora dockerd[60398]:          /usr/local/go/src/net/http/server.go:1943 +0xd3
Nov 29 02:19:09 fedora dockerd[60398]: panic({0x55e6e768bd00?, 0x55e6e92afda0?})
Nov 29 02:19:09 fedora dockerd[60398]:          /usr/local/go/src/runtime/panic.go:783 +0x132
Nov 29 02:19:09 fedora dockerd[60398]: [github.com/moby/moby/v2/daemon.buildPortsRelatedCreateEndpointOptions(0xc000ad6008](https://github.com/moby/moby/v2/daemon.buildPortsRelatedCreateEndpointOptions(0xc000ad6008), 0x55e6e7b90120?, 0xc000690780)
Nov 29 02:19:09 fedora dockerd[60398]:          /root/rpmbuild/BUILD/docker-ce-29.1.1-build/src/engine/daemon/network.go:1047 +0xae6
Nov 29 02:19:09 fedora dockerd[60398]: [github.com/moby/moby/v2/daemon.buildCreateEndpointOptions(0xc000ad6008](https://github.com/moby/moby/v2/daemon.buildCreateEndpointOptions(0xc000ad6008), 0xc00079f1e0, 0xc0013b78f0, 0xc000690780, {0x0, 0x0, 0x0?})
Nov 29 02:19:09 fedora dockerd[60398]:          /root/rpmbuild/BUILD/docker-ce-29.1.1-build/src/engine/daemon/network.go:988 +0x2bf
Nov 29 02:19:09 fedora dockerd[60398]: [github.com/moby/moby/v2/daemon.(*Daemon).connectToNetwork(0xc0007d0a08](https://github.com/moby/moby/v2/daemon.(*Daemon).connectToNetwork(0xc0007d0a08), {0x55e6e7bf0538, 0xc0011706f0}, 0xc0007e0008, 0xc000ad6008, {0x55e6e6e694cd, 0x6}, 0xc0013b78f0)
Nov 29 02:19:09 fedora dockerd[60398]:          /root/rpmbuild/BUILD/docker-ce-29.1.1-build/src/engine/daemon/container_operations.go:738 +0x96e
```

Related issue in testcontainers-rs https://github.com/testcontainers/testcontainers-rs/issues/884

### PR DESCRIPTION
**Pull request by robmry**
**- What I did**

- fix https://github.com/moby/moby/issues/51620
- Introduced by https://github.com/moby/moby/pull/51586

**- How I did it**

**- How to verify it**

**- Human readable description for the release notes**

```markdown changelog
- Prevent a crash when making an API request with `HostConfig.PublishAllPorts` set (`-P`), and no port bindings
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by zhangguanzhang — APPROVED** [review]

File: integration/networking/bridge_linux_test.go [hunk 1]
```diff
@@ -2139,3 +2141,18 @@ func TestGatewayErrorOnNetDisconnect(t *testing.T) {
...
 	assert.Check(t, is.Contains(ctrInsp.NetworkSettings.Networks, "n2"))
 }
+
+// Regression test for https://github.com/moby/moby/issues/51620
+func TestPublishAllWithNilPortBindings(t *testing.T) {
+	ctx := setupTest(t)
+	c := testEnv.APIClient()
+
+	imgWithExpose := container.WithImage(build.Do(ctx, t, c,
+		fakecontext.New(t, "", fakecontext.WithDockerfile("FROM busybox\nEXPOSE 80/tcp\n"))))
```
Comment (thaJeztah) [inline integration/networking/bridge_linux_test.go:2151]: Silly question; does this require the _image_ to have the exposed ports set, or would the same work when creating the container with `--expose` ?

(Mostly looking if we can avoid using `docker build` as part of test preparation if it's not needed)

**Review by thaJeztah — APPROVED** [review]
LGTM


left one question, but definitely not a blocker

**Review by vvoland — APPROVED** [review]

File: integration/networking/bridge_linux_test.go (hunk 1 above)
Comment (robmry) [reply integration/networking/bridge_linux_test.go:2151]: The same should work for a container `--expose` ... I did it this way because the build command in the test was trivial, and it seemed more likely to be testing something a user would do (I'm guessing `--expose` with a `-P` on the container is unusual, compared with `-p`).

The test runs in < 1s, but the build is a bit log-spammy. Can change it, or test both ways?

**Review by austinvazquez — APPROVED** [review]

File: integration/networking/bridge_linux_test.go (hunk 1 above)
Comment (thaJeztah) [reply integration/networking/bridge_linux_test.go:2151]: Yeah, either way is probably fine; I recall we had some cases where the build itself was more problematic than the test.
