### PR TITLE
Fix for Issue 11285: warning message displayed when updating an existing image

### LINKED ISSUE #11285: docker load clobbers the name of the existing image
Description of problem:
Given an image "foo:latest" with ID 1234 already in docker, docker load < foo.tar with ID 5678 (same name, different ID) clobbers the existing name (of ID 1234) to "<none>".  Since images are most often referenced by name, it's not a very nice thing to do w/o being documented or issuing a "Warning: image foo already exists, renaming to <none>".

Version-Release number of selected component (if applicable):
docker-1.4.1-12.el7.x86_64

How reproducible:
Minor prep. required.

Steps to Reproduce:
1. docker run --name foo rhel7 /bin/true
2. docker commit foo foobar
   (note image ID)
3. docker save foobar > foobar.tar
4. docker rm foo
5. docker rmi foobar
6. docker run --name bar rhel7 /bin/false
7. docker commit bar foobar
   (note image ID)
8. docker rm bar
9. docker load < foobar.tar
10. docker images

Actual results:
[root@dockertest ~]# docker images
REPOSITORY                         TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
foobar                             latest              17be95040cc3        13 seconds ago      147 MB
...cut...
[root@dockertest ~]# docker load < foobar.tar
[root@dockertest ~]# echo $?
0
[root@dockertest ~]# docker images
REPOSITORY                         TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
<none>                             <none>              17be95040cc3        29 seconds ago      147 MB
foobar                             latest              90e44769e068        2 minutes ago       147 MB

Expected results:
Allow the load, but issue "Warning: existing image will be renamed <none>"
-or-
Document this in a "note" in the docker load man page
-or-
Fail the load with a 'image foobar already exists'

Additional Info: Docker load creates a new image with {ID: 5678} but also clobbers the name of the existing image {ID: 1234}

### PR DESCRIPTION
**Pull request by shishir-a412ed**
Fixes #11285

### CODE REVIEW

**Comment by shishir-a412ed** [comment]
Fixes #11285

**Comment by tiborvass** [comment]
Putting in design review to make sure the solution to the issue is the correct one.

**Comment by shishir-a412ed** [comment]
@jlhawn Let me know what do you think of replacing the existing image name to <imagename_id>:<tag> rather than <none>:<none>.

So for example if someone is loading busybox:latest with ID (4349ec6bf114) and there is already an existing image busybox:latest with ID (f7189223014c). 

The existing one should become busybox_f7189223014c:latest
and the new one busybox:latest

Shishir

**Comment by jlhawn** [comment]
After looking at the patch, it looks like you just print the message to stdout on the daemon. We should probably use the regular logging package *and* figure out how to display it to the client (would require a refactor because the `(*TagStore).Set()` method doesn't take a job output/stream formatter argument.)

@shishir-a412ed as for your suggestion:

> Let me know what do you think of replacing the existing image name to : rather than :.
>
> So for example if someone is loading busybox:latest with ID (4349ec6bf114) and there is already an existing image busybox:latest with ID (f7189223014c).
>
> The existing one should become busybox_f7189223014c:latest
and the new one busybox:latest

hmm, changing the full name of the repository is kind of weird. Can we just change the tag to be the image ID? ex: `busybox:latest -> busybox:f7189223014c`. In fact, I think you can *already* refer to the image this way anyway. Let me try it... yep:

```bash
$ docker images busybox
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
busybox             latest              4986bf8c1536        10 weeks ago        2.433 MB
...
$ docker run --rm busybox:4986bf8c1536 echo 'it works!'
it works!
```

So, no need to do anything but display the info message to the user, in my opinion.

**Comment by shishir-a412ed** [comment]
@jlhawn the reason for renaming is to avoid getting it named to <none>:<none>.
How do I know that <none>:<none> stands for a busybox image (older version) ?

Currently if I do a `docker images --all` I see a lot of <none>:<none> images which resulted due to name conflicts. I think `busybox:latest -> busybox: f7189223014c` should work, although I have to implement that part.

Do you want that change to be a part of separate PR or just add another commit in this PR ?
I ll take a look at the logging facility to update the warning message.

**Comment by shishir-a412ed** [comment]
@jlhawn I discussed with my QE team, warning message is good enough for our problem.
I have redirected the warning message to the client side.

Please take a look and let me know if this works for you.

Shishir

File: graph/tags.go [hunk 1]
```diff
@@ -222,6 +223,15 @@ func (store *TagStore) Set(repoName, tag, imageName string, force bool) error {
...
+		if id, exists := store.Repositories[repoName][tag]; exists {
+
+			if id != img.ID && job != nil && job.Name == "load" {
+				str := "The image " + repoName + ":" + tag + " already exists, renaming the old one with id " + id[:12] + " to <none>:<none>\n"
+				job.Stdout.Write([]byte(str))
+			}
+		}
+
 		repo = r
 		if old, exists := store.Repositories[repoName][tag]; exists && !force {
```
Comment (jlhawn) [inline graph/tags.go]: Looks like there's already a check here, you should be able to re-use this block of code.

also note that it's not necessary here to use `store.Repositories[repoName]` as this variable was already declared/set in the outer `if` statement as `r`.

and let's not special case the message just for the "load" job. It's useful to have in general. We can also get rid of the `job` argument to this method and just use an `io.Writer`.

Comment (shishir-a412ed) [inline graph/tags.go]: If you are talking about line 227, this one is the existing upstream code.
If you like I can change this to r[tag] instead of store.Repositories[repoName][tag] and see if that works.

**Comment by shishir-a412ed** [comment]
@jlhawn I have modified the code.

The reason I was receiving `job *engine.Job` as an argument, and not `job.Stdout`, and putting a check just on "load" was because it was throwing a lot of errors in the test suite. Probably it was running this warning message for other use cases and breaking the expected behaviour.

I have modified the code to receive io.Writer. Lets wait and see if Jenky breaks.

Shishir

**Comment by jlhawn** [comment]
Design looks good to me: the "tag set" job can now have messages written to its stdout and this is now used to display a message to the Client when there's a conflict in `docker load`.

Code changes LGTM as well.

@tiborvass please take a look and move into code-review if the design is okay with you.

**Comment by shishir-a412ed** [comment]
@LK4D4 I have made the requested changes, what we discussed on irc.

Adding @jlhawn too. I have seen this jenkins error before on this PR. This doesn't seem to be related to this PR. Let me know if it is and I ll take a look.

**Comment by jlhawn** [comment]
@shishir-a412ed I triggered a rebuild and janky passed ;-)

**Comment by shishir-a412ed** [comment]
@jlhawn Awesome !!

**Comment by LK4D4** [comment]
@shishir-a412ed Super nice that you reduced your diff.

**Comment by LK4D4** [comment]
ping @tiborvass

**Comment by shishir-a412ed** [comment]
@tiborvass Can we merge this ?

**Comment by icecrime** [comment]
Moving to code review (hoping @tiborvass won't have any objection).

File: graph/tags.go [hunk 2]
```diff
@@ -241,8 +246,15 @@ func (store *TagStore) Set(repoName, tag, imageName string, force bool) error {
 	repoName = registry.NormalizeLocalName(repoName)
 	if r, exists := store.Repositories[repoName]; exists {
 		repo = r
-		if old, exists := store.Repositories[repoName][tag]; exists && !force {
-			return fmt.Errorf("Conflict: Tag %s is already set to image %s, if you want to replace it, please use -f option", tag, old)
+		if old, exists := store.Repositories[repoName][tag]; exists {
+
+			if old != img.ID && out != nil {
+				str := "The image " + repoName + ":" + tag + " already exists, renaming the old one with id " + old[:12] + " to <none>:<none>\n"
+				out.Write([]byte(str))
```
Comment (icecrime) [inline graph/tags.go]: Am I missing something or `out` can be `nil` here (especially when called from `TagStore.Set`)?

File: graph/load.go [hunk 3]
```diff
@@ -68,7 +68,7 @@ func (s *TagStore) CmdLoad(job *engine.Job) engine.Status {
 
 		for imageName, tagMap := range repositories {
 			for tag, address := range tagMap {
-				if err := s.Set(imageName, tag, address, true); err != nil {
+				if err := s.SetLoad(imageName, tag, address, true, job.Stdout); err != nil {
```
Comment (icecrime) [inline graph/load.go]: Sorry but I don't get it: if `SetLoad` returns an error, why isn't it reported to the client? Why do we need to pass the `job.Stdout` and emit a new line of output there, isn't the solution just to write the error result to `w` in `postImagesLoad`?

Comment (shishir-a412ed) [inline graph/load.go]: @icecrime it's a warning message not an error. We still want the `docker load` to go through.

File: graph/tags.go (hunk 2 above)
Comment (tiborvass) [inline graph/tags.go]: this should be `fmt.Fprintf(out, "The image %s:%s already exists, renaming the old one with ID %s to empty string\n", repoName, tag, old[:12])`

File: graph/load.go (hunk 3 above)
Comment (icecrime) [inline graph/load.go]: But does it mean that when it doesn't go through (such as needing `force`), we're gonna get both a warning and an error?

Comment (shishir-a412ed) [inline graph/load.go]: @icecrime it depends ... if the tar ball being loaded has a new content i.e image ID's are different, but the image name: tag of the old and new images are same.

The idea is to show a display message to user, so that he doesn't get confused when the old image with the same name is renamed to none:none.

File: graph/tags.go (hunk 2 above)
Comment (shishir-a412ed) [inline graph/tags.go]: @tiborvass I have made the change. Please check now.

File: graph/tags.go [hunk 4]
```diff
@@ -219,6 +220,10 @@ func (store *TagStore) Delete(repoName, ref string) (bool, error) {
 }
 
 func (store *TagStore) Set(repoName, tag, imageName string, force bool) error {
+	return store.SetLoad(repoName, tag, imageName, force, nil)
+}
+
+func (store *TagStore) SetLoad(repoName, tag, imageName string, force bool, out io.Writer) error {
```
Comment (tiborvass) [inline graph/tags.go]: @shishir-a412ed why not make these one `Set` method ? Just add the `out` param.

Comment (shishir-a412ed) [inline graph/tags.go]: @LK4D4 would you like to answer @tiborvass ?

Comment (tiborvass) [inline graph/tags.go]: lol

File: graph/tags.go [hunk 5]
```diff
@@ -241,8 +246,16 @@ func (store *TagStore) Set(repoName, tag, imageName string, force bool) error {
...
-		if old, exists := store.Repositories[repoName][tag]; exists && !force {
-			return fmt.Errorf("Conflict: Tag %s is already set to image %s, if you want to replace it, please use -f option", tag, old)
+		if old, exists := store.Repositories[repoName][tag]; exists {
+
+			if old != img.ID && out != nil {
+
+				fmt.Fprintf(out, "The image %s:%s already exists, renaming the old one with ID %s to empty string\n", repoName, tag, old[:12])
+
+			}
+			if !force {
```
Comment (dmcgowan) [inline graph/tags.go]: Why is this check after the output statement since no changes are saved if this condition is true?

Comment (shishir-a412ed) [inline graph/tags.go]: @dmcgowan what do you mean ? Can you elaborate a bit more.
Do you mean why display the warning message and then throw the error too if `force` flag is false ?

Comment (dmcgowan) [inline graph/tags.go]: > Do you mean why display the warning message and then throw the error too if force flag is false ?

Yes, when the error is thrown, it doesn't appear anything is renamed

Comment (shishir-a412ed) [inline graph/tags.go]: @dmcgowan I have made the changes.

**Comment by dmcgowan** [comment]
Tested and I am seeing the error message, I am confused on how the force flag works since `docker load` does not have a force flag.

~~~
Usage: docker load [OPTIONS]

Load an image from a tar archive on STDIN

  --help=false       Print usage
  -i, --input=       Read from a tar archive file, instead of STDIN
~~~

When I just run, it seems to work.  Not sure how to test "unforced" though

~~~
$ docker load < /tmp/foobar.tar
The image foobar:latest already exists, renaming the old one with ID 883f763834c1 to empty string
~~~

**Comment by shishir-a412ed** [comment]
@dmcgowan AFAIK docker tag command also makes a call to the `Set` method, and it has the `force` flag.

**Comment by dmcgowan** [comment]
Alright, thanks for the clarification.  Is it expected that issuing a `-f` on tag won't show the message you added?

~~~
$ docker tag 883f763834c1 foobar
FATA[0000] Error response from daemon: Conflict: Tag latest is already set to image 6705fbab54cee055f6ef0239709284a024f8dd8b30c102d6596dcd405779fa2e, if you want to replace it, please use -f option
$ docker tag -f 883f763834c1 foobar
$
~~~

**Comment by shishir-a412ed** [comment]
@dmcgowan yes this change is only related to `docker load`

**Comment by dmcgowan** [comment]
LGTM

**Comment by dmcgowan** [comment]
ping @tiborvass

**Comment by tiborvass** [comment]
LGTM
