### PR TITLE
Fix environ substitutions in `docker commit --change ...`

### LINKED ISSUE #30538: docker commit -c does not expand from container/parent environment
**Description**

`docker commit -c` does not expand environment variables from parent images or the container, the way a `Dockerfile` does.

**Steps to reproduce the issue:**

```
bash-3.2$ grep '' -r .
./base/Dockerfile:FROM busybox
./base/Dockerfile:ENV ABC abc
./next/Dockerfile:FROM local/base
./next/Dockerfile:ENV DEF $ABC
bash-3.2$ docker build -t local/base base
Sending build context to Docker daemon 2.048 kB
Step 1/2 : FROM busybox
 ---> 7968321274dc
Step 2/2 : ENV ABC abc
 ---> Running in 469e22f566ec
 ---> 6cba68c627bc
Removing intermediate container 469e22f566ec
Successfully built 6cba68c627bc
bash-3.2$ docker build -t local/next next
Sending build context to Docker daemon 2.048 kB
Step 1/2 : FROM local/base
 ---> 6cba68c627bc
Step 2/2 : ENV DEF $ABC
 ---> Running in 2bbbd2c5d335
 ---> f2c0582b954c
Removing intermediate container 2bbbd2c5d335
Successfully built f2c0582b954c
bash-3.2$ docker inspect local/next | jq '.[].Config.Env'
[
  "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
  "ABC=abc",
  "DEF=abc"
]
bash-3.2$ docker create --name test-commit local/base
770c21912fdede7bf48ac93472b9521d8302e9051b6e3e21d5cba78cee552070
bash-3.2$ docker commit -c 'ENV DEF $ABC' test-commit local/test-commit
sha256:60448d42c689cf079cb3399d1a99f46acf496ebae89d406b17b00ec3e564ac5e
bash-3.2$ docker inspect local/test-commit | jq '.[].Config.Env'
[
  "DEF=",
  "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
  "ABC=abc"
]
bash-3.2$
```

**Describe the results you received:**

Expression `$ABC` was not expanded in the `docker commit -c` command, even though it was in the chained Dockerfile build.

**Describe the results you expected:**

`DEF=abc`, just as in the `local/next` chained-Dockerfile build.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 5
 Running: 1
 Paused: 0
 Stopped: 4
Images: 95
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 144
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.4-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.787 GiB
Name: moby
ID: ILWD:XNQW:SI6X:EQLJ:UDJA:ZQOC:EGRY:XGXD:OR66:NC6R:T6ZW:NHDB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 19
 Goroutines: 33
 System Time: 2017-01-28T22:05:15.595520577Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Using Docker for Mac 1.13.0, though I strongly suspect this issue lies inside the Docker daemon code (inside the Docker machine VM), not in the Mac client.

### PR DESCRIPTION
**Pull request by asottile**
The building machinery was being handed an uninitialized container
Config.  This changes it to use the target container's Config.

Resolves #30538

**- How to verify it**

#### before

```console
# cid=$(docker create ubuntu:xenial) && \
>     docker commit --change 'ENV PATH=/wat:$PATH' "$cid" test > /dev/null && \
>     docker rm "$cid" > /dev/null && \
>     docker inspect test --format='{{.Config.Env}}'
[PATH=/wat:]
```

#### after

```console
# cid=$(docker create ubuntu:xenial) && \
>    docker commit --change 'ENV PATH=/wat:$PATH' "$cid" test > /dev/null && \
>    docker rm "$cid" > /dev/null && \
>    docker inspect test --format='{{.Config.Env}}'
[PATH=/wat:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin]
```

**- Description for the changelog**
Fix environ substitutions in `docker commit --change ...`

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by asottile** [comment]
An aside: while working on this I noticed that 4 (**!**) different `Config` objects are in scope inside `Commit`:
- `container.Config`: (probably the only useful one)
- `newConfig`: `BuildFromConfig` return value (should probably be used the rest of the function?)
- `c.ContainerConfig`: ???
- `c.Config`: ???

lmk if you want me to attempt to clean this up as part of this change as well :)

**Comment by asottile** [comment]
My initial patch was:

```diff
diff --git a/daemon/commit.go b/daemon/commit.go
index 0053132..3482af9 100644
--- a/daemon/commit.go
+++ b/daemon/commit.go
@@ -149,7 +149,7 @@ func (daemon *Daemon) Commit(name string, c *backend.ContainerCommitConfig) (str
                defer daemon.containerUnpause(container)
        }
 
-       newConfig, err := dockerfile.BuildFromConfig(c.Config, c.Changes)
+       newConfig, err := dockerfile.BuildFromConfig(container.Config, c.Changes)
        if err != nil {
                return "", err
        }
```

The current patch imo is a little lower impact :)

File: integration-cli/docker_cli_commit_test.go [hunk 1]
```diff
@@ -125,7 +125,7 @@ func (s *DockerSuite) TestCommitChange(c *check.C) {
 	prefix = strings.ToUpper(prefix) // Force C: as that's how WORKDIR is normalized on Windows
 	expected := map[string]string{
 		"Config.ExposedPorts": "map[8080/tcp:{}]",
-		"Config.Env":          "[DEBUG=true test=1 PATH=/foo]",
+		"Config.Env":          "[PATH=/foo DEBUG=true test=1]",
```
Comment (asottile) [inline integration-cli/docker_cli_commit_test.go]: I was a bit puzzled why this changed until I thought more about it.  Now that the base configuration environ (`[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin]`) is being used to seed the new environ -- `--change PATH=/foo` will override the beginning element and then the others will append.

File: integration-cli/docker_cli_commit_test.go [hunk 2]
```diff
@@ -155,3 +155,17 @@ func (s *DockerSuite) TestCommitChangeLabels(c *check.C) {
...
+func (s *DockerSuite) TestCommitInheritEnv(c *check.C) {
+	dockerCmd(c, "run", "--name", "test", "busybox", "true")
+	dockerCmd(c, "commit",
+		"--change", "ENV PATH=/bin",
+		"test", "test-img-1")
+	dockerCmd(c, "run", "--name", "test2", "test-img-1", "true")
+	imageID, _ := dockerCmd(c, "commit",
+		"--change", "ENV PATH=/usr/bin:$PATH",
+		"test2", "test-img-2")
+	imageID = strings.TrimSpace(imageID)
```
Comment (asottile) [inline integration-cli/docker_cli_commit_test.go]: I decided to commit twice to make this test less dependent on the details of busybox (though I doubt that busybox's `PATH` is going to change any time soon)

**Comment by asottile** [comment]
I don't mean to be short but I find this a bit ridiculous:

```
03:59:21 The following new tests were added to integration-cli:
03:59:21 
03:59:21 +func (s *DockerSuite) TestCommitInheritEnv(c *check.C) {
03:59:21 
03:59:21 integration-cli is deprecated. Please add an API integration test to
03:59:21 ./integration/COMPONENT/. See ./TESTING.md for more details.
03:59:21 
03:59:21 Build step 'Execute shell' marked build as failure
```

There's 55kloc of `integration-cli` tests:

```
$ git ls-files -- integration-cli/ | xargs wc -l | tail -1
  55358 total
```

and a mere 2kloc of `integration` tests:

```
$ git ls-files -- integration/ | xargs wc -l | tail -1
 2051 total
```

There's _no_ examples of anything even remotely related to what I'm touching in `commit` in either unit tests (there's no `daemon/commit_test.go` even!) or integration tests -- adding an entire testsuite for this (imo quite complicated interaction between components _needing_ an integration test) seems very out of scope.

I get that the effort is in the direction of eliminating `integration-cli`, but there's a ton of friction to even start working in that direction!  Honestly my first gut on seeing that error message was, wellp I'll just delete the test then.

File: daemon/commit.go [hunk 3]
```diff
@@ -149,6 +149,11 @@ func (daemon *Daemon) Commit(name string, c *backend.ContainerCommitConfig) (str
 		defer daemon.containerUnpause(container)
 	}
 
+	// Ensure environ substitutions in commit use the container's image config
+	if len(c.Config.Env) == 0 {
+		c.Config.Env = make([]string, len(container.Config.Env))
+		copy(c.Config.Env, container.Config.Env)
```
Comment (dnephin) [inline daemon/commit.go]: I'm not sure why `c.Config` even exists. It seems like it should be using `container.Config` as the base, but it's been this way for a while. 

This fix looks right when used with the CLI, because the CLI never sends a `c.Config` in the request body, but there could be API consumers sending a request body. This is a great example of why testing using the CLI is a bad idea.

If someone is sending a Config in the request body I guess it's on them to use the correct Config.

**Comment by dnephin** [comment]
I can help you with the tests. The test would go into `integration/image/commit_test.go`. I would expect it to do something like this:

```go
package image

import (
	"context"
	"testing"

	"github.com/docker/docker/api/types"
	"github.com/docker/docker/api/types/container"
	"github.com/docker/docker/integration/util/request"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestCommit(t *testing.T) {
	defer setupTest(t)()
	client := request.NewAPIClient(t)
	ctx := context.Background()

	createResp, err := client.ContainerCreate(ctx, &container.Config{Image: "busybox"}, nil, nil, "")
	require.NoError(t, err)

	commitResp, err := client.ContainerCommit(ctx, createResp.ID, types.ContainerCommitOptions{
		Changes:   []string{"ENV PATH=/new/path:$PATH"},
		Reference: "test-commit-image",
	})
	require.NoError(t, err)

	image, _, err := client.ImageInspectWithRaw(ctx, commitResp.ID)
	require.NoError(t, err)
	expected := types.ImageInspect{
		Config: &container.Config{
			Env: []string{"PATH=..."},
			// ...
		},
		// ...
	}
	assert.Equal(t, expected, image)
}

```

**Comment by dnephin** [comment]
Re: "why are there so many config objects in Commit?" it looks like a refactor in #17762 made some changes that haven't aged well. I think the API `postCommit()` should only accept either a container name or a `request.Body`, and error if both are set. Then `Commit()` shouldn't need to merge anything.

`c.ContainerConfig` is required by the builder, it's a separate field in the Image.

Commit could definitely use some cleanup.

File: daemon/commit.go (hunk 3 above)
Comment (asottile) [reply daemon/commit.go]: I think the _actual_ semantics I want is to replace this if statement [here](https://github.com/moby/moby/blob/c307e0ce49d63d1b1f479560955dca3956f005ec/api/server/router/image/image_routes.go#L49-L51) to something like:

```
if c == nil {
    c = copyRunConfig(GetContainer(cname))
}
```
- `copyRunConfig` being [from here](https://github.com/moby/moby/blob/c307e0ce49d63d1b1f479560955dca3956f005ec/builder/dockerfile/internals.go#L434)
- `GetContainer` being [from here](https://github.com/moby/moby/blob/c307e0ce49d63d1b1f479560955dca3956f005ec/daemon/container.go#L34)

but the current encapsulation doesn't allow me to do this (perhaps intentionally?)

Comment (dnephin) [reply daemon/commit.go]: You shouldn't need copy because `GetContainer()` should hopefully give you a copy already.

`GetContainer()` could be exposed in the `Backend` interface. That should probably work

Comment (asottile) [reply daemon/commit.go]: from what I can tell, it gives me the live `Container` and not a copy :(

Where would I look to extend the `Backend` interface?

Comment (dnephin) [reply daemon/commit.go]: https://github.com/moby/moby/blob/c307e0ce49d63d1b1f479560955dca3956f005ec/api/server/router/image/backend.go

The methods exposed by backend all return `api/types` not internal types, so I guess you'll need to use `Daemon.ContainerInspectCurrent()` instead of `GetContainer()`, but that should still give you the `container.Config`, and that one would be a copy.

**Comment by asottile** [comment]
@dnephin I've updated my patch

I still needed the `copyRunConfig` in `builder/dockerfile/builder.go` otherwise this test fails.  This to me means two things:
- we're not getting a copy
- `BuildFromConfig` both mutates the first parameter and returns it.

```
----------------------------------------------------------------------
FAIL: docker_cli_commit_test.go:146: DockerSuite.TestCommitChangeLabels

docker_cli_commit_test.go:156:
    // check that container labels didn't change
    c.Assert(inspectField(c, "test", "Config.Labels"), checker.Equals, "map[some:label]")
... obtained string = "map[some:label2]"
... expected string = "map[some:label]"


----------------------------------------------------------------------
```

**Comment by dnephin** [comment]
There's a `golint` error, but otherwise I think this looks good.

With this change I think `MergeConfigs` can be removed. Mind trying to remove that and see if the tests are happy?

**Comment by asottile** [comment]
cool, fixed the lint error, I've pushed these in separate commits and if the tests are happy I can squash.

**Comment by asottile** [comment]
yeah removing `MergeConfigs` fails some tests:

```
----------------------------------------------------------------------
FAIL: docker_api_containers_test.go:509: DockerSuite.TestContainerAPICommitWithLabelInConfig

docker_api_containers_test.go:535:
    c.Assert(cmd, checker.Equals, "[/bin/sh -c touch /test]", check.Commentf("got wrong Cmd from commit: %q", cmd))
... obtained string = "[]"
... expected string = "[/bin/sh -c touch /test]"
... got wrong Cmd from commit: "[]"

```

going to leave that bit out for now

**Comment by dnephin** [comment]
Thanks for trying.

WindowsRS1 failures looks related

**Comment by asottile** [comment]
Indeed, the windows failures would imply that `busybox` on windows doesn't have `PATH` set by default... strange.  Any ideas how to debug this and/or fix the test?  My gut is to `if windows: ... else: ...` but I'd like to verify my assumption before doing so.

**Comment by dnephin** [comment]
Sounds right, if/else is what we do everywhere else, so should be fine here too

**Comment by asottile** [comment]
Added a branch, windows is passing now!

**Comment by asottile** [comment]
@dnephin seems like powerpc flaked, is there a way to restart that build?

**Comment by thaJeztah** [comment]
I restarted PowerPC 👍

**Review by dnephin — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM :frog:

**Comment by vdemeester** [comment]
cc @tonistiigi

File: api/server/router/image/image_routes.go [hunk 4]
```diff
@@ -47,7 +46,11 @@ func (s *imageRouter) postCommit(ctx context.Context, w http.ResponseWriter, r *
 		return err
 	}
 	if c == nil {
-		c = &container.Config{}
+		containerJSON, err := s.backend.ContainerInspectCurrent(cname, false)
```
Comment (tonistiigi) [inline api/server/router/image/image_routes.go]: Why is this in builder pkg and not in daemon.commit ?

Comment (dnephin) [reply api/server/router/image/image_routes.go]: Do you mean the api package? 

`daemon.Commit()` is overloaded right now, it's trying to share too much when the two consumers are not that similar. The parts that are not similar need to be pulled out

Comment (tonistiigi) [reply api/server/router/image/image_routes.go]: Sorry, yes, api. Shouldn't `MergeConfigs` mean the same what these lines are doing(when empty config is passed)?

Comment (dnephin) [reply api/server/router/image/image_routes.go]: My question is why would `MergeConfigs` even need to exist? It seems like a hack to support a weird code structure (it was added in a refactor, not as a feature).

Comment (tonistiigi) [reply api/server/router/image/image_routes.go]: My understanding is that commits from builder do not merge while commits from `commit` do.  If you would want to refactor it so that they don't call the same function with different parameters(you comment about it being overloaded) that may be ok, but makes it even weirder to have parts of the same functionality split in different packages.

Comment (dnephin) [reply api/server/router/image/image_routes.go]: What functionality is split?

Here is my understanding, there are 3 possible operations:
* the builder calls `Commit()` with a new config to save as a child of an image
* the commit endpoint calls `Commit()` with a config that should be applied (merged) over an image config, then saved as a child of the image
* the commit endpoint calls `Commit()` with a list of `changes` that should be translated into a config by the builder, then saved as a child of the image

`Commit()` should only include the parts that are used in these 3 cases (save a config as a child of an image), but right now it does a lot more.

I guess `MergeConfigs` is needed for the second case, but not 1 and 3. 

Does that sound right to you?

> Shouldn't MergeConfigs mean the same what these lines are doing(when empty config is passed)?

It doesn't, because it happens after `BuildFromConfig()`, which is the problem this is trying to fix.

Comment (tonistiigi) [reply api/server/router/image/image_routes.go]: > What functionality is split?

Implementation of `MergeConfigs`. It only merges if you specify the override config, not when config is created by changes. To do it properly one has to request the current config before using `daemon.Commit`.

> It doesn't, because it happens after BuildFromConfig()

Exactly, it seemed tp me that `MergeConfigs` is not implemented properly and causes this problem. Suggestion is to fix the problem, not change the caller so that it wouldn't hit this case anymore.

Comment (dnephin) [reply api/server/router/image/image_routes.go]: Isn't `MergeConfigs` only necessary for case 2 (commit with with config from request body)?

The bug this PR is fixing is in case 3 (commit with `changes` applied by builder). In this case `merge()` is a no-op, because the changes were already applied ("merged") by the builder.

After this change `MergeConfigs` can be removed from `Commit()` and moved out to the caller for the one case that needs it (when `changes` is empty, and request body has a config).

Comment (asottile) [reply api/server/router/image/image_routes.go]: This seems to have stalled, is there anything I can do to help this along?

Comment (tonistiigi) [reply api/server/router/image/image_routes.go]: @dnephin Unless you change the API to call `dockerfile.BuildFromConfig` I don't see how you could cover all the cases that the API supports.

@asottile Yes, sorry. You can either make the change I asked for or @dnephin can merge because this already has 2 LGTMs.

Comment (dnephin) [reply api/server/router/image/image_routes.go]: Yes, I think it should call the equivalent of `dockerfile.BuildFromConfig()`. We could add a separate method on `Daemon` if we think we need the abstraction. That is effectively what it does now, except it's mixed up with `Commit()`.

Do you agree with my assessment of the 3 cases?

Comment (tonistiigi) [reply api/server/router/image/image_routes.go]: > Do you agree with my assessment of the 3 cases?

2 and 3 could happen together. But that isn't really related to this PR as this is fixing an issue in existing code, not refactoring the internal go api.

Comment (tonistiigi) [reply api/server/router/image/image_routes.go]: To be clear, my proposed fixed is 
```
if c.MergeConfigs && c.Config== nil {
  c.Config = container.Config
}
```

before `BuildConfig` in the daemon, that avoids adding the extra method.

Comment (dnephin) [reply api/server/router/image/image_routes.go]: Thanks. While I still think this makes `Commit()` worse, I agree it does keep the exported interface cleaner. Since it may be a while before we can properly cleanup the commit api backend, I guess this is a better option for now.

@asottile do you mind making that change? It should remove the need to change the Backend interface.

Sorry for all the changes on this.

Comment (asottile) [reply api/server/router/image/image_routes.go]: That was actually my initial patch but I believe it broke tests.  I can try it again.

Comment (asottile) [reply api/server/router/image/image_routes.go]: seems to work now, probably because of the code I added to avoid the mutation inside `BuildFromConfig`

**Review by dnephin — APPROVED** [review]
LGTM

**Review by tonistiigi — APPROVED** [review]
@asottile Thanks!

LGTM (if green)

**Comment by tonistiigi** [comment]
z failure unrelated (other PRs hanging same way).

**Comment by thaJeztah** [comment]
Thank you @asottile !
