### PR TITLE
#46621 ensure that errors reading the response body are returned to the caller

### LINKED ISSUE #46621: Golang client library - client.ContainerWait returns wrong error when context is canceled
### Description

Given the following function and assuming `cli` is a `*client.Client` we call `WaitForContainer` with a `context.WithCancel(ctx)`.

```go
func WaitForContainer(ctx context.Context, containerID string, timeout time.Duration) (int64, error) {
        waitCtx, cancelWait := context.WithTimeout(ctx, timeout)
	defer cancelWait()

	statusCh, errCh := cli.ContainerWait(waitCtx, containerID, container.WaitConditionNotRunning)
	select {
	case err := <-errCh:
		if err != nil {
			return -1, fmt.Errorf("container exited with an error: %w", err)
		}
	case status := <-statusCh:
		return status.StatusCode, nil
	}
        return -1, nil
}
```

If the context `ctx` is then canceled from the outside, the `errCh` is populated with an empty ( `""`) error and therefor the information that the context has been canceled is lost. 
I added the following to circumvent the problem, but that does not look nice or even reliable IMO.

```go
[...]
                if err != nil {
			if err.Error() == "" {
				// this happens when ContainerWait has been cancelled by the context
				return -1, context.Canceled
			}
			return -1, fmt.Errorf("container exited with an error: %w", err)
		}
[...]
```

The reason for this is that there's no check for context cancelation (or timeout) in `"github.com/docker/docker/client" ContainerWait()` (see [`client/container_wait.go:66`](https://github.com/moby/moby/blob/d7caea206ee1cce1e87aa81c47553bf21cef75ac/client/container_wait.go#L66)). 

### Reproduce

See above.

### Expected behavior

The error returned from the `errCh` should be a `context.Canceled` error.

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:28:49 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.24.0 (122432)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:36 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.6
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.5
    Path:     /Users/s/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.22.0-desktop.2
    Path:     /Users/s/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/s/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /Users/s/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.8
    Path:     /Users/s/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/s/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/s/.docker/cli-plugins/docker-scan
  scout: Docker Scout (Docker Inc.)
    Version:  v1.0.7
    Path:     /Users/s/.docker/cli-plugins/docker-scout

Server:
 Containers: 81
  Running: 12
  Paused: 0
  Stopped: 69
 Images: 74
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.4.16-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 11
 Total Memory: 11.68GiB
 Name: docker-desktop
 ID: 2e53878e-fa7e-4736-b79e-3b1207b4543f
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by sgehrig**
Fixes #46621 by returning a `context.Canceled` error to the caller.

**- What I did**

I added a check id `err` is a `context.Canceled` error. If so, we return the `err` directly to the caller through `errC`. In all other cases the error is generated from the API response just as before the change.

**- How I did it**

It's as easy as checking the type of `err`. If it's a `context.Canceled` we skip creating an error from the (then empty) API response.

**- How to verify it**

Call `client.ContainerWait()` with a cancelable context and while waiting for the method to end, cancel the given context. before the change an error with an empty (`""`) error message has been returned on `errC`. After the change a `context.Canceled` error will be returned on the `errC`.

**- Description for the changelog**

`client.ContainerWait()` now returns a `context.Canceled` error on the error channel when the operation is canceled via its context.

### CODE REVIEW

**Comment by sgehrig** [comment]
@cpuguy83 I'd love to add a test, but I'm unsure how to do it. The `context.Canceled` error appears in 

```go
if err := json.NewDecoder(stream).Decode(&res); err != nil {
```

so I have to somehow mock the response body to return a `context.Canceled` error when the JSON decoder tries to read from it.

File: client/container_wait_test.go [hunk 1]
```diff
@@ -127,3 +128,36 @@ func ExampleClient_ContainerWait_withTimeout() {
...
+	case err := <-errC:
+		if !errors.Is(err, context.Canceled) {
+			t.Fatalf("Unexpected error: %v", err)
+		}
+		return
+	case result := <-resultC:
+		t.Fatalf("Unexpected result: %v", result)
+		return
+	}
+	t.Fatal("Unexpected - we should not reach this line")
```
Comment (thaJeztah) [inline client/container_wait_test.go:162]: My IDE flags this as unreachable code, which is of course expected here; wondering if any linter will complain (otherwise we could consider changing this to just a comment)

File: client/container_wait_test.go [hunk 2]
```diff
@@ -127,3 +128,36 @@ func ExampleClient_ContainerWait_withTimeout() {
...
 	}
 }
+
+type TestClient_ContainerWait_cancelReader struct{}
+
+func (TestClient_ContainerWait_cancelReader) Read(p []byte) (n int, err error) {
+	return 0, context.Canceled
+}
+
+func TestClient_ContainerWait_canceled(t *testing.T) {
```
Comment (thaJeztah) [inline client/container_wait_test.go:138]: Perhaps

- rename this test to be similar to the existing tests higher up (e.g. `TestContainerWaitContextCancelled`), so that we can filter tests by common prefixes.
- while doing so, perhaps move this test (and the type) above the `ExampleClient_..` code (which probably should've been in a separate file, but that's for a separate PR)

File: client/container_wait_test.go [hunk 3]
```diff
@@ -127,3 +128,36 @@ func ExampleClient_ContainerWait_withTimeout() {
 		log.Fatal(err)
 	}
 }
+
+type TestClient_ContainerWait_cancelReader struct{}
+
+func (TestClient_ContainerWait_cancelReader) Read(p []byte) (n int, err error) {
```
Comment (thaJeztah) [inline client/container_wait_test.go:134]: Minor nit; perhaps a shorter name would work for this, which can be unexpected. e.g. `cancelReader`

**Review by thaJeztah — COMMENTED** [review]
just some quick comments; I think it's also fine to squash the two commits, so that the test and code-changes are part of the same commit

File: client/container_wait_test.go (hunk 1 above)
Comment (sgehrig) [reply client/container_wait_test.go:162]: No problem.

File: client/container_wait_test.go (hunk 2 above)
Comment (sgehrig) [reply client/container_wait_test.go:138]: Done.

**Comment by sgehrig** [comment]
> just some quick comments; I think it's also fine to squash the two commits, so that the test and code-changes are part of the same commit

Sure. I wanted to squash everything as soon as the PR is approved. Wasn't sure how this is handled in this repository, but that's how I'm used to do PRs.

File: client/container_wait_test.go [hunk 4]
```diff
@@ -117,6 +118,39 @@ func TestContainerWaitProxyInterruptLong(t *testing.T) {
...
+func TestContainerWaitContextCancelled(t *testing.T) {
+	ctx, cancel := context.WithCancel(context.Background())
+	defer cancel()
+
+	client := &Client{
+		version: "1.30",
+		client: newMockClient(func(req *http.Request) (*http.Response, error) {
+			return &http.Response{
+				StatusCode: http.StatusOK,
+				Body:       io.NopCloser(TestClient_ContainerWait_cancelReader{}),
```
Comment (thaJeztah) [inline client/container_wait_test.go:136]: Looks like you missed this one when renaming;

```
client/container_wait_test.go:136:30: undefined: TestClient_ContainerWait_cancelReader
```

Comment (sgehrig) [reply client/container_wait_test.go]: 🤦‍♂️ Sorry... Fixed. Happens when you think "oh let's do that quickly and forget about that IDE"

**Comment by thaJeztah** [comment]
> Sure. I wanted to squash everything as soon as the PR is approved. Wasn't sure how this is handled in this repository, but that's how I'm used to do PRs.

No worries! Mostly commented so that we don't forget 😅

For smaller PRs, we usually squash /rebase immediately; for some larger PRs we may have temporary ("to be squashed") commits, but if a PR is that large, we also try to have commits grouped in logical chunks of work where possible.

File: client/container_wait_test.go (hunk 4 above)
Comment (thaJeztah) [reply client/container_wait_test.go]: Happens to me all the time! 😂 no harm done, that's where review and CI is for!

**Review by corhere — CHANGES_REQUESTED** [review]
`(json.Decoder).Decode()` passes through whatever error is returned from `(io.Reader).Read()` (except for `io.EOF`) and so could be practically any error value, not just `context.Canceled`. Instead of enumerating the set of errors which should be passed through, which is unbounded, how about inverting the logic and enumerating the set of errors that should be handled by returning the response body as an error? That's what the code is intended to do, after all.
https://github.com/moby/moby/blob/c2aa895908231e170f0686d4ca03cf286ae6f9eb/client/container_wait.go#L73-L74

The JSON decoder returns a json.SyntaxError when it encounters a parsing error. [Special-case that type of error and pass through all others.](https://go.dev/play/p/Sh_AZRfbqjZ)

File: client/container_wait_test.go [hunk 5]
```diff
@@ -117,6 +118,39 @@ func TestContainerWaitProxyInterruptLong(t *testing.T) {
...
+func TestContainerWaitContextCancelled(t *testing.T) {
+	ctx, cancel := context.WithCancel(context.Background())
+	defer cancel()
+
+	client := &Client{
+		version: "1.30",
+		client: newMockClient(func(req *http.Request) (*http.Response, error) {
+			return &http.Response{
+				StatusCode: http.StatusOK,
+				Body:       io.NopCloser(cancelReader{}),
```
[the remark this answers is not in the document]
Comment (thaJeztah) [reply client/container_wait_test.go:136]: oh! I went looking for that one, as I recalled there was something, but thought it was in `io.`

[the remark this answers is not in the document]
Comment (sgehrig) [reply client/container_wait_test.go:136]: Great point. Didn't even know something like this existed. I'll update the PR accordingly.

[the remark this answers is not in the document]
Comment (sgehrig) [reply client/container_wait_test.go:136]: I'll also change the logic to handle other errors as well as it was described by @corhere. Thanks a lot!
And sorry for all the additional work. First PR in this repository 😳

**Comment by sgehrig** [comment]
I updated the logic to determine the cause of the error. Now it just checks whether it's a `json.SyntaxError` and returns the raw response in an error in these cases. Otherwise it returns the original error.

**Review by corhere — APPROVED** [review]
LGTM, thanks! I have one minor nitpick with the test, though.

**Comment by sgehrig** [comment]
> LGTM, thanks! I have one minor nitpick with the test, though.

Done. 👍

**Comment by thaJeztah** [comment]
Minor nit; could you update the commit message to remove the related ticket-number from the title (`#46621`)? It's mostly to reduce noise on GitHub, as GitHub tends to be rather fanatical trying to surface linked PRs and commits (which can result in a lot of noise if such commits are cherry-picked or merged in this repository or other forks)

**Comment by sgehrig** [comment]
> Minor nit; could you update the commit message to remove the related ticket-number from the title (`#46621`)? It's mostly to reduce noise on GitHub, as GitHub tends to be rather fanatical trying to surface linked PRs and commits (which can result in a lot of noise if such commits are cherry-picked or merged in this repository or other forks)

No problem. Done.

**Review by thaJeztah — APPROVED** [review]
oops, looks like this one dropped of my radar (sorry for the wait!)

LGTM
