### PR TITLE
Fix wrong kill signal parsing

### LINKED ISSUE #13665: docker kill sends SIGKILL regardless of -s flag
As of Docker 1.7 RC1, it seems that `POST /containers/:name/kill` ignores the `signal` parameter, always sending SIGKILL.

Here's a quick test run on a 1.7.1 RC machine, sending SIGWINCH to `top` running in `busybox`:

```
docker@dev:~$ docker version
Client version: 1.7.0-rc1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 395cced
OS/Arch (client): linux/amd64
Server version: 1.7.0-rc1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 395cced
OS/Arch (server): linux/amd64

docker@dev:~$ ID=$(docker run -d busybox top); docker kill -s SIGWINCH $ID; docker inspect -f 'Image: {{.Image}}, Cmd: {{.Config.Cmd}}, Running: {{.State.Running}}' $ID
d4667497a4504b5bc43f8ae017794bab1c07e1421d5827f935c1c3c3e2f07609
Image: 8c2e06607696bd4afb3d03b687e361cc43cf8ec1a4a725bc96e39f05ba97dd55, Cmd: {[top]}, Running: false
```

Here's the relevant log output:

```
time="2015-06-02T14:13:16.420427938Z" level=debug msg="Calling POST /containers/{name:.*}/kill"
time="2015-06-02T14:13:16.420462290Z" level=info msg="POST /v1.19/containers/d4667497a4504b5bc43f8ae017794bab1c07e1421d5827f935c1c3c3e2f07609/kill?signal=SIGWINCH"
time="2015-06-02T14:13:16.420486513Z" level=debug msg="Sending 9 to d4667497a4504b5bc43f8ae017794bab1c07e1421d5827f935c1c3c3e2f07609"
```

And the same on a 1.6.2 machine:

```
docker@dev-1:~$ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

docker@dev-1:~$ ID=$(docker run -d busybox top); docker kill -s SIGWINCH $ID; docker inspect -f 'Image: {{.Image}}, Cmd: {{.Config.Cmd}}, Running: {{.State.
Running}}' $ID
645070a0919d382d0ab5cb443fbae183fb944569051d33f940edf7af2249b568
Image: 8c2e06607696bd4afb3d03b687e361cc43cf8ec1a4a725bc96e39f05ba97dd55, Cmd: [top], Running: true
```

```
time="2015-06-02T14:18:05Z" level=debug msg="Calling POST /containers/{name:.*}/kill"
time="2015-06-02T14:18:05Z" level=info msg="POST /v1.18/containers/15150f649f3a9e228df542e60519bfe7a9839b3a9e51ace77589a602baf3b50a/kill?signal=SIGWINCH"
time="2015-06-02T14:18:05Z" level=info msg="+job kill(15150f649f3a9e228df542e60519bfe7a9839b3a9e51ace77589a602baf3b50a, SIGWINCH)"
time="2015-06-02T14:18:05Z" level=debug msg="Sending 28 to 15150f649f3a9e228df542e60519bfe7a9839b3a9e51ace77589a602baf3b50a"
time="2015-06-02T14:18:05Z" level=info msg="-job kill(15150f649f3a9e228df542e60519bfe7a9839b3a9e51ace77589a602baf3b50a, SIGWINCH) = OK (0)"```

### PR DESCRIPTION
**Pull request by runcom**
fixes #13665 

https://github.com/docker/docker/blob/v1.7.0-rc1/api/server/server.go#L274 `signal` isn't in `vars`
old code https://github.com/docker/docker/blob/v1.6.2/api/server/server.go#L215

this resulted in alwasy passing `0` as signal and being interpreted by the daemon as `SIGKILL`

/cc @aanand

```
DEBU[0016] Calling POST /containers/create              
INFO[0016] POST /v1.20/containers/create                
DEBU[0016] Calling POST /containers/{name:.*}/start     
INFO[0016] POST /v1.20/containers/9ace169f8625121a9d662b865f00d27a1b4f658d403d8a7ba74b425282f65506/start 
DEBU[0016] Calling POST /containers/{name:.*}/kill      
INFO[0016] POST /v1.20/containers/9ace169f8625121a9d662b865f00d27a1b4f658d403d8a7ba74b425282f65506/kill?signal=SIGWINCH 
DEBU[0016] Sending 28 to 9ace169f8625121a9d662b865f00d27a1b4f658d403d8a7ba74b425282f65506 
DEBU[0016] Calling GET /containers/{name:.*}/json       
INFO[0016] GET /v1.20/containers/9ace169f8625121a9d662b865f00d27a1b4f658d403d8a7ba74b425282f65506/json
```

Signed-off-by: Antonio Murdaca antonio.murdaca@gmail.com

### CODE REVIEW

**Comment by duglin** [comment]
the fact that all of our tests pass w/o this fix means we need at least one new test  :-)

**Comment by runcom** [comment]
@duglin sure :P

**Comment by estesp** [comment]
nice catch..should this make 1.7? ping @jfrazelle 

agree with @duglin on a test :)

**Comment by runcom** [comment]
@estesp pretty sure this will go in 1.7, I added the milestone but remove it if I'm wrong

**Comment by thaJeztah** [comment]
Assigned Jess for cherry-pick once it's ready

**Comment by runcom** [comment]
@duglin @estesp PTAL

File: integration-cli/docker_cli_kill_test.go [hunk 1]
```diff
@@ -58,3 +58,62 @@ func (s *DockerSuite) TestKillDifferentUserContainer(c *check.C) {
...
+	c.Assert(waitRun(cid), check.IsNil)
+
+	killCmd := exec.Command(dockerBinary, "kill", "-s", "SIGWINCH", cid)
+	_, err = runCommand(killCmd)
+	c.Assert(err, check.IsNil)
+
+	running, err := inspectField(cid, "State.Running")
+	if running != "true" {
+		c.Fatal("Container should be in running state after SIGWINCH")
+	}
```
Comment (duglin) [inline integration-cli/docker_cli_kill_test.go]: its too bad we can't check the actually signal that was sent to the container via the event log.

**Comment by duglin** [comment]
LGTM

File: integration-cli/docker_cli_kill_test.go (hunk 1 above)
Comment (runcom) [inline integration-cli/docker_cli_kill_test.go]: yup, but I recall we have some proposal about including how the container died in Config/HostConfig so maybe we should takle that proposal too

Comment (duglin) [inline integration-cli/docker_cli_kill_test.go]: even if we don't include it in the config/state info, the code that calls LogEvent (I think) has the info so it could add it to the event.  Should be an easy one - as long as we're allowed to modify the event string in that way.

**Comment by icecrime** [comment]
LGTM

**Comment by estesp** [comment]
LGTM

**Comment by jfrazelle** [comment]
cherry-picked!

**Comment by aanand** [comment]
:heart:
