### PR TITLE
Fix build with `ADD` urls without any sub path

### LINKED ISSUE #34208: ADD step fails with urls without any sub path
**Description**

**Steps to reproduce the issue:**
1. Create Dockerfile with step of `ADD https://install.meteor.com/ install-meteor.sh` or  `ADD https://install.meteor.com install-meteor.sh`
2. Build Dockerfile

**Describe the results you received:**
```
ADD failed: open /var/lib/docker/tmp/docker-remote644588657: file exists
```
**Describe the results you expected:**
URL downloaded and build proceeds

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 17.06.0-ce, build 02c1d87
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 41
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.11.10-300.fc26.x86_64
Operating System: Fedora 26 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.55GiB
Name: localhost.localdomain
ID: QTSB:SFY3:32EM:UYCD:FZYP:Y5WR:AIC6:QYQD:CPZE:SF6F:LY7B:M3PN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by yongtang**
**- What I did**
This fix tries to address the issue raised in #34208 where in Dockerfile an `ADD` followed by an url without any sub path will cause an error.

The issue is because the temporary filename relies on the sub path.

**- How I did it**
This fix fixes this issue by having `index.html` as the filename if no sub path exists.

**- How to verify it**
An integration test has been added.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**
5vznpa4dkmk

This fix fixes #34208.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

File: builder/dockerfile/copy.go [hunk 1]
```diff
@@ -305,10 +305,14 @@ func downloadSource(output io.Writer, stdout io.Writer, srcURL string) (remote b
 	if err != nil {
 		return
 	}
-	filename := filepath.Base(filepath.FromSlash(u.Path)) // Ensure in platform semantics
-	if filename == "" {
-		err = errors.Errorf("cannot determine filename from url: %s", u)
-		return
+	// Use index.html if path is "" or "/" (e.g., http://example.com or http://example.com/)
+	filename := "index.html"
```
Comment (thaJeztah) [inline builder/dockerfile/copy.go]: Thinking;

- first of all, we can't assume `.html` here (could be any kind of file)
- server can send a [`Content-Disposition: attachment; filename="<something>"`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition) - do we handle those currently?

If no filename can be determined - perhaps we _can_ generate a filename (could be just `unnamed-file` - shouldn't matter, because it's only the temp-file), however _only_ support this if there's a target filename set as well, i.e.;

```
ADD https://example.com/ filename.foo
```

And fail if;

```
ADD https://example.com/ /some/path/
```

Challenge here may be to determine if the target is a _filename_ or a _path_ (which cannot be determined if the target doesn't exist), i.e.

```
ADD https://example.com/ filename.foo
```

Here, `filename.foo` could mean;

- create a _directory_ named `filename.foo`, and copy the downloaded file into it
- save the downloaded file as `filename.foo`

(haven't checked the current semantics on this)

File: builder/dockerfile/copy.go [hunk 2]
```diff
@@ -305,10 +305,14 @@ func downloadSource(output io.Writer, stdout io.Writer, srcURL string) (remote b
...
+	if u.Path != "" && u.Path != "/" {
```
Comment (thaJeztah) [inline builder/dockerfile/copy.go]: We'd probably run into the same issue if a subdirectory is used as source;

```
ADD http://example.com/foo/bar/ /filename.foo
```

**Review by thaJeztah — CHANGES_REQUESTED** [review]
Thanks for looking into this; I suspected this was the cause of the issue being reported, but think this may be difficult to fix (without introducing unwanted side-effects)

perhaps @tonistiigi has some ideas as well

**Comment by yongtang** [comment]
Thanks @thaJeztah for the review. I changed the default filename to `unnamed-file`. 

For URL resources, the build process is actually different from a local file system. A URL always points to one file. For example,
```
# Add the default web page of https://example.com/
ADD https://example.com/ filename.foo

#Add the web page of "Get Started, Part 2: Containers"
ADD https://docs.docker.com/get-started/part2/ filename.foo 
```


Also, see the line:
https://github.com/moby/moby/blob/2981667e11e24e9e1e61252a40ceb11fd7cb9811/builder/dockerfile/copy.go#L308
```
filename := filepath.Base(filepath.FromSlash(u.Path))
```

In case of the target directory like:
```
ADD https://example.com/ /some/path/
```

The `filename` is actually `path` (after stripping `/some/.../`). 

The only issue with ` filepath.Base(filepath.FromSlash(u.Path))` is that, it does not handle empty filenames. If `u.Path == ""` or `u.Path == "/"`, then "." is returned.
```
filename := filepath.Base(filepath.FromSlash(u.Path)) // returned value is actually "."
```

For that I tend to think having a default filename of `unnamed-file` for `u.Path == ""` or `u.Path == "/"` would be suffice to address the issue.

**Comment by ijc** [comment]
Is it necessary for the download target's filename to have anything to do with the URL path at all? IOW why not just use `ioutil.TempFile()` (either passing it the existing `tmpdir` or arranging to clean it up separately) to get a unique local name?

**Comment by ijc** [comment]
Or since you already have a dedicated/local/unique tmpdir, why not just call it `bob`?

**Comment by yongtang** [comment]
@ijc The name is not an issue as long as the target is also a file:
```
ADD http://example.com /filename.foo
```

However, I realized it will be an issue in case the target is a directory (was pointed out by @thaJeztah):
```
ADD http://example.com /
```

In that case, the container will have a file of `/blob` in its file system. That is something that should be addressed.

I think in case
```
ADD http://example.com /
```
is specified, an error should be returned.

In case 
```
ADD https://docs.docker.com/get-started/part2/ /
```
is specified, a filename named `/part2` should be created in container's file system. (The `part2` actually carries a meaning in HTTP 's URL and it is very common in some web pages.) 

I will update the PR.

**Comment by thaJeztah** [comment]
I don't think we should take `part2` as name here; it has a trailing slash, so it's a directory, not a file (and the webserver happens to be configured to treat index.html as a default.

In such a case;

- if webserver has a header specifying the filename, use it
- if not, and no target filename was specified, we should probably error, as there's no "good" choice

**Comment by ijc** [comment]
I had missed that `filename` was used in the return as well, so I thought it was just a local tempfile, sorry.

I agree with https://github.com/moby/moby/pull/34217#issuecomment-317541247 and erroring rather than fabricating names. `Content-Disposition` is the header to look for I think.

**Comment by thaJeztah** [comment]
Yes, I think that's the right header (see my first comment https://github.com/moby/moby/pull/34217#discussion_r128884629)

File: builder/dockerfile/copy.go [hunk 3]
```diff
@@ -305,10 +305,15 @@ func downloadSource(output io.Writer, stdout io.Writer, srcURL string) (remote b
 	if err != nil {
 		return
 	}
-	filename := filepath.Base(filepath.FromSlash(u.Path)) // Ensure in platform semantics
-	if filename == "" {
-		err = errors.Errorf("cannot determine filename from url: %s", u)
-		return
+	// Use "unnamed-file" if path is "" or "/" (e.g., http://example.com or http://example.com/)
+	// In case the path "" or "/", filepath.Base(filepath.FromSlash(u.Path)) will be "."
+	filename := "unamed-file"
```
Comment (dsheets) [inline builder/dockerfile/copy.go]: should this be `filename := "unnamed-file"` (with 2 'n's in 'unnamed')?

**Comment by yongtang** [comment]
Thanks all for the review. The PR has been updated so that `srcURL`, `dest`, and `Content-Disposition` would be taken into consideration to find the file name. Please take a look and let me know if there are any issues.

File: builder/dockerfile/copy.go [hunk 4]
```diff
@@ -288,33 +289,56 @@ func walkSource(source builder.Source, origPath string) ([]string, error) {
...
+		if filename == "" {
+			err = errors.Errorf("cannot determine filename from url: %s", u)
+			return
+		}
+	} else if dest != "" && !strings.HasSuffix(dest, "/") {
+		filename = filepath.Base(filepath.FromSlash(dest))
+		if filename == "" {
+			err = errors.Errorf("cannot determine filename from dest: %s", dest)
+			return
+		}
```
Comment (dnephin) [inline builder/dockerfile/copy.go]: Please split this into a new function:

```go
func getTargetFilename(url *url.Url) string {

}
```

I don't think we need to pass `dest` all the way from through function call chain. The filename doesn't seem terribly relevant. Can't we just use a random name, or even a hardcoded name since we're creating a new temporary directory anyway?

I think `getTargetFilename` should make a "best guess" at a filename (using `filepath.Base()` like it did before), and if it fails just returns the string `"download"` instead of erroring or using dest or content-dispoition.

File: integration-cli/docker_cli_build_test.go [hunk 5]
```diff
@@ -6488,3 +6488,19 @@ RUN touch /foop
...
 }
+
+// Test case for #34208
+func (s *DockerSuite) TestBuildAddHTTPRoot(c *check.C) {
+	testRequires(c, Network, DaemonIsLinux)
+	buildImageSuccessfully(c, "buildaddhttproot", build.WithDockerfile(`
+                FROM scratch
+                ADD http://example.com/index.html /example1
+                ADD http://example.com /example2
+                ADD http://example.com /example3`))
```
Comment (dnephin) [inline integration-cli/docker_cli_build_test.go]: This shouldn't be a slow integration test. Any time `example.com` is unavailable the build will fail, which is not good.

This bug was in a single small function. We can test this with a fast unit test. Splitting out `getTargetFilename()` will make it even easier to test because we won't even need to perform an HTTP request to exercise the bug.

**Review by dnephin — CHANGES_REQUESTED** [review]

**Comment by dnephin** [comment]
I see now my suggestion has already been discussed.

> I had missed that filename was used in the return as well, so I thought it was just a local tempfile, sorry.

You were correct. It is used in the return, but only as the **source** for the copy operation.

We should just use any random or hardcoded filename if `filepath.Base()` is not valid. We could even removed `filepath.Base()` entirely.

File: builder/dockerfile/copy.go [hunk 6]
```diff
@@ -288,33 +289,56 @@ func walkSource(source builder.Source, origPath string) ([]string, error) {
...
+	if filename == "" {
+		// Guess filename based on Content-Disposition
+		if contentDisposition := resp.Header.Get("Content-Disposition"); contentDisposition != "" {
+			if _, params, err := mime.ParseMediaType(contentDisposition); err == nil {
+				if params["filename"] != "" && !strings.HasSuffix(params["filename"], "/") {
+					filename = params["filename"]
+				}
+			}
+		}
+		if filename == "" {
```
Comment (thaJeztah) [inline builder/dockerfile/copy.go]: Make sure to sanitise the filename we received from the `"Content-Disposition"` header; we're only interested in a filename, not any (if passed) path information

Comment (yongtang) [inline builder/dockerfile/copy.go]: Thanks @thaJeztah. The PR has been updated.

File: builder/dockerfile/copy.go (hunk 4 above)
Comment (yongtang) [inline builder/dockerfile/copy.go]: @dnephin Thanks. The PR has been updated with functions splitter into getTargetFilename and getTargetFilenameFromResp.

File: integration-cli/docker_cli_build_test.go (hunk 5 above)
Comment (yongtang) [inline integration-cli/docker_cli_build_test.go]: @dnephin The integration test has been covered to unit test.

**Comment by yongtang** [comment]
@dnephin Thanks for the review. The PR has been updated. The `dest` is still carried though as the docker file will need to have some "definitive" name. If both src and dest end with '/' then it it is actually problematic:
```
ADD http://example.org /
```
In the above case, we could not use a random name because we don't want to copy a "__random__name__xxx__" file to `/`:
```
/__random__name__xxx__ 
```

Please take a look.

**Comment by dnephin** [comment]
> In the above case, we could not use a random name because we don't want to copy a "random__name__xxx" file to /

Yes, that's a good point. So the problem case is when source is a directory path, and dest is also a directory path. If `dest` is a file path we don't really need it, because it will be used later on during the copy.  I think this is not really obvious from the code right now.

Instead of passing in `dest string` what do you think about this:
* keep the existing definition for `type sourceDownloader`
* have `downloadSource` attempt to get a filename from either `u.Path` or the response
* if it fails to get a filename from either then return the source and random generated filename, with a custom error `errUndefinedPath` (or something like that).

In the caller `getCopyInfoForSourcePath()` it can check dest if it gets that error:
```go
remote, path, err := o.download(orig)
switch err {
case err == errUndefinedPath && strings.HasSuffix(path, "/"):
     return nil, errors.Errorf("cannot determine filename for source %s...")
case err:
    return nil, err
}
```

In the case where `err == errUndefinedPath` but `dest` is a path to a file then we're ok, because dest will be used later, right?

File: builder/dockerfile/copy.go [hunk 7]
```diff
@@ -288,33 +289,62 @@ func walkSource(source builder.Source, origPath string) ([]string, error) {
...
 	u, err := url.Parse(srcURL)
 	if err != nil {
 		return
 	}
-	filename := filepath.Base(filepath.FromSlash(u.Path)) // Ensure in platform semantics
+	filename := getTargetFilename(u.Path)
 	if filename == "" {
-		err = errors.Errorf("cannot determine filename from url: %s", u)
-		return
+		filename = getTargetFilename(dest)
```
Comment (dnephin) [inline builder/dockerfile/copy.go]: Nit: please move this down next  to the other `filename` setting code, that way it's all together.

I think this (and the lines below that get the filename from response) could also be in a separate function `getFilenameForDownload(url url.Url, resp http.Response) string` which would mean that you could test the full logic together.

**Comment by yongtang** [comment]
@dnephin Thanks for the review. The PR has been updated. Please take a look.

**Review by dnephin — APPROVED** [review]
thanks, LGTM!

**Comment by yongtang** [comment]
Ping @thaJeztah.

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Comment by thaJeztah** [comment]
I triggered CI, because it was quite a while back that it was last run on this PR

**Comment by yongtang** [comment]
All tests passed. Thanks all for the review!
