### PR TITLE
Wait for containerd to die before restarting it

### LINKED ISSUE #23131: [1.11.1] Docker daemon hanging on startup
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 30
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-86-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: ip-172-18-0-56
ID: 53GT:ASJT:ASAC:OYKP:7T7S:RF6Q:H4L2:VZGK:QB2N:W56A:X6WC:3P6I
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 18
 Goroutines: 41
 System Time: 2016-05-31T16:38:06.468909009Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS; docker is hanging on initial launch from AMI. AMI is built from Ubuntu Trusty, with linux-image-extras and docker installed.

**Steps to reproduce the issue:**
1. Launch an AMI with Docker 1.11.1 installed

**Describe the results you received:**

Docker is hanging on startup. Any docker commands that communicate with the daemon (`ps`, `info`, `run`, `pull`, ...) hang indefinitely.

```
time="2016-05-31T16:29:27.742468971Z" level=debug msg="docker group found. gid: 999" 
time="2016-05-31T16:29:27.742553101Z" level=debug msg="Listener created for HTTP on unix (/var/run/docker.sock)
" 
/var/run/docker.sock is up
time="2016-05-31T16:29:28.440531154Z" level=info msg="New containerd process, pid: 1619\n" 
time="2016-05-31T16:29:28.759224749Z" level=debug msg="containerd connection state change: CONNECTING" 
time="2016-05-31T16:29:28.759533205Z" level=debug msg="containerd connection state change: TRANSIENT_FAILURE" 
time="2016-05-31T16:29:31.759889842Z" level=debug msg="containerd connection state change: TRANSIENT_FAILURE" 
DEBU[0000] containerd: read past events                  count=0
DEBU[0000] containerd: supervisor running                cpus=1 memory=2000 runtime=docker-runc runtimeArgs=[] 
stateDir=/run/containerd
DEBU[0000] containerd: grpc api on /var/run/docker/libcontainerd/docker-containerd.sock 
time="2016-05-31T16:29:34.760226204Z" level=debug msg="containerd connection state change: TRANSIENT_FAILURE" 
time="2016-05-31T16:29:34.760298247Z" level=info msg="previous instance of containerd still alive (1619)" 
```

**Describe the results you expected:**

Docker should start normally.

```
/var/run/docker.sock is up
time="2016-05-31T16:36:13.336502737Z" level=debug msg="docker group found. gid: 999" 
time="2016-05-31T16:36:13.336649784Z" level=debug msg="Listener created for HTTP on unix (/var/run/docker.sock)
" 
time="2016-05-31T16:36:13.340959840Z" level=info msg="New containerd process, pid: 2098\n" 
DEBU[0000] containerd: read past events                  count=0
DEBU[0000] containerd: supervisor running                cpus=1 memory=2000 runtime=docker-runc runtimeArgs=[] 
stateDir=/run/containerd
DEBU[0000] containerd: grpc api on /var/run/docker/libcontainerd/docker-containerd.sock 
time="2016-05-31T16:36:13.348085025Z" level=debug msg="containerd connection state change: READY" 
time="2016-05-31T16:36:13.348764443Z" level=debug msg="Using default logging driver json-file" 
time="2016-05-31T16:36:13.348807782Z" level=debug msg="Golang's threads limit set to 28350" 
time="2016-05-31T16:36:13.397853157Z" level=debug msg="received past containerd event: &types.Event{Type:\"live
\", Id:\"\", Status:0x0, Pid:\"\", Timestamp:0x574dbd7d}" 
time="2016-05-31T16:36:14.245629031Z" level=info msg="[graphdriver] using prior storage driver \"aufs\"" 
time="2016-05-31T16:36:14.245735836Z" level=debug msg="Using graph driver aufs" 
time="2016-05-31T16:36:17.775448474Z" level=info msg="Graph migration to content-addressability took 0.00 secon
ds" 
time="2016-05-31T16:36:17.775596758Z" level=debug msg="Option DefaultDriver: bridge" 
time="2016-05-31T16:36:17.775648036Z" level=debug msg="Option DefaultNetwork: bridge" 
time="2016-05-31T16:36:18.177452410Z" level=warning msg="Running modprobe bridge br_netfilter failed with messa
ge: modprobe: WARNING: Module br_netfilter not found.\ninsmod /lib/modules/3.13.0-86-generic/kernel/net/llc/llc.ko \ninsmod /lib/modules/3.13.0-86-generic/kernel/net/802/stp.ko \ninsmod /lib/modules/3.13.0-86-generic/kernel/net/bridge/bridge.ko \n, error: exit status 1" 
time="2016-05-31T16:36:19.002029744Z" level=info msg="Firewalld running: false" 
time="2016-05-31T16:36:19.176005296Z" level=debug msg="/sbin/iptables, [--wait --version]" 
<snip/>
```

**Additional information you deem important (e.g. issue happens only occasionally):**

* The hang happens frequently, but not every time we launch an AMI.
* After the instance is launched, `restart docker` consistently gets the daemon running.
* I tried sending `SIGUSR1` to the daemon to get a stack trace, but nothing showed in the logs. I confirmed that the command I used (`killall -USR1 docker`) did generate a stack dump once Docker was properly running.

### PR DESCRIPTION
**Pull request by mlaventure**
Fixes #23131

### CODE REVIEW

File: libcontainerd/remote_linux.go [hunk 1]
```diff
@@ -388,7 +391,9 @@ func (r *remote) runContainerdDaemon() error {
 		return err
 	}
 
-	go cmd.Wait() // Reap our child when needed
+	go func() {
+		r.daemonWaitCh <- cmd.Wait()
```
Comment (LK4D4) [inline libcontainerd/remote_linux.go]: I think there will be goroutine leak in case of `!utils.IsProcessAlive(r.daemonPid)`. Make channel buffered or if you're not going to use error, better to do it `chan struct{}` and just close after wait.

**Comment by mlaventure** [comment]
@LK4D4 updated.

**Comment by tonistiigi** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM
