### PR TITLE
Default events since to current time

### LINKED ISSUE #13753: docker 1.7 events api reporting last 64 events causes issues
Description of problem:

The new events API seems to return the last 64 events when you query it, rather than simply tailing.  This is causing issues for logspout. You can see the logspout bug here:

https://github.com/gliderlabs/logspout/issues/106

This seems to be the expected behavior, so I'm mostly looking for guidance on how to deal with it.  If there could be a way to  get the old tail behavior, that'd be awesome.

```
$ docker --version
Docker version 1.7.0-dev, build 115b11a
```

```
$ docker info
Containers: 8
Images: 69
Storage Driver: btrfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-53-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 8
Total Memory: 14.69 GiB
Name: ip-10-128-17-16
ID: JCSN:4DZP:HF3H:OFRY:TX4J:IW37:FT5K:5TXS:7NIR:65H5:VDI6:V7CS
```

```
$ uname -a
Linux ip-10-128-17-16 3.13.0-53-generic #89-Ubuntu SMP Wed May 20 10:34:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Environment details: `AWS, c4.2xlarge`

How reproducible:  Easily reproducible, it's a change in the API behavior.

Steps to Reproduce:
1. Hit the events API - it returns the last 64 events (if there are some) then goes into the tail behavior.

### PR DESCRIPTION
**Pull request by cpuguy83**
Closes #13753

### CODE REVIEW

**Comment by LK4D4** [comment]
makes sense

**Comment by cpuguy83** [comment]
Not really sure why this test is failing.
Manual testing has this working.

**Comment by LK4D4** [comment]
@cpuguy83 Maybe races between times? I have alternative solution, but I like this.

**Comment by cpuguy83** [comment]
Yeah, probably with until being set from the CLI and since being set to a time after until since it is set on the daemon.

Could instead do a special case for when since == -1.

**Comment by LK4D4** [comment]
@cpuguy83 Yeah, maybe just
```
if since == -1 {
    current = nil
}
```

**Comment by cpuguy83** [comment]
Updated with special case for `-1`

**Comment by LK4D4** [comment]
LGTM

File: integration-cli/docker_cli_events_test.go [hunk 1]
```diff
@@ -628,7 +628,7 @@ func (s *DockerSuite) TestEventsCopy(c *check.C) {
 		c.Fatalf("Failed getting file:%q\n%q", out, err)
 	}
 
-	cmd = exec.Command(dockerBinary, "events", "-f", "container=cptest", "--until="+strconv.Itoa(int(since)))
+	cmd = exec.Command(dockerBinary, "events", "--since=0", "-f", "container=cptest", "--until="+strconv.Itoa(int(since)))
```
Comment (duglin) [inline integration-cli/docker_cli_events_test.go]: I think some clarity on what the default behavior is would be good. The docs (unless I missed it) don't seem to say what the default value for `--since` is. Is it "since time began" or is it "from now on" ?
Can we get a doc change to say which it is.

If its "since time began", since you added `--since=0` to all of theses, are we actually testing the default any more? The new test at the bottom would need to be modified to include some event prior to the `docker events` call.

If its "from now on" then that new test should be modified to include some docker commands that generates an event before the `docker events` call just to ensure that there's something in the event stream that will be skipped.

Comment (cpuguy83) [inline integration-cli/docker_cli_events_test.go]: This is exactly what all the other/older tests are already doing. So these tests were just wrong.

Comment (cpuguy83) [inline integration-cli/docker_cli_events_test.go]: Also the new test already does generate some events before calling events.

Comment (duglin) [inline integration-cli/docker_cli_events_test.go]: oops sorry - not sure how I missed the 'docker run'.  doi

**Comment by duglin** [comment]
LGTM

File: integration-cli/docker_cli_events_test.go (hunk 1 above)
Comment (duglin) [inline integration-cli/docker_cli_events_test.go]: I think the doc update would be good though

Comment (cpuguy83) [inline integration-cli/docker_cli_events_test.go]: Here's what the docs currently say:

>   --since=""         Show all events created since timestamp

And there are several examples of what timestamps can look like.
I don't think there's any need for a docs change here.

Comment (duglin) [inline integration-cli/docker_cli_events_test.go]: But it doesn't say what happens when there is no timestamp given.  Show all or show from "now".  Just something simple like:
```
When no '--since' value is specified, the default value is the current time.
```

**Comment by phobologic** [comment]
:+1:  Thanks for this!

**Comment by icecrime** [comment]
Code LGTM.

**Comment by icecrime** [comment]
Pushing to docs-review to clarify @duglin last questions.

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
ping @thaJeztah @moxiegirl so i can cherry-pick ;)

**Comment by thaJeztah** [comment]
This is fixing a regression in behavior from 1.6, and we were good with the way this was documented in 1.6, so I don't see the docs a "blocking issue" for this to be merged.

*However*, I agree with @duglin https://github.com/docker/docker/pull/13754#discussion_r31928353 that the current documentation is incomplete and doesn't clearly explain the behavior.

In short, @cpuguy83 if you want to add @duglin's suggestion to the [CLI docs](http://docs.master.dockerproject.org/reference/commandline/cli/#events) and [man page](https://github.com/docker/docker/blob/4e3b21f99e7fb7fac0075be2e7190d5f07c9ee66/docs/man/docker-events.1.md), that'd be great, but if this is blocking the release, I'm fine with merging as-is and a follow-up PR to improve the docs.

LGTM, with the notes above

**Comment by thaJeztah** [comment]
ping @moxiegirl if you agree with https://github.com/docker/docker/pull/13754#issuecomment-110656485

**Comment by cpuguy83** [comment]
Added minor doc changes.

**Comment by icecrime** [comment]
Thanks @cpuguy83! Ping @thaJeztah @moxiegirl for review.

File: docs/man/docker-events.1.md [hunk 2]
```diff
@@ -76,7 +76,10 @@ relative to the current time on the client machine:
     2015-05-12T15:53:45.999999999Z07:00  7805c1d35632: (from redis:2.8) die
     2015-05-12T15:54:03.999999999Z07:00  7805c1d35632: (from redis:2.8) stop
 
+If `--since` is not provided, only new/live events be shown
```
Comment (thaJeztah) [inline docs/man/docker-events.1.md]: If the `--since` option is not provided, only new/live events will be show.

(looking for better wording, but don't have anything right now)

File: docs/sources/reference/commandline/cli.md [hunk 3]
```diff
@@ -1125,7 +1125,8 @@ and Docker images will report:
 
 The `--since` and `--until` parameters can be Unix timestamps, RFC3339
 dates or Go duration strings (e.g. `10m`, `1h30m`) computed relative to
-client machine’s time.
+client machine’s time. If `--since` is not provided, only new/live events be
+shown
```
Comment (thaJeztah) [inline docs/sources/reference/commandline/cli.md]: Same here;

    If the `--since` option is not provided, only new/live events will be show.

**Comment by thaJeztah** [comment]
Thanks @cpuguy83, minor correction, apart from that LGTM

File: docs/sources/reference/commandline/cli.md (hunk 3 above)
Comment (moxiegirl) [inline docs/sources/reference/commandline/cli.md]: Active voice also awkward construction:

If you do not provide the `--since` option, the command returns only new and/or live events.

File: integration-cli/docker_cli_events_test.go (hunk 1 above)
Comment (moxiegirl) [inline integration-cli/docker_cli_events_test.go]: If you do not provide the `--since` option, the command returns only new and/or live events.

**Comment by cpuguy83** [comment]
Updated docs.

**Comment by thaJeztah** [comment]
LGTM, thanks!

**Comment by moxiegirl** [comment]
LGTM !

**Comment by jfrazelle** [comment]
cherry-picked

**Comment by phobologic** [comment]
Wow, thanks for the fast turn around time on this guys.  Awesome to see you all cranking through this. :)

**Comment by phobologic** [comment]
Quick question: When are changes that are merged into master built onto https://master.dockerproject.org/?  It looks like it hasn't been updated since the 8th.  Thanks!

**Comment by jfrazelle** [comment]
they are updated now, cache issue sorry
