### PR TITLE
Better error messages when IP address autodetection fails

### LINKED ISSUE #25141: Better error messages when IP address autodetection fails
The current error message explains that the system has more than one IP address, so Docker doesn't know which to use. We should be more specific. For example, if two interfaces both have IP addresses, we should list those interfaces. If one interface has multiple IPs, we should name that interface.

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to improve error messages when IP address autodetection fails, as is specified in #25141.

Previously, error messages only indicate that multiple IPs exist when autodetection fails. In this fix, if one interface consists of multiple addresses or multiple interfaces consist of addresses, the error messages output the address names and interface names so that end user could take notice.

This fix is verified manually.

When multiple addresses exist on multiple interfaces:

```
$ sudo docker swarm init
Error response from daemon: could not choose an IP address
to advertise since this system has multiple addresses
(192.168.186.128 on ens33 and 192.168.100.199 on eth10) on
different interfaces - specify one with --advertise-addr
```

When multiple addresses exist on single interface:

```
$ sudo docker swarm init
Error response from daemon: could not choose an IP address
to advertise since this system has multiple addresses
(192.168.186.128 and 192.168.55.199) on interface ens33
- specify one with --advertise-addr
```

This fix fixes #25141.

Signed-off-by: Yong Tang yong.tang.github@outlook.com

### CODE REVIEW

**Comment by aaronlehmann** [comment]
Thanks for doing this!

My only feedback is that the `interface:address` formatting in the output (`eth10:192.168.100.199`) might be confusing, especially when IPv6 addresses are involved. Maybe it's better to write it out with words (for example `192.168.100.199 on eth10`).

Other than that, it looks good.

**Comment by yongtang** [comment]
Thanks @aaronlehmann the pull request has been updated.

**Comment by aaronlehmann** [comment]
LGTM

File: daemon/cluster/listen_addr.go [hunk 1]
```diff
@@ -223,14 +223,16 @@ ifaceLoop:
 		// and exactly one IPv6 address, favor IPv4 over IPv6.
 		if interfaceAddr4 != nil {
 			if systemAddr != nil {
-				return nil, errMultipleIPs
+				return nil, fmt.Errorf("could not choose an IP address to advertise since this system has multiple addresses (%s on %s and %s on %s) on different interfaces", systemAddr, systemInterface.Name, interfaceAddr4, intf.Name)
```
Comment (aaronlehmann) [inline daemon/cluster/listen_addr.go]: Minor suggestion: Move the addresses and interfaces after "on different interfaces".

`could not choose an IP address to advertise since this system has multiple addresses on different interfaces (%s on %s and %s on %s)`

File: daemon/cluster/listen_addr.go [hunk 2]
```diff
@@ -223,14 +223,16 @@ ifaceLoop:
...
 			}
 			systemAddr = interfaceAddr4
+			systemInterface = intf
 		} else if interfaceAddr6 != nil {
 			if systemAddr != nil {
-				return nil, errMultipleIPs
+				return nil, fmt.Errorf("could not choose an IP address to advertise since this system has multiple addresses (%s on %s and %s on %s) on different interfaces", systemAddr, systemInterface.Name, interfaceAddr6, intf.Name)
```
Comment (aaronlehmann) [inline daemon/cluster/listen_addr.go]: Same here.

File: daemon/cluster/listen_addr.go (hunk 1 above)
Comment (yongtang) [inline daemon/cluster/listen_addr.go]: Thanks @aaronlehmann, PR has been updated.

File: daemon/cluster/listen_addr.go (hunk 2 above)
Comment (yongtang) [inline daemon/cluster/listen_addr.go]: Thanks @aaronlehmann, updated.

**Comment by vdemeester** [comment]
LGTM 👼

**Comment by thaJeztah** [comment]
@aaronlehmann this is for 1.13? or should this be included in 1.12.1 if we do a patch release?

**Comment by aaronlehmann** [comment]
@thaJeztah: I don't know if it should be in 1.12.1 according to the general policy, since it is not a fix for a serious bug. That said, it's a low-risk change that will help people understand errors - so it seems like it would be nice to have in a patch release.

**Comment by thaJeztah** [comment]
Given that auto-detection isn't perfect yet, I think this may help us debugging issues, so I'm adding this to the 1.12.1 milestone

/cc @tiborvass
