### PR TITLE
Handle `run --rm` against older daemons on the cli

### LINKED ISSUE #28439: Handling of `--rm` broken when talking to older daemons
With the new daemon-side auto-remove on exit, the `--rm` flag causes the CLI to hang when talking to an older (pre-1.13) daemon.

Reproduce:

1. Build a 1.13 client
2. Do a `docker run --rm` against a 1.12 daemon

### PR DESCRIPTION
**Pull request by cpuguy83**
For previous versions of Docker, `--rm` was handled client side, as such
there was no support in the daemon for it.
Now it is handled daemon side, but we still need to handle the case of a
newer client talking to an older daemon.

Falls back to client-side removal when the daemon does not support it.

Fixes #28439

### CODE REVIEW

File: cli/command/container/utils.go [hunk 1]
```diff
@@ -38,6 +49,17 @@ func waitExitOrRemoved(ctx context.Context, dockerCli *command.DockerCli, contai
 			if !waitRemove {
 				stopProcessing = true
 			}
+
+			// If we are talking to an older daemon, `AutoRemove` is not supported.
+			// We need to fall back to the old behavior, which is client-side removal
+			if waitRemove && versions.LessThan(dockerCli.Client().ClientVersion(), "1.25") {
```
Comment (WeiZhang555) [inline cli/command/container/utils.go]: I think this should be `dockerCli.Client().ServerVersion().Version`, it should detect daemon version but not the client version.

**Review by WeiZhang555 — CHANGES_REQUESTED** [review]

File: cli/command/container/utils.go [hunk 2]
```diff
@@ -53,27 +75,20 @@ func waitExitOrRemoved(ctx context.Context, dockerCli *command.DockerCli, contai
...
 	go func() {
 		defer cancel()
 
 		for {
 			select {
+			case <-eventCtx.Done():
+				if removeErr != nil {
+					logrus.Errorf("error removing container: %v", removeErr)
+					return
+				}
```
Comment (WeiZhang555) [inline cli/command/container/utils.go]: Also, I think if `ContainerRemove` failed and `removeError != nil`, client will still hang. Should we send exitcode to statusChan to make client exit? I mean 
```
				if removeErr != nil {
					logrus.Errorf("error removing container: %v", removeErr)
+					statusChan <- exitCode
					return
				}
```

**Review by WeiZhang555 — CHANGES_REQUESTED** [review]

File: cli/command/container/utils.go (hunk 1 above)
Comment (cpuguy83) [inline cli/command/container/utils.go]: No we want `ClientVersions()`, which is negotiated when the CLI is initialized.

**Comment by thaJeztah** [comment]
ping @mlaventure @tonistiigi PTAL!

File: cli/command/container/utils.go (hunk 2 above)
Comment (thaJeztah) [inline cli/command/container/utils.go]: @cpuguy83 ^^?

Comment (cpuguy83) [inline cli/command/container/utils.go]: Hmm... If container remove fails, removeErr will not be nil, the eventCtx will be cancelled, and the select will hit `eventCtx.Done()` and return.

If container remove does not fail then processing keeps going as usual until it gets the remove event and returns.

Comment (cpuguy83) [inline cli/command/container/utils.go]: I see. This is a little funky sense we're sending the exitCode in the even processor above in the everything is ok case.
Should probably be in a defer or something, WDYT?

Comment (cpuguy83) [inline cli/command/container/utils.go]: Updated, PTAL.

Comment (WeiZhang555) [inline cli/command/container/utils.go]: Looks good :+1:

File: cli/command/container/utils.go (hunk 1 above)
Comment (WeiZhang555) [inline cli/command/container/utils.go]: You are right :smile:

File: cli/command/container/utils.go [hunk 3]
```diff
@@ -38,45 +49,45 @@ func waitExitOrRemoved(ctx context.Context, dockerCli *command.DockerCli, contai
 			if !waitRemove {
 				stopProcessing = true
 			}
+
+			// If we are talking to an older daemon, `AutoRemove` is not supported.
+			// We need to fall back to the old behavior, which is client-side removal
+			if waitRemove && versions.LessThan(dockerCli.Client().ClientVersion(), "1.25") {
```
Comment (mlaventure) [inline cli/command/container/utils.go]: Nit: this could be an else clause

**Review by mlaventure — APPROVED** [review]
LGTM with a little nt

**Comment by tiborvass** [comment]
LGTM

**Comment by vieux** [comment]
LGTM after @mlaventure nit is addressed

**Comment by cpuguy83** [comment]
Updated.

**Review by vdemeester — APPROVED** [review]
LGTM :frog:
