### PR TITLE
daemon/graphdriver/btrfs: workaround field rename in btrfs-progs 6.1

### LINKED ISSUE #44698: daemon/graphdriver/btrfs/btrfs.go args.lim.max_referenced undefined
### Description

While building docker-20.10.22 on Funtoo linux with btrfs-progs 6.1, got this error

> daemon/graphdriver/btrfs/btrfs.go:437:11: args.lim.max_referenced undefined (type _Ctype_struct_btrfs_qgroup_limit has no field or method max_referenced)

### Reproduce

1. extract source
2. hack/make.sh dynbinary

### Expected behavior

Build not fail.

### docker version

```bash
Not relevant.
```

### docker info

```bash
Not relevant.
```

### Additional Info

Only fails with btrfs-progs 6.1, with previous versions (6.0.x) builds ok.

IMHO the change of btrfs-progs that caused this affect is 

https://github.com/kdave/btrfs-progs/commit/03451430de7cd2fad18b0f01745545758bc975a5

### PR DESCRIPTION
**Pull request by zhsj**
Closes: #44698

An ugly hack, but hmm...

### CODE REVIEW

**Comment by thaJeztah** [comment]
Hmm interesting error from GitHub;

```
ADD failed: failed to GET https://github.com/moby/busybox/releases/download/FRP-3329-gcf0fa4d13/busybox-w32-FRP-3329-gcf0fa4d13.exe with status 503 Service Unavailable: ﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>ServerBusy</Code><Message>Egress is over the account limit.
```

File: daemon/graphdriver/btrfs/btrfs.go [hunk 1]
```diff
@@ -4,6 +4,9 @@
 package btrfs // import "github.com/docker/docker/daemon/graphdriver/btrfs"
 
 /*
+// keep struct field name compatible with btrfs-progs < 6.1.
+#define max_referenced max_rfer
+
 #include <stdlib.h>
 #include <dirent.h>
 #include <btrfs/ioctl.h>
```
Comment (corhere) [inline daemon/graphdriver/btrfs/btrfs.go:12]:
```suggestion
#include <stdlib.h>
#include <dirent.h>

// keep struct field name compatible with btrfs-progs < 6.1.
#define max_referenced max_rfer
#include <btrfs/ioctl.h>
```

Just to be safe, in case the libc headers contain a `max_referenced` token.

**Review by corhere — APPROVED** [review]
That hack is _beautiful_! I'm ashamed I hadn't thought of it myself.

File: daemon/graphdriver/btrfs/btrfs.go (hunk 1 above)
Comment (zhsj) [reply daemon/graphdriver/btrfs/btrfs.go]: done

**Review by neersighted — APPROVED** [review]
