### PR TITLE
Fixed docker.internal.gateway not displaying properly on live restore

### LINKED ISSUE #42753: host.docker.internal:host-gateway on breaks on daemon restart with live-restore
**Description**
Restarting docker daemon breaks host.docker.internal:host-gateway mapping, only a host reboot seems to fix.
Tested this with live-restore set to false and this behavior does not occur (new containers get the IP instead of nil)

**Steps to reproduce the issue:**
1.  sudo docker run --add-host=host.docker.internal:host-gateway busybox sh -c 'cat /etc/hosts' -> 
    Outputs: ``` 172.17.0.1	host.docker.internal```
2. sudo service docker restart (or systemctl restart docker)
2. sudo docker run --add-host=host.docker.internal:host-gateway busybox sh -c 'cat /etc/hosts'
    Outputs: ```<nil>	host.docker.internal```

**Describe the results you received:**

```
<nil>	host.docker.internal
```

**Describe the results you expected:**

```
 172.17.0.1	host.docker.internal
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:49 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:54:13 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 9
  Running: 3
  Paused: 0
  Stopped: 6
 Images: 10
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1160.36.2.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.701GiB
 Name: <REDACTED>
 ID: <REDACTED>
 Docker Root Dir: /<REDACTED>/var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  <REDACTED>
 Live Restore Enabled: true

WARNING: bridge-nf-call-ip6tables is disabled
```

CentOS Linux release 7.9.2009 (Core) on VMware

### PR DESCRIPTION
**Pull request by sanchayanghosh**
fixes https://github.com/moby/moby/issues/42753

…erly

**- What I did**

I fixed the issue 42573, where the docker.internal.host-gateway was not assigned to containers after a reboot, when live-restore was enabled. This was to do with containers that ran after the docker daemon was restarted.

**- How I did it**

There was a function that assigned the host gateway IP addresses. I made sure that the IP address was also called inside the conditional that ran when there were active sandboxes.

**- How to verify it**

#42753 - details the steps

**- Description for the changelog**
 This pull request is a change to remove the recurrence of #42753 , by writing HostGatewayIP to a function and calling that once in the normal case and once when the sandboxes(containers) are running during daemon restart.

The pull request is a WIP since I am yet to write a unit test. I would need your guidance for it. I am not sure how to call the API for the test, for docker run --add-host=.... busybox in script form and getting the output. I know how to do it with fork/subprocess, but am not sure of the API approach to it.

**- A picture of a cute animal (not mandatory but encouraged)**

Not mine, but posting it here.

### CODE REVIEW

File: daemon/daemon_unix.go [hunk 1]
```diff
@@ -903,6 +905,14 @@ func (daemon *Daemon) initNetworkController(config *config.Config, activeSandbox
...
 	// Set HostGatewayIP to the default bridge's IP  if it is empty
+	setHostGatewayIP(daemon, controller)
+
+	return controller, nil
+}
+
+/* This is a function that runs a block of code initially inside of initNetworkController
+This is a potential fix to an issue #42753 relating to containers not receiving host bridge addresses */
+func setHostGatewayIP(daemon *Daemon, controller libnetwork.NetworkController) {
 	if daemon.configStore.HostGatewayIP == nil && controller != nil {
```
Comment (thaJeztah) [inline daemon/daemon_unix.go:916]: Perhaps instead of passing the whole daemon, we could make it get just the config-store. Looks like the nil-check for `controller` is also redundant (because at this point, we should always have a controller?)

Perhaps also change the `if` to use an early return, so that we don't need the nested ifs;

```go
// setHostGatewayIP sets cfg.HostGatewayIP to the default bridge's IP  if it is empty
func setHostGatewayIP(config *config.Config, controller libnetwork.NetworkController) {
	if config.HostGatewayIP != nil {
		return
	}
	if n, err := controller.NetworkByName("bridge"); err == nil {
	...
```

Comment (thaJeztah) [reply daemon/daemon_unix.go:916]: Not related to your change, but It's actually odd that we're passing `config` as argument to `initNetworkController()`, because it's already available through `daemon`. We should probably change that (in a follow-up PR) to _either_ remove `daemon` _or_ the argument;

https://github.com/moby/moby/blob/9e7bbdb9ba53440cfc67e2e1de89e35e44c43ddf/daemon/daemon.go#L475

**Review by thaJeztah — CHANGES_REQUESTED** [review]
thanks! overall, this approach seems to make sense; I left review comments inline.

**Comment by thaJeztah** [comment]
I have made the changes I suggested locally; I can open a PR against your branch if you want; diff is;

```patch
diff --git a/daemon/daemon_unix.go b/daemon/daemon_unix.go
index 1bed6aad9b..3288ad8fd5 100644
--- a/daemon/daemon_unix.go
+++ b/daemon/daemon_unix.go
@@ -867,7 +867,7 @@ func (daemon *Daemon) initNetworkController(config *config.Config, activeSandbox
 
 	if len(activeSandboxes) > 0 {
 		logrus.Info("There are old running containers, the network config will not take affect")
-		setHostGatewayIP(daemon, controller)
+		setHostGatewayIP(daemon.configStore, controller)
 		return controller, nil
 	}
 
@@ -905,25 +905,25 @@ func (daemon *Daemon) initNetworkController(config *config.Config, activeSandbox
 	}
 
 	// Set HostGatewayIP to the default bridge's IP  if it is empty
-	setHostGatewayIP(daemon, controller)
+	setHostGatewayIP(daemon.configStore, controller)
 
 	return controller, nil
 }
 
-/* This is a function that runs a block of code initially inside of initNetworkController
-This is a potential fix to an issue #42753 relating to containers not receiving host bridge addresses */
-func setHostGatewayIP(daemon *Daemon, controller libnetwork.NetworkController) {
-	if daemon.configStore.HostGatewayIP == nil && controller != nil {
-		if n, err := controller.NetworkByName("bridge"); err == nil {
-			v4Info, v6Info := n.Info().IpamInfo()
-			var gateway net.IP
-			if len(v4Info) > 0 {
-				gateway = v4Info[0].Gateway.IP
-			} else if len(v6Info) > 0 {
-				gateway = v6Info[0].Gateway.IP
-			}
-			daemon.configStore.HostGatewayIP = gateway
-		}
+// setHostGatewayIP sets cfg.HostGatewayIP to the default bridge's IP  if it is empty
+func setHostGatewayIP(config *config.Config, controller libnetwork.NetworkController) {
+	if config.HostGatewayIP != nil {
+		return
+	}
+	if n, err := controller.NetworkByName("bridge"); err == nil {
+		v4Info, v6Info := n.Info().IpamInfo()
+		var gateway net.IP
+		if len(v4Info) > 0 {
+			gateway = v4Info[0].Gateway.IP
+		} else if len(v6Info) > 0 {
+			gateway = v6Info[0].Gateway.IP
+		}
+		config.HostGatewayIP = gateway
 	}
 }
 
```

**Comment by thaJeztah** [comment]
Opened https://github.com/sanchayanghosh/moby/pull/1 if that's easier (please squash the commits after that)

**Comment by sanchayanghosh** [comment]
Didn't see you message then. I have merged your PR. Thanks a lot for the changes you made. I should have thought of them myself. If the CI check is successful, should be ready to merge.

**Review by thaJeztah — CHANGES_REQUESTED** [review]
thanks! changes LGTM; could you squash the commits? (it's ok to squash my commit with yours; it's cleaner to have a single commit with the changes from this PR)

Let me know if you need help / instructions on doing so!

**Review by thaJeztah — APPROVED** [review]
LGTM (assuming "green")

did a quick rebase/squash

**Comment by sanchayanghosh** [comment]
Sorry for the delay in replying! Didn't check my github for a long time.Thanks for looking into my commit. I guess you have squashed the commit.

I guess all that is left now is to figure out which unit tests are failing and root cause those issues.

**Comment by sanchayanghosh** [comment]
From the CI cycle: 

1. [2021-11-03T14:03:13.278Z]     build_test.go:572: assertion failed: value "{\"stream\":\"Step 1/8 : FROM busybox AS intermediate\"}\r\n{\"stream\":\"\\n\"}\r\n{\"stream\":\" ---\\u003e e62f5033c360\\n\"}\r\n{\"stream\":\"Step 2/8 : WORKDIR C:\\\\\\\\stuff\"}\r\n{\"stream\":\"\\n\"}\r\n{\"stream\":\" ---\\u003e Running in 6fdb2bcb8a93\\n\"}\r\n{\"stream\":\"Removing intermediate container 6fdb2bcb8a93\\n\"}\r\n{\"stream\":\" ---\\u003e b71154038b3f\\n\"}\r\n{\"stream\":\"Step 3/8 : RUN fsutil file createnew C:\\\\\\\\stuff\\\\\\\\bigfile_0.txt 22548578304 \\u0026\\u0026 del bigfile_0.txt\"}\r\n{\"stream\":\"\\n\"}\r\n{\"stream\":\" ---\\u003e Running in b85d42eb2ce5\\n\"}\r\n{\"stream\":\"File C:\\\\stuff\\\\bigfile_0.txt is created\\r\\n\"}\r\n{\"stream\":\"Removing intermediate container b85d42eb2ce5\\n\"}\r\n{\"stream\":\" ---\\u003e 2600516b85e0\\n\"}\r\n{\"stream\":\"Step 4/8 : RUN fsutil file createnew C:\\\\\\\\stuff\\\\\\\\bigfile_1.txt 7516192768\"}\r\n{\"stream\":\"\\n\"}\r\n{\"stream\":\" ---\\u003e Running in fe47b0eb34a6\\n\"}\r\n{\"stream\":\"File C:\\\\stuff\\\\bigfile_1.txt is created\\r\\n\"}\r\n{\"stream\":\"Removing intermediate container fe47b0eb34a6\\n\"}\r\n{\"stream\":\" ---\\u003e 4ca7c7be8f54\\n\"}\r\n{\"stream\":\"Step 5/8 : RUN fsutil file createnew C:\\\\\\\\stuff\\\\\\\\bigfile_2.txt 7516192768\"}\r\n{\"stream\":\"\\n\"}\r\n{\"stream\":\" ---\\u003e Running in f9e64ed2f7e5\\n\"}\r\n{\"stream\":\"File C:\\\\stuff\\\\bigfile_2.txt is created\\r\\n\"}\r\n{\"stream\":\"Removing intermediate container f9e64ed2f7e5\\n\"}\r\n{\"stream\":\" ---\\u003e 735e0fa624e1\\n\"}\r\n{\"stream\":\"Step 6/8 : RUN fsutil file createnew C:\\\\\\\\stuff\\\\\\\\bigfile_3.txt 7516192768\"}\r\n{\"stream\":\"\\n\"}\r\n{\"stream\":\" ---\\u003e Running in 1e57751521cf\\n\"}\r\n{\"stream\":\"File C:\\\\stuff\\\\bigfile_3.txt is created\\r\\n\"}\r\n{\"stream\":\"Removing intermediate container 1e57751521cf\\n\"}\r\n{\"stream\":\" ---\\u003e b2cf04c5e66c\\n\"}\r\n{\"aux\":{\"ID\":\"sha256:b2cf04c5e66c8619f23ec60bc5903ca1648bd2ebab249f3d3e2cfce832e05404\"}}\r\n{\"stream\":\"Step 7/8 : FROM busybox\"}\r\n{\"stream\":\"\\n\"}\r\n{\"stream\":\" ---\\u003e e62f5033c360\\n\"}\r\n{\"stream\":\"Step 8/8 : COPY --from=intermediate C:\\\\\\\\stuff C:\\\\\\\\stuff\"}\r\n{\"stream\":\"\\n\"}\r\n{\"errorDetail\":{\"message\":\"re-exec error: exit status 1: output: hcsshim::ImportLayer - failed failed in Win32: The system cannot find the path specified. (0x3)\"},\"error\":\"re-exec error: exit status 1: output: hcsshim::ImportLayer - failed failed in Win32: The system cannot find the path specified. (0x3)\"}\r\n" does not match regexp "Successfully built|re-exec error: exit status 1: output: write.*daemon\\\\\\\\tmp\\\\\\\\hcs.*bigfile_[1-3].txt: There is not enough space on the disk."
and 

2021-11-03T14:03:13.279Z] === FAIL: github.com/docker/docker/integration/build TestBuildWCOWSandboxSize (567.49s)

[2021-11-03T14:03:13.279Z]     build_test.go:572: assertion failed: value "{\"stream\":\"Step 1/8 : FROM busybox AS intermediate\"}\r\n{\"stream\":\"\\n\"}\r\n{\"stream\":\" ---\\u003e e62f5033c360\\n\"}\r\n{\"stream\":\"Step 2/8 : WORKDIR C:\\\\\\\\stuff\"}\r\n{\"stream\":\"\\n\"}\r\n{\"stream\":\" ---\\u003e Running in 6fdb2bcb8a93\\n\"}\r\n{\"stream\":\"Removing intermediate container 6fdb2bcb8a93\\n\"}\r\n{\"stream\":\" ---\\u003e b71154038b3f\\n\"}\r\n{\"stream\":\"Step 3/8 : RUN fsutil file createnew C:\\\\\\\\stuff\\\\\\\\bigfile_0.txt 22548578304 \\u0026\\u0026 del bigfile_0.txt\"}\r\n{\"stream\":\"\\n\"}\r\n{\"stream\":\" ---\\u003e Running in b85d42eb2ce5\\n\"}\r\n{\"stream\":\"File C:\\\\stuff\\\\bigfile_0.txt is created\\r\\n\"}\r\n{\"stream\":\"Removing intermediate container b85d42eb2ce5\\n\"}\r\n{\"stream\":\" ---\\u003e 2600516b85e0\\n\"}\r\n{\"stream\":\"Step 4/8 : RUN fsutil file createnew C:\\\\\\\\stuff\\\\\\\\bigfile_1.txt 7516192768\"}\r\n{\"stream\":\"\\n\"}\r\n{\"stream\":\" ---\\u003e Running in fe47b0eb34a6\\n\"}\r\n{\"stream\":\"File C:\\\\stuff\\\\bigfile_1.txt is created\\r\\n\"}\r\n{\"stream\":\"Removing intermediate container fe47b0eb34a6\\n\"}\r\n{\"stream\":\" ---\\u003e 4ca7c7be8f54\\n\"}\r\n{\"stream\":\"Step 5/8 : RUN fsutil file createnew C:\\\\\\\\stuff\\\\\\\\bigfile_2.txt 7516192768\"}\r\n{\"stream\":\"\\n\"}\r\n{\"stream\":\" ---\\u003e Running in f9e64ed2f7e5\\n\"}\r\n{\"stream\":\"File C:\\\\stuff\\\\bigfile_2.txt is created\\r\\n\"}\r\n{\"stream\":\"Removing intermediate container f9e64ed2f7e5\\n\"}\r\n{\"stream\":\" ---\\u003e 735e0fa624e1\\n\"}\r\n{\"stream\":\"Step 6/8 : RUN fsutil file createnew C:\\\\\\\\stuff\\\\\\\\bigfile_3.txt 7516192768\"}\r\n{\"stream\":\"\\n\"}\r\n{\"stream\":\" ---\\u003e Running in 1e57751521cf\\n\"}\r\n{\"stream\":\"File C:\\\\stuff\\\\bigfile_3.txt is created\\r\\n\"}\r\n{\"stream\":\"Removing intermediate container 1e57751521cf\\n\"}\r\n{\"stream\":\" ---\\u003e b2cf04c5e66c\\n\"}\r\n{\"aux\":{\"ID\":\"sha256:b2cf04c5e66c8619f23ec60bc5903ca1648bd2ebab249f3d3e2cfce832e05404\"}}\r\n{\"stream\":\"Step 7/8 : FROM busybox\"}\r\n{\"stream\":\"\\n\"}\r\n{\"stream\":\" ---\\u003e e62f5033c360\\n\"}\r\n{\"stream\":\"Step 8/8 : COPY --from=intermediate C:\\\\\\\\stuff C:\\\\\\\\stuff\"}\r\n{\"stream\":\"\\n\"}\r\n{\"errorDetail\":{\"message\":\"re-exec error: exit status 1: output: hcsshim::ImportLayer - failed failed in Win32: The system cannot find the path specified. (0x3)\"},\"error\":\"re-exec error: exit status 1: output: hcsshim::ImportLayer - failed failed in Win32: The system cannot find the path specified. (0x3)\"}\r\n" does not match regexp "Successfully built|re-exec error: exit status 1: output: write.*daemon\\\\\\\\tmp\\\\\\\\hcs.*bigfile_[1-3].txt: There is not enough space on the disk."

are causing failure.

**Comment by thaJeztah** [comment]
CI is green now, after fixes in master were merged

@AkihiroSuda @tianon PTAL 🤗

**Review by tianon — APPROVED** [review]

**Review by AkihiroSuda — APPROVED** [review]

**Comment by tribut** [comment]
Any chance this will make it into a 20.10 bugfix release?

**Comment by danger89** [comment]
To be honest I still have this issue indeed under 20.10...!?? Not nice. 20.10 is a LTS release.

```
Client: Docker Engine - Community
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:28:04 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:25:49 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.15
  GitCommit:        5b842e528e99d4d4c1686467debf2bd4b88ecd86
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by sanchayanghosh** [comment]
I see that this #43275 , the fix is in 22.06.0-beta.0. There you should see the gateway should be available when you do a live restore.

**Comment by danger89** [comment]
> There you should see the gateway should be available when you do a live restore.

What?

This fix needs to be ported to v20.10.
