### PR TITLE
Make TestLogsAPIStdout a bit less racey

### LINKED ISSUE #33301: Racey test TestLogsAPIStdout
I've seen this fail a few times on Windows recently:

```
02:43:14 FAIL: docker_api_logs_test.go:15: DockerSuite.TestLogsAPIWithStdout
02:43:14 
02:43:14 docker_api_logs_test.go:50:
02:43:14     c.Fatal("timeout waiting for logs to exit")
02:43:14 ... Error: timeout waiting for logs to exit
02:43:14 
02:43:14 
02:43:14 ----------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by cpuguy83**

### CODE REVIEW

**Comment by cpuguy83** [comment]
Failed Windows test is not this one :)

```
11:45:43 FAIL: docker_cli_restart_test.go:265: DockerSuite.TestRestartContainerwithRestartPolicy
11:45:43 
11:45:43 docker_cli_restart_test.go:282:
11:45:43     // Make sure we can stop/start (regression test from a705e166cf3bcca62543150c2b3f9bfeae45ecfa)
11:45:43     dockerCmd(c, "stop", id1)
11:45:43 c:/gopath/src/github.com/docker/docker/pkg/testutil/cmd/command.go:64:
11:45:43     t.Fatalf("at %s:%d - %s", filepath.Base(file), line, err.Error())
11:45:43 ... Error: at cli.go:48 - 
11:45:43 Command:  d:\CI\CI-409bc3bff\binary\docker.exe stop 95484bdbc31eb113b86ba1fad0dd46016a580c8777cbc273795c515015c79d3b
11:45:43 ExitCode: 1
11:45:43 Error:    exit status 1
11:45:43 Stdout:   
11:45:43 Stderr:   Error response from daemon: Cannot stop container 95484bdbc31eb113b86ba1fad0dd46016a580c8777cbc273795c515015c79d3b: Cannot kill container 95484bdbc31eb113b86ba1fad0dd46016a580c8777cbc273795c515015c79d3b: invalid container: 95484bdbc31eb113b86ba1fad0dd46016a580c8777cbc273795c515015c79d3b
```

File: integration-cli/docker_api_logs_test.go [hunk 1]
```diff
@@ -19,34 +19,31 @@ func (s *DockerSuite) TestLogsAPIWithStdout(c *check.C) {
 
 	type logOut struct {
 		out string
-		res *http.Response
 		err error
 	}
+
 	chLog := make(chan logOut)
+	res, body, err := request.Get(fmt.Sprintf("/containers/%s/logs?follow=1&stdout=1&timestamps=1", id))
```
Comment (aaronlehmann) [inline integration-cli/docker_api_logs_test.go]: nit: Could use the `+` operator for string concatenation instead of `Sprintf`. I find that easier to read and safer against type safety bugs and argument mismatch bugs, but I know now everyone shares the opinion.

**Comment by aaronlehmann** [comment]
Not sure I understand the fix. The main change seems to be moving `request.Get` out of the goroutine. Was this method taking a very long time, and causing the timeout to be reached?

**Comment by cpuguy83** [comment]
@aaronlehmann Well there is no way to know if we've even fired off the request (outside of actually communicating that out of the goroutine).
The request itself does not need to be in a goroutine since it's not blocking.

**Comment by aaronlehmann** [comment]
> The request itself does not need to be in a goroutine since it's not blocking.

I agree, but I don't understand what was causing the test to fail, and why moving this out of the goroutine would fix it.

**Comment by cpuguy83** [comment]
@aaronlehmann We have a guarantee that the logs call actually ran and thus something that we can really base the timeout on.

The change is removing the potential for flakiness as much as possible.

**Comment by aaronlehmann** [comment]
If the call to `Get` doesn't complete after 20 seconds, isn't it appropriate for the test to fail anyway?

Again, I have no issue with moving this call out of the goroutine, I just don't see how it fixes the problem.

**Comment by cpuguy83** [comment]
@aaronlehmann It depends... right now the code is dependent on the client which is why it's potentially flakey. But if there's some issue connecting to the daemon then we should get a client timeout anyway.

**Comment by aaronlehmann** [comment]
LGTM, because I think this makes sense and does no harm, but I'd ask to remove `Fixes #33301` from the description, because I'm not confident it will fix the problem.

**Review by dnephin — APPROVED** [review]
LGTM
