### PR TITLE
Set OS on scratch image and prevent panic if empty

### LINKED ISSUE #35413: docker build exits successfully but fails to build image
**Description**

My `docker build -t test .` invocation exits with code 0 but the build is not completed and the tag is not created.

**Steps to reproduce the issue:**

Using the `Dockerfile`:
```
FROM alpine AS base

FROM scratch

COPY --from=base /bin /

LABEL foo=bar

# This line is never executed:
CMD /sh
```
Run the command:
```
$ docker build -t test .
```

**Describe the results you received:**
```
Sending build context to Docker daemon  31.19MB
Step 1/5 : FROM alpine AS base
latest: Pulling from library/alpine
b56ae66c2937: Pull complete 
Digest: sha256:d6bfc3baf615dc9618209a8d607ba2a8103d9c8a405b3bd8741d88b4bef36478
Status: Downloaded newer image for alpine:latest
 ---> 053cde6e8953
Step 2/5 : FROM scratch
 ---> 
Step 3/5 : COPY --from=base /bin /
 ---> b9b01ebc02ce
Step 4/5 : LABEL foo=bar
$ echo $?
0
```
Notice how
- the last step to execute is 4/5
- no tag is created
- the command succeeds

If I remove the `COPY` then it succeeds properly. If I permute the last 2 lines (the `LABEL` and the `CMD` after the `COPY`) then it fails in the same way: always at step 4/5. If I insert additional `COPY` steps then they execute successfully (but the overall build still fails to complete)

**Describe the results you expected:**

On `17.09.0-ce` it works as follows:
```
$ docker build -t test .
Sending build context to Docker daemon  31.19MB
Step 1/5 : FROM alpine AS base
latest: Pulling from library/alpine
b56ae66c2937: Pull complete 
Digest: sha256:d6bfc3baf615dc9618209a8d607ba2a8103d9c8a405b3bd8741d88b4bef36478
Status: Downloaded newer image for alpine:latest
 ---> 053cde6e8953
Step 2/5 : FROM scratch
 ---> 
Step 3/5 : COPY --from=base /bin /
 ---> f6ca610bcf97
Step 4/5 : LABEL foo bar
 ---> Running in 8b63bfa48014
 ---> 1046dd92658e
Removing intermediate container 8b63bfa48014
Step 5/5 : CMD /sh
 ---> Running in 764e0e54304c
 ---> 1e6bade266fd
Removing intermediate container 764e0e54304c
Successfully built 1e6bade266fd
Successfully tagged test:latest
$ echo $?
0
```

Notice
- all 5/5 steps are executed
- the tag is created
- the command exits successfully

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      17.11.0-ce-rc2
 API version:  1.34
 Go version:   go1.8.4
 Git commit:   d7062e5
 Built:        Wed Nov  1 22:08:25 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.11.0-ce-rc2
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.5
 Git commit:   d7062e5
 Built:        Wed Nov  1 22:14:52 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
$ docker info
Containers: 10
 Running: 0
 Paused: 0
 Stopped: 10
Images: 104
Server Version: 17.11.0-ce-rc2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: v1.0.0-beta.2-53-g992280e8 (expected: 992280e8e265f491f7a624ab82f3e238be086e49)
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.44-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: 5QEB:AR7F:CK5A:RJXE:YARC:SWGG:OK56:EMXW:2NTY:HY74:OWT6:6UKE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 23
 Goroutines: 42
 System Time: 2017-11-06T13:51:06.52057428Z
 EventsListeners: 2
No Proxy: *.local, 169.254.0.0/16, *.io
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This is Docker for Mac with 17.11.0-ce-rc2.
```
Version 17.11.0-ce-rc2-mac37 (20033)
Channel: edge
d7d657d636
```

### PR DESCRIPTION
**Pull request by johnstep**
Signed-off-by: John Stephens <johnstep@docker.com>

This change fixes https://github.com/moby/moby/issues/35413 and adds a test. The regression was introduced with https://github.com/moby/moby/commit/0380fbff37922cadf294851b1546f4c212c7f364, which requires an OS from the image. Images built from scratch did not specify an OS, leading to the eventual panic.

### CODE REVIEW

File: integration-cli/docker_api_build_test.go [hunk 1]
```diff
@@ -619,6 +619,28 @@ func testBuildWithSession(c *check.C, dir, dockerfile string) (outStr string) {
...
+	res, body, err := request.Post(
+		"/build",
+		request.RawContent(ctx.AsTarReader(c)),
+		request.ContentType("application/x-tar"))
+	c.Assert(err, checker.IsNil)
+	c.Assert(res.StatusCode, checker.Equals, http.StatusOK)
+
+	out, err := request.ReadBody(body)
+	require.NoError(c, err)
+	assert.Contains(c, string(out), "Successfully built")
```
Comment (tonistiigi) [inline integration-cli/docker_api_build_test.go]: Ideally, we should check here that `OS` was set. Do you know why there is an override in inspect that currently prevents it https://github.com/moby/moby/blob/b00b1b1c40750dd0239fb30e421686b63b4183bd/daemon/image_inspect.go#L22-L25. That doesn't look correct. (cc @jhowardmsft )

File: daemon/create.go [hunk 2]
```diff
@@ -95,7 +95,14 @@ func (daemon *Daemon) create(params types.ContainerCreateConfig, managed bool) (
...
-		os = img.OS
+		if img.OS != "" {
+			os = img.OS
+		} else {
+			// default to the host OS except on Windows with LCOW
+			if runtime.GOOS == "windows" && system.LCOWSupported() {
+				os = "linux"
+			}
+		}
 		imgID = img.ID()
```
Comment (tonistiigi) [inline daemon/create.go]: We should also validate that the os in image is actually valid, and produces a correct error if it is not instead of letting it panic. This can be follow-up in another PR as it is related but not quite the same issue and there are probably more places that need this check.

**Review by tonistiigi — COMMENTED** [review]
Some comments, overall LGTM if green

**Review by vdemeester — APPROVED** [review]
LGTM 🐮

**Comment by thaJeztah** [comment]
Wondering if there's corner cases where an 'FROM scratch' image should remain platform-independent (perhaps there's none, but I was just wondering when reading this PR)

File: integration-cli/docker_api_build_test.go (hunk 1 above)
Comment (jhowardmsft) [reply integration-cli/docker_api_build_test.go]: @tonistiigi It's removed in the PR to re-coalesce the stores. https://github.com/moby/moby/pull/34859/files#diff-1ed32f2ce4c90e536bbbb9ede729120cL21

**Comment by jhowardmsft** [comment]
@thaJeztah Supporting `FROM scratch` on Windows is technically not feasible (Windows Containers on Windows, that is). We can support it for LCOW though. So on that basis currently, scratch implies Linux.

File: builder/dockerfile/imagecontext.go [hunk 3]
```diff
@@ -73,7 +75,13 @@ func (m *imageSources) Unmount() (retErr error) {
 func (m *imageSources) Add(im *imageMount) {
 	switch im.image {
 	case nil:
-		im.image = &dockerimage.Image{}
+		// set the OS for scratch images
+		os := runtime.GOOS
+		// Windows does not support scratch except for LCOW
+		if runtime.GOOS == "windows" {
+			os = "linux"
```
Comment (jhowardmsft) [inline builder/dockerfile/imagecontext.go]: I think this should have a guard for `LCOWSupported()` in this version of the codebase (although it will be removed once https://github.com/moby/moby/pull/34859 gets merged)

**Review by lowenna — APPROVED** [review]
LGTM with one minor nit that doesn't really need addressing.

File: daemon/create.go (hunk 2 above)
Comment (jhowardmsft) [reply daemon/create.go]: This is indirectly addressed by the store re-coalescing PR.

**Comment by thaJeztah** [comment]
> Supporting FROM scratch on Windows is technically not feasible (Windows Containers on Windows, that is). 

Yes, I realise you cannot _run_ an image "from scratch", but use case I had in mind (and which is known to be used) is things like;

```
FROM scratch
COPY /static_html/ /var/www
VOLUME /var/www
```

```bash
docker build -t static:latest .
docker create --name content static:latest
docker run --volumes-from=content mywebserver
```

Wasn't sure if that worked on Windows 😅

**Comment by jhowardmsft** [comment]
@thaJeztah No, that won't work.
