### PR TITLE
fix `docker cp -a` failing to access `/` in container (run `getent` with a noop stdin)

### LINKED ISSUE #45719: docker cp -a broken in 24.0
### Description

docker copy with archive mode enabled is broken in 24.0

### Reproduce

```
$ docker run --name test --user 1000 alpine
$ docker cp -a foo.txt test:/
Error response from daemon: Could not find the file / in container test
```

### Expected behavior

copy is successful

### docker version

```bash
Client:
 Version:      unknown-version
 API version:  1.30
 Go version:   go1.20.4
 Git commit:   unknown-commit
 Built:        unknown-buildtime
 OS/Arch:      linux/arm64

Server:
 Version:      dev
 API version:  1.43 (minimum version 1.12)
 Go version:   go1.20.4
 Git commit:   659604f9ee
 Built:        Fri Jun  9 08:45:12 2023
 OS/Arch:      linux/arm64
 Experimental: false
```

### docker info

```bash
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: dev
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Using metacopy: false
 Native Overlay Diff: true
 userxattr: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: crun io.containerd.runc.v2 runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 1677a17964311325ed1c31e2c0a3589ce6d5c30d
runc version: v1.1.7-0-g860f061
init version: de40ad0
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: builtin
 cgroupns
Kernel Version: 5.15.49-linuxkit-pr
Operating System: Debian GNU/Linux 11 (bullseye) (containerized)
OSType: linux
Architecture: aarch64
CPUs: 5
Total Memory: 7.667GiB
Name: f0200a2aa625
ID: bf489987-0cf4-44df-b671-abd8b8b67076
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 25
 Goroutines: 41
 System Time: 2023-06-09T09:07:02.540923671Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### Additional Info

I ran this issue in Moby development container with a debugger attached

When `docker cp` uses copyGUID flag set to true, engine need to resolve configured user ID in [callGetent](https://github.com/moby/moby/blob/master/pkg/idtools/idtools_unix.go#L163) by running `/usr/bin/getent passwd 1000`
I can run this exact same command in moby dev container:
```
root@f0200a2aa625:/go/src/github.com/docker/docker# /usr/bin/getent passwd 1000
unprivilegeduser:x:1000:999::/home/unprivilegeduser:/bin/sh
```
but from daemon code, running this command with `os.exec.Run` fails with error:
```
fs.PathError {
Op = {string} "open"
Path = {string} "/dev/null"
Err = {error | syscall.Errno} github.com/docker/docker/vendor/github.com/cilium/ebpf/internal/unix.ENOENT (2)
}
```

this is caused by stdin being set to `nil` for this command, so `/dev/null` is used instead (https://github.com/golang/go/blob/master/src/os/exec/exec.go#L491) and `os.Open(os.DevNull)` triggers this weird error

### PR DESCRIPTION
**Pull request by ndeloof**
fixes https://github.com/moby/moby/issues/45719 (actually, just a workaround)

**- What I did**
configure command to run `getent` to use a noop readCloser as stdin to prevent ENOENT failure to open `/dev/null`

**- How I did it**

**- How to verify it**
test case included

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**
image

### CODE REVIEW

**Comment by ndeloof** [comment]
test fails with
```
copy_test.go:104: assertion failed: error is not nil: error during connect: Put "http://%2Fgo%2Fsrc%2Fgithub.com%2Fdocker%2Fdocker%2Fbundles%2Ftest-integration%2Fdocker.sock/v1.44/containers/4446d6b05ba6d3859beac4894a89652a0bba29cefa0c3157d0f0f4571879c64f/archive?copyUIDGID=true&noOverwriteDirNonDir=true&path=%2F": io: read/write on closed pipe
```
while doing this by CLI works:
```
$ touch foo
$ docker cp -a foo test:/tmp 
                             Successfully copied 1.54kB to test:/tmp
```

**Review by glours — APPROVED** [review]
LGTM

File: foo
Comment (rumpl) [inline foo:1]: Not sure this is needed?

Comment (ndeloof) [reply foo:1]: oh indeed, file I created running manual test in development container

**Comment by cpuguy83** [comment]
Seems like a strange thing:

```console
$ getent passwd 1000 < /dev/null
cpuguy83:x:1000:1000:Ubuntu:/home/cpuguy83:/bin/bash
```

Also doing the same in go works just fine as well.

**Comment by neersighted** [comment]
I'm not convinced this is right at all either -- if `nil` Stdin is breaking something, I think that represents a regression in the Go runtime and not something to work around in Moby.

**Comment by ndeloof** [comment]
@neersighted I totally agree with you, this is at most a temporary workaround. Maybe this deserve a `FIXME` note
I have no explanation why `os.Open(os.DevNull)` fails in this specific scenario with:
```
fs.PathError {
Op = {string} "open"
Path = {string} "/dev/null"
Err = {error | syscall.Errno} github.com/docker/docker/vendor/github.com/cilium/ebpf/internal/unix.ENOENT (2)
}
```
but I haven't found any bug reported to the golang team related to such an issue, and have no idea how to investigate further.

**Comment by rumpl** [comment]
During copy the [container filesystem is mounted](https://github.com/moby/moby/blob/master/daemon/containerfs_linux.go#L83-L145) and the archive code gets a view of that filesystem, `/dev/` is not mounted there, that's why you get this error.

I tried adding a simple

```golang
if err := mount.Mount("/dev", dest, "tmpfs", "rbind"); err != nil {
	return err
}
```

But then the copy fails with `getent unable to find entry "1000" in passwd database`

File: pkg/idtools/idtools_unix.go [hunk 1]
```diff
@@ -166,7 +166,9 @@ func callGetent(database, key string) (io.Reader, error) {
 	if getentCmd == "" {
 		return nil, fmt.Errorf("unable to find getent command")
 	}
-	out, err := exec.Command(getentCmd, database, key).CombinedOutput()
+	command := exec.Command(getentCmd, database, key)
+	command.Stdin = io.NopCloser(bytes.NewReader(nil))
```
Comment (cpuguy83) [inline pkg/idtools/idtools_unix.go:170]: Maybe a comment here why this is needed.

**Comment by neersighted** [comment]
It appears this isn't a regression then, but a subtle breaking change where the Go runtime depends on the `/dev/null` device node being available. I wonder if it's worth the trouble to provide some basic device nodes during copy -- likely this is more pragmatic, but it seems possible that we could run into similar issues in the future.

**Comment by ndeloof** [comment]
according to https://github.com/moby/moby/pull/45720#issuecomment-1585133396 this is actually a reasonable fix, but need to add some comment to explain the reason for this. I'll update my PR on Monday

**Review by neersighted — APPROVED** [review]

File: pkg/idtools/idtools_unix.go [hunk 2]
```diff
@@ -166,7 +166,10 @@ func callGetent(database, key string) (io.Reader, error) {
 	if getentCmd == "" {
 		return nil, fmt.Errorf("unable to find getent command")
 	}
-	out, err := exec.Command(getentCmd, database, key).CombinedOutput()
+	command := exec.Command(getentCmd, database, key)
+	// we run getent within container filesystem, but without /dev so /dev/null is not available for exec to mock stdin
```
Comment (neersighted) [inline pkg/idtools/idtools_unix.go:170]: 'close' might be more accurate than 'mock'; but this is fine.

**Review by cpuguy83 — APPROVED** [review]

File: integration/container/copy_test.go [hunk 3]
```diff
@@ -65,6 +65,34 @@ func TestCopyToContainerPathDoesNotExist(t *testing.T) {
 func TestCopyEmptyFile(t *testing.T) {
 	defer setupTest(t)()
 
+	ctx := context.Background()
+	apiclient := testEnv.APIClient()
+	cid := container.Create(ctx, t, apiclient)
+
+	// empty content
+	dstDir, _ := makeEmptyArchive(t)
+	err := apiclient.CopyToContainer(ctx, cid, dstDir, bytes.NewReader([]byte("")), types.CopyToContainerOptions{})
```
Comment (thaJeztah) [inline integration/container/copy_test.go:74]: Not a blocker; we probably could've used subtests for these

File: integration/container/copy_test.go [hunk 4]
```diff
@@ -65,6 +65,34 @@ func TestCopyToContainerPathDoesNotExist(t *testing.T) {
...
+	assert.NilError(t, err)
```
Comment (thaJeztah) [inline integration/container/copy_test.go:75]: Not a blocker; using `assert.Check()` allows the test to continue (`assert.NilError()` does a `t.Fatal()`, which in this case means we won't test the other cases if an earlier one fails)

```suggestion
	assert.Check(t, err)
```

**Review by thaJeztah — APPROVED** [review]
LGTM
