### PR TITLE
Fix issue with multiple volume refs with same name

### LINKED ISSUE #20378: [1.10.0] Docker daemon panics and freezes when starting a volumes-from container
When creating a "volumes" container and mounting it in another as a "volumes-from" container, Docker daemon panics:

```bash
#! /bin/bash

export DOCKER_HOST=127.0.0.1:2375

curl -v ${DOCKER_HOST}/containers/create?name=sample1 \
  -H 'Content-Type: application/json' \
  -X POST \
  -d '{"Image":"ubuntu","Volumes":{"/tmp":{}}}'

curl -v ${DOCKER_HOST}/containers/create?name=sample2 \
  -H 'Content-Type: application/json' \
  -X POST \
  -d '{"Image":"ubuntu","HostConfig":{"VolumesFrom":["sample1"]}}'

curl -v ${DOCKER_HOST}/containers/sample2/start \
  -H 'Content-Type: application/json' \
  -X POST \
  -d '{"VolumesFrom":["sample1"]}'
``` 

In short, the above recipe is this:
* Create a `-v /tmp` sample1 container
* Create a `--volumes-from=sample1` sample2 container
* Start the sample2 container.

This results in a panic and the Docker daemon becomes unresponsive to any further API calls after that:

```
DEBU[0008] POST /containers/sample2/start               
DEBU[0008] form data: {"VolumesFrom":["sample1"]}       
WARN[0008] DEPRECATED: Setting host configuration options when the container starts is deprecated and will be removed in Docker 1.12 
2016/02/16 19:47:49 http: panic serving 127.0.0.1:60308: runtime error: slice bounds out of range
goroutine 76 [running]:
net/http.(*conn).serve.func1(0xc82009c6e0, 0x7f57081fd3e0, 0xc82013c358)
	/usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/docker/docker/volume/store.(*VolumeStore).Dereference(0xc8207d42c0, 0x7f57081fcfc8, 0xc82097e380, 0xc820a15e40, 0x40)
	/go/src/github.com/docker/docker/volume/store/store.go:304 +0x62b
github.com/docker/docker/daemon.(*Daemon).registerMountPoints(0xc82015a900, 0xc820764000, 0xc8208de600, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/volumes.go:148 +0xf26
github.com/docker/docker/daemon.(*Daemon).setHostConfig(0xc82015a900, 0xc820764000, 0xc8208de600, 0x0, 0x0)
...
```

The above says that setting HostConfig at container start is deprecated, but that does not mean it should stop working.

The above is reproducible with (since) Docker v1.10.0, v1.10.1, v1.11.0.

Please note: this is not a contrived example. A workaround had to be implemented in a real world project around this situation: https://github.com/eris-ltd/eris-cli

This function https://github.com/docker/docker/blob/master/volume/store/store.go#L298-L315
which is likely to blame works fine as long as the number of `ref` occurrences doesn't exceed 1 in the `refs` slice which was true in my case: the first and the last element was the same volume ref. Please see this snippet: https://play.golang.org/p/mjvkCrU52t

`docker -v`: Docker version 1.10.0, build 590d5108

`docker info`:
```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 9
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 144
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-40-generic
Operating System: Ubuntu 14.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.861 GiB
Name: talkback
ID: O26B:CZET:GEEC:QA6I:7V3N:2HVS:CIVA:JIHU:KAH4:3RB3:FR4Q:MWZB
Debug mode (server): true
 File Descriptors: 11
 Goroutines: 24
 System Time: 2016-02-16T20:07:05.574365791-05:00
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /var/lib/docker
```
`uname -a`: `Linux talkback 3.13.0-40-generic #69-Ubuntu SMP Thu Nov 13 17:53:56 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

### PR DESCRIPTION
**Pull request by cpuguy83**
Fixes #20378

### CODE REVIEW

**Comment by thaJeztah** [comment]
@tiborvass @cpuguy83 given that we have two "panic" issues, should we have a 1.10.2 branch, and open these fixes on that branch?

File: volume/store/store.go [hunk 1]
```diff
@@ -302,16 +302,14 @@ func (s *VolumeStore) Dereference(v volume.Volume, ref string) {
 
 	s.globalLock.Lock()
 	defer s.globalLock.Unlock()
-	refs, exists := s.refs[v.Name()]
-	if !exists {
-		return
-	}
```
Comment (coolljt0725) [inline volume/store/store.go]: I think this check is still need. Or else if `s.refs[v.Name()]` does not exists, the `s.refs[v.Name()] = refs` will make it exists, this may cause issue if some other operation relay on `refs, exists := s.refs[v.Name()]`

Comment (cpuguy83) [inline volume/store/store.go]: We aren't tracking existence anywhere as it's not what matters. What matters here is length (ie, 0 length it has no references, > 0 length it has references).

**Comment by thaJeztah** [comment]
https://jenkins.dockerproject.org/job/Docker-PRs-WoW-TP4/1137/console
```
fatal: unable to access 'https://github.com/docker/docker.git/': Failed to connect to github.com port 443: Timed out
21:48:37 + ec=128
21:48:37 + set +x
```

File: volume/store/store.go (hunk 1 above)
Comment (coolljt0725) [inline volume/store/store.go]: make sense if we aren't tracking existence anywhere :)

**Comment by thaJeztah** [comment]
@coolljt0725 does this LGTY?

**Comment by coolljt0725** [comment]
@thaJeztah  Yes, LGTM

**Comment by calavera** [comment]
LGTM
