### PR TITLE
Show right tag for container in ps

### LINKED ISSUE #10599: docker ps / list containers rest call reports incorrect tag name
the output of `docker ps` calls (and the corresponding `list containers` rest call) does not correctly report the tag of the image the container was started with when there are multiple tags. 

for example, here is a listing of tomcat images
```
tomcat                         8-jre8              d9235bd6a401        9 days ago          316.7 MB
tomcat                         8.0-jre8            d9235bd6a401        9 days ago          316.7 MB
tomcat                         8.0.18-jre8         d9235bd6a401        9 days ago          316.7 MB
tomcat                         jre8                d9235bd6a401        9 days ago          316.7 MB
```
if i start a container using `tomcat:jre8`, that is not the tag that is reported back to me via those two calls:
```
docker run -d tomcat:jre8
29b5b8286a6836b524caddc39789f2181e1391d9347e37b25531159d167d3202
docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
29b5b8286a68        tomcat:8-jre8       "catalina.sh run"   1 seconds ago       Up 1 seconds        8080/tcp            drunk_meitner       
```
output from the rest call (snipped for brevity) 
```json
[{
    "Command": "catalina.sh run",
    "Created": 1423170738,
    "Id": "29b5b8286a6836b524caddc39789f2181e1391d9347e37b25531159d167d3202",
    "Image": "tomcat:8-jre8",
    ...
}]
```
`docker inspect` however correctly shows the tag name (snipped for brevity) :

```json
"Config": {
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": [
            "catalina.sh",
            "run"
        ],
        "CpuShares": 0,
        "Cpuset": "",
        "Domainname": "",
        "Entrypoint": null,
        "Env": [
            "PATH=/usr/local/tomcat/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "JAVA_VERSION=8u40~b09",
            "JAVA_DEBIAN_VERSION=8u40~b09-1",
            "CA_CERTIFICATES_JAVA_VERSION=20140324",
            "CATALINA_HOME=/usr/local/tomcat",
            "TOMCAT_MAJOR=8",
            "TOMCAT_VERSION=8.0.18",
            "TOMCAT_TGZ_URL=https://www.apache.org/dist/tomcat/tomcat-8/v8.0.18/bin/apache-tomcat-8.0.18.tar.gz"
        ],
        "ExposedPorts": {
            "8080/tcp": {}
        },
        "Hostname": "29b5b8286a68",
        "Image": "tomcat:jre8",
        "MacAddress": "",
        "Memory": 0,
        "MemorySwap": 0,
        "NetworkDisabled": false,
        "OnBuild": null,
        "OpenStdin": false,
        "PortSpecs": null,
        "StdinOnce": false,
        "Tty": false,
        "User": "",
        "Volumes": null,
        "WorkingDir": "/usr/local/tomcat"
    }
```
this causes tooling that relies on finding container(s) by image name to fail.

### PR DESCRIPTION
**Pull request by LK4D4**
Fixes #10599

### CODE REVIEW

File: integration-cli/docker_cli_ps_test.go [hunk 1]
```diff
@@ -490,3 +490,51 @@ func TestPsListContainersFilterExited(t *testing.T) {
...
+				t.Fatalf("Expected %s tag for id %s, got %s", "busybox", id1, f[1])
+			}
+		case id2:
+			if f[1] != tag {
+				t.Fatalf("Expected %s tag for id %s, got %s", tag, id1, f[1])
+			}
+		default:
+			t.Fatalf("Unexpected id %s, expected %s and %s", f[0], id1, id2)
+		}
+	}
```
Comment (jfrazelle) [inline integration-cli/docker_cli_ps_test.go]: missing logDone ;) other than that LGTM

**Comment by LK4D4** [comment]
@jfrazelle Fixed, thanks!

**Comment by tiborvass** [comment]
LGTM
