### PR TITLE
Fixes Issue # 23418: Race condition between device deferred removal and resume device.

### LINKED ISSUE #23418: devicemapper issue: Race condition between device deferred removal and resume device.
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.4
 Git commit:   6ac8599
 Built:        Thu Jun  9 13:52:39 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.4
 Git commit:   6ac8599
 Built:        Thu Jun  9 13:52:39 2016
 OS/Arch:      linux/amd64
```
**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.12.0-dev
Storage Driver: devicemapper
 Pool Name: docker-8:19-16121923-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 1.074 GB
 Backing Filesystem: xfs
 Data file: /dev/loop1
 Metadata file: /dev/loop2
 Data Space Used: 709 MB
 Data Space Total: 107.4 GB
 Data Space Available: 106.7 GB
 Metadata Space Used: 913.4 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.109 (2015-09-22)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.9-300.fc23.x86_64
Operating System: Fedora 23 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.72 GiB
Name: dhcp-10-19-62-127.boston.devel.redhat.com
ID: M4W2:KN7L:WVHC:KGXZ:ZNAN:CJJJ:5PWS:V7VV:GPHO:65Y3:4UEP:MCUX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: shm32
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
OpenShift Enterprise (OSE)

**Steps to reproduce the issue:**
Let's consider an example scenario that involves deferred removal
1. A new base image gets created (e.g. 'docker load -i'). The base device is activated and mounted at some point in time during image creation.
2. While image creation is in progress, a privileged container is started
  from another image and the host's mount name space is shared with this
  container ('docker run --privileged -v /:/host').
3. Image creation completes and the base device gets unmounted. However,
  as the privileged container still holds a reference on the base image
  mount point, the base device cannot be removed right away. So it gets
  flagged for deferred removal.
4. Next, the privileged container terminates and thus its reference to the
  base image mount point gets released. The base device (which is flagged
  for deferred removal) may now be cleaned up by the device-mapper. This
  opens up an opportunity for a race between a 'kworker' thread (executing
  the do_deferred_remove() function) and the Docker daemon (executing the
  CreateSnapDevice() function).

**Describe the results you received:**
http://pastebin.com/mAp32Zgk

**Describe the results you expected:**
I should be able to successfully create and run a docker container.

**Additional information you deem important (e.g. issue happens only occasionally):**
RHEL 7.2
Openshift Environment
Kernel:  3.10.0-327.10.1.el7.x86_64
lvm2: 2.02.130-5.el7_2.1.x86_64
docker: 1.8.2-10.el7.x86_64
devicemapper*: 1.02.107-5.el7_2.1.x86_64

### PR DESCRIPTION
**Pull request by shishir-a412ed**
Fixes #23418 

Signed-off-by: Shishir Mahajan shishir.mahajan@redhat.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @LK4D4 @cpuguy83 @rhvgoyal ptal

File: daemon/graphdriver/devmapper/deviceset.go [hunk 1]
```diff
@@ -841,11 +841,42 @@ func (devices *DeviceSet) createRegisterDevice(hash string) (*devInfo, error) {
...
 
-func (devices *DeviceSet) createRegisterSnapDevice(hash string, baseInfo *devInfo, size uint64) error {
+func (devices *DeviceSet) takeSnapshot(hash string, baseInfo *devInfo, size uint64) error {
+	var doSuspend bool
+
 	if err := devices.poolHasFreeSpace(); err != nil {
 		return err
 	}
 
+	CancelledRemoval, err := devices.cancelDeferredRemoval(baseInfo)
```
Comment (cpuguy83) [inline daemon/graphdriver/devmapper/deviceset.go]: lower-cased please

File: daemon/graphdriver/devmapper/deviceset.go [hunk 2]
```diff
@@ -877,6 +909,7 @@ func (devices *DeviceSet) createRegisterSnapDevice(hash string, baseInfo *devInf
 			devices.markDeviceIDFree(deviceID)
 			return err
 		}
+
```
Comment (rhvgoyal) [inline daemon/graphdriver/devmapper/deviceset.go]: No need to introduce extra blank lines.

File: pkg/devicemapper/devmapper.go [hunk 3]
```diff
@@ -750,51 +750,47 @@ func activateDevice(poolName string, name string, deviceID int, size uint64, ext
...
+	doSuspend := devinfo != nil && devinfo.Exists != 0
+
+	if doSuspend {
+		if err := SuspendDevice(baseName); err != nil {
+			return err
+		}
+	}
 
+	if err := CreateSnapDeviceRaw(poolName, deviceID, baseName, baseDeviceID); err != nil {
+		ResumeDevice(baseName)
```
Comment (rhvgoyal) [inline pkg/devicemapper/devmapper.go]: Device should be resumed only if doSuspend is true.

File: daemon/graphdriver/devmapper/deviceset.go (hunk 1 above)
Comment (shishir-a412ed) [inline daemon/graphdriver/devmapper/deviceset.go]: Fixed.

File: daemon/graphdriver/devmapper/deviceset.go (hunk 2 above)
Comment (shishir-a412ed) [inline daemon/graphdriver/devmapper/deviceset.go]: Fixed.

File: pkg/devicemapper/devmapper.go (hunk 3 above)
Comment (shishir-a412ed) [inline pkg/devicemapper/devmapper.go]: Fixed.

File: daemon/graphdriver/devmapper/deviceset.go [hunk 4]
```diff
@@ -858,7 +889,8 @@ func (devices *DeviceSet) createRegisterSnapDevice(hash string, baseInfo *devInf
 	}
 
 	for {
-		if err := devicemapper.CreateSnapDevice(devices.getPoolDevName(), deviceID, baseInfo.Name(), baseInfo.DeviceID); err != nil {
+
```
Comment (rhvgoyal) [inline daemon/graphdriver/devmapper/deviceset.go]: Don't add new blank line after for starting block

Comment (shishir-a412ed) [inline daemon/graphdriver/devmapper/deviceset.go]: Fixed.

**Comment by rhvgoyal** [comment]
LGTM

File: pkg/devicemapper/devmapper.go [hunk 5]
```diff
@@ -750,51 +750,49 @@ func activateDevice(poolName string, name string, deviceID int, size uint64, ext
...
 
+	if doSuspend {
+		if err := SuspendDevice(baseName); err != nil {
+			return err
+		}
+	}
+
+	if err := CreateSnapDeviceRaw(poolName, deviceID, baseName, baseDeviceID); err != nil {
+		if doSuspend {
+			ResumeDevice(baseName)
```
Comment (runcom) [inline pkg/devicemapper/devmapper.go]: check err?

File: pkg/devicemapper/devmapper.go [hunk 6]
```diff
@@ -750,51 +750,49 @@ func activateDevice(poolName string, name string, deviceID int, size uint64, ext
...
+	return nil
+}
+
+// CreateSnapDevice creates a snapshot based on the device identified by the baseName and baseDeviceId,
+func CreateSnapDevice(poolName string, deviceID int, baseName string, baseDeviceID int) error {
+	devinfo, _ := GetInfo(baseName)
+	doSuspend := devinfo != nil && devinfo.Exists != 0
 
+	if doSuspend {
+		if err := SuspendDevice(baseName); err != nil {
```
Comment (runcom) [inline pkg/devicemapper/devmapper.go]: check err?

**Comment by runcom** [comment]
```
19:56:14 ----------------------------------------------------------------------
19:56:14 FAIL: docker_api_swarm_test.go:556: DockerSwarmSuite.TestApiSwarmLeaveOnPendingJoin
19:56:14 
19:56:14 [d40976264] waiting for daemon to start
19:56:14 [d40976264] daemon started
19:56:14 [d64227023] waiting for daemon to start
19:56:14 [d64227023] exiting daemon
19:56:14 docker_api_swarm_test.go:558:
19:56:14     d2 := s.AddDaemon(c, false, false)
19:56:14 check_test.go:212:
19:56:14     c.Assert(err, check.IsNil)
19:56:14 ... value *errors.errorString = &errors.errorString{s:"[d64227023] Daemon exited during startup"} ("[d64227023] Daemon exited during startup")
19:56:14 
19:56:14 [d40976264] exiting daemon
```
could this be related? (failing in experimental)

File: pkg/devicemapper/devmapper.go (hunk 5 above)
Comment (shishir-a412ed) [inline pkg/devicemapper/devmapper.go]: So me and @rhvgoyal discussed this. If you check the original code, e.g https://github.com/docker/docker/blob/master/pkg/devicemapper/devmapper.go#L781

There was no check for error in `ResumeDevice(baseName)`. One reason can be, if I check for error in `ResumeDevice(baseName)` and if `err != nil` and I return the error. the error from `CreateSnapDeviceRaw` will be ignored and not returned (Unless we concat both the errors and return them as one). So we decided to keep it as original code.

Shishir

File: pkg/devicemapper/devmapper.go (hunk 6 above)
Comment (shishir-a412ed) [inline pkg/devicemapper/devmapper.go]: Same as above.

**Comment by shishir-a412ed** [comment]
@thaJeztah Any updates on this one ?

**Comment by thaJeztah** [comment]
ping @cpuguy83 @runcom PTAL

File: daemon/graphdriver/devmapper/deviceset.go [hunk 7]
```diff
@@ -2126,9 +2157,11 @@ func (devices *DeviceSet) removeDevice(devname string) error {
 	return err
 }
 
-func (devices *DeviceSet) cancelDeferredRemoval(info *devInfo) error {
+func (devices *DeviceSet) cancelDeferredRemoval(info *devInfo) (bool, error) {
```
Comment (cpuguy83) [inline daemon/graphdriver/devmapper/deviceset.go]: It seems like we don't really need this bool return.
If there is an error it wasn't cancelled, if there is no error it was cancelled.

File: pkg/devicemapper/devmapper.go [hunk 8]
```diff
@@ -750,51 +750,49 @@ func activateDevice(poolName string, name string, deviceID int, size uint64, ext
...
+			return err
+		}
```
Comment (cpuguy83) [inline pkg/devicemapper/devmapper.go]: `defer ResumeDevice(baseName)` and remove the all the `if doSuspend` blocks below?

File: pkg/devicemapper/devmapper.go (hunk 5 above)
Comment (cpuguy83) [inline pkg/devicemapper/devmapper.go]: Might be good to log these errors, or probably even more something like:
```go
if err2 := ResumeDevice(baseName); err2 != nil {
  if err == nil {
    err = err2
  }
  return err
}
```

File: daemon/graphdriver/devmapper/deviceset.go (hunk 7 above)
Comment (rhvgoyal) [inline daemon/graphdriver/devmapper/deviceset.go]: There are few conditions where err is nil still deferred remove was not cancelled.

- If device was not scheduled for deferred removal.
- If device is not active to being with.

        if devinfo != nil && devinfo.DeferredRemove == 0 {
                return nil
        }

Comment (cpuguy83) [inline daemon/graphdriver/devmapper/deviceset.go]: Shouldn't these be error cases?
We are saying "go cancel this thing" and then essentially returning back "ok nothing is wrong".
We can always check the error type if need be.

I think it may be a little more clear handling this logic in the caller... this is similar to how we tend to ignore `IsNotExist` type errors when we are removing the file anyway.

Comment (cpuguy83) [inline daemon/graphdriver/devmapper/deviceset.go]: And I realize this is probably totally subjective, but LMK what you think.

Not a big fan of adding this bool return.

File: pkg/devicemapper/devmapper.go (hunk 5 above)
Comment (shishir-a412ed) [inline pkg/devicemapper/devmapper.go]: We will only hit `ResumeDevice(baseName)` here if `err != nil`. err will not be equal to nil (err==nil) in this case.
You mean something like:
```
        if err := CreateSnapDeviceRaw(poolName, deviceID, baseName, baseDeviceID); err != nil {
                if doSuspend {
                        if err2 := ResumeDevice(baseName); err2 != nil{
                                return fmt.Errorf("ResumeDevice Error: (%v); CreateSnapDeviceRaw Error (%v)", err2, err)
                        }
                }
                return err
        }
```

File: daemon/graphdriver/devmapper/deviceset.go (hunk 7 above)
Comment (shishir-a412ed) [inline daemon/graphdriver/devmapper/deviceset.go]: I understand what you are saying, but devicemapper (cancelDeferredRemoval) coming back with `err==nil` doesn't necessarily means that the deferred removal was cancelled.
It means "Nothing is wrong" but we still need additional information to know if the deferred removal was actually cancelled, and do we need to reschedule it?
 
`err == nil` can mean
a) deferred removal option is not even supported. FALSE
b) the device exists but it is not marked for deferred removal. FALSE
c) the deferred removal was scheduled on the device, and now it is cancelled successfully. TRUE
d) The device was already gone, by the time we reached to cancel the deferred removal. So now it's not needed anymore. FALSE.

Only in case (c) we really need to reschedule the deferred removal, since it was actually cancelled.
I know what you are saying with `os.IsNotExist(err)` however that is a type of error and can be checked. We don't have an error here, and we need more information to make an informed decision.
Unless, you rewrite the entire functionality on how we implement `cancelDeferredRemoval`, I am afraid we would have to go with a boolean variable.

File: pkg/devicemapper/devmapper.go (hunk 8 above)
Comment (shishir-a412ed) [inline pkg/devicemapper/devmapper.go]: you wan't something like this:
```
func CreateSnapDevice(poolName string, deviceID int, baseName string, baseDeviceID int) error {
        devinfo, _ := GetInfo(baseName)
        doSuspend := devinfo != nil && devinfo.Exists != 0
        if doSuspend {
                if err := SuspendDevice(baseName); err != nil {
                        return err
                }
                defer ResumeDevice(baseName)
        }
       return CreateSnapDeviceRaw(poolName, deviceID, baseName, baseDeviceID)
}
```
IIRC the reason why we didn't do it like this was, the original code was not using `defer`.
https://github.com/docker/docker/blob/master/pkg/devicemapper/devmapper.go#L800-L804

and since this code is very tricky (it handles multiple conditions) we didn't wanted to change and introduce new errors. Also `defer` is very convenient at ignoring errors. if there is an error in `ResumeDevice(baseName)` it will ignore it, the current style of code still handles that.

Let me know if you feel strongly about it, and I will change it.

File: daemon/graphdriver/devmapper/deviceset.go (hunk 7 above)
Comment (rhvgoyal) [inline daemon/graphdriver/devmapper/deviceset.go]: If you don't like bool, may be we can provide another helper function which only does the actual removal. Rest of the conditions can be checked by caller.

So say provide another funciton __cancelDeferredRmoval(info devInfo), which does not do various check and just calls devicemapper.CancelDeferredRemove(). Now this function will return success if deferred removal as actually cancelled or error.

Caller can check for rest of the conditions and call this only if.
- Deferred removal is enabled.
- There is an active device.
- Device is in deferred remove state.

That way we will get rid of bool return parameter.

Comment (rhvgoyal) [inline daemon/graphdriver/devmapper/deviceset.go]: And this function will probably return ErrEnxio while it is retrying in busy loop.

Comment (rhvgoyal) [inline daemon/graphdriver/devmapper/deviceset.go]: Basically we need two functions.

- One which just ensures that when the function finishes, device should not be in deferred remove state. Other states like device not being there any more etc are fine. This is what current function is implementing.

- Another function which returns success only if deferred removal was cancelled otherwise appropriate error message. 

Shishir, lets implement this second variant of function and any other required bits let open code in the caller. And that should take care of concern raised by @cpuguy83

Comment (shishir-a412ed) [inline daemon/graphdriver/devmapper/deviceset.go]: Fixed.

File: pkg/devicemapper/devmapper.go (hunk 5 above)
Comment (shishir-a412ed) [inline pkg/devicemapper/devmapper.go]: Fixed.

File: pkg/devicemapper/devmapper.go (hunk 8 above)
Comment (shishir-a412ed) [inline pkg/devicemapper/devmapper.go]: Me and @rhvgoyal discussed this, and we feel it's better not to change the original code (and introduce new errors) for the above mentioned comment. 
https://github.com/docker/docker/pull/23497#discussion_r69142670

Since this is more of a code cleanup activity, if you really want this. I will open a separate PR for this later.

**Comment by shishir-a412ed** [comment]
@rhvgoyal @cpuguy83 @runcom @thaJeztah PTAL.

File: daemon/graphdriver/devmapper/deviceset.go [hunk 9]
```diff
@@ -841,11 +841,59 @@ func (devices *DeviceSet) createRegisterDevice(hash string) (*devInfo, error) {
...
+
 	if err := devices.poolHasFreeSpace(); err != nil {
 		return err
 	}
 
+	if !devices.deferredRemove {
+		deferredRemove = false
+	}
+
+	devinfo, err := devicemapper.GetInfoWithDeferred(baseInfo.Name())
```
Comment (cpuguy83) [inline daemon/graphdriver/devmapper/deviceset.go]: We're grabbing this error but not doing anything with it.

File: daemon/graphdriver/devmapper/deviceset.go [hunk 10]
```diff
@@ -2167,6 +2215,30 @@ func (devices *DeviceSet) cancelDeferredRemoval(info *devInfo) error {
...
+	var err error
+
+	// Cancel deferred remove
+	for i := 0; i < 100; i++ {
+		err = devicemapper.CancelDeferredRemove(info.Name())
+		if err != nil {
+			if err == devicemapper.ErrBusy {
+				// If we see EBUSY it may be a transient error,
+				// sleep a bit a retry a few times.
+				devices.Unlock()
```
Comment (cpuguy83) [inline daemon/graphdriver/devmapper/deviceset.go]: This looks pretty dangerous and opening ourselves up for races.

Comment (shishir-a412ed) [inline daemon/graphdriver/devmapper/deviceset.go]: Can you elaborate a little bit, what do you mean ?

Comment (cpuguy83) [inline daemon/graphdriver/devmapper/deviceset.go]: If were unlocking the devices lock won't other threads be able to do other unexpected things with this `*devInfo`?

Comment (shishir-a412ed) [inline daemon/graphdriver/devmapper/deviceset.go]: This is how it was originally. I didn't change this code.
https://github.com/docker/docker/blob/master/daemon/graphdriver/devmapper/deviceset.go#L2163-l2165

Let me check with @rhvgoyal what was the rationale behind this.

Comment (rhvgoyal) [inline daemon/graphdriver/devmapper/deviceset.go]: @cpuguy83 We have two locks. There is one global lock which is devices.Lock and then there is per device lock (devInfo.lock.Lock()). We are releasing only global lock but continuing to hold per device lock. So any other task can work on other device but not on this device. This is to make sure if we are waiting on a device, operations on other devices can continue in parallel. We are doing this all across the devmapper code and this is nothing new and should be safe.

File: daemon/graphdriver/devmapper/deviceset.go (hunk 9 above)
Comment (rhvgoyal) [inline daemon/graphdriver/devmapper/deviceset.go]: I guess handling err is a good idea.

Comment (shishir-a412ed) [inline daemon/graphdriver/devmapper/deviceset.go]: Fixed.

**Comment by shishir-a412ed** [comment]
@cpuguy83 @rhvgoyal PTAL.

File: daemon/graphdriver/devmapper/deviceset.go [hunk 11]
```diff
@@ -841,11 +841,62 @@ func (devices *DeviceSet) createRegisterDevice(hash string) (*devInfo, error) {
...
+	}
+
+	// if deferred removal was cancelled, we can safely assume the device is active.
+	if deferredRemove {
+		doSuspend = true
+		defer devices.deactivateDevice(baseInfo)
+	} else {
+		devinfo, _ := devicemapper.GetInfo(baseInfo.Name())
+		doSuspend = devinfo != nil && devinfo.Exists != 0
+	}
```
Comment (rhvgoyal) [inline daemon/graphdriver/devmapper/deviceset.go]: We don't have to do GetInfo() again. We already did it once and that will give information if device exists or not.

File: daemon/graphdriver/devmapper/deviceset.go [hunk 12]
```diff
@@ -841,11 +841,62 @@ func (devices *DeviceSet) createRegisterDevice(hash string) (*devInfo, error) {
...
+	if err != nil {
+		return err
+	}
+
+	if devinfo != nil && devinfo.DeferredRemove == 0 {
+		deferredRemove = false
+	}
+
+	if deferredRemove {
+		err = devices._cancelDeferredRemoval(baseInfo)
```
Comment (rhvgoyal) [inline daemon/graphdriver/devmapper/deviceset.go]: How about if we name this new function as cancelDeferredRemoval() and rename the original one to "cancelDeferredRemovalIfNeeded()"

File: daemon/graphdriver/devmapper/deviceset.go (hunk 9 above)
Comment (rhvgoyal) [inline daemon/graphdriver/devmapper/deviceset.go]: GetInfoWithDeferred() works only if deferred removal support is there in libdm. So I think we will have to do following.

if devices.deferredRemove {
     devicemapper.GetInfoWithDeferred()
} else {
    devicemapper.GetInfo();
}

File: daemon/graphdriver/devmapper/deviceset.go (hunk 11 above)
Comment (shishir-a412ed) [inline daemon/graphdriver/devmapper/deviceset.go]: Fixed.

File: daemon/graphdriver/devmapper/deviceset.go (hunk 12 above)
Comment (shishir-a412ed) [inline daemon/graphdriver/devmapper/deviceset.go]: Fixed.

File: daemon/graphdriver/devmapper/deviceset.go (hunk 9 above)
Comment (shishir-a412ed) [inline daemon/graphdriver/devmapper/deviceset.go]: Fixed.

File: daemon/graphdriver/devmapper/deviceset.go [hunk 13]
```diff
@@ -841,11 +841,69 @@ func (devices *DeviceSet) createRegisterDevice(hash string) (*devInfo, error) {
...
+		deferredRemove = false
+	}
+
+	if deferredRemove {
+		err = devices.cancelDeferredRemoval(baseInfo)
+		if err != nil {
+			if err != devicemapper.ErrEnxio {
+				return err
+			}
+			// Error is ErrEnxio. Device is probably already gone. Return success.
```
Comment (rhvgoyal) [inline daemon/graphdriver/devmapper/deviceset.go]: This comment is stale now. We are not returning success. Instead say that device is already gone, continue.

File: daemon/graphdriver/devmapper/deviceset.go [hunk 14]
```diff
@@ -841,11 +841,69 @@ func (devices *DeviceSet) createRegisterDevice(hash string) (*devInfo, error) {
...
 }
 
-func (devices *DeviceSet) createRegisterSnapDevice(hash string, baseInfo *devInfo, size uint64) error {
-	if err := devices.poolHasFreeSpace(); err != nil {
+func (devices *DeviceSet) takeSnapshot(hash string, baseInfo *devInfo, size uint64) error {
+	var (
+		doSuspend      bool
+		devinfo        *devicemapper.Info
+		deferredRemove = true
+		err            error
```
Comment (rhvgoyal) [inline daemon/graphdriver/devmapper/deviceset.go]: Why to declar "err".  err := statement should do?

File: daemon/graphdriver/devmapper/deviceset.go [hunk 15]
```diff
@@ -841,11 +841,69 @@ func (devices *DeviceSet) createRegisterDevice(hash string) (*devInfo, error) {
...
+		devinfo, err = devicemapper.GetInfo(baseInfo.Name())
+		if err != nil {
+			return err
+		}
+	}
+
+	if devinfo != nil && devinfo.DeferredRemove == 0 {
+		deferredRemove = false
+	}
+
```
Comment (rhvgoyal) [inline daemon/graphdriver/devmapper/deviceset.go]: I think this check can go inside first block if if condition. Right after GetInfoWithDeferred().

File: daemon/graphdriver/devmapper/deviceset.go [hunk 16]
```diff
@@ -841,11 +841,69 @@ func (devices *DeviceSet) createRegisterDevice(hash string) (*devInfo, error) {
...
+			if err != devicemapper.ErrEnxio {
+				return err
+			}
+			// Error is ErrEnxio. Device is probably already gone. Return success.
+			deferredRemove = false
+		}
+	}
+
+	// if deferred removal was cancelled, we can safely assume the device is active.
+	if deferredRemove {
```
Comment (rhvgoyal) [inline daemon/graphdriver/devmapper/deviceset.go]: Given we have already done GetInfo(), I think we can simplify it and not try to infer it from deferred remove. 

doSuspend := devinfo != nil && devinfo.Exists != 0

File: daemon/graphdriver/devmapper/deviceset.go [hunk 17]
```diff
@@ -841,11 +841,69 @@ func (devices *DeviceSet) createRegisterDevice(hash string) (*devInfo, error) {
 	return info, nil
 }
 
-func (devices *DeviceSet) createRegisterSnapDevice(hash string, baseInfo *devInfo, size uint64) error {
-	if err := devices.poolHasFreeSpace(); err != nil {
+func (devices *DeviceSet) takeSnapshot(hash string, baseInfo *devInfo, size uint64) error {
+	var (
+		doSuspend      bool
```
Comment (rhvgoyal) [inline daemon/graphdriver/devmapper/deviceset.go]: I think we don't have to declare it?

File: pkg/devicemapper/devmapper.go [hunk 18]
```diff
@@ -750,51 +750,51 @@ func activateDevice(poolName string, name string, deviceID int, size uint64, ext
...
-	devinfo, _ := GetInfo(baseName)
-	doSuspend := devinfo != nil && devinfo.Exists != 0
-
-	if doSuspend {
-		if err := SuspendDevice(baseName); err != nil {
-			return err
-		}
-	}
-
+// CreateSnapDeviceRaw creates a snapshot device. Caller is assumed to resume and suspend the device.
```
Comment (rhvgoyal) [inline pkg/devicemapper/devmapper.go]: Lets make this comment little better. "Caller needs to suspend and resume the origin device if it is active".

File: pkg/devicemapper/devmapper.go [hunk 19]
```diff
@@ -750,51 +750,51 @@ func activateDevice(poolName string, name string, deviceID int, size uint64, ext
...
+func CreateSnapDeviceRaw(poolName string, deviceID int, baseName string, baseDeviceID int) error {
```
Comment (rhvgoyal) [inline pkg/devicemapper/devmapper.go]: baseName nobody seems to be using? If yes, then let us remove it.

File: pkg/devicemapper/devmapper.go [hunk 20]
```diff
@@ -750,51 +750,51 @@ func activateDevice(poolName string, name string, deviceID int, size uint64, ext
...
+		if err := SuspendDevice(baseName); err != nil {
+			return err
+		}
+	}
+
+	if err := CreateSnapDeviceRaw(poolName, deviceID, baseName, baseDeviceID); err != nil {
+		if doSuspend {
+			if err2 := ResumeDevice(baseName); err2 != nil {
+				return fmt.Errorf("ResumeDevice Error: (%v); CreateSnapDeviceRaw Error (%v)", err2, err)
+			}
```
Comment (rhvgoyal) [inline pkg/devicemapper/devmapper.go]: Shouldn't sequence of error be reversed. Create snapshot error happened first and that should come first and resume device error message should come after that. That way it is clear that first create device error happened and then resume device error happened?

Comment (rhvgoyal) [inline pkg/devicemapper/devmapper.go]: May be ignore that. I think in rest of the code, caller gets an error and it suffixes that error to its own error message.

Comment (rhvgoyal) [inline pkg/devicemapper/devmapper.go]: I personally feel that this code has been working like this for a long time and prefer not to change it now. It should be done as a separate PR to improve error handling in CreateSnapDevice().  But I will leave it to others.

File: daemon/graphdriver/devmapper/deviceset.go (hunk 17 above)
Comment (shishir-a412ed) [inline daemon/graphdriver/devmapper/deviceset.go]: We need to declare this (doSuspend), as the first time it is used, It is scoped inside an if condition.

File: daemon/graphdriver/devmapper/deviceset.go (hunk 14 above)
Comment (shishir-a412ed) [inline daemon/graphdriver/devmapper/deviceset.go]: Yes it would work, but that would scope `devinfo` within the if condition. We need to use `devinfo` later outside the if condition. So we need to declare both the variables {error, devinfo}. 

Golang has scoped variables, and it's painful :)

Shishir

File: daemon/graphdriver/devmapper/deviceset.go (hunk 13 above)
Comment (shishir-a412ed) [inline daemon/graphdriver/devmapper/deviceset.go]: Fixed.

File: daemon/graphdriver/devmapper/deviceset.go (hunk 15 above)
Comment (shishir-a412ed) [inline daemon/graphdriver/devmapper/deviceset.go]: Fixed.

File: pkg/devicemapper/devmapper.go (hunk 18 above)
Comment (shishir-a412ed) [inline pkg/devicemapper/devmapper.go]: Fixed.

File: pkg/devicemapper/devmapper.go (hunk 19 above)
Comment (shishir-a412ed) [inline pkg/devicemapper/devmapper.go]: Fixed.

File: pkg/devicemapper/devmapper.go (hunk 20 above)
Comment (shishir-a412ed) [inline pkg/devicemapper/devmapper.go]: Fixed.

File: daemon/graphdriver/devmapper/deviceset.go (hunk 16 above)
Comment (shishir-a412ed) [inline daemon/graphdriver/devmapper/deviceset.go]: Fixed.

File: pkg/devicemapper/devmapper.go [hunk 21]
```diff
@@ -750,51 +750,51 @@ func activateDevice(poolName string, name string, deviceID int, size uint64, ext
...
+	if doSuspend {
+		if err := SuspendDevice(baseName); err != nil {
+			return err
+		}
+	}
+
+	if err := CreateSnapDeviceRaw(poolName, deviceID, baseDeviceID); err != nil {
+		if doSuspend {
+			if err2 := ResumeDevice(baseName); err2 != nil {
+				return fmt.Errorf("CreateSnapDeviceRaw Error (%v); ResumeDevice Error: (%v)", err, err2)
```
Comment (rhvgoyal) [inline pkg/devicemapper/devmapper.go]: I think you want to put a colon (:) and not semi colon (;) between two error strings.

CreateSnapDeviceRaw Error(%v) : ResumeDevice Error: (%v)

Comment (shishir-a412ed) [inline pkg/devicemapper/devmapper.go]: Fixed.

**Comment by rhvgoyal** [comment]
LGTM. Thanks Shishir.

**Comment by thaJeztah** [comment]
ping @cpuguy83 PTAL

File: daemon/graphdriver/devmapper/deviceset.go [hunk 22]
```diff
@@ -2128,13 +2173,13 @@ func (devices *DeviceSet) removeDevice(devname string) error {
...
-func (devices *DeviceSet) cancelDeferredRemoval(info *devInfo) error {
+func (devices *DeviceSet) cancelDeferredRemovalIfNeeded(info *devInfo) error {
 	if !devices.deferredRemove {
 		return nil
 	}
 
-	logrus.Debugf("devmapper: cancelDeferredRemoval START(%s)", info.Name())
-	defer logrus.Debugf("devmapper: cancelDeferredRemoval END(%s)", info.Name())
+	logrus.Debugf("devmapper: cancelDeferredRemovalIfNeeded START(%s)", info.Name())
+	defer logrus.Debugf("devmapper: cancelDeferredRemovalIfNeeded END(%s)", info.Name())
```
Comment (cpuguy83) [inline daemon/graphdriver/devmapper/deviceset.go]: I would assume we'd be able to call `cancelDeferredRemoval` from here, though the loop is a little different. Is that intended? Should they be the same?

Comment (rhvgoyal) [inline daemon/graphdriver/devmapper/deviceset.go]: Agreed. We should be able to reuse cancelDeferredRemoval() in cancelDeferredRemovalIfNeeded().

Although not exactly here, we should be calling after.

        if devinfo != nil && devinfo.DeferredRemove == 0 {
                return nil
        }

Also if cancelDeferredRemoval() returns, ErrEnxio, then that means device is gone and this function should still return success as deferred removal is not needed any more.

Comment (shishir-a412ed) [inline daemon/graphdriver/devmapper/deviceset.go]: Or we can change the condition to `if devinfo != nil && devinfo.DeferredRemove != 0` and call `cancelDeferredRemoval()` inside the condition. The same way we did it inside `takeSnapshot()`. @rhvgoyal WDYT ?

https://github.com/shishir-a412ed/docker/blob/dm_task_run_failed/daemon/graphdriver/devmapper/deviceset.go#L859-l865

Shishir

Comment (rhvgoyal) [inline daemon/graphdriver/devmapper/deviceset.go]: I think that would not help. That will push cancelDeferredRemoval() call inside if block and there is really no need to to that. Code will look cleaner if we just first check all the conditions and return if deferred removal is not needed at all.

Comment (shishir-a412ed) [inline daemon/graphdriver/devmapper/deviceset.go]: Fixed.

**Comment by shishir-a412ed** [comment]
@rhvgoyal @cpuguy83 PTAL.

File: daemon/graphdriver/devmapper/deviceset.go (hunk 22 above)
Comment (cpuguy83) [inline daemon/graphdriver/devmapper/deviceset.go]: These two logs are now essentially dupes of the ones in `cancelDeferredRemoval`

Comment (shishir-a412ed) [inline daemon/graphdriver/devmapper/deviceset.go]: Are you taking about these two ? 

1) https://github.com/shishir-a412ed/docker/blob/dm_task_run_failed/daemon/graphdriver/devmapper/deviceset.go#L2181-L2182

2) https://github.com/shishir-a412ed/docker/blob/dm_task_run_failed/daemon/graphdriver/devmapper/deviceset.go#L2204-L2205

`takeSnapshot()` calls `cancelDeferredRemoval()` directly.  So in that case only `cancelDeferredRemoval()` logs will be printed.

**Comment by rhvgoyal** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Comment by thaJeztah** [comment]
@shishir-a412ed can you improve the commit message, and;

- add the problem description from https://github.com/docker/docker/issues/23418 (which gives a good description of what this is trying to fix)
- add a short description of how this changeset fixes it

**Comment by shishir-a412ed** [comment]
@thaJeztah Please check now.

**Comment by thaJeztah** [comment]
Thank you!

**Comment by shishir-a412ed** [comment]
@thaJeztah Any updates on this one ?

**Comment by rhvgoyal** [comment]
@thaJeztah can we merge this one now. Its a race condition users have reported to us and is an issue gets visible if deferred removal is enabled.

**Comment by thaJeztah** [comment]
@rhvgoyal let me check

**Comment by shishir-a412ed** [comment]
@thaJeztah Any updates :)

**Comment by cpuguy83** [comment]
@shishir-a412ed We aren't doing any non-1.12 related merges until after the release.
Since this has been a problem since the feature was added and really hasn't had enough time to get some people actually using it and the potential impact of these changes, we decided not to include in 1.12.

**Comment by thaJeztah** [comment]
1.12 was released, and all green, so merging
