### PR TITLE
Exit if service config is loaded unsuccessfully on startup

### LINKED ISSUE #34476: Invalid registry-mirrors in daemon.json silently ignored
**Description**

When configuring registry-mirrors through the `daemon.json` configuration-file, invalid mirrors are silently ignored.

While there is validation when specifying a mirror through the --registry-mirror`, and pull-request https://github.com/moby/moby/pull/29650 (https://github.com/moby/moby/commit/5b9348c553d183bc62f6e7cc8f934766fac162bd) added the possibility to reload mirrors without restarting the daemon (which _does_ validate the option), a regular start of the daemon just ignores the value.

**Steps to reproduce the issue:**

Starting the daemon manually, and setting the `--registry-mirror` flag, the value is validated correctly:

```bash
$ dockerd --debug --registry-mirror="example.com:5000"
Status: invalid argument "example.com:5000" for --registry-mirror=example.com:5000: invalid mirror: unsupported scheme "example.com" in "example.com:5000"
```

Doing the same through the `daemon.json` configuration file however, silently ignores the invalid option. No message is logged as well (even in debug mode (not shown in the example output below));

```bash
$ mkdir -p /etc/docker/ && echo '{"registry-mirrors": ["example.com:5000"]}' > /etc/docker/daemon.json
$ dockerd

WARN[0000] could not change group /var/run/docker.sock to docker: group docker not found
INFO[0000] libcontainerd: new containerd process, pid: 91
INFO[0001] [graphdriver] using prior storage driver: aufs
INFO[0001] Graph migration to content-addressability took 0.00 seconds
INFO[0001] Loading containers: start.
INFO[0001] Default bridge (docker0) is assigned with an IP address 172.18.0.0/16. Daemon option --bip can be used to set a preferred IP address
WARN[0001] Running modprobe nf_nat failed with message: `modprobe: can't change directory to '/lib/modules': No such file or directory`, error: exit status 1
WARN[0001] Running modprobe xt_conntrack failed with message: `modprobe: can't change directory to '/lib/modules': No such file or directory`, error: exit status 1
WARN[0001] Failed to create DOCKER-USER chain: Iptables not found
INFO[0001] Loading containers: done.
WARN[0001] Couldn't run auplink before unmount /var/lib/docker/tmp/docker-aufs-union121916784: exec: "auplink": executable file not found in $PATH
INFO[0001] Daemon has completed initialization
INFO[0001] Docker daemon                                 commit=02c1d87 graphdriver=aufs version=17.06.0-ce
INFO[0001] API listen on /var/run/docker.sock
```

However, when _reloading_ the same configuration, an error is logged, stating that the configuration is invalid and will not be reloaded:

```bash
$ kill -HUP $(pidof dockerd)

INFO[0304] Got signal to reload configuration, reloading from: /etc/docker/daemon.json
ERRO[0304] Error reconfiguring the daemon: invalid mirror: unsupported scheme "example.com" in "example.com:5000"
```

Note that users can discover that the option is ignored by watching the output of `docker info`; in case of an invalid mirror, the mirror is not shown in the output:

```
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

While with a _correct_ configuration, the mirror is shown:

```
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://example.com:5000/
Live Restore Enabled: false
```

**Describe the results you received:**

No error message, and the option silently ignored

**Describe the results you expected:**

The daemon refusing to start, printing an error message that the configuration is invalid.

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:15:15 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

not relevant; not platform dependent

### PR DESCRIPTION
**Pull request by boaz0**
**- What I did**

This PR closes #34476

In `registry/config.go` at `newServiceConfig` the error returned by `config.LoadMirrors` and `config.LoadInsecureRegistries` weren't checked and by that caused the service configurations error to be silently ignored.

**- How I did it**

Check whether `config.LoadMirrors`/`config.LoadInsecureRegistries` returns an error. If it does, the daemon will print it and exit.

**- How to verify it**

```
$ mkdir -p /etc/docker/ && echo '{"registry-mirrors": ["example.com:5000"]}' > /etc/docker/daemon.json
$ dockerd
```
Should exit and print:
```
invalid registry mirror configurations: invalid mirror: unsupported scheme "example.com" in "example.com:5000
```

**- Description for the changelog**

Fix #34476: invalid registry mirrors configuration isn't being silently ignored

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: registry/config.go [hunk 1]
```diff
@@ -99,8 +99,12 @@ func newServiceConfig(options ServiceOptions) *serviceConfig {
 	}
 
 	config.LoadAllowNondistributableArtifacts(options.AllowNondistributableArtifacts)
-	config.LoadMirrors(options.Mirrors)
-	config.LoadInsecureRegistries(options.InsecureRegistries)
+	if err := config.LoadMirrors(options.Mirrors); err != nil {
+		logrus.Fatalf("invalid registry mirror configurations: %s", err)
```
Comment (AkihiroSuda) [inline registry/config.go]: This should rather return an error and `cmd/dockerd/daemon.go` should catch that err.

Comment (thaJeztah) [inline registry/config.go]: Yes I think that would be better; I also think we can drop the `invalid registry mirror configurations` and `invalid insecure registry configurations` prefix here; the error itself looks pretty self-describing already;

```
invalid mirror: unsupported scheme "example.com" in "example.com:5000
```

When handling in the daemon, we could have a prefix added, similar as what's used for _reloading_ the configuration, e.g.:

```
Error configuring the daemon: 
```

**Review by thaJeztah — CHANGES_REQUESTED** [review]

File: registry/config_test.go [hunk 2]
```diff
@@ -169,6 +169,37 @@ func TestValidateMirror(t *testing.T) {
...
+
+	for _, testCase := range testCases {
+		var err error
+		for _, r := range testCase.registries {
+			err = validateSchemelessRegistry(r)
+		}
+		if err != nil && testCase.err == "" {
+			t.Errorf("expected options to be valid: %s", err)
+		} else if err == nil && testCase.err != "" {
+			t.Errorf("expected options to return error '%s' but got none")
```
Comment (tophj-ibm) [inline registry/config_test.go]: looks like you forgot to point to testCase.err here, janky:
```
registry/config_test.go:196: missing argument for Errorf("%s"): format reads arg 1, have only 0 args
```

File: cmd/dockerd/daemon.go [hunk 3]
```diff
@@ -198,6 +198,9 @@ func (cli *DaemonCli) start(opts *daemonOptions) (err error) {
 		cli.api.Accept(addr, ls...)
 	}
 
+	if err := registry.ValidateServiceOpts(cli.Config.ServiceOptions); err != nil {
+		return err
+	}
 	registryService := registry.NewService(cli.Config.ServiceOptions)
```
Comment (vrothberg) [inline cmd/dockerd/daemon.go]: How about adding a second (error) return value to `NewService()`? This would leave validation to the service and the errors when loading mirrors and registry, etc. wouldn't be ignored anymore (see a similar change in https://github.com/moby/moby/pull/34691/commits/bd3cf1ee56afd22321831396fe89ddf1813be602). Also, notice that the change in the current form is likely to break what @stevvooe suggest in https://github.com/moby/moby/pull/34319, namely to add private-registry-mirror semantics to `--registry-mirror`.

To me it seems like redundant checks, so I suggest to add a second error return value to `NewService()` and leave validation there.

Comment (ripcurld0) [reply cmd/dockerd/daemon.go]: That's actually the best way to handle it. However, that change will require me updating many parts in the code.

Would you suggest to do that even though?

Comment (vrothberg) [reply cmd/dockerd/daemon.go]: @ripcurld0 Do you mean to apply the suggested changes or if I can take over this PR?

Comment (vrothberg) [reply cmd/dockerd/daemon.go]: Ah yes, that makes more sense. `newServiceConfig` should be the right place!

Comment (ripcurld0) [reply cmd/dockerd/daemon.go]: @vrothberg 👍 
@AkihiroSuda @thaJeztah can you please give feedback.

Comment (vrothberg) [reply cmd/dockerd/daemon.go]: But we still need to pass error to daemon start, which implies adding an error return to `newService` (as it calls `newServiceConfig`. Doesn't it?

Comment (ripcurld0) [reply cmd/dockerd/daemon.go]: Yes, actually we do otherwise there is no way to propagate that error.

Comment (ripcurld0) [reply cmd/dockerd/daemon.go]: In a second thought we could create a new function called `NewServiceWithError` and use it in `daemon/dockerd.go`

Comment (vrothberg) [reply cmd/dockerd/daemon.go]: I think that a function that parses or validates user input should return an error, so I prefer to do that for `newService`. But that's just my 2 cents :-)

**Comment by ripcurld0** [comment]
Okay, I am going to update this commit as discussed [here](https://github.com/moby/moby/pull/34495#discussion_r136308821).

I will change `newServiceConfig` to return error too and adjust it to this change.

**Review by stevvooe — APPROVED** [review]

**Comment by vrothberg** [comment]
LGTM. Thank you very much for your changes, @ripcurld0!

**Review by vdemeester — APPROVED** [review]
LGTM 🐮

**Review by thaJeztah — CHANGES_REQUESTED** [review]
changes LGTM, but am I correct that we don't have a test-case added to test the new behaviour? I saw there was a test in an older version of this PR 😅 (perhaps I missed some of the discussion during my vacation)

**Comment by ripcurld0** [comment]
Yes, I need to figure out how to do that in the new integration tests.

**Review by dnephin — COMMENTED** [review]
I think this can be tested with a unit test of `newServiceConfig()`. I don't think there needs to be an integration test.

**Comment by ripcurld0** [comment]
@dnephin thanks I figured it out. ❤️ 
@thaJeztah I am working on this. Thanks for noticing. 😄

**Comment by ripcurld0** [comment]
@thaJeztah and @dnephin 
can you please revisit my changes and verify I am not missing anything.
🍔 😆

**Review by dnephin — APPROVED** [review]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!
