### PR TITLE
API/CLI discrepancy on hostname validation (#21595).

### LINKED ISSUE #21595: API/CLI discrepancy on hostname validation
In the CLI, running a container with a `--hostname` of more than 64 characters will fail:

```
user@ubuntu:~$ docker run -it --net=f826338a441f2f8a4685630e4fd83ad3af78c0fc --hostname=f826338a441f2f8a4685630e4fd83ad3af78c0fc_go1.f826338a441f2f8a4685630e4fd83ad3af78c0fc --name=f826338a441f2f8a4685630e4fd83ad3af78c0fc_go1 golang
docker: invalid hostname format for --hostname: f826338a441f2f8a4685630e4fd83ad3af78c0fc_go1.f826338a441f2f8a4685630e4fd83ad3af78c0fc.
See 'docker run --help'.
```

However, this seems to be allowed through the API, and fails later down the road with:

```
Error response from daemon: Cannot start container 353dc194a5cf9b34d9653b9828aa101f8f598fd2b91c4f3633ac1b5d86f4a72d: [9] System error: invalid argument
```

As far as I can tell, hostname validation happens in [`runconfig/opts/parse.go`](https://github.com/docker/docker/blob/master/runconfig/opts/parse.go#L249).

Cc @calavera @MHBauer.

Indirectly reported in #21562.

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to fix the discrepancy between API and CLI on hostnamevalidation. Previously, the hostname validation was handled at theCLI interface in runconfig/opts/parse.go and return an error if the hostname is invalid. However, if an end user use the remote API topass the hostname, the error will not be returned immediately.Instead the error will only be thrown out when the container creation
fails. This creates behavior discrepancy between API and CLI.

In this fix, the hostname validation was moved to verifyContainerSettings so the behavior will be the same for API andCLI.

After the change, since CLI does not handle the hostname validationany more, the previous unit tests about hostname validation on CLIin runconfig/opts/parse_test.go has to be updated as well becausethere is no validation at this stage. All those unit tests are movedto integration test TestRunTooLongHostname so that the hostnamevalidation is still properly covered as before.

Note: Since the hostname validation moved to API, the error message changes from `invalid hostname format for --hostname:` to`invalid hostname format:` as well because `--hostname` is passedto CLI only.

This fix fixes #21595.

Signed-off-by: Yong Tang yong.tang.github@outlook.com

### CODE REVIEW

**Comment by calavera** [comment]
LGTM

File: daemon/daemon.go [hunk 1]
```diff
@@ -1451,6 +1452,15 @@ func (daemon *Daemon) verifyContainerSettings(hostConfig *containertypes.HostCon
 				return nil, err
 			}
 		}
+
+		// Validate if the given hostname is RFC 1123 (https://tools.ietf.org/html/rfc1123) compliant.
+		if len(config.Hostname) > 0 {
+			// Linux hostname is limited to HOST_NAME_MAX=64, not not including the terminating null byte.
```
Comment (vdemeester) [inline daemon/daemon.go]: ping @jhowardmsft @darrenstahlmsft Is there such a limitation for windows ? (point is should this be there only for linux, or …)

**Comment by vdemeester** [comment]
@yongtang I think the `invalidHostnames` should be removed all together them, as there is almost no purpose on keeping them (other than *we don't validate anything anymore*).

File: daemon/daemon.go (hunk 1 above)
Comment (jhowardmsft) [inline daemon/daemon.go]: From a NetBIOS perspective, it's 15. But unfortunately not that clear cut...

image

From an actual computername, it's 63 - You can't type any more characters after that.

image

image


So the absolute limit can't be more than 63, but I'm not sure whether we should actually limit it to 15 on Windows. @jstarks do you have an opinion here?

**Comment by jhowardmsft** [comment]
I should add, there are invalid characters on Windows: `ComputerName cannot use spaces or any of the following characters: { | } ~ [ \ ] ^ ' : ; < = > ? @ ! " # $ % ` ( ) + / . , * &, or contain any spaces.` from https://technet.microsoft.com/en-us/library/ff715676.aspx

**Comment by yongtang** [comment]
Thanks @jhowardmsft @vdemeester @calavera for the review and providing great information. It looks like I will need to make changes so that Windows platform could be taken into consideration. I will update the pull request soon.

**Comment by yongtang** [comment]
@vdemeester The `invalidHostnames` have been removed.

**Comment by yongtang** [comment]
@vdemeester @jhowardmsft: I may need some input with respect to hostname check in Windows. I am not very familiar with how Docker works cross-platform so I am not sure where to perform the hostname check.

Should the hostname check be done separately for Windows and Linux, one in daemon_windows.go and  another in daemon_linux.go?

Or we need to combine the hostname restrictions in Windows and Linux to have one check for all platforms? At the moment the different between Linux and Windows check is that
1. 64 bytes for Linux and 63 bytes for Windows
2. Windows does not allow `.` char.

Any input would be much appreciated.

**Comment by thaJeztah** [comment]
> Linux and Windows check is that
> 1. 64 bytes for Linux and 63 bytes for Windows
> 2. Windows does not allow . char.

Hm, a quick search brought me; http://www.ietf.org/rfc/rfc1035.txt

> The labels must follow the rules for ARPANET host names.  They must
start with a letter, end with a letter or digit, and have as interior
characters only letters, digits, and hyphen.  There are also some
restrictions on the length.  Labels must be 63 characters or less.

And https://tools.ietf.org/html/rfc1123

> The DNS defines domain name syntax very generally -- a
> string of labels each containing up to 63 8-bit octets,
> separated by dots, and with a maximum total of 255
> octets.


So looks like 63 characters is actually the right length

**Comment by yongtang** [comment]
@thaJeztah Thanks. The 64 bytes was from the Linux reference:
http://man7.org/linux/man-pages/man2/gethostname.2.html
I tested with 64 and 65 bytes hostnames on Linux and 64 bytes is fine (65 bytes will throw out an error). Also hostnames in Linux could contain `.` (dot) which seems to be different from Windows.

**Comment by jstarks** [comment]
Windows has two things: host name and computer name. For containers, we take the provided host name and convert it to a computer name by upcasing and truncating it. Technically we should filter out some other characters, but this hasn't been a priority.

I don't think Docker should concern itself with these details since the computer name typically won't be of interest to containers. It should just ensure that we are passed a valid host name (which should be <= 63 characters without dots, per various RFCs).

**Comment by yongtang** [comment]
@jstarks Thanks. I have updated the pull request with the restriction of hostname <= 63 bytes, to stick with RFCs.
Let me know if there are any other issues.

**Comment by calavera** [comment]
still LGTM

File: daemon/daemon.go [hunk 2]
```diff
@@ -1338,6 +1339,18 @@ func (daemon *Daemon) verifyContainerSettings(hostConfig *containertypes.HostCon
 				return nil, err
 			}
 		}
+
+		// Validate if the given hostname is RFC 1123 (https://tools.ietf.org/html/rfc1123) compliant.
+		if len(config.Hostname) > 0 {
+			// RFC1123 specifies that 63 bytes is the maximium length
+			// Windows has the limitation of 63 bytes in length
+			// Linux hostname is limited to HOST_NAME_MAX=64, not not including the terminating null byte.
```
Comment (thaJeztah) [inline daemon/daemon.go]: typo: "not not" -> "not" (no need to fix unless there are other things to fix)

**Comment by thaJeztah** [comment]
ping @vdemeester @jhowardmsft PTAL

**Comment by jhowardmsft** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM and green :green_heart:
