### PR TITLE
Specify in which line the Dockerfile parser failed

### LINKED ISSUE #30022: No line numbers on Dockerfile parse errors
In 1.13 we pre parse the Dockerfile for errors, but the reporting sadly lacks the context you would get from the previous setup, as you can't see where in the Dockerfile you have got to. This came up while debugging yesterday where there were two places in the Dockerfile the error could occur, and the user had I think only checked the first one, but the error did not help.

eg with this Dockerfile
```
FROM alpine
ERROR
RUN echo
ERROR
```

I get 
```
buckeye:error justin$ docker build .
Sending build context to Docker daemon 2.048 kB
Error response from daemon: Unknown instruction: ERROR
```

Obviously here they are more obvious but with errors due to comments and continuations they are less so.

### PR DESCRIPTION
**Pull request by boaz0**
closes #30022 

**- What I did**
Add the line number in the file in the Dockerfile parser error.

**- How I did it**
Apparently, the [parser.Node](https://github.com/docker/docker/blob/master/builder/dockerfile/parser/parser.go#L28-L37) holds the starting line of the command in the file.
Using it, it's easy to concatenate the line number where Docker fails to parse the Dockerfile. 

**- How to verify it**
Run integration-cli tests:
```shell
TESTFLAGS='-check.f DockerSuite.TestBuildLineError*' make test-integration-cli
```

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by justincormack** [comment]
poked the CI to actually run the tests...

**Comment by justincormack** [comment]
This is definitely an improvement, but I would prefer the line number not the step number if possible, as if people have made errors in commenting or continuations it might be confusing. If that is really hard, printing the step might be better too?

**Comment by ripcurld0** [comment]
@justincormack cool. I think I can do that 👣

**Comment by ripcurld0** [comment]
@justincormack  🕺 done

File: builder/dockerfile/builder.go [hunk 1]
```diff
@@ -264,7 +264,8 @@ func (b *Builder) build(stdout io.Writer, stderr io.Writer, out io.Writer) (stri
 	total := len(b.dockerfile.Children)
 	for _, n := range b.dockerfile.Children {
 		if err := b.checkDispatch(n, false); err != nil {
-			return "", err
+			// Specify in which line the parsing failed
+			return "", fmt.Errorf("Line %d: %s", n.StartLine, err)
```
Comment (justincormack) [inline builder/dockerfile/builder.go]: I think we should specifically say `Dockerfile parse error line %d`... so the error is self contained, as there could be other types of Dockerfile error in future.

Comment (ripcurld0) [inline builder/dockerfile/builder.go]: Yes, that makes more sense.

**Review by justincormack — APPROVED** [review]

**Comment by justincormack** [comment]
Thanks! LGTM.

cc @thaJeztah

File: builder/dockerfile/builder.go [hunk 2]
```diff
@@ -264,7 +264,8 @@ func (b *Builder) build(stdout io.Writer, stderr io.Writer, out io.Writer) (stri
 	total := len(b.dockerfile.Children)
 	for _, n := range b.dockerfile.Children {
 		if err := b.checkDispatch(n, false); err != nil {
-			return "", err
+			// Specify in which line the parsing failed
+			return "", fmt.Errorf("Dockerfile parse error line %d: %s", n.StartLine, err)
```
Comment (cpuguy83) [inline builder/dockerfile/builder.go]: `errors.Wrapf`
Also the comment seems redundant here.

**Comment by duglin** [comment]
LGTM

File: builder/dockerfile/builder.go (hunk 2 above)
Comment (ripcurld0) [inline builder/dockerfile/builder.go]: Thanks @cpuguy83 I will do these changes.

**Review by cpuguy83 — APPROVED** [review]
LGTM
