### PR TITLE
Fix wrong graphdb refs paths purging

### LINKED ISSUE #12334: (master) links shows error when restarting linked-to container
With master binary:

```
# docker run -d --name test busybox top
54ae2450e1fcccbb53552b904cabef462718fe12da271a772116374be7a9eb1a
# docker run -d --name test2 --link test:test busybox
cd5ef2344c99c5fa8fc8ad49c9e1d63a4966b489ff3672f05185cbb2c411ff06
# docker rm test2
# docker restart test
DEBU[0096] Calling POST /containers/{name:.*}/restart
INFO[0096] POST /v1.19/containers/test/restart?t=10
INFO[0096] +job restart(test)
DEBU[0096] Sending 15 to 54ae2450e1fcccbb53552b904cabef462718fe12da271a772116374be7a9eb1a
ERRO[0096] no such id: cd5ef2344c99c5fa8fc8ad49c9e1d63a4966b489ff3672f05185cbb2c411ff06
INFO[0097] -job restart(test) OK
test
#
```

Links still work, however it seems removed containers are not being de-refed properly in the link graph.

### PR DESCRIPTION
**Pull request by runcom**
Fixes: #12334

When deleting (purging) a container, linked containers were not updating correctly meaning they were left with the `parent_id` referencing a deleted container.
The solution is to just delete the edge (container) that has `parent_id` referencing to the deleted container. Updating this row is not necessary because there's just a row for that container.

Maybe this let you undestand better.
After `docker run -d --name fixgraph busybox top` and `docker run -d --name fixgraphtest --link fixgraph:fixgraph busybox` run, the sqlite db looks like this:

Pre

After `docker rm fixgraphtest` the table looks like:

Post

So due to to row `258` is still there the error in the issue is thrown. Hence this fix.

Hope this won't break something because it seems to not have showed up till now even if this error was present in previous release (tested on both 1.6.0-rc5/6 and stock 1.5.0). Also I'm not aware if leaving that row was intentional for debugging purpose or something else. 

I'll add a regression test asap if this is confirmed.

/cc @cpuguy83 @LK4D4 @crosbymichael 

Signed-off-by: Antonio Murdaca me@runcom.ninja

### CODE REVIEW

**Comment by cpuguy83** [comment]
SGTM

**Comment by LK4D4** [comment]
Seems legit. I think we'll merge this with test.

**Comment by runcom** [comment]
I'll add it

File: pkg/graphdb/graphdb.go [hunk 1]
```diff
@@ -378,12 +378,22 @@ func (db *Database) Purge(id string) (int, error) {
...
 		return -1, err
 	}
-
 	changes, err := rows.RowsAffected()
 	if err != nil {
 		return -1, err
 	}
 
+	// Clear who's using this id as parent
+	refs, err := tx.Exec("DELETE FROM edge WHERE parent_id = ?;", id)
```
Comment (thaJeztah) [inline pkg/graphdb/graphdb.go]: Can't SQLite handle this by itself if a proper foreign-key constraint is defined?

Comment (runcom) [inline pkg/graphdb/graphdb.go]: problem is `on delete cascade` cannot be used because of the unique constraints and the other foreign key on `entity_id`

Comment (thaJeztah) [inline pkg/graphdb/graphdb.go]: 😢 I think this should be fine, but had the graph db on my list to delve into. I personally always like the db to be in control for referential integrity, not the app :)

Comment (runcom) [inline pkg/graphdb/graphdb.go]: putting on cascade delete on the reference doesn't remove the row in question, I've not digged around so much because i didn't fell super confortable in changing these things in this pr, maybe should be another pr to address correct handling of references using the schema itself. If you look the funcion call above is using the same pattern btw, when if correctly handled by the db only the next function would be needed (the one deleting the row holding the foreign key and triggering the cascade)

**Comment by runcom** [comment]
ping @LK4D4 @cpuguy83 test added

**Comment by jfrazelle** [comment]
nice LGTM

**Comment by jfrazelle** [comment]
thanks @runcom

**Comment by LK4D4** [comment]
LGTM
