### PR TITLE
Fixing Regression in exit codes in 1.12

### LINKED ISSUE #26775: Regression in exit codes in 1.12
This is a copy of https://github.com/docker/docker/issues/26152, which is resolved on master, but the fix is part of a bigger change (conversion of `docker` and `dockerd` to Cobra), so to fix this we need to have a different patch that only contains a fix for the exit codes.

Opening this for the 1.12.2 milestone as this is a regression in 1.12 (see https://github.com/docker/docker/issues/26152#issuecomment-248549495)

### PR DESCRIPTION
**Pull request by vdemeester**
Fixes #26775. Opened the PR against `1.12.x` branch.

```
   # docker load --input;echo $?
   flag needs an argument: --input
   See 'docker load --help'.
   125    <-- 125 with docker-1.10 ; 1 with docker-1.12

   # docker ps --filters;echo $?         <-- same with -n or --format
   unknown flag: --filters
   See 'docker ps --help'.
   125    <-- 125 with docker-1.10 ; 1 with docker-1.12
```

/cc @dnephin @runcom @thaJeztah @icecrime 

Signed-off-by: Vincent Demeester vincent@sbr.pm

### CODE REVIEW

File: api/client/container/wait.go [hunk 1]
```diff
@@ -28,7 +28,6 @@ func NewWaitCommand(dockerCli *client.DockerCli) *cobra.Command {
 			return runWait(dockerCli, &opts)
 		},
 	}
-	cmd.SetFlagErrorFunc(flagErrorFunc)
```
Comment (dnephin) [inline api/client/container/wait.go]: I think the definition for  `func flagErrorFunc()` can be deleted as well? That way we can be sure it's not use anywhere else.

Comment (vdemeester) [inline api/client/container/wait.go]: ah that's right, I'll update 👼

Comment (vdemeester) [inline api/client/container/wait.go]: done :)

**Comment by dnephin** [comment]
LGTM

**Comment by andrewhsu** [comment]
can this be tested with integration-cli?

**Review by thaJeztah — APPROVED** [review]
LGTM

> can this be tested with integration-cli?

@andrewhsu I briefly discussed this with @vdemeester, and testing this would require quite some work, but if you want to contribute a test on master to prevent future regressions, let us know.

**Comment by vieux** [comment]
@vdemeester should we fix it in master too ?

**Comment by vdemeester** [comment]
@vieux it's already fixed in master (@dnephin did it when switching all commands to cobra).

**Comment by dnephin** [comment]
Yup, It was part of a larger PR so there wasn't a single commit to be cherry-picked to the release branch
