### PR TITLE
Resolve race conditions in attach API call

### LINKED ISSUE #29285: Suspected race conditions in daemon/attach.go
**Description**

I ran into a sporadic API consumer hang when reading stdout/stderr from a very short-executing container.  The API consumer calls ContainerCreate, ContainerAttach, ContainerStart, ContainerWait in order.  When the problem occurs, the server does not write the container stdout/stderr to the ContainerAttach connection, and after the ContainerWait call completes, the server does not close the ContainerAttach connection, causing the API consumer to hang. 

By inspection I found the following suspected race conditions in https://github.com/docker/docker/blob/master/daemon/attach.go:

1. ContainerAttach returns "200 OK" to the caller at https://github.com/docker/docker/blob/9d884986f5c001cacb60aa3c50036575ed2dd22d/daemon/attach.go#L37 before the stdout/stderr streams are actually attached to the container at https://github.com/docker/docker/blob/9d884986f5c001cacb60aa3c50036575ed2dd22d/daemon/attach.go#L61.

   During this window, it is actually possible for a container to be started and to run to completion.  If this happens, the API consumer doesn't receive the container stdout/stderr, and the consumer also misses its connection being closed as part of the container teardown in https://github.com/docker/docker/blob/9d884986f5c001cacb60aa3c50036575ed2dd22d/container/stream/streams.go#L90.

   The easiest way I've found to reproduce this requires modifying the server: insert `time.Sleep(10 * time.Second)` before https://github.com/docker/docker/blob/9d884986f5c001cacb60aa3c50036575ed2dd22d/daemon/attach.go#L61 and then compile and run the test program below.

   _Note: as an additional protection measure IMO it would be worth making broadcaster.Unbuffered stateful and unreusable to protect against new Writers being `Add()`ed after `Clean()` has been called._

2. I suspect `containerAttach` (https://github.com/docker/docker/blob/9d884986f5c001cacb60aa3c50036575ed2dd22d/daemon/attach.go#L76) to be racy: logs are harvested and returned at https://github.com/docker/docker/blob/9d884986f5c001cacb60aa3c50036575ed2dd22d/daemon/attach.go#L77-L106, then I believe there is a window during which any new logs would be lost to the consumer before `Attach` succeeds at https://github.com/docker/docker/blob/9d884986f5c001cacb60aa3c50036575ed2dd22d/daemon/attach.go#L131.  At the moment, I believe a caller who sets logs = true and stream = true is not guaranteed not to lose logging data.

3. I suspect the invocation of `container.IsPaused()` at https://github.com/docker/docker/blob/9d884986f5c001cacb60aa3c50036575ed2dd22d/daemon/attach.go#L32 must be racy because I don't see any protection against the container state changing in parallel before the containerAttach completes.

I believe that if these issues are valid, they indicate that overall the attach and logging logic needs some rework to be more closely integrated into pre-existing container state / synchronisation primitives, and consideration also needs to be given about if/how to atomically read past logs and start streaming without missing data.

**Steps to reproduce the issue:**
1. Insert `time.Sleep(10 * time.Second)` before https://github.com/docker/docker/blob/9d884986f5c001cacb60aa3c50036575ed2dd22d/daemon/attach.go#L61; compile and run Docker server
2. `docker pull busybox`
3. Compile and run the following golang program:
```golang
package main

import (
	"context"
	"os"

	"github.com/docker/docker/api/types"
	"github.com/docker/docker/api/types/container"
	"github.com/docker/docker/api/types/network"
	"github.com/docker/docker/client"
	"github.com/docker/docker/pkg/stdcopy"
)

func main() {
	ctx := context.Background()

	cli, err := client.NewEnvClient()
	if err != nil {
		panic(err)
	}

	c, err := cli.ContainerCreate(ctx, &container.Config{Image: "busybox", Entrypoint: []string{"sh", "-c", "echo hello world"}}, &container.HostConfig{}, &network.NetworkingConfig{}, "")
	if err != nil {
		panic(err)
	}

	hi, err := cli.ContainerAttach(ctx, c.ID, types.ContainerAttachOptions{Stream: true, Stdout: true})
	if err != nil {
		panic(err)
	}

	ch := make(chan error, 1)
	go func() {
		_, copyerr := stdcopy.StdCopy(os.Stdout, os.Stdout, hi.Reader)
		ch <- copyerr
	}()

	err = cli.ContainerStart(ctx, c.ID, types.ContainerStartOptions{})
	if err != nil {
		panic(err)
	}

	code, err := cli.ContainerWait(ctx, c.ID)
	if err != nil {
		panic(err)
	}

	err = <-ch
	if err != nil {
		panic(err)
	}

	os.Exit(int(code))
}
```

**Describe the results you received:**
no output; hang

**Describe the results you expected:**
output "hello world", exit 0.

**Output of `docker version`:**

```
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.4
 Git commit:   9d88498
 Built:        Fri Dec  9 20:01:40 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.14.0-dev
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.4
 Git commit:   9d88498
 Built:        Fri Dec  9 20:01:40 2016
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.14.0-dev
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.2.3-300.fc23.x86_64
Operating System: Fedora 23 (Twenty Three)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.797 GiB
Name: openshiftdev
ID: YHFD:22Z2:JM6H:AUT2:XA72:6POC:DFYQ:JTFZ:KE3Y:QPUM:ZY33:DOVO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### PR DESCRIPTION
**Pull request by jim-minter**
Signed-off-by: Jim Minter <jminter@redhat.com>

Fixes #29285

**- What I did**

In `container/container.go`, split AttachStreams() into two pieces.  The first returns the container's streams, having registered stdout & stderr in the broadcaster.  The second does the byte copying as before.

In `daemon/attach.go` pull forward the call to container.AttachStreams() so that these are held before the HTTP response is returned to the client via c.GetStreams().

**- How to verify it**

See reproducer in #29285

**- Description for the changelog**

Resolve race conditions in attach API call

### CODE REVIEW

**Comment by jim-minter** [comment]
@runcom @tonistiigi @cpuguy83 @LK4D4

File: container/container.go [hunk 1]
```diff
@@ -373,35 +373,46 @@ func (container *Container) GetExecIDs() []string {
...
+
+	if useStderr {
+		cStderr = streamConfig.StderrPipe()
+	}
+
+	return cStdin, cStdout, cStderr
+}
+
+// CopyStreams starts goroutines to copy data in and out to/from the container
+// Used by exec too. Should this move somewhere else?
```
Comment (thaJeztah) [inline container/container.go]: This should be a TODO?

File: container/container.go [hunk 2]
```diff
@@ -373,35 +373,46 @@ func (container *Container) GetExecIDs() []string {
...
+func CopyStreams(ctx context.Context, streamConfig *stream.Config, openStdin, stdinOnce, tty bool, stdin io.ReadCloser, stdout io.Writer, stderr io.Writer, cStdin io.WriteCloser, cStdout io.ReadCloser, cStderr io.ReadCloser, keys []byte) chan error {
```
Comment (AkihiroSuda) [inline container/container.go]: * `streamConfig` seems unused
* having a dozen of arguments does not seem a good design
* Since this function is not used in the `container` package, you can move this to `daemon` package. Maybe it is even ok to move to under `pkg/something`.

**Review by AkihiroSuda — CHANGES_REQUESTED** [review]

File: container/container.go [hunk 3]
```diff
@@ -373,35 +373,46 @@ func (container *Container) GetExecIDs() []string {
...
 
-// Attach connects to the container's TTY, delegating to standard
-// streams or websockets depending on the configuration.
-func (container *Container) Attach(stdin io.ReadCloser, stdout io.Writer, stderr io.Writer, keys []byte) chan error {
-	ctx := container.InitAttachContext()
-	return AttachStreams(ctx, container.StreamConfig, container.Config.OpenStdin, container.Config.StdinOnce, container.Config.Tty, stdin, stdout, stderr, keys)
-}
-
 // AttachStreams connects streams to a TTY.
 // Used by exec too. Should this move somewhere else?
```
Comment (AkihiroSuda) [inline container/container.go]: "Should this move somewhere else?" makes sense now

File: container/container.go (hunk 2 above)
Comment (cpuguy83) [inline container/container.go]: Please see https://github.com/docker/docker/pull/30344/files

**Comment by LK4D4** [comment]
@jim-minter I just merged #30344 
Your PR should be slightly simpler after rebase. Thanks!

**Comment by jim-minter** [comment]
Rebased.

File: daemon/exec.go [hunk 4]
```diff
@@ -210,15 +210,19 @@ func (d *Daemon) ContainerExecStart(ctx context.Context, name string, stdin io.R
 		return err
 	}
 
-	attachConfig := &stream.AttachConfig{
```
Comment (LK4D4) [inline daemon/exec.go]: why?

**Comment by LK4D4** [comment]
LGTM apart from `&` :) I don't know why, but I don't like this style and it was different before.

File: daemon/exec.go (hunk 4 above)
Comment (jim-minter) [inline daemon/exec.go]: Removal of the '&' on this line means that it can be put in the argument of the AttachStreams() function call subsequently, which is a tiny hint to any reader that the struct is mutated by that function.

I can switch this back if preferred, but I thought it was better this way around.

Comment (LK4D4) [inline daemon/exec.go]: It's okay for me. Thanks for explanation.

**Comment by LK4D4** [comment]
ping @AkihiroSuda

**Comment by LK4D4** [comment]
ping @docker/core-engine-maintainers

File: container/stream/attach.go [hunk 5]
```diff
@@ -33,33 +33,47 @@ type AttachConfig struct {
 	// For example, this would close the attached container's stdin.
 	CloseStdin bool
 
+	UseStdin, UseStdout, UseStderr bool
+
+	CStdin           io.WriteCloser
```
Comment (AkihiroSuda) [inline container/stream/attach.go]: Please add a comment about `{Use,C}Std{in,out,err}` here for ease of understandability?

Comment (jim-minter) [inline container/stream/attach.go]: Comments added, thanks.

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by runcom** [comment]
@jim-minter @LK4D4 @cpuguy83 this has caused a regression:
```sh
$ echo true | docker run -a stdin -a stderr --tty=false centos
read unix @->/var/run/docker.sock: read: connection reset by peer

$ echo true | docker run -a stdin -a stderr centos
read unix @->/var/run/docker.sock: read: connection reset by peer
```
It's happening only if _both_ stdin and stderr are attached, if you attach just stdin or just stderr, no issues. However, this works w/o this patch.

**Comment by runcom** [comment]
opened https://github.com/docker/docker/issues/30816

**Comment by thaJeztah** [comment]
Thanks @runcom
