### PR TITLE
Fix container cleanup on daemon restart

### LINKED ISSUE #36145: docker start <container_name> returns "container <hash> already exists"
**Description**
`docker start` returns `Error response from daemon: container <hash>: already exists`
This happened after I installed the latest upgrade.
The only other change I did was to remove check from "Enable kubernetes" and apply that change (from docker preferences window).

**Describe the results you received:**
```
dps -a
IMAGE                                                 NAMES                PORTS                                            COMMAND                  STATUS
jetty                                                 infallible_hodgkin                                                    "/docker-entrypoint.…"   Exited (0) 2 weeks ago
jetty                                                 gallant_perlman                                                       "/docker-entrypoint.…"   Exited (1) 2 weeks ago
docker.elastic.co/elasticsearch/elasticsearch:5.6.3   st-es                0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp   "/bin/bash bin/es-do…"   Exited (255) 18 minutes ago
appbaseio/mirage                                      mystifying_meitner   0.0.0.0:3030->3030/tcp                           "http-server '-p 303…"   Exited (255) 2 months ago
appbaseio/dejavu                                      heuristic_jones      0.0.0.0:1358->1358/tcp                           "http-server '-p 135…"   Exited (255) 2 months ago
mongo                                                 mongo                0.0.0.0:27017->27017/tcp                         "docker-entrypoint.s…"   Exited (255) 5 weeks ago
zookeeper                                             st-zk                2888/tcp, 0.0.0.0:2181->2181/tcp, 3888/tcp       "/docker-entrypoint.…"   Exited (255) 18 minutes ago
mysql:5.5                                             st-mysql             0.0.0.0:3306->3306/tcp                           "docker-entrypoint.s…"   Exited (255) 18 minutes ago
% 
% 
% docker start st-mysql
Error response from daemon: container "fa0db3388ad6eb043d8632039c152f58afb68dbb6a2c5a3a7721420a56518477": already exists
Error: failed to start containers: st-mysql
```
**Output of `docker version`:**

```
Client:
 Version:	18.02.0-ce-rc1
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	5e1d90a
 Built:	Thu Jan 25 00:33:50 2018
 OS/Arch:	darwin/amd64
 Experimental:	true
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.02.0-ce-rc1
  API version:	1.36 (minimum version 1.12)
  Go version:	go1.9.3
  Git commit:	5e1d90a
  Built:	Thu Jan 25 00:40:43 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**

```
Containers: 8
 Running: 1
 Paused: 0
 Stopped: 7
Images: 32
Server Version: 18.02.0-ce-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 157
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.75-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 3
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: TLZO:G2VR:E4RK:4L5T:7QZ3:56R3:WSBW:Z7XW:LQMW:AXRE:5QZU:Z3HA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 28
 Goroutines: 45
 System Time: 2018-01-30T14:51:16.971310166Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3128
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### PR DESCRIPTION
**Pull request by cpuguy83**
When the daemon restores containers on daemon restart, it syncs up with
containerd to determine the existing state. For stopped containers it
then removes the container metadata from containerd.

In some cases this is not handled properly and causes an error when
someone attempts to start that container again.
In particular, this case is just a bad error check.

Fixes #36145

### CODE REVIEW

**Review by boaz0 — APPROVED** [review]
LGTM 👍

File: integration/container/daemon_linux_test.go [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+	t.Parallel()
+
+	d := daemon.New(t, "", "dockerd", daemon.Config{})
+	d.StartWithBusybox(t, "--iptables=false")
+	defer d.Stop(t)
+
+	client, err := d.NewClient()
+	if err != nil {
+		t.Fatal(err)
+	}
```
Comment (dnephin) [inline integration/container/daemon_linux_test.go]:
```go
assert.NoError(t, err)
```
?

File: integration/container/daemon_linux_test.go [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+
+	inspect, err := client.ContainerInspect(ctx, c.ID)
+	if err != nil {
+		t.Fatal(err)
+	}
+	if inspect.State.Pid <= 1 {
+		t.Fatalf("got unexpected container PID: %d", inspect.State.Pid)
+	}
```
Comment (dnephin) [inline integration/container/daemon_linux_test.go]: Is this check necessary? won't it fail on the next line, and the pid will be in the pathError message?

File: integration/container/daemon_linux_test.go [hunk 3]
```diff
@@ -0,0 +1,96 @@
...
+
+	// Get the pid of the containerd-shim
+	statB, err := ioutil.ReadFile(fmt.Sprintf("/proc/%d/stat", inspect.State.Pid))
```
Comment (dnephin) [inline integration/container/daemon_linux_test.go]: I think this (line 62-79) should be extracted into a helper so it doesn't distract from the test logic:

```go
ppid := getContainerdShimPID(t, inspect.State.Pid)
```

File: integration/container/daemon_linux_test.go [hunk 4]
```diff
@@ -0,0 +1,96 @@
+package container
```
Comment (dnephin) [inline integration/container/daemon_linux_test.go]: I'm not really sure where this test should go. It seems like it has more to do with daemon state than the container API/.

`s/daemon_linux_test/daemon_test.go/` and add a `skip.If()` because the relevant OS is where the daemon is running, not where the test client is running, so this would be skipped incorrectly if the client was windows, and the daemon was linux.

Comment (cpuguy83) [reply integration/container/daemon_linux_test.go]: This test will not compile on Windows and requires being on the same host since it's starts up a new daemon, kills processes, etc.

Comment (cpuguy83) [reply integration/container/daemon_linux_test.go]: > It seems like it has more to do with daemon state than the container API

It's kind of everything, sadly.

**Comment by cpuguy83** [comment]
Updated

**Review by dnephin — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐯
