### PR TITLE
daemon/config: use strings.Cut(), fix panic in BuilderGCFilter

### LINKED ISSUE #44361: Crash in config.(*BuilderGCFilter).UnmarshalJSON
### Description

We used the Fuzz engine to modify some Test(TestBuilderGC) data, and then the following crash appeared. We hope to get the help of the developer to confirm whether it is a real bug.

### Reproduce

Part of the modified Test Code

```go
	tempFile := fs.NewFile(t, "config", fs.WithContent(`{
  "builder": {
    "gc": {
      "enabled": true,
      "poliCy": [
        {"keepStorage": "10GB", "filter": ["unused-for(2200h"]},
        {"keepStorage": "50GB", "filter": {"unused-for": {"3300h": true}}},
        {"keepStorage": "100GB", "all": true}
      ]
    }
  }
}`))
	defer tempFile.Remove()
	configFile := tempFile.Path()

	cfg, err := MergeDaemonConfigurations(&Config{}, nil, configFile) //crash in MergeDaemonConfigurations
```

Crash Log

```
panic: runtime error: index out of range [1] with length 1 [recovered]
	panic: runtime error: index out of range [1] with length 1

goroutine 101 [running]:
testing.tRunner.func1.2({0x11f1120, 0xc000294cc0})
	/home/gogen/.local/go/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	/home/gogen/.local/go/src/testing/testing.go:1212 +0x218
panic({0x11f1120, 0xc000294cc0})
	/home/gogen/.local/go/src/runtime/panic.go:1038 +0x215
github.com/docker/docker/daemon/config.(*BuilderGCFilter).UnmarshalJSON(0xc000298108, {0xc0002a3870, 0x14, 0x190})
	/home/gogen/workspace/gowork/src/topproj/moby/daemon/config/builder.go:50 +0x338
encoding/json.(*decodeState).array(0xc0002fe090, {0x1175160, 0xc000298108, 0x1a2})
	/home/gogen/.local/go/src/encoding/json/decode.go:506 +0x3f6
encoding/json.(*decodeState).value(0xc0002fe090, {0x1175160, 0xc000298108, 0xc0002a3867})
	/home/gogen/.local/go/src/encoding/json/decode.go:363 +0x7e
encoding/json.(*decodeState).object(0xc0002fe090, {0x11b3a40, 0xc000298100, 0xb})
	/home/gogen/.local/go/src/encoding/json/decode.go:774 +0xca5
encoding/json.(*decodeState).value(0xc0002fe090, {0x11b3a40, 0xc000298100, 0x1})
	/home/gogen/.local/go/src/encoding/json/decode.go:373 +0x45
encoding/json.(*decodeState).array(0xc0002fe090, {0x10f5700, 0xc000b58960, 0x1d2})
	/home/gogen/.local/go/src/encoding/json/decode.go:561 +0x626
encoding/json.(*decodeState).value(0xc0002fe090, {0x10f5700, 0xc000b58960, 0xc0002a383b})
	/home/gogen/.local/go/src/encoding/json/decode.go:363 +0x7e
encoding/json.(*decodeState).object(0xc0002fe090, {0x11b3980, 0xc000b58958, 0x1192f01})
	/home/gogen/.local/go/src/encoding/json/decode.go:774 +0xca5
encoding/json.(*decodeState).value(0xc0002fe090, {0x11b3980, 0xc000b58958, 0xc0002a3816})
	/home/gogen/.local/go/src/encoding/json/decode.go:373 +0x45
encoding/json.(*decodeState).object(0xc0002fe090, {0x1192f60, 0xc000b58958, 0x1a6af01})
	/home/gogen/.local/go/src/encoding/json/decode.go:774 +0xca5
encoding/json.(*decodeState).value(0xc0002fe090, {0x1192f60, 0xc000b58958, 0x7})
	/home/gogen/.local/go/src/encoding/json/decode.go:373 +0x45
encoding/json.(*decodeState).object(0xc0002fe090, {0x120bfc0, 0xc000b58580, 0x886305})
	/home/gogen/.local/go/src/encoding/json/decode.go:774 +0xca5
encoding/json.(*decodeState).value(0xc0002fe090, {0x120bfc0, 0xc000b58580, 0x90})
	/home/gogen/.local/go/src/encoding/json/decode.go:373 +0x45
encoding/json.(*decodeState).unmarshal(0xc0002fe090, {0x120bfc0, 0xc000b58580})
	/home/gogen/.local/go/src/encoding/json/decode.go:180 +0x1de
encoding/json.Unmarshal({0xc0002a3800, 0x7f609b0b0c00, 0x857d50}, {0x120bfc0, 0xc000b58580})
	/home/gogen/.local/go/src/encoding/json/decode.go:107 +0x125
github.com/docker/docker/daemon/config.getConflictFreeConfiguration({0xc0002942d0, 0xc000b58000}, 0x0)
	/home/gogen/workspace/gowork/src/topproj/moby/daemon/config/config.go:473 +0x405
github.com/docker/docker/daemon/config.MergeDaemonConfigurations(0x1390f08, 0xc000882820, {0xc0002942d0, 0x6})
	/home/gogen/workspace/gowork/src/topproj/moby/daemon/config/config.go:393 +0x33
```

### Expected behavior

-

### docker version

```bash
-
```

### docker info

```bash
-
```

### Additional Info

Implemented only with go test

### PR DESCRIPTION
**Pull request by thaJeztah**
splitting this out of a branch I had which replaces strings.Split(N) calls.

- fixes https://github.com/moby/moby/issues/44361

### CODE REVIEW

**Comment by thaJeztah** [comment]
Actually; let me add a test for this, based on the report

**Comment by cpuguy83** [comment]
Is this change in the other PR?

**Comment by thaJeztah** [comment]
> Is this change in the other PR?

No, I split the commit from the other one, as this one was fixing a bug reported (in case we wanted to include the fix in a release separate from the other changes)

**Review by cpuguy83 — APPROVED** [review]

File: daemon/config/builder_test.go [hunk 1]
```diff
@@ -42,3 +42,24 @@ func TestBuilderGC(t *testing.T) {
 	assert.Assert(t, filters.Args(cfg.Builder.GC.Policy[0].Filter).UniqueExactMatch("unused-for", "2200h"))
 	assert.Assert(t, filters.Args(cfg.Builder.GC.Policy[1].Filter).UniqueExactMatch("unused-for", "3300h"))
 }
+
+// Regression test for https://github.com/moby/moby/issues/44361
+func TestBuilderGCPanic(t *testing.T) {
```
Comment (cpuguy83) [inline daemon/config/builder_test.go:47]: Already LGTM'd, but I think it would make sense to name this test based on what is being tested which clearly was not being tested before.
We aren't testing to see if the builder panics, we are testing how it handles various inputs.
