### PR TITLE
api: allow NW name that is the prefix of a swarm NW ID

### LINKED ISSUE #27866: Flaky test: DockerSwarmSuite.TestPruneNetwork
Seen flakily failing on arm and ppc64le.

``` sh
----------------------------------------------------------------------
FAIL: docker_cli_prune_unix_test.go:26: DockerSwarmSuite.TestPruneNetwork

[d4ebd159337da] waiting for daemon to start
[d4ebd159337da] daemon started
docker_cli_prune_unix_test.go:35:
    c.Assert(err, checker.IsNil)
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc4205245a0), Stderr:[]uint8(nil)} ("exit status 1")

[d4ebd159337da] exiting daemon

----------------------------------------------------------------------
```

unfortunately the Jenkins logs were deleted as I was making this, but I'm seeing it on my local power machine on master as well.

### PR DESCRIPTION
**Pull request by AkihiroSuda**
**- What I did**

Allows creating a network of which name is the prefix of the ID of a swarm network
    
Previously, it doesn't allow creating such a network:

e.g.
 
```console
$ docker network inspect -f '{{.Id}}' ingress
84xh9knigj6zyt00u31e26nj3
$ docker network create 84
Error response from daemon: network with name 84 already exists
```
Fix #27866 (Flaky test: DockerSwarmSuite.TestPruneNetwork) 

**- How I did it**
Please look at api/server/router/network/network_routes.go

**- How to verify it**

```console
$ docker network inspect -f '{{.Id}}' ingress
84xh9knigj6zyt00u31e26nj3
$ docker network create 84
40a945ea84e643bd5234751846e72aadd08a3afab91fbcd4ab3b6e44d3fda8f3
```

**- Description for the changelog**

api: allow NW name that is the prefix of a swarm NW ID

**- A picture of a cute animal (not mandatory but encouraged)**
image

Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>

### CODE REVIEW

**Comment by cpuguy83** [comment]
ping @mrjana

File: api/server/router/network/network_routes.go [hunk 1]
```diff
@@ -79,8 +80,16 @@ func (n *networkRouter) postNetworkCreate(ctx context.Context, w http.ResponseWr
 		return err
 	}
 
-	if _, err := n.clusterProvider.GetNetwork(create.Name); err == nil {
-		return libnetwork.NetworkNameError(create.Name)
+	if nw, err := n.clusterProvider.GetNetwork(create.Name); err == nil {
```
Comment (aaronlehmann) [inline api/server/router/network/network_routes.go]: This check doesn't seem very useful. First, it's racy. Also, it does a prefix match, which is not what we want here.

`n.clusterProvider.CreateNetwork` will fail if the name conflicts. Could we just remove this check?

Comment (AkihiroSuda) [inline api/server/router/network/network_routes.go]: Makes sense, however, we need to check the conflict before calling `backend.CreateNetwork()`, so as to detect a conflict like this:
```console
$  docker service create -d overlay foo
$  docker service create -d bridge foo 
Error response from daemon: network with name foo already exists
```

A solution I can come up with is to call `clusterProvider.CreateNetwork()` before calling `backend.CreateNetwork()` for swarm-scoped networks, but I'm not sure how we can detect the scope here.

WDYT?
cc @mrjana @mavenugo @aboch

Comment (AkihiroSuda) [inline api/server/router/network/network_routes.go]: I can understand your opinion. But even for production, people may try to create a network named "n1", "n2"..
It would be great if we can find a solution.

Comment (aboch) [inline api/server/router/network/network_routes.go]: Agree. But I am afraid this cannot be guaranteed unless we serialize the network creation at API level. Which seems too much of a penalty.

Comment (aaronlehmann) [inline api/server/router/network/network_routes.go]: I agree with @AkihiroSuda. It's ridiculous not to allow creating a network if its name is a prefix of another network's ID.

And using longer names in the test won't solve the problem, it will just make the failures less likely - so when they do happen, they will be very hard to reproduce and cause a lot of confusion.

Comment (stevvooe) [inline api/server/router/network/network_routes.go]: > isn't it the same as partial ID matches for containers; ID > full name match > partial ID match

I am not sure. Typically, there should be a resolution component and the getter should _only_ take ID. In this case, I think we hit the docker API, so ambiguity of id/name may be a problem.

**Comment by AkihiroSuda** [comment]
Updated PR. 
PTAL @aaronlehmann @aboch @stevvooe 

This fix should be enough for the original issue https://github.com/docker/docker/issues/27866 .

However, this doesn't fix an issue about removing networks.

e.g.
```console
$ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
0db1e31d181f        bridge              bridge              local
4f8a8c0144ad        docker_gwbridge     bridge              local
4aa7a6b845ef        host                host                local
kveaqnegpm66        ingress             overlay             swarm
82ba9477298d        kvea                bridge              swarm
7190e8d532c5        none                null                local
$ docker network rm kvea                                                                  
Error response from daemon: rpc error: code = 7 desc = ingress (kveaqnegpm66y75q9wj6urfwq) is a pre-defined network and cannot be removed
```
(`docker network rm kvea` should remove the network of which name is`kvea`, of which ID starts with `82ba9477298d`)

For removal, we would need to implement the "set" approach which @stevvooe repeatedly mentioned (e.g. https://github.com/docker/swarmkit/pull/1279#issuecomment-246519291, https://github.com/docker/swarmkit/pull/1194#issuecomment-239029662) in another PR.

File: api/server/router/network/network_routes.go [hunk 2]
```diff
@@ -80,7 +80,7 @@ func (n *networkRouter) postNetworkCreate(ctx context.Context, w http.ResponseWr
 		return err
 	}
 
-	if _, err := n.clusterProvider.GetNetwork(create.Name); err == nil {
+	if _, err := n.clusterProvider.GetNetworkByName(create.Name); err == nil {
 		return libnetwork.NetworkNameError(create.Name)
```
Comment (thaJeztah) [inline api/server/router/network/network_routes.go]: Not directly related to this PR, but wondering; should this check only be performed if `create.CheckDuplicate` is true? (see [daemon/network.go#L256-L258](https://github.com/docker/docker/blob/4fae94f6637bfbbeba809f930f2ecf1e36748882/daemon/network.go#L256-L258))

I see this was added in [#24158](https://github.com/docker/docker/pull/24158/commits/0ce5158a2a9a3f10a62d3c1ea289c55e524cdac5#diff-6e937312ed7fe823e2b7fe0d1215fb60R84)

Since allowing duplicate names is by design (https://github.com/docker/docker/issues/18864#issuecomment-167006094), I wonder if it should error out.

(t.b.h. I would rather stop allowing duplicate names, because I think the _name_ is used in many cases as the only reference)

ping @mavenugo ^^

**Comment by mavenugo** [comment]
@AkihiroSuda @thaJeztah I can't think of a good use-case for this to be a useful fix. Yes. this is an inconvenience for some cases, but I don't see a strong need to get this PR. IMO living with this restriction is better than trying to fix it and cause more head-aches.

**Comment by aaronlehmann** [comment]
@mavenugo: What downside do you see? The old code was querying for a duplicate network in a way that would do prefix matching on IDs, which is clearly wrong. This was causing random integration test failures (sometimes "n1" would be a prefix of a network with ID "n1..."). I know there are still some remaining issues, but would like to understand what headaches it may cause to correct this check.

**Comment by mavenugo** [comment]
@aaronlehmann the existing UX accepts `name`, `id` and `partial-id` in many places. And this will cause confusion on those areas. and that is the reason @AkihiroSuda  mentioned this : `However, this doesn't fix an issue about removing networks.` and I expect the same problem in other areas such as `inspect`.
am trying to understand the use-case for such a requirement. Especially because names are user-provided and can be anything. Why would someone need a overlapping name with an existing id ?

**Comment by aaronlehmann** [comment]
One of the use cases is what I mentioned above. If you try to create a network named `n1`, and there is an existing network whose ID is the base36 string starting with `n1...`, it fails with the current code. This caused problems in an integration test. With the current code, it would be impossible to choose a name that is always okay, because any name can potentially overlap with an ID prefix.

I don't see this as adding a feature, but instead correcting incorrect validation. It's completely legitimate to have a name overlap with an ID prefix. We allow it for other kinds of objects. Networks are handled inconsistently and this is a bug.

There should be no issue with `inspect`. We always prefer exact name matches to ID prefix matches. This is what is done for all other objects I know of, such as images, containers, services, and so on. We need to make networks consistent with these other objects.

**Comment by mavenugo** [comment]
@aaronlehmann okay. if this is something unique to network then i agree we should fix it. Do you prefer fixing the IT issue alone in this PR and address the rest later in other PRs ?

Also, the simpler fix for the IT issue would be to change the TestPruneNetwork to use a longer randomized network name. And we do rely on the uniqueness of IDs (since the randomization really works and doesn't cause flaky tests for other tests :) )

**Comment by aaronlehmann** [comment]
> okay. if this is something unique to network then i agree we should fix it. Do you prefer fixing the IT issue alone in this PR and address the rest later in other PRs ?

Yes, I think we should start by allowing names to overlap with ID prefixes, and in separate PRs we should fix the other issues.

> Also, the simpler fix for the IT issue would be to change the TestPruneNetwork to use a longer randomized network name. And we do rely on the uniqueness of IDs (since the randomization really works and doesn't cause flaky tests for other tests :)

I agree that this would technically work and that we rely on ID uniqueness. My preference is to allow names to overlap with ID prefixes for consistency with other objects, as done in the latest revision of this PR.

File: daemon/cluster/cluster.go [hunk 3]
```diff
@@ -1538,13 +1537,23 @@ func (c *Cluster) GetNetwork(input string) (apitypes.NetworkResource, error) {
...
-	network, err := getNetwork(ctx, c.client, input)
+	network, err := getter(ctx, c.client, input)
 	if err != nil {
 		return apitypes.NetworkResource{}, err
 	}
 	return convert.BasicNetworkFromGRPC(*network), nil
 }
 
+// GetNetwork returns a cluster network by an ID.
+func (c *Cluster) GetNetwork(input string) (apitypes.NetworkResource, error) {
```
Comment (tiborvass) [inline daemon/cluster/cluster.go]: rename `input` to `id` to make it clearer

File: daemon/cluster/cluster.go [hunk 4]
```diff
@@ -1538,13 +1537,23 @@ func (c *Cluster) GetNetwork(input string) (apitypes.NetworkResource, error) {
...
+	return c.getNetwork(input, getNetwork)
+}
+
+// GetNetworkByName returns a cluster network by name.
+func (c *Cluster) GetNetworkByName(input string) (apitypes.NetworkResource, error) {
```
Comment (tiborvass) [inline daemon/cluster/cluster.go]: rename `input` to `name`

File: daemon/cluster/cluster.go (hunk 3 above)
Comment (AkihiroSuda) [inline daemon/cluster/cluster.go]: done

File: daemon/cluster/cluster.go (hunk 4 above)
Comment (AkihiroSuda) [inline daemon/cluster/cluster.go]: done

File: api/server/router/network/network_routes.go (hunk 2 above)
Comment (AkihiroSuda) [inline api/server/router/network/network_routes.go]: hmm, probably in another PR?

**Comment by AkihiroSuda** [comment]
updated PR, about @tiborvass 's comments

**Comment by AkihiroSuda** [comment]
rebased

File: api/server/router/network/network_routes.go (hunk 2 above)
Comment (thaJeztah) [inline api/server/router/network/network_routes.go]: Yes, that makes sense, then we can confirm if it should be fixed / changed on that PR

**Comment by thaJeztah** [comment]
One problem with this change, is that a name can now mask an ID. Although I don't think that's a problem during _create_, we should probably fix other locations where we accept both ID's, ID-prefixes, and names.


For example;

```bash
$ docker network create foo

c7e93379f7ea502d12962076c7b61707a20fc95c3b7ddf425b6b125e9e1d5d9b

$ docker network create 7e93379f7ea502d12962076c7b61707a20fc95c3b7ddf425b6b125e9e1d5d9b

021dec6c2411ce0000ce353c0864b6e3c91370b57fa5f4b1ddd57023b6fdccef


$ docker network inspect --format '{{.Name}}' c7e93379f7ea502d12962076c7b61707a20fc95c3b7ddf425b6b125e9e1d5d9b

c7e93379f7ea502d12962076c7b61707a20fc95c3b7ddf425b6b125e9e1d5d9b
```

When doing an `docker network inspect` or `docker network rm`, the _name_ should not be able to mask the ID.

**Comment by thaJeztah** [comment]
Hm, actually, looks like this was already a problem on 1.12, because docker only detected overlap between name and ID if the network is actively used 😞

**Comment by thaJeztah** [comment]
Ok, there's definitely something strange happening with this patch;

With this patch, I'm able to create two networks with the same name;

```bash
$ docker network create -d overlay test
tpy1z4pnimt6hsxajozbzqrsc

$ docker network create test
de2771fb0c5775ec6a2b06fe2746b50959c19a25fa01ab9ab39fb9c2dedf62d7
```


Now, create a service using that network

```bash
$ docker service create --name test --network test nginx:alpine
pok49r96pen6djpmsco1wml5k
```

Wait until the service is up and running;


```bash
docker service ls
ID            NAME  MODE        REPLICAS  IMAGE
pok49r96pen6  test  replicated  1/1       nginx:alpine
```


Then check the networks that are present;

```bash
$ docker network ls

NETWORK ID          NAME                DRIVER              SCOPE
049959e5a946        bridge              bridge              local
bf45d394e7ca        docker_gwbridge     bridge              local
08548c9193b7        host                host                local
pblmrxr04g50        ingress             overlay             swarm
0ea5ebe575d2        none                null                local
tpy1z4pnimt6        test                overlay             swarm
```


The "bridge" network disappeared! Trying to access it by ID, also
produces an error;

```bash
$ docker network inspect de2771fb0c5775ec6a2b06fe2746b50959c19a25fa01ab9ab39fb9c2dedf62d7
[]
Error: No such network: de2771fb0c5775ec6a2b06fe2746b50959c19a25fa01ab9ab39fb9c2dedf62d7
```

**Comment by thaJeztah** [comment]
Note that in the last situation, the network originally appeared in the list, but disappeared once the service is up and running.

Starting the service also takes a lot longer; I haven't checked the daemon logs, but I suspect it tries using the "bridge" network, which fails, and then tries the "overlay" network (possibly multiple times, because I see a lot of failures hoping up in the logs)

**Comment by AkihiroSuda** [comment]
@thaJeztah thank you a lot for testing!
I'll look into that..

Also, I found that `docker network create test & docker network create test` creates multiple networks with the same name (v.1.12.2) https://github.com/docker/docker/issues/29268
Probably we need to completely rewrite the store for network names

**Comment by aaronlehmann** [comment]
```
daemon/cluster/cluster.go:1392:1: comment on exported method Cluster.GetNetworksByName should be of the form "GetNetworksByName ..."
```

**Comment by AkihiroSuda** [comment]
Now CI green

**Review by thaJeztah — APPROVED** [review]
LGTM

we should probably address https://github.com/docker/docker/pull/27938#issuecomment-265762425 though (in a separate PR)

**Comment by thaJeztah** [comment]
oh, and needs a rebase :cry:

File: integration-cli/docker_cli_swarm_test.go [hunk 5]
```diff
@@ -1358,3 +1358,49 @@ func (s *DockerSwarmSuite) TestSwarmNetworkIPAMOptions(c *check.C) {
...
+	// (ingressID in this case)
+	newNetName := ingressID[0:2]
+	out, err = d.Cmd("network", "create", "--driver", "overlay", newNetName)
+	// In #27866, it was failing because of "network with name %s already exists"
+	c.Assert(err, checker.IsNil, check.Commentf("out: %v", out))
+	out, err = d.Cmd("network", "rm", newNetName)
+	c.Assert(err, checker.IsNil, check.Commentf("out: %v", out))
+}
+
+// Test case for https://github.com/docker/docker/pull/27938#issuecomment-265768303
```
Comment (vdemeester) [inline integration-cli/docker_cli_swarm_test.go]: Would be cool if there could also be a description on what it does 👼 (linking the issue is 👍, but it would be even better with a small explanation so the reader doesn't have to necessary open his browser to know why it's there 👼)

Same above for `TestSwarmNetworkCreateIssue27866`

File: integration-cli/docker_cli_swarm_test.go [hunk 6]
```diff
@@ -1358,3 +1358,49 @@ func (s *DockerSwarmSuite) TestSwarmNetworkIPAMOptions(c *check.C) {
...
+	out, err = d.Cmd("network", "create", name)
+	c.Assert(out, checker.Contains,
+		fmt.Sprintf("network with name %s already exists", name))
+	c.Assert(err, checker.NotNil)
+	out, err = d.Cmd("network", "rm", name)
+	c.Assert(err, checker.IsNil, check.Commentf("out: %v", out))
+}
+
+// Reversed case for TestSwarmNetworkCreateDup
+func (s *DockerSwarmSuite) TestSwarmNetworkCreateDup2(c *check.C) {
```
Comment (vdemeester) [inline integration-cli/docker_cli_swarm_test.go]: Pretty sure these 2 tests could be on the same one 👼

**Review by vdemeester — CHANGES_REQUESTED** [review]
Two small comments (that could be seen as nits) but otherwise looks good

**Comment by thaJeztah** [comment]
ping @AkihiroSuda this needs a rebase, also, could you address @vdemeester's comments, then we should be ready to merge for 1.13.0-rc4

**Comment by AkihiroSuda** [comment]
@thaJeztah @vdemeester updated PR, sorry for being late 😅

File: integration-cli/docker_cli_swarm_test.go (hunk 5 above)
Comment (vdemeester) [inline integration-cli/docker_cli_swarm_test.go]: :heart:

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by thaJeztah** [comment]
all green 💚
