### PR TITLE
Windows: Fix COPY file . after WORKDIR

### LINKED ISSUE #27545: Inconsistent Dockerfile behavior between Windows Containers and Linux
**Description**

It appears the Windows Containers behavior of the `COPY` command is slightly different than on Linux when the destination is `.`

**Steps to reproduce the issue:**
1. Get a working Windows Container environment.
2. Create a directory with some files with one of them named `project.json`
3. Add the following Dockerfile to the directory.  Note:  This is a simplified Dockerfile.  In the real usage there are commands in between the COPY commands that don't need to be re-run if the project.json doesn't change.

```
FROM microsoft/nanoserver

WORKDIR app
COPY project.json .
COPY . .
```

**Describe the results you received:**
Output of building is:

```
Sending build context to Docker daemon 6.144 kB
Step 1/4 : FROM microsoft/nanoserver
 ---> 105d76d0f40e
Step 2/4 : WORKDIR app
 ---> Using cache
 ---> 5c0466311dc7
Step 3/4 : COPY project.json .
 ---> Using cache
 ---> 0d4a942fa0c6
Step 4/4 : COPY . .
mkdir \\?\Volume{c0949f92-8c99-11e6-b9a3-adda2ced055a}\app: The system cannot find the path specified.
```

**Describe the results you expected:**
The same Dockerfile with the exception of `FROM debian:jessie` builds and produces the expected results (all files are copied into the app dir) in my Ubuntu environment.

**Additional information you deem important (e.g. issue happens only occasionally):**
There are two ways to get the Dockerfile to work on Windows Containers
1. Add `RUN mkdir c:\app` before the `WORKDIR` command
2. Change the two `COPY` destinations to `./` 

**Output of `docker version`:**

```
Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
Containers: 18
 Running: 1
 Paused: 0
 Stopped: 17
Images: 302
Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.206.amd64fre.rs1_release.160915-0644)
Operating System: Windows Server 2016 Standard Evaluation
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 1.159 GiB
Name: WIN-F6RFOUBH784
ID: R644:EESZ:OP6H:7Z62:UABL:VAFV:7TZC:BIR7:KXD7:ISDG:SP37:FXUY
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

Fixes #27545. @duglin @thaJeztah @friism 

This fixes the last of the problems reported in the above issue, specifically on Windows where `COPY somefile .` after a `WORKDIR` statement where the workdir does not previously exist in the image, copied the contents of `somefile` to a filename of the WORKDIR, rather than a file in the folder of the WORKDIR. This change makes the builder on Windows consistent with Linux. Test case added too. 

(Another fix for the overall issue from @duglin at https://github.com/docker/docker/pull/27873)

@MichaelSimons @StefanScherer FYI

### CODE REVIEW

**Comment by jhowardmsft** [comment]
cc @johnstep

**Comment by StefanScherer** [comment]
That's great to have the same experience on both platforms. Seems to have an issue with  `TestBuildWindowsAddCopyPathProcessing`.

**Comment by jhowardmsft** [comment]
Fixed.

File: integration-cli/docker_cli_build_test.go [hunk 1]
```diff
@@ -1865,10 +1865,6 @@ func (s *DockerSuite) TestBuildWindowsWorkdirProcessing(c *check.C) {
 func (s *DockerSuite) TestBuildWindowsAddCopyPathProcessing(c *check.C) {
 	testRequires(c, DaemonIsWindows)
 	name := "testbuildwindowsaddcopypathprocessing"
-	// TODO Windows (@jhowardmsft). Needs a follow-up PR to 22181 to
```
Comment (MHBauer) [inline integration-cli/docker_cli_build_test.go]: Is this To Done? Somewhere else?

Comment (jhowardmsft) [inline integration-cli/docker_cli_build_test.go]: Still todo. Nothing to do with this PR.

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by johnstep** [comment]
I applied the patch and ran a test that works on Linux (changing `FROM`, of course):

```
FROM microsoft/nanoserver
WORKDIR x
COPY Dockerfile .
COPY . .
```

With this patch, building still fails on Windows but with a different error:

`Cannot mkdir: C:\x is not a directory`

Before this patch, the error was:

`mkdir \\?\Volume{<guid>}\x: The system cannot find the path specified.`

**Comment by jhowardmsft** [comment]
`x` isn't a directory. Use `WORKDIR c:\x`

**Comment by thaJeztah** [comment]
isn't `WORKDIR` relative to the current location? (i.e. relative to `C:\` if that's the current path)

**Comment by thaJeztah** [comment]
(https://github.com/docker/docker/issues/3937, https://github.com/docker/docker/pull/4691)

**Comment by jhowardmsft** [comment]
```
PS E:\docker\build\27545> type .\Dockerfile
# escape=`

FROM nanoserver
WORKDIR c:\app
COPY project.json .
COPY . .
PS E:\docker\build\27545> docker build --no-cache .
Sending build context to Docker daemon 4.096 kB
Step 1/4 : FROM nanoserver
 ---> 22738ff49c6d
Step 2/4 : WORKDIR c:\app
 ---> Running in ca6f39443a60
 ---> 6f59f9c15693
Removing intermediate container ca6f39443a60
Step 3/4 : COPY project.json .
 ---> 5c7225b4083f
Removing intermediate container c441b1b1e8fe
Step 4/4 : COPY . .
 ---> 9b9dfa6fcd22
Removing intermediate container 74747f9e78dd
Successfully built 9b9dfa6fcd22
PS E:\docker\build\27545> docker run --rm 5c7 cmd /s /c dir c:\
 Volume in drive C has no label.
 Volume Serial Number is 7E6D-E0F7

 Directory of c:\

10/31/2016  10:55 AM    <DIR>          app
10/05/2016  05:04 PM             1,894 License.txt
10/05/2016  02:22 PM    <DIR>          Program Files
10/05/2016  02:14 PM    <DIR>          Program Files (x86)
10/31/2016  10:56 AM    <DIR>          Users
10/31/2016  10:56 AM    <DIR>          Windows
               1 File(s)          1,894 bytes
               5 Dir(s)  21,258,801,152 bytes free
PS E:\docker\build\27545> docker run --rm 5c7 cmd /s /c dir c:\app
 Volume in drive C has no label.
 Volume Serial Number is 7E6D-E0F7

 Directory of c:\app

10/31/2016  10:55 AM    <DIR>          .
10/31/2016  10:55 AM    <DIR>          ..
10/28/2016  09:04 AM                14 project.json
               1 File(s)             14 bytes
               2 Dir(s)  21,262,458,880 bytes free
PS E:\docker\build\27545> docker run --rm 9b9 cmd /s /c dir c:\app
 Volume in drive C has no label.
 Volume Serial Number is 7E6D-E0F7

 Directory of c:\app

10/31/2016  10:55 AM    <DIR>          .
10/31/2016  10:55 AM    <DIR>          ..
10/31/2016  10:53 AM                76 Dockerfile
10/28/2016  09:04 AM                14 project.json
10/28/2016  09:04 AM                14 somefile
               3 File(s)            104 bytes
               2 Dir(s)  21,259,091,968 bytes free
PS E:\docker\build\27545> dir


    Directory: E:\docker\build\27545


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       10/31/2016  10:53 AM             76 Dockerfile
-a----       10/28/2016   9:04 AM             14 project.json
-a----       10/28/2016   9:04 AM             14 somefile


PS E:\docker\build\27545>
```

**Comment by jhowardmsft** [comment]
Good point, yes, it can be relative.  But it's working for me on master which contains this patch:

```
PS E:\docker\build\27545> docker build --no-cache .
Sending build context to Docker daemon 4.096 kB
Step 1/3 : FROM nanoserver
 ---> 22738ff49c6d
Step 2/3 : WORKDIR app
 ---> Running in e64f41b44c12
 ---> 87d35195ee95
Removing intermediate container e64f41b44c12
Step 3/3 : COPY project.json .
 ---> d922038bdfe9
Removing intermediate container c7a5148e9468
Successfully built d922038bdfe9
PS E:\docker\build\27545> docker run --rm d922 cmd /s /c dir c:\
 Volume in drive C has no label.
 Volume Serial Number is 7E6D-E0F7

 Directory of c:\

10/31/2016  10:57 AM    <DIR>          app
10/05/2016  05:04 PM             1,894 License.txt
10/05/2016  02:22 PM    <DIR>          Program Files
10/05/2016  02:14 PM    <DIR>          Program Files (x86)
10/31/2016  10:57 AM    <DIR>          Users
10/31/2016  10:57 AM    <DIR>          Windows
               1 File(s)          1,894 bytes
               5 Dir(s)  21,259,096,064 bytes free
PS E:\docker\build\27545> docker run --rm d922 cmd /s /c dir c:\app
 Volume in drive C has no label.
 Volume Serial Number is 7E6D-E0F7

 Directory of c:\app

10/31/2016  10:57 AM    <DIR>          .
10/31/2016  10:57 AM    <DIR>          ..
10/28/2016  09:04 AM                14 project.json
               1 File(s)             14 bytes
               2 Dir(s)  21,259,087,872 bytes free
PS E:\docker\build\27545>
```

```
PS E:\docker\build\27545> docker version
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   a0629ea-jhoward-JHOWARD-Z420-Dynamic
 Built:        Mon Oct 31 17:54:28 UTC 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   a0629ea-jhoward-JHOWARD-Z420-Dynamic
 Built:        Mon Oct 31 17:54:28 UTC 2016
 OS/Arch:      windows/amd64
 Experimental: false
```

**Comment by jhowardmsft** [comment]
https://github.com/docker/docker/commit/a0629eab7302bef57c9ce9930b24f59f751303d7

**Comment by johnstep** [comment]
It works if I add the backtick escape directive:

```
# escape `

FROM microsoft/nanoserver
WORKDIR x
COPY Dockerfile .
COPY . .
```

**Comment by johnstep** [comment]
@jhowardmsft Has there been discussion on changing the default escape character for Windows? Unfortunately, without versioning, I guess that would break many existing Dockerfiles.

**Comment by jhowardmsft** [comment]
Yes, discussed significantly in the PR to introduce it. There were many reasons to keep the default as `\` on Windows and Linux.

**Comment by jhowardmsft** [comment]
@johnstep Works for me (as it should do here as there's no / \ ambiguity in this Dockerfile) regardless of the parser directive. Here's without (again running master):

```
PS E:\docker\build\27545> type dockerfile
FROM nanoserver
WORKDIR app
COPY project.json .
COPY . .
PS E:\docker\build\27545> docker build --no-cache .
Sending build context to Docker daemon 4.096 kB
Step 1/4 : FROM nanoserver
 ---> 22738ff49c6d
Step 2/4 : WORKDIR app
 ---> Running in d660dbb89d79
 ---> 7e798a746f69
Removing intermediate container d660dbb89d79
Step 3/4 : COPY project.json .
 ---> 02656319e083
Removing intermediate container 463f8466e7c9
Step 4/4 : COPY . .
 ---> ae581ab31c0e
Removing intermediate container ea97d4e8f5e1
Successfully built ae581ab31c0e
PS E:\docker\build\27545> docker run --rm 026 cmd /s /c dir c:\app
 Volume in drive C has no label.
 Volume Serial Number is 7E6D-E0F7

 Directory of c:\app

10/31/2016  02:09 PM    <DIR>          .
10/31/2016  02:09 PM    <DIR>          ..
10/28/2016  09:04 AM                14 project.json
               1 File(s)             14 bytes
               2 Dir(s)  21,262,458,880 bytes free
PS E:\docker\build\27545> docker run --rm ae58 cmd /s /c dir c:\app
 Volume in drive C has no label.
 Volume Serial Number is 7E6D-E0F7

 Directory of c:\app

10/31/2016  02:09 PM    <DIR>          .
10/31/2016  02:09 PM    <DIR>          ..
10/31/2016  02:06 PM                59 Dockerfile
10/28/2016  09:04 AM                14 project.json
10/28/2016  09:04 AM                14 somefile
               3 File(s)             87 bytes
               2 Dir(s)  21,259,100,160 bytes free
PS E:\docker\build\27545> dir


    Directory: E:\docker\build\27545


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       10/31/2016   2:06 PM             59 Dockerfile
-a----       10/28/2016   9:04 AM             14 project.json
-a----       10/28/2016   9:04 AM             14 somefile


PS E:\docker\build\27545>
```

**Comment by johnstep** [comment]
It worked fine when I rebuilt with `--no-cache`; no issues here. Thanks!
