### PR TITLE
Fix service inspect --pretty

### LINKED ISSUE #24601: Cleanup docker service inspect
docker service inspect contains fields that do not exist. In `--pretty` mode, it also displays fields that have no value which provide little use but make the output harder on the eyes.

```
Placement:
 Strategy:	Spread
```

Placement strategy has been removed from SwarmKit. We should remove it from engine-api and inspect. /cc @dongluochen 

```
UpdateConfig:
 Parallelism:	0
```

In this case, the update config hasn't been set. I assume we're unable to make the difference between `0` and `default value` so I don't think there's anything we can do, right?

```
Resources:
Reservations:
Limits:
```

First of all, `Reservations` and `Limits` should be nested below Resources.

Also, when empty, we should probably not display them. For instance, when `Reservations` is empty, we skip it. If both `Reservations` and `Limits` are empty, we should skip the entire `Resources` section.

```
Ports:
 Name =
```

Is there even a way to name a port through the API/CLI? Should we remove the `name` altogether from the CLI? API? SwarmKit? /cc @mrjana @mavenugo 

/cc @vieux @dnephin @icecrime

### PR DESCRIPTION
**Pull request by dongluochen**
Fix #24601.

Signed-off-by: Dong Chen dongluo.chen@docker.com

### CODE REVIEW

**Comment by vieux** [comment]
LGTM

File: api/client/service/inspect.go [hunk 1]
```diff
@@ -114,23 +113,27 @@ func printService(out io.Writer, service swarm.Service) {
...
+				fmt.Fprintf(out, "  Memory:\t\t%s\n", units.BytesSize(float64(r.MemoryBytes)))
 			}
 		}
-		if service.Spec.TaskTemplate.Resources.Reservations != nil {
-			fmt.Fprintln(out, "Reservations:")
-			printResources(out, service.Spec.TaskTemplate.Resources.Reservations)
+
+		if resources.Reservations != nil &&
+			(resources.Reservations.NanoCPUs != 0 || resources.Reservations.MemoryBytes != 0) {
+			fmt.Fprintln(out, " Reservations:")
```
Comment (aaronlehmann) [inline api/client/service/inspect.go]: Cosmetic suggestion: fold this stuff into `printResources` and add an argument for the heading. Then this part of the code becomes

```go
printResources(out, "Reservations", resources.Reservations)
printResources(out, "Limits", resources.Limits)
```

I think it will make the code simpler, especially if we add more resource types in the future.

**Comment by aaronlehmann** [comment]
LGTM

File: api/client/service/inspect.go (hunk 1 above)
Comment (dongluochen) [inline api/client/service/inspect.go]: I like it as it reduces code.

**Comment by vdemeester** [comment]
LGTM 🐸
