### PR TITLE
Set 127GB default sandbox size for WCOW, and ensure storage-opts is honoured on all paths under WCOW and LCOW

### LINKED ISSUE #37352: COPY step fails on Windows when the size is greater than 20GB.
**Description**

Normally the default layer size for Windows is set as 127GB by default with #35925. However, on this line: https://github.com/moby/moby/blob/8e610b2b55bfd1bfa9436ab110d311f5e8a74dcb/daemon/images/image_builder.go#L56 `CreateRWLayerOpts` is sent as nil. So the storage options are not in effect.

### PR DESCRIPTION
**Pull request by TBBle**
**- What I did**

* Applied the 127GB WCOW default sandbox size for `RUN` (introduced in #35925) to all WCOW sandboxes.
* * Also ensured this default applies whether WCOW was chosen by explicit `--platform windows` or by image-based or defaulted platform choice.
* Ensures the `storage-opts` overrides the 127GB default sandbox size when both are applied.
* * Supplants: #40256
* * Addresses: https://github.com/moby/moby/issues/34947#issuecomment-510078008
* Applied the `storage-opts` setting for _dockerd.exe_ to all WCOW and LCOW sandboxes, not just the ones underlying a container, i.e. not just `RUN` and `docker run`.
* * This means we validate `lcow.sandboxsize` (it cannot be less than 20GB) at startup rather than waiting until someone runs a container.
* * Fixes: #37352
* * Another occurrence: https://github.com/adamrehn/ue4-docker/issues/99#issuecomment-706268305 onwards.

**- How I did it**

* Moved the 127GB WCOW default from the Builder internals to the Windows Filter GraphDriver.
* Processed daemon `storage-opts` in the Windows Filter and LCOW GraphDrivers `initfn` instead of merging them into the container-creation parameters.
* Worked around the limited storage on the Windows RS5 Jenkins build node by detecting when the test passed but the container build failed, see 695b151a18299ade7c70dfe3babc8d77b7f5aba6.

TODO: Update the [documentation](https://docs.docker.com/engine/reference/commandline/dockerd/#size) for the new effective default value of `--storage-opts size`. [Source](https://github.com/docker/cli/blob/master/docs/reference/commandline/dockerd.md).

**- How to verify it**

* Added `TestBuildWCOWSandboxSize` to the integration test suite
* * Creates a 21GB file (and immediately deletes it) to confirm the `RUN` sandbox is > 20GB.
* * Attempts to copy three 7GB files from a previous layer into a new layer, to confirm the `COPY` sandbox is > 20GB.
* Manual testing of storage-opts can be done either by hand, or using the `DOCKER_STORAGE_OPTS` env-var for the integration test script. Setting `size=20GB` will cause `TestBuildWCOWSandboxSize` to fail.
* * If the first failure line (the `RUN fsutil && delete` call) is deleted, it should then also fail on the last step (the `COPY --from`).
* * This test could be split into two, one for the `RUN` sandbox and one for the `COPY` sandbox, if that's useful. The `RUN` test has almost-zero time or space overhead where it is, as fsutil creates an empty file, and we delete it before it's archived into a layer.
* * TODO: Think of some way to automate this? To adjust `DOCKER_STORAGE_OPTS` for CI, we'd need a separate pipeline stage. That probably needs separate discussion. And special tests that detect correctly running out of space in `docker build`.
* Manual testing with `docker run --isolation=hyperv -it --rm mcr.microsoft.com/windows/servercore:2004` showed that storage-opts was taking effect, and if not supplied, a 127GB sandbox was used.

**- Description for the changelog**

On Windows, all WCOW read-write layers default to 127GB of free space (up from 20GB in most cases), and all WCOW and LCOW layers will honour the [`size` option](https://docs.docker.com/engine/reference/commandline/dockerd/#size) and [`lcow.sandboxsize` option](https://docs.docker.com/engine/reference/commandline/dockerd/#lcowsandboxsize) (repsectively) in the daemon's `storage-opts` configuration

**- A picture of a cute animal (not mandatory but encouraged)**

[](https://imgur.com/1oMXHEo)

### CODE REVIEW

**Comment by TBBle** [comment]
In case we want it later, [Jenkins build #8](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-41636/8/pipeline/262) (b266896) replicates #37352 in an integration test. So now I just need to fix it. ^_^

**Comment by TBBle** [comment]
Annoyingly, [Build #17](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-41636/17/pipeline/330) shows it successfully passed the test of `COPY` getting a sandbox obeying the 127GB allowance, but it then failed while archiving the resulting 21GB layer:

> re-exec error: exit status 1: output: write \\\\\\\\?\\\\D:\\\\CI\\\\PR-41636\\\\17\\\\daemon\\\\tmp\\\\hcs198867335\\\\Files\\\\stuff\\\\bigfile_1.txt: There is not enough space on the disk.

(`re-exec` is used only for `writeLayer`, and the directory here is the temporary directory created by hcsshim's `LegacyLayerWriter` to stream the data out to as a source for the tarstream)

The expected failure for "COPY got a 20GB sandbox" is visible in [build 8](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-41636/8/pipeline/262):

> failed to copy files: failed to copy directory: write \\\\\\\\?\\\\Volume{7981a97f-1f77-11eb-b13e-e3f2701e02c7}\\\\stuff\\\\bigfile_3.txt: There is not enough space on the disk.

I _suspect_ I actually ran out of disk space on the test node there. I'm not sure what to do about that, if that's something we have control over? Given that the files being created are all-zeroes, we should only have taken about 42GB of disk space: 21GB for the WCOW Layer, another 21GB for the temp directory, and we ran out of space in the last third of that last 21GB.

Anyway, that demonstrates "Moved the 127GB WCOW default from the Builder internals to the Windows Filter GraphDriver." worked, so I'll consider this part "tested".

**Comment by TBBle** [comment]
Validation failures in CI are inherited from #41638 (See https://github.com/moby/moby/pull/41638#issuecomment-722418448)

**Comment by TBBle** [comment]
Looks ready-for-review. The only CI failure was from s390x, which shouldn't have been affected by anything I did, and hasn't failed before now.
```
=== RUN   TestDiff
--- FAIL: TestDiff (0.88s)
    diff_test.go:42: assertion failed: 
        --- expected
        +++ items
        {[]container.ContainerChangeResponseItem}[1->?]:
        	-: container.ContainerChangeResponseItem{Kind: 0x01, Path: "/foo/bar"}
        	+: <non-existent>
```

**Comment by TBBle** [comment]
Rebased on #41638, and pulled in a minor change called out as a nit on #41638 (in Linux integration tests) that was not corrected before merging.

All jobs have passed, except the Win-RS5 test which appears to be stalled waiting to start. [It passed on the previous run](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-41636/22/pipeline/191), and [almost every file changed in the rebase](https://github.com/moby/moby/compare/f059b68d3428653fecd0dbbea6342378296fe782..1571e9331b4c56cc350bdf339b9aacd72eb3bbbd) is immaterial to the Windows build, being tagged `linux` or `unix`.

**Comment by TBBle** [comment]
@thaJeztah I have a process question: Is there anything I'm overlooking doing to get this PR reviewed. I'd really like to land it in 20.10, since it's a user-facing behaviour change, and unblocks a long-standing issue in https://github.com/adamrehn/ue4-docker/ which has become more-important due to the increasing size of UE4 builds.

**Comment by TBBle** [comment]
Since 20.10 shipped, is there any chance of this going into a 20.10 point-release, or will it be too-large a change, and hence waiting for a 21.x release?

**Comment by tianon** [comment]
Conceptually this seems sane; what's the downside?

(In other words, why was this defaulted so much lower previously?)

**Comment by TBBle** [comment]
The 20GB default is what happens if you ask HCS to create you a sandbox and don't then resize it. Someone at MS picked a random number sometime before 2016, perhaps. It is a nice, round number, and doesn't seem too terrifyingly large, or painfully small.

[The documented rationale](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-storage#storage-limits) leaves a lot to be desired:
> A common pattern for Windows applications is to query the amount of free disk space before installing or creating new files or as a trigger for cleaning up temporary files. With the goal of maximizing application compatibility, the C: drive in a Windows container represents a virtual free size of 20GB.

ECR caps image layers at 10GB (which is super-annoying...), which matches the devicemapper graphdriver base image size, so 20GB looks positively generous in the right contexts.

I'm not aware of any downside to this change, unless perhaps people were relying on the 20GB default size to prevent runaway disk consumption on the backing drive.

I checked and the _sandbox.vhdx_ file created doesn't consume the full 20GB (the vhdx is about 4MB when created, is temporarily larger when mounted (37MB), and when unmounted (without doing anything else) shrinks back down to about 9MB, so the "differencing VHDX" fileformat doesn't appear to be going to blow out with this change. And I probably would have noticed, as I don't have 127GB free on the drive where I developed and tested this PR. It might be _proportionally_ larger, if it's tracking something that scales with storage size, perhaps. I don't happen to have a larger sandbox at-hand to check.

Perhaps those who had tried to change this default in the past were bitten by https://github.com/microsoft/hcsshim/issues/708 and gave up...

#35925 _should_ have caused that bug to be seen often, but I suspect most people (including the Docker CI pipeline...) were not passing `--platform windows`, and so #35925's change was not effective for them. For those who were passing `--platform windows`, perhaps they saw https://github.com/microsoft/hcsshim/issues/708 and just stopped doing so.

**Comment by tianon** [comment]
Thank you, that makes sense, and sounds like it brings us closer to how Linux works (unless you're using devicemapper, which we try not to talk too loudly about 😅).

**Review by tianon — APPROVED** [review]
Changes LGTM, but I'm not sure I'm the right person to review all these changes 😇

**Comment by TBBle** [comment]
Who would be the right person to review these changes? We're already unable to build the latest Unreal Engine, as its output size is over 20GB on Windows, and each release seems larger than the last.

File: integration/container/mounts_linux_test.go [hunk 1]
```diff
@@ -285,15 +285,15 @@ func TestContainerVolumesMountedAsShared(t *testing.T) {
 
 	// Convert this directory into a shared mount point so that we do
 	// not rely on propagation properties of parent mount.
```
Comment (thaJeztah) [inline integration/container/mounts_linux_test.go:287]: Looks like this comment was no longer matching what was actually done?
```suggestion
	// Convert this directory into a private mount point so that we do
	// not rely on propagation properties of parent mount.
```

File: integration/container/mounts_linux_test.go [hunk 2]
```diff
@@ -342,15 +342,15 @@ func TestContainerVolumesMountedAsSlave(t *testing.T) {
...
```
Comment (thaJeztah) [inline integration/container/mounts_linux_test.go:344]: Same here?

```suggestion
	// Convert this directory into a private mount point so that we do
	// not rely on propagation properties of parent mount.
```

File: integration/container/mounts_linux_test.go (hunk 1 above)
Comment (thaJeztah) [reply integration/container/mounts_linux_test.go:287]: Actually; wondering if this last commit should be in this PR, as it doesn't look related to the change itself 😅  (not a blocker though)

**Review by thaJeztah — CHANGES_REQUESTED** [review]
oops, sorry, thought I reviewed already; left some nits on the last commit (also feel free to open it separately if you want to unblock this PR), LGTM otherwise

File: integration/container/mounts_linux_test.go (hunk 1 above)
Comment (TBBle) [reply integration/container/mounts_linux_test.go:287]: No, it's still shared. This change is just a refactoring:

> `mount.Mount(X,X, "none", "bind,private")` => `mount.MakePrivate(X)`

and

> `mount.Mount("none", X, "none", "shared")` => `mount.MakeShared(X);`

In both cases, it generates 3 mount syscalls: `bind`, `private`, `shared` on that path.

The _final_ result is a 'shared' mount (so others mounting this will see mounts done here or there), but which is not receiving any mount changes from its parent tree.

You're right, it's not part of this change. It's a minor cleanup that was pointed out to me in #41638 (where I moved these tests from integration-cli to integration) _after_ that was merged. Or rather, the comment was made before it was merged, but I didn't see the comment until after it was merged.

Comment (thaJeztah) [reply integration/container/mounts_linux_test.go:287]: Ah, yes, that's definitely confusing. I think what makes it confusing is that the comment is associated with he first of those mounts (`mount.MakePrivate`), which is only the first step; perhaps we should rephrase it somewhat to outline the steps (bind -> private -> shared).

Anyway; it's indeed not something new, so let's keep that for a follow-up

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by TBBle** [comment]
Awesome, thank you for landing this.

Is there anything I can or should do to help this get into 20.10.3, or will that process proceed simply from the milestone tag, and I should just wait and see?

**Comment by thaJeztah** [comment]
We'll go through PR's that were merged and look what to include in upcoming patch releases 👍

**Comment by slonopotamus** [comment]
@thaJeztah could you please comment on whether this PR got into 20.10.x releases? I currently see that is has 20.10.3 milestone as labelled with `process/cherry-pick`, but 20.10.3 was already released and according to its changelog, it doesn't contain changes from current PR.

**Comment by TBBle** [comment]
It shows the 21.xx milestone, [updated on February 3rd](https://github.com/moby/moby/pull/41636#event-4279392018).

**Comment by slonopotamus** [comment]
Oh, I misread it somehow, sorry.

**Comment by TBBle** [comment]
Yeah, the GitHub change log can be confusing. Every time I see
image
I have to check if the change was 'added' or 'removed', because GitHub doesn't distinguish them. >_< In this case, the first was removed, the second was added.

**Comment by wbudd** [comment]
@TBBle I see. Thanks for the heads up. That's a very _patient_ release cycle.

(And sorry 'bout the snarkiness of my prev comment. Getting bitten by this limit was a bit frustrating yesterday, but in general I do of course appreciate all the work you guys put in creating all the Docker tooling that (mostly) makes my life as a dev a lot less painful than I'm sure it otherwise would be!)
