### PR TITLE
correct handling of volumes while service update.

### LINKED ISSUE #25772: service update "--mount-add" fails with "duplicate mount point"
Updating a service to replace a volume with a different volume fails with "duplicate mount point"

To reproduce:

``` bash
$ docker service create --name=foo --mount type=volume,source=volume1,target=/foo nginx:alpine
foo

$docker service update --mount-add type=volume,source=volume2,target=/foo foo
foo
```

Then see tasks failing:

``` bash
$ docker service ps foo

ID                         NAME             IMAGE         NODE          DESIRED STATE  CURRENT STATE            ERROR
0c7uelw2fk0qkeneww14g553m  foo.1      nginx:alpine  7e44720a5b2a  Ready          Rejected 1 second ago    "Duplicate mount point '/foo"
ckhrp1iq2rh5ehabqxw5992e2   \_ foo.1  nginx:alpine  7e44720a5b2a  Shutdown       Rejected 6 seconds ago   "Duplicate mount point '/foo"
38ycpjw10baw0lyfr7sjuhnul   \_ foo.1  nginx:alpine  7e44720a5b2a  Shutdown       Rejected 11 seconds ago  "Duplicate mount point '/foo"
1mz8x3nwhj3hrxtjlbtbic9y3   \_ foo.1  nginx:alpine  7e44720a5b2a  Shutdown       Rejected 16 seconds ago  "Duplicate mount point '/foo"
0k3oycgrzzurzoi8pvjg6teg0   \_ foo.1  nginx:alpine  7e44720a5b2a  Shutdown       Rejected 20 seconds ago  "Duplicate mount point '/foo"
```

``` bash
$ docker inspect 0c7uelw2fk0qkeneww14g553m
...
"Status": {
    "Timestamp": "2016-08-16T21:09:40.972455571Z",
    "State": "rejected",
    "Message": "preparing",
    "Err": "Duplicate mount point '/foo'",
    "ContainerStatus": {}
},
...
```

Tested on current master, https://github.com/docker/docker/commit/641e1564cfeb3f94f68f3c43a353df10331afecf

### PR DESCRIPTION
**Pull request by kunalkushwaha**
**\- What I did**
Fixed #25772, with proper handling of volume mount data in `docker service update` command.

i.e. while building `docker service update` container Specs, check if volume(mount target) already exists, delete the existing mount data and append new volume mount data to avoid duplicates entry.

**\- How I did it**
In `api/client/service/update.go`, instead of blindly appending the mount list, check for entry in `mounts` list, and replace it with new entry.
If it doesn't exist append the list.
Function added : `findAndReplaceMountDatamounts *[]mounttypes.Mount, values []mounttypes.Mount) bool`

**\- How to verify it**
Test added as `TestUpdateMountsWithDuplicateMounts`
and also steps from #25772 can be followed.

**\- Description for the changelog**

- `--mount-add` option for `docker service update` handle mount points as expected.

**\- A picture of a cute animal (not mandatory but encouraged)**

Updating a service to replace a volume is handled properly now.
Fixes #25772 

Signed-off-by: Kunal Kushwaha kushwaha_kunal_v7@lab.ntt.co.jp

### CODE REVIEW

**Comment by erikh** [comment]
nice!

**Comment by stevvooe** [comment]
This needs to be done on the swarmkit side.

**Comment by tonistiigi** [comment]
Design-wise this seems like a correct fix for #25770 but not necessarily for #25772 . Is there a swarmkit issue about validating multiple targets?

**Comment by stevvooe** [comment]
I agree, but this needs to be balanced with a server-side validation.

**Comment by thaJeztah** [comment]
ping @stevvooe is there more to be done here, or should swarmkit be fixed first?

**Comment by stevvooe** [comment]
@thaJeztah https://github.com/docker/swarmkit/pull/1500 needs to be merged first.

File: api/client/service/update.go [hunk 1]
```diff
@@ -357,7 +357,12 @@ func removeItems(
 func updateMounts(flags *pflag.FlagSet, mounts *[]mounttypes.Mount) {
 	if flags.Changed(flagMountAdd) {
 		values := flags.Lookup(flagMountAdd).Value.(*MountOpt).Value()
-		*mounts = append(*mounts, values...)
+
+		exist := findAndReplaceMountData(mounts, values)
```
Comment (stevvooe) [inline api/client/service/update.go]: So, mount ordering needs to be consistent for the update. It might be easier to build a target key, add all the mounts, error on duplicate. Then, build the mount set and sort it.

**Review by stevvooe — CHANGES_REQUESTED** [review]

File: api/client/service/update.go (hunk 1 above)
Comment (kunalkushwaha) [inline api/client/service/update.go]: Comments are not clear to me.
- Since here, volume with duplicate target will be updated, so raising error is not required.
- Keeping mount ordering with updates make sense, will make changes for same.

Comment (kunalkushwaha) [inline api/client/service/update.go]: I think, I understood the error for duplicates. It is for input list for update to have duplicate entries. Something similar to updatePorts() function.

Will make necessary changes.

Comment (stevvooe) [inline api/client/service/update.go]:
```
var mountsByTarget map[string]Mount
for _, mount := range mounts {
  if _, ok := mountsByTarget[mount.Target]; ok {
    return fmt.Errorf("duplicate mount target")
  }

  mountsByTarget[mount] = mount
}

var mounts []Mount

for _, mount := range mountsByTarget {
  mounts = append(mounts, mount)
}

sortMountsBySourceThenTarget(mounts)
```

The find and replace isn't really necessary. Just rebuild the dataset correctly.

**Comment by kunalkushwaha** [comment]
Sorry for delay, Will update the PR with suggested changes soon.

File: cli/command/service/update.go [hunk 2]
```diff
@@ -361,20 +363,47 @@ func removeItems(
...
-func updateMounts(flags *pflag.FlagSet, mounts *[]mounttypes.Mount) {
+type byMountSource []mounttypes.Mount
+
+func (m byMountSource) Len() int      { return len(m) }
+func (m byMountSource) Swap(i, j int) { m[i], m[j] = m[j], m[i] }
+func (m byMountSource) Less(i, j int) bool {
+	return m[i].Source < m[j].Source
+}
+
+func updateMounts(flags *pflag.FlagSet, mounts *[]mounttypes.Mount) error {
```
Comment (kunalkushwaha) [inline cli/command/service/update.go]: This was implemented as per rest of functions behavior in this file.
Since the [``updateService()``](https://github.com/docker/docker/blob/master/cli/command/service/update.go#L120) consumes all these function to update the container spec and using out parameter to simplifies the caller code.

Changing behavior of this function only, will look odd in this code, esp ``updaqteMounts()``  is only consumed by ``updateService()``

**Comment by thaJeztah** [comment]
ping @stevvooe PTAL

@kunalkushwaha can you rebase?

**Comment by stevvooe** [comment]
LGTM

File: cli/command/service/update.go [hunk 3]
```diff
@@ -402,20 +404,53 @@ func removeItems(
...
+
 	if flags.Changed(flagMountAdd) {
 		values := flags.Lookup(flagMountAdd).Value.(*opts.MountOpt).Value()
-		*mounts = append(*mounts, values...)
+		for _, mount := range values {
+			if _, ok := mountsByTarget[mount.Target]; ok {
+				return fmt.Errorf("duplicate mount target")
+			}
+			mountsByTarget[mount.Target] = mount
+		}
```
Comment (aaronlehmann) [inline cli/command/service/update.go]: Should we process removals first so that a mount with a given target can be removed and then added again as part of the same command?

Comment (aaronlehmann) [inline cli/command/service/update.go]: Should we process removals before additions so it's possible to remove a mount with a given target and add a new one at the same time? With the current code, it looks like the `--mount-add` corresponding to the removed mount would be ignored by the `toRemove` check.

Comment (kunalkushwaha) [inline cli/command/service/update.go]: true, If ``--mount-rm``  & ``--mount-add`` on same target is specified, it will be ignored. But, the use case seems to be of ``update`` which can be achieved directly using ``--mount-add``, no need to use ``mount-rm``.

**Comment by aaronlehmann** [comment]
LGTM
