### PR TITLE
Revert "Added API to set ephemeral port allocator range."

### LINKED ISSUE #43054: Linux kernel ephemeral port range ignored in Docker 20+
**Description**

According to the "publish" (-P) section of Docker run docs (https://docs.docker.com/engine/reference/run/):
"Docker binds each exposed port to a random port on the host. The range of ports are within an ephemeral port range defined by /proc/sys/net/ipv4/ip_local_port_range."

In Docker versions pre-20, this was correct and working in our environment. However, since upgrading to Docker versions 20+, the kernel ip_local_port_range value is ignored, and Docker instead assigns a port from 49153 through 65535.  This actually affects both the -P option where one publishes all exposed ports, and the -p option where one publishes a single port **and** does not provide a host port. 

I have tested this on Ubuntu Focal, and Flatcar and both exhibit the same behaviour. 

**Steps to reproduce the issue:**
1. Set ip_local_port_range value `sudo sysctl -w net.ipv4.ip_local_port_range="32678 40000"`
2. Make sure docker is stopped and then install docker-ce/docker-ce-cli packages, any 19.X version
3. Start a test container publishing all exposed ports or with a single published port, without providing a host port/host port range. (eg ` docker run -d -p :80 nginx`or `docker run -d -P nginx`)
4. Check the host port assigned with `docker ps` or `docker port`. It will be within 32678-40000 range.
5. Remove container. Stop docker
6. Install docker-ce/docker-ce-cli packages, any 20.X version. Start docker
7. Start a test container publishing all exposed ports or with a single published port, without providing a host port/host port range. (eg. ` docker run -d -p :80 nginx` or `docker run -d -P nginx`)
8. Check the host port assigned with `docker ps` or `docker port`. It will be within 49153-65535 range.

**Describe the results you received:**

A port is assigned from 49153-65535 ephemeral range

**Describe the results you expected:**

A port is assigned from the ephemeral range set by the kernel parameter `/proc/sys/net/ipv4/ip_local_port_range`

**Additional information you deem important (e.g. issue happens only occasionally):**

Our use case here is, we are running many containers on AWS ECS. We would like to control the ports assigned to containers so we can specifically allow these ports through security groups. This is more desirable for us than allowing the whole ephemeral range 32678-65535.

**Output of `docker version`:**

Tested on Ubuntu Focal (I provided minimum 20.10 version, but 20.10.11 also affected)

```
Client: Docker Engine - Community
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        7287ab3
 Built:             Tue Dec  8 18:59:40 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       eeddea2
  Built:            Tue Dec  8 18:57:45 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.4.2-docker)
  scan: Docker Scan (Docker Inc., v0.9.0)

Server:
 Containers: 24
  Running: 3
  Paused: 0
  Stopped: 21
 Images: 42
 Server Version: 20.10.0
 Storage Driver: zfs
  Zpool: xpool
  Zpool Health: ONLINE
  Parent Dataset: xpool/docker
  Space Used By Parent: 3931974144
  Space Available: 131577568768
  Parent Quota: no
  Compression: lz4
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.11.0-27-generic
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 22.97GiB
 Name: ds0377
 ID: 4LGQ:IJGY:AFAY:XS6R:AD6D:JRIE:QX42:D5CD:U74W:34MN:VA7E:G5PV
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 40
  Goroutines: 46
  System Time: 2021-12-01T13:49:21.851318574Z
  EventsListeners: 0
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio weight support
WARNING: No blkio weight_device support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Both AWS ECS (running Flatcar 2983.2.1/docker - 20.10.11) and physical laptop Ubuntu Focal.

### PR DESCRIPTION
**Pull request by akerouanton**
**- What I did**

Since commit 2c4a868f64e6e13bf06589a6670122196651e82e, Docker doesn't
use the value of net.ipv4.ip_local_port_range when choosing an ephemeral
port. This change reverts back to the previous behavior.

Fixes #43054.

**- How to verify it**

1. `make shell`
2. In the container, `sysctl -w net.ipv4.ip_local_port_range="39000 40000"`
3. Start dockerd
4. Run `docker run --rm -it -p 80 nginx`
5. Check what port Docker has picked with `docker ps`

**- Description for the changelog**

`Use the value of net.ipv4.ip_local_port_range when choosing an ephemeral port`

### CODE REVIEW

**Review by neersighted — APPROVED** [review]
This looks really clean from a revert/application standpoint. However, I do wonder if it is desirable to reintroduce the ability to set the range over the API in a way that is documented and falls back to the kernel parameter as a default?

Regardless, this is aligned with the documented behavior and the right move given this has manifested as a regression for users.

**Review by tianon — APPROVED** [review]
I was worried that the removal of `OptionDynamicPortRange` would be a problem, but it looks like it was only ever used in https://github.com/moby/moby/pull/40055 (which is still unmerged). :+1:

**Comment by tianon** [comment]
(This needs a rebase for some conflicts, but they look like they're pretty minor -- just the `imports`, perhaps?)

File: libnetwork/portallocator/portallocator.go [hunk 1]
```diff
@@ -104,20 +88,12 @@ func Get() *PortAllocator {
...
+func newInstance() *PortAllocator {
 	start, end, err := getDynamicPortRange()
-	if err == nil {
-		start, end, err = sanitizePortRange(start, end)
-	}
 	if err != nil {
-		logrus.WithError(err).Infof("falling back to default port range %d-%d", defaultPortRangeStart, defaultPortRangeEnd)
-		start, end = defaultPortRangeStart, defaultPortRangeEnd
+		logrus.WithError(err).Infof("falling back to default port range %d-%d", DefaultPortRangeStart, DefaultPortRangeEnd)
+		start, end = DefaultPortRangeStart, DefaultPortRangeEnd
```
Comment (thaJeztah) [inline libnetwork/portallocator/portallocator.go:95]: Looks like these consts aren't used outside of the package, so I guess we can keep those

**Comment by thaJeztah** [comment]
Doing a quick rebase, and I'll add a commit to keep the consts un-exported

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
No worries! (apologies on our side for this have taken so long!)

File: libnetwork/portallocator/portallocator_unix.go [hunk 2]
```diff
@@ -9,5 +9,5 @@ const (
 	// defaultPortRangeEnd indicates the last port in port range
 	// consistent with default /proc/sys/net/ipv4/ip_local_port_range
 	// upper bound on linux
-	defaultPortRangeEnd = 60999
+	defaultPortRangeEnd = 65535
```
Comment (thaJeztah) [inline libnetwork/portallocator/portallocator_unix.go:12]: Let me comment on this line; this may have been related to https://github.com/moby/moby/pull/40055#issuecomment-1145398915 as well (in case we need to un-revert this change in range)

/cc @neersighted @corhere @evol262 

(and myself, for if this causes havoc in our products 🙈)

**Comment by thaJeztah** [comment]
Failure is unrelated; known flaky test (https://github.com/moby/moby/issues/38521)

```
=== FAIL: github.com/docker/docker/integration-cli TestDockerSuite/TestStartReturnCorrectExitCode (4.54s)
    docker_cli_start_test.go:191: assertion failed: 
        Command:  D:\a\moby\moby\out\docker.exe start -a withRestart
        ExitCode: 0
        Stdout:   
        Stderr:   
        
        Failures:
        ExitCode was 0 expected 11
    --- FAIL: TestDockerSuite/TestStartReturnCorrectExitCode (4.54s)
```
