### PR TITLE
Don't log error if file is already closed

### LINKED ISSUE #33172: logs request will make daemon raising a error when container stopped
**Description**

if a container stopped and you had a request or use cli command to get it's logs, you will see "level=error msg="Error closing logger: invalid argument"" in daemon's log.

**Steps to reproduce the issue:**

1. start a container, make sure it use json-file log driver.
2. start a request or use cli command to get it logs.
3. stop the container

**Describe the results you received:**

in daemon's log, I got 
```c2-docker-31.ricebook.link dockerd[11491]: time="2017-05-12T16:07:47.376078508+08:00" level=error msg="Error closing logger: invalid argument"```

**Describe the results you expected:**

nothing

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**
```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 17.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge calico host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.64-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.67GiB
Name: c2-docker-31.ricebook.link
ID: CHYZ:J7RJ:SVRT:FLUT:TXN5:77S5:JFNJ:V2E4:WB3X:LMX3:ZJ3F:4XKK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Cluster Store: etcd://127.0.0.1:2379
Insecure Registries:
 hub.ricebook.net
 127.0.0.0/8
Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

### PR DESCRIPTION
**Pull request by thaJeztah**
When closing the log-file, and the file is already
closed, there's no need to log an error.

This patch checks if the file is closed, and if so,
skip closing the file. This prevents errors like
this being logged:

    level=error msg="Error closing logger: invalid argument"

closes https://github.com/moby/moby/issues/33172

### CODE REVIEW

**Comment by thaJeztah** [comment]
@cpuguy83 something like this you meant?

File: daemon/logger/loggerutils/rotatefilewriter.go [hunk 1]
```diff
@@ -120,5 +120,10 @@ func (w *RotateFileWriter) NotifyRotateEvict(sub chan interface{}) {
 
 // Close closes underlying file and signals all readers to stop.
 func (w *RotateFileWriter) Close() error {
+	w.mu.Lock()
```
Comment (aaronlehmann) [inline daemon/logger/loggerutils/rotatefilewriter.go]: It seems like a good idea to take the lock here. It's not clear to me if `Close` is called concurrently with `Write`, but why take the chance?

However, shouldn't `LogPath` also lock the mutex?

Comment (cpuguy83) [inline daemon/logger/loggerutils/rotatefilewriter.go]: Indeed.

File: daemon/logger/loggerutils/rotatefilewriter.go [hunk 2]
```diff
@@ -120,5 +120,10 @@ func (w *RotateFileWriter) NotifyRotateEvict(sub chan interface{}) {
...
+	defer w.mu.Unlock()
+	if w.f == nil {
```
Comment (cpuguy83) [inline daemon/logger/loggerutils/rotatefilewriter.go]: `w.f` is not really ever set to nil or could potentially be nil for other reasons.
I'd track his with a `closed` bool on `w`

File: daemon/logger/loggerutils/rotatefilewriter.go [hunk 3]
```diff
@@ -42,6 +44,9 @@ func NewRotateFileWriter(logPath string, capacity int64, maxFiles int) (*RotateF
 //WriteLog write log message to File
 func (w *RotateFileWriter) Write(message []byte) (int, error) {
 	w.mu.Lock()
+	if w.closed {
+		return -1, errors.New("cannot write because the output file was closed")
```
Comment (aaronlehmann) [inline daemon/logger/loggerutils/rotatefilewriter.go]: This returns without unlocking.

I suggest using `defer` in this function as well.

Comment (cpuguy83) [inline daemon/logger/loggerutils/rotatefilewriter.go]: I would not use defer here since it adds significant overhead and this is a critical path.

Comment (ripcurld0) [inline daemon/logger/loggerutils/rotatefilewriter.go]: @cpuguy83 👍  https://lk4d4.darth.io/posts/defer/

Comment (thaJeztah) [inline daemon/logger/loggerutils/rotatefilewriter.go]: Ah, my mistake - I drafted this up too quickly to check if this was what @cpuguy83 had in mind; I'll update

**Comment by thaJeztah** [comment]
@aaronlehmann @cpuguy83 added the missing `unlock` https://github.com/moby/moby/pull/33305#discussion_r117798233. PTAL

**Comment by aaronlehmann** [comment]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM
