### PR TITLE
Docker http panics caused by container deletion with empty names.

### LINKED ISSUE #22210: docker http panics
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 252
 Running: 73
 Paused: 0
 Stopped: 179
Images: 4
Server Version: 1.10.3
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: journald
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.0-15-generic
Operating System: Ubuntu 16.04
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 62.9 GiB
Name: ip-10-0-1-115
ID: 3FQR:PLJG:D4NS:TGV2:7DQY:IAKT:R2V7:2NQJ:O2XS:MT43:BEVE:CHF7
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS, m4.4xlarge.

**Steps to reproduce the issue:** Unknown. We're running `amazon-ecs-agent` 1.8.2 and scheduling a bunch of tasks.

**Describe the results you received:** Some container deletions fail. We can see panics in logs. They are remarkably consistent.

```
$ journalctl -u docker _TRANSPORT=stdout | grep -A33 'panic serving'
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: 2016/04/20 19:40:11 http: panic serving @: runtime error: index out of range
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: goroutine 55903667 [running]:
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: net/http.(*conn).serve.func1(0xc8263442c0, 0x7f5df2aa2218, 0xc821608e10)
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1287 +0xb5
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: github.com/docker/docker/daemon.(*Daemon).GetByName(0xc820157800, 0xc825e63057, 0x0, 0x0, 0x0, 0x0)
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/daemon/daemon.go:529 +0x3fb
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: github.com/docker/docker/daemon.(*Daemon).GetContainer(0xc820157800, 0xc825e63057, 0x0, 0x0, 0x0, 0x0)
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/daemon/daemon.go:149 +0xd2
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: github.com/docker/docker/daemon.(*Daemon).ContainerRm(0xc820157800, 0xc825e63057, 0x0, 0xc8210c94c0, 0x0, 0x0)
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/daemon/delete.go:22 +0x6e
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server/router/container.(*containerRouter).deleteContainers(0xc820754c60, 0x7f5df2aefb08, 0xc825e631d0, 0x7f5df2aef800, 0xc8263444d0, 0xc824aaa380, 0xc825e630e0, 0x0, 0x0)
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/router/container/container_routes.go:401 +0x1de
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.deleteContainers)-fm(0x7f5df2aefb08, 0xc825e631d0, 0x7f5df2aef800, 0xc8263444d0, 0xc824aaa380, 0xc825e630e0, 0x0, 0x0)
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/router/container/container.go:64 +0x74
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.versionMiddleware.func1(0x7f5df2aefb08, 0xc825e631d0, 0x7f5df2aef800, 0xc8263444d0, 0xc824aaa380, 0xc825e630e0, 0x0, 0x0)
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/middleware.go:155 +0x83a
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*Server).corsMiddleware.func1(0x7f5df2aa1c28, 0xc820075440, 0x7f5df2aef800, 0xc8263444d0, 0xc824aaa380, 0xc825e630e0, 0x0, 0x0)
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/middleware.go:134 +0xfa
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*Server).userAgentMiddleware.func1(0x7f5df2aa1c28, 0xc820075440, 0x7f5df2aef800, 0xc8263444d0, 0xc824aaa380, 0xc825e630e0, 0x0, 0x0)
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/middleware.go:117 +0x4be
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7f5df2aef800, 0xc8263444d0, 0xc824aaa380)
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/server.go:169 +0x2ad
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: net/http.HandlerFunc.ServeHTTP(0xc8208f6740, 0x7f5df2aef800, 0xc8263444d0, 0xc824aaa380)
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1422 +0x3a
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc8207febe0, 0x7f5df2aef800, 0xc8263444d0, 0xc824aaa380)
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc8209fe4d0, 0x7f5df2aef800, 0xc8263444d0, 0xc824aaa380)
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: net/http.serverHandler.ServeHTTP(0xc82016e9c0, 0x7f5df2aef800, 0xc8263444d0, 0xc824aaa380)
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1862 +0x19e
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: net/http.(*conn).serve(0xc8263442c0)
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1361 +0xbee
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: created by net/http.(*Server).Serve
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1910 +0x3f6
--
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: 2016/04/20 19:52:48 http: panic serving @: runtime error: index out of range
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: goroutine 56017683 [running]:
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: net/http.(*conn).serve.func1(0xc820e540b0, 0x7f5df2aa2218, 0xc820d42360)
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1287 +0xb5
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: github.com/docker/docker/daemon.(*Daemon).GetByName(0xc820157800, 0xc826caa667, 0x0, 0x0, 0x0, 0x0)
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/daemon/daemon.go:529 +0x3fb
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: github.com/docker/docker/daemon.(*Daemon).GetContainer(0xc820157800, 0xc826caa667, 0x0, 0x0, 0x0, 0x0)
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/daemon/daemon.go:149 +0xd2
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: github.com/docker/docker/daemon.(*Daemon).ContainerRm(0xc820157800, 0xc826caa667, 0x0, 0xc827350f20, 0x0, 0x0)
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/daemon/delete.go:22 +0x6e
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server/router/container.(*containerRouter).deleteContainers(0xc820754c60, 0x7f5df2aefb08, 0xc826caa7b0, 0x7f5df2aef800, 0xc820e54160, 0xc824b28000, 0xc826caa6f0, 0x0, 0x0)
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/router/container/container_routes.go:401 +0x1de
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.deleteContainers)-fm(0x7f5df2aefb08, 0xc826caa7b0, 0x7f5df2aef800, 0xc820e54160, 0xc824b28000, 0xc826caa6f0, 0x0, 0x0)
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/router/container/container.go:64 +0x74
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.versionMiddleware.func1(0x7f5df2aefb08, 0xc826caa7b0, 0x7f5df2aef800, 0xc820e54160, 0xc824b28000, 0xc826caa6f0, 0x0, 0x0)
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/middleware.go:155 +0x83a
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*Server).corsMiddleware.func1(0x7f5df2aa1c28, 0xc820075440, 0x7f5df2aef800, 0xc820e54160, 0xc824b28000, 0xc826caa6f0, 0x0, 0x0)
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/middleware.go:134 +0xfa
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*Server).userAgentMiddleware.func1(0x7f5df2aa1c28, 0xc820075440, 0x7f5df2aef800, 0xc820e54160, 0xc824b28000, 0xc826caa6f0, 0x0, 0x0)
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/middleware.go:117 +0x4be
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7f5df2aef800, 0xc820e54160, 0xc824b28000)
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/server.go:169 +0x2ad
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: net/http.HandlerFunc.ServeHTTP(0xc8208f6740, 0x7f5df2aef800, 0xc820e54160, 0xc824b28000)
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1422 +0x3a
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc8207febe0, 0x7f5df2aef800, 0xc820e54160, 0xc824b28000)
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc8209fe4d0, 0x7f5df2aef800, 0xc820e54160, 0xc824b28000)
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: net/http.serverHandler.ServeHTTP(0xc82016e9c0, 0x7f5df2aef800, 0xc820e54160, 0xc824b28000)
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1862 +0x19e
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: net/http.(*conn).serve(0xc820e540b0)
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1361 +0xbee
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: created by net/http.(*Server).Serve
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1910 +0x3f6
--
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: 2016/04/20 20:04:12 http: panic serving @: runtime error: index out of range
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: goroutine 56121551 [running]:
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: net/http.(*conn).serve.func1(0xc8263442c0, 0x7f5df2aa2218, 0xc826a4f5c0)
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1287 +0xb5
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: github.com/docker/docker/daemon.(*Daemon).GetByName(0xc820157800, 0xc82692c4e7, 0x0, 0x0, 0x0, 0x0)
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/daemon/daemon.go:529 +0x3fb
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: github.com/docker/docker/daemon.(*Daemon).GetContainer(0xc820157800, 0xc82692c4e7, 0x0, 0x0, 0x0, 0x0)
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/daemon/daemon.go:149 +0xd2
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: github.com/docker/docker/daemon.(*Daemon).ContainerRm(0xc820157800, 0xc82692c4e7, 0x0, 0xc820d753d0, 0x0, 0x0)
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/daemon/delete.go:22 +0x6e
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server/router/container.(*containerRouter).deleteContainers(0xc820754c60, 0x7f5df2aefb08, 0xc82692c630, 0x7f5df2aef800, 0xc826344370, 0xc826dbc460, 0xc82692c570, 0x0, 0x0)
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/router/container/container_routes.go:401 +0x1de
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.deleteContainers)-fm(0x7f5df2aefb08, 0xc82692c630, 0x7f5df2aef800, 0xc826344370, 0xc826dbc460, 0xc82692c570, 0x0, 0x0)
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/router/container/container.go:64 +0x74
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.versionMiddleware.func1(0x7f5df2aefb08, 0xc82692c630, 0x7f5df2aef800, 0xc826344370, 0xc826dbc460, 0xc82692c570, 0x0, 0x0)
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/middleware.go:155 +0x83a
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*Server).corsMiddleware.func1(0x7f5df2aa1c28, 0xc820075440, 0x7f5df2aef800, 0xc826344370, 0xc826dbc460, 0xc82692c570, 0x0, 0x0)
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/middleware.go:134 +0xfa
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*Server).userAgentMiddleware.func1(0x7f5df2aa1c28, 0xc820075440, 0x7f5df2aef800, 0xc826344370, 0xc826dbc460, 0xc82692c570, 0x0, 0x0)
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/middleware.go:117 +0x4be
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7f5df2aef800, 0xc826344370, 0xc826dbc460)
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/server.go:169 +0x2ad
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: net/http.HandlerFunc.ServeHTTP(0xc8208f6740, 0x7f5df2aef800, 0xc826344370, 0xc826dbc460)
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1422 +0x3a
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc8207febe0, 0x7f5df2aef800, 0xc826344370, 0xc826dbc460)
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc8209fe4d0, 0x7f5df2aef800, 0xc826344370, 0xc826dbc460)
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: net/http.serverHandler.ServeHTTP(0xc82016e9c0, 0x7f5df2aef800, 0xc826344370, 0xc826dbc460)
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1862 +0x19e
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: net/http.(*conn).serve(0xc8263442c0)
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1361 +0xbee
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: created by net/http.(*Server).Serve
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1910 +0x3f6
--
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: 2016/04/20 23:01:52 http: panic serving @: runtime error: index out of range
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: goroutine 57686309 [running]:
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: net/http.(*conn).serve.func1(0xc822c16d10, 0x7f5df2aa2218, 0xc8212f4ed8)
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1287 +0xb5
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: github.com/docker/docker/daemon.(*Daemon).GetByName(0xc820157800, 0xc82284ba77, 0x0, 0x0, 0x0, 0x0)
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/daemon/daemon.go:529 +0x3fb
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: github.com/docker/docker/daemon.(*Daemon).GetContainer(0xc820157800, 0xc82284ba77, 0x0, 0x0, 0x0, 0x0)
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/daemon/daemon.go:149 +0xd2
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: github.com/docker/docker/daemon.(*Daemon).ContainerRm(0xc820157800, 0xc82284ba77, 0x0, 0xc8253ca890, 0x0, 0x0)
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/daemon/delete.go:22 +0x6e
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server/router/container.(*containerRouter).deleteContainers(0xc820754c60, 0x7f5df2aefb08, 0xc82284bbc0, 0x7f5df2aef800, 0xc822c16dc0, 0xc8253f29a0, 0xc82284bb00, 0x0, 0x0)
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/router/container/container_routes.go:401 +0x1de
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.deleteContainers)-fm(0x7f5df2aefb08, 0xc82284bbc0, 0x7f5df2aef800, 0xc822c16dc0, 0xc8253f29a0, 0xc82284bb00, 0x0, 0x0)
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/router/container/container.go:64 +0x74
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.versionMiddleware.func1(0x7f5df2aefb08, 0xc82284bbc0, 0x7f5df2aef800, 0xc822c16dc0, 0xc8253f29a0, 0xc82284bb00, 0x0, 0x0)
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/middleware.go:155 +0x83a
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*Server).corsMiddleware.func1(0x7f5df2aa1c28, 0xc820075440, 0x7f5df2aef800, 0xc822c16dc0, 0xc8253f29a0, 0xc82284bb00, 0x0, 0x0)
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/middleware.go:134 +0xfa
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*Server).userAgentMiddleware.func1(0x7f5df2aa1c28, 0xc820075440, 0x7f5df2aef800, 0xc822c16dc0, 0xc8253f29a0, 0xc82284bb00, 0x0, 0x0)
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/middleware.go:117 +0x4be
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7f5df2aef800, 0xc822c16dc0, 0xc8253f29a0)
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/server.go:169 +0x2ad
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: net/http.HandlerFunc.ServeHTTP(0xc8208f6740, 0x7f5df2aef800, 0xc822c16dc0, 0xc8253f29a0)
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1422 +0x3a
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc8207febe0, 0x7f5df2aef800, 0xc822c16dc0, 0xc8253f29a0)
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc8209fe4d0, 0x7f5df2aef800, 0xc822c16dc0, 0xc8253f29a0)
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: net/http.serverHandler.ServeHTTP(0xc82016e9c0, 0x7f5df2aef800, 0xc822c16dc0, 0xc8253f29a0)
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1862 +0x19e
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: net/http.(*conn).serve(0xc822c16d10)
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1361 +0xbee
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: created by net/http.(*Server).Serve
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1910 +0x3f6
```

**Describe the results you expected:** No panics.

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens on a small subset of our production hosts.

systemd unit file for Docker:
```
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target docker.socket
Requires=docker.socket

[Service]
Restart=always
Type=notify
ExecStart=/usr/bin/docker daemon --default-ulimit nofile=64000:64000 \
  --storage-driver=overlay \
  --log-driver=journald \
  --log-opt env=GALAXY_APP_ID,[shortened by pcarrier...]
MountFlags=slave
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity
OOMScoreAdjust=-1000
TasksMax=infinity
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target
```

### PR DESCRIPTION
**Pull request by yongtang**
**\- What I did**

This fix tries to fix the http panics caused by container deletion with empty names in #22210.

**\- How I did it**

The issue was because when an empty string was passed, `GetByName()` tried to access the first element of the name string without checking the length. A length check has been added.

**\- How to verify it**

A test case for #22210 has been added.

**\- A picture of a cute animal (not mandatory but encouraged)**

This fix fixes #22210.

Signed-off-by: Yong Tang yong.tang.github@outlook.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @cpuguy83 @vdemeester ptal

**Comment by justincormack** [comment]
LGTM

File: daemon/daemon.go [hunk 1]
```diff
@@ -530,6 +530,9 @@ func (daemon *Daemon) newContainer(name string, config *containertypes.Config, i
 
 // GetByName returns a container given a name.
 func (daemon *Daemon) GetByName(name string) (*container.Container, error) {
+	if len(name) == 0 {
+		return nil, fmt.Errorf("Could not find entity for empty container name")
```
Comment (cpuguy83) [inline daemon/daemon.go]: Can you use `errors.NewBadRequestError` here. This will ensure the proper HTTP handling.
Maybe improve the error message with `No container name or ID supplied`.

File: daemon/daemon.go [hunk 2]
```diff
@@ -530,6 +530,9 @@ func (daemon *Daemon) newContainer(name string, config *containertypes.Config, i
 
 // GetByName returns a container given a name.
 func (daemon *Daemon) GetByName(name string) (*container.Container, error) {
+	if len(name) == 0 {
```
Comment (runcom) [inline daemon/daemon.go]: `name == ""` ?

Comment (cpuguy83) [inline daemon/daemon.go]: Tend to prefer `len(name)` better.

Comment (runcom) [inline daemon/daemon.go]: Fair enough...

File: daemon/daemon.go (hunk 1 above)
Comment (yongtang) [inline daemon/daemon.go]: Thanks @cpuguy83 just updated the pull request.

File: integration-cli/docker_api_containers_test.go [hunk 3]
```diff
@@ -1616,3 +1616,10 @@ func (s *DockerSuite) TestPostContainersCreateWithOomScoreAdjInvalidRange(c *che
 		c.Fatalf("Expected output to contain %q, got %q", expected, string(b))
 	}
 }
+
+// test case for #22210 where an emtpy container name caused panic.
+func (s *DockerSuite) TestContainerApiDeleteWithEmptyName(c *check.C) {
+	status, _, err := sockRequest("DELETE", "/containers/", nil)
+	c.Assert(err, checker.IsNil)
+	c.Assert(status, checker.Equals, http.StatusNotFound)
```
Comment (cpuguy83) [inline integration-cli/docker_api_containers_test.go]: I suspect that CI will fail since we'd expect an http.StatusBadRequest now.

Comment (yongtang) [inline integration-cli/docker_api_containers_test.go]: Hi @cpuguy83 `GetContainer(prefixOrName string)` will call `GetByName()` and only check if the name is nil or not:
https://github.com/docker/docker/blob/v1.11.0/daemon/daemon.go#L148-L152
If there is any error (e.g., empty string) it will move on to check
```
daemon.idIndex.Get(prefixOrName)
```
So the error code will still be 404.

Maybe the check of empty string should be placed inside `GetContainer(prefixOrName string)`?

Comment (cpuguy83) [inline integration-cli/docker_api_containers_test.go]: Oh yep, perhaps it should. It is the only caller of `GetByName` anyway.

Comment (yongtang) [inline integration-cli/docker_api_containers_test.go]: Thanks @cpuguy83 I just updated the pull request. In addition to the check in `GetContainer(prefixOrName string)` I still placed a check in `GetByName()` in case later on this function is called in other places.

**Comment by cpuguy83** [comment]
LGTM

**Comment by tonistiigi** [comment]
LGTM

**Comment by cpuguy83** [comment]
Thanks @yongtang !
