### PR TITLE
pkg/idtools: refactor to avoid string-splitting

### LINKED ISSUE #41372: userns-remap fails with username/groupname with space (getent command)
**Description**

Docker daemon fails to start when userns-remap requires the `getent` binary call and the username or groupname contains space. This is particularly the case when using docker in an LDAP/Active Directory environment where the GID is `domain users`

**Steps to reproduce the issue:**

Content of _/etc/subuid_

```
user:1266401166:65536
```

Content of _/etc/subgid_

```
domain users:1266401153:65536
```

**Describe the results you received:**
```
sudo dockerd -D -H tcp://127.0.0.1:2375 --userns-remap="user:domain users"
INFO[2020-08-19T10:26:59.288868661+02:00] Starting up                                  
Error during groupname lookup for "domain users": getent unable to find entry "domain" in group database
```

**Describe the results you expected:**

Docker daemon should be able to parse group/user with space when calling getent

**Additional information you deem important (e.g. issue happens only occasionally):**

The issue relies in the way the  `getent` is called by the [execCmd](https://github.com/moby/moby/blob/d0eff1f86f92c7e30c9a947541374e20d4fed0a9/pkg/idtools/utils_unix.go#L30) function. The args string is simply splat using `" "` delimiter which leads to an issue when groupname or username contain space. My first guess is to change the definition of the args from the exeCmd function to take an []string instead of just a string

```go
func execCmd(cmd, args []string) ([]byte, error) {
}
```

Furthermore, the [LookupGroup](https://github.com/moby/moby/blob/d0eff1f86f92c7e30c9a947541374e20d4fed0a9/pkg/idtools/idtools_unix.go#L160) function should escape the `groupname` with `\ ` character. I guess that the following replacement will make the trick

```go
func LookupGroup(groupname string) (user.Group, error) {
	// first try a local system files lookup using existing capabilities
	group, err := user.LookupGroup(groupname)
	if err == nil {
		return group, nil
	}
	// local files lookup failed; attempt to call `getent` to query configured group dbs
       // old : return getentGroup(fmt.Sprintf("%s %s", "group", groupname))
	return getentGroup(fmt.Sprintf("%s %s", "group", strings.Replace(groupname, " ", "\\ ", -1)))
}
```

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:50 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 13
  Running: 0
  Paused: 0
  Stopped: 13
 Images: 89
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-10-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.08GiB
 Name: maxime-port.lin.ariane.network
 ID: X5OZ:FT2A:DR5P:JUFG:T3TH:XPUS:NOFF:AVEQ:EPTJ:UJBK:ABSU:5WV2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Laptop with a user part of an Active Directory environment.

```
 getent passwd user
user:*:1266401166:1266401166:John Doe:/home/doe:/bin/bash
```

```
getent group domain\ users
domain users:*:1266400513:
```

### PR DESCRIPTION
**Pull request by thaJeztah**
fixes https://github.com/moby/moby/issues/41372

The package used a lot of string-formatting, followed by string-splitting.
This looked to originate from attempts to use templating to allow future
extensibility (9a3ab0358ecd657e3754677ff52250fd6cca4422 / https://github.com/moby/moby/pull/12648).

Looking at the history of the package, only a single update was made to
these templates, 5 years go, which makes it unlikely that more templating
will be needed.

This patch simplifies the handling of arguments to use `[]string` instead
of a single `string` (and splitting to a `[]string`). This both simplifies
the code somewhat, and prevents user/group-names containing spaces to be
splitted (causing, e.g. `getent` to fail).

Note that user/group-names containing spaces are invalid (or at least
discouraged), there are situations where such names may be used, so we
should avoid breaking on such names.

Before this change, a user/group name with a space in its name would fail;

    dockerd --userns-remap="user:domain users"
    INFO[2020-08-19T10:26:59.288868661+02:00] Starting up
    Error during groupname lookup for "domain users": getent unable to find entry "domain" in group database

With this change:

    # Add some possibly problematic usernames for testing
    # need to do this manually, as `adduser` / `useradd` won't accept these names
    echo 'user name:x:1002:1002::/home/one:/bin/false' >> /etc/passwd; \
    echo 'user name:x:1002:' >> /etc/group; \
    echo 'user name:1266401166:65536' >> /etc/subuid; \
    echo 'user name:1266401153:65536' >> /etc/subgid; \
    echo 'user$HOME:x:1003:1003::/home/one:/bin/false' >> /etc/passwd; \
    echo 'user$HOME:x:1003:' >> /etc/group; \
    echo 'user$HOME:1266401166:65536' >> /etc/subuid; \
    echo 'user$HOME:1266401153:65536' >> /etc/subgid; \
    echo 'user'"'"'name:x:1004:1004::/home/one:/bin/false' >> /etc/passwd; \
    echo 'user'"'"'name:x:1004:' >> /etc/group; \
    echo 'user'"'"'name:1266401166:65536' >> /etc/subuid; \
    echo 'user'"'"'name:1266401153:65536' >> /etc/subgid; \
    echo 'user"name:x:1005:1005::/home/one:/bin/false' >> /etc/passwd; \
    echo 'user"name:x:1005:' >> /etc/group; \
    echo 'user"name:1266401166:65536' >> /etc/subuid; \
    echo 'user"name:1266401153:65536' >> /etc/subgid;

    # Start the daemon using those users
    dockerd --userns-remap="user name:user name"
    dockerd --userns-remap='user$HOME:user$HOME'
    dockerd --userns-remap="user'name":"user'name"
    dockerd --userns-remap='user"name':'user"name'

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

```
Fix handling of looking up user- and group-names with spaces
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
@AkihiroSuda @kolyshkin @estesp PTAL

File: pkg/idtools/utils_unix.go [hunk 1]
```diff
@@ -26,7 +25,7 @@ func resolveBinary(binname string) (string, error) {
 	return "", fmt.Errorf("Binary %q does not resolve to a binary of that name in $PATH (%q)", binname, resolvedPath)
 }
 
-func execCmd(cmd, args string) ([]byte, error) {
-	execCmd := exec.Command(cmd, strings.Split(args, " ")...)
+func execCmd(cmd string, args []string) ([]byte, error) {
```
Comment (thaJeztah) [inline pkg/idtools/utils_unix.go:28]: Actually, perhaps just change this to match `exec.Command`

```suggestion
func execCmd(cmd string, arg ...string) ([]byte, error) {
```

**Review by estesp — APPROVED** [review]
LGTM

File: pkg/idtools/idtools_unix.go [hunk 2]
```diff
@@ -182,18 +181,18 @@ func getentGroup(args string) (user.Group, error) {
...
 	return groups[0], nil
 }
 
-func callGetent(args string) (io.Reader, error) {
+func callGetent(database, key string) (io.Reader, error) {
 	entOnce.Do(func() { getentCmd, _ = resolveBinary("getent") })
 	// if no `getent` command on host, can't do anything else
 	if getentCmd == "" {
-		return nil, fmt.Errorf("")
+		return nil, fmt.Errorf("unable to find getent command")
```
Comment (cpuguy83) [inline pkg/idtools/idtools_unix.go:193]: 😱

**Review by cpuguy83 — APPROVED** [review]
LGTM

File: pkg/idtools/idtools_unix.go (hunk 2 above)
Comment (thaJeztah) [reply pkg/idtools/idtools_unix.go:193]: LOL, yes, I guess it had to return "an error", but empty error string felt a bit too minimal 😹
