### PR TITLE
Generate a swarm joining secret if none is specified

### LINKED ISSUE #23785: [1.12.0-rc2] Joining a remote node without --manager doesn't require acceptance
**Output of `docker version`:**

Client (laptop, OSX)
```
$> docker version
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   a7119de
 Built:        Fri Jun 17 22:09:20 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

Server:

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd-unsupported
 Built:        Fri Jun 17 21:21:56 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd-unsupported
 Built:        Fri Jun 17 21:21:56 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

Client:
```
Containers: 78
 Running: 0
 Paused: 0
 Stopped: 78
Images: 51
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 344
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: inactive
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 4.4.13-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: moby
ID: AX3N:B5KC:6TY6:V5UW:5MAH:JSD3:PXBN:HC3H:GF3L:GC7L:Z35R:KAIW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 33
 Goroutines: 95
 System Time: 2016-06-20T22:09:37.819574454Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

Server (swarm cluster):
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay host null bridge
Swarm: inactive
Runtimes: default
Default Runtime: default
Security Options: apparmor seccomp
Kernel Version: 4.4.0-24-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 991.1 MiB
Name: docker1
ID: LOR7:TUJW:PXCF:SGKX:L5LU:GQCT:UTRN:G72M:JU32:I24J:JN3R:BN34
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Set up a remote swarm cluster - mine is 4 remote nodes, 2 leaders
2. On your laptop, run:
```
$> docker swarm join swarmIP:2377
This node joined a Swarm as a worker.
```
3. On the leader:
```
docker node ls
ID                         NAME     MEMBERSHIP  STATUS  AVAILABILITY  MANAGER STATUS
09y7cdu03xmuwhta0ykvd72gb  docker4  Accepted    Ready   Active        Reachable
1jkzrkblwbdig3l5u29997n00  docker1  Accepted    Ready   Active        Leader
41znz1ntskwvvvea8up52wu0m  docker2  Accepted    Ready   Active        
5bt1bcak4tuzm9a39a7ou9upz  docker3  Accepted    Ready   Active        
7ljlfo1zqcid0mc8cmir64i6g  moby     Accepted    Ready   Active 
```

**Describe the results you received:**

My 'rogue' laptop was able to join the swarm cluster as a worker and shows up in the manager list as ready and active.

**Describe the results you expected:**

I expected the join command to require approval from a manager node as it does in manager mode

**Additional information you deem important (e.g. issue happens only occasionally):**

### PR DESCRIPTION
**Pull request by aaronlehmann**
The current behavior of `docker swarm init` is to set up a swarm that
has no secret for joining, and does not require manual acceptance for
workers. Since workers may sometimes receive sensitive data such as pull
credentials, it makes sense to harden the defaults.

This change makes `docker swarm init` generate a random secret if none
is provided, and print it to the terminal. This secret will be needed to
join workers or managers to the swarm. In addition to improving access
control to the cluster, this setup removes an avenue for
denial-of-service attacks, since the secret is necessary to even create
an entry in the node list.

`docker swarm init --secret ""` will set up a swarm without a secret,
matching the old behavior. `docker swarm update --secret ""` removes the
automatically generated secret after `docker swarm init`.

Closes #23785

cc @diogomonica @aluzzardi @tonistiigi @dnephin

### CODE REVIEW

**Comment by aaronlehmann** [comment]
Note that this PR does not change the defaults for auto-acceptance. So while a secret will be required in all cases, under default settings, a node can't join as a manager without approval, even though it presents the secret. It will still show up as a pending node, which needs to be accepted with `docker node accept` on a manager.

**Comment by aaronlehmann** [comment]
cc @sfsmithcha

File: api/client/swarm/init.go [hunk 1]
```diff
@@ -45,11 +55,31 @@ func newInitCommand(dockerCli *client.DockerCli) *cobra.Command {
 func runInit(dockerCli *client.DockerCli, flags *pflag.FlagSet, opts initOptions) error {
 	client := dockerCli.Client()
 	ctx := context.Background()
+	spec := opts.swarmOptions.ToSpec()
+
+	// If no secret was specified, we create a random one
+	if !flags.Changed("secret") {
+		var secretBytes [generatedSecretEntropyBytes]byte
+
+		if _, err := io.ReadFull(cryptorand.Reader, secretBytes[:]); err != nil {
```
Comment (tonistiigi) [inline api/client/swarm/init.go]: nit: same as `rand.Read()`

**Comment by aaronlehmann** [comment]
Updated to made `docker swarm init` show a `docker swarm join` command that can be used to join the new swarm.

File: api/client/swarm/init.go [hunk 2]
```diff
@@ -45,19 +54,61 @@ func newInitCommand(dockerCli *client.DockerCli) *cobra.Command {
...
+	if !flags.Changed("secret") {
+		var secretBytes [generatedSecretEntropyBytes]byte
+
+		if _, err := cryptorand.Read(secretBytes[:]); err != nil {
+			panic(fmt.Errorf("failed to read random bytes: %v", err))
+		}
+
+		var nn big.Int
+		nn.SetBytes(secretBytes[:])
+		secret = fmt.Sprintf("%0[1]*s", maxGeneratedSecretLength, nn.Text(generatedSecretBase))
```
Comment (dnephin) [inline api/client/swarm/init.go]: This block (62-70) looks like it should be in its own function `func generateRandomSecret() string`

File: api/client/swarm/init.go [hunk 3]
```diff
@@ -45,19 +54,61 @@ func newInitCommand(dockerCli *client.DockerCli) *cobra.Command {
...
+
+		fmt.Fprintf(dockerCli.Out(), "No node joining secret provided. Generated random secret:\n\t%s\n\n", secret)
```
Comment (dnephin) [inline api/client/swarm/init.go]: In the secret flag usage text we say "Set secret value needed to accept nodes into cluster". Is that wrong? Should it be "secret value needed to join a cluster" ?

"No node joining secret" reads a little strange to me, could this be just "No --secret  provided" ?

File: api/client/swarm/init.go [hunk 4]
```diff
@@ -45,19 +54,61 @@ func newInitCommand(dockerCli *client.DockerCli) *cobra.Command {
...
+
+		for i := range spec.AcceptancePolicy.Policies {
+			spec.AcceptancePolicy.Policies[i].Secret = &secret
+		}
+	} else {
+		secret = opts.secret
+	}
```
Comment (dnephin) [inline api/client/swarm/init.go]: This looks wrong. Why would the secret be set in one block and not the other?

I think if you move `spec := opts.swarmOptions.ToSpec()` back to where it was then you wouldn't need this at all. You could have the `if !Changed()`  block just set `opts.secret`, and the else block wouldn't need to exist (just read `opts.secret` below instead of creating a new variable for it).

Comment (dnephin) [inline api/client/swarm/init.go]: Oh, I guess this is to deal with unset vs default of `""` ? We should make `opts.secret` a `*string`

Comment (aaronlehmann) [inline api/client/swarm/init.go]: The secret is set in both blocks. In the first block it's

`secret = fmt.Sprintf("%0[1]*s", maxGeneratedSecretLength, nn.Text(generatedSecretBase))`

and in the second block it's

`secret = opts.secret`

In other words, if the user specifies a secret, we set the `secret` variable to that value. Otherwise, we generate one and set it to the generated value.

I guess you're right that the `if` case could set `opts.secret` directly. That didn't feel quite right to me, because the generated secret is not an option provided by the user.

File: api/client/swarm/init.go (hunk 3 above)
Comment (aaronlehmann) [inline api/client/swarm/init.go]: > In the secret flag usage text we say "Set secret value needed to accept nodes into cluster". Is that wrong? Should it be "secret value needed to join a cluster" ?

Yeah, the text should be changed to this. Acceptance is a separate step (as I just learned yesterday).

I'll change this to `No --secret provided for now`, but just FYI, based on discussions with @aluzzardi and @diogomonica, it sounds like we will be removing the ability to set a user-specified secret in a followup PR, and going with generated secrets only. This will allow us to make the secret more discoverable because we won't have to worry about exposing passwords from the API. Here is a mockup: https://gist.github.com/aaronlehmann/a919b014cf43fc46ab046a84d06bd097

File: api/client/swarm/init.go (hunk 4 above)
Comment (dnephin) [inline api/client/swarm/init.go]: Neither are default values, which also end up in `opts` fields. I think that's ok. This is just another way of setting a default value.

**Comment by aaronlehmann** [comment]
@dnephin: Updated to address the comments, PTAL.

**Comment by tonistiigi** [comment]
Design LGTM

**Comment by dnephin** [comment]
Thanks LGTM

**Comment by diogomonica** [comment]
@aaronlehmann this LGTM, but are you going to do the changes we talked about yesterday in another PR?

**Comment by aaronlehmann** [comment]
@diogomonica: Yes, I'm planning to do those as a followup.

I'm waiting for design review on the mockup, and also on the swarmkit PR https://github.com/docker/swarmkit/pull/1128.

**Comment by praving5** [comment]
Didn't quite understand. So, the old behavior still exists right? Nodes can join swarm cluster without any secret and the default `--auto-accept` is set to `worker`?

Or are you saying that passing `--secret` is now mandatory and if we don't explicitly set it up, docker swarm will automatically pick one and thereafter both `worker` and `manager` nodes need to know that auto-generated secret to join the cluster.

So, are we dropping `none` as a parameter value for `--auto-accept`? or are we thinking to drop `--auto-accept` parameter itself since it will no more be needed since we are mandating `--secret`?

Can we also update the [respective documentation](https://docs.docker.com/engine/reference/commandline/swarm_init/)?

**Comment by thaJeztah** [comment]
@praving5 see https://github.com/docker/docker/issues/24430 for more context

**Comment by aaronlehmann** [comment]
@praving5: The new behavior is that `swarm init` by default will generate a secret that you need to pass to add nodes. `swarm init` will print a complete command line you can use to do this, including the secret. You can always opt out of this behavior by passing `--secret ""` on the `swarm init` command line (though note that the form of this flag may change soon - see #24430).

Node acceptance is a separate concept from the joining secret. The defaults there haven't changed, so it's still necessary to accept managers with `docker node accept`.

The documentation you mentioned was updated as part of this PR.
