### PR TITLE
Avoid redundant HEAD requests for identical layers on push

### LINKED ISSUE #14873: Redundant HEAD requests on push checking if the same layer exists
Description of problem:

Pushing a repository can cause many redundant HTTP HEAD requests to the registry, which check the existence of the same image. For example:

    $ docker push localhost:5000/aaronl/golang
    The push refers to a repository [localhost:5000/aaronl/golang] (len: 4)
    124e2127157f: Image already exists 
    124e2127157f: Image already exists 
    69c177f0c117: Image already exists 
    141b650c3281: Image already exists 
    8fb45e60e014: Image already exists 
    63e9d2557cd7: Image already exists 
    b279b4aae826: Image already exists 
    d86979befb72: Image already exists 
    8ddc08289e1a: Image already exists 
    8d38711ccc0d: Image already exists 
    8ddc08289e1a: Image already exists 
    8d38711ccc0d: Image already exists 
    0f5121dd42a6: Image already exists 
    607e965985c1: Image already exists 
    1ff9f26f09fb: Image already exists 
    9a61b6b1315e: Image already exists 
    902b87aaaec9: Image already exists

Each of these lines of output corresponds to a HEAD request. In this example, there are redundant requests for 124e2127157f, 8d38711ccc0d, and 8ddc08289e1a. With some repositories, images can be checked dozens of times; for example https://github.com/docker/docker/issues/12489#issuecomment-123808907

This happens when the repository has multiple tags. The tags appear to be handled independently, but they will often refer to overlapping sets of images, so there should be some deduplication to avoid extra work checking for those images.

This is an offshoot of #12489.

`docker version`:

    Client version: 1.7.0
    Client API version: 1.19
    Go version (client): go1.4.2
    Git commit (client): 0baf609
    OS/Arch (client): darwin/amd64
    Server version: 1.7.0
    Server API version: 1.19
    Go version (server): go1.4.2
    Git commit (server): 0baf609
    OS/Arch (server): linux/amd64

`docker info`:

    Containers: 6
    Images: 142
    Storage Driver: aufs
     Root Dir: /mnt/sda1/var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 154
     Dirperm1 Supported: true
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 4.0.5-boot2docker
    Operating System: Boot2Docker 1.7.0 (TCL 6.3); master : 7960f90 - Thu Jun 18 18:31:45 UTC 2015
    CPUs: 1
    Total Memory: 1.956 GiB
    Name: dev
    ID: NL56:VA6W:U27U:7F3F:EFRF:PIJR:POEO:M5KA:G4KW:GB7Q:SVFF:I3EU
    Debug mode (server): true
    File Descriptors: 31
    Goroutines: 112
    System Time: 2015-07-22T20:51:33.08148101Z
    EventsListeners: 1
    Init SHA1: 
    Init Path: /usr/local/bin/docker
    Docker Root Dir: /mnt/sda1/var/lib/docker
    Labels:
     provider=virtualbox

`uname -a`:

    Darwin Aarons-MacBook-Pro.local 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64

Environment details (AWS, VirtualBox, physical, etc.): Kitematic

How reproducible: Consistently

Steps to Reproduce:
1. `docker pull golang`
2. `docker tag golang localhost:5000/aaronl/golang`
3. `docker push localhost:5000/aaronl/golang`
4. `docker tag golang localhost:5000/aaronl/golang:tag1`
5. `docker push localhost:5000/aaronl/golang`

Actual Results: Duplicate layers listed in final `docker push` output; duplicate HEAD requests go over the network

Expected Results: Each layer is only checked once.

Additional info: N/A

### PR DESCRIPTION
**Pull request by aaronlehmann**
pushV2Tag already deduplicates layers, but the scope of this
deduplication is only for a particular tag. If we are pushing all tags
in a repository, we may check layers several times. Fix this by moving
the layersSeen map from the pushV2Tag function to the v2Pusher struct.

In addition to avoiding some useless round-trips, this makes the "docker
push" output less confusing. It formerly could contain many repeated
lines like:

```
124e2127157f: Image already exists
124e2127157f: Image already exists
...
```

Add test coverage based on the "docker push" output: a hash should not
appear multiple times when pushing multiple tags.

Fixes #14873

Signed-off-by: Aaron Lehmann aaron.lehmann@docker.com

### CODE REVIEW

**Comment by aaronlehmann** [comment]
@dmcgowan @stevvooe PTAL

File: integration-cli/docker_cli_push_test.go [hunk 1]
```diff
@@ -60,7 +60,32 @@ func (s *DockerRegistrySuite) TestPushMultipleTags(c *check.C) {
 
 	dockerCmd(c, "tag", "busybox", repoTag2)
 
-	dockerCmd(c, "push", repoName)
+	out, _ := dockerCmd(c, "push", repoName)
```
Comment (stevvooe) [inline integration-cli/docker_cli_push_test.go]: Check the error.

**Comment by dmcgowan** [comment]
LGTM

File: integration-cli/docker_cli_push_test.go (hunk 1 above)
Comment (dmcgowan) [inline integration-cli/docker_cli_push_test.go]: The error is checked by `dockerCmd`, the `_` is the status which is irrelevant here

File: graph/push_v2.go [hunk 2]
```diff
@@ -26,6 +26,10 @@ type v2Pusher struct {
 	config    *ImagePushConfig
 	sf        *streamformatter.StreamFormatter
 	repo      distribution.Repository
+
+	// Layers known to exist on the remote side. This avoids redundant
```
Comment (stevvooe) [inline graph/push_v2.go]:
```
// layersSeen ...
```

**Comment by stevvooe** [comment]
LGTM after doc fix.

**Comment by aaronlehmann** [comment]
Fixed the comment, thanks for the review.

**Comment by icecrime** [comment]
Thanks @aaronlehmann!

Waiting on CI: feel free to merge once green.
