### PR TITLE
Avoid using "example.com" in integration test

### LINKED ISSUE #32267: Flaky Test: DockerSuite.TestAPIImagesImportBadSrc
Seen on Z-PRs, https://jenkins.dockerproject.org/job/Docker-PRs-s390x/925/consoleFull

```
22:31:19 ----------------------------------------------------------------------
22:31:19 FAIL: docker_api_images_test.go:120: DockerSuite.TestAPIImagesImportBadSrc
22:31:19 
22:31:19 docker_api_images_test.go:137:
22:31:19     c.Assert(res.StatusCode, checker.Equals, te.statusExp)
22:31:19 ... obtained int = 500
22:31:19 ... expected int = 404
22:31:19 
22:31:20 
22:31:20 ----------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by aaronlehmann**
This test appears to trigger HTTP requests to "example.com", which may
explain why it is not behaving consistently. This changes it to use an
internal HTTP server to avoid unexpected behavior caused by firewalls or
proxies.

Attempts to fix #32267

cc @vdemeester @tophj-ibm @michael-holzheu

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM (if green 😅 )

File: integration-cli/docker_api_images_test.go [hunk 1]
```diff
@@ -120,13 +121,16 @@ func (s *DockerSuite) TestAPIImagesHistory(c *check.C) {
 func (s *DockerSuite) TestAPIImagesImportBadSrc(c *check.C) {
 	testRequires(c, Network)
```
Comment (vdemeester) [inline integration-cli/docker_api_images_test.go]: I think we can remove that one, right ? (as now we don't need to access to network)

**Review by vdemeester — APPROVED** [review]
LGTM 🦁 
(just one nit comment)

File: integration-cli/docker_api_images_test.go (hunk 1 above)
Comment (vieux) [inline integration-cli/docker_api_images_test.go]: @vdemeester I see this it merged. is this line needed ?

Comment (aaronlehmann) [inline integration-cli/docker_api_images_test.go]: Oh, you should have let me remove it :)

Comment (vieux) [inline integration-cli/docker_api_images_test.go]: @vdemeester you're too fast :D

Comment (vdemeester) [inline integration-cli/docker_api_images_test.go]: @aaronlehmann @vieux lol 😛 I just wanted to have it merge, we can follow-up to remove it 🤗 (it was green 🌥)
