### PR TITLE
fix Bind-mounts not properly registering after daemon restart

### LINKED ISSUE #9629: Data container goes stale, won't mount volumes-from
When I first created the DATA container (backed by localhost storage) everything was working fine. After a while, it stopped mounting. I can remove the data container and recreate it (again since everything is backed by localhost storage), and everything works again for a while.

Any ideas? Am I doing something wrong?

```Shell
$ docker inspect DATA | grep -A 3 -E '"Volumes": {'
    "Volumes": {
        "/root/.m2": "/opt/data/m2"
    },

$ ls -la /opt/data/m2/settings.xml 
-rwxr-xr-x 1 root root 2024 Dec  2 19:56 /opt/data/m2/settings.xml

$ docker run --rm --volumes-from DATA busybox ls -la /root/.m2/settings.xml
ls: /root/.m2/settings.xml: No such file or directory

$ docker rm DATA
DATA

$ docker run --name DATA -v /opt/data/m2:/root/.m2 tianon/true

$ docker run --rm --volumes-from DATA busybox ls -la /root/.m2/settings.xml
-rwxr-xr-x    1 root     root          2024 Dec  2 19:56 /root/.m2/settings.xml
```

```Shell
$ docker -v
Docker version 1.3.2, build 39fa2fa
```

### PR DESCRIPTION
**Pull request by cpuguy83**
Fixes #9629 #9768

1) Volume config is not restored if we couldn't find it with the graph
driver, but bind-mounts would never be found by the graph driver since
they aren't in that dir

2) container volumes were only being restored if they were found in the
volumes repo, but volumes created by old daemons wouldn't be in the
repo until the container is at least started.

### CODE REVIEW

**Comment by jfrazelle** [comment]
LGTM

File: daemon/volumes.go [hunk 1]
```diff
@@ -119,8 +119,18 @@ func (container *Container) VolumePaths() map[string]struct{} {
...
 
 func (container *Container) registerVolumes() {
-	for _, mnt := range container.VolumeMounts() {
-		mnt.volume.AddContainer(container.ID)
+	for path := range container.VolumePaths() {
+		if v := container.daemon.volumes.Get(path); v != nil {
+			v.AddContainer(container.ID)
+		} else {
+			// if container was created with an old daemon, this volume may not be registered
+			v, err := container.daemon.volumes.FindOrCreateVolume(path, container.VolumesRW[path])
```
Comment (crosbymichael) [inline daemon/volumes.go]: What if the volume is not a `rw` volume in `VolumesRW`?

Comment (crosbymichael) [inline daemon/volumes.go]: Ahh, from what I can tell this is only used for very old daemons

File: volumes/repository.go [hunk 2]
```diff
@@ -80,38 +81,36 @@ func (r *Repository) newVolume(path string, writable bool) (*Volume, error) {
...
-		vol := &Volume{
-			ID:         id,
-			configPath: r.configPath + "/" + id,
+		dec := json.NewDecoder(f)
+		v := &Volume{
+			configPath: filepath.Join(r.configPath, d.Name()),
 			containers: make(map[string]struct{}),
-			Path:       path,
 		}
-		if err := vol.FromDisk(); err != nil {
```
Comment (crosbymichael) [inline volumes/repository.go]: I see you are not using any of these methods now like `FromDisk`.  Is this not used at all because if not, you should delete it.

File: daemon/volumes.go (hunk 1 above)
Comment (cpuguy83) [inline daemon/volumes.go]: It would be pre 1.3 daemons, so not that old.

I'll update this VolumesRW thing to make sure we don't panic here.  It _shouldn't_ be nil, but it could be.

File: volumes/repository.go [hunk 3]
```diff
@@ -80,38 +81,36 @@ func (r *Repository) newVolume(path string, writable bool) (*Volume, error) {
 }
 
 func (r *Repository) restore() error {
+	log.Debugf("Restoring volumes")
```
Comment (crosbymichael) [inline volumes/repository.go]: This file looks to be full of refactoring not related to the fix.  Please don't refactor unrelated blocks in bug fixes.

Unless this is related to the fix for the bugs please remove this refactoring because there are a few bugs and areas where this code panics.

**Comment by cpuguy83** [comment]
@crosbymichael Updated

**Comment by LK4D4** [comment]
@cpuguy83 Is it possible to write test for this? We have test-daemon for restarting.

**Comment by cpuguy83** [comment]
@LK4D4 There is a test there.

**Comment by LK4D4** [comment]
@cpuguy83 Yup, sorry :)

File: daemon/volumes.go [hunk 4]
```diff
@@ -119,8 +119,22 @@ func (container *Container) VolumePaths() map[string]struct{} {
 }
 
 func (container *Container) registerVolumes() {
-	for _, mnt := range container.VolumeMounts() {
-		mnt.volume.AddContainer(container.ID)
+	for path := range container.VolumePaths() {
+		if v := container.daemon.volumes.Get(path); v != nil {
+			v.AddContainer(container.ID)
```
Comment (LK4D4) [inline daemon/volumes.go]: should be continue here

File: daemon/volumes.go [hunk 5]
```diff
@@ -119,8 +119,22 @@ func (container *Container) VolumePaths() map[string]struct{} {
...
+		} else {
+			// if container was created with an old daemon, this volume may not be registered
+			var mode = true
```
Comment (LK4D4) [inline daemon/volumes.go]: maybe `mode := true`? Also `mode` is pretty weird name, maybe `writtable`?

**Comment by cpuguy83** [comment]
@LK4D4 Updated

**Comment by LK4D4** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Comment by grossws** [comment]
Does it fix #9801?

**Comment by jfrazelle** [comment]
thanks @grossws I have closed that issue.

**Comment by HuKeping** [comment]
It will cause a panic with this patch.

**Comment by cpuguy83** [comment]
How so?

**Comment by HuKeping** [comment]
hi @cpuguy83 , when u restart the daemon without -g to specify another new storage path, u would like to get this:
```
goroutine 8 [running]:
runtime.panic(0xb22d80, 0x164e5e8)
	/usr/local/go/src/pkg/runtime/panic.c:266 +0xb6
github.com/docker/docker/volumes.(*Volume).createIfNotExist(0xc2101b16e0, 0x0, 0x27)
	/go/src/github.com/docker/docker/volumes/volume.go:102 +0x2b2
github.com/docker/docker/volumes.(*Volume).initialize(0xc2101b16e0, 0x0, 0x0)
	/go/src/github.com/docker/docker/volumes/volume.go:130 +0x83
github.com/docker/docker/volumes.(*Repository).restore(0xc210245810, 0x0, 0xc210245840)
	/go/src/github.com/docker/docker/volumes/repository.go:110 +0x6fe
github.com/docker/docker/volumes.NewRepository(0xc21013d160, 0x17, 0x7f29b9c9c928, 0xc21017d0b0, 0x17, ...)
	/go/src/github.com/docker/docker/volumes/repository.go:39 +0x178
github.com/docker/docker/daemon.NewDaemonFromDirectory(0x1670b20, 0xc21008da50, 0x0, 0x47, 0xb9)
	/go/src/github.com/docker/docker/daemon/daemon.go:892 +0xed6
github.com/docker/docker/daemon.NewDaemon(0x1670b20, 0xc21008da50, 0x0, 0x2, 0x0)
	/go/src/github.com/docker/docker/daemon/daemon.go:779 +0x31
main.func·001()
	/go/src/github.com/docker/docker/docker/daemon.go:55 +0x43
created by main.mainDaemon
	/go/src/github.com/docker/docker/docker/daemon.go:78 +0x290

goroutine 1 [chan receive]:
github.com/docker/docker/api/server.ServeApi(0xc210047880, 0x7f29b9c91040)
	/go/src/github.com/docker/docker/api/server/server.go:1639 +0x440
github.com/docker/docker/engine.(*Job).Run(0xc210047880, 0x0, 0x0)
	/go/src/github.com/docker/docker/engine/job.go:83 +0x76e
main.mainDaemon()
	/go/src/github.com/docker/docker/docker/daemon.go:93 +0x514
main.main()
goroutine 3 [syscall]:
os/signal.loop()
	/usr/local/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
	/usr/local/go/src/pkg/os/signal/signal_unix.go:27 +0x31

goroutine 4 [syscall]:
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1394

goroutine 10 [runnable]:
runtime.gosched()
	/usr/local/go/src/pkg/runtime/proc.c:1368 +0x27
runtime.gc(0x1)
	/usr/local/go/src/pkg/runtime/mgc0.c:2047 +0x27c
runfinq()
	/usr/local/go/src/pkg/runtime/mgc0.c:2325 +0x1f2
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1394

goroutine 7 [chan receive]:
github.com/docker/docker/pkg/signal.func·002()
	/go/src/github.com/docker/docker/pkg/signal/trap.go:30 +0x6c
created by github.com/docker/docker/pkg/signal.Trap
	/go/src/github.com/docker/docker/pkg/signal/trap.go:53 +0x26c

goroutine 9 [chan receive]:
github.com/docker/docker/pkg/listenbuffer.(*defaultListener).Accept(0xc210185720, 0x0, 0x1000000a349c0, 0xc210185dc0, 0x2100efd70)
	/go/src/github.com/docker/docker/pkg/listenbuffer/buffer.go:43 +0x7c
net/http.(*Server).Serve(0xc210265dc0, 0x7f29b9c9c7e0, 0xc210185720, 0x0, 0x0)
	/usr/local/go/src/pkg/net/http/server.go:1622 +0x91
github.com/docker/docker/api/server.(*HttpServer).Serve(0xc210185dc0, 0x4, 0xc2100b5967)
	/go/src/github.com/docker/docker/api/server/server.go:51 +0x3a
github.com/docker/docker/api/server.func·006()
	/go/src/github.com/docker/docker/api/server/server.go:1634 +0x206
created by github.com/docker/docker/api/server.ServeApi
	/go/src/github.com/docker/docker/api/server/server.go:1635 +0x3f1
```

**Comment by cpuguy83** [comment]
@HuKeping Hi, thanks for the report!  This got resolved in #10243

**Comment by HuKeping** [comment]
OK, so fast........
