### PR TITLE
builder: fix copy —from conflict with force pull

### LINKED ISSUE #1751: Multi-stage builds
I have a simple multi-stage Dockerfile very similar to the example at: https://docs.docker.com/engine/userguide/eng-image/multistage-build/#name-your-build-stages

It builds perfectly on a Linux machine with: 
> Docker version v17.05.0-ce, (89658be)

But, using the exact same codebase and Dockerfile on:
> Docker for-mac edge v17.06.0-rc4-ce-mac15 (18357)

It fails at the `COPY --from=builder` directive with: `invalid from flag value builder: repository sha256 not found: does not exist or no pull access`

Has anyone else tried this? I'm unclear if this is a bug or a known limitation?

### PR DESCRIPTION
**Pull request by tonistiigi**
fixes https://github.com/docker/for-mac/issues/1751

@dnephin @thaJeztah 

Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

### CODE REVIEW

**Comment by vieux** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

File: daemon/build.go [hunk 1]
```diff
@@ -104,13 +105,19 @@ func (daemon *Daemon) pullForBuilder(ctx context.Context, name string, authConfi
 // Every call to GetImageAndReleasableLayer MUST call releasableLayer.Release() to prevent
 // leaking of layers.
 func (daemon *Daemon) GetImageAndReleasableLayer(ctx context.Context, refOrID string, opts backend.GetImageAndLayerOptions) (builder.Image, builder.ReleaseableLayer, error) {
-	if !opts.ForcePull {
-		image, _ := daemon.GetImage(refOrID)
+	id, _ := daemon.GetImageID(refOrID)
+	refIsID := id.String() == refOrID // detect if ref is an ID to skip pulling
```
Comment (dnephin) [inline daemon/build.go]: Shouldn't this use `strings.HasPrefix()` ? A prefix ID passed to `refOrID` would still be valid.

Or an even safer option would be to split up `GetImageID()` so that the first part (which checks if it's a reference or an image) can be exposed here.

Comment (tonistiigi) [inline daemon/build.go]: I'm not sure how safe that would be. Prefix ID and references are ambiguous. If the prefix matches local image it doesn't really mean that pulling would never be needed. Probably ok to assume that `--pull` and ambiguous explicit local IDs don't work together, if not then security suffers a bit. In this case full ID is automatically taken from build stage, so the user never sets it.

Comment (dnephin) [inline daemon/build.go]: True, if we split up `GetImage()` to expose the "is ref or ID logic" then we don't have to worry about it.

Comment (tonistiigi) [inline daemon/build.go]: The logic in `GetImageID` just tries to find a local image match based on checks with different priorities. It doesn't do know anything about if that ref may exist in registry or not. "ref or ID" is determined by 1) unambiguous full-length match 2) searching prefix from local imagestore.

It just depends what we consider `--pull` semantics to be. If it is `docker pull && docker run` then current is correct. If it is `docker pull || true && docker run` then it has some potential attack vectors if the registry is unreachable.

Comment (dnephin) [inline daemon/build.go]: My point is that this determination of `refIsID` is incorrect. The correct logic is in `GetImageID()`. We should re-use that logic.

Comment (tonistiigi) [inline daemon/build.go]: I don't know what you mean by it being incorrect. It uses `GetImageID` specifically to only have single code-path for this detection.

This returns the previous(checked 17.03) `docker pull && docker run` semantics as it is a bugfix to `17.06` multi-stage build regression. If you want to change the semantics we can discuss that(though I think I disagree) but shouldn't be part of this PR.

Comment (dnephin) [inline daemon/build.go]: I'm not suggesting we change the semantics. I'm saying I don't think the fix is correct. It only partially fixes the bug. Calling this method with partial IDs and pull is still going to fail, isn't it?

Comment (tonistiigi) [inline daemon/build.go]: >  Calling this method with partial IDs and pull is still going to fail, isn't it?

Yes, exactly like it failed in `17.03` as well.

Comment (dnephin) [inline daemon/build.go]: Are you suggesting that is the correct behaviour?

I think this bug has existed for a while, we just exposed it by adding new features that make it more obvious. Why would we only half fix the bug?

Comment (tonistiigi) [inline daemon/build.go]: I don't think there is obvious correct behavior. It's a compromise between ux and security/correctness. I don't think `17.06` semantics are accidental.

Comment (dnephin) [inline daemon/build.go]: It seems accidental to me. 

If you're sure that the old failures are "correct" then I still don't think this is the right fix. The caller should pass it `Pull = false` when it's using an ID from the cache.

I'm going to submit a PR to this branch to show what I mean about using the logic from `GetImageID()`.

**Comment by vdemeester** [comment]
@tonistiigi needs a rebase 👼 🙏

File: api/types/backend/build.go [hunk 2]
```diff
@@ -7,6 +7,15 @@ import (
 	"github.com/docker/docker/pkg/streamformatter"
 )
 
+const (
+	// PullFlagNoPull only returns local images
+	PullFlagNoPull int = iota
```
Comment (dnephin) [inline api/types/backend/build.go]: Maybe a `type PullOption int` here instead of int so the supported values are easier to discover?

**Review by dnephin — COMMENTED** [review]
One minor thing, otherwise looks good

**Comment by tonistiigi** [comment]
The updated version seems to cause failure to `docker-py` test https://github.com/docker/docker-py/blob/master/tests/integration/api_container_test.py#L1142-L1143

Looking at this test, it seems wrong as it doesn't create any data and so there isn't anything to reclaim. If I change container command to create data the tests starts to pass fine. So it seems that it was caused by some other state, but I'm not sure how the changes in here could have any effect.

@dnephin @shin-

**Comment by tonistiigi** [comment]
Same test is failing in other PRs. So not related to these changes

**Comment by shin-** [comment]
I can change the test. It works on current releases though, which is odd (?)

**Comment by shin-** [comment]
@tonistiigi does it work if you use https://github.com/docker/docker-py/pull/1659/commits/9b9fb0aa0140cae1fc2c6eb549f2615501453eb9 ?

**Comment by tonistiigi** [comment]
@shin- It should. That's exactly what I tried myself before.

**Comment by shin-** [comment]
ok, merged. You can bump `DOCKER_PY_COMMIT` to `a962578e515185cf06506050b2200c0b81aa84ef` in the relevant files

**Comment by thaJeztah** [comment]
docker-py was bumped in https://github.com/moby/moby/pull/33757

**Review by thaJeztah — APPROVED** [review]
looks like https://github.com/moby/moby/pull/33735#discussion_r123072508 was addressed, and we have two LGTM's
