### PR TITLE
Fixed `raw` mode splunk logger

### LINKED ISSUE #34749: Splunk logger not transmitting log data when tag is empty
**Description**
Running Docker with the Splunk log driver in raw mode and tag="" I don't see any data in Splunk from my application.

daemon/logger/splunk/splunk.go implies tag="" will cause the tag to be omitted and log entries will be sent to Splunk.

If I set tag="-" or some other string the logs from my application are visible in Splunk with the tag prefix.

**Steps to reproduce the issue:**
1. Have a docker image which sends some data to stdout
2. 
```
docker run --rm --log-driver=splunk \
--log-opt splunk-format=raw \
--log-opt splunk-index=lab \
--log-opt splunk-insecureskipverify=true \
--log-opt splunk-source="test" \
--log-opt splunk-token=<my splunk token>\
--log-opt splunk-url=<my splunk url> \
--log-opt tag="" \
 <imageId>
```

**Describe the results you received:**
I see logs from my application appearing in stdout.
I do not see any of those appearing in splunk

**Describe the results you expected:**
I expect Splunk to contain an exact replica of the content of stdout

**Additional information you deem important (e.g. issue happens only occasionally):**
Using 
--log-opt tag="-" \
I see entries in Splunk with the prefix "- ".

**Output of `docker version`:**

```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:12:06 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:19 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 17.06.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.41-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: VSP6:DTQJ:CRIQ:JSTP:QETN:HCXZ:CHD3:YTPB:P7ZO:6DNQ:M5SE:UPWO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 31
 System Time: 2017-09-06T16:33:17.602339091Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by fnoeding**
fixes https://github.com/moby/moby/issues/34749

**- What I did**
I tried to use the Splunk logger with the raw format without a tag. I noticed that my logs stopped appearing in Splunk, after an empty line was produced by my docker containers. Since the splunk log driver will repeatedly try to submit the invalid log event, no more logs will be accepted by Splunk.

Here's a minimal sample of my configuration:
```
docker run \
	--rm \
	-it \
	--log-driver splunk \
	--log-opt splunk-token=${SPLUNK_TOKEN} \
	--log-opt splunk-url=http://127.0.0.1:8088 \
	--log-opt splunk-format=raw \
	--log-opt tag="" \
	--hostname ${HOSTNAME} \
	alpine \
	/bin/sh -c "for i in \`seq 10\`; do echo \"hello world from docker \${i}\"; sleep 1; done; echo \"empty line will follow\"; echo \"\"; echo \"    \"; echo \"done\"; "
```

The first few `echo` commands will succeed, but the one with the empty or whitespace only lines will break the logging to Splunk.

**- How I did it**

First checked the behaviour of Splunk: Events with empty or whitespace-only event's are rejected by Splunk HEC. So I've added a check to the Splunk logger, that skips whitespace-only events in raw mode.

**- How to verify it**

See above. I've also extended the unit tests for the Splunk log driver

**- Description for the changelog**

Fixed raw mode Splunk logger when used without a tag

### CODE REVIEW

**Comment by fnoeding** [comment]
Failed checks are due to an unrelated error:
```
14:37:34 FAIL: docker_cli_search_test.go:47: DockerSuite.TestSearchCmdOptions
14:37:34 
14:37:34 docker_cli_search_test.go:72:
14:37:34     c.Assert(outSearchCmdOfficialSlice, checker.HasLen, 3) // 1 header, 1 line, 1 carriage return
14:37:34 ... obtained []string = []string{"NAME      DESCRIPTION   STARS     OFFICIAL   AUTOMATED", ""}
14:37:34 ... n int = 3
14:37:34 
14:37:34
```

Do you know if there's already a fix for this? If so, I can rebase.

**Comment by thaJeztah** [comment]
failing test looks like an issue with Docker Hub, or CI not able to reach docker hub; let me trigger CI again

**Comment by fnoeding** [comment]
@thaJeztah still the same issue. Can you retry again?

File: daemon/logger/splunk/splunk.go [hunk 1]
```diff
@@ -366,6 +367,10 @@ func (l *splunkLoggerRaw) Log(msg *logger.Message) error {
 	message := l.createSplunkMessage(msg)
 
 	message.Event = string(append(l.prefix, msg.Line...))
+	// empty or whitespace-only mesages are not accepted by HEC
+	if strings.TrimSpace(message.Event.(string)) == "" {
```
Comment (thaJeztah) [inline daemon/logger/splunk/splunk.go]: Wondering if it would be a problem to just check the `msg.Line`, and don't take the prefix into account; if line is empty, basically we'd just be logging the prefixes.

Just thinking out loud here, so happy to hear what others think

Comment (fnoeding) [inline daemon/logger/splunk/splunk.go]: makes sense to me, I'll update the code

Comment (fnoeding) [inline daemon/logger/splunk/splunk.go]: updated

**Comment by fnoeding** [comment]
Build on `z` failed due to
```
10:59:55 FAIL: check_test.go:348: DockerSwarmSuite.TearDownTest
10:59:55 
10:59:55 unmount of /tmp/docker-execroot/d61562b5a35e9/netns failed: invalid argument
10:59:55 unmount of /tmp/docker-execroot/d61562b5a35e9/netns failed: no such file or directory
10:59:55 unmount of /tmp/docker-execroot/d68dcf869d700/netns failed: invalid argument
10:59:55 unmount of /tmp/docker-execroot/d68dcf869d700/netns failed: no such file or directory
10:59:55 unmount of /tmp/docker-execroot/df1308656c60e/netns failed: no such file or directory
10:59:55 unmount of /tmp/docker-execroot/d09af4e542c7d/netns failed: no such file or directory
10:59:55 check_test.go:353:
10:59:55     d.Stop(c)
10:59:55 daemon/daemon.go:392:
10:59:55     t.Fatalf("Error while stopping the daemon %s : %v", d.id, err)
10:59:55 ... Error: Error while stopping the daemon d4ea919fa4f84 : exit status 130
10:59:55 
10:59:55 
10:59:55 ----------------------------------------------------------------------
10:59:55 PANIC: docker_api_swarm_test.go:757: DockerSwarmSuite.TestAPISwarmRestartCluster
```

Retry again?

File: daemon/logger/splunk/splunk.go [hunk 2]
```diff
@@ -363,6 +364,11 @@ func (l *splunkLoggerJSON) Log(msg *logger.Message) error {
 }
 
 func (l *splunkLoggerRaw) Log(msg *logger.Message) error {
+	// empty or whitespace-only messages are not accepted by HEC
+	if strings.TrimSpace(string(msg.Line)) == "" {
```
Comment (thaJeztah) [inline daemon/logger/splunk/splunk.go]: one more thing I was thinking, as performance may be important for logging; should we check for real empty first? e.g.;

```go
if len(msg.Line) == 0 || strings.TrimSpace(....
```

(sorry, I'm traveling, reading all notifications from my phone :sweat_smile:)

Comment (fnoeding) [inline daemon/logger/splunk/splunk.go]: I believe performance at this place is not of sufficient importance to make the logic more complicated:
- most lines will not be empty or whitespace only, so the common case is a line that will be logged
- whenever a line is logged we write data to kernel space. A syscall is probably much more expensive than TrimSpace
- but if you know of a better way of checking "string has at least one non-whitespace character" that would be a nice improvement

Comment (fnoeding) [reply daemon/logger/splunk/splunk.go]: @thaJeztah do you have further feedback for me? And how can we get this merged soon?

**Comment by fnoeding** [comment]
@tiborvass any further feedback to get this merged? :)

**Comment by fnoeding** [comment]
@thaJeztah @tiborvass how can I help to get this merged?

**Review by thaJeztah — APPROVED** [review]
sorry for the delay; LGTM, thanks!

ping @cpuguy83 @vieux PTAL

**Review by vdemeester — APPROVED** [review]
LGTM 🐮
