### PR TITLE
LCOW: lazycontext: Use correct lstat, fix archive check

### LINKED ISSUE #36793: LCOW builder uses wrong cache layer.
**Description**

If an image is rebuild with different content but with the same name, builder continues to use the old layers as cache.

**Steps to reproduce the issue:**
1. First Dockerfile:
    ```
    FROM alpine
    RUN echo 1 > /test.txt
    ```
    Second Dockerfile:
    ```
    FROM alpine
    RUN echo 2 > /test.txt
    ```
    Third Dockerfile:
    ```
    FROM alpine
    COPY --from=testcachelinux /test.txt /t.txt
    RUN cat /t.txt
    ```
2. Run the following build commands:
    `docker build --platform=linux -t testcachelinux 1`
    `docker build --platform=linux -t testusecachelinux 3`
    `docker build --platform=linux -t testcachelinux 2`
    `docker build --platform=linux -t testusecachelinux 3`

**Describe the results you received:**
Outputs:
```
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM alpine
 ---> 3fd9065eaf02
Step 2/2 : RUN echo 1 > /test.txt
 ---> Running in 9d984852bca6
Removing intermediate container 9d984852bca6
 ---> 886af9e109ed
Successfully built 886af9e109ed
Successfully tagged testcachelinux:latest
```
```
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM alpine
 ---> 3fd9065eaf02
Step 2/3 : COPY --from=testcachelinux /test.txt /t.txt
 ---> c29dd34dfe6c
Step 3/3 : RUN cat /t.txt
 ---> Running in 6bdb005480a5
1
Removing intermediate container 6bdb005480a5
 ---> 226c261ba92d
Successfully built 226c261ba92d
Successfully tagged testusecachelinux:latest
```
```
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM alpine
 ---> 3fd9065eaf02
Step 2/2 : RUN echo 2 > /test.txt
 ---> Running in cc315eee2de6
Removing intermediate container cc315eee2de6
 ---> c073b79f83fd
Successfully built c073b79f83fd
Successfully tagged testcachelinux:latest
```
```
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM alpine
 ---> 3fd9065eaf02
Step 2/3 : COPY --from=testcachelinux /test.txt /t.txt
 ---> Using cache
 ---> c29dd34dfe6c
Step 3/3 : RUN cat /t.txt
 ---> Using cache
 ---> 226c261ba92d
Successfully built 226c261ba92d
Successfully tagged testusecachelinux:latest
```

**Describe the results you expected:**
Output of the last command should be:
```
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM alpine
 ---> 3fd9065eaf02
Step 2/3 : COPY --from=testcachelinux /test.txt /t.txt
 ---> SomeOtherId
Step 3/3 : RUN cat /t.txt
 ---> Running in SomeOtherId
2
Removing intermediate container SomeOtherId
 ---> SomeOtherId
Successfully built SomeOtherId
Successfully tagged testusecachelinux:latest
```

**Additional information you deem important (e.g. issue happens only occasionally):**
This is not an issue for windows containers. If you want to try here are the Dockerfiles and commands:

First Dockerfile:
```
# escape=`
FROM microsoft/windowsservercore
RUN echo 1 > C:\test.txt
```

Second Dockerfile:
```
# escape=`
FROM microsoft/windowsservercore
RUN echo 2 > C:\test.txt
```

Third Dockerfile:
```
# escape=`
FROM microsoft/windowsservercore
COPY --from=testcachewindows C:\test.txt C:\t.txt
RUN type C:\t.txt
```

Commands:
`docker build -t testcachewindows 1`
`docker build -t testusecachewindows 3`
`docker build -t testcachewindows 2`
`docker build -t testusecachewindows 3`

Outputs:
```
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM microsoft/windowsservercore
 ---> 1a599239a62c
Step 2/2 : RUN echo 1 > C:\test.txt
 ---> Running in 6f3ac59af048
Removing intermediate container 6f3ac59af048
 ---> d9a87b04fe65
Successfully built d9a87b04fe65
Successfully tagged testcachewindows:latest
```

```
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM microsoft/windowsservercore
 ---> 1a599239a62c
Step 2/3 : COPY --from=testcachewindows C:\test.txt C:\t.txt
 ---> 28280943f396
Step 3/3 : RUN type C:\t.txt
 ---> Running in 46ca27f3968d
1
Removing intermediate container 46ca27f3968d
 ---> cacf919a2ee2
Successfully built cacf919a2ee2
Successfully tagged testusecachewindows:latest
```

```
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM microsoft/windowsservercore
 ---> 1a599239a62c
Step 2/2 : RUN echo 2 > C:\test.txt
 ---> Running in d25ebc2638b5
Removing intermediate container d25ebc2638b5
 ---> e6533c599c75
Successfully built e6533c599c75
Successfully tagged testcachewindows:latest
```

```
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM microsoft/windowsservercore
 ---> 1a599239a62c
Step 2/3 : COPY --from=testcachewindows C:\test.txt C:\t.txt
 ---> 9feb73000076
Step 3/3 : RUN type C:\t.txt
 ---> Running in b77b405761e4
2
Removing intermediate container b77b405761e4
 ---> 630e7799bf98
Successfully built 630e7799bf98
Successfully tagged testusecachewindows:latest
```

**Output of `docker version`:**

```
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:06:28 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:21:06 2018
  OS/Arch:      windows/amd64
  Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 10
Server Version: 18.03.0-ce
Storage Driver: windowsfilter (windows) lcow (linux)
 Windows:
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 15.89GiB
Name: YUSUFG-PC
ID: 7BCW:GTLJ:2FQB:KV3J:NRRE:IHTW:6C3B:YOCE:65GK:NKHJ:IS3D:3LNJ
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 23
 System Time: 2018-04-05T16:10:42.9263824+03:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard <jhoward@microsoft.com>

Fixes #36793. Replacement for https://github.com/moby/moby/pull/37316

First - thanks @yusuf-gunaydin for debugging and coming up with a fix. Yours was so very close :)

Here's the output using the same files as described in https://github.com/moby/moby/issues/36793 with the updated fix:

```
PS E:\docker\build\36793> docker build --platform=linux -t testcachelinux 1
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM alpine
latest: Pulling from library/alpine
ff3a5c916c92: Pull complete
Digest: sha256:e1871801d30885a610511c867de0d6baca7ed4e6a2573d506bbec7fd3b03873f
Status: Downloaded newer image for alpine:latest
 ---> 3fd9065eaf02
Step 2/2 : RUN echo 1 > /test.txt
 ---> Running in 260838f99d98
Removing intermediate container 260838f99d98
 ---> e09ed90c53b3
Successfully built e09ed90c53b3
Successfully tagged testcachelinux:latest
```

```
PS E:\docker\build\36793> docker build --platform=linux -t testusecachelinux 3
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM alpine
 ---> 3fd9065eaf02
Step 2/3 : COPY --from=testcachelinux /test.txt /t.txt
 ---> a68b85ea733c
Step 3/3 : RUN cat /t.txt
 ---> Running in 49834d78be86
1
Removing intermediate container 49834d78be86
 ---> be1ac7fc3569
Successfully built be1ac7fc3569
Successfully tagged testusecachelinux:latest
```

```
PS E:\docker\build\36793> docker build --platform=linux -t testcachelinux 2
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM alpine
 ---> 3fd9065eaf02
Step 2/2 : RUN echo 2 > /test.txt
 ---> Running in 004c92e53c89
Removing intermediate container 004c92e53c89
 ---> c6ed3a426e67
Successfully built c6ed3a426e67
Successfully tagged testcachelinux:latest
```

```
PS E:\docker\build\36793> docker build --platform=linux -t testusecachelinux 3
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM alpine
 ---> 3fd9065eaf02
Step 2/3 : COPY --from=testcachelinux /test.txt /t.txt
 ---> a02aa0e250d1
Step 3/3 : RUN cat /t.txt
 ---> Running in fa75974f48e8
2
Removing intermediate container fa75974f48e8
 ---> bce0113cecf4
Successfully built bce0113cecf4
Successfully tagged testusecachelinux:latest
PS E:\docker\build\36793>
```

Note on the last build step:

- Step 2/3 correctly does NOT use the cache.
- Step 3/3 correctly outputs 2 and tags `bce0113cef4` correctly.

During debugging this (happened to be building the Microsoft/opengcs repo as that exercises LCOW code quite well in lieu of format CI yet), as mentioned in the issue, I noticed that as the `Lstat` call is now being made, and can succeed, there's an incorrect assertion in generating the hash (`prepareHash` function) when it calls into the archiver to Canonicalise the path, which causes build failures to occur on a step such as `COPY --from=runc /usr/bin/runc /usr/bin`. Have removed the incorrect assertion, updated the function to no longer return an `error`, and updated unit tests/call-sites not to handle the error there.

### CODE REVIEW

**Comment by jhowardmsft** [comment]
@johnstep PTAL

**Comment by jhowardmsft** [comment]
@cpuguy83 This addresses your feedback on the original PR: https://github.com/moby/moby/pull/37316#issuecomment-398930594

File: pkg/archive/archive_windows.go [hunk 1]
```diff
@@ -26,15 +26,8 @@ func getWalkRoot(srcPath string, include string) string {
...
-func CanonicalTarNameForPath(p string) (string, error) {
-	// windows: convert windows style relative path with backslashes
-	// into forward slashes. Since windows does not allow '/' or '\'
-	// in file names, it is mostly safe to replace however we must
-	// check just in case
-	if strings.Contains(p, "/") {
-		return "", fmt.Errorf("Windows path contains forward slash: %s", p)
-	}
-	return strings.Replace(p, string(os.PathSeparator), "/", -1), nil
+func CanonicalTarNameForPath(p string) string {
```
Comment (tonistiigi) [inline pkg/archive/archive_windows.go]: That seems same as `filepath.ToSlash()`

Comment (jhowardmsft) [reply pkg/archive/archive_windows.go]: Ha, yes, indeed. Not sure how long it's been like that. Will update.

Comment (jhowardmsft) [reply pkg/archive/archive_windows.go]: Pushed update

File: pkg/archive/archive_windows_test.go [hunk 2]
```diff
@@ -36,19 +36,13 @@ func TestCopyFileWithInvalidDest(t *testing.T) {
 func TestCanonicalTarNameForPath(t *testing.T) {
 	cases := []struct {
 		in, expected string
-		shouldFail   bool
 	}{
-		{"foo", "foo", false},
-		{"foo/bar", "___", true}, // unix-styled windows path must fail
```
Comment (cpuguy83) [inline pkg/archive/archive_windows_test.go]: Can we keep this case?

File: pkg/archive/archive_windows.go (hunk 1 above)
Comment (tonistiigi) [reply pkg/archive/archive_windows.go]: I thought just removing this function completely but that can be a follow-up.

**Review by cpuguy83 — CHANGES_REQUESTED** [review]

File: pkg/archive/archive_windows_test.go (hunk 2 above)
Comment (tonistiigi) [reply pkg/archive/archive_windows_test.go]: @cpuguy83 Is is a desired behavior for these paths to fail? I would think not.

Comment (cpuguy83) [reply pkg/archive/archive_windows_test.go]: Not fail but stay the same at least.

Comment (jhowardmsft) [reply pkg/archive/archive_windows_test.go]: Sure, added back in and updated to check they stay the same.

**Comment by tonistiigi** [comment]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by jhowardmsft** [comment]
@thaJeztah Is this a known failure in experimental and Janky - both failed the same, but restarted:

```
01:12:21.330 PASS: docker_api_swarm_test.go:201: DockerSwarmSuite.TestAPISwarmPromoteDemote	6.708s
01:13:30.804 
01:13:30.804 ----------------------------------------------------------------------
01:13:30.805 FAIL: check_test.go:347: DockerSwarmSuite.TearDownTest
01:13:30.805 
01:13:30.805 check_test.go:352:
01:13:30.805     d.Stop(c)
01:13:30.805 /go/src/github.com/docker/docker/internal/test/daemon/daemon.go:401:
01:13:30.805     t.Fatalf("Error while stopping the daemon %s : %v", d.id, err)
01:13:30.805 ... Error: Error while stopping the daemon df4a0aa9ac2f8 : exit status 130
01:13:30.805 
01:13:30.805 
01:13:30.805 ----------------------------------------------------------------------
01:13:30.805 PANIC: docker_api_swarm_test.go:359: DockerSwarmSuite.TestAPISwarmRaftQuorum
01:13:30.806 
01:13:30.806 [df4a0aa9ac2f8] waiting for daemon to start
01:13:30.806 [df4a0aa9ac2f8] daemon started
01:13:30.806 
01:13:30.806 [dda6fed517a8f] waiting for daemon to start
01:13:30.806 [dda6fed517a8f] daemon started
01:13:30.806 
01:13:30.806 [da0cd054b9b3e] waiting for daemon to start
01:13:30.806 [da0cd054b9b3e] daemon started
01:13:30.806 
01:13:30.806 [dda6fed517a8f] exiting daemon
01:13:30.806 [da0cd054b9b3e] exiting daemon
01:13:30.806 [dda6fed517a8f] waiting for daemon to start
01:13:30.806 [dda6fed517a8f] daemon started
01:13:30.806 
01:13:30.806 [df4a0aa9ac2f8] daemon started
01:13:30.806 Attempt #2: daemon is still running with pid 12513
01:13:30.806 Attempt #3: daemon is still running with pid 12513
01:13:30.807 Attempt #4: daemon is still running with pid 12513
01:13:30.807 [df4a0aa9ac2f8] exiting daemon
01:13:30.807 ... Panic: Fixture has panicked (see related PANIC)
01:13:30.807 
01:13:30.807 ----------------------------------------------------------------------
```

**Comment by thaJeztah** [comment]
Janky https://jenkins.dockerproject.org/job/Docker-PRs/49887/console failing on a flaky test; tracked through https://github.com/moby/moby/issues/36501

```
02:12:32 FAIL: docker_api_swarm_service_test.go:33: DockerSwarmSuite.TestAPIServiceUpdatePort
02:12:32 
02:12:32 [d7565f4084109] waiting for daemon to start
02:12:32 [d7565f4084109] daemon started
02:12:32 
02:12:32 docker_api_swarm_service_test.go:39:
02:12:32     waitAndAssert(c, defaultReconciliationTimeout, d.CheckActiveContainerCount, checker.Equals, 1)
02:12:32 docker_utils_test.go:435:
02:12:32     c.Assert(v, checker, args...)
02:12:32 ... obtained int = 0
02:12:32 ... expected int = 1
02:12:32 
02:12:32 [d7565f4084109] exiting daemon


02:37:31 FAIL: docker_cli_swarm_test.go:1605: DockerSwarmSuite.TestSwarmPublishDuplicatePorts
02:37:31 
02:37:31 [d46e0af83d092] waiting for daemon to start
02:37:31 [d46e0af83d092] daemon started
02:37:31 
02:37:31 docker_cli_swarm_test.go:1613:
02:37:31     // make sure task has been deployed.
02:37:31     waitAndAssert(c, defaultReconciliationTimeout, d.CheckActiveContainerCount, checker.Equals, 1)
02:37:31 docker_utils_test.go:435:
02:37:31     c.Assert(v, checker, args...)
02:37:31 ... obtained int = 0
02:37:31 ... expected int = 1
02:37:31 
02:37:31 [d46e0af83d092] exiting daemon
```

Experimental https://jenkins.dockerproject.org/job/Docker-PRs-experimental/41137 also failing on a flaky test (tracked through https://github.com/moby/moby/issues/37246)

```
01:58:43 FAIL: docker_cli_daemon_test.go:1490: DockerDaemonSuite.TestRunContainerWithBridgeNone
01:58:43 
01:58:43 [dac3baa3784d0] waiting for daemon to start
01:58:43 [dac3baa3784d0] daemon started
01:58:43 
01:58:43 docker_cli_daemon_test.go:1514:
01:58:43     c.Assert(out, check.Equals, fmt.Sprintf("%s", stdout),
01:58:43         check.Commentf("The network interfaces in container should be the same with host when --net=host when bridge network is disabled: %s", out))
```

**Comment by thaJeztah** [comment]
None of those failures are related in any way, so I'll go ahead and merge
