### PR TITLE
Fix network name masking network ID on delete

### LINKED ISSUE #32689: Distinguishing between names and ids?
When you run

docker network create net_1

a new network is created and its id is returned: 88bc727969193ae1b2958cbb24f95796b79085917c33addccffea0068e7a5066

Feeling mischievous, you can use this id as the name for another new network:

docker network create 88bc727969193ae1b2958cbb24f95796b79085917c33addccffea0068e7a5066

This then seems to create some ambiguity for the meaning of:

docker network rm 88bc727969193ae1b2958cbb24f95796b79085917c33addccffea0068e7a5066

I don't know if this is an issue for anybody at all, but I thought I'd share it anyway...

docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:42:29 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:42:29 2017
 OS/Arch:      linux/amd64
 Experimental: false

docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 9
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /docker-workdir/aufs
 Backing Filesystem: extfs
 Dirs: 63
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 0yzfgikq7n2e1rodqdyxs7mxp
 Is Manager: false
 Node Address: ...
 Manager Addresses:
  ...:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.19.0-80-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 991.5 MiB
Name: ...
ID: Q7FR:AKBW:WOOI:P4QK:I6ZR:4GAP:TL5T:GBUR:PIFJ:GTFE:ZZKC:VIOW
Docker Root Dir: /docker-workdir
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

### PR DESCRIPTION
**Pull request by thaJeztah**
fixes https://github.com/moby/moby/issues/32689

If a network is created with a name that matches another network's ID, the network with that name was masking the other network's ID.

As a result, it was not possible to remove the network with a given ID.

This patch changes the order in which networks are matched to be what we use for other cases;

1. Match on full ID
2. Match on full Name
3. Match on Partial ID

Before this patch:

    $ docker network create foo
    336717eac9eaa3da6557042a04efc803f7e8862ce6cf96f6b9565265ba5c618b

    $ docker network create 336717eac9eaa3da6557042a04efc803f7e8862ce6cf96f6b9565265ba5c618b
    4a698333f1197f20224583abce14876d7f25fdfe416a8545927006c315915a2a

    $ docker network ls
    NETWORK ID          NAME                                                               DRIVER              SCOPE
    4a698333f119        336717eac9eaa3da6557042a04efc803f7e8862ce6cf96f6b9565265ba5c618b   bridge              local
    d1e40d43a2c0        bridge                                                             bridge              local
    336717eac9ea        foo                                                                bridge              local
    13cf280a1bbf        host                                                               host                local
    d9e4c03728a0        none                                                               null                local

    $ docker network rm 336717eac9eaa3da6557042a04efc803f7e8862ce6cf96f6b9565265ba5c618b
    4a698333f1197f20224583abce14876d7f25fdfe416a8545927006c315915a2a

    $ docker network ls
    NETWORK ID          NAME                DRIVER              SCOPE
    d1e40d43a2c0        bridge              bridge              local
    336717eac9ea        foo                 bridge              local
    13cf280a1bbf        host                host                local
    d9e4c03728a0        none                null                local

After this patch:

    $ docker network create foo
    2d1791a7def4e2a1ef0f6b83c6add333df0bb4ced2f196c584cb64e6bd94b835

    $ docker network create 2d1791a7def4e2a1ef0f6b83c6add333df0bb4ced2f196c584cb64e6bd94b835
    6cbc749a529cd2d9d3b10566c84e56c4203dd88b67417437b5fc7a6e955dd48f

    $ docker network ls
    NETWORK ID          NAME                                                               DRIVER              SCOPE
    6cbc749a529c        2d1791a7def4e2a1ef0f6b83c6add333df0bb4ced2f196c584cb64e6bd94b835   bridge              local
    166c943dbeb5        bridge                                                             bridge              local
    2d1791a7def4        foo                                                                bridge              local
    6c45b8aa6d8e        host                                                               host                local
    b11c96b51ea7        none                                                               null                local

    $ docker network rm 2d1791a7def4e2a1ef0f6b83c6add333df0bb4ced2f196c584cb64e6bd94b835
    2d1791a7def4e2a1ef0f6b83c6add333df0bb4ced2f196c584cb64e6bd94b835

    $ docker network ls
    NETWORK ID          NAME                                                               DRIVER              SCOPE
    6cbc749a529c        2d1791a7def4e2a1ef0f6b83c6add333df0bb4ced2f196c584cb64e6bd94b835   bridge              local
    166c943dbeb5        bridge                                                             bridge              local
    6c45b8aa6d8e        host                                                               host                local
    b11c96b51ea7        none                                                               null                local

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>

**- What I did**

**- How I did it**

**- How to verify it**

See steps above

**- Description for the changelog**

   Fix network names being able to mask another network's ID

**- A picture of a cute animal (not mandatory but encouraged)**

corn snake baby - imgur

Picture: [Corn snake baby by isoldael](http://imgur.com/gallery/bTULJYm)

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @fcrisciani @mavenugo

File: daemon/network.go [hunk 1]
```diff
@@ -32,37 +32,48 @@ func (daemon *Daemon) NetworkControllerEnabled() bool {
...
-		return nil, libnetwork.ErrNoSuchNetwork(partialID)
-	}
-	if len(list) > 1 {
-		return nil, libnetwork.ErrInvalidID(partialID)
+// GetNetworkByID function returns a network whose ID matches the given ID.
+// It fails with an error if no matching network is found.
+func (daemon *Daemon) GetNetworkByID(id string) (libnetwork.Network, error) {
+	c := daemon.netController
+	if c == nil {
+		return nil, libnetwork.ErrNoSuchNetwork(id)
```
Comment (fcrisciani) [inline daemon/network.go]: not sure if this is a possible case, but maybe should we return something more appropriate than NoSuchNetwork?

Comment (thaJeztah) [inline daemon/network.go]: I kept what was already there; other than on Windows, would there be another situation where `daemon.netController` isn't there?

Comment (thaJeztah) [inline daemon/network.go]: Oh, sorry, no this one wasn't there. Hm, I think I took it from somewhere, let me have a look

Comment (thaJeztah) [inline daemon/network.go]: Ah, yes, took it from `GetNetworkByName` below

Comment (fcrisciani) [inline daemon/network.go]: I see why you have to pass it as ErrNoSuchNetwork, so that it goes to the next check. you said on windows is nil the controller, any idea then how it works the GetNetwork there?

Comment (thaJeztah) [inline daemon/network.go]: Looks like in that situation  the network endpoints are not created; https://github.com/moby/moby/blob/cbbc28341ccc3a4597f1d1ce1259d3fbe1b29a6d/cmd/dockerd/daemon.go#L524-L526

Comment (fcrisciani) [inline daemon/network.go]: ok so basically there is no way to call this method

**Comment by fcrisciani** [comment]
LGTM

**Review by boaz0 — COMMENTED** [review]
LGTM

**Comment by ripcurld0** [comment]
@thaJeztah I think you need to rebase

**Comment by thaJeztah** [comment]
Thanks for the ping! I'll update when I get back home later tonight

**Comment by thaJeztah** [comment]
rebased

**Comment by fcrisciani** [comment]
LGTM

**Comment by thaJeztah** [comment]
ping @vdemeester PTAL 😇

File: integration-cli/docker_cli_network_unix_test.go [hunk 2]
```diff
@@ -434,6 +434,42 @@ func (s *DockerSuite) TestDockerNetworkDeleteNotExists(c *check.C) {
 	c.Assert(err, checker.NotNil, check.Commentf("%v", out))
 }
 
+// TestDockerNetworkDeletePreferID tests that if a network with a name
+// equal to another network's ID exists, the Network with the given
+// ID is removed, and not the network with the given name.
+func (s *DockerSuite) TestDockerNetworkDeletePreferID(c *check.C) {
```
Comment (dnephin) [inline integration-cli/docker_cli_network_unix_test.go]: Please make these API tests!

**Comment by thaJeztah** [comment]
ping @dnephin updated the test to use the API, PTAL

File: daemon/network.go [hunk 3]
```diff
@@ -31,37 +31,48 @@ func (daemon *Daemon) NetworkControllerEnabled() bool {
...
+	n, err := daemon.GetNetworkByID(idName)
+	if err == nil {
+		return n, nil
+	}
+	if !isNoSuchNetworkError(err) {
 		return nil, err
 	}
 
-	if n != nil {
+	// 2. match via full name and ID prefix.
```
Comment (dnephin) [inline daemon/network.go]: should "and ID prefix" be removed here? I think that's case 3 below?

File: daemon/network.go [hunk 4]
```diff
@@ -31,37 +31,48 @@ func (daemon *Daemon) NetworkControllerEnabled() bool {
...
 func (daemon *Daemon) FindNetwork(idName string) (libnetwork.Network, error) {
-	// Find by Name
-	n, err := daemon.GetNetworkByName(idName)
-	if err != nil && !isNoSuchNetworkError(err) {
+	// 1. match via full ID.
+	n, err := daemon.GetNetworkByID(idName)
+	if err == nil {
+		return n, nil
+	}
+	if !isNoSuchNetworkError(err) {
```
Comment (dnephin) [inline daemon/network.go]: Minor: this could be written as:

```go
if err == nil || !isNoSuchNetworkError(err) {
    return n, err
}
```

same below

File: integration/network/delete_test.go [hunk 5]
```diff
@@ -0,0 +1,80 @@
...
+
+	nws, err := client.NetworkList(ctx, types.NetworkListOptions{})
+	require.NoError(t, err)
+
+	assert.Equal(t, true, containsNetwork(nws, n1), "Network n1 not found")
+	assert.Equal(t, true, containsNetwork(nws, n2), "Network n2 not found")
+
+	// Delete the network using networkID. This should remove the original
+	// network, not the network with the name equal to the networkID
+	client.NetworkRemove(ctx, n1.ID)
```
Comment (dnephin) [inline integration/network/delete_test.go]: Should check that the error returned here is nil

File: integration/network/delete_test.go [hunk 6]
```diff
@@ -0,0 +1,80 @@
...
+	n1, err := client.NetworkCreate(ctx, "testNW", types.NetworkCreate{})
+	require.NoError(t, err)
+	n2, err := client.NetworkCreate(ctx, n1.ID, types.NetworkCreate{})
+	require.NoError(t, err)
+
+	nws, err := client.NetworkList(ctx, types.NetworkListOptions{})
+	require.NoError(t, err)
+
+	assert.Equal(t, true, containsNetwork(nws, n1), "Network n1 not found")
+	assert.Equal(t, true, containsNetwork(nws, n2), "Network n2 not found")
```
Comment (dnephin) [inline integration/network/delete_test.go]: Since these are just "sanity checks" that the setup was done correctly maybe this whole block (create networks, list and assert) can be moved out into a `setupOverlappingNetworks()` so that the test setup doesn't distract from the actual test case.

File: integration/network/delete_test.go [hunk 7]
```diff
@@ -0,0 +1,80 @@
...
+	nws, err = client.NetworkList(ctx, types.NetworkListOptions{})
+	require.NoError(t, err)
+	assert.Equal(t, false, containsNetwork(nws, n1), "Network n1 was not removed")
+	assert.Equal(t, true, containsNetwork(nws, n2), "Network n2 not found")
+}
+
+// TestDockerNetworkDeletePreferID tests that if a network with a name
+// equal to another network's partial ID exists, the Network with the given
+// Name is removed, and not the network with only a partially matching ID (prefix).
+func TestDockerNetworkDeletePreferFullName(t *testing.T) {
```
Comment (dnephin) [inline integration/network/delete_test.go]: This could be done in the same test case I think. If you create 3 networks and removes them in order of highest priority to lowest?

File: daemon/network.go (hunk 4 above)
Comment (thaJeztah) [reply daemon/network.go]: Yes! I like that 👍

File: daemon/network.go (hunk 3 above)
Comment (thaJeztah) [reply daemon/network.go]: Yes, leftover from an earlier iteration, thx

**Comment by thaJeztah** [comment]
ping @dnephin addressed your comments 😅

**Comment by thaJeztah** [comment]
hmm, odd one on z https://jenkins.dockerproject.org/job/Docker-PRs-s390x/6235/console;

```
20:13:09 === RUN   TestDockerNetworkDeletePreferID
20:13:40 --- FAIL: TestDockerNetworkDeletePreferID (31.03s)
20:13:40 	protect.go:127: Failed to load frozen images: ApplyLayer exit status 1 stdout:  stderr: unexpected EOF
```

**Review by dnephin — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 👼
