### PR TITLE
rootless: support --pid=host

### LINKED ISSUE #41457: rootless: `docker run --pid=host` fails with `mounting "proc" to rootfs at "/proc" caused: operation not permitted`
**Description**

`docker run --pid=host` fails with `mounting "proc" to rootfs at "/proc" caused: operation not permitted` on rootless

**Steps to reproduce the issue:**
1. `dockerd-rootless.sh`
2. `docker -H unix:///run/user/1001/docker.sock run --rm --pid=host hello-world`

**Describe the results you received:**
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:60: mounting "proc" to rootfs at "/proc" caused: operation not permitted: unknown.
```

**Describe the results you expected:**
Shouldn't fail

**Output of `docker version`:**

```
Client:
 Version:           20.03.0-dev
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        e0eba83bd
 Built:             Wed Sep 16 10:08:53 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          dev
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       f99814d749
  Built:            Wed Sep 16 10:07:13 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.4.0-81-g373cbc2a
  GitCommit:        373cbc2a7f5469b2a833660ba2f474cf4f947d32
 runc:
  Version:          1.0.0-rc92+dev
  GitCommit:        892477ca26638b214dc79150a09ba3565b93137d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.4.1)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: dev
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: none
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 373cbc2a7f5469b2a833660ba2f474cf4f947d32
 runc version: 892477ca26638b214dc79150a09ba3565b93137d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  rootless
 Kernel Version: 5.4.0-47-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.748GiB
 Name: suda-ws01
 ID: CWVR:KJQU:3CNT:IJF7:FMME:22Y7:GKFW:AFKJ:IVLQ:JOVW:3KZY:S25M
 Docker Root Dir: /home/suda/.local/share/docker
 Debug Mode: false
 Username: akihirosuda
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: Running in rootless-mode without cgroups. To enable cgroups in rootless-mode, you need to boot the system in cgroup v2 mode.
```

### PR DESCRIPTION
**Pull request by AkihiroSuda**
**- What I did**
rootless: support --pid=host

Fix #41457

Also port `TestRunModePIDHost` from CLI test  to API test

**- How I did it**
By substituting procfs mount with rbind (https://github.com/containers/podman/blob/v3.0.0-rc1/pkg/specgen/generate/oci.go#L248-L257)

**- How to verify it**
`DOCKER_ROOTLESS=1 TEST_SKIP_INTEGRATION_CLI=1 TESTFLAGS='-test.run TestPidHost' make test-integration`

**- Description for the changelog**

rootless: support --pid=host

**- A picture of a cute animal (not mandatory but encouraged)**

:penguin:

### CODE REVIEW

File: rootless/specconv/specconv_linux.go [hunk 1]
```diff
@@ -70,5 +74,63 @@ func toRootless(spec *specs.Spec, v2Controllers []string, currentOOMScoreAdj int
...
+		}
+	}
+	return true, nil
+}
+
+func bindMountHostProcfs(spec *specs.Spec) error {
+	// Replace procfs mount with rbind
+	// https://github.com/containers/podman/blob/v3.0.0-rc1/pkg/specgen/generate/oci.go#L248-L257
+	for i, m := range spec.Mounts {
+		if filepath.Clean(m.Destination) == "/proc" {
```
Comment (thaJeztah) [inline rootless/specconv/specconv_linux.go:114]: This can use `path.Clean` as well (instead of `filepath`. Do we want a fast-path here in case no cleaning is needed?

```suggestion
		if m.Destination == "/proc" || path.Clean(m.Destination) == "/proc" {
```

File: rootless/specconv/specconv_linux.go [hunk 2]
```diff
@@ -70,5 +74,63 @@ func toRootless(spec *specs.Spec, v2Controllers []string, currentOOMScoreAdj int
...
+				Type:        "bind",
+				Source:      "/proc",
+				Options:     []string{"rbind", "nosuid", "noexec", "nodev"},
+			}
+			spec.Mounts[i] = newM
+		}
+	}
+
+	// Remove ReadonlyPaths for /proc/*
+	var newROP []string
```
Comment (thaJeztah) [inline rootless/specconv/specconv_linux.go:126]: Not sure if premature optimisation, but could use https://github.com/golang/go/wiki/SliceTricks#filtering-without-allocating

```suggestion
newROP := spec.Linux.ReadonlyPaths[:0]
```

File: integration/internal/container/ns.go [hunk 3]
```diff
@@ -0,0 +1,20 @@
...
+	"testing"
+
+	"github.com/docker/docker/client"
+	"gotest.tools/v3/assert"
+	is "gotest.tools/v3/assert/cmp"
+)
+
+// Gets the value of the specified namespace of a container
+func GetContainerNS(ctx context.Context, t *testing.T, client client.APIClient, cID, nsName string) string {
+	res, err := Exec(ctx, client, cID, []string{"readlink", "/proc/self/ns/" + nsName})
```
Comment (thaJeztah) [inline integration/internal/container/ns.go:15]: While at it, perhaps make this helper?

```suggestion
	t.Helper()
	res, err := Exec(ctx, client, cID, []string{"readlink", "/proc/self/ns/" + nsName})
```

**Review by thaJeztah — CHANGES_REQUESTED** [review]

File: rootless/specconv/specconv_linux.go (hunk 1 above)
Comment (AkihiroSuda) [reply rootless/specconv/specconv_linux.go:114]: That makes the code longer and I feel less readable, but just my feeling

File: rootless/specconv/specconv_linux.go [hunk 4]
```diff
@@ -70,5 +74,63 @@ func toRootless(spec *specs.Spec, v2Controllers []string, currentOOMScoreAdj int
...
+	// Fix up /proc if --pid=host
+	if ok, err := isPidHost(spec); err != nil {
+		return err
+	} else if ok {
+		if err := bindMountHostProcfs(spec); err != nil {
+			return err
+		}
+	}
+
+	return nil
```
[the remark this answers is not in the document]
Comment (AkihiroSuda) [reply rootless/specconv/specconv_linux.go:87]: fixed

File: rootless/specconv/specconv_linux.go (hunk 2 above)
Comment (AkihiroSuda) [reply rootless/specconv/specconv_linux.go:126]: fixed

File: integration/internal/container/ns.go (hunk 3 above)
Comment (AkihiroSuda) [reply integration/internal/container/ns.go:15]: fixed

File: rootless/specconv/specconv_linux.go [hunk 5]
```diff
@@ -70,5 +74,63 @@ func toRootless(spec *specs.Spec, v2Controllers []string, currentOOMScoreAdj int
...
+				Options:     []string{"rbind", "nosuid", "noexec", "nodev"},
+			}
+			spec.Mounts[i] = newM
+		}
+	}
+
+	// Remove ReadonlyPaths for /proc/*
+	var newROP []string
+	for _, s := range spec.Linux.ReadonlyPaths {
+		s = filepath.Clean(s)
```
[the remark this answers is not in the document]
Comment (AkihiroSuda) [reply rootless/specconv/specconv_linux.go]: fixed

File: integration/container/pidmode_linux_test.go [hunk 6]
```diff
@@ -0,0 +1,36 @@
...
+	"time"
+
+	"github.com/docker/docker/integration/internal/container"
+	"gotest.tools/v3/assert"
+	"gotest.tools/v3/poll"
+	"gotest.tools/v3/skip"
+)
+
+func TestPidHost(t *testing.T) {
+	skip.If(t, testEnv.DaemonInfo.OSType != "linux")
```
Comment (cpuguy83) [inline integration/container/pidmode_linux_test.go:16]: Also need a case for local daemon since this won't work remotely.

Comment (AkihiroSuda) [reply integration/container/pidmode_linux_test.go:16]: done

**Review by thaJeztah — APPROVED** [review]
SGTM

**Comment by thaJeztah** [comment]
@cpuguy83 ptal

File: integration/container/run_cgroupns_linux_test.go [hunk 7]
```diff
@@ -38,7 +27,7 @@ func testRunWithCgroupNs(t *testing.T, daemonNsMode string, containerOpts ...fun
 	poll.WaitOn(t, container.IsInState(ctx, client, cID, "running"), poll.WithDelay(100*time.Millisecond))
 
 	daemonCgroup := d.CgroupNamespace(t)
-	containerCgroup := containerCgroupNamespace(ctx, t, client, cID)
+	containerCgroup := container.GetContainerNS(ctx, t, client, cID, "cgroup")
```
Comment (kolyshkin) [inline integration/container/run_cgroupns_linux_test.go:30]: This changes the code from reading `/proc/1/ns/cgroup` to `/proc/self/ns/cgroup` but the end result should be the same, so no issue here (just noticing).

Comment (AkihiroSuda) [reply integration/container/run_cgroupns_linux_test.go:30]: Yes, I know.

File: rootless/specconv/specconv_linux.go [hunk 8]
```diff
@@ -70,5 +74,62 @@ func toRootless(spec *specs.Spec, v2Controllers []string, currentOOMScoreAdj int
...
+			}
+			pidNS, err := os.Readlink(ns.Path)
+			if err != nil {
+				return false, err
+			}
+			selfPidNS, err := os.Readlink("/proc/self/ns/pid")
+			if err != nil {
+				return false, err
+			}
+			return pidNS == selfPidNS, nil
```
Comment (kolyshkin) [inline rootless/specconv/specconv_linux.go:103]: A little bit faster way would be to run stat on both pats and `return (st1.Dev == st2.Dev) && (st1.Ino == st2.Ino), nil`. Comparing symlinks is OK, too.

**Review by kolyshkin — APPROVED** [review]
LGTM

**Comment by AkihiroSuda** [comment]
Mergeable? @kolyshkin @thaJeztah

File: rootless/specconv/specconv_linux.go (hunk 1 above)
Comment (kolyshkin) [reply rootless/specconv/specconv_linux.go]: Too bad we don't have a spec requirement that the paths should be absolute and cleaned.

Hmm, a somewhat similar code in buildkit do not have `path.Clean()`:

https://github.com/moby/buildkit/blob/master/util/rootless/specconv/specconv_linux.go#L28-L29

So I'm not sure whether it is needed here.

**Comment by AkihiroSuda** [comment]
I see two LGTMs, so merging
