### PR TITLE
daemon: use the registry service config for getting registry hosts

### LINKED ISSUE #1642: BUILDKIT ignores "insecure-registries". server gave HTTP response to HTTPS client. x509: certificate error
Hello! After upgrading to Docker Engine v23.0.1 our CI process started failing due to errors accessing internal Harbor registry.
As I see [BuildKit became default in versions 23+](https://github.com/docker/cli/blob/master/docs/deprecated.md).

Unfortunately Docker BuildKit disregards configuration `insecure-registries` in `/etc/docker/daemon.json`.

All attempts to build image fail with the following errors. Needless to say that address of our Harbor registry was added to `insecure-registries`. It used to work normally with previous versions of Docker.
```
Error getting v2 registry: Get \"https://harbor.company.local/v2/\/": http: server gave HTTP response to HTTPS client"
```
```
ERROR: failed to solve: harbor.company.local/hub/library/node:16.17.0-alpine3.16: failed to do request: Head "https://harbor.company.local/v2/hub/library/node/manifests/16.17.0-alpine3.16":
 x509: certificate is valid for ingress.local, not harbor.company.local
 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
```
If we place commands like 
```bash
docker pull harbor.company.local/hub/library/node:16.17.0-alpine3.16`
```
before `docker build`, all images are pulled successfully, which is proves that docker daemon is configured correctly and all other processes keep working.

Thanks to the discussion in #1613, we managed to implement a workaround with setting `BUILDKIT_NO_CLIENT_TOKEN=true`. :+1: 
For the sake of completeness, I have to mention another issue #1589, which is related to the same or very similar problem I believe.

Another workaround was to `export DOCKER_BUILDKIT=0`.
When this variable is set, the following message appear in the logs, which is expected, I'm convinced.
```
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
BuildKit is currently disabled; enable it by removing the DOCKER_BUILDKIT=0 environment-variable.
```

Anyway, we still shall appreciate if you can fix this behaviour and make BuildKit rely on `insecure-registries` in `/etc/docker/daemon.json`.

### PR DESCRIPTION
**Pull request by jedevc**
**- What I did**

Fixes https://github.com/docker/buildx/issues/1642 (this one was an utter pain to track down :tada:)

The logic in `RegistryHosts` appears to be shared between BuildKit and the containerd snapshotter, so this may also be a [containerd related fix](https://github.com/moby/moby/blob/ee794231240b4f4087cffb434dcc67b06f402a47/daemon/daemon.go#L1065)?

> **Note**
>
> This patch fixes the above issue, but the underlying bug in the issue is actually the use of `url.Parse`, which can incorrectly parse "foo-registry:5000" with opaque data: https://play.golang.com/p/469UqjaiVhg.
>
> Instead of just fixing this directly, it makes more sense to actually just use the same logic that we already have for parsing the insecure registries config.

**- How I did it**

The logic previously used in `RegistryHosts` was duplicated logic from the config we've already parsed - however, there were significant differences in exactly the outputs it produced.

To resolve the above buildx issue, it's sufficient to just update `RegistryHosts` to use the already parsed configs, which have been validated and cleaned appropriately. We can also add support for the CIDR notation allowed in insecure-registries while we're in the area.

**- How to verify it**

See the reproduction instructions in https://github.com/docker/buildx/issues/1642#issuecomment-1624435786. Before the patches in this PR you should see:

```
#3 [internal] load metadata for foo-registry:5000/library/hello-world:linux
#3 ERROR: failed to do request: Head "https://foo-registry:5000/v2/library/hello-world/manifests/linux": http: server gave HTTP response to HTTPS client
------
 > [internal] load metadata for foo-registry:5000/library/hello-world:linux:
------
Dockerfile:1
--------------------
   1 | >>> FROM foo-registry:5000/library/hello-world:linux
   2 |     RUN ["/hello"]
--------------------
ERROR: failed to solve: foo-registry:5000/library/hello-world:linux: failed to do request: Head "https://foo-registry:5000/v2/library/hello-world/manifests/linux": http: server gave HTTP response to HTTPS client
```

And after the patches, the build should complete successfully, with no error displayed.

**- Description for the changelog**

Resolve `insecure-registries` consistently for BuildKit builds

**- A picture of a cute animal (not mandatory but encouraged)**

image

cc @tianon @tonistiigi @crazy-max

### CODE REVIEW

File: daemon/daemon.go [hunk 1]
```diff
@@ -194,42 +192,20 @@ func (daemon *Daemon) UsesSnapshotter() bool {
 // RegistryHosts returns the registry hosts configuration for the host component
 // of a distribution image reference.
```
[the remark this answers is not in the document]
Comment (jedevc) [reply daemon/daemon.go:193]: I think so, yup. We still take a host as the argument, and store the resulting hosts.

We already discarded paths/fragments/etc in this function, so no behaviour changes on that front.

**Comment by thaJeztah** [comment]
@tianon @neersighted PTAL :)

File: daemon/daemon.go [hunk 2]
```diff
@@ -194,42 +192,27 @@ func (daemon *Daemon) UsesSnapshotter() bool {
...
-			v = u.Host
+		if !v.Secure {
 			t := true
-			if u.Scheme == "http" {
-				c.PlainHTTP = &t
-			} else {
-				c.Insecure = &t
-			}
+			c.PlainHTTP = &t
+			c.Insecure = &t
```
Comment (tianon) [inline daemon/daemon.go:206]: Does this mean we assume _all_ insecure registries are plain HTTP, or is this used to trigger the "try HTTPS ignoring the cert, then fall back to HTTP" logic?  Sorry, I'm not very familiar with the underlying code here :sob:

(IMO this detection behavior of "insecure-registries" is still a misfeature and it'd be a benefit to us to go the other direction and encourage users to make it explicit, but I think I might've already lost that fight with some of the previous related PRs :see_no_evil:)

Comment (jedevc) [reply daemon/daemon.go:206]: > or is this used to trigger the "try HTTPS ignoring the cert, then fall back to HTTP" logic

Exactly this :tada: This is how we get here in BuildKit: https://github.com/moby/buildkit/blob/master/util/resolver/resolver.go#L25.

This function gets called in `resolver.NewRegistryConfig` which is called by moby, which returns the two hosts, which get tried in order (return on first success).

> and it'd be a benefit to us to go the other direction and encourage users to make it explicit, but I think I might've already lost that fight with some of the previous related PRs

I don't think this battle is necessarily lost -- given *our* lack of knowledge about how this worked, I think it's fair to assume most users don't really know. So we could make a point of deprecating the current behavior at some point, and try and require protocols.

**Review by tianon — APPROVED** [review]

**Comment by jedevc** [comment]
Looking further, this looks like this may also resolve:

> Local registry mirror configuration isn’t implemented yet with the containerd image store. The registry-mirrors and insecure-registries aren’t taken into account by the Docker daemon.

from https://docs.docker.com/desktop/containerd/#docker-desktop-4120-release.

I can't find a tracking issue for this in GitHub though, not sure if this way already fixed by something else?

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Comment by thaJeztah** [comment]
We briefly discussed this in the maintainers call. This is indeed one of the "historic" areas where a lot of context has been lost, and behavior is very under-defined. Let's get this one in for the 25.0 release at least, and if the world doesn't explode, we can consider backporting to 24.0 and 23.0 branches if needed.

**Comment by cpuguy83** [comment]
Did this need a backport?

**Comment by thaJeztah** [comment]
@cpuguy83 see my comment above, but if you think it's safe, we can still consider to already backport it

**Comment by MetSystem** [comment]
When used internally, you need to use http, and you want to configure the item to turn it on or off.
