### PR TITLE
Fix channel closing race in event tests.

### LINKED ISSUE #19207: Flaky test (?): Panic in 'TestEventsImageUntagDelete' (on experimental)
Again, not sure if this is a flaky test or a bug. Saw this on https://github.com/docker/docker/pull/18906, so thought I'd open an issue to investigate/check

https://jenkins.dockerproject.org/job/Docker-PRs-experimental/13362/console

```
03:58:57 PASS: docker_cli_events_test.go:165: DockerSuite.TestEventsImageTag	1.068s
03:59:17 
03:59:17 ----------------------------------------------------------------------
03:59:17 PANIC: docker_cli_events_unix_test.go:260: DockerSuite.TestEventsImageUntagDelete
03:59:17 
03:59:17 ... Panic: close of closed channel (PC=0x4606EE)
03:59:17 
03:59:17 /usr/local/go/src/runtime/panic.go:423
03:59:17   in gopanic
03:59:17 /usr/local/go/src/runtime/chan.go:303
03:59:17   in closechan
03:59:17 github.com/docker/docker/integration-cli/_test/_obj_test/events_utils.go:159
03:59:17   in matchEventLine.func1
03:59:17 github.com/docker/docker/integration-cli/_test/_obj_test/events_utils.go:125
03:59:17   in eventObserver.CheckEventError
03:59:17 docker_cli_events_unix_test.go:294
03:59:17   in DockerSuite.TestEventsImageUntagDelete
03:59:17 /usr/local/go/src/reflect/value.go:300
03:59:17   in Value.Call
03:59:17 /go/src/github.com/docker/docker/vendor/src/github.com/go-check/check/check.go:772
03:59:17   in suiteRunner.forkTest.func1
03:59:17 /go/src/github.com/docker/docker/vendor/src/github.com/go-check/check/check.go:666
03:59:17   in suiteRunner.forkCall.func1
03:59:17 /usr/local/go/src/runtime/asm_amd64.s:1721
03:59:17   in goexit
03:59:25 
03:59:25 ----------------------------------------------------------------------
03:59:25 PASS: docker_cli_events_test.go:96: DockerSuite.TestEventsLimit	7.435s
```

### PR DESCRIPTION
**Pull request by calavera**
Divide event matching into two functions, a matcher and
a processor. That way, the error handling doesn't call
the channel closing logic at all.
Fixes #19207

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by cpuguy83** [comment]
LGTM

File: integration-cli/events_utils.go [hunk 1]
```diff
@@ -130,7 +130,7 @@ func matchEventLine(id, eventType string, actions map[string]chan bool) eventMat
 
 		if matchIDAndEventType(matches, id, eventType) {
 			if ch, ok := actions[matches["action"]]; ok {
-				close(ch)
+				ch <- true
```
Comment (coolljt0725) [inline integration-cli/events_utils.go]: To avoid closing closed channel, It's better to use
<pre><code>select {
    	case <-ch:
    	default:
    	   close(ch)
    }</code></pre>  WDYT?

Comment (cpuguy83) [inline integration-cli/events_utils.go]: That is still racey too, unfortunately, since both can hit a select like that at the same time.

**Comment by calavera** [comment]
> wouldn't this just make a send on a closed channel

Nope, we don't close channels at all anymore. This change make that in the case of this race condition we send two messages over the same channel, which are always ignored. We only use these channels to control the test execution, receiving two messages doesn't have any meaning whatsoever.

**Comment by calavera** [comment]
This race condition happens when these three conditions occur, which is very complicated to happen:

1. The goroutine listening for events match an expected event, causing the first channel closing to happen.
2. There is a connection error and event listener enters into fallback mode.
3. At the same time, the timeout that controls the test execution in the main goroutine awakes. Since the listener is in fallback mode, before returning an error, the listener requests all the events since the start, to double check that the event it's waiting for didn't happen. It iterates over the events and matches again, closing the channel again. THIS is the moment when we panic.

Changing the logic to send a message makes this very unlikely race condition to no have any effect, and the tests finish execution as expected.

File: integration-cli/events_utils.go (hunk 1 above)
Comment (calavera) [inline integration-cli/events_utils.go]: we don't really care if the channel is closed or not, we only want to notify the main goroutine.

**Comment by aaronlehmann** [comment]
These are unbuffered channels, so if this race condition occurs after the change here, won't there be a deadlock?

1. The `go observer.Match(matcher)` goroutine blocks forever writing to the channel because nothing is reading from it.
2. The call to `CheckEventError` calls `match`, which also tries to to write to the channel, and this blocks too because nothing is reading from it.

What am I missing?

**Comment by calavera** [comment]
> What am I missing?

the tests read from those channels in a `select` statement to control execution.

https://github.com/docker/docker/blob/master/integration-cli/docker_cli_build_unix_test.go#L180-L188

```

	testActions := map[string]chan bool{
		"start": make(chan bool),
		"die":   make(chan bool),
	}

	matcher := matchEventLine(buildID, "container", testActions)
	go observer.Match(matcher)

	select {
	case <-time.After(10 * time.Second):
		observer.CheckEventError(c, buildID, "start", matcher)
	case <-testActions["start"]:
		// ignore, done
	}
```

**Comment by aaronlehmann** [comment]
But that select can't receive while it's inside the other case, which is how the race happened, as I understand it. It seems like it would turn into a deadlock, because the `<-time.After` case may try to send to `testActions["start"]`.

**Comment by calavera** [comment]
oh, I see what you mean. Yes, that might be a problem. Fixing.

**Comment by calavera** [comment]
Ok, I changed the logic completely to not call the channel logic at all when the handle the timeout errors. That way, we remove any possibility of race conditions.

**Comment by aaronlehmann** [comment]
Compile errors... but the new logic looks correct to me.

**Comment by cpuguy83** [comment]
```
18:01:36 /tmp/go-build807206413/github.com/docker/docker/integration-cli/_test/_obj_test/events_utils.go:104: multiple-value match() in single-value context
18:01:36 /tmp/go-build807206413/github.com/docker/docker/integration-cli/_test/_obj_test/events_utils.go:106: cannot use text (type string) as type map[string]string in argument to process
18:01:36 /tmp/go-build807206413/github.com/docker/docker/integration-cli/_test/_obj_test/events_utils.go:134: multiple-value match() in single-value context
```

**Comment by calavera** [comment]
it should be fixed now, thanks!

**Comment by aaronlehmann** [comment]
LGTM

**Comment by thaJeztah** [comment]
ping @cpuguy83 can you have another look?

**Comment by cpuguy83** [comment]
LGTM
