### PR TITLE
Fix `service update --env-add` issue

### LINKED ISSUE #25404: --env-add flag doesn't update the variable as the help states
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 18
 Running: 7
 Paused: 0
 Stopped: 11
Images: 10
Server Version: 1.12.0
Storage Driver: devicemapper
 Pool Name: docker-202:1-149180-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 5.9 GB
 Data Space Total: 107.4 GB
 Data Space Available: 963.2 MB
 Metadata Space Used: 8.262 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 963.2 MB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: active
 NodeID: **
 Is Manager: true
 ClusterID: **
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot interval: 10000
  Heartbeat tick: 1
  Election tick: 3
 Dispatcher:
  Heartbeat period: 5 seconds
 CA configuration:
  Expiry duration: 3 months
 Node Address: **
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-92-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859 GiB
Name: ip-10-100-20-69
ID: ***
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Steps to reproduce the issue:**
1. Create a service: i.e: `docker service create -e A=c --name test redis:latest`

`docker service inspect test --pretty` gives you the following:

```
ID:		a666bsuxvm6yem3nub2ikplyi
Name:		test
Mode:		Replicated
 Replicas:	1
Update status:
 State:		updating
 Started:	1 seconds ago
 Message:	update in progress
Placement:
UpdateConfig:
 Parallelism:	1
 On failure:	pause
ContainerSpec:
 Image:		redis:latest
 Env:		A=c
Resources:
```

You can see the environment variable has been passed. 

2. Now, update the environment variable `A` following the description of `--env-add`, which states it's used to update the variable as well as add a new one. I understand it work like an 'upsert':

`docker service update --env-add A=b test`

3. See the output of `docker service inspect test --pretty` 

```
ID:		a666bsuxvm6yem3nub2ikplyi
Name:		test
Mode:		Replicated
 Replicas:	1
Update status:
 State:		completed
 Started:	3 seconds ago
 Completed:	1 seconds ago
 Message:	update completed
Placement:
UpdateConfig:
 Parallelism:	1
 On failure:	pause
ContainerSpec:
 Image:		redis:latest
 Env:		A=c A=b
Resources:
```

**Describe the results you received:**

As it's evident, the environment variable is duplicated:

```
 Env:		A=c A=b
```

I expect the variable `A` to be updated instead.

### PR DESCRIPTION
**Pull request by yongtang**
**\- What I did**

This fix tries to address the issue in #25404 where updating environmental variable in `service update --env-add` will not work.

The issue is because `--env-add` will only append the env, not update if the same env already exist.

**\- How I did it**

This fix tracks the env variable with a map and update if the variable is the same.

**\- How to verify it**

An integration test has been added.

**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**

This fix fixes #25404.

Signed-off-by: Yong Tang yong.tang.github@outlook.com

### CODE REVIEW

**Comment by hvpareja** [comment]
Seems like it's been a punctual error: 

03:57:26 ---> Making bundle: validate-dco (in bundles/1.13.0-dev/validate-dco)
03:57:38 fatal: unable to access 'https://github.com/docker/docker.git/': Couldn't resolve host 'github.com'

Can you trigger the build again manually?

**Comment by icecrime** [comment]
Ping @dnephin @vieux!

File: integration-cli/docker_cli_swarm_test.go [hunk 1]
```diff
@@ -194,3 +194,27 @@ func (s *DockerSwarmSuite) TestSwarmNodeTaskListFilter(c *check.C) {
...
+	c.Assert(err, checker.IsNil)
+	c.Assert(strings.TrimSpace(out), checker.Equals, "[A=c]")
+
+	out, err = d.Cmd("service", "update", "--env-add", "A=b", name)
+	c.Assert(err, checker.IsNil)
+
+	out, err = d.Cmd("service", "inspect", "--format", "{{ .Spec.TaskTemplate.ContainerSpec.Env }}", name)
+	c.Assert(err, checker.IsNil)
+	c.Assert(strings.TrimSpace(out), checker.Equals, "[A=b]")
+}
```
Comment (dnephin) [inline integration-cli/docker_cli_swarm_test.go]: I don't think this needs to be an integration test.

We can fully test this change as a unit test. in `api/client/service/update_test.go`

File: api/client/service/update_test.go [hunk 2]
```diff
@@ -68,8 +68,13 @@ func TestUpdateEnvironment(t *testing.T) {
...
 	assert.Equal(t, len(envs), 2)
-	assert.Equal(t, envs[0], "tokeep=value")
-	assert.Equal(t, envs[1], "toadd=newenv")
+	// Order has been removed in updateEnvironment (map)
+	if envs[0] == "tokeep=value" {
+		assert.Equal(t, envs[1], "toadd=newenv")
+	} else {
+		assert.Equal(t, envs[0], "toadd=newenv")
+		assert.Equal(t, envs[1], "tokeep=value")
+	}
```
Comment (dnephin) [inline api/client/service/update_test.go]: How about sorting the slices instead of this condition? The `if` makes the test a bit harder to read.

Comment (yongtang) [inline api/client/service/update_test.go]: Thanks @dnephin, that makes sense. The pull request has been updated with sort.

File: integration-cli/docker_cli_swarm_test.go (hunk 1 above)
Comment (yongtang) [inline integration-cli/docker_cli_swarm_test.go]: Thanks @dnephin. The integration test has been removed and replaced with a unit test.

**Comment by dnephin** [comment]
LGTM

**Comment by thaJeztah** [comment]
retest this please

**Comment by thaJeztah** [comment]
LGTM
