### PR TITLE
Move stdio attach from libcontainerd backend to callback

### LINKED ISSUE #27011: panic: sync: WaitGroup is reused before previous Wait has returned
**Description**

Docker 1.11.2 crashed after ~3 months uptime

**Steps to reproduce the issue:**

Unknown, I just noticed it crashed.

**Describe the results you received:**

```
Jun 28 17:12:02 west systemd[1]: Starting docker.service...
Jun 28 17:12:02 west systemd[1]: Started docker.service.
Jun 28 17:12:02 west docker[20336]: time="2016-06-28T17:12:02.553034195+02:00" level=info msg="New containerd process, pid: 20342\n"
Jun 28 17:12:02 west docker[20336]: time="2016-06-28T17:12:02+02:00" level=warning msg="containerd: low RLIMIT_NOFILE changing to max" current=1024 max=4096
Jun 28 17:12:03 west docker[20336]: time="2016-06-28T17:12:03.831316092+02:00" level=info msg="devmapper: Creating filesystem xfs on device docker-253:4-393228-base"
Jun 28 17:12:04 west docker[20336]: time="2016-06-28T17:12:04.136340079+02:00" level=info msg="devmapper: Successfully created filesystem xfs on device docker-253:4-393228-base"
Jun 28 17:12:04 west docker[20336]: time="2016-06-28T17:12:04.390808091+02:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Jun 28 17:12:04 west docker[20336]: time="2016-06-28T17:12:04.393786524+02:00" level=info msg="Firewalld running: false"
Jun 28 17:12:04 west docker[20336]: time="2016-06-28T17:12:04.439902984+02:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Jun 28 17:12:04 west docker[20336]: time="2016-06-28T17:12:04.674135540+02:00" level=warning msg="Your kernel does not support cgroup memory limit"
Jun 28 17:12:04 west docker[20336]: time="2016-06-28T17:12:04.674163966+02:00" level=warning msg="Your kernel does not support cgroup cfs period"
Jun 28 17:12:04 west docker[20336]: time="2016-06-28T17:12:04.674171905+02:00" level=warning msg="Your kernel does not support cgroup cfs quotas"
Jun 28 17:12:04 west docker[20336]: time="2016-06-28T17:12:04.674308017+02:00" level=warning msg="mountpoint for pids not found"
Jun 28 17:12:04 west docker[20336]: time="2016-06-28T17:12:04.674500157+02:00" level=info msg="Loading containers: start."
Jun 28 17:12:04 west docker[20336]: time="2016-06-28T17:12:04.674529402+02:00" level=info msg="Loading containers: done."
Jun 28 17:12:04 west docker[20336]: time="2016-06-28T17:12:04.674545699+02:00" level=info msg="Daemon has completed initialization"
Jun 28 17:12:04 west docker[20336]: time="2016-06-28T17:12:04.674562898+02:00" level=info msg="Docker daemon" commit=b9f10c9 graphdriver=devicemapper version=1.11.2
Jun 28 17:12:04 west docker[20336]: time="2016-06-28T17:12:04.681375955+02:00" level=info msg="API listen on /var/run/docker.sock"
Jun 28 17:13:17 west docker[20336]: time="2016-06-28T17:13:17.292100750+02:00" level=error msg="Handler for POST /v1.23/containers/libres3/stop returned error: No such container: libres3"
Jun 28 17:13:17 west docker[20336]: time="2016-06-28T17:13:17.300782890+02:00" level=error msg="Handler for DELETE /v1.23/containers/libres3 returned error: No such container: libres3"
Jun 28 17:13:18 west docker[20336]: time="2016-06-28T17:13:18+02:00" level=error msg="containerd: notify OOM events" error="open memory.oom_control: no such file or directory"
Jun 28 17:22:21 west docker[20336]: time="2016-06-28T17:22:21.956898601+02:00" level=error msg="Handler for POST /v1.23/containers/create returned error: No such image: sxshare:latest"
Jun 28 17:22:23 west docker[20336]: time="2016-06-28T17:22:23.184662449+02:00" level=error msg="Attempting next endpoint for pull after error: unauthorized: authentication required"
Jun 28 17:22:23 west docker[20336]: time="2016-06-28T17:22:23.625345708+02:00" level=error msg="Not continuing with pull after error: Error: image library/sxshare not found"
Jun 28 17:23:07 west docker[20336]: time="2016-06-28T17:23:07.803611840+02:00" level=info msg="Layer sha256:77fb79546eaf4c136b0430033fcdd865d0b58152697be2959a2c32203a6f6daa cleaned up"
Jun 28 17:23:09 west docker[20336]: time="2016-06-28T17:23:09+02:00" level=error msg="containerd: notify OOM events" error="open memory.oom_control: no such file or directory"
Jun 28 17:24:56 west docker[20336]: time="2016-06-28T17:24:56+02:00" level=error msg="containerd: notify OOM events" error="open memory.oom_control: no such file or directory"
Jun 28 17:26:03 west docker[20336]: time="2016-06-28T17:26:03.828342050+02:00" level=info msg="Layer sha256:aa540c740343cfb8ff3f030068cd304b50a077c739c5706f42c2446d50681d81 cleaned up"
Jun 28 17:26:07 west docker[20336]: time="2016-06-28T17:26:07+02:00" level=error msg="containerd: notify OOM events" error="open memory.oom_control: no such file or directory"
Jun 28 17:26:16 west docker[20336]: time="2016-06-28T17:26:16.886233792+02:00" level=info msg="Layer sha256:cf84863ca10b13c1e0d8efffed2cb410ce0fd25933eaf3535a80202b7f19d981 cleaned up"
Jun 28 17:26:20 west docker[20336]: time="2016-06-28T17:26:20+02:00" level=error msg="containerd: notify OOM events" error="open memory.oom_control: no such file or directory"
Jun 28 17:26:35 west docker[20336]: time="2016-06-28T17:26:35.526803311+02:00" level=info msg="Layer sha256:afb63a2d743df709d4db96c854caf9739ed1d41be4d4876bc2b0e74f4b9350c2 cleaned up"
Jun 28 17:26:45 west docker[20336]: time="2016-06-28T17:26:45+02:00" level=error msg="containerd: notify OOM events" error="open memory.oom_control: no such file or directory"
Jun 28 17:28:15 west docker[20336]: time="2016-06-28T17:28:15.113619172+02:00" level=info msg="Layer sha256:f6f15cc9e1a1650fb6ef37e28276b83c450651a3ccf92d924705408e3a059fb2 cleaned up"
Jun 28 17:28:22 west docker[20336]: time="2016-06-28T17:28:22.438259881+02:00" level=info msg="Layer sha256:f6f15cc9e1a1650fb6ef37e28276b83c450651a3ccf92d924705408e3a059fb2 cleaned up"
Jun 28 17:29:53 west docker[20336]: time="2016-06-28T17:29:53+02:00" level=error msg="containerd: notify OOM events" error="open memory.oom_control: no such file or directory"
Sep 27 06:25:01 west docker[20336]: panic: sync: WaitGroup is reused before previous Wait has returned
Sep 27 06:25:01 west docker[20336]: goroutine 408 [running]:
Sep 27 06:25:01 west docker[20336]: sync.(*WaitGroup).Wait(0xc82296bb00)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/sync/waitgroup.go:128 +0x114
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/daemon.(*Daemon).StateChanged(0xc820327c80, 0xc82236cf80, 0x40, 0x1765290, 0xc, 0x0, 0xc82236d0c0, 0x40, 0x0, 0x0, ...)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/monitor.go:62 +0xd8b
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/libcontainerd.(*container).handleEvent.func2()
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/container_linux.go:177 +0xa5
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/libcontainerd.(*queue).append.func1(0xc820045c01, 0xc821f6a000, 0xc82254e0e0, 0xc821f562a0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/queue_linux.go:26 +0x47
Sep 27 06:25:01 west docker[20336]: created by github.com/docker/docker/libcontainerd.(*queue).append
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/queue_linux.go:28 +0x1da
Sep 27 06:25:01 west docker[20336]: goroutine 1 [chan receive, 130392 minutes]:
Sep 27 06:25:01 west docker[20336]: main.(*DaemonCli).CmdDaemon(0xc82040b940, 0xc82000a140, 0x4, 0x4, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/docker/daemon.go:337 +0x23e1
Sep 27 06:25:01 west docker[20336]: reflect.callMethod(0xc8203fba10, 0xc8210cdc78)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/reflect/value.go:628 +0x1fc
Sep 27 06:25:01 west docker[20336]: reflect.methodValueCall(0xc82000a140, 0x4, 0x4, 0x1, 0xc8203fba10, 0x0, 0x0, 0xc8203fba10, 0x0, 0x47cc24, ...)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/reflect/asm_amd64.s:29 +0x36
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/cli.(*Cli).Run(0xc8203fb7d0, 0xc82000a130, 0x5, 0x5, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/cli/cli.go:89 +0x383
Sep 27 06:25:01 west docker[20336]: main.main()
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/docker/docker.go:63 +0x43c
Sep 27 06:25:01 west docker[20336]: goroutine 17 [syscall, 130392 minutes, locked to thread]:
Sep 27 06:25:01 west docker[20336]: runtime.goexit()
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1
Sep 27 06:25:01 west docker[20336]: goroutine 35 [select, 130392 minutes]:
Sep 27 06:25:01 west docker[20336]: google.golang.org/grpc.(*Conn).transportMonitor(0xc8203be0c0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/vendor/src/google.golang.org/grpc/clientconn.go:490 +0x1c9
Sep 27 06:25:01 west docker[20336]: google.golang.org/grpc.NewConn.func1(0xc8203be0c0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/vendor/src/google.golang.org/grpc/clientconn.go:301 +0x1b5
Sep 27 06:25:01 west docker[20336]: created by google.golang.org/grpc.NewConn
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/vendor/src/google.golang.org/grpc/clientconn.go:302 +0x4fb
Sep 27 06:25:01 west docker[20336]: goroutine 18 [syscall, 130392 minutes]:
Sep 27 06:25:01 west docker[20336]: os/signal.loop()
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
Sep 27 06:25:01 west docker[20336]: created by os/signal.init.1
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/os/signal/signal_unix.go:28 +0x37
Sep 27 06:25:01 west docker[20336]: goroutine 34 [syscall, 130392 minutes]:
Sep 27 06:25:01 west docker[20336]: syscall.Syscall6(0x3d, 0x4f76, 0xc820020df4, 0x0, 0xc82034ea20, 0x0, 0x0, 0x2, 0x4247f4, 0xc82027c778)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
Sep 27 06:25:01 west docker[20336]: syscall.wait4(0x4f76, 0xc820020df4, 0x0, 0xc82034ea20, 0x90, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/syscall/zsyscall_linux_amd64.go:172 +0x72
Sep 27 06:25:01 west docker[20336]: syscall.Wait4(0x4f76, 0xc820020e3c, 0x0, 0xc82034ea20, 0x4696b0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/syscall/syscall_linux.go:256 +0x55
Sep 27 06:25:01 west docker[20336]: os.(*Process).wait(0xc8204115c0, 0x419593, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/os/exec_unix.go:22 +0x105
Sep 27 06:25:01 west docker[20336]: os.(*Process).Wait(0xc8204115c0, 0xdcb29e, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/os/doc.go:45 +0x2d
Sep 27 06:25:01 west docker[20336]: os/exec.(*Cmd).Wait(0xc8203fef00, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/os/exec/exec.go:380 +0x211
Sep 27 06:25:01 west docker[20336]: created by github.com/docker/docker/libcontainerd.(*remote).runContainerdDaemon
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/remote_linux.go:386 +0xf0a
Sep 27 06:25:01 west docker[20336]: goroutine 36 [semacquire, 130392 minutes]:
Sep 27 06:25:01 west docker[20336]: sync.runtime_Syncsemacquire(0xc8204249d0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/runtime/sema.go:237 +0x201
Sep 27 06:25:01 west docker[20336]: sync.(*Cond).Wait(0xc8204249c0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/sync/cond.go:62 +0x9b
Sep 27 06:25:01 west docker[20336]: google.golang.org/grpc.(*Conn).WaitForStateChange(0xc8203be0c0, 0x7f6d080c1200, 0xc82000efe0, 0x2, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/vendor/src/google.golang.org/grpc/clientconn.go:351 +0x19f
Sep 27 06:25:01 west docker[20336]: google.golang.org/grpc.(*unicastPicker).WaitForStateChange(0xc820411600, 0x7f6d080c1200, 0xc82000efe0, 0x2, 0x18c30c0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/vendor/src/google.golang.org/grpc/picker.go:96 +0x4f
Sep 27 06:25:01 west docker[20336]: google.golang.org/grpc.(*ClientConn).WaitForStateChange(0xc82033d280, 0x7f6d080c1200, 0xc82000efe0, 0x2, 0x1, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/vendor/src/google.golang.org/grpc/clientconn.go:228 +0x6b
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/libcontainerd.(*remote).handleConnectionChange(0xc820350580)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/remote_linux.go:116 +0xa5
Sep 27 06:25:01 west docker[20336]: created by github.com/docker/docker/libcontainerd.New
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/remote_linux.go:103 +0xa24
Sep 27 06:25:01 west docker[20336]: goroutine 38 [select, 130392 minutes]:
Sep 27 06:25:01 west docker[20336]: google.golang.org/grpc/transport.(*http2Client).controller(0xc8204000f0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/vendor/src/google.golang.org/grpc/transport/http2_client.go:812 +0x5d8
Sep 27 06:25:01 west docker[20336]: created by google.golang.org/grpc/transport.newHTTP2Client
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/vendor/src/google.golang.org/grpc/transport/http2_client.go:193 +0x1536
Sep 27 06:25:01 west docker[20336]: goroutine 39 [IO wait]:
Sep 27 06:25:01 west docker[20336]: net.runtime_pollWait(0x7f6d080c3260, 0x72, 0xc82000e100)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/runtime/netpoll.go:157 +0x60
Sep 27 06:25:01 west docker[20336]: net.(*pollDesc).Wait(0xc820409640, 0x72, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
Sep 27 06:25:01 west docker[20336]: net.(*pollDesc).WaitRead(0xc820409640, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
Sep 27 06:25:01 west docker[20336]: net.(*netFD).Read(0xc8204095e0, 0xc82034eb64, 0x9, 0x9, 0x0, 0x7f6d0c38d050, 0xc82000e100)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/net/fd_unix.go:232 +0x23a
Sep 27 06:25:01 west docker[20336]: net.(*conn).Read(0xc8203361b8, 0xc82034eb64, 0x9, 0x9, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/net/net.go:172 +0xe4
Sep 27 06:25:01 west docker[20336]: io.ReadAtLeast(0x7f6d080c3d50, 0xc8203361b8, 0xc82034eb64, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/io/io.go:298 +0xe6
Sep 27 06:25:01 west docker[20336]: io.ReadFull(0x7f6d080c3d50, 0xc8203361b8, 0xc82034eb64, 0x9, 0x9, 0x7f6d08101990, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/io/io.go:316 +0x62
Sep 27 06:25:01 west docker[20336]: golang.org/x/net/http2.readFrameHeader(0xc82034eb64, 0x9, 0x9, 0x7f6d080c3d50, 0xc8203361b8, 0x21000000, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/vendor/src/golang.org/x/net/http2/frame.go:228 +0xa5
Sep 27 06:25:01 west docker[20336]: golang.org/x/net/http2.(*Framer).ReadFrame(0xc82034eb40, 0x0, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/vendor/src/golang.org/x/net/http2/frame.go:373 +0xe6
Sep 27 06:25:01 west docker[20336]: google.golang.org/grpc/transport.(*framer).readFrame(0xc820426210, 0x0, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/vendor/src/google.golang.org/grpc/transport/http_util.go:450 +0x3d
Sep 27 06:25:01 west docker[20336]: google.golang.org/grpc/transport.(*http2Client).reader(0xc8204000f0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/vendor/src/google.golang.org/grpc/transport/http2_client.go:742 +0x115
Sep 27 06:25:01 west docker[20336]: created by google.golang.org/grpc/transport.newHTTP2Client
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/vendor/src/google.golang.org/grpc/transport/http2_client.go:199 +0x1595
Sep 27 06:25:01 west docker[20336]: goroutine 41 [chan receive, 130392 minutes]:
Sep 27 06:25:01 west docker[20336]: google.golang.org/grpc.NewClientStream.func1(0xc8203be240, 0xc82033d580)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/vendor/src/google.golang.org/grpc/stream.go:136 +0x7c
Sep 27 06:25:01 west docker[20336]: created by google.golang.org/grpc.NewClientStream
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/vendor/src/google.golang.org/grpc/stream.go:138 +0x869
Sep 27 06:25:01 west docker[20336]: goroutine 42 [select]:
Sep 27 06:25:01 west docker[20336]: google.golang.org/grpc/transport.(*recvBufferReader).Read(0xc820426330, 0xc82202a080, 0x5, 0x5, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/vendor/src/google.golang.org/grpc/transport/transport.go:141 +0x7e5
Sep 27 06:25:01 west docker[20336]: google.golang.org/grpc/transport.(*Stream).Read(0xc8203be240, 0xc82202a080, 0x5, 0x5, 0x19, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/vendor/src/google.golang.org/grpc/transport/transport.go:281 +0x6d
Sep 27 06:25:01 west docker[20336]: io.ReadAtLeast(0x7f6d080c3f40, 0xc8203be240, 0xc82202a080, 0x5, 0x5, 0x5, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/io/io.go:298 +0xe6
Sep 27 06:25:01 west docker[20336]: io.ReadFull(0x7f6d080c3f40, 0xc8203be240, 0xc82202a080, 0x5, 0x5, 0x44a211, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/io/io.go:316 +0x62
Sep 27 06:25:01 west docker[20336]: google.golang.org/grpc.(*parser).recvMsg(0xc820422a60, 0x200000003, 0x0, 0x0, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/vendor/src/google.golang.org/grpc/rpc_util.go:139 +0xc5
Sep 27 06:25:01 west docker[20336]: google.golang.org/grpc.recv(0xc820422a60, 0x7f6d080c3bc0, 0x2214988, 0x15ab460, 0xc82236d900, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/vendor/src/google.golang.org/grpc/rpc_util.go:195 +0x42
Sep 27 06:25:01 west docker[20336]: google.golang.org/grpc.(*clientStream).RecvMsg(0xc82033d580, 0x15ab460, 0xc82236d900, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/vendor/src/google.golang.org/grpc/stream.go:202 +0x89
Sep 27 06:25:01 west docker[20336]: github.com/docker/containerd/api/grpc/types.(*aPIEventsClient).Recv(0xc820422a70, 0xecf7beb9d, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/vendor/src/github.com/docker/containerd/api/grpc/types/api.pb.go:955 +0x7e
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/libcontainerd.(*remote).handleEventStream(0xc820350580, 0x7f6d080c4068, 0xc820422a70)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/remote_linux.go:258 +0x6d
Sep 27 06:25:01 west docker[20336]: created by github.com/docker/docker/libcontainerd.(*remote).startEventsMonitor
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/remote_linux.go:251 +0x184
Sep 27 06:25:01 west docker[20336]: goroutine 43 [select, 130392 minutes, locked to thread]:
Sep 27 06:25:01 west docker[20336]: runtime.gopark(0x1a74b48, 0xc820437f28, 0x1742e80, 0x6, 0x444818, 0x2)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/runtime/proc.go:185 +0x163
Sep 27 06:25:01 west docker[20336]: runtime.selectgoImpl(0xc820437f28, 0x0, 0x18)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/runtime/select.go:392 +0xa64
Sep 27 06:25:01 west docker[20336]: runtime.selectgo(0xc820437f28)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/runtime/select.go:212 +0x12
Sep 27 06:25:01 west docker[20336]: runtime.ensureSigM.func1()
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/runtime/signal1_unix.go:227 +0x353
Sep 27 06:25:01 west docker[20336]: runtime.goexit()
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1
Sep 27 06:25:01 west docker[20336]: goroutine 44 [chan receive, 130392 minutes]:
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/daemon.setupDumpStackTrap.func1(0xc820343bc0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/debugtrap_unix.go:17 +0x4d
Sep 27 06:25:01 west docker[20336]: created by github.com/docker/docker/daemon.setupDumpStackTrap
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/debugtrap_unix.go:20 +0x12a
Sep 27 06:25:01 west docker[20336]: goroutine 49 [select, 130376 minutes]:
Sep 27 06:25:01 west docker[20336]: github.com/docker/libnetwork.(*controller).watchLoop(0xc82009a840)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/vendor/src/github.com/docker/libnetwork/store.go:420 +0x140
Sep 27 06:25:01 west docker[20336]: created by github.com/docker/libnetwork.(*controller).startWatch
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/vendor/src/github.com/docker/libnetwork/store.go:437 +0x115
Sep 27 06:25:01 west docker[20336]: goroutine 106 [IO wait]:
Sep 27 06:25:01 west docker[20336]: net.runtime_pollWait(0x7f6d080c3320, 0x72, 0xc82000e100)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/runtime/netpoll.go:157 +0x60
Sep 27 06:25:01 west docker[20336]: net.(*pollDesc).Wait(0xc8204093a0, 0x72, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
Sep 27 06:25:01 west docker[20336]: net.(*pollDesc).WaitRead(0xc8204093a0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
Sep 27 06:25:01 west docker[20336]: net.(*netFD).accept(0xc820409340, 0x0, 0x7f6d0c391858, 0xc820d4a080)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/net/fd_unix.go:408 +0x27c
Sep 27 06:25:01 west docker[20336]: net.(*UnixListener).AcceptUnix(0xc8204110c0, 0xc820039dd8, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/net/unixsock_posix.go:304 +0x53
Sep 27 06:25:01 west docker[20336]: net.(*UnixListener).Accept(0xc8204110c0, 0x0, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/net/unixsock_posix.go:314 +0x41
Sep 27 06:25:01 west docker[20336]: net/http.(*Server).Serve(0xc8203435c0, 0x7f6d080c3988, 0xc8204110c0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/net/http/server.go:1887 +0xb3
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/api/server.(*HTTPServer).Serve(0xc8204112c0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:107 +0x47
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/api/server.(*Server).serveAPI.func1(0xc8209c9a40, 0xc8204112c0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:80 +0x13d
Sep 27 06:25:01 west docker[20336]: created by github.com/docker/docker/api/server.(*Server).serveAPI
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:84 +0x137
Sep 27 06:25:01 west docker[20336]: goroutine 104 [chan receive, 130392 minutes]:
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/pkg/signal.Trap.func1(0xc8209c99e0, 0xc8209ad110)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/signal/trap.go:29 +0x71
Sep 27 06:25:01 west docker[20336]: created by github.com/docker/docker/pkg/signal.Trap
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/signal/trap.go:55 +0x21a
Sep 27 06:25:01 west docker[20336]: goroutine 103 [chan receive, 130392 minutes]:
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/api/server.(*Server).serveAPI(0xc820343560, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:88 +0x19e
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/api/server.(*Server).Wait(0xc820343560, 0xc8209c9980)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:177 +0x2b
Sep 27 06:25:01 west docker[20336]: created by main.(*DaemonCli).CmdDaemon
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/docker/daemon.go:319 +0x22b4
Sep 27 06:25:01 west docker[20336]: goroutine 102 [chan receive, 130392 minutes]:
Sep 27 06:25:01 west docker[20336]: main.setupConfigReloadTrap.func1(0xc8209c9920, 0x1831a70, 0x17, 0xc82033cf80, 0xc8202e07e0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/docker/daemon_unix.go:60 +0x68
Sep 27 06:25:01 west docker[20336]: created by main.setupConfigReloadTrap
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/docker/daemon_unix.go:65 +0x162
Sep 27 06:25:01 west docker[20336]: goroutine 101 [chan receive, 4 minutes]:
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/daemon.(*Daemon).execCommandGC(0xc820327c80)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/exec.go:215 +0x8e
Sep 27 06:25:01 west docker[20336]: created by github.com/docker/docker/daemon.NewDaemon
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/daemon.go:851 +0x3243
Sep 27 06:25:01 west docker[20336]: goroutine 85 [IO wait, 130376 minutes]:
Sep 27 06:25:01 west docker[20336]: net.runtime_pollWait(0x7f6d080c31a0, 0x72, 0xc82000e100)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/runtime/netpoll.go:157 +0x60
Sep 27 06:25:01 west docker[20336]: net.(*pollDesc).Wait(0xc8203fc220, 0x72, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
Sep 27 06:25:01 west docker[20336]: net.(*pollDesc).WaitRead(0xc8203fc220, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
Sep 27 06:25:01 west docker[20336]: net.(*netFD).accept(0xc8203fc1c0, 0x0, 0x7f6d0c391858, 0xc820f0e4a0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/net/fd_unix.go:408 +0x27c
Sep 27 06:25:01 west docker[20336]: net.(*UnixListener).AcceptUnix(0xc8203f3a20, 0xc820479ed0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/net/unixsock_posix.go:304 +0x53
Sep 27 06:25:01 west docker[20336]: net.(*UnixListener).Accept(0xc8203f3a20, 0x0, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/net/unixsock_posix.go:314 +0x41
Sep 27 06:25:01 west docker[20336]: github.com/docker/libnetwork.(*controller).acceptClientConnections(0xc82009a840, 0xc8203fc0e0, 0x63, 0x7f6d080c3988, 0xc8203f3a20)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/vendor/src/github.com/docker/libnetwork/sandbox_externalkey_unix.go:128 +0x45
Sep 27 06:25:01 west docker[20336]: created by github.com/docker/libnetwork.(*controller).startExternalKeyListener
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/vendor/src/github.com/docker/libnetwork/sandbox_externalkey_unix.go:122 +0x28a
Sep 27 06:25:01 west docker[20336]: goroutine 100 [chan receive]:
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/daemon.(*statsCollector).run(0xc8202854c0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/stats_collector_unix.go:106 +0xcd
Sep 27 06:25:01 west docker[20336]: created by github.com/docker/docker/daemon.(*Daemon).newStatsCollector
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/stats_collector_unix.go:44 +0x1f0
Sep 27 06:25:01 west docker[20336]: goroutine 114 [select, 130392 minutes]:
Sep 27 06:25:01 west docker[20336]: google.golang.org/grpc.(*Conn).WaitForStateChange.func1(0x7f6d080c1200, 0xc82000efe0, 0xc8203be0c0, 0xc8209c6000, 0xc820342000)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/vendor/src/google.golang.org/grpc/clientconn.go:340 +0x1b0
Sep 27 06:25:01 west docker[20336]: created by google.golang.org/grpc.(*Conn).WaitForStateChange
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/vendor/src/google.golang.org/grpc/clientconn.go:348 +0x14e
Sep 27 06:25:01 west docker[20336]: goroutine 640 [semacquire, 752 minutes]:
Sep 27 06:25:01 west docker[20336]: sync.runtime_Syncsemacquire(0xc820d62290)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/runtime/sema.go:237 +0x201
Sep 27 06:25:01 west docker[20336]: sync.(*Cond).Wait(0xc820d62280)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/sync/cond.go:62 +0x9b
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/pkg/ioutils.(*BytesPipe).Read(0xc822872140, 0xc82293f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/ioutils/bytespipe.go:127 +0x121
Sep 27 06:25:01 west docker[20336]: bufio.(*Reader).fill(0xc820475ed0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/bufio/bufio.go:97 +0x1e9
Sep 27 06:25:01 west docker[20336]: bufio.(*Reader).ReadSlice(0xc820475ed0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/bufio/bufio.go:328 +0x21a
Sep 27 06:25:01 west docker[20336]: bufio.(*Reader).ReadBytes(0xc820475ed0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/bufio/bufio.go:406 +0xa9
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/daemon/logger.(*Copier).copySrc(0xc820d62440, 0x1743650, 0x6, 0x7f6d0c3b6fd0, 0xc822872140)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/logger/copier.go:53 +0x14a
Sep 27 06:25:01 west docker[20336]: created by github.com/docker/docker/daemon/logger.(*Copier).Run
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/logger/copier.go:40 +0x127
Sep 27 06:25:01 west docker[20336]: goroutine 746 [semacquire]:
Sep 27 06:25:01 west docker[20336]: sync.runtime_Semacquire(0xc822004a8c)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/runtime/sema.go:43 +0x26
Sep 27 06:25:01 west docker[20336]: sync.(*WaitGroup).Wait(0xc822004a80)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/sync/waitgroup.go:126 +0xb4
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/container.AttachStreams.func3.1(0xc822004a80, 0xc821ef8000)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/container/container.go:443 +0x21
Sep 27 06:25:01 west docker[20336]: created by github.com/docker/docker/container.AttachStreams.func3
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/container/container.go:445 +0xed
Sep 27 06:25:01 west docker[20336]: goroutine 260 [semacquire]:
Sep 27 06:25:01 west docker[20336]: sync.runtime_Syncsemacquire(0xc820fdd0d0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/runtime/sema.go:237 +0x201
Sep 27 06:25:01 west docker[20336]: sync.(*Cond).Wait(0xc820fdd0c0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/sync/cond.go:62 +0x9b
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/pkg/ioutils.(*BytesPipe).Read(0xc820f92550, 0xc820da3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/ioutils/bytespipe.go:127 +0x121
Sep 27 06:25:01 west docker[20336]: bufio.(*Reader).fill(0xc820036ed0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/bufio/bufio.go:97 +0x1e9
Sep 27 06:25:01 west docker[20336]: bufio.(*Reader).ReadSlice(0xc820036ed0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/bufio/bufio.go:328 +0x21a
Sep 27 06:25:01 west docker[20336]: bufio.(*Reader).ReadBytes(0xc820036ed0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/bufio/bufio.go:406 +0xa9
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/daemon/logger.(*Copier).copySrc(0xc820fdd180, 0x1743650, 0x6, 0x7f6d0c3b6fd0, 0xc820f92550)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/logger/copier.go:53 +0x14a
Sep 27 06:25:01 west docker[20336]: created by github.com/docker/docker/daemon/logger.(*Copier).Run
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/logger/copier.go:40 +0x127
Sep 27 06:25:01 west docker[20336]: goroutine 659 [semacquire, 130376 minutes]:
Sep 27 06:25:01 west docker[20336]: sync.runtime_Syncsemacquire(0xc821a94700)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/runtime/sema.go:237 +0x201
Sep 27 06:25:01 west docker[20336]: sync.(*Cond).Wait(0xc821a946f0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/sync/cond.go:62 +0x9b
Sep 27 06:25:01 west docker[20336]: io.(*pipe).read(0xc821a946c0, 0xc8210fc000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/io/pipe.go:52 +0x2d2
Sep 27 06:25:01 west docker[20336]: io.(*PipeReader).Read(0xc821d06ea8, 0xc8210fc000, 0x8000, 0x8000, 0x3b, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/io/pipe.go:134 +0x50
Sep 27 06:25:01 west docker[20336]: io.copyBuffer(0x7f6d081281e8, 0xc820f5a3a0, 0x7f6d081238a0, 0xc821d06ea8, 0xc8210fc000, 0x8000, 0x8000, 0xe3c, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/io/io.go:381 +0x247
Sep 27 06:25:01 west docker[20336]: io.Copy(0x7f6d081281e8, 0xc820f5a3a0, 0x7f6d081238a0, 0xc821d06ea8, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/io/io.go:351 +0x64
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/daemon.(*Daemon).AttachStreams.func2.1(0x7f6d081281e8, 0xc820f5a3a0, 0x7f6d081238a0, 0xc821d06ea8, 0xc82027d09e, 0x40, 0xc8219a9bc0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/monitor.go:129 +0x79
Sep 27 06:25:01 west docker[20336]: created by github.com/docker/docker/daemon.(*Daemon).AttachStreams.func2
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/monitor.go:133 +0xaf
Sep 27 06:25:01 west docker[20336]: goroutine 259 [syscall, 4321 minutes]:
Sep 27 06:25:01 west docker[20336]: syscall.Syscall(0x0, 0x12, 0xc820dac000, 0x8000, 0xa, 0x1a, 0x6eef60)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
Sep 27 06:25:01 west docker[20336]: syscall.read(0x12, 0xc820dac000, 0x8000, 0x8000, 0x4416c2, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/syscall/zsyscall_linux_amd64.go:783 +0x5f
Sep 27 06:25:01 west docker[20336]: syscall.Read(0x12, 0xc820dac000, 0x8000, 0x8000, 0x4695d0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/syscall/syscall_unix.go:160 +0x4d
Sep 27 06:25:01 west docker[20336]: os.(*File).read(0xc820028030, 0xc820dac000, 0x8000, 0x8000, 0xc820dac000, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/os/file_unix.go:211 +0x53
Sep 27 06:25:01 west docker[20336]: os.(*File).Read(0xc820028030, 0xc820dac000, 0x8000, 0x8000, 0x2c, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/os/file.go:95 +0x8a
Sep 27 06:25:01 west docker[20336]: io.copyBuffer(0x7f6d0018e000, 0xc820028028, 0x7f6d0c391270, 0xc820028030, 0xc820dac000, 0x8000, 0x8000, 0x2c, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/io/io.go:381 +0x247
Sep 27 06:25:01 west docker[20336]: io.Copy(0x7f6d0018e000, 0xc820028028, 0x7f6d0c391270, 0xc820028030, 0xc820028030, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/io/io.go:351 +0x64
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/libcontainerd.openReaderFromFifo.func1(0xc821108000, 0xc820a90070, 0x6a, 0xc820028020, 0xc820028028)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/process_linux.go:89 +0x11d
Sep 27 06:25:01 west docker[20336]: created by github.com/docker/docker/libcontainerd.openReaderFromFifo
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/process_linux.go:94 +0x1e7
Sep 27 06:25:01 west docker[20336]: goroutine 261 [semacquire, 4321 minutes]:
Sep 27 06:25:01 west docker[20336]: sync.runtime_Syncsemacquire(0xc820fdd150)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/runtime/sema.go:237 +0x201
Sep 27 06:25:01 west docker[20336]: sync.(*Cond).Wait(0xc820fdd140)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/sync/cond.go:62 +0x9b
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/pkg/ioutils.(*BytesPipe).Read(0xc820f925a0, 0xc820fd1000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/ioutils/bytespipe.go:127 +0x121
Sep 27 06:25:01 west docker[20336]: bufio.(*Reader).fill(0xc820478ed0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/bufio/bufio.go:97 +0x1e9
Sep 27 06:25:01 west docker[20336]: bufio.(*Reader).ReadSlice(0xc820478ed0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/bufio/bufio.go:328 +0x21a
Sep 27 06:25:01 west docker[20336]: bufio.(*Reader).ReadBytes(0xc820478ed0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/bufio/bufio.go:406 +0xa9
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/daemon/logger.(*Copier).copySrc(0xc820fdd180, 0x1743638, 0x6, 0x7f6d0c3b6fd0, 0xc820f925a0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/logger/copier.go:53 +0x14a
Sep 27 06:25:01 west docker[20336]: created by github.com/docker/docker/daemon/logger.(*Copier).Run
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/logger/copier.go:40 +0x127
Sep 27 06:25:01 west docker[20336]: goroutine 651 [syscall, 130376 minutes]:
Sep 27 06:25:01 west docker[20336]: syscall.Syscall(0x0, 0x15, 0xc821f14000, 0x8000, 0xa, 0x1a, 0x6eef60)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
Sep 27 06:25:01 west docker[20336]: syscall.read(0x15, 0xc821f14000, 0x8000, 0x8000, 0x4416c2, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/syscall/zsyscall_linux_amd64.go:783 +0x5f
Sep 27 06:25:01 west docker[20336]: syscall.Read(0x15, 0xc821f14000, 0x8000, 0x8000, 0x4695d0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/syscall/syscall_unix.go:160 +0x4d
Sep 27 06:25:01 west docker[20336]: os.(*File).read(0xc821d06eb8, 0xc821f14000, 0x8000, 0x8000, 0xc821f14000, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/os/file_unix.go:211 +0x53
Sep 27 06:25:01 west docker[20336]: os.(*File).Read(0xc821d06eb8, 0xc821f14000, 0x8000, 0x8000, 0x3b, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/os/file.go:95 +0x8a
Sep 27 06:25:01 west docker[20336]: io.copyBuffer(0x7f6d0018e000, 0xc821d06eb0, 0x7f6d0c391270, 0xc821d06eb8, 0xc821f14000, 0x8000, 0x8000, 0xe3c, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/io/io.go:381 +0x247
Sep 27 06:25:01 west docker[20336]: io.Copy(0x7f6d0018e000, 0xc821d06eb0, 0x7f6d0c391270, 0xc821d06eb8, 0xc821d06eb8, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/io/io.go:351 +0x64
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/libcontainerd.openReaderFromFifo.func1(0xc821412f00, 0xc8230aa5b0, 0x6a, 0xc821d06ea8, 0xc821d06eb0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/process_linux.go:89 +0x11d
Sep 27 06:25:01 west docker[20336]: created by github.com/docker/docker/libcontainerd.openReaderFromFifo
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/process_linux.go:94 +0x1e7
Sep 27 06:25:01 west docker[20336]: goroutine 638 [syscall, 752 minutes]:
Sep 27 06:25:01 west docker[20336]: syscall.Syscall(0x0, 0x13, 0xc82165c000, 0x8000, 0xa, 0x1a, 0x6eef60)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
Sep 27 06:25:01 west docker[20336]: syscall.read(0x13, 0xc82165c000, 0x8000, 0x8000, 0x4416c2, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/syscall/zsyscall_linux_amd64.go:783 +0x5f
Sep 27 06:25:01 west docker[20336]: syscall.Read(0x13, 0xc82165c000, 0x8000, 0x8000, 0x4695d0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/syscall/syscall_unix.go:160 +0x4d
Sep 27 06:25:01 west docker[20336]: os.(*File).read(0xc820a609d0, 0xc82165c000, 0x8000, 0x8000, 0xc82165c000, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/os/file_unix.go:211 +0x53
Sep 27 06:25:01 west docker[20336]: os.(*File).Read(0xc820a609d0, 0xc82165c000, 0x8000, 0x8000, 0x87, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/os/file.go:95 +0x8a
Sep 27 06:25:01 west docker[20336]: io.copyBuffer(0x7f6d0018e000, 0xc820a609c8, 0x7f6d0c391270, 0xc820a609d0, 0xc82165c000, 0x8000, 0x8000, 0x5cb57, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/io/io.go:381 +0x247
Sep 27 06:25:01 west docker[20336]: io.Copy(0x7f6d0018e000, 0xc820a609c8, 0x7f6d0c391270, 0xc820a609d0, 0xc820a609d0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/io/io.go:351 +0x64
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/libcontainerd.openReaderFromFifo.func1(0xc82011a1e0, 0xc822532b60, 0x6a, 0xc820a609a0, 0xc820a609c8)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/process_linux.go:89 +0x11d
Sep 27 06:25:01 west docker[20336]: created by github.com/docker/docker/libcontainerd.openReaderFromFifo
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/process_linux.go:94 +0x1e7
Sep 27 06:25:01 west docker[20336]: goroutine 294 [semacquire, 4321 minutes]:
Sep 27 06:25:01 west docker[20336]: sync.runtime_Syncsemacquire(0xc8203be340)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/runtime/sema.go:237 +0x201
Sep 27 06:25:01 west docker[20336]: sync.(*Cond).Wait(0xc8203be330)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/sync/cond.go:62 +0x9b
Sep 27 06:25:01 west docker[20336]: io.(*pipe).read(0xc8203be300, 0xc821150000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/io/pipe.go:52 +0x2d2
Sep 27 06:25:01 west docker[20336]: io.(*PipeReader).Read(0xc820028020, 0xc821150000, 0x8000, 0x8000, 0x2c, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/io/pipe.go:134 +0x50
Sep 27 06:25:01 west docker[20336]: io.copyBuffer(0x7f6d081281e8, 0xc820f3c900, 0x7f6d081238a0, 0xc820028020, 0xc821150000, 0x8000, 0x8000, 0x2c, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/io/io.go:381 +0x247
Sep 27 06:25:01 west docker[20336]: io.Copy(0x7f6d081281e8, 0xc820f3c900, 0x7f6d081238a0, 0xc820028020, 0x2a64ebaf6b2c4012, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/io/io.go:351 +0x64
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/daemon.(*Daemon).AttachStreams.func2.1(0x7f6d081281e8, 0xc820f3c900, 0x7f6d081238a0, 0xc820028020, 0xc82119a79e, 0x40, 0xc82145ffc0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/monitor.go:129 +0x79
Sep 27 06:25:01 west docker[20336]: created by github.com/docker/docker/daemon.(*Daemon).AttachStreams.func2
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/monitor.go:133 +0xaf
Sep 27 06:25:01 west docker[20336]: goroutine 311 [select, 2 minutes]:
Sep 27 06:25:01 west docker[20336]: github.com/docker/libnetwork/osl.removeUnusedPaths()
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/vendor/src/github.com/docker/libnetwork/osl/namespace_linux.go:74 +0x490
Sep 27 06:25:01 west docker[20336]: created by github.com/docker/libnetwork/osl.createBasePath
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/vendor/src/github.com/docker/libnetwork/osl/namespace_linux.go:59 +0xbe
Sep 27 06:25:01 west docker[20336]: goroutine 309 [syscall]:
Sep 27 06:25:01 west docker[20336]: syscall.Syscall(0x0, 0x11, 0xc8215ae000, 0x8000, 0xa, 0x1a, 0x6eef60)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
Sep 27 06:25:01 west docker[20336]: syscall.read(0x11, 0xc8215ae000, 0x8000, 0x8000, 0x4416c2, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/syscall/zsyscall_linux_amd64.go:783 +0x5f
Sep 27 06:25:01 west docker[20336]: syscall.Read(0x11, 0xc8215ae000, 0x8000, 0x8000, 0x4695d0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/syscall/syscall_unix.go:160 +0x4d
Sep 27 06:25:01 west docker[20336]: os.(*File).read(0xc820a60ba8, 0xc8215ae000, 0x8000, 0x8000, 0xc8215ae000, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/os/file_unix.go:211 +0x53
Sep 27 06:25:01 west docker[20336]: os.(*File).Read(0xc820a60ba8, 0xc8215ae000, 0x8000, 0x8000, 0x82, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/os/file.go:95 +0x8a
Sep 27 06:25:01 west docker[20336]: io.copyBuffer(0x7f6d0018e000, 0xc820a60ba0, 0x7f6d0c391270, 0xc820a60ba8, 0xc8215ae000, 0x8000, 0x8000, 0xa0d9718, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/io/io.go:381 +0x247
Sep 27 06:25:01 west docker[20336]: io.Copy(0x7f6d0018e000, 0xc820a60ba0, 0x7f6d0c391270, 0xc820a60ba8, 0xc820a60ba8, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/io/io.go:351 +0x64
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/libcontainerd.openReaderFromFifo.func1(0xc82119ac00, 0xc820a9a460, 0x6a, 0xc820a60b98, 0xc820a60ba0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/process_linux.go:89 +0x11d
Sep 27 06:25:01 west docker[20336]: created by github.com/docker/docker/libcontainerd.openReaderFromFifo
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/process_linux.go:94 +0x1e7
Sep 27 06:25:01 west docker[20336]: goroutine 293 [semacquire]:
Sep 27 06:25:01 west docker[20336]: sync.runtime_Syncsemacquire(0xc8201dc4c0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/runtime/sema.go:237 +0x201
Sep 27 06:25:01 west docker[20336]: sync.(*Cond).Wait(0xc8201dc4b0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/sync/cond.go:62 +0x9b
Sep 27 06:25:01 west docker[20336]: io.(*pipe).read(0xc8201dc480, 0xc820cde000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/io/pipe.go:52 +0x2d2
Sep 27 06:25:01 west docker[20336]: io.(*PipeReader).Read(0xc820a60b98, 0xc820cde000, 0x8000, 0x8000, 0x82, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/io/pipe.go:134 +0x50
Sep 27 06:25:01 west docker[20336]: io.copyBuffer(0x7f6d081281e8, 0xc820f3c940, 0x7f6d081238a0, 0xc820a60b98, 0xc820cde000, 0x8000, 0x8000, 0xa0d9718, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/io/io.go:381 +0x247
Sep 27 06:25:01 west docker[20336]: io.Copy(0x7f6d081281e8, 0xc820f3c940, 0x7f6d081238a0, 0xc820a60b98, 0xc820a60240, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/io/io.go:351 +0x64
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/daemon.(*Daemon).AttachStreams.func2.1(0x7f6d081281e8, 0xc820f3c940, 0x7f6d081238a0, 0xc820a60b98, 0xc82119a79e, 0x40, 0xc82145ffc0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/monitor.go:129 +0x79
Sep 27 06:25:01 west docker[20336]: created by github.com/docker/docker/daemon.(*Daemon).AttachStreams.func2
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/monitor.go:133 +0xaf
Sep 27 06:25:01 west docker[20336]: goroutine 759 [runnable]:
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/daemon.(*Daemon).AttachStreams.func2.1(0x7f6d081281e8, 0xc82241e4a0, 0x7f6d081238a0, 0xc821d06008, 0xc821288071, 0x40, 0xc82296bb00)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/monitor.go:128
Sep 27 06:25:01 west docker[20336]: created by github.com/docker/docker/daemon.(*Daemon).AttachStreams.func2
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/monitor.go:133 +0xaf
Sep 27 06:25:01 west docker[20336]: goroutine 658 [semacquire, 752 minutes]:
Sep 27 06:25:01 west docker[20336]: sync.runtime_Syncsemacquire(0xc820d3f840)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/runtime/sema.go:237 +0x201
Sep 27 06:25:01 west docker[20336]: sync.(*Cond).Wait(0xc820d3f830)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/sync/cond.go:62 +0x9b
Sep 27 06:25:01 west docker[20336]: io.(*pipe).read(0xc820d3f800, 0xc821f36000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/io/pipe.go:52 +0x2d2
Sep 27 06:25:01 west docker[20336]: io.(*PipeReader).Read(0xc820a609a0, 0xc821f36000, 0x8000, 0x8000, 0x87, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/io/pipe.go:134 +0x50
Sep 27 06:25:01 west docker[20336]: io.copyBuffer(0x7f6d081281e8, 0xc820f5a3e0, 0x7f6d081238a0, 0xc820a609a0, 0xc821f36000, 0x8000, 0x8000, 0x5cb57, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/io/io.go:381 +0x247
Sep 27 06:25:01 west docker[20336]: io.Copy(0x7f6d081281e8, 0xc820f5a3e0, 0x7f6d081238a0, 0xc820a609a0, 0xc822872230, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/io/io.go:351 +0x64
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/daemon.(*Daemon).AttachStreams.func2.1(0x7f6d081281e8, 0xc820f5a3e0, 0x7f6d081238a0, 0xc820a609a0, 0xc82027d09e, 0x40, 0xc8219a9bc0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/monitor.go:129 +0x79
Sep 27 06:25:01 west docker[20336]: created by github.com/docker/docker/daemon.(*Daemon).AttachStreams.func2
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/monitor.go:133 +0xaf
Sep 27 06:25:01 west docker[20336]: goroutine 641 [semacquire, 130376 minutes]:
Sep 27 06:25:01 west docker[20336]: sync.runtime_Syncsemacquire(0xc820d62390)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/runtime/sema.go:237 +0x201
Sep 27 06:25:01 west docker[20336]: sync.(*Cond).Wait(0xc820d62380)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/sync/cond.go:62 +0x9b
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/pkg/ioutils.(*BytesPipe).Read(0xc822872230, 0xc822d5f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/ioutils/bytespipe.go:127 +0x121
Sep 27 06:25:01 west docker[20336]: bufio.(*Reader).fill(0xc82159ded0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/bufio/bufio.go:97 +0x1e9
Sep 27 06:25:01 west docker[20336]: bufio.(*Reader).ReadSlice(0xc82159ded0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/bufio/bufio.go:328 +0x21a
Sep 27 06:25:01 west docker[20336]: bufio.(*Reader).ReadBytes(0xc82159ded0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/bufio/bufio.go:406 +0xa9
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/daemon/logger.(*Copier).copySrc(0xc820d62440, 0x1743638, 0x6, 0x7f6d0c3b6fd0, 0xc822872230)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/logger/copier.go:53 +0x14a
Sep 27 06:25:01 west docker[20336]: created by github.com/docker/docker/daemon/logger.(*Copier).Run
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/logger/copier.go:40 +0x127
Sep 27 06:25:01 west docker[20336]: goroutine 705 [runnable]:
Sep 27 06:25:01 west docker[20336]: sync.(*Mutex).Unlock(0xc8209cc2f0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/sync/mutex.go:99
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/pkg/locker.(*Locker).Lock(0xc8209cc2f0, 0xc82145ff80, 0x40)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/locker/locker.go:87 +0x175
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/libcontainerd.(*client).lock(0xc8209c8a20, 0xc82145ff80, 0x40)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/client.go:19 +0x39
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/libcontainerd.(*client).AddProcess(0xc8209c8a20, 0xc82145ff80, 0x40, 0xc821288071, 0x40, 0x0, 0x0, 0xc8222c25a0, 0x3, 0x3, ...)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/client_linux.go:102 +0xb53
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/daemon.(*Daemon).ContainerExecStart(0xc820327c80, 0xc821288071, 0x40, 0x7f6ce85c0788, 0xc820a60010, 0x7f6d0006c1e8, 0xc820d4a3e0, 0x7f6d0006c1e8, 0xc820d4a3c0, 0x0, ...)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/exec.go:201 +0x111e
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/api/server/router/container.(*containerRouter).postContainerExecStart(0xc8209d4d20, 0x7f6d080c3e68, 0xc8222c2a80, 0x7f6d0c3a9c10, 0xc8200e60b0, 0xc820eb2000, 0xc8222c2090, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/container/exec.go:109 +0x8fe
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.postContainerExecStart)-fm(0x7f6d080c3e68, 0xc8222c2a80, 0x7f6d0c3a9c10, 0xc8200e60b0, 0xc820eb2000, 0xc8222c2090, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/container/container.go:54 +0x74
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/api/server/middleware.NewVersionMiddleware.func1.1(0x7f6d080c3e68, 0xc8222c2a80, 0x7f6d0c3a9c10, 0xc8200e60b0, 0xc820eb2000, 0xc8222c2090, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware/version.go:42 +0xa43
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/api/server/middleware.NewUserAgentMiddleware.func1.1(0x7f6d080c3e68, 0xc8222c21e0, 0x7f6d0c3a9c10, 0xc8200e60b0, 0xc820eb2000, 0xc8222c2090, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware/user_agent.go:34 +0x6b8
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7f6d0c3a9c10, 0xc8200e60b0, 0xc820eb2000)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:132 +0x138
Sep 27 06:25:01 west docker[20336]: net/http.HandlerFunc.ServeHTTP(0xc82000dd20, 0x7f6d0c3a9c10, 0xc8200e60b0, 0xc820eb2000)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/net/http/server.go:1422 +0x3a
Sep 27 06:25:01 west docker[20336]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc820011770, 0x7f6d0c3a9c10, 0xc8200e60b0, 0xc820eb2000)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc82097e310, 0x7f6d0c3a9c10, 0xc8200e60b0, 0xc820eb2000)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
Sep 27 06:25:01 west docker[20336]: net/http.serverHandler.ServeHTTP(0xc8203435c0, 0x7f6d0c3a9c10, 0xc8200e60b0, 0xc820eb2000)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/net/http/server.go:1862 +0x19e
Sep 27 06:25:01 west docker[20336]: net/http.(*conn).serve(0xc8200e6000)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/net/http/server.go:1361 +0xbee
Sep 27 06:25:01 west docker[20336]: created by net/http.(*Server).Serve
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/net/http/server.go:1910 +0x3f6
Sep 27 06:25:01 west docker[20336]: goroutine 757 [select]:
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/container.AttachStreams.func3(0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/container/container.go:446 +0x2f0
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/pkg/promise.Go.func1(0xc8212881e0, 0xc821288180)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/promise/promise.go:8 +0x1d
Sep 27 06:25:01 west docker[20336]: created by github.com/docker/docker/pkg/promise.Go
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/promise/promise.go:9 +0x5d
Sep 27 06:25:01 west docker[20336]: goroutine 679 [IO wait]:
Sep 27 06:25:01 west docker[20336]: net.runtime_pollWait(0x7f6d080c2f60, 0x72, 0xc82000e100)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/runtime/netpoll.go:157 +0x60
Sep 27 06:25:01 west docker[20336]: net.(*pollDesc).Wait(0xc821f76060, 0x72, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
Sep 27 06:25:01 west docker[20336]: net.(*pollDesc).WaitRead(0xc821f76060, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
Sep 27 06:25:01 west docker[20336]: net.(*netFD).Read(0xc821f76000, 0xc82293e000, 0x1000, 0x1000, 0x0, 0x7f6d0c38d050, 0xc82000e100)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/net/fd_unix.go:232 +0x23a
Sep 27 06:25:01 west docker[20336]: net.(*conn).Read(0xc820336008, 0xc82293e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/net/net.go:172 +0xe4
Sep 27 06:25:01 west docker[20336]: net/http.(*liveSwitchReader).Read(0xc82009a0f8, 0xc82293e000, 0x1000, 0x1000, 0xc822d5e000, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/net/http/server.go:219 +0xa4
Sep 27 06:25:01 west docker[20336]: io.(*LimitedReader).Read(0xc82241e0e0, 0xc82293e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/io/io.go:427 +0xbd
Sep 27 06:25:01 west docker[20336]: bufio.(*Reader).fill(0xc8225e4000)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/bufio/bufio.go:97 +0x1e9
Sep 27 06:25:01 west docker[20336]: bufio.(*Reader).Peek(0xc8225e4000, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/bufio/bufio.go:132 +0xcc
Sep 27 06:25:01 west docker[20336]: net/http.(*conn).readRequest(0xc82009a0b0, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/net/http/server.go:629 +0x2bb
Sep 27 06:25:01 west docker[20336]: net/http.(*conn).serve(0xc82009a0b0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/net/http/server.go:1319 +0x727
Sep 27 06:25:01 west docker[20336]: created by net/http.(*Server).Serve
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/net/http/server.go:1910 +0x3f6
Sep 27 06:25:01 west docker[20336]: goroutine 756 [semacquire]:
Sep 27 06:25:01 west docker[20336]: sync.runtime_Syncsemacquire(0xc8223541d0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/runtime/sema.go:237 +0x201
Sep 27 06:25:01 west docker[20336]: sync.(*Cond).Wait(0xc8223541c0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/sync/cond.go:62 +0x9b
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/pkg/ioutils.(*BytesPipe).Read(0xc8215280a0, 0xc8227ee000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/ioutils/bytespipe.go:127 +0x121
Sep 27 06:25:01 west docker[20336]: io.copyBuffer(0x7f6d0006c1e8, 0xc820d4a3c0, 0x7f6d0c3b6fd0, 0xc8215280a0, 0xc8227ee000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/io/io.go:381 +0x247
Sep 27 06:25:01 west docker[20336]: io.Copy(0x7f6d0006c1e8, 0xc820d4a3c0, 0x7f6d0c3b6fd0, 0xc8215280a0, 0xc8215280a0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/io/io.go:351 +0x64
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/container.AttachStreams.func2(0x1743638, 0x6, 0x7f6d0006c1e8, 0xc820d4a3c0, 0x7f6d0c3b6fa0, 0xc8215280a0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/container/container.go:420 +0x1db
Sep 27 06:25:01 west systemd[1]: docker.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 27 06:25:01 west docker[20336]: created by github.com/docker/docker/container.AttachStreams
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/container/container.go:438 +0x3e0
Sep 27 06:25:01 west docker[20336]: goroutine 755 [semacquire]:
Sep 27 06:25:01 west docker[20336]: sync.runtime_Syncsemacquire(0xc8214c7d90)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/runtime/sema.go:237 +0x201
Sep 27 06:25:01 west docker[20336]: sync.(*Cond).Wait(0xc8214c7d80)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/sync/cond.go:62 +0x9b
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/pkg/ioutils.(*BytesPipe).Read(0xc821528050, 0xc821fa4000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/ioutils/bytespipe.go:127 +0x121
Sep 27 06:25:01 west docker[20336]: io.copyBuffer(0x7f6d0006c1e8, 0xc820d4a3e0, 0x7f6d0c3b6fd0, 0xc821528050, 0xc821fa4000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/io/io.go:381 +0x247
Sep 27 06:25:01 west docker[20336]: io.Copy(0x7f6d0006c1e8, 0xc820d4a3e0, 0x7f6d0c3b6fd0, 0xc821528050, 0xc821528050, 0x0, 0x0)
Sep 27 06:25:01 west docker[20336]: /usr/local/go/src/io/io.go:351 +0x64
Sep 27 06:25:01 west docker[20336]: github.com/docker/docker/container.AttachStreams.func2(0x1743650, 0x6, 0x7f6d0006c1e8, 0xc820d4a3e0, 0x7f6d0c3b6fa0, 0xc821528050)
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/container/container.go:420 +0x1db
Sep 27 06:25:01 west docker[20336]: created by github.com/docker/docker/container.AttachStreams
Sep 27 06:25:01 west docker[20336]: /usr/src/docker/.gopath/src/github.com/docker/docker/container/container.go:437 +0x37e
Sep 27 06:25:02 west docker[20336]: time="2016-09-27T06:25:02+02:00" level=info msg="stopping containerd after receiving terminated"
Sep 27 06:25:02 west docker[20336]: time="2016-09-27T06:25:02+02:00" level=fatal msg="containerd: serve grpc" error="accept unix /var/run/docker/libcontainerd/docker-containerd.sock: use of closed network connection"
Sep 27 06:26:32 west systemd[1]: docker.service stop-sigterm timed out. Killing.
Sep 27 06:26:32 west systemd[1]: Unit docker.service entered failed state.
```

**Describe the results you expected:**

No crash.
I had 3 other servers running similar containers with docker versions 1.9.1 and 1.10.3, and they didn't crash.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker info`:**

Note: I upgraded docker to 1.12.1 already before filing this bug, so the info is from the new docker, not from the one that crashed, but the config is the same:
```
Containers: 5
 Running: 1
 Paused: 0
 Stopped: 4
Images: 22
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: vg0-thinpool-tpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 4.196 GB
 Data Space Total: 42.95 GB
 Data Space Available: 38.75 GB
 Metadata Space Used: 831.5 kB
 Metadata Space Total: 1.074 GB
 Metadata Space Available: 1.073 GB
 Thin Pool Minimum Free Space: 4.295 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.90 (2014-09-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.35 GiB
Name: west
ID: ZZP6:PCGK:YFDX:EOB4:WIMM:24KL:ZEGE:4KDA:COVG:WWVM:UJUQ:6Z4G
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical

### LINKED ISSUE #27289: Output from stdout for `docker exec` sometimes isn't returned / displayed
**Description**

Output from `docker exec` sometimes isn't returned/displayed. I've seen this in both 1.11.2 and 1.12.1. I *think* this may apply to `docker attach` as well, but I have only ever tested with exec.

**Steps to reproduce the issue:**
1. `sudo docker run -d --name nginx nginx`
2. `while true; do output=$(sudo docker exec nginx echo running in container); echo "${output}"; if [ "${output}" != "running in container" ]; then echo OMG; break; fi; done`

**Describe the results you received:**
After numerous iterations, each printing out `running in container` correctly, I see a blank line followed by my error indicator (`OMG`). Here is the tail of the results:

```
running in container
running in container
running in container

OMG
```

**Describe the results you expected:**

An endless display of `running in container` and never any blank lines.

**Additional information you deem important (e.g. issue happens only occasionally):**

This happens sporadically. I've seen it take anywhere from 10 minutes to about an hour or more to reproduce.

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-8:1-256115-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 250.8 MB
 Data Space Total: 107.4 GB
 Data Space Available: 8.914 GB
 Metadata Space Used: 876.5 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.110 (2015-10-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 992.3 MiB
Name: ubuntu-xenial
ID: 7D6Z:FC5P:U5BW:W622:Z4H2:PUZE:VDCV:NW4I:HGKD:DYUB:6XQO:VGEX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 19
 Goroutines: 29
 System Time: 2016-10-11T15:22:07.361345248Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I've tested this in GCE using the GCI image with 1.11.2. I've also tested on VirtualBox using Ubuntu Xenial with both 1.11.2 and 1.12.1.

cc @runcom

### PR DESCRIPTION
**Pull request by tonistiigi**
fixes #27289
fixes #27011

Move stdio attaching from backend to callback to fix to keep the lock during startup. Still not very nice because we need to expose public methods because the split between daemon/container/streamconfig is quite arbitrary.

@mlaventure 

Signed-off-by: Tonis Tiigi tonistiigi@gmail.com

### CODE REVIEW

**Comment by mlaventure** [comment]
:+1: for the moving of the logging routine into the container object.

File: runconfig/streams.go [hunk 1]
```diff
@@ -107,3 +109,34 @@ func (streamConfig *StreamConfig) CloseStreams() error {
 
 	return nil
 }
+
+// CopyToPipe connects streamconfig with a libcontainerd.IOPipe
+func (streamConfig *StreamConfig) CopyToPipe(iop libcontainerd.IOPipe) {
+	copyFunc := func(w io.Writer, r io.Reader) {
+		streamConfig.Add(1)
+		go func() {
+			if _, err := io.Copy(w, r); err != nil {
```
Comment (LK4D4) [inline runconfig/streams.go]: I wonder if we're here it makes sense to use `pools.Copy`, because each copy allocates 32Kb regardless of real copy size.

File: libcontainerd/client_linux.go [hunk 2]
```diff
@@ -98,13 +98,9 @@ func (clnt *client) AddProcess(ctx context.Context, containerID, processFriendly
 
 	container.processes[processFriendlyName] = p
 
-	clnt.unlock(containerID)
-
-	if err := clnt.backend.AttachStreams(processFriendlyName, *iopipe); err != nil {
-		clnt.lock(containerID)
+	if err := attachStdio(*iopipe); err != nil {
```
Comment (LK4D4) [inline libcontainerd/client_linux.go]: Sort of unrelated question, but why don't just use `IOPipe` values everywhere to avoid `*`.

File: runconfig/streams.go (hunk 1 above)
Comment (tonistiigi) [inline runconfig/streams.go]: updated

File: libcontainerd/client_linux.go (hunk 2 above)
Comment (tonistiigi) [inline libcontainerd/client_linux.go]: Could change that. It's so because it is easier to return nil instead empty struct in `openFifos` and I didn't want to pass pointers through pkg boundary when the other side is not meant to change the struct.

**Comment by tonistiigi** [comment]
@ncdc Can you check if this fixes #27289 for you?

File: libcontainerd/client_linux.go (hunk 2 above)
Comment (LK4D4) [inline libcontainerd/client_linux.go]: thanks for an explanation, definitely not this PR material

**Comment by ncdc** [comment]
@tonistiigi I'll be happy to give it a spin. Although, given the current lack of a deterministic reproducer, it's hard to say with certainty that any potential fix resolves the issue. Do you have any suggestions for how to make this race happen all the time?

**Comment by tonistiigi** [comment]
@ncdc In old code the problem can be reproduced by adding a sleep to https://github.com/docker/docker/blob/668189e7f007dcf276f94453504ee1d7a187ba7f/daemon/monitor.go#L159 . With this patch that part of the code is removed.

File: runconfig/streams.go [hunk 3]
```diff
@@ -107,3 +110,34 @@ func (streamConfig *StreamConfig) CloseStreams() error {
...
+		copyFunc(streamConfig.Stdout(), iop.Stdout)
+	}
+	if iop.Stderr != nil {
+		copyFunc(streamConfig.Stderr(), iop.Stderr)
+	}
+
+	if stdin := streamConfig.Stdin(); stdin != nil {
+		if iop.Stdin != nil {
+			go func() {
+				io.Copy(iop.Stdin, stdin)
```
Comment (LK4D4) [inline runconfig/streams.go]: should be pools too :)

Comment (tonistiigi) [inline runconfig/streams.go]: thanks

**Comment by LK4D4** [comment]
LGTM

**Comment by ncdc** [comment]
cc @runcom @mrunalp @jwhonce

**Comment by runcom** [comment]
@ncdc is this working for you? (at least to your reproducer)

**Comment by ncdc** [comment]
So far so good. I had my endless loop running for a couple of days and it didn't fail.

**Comment by runcom** [comment]
@tonistiigi needs a rebase, ping @mlaventure

**Comment by runcom** [comment]
LGTM

**Comment by ncdc** [comment]
I've got a test running and will take a look once I'm at my desk

**Comment by tonistiigi** [comment]
@tonylambiris That should be a dupe of #27760

**Comment by tonylambiris** [comment]
Thanks for the update. :+1:
