### PR TITLE
Skip UTF-8 BOM bytes from Dockerfile and .dockerignore if exist

### LINKED ISSUE #23221: 'Unknown instruction: FROM' when docker build
**Output of `docker version`:**

```
root@ubuntu:~/dockerfiles# docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
root@ubuntu:~/dockerfiles# docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 38
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 376
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: ubuntu
ID: HRBI:EV6M:3NAC:CXZ3:BDS7:UOKL:PD6Y:ZCK4:V3PF:V7MR:CU2Y:3LGG
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 29
 System Time: 2016-06-03T10:57:29.679646373+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
root@ubuntu:~/dockerfiles# uname -a
Linux ubuntu 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Steps to reproduce the issue:**
1.
```
root@ubuntu:~/dockerfiles# docker build -t="test" .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM
Unknown instruction: FROM
```

**Additional information you deem important (e.g. issue happens only occasionally):**
Dockerfile Details
```
root@ubuntu:~/dockerfiles# cat Dockerfile
FROM daocloud.io/ubuntu:trusty
```
This happens on docker 1.8.3 and docker 1.9.1.

And if I copy the content to another Dockerfile, it works fine. So I wonder if this Dockerfile's file format and attributes stop the build procedure.

Unfortunately, Github does not support attachment of Dockerfile.

### PR DESCRIPTION
**Pull request by yongtang**
**\- What I did**

This fix tries to address issues in #23221 where Dockerfile or .dockerignore may consists of UTF-8 BOM. This likely happens when Notepad tries to save a file as UTF-8 in Windows.

**\- How I did it**

This fix skips the UTF-8 BOM bytes from the beginning of the Dockerfile or .dockerignore if exist.

**\- How to verify it**

Additional tests has been added to cover the changes in this fix.

**\- Description for the changelog**

Skip UTF-8 BOM bytes from the beginning of the Dockerfile or .dockerignore if exist.

**\- A picture of a cute animal (not mandatory but encouraged)**

This fix fixes #23221.

Signed-off-by: Yong Tang yong.tang.github@outlook.com

### CODE REVIEW

**Comment by justincormack** [comment]
cc @jhowardmsft

**Comment by justincormack** [comment]
I think this is a good idea, as I have seen the pain of random things failing for this reason in the past and being asked to debug. It should I guess also apply to `.dockerignore`?

File: builder/dockerfile/parser/parser.go [hunk 1]
```diff
@@ -152,8 +153,14 @@ func Parse(rwc io.Reader) (*Node, error) {
 	root.StartLine = -1
 	scanner := bufio.NewScanner(rwc)
 
+	utf8bom := []byte{0xEF, 0xBB, 0xBF}
 	for scanner.Scan() {
-		scannedLine := strings.TrimLeftFunc(scanner.Text(), unicode.IsSpace)
+		scannedBytes := scanner.Bytes()
+		// We trim UTF8 BOM
+		if currentLine == 0 && bytes.HasPrefix(scannedBytes, utf8bom) {
```
Comment (thaJeztah) [inline builder/dockerfile/parser/parser.go]: the `bytes.HasPrefix()` is redundant, because `TrimPrefix()` already does this; https://golang.org/src/strings/strings.go?s=16765:16805#L612

**Comment by thaJeztah** [comment]
Got bit by this a few times, sgtm

**Comment by allencloud** [comment]
Great. Thanks @yongtang

File: builder/dockerfile/parser/parser.go (hunk 1 above)
Comment (yongtang) [inline builder/dockerfile/parser/parser.go]: Thanks @thaJeztah The pull request has been updated to remove the `bytes.HasPrefix()`.

**Comment by yongtang** [comment]
Thanks @justincormack @thaJeztah @allencloud for the feedback. I updated the pull request. Now UTF-8 BOM in bother Dockerfile and .dockerignore will be skipped. Let me know if there are any issues.

**Comment by jhowardmsft** [comment]
LGTM

**Comment by thaJeztah** [comment]
LGTM failing test is https://github.com/docker/docker/issues/23246

**Comment by thaJeztah** [comment]
Windows failure is not related, and will be fixed in https://github.com/docker/docker/issues/23246, so ignoring that failing test
