### PR TITLE
cli: Wrong error message from "node ps" outside swarm mode

### LINKED ISSUE #31879: `docker node ps` does not check for swarm node
If you issue swarm commands on a non-swarm node, you get an error indicating that the command can only be issued on a swarm manager. Example:

```bash
$ docker node ls
Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.
```
This is not true for `docker node ps`:
```bash
$ docker node ps
ID                  NAME                IMAGE               NODE                DESIRED STATE       CURRENT STATE       ERROR               PORTS
Error: No such node:
```

### PR DESCRIPTION
**Pull request by aaronlehmann**
`docker node ps` behaves strangely outside swarm mode:

    $ docker node ps
    ID                  NAME                IMAGE               NODE                DESIRED STATE       CURRENT STATE       ERROR               PORTS
    Error: No such node:

It should explain that the node is not a swarm manager.

The reason this happens is that the argument to `docker node ps` defaults
to "self". The first thing the command does is try to resolve "self" to
a node ID using the /info endpoint. If there is no node ID, it tries to
use the empty string as an ID, and tries to `GET /nodes/`, which is not a
valid endpoint.

Change the command to check if the node ID is present in the /info
response. If it isn't, a swarm API endpoint can supply a useful error
message.

Also, avoid printing the column headers if the only following text is an
error.

Fixes #31879

### CODE REVIEW

File: cli/command/node/cmd.go [hunk 1]
```diff
@@ -38,6 +41,16 @@ func Reference(ctx context.Context, client apiclient.APIClient, ref string) (str
 		if err != nil {
 			return "", err
 		}
+		if info.Swarm.NodeID == "" {
+			// If there's no node ID in /info, the node probably
+			// isn't a manager. Call a swarm-specific endpoint to
+			// get a more specific error message.
+			_, err = client.NodeList(ctx, types.NodeListOptions{})
```
Comment (thaJeztah) [inline cli/command/node/cmd.go]: It looks like we now have different approaches (and multiple locations) where we check if it's a manager;

using `info.Swarm.ControlAvailable`;
https://github.com/docker/docker/blob/b0d1936d304824dc0438b200d269e2d4e0751fcc/cli/command/stack/deploy.go#L65-L78

using `info.Swarm.LocalNodeState`;
https://github.com/docker/docker/blob/38f766ae0e4b80d452a3825c42a7ac9fee965790/cli/command/swarm/unlock.go#L47-L49

Should we have a single function to perform this check? (Not sure which one of the above is best :smile:)

Comment (aaronlehmann) [inline cli/command/node/cmd.go]: My first approach was to use `info.Swarm.ControlAvailable`, but this misses important information that might cause alternate error messages, like the node being locked.

I think the best way is to either do what I'm doing here, or port this function to the client:

https://github.com/docker/docker/blob/250e05e42773a875d2fb8248b94fa72f2934a4b6/daemon/cluster/cluster.go#L313-L329

Comment (thaJeztah) [inline cli/command/node/cmd.go]: It was also out of interest, because I saw the multiple implementations, and was hoping we could have a single "here's what to use" function.

If `info.Swarm.ControlAvailable` is true, but the node is locked, won't the `NodeInspectWithRaw ` API call still fail? https://github.com/docker/docker/blob/b1debf1374ca7be7e7b4d4fcd41eceaf8b7cf153/cli/command/node/ps.go#L71-L75

Comment (aaronlehmann) [inline cli/command/node/cmd.go]: I don't believe that combination is possible. If the node is locked, the control socket is not available.

**Comment by AkihiroSuda** [comment]
Should we have an IT?

File: cli/command/node/cmd.go (hunk 1 above)
Comment (thaJeztah) [inline cli/command/node/cmd.go]: Oh, I must've misunderstood, was confused by

> My first approach was to use info.Swarm.ControlAvailable, but this misses important information that might cause alternate error messages, like the node being locked

**Review by thaJeztah — APPROVED** [review]
LGTM, but @AkihiroSuda suggested to have an integration test

**Review by vdemeester — APPROVED** [review]
LGTM 🦁
