### PR TITLE
Network not deleted after stack is removed

### LINKED ISSUE #39225: `docker swarm leave` doesn't remove all Swarm networks
**Description**

Since 19.03.0-beta4, swarm tests are failing on Docker Desktop CI. It seems that after a `docker swarm leave`, Swarm networks are still present. 

Our tests are doing in BeforeEach and AfterEach `docker swarm init` and `docker swarm leave --force`. After the first test, a network is left in the network list.
The second test is then failing and we can see in the log: `Pool overlaps with other one on this address space`

Looking at the git log, this commit seems the faulty one: https://github.com/moby/moby/commit/2a7513a9721a222e384850c524aa499f80a40a7a

**Steps to reproduce the issue:**

```
#!/bin/sh -x
docker swarm init
cat > docker-compose.yml <<EOT
version: "3"
services:

  test:
    image: nginx
EOT
docker pull nginx
docker stack deploy mystack -c docker-compose.yml
sleep 10
docker stack rm mystack
docker swarm leave --force
docker network ls
```

**Describe the results you received:**

```
NETWORK ID          NAME                DRIVER              SCOPE
4569577938d3        bridge              bridge              local
dbc909e550ba        docker_gwbridge     bridge              local
8cb6e9320a38        host                host                local
s6dz39bbxf9x        mystack_default     overlay             swarm
35074e31cf14        none                null                local
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Enterprise
 Version:           19.03.0-beta4
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        d9934ea
 Built:             Tue May 14 06:40:00 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.0-beta4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       d9934ea
  Built:            Tue May 14 06:46:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

### PR DESCRIPTION
**Pull request by arkodg**
Make sure adapter.removeNetworks executes during task Remove

Fixes https://github.com/moby/moby/issues/39225
Relates to https://github.com/moby/moby/pull/39174

Signed-off-by: Arko Dasgupta <arko.dasgupta@docker.com>

**- How to verify it**
```
docker swarm init
cat > docker-compose.yml <<EOT
version: "3"
services:

  test:
    image: nginx
EOT
docker pull nginx
docker stack deploy mystack -c docker-compose.yml
sleep 50
docker stack rm mystack
docker swarm leave --force
docker network ls
```

### CODE REVIEW

**Comment by arkodg** [comment]
@thaJeztah @mavenugo  PTAL, was not aware of all the state machine changes in swarm .
Looks like `isUnknownContainer(err)` is `true` after `r.adapter.remove` is executed which caused us to skip `r.adapter.removeNetworks`

**Comment by arkodg** [comment]
Derek add label:rebuild

**Comment by thaJeztah** [comment]
Failure looks genuine; all of these are failing on the same;


- Experimental; https://jenkins.dockerproject.org/job/Docker-PRs-experimental/45326/console
- Janky: https://jenkins.dockerproject.org/job/Docker-PRs/54184/console
- PowerPC: https://jenkins.dockerproject.org/job/Docker-PRs-powerpc/14426/console
- s390x: https://jenkins.dockerproject.org/job/Docker-PRs-s390x/14344/console

```
22:05:06 --- FAIL: TestServiceUpdateNetwork (14.06s)
22:05:06     update_test.go:201: Creating a new daemon
22:05:06     daemon.go:300: [d4dfefb9307a3] waiting for daemon to start
22:05:06     daemon.go:332: [d4dfefb9307a3] daemon started
22:05:06     update_test.go:242: assertion failed: expression is false: len(netInfo.Containers) == 0: Load balancing endpoint still exists in network
22:05:06     daemon.go:284: [d4dfefb9307a3] exiting daemon
```

**Comment by arkodg** [comment]
Derek add label: rebuild

**Comment by olljanat** [comment]
Derek add label: rebuild/*

**Comment by olljanat** [comment]
@arkodg FYI, you can see valid labels on https://github.com/moby/moby/blob/2b8b0fefb758087852227cb8db7709ec2507f725/poule.yml#L38-L101 

and *status/failing-ci* label need to be removed first other why CI will not be triggered.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
ping @kolyshkin @tiborvass @cpuguy83 PTAL

**Comment by kolyshkin** [comment]
@arkodg could you please provide a longer description in the commit message, explaining why you made this change and what it does to the code flow?

File: daemon/cluster/executor/container/controller.go [hunk 1]
```diff
@@ -369,20 +369,17 @@ func (r *controller) Shutdown(ctx context.Context) error {
...
-
-		return err
 	}
 
 	// Try removing networks referenced in this task in case this
 	// task is the last one referencing it
 	if err := r.adapter.removeNetworks(ctx); err != nil {
-		if isUnknownContainer(err) {
-			return nil
+		if !isUnknownContainer(err) {
```
Comment (cpuguy83) [inline daemon/cluster/executor/container/controller.go]: Why are we looking for unknown container here?

**Comment by cpuguy83** [comment]
These error checks are wrong.
We should be using `errdefs.IsNotFound` and `errdefs.Conflict` (or maybe `errdefs.IsNotModified` in the case of stopping a stopped container).

File: daemon/cluster/executor/container/controller.go (hunk 1 above)
Comment (arkodg) [reply daemon/cluster/executor/container/controller.go]: this was already part of the original code, I'm not aware of the exact case for why it was needed

**Comment by arkodg** [comment]
> These error checks are wrong.
> We should be using `errdefs.IsNotFound` and `errdefs.Conflict` (or maybe `errdefs.IsNotModified` in the case of stopping a stopped container).
@cpuguy83  are you suggesting to replace `isUnknownContainer` with `errdefs.IsNotFound`
and with isStoppedContainer with `errdefs.IsNotModified` . I can make those changes

File: daemon/cluster/executor/container/controller.go (hunk 1 above)
Comment (arkodg) [reply daemon/cluster/executor/container/controller.go]: looks like it was introduced by https://github.com/moby/moby/commit/534a90a99367af6f6bba1ddcc7eb07506e41f774

**Comment by arkodg** [comment]
Derek add label: rebuild/*

**Comment by thaJeztah** [comment]
ping @kolyshkin @cpuguy83 PTAL

**Review by tiborvass — APPROVED** [review]
