### PR TITLE
Fix premature close of build output on pull

### LINKED ISSUE #10364: incomplete /build response payload for non-cached /build
With docker 1.5.0-rc1 (mentioned in https://github.com/docker/docker/pull/10286) the response payload for /build seems incomplete w/ an empty cache:
```
>>> cli = docker.Client(**docker.utils.kwargs_from_env(assert_hostname=False)); cli.version()
{u'KernelVersion': u'3.16.7-tinycore64', u'Arch': u'amd64', u'ApiVersion': u'1.17', u'Version': u'1.5.0', u'GitCommit': u'7e803ba', u'Os': u'linux', u'GoVersion': u'go1.4.1'}
>>> print [x for x in cli.build(path='/tmp/context')]
['{"stream":"Step 0 : FROM busybox\\n"}\r\n', '{"status":"Pulling repository busybox"}\r\n', '{"status":"Pulling image (latest) from busybox","progressDetail":{},"id":"4986bf8c1536"}', '{"status":"Pulling image (latest) from busybox, endpoint: https://registry-1.docker.io/v1/","progressDetail":{},"id":"4986bf8c1536"}', '{"status":"Pulling dependent layers","progressDetail":{},"id":"4986bf8c1536"}', '{"status":"Pulling metadata","progressDetail":{},"id":"511136ea3c5a"}', '{"status":"Pulling fs layer","progressDetail":{},"id":"511136ea3c5a"}', '{"status":"Downloading","progressDetail":{"current":3646,"total":10240,"start":1422312173},"progress":"[=================\\u003e                                 ] 3.646 kB/10.24 kB 0","id":"511136ea3c5a"}', '{"status":"Download complete","progressDetail":{},"id":"511136ea3c5a"}', '{"status":"Pulling metadata","progressDetail":{},"id":"df7546f9f060"}', '{"status":"Pulling fs layer","progressDetail":{},"id":"df7546f9f060"}', '{"status":"Downloading","progressDetail":{"current":180,"total":180,"start":1422312175},"progress":"[==================================================\\u003e]    180 B/180 B","id":"df7546f9f060"}', '{"status":"Download complete","progressDetail":{},"id":"df7546f9f060"}', '{"status":"Pulling metadata","progressDetail":{},"id":"ea13149945cb"}', '{"status":"Pulling fs layer","progressDetail":{},"id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":13686,"total":1141531,"start":1422312177},"progress":"[\\u003e                                                  ] 13.69 kB/1.142 MB 1m8s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":33958,"total":1141531,"start":1422312177},"progress":"[=\\u003e                                                 ] 33.96 kB/1.142 MB 27s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":50342,"total":1141531,"start":1422312177},"progress":"[==\\u003e                                                ] 50.34 kB/1.142 MB 19s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":68710,"total":1141531,"start":1422312177},"progress":"[===\\u003e                                               ] 68.71 kB/1.142 MB 14s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":85094,"total":1141531,"start":1422312177},"progress":"[===\\u003e                                               ] 85.09 kB/1.142 MB 11s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":101478,"total":1141531,"start":1422312177},"progress":"[====\\u003e                                              ] 101.5 kB/1.142 MB 9s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":117862,"total":1141531,"start":1422312177},"progress":"[=====\\u003e                                             ] 117.9 kB/1.142 MB 7s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":134246,"total":1141531,"start":1422312177},"progress":"[=====\\u003e                                             ] 134.2 kB/1.142 MB 6s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":150630,"total":1141531,"start":1422312177},"progress":"[======\\u003e                                            ] 150.6 kB/1.142 MB 6s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":167014,"total":1141531,"start":1422312177},"progress":"[=======\\u003e                                           ]   167 kB/1.142 MB 5s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":183398,"total":1141531,"start":1422312177},"progress":"[========\\u003e                                          ] 183.4 kB/1.142 MB 4s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":199782,"total":1141531,"start":1422312177},"progress":"[========\\u003e                                          ] 199.8 kB/1.142 MB 4s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":216166,"total":1141531,"start":1422312177},"progress":"[=========\\u003e                                         ] 216.2 kB/1.142 MB 3s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":232550,"total":1141531,"start":1422312177},"progress":"[==========\\u003e                                        ] 232.6 kB/1.142 MB 3s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":248934,"total":1141531,"start":1422312177},"progress":"[==========\\u003e                                        ] 248.9 kB/1.142 MB 3s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":265318,"total":1141531,"start":1422312177},"progress":"[===========\\u003e                                       ] 265.3 kB/1.142 MB 3s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":281702,"total":1141531,"start":1422312177},"progress":"[============\\u003e                                      ] 281.7 kB/1.142 MB 2s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":298086,"total":1141531,"start":1422312177},"progress":"[=============\\u003e                                     ] 298.1 kB/1.142 MB 2s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":314470,"total":1141531,"start":1422312177},"progress":"[=============\\u003e                                     ] 314.5 kB/1.142 MB 2s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":330854,"total":1141531,"start":1422312177},"progress":"[==============\\u003e                                    ] 330.9 kB/1.142 MB 2s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":347238,"total":1141531,"start":1422312177},"progress":"[===============\\u003e                                   ] 347.2 kB/1.142 MB 2s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":363622,"total":1141531,"start":1422312177},"progress":"[===============\\u003e                                   ] 363.6 kB/1.142 MB 2s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":380006,"total":1141531,"start":1422312177},"progress":"[================\\u003e                                  ]   380 kB/1.142 MB 1s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":396390,"total":1141531,"start":1422312177},"progress":"[=================\\u003e                                 ] 396.4 kB/1.142 MB 1s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":412774,"total":1141531,"start":1422312177},"progress":"[==================\\u003e                                ] 412.8 kB/1.142 MB 1s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":429158,"total":1141531,"start":1422312177},"progress":"[==================\\u003e                                ] 429.2 kB/1.142 MB 1s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":445542,"total":1141531,"start":1422312177},"progress":"[===================\\u003e                               ] 445.5 kB/1.142 MB 1s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":461926,"total":1141531,"start":1422312177},"progress":"[====================\\u003e                              ] 461.9 kB/1.142 MB 1s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":478310,"total":1141531,"start":1422312177},"progress":"[====================\\u003e                              ] 478.3 kB/1.142 MB 1s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":494694,"total":1141531,"start":1422312177},"progress":"[=====================\\u003e                             ] 494.7 kB/1.142 MB 1s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":511078,"total":1141531,"start":1422312177},"progress":"[======================\\u003e                            ] 511.1 kB/1.142 MB 1s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":527462,"total":1141531,"start":1422312177},"progress":"[=======================\\u003e                           ] 527.5 kB/1.142 MB 1s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":543846,"total":1141531,"start":1422312177},"progress":"[=======================\\u003e                           ] 543.8 kB/1.142 MB 1s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":560230,"total":1141531,"start":1422312177},"progress":"[========================\\u003e                          ] 560.2 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":576614,"total":1141531,"start":1422312177},"progress":"[=========================\\u003e                         ] 576.6 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":592998,"total":1141531,"start":1422312177},"progress":"[=========================\\u003e                         ]   593 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":609382,"total":1141531,"start":1422312177},"progress":"[==========================\\u003e                        ] 609.4 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":625766,"total":1141531,"start":1422312177},"progress":"[===========================\\u003e                       ] 625.8 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":642150,"total":1141531,"start":1422312177},"progress":"[============================\\u003e                      ] 642.1 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":658534,"total":1141531,"start":1422312177},"progress":"[============================\\u003e                      ] 658.5 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":674918,"total":1141531,"start":1422312177},"progress":"[=============================\\u003e                     ] 674.9 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":691302,"total":1141531,"start":1422312177},"progress":"[==============================\\u003e                    ] 691.3 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":707686,"total":1141531,"start":1422312177},"progress":"[==============================\\u003e                    ] 707.7 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":724070,"total":1141531,"start":1422312177},"progress":"[===============================\\u003e                   ] 724.1 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":740454,"total":1141531,"start":1422312177},"progress":"[================================\\u003e                  ] 740.5 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":756838,"total":1141531,"start":1422312177},"progress":"[=================================\\u003e                 ] 756.8 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":773222,"total":1141531,"start":1422312177},"progress":"[=================================\\u003e                 ] 773.2 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":789606,"total":1141531,"start":1422312177},"progress":"[==================================\\u003e                ] 789.6 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":805990,"total":1141531,"start":1422312177},"progress":"[===================================\\u003e               ]   806 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":822374,"total":1141531,"start":1422312177},"progress":"[====================================\\u003e              ] 822.4 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":838758,"total":1141531,"start":1422312177},"progress":"[====================================\\u003e              ] 838.8 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":855142,"total":1141531,"start":1422312177},"progress":"[=====================================\\u003e             ] 855.1 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":871526,"total":1141531,"start":1422312177},"progress":"[======================================\\u003e            ] 871.5 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":887910,"total":1141531,"start":1422312177},"progress":"[======================================\\u003e            ] 887.9 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":904294,"total":1141531,"start":1422312177},"progress":"[=======================================\\u003e           ] 904.3 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":920678,"total":1141531,"start":1422312177},"progress":"[========================================\\u003e          ] 920.7 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":937062,"total":1141531,"start":1422312177},"progress":"[=========================================\\u003e         ] 937.1 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":953446,"total":1141531,"start":1422312177},"progress":"[=========================================\\u003e         ] 953.4 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":969830,"total":1141531,"start":1422312177},"progress":"[==========================================\\u003e        ] 969.8 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":986214,"total":1141531,"start":1422312177},"progress":"[===========================================\\u003e       ] 986.2 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":1002598,"total":1141531,"start":1422312177},"progress":"[===========================================\\u003e       ] 1.003 MB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":1018982,"total":1141531,"start":1422312177},"progress":"[============================================\\u003e      ] 1.019 MB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":1035366,"total":1141531,"start":1422312177},"progress":"[=============================================\\u003e     ] 1.035 MB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":1051750,"total":1141531,"start":1422312177},"progress":"[==============================================\\u003e    ] 1.052 MB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":1068134,"total":1141531,"start":1422312177},"progress":"[==============================================\\u003e    ] 1.068 MB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":1084518,"total":1141531,"start":1422312177},"progress":"[===============================================\\u003e   ] 1.085 MB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":1100902,"total":1141531,"start":1422312177},"progress":"[================================================\\u003e  ] 1.101 MB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":1117286,"total":1141531,"start":1422312177},"progress":"[================================================\\u003e  ] 1.117 MB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":1133670,"total":1141531,"start":1422312177},"progress":"[=================================================\\u003e ] 1.134 MB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":1141531,"total":1141531,"start":1422312177},"progress":"[==================================================\\u003e] 1.142 MB/1.142 MB","id":"ea13149945cb"}', '{"status":"Download complete","progressDetail":{},"id":"ea13149945cb"}', '{"status":"Pulling metadata","progressDetail":{},"id":"4986bf8c1536"}', '{"status":"Pulling fs layer","progressDetail":{},"id":"4986bf8c1536"}', '{"status":"Downloading","progressDetail":{"current":32,"total":32,"start":1422312179},"progress":"[==================================================\\u003e]     32 B/32 B","id":"4986bf8c1536"}', '{"status":"Download complete","progressDetail":{},"id":"4986bf8c1536"}', '{"status":"Download complete","progressDetail":{},"id":"4986bf8c1536"}', '{"status":"Status: Downloaded newer image for busybox:latest"}\r\n']
```

Wheras cached build would produce:
```
>>> print [x for x in cli.build(path='/tmp/context')]
['{"stream":"Step 0 : FROM busybox\\n"}\r\n', '{"stream":" ---\\u003e 4986bf8c1536\\n"}\r\n', '{"stream":"Step 1 : ADD true /true\\n"}\r\n', '{"stream":" ---\\u003e Using cache\\n"}\r\n', '{"stream":" ---\\u003e 13d576188811\\n"}\r\n', '{"stream":"Step 2 : CMD /true\\n"}\r\n', '{"stream":" ---\\u003e Using cache\\n"}\r\n', '{"stream":" ---\\u003e e2791e1d42aa\\n"}\r\n', '{"stream":"Successfully built e2791e1d42aa\\n"}\r\n']
```

This could break third-party integration that assume on a stable json schema from `/build` api call.

### PR DESCRIPTION
**Pull request by jlhawn**
The `build` job will sometimes trigger a `pull` job when the base image
does not exist. Now that engine jobs properly close their output by default
the pull job would also close the build job's stdout in a cascading close
upon completion of the pull.

This patch corrects this to set the `pull` job to not close it's IO when
complete. It also adds a warning log when a job writes to output with no
destinations and makes it an error to call `Write()` on a job output that
has already been closed.

fixes #10364

### CODE REVIEW

**Comment by jlhawn** [comment]
Another fix would have been to make the `pull` job with stdout wrapped in an `ioutil.NopCloser`.

**Comment by jlhawn** [comment]
er, the equivalent version of `ioutil.NopCloser` but for a writer.

**Comment by dqminh** [comment]
I think wrapping `pull` job stdout is probably a cleaner fix.

File: engine/streams.go [hunk 1]
```diff
@@ -82,9 +86,19 @@ func (o *Output) AddPipe() (io.Reader, error) {
 // Write writes the same data to all registered destinations.
 // This method is thread-safe.
 func (o *Output) Write(p []byte) (n int, err error) {
+	if o.closed {
```
Comment (dmcgowan) [inline engine/streams.go]: Shouldn't this be done inside the lock to prevent a race condition

**Comment by jlhawn** [comment]
While I think better close handling in the engine Output is also a good idea in the long run, I've updated this patch to just wrap the `pull` job's stdout with a NopCloseWriter for now as the first fix breaks too many tests.

**Comment by tiborvass** [comment]
@jlhawn much better, and solves the problem!

LGTM

**Comment by jlhawn** [comment]
@tiborvass said:

> much better

I disagree that it's better, but I'll fix the `engine.Output` stuff later.

**Comment by unclejack** [comment]
@jlhawn Can you also add a test for this, please?

**Comment by jlhawn** [comment]
@unclejack I added a unit test to the `engine` package with a note to fix the write-on-closed-output behavior in the future.

File: builder/internals.go [hunk 2]
```diff
@@ -433,7 +434,7 @@ func (b *Builder) pullImage(name string) (*imagepkg.Image, error) {
 	job.SetenvBool("json", b.StreamFormatter.Json())
 	job.SetenvBool("parallel", true)
 	job.SetenvJson("authConfig", pullRegistryAuth)
-	job.Stdout.Add(b.OutOld)
+	job.Stdout.Add(ioutils.NopWriteCloser(b.OutOld))
```
Comment (proppy) [inline builder/internals.go]: wouldn't that mean that you also discard any output from pull?

Comment (jlhawn) [inline builder/internals.go]: Sorry, I don't quite understand the question. :( The cause of the issue that you reported was that when the "pull" job ends it would close its Stdout which is also the "build" job's stdout. This makes the the "pull" job's Stdout Close no longer propagate and close the "build" Stdout.

Comment (jlhawn) [inline builder/internals.go]: Oh wait - maybe you're confused by the name `NopWriteCloser`. This makes only the `Close` call be a nop - the writes still work and are written to the underlying writer.

**Comment by LK4D4** [comment]
LGTM
