### PR TITLE
Make plugin removes more resilient to failure

### LINKED ISSUE #33799: Unable to start the docker engine after a plugin rm -f (17.06 RC5)
**Description**
The `docker engine` is unable to start after an `enabled` plugin is removed with `docker plugin rm -f`. It's important to notice that this plugin is using the `propagated mount` and that seems to be related to this issue. 

**Steps to reproduce the issue:**
1. `docker plugin ls`
```
[root@ip-172-31-34-7 plugins]# docker plugin ls
ID                  NAME                                           ENABLED
52d8df7621aa        rogaha/metrics-plugin:17.06.0.ce-1.0.0-test      true
```
1. `docker rm -f rogaha/metrics-plugin:17.06.0.ce-1.0.0-test`
2. `systemctl stop docker`
3. `systemctl start docker`

**Describe the results you received:**
```
-- Unit docker.service has begun starting up.
Jun 23 11:07:42 ip-172-31-34-7.us-west-2.compute.internal dockerd[2484]: time="2017-06-23T11:07:42.582778118-04:00" level=info msg="libcontainerd: new containerd process, pid: 2487"
Jun 23 11:07:43 ip-172-31-34-7.us-west-2.compute.internal dockerd[2484]: Error starting daemon: couldn't create plugin manager: failed to restore plugins: error reading /var/lib/docker/plugins/52d8df7621aa99c40dabece633f388fcb1b7c567ae93eed79fe906860a17c559/config.json: open /var/lib/docker/plugins/52d8df7621aa99c40dabece633f388fcb1b7c567ae93eed79fe906860a17c559/config.json: no such file or directory
Jun 23 11:07:43 ip-172-31-34-7.us-west-2.compute.internal systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Jun 23 11:07:43 ip-172-31-34-7.us-west-2.compute.internal systemd[1]: Failed to start Docker Application Container Engine.
```

**Describe the results you expected:**
`Docker engine` should properly remove the `running` plugin and `start` the docker engine once it's stopped. 

**Additional information you deem important (e.g. issue happens only occasionally):**
### Directory before removing the plugin 
```
[root@ip-172-31-34-7 plugins]# ls 52d8df7621aa99c40dabece633f388fcb1b7c567ae93eed79fe906860a17c559
config.json  propagated-mount  rootfs
```

### Directory after removing the plugin with `rm -f`
```
[root@ip-172-31-34-7 plugins]# ls 52d8df7621aa99c40dabece633f388fcb1b7c567ae93eed79fe906860a17c559/
rootfs
[root@ip-172-31-34-7 plugins]# rm -rf 52d8df7621aa99c40dabece633f388fcb1b7c567ae93eed79fe906860a17c559/
rm: cannot remove ‘52d8df7621aa99c40dabece633f388fcb1b7c567ae93eed79fe906860a17c559/rootfs/run/docker’: Device or resource busy
[root@ip-172-31-34-7 plugins]#
```

After restarting the `VM`, I'm able to manually remove the `52d8df7621aa99c40dabece633f388fcb1b7c567ae93eed79fe906860a17c559` directory and start the `docker engine`.

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce-rc5
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   b7e4173
 Built:        Thu Jun 22 16:51:12 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce-rc5
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   b7e4173
 Built:        Thu Jun 22 16:52:22 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Server Version: 17.06.0-ce-rc5
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.795GiB
Name: ip-172-31-34-7.us-west-2.compute.internal
ID: ZQ2M:QT7C:33GG:IIHD:KMYL:NRSH:FFAZ:COS6:3YLE:JU6I:VG6J:JPAJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

/cc @cpuguy83 @anusha-ragunathan @tiborvass

### PR DESCRIPTION
**Pull request by cpuguy83**
Before this patch, if the plugin's `config.json` is successfully removed
but the main plugin state dir could not be removed for some reason (e.g.
leaked mount), it will prevent the daemon from being able to be
restarted.

This patches changes this to atomically remove the plugin such that on
daemon restart we can detect that there was an error and re-try. It also
changes the logic so that it only logs errors on restore rather than
erroring out the daemon.

This also removes some code which is now duplicated elsewhere.

Fixes #33799

### CODE REVIEW

**Comment by cpuguy83** [comment]
ping @rogaha

**Review by rogaha — APPROVED** [review]
LGTM

Thanks for the quick turnaround @cpuguy83!

**Comment by rogaha** [comment]
@cpuguy83 I confirm that now the engine starts as expected. 

```
[root@ip-172-31-34-7 tmp]# docker plugin ls
ID                  NAME                                       DESCRIPTION                    ENABLED
ee1211eb7f2d        rogaha/metrics-plugin:17.06.0-1.0.0-test               true
[root@ip-172-31-34-7 tmp]# docker plugin rm -f rogaha/metrics-plugin:17.06.0-1.0.0-test
docker/metrics-plugin:17.06.0-1.0.0-test
[root@ip-172-31-34-7 tmp]# systemctl stop docker
[root@ip-172-31-34-7 tmp]# systemctl start docker
[root@ip-172-31-34-7 tmp]# docker version
Client:
 Version:      17.06.0-dev
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   f22765b
 Built:        Mon Jun 26 20:58:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-dev
 API version:  1.31 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   f22765b
 Built:        Mon Jun 26 21:00:42 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

File: plugin/manager_linux.go [hunk 1]
```diff
@@ -169,6 +169,8 @@ func (pm *Manager) disable(p *v2.Plugin, c *controller) error {
 
 	c.restart = false
 	shutdownPlugin(p, c, pm.containerdClient)
+	pluginDir := filepath.Join(pm.config.Root, p.GetID())
+	mount.RecursiveUnmount(pluginDir)
```
Comment (thaJeztah) [inline plugin/manager_linux.go]: Should this also be done on `Shutdown()`?

Comment (cpuguy83) [inline plugin/manager_linux.go]: Actually I think this may be overkill since unmounts happen in `StateChanged` when we get the containerd event.

**Comment by thaJeztah** [comment]
Four builds failed, four different failures - that's a new record 😞 none seem to be related

experimental:

```
16:07:16 ________________________ ServiceTest.test_service_logs _________________________
16:07:16 /docker-py/tests/helpers.py:67: in wrapped
16:07:16     return f(self, *args, **kwargs)
16:07:16 /docker-py/tests/integration/api_service_test.py:109: in test_service_logs
16:07:16     assert self.get_service_container(name, include_stopped=True)
16:07:16 /docker-py/tests/integration/api_service_test.py:41: in get_service_container
16:07:16     all=include_stopped
16:07:16 /docker-py/docker/api/container.py:189: in containers
16:07:16     res = self._result(self._get(u, params=params), True)
16:07:16 /docker-py/docker/utils/decorators.py:46: in inner
16:07:16     return f(self, *args, **kwargs)
16:07:16 /docker-py/docker/api/client.py:183: in _get
16:07:16     return self.get(url, **self._set_request_timeout(kwargs))
16:07:16 /usr/lib/python2.7/dist-packages/requests/sessions.py:469: in get
16:07:16     return self.request('GET', url, **kwargs)
16:07:16 /usr/lib/python2.7/dist-packages/requests/sessions.py:457: in request
16:07:16     resp = self.send(prep, **send_kwargs)
16:07:16 /usr/lib/python2.7/dist-packages/requests/sessions.py:569: in send
16:07:16     r = adapter.send(request, **kwargs)
16:07:16 /usr/lib/python2.7/dist-packages/requests/adapters.py:407: in send
16:07:16     raise ConnectionError(err, request=request)
16:07:16 E   ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

Janky:

```
16:08:36 _____________ ServiceTest.test_create_service_with_unicode_secret ______________
16:08:36 /docker-py/tests/integration/api_service_test.py:454: in test_create_service_with_unicode_secret
16:08:36     container = self.get_service_container(name)
16:08:36 /docker-py/tests/integration/api_service_test.py:41: in get_service_container
16:08:36     all=include_stopped
16:08:36 /docker-py/docker/api/container.py:189: in containers
16:08:36     res = self._result(self._get(u, params=params), True)
16:08:36 /docker-py/docker/utils/decorators.py:46: in inner
16:08:36     return f(self, *args, **kwargs)
16:08:36 /docker-py/docker/api/client.py:183: in _get
16:08:36     return self.get(url, **self._set_request_timeout(kwargs))
16:08:36 /usr/lib/python2.7/dist-packages/requests/sessions.py:469: in get
16:08:36     return self.request('GET', url, **kwargs)
16:08:36 /usr/lib/python2.7/dist-packages/requests/sessions.py:457: in request
16:08:36     resp = self.send(prep, **send_kwargs)
16:08:36 /usr/lib/python2.7/dist-packages/requests/sessions.py:569: in send
16:08:36     r = adapter.send(request, **kwargs)
16:08:36 /usr/lib/python2.7/dist-packages/requests/adapters.py:407: in send
16:08:36     raise ConnectionError(err, request=request)
16:08:36 E   ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```


PowerPC

```
14:29:05 ----------------------------------------------------------------------
14:29:05 FAIL: docker_cli_start_test.go:189: DockerSuite.TestStartReturnCorrectExitCode
14:29:05 
14:29:05 docker_cli_start_test.go:194:
14:29:05     c.Assert(err, checker.NotNil)
14:29:05 ... value = nil
14:29:05 
14:29:07 
```

WindowsRS1 (definitely not related);

```
14:02:42 write \\?\d:\CI\CI-c92599559\docker-import-817221653\layer0.tar: There is not enough space on the disk.
14:02:42 
14:02:42 
14:02:42 ERROR: Failed 'ERROR: Failed to load c:\baseimages\windowsservercore.tar into daemon under test' at 06/27/2017 14:02:42
14:02:42 
```

**Comment by thaJeztah** [comment]
hitting https://github.com/moby/moby/issues/33863 😞 - restarting

File: plugin/manager.go [hunk 2]
```diff
@@ -173,9 +173,22 @@ func (pm *Manager) reload() error { // todo: restore
...
+					logrus.WithError(err).WithField("id", filepath.Base(v.Name())).Error("Error loading plugin, skipping.")
+				}
+				continue
 			}
 			plugins[p.GetID()] = p
+		} else {
+			if validFullID.MatchString(strings.TrimSuffix(v.Name(), "-removing")) {
+				// There was likely some error while removing this plugin, let's try to remove again here
+				if err := system.EnsureRemoveAll(v.Name()); err != nil {
+					logrus.WithError(err).WithField("id", filepath.Base(v.Name())).Warn("error while attempting to clean up previously removed plugin")
```
Comment (thaJeztah) [inline plugin/manager.go]: Minor nit; error message starts with lowercase here, but the other errors added start with a capital

Comment (thaJeztah) [inline plugin/manager.go]: Looks like the other messages are all lowercase, so I suggest changing the ones above to be lowercase as well

File: plugin/manager.go [hunk 3]
```diff
@@ -173,9 +173,22 @@ func (pm *Manager) reload() error { // todo: restore
 		if validFullID.MatchString(v.Name()) {
 			p, err := pm.loadPlugin(v.Name())
 			if err != nil {
-				return err
+				if os.IsNotExist(errors.Cause(err)) {
+					// Likely some error while removing on an older version of docker
+					logrus.WithError(err).WithField("id", filepath.Base(v.Name())).Warn("Missing plugin config, skipping. This may be caused due to a failed remove and requires manual cleanup.")
+				} else {
+					logrus.WithError(err).WithField("id", filepath.Base(v.Name())).Error("Error loading plugin, skipping.")
```
Comment (thaJeztah) [inline plugin/manager.go]: Question: previously, we would _fail_ on the first plugin that failed to be reloaded. Now, we change the behavior, and accept that "some" plugins (which could be: "all of them") fail to load, and only _log_ it as an error.

If _all_ plugins fail to load, should we return it as an error? Should we collect the errors, and return an error at the end of this function? (i.e.; https://github.com/moby/moby/blob/4ec9766a27ffb964cec6b8b2745725965b2644aa/plugin/manager.go#L117-L119 now only marks the manager as "failed" if the plugin-root could not be read, but "succeeds" in all other cases

File: plugin/manager.go [hunk 4]
```diff
@@ -173,9 +173,22 @@ func (pm *Manager) reload() error { // todo: restore
...
+				}
+				continue
 			}
 			plugins[p.GetID()] = p
+		} else {
```
Comment (thaJeztah) [inline plugin/manager.go]: Perhaps we should refactor this loop a bit; there's a lot of nested conditions now. Perhaps do a `continue` in each `if` branch to reduce nesting with one level at least

File: plugin/manager.go [hunk 5]
```diff
@@ -173,9 +173,22 @@ func (pm *Manager) reload() error { // todo: restore
 		if validFullID.MatchString(v.Name()) {
 			p, err := pm.loadPlugin(v.Name())
 			if err != nil {
-				return err
+				if os.IsNotExist(errors.Cause(err)) {
```
Comment (thaJeztah) [inline plugin/manager.go]: perhaps

```go
if os.IsNotExist(errors.Cause(err)) {
	// Likely some error while removing on an older version of docker
	logrus.WithError(err).WithField("id", filepath.Base(v.Name())).Warn("Missing plugin config, skipping. This may be caused due to a failed remove and requires manual cleanup.")
	continue
}
logrus.WithError(err).WithField("id", filepath.Base(v.Name())).Error("Error loading plugin, skipping.")
```

**Review by thaJeztah — CHANGES_REQUESTED** [review]
some minor nits, and a question about the change of behavior

File: plugin/manager.go (hunk 3 above)
Comment (cpuguy83) [inline plugin/manager.go]: What's the difference between 1 plugin failing vs all plugins failing if there's only 1 plugin loaded?

The systems that require failed plugins will error out anyway. I don't think it makes sense to fail the daemon because a plugin couldn't load.

File: plugin/manager.go (hunk 4 above)
Comment (cpuguy83) [inline plugin/manager.go]: Ok, it's a little bit better, but much more and we'll be doing some nasty contortions, I think.

**Comment by cpuguy83** [comment]
Ugh, some strange new issues... I've not seen these before.

**Comment by rogaha** [comment]
@cpuguy83 related to the `PR` changes?

**Comment by cpuguy83** [comment]
No.

**Comment by rogaha** [comment]
we need to fix these unreliable tests.

**Comment by rogaha** [comment]
@thaJeztah all tests are passing now! :)

**Review by thaJeztah — APPROVED** [review]
LGTM

File: plugin/backend_linux.go [hunk 6]
```diff
@@ -624,14 +624,20 @@ func (pm *Manager) Remove(name string, config *types.PluginRmConfig) error {
 	}()
 
 	id := p.GetID()
-	pm.config.Store.Remove(p)
 	pluginDir := filepath.Join(pm.config.Root, id)
-	if err := recursiveUnmount(pluginDir); err != nil {
-		logrus.WithField("dir", pluginDir).WithField("id", id).Warn(err)
+
+	if err := mount.RecursiveUnmount(pluginDir); err != nil {
+		return errors.Wrap(err, "error unmounting plugin data")
```
Comment (tiborvass) [inline plugin/backend_linux.go]: Does returning here prevent starting the daemon?

File: plugin/manager.go [hunk 7]
```diff
@@ -173,9 +186,17 @@ func (pm *Manager) reload() error { // todo: restore
 		if validFullID.MatchString(v.Name()) {
 			p, err := pm.loadPlugin(v.Name())
 			if err != nil {
-				return err
+				handleLoadError(err, v.Name())
```
Comment (tiborvass) [inline plugin/manager.go]: Disregard my previous comment, I got my answer :)

**Comment by tiborvass** [comment]
LGTM
