### PR TITLE
Skip TestPullVerified

### LINKED ISSUE #12467: CI failed
a lot of new PRs failed CI by

```
--- FAIL: TestPullVerified (3.84s)
	docker_cli_pull_test.go:71: pulling a verified image failed. expected: The image you are pulling has been verified
		got: latest: Pulling from hello-world
		511136ea3c5a: Already exists
		31cbccb51277: Already exists
		e45a5af57b00: Already exists
		e45a5af57b00: Already exists
		Digest: sha256:55642409e2c6e441d34db2383620461a9513c54e6b7ab029faf28365ea8c6643
		Status: Downloaded newer image for hello-world:latest
		, <nil>
```

### PR DESCRIPTION
**Pull request by icecrime**
Since 1.6.0 delivery and hub infrastructure operations, `TestPullVerified` is not systematically failing: skip the test until we figure out a more reliable way to implement it.

Closes: #12467

### CODE REVIEW

**Comment by HuKeping** [comment]
closes #12467

File: integration-cli/docker_cli_pull_test.go [hunk 1]
```diff
@@ -55,6 +55,8 @@ func TestPullImageWithAliases(t *testing.T) {
 
 // pulling library/hello-world should show verified message
 func TestPullVerified(t *testing.T) {
+	t.Skip("Skipping hub dependent test")
```
Comment (thaJeztah) [inline integration-cli/docker_cli_pull_test.go]: Does it need a FIXME / TODO (and a related issue `#`), so it's not forgotten to re-enable/rewrite it?

**Comment by duglin** [comment]
LGTM
