### PR TITLE
choose rpc code to determine status code

### LINKED ISSUE #31909: Secrets API: Name conflict returns 500, should be 409
**Description**

When I create a secret, then try to create a new secret with the same name, the HTTP error code I get back is wrong.

**Steps to reproduce the issue:**
1. Create a secret (either through the command line or the REST API).
```bash
$ echo "secrets" | docker secret create my-secret -
```
2. Attempt to create another secret with the same name (this time using the REST API, so you can see the HTTP status you get back.)
```bash
$ curl -i --unix-socket /var/run/docker.sock -X POST -H 'content-type: application/json' -d '{"Name": "my-secret", "Data": "c2VjcmV0cwo="}' http://localhost/secrets/create
```

**Describe the results you received:**
HTTP 500
```
HTTP/1.1 500 Internal Server Error
Api-Version: 1.26
Content-Length: 73
Content-Type: application/json
Date: Fri, 17 Mar 2017 03:04:56 GMT
Docker-Experimental: true
Server: Docker/17.03.0-ce (linux)

{"message":"rpc error: code = 6 desc = secret my-secret already exists"}
```

**Describe the results you expected:**
HTTP 409 conflict, [as stated in the swagger spec](https://github.com/docker/docker/blob/master/api/swagger.yaml#L7982).

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 20
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 34
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: 2n2g46cvu27nk0yuoowhe1t8b
 Is Manager: true
 ClusterID: 3j26e6low77hibavv55u87hvp
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.65.2
 Manager Addresses:
  192.168.65.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.12-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: 3NXV:6OUU:O7VQ:BPBV:XDC2:ZPMT:IRSG:VJ3I:SL2H:ZWC2:ECT6:7X4R
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 33
 Goroutines: 131
 System Time: 2017-03-17T03:11:47.838534917Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: xnat
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I have seen this on Docker for Mac and Ubuntu 14.04, the latter using docker versions [1.13.1](https://travis-ci.org/spotify/docker-client/jobs/211952225#L3753) and [17.03.0-ce](https://travis-ci.org/spotify/docker-client/jobs/211952226#L3762).

### PR DESCRIPTION
**Pull request by allencloud**
Signed-off-by: allencloud <allen.sun@daocloud.io>

Since docker daemon use gRPC to communicate with swarmkit, so when docker daemon accepts http request and transfers to swarmkit side, the at last, swarmkit will return a gRPC code to docker daemon. For the user's request, we definitely need to return a response with an HTTP status code. This PR hopes to determine the http status code from the gRPC code.

this fixes https://github.com/docker/docker/issues/31909

**- What I did**
1. choose rpc code to determine status code
2. make secret operation use the correct status code. currently I only change the secret side.
3. add two test cases for issue https://github.com/docker/docker/issues/31909
4. update  docker-py to the version 2.3.0 in Dockerfiles
 

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by vdemeester — COMMENTED** [review]
/cc @thaJeztah @stevvooe @aaronlehmann

File: daemon/cluster/utils.go [hunk 1]
```diff
@@ -61,3 +65,40 @@ func removingManagerCausesLossOfQuorum(reachable, unreachable int) bool {
...
+func newErrWithHTTPCodeFromGRPC(err error) error {
+	if err == nil {
+		return nil
+	}
+
+	switch grpc.Code(err) {
+	case codes.OK: // code 0
+		return nil
+	case codes.InvalidArgument: // code 3
+		return errors.NewBadRequestError(err)
```
Comment (cpuguy83) [inline daemon/cluster/utils.go]: I'd like to not propagate this usage.
At the very least we can catch grpc errors in the API package and produce the correct error code from there.

**Review by cpuguy83 — CHANGES_REQUESTED** [review]

File: daemon/cluster/utils.go [hunk 2]
```diff
@@ -61,3 +65,40 @@ func removingManagerCausesLossOfQuorum(reachable, unreachable int) bool {
 func isLastManager(reachable, unreachable int) bool {
 	return reachable == 1 && unreachable == 0
 }
+
+// newErrWithHTTPCodeFromGRPC converts an error from gRPC into an error with HTTP status code
+func newErrWithHTTPCodeFromGRPC(err error) error {
```
Comment (stevvooe) [inline daemon/cluster/utils.go]: This is a mouthful.

`newHTTPErrorFromGRPC`

File: daemon/cluster/utils.go [hunk 3]
```diff
@@ -61,3 +65,40 @@ func removingManagerCausesLossOfQuorum(reachable, unreachable int) bool {
...
+		return nil
+	}
+
+	switch grpc.Code(err) {
+	case codes.OK: // code 0
+		return nil
+	case codes.InvalidArgument: // code 3
+		return errors.NewBadRequestError(err)
+	case codes.DeadlineExceeded: // code 4
+		return errors.NewErrorWithStatusCode(err, http.StatusRequestTimeout)
```
Comment (stevvooe) [inline daemon/cluster/utils.go]: This is incorrect. 408 is only used when the client doesn't send a complete request.

File: daemon/cluster/utils.go [hunk 4]
```diff
@@ -61,3 +65,40 @@ func removingManagerCausesLossOfQuorum(reachable, unreachable int) bool {
...
+	case codes.NotFound: // code 5
+		return errors.NewRequestNotFoundError(err)
+	case codes.AlreadyExists: // code 6
+		return errors.NewRequestConflictError(err)
```
Comment (stevvooe) [inline daemon/cluster/utils.go]: Conflict is a specific http error. This should be a 400 or some other error. There is already an open issue about the incorrect usage of 409. @justincormack

File: daemon/cluster/utils.go [hunk 5]
```diff
@@ -61,3 +65,40 @@ func removingManagerCausesLossOfQuorum(reachable, unreachable int) bool {
...
+	case codes.PermissionDenied: // code 7
+		return errors.NewErrorWithStatusCode(err, http.StatusNotImplemented)
+	case codes.Unauthenticated: // code 16
+		return errors.NewErrorWithStatusCode(err, http.StatusUnauthorized)
+	case codes.FailedPrecondition: // code 9
+		return errors.NewErrorWithStatusCode(err, http.StatusPreconditionFailed)
```
Comment (stevvooe) [inline daemon/cluster/utils.go]: This is a specific http error that doesn't map to the same thing as the GRPC error code.

File: daemon/cluster/utils.go (hunk 3 above)
Comment (stevvooe) [inline daemon/cluster/utils.go]: A 504 would work here.

File: daemon/cluster/utils.go (hunk 1 above)
Comment (allencloud) [inline daemon/cluster/utils.go]: Thanks for your feedback. Like you mentioned, I tried to move that part into api/server/httputils/errors.go. PTAL
@cpuguy83

File: integration-cli/docker_api_swarm_secret_test.go [hunk 6]
```diff
@@ -55,6 +62,13 @@ func (s *DockerSwarmSuite) TestAPISwarmSecretsDelete(c *check.C) {
 	status, out, err := d.SockRequest("GET", "/secrets/"+id, nil)
 	c.Assert(err, checker.IsNil)
 	c.Assert(status, checker.Equals, http.StatusNotFound, check.Commentf("secret delete: %s", string(out)))
+
+	// delete non-existing secret, daemon should return a status code of 404
+	id = "non-exsiting"
```
Comment (thaJeztah) [inline integration-cli/docker_api_swarm_secret_test.go]: typo s/non-exsiting/non-existing/ :joy:

**Comment by thaJeztah** [comment]
Looks like some tests need updating

File: api/server/httputils/errors.go [hunk 7]
```diff
@@ -72,6 +73,12 @@ func GetHTTPErrorStatusCode(err error) int {
 				break
 			}
 		}
+
+		// if the error has a type of grpc.rpcError, the error message should
+		// contain a sub string of "rpc error: code = "
+		if strings.Contains(errStr, "rpc error: code = ") {
```
Comment (cpuguy83) [inline api/server/httputils/errors.go]: Can we move this up to top of the default case and instead pass the error directly rather than checking the error string?

Then we can gate the horrid string checking pattern currently above this with something like:
```go
if statusCode == http.StatusInternalServerError {
    // horrible string parser
}
```

File: api/server/httputils/errors.go [hunk 8]
```diff
@@ -102,3 +109,39 @@ func MakeErrorHandler(err error) http.HandlerFunc {
...
+	case codes.InvalidArgument: // code 3
+		return http.StatusBadRequest
+	case codes.DeadlineExceeded: // code 4
+		return http.StatusGatewayTimeout
+	case codes.NotFound: // code 5
+		return http.StatusNotFound
+	case codes.AlreadyExists: // code 6
+		return http.StatusConflict
+	case codes.PermissionDenied: // code 7
+		return http.StatusNotImplemented
```
Comment (cpuguy83) [inline api/server/httputils/errors.go]: Why not implemented? Wouldn't this be `StatusForbidden`?

File: api/server/httputils/errors.go [hunk 9]
```diff
@@ -102,3 +109,39 @@ func MakeErrorHandler(err error) http.HandlerFunc {
...
+
+// statusCodeFromGRPCError returns status code according to gRPC error
+func statusCodeFromGRPCError(err error) int {
+	switch grpc.Code(err) {
+	case codes.OK: // code 0
+		return http.StatusOK
+	case codes.InvalidArgument: // code 3
+		return http.StatusBadRequest
+	case codes.DeadlineExceeded: // code 4
+		return http.StatusGatewayTimeout
```
Comment (cpuguy83) [inline api/server/httputils/errors.go]: This does not seem like the correct code.
This is used when the server is acting as a proxy. In this case something just went really wrong. I think this would just be a 500.

File: api/server/httputils/errors.go [hunk 10]
```diff
@@ -102,3 +109,39 @@ func MakeErrorHandler(err error) http.HandlerFunc {
...
+		return http.StatusNotImplemented
+	case codes.Internal: // code 13
+		return http.StatusInternalServerError
+	case codes.Unavailable: // code 14
+		return http.StatusServiceUnavailable
+	default:
+		// codes.Canceled(1)
+		// codes.Unknown(2)
+		// codes.ResourceExhausted(8)
+		// codes.FailedPrecondition(9)
```
Comment (cpuguy83) [inline api/server/httputils/errors.go]: This should be conflict, I think

File: api/server/httputils/errors.go (hunk 9 above)
Comment (cpuguy83) [inline api/server/httputils/errors.go]: While the engine may technically be acting as a proxy to containerd/swarm, I don't think this is something that should propagate up to the user.

File: api/server/httputils/errors.go [hunk 11]
```diff
@@ -102,3 +109,39 @@ func MakeErrorHandler(err error) http.HandlerFunc {
...
+	case codes.NotFound: // code 5
+		return http.StatusNotFound
+	case codes.AlreadyExists: // code 6
+		return http.StatusConflict
+	case codes.PermissionDenied: // code 7
+		return http.StatusNotImplemented
+	case codes.Unauthenticated: // code 16
+		return http.StatusUnauthorized
+	case codes.OutOfRange: // code 11
+		return http.StatusRequestedRangeNotSatisfiable
```
Comment (cpuguy83) [inline api/server/httputils/errors.go]: We probably shouldn't make up new status code usages here. The description of this status does not seem like anything we'd ever require.

File: api/server/httputils/errors.go [hunk 12]
```diff
@@ -102,3 +109,39 @@ func MakeErrorHandler(err error) http.HandlerFunc {
...
+	case codes.Unimplemented: // code 12
+		return http.StatusNotImplemented
+	case codes.Internal: // code 13
+		return http.StatusInternalServerError
+	case codes.Unavailable: // code 14
+		return http.StatusServiceUnavailable
```
Comment (cpuguy83) [inline api/server/httputils/errors.go]: Is swarm or containerd returning this ever? If so, is the HTTP code documented in the API?

File: api/server/httputils/errors.go [hunk 13]
```diff
@@ -102,3 +109,39 @@ func MakeErrorHandler(err error) http.HandlerFunc {
...
+		return http.StatusConflict
+	case codes.PermissionDenied: // code 7
+		return http.StatusNotImplemented
+	case codes.Unauthenticated: // code 16
+		return http.StatusUnauthorized
+	case codes.OutOfRange: // code 11
+		return http.StatusRequestedRangeNotSatisfiable
+	case codes.Unimplemented: // code 12
+		return http.StatusNotImplemented
+	case codes.Internal: // code 13
```
Comment (cpuguy83) [inline api/server/httputils/errors.go]: Can move this to the default case

File: api/server/httputils/errors.go [hunk 14]
```diff
@@ -102,3 +109,39 @@ func MakeErrorHandler(err error) http.HandlerFunc {
 		}
 	}
 }
+
+// statusCodeFromGRPCError returns status code according to gRPC error
+func statusCodeFromGRPCError(err error) int {
+	switch grpc.Code(err) {
+	case codes.OK: // code 0
```
Comment (cpuguy83) [inline api/server/httputils/errors.go]: I don't think this would ever happen?

**Review by cpuguy83 — CHANGES_REQUESTED** [review]
Thanks for moving this, seems like a better place to handle it, and in line with the changes requested in #32144

File: api/server/httputils/errors.go (hunk 9 above)
Comment (stevvooe) [inline api/server/httputils/errors.go]: What do you propose instead?

File: api/server/httputils/errors.go (hunk 11 above)
Comment (stevvooe) [inline api/server/httputils/errors.go]: `OutOfRange` should just be mapped to `400 Bad Request`.

File: api/server/httputils/errors.go (hunk 10 above)
Comment (stevvooe) [inline api/server/httputils/errors.go]: Not 400?

File: api/server/httputils/errors.go (hunk 9 above)
Comment (cpuguy83) [inline api/server/httputils/errors.go]: 500

File: api/server/httputils/errors.go (hunk 10 above)
Comment (cpuguy83) [inline api/server/httputils/errors.go]: 400 works too, just not 500.

Comment (cpuguy83) [inline api/server/httputils/errors.go]: well, technically I think 400 is for the HTTP server and shouldn't be used by us, but we do :)

File: api/server/httputils/errors.go (hunk 9 above)
Comment (allencloud) [inline api/server/httputils/errors.go]: Yeah, in failed test:
```
11:17:28 docker_api_swarm_test.go:342:
11:17:28     c.Assert(status, checker.Equals, http.StatusInternalServerError, check.Commentf("deadline exceeded", string(out)))
11:17:28 ... obtained int = 504
11:17:28 ... expected int = 500
11:17:28 ... deadline exceeded%!(EXTRA string={"message":"rpc error: code = 4 desc = context deadline exceeded"}
11:17:28 )
11:17:28 
11:17:28 [d0f11ccd4b298] exiting daemon
```
Original code is 500

File: api/server/httputils/errors.go (hunk 7 above)
Comment (allencloud) [inline api/server/httputils/errors.go]: > Then we can gate the horrid string checking pattern currently above this with something like:

Sorry, actually I cannot follow this one.

Comment (cpuguy83) [inline api/server/httputils/errors.go]: Basically, move this above this stuff:
```
			{"not found", http.StatusNotFound},
			{"cannot find", http.StatusNotFound},
			{"no such", http.StatusNotFound},
			{"bad parameter", http.StatusBadRequest},
			{"no command", http.StatusBadRequest},
			{"conflict", http.StatusConflict},
			{"impossible", http.StatusNotAcceptable},
			{"wrong login/password", http.StatusUnauthorized},
			{"unauthorized", http.StatusUnauthorized},
			{"hasn't been activated", http.StatusForbidden},
			{"this node", http.StatusServiceUnavailable},
			{"needs to be unlocked", http.StatusServiceUnavailable},
			{"certificates have expired", http.StatusServiceUnavailable},
```

And only check that stuff if the parsed statusCode from the grpc check is 500.

**Comment by allencloud** [comment]
Yes, some tests need updating. @thaJeztah 
I think `POST /secrets/{id}/update` introduces a status code of 400, which is included in PR https://github.com/docker/docker/pull/32464

And `POST /nodes/{id}/update` adds a case whose status code is originally 500, now to be 400.

I think I still need to update docs/api/version-history.md, WDYT?

File: api/server/httputils/errors.go (hunk 14 above)
Comment (allencloud) [inline api/server/httputils/errors.go]: Yeah, updated. PTAL

**Comment by allencloud** [comment]
I am afraid such kind of change may influence docker-py, here is some evidence which docekr-py test failed:
```
10:32:09 =================================== FAILURES ===================================
10:32:09 _______________________ SwarmTest.test_remove_main_node ________________________
10:32:09 /docker-py/tests/integration/api_swarm_test.py:171: in test_remove_main_node
10:32:09     assert e.value.response.status_code == 500
10:32:09 E   AssertionError: assert 400 == 500
10:32:09 E    +  where 400 = <Response [400]>.status_code
10:32:09 E    +    where <Response [400]> = APIError(HTTPError('400 Client Error: Bad Request',),).response
10:32:09 E    +      where APIError(HTTPError('400 Client Error: Bad Request',),) = <ExceptionInfo APIError tblen=6>.value
10:32:09 ======== 1 failed, 205 passed, 31 skipped, 2 xfailed in 408.65 seconds =========
10:32:09 ---> Making bundle: .integration-daemon-stop (in bundles/17.06.0-dev/test-docker-py)
```
Any input for this, or what should I do for this? @shin-

**Comment by allencloud** [comment]
I think such PR will influence the original docker daemon's API status code, then incompatibility happens in docker-py, like:  https://github.com/docker/docker-py/blob/master/tests/integration/api_swarm_test.py#L171

If we think that the design of this PR is OK, then I am afraid we still need to update docker-py's integration test case.

So, do I have to submit a new PR in rep docker/docker-py to fix the status code first?

Then back to this PR?

Am I on the correct direction? @thaJeztah @shin- @LK4D4 @stevvooe @cpuguy83

**Comment by allencloud** [comment]
Any update with this one? I think client side suffers this issue for a long time. 🌔

**Comment by thaJeztah** [comment]
ping @stevvooe @cpuguy83 PTAL

**Comment by stevvooe** [comment]
LGTM on the mapping.

**Comment by thaJeztah** [comment]
@allencloud looks like this needs an update to the `docker-py` tests;

```
19:16:09 _______________________ SwarmTest.test_remove_main_node ________________________
19:16:09 /docker-py/tests/integration/api_swarm_test.py:171: in test_remove_main_node
19:16:09     assert e.value.response.status_code == 500
19:16:09 E   AssertionError: assert 400 == 500
19:16:09 E    +  where 400 = <Response [400]>.status_code
19:16:09 E    +    where <Response [400]> = APIError(HTTPError('400 Client Error: Bad Request',),).response
19:16:09 E    +      where APIError(HTTPError('400 Client Error: Bad Request',),) = <ExceptionInfo APIError tblen=6>.value
19:16:09 ======== 1 failed, 205 passed, 31 skipped, 2 xfailed in 265.19 seconds =========
19:16:09 ---> Making bundle: .integration-daemon-stop (in bundles/17.06.0-dev/test-docker-py)
```

**Comment by allencloud** [comment]
I think my pull request for docker-py has been merged in https://github.com/docker/docker-py/pull/1605.

While in the docker-py test in integration for moby/moby, it still throws the error：
```
_______________________ SwarmTest.test_remove_main_node ________________________
09:04:45 /docker-py/tests/integration/api_swarm_test.py:171: in test_remove_main_node
09:04:45     assert e.value.response.status_code == 500
09:04:45 E   AssertionError: assert 400 == 500
09:04:45 E    +  where 400 = <Response [400]>.status_code
09:04:45 E    +    where <Response [400]> = APIError(HTTPError('400 Client Error: Bad Request',),).response
09:04:45 E    +      where APIError(HTTPError('400 Client Error: Bad Request',),) = <ExceptionInfo APIError tblen=6>.value
```
It seem that the test does not use the latest docker-py. 

While I found that in [hack/make/test-docker-py](https://github.com/moby/moby/blob/master/hack/make/test-docker-py), it uses command like following:
```
git clone https://github.com/docker/docker-py.git "$dockerPy"
```
It will use the lasted version of docker-py/master, right?

I am stuck here. Anything helps. Thanks a lot.

ping @thaJeztah @shin- @stevvooe

**Comment by thaJeztah** [comment]
Let me restart the build, possibly it wasn't merged yet when it last ran

**Comment by alfred-landrum** [comment]
@allencloud - I'm also debugging a test failure in a PR of mine: I think you need to update the DOCKER_PY_COMMIT variable in moby/moby Dockerfile; see @thaJeztah 's comment here: https://github.com/moby/moby/pull/33005#issuecomment-299925366 .

**Comment by thaJeztah** [comment]
Oh, you're right, forgot about the `DOCKER_PY_COMMIT` variable :blush:

**Comment by thaJeztah** [comment]
Bumped `DOCKER_PY_COMMIT` to 0832898507d3ce65f449003e3f244c4750e41393 (matching version 2.3.0 https://github.com/docker/docker-py/releases/tag/2.3.0)

**Review by thaJeztah — APPROVED** [review]
LGTM (if green)

**Comment by allencloud** [comment]
Thanks for your feedback. @thaJeztah @alfred-landrum 
While I have updated DOCKER_PY_COMMIT in all dockerfiles to the commit ID of docker-py 2.3.0, but it seems no change in the test case for docker-py.

**Comment by thaJeztah** [comment]
@allencloud looks like only the check on line 171 was updated, but not the one on line 176, which is the one that is failing; https://github.com/docker/docker-py/blob/0832898507d3ce65f449003e3f244c4750e41393/tests/integration/api_swarm_test.py#L171-L176

```python
        assert e.value.response.status_code >= 400

        with pytest.raises(docker.errors.APIError) as e:
            self.client.remove_node(node_id, True)

        assert e.value.response.status_code == 500
```

**Comment by allencloud** [comment]
My gosh, It is indeed caused by my carelessness.
Thanks @thaJeztah for your careful review.  And I added another PR in docker/docker-py https://github.com/docker/docker-py/pull/1621 to fix this.

**Comment by thaJeztah** [comment]
https://github.com/docker/docker-py/pull/1621 was merged; can you try updating this PR?

**Comment by allencloud** [comment]
Thanks for your feedback, @thaJeztah
Actually this pr has been updated yesterday.

The status code test error in docker-py never happens. While another error in docker-py occurs:
```
04:31:10 =================================== FAILURES ===================================
04:31:10 ______________________ PruneImagesTest.test_prune_images _______________________
04:31:10 /docker-py/tests/integration/api_image_test.py:306: in test_prune_images
04:31:10     result = self.client.prune_images()
04:31:10 /docker-py/docker/utils/decorators.py:35: in wrapper
04:31:10     return f(self, *args, **kwargs)
04:31:10 /docker-py/docker/api/image.py:300: in prune_images
04:31:10     return self._result(self._post(url, params=params), True)
04:31:10 /docker-py/docker/utils/decorators.py:47: in inner
04:31:10     return f(self, *args, **kwargs)
04:31:10 /docker-py/docker/api/client.py:179: in _post
04:31:10     return self.post(url, **self._set_request_timeout(kwargs))
04:31:10 /usr/lib/python2.7/dist-packages/requests/sessions.py:500: in post
04:31:10     return self.request('POST', url, data=data, json=json, **kwargs)
04:31:10 /usr/lib/python2.7/dist-packages/requests/sessions.py:457: in request
04:31:10     resp = self.send(prep, **send_kwargs)
04:31:10 /usr/lib/python2.7/dist-packages/requests/sessions.py:569: in send
04:31:10     r = adapter.send(request, **kwargs)
04:31:10 /usr/lib/python2.7/dist-packages/requests/adapters.py:407: in send
04:31:10     raise ConnectionError(err, request=request)
04:31:10 E   ConnectionError: ('Connection aborted.', BadStatusLine("''",))
04:31:10 ========= 1 failed, 241 passed, 7 skipped, 3 xfailed in 377.00 seconds =========
```

I am still searching the error's root cause.

**Comment by alfred-landrum** [comment]
@allencloud - I have a PR that is also blocked on the test_prune_images failure, which seems to be unrelated to the content of my PR. I haven't been able to reproduce it locally, but will share anything I find.
https://github.com/moby/moby/pull/33005

**Comment by allencloud** [comment]
Thanks @alfred-landrum 
I think it is good for us to see all green. And Is there anything more I could do to meet your change request. @cpuguy83 

In addition, I think we still to add more status code change in version_history.md, right? @thaJeztah

**Comment by allencloud** [comment]
Any update? ☀️

File: api/server/httputils/errors.go [hunk 15]
```diff
@@ -48,7 +49,19 @@ func GetHTTPErrorStatusCode(err error) int {
 		// there are errors falling back into this logic.
 		// If we need to differentiate between different possible error types,
 		// we should create appropriate error types that implement the httpStatusError interface.
+
 		errStr := strings.ToLower(errMsg)
+		// if the error has a type of grpc.rpcError, the error message should
+		// contain a sub string of "rpc error: code = "
+		if strings.Contains(errStr, "rpc error: code = ") {
```
Comment (cpuguy83) [inline api/server/httputils/errors.go]: This string check is probably more expensive, and certainly more fragile, than just checking `statusCodeFromGRPCError` in all cases.

If we move this to the top of the `default` case, in many cases we won't have to mess around with this string handling.
so...

```go
default:
    statusCode = statusCodeFromGRPCError(err)
    if statusCode == http.StatusInternalServerError {
        // nasty string comparison stuff
    }
````

Comment (allencloud) [inline api/server/httputils/errors.go]: Thanks for your feedback. @cpuguy83   I think what you said is reasonable. Thanks a lot.
While I think CI fails according to accident. Can you re-trigger that? @thaJeztah

**Comment by allencloud** [comment]
Does the change I added seem OK for you, @cpuguy83 ?
And feel free to tell me if I could do anything else? ☀️

File: docs/api/version-history.md [hunk 16]
```diff
@@ -29,6 +29,10 @@ keywords: "API, Docker, rcli, REST, documentation"
  generate and rotate to a new CA certificate/key pair.
 * `POST /service/create` and `POST /services/(id or name)/update` now take the field `Platforms` as part of the service `Placement`, allowing to specify platforms supported by the service.
 * `POST /containers/(name)/wait` now accepts a `condition` query parameter to indicate which state change condition to wait for. Also, response headers are now returned immediately to acknowledge that the server has registered a wait callback for the client.
+* `DELETE /secrets/(name)` now returns status code 404 instead of 500 when the secret does not exist.
+* `POST /secrets/create` now returns status code 409 instead of 500 when creating an already existing secret.
+* `POST /secrets/(name)/update` now returns status code 400 instead of 500 when updating a secret's content which is not the labels.
+* `POST /nodes/(name)/update` now returns status code 400 instead of 500 when demoting last node fails.
```
Comment (thaJeztah) [inline docs/api/version-history.md]: Probably we need to update the swagger.yml as well?

**Comment by cpuguy83** [comment]
@allencloud perfect!

**Comment by LK4D4** [comment]
@cpuguy83 LGTY? feel free to merge if yes

**Comment by cpuguy83** [comment]
Just needs the changes requested by @thaJeztah

**Comment by allencloud** [comment]
I think there is no need to update swagger.yml, since in swagger.yml no change will be involved.
For example, 
`DELETE /secrets/(name)` already has code 404 in swagger.yml, but in old version of docker, like docker-17.05, it has no code of 404, but 404 is still in swagger.yml;
`POST /secrets/create` already has code 409;
`POST /secrets/(name)/update` already has two code 400 and 500, but one case changing from 500 to 400;
`POST /nodes/(name)/update` already has two code 400 and 500, but one case changing from 500 to 400;

So there will be no change for swagger.yml.
@thaJeztah @cpuguy83

File: docs/api/version-history.md (hunk 16 above)
Comment (allencloud) [inline docs/api/version-history.md]: I think there is no need to update swagger.yml.

**Comment by thaJeztah** [comment]
> So there will be no change for swagger.yml.

Even better, thanks for checking 👍

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
yes, LGTM as well 😅
