### PR TITLE
Don't dump request body when too large

### LINKED ISSUE #19177: Daemon memory leak in image load when called from go dockerclient
When using the samalba docker client, loading a large image can cause the daemon in 1.10 to become extremely large.  In my testing, using a 714M image (selenium/standalone-firefox:2.47.1 in my case, but any large image should do) and the following example program, 1.9 stays small (~50-60MB rss) but 1.10 grows to 1.8G

```go
package main

import (
	"fmt"
	"os"
	"github.com/samalba/dockerclient"
)

func main() {
	c, err := dockerclient.NewDockerClient("unix:///var/run/docker.sock", nil)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to connect: %s\n", err)
		os.Exit(1)
	}
	if err := c.LoadImage(os.Stdin); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to send image: %s\n", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "finished the load\n")
}
```

Loading the same image with the docker CLI doesn't cause the massive memory growth (it stays in the 50-60MB range rss).

### PR DESCRIPTION
**Pull request by cpuguy83**
Fixes an issue where a client can send a large body but specifiy
application/json as the content-type, and cause Docker to consume lots
of RAM while trying to buffer the body so it can be dumped to the debug
log.

Fixes #19177

### CODE REVIEW

File: api/server/middleware.go [hunk 1]
```diff
@@ -27,25 +27,36 @@ func debugRequestMiddleware(handler httputils.APIFunc) httputils.APIFunc {
...
-						}
-					}
-				}
+		if r.Method != "POST" {
+			return handler(ctx, w, r, vars)
+		}
+		if err := httputils.CheckForJSON(r); err != nil {
+			return handler(ctx, w, r, vars)
+		}
+		maxBodySize := 4097 // 4KB + 1 byte
```
Comment (tiborvass) [inline api/server/middleware.go]: why +1 ?

Comment (cpuguy83) [inline api/server/middleware.go]: Just so we can say it's 4KB max and not 4KB - 1

Comment (calavera) [inline api/server/middleware.go]: you can also inverse the order and do

```go
if r.ContentLength <= 4K {
   // dump
}

// normal execution
return handler(...
```

Comment (cpuguy83) [inline api/server/middleware.go]: @calavera We're look at more than just ContentLength since in particular the bug reported the request is already incorrect, but I figure look at ContentLength early and if it is indeed bigger skip it.

**Comment by cpuguy83** [comment]
Cleaned up a little bit, also added a fix for authz plugins.

**Comment by tiborvass** [comment]
LGTM thanks @cpuguy83 !

**Comment by thaJeztah** [comment]
Broken test? On userns https://jenkins.dockerproject.org/job/Docker-PRs-userns/4839/console;

```
22:25:09 
22:25:09 ----------------------------------------------------------------------
22:25:09 FAIL: docker_cli_events_unix_test.go:48: DockerSuite.TestEventsOOMDisableFalse
22:25:09 
22:25:09 docker_cli_events_unix_test.go:61:
22:25:09     c.Assert(err, checker.IsNil)
22:25:09 ... value *errors.errorString = &errors.errorString{s:"wrong exit code for OOM container: expected 137, got 125 (output: \"WARNING: Your kernel does not support swap limit capabilities, memory limited without swap.\\ndocker: Error response from daemon: Cannot start container 9103a66988dea3599080ab8bd2b6477303175e719702237fc5368b4c46a19615: [9] System error: write parent: broken pipe.\\n\")"} ("wrong exit code for OOM container: expected 137, got 125 (output: \"WARNING: Your kernel does not support swap limit capabilities, memory limited without swap.\\ndocker: Error response from daemon: Cannot start container 9103a66988dea3599080ab8bd2b6477303175e719702237fc5368b4c46a19615: [9] System error: write parent: broken pipe.\\n\")")
22:25:09 
```

**Comment by aaronlehmann** [comment]
LGTM

I wonder if it would be more graceful to log a truncated request than not logging large ones at all - just to make it clearer what's going on, and avoid discontinuous behavior near the 4k boundary. But this is probably fine, especially if the 4k boundary is the right place to draw the line between legitimate requests and broken ones.

**Comment by cpuguy83** [comment]
Really 4K seems really high for dumping to the log, but since seccomp profiles are passed in from the client, it could make those requests grow fairly large.

File: pkg/authorization/authz.go [hunk 2]
```diff
@@ -1,16 +1,19 @@
...
 	"io"
-	"io/ioutil"
 	"net/http"
 	"strings"
 
 	"github.com/Sirupsen/logrus"
+	"github.com/docker/docker/pkg/ioutils"
 )
 
+const maxBodySize = 1048576 // 1MB
```
Comment (cpuguy83) [inline pkg/authorization/authz.go]: Also note the 1MB I did here for authz plugins -- just guessing at these numbers, but this can safely be much higher than the log dump since, well I wouldn't want to dump 1MB to the log.
