### PR TITLE
Change 'docker run' exit codes to distinguish docker/contained errors

### LINKED ISSUE #6734: docker run exit code consisency
I found other issues that talked about this but I did not find one that addressed it exactly.  

The problem is differentiating between an exit code from 

docker run blowing up versus the command being run by docker run blowing up.

We could follow the chroot standard.
  Exit status:

     125 if 'chroot' itself fails
     126 if COMMAND is found but cannot be invoked
     127 if COMMAND cannot be found
     the exit status of COMMAND otherwise

### PR DESCRIPTION
**Pull request by sallyom**
close #6734

The purpose of this PR is for users to distinguish Docker errors from
contained command errors.
This PR modifies 'docker run' exit codes to follow the chroot standard
for exit codes.
Exit status:
125 if 'docker run' itself fails
126 if contained command cannot be invoked
127 if contained command cannot be found
the exit status otherwise

Signed-off-by: Sally O'Malley somalley@redhat.com

### CODE REVIEW

**Comment by sallyom** [comment]
I am an intern working with @rhatdan.

**Comment by rhatdan** [comment]
We are basing this off of the "defacto" chroot standard.  Bash has some rules around this also.

**Comment by LK4D4** [comment]
looks ok for me.
ping @docker/core-maintainers

**Comment by tiborvass** [comment]
@sallyom @LK4D4 Also see #13907 that just got merged

**Comment by sallyom** [comment]
Any word on this?

**Comment by rhatdan** [comment]
@crosbymichael @jfrazelle @tianon

**Comment by crosbymichael** [comment]
I think this is a good idea.  Do you think we would break anyone relying on the existing error codes or do you think they are just checking for a non-zero return?

**Comment by rhatdan** [comment]
I would doubt anyone would check on this, but if they were that would be a bug in their code.  Currently you can  not differentiate between docker errors and errors in apps in containers, so looking for exit code of 1 makes little sense.

**Comment by sallyom** [comment]
will this be considered before Docker 1.8?

**Comment by rhatdan** [comment]
@crosbymichael @jfrazelle @tianon @cpuguy83

**Comment by cpuguy83** [comment]
+1 makes sense. Moving to code review since @crosbymichael seemed to be ok with it as well.

File: api/client/run.go [hunk 1]
```diff
@@ -35,6 +38,25 @@ func (cid *cidFile) Write(id string) error {
 	return nil
 }
 
+// Exit code 125 signals docker failure
+// Exit code 126 signals contained cmd not executable
+// Exit code 127 for contained cmd not found
+func RunError(err error) error {
```
Comment (cpuguy83) [inline api/client/run.go]: Does this need to be exported?

**Comment by cpuguy83** [comment]
Instead of having CLI command functions call `RunError`, call it from https://github.com/docker/docker/blob/master/api/client/cli.go#L90 and the command functions can still just `return err`.

**Comment by duglin** [comment]
should at least some of these codes make it into the container's metadata so that we see them via an inspect() ?

File: api/client/run.go [hunk 2]
```diff
@@ -35,6 +38,25 @@ func (cid *cidFile) Write(id string) error {
...
+	var statusError StatusError
+	if strings.Contains(err.Error(), syscall.ENOENT.Error()) {
```
Comment (cpuguy83) [inline api/client/run.go]: I think a switch is better for this.

**Comment by rhatdan** [comment]
@cpuguy83 I had @sallyom simplify runError to only use three if statements.  Not sure why switch would improve this.

We only want runError to be called on Run and Exec Commands.  Wouldn't moving this runError to cli.go cause it to be called on other cli commands potentially causing additional errors? 

Also moving to cli.go, could cause error codes returned by the command executed within the container to get eaten.

**Comment by tiborvass** [comment]
@sallyom rebase please

**Comment by thaJeztah** [comment]
I see this was rebased

ping @cpuguy83 @duglin PTAL

**Comment by duglin** [comment]
@sallyom any comment on this https://github.com/docker/docker/pull/14012#issuecomment-122396476 ?

**Comment by sallyom** [comment]
@duglin rebased, PTAL thanks

**Comment by cpuguy83** [comment]
Tests are failing against Windows.

**Comment by LK4D4** [comment]
@sallyom Yup, indeed windows tests are failing. Maybe @jhowardmsft can help

**Comment by jhowardmsft** [comment]
I can't see anything obvious in here - maybe Windows golang doesn't allow exit codes that high for some reason? I can take a look in the morning - heading out of the office shortly.

**Comment by duglin** [comment]
@sallyom https://github.com/docker/docker/pull/14012#issuecomment-122396476

For example, State.ExitCode is -1 instead of 127.  Should it be 127?

**Comment by sallyom** [comment]
Thanks @jhowardmsft , I was going to ping you on irc for this!   I have been scouring the code to pinpoint the windows failure, too.  Looking forward to resolving this.

**Comment by jhowardmsft** [comment]
OK, the problem is the string comparison. With the following little test program:

package main

import (
    "fmt"
    "os/exec"
    "syscall"
)

func main () {
    fmt.Println(syscall.ENOENT.Error())
    fmt.Println(exec.ErrNotFound.Error())
}

Windows output
Y:\test>test
The system cannot find the file specified.
executable file not found in %PATH%

Linux output
Y:\test>type a.a
no such file or directory
executable file not found in $PATH

**Comment by sallyom** [comment]
Ok, @jhowardmsft thanks!  hopefully it will pass now.

**Comment by sallyom** [comment]
Made a change to compare to Windows error msgs, still failing.  I should have time to look closer this afternoon.

**Comment by duglin** [comment]
@sallyom I'd really appreciate a reply to https://github.com/docker/docker/pull/14012#issuecomment-129637212

**Comment by sallyom** [comment]
@duglin 
https://github.com/docker/docker/blob/master/daemon/execdriver/windows/run.go#L236  - changed to:
return execdriver.ExitStatus{ExitCode: 127}, err    
This should be 127, not -1. 
I had this change already but windows test failed if I remember correctly?  Trying again...

**Comment by duglin** [comment]
I probably wasn’t clear.  Unless I did something wrong, when I use your PR and try to start an exe that doesn’t exist in the container and then use “docker inspect” to ask for the exit code I see “-1” not “127”.  Should the new exit code values that you defined also be stored in the container’s ExitCode metadata?  It seems like it.

**Comment by sallyom** [comment]
@duglin Yes, i see that now, thanks for clarifying.  Yes it should definitely be 127.  I'll make the fix.  Thanks for the help.

**Comment by sallyom** [comment]
@duglin I made a fix so new exit code values get stored in the container's Exitcode metadata.  
126 for "permission denied" error, ex) docker run busybox /etc
127 for "executable file not found" or "no such file or directory"
  ex) docker run busybox foo, docker run busybox /bin/foo  
thanks again for the review.

**Comment by sallyom** [comment]
@duglin non-Windows tests are clear after implementing your fb on the ExitCode metadata.  
@jhowardmsft tried adding Windows specific msgs to comparison, Windows still fails, still looking into it.

**Comment by sallyom** [comment]
@duglin please confirm that ExitCode metadata is consistent now, thanks.
@jhowardmsft still looking at Windows failure, tried adjusting string comparison.  Looking closer today.

File: integration-cli/docker_cli_run_test.go [hunk 3]
```diff
@@ -2826,3 +2826,48 @@ func (s *DockerSuite) TestRunCreateContainerFailedCleanUp(c *check.C) {
...
 	c.Assert(containerID, check.Equals, "", check.Commentf("Expected not to have this container: %s!", containerID))
 }
+
+// TestRunNonExecutableCmd checks that 'docker run busybox foo' exits with error code 127'
+func (s *DockerSuite) TestRunNonExecutableCmd(c *check.C) {
+	runCmd := exec.Command(dockerBinary, "run", "busybox", "foo")
+	out, exit, err := runCommandWithOutput(runCmd)
+	if !(err != nil && exit == 127) {
+		c.Fatalf("Run non-executable command should have errored with exit code 127, but we got out: %s, exit: %d, err: %s", out, exit, err)
+	}
```
Comment (duglin) [inline integration-cli/docker_cli_run_test.go]: Can you please add a check of the "docker inspect" output to make sure that State.ExitCode is also 127?  Just to be sure.

File: integration-cli/docker_cli_run_test.go [hunk 4]
```diff
@@ -2826,3 +2826,48 @@ func (s *DockerSuite) TestRunCreateContainerFailedCleanUp(c *check.C) {
...
+}
+
+// TestRunNonExistingCmd checks that 'docker run busybox /bin/foo' exits with code 127'
+func (s *DockerSuite) TestRunNonExistingCmd(c *check.C) {
```
Comment (duglin) [inline integration-cli/docker_cli_run_test.go]: How is this test different from the previous one?  In both cases we appear to be trying to run an exe that doesn't exit.

File: integration-cli/docker_cli_run_test.go [hunk 5]
```diff
@@ -2826,3 +2826,48 @@ func (s *DockerSuite) TestRunCreateContainerFailedCleanUp(c *check.C) {
...
+	}
+}
+
+// TestCmdCannotBeInvoked checks that 'docker run busybox /etc' exits with 126 and contains 'permission denied'
+func (s *DockerSuite) TestCmdCannotBeInvoked(c *check.C) {
+	runCmd := exec.Command(dockerBinary, "run", "busybox", "/etc")
+	out, exit, err := runCommandWithOutput(runCmd)
+	if !(err != nil && exit == 126) {
+		c.Fatalf("Run cmd that cannot be invoked should have errored with code 126, but we got out: %s, exit: %d, err: %s", out, exit, err)
+	}
```
Comment (duglin) [inline integration-cli/docker_cli_run_test.go]: Please check State.ExitCode here too.

File: integration-cli/docker_cli_run_test.go [hunk 6]
```diff
@@ -2826,3 +2826,48 @@ func (s *DockerSuite) TestRunCreateContainerFailedCleanUp(c *check.C) {
...
+}
+
+// TestRunNonExistingImage checks that 'docker run foo' exits with error msg 125 and contains  'Unable to find image'
+func (s *DockerSuite) TestRunNonExistingImage(c *check.C) {
+	runCmd := exec.Command(dockerBinary, "run", "foo")
+	out, exit, err := runCommandWithOutput(runCmd)
+	if !(err != nil && exit == 125 && strings.Contains(out, "Unable to find image")) {
+		c.Fatalf("Run non-existing image should have errored with 'Unable to find image' code 125, but we got out: %s, exit: %d, err: %s", out, exit, err)
+	}
```
Comment (duglin) [inline integration-cli/docker_cli_run_test.go]: Check State.ExitCode.

Comment (duglin) [inline integration-cli/docker_cli_run_test.go]: nvm, no container to check.  doi. :-)

**Comment by duglin** [comment]
@sallyom yup - look like it works, thanks.  Just a few minor comments about the tests.

File: integration-cli/docker_cli_run_test.go (hunk 4 above)
Comment (sallyom) [inline integration-cli/docker_cli_run_test.go]: 'run busybox foo' exits with syscall.ENOENT "no such file or directory" and 'run busybox /bin/foo' exits with exec.ErrNotFound "executable file not found in $PATH" 
(both error msgs are in the string compare that sets the exit code to 127, hence the test for each)

**Comment by sallyom** [comment]
@LK4D4 @cpuguy83 
https://github.com/docker/docker/blob/master/integration-cli/utils.go#L31-#L40
This should be something other than 127, right?

**Comment by bfirsh** [comment]
Thanks for your patience here, @sallyom! Any chance you could rebase and address @duglin's comments?

**Comment by sallyom** [comment]
@bfirsh sorry for the delay, had a hard time getting the State.ExitCode tests to pass, strange errors in many tests similar to https://github.com/docker/docker/issues/15876 I believe.  Funny, my added tests were all passing but the rest of the suite blew up.  Finally passing (at least locally, tbd here).  Rebased, also.

**Comment by sallyom** [comment]
also, wondering if https://github.com/docker/docker/blob/master/integration-cli/utils.go#L36:#L37 should be changed to exit code 125 rather than 127 for 'docker run' failure?

**Comment by sallyom** [comment]
**As you can see from the windows build output, the State.ExitCode is set correctly.**
FAIL: docker_cli_run_test.go:2791: DockerSuite.TestRunNonExecutableCmd
docker_cli_run_test.go:2797:
    c.Fatalf("Run non-executable command should have errored with exit code 127, but we got exit: %d, State.ExitCode: %s", exit, stateExitCode)
... Error: Run non-executable command should have errored with exit code 127, but we got exit: 1, **State.ExitCode: 127**

@jhowardmsft  `docker inspect -f {{.State.ExitCode}} c.ID`in `daemon/execdriver/windows/exec.go` and in `daemon/execdriver/windows/run.go` to set exitCode == output from `docker inspect` should work?

**Comment by jhowardmsft** [comment]
Should do. Just tried 
- docker run --rm windowsservercore cmd in first window
- docker ps in second window
- exit 83 in first windows
- docker inspect -f {{.State.ExitCode}} ac15 in second windows (ac15 was the ID)

And got 83 back as a result.

**Comment by jhowardmsft** [comment]
Ah, but I don't think this will work with exit from a docker exec. Just docker run.

**Comment by sallyom** [comment]
@jhowardmsft can you run `docker run --name test busybox foo`, check the exit code (it's probably 1)? and then `docker inspect -f {{.State.ExitCode}} test` and check the exit code (should be 127) . Please, thank you!
If the exit code of the docker run is 127, that's great, it means I have to change my test.  If not, I'm still on the task of figuring out where it's set, exactly, and where to set to 127.  We

**Comment by sallyom** [comment]
@jhowardmsft please and thanks so much, can you run:
`docker run --name test` busybox foo` verify exits 1 (it will be great if it exits 127, then I'll rework the test).
`docker inspect -f {{.State.ExitCode}} test` verify it exits 127.
thanks again for your help.

**Comment by jhowardmsft** [comment]
Well can't do busybox, but tried docker run -it windowsservercore doesnotexist, and inspect gave 127 on your branch. Not sure where I should be checking the exit code of 1 from though?

**Comment by sallyom** [comment]
I'm looking for the exit code of the last command, like  `echo $?` in bash :)

**Comment by sallyom** [comment]
@jhowardmsft @LK4D4 @cpuguy83 
(not sure if my windows "fix" is acceptable, PTAL, thanks)

File: integration-cli/docker_utils.go [hunk 7]
```diff
@@ -679,6 +679,22 @@ func dockerCmdInDirWithTimeout(timeout time.Duration, path string, args ...strin
...
 }
 
+func findContainerExitCode(c *check.C, name string, vargs ...string) (string, int) {
+	args := append(vargs, "inspect", "--format='{{ .State.ExitCode }} {{ .State.Error }}'", name)
+	cmd := exec.Command(dockerBinary, args...)
+	out, _, err := runCommandWithOutput(cmd)
+	if err != nil {
+		c.Fatal(err, out)
+	}
+	// return 127 for Windows build testing
```
Comment (jhowardmsft) [inline integration-cli/docker_utils.go]: Can you explain why this is Windows specific?

Comment (sallyom) [inline integration-cli/docker_utils.go]: In Windows, in testing 'docker run busybox /bin/foo' or 'docker run busybox foo', container exits with a code of 1, but with a State.ExitCode of "127".  So if you do 'docker inspect' you'll see the ExitCode of "127" but checking the exit code of last cmd will give 1.  It appears to be quite tricky to get the container to exit with 127 when running in Windows, it exits with a 1, regardless of any changes I've made to the code.  So instead, in testing, I'm ensuring that the container exited with the State.Exit.Code of "127" and if   the exit code != 127 (this ONLY happens during Windows build) then just manually set the code to 127 for the test IF the proper error msg is in State.Error.  The test passes if a) State.ExitCode is "127"  and proper 127 error msg was found in State.Error (Windows) or b) State.ExitCode is "127" and exit code is 127. Implementing the changes in this PR will give users the benefit of more information about why the container exited with a non-zero code.

**Comment by sallyom** [comment]
@LK4D4 @cpuguy83  thoughts on the Windows integration testing solution (please see my response above,  thanks :)

File: integration-cli/docker_utils.go (hunk 7 above)
Comment (jhowardmsft) [inline integration-cli/docker_utils.go]: Just to be clear - this is running from a Windows CLI against a Linux daemon when you say "In Windows...." and later "when running in Windows".

If so, the exit code is set by the daemon, so there shouldn't be a reason you have to do client-specific processing.

Comment (sallyom) [inline integration-cli/docker_utils.go]: yes, understood. I see my wording is misleading, updating.  thanks.

Comment (jhowardmsft) [inline integration-cli/docker_utils.go]: I'm still really confused here. I did not see a difference between a Linux CLI and a Windows CLI pointing to a Linux daemon. On both I ran docker run busybox foo, and both came back with State.ExitCode=-1 when run on master.

Comment (sallyom) [inline integration-cli/docker_utils.go]: *  From master, I also get a State.ExitCode of -1.  However, I get output of **1** from `echo $?` 
*  From my branch, I get a State.ExitCode of 127 (Windows and Linux CLI) but with Windows CLI the  exit is still 1, while with Linux the exit is 127.  
*  What I really don't understand (yet) is why  with Windows CLI  exit code and State.ExitCode both are 126 in the case of `docker run busybox /etc' when the error is "permission denied" from contained cmd.

Comment (jhowardmsft) [inline integration-cli/docker_utils.go]: No idea.... But FWIW, on master I see that Windows is perhaps already doing what you're wanting. docker run busybox foo, pointing to a Linux box. State.ExitCode=-1 on both platforms. echo %ERRORLEVEL% on Windows gives 127. But yes, echo $? on Linux is 1. 

Repeating same on master but using your /etc example. From a both CLI, State.ExitCode=-1. Linux $?=1, Windows %ERRORLEVEL%=1.

**Comment by sallyom** [comment]
@cpuguy83  @LK4D4 @duglin @jhowardmsft @rhatdan 
Please take another look, up-to-date, all tests are passing now.  Thanks.

File: daemon/container.go [hunk 8]
```diff
@@ -262,9 +264,16 @@ func (container *Container) Start() (err error) {
 	defer func() {
 		if err != nil {
 			container.setError(err)
+			if strings.Contains(err.Error(), syscall.ENOENT.Error()) ||
```
Comment (jhowardmsft) [inline daemon/container.go]: Should this block not have the same checks as in runerror on the CLI side?

Comment (sallyom) [inline daemon/container.go]: Added comment https://github.com/docker/docker/pull/14012/files#diff-07773483549b2d3c003c53614e1e2ab2R45 to clarify.

**Comment by sallyom** [comment]
@cpuguy83 @LK4D4 @duglin @rhatdan up to date, tests passing, please take another look, thanks.

File: api/client/run.go [hunk 9]
```diff
@@ -36,6 +38,27 @@ func (cid *cidFile) Write(id string) error {
...
+	if strings.Contains(err.Error(), "system cannot find the file specified") ||
+		strings.Contains(err.Error(), "no such file or directory") ||
+		strings.Contains(err.Error(), "executable file not found") {
+		return Cli.StatusError{StatusCode: 127}
+	}
+	if strings.Contains(err.Error(), syscall.EACCES.Error()) {
+		return Cli.StatusError{StatusCode: 126}
+	}
+	if strings.Contains(err.Error(), "latest not found") {
+		return Cli.StatusError{StatusCode: 125}
```
Comment (runcom) [inline api/client/run.go]: why don't these `StatusError` (125,126,127) contain a `Status` field set to `err.Error` (like the generic 125)?

now if you hit an error from 125 (latest not found), 126 or 127 the output is:
```
root@224662c1534f:/go/src/github.com/docker/docker# docker run busybox /etc
exec: "/etc": permission denied
```
while before this patch (and with `Status` field populated) output is:
```
root@224662c1534f:/go/src/github.com/docker/docker# docker run busybox /etc
exec: "/etc": permission denied
Error response from daemon: Cannot start container 62f29bd2a514c57fd0708b6a7dddf62008b1fc73a1b4797eb497e34f39b20b19: [8] System error: exec: "/etc": permission denied
```
is this change intented?

**Comment by rhatdan** [comment]
Probably not intentional, but I like it from a usability point of view.

File: api/client/run.go [hunk 10]
```diff
@@ -36,6 +38,27 @@ func (cid *cidFile) Write(id string) error {
...
+	// Linux: "no such file or directory" and "executable file not found in $PATH"
+	if strings.Contains(err.Error(), "system cannot find the file specified") ||
+		strings.Contains(err.Error(), "no such file or directory") ||
+		strings.Contains(err.Error(), "executable file not found") {
+		return Cli.StatusError{StatusCode: 127}
+	}
+	if strings.Contains(err.Error(), syscall.EACCES.Error()) {
+		return Cli.StatusError{StatusCode: 126}
+	}
+	if strings.Contains(err.Error(), "latest not found") {
```
Comment (runcom) [inline api/client/run.go]:
```
# docker run busybox:notlatest true
Unable to find image 'busybox:notlatest' locally
Pulling repository docker.io/library/busybox
Tag notlatest not found in repository docker.io/library/busybox

# echo $?
1

# docker run cpuguy83/runcomtest          
Unable to find image 'cpuguy83/runcomtest:latest' locally
Pulling repository docker.io/cpuguy83/runcomtest

# echo $?
125
```
If I'm trying to pull an image by a not-latest tag the error is shown but the exit code is `1`
If I'm trying to pull an image looking for latest tag but it doesn't have it error isn't shown and exit code is `127`
instead of looking for `latest not found` should this look for `not found in repository` to be consistent for every tag? (not sure why you don't want to show the error if the tag isn't latest)

**Comment by runcom** [comment]
I'm wondering if the introduction of the new `errors` pkg would help in this instead of just checking strings content. So the third case (125) could be just a type check on some error type from docker.
ping @duglin

**Comment by cpuguy83** [comment]
@runcom My thoughts as well.

**Comment by sallyom** [comment]
@cpuguy83 @runcom I'm working on that right now, actually.  No need to make any changes in api/client/run.go....I'll ping you when I've got it cleaned up.  Thanks.

**Comment by sallyom** [comment]
ping @cpuguy83 @runcom Thanks for taking another look at this.

**Comment by thaJeztah** [comment]
@sallyom looks like this needs another rebase as well :cry:

**Comment by sallyom** [comment]
rebased :)

File: daemon/container.go [hunk 11]
```diff
@@ -257,7 +257,7 @@ func (container *Container) Start() (err error) {
 			container.setError(err)
 			// if no one else has set it, make sure we don't leave it at zero
 			if container.ExitCode == 0 {
-				container.ExitCode = 128
+				container.ExitCode = 125
```
Comment (runcom) [inline daemon/container.go]: I'd rather leave 128 here just to be sure we know this is the case and we can differentiate from the other codes

File: daemon/start.go [hunk 12]
```diff
@@ -45,7 +47,20 @@ func (daemon *Daemon) ContainerStart(name string, hostConfig *runconfig.HostConf
 	}
 
 	if err := container.Start(); err != nil {
-		return derr.ErrorCodeCantStart.WithArgs(name, utils.GetErrorMessage(err))
+		derrErr := derr.ErrorCodeCantStart.WithArgs(name, utils.GetErrorMessage(err))
```
Comment (runcom) [inline daemon/start.go]: I don't really like this whole logic here, isn't it better to hide all of this inside `container.Start()`?

File: pkg/mflag/flag.go [hunk 13]
```diff
@@ -1058,7 +1058,7 @@ func (fs *FlagSet) Parse(arguments []string) error {
 		case ContinueOnError:
 			return err
 		case ExitOnError:
-			os.Exit(2)
+			os.Exit(125)
```
Comment (runcom) [inline pkg/mflag/flag.go]: mmm this sounds weird here in pkg/mflag

File: api/client/run.go [hunk 14]
```diff
@@ -115,6 +134,10 @@ func (cli *DockerCli) CmdRun(args ...string) error {
 
 	createResponse, err := cli.createContainer(config, hostConfig, hostConfig.ContainerIDFile, *flName)
 	if err != nil {
+		if strings.Contains(err.Error(), "Error: image library") {
```
Comment (runcom) [inline api/client/run.go]: this is wrong:
```
root@6ec0bedaeade:/go/src/github.com/docker/docker# docker run runcom/busybox true
Unable to find image 'runcom/busybox:latest' locally
Pulling repository docker.io/runcom/busybox
Error: image runcom/busybox:latest not found

root@6ec0bedaeade:/go/src/github.com/docker/docker# echo $?
1
```

**Comment by runcom** [comment]
some other problems with latest tag:

```
root@6ec0bedaeade:/go/src/github.com/docker/docker# docker run busybox:notlatest true
Unable to find image 'busybox:notlatest' locally
Pulling repository docker.io/library/busybox
Tag notlatest not found in repository docker.io/library/busybox

# echo $?
1

root@6ec0bedaeade:/go/src/github.com/docker/docker# docker run cpuguy83/runcomtest
Unable to find image 'cpuguy83/runcomtest:latest' locally
Pulling repository docker.io/cpuguy83/runcomtest
Tag latest not found in repository docker.io/cpuguy83/runcomtest

root@6ec0bedaeade:/go/src/github.com/docker/docker# echo $?
1
```
- If I'm trying to pull an image by a not-latest tag, the error is 1 not 125
- If I'm trying to pull an image looking for latest tag but it doesn't have it, the error is 1 not 125

**Comment by runcom** [comment]
Did a quick review and there still seems to be inconsistencies, will continue tomorrow
ping @cpuguy83 @duglin

File: pkg/mflag/flag.go (hunk 13 above)
Comment (rhatdan) [inline pkg/mflag/flag.go]: Why?  125 means the command failed in a lot of situations (Or ECANCELLED in errno).  Exit 2 means either nothing (or file does not exist in ERRNO).

I think 125 is a more correct error.

File: daemon/start.go (hunk 12 above)
Comment (rhatdan) [inline daemon/start.go]: Yes probably.  @sallyom See about moving this into container.Start()

File: pkg/mflag/flag.go (hunk 13 above)
Comment (runcom) [inline pkg/mflag/flag.go]: fair

File: daemon/container.go (hunk 11 above)
Comment (rhatdan) [inline daemon/container.go]: Is exit code 128 ever defined to mean anything in  similar commands like chroot or bash?  Googling it shows a hole mismatch of definitions. I have no problem leaving it but we need to document what it means so the qe people could test for this exit code and describe what i

File: api/client/run.go [hunk 15]
```diff
@@ -6,9 +6,11 @@ import (
 	"net/url"
 	"os"
 	"runtime"
+	"strings"
 
 	"github.com/Sirupsen/logrus"
 	Cli "github.com/docker/docker/cli"
+	"github.com/docker/docker/errors"
```
Comment (duglin) [inline api/client/run.go]: Just for consistency, please alias this to "derr". since "errors" is used in other files for go's errors package.

File: api/client/run.go [hunk 16]
```diff
@@ -36,6 +38,23 @@ func (cid *cidFile) Write(id string) error {
...
+	if derr127 == strings.Trim(err.Error(), "Error response from daemon: ") {
+		statusError = Cli.StatusError{StatusCode: 127}
+	} else if derr126 == strings.Trim(err.Error(), "Error response from daemon: ") {
+		statusError = Cli.StatusError{StatusCode: 126}
+	} else {
+		statusError = Cli.StatusError{StatusCode: 127}
+	}
+	return statusError
+}
+
```
Comment (duglin) [inline api/client/run.go]: Not your fault, but I can't tell you how much this code makes me shutter.   strcmp (and even worse, substr) on error messages stinks.

File: integration-cli/docker_cli_exec_test.go [hunk 17]
```diff
@@ -618,8 +617,8 @@ func (s *DockerSuite) TestExecStartFails(c *check.C) {
 	name := "exec-15750"
 	dockerCmd(c, "run", "-d", "--name", name, "busybox", "top")
 	c.Assert(waitRun(name), check.IsNil)
-
 	out, _, err := dockerCmdWithError("exec", name, "no-such-cmd")
-	c.Assert(err, check.NotNil, check.Commentf(out))
-	c.Assert(out, checker.Contains, "executable file not found")
+	if !(err != nil || out == "" || strings.Contains(err.Error(), "Error running command in existing container")) {
+		c.Fatalf("exec with non-existent cmd should have errored out with no output")
```
Comment (duglin) [inline integration-cli/docker_cli_exec_test.go]: Doesn't this seem wrong to show no output at all? Not even an "exe not found" type of error msg.
Also, shouldn't we be checking the exit code to make sure its correct?

File: integration-cli/docker_cli_run_test.go [hunk 18]
```diff
@@ -3438,3 +3438,54 @@ func (s *DockerSuite) TestRunWrongCpusetMemsFlagValue(c *check.C) {
...
 	c.Assert(out, check.Equals, expected, check.Commentf("Expected output to contain %q, got %q", expected, out))
 }
+
+// TestRunNonExecutableCmd checks that 'docker run busybox foo' exits with error code 127'
+func (s *DockerSuite) TestRunNonExecutableCmd(c *check.C) {
+	name := "testNonExecutableCmd"
+	runCmd := exec.Command(dockerBinary, "run", "--name", name, "busybox", "foo")
+	_, exit, _ := runCommandWithOutput(runCmd)
+	stateExitCode := findContainerExitCode(c, name)
+	if !(exit == 127 && strings.Contains(stateExitCode, "127")) {
```
Comment (duglin) [inline integration-cli/docker_cli_run_test.go]: I like that you check both!!!

File: pkg/integration/utils.go [hunk 19]
```diff
@@ -27,6 +27,16 @@ func GetExitCode(err error) (int, error) {
 			return procExit.ExitStatus(), nil
 		}
 	}
+	// error if contained command not found/does not exist
```
Comment (duglin) [inline pkg/integration/utils.go]: Can you explain this code here? If we have to check the output error message to "calculate" the exit code, then isn't something wrong since I thought the point of this PR was to make sure our exit codes were set properly?

File: pkg/integration/utils.go [hunk 20]
```diff
@@ -36,9 +46,8 @@ func ProcessExitCode(err error) (exitCode int) {
 	if err != nil {
 		var exiterr error
 		if exitCode, exiterr = GetExitCode(err); exiterr != nil {
-			// TODO: Fix this so we check the error's text.
-			// we've failed to retrieve exit code, so we set it to 127
-			exitCode = 127
+			// we've failed to retrieve exit code, so we set it to 125
+			exitCode = 125
```
Comment (duglin) [inline pkg/integration/utils.go]: Might as well just make GetExitCode() return 125 in these cases instead of `exitCode, fmt.Errorf("failed to get....")` - then we can have it just return 'exitCode' w/o the error.  No one else calls GetExitCode() except right here anyway.

File: pkg/mflag/flag.go (hunk 13 above)
Comment (sallyom) [inline pkg/mflag/flag.go]: working on feedback now, I've fixed the 'image doesn't not exist' errors by adding a similar check in api/client/run.go for the already existing derr.ErrorCodeNoSuchImageHash and derr.ErrorCodeNoSuchImageTag errors that were created in daemon/create.go --should have seen this before :(   working on other feedback now....

File: integration-cli/docker_cli_run_test.go (hunk 18 above)
Comment (sallyom) [inline integration-cli/docker_cli_run_test.go]: :) thnx

**Comment by sallyom** [comment]
working on feedback now, I've fixed the 'image doesn't not exist' errors by adding a similar check in api/client/run.go for the already existing derr.ErrorCodeNoSuchImageHash and derr.ErrorCodeNoSuchImageTag errors that were created in daemon/create.go --should have seen this before :( working on other feedback now....

File: daemon/start.go (hunk 12 above)
Comment (sallyom) [inline daemon/start.go]: np, I was building on what was there already but I agree it should be in container.Start()

File: api/client/run.go (hunk 16 above)
Comment (sallyom) [inline api/client/run.go]: i agree...but i did my best to make it seem less string-comparey.

File: integration-cli/docker_cli_exec_test.go (hunk 17 above)
Comment (sallyom) [inline integration-cli/docker_cli_exec_test.go]: when i run these 2 cmds:
docker run -d  --name exec-15750 busybox top
docker exec exec-15750 no-such-cmd
this spits out:
exec: "no-such-cmd": executable file not found in $PATH
but with dockerCmdWithError("exec", name, "no-such-cmd"), it's the err that contains "executable file not found in $PATH"  and out is ""
exitCode not checked because the container "exec-15750" still running...so it's 255 from the contained process
I may be confused, I've been staring at this for a long time...

File: pkg/integration/utils.go (hunk 19 above)
Comment (sallyom) [inline pkg/integration/utils.go]: not ignoring this, just looking into it more to compare to derr.Errs...not very easy to test this package, actually.

Comment (sallyom) [inline pkg/integration/utils.go]: @duglin as I (now) understand it the pkg/integration is to set up/test the utilities used in integration-cli, so there's no need to add tests or change anything there.  The new exit codes are tested in int-cli.  Thnx for your patience :)

**Comment by sallyom** [comment]
@LK4D4 @cpuguy83 I've addressed all feedback, thanks for giving it another look.
@duglin, see my response about the pkg/integration (no changes necessary) 
thanks :)

File: api/client/run.go [hunk 21]
```diff
@@ -199,8 +224,9 @@ func (cli *DockerCli) CmdRun(args ...string) error {
 	}()
 
 	//start the container
-	if _, _, err = readBody(cli.call("POST", "/containers/"+createResponse.ID+"/start", nil, nil)); err != nil {
-		return err
+	if _, _, err := readBody(cli.call("POST", "/containers/"+createResponse.ID+"/start", nil, nil)); err != nil {
+		cmd.ReportError(err.Error(), true)
```
Comment (duglin) [inline api/client/run.go]: I'm thinking the 2nd param should be `false` here.
```
$ docker run -ti ubuntu /tmp
exec: "/tmp": permission denied
docker: Error response from daemon: Contained command could not be invoked..
See '/root/docker/bundles/1.9.0-dev/binary/docker run --help'.
```
I think it makes sense to show the short help message in cases where we think there might be a docker specific error on the cmd line (like a bad option), but in cases where we've made it all the way to the container.start() we're probably into the user (or cmd) space and so I'm not sure showing the help message helps.  Keeping it on the parsing error and create error, above, are ok though.

File: errors/daemon.go [hunk 22]
```diff
@@ -872,4 +863,31 @@ var (
 		Description:    "An attempt to create a volume using a driver but the volume already exists with a different driver",
 		HTTPStatusCode: http.StatusInternalServerError,
 	})
+
+	// ErrorCodeCantStart127 is generated when contained cmd can't start,
+	// contained command not found error, exit code 127
+	ErrorCodeCantStart127 = errcode.Register(errGroup, errcode.ErrorDescriptor{
+		Value:          "COMMANDNOTFOUND",
```
Comment (duglin) [inline errors/daemon.go]: The pattern we're following is that the "Value" matches the ErrorCode, but in all caps. So this would be CANTSTART127

**Comment by duglin** [comment]
overall looks good - just a couple of minor comments

**Comment by sallyom** [comment]
@duglin, addressed your comments, thanks again.

**Comment by duglin** [comment]
LGTM!

**Comment by sallyom** [comment]
ping @LK4D4 @cpuguy83, anything else?  Thanks :)

**Comment by bfirsh** [comment]
ping @jfrazelle @tiborvass look good?

**Comment by calavera** [comment]
LGTM.

I'm rerunning the build before merging it to make sure this change doesn't break anything after so many changes.

**Comment by sallyom** [comment]
@calavera anything else?

**Comment by thaJeztah** [comment]
Hm, does this need documentation changes somewhere? I'm not sure actually if we mention exit-codes somewhere in the docs

**Comment by thaJeztah** [comment]
I counted two LGTM's, moving to docs review (but I'm not actually sure we have something around this, so suggestions are welcome)

**Comment by icecrime** [comment]
It's a good feature, I believe it should be documented indeed!

**Comment by sallyom** [comment]
@thaJeztah @icecrime in man/docker-run.1.md and docs/reference/run.md?  I'm on it :)

File: docs/reference/run.md [hunk 23]
```diff
@@ -518,6 +518,38 @@ non-zero exit status more than 10 times in a row Docker will abort trying to
 restart the container. Providing a maximum restart limit is only valid for the
 **on-failure** policy.
 
+## Exit Status
+
+The exit code from `docker run` will give information about why the container
```
Comment (thaJeztah) [inline docs/reference/run.md]: small nit: s/will give/gives/

**Comment by thaJeztah** [comment]
> in man/docker-run.1.md and docs/reference/run.md? I'm on it :)

sgtm! I see you added to `reference/run.md`, not yet in the man page

looks like this needs to be squashed and rebased as well (don't shoot the messenger! :smile:)

**Comment by sallyom** [comment]
@thaJeztah done!

**Comment by calavera** [comment]
thanks @sallyom. Man LGTM too. @thaJeztah can you check it out and merge if it looks good to you?

**Comment by thaJeztah** [comment]
Oh cool, it's updated, thanks!!

LGTM \o/

**Comment by sallyom** [comment]
woohoo!

**Comment by cpuguy83** [comment]
/me waits for the world to burn with this one :)

This is a good change though, I like having distinct exit codes.

**Comment by runcom** [comment]
@sallyom thanks! and great job!
