### PR TITLE
Test & Fix build with rm/force-rm matrix

### LINKED ISSUE #35116: [17.10-rc1] Build containers not being removed after failing build
**Description**

A failing `docker build` now preserves all intermediary build containers, while previous versions removed them.

**Steps to reproduce the issue:**
1. Create failing `Dockerfile`:
```
FROM busybox:latest
LABEL com.docker.compose.test_image=true
LABEL com.docker.compose.test_failing_image=true
RUN exit 1

```
2. Run `docker build --no-cache . | grep "Running in" | cut -d' ' -f5 | xargs docker inspect | grep '"Id"'`
3. Note how all 3 containers have been preserved.

**Describe the results you received:**

Build containers remained

**Describe the results you expected:**

Build containers are removed
```
$ ~/engines/docker-1.10.2 build --no-cache . | grep "Running in" | cut -d' ' -f5 | xargs ~/engines/docker-1.10.2 inspect
Error: No such image or container: 1ce422fe7da2
```

**Additional information you deem important (e.g. issue happens only occasionally):**

This error also affects Compose (https://github.com/docker/compose/issues/5242), so it's not a CLI bug.

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      17.10.0-ce-rc1
 API version:  1.33
 Go version:   go1.8.3
 Git commit:   d866876
 Built:        Wed Oct  4 21:45:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.10.0-ce-rc1
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   d866876
 Built:        Wed Oct  4 21:44:33 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 17
 Running: 0
 Paused: 0
 Stopped: 17
Images: 372
Server Version: 17.10.0-ce-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 446
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-92-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.499GiB
Name: yuna
ID: YZQG:AKYJ:JQXJ:CEHT:62DP:PMWA:S43W:5X47:SSOE:UXGG:XHWS:555F
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

### PR DESCRIPTION
**Pull request by simonferquel**
fix #35116

**- What I did**

Added test cases for build related to rm/force-rm flags, and fixed a few related issues

**- How I did it**

Added a test with a case matrix in integration/build reproducing potential issues and fixed them in build code base

**- How to verify it**

run the tests :)

Note:
docker build `rm` and `force-rm` flags might be better documented:
It is unclear that on build failures, rm still remove successfull individual intermediate containers (only the failing one is kept).

### CODE REVIEW

File: integration/build/build_test.go [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+			rm:      true,
+			forceRm: true,
+		},
+	}
+
+	client := request.NewAPIClient(t)
+
+	for _, c := range cases {
+
+		existing, err := client.ContainerList(context.Background(), types.ContainerListOptions{All: true})
```
Comment (vdemeester) [inline integration/build/build_test.go]: nit: maybe reuse the `context` for all the calls ? 🤔

**Review by thaJeztah — COMMENTED** [review]
LGTM, but I'd like @tonistiigi to have a look as well 👍

File: builder/dockerfile/builder.go [hunk 2]
```diff
@@ -322,6 +325,10 @@ func (b *Builder) dispatchDockerfileWithCancellation(parseResult []instructions.
 			if err := dispatch(dispatchRequest, cmd); err != nil {
 				return nil, err
 			}
+			if b.options.Remove && !b.options.ForceRemove {
```
Comment (tonistiigi) [inline builder/dockerfile/builder.go]: There is another `ForceRemove` defer inside the `dispatch` function https://github.com/moby/moby/blob/d9cd40d58bef2f607d4a798c99eb98cf56aab112/builder/dockerfile/evaluator.go#L56 that overrides this condition. I think we should keep always removing after each dispatch to be consistent with old versions and better protect against crashes. This is how it works atm as well but this code/comment indicates the opposite.

**Review by tonistiigi — COMMENTED** [review]
@andrewhsu We should take this for next `v17.10` RC. lmk if you need cherry-pick prs.

cc @dnephin to check the test

File: builder/dockerfile/builder.go (hunk 2 above)
Comment (simonferquel) [reply builder/dockerfile/builder.go]: Good catch @tonistiigi. I'll put remove handling in the global dispatch function.

**Comment by simonferquel** [comment]
@tonistiigi I centralized intermediate container removal logic in a single defer block in the dispatch() function with proper comments.
I think it makes it easier to understand the effect of rm/force-rm flags. 
I'll make a PR in CLI that tries to make the `-rm` flag documentation more precise.

File: builder/dockerfile/evaluator.go [hunk 3]
```diff
@@ -52,10 +52,12 @@ func dispatch(d dispatchRequest, cmd instructions.Command) error {
...
 
-	if d.builder.options.ForceRemove {
-		defer d.builder.containerManager.RemoveAll(d.builder.Stdout)
-	}
-
+	defer func() {
+		if d.builder.options.ForceRemove || // unconditionally remove intermediate containers
+			(d.builder.options.Remove && err == nil) { // if no error while running command, remove intermediate containers
+			d.builder.containerManager.RemoveAll(d.builder.Stdout)
+		}
```
Comment (thaJeztah) [inline builder/dockerfile/evaluator.go]: Perhaps making these two separate conditions (small bit of duplication, but may be better to understand without having to add comments to explain)

```go
if d.builder.options.ForceRemove {
	d.builder.containerManager.RemoveAll(d.builder.Stdout)
	return
}
if d.builder.options.Remove && err == nil {
	d.builder.containerManager.RemoveAll(d.builder.Stdout)
	return
}
```

One thing I was wondering; it `--rm=false`, should `--force-remove` still remove containers? Can you check on an older version?

If that's the case, then it should likely look like:

```go
if !d.builder.options.Remove {
	return
}
if err == nil || d.builder.options.ForceRemove {
	d.builder.containerManager.RemoveAll(d.builder.Stdout)
}
```

**Review by thaJeztah — CHANGES_REQUESTED** [review]

File: builder/dockerfile/evaluator.go (hunk 3 above)
Comment (simonferquel) [reply builder/dockerfile/evaluator.go]: @thaJeztah on options deserialization, there is a reconcilation that forces `rm` to true if `force-rm` is true:
```
	if httputils.BoolValue(r, "forcerm") && versions.GreaterThanOrEqualTo(version, "1.12") {
		options.Remove = true
	} else if r.FormValue("rm") == "" && versions.GreaterThanOrEqualTo(version, "1.12") {
		options.Remove = true
	} else {
		options.Remove = httputils.BoolValue(r, "rm")
	}
```

**Comment by simonferquel** [comment]
@thaJeztah condition expression split :)

File: integration/build/build_test.go [hunk 4]
```diff
@@ -0,0 +1,101 @@
...
+			numberOfIntermediateContainers: 0,
+			rm:      true,
+			forceRm: true,
+		},
+	}
+
+	client := request.NewAPIClient(t)
+	ctx := context.Background()
+	for _, c := range cases {
+
```
Comment (dnephin) [inline integration/build/build_test.go]: You can use https://golang.org/pkg/testing/#T.Run so that all test cases run even if one of the `require` fail.

File: integration/build/build_test.go [hunk 5]
```diff
@@ -0,0 +1,101 @@
...
+	"io/ioutil"
+	"testing"
+
+	"github.com/stretchr/testify/require"
+
+	"github.com/docker/docker/api/types"
+	"github.com/docker/docker/integration/util/request"
+)
+
+func TestBuildFailuresAndIntermediateContainers(t *testing.T) {
```
Comment (dnephin) [inline integration/build/build_test.go]: Maybe `TestBuildWithRemoveAndForceRemove` or something like that? Intermediate containers seem like more of the test result than the test condition. And this tests both failures and non-failures, so failures doesn't seem relevant to the name.

File: integration/build/build_test.go [hunk 6]
```diff
@@ -0,0 +1,101 @@
...
+		require.NoError(t, tw.Close())
+		resp, err := client.ImageBuild(ctx, buff, types.ImageBuildOptions{Remove: c.rm, ForceRemove: c.forceRm, NoCache: true})
+		require.NoError(t, err)
+		ioutil.ReadAll(resp.Body)
+		resp.Body.Close()
+
+		new, err := client.ContainerList(ctx, types.ContainerListOptions{All: true})
+		require.NoError(t, err)
+		actualCountDiff := len(new) - len(existing)
+		require.Equal(t, c.numberOfIntermediateContainers, actualCountDiff, "Expected %v remaining intermediate containers, got %v. {rm: %v, force-rm: %v dockerfile:%v}", c.numberOfIntermediateContainers, actualCountDiff, c.rm, c.forceRm, c.dockerfile)
```
Comment (dnephin) [inline integration/build/build_test.go]: If you use `t.Run()` you can use this extra string as the test name so that any assert/require failure has this extra information associated with it, instead of just the last assert.Equal()

File: integration/build/build_test.go [hunk 7]
```diff
@@ -0,0 +1,101 @@
...
+		require.NoError(t, err)
+		require.NoError(t, tw.Close())
+		resp, err := client.ImageBuild(ctx, buff, types.ImageBuildOptions{Remove: c.rm, ForceRemove: c.forceRm, NoCache: true})
+		require.NoError(t, err)
+		ioutil.ReadAll(resp.Body)
+		resp.Body.Close()
+
+		new, err := client.ContainerList(ctx, types.ContainerListOptions{All: true})
+		require.NoError(t, err)
+		actualCountDiff := len(new) - len(existing)
```
Comment (dnephin) [inline integration/build/build_test.go]: This will make it impossible to run the test in parallel with any other test that creates containers.

Instead of counting the total number of containers I think it would be possible to parse the build output and grab the container ids. Then attempt to list or inspect the containers with those ids to see if they exist.

**Review by dnephin — COMMENTED** [review]
thanks, fix looks good, left some suggestions for the tests

**Comment by tonistiigi** [comment]
LGTM

File: integration/build/build_test.go [hunk 8]
```diff
@@ -0,0 +1,129 @@
...
+	"testing"
+
+	"github.com/docker/docker/pkg/jsonmessage"
+
+	"github.com/docker/docker/api/types/filters"
+
+	"github.com/stretchr/testify/require"
+
+	"github.com/docker/docker/api/types"
+	"github.com/docker/docker/integration/util/request"
```
Comment (thaJeztah) [inline integration/build/build_test.go]: Can you remove the blank lines between the `github.com...` dependencies, and make sure they're sorted correctly?

```go
import (
	"archive/tar"
	"bytes"
	"context"
	"encoding/json"
	"io"
	"strings"
	"testing"

	"github.com/docker/docker/api/types"
	"github.com/docker/docker/api/types/filters"
	"github.com/docker/docker/integration/util/request"
	"github.com/docker/docker/pkg/jsonmessage"
	"github.com/stretchr/testify/require"
)
```

**Review by thaJeztah — CHANGES_REQUESTED** [review]
one nit in the code; also can you check if some of the commits should be squashed?

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

File: integration/build/build_test.go [hunk 9]
```diff
@@ -0,0 +1,129 @@
...
+	t.Parallel()
+	cases := []struct {
+		name                           string
+		dockerfile                     string
+		numberOfIntermediateContainers int
+		rm                             bool
+		forceRm                        bool
+	}{
+		{
+			name: "successfull-false-false",
```
Comment (dnephin) [inline integration/build/build_test.go]: These names could be a lot more descriptive. The dashes can also be spaces, `testing.Run()` will take care of adding the dashes.  

* "successful build with no removal"
* "successful build with remove"
* "successful build with remove and force remove"
* "failed build with no removal"
...

File: integration/build/build_test.go [hunk 10]
```diff
@@ -0,0 +1,129 @@
...
+				if err == io.EOF {
+					break
+				}
+				require.NoError(t, err)
+				if ix := strings.Index(m.Stream, intermediateContainerPrefix); ix != -1 {
+					filter.Add("id", strings.TrimSpace(m.Stream[ix+len(intermediateContainerPrefix):]))
+				}
+			}
+
+			resp.Body.Close()
```
Comment (dnephin) [inline integration/build/build_test.go]: this cleanup will be missed if `require.NoError(t, err)` fails the test, could be deferred.

File: integration/build/build_test.go [hunk 11]
```diff
@@ -0,0 +1,129 @@
...
+				Name: "Dockerfile",
+				Size: int64(len(dockerfile)),
+			}))
+			_, err := tw.Write(dockerfile)
+			require.NoError(t, err)
+			require.NoError(t, tw.Close())
+			resp, err := client.ImageBuild(ctx, buff, types.ImageBuildOptions{Remove: c.rm, ForceRemove: c.forceRm, NoCache: true})
+			require.NoError(t, err)
+
+			const intermediateContainerPrefix = " ---> Running in "
```
Comment (dnephin) [inline integration/build/build_test.go]: parsing of ids from the response would be great in a separate function to keep the test more readable.

**Review by dnephin — APPROVED** [review]
minor nits on the test

LGTM

**Comment by simonferquel** [comment]
@dnephin, @thaJeztah, latest nits are fixed, everything squashed and rebased

**Review by dnephin — APPROVED** [review]
LGTM

**Comment by dnephin** [comment]
powerpc failures mostly look like flakes, but the busybox missing flag is weird. I'll try restarting it.
