### PR TITLE
LogFile follow without filenotify

### LINKED ISSUE #30046: Windows docker -f doesn't follow instantly
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Description**

Windows docker -f  doesn't follow instantly as expected. Most the times It just outputted the history logs and stuck there , seldom it outputted new logs every one minute.
This happens ONLY to Windows docker.

**Steps to reproduce the issue:**
1.
`docker run -d --name=log-tester microsoft/windowsservercore powershell while ($true) {$d=Get-Date; write-host 'Time is:' $d; Sleep 1}`
2.
`docker logs -f log-tester`

**Describe the results you received:**
Logs didn't get printed every second. Instead, only history logs were outputted but new logs either didn't printed (most testcases) or printed in a batch  every one minute (in very few testcases)

**Describe the results you expected:**
logs should be outputted in stream instantly. In this particular testcase, logs should get printed every second. 

**Output of `docker version`:**

```
C:\Users\Administrator>docker version
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.3
 Git commit:   f93c04d
 Built:        Sat Dec 17 15:16:54 2016
 OS/Arch:      windows/amd64

Server:
 Version:             1.14.0-dev
 API version:         1.26
 Minimum API version: 1.24
 Go version:          go1.7.3
 Git commit:          f93c04d
 Built:               Sat Dec 17 15:16:54 2016
 OS/Arch:             windows/amd64
 Experimental:        false
```

**Output of `docker info`:**

```
C:\Users\Administrator>docker info
Containers: 8
 Running: 3
 Paused: 0
 Stopped: 5
Images: 25
Server Version: 1.14.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.351.amd64fre.rs1_release_inmarket.161014-1755)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 3.999 GiB
Name: WIN2016-DOCKER-01
ID: MCVH:SYEM:X2IN:FRIH:CYGH:HGLB:PAKZ:XAME:2IE7:PNZF:XTTL:EDLM
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 192.168.180.200:5000
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMware Workstation 12.5.1 Virtual Machine

### LINKED ISSUE #37646: docker logs -f stops when json-file rotates log file
**Description**

When Docker json-file log driver rotates the log file, applications streaming the log such as `docker logs -f` or logspout stop receiving new log events.

**Steps to reproduce the issue:**
1. Start container that produces logs: `docker run --rm -d alpine sh -c 'while true; do echo $(date); done'`
2. Start tailing logs: `docker logs -f <container-id>`
3. Observe log file size at `/var/lib/docker/containers/<container-id>/<container-id>-json.log`

**Describe the results you received:**

When the log file rotates, `docker logs -f` output stops.

**Describe the results you expected:**

I expect `docker logs -f` to continue outputting logs until terminated.

**Additional information you deem important (e.g. issue happens only occasionally):**

Seems to be a duplicate of https://github.com/moby/moby/issues/23913 which was supposed to have been fixed through https://github.com/moby/moby/pull/24514 in 1.13.

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.6
 Git commit:   9ee9f40
 Built:        Thu Apr 26 04:27:49 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.6
  Git commit:   9ee9f40
  Built:        Thu Apr 26 04:27:49 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
$ docker info
Containers: 24
 Running: 5
 Paused: 0
 Stopped: 19
Images: 47
Server Version: 18.03.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 3641oiewax7rd3re6mbt0uhto
 Is Manager: true
 ClusterID: 3dg2kejti78ucxky28skve8cv
 Managers: 3
 Nodes: 6
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 172.18.5.178
 Manager Addresses:
  172.18.5.136:2377
  172.18.5.178:2377
  172.18.5.248:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: v0.13.2 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
 selinux
Kernel Version: 4.14.59-coreos-r2
Operating System: Container Linux by CoreOS 1800.6.0 (Rhyolite)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.853GiB
Name: REDACTED
ID: EK5F:II7L:AE6M:JCUO:C4CT:TM5F:XL6Z:XL6P:FJ2M:2EBC:LC45:VJTJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 103
 Goroutines: 273
 System Time: 2018-08-15T12:35:17.758625842Z
 EventsListeners: 3
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://REDACTED/
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

CoreOS stable channel on EC2.

### LINKED ISSUE #39274: Docker json-file logging driver hangs when rotating files on Windows
**Description**

Docker json-file logging driver hangs when rotating files on Windows. Once a container gets in hung state, no more log entries are saved for it unless docker or the container is restarted.

PS> Get-EventLog -LogName Application -Source Docker shows the following error messages:

```
Failed to log msg "" for logger json-file: error removing oldest log file: remove C:\ProgramData\docker\containers\e9b7722458801aadcfdc6f37a7d44c077c36d3680a906a305dad878e9cf6a9ae\e9b7722458801aadcfdc6f37a7d44c077c36d3680a906a305dad878e9cf6a9ae-json.log.1: The process cannot access the file because it is being used by another process.
```

(REPEATED UNTIL MITIGATED) 
```
Failed to log msg "" for logger json-file: error closing file: close C:\ProgramData\docker\containers\e9b7722458801aadcfdc6f37a7d44c077c36d3680a906a305dad878e9cf6a9ae\e9b7722458801aadcfdc6f37a7d44c077c36d3680a906a305dad878e9cf6a9ae-json.log: file already closed.
```

The issue does not happen every time but happens quite frequently.

**Steps to reproduce the issue:**
0. Run a Windows 2019 OS VM with docker using named pipes.
1. Run a docker container on the VM which outputs some log entries. Set this container to use json-file logging driver with 1M file size and 2 file-limit.
2. Create another docker container which is has the docker named pipe mounted. Run periodic ContainerLogs API call for the container in step 1 in this container.
3. Let the setup run until Event log entries start showing the error messages described above. Once this state is reached, no more logs are captured in the json files.

**Describe the results you received:**
1. Container logs stop getting captured on log file rotation.

**Describe the results you expected:**
1. Container logs should not get stuck.

**Additional information you deem important (e.g. issue happens only occasionally):**
This issue does not occur every time. But it happens very frequently when multiple containers are running on multiple VMs.

**Output of `docker version`:**

```
> docker version
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        142dfcedca
 Built:             02/28/2019 06:33:17
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.8
  Git commit:       142dfcedca
  Built:            02/28/2019 06:31:15
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 18.09.3
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.316)
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 15GiB
Name: dc48a85165fcf24
ID: KCKO:GJP5:M7R3:IE45:2LVF:FCYR:MOBJ:DFS7:BBV6:L4XV:DRZY:ZA5M
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows 2019 VM on GCP
Mitigations = restart affected container, or restart docker service on Windows.

**docker inspect output on a container which got into this state**
```
> docker inspect e9b
[
    {
        "Id": "e9b7722458801aadcfdc6f37a7d44c077c36d3680a906a305dad878e9cf6a9ae",
        "Created": "REDACTED",
        "Path": "REDACTED",
        "Args": [
           "REDACTED"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 3648,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2019-05-28T00:52:02.4274538Z",
            "FinishedAt": "2019-05-28T00:52:00.7740957Z"
        },
        "Image": "sha256:b301392b301239e154b21e03c8b77c03abd14e8ab3459835036a411998b60fd8",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "LogPath": "C:\\ProgramData\\docker\\containers\\e9b7722458801aadcfdc6f37a7d44c077c36d3680a906a305dad878e9cf6a9ae\\e9b7722458801aadcfdc6f37a7d44c077c36d3680a906a305dad878e9cf6a9ae-json.log",
        "Name": "REDACTED",
        "RestartCount": 0,
        "Driver": "windowsfilter",
        "Platform": "windows",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "REDACTED"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {
                    "max-file": "2",
                    "max-size": "1m"
                }
            },
            "NetworkMode": "nat",
            "PortBindings": null,
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 0,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "process",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": null,
            "ReadonlyPaths": null
        },
        "GraphDriver": {
            "Data": {
                "dir": "C:\\ProgramData\\docker\\windowsfilter\\e9b7722458801aadcfdc6f37a7d44c077c36d3680a906a305dad878e9cf6a9ae"
            },
            "Name": "windowsfilter"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "REDACTED",
                "Destination": "REDACTED",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "REDACTED",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": [
                "REDACTED",
            ],
            "Image": "REDACTED",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [],
            "OnBuild": null,
            "Labels": {
                "agent.config": "REDACTED",
                "agent.managed": "true"
            },
            "StopSignal": "SIGTERM"
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "e9b7722458801aadcfdc6f37a7d44c077c36d3680a906a305dad878e9cf6a9ae",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "e9b7722458801aadcfdc6f37a7d44c077c36d3680a906a305dad878e9cf6a9ae",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "nat": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "93a8f0003991defdec723729ef537a49ecab734ede99e070a8dd1181ff79137e",
                    "EndpointID": "8d8509776404f0d0532d5afe3132c5a4a63e94e0b5fcb94751d53f24e29e1f9a",
                    "Gateway": "REDACTED",
                    "IPAddress": "REDACTED",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "00:15:5d:02:1c:ff",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

### PR DESCRIPTION
**Pull request by corhere**
- Fixes #30046
- fixes #37646
- fixes #39274

**- What I did**
I fixed issues with log reading on Windows and other platforms.

**- How I did it**
I added an extensive test suite for validating the behavior of `logger.LogReader` implementations. The tests caught bugs in both the `local` driver and the LogFile follow implementation, all of which I have fixed. In order to make the tests repeatable, I had to synchronize the opening of a log watcher so that it consistently [happens before](https://en.wikipedia.org/wiki/Happened-before) the next message is logged. This required some refactoring of log readers and `logger.LogWatcher` so that the logging drivers no longer needed to keep track of active LogWatchers in order to signal when the logging driver is closed.

I modified how LogFile rotates log files, eliminating the need to evict readers or retry renames. Unlike POSIX, there is no direct equivalent to `unlink(3)` on Windows. A file's name is not available for reuse until the file is deleted, and a file is not deleted until all handles to it are closed. (`DeleteFile` only marks a file for delete on close.) If any readers had the oldest log file open when LogFile went to rotate logs and delete that file, renaming the second-oldest log file would fail on Windows. [A file name can be reused immediately by renaming the existing file](https://docs.microsoft.com/en-us/windows/win32/fileio/closing-and-deleting-files#:~:text=The%20DeleteFile%20function%20can%20be%20used%20to%20delete%20a%20file%20on%20close.%20A%20file%20cannot%20be%20deleted%20until%20all%20handles%20to%20it%20are%20closed.%20If%20a%20file%20cannot%20be%20deleted%2C%20its%20name%20cannot%20be%20reused.%20To%20reuse%20a%20file%20name%20immediately%2C%20rename%20the%20existing%20file.) so I have emulated `unlink` on Windows by renaming the file to a random name before marking it for deletion.

I made following when `max-file=1` less likely to miss any log entries. The existing implementation would truncate the log file, immediately erasing all existing log messages. If a follower had fallen behind, any messages between its read position and the rotation would be skipped. Instead of truncating, I changed it so the file is rotated as usual: the existing file is deleted and a new one is created in its place. Any followers which have the file open can continue to read from it uninterrupted, and the OS will free up the disk space as soon as the last follower is done with it.

I rewrote how LogFile follows logs. I replaced filenotify with intra-process communication between the log writer and followers. Compared to the previous attempt to remove filenotify, #19498, this implementation does not regress logging performance. The race condition where followers could read a partially-written log message, which was worked around by retrying the read until it succeeded, is eliminated by having the writer signal the size of the file when the write has completed and so followers know not read past that offset. The event fanout with channels pattern [from Rethinking Classical Concurrency Patterns (pages 102-3)](https://drive.google.com/file/d/1nPdvhB0PutEJzdCq5ms6UI58dp50fcAN/view) is used instead of `pkg/pubsub` as it is lighter weight, consuming no resources unless a follower is waiting for a new message to be written.

I replaced refCounter, used when reading compressed logs, with a new implementation which does not get confused when the compressed log files are renamed, as happens whenever the logs are rotated.

**- How to verify it**
The added unit tests verify that no regressions have been introduced. The new LogFile follow implementation can be verified to not regress performance using `daemon/logger/jsonfilelog.BenchmarkJSONFileLoggerReadLogs`. I have found that benchmarking with a fixed number of iterations (messages logged) yields measurements with significantly less variance than giving the framework a target runtime duration.

In my testing, I have measured slightly _improved_ throughput compared to master. Benchmarked on darwin with `go test ./daemon/logger/jsonfilelog -bench BenchmarkJSONFileLoggerReadLogs -benchtime 1000000x -count=16`:
```
name                       old time/op    new time/op    delta
JSONFileLoggerReadLogs-12    5.49µs ± 7%    5.28µs ±10%  -3.89%  (p=0.034 n=15+16)

name                       old speed      new speed      delta
JSONFileLoggerReadLogs-12  22.1MB/s ± 7%  23.0MB/s ±11%  +4.19%  (p=0.034 n=15+16)
```

Instructions for reproducing, and thus verifying the fix for, the issue following logs on Windows can be found in https://github.com/moby/moby/issues/39274#issuecomment-497966709

**- Description for the changelog**
- Improved reliability of log following on Windows.
- Newlines are no longer dropped at the end of long log lines when using the `local` log driver.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: daemon/logger/loggerutils/logfile.go [hunk 1]
```diff
@@ -111,10 +103,16 @@ type Decoder interface {
...
 // This is used for tailing log files.
 type SizeReaderAt interface {
+	io.Reader
 	io.ReaderAt
 	Size() int64
 }
 
+type readAtCloser interface {
+	io.ReaderAt
+	Close() error
```
Comment (rumpl) [inline daemon/logger/loggerutils/logfile.go:113]: Couldn't this be `io.Closer`?

File: daemon/logger/loggerutils/follow.go [hunk 2]
```diff
@@ -1,211 +1,162 @@
...
 		if err != nil {
-			if err := fl.handleDecodeErr(err); err != nil {
-				if err == errDone {
-					return
-				}
-				// we got an unrecoverable error, so return
-				fl.logWatcher.Err <- err
-				return
+			if errors.Is(err, io.EOF) {
+				return false
```
Comment (ndeloof) [inline daemon/logger/loggerutils/follow.go:143]: maybe I misunderstood, but why return `done=false` on EOF?

File: daemon/logger/loggerutils/sharedtemp.go [hunk 3]
```diff
@@ -0,0 +1,225 @@
...
+
+// Do returns a reader for the contents of f as converted by the c.C function.
+// It is the caller's responsibility to close the returned reader.
+//
+// This function is safe for concurrent use by multiple goroutines.
+func (c *sharedTempFileConverter) Do(f *os.File) (*sharedFileReader, error) {
+	c.init.Do(func() {
+		c.st = make(chan stfcState, 1)
+		c.st <- stfcState{fl: make(map[stfID]sharedTempFile)}
+	})
```
Comment (ndeloof) [inline daemon/logger/loggerutils/sharedtemp.go:61]: Could maybe introduce `NewSharedTempFileConverter(fileConvertFn)` to make it clearer the required attributes and initializer logic? Using `sync.Once` to workaround lack of constructors in go sounds a bit hack-ish to me :P

File: daemon/logger/loggerutils/follow.go (hunk 2 above)
Comment (corhere) [reply daemon/logger/loggerutils/follow.go:143]: `done=true` signals that a terminal stopping condition for following logs has been encountered while decoding: unexpected error, watch consumer is gone, or the `docker logs --until` condition has been reached. EOF means that the follower has caught up to the log writer or has reached the end of a rotated log file, neither of which is a reason to stop following.

File: daemon/logger/loggerutils/sharedtemp.go (hunk 3 above)
Comment (corhere) [reply daemon/logger/loggerutils/sharedtemp.go:61]: Using `sync.Once` here is a minor optimization to lazily initialize state (and allocate memory) on first use as the converter is not used unless there is a compressed rotated log file to read. But it's probably such a trivial amount of improvement—and a premature optimization—that it's not worth the readability hit.

File: pkg/filenotify/filenotify.go [hunk 4]
```diff
@@ -1,40 +0,0 @@
-// Package filenotify provides a mechanism for watching file(s) for changes.
-// Generally leans on fsnotify, but provides a poll-based notifier which fsnotify does not support.
-// These are wrapped up in a common interface so that either can be used interchangeably in your code.
-package filenotify // import "github.com/docker/docker/pkg/filenotify"
-
-import "github.com/fsnotify/fsnotify"
```
Comment (cpuguy83) [inline pkg/filenotify/filenotify.go:6]: I think we should be able to remove this dependency from vendor/?

**Review by cpuguy83 — CHANGES_REQUESTED** [review]
This seems good, thanks for putting the time into making these changes.

There's quite a lot of changes here and it is not that easy (for me) to review, but I think this is at least safe for for vNext.
Were you also wanting these changes in 20.10?

File: daemon/logger/loggerutils/file_windows.go [hunk 5]
```diff
@@ -224,3 +225,28 @@ func volumeName(path string) (v string) {
 	}
 	return ""
 }
+
+func unlink(name string) error {
+	// Rename the file before deleting it so that the original name is freed
```
[the remark this answers is not in the document]
Comment (corhere) [reply daemon/logger/loggerutils/file_windows.go:230]: Yes it does

File: daemon/logger/loggerutils/logfile.go [hunk 6]
```diff
@@ -204,29 +205,31 @@ func (w *LogFile) checkCapacityAndRotate() (retErr error) {
...
 	}
 
 	if err := rotate(fname, w.maxFiles, w.compress); err != nil {
 		logrus.WithError(err).Warn("Error rotating log file, log data may have been lost")
 	} else {
-		var renameErr error
-		for i := 0; i < 10; i++ {
-			if renameErr = os.Rename(fname, fname+".1"); renameErr != nil && !os.IsNotExist(renameErr) {
-				logrus.WithError(renameErr).WithField("file", fname).Debug("Error rotating current container log file, evicting readers and retrying")
-				w.notifyReaders.Publish(renameErr)
```
[the remark this answers is not in the document]
Comment (corhere) [reply daemon/logger/loggerutils/logfile.go:217]: Logging already can continue if rotation fails: it falls back to truncating the current log file. Evicting readers is disruptive to users and adds significant complexity to the log following code so I would really prefer not to add that complexity back in without a compelling reason to do so.

**Comment by corhere** [comment]
> Were you also wanting these changes in 20.10?

Not any time soon, if at all. Maybe at some point in the future if there is enough demand from users, once these changes have been sufficiently battle-tested in the field.

**Review by cpuguy83 — APPROVED** [review]

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Failure on arm is a known flaky test, so we can ignore that one (Windows is still running)

```
=== RUN   TestNetworkDBCRUDTableEntries
    networkdb_test.go:310: Entry existence verification test failed for node2(ba5cfe4faa8c)
2022/05/19 19:37:25 Closing DB instances...
--- FAIL: TestNetworkDBCRUDTableEntries (7.63s)
```

**Comment by thaJeztah** [comment]
Windows passed, so the above was the only failure

**Review by thaJeztah — APPROVED** [review]
LGTM

thanks for the rebase and removing the vendor files 👍
