### PR TITLE
pkg/idtools: remove CanAccess(), and move to daemon

### LINKED ISSUE #43724: incorrect accessible() implementation
https://github.com/moby/moby/blob/74286cba8c2c14d5360caec44d2da74858e9c707/pkg/idtools/idtools_unix.go#L95

```
func accessible(isOwner, isGroup bool, perms os.FileMode) bool {
	if isOwner && (perms&0100 == 0100) {
		return true
	}
	if isGroup && (perms&0010 == 0010) {
		return true
	}
	if perms&0001 == 0001 {
		return true
	}
	return false
}
```

Hello, the `accessible()` function can give incorrect results if `isOwner` or `isGroup` is true. (Well, 'incorrect' in the sense that it gives different results than Unix and Linux systems.)

The traditional implementation of discretionary access controls does NOT fall back to the wider permissions:

Consider:

```
$ mkdir owner
$ mkdir group
$ mkdir world
$ chmod 100 owner
$ chmod 010 group
$ chmod 001 world
$ cd owner/
$ cd ..
$ cd group/
bash: cd: group/: Permission denied
$ cd world/
bash: cd: world/: Permission denied
$ ls -ld owner group world
d-----x--- 2 sarnold sarnold 2 Jun 17 02:17 group
d--x------ 2 sarnold sarnold 2 Jun 17 02:17 owner
d--------x 2 sarnold sarnold 2 Jun 17 02:17 world
```

(For the ultra-curious, I strongly recommend checking out the ancient Unix source code at http://warsus.github.io/lions-/all.html ; there's a bit of complication around root getting all permissions except execution, but a very pleasing "shift the permissions right three bits" if the uid or gid don't match followed by a single test. Look for `access(aip, mode)`.)

I'm a little worried about the presence of this function at all, however; `access(2)` has been a source of security bugs in the Unix world for decades, and this implementation completely ignores the permissions on path resolution, so it's even less useful than the `access(2)` syscall provided by the Linux kernel.

How is this function used? Why?

Thanks

### PR DESCRIPTION
**Pull request by thaJeztah**
- follow-up to https://github.com/moby/moby/pull/44254
- relates to / closes https://github.com/moby/moby/issues/43724

The implementation of CanAccess() is very rudimentary, and should
not be used for anything other than a basic check (and maybe not
even for that). It's only used in a single location in the daemon,
so move it there, and un-export it to not encourage others to use
it out of context.

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]

File: daemon/daemon_unix.go [hunk 1]
```diff
@@ -1259,6 +1260,34 @@ func setupDaemonRoot(config *config.Config, rootDir string, remappedRoot idtools
...
+	ssi := statInfo.Sys().(*syscall.Stat_t)
+	if ssi.Uid == uint32(pair.UID) && (perms&0o100 == 0o100) {
+		// owner access.
+		return true
+	}
+	if ssi.Gid == uint32(pair.GID) && (perms&0o010 == 0o010) {
+		// group access.
+		return true
+	}
+	return false
```
Comment (corhere) [inline daemon/daemon_unix.go:1288]: It may be a rudimentary and incomplete check, but it wouldn't be much effort to make it less broken.

```suggestion
	perms := statInfo.Mode().Perm()
	ssi := statInfo.Sys().(*syscall.Stat_t)
	if ssi.Uid == uint32(pair.UID) {
		// owner access.
		return perms&0o100 == 0o100
	}
	if ssi.Gid == uint32(pair.GID) {
		// group access.
		return perms&0o010 == 0o010
	}
	return perms&0o001 == 0o001 // world access
```

**Review by corhere — APPROVED** [review]
