### PR TITLE
Fail when there is an error executing an inspect template.

### LINKED ISSUE #15566: Docker Inspect Issue: Leading literal strings are duplicated when template resolution fails.
When you're using literal strings in a "docker inspect" format string, it seems that if a template resolution fails, leading literal strings can be duplicated. First, an example when it works, both without and with a leading literal string:

sh-4.3# docker inspect -f '{{.Architecture}}' httpd
amd64
sh-4.3# docker inspect -f 'My arch is {{.Architecture}}' httpd
My arch is amd64
sh-4.3#

But look what happens if i misspell as "Archtecture" in both cases:

sh-4.3# docker inspect -f '{{.Archtecture}}' httpd
<no value>
sh-4.3# docker inspect -f 'My arch is {{.Archtecture}}' httpd
My arch is My arch is <no value>
           ^^^^^^^^^^ ???

This is entirely reproducible; just misspell the contents of the template:

sh-4.3# docker inspect -f 'My ports are {{.Config.Ports}}' httpd
My ports are My ports are <no value>

uname -a 
Linux dhcp-25-141.bos.redhat.com 4.0.4-303.fc22.x86_64 #1 SMP Thu May 28 12:37:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

docker version
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   650feb2-dirty
 Built:        Thu Aug 13 16:50:09 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   650feb2-dirty
 Built:        Thu Aug 13 16:50:09 UTC 2015
 OS/Arch:      linux/amd64

docker info
Containers: 8
Images: 22
Storage Driver: devicemapper
 Pool Name: docker-8:3-2360227-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.513 GB
 Data Space Total: 107.4 GB
 Data Space Available: 40.34 GB
 Metadata Space Used: 2.228 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.4-303.fc22.x86_64
Operating System: Fedora 22 (Twenty Two)
CPUs: 4
Total Memory: 11.72 GiB
Name: dhcp-25-141.bos.redhat.com
ID: NODU:OCAV:EOZD:CWD3:EEKS:AJCL:ZCKH:B6S7:7247:UVAC:2EAK:3FC2

### LINKED ISSUE #17026: `docker inspect` issue in 1.9.0-rc1
````
$ docker version
Client:
 Version:      1.9.0-rc1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   9291a0e
 Built:        Wed Oct 14 03:07:34 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0-rc1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   9291a0e
 Built:        Wed Oct 14 03:07:34 UTC 2015
 OS/Arch:      linux/amd64
$ docker run -tid --name test busybox
56fcd6a8512e880465c84695e8669c17b74332a1ab9dc0369b8ac219e5ed577b
$ docker inspect -f '{{.State.Running}} {{.State.ExitCode}} {{.HostConfig.Dns}}' test
true 0 true 0 <no value>
````
Note that the string `true 0 ` is repeated erroneously. Here's the same on 1.8.3:

````
$ docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:27:08 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:27:08 UTC 2015
 OS/Arch:      linux/amd64
$ docker run -tid --name test busybox
$ docker inspect -f '{{.State.Running}} {{.State.ExitCode}} {{.HostConfig.Dns}}' test
true 0 []

````

### PR DESCRIPTION
**Pull request by calavera**
- Do not execute the template directly in the cli outout, go is not atomic
  in this operation and can send bytes before failing the execution.
- Fail after evaluating a raw interface if the typed execution also
  failed, assuming there is a template parsing error.

Closes #15566
Closes #17026

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by tiborvass** [comment]
@calavera needs rebase

**Comment by calavera** [comment]
Rebased

File: api/client/inspect.go [hunk 1]
```diff
@@ -101,42 +100,45 @@ func (cli *DockerCli) CmdInspect(args ...string) error {
...
+			buf := bytes.NewBufferString("")
 
 			if isImage {
 				inspPtr := types.ImageInspect{}
 				if err := dec.Decode(&inspPtr); err != nil {
-					fmt.Fprintf(cli.err, "%s\n", err)
+					fmt.Fprintf(cli.err, "Unable to read inspect data: %v\n", err)
 					status = 1
-					continue
+					break
```
Comment (tiborvass) [inline api/client/inspect.go]: why break? it used to continue to the next argument to inspect.

Comment (tiborvass) [inline api/client/inspect.go]: is that the fix?

**Comment by calavera** [comment]
After further investigation, it looks like this fix also solves #17026:

```
➜  docker inspect -f '{{.State.Running}} {{.State.ExitCode}} {{.HostConfig.Dns}}' test
false 143 []
```

File: api/client/inspect.go (hunk 1 above)
Comment (calavera) [inline api/client/inspect.go]: because there is something very wrong when we cannot decode an api response and we should not continue with the next arguments.

Comment (calavera) [inline api/client/inspect.go]: The previous behavior explained like a movie:

- Client: hey, can I have this container's info?
- API: sure, here you have some gibberish that might not even be a json payload
- Client: cool, can I have this other container's info?

The new behavior goes like this:

- Client: hey, can I have this container's info?
- API: sure, here you have some gibberish that might not even be a json payload
- Client: what's wrong with you API?? abort!

**Comment by duglin** [comment]
at one point I thought @shishir-a412ed had a fix for this that just tried using the current path, and then if that failed it tried again using the raw - but didn't output anything until the end.  Would be easier?

**Comment by calavera** [comment]
> Would be easier?

that's exactly what this patch does. Look at the `tmpl.Execute` methods, the stopped using `cli.out` as the template output and now they use a buffer.

**Comment by duglin** [comment]
yea, its just I think he did it w/o a new func and I remember it being just a few more lines added - but perhaps I'm remembering incorrectly.

**Comment by calavera** [comment]
No, he didn't do any of that, he's PR modified the the api returned types and removed the raw decoding.

File: api/client/inspect.go (hunk 1 above)
Comment (thaJeztah) [inline api/client/inspect.go]: :laughing:

**Comment by duglin** [comment]
the latest did yea, but I think an older version didn’t do all of that.

File: api/client/inspect.go [hunk 2]
```diff
@@ -101,42 +100,45 @@ func (cli *DockerCli) CmdInspect(args ...string) error {
 		} else {
 			rdr := bytes.NewReader(obj)
 			dec := json.NewDecoder(rdr)
+			buf := bytes.NewBufferString("")
```
Comment (tiborvass) [inline api/client/inspect.go]: `buf := new(bytes.Buffer)` is more idiomatic but dont update just for this

**Comment by tiborvass** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Comment by phemmer** [comment]
Do we want to do the same for `docker version` (buffer the output)? It doesn't repeat things, but it will send partial output before failing:

```
# docker version -f 'My foo is {{.Foo}}'
My foo is 
template: :1:12: executing "" at <.Foo>: Foo is not a field of struct type client.VersionData
```

**Comment by calavera** [comment]
@phemmer I'd say yes. We already handle ps like that and I think it's a good UX behavior, partial outputs are not very friendly.
