### PR TITLE
Using authorization plugin, I changed Content-Type check routine.

### LINKED ISSUE #36317: Auth plugins recieve empty request bodies when content-type of request contains charset.
If you submit a request to create a container (POST /containers/create) with a specific content type (Content-Type: application/json; charset=utf-8), than an empty request body is forwarded to the auth plugin, effectively not allowing the auth plugin to verify the request (if said auth plugin uses the body to perform authentication).

The bug is in how the auth plugin handler API determines whether or not to send the body to auth plugins (specifically on line 156 of https://github.com/moby/moby/blob/master/pkg/authorization/authz.go).

The check does a straight string comparison of the content-type with the hard coded string "application/json". This should also be able to handle charsets as specified in https://www.w3.org/International/articles/http-charset/index.

Other parts of the docker code base ([httputils.CheckJson](https://github.com/moby/moby/blob/master/api/server/httputils/httputils.go ) or using golangs  [mime.ParseMediaType](https://golang.org/pkg/mime/)) already perform different logic to verify the content-type header succesfully, this line of code should be modified to perform the same (or similar) logic.

Steps to reproduce:
1. Install the debug auth plugin I created to demonstrate this (it simply logs the content length, content type and the length of the body).

https://bitbucket.org/nburrell/authz/src/master/

2. Post the following request to docker (note the content-type is simply **"application/json"**) and note the length of the body being the same as the content length in the request:

`curl -X POST -H 'Content-Type: application/json' -d '{"ExposedPorts":{"9324/tcp":{}},"HostConfig":{"Binds":["/opt/atlassian/pipelines/agent/build/application/src/test/resources/elasticmq.conf:/elasticmq.conf"],"PortBindings":{"9324/tcp":[{"HostPort":"9324"}]},"VolumesFrom":[]},"Image":"graze/sqs-local","Labels":{"dmp.coordinates":"com.atlassian.pipelines:agent-service-application:2.449-SNAPSHOT"},"Volumes":{"/elasticmq.conf":{}}}' http://localhost:2375/v1.18/containers/create
`

3. Post the following request to docker (note the content-type in this one is **"application/json; charset=utf-8"**) and note the length of the body being 0, even though the content length is correct:

`curl -X POST -H 'Content-Type: application/json; charset=utf-8' -d '{"ExposedPorts":{"9324/tcp":{}},"HostConfig":{"Binds":["/opt/atlassian/pipelines/agent/build/application/src/test/resources/elasticmq.conf:/elasticmq.conf"],"PortBindings":{"9324/tcp":[{"HostPort":"9324"}]},"VolumesFrom":[]},"Image":"graze/sqs-local","Labels":{"dmp.coordinates":"com.atlassian.pipelines:agent-service-application:2.449-SNAPSHOT"},"Volumes":{"/elasticmq.conf":{}}}' http://localhost:2375/v1.18/containers/create
`

Also note the docker client isnt affected by this as it always sets the content-type to "application/json" however other docker clients such as [fabric8io/docker-maven-plugin](https://github.com/fabric8io/docker-maven-plugin) include the charset and thus cannot interact with the docker daemon that uses auth plugins correctly.

### PR DESCRIPTION
**Pull request by odg0318**
- fixes https://github.com/moby/moby/issues/36317

**- What I did**
I changed `Content-Type` check routine.
`sendBody` function in `pkg/authorization/authz.go` checks `Content-Type` in  http request.
But the routine can cover `application/json` but not `application/json;charset=UTF8`.
Actually, `Portainer`, a tool for managing docker resource, sends `Content-Type` including charset such as `application/json;charset=UTF8`.

**- How I did it**
I extract `application/json` from `Content-Type` in header using `mime` package.

**- How to verify it**
I added test case, `TestSendBody`.

**- Description for the changelog**
Fixed a function to check `Content-type` is `application/json` or not.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: pkg/authorization/authz.go [hunk 1]
```diff
@@ -153,7 +153,8 @@ func sendBody(url string, header http.Header) bool {
 	}
 
 	// body is sent only for text or json messages
-	return header.Get("Content-Type") == "application/json"
+	var contentType = strings.Split(header.Get("Content-Type"), ";")[0]
```
Comment (stevvooe) [inline pkg/authorization/authz.go]: Please use the `mimetype` package to parse this.

File: pkg/authorization/authz_unix_test.go [hunk 2]
```diff
@@ -172,6 +172,22 @@ func TestDrainBody(t *testing.T) {
...
+	url := "nothing.com"
+
+	header := http.Header{}
+	header.Set("Content-Type", "application/json")
+
+	if b := sendBody(url, header); b == false {
+		t.Fatalf("Content-Type should be application/json")
+	}
+
+	header.Set("Content-Type", "application/json;charset=UTF8")
```
[the remark this answers is not in the document]
Comment (odg0318) [reply pkg/authorization/authz_unix_test.go]: Done.

File: pkg/authorization/authz_unix_test.go [hunk 3]
```diff
@@ -172,6 +172,54 @@ func TestDrainBody(t *testing.T) {
...
 
+func TestSendBody(t *testing.T) {
+	var (
+		url       = "nothing.com"
+		testcases = []struct {
+			contentType string
+			expected    bool
+		}{
+			{
+				contentType: "application/json",
```
Comment (thaJeztah) [inline pkg/authorization/authz_unix_test.go]: Perhaps to be complete, we should have a mixed-case example here as well, e.g.  `Application/JSON`, because they [are case-insensitive](https://www.w3.org/Protocols/rfc1341/4_Content-Type.html) (`mime.ParseMediaType()` already normalises that, so no changes to the code are needed)

**Review by thaJeztah — CHANGES_REQUESTED** [review]
one tiny nit, but looks good otherwise

File: pkg/authorization/authz_unix_test.go (hunk 3 above)
Comment (odg0318) [reply pkg/authorization/authz_unix_test.go]: I added 3 testcases more.

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

@stevvooe PTAL

**Comment by anusha-ragunathan** [comment]
LGTM

**Comment by thaJeztah** [comment]
I'm a bit unsure if we should export the httputils version and import that into a `pkg/`. Looks like currently the api/server/httputils package is only used inside the API, importing it into `pkg/` may not be desirable for three lines of code

**Comment by anusha-ragunathan** [comment]
@thaJeztah : I'm more concerned about the redundant unit tests and the time taken on all CI runs after this. Hence the suggestion to package it, so we can leverage testing.

**Comment by thaJeztah** [comment]
Agreed there's some redundancy, but it's a unit test, and this test runs in 3ms on my machine; whole file takes less than a second;

    ok  	github.com/docker/docker/pkg/authorization	0.195s

**Comment by LautaroJayat** [comment]
This Fixes https://github.com/moby/moby/issues/36317.
I think that issue can be closed now :)
