### PR TITLE
Fix incorrect `Scope` in `network ls/inspect` with duplicate network names

### LINKED ISSUE #30242: daemon allows creating two network with same name when checkDuplicate is false, REASONABLE?
**Description**

Hi, All,

I found that we could create two bridge networks with same name, as we use a field `"checkDuplicate":false,` in the api request payload.

Is it reasonable?

Here is my request:
```
POST 192.168.59.103:2375/networks/create
payload:
{
	"Name":"ouyang",
	"Driver":"bridge",
	"EnableIPv6":false,
	"Internal":false,
	"Attachable":false,
	"Options":{},
	"checkDuplicate":false,
	"Labels":{},
	"IPAM":{
		"Driver":"default",
		"Options":{},
		"Config":[]
	}
}
```

With the first create request, we got the response:
```
{
  "Id":"1c4fcb3e1e9b3a25aa04164328a6d680bab897e151dbc09a0c8e3d414e22a0bc",
  "Warning": ""
}
```

With the first create request, we got the response:
```
{
  "Id": "1c4fcb3e1e9b3a25aa04164328a6d680bab897e151dbc09a0c8e3d414e22a0bc",
  "Warning": "Network with name ouyang (id : 77ab41fbbe321bc02622b50d81ef2404b3229a8d8a53aeb8922f762b9d15ec9f) already exists"
}
```
We create twice, and get result like this:
```
root@ubuntu:~# docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
30d1f8c9ec34        bridge              bridge              local
85ded5476b05        docker_gwbridge     bridge              local
d909a9f88b4c        host                host                local
f799odklwkfi        ingress             overlay             swarm
615a39ff6c47        none                null                local
77ab41fbbe32        ouyang              bridge              local
1c4fcb3e1e9b        ouyang              bridge              local
```

Two network ouyang, is it reasonable? Since it happens, we could not use `docker network inspect ouyang` and some other network commands using network name:
1. `docker network inspect ouyang` may get the wrong network;
2. `docker network rm ouyang` may  remove the wrong network;
3. .....

Or it is for some kind of back compatibility?  If that, I think we should mark that in the source code.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
root@ubuntu:~# docker version
Client:
 Version:      1.13.0-rc4
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   88862e7
 Built:        Fri Dec 16 22:59:15 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-rc4
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   88862e7
 Built:        Fri Dec 16 22:59:15 2016
 OS/Arch:      linux/amd64
 Experimental: false
root@ubuntu:~#
```

**Output of `docker info`:**

```
root@ubuntu:~# docker info
Containers: 8
 Running: 6
 Paused: 0
 Stopped: 2
Images: 37
Server Version: 1.13.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 202
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 07jqxh286upar2z13e9cf69ad
 Is Manager: true
 ClusterID: vkawf2iglgltjxyupnvpbst5f
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.59.103
 Manager Addresses:
  192.168.59.103:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: ubuntu
ID: Q2ZC:GWDN:27OH:GRMH:G6QU:W7QP:4TIX:Q5F6:YEVK:45XP:EXHC:HOB5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 90
 Goroutines: 184
 System Time: 2017-01-17T14:45:33.364813219+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://a.b.c/
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by yongtang**
**- What I did**

This fix tries to address the issue raised in comment https://github.com/docker/docker/issues/30242#issuecomment-273468307 where the `Scope` field always changed to `swarm` in the ouput of `docker network ls/inspect` when duplicate network name exists.

The reason for the issue was that `buildNetworkResource()` use network name
(which may not be unique) to check for the scope.

**- How I did it**

This fix fixes the issue by always use network ID in `buildNetworkResource()`.

**- How to verify it**

A test has been added. The test fails before the fix and passes after the fix.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

j3iz7jp

This fix is related to #30242.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by allencloud** [comment]
I am a super fan of you, @yongtang 
😆 ❤️

**Comment by aboch** [comment]
Looks good to me

**Comment by chanwit** [comment]
thank you @yongtang, you're awesome!
non-maintainer LGTM, both codes and the test case.

ping @thaJeztah I think you know who should review this PR :-)

**Review by thaJeztah — CHANGES_REQUESTED** [review]
one nit/suggestion for the tests, but LGTM otherwise

File: integration-cli/docker_api_swarm_test.go [hunk 1]
```diff
@@ -1329,3 +1331,44 @@ func (s *DockerSwarmSuite) TestAPISwarmErrorHandling(c *check.C) {
...
+	var n2 types.NetworkCreateResponse
+	networkCreateRequest.NetworkCreate.Driver = "overlay"
+
+	status, out, err = d.SockRequest("POST", "/networks/create", networkCreateRequest)
+	c.Assert(err, checker.IsNil, check.Commentf(string(out)))
+	c.Assert(status, checker.Equals, http.StatusCreated, check.Commentf(string(out)))
+
+	c.Assert(json.Unmarshal(out, &n2), checker.IsNil)
+
+	out1, err := d.Cmd("network", "inspect", "--format", "{{.Scope}}", n1.ID)
```
Comment (yongtang) [inline integration-cli/docker_api_swarm_test.go]: Thanks @thaJeztah for the review. The PR has been updated with API used. Please take a look.

**Review by thaJeztah — APPROVED** [review]
LGTM (if green), thanks!

**Comment by allencloud** [comment]
It is great to see all greens. 😄 
ping @thaJeztah
