### PR TITLE
Don't resolve or pull images referenced by ID

### LINKED ISSUE #28034: Swarm checks docker.io to locate locally built images (1.12.3)
**Description**

When testing swarm on a local machine during developments with locally built images, if you create a service that references an image by sha256 hash, docker will attempt to download it from the docker.io repository.

The error is ignored so it's not a correctness issue, but more a performance issues (load on docker.io services and service startup latency).

**Steps to reproduce the issue:**

1. Build a local image (docker build)
2. Create a service which references the image by sha256 hash.

**Describe the results you received:**

tcpdump records traffic to docker.io.
The log file records the following:

```
Nov  3 12:50:30 docker-host dockerd[820]: time="2016-11-03T12:50:30.901321060+01:00" level=debug msg="Service dvqcc2sgji8l8ubhbacoqtdlv was scaled up from 0 to 1 instances"
Nov  3 12:50:30 docker-host dockerd[820]: time="2016-11-03T12:50:30.913146895+01:00" level=debug msg="RequestAddress(GlobalDefault/10.0.4.0/24, <nil>, map[])"
Nov  3 12:50:30 docker-host dockerd[820]: time="2016-11-03T12:50:30.969383714+01:00" level=debug msg="Assigning to node b045pff5gn01y0oyk4g36ve4f" task.id=63bmxseq3kb4ayo206lupt2vl
Nov  3 12:50:31 docker-host dockerd[820]: time="2016-11-03T12:50:31.027359878+01:00" level=debug msg="(*worker).Assign" len(tasks)=56 module=agent
Nov  3 12:50:31 docker-host dockerd[820]: time="2016-11-03T12:50:31.028662747+01:00" level=debug msg=assigned module=agent task.desiredstate=RUNNING task.id=63bmxseq3kb4ayo206lupt2vl
Nov  3 12:50:31 docker-host dockerd[820]: time="2016-11-03T12:50:31.028723936+01:00" level=debug msg="state changed" module=agent state.desired=RUNNING state.transition="ASSIGNED->ACCEPTED" task.id=63bmxseq3kb4ayo206lupt2vl
Nov  3 12:50:31 docker-host dockerd[820]: time="2016-11-03T12:50:31.028824749+01:00" level=debug msg="(*Agent).UpdateTaskStatus" module=agent task.id=63bmxseq3kb4ayo206lupt2vl
Nov  3 12:50:31 docker-host dockerd[820]: time="2016-11-03T12:50:31.029103566+01:00" level=debug msg="state changed" module=taskmanager state.desired=RUNNING state.transition="ASSIGNED->ACCEPTED" task.id=63bmxseq3kb4ayo206lupt2vl
Nov  3 12:50:31 docker-host dockerd[820]: time="2016-11-03T12:50:31.042642197+01:00" level=debug msg="task status reported" module=agent
Nov  3 12:50:31 docker-host dockerd[820]: time="2016-11-03T12:50:31.042701810+01:00" level=debug msg="(*Agent).UpdateTaskStatus" module=agent task.id=63bmxseq3kb4ayo206lupt2vl
Nov  3 12:50:31 docker-host dockerd[820]: time="2016-11-03T12:50:31.042939238+01:00" level=debug msg="task status reported" module=agent
Nov  3 12:50:31 docker-host dockerd[820]: time="2016-11-03T12:50:31.063001169+01:00" level=debug msg="state changed" module=taskmanager state.desired=RUNNING state.transition="ACCEPTED->PREPARING" task.id=63bmxseq3kb4ayo206lupt2vl
Nov  3 12:50:31 docker-host dockerd[820]: time="2016-11-03T12:50:31.063331480+01:00" level=debug msg="(*Agent).UpdateTaskStatus" module=agent task.id=63bmxseq3kb4ayo206lupt2vl
Nov  3 12:50:31 docker-host dockerd[820]: time="2016-11-03T12:50:31.063916732+01:00" level=debug msg="task status reported" module=agent
Nov  3 12:50:31 docker-host dockerd[820]: time="2016-11-03T12:50:31.069419207+01:00" level=debug msg="Trying to pull sha256 from https://registry-1.docker.io v2"
Nov  3 12:50:31 docker-host dockerd[820]: time="2016-11-03T12:50:31.075832453+01:00" level=debug msg="task status updated" method="(*Dispatcher).processTaskUpdates" module=dispatcher state.transition="ASSIGNED->PREPARING" task.id=63bmxseq3kb4ayo206lupt2vl
Nov  3 12:50:31 docker-host dockerd[820]: time="2016-11-03T12:50:31.133400815+01:00" level=debug msg="(*worker).Assign" len(tasks)=55 module=agent
Nov  3 12:50:31 docker-host dockerd[820]: time="2016-11-03T12:50:31.133784052+01:00" level=debug msg=assigned module=agent task.desiredstate=RUNNING task.id=63bmxseq3kb4ayo206lupt2vl
Nov  3 12:50:32 docker-host dockerd[820]: time="2016-11-03T12:50:32.167680220+01:00" level=debug msg="Increasing token expiration to: 60 seconds"
Nov  3 12:50:32 docker-host dockerd[820]: time="2016-11-03T12:50:32.533887157+01:00" level=error msg="Attempting next endpoint for pull after error: unauthorized: authentication required"
Nov  3 12:50:32 docker-host dockerd[820]: time="2016-11-03T12:50:32.533926214+01:00" level=debug msg="Trying to pull sha256 from https://index.docker.io v1"
Nov  3 12:50:32 docker-host dockerd[820]: time="2016-11-03T12:50:32.533947661+01:00" level=debug msg="hostDir: /etc/docker/certs.d/docker.io"
Nov  3 12:50:32 docker-host dockerd[820]: time="2016-11-03T12:50:32.534025000+01:00" level=debug msg="[registry] Calling GET https://index.docker.io/v1/repositories/library/sha256/images"
Nov  3 12:50:32 docker-host dockerd[820]: time="2016-11-03T12:50:32.534254835+01:00" level=debug msg="pull progress map[status:Pulling repository docker.io/library/sha256]"
Nov  3 12:50:33 docker-host dockerd[820]: time="2016-11-03T12:50:33.246423560+01:00" level=error msg="Not continuing with pull after error: Error: image library/sha256:7027f95bb25e5716c31c26b20f9dca4020689764dc66f88006984640c7a14d1b not found"
Nov  3 12:50:33 docker-host dockerd[820]: time="2016-11-03T12:50:33.246462602+01:00" level=error msg="pulling image failed" error="Error: image library/sha256:7027f95bb25e5716c31c26b20f9dca4020689764dc66f88006984640c7a14d1b not found" module=taskmanager task.id=63bmxseq3kb4ayo206lupt2vl
Nov  3 12:50:33 docker-host dockerd[820]: time="2016-11-03T12:50:33.321554074+01:00" level=debug msg="container mounted via layerStore: /var/lib/docker/aufs/mnt/5153b105792f0ed7d052ec7ba6205d7fae8fe98bc5df2bf0e094ecab6c2fd081"

```

**Describe the results you expected:**

The service starts without checking the registry.

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:39:14 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:39:14 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 135
 Running: 9
 Paused: 0
 Stopped: 126
Images: 495
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 941
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay bridge host
Swarm: active
 NodeID: b045pff5gn01y0oyk4g36ve4f
 Is Manager: true
 ClusterID: bafvlrn31z0mlv7dd3jlmdlf4
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.122.172
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 11.76 GiB
Name: martijn-jessie
ID: DUEF:LBIX:GMD7:UKUF:DY4B:LNA7:ZXS2:AEDT:IE5W:KAQW:TMJS:R42Q
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 97
 Goroutines: 319
 System Time: 2016-11-03T17:38:59.349027009+01:00
 EventsListeners: 9
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VM on Laptop

### PR DESCRIPTION
**Pull request by aaronlehmann**
If a swarm service is created using an image ID, it's useless to try to
pull this reference or resolve it to a manifest digest. Avoid doing this
when a fully qualified image ID is given.

Fixes #28034

cc @thaJeztah @nishanttotla

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

File: daemon/cluster/cluster.go [hunk 1]
```diff
@@ -1021,6 +1022,9 @@ func (c *Cluster) GetServices(options apitypes.ServiceListOptions) ([]types.Serv
 // TODO(nishanttotla): After the packages converge, the function must
 // convert distreference.Named -> distreference.Canonical, and the logic simplified.
 func (c *Cluster) imageWithDigestString(ctx context.Context, image string, authConfig *apitypes.AuthConfig) (string, error) {
+	if _, err := digest.ParseDigest(image); err == nil {
```
Comment (nishanttotla) [inline daemon/cluster/cluster.go]: Why is this check necessary? Doesn't the `distreference.ParseNamed` followed by checking if it's a `Canonical` reference achieve the same thing?

Comment (aaronlehmann) [inline daemon/cluster/cluster.go]: This will validate something of the form:

```
sha256:e02e811dd08fd49e7f6032625495118e63f597eb150403d02e3238af1df240ba
```

`distreference.ParseNamed` followed by the `Canonical` check will validate something of the form:

```
busybox@sha256:29f5d56d12684887bdfa50dcd29fc31eea4aaf4ad3bec43daf19026a7ce69912
```

**Comment by nishanttotla** [comment]
Also, does this PR mean we can refactor some code from #28265?

File: daemon/cluster/cluster.go (hunk 1 above)
Comment (nishanttotla) [inline daemon/cluster/cluster.go]: Ah okay, I see the point now, the earlier issue was a little confusing at first.

**Review by nishanttotla — APPROVED** [review]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐸
