### PR TITLE
Fix userns-remap option when username & UID match

### LINKED ISSUE #42003: Using userns-remap option when username & UID are the same causes containers to not run since 20.10.0
**Description**

The userns option uses an append of the UID and username (I guess the use case of using a username & UID which are the same was not considered). When both match this causes an issue where namespaced containers will no longer start.

**Steps to reproduce the issue:**
1. `echo "10426:x:10426:10426::/nonexistent:/bin/false" >> /etc/passwd`
2. `echo "10426:x:10426:" >> /etc/group`
3. `echo "10426:10426000:10000" >> /etc/subuid`
4. `echo "10426:10426000:10000" >> /etc/subgid`
5. dockerd --userns-remap=10426 &
6. docker run hello-world

**Describe the results you received:**
`
ERRO[2021-02-09T16:00:21.363273000Z] Handler for POST /v1.30/containers/ead4e0053b76f9ea88f03bb0c0cfc3af40c6c4717c625d70cbfe4a8f29b5fa42/start returned error: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:338: getting the final child's pid from pipe caused: EOF: unknown 
`

**Describe the results you expected:**
The container to start successfully

**Additional information you deem important (e.g. issue happens only occasionally):**
This started with docker `20.10.0` following the commit https://github.com/moby/moby/commit/7ad0da705144c2a8a223fa0f8d0cad2fbffe4554

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:33:21 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       eeddea2
  Built:            Tue Dec  8 18:57:45 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 12
  Running: 12
  Paused: 0
  Stopped: 0
 Images: 12
 Server Version: 20.10.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  userns
 Kernel Version: 5.10.13-051013-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 11.47GiB
 Name: test.ssd.local.cylo.net
 ID: CRII:VLIT:JYPX:DF6I:2F7A:NJDB:NMN2:54QI:UB63:DXBA:GE3V:JZ3J
 Docker Root Dir: /var/lib/docker/100000.100000
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio weight support
WARNING: No blkio weight_device support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by Rid**
Signed-off-by: Grant Millar <rid@cylo.io>

**- What I did**
Fixed #42003 by only matching UID or username.

**- How I did it**
Check `subuidRangesWithUID` first then `subuidRangesWithUserName`.

**- How to verify it**

1. `echo "10426:x:10426:10426::/nonexistent:/bin/false" >> /etc/passwd`
2. `echo "10426:x:10426:" >> /etc/group`
3. `echo "10426:10426000:10000" >> /etc/subuid`
4. `echo "10426:10426000:10000" >> /etc/subgid`
5. `dockerd --userns-remap=10426 &`
6. `docker run hello-world`

**- Description for the changelog**

Fix userns-remap option when username & UID match

**- A picture of a cute animal (not mandatory but encouraged)**
06-beaver-attack

### CODE REVIEW

File: pkg/idtools/idtools_unix.go [hunk 1]
```diff
@@ -265,13 +265,22 @@ func NewIdentityMapping(name string) (*IdentityMapping, error) {
...
-	subgidRanges := append(subgidRangesWithUserName, subgidRangesWithUID...)
+	var subuidRanges ranges
+	var subgidRanges ranges
 
-	if len(subuidRanges) == 0 {
+	if len(subuidRangesWithUID) > 0 {
+		subuidRanges = subuidRangesWithUID
+	} else if len(subuidRangesWithUserName) > 0 {
+		subuidRanges = subuidRangesWithUserName
+	} else {
```
Comment (thaJeztah) [inline pkg/idtools/idtools_unix.go:275]: Actually wondering why we're looking up both; perhaps instead we should return early (try lookup sub-uids by UID -> if error, or no results -> lookup by Name -> repeat for sub-gids).

That said; ISTR there was some discussion about wether "user-name" or "user-id" takes precedence (user-name should probably not be able to take precedence (i.e., a user _named_ `0` should not be able to "trump" `root`), but linux disagreed on that (some discussion on https://github.com/moby/moby/issues/21436 and https://github.com/opencontainers/runc/commit/0a5293fa4ee5b38d1eeaa041754fd01f15960ad9 (https://github.com/opencontainers/runc/pull/708))

Comment (thaJeztah) [reply pkg/idtools/idtools_unix.go:275]: Did a quick try at what it _could_ look like (feedback welcome) earlier;

```go
// NewIdentityMapping takes a requested username and
// using the data from /etc/sub{uid,gid} ranges, creates the
// proper uid and gid remapping ranges for that user/group pair
func NewIdentityMapping(name string) (*IdentityMapping, error) {
	usr, err := LookupUser(name)
	if err != nil {
		return nil, fmt.Errorf("Could not get user for username %s: %v", name, err)
	}

	subuidRanges, err := lookupSubUIDRanges(usr)
	if err != nil {
		return nil, err
	}
	subgidRanges, err := lookupSubGIDRanges(usr)
	if err != nil {
		return nil, err
	}

	return &IdentityMapping{
		uids: subuidRanges,
		gids: subgidRanges,
	}, nil
}

func lookupSubUIDRanges(usr user.User) ([]IDMap, error) {
	r, err := parseSubuid(strconv.Itoa(usr.Uid))
	if err != nil {
		return nil, err
	}
	if len(r) == 0 {
		r, err = parseSubuid(usr.Name)
		if err != nil {
			return nil, err
		}
	}
	if len(r) == 0 {
		return nil, errors.Errorf("no subuid ranges found for user %q", usr.Name)
	}
	return createIDMap(r), nil
}

func lookupSubGIDRanges(usr user.User) ([]IDMap, error) {
	r, err := parseSubgid(strconv.Itoa(usr.Uid))
	if err != nil {
		return nil, err
	}
	if len(r) == 0 {
		r, err = parseSubgid(usr.Name)
		if err != nil {
			return nil, err
		}
	}
	if len(r) == 0 {
		return nil, errors.Errorf("no subgid ranges found for user %q", usr.Name)
	}
	return createIDMap(r), nil
}
```

Comment (Rid) [reply pkg/idtools/idtools_unix.go:275]: I think it makes sense for UIDs to take precedence, as 99% of the time a numerical value is going to be a UID rather than a username.

I was thinking originally to implement separate functions, I wasn't sure if it was too much boilerplate but semantically it looks better to me.

Do you want me to update the commit with your implementation?

Comment (thaJeztah) [reply pkg/idtools/idtools_unix.go:275]: Yes, there's definitely some boilerplating; I initially kept it inline, and, well, it was still boilerplating, so I extracted it to separate functions.

Definitely feel free to copy my code (check if I didn't make a mistake, as it was a quick write up 😅)

**Comment by Rid** [comment]
@thaJeztah Updated, PTAL.

**Comment by Rid** [comment]
Ping @thaJeztah, are we able to merge this and get it into the next release? I hate to push but we really need this to upgrade our production environment. 😇

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by tiborvass — APPROVED** [review]

**Review by cpuguy83 — COMMENTED** [review]
@tiborvass mentioned we should have a test for this.
