### PR TITLE
Change root_maxkeys

### LINKED ISSUE #22865: oci runtime error: could not synchronise with container process: could not create session key: disk quota exceeded
Output of docker version:
```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:20:46 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:20:46 2016
 OS/Arch:      linux/amd64
```

Output of docker info:

```
# docker info
Containers: 555
 Running: 197
 Paused: 0
 Stopped: 358
Images: 109
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1242
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 7 (wheezy)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.324 GiB
Name: e2e-test-dawnchen-minion-18ah
ID: UZMP:J3YN:4AHS:RHBP:SSQH:EKFD:PRQR:HGFN:DRPL:JWZR:RJZL:TEQR
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

Additional environment details (AWS, VirtualBox, physical, etc.):

Just a standard Kubernetes node with docker 1.11.1

Steps to reproduce the issue:

I just simply run the command and quickly hit the cap (~200)
```
for i in {1..500}; do echo $i; docker run -d --name container$i gcr.io/google_containers/pause:2.0; done
```
The error message:

```
1
410d715441504b1e93d77cdec531b338631fcafd637215376df2e8e65d27484e
...
ec5255dc7d1b69624f9f3cc4687708286cc7aefb6b3cd32024d0e41701678337
177
ab99e85ac7b67204ba0c3ff0214dd319bd79fcb06285925c936614a43aa34416
178
dfddfc1ac3bc43625616677385ad68137295af69bfd7274691448476f4cbe675
179
741e2d5708b95469afa65967fafaaf04175ae792eaf6fb3284a5209dcfd71a1c
180
90242513e32aa465ce8fe0df5ab79a0bcd3af4cb32723470f589bff943748c30
181
d77c7e9f06724b1aee0e98f587dba04212a7449723786c5ea7a5bdf623896a38
182
e5631849be2cbe9ced9d463cd00267f8185a9df776f40e9015825a899f755028
docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: could not create session key: disk quota exceeded".
183
e542d7ed3cdfe61add072d47abc23f41f2386ea4df82491415c76cb4ed168326
docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: could not create session key: disk quota exceeded".
184
cc6034b216e191242dfa825d37c5b514ff5133e26dc00c3fa1ea8c6b9fbb5871
docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: could not create session key: disk quota exceeded".
185
53c0b3d65d9f1b6d87cd385cf7d90d79983b518dd4f5d57779e615e9a23d4220
docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: could not create session key: disk quota exceeded".
186
8f74f50ea15dee4dd286189de828ec2333644e1552d5436976ad0e458da5604d
docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: could not create session key: disk quota exceeded".
187
a7ed9ce29299e70414390490b4f8c103b284d12ef7e85d20efa182211b356a1f
docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: could not create session key: disk quota exceeded".
...
500
237e185ab8b5b0774b09c058bed74f0331da8a1c999ec614bac69ad98106bf77
docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: could not create session key: disk quota exceeded".
```

I believe we are hitting at this issue: https://github.com/opencontainers/runc/issues/726, but an attempt solution (https://github.com/opencontainers/runc/pull/727) was closed and the suggestion is the issue should be handled at the higher layer, which I believe it should be docker engine here.

### PR DESCRIPTION
**Pull request by crosbymichael**
Fixes #22865 

Most modern distros have the limit for the maximum root keys at 1000000
but some do not.  Because we are creating a new key for each container
we need to bump this up as the older distros are having this limit at
200.

Using 1000000 as the limit because that is that most distros are setting
this to now.  If someone has this value configured over that we do not
change it.

Signed-off-by: Michael Crosby crosbymichael@gmail.com

### CODE REVIEW

File: daemon/keys.go [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+)
+
+// ModifyRootKeyLimit checks to see if the root key limit is set to
+// atleast 1000000.
+func ModifyRootKeyLimit() error {
+	value, err := readRootKeyLimit()
+	if err != nil {
+		return err
+	}
+	if value < rootKeyLimit {
```
Comment (cyphar) [inline daemon/keys.go]: @crosbymichael I don't like this, because we're changing global distribution policy. There's almost certainly some side-effects -- I'd prefer if we made the keyring joining optional (as you mentioned in opencontainers/runc#818).

Comment (crosbymichael) [inline daemon/keys.go]: optional but default so we still need something like this .

**Comment by crosbymichael** [comment]
@justincormack what do you think about doing this change?

**Comment by justincormack** [comment]
I wonder if the rpm or deb for the affected distros could have a file in
`/etc/sysctl.d/dockerd` instead? Plus docs for people doing installs
themselves and a warning? That seems the right place really, I don't really
like just changing it at startup much either, although there are precedents
(changing max file descriptors).

**Comment by cyphar** [comment]
@justincormack Changing max file descriptors isn't a global option. The root key limit _is_ a global option. We'd probably be fine with packaging an `/etc/sysctl.d/docker` for SUSE (though we'd have to see what maintenance thinks about it).

**Comment by justincormack** [comment]
Yes true, it is overriding policy set for our process though because we are
root and can, which I also don't like that much, even if it just affects us.

**Comment by crosbymichael** [comment]
We change global network options at boot.

**Comment by crosbymichael** [comment]
What is a better alternative then?  I'm not sure i see it being too big of a problem because other distros are shipping with these limits, it seems like something is just being overlooked.  What if we only bump with from 200 to something like 1024 and provide a flag on the daemon to change it? 

`dockerd --root-key-limit 2048`

**Comment by thaJeztah** [comment]
Alternatively, we could output a warning when running `docker info`, providing the instructions to set this value (like we do for other features not being available / set)?

**Comment by justincormack** [comment]
Yes, lets just do this, the other options are worse. LGTM.

File: daemon/keys.go [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+	"strings"
+)
+
+const (
+	rootKeyFile  = "/proc/sys/kernel/keys/root_maxkeys"
+	rootKeyLimit = 1000000
+)
+
+// ModifyRootKeyLimit checks to see if the root key limit is set to
+// atleast 1000000.
```
Comment (justincormack) [inline daemon/keys.go]: missing a space "at least"

File: daemon/keys.go (hunk 1 above)
Comment (justincormack) [inline daemon/keys.go]: Basically the kernel shipped with the wrong policy and fixed it, but old distros won't change, so we should just fix it.

**Comment by crosbymichael** [comment]
Modified this to also update the maxbytes for the root keys because you need both.  The multiplier is a common 25 bytes per key

**Comment by justincormack** [comment]
I think we can move this to code review as i was the only person unsure and I changed my mind...

**Comment by justincormack** [comment]
LGTM when green

**Comment by crosbymichael** [comment]
green

**Comment by jfrazelle** [comment]
looks good to me

File: daemon/keys.go [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+	"strconv"
+	"strings"
+)
+
+const (
+	rootKeyFile   = "/proc/sys/kernel/keys/root_maxkeys"
+	rootBytesFile = "/proc/sys/kernel/keys/root_maxbytes"
+	rootKeyLimit  = 1000000
+	// it is standard configuration to allocate 25 bytes per key
+	rootKeyByteMultiplyer = 25
```
Comment (thaJeztah) [inline daemon/keys.go]: nit: s/rootKeyByteMultiplyer/rootKeyByteMultiplier/ ?

**Comment by thaJeztah** [comment]
one nit, but LGTM otherwise

**Comment by crosbymichael** [comment]
@thaJeztah fixed

**Comment by mlaventure** [comment]
experimental is actually :green_heart: (that false reporting should be fixed by #24002)

**Comment by thaJeztah** [comment]
you're right, let's merge

**Comment by thaJeztah** [comment]
LOL; looks like 1000000 became a magic number in this repo

magic_number

There's a commit that starts with `1000000`, which matches the short commit SHA prefix that's currently used (7 chars).

magic_commit


The full commit SHA is `10000004a7e6cd43ad57c5f7e4165fa867379555`, and fun thing is that it's NOT in our repository; it's somewhere in a fork :joy: (I have not yet found which fork it is)

- Original commit in this repo is; https://github.com/moby/moby/commit/722d477bc6bc3a8e032c44c63a962d79b5c948d3
- Forked commit is https://github.com/moby/moby/commit/10000004a7e6cd43ad57c5f7e4165fa867379555
