### PR TITLE
libnetwork/networkdb: prioritize local table broadcasts over event rebroadcasts

### LINKED ISSUE #50089: Flaky test: libnetwork/networkdb.TestNetworkCRUDTableEntries
### Description

```
=== Failed
=== FAIL: github.com/docker/docker/libnetwork/networkdb TestNetworkDBCRUDTableEntries (8.20s)
    networkdb_test.go:315: Entry existence verification test failed for node2(ccbf4238b23d)
```

My improvements to NetworkDB have not been sufficient to squash all the flakiness, apparently.

### Reproduce

If I knew I would have fixed it already.

Seen on windows-2022 and Linux CI. It's not platform-specific.

### Expected behavior

_No response_

### docker version

```bash
N/A
```

### docker info

```bash
N/A
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by corhere**
**- What I did**
- Fixed #50089 

**- How I did it**
The flaky TestNetworkDBCRUDTableEntries only waits long enough for a handful of gossip cycles to execute before it asserts that the entries owned by one node exist on the other nodes. It does not wait long enough for a bulk-sync to be performed between the nodes. The test therefore asserts, effectively, that gossip is sufficient to reliably converge in a lossless network scenario. The flaky test failures are always due to the CREATE event for a single table entry not being propagated through gossip. The stats and debug logs (not committed to this PR for being very spammy with a low signal:noise ratio) revealed that when the test flakes, the CREATE event for the offending entry was enqueued but never received by the other node and the owning node's queue is holding a large number of messages. Rebroadcasts for messages received from other nodes are delaying the broadcasting of the local node's messages.

Improve the convergence rate of NetworkDB by preferentially broadcasting event messages for entries owned by the local node before rebroadcasting received messages. Enqueue the messages for rebroadcasting into a separate queue which is only pulled from if there is space left over in the gossip packet after filling it with local event messages.

**- How to verify it**
```console
$ go test -count=100 -run CRUDTableEntries -failfast ./libnetwork/networkdb
```

**- Human readable description for the release notes**

```markdown changelog
- Improve the convergence rate of NetworkDB, part of the management plane for overlay networking, after bursts of updates.
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: libnetwork/networkdb/cluster.go [hunk 1]
```diff
@@ -461,21 +461,20 @@ func (nDB *NetworkDB) gossip() {
...
 		// Collect stats and print the queue info, note this code is here also to have a view of the queues empty
 		network.qMessagesSent.Add(int64(len(msgs)))
 		if printStats {
 			msent := network.qMessagesSent.Swap(0)
-			log.G(context.TODO()).Infof("NetworkDB stats %v(%v) - netID:%s leaving:%t netPeers:%d entries:%d Queue qLen:%d netMsg/s:%d",
+			log.G(context.TODO()).Infof("NetworkDB stats %v(%v) - netID:%s leaving:%t netPeers:%d entries:%d Queue qLen:%d+%d netMsg/s:%d",
 				nDB.config.Hostname, nDB.config.NodeID,
-				nid, network.leaving, broadcastQ.NumNodes(), network.entriesNumber.Load(), broadcastQ.NumQueued(),
+				nid, network.leaving, network.tableBroadcasts.NumNodes(), network.entriesNumber.Load(),
+				network.tableBroadcasts.NumQueued(), network.tableRebroadcasts.NumQueued(),
```
Comment (robmry) [inline libnetwork/networkdb/cluster.go:480]: `network.tableBroadcasts` is checked above, but can `network.tableRebroadcasts` be nil here?

JoinNetwork sets up both before adding a `network` to `networkNodes`. So, if one is non-nil, the other is also non-nil? (In which case, worth a comment if not an extra nil check?)

File: libnetwork/networkdb/networkdb.go [hunk 2]
```diff
@@ -146,7 +146,7 @@ type network struct {
 
 	// The broadcast queue for table event gossip. This is only
 	// initialized for this node's network attachment entries.
-	tableBroadcasts *memberlist.TransmitLimitedQueue
+	tableBroadcasts, tableRebroadcasts *memberlist.TransmitLimitedQueue
```
Comment (robmry) [inline libnetwork/networkdb/networkdb.go]: Could update the comment to explain why two queues are necessary?

File: libnetwork/networkdb/cluster.go (hunk 1 above)
Comment (corhere) [reply libnetwork/networkdb/cluster.go:480]: I dropped the nil-checks entirely. Neither field can be nil if the network pointer is non-nil.

Comment (robmry) [reply libnetwork/networkdb/cluster.go:480]: I wondered that - but networks are constructed here too ... https://github.com/moby/moby/blob/270a4d41dc1a127802e041415c3c82b0bfc2e559/libnetwork/networkdb/delegate.go#L137-L141

So, I think it's neither or both are non-nil.

File: libnetwork/networkdb/networkdb.go (hunk 2 above)
Comment (corhere) [reply libnetwork/networkdb/networkdb.go]: Done

File: libnetwork/networkdb/cluster.go (hunk 1 above)
Comment (corhere) [reply libnetwork/networkdb/cluster.go:480]: What the?! Ewww.

Comment (corhere) [reply libnetwork/networkdb/cluster.go:480]: The networks in `nDB.networks[nDB.config.NodeID]` (read: thisNodeNetworks) are guaranteed to have the `tableBroadcasts` and `tableRebroadcasts` fields initialized. Networks in the maps for other nodes are guaranteed to have them nil. The places I removed the nil-guards are always using thisNodeNetworks, so my changes are sound aside from the silly mistake I made in one place.

That all said, I am not happy that a `*network` for this node is cannot be substituted for a `*network` for another node. I'm going to do a touch of refactoring to clean this up.

Comment (robmry) [reply libnetwork/networkdb/cluster.go:480]: Sounds good!

There's a `q == nil` in the new `getBroadcasts` that could probably go too.

Comment (robmry) [reply libnetwork/networkdb/cluster.go:480]: Oh, except there's a nil pointer deref in the unit tests.

**Review by robmry — APPROVED** [review]

**Review by akerouanton — APPROVED** [review]

**Comment by vvoland** [comment]
No backport for 28.3.2 - we can backport it for the new release along with https://github.com/moby/moby/pull/50344
