### PR TITLE
fix shm size handling

### LINKED ISSUE #18172: --shm-size: inconsistencies
```
$ docker run -d ubuntu top
09606c3c2e31df6c9c5c67783ef2d950c8ac836d9b734329cb6eddf0eb425b1a
$ docker inspect 096 | grep -i shm
        "ShmSize": 67108864,
```
So far, so good CLI side...
```
$ docker run -d --shm-size="-1" ubuntu top
docker: --shm-size: invalid SHM size.
See 'docker run --help'.
```
`-1` is not even parseable by `units.RAMInBytes` so we get `invalid SHM size.`. This can be good maybe.
```
docker run -d --shm-size=0 ubuntu top
docker: --shm-size: SHM size must be greater than 0 . You specified: 0 .
See 'docker run --help'.
```
With `0`, `RAMInBytes` passes but `0` is not valid. We are hitting https://github.com/docker/docker/blob/master/runconfig/parse.go#L211 and the condition cannot be clearly catch the strictly `< 0` because it's catched by the error in `RAMInBytes` two lines above..

So the CLI applies the default `64MB` only if the flag is not passed. It will error out (with different errors?!) if the value is invalid. 

API side
```
$ curl -X POST -H "Content-Type: application/json" -d '{"Image":"busybox", "Cmd": "mount", "HostConfig":{"ShmSize": -1}}' http://localhost:2375/containers/create
{"Id":"975c16bf9e3fd94eb9afb1f7737f1c78bc90ff4d0939dc7090e5b979d1277923","Warnings":null}
$ docker start -i 975 | grep shm
shm on /dev/shm type tmpfs (rw,seclabel,nosuid,nodev,noexec,relatime,size=65536k)
```
On the API I can pass `-1` and it won't bother about the fact it's invalid so it applies the default `64MB`. Should it error out instead much like on the cli?
Plus:
```
$ docker inspect 7c125 | grep -i shm
        "ShmSize": -1,
```
Inspect shows an shm size of `-1` which seems incorrect..(to me)
Same goes if I provide `0` to the API, inspect will report `0` and `64MB` will be applied (instead of erroring out)

Lastly, if you don't provide an HostConfig at all it will default to `64MB` and report `64MB` in inspect :
```
$ curl -X POST -H "Content-Type: application/json" -d '{"Image":"busybox", "Cmd": "mount"}' http://localhost:2375/containers/create
{"Id":"975c16bf9e3fd94eb9afb1f7737f1c78bc90ff4d0939dc7090e5b979d1277923","Warnings":null}
$ docker start -i 975 | grep shm
shm on /dev/shm type tmpfs (rw,seclabel,nosuid,nodev,noexec,relatime,size=65536k)
$ docker inspect 975 | grep -i shm
        "ShmSize": 67108864,
```
(I'm sure I've even forgot something to report lol, but we'll see)

I think validation should be either the same for cli and API or API side only.. (much like we're currently doing with things in `verifyPlatformContainerSettings`, which will save the overwritten value so inspect is consistent)
ping @LK4D4 @calavera @duglin @cpuguy83  WDYT we should go with this? is the current behavior ok? I'll fix it if we find a common ground and this is not ok.

### PR DESCRIPTION
**Pull request by runcom**
Much like `MemorySwappiness` is currently working to have a default..
Added a bunch of test to make sure default is working correctly

Fix #18172

Signed-off-by: Antonio Murdaca runcom@redhat.com

### CODE REVIEW

File: daemon/container_unix.go [hunk 1]
```diff
@@ -1358,11 +1358,16 @@ func (daemon *Daemon) setupIpcDirs(container *Container) error {
 			return err
 		}
 
-		// When ShmSize is 0 or less, the SHM size is set to 64MB.
-		if container.hostConfig.ShmSize <= 0 {
-			container.hostConfig.ShmSize = 67108864
+		// this is to handle an omitted HostConfig passed to the API which won't hit
+		// adaptContainerSettings in daemon_unix.go and won't have a default ShmSize
```
Comment (thaJeztah) [inline daemon/container_unix.go]: can you add back a mention that we're setting it to `64MB` by default? prevents people from scratching their heads what the magic number `67108864` is :smile:

Comment (runcom) [inline daemon/container_unix.go]: Yup will do

**Comment by runcom** [comment]
ping @calavera @cpuguy83 @LK4D4

**Comment by estesp** [comment]
Slightly related to @thaJeztah's comment, I wonder if it would make sense to have a constant for `DEFAULT_SHM_SIZE` == 64MB in bytes. Pretty minor as maybe there isn't a great place that all 3 locations where you utilize it could reference it (+ testcases I guess), but that way if it ever needed to change it would be less impact across the code..

Other than that, which I'm not going to be hung up on, LGTM..

**Comment by runcom** [comment]
@estesp I thought so much about that but couldn't figure out where to put it at then end :/ if anyone has suggestions pls...

**Comment by thaJeztah** [comment]
Yup, I saw we actually had a constant in another location for that, but agreed, not sure what a logical place would be to have it in a single place :/

**Comment by cpuguy83** [comment]
How about runconfig.DefaultSHMSize?

**Comment by thaJeztah** [comment]
perhaps a separate `runconfig.defaults` or would that be cumbersome (thinking out loud®)

**Comment by runcom** [comment]
> How about runconfig.DefaultSHMSize?

+1 to this, I'll update the code and see how it goes

**Comment by runcom** [comment]
@cpuguy83 @estesp @thaJeztah updated with a const in runconfig

**Comment by vdemeester** [comment]
@runcom needs a rebase :sweat:

**Comment by runcom** [comment]
rebased

File: runconfig/parse.go [hunk 2]
```diff
@@ -42,6 +42,9 @@ var (
 	ErrConflictNetworkExposePorts = fmt.Errorf("Conflicting options: --expose and the network mode (--net)")
 )
 
+// DefaultSHMSize is the default size of the SHM which will be mounted in the container
+const DefaultSHMSize int64 = 67108864
```
Comment (thaJeztah) [inline runconfig/parse.go]: I'd suggest to mention the `64MB` here (so that people don't have to calculate what this number is), and remove it in other places (will add some comments)

File: api/server/router/local/image.go [hunk 3]
```diff
@@ -357,7 +357,12 @@ func (s *router) postBuild(ctx context.Context, w http.ResponseWriter, r *http.R
 	buildConfig.ForceRemove = httputils.BoolValue(r, "forcerm")
 	buildConfig.MemorySwap = httputils.Int64ValueOrZero(r, "memswap")
 	buildConfig.Memory = httputils.Int64ValueOrZero(r, "memory")
-	buildConfig.ShmSize = httputils.Int64ValueOrZero(r, "shmsize")
+	// default 64MB if not provided at all
```
Comment (thaJeztah) [inline api/server/router/local/image.go]: `Set to default if not provided` (or remove, because `httputils.Int64ValueOrDefault()` may be descriptive enough on its own)

File: daemon/container_unix.go [hunk 4]
```diff
@@ -1358,11 +1358,17 @@ func (daemon *Daemon) setupIpcDirs(container *Container) error {
...
+		// of 64MB
```
Comment (thaJeztah) [inline daemon/container_unix.go]: can be removed

File: daemon/daemon_unix.go [hunk 5]
```diff
@@ -131,6 +131,11 @@ func (daemon *Daemon) adaptContainerSettings(hostConfig *runconfig.HostConfig, a
 		// By default, MemorySwap is set to twice the size of Memory.
 		hostConfig.MemorySwap = hostConfig.Memory * 2
 	}
+	// Make sure the default ShmSize if 64MB if none is provided
```
Comment (thaJeztah) [inline daemon/daemon_unix.go]: `Use default ShmSize is set if none is provided`?

**Comment by runcom** [comment]
@thaJeztah thanks, updated

File: api/client/build.go [hunk 6]
```diff
@@ -211,15 +211,12 @@ func (cli *DockerCli) CmdBuild(args ...string) error {
 		}
 	}
 
-	var shmSize int64 = 67108864 // initial SHM size is 64MB
+	shmSize := runconfig.DefaultSHMSize
```
Comment (cpuguy83) [inline api/client/build.go]: Wondering, shouldn't this be empty on the client when not set and set the default on the daemon side?

Comment (runcom) [inline api/client/build.go]: updated

Comment (runcom) [inline api/client/build.go]: I also think I can move the const to daemon or container as well since it isn't used in runconfig anymore

**Comment by estesp** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Comment by runcom** [comment]
I'll submit a followup because I moved defaultSHMSize to daemon and removed the dependency on knowing the default SHM size inside the server/router :/ you guys were too fast lol

**Comment by estesp** [comment]
ha..no, you were too slow!! :) :) :)

**Comment by runcom** [comment]
ouch lol
