### PR TITLE
daemon: set docker0 subpool as the IPAM pool

### LINKED ISSUE #45356: docker fails to start after upgrade to 23.0.4
### Description

I updated to docker-ce `5:23.0.4-1~debian.11~bullseye` (tested with a fresh installation) and now dockerd fails to start:
```
failed to start daemon: Error initializing network controller: Error creating default "bridge" network: failed to parse pool request for address space "LocalDefault" pool "" subpool "100.64.0.0/26": Invalid Address SubPool
```
It worked with the previous version (`5:23.0.3-1~debian.11~bullseye`).

My `/etc/docker/daemon.json` contains:
```json
{
  "fixed-cidr": "100.64.0.0/26"
}
```

I suspect this is caused by #45246.

### Reproduce

Install docker as explained in the issue description and `systemctl start docker`.

### Expected behavior

normal docker startup

### docker version

```bash
Client: Docker Engine - Community
 Version:           23.0.4
 API version:       1.42
 Go version:        go1.19.8
 Git commit:        f480fb1
 Built:             Fri Apr 14 10:32:17 2023
 OS/Arch:           linux/amd64
 Context:           default
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
errors pretty printing info
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by akerouanton**
**- What I did**

Fix a regression introduced by:

- https://github.com/moby/moby/pull/44827

Since cc19eba (backported to v23.0.4), the PreferredPool for docker0 is set only when the user provides the bip config parameter or when the default bridge already exist. That means, if a user provides the fixed-cidr parameter on a fresh install or reboot their computer/server without bip set, dockerd throw the following error when it starts:

> failed to start daemon: Error initializing network controller: Error creating default "bridge" network: failed to parse pool request for address space "LocalDefault" pool "" subpool "100.64.0.0/26": Invalid Address SubPool

I added a new integration test to `integration-cli` to make sure we won't re-introduce this regression.

Closes #45356.

**- How to verify it**

Execute the daemon with the config provided in the original issue reporting this regression. And check if CI is green.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by corhere — CHANGES_REQUESTED** [review]
Looks like the new integration test breaks other integration tests

File: libnetwork/drivers/bridge/setup_device.go [hunk 1]
```diff
@@ -16,8 +16,10 @@ import (
 // SetupDevice create a new bridge interface/
 func setupDevice(config *networkConfiguration, i *bridgeInterface) error {
 	// We only attempt to create the bridge when the requested device name is
-	// the default one.
-	if config.BridgeName != DefaultBridgeName && config.DefaultBridge {
+	// the default one. The env var DOCKER_TEST_CREATE_DEFAULT_BRIDGE should be
+	// used only for test purpose.
+	if _, ok := os.LookupEnv("DOCKER_TEST_CREATE_DEFAULT_BRIDGE"); !ok &&
```
Comment (thaJeztah) [inline libnetwork/drivers/bridge/setup_device.go:21]: From our earlier conversation on Slack; could we use the env-var to override the _name_ of the bridge to use (i.e., if it's set (non-empty value) to override `DefaultBridgeName`, and consider it to be the default bridge name)?

File: integration/daemon/daemon_test.go [hunk 2]
```diff
@@ -400,3 +401,23 @@ func testLiveRestoreVolumeReferences(t *testing.T) {
...
+	}()
+
+	defer deleteInterface(bridgeName)
+	d.StartWithBusybox(t, "--bridge", bridgeName, "--fixed-cidr", "192.168.130.0/24")
+}
+
+func deleteInterface(ifName string) {
+	icmd.RunCommand("ip", "link", "delete", ifName)
+	icmd.RunCommand("iptables", "-t", "nat", "--flush")
+	icmd.RunCommand("iptables", "--flush")
```
Comment (corhere) [inline integration/daemon/daemon_test.go:422]: The results of running these commands should probably be asserted on, at least so that any nonzero exits are logged along with the failing commands' output.

**Review by corhere — APPROVED** [review]

File: integration/daemon/daemon_test.go (hunk 2 above)
Comment (akerouanton) [reply integration/daemon/daemon_test.go:422]: I'm not sure if that's really needed. `ip link delete` would fail if the daemon didn't start properly. OTOH if those commands don't run properly they could leave the host in such a state that some tests could become flakes :thinking:

**Review by cpuguy83 — APPROVED** [review]

**Review by cpuguy83 — CHANGES_REQUESTED** [review]
LGTM just needs an update to at least log error messages from ip/iptables commands.

**Review by vvoland — APPROVED** [review]

**Review by thaJeztah — APPROVED** [review]
LGTM

@cpuguy83 ptal

**Review by cpuguy83 — APPROVED** [review]
