### PR TITLE
Ensure --hostname is valid

### LINKED ISSUE #20371: --hostname does not properly validate the specified hostname
---hostname does not check for the _ character which is not allowed in hostnames. 
See https://en.wikipedia.org/wiki/Hostname

This leads to hard to find issues, because a service inside the container might not work properly. 
I just ran into an issue with an old version of jboss that does validate the hostname, but only shows a relative generic error message. Something like "There might be an incorrect character or wrong port used"

The hostname specified should be validated. 
e.g --hostname bla_bla should lead to an error. 

$ docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:34:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:34:50 2016
 OS/Arch:      linux/amd64

$ docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 718
Server Version: 1.10.0
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.0-1.el7.elrepo.x86_64
Operating System: Red Hat Enterprise Linux Client 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.3 GiB
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

### PR DESCRIPTION
**Pull request by AndrewGuenther**
Validates whether the given hostname is RFC 1123
(https://tools.ietf.org/html/rfc1123) compliant.

Fixes #20371

Signed-off-by: Andrew Guenther guenther.andrew.j@gmail.com

### CODE REVIEW

**Comment by AndrewGuenther** [comment]
I have not yet added additional unit tests because I first want to ensure that this is the correct place to put this check. See the original issue for discussion.

**Comment by aanm** [comment]
Hmm what about in the server? https://github.com/docker/docker/blob/master/api/server/router/container/container_routes.go

**Comment by AndrewGuenther** [comment]
@aanm This is on the server. `runconfig` is what the API calls to validate the request params.

**Comment by aanm** [comment]
@AndrewGuenther oh cool, I thought that was from the client side.

**Comment by icecrime** [comment]
Win2lin job is hitting the known race condition fixed in #20753.

**Comment by calavera** [comment]
@AndrewGuenther can you please add tests :wink:

**Comment by AndrewGuenther** [comment]
@calavera I'd be happy to! I just wanted to get some confirmation that this is the right place to do this check first.

**Comment by Fredjet** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  fredjet15@gmail.com
    Domain ventureacceleration.com has exceeded the max emails per hour (62/50 (124%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:60412 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by eaglepeak.ovasp.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1aarpj-0008JF-4q
	for fred@ventureacceleration.com; Tue, 01 Mar 2016 16:27:55 -0500
Date: Tue, 01 Mar 2016 13:26:58 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1456867618;
	bh=oyRMuIIO71DtdqIMlF5naFpED+dpNzniPNDLIbXC6YI=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=zWHQxpKQ5pADR/FYtPZbiGvTEvmSA2WPQwkUgiBn/pbSQSmXhN9Elrd5+/OhDhdXK
	 aceefav3PRqj4xwr7OkBDaehtSOK0S5vYLTOQUEkUphdDQbE3H04nLVtzyx86o4F3G
	 2b0XLV50PhL+lw915euJGpcUSuKa3yQXhsoqZJm4=

**Comment by thaJeztah** [comment]
@AndrewGuenther looks like you did a merge, not a rebase; can you rebase to get rid of the merge commit?

**Comment by AndrewGuenther** [comment]
@thaJeztah yeah, I accidentally hit the nasty "Update branch" button. I'll fix it once I add the unit test commit.

**Comment by thaJeztah** [comment]
Oh! That one is really really nasty, I hit it once as well

**Comment by calavera** [comment]
LGTM

File: runconfig/opts/parse.go [hunk 1]
```diff
@@ -248,6 +249,12 @@ func Parse(cmd *flag.FlagSet, args []string) (*container.Config, *container.Host
 		hostname = parts[0]
 		domainname = parts[1]
 	}
+	if hostname != "" {
+		matched, _ := regexp.MatchString("^(([[:alnum:]]|[[:alnum:]][[:alnum:]\\-]*[[:alnum:]])\\.)*([[:alnum:]]|[[:alnum:]][[:alnum:]\\-]*[[:alnum:]])$", hostname)
```
Comment (thaJeztah) [inline runconfig/opts/parse.go]: Perhaps we should add a comment here, explaining what RFC we're validating against?, e.g.

    // Validate if the given hostname is RFC 1123 (https://tools.ietf.org/html/rfc1123) compliant.

File: runconfig/opts/parse_test.go [hunk 2]
```diff
@@ -385,11 +385,29 @@ func TestParseWithMemorySwap(t *testing.T) {
...
+		"hostname":    "hostname",
+		"host-name":   "host-name",
+		"hostname123": "hostname123",
+		"123hostname": "123hostname",
+	}
+	invalidHostnames := map[string]string{
+		"^hostname": "invalid hostname format for --hostname: ^hostname",
+		"hostname%": "invalid hostname format for --hostname: hostname%",
+		"host&name": "invalid hostname format for --hostname: host&name",
+		"-hostname": "invalid hostname format for --hostname: -hostname",
```
Comment (thaJeztah) [inline runconfig/opts/parse_test.go]: Looking at the issue this PR is resolving, I don't see any host names containing an underscore here? Original issue was (https://github.com/docker/docker/issues/20371);

> hostname does not check for the _ character which is not allowed in hostnames.

Comment (AndrewGuenther) [inline runconfig/opts/parse_test.go]: Wow, that a huge fail on my part! Great catch. I'll add that and update.

**Comment by thaJeztah** [comment]
ping @AndrewGuenther have you had time to look at those tests?

**Comment by AndrewGuenther** [comment]
@thaJeztah I will tonight or tomorrow. I was on vacation this past weekend and didn't got a chance.

**Comment by thaJeztah** [comment]
No worries, thanks!

**Comment by AndrewGuenther** [comment]
@thaJeztah Added a test case. Builds seem to be failing and they don't seem related to my change, but it is the most flakes I've ever seen on a PR, so if I've done something suspect, let me know.

**Comment by thaJeztah** [comment]
thanks, LGTM

**Comment by calavera** [comment]
It looks like this is failing building on Windows, but I don't have any idea why:

```
18:37:01 Building: bundles/1.11.0-dev/binary/docker-1.11.0-dev.exe
18:37:12 # github.com/docker/docker/runconfig/opts
18:37:12 runconfig\opts\parse.go:245: undefined: hostname
18:37:12 runconfig\opts\parse.go:246: undefined: hostname
18:37:12 runconfig\opts\parse.go:248: undefined: hostname
```

that file is shared between platforms, @jhowardmsft any clues?

**Comment by calavera** [comment]
Different Go version? the windows binaries build with Cross platform on linux:

```
08:16:11 Building: bundles/1.11.0-dev/cross/windows/amd64/docker-1.11.0-dev.exe
08:17:17 Created binary: bundles/1.11.0-dev/cross/windows/amd64/docker-1.11.0-dev.exe
08:17:17 Building: bundles/1.11.0-dev/cross/windows/386/docker-1.11.0-dev.exe
08:17:40 Created binary: bundles/1.11.0-dev/cross/windows/386/docker-1.11.0-dev.exe
08:17:40 
```

**Comment by jhowardmsft** [comment]
That's a weird one! Restarting and will investigate (I'm trying to heal those broken CI servers right now)

**Comment by calavera** [comment]
I don't know what's going on, but it looks like the error is not the same anymore. The one in this build is more expected:

https://jenkins.dockerproject.org/job/Docker-PRs-WoW-TP4/3244/console

**Comment by icecrime** [comment]
@jhowardmsft Are you ok with us merging this?

**Comment by icecrime** [comment]
I don't see anything Windows related in this changeset, so I'm going to go ahead and merge :fearful: I hope that's ok :innocent:

**Comment by icecrime** [comment]
Well, I broke master :crying_cat_face:
