### PR TITLE
Make `docker pull` detect plugin content and error out.

### LINKED ISSUE #23752: [1.12.x] `docker pull` for plugin should fail with a human-friendly error
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd-unsupported
 Built:        Fri Jun 17 21:12:28 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd-unsupported
 Built:        Fri Jun 17 21:12:28 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0-rc2
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: default
Default Runtime: default
Security Options: apparmor seccomp
Kernel Version: 4.4.0-22-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.795 GiB
Name: hoge
ID: 5HJM:SQPO:3NEM:ZYX7:3LME:WIHB:E3BN:RNMZ:6K4F:JCQ6:UY2Z:CR26
Docker Root Dir: /mnt/disk2/docker3
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Steps to reproduce the issue:**
Do `docker pull tiborvass/no-remove`

**Describe the results you received:**
```
$ docker pull tiborvass/no-remove
Using default tag: latest
latest: Pulling from tiborvass/no-remove
1c482de4cb9f: Pull complete 
unexpected EOF
```

Plus the daemon panics (and recovered, so this is _not_ critical)
```
http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 137 [running]:
net/http.(*conn).serve.func1(0xc820323700)
        /usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0x1a56920, 0xc82000e090)
        /usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/docker/docker/distribution.(*v2Puller).pullSchema2(0xc8203c0960, 0x7f1f8fc0a2a0, 0xc820e78740, 0x7f1f8fc1b388, 0xc820d710b0, 0xc820967830, 0xc820df48c0, 0x47, 0xc820d

        /usr/src/docker/.gopath/src/github.com/docker/docker/distribution/pull_v2.go:585 +0xca4
github.com/docker/docker/distribution.(*v2Puller).pullV2Tag(0xc8203c0960, 0x7f1f8fc0a2a0, 0xc820d8e380, 0x7f1f8fc1b388, 0xc820d710b0, 0x2, 0x0, 0x0)
        /usr/src/docker/.gopath/src/github.com/docker/docker/distribution/pull_v2.go:378 +0xd8d
github.com/docker/docker/distribution.(*v2Puller).pullV2Repository(0xc8203c0960, 0x7f1f8fc0a2a0, 0xc820d8e380, 0x7f1f8fc1b388, 0xc820d710b0, 0x0, 0x0)
        /usr/src/docker/.gopath/src/github.com/docker/docker/distribution/pull_v2.go:86 +0xdb
github.com/docker/docker/distribution.(*v2Puller).Pull(0xc8203c0960, 0x7f1f8fc0a2a0, 0xc820d8e380, 0x7f1f8fc1b388, 0xc820d710b0, 0x0, 0x0)
        /usr/src/docker/.gopath/src/github.com/docker/docker/distribution/pull_v2.go:67 +0x283
github.com/docker/docker/distribution.Pull(0x7f1f8fc0a2a0, 0xc820d8e380, 0x7f1f8fc1b388, 0xc820d710b0, 0xc8207e5ce0, 0x0, 0x0)
        /usr/src/docker/.gopath/src/github.com/docker/docker/distribution/pull.go:138 +0x9ed
github.com/docker/docker/daemon.(*Daemon).pullImageWithReference(0xc8204441a0, 0x7f1f8fc0a2a0, 0xc820d8e380, 0x7f1f8fc1b388, 0xc820d710b0, 0xc820d85980, 0xc8207e5b90, 0x7f1f8fc1

        /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/image_pull.go:102 +0x39c
github.com/docker/docker/daemon.(*Daemon).PullImage(0xc8204441a0, 0x7f1f8fc0a2a0, 0xc820d8e240, 0xc820d86e60, 0x13, 0xc820d7267e, 0x6, 0xc820d85980, 0xc8207e5b90, 0x7f1f8fc1b168

        /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/image_pull.go:44 +0x34c
github.com/docker/docker/api/server/router/image.(*imageRouter).postImagesCreate(0xc820452280, 0x7f1f8fc0a2a0, 0xc820d8e240, 0x7f1f8fbd0d20, 0xc820aceb60, 0xc820d6c380, 0xc820d8

        /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/image/image_routes.go:108 +0xb74
github.com/docker/docker/api/server/router/image.(*imageRouter).(github.com/docker/docker/api/server/router/image.postImagesCreate)-fm(0x7f1f8fc0a2a0, 0xc820d8e240, 0x7f1f8fbd0d
20d85770, 0x0, 0x0)
        /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/image/image.go:43 +0x74
github.com/docker/docker/api/server/router.cancellableHandler.func1(0x7f1f8fc0a2a0, 0xc820d8e240, 0x7f1f8fbd0d20, 0xc820aceb60, 0xc820d6c380, 0xc820d85770, 0x0, 0x0)
        /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/local.go:84 +0x1ed
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x7f1f8fc0a230, 0xc820d858c0, 0x7f1f8fbd0d20, 0xc820aceb60, 0xc820d6c380, 0xc820d85770, 0x0, 0

        /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware/version.go:56 +0x9aa
github.com/docker/docker/api/server/middleware.UserAgentMiddleware.WrapHandler.func1(0x7f1f8fc0a230, 0xc820d857d0, 0x7f1f8fbd0d20, 0xc820aceb60, 0xc820d6c380, 0xc820d85770, 0x0,

        /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware/user_agent.go:45 +0x68e
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7f1f8fbd0d20, 0xc820aceb60, 0xc820d6c380)
        /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:139 +0x138
net/http.HandlerFunc.ServeHTTP(0xc8204656c0, 0x7f1f8fbd0d20, 0xc820aceb60, 0xc820d6c380)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc82000b040, 0x7f1f8fbd0d20, 0xc820aceb60, 0xc820d6c380)
        /usr/src/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc8208103e0, 0x7f1f8fbd0d20, 0xc820aceb60, 0xc820d6c380)
        /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
net/http.serverHandler.ServeHTTP(0xc8203e4080, 0x7f1f8fbd0d20, 0xc820aceb60, 0xc820d6c380)
        /usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820323700)
        /usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2137 +0x44e
```

**Describe the results you expected:**
(example)
```
$ docker pull tiborvass/no-remove
tiborvass/no-remove is a plugin. Please use `docker plugin` instead for installing this plugin.
```

**Additional information you deem important (e.g. issue happens only occasionally):**

- https://hub.docker.com/r/tiborvass/no-remove/ should not show `docker pull` command
- `docker search` should not show plugins? (and there should be `docker plugin search`?)

### PR DESCRIPTION
**Pull request by anusha-ragunathan**
**\- What I did**
Make `docker pull` detect plugin mediatype and error out.
In this process, also add the plugin media type to distribution package.

**\- How I did it**
Detect using manifest config's mediatype.

**\- How to verify it**
docker pull tiborvass/no-remove fails; before this change it panics. 

Signed-off-by: Anusha Ragunathan anusha@docker.com

Fixes #23752

### CODE REVIEW

**Comment by thaJeztah** [comment]
Got a golint failure;

```
19:16:12 ---> Making bundle: validate-lint (in bundles/1.13.0-dev/validate-lint)
19:16:12 Errors from golint:
19:16:12 plugin/distribution/types.go:13:7: exported const DefaultTag should have comment or be unexpected
```

File: distribution/pull_v2.go [hunk 1]
```diff
@@ -32,7 +32,10 @@ import (
 	"golang.org/x/net/context"
 )
 
-var errRootFSMismatch = errors.New("layers from manifest don't match image configuration")
+var (
+	errRootFSMismatch  = errors.New("layers from manifest don't match image configuration")
+	errMediaTypePlugin = errors.New("plugins cannot be pulled in this manner. Use `docker plugin install`")
```
Comment (thaJeztah) [inline distribution/pull_v2.go]: bit unsure about "cannot be pulled in this manner", perhaps 

    invalid manifest type for image. Use `docker plugin install`

but not really satisfied with that one @sfsmithcha perhaps you have a suggestion?

**Comment by thaJeztah** [comment]
Tested this and it resolves the issue I saw, so LGTM (pending vendoring, and possibly better suggestions for the error)

File: distribution/pull_v2.go [hunk 2]
```diff
@@ -356,6 +359,18 @@ func (p *v2Puller) pullV2Tag(ctx context.Context, ref reference.Named) (tagUpdat
 		return false, fmt.Errorf("image manifest does not exist for tag or digest %q", tagOrDigest)
 	}
 
+	_, pl, err := manifest.Payload()
+	if err != nil {
+		return false, err
+	}
+	var m schema2.Manifest
+	if err := json.Unmarshal(pl, &m); err != nil {
```
Comment (tonistiigi) [inline distribution/pull_v2.go]: `if m, ok := manifest.(*schema2.DeserializedManifest); ok  { m.Manifest.Config.MediaType }` ?

File: distribution/pull_v2.go (hunk 1 above)
Comment (sfsmithcha) [inline distribution/pull_v2.go]: What about

    target is a plugin manifest. Use `docker plugin install` to install plugins.

Comment (thaJeztah) [inline distribution/pull_v2.go]: oh, that looks good, thanks

**Comment by tonistiigi** [comment]
> before this change it panics.

We should add some general purpose protection for this as well. Thankfully it doesn't panic the daemon but only the HTTP request. But we should consider anything returned by registry as potentially malicious and always validate it.

**Comment by anusha-ragunathan** [comment]
Vendoring change at https://github.com/docker/distribution/pull/1901

File: distribution/pull_v2.go [hunk 3]
```diff
@@ -356,6 +360,12 @@ func (p *v2Puller) pullV2Tag(ctx context.Context, ref reference.Named) (tagUpdat
 		return false, fmt.Errorf("image manifest does not exist for tag or digest %q", tagOrDigest)
 	}
 
+	if m, ok := manifest.(*schema2.DeserializedManifest); ok {
+		if m.Manifest.Config.MediaType == schema2.MediaTypePluginConfig {
```
Comment (dmcgowan) [inline distribution/pull_v2.go]: I believe only `schema2.MediaTypeConfig` is expected value here. Wondering if we could just throw an error of an expected configuration type if that is not seen. Ping @aaronlehmann

Comment (aaronlehmann) [inline distribution/pull_v2.go]: I think the plugin stuff extends this with an additional media type?

Comment (dmcgowan) [inline distribution/pull_v2.go]: It does, but it has it's own pull method. It is invalid to pull a plugin type here. My preference for the code would be rather than having to have this part of the code know about plugins, just have it check for the configuration types it expects, in this case `schema2.MediaTypeConfig`

Comment (aaronlehmann) [inline distribution/pull_v2.go]: Ah, SGTM

Comment (anusha-ragunathan) [inline distribution/pull_v2.go]: I tried this approach before blacklisting plugins. The problem is that docker pull official Hub images such busybox, python, ubuntu has mediatype set to  "application/octet-stream" and not the expected schema2.MediaTypeConfig ("application/vnd.docker.container.image.v1+json").

https://github.com/docker/distribution/issues/1621 seems relevant.

**Comment by thaJeztah** [comment]
ping @aaronlehmann @dmcgowan what's the status here?

File: distribution/pull_v2.go (hunk 3 above)
Comment (dmcgowan) [inline distribution/pull_v2.go]: If at this point the MediaType could still be `application/octet-stream` I would prefer to update it to `schema2.MediaTypeConfig` explicitly in the code with a comment linking to the issue, then check for `schema2.MediaTypeConfig`. @aaronlehmann would it problematic for verification if we updated this value before the check?

Comment (aaronlehmann) [inline distribution/pull_v2.go]: @dmcgowan: Can you show pseudocode for what you have in mind?

Comment (dmcgowan) [inline distribution/pull_v2.go]:
```
// Treat octet stream as media type config
// see https://github.com/docker/distribution/issues/1621
if m.Manifest.Config.MediaType == "application/octet-stream" {
	m.Manifest.Config.MediaType = schema2.MediaTypeConfig
}
if m.Manifest.Config.MediaType != schema2.MediaTypeConfig {
	return false, errors.New("unsupported configuration type")
}
```

The first part could be anywhere but this would accomplish what I am talking about

Comment (aaronlehmann) [inline distribution/pull_v2.go]: I think that's okay, but I don't understand the benefit of changing it in the deserialized manifest. I don't think it's looked at anywhere else.

Also, are we sure that application/octet-stream is the only incorrect media type?

Comment (anusha-ragunathan) [inline distribution/pull_v2.go]: I dont understand how this hack is better than blacklisting plugin mediatypes.

Comment (dmcgowan) [inline distribution/pull_v2.go]: That we know about. At some point we will have to be restrictive in the supported values. If it fails then we can assess whether it is legitimate and we should make a code change or whether the manifest needs to be recreated. We accept the `application/octet-stream` because we know there were many manifests mistakenly created with it and that at the time when they were created the only supported value is `application/vnd.docker.container.image.v1+json`.

For this change in particular, since now there are multiple possible types, I think it makes sense to define what is supported and have a special case for that one distribution bug.

Comment (dmcgowan) [inline distribution/pull_v2.go]: @anusha-ragunathan to me it more about separation of the code. This code should not be pulling plugins, and it really doesn't even need to know about anything that is a non-image. Having the whitelist would also negate the need of having the `v0` version defined in distribution since the code change can be isolated to the image pull logic.

**Comment by dmcgowan** [comment]
Upstream merged

File: distribution/pull_v2.go (hunk 3 above)
Comment (dmcgowan) [inline distribution/pull_v2.go]: We can make these sort of updates later, I am fine with it like this fo rnow

Comment (anusha-ragunathan) [inline distribution/pull_v2.go]: @dmcgowan: distribution knowing about the plugin mediatype should be okay. Are you concerned purely because it is in v0 and will be okay to include it in distribution once we have a stable v1 manifest spec? Also, I agree that code separation is ideal but the above workaround to detecting the container image mediatype feels hackish. What if there are other mediatypes that we are not aware of, but qualify as a good container image today. Then this change  will break a lot of users. That's why blacklisting is safe, since it wont break a thing.

Comment (dmcgowan) [inline distribution/pull_v2.go]: I think we need to add something in distribution to handle this sort of filtering and offering a "media type" separate from the version, so we can test to see if the media type is indeed an image rather than something else. I will create an issue in distribution to track this.

**Comment by tiborvass** [comment]
@dmcgowan My ¢0.02, i don't quite see why the plugin media type has to be in the distribution repo. It should be orthogonal.

**Comment by dmcgowan** [comment]
@tiborvass I agree, we would like to have the definition for all the known media types for the schema2 manifest in the `schema2` package. Didn't have to be done right now but it should be followed up with the documentation next to the other `schema2` documentation. The distribution package certainly doesn't have to be the gatekeeper for these media types but we would like them to flow back in once going out in a release.

**Comment by anusha-ragunathan** [comment]
Distribution vendor at https://github.com/docker/docker/pull/25841

**Comment by anusha-ragunathan** [comment]
@dmcgowan Distribution changes are vendored in. PTAL.

**Comment by dmcgowan** [comment]
LGTM

**Comment by thaJeztah** [comment]
re-LGTM, ping @aaronlehmann @tiborvass

File: plugin/distribution/types.go [hunk 4]
```diff
@@ -10,10 +10,5 @@ var ErrUnsupportedRegistry = errors.New("only V2 repositories are supported for
 // ErrUnsupportedMediaType indicates we are pulling content that's not a plugin
 var ErrUnsupportedMediaType = errors.New("content is not a plugin")
 
-// Plugin related media types
-const (
-	MediaTypeManifest = "application/vnd.docker.distribution.manifest.v2+json"
-	MediaTypeConfig   = "application/vnd.docker.plugin.v0+json"
-	MediaTypeLayer    = "application/vnd.docker.image.rootfs.diff.tar.gzip"
-	DefaultTag        = "latest"
```
Comment (aaronlehmann) [inline plugin/distribution/types.go]: I'm surprised `golint` allowed these not to be commented individually. `golint` generally requires exported constants to have comments. Are we somehow running `golint` incorrectly?

File: distribution/pull_v2.go [hunk 5]
```diff
@@ -32,7 +32,11 @@ import (
 	"golang.org/x/net/context"
 )
 
-var errRootFSMismatch = errors.New("layers from manifest don't match image configuration")
+var (
+	errRootFSMismatch  = errors.New("layers from manifest don't match image configuration")
+	errMediaTypePlugin = errors.New("target is a plugin. Use `docker plugin install` to install plugins")
```
Comment (aaronlehmann) [inline distribution/pull_v2.go]: This would be returned by the API. It may be better to return `target is a plugin`, and have the CLI recognize this error and add the `docker plugin install` suggestion. We're doing this for `docker swarm init`: https://github.com/docker/docker/blob/v1.12.0/api/client/swarm/init.go#L67

File: plugin/distribution/types.go (hunk 4 above)
Comment (vdemeester) [inline plugin/distribution/types.go]: `golint` allows to put one comment on top of `const` if we want to be lazy (and if there is no comment on any constant).

File: distribution/pull_v2.go (hunk 5 above)
Comment (anusha-ragunathan) [inline distribution/pull_v2.go]: Done. PTAL.

**Comment by aaronlehmann** [comment]
LGTM
