### PR TITLE
Fix bug in initializeNetwork()

### LINKED ISSUE #17543: [1.9.0-rc3] Cant use network id in `--net` flag
`docker network create` always outputs the network ID.
`docker run --net` will accept the ID, but you end up with an error: `Error response from daemon: Cannot start container 69b5abfc1fd1e625d76e55897441dd568d2573f69c3e2ff08eb0ff2128b664f0: container already connected to network backend`

As we can see, the network name is `backend` and it was resolved correctly, however it is not usable.
I can however use `docker network connect` with the network ID (but not with this container, as it is now a garbage container that I cannot start).

### PR DESCRIPTION
**Pull request by aboch**
- On `docker run --net <network id> ...`
  the bug would cause the container to attempt
  to connect to the network two times
- Also made sure endpoint creation rollback will
  be executed on failures in `func (container *Container) connectToNetwork()`

Fixes #17543 

Signed-off-by: Alessandro Boch aboch@docker.com

### CODE REVIEW

File: daemon/container_unix.go [hunk 1]
```diff
@@ -1007,13 +1013,15 @@ func (container *Container) connectToNetwork(idOrName string, updateSettings boo
 		}
 	}()
 
-	if err := container.updateEndpointNetworkSettings(n, ep); err != nil {
+	if err = container.updateEndpointNetworkSettings(n, ep); err != nil {
```
Comment (LK4D4) [inline daemon/container_unix.go]: Uh-oh, that's why I'm fan of named return handling in defers. Because someone new will write `:=` 100%

File: daemon/container_unix.go [hunk 2]
```diff
@@ -914,6 +914,12 @@ func (container *Container) allocateNetwork() error {
 		if mode.IsDefault() {
 			networkName = controller.Config().Daemon.DefaultNetwork
 		}
+		if mode.IsUserDefined() {
+			if n, err := container.daemon.FindNetwork(networkName); err == nil {
+				networkName = n.Name()
```
Comment (mavenugo) [inline daemon/container_unix.go]: I understand the intent. but not quite sure I understand the reason on how having the network-id as the name will cause the container to make a duplicate attempt to connect to the same network. Could you pls help me understand that ?

File: daemon/container_unix.go (hunk 1 above)
Comment (mavenugo) [inline daemon/container_unix.go]: Yes. defers with `:=` is a bad combination and it has tripped us once in the past.

File: daemon/container_unix.go [hunk 3]
```diff
@@ -1025,11 +1033,11 @@ func (container *Container) connectToNetwork(idOrName string, updateSettings boo
 		container.updateSandboxNetworkSettings(sb)
 	}
 
-	if err := ep.Join(sb); err != nil {
+	if err = ep.Join(sb); err != nil {
 		return err
 	}
```
Comment (mavenugo) [inline daemon/container_unix.go]: should we also include a defered ep.Leave if the following call to `UpdateJoinInfo` fails

File: daemon/container_unix.go (hunk 2 above)
Comment (mavenugo) [inline daemon/container_unix.go]: Also, isnt it better to fail the call here if `err != nil`

File: daemon/container_unix.go (hunk 3 above)
Comment (mrjana) [inline daemon/container_unix.go]: we don't need to. The `container.cleanup` defer call in `container.Start` will take care of it by calling `releaseNetwork`

File: daemon/container_unix.go [hunk 4]
```diff
@@ -1025,11 +1033,11 @@ func (container *Container) connectToNetwork(idOrName string, updateSettings boo
 		container.updateSandboxNetworkSettings(sb)
 	}
 
-	if err := ep.Join(sb); err != nil {
+	if err = ep.Join(sb); err != nil {
```
Comment (mavenugo) [inline daemon/container_unix.go]: this is going to hep with one of the strange stale endpoint issues if in case of failures during join.

File: daemon/container_unix.go (hunk 2 above)
Comment (aboch) [inline daemon/container_unix.go]: Please take a look at the loop at original line 923. It will cause the code to first connect to the network by id, then again by name...

File: daemon/container_unix.go (hunk 1 above)
Comment (aboch) [inline daemon/container_unix.go]: @LK4D4 
I agree that naked return would also help. But by experience I noticed that from a code clarity standpoint, it is not optimal to use naked return functions bigger than an handful of lines.

File: daemon/container_unix.go (hunk 2 above)
Comment (mavenugo) [inline daemon/container_unix.go]: @aboch thanks. got it.

Comment (mavenugo) [inline daemon/container_unix.go]: @aboch and what about ?
> Also, isnt it better to fail the call here if err != nil

Comment (aboch) [inline daemon/container_unix.go]: It is not this function's concern to do that validation. This function only cares of getting an hold of the real name for a user defined network, in case the network was passed by id. It is a best effort.

The function which will fail (in the situation you described) is the one effectively dealing with the network controller, later on: 
`func (container *Container) connectToNetwork()`

We are not modifying that logic with this change.

File: daemon/container_unix.go (hunk 3 above)
Comment (mavenugo) [inline daemon/container_unix.go]: @mrjana thanks. got it.

File: daemon/container_unix.go (hunk 2 above)
Comment (mavenugo) [inline daemon/container_unix.go]: @aboch I understand. but it is strange in this case to not handle the error.
I personally would prefer to handle the error and return right here.

**Comment by aboch** [comment]
@mavenugo Addressed your comment. PTAL.

File: daemon/container_unix.go (hunk 1 above)
Comment (mavenugo) [inline daemon/container_unix.go]: @aboch for the sake of consistency with `daemon/container.go`, I think it would be good to follow @LK4D4's suggestion.

**Comment by aboch** [comment]
@LK4D4 Taken care of your comment. PTAL when you get a chance.

**Comment by vdemeester** [comment]
@aboch `golint` issue : 

```daemon/container_unix.go:920:11: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)```

**Comment by aboch** [comment]
Thanks @vdemeester. Taken care of the golint issue. PTAL.

**Comment by calavera** [comment]
LGTM. Janky error is unrelated.

File: daemon/container_unix.go [hunk 5]
```diff
@@ -914,6 +914,16 @@ func (container *Container) allocateNetwork() error {
 		if mode.IsDefault() {
 			networkName = controller.Config().Daemon.DefaultNetwork
 		}
+		if mode.IsUserDefined() {
+			var (
```
Comment (cpuguy83) [inline daemon/container_unix.go]: Can we get rid of this var block and instead do
```go
n, err := condainer.daemon...;
if err != nil {
    return err
}
networkName = n.Name()
```

Comment (aboch) [inline daemon/container_unix.go]: Good point.
Let me take care of it.

Thanks

**Comment by cpuguy83** [comment]
LGTM
