### PR TITLE
 daemon option (--storage-opt dm.basesize) for increasing the base device size on daemon restart

### LINKED ISSUE #18314: `docker run`/`docker rm` extremely slow in Docker 1.9.1 with devicemapper
Description of problem: `docker run`/`docker rm` extremely slow in Docker 1.9.1 with devicemapper

`docker version`:
```
ubuntu@ip-172-31-39-228:~$ sudo docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:
```
ubuntu@ip-172-31-39-228:~$ sudo docker info
Containers: 1000
Images: 14
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-202:1-401324-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.369 GB
 Data Space Total: 107.4 GB
 Data Space Available: 26.44 GB
 Metadata Space Used: 47.08 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.1 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-48-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 992.5 MiB
Name: ip-172-31-39-228
ID: ZLSZ:CSSF:WXIO:KKKE:XMIE:JQGJ:ET27:2Z5Z:ABXI:XQBY:76UY:NHTO
WARNING: No swap limit support
```

`uname -a`:
```
ubuntu@ip-172-31-39-228:~$ uname -a
Linux ip-172-31-39-228 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.):
Amazon EC2 instance running Ubuntu 14.04 (ami-5189a661 in us-west-2)

How reproducible:

Steps to Reproduce:
1. Launch an instance with userdata as [this script](https://gist.github.com/samuelkarp/cab8f8bfd50a99df8959)
2. Let it run until it finishes
3. Observe that `docker run` and `docker rm` both grow to take around 90s to complete

Actual Results:
```
ubuntu@ip-172-31-39-228:/opt/test$ tail run-only.out
Ran in 5.17
Running 999/1000
hello, container
Ran in 87.74
Running 1000/1000
hello, container
Ran in 85.55
Ran 1000; the longest-running container took 92.66 to run.
ubuntu@ip-172-31-39-228:/opt/test$ tail run-delete.out 
2507862ce325f509367fcf070858705bd92885654401037a00f2722812598647
Removing 2507862ce325f509367fcf070858705bd92885654401037a00f2722812598647
2507862ce325f509367fcf070858705bd92885654401037a00f2722812598647
Removed in 72.49
Running 1000/1000: a87283b31e3d8b0e4a5207d4261c04340998a56b4414547cbcb72cd19d17ee0b
a87283b31e3d8b0e4a5207d4261c04340998a56b4414547cbcb72cd19d17ee0b
Removing a87283b31e3d8b0e4a5207d4261c04340998a56b4414547cbcb72cd19d17ee0b
a87283b31e3d8b0e4a5207d4261c04340998a56b4414547cbcb72cd19d17ee0b
Removed in 74.74
Removed 1000; the longest removal took 94.42
```

Expected Results:
`docker run` should take under 1s and `docker rm` should take under 3s (this is what I observe with Docker 1.7.1).

Additional info:  I don't see the same behavior with aufs, so it looks like it's something specific to devicemapper.  I do see this same behavior with Docker 1.9.1 (and Docker 1.9.0) on the Amazon Linux AMI using devicemapper (aufs is not available).  This may be related to #17720 and #17448.

### PR DESCRIPTION
**Pull request by shishir-a412ed**
Signed-off-by: Shishir Mahajan shishir.mahajan@redhat.com

Fixes #18314

### CODE REVIEW

**Comment by shishir-a412ed** [comment]
With this patch the user can pass the container's filesystem size at creation time.
I have added CLI options for docker create and run.

User can grow the FS but cannot shrink it. e.g if the Basedevice FS size is 100G.
User can specify `--storage-opt size:120G` to grow the container's filesystem size to 120GB. However if the user tries to pass `--storage-opt size:80G` daemon will throw an error.

Shishir

**Comment by thaJeztah** [comment]
@shishir-a412ed @rhvgoyal I think this closes https://github.com/docker/docker/issues/14678 ?

**Comment by rhvgoyal** [comment]
@thaJeztah right.

**Comment by calavera** [comment]
we should revert the default value to 10G or 20G if growing is okay but shrinking is not allowed.

**Comment by rhvgoyal** [comment]
@calavera makes sense. Shishir, can you update the patch to also change default base size value to say  10G.

**Comment by thaJeztah** [comment]
@rhvgoyal does this only work for loop, or also for direct-lvm (I'm not too fluent in devicemapper)

**Comment by shishir-a412ed** [comment]
@rhvgoyal 
Changed the default base size to 10G.

@thaJeztah @calavera Added tests.

Shishir

**Comment by rhvgoyal** [comment]
@thaJeztah This works for devicemapper graph driver. One could be using loop devices or regular block devices and it does not matter. That's underlying detail. So yes, it will work for loop devices as well.

This size parameter will not work for other graph drivers like, overlay, btrfs, aufs and zfs.

File: daemon/graphdriver/devmapper/deviceset.go [hunk 1]
```diff
@@ -1744,10 +1752,99 @@ func (devices *DeviceSet) AddDevice(hash, baseHash string) error {
...
+	case "ext4":
+		if out, err := exec.Command("resize2fs", info.DevName()).CombinedOutput(); err != nil {
+			logrus.Debugf("Failed to grow rootfs:%v:%s", err, string(out))
+		}
+	case "xfs":
+		if out, err := exec.Command("xfs_growfs", info.DevName()).CombinedOutput(); err != nil {
+			logrus.Debugf("Failed to grow rootfs:%v:%s", err, string(out))
+		}
+	default:
+		err = fmt.Errorf("Unsupported filesystem type %s", devices.BaseDeviceFilesystem)
```
Comment (calavera) [inline daemon/graphdriver/devmapper/deviceset.go]: this error is never returned, you need to add `return err` at the end of the function.

File: daemon/graphdriver/devmapper/deviceset.go [hunk 2]
```diff
@@ -1744,10 +1752,99 @@ func (devices *DeviceSet) AddDevice(hash, baseHash string) error {
...
+	info.lock.Lock()
+	defer info.lock.Unlock()
+
+	if err := devices.activateDeviceIfNeeded(info, false); err != nil {
+		return fmt.Errorf("Error activating devmapper device for '%s': %s", hash, err)
+	}
+
+	defer devices.deactivateDevice(info)
+
+	fsMountPoint := "/run/docker/mnt"
```
Comment (calavera) [inline daemon/graphdriver/devmapper/deviceset.go]: is this path always valid? can users override it somehow? we should take that into account.

**Comment by calavera** [comment]
I think we should include this for 1.10, but we might be slightly constraint in time.

I'm going to add the `StorageOpt` in https://github.com/docker/engine-api so we can make this happen.

I don't think we should add more features here, like version logic detection, so we have less things to discuss.

File: daemon/graphdriver/devmapper/deviceset.go (hunk 2 above)
Comment (rhatdan) [inline daemon/graphdriver/devmapper/deviceset.go]: I don't think we should allow users to change this.  This directory is only needed since you have to actually mount the device in order to expand it.  So we need to temporarily mount the device.

**Comment by rhatdan** [comment]
Getting this into docker-1.10 would be great.

**Comment by calavera** [comment]
This PR brings the StorageOpt to the api. We should be good to go once it's merged:

https://github.com/docker/docker/pull/19173

**Comment by icecrime** [comment]
Can someone please explain:

- What are the implication of the initial size? In particular, I've heard about the tradeoff of a too important initial size, but what are the drawbacks of a smaller default (such as the 10G we use to have)?
- Why would I want to pick a bigger one from the start?

I'm not contesting this PR, I'm just trying to understand the requirement here. Thanks!

**Comment by runcom** [comment]
@rhvgoyal 

> This size parameter will not work for other graph drivers like, overlay, btrfs, aufs and zfs.

Agree but I think we shouldn't error out if `storageOpt` is provided to other graph drivers. Silently ignore not supported storage options would be better if in the future we will add some to the other graph drivers (also, does the daemon ignore --storage-opt on other graph drivers as well?)

**Comment by rhvgoyal** [comment]
@runcom 

I think if you pass --storage-opt to other graph drivers, then there is no error. It is ignored silently. BUT, if you pass a non-supported option to device mapper graph driver it errors out.

I personally feel that it probably is better to error out on unsupported option. For example if somebody is trying to shrink container size we should return error instead of ignoring it. 

If we implement options for other graph drivers later, then we will stop erroring out on valid options.

IOW, what's the advantage of ignoring storage-opt which are not supported?

**Comment by rhvgoyal** [comment]
@icecrime 

For some people 10G was not enough and if one is building bigger images then 10G, docker build will fail and that's the reason we bumped up the size to say 100G. Initial idea was that it is virtual size so there is no cost involved in bumping up the size. But two issues came up.

- Container removal was slow on loop devices (due to discards)
- Creation of ext4 file system on 100G device took significantly longer and systemd timed out.

Second issue was fixed by switching to xfs by default (if it is available on host).

For first one a kernel fix is available which will go in 4.5.

So having initial bigger size is a problem with ext4 file system and with discards. By reducing it to smaller size we will move away from these problems but those who want to build images bigger
than 10G, will fail and they will have to wipe everything and start from scratch.

**Comment by runcom** [comment]
@rhvgoyal 

I'm talking about erroring out here for instance https://github.com/docker/docker/pull/19123/files#diff-2441da2e3b5de478b533a1310aa1864aR206

this way from now on we will error out on the cli (if I'm not wrong) if I pass `--storage-opt size=10G` on an aufs driver...
on the other way, even if it will never happen, we may just print a warning or better ignore that we have provided `size` in storageOpt , but erroring out on storageOpt provided will change the cli interface and future version do not error out anymore....no big deal though :)

**Comment by rhvgoyal** [comment]
@runcom If aufs does not support passed in --storage-opt size:10G, to me it is logical to error out. User should not be passing it in to begin with.

But if others think that ignoring or printing a warning is better than error, we can change it.  not a big deal. This is just initial proposal.

File: daemon/graphdriver/devmapper/deviceset.go (hunk 2 above)
Comment (rhvgoyal) [inline daemon/graphdriver/devmapper/deviceset.go]: agreed that it should not be user configurable. I am wondering why not create a directory say `tmpmnt` in devmapper graph driver directory itself. Say `/var/lib/docker/devicemapper/mnt/tmpmnt`

**Comment by shishir-a412ed** [comment]
@runcom @rhvgoyal 
Personally I am not a big fan of silently ignoring invalid flags. I have seen this before with docker daemon (docker -d) where daemon flags were silently ignored by other docker commands. With this approach the user has no idea whether the flag is actually doing something meaningful or not. An error is more expressive. But that's just me :) .. I ll let other maintainers chime in.

File: daemon/graphdriver/devmapper/deviceset.go (hunk 1 above)
Comment (shishir-a412ed) [inline daemon/graphdriver/devmapper/deviceset.go]: Fixed.

**Comment by thaJeztah** [comment]
Yeah, I think I prefer an error as well; it can be really nasty to find (e.g.) that you had made a typo in an option, and no error/warning is shown. Any reason you want to ignore incorrect options @runcom ?

**Comment by calavera** [comment]
> Personally I am not a big fan of silently ignoring invalid flags.

I agree, we should fail fast.

@shishir-a412ed it looks like the experimental build is broken, I think you left something unchanged. Can you take a look?

**Comment by rhatdan** [comment]
I agree fail on bad option

"Size option not supported on Overlayfs"

As opposed to, Issue/Bugzilla I set size option and it did not work.

File: daemon/graphdriver/devmapper/deviceset.go (hunk 2 above)
Comment (shishir-a412ed) [inline daemon/graphdriver/devmapper/deviceset.go]: @rhatdan what do you think of mounting at `/var/lib/docker/devicemapper/mnt/tmpmnt` (what @rhvgoyal suggested) ?

Comment (rhatdan) [inline daemon/graphdriver/devmapper/deviceset.go]: I don't care, I am just not sure why it matters other then the mount point is not available to non privileged users.

Comment (rhvgoyal) [inline daemon/graphdriver/devmapper/deviceset.go]: I thought it is simpler. We don't have to create another directory inside /run. Also I am not sure if all the systems where docker runs have /run or not. And also not sure why there is a need for unprivileged users to be able to see this temporary mount point.

Comment (rhatdan) [inline daemon/graphdriver/devmapper/deviceset.go]: There is definitely no reason for non privileged users to see this.  /run is a standard, that all distributions use, but I don't really care where we put it as long as it is not /tmp/

**Comment by shishir-a412ed** [comment]
@calavera Fixed experimental.

**Comment by tiborvass** [comment]
Following our discussion on #docker-dev IRC with @shishir-a412ed and @rhvgoyal, we decided to limit the scope of this PR to automatically grow the basefs size on startup, if the user specified `--storage-opt` on the **daemon** (as opposed to on `docker run`) and it is bigger than that of the existing pool (dm.basesize). So assuming the default is 10G, the people who need to change that to 100G, can do so by simply restarting their daemons with `--storage-opt dm.basesize=100G`.

This allows us to have a simple solution for 1.10 that doesn't require changing the API.
Per-container granularity can be further discussed later.

**Comment by rhatdan** [comment]
Seems like a reasonable compromise.  Thanks @tiborvass

**Comment by rhvgoyal** [comment]
@tiborvass We have a patch to grow base image but growing base image itself is not sufficient. Any existing images should be deleted and pull again to benefit from new base image size. Otherwise existing image size continues to be old size and any container launched off these images continues to be old size.

Image can't be removed if there are containers using it already. So it means one needs to remove all the containers using that image, remove image, pull it again and then only one will benefit from increased base image size.

Or this will work only for new images (which are not already pulled in).

So this is pretty close to wipe all metadata of docker and start fresh. Just little bit better.

I guess this just makes the case of per container storage-opt little bit stronger.

**Comment by calavera** [comment]
Since release freeze is in two days, let's go with the current implementation of using a daemon option. We can expand it later to container option when those other patches are in place.

**Comment by rhvgoyal** [comment]
@calavera shishir is cleaning up the code a little more. So please don't merge this version yet. Soon a new version should be up.

**Comment by rhvgoyal** [comment]
LGTM

Thanks @shishir-a412ed

**Comment by tiborvass** [comment]
Thank you @shishir-a412ed @rhvgoyal 

LGTM

**Comment by calavera** [comment]
LGTM

**Comment by tiborvass** [comment]
Ping @thaJeztah @moxiegirl @jamtur01

**Comment by tiborvass** [comment]
@shishir-a412ed actually i just realized there are no updates to the documentation. I know for sure there's at least the `100G` -> `10G` to be changed in the docs, but would be great to explain the growfs thing too in some paragraph.

**Comment by vdemeester** [comment]
I agree with @tiborvass :stuck_out_tongue:. Changes are in :

- `docs/reference/commandline/daemon.md`,
- `man/docker-daemon.8.md`
- *maybe* `docs/userguide/storagedriver/device-mapper-driver.md` for `100G` and something about growfs.

**Comment by tiborvass** [comment]
Ping @vdemeester @MHBauer @thaJeztah

File: docs/reference/commandline/daemon.md [hunk 3]
```diff
@@ -213,11 +213,21 @@ options for `zfs` start with `zfs`.
...
+    10 GB of space on the pool. However, the filesystem will use more space for
     the empty case the larger the device is.
 
+    The base device size can be increased at daemon restart which will allow
+    all future images and containers (based on those new images) to be of the 
+    new base device size.
+
+    Example use: `docker daemon --storage-opt dm.basesize=50G` 
+
+    This will increase the base device size to 50G. docker daemon will throw an
```
Comment (jamtur01) [inline docs/reference/commandline/daemon.md]: The Docker daemon

File: docs/reference/commandline/daemon.md [hunk 4]
```diff
@@ -213,11 +213,21 @@ options for `zfs` start with `zfs`.
...
+    size of images and containers. The default value is 10G. Note, thin devices
+    are inherently "sparse", so a 10G device which is mostly empty doesn't use
+    10 GB of space on the pool. However, the filesystem will use more space for
     the empty case the larger the device is.
 
+    The base device size can be increased at daemon restart which will allow
+    all future images and containers (based on those new images) to be of the 
+    new base device size.
+
+    Example use: `docker daemon --storage-opt dm.basesize=50G`
```
Comment (jamtur01) [inline docs/reference/commandline/daemon.md]: Maybe format as:

    ```
    docker daemon --storage-opt dm.basesize=50G
    ````

File: man/docker-daemon.8.md [hunk 5]
```diff
@@ -271,12 +271,22 @@ Example use: `docker daemon --storage-opt dm.thinpooldev=/dev/mapper/thin-pool`
...
+thin devices are inherently "sparse", so a 10G device which is mostly
+empty doesn't use 10 GB of space on the pool. However, the filesystem
 will use more space for base images the larger the device
 is.
 
+The base device size can be increased at daemon restart which will allow
+all future images and containers (based on those new images) to be of the 
+new base device size.
+
+Example use: `docker daemon --storage-opt dm.basesize=50G`
```
Comment (jamtur01) [inline man/docker-daemon.8.md]: As above

File: man/docker-daemon.8.md [hunk 6]
```diff
@@ -271,12 +271,22 @@ Example use: `docker daemon --storage-opt dm.thinpooldev=/dev/mapper/thin-pool`
...
 will use more space for base images the larger the device
 is.
 
+The base device size can be increased at daemon restart which will allow
+all future images and containers (based on those new images) to be of the 
+new base device size.
+
+Example use: `docker daemon --storage-opt dm.basesize=50G` 
+
+This will increase the base device size to 50G. docker daemon will throw an
```
Comment (jamtur01) [inline man/docker-daemon.8.md]: As above.

**Comment by jamtur01** [comment]
Docs mostly LGTM - minor comments.

**Comment by shishir-a412ed** [comment]
@jamtur01 check now. I have kept my example in the same format as the example below (docker daemon --storage-opt dm.basesize=20G ) in that section.

**Comment by jamtur01** [comment]
One comment still not addressed. Thanks!

**Comment by shishir-a412ed** [comment]
@jamtur01 PTAL.

**Comment by jamtur01** [comment]
Docs LGTM

File: docs/reference/commandline/daemon.md [hunk 7]
```diff
@@ -213,11 +213,23 @@ options for `zfs` start with `zfs`.
...
+    10 GB of space on the pool. However, the filesystem will use more space for
     the empty case the larger the device is.
 
+    The base device size can be increased at daemon restart which will allow
+    all future images and containers (based on those new images) to be of the 
+    new base device size.
+
+    Example use: 
+
+	$ docker daemon --storage-opt dm.basesize=50G`
```
Comment (thaJeztah) [inline docs/reference/commandline/daemon.md]: Can you change the indentation here to 8 spaces, otherwise it won't render as a code-block

File: man/docker-daemon.8.md (hunk 5 above)
Comment (thaJeztah) [inline man/docker-daemon.8.md]: @shishir-a412ed looks like you forgot to address this one? Can you change this to:

```Markdown
Example use:

    docker daemon --storage-opt dm.basesize=50G
```

**Comment by thaJeztah** [comment]
two formatting comments, but LGTM otherwise

File: docs/reference/commandline/daemon.md (hunk 7 above)
Comment (jamtur01) [inline docs/reference/commandline/daemon.md]: Oh and I missed the trailing \` - you should remove that.

Comment (thaJeztah) [inline docs/reference/commandline/daemon.md]: :+1:

Comment (shishir-a412ed) [inline docs/reference/commandline/daemon.md]: Fixed.

**Comment by calavera** [comment]
docs LGTM, thanks!

File: man/docker-daemon.8.md (hunk 5 above)
Comment (thaJeztah) [inline man/docker-daemon.8.md]: ping @shishir-a412ed can you fix this one, then we are ready to go

**Comment by thaJeztah** [comment]
actually,  looks like there's one comment not addressed; https://github.com/docker/docker/pull/19123#discussion_r49636683

can you take care of that @shishir-a412ed ?

File: man/docker-daemon.8.md (hunk 5 above)
Comment (shishir-a412ed) [inline man/docker-daemon.8.md]: @thaJeztah This is in sync with other examples below.
Let me know if you still want me to change it.

Comment (thaJeztah) [inline man/docker-daemon.8.md]: @shishir-a412ed fair, alright, lets keep it like this then :+1:

**Comment by thaJeztah** [comment]
thanks @shishir-a412ed, LGTM!
