### PR TITLE
do not fail fast when executing inspect command

### LINKED ISSUE #30599: docker inspect --type task fails fast with "No such task" error.
**Description**

`docker inspect --type task abc123 def456` fails fast if `abc123` is not a valid task.

**Steps to reproduce the issue:**

1. Run a container. Observe the task attached, and for this example assume it is has identifier `def456`.
2. Run `docker inspect --type task abc123 def456` (where `abc123` is not a task identifier in any container)

**Describe the results you received:**

```
[]
Error: No such task: abc123
```

**Describe the results you expected:**

```
[
    {
        "ID": "def456",
        ...
    }
]
Error: No such task: abc123
```

I expect this result because switching the order of tasks does not fail fast:

```
docker inspect --type task def456 abc123
```

**Additional information you deem important (e.g. issue happens only occasionally):**

This happens occasionally when diagnosing a failing swarm service: First I need to get the task identifiers, and then I need to inspect them. If it happens that the first task identifier in my list is invalid, the `docker inspect --type task ...` command fails and returns nothing about the otherwise correctly identified tasks.

As a result, I have to resort to calling `docker inspect --type task ...` with one task at a time which is less efficient.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.24 (downgraded from 1.25)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.6
 API version:  1.24 (minimum version )
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:38:45 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 17
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-202:1-524732-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 4.758 GB
 Data Space Total: 107.4 GB
 Data Space Available: 23.58 GB
 Metadata Space Used: 6.644 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.141 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.110 (2015-10-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null host bridge
Swarm: active
 NodeID: 1qutd93aptnd2us8wnbypjhyc
 Is Manager: true
 ClusterID: 9a8q3p4qg01vo386rsueqtk33
 Managers: 3
 Nodes: 7
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: xx.xx.xx.xx
 Manager Addresses:
  xx.xx.xx.xx:2377
  xx.xx.xx.xx:2377
  xx.xx.xx.xx:2377
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version:
runc version:
init version:
Security Options:
 apparmor
 seccomp
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67 GiB
Name: xxxxxx
ID: xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by allencloud**
Signed-off-by: allencloud <allen.sun@daocloud.io>

fixes #30599 

do not fail fast when executing inspect command.

Current if user executes a command like `docker network inspect nonexist exist1 exist2`, it will fail fast. Like:
```
root@ubuntu:~# docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
b80b14598d1f        allen               bridge              local
fd6a89aad8ff        bridge              bridge              local
85ded5476b05        docker_gwbridge     bridge              local
d909a9f88b4c        host                host                local
z1sybtvc99hu        ingress             overlay             swarm
615a39ff6c47        none                null                local
root@ubuntu:~# docker network inspect nonexist bridge host
[]
Error: No such network: nonexist
```

This PR tries to fix this improper fast failing.

**- What I did**

**- How I did it**

**- How to verify it**
Choose an inspect command in which non-existent object locates at the head, and check if it fails fast.
```
root@ip-172-31-23-42:~ ./docker-1.14.0-dev network inspect allen allen2 host
[
    {
        "Name": "host",
        "Id": "04157c270e60a3f28dd72cdda45d103e640f0e89cba2c8d29d690081936cde4f",
        "Created": "0001-01-01T00:00:00Z",
        "Scope": "local",
        "Driver": "host",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": []
        },
        "Internal": false,
        "Attachable": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    }
]
Error: No such network: allen
Error: No such network: allen2
```

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by allencloud** [comment]
CI fails since the test `FAIL: docker_cli_inspect_test.go:355: DockerSuite.TestInspectStopWhenNotFound`, the test is in https://github.com/docker/docker/blob/master/integration-cli/docker_cli_inspect_test.go#L355-L364.

And I found the **container** inspect failing fast seems intentional, and it is introduced in https://github.com/docker/docker/pull/18472, in which pr description shows that 

> Breaking changes
Of course there are always consequences. I introduced what can be considered as a breaking change. In my opinion, the new behavior is more correct 😸

> Until now, docker inspect continued evaluating containers if you typed a wrong id, see this example:
$ docker run -d --name test alpine true
$ docker inspect this_container_does_not_exist test

> The message about this_container_does_not_exist not existing would be followed by the test container output, a json payload of about 100 lines. This makes almost impossible to see the error.
With the new behavior, the cli stops execution as soon as it finds an error. This is a more predictable behavior. Users know sooner and more clear that there is a problem with the command they just executed.

for the original cause, I think it is reasonable. While until now, I am afraid there are more things we need to take into consideration:

* FIRST, except container inspect, there are still image, network, volume, plugin, service, node inspect and so on. Some inspect has json payload much less than 100 lines, and failing fast to avoid unreadable issue seems not so reasonable.
* SECOND, for readable case, can we always show the errors at the ending of output, like this PR's way? I think everyone will care about the ending details in the cli output, since it always shows the err, warning and something incorrect. Like below:

```
root@ip-172-31-23-42:~/.../bundles/1.14.0-dev/binary-client# ./docker-1.14.0-dev network inspect allen allen2 host
[
    {
        "Name": "host",
        "Id": "04157c270e60a3f28dd72cdda45d103e640f0e89cba2c8d29d690081936cde4f",
        "Created": "0001-01-01T00:00:00Z",
        "Scope": "local",
        "Driver": "host",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": []
        },
        "Internal": false,
        "Attachable": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    }
]
Error: No such network: allen
Error: No such network: allen2
```

ping @LK4D4 @AkihiroSuda @thaJeztah

**Comment by LK4D4** [comment]
haha, suddenly I have no strong opinion on design
I think it might be related to the case where we inspecting different types of objects - in terms of consistency.
ping @thaJeztah who is the author of "different types" PR

**Comment by allencloud** [comment]
I think https://github.com/docker/docker/pull/23614 introduced `different types` in inspect.
/cc @LK4D4 @thaJeztah @icecrime

**Comment by allencloud** [comment]
Any update? 
OK with the design?
Or anything to make this move forward?

File: integration-cli/docker_cli_network_unix_test.go [hunk 1]
```diff
@@ -507,6 +507,19 @@ func (s *DockerSuite) TestDockerInspectMultipleNetwork(c *check.C) {
...
+	c.Assert(result, icmd.Matches, icmd.Expected{
+		ExitCode: 1,
+		Err:      "Error: No such network: nonexistent",
+		Out:      "host",
+	})
+
+	networkResources = []types.NetworkResource{}
+	err = json.Unmarshal([]byte(result.Stdout()), &networkResources)
+	c.Assert(err, check.IsNil)
+	c.Assert(networkResources, checker.HasLen, 1)
```
Comment (dnephin) [inline integration-cli/docker_cli_network_unix_test.go]: Please make this a new test function. The comment can be replaced with a descriptive test name

File: integration-cli/docker_cli_inspect_test.go [hunk 2]
```diff
@@ -353,13 +353,21 @@ func (s *DockerSuite) TestInspectByPrefix(c *check.C) {
...
-	runSleepingContainer(c, "--name=not-shown", "-d")
-	out, _, err := dockerCmdWithError("inspect", "--type=container", "--format='{{.Name}}'", "busybox", "missing", "not-shown")
+	runSleepingContainer(c, "--name=busybox1", "-d")
+	runSleepingContainer(c, "--name=busybox2", "-d")
+	out, _, err := dockerCmdWithError("inspect", "--type=container", "--format='{{.Name}}'", "busybox1", "busybox2", "missing")
+
+	c.Assert(err, checker.Not(check.IsNil))
+	c.Assert(out, checker.Contains, "busybox1")
+	c.Assert(out, checker.Contains, "busybox2")
+	c.Assert(out, checker.Contains, "Error: No such container: missing")
```
Comment (dnephin) [inline integration-cli/docker_cli_inspect_test.go]: I think this test can be improved by asserting that a specific stream (stdout vs stderr) containers this text, instead of the combined stream.

If you change `dockerCmdWithError()` to use the `dockerCmdWithResult()`, you can check `result.Stderr()`, and `result.Stdout()`

**Review by dnephin — COMMENTED** [review]
Design LGTM

File: integration-cli/docker_cli_network_unix_test.go (hunk 1 above)
Comment (cpuguy83) [inline integration-cli/docker_cli_network_unix_test.go]: Any update here?

Comment (allencloud) [inline integration-cli/docker_cli_network_unix_test.go]: Yes, it has been updated. Since it has been moved into a new test func `TestDockerInspectMultipleNetworksIncludingNonexistent `, but the content keeps the same.

**Review by cpuguy83 — APPROVED** [review]
LGTM

File: integration-cli/docker_cli_network_unix_test.go (hunk 1 above)
Comment (dnephin) [inline integration-cli/docker_cli_network_unix_test.go]: Did you forget to push that change? I still see it in  the same function

**Review by dnephin — APPROVED** [review]
LGTM

**Comment by dnephin** [comment]
@thaJeztah I don't think this PR needs any impact labels or docs, but pinging you just in case.

**Comment by thaJeztah** [comment]
Agreed, don't think this needs impact labels. let's merge (thanks!)
