### PR TITLE
On container rm, don't remove named mountpoints

### LINKED ISSUE #17907: Using `run` with `--rm` deletes volumes created with `docker volume create`
# Bug Report Information

## `docker version`

```
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 18:00:05 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 18:00:05 UTC 2015
 OS/Arch:      linux/amd64
```

## `docker info`

```
Containers: 0
Images: 6
Server Version: 1.9.0
Storage Driver: devicemapper
 Pool Name: docker-8:2-3222770360-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 545.8 MB
 Data Space Total: 107.4 GB
 Data Space Available: 106.8 GB
 Metadata Space Used: 1.004 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.14.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 8
Total Memory: 23.38 GiB
Name: x.y.z
ID: MMMV:B5GR:6NIY:ODB7:OV7U:BVJE:VPLR:I56P:D34C:CKKG:ECKU:EWSC

```

## `uname -a`

```
Linux x.y.z 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Sep 15 15:05:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Steps to reproduce:

1. Create a volume with the new `volume` command:

```
docker volume create --name hello
> hello
docker volume ls
> DRIVER              VOLUME NAME
> local               hello
```
2. Then "mount" it:

```
docker run --rm -it -v hello:/world busybox sh
/ # touch world/foobar
/ # exit
```

3. Then look for volume:

```    
docker volume ls
> DRIVER              VOLUME NAME
```

This seems dangerous behavior given that volumes are considered the persistent component of the system.

----------END REPORT ---------

### PR DESCRIPTION
**Pull request by cpuguy83**
This makes it so when calling `docker run --rm`, or `docker rm -v`, only
volumes specified without a name, e.g. `docker run -v /foo` instead of
`docker run -v awesome:/foo` are removed.

Note that all volumes are named, some are named by the user, some get a
generated name. This is specifically about how the volume was specified
on `run`, assuming that if the user specified it with a name they expect
it to persist after the container is cleaned up.

Fixes #17907

### CODE REVIEW

File: integration-cli/docker_cli_run_test.go [hunk 1]
```diff
@@ -4058,3 +4058,18 @@ func (s *DockerSuite) TestRunNamedVolumeCopyImageData(c *check.C) {
...
 	c.Assert(strings.TrimSpace(out), check.Equals, "hello")
 }
+
+func (s *DockerSuite) TestRunNamedVolumeNotRemoved(c *check.C) {
+	dockerCmd(c, "volume", "create", "--name", "test")
+
+	dockerCmd(c, "run", "--rm", "-v", "test:/foo", "-v", "/bar", "busybox", "true")
+	dockerCmd(c, "volume", "inspect", "test")
+	out, _ := dockerCmd(c, "volume", "ls", "-q")
+	c.Assert(strings.TrimSpace(out), checker.Equals, "test")
```
Comment (calavera) [inline integration-cli/docker_cli_run_test.go]: can we assert that `bar` is not in the output too somehow?

**Comment by calavera** [comment]
sounds like a great plan :+1:

**Comment by thaJeztah** [comment]
nice approach for this! basically, this would handle the cases below;

```bash
docker run --rm myname:/foo ...

# note: no name specified during creation of the volume
# however, the generated name is passed on to docker run
# so it's considered a "named" volume, and won't be removed
VOL=$(docker volume create); docker run --rm -v $VOL:/foo ..

# same here, but no intermediate variable
docker run --rm -v $(docker volume create):/foo ...
```

In all those cases, the volume is *not* removed when the container is removed. However, the examples below treat the volume as ephemeral  and remove the volume together with the container;

```bash
docker run --rm -v /foo ..

# image that has a `VOLUME` specified;
docker run --rm something
```

**Comment by thaJeztah** [comment]
We may need to update some documentation explaining this

File: integration-cli/docker_cli_run_test.go (hunk 1 above)
Comment (cpuguy83) [inline integration-cli/docker_cli_run_test.go]: We are, we are doing `checker.Equals`

**Comment by cpuguy83** [comment]
@thaJeztah I'll take a look at the docs tomorrow.

**Comment by thaJeztah** [comment]
@cpuguy83 :+1: just mentioning it to prevent trigger-happy merges :smile:

**Comment by coolljt0725** [comment]
@cpuguy83  I tested your branch. This scenario does not work, the volume still be remove if the named volume is from `--volumes-from CONTAINER` and the original `CONTAINER` has been removed. 
<pre><code>
$ docker volume create --name data
data
$ docker run -ti --name foo -v data:/data busybox
/ # exit
$ docker run -ti --rm --name bar --volumes-from foo busybox
/ #

</code></pre>
Remove container `foo`
` $ docker rm foo
foo`
And then kill container `bar`, the volume `data` will be removed
<pre><code>DEBU[0637] DELETE /v1.23/containers/7b4e2b232d6269036b1bf28f9b563426b0b7cac60e0125446d420a6eaca45e6e?v=1
DEBU[0637] Removing volume reference: driver local, name data

</code></pre> 
seems we should also handle https://github.com/docker/docker/blob/master/daemon/volumes.go#L73

**Comment by cpuguy83** [comment]
@coolljt0725 Nice catch! Updated with a fix and another test.

**Comment by estesp** [comment]
code LGTM. Still considering docs additions, I assume?

**Comment by thaJeztah** [comment]
We're considering this a bug fix, added to the milestone

**Comment by thaJeztah** [comment]
@estesp yes, @cpuguy83 was going to work on docs today

File: integration-cli/docker_cli_run_test.go (hunk 1 above)
Comment (calavera) [inline integration-cli/docker_cli_run_test.go]: oh right, nevermind, thanks.

**Comment by calavera** [comment]
LGTM

**Comment by cpuguy83** [comment]
Rebased and added docs

**Comment by thaJeztah** [comment]
Thanks @cpuguy83 can you also update the note in this section; https://github.com/docker/docker/blob/master/docs/reference/run.md#clean-up---rm ?

**Comment by cpuguy83** [comment]
@thaJeztah Updated.

**Comment by thaJeztah** [comment]
Thanks! Docs LGTM

ping @vdemeester @MHBauer for docs review

**Comment by jhowardmsft** [comment]
@cpuguy83 - The failures in windowsTP4 is real :)

**Comment by cpuguy83** [comment]
Woah, it actually ran.

**Comment by thaJeztah** [comment]
Oh, TP4 is running now!

**Comment by jhowardmsft** [comment]
@cpuguy83 @thaJeztah Of course! Yeah, I've been working on getting this brought up for a while. The switch was just flipped to turn it on.

File: docs/reference/run.md [hunk 2]
```diff
@@ -590,7 +590,10 @@ the container exits**, you can add the `--rm` flag:
 
 > **Note**: When you set the `--rm` flag, Docker also removes the volumes
 associated with the container when the container is removed. This is similar
-to running `docker rm -v my-container`.
+to running `docker rm -v my-container`. Only volumes that are specified without a
+name are removed. This includes volumes inherited via `--volumes-from`. For example, with
```
Comment (vdemeester) [inline docs/reference/run.md]: I'm wondering something on that sentence. From reading it, I was wondering if doing a `docker run --rm --volumes-from=data-container…` would remove or not the unamed volumes from the container `data-container` — by reading it my first guess was that it would remove them, which it does not.

```
$ docker volume create --name=one
$ docker volume create --name=two
$ docker run -dti -v one:/one -v /three busybox /bin/sh
$ docker run --rm -it --volumes-from silly_hugle -v /four -v two:/two busybox /bin/sh
# While running
DRIVER              VOLUME NAME
local               one
local               two
local               b01400488037b97d25dcd0b1049f3f0c9c1c8f462843ba1f2b1c2fe92d75ca71
local               7a98cabdc8acbb3d1f7790041bc8c0798febc8ae98c61d3fce428d1b57d97f36
# After leaving the `--rm` container
DRIVER              VOLUME NAME
local               one
local               two
local               b01400488037b97d25dcd0b1049f3f0c9c1c8f462843ba1f2b1c2fe92d75ca71
```

I think we could be a little clearer on this, @cpuguy83 wdyt ?

Comment (cpuguy83) [inline docs/reference/run.md]: Sure, makes sense. Let me come up with a re-word.

**Comment by cpuguy83** [comment]
Updated -- also fixed windows test (hopefully, we'll see).
@vdemeester PTAL at the doc change

File: integration-cli/docker_cli_run_test.go [hunk 3]
```diff
@@ -4137,3 +4137,42 @@ func (s *DockerSuite) TestRunNamedVolumeCopyImageData(c *check.C) {
...
+
+func (s *DockerSuite) TestRunNamedVolumeNotRemoved(c *check.C) {
+	prefix := ""
+	if daemonPlatform == "windows" {
+		prefix = "c:"
+	}
+
+	dockerCmd(c, "volume", "create", "--name", "test")
+
+	dockerCmd(c, "run", "--rm", "-v", "test:/foo", "-v", prefix+"/bar", "busybox", "true")
```
Comment (jhowardmsft) [inline integration-cli/docker_cli_run_test.go]: You're missing a `prefix` on the first volume. Also a few lines down.

File: integration-cli/docker_cli_run_test.go [hunk 4]
```diff
@@ -4137,3 +4137,42 @@ func (s *DockerSuite) TestRunNamedVolumeCopyImageData(c *check.C) {
...
+}
+
+func (s *DockerSuite) TestRunNamedVolumesFromNotRemoved(c *check.C) {
+	prefix := ""
+	if daemonPlatform == "windows" {
+		prefix = "c:"
+	}
+
+	dockerCmd(c, "volume", "create", "--name", "test")
+	dockerCmd(c, "run", "--name=parent", "-v", "test:"+prefix+"/foo", "-v", "/bar", "busybox", "true")
```
Comment (jhowardmsft) [inline integration-cli/docker_cli_run_test.go]: missing `prefix` on the second `-v`

**Comment by vdemeester** [comment]
Docs LGTM 🐹

File: docs/reference/commandline/rm.md [hunk 5]
```diff
@@ -45,3 +45,17 @@ This command will delete all stopped containers. The command
...
+  redis
+
+This command will remove the container and any volumes associated with it.
+Note that if a volume was specified with a name, it will not be removed.
+
+  $ docker create -v awesome:/foo -v /bar --name hello redis
+  hello
+  $ docker rm -v hello
+
+In this example, the volume for `/foo` will remain in tact, but the volume for
```
Comment (MHBauer) [inline docs/reference/commandline/rm.md]: `in tact` -> `intact`

**Comment by MHBauer** [comment]
docs nit, but otherwise LTGM. reading the tests helped me understand. The two new ones are simple and good for understanding the behavior. The full cases they represent might make better examples than the given examples that are present, but that is a balance between verbosity and education. It would be best if we could somehow link the code directly into the docs, but I don't think that's feasible.

**Comment by cpuguy83** [comment]
@MHBauer thanks, fixed the mistake.

**Comment by thaJeztah** [comment]
Hit this one on gccgo https://github.com/docker/docker/issues/19368

**Comment by thaJeztah** [comment]
And weird message on win2lin;

```
22:22:29 INFO: Commmit hash is d17261b
22:22:29 INFO: Attempting curl to ping the DIND daemon
22:22:29 ERROR: Invalid syntax. Default option is not allowed more than '1' time(s).
22:22:29 Type "TIMEOUT /?" for usage.
```

**Comment by tiborvass** [comment]
gccgo hit again #19368... merging

**Comment by thaJeztah** [comment]
Added changelog; it's a notable bug fix
