### PR TITLE
volume create error on conflict option

### LINKED ISSUE #15998: Docker "volume create" doesn't error on conflicting options
When creating a volume, `docker volume create` should produce an error if a conflicting option is provided. Currently the conflicting option is silently ignored

```bash
$ docker volume create --name myvolume
myvolume
$ docker volume create --name myvolume --driver convoy
myvolume
```

**expected result**

```bash
$ docker volume create --name myvolume
myvolume
$ docker volume create --name myvolume --driver convoy
Error: cannot create volume 'myvolume' using the 'convoy' driver because ... (some description)
```

### PR DESCRIPTION
**Pull request by azurezk**
fixes #15998
Signed-off-by: Kun Zhang zkazure@gmail.com

### CODE REVIEW

**Comment by runcom** [comment]
Can you add a test case for this change just to make sure the command errors out correctly? 

Btw the linked issue seems to have a broader scope in making sure conflicting options errors out, does that only apply to driver names?

**Comment by azurezk** [comment]
added test. :)
I m not sure about other conflict cases. @runcom  @thaJeztah @cpuguy83

File: integration-cli/docker_cli_volume_test.go [hunk 1]
```diff
@@ -18,6 +18,18 @@ func (s *DockerSuite) TestVolumeCliCreate(c *check.C) {
 	c.Assert(name, check.Equals, "test")
 }
 
+func (s *DockerSuite) TestVolumeCliCreateOptionConflict(c *check.C) {
+	dockerCmd(c, "volume", "create")
```
Comment (runcom) [inline integration-cli/docker_cli_volume_test.go]: is this really needed?

File: integration-cli/docker_cli_volume_test.go [hunk 2]
```diff
@@ -18,6 +18,18 @@ func (s *DockerSuite) TestVolumeCliCreate(c *check.C) {
...
+
+	dockerCmd(c, "volume", "create", "--name=test")
+	_, _, err := dockerCmdWithError("volume", "create", "--name", "test", "--driver", "nosuchdriver")
+	c.Assert(err, check.Not(check.IsNil), check.Commentf("volume create excepted to be failed on creating an existed volume with a different driver name"))
```
Comment (runcom) [inline integration-cli/docker_cli_volume_test.go]: nit, you could use `check.NotNil` directly

**Comment by runcom** [comment]
just two small comments, otherwise LGTM, ping @cpuguy83 @thaJeztah

File: daemon/volumes.go [hunk 3]
```diff
@@ -136,6 +136,9 @@ func (s *volumeStore) Create(name, driverName string, opts map[string]string) (v
 	if vc, exists := s.vols[name]; exists {
 		v := vc.Volume
 		s.mu.Unlock()
+		if driverName != v.DriverName() {
```
Comment (cpuguy83) [inline daemon/volumes.go]: This should go in daemon.VolumeCreate (in daemon/create.go) instead of here.
In cases where you have `docker run -v some_name:/foo --volume-driver other_driver` and `some_name` is an existing volume but on a different driver, this should work.

**Comment by thaJeztah** [comment]
> Btw the linked issue seems to have a broader scope in making sure conflicting options errors out, does that only apply to driver names?

At this moment, yes, only the driver: Docker doesn't keep track of other options (e.g. driver-options used to create the volume), so it's not possible to check if a user is trying to create a volume with the same name, but different options.

**Comment by runcom** [comment]
@thaJeztah gotcha thanks

**Comment by azurezk** [comment]
change to daemon/create.go :) @cpuguy83

File: daemon/create.go [hunk 4]
```diff
@@ -139,6 +139,15 @@ func (daemon *Daemon) VolumeCreate(name, driverName string, opts map[string]stri
 		name = stringid.GenerateNonCryptoID()
 	}
 
+	daemon.volumes.mu.Lock()
```
Comment (cpuguy83) [inline daemon/create.go]: Sorry, this is not quite correct.
We can remove all this low-level check here and just check if the volume returned by `daemon.volumes.Create` has the same driver as `driverName`.

Comment (calavera) [inline daemon/create.go]: @cpuguy83 I guess the problem with that is that you'd still end up creating the volume, and we want to avoid it.
I agree though that this might not be the right place to put this code. What do you think about adding this inside `volume.Create` and returning an "already created" error?

Comment (cpuguy83) [inline daemon/create.go]: Well we do want it to be created if it doesn't exist, which would be the only case it would actually be created.

The thing with having it return an error when it already exists is it would break named volumes on run.

**Comment by azurezk** [comment]
I misunderstood your meaning. Updated!  @cpuguy83

File: daemon/create.go [hunk 5]
```diff
@@ -144,5 +144,9 @@ func (daemon *Daemon) VolumeCreate(name, driverName string, opts map[string]stri
 	if err != nil {
 		return nil, err
 	}
+
+	if driverName != "" && v.DriverName() != driverName {
```
Comment (runcom) [inline daemon/create.go]: is the emtpy string check needed here?

File: daemon/create.go [hunk 6]
```diff
@@ -144,5 +144,9 @@ func (daemon *Daemon) VolumeCreate(name, driverName string, opts map[string]stri
...
+		return nil, fmt.Errorf("cannot create volume '%s' using the '%s' driver because the volume '%s' already exists and the driver name is '%s'", name, driverName, name, v.DriverName())
```
Comment (cpuguy83) [inline daemon/create.go]: error message should start with `Conflict`, and we should add the error response to the API docs.

File: daemon/create.go (hunk 5 above)
Comment (azurezk) [inline daemon/create.go]: @runcom , yes , because if user don' t give a driver name when create a  volume the driverName will be "" and the volume will be given a default driver name "local", no matter the volume is exist or not, it' s not a conflict case

Comment (runcom) [inline daemon/create.go]: oh gotcha!

Comment (cpuguy83) [inline daemon/create.go]: Yep, definitely needed but we need to get the default volume driver if it is `""` instead of ignoring.

**Comment by azurezk** [comment]
have updated! @cpuguy83

**Comment by calavera** [comment]
Change LGTM, but it needs be be squashed into a single commit.

**Comment by azurezk** [comment]
Forgot to squash , updated!

**Comment by cpuguy83** [comment]
Cool, LGTM, moving to docs review.

**Comment by cpuguy83** [comment]
@azurezk Actually if you can update the commit message to just a single message and a single sign-off that would be amazing. Thanks!

**Comment by azurezk** [comment]
No problem! changed @cpuguy83

**Comment by cpuguy83** [comment]
Thanks!

File: docs/reference/commandline/volume_create.md [hunk 7]
```diff
@@ -29,6 +29,8 @@ The mount is created inside the container's `/src` directory. Docker does not su
 
 Multiple containers can use the same volume in the same time period. This is useful if two containers need access to shared data. For example, if one container writes and the other reads the data.
 
+If a volume is already exist, you cannot create again with a different driver name and with the same volume name. If you create again with the same name and no drivername or the same dirvername, you just get the existing volume.
```
Comment (calavera) [inline docs/reference/commandline/volume_create.md]: `You cannot create a volume if there is a volume already registered with the same name in other driver. Docker returns the existent volume ID if the volume name conflicts and you don't specify the driver`

Comment (calavera) [inline docs/reference/commandline/volume_create.md]: @azurezk do you mind review this paragraph?

File: daemon/create.go [hunk 8]
```diff
@@ -151,5 +153,9 @@ func (daemon *Daemon) VolumeCreate(name, driverName string, opts map[string]stri
 	if err != nil {
 		return nil, err
 	}
+
+	if (driverName != "" && v.DriverName() != driverName) || (driverName == "" && v.DriverName() != volume.DefaultDriverName) {
```
Comment (tiborvass) [inline daemon/create.go]: @azurezk this check should probably be inside `volumes.Create()` otherwise the volume is already created. See @coolljt0725's #16278 PR that has a better logic IMO.

Comment (azurezk) [inline daemon/create.go]: @tiborvass  I did that way in the first time. But as @cpuguy83  comments,  "This should go in daemon.VolumeCreate (in daemon/create.go) instead of here.
In cases where you have docker run -v some_name:/foo --volume-driver other_driver and some_name is an existing volume but on a different driver, this should work."

Comment (tiborvass) [inline daemon/create.go]: oh ok i'll let @calavera chime in too

Comment (calavera) [inline daemon/create.go]: yeah, this is okay here.

Comment (tiborvass) [inline daemon/create.go]: ok thanks for clarifying, put in docs review

Comment (calavera) [inline daemon/create.go]: maybe we could leave a comment in the code about why this is here :smile_cat:

File: daemon/create.go [hunk 9]
```diff
@@ -151,5 +153,9 @@ func (daemon *Daemon) VolumeCreate(name, driverName string, opts map[string]stri
...
+		return nil, fmt.Errorf("Conflict. Cannot create volume '%s' using the '%s' driver because the volume '%s' already exists and the driver name is '%s'.", name, driverName, name, v.DriverName())
```
Comment (calavera) [inline daemon/create.go]: @azurezk do you mind to move this error to our new `errors` package?

See examples in: https://github.com/docker/docker/blob/master/errors/daemon.go

**Comment by calavera** [comment]
I moved it back to code-review because I'd like to have the error in the errors package. But after that, I'll move it forward.

**Comment by azurezk** [comment]
@calavera   have updated

File: integration-cli/docker_cli_volume_test.go [hunk 10]
```diff
@@ -20,6 +20,16 @@ func (s *DockerSuite) TestVolumeCliCreate(c *check.C) {
 	c.Assert(name, check.Equals, "test")
 }
 
+func (s *DockerSuite) TestVolumeCliCreateOptionConflict(c *check.C) {
+	dockerCmd(c, "volume", "create", "--name=test")
+	_, _, err := dockerCmdWithError("volume", "create", "--name", "test", "--driver", "nosuchdriver")
+	c.Assert(err, check.NotNil, check.Commentf("volume create excepted to be failed on creating an existed volume with a different driver name"))
```
Comment (calavera) [inline integration-cli/docker_cli_volume_test.go]: can we test that the error we get is the right error we expect? I'm not completely sure this command fails where we expect it to fail.

File: errors/daemon.go [hunk 11]
```diff
@@ -827,4 +827,13 @@ var (
 		Description:    "While trying to delete a container, there was an error trying to delete one of its volumes",
 		HTTPStatusCode: http.StatusInternalServerError,
 	})
+
+	// ErrorVolNameConflict is generated when an error occurred while
+	// trying to create a volume that has existed using different driver.
+	ErrorVolNameConflict = errcode.Register(errGroup, errcode.ErrorDescriptor{
```
Comment (calavera) [inline errors/daemon.go]: I think this should be `ErrorVolumeNameTaken` better, with the value `VOLUME_NAME_TAKEN`.

File: daemon/create.go [hunk 12]
```diff
@@ -152,5 +153,10 @@ func (daemon *Daemon) VolumeCreate(ctx context.Context, name, driverName string,
 	if err != nil {
 		return nil, err
 	}
+
+	// keep "docker run -v existing_volume:/foo --volume-driver other_driver" work
+	if (driverName != "" && v.DriverName() != driverName) || (driverName == "" && v.DriverName() != volume.DefaultDriverName) {
```
Comment (calavera) [inline daemon/create.go]: I wonder if we should move this logic to the before calling `daemon.volumes.Create` in this same function. I'm worried we'd end up sending unnecessary creation requests to the drivers. What about something like:

```go
v, err := daemon.volumes.Get(name)
if err != errors.ErrorNoSuchVolume || v.DriverName() != driverName {
   // Return error here
}

v, err := daemon.volumes.Create...
```

Comment (azurezk) [inline daemon/create.go]: IMHO, I think it just did the same thing as "volumes.Create" does. 
func (s *VolumeStore) Create(name, driverName string, opts map[string]string) (volume.Volume, error) {
	s.mu.Lock()
	if vc, exists := s.vols[name]; exists {
		v := vc.Volume
		s.mu.Unlock()
		return v, nil
	}
Create() just do the same check and return the existed volume if it exists. Is it necessary to do the same thing?

**Comment by jfrazelle** [comment]
needs rebase

**Comment by azurezk** [comment]
rebased

**Comment by jfrazelle** [comment]
ping @cpuguy83

**Comment by icecrime** [comment]
Moving to docs review, thanks!

File: docs/reference/commandline/volume_create.md [hunk 13]
```diff
@@ -29,6 +29,8 @@ The mount is created inside the container's `/src` directory. Docker does not su
 
 Multiple containers can use the same volume in the same time period. This is useful if two containers need access to shared data. For example, if one container writes and the other reads the data.
 
+You cannot create a volume if there is a volume already registered with the same name in other driver. Docker returns the existent volume ID if the volume name conflicts and you don't specify the driver.
```
Comment (thaJeztah) [inline docs/reference/commandline/volume_create.md]: Slightly confused by the description here; if I understand correctly, the new behavior is;

- if I try to create a volume with the same name but a different driver, I receive an error
- if I try to create a volume with the same name, but *don't* specify a driver, it is assumed I want to re-use the existing volume, so I don't get an error

Correct?

Comment (azurezk) [inline docs/reference/commandline/volume_create.md]: correct!

Comment (thaJeztah) [inline docs/reference/commandline/volume_create.md]: Thanks! I'll see if I can come with a better description, unless @moxiegirl beats me to it :-)

File: errors/daemon.go [hunk 14]
```diff
@@ -863,4 +863,13 @@ var (
 		Description:    "While verifying the container's 'HostConfig', cpuset memory nodes provided aren't available in the container's cgroup available set",
 		HTTPStatusCode: http.StatusInternalServerError,
 	})
+
+	// ErrorVolumeNameTaken is generated when an error occurred while
+	// trying to create a volume that has existed using different driver.
+	ErrorVolumeNameTaken = errcode.Register(errGroup, errcode.ErrorDescriptor{
+		Value:          "VOLUME_NAME_TAKEN",
+		Message:        "Cannot create volume '%s' using the '%s' driver because the volume already exists and the driver name is '%s'.",
```
Comment (moxiegirl) [inline errors/daemon.go]: A volume name %s  already exists with the %s driver. Choose a different volume name.

File: docs/reference/commandline/volume_create.md (hunk 13 above)
Comment (moxiegirl) [inline docs/reference/commandline/volume_create.md]: @azurezk Thank you for the contribution.  Couple of changes to text and error message.

---> https://gist.github.com/moxiegirl/77c1f117d3080d1c95c6

Volume names must be unique among drivers.  This means you cannot use the same volume name with two different drivers.  If you attempt this `docker` returns an error:

```
A volume named  %s  already exists with the %s driver. Choose a different volume name.
```

If you specify a volume name already in use on the current driver, Docker assumes you want to re-use the existing volume and does not return an error.

File: integration-cli/docker_cli_volume_test.go [hunk 15]
```diff
@@ -20,6 +22,18 @@ func (s *DockerSuite) TestVolumeCliCreate(c *check.C) {
 	c.Assert(name, check.Equals, "test")
 }
 
+func (s *DockerSuite) TestVolumeCliCreateOptionConflict(c *check.C) {
+	dockerCmd(c, "volume", "create", "--name=test")
+	out, _, err := dockerCmdWithError("volume", "create", "--name", "test", "--driver", "nosuchdriver")
+	c.Assert(err, check.NotNil, check.Commentf("volume create excepted to be failed on creating an existed volume with a different driver name"))
```
Comment (moxiegirl) [inline integration-cli/docker_cli_volume_test.go]: c.Assert(err, check.NotNil, check.Commentf("volume create excepted to be failed on creating an existed volume with a different driver name"))

c.Assert(err, check.NotNil, check.Commentf("volume create exception volume name already in use with another driver"))

**Comment by azurezk** [comment]
updated @moxiegirl

**Comment by thaJeztah** [comment]
LGTM, thanks @azurezk !

**Comment by icecrime** [comment]
Ping @moxiegirl: all good? ;-)

**Comment by moxiegirl** [comment]
LGTM @icecrime I'll let you coders merge the GO

File: docs/reference/commandline/volume_create.md [hunk 16]
```diff
@@ -29,6 +29,14 @@ The mount is created inside the container's `/src` directory. Docker does not su
 
 Multiple containers can use the same volume in the same time period. This is useful if two containers need access to shared data. For example, if one container writes and the other reads the data.
 
+Volume names must be unique among drivers.  This means you cannot use the same volume name with two different drivers.  If you attempt this `docker` returns an error:
+
+```
+A volume named  %s  already exists with the %s driver. Choose a different volume name.
```
Comment (cpuguy83) [inline docs/reference/commandline/volume_create.md]: Oops, `%s` is not what we want here :)

Comment (azurezk) [inline docs/reference/commandline/volume_create.md]: Oh, I open #17515 to fix it
