### PR TITLE
Fix #20942 TestContainerPsContext unit test

### LINKED ISSUE #20942: Flaky test: TestContainerPsContext ?
Flaky test on WindowsTP4? https://jenkins.dockerproject.org/job/Docker-PRs-WoW-TP4/2071/console

Seen on https://github.com/docker/docker/pull/20903

```
02:55:41 ---> Making bundle: test-unit (in bundles/1.11.0-dev/test-unit)
02:55:41 Fri Mar  4 02:55:41 CUT 2016
02:56:02 ok  	github.com/docker/docker/api	0.284s	coverage: 92.5% of statements
02:56:21 ok  	github.com/docker/docker/api/client	0.098s	coverage: 1.3% of statements
02:56:21 --- FAIL: TestContainerPsContext (0.31s)
02:56:21 	custom_test.go:67: Expected Less than a second, was 1 seconds
02:56:21 FAIL
02:56:21 coverage: 90.6% of statements
```

### PR DESCRIPTION
**Pull request by vdemeester**
Fixing #20942 TestContainerPsContext unit test 🐙.

Depending on how much time each case takes, it could be more than 1 second (on windows :sweat_smile:). Update it to print `About a minute` instead, thus it gives us a whole minute for the loop to complete (which should be more than plenty).

Fixes #20942 

🐸

Signed-off-by: Vincent Demeester vincent@sbr.pm

### CODE REVIEW

File: api/client/formatter/custom_test.go [hunk 1]
```diff
@@ -55,7 +55,7 @@ func TestContainerPsContext(t *testing.T) {
 		{types.Container{SizeRw: 10, SizeRootFs: 20}, true, "10 B (virtual 20 B)", sizeHeader, ctx.Size},
 		{types.Container{}, true, "", labelsHeader, ctx.Labels},
 		{types.Container{Labels: map[string]string{"cpu": "6", "storage": "ssd"}}, true, "cpu=6,storage=ssd", labelsHeader, ctx.Labels},
-		{types.Container{Created: unix}, true, "Less than a second", runningForHeader, ctx.RunningFor},
+		{types.Container{Created: time.Now().Unix()}, true, "Less than a second", runningForHeader, ctx.RunningFor},
```
Comment (thaJeztah) [inline api/client/formatter/custom_test.go]: What comes after this, "Less than a minute?" can we check for just "Less than" ?

Comment (thaJeztah) [inline api/client/formatter/custom_test.go]: Oh, guess it's xx seconds ago :disappointed:

Comment (vdemeester) [inline api/client/formatter/custom_test.go]: yep, it's `xx seconds ago` :stuck_out_tongue_closed_eyes:

File: api/client/formatter/custom_test.go [hunk 2]
```diff
@@ -55,7 +55,7 @@ func TestContainerPsContext(t *testing.T) {
 		{types.Container{SizeRw: 10, SizeRootFs: 20}, true, "10 B (virtual 20 B)", sizeHeader, ctx.Size},
 		{types.Container{}, true, "", labelsHeader, ctx.Labels},
 		{types.Container{Labels: map[string]string{"cpu": "6", "storage": "ssd"}}, true, "cpu=6,storage=ssd", labelsHeader, ctx.Labels},
-		{types.Container{Created: unix}, true, "Less than a second", runningForHeader, ctx.RunningFor},
+		{types.Container{Created: unix}, true, "About a minute", runningForHeader, ctx.RunningFor},
```
Comment (thaJeztah) [inline api/client/formatter/custom_test.go]: Actual text is "About a minute ago" does that matter here?

Comment (vdemeester) [inline api/client/formatter/custom_test.go]: :sweat_smile:

**Comment by thaJeztah** [comment]
LGTM (if tests are green, haha)

File: api/client/formatter/custom_test.go (hunk 2 above)
Comment (vdemeester) [inline api/client/formatter/custom_test.go]: Well it's "About a minute", no "*ago*" :angel:

Comment (thaJeztah) [inline api/client/formatter/custom_test.go]: LOL, just realized I looked at the `CREATED` column :blush:

**Comment by runcom** [comment]
LGTM

**Comment by vdemeester** [comment]
:tada: :100: :blush:

**Comment by thaJeztah** [comment]
Oh!! Congrats!! :100:
