### PR TITLE
daemon: rename: don't reload endpoint from datastore

### LINKED ISSUE #47186: docker container rename fails
### Description

I installed docker-ce 25.0.0 on a fresh Debian bookworm machine using the recommended package source. Then I tried renaming a running container multiple times, from the second try it fails with the error message: 

```
Error response from daemon: Unable to complete atomic operation, key modified
Error: failed to rename container named admiring_beaver.1
```

### Reproduce

1. create a running container: `docker run -it debian:latest bash`
2. find the container name `docker ps -a` -> e.g. name1
3. `docker container rename name1 name2` -> works
4. `docker container rename name2 name3` -> fails

### Expected behavior

`docker container rename` should work without an error.

### docker version

```bash
Client: Docker Engine - Community
 Version:           25.0.0
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        e758fe5
 Built:             Thu Jan 18 17:09:59 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.0
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       615dfdf
  Built:            Thu Jan 18 17:09:59 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.27
  GitCommit:        a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc:
  Version:          1.1.11
  GitCommit:        v1.1.11-0-g4bccb38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    25.0.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 25.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc version: v1.1.11-0-g4bccb38
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-17-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.874GiB
 Name: debian-2gb-nbg1-1
 ID: 969fcd6d-78f0-48f9-bdc5-976fe76d87ae
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by akerouanton**
- Related to https://github.com/moby/moby/pull/46853
- fixes https://github.com/moby/moby/issues/47186

**- What I did**

Commit 8b7af1d0f added some code to update the DNSNames of all endpoints attached to a sandbox by loading a new instance of each affected endpoints from the datastore through a call to `Network.EndpointByID()`.

This method then calls `Network.getEndpointFromStore()`, that in turn calls `store.GetObject()`, which then calls `cache.get()`, which calls `o.CopyTo(kvObject)`. This effectively creates a fresh new instance of an Endpoint. However, endpoints are already kept in memory by Sandbox, meaning we now have two in-memory instances of the same Endpoint.

As it turns out, libnetwork is built around the idea that no two objects representing the same thing should live in-memory, otherwise breaking mutex locking and optimistic locking (as both instances will have a drifting version tracking ID -- dbIndex in libnetwork parliance).

In this specific case, this bug materializes by container rename failing when applied a second time for a given container. An integration test is added to make sure this doesn't happen in the future.

**- How I did it**

This is a quick-fix; instead of loading endpoints through `Network.EndpointByID()`, `Sandbox.getEndpoint()` was made public and is now used. I also added a comment on `Network.EndpointByID()` saying this method should *never* be used -- and actually it should be removed in a follow-up.

**- How to verify it**

I added an integration test to test that `docker rename` can be called multiple times for the same container.

**- Description for the changelog**

- Fix a bug that prevented a container from being renamed twice

### CODE REVIEW

**Review by robmry — APPROVED** [review]
LGTM

File: libnetwork/network.go [hunk 1]
```diff
@@ -1276,8 +1276,8 @@ func (n *Network) EndpointByName(name string) (*Endpoint, error) {
 	return e, nil
 }
 
-// EndpointByID returns the Endpoint which has the passed id. If not found,
-// the error ErrNoSuchEndpoint is returned.
+// EndpointByID should *never* be called as it's going to create a 2nd instance of an Endpoint. The first one lives in
+// the Sandbox the endpoint is attached to. Instead, the endpoint should be retrieved by calling [Sandbox.Endpoints()].
 func (n *Network) EndpointByID(id string) (*Endpoint, error) {
```
Comment (corhere) [inline libnetwork/network.go:1281]: Whereas `ds.cache.get()` makes a copy, `ds.cache.list()` does not. `func (*Network) Endpoints()` is implemented in terms of the latter, so could this function be fixed by implementing it in terms of `n.Endpoints()`?

File: daemon/rename.go [hunk 2]
```diff
@@ -121,15 +122,20 @@ func (daemon *Daemon) ContainerRename(oldName, newName string) (retErr error) {
...
+			sbEps[ep.Network()] = ep
+		}
+
 		for nwName, epConfig := range container.NetworkSettings.Networks {
 			nw, err := daemon.FindNetwork(nwName)
 			if err != nil {
 				return err
 			}
 
-			ep, err := nw.EndpointByID(epConfig.EndpointID)
```
Comment (corhere) [inline daemon/rename.go:130]: `Sandbox` has an unexported method `getEndpoint(id string)`; why not export and use that?

File: libnetwork/network.go (hunk 1 above)
Comment (akerouanton) [reply libnetwork/network.go:1281]: Indeed, the longer term fix would be to change the signature of `ds.GetObject()` to make it return the `KVObject` it retrieves from the cache. But that would impact all `GetObject()` callsites and I'm not comfortable backporting such a change to v25.0 (see [here](https://github.com/search?q=repo%3Amoby/moby%20GetObject&type=code) for the complete list of callsites).

By doing so, we'll be able to finally ditch 'KVObject.CopyTo()` :tada:

Comment (corhere) [reply libnetwork/network.go:1281]: Huh? I didn't ask about changing the signature of `ds.GetObject()`. I asked about implementing `func (*Network) EndpointByID` in terms of `func (*Network) Endpoints`.

**Review by corhere — APPROVED** [review]

**Comment by thaJeztah** [comment]
nice find on the `sb.getendPoint` @corhere !

**Review by thaJeztah — APPROVED** [review]
LGTM
