### PR TITLE
 fix(distribution): digest cache should not be moved if it was an auth

### LINKED ISSUE #36309: docker pull full layer of image even base image already on the host
when pull image from our on-premise registry on a host that has already pulled base image, it still perform a full download even there is only one layer different, the interesting is when I delete the derived image then pull again, it will only pull the difference

**Steps to reproduce the issue:**
1. pull base image, build a new image base on that base image and push to registry
2. on a brand new host, pull the base image first, then pull the newly created image

**Describe the results you received:**
it pull all layers even base image has already on the host
this is inspect from base image
image

this is inspect from derived image 
image

there is only on layer difference

image

when I delete the derived image, it will only delete the difference

image

then pull again

image

that's obvious that most of the layers are identical, and shared by both base and derived image.

**Describe the results you expected:**
only pull diff layers

**Additional information you deem important (e.g. issue happens only occasionally):**
the base image and derived image are pushed to registry by two different account

**Output of `docker version`:**

```
Docker version 1.11.1
```

**Output of `docker info`:**

```
Containers: 12
 Running: 8
 Paused: 0
 Stopped: 4
Images: 127
Server Version: 1.11.1
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 62.71 GiB
Name: srmbuffer010210212101.ztt
ID: 3PZ4:7DWX:4TPZ:A4FV:MZT5:W5EM:TZYA:45OC:PQXG:M4QZ:MVHK:45XT
Docker Root Dir: /home/acs/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: true
Live Restore Enabled: true
```

### PR DESCRIPTION
**Pull request by xujihui1985**
fixes https://github.com/moby/moby/issues/36309

**- How I did it**
when push mount candidate to registry, first check if error is autherror, then check if user has authConfig
if both autherror while user has not login, do not remove the local cache.
**- How to verify it**
push the image without login, and login again, you still can mount the shared layer
**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @dmcgowan @tonistiigi PTAL

**Comment by xujihui1985** [comment]
ping @dmcgowan

File: distribution/push_v2.go [hunk 1]
```diff
@@ -580,14 +600,14 @@ func getMaxMountAndExistenceCheckAttempts(layer PushLayer) (maxMountAttempts, ma
 		// then fallback to upload
 		return 4, 3, true
 
-	// middle sized blobs; if we could not get the size, assume we deal with middle sized blob
+		// middle sized blobs; if we could not get the size, assume we deal with middle sized blob
```
Comment (aaronlehmann) [inline distribution/push_v2.go]: This comment should not have the extra indentation.

File: distribution/push_v2.go [hunk 2]
```diff
@@ -580,14 +600,14 @@ func getMaxMountAndExistenceCheckAttempts(layer PushLayer) (maxMountAttempts, ma
...
 	case size > smallLayerMaximumSize, err != nil:
 		// 1st attempt to mount blobs of average size few times
 		// 2nd try at most 1 existence check if there's an existing mapping to the target repository
 		// then fallback to upload
 		return 3, 1, false
 
-	// small blobs, do a minimum number of checks
+		// small blobs, do a minimum number of checks
```
Comment (aaronlehmann) [inline distribution/push_v2.go]: This comment should not have the extra indentation.

File: distribution/push_v2_test.go [hunk 3]
```diff
@@ -9,10 +9,15 @@ import (
...
 	"github.com/docker/distribution/manifest/schema2"
 	"github.com/docker/distribution/reference"
+	refstore "github.com/docker/docker/reference"
 	"github.com/docker/docker/distribution/metadata"
 	"github.com/docker/docker/layer"
 	"github.com/docker/docker/pkg/progress"
 	"github.com/opencontainers/go-digest"
+	"github.com/docker/docker/api/types"
+	"github.com/docker/docker/registry"
+	"net/url"
```
Comment (aaronlehmann) [inline distribution/push_v2_test.go]: Put this above with "net/http".

File: distribution/push_v2.go [hunk 4]
```diff
@@ -397,8 +416,9 @@ func (pd *v2PushDescriptor) Upload(ctx context.Context, progressOutput progress.
 			return distribution.Descriptor{}, retryOnError(err)
 		}
 	}
-	defer layerUpload.Close()
-
+	if layerUpload != nil {
```
Comment (aaronlehmann) [inline distribution/push_v2.go]: It doesn't seem right to allow `layerUpload` to be nil and then immediately afterwards call `pd.uploadUsingSession` with `layerUpload`. Why would `layerUpload` be nil when `bs.Create` returned no error a few lines above?

File: distribution/push_v2.go [hunk 5]
```diff
@@ -360,11 +364,26 @@ func (pd *v2PushDescriptor) Upload(ctx context.Context, progressOutput progress.
 				return distribution.Descriptor{}, xfer.DoNotRetry{Err: err}
 			}
 			return err.Descriptor, nil
+		case errcode.Errors:
+			for _, e := range err {
+				switch e := e.(type) {
+				case errcode.Error:
+					if e.Code == errcode.ErrorCodeUnauthorized {
+						logrus.Debugf("error code is unauthoriedError")
```
Comment (aaronlehmann) [inline distribution/push_v2.go]: `unauthoriedError` is misspelled.

File: distribution/push_v2.go [hunk 6]
```diff
@@ -360,11 +364,26 @@ func (pd *v2PushDescriptor) Upload(ctx context.Context, progressOutput progress.
...
+			}
 		default:
 			logrus.Infof("failed to mount layer %s (%s) from %s: %v", diffID, mountCandidate.Digest, mountCandidate.SourceRepository, err)
 		}
 
-		if len(mountCandidate.SourceRepository) > 0 &&
+		if isUnauthorizedError && !pd.pushState.hasAuthInfo {
+			// break the attempt loop as user has not login
+			logrus.Infoln("failed to push image to registry because unauthorized error and user not login")
+			break
```
Comment (aaronlehmann) [inline distribution/push_v2.go]: I think this should continue instead of break. There might be other repos which do not require credentials to mount the blob. The continue can go inside the error checking code, instead of setting an `isUnauthorizedError` variable (it would mean having a label on the candidate loop and using `continue candidateLoop`).

File: distribution/push_v2.go (hunk 1 above)
Comment (xujihui1985) [reply distribution/push_v2.go]: sorry for my ide auto format the code

File: distribution/push_v2.go (hunk 4 above)
Comment (xujihui1985) [reply distribution/push_v2.go]: yes, this is paranoid, when I test the code with mock method I thought that may be the case when error is empty while layerUpload is nil too, and that should not happened

File: distribution/push_v2.go (hunk 6 above)
Comment (xujihui1985) [reply distribution/push_v2.go]: this is modified as you suggested

**Comment by thaJeztah** [comment]
PowerPC failing is due to a flaky test;


https://jenkins.dockerproject.org/job/Docker-PRs-powerpc/8973/console

```
12:00:49 --- FAIL: TestLinksEtcHostsContentMatch (0.53s)
12:00:49 	assertions.go:226: 
                          
	Error Trace:	links_linux_test.go:46
12:00:49 		
	Error:      	Not equal: 
12:00:49 		
	            	expected: "127.0.0.1\tlocalhost\n::1\tlocalhost ip6-localhost ip6-loopback\nfe00::0\tip6-localnet\nff00::0\tip6-mcastprefix\nff02::1\tip6-allnodes\nff02::2\tip6-allrouters\n172.17.0.2\t6fe75c06bdcd\n"
12:00:49 		
	            	received: ""
```


I see that one is being fixed through https://github.com/moby/moby/pull/36569

File: distribution/push_v2.go [hunk 7]
```diff
@@ -360,6 +364,18 @@ func (pd *v2PushDescriptor) Upload(ctx context.Context, progressOutput progress.
...
 			}
 			return err.Descriptor, nil
+		case errcode.Errors:
+			for _, e := range err {
+				switch e := e.(type) {
+				case errcode.Error:
+					if e.Code == errcode.ErrorCodeUnauthorized && !pd.pushState.hasAuthInfo {
+						// continue to try other candidate as other repos may not require credentials to mount the blob
+						logrus.Debugf("failed to push layer to registry because unauthorized error and user not login")
+						continue candidateLoop
```
Comment (dmcgowan) [inline distribution/push_v2.go]: Does the layer upload need to be cancelled here? Maybe instead of a continue statement just ensure that the remove doesn't happen so there are fewer early exit/continue conditions.

Comment (xujihui1985) [reply distribution/push_v2.go]: image

this is my first attempt, what do you think of this?

Comment (xujihui1985) [reply distribution/push_v2.go]: as @aaronlehmann mentioned 
> I think this should continue instead of break. There might be other repos which do not require credentials to mount the blob. The continue can go inside the error checking code, instead of setting an isUnauthorizedError variable (it would mean having a label on the candidate loop and using continue candidateLoop).

is that the reason when authorizedError happened, it should continue to check other candidates?

Comment (xujihui1985) [reply distribution/push_v2.go]: the main difference is do we break here when first authorizedError met or continue to try other candidates

Comment (xujihui1985) [reply distribution/push_v2.go]: do we have some conclusion on this so that I can have another commit before this weekend?  @dmcgowan @aaronlehmann  : )

Comment (aaronlehmann) [reply distribution/push_v2.go]: @dmcgowan is right that this needs to cancel the layer upload.

How about adding `&& !isUnauthorizedError` to `if len(mountCandidate.SourceRepository) > 0...` below, instead of the continue?

Comment (xujihui1985) [reply distribution/push_v2.go]: > How about adding && !isUnauthorizedError to if len(mountCandidate.SourceRepository) > 0... below, instead of the continue?

it looks like it will still continue to try next candidate which is not necessary?

**Comment by aaronlehmann** [comment]
> it looks like it will still continue to try next candidate which is not necessary?
> 
I think it's a good idea to try the next candidate, but don't feel strongly.

File: distribution/push_v2.go [hunk 8]
```diff
@@ -360,11 +364,26 @@ func (pd *v2PushDescriptor) Upload(ctx context.Context, progressOutput progress.
...
+				}
+			}
 		default:
 			logrus.Infof("failed to mount layer %s (%s) from %s: %v", diffID, mountCandidate.Digest, mountCandidate.SourceRepository, err)
 		}
 
+		// when error is unauthorizedError and user don't hasAuthInfo that's the case user don't has right to push layer to register
+		// and he hasn't login either, in this case candidate cache should be removed
 		if len(mountCandidate.SourceRepository) > 0 &&
+			!(isUnauthorizedError && !pd.pushState.hasAuthInfo) &&
```
Comment (xujihui1985) [inline distribution/push_v2.go]: @dmcgowan  @aaronlehmann  please have a look at this commit, hope that makes you happy

**Review by aaronlehmann — APPROVED** [review]

File: distribution/push_v2.go (hunk 8 above)
Comment (xujihui1985) [reply distribution/push_v2.go]: @dmcgowan let me know if you have any concern with this commit.

**Comment by xujihui1985** [comment]
can we proceed this PR...? 🤓

**Review by thaJeztah — APPROVED** [review]
LGTM (thanks for reviewing @aaronlehmann @dmcgowan)

**Comment by xujihui1985** [comment]
janky status seems not updated, actually it has finished

**Comment by vdemeester** [comment]
[`janky` is green](https://jenkins.dockerproject.org/job/Docker-PRs/48652/console) 👼 not sure why the check status is not up-to-date
