### PR TITLE
Fix duplicate mount points for multiple `--volumes-from` in `docker run`

### LINKED ISSUE #21845: Cannot remove docker volume
**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 47
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 295
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.19-boot2docker
Operating System: Boot2Docker 1.10.3 (TCL 6.4.1); master : 625117e - Thu Mar 10 22:09:02 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.1 MiB
Name: default
ID: XWWF:P22A:CMF2:PGQC:M4DA:2TEH:ZTCG:VIPU:DO2M:IMCC:Q5I3:QQ6T
Debug mode (server): true
 File Descriptors: 10
 Goroutines: 22
 System Time: 2016-04-06T12:05:22.62834683Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: mindaugas
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VirtualBox Version 5.0.16 r105871

**Steps to reproduce the issue:**
1. Create files:
docker-compose-1.yml:

``` yaml
app:
  container_name: app.container
  image: busybox
  volumes_from:
  - data1
  entrypoint: "top"
data1:
  container_name: data1.container
  build: .
  dockerfile: Dockerfile-1
```

docker-compose-2.yml:

``` yaml
app:
  volumes_from:
  - data2
data2:
  container_name: data2.container
  build: .
  dockerfile: Dockerfile-1
```

Dockerfile-1:

```
FROM busybox
ADD . /tmp/data
VOLUME ["/tmp/data"]
CMD ["true"]
```
1. Run containers:

``` bash
docker-compose -f docker-compose-1.yml -f docker-compose-2.yml up -d
```
1. Remove containers:

``` bash
docker rm -f -v $(docker ps -aq)
```

**Describe the results you received:**

```
$ docker rm -f -v $(docker ps -aq)
73ff8a6d5203
6883f51cd6fd
...

$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

$ docker volume ls
DRIVER              VOLUME NAME
local               fc12bdcfce09a647bdd0015d41635154b86352447c07fc5104fc72a958be9538

$ docker volume rm fc12bdcfce09a647bdd0015d41635154b86352447c07fc5104fc72a958be9538
Error response from daemon: Conflict: remove fc12bdcfce09a647bdd0015d41635154b86352447c07fc5104fc72a958be9538: volume is in use - [ad009b5b5c088c4d91917f14b05b9f6f174badcb82c7f603734550b36c20a120]

$ docker rm ad009b5b5c088c4d91917f14b05b9f6f174badcb82c7f603734550b36c20a120
Failed to remove container (ad009b5b5c088c4d91917f14b05b9f6f174badcb82c7f603734550b36c20a120): Error response from daemon: No such container: ad009b5b5c088c4d91917f14b05b9f6f174badcb82c7f603734550b36c20a120

$ docker-machine ssh
Boot2Docker version 1.10.3, build master : 625117e - Thu Mar 10 22:09:02 UTC 2016
Docker version 1.10.3, build 20f81dd

docker@default:~$ sudo /etc/init.d/docker restart
cat: can't open '/var/run/docker.pid': No such file or directory
Need TLS certs for default,127.0.0.1,10.0.2.15,192.168.99.100
-------------------

docker@default:~$ exit

$ docker volume rm fc12bdcfce09a647bdd0015d41635154b86352447c07fc5104fc72a958be9538
fc12bdcfce09a647bdd0015d41635154b86352447c07fc5104fc72a958be9538

$ docker volume ls
DRIVER              VOLUME NAME
```

**Describe the results you expected:**
Successfully removed all docker volume

**Additional information you deem important (e.g. issue happens only occasionally):**
the same issue on my colleague computer (linux) where docker runs locally.

### PR DESCRIPTION
**Pull request by yongtang**
**- What I did**
This fix tries to fix the issue raised in #21845.

The issue with #21845 is that if multiple `--volumes-from` with the same destination has been specified, then one volume will be overridden by the other. This will mess up reference and prevent the overridden volume from being removed at the end.

Issue #21845 was observed with `docker-compose` though it is possible to emulate the same behavior with `docker` alone:
```
$ cat Dockerfile
FROM busybox
VOLUME ["/tmp/data"]
$ docker build -t vimage .
$ docker run --name=data1 vimage true
$ docker run --name=data2 vimage true
$ docker run --name=app --volumes-from=data1 --volumes-from=data2 -d busybox top
$ docker rm -f -v $(docker ps -aq)
$ docker volume ls
$ docker volume rm ...
```

**- How I did it**

This fix tries to address the issue by return an error if duplicate mount points was used with `--volumes-from`.

**- How to verify it**

An integration test has been added.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

aww-cat-cute-kitten-favim com-288946_large

This fix fixes #21845.

/cc @cpuguy83 @vdemeester @thaJeztah 

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

File: daemon/volumes.go [hunk 1]
```diff
@@ -103,6 +103,9 @@ func (daemon *Daemon) registerMountPoints(container *container.Container, hostCo
 		}
 
 		for _, m := range c.MountPoints {
+			if _, ok := mountPoints[m.Destination]; ok {
```
Comment (AkihiroSuda) [inline daemon/volumes.go]: I wonder similar checking about `mountPoints` is needed for this loop (`for _, cfg := range hostConfig.Mounts {}`) as well: https://github.com/yongtang/docker/blob/d231e33926a58a11974bbdd9a038e79fac2217df/daemon/volumes.go#L164-L206

**Comment by thaJeztah** [comment]
CI looks to be failing

```
02:45:57 
02:45:57 ----------------------------------------------------------------------
02:45:57 FAIL: docker_deprecated_api_v124_test.go:87: DockerSuite.TestDeprecatedContainerAPIStartVolumesFrom
02:45:57 
02:45:57 docker_deprecated_api_v124_test.go:110:
02:45:57     c.Assert(status, checker.Equals, http.StatusNoContent)
02:45:57 ... obtained int = 500
02:45:57 ... expected int = 204
02:45:57 
```

**Comment by thaJeztah** [comment]
Interesting, these work:

```
$ docker run -v /bla -v /bla --rm alpine sh
$ docker run -v /bla -v bla:/bla --rm alpine sh
$ docker run -v /bla --tmpfs /bla --rm alpine sh
```

These don't

```
$ docker run -v bla:/bla -v /bla --tmpfs /bla --rm alpine sh
docker: Error response from daemon: Duplicate mount point '/bla'.
See 'docker run --help'.

$ docker run -v bla:/bla --tmpfs /bla --rm alpine sh
docker: Error response from daemon: Duplicate mount point '/bla'.
See 'docker run --help'.
```

Not sure if it's all expected (i.e., can it be a problem as well for anonymous volumes?),
but thought I'd post it here for reference

File: daemon/volumes.go [hunk 2]
```diff
@@ -103,6 +103,9 @@ func (daemon *Daemon) registerMountPoints(container *container.Container, hostCo
...
+				return fmt.Errorf("Duplicate mount point '%s'", m.Destination)
```
Comment (cpuguy83) [inline daemon/volumes.go]: This is really a behavior change.
I think this will end up breaking people who have already brought in a volume and then also do `--volumes-from` on a container with the same volume.

Comment (cpuguy83) [inline daemon/volumes.go]: I think we'll need to pick which one wins and *log* an error for the other one.
And the one we pick is whatever happens to win right now.

**Review by cpuguy83 — CHANGES_REQUESTED** [review]

File: daemon/volumes.go (hunk 1 above)
Comment (yongtang) [inline daemon/volumes.go]: Thanks @AkihiroSuda for the reminder. I will double check for this case.

File: daemon/volumes.go (hunk 2 above)
Comment (yongtang) [inline daemon/volumes.go]: @cpuguy83 @thaJeztah Got that, thanks. Was wondering how to best handle this situation. Will take a look and make sure the previous behavior is preserved.

**Comment by yongtang** [comment]
Update on this PR:

In addition to the issue described above, the following will also prevent volumes from removed:
```
$ docker build -t vimage .
$ docker run --name=data1 vimage true
$ docker run --name=data2 vimage true
$ docker run --name=app --volumes-from=data1 --volumes-from=data2 -v /tmp/data:/tmp/data -d busybox top
$ docker rm -f -v $(docker ps -aq)
$ docker volume ls
$ docker volume rm ...
```

The bind `-v /tmp/data:/tmp/data` will override the mount point as well.

Both the original issue and the bind override issue have been fixed.

Will continue to investigate other scenarios.

**Comment by yongtang** [comment]
Update of the PR (case 3):
In addition to the above two mentioned cases, it is also possible to specify bind with `HostConfig.Mounts` in API:
```
$ docker build -t vimage .
$ docker run --name=data1 vimage true
$ docker run --name=data2 vimage true
$ curl --unix-socket /var/run/docker.sock ...
$ docker rm -f -v $(docker ps -aq)
$ docker volume ls
$ docker volume rm ...
```
This case will also trigger `volume is in use - ...` error. This case is different from case (2) in that `HostConfig.Mounts` is only available in API. Case (2) and Case (3) happens in different places in `registerMountpoint()`.

**Comment by yongtang** [comment]
@cpuguy83 @AkihiroSuda @thaJeztah. The PR has been updated with different possible combinations of scenarios covered. Please take a look and let me know if there are any issues.

**Comment by vdemeester** [comment]
ping @thaJeztah @cpuguy83

**Comment by cpuguy83** [comment]
Is this actually fixed now that references are stored as a map instead of a slice?

File: daemon/volumes.go [hunk 3]
```diff
@@ -121,7 +121,12 @@ func (daemon *Daemon) registerMountPoints(container *container.Container, hostCo
 				}
 				cp.Volume = v
 			}
-
+			if v, ok := mountPoints[m.Destination]; ok {
```
Comment (LK4D4) [inline daemon/volumes.go]: These seven lines are the same three times; maybe we should have a helper for it.

Comment (yongtang) [inline daemon/volumes.go]: Thanks @LK4D4. The PR has been updated with helper func. Please take a look.

**Comment by yongtang** [comment]
Thanks @cpuguy83 for the review. To preserve the behavior we need to deference the old volume that points to the same mount point (when old and new volume point to the same mount point). So the change is needed for the fix.

**Review by LK4D4 — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Not sure if it's the same part that's causing this error, but;

```
docker run -ti --rm --tmpfs /dev/shm:rw,nosuid,nodev,size=8g busybox
docker: Error response from daemon: linux mounts: Duplicate mount point '/dev/shm'.
```

As mentioned here; https://github.com/docker/docker/issues/6758#issuecomment-276229423

**Review by cpuguy83 — APPROVED** [review]
LGTM

This looks like it's fixing a real problem with refcounting.
However our code looks really awful here because we're essentially leaking volumes.
Not sure what to do here at the moment, but we should figure out how to do this better.

File: daemon/volumes.go [hunk 4]
```diff
@@ -85,6 +85,15 @@ func (daemon *Daemon) registerMountPoints(container *container.Container, hostCo
 		}
 	}()
 
+	dereferenceIfExists := func(destination string) {
+		if v, ok := mountPoints[destination]; ok {
+			logrus.Errorf("Duplicate mount point '%s'", destination)
```
Comment (cpuguy83) [inline daemon/volumes.go]: Actually, sorry this looks like it should be `Debug`, not `Error`

**Review by cpuguy83 — CHANGES_REQUESTED** [review]

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by yongtang** [comment]
Thanks @cpuguy83. I agree the current way of handling it is less than ideal. I will spend some time to investigate it and see if we could come up with something better.
