### PR TITLE
Ignore certificate expiry error for top-level inspect

### LINKED ISSUE #29242: [1.13-rc3] getting "certification expired" error on 'docker inspect'
**Description**

I get the following error after upgrading to 1.13.0rc3 on Docker for Mac beta channel today.

```
$ docker inspect something_that_does_not_exist
[]
Error response from daemon: Swarm certificates have expired. To replace them, leave the swarm and join again.
```

The error only appears for containers that do not exist (as listed by `docker ps -a`):

```
$ docker inspect something_that_exists
[…] normal output
```

Below is some diagnostic information.

```
$ docker version
Client:
 Version:      1.13.0-rc3
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        Tue Dec  6 01:15:44 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0-rc3
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        Tue Dec  6 01:15:44 2016
 OS/Arch:      linux/amd64
 Experimental: true

$ docker info
Containers: 71
 Running: 3
 Paused: 0
 Stopped: 68
Images: 95
Server Version: 1.13.0-rc3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 250
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: error
 NodeID:
 Error: Swarm certificates have expired. To replace them, leave the swarm and join again.
 Is Manager: false
 Node Address: 192.168.65.2
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.8.12-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: IEMY:6NDR:XEEJ:5HXA:AZCF:NJMX:KBDX:ATTA:K4RN:O3PF:P5LN:JFR7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 55
 Goroutines: 77
 System Time: 2016-12-08T08:27:54.125249557Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: shykes
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

Thank you!

### PR DESCRIPTION
**Pull request by thaJeztah**
The top-level `docker inspect` command could return an error if the nodes Swarm certificates were expired.

In situations where the user did not explicitly ask for an object-type (`--type=foo`), we should ignore these errors, and consider them equal to "node is not a swarm manager".

This change makes `docker inspect` ignore these errors if no type was specified.

As a further optimization, the "swarm status" result is now stored in a variable, so that other swarm-specific API calls can be skipped.

fixes https://github.com/docker/docker/issues/29242

### CODE REVIEW

File: cli/command/system/inspect.go [hunk 1]
```diff
@@ -105,30 +105,51 @@ func inspectAll(ctx context.Context, dockerCli *command.DockerCli, getSize bool,
 	var inspectAutodetect = []struct {
 		ObjectType      string
 		IsSizeSupported bool
+		IsSwarmObject   bool
```
Comment (aaronlehmann) [inline cli/command/system/inspect.go]: Non-blocking observation: There's no reason for the fields in this structure to be exported.

File: cli/command/system/inspect.go [hunk 2]
```diff
@@ -105,30 +105,51 @@ func inspectAll(ctx context.Context, dockerCli *command.DockerCli, getSize bool,
...
+	// changes in a future release, and client is connecting to a daemon with a
+	// different version.
 	isErrNotSwarmManager := func(err error) bool {
-		return strings.Contains(err.Error(), "This node is not a swarm manager")
+		return strings.Contains(err.Error(), "is not a swarm manager")
+	}
+
+	// FIXME checking for literal string will be problematic if this error
+	// changes in a future release, and client is connecting to a daemon with a
+	// different version.
```
Comment (aaronlehmann) [inline cli/command/system/inspect.go]: I agree it's problematic. In addition to these concerns, there may be other errors we aren't considering which shouldn't be fatal for `inspect`.

I wonder if it would be better to ignore all errors returned from swarm-related endpoints. If there's really some problem communicating with the daemon, the interactions with non-swarm endpoints will trigger a visible error.

File: cli/command/system/inspect.go (hunk 1 above)
Comment (thaJeztah) [inline cli/command/system/inspect.go]: Yes, I doubted here, but they can probably all be unexpected

File: cli/command/system/inspect.go (hunk 2 above)
Comment (tonistiigi) [inline cli/command/system/inspect.go]: For example, this doesn't handle errors from locked swarm.

Comment (thaJeztah) [inline cli/command/system/inspect.go]: I wasn't sure if there were errors we _do_ want to show, but perhaps we should ignore them all indeed, and only show if there is a `--type` set.

Doing so won't make it possible to "skip" all swarm endpoints though; perhaps we should do a check if swarm mode is enabled somehow, and store that result; wdyt?

Comment (aaronlehmann) [inline cli/command/system/inspect.go]: The `/info` endpoint includes a `Swarm` section which has a `LocalNodeState` field. We could check that this field is set to `LocalNodeStateActive` before querying the swarm endpoints.

Comment (thaJeztah) [inline cli/command/system/inspect.go]: i recently was discussing that; the `/info` endpoint isnt really "light weight" nowadays, let me der what otter options we have as well.

For now it probably is the best choice though

Comment (thaJeztah) [inline cli/command/system/inspect.go]: hmf damn autocorrect

**Comment by thaJeztah** [comment]
@aaronlehmann updated the PR, but I don't know how to easily test the actual "certificate expired" case 😅

File: cli/command/system/inspect.go [hunk 3]
```diff
@@ -103,38 +102,53 @@ func inspectPlugin(ctx context.Context, dockerCli *command.DockerCli) inspect.Ge
...
-		{"node", false, inspectNode(ctx, dockerCli)},
-		{"plugin", false, inspectPlugin(ctx, dockerCli)},
+		{"container", true, false, inspectContainers(ctx, dockerCli, getSize)},
+		{"image", false, false, inspectImages(ctx, dockerCli)},
+		{"network", false, false, inspectNetwork(ctx, dockerCli)},
+		{"volume", false, false, inspectVolume(ctx, dockerCli)},
+		{"service", false, true, inspectService(ctx, dockerCli)},
+		{"task", false, true, inspectTasks(ctx, dockerCli)},
+		{"node", false, true, inspectNode(ctx, dockerCli)},
+		{"plugin", false, false, inspectPlugin(ctx, dockerCli)},
```
Comment (aaronlehmann) [inline cli/command/system/inspect.go]: Cosmetic: this may be easier to read if written as follows:

```
{
        objectType: "container",
        isSizeSupported: true,
        objectInspector: inspectContainers(ctx, dockerCli, getSize),
},
{
        objectType: "image",
        objectInspector: inspectImages(ctx, dockerCli),
},
...
```

This would cut down on some noise. Only fields that differ from the default value need to be specified.

The existing code is fine and I don't want to slow down this fix, but thought I would offer the suggestion.

File: cli/command/system/inspect.go [hunk 4]
```diff
@@ -103,38 +102,53 @@ func inspectPlugin(ctx context.Context, dockerCli *command.DockerCli) inspect.Ge
...
 	}
 
-	isErrNotSwarmManager := func(err error) bool {
-		return strings.Contains(err.Error(), "This node is not a swarm manager")
+	// isSwarmManager does an Info API call to verify that the daemon is
+	// a swarm manager.
+	isSwarmManager := func() bool {
+		info, err := dockerCli.Client().Info(ctx)
+		if err != nil {
+			fmt.Fprintf(dockerCli.Err(), "%v\n", err)
```
Comment (aaronlehmann) [inline cli/command/system/inspect.go]: `fmt.Fprintln(dockerCli.Err(), err)` ?

File: cli/command/system/inspect.go [hunk 5]
```diff
@@ -103,38 +102,53 @@ func inspectPlugin(ctx context.Context, dockerCli *command.DockerCli) inspect.Ge
...
 	return func(ref string) (interface{}, []byte, error) {
+		// assume node is an active swarm manager until proven otherwise
+		isSwarmSupported := true
+
 		for _, inspectData := range inspectAutodetect {
-			if typeConstraint != "" && inspectData.ObjectType != typeConstraint {
+			if typeConstraint != "" && inspectData.objectType != typeConstraint {
+				continue
+			}
+			if typeConstraint == "" && inspectData.isSwarmObject && (!isSwarmSupported || !isSwarmManager()) {
```
Comment (aaronlehmann) [inline cli/command/system/inspect.go]: Let's make sure we don't call `isSwarmManager` multiple times.

Perhaps something like the following:

```go
const (
        swarmSupportUnknown = iota
        swarmSupported
        swarmUnsupported
)

isSwarmSupported := swarmSupportUnknown

...

if typeConstraint == "" && inspectData.isSwarmObject {
        if isSwarmSupported == swarmUnsupported || (isSwarmSupported == swarmSupportUnknown && !isSwarmManager()) {
                isSwarmSupported = swarmUnsupported
                continue
        }
}
```

Comment (thaJeztah) [inline cli/command/system/inspect.go]: i'll double check, but i don't think it's called multiple times, as it enters the `if` once the variable is `false`

**Comment by aaronlehmann** [comment]
> i'll double check, but i don't think it's called multiple times, as it enters the if once the variable is false
> 

Makes sense. I was reading it wrong.

File: cli/command/system/inspect.go (hunk 5 above)
Comment (thaJeztah) [inline cli/command/system/inspect.go]: Yup, the current code only calls `isSwarmManager()` once; https://play.golang.org/p/y8MPnLGXl8

**Comment by aaronlehmann** [comment]
LGTM

**Comment by thaJeztah** [comment]
oops, just pushed an update with your suggestions (https://github.com/docker/docker/pull/29246#discussion_r91995921,  https://github.com/docker/docker/pull/29246/files/c758975d679f46f2ab04cefcf9ea48bacc58c9a5#diff-f21a2c264fcc2951a96946cb782076b8) ptal :smile:

**Comment by aaronlehmann** [comment]
Looks even better.

**Comment by tonistiigi** [comment]
LGTM

**Comment by thaJeztah** [comment]
Thinking about https://github.com/docker/docker/pull/29246#discussion_r91997645 some more, @aaronlehmann may be right in the case where swarm _is_ enabled (I was too focussed on the "skip if disabled" case). Let me do another check and update if needed

**Comment by thaJeztah** [comment]
Updated, based on a variation of @aaronlehmann's suggestion, PTAL

**Comment by aaronlehmann** [comment]
Looks good again.

**Comment by thaJeztah** [comment]
Flaky test on Windows?

```
FAIL: docker_api_logs_test.go:15: DockerSuite.TestLogsAPIWithStdout

docker_api_logs_test.go:50:
    c.Fatal("timeout waiting for logs to exit")
... Error: timeout waiting for logs to exit
```

**Comment by Myahr208** [comment]
at 7:40, Nov 12:

<A.i><permission.granted/><open.source><help/>
