### PR TITLE
Fixes content-type/length for stats stream=false

### LINKED ISSUE #13785: Fix error with TestCliStatsNoStreamGetCpu
```
---------------------------------------------------------------------
FAIL: github.com/docker/docker/integration-cli/_test/_obj_test/docker_api_stats.go:12: DockerSuite.TestCliStatsNoStreamGetCpu

github.com/docker/docker/integration-cli/_test/_obj_test/docker_api_stats.go:18:
    ...open github.com/docker/docker/integration-cli/_test/_obj_test/docker_api_stats.go: no such file or directory
... value *errors.errorString = &errors.errorString{s:"error executing docker inspect: exit status 1\nError response from daemon: 404 page not found"} ("error executing docker inspect: exit status 1\nError response from daemon: 404 page not found")
```

### LINKED ISSUE #13910: [1.7.0-rc2] Response of GET /containers/(id)/stats?stream=0 has wrong content type
The new one-time stats feature `GET /containers/(id)/stats?stream=0` returns a json response with content type `text/plain; charset=utf-8`. The correct content type should be `application/json`.

### PR DESCRIPTION
**Pull request by cpuguy83**
Closes #13910
Closes #13785

Opted to not add another 12s+ test for checking the content-type and content length... but can make it separate if desired.

### CODE REVIEW

File: daemon/stats.go [hunk 1]
```diff
@@ -12,31 +13,43 @@ func (daemon *Daemon) ContainerStats(name string, stream bool, out io.Writer) er
...
 			return err
 		}
-		if !stream {
-			break
-		}
 	}
 	return nil
 }
+
+func streamStats(c chan interface{}, out io.Writer) {
```
Comment (tiborvass) [inline daemon/stats.go]: is this some remnants?

Comment (cpuguy83) [inline daemon/stats.go]: whoops!

**Comment by calavera** [comment]
LGTM

File: daemon/stats.go (hunk 1 above)
Comment (cpuguy83) [inline daemon/stats.go]: Updated that

File: integration-cli/docker_api_stats_test.go [hunk 2]
```diff
@@ -10,14 +10,16 @@ import (
 )
 
 func (s *DockerSuite) TestCliStatsNoStreamGetCpu(c *check.C) {
-	out, _ := dockerCmd(c, "run", "-d", "--cpu-quota=2000", "busybox", "/bin/sh", "-c", "while true;do echo 'Hello';done")
+	out, _ := dockerCmd(c, "run", "-d", "busybox", "/bin/sh", "-c", "while true;do echo 'Hello'; sleep 0.1; done")
```
Comment (tiborvass) [inline integration-cli/docker_api_stats_test.go]: i'm not sure sleep 0.1 works

Comment (cpuguy83) [inline integration-cli/docker_api_stats_test.go]: Tests ran through ok.

Comment (cpuguy83) [inline integration-cli/docker_api_stats_test.go]: Updated to use `usleep`

File: daemon/stats.go [hunk 3]
```diff
@@ -12,31 +13,39 @@ func (daemon *Daemon) ContainerStats(name string, stream bool, out io.Writer) er
...
 		ss.CpuStats.SystemUsage = update.SystemUsage
-		pre_cpu_stats = ss.CpuStats
-		if err := enc.Encode(ss); err != nil {
+		preCpuStats = ss.CpuStats
+		return ss
+	}
+
+	enc := json.NewEncoder(out)
+
+	if !stream {
```
Comment (icecrime) [inline daemon/stats.go]: I'm a bit confused by this block. Why does it call `getStat` twice, and why does it update the local `preCpuStats` variable which doesn't seem to be used anywhere before returning?

Comment (cpuguy83) [inline daemon/stats.go]: twice because it needs to compare CPU stat values to provide meaningful information.

preCpuStats is actually set in `getStat()` above.
I think I can actually remove lines 33 and 34 here since it's setting that above.  Not sure why that was being done.

Comment (cpuguy83) [inline daemon/stats.go]: fyi, otherwise cpustats is just 0.

Comment (icecrime) [inline daemon/stats.go]: My bad, I missed that `getStat` was a closure... Super confusing I thought it didn't receive `preCpuStats`! Thanks

Comment (cpuguy83) [inline daemon/stats.go]: updated removing those useless lines below and added comments

**Comment by runcom** [comment]
LGTM

**Comment by icecrime** [comment]
Cherry-picked
