### PR TITLE
Fix issue in `service update --publish-add`

### LINKED ISSUE #25375: service update --publish-add is not idempotent
From the usage description:

```
--publish-add value              Add or update a published port (default [])
```

However, updating a port does not work;

```bash
$ docker service create --name web nginx:alpine
6sjc95b0pxdeo7m3hy92pk2y6

$ docker service update --publish-add 80:80 web
web

$ docker service update --publish-add 80:80 web
Error response from daemon: rpc error: code = 3 desc = EndpointSpec: duplicate ports provided
```

The second call to `service update` should not fail if the definition is not conflicting (not sure what the behavior should be if it *is* conflicting)

/cc @dnephin

### PR DESCRIPTION
**Pull request by yongtang**
**\- What I did**

This fix tries to address the issue raised in #25375 where `service update --publish-add` returns an error if the exact same value is repeatedly updated.

**\- How I did it**

This fix use a map to filter out repeated port configs so that `--publish-add` does not error out.

**\- How to verify it**

An integration test has been added.

**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**

This fix fixes #25375.

Signed-off-by: Yong Tang yong.tang.github@outlook.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks @yongtang!

I've tested this, and this solves the direct issue (i.e. providing the exact same port mapping twice);

```bash
docker service create --publish 80:20 --name web nginx:alpine
cquoc5o30b8c9qlv9x1x1wu4n

docker service update --publish-add 80:20 web
web
```

However, (e.g. when realizing I have the wrong port published), trying to *update* the port;

```bash
docker service update --publish-add 80:80 web
Error response from daemon: rpc error: code = 3 desc = port '80' is already in use by service cquoc5o30b8c9qlv9x1x1wu4n
```

First of all, that error is confusing, because this *is* service `cquoc5o30b8c9qlv9x1x1wu4n`,
so we should improve that if possible.

Also, thinking about this more, I think we should consider that `--publish-add 80:80` should update port 80 with the new container port.

As an alternative, we could consider requiring to *unpublish* the port first, i.e., to use `--publish-rm` first, but this currently doesn't work (due to https://github.com/docker/docker/issues/25200)


ping @vieux @dnephin @aluzzardi PTAL; should overwriting the previous port-mapping work without errors?

**Comment by stevvooe** [comment]
@thaJeztah `--publish-add 80:*` should replace any existing port entries. Otherwise, to change the target port, you'd have to remove then add.

There may be an issue with the validation logic in swarmkit that prevents moving the target port.

File: api/client/service/update.go [hunk 1]
```diff
@@ -358,12 +358,23 @@ func updateMounts(flags *pflag.FlagSet, mounts *[]swarm.Mount) {
...
+		portSet[entry] = struct{}{}
+	}
+
 	if flags.Changed(flagPublishAdd) {
 		values := flags.Lookup(flagPublishAdd).Value.(*opts.ListOpts).GetAll()
 		ports, portBindings, _ := nat.ParsePortSpecs(values)
 
 		for port := range ports {
-			*portConfig = append(*portConfig, convertPortToPortConfig(port, portBindings)...)
+			newConfigs := convertPortToPortConfig(port, portBindings)
```
Comment (stevvooe) [inline api/client/service/update.go]: Make sure to sort this, as well, or random orderings could cause unnecessary updates.

**Comment by stevvooe** [comment]
This PR looks okay, but the full problem needs a fix in swarmkit. One should be able to change the target of a port and it looks like the validation is preventing that.

**Comment by mrjana** [comment]
IMO, I think the whole issue reported in #25375 should be fixed in swarmkit in `controlapi`. @yongtang would you be interested in fixing this in swarmkit rather than here and close this PR?

**Comment by yongtang** [comment]
Thanks @thaJeztah @stevvooe @mrjana for the review and feedback. Let me create a pull request in swarmkit.

File: api/client/service/update.go [hunk 2]
```diff
@@ -358,12 +358,23 @@ func updateMounts(flags *pflag.FlagSet, mounts *[]swarm.Mount) {
 }
 
 func updatePorts(flags *pflag.FlagSet, portConfig *[]swarm.PortConfig) {
+	portSet := make(map[swarm.PortConfig]struct{})
+	for _, entry := range *portConfig {
```
Comment (stevvooe) [inline api/client/service/update.go]: Wait: build an index by the left port (where `left:right`). That is what needs to be unique here.

File: integration-cli/docker_cli_swarm_test.go [hunk 3]
```diff
@@ -194,3 +194,19 @@ func (s *DockerSwarmSuite) TestSwarmNodeTaskListFilter(c *check.C) {
...
+
+	name := "top"
+	out, err := d.Cmd("service", "create", "--name", name, "--label", "x=y", "busybox", "top")
+	c.Assert(err, checker.IsNil)
+	c.Assert(strings.TrimSpace(out), checker.Not(checker.Equals), "")
+
+	out, err = d.Cmd("service", "update", "--publish-add", "80:80", name)
+	c.Assert(err, checker.IsNil)
+
+	out, err = d.Cmd("service", "update", "--publish-add", "80:80", name)
```
Comment (stevvooe) [inline integration-cli/docker_cli_swarm_test.go]: Add a failing case for `--publish-add 80:80 --publish-add 80:20`. That should error out on the client side.

Also add a case for service created with `--publish 80:80` then update to `--publish-add 80:20`.

The verb "add" implies set logic. We consider the exposed cluster ports a set of external ports. Adding a port with a new target port should update the value.

File: integration-cli/docker_cli_swarm_test.go [hunk 4]
```diff
@@ -194,3 +194,19 @@ func (s *DockerSwarmSuite) TestSwarmNodeTaskListFilter(c *check.C) {
 	c.Assert(out, checker.Not(checker.Contains), name+".2")
 	c.Assert(out, checker.Not(checker.Contains), name+".3")
 }
+
+// Test case for #25375
+func (s *DockerSwarmSuite) TestSwarmPublishAdd(c *check.C) {
```
Comment (dnephin) [inline integration-cli/docker_cli_swarm_test.go]: I think this can be tested with a unit test, we don't need the extra cost of an integration test to fully test this behaviour.

**Comment by aluzzardi** [comment]
> This PR looks okay, but the full problem needs a fix in swarmkit. One should be able to change the target of a port and it looks like the validation is preventing that.

Can someone log an issue on docker/swarmkit regarding this? It looks like we're missing validation and this PR is just going to hide an API validation bug.

**Comment by yongtang** [comment]
@aluzzardi @dnephin @stevvooe   @mrjana @thaJeztah I created an issue in swarmkit:
https://github.com/docker/swarmkit/issues/1348
to capture the potential issues about validation of `service update --publish-add` in swarmkit API.

Depending on whether we pass the delta portConfig or fully updated portConfig in `api.UpdateServiceRequest`, the validation could be done either in swarmkit side, or docker side.

Please take a look and let me know what is the best way to handle those scenarios and I will update the PR accordingly.

**Comment by yongtang** [comment]
@aluzzardi @dnephin @stevvooe @mrjana @thaJeztah  this PR has been updated.

Another PR in swarmkit (https://github.com/docker/swarmkit/pull/1349) has also been opened. 

Please take a look and let me know for any feedback/suggestions.

File: integration-cli/docker_cli_swarm_test.go (hunk 3 above)
Comment (yongtang) [inline integration-cli/docker_cli_swarm_test.go]: Thanks @stevvooe the test case has been added.

File: integration-cli/docker_cli_swarm_test.go (hunk 4 above)
Comment (yongtang) [inline integration-cli/docker_cli_swarm_test.go]: Thanks @dnephin I added a couple of more unit tests. I temporarily leave the integration test alone, as some of the test case will need to rely on swarmkit. Let me know if we feel unit test is ok to cover the above mentioned scenarios and I will update the PR accordingly.

**Comment by thaJeztah** [comment]
> Depending on whether we pass the delta portConfig or fully updated portConfig in api.UpdateServiceRequest, the validation could be done either in swarmkit side, or docker side.

@aluzzardi wdyt? I'm not sure what's best there; if the client sends the *desired* state, it could do so based on an outdated view of the service (and SwarmKit would be able to detect that?), so may be best? I'm usually in favor of having validation as close to the "source" as possible (so SwarmKit in this case)

**Comment by yongtang** [comment]
@thaJeztah @aluzzardi if the client send desired state, it is probably easy to assume the desired state has already been validated and sanitized by the client side (so swarmkit will not normalize/sanitize, but return error immediately)

If the client send only delta, then it is possible for client to just blindly send everything from the user input and let swarmkit to normalize and sanitize the request and get the desired state.

**Comment by aaronlehmann** [comment]
Pretty sure the client should send the full desired state in the update. This is how all the RPCs work and we've tried pretty hard to keep that model. If it's based on an outdated view of the service, the "version" check will fail, so that's not a concern.

**Comment by tiborvass** [comment]
@yongtang please revendor swarmkit :)

**Comment by yongtang** [comment]
Thanks @tiborvass. The pull request has been updated with swarmkit revendored.

File: api/client/service/update.go (hunk 1 above)
Comment (tiborvass) [inline api/client/service/update.go]: Ping @yongtang can you please address this issue?

File: api/client/service/update.go [hunk 5]
```diff
@@ -383,6 +406,7 @@ portLoop:
 		newPorts = append(newPorts, port)
 	}
 	*portConfig = newPorts
```
Comment (stevvooe) [inline api/client/service/update.go]: Make sure ordering here is stable. Looks like it is map bound, which is random.

File: api/client/service/update.go (hunk 1 above)
Comment (yongtang) [inline api/client/service/update.go]: Thanks @stevvooe @tiborvass. The pull request has been updated (sort is in Line 432).

File: api/client/service/update.go [hunk 6]
```diff
@@ -369,23 +372,54 @@ func updateMounts(flags *pflag.FlagSet, mounts *[]swarm.Mount) {
...
 
-func updatePorts(flags *pflag.FlagSet, portConfig *[]swarm.PortConfig) {
+type byPortConfig []swarm.PortConfig
+
+func (r byPortConfig) Len() int      { return len(r) }
+func (r byPortConfig) Swap(i, j int) { r[i], r[j] = r[j], r[i] }
+func (r byPortConfig) Less(i, j int) bool {
+	// We convert PortConfig into `port/protocol`, e.g., `80/tcp`
+	// In updatePorts we already filter out with map so there is duplicate entries
+	return strings.Compare(portConfigToString(&r[i]), portConfigToString(&r[j])) < 0
```
Comment (stevvooe) [inline api/client/service/update.go]:
```
portConfigToString(&r[i]) < portConfigToString(&r[j]))
```

**Comment by stevvooe** [comment]
Small nit in comparison but LGTM otherwise.

File: api/client/service/update.go (hunk 6 above)
Comment (yongtang) [inline api/client/service/update.go]: Thanks @stevvooe. Must have short circuited to forget the string comparison. The pull request has been updated.

**Comment by vdemeester** [comment]
LGTM :cat:

**Comment by aaronlehmann** [comment]
LGTM

**Comment by ziqingzhu** [comment]
why report " port '8880' is already in use " when i --publish-add 8881?
`[root@localhost ~]# docker service update semantic --publish-add 8881:28000
Error response from daemon: rpc error: code = 3 desc = port '8880' is already in use by service 25ll6oq0raap7rzh1xxn3v0pe`

**Comment by stevvooe** [comment]
@ziqingzhu Rather than comment on a closed PR, it is best to file an issue describing the conditions under which you've experience this behavior.
