### PR TITLE
Fix returned error code for network creation from 500 to 409

### LINKED ISSUE #34459: Create duplicated network expect 409 response but get 500
**Description**

When create a network with name already existed using docker-py, and set arg `check_duplicated=True`, the error should be `409 Conflict`, but `500 Internal Server Error` returns.

**Steps to reproduce the issue:**
In python console
```
>>> import docker
>>> c = docker.from_env()
>>> c.networks.create('net1')
<Network: 4c7d2d08e3>
>>> c.networks.create('net1', check_duplicate=True)
```

**Describe the results you received:**

```
>>> c.networks.create('net1', check_duplicate=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/docker/models/networks.py", line 144, in create
    resp = self.client.api.create_network(name, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/utils/decorators.py", line 35, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/api/network.py", line 134, in create_network
    return self._result(res, json=True)
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 220, in _result
    self._raise_for_status(response)
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 216, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python2.7/site-packages/docker/errors.py", line 30, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error for url: http+docker://localunixsocket/v1.24/networks/create ("network with name net1 already exists")
>>> 
```

**Describe the results you expected:**

```
>>> c.networks.create('net1', check_duplicate=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/docker/models/networks.py", line 144, in create
    resp = self.client.api.create_network(name, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/utils/decorators.py", line 35, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/api/network.py", line 134, in create_network
    return self._result(res, json=True)
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 220, in _result
    self._raise_for_status(response)
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 216, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python2.7/site-packages/docker/errors.py", line 30, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 409 Client Error: Conflict for url: http+docker://localunixsocket/v1.24/networks/create ("network with name net1 already exists")
>>> 
```

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:21:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.06.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 7ty93f9vgo9gb2nmwk4km10hb
 Is Manager: true
 ClusterID: fofqp1rgom60nftnc5fwkz1st
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 192.168.249.129
 Manager Addresses:
  192.168.249.129:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 472.5MiB
Name: swarm_manager
ID: YRD2:DTIW:AKEF:RXJY:RKXM:OJU2:N7B6:K7JK:XDOG:4E5S:NWFU:SGWY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 40
 Goroutines: 184
 System Time: 2017-08-08T14:20:57.288514678+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 10.27.37.40:5000
 10.37.210.125:5001
 127.0.0.0/8
Registry Mirrors:
 https://2h3po24q.mirror.aliyuncs.com/
Live Restore Enabled: false

WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
docker-py version 2.1.0
```

### PR DESCRIPTION
**Pull request by tossmilestone**
Signed-off-by: He Xiaoxi <tossmilestone@gmail.com>

**- What I did**

Fixes #34459 

**- How I did it**

Add a `conflictError` error type, and return the error when create a network with a conflict network name.

**- How to verify it**

In python console, run:
```
>>> import docker
>>> c = docker.from_env()
>>> c.networks.create('net1')
<Network: 4c7d2d08e3>
>>> c.networks.create('net1', check_duplicate=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/docker/models/networks.py", line 144, in create
    resp = self.client.api.create_network(name, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/utils/decorators.py", line 35, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/api/network.py", line 134, in create_network
    return self._result(res, json=True)
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 220, in _result
    self._raise_for_status(response)
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 216, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python2.7/site-packages/docker/errors.py", line 30, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 409 Client Error: Conflict for url: http+docker://localunixsocket/v1.24/networks/create ("network with name net1 already exists")
>>> 
```

**- Description for the changelog**

Return 409 instead of 500 if create a network with an existed name.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: api/server/router/network/network_routes.go [hunk 1]
```diff
@@ -100,6 +100,20 @@ func (e ambigousResultsError) Error() string {
 
 func (ambigousResultsError) InvalidParameter() {}
 
+type conflictingNetworkName struct {
```
Comment (yastij) [inline api/server/router/network/network_routes.go]: see [#34484(comment)](https://github.com/moby/moby/pull/34484#issuecomment-325014066)

**Review by thaJeztah — APPROVED** [review]
code LGTM, and looks to work as expected;

```bash
$ docker network create foo
91e999cc2de4a8be51b55afe23389d791af95561626e24f0315d2838c4ebb63a

$  curl --unix-socket /var/run/docker.sock -v -XPOST -H"Content-Type: application/json" -d'{"Attachable":false,"CheckDuplicate":true,"ConfigFrom":null,"ConfigOnly":false,"Driver":"bridge","EnableIPv6":false,"IPAM":{"Config":[],"Driver":"default","Options":{}},"Ingress":false,"Internal":false,"Labels":{},"Name":"foo","Options":{},"Scope":""}' http://localhost/networks/create
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying /var/run/docker.sock...
* Connected to localhost (/var/run/docker.sock) port 80 (#0)
> POST /networks/create HTTP/1.1
> Host: localhost
> User-Agent: curl/7.52.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 251
>
* upload completely sent off: 251 out of 251 bytes
< HTTP/1.1 409 Conflict
< Api-Version: 1.33
< Content-Type: application/json
< Docker-Experimental: false
< Ostype: linux
< Server: Docker/17.06.0-dev (linux)
< Date: Fri, 29 Sep 2017 15:19:39 GMT
< Content-Length: 51
<
{"message":"network with name foo already exists"}
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
```

**Comment by cpuguy83** [comment]
Maybe provide a helper function like:

```go
func nameConflict(name string) error {
    conflictError{libnetwork.NetworkNameError(name)}
}
```

File: api/server/router/network/network_routes.go (hunk 1 above)
Comment (tossmilestone) [reply api/server/router/network/network_routes.go]: Yes, I have use it, and this is the implementation of the `errdefs` interfaces.

**Comment by tossmilestone** [comment]
@cpuguy83 updated, PTAL.

**Comment by cpuguy83** [comment]
Can you add an API test checking the error code?

File: api/server/router/network/network_routes.go [hunk 2]
```diff
@@ -100,6 +100,24 @@ func (e ambigousResultsError) Error() string {
...
```
Comment (cpuguy83) [inline api/server/router/network/network_routes.go]: This would probably be best as just a generic conflict error

Comment (tossmilestone) [reply api/server/router/network/network_routes.go]: Yes, you're right! A generic conflict error will be good to extend.

**Comment by tossmilestone** [comment]
@cpuguy83 Added the api test for the error code, PTAL.

**Review by boaz0 — COMMENTED** [review]
Maybe it's a good time to move those tests to `integration/network/`? @dnephin @vdemeester WDYT?

**Comment by dnephin** [comment]
I would be, but it's not necessary either

**Comment by ehazlett** [comment]
LGTM

ping @cpuguy83

**Review by thaJeztah — APPROVED** [review]
still LGTM
