### PR TITLE
#12148: sort ports mapping before allocating

### LINKED ISSUE #12148: Failed to allocate port if the static port conflicted with the container's previous dynamic port
When user allocates a static port mapping that happens to be conflicted with the mapping that Docker's going to allocate to the same container, the port allocation will fail. This is another variation of #7158 

Steps to reproduce:
```
docker git:master ❯ sudo service docker restart
docker stop/waiting
docker start/running, process 19816
docker git:master ❯ cat /proc/sys/net/ipv4/ip_local_port_range
32768   61000
# now tries to map port 80 dynamically and port 8080 statically to the beginning of the port range
# the first request will fail
docker git:master ❯ docker run -P -p 80 -p 32768:8080 -d busybox top
6315c5cb8192e6d414065c73967605eccf48c1976c4c541a9e8afb6af0fd8aad
FATA[0000] Error response from daemon: Cannot start container 6315c5cb8192e6d414065c73967605eccf48c1976c4c541a9e8afb6af0fd8aad:
Bind for 0.0.0.0:32768 failed: port is already allocated
# second request will succeed
docker git:master ❯ docker run -P -p 80 -p 32768:8080 -d busybox top
b483e0742d2893f2fdff9492fe25ac028d9f9647cc2184dbc1a8c6804adb39c1
```

My docker version:
```
docker git:master ❯ docker version
Client version: 1.5.0-dev
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 9ede3f9
OS/Arch (client): linux/amd64
Server version: 1.5.0-dev
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 9ede3f9
OS/Arch (server): linux/amd64
```

cc @tiborvass

### PR DESCRIPTION
**Pull request by dqminh**
Fix #12148

Prioritize the ports with static mapping before dynamic mapping. This removes the port conflicts when we allocate static port in the reserved range together with dynamic ones.

When static port is allocated first, Docker will skip those when determining free ports for dynamic ones.

### CODE REVIEW

**Comment by dqminh** [comment]
cc @tiborvass

File: nat/sort.go [hunk 1]
```diff
@@ -26,3 +29,55 @@ func Sort(ports []Port, predicate func(i, j Port) bool) {
...
+	var (
+		i  int
+		pm = make(map[Port]struct{})
+	)
+	// reorder ports
+	for _, entry := range s {
+		if _, ok := pm[entry.port]; !ok {
+			ports[i] = entry.port
+			pm[entry.port] = struct{}{}
+			i++
```
Comment (crosbymichael) [inline nat/sort.go]: This `i` is declared outside, is it ok that this is to be iterated over in these inner loops?

**Comment by jfrazelle** [comment]
oh shoot we are going to need the tests updated since we switched to gocheck :(

File: integration-cli/docker_cli_run_test.go [hunk 2]
```diff
@@ -2603,6 +2603,44 @@ func TestRunPortProxy(t *testing.T) {
 	logDone("run - proxy should work with unavailable port")
 }
 
+// https://github.com/docker/docker/issues/12148
+func TestRunAllocatePortInReservedRange(t *testing.T) {
+	defer deleteAllContainers()
+	testRequires(t, SameHostDaemon)
```
Comment (LK4D4) [inline integration-cli/docker_cli_run_test.go]: Why it should be SameHostDaemon?

Comment (dqminh) [inline integration-cli/docker_cli_run_test.go]: iirc i copied-pasted the test above :D

File: nat/sort.go [hunk 3]
```diff
@@ -26,3 +29,55 @@ func Sort(ports []Port, predicate func(i, j Port) bool) {
...
+	pi, pj := toInt(string(s[i].port)), toInt(string(s[j].port))
+	hpi, hpj := toInt(s[i].binding.HostPort), toInt(s[j].binding.HostPort)
+	return (hpi > hpj) || (pi > pj)
+}
+
+// SortPortMap sorts the list of ports and their respected mapping. The ports
+// will explicit HostPort will be placed first.
+func SortPortMap(ports []Port, bindings PortMap) {
+	s := portMapSorter{}
+	for _, p := range ports {
```
Comment (LK4D4) [inline nat/sort.go]: I'm failing to understand algorithm :D Could you describe this loop for me?

File: nat/sort.go (hunk 1 above)
Comment (dqminh) [inline nat/sort.go]: i think it's safe. It's only changed when we encounter a new port. This is done so that we can override the original ordering of ports.

File: nat/sort.go (hunk 3 above)
Comment (dqminh) [inline nat/sort.go]: So the idea is to sort the list of ports and port bindings so that port which has explicit port bindings comes first. This put sport-binding combinations into a list, sort them and then rewrite the original list / bindings.

I hope that's clearer :D

File: nat/sort_test.go [hunk 4]
```diff
@@ -39,3 +40,31 @@ func TestSortSamePortWithDifferentProto(t *testing.T) {
...
 	}
 }
+
+func TestSortPortMap(t *testing.T) {
+	ports := []Port{
+		Port("22/tcp"),
+		Port("6379/tcp"),
+	}
+
+	portMap := PortMap{
```
Comment (LK4D4) [inline nat/sort_test.go]: Can we have more ports for testing?

Comment (dqminh) [inline nat/sort_test.go]: done! sorry for the slow response.

**Comment by LK4D4** [comment]
LGTM

File: nat/sort.go (hunk 3 above)
Comment (tiborvass) [inline nat/sort.go]: @dqminh feel free to add comments in the code :)

**Comment by jfrazelle** [comment]
LGTM
