### PR TITLE
Fix bindmount autocreate race

### LINKED ISSUE #37083: docker run --mount creates a directory owned by root if directory is removed at a wrong time
**Description**

If a "docker run" is started using "--mount" and the mounted directory is removed at a certain point during the invocation, it will create a directory owned by root.
This seems a race condition, since the timing or directory removal matters

**Steps to reproduce the issue:**

The following script has a good chance of reproducing the issue. Changing the timing of "sleep 0.5" changes the possibility of problems.

```
sudo rm -rf /tmp/try/nnn
mkdir -p /tmp/try/nnn
echo "before start:"  `ls -ld /tmp/try/nnn`
docker run -u 277174:89939 --mount type=bind,src=/tmp/try/nnn,dst=/test debian  sleep 3 &
sleep 0.5
rm -rf /tmp/try/nnn
echo "before sleep:"  `ls -ld /tmp/try/nnn`
sleep 3
echo "after sleep:"  `ls -ld /tmp/try/nnn`
```

**Describe the results you received:**

More often than not, this results in the following messages:

```
before start: drwxr-x--- 2 agoulti primarygroup 4096 May 16 14:48 /tmp/try/nnn
after start: drwxr-x--- 2 agoulti primarygroup 4096 May 16 14:48 /tmp/try/nnn
ls: cannot access '/tmp/try/nnn': No such file or directory
before sleep:
after sleep: drwxr-xr-x 2 root root 4096 May 16 14:48 /tmp/try/nnn

```

**Describe the results you expected:**

--mount is said not to create a directory if it doesn't exist.
I am creating bad running conditions, so I expect docker to fail.
However, I expect `/tmp/try/nnn` to never be created.

**Additional information you deem important (e.g. issue happens only occasionally):**

This is a race condition, so the results are not guaranteed.
On my machine I get a problem around half the time. 
Changing "sleep 0.5" duration changes the behaviour, you might need to tune it to reproduce on another machine.

Too short and it correctly executes with:
`docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist.`

Too long and it correctly executes with:
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/tmp/try/nnn\\\" to rootfs \\\"/usr/[...]merged\\\" at \\\"/test\\\" caused \\\"stat /tmp/try/nnn: no such file or directory\\\"\"": unknown.`

**Output of `docker version`:**

```
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:10:06 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:08:35 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 813
 Running: 0
 Paused: 0
 Stopped: 813
Images: 26
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.9.0-6-amd64
Operating System: Debian GNU/Linux buster/sid
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 31.35GiB
Name: agoulti.wat.corp.google.com
ID: MMPA:UN32:XDPC:C6LU:IQ4F:WXSG:S2TS:23E4:GW73:4WSB:PKW5:RMWW
Docker Root Dir: /usr/local/google/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Desktop Linux machine

### PR DESCRIPTION
**Pull request by cpuguy83**
When using the mounts API, bind mounts are not supposed to be
automatically created.

Before this patch there is a race condition between validating that a
bind path exists and then actually setting up the bind mount where the
bind path may exist during validation but was removed during mountpooint
setup.

This adds a field to the mountpoint struct to ensure that binds created
over the mounts API are not accidentally created.

Closes #37083

### CODE REVIEW

File: volume/mounts/mounts.go [hunk 1]
```diff
@@ -62,6 +62,12 @@ type MountPoint struct {
 	// Sepc is a copy of the API request that created this mount.
 	Spec mounttypes.Mount
 
+	// Some bind mounts should not be automatically created.
+	// (Some are auto-created for backwards-compatability)
+	// This is checked on the API but setting this here prevents race conditions.
+	// where a bind dir existed during validation was removed before reaching the setup code.
+	DisableBindmountAutoCreate bool
```
Comment (kolyshkin) [inline volume/mounts/mounts.go]: Maybe something simpler, like `SkipMountPointCreation` or `DoNotCreateMountPoint`?

File: volume/mounts/mounts.go [hunk 2]
```diff
@@ -140,12 +146,15 @@ func (m *MountPoint) Setup(mountLabel string, rootIDs idtools.IDPair, checkFun f
...
 			}
 		}
-		// idtools.MkdirAllNewAs() produces an error if m.Source exists and is a file (not a directory)
-		// also, makes sure that if the directory is created, the correct remapped rootUID/rootGID will own it
-		if err := idtools.MkdirAllAndChownNew(m.Source, 0755, rootIDs); err != nil {
-			if perr, ok := err.(*os.PathError); ok {
-				if perr.Err != syscall.ENOTDIR {
-					return "", errors.Wrapf(err, "error while creating mount source path '%s'", m.Source)
+
+		if !m.DisableBindmountAutoCreate {
```
Comment (kolyshkin) [inline volume/mounts/mounts.go]: Maybe
```go
if m.DisableBindmountAutoCreate {
		return m.Source, nil
}

File: volume/mounts/mounts.go (hunk 1 above)
Comment (kolyshkin) [reply volume/mounts/mounts.go]: I mean, the name doesn't have to contain BindMount, also it's not clear from yours what is being auto created (a mount point).

Comment (cpuguy83) [reply volume/mounts/mounts.go]: I like it, also makes it more straightforward to just skip setup earlier.

Comment (cpuguy83) [reply volume/mounts/mounts.go]: Updated.

**Review by kolyshkin — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Review by thaJeztah — APPROVED** [review]
LGTM
