### PR TITLE
Fix pull on client disconnect

### LINKED ISSUE #15589: [1.8.1]: ^C on pull broken
^C on a pull is unrecoverable, and does not even show the message "layer being pulled by another client"

### PR DESCRIPTION
**Pull request by tonistiigi**
Fixes #15589

Not quite sure if `discard` is a best solution here but seemed more robust than letting all the progress logging know that they are not needed any more. The issue is that progress logger's writes block because there are no readers in the other side of the pipe any more.

Regarding the other pull issues we have for `1.8.1` they may be related, but not sure because they are much harder to reproduce. 

Signed-off-by: Tonis Tiigi tonistiigi@gmail.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Added this to the milestone, because the linked issue is on the milestone ;-)

File: graph/pull_v2.go [hunk 1]
```diff
@@ -223,6 +223,9 @@ func (p *v2Puller) pullV2Tag(tag, taggedName string) (verified bool, err error)
 	go func() {
 		if _, err := io.Copy(out, pipeReader); err != nil {
 			logrus.Errorf("error copying from layer download progress reader: %s", err)
+			if _, err := io.Copy(ioutil.Discard, pipeReader); err != nil {
```
Comment (stevvooe) [inline graph/pull_v2.go]: This pipe cancellation technique was supposed to be done on the download stream, not the progress channel.

Either way, `pipeReader` isn't connected to anything.

Comment (tonistiigi) [inline graph/pull_v2.go]: Can you explain a bit more. Afaik this `pipeWriter` is directly thrown to the `download` and from there to `progressreader`. I guess we could also just close `pipeReader` here(cleaner but errors for writers) but not not sure how we do it from `download`. Just so that everything is clear, we are not actually canceling the pull, we just want the progress writers not to block.

Comment (stevvooe) [inline graph/pull_v2.go]: This was implemented with https://github.com/docker/docker/pull/15353. The original idea was to cancel the download by controlling the download pipe, not the progress reporting pipe. Looks like I missed this detail in review. This lets you cancel the `io.Copy` in https://github.com/docker/docker/pull/15353/files#diff-7e2a216082b6bd557c7ecebd68305e2eL174 and stop the download (ack! that error should be checked, as well).

Studying this again, the use of `pipeReader` is correct. Rather than sending to discard, it should be sufficient to call `CloseWithError` on the `pipeReader`.

Comment (tonistiigi) [inline graph/pull_v2.go]: Ok, for `v1.8.2` we don't want to change the download logic, only make it compatible with `v1.7.1` and fix the blocking. I'll change the `pipeReader` to close.

File: graph/pull_v2.go [hunk 2]
```diff
@@ -223,6 +223,9 @@ func (p *v2Puller) pullV2Tag(tag, taggedName string) (verified bool, err error)
 	go func() {
 		if _, err := io.Copy(out, pipeReader); err != nil {
 			logrus.Errorf("error copying from layer download progress reader: %s", err)
+			if err := pipeReader.CloseWithError(err); err != nil {
```
Comment (stevvooe) [inline graph/pull_v2.go]: Just close in the same place the writer is closed in the deferred function.

**Comment by stevvooe** [comment]
@tonistiigi We may also want to confirm that `pipeReader`/`pipeWriter` are always closed. That defer function check is suspect.

File: graph/pull_v2.go (hunk 2 above)
Comment (tonistiigi) [inline graph/pull_v2.go]: No, that defer is only reached after pull has completed(or real download error). The goal is to carry on with the pull although client has disconnected.

File: integration-cli/docker_cli_pull_test.go [hunk 3]
```diff
@@ -369,3 +369,40 @@ func (s *DockerTrustSuite) TestTrustedPullWithExpiredSnapshot(c *check.C) {
 		}
 	})
 }
+
+// #15589
+func (s *DockerTrustSuite) TestPullCancellation(c *check.C) {
```
Comment (pwaller) [inline integration-cli/docker_cli_pull_test.go]: As someone who is interested in pull cancellation (e.g, ctrl-c stops the download), I am concerned that `TestPullCancellation` is a confusing name, since I assume that this pull request is not related to stopping the download (as build cancellation does analogously stop the build). If that's the case, can it be renamed?

Suggestions:
```
TestPullClientDisconnect
TestPullClientGiveup
TestPullClientGoaway
```

In addition, a comment above the function name explaining what is being tested would be a good idea. I'm just picturing a future developer making assumptions about what is being tested by this function and tying themselves in a knot.

I followed the issue number and that isn't quite enough to know what is being tested here.

Comment (tonistiigi) [inline integration-cli/docker_cli_pull_test.go]: Updated.

Comment (pwaller) [inline integration-cli/docker_cli_pull_test.go]: :+1:

**Comment by LK4D4** [comment]
LGTM

**Comment by calavera** [comment]
LGTM

**Comment by calavera** [comment]
Cherry picked into #15809

File: integration-cli/docker_cli_pull_test.go [hunk 4]
```diff
@@ -369,3 +369,40 @@ func (s *DockerTrustSuite) TestTrustedPullWithExpiredSnapshot(c *check.C) {
 		}
 	})
 }
+
+// Test that pull continues after client has disconnected. #15589
+func (s *DockerTrustSuite) TestPullClientDisconnect(c *check.C) {
```
Comment (aaronlehmann) [inline integration-cli/docker_cli_pull_test.go]: Sorry to only notice this after the merge, but this should be probably be in DockerRegistrySuite.

Comment (aaronlehmann) [inline integration-cli/docker_cli_pull_test.go]: Actually, DockerSuite, since it doesn't involve a private registry either. Opened a PR here: https://github.com/docker/docker/pull/15894
