### PR TITLE
Fix `Size` in `docker images` for v1.12 client to v1.13 daemon

### LINKED ISSUE #30027: [1.13.0-rc5] Docker Image Size reported as -1 in 1.11/1.12 client
When the server is running Docker 1.13.0-rc5, when the client runs `docker images` the sizes will be reported as -1

```
$ docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0-rc5
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   43cc971
 Built:        Thu Jan  5 03:07:30 2017
 OS/Arch:      linux/amd64
```

```
$ docker images
REPOSITORY                        TAG                 IMAGE ID            CREATED             SIZE
katacoda/docker-http-server       large               1e023cfd8ba8        18 hours ago        -1 B
katacoda/docker-http-server       latest              c6dfc1d5003f        18 hours ago        -1 B
katacoda/docker-http-server       v1                  c6dfc1d5003f        18 hours ago        -1 B
```

Upgrading the client to Docker 1.13 fixes the issue.

```
$ docker version
Client:
 Version:      1.13.0-rc5
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   43cc971
 Built:        Thu Jan  5 03:07:30 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0-rc5
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   43cc971
 Built:        Thu Jan  5 03:07:30 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
$ docker images
REPOSITORY                        TAG                 IMAGE ID            CREATED             SIZE
katacoda/docker-http-server       large               1e023cfd8ba8        18 hours ago        771 MB
katacoda/docker-http-server       latest              c6dfc1d5003f        18 hours ago        7.59 MB
katacoda/docker-http-server       v1                  c6dfc1d5003f        18 hours ago        7.59 MB
```

### PR DESCRIPTION
**Pull request by yongtang**
**- What I did**

This fix tries to address the issue raised in #30027 where `Size` in `docker images` always show `-1` for v1.12 client against v1.13 daemon.

The reason for the issue is that in v1.12, `Size` is used while in v1.13 `VirtualSize` is used. And in v1.13, `Size` has been always initialized as `-1`.

**- How I did it**

This fix address the issue by copy the value of `VirtualSize` to `Size` if version is less or equal to v1.24 (docker v1.12).

**- How to verify it**

An integration test has been added.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

u 1024162214 1388002003 fm 21 gp 0

This fix fixes #30027.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

File: integration-cli/docker_api_images_test.go [hunk 1]
```diff
@@ -128,3 +128,38 @@ func (s *DockerSuite) TestAPIImagesSearchJSONContentType(c *check.C) {
 	c.Assert(res.StatusCode, checker.Equals, http.StatusOK)
 	c.Assert(res.Header.Get("Content-Type"), checker.Equals, "application/json")
 }
+
+// Test case for 30027
```
Comment (AkihiroSuda) [inline integration-cli/docker_api_images_test.go]: nit: please add a brief description about #30027? (e.g. "Image size reported as -1 in v1.12 client against v1.13 daemon")

**Comment by thaJeztah** [comment]
ping @mlaventure

File: integration-cli/docker_api_images_test.go (hunk 1 above)
Comment (yongtang) [inline integration-cli/docker_api_images_test.go]: Thanks @AkihiroSuda. The PR has been updated.

**Comment by mlaventure** [comment]
@yongtang we decided to fix the meaning of the field instead, but I feel like the PR should bear your name.

Do you mean using this commit: https://github.com/mlaventure/docker/commit/d143fb8bee428074c91ec901e204e23b318c3cc3 

And add your test to it?

Thanks!

**Comment by yongtang** [comment]
@mlaventure Thanks for the help! The commit has been carried and test has been added. Please take a look and let me know if there are any issues.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by mlaventure — APPROVED** [review]
LGTM

Thanks @yongtang !

**Comment by ZYNCMA** [comment]
> - How I did it
>
>This fix address the issue by copy the value of VirtualSize to Size if version is less or equal to v1.24 (docker v1.12).

@yongtang Did you really judge the api version before assigning virtualsize to size?
 I cannot find it in your commits. Did I miss anything?

**Comment by thaJeztah** [comment]
@ZYNCMA `Size` and `VirtualSize` were used before Docker 1.10 (which introduced content addressable store). Before 1.10, `Size` was the size of just the last layer of the image, and `VirtualSize` the calculated size of the image + all its parents. After Docker 1.10, images are self-contained, so `Size` and `VirtualSize` will always be the same.

This PR reverts a change that re-used `Size`, and set it to_just_ the size of layers that are not shared with other images. We decided it was bad to change the definition of that field, so reverted the change; therefore this change does not have to take the API version into account.

You can see the original change here; https://github.com/docker/docker/pull/26108/commits/b717de5153db503fae61c11e30f04f400f66a6fd#diff-4adce79060ec85cddf1545ebadcc0d5eR244

(I see we didn't change back the _name_ of the parameter; let me open a separate PR for that, but it's not critical, just a "nit")

**Comment by thaJeztah** [comment]
Opened https://github.com/docker/docker/pull/30120 to change back the name

**Comment by ZYNCMA** [comment]
@thaJeztah I'm fine with the PR. I was just confused about the inconsistency of the description I quoted before and the commit.
As it's unnecessary to take the API version into account, it should be the fault of the description.
Thanks for your explanation!

**Comment by ZYNCMA** [comment]
@yongtang Got it.
