### PR TITLE
"Fix" checkpoint on v2 runtime

### LINKED ISSUE #41531: Checkpoint fails with shimv2
Calling `docker checkpoint` with the (now default) v2 shim yields an error from the shim:

```
invalid task checkpoint option for io.containerd.runc.v2: unknown
```

### PR DESCRIPTION
**Pull request by cpuguy83**
Checkpoint/Restore is horribly broken all around.
But on the, now default, v2 runtime it's even more broken.

This at least makes checkpoint equally broken on both runtimes.

Closes #41531

### CODE REVIEW

File: libcontainerd/remote/client.go [hunk 1]
```diff
@@ -511,26 +511,44 @@ func (c *client) Status(ctx context.Context, containerID string) (containerd.Pro
...
+		if !exit {
+			// shortcut no-op for now since exit is the only thing we set
+			return nil
+		}
+
+		c.v2runcoptionsMu.Lock()
+		_, isV2 := c.v2runcoptions[id]
+		c.v2runcoptionsMu.Unlock()
+
+		if isV2 {
```
Comment (kolyshkin) [inline libcontainerd/remote/client.go:525]: Can we maybe do something like this instead?
```go
if r.Options == nil {
    if isV2 {
        r.Options = &v2runcoptions.CheckpointOptions{}
    } else {
        r.Options = &runctypes.CheckpointOptions{}
    }
}
r.Options.Exit = exit
```

This seems slightly more readable as well as potentially extensible.

Maybe remove the `if !exit` shortcut, too, unless it saves us a lot of resources (which I doubt).

**Review by kolyshkin — CHANGES_REQUESTED** [review]
This juggling looks a tad crazy to me, but I guess there's not much we can do. Left a suggestion to slightly simplify the code, not sure it will work though

File: libcontainerd/remote/client.go (hunk 1 above)
Comment (cpuguy83) [reply libcontainerd/remote/client.go:525]: Your code doesn't work because of the different types.
`Options` is an `interface{}` that we need to assert against... but certainly we can do something like

```go
if r.Options == nil {
    if isV2 {
        r.Options = &v2runcoptions.CheckpointOptions{}
    } else {
        r.Options = &runctypes.CheckpointOptions{}
    }
}

switch o := r.Options.(typ) {
// assertions
}
```

Comment (cpuguy83) [reply libcontainerd/remote/client.go:525]: I wanted to avoid assertions where it's not needed as the old code did... but in the grand scheme of things it's not saving us anything noticeable.

Comment (kolyshkin) [reply libcontainerd/remote/client.go:525]: > Your code doesn't work because of the different types.

right :man_facepalming:

**Review by kolyshkin — APPROVED** [review]
LGTM

**Comment by cpuguy83** [comment]
I think the key to all the jugglign to move v2/v1 handling out. I'd honestly like to, in the future, be able to handle more than just the built-in shims... probably would help here.

**Review by AkihiroSuda — APPROVED** [review]

**Comment by AkihiroSuda** [comment]
Didn't we have an integration test?

**Comment by cpuguy83** [comment]
@AkihiroSuda There are disabled apparently due to to 💩 🔥 (also flakiness).

**Comment by rst0git** [comment]
@cpuguy83 with the change in this PR, `docker checkpoint create` fails as follows:
```
$ make BIND_DIR=. shell
...
$ docker run -d --name looper busybox /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'
$ docker checkpoint create looper checkpoint1
time="2020-10-13T00:23:34.572955617Z" level=error msg="resuming exited container from paused state" error="runc did not terminate successfully: container \"c9331dc7c566530183a8a9fb4940058cd989354fd340ccafd90662af05fe544c\" does not exist\n"
INFO[2020-10-13T00:23:34.586458467Z] ignoring event                                module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
INFO[2020-10-13T00:23:34.586652537Z] shim disconnected                             id=c9331dc7c566530183a8a9fb4940058cd989354fd340ccafd90662af05fe544c
ERRO[2020-10-13T00:23:34.690462147Z] Handler for POST /v1.30/containers/looper/checkpoints returned error: Cannot checkpoint container looper: image "docker.io/library/busybox": not found 
Error response from daemon: Cannot checkpoint container looper: image "docker.io/library/busybox": not found

```

**Comment by cpuguy83** [comment]
@rst0git That's farther than I get at least. Mine complains about `iptables-restore`, and I can't seem to work around it.
Though I'm pretty sure someone worked on that image issue since we don't need to checkpoint the image.

**Review by thaJeztah — APPROVED** [review]
LGTM
