### PR TITLE
Handle https proxy's CONNECT response

### LINKED ISSUE #34131: ./contrib/download-frozen-image-v2.sh failed to parse http redirect
**Description**

```
# make BIND_DIR=. shell
...
parse error: Invalid numeric literal at line 1, column 3
The command '/bin/sh -c ./contrib/download-frozen-image-v2.sh /docker-frozen-images     buildpack-deps:jessie@sha256:85b379ec16065e4fe4127eb1c5fb1bcc03c559bd36dbb2e22ff496de55925fa6   busybox:latest@sha256:32f093055929dbc23dec4d03e09dfe971f5973a9ca5cf059cbfb644c206aa83f      debian:jessie@sha256:72f784399fd2719b4cb4e16ef8e369a39dc67f53d978cd3e2e7bf4e502c7b793   hello-world:latest@sha256:c5515758d4c5e1e838e9cd307f6c6a0d620b5e07e6f927b07d05f6d12a1ac8d7' returned a non-zero code: 4
make: *** [build] Error 4
```

**Steps to reproduce the issue:**
1. Setup a https proxy to build docker dev env
2. make BIND_DIR=. shell

**Describe the results you received:**
```
parse error: Invalid numeric literal at line 1, column 3
The command '/bin/sh -c ./contrib/download-frozen-image-v2.sh /docker-frozen-images     buildpack-deps:jessie@sha256:85b379ec16065e4fe4127eb1c5fb1bcc03c559bd36dbb2e22ff496de55925fa6   busybox:latest@sha256:32f093055929dbc23dec4d03e09dfe971f5973a9ca5cf059cbfb644c206aa83f      debian:jessie@sha256:72f784399fd2719b4cb4e16ef8e369a39dc67f53d978cd3e2e7bf4e502c7b793   hello-world:latest@sha256:c5515758d4c5e1e838e9cd307f6c6a0d620b5e07e6f927b07d05f6d12a1ac8d7' returned a non-zero code: 4
make: *** [build] Error 4

```

**Describe the results you expected:**
The script returns a zero code.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by wenjianhn**
When using a https proxy, an extra HTTP 200 header will be generated.
So we can't rely on detecting the first http header.

$curlHeaders with https proxy:
"HTTP/1.0 200 Connection established  <-- the https proxy's response

HTTP/1.1 307 Temporary Redirect
...
"

See https://stackoverflow.com/a/34537988/889429

Fixes #34131

Signed-off-by: Jacob Wen <jian.w.wen@oracle.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thank you!

ping @tianon @albers PTAL

**Comment by albers** [comment]
I successfully verified the problem and this fix.
Thanks a lot for digging into this. Really strange, a https response with multiple headers!

LGTM

File: contrib/download-frozen-image-v2.sh [hunk 1]
```diff
@@ -63,10 +63,10 @@ fetch_blob() {
 			-o "$targetFile" \
 			-D-
 	)"
-	curlHeaders="$(echo "$curlHeaders" | tr -d '\r')"
```
Comment (tianon) [inline contrib/download-frozen-image-v2.sh]: Is moving this line important?  The new `grep` should match better with proper `\n` than with additional `\r`, shouldn't it?

File: contrib/download-frozen-image-v2.sh [hunk 2]
```diff
@@ -63,10 +63,10 @@ fetch_blob() {
...
-	if [ "$(echo "$curlHeaders" | awk 'NR == 1 { print $2; exit }')" != '200' ]; then
+	if echo "$curlHeaders" | egrep -q "^HTTP/[0-9].[0-9] 307"; then
```
Comment (tianon) [inline contrib/download-frozen-image-v2.sh]: `egrep` is deprecated in favor of `grep -E`: (from `grep(1)`)
```
       In addition, the variant programs egrep  and  fgrep  are  the  same  as
       grep -E  and grep -F, respectively.  These variants are deprecated, but
       are provided for backward compatibility.
```

Comment (tianon) [inline contrib/download-frozen-image-v2.sh]: Also, would it make sense to allow for any redirection code here (instead of just `307`)?  ala https://en.wikipedia.org/wiki/URL_redirection#HTTP_status_codes_3xx

File: contrib/download-frozen-image-v2.sh (hunk 1 above)
Comment (wenjianhn) [inline contrib/download-frozen-image-v2.sh]: No. I will bring it back.

File: contrib/download-frozen-image-v2.sh (hunk 2 above)
Comment (wenjianhn) [inline contrib/download-frozen-image-v2.sh]:
```
:~$ cat `which egrep`
#!/bin/sh
exec grep -E "$@"
```

We can still use these variants, since they provided for backward compatibility.

Comment (wenjianhn) [inline contrib/download-frozen-image-v2.sh]: Yes. It make sense.

Comment (wenjianhn) [inline contrib/download-frozen-image-v2.sh]: @tianon ping

File: contrib/download-frozen-image-v2.sh [hunk 3]
```diff
@@ -63,8 +63,8 @@ fetch_blob() {
 			-o "$targetFile" \
 			-D-
 	)"
-	curlHeaders="$(echo "$curlHeaders" | tr -d '\r')"
-	if [ "$(echo "$curlHeaders" | awk 'NR == 1 { print $2; exit }')" != '200' ]; then
+        curlHeaders="$(echo "$curlHeaders" | tr -d '\r')"
```
Comment (thaJeztah) [inline contrib/download-frozen-image-v2.sh]: Looks like this line now uses spaces, not tabs, for indentation; can you fix that? (our shell scripts use tabs for indentation)

**Review by thaJeztah — CHANGES_REQUESTED** [review]

File: contrib/download-frozen-image-v2.sh (hunk 3 above)
Comment (wenjianhn) [inline contrib/download-frozen-image-v2.sh]: Done.

**Review by tianon — APPROVED** [review]
LGTM :+1:

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
thanks!
