### PR TITLE
Fix for #13720. Unpublished ports missing in docker ps

### LINKED ISSUE #13720: 1.7: Unpublished ports are missing in `docker ps`
In Docker 1.6

```
docker run -d ibuildthecloud/helloworld
docker ps

CONTAINER ID        IMAGE                              COMMAND             CREATED             STATUS              PORTS               NAMES
aab6cda50fb3        ibuildthecloud/helloworld:latest   "/sleep.sh"         3 seconds ago       Up 3 seconds        8080/tcp            agitated_lovelace   
```

In Docker 1.7-rc1

```
CONTAINER ID        IMAGE                       COMMAND             CREATED             STATUS              PORTS               NAMES
1f4cf7da1aae        ibuildthecloud/helloworld   "/sleep.sh"         6 seconds ago       Up 5 seconds                            pensive_cray  
```

Looking at the API response `/containers/json` is return an empty list for `Ports`

### PR DESCRIPTION
**Pull request by aboch**
Fixes #13720.

Signed-off-by: Alessandro Boch aboch@docker.com

### CODE REVIEW

File: daemon/container_linux.go [hunk 1]
```diff
@@ -513,13 +513,21 @@ func (container *Container) buildPortMapInfo(n libnetwork.Network, ep libnetwork
 		networkSettings.MacAddress = mac.(net.HardwareAddr).String()
 	}
 
+	networkSettings.Ports = nat.PortMap{}
+
+	if expData, ok := driverInfo[netlabel.ExposedPorts]; ok {
+		for _, tp := range expData.([]types.TransportPort) {
```
Comment (icecrime) [inline daemon/container_linux.go]: We must verify the type assertion: if this doesn't hold for some reason, the daemon will panic.

Comment (aboch) [inline daemon/container_linux.go]: It cannot happen, the code that packs driverInfo is vendored go code.
But ok, I can add the type assertion.

Comment (icecrime) [inline daemon/container_linux.go]: As far as I can tell it's something that the driver builds: I don't think we can trust a driver to always give us something of the expected type. But maybe I'm being paranoid.

Comment (aboch) [inline daemon/container_linux.go]: Yeah, exposed ports could be provided by other drivers other than the default bridge.
Better to assert. Just tested the change, will push them now.
Thanks.

**Comment by thaJeztah** [comment]
@aboch really minor detail; could your change the title of this PR to be a bit more descriptive (In case we need to find it back in a later stage) :-)

**Comment by aboch** [comment]
@thaJeztah Done. Feel free to change it, add the proper keywords. I am new to docker/docker.

**Comment by thaJeztah** [comment]
@aboch Excellent! 

> I am new to docker/docker

No problem, we need to pay more attention to those in general, given the large amount of PR's in this repo.

**Comment by duglin** [comment]
@aboch can you please add some testcases so we can detect if this breaks in the future?

File: hack/vendor.sh [hunk 2]
```diff
@@ -55,7 +55,7 @@ clone hg code.google.com/p/go.net 84a4013f96e0
 clone hg code.google.com/p/gosqlite 74691fb6f837
 
 #get libnetwork packages
-clone git github.com/docker/libnetwork 005bc475ee49a36ef2ad9c112d1b5ccdaba277d4
+clone git github.com/docker/libnetwork f72ad20491e8c46d9664da3f32a0eddb301e7c8d
```
Comment (duglin) [inline hack/vendor.sh]: I'm not 100% clear on how this part of our process works, but wouldn't the 'vendor' dir's copy of libnetwork need to be changed too?

Comment (runcom) [inline hack/vendor.sh]: also can the libnetwork version bump and the code fix be in separate commits? does it make sense?

**Comment by duglin** [comment]
@aboch minor thing, but since you mentioned you're new to docker, you may want to use branches instead of "master" for PRs. Then you could be working on more than one change at a time and keep each in an appropriately named branch.  https://github.com/docker/docker/blob/master/CONTRIBUTING.md#conventions

File: vendor/src/github.com/docker/libnetwork/drivers/bridge/bridge.go [hunk 3]
```diff
@@ -686,6 +686,15 @@ func (d *driver) EndpointOperInfo(nid, eid types.UUID) (map[string]interface{},
 
 	m := make(map[string]interface{})
 
+	if ep.config.ExposedPorts != nil {
```
Comment (duglin) [inline vendor/src/github.com/docker/libnetwork/drivers/bridge/bridge.go]: I think the way this works is that you'll need to open a PR in the libnetwork project for this change. Then once that's merged you'll need to open a PR for docker to grab the newer version of libnetwork.  We don't do "vendor" changes are part of Docker PRs - the "vendor" dir is just a copy of the remote repo at the level we want.

**Comment by duglin** [comment]
On the positive side, I tested it and it does seem to fix the issue!

File: hack/vendor.sh (hunk 2 above)
Comment (mavenugo) [inline hack/vendor.sh]: @duglin in order to bump a version of a dependency, we change it in `hack/vendor.sh` and run the script locally which will pull in all the required changes into the `vendor` dir.

@runcom not necessarily always. especially if a change in dependent package causes any API or semantic changes, then the corresponding change in docker/docker must be done in the same commit.

File: vendor/src/github.com/docker/libnetwork/drivers/bridge/bridge.go (hunk 3 above)
Comment (mavenugo) [inline vendor/src/github.com/docker/libnetwork/drivers/bridge/bridge.go]: @duglin Yes. PR in libnetwork was : https://github.com/docker/libnetwork/pull/254.
Vendor version bumps are also normal Docker PRs. But, if a version bump in libnetwork needs corresponding change in `docker/docker` or not is entirely upto the syntax/semantic changes introduced by that version bump. 
In those circumstances, we have to deal with the corresponding `docker/docker` changes during the vendor-in PR itself. I dont think that is applicable here though.

**Comment by icecrime** [comment]
I think we're fine regarding the changeset, commit layout, and vendoring process. Give me a minute to test it now ;-)

**Comment by icecrime** [comment]
LGTM

File: hack/vendor.sh (hunk 2 above)
Comment (aboch) [inline hack/vendor.sh]: @duglin Yeah, I should have added a test case. Just that this change needs to go in 1.7 rc2, I felt some signs of urgency. If docker committer feel we can wait, I can add it.

**Comment by aboch** [comment]
@duglin regarding the push to master, I was suggested to do so. Not sure why, maybe because this change is updating the vendoring or because needs to be cherry picked for the rc2 release branch ?

**Comment by calavera** [comment]
LGTM I got port information in the ps output:

```
root@vagrant:/vagrant# ./docker-1.7 ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                    NAMES
80b8dcde2065        ubuntu              "bash"              4 seconds ago       Up 3 seconds        0.0.0.0:8080->8080/tcp   cocky_davinci
```

**Comment by thaJeztah** [comment]
@calavera that's not the issue there; this one was about containers only *exposing* ports, not published

File: hack/vendor.sh (hunk 2 above)
Comment (aboch) [inline hack/vendor.sh]: @runcom I If this commit would address only the docker side part, issue would not be fixed.
I think it would not be correct to have a commit in the tree which is only a partial fix.
I could see a case where a maintainer has to cherry-pick fixes from a master branch to a release branch: It would not be fair he had to do the extra work of correlating an issue to multiple commits. It would also be an error prone process.

**Comment by duglin** [comment]
re: testing - some tests I'd like to see added (testing the output of "ps" for each):
- container w/o EXPOSE, w/o -p 
- container w/o EXPOSE, w/ -p
- container w/ EXPOSE, w/o -p 
- container w/ EXPOSE, w/ -p 
- and then do it with multiple ports EXPOSEd to make sure just the one mentioned in -p is mapped.

**Comment by thaJeztah** [comment]
@duglin from a test-perspective, is there a difference between `EXPOSE` (Dockerfile) and `--expose` (single port or range)? If there is, that may need to be tested separately

**Comment by aboch** [comment]
@duglin it makes a lot of sense to test those combinations.
A couple were covered during manual tests.

Would it work if I push a separate lower priority change, to cover the tests you suggested ?

**Comment by duglin** [comment]
@thaJeztah semantically they should be the same but given its different code paths they probably need both to be tested.  Not sure how much of this is already covered by current tests.

@aboch whether its part of this PR or not, to me, is just a factor of time. If you can get at least some of the key tests done today as part of this then I'd prefer at least some to be included in this PR than none.

**Comment by calavera** [comment]
It stills LGTM. Let's move forward with this and add more tests in another PR:

```
root@vagrant:/vagrant# ./docker-1.7 run --expose 8080 -d -it ubuntu bash
c36a1f7fb39b8d7e232c95929da61a4b3d83988ed723ecb76bb9c94a53e3c460
root@vagrant:/vagrant# ./docker-1.7 ps
CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS              PORTS                     NAMES
c36a1f7fb39b        ubuntu              "bash"              3 seconds ago        Up 1 seconds        8080/tcp                  goofy_pare
```

**Comment by icecrime** [comment]
Discussed with @aboch: he'll contribute tests in an ulterior PR. It's his first contrib so he needs a bit more time, and we'd like to unblock 1.7.0-rc2 the earliest.

**Comment by thaJeztah** [comment]
SGTM thanks so much @aboch!

**Comment by jfrazelle** [comment]
cherry-picked
