### PR TITLE
Fix flaky test TestServiceGet

### LINKED ISSUE #37245: Flaky test: TestServiceGet
Windows https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS1/21104/console failed on a test that looks racy; seen it fail on some others, and looks like it's comparing timestamps (which can obviously fail);

```
17:47:17 ok  	github.com/docker/docker/volume/mounts	0.084s	coverage: 66.9% of statements
17:47:17 --- FAIL: TestServiceGet (0.09s)
17:47:17 	service_test.go:144: assertion failed: 
17:47:17 		{*types.Volume}.CreatedAt:
17:47:17 			-: "2018-06-08T17:46:53Z"
17:47:17 			+: "2018-06-08T17:46:54Z"
17:47:17 		
17:47:17 time="2018-06-08T17:46:54Z" level=warning msg="could not determine size of volume" error="GetFileAttributesEx fake: The system cannot find the file specified." volume=test
17:47:17 time="2018-06-08T17:46:54Z" level=warning msg="could not determine size of volume" error="GetFileAttributesEx fake: The system cannot find the file specified." volume=test
17:47:17 time="2018-06-08T17:46:54Z" level=warning msg="could not determine size of volume" error="GetFileAttributesEx fake: The system cannot find the file specified." volume=test
17:47:17 time="2018-06-08T17:46:54Z" level=warning msg="could not determine size of volume" error="GetFileAttributesEx fake: The system cannot find the file specified." volume=test3
17:47:17 time="2018-06-08T17:46:54Z" level=warning msg="could not determine size of volume" error="GetFileAttributesEx fake: The system cannot find the file specified." volume=test
17:47:17 FAIL
```

### PR DESCRIPTION
**Pull request by katakonst**
Fixes  #37245

**- What I did**
Fix flaky tests when comparing volumes
**- How I did it**
Ignore CreatedAt field when comparing volumes

**- A picture of a cute animal (not mandatory but encouraged)**

image

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

File: volume/service/service_test.go [hunk 1]
```diff
@@ -141,7 +143,7 @@ func TestServiceGet(t *testing.T) {
 
 	v, err = service.Get(ctx, "test")
 	assert.Assert(t, err)
-	assert.Assert(t, is.DeepEqual(created, v))
+	assert.Assert(t, is.DeepEqual(created, v, cmpopts.IgnoreFields(types.Volume{}, "CreatedAt")))
```
Comment (tonistiigi) [inline volume/service/service_test.go]: Why would these have different created time?

Comment (thaJeztah) [reply volume/service/service_test.go]: Wonder if it's due to `t.Parallel()`; could it be that we're inspecting a volume named `test` from another test?

Comment (katakonst) [reply volume/service/service_test.go]: It may be because for testing it uses the FakeVolume type which has the method:
https://github.com/moby/moby/blob/5037c5a8ce762b46638378b7a7d1081572eadba1/volume/testutils/testutils.go#L72

Which is used to assign a value to the CreatedAt field.

Comment (thaJeztah) [reply volume/service/service_test.go]: Ah, yes, that definitely looks like the problem. We should probably set an actual `created` date when creating the volume;

https://github.com/moby/moby/blob/5037c5a8ce762b46638378b7a7d1081572eadba1/volume/testutils/testutils.go#L93-L100


And update `NewFakeVolume ()` to take that date as an argument

https://github.com/moby/moby/blob/5037c5a8ce762b46638378b7a7d1081572eadba1/volume/testutils/testutils.go#L40-L49

Comment (tonistiigi) [reply volume/service/service_test.go]: We probably don't need the date argument. Just take the current time inside `NewFakeVolume`, store it and always use the same date later.

Comment (thaJeztah) [reply volume/service/service_test.go]: Ah, yes, that should be sufficient

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

@tonistiigi PTAL

**Review by tonistiigi — APPROVED** [review]

**Comment by thaJeztah** [comment]
Thanks @katakonst !
