### PR TITLE
daemon: handleContainerExit: ignore networking errors

### LINKED ISSUE #49501: Containers with a port already in use restart in a tight loop
### Description

When a container binding a port already in use is started, the Engine tries to restart that container in a tight loop. This leads to Engine logs being spammed with the following sequence:

```
WARN[2025-02-20T10:39:14.092909922Z] Failed to allocate and map port: Bind for 0.0.0.0:80 failed: port is already allocated  eid=d19d71c1b21f33fa01e03609411c44e38b1306e92753347fdbf480267d3fe8df ep=test-nginx-2 net=bridge nid=275131c11d246d6d9f2badbeb6fcb8b274560d527eb2c00133078628d87b8823
INFO[2025-02-20T10:39:14.103913422Z] shim disconnected                             id=4bc653f7c8eafdfbbe9741c77a5c9b8a90268f281e89cf2a5180b5a5957d3142 namespace=moby
WARN[2025-02-20T10:39:14.103969089Z] cleaning up after shim disconnected           id=4bc653f7c8eafdfbbe9741c77a5c9b8a90268f281e89cf2a5180b5a5957d3142 namespace=moby
INFO[2025-02-20T10:39:14.103975839Z] cleaning up dead shim                         namespace=moby
INFO[2025-02-20T10:39:14.103990672Z] ignoring event                                container=4bc653f7c8eafdfbbe9741c77a5c9b8a90268f281e89cf2a5180b5a5957d3142 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
ERRO[2025-02-20T10:39:14.116708297Z] restartmanger wait error: driver failed programming external connectivity on endpoint test-nginx-2 (d19d71c1b21f33fa01e03609411c44e38b1306e92753347fdbf480267d3fe8df): Bind for 0.0.0.0:80 failed: port is already allocated
```

This was introduced in: fe856b94b5149718b1a7f369220608846fea32bc.

### Reproduce

```
$ docker run --rm -d -p 80:80 --name test-nginx nginx
$ docker run -d -p 80:80 --name test-nginx-2 --restart=always nginx
```

### Expected behavior

When a container can't be started because one of its port is already in use, the Engine shouldn't try to restart the container. That's what the Engine did prior to v28.0.

### docker version

```bash
Client:
 Version:           27.4.1
 API version:       1.47
 Go version:        go1.22.10
 Git commit:        b9d17ea
 Built:             Tue Dec 17 15:42:24 2024
 OS/Arch:           darwin/arm64
 Context:           default

Server:
 Engine:
  Version:          dev
  API version:      1.48 (minimum version 1.24)
  Go version:       go1.23.6
  Git commit:       af898abe44662d9554fb15ee4d4a7307f1b8e315
  Built:            Thu Feb 20 10:46:42 2025
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v1.7.25
  GitCommit:        bcc810d6b9066471b0b6fa75f557a15a1cbf31bb
 runc:
  Version:          1.2.5
  GitCommit:        v1.2.5-0-g59923ef
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    27.4.1
 Context:    default
 Debug Mode: false
 Plugins:
  ai: Docker AI Agent - Ask Gordon (Docker Inc.)
    Version:  v0.8.4
    Path:     /Users/aker/.docker/cli-plugins/docker-ai
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.19.1-desktop.1
    Path:     /Users/aker/.pinata/downloads/docker-plugins/v0.19.1-desktop.1/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.33.0-desktop.1
    Path:     /Users/aker/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.38
    Path:     /Users/aker/.docker/cli-plugins/docker-debug
  desktop: Docker Desktop commands (Beta) (Docker Inc.)
    Version:  v0.1.4
    Path:     /Users/aker/.docker/cli-plugins/docker-desktop
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /Users/aker/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.27
    Path:     /Users/aker/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     /Users/aker/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.4.0
    Path:     /Users/aker/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/aker/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.16.3
    Path:     /Users/aker/.docker/cli-plugins/docker-scout

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 1
 Server Version: dev
 Storage Driver: vfs
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: crun io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: bcc810d6b9066471b0b6fa75f557a15a1cbf31bb
 runc version: v1.2.5-0-g59923ef
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.10.14-linuxkit
 Operating System: Debian GNU/Linux 12 (bookworm) (containerized)
 OSType: linux
 Architecture: aarch64
 CPUs: 14
 Total Memory: 7.653GiB
 Name: f925c01a725e
 ID: dbdd9b72-428c-467d-a08d-7e5a666e73d2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false

[DEPRECATION NOTICE]: API is accessible on http://0.0.0.0:2374 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/go/attack-surface/
In future versions this will be a hard failure preventing the daemon from starting! Learn more at: https://docs.docker.com/go/api-security/
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by akerouanton**
- fixes https://github.com/moby/moby/issues/49501

Related to:

- https://github.com/moby/moby/pull/47406

**- What I did**

Prior to commit fe856b94b5149718b1a7f369220608846fea32bc, containers' network sandbox and interfaces were created before the containerd task. Now, it's created after.

If this step fails, the containerd task is forcefully deleted, and an event is sent to the c8d event monitor, which triggers `handleContainerExit`. Then this method tries to restart the faulty container.

This leads to containers with a published port already in use to be stuck in a tight restart loop (if they're started with `--restart=always`) until the port is available. This is needlessly spamming the daemon logs.

Prior to that commit, a published port already in use wouldn't trigger the restart process.

**- How I did it**

This commit adds a check to `handleContainerExit` to ignore exit events if the latest container error is related to networking setup.

**- How to verify it**

**- Human readable description for the release notes**

```markdown changelog
Fix a bug that was causing containers with `--restart=always` and a published port already in use to be restarting in a tight loop.
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: daemon/monitor.go [hunk 1]
```diff
@@ -32,6 +32,16 @@ func (daemon *Daemon) handleContainerExit(c *container.Container, e *libcontaine
 	var ctrExitStatus container.ExitStatus
 	c.Lock()
 
+	// If the container is not running, paused, or restarting, then the exit
+	// event was triggered while the container was being created. This
+	// indicates that the networking config, and thus the container spec, is
+	// temporarily or permanently invalid. In that case, we don't want to
+	// restart the container.
+	if !c.State.Running && !c.State.Paused && !c.State.Restarting {
```
Comment (akerouanton) [inline daemon/monitor.go:40]: @vvoland Could you confirm whether this change is reasonable? As mentioned in the commit message / PR description, this is also going to ignore any error happening during the following call to c8d. I'm not 100% sure if this is okay, or if we do want to trigger the restart process if this call fails.

https://github.com/moby/moby/blob/af898abe44662d9554fb15ee4d4a7307f1b8e315/daemon/start.go#L240-L242

Comment (vvoland) [reply daemon/monitor.go:40]: Shouldn't we still execute the rest of the function though? The task was still created, so the cleanup should still happen I think?

Comment (vvoland) [reply daemon/monitor.go:40]: We should only make sure that we don't restart the container. Perhaps we could also make use of `c.State.Err() != nil`.

Comment (akerouanton) [reply daemon/monitor.go]: > Shouldn't we still execute the rest of the function though? The task was still created, so the cleanup should still happen I think?

As dicussed on Slack, we need to early return from handleContainerExit to keep the container in Created state (as it was before 28.0). Otherwise the container will be reported in Exited state with exit code == 137.

**Review by vvoland — APPROVED** [review]
LGTM

File: daemon/start_linux.go [hunk 2]
```diff
@@ -34,5 +34,8 @@ func (daemon *Daemon) initializeCreatedTask(
 			return errdefs.System(err)
 		}
 	}
-	return daemon.allocateNetwork(ctx, cfg, ctr)
+	if err := daemon.allocateNetwork(ctx, cfg, ctr); err != nil {
+		return fmt.Errorf("failed to set up container networking: %w", err)
```
Comment (robmry) [inline daemon/start_linux.go:38]: The test failure should be enough to avoid regressions. But, as these are both in `package daemon`, could put the error string in a const to make it clear where the message is used?

**Review by robmry — APPROVED** [review]
LGTM

File: daemon/start_linux.go (hunk 2 above)
Comment (akerouanton) [reply daemon/start_linux.go]: Done.

**Review by neersighted — APPROVED** [review]
LGTM
