### PR TITLE
[19.03 backport] Use certs.d from XDG_CONFIG_HOME when in rootless mode (fixes #40236)

### LINKED ISSUE #40236: Docker rootless dies when unable to read /etc/docker/certs.d
**Description**

**Steps to reproduce the issue:**
1. sudo mkdir -p /etc/docker/certs.d/quay.io && sudo touch /etc/docker/certs.d/quay.io/{client.cert,client.key,ca.crt} && sudo chmod 700 /etc/docker/certs.d/quay.io
2.  ./dockerd-rootless.sh --experimental
3.  docker -H unix:///run/user/<UID>/docker.sock pull quay.io/benyoo/gitlab

**Describe the results you received:**
```bash
docker -H unix:///run/user/1000/docker.sock pull quay.io/benyoo/gitlab
Using default tag: latest
Error response from daemon: open /etc/docker/certs.d/quay.io: permission denied
```

**Describe the results you expected:**
If the rootless daemon cannot read /etc/docker/certs.d, it should ignore the directory.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:52:22 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          dev
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.3
  Git commit:       649e4c8
  Built:            Mon Nov 11 12:42:03 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.3.0
  GitCommit:        36cf5b690dcc00ff0f34ff7799209050c3d0c59a
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: dev
 Storage Driver: vfs
 Logging Driver: json-file
 Cgroup Driver: none
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 36cf5b690dcc00ff0f34ff7799209050c3d0c59a
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
  rootless
 Kernel Version: 3.10.0-1062.4.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.699GiB
 Name: localhost.localdomain
 ID: ZGPZ:WCD7:AL65:BPHK:FEDC:XROH:BTT2:GS6N:V4ZJ:2W5Y:ZS7A:RPMY
 Docker Root Dir: /home/brian/.local/share/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
N/A

### PR DESCRIPTION
**Pull request by AkihiroSuda**
cherrypick #40243

### CODE REVIEW

File: registry/registry.go [hunk 1]
```diff
@@ -17,6 +17,9 @@ import (
 	"github.com/docker/go-connections/sockets"
 	"github.com/docker/go-connections/tlsconfig"
 	"github.com/sirupsen/logrus"
+
+	"github.com/docker/docker/pkg/homedir"
```
Comment (thaJeztah) [inline registry/registry.go]: nit: looks like gofmt fix-up was done in https://github.com/moby/moby/pull/40349, so possibly pick that one as well

File: registry/registry.go [hunk 2]
```diff
@@ -56,7 +71,7 @@ func hasFile(files []os.FileInfo, name string) bool {
 // provided TLS configuration.
 func ReadCertsDirectory(tlsConfig *tls.Config, directory string) error {
 	fs, err := ioutil.ReadDir(directory)
-	if err != nil && !os.IsNotExist(err) {
+	if err != nil && !os.IsNotExist(err) && !os.IsPermission(err) {
```
Comment (thaJeztah) [inline registry/registry.go]: This was the only change I had to give some thinking (could this hide actual errors?) I _guess_ in the "rootful" situation, `root` would always have access, unless (e.g.) a "read-only filesystem", AppArmor, or Seccomp would also show up as a "permission" error (?)

Would be good if someone could try if that's possible, and if so, we should to a follow-up to log the `os.IsNotExist(err)` error as a Warning instead of fully ignoring it.

Comment (thaJeztah) [reply registry/registry.go]: @AkihiroSuda Actually; now that we're using a different path for the rootless situation; why would we want a permission error to be ignored at all? Shouldn't it remain an error situation?

**Review by thaJeztah — CHANGES_REQUESTED** [review]
Sorry, I realize this is a cherry-pick of something that's already on master, but have some questions reading over it again 🤗

File: registry/registry.go (hunk 2 above)
Comment (AkihiroSuda) [reply registry/registry.go]: @sh7dm ptal?

Comment (sh7dm) [reply registry/registry.go]: Hmm, I don't really remember why it was added.

Comment (sh7dm) [reply registry/registry.go]: This was introduced before, so daemon won't fail if it can't find or access `certs.d`, the final fix I did in second commit was searching for `certs.d` in `$XDG_CONFIG_HOME`.

Comment (thaJeztah) [reply registry/registry.go]: Thanks! So looks like we can remove that;

```suggestion
	if err != nil && !os.IsNotExist(err) {
```

I'll open a PR on master

Comment (sh7dm) [reply registry/registry.go]: :+1: Great! Thanks!

Comment (thaJeztah) [reply registry/registry.go]: Looks like it's a separate commit, @AkihiroSuda, so you can drop the commit from this cherry-pick to address it.

For master, I opened https://github.com/moby/moby/pull/40576, which reverts the commit

Comment (AkihiroSuda) [reply registry/registry.go]: dropped this commit

File: registry/registry.go (hunk 1 above)
Comment (thaJeztah) [reply registry/registry.go]: ^ didn't apply cleanly, so not worth spending too much time on

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@cpuguy83 @tiborvass PTAL

**Comment by thaJeztah** [comment]
Why is swagger failing to build? Let me check if we made a mistake somewhere and didn't update it to use the forked version with fixes.

```

[2020-02-26T08:16:19.168Z] #15 ERROR: executor failed running [/bin/sh -c set -x 	&& export GOPATH="$(mktemp -d)" 	&& git clone https://github.com/go-swagger/go-swagger.git "$GOPATH/src/github.com/go-swagger/go-swagger" 	&& (cd "$GOPATH/src/github.com/go-swagger/go-swagger" && git checkout -q "$GO_SWAGGER_COMMIT") 	&& go build -o /build/swagger github.com/go-swagger/go-swagger/cmd/swagger 	&& rm -rf "$GOPATH"]: runc did not terminate sucessfully
[2020-02-26T08:16:19.168Z] ------
[2020-02-26T08:16:19.168Z]  > [swagger 1/1] RUN set -x 	&& export GOPATH="$(mktemp -d)" 	&& git clone https://github.com/go-swagger/go-swagger.git "/go/src/github.com/go-swagger/go-swagger" 	&& (cd "/go/src/github.com/go-swagger/go-swagger" && git checkout -q "c28258affb0b6251755d92489ef685af8d4ff3eb") 	&& go build -o /build/swagger github.com/go-swagger/go-swagger/cmd/swagger 	&& rm -rf "/go":
[2020-02-26T08:16:19.168Z] ------
```

**Comment by thaJeztah** [comment]
Hm, nope, that's not it; the 19.03 branch still points to https://github.com/go-swagger/go-swagger/commit/c28258affb0b6251755d92489ef685af8d4ff3eb, which is the non-forked version.

This PR updates the branch to use the fork, but it's not merged yet; https://github.com/moby/moby/pull/40558

**Comment by thaJeztah** [comment]
Triggered CI again 🤷‍♂

**Review by cpuguy83 — APPROVED** [review]
LGTM
