### PR TITLE
Conntrack flush support

### LINKED ISSUE #8795: Failed to receive UDP traffic after container restart
I start a container and share a port for UDP traffic as this:

docker run —rm -p 5060:5060/udp —name host1 -i -t ubuntu:14.04

Then in that container I wait for traffic with:

nc -u -l 5060

I then generate traffic from another machine:

nc -u <docker_host_ip> 5060

Then everything works fine and I can see that I receive the UDP traffic in the container.

But when I exit the container and do the same thing again, then I can no longer receive UDP traffic in the docker container.
If I wait for about 5 minutes before I start to send it will work though. I have also noticed that if the sender change the port it is binding to locally it will also work.  So there seems to be some mapping that is not deleted when the docker container is removed.

### LINKED ISSUE #31414: Leaked namespace and network interfaces if container startup (prestart hook) fails
**Description**
We've observed an issue where occasionally container startup fails with the following error:

```
docker[28335]: /usr/bin/docker: Error response from daemon: oci runtime error: process_linux.go:334: running prestart hook 0 caused "exit status 1: time=\"2017-01-27T11:04:33+01:00\" level=fatal msg=\"failed to add interface veth944fac0 to sandbox: failed to set link up: device or resource busy\" \n".
```

After the above failure, all subsequent docker run commands with the same IP address specified fail with the following error:

```
docker[28335]: /usr/bin/docker: Error response from daemon: oci runtime error: process_linux.go:334: running prestart hook 0 caused "exit status 1: time=\"2017-01-27T11:04:33+01:00\" level=fatal msg=\"failed to add interface veth944fac0 to sandbox: failed to set link up: device or resource busy\" \n".
```

The containers are run via `docker run --net=ournetwork --ip=10.10.10.1 --ip6=fec0::a123:10:10:10:1 image-name`. We're using a custom network with the macvlan driver:

```
docker network inspect ournetwork
[
    {
        "Name": "ournetwork",
        "Id": "55f89666fe515afb05927762eadad282f663ade59f34dd11fb0ffe2894428eb1",
        "Scope": "local",
        "Driver": "macvlan",
        "EnableIPv6": true,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "10.10.0.0/16",
                    "Gateway": "10.10.255.254"
                },
                {
                    "Subnet": "fec0:0:0:a123::/64"
                }
            ]
        },
        "Internal": false,
        "Containers": {},
        "Options": {
            "parent": "eth0"
        },
        "Labels": {}
    }
]
```

I've found some seemingly unused netns mounts in /var/run/docker/netns, and running `ip address show` in those unused network namespaces reveals that the namespace and a network interface in it with IP address 10.10.10.1 is leaked after each and every error where the prestart hook fails.

For example, in netns fc371b062ac8, running `ip address show` shows the following:

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
10006: eth0@if2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default 
    link/ether 02:42:0a:6e:1e:1c brd ff:ff:ff:ff:ff:ff
    inet 10.10.10.1/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fec0::a123:10:10:10:1/64 scope site nodad 
       valid_lft forever preferred_lft forever
```

**Steps to reproduce the issue:**

After the first (random, seemingly some kind of race condition adding the IPv6 gateway) prestart hook failure, all subsequent 'docker run' commands fail and all of them leak the network namespace and the interfaces created.

**Describe the results you received:**

The IP address configured in `docker run --ip` can be pinged even though the container is not running.

**Describe the results you expected:**

The namespace and all associated interfaces should be properly deleted if container startup fails.

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   34a2ead
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   34a2ead
 Built:        
 OS/Arch:      linux/amd64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

We're running CoreOS 1235.1.0 with the docker version supplied with that release.

Since the error messages above are printed by runc, I've previously reported this as a runc issue (https://github.com/opencontainers/runc/issues/1352), but it seems that even though runc is failing, it's the docker daemon that was supposed to clean up after such a failure.

### LINKED ISSUE #31610: Docker creates ingress network folder in /var/lib/docker even when using -g
**Description**

We are specifying a different docker root with `-g`, i.e. `-g /data/docker/`. It works, however docker is still recreating the `/var/lib/docker` folder and creates: `/var/lib/docker/network/files/ingress_sbox`.

Inside that folder are three files:
```
root@xxx:/var/lib/docker/network/files/ingress_sbox# ls -l
total 12
-rw-r--r-- 1 root root 150 Mar  7 13:18 hosts
-rw-r--r-- 1 root root  58 Mar  7 13:18 resolv.conf
-rw-r--r-- 1 root root  71 Mar  7 13:18 resolv.conf.hash
```

**Steps to reproduce the issue:**
1. Create a swarm
2. Create a service

**Describe the results you received:**
Docker is creating the `/var/lib/docker` folder.

**Describe the results you expected:**
Docker shouldn't create the `/var/lib/docker` folder.

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:01:32 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:01:32 2017
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 20
 Running: 6
 Paused: 0
 Stopped: 14
Images: 20
Server Version: 17.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 9xet8ik8dju4y8786a2b3aemd
 Is Manager: true
 ClusterID: c935qq94yavddxpuc6292zbxu
 Managers: 3
 Nodes: 5
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.31.70.70
 Manager Addresses:
  172.31.70.70:2377
  172.31.71.70:2377
  172.31.72.70:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.952 GiB
Name: ip-172-31-70-70
ID: FMBW:VTZX:TIKD:2IDU:P23J:LAOZ:5PAX:ZUOT:WUIY:NTES:LX5W:VR76
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Swarm is hosted in AWS, we are specifying a second EBS volume (which is encrypted) with `-g`.

### PR DESCRIPTION
**Pull request by fcrisciani**
**- What I did**
Fixes #8795 
Fixes #31610
Fixes #31414

On external connectivity removal, the bridge driver will take care of erasing all the conntrack flows relative to the endpoint that is going down

**- How I did it**
Introduced the conntrack support in the netlink library and then from libnetwork will cleanup the flows passing the IP address of the endpoint that is going down

**- How to verify it**
Added a test that creates a server container and a client container and establishes an UDP flow (using UDP for simplicity) between them.
The test verifies the presence of the flow fetching its from the conntrack table.
The server container is then destroyed and the tests validates that the previous flow got purged from conntrack.

**- Description for the changelog**

Conntrack flush on external connectivity removal

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by mavenugo** [comment]
@fcrisciani thanks for resolving this long standing issue and a good test to catch it as well.

LGTM

**Review by mavenugo — APPROVED** [review]

**Comment by vieux** [comment]
LGTM

File: integration-cli/docker_cli_nat_test.go [hunk 1]
```diff
@@ -81,3 +83,54 @@ func (s *DockerSuite) TestNetworkLoopbackNat(c *check.C) {
...
+	cmd = "echo aa | nc -q 1 -u 192.168.10.1 8080"
+	_, _, err = dockerCmdWithError("run", "-d", "--name", "client", "--net=host", "appropriate/nc", "sh", "-c", cmd)
+	c.Assert(err, check.IsNil)
+
+	// Get all the flows using netlink
+	flows, err := netlink.ConntrackTableList(netlink.ConntrackTable, syscall.AF_INET)
+	c.Assert(err, check.IsNil)
+	var flowMatch int
+	for _, flow := range flows {
+		if flow.Forward.Protocol == 17 &&
```
Comment (AkihiroSuda) [inline integration-cli/docker_cli_nat_test.go]: Can we use constant for this magic number?

**Comment by mavenugo** [comment]
@fcrisciani the windowsRS1 failure seems genuine - 

```
02:32:17 # github.com/docker/docker/vendor/github.com/vishvananda/netns
02:32:17 ..\vendor\github.com\vishvananda\netns\netns.go:27: undefined: syscall.Stat_t
02:32:17 ..\vendor\github.com\vishvananda\netns\netns.go:28: undefined: syscall.Fstat
02:32:17 ..\vendor\github.com\vishvananda\netns\netns.go:31: undefined: syscall.Fstat
02:32:17 ..\vendor\github.com\vishvananda\netns\netns.go:39: undefined: syscall.Stat_t
02:32:17 ..\vendor\github.com\vishvananda\netns\netns.go:43: undefined: syscall.Fstat
02:32:17 ..\vendor\github.com\vishvananda\netns\netns.go:57: cannot use int(*ns) (type int) as type syscall.Handle in argument to syscall.Close
02:32:17 FAIL	github.com/docker/docker/integration-cli [build failed]
```

File: integration-cli/docker_cli_nat_test.go (hunk 1 above)
Comment (fcrisciani) [inline integration-cli/docker_cli_nat_test.go]: will do

**Comment by thaJeztah** [comment]
ping @mavenugo @vieux all green now; ready to merge?

**Comment by thaJeztah** [comment]
adding `impact/changelog`, because https://github.com/docker/docker/issues/8795 has been a long standing issue, so worth a mention in the changelog

**Comment by mavenugo** [comment]
@thaJeztah @vieux 👍

**Comment by thaJeztah** [comment]
Thanks! I'll go ahead and merge 👍

File: integration-cli/docker_cli_network_unix_test.go [hunk 2]
```diff
@@ -1789,3 +1790,56 @@ func (s *DockerNetworkSuite) TestDockerNetworkDisconnectFromBridge(c *check.C) {
...
+func (s *DockerNetworkSuite) TestConntrackFlowsLeak(c *check.C) {
+	testRequires(c, IsAmd64, DaemonIsLinux, Network)
+
+	// Create a new network
+	dockerCmd(c, "network", "create", "--subnet=192.168.10.0/24", "--gateway=192.168.10.1", "-o", "com.docker.network.bridge.host_binding_ipv4=192.168.10.1", "testbind")
+	assertNwIsAvailable(c, "testbind")
+
+	// Launch the server, this will remain listening on an exposed port and reply to any request in a ping/pong fashion
+	cmd := "while true; do echo hello | nc -w 1 -lu 8080; done"
+	_, _, err := dockerCmdWithError("run", "-d", "--name", "server", "--net", "testbind", "-p", "8080:8080/udp", "appropriate/nc", "sh", "-c", cmd)
```
Comment (seemethere) [inline integration-cli/docker_cli_network_unix_test.go]: `appropriate/nc`?

tisk tisk

Comment (fcrisciani) [reply integration-cli/docker_cli_network_unix_test.go]: ?

Comment (vieux) [reply integration-cli/docker_cli_network_unix_test.go]: @fcrisciani I think @seemethere was refering to the use of a 3rd party image, and it that case it was not updated in 2 years. could you replace it with a simple `alpine` for the official library ? it includes `nc`

Comment (fcrisciani) [reply integration-cli/docker_cli_network_unix_test.go]: @vieux @seemethere Using that image is not accidental but is intended. The nc version in alpine does not support for example the option -q. There is a bug in nc that let the command never return also when specify the -w option. 
Feel free to try to change it to the alpine removing the -q option to let the command work, but most likely the test will fail timing out because the nc command will hang forever.
