### PR TITLE
Fix duplicate container names conflict

### LINKED ISSUE #15995: Race condition causing 'a container has already joined the endpoint'
Related to #14083
Very similar to  #15727, but in this case it's not as repeatable.

We're seeing a test in the compose test suite (`ServiceTest.test_scale_with_custom_container_name_outputs_warning`) fail frequently against docker 1.8.1 (docker is curled from https://get.docker.com/builds/Linux/x86_64/docker-1.8.1 on each run): https://jenkins.dockerproject.org/job/Compose-PRs/1208/console

```
ERROR: for 2  Cannot start container 95da47d874fa328c0d6585130237b82ab9ba495ccb462ce939ffcdd90becded0: a container has already joined the endpoint 
ERROR: for 3  Cannot start container c531de7a43481b59f02961554a65830f04076586a8695d829a06e185112d6489: a container has already joined the endpoint 
```

### Description of problem:

The test attempts to create 3 containers with the same name (in parallel). The expected result is that one container should be created and started, and the other two should fail. The test runs successfully occasionally, but fairly often we're seeing a failure case where one container is created, but fails to start. 

```
$ docker inspect custom-container | jq '.[].State'
{
  "FinishedAt": "0001-01-01T00:00:00Z",
  "StartedAt": "0001-01-01T00:00:00Z",
  "Running": false,
  "Paused": false,
  "Restarting": false,
  "OOMKilled": false,
  "Dead": false,
  "Pid": 0,
  "ExitCode": 128,
  "Error": "a container has already joined the endpoint"
}
```

### Expected result

One container should be created and started

### Actual result

The one container was created but it failed to start

### Steps to Reproduce

```
parallel docker run --name duplicate -d alpine:edge sleep ::: 2 2 2 2
```

It will fail 25%-75% of the runs.

Running it against a `docker-machine` virtualbox with no containers doesn't trigger the error, so it may need a few containers to trigger the issue.

### PR DESCRIPTION
**Pull request by tonistiigi**
While creating multiple containers the second 
container could remove the first one from graph
and not produce an error.

Fixes #15995

Signed-off-by: Tonis Tiigi tonistiigi@gmail.com

### CODE REVIEW

**Comment by crosbymichael** [comment]
LGTM

**Comment by thaJeztah** [comment]
:heart: much cleaner LGTM

**Comment by tiborvass** [comment]
LGTM

**Comment by crosbymichael** [comment]
Who wrote this bad code?

me

**Comment by calavera** [comment]
@tonistiigi I think this also closes #15727, doesn't it?

**Comment by calavera** [comment]
nevermind

**Comment by tiborvass** [comment]
Tested locally, `make test` succeeded. Merging.

File: daemon/daemon.go [hunk 1]
```diff
@@ -407,20 +407,12 @@ func (daemon *Daemon) reserveName(id, name string) (string, error) {
 
 		conflictingContainer, err := daemon.GetByName(name)
 		if err != nil {
-			if strings.Contains(err.Error(), "Could not find entity") {
-				return "", err
-			}
```
Comment (mountkin) [inline daemon/daemon.go]: I came across a condition where the container record exists in the sqlite database (aka `containerGraphDB` to the daemon) but absent from the `contStore`.
I switched the storage driver from device mapper to aufs long time ago. The containers that were created with device mapper couldn't be registered to the `contStore` because of different storage drivers.
In this case when I run `docker ps -a` it shows no containers.
But if I try to create a container with the name that were used by the broken container in the sqlite database,  the `err` here is ` Could not find container for entity id xxx` and the create command fails with `Error response from daemon: Could not find container for entity id f2bd2b291853fe70c9b3cc378d2bbf04c2089d5c61893748761bcbfc795c5911`. This is really confusing.

I think the `if` condition above is opposite and should be changed to 
```go
if !strings.Contains(err.Error(), "Could not find entity") {
	return "", err
} else {
	// Remove name and continue starting the container
}
```

If it's unsafe to do this, I think we should either refuse the container to start or delete the broken container records from database at start up if some of the containers were created with different storage drivers.

My 0.02 cents :smile_cat:

Comment (thaJeztah) [inline daemon/daemon.go]: Just wondering; could we make those containers show up in `docker ps -a` in stead? And allow users to remove them? I'm not a big fan of too much "magic" / "smart" behavior (especially when poorly documented, lol)

Comment (mountkin) [inline daemon/daemon.go]: @thaJeztah I like your idea. Perhaps we should add a new container state to mark the broken containers.
I'll open a PR for discussion.

Comment (thaJeztah) [inline daemon/daemon.go]: Thanks @mountkin, and thanks for finding this situation; we were scratching our heads a bit because of this code, and it looks like there are unhandled situations :+1:

Comment (mountkin) [inline daemon/daemon.go]: @thaJeztah  On second thought perhaps allowing the user to delete the broken containers is a bit dangerous. The container's config and the record in the graph db can be deleted, but the data generated by the container can not be easily deleted because it's using a different storage driver. If we only delete the index and config of the container when the user run `docker rm xxx`, there'll be garbage data left on the disk.
Is it possible to maintain a `linkgraph.db` for each graph driver?  This way the user can switch between different graph drivers without such problem.
I noticed that each graph driver already has its own image repositories file, such as `repositories-aufs`, `repositories-devicemapper`, etc.

BTW: I created a patch here https://github.com/mountkin/docker/commit/3563666d3d98661385131ef723cb33bfd325410b but I'm hesitating whether it's the right way to handle this situation.

Comment (thaJeztah) [inline daemon/daemon.go]: @mountkin hm, good question w.r.t the graph.db

> If we only delete the index and config of the container when the user run docker rm xxx, there'll be garbage data left on the disk.

But that would be the same as the "automagic" removal?

Comment (mountkin) [inline daemon/daemon.go]: The difference is that the user can reuse the name without breaking the containers from other storage driver.
Another possible solution is keep the current behavior but improve the error message to tell the user exactly what had happened and how to delete the bad containers.

Comment (thaJeztah) [inline daemon/daemon.go]: perhaps you should open that PR, so that we have some more room to discuss it (and have other maintainers have their comment added)

Comment (mountkin) [inline daemon/daemon.go]: Will open the PR tomorrow. It's midnight here :zzz:

Comment (thaJeztah) [inline daemon/daemon.go]: sure! no problem, thanks so much in advance

Comment (tonistiigi) [inline daemon/daemon.go]: I agree that we should probably separate containers by graphdriver. Other way would be to load containers into a broken state and allow users to delete, but I think this will be more confusing to the user with benefits only in very rare cases. Magically removing containers on conflict seems like the worst option.
