### PR TITLE
Prevent double escaping of Dockerfile commands on Windows

### LINKED ISSUE #17509: Building Windows Docker images doesn't work as well as in previous versions
Description of problem:

Building Windows Docker images doesn't work as well as in previous versions.

`docker version`:
```
Client:
 Version:      1.9.0-dev
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   9657062
 Built:        Thu Oct 29 02:23:58 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.9.0-dev
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   9657062
 Built:        Thu Oct 29 02:23:58 UTC 2015
 OS/Arch:      windows/amd64
```

`docker info`:
```
PS C:\Windows\system32> docker info
Containers: 45
Images: 235
Server Version: 1.9.0-dev
Storage Driver: windowsfilter
 Windows:
Execution Driver: Windows 1854 1.9.0-dev 9657062
Logging Driver: json-file
Kernel Version: 10.0 10514 (10514.10.amd64fre.th2_release_svc.151006-1500)
Operating System: Windows Server 2016 Technical Preview 3
CPUs: 2
Total Memory: 4 GiB
Name: vagrant-2016
ID: BGZN:GWR2:JUZY:J35M:2KDB:JTE4:L6QA:OHVU:Q4TK:MHG3:BDUW:NNXF
Debug mode (server): true
 File Descriptors: -1
 Goroutines: 17
 System Time: 2015-10-29T22:27:53.2108401+01:00
 EventsListeners: 0
 Init SHA1:
 Init Path: C:\Windows\System32\docker.exe
 Docker Root Dir: C:\ProgramData\docker
```

`uname -a`:
```
MSYS_NT-10.0 vagrant-2016 2.3.0(0.290/5/3) 2015-09-29 10:48 x86_64 Msys
```

Environment details (AWS, VirtualBox, physical, etc.):
Windows 2016 TP3 Build 10514 with latest Windows updates running in VMware Fusion 7.1.2 on a MacBook Pro El Capitan 10.11.1

How reproducible:

Building a Node.js 4.2.1 Docker image for Windows does not install Node.js with the current nightly build of the Docker Engine for Windows.

Steps to Reproduce:
1.) Take Windows 2016 TP3 with latest Windows Updates and docker installed 

2.) Update docker to latest in an admin PowerShell:
```
stop-service docker
wget https://master.dockerproject.org/windows/amd64/docker.exe -outfile C:\windows\system32\docker.exe
start-service docker
```

3.) Save the following Dockerfile for Node.js 4.2.1
```
FROM windowsservercore

ENV NPM_CONFIG_LOGLEVEL info
ENV NODE_VERSION 4.2.1
ENV NODE_SHA256 e460a71ea9aa4d743387a20319042de203de837cb613be0737b6ca368480302d

RUN powershell -Command " \
    wget -Uri https://nodejs.org/dist/v%NODE_VERSION%/node-v%NODE_VERSION%-x64.msi -OutFile node.msi -UseBasicParsing; \
    if ((Get-FileHash node.msi -Algorithm sha256).Hash -ne $env:NODE_SHA256) {exit 1}; \
    msiexec /q /i node.msi | Out-Null; \
    Remove-Item -Path node.msi; \
    wget -Uri https://github.com/StefanScherer/win-patch-iojs/releases/download/1.0.9/patchiojs.exe -OutFile patchiojs.exe -UseBasicParsing; \
    patchiojs.exe 'C:/Program Files/nodejs/node.exe'; \
    Remove-Item -Path patchiojs.exe; \
    "

CMD [ "node" ]
```

4.) Build the Node.js 4.2.1 Docker image with this Dockerfile
```
docker build -t node --no-cache .
```

5.) Check if node is installed by running the interpreter
```
docker run --rm -ti node node --version
```

Actual Results:

```
PS Z:\-vagrant\resources\dockerfiles-windows\node> docker run --rm -ti node node --version
Error response from daemon: Cannot start container 70427d7cb1a3472bf167796af1bc6c3e302f4f8bcd776c1cc4020a0d4791b46d: HCSShim::CreateProcessInComputeSystem - Win32 API call returned error r1=2147942402 err=The system cannot find the file specified. id=70427d7cb1a3472bf167796af1bc6c3e302f4f8bcd776c1cc4020a0d4791b46d params={ node --version  map[NPM_CONFIG_LOGLEVEL:info NODE_VERSION:4.2.1 NODE_SHA256:e460a71ea9aa4d743387a20319042de203de837cb613be0737b6ca368480302d] true [33 98]}
```

Expected Results:

```
PS Z:\-vagrant\resources\dockerfiles-windows\node> docker run --rm -ti node node --version
v4.2.1
```

Additional info:

Everything works fine if I switch back to the first preview release:

```
stop-service docker
wget -uri https://aka.ms/ContainerTools -OutFile C:\windows\system32\docker.exe
start-service docker
```

The output of the original `docker version`:
```
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   4376380
 Built:        Wed Aug 19 14:59:24 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   4376380
 Built:        Wed Aug 19 14:59:24 UTC 2015
 OS/Arch:      windows/amd64
```

I also tested splitting the long RUN command script into single RUN steps:

```
FROM windowsservercore

ENV NPM_CONFIG_LOGLEVEL info
ENV NODE_VERSION 4.2.1
ENV NODE_SHA256 e460a71ea9aa4d743387a20319042de203de837cb613be0737b6ca368480302d

RUN powershell -Command "wget -Uri https://nodejs.org/dist/v%NODE_VERSION%/node-v%NODE_VERSION%-x64.msi -OutFile node.msi -UseBasicParsing;"
RUN powershell -Command "if ((Get-FileHash node.msi -Algorithm sha256).Hash -ne $env:NODE_SHA256) {exit 1};"
RUN msiexec /q /i node.msi
RUN powershell -Command "wget -Uri https://github.com/StefanScherer/win-patch-iojs/releases/download/1.0.9/patchiojs.exe -OutFile patchiojs.exe -UseBasicParsing;"
RUN patchiojs.exe 'C:/Program Files/nodejs/node.exe';

CMD [ "node" ]
```

But then the build fails accessing the just downloaded msi file from one layer to the next layer:

```
PS Z:\-vagrant\resources\dockerfiles-windows\node> docker build -t node --no-cache 4.2
Sending build context to Docker daemon 10.23 MB
Step 1 : FROM windowsservercore
 ---> 0d53944cb84d
Step 2 : ENV NPM_CONFIG_LOGLEVEL info
 ---> Running in b583f92ec818
 ---> 755467fba49d
Removing intermediate container b583f92ec818
Step 3 : ENV NODE_VERSION 4.2.1
 ---> Running in cd20280545a6
 ---> d6664c6390d5
Removing intermediate container cd20280545a6
Step 4 : ENV NODE_SHA256 e460a71ea9aa4d743387a20319042de203de837cb613be0737b6ca368480302d
 ---> Running in 2995cbb6e4d2
 ---> bfcac0adfa36
Removing intermediate container 2995cbb6e4d2
Step 5 : RUN powershell -Command "wget -Uri https://nodejs.org/dist/v%NODE_VERSION%/node-v%NODE_VERSION%-x64.msi -OutFile node.msi -UseBasicParsing;"
 ---> Running in 206af7b7d3fb
wget -Uri https://nodejs.org/dist/v4.2.1/node-v4.2.1-x64.msi -OutFile node.msi -UseBasicParsing;
 ---> e8de0b78898b
Removing intermediate container 206af7b7d3fb
Step 6 : RUN powershell -Command "if ((Get-FileHash node.msi -Algorithm sha256).Hash -ne $env:NODE_SHA256) {exit 1};"
 ---> Running in aafe3105a161
if ((Get-FileHash node.msi -Algorithm sha256).Hash -ne e460a71ea9aa4d743387a20319042de203de837cb613be0737b6ca368480302d) {exit 1};
 ---> dcd6bb267e76
Removing intermediate container aafe3105a161
Step 7 : RUN msiexec /q /i node.msi
 ---> Running in 6382880f9dfe
This installation package could not be opened.  Verify that the package exists and that you can access it, or contact the application vendor to verify that this is a valid Windows Installer package.
The command 'cmd /S /C msiexec /q /i node.msi' returned a non-zero code: 1619
```

### PR DESCRIPTION
**Pull request by darstahl**
This fixes #17509 

Signed-off-by: Darren Stahl darst@microsoft.com

### CODE REVIEW

**Comment by jhowardmsft** [comment]
@thaJeztah Any chance of a TP4 tag. This has regressed behaviour from TP3 reported in #17509

**Comment by thaJeztah** [comment]
IIUC, this affects the API, so added the impact-label (so we don't forget), may need a docs update as well

File: runconfig/config.go [hunk 1]
```diff
@@ -20,6 +20,7 @@ type Config struct {
 	Hostname        string                // Hostname
 	Domainname      string                // Domainname
 	User            string                // User that will run the command(s) inside the container
+	ArgsEscaped     bool                  `json:",omitempty"` // True if command is already escaped
```
Comment (runcom) [inline runconfig/config.go]: Does this really live in Config? Is it needed to be committed to the final image?

Comment (runcom) [inline runconfig/config.go]: This seems also so platform specific

Comment (darrenstahlmsft) [inline runconfig/config.go]: Where is the best place to put it such that it can be sent from dockerfile/dispatchers.go to the execdriver where it needs to be processed? I put it in Config, as that seemed to be the location for similar parameters. And yes, it is platform specific.

Comment (darrenstahlmsft) [inline runconfig/config.go]: On second thought, I think it does need to live in Config, since it is not a runtime configuration, but rather reflecting the state of the Command.

**Comment by darrenstahlmsft** [comment]
Rebased

**Comment by jhowardmsft** [comment]
@runcom - Hey Antonio - which bit of the design are you concerned about? That we're adding something to the persistent state? Unfortunately, I believe we need this persisted there (rather than in hostConfig) as it applies to the command which is stored in there, nothing to do with the host configuration where the container runs. There's no way of breaking the config (or hostconfig) into platform specific parts as these are passed through the API complete. It's only daemon side that the platform daemon can work out what applies and what doesn't. This isn't new though or without precedent - there are certainly linux-specific fields in Config (for example we don't have a TTY; support the recently introduced StopSignal as signals don't exist on Windows; User; or PublishService among probably others). Can you ping me on IRC when you get a chance? I'm concerned if this one gets held up as it breaks some images which need to get built for TP4, plus fixes a TP3 regression, and time is running desperately out now. Thanks! :+1: 

@darrenstahlmsft I do think though you should prepend the comment in the added field `(Windows specific)` though to make it clear.

**Comment by jhowardmsft** [comment]
BTW - @darrenstahlmsft can you add updates to the API docs. I think docs\reference\api\docker_remote_api_v1.22.md is the right place.

**Comment by darrenstahlmsft** [comment]
@jhowardmsft Will do on both accounts (just updated PR before I saw your second comment)

**Comment by darrenstahlmsft** [comment]
Docs updated, plus moved ArgsEscaped to right after Cmd, as it is directly related. Should I add an example (or change an existing one) of when ArgsEscaped is true?

**Comment by jhowardmsft** [comment]
It wouldn't hurt to add a new one :)

File: daemon/execdriver/windows/commandlinebuilder.go [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+
+// createCommandLine creates a command line from the Entrypoint and args
+// of the ProcessConfig. It escapes the arguments if they are not already
+// escaped
+func createCommandLine(processConfig *execdriver.ProcessConfig, escapeArgs bool) (commandLine string, err error) {
+	// While this should get caught earlier, just in case, validate that we
+	// have something to run.
+	if processConfig.Entrypoint == "" {
+		err := errors.New("No entrypoint specified")
+		logrus.Error(err)
```
Comment (LK4D4) [inline daemon/execdriver/windows/commandlinebuilder.go]: I think this will be logged somewhere upper anyway, at least it should

File: daemon/execdriver/windows/commandlinebuilder.go [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+		return "", err
+	}
+
+	// Build the command line of the process
+	commandLine = processConfig.Entrypoint
+	logrus.Debugln("Entrypoint: ", processConfig.Entrypoint)
```
Comment (LK4D4) [inline daemon/execdriver/windows/commandlinebuilder.go]: We using `Debugf` with formatting in such cases. Just for consistency.

File: daemon/execdriver/windows/exec.go [hunk 4]
```diff
@@ -34,21 +33,11 @@ func (d *Driver) Exec(c *execdriver.Command, processConfig *execdriver.ProcessCo
...
 	createProcessParms.Environment = setupEnvironmentVariables(processConfig.Env)
 
-	// While this should get caught earlier, just in case, validate that we
-	// have something to run.
-	if processConfig.Entrypoint == "" {
-		err = errors.New("No entrypoint specified")
-		logrus.Error(err)
-		return -1, err
-	}
+	createProcessParms.CommandLine, err = createCommandLine(&c.ProcessConfig, !c.ArgsEscaped)
```
Comment (LK4D4) [inline daemon/execdriver/windows/exec.go]: Can we not revert argument here, but use `!` inside funtion? I think it's sorta hard to read.

File: daemon/execdriver/windows/commandlinebuilder.go (hunk 2 above)
Comment (LK4D4) [inline daemon/execdriver/windows/commandlinebuilder.go]: Ah, it was there already. But it shouldn't, also such logline will tell nothing to reader.

File: daemon/execdriver/windows/exec.go (hunk 4 above)
Comment (darrenstahlmsft) [inline daemon/execdriver/windows/exec.go]: I also felt that it was hard to read. I think that will make it clearer. Will do.

File: daemon/execdriver/windows/commandlinebuilder.go (hunk 3 above)
Comment (darrenstahlmsft) [inline daemon/execdriver/windows/commandlinebuilder.go]: Will do.

File: daemon/execdriver/windows/commandlinebuilder.go (hunk 2 above)
Comment (darrenstahlmsft) [inline daemon/execdriver/windows/commandlinebuilder.go]: Ok

**Comment by darrenstahlmsft** [comment]
Requested changes made, and docs changed removed (Will resend those in a separate PR)

File: daemon/execdriver/windows/commandlinebuilder.go (hunk 3 above)
Comment (LK4D4) [inline daemon/execdriver/windows/commandlinebuilder.go]: Looks like you forgot this :)

Comment (darrenstahlmsft) [inline daemon/execdriver/windows/commandlinebuilder.go]: Oops

File: daemon/execdriver/windows/commandlinebuilder.go [hunk 5]
```diff
@@ -0,0 +1,37 @@
...
+
+// createCommandLine creates a command line from the Entrypoint and args
+// of the ProcessConfig. It escapes the arguments if they are not already
+// escaped
+func createCommandLine(processConfig *execdriver.ProcessConfig, alreadyEscaped bool) (commandLine string, err error) {
+	// While this should get caught earlier, just in case, validate that we
+	// have something to run.
+	if processConfig.Entrypoint == "" {
+		err := errors.New("No entrypoint specified")
+		return "", err
```
Comment (LK4D4) [inline daemon/execdriver/windows/commandlinebuilder.go]: can be just `return "", errors.New(...)`

**Comment by LK4D4** [comment]
LGTM apart from nit

**Comment by jhowardmsft** [comment]
Ping @runcom

**Comment by darrenstahlmsft** [comment]
Nit fixed

**Comment by runcom** [comment]
LGTM

**Comment by runcom** [comment]
Agreed with @jhowardmsft to have a follow-up PR to address docs (if any are needed) ping @thaJeztah

**Comment by StefanScherer** [comment]
@darrenstahlmsft Thanks! But I have to wait until TP4 as of #17919 :cry:  ;-) But shouldn't take too long I guess.
