### PR TITLE
Atomically save libtrust key file

### LINKED ISSUE #23985: Error starting daemon: Error loading key file /etc/docker/key.json: unable to decode private key JWK: decoding JWK Private Key JSON data: unexpected end of JSON input
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6
 Git commit:   20f81dd
 Built:        Fri May  6 21:33:59 2016
 OS/Arch:      linux/arm

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6
 Git commit:   20f81dd
 Built:        Fri May  6 21:33:59 2016
 OS/Arch:      linux/arm
```

**Steps to reproduce the issue:**
1. Start docker (e.g. let systemd start it for you)
2. Force docker to stop executing during its boot up sequence (e.g. cut power to the device just after systemd starts activating docker.service)
3. An empty key.json file should appear in /etc/docker/

**Describe the results you received:**

 Error starting daemon: Error loading key file /etc/docker/key.json: unable to decode private key JWK: decoding JWK Private Key JSON data: unexpected end of JSON input

### PR DESCRIPTION
**Pull request by dmcgowan**
The libtrust keyfile which is used to set the "ID" property of a daemon must be generated or loaded on every startup. If the process crashes during startup this could cause the file to be incomplete causing future startup errors. Ensure that the file is written atomically to ensure the file is never in an incomplete state.

Fixes #23985

### CODE REVIEW

File: api/common.go [hunk 1]
```diff
@@ -135,11 +139,31 @@ func LoadOrCreateTrustKey(trustKeyPath string) (libtrust.PrivateKey, error) {
...
+			return nil, fmt.Errorf("unable to encode private key JWK: %s", err)
+		}
+	} else {
+		pemBlock, err := key.PEMBlock()
+		if err != nil {
+			return nil, fmt.Errorf("unable to encode private key PEM: %s", err)
+		}
+		encoded = pem.EncodeToMemory(pemBlock)
+	}
+	return
```
Comment (thaJeztah) [inline api/common.go]:
```
return encode, nil
```
?

Comment (dmcgowan) [inline api/common.go]: I am not a fan of named returns but this saves an extra variable declaration before the if block. I don't believe this violates any of our code conventions though.

**Comment by aaronlehmann** [comment]
Would it make sense to fix `libtrust.SaveKey` to do the write atomically?

**Comment by dmcgowan** [comment]
@aaronlehmann considering libtrust is no longer under development and the remaining functionality used by docker should likely be moved into a `pkg`, I would rather not make any changes there.

**Comment by tonistiigi** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM
