### PR TITLE
Restore the SetKey prestart hook.

### LINKED ISSUE #47619: simple run command with --sysctl for network interface fails after upgrade
### Description

after upgrade my Debian from bullseye to bookworm today,  my container failed to work.

i traced it down to this simple command:

> docker run --rm --sysctl net.ipv4.conf.eth0.forwarding=1 alpine 
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: open /proc/sys/net/ipv4/conf/eth0/forwarding: no such file or directory: unknown.

but when the container is started, the _eth0_ conf is right there. maybe network interface renaming timing changed ?
and if i change the interface name to _lo_ or _all,_ the above command works fine.

unfortunately, i have to rely on the interface name: if i use _all_ to set both _forwarding=1_ and _accept_ra=2_, the container seems not respected _accept_ra_ setting. in other words, if i use following commands, the containers won't get its IPv6 address form RA. (_XXX_ is my custom IPv6 enabled MacVLAN network)

> docker run -it --rm --network XXX --sysctl net.ipv6.conf.all.forwarding=1 --sysctl net.ipv6.conf.all.accept_ra=2 ubuntu bash
docker run -it --rm --network XXX --sysctl net.ipv6.conf.all.forwarding=1 --sysctl net.ipv6.conf.all.accept_ra=2 alpine sh

### Reproduce

for _--sysctl_ failure:
1. _docker run --rm --sysctl net.ipv4.conf.eth0.forwarding=1 alpine sh_ will fail

for no IPv6 address from RA (this probably not related to docker, just i can't use _all_ for interface name)
1. create a IPv6 enabled network XXX
2. _docker run -it --rm --network XXX --sysctl net.ipv6.conf.all.forwarding=1 --sysctl net.ipv6.conf.all.accept_ra=2 alpine sh_ will not get IPv6 address from RA

### Expected behavior

_No response_

### docker version

```bash
Client: Docker Engine - Community
 Version:           26.0.0
 API version:       1.45
 Go version:        go1.21.8
 Git commit:        2ae903e
 Built:             Wed Mar 20 15:18:02 2024
 OS/Arch:           linux/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.0.0
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.8
  Git commit:       8b79278
  Built:            Wed Mar 20 15:18:02 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    26.0.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.13.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.25.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 5
  Running: 5
  Paused: 0
  Stopped: 0
 Images: 16
 Server Version: 26.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.21-v8+
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.705GiB
 Name: rpi4
 ID: 60af6eb1-813d-4d13-929e-23993c2a56dc
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by robmry**
**- What I did**

- Fix https://github.com/moby/moby/issues/47619
- Partially reverted https://github.com/moby/moby/commit/0046b16d87105d334b72f5e98efd28bbd94d9659 - daemon: set libnetwork sandbox key w/o OCI hook; https://github.com/moby/moby/pull/47062
- Partially reverted https://github.com/moby/moby/pull/47521/commits/ef5295cda40d3d2babb5ce85ffcf67371c3ecb47 - Don't configure IPv6 addr/gw when IPv6 disabled; https://github.com/moby/moby/pull/47521

Running SetKey to store the OCI Sandbox key after task creation, rather than from the OCI prestart hook, meant it happened after sysctl settings were applied by the runtime - which was the intention, we wanted to complete Sandbox configuration after IPv6 had been disabled by a sysctl if that was going to happen.

But, it meant '--sysctl' options for a specfic network interface caused container task creation to fail, because the interface is only moved into the network namespace during SetKey.

**- How I did it**

Restored the SetKey prestart hook.

Regenerate config files that depend on the container's support for IPv6 after the task has been created.

The changes in the second partially-reverted commit, to check IPv6 support before assigning an interface address/gateway would no longer work, but are no longer necessary.  IPv6 addresses applied during the SetKey prestart hook will be removed when the sysctl disabling IPv6 in the container is applied.

**- How to verify it**

Added a regression test, to make sure it's possible to set an interface-specfic sysctl.

The tests for IPv6 addresses in '/etc/hosts' when IPv6 is disabled still work.

**- Description for the changelog**
```markdown changelog
Fix a regression that meant network interface specific `--sysctl` options prevented container startup.
```

### CODE REVIEW

File: integration/networking/bridge_test.go [hunk 1]
```diff
@@ -675,3 +675,31 @@ func TestDisableIPv6Addrs(t *testing.T) {
 		})
 	}
 }
+
+// Test that it's possible to set a sysctl on an interface in the container.
+// Regression test for https://github.com/moby/moby/issues/47619
+func TestSetInterfaceSysctl(t *testing.T) {
+	skip.If(t, testEnv.DaemonInfo.OSType == "windows", "no sysctl on Windows")
```
Comment (thaJeztah) [inline integration/networking/bridge_test.go:682]: For a follow-up; all tests in this file (`bridge_test.go`) are Linux-only; if this file is specific for the `bridge` driver (which is not supported on Windows), perhaps we should consider renaming the file to `bridge_linux_test.go`, or adding a `//go:build linux` build-tag to it.

File: daemon/start_linux.go [hunk 2]
```diff
@@ -1,30 +1,23 @@
...
-	"github.com/docker/docker/libcontainerd/types"
 	"github.com/docker/docker/oci"
+	specs "github.com/opencontainers/runtime-spec/specs-go"
 )
 
 // initializeCreatedTask performs any initialization that needs to be done to
-// prepare a freshly-created task to be started.
-func (daemon *Daemon) initializeCreatedTask(ctx context.Context, tsk types.Task, container *container.Container, spec *specs.Spec) error {
+// prepare a freshly-created container to be started.
+func (daemon *Daemon) initializeCreatedContainer(container *container.Container, spec *specs.Spec) error {
```
Comment (thaJeztah) [inline daemon/start_linux.go:12]: Wondering if we should keep the `context.Context` (assuming we may need it again at some point), although I guess we could add it back when that moment arrives.

File: integration/networking/bridge_test.go (hunk 1 above)
Comment (robmry) [reply integration/networking/bridge_test.go:682]: It's got `TestBridgeICCWindows` - which uses "nat" instead of "bridge", I think I put it there because it covers some of the same ground as `TestBridgeICC` ... but yes, we could split the file in to windows/not-windows.

File: daemon/start_linux.go (hunk 2 above)
Comment (robmry) [reply daemon/start_linux.go:12]: I'm happy to put it back ... but yes, my thinking was that as it's a non-exported function it can always be added back when needed.

**Comment by akerouanton** [comment]
I don't think #47619 alone fully outweighs the benefits of https://github.com/moby/moby/commit/0046b16d87105d334b72f5e98efd28bbd94d9659. We should probably find a way to filter out interface-specific sysctls from the OCI spec and apply them after all the endpoints are created / joined. But I think that'd be an important change for a patch release, so it's probably better to do that for the next major release.

**Review by corhere — DISMISSED** [review]
Blocking until I have confirmed to my satisfaction that there is _no_ alternative whatsoever to reverting to the use of OCI hooks.

**Comment by corhere** [comment]
runC executes prestart hooks before it applies sysctls, and both are performed as part of the `create` command. There are two possible paths forward: revert, or roll forward with a solution that fixes the regression while also retaining support for handling containers with IPv6 disabled by `--sysctl`. I'm not exactly sure how we can do that (or if we need to implement some other affordance to support users specifying sysctls per iface) so reverting for now and trying again for v27 is looking to be the best solution.

File: daemon/start_linux.go (hunk 2 above)
Comment (corhere) [reply daemon/start_linux.go:12]: I'd like to keep the function name and signature unchanged as it makes for less code to review in both this PR and in the future PR which carries the next version of the network config code. (It's just noise to have to touch start_notlinux.go)

**Review by corhere — APPROVED** [review]

File: daemon/start_linux.go (hunk 2 above)
Comment (thaJeztah) [reply daemon/start_linux.go:12]: @corhere you mean keeping the signature as it was before this PR? (so adjust the patch to not change the signature?)

**Review by akerouanton — APPROVED** [review]
LGTM

**Comment by robmry** [comment]
> I'd like to keep the function name and signature unchanged as it makes for less code to review in both this PR and in the future PR which carries the next version of the network config code. (It's just noise to have to touch start_notlinux.go)

So - add back code that isn't needed, but might be in future if a change that isn't planned ends up looking like we think it might, to make the already-reviewed code easier to review, but needing another review. Sure, why not!
