### PR TITLE
Ensure health probe is stopped when a container exits

### LINKED ISSUE #30107: 1.13.0-rc5 healthcheck on non existant containers goes awry
A few minutes after we launch our containers, and for too long afterwards, we see ongoing health check on non existent containers...
Maybe the 1 or 2 we use at the beginning to setup things, but that exit after, leave their mark somewhere and aren't cleared in the health check container list.

The result is that the `No such exec instance` warning quickly (sometimes < 1h) turn into `context deadline exceeded` errors and the daemon reports everyone as unhealthy. 
Furthermore, the daemon sometimes stops responding swiftly. 
Even stranger, the docker info line of the `containerd version:` now says `N/A` as seen below while it was fine on the daemon's initial start.

**Steps to reproduce the issue:**
Hard to say, it seems we use a container whose health check stay active after their gone, causing a build up that ends up causing more trouble for the docker daemon. 

**Describe the results you received:**
```
Jan 11 10:25:46 server0 dockerd[903]: time="2017-01-11T10:25:46.412211080-05:00" level=warning msg="Health check for container 075bf45cf93dd571bcad58bdabf0ff110a3858a7adc7e723f086b52d3bad5265 error: No such exec instance 'db55507a76e5a807224bc3ee3a13a51560d1c06842b42974cb88096327e0c536' found in daemon"
Jan 11 10:26:13 server0 dockerd[903]: time="2017-01-11T10:26:13.266877963-05:00" level=warning msg="Health check for container 2fc1a5a860dba35a0a3a67d4ad65fd0ad332e2d0c6867a1cb44d915d0e6d1538 error: No such exec instance '737e5577996f393824ac2bb26609f44432f34ea7dd3bec14552d5442d6a08011' found in daemon"
Jan 11 10:26:16 server0 dockerd[903]: time="2017-01-11T10:26:16.413149842-05:00" level=warning msg="Health check for container 075bf45cf93dd571bcad58bdabf0ff110a3858a7adc7e723f086b52d3bad5265 error: No such exec instance 'd72b00fdaf51984253fb9c988974754218917a8a687627cd462c586df2f75448' found in daemon"
Jan 11 10:26:43 server0 dockerd[903]: time="2017-01-11T10:26:43.267936886-05:00" level=warning msg="Health check for container 2fc1a5a860dba35a0a3a67d4ad65fd0ad332e2d0c6867a1cb44d915d0e6d1538 error: No such exec instance '4ffe31051cce8b1aa0f60b1f7456e3469d734058a5ac2e050bd2663737992812' found in daemon"
Jan 11 10:26:46 server0 dockerd[903]: time="2017-01-11T10:26:46.413808033-05:00" level=warning msg="Health check for container 075bf45cf93dd571bcad58bdabf0ff110a3858a7adc7e723f086b52d3bad5265 error: No such exec instance '9a481c36d86c4015e851943a0414d54f027860801ca9ec2f773f916fc6d09c15' found in daemon"
Jan 11 10:27:13 server0 dockerd[903]: time="2017-01-11T10:27:13.268959487-05:00" level=warning msg="Health check for container 2fc1a5a860dba35a0a3a67d4ad65fd0ad332e2d0c6867a1cb44d915d0e6d1538 error: No such exec instance 'f0f6246f9eda5d7f38f9a8b9cfdbf75c89d10580eecae869064fa738779329fc' found in daemon"
Jan 11 10:27:16 server0 dockerd[903]: time="2017-01-11T10:27:16.414144730-05:00" level=warning msg="Health check for container 075bf45cf93dd571bcad58bdabf0ff110a3858a7adc7e723f086b52d3bad5265 error: No such exec instance 'cc777112330b7607cb0f9776902d8047a7ab5e81c81aa676138f3446eaec085a' found in daemon"
Jan 11 10:27:28 server0 dockerd[903]: time="2017-01-11T10:27:28.022418771-05:00" level=warning msg="Health check for container 1807479428c59e08be1c056269462a526ab367d71bcc1860c0b541cbf024a819 error: rpc error: code = 4 desc = context deadline exceeded"
Jan 11 10:27:28 server0 dockerd[903]: time="2017-01-11T10:27:28.770459007-05:00" level=warning msg="Health check for container 515b205d5d47a165845c9a2c5236bf0910a872f6ae1dbf19cf5fb69623ab4f09 error: rpc error: code = 4 desc = context deadline exceeded"
Jan 11 10:27:30 server0 dockerd[903]: time="2017-01-11T10:27:30.088651675-05:00" level=warning msg="Health check for container 1b80639a25d75e73310fe45c1dbc604846ac5085773c4441635d3c48d59b0077 error: rpc error: code = 4 desc = context deadline exceeded"
Jan 11 10:27:33 server0 dockerd[903]: time="2017-01-11T10:27:33.507450992-05:00" level=warning msg="Health check for container 8090bd7c56c46d545001af00b4edb516ea4b000f5f097c283329189982623729 error: rpc error: code = 4 desc = context deadline exceeded"
Jan 11 10:27:34 server0 dockerd[903]: time="2017-01-11T10:27:34.463844739-05:00" level=warning msg="Health check for container c87549ceadc9f40b474f1c2b24d5c1468f6d07534519d94b40a44b92b3b44112 error: rpc error: code = 4 desc = context deadline exceeded"
Jan 11 10:27:35 server0 dockerd[903]: time="2017-01-11T10:27:35.081994789-05:00" level=warning msg="Health check for container 7b78b1c413d5bf767abb4f2e650458431fe1e3e789d71838f32028254393f567 error: rpc error: code = 4 desc = context deadline exceeded"
Jan 11 10:27:35 server0 dockerd[903]: time="2017-01-11T10:27:35.207010460-05:00" level=warning msg="Health check for container c9cdadde8fdf9c0c584f88f3f8075c4b127aa1ec3e5e3447902c80a27f056b0e error: rpc error: code = 4 desc = context deadline exceeded"
Jan 11 10:27:36 server0 dockerd[903]: time="2017-01-11T10:27:36.048869073-05:00" level=error msg="libcontainerd: failed to receive event from containerd: rpc error: code = 13 desc = transport is closing"
Jan 11 10:27:36 server0 dockerd[903]: time="2017-01-11T10:27:36.056835736-05:00" level=info msg="libcontainerd: new containerd process, pid: 31072"
Jan 11 10:27:36 server0 dockerd[903]: time="2017-01-11T10:27:36.088448897-05:00" level=warning msg="Health check for container 16c786570ae6fc698d5af7e6b388a61b075f68d5fb232610429fc2904f439b19 error: rpc error: code = 13 desc = transport is closing"
Jan 11 10:27:36 server0 dockerd[903]: time="2017-01-11T10:27:36.175748731-05:00" level=fatal msg="open /var/run/docker/libcontainerd/containerd/1807479428c59e08be1c056269462a526ab367d71bcc1860c0b541cbf024a819/70fb10743a22cb7b0bee1e30294d1d58193d8170a3f5ee3d6c20a78050cef65f/process.json: no such file or directory"
Jan 11 10:27:36 server0 dockerd[903]: time="2017-01-11T10:27:36.871861345-05:00" level=info msg="libcontainerd: new containerd process, pid: 31081"
Jan 11 10:27:36 server0 dockerd[903]: time="2017-01-11T10:27:36.924295488-05:00" level=fatal msg="open /var/run/docker/libcontainerd/containerd/1807479428c59e08be1c056269462a526ab367d71bcc1860c0b541cbf024a819/70fb10743a22cb7b0bee1e30294d1d58193d8170a3f5ee3d6c20a78050cef65f/process.json: no such file or directory"
Jan 11 10:27:37 server0 dockerd[903]: time="2017-01-11T10:27:37.868735810-05:00" level=warning msg="Health check for container 4191eb499571da26c3493f94598d3f2a5c6565171d0dbb6c7be2fed985103b1c error: rpc error: code = 14 desc = grpc: the connection is unavailable"
Jan 11 10:27:38 server0 dockerd[903]: time="2017-01-11T10:27:38.373862486-05:00" level=info msg="libcontainerd: new containerd process, pid: 31090"
Jan 11 10:27:38 server0 dockerd[903]: time="2017-01-11T10:27:38.398648957-05:00" level=fatal msg="open /var/run/docker/libcontainerd/containerd/1807479428c59e08be1c056269462a526ab367d71bcc1860c0b541cbf024a819/70fb10743a22cb7b0bee1e30294d1d58193d8170a3f5ee3d6c20a78050cef65f/process.json: no such file or directory"
Jan 11 10:27:39 server0 dockerd[903]: time="2017-01-11T10:27:39.872293729-05:00" level=info msg="libcontainerd: new containerd process, pid: 31098"
Jan 11 10:27:39 server0 dockerd[903]: time="2017-01-11T10:27:39.89301445-05:00" level=fatal msg="open /var/run/docker/libcontainerd/containerd/1807479428c59e08be1c056269462a526ab367d71bcc1860c0b541cbf024a819/70fb10743a22cb7b0bee1e30294d1d58193d8170a3f5ee3d6c20a78050cef65f/process.json: no such file or directory"
Jan 11 10:27:41 server0 dockerd[903]: time="2017-01-11T10:27:41.373768302-05:00" level=info msg="libcontainerd: new containerd process, pid: 31106"
Jan 11 10:27:41 server0 dockerd[903]: time="2017-01-11T10:27:41.423101794-05:00" level=fatal msg="open /var/run/docker/libcontainerd/containerd/1807479428c59e08be1c056269462a526ab367d71bcc1860c0b541cbf024a819/70fb10743a22cb7b0bee1e30294d1d58193d8170a3f5ee3d6c20a78050cef65f/process.json: no such file or directory"
Jan 11 10:27:42 server0 dockerd[903]: time="2017-01-11T10:27:42.874085871-05:00" level=info msg="libcontainerd: new containerd process, pid: 31115"
Jan 11 10:27:42 server0 dockerd[903]: time="2017-01-11T10:27:42.895149032-05:00" level=fatal msg="open /var/run/docker/libcontainerd/containerd/1807479428c59e08be1c056269462a526ab367d71bcc1860c0b541cbf024a819/70fb10743a22cb7b0bee1e30294d1d58193d8170a3f5ee3d6c20a78050cef65f/process.json: no such file or directory"
Jan 11 10:27:43 server0 dockerd[903]: time="2017-01-11T10:27:43.269496559-05:00" level=warning msg="Health check for container 2fc1a5a860dba35a0a3a67d4ad65fd0ad332e2d0c6867a1cb44d915d0e6d1538 error: No such exec instance '25de0f4c8f8a4e0e6dfb9ca5ba86a9204cb512d3f894e23c98de11c52b2c5059' found in daemon"
Jan 11 10:27:44 server0 dockerd[903]: time="2017-01-11T10:27:44.371805952-05:00" level=info msg="libcontainerd: new containerd process, pid: 31123"
Jan 11 10:27:44 server0 dockerd[903]: time="2017-01-11T10:27:44.391271529-05:00" level=fatal msg="open /var/run/docker/libcontainerd/containerd/1807479428c59e08be1c056269462a526ab367d71bcc1860c0b541cbf024a819/70fb10743a22cb7b0bee1e30294d1d58193d8170a3f5ee3d6c20a78050cef65f/process.json: no such file or directory"
Jan 11 10:27:45 server0 dockerd[903]: time="2017-01-11T10:27:45.873800793-05:00" level=info msg="libcontainerd: new containerd process, pid: 31130"
Jan 11 10:27:45 server0 dockerd[903]: time="2017-01-11T10:27:45.898087536-05:00" level=fatal msg="open /var/run/docker/libcontainerd/containerd/1807479428c59e08be1c056269462a526ab367d71bcc1860c0b541cbf024a819/70fb10743a22cb7b0bee1e30294d1d58193d8170a3f5ee3d6c20a78050cef65f/process.json: no such file or directory"
Jan 11 10:27:46 server0 dockerd[903]: time="2017-01-11T10:27:46.415003192-05:00" level=warning msg="Health check for container 075bf45cf93dd571bcad58bdabf0ff110a3858a7adc7e723f086b52d3bad5265 error: No such exec instance 'bcacfba2bd99da04082e8ecfcfbad4301e14722a46a25d5c1d98e2f37fa09b20' found in daemon"
Jan 11 10:27:47 server0 dockerd[903]: time="2017-01-11T10:27:47.372911944-05:00" level=info msg="libcontainerd: new containerd process, pid: 31140"
Jan 11 10:27:47 server0 dockerd[903]: time="2017-01-11T10:27:47.391975517-05:00" level=fatal msg="open /var/run/docker/libcontainerd/containerd/1807479428c59e08be1c056269462a526ab367d71bcc1860c0b541cbf024a819/70fb10743a22cb7b0bee1e30294d1d58193d8170a3f5ee3d6c20a78050cef65f/process.json: no such file or directory"
Jan 11 10:27:48 server0 dockerd[903]: time="2017-01-11T10:27:48.004981172-05:00" level=warning msg="Health check for container c1a153c01eb7b7667498af5024a042464dc30d7d5f5fb04c538ee8864b99c257 error: rpc error: code = 14 desc = grpc: the connection is unavailable"
Jan 11 10:27:48 server0 dockerd[903]: time="2017-01-11T10:27:48.873267403-05:00" level=info msg="libcontainerd: new containerd process, pid: 31149"
Jan 11 10:27:48 server0 dockerd[903]: time="2017-01-11T10:27:48.894804885-05:00" level=fatal msg="open /var/run/docker/libcontainerd/containerd/1807479428c59e08be1c056269462a526ab367d71bcc1860c0b541cbf024a819/70fb10743a22cb7b0bee1e30294d1d58193d8170a3f5ee3d6c20a78050cef65f/process.json: no such file or directory"
Jan 11 10:27:50 server0 dockerd[903]: time="2017-01-11T10:27:50.371847643-05:00" level=info msg="libcontainerd: new containerd process, pid: 31157"
Jan 11 10:27:50 server0 dockerd[903]: time="2017-01-11T10:27:50.391874139-05:00" level=fatal msg="open /var/run/docker/libcontainerd/containerd/1807479428c59e08be1c056269462a526ab367d71bcc1860c0b541cbf024a819/70fb10743a22cb7b0bee1e30294d1d58193d8170a3f5ee3d6c20a78050cef65f/process.json: no such file or directory"
Jan 11 10:27:50 server0 dockerd[903]: time="2017-01-11T10:27:50.472630292-05:00" level=warning msg="Health check for container d1b297c55f4a0757dff8f4308f14b26640d7867c10ceca1191df99984480e702 error: rpc error: code = 14 desc = grpc: the connection is unavailable"
Jan 11 10:27:51 server0 dockerd[903]: time="2017-01-11T10:27:51.872738602-05:00" level=info msg="libcontainerd: new containerd process, pid: 31165"
Jan 11 10:27:51 server0 dockerd[903]: time="2017-01-11T10:27:51.895508321-05:00" level=fatal msg="open /var/run/docker/libcontainerd/containerd/1807479428c59e08be1c056269462a526ab367d71bcc1860c0b541cbf024a819/70fb10743a22cb7b0bee1e30294d1d58193d8170a3f5ee3d6c20a78050cef65f/process.json: no such file or directory"
Jan 11 10:27:52 server0 dockerd[903]: time="2017-01-11T10:27:52.376425977-05:00" level=warning msg="Health check for container 165693603abb52553ea1055d18f68d57b7fc1bd54f1ae10b03de64574baf883f error: rpc error: code = 14 desc = grpc: the connection is unavailable"
Jan 11 10:27:53 server0 dockerd[903]: time="2017-01-11T10:27:53.375101821-05:00" level=info msg="libcontainerd: new containerd process, pid: 31171"
Jan 11 10:27:53 server0 dockerd[903]: time="2017-01-11T10:27:53.400707355-05:00" level=fatal msg="open /var/run/docker/libcontainerd/containerd/1807479428c59e08be1
```

**Describe the results you expected:**
- Healthcheck logs should stop quite fast for containers that don't exist at all (`docker ps -a` not showing these hashes).
- Healthcheck status should stay healthy for other containers.
- docker commands should keep working

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc5
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   43cc971
 Built:        Thu Jan  5 00:55:26 2017
 OS/Arch:      linux/amd64
Server:
 Version:      1.13.0-rc5
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   43cc971
 Built:        Thu Jan  5 00:55:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

The interesting thing is that the `containerd version` line, after a while, becomes N/A...

```
Containers: 28
 Running: 28
 Paused: 0
 Stopped: 0
Images: 43
Server Version: 1.13.0-rc5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 389
 Dirperm1 Supported: true
Logging Driver: syslog
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: N/A (expected: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e)
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-59-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 22.99 GiB
Name: warden
ID: MRFE:3XHR:QEKV:QMJF:RV3O:Z63T:DAEC:QB4G:H72B:4CNA:E5G4:Z4HR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
It runs on a Proxmox VM.

Not sure if it relates to these other issues:
https://github.com/docker/docker/issues/29854 
https://github.com/docker/docker/issues/29369

### PR DESCRIPTION
**Pull request by mlaventure**
Signed-off-by: Kenfe-Mickael Laventure <mickael.laventure@gmail.com>

-- 

**- What I did**

Fixes #30107 by preventing an health check to keep on running after a container has been removed

**- How I did it**

By **always** stopping health checks on container exits. Health checks are always started if present on container start (see [`daemon.StateChanged()`](https://github.com/docker/docker/blob/9518a71ceff0f1aa9abada5b51cbac40f8e8c80e/daemon/monitor.go#L114)), so there's no fear of missing any and it avoid unneeded exec while the container is still down.

**- How to verify it**

Given it's a race, it has to be manually testing unfortunately. Instructions provided by @esbite were used (https://gist.github.com/esbite/d0c639e72435b4721d44445b0972dff8)

**- Description for the changelog**

Ensure health probe is stopped when a container exits

**- A picture of a cute animal (not mandatory but encouraged)**

Not Today :scream_cat:

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM 🦁

File: daemon/delete.go [hunk 1]
```diff
@@ -141,6 +141,15 @@ func (daemon *Daemon) cleanupContainer(container *container.Container, forceRemo
...
 	}
 
+	// Ensure the health probe is stopped.
+	//
+	// If the contianer is continuously unhealthy, it may not
+	// happen automatically as the container would have exited
+	// before a call to `rm <-f>` which would not have lead to
+	// stop of the health monitor since the container was
+	// still marked as running
+	daemon.updateHealthMonitor(container)
```
Comment (cpuguy83) [inline daemon/delete.go]: This needs to be called with a lock.

Comment (cpuguy83) [inline daemon/delete.go]: Also should be called after `containerStop()`?

**Review by cpuguy83 — CHANGES_REQUESTED** [review]

File: daemon/delete.go (hunk 1 above)
Comment (mlaventure) [inline daemon/delete.go]: Just realized that `containerStop()` already stop the health check.

Going to go through the flow again, there's definitely a race there, but I'm thinking it's more in the `StateChanged()` daemon callback now.

**Comment by mlaventure** [comment]
@vdemeester @cpuguy83 changed the fixed (and updated the PR description) PTAL

**Review by tonistiigi — APPROVED** [review]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by vdemeester** [comment]
powerpc failure known flaky, let's merge this 👼
