### PR TITLE
registry: allow fallback on unknown errors

### LINKED ISSUE #15130: [1.8.0-rc1] v1 registry mirror - error pulling images
Description of problem:
When running docker engine 1.8.0-rc1, I am seeing failures to pull from a v1 registry mirror.  I am also seeing the same with the experimental `1.8.0~dev~git20150725.210247.0.a2ea8f2-0~stretch` build.  It seems that the fallback to checking for v1 is not working.  I am not sure if this is intended or not.

`docker version`:

```
$ docker version
Client:
 Version:      1.8.0-rc1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   4f1c66a
 Built:        Sat Jul 25 05:32:36 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.0-rc1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   4f1c66a
 Built:        Sat Jul 25 05:32:36 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:

```
$ docker info
Containers: 0
Images: 315
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 315
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux stretch/sid
CPUs: 2
Total Memory: 1.963 GiB
Name: localdev
ID: ABO2:4REM:BS7R:OXYG:R7V6:UJGL:2YTX:CJ7H:UEYY:IK7O:JXYQ:YBYX
Username: mbentley
Registry: https://index.docker.io/v1/
```

`uname -a`:

```
$ uname -a
Linux localdev 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.):
VirtualBox 5.0.0
Debian Sid
Using the standard mirror configured as documented [here](https://docs.docker.com/articles/registry_mirror/)

How reproducible:
Every time

Steps to Reproduce:
1. Setup v1 mirror
2. Configure daemon to use v1 registry mirror
3. Attempt to pull an image from Docker Hub

Actual Results:

From docker client:
```
$ docker pull nginx
Using default tag: latest
Error response from daemon: Error parsing HTTP response: invalid character '<' looking for beginning of value: "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n<title>404 Not Found</title>\n<h1>Not Found</h1>\n<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>\n"
```

From registry mirror:
```
192.168.1.148 - - [29/Jul/2015:18:19:43 +0000] "GET /v2/ HTTP/1.1" 404 233 "-" "docker/1.8.0-rc1 go/go1.4.2 git-commit/4f1c66a kernel/3.16.0-4-amd64 os/linux arch/amd64"
192.168.1.148 - - [29/Jul/2015:18:19:43 +0000] "GET /v2/library/nginx/manifests/latest HTTP/1.1" 404 233 "-" "docker/1.8.0-rc1 go/go1.4.2 git-commit/4f1c66a kernel/3.16.0-4-amd64 os/linux arch/amd64"
```

Expected Results:
From docker client:
```
$ docker pull nginx
Pulling repository nginx
6886fb5a9b8d: Download complete
902b87aaaec9: Download complete
9a61b6b1315e: Download complete
aface2a79f55: Download complete
5dd2638d10a1: Download complete
97df1ddba09e: Download complete
56c99fa886e8: Download complete
cd27805ea89f: Download complete
5e95ac0e9a79: Download complete
9f36f81a1ccb: Download complete
4c1809b04591: Download complete
98c9ccd75644: Download complete
Status: Image is up to date for nginx:latest
```

From registry mirror:
```
29/Jul/2015:18:22:20 +0000 INFO: Starting new HTTPS connection (1): index.docker.io
192.168.1.148 - - [29/Jul/2015:18:22:20 +0000] "GET /v1/images/6886fb5a9b8d73b12d842bab8f9a6941c36094c2974abddb685d54c9d99e37da/ancestry HTTP/1.1" 200 816 "-" "docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.16.0-4-amd64 os/linux arch/amd64"
```

Additional info:

### PR DESCRIPTION
**Pull request by tiborvass**
This patch fixes a bug where a user specifies a v1 mirror for
`--registry-mirror` and pull an image from the Hub.

It used to not fallback because of an unexpected error returned when
trying to JSON marshal nginx output.

We now ensure that any unexpected error falls back to the next endpoint
in the list.

Signed-off-by: Tibor Vass tibor@docker.com

Fixes #15130 
**Important Note**: v2 still has precedence over v1 mirrors, so specifying a v1 mirror to talk to a v2 endpoint will NOT work unless something blocks the v2 endpoint. Please use a v2 mirror in that case.

### CODE REVIEW

**Comment by dmcgowan** [comment]
LGTM

**Comment by calavera** [comment]
LGTM, waiting for jenkins to go :green_heart:

**Comment by calavera** [comment]
cherry-picked into #15091

File: registry/registry.go [hunk 1]
```diff
@@ -211,8 +212,14 @@ func ContinueOnError(err error) bool {
...
 		return shouldV2Fallback(v)
+	case *client.UnexpectedHTTPResponseError:
+		return true
 	}
-	return false
+	// let's be nice and fallback if the error is a completely
+	// unexpected one.
+	// If new errors have to be handled in some way, please
+	// add them to the switch above.
+	return true
```
Comment (stevvooe) [inline registry/registry.go]: This seems dangerous. We've hand a huge number of reports where falling back to v1 mid flow results in some odd behavior.

Comment (tiborvass) [inline registry/registry.go]: @dmcgowan @stevvooe show them to me and we can add those cases in the switch.

Comment (stevvooe) [inline registry/registry.go]: github.com/docker/distribution/issues :smiley_cat: 

In all seriousness, fallback should only happen at the start. Once the process has begun, we should not fallback midway. We've ended up with some odd v1/v2 crossover images in those cases.

This might be one of those, just wait longer and v1 will be gone, so this doesn't matter.
