### PR TITLE
Vendor libnetwork v0.6.0-rc4 & corresponding changes in engine for port-map sandobx handling.

### LINKED ISSUE #18222: docker 1.9.1 initial container exposed port  is not exposed after several container restarts
$ sudo docker info
Containers: 11
Images: 590
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.3.0-040300-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 8
Total Memory: 15.16 GiB
Name: sebi
ID: G3MJ:2URQ:P7DQ:5Z4W:GAW4:RYKP:U23J:NPER:IFEQ:XLFB:QX77:H3VA
Username: sebihgdata
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Cluster store: consul://localhost:8500
Cluster advertise: 192.168.77.233:2375

$ sudo docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Steps to reproduce:
  I have an apache httpd container that is connected to 2 overlay networks and exposes the 443 port... after several container restarts the port will fail to be exposed. 
  I created a typescript gist at https://gist.github.com/sebi-hgdata/adcfe6585911df94b33c (see last iptables --list command)

### LINKED ISSUE #19677: [1.10-rc1]  getting ` cannot create network docker_gwbridge` when concurentry starting containers
I'm getting the above error when concurrently starting containers on  'cleaned up' docker, but I also seen it when rebooting a machine that has containers with restart policies. Here is my script for reproducing it (has some custom consul and docker paths):
```
#!/bin/bash
sudo docker rm -f $(sudo docker ps -a -q)

sudo service docker stop

sudo umount /var/run/docker/netns/*
sudo rm /var/run/docker/netns/*
sudo rm -rf /var/lib/docker/network
sudo service consul-server stop
sudo rm -rf ~/hgdata/deployments/docker/network
# cleanu consul data
sudo rm -rf ~/hgdata/deployments/consul/data/*
sudo service docker start
sudo service consul-server start

sudo docker network create -d overlay o1
sudo docker run -td --restart=unless-stopped  --net=o1 ubuntu:14.04.2 &
sudo docker run -td --restart=unless-stopped  --net=o1 ubuntu:14.04.2 &
sudo docker run -td --restart=unless-stopped  --net=o1 ubuntu:14.04.2 &
sudo docker run -td --restart=unless-stopped  --net=o1 ubuntu:14.04.2 &
```
```
$ sudo docker version
Client:
 Version:      1.10.0-rc1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   677c593
 Built:        Fri Jan 15 18:17:17 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0-rc1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   677c593
 Built:        Fri Jan 15 18:17:17 2016
 OS/Arch:      linux/amd64

$ sudo docker info
Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 290
Server Version: 1.10.0-rc1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host overlay
Kernel Version: 4.3.0-040300-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.706 GiB
Name: seb
ID: B2M7:KYAT:FVQA:TA6R:FLAN:DUF5:224N:JFD3:E4UF:KL2Y:FHDM:FPCI
Username: sebihgdata
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Cluster store: consul://localhost:8500
Cluster advertise: 192.168.0.106:2375
```

### PR DESCRIPTION
**Pull request by mavenugo**
- Vendor libnetwork v0.6.0-rc4
- Fixes #18222 
- Fixes #19677

### CODE REVIEW

**Comment by mavenugo** [comment]
ping @tiborvass @thaJeztah

**Comment by tiborvass** [comment]
@mavenugo 2 tests are failing

**Comment by mavenugo** [comment]
@tiborvass fixed. PTAL.

**Comment by tiborvass** [comment]
LGTM

File: container/container_unix.go [hunk 1]
```diff
@@ -148,30 +156,45 @@ func (container *Container) buildPortMapInfo(ep libnetwork.Endpoint) error {
...
+func getSandboxPortMapInfo(sb libnetwork.Sandbox) nat.PortMap {
+	pm := nat.PortMap{}
+	if sb == nil {
+		return pm
+	}
+
+	for _, ep := range sb.Endpoints() {
+		pm, _ = getEndpointPortMapInfo(ep)
+		if len(pm) > 0 {
+			break
```
Comment (thaJeztah) [inline container/container_unix.go]: I was slightly confused why the break was here; Looking at where this function is used, it looks like we're only interested *if* ports are mapped on *an* endpoint? should this function be named something like `hasMappedPorts` ? (Perhaps I'm misunderstanding)

Comment (mavenugo) [inline container/container_unix.go]: please refer to the commit message : https://github.com/mavenugo/docker/commit/e38463b2779f455b4173171d5a1fdb115180a7e9 . Due to historical reasons, we used endpoint data-model to carry the port-mapping information. But, things have changed from the days we started with `endpoint` = `service` & hence the port-mapping belongs to the sandbox. We need this PR as a way to use endpoint data-model to get the port-mapping info for Sandbox (as the function name `getSandboxPortMapInfo` suggest). We are infact returning the port-map table and hence it is called `get` and not `has`. Hope it explains.

**Comment by icecrime** [comment]
LGTM

File: container/container_unix.go (hunk 1 above)
Comment (thaJeztah) [inline container/container_unix.go]: Yes, I saw it currently returned the port-map table, but it was only used *once*, and only to check *if* there's a port-map; https://github.com/docker/docker/blob/269a6d7d3656fe7edf7cb630125ee4664dd24c78/container/container_unix.go#L337-L338

Hence my thinking :smile:

Comment (mavenugo) [inline container/container_unix.go]: okay. yes. it is not ideal. docker/libnetwork#810 is the better fix for this problem.
We are just trying to mimic the port-mapping on Sandbox using this logic in 1.10 (since only 1 endpoint will anyways carry the port-map information). 
We can address it properly in 1.11 via docker/libnetwork#810.

Comment (thaJeztah) [inline container/container_unix.go]: Ah, makes sense, thx
