### PR TITLE
Fix the driver name empty case

### LINKED ISSUE #20900: debug logs not have volume driver name printed
Output of `docker version`:

```
1.11 master
```

Output of `docker info`:

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 3
Server Version: 1.11.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 8
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.19.0-30-generic
Operating System: Ubuntu 14.04.3 LTS (containerized)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.797 GiB
Name: 1c9affa56351
ID: YW7G:7EDY:T3ZV:EXB6:C2GP:4NGS:55UH:J6SO:QCYL:YRR2:JCEF:R37J
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 10
 Goroutines: 17
 System Time: 2016-03-03T07:26:00.525213197Z
 EventsListeners: 0
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):

List the steps to reproduce the issue:
1. start docker with debug level enabled
2. docker run -v /test busybox
3. The debug logs would have following:
Registering new volume reference: driver "", name "1c026283ac0922472980df372edaac03a4336cc8884862337de6040c42897604"

Describe the results you received:
Registering new volume reference: driver "", name "1c026283ac0922472980df372edaac03a4336cc8884862337de6040c42897604"

Describe the results you expected:
driver would have value, like "local"

Provide additional info you think is important:

### PR DESCRIPTION
**Pull request by HackToday**
As drivername maybe "" in hostconfig, so we should not
directly print dirvername with var drivername,
instead, we use the real driver name property to print it.

Fixes: #20900
Signed-off-by: Kai Qiang Wu(Kennan) wkqwu@cn.ibm.com

### CODE REVIEW

File: volume/store/store.go [hunk 1]
```diff
@@ -194,8 +194,9 @@ func (s *VolumeStore) create(name, driverName string, opts map[string]string) (v
 		}
 	}
 
-	logrus.Debugf("Registering new volume reference: driver %q, name %q", driverName, name)
 	vd, err := volumedrivers.GetDriver(driverName)
+	logrus.Debugf("Registering new volume reference: driver %q, name %q", vd.Name(), name)
```
Comment (vdemeester) [inline volume/store/store.go]: This logs probably need to be after the error check though :wink:

**Comment by HackToday** [comment]
ping @vdemeester  PTAL.

File: volume/store/store.go [hunk 2]
```diff
@@ -194,12 +194,14 @@ func (s *VolumeStore) create(name, driverName string, opts map[string]string) (v
 		}
 	}
 
-	logrus.Debugf("Registering new volume reference: driver %q, name %q", driverName, name)
```
Comment (thaJeztah) [inline volume/store/store.go]: I like that the log-message is better, but perhaps we still want to have a log message *before* volumedrivers.GetDriver() to see where something went wrong? idk

Comment (thaJeztah) [inline volume/store/store.go]: I.e., the original message wasn't *wrong*, because it showed what name was *specified*

perhaps @vdemeester has thoughts on that; i.e. Is it valuable to have a log message for this?

Comment (vdemeester) [inline volume/store/store.go]: Hum, it doesn't hurt to have the log before too, right :smile_cat: (and it's `Debug` logs so…). I'm fine with keeping it (maybe without the `driverName` if empty), Idk :sweat_smile:.

Comment (HackToday) [inline volume/store/store.go]: I did not think log drivername = "" is good, as whether or not, you would use local driver name for that, in that case,

why not tell we are using drivername is "local".

If we like to keep "" old log message,(which I think it is misleading)

Comment (thaJeztah) [inline volume/store/store.go]: Well, my thought was that we're *requesting* a driver called `""`, which resulted in loading the `local` driver; I was wondering if we're interested in that information *before* the driver is actually loaded/resolved as well

**Comment by thaJeztah** [comment]
Windows TP4 timed out: https://jenkins.dockerproject.org/job/Docker-PRs-WoW-TP4/2020/console

```
09:48:14 SKIP: docker_cli_run_test.go:1395: DockerSuite.TestRunResolvconfUpdate (Test requires a Linux daemon)
09:49:43 PASS: docker_cli_run_test.go:2713: DockerSuite.TestRunRestartMaxRetries	89.352s
09:49:43 SKIP: docker_cli_run_test.go:2160: DockerSuite.TestRunReuseBindVolumeThatIsSymlink (Test requires a Linux daemon)
09:49:44 panic: test timed out after 2h0m0s
09:49:44 
09:49:44 goroutine 6058 [running]:
09:49:44 panic(0xb895e0, 0xc082285910)
```

**Comment by calavera** [comment]
LGTM

**Comment by thaJeztah** [comment]
sigh https://jenkins.dockerproject.org/job/Docker-PRs-WoW-TP4/2042/console

```
16:06:09 Cannot start container a99a39802eb8f67462388421bfebd135395d3f714d62dd01cb93061b435e500c: HCSShim::StartComputeSystem failed in Win32: The object identifier does not represent a valid object. (0x10d8) id=a99a39802eb8f67462388421bfebd135395d3f714d62dd01cb93061b435e500c
16:06:09 
```

**Comment by thaJeztah** [comment]
alright let's keep it like this, we can decide later if we need the extra log line at the beginning

LGTM

**Comment by thaJeztah** [comment]
merging, don't think we need another run of WindowsTP4 for this
