### PR TITLE
c8d: Fix `docker diff`

### LINKED ISSUE #46607: .dockerenv does not appear when containerd-snapshotter is enabled
### Description

docker container should have /.dockerenv

### Reproduce

```
$ cat /etc/docker/daemon.json
{
	"features": {
		"containerd-snapshotter": true
	}
}

$ docker run --rm alpine ls -a /
.
..
bin
```

### Expected behavior

it should show .dockerenv

### docker version

```bash
Client: Docker Engine - Community
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:32:16 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:32:16 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 9
 Server Version: 24.0.6
 Storage Driver: overlayfs
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 6.1.0-0.deb11.11-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.28GiB
 Name: _______
 ID: RUHZ:MCAY:YDM2:JHNM:FH5J:BUZU:U7W2:LELY:EV7Q:HOKR:D5WW:QJFP
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

note: this is the same output as `sudo nerdctl --namespace moby run --rm alpine ls -a /`. So this might be snapshotter spec.

without containerd-snapshotter, the output is expected:

```
$ docker run --rm alpine ls -a /
.
..
.dockerenv
bin
```

### PR DESCRIPTION
**Pull request by rumpl**
- fixes https://github.com/moby/moby/issues/46607

**- What I did**

Diffing a container yielded some extra changes that come from the files/directories that we mount inside the container (/etc/resolv.conf for example). To avoid that we create an intermediate snapshot that has these files, with this we can now diff the container fs with its parent and only get the differences that were made inside the container.

**- How I did it**

Added a layer for the base snapshot of a container containing the files that are created by the runtime.

**- How to verify it**

Run `TestDiff`

```console
$ make DOCKER_GRAPHDRIVER=overlayfs TEST_FILTER=TestDiff TEST_INTEGRATION_USE_SNAPSHOTTER=1 TEST_IGNORE_CGROUP_CHECK=1 test-integration
```

**- Description for the changelog**

- containerd integration: Fixed `docker diff` containing extra differences

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: daemon/containerd/image_snapshot.go [hunk 1]
```diff
@@ -59,29 +60,44 @@ func (i *ImageService) PrepareSnapshot(ctx context.Context, id string, parentIma
...
-		ID:   id,
-		Type: "snapshots/" + i.StorageDriver(),
-	}); err != nil {
-		return err
-	}
+	ctx = leases.WithLease(ctx, lease.ID)
 
 	snapshotter := i.client.SnapshotService(i.StorageDriver())
 
+	if err := i.prepareInitLayer(ctx, id, parentSnapshot, setupInit); err != nil {
```
[the remark this answers is not in the document]
Comment (rumpl) [reply daemon/containerd/image_snapshot.go:72]: `setupInit` is always needed yes

File: integration/container/diff_test.go [hunk 2]
```diff
@@ -12,22 +12,36 @@ import (
...
+		{Kind: containertypes.ChangeAdd, Path: "/foo/bar"},
+	}
+
+	items, err := apiClient.ContainerDiff(ctx, cID)
+	assert.NilError(t, err)
+	assert.DeepEqual(t, expected, items)
+}
+
+func TestDiffStoppedContainer(t *testing.T) {
 	skip.If(t, testEnv.DaemonInfo.OSType == "windows", "FIXME")
```
Comment (thaJeztah) [inline integration/container/diff_test.go:32]: If we cannot diff a running container, does that mean we _could_ diff a stopped container on Windows (and so, we wouldn't have to skip this one?)

File: integration/container/diff_test.go [hunk 3]
```diff
@@ -12,22 +12,36 @@ import (
...
 	ctx := setupTest(t)
 	apiClient := testEnv.APIClient()
 
 	cID := container.Run(ctx, t, apiClient, container.WithCmd("sh", "-c", `mkdir /foo; echo xyzzy > /foo/bar`))
 
-	// Wait for it to exit as cannot diff a running container on Windows, and
-	// it will take a few seconds to exit. Also there's no way in Windows to
-	// differentiate between an Add or a Modify, and all files are under
-	// a "Files/" prefix.
+	poll.WaitOn(t, container.IsInState(ctx, apiClient, cID, "exited"), poll.WithDelay(100*time.Millisecond), poll.WithTimeout(60*time.Second))
```
Comment (thaJeztah) [inline integration/container/diff_test.go:38]: Would this comment still be useful (as it gives some context)?

Is the timeout we use here the timeout we nowadays need for Windows? (I recall @vvoland created a `const` for it somewhere, but not sure if that's in this package)

File: daemon/containerd/image_changes.go [hunk 4]
```diff
@@ -2,68 +2,35 @@ package containerd
...
-	diffIDs := image.RootFS.DiffIDs
-	parent, err := snapshotter.View(ctx, rnd.String(), identity.ChainID(diffIDs).String())
-	if err != nil {
-		return nil, err
-	}
 	defer func() {
-		if err := snapshotter.Remove(ctx, rnd.String()); err != nil {
-			log.G(ctx).WithError(err).WithField("key", rnd.String()).Warn("remove temporary snapshot")
+		if err := snapshotter.Remove(ctx, container.ID+"-parent-view"); err != nil {
+			log.G(ctx).WithError(err).Warn("error remove the parent view snapshot")
```
Comment (thaJeztah) [inline daemon/containerd/image_changes.go:23]: The warn here should probably be `error removing the parent view snapshot` or `removing the parent view snapshot` (it's clear form it being a warning and an error as detail that an error occurred while doing so).

**Review by thaJeztah — COMMENTED** [review]
I only gave this a "global" look; left some comments, but would have to dive deeper into the logic for a "full" review (but maybe others are able to help review).

File: daemon/containerd/image_snapshot.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (dmcgowan) [reply daemon/containerd/image_snapshot.go:72]: The current version doesn't use it though right? My understanding is that is no longer necessary from a runtime perspective and only useful to cleanup this diff case.

File: integration/container/diff_test.go (hunk 3 above)
Comment (vvoland) [reply integration/container/diff_test.go:38]: Yeah it's in the same package: `StopContainerWindowsPollTimeout`

Comment (vvoland) [reply integration/container/diff_test.go:38]: But, this test isn't supposed to execute on Windows, so I think we can just leave the default timeout here.

File: daemon/containerd/image_changes.go (hunk 4 above)
Comment (rumpl) [reply daemon/containerd/image_changes.go:23]: Oh man, who wrote this? Did I? That's not proper english!

File: integration/container/diff_test.go (hunk 3 above)
Comment (rumpl) [reply integration/container/diff_test.go:38]: > Would this comment still be useful (as it gives some context)?

It will yeah, I moved these tests a bit too much but yeah, the comment is useful

File: integration/container/diff_test.go (hunk 2 above)
Comment (rumpl) [reply integration/container/diff_test.go:32]: I think we should be able to diff a stopped container, the tests suggests so, but I have no idea what "FIXME" means, I didn't go spelunking to see when and why this was added, I will, FIXME is quite criptic and doesn't really give any useful info

**Review by vvoland — APPROVED** [review]

File: daemon/containerd/image_snapshot.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (rumpl) [reply daemon/containerd/image_snapshot.go:72]: Ah sorry, I misunderstood your question, so yeah, it would seem that this is not really needed for the runtime. Let me see if I can switch this up and prepare a snapshot with the init layer only when diffing, see where that takes us

File: integration/container/diff_test.go (hunk 2 above)
Comment (thaJeztah) [reply integration/container/diff_test.go:32]: LOL, and in case you were wondering "why all the skips, and not just gate them in files with `//go:build windows` build-tags; I think that was a combination;

- being able to run the test from a Linux machine against a Windows machine (I think this was needed when there were only internal builds of Windows that supported containers, so we didn't have them in our CI, but could connect to them)
- as a passive-aggressive way to say: look at all these skipped tests on Windows (hint hint, nudge nudge)

Comment (rumpl) [reply integration/container/diff_test.go:32]: > If we think this should work on Windows, perhaps we should try removing the skip and see if it does :)

I tried, it fails, or rather it gives a huge diff

Comment (rumpl) [reply integration/container/diff_test.go:32]: > Right, so I (perhaps incorrectly) assumed you added the new test to split the "won't work on windows" from "should work on windows" ones, so that we could skip the new test, but run the existing one.

Yeah no, I split to two different tests: one for diffing running containers and the second one for diffing on a stopped container, we didn't have a test for diff on a stopped container on linux and I had a bug in my code so wanted to make sure that doesn't happen again

File: daemon/containerd/image_changes.go (hunk 4 above)
Comment (rumpl) [reply daemon/containerd/image_changes.go]: Fixed

File: integration/container/diff_test.go (hunk 3 above)
Comment (rumpl) [reply integration/container/diff_test.go:40]: I put the comment back now

File: daemon/containerd/image_snapshot.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (rumpl) [reply daemon/containerd/image_snapshot.go:72]: OK so the init layer is indeed only needed for diffing, I tried not adding it and juggling around with the snapshots but at the end of the day the root in `containerRoot` is missing things (like `/proc` etc).

[the remark this answers is not in the document]
Comment (thaJeztah) [reply daemon/containerd/image_snapshot.go:72]: Are those parts that are missing the "default mounts"? Wondering if in that case we could take that list and exclude them 🤔

File: integration/container/diff_test.go (hunk 2 above)
Comment (thaJeztah) [reply integration/container/diff_test.go:34]: > I tried, it fails, or rather it gives a huge diff

OH! I think i saw that diff posted somewhere (or in a CI failure)

LOL, so I guess "diff" is just broken on Windows then, and nobody ever looked into it, and nobody complained 🥹

File: daemon/containerd/image_snapshot.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (rumpl) [reply daemon/containerd/image_snapshot.go:72]: If we exclude them then we won't know if things changed, for example, what would happen if I `rm -fr /etc` in my container? Removing those from the diff would mean the diff is wrong

**Review by dmcgowan — APPROVED** [review]
