### PR TITLE
Check bad syntax on dockerfile before building.

### LINKED ISSUE #26453: Bad syntax on Dockerfile should be checked before building
**Output of `docker version`:**

<details>
```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:08:31 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:08:31 2016
 OS/Arch:      linux/amd64
```
</details>

**Output of `docker info`:**

<details>
```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-8:5-263836-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.831 GB
 Data Space Total: 107.4 GB
 Data Space Available: 5.477 GB
 Metadata Space Used: 2.437 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.133 (2016-08-15)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.6.0-1-amd64
Operating System: Debian GNU/Linux stretch/sid
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.769 GiB
Name: debian
ID: UBDH:TW5K:N3EZ:UJRQ:UPL3:YUC3:4LCV:XGSR:WWL2:CBB2:L5BJ:AIYG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: mcornella
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
Insecure Registries:
 127.0.0.0/8
```
</details>

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Environment agnostic.

**Steps to reproduce the issue:**

1. Create a malformed Dockerfile, for instance forgetting a backslash before a newline, specially on a later point in the build:

    <details>
    ```Dockerfile
FROM ubuntu:trusty

RUN apt-get update && apt-get install -y \
        zsh \
        curl \
        gdb \
    && curl https://taskwarrior.org/download/task-2.5.1.tar.gz -o task-2.5.1.tar.gz \
    && tar xzf task-2.5.1.tar.gz \
    && cd task-2.5.1 \
    && cmake -DCMAKE_BUILD_TYPE=release . \
    && make \
    && make install \
    && cd ..                                        # oops
    && rm -rf task* \
    && rm -rf /var/lib/apt/lists/*
```
</details>

2. Build the image with `docker build .`

3. Wait until the whole build arrives at the point in which there's a syntax error. Then curse the world.

**Describe the results you received:**

A whole page of output after minutes of building, then a dreaded `Unknown instruction: &&`:

<details>
```
...
-- Installing: /usr/local/share/doc/task/scripts/zsh/_task
-- Installing: /usr/local/share/doc/task/scripts/hooks
-- Installing: /usr/local/share/doc/task/scripts/hooks/on-exit.shadow-file
-- Installing: /usr/local/share/doc/task/scripts/hooks/on-add
-- Installing: /usr/local/share/doc/task/scripts/hooks/README
-- Installing: /usr/local/share/doc/task/scripts/hooks/on-add.the
-- Installing: /usr/local/share/doc/task/scripts/hooks/on-launch
-- Installing: /usr/local/share/doc/task/scripts/hooks/on-exit
-- Installing: /usr/local/share/doc/task/scripts/hooks/on-modify
-- Installing: /usr/local/share/doc/task/scripts/add-ons
-- Installing: /usr/local/share/doc/task/scripts/add-ons/update-holidays.pl
-- Installing: /usr/local/share/doc/task/scripts/add-ons/README
 ---> 43792c96d23d
Removing intermediate container 0f5ab0af990c
Step 4 : && 
Unknown instruction: &&
```
</details>

**Describe the results you expected:**

A syntax error right before beginning the build, hopefully with debugging information like the line number. For example:

```
$ docker build .
line 14: Unknown instruction: &&
```

**Additional information you deem important (e.g. issue happens only occasionally):**

This happens specially when constructing an image for the first time and iterating back and forth in search of the proper code.

### PR DESCRIPTION
**Pull request by yongtang**
**\- What I did**

This fix tries to address the issue raised in #26453 where bad syntax on dockerfile is not checked before building, thus user has to wait before seeing error in dockerfile.

**\- How I did it**

This fix fixes the issue by evaluating all the instructions and check syntax before dockerfile is invoked actually.

**\- How to verify it**

All existing tests pass.

**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**

This fix fixes  #26453

Signed-off-by: Yong Tang yong.tang.github@outlook.com

### CODE REVIEW

File: builder/dockerfile/evaluator.go [hunk 1]
```diff
@@ -201,3 +201,31 @@ func (b *Builder) dispatch(stepN int, stepTotal int, ast *parser.Node) error {
 
 	return fmt.Errorf("Unknown instruction: %s", upperCasedCmd)
 }
+
+// evaluateDispatch does a simple check for syntax errors of the Dockerfile.
+// Because some of the instructions can only be validated through runtime,
+// arg, env, etc., this syntax check will not be complete and could not replace
+// the runtime check. Instead, this function is only a helper that allows
+// user to find out the obvious error in Dockerfile earlier on.
+func (b *Builder) evaluateDispatch(ast *parser.Node) error {
```
Comment (cyphar) [inline builder/dockerfile/evaluator.go]: IMO this should be called "checkDispatch", since you're not actually evaluating anything here.

**Comment by runcom** [comment]
@yongtang would be nice to have integration tests to check this behavior (and fix the old one probably)

File: builder/dockerfile/evaluator.go [hunk 2]
```diff
@@ -201,3 +201,31 @@ func (b *Builder) dispatch(stepN int, stepTotal int, ast *parser.Node) error {
...
+	cmd := ast.Value
+	upperCasedCmd := strings.ToUpper(cmd)
+
+	// To ensure the user is given a decent error message if the platform
+	// on which the daemon is running does not support a builder command.
+	if err := platformSupports(strings.ToLower(cmd)); err != nil {
+		return err
+	}
+
+	if cmd == "onbuild" {
```
Comment (duglin) [inline builder/dockerfile/evaluator.go]: While this is a trivial check I'd prefer if we didn't treat "ONBIULD" as special since this type of check could be done for pretty much all of the cmds, so we should be consistent and leave this function as just a check of the cmds themselves and nothing more - for now.

Comment (duglin) [inline builder/dockerfile/evaluator.go]: ok, now I think I know why you did ONBUILD on its own... you wanted to check the next args to see if its a valid cmd.  So, why not do that here instead of in `processImageFrom()`?  I'd prefer if we did all of this simple syntax checking in one spot.

File: builder/dockerfile/internals.go [hunk 3]
```diff
@@ -435,14 +435,18 @@ func (b *Builder) processImageFrom(img builder.Image) error {
...
-		for i, n := range ast.Children {
+		for _, n := range ast.Children {
 			switch strings.ToUpper(n.Value) {
 			case "ONBUILD":
 				return fmt.Errorf("Chaining ONBUILD via `ONBUILD ONBUILD` isn't allowed")
 			case "MAINTAINER", "FROM":
 				return fmt.Errorf("%s isn't allowed as an ONBUILD trigger", n.Value)
 			}
-
+			if err := b.evaluateDispatch(n); err != nil {
```
Comment (duglin) [inline builder/dockerfile/internals.go]: if I'm following, I'd prefer to undo this split here and just do the syntax check in the `evaluateDispatch()` func above.

File: cli/command/image/build.go [hunk 4]
```diff
@@ -293,6 +293,9 @@ func runBuild(dockerCli *command.DockerCli, options buildOptions) error {
 
 	response, err := dockerCli.Client().ImageBuild(ctx, body, buildOptions)
 	if err != nil {
+		if options.quiet {
```
Comment (duglin) [inline cli/command/image/build.go]: What's this change about?

**Comment by duglin** [comment]
Just a few questions/comments.  Can you also look to add some testcases?  Or do existing tests cover it?

File: builder/dockerfile/evaluator.go (hunk 1 above)
Comment (yongtang) [inline builder/dockerfile/evaluator.go]: Thanks @cyphar. The PR has been updated with name changed.

File: builder/dockerfile/evaluator.go (hunk 2 above)
Comment (yongtang) [inline builder/dockerfile/evaluator.go]: Thanks @duglin the PR has been updated with check done inside `checkDispatch()`

File: cli/command/image/build.go (hunk 4 above)
Comment (yongtang) [inline cli/command/image/build.go]: The change is to adjust the case in `TestBuildNotVerboseFailure` because it requires stderr output in quiet mode and stdout+stderr output in verbose mode to be equal. Without the change the `Sending build context to Docker daemon 2.048 kB` will be missing from the output:

```
func (s *DockerSuite) TestBuildNotVerboseFailure(c *check.C) {
        // This test makes sure that -q works correctly when build fails by
        // comparing between the stderr output in quiet mode and in stdout
        // and stderr output in verbose mode
        tt := []struct {
                TestName  string
                BuildCmds string
        }{
                {"quiet_build_no_from_at_the_beginning", "RUN whoami"},
                {"quiet_build_unknown_instr", "FROMD busybox"},
        }

        for _, te := range tt {
                _, _, qstderr, qerr := buildImageWithStdoutStderr(te.TestName, te.BuildCmds, false, "-q", "--force-rm", "--rm")
                _, vstdout, vstderr, verr := buildImageWithStdoutStderr(te.TestName, te.BuildCmds, false, "--force-rm", "--rm")
                if verr == nil || qerr == nil {
                        c.Fatal(fmt.Errorf("Test [%s] expected to fail but didn't", te.TestName))
                }
                if qstderr != vstdout+vstderr {
                        c.Fatal(fmt.Errorf("Test[%s] expected that quiet stderr and verbose stdout are equal; quiet [%v], verbose [%v]", te.TestName, qstderr, vstdout+vstderr))
                }
    }
```

**Comment by yongtang** [comment]
Thanks @runcom @duglin for the review. The pull request has been updated and integration test cases have been added to the PR.

Please take a look and let me know if there are any issues.

**Comment by duglin** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐸
Moving this to doc review as I think we should at least note something in the build docs (and in API changes too 👼)
/cc @thaJeztah

**Comment by thaJeztah** [comment]
Yes, I think we could use some information that the builder performs a "basic" validation of the Dockerfile before starting the actual build. Perhaps;

- in the changelog (although strictly, it's not versioned, so we should probably mention that there); https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api.md#v125-api-changes
-  in the description of the endpoint https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.25.md#build-image-from-a-dockerfile (here as well; we may need to update old versions of the API docs as well, since it's not versioned)
- a mention of this in the "usage" section of the builder https://github.com/docker/docker/blob/master/docs/reference/builder.md#usage (thinking of adding it to the paragraph starting with "The Docker daemon runs the instructions ...", but open to suggestions)

**Comment by yongtang** [comment]
Thanks @thaJeztah. The docs and changelog have been updated. Please take a look and let me know if there are any issues.

File: docs/reference/api/docker_remote_api_v1.18.md [hunk 5]
```diff
@@ -1201,6 +1201,11 @@ The archive may include any number of other files,
 which are accessible in the build context (See the [*ADD build
 command*](../../reference/builder.md#add)).
 
+Before the Docker daemon runs the instructions in the `Dockerfile`, it performs
+a preliminary validation of the `Dockerfile` and returns error if the syntax is
+incorrect. After that, each instruction is run one-by-one until the ID of the new
+image is output.
```
Comment (thaJeztah) [inline docs/reference/api/docker_remote_api_v1.18.md]: Was thinking;

```Markdown
The Docker daemon performs a preliminary validation of the `Dockerfile` before
starting the build, and returns an error if the syntax is incorrect. After that,
each instruction is run one-by-one until the ID of the new image is output.
```

Perhaps `preliminary` should be `cursory`?

@duglin @mstanleyjones could you have a look at my suggestions?

File: docs/reference/api/docker_remote_api.md [hunk 6]
```diff
@@ -123,6 +123,7 @@ This section lists each version from latest to oldest.  Each listing includes a
 * `POST /containers/create/` and `POST /containers/(name)/update` now validates restart policies.
 * `POST /containers/create` now validates IPAMConfig in NetworkingConfig, and returns error for invalid IPv4 and IPv6 addresses (`--ip` and `--ip6` in `docker create/run`).
 * `POST /containers/create` now takes a `Mounts` field in `HostConfig` which replaces `Binds` and `Volumes`. *note*: `Binds` and `Volumes` are still available but are exclusive with `Mounts`
+* `POST /build` now performs a preliminary validation of the `Dockerfile` and returns error, before each instruction is run one-by-one. Note this is unversioned and applied to all previous remote API versions.
```
Comment (thaJeztah) [inline docs/reference/api/docker_remote_api.md]: "one-by-one" is not needed here, we can simplify to

```Markdown
* `POST /build` now performs a preliminary validation of the `Dockerfile` before starting the build,
  and returns an error if the syntax is incorrect. Note that this change is _unversioned_ and applied
  to all API versions.
```

File: docs/reference/builder.md [hunk 7]
```diff
@@ -68,6 +68,13 @@ add multiple `-t` parameters when you run the `build` command:
 
     $ docker build -t shykes/myapp:1.0.2 -t shykes/myapp:latest .
 
+Before the Docker daemon runs the instructions in the `Dockerfile`, it performs
+a preliminary validation of the `Dockerfile` and returns error if the syntax is incorrect:
```
Comment (thaJeztah) [inline docs/reference/builder.md]: s/error/an error/

**Review by thaJeztah — CHANGES_REQUESTED** [review]
Thanks @yongtang, I left some comments (but open to suggestions from native english people :smile:)

**Comment by thaJeztah** [comment]
Orthogonal to this PR, but @duglin what would you think about having;

- having the client perform a validate step first, before sending the build-context (validation could take place on the daemon; same endpoint with a query-parameter or a separate endpoint)
- perhaps a `docker build --validate-only` option?

I know https://github.com/docker/docker/issues/26453 is about validating the Dockerfile to prevent having to wait for the _build_ to complete, but in some scenarios, sending the build-context could actually take up a lot of time; validating the Dockerfile before sending could be a big timesaver for those situations.

**Comment by duglin** [comment]
If we can do the fail-quick-syntax-check on the Dockerfile on the client, and do it easily, meaning it doesn't require a major redesign of the code then I think its a good idea.  My only concern is https://github.com/docker/docker/pull/12749.  I really think that INCLUDE needs to support env vars, and args, and I'm not sure we can do a simple syntax check on included files w/o processing the ENV and ARG cmds fully.  Of course https://github.com/docker/docker/pull/12749 could impact this PR too - just didn't get that far yet in my thinking about it....

**Comment by yongtang** [comment]
Thanks @thaJeztah. The documentation has been updated. Please let me know if there are any issues.

**Comment by thaJeztah** [comment]
docs LGTM, thanks!

**Review by thaJeztah — APPROVED** [review]

**Review by vdemeester — APPROVED** [review]
docs LGTM 🐸

**Comment by mcornella** [comment]
Thanks everybody!

**Comment by thaJeztah** [comment]
Thanks @yongtang - let me know if you (with @duglin) want to work on the improvements suggested above (https://github.com/docker/docker/pull/26516#issuecomment-248868526). Perhaps we should open an issue for tracking that?

**Comment by yongtang** [comment]
Thanks @duglin @thaJeztah. I opened a new issue #26877 to track the improvement proposal. I will see if I can open a PR soon.
