### PR TITLE
modifying docker --since and --until to support nanoseconds and time …

### LINKED ISSUE #16395: `docker logs --since` incorrectly parses timestamps generated by `docker logs -t`
`docker logs -t` emits RFC3339 timestamps with a "Z" timezone suffix, which denotes UTC.

```
$ docker logs -t 196a93700f9c
2015-09-18T11:30:13.368899817Z 1
2015-09-18T11:30:13.871609615Z 2
2015-09-18T11:30:14.376469980Z 3
2015-09-18T11:30:14.878498664Z 4
2015-09-18T11:30:15.383748382Z 5
```

But, `docker logs --since TIMESTAMP` seems to ignore the "Z" suffix.

```
$ docker logs -t --since 2015-09-18T11:30:15.383748382Z 196a93700f9c
2015-09-18T11:30:13.368899817Z 1
2015-09-18T11:30:13.871609615Z 2
2015-09-18T11:30:14.376469980Z 3
2015-09-18T11:30:14.878498664Z 4
2015-09-18T11:30:15.383748382Z 5
```

even though it does recognise the equivalent "+00:00":

```
$ docker logs -t --since 2015-09-18T11:30:15.383748382+00:00 196a93700f9c
2015-09-18T11:30:15.383748382Z 5
```

We can also see that even with the explicit "Z" suffix, timestamp parsing is affected by local timezone:

```
$ docker logs -t --since 2015-09-18T11:30:15.383748382Z 196a93700f9c
2015-09-18T11:30:13.368899817Z 1
2015-09-18T11:30:13.871609615Z 2
2015-09-18T11:30:14.376469980Z 3
2015-09-18T11:30:14.878498664Z 4
2015-09-18T11:30:15.383748382Z 5

$ TZ=GMT docker logs -t --since 2015-09-18T11:30:15.383748382Z 196a93700f9c
2015-09-18T11:30:15.383748382Z 5
```

### LINKED ISSUE #16396: "docker logs --since" ignores sub-second component of timestamp
I expected the `--since` option to `docker logs` to consider the entire timestamp, but it appears to ignore the sub-second component.

```
$ docker logs -t --since 2015-09-18T11:30:15.999999999+00:00 196a93700f9c
2015-09-18T11:30:15.383748382Z 5

$ docker logs -t --since 2015-09-18T11:30:16+00:00 196a93700f9c
```

With

```
$ docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   0a8c2e3
 Built:        Fri Sep 11 01:46:35 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64
```

### PR DESCRIPTION
**Pull request by mikebrow**
Added ".nanoseconds" to since variable in json that is being passed between client and server for docker log -t --since command, and docker events --since and --until; refactored the code; added a new function for parsing the json received unix timestamp; added additional supported timestamp formats for the command line; and updated the docs to reflect the changes; added enough unit testcases to get to 100% coverage on the two apis in the timeutils package

Fix #16396
Fix #16395 
Rebases PR #16688

Signed-off-by: Mike Brown brownwm@us.ibm.com

### CODE REVIEW

**Comment by mikebrow** [comment]
@vdemeester I've addressed your comments regarding the unit tests by adding an expectedErr bool to the unit test...  Much better now I think.  Thx!

File: pkg/timeutils/utils_test.go [hunk 1]
```diff
@@ -8,37 +8,84 @@ import (
...
 	for _, c := range cases {
-		o := GetTimestamp(c.in, now)
-		if o != c.expected {
-			t.Fatalf("wrong value for '%s'. expected:'%s' got:'%s'", c.in, c.expected, o)
+		s, n, err := ParseTimestamps(c.in, c.def)
+		if s != c.expectedS ||
+			n != c.expectedN ||
+			(err == nil && c.expectedErr) ||
+			(err != nil && !c.expectedErr) {
+			t.Fatalf("wrong values for input `%s` with default `%d` expected:'%d'seconds and `%d`nanosecond got:'%d'seconds and `%d`nanoseconds with error: `%s`", c.in, c.def, c.expectedS, c.expectedN, s, n, err)
```
Comment (MHBauer) [inline pkg/timeutils/utils_test.go]: Same as above.

File: pkg/timeutils/utils_test.go [hunk 2]
```diff
@@ -8,37 +8,84 @@ import (
...
-		{"invalid", "invalid"},
+		{"invalid", "invalid", false},
+	}
+
+	for _, c := range cases {
+		o, err := GetTimestamp(c.in, now)
+		if o != c.expected ||
+			(err == nil && c.expectedErr) ||
+			(err != nil && !c.expectedErr) {
+			t.Fatalf("wrong value for '%s'. expected:'%s' got:'%s' with error: `%s`", c.in, c.expected, o, err)
```
Comment (MHBauer) [inline pkg/timeutils/utils_test.go]: In the interest of running the whole table to see if there are any other errors, maybe
```
t.Fail()
t.Errorf(...)
```

Also, maybe print the value of `expectedErr`, to know if that is what failed the check.

**Comment by MHBauer** [comment]
Tests of timeutil look good. I would like to see an integration-test for the cli, to show that it surfaces the new logic that fails on the client side with a badly formatted time.

File: api/server/router/local/info.go [hunk 3]
```diff
@@ -66,19 +67,19 @@ func (s *router) getEvents(ctx context.Context, w http.ResponseWriter, r *http.R
 	if err := httputils.ParseForm(r); err != nil {
 		return err
 	}
-	since, err := httputils.Int64ValueOrDefault(r, "since", -1)
+	since, sincen, err := timeutils.ParseTimestamps(r.Form.Get("since"), -1)
```
Comment (cpuguy83) [inline api/server/router/local/info.go]: Can we call this `sinceNano` instead of `sincen`?

File: api/server/router/local/info.go [hunk 4]
```diff
@@ -66,19 +67,19 @@ func (s *router) getEvents(ctx context.Context, w http.ResponseWriter, r *http.R
...
 	if err != nil {
 		return err
 	}
-	until, err := httputils.Int64ValueOrDefault(r, "until", -1)
+	until, untiln, err := timeutils.ParseTimestamps(r.Form.Get("until"), -1)
```
Comment (cpuguy83) [inline api/server/router/local/info.go]: Can we call this `untilNano` instead of `untiln`

File: pkg/timeutils/utils.go [hunk 5]
```diff
@@ -1,36 +1,122 @@
...
+		} else {
+			if tcolons >= 2 {
+				format = time.RFC3339
+			} else if tcolons == 1 {
+				format = "2006-01-02T15:04Z07:00"
+			} else {
+				format = "2006-01-02T15Z07:00"
+			}
+		}
+	} else if parseInLocation {
```
Comment (cpuguy83) [inline pkg/timeutils/utils.go]: This looks like a good case for a `switch` instead of `if...else if...elise if..`

File: pkg/timeutils/utils.go [hunk 6]
```diff
@@ -1,36 +1,122 @@
...
+		// there will be an extra colon in the input for the tz offset subract that
+		// colon from the tcolons count
+		if !parseInLocation && !strings.ContainsAny(value, "zZ") && tcolons > 0 {
+			tcolons--
+		}
+		if parseInLocation {
+			if tcolons >= 2 {
+				format = RFC3339Local
+			} else if tcolons == 1 {
+				format = "2006-01-02T15:04"
```
Comment (cpuguy83) [inline pkg/timeutils/utils.go]: constants for these formats?

File: pkg/timeutils/utils.go [hunk 7]
```diff
@@ -1,36 +1,122 @@
...
+	"math"
 	"strconv"
 	"strings"
 	"time"
 )
 
+// These are additional predefined layouts for use in Time.Format and Time.Parse
+// with --since and --until parameters for `docker logs` and `docker events`
+const (
+	RFC3339Local     = "2006-01-02T15:04:05"           // RFC3339 with local timezone
```
Comment (cpuguy83) [inline pkg/timeutils/utils.go]: It doesn't seem like these are used outside this package. Can we un-export?

File: pkg/timeutils/utils.go [hunk 8]
```diff
@@ -1,36 +1,122 @@
...
+		// we want the number of colons in the T portion of the timestamp
+		tcolons := strings.Count(value, ":")
+		// if parseInLocation is off and we have a +/- zone offset (not Z) then
+		// there will be an extra colon in the input for the tz offset subract that
+		// colon from the tcolons count
+		if !parseInLocation && !strings.ContainsAny(value, "zZ") && tcolons > 0 {
+			tcolons--
+		}
+		if parseInLocation {
+			if tcolons >= 2 {
```
Comment (cpuguy83) [inline pkg/timeutils/utils.go]:
```go
format = "2006-01-02T15"
if tcolons > 2 {
    format = RFC3339Local
}
if tcolons == 1 {
  format = format = "2006-01-02T15:04"
}

Comment (cpuguy83) [inline pkg/timeutils/utils.go]: This is my personal preference as I find this easier to read.

File: pkg/timeutils/utils.go [hunk 9]
```diff
@@ -1,36 +1,122 @@
...
 
-	loc := time.FixedZone(time.Now().Zone())
-	if len(value) < len(format) {
-		format = format[:len(value)]
+	if err != nil {
+		// if there is a `-` then its an RFC3339 like timestamp otherwise assume unixtimestamp
+		if strings.Contains(value, "-") {
+			return "", err // was probably an RFC3339 like timestamp but the parser failed with an error
+		}
+		return value, nil // unixtimestamp in and out case
```
Comment (cpuguy83) [inline pkg/timeutils/utils.go]: ??? I don't understand the comment

Comment (mikebrow) [inline pkg/timeutils/utils.go]: it means we are returning what was passed into the function because we believe they entered seconds[.nanoseconds] from the command line.

File: pkg/timeutils/utils.go (hunk 6 above)
Comment (mikebrow) [inline pkg/timeutils/utils.go]: I didn't think those sub-set formats were worthy of a constant..

File: pkg/timeutils/utils_test.go (hunk 2 above)
Comment (mikebrow) [inline pkg/timeutils/utils_test.go]: The expected an error is just a bool.. I didn't want to be tied to a specific error type in case it changed over time.

File: api/server/router/local/info.go (hunk 3 above)
Comment (mikebrow) [inline api/server/router/local/info.go]: will do...

File: api/server/router/local/info.go (hunk 4 above)
Comment (mikebrow) [inline api/server/router/local/info.go]: will do

File: pkg/timeutils/utils.go (hunk 5 above)
Comment (mikebrow) [inline pkg/timeutils/utils.go]: feels odd switching from ifs to switches in the middle of some if logic..

File: pkg/timeutils/utils.go (hunk 7 above)
Comment (mikebrow) [inline pkg/timeutils/utils.go]: sure

File: pkg/timeutils/utils.go (hunk 9 above)
Comment (cpuguy83) [inline pkg/timeutils/utils.go]: ok, thanks.

File: pkg/timeutils/utils.go (hunk 8 above)
Comment (mikebrow) [inline pkg/timeutils/utils.go]: ok... np I tend to write code that will run faster vs easier to read... maybe the compiler will optimize :-)

File: pkg/timeutils/utils_test.go (hunk 1 above)
Comment (mikebrow) [inline pkg/timeutils/utils_test.go]: will do...

**Comment by mikebrow** [comment]
Updated the PR addressing everyone's comments... cheers!

File: man/docker-logs.1.md [hunk 10]
```diff
@@ -42,11 +42,17 @@ logging drivers.
...
-the date relative to the client machine’s time. You can combine
-the `--since` option with either or both of the `--follow` or `--tail` options.
+The `--since` option can be Unix timestamps, date formated timestamps, or Go 
+duration strings (e.g. `10m`, `1h30m`) computed relative to the client machine’s 
+time. Supported formats for date formated time stamps include RFC3339Nano, 
+RFC3339, `2006-01-02T15:04:05`, `2006-01-02T15:04:05.999999999`, 
+`2006-01-02Z07:00`, and `2006-01-02`. The local timezone on the client will be 
+used if you do not provide either a `Z` or a `+-00:00` timezone offset at the 
+end of the timestamp.  When providing Unix timestamps enter 
+seconds[.nanoseconds], where seconds is the number of seconds that have elapsed
```
Comment (MHBauer) [inline man/docker-logs.1.md]: Since the code performs a shift (i.e. 123.456 is four-fifty-six milliseconds, rather than four-fifty-six nanoseconds), should this not say `seconds[.subseconds]`?

Comment (mikebrow) [inline man/docker-logs.1.md]: Or fractional second... but let's consider...  

The shift is hidden by the code, the precision is to nanoseconds because of the unix time api limitations.  The traditional unix timestamp says it's nanoseconds. But you are right in that because it's not a separate value it's not really nanoseconds it's subseconds up to or exceeding the precision of nanoseconds.  But alas that gets a bit long winded to say no? That the impl will support whatever you put there as a subsecond and convert that to the precision of nanoseconds for the check against the log/event entries that are stored as seconds + nanoseconds. When they run the logs with -t they see seconds.nanoseconds.  When they cut and paste the timestamp from seconds.nanoseconds they would have to manually trunc some portion of the timestamp nanoseconds to get millis and it would work...  

I propose leaving it as it is but add a sentence explaining it.  Something like "Where the optional .nanoseconds field is a fraction of a second and is no more than nine digits long."

**Comment by mikebrow** [comment]
A couple documentation updates to the PR per suggestion from @MHBauer.  Cheers!!

**Comment by MHBauer** [comment]
I like it. Seems complete.

**Comment by crosbymichael** [comment]
LGTM

**Comment by tonistiigi** [comment]
LGTM

**Comment by runcom** [comment]
LGTM

**Comment by trajano** [comment]
This seems to fail with millisecond timestamps though e.g. `2020-05-01T12:17:41.248Z`
