### PR TITLE
Prune named but untagged images if danglingOnly=true

### LINKED ISSUE #30307: 1.13.0 - system prune vs. images -f dangling=true: different behaviour
**Description**
`docker system prune -f` is supposed to remove dangling images but images tagged `<none>` aren't necessarily removed. 
Meanwhile, `docker rmi $(docker images -f dangling=true)` will remove more images. 
Something is not coherent in one of those?

**Steps to reproduce the issue:**
1. Pull an image by a digest (docker pull image@sha256:...)
2. docker system prune -f
3. docker rmi $(docker images -f dangling=true)

**Describe the results you received:**
3rd command above still deletes an image.

**Describe the results you expected:**
Prune should have done all the work before the last command.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 23
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 31
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-59-generic
Operating System: Linux Mint 18
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 30.99 GiB
Name: octet
ID: Z6SL:RSSC:M7BQ:NXJX:KHVZ:7IAZ:TIO2:G2QP:HKVC:NM76:ZWOH:KMVC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by mlaventure**
Signed-off-by: Kenfe-Mickael Laventure <mickael.laventure@gmail.com>

--
Closes #30307

### CODE REVIEW

File: daemon/prune.go [hunk 1]
```diff
@@ -135,24 +135,34 @@ func (daemon *Daemon) ImagesPrune(pruneFilters filters.Args) (*types.ImagesPrune
...
 
-			nrRefs := len(refs)
-			for _, ref := range refs {
-				// If nrRefs == 1, we have an image marked as myreponame:<none>
-				// i.e. the tag content was changed
-				if _, ok := ref.(reference.Canonical); ok && nrRefs > 1 {
-					continue
+				for _, ref := range refs {
+					if _, ok := ref.(reference.NamedTagged); ok {
+						repoTagsCount++
```
Comment (cpuguy83) [inline daemon/prune.go]: Can just be a boolean and break can't it?

File: daemon/prune.go [hunk 2]
```diff
@@ -135,24 +135,34 @@ func (daemon *Daemon) ImagesPrune(pruneFilters filters.Args) (*types.ImagesPrune
 		deletedImages := []types.ImageDelete{}
 		refs := daemon.referenceStore.References(dgst)
 		if len(refs) > 0 {
-			if danglingOnly {
-				// Not a dangling image
-				continue
-			}
+			if !danglingOnly {
```
Comment (cpuguy83) [inline daemon/prune.go]: Can we simplify this a bit?

Seems like we could do something like

```go
shouldDelete := !danglingOnly
if !shouldDelete {
   for _, ref := range refs {
       if _, ok := ref.(reference.NamedTagged); ok {
           shouldDelete = true
           break
       }
    }

    if shouldDelete {
        // delete all the things
    }
}
```

**Review by cpuguy83 — CHANGES_REQUESTED** [review]
Maybe we can add a quick test (do we already have a pull-by-digest test somewhere?) for this?

**Comment by mlaventure** [comment]
@cpuguy83 have a look at this version, it's indeed cleaner, thanks.

File: daemon/prune.go [hunk 3]
```diff
@@ -135,24 +135,29 @@ func (daemon *Daemon) ImagesPrune(pruneFilters filters.Args) (*types.ImagesPrune
 		deletedImages := []types.ImageDelete{}
 		refs := daemon.referenceStore.References(dgst)
 		if len(refs) > 0 {
-			if danglingOnly {
-				// Not a dangling image
-				continue
+			shouldDelete := !danglingOnly
+			if !shouldDelete {
+				hasTag := false
```
Comment (cpuguy83) [inline daemon/prune.go]: This is really an extra variable since you can set `shouldDelete` in the loop below.

Comment (mlaventure) [inline daemon/prune.go]: `shouldDelete` needs to stay `false` in that case. I only want to set it to `true` if there's no `NamedTagged`. If I were to set to `true` here it would delete all images.

Comment (cpuguy83) [inline daemon/prune.go]: Oh yes, missed that subtlety.

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by LK4D4** [comment]
LGTM
