### PR TITLE
fix: load the CDI driver before the dockerd daemon starts

### LINKED ISSUE #49989: With CDI enabled, dockerd fails to start containers with `restart: always` setting
### Description

Whenever dockerd starts, containers that depend on CDI devices that have been set to start automatically will fail with error: `could not select device driver \"cdi\" with capabilities: [[]]`.

This is because when the dockerd daemon starts, it will register the CDI device too late when containers are set to automatically start.

When dockerd starts, it creates the daemon at:
- https://github.com/moby/moby/blob/b87aecc50adb5af7c79b9fcffde0fed79735b115/cmd/dockerd/daemon.go#L253-L253

Which in turn, calls to restoring the containers:
- https://github.com/moby/moby/blob/c4dc09eac1c441b9b8af6dff1aabbbbd93f6ba4e/daemon/daemon.go#L1171

All this, happens before the CDI registration happens at https://github.com/moby/moby/blob/b87aecc50adb5af7c79b9fcffde0fed79735b115/cmd/dockerd/daemon.go#L265-L273, leading to the error: `could not select device driver \"cdi\" with capabilities: [[]]`

### Reproduce

1. Enable CDI, configure CDI so that you have at least one valid device
2. `docker run --name=gpu-test-container --restart=always --entrypoint='/bin/sh' --device=nvidia.com/gpu=all ubuntu:latest -c 'nvidia-smi -L && sleep infinity'`
3. Restart docker daemon
4. Check that the container failed to start due to the mentioned error

### Expected behavior

The containers set to automatically restart should restart without errors.

### docker version

```bash
❯ docker version
Client:
 Version:           27.5.1
 API version:       1.47
 Go version:        go1.24.2
 Git commit:        v27.5.1
 Built:             Thu Jan  1 00:00:00 1970
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          dev
  API version:      1.49 (minimum version 1.24)
  Go version:       go1.24.3
  Git commit:       451c9f0492b66f444f6ed5c9a7c31a6eeca0c81c
  Built:            Thu May 15 09:31:05 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v2.0.1
  GitCommit:        refs/tags/v2.0.1
 runc:
  Version:          1.1.15
  GitCommit:
 rootlesskit:
  Version:          2.3.1
  ApiVersion:       1.1.1
  NetworkDriver:    slirp4netns
  PortDriver:       builtin
  StateDir:         /run/user/1000/dockerd-rootless
 slirp4netns:
  Version:          1.3.1
  GitCommit:        e5e368c4f5db6ae75c2fce786e31eef9da6bf236
```

### docker info

```bash
Client:
 Version:    27.5.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.23.0
    Path:     /nix/store/abz8nglshj13ffgqlsi0ww9ykdhmrksy-docker-plugins/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  2.36.0
    Path:     /nix/store/abz8nglshj13ffgqlsi0ww9ykdhmrksy-docker-plugins/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 1
 Server Version: dev
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 CDI spec directories:
  /etc/cdi/
  /var/run/cdi/
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: refs/tags/v2.0.1
 runc version: 
 init version: N/A
 Security Options:
  seccomp
   Profile: builtin
  rootless
  cgroupns
 Kernel Version: 6.12.28
 Operating System: NixOS 25.05 (Warbler)
 OSType: linux
 Architecture: x86_64
 CPUs: 128
 Total Memory: 251.5GiB
 Name: hulk
 ID: bbbc9648-8f2b-4c0e-ae85-bd1e30d9669e
 Docker Root Dir: /home/ereslibre/.local/share/docker
 Debug Mode: true
  File Descriptors: 29
  Goroutines: 56
  System Time: 2025-05-15T11:56:19.952862732+02:00
  EventsListeners: 0
 Username: ereslibre
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by ereslibre**
Fixes: https://github.com/moby/moby/issues/49989

**- What I did**

Register the CDI driver before the daemon starts, trying to restore containers, some of them which might depend on the CDI driver to be already registered.

**- How I did it**

I updated the logic to register the CDI driver before any container is restored when the daemon is started, so that when that happens, the CDI driver is present.

**- How to verify it**

**- Human readable description for the release notes**

```markdown changelog
Fix containers with `--restart always` policy using CDI devices failing to start on daemon restart.
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by vvoland — APPROVED** [review]
LGTM, thanks!

For a follow up -- perhaps we should consider a centralized function to register all available device drivers.
Currently it's a bit inconsistent because the `nvidia` driver initializes itself via `func init` and the CDI is registered manually (because it needs a feature flag check).

File: cmd/dockerd/daemon.go [hunk 1]
```diff
@@ -244,6 +244,17 @@ func (cli *daemonCLI) start(ctx context.Context) (err error) {
...
+	// Note that CDI is not inherently linux-specific, there are some linux-specific assumptions / implementations in the code that
+	// queries the properties of device on the host as well as performs the injection of device nodes and their access permissions into the OCI spec.
+	//
+	// In order to lift this restriction the following would have to be addressed:
+	// - Support needs to be added to the cdi package for injecting Windows devices: https://tags.cncf.io/container-device-interface/issues/28
+	// - The DeviceRequests API must be extended to non-linux platforms.
+	if runtime.GOOS == "linux" && cli.Config.Features["cdi"] {
+		daemon.RegisterCDIDriver(cli.Config.CDISpecDirs...)
+	}
+
```
Comment (thaJeztah) [inline cmd/dockerd/daemon.go:257]: Change looks good to me; we should probably look at rolling this into `daemon.NewDaemon`, as there's some validation and setup steps being performed in that function as well (and _possibly_ adjusting of config options), so possibly this should go after that; https://github.com/moby/moby/blob/b87aecc50adb5af7c79b9fcffde0fed79735b115/daemon/daemon.go#L763-L783

**Review by thaJeztah — APPROVED** [review]
LGTM
