### PR TITLE
Carry #35333: Devicemapper: ignore Nodata errors when delete thin device

### LINKED ISSUE #34463: Error response from daemon: devicemapper failed to remove the rootFS for <id> : devicemapper : Error running DeleteDevice dm_task_run failed
Pinging @rhvgoyal @thaJeztah 

**Details:**
`OS`- CentOS Linux release 7.3.1611 (Core) 
`uname -a` : 3.10.0-514.26.2.el7.x86_64 

_**Docker version:**_
```
Client:
Version:      17.06.0-ce
API version:  1.30
Go version:   go1.8.3
Git commit:   02c1d87
Built:        Fri Jun 23 21:20:36 2017
OS/Arch:      linux/amd64

Server:
Version:      17.06.0-ce
API version:  1.30 (minimum version 1.12)
Go version:   go1.8.3
Git commit:   02c1d87
Built:        Fri Jun 23 21:21:56 2017
OS/Arch:      linux/amd64
```

**_Docker info_**:
```
Containers: 12
Running: 0
Paused: 0
Stopped: 12
Images: 14
Server Version: 17.06.0-ce
Storage Driver: devicemapper
Pool Name: docker-8:3-396359-pool
Pool Blocksize: 65.54kB
Base Device Size: 10.74GB
Backing Filesystem: xfs
Data file: /dev/loop0
Metadata file: /dev/loop1
Data Space Used: 5.607GB
Data Space Total: 107.4GB
Data Space Available: 7.345GB
Metadata Space Used: 7.221MB
Metadata Space Total: 2.147GB
Metadata Space Available: 2.14GB
Thin Pool Minimum Free Space: 10.74GB
Udev Sync Supported: true
Deferred Removal Enabled: false
Deferred Deletion Enabled: false
Deferred Deleted Device Count: 0
Data loop file: /var/lib/docker/devicemapper/devicemapper/data
Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: bridge host macvlan null overlay
Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
NodeID: q32938pqmetuskqk09afoyrrl
Is Manager: false
Node Address: 192.168.10.108
Manager Addresses:
  192.168.41.53:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
seccomp
  Profile: default
Kernel Version: 3.10.0-514.26.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 2.781GiB
Name: localhost.localdomain
ID: KQAH:NHUS:NOKK:KKKL:P62B:H5PC:NT6S:RSOG:D36X:UOUJ:JKW2:MSA2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: 2606
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
127.0.0.0/8
Live Restore Enabled: false
```

**Problem:**
There are four containers in this node which are dead. I am unable to remove them. 

Details:
docker container 1

`docker rm -f <container_id>` is not working
docker container 2

I browsed through GitHub issues for any solution. Instead I got an impression that this is not an error but a serious bug which is rearing its head again and again. 

Help needed in resolving this issue.

Regards
Aditya

### PR DESCRIPTION
**Pull request by yongtang**
**- What I did**

This fix carries #35333 and adds the needed test to cover the changes.

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

This fix fixes #34463. This fix closes #35333.

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks @yongtang!

ping @kolyshkin @vieux

File: pkg/devicemapper/devmapper.go [hunk 1]
```diff
@@ -67,12 +67,14 @@ var (
...
 )
 
 var (
-	dmSawBusy  bool
-	dmSawExist bool
-	dmSawEnxio bool // No Such Device or Address
+	dmSawBusy    bool
+	dmSawExist   bool
+	dmSawEnxio   bool // No Such Device or Address
+	dmSawEnoData bool // No data available
```
Comment (dnephin) [inline pkg/devicemapper/devmapper.go]: Could these be returned from `task.run()` instead of globals?

File: integration/container/stop_test.go [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+)
+
+func TestDeleteDevicemapper(t *testing.T) {
+	skip.IfCondition(t, testEnv.DaemonInfo.Driver != "devicemapper")
+
+	defer setupTest(t)()
+	client := request.NewAPIClient(t)
+	ctx := context.Background()
+
+	foo, err := client.ContainerCreate(ctx,
```
Comment (dnephin) [inline integration/container/stop_test.go]: Does this change actually need a container to exist, or could this be a unit test in `pkg/devicemapper` ?

File: pkg/devicemapper/devmapper.go (hunk 1 above)
Comment (yongtang) [reply pkg/devicemapper/devmapper.go]: @dnephin The value is passed through a log callback:
https://github.com/moby/moby/blob/master/pkg/devicemapper/devmapper_log.go#L42-L56

which is wrapped in cgo:
https://github.com/moby/moby/blob/master/pkg/devicemapper/devmapper_wrapper.go#L13

I think it might be difficult to return from `task.run()`

File: integration/container/stop_test.go (hunk 2 above)
Comment (yongtang) [reply integration/container/stop_test.go]: @dnephin The PR tries to fix the issue where an out-of-sync deletion of pool device will not prevent container deletion from returning an error. Though I am not very familiar with this part of the code. There is no existing unit test in `pkg/devicemapper` so not sure if it is possible to created a unit test easily.

File: pkg/devicemapper/devmapper.go (hunk 1 above)
Comment (dnephin) [reply pkg/devicemapper/devmapper.go]: ok, yes that does seem like it would require a much bigger change to fix.

**Comment by kolyshkin** [comment]
As I said in #35333 
> Looks a bit kludgy, but I can't think of anything better, therefore LGTM

LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🌮

**Review by thaJeztah — APPROVED** [review]
LGTM
