### PR TITLE
Fix restartpolicy max-retry validation

### LINKED ISSUE #29035: docker 1.13 breaks restart policy: maximum restart count must be a positive integer
**Description**
**Steps to reproduce the issue:**
1. Get docker v1.13 on Docker for Mac
2. `docker run -d --restart=on-failure nginx`

**Describe the results you received:**
```
docker: Error response from daemon: maximum restart count must be a positive integer.
See 'docker run --help'.
```

**Describe the results you expected:**
* Container is started without a problem.

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.13.0-rc2
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   1f9b3ef
 Built:        Wed Nov 23 17:40:58 2016
 OS/Arch:      darwin/amd64

Server:
 Version:             1.13.0-rc2
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          1f9b3ef
 Built:               Wed Nov 23 17:40:58 2016
 OS/Arch:             linux/amd64
 Experimental:        true
```

**Output of `docker info`:**

http://pastebin.com/raw/ckKsKLNh

**Additional environment details (AWS, VirtualBox, physical, etc.):**
* Docker for Mac
* The same thing works with docker v1.12.

### PR DESCRIPTION
**Pull request by thaJeztah**
the restart policy validation was moved from
the client to the daemon in 94e95e4711643640701bd614902e75a2d01f12c5 (https://github.com/docker/docker/pull/24073)

As part of that change, retry-counts < 1 were marked as "invalid".
However, the default is 0 (unlimited), causing

    docker run -d --restart=on-failure nginx

To fail.

This changes the validation to only invalidate retry-counts < 0.

A test was added, and other tests renamed to allow running just these tests :)

fixes https://github.com/docker/docker/issues/29035

### CODE REVIEW

**Comment by cpuguy83** [comment]
Perhaps a CLI test as well?

**Comment by thaJeztah** [comment]
added CLI test, and updated the error message, PTAL

File: integration-cli/docker_cli_restart_test.go [hunk 1]
```diff
@@ -74,15 +74,15 @@ func (s *DockerSuite) TestRestartWithVolumes(c *check.C) {
 }
 
 func (s *DockerSuite) TestRestartPolicyNO(c *check.C) {
-	out, _ := dockerCmd(c, "run", "-d", "--restart=no", "busybox", "false")
+	out, _ := dockerCmd(c, "create", "--restart=no", "busybox")
```
Comment (thaJeztah) [inline integration-cli/docker_cli_restart_test.go]: These tests only did an inspect on the container-config, so no "run" was needed. I changed to "create" to save some time, but happy to change back if you don't agree with changing this

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by LK4D4** [comment]
LGTM
