### PR TITLE
daemon: also ensureDefaultApparmorProfile in exec path

### LINKED ISSUE #31733: Daily Apt Activities destroyed apparmor profile
**Description**

Last night, on 2 separate swarms, exec commands started failing as well as simple kill or stop commands.
After investigating it seemed this coincided with the daily apt schedule (I have unattended upgrades installed and set to security upgrades only).

The syslogs are below
 

**Steps to reproduce the issue:**
Not sure.

**Describe the results you received:**

Could not run `docker exec` or `docker kill` for any container on that host.

```
Mar 10 04:26:28 aws-acme-qa-node-1 systemd[1]: Starting Daily apt activities...
Mar 10 04:26:36 aws-acme-qa-node-1 bash[3074]:     2017/03/10 04:26:36 [WARN] agent: Check 'docker-daemon-status' is now warning
Mar 10 04:26:39 aws-acme-qa-node-1 systemd[1]: Reloading.
Mar 10 04:26:40 aws-acme-qa-node-1 systemd[1]: Started ACPI event daemon.
Mar 10 04:26:40 aws-acme-qa-node-1 systemd[1]: Reloading LSB: AppArmor initialization.
Mar 10 04:26:40 aws-acme-qa-node-1 apparmor[29393]:  * Reloading AppArmor profiles
Mar 10 04:26:40 aws-acme-qa-node-1 kernel: [275867.857428] audit: type=1400 audit(1489120000.550:17): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="lxc-container-default" pid=29420 comm="apparmor_parser"
Mar 10 04:26:40 aws-acme-qa-node-1 kernel: [275867.857849] audit: type=1400 audit(1489120000.550:18): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="lxc-container-default-cgns" pid=29420 comm="apparmor_parser"
Mar 10 04:26:40 aws-acme-qa-node-1 kernel: [275867.858188] audit: type=1400 audit(1489120000.550:19): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="lxc-container-default-with-mounting" pid=29420 comm="apparmor_parser"
Mar 10 04:26:40 aws-acme-qa-node-1 kernel: [275867.858497] audit: type=1400 audit(1489120000.550:20): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="lxc-container-default-with-nesting" pid=29420 comm="apparmor_parser"
Mar 10 04:26:40 aws-acme-qa-node-1 kernel: [275868.033860] audit: type=1400 audit(1489120000.726:21): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/sbin/dhclient" pid=29422 comm="apparmor_parser"
Mar 10 04:26:40 aws-acme-qa-node-1 kernel: [275868.034199] audit: type=1400 audit(1489120000.726:22): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/lib/NetworkManager/nm-dhcp-client.action" pid=29422 comm="apparmor_parser"
Mar 10 04:26:40 aws-acme-qa-node-1 kernel: [275868.034487] audit: type=1400 audit(1489120000.726:23): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/lib/NetworkManager/nm-dhcp-helper" pid=29422 comm="apparmor_parser"
Mar 10 04:26:40 aws-acme-qa-node-1 kernel: [275868.034746] audit: type=1400 audit(1489120000.726:24): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/lib/connman/scripts/dhclient-script" pid=29422 comm="apparmor_parser"
Mar 10 04:26:40 aws-acme-qa-node-1 kernel: [275868.042790] audit: type=1400 audit(1489120000.734:25): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/bin/lxc-start" pid=29431 comm="apparmor_parser"
Mar 10 04:26:40 aws-acme-qa-node-1 apparmor[29393]: Skipping profile in /etc/apparmor.d/disable: usr.sbin.rsyslogd
Mar 10 04:26:41 aws-acme-qa-node-1 apparmor[29393]:    ...done.
Mar 10 04:26:41 aws-acme-qa-node-1 systemd[1]: Reloaded LSB: AppArmor initialization.
Mar 10 04:26:42 aws-acme-qa-node-1 dockerd[1185]: time="2017-03-10T04:26:42.494473648Z" level=error msg="Error running exec in container: rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused \"apparmor failed to apply profile: no such file or directory\"\n"
Mar 10 04:26:42 aws-acme-qa-node-1 bash[3074]:     2017/03/10 04:26:42 [WARN] agent: Check 'service:aws-acme-qa-node-1:dev_acme2_api_blue_1:80' is now warning
Mar 10 04:26:42 aws-acme-qa-node-1 bash[3074]:     2017/03/10 04:26:42 [INFO] agent: Synced check 'service:aws-acme-qa-node-1:dev_acme2_api_blue_1:80'
Mar 10 04:26:43 aws-acme-qa-node-1 dockerd[1185]: time="2017-03-10T04:26:43.007927762Z" level=error msg="Error running exec in container: rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused \"apparmor failed to apply profile: no such file or directory\"\n"
Mar 10 04:26:43 aws-acme-qa-node-1 bash[3074]:     2017/03/10 04:26:43 [WARN] agent: Check 'service:aws-acme-qa-node-1:dev_acme2_api_db_blue_1:3306' is now critical
Mar 10 04:26:43 aws-acme-qa-node-1 bash[3074]:     2017/03/10 04:26:43 [INFO] agent: Synced check 'service:aws-acme-qa-node-1:dev_acme2_api_db_blue_1:3306'
Mar 10 04:26:43 aws-acme-qa-node-1 dockerd[1185]: time="2017-03-10T04:26:43.781383368Z" level=error msg="Error running exec in container: rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused \"apparmor failed to apply profile: no such file or directory\"\n"
Mar 10 04:26:43 aws-acme-qa-node-1 bash[3074]:     2017/03/10 04:26:43 [WARN] agent: Check 'service:aws-acme-qa-node-1:dev_invoice_blue_1:80' is now critical
Mar 10 04:26:43 aws-acme-qa-node-1 bash[3074]:     2017/03/10 04:26:43 [INFO] agent: Synced check 'service:aws-acme-qa-node-1:dev_invoice_blue_1:80'
Mar 10 04:26:43 aws-acme-qa-node-1 systemd[1]: Started Daily apt activities.
Mar 10 04:26:43 aws-acme-qa-node-1 systemd[1]: apt-daily.timer: Adding 7h 55min 24.955446s random time.
Mar 10 04:26:43 aws-acme-qa-node-1 systemd[1]: apt-daily.timer: Adding 6h 55min 39.256449s random time.
Mar 10 04:26:45 aws-acme-qa-node-1 kernel: [275872.915528] audit_printk_skb: 30 callbacks suppressed
Mar 10 04:26:45 aws-acme-qa-node-1 kernel: [275872.915531] audit: type=1400 audit(1489120005.606:36): apparmor="DENIED" operation="change_onexec" info="label not found" error=-2 profile="unconfined" name="docker-default" pid=29672 comm="runc:[2:INIT]"
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

The daemon is unresponsive just now and I don't want to taint the crime scene.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS

### PR DESCRIPTION
**Pull request by cyphar**
When 567ef8e7858c ("daemon: switch to 'ensure' workflow for AppArmor
profiles") was merged, it didn't correctly handle the exec path if
AppArmor profiles were deleted. Fix this by duplicating the
ensureDefaultApparmorProfile code in the exec code.

[Mikey's Window](https://flic.kr/p/fd7E3k)

Fixes #31733
Fixes: 567ef8e7858c ("daemon: switch to 'ensure' workflow for AppArmor profiles")
Signed-off-by: Aleksa Sarai <asarai@suse.de>

###### [Mikey's Window](https://flic.kr/p/fd7E3k) by [Jessica Nichole](https://www.flickr.com/photos/95831741@N06/), on Flickr

### CODE REVIEW

File: daemon/exec_linux.go [hunk 1]
```diff
@@ -23,5 +23,27 @@ func execSetPlatformOpt(c *container.Container, ec *exec.Config, p *libcontainer
 	if ec.Privileged {
 		p.Capabilities = caps.GetAllCapabilities()
 	}
+	if apparmor.IsEnabled() {
+		var appArmorProfile string
+		if c.AppArmorProfile != "" {
+			appArmorProfile = c.AppArmorProfile
+		} else if c.HostConfig.Privileged {
```
Comment (cyphar) [inline daemon/exec_linux.go]: I'm not sure if this should be `ec.Privileged` or `c.HostConfig.Privileged`.

**Comment by cyphar** [comment]
Janky failure looks unrelated, and AFAICS `#docker-maintainers` is broken so I can't trigger a rebuild.

**Comment by thaJeztah** [comment]
ping @justincormack @jessfraz ptal

File: daemon/exec_linux.go (hunk 1 above)
Comment (justincormack) [inline daemon/exec_linux.go]: Indeed, the privileged model for exec is non obvious. `hostconfig` is in fact correct - `docker exec --privileged` does not in fact disable apparmor at present.

**Review by justincormack — APPROVED** [review]

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
cherry-picked into 17.03.1 through https://github.com/docker/docker/pull/31754
