### PR TITLE
Fix issue where service healthcheck is `{}` in remote API

### LINKED ISSUE #30178: Service name dns resolve failed with null healthcheck field.
How to reproduce:

1. create an overlay network

```bash
# docker network create -d overlay lb
cl5h32nlha9wexjuxtktvda15
```

2. Use this payload to create a service named as `nginx1`:

**The field `"Healthcheck"` is a null object.**

```json
{
	"Name": "nginx1",
    "TaskTemplate": {
        "ContainerSpec": {
            "Healthcheck": {},
            "Image": "daocloud.io/nginx",
            "DNSConfig": {}
        },
        "Resources": {
            "Limits": {},
            "Reservations": {}
        },
        "RestartPolicy": {},
        "Placement": {},
        "Networks": [
            {
                "Target": "lb"
            }
        ],
        "ForceUpdate": 0
    },
    "Mode": {
        "Replicated": {}
    },
    "UpdateConfig": {
        "Parallelism": 1,
        "FailureAction": "pause",
        "MaxFailureRatio": 0
    },
    "EndpointSpec": {}
}
```

3. Find the container and try `ping nginx1`:

```bash
# docker exec -it feb787290463 bash
root@feb787290463:/# ping nginx1
ping: unknown host
root@feb787290463:/# 
```

When I remove the `"Healthcheck"` field and create another service, this would be succeeded.

I'm using docker-1.13.0-rc7.

Here is the docker info:

```bash
# docker info
Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 104
Server Version: 1.13.0-rc7
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 530
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: 8buhei2zqiuw3rs15v44805bo
 Is Manager: true
 ClusterID: arc4aaprjo65pdxj6f1g8qieh
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 10
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.1.137
 Manager Addresses:
  192.168.1.137:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-59-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953 GiB
Name: dce2-dev-1
ID: QULS:TLXH:5M6M:CZJH:CTNP:USWX:Y3Y6:F3YY:OOPG:PB23:5LB6:4RUC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 173
 Goroutines: 317
 System Time: 2017-01-16T13:17:42.598820428+08:00
 EventsListeners: 3
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 0.0.0.0/0
 127.0.0.0/8
Registry Mirrors:
 http://m.***.io
Live Restore Enabled: false
```

Any help would be appreciated.

### PR DESCRIPTION
**Pull request by yongtang**
**- What I did**

This fix tries to address the issue raised in #30178 where service healthcheck is `{}` in remote API will result in dns resolve failure.

The reason was that when service healthcheck is `{}`, `activateServiceBinding()` is not called.

**- How I did it**

This fix fixes the issue.

**- How to verify it**

An integration test has been added.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

unnamed

This fix fixes #30178.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by aaronlehmann** [comment]
ping @dongluochen

File: daemon/cluster/executor/container/controller.go [hunk 1]
```diff
@@ -205,20 +205,14 @@ func (r *controller) Start(ctx context.Context) error {
 	}
 
 	// no health check
-	if ctnr.Config == nil || ctnr.Config.Healthcheck == nil {
+	if ctnr.Config == nil || ctnr.Config.Healthcheck == nil || len(ctnr.Config.Healthcheck.Test) == 0 || ctnr.Config.Healthcheck.Test[0] == "NONE" {
```
Comment (aaronlehmann) [inline daemon/cluster/executor/container/controller.go]: Will this have the right behavior if `Test` has multiple items, and one of them is not `NONE`?

Comment (dongluochen) [inline daemon/cluster/executor/container/controller.go]: The first item is `Test` type with values "NONE", "CMD" or "CMD-SHELL", where "NONE" means no healthcheck.

**Comment by dongluochen** [comment]
sgtm

**Comment by LK4D4** [comment]
@yongtang would you mind to rebase? Thanks!

**Comment by yongtang** [comment]
Thanks @LK4D4. Rebased.

**Comment by LK4D4** [comment]
@yongtang I think experimental failure is sorta real. Could you check please?

**Comment by LK4D4** [comment]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by thaJeztah** [comment]
cherry-picked into 17.03.1 through https://github.com/docker/docker/pull/31754
