### PR TITLE
Verify NetworkingConfig to make sure EndpointSettings is not nil

### LINKED ISSUE #35752: bad response from Docker engine with NetworkConfig EndpointSettings is nil
Originally filed in https://github.com/docker/for-mac/issues/2300, but moved to here as it's a problem within Moby.

**Description**

When a container creation request provides an `EndpointSettings` value of nil in the `NetworkConfig.EndpointConfig`, the API will respond with `bad response from Docker engine`. Either this error should not be happening in the first place, or an error that is more clear should be returned.

**Steps to reproduce the issue:**

A minimum example that will exhibit the problem is the following client code:

```go
package main

import (
	"context"
	"log"

	"github.com/moby/moby/client"

	"github.com/docker/docker/api/types"
	"github.com/docker/docker/api/types/container"
	"github.com/docker/docker/api/types/network"
)

func main() {
	client, err := client.NewEnvClient()
	if err != nil {
		log.Fatal(err)
	}
	networkName := "mynetwork"
	endpoints := make(map[string]*network.EndpointSettings, 1)
	endpoints[networkName] = nil
	// If the above line is replaced with the following line, everything works fine.
	// endpoints[networkName] = &network.EndpointSettings{}
	resp, err := client.ContainerCreate(
		context.TODO(),
		&container.Config{
			Image: "myimage",
		},
		nil,
		&network.NetworkingConfig{
			EndpointsConfig: endpoints,
		},
		"",
	)
	if err != nil {
		log.Fatal(err)
	}
	if err := client.ContainerStart(context.TODO(), resp.ID, types.ContainerStartOptions{}); err != nil {
		log.Fatal(err)
	}
}
```

**Describe the results you received:**
- A container is created, and when attempting to start it an engine error is returned.

**Describe the results you expected:**
- A container is created and started.

**Output of `docker version`:** 

```
lient:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 9
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.49-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: Z6L4:JUOG:LGE3:VTWQ:TXTA:545D:33JF:R4EQ:NIN5:NVXF:FLDM:NWMG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 19
 Goroutines: 32
 System Time: 2017-12-09T01:38:05.1673997Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### PR DESCRIPTION
**Pull request by yongtang**
**- What I did**

This fix tries to address the issue raised in #35752 where container start will trigger a crash if EndpointSettings is nil.

**- How I did it**

This fix adds the validation to make sure EndpointSettings != nil

**- How to verify it**

A unit test has been added.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

baby-animals-animal-ocean-whale-nature-image-background

This fix fixes #35752.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

File: daemon/create.go [hunk 1]
```diff
@@ -322,8 +322,11 @@ func verifyNetworkingConfig(nwConfig *networktypes.NetworkingConfig) error {
 		return nil
 	}
 	if len(nwConfig.EndpointsConfig) == 1 {
-		for _, v := range nwConfig.EndpointsConfig {
-			if v != nil && v.IPAMConfig != nil {
+		for k, v := range nwConfig.EndpointsConfig {
+			if v == nil {
+				return errors.Errorf("no EndpointSettings for %s", k)
```
Comment (cpuguy83) [inline daemon/create.go]: Please wrap this in an "errdefs.InvalidParameter" error.

**Review by cpuguy83 — CHANGES_REQUESTED** [review]

**Comment by yongtang** [comment]
Thanks @cpuguy83. The PR has been updated. Please take a look.

File: daemon/create_test.go [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+// Test case for 35752
+func TestVerifyNetworkingConfig(t *testing.T) {
+	name := "mynet"
+	endpoints := make(map[string]*network.EndpointSettings, 1)
+	endpoints[name] = nil
+	nwConfig := &network.NetworkingConfig{
+		EndpointsConfig: endpoints,
+	}
+	err := verifyNetworkingConfig(nwConfig)
+	assert.EqualError(t, err, "no EndpointSettings for mynet")
```
Comment (cpuguy83) [inline daemon/create_test.go]: Can you assert true on `errdefs.IsInvalidParameter`?

**Review by boaz0 — APPROVED** [review]
LGTM 👍

File: daemon/create_test.go (hunk 2 above)
Comment (yongtang) [reply daemon/create_test.go]: Thanks @cpuguy83  The PR has been updated.

File: daemon/create_test.go [hunk 3]
```diff
@@ -0,0 +1,22 @@
...
+func TestVerifyNetworkingConfig(t *testing.T) {
+	name := "mynet"
+	endpoints := make(map[string]*network.EndpointSettings, 1)
+	endpoints[name] = nil
+	nwConfig := &network.NetworkingConfig{
+		EndpointsConfig: endpoints,
+	}
+	err := verifyNetworkingConfig(nwConfig)
+	assert.True(t, errdefs.IsInvalidParameter(err))
+	assert.EqualError(t, err, "no EndpointSettings for mynet")
```
Comment (cpuguy83) [inline daemon/create_test.go]: Sorry, I'd prefer to remove this assertion since error messages can change and should not be relied upon.
If you want to check that the cause is a specific type (or something defined at the package level) then that'd be ok.

Comment (yongtang) [reply daemon/create_test.go]: Thanks @cpuguy83. Having a specific error type but loose the restriction on error message itself makes sense in many situations. The PR has been updated.

**Review by fcrisciani — APPROVED** [review]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM
