### PR TITLE
Unmount recursively to unmount volumes

### LINKED ISSUE #17823: Unable to remove filesystem [...]/mqueue: device or resource busy
We have been trying to figure out some cases where users get this error message when using our product, weave, with Docker 1.9.  This is a repro without any weave containers - just alpine - so the steps may seem a little weird.

`docker version`:
````
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64
````

`docker info`:
````
Containers: 1
Images: 83
Server Version: 1.9.0
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-28-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 3.614 GiB
Name: host5
ID: Y2J3:4YXQ:PJZB:SU2G:TVQG:WMS4:JOAS:OOC2:7RVB:ONPP:NR3Q:V3ZT
WARNING: No swap limit support
````

`uname -a`:
````
Linux host5 3.19.0-28-generic #30~14.04.1-Ubuntu SMP Tue Sep 1 09:32:55 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
````

Environment details: GCE VM

How reproducible: 100%

Steps to Reproduce:
````
$ docker run --name=c1 -v /var/lib/docker/containers:/var/lib/docker/containers -d alpine /bin/sh
e8f88525360b1b74d28326676e1ead149c5191f58800ab0f1e1860023fc8bd4d
$ docker run --name=c2 -td alpine /bin/sh
171ac63b59d57756a21d992ec705b96f4647d85ceaa57d155492be6a885dc437
$ docker cp c1:/etc/hosts /tmp/hosts
$ docker rm -f c2
````

Actual Results:
````
Error response from daemon: Unable to remove filesystem for 171ac63b59d57756a21d992ec705b96f4647d85ceaa57d155492be6a885dc437: remove /var/lib/docker/containers/171ac63b59d57756a21d992ec705b96f4647d85ceaa57d155492be6a885dc437/mqueue: device or resource busy
Error: failed to remove containers: [c2]
````

Expected Results:
````
c2
````

Additional info:

This repro is using `overlayfs`; we have seen the same message using `aufs`

Reference https://github.com/weaveworks/weave/issues/1647, https://github.com/weaveworks/weave/issues/1652

### PR DESCRIPTION
**Pull request by rhvgoyal**
Fixes #17823 

Bind mounted volumes are bind mounted recursively. That means any mounts
under top mount also becomes visible under destination mount point. And
that also means that simple umount(dest) will fail as it has other mount
points underneath it. Instead use utitlity "umount -R dest" for recursively
unmounting all the mounts under dest.

Signed-off-by: Vivek Goyal vgoyal@redhat.com

### CODE REVIEW

**Comment by rhvgoyal** [comment]
@cpuguy83 Does this look like a reasonable solution?

**Comment by rhvgoyal** [comment]
@bboreham Can you please test this patch and see if it solves your issue.

**Comment by rhvgoyal** [comment]
fixed golint issue and pushed again.

File: pkg/system/syscall_unix.go [hunk 1]
```diff
@@ -2,10 +2,23 @@
...
 // Unmount is a platform-specific helper function to call
 // the unmount syscall.
 func Unmount(dest string) error {
 	return syscall.Unmount(dest, 0)
 }
+
+// UnmountRecursive is a platform-specific helper function to call
+// the umount -R command provided by util-linux package.
+func UnmountRecursive(dest string) error {
+	if out, err := exec.Command("umount", "-R", dest).CombinedOutput(); err != nil {
```
Comment (LK4D4) [inline pkg/system/syscall_unix.go]: I think we used `MNT_DETACH` before for such task...

**Comment by rhvgoyal** [comment]
@crosbymichael @LK4D4 @cpuguy83 Pushed new version doing lazy unmount. This this look better.

**Comment by crosbymichael** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Comment by anusha-ragunathan** [comment]
LGTM

**Comment by cpuguy83** [comment]
@rhvgoyal Thanks for looking into this!

**Comment by rade** [comment]
any chance to get this into 1.9.2?

**Comment by LK4D4** [comment]
@rade sure, if there will be 1.9.2, why not

**Comment by thaJeztah** [comment]
@rade note that it's not been decided yet if we will actually be releasing a 1.9.2 release, we use the milestone to collect issues that may make sense in a 1.9.2 release, but it will only be released if there are serious issues that warrant a release
