### PR TITLE
Fix authorization issue - when request is denied return forbbiden exist code (403).

### LINKED ISSUE #22428: 500 response code for commands denied by auth plugin
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:38:55 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:38:55 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.11.1
Storage Driver: devicemapper
 Pool Name: docker-8:1-491769-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 305.7 MB
 Data Space Total: 107.4 GB
 Data Space Available: 39.55 GB
 Metadata Space Used: 729.1 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.99 (2015-06-20)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
 Authorization: docker-auth
Kernel Version: 4.2.0-35-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 488.9 MiB
Name: vagrant-ubuntu-wily-64
ID: RWVA:C37Z:CVFE:2BEA:U4B5:5DKD:FZ43:74KW:A5XJ:HW5K:6CDC:P5IH
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 14
 Goroutines: 30
 System Time: 2016-04-29T21:01:09.169890289Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Vagrant-created VirtualBox VM

**Steps to reproduce the issue:**
1. Enable an auth plugin
2. Perform a request that is denied by the auth plugin
3. Check the response code

**Describe the results you received:**
```
curl -v -H "Content-Type: application/json" -X POST -d @bad-command.json --unix-socket /var/run/docker.sock http:/containers/create
*   Trying /var/run/docker.sock...
* Connected to http (/var/run/docker.sock) port 80 (#0)
> POST /containers/create HTTP/1.1
> Host: http
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 1645
> Expect: 100-continue
> 
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Fri, 29 Apr 2016 20:46:31 GMT
< Content-Length: 183
< 
authorization denied by plugin docker-auth: <Error message>
```

**Describe the results you expected:**
Expected the status code to be a 403 Forbidden

**Additional information you deem important (e.g. issue happens only occasionally):**
According to the [auth plugin docs](https://docs.docker.com/engine/extend/plugins_authorization/#response-authorization), it looks like it should be possible to modify the response code. However, the relevant fields don't seem to actually be in the code base. (e.g., ModifiedStatusCode appears in the docs, but [not the code](https://github.com/docker/docker/search?q=ModifiedStatusCode&type=Code&utf8=%E2%9C%93)).

### PR DESCRIPTION
**Pull request by liron-l**
**\- What I did**
When request is rejected by authorization plugin, replace status code 500 (internal server error) with 403 (forbidden). Based on discussion in #2242

**\- How I did it**
Used `errors.NewErrorWithStatusCode` when authorization plugin rejects requests

**\- How to verify it**
New integration test for API

**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**
- Fix outdated documentation on response modification in authorization
- Return 403 (forbidden) when request is denied in authorization flows
  (including integration test)
- Fix #22428

Signed-off-by: Liron Levin liron@twistlock.com

### CODE REVIEW

File: pkg/authorization/authz.go [hunk 1]
```diff
@@ -85,7 +86,7 @@ func (ctx *Ctx) AuthZRequest(w http.ResponseWriter, r *http.Request) error {
 		}
 
 		if !authRes.Allow {
-			return fmt.Errorf("authorization denied by plugin %s: %s", plugin.Name(), authRes.Msg)
+			return errors.NewErrorWithStatusCode(fmt.Errorf("authorization denied by plugin %s: %s", plugin.Name(), authRes.Msg), http.StatusForbidden)
```
Comment (thaJeztah) [inline pkg/authorization/authz.go]: Perhaps create a new helper function for this? (`NewRequestForbiddenError`?) Similar to https://github.com/docker/docker/blob/3d13fddd2bc4d679f0eaa68b0be877e5a816ad53/errors/errors.go#L37-L41

(also two other locations may need to be updated then; https://github.com/docker/docker/blob/7fd53f7c711474791ce4292326e0b1dc7d4d6b0f/daemon/network.go#L100 and https://github.com/docker/docker/blob/7fd53f7c711474791ce4292326e0b1dc7d4d6b0f/daemon/network.go#L224)

File: integration-cli/docker_cli_authz_unix_test.go [hunk 2]
```diff
@@ -272,6 +275,27 @@ func (s *DockerAuthzSuite) TestAuthZPluginDenyRequest(c *check.C) {
...
 }
 
+// TestAuthZPluginApiDenyResponse validates that when authorization plugin deny the request, the status code is forbidden
+func (s *DockerAuthzSuite) TestAuthZPluginApiDenyResponse(c *check.C) {
+	err := s.d.Start("--authorization-plugin=" + testAuthZPlugin)
+	c.Assert(err, check.IsNil)
+	s.ctrl.reqRes.Allow = false
+	s.ctrl.resRes.Msg = unauthorizedMessage
+
+	daemonUrl, err := url.Parse(s.d.sock())
```
Comment (thaJeztah) [inline integration-cli/docker_cli_authz_unix_test.go]: Looks like golint is complaining here; this should be `daemonURL`;

```
10:56:18 ---> Making bundle: validate-lint (in bundles/1.12.0-dev/validate-lint)
10:56:18 Errors from golint:
10:56:18 integration-cli/docker_cli_authz_unix_test.go:285:2: var daemonUrl should be daemonURL
10:56:18 
10:56:18 Please fix the above errors. You can test via "golint" and commit the result.
```

**Comment by liron-l** [comment]
Thanks @thaJeztah, fixed both issues (also refactored network errors to use `NewRequestForbiddenError`)

**Comment by thaJeztah** [comment]
Thanks @liron-l  - sorry, I just thought of this, but can you move the documentation changes to a separate PR? I have a cherry-pick PR to update the docs and having a separate PR makes it easier for me to cherry-pick just those changes (https://github.com/docker/docker/pull/22421) in case we do an update of the documentation before the next release

**Comment by thaJeztah** [comment]
owww, erm.. looks like using the "errors" in a package wasn't a good idea :cry: :blush:

```
11:49:23 ---> Making bundle: validate-pkg (in bundles/1.12.0-dev/validate-pkg)
11:49:24 These files import internal code: (either directly or indirectly)
11:49:24  - pkg/authorization/authz.go imports github.com/docker/docker/errors
```

**Comment by liron-l** [comment]
Thanks @thaJeztah, removed the reference from `pkg`, but kept the one in `daemon`.
I've also removed the documentation section and will update those in a separate PR (after this PR will pass)

**Comment by thaJeztah** [comment]
oh looks like there's a gofmt issue now (well, at least we have managed to trigger all checks 😜)

```
12:37:25 ---> Making bundle: validate-gofmt (in bundles/1.12.0-dev/validate-gofmt)
12:37:25 These files are not properly gofmt'd:
12:37:25  - pkg/authorization/authz.go
12:37:25 
12:37:25 Please reformat the above files using "gofmt -s -w" and commit the result.
```

File: pkg/authorization/authz.go [hunk 3]
```diff
@@ -163,3 +163,16 @@ func headers(header http.Header) map[string]string {
 	}
 	return v
 }
+
+// authorizationError represents an authorization deny error
+type authorizationError struct {
+	error
+}
+
+func (e authorizationError) HTTPErrorStatusCode() int {
```
Comment (thaJeztah) [inline pkg/authorization/authz.go]: Should probably be documented, as it's an exported function;

    // HTTPErrorStatusCode returns a status code.

**Comment by liron-l** [comment]
Thanks @thaJeztah , I think everything is fixed now.

**Comment by thaJeztah** [comment]
Yes, looks okay now. win2lin failure is not related

LGTM

**Comment by lblackstone** [comment]
Minor nit, but the commit message still references the doc change which got pulled into a separate PR.

**Comment by liron-l** [comment]
Thanks @lblackstone, I've updated the commit message.

**Comment by aaronlehmann** [comment]
LGTM
