### PR TITLE
Revendor Microsoft/go-winio for 8gB file fix when importing or committing image layers

### LINKED ISSUE #40444: Docker fails to create Windows Containers with a file larger than 8gB
**Description**

When trying to create a container on Windows with a file larger than 8gB (8,589,934,592 bytes of random data is my test-case), Docker fails to commit the layer, giving an error along the lines of [`re-exec error: exit status 1: output: write \\?\C:\ProgramData\docker\tmp\hcs816749287\Files\UnrealEngine\LocalBuilds\Engine\Windows\Engine\Plugins\Experimental\BlastPlugin\Binaries\Win64\UE4Editor-BlastAuthoring.pdb: There is not enough space on the disk.`](https://github.com/adamrehn/ue4-docker/issues/63#issuecomment-580964306) or [`hcsshim::ImportLayer - failed failed in Win32: The system cannot find the path specified. (0x3)`](https://github.com/adamrehn/ue4-docker/issues/63#issuecomment-580585672).

**Steps to reproduce the issue:**

For better debug logging:
* Set a system env-var `DOCKER_WINDOWSFILTER_NOREEXEC=true`
* Ensure dockerd has both debug enabled, and log-level debug set:
```
  "debug": true,
  "log-level": "debug",
```
* Start/restart dockerd.exe with those settings.

1. Given an 8gB file, e.g.,
```powershell
$writer = [System.IO.File]::OpenWrite('8gfile')
$random = new-object Random
$blockSize = 1073741824
$bytes = new-object byte[] $blockSize
for ($i=0; $i -lt 8; $i++)
{
 $random.NextBytes($bytes)
 $writer.Write($bytes, 0, $blockSize)
}
$writer.Close()
```
2. And the following Dockerfile
```
FROM mcr.microsoft.com/windows/nanoserver:1909
COPY 8gfile 8gfile
```
3. `docker build .`

Alternative repro, using the [`ue4-docker` tool](https://github.com/adamrehn/ue4-docker/issues/63#issuecomment-580585672):
1. Given Python 3 (or a virtual env)
2. `pip install ue4-docker`
3. `ue4-docker diagnostics 8gig`

This runs the file-creation script inside the container, rather than using `COPY`, and triggers the same failure. See the [Dockerfile](https://github.com/adamrehn/ue4-docker/blob/master/ue4docker/dockerfiles/diagnostics/8gig/windows/Dockerfile) for reference.

**Describe the results you received:**

The CLI may simply report `archive/tar: invalid tar header` and terminate.

Errors as described above in the logs, on the various times I've tried. There's a lot of diagnostics at https://github.com/adamrehn/ue4-docker/issues/44 where I originally hit the issue with Docker EE 18.09.5 for Windows Server.

The current log output for the `COPY` stage in my repro looks like this, with blank lines around the `hcsshim::ImportLayer` span which is failing for some reason.
```
[09:27:11.061][WindowsDaemon     ][Info   ] debug: [BUILDER] Cache miss: [cmd /S /C #(nop) COPY file:6eacbaee636d1db8e156690cfb8319f516a3dc7aed07881788d2b01bc5f63c42 in 8gfile ]
[09:27:11.061][WindowsDaemon     ][Info   ] debug: hcsshim::GetLayerMountPath [path=C:\ProgramData\Docker\windowsfilter\3c5bfe2daef2c14ab2185e679ccf26891f306db3c8af06cd6a0b06eecc3a0f1f]
[09:27:11.061][WindowsDaemon     ][Info   ] debug: Calling proc (1) [path=C:\ProgramData\Docker\windowsfilter\3c5bfe2daef2c14ab2185e679ccf26891f306db3c8af06cd6a0b06eecc3a0f1f]
[09:27:11.062][WindowsDaemon     ][Info   ] debug: Calling proc (2) [path=C:\ProgramData\Docker\windowsfilter\3c5bfe2daef2c14ab2185e679ccf26891f306db3c8af06cd6a0b06eecc3a0f1f]
[09:27:11.062][WindowsDaemon     ][Info   ] debug: hcsshim::GetLayerMountPath - succeeded [mountPath=C:\ProgramData\Docker\windowsfilter\3c5bfe2daef2c14ab2185e679ccf26891f306db3c8af06cd6a0b06eecc3a0f1f path=C:\ProgramData\Docker\windowsfilter\3c5bfe2daef2c14ab2185e679ccf26891f306db3c8af06cd6a0b06eecc3a0f1f]
[09:27:11.062][WindowsDaemon     ][Info   ] debug: hcsshim::CreateScratchLayer [path=C:\ProgramData\Docker\windowsfilter\3c0a616503a2de2ed418f49aabcf18e54e7809d5340a0c859f877c45a5c6c9bc]
[09:27:11.062][WindowsDaemon     ][Info   ] debug: hcsshim::NameToGuid [name=3c5bfe2daef2c14ab2185e679ccf26891f306db3c8af06cd6a0b06eecc3a0f1f]
[09:27:11.062][WindowsDaemon     ][Info   ] debug: hcsshim::NameToGuid - succeeded [name=3c5bfe2daef2c14ab2185e679ccf26891f306db3c8af06cd6a0b06eecc3a0f1f guid=9a520dd8-e003-5ac9-aafa-90282d69bead]
[09:27:11.068][WindowsDaemon     ][Info   ] debug: hcsshim::CreateScratchLayer - succeeded [path=C:\ProgramData\Docker\windowsfilter\3c0a616503a2de2ed418f49aabcf18e54e7809d5340a0c859f877c45a5c6c9bc]
[09:27:11.072][WindowsDaemon     ][Info   ] debug: WindowsGraphDriver Get() id 3c0a616503a2de2ed418f49aabcf18e54e7809d5340a0c859f877c45a5c6c9bc mountLabel 
[09:27:11.073][WindowsDaemon     ][Info   ] debug: hcsshim::ActivateLayer [path=C:\ProgramData\Docker\windowsfilter\3c0a616503a2de2ed418f49aabcf18e54e7809d5340a0c859f877c45a5c6c9bc]
[09:27:11.084][WindowsDaemon     ][Info   ] debug: hcsshim::ActivateLayer - succeeded [path=C:\ProgramData\Docker\windowsfilter\3c0a616503a2de2ed418f49aabcf18e54e7809d5340a0c859f877c45a5c6c9bc]
[09:27:11.084][WindowsDaemon     ][Info   ] debug: hcsshim::PrepareLayer [path=C:\ProgramData\Docker\windowsfilter\3c0a616503a2de2ed418f49aabcf18e54e7809d5340a0c859f877c45a5c6c9bc]
[09:27:11.085][WindowsDaemon     ][Info   ] debug: hcsshim::NameToGuid [name=3c5bfe2daef2c14ab2185e679ccf26891f306db3c8af06cd6a0b06eecc3a0f1f]
[09:27:11.086][WindowsDaemon     ][Info   ] debug: hcsshim::NameToGuid - succeeded [name=3c5bfe2daef2c14ab2185e679ccf26891f306db3c8af06cd6a0b06eecc3a0f1f guid=9a520dd8-e003-5ac9-aafa-90282d69bead]
[09:27:11.111][WindowsDaemon     ][Info   ] debug: hcsshim::PrepareLayer - succeeded [path=C:\ProgramData\Docker\windowsfilter\3c0a616503a2de2ed418f49aabcf18e54e7809d5340a0c859f877c45a5c6c9bc]
[09:27:11.111][WindowsDaemon     ][Info   ] debug: hcsshim::GetLayerMountPath [path=C:\ProgramData\Docker\windowsfilter\3c0a616503a2de2ed418f49aabcf18e54e7809d5340a0c859f877c45a5c6c9bc]
[09:27:11.111][WindowsDaemon     ][Info   ] debug: Calling proc (1) [path=C:\ProgramData\Docker\windowsfilter\3c0a616503a2de2ed418f49aabcf18e54e7809d5340a0c859f877c45a5c6c9bc]
[09:27:11.113][WindowsDaemon     ][Info   ] debug: Calling proc (2) [path=C:\ProgramData\Docker\windowsfilter\3c0a616503a2de2ed418f49aabcf18e54e7809d5340a0c859f877c45a5c6c9bc]
[09:27:11.114][WindowsDaemon     ][Info   ] debug: hcsshim::GetLayerMountPath - succeeded [path=C:\ProgramData\Docker\windowsfilter\3c0a616503a2de2ed418f49aabcf18e54e7809d5340a0c859f877c45a5c6c9bc mountPath=\\?\Volume{1c31fe35-e5f2-4858-b1bf-93dd6de9e54a}]
[09:27:11.115][WindowsDaemon     ][Info   ] debug: CopyFileWithTar(\\?\C:\ProgramData\Docker\tmp\docker-builder002875846\8gfile, \\?\Volume{1c31fe35-e5f2-4858-b1bf-93dd6de9e54a}\8gfile)
[09:27:31.096][WindowsDaemon     ][Info   ] debug: hcsshim::UnprepareLayer [path=C:\ProgramData\Docker\windowsfilter\3c0a616503a2de2ed418f49aabcf18e54e7809d5340a0c859f877c45a5c6c9bc]
[09:27:31.098][WindowsDaemon     ][Info   ] debug: hcsshim::UnprepareLayer - succeeded [path=C:\ProgramData\Docker\windowsfilter\3c0a616503a2de2ed418f49aabcf18e54e7809d5340a0c859f877c45a5c6c9bc]
[09:27:31.098][WindowsDaemon     ][Info   ] debug: hcsshim::GetLayerMountPath [path=C:\ProgramData\Docker\windowsfilter\3c5bfe2daef2c14ab2185e679ccf26891f306db3c8af06cd6a0b06eecc3a0f1f]
[09:27:31.099][WindowsDaemon     ][Info   ] debug: Calling proc (1) [path=C:\ProgramData\Docker\windowsfilter\3c5bfe2daef2c14ab2185e679ccf26891f306db3c8af06cd6a0b06eecc3a0f1f]
[09:27:31.099][WindowsDaemon     ][Info   ] debug: hcsshim::ExportLayer [exportFolderPath=C:\ProgramData\Docker\tmp\hcs621940270 path=C:\ProgramData\Docker\windowsfilter\3c0a616503a2de2ed418f49aabcf18e54e7809d5340a0c859f877c45a5c6c9bc]
[09:27:31.099][WindowsDaemon     ][Info   ] debug: hcsshim::NameToGuid [name=3c5bfe2daef2c14ab2185e679ccf26891f306db3c8af06cd6a0b06eecc3a0f1f]
[09:27:31.100][WindowsDaemon     ][Info   ] debug: Calling proc (2) [path=C:\ProgramData\Docker\windowsfilter\3c5bfe2daef2c14ab2185e679ccf26891f306db3c8af06cd6a0b06eecc3a0f1f]
[09:27:31.100][WindowsDaemon     ][Info   ] debug: hcsshim::NameToGuid - succeeded [name=3c5bfe2daef2c14ab2185e679ccf26891f306db3c8af06cd6a0b06eecc3a0f1f guid=9a520dd8-e003-5ac9-aafa-90282d69bead]
[09:27:31.100][WindowsDaemon     ][Info   ] debug: hcsshim::GetLayerMountPath - succeeded [path=C:\ProgramData\Docker\windowsfilter\3c5bfe2daef2c14ab2185e679ccf26891f306db3c8af06cd6a0b06eecc3a0f1f mountPath=C:\ProgramData\Docker\windowsfilter\3c5bfe2daef2c14ab2185e679ccf26891f306db3c8af06cd6a0b06eecc3a0f1f]
[09:27:31.100][WindowsDaemon     ][Info   ] debug: hcsshim::CreateLayer [path=C:\ProgramData\Docker\windowsfilter\e2c4b4241777c2f707a7e75fdfde0b5e17570bb92c915e1176f82e01b795a2e9 parent=3c5bfe2daef2c14ab2185e679ccf26891f306db3c8af06cd6a0b06eecc3a0f1f]
[09:27:31.101][WindowsDaemon     ][Info   ] debug: hcsshim::CreateLayer - succeeded [parent=3c5bfe2daef2c14ab2185e679ccf26891f306db3c8af06cd6a0b06eecc3a0f1f path=C:\ProgramData\Docker\windowsfilter\e2c4b4241777c2f707a7e75fdfde0b5e17570bb92c915e1176f82e01b795a2e9]
[09:27:31.102][WindowsDaemon     ][Info   ] debug: hcsshim::GetLayerMountPath [path=C:\ProgramData\Docker\windowsfilter\3c5bfe2daef2c14ab2185e679ccf26891f306db3c8af06cd6a0b06eecc3a0f1f]
[09:27:31.102][WindowsDaemon     ][Info   ] debug: Calling proc (1) [path=C:\ProgramData\Docker\windowsfilter\3c5bfe2daef2c14ab2185e679ccf26891f306db3c8af06cd6a0b06eecc3a0f1f]
[09:27:31.102][WindowsDaemon     ][Info   ] debug: Calling proc (2) [path=C:\ProgramData\Docker\windowsfilter\3c5bfe2daef2c14ab2185e679ccf26891f306db3c8af06cd6a0b06eecc3a0f1f]
[09:27:31.103][WindowsDaemon     ][Info   ] debug: hcsshim::GetLayerMountPath - succeeded [path=C:\ProgramData\Docker\windowsfilter\3c5bfe2daef2c14ab2185e679ccf26891f306db3c8af06cd6a0b06eecc3a0f1f mountPath=C:\ProgramData\Docker\windowsfilter\3c5bfe2daef2c14ab2185e679ccf26891f306db3c8af06cd6a0b06eecc3a0f1f]
[09:27:53.663][WindowsDaemon     ][Info   ] debug: hcsshim::ExportLayer - succeeded [path=C:\ProgramData\Docker\windowsfilter\3c0a616503a2de2ed418f49aabcf18e54e7809d5340a0c859f877c45a5c6c9bc exportFolderPath=C:\ProgramData\Docker\tmp\hcs621940270]

[09:27:53.669][WindowsDaemon     ][Info   ] debug: hcsshim::ImportLayer [importFolderPath=C:\ProgramData\Docker\tmp\hcs438461328 path=\\?\C:\ProgramData\Docker\windowsfilter\e2c4b4241777c2f707a7e75fdfde0b5e17570bb92c915e1176f82e01b795a2e9]
[09:27:53.669][WindowsDaemon     ][Info   ] debug: hcsshim::NameToGuid [name=3c5bfe2daef2c14ab2185e679ccf26891f306db3c8af06cd6a0b06eecc3a0f1f]
[09:27:53.669][WindowsDaemon     ][Info   ] debug: hcsshim::NameToGuid - succeeded [name=3c5bfe2daef2c14ab2185e679ccf26891f306db3c8af06cd6a0b06eecc3a0f1f guid=9a520dd8-e003-5ac9-aafa-90282d69bead]
[09:27:53.676][WindowsDaemon     ][Error  ] hcsshim::ImportLayer - failed failed in Win32: The system cannot find the path specified. (0x3) [path=\\?\C:\ProgramData\Docker\windowsfilter\e2c4b4241777c2f707a7e75fdfde0b5e17570bb92c915e1176f82e01b795a2e9 importFolderPath=C:\ProgramData\Docker\tmp\hcs438461328 error=hcsshim::ImportLayer - failed failed in Win32: The system cannot find the path specified. (0x3)]

[09:28:49.409][WindowsDaemon     ][Info   ] debug: Cleaning up layer e2c4b4241777c2f707a7e75fdfde0b5e17570bb92c915e1176f82e01b795a2e9: archive/tar: invalid tar header
[09:28:49.409][WindowsDaemon     ][Info   ] debug: hcsshim::GetComputeSystems - Begin Operation
[09:28:49.410][WindowsDaemon     ][Info   ] debug: HCS ComputeSystem Query [json={}]
[09:28:49.412][WindowsDaemon     ][Info   ] debug: hcsshim::GetComputeSystems - End Operation - Success
[09:28:49.421][WindowsDaemon     ][Info   ] debug: hcsshim::DestroyLayer [path=C:\ProgramData\Docker\windowsfilter\e2c4b4241777c2f707a7e75fdfde0b5e17570bb92c915e1176f82e01b795a2e9-removing]
[09:28:49.422][WindowsDaemon     ][Info   ] debug: hcsshim::DestroyLayer - succeeded [path=C:\ProgramData\Docker\windowsfilter\e2c4b4241777c2f707a7e75fdfde0b5e17570bb92c915e1176f82e01b795a2e9-removing]
[09:28:49.423][WindowsDaemon     ][Info   ] debug: hcsshim::PrepareLayer [path=C:\ProgramData\Docker\windowsfilter\3c0a616503a2de2ed418f49aabcf18e54e7809d5340a0c859f877c45a5c6c9bc]
[09:28:49.423][WindowsDaemon     ][Info   ] debug: hcsshim::NameToGuid [name=3c5bfe2daef2c14ab2185e679ccf26891f306db3c8af06cd6a0b06eecc3a0f1f]
[09:28:49.423][WindowsDaemon     ][Info   ] debug: hcsshim::NameToGuid - succeeded [name=3c5bfe2daef2c14ab2185e679ccf26891f306db3c8af06cd6a0b06eecc3a0f1f guid=9a520dd8-e003-5ac9-aafa-90282d69bead]
[09:28:49.423][WindowsDaemon     ][Info   ] debug: hcsshim::PrepareLayer - succeeded [path=C:\ProgramData\Docker\windowsfilter\3c0a616503a2de2ed418f49aabcf18e54e7809d5340a0c859f877c45a5c6c9bc]
[09:28:49.423][WindowsDaemon     ][Info   ] debug: WindowsGraphDriver Put() id 3c0a616503a2de2ed418f49aabcf18e54e7809d5340a0c859f877c45a5c6c9bc
[09:28:49.423][WindowsDaemon     ][Info   ] debug: hcsshim::UnprepareLayer [path=C:\ProgramData\Docker\windowsfilter\3c0a616503a2de2ed418f49aabcf18e54e7809d5340a0c859f877c45a5c6c9bc]
[09:28:49.424][WindowsDaemon     ][Info   ] debug: hcsshim::UnprepareLayer - succeeded [path=C:\ProgramData\Docker\windowsfilter\3c0a616503a2de2ed418f49aabcf18e54e7809d5340a0c859f877c45a5c6c9bc]
[09:28:49.424][WindowsDaemon     ][Info   ] debug: hcsshim::DeactivateLayer [path=C:\ProgramData\Docker\windowsfilter\3c0a616503a2de2ed418f49aabcf18e54e7809d5340a0c859f877c45a5c6c9bc]
[09:28:49.698][WindowsDaemon     ][Info   ] debug: hcsshim::DeactivateLayer - succeeded [path=C:\ProgramData\Docker\windowsfilter\3c0a616503a2de2ed418f49aabcf18e54e7809d5340a0c859f877c45a5c6c9bc]
[09:28:49.698][WindowsDaemon     ][Info   ] debug: hcsshim::GetComputeSystems - Begin Operation
[09:28:49.699][WindowsDaemon     ][Info   ] debug: HCS ComputeSystem Query [json={}]
[09:28:49.699][WindowsDaemon     ][Info   ] debug: hcsshim::GetComputeSystems - End Operation - Success
[09:28:49.700][WindowsDaemon     ][Info   ] debug: hcsshim::DestroyLayer [path=C:\ProgramData\Docker\windowsfilter\3c0a616503a2de2ed418f49aabcf18e54e7809d5340a0c859f877c45a5c6c9bc-removing]
[09:28:49.701][WindowsDaemon     ][Info   ] debug: hcsshim::DestroyLayer - succeeded [path=C:\ProgramData\Docker\windowsfilter\3c0a616503a2de2ed418f49aabcf18e54e7809d5340a0c859f877c45a5c6c9bc-removing]
```

**Describe the results you expected:**

The container commits its layer successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

In case it's useful, I did a diagnostics upload from Docker Desktop: 98C09E8E-11CF-4AA0-AA5F-9160DDC01FE8/20200201223719

As well as reproducing with Docker Desktop's bundled 19.03.5 Docker Engine, I was also able to reproduce the problem with a build of dockerd.exe from 513b207b002dfe070705d790326f731a803cf68d, and also reproduced it (but with less-useful logs) from 513b207b002dfe070705d790326f731a803cf68d with Microsoft/hcsshim revendored to 99f064b70e88824d6653da19160d4ae02fd35a72.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:36:50 2019
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 19.03.5
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 18363 (18362.1.amd64fre.19h1_release.190318-1202)
 Operating System: Windows 10 Pro Version 1909 (OS Build 18363.592)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.96GiB
 Name: KEITARO
 ID: NDQJ:UAVJ:AHVY:OAXE:FYZU:4JGK:FV2M:PCET:ZEBX:AGSH:7L7H:GHCF
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 27
  System Time: 2020-02-02T10:08:41.0300877+11:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by TBBle**
**- What I did**

Revendored https://github.com/microsoft/go-winio to pull https://github.com/microsoft/go-winio/pull/175, which replaces a bundled fork of archive/tar for Go 1.6 with use of vanilla archive/tar.

There's more context on this issue on https://github.com/microsoft/Windows-Containers/issues/43.

Fixes: #40444

**- How I did it**

* Implemented the test `github.com/docker/docker/integration/build TestBuildWithHugeFile` for Windows, to reproduce the issue.
* Changed the revision in vendor.conf for _github.com/Microsoft/go-winio_ to the master revision containing https://github.com/microsoft/go-winio/pull/175 (Full diff: https://github.com/microsoft/go-winio/compare/6c72808b55902eae4c5943626030429ff20f3b63...5b44b70ab3ab4d291a7c1d28afe7b4afeced0ed4, thank you @cpuguy83 for the reminder)
* Ran `vndr -whitelist=^archive/tar github.com/Microsoft/go-winio` (per the note at the end of vendor.conf)
* Ran `git checkout vendor/archive/tar` to revert vndr's deletion of _vendor/archive/tar_.
* Changed the one user of `github.com/Microsoft/go-winio/archive/tar` to use `archive/tar` instead.

**- How to verify it**

The existing unit test `github.com/docker/docker/integration/build TestBuildWithHugeFile` has been implemented for Windows Containers, and reproduces the issue.

For manual reproduction, see #40444 or the below procedure.

1. Given an 8gB file, e.g.,
```powershell
$writer = [System.IO.File]::OpenWrite('8gfile')
$random = new-object Random
$blockSize = 1073741824
$bytes = new-object byte[] $blockSize
for ($i=0; $i -lt 8; $i++)
{
 $random.NextBytes($bytes)
 $writer.Write($bytes, 0, $blockSize)
}
$writer.Close()
```
2. And the following Dockerfile
```
FROM mcr.microsoft.com/windows/nanoserver:1909
COPY 8gfile 8gfile
```
3. `docker build .`

**- Description for the changelog**

> Fix import or commit of Windows Container image layers containing files larger than 8gB by updating vendored go-winio library

**- A picture of a cute animal (not mandatory but encouraged)**

[A platypus being photogenic](https://i.imgur.com/rALUXtZ)

### CODE REVIEW

**Comment by TBBle** [comment]
TODO for self: A Windows version of `TestBuildWithHugeFile`, since that's currently skipped on Windows.

**Comment by TBBle** [comment]
It _should_ be right to go now, but the [win-RS5 CI build](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-41430/5/pipeline/55) has failed at the checkout stage, and I'm not seeing a way to reattempt it.

**Review by cpuguy83 — APPROVED** [review]
Full diff https://github.com/Microsoft/go-winio/compare/6c72808b55902eae4c5943626030429ff20f3b63...5b44b70ab3ab4d291a7c1d28afe7b4afeced0ed4

**Comment by TBBle** [comment]
I'm not clear how backporting candidacy is handled (I don't see a priority on #40444), but I think this could be a candidate for a 19.03 patch release, so we can resolve https://github.com/adamrehn/ue4-docker/issues/44 sooner.

**Comment by TBBle** [comment]
Hmm. [Test failed on Win-RS5](https://ci-next.docker.com/public/blue/rest/organizations/jenkins/pipelines/moby/branches/PR-41430/runs/6/nodes/275/log/?start=0).
```
[2020-09-09T17:32:42.803Z] === Failed
[2020-09-09T17:32:42.803Z] === FAIL: github.com/docker/docker/integration/build TestBuildWithHugeFile (600.28s)
[2020-09-09T17:32:42.803Z] panic: test timed out after 10m0s
```

Might need to increase the timeout, even a previous successful run took over 9 minutes for this test, since it's writing out an 8gB file inside the container. It's possible this could be made faster somehow, but I never worked out how during my repro efforts earlier this year.

File: integration/build/build_test.go [hunk 1]
```diff
@@ -488,15 +488,22 @@ RUN [ ! -f foo ]
...
-	skip.If(t, testEnv.OSType == "windows")
 	ctx := context.TODO()
 	defer setupTest(t)()
 
 	dockerfile := `FROM busybox
-# create a sparse file with size over 8GB
+`
+
+	if testEnv.DaemonInfo.OSType == "windows" {
+		dockerfile += `# create a file with size over 8GB
```
Comment (marosset) [inline integration/build/build_test.go:500]: `fsutil.exe file createnew bigfile.txt 8589934592` might work better here.

Comment (TBBle) [reply integration/build/build_test.go:500]: Oh, nice! That creates a sparse file by default? Definitely much better. I'll have a play tonight, that would let me revert the timeout change too, as long as it correctly reproduces the issue.

Comment (TBBle) [reply integration/build/build_test.go:500]: I just confirmed elsewhere, that cut the time for the test using `ue4-docker` in half. So I'll rework this PR to use this in the integration test instead.

Thank you @marosset.

Comment (marosset) [reply integration/build/build_test.go:500]: Actually I believe fsutil.exe file createnew will just create an empty file. You can follow up with `fsutil.exe sparse setflag bigfile.txt` and `fsutil.exe sparse setrange bigfile.txt 0 1000` to populate some of the bits.
Should still be a lot faster than powershell tho :)
https://www.geeksforgeeks.org/creating-sparse-files-on-windows-linux/

Comment (TBBle) [reply integration/build/build_test.go:500]: An empty file with a large size is file, the bug relates to tar headers for the filesize, rather than anything about the content or in-container storage.

Comment (TBBle) [reply integration/build/build_test.go]: That took 3 minutes, instead of 10. Much better, thank you.

**Comment by TBBle** [comment]
Okay, this is ready to go, again. ^_^

For some reason two of the integration-cli testsuites failed. They haven't failed before with these changes, and I noticed that they also seem a bit flaky on the [master builds](https://ci-next.docker.com/public/job/moby/job/master/lastCompletedBuild/testReport/) on other platforms, so I'm not sure if I can do anything about that.

Also, the CI pipeline appears to be stuck. One step has been stuck for [almost two hours](https://ci-next.docker.com/public/job/moby/job/PR-41430/10/execution/node/158/log/), despite hitting `exit 1`.

**Comment by olljanat** [comment]
@TBBle Windows CI have been on very bad shape on very long time here and I starting to be bit skeptic with these so now when #40599 is merged can I ask you to:

1. Force push version which only contains your updated test to here so we see that it really fails.
2. Wait that #38469 gets merged before push revendor commit back so we see that all of those tests still passes.

**Comment by TBBle** [comment]
A revert of the revendoring (ab8518ef4ba127a0344aeee3b792128b4bf79f3a), i.e. [just the Windows enablement of `TestBuildWithHugeFile`](https://github.com/moby/moby/compare/0bad48279efe3e5f56df1c4c8c2e6bc90fbb36e9..ab8518ef4ba127a0344aeee3b792128b4bf79f3a) demonstrates the [test and pipeline failure on the Windows RS5 build](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-41430/12/pipeline/237).

**Comment by TBBle** [comment]
If `gotest.tools/v3` supported an 'expected to fail' marker, then I'd suggest pulling the test into #38469 with such a marker, so that this PR could just be a single commit that revendors go-winio _and_ removes the 'expected fail' marker from that test.

But as far as I know, this testing framework supports no such marker.

**Comment by olljanat** [comment]
> A revert of the revendoring ([ab8518e](https://github.com/moby/moby/commit/ab8518ef4ba127a0344aeee3b792128b4bf79f3a)), i.e. [just the Windows enablement of `TestBuildWithHugeFile`](https://github.com/moby/moby/compare/0bad48279efe3e5f56df1c4c8c2e6bc90fbb36e9..ab8518ef4ba127a0344aeee3b792128b4bf79f3a) demonstrates the [test and pipeline failure on the Windows RS5 build](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-41430/12/pipeline/237).

Yes I see that it failed as expected and it happened already on 22 minutes when full CI takes ~60 minutes. Thanks. 

To be honest, I'm not familiar with 'expected to fail' marker or frameworks which support it. However I didn't expect that you would update PR already today so maybe it is not needed to wait #38469 

So LGTM (not maintainer).

@thaJeztah PTAL

**Comment by TBBle** [comment]
CI run failed in building e2e test image, I can't see how that'd be related to my changes...

```
[2020-09-19T15:44:49.076Z] #20 [frozen-images 2/2] RUN /download-frozen-image-v2.sh /build 	buildpack-d...

[2020-09-19T15:44:49.076Z] #20 2.309 Downloading 'library/buildpack-deps:buster@sha256:d0abb4b1e5c664828b93e8b6ac84d10bce45ee469999bef88304be04a2709491' (5 layers)...

[2020-09-19T15:44:49.076Z] #20 2.740 

[2020-09-19T15:44:49.076Z] #20 2.860 
                                                                           0.6%
##########                                                                15.1%
######################                                                    31.5%
#######################################                                   54.2%
##################################################                        69.9%
################################################################          89.4%
######################################################################## 100.0%

[2020-09-19T15:44:49.076Z] #20 4.120 

[2020-09-19T15:44:49.076Z] #20 4.237 
###################################                                       49.2%
######################################################################## 100.0%

[2020-09-19T15:44:49.076Z] #20 4.604 

[2020-09-19T15:44:49.076Z] #20 ERROR: executor failed running [/bin/sh -c /download-frozen-image-v2.sh /build 	buildpack-deps:buster@sha256:d0abb4b1e5c664828b93e8b6ac84d10bce45ee469999bef88304be04a2709491 	busybox:latest@sha256:95cf004f559831017cdf4628aaf1bb30133677be8702a8c5f2994629f637a209 	busybox:glibc@sha256:1f81263701cddf6402afe9f33fca0266d9fff379e59b1748f33d3072da71ee85 	debian:buster@sha256:46d659005ca1151087efa997f1039ae45a7bf7a2cbbe2d17d3dcbda632a3ee9a 	hello-world:latest@sha256:d58e752213a51785838f9eed2b7a498ffa1cb3aa7f946dda11af39286c3db9a9]: runc did not terminate sucessfully

[2020-09-19T15:44:49.076Z] 
```

**Comment by olljanat** [comment]
@TBBle yep. Not related to this one , can be ignored.

File: vendor.conf [hunk 2]
```diff
@@ -1,6 +1,6 @@
 github.com/Azure/go-ansiterm                        d6e3b3328b783f23731bc4d058875b0371ff8109
 github.com/Microsoft/hcsshim                        9dcb42f100215f8d375b4a9265e5bba009217a85 # moby branch
-github.com/Microsoft/go-winio                       6c72808b55902eae4c5943626030429ff20f3b63 # v0.4.14
+github.com/Microsoft/go-winio                       5b44b70ab3ab4d291a7c1d28afe7b4afeced0ed4 # v0.4.15-0.20200908182639-5b44b70ab3ab
```
Comment (thaJeztah) [inline vendor.conf:3]: @kevpar @jterry75 is it possible to tag a new release with this change?

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Review by tiborvass — APPROVED** [review]

**Comment by thaJeztah** [comment]
Thanks!
