### PR TITLE
[v1.11.2] Fix already active error on restoring from ungraceful restart

### LINKED ISSUE #22913: 1.11 containers "already active" after ungraceful shutdown
(found during debugging of https://github.com/docker/docker/issues/22895 (https://github.com/docker/docker/issues/22895#issuecomment-220939087))

after ungraceful killing `docker daemon` (`kill -9 <daemon-pid>` and starting again, `docker ps` shows that the container is exited;

```
CONTAINER ID        IMAGE                COMMAND                CREATED             STATUS                      PORTS               NAMES
eb8eaa41b8b3        supertest2014/nyan   "/bin/sh -c nyancat"   18 minutes ago      Exited (0) 15 minutes ago                       nan

```
However, starting the container doesn't work, looks like the state of `docker-containerd` and `docker daemon` are out of sync in that case;

```
May 23 05:56:46 digitalocean docker[16723]: time="2016-05-23T05:56:46.201963383-04:00" level=error msg="Handler for POST /v1.23/containers/nyan/start returned error: Container eb8eaa41b8b36a56b34502458f4bf44c64e9a8a28c5bb815533525862e4e2210 is aleady active"
```

stopping and starting again doesn't work either;

```
docker stop nyan
nyan
docker start nyan
Error response from daemon: Container eb8eaa41b8b36a56b34502458f4bf44c64e9a8a28c5bb815533525862e4e2210 is aleady active
Error: failed to start containers: nyan
```

(and logs:)
```
May 23 05:59:06 digitalocean docker[16723]: time="2016-05-23T05:59:06.947435285-04:00" level=error msg="Handler for POST /v1.23/containers/nyan/stop returned error: Container nyan is already stopped"
May 23 05:59:20 digitalocean kernel: [ 4099.466155] aufs au_opts_verify:1597:docker[16740]: dirperm1 breaks the protection by the permission bits on the lower branch
May 23 05:59:20 digitalocean kernel: [ 4099.471178] device vethdfa5ed8 entered promiscuous mode
May 23 05:59:20 digitalocean kernel: [ 4099.471302] IPv6: ADDRCONF(NETDEV_UP): vethdfa5ed8: link is not ready
May 23 05:59:20 digitalocean systemd-udevd[16880]: Could not generate persistent MAC address for vethdfa5ed8: No such file or directory
May 23 05:59:20 digitalocean systemd-udevd[16879]: Could not generate persistent MAC address for veth7f497e4: No such file or directory
May 23 05:59:20 digitalocean kernel: [ 4099.488728] docker0: port 1(vethdfa5ed8) entered disabled state
May 23 05:59:20 digitalocean kernel: [ 4099.489824] device vethdfa5ed8 left promiscuous mode
May 23 05:59:20 digitalocean kernel: [ 4099.489828] docker0: port 1(vethdfa5ed8) entered disabled state
May 23 05:59:20 digitalocean docker[16723]: time="2016-05-23T05:59:20.346948775-04:00" level=error msg="Handler for POST /v1.23/containers/nyan/start returned error: Container eb8eaa41b8b36a56b34502458f4bf44c64e9a8a28c5bb815533525862e4e2210 is aleady active"
```

To resolve this, doing a "clean" restart of the daemon;

```
systemctl restart docker
docker start nyan
nyan
docker ps
CONTAINER ID        IMAGE                COMMAND                CREATED             STATUS              PORTS               NAMES
eb8eaa41b8b3        supertest2014/nyan   "/bin/sh -c nyancat"   22 minutes ago      Up 8 seconds
```

note that this is not the same issue as https://github.com/docker/docker/issues/22851, which is for experimental, and related to systemd

### PR DESCRIPTION
**Pull request by tonistiigi**
On killing the processes that were still running
after ungraceful restart, containerd can’t fully
exit the process if the fifos have not been fully
read. In this case, process was just marked as exited
and not removed from the internal containers array.

Fixes #22913

@mlaventure @crosbymichael

Signed-off-by: Tonis Tiigi tonistiigi@gmail.com

### CODE REVIEW

**Comment by tonistiigi** [comment]
@thaJeztah Removed the merge-to-master tag. This code was removed by #22541 that makes removes shutting down containers on daemon reboot.

File: libcontainerd/container_linux.go [hunk 1]
```diff
@@ -191,3 +192,16 @@ func (ctr *container) handleEvent(e *containerd.Event) error {
 	}
 	return nil
 }
+
+func (ctr *container) discardFifos() {
```
Comment (cpuguy83) [inline libcontainerd/container_linux.go]: The reasoning behind this function could use some documentation.

File: libcontainerd/container_linux.go [hunk 2]
```diff
@@ -191,3 +192,16 @@ func (ctr *container) handleEvent(e *containerd.Event) error {
...
+	for _, i := range []int{syscall.Stdout, syscall.Stderr} {
+		f := ctr.fifo(i)
+		c := make(chan struct{})
+		go func() {
+			close(c) // this channel is used to not close the writer too early, before readonly open has been called.
```
Comment (cpuguy83) [inline libcontainerd/container_linux.go]: Is the race between closing this and actually calling `io.Copy` (or is it `openReaderFromFile`?) ok?

Comment (tonistiigi) [inline libcontainerd/container_linux.go]: If there is no other side then it doesn’t matter what you call first as they both block. If there is something keeping the writer side open then again it doesn’t matter because we don’t need close at all.

**Comment by crosbymichael** [comment]
LGMT

**Comment by cpuguy83** [comment]
LGTM

**Comment by ashleydw** [comment]
As posted in https://github.com/docker/docker/issues/22913#issuecomment-263214754 I receive the same error on a exited (error 135) container running in docker 1.12.3

When you say "this code was removed by...." does this mean this PR got merged and taken out in 1.12?

**Comment by thaJeztah** [comment]
@ashleydw please open a new issue if you're having this issue on 1.12.3, if possible with steps to reproduce
