### PR TITLE
Don't create endpoint config for MAC addr config migration

### LINKED ISSUE #47441: Docker 25.03 - Updating containers results in IP Error
### Description

I had incorrectly opened [this issue in the CLI tracker](https://github.com/docker/cli/issues/4895).  So closing that, and recreating here.
Copy-paste from that ticket.

--------------------

Hi,

I had been running docker 24.0.X successfully with current setup without issue, however docker 25 started the below.  I saw that fixes had gone into version including the 25.0.3 item to [resolve MAC address issues](https://github.com/moby/moby/pull/47304).
I have also followed the instructions around recreating all the dockers once on 25.0.3 but my issue remains.

My setup is as follows:

- I have a macvlan-network setup with IPV4 Subnet - 192.168.40.0/22 and IPV4 Gateway - 192.168.41.1.  I have defined IPV4 IP Range - 192.168.42.252/32.   
- I have portainer managing my dockers, with each docker stack defining the related docker's hard coded MAC and IP Address.  For example:

```
version: "2.4"

services:
  librespeed:
    container_name: LibreSpeed
    image: adolfintel/speedtest:latest
    networks:
      macvlan-network:
         ipv4_address: 192.168.41.35
    hostname: speedtest
    domainname: MYFQDN.com
    mac_address: 02:42:c0:a8:29:23
    dns: 192.168.41.1
    restart: unless-stopped
    environment:
      - WEBPORT=80
networks:
  macvlan-network:
    external: true
    name: macvlan-network
```

- I also have Watchtower which regularly updates my dockers.

Since upgrading from 24.0.X (and currently on 25.0.3), it appears that the first(? or one of the first) upgrades will be given the .252 address (even thouigh it should get a hardcoded/static IP as defined in the compose/stack).   Since this is the only IP Address allowed in my range, the next updated dockers will fail to load with the error message:

> Creating /NameOfDocker
> Error response from daemon: no available IPv4 address on this network's address pools: macvlan-network (a36........f1).

At this point, I have to manually delete the docker container and delete the docker image of both the docker taking up the "wrongly assigned" IP address, as well as the containers that failed to install, then go into the stack/compose and redeploy them.   They will then be given the correct static IP addresses, and all is well.

Until the next set of updates.

### Reproduce

Per above.
If watchtower updates a given container after the number of updates passes the number of dynamic IPs that docker is allowed to allocated, this error seems to be hit.  
In my case, I have set docker to allocate 1 single IP, but all my containers have static IP addresses defined for them - so the dynamic IP should never be used / cause this issue.

### Expected behavior

Dockers should be given the \static MAC and IP address as defined in their docker compose/stack.  This was the correct behavior in 24.0.X which has regressed in 25.0.X

### docker version

```bash
Client: Docker Engine - Community
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:14:25 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:25 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    25.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.5
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 16
  Running: 15
  Paused: 0
  Stopped: 1
 Images: 16
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-18-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 31.06GiB
 Name: GypsyPC
 ID: X76E:4OGO:P4TZ:NJT3:KUZK:BELS:4CQB:SD2N:NNKI:BEBQ:2CL6:TDMV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by robmry**
**- What I did**

- Fix https://github.com/moby/moby/issues/47441 - problem introduced in 25.0, https://github.com/moby/moby/pull/45905

When a container-wide MAC address is supplied, it's migrated to the endpoint settings.

Previously, if the network identity supplied in `HostConfig.NetworkMode` did not match the key for a network in `NetworkSettings.Networks`, a new `EndpointSettings` was created to store the MAC address.

But, the mismatch could be due to mixing network name/id/short-id in those fields. In that case, creating a new `EndpointSettings` resulted in duplicate config for the network, and one set was eventually discarded.

**- How I did it**

Don't create a new `EndpointSettings`, unless there are no existing settings.

For the old API, if the API request contains a container-wide MAC address and more than one set of endpoint config, reject the request (not expecting more than one entry in `NetworkSettings.Networks` in that case). Otherwise, apply the container-wide setting to the single endpoint.

For the new API, if the deprecated container wide field is used in the new API and `EndpointsConfig` is provided for any network, the NetworkMode and key in `NetworkSettings.Networks` must be the same - no mixing of ids and names.

**- How to verify it**

New unit test, and a new integration test that mimics Watchtower container creation.

Without this change, the new integration test fails with `Error response from daemon: no available IPv4 addresses on this network's address pools: wtmvl`.

**- Description for the changelog**
```markdown changelog
Preserve supplied endpoint configuration in a container-create API request, when a container-wide MAC address is specified, but `NetworkMode` name-or-id is not the same as the name-or-id used in `NetworkSettings.Networks`.
```

### CODE REVIEW

File: api/server/router/container/container_routes.go [hunk 1]
```diff
@@ -623,42 +623,78 @@ func (s *containerRouter) postContainersCreate(ctx context.Context, w http.Respo
...
 		}
 		if !hostConfig.NetworkMode.IsDefault() && !hostConfig.NetworkMode.IsBridge() && !hostConfig.NetworkMode.IsUserDefined() {
 			return "", runconfig.ErrConflictContainerNetworkAndMac
 		}
 
+		// If there's config for more than one network, return an error. It wasn't possible to
+		// create a container connected to more than one network in older versions of the API.
+		// Could try to match HostConfig.NetworkMode.Name() with the key in EndpointsConfig,
+		// or the NetworkID in there - but they can be any mix of name/id/short-id.
+		if len(networkingConfig.EndpointsConfig) > 1 {
```
Comment (akerouanton) [inline api/server/router/container/container_routes.go:646]: I think that's not needed since `handleMACAddressBC` is called by `(*containerRouter).postContainerCreate()` on line 606, and we already have that check on line 588.

File: integration/networking/mac_addr_test.go [hunk 2]
```diff
@@ -231,3 +231,53 @@ func TestInspectCfgdMAC(t *testing.T) {
...
+	defer network.RemoveNoError(ctx, t, c, netName)
+
+	// Start a container, using the network's id in NetworkMode but its name
+	// in EndpointsConfig. (The container-wide MAC address must be merged with
+	// the endpoint config containing the preferred IP address, but the names
+	// don't match.)
+	const ctrName = "ctr1"
+	const ctrIP = "172.30.0.2"
+	const ctrMAC = "02:42:ac:11:00:42"
+	opts := []func(*container.TestContainerConfig){
```
Comment (akerouanton) [inline integration/networking/mac_addr_test.go:269]: I think you can put all the config funcs into the call to `container.Run`.

**Review by akerouanton — CHANGES_REQUESTED** [review]

File: api/server/router/container/container_routes.go (hunk 1 above)
Comment (robmry) [reply api/server/router/container/container_routes.go]: Ah, yes - excellent! Removed from here and the unit test.

**Review by akerouanton — APPROVED** [review]
LGTM

**Comment by NonaSuomy** [comment]
Will this fix watchtower without them having to do anything or will they still have to do something for this to work properly?

I use mac_address: on about 30 containers with v25.0.3 docker compose they get a static MAC just fine. When watchtower runs it gives them random MACs.

**Comment by robmry** [comment]
> Will this fix watchtower without them having to do anything or will they still have to do something for this to work properly?
> 
> I use mac_address: on about 30 containers with v25.0.3 docker compose they get a static MAC just fine. When watchtower runs it gives them random MACs.
> 
> In the latest 25.0.3 mac_address needs to be under networks or it fails to set it.

Hi @NonaSuomy ... the intention of the original change was to migrate the MAC address from top level config to endpoint config, for any version of the API. And, when an older version of the API is used, to continue to ignore a MAC address supplied in endpoint configuration. This PR doesn't change that intention, it should just stop us from losing track of settings when a mix of network names and ids are used in the API request. It also drops the per-endpoint config for the old API even when no container-wide setting is supplied.

I think this sounds like a different issue, perhaps related to https://github.com/moby/moby/pull/47233 but I'm not sure.

If you can catch logs for a failed update, as well as "docker inspect" for the container before and after - and pop them into a new moby issue, I'll take a look.

Instructions for enabling debug logging are at https://docs.docker.com/config/daemon/logs/#enable-debugging ... when the container's updated, you should see lines "Calling POST" - creating the container, then to disconnect and connect the networks, and finally to start the container. The "form data" log lines following each of those show the API request data.

**Review by vvoland — APPROVED** [review]
LGTM
