### PR TITLE
daemon: Fix mounting same image multiple times with different destinations

### LINKED ISSUE #50122: [BUG] Mounting an image volume multiple times doesn't work
### Description

I originally reported this issue in [docker/compose](https://github.com/docker/compose/issues/12883), but was asked to report it instead. See the original report for a "compose" reproducer.

Mounting an image volume multiple time with the same source image doesn't seem to work as expected. (error: "mount already exists with name").
I would expect that the image volume would be mounted.

Changing the image source to using the digest corresponding to the tag instead of a tag seems to work around the problem.

For context, my use case is that I need to mount a directory but still prevent the shadowing of a few files from the same directory in the image.

### Reproduce

```sh
$ docker run --mount type=image,src=alpine,dst=/etc/foo  --mount type=image,src=alpine,dst=/etc/bar alpine ls -al /etc
docker: Error response from daemon: mount already exists with name
```

### Expected behavior

I would expect that the image volume would be mounted.

### docker version

```bash
Client: Docker Engine - Community
 Version:           28.1.1
 API version:       1.49
 Go version:        go1.23.8
 Git commit:        4eba377
 Built:             Fri Apr 18 09:52:29 2025
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          28.1.1
  API version:      1.49 (minimum version 1.24)
  Go version:       go1.23.8
  Git commit:       01f442b
  Built:            Fri Apr 18 09:52:29 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.27
  GitCommit:        05044ec0a9a75232cad458027ca83437aae3f4da
 runc:
  Version:          1.2.5
  GitCommit:        v1.2.5-0-g59923ef
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    28.1.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.35.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 70
 Server Version: 28.1.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05044ec0a9a75232cad458027ca83437aae3f4da
 runc version: v1.2.5-0-g59923ef
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.10.0-35-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.759GiB
 Name: alchemy
 ID: fbfb1d0b-9b94-4be2-9720-20850fe255d0
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://172.16.0.1:3128
 HTTPS Proxy: http://172.16.0.1:3128
 No Proxy: localhost,127.0.0.1
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by vvoland**
- fixes: https://github.com/moby/moby/issues/50122

The previous implementation generated layer names based on container ID and source image, which would cause conflicts when mounting the same image to multiple destinations within a container.

This fixes the issue by changing the layer naming strategy to include the destination path in the layer name, making it unique for each mount point.

To avoid filesystem paths producing unexpected names, the combined string is hex-encoded and used as a layer name.

**- How to verify it**
TestRunMountImageMultipleTimes

**- Human readable description for the release notes**

```markdown changelog
Fix `--mount type=image` failure when mounting the same image multiple times to a different destinations.
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: daemon/volumes.go [hunk 1]
```diff
@@ -257,7 +258,11 @@ func (daemon *Daemon) registerMountPoints(container *container.Container, hostCo
 				StorageOpt: container.HostConfig.StorageOpt,
 			}
 
-			layerName := fmt.Sprintf("%s-%s", container.ID, mp.Source)
+			// Include the destination in the layer name to make it unique for each mount point and container.
+			// This makes sure that the same image can be mounted multiple times with different destinations.
+			// Hash the destination to create a safe, unique identifier
+			destHash := sha256.Sum256([]byte(container.ID + "src=" + mp.Source + "dst=" + mp.Destination))
+			layerName := hex.EncodeToString(destHash[:])
```
Comment (thaJeztah) [inline daemon/volumes.go]: Would we need to correlate the ID with these anywhere? Considering if (e.g.) base64 encoding or something like that would work instead of a cryptographic hash.

What are the constraints on these names? (is this path on disk, or otherwise?)

Comment (vvoland) [reply daemon/volumes.go]: We don't really need to correlate these, we just need "a" name for the snapshot. I think it could only be problematic when trying to match the name when filtering snapshots?

Also not sure if there's a length limit on snapshot ids.

Comment (vvoland) [reply daemon/volumes.go]: Changed to hex-encoding, so it's reversible in case it's needed.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by dmcgowan — APPROVED** [review]

**Comment by apollo13** [comment]
This fix seems to break image mounts completely depending on the filesystem (?) https://github.com/moby/moby/issues/51687

**Comment by vvoland** [comment]
You're absolutely right! /s

I restored hashing the mount paths to avoid that and opened a PR: https://github.com/moby/moby/pull/51827

Thanks for a ping!
