### PR TITLE
Data path traffic separation option in swarm mode

### LINKED ISSUE #32446: Daemon shutdown delayed by "broadcasting node event"
When I shut down the daemon with `^C`, there is a 5 second pause, and then I get an error message "timed out broadcasting node event".

```
DEBU[0056] start clean shutdown of cluster resources...
ERRO[0061] failed to send node leave: timed out broadcasting node event
```

This seems to be new on master in the last day or so. I think it's caused by #32283 

cc @aboch

### PR DESCRIPTION
**Pull request by fcrisciani**
**- What I did**
In SWARM mode is now possible to pass a new flag to specify which is the interface to use for data path traffic. This will allow to separate data traffic (container to container pkts) from control traffic (grpc between workers and managers)

**- How I did it**
Introduced a new flag `--data-path-addr` in the docker swarm init and docker swarm join

**- How to verify it**
Create a swarm cluster on hosts with at least 2 interfaces, one will be dedicated for the management and will be the one that will be used in the --advertise-addr, the other instead will be the one for the`--data-path-addr` flag.
Second step is to create an overlay network
Third step is to launch containers on different workers using the overlay network.
At this point the traffic between the containers on different workers will happen on the interface identified by the `--data-path-addr`

**- Description for the changelog**

Data path traffic separation option in swarm mode

Fixes #32446

**- A picture of a cute animal (not mandatory but encouraged)**
hqdefault

### CODE REVIEW

**Comment by fcrisciani** [comment]
@aaronlehmann had to reopen it because the previous pull https://github.com/moby/moby/pull/32615 was not getting updated

**Comment by aaronlehmann** [comment]
LGTM

**Comment by aboch** [comment]
looks good to me

**Comment by cpuguy83** [comment]
Can you squash so there are two commits, one for libnetwork and one for the new flag/test/etc

**Comment by auntunif** [comment]
/ test / etc

**Comment by fcrisciani** [comment]
@cpuguy83 good like that?

**Comment by fcrisciani** [comment]
@cpuguy83 the powerpc pipeline is stuck

**Comment by cpuguy83** [comment]
Can we move these cli changes over to the docker/cli repo?

**Comment by aaronlehmann** [comment]
I thought the CLI code hadn't been moved over yet. Shouldn't we make changes here until it is?

**Comment by cpuguy83** [comment]
Every change is 1 more rebase.
As I understand it's fairly imminent.

**Comment by aaronlehmann** [comment]
I'm concerned about having two diverging implementations. I think we should continue making changes here until the switch happens.

Among other things, the integration test being added here wouldn't pass because there would be a circular dependency between the test and the code being added in `docker/cli`. I think this is one of the things we need to solve before splitting out the CLI. I haven't heard a proposal yet.

File: daemon/cluster/swarm.go [hunk 1]
```diff
@@ -93,6 +98,7 @@ func (c *Cluster) Init(req types.InitRequest) (string, error) {
 		LocalAddr:       localAddr,
 		ListenAddr:      net.JoinHostPort(listenHost, listenPort),
 		AdvertiseAddr:   net.JoinHostPort(advertiseHost, advertisePort),
+		DataPathAddr:    dataPathAddr,
```
Comment (dongluochen) [inline daemon/cluster/swarm.go]: If `--data-path-addr` not specified, should it use `AdvertiseAddr`, or empty string?

Comment (dongluochen) [inline daemon/cluster/swarm.go]: According to document, it should use `AdvertiseAddr`. 

```
+If unspecified, Docker will use the same IP address or interface that is used for the
 +advertise address.
```

Comment (fcrisciani) [inline daemon/cluster/swarm.go]: The config is saved consistently with the user input, this way we are not losing track of the original value inserted from the CLI.
The final decision on what to use in case the parameter is not specified is left to the final user of the flag itself.
Today libnetwork if the DataPathAddr is not specified will fallback using the AdvertiseAddr.

File: daemon/cluster/cluster.go [hunk 2]
```diff
@@ -270,6 +270,16 @@ func (c *Cluster) GetAdvertiseAddress() string {
 	return c.currentNodeState().actualLocalAddr
 }
 
+// GetDataPathAddress returns the address to be used for the data path traffic.
```
Comment (dongluochen) [inline daemon/cluster/cluster.go]: `GetDataPathAddress returns the address configured for data path traffic.`

File: daemon/cluster/swarm.go (hunk 1 above)
Comment (dongluochen) [inline daemon/cluster/swarm.go]: Make sense. I think the `GetDataPathAddress` should clarify its description.

File: daemon/cluster/cluster.go (hunk 2 above)
Comment (fcrisciani) [inline daemon/cluster/cluster.go]: Would you prefer something like: GetDataPathAddress returns the address to be used for the data path traffic, if specified.

Comment (dongluochen) [inline daemon/cluster/cluster.go]: That sounds good.

Comment (fcrisciani) [inline daemon/cluster/cluster.go]: k will change it

**Comment by dongluochen** [comment]
looks good to me

**Review by cpuguy83 — APPROVED** [review]
LGTM

File: integration-cli/docker_cli_swarm_test.go [hunk 3]
```diff
@@ -1932,3 +1932,15 @@ func (s *DockerSwarmSuite) TestSwarmServiceLsFilterMode(c *check.C) {
 	c.Assert(out, checker.Contains, "top1")
 	c.Assert(out, checker.Not(checker.Contains), "top2")
 }
+
+func (s *DockerSwarmSuite) TestSwarmInitUnspecifiedDataPathAddr(c *check.C) {
+	d := s.AddDaemon(c, false, false)
+
+	out, err := d.Cmd("swarm", "init", "--data-path-addr", "0.0.0.0")
```
Comment (fntlnz) [inline integration-cli/docker_cli_swarm_test.go]: Here I would add a test with a completely invalid data path addr to check if the error is consistent

File: vendor.conf [hunk 4]
```diff
@@ -25,7 +25,7 @@ github.com/RackSec/srslog 456df3a81436d29ba874f3590eeeee25d666f8a5
 github.com/imdario/mergo 0.2.1
 
 #get libnetwork packages
-github.com/docker/libnetwork b13e0604016a4944025aaff521d9c125850b0d04
+github.com/docker/libnetwork 5dc95a3f9ce4b70bf08492ca37ec55c5b6d84975
```
Comment (fntlnz) [inline vendor.conf]: I see that this commit implements your required changes from libnetwork but why not using the latest atm?

Comment (fntlnz) [inline vendor.conf]: for those who need a compare:

Proposed commit
https://github.com/docker/libnetwork/compare/b13e0604016a4944025aaff521d9c125850b0d04...5dc95a3f9ce4b70bf08492ca37ec55c5b6d84975

Master:
https://github.com/docker/libnetwork/compare/b13e0604016a4944025aaff521d9c125850b0d04...master

Is there something I'm missing?

File: daemon/cluster/listen_addr.go [hunk 5]
```diff
@@ -20,23 +22,17 @@ func resolveListenAddr(specifiedAddr string) (string, string, error) {
...
 	// Does the host component match any of the interface names on the
 	// system? If so, use the address from that interface.
-	interfaceAddr, err := resolveInterfaceAddr(specifiedHost)
-	if err == nil {
-		return interfaceAddr.String(), specifiedPort, nil
-	}
-	if err != errNoSuchInterface {
+	specifiedIP, err := resolveInputIPAddr(specifiedHost, true)
+	if err != nil {
+		if err == errBadNetworkIdentifier {
```
Comment (fcrisciani) [inline daemon/cluster/listen_addr.go]: This is the resolveListenAddr that validates the listening address so the error is converted in a way that report an issue on the listening address

File: vendor.conf (hunk 4 above)
Comment (fcrisciani) [inline vendor.conf]: Not sure I follow, this patch got merged already several days ago

Comment (thaJeztah) [inline vendor.conf]: @fntlnz this PR was merged 25 days ago, so wouldn't be able to get all changes in master that are available now :)

File: integration-cli/docker_cli_swarm_test.go (hunk 3 above)
Comment (fcrisciani) [inline integration-cli/docker_cli_swarm_test.go]: non valid IP addresses are captured by the net.ParseIP() and all collapsed to the same error message errBadNetworkIdentifier.

File: vendor.conf (hunk 4 above)
Comment (fntlnz) [inline vendor.conf]: daf*** haven't noticed the merged button :D had it in my review list and finally found time to look at it! Anyway @fcrisciani super nice feature!

**Comment by praving55** [comment]
https://github.com/moby/moby/issues/33936

**Comment by thaJeztah** [comment]
@praving55 ah! I see you commented here as well; I see the flag was renamed during the design/PR review process (originally `--datapath-addr`, later `--data-path-addr`. I updated the top description to prevent  this confusion (already commented in https://github.com/moby/moby/issues/33936#issuecomment-312796936)
