### PR TITLE
Retry creating dynamic networks if not found

### LINKED ISSUE #25528: Swarm mode - service start failing - `could not find an appropriate master` /  `network [name] not found`
**Output of `docker version`:**

```
# docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 22
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 66
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: active
 NodeID: 2cablbfkjystf7y45mxnnyno5
 Is Manager: true
 ClusterID: 0i5aaf4pqb68oh15w6d7k3pkb
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot interval: 10000
  Heartbeat tick: 1
  Election tick: 3
 Dispatcher:
  Heartbeat period: 5 seconds
 CA configuration:
  Expiry duration: 3 months
 Node Address: 10.#.#.#
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-86-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.5 MiB
Name: manager-1
ID: XISA:J5UD:HJYM:IBW4:HODQ:DRPM:XZYB:YLTO:EKCE:TS6G:CQMI:J5XW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

 * Running as root
 * Each machine has 2 interfaces (in essence, internal network `eth0` and public-facing `eth1`)

**Steps to reproduce the issue:**
1. manager-1: `docker swarm init --listen-addr=eth0 --advertise-addr=eth0`
2. node-1/node-2: `docker swarm join --advertise-addr=eth0 --listen-addr=eth0 [...tokens, machine]`
3. manager-1: `docker network create -d overlay my_default`
4. manager-1: `docker service create --replicas 1 --publish 80:80/tcp --name helloworld --network my_default kitematic/hello-world-nginx`

I have tried this with:
 * manager  + 2 nodes
 * drained manager + 2 nodes
 * drained manager + 1 node

And tried multiple times with different numbers of replicas.

**Describe the results you received:**

 * Swarm is created
 * Nodes successfully joined swarm.
 * netstat reveals listening on interfaces expected from `listen/advertise-addr`
 * but, Docker repeatedly tries to start the service, but repeatedly fails. The following is the result of inspecting a failed task.
```
[
    {
        "ID": "866d8e8hoat57gxcd47tbb1bk",
        "Version": {
            "Index": 2548
        },
        "CreatedAt": "2016-08-09T08:15:20.148303686Z",
        "UpdatedAt": "2016-08-09T08:15:25.479130361Z",
        "Spec": {
            "ContainerSpec": {
                "Image": "kitematic/hello-world-nginx"
            },
            "Resources": {
                "Limits": {},
                "Reservations": {}
            },
            "RestartPolicy": {
                "Condition": "any",
                "MaxAttempts": 0
            },
            "Placement": {}
        },
        "ServiceID": "78c4169tbt1q8sdd49ha5jzzw",
        "Slot": 1,
        "NodeID": "1tnunlskw010sjo1f8ql7buqh",
        "Status": {
            "Timestamp": "2016-08-09T08:15:25.452521634Z",
            "State": "failed",
            "Message": "starting",
            "Err": "starting container failed: could not add veth pair inside the network sandbox: could not find an appropriate master \"ov-000100-32d6h\" for \"vethcce52b4\"",
            "ContainerStatus": {
                "ContainerID": "395f6c5c8505a92eece2fdee6553da1bf3ae4351e1b09e3219ad57616b52961f",
                "ExitCode": 128
            }
        },
        "DesiredState": "shutdown",
        "NetworksAttachments": [
            {
                "Network": {
                    "ID": "32d6hihsdxuw9erz3b8kx153y",
                    "Version": {
                        "Index": 7
                    },
                    "CreatedAt": "2016-08-08T15:12:57.445157207Z",
                    "UpdatedAt": "2016-08-08T15:12:57.457986108Z",
                    "Spec": {
                        "Name": "ingress",
                        "Labels": {
                            "com.docker.swarm.internal": "true"
                        },
                        "DriverConfiguration": {},
                        "IPAMOptions": {
                            "Driver": {},
                            "Configs": [
                                {
                                    "Subnet": "10.255.0.0/16",
                                    "Gateway": "10.255.0.1"
                                }
                            ]
                        }
                    },
                    "DriverState": {
                        "Name": "overlay",
                        "Options": {
                            "com.docker.network.driver.overlay.vxlanid_list": "256"
                        }
                    },
                    "IPAMOptions": {
                        "Driver": {
                            "Name": "default"
                        },
                        "Configs": [
                            {
                                "Subnet": "10.255.0.0/16",
                                "Gateway": "10.255.0.1"
                            }
                        ]
                    }
                },
                "Addresses": [
                    "10.255.0.6/16"
                ]
            },
            {
                "Network": {
                    "ID": "d52l8p0fdlhzhym80nd4a7s29",
                    "Version": {
                        "Index": 2332
                    },
                    "CreatedAt": "2016-08-09T07:59:30.289451012Z",
                    "UpdatedAt": "2016-08-09T07:59:30.297942566Z",
                    "Spec": {
                        "Name": "my_default",
                        "DriverConfiguration": {
                            "Name": "overlay"
                        },
                        "IPAMOptions": {
                            "Driver": {
                                "Name": "default"
                            }
                        }
                    },
                    "DriverState": {
                        "Name": "overlay",
                        "Options": {
                            "com.docker.network.driver.overlay.vxlanid_list": "257"
                        }
                    },
                    "IPAMOptions": {
                        "Driver": {
                            "Name": "default"
                        },
                        "Configs": [
                            {
                                "Subnet": "10.0.0.0/24",
                                "Gateway": "10.0.0.1"
                            }
                        ]
                    }
                },
                "Addresses": [
                    "10.0.0.3/24"
                ]
            }
        ]
    }
]
```

**Describe the results you expected:**

 * Task not failing
 * Connecting to my_default network
 * Published port 80 available across nodes

**Additional information you deem important (e.g. issue happens only occasionally):**

 * The service will start if I'm not publishing the port
 * Have tried this many times, with different combinations of listen addr/advertise addr.
 * Sometimes it switches to a different error : "network my_default not found"
 * the network is there on the node (at least for some time)
```
node-2: docker network inspect my_default
[
    {
        "Name": "my_default",
        "Id": "d52l8p0fdlhzhym80nd4a7s29",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.0.0/24",
                    "Gateway": "10.0.0.1"
                }
            ]
        },
        "Internal": false,
        "Containers": {},
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "257"
        },
        "Labels": {}
    }
]
```
 * I notice that there is an error if I leave and join the node from the swarm, but don't know if this could be related:
```
time="2016-08-09T16:35:34.791155243+08:00" level=info msg="Waiting for TLS certificate to be issued..." 
time="2016-08-09T16:35:34.850700848+08:00" level=info msg="Downloaded new TLS credentials with role: swarm-worker." 
time="2016-08-09T16:35:35.126747636+08:00" level=info msg="Initializing Libnetwork Agent Local-addr=10.###### Adv-addr=10.###### Remote-addr =10.######" 
time="2016-08-09T16:35:35.131275362+08:00" level=error msg="Error getting node 7uj0a3dtazhk45azpve3lpg4m: This node is not a swarm manager. Worker nodes can't be used to view or modify cluster state. Please run this command on a manager node or promote the current node to a manager." 
time="2016-08-09T16:35:35.131336393+08:00" level=error msg="Handler for GET /v1.24/nodes/7uj0a3dtazhk45azpve3lpg4m returned error: This node is not a swarm manager. Worker nodes can't be used to view or modify cluster state. Please run this command on a manager node or promote the current node to a manager." 
```
 * here are some logs showing the seemingly chaotic nature of the issue, where the logged error flits between network not found and the one inspected above.. ( I assume docker is trying to recover some state, but unsure what the underlying problem is?):
```
time="2016-08-09T16:38:14.236638299+08:00" level=error msg="fatal task error" error= module=taskmanager task.id=2ezlqpi05yrxqjjsmuvdpyjzv 
time="2016-08-09T16:38:19.480286483+08:00" level=error msg="fatal task error" error= module=taskmanager task.id=cnw3o0k9uezjy12a39ib9d4mh 
time="2016-08-09T16:38:23.692027580+08:00" level=error msg="fatal task error" error="network my_default not found" module=taskmanager task.id=c683gvmxawzaxq4qqq54vppts 
time="2016-08-09T16:38:24.676231768+08:00" level=error msg="network my_default remove failed: network my_default not found" module=taskmanager task.id=454sq89k0t5fock9goxgybfhc 
time="2016-08-09T16:38:24.676652083+08:00" level=error msg="remove task failed" error="network my_default not found" module=taskmanager task.id=454sq89k0t5fock9goxgybfhc 
time="2016-08-09T16:38:29.724370136+08:00" level=error msg="fatal task error" error= module=taskmanager task.id=bqtkeos2bhf3u0c9m4033mb1x 
time="2016-08-09T16:38:34.512645166+08:00" level=error msg="fatal task error" error="network my_default not found" module=taskmanager task.id=cwpkictzj7qigattw4qk6t9pc 
time="2016-08-09T16:38:38.933775777+08:00" level=error msg="fatal task error" error="network my_default not found" module=taskmanager task.id=bwcplcv8biov2anypctw7vgen 
time="2016-08-09T16:38:44.165994064+08:00" level=error msg="fatal task error" error="network my_default not found" module=taskmanager task.id=2isojd0at5vdeaitfyk2uqquy 
time="2016-08-09T16:38:49.781243365+08:00" level=error msg="fatal task error" error="network my_default not found" module=taskmanager task.id=74wx6tvsashuze9psr9rvzcme 
time="2016-08-09T16:38:49.923918645+08:00" level=error msg="network my_default remove failed: network my_default not found" module=taskmanager task.id=bqtkeos2bhf3u0c9m4033mb1x 
time="2016-08-09T16:38:49.924349209+08:00" level=error msg="remove task failed" error="network my_default not found" module=taskmanager task.id=bqtkeos2bhf3u0c9m4033mb1x 
time="2016-08-09T16:38:54.981108235+08:00" level=error msg="fatal task error" error= module=taskmanager task.id=2t0t1cqhnvwkwp1vvf8lh31gz 
time="2016-08-09T16:39:00.305111095+08:00" level=error msg="fatal task error" error= module=taskmanager task.id=6fvbiz71u13m8lz3tjjvj7j3y 
time="2016-08-09T16:39:05.508501941+08:00" level=error msg="fatal task error" error= module=taskmanager task.id=5xmld60h2l9926yhdlen4abyb 
time="2016-08-09T16:39:10.877713447+08:00" level=error msg="fatal task error" error= module=taskmanager task.id=ey9viblu9hquteaf3bxyk47j8 
time="2016-08-09T16:39:15.337916025+08:00" level=error msg="fatal task error" error="network my_default not found" module=taskmanager task.id=aqceqd1ycnjapxscfbmg7jv8u 
time="2016-08-09T16:39:20.049910042+08:00" level=error msg="fatal task error" error="network my_default not found" module=taskmanager task.id=10js63klwvpwvkpts1mryio3s 
time="2016-08-09T16:39:25.514600345+08:00" level=error msg="fatal task error" error="network my_default not found" module=taskmanager task.id=eedatxm2u4d1ey6f6ebnnyiaf 
time="2016-08-09T16:39:29.171195558+08:00" level=error msg="fatal task error" error="network my_default not found" module=taskmanager task.id=86psp8i5uxoxjcshsh7m46poy
```

### PR DESCRIPTION
**Pull request by mrjana**
In cases there are failures in task start, swarmkit might be trying to
restart the task again in the same node which might keep failing. This
creates a race where when a failed task is getting removed it might
remove the associated network while another task for the same service
or a different service but connected to the same network is proceeding
with starting the container knowing that the network is still
present. Fix this by reacting to `ErrNoSuchNetwork` error during
container start by trying to recreate the managed networks. If they
have been removed it will be recreated. If they are already present
nothing bad will happen.

Fixes #25528

Signed-off-by: Jana Radhakrishnan mrjana@docker.com

### CODE REVIEW

**Comment by tonistiigi** [comment]
Why do we allow removing networks that are used by existing (stopped) containers?

**Comment by mrjana** [comment]
No, we don't remove networks for stopped containers. But some of them do get removed(when there are continuous failures) and when they get removed we do remove the networks. That is when this issue happens.

**Comment by tonistiigi** [comment]
@mrjana If that is the case then I think this check could be in `create` instead of `start` but with manual testing I was able to remove a network that was being used and only get an error on container start.

**Comment by mrjana** [comment]
@tonistiigi Yeah you don't get an error in create because there is no network setup involved during create. The error only happens during start because that is where the network setup happens and that is why the check is there.

**Comment by tonistiigi** [comment]
LGTM

File: daemon/cluster/executor/container/controller.go [hunk 1]
```diff
@@ -163,8 +164,23 @@ func (r *controller) Start(ctx context.Context) error {
...
+		if err := r.adapter.start(ctx); err != nil {
+			if _, ok := err.(libnetwork.ErrNoSuchNetwork); ok {
+				// Retry network creation again if we
+				// failed because some of the networks
+				// were not found.
+				if err := r.adapter.createNetworks(ctx); err != nil {
+					return err
+				}
+
+				continue
```
Comment (tiborvass) [inline daemon/cluster/executor/container/controller.go]: no need to change this now, but it's typically somewhere i would just use a `goto` :)

**Comment by tiborvass** [comment]
LGTM
