### PR TITLE
daemon/containerd: fix label!= filter ignoring images without label

### LINKED ISSUE #52334: `docker image prune` ignores label!= filter on Docker 29+
### Description

docker image prune does not remove any images when using a negative label filter (label!=...). The command completes successfully with **no errors**, but **no images are deleted** even when they clearly do not match the excluded label.

Removing the filter makes the command behave correctly.

This is a regression or behavior change in Docker 29+.

### Reproduce

Docker version 29.3.1
My label is `on_prune=keep`. It is only part of my custom builds. 
`docker pull mongo`

The label is not in the mongo image
```
docker image inspect mongo:latest --format '{{json .Config.Labels}}'
{"org.opencontainers.image.version":"24.04"}
```

Negative filter does not work
```
docker image list --filter=label!=on_prune=keep
                                                                                                                                                                                                 i Info →   U  In Use
IMAGE   ID             DISK USAGE   CONTENT SIZE   EXTRA
```

Images WITHOUT the custom label are not pruned
```
docker image prune -a -f --filter=label!=on_prune=keep
Total reclaimed space: 0B
```

The image mongo:latest should be deleted, since it does not have the label on_prune=keep.

### Expected behavior

As in Docker 28.1.1
Negative filter allows to prune all images that DON'T have the label

```
docker pull mongo

Using default tag: latest
latest: Pulling from library/mongo
689b91d88a0f: Pull complete 
db782b49bd71: Pull complete 
66e4666e3305: Pull complete 
cd5dd782e823: Pull complete 
b286261d1310: Pull complete 
a7231d1eab25: Pull complete 
5283059b6331: Pull complete 
2a1aa97b40be: Pull complete 
Digest: sha256:f071cbf97a6e52fb7f07ce9ca5d862ad79876bf0eba9ba97758337d740449638
Status: Downloaded newer image for mongo:latest
docker.io/library/mongo:latest
```

```
docker image prune -a -f --filter=label!=on_prune=keep

Deleted Images:
untagged: mongo:latest
untagged: mongo@sha256:f071cbf97a6e52fb7f07ce9ca5d862ad79876bf0eba9ba97758337d740449638
deleted: sha256:54f808fc62647d6b9bc5eb991fce8d628e2b2989d032e9df7d85cefa47cd9cc3
deleted: sha256:364489d7c38ce4d80dcbfcd24c65d5a084c0ea8ecad388670c068bd7261f04e9
deleted: sha256:37981eb2f6f6a8dad3e2657479563efc1270cb619bdbd95926589ae2ff1da5ce
deleted: sha256:e3b7ce1db8f32dac3fc23c801ff0974f82eb45c1348c27846ebb6d33d9bb4dfc
deleted: sha256:275d7436e9ff11633a1f4547e97132e72c96365a12cfe3c5f8a2dd88753197e4
deleted: sha256:b767a2f2bdb8af31858d9065f4f398c6568132502aa1f770b7a7358173b2f6b3
deleted: sha256:1ec14ae652349bfed797ba6f242ff0e872ee805bdeea66a0b1484cc742585e46
deleted: sha256:99f80900d6004ed107a97a88471d48056558dce4ee6e527829a9e5e3d7fcfc0a
deleted: sha256:5e732af9e7c568c9b41ecabc76ac93a58471934d5155070dfd64a9567667fd9d

Total reclaimed space: 950.1MB
```

### docker version

```bash
docker version
Client: Docker Engine - Community
 Version:           29.3.1
 API version:       1.54
 Go version:        go1.25.8
 Git commit:        c2be9cc
 Built:             Wed Mar 25 16:13:32 2026
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          29.3.1
  API version:      1.54 (minimum version 1.40)
  Go version:       go1.25.8
  Git commit:       f78c987
  Built:            Wed Mar 25 16:13:32 2026
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v2.2.2
  GitCommit:        301b2dac98f15c27117da5c8af12118a041a31d9
 runc:
  Version:          1.3.4
  GitCommit:        v1.3.4-0-gd6d73eb8
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    29.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.33.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v5.1.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 38
  Running: 38
  Paused: 0
  Stopped: 0
 Images: 36
 Server Version: 29.3.1
 Storage Driver: overlayfs
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 CDI spec directories:
  /etc/cdi
  /var/run/cdi
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 301b2dac98f15c27117da5c8af12118a041a31d9
 runc version: v1.3.4-0-gd6d73eb8
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-173-generic
 Operating System: Ubuntu 22.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 29.8GiB
 Name: lmio-bat
 ID: af576cde-5255-437d-81e5-d20c7f89ebb0
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
  ::1/128
 Live Restore Enabled: false
 Firewall Backend: iptables
```

### Additional Info

This breaks workflows that depend on preserving specific images via labels while pruning all others. The failure is silent, which makes it particularly dangerous in automation.

### PR DESCRIPTION
**Pull request by sahilsGit**
- Fixes #52334

**What changed**
- Fixed a logic bug in `setupLabelFilter` (`daemon/containerd/image_list.go`) where negated filter checks (`label!=key=value`) incorrectly failed when the image was missing the label entirely.
- Modified the filter condition so that if a label is missing, we evaluate whether it's a negated check before deciding to early return.
- Added a comprehensive regression test suite (`TestSetupLabelFilterNegativeValue`) into a new `prune_test.go` file.

**Why**
Prior to this fix, the containerd `setupLabelFilter` logic treated a missing label as a non-match regardless of whether the filter was negated. This caused commands like `docker image prune --filter label!=key=value` to silently skip images that don't have the label at all. Since `containerd-snapshotter` is enabled by default in Docker 29+, this caused a regression in pruning behavior where images lacking a key inexplicably failed to be deleted. 

**Validation**
- Manually verified `docker image prune -a --force --filter 'label!=on_prune=keep'` correctly reclaims space and deletes the image on the containerd backend.
- Verified all newly added regression tests in `image_labelfilter_test.go` pass successfully:
  - `label!=key=value` correctly matches images missing the label.
  - `label=key=value` correctly *does not* match images missing the label.
  - `label!=key=other` correctly matches images with the key but a different value.

```markdown changelog
containerd image store: Fix `docker image prune --filter label!=key=value` incorrectly skipping images that don't have the specified label.
```

### CODE REVIEW

File: daemon/containerd/image_labelfilter_test.go [hunk 1]
```diff
@@ -0,0 +1,156 @@
...
+	"gotest.tools/v3/assert"
+)
+
+// TestSetupLabelFilterNegativeValue is a regression test for the bug where
+// --filter=label!=key=value did not match images that are missing the label
+// entirely. Images without the label should satisfy the negated filter because
+// they certainly do not have label=value. The old code returned false (no
+// match) whenever the label was absent, regardless of whether the check was
+// negated.
+func TestSetupLabelFilterNegativeValue(t *testing.T) {
```
Comment (vvoland) [inline daemon/containerd/image_labelfilter_test.go]: This should be an integration test that will run against both containerd and the legacy image store (so we make sure that it behaves the same).

File: daemon/containerd/image_labelfilter_test.go [hunk 2]
```diff
@@ -0,0 +1,156 @@
...
+	})
+	assert.NilError(t, err)
+
+	imgWithLabel := imagesFromIndex(idxWithLabel)[0]
+
+	// Patch the image: rewrite the config blob to include the label, then
+	// rewrite the manifest to point to the new config blob.
+	imgWithLabel = patchImageConfigLabels(t, ctx, cs, blobsDir, imgWithLabel, map[string]string{
+		"on_prune": "keep",
+	})
```
Comment (vvoland) [inline daemon/containerd/image_labelfilter_test.go]: A better solution would be to add (or extend) something like https://github.com/moby/moby/blob/master/internal/testutil/specialimage/configtarget.go to also add that label while creating the image config.

**Review by vvoland — COMMENTED** [review]
Thanks! A couple of suggestions

File: daemon/containerd/image_labelfilter_test.go (hunk 1 above)
Comment (sahilsGit) [reply daemon/containerd/image_labelfilter_test.go]: Cool

File: daemon/containerd/image_labelfilter_test.go (hunk 2 above)
Comment (sahilsGit) [reply daemon/containerd/image_labelfilter_test.go]: Alright, I will consider

Comment (sahilsGit) [reply daemon/containerd/image_labelfilter_test.go]: Hey @vvoland , I pushed the requested changes, can you re-review

File: daemon/containerd/image_labelfilter_test.go (hunk 1 above)
Comment (sahilsGit) [reply daemon/containerd/image_labelfilter_test.go]: done!

File: integration/image/prune_test.go [hunk 3]
```diff
@@ -229,3 +230,49 @@ func TestPruneDontDeleteUsedImage(t *testing.T) {
...
+
+	d := daemon.New(t)
+	d.Start(t)
+	defer d.Stop(t)
+
+	apiClient := d.NewClientT(t)
+
+	// Load an image that has the on_prune=keep label — must NOT be pruned.
+	withLabelID := iimage.Load(ctx, t, apiClient, func(dir string) (*ocispec.Index, error) {
+		return specialimage.MultiLayerCustomWithLabels(dir, "withlabel:latest", []specialimage.SingleFileLayer{
```
Comment (vvoland) [inline integration/image/prune_test.go]: This doesn't require an actual image with multiple layers right? We only care about the image config having a label.

I think it would be better not to overload the "multi layer" image purpose and have a dedicated specialimage function for this.

Comment (sahilsGit) [reply integration/image/prune_test.go]: Alright, I would revert and create a new testfile similar to `configtarget.go`, to get this done.

Comment (vvoland) [reply integration/image/prune_test.go]: Yep! Note, the `configtarget` is kind of a special edge case, because it skips the OCI manifest.
So it's still fine to draw inspiration from `MultiLayerCustomWithLabels`

Comment (sahilsGit) [reply integration/image/prune_test.go]: Hey, I was thinking of making an image with no layers (referring to `dangling.go`, or should I create a single layered, it should not matter right?

```
	configDesc, err := writeJsonBlob(dir, ocispec.MediaTypeImageConfig, ocispec.Image{
		Platform: platforms.DefaultSpec(),
		Config: ocispec.ImageConfig{
			Labels: labels,
		},
		RootFS: ocispec.RootFS{
			Type: "layers",
		},
	})
	if err != nil {
		return nil, err
	}

	manifest := ocispec.Manifest{
		MediaType: ocispec.MediaTypeImageManifest,
		Config:    configDesc,
		Layers:    []ocispec.Descriptor{},
	}

	legacyManifests := []manifestItem{
		{
			Config:   blobPath(configDesc),
			RepoTags: []string{imageRef},
		},
	}
	
	
	like this

Comment (vvoland) [reply integration/image/prune_test.go]: Yeah it should be fine

File: integration/image/prune_test.go [hunk 4]
```diff
@@ -229,3 +230,45 @@ func TestPruneDontDeleteUsedImage(t *testing.T) {
...
+	filters.Add("dangling", "false")
+
+	_, err := apiClient.ImagePrune(ctx, client.ImagePruneOptions{
+		Filters: filters,
+	})
+	assert.NilError(t, err)
+
+	// The image without the label must have been pruned.
+	_, err = apiClient.ImageInspect(ctx, noLabelID)
+	assert.Check(t, err != nil, "nolabel image should no longer exist after prune")
```
Comment (vvoland) [inline integration/image/prune_test.go]: Let's make sure we got the correct error

```suggestion
	assert.Check(t, errdefs.IsNotFound(err), "nolabel image should no longer exist after prune")
```

File: integration/image/prune_test.go [hunk 5]
```diff
@@ -229,3 +230,45 @@ func TestPruneDontDeleteUsedImage(t *testing.T) {
...
+		return specialimage.Labeled(dir, "nolabel:latest", nil)
+	})
+
+	filters := make(client.Filters)
+	filters.Add("label!", "on_prune=keep")
+	filters.Add("dangling", "false")
+
+	_, err := apiClient.ImagePrune(ctx, client.ImagePruneOptions{
+		Filters: filters,
+	})
```
Comment (vvoland) [inline integration/image/prune_test.go]: `ImagePrune` also returns report containing `ImagesDeleted`.

Would be good to also check that!

**Review by vvoland — COMMENTED** [review]
Failure related:

```
=== FAIL: amd64.integration-cli TestDockerDaemonSuite/TestPruneImageLabel (21.40s)
    docker_cli_prune_unix_test.go:312: assertion failed: strings.Contains(strings.TrimSpace(out), id2) is true
    --- FAIL: TestDockerDaemonSuite/TestPruneImageLabel (21.40s)
```

File: integration/image/prune_test.go (hunk 5 above)
Comment (sahilsGit) [reply integration/image/prune_test.go]: Hey @vvoland , the failing test's creating image with the both the main manifest and attestation manifests. My fix causes the negated filter (label!=bar=foo) to "pass" for attestation configs (which have no labels), causing the entire image to match the filter even when its main config has the excluded label.

Any advice on how to tackle this? I need to skip attestation manifests during the label config walk, I can see that `IsAttestation()` checks for the vnd.docker.reference.type annotation on the descriptor.

Is the right place to guard against this inside Dispatch handler — skipping descriptors that have the attestation annotation before reading the config? Or is there a cleaner existing abstraction I should be using instead?

Comment (vvoland) [reply integration/image/prune_test.go]: Yes, in this case it seems to be a good solution!

Note, you actually need to prevent from traversing the whole chain starting from the attestation manifest.

For that, a simple return won't be enough - you will need to instruct the `Dispatch` to stop.
You can do that by returning [`ErrSkipDesc`](https://github.com/containerd/containerd/blob/341401c1d5c643d303e535f593a435637adb64e2/core/images/handlers.go#L36-L38)

Comment (sahilsGit) [reply integration/image/prune_test.go]: @vvoland I have addressed all the feedback. Also ran `TEST_FILTER=TestPrune make test-integration` locally — all prune tests pass including `TestPruneLabelFilterNegative` and `TestPruneImageLabel`. 

Ready for re-reviewing.

**Review by vvoland — APPROVED** [review]
LGTM, thanks!

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by rrjjvv** [comment]
@vvoland @thaJeztah, on the surface, this appears to address one of my earlier reports in #50618; I'll verify when I get chance if you guys don't confirm and/or close first.
