### PR TITLE
Fix windows log file rotation with readers

### LINKED ISSUE #40999: Windows log rotation errors with active readers
On Windows, when the daemon attempts to rotate logs, if there is an active reader, the rotation fails.
This failure was totally unrecoverable until https://github.com/moby/moby/pull/40920
However that PR only allows the daemon to recover after an error.

The issue occurs when the daemon tries to rename a file that a log reader (e.g. `docker logs` client) has open.
This should have, based on the best info I've found, been fixed by using FILE_SHARE_DELETE (https://github.com/moby/moby/pull/39974), however that does not seem to be the case.
Furthermore, I've tried to apply this same change to all file opens in that package and still hit the same issue.

What this means right now is that if there is a `docker logs` client open and log rotation is enabled, if a file is ready for rotation then log writes will error out until the log client is gone.

### PR DESCRIPTION
**Pull request by cpuguy83**
This fixes the case where log rotation fails on Windows while there are
clients reading container logs.

Fixes https://github.com/moby/moby/issues/40999

### CODE REVIEW

**Comment by thaJeztah** [comment]
Seeing some failures on Windows RS5;

```
=== RUN   TestReadLog/tail_exact
    --- FAIL: TestReadLog/tail_exact (0.00s)
        local_test.go:146: assertion failed: error is not nil: error opening rotated log file: error opening file: The system cannot find the file specified.

=== RUN   TestReadLog/tail_less_than_available
    --- FAIL: TestReadLog/tail_less_than_available (0.00s)
        local_test.go:156: assertion failed: error is not nil: error opening rotated log file: error opening file: The system cannot find the file specified.

=== RUN   TestReadLog/tail_more_than_available
    --- FAIL: TestReadLog/tail_more_than_available (0.00s)
        local_test.go:164: assertion failed: error is not nil: error opening rotated log file: error opening file: The system cannot find the file specified.
```

**Comment by cpuguy83** [comment]
I see the problem. It's an error handling issue with `openFile`

**Comment by cpuguy83** [comment]
Should be fixed now.

**Comment by thaJeztah** [comment]
Hmm.. one failure remaining on RS5;

```
=== RUN   TestCheckCapacityAndRotate
--- FAIL: TestCheckCapacityAndRotate (0.01s)
    logfile_test.go:294: assertion failed: error is not nil: rename C:\Users\ContainerAdministrator\AppData\Local\Temp\TestCheckCapacityAndRotate612011099\log214931454 C:\Users\ContainerAdministrator\AppData\Local\Temp\TestCheckCapacityAndRotate612011099\log214931454.1: Access is denied.
```

**Comment by cpuguy83** [comment]
I do not know why this is failing now... It didn't fail until I changed to not wrap the error from open...

**Comment by cpuguy83** [comment]
Ok, so I had to change the this to evict log readers when there is an error rotating files.
I found that in this scenario:

1. Client opens log stream
2. Rotation occurs
3. Rotation occurs again

On step 3, the rotation will fail when it is trying to rename the current file.
It will either get an "Access is denied" error, or "file is being used by another process" error.

So on step 3, when an error occurs, it will evict readers and try again (a few times until successful || max retries).

The thinking here is allowing the container to make progress is more important than the log reader reading the logs.
We can't really seamlessly transfer the log reader without dropping logs anyway, so take the simpler route and have the client reconnect.
We pass the eviction error along to the client.

Without this change, log rotation is essentially broken on Windows if there are active log consumers.

**Comment by cpuguy83** [comment]
Added a 2nd commit to fix some race conditions in the loggerutils tests.
Additionally, I think I fixed the flakey test. See commit for details.

**Comment by thaJeztah** [comment]
@kevpar @kolyshkin ptal

**Comment by cpuguy83** [comment]
And split up commits for easier review.

**Comment by cpuguy83** [comment]
All green.

**Comment by thaJeztah** [comment]
@kevpar @kolyshkin ptal

File: daemon/logger/loggerutils/logfile.go [hunk 1]
```diff
@@ -204,15 +204,31 @@ func (w *LogFile) checkCapacityAndRotate() (retErr error) {
 	}
 
 	if err := rotate(fname, w.maxFiles, w.compress); err != nil {
-		return err
+		logrus.WithError(err).Warn("Error rotating log file, log data may hav been lost")
```
Comment (kolyshkin) [inline daemon/logger/loggerutils/logfile.go:207]: nit: `s/hav/have/`

File: daemon/logger/loggerutils/logfile.go [hunk 2]
```diff
@@ -569,7 +605,7 @@ func tailFiles(files []SizeReaderAt, watcher *logger.LogWatcher, dec Decoder, ge
 	}
 }
 
-func followLogs(f *os.File, logWatcher *logger.LogWatcher, notifyRotate chan interface{}, dec Decoder, since, until time.Time) {
+func followLogs(f *os.File, logWatcher *logger.LogWatcher, notifyRotate, notifytEvict chan interface{}, dec Decoder, since, until time.Time) {
```
Comment (kolyshkin) [inline daemon/logger/loggerutils/logfile.go:608]: nit: `s/notifytEvict/notifyEvict/`

**Comment by thaJeztah** [comment]
@kolyshkin nits are addressed; PTAL

**Comment by thaJeztah** [comment]
@kevpar @kolyshkin @tonistiigi ptal

**Comment by kevpar** [comment]
I don't have much context on this code, but the issue I'm aware of should be fixed by switching to do file opens with `FILE_SHARE_DELETE`. It looks like this PR consistently uses the `open`/`openFile` wrappers which do so, so LGTM.

File: daemon/logger/loggerutils/logfile.go [hunk 3]
```diff
@@ -179,45 +179,54 @@ func (w *LogFile) WriteLogEntry(msg *logger.Message) error {
...
+	}
+	file, err := openFile(fname, os.O_WRONLY|os.O_TRUNC|os.O_CREATE, w.perms)
+	if err != nil {
+		return err
+	}
+	w.f = file
+	w.currentSize = 0
+	w.notifyRotate.Publish(struct{}{})
+
+	if w.maxFiles <= 1 || !w.compress {
```
Comment (thaJeztah) [inline daemon/logger/loggerutils/logfile.go:233]: Perhaps `w.rotateMu.Unlock()` here, so that we don't have to do the extra check in the `defer`?

**Review by thaJeztah — COMMENTED** [review]
overall seems good; left one comment/suggestion (as discussed)

File: daemon/logger/loggerutils/logfile.go (hunk 3 above)
Comment (cpuguy83) [reply daemon/logger/loggerutils/logfile.go]: Updated, but more as we discussed on last weeks call.
This now sets a var for `noCompress := i w.maxFiles <= 1 || !w.compress`, then we check that var both in the defer and here.

Additionally added some docs around that in the defer.

**Review by thaJeztah — APPROVED** [review]
LGTM if green

**Comment by cpuguy83** [comment]
All green!

**Review by StefanScherer — APPROVED** [review]
LGTM

**Review by StefanScherer — APPROVED** [review]

**Review by tonistiigi — APPROVED** [review]
sgtm

File: daemon/logger/loggerutils/logfile.go [hunk 4]
```diff
@@ -167,56 +167,84 @@ func (w *LogFile) WriteLogEntry(msg *logger.Message) error {
...
 
-		if w.maxFiles <= 1 || !w.compress {
-			w.rotateMu.Unlock()
-			return nil
+	if err := rotate(fname, w.maxFiles, w.compress); err != nil {
+		logrus.WithError(err).Warn("Error rotating log file, log data may have been lost")
+	} else {
+		var renameErr error
+		for i := 0; i < 10; i++ {
+			if renameErr = os.Rename(fname, fname+".1"); renameErr != nil && !os.IsNotExist(renameErr) {
```
Comment (tianon) [inline daemon/logger/loggerutils/logfile.go:214]: If `fname.1` already exists, this will potentially be the same issue, right?  Should this use `i` or `i+1` instead?
(Sorry I'm not more familiar with this code to know whether this even makes sense :see_no_evil:)
