### PR TITLE
Fix to address regression caused by PR 30897

### LINKED ISSUE #36247: [18.02.0] Swarm service cannot attach to host network - "only one instance of "host" network is allowed"
According to the [compose file docs](https://docs.docker.com/compose/compose-file/#host-or-none), this fragment should create a swarm service whose instances are connected to the host`s network:

```yaml
services:
  web:
    ...
    networks:
      hostnet: {}

networks:
  hostnet:
    external:
      name: host
```

This used to work for me up to Docker 18.01.0-ce:
```bash
user@docker4:~$ cat hostnet.yml
version: '3.4'

services:
  web:
    image: nginx
    networks:
      hostnet: {}

networks:
  hostnet:
    external:
      name: host
user@docker4:~$ docker stack deploy -c hostnet.yml hostnet
Creating service hostnet_web
user@docker4:~$ docker service ps hostnet_web
ID                  NAME                IMAGE               NODE                DESIRED STATE       CURRENT STATE            ERROR               PORTS
ekh2x9fiftwn        hostnet_web.1       nginx:latest        docker4             Running             Running 10 seconds ago
```
WIth Docker 18.02.0, deployment fails with *only one instance of \"host\" network is allowed"*:
```bash
user@docker4:~$ docker stack deploy -c hostnet.yml hostnet
Creating service hostnet_web
user@docker4:~$ docker service ps hostnet_web
ID                  NAME                IMAGE               NODE                DESIRED STATE       CURRENT STATE            ERROR                              PORTS
tbrwxomncmxh        hostnet_web.1       nginx:latest        docker4             Ready               Rejected 2 seconds ago   "only one instance of "host" n…"
5wfft46phw7n         \_ hostnet_web.1   nginx:latest        docker4             Shutdown            Rejected 7 seconds ago   "only one instance of "host" n…"
o95qdlf4w029         \_ hostnet_web.1   nginx:latest        docker4             Shutdown            Rejected 8 seconds ago   "only one instance of "host" n…"
```
Log output:

    ERRO[2018-02-08T15:46:59.635485455+01:00] fatal task error   error="only one instance of \"host\" network is allowed" module=node/agent/taskmanager node.id=[...] task.id=[...]

<details>
  <summary>Output of `docker version`</summary>

```
Client:
 Version:       18.02.0-ce
 API version:   1.36
 Go version:    go1.9.3
 Git commit:    fc4de44
 Built: Wed Feb  7 21:16:33 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.02.0-ce
  API version:  1.36 (minimum version 1.12)
  Go version:   go1.9.3
  Git commit:   fc4de44
  Built:        Wed Feb  7 21:15:05 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

</details>

<details>
  <summary>Output of `docker info`</summary>

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 133
Server Version: 18.02.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 222
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 5tgj049z74d8bigq4osjujr1b
 Is Manager: true
 ClusterID: oy18buvxbbqb00libidep5kx9
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.0.1.51
 Manager Addresses:
  10.0.1.51:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-112-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 11.72GiB
Name: docker4
ID: BHDU:YEDX:7NMN:QIHK:PFXZ:MWOX:5WZF:FZTK:3RDE:GAEY:U7L2:NP72
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

</details>

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Both command sequences were issued on the same box, a Ubuntu 16.04 LTS running on VMware workstation. Same behaviour on a three-node swarm cluster.

### PR DESCRIPTION
**Pull request by selansen**
fixes https://github.com/moby/moby/issues/36247

With the inclusion of PR https://github.com/moby/moby/pull/30897, creating service for host network fails in 18.02. Modified IsPreDefinedNetwork check and return NetworkNameError instead of errdefs.Forbidden to address this issue

Signed-off-by: selansen <elango.siva@docker.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: daemon/network.go [hunk 1]
```diff
@@ -267,9 +267,9 @@ func (daemon *Daemon) CreateNetwork(create types.NetworkCreateRequest) (*types.N
 }
 
 func (daemon *Daemon) createNetwork(create types.NetworkCreateRequest, id string, agent bool) (*types.NetworkCreateResponse, error) {
-	if runconfig.IsPreDefinedNetwork(create.Name) && !agent {
-		err := fmt.Errorf("%s is a pre-defined network and cannot be created", create.Name)
-		return nil, errdefs.Forbidden(err)
+	if runconfig.IsPreDefinedNetwork(create.Name) {
+		logrus.Debugf("%s is a pre-defined network and cannot be created", create.Name)
+		return nil, libnetwork.NetworkNameError(create.Name)
```
Comment (cpuguy83) [inline daemon/network.go]: I still think this should be wrapped in a `errdefs.Forbidden(err)`, but callers that need to check the error for `NetworkNameError` should check against `errors.Cause(err)`

**Comment by selansen** [comment]
In the same function below we do exact same logic. May I know is there any
advantage are we going to get by throwing errdefs.Forbidden instead of
NetworkNameError ?
I can go ahead and modify but just trying to understand if I am missing
anything with your suggestion.
Thanks in advance.

**Comment by cpuguy83** [comment]
The error wrapping in this case is so that we return the correct error code to the API.

**Comment by cpuguy83** [comment]
```
04:57:16 FAIL: docker_api_network_test.go:241: DockerSuite.TestAPICreateDeletePredefinedNetworks
04:57:16 
04:57:16 docker_api_network_test.go:243:
04:57:16     createDeletePredefinedNetwork(c, "bridge")
04:57:16 docker_api_network_test.go:323:
04:57:16     c.Assert(resp.StatusCode, checker.Equals, expectedStatusCode)
04:57:16 ... obtained int = 409
04:57:16 ... expected int = 403
```

**Comment by selansen** [comment]
That make sense. will change it as per your suggestion and let the caller
handle error case according to their requirement.
Thanks.

**Comment by thaJeztah** [comment]
@selansen this fixes https://github.com/moby/moby/pull/36316 correct?

**Comment by selansen** [comment]
You mean 36247 ??? Yes.

**Comment by thaJeztah** [comment]
errr, copy/pasta error, yes, meant https://github.com/moby/moby/issues/36247

**Comment by selansen** [comment]
Yes. But looks like fix  is causing existing test case failure. Let me dig
deeper while addressing cpuguy83 suggestion.

**Comment by ddebroy** [comment]
We also need a test to make sure similar regression does not happen. Maybe add a test to make sure attaching to `host` and other "predefined" networks work fine with both swarm services and regular containers as well as a unit test to make sure the "predefined" networks are properly rejected.

File: daemon/cluster/executor/container/adapter.go [hunk 2]
```diff
@@ -153,6 +154,11 @@ func (c *containerAdapter) createNetworks(ctx context.Context) error {
 			if _, ok := err.(libnetwork.NetworkNameError); ok {
 				continue
 			}
+			// We will continue if CreateManagedNetwork returns forbidden error.
+			// Other callers still can treat it as Error.
+			if errdefs.IsForbidden(err) {
```
Comment (thaJeztah) [inline daemon/cluster/executor/container/adapter.go]: I’ll have to give this more thinking (haven’t looked at what other situations return), but isn’t the case where we try to create a pre-defined network a _conflict_ (i.e. the network already “exists”).

Forbidden sounds like “you don’t have access to this endpoint” (but you do). Other options would be “invalid argument” (passed value is not valid)

Just dumping my thinking here, so that I don’t forget :smile:

Comment (cpuguy83) [reply daemon/cluster/executor/container/adapter.go]: Conflict would imply that if the state changed then it would be possible to perform the action. In this case it is not allowed.

Comment (selansen) [reply daemon/cluster/executor/container/adapter.go]: Predefined networks are created when Daemon starts. When user creates service with predefined network, we know that network already exists and return saying you can't create. But service creation still can go ahead as the predefined network exists already. so we can ignore this error and continue in this scenario.

Comment (thaJeztah) [reply daemon/cluster/executor/container/adapter.go]: > Conflict would imply that if the state changed then it would be possible to perform the action. In this case it is not allowed.

Right, yes. I was looking at the 403 because I wondered if it could cause issues in situations where a 403 could also occur due to authentication issues to the API. A generic `400` (bad request - the name is reserved/invalid) could've been an option for that.


Looking at [`NetworkNameError`](https://github.com/docker/libnetwork/blob/cb09a3770a365d8a4ed54f66e284041daf09ddef/error.go#L101-L108), I see that is also a "Forbidden" error; should we be more specific in this case, and check if it's actually a "forbidden" error, because it's a predefined network?

Given that we already walk different paths inside `createNetwork()` if the caller is `agent`, we could also use the `agent` option to just return a `nil`  instead;

```go
if runconfig.IsPreDefinedNetwork(create.Name) {
   if agent {
      return nil, nil
   }
    err := fmt.Errorf("%s is a pre-defined network and cannot be created", create.Name)
    return nil, errdefs.Forbidden(err)
}
```

**Comment by selansen** [comment]
I still believe instead of returning nil in case of agent is true, we let
the caller decides the error information. Because setupIngress() also calls
createNetwork with agent=true option.

**Comment by thaJeztah** [comment]
> I still believe instead of returning nil in case of agent is true, we let the caller decides the error information. Because setupIngress() also calls createNetwork with agent=true option.

Yeah not a big fan of the `agent` boolean (it's changing the behaviour of that function; perhaps that needs a refactor).

If we keep the check in the other location, should we be more specific though (as I mentioned above)?

**Comment by selansen** [comment]
@thaJeztah , I can add new Forbidden Error type say "PredefinedNetworkExistError" and use it in all the places accordingly. Would that be  ok with you?

**Comment by thaJeztah** [comment]
@selansen yes, if you can add an error so that we can distinguish if the error was due to "predefined network" and not some other "forbidden" error, that would be good.

File: daemon/network.go [hunk 3]
```diff
@@ -267,7 +267,7 @@ func (daemon *Daemon) CreateNetwork(create types.NetworkCreateRequest) (*types.N
 }
 
 func (daemon *Daemon) createNetwork(create types.NetworkCreateRequest, id string, agent bool) (*types.NetworkCreateResponse, error) {
-	if runconfig.IsPreDefinedNetwork(create.Name) && !agent {
+	if runconfig.IsPreDefinedNetwork(create.Name) {
```
Comment (ddebroy) [inline daemon/network.go]: Sorry for this late comment. Do we really need the `IsPreDefinedNetwork` logic here? I was discussing with Flavio a bit and it seems `daemon.GetNetworkByName` right below should be able to reject all PreDefined networks. This way, we will not even need `IsPreDefinedNetwork` above.

Comment (ddebroy) [reply daemon/network.go]: Just discussed a bit and we do need separate code paths for Pre-Defined vs User-defined as we do allow name conflicts for the latter category.

Comment (selansen) [reply daemon/network.go]: Thats is what I h added originally. I was reluctant to change.  But we need to be able to differentiate  regular network name exist and predefined network exist .  Review comments were asking me to be more specific to error reports to the callers. Hence I added new type .

**Comment by selansen** [comment]
@thaJeztah CI tests results looks good. only one test is failing . That is failing due to below test case. I looked into it. Its not related to above changes.
----------------------------------------------------------------------
18:25:05 FAIL: check_test.go:366: DockerSwarmSuite.TearDownTest
18:25:05 
18:25:05 unmount of /tmp/docker-execroot/d9cc520883592/netns failed: invalid argument
18:25:05 unmount of /tmp/docker-execroot/d9cc520883592/netns failed: no such file or directory
18:25:05 check_test.go:371:
18:25:05     d.Stop(c)
18:25:05 daemon/daemon.go:389:
18:25:05     t.Fatalf("Error while stopping the daemon %s : %v", d.id, err)
18:25:05 ... Error: Error while stopping the daemon d58c8df026d8e : exit status 130
18:25:05

**Review by thaJeztah — CHANGES_REQUESTED** [review]
one nit/question, but otherwise looks good

File: daemon/network.go [hunk 4]
```diff
@@ -528,6 +537,7 @@ func (daemon *Daemon) deleteNetwork(nw libnetwork.Network, dynamic bool) error {
 	if runconfig.IsPreDefinedNetwork(nw.Name()) && !dynamic {
 		err := fmt.Errorf("%s is a pre-defined network and cannot be removed", nw.Name())
 		return errdefs.Forbidden(err)
+		//return PredefinedNetworkError(nw.Name())
```
[the remark this answers is not in the document]
Comment (selansen) [reply daemon/network.go]: Let me remove it. I was testing it . but forgot to remove it.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@selansen looks like there's a golint failure:

```
23:16:50 integration/network/service_test.go:67:10:warning: if block ends with a return statement, so drop this else and outdent its block (golint)
23:16:50 Build step 'Execute shell' marked build as failure
```

File: integration/network/service_test.go [hunk 5]
```diff
@@ -0,0 +1,71 @@
...
+func serviceRunningCount(client client.ServiceAPIClient, serviceID string, instances uint64) func(log poll.LogT) poll.Result {
+	return func(log poll.LogT) poll.Result {
+		filter := filters.NewArgs()
+		filter.Add("service", serviceID)
+		services, err := client.ServiceList(context.Background(), types.ServiceListOptions{})
+		if err != nil {
+			return poll.Error(err)
+		}
+
+		if len(services) != int(instances) {
```
Comment (thaJeztah) [inline integration/network/service_test.go]: To make golint happy, change this to

```go
		if len(services) != int(instances) {
			return poll.Continue("Service count at %d waiting for %d", len(services), instances)
		}
		return poll.Success()
```

Comment (selansen) [reply integration/network/service_test.go]: Already fixed golint changes and all test cases passed now.

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

File: integration/network/service_test.go [hunk 6]
```diff
@@ -0,0 +1,70 @@
...
+
+	poll.WaitOn(t, serviceIsRemoved(client, serviceID), pollSettings)
+	poll.WaitOn(t, noTasks(client), pollSettings)
+
+}
+
+func serviceRunningCount(client client.ServiceAPIClient, serviceID string, instances uint64) func(log poll.LogT) poll.Result {
+	return func(log poll.LogT) poll.Result {
+		filter := filters.NewArgs()
+		filter.Add("service", serviceID)
```
Comment (dnephin) [inline integration/network/service_test.go]: This `filter` is not  used. Was it supposed to be set in `ServiceListOptions` ?

You can build these inline now, which would prevent such an issue:

```go
filters.NewArgs(filter.Arg("service", serviceID))
```
