### PR TITLE
Fix issue backporting mount spec to pre-1.13 obj

### LINKED ISSUE #32613: Named volume incorrectly removed after engine upgrade
**Description**

A named volume associated to a container before a Docker Engine upgrade will be removed by `docker rm -v <container>` after the upgrade.

**Steps to reproduce the issue:**
1. Downgrade to Docker Engine 1.12.6: `sudo apt install docker-engine=1.12.6-0~ubuntu-xenial`
1. Create a named volume: `docker volume create --name foo`
2. Create a container mounting the newly created volume: `docker run --name repro -v foo:/foomnt alpine true`
3. Upgrade Docker Engine to the latest version: `sudo apt upgrade`
3. Remove the container created earlier with the `--volumes` option: `docker rm -v repro`

**Describe the results you received:**

The named volume is removed alongside the container.

**Describe the results you expected:**

The named volume remains after the container is removed.

**Additional information you deem important (e.g. issue happens only occasionally):**

Originally reported here: https://github.com/docker/compose/issues/4607
Note that the volume isn't removed if it was created with the same engine version.

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 109
Server Version: 17.04.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 249
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: sg2ufch61oe8j2ndv2vwqtehp
 Is Manager: true
 ClusterID: xhbxxpaiwazbnrfy0ms860ia8
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.100.237
 Manager Addresses:
  192.168.100.237:2377
Runtimes: runc
Default Runtime: runc
Init Binary: 
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-72-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.499GiB
Name: yuna
ID: YZQG:AKYJ:JQXJ:CEHT:62DP:PMWA:S43W:5X47:SSOE:UXGG:XHWS:555F
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

### PR DESCRIPTION
**Pull request by cpuguy83**
In some cases a mount spec would not be properly backported which could
lead to accidental removal of the underlying volume on container remove
(which should never happen with named volumes).

Adds unit tests for this as well. Unfortunately I had to add a daemon
depdency for the backport function due to looking up `VolumesFrom`
specs.

Fixes #32613 

0b2ae20f3e1272496e3ecf9d4a17e996

### CODE REVIEW

**Comment by thaJeztah** [comment]
@cpuguy83 tests are failing, and looks related

**Comment by cpuguy83** [comment]
All green

**Comment by thaJeztah** [comment]
ping @cpuguy83 looks like it needs a rebase :cry:

**Comment by cpuguy83** [comment]
rebased

**Comment by thaJeztah** [comment]
ping @dnephin @stevvooe PTAL

**Review by vdemeester — APPROVED** [review]
LGTM 🐯

File: daemon/volumes.go [hunk 1]
```diff
@@ -239,48 +241,120 @@ func (daemon *Daemon) lazyInitializeVolume(containerID string, m *volume.MountPo
...
+		return false
+	}
 
-			// make sure this is not an anonymous volume before setting the spec source
-			if _, exists := container.Config.Volumes[target]; !exists {
-				m.Spec.Source = m.Name
+	for _, cm := range container.MountPoints {
+		// nothing to backport if from hostconfig.Mounts
+		if mountSpecs[cm.Destination] {
+			continue
```
Comment (thaJeztah) [inline daemon/volumes.go]: Will this be an issue if both the container itself, and the `--volumes-from` container specify a volume for the same destination? (and the `--volumes-from` needs updating)

**Review by thaJeztah — CHANGES_REQUESTED** [review]
left some questions ☺️

File: daemon/volumes.go (hunk 1 above)
Comment (cpuguy83) [inline daemon/volumes.go]: `-volumes-from` is lowest precedence.
Can't have two mountpoints with the same destination.

File: daemon/volumes.go [hunk 2]
```diff
@@ -239,48 +241,120 @@ func (daemon *Daemon) lazyInitializeVolume(containerID string, m *volume.MountPo
...
+						cm.Spec = mp.Spec
+						updated = true
+					}
+					continue
 				}
-				m.Spec.VolumeOptions.NoCopy = true
 			}
+
+			if cm.Type != "" {
+				// probably specified view the hostconfig.Mounts
```
Comment (cpuguy83) [inline daemon/volumes.go]: hah, *via

File: daemon/volumes.go [hunk 3]
```diff
@@ -239,48 +241,120 @@ func (daemon *Daemon) lazyInitializeVolume(containerID string, m *volume.MountPo
...
-					m.Spec.VolumeOptions = &mounttypes.VolumeOptions{}
+
+			for _, fromSpec := range container.HostConfig.VolumesFrom {
+				from, _, err := volume.ParseVolumesFrom(fromSpec)
+				if err != nil {
+					logrus.WithError(err).WithField("id", container.ID).Error("error reading volumes-from spec during mount spec backport")
+				}
+				fromC, err := daemon.GetContainer(from)
+				if err != nil {
+					logrus.WithError(err).WithField("from-container", from).Error("Error looking up volumes-from container")
```
Comment (cpuguy83) [inline daemon/volumes.go]: Yes need continue (or something), nice catch.

Logged errors are typically capitalized.

Comment (thaJeztah) [inline daemon/volumes.go]: In that case, capitalize the error at line 298 👍

File: daemon/volumes.go [hunk 4]
```diff
@@ -239,48 +241,114 @@ func (daemon *Daemon) lazyInitializeVolume(containerID string, m *volume.MountPo
...
+	mountSpecs := make(map[string]bool, len(container.HostConfig.Mounts))
+	for _, m := range container.HostConfig.Mounts {
+		mountSpecs[m.Target] = true
+	}
+
+	binds := make(map[string]*volume.MountPoint, len(container.HostConfig.Binds))
+	for _, rawSpec := range container.HostConfig.Binds {
+		mp, err := volume.ParseMountRaw(rawSpec, container.HostConfig.VolumeDriver)
+		if err != nil {
+			logrus.WithError(err).Error("Got unepxected error while re-parsing raw volume spec during spec backport")
```
Comment (thaJeztah) [inline daemon/volumes.go]: typo `s/unepxected/unexpected/`

File: daemon/volumes.go [hunk 5]
```diff
@@ -239,48 +241,114 @@ func (daemon *Daemon) lazyInitializeVolume(containerID string, m *volume.MountPo
...
 			}
-			if container.HostConfig.VolumeDriver != "" {
-				m.Spec.VolumeOptions = &mounttypes.VolumeOptions{
-					DriverConfig: &mounttypes.Driver{Name: container.HostConfig.VolumeDriver},
+			continue
+		}
+
+		if cm.Name != "" {
+			if mp, exists := volumesFrom[cm.Destination]; exists {
+				if needsUpdate(cm, &mp) {
```
Comment (thaJeztah) [inline daemon/volumes.go]: Wondering in what situation this would need an update; `cm.Destination` is only added to `volumesFrom` if we entered the `for _, fromSpec := range container.HostConfig.VolumesFrom {` loop below, in which case the `needsUpdate()` check is already performed.

Should this just be `continue`?

File: daemon/volumes.go [hunk 6]
```diff
@@ -239,48 +241,114 @@ func (daemon *Daemon) lazyInitializeVolume(containerID string, m *volume.MountPo
...
 				}
-				m.Spec.VolumeOptions.NoCopy = true
+				fromC, err := daemon.GetContainer(from)
+				if err != nil {
+					logrus.WithError(err).WithField("from-container", from).Error("Error looking up volumes-from container")
+					continue
+				}
+
+				// make sure from container's specs have been backported
+				daemon.backportMountSpec(fromC)
```
Comment (thaJeztah) [inline daemon/volumes.go]: We no longer write updated mount-specs to disk for `volumes-from` containers, only in-memory, correct?

**Review by thaJeztah — CHANGES_REQUESTED** [review]
found a typo, and some questions 😅

File: daemon/volumes.go (hunk 6 above)
Comment (cpuguy83) [inline daemon/volumes.go]: In this function yes, they are persisted to disk in the caller.
I can add a note to that in the docstring.

File: daemon/volumes.go (hunk 5 above)
Comment (cpuguy83) [inline daemon/volumes.go]: Let me just move this stuff up to make the code simpler.
I was trying to save some time and not process volumes-from if not-neccessary, but the code is very messy.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
All green! Checked with @vdemeester earlier, and this still looked good to him

File: daemon/volumes.go [hunk 7]
```diff
@@ -239,48 +241,124 @@ func (daemon *Daemon) lazyInitializeVolume(containerID string, m *volume.MountPo
...
+			continue
+		}
+		binds[mp.Destination] = mp
+	}
+
+	volumesFrom := make(map[string]volume.MountPoint)
+	for _, fromSpec := range container.HostConfig.VolumesFrom {
+		from, _, err := volume.ParseVolumesFrom(fromSpec)
+		if err != nil {
+			logrus.WithError(err).WithField("id", container.ID).Error("Error reading volumes-from spec during mount spec backport")
```
Comment (thaJeztah) [inline daemon/volumes.go]: Missed this in my review; needs a `continue` (see https://github.com/moby/moby/pull/33207#discussion_r116583731)

Comment (cpuguy83) [inline daemon/volumes.go]: #33209

**Comment by thaJeztah** [comment]
cherry-picked for 17.03.2 in https://github.com/moby/moby/pull/33207
