### PR TITLE
Validate docker-load receives a tar file

### LINKED ISSUE #25363: Always "hang" when I run  `Docker load` without paramter
**Output of `docker version`: 
1.12

```
(paste your output here)
```

Sams-MacBook-Pro:default samchen$ docker load 

**Output of `docker info`:**
Sams-MacBook-Pro:default samchen$ docker info
Containers: 39
 Running: 1
 Paused: 0
 Stopped: 38
Images: 226
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 318
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null overlay host
Swarm: active
 NodeID: bqo9wjuolar5qk0qm8v3nnmg1
 Is Manager: true
 ClusterID: f350z8ybay7jshcq2k97rilnw
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot interval: 10000
  Heartbeat tick: 1
  Election tick: 3
 Dispatcher:
  Heartbeat period: 5 seconds
 CA configuration:
  Expiry duration: 3 months
 Node Address: 192.168.65.2
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: moby
ID: KCVJ:4PIN:RF33:55IX:TM6S:KCKT:SEVN:RCMR:COUK:RO4Z:AK5Z:SBQH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 40
 Goroutines: 126
 System Time: 2016-08-03T11:11:08.657760542Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Install Mac Docker distribution 1.12
2. run "docker load"
3.

**Describe the results you received:**

**Describe the results you expected:**
It supposed to prompt up "syntax" or "usage"

**Additional information you deem important (e.g. issue happens only occasionally):**

### PR DESCRIPTION
**Pull request by boaz0**
**- What I did**
Should close #25363 
Print an error message if the tar file isn't specified using either the input argument or stdin.

**- How I did it**
Checking the docker CLI input is not a terminal or the input argument is set.

**- How to verify it**
Run:
```
TESTFLAGS='-check.f DockerSuite.TestLoadNoStdinFail' hack/make.sh test-integration-cli
```
```
TESTFLAGS='-check.f DockerSuite.TestSaveAndLoadWithProgressBar' hack/make.sh test-integration-cli
```

**- Description for the changelog**

To load an image from a tar file, you can specify the tar file in the -i/--input option:
docker load -i image_1.tar

or using stdin:

docker load < image_1.tar
cat image_1.tat | docker load

If the image file isn't given the `docker load` command gets stuck.

To avoid that, the load makes sure the CLI input is not a terminal or the `--input` option was set.
If not then an error message is shown.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by ripcurld00d** [comment]
@jhowardmsft -- Sorry for bothering you again.
But do you think we can test this also on Windows?

File: cli/command/image/load.go [hunk 1]
```diff
@@ -49,6 +50,9 @@ func runLoad(dockerCli *command.DockerCli, opts loadOptions) error {
 		defer file.Close()
 		input = file
 	}
+	if opts.input == "" && dockerCli.In().IsTerminal() {
+		return fmt.Errorf("a tar file is not given (e.g. docker load < image.tar)")
```
Comment (cpuguy83) [inline cli/command/image/load.go]: Maybe "requested load from stdin, but stdin is empty"

Comment (cpuguy83) [inline cli/command/image/load.go]: And maybe a comment above the `if` so other people know what this is for specifically.

File: integration-cli/docker_cli_save_load_unix_test.go [hunk 2]
```diff
@@ -86,3 +86,21 @@ func (s *DockerSuite) TestSaveAndLoadWithProgressBar(c *check.C) {
...
+
+// fail because load didn't receive data from stdin
+func (s *DockerSuite) TestLoadNoStdinFail(c *check.C) {
+	pty, tty, err := pty.Open()
+	c.Assert(err, check.IsNil)
+	cmd := exec.Command(dockerBinary, "load")
+	cmd.Stdin = tty
+	cmd.Stdout = tty
+	cmd.Stderr = tty
+	c.Assert(cmd.Start(), check.IsNil)
```
Comment (cpuguy83) [inline integration-cli/docker_cli_save_load_unix_test.go]: `cmd.Run()` then there is no need for `cmd.Wait()`

**Review by cpuguy83 — CHANGES_REQUESTED** [review]

File: cli/command/image/load.go (hunk 1 above)
Comment (ripcurld00d) [inline cli/command/image/load.go]: :+1: totally

File: integration-cli/docker_cli_save_load_unix_test.go (hunk 2 above)
Comment (cpuguy83) [inline integration-cli/docker_cli_save_load_unix_test.go]: Well, `Start() && Wait()` is the same thing as `Run()`.
What we can do is use https://golang.org/pkg/os/exec/#CommandContext and set a timeout.

Comment (ripcurld00d) [inline integration-cli/docker_cli_save_load_unix_test.go]: Sounds like a plan! :+1:

**Comment by ripcurld00d** [comment]
@cpuguy83 thanks for your review.
Can you please review the new changes?
:beers:

**Review by cpuguy83 — APPROVED** [review]
LGTM If janky is happy

**Review by thaJeztah — APPROVED** [review]
LGTM
