### PR TITLE
rootless: overlay2: support native overlay diff when using rootless-mode in kernel 5.11 and above

### LINKED ISSUE #43626: Rootless Docker Service doesn't use native overlayfs (` Native Overlay Diff: false`)
**Rootless Docker Service doesn't use native overlayfs**

Rootless Docker Service doesn't use native overlayfs despite modprobe options:
```options overlay metacopy=off redirect_dir=off```
whereas, the root Docker service works as expected.

**Steps to reproduce the issue:**
1. export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock
2. systemctl --user start docker.service
3. docker info | grep Native

**Describe the results you received:**
  Native Overlay Diff: false

**Describe the results you expected:**
  Native Overlay Diff: true

**Output of `docker version`:**

```
Docker version 20.10.16, build aa7e414fdc
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., 2.5.1)

Server:
 Containers: 6
  Running: 2
  Paused: 0
  Stopped: 4
 Images: 4
 Server Version: 20.10.16
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: none
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 212e8b6fa2f44b9c21b2798135fc6fb7c53efc16.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  rootless
  cgroupns
 Kernel Version: 5.15.40-1-lts
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 62.47GiB
 Name: phantom
 ID: SMDW:PBEU:YHFR:NAVA:5WGK:ELUL:YRF3:SIHN:JEZB:FV52:LQZD:GUSE
 Docker Root Dir: /home/sighoya/vm/docker
 Debug Mode: true
  File Descriptors: 40
  Goroutines: 59
  System Time: 2022-05-21T16:02:20.585738277+02:00
  EventsListeners: 0
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: Running in rootless-mode without cgroups. Systemd is required to enable cgroups in rootless-mode.

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
ArchLinux Linux phantom 5.15.40-1-lts #1 SMP Sun, 15 May 2022 19:07:59 +0000 x86_64 GNU/Linux

See also: https://github.com/moby/moby/issues/41802

### PR DESCRIPTION
**Pull request by jonasgeiler**
Closes #43626 

**- What I did**
I have implemented the changes I have proposed in #43626 to the best of my knowledge. This should hopefully fix native diff detection for the overlay2 storage driver on rootless docker installations.

**- How I did it**
I mostly took inspiration from the [equivalent function in the podman source code](https://github.com/containers/storage/blob/b0c3d9650bfb3b32a312640ae581f9fc7811bb87/drivers/overlay/check.go#L29). Native overlay diff always worked without problems on podman so I thought I'd check what they do differently, and I noticed that Native Overlay Diff is always disabled on rootless docker, even if it is supported by kernel 5.11 and above.
I'm not exactly sure if I did everything correctly since I'm still a beginner when it comes to Go and this is my first PR. It would be great if someone could double check these changes on their machine (my `make test` run failed after an hour with seemingly unrelated issues...).
Although, @AkihiroSuda and @thaJeztah have acknowledged these changes in #43626.

**- How to verify it**
To the best of my knowledge, the `Native Overlay Diff` entry in `docker info` always returns `false` in rootless-mode since it only checks if we are in a user namespace. After the changes I've made `Native Overlay Diff` should be set to `true` in `docker info`, when supported by the kernel version and when rootless-mode is properly set up.
Also, this warning message when starting the docker service should not show up anymore in kernel 5.11 and above, or at least have a different reason for why it's not supported:
```
Not using native diff for overlay2, this may cause degraded performance for building images: running in a user namespace
```
It should also be double checked there aren't any errors when pulling images like `docker --context=rootless pull python:3.9` and `docker --context=rootless pull hello-world`.

**- Description for the changelog**
```markdown changelog
rootless: overlay2: support native overlay diff when using rootless-mode in kernel 5.11 and above
```
(open for better changelog suggestions...)

**- A picture of a cute animal (not mandatory but encouraged)**
:shipit:

### CODE REVIEW

File: daemon/graphdriver/overlay2/check.go [hunk 1]
```diff
@@ -22,11 +23,23 @@ import (
...
-// immediately.
+// When running in a user namespace before kernel 5.11, returns
+// errRunningInUserNS immediately. In kernel 5.11 and later, we
+// check support as usual with some user namespace differences.
 func doesSupportNativeDiff(d string) error {
+	userxattr := false
 	if userns.RunningInUserNS() {
-		return errors.New("running in a user namespace")
+		if !kernel.CheckKernelVersion(5, 11, 0) {
+			return errors.New("running in a user namespace")
```
Comment (jonasgeiler) [inline daemon/graphdriver/overlay2/check.go:33]: I'm not sure if it's okay to just edit error messages or if that breaks stuff, but this error message should probably improved and suggest updating the kernel, like one of the error messages below.

File: daemon/graphdriver/overlay2/check.go [hunk 2]
```diff
@@ -22,11 +23,23 @@ import (
...
-// When running in a user namespace, returns errRunningInUserNS
-// immediately.
+// When running in a user namespace before kernel 5.11, returns
+// errRunningInUserNS immediately. In kernel 5.11 and later, we
+// check support as usual with some user namespace differences.
 func doesSupportNativeDiff(d string) error {
+	userxattr := false
 	if userns.RunningInUserNS() {
-		return errors.New("running in a user namespace")
+		if !kernel.CheckKernelVersion(5, 11, 0) {
```
Comment (neersighted) [inline daemon/graphdriver/overlay2/check.go:32]: We generally do not want to introduce any new kernel version checks; this code should instead rely solely on the functional test.

Comment (jonasgeiler) [reply daemon/graphdriver/overlay2/check.go]: I have just commited a hopefully better solution which makes use of the existing `userxattr` check, since there is already a kernel version check in `NeedsUserXAttr()`. Unfortunately I cannot confirm if the new solution can cause problems in cases where `userxattr` is supported, while Native Overlay Diff isn't 🤔 I'll try to cross-check with previous bug reports to verify when I have the time.

**Comment by jonasgeiler** [comment]
Hmm okay bad news: I just manually tested a dev build of this PR and I got the following error when pulling `archlinux`:
```
failed to register layer: setxattr("/var/cache/ldconfig", trusted.overlay.opaque=y): operation not permitted
```
Looks like it's caused by the usage of `trusted.overlay.opaque` instead of `user.overlay.opaque` at https://github.com/moby/moby/blob/59c5059081c42035ab2c14f4726dd997a1b0a666/pkg/archive/archive_linux.go#L72
I will attempt to fix it by just doing the same thing I did in `check.go`

**Comment by jonasgeiler** [comment]
> Hmm okay bad news: I just manually tested a dev build of this PR and I got the following error when pulling `archlinux`:
> 
> ```
> failed to register layer: setxattr("/var/cache/ldconfig", trusted.overlay.opaque=y): operation not permitted
> ```
> 
> Looks like it's caused by the usage of `trusted.overlay.opaque` instead of `user.overlay.opaque` at
> 
> https://github.com/moby/moby/blob/59c5059081c42035ab2c14f4726dd997a1b0a666/pkg/archive/archive_linux.go#L72-L75
> 
> I will attempt to fix it by just doing the same thing I did in `check.go`

Alright, I think I've fixed the problem. I tested it now on Debian 11, Debian 12 and Ubuntu LTS 20.04 and it seems to work on all three without problems (so far).
Open for review!

File: daemon/graphdriver/overlay2/check.go [hunk 3]
```diff
@@ -22,11 +22,21 @@ import (
...
 	if userns.RunningInUserNS() {
-		return errors.New("running in a user namespace")
+		needed, err := overlayutils.NeedsUserXAttr(d)
+		if err != nil {
+			return err
+		}
+		if needed {
+			userxattr = true
+		} else {
+			return errors.New("not supported in user namespace, consider updating to kernel 5.11 or later to fix")
```
Comment (AkihiroSuda) [inline daemon/graphdriver/overlay2/check.go:38]:
```suggestion
			return errors.New("native diff is not supported in user namespace, consider updating to kernel 5.11 or later to fix")
```

**Review by AkihiroSuda — APPROVED** [review]

**Comment by vvoland** [comment]
The signoff check fails with:
```
Author: Jonas Geiler, Committer: GitHub; Expected "Jonas Geiler [github@jonasgeiler.com](mailto:github@jonasgeiler.com)", but got "Jonas Geiler [git@jonasgeiler.com](mailto:git@jonasgeiler.com)".
```

Looks like there's an e-mail mismatch between the sign-off and the commit author?

**Review by neersighted — APPROVED** [review]

**Review by dmcgowan — APPROVED** [review]

**Review by vvoland — APPROVED** [review]
