### PR TITLE
libnetwork: fix graceful service endpoint removal

### LINKED ISSUE #51651: Established tcp sessions seem to hang / drop when trying to bring down container cleanly after `docker service remove`
### Description

I have my entrypoint script setup to trap SIGTERM and cleanly shut down the running processes/activities inside my docker container.  In 28.5, this works cleanly, but  after upgrading to 29.0.2 and 29.0.4, it seems that **established** tcp sessions into the docker container are killed, or hang until the time limit that docker starts killing processes.

If there are no established tcp sessions, the container shuts down cleanly.  

Falling back to 28.5 reverted the behavior back to clean shutdown. 

### Reproduce

Use the following compose file
```yaml
version: "3.9"

networks:
  back-tier: {}

services:
  tcptest:
    image: ruby:3.4.5-slim
    ports:
      - "7800:7800"
    networks:
      back-tier: {}
    volumes:
      - /path/to/ruby/script:/usr/src/myapp
    stop_grace_period: 5m
    command: ruby /usr/src/myapp/entrypoint.rb
```

with the following ruby script:
```ruby
#!/usr/bin/env ruby
require 'socket'
require 'securerandom'
require 'time'
require 'json'

PORT = 7800

$stdout.sync = true

server = TCPServer.new(PORT)
$stdout.puts "Listening on port #{PORT}..."

shutdown_requested = false
shutdown_at = nil

Signal.trap("TERM") do
  unless shutdown_requested
    shutdown_requested = true
    shutdown_delay = rand(120..180) # 2–3 minutes
    shutdown_at = Time.now + shutdown_delay
    $stdout.puts "SIGTERM received, shutting down in #{shutdown_delay} seconds"
  end
end

loop do
  break if shutdown_requested && Time.now >= shutdown_at

  $stdout.puts "Waiting for client..."
  client = server.accept
  $stdout.puts "Client connected"

  # Notify client if shutdown already requested
  if shutdown_requested
    client.write("[SERVER] Shutdown pending, terminating at #{shutdown_at.utc.iso8601}\n")
  end

  begin
    loop do
      break if shutdown_requested && Time.now >= shutdown_at

      # Echo client input (non-blocking)
      if IO.select([client], nil, nil, 0)
        data = client.read_nonblock(1024)
        client.write(data)
      end

      # Heartbeat message
      heartbeat = {
        timestamp: Time.now.utc.iso8601,
        uuid: SecureRandom.uuid,
        status: shutdown_requested ? "PENDING_SHUTDOWN" : "RUNNING",
        shutdown_at: shutdown_requested ? shutdown_at.utc.iso8601 : nil
      }

      client.write("HEARTBEAT #{heartbeat.to_json}\n")

      sleep rand(1..5)
    end
  rescue EOFError, IOError
    $stdout.puts "Client disconnected"
    if shutdown_requested
      $stdout.puts "Client work finished, shutting down"
      break
    end
  ensure
    client.close rescue nil
  end
end

$stdout.puts "Server shutdown complete"
server.close rescue nil
```

1. Do `docker stack up --with-registry-auth --detach=true foo compose.yml`
2. Validate its running by running `docker service logs -f foo_tcptest --timestamps`
3. Connect via netcat to the listening port `nc <host> 7800`
4. Confirm you're receiving heratbeat and it's echos back anything you send it
5. Perform `docker service rm foo_tcptest` and see that you might get 1 shutdown heartbeat, but no more, and it no longer echos back anything you send it.

### Expected behavior

Already established TCP sessions should continue to function until past the shutdown grace period, or they're closed normally.  If the above is executed on version 28.5, You'll continue to get heartbeats until the graceful shutdown timer establishes, or until you end the tcp session, and you'll see in the service logs that it cleanly shutdown.

### docker version

```bash
Client: Docker Engine - Community
 Version:           29.0.0
 API version:       1.52
 Go version:        go1.25.4
 Git commit:        3d4129b
 Built:             Mon Nov 10 21:47:06 2025
 OS/Arch:           linux/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          29.0.0
  API version:      1.52 (minimum version 1.44)
  Go version:       go1.25.4
  Git commit:       d105562
  Built:            Mon Nov 10 21:47:06 2025
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v2.1.5
  GitCommit:        fcd43222d6b07379a4be9786bda52438f0dd16a1
 runc:
  Version:          1.3.3
  GitCommit:        v1.3.3-0-gd842d771
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    29.0.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.30.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.40.3
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 11
 Server Version: 29.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 CDI spec directories:
  /etc/cdi
  /var/run/cdi
 Swarm: active
  NodeID: wk53ed8mz0rxbhpgsdkfogsl0
  Is Manager: true
  ClusterID: 9rzhyf1chpq4ti38cjkmk9g5w
  Managers: 3
  Nodes: 3
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.3.14.1
  Manager Addresses:
   10.3.14.1:2377
   10.3.14.2:2377
   10.3.14.3:2377
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: fcd43222d6b07379a4be9786bda52438f0dd16a1
 runc version: v1.3.3-0-gd842d771
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.12.47+rpt-rpi-2712
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.874GiB
 Name: hyades1
 ID: 38f01d86-78f3-4d19-88e1-d77c64c50179
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: vtcifer
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
 Firewall Backend: iptables
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by corhere**
**- What I did**

- Fixed #51651

**- How I did it**

When a container is stopped, new connections to a published port will not be routed to that container but [any existing connections are permitted to continue uninterrupted](https://github.com/moby/libnetwork/pull/2112) for the duration of the container's grace period. Unfortunately recent fixes to overlay networks introduced a regression: existing connections routed over the service mesh to containers on remote nodes are dropped immediately when the container is stopped, irrespective of the grace period.

Fix the handling of NetworkDB endpoint table events so that the endpoint is disabled in the load balancer when a service endpoint transitions to ServiceDisabled instead of deleting the endpoint and re-adding it. And fix the other bugged state transitions with the help of a unit test which exhaustively covers all permutations of endpoint event.

**- How to verify it**
New unit test.

**- Human readable description for the release notes**

```markdown changelog
- Fixed a regression where established network connections could be disrupted during a container's shutdown grace period.
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: daemon/libnetwork/agent.go [hunk 1]
```diff
@@ -957,7 +972,7 @@ func (c *Controller) handleEpTableEvent(ev events.Event) {
 					logger.WithError(err).Error("failed removing service binding")
 				}
 			}
-		} else {
+		} else if !prev.ServiceDisabled && (!equivalent || epRec == nil || epRec.ServiceDisabled) {
```
Comment (thaJeztah) [inline daemon/libnetwork/agent.go:975]: No good answer to this one; just that these conditions start to become ... complex, and potentially brittle. I guess we could abstract it or have some intermediate var to describe the condition, but don't think that makes it much better 🤷

File: daemon/libnetwork/agent_test.go [hunk 2]
```diff
@@ -88,3 +96,321 @@ func TestEndpointEvent_EquivalentTo(t *testing.T) {
...
+				"addContainerNameResolution(network1, endpoint1, ctr2, 172.18.1.2)",
+			},
+		},
+		{
+			name: "Replace/From=Container/To=Container/ServiceDisabled=tt",
+			prev: &ctr1disabled,
+			ev:   &ctr2disabled,
+		},
+	}
+	for _, tt := range tests {
```
Comment (thaJeztah) [inline daemon/libnetwork/agent_test.go:396]: Nit; and no need to update (unless there's other reasons to update the PR); we mostly converged on using `tc` ("test case") for these, so would be good to use that as name for consistency.


```suggestion
	for _, tc := range tests {
```

**Review by thaJeztah — APPROVED** [review]
LGTM


@robmry @akerouanton PTAL

File: daemon/libnetwork/agent_test.go [hunk 3]
```diff
@@ -1,11 +1,16 @@
...
+	"fmt"
+	"net"
 	"net/netip"
 	"slices"
 	"testing"
 
+	"github.com/gogo/protobuf/proto"
 	"gotest.tools/v3/assert"
+
+	"github.com/moby/moby/v2/daemon/libnetwork/networkdb"
```
Comment (robmry) [inline daemon/libnetwork/agent_test.go:13]: nit: moby normally only has two groups of imports, should perhaps stick with that?

**Review by robmry — APPROVED** [review]

File: daemon/libnetwork/agent_test.go (hunk 3 above)
Comment (thaJeztah) [reply daemon/libnetwork/agent_test.go:13]: Ah, yes, I spotted that as well; OTOH, I think there's a PR (somewhere) to switch to using 3 groups, as it's slightly more idiomatic (IIRC), so I thought "might as well switch this one over already", but I'm fine either way 😅

File: daemon/libnetwork/agent.go (hunk 1 above)
Comment (vvoland) [reply daemon/libnetwork/agent.go:975]: I see `epRec == nil || !equivalent` is used in 3 different expressions.

Perhaps it could be extracted to a separate var like:

```
epDeletedOrReplaced := epRec == nil || !equivalent`
``` 

and then used instead?

That would be a bit more easier to parse IMO.

Comment (corhere) [reply daemon/libnetwork/agent.go:975]: The brittleness is a concern I share, hence the exhaustive unit test coverage. And while there are a lot of clauses in the predicate, they line up beat-for-beat with a prose description of the algorithm. E.g., for the commented-on line: "if the entry was not previously disabled and has been replaced, deleted, or disabled, remove the container's endpoint from DNS."

> I see `epRec == nil || !equivalent` is used in 3 different expressions.

For two of the three, the expressions take the form of `epRec == nil || /* dereference epRec */` which I would prefer to leave open-coded to make it obvious by inspection that there is no risk of a nil-dereference. And with the necessary complexity of the predicates, I think that abstracting away some of the clauses adds to the cognitive load more than expressing the same idea as an open-coded idiom. The reader has to know that `epRec == nil` means deletion either way since there are bare `epRec == nil` conditions elsewhere in the function. An implementation with `epDeletedOrReplaced` would contain more concepts for the reader to keep track of than my current implementation.

Comment (thaJeztah) [reply daemon/libnetwork/agent.go:975]: > Perhaps it could be extracted to a separate var like:

That's what I considered as well for a bit, but;

> ...I think that abstracting away some of the clauses adds to the cognitive load...

This was my conclusion as well. Having a `epDeletedOrReplaced` makes the call-site look nice, but doesn't make the conditions less complex, so to understand "what does `epDeletedOrReplaced` .. mean?" you'd still have to navigate to its declaration.

So yes, "do I like the complex conditions?" no, but "does abstracting it make it better?" ... also no (not really).
