### PR TITLE
Stop and Kill commands made robust

### LINKED ISSUE #10182: stop/kill commands fail when container is exiting
There is a short period of time between container's process exit and container's cleanup. If `stop` or `kill` commands are executed during this window, they fail with:

    Error response from daemon: Cannot stop container test: no such process
    FATA[0000] Error: failed to stop one or more containers 

Reproducer is simple:

    $ docker run --name test --net=none --detach fedora:latest /bin/bash -c "exit"
    $ docker restart -t 2 test
    $ docker stop test  # or: docker kill test

Of course this is not reproduceable every time because the period is not that long. On my VM the window is hit in one of two cases.

`container.Kill()` and `container.Stop()` functions check whether container is running before they issue `syscall.Kill()`. The problem is that the check tests just the existence of `rootfs`, not the existence of process which may have already finished.

I'll post a PR for this soon.

### PR DESCRIPTION
**Pull request by miminar**
Fixes #10182

There is a short period of time between container's process exit and
container's cleanup. If stop or kill commands are executed during this window,
they fail with:

```
Error response from daemon: Cannot stop container test: no such process
FATA[0000] Error: failed to stop one or more containers 
```

container.Kill() and container.Stop() functions check whether container is
running before they issue syscall.Kill(). The problem is that the check tests
just the existence of rootfs, not the existence of process which may have
already finished.

Signed-off-by: Michal Minar miminar@redhat.com

### CODE REVIEW

**Comment by cpuguy83** [comment]
It seems like in the parts where we are currently doing killing 9ing with syscall, we can wrap that in the container lock, check if the pid is still running, then make the kill (which also, should be moved to the exec driver, IMHO, but perhaps for a different PR).

Also, it seems like we shouldn't be adding more stuff calling syscall to this part of the code and should push off to the exec driver.

**Comment by crosbymichael** [comment]
LGTM

File: daemon/container.go [hunk 1]
```diff
@@ -687,7 +689,11 @@ func (container *Container) Kill() error {
 		if pid := container.GetPid(); pid != 0 {
 			log.Infof("Container %s failed to exit within 10 seconds of kill - trying direct SIGKILL", utils.TruncateID(container.ID))
 			if err := syscall.Kill(pid, 9); err != nil {
-				return err
+				if err != syscall.ESRCH {
+					return err
+				} else {
```
Comment (LK4D4) [inline daemon/container.go]: Redundant `else`

File: daemon/container.go [hunk 2]
```diff
@@ -677,8 +677,10 @@ func (container *Container) Kill() error {
 	}
 
 	// 1. Send SIGKILL
-	if err := container.KillSig(9); err != nil {
+	if err := container.KillSig(9); err != nil && err != syscall.ESRCH {
```
Comment (LK4D4) [inline daemon/container.go]: This can be rewritten like
```
if err := container.KillSig(9); err != nil {
    if err != syscall.ESRCH {
        return err
    }
    log.Debugf("Cannot kill process (pid=%d): no such process.", container.GetPid())
}
```
which is more readable IMO

File: daemon/container.go [hunk 3]
```diff
@@ -702,11 +708,13 @@ func (container *Container) Stop(seconds int) error {
...
 
 	// 1. Send a SIGTERM
-	if err := container.KillSig(15); err != nil {
+	if err := container.KillSig(15); err != nil && err != syscall.ESRCH {
 		log.Infof("Failed to send SIGTERM to the process, force killing")
-		if err := container.KillSig(9); err != nil {
+		if err := container.KillSig(9); err != nil && err != syscall.ESRCH {
 			return err
 		}
+	} else if err == syscall.ESRCH {
```
Comment (LK4D4) [inline daemon/container.go]: same here

File: daemon/container.go (hunk 2 above)
Comment (miminar) [inline daemon/container.go]: Ok, I'll change it.

File: daemon/container.go [hunk 4]
```diff
@@ -705,9 +711,12 @@ func (container *Container) Stop(seconds int) error {
 	// 1. Send a SIGTERM
 	if err := container.KillSig(15); err != nil {
 		log.Infof("Failed to send SIGTERM to the process, force killing")
-		if err := container.KillSig(9); err != nil {
-			return err
+		if err != syscall.ESRCH {
+			if err := container.KillSig(9); err != nil && err != syscall.ESRCH {
```
Comment (LK4D4) [inline daemon/container.go]: I think that maybe makes sense to write debug message here too as in other places. Just to be sure that we see whole flow of execution.

Comment (miminar) [inline daemon/container.go]: But that would just duplicate the message if the process terminates before `kill 15` with no message in between.

Comment (LK4D4) [inline daemon/container.go]: If process was terminated before `kill 15` you will not go to `kill 9` because it's in `err != syscall.ESRCH` branch.

Comment (miminar) [inline daemon/container.go]: Oops, sorry. The message would be duplicated if the process terminates before `kill 9` and after `kill 15` and I still don't see a benefit of it.

Just to be sure, are we talking about this:

	if err := container.KillSig(15); err != nil {
 		log.Infof("Failed to send SIGTERM to the process, force killing")
		if err != syscall.ESRCH {
			if err := container.KillSig(9); err != nil {
				if err != syscall.ESRCH {
					return err
				}
				log.Debugf("Cannot kill process (pid=%d): no such process.", container.GetPid())
			}
 		}
		log.Debugf("Cannot kill process (pid=%d): no such process.", container.GetPid())
 	}

?
The second debug statement could be put into an else branch which would prevent the duplication. But still the outcome would be the same as with current code.

Comment (LK4D4) [inline daemon/container.go]: Benefit is that you will know when your process died exactly. Also now I think maybe makes sense to add signal number to log messages.

Comment (miminar) [inline daemon/container.go]: Fair enough. I'll tweak it once more. Thanks for your insight.

**Comment by miminar** [comment]
@LK4D4: can you please take another look?

File: daemon/container.go [hunk 5]
```diff
@@ -652,6 +652,16 @@ func (container *Container) KillSig(sig int) error {
 	return container.daemon.Kill(container, sig)
 }
 
+// Wrapper aroung KillSig() suppressing "no such process" error.
+func (container *Container) killPossiblyDeadProcess(sig int) error {
+	err := container.KillSig(sig)
+	if err == syscall.ESRCH {
+		log.Debugf("Cannot kill process (pid=%d) with signal %d: no such process.", container.GetPid(), sig)
+		err = nil
```
Comment (LK4D4) [inline daemon/container.go]: It's better `return nil` here

Comment (miminar) [inline daemon/container.go]: Done.

**Comment by LK4D4** [comment]
LGTM
My comments was about style mostly

**Comment by LK4D4** [comment]
@miminar Thanks!
