### PR TITLE
Refine error message when save non-exist image

### LINKED ISSUE #20709: Enhancement: give friendly error message when non-image name passed to "docker save"
Output of `docker version`:

```
David@noe MINGW64 ~/extvol
$ docker version
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      linux/amd64

David@noe MINGW64 ~/extvol
$
```

Output of `docker info`:

```
David@noe MINGW64 ~/extvol
$ docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 21
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 37
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 4.1.18-boot2docker
Operating System: Boot2Docker 1.10.2 (TCL 6.4.1); master : 611be10 - Mon Feb 22 22:47:06 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.1 MiB
Name: default
ID: 226R:TS6B:7ZBR:LRVK:UP2Y:HY6M:3L2N:XYK5:7QIH:4TIJ:AIO6:ULTN
Debug mode (server): true
 File Descriptors: 18
 Goroutines: 32
 System Time: 2016-02-25T22:45:17.889222018Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

David@noe MINGW64 ~/extvol
$
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):

> Recent installation using docker-machine on Windows 10.

List the steps to reproduce the issue:

> 1. created data volume /var/lib/postgresql/data  in container based on debian:8.2 for use by known working image based on postgres:9.4.5
> 2. tried to run `docker save` on container with data volume

Describe the results you received:
```
David@noe MINGW64 ~/extvol
$ docker save data_vlpd > data_vlpd.tar
Error response from daemon: digest not found

David@noe MINGW64 ~/extvol
$ docker save -o data_vlpd.tar data_vlpd
Error response from daemon: digest not found

David@noe MINGW64 ~/extvol
$
```

Describe the results you expected:

> Friendly error message along lines of `"data_vlpd" is not an image`

Provide additional info you think is important:

```
Motivated by #20705 . Filed at suggestion of @thaJeztah
```

### PR DESCRIPTION
**Pull request by HackToday**
Fixes: #20709
As discussed in the issue, we need refine the message to
help user more understood, what happened for non-exist image.

Signed-off-by: Kai Qiang Wu(Kennan) wkqwu@cn.ibm.com

### CODE REVIEW

**Comment by HackToday** [comment]
ping @tonistiigi

File: image/store.go [hunk 1]
```diff
@@ -170,6 +171,9 @@ func (is *store) Search(term string) (ID, error) {
 
 	dgst, err := is.digestSet.Lookup(term)
 	if err != nil {
+		if strings.Contains(err.Error(), "digest not found") {
+			err = fmt.Errorf("Image %s could not found or does not exist.", term)
```
Comment (thaJeztah) [inline image/store.go]: Think this should be either "could not be found" (added 'be'), but perhaps it's better to use

    no such image: %s

As that's what we use in other locations

File: integration-cli/docker_cli_save_load_test.go [hunk 2]
```diff
@@ -167,6 +167,20 @@ func (s *DockerSuite) TestSaveAndLoadRepoFlags(c *check.C) {
...
+	testRequires(c, DaemonIsLinux)
+	name := "test-save-image"
+	dockerCmd(c, "run", "--name", name, "busybox", "true")
+
+	repoName := "foobar-save-image-test"
+
+	deleteImages(repoName)
+
+	out, _, err := dockerCmdWithError("save", "-o", "test-img.tar", repoName)
+	c.Assert(err, checker.NotNil, check.Commentf("save image should fail for non-exist image"))
```
Comment (thaJeztah) [inline integration-cli/docker_cli_save_load_test.go]: s/non-exist/non-existing/

File: integration-cli/docker_cli_save_load_test.go [hunk 3]
```diff
@@ -167,6 +167,20 @@ func (s *DockerSuite) TestSaveAndLoadRepoFlags(c *check.C) {
 	c.Assert(before, checker.Equals, after, check.Commentf("inspect is not the same after a save / load"))
 }
 
+func (s *DockerSuite) TestSaveWithNoExistImage(c *check.C) {
+	testRequires(c, DaemonIsLinux)
+	name := "test-save-image"
+	dockerCmd(c, "run", "--name", name, "busybox", "true")
```
Comment (thaJeztah) [inline integration-cli/docker_cli_save_load_test.go]: Do we need this? I don't think this image is used anywhere

File: integration-cli/docker_cli_save_load_test.go [hunk 4]
```diff
@@ -167,6 +167,20 @@ func (s *DockerSuite) TestSaveAndLoadRepoFlags(c *check.C) {
...
+
+	repoName := "foobar-save-image-test"
```
Comment (thaJeztah) [inline integration-cli/docker_cli_save_load_test.go]: nit: perhaps rename to something like "foobar-non-existing-image"

File: integration-cli/docker_cli_save_load_test.go [hunk 5]
```diff
@@ -167,6 +167,20 @@ func (s *DockerSuite) TestSaveAndLoadRepoFlags(c *check.C) {
...
+
+	deleteImages(repoName)
```
Comment (thaJeztah) [inline integration-cli/docker_cli_save_load_test.go]: Should we cleanup at the end of the test as well (defer)?

File: integration-cli/docker_cli_save_load_test.go (hunk 3 above)
Comment (HackToday) [inline integration-cli/docker_cli_save_load_test.go]: just test we did have an image, and delete it, so that image not exist, and then run save would get the expected error  :)

File: integration-cli/docker_cli_save_load_test.go (hunk 5 above)
Comment (HackToday) [inline integration-cli/docker_cli_save_load_test.go]: if you mean containers, we not need to cleanup anything. as DockerSuite would did that for us

File: integration-cli/docker_cli_save_load_test.go (hunk 3 above)
Comment (thaJeztah) [inline integration-cli/docker_cli_save_load_test.go]: sorry, meant "container"; this is using a different name than the repo below, so I don't really see why it's needed

Comment (HackToday) [inline integration-cli/docker_cli_save_load_test.go]: yes, forgot to add commit steps, would change that . Thanks

File: image/store.go [hunk 6]
```diff
@@ -170,6 +171,9 @@ func (is *store) Search(term string) (ID, error) {
 
 	dgst, err := is.digestSet.Lookup(term)
 	if err != nil {
+		if strings.Contains(err.Error(), "digest not found") {
```
Comment (calavera) [inline image/store.go]: can we make `digestSet.Lookup` to return a typed error to avoid this string comparison?

Comment (tonistiigi) [inline image/store.go]: that should be `digest.ErrDigestNotFound`

File: integration-cli/docker_cli_save_load_test.go (hunk 5 above)
Comment (thaJeztah) [inline integration-cli/docker_cli_save_load_test.go]: Oh, sorry, my mistake, we're only *saving* images here, not loading

**Comment by HackToday** [comment]
@tonistiigi @calavera and @thaJeztah  PTAL. Thanks

File: integration-cli/docker_cli_save_load_test.go (hunk 3 above)
Comment (thaJeztah) [inline integration-cli/docker_cli_save_load_test.go]: Oh, now I see what you meant; but is it necessary? All we need is an image name that we know doesn't exist, so creating it first, then removing it shouldn't be needed?

Comment (HackToday) [inline integration-cli/docker_cli_save_load_test.go]: I think if we had such  image name that, and we delete that, then the image should not surely existed. And then we save that,  It is guaranteed that image not existed. :)

Comment (HackToday) [inline integration-cli/docker_cli_save_load_test.go]: What I meant is that, we know we delete one image, and that image not exist anymore. And then test docker save in such case is more meaningful.

Comment (HackToday) [inline integration-cli/docker_cli_save_load_test.go]: ping @thaJeztah  PTAL if that make sense. Thanks

Comment (thaJeztah) [inline integration-cli/docker_cli_save_load_test.go]: I just don't think it's needed; because if that image has never been there, we don't need to create it first, only to delete it later.

perhaps @vdemeester can have a look as well, but I don't think it's needed :smile:

**Comment by HackToday** [comment]
ping @vdemeester and @thaJeztah  PTAL the new change.

Also seems jenkins not failed with this issue :0

**Comment by HackToday** [comment]
please test this

**Comment by calavera** [comment]
LGTM

**Comment by thaJeztah** [comment]
LGTM, thanks @HackToday!
