### PR TITLE
Ensure stdin does not block after container stop

### LINKED ISSUE #11957: docker run -i never exits if spawned by other process for reading / writing using pipe
Description of problem:

When interacting with docker container through popen, the dockerized process hangs. The process is visible in system process list `ps aux | grep docker`, but `docker ps` shows that it exited.
When I pass something onto `stdin`, the process exits. The problem is easily reproducible, I tried on Docker 1.4.1 and 1.5.0 and result was the same. Scroll down to see the example code how to reproduce it.

`docker version`:

```
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

`docker info`:

```
Containers: 26
Images: 143
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 216
Execution Driver: native-0.2
Kernel Version: 3.13.0-43-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 7.633 GiB
Name: lukasz-ThinkPad-T420
ID: LKJ2:DWR4:JPLK:6TCQ:JZ4K:CQWB:PIGH:PFM4:FAFI:OTHH:QESL:OIFC
WARNING: No swap limit support
```

`uname -a`: 

`Linux lukasz-ThinkPad-T420 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

Environment details: physical, Ubuntu 14.04

How reproducible:

Create test.rb file with following code:

```ruby
command = 'docker run -i ubuntu /bin/ls'

in_r, in_w = IO.pipe
out_r, out_w = IO.pipe
err_r, err_w = IO.pipe

in_w.sync = true

pid = spawn(
  command,
  in: in_r,
  out: out_w,
  err: err_w
)

[in_r, out_w, err_w].each {|io| io.close }

puts "One: #{pid}"

Process.waitpid(pid)

puts "Two"
```

Then run:

`ruby test.rb`

Actual Results:

You will see that it never exits, never returns "Two". Dockerized `/bin/ls` process is still running but running `docker ps --all` shows that container immediately exited. If you remove `-i` flag is starts to work as expected but communication with process is lost.

Expected Results:

`ruby test.rb` should exit immediately returning "Two"

### LINKED ISSUE #12319: Interactive container hangs when executing from a Java Application
Hi!

I'm trying to execute an interactive container from a Java Application (I'm building an online free Java compiler). But for some reason the termination signal is not received and the Java application thinks that the program continues running (Docker version 1.5.0, build a8a31ef)
The attached code hangs on the process.waitFor(). But if I remove the -i flag the program runs ok
Maybe this issue is related to this other fixed before -> https://github.com/docker/docker/issues/6509
I need the program to run with the -i flag due that I want to execute interactive Java programs inside the docker container. Also I tried with the -t flag but Java does not provide a TTY so it fails to execute.

One thing that I cannot figure out is why the docker command works from the command line but no from the java application, maybe the difference is that I have a TTY when I execute the command from the command line

<pre>
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;

public class Test {
	
	public static void main(String[] args) throws Exception {
		Process process = Runtime.getRuntime().exec("sudo docker run -i ubuntu ls");
		int returnCode = process.waitFor();
		System.out.println("returnCode: " + returnCode);
		System.out.println("output: " + output(process.getInputStream()));
	}
	
	private static String output(InputStream inputStream) throws IOException {
		StringBuilder sb = new StringBuilder();
		BufferedReader br = null;
		try {
			br = new BufferedReader(new InputStreamReader(inputStream));
			String line = null;
			while ((line = br.readLine()) != null) {
				sb.append(line + System.getProperty("line.separator"));
			}
		} finally {
			br.close();
		}
		return sb.toString();
	}
}
</pre>

### PR DESCRIPTION
**Pull request by cpuguy83**
Fixes #11957
Fixes #12319

Also removes check for Darwin when the stdin reader is closed as it
doesn't appear to block any more.

### CODE REVIEW

File: api/client/hijack.go [hunk 1]
```diff
@@ -196,19 +193,15 @@ func (cli *DockerCli) hijack(method, path string, setRawTerminal bool, in io.Rea
 		defer term.RestoreTerminal(cli.inFd, oldState)
 	}
 
+	receiveStdout := make(chan error)
```
Comment (noxiouz) [inline api/client/hijack.go]: I think it should be buffered to avoid goroutine leak, because select at 236 has two ways now.

Comment (cpuguy83) [inline api/client/hijack.go]: I don't think there is an issue with unbuffered here. It still makes sure to read off whatever is being sent, and only one thing is sending.

**Comment by vdemeester** [comment]
@cpuguy83 yay it does fix it :wink: SGTM :smile_cat:

File: api/client/hijack.go (hunk 1 above)
Comment (LK4D4) [inline api/client/hijack.go]: Yes. BUT.. I think @noxiouz is right, because channel with value is cheaper than whole closure. With buffered channel you can just return from closure and forget about it.

**Comment by tonistiigi** [comment]
LGTM

**Comment by cpuguy83** [comment]
Added buffer to `receiveStdout` chan

**Comment by jfrazelle** [comment]
LGTM
