### PR TITLE
Fix issue caused by duplicate `docker plugin create` with same names

### LINKED ISSUE #28684: [1.13.0-rc1] docker plugin create does not check for duplicates, creates multiple copies
**Description**

The new `docker plugin create` command from #28164 does not check for duplicates. Running the same `docker plugin create` command more than once in a row for the same rootfs/config.json creates multiple plugin entries. But only one of them can be removed. Once it is removed, the remaining are stranded.

**Steps to reproduce the issue:**
1. docker plugin create repo/image rootfs-dir
2. docker plugin create repo/image rootfs-dir
3. docker plugin create repo/image rootfs-dir

**Describe the results you received:**

````
$ docker plugin create blockbridge/volume-driver plugin
blockbridge/volume-driver
$ docker plugin create blockbridge/volume-driver plugin
blockbridge/volume-driver
$ docker plugin create blockbridge/volume-driver plugin
blockbridge/volume-driver

$ docker plugin ls
NAME                        TAG                 DESCRIPTION                 ENABLED
vieux/sshfs                 latest              sshFS plugin for Docker     true
blockbridge/volume-driver   latest              Blockbridge Volume Plugin   false
blockbridge/volume-driver   latest              Blockbridge Volume Plugin   false
blockbridge/volume-driver   latest              Blockbridge Volume Plugin   false

$ docker plugin rm blockbridge/volume-driver
blockbridge/volume-driver

$ docker plugin rm blockbridge/volume-driver:latest
Error response from daemon: plugin "blockbridge/volume-driver:latest" not found

$ docker plugin ls
NAME                        TAG                 DESCRIPTION                 ENABLED
vieux/sshfs                 latest              sshFS plugin for Docker     true
blockbridge/volume-driver   latest              Blockbridge Volume Plugin   false
blockbridge/volume-driver   latest              Blockbridge Volume Plugin   false

$ docker plugin rm blockbridge/volume-driver
Error response from daemon: plugin "blockbridge/volume-driver:latest" not found
````

**Describe the results you expected:**

The first should succeed, subsequent create commands should fail.

**Additional information you deem important (e.g. issue happens only occasionally):**

With multiple entries, there is no way to reference them uniquely, since they are named the same. Remove also can not recover, as they are stranded. Daemon restart does not change the behavior.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc1
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   75fd88b
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:             1.13.0-rc1
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          75fd88b
 Built:               
 OS/Arch:             linux/amd64
 Experimental:        false
```

**Output of `docker info`:**

```
Containers: 11
 Running: 1
 Paused: 0
 Stopped: 10
Images: 328
Server Version: 1.13.0-rc1
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 29.37 GB
 Data Space Total: 102 GB
 Data Space Available: 72.63 GB
 Metadata Space Used: 7.647 MB
 Metadata Space Total: 1.07 GB
 Metadata Space Available: 1.062 GB
 Thin Pool Minimum Free Space: 10.2 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 8517738ba4b82aff5662c97ca4627e7e4d03b531
runc version: ac031b5bf1cc92239461125f4c1ffb760522bbf2
init version: N/A (expected: v0.13.0)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.27-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.67 GiB
Name: srust7.localnet
ID: MIUE:GKLN:L4OB:B2JU:OIPH:BTWO:L2P5:RQLP:F4DZ:GS5A:RHEH:PDCX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 25
 Goroutines: 29
 System Time: 2016-11-21T22:42:27.11929573Z
 EventsListeners: 0
```

CC @anusha-ragunathan @vieux @tiborvass

### PR DESCRIPTION
**Pull request by yongtang**
**- What I did**

This fix tries to fix the issue raised in #28684:
1. Duplicate plugin create with the same name will override the old plugin reference
2. In case an error happens in the middle of the plugin creation, plugin directories in `/var/lib/docker/plugins` are not cleaned up.

**- How I did it**

This fix update the plugin store so that `Add()` will return an error if a plugin with the same name already exist.

This fix also will clean up the directory in `/var/lib/docker/plugins` in case an error happens in the middle of the plugin creation.

**- How to verify it**

An integration test has been added to cover the changes.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

600950-cute-red-kitten

This fix fixes #28684.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

File: plugin/backend_linux.go [hunk 1]
```diff
@@ -191,6 +191,16 @@ func (pm *Manager) CreateFromContext(ctx context.Context, tarCtx io.Reader, opti
 		return err
 	}
 
+	// In case an erorr happens, remove the created directory.
+	if err := pm.createFromContext(ctx, pluginID, pluginDir, tarCtx, options); err != nil {
+		os.RemoveAll(pluginDir)
```
Comment (AkihiroSuda) [inline plugin/backend_linux.go]: IMO at least we should print a warning in a case RemoveAll returns an error

**Comment by vieux** [comment]
ping @anusha-ragunathan @tiborvass

File: plugin/backend_linux.go (hunk 1 above)
Comment (yongtang) [inline plugin/backend_linux.go]: Thanks @AkihiroSuda. Updated the PR and added a warning.

**Comment by yongtang** [comment]
Updated the PR and also adds an integration test to cover the changes.

File: plugin/store/store.go [hunk 2]
```diff
@@ -98,12 +98,21 @@ func (ps *Store) SetState(p *v2.Plugin, state bool) {
...
 
 // Add adds a plugin to memory and plugindb.
-func (ps *Store) Add(p *v2.Plugin) {
+// An error will be returned if there is a collision.
+func (ps *Store) Add(p *v2.Plugin) error {
 	ps.Lock()
+	defer ps.Unlock()
+
+	if v, exist := ps.plugins[p.GetID()]; exist {
+		return fmt.Errorf("plugin '%s' has the same ID '%s' as '%s'", p.Name(), p.GetID(), v.Name())
```
Comment (tiborvass) [inline plugin/store/store.go]: we tend to use `%q` instead of apostrophes `'%s'`

**Review by tiborvass — CHANGES_REQUESTED** [review]

File: plugin/backend_linux.go [hunk 3]
```diff
@@ -194,6 +194,18 @@ func (pm *Manager) CreateFromContext(ctx context.Context, tarCtx io.Reader, opti
 		return err
 	}
 
+	// In case an erorr happens, remove the created directory.
+	if err := pm.createFromContext(ctx, pluginID, pluginDir, tarCtx, options); err != nil {
+		if err := os.RemoveAll(pluginDir); err != nil {
+			logrus.Warnf("unable to remove '%s' from failed plugin creation", pluginDir)
```
Comment (AkihiroSuda) [inline plugin/backend_linux.go]: Let's print the err here

File: plugin/store/store.go (hunk 2 above)
Comment (yongtang) [inline plugin/store/store.go]: Thanks @tiborvass. The PR has been updated.

File: plugin/backend_linux.go (hunk 3 above)
Comment (yongtang) [inline plugin/backend_linux.go]: Thanks @AkihiroSuda. Done.

File: plugin/store/store.go [hunk 4]
```diff
@@ -98,12 +98,31 @@ func (ps *Store) SetState(p *v2.Plugin, state bool) {
...
+	if _, exist := ps.nameToID[p.Name()]; exist {
+		return fmt.Errorf("plugin %q already exist", p.Name())
+	}
+	ps.plugins[p.GetID()] = p
+	ps.nameToID[p.Name()] = p.GetID()
+	ps.updatePluginDB()
+	return nil
+}
+
+// Update update a plugin to memory and plugindb.
```
Comment (AkihiroSuda) [inline plugin/store/store.go]: nit: Update updates...

Comment (yongtang) [inline plugin/store/store.go]: Thanks. Done.

**Review by vdemeester — APPROVED** [review]
LGTM :frog: but would like to be sure it's ok for @anusha-ragunathan @tiborvass and @vieux :angel:

File: plugin/backend_linux.go [hunk 5]
```diff
@@ -194,6 +194,18 @@ func (pm *Manager) CreateFromContext(ctx context.Context, tarCtx io.Reader, opti
 		return err
 	}
 
+	// In case an erorr happens, remove the created directory.
```
Comment (anusha-ragunathan) [inline plugin/backend_linux.go]: typo: "erorr" -> "error"

File: plugin/store/store.go [hunk 6]
```diff
@@ -98,12 +98,31 @@ func (ps *Store) SetState(p *v2.Plugin, state bool) {
...
+// An error will be returned if there is a collision.
+func (ps *Store) Add(p *v2.Plugin) error {
 	ps.Lock()
+	defer ps.Unlock()
+
+	if v, exist := ps.plugins[p.GetID()]; exist {
+		return fmt.Errorf("plugin %q has the same ID %s as %q", p.Name(), p.GetID(), v.Name())
+	}
+	if _, exist := ps.nameToID[p.Name()]; exist {
+		return fmt.Errorf("plugin %q already exist", p.Name())
```
Comment (anusha-ragunathan) [inline plugin/store/store.go]: nit: "exist" -> "exists"

File: plugin/store/store.go [hunk 7]
```diff
@@ -98,12 +98,31 @@ func (ps *Store) SetState(p *v2.Plugin, state bool) {
 }
 
 // Add adds a plugin to memory and plugindb.
-func (ps *Store) Add(p *v2.Plugin) {
+// An error will be returned if there is a collision.
```
Comment (anusha-ragunathan) [inline plugin/store/store.go]: Callers of `pluginStore.Add` in backend_linux.go (Pull) and manager.go (init) should also be updated to check for returned error.

Comment (anusha-ragunathan) [inline plugin/store/store.go]: @yongtang : Not this change, but `Pull` should also remove the created pluginDir, in case of errors. Would you like to take care of that as part of this PR?

Comment (anusha-ragunathan) [inline plugin/store/store.go]: Never mind. https://github.com/docker/docker/pull/28893 fixes the error on pull issue

Comment (anusha-ragunathan) [inline plugin/store/store.go]: Also, Pull() checks for duplicate names using `pm.pluginStore.GetByName`. I like how this fails fast, rather than at `Add`, which is pretty late in the function.  `Add` is still valuable to catch the corner cases, where there's a collision in the generated ID.  Lets be consistent on how both collisions are checked in `Pull` and `Create`.

File: plugin/backend_linux.go (hunk 5 above)
Comment (yongtang) [inline plugin/backend_linux.go]: Thanks @anusha-ragunathan. Done.

File: plugin/store/store.go (hunk 6 above)
Comment (yongtang) [inline plugin/store/store.go]: Thanks @anusha-ragunathan. The PR has been updated.

**Review by tiborvass — APPROVED** [review]

File: plugin/store/store.go (hunk 7 above)
Comment (anusha-ragunathan) [inline plugin/store/store.go]: @yongtang : Can you use `GetByName` in `Pull` to check for duplicate names and fail fast in the function? Then you can update `Add` to only check for collision by ID.

Comment (yongtang) [inline plugin/store/store.go]: Thanks @anusha-ragunathan. I created a PR #28949 for the follow up of using `GetByName()`. Please take a look and let me know if there are any issues.
