### PR TITLE
rootless: fix `open /etc/docker/plugins: permission denied`

### LINKED ISSUE #47436: v25 regression: Rootless docker - plugin discovery uses wrong path
### Description

We encounter exactly the same problem as earlier described in https://github.com/moby/moby/issues/43111

This issue was fixed in v24.0.0, we are now using v25.0.3

### Reproduce

1. run the commands `docker system prune -a -f --volumes` and `docker system df` 
2. An error is returned: `Error response from daemon: list: error listing plugins: legacy plugin: error reading dir entries: open /etc/docker/plugins: permission denied`

### Expected behavior

The commands should be executed without error

### docker version

```bash
Client: Docker Engine - Community
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:14:26 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:26 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    25.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.5
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.10.0-28-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 23.46GiB
 Name: tridev002
 ID: KVHD:CZGB:YY5C:SF3K:6OM6:62UH:HZ6V:XF7J:WMBL:KOPK:BEUN:T35H
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://docker.triopsys.net/
 Live Restore Enabled: false
```

### Additional Info

As a workaround group and other are given read and execute permissions for /etc/docker and /etc/docker/plugins

### PR DESCRIPTION
**Pull request by AkihiroSuda**
**- What I did**
Fixed #47436

**- How I did it**

Skipped the `specsPaths` loop on `ErrPermission`.

**- How to verify it**
```
sudo mkdir -m 0700 /etc/docker/plugins
docker volume ls
```

**- Description for the changelog**

```markdown changelog
rootless: fix `open /etc/docker/plugins: permission denied`
```

**- A picture of a cute animal (not mandatory but encouraged)**
🐧

### CODE REVIEW

File: pkg/plugins/discovery.go [hunk 1]
```diff
@@ -57,6 +58,9 @@ func (l *LocalRegistry) Scan() ([]string, error) {
 	for _, p := range l.specsPaths {
 		dirEntries, err = os.ReadDir(p)
 		if err != nil && !os.IsNotExist(err) {
+			if errors.Is(err, fs.ErrPermission) && userns.RunningInUserNS() {
+				continue
+			}
 			return nil, errors.Wrap(err, "error reading dir entries")
 		}
```
Comment (thaJeztah) [inline pkg/plugins/discovery.go:65]: Perhaps we should put the `os.IsNotExist(err)` inside the `if` branch here as well; at least I think it might be slightly more readable; wdyt?

```go
if err != nil {
	if os.IsNotExist(err) {
		continue
	}
	if errors.Is(err, fs.ErrPermission) && userns.RunningInUserNS() {
		continue
	}
	return nil, errors.Wrap(err, "error reading dir entries")
}
```

I guess the `errors.Is(err, fs.ErrPermission)` _could be_ `os.IsPermission(err)` as well, to stick with the same as we do for the `os.IsNotExist()` (although I think either is probably fine);

```go
if err != nil {
	if os.IsNotExist(err) {
		continue
	}
	if os.IsPermission(err) && userns.RunningInUserNS() {
		continue
	}
	return nil, errors.Wrap(err, "error reading dir entries")
}
```

Comment (thaJeztah) [reply pkg/plugins/discovery.go:65]: Thanks! Do you know why we have this permissions issue in the first place? Are we hiding the underlying issue here, and should the directory have been created with different permissions?

If that's the case, should we add a `Warn` or `Debug` log here?

Comment (AkihiroSuda) [reply pkg/plugins/discovery.go]: Updated to use `os.IsPermission`, although I feel `os.Is...` functions have been substantially soft-deprecated.

Also added a debug log.

**Review by cpuguy83 — APPROVED** [review]

File: pkg/plugins/discovery.go [hunk 2]
```diff
@@ -56,10 +58,16 @@ func (l *LocalRegistry) Scan() ([]string, error) {
 
 	for _, p := range l.specsPaths {
 		dirEntries, err = os.ReadDir(p)
-		if err != nil && !os.IsNotExist(err) {
+		if err != nil {
+			if os.IsNotExist(err) {
+				continue
+			}
+			if os.IsPermission(err) && userns.RunningInUserNS() {
+				logrus.Debug(err.Error())
```
Comment (thaJeztah) [inline pkg/plugins/discovery.go:66]: this should probably be using containerd/log

Comment (AkihiroSuda) [reply pkg/plugins/discovery.go]: fixed

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

File: pkg/plugins/discovery.go (hunk 1 above)
Comment (vvoland) [reply pkg/plugins/discovery.go]: FYI,`errors.Is(err, os.IsPermission)` should be preferred over `os.IsPermission(err)` (this also applies to other fs errors):

> This function predates errors.Is. It only supports errors returned by the os package. New code should use errors.Is(err, fs.ErrPermission). 
~ https://pkg.go.dev/os#IsPermission

Comment (thaJeztah) [reply pkg/plugins/discovery.go]: Yeah, ISTR the `os.IsXXX` ones did some extra checks related to syscall errors, but for this case, probably either is fine.

Note that `os.XXX` errors are on their own an alias for `fs.XXX` errors, so the "fully correct" thing is to also import` fs` (which is a bit of a nuisance)
