### PR TITLE
chroot: remount everything as private in new mntns

### LINKED ISSUE #25925: Docker build cannot COPY the file to `/` directory
Dear all,

I'm running docker inside an ubuntu (16.04) VM (vmware player), here is my docker version

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64
```

the output of `docker info`

```
Containers: 11
 Running: 1
 Paused: 0
 Stopped: 10
Images: 161
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 85
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-34-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.66 GiB
Name: ubuntu
ID: NAWG:CZGX:MIW2:B6XJ:FBKQ:5FCP:UP6W:JWLO:R63J:ZUSC:D4Y7:3VXJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

I have a simple `Dockerfile`

```
FROM alpine:3.4
COPY start.sh /
```

the `start.sh` is inside same folder as `Dockerfile`

when `docker build`, it shows:

```
Step 1 : FROM alpine:3.4
 ---> 4e38e38c8ce0
Step 2 : COPY start.sh /
stat /var/lib/docker/aufs/mnt/6379713235a0e7c418874544c96e44a92a142955b78251e8ccb8145b760db7ed/start.sh: no such file or directory
```

it worked before, while after installing `docker-machine` and `virtualbox`, it doesn't work, don't know if it related or not. Any idea, thank you in advance.

### PR DESCRIPTION
**Pull request by tonistiigi**
If parent of the destination path is shared, this path will be unmounted from the parent ns even if
the path itself is private.

Second commit just removes code that seemed unnecessary as kernel would do this cleanup anyway, doesn't fix any issues.

Likely fixes #25925 although it is unknown what makes the `/var/lib/docker/overlay` shared as daemon always enforces them to be private on every boot.

@crosbymichael @runcom  @mlaventure

### CODE REVIEW

**Comment by crosbymichael** [comment]
LGTM

**Comment by mlaventure** [comment]
LGTM if :green_heart:

File: pkg/chrootarchive/chroot_linux.go [hunk 1]
```diff
@@ -57,13 +62,6 @@ func chroot(path string) (err error) {
 				err = errCleanup
 			}
 		}
-
-		if errCleanup := syscall.Unmount("/", syscall.MNT_DETACH); errCleanup != nil {
-			if err == nil {
-				err = fmt.Errorf("error unmounting root: %v", errCleanup)
-			}
-			return
-		}
```
Comment (thaJeztah) [inline pkg/chrootarchive/chroot_linux.go]: Should we put a comment here / somewhere to explain why we don't cleanup? Trying to prevent future contributors from opening a PR that adds this back and we forgot about why we're not doing that

Comment (thaJeztah) [inline pkg/chrootarchive/chroot_linux.go]: Also please put that in the commit message if it requires additional explanation

Comment (tonistiigi) [inline pkg/chrootarchive/chroot_linux.go]: Idk, to me it seemed unexpected and intention seemed confusing. I think a comment in here can be more confusing than helpful. cc @runcom who added this.

**Comment by vieux** [comment]
LGTM

**Comment by runcom** [comment]
LGTM (cc @rhvgoyal)

File: pkg/chrootarchive/chroot_linux.go (hunk 1 above)
Comment (runcom) [inline pkg/chrootarchive/chroot_linux.go]: I remember we needed this but if it's not needed anymore then yeah let's remove it..
