### PR TITLE
Replace secrets with join tokens

### LINKED ISSUE #24430: Proposal: Replace secrets with "join tokens"
Now that #24349 has been merged, we will generate a secret if none is specified by default. However, users can also specify their own secrets. Because of this, it's possible for users to choose a weak secret, or a potentially sensitive secret such as a password used elsewhere. The way that a secret can be either generated or specified is odd, and has some negative implications (currently, we hash the secrets to protect them, so we can't retrieve them after the fact).

As discussed with @aluzzardi and @diogomonica, we think it's better to avoid user-specified secrets and only use automatically generated "join tokens". Then we can more safely store them in plaintext and expose them them through the API/CLI.

This would include the following changes:

- Rename "secret" to "join token". This makes their purpose clearer, and will avoid confusion with actual application-level secrets when we add support for those.
- `docker swarm init` always generates a secret unless `--no-join-token` is specified. It is not possible to specify a user-provided secret for node joining purposes.
- Join tokens will be stored in raft in plaintext so they can be retrieved when the admin wants to use the token to add a new node. However, we shouldn't put them in the `docker info` output because this goes into bug reports. So we would instead add a `docker swarm join-token` subcommand that allows easily scriptable retrieval of the token, and also options to rotate or clear the token.
- Use separate join tokens for workers and managers. The current Docker code uses the same token for both, but at the API level they are separately defined. By splitting them, we'll avoid the possibility of a rogue worker using the join token to add itself as a manager (though note that managers require manual approval by default).

Here is a mockup of how the UX would look:

```
# docker swarm init
Autodetected IP address 192.168.1.1. If this is not the address
where other swarm members will reach this node, recreate this cluster
with the --listen-addr option.

Generated new join tokens:
	worker: 4ao565v9jsuogtq5t8s379ulb
	manager: 2bs0rkz9iuws6zddqayngydrq

Swarm initialized: current node (4ttpzq1ekahoyt7b57m6053x2) is now a manager.

To add a worker to this swarm, run the following command:
  docker swarm join --secret 4ao565v9jsuogtq5t8s379ulb
  --ca-hash sha256:b7986d3baeff2f5664dfe350eec32e2383539ec1a802ba541c4eb829056b5f61 \
  192.168.1.1:2377

# docker swarm join-token
worker: 4ao565v9jsuogtq5t8s379ulb
manager: 2bs0rkz9iuws6zddqayngydrq

# docker swarm join-token --worker  # for easier scripting
4ao565v9jsuogtq5t8s379ulb

# docker swarm join-token --manager  # for easier scripting
2bs0rkz9iuws6zddqayngydrq

# docker swarm join-token --rotate=worker,manager
Generated new join tokens:
	worker: 6jb4d5v9j8uagtq5t8s3v9ule
	manager: 1bshrkh2iuws6addqa3ngydr6

# docker swarm join-token --clear=worker,manager  # swarm no longer requires a token to join
```

ping @diogomonica @aluzzardi @tonistiigi @icecrime @cpuguy83 @dnephin @stevvooe @tiborvass

### PR DESCRIPTION
**Pull request by aaronlehmann**
Implement the proposal from
https://github.com/docker/docker/issues/24430#issuecomment-233100121

Removes acceptance policy and secret in favor of an automatically
generated join token that combines the secret, CA hash, and
manager/worker role into a single opaque string.

Adds a docker swarm join-token subcommand to inspect and rotate the
tokens.

Fixes #24430

cc @tonistiigi @diogomonica @tiborvass @aluzzardi

### CODE REVIEW

File: api/client/swarm/opts.go [hunk 1]
```diff
@@ -15,29 +15,16 @@ import (
...
-	defaultPolicies = []swarm.Policy{
-		{Role: worker, Autoaccept: true},
-		{Role: manager, Autoaccept: false},
-	}
-)
-
 type swarmOptions struct {
-	autoAccept          AutoAcceptOption
-	secret              string
+	token               string
```
Comment (tonistiigi) [inline api/client/swarm/opts.go]: What is this used for?

Comment (aaronlehmann) [inline api/client/swarm/opts.go]: It's the token that is passed to `swarm join -token ...`.

Comment (tonistiigi) [inline api/client/swarm/opts.go]: But join uses `joinOptions`?

Comment (aaronlehmann) [inline api/client/swarm/opts.go]: Missed that. I'll remove it from `swarmOptions`.

Maybe we should rename this to `initUpdateOptions`.

File: daemon/cluster/cluster.go [hunk 2]
```diff
@@ -354,9 +351,6 @@ func (c *Cluster) Join(req types.JoinRequest) error {
 	for {
 		select {
 		case <-certificateRequested:
```
Comment (tonistiigi) [inline daemon/cluster/cluster.go]: Should be safe to remove this whole case, certificateRequested var and for cycle.

File: api/client/swarm/join_token.go [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+
+const (
+	flagRotate = "rotate"
+)
+
+func newJoinTokenCommand(dockerCli *client.DockerCli) *cobra.Command {
+	var rotate bool
+
+	cmd := &cobra.Command{
+		Use:   "join-token [--rotate] worker | manager",
```
Comment (tiborvass) [inline api/client/swarm/join_token.go]: i wonder if it should have parentheses `(worker|manager)` (like in docopt.org) not sure what's the standard here

**Comment by tiborvass** [comment]
I think design-wise we agree so moving to code review.

**Comment by cpuguy83** [comment]
Any chance you can split the swarmkit vendor into a separate commit?

**Comment by aaronlehmann** [comment]
Split the vendoring commits and addressed some early feedback. Starting to work on updating tests.

File: api/client/swarm/join.go [hunk 4]
```diff
@@ -46,20 +42,16 @@ func runJoin(dockerCli *client.DockerCli, opts joinOptions) error {
...
 	err := client.SwarmJoin(ctx, req)
 	if err != nil {
 		return err
 	}
-	if opts.manager {
-		fmt.Fprintln(dockerCli.Out(), "This node joined a Swarm as a manager.")
-	} else {
-		fmt.Fprintln(dockerCli.Out(), "This node joined a Swarm as a worker.")
-	}
+	// TODO(aaronl): Perhaps SwarmJoin should return whether the node
```
Comment (diogomonica) [inline api/client/swarm/join.go]: Agreed.

File: api/client/swarm/join_token.go [hunk 5]
```diff
@@ -0,0 +1,71 @@
...
+					return err
+				}
+			}
+
+			swarm, err := client.SwarmInspect(ctx)
+			if err != nil {
+				return err
+			}
+
+			if args[0] == "worker" {
```
Comment (diogomonica) [inline api/client/swarm/join_token.go]: This will allow rotating both tokens simultaneously. Do we want to have a different output that prefaces each token with `Worker:` and `Manager:` in the case both new tokens are being printed out?

Comment (aaronlehmann) [inline api/client/swarm/join_token.go]: You can only rotate one at a time.

**Comment by diogomonica** [comment]
LGTM

**Comment by aaronlehmann** [comment]
Tests should be passing now. Also restored the `This node joined a Swarm as a (worker|manager)` message. Starting to work on doc changes.

**Comment by aaronlehmann** [comment]
I've updated the API and CLI reference docs. @sfsmithcha @thaJeztah PTAL.

**Comment by aaronlehmann** [comment]
engine-api PR is docker/engine-api#327.

swarmkit PR is docker/swarmkit#1189 (already merged). I'll fix the swarmkit vendoring once engine-api is ready to go as well.

**Comment by aaronlehmann** [comment]
Both upstream PRs were merged. Updated the PR to properly vendor those components.

**Comment by tonistiigi** [comment]
LGTM

File: docs/reference/commandline/node_ls.md [hunk 6]
```diff
@@ -54,16 +54,16 @@ The `name` filter matches on all or part of a node name.
...
+    e216jshn25ckzbvmwlnh5jr3g *  swarm-manager1  Ready   Active        Reachable       Yes
 
 ### id
 
 The `id` filter matches all or part of a node's id.
 
     $ docker node ls -f id=1
-    ID                         HOSTNAME       MEMBERSHIP  STATUS  AVAILABILITY  MANAGER STATUS  LEADER
-    1bcef6utixb0l0ca7gxuivsj0  swarm-worker2  Accepted    Ready   Active
+    ID                         HOSTNAME       STATUS  AVAILABILITY  MANAGER STATUS  LEADER
```
Comment (sfsmithcha) [inline docs/reference/commandline/node_ls.md]: Is this right? I don't see a `LEADER` column.

```
ID                           HOSTNAME      STATUS  AVAILABILITY  MANAGER STATUS
5ff7wbwlpntfir9o85ji525d2 *  2b2a7bb10c50  Ready   Active        Leader

Comment (aaronlehmann) [inline docs/reference/commandline/node_ls.md]: Thanks. Unrelated to my change, but I've corrected these examples.

File: docs/reference/commandline/swarm_init.md [hunk 7]
```diff
@@ -34,54 +32,22 @@ in the newly created one node Swarm cluster.
...
-To disable auto acceptance, use the `none` option. Note that this option cannot
-be combined with other values. When disabling auto acceptance, nodes must be
-manually accepted or rejected using `docker node accept` or `docker node rm`.
-
-The following example enables swarm mode with auto acceptance disabled:
-
-```bash
-$ docker swarm init --listen-addr 192.168.99.121:2377 --auto-accept none
-```
+`docker swarm init` generates random tokens that can be used by other nodes to join the swarm as
```
Comment (sfsmithcha) [inline docs/reference/commandline/swarm_init.md]: This could be stronger:

`docker swarm init` generates two random tokens, a worker token and a manager token. When you join a new node to the swarm, the node joins as a worker node or manager node based upon the token you pass to `docker swarm join`.

After you create the swarm, you can display a token or rotate a token using [swarm join token](swarm_join_token.md).

File: docs/reference/commandline/swarm_join.md [hunk 8]
```diff
@@ -17,52 +17,52 @@ Usage:  docker swarm join [OPTIONS] HOST:PORT
...
       --help                Print usage
       --listen-addr value   Listen address (default 0.0.0.0:2377)
-      --manager             Try joining as a manager.
-      --secret string       Secret for node acceptance
+      --token string        Token for entry into the swarm
 ```
 
-Join a node to a Swarm cluster. If the `--manager` flag is specified, the docker engine
-targeted by this command becomes a `manager`. If it is not specified, it becomes a `worker`.
+Join a node to a Swarm cluster. If the token given to the `--token` flag is a manager token,
```
Comment (sfsmithcha) [inline docs/reference/commandline/swarm_join.md]: Swarm is lowercase except at the beginning of a sentence.  Suggest:

Join a node to a swarm. The node joins as a manager node or worker node based upon the token you pass with the `--token` flag. If you pass a manager token, the node joins as a manager. If you pass a worker token, the node joins as a worker.

File: docs/reference/commandline/swarm_join.md [hunk 9]
```diff
@@ -17,52 +17,52 @@ Usage:  docker swarm join [OPTIONS] HOST:PORT
...
+the Docker engine targeted by this command becomes a `manager`. If it is a worker token, this
+engine becomes a `worker`.
 
 ### Join a node to swarm as a manager
 
+In the example below, the token given to `--token` is a manager token.
```
Comment (sfsmithcha) [inline docs/reference/commandline/swarm_join.md]: The example below demonstrates using a manager token.

File: docs/reference/commandline/swarm_join.md [hunk 10]
```diff
@@ -17,52 +17,52 @@ Usage:  docker swarm join [OPTIONS] HOST:PORT
...
+dvfxp4zseq4s0rih1selh0d20    manager1  Ready   Active        Leader
 ```
 
+A cluster should only have 3-7 managers at most, because a majority of managers must be available
+for the cluster to function. Nodes that aren't meant to participate in this management quorum
+should join as workers instead. Managers should be stable hosts that have static IP addresses.
+
 ### Join a node to swarm as a worker
 
+This command line is the same as the example above, except that the token is a worker token, which
```
Comment (sfsmithcha) [inline docs/reference/commandline/swarm_join.md]: The example below demonstrates joining a worker node using a worker token.

File: docs/reference/commandline/swarm_join_token.md [hunk 11]
```diff
@@ -0,0 +1,52 @@
...
+Usage:	docker swarm join-token [--rotate] (worker|manager)
+
+Manage join tokens
+
+Options:
+      --help     Print usage
+      --rotate   Rotate join token
+```
+
+Join tokens are the strings passed to the `--token` flag of `swarm join`. This command allows the
```
Comment (sfsmithcha) [inline docs/reference/commandline/swarm_join_token.md]: Join tokens are secrets that determine whether or not a node will join the swarm as a manager node or a worker node. You pass the token using the `--token` flag when you run `swarm join`. You can access the current tokens or rotate the tokens using `swarm join-token`.

File: docs/reference/commandline/swarm_join_token.md [hunk 12]
```diff
@@ -0,0 +1,52 @@
...
+title = "swarm join-token"
+description = "The swarm join-token command description and usage"
+keywords = ["swarm, join-token"]
+advisory = "rc"
+[menu.main]
+parent = "smn_cli"
++++
+<![end-metadata]-->
+
+# swarm init
```
Comment (sfsmithcha) [inline docs/reference/commandline/swarm_join_token.md]: # swarm join-token

File: docs/reference/commandline/swarm_join_token.md [hunk 13]
```diff
@@ -0,0 +1,52 @@
...
+role:
+
+```bash
+$ docker swarm join-token worker
+SWMTKN-1-3pu6hszjas19xyp7ghgosyx9k8atbfcr8p2is99znpy26u2lkl-1awxwuwd3z9j1z3puu7rcgdbx
+$ docker swarm join-token manager
+SWMTKN-1-3pu6hszjas19xyp7ghgosyx9k8atbfcr8p2is99znpy26u2lkl-7p73s1dx5in4tatdymyhg9hu2
+```
+
+When used with the `--rotate` flag, a new join token will be generated for the specified role,
```
Comment (sfsmithcha) [inline docs/reference/commandline/swarm_join_token.md]: Use the `--rotate` fag to generate a new join token for the specified role and print the output:

File: docs/reference/commandline/swarm_join_token.md [hunk 14]
```diff
@@ -0,0 +1,52 @@
...
+and printed to the output:
+
+```bash
+$ docker swarm join-token --rotate worker
+SWMTKN-1-3pu6hszjas19xyp7ghgosyx9k8atbfcr8p2is99znpy26u2lkl-b30ljddcqhef9b9v4rs7mel7t
+```
+
+### `--rotate`
+
+This flag causes the join token for the specified role to be replaced with a new token.
```
Comment (sfsmithcha) [inline docs/reference/commandline/swarm_join_token.md]: Update the join token for a specified role with a new token and print the token.

**Comment by sfsmithcha** [comment]
Aside from cp/paste error in header of `swarm join-token` and editorial suggestions LGTM

File: docs/reference/commandline/swarm_join.md (hunk 8 above)
Comment (aaronlehmann) [inline docs/reference/commandline/swarm_join.md]: I'm afraid `Swarm` isn't consistently lowercased. The "swarm join" reference page uses a mix of title case and lower case, and messages from the CLI itself tend to use title case; for example "This node joined a Swarm as a worker.".

Should I go through and change these?

Comment (tiborvass) [inline docs/reference/commandline/swarm_join.md]: I suggest fixing casing in a separate docs PR to make it consistent everywhere.

Comment (aaronlehmann) [inline docs/reference/commandline/swarm_join.md]: I'll just do it here if you don't mind. It's not many changes, but I'm worried about conflicts if I make a separate PR.

**Comment by aaronlehmann** [comment]
Added a commit to address docs feedback. Will squash this once it has been reviewed.

I fixed title case references to `Swarm` in the actual CLI and the CLI reference docs. There are still quite a few in other docs. These can be addressed in a separate PR.

File: docs/reference/commandline/swarm_join.md (hunk 8 above)
Comment (sfsmithcha) [inline docs/reference/commandline/swarm_join.md]: @tiborvass , @aaronlehmann , either way, we'll need to review the doc set for consistent usage in addition to this PR. So I've opened a docs issue: https://github.com/docker/docker/issues/24905

**Comment by aaronlehmann** [comment]
I've updated `docker swarm join-token` to print a full `docker swarm join` command by default, per the suggestion in #24907. With the `-q` or `--quiet` option, it only prints the token.

PTAL.

**Comment by tiborvass** [comment]
Small nit, but it feels weird to have `join` and `join-token` not next to each other in `docker swarm`'s output.

**Comment by tiborvass** [comment]
Otherwise LGTM

**Comment by SvenDowideit** [comment]
this appears to have been cherry-picked into bump_v1.12.0 already.
