### PR TITLE
When authz plugin is disabled, remove from authz middleware chain.

### LINKED ISSUE #31836: Unable to enable/disable authZ plugins via the plugin APIs
**Description**

I'm trying to `disable` an `authZ` plugin using the `docker CLI`, but the `daemon` is still routing the events to the `stopped` plugin. The `docker-engine` doesn't work after disabling the `plugin` -- it requires a manual `removal`. 

**Steps to reproduce the issue:**
1. `docker plugin install index-stage.docker.io/rogaha/rogaha-auth-plugin:latest`
2. add `--authorization-plugin=index-stage.docker.io/rogaha/rogaha-auth-plugin:latest` to the `dockerd` parameters (I modified the `/etc/init.d/docker` in `Moby`)
3. restart the `docker` service
4. `docker plugin disable index-stage.docker.io/rogaha/rogaha-auth-plugin:latest`
5. Try any docker command and it will hang trying to reach the disabled authz plugin.

**Describe the results you received:**
```
Mar 15 01:15:27 moby root: time="2017-03-15T01:15:27.254597975Z" level=debug msg="Calling POST /v1.26/plugins/index-stage.docker.io/rogaha/rogaha-auth-plugin:latest/disable"
Mar 15 01:15:27 moby root: time="2017-03-15T01:15:27.254673208Z" level=debug msg="AuthZ request using plugin index-stage.docker.io/rogaha/rogaha-auth-plugin:latest"
Mar 15 01:15:27 moby root: time="2017-03-15T01:15:27Z" level=info msg="time=\"2017-03-15T01:15:27Z\" level=info msg=\"{User: UserAuthNMethod: RequestMethod:POST RequestURI:/v1.26/plugins/index-stage.docker.io/rogaha/rogaha-auth-plugin:latest/disable RequestBody:[] RequestHeaders:map[Content-Length:0 Content-Type:text/plain User-Agent:Docker-Client/17.03.0-ce (darwin)] RequestPeerCertificates:[] ResponseStatusCode:0 ResponseBody:[] ResponseHeaders:map[]}\" " plugin=90f69d63bc4a0f2f7317ef4a5ccec3741c9bc68266cdd87fe63781d6c733d548
Mar 15 01:15:27 moby root: time="2017-03-15T01:15:27.377523224Z" level=debug msg="containerd: process exited" id=90f69d63bc4a0f2f7317ef4a5ccec3741c9bc68266cdd87fe63781d6c733d548 pid=init status=2 systemPid=6723
Mar 15 01:15:27 moby root: time="2017-03-15T01:15:27.382569366Z" level=debug msg="libcontainerd: received containerd event: &types.Event{Type:\"exit\", Id:\"90f69d63bc4a0f2f7317ef4a5ccec3741c9bc68266cdd87fe63781d6c733d548\", Status:0x2, Pid:\"init\", Timestamp:(*timestamp.Timestamp)(0xc421032900)}"
Mar 15 01:15:27 moby root: time="2017-03-15T01:15:27.382763034Z" level=debug msg="plugin state changed 90f69d63bc4a0f2f7317ef4a5ccec3741c9bc68266cdd87fe63781d6c733d548 libcontainerd.StateInfo{CommonStateInfo:libcontainerd.CommonStateInfo{State:\"exit\", Pid:0x0, ExitCode:0x2, ProcessID:\"\"}, OOMKilled:false}"
Mar 15 01:15:27 moby root: time="2017-03-15T01:15:27.382832644Z" level=debug msg="Clean shutdown of plugin"
Mar 15 01:15:27 moby root: time="2017-03-15T01:15:27.397478862Z" level=debug msg="AuthZ response using plugin index-stage.docker.io/rogaha/rogaha-auth-plugin:latest"
Mar 15 01:15:27 moby root: time="2017-03-15T01:15:27.397734817Z" level=warning msg="Unable to connect to plugin: /run/docker/plugins/90f69d63bc4a0f2f7317ef4a5ccec3741c9bc68266cdd87fe63781d6c733d548/rogaha.sock/AuthZPlugin.AuthZRes: Post http://%2Frun%2Fdocker%2Fplugins%2F90f69d63bc4a0f2f7317ef4a5ccec3741c9bc68266cdd87fe63781d6c733d548%2Frogaha.sock/AuthZPlugin.AuthZRes: dial unix /run/docker/plugins/90f69d63bc4a0f2f7317ef4a5ccec3741c9bc68266cdd87fe63781d6c733d548/rogaha.sock: connect: no such file or directory, retrying in 1s"
Mar 15 01:15:28 moby root: time="2017-03-15T01:15:28.399704517Z" level=warning msg="Unable to connect to plugin: /run/docker/plugins/90f69d63bc4a0f2f7317ef4a5ccec3741c9bc68266cdd87fe63781d6c733d548/rogaha.sock/AuthZPlugin.AuthZRes: Post http://%2Frun%2Fdocker%2Fplugins%2F90f69d63bc4a0f2f7317ef4a5ccec3741c9bc68266cdd87fe63781d6c733d548%2Frogaha.sock/AuthZPlugin.AuthZRes: dial unix /run/docker/plugins/90f69d63bc4a0f2f7317ef4a5ccec3741c9bc68266cdd87fe63781d6c733d548/rogaha.sock: connect: no such file or directory, retrying in 2s"
Mar 15 01:15:29 moby root: time="2017-03-15T01:15:29.526485973Z" level=info msg="agent: found node update" module="node/agent"
Mar 15 01:15:29 moby root: time="2017-03-15T01:15:29.526683662Z" level=debug msg="agent: rebuild session" module="node/agent"
Mar 15 01:15:29 moby root: time="2017-03-15T01:15:29.526842431Z" level=debug msg="(*session).start" module="node/agent"
Mar 15 01:15:29 moby root: time="2017-03-15T01:15:29.533631110Z" level=debug msg="node status updated" method="(*Dispatcher).processUpdates" module=dispatcher node.id=3ae4dpdznkbm5x3n1e2qtomai
Mar 15 01:15:29 moby root: time="2017-03-15T01:15:29.539761085Z" level=debug method="(*session).logSubscriptions" module="node/agent" session.id=q77l0f8yew6xp7jvedb5epbhs
Mar 15 01:15:29 moby root: time="2017-03-15T01:15:29.539831626Z" level=debug msg="(*session).heartbeat" module="node/agent" session.id=q77l0f8yew6xp7jvedb5epbhs
Mar 15 01:15:29 moby root: time="2017-03-15T01:15:29.539889048Z" level=debug method="(*session).watch" module="node/agent" session.id=q77l0f8yew6xp7jvedb5epbhs
Mar 15 01:15:29 moby root: time="2017-03-15T01:15:29.539920683Z" level=debug msg="(*session).listen" module="node/agent" session.id=q77l0f8yew6xp7jvedb5epbhs
Mar 15 01:15:29 moby root: time="2017-03-15T01:15:29.539959765Z" level=debug msg="agent: registered" module="node/agent"
Mar 15 01:15:29 moby root: time="2017-03-15T01:15:29.540092862Z" level=debug method="(*Dispatcher).Assignments" node.id=3ae4dpdznkbm5x3n1e2qtomai node.session=q77l0f8yew6xp7jvedb5epbhs
Mar 15 01:15:29 moby root: time="2017-03-15T01:15:29.540429606Z" level=debug msg="node registered" method="(*LogBroker).ListenSubscriptions" node=3ae4dpdznkbm5x3n1e2qtomai
Mar 15 01:15:29 moby root: time="2017-03-15T01:15:29.541141613Z" level=debug msg="(*worker).Assign" len(assignments)=5 module="node/agent"
Mar 15 01:15:29 moby root: time="2017-03-15T01:15:29.541170272Z" level=debug msg="(*worker).reconcileSecrets" len(removedSecrets)=0 len(updatedSecrets)=0 module="node/agent"
Mar 15 01:15:29 moby root: time="2017-03-15T01:15:29.541215015Z" level=debug msg="(*worker).reconcileTaskState" len(removedTasks)=0 len(updatedTasks)=5 module="node/agent"
Mar 15 01:15:29 moby root: time="2017-03-15T01:15:29.541302834Z" level=debug msg=assigned module="node/agent" task.desiredstate=SHUTDOWN task.id=48kg3574enk1atvdc5wr5qgie
Mar 15 01:15:29 moby root: time="2017-03-15T01:15:29.541389724Z" level=debug msg=assigned module="node/agent" task.desiredstate=SHUTDOWN task.id=q2xu69kuakvrl64tq8zpsxafg
Mar 15 01:15:29 moby root: time="2017-03-15T01:15:29.541587333Z" level=debug msg=assigned module="node/agent" task.desiredstate=RUNNING task.id=q9i05l9vp1yy0cmg8xius5iyj
Mar 15 01:15:29 moby root: time="2017-03-15T01:15:29.541646601Z" level=debug msg=assigned module="node/agent" task.desiredstate=SHUTDOWN task.id=qsbcp55lhnp3mr8r32bfuz2xi
Mar 15 01:15:29 moby root: time="2017-03-15T01:15:29.541669671Z" level=debug msg=assigned module="node/agent" task.desiredstate=SHUTDOWN task.id=zxne6z25vc15wnvhxe02j20lw
Mar 15 01:15:30 moby root: time="2017-03-15T01:15:30.400743335Z" level=warning msg="Unable to connect to plugin: /run/docker/plugins/90f69d63bc4a0f2f7317ef4a5ccec3741c9bc68266cdd87fe63781d6c733d548/rogaha.sock/AuthZPlugin.AuthZRes: Post http://%2Frun%2Fdocker%2Fplugins%2F90f69d63bc4a0f2f7317ef4a5ccec3741c9bc68266cdd87fe63781d6c733d548%2Frogaha.sock/AuthZPlugin.AuthZRes: dial unix /run/docker/plugins/90f69d63bc4a0f2f7317ef4a5ccec3741c9bc68266cdd87fe63781d6c733d548/rogaha.sock: connect: no such file or directory, retrying in 4s"
Mar 15 01:15:34 moby root: time="2017-03-15T01:15:34.405922304Z" level=warning msg="Unable to connect to plugin: /run/docker/plugins/90f69d63bc4a0f2f7317ef4a5ccec3741c9bc68266cdd87fe63781d6c733d548/rogaha.sock/AuthZPlugin.AuthZRes: Post http://%2Frun%2Fdocker%2Fplugins%2F90f69d63bc4a0f2f7317ef4a5ccec3741c9bc68266cdd87fe63781d6c733d548%2Frogaha.sock/AuthZPlugin.AuthZRes: dial unix /run/docker/plugins/90f69d63bc4a0f2f7317ef4a5ccec3741c9bc68266cdd87fe63781d6c733d548/rogaha.sock: connect: no such file or directory, retrying in 8s"
Mar 15 01:15:42 moby root: time="2017-03-15T01:15:42.410673503Z" level=error msg="AuthZResponse for POST /v1.26/plugins/index-stage.docker.io/rogaha/rogaha-auth-plugin:latest/disable returned error: plugin index-stage.docker.io/rogaha/rogaha-auth-plugin:latest failed with error: Post http://%2Frun%2Fdocker%2Fplugins%2F90f69d63bc4a0f2f7317ef4a5ccec3741c9bc68266cdd87fe63781d6c733d548%2Frogaha.sock/AuthZPlugin.AuthZRes: dial unix /run/docker/plugins/90f69d63bc4a0f2f7317ef4a5ccec3741c9bc68266cdd87fe63781d6c733d548/rogaha.sock: connect: no such file or directory"
Mar 15 01:15:42 moby root: time="2017-03-15T01:15:42.410850409Z" level=error msg="Handler for POST /v1.26/plugins/index-stage.docker.io/rogaha/rogaha-auth-plugin:latest/disable returned error: plugin index-stage.docker.io/rogaha/rogaha-auth-plugin:latest failed with error: Post http://%2Frun%2Fdocker%2Fplugins%2F90f69d63bc4a0f2f7317ef4a5ccec3741c9bc68266cdd87fe63781d6c733d548%2Frogaha.sock/AuthZPlugin.AuthZRes: dial unix /run/docker/plugins/90f69d63bc4a0f2f7317ef4a5ccec3741c9bc68266cdd87fe63781d6c733d548/rogaha.sock: connect: no such file or directory"
```

**Describe the results you expected:**
 - `Enable/disable` the plugin without having to restart the `daemon` using the plugin's API (e.g. `docker plugin disable ...`)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 30
 Running: 1
 Paused: 0
 Stopped: 29
Images: 136
Server Version: 17.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Authorization: index-stage.docker.io/rogaha/rogaha-auth-plugin:latest
Swarm: active
 NodeID: 3ae4dpdznkbm5x3n1e2qtomai
 Is Manager: true
 ClusterID: o0sxc2wbd0pcpg7zoezvy341w
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.65.2
 Manager Addresses:
  192.168.65.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.12-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: KICG:OKKZ:44AF:Q665:VP5O:6Q4L:R5JP:7Z2C:R64P:SY5U:67HK:6KII
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 45
 Goroutines: 148
 System Time: 2017-03-15T13:20:50.315011712Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: rogaha
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by anusha-ragunathan**
When the daemon is configured to run with an authorization-plugin and if
the plugin is disabled, the daemon continues to send API requests to the
plugin and expect it to respond. But the plugin has been disabled. As a
result, all API requests are blocked. Fix this behavior by removing the
disabled plugin from the authz middleware chain.

Tested using riyaz/authz-no-volume-plugin and observed that after
disabling the plugin, API request/response is functional.

Fixes #31836

Signed-off-by: Anusha Ragunathan <anusha.ragunathan@docker.com>

### CODE REVIEW

**Comment by anusha-ragunathan** [comment]
@rogaha :This PR should fix 31836. Can you please test out the PR and confirm that your use case works after the fix?

File: cmd/dockerd/daemon.go [hunk 1]
```diff
@@ -508,10 +511,15 @@ func (cli *DaemonCli) initMiddlewares(s *apiserver.Server, cfg *apiserver.Config
 		s.UseMiddleware(c)
 	}
 
-	if err := validateAuthzPlugins(cli.Config.AuthorizationPlugins, cli.d.PluginStore); err != nil {
-		return fmt.Errorf("Error validating authorization plugin: %v", err)
-	}
-	cli.authzMiddleware = authorization.NewMiddleware(cli.Config.AuthorizationPlugins, cli.d.PluginStore)
+	// XXX: enabled plugins are not yet restored and running when this call is made.
```
Comment (anusha-ragunathan) [inline cmd/dockerd/daemon.go]: @riyazdf : I ran into errors here when an enabled plugin is looked up for validation, even before the plugin is restored to running state. How does `TestAuthZPluginAllowNonVolumeRequest` pass?

Comment (anusha-ragunathan) [inline cmd/dockerd/daemon.go]: Never mind. I changed the order of initialization such that authz middleware is initialized before plugin is restored. Need to rework that part.

File: cmd/dockerd/daemon.go [hunk 2]
```diff
@@ -494,10 +502,10 @@ func initRouter(s *apiserver.Server, d *daemon.Daemon, c *cluster.Cluster) {
 	s.InitRouter(debug.IsEnabled(), routers...)
 }
 
-func (cli *DaemonCli) initMiddlewares(s *apiserver.Server, cfg *apiserver.Config) error {
+func (cli *DaemonCli) initMiddlewares(s *apiserver.Server, cfg *apiserver.Config, pluginStore *plugin.Store) error {
 	v := cfg.Version
 
-	exp := middleware.NewExperimentalMiddleware(cli.d.HasExperimental())
+	exp := middleware.NewExperimentalMiddleware(cli.Config.Experimental)
```
Comment (riyazdf) [inline cmd/dockerd/daemon.go]: For my own understanding: this is necessary now because we init the middlewares prior to starting the daemon right?  Could we add a comment to this function if so, stating that we can't expect `cli.d` to be non-nil since this runs prior to starting the daemon?

File: pkg/authorization/plugin.go [hunk 3]
```diff
@@ -98,6 +103,7 @@ func (a *authorizationPlugin) initPlugin() error {
 
 			if pg := GetPluginGetter(); pg != nil {
 				plugin, e = pg.Get(a.name, AuthZApiImplements, plugingetter.Lookup)
+				a.SetName(plugin.Name())
```
Comment (riyazdf) [inline pkg/authorization/plugin.go]: does this need to be in the `else` case below too?

File: plugin/backend_linux.go [hunk 4]
```diff
@@ -56,6 +56,19 @@ func (pm *Manager) Disable(refOrID string, config *types.PluginDisableConfig) er
 		return fmt.Errorf("plugin %s is in use", p.Name())
 	}
 
+	for _, typ := range p.GetTypes() {
+		if typ.Capability == "authz" {
```
Comment (riyazdf) [inline plugin/backend_linux.go]: can we use `authorization.AuthZApiImplements`?

File: cmd/dockerd/daemon.go [hunk 5]
```diff
@@ -264,11 +265,22 @@ func (cli *DaemonCli) start(opts daemonOptions) (err error) {
 	// Notify that the API is active, but before daemon is set up.
 	preNotifySystem()
 
-	d, err := daemon.NewDaemon(cli.Config, registryService, containerdRemote)
+	pluginStore := plugin.NewStore(cli.Config.Root)
```
Comment (riyazdf) [inline cmd/dockerd/daemon.go]: I'm not too familiar with the `Config.Root` - but did we want this in `<root>/plugins` or is the root expected?

**Review by riyazdf — COMMENTED** [review]
code looks great!  I have some clarifying questions in my review.

Also could it be possible to amend the tests in `docker_cli_authz_plugin_v2_test.go` to validate that the daemon's plugin state is updated and that other docker command succeed after disabling?

File: cmd/dockerd/daemon.go (hunk 5 above)
Comment (anusha-ragunathan) [inline cmd/dockerd/daemon.go]: `plugin.NewManager` takes care of that. Infact, we dont need to pass down `cli.Config.Root` while initializing store anymore. I'll remove this.

File: cmd/dockerd/daemon.go (hunk 2 above)
Comment (anusha-ragunathan) [inline cmd/dockerd/daemon.go]: `cli.d` will ofcourse be nil since this function is run *before* `NewDaemon`. That's why I'm using `cli.Config.Experimental` rather than `cli.d.HasExperimental`

File: pkg/authorization/plugin.go (hunk 3 above)
Comment (anusha-ragunathan) [inline pkg/authorization/plugin.go]: No, the else case is for v1 plugins.

**Comment by anusha-ragunathan** [comment]
@riyazdf : Added `TestAuthZPluginDisable` to test API works after disabling plugin.

**Comment by rogaha** [comment]
that's awesome! Thanks for putting it together @anusha-ragunathan! I'll try it out today.

File: cmd/dockerd/daemon.go (hunk 2 above)
Comment (riyazdf) [inline cmd/dockerd/daemon.go]: 👍 any chance we can add a comment to this function so that future contributors don't attempt to use `cli.d`?

File: integration-cli/docker_cli_authz_plugin_v2_test.go [hunk 6]
```diff
@@ -75,6 +75,36 @@ func (s *DockerAuthzV2Suite) TestAuthZPluginAllowNonVolumeRequest(c *check.C) {
...
+	out, err := s.d.Cmd("volume", "create")
+	c.Assert(err, check.NotNil)
+	c.Assert(out, checker.Contains, fmt.Sprintf("Error response from daemon: plugin %s failed with error:", authzPluginNameWithTag))
+
+	// disable the plugin
+	_, err = s.d.Cmd("plugin", "disable", authzPluginNameWithTag)
+	c.Assert(err, checker.IsNil)
+
+	// now test to see if the docker api works.
+	out, err = s.d.Cmd("volume", "create")
```
Comment (riyazdf) [inline integration-cli/docker_cli_authz_plugin_v2_test.go]: nit: we don't need to assign to `out` since it isn't checked

File: pkg/authorization/middleware.go [hunk 7]
```diff
@@ -25,6 +25,20 @@ func NewMiddleware(names []string, pg plugingetter.PluginGetter) *Middleware {
...
+	m.mu.Lock()
+	defer m.mu.Unlock()
+	return m.plugins
+}
+
+// SetAuthzPlugins sets authorization plugins
+func (m *Middleware) SetAuthzPlugins(plugins []Plugin) {
+	m.mu.Lock()
+	m.plugins = plugins
+	m.mu.Unlock()
```
Comment (riyazdf) [inline pkg/authorization/middleware.go]: nit: this could be `defer m.mu.Unlock()` like the above function

File: integration-cli/docker_cli_authz_plugin_v2_test.go [hunk 8]
```diff
@@ -75,6 +75,36 @@ func (s *DockerAuthzV2Suite) TestAuthZPluginAllowNonVolumeRequest(c *check.C) {
 	c.Assert(assertContainerList(out, []string{id}), check.Equals, true)
 }
 
+func (s *DockerAuthzV2Suite) TestAuthZPluginDisable(c *check.C) {
```
Comment (riyazdf) [inline integration-cli/docker_cli_authz_plugin_v2_test.go]: 👍

File: integration-cli/docker_cli_authz_plugin_v2_test.go [hunk 9]
```diff
@@ -75,6 +75,36 @@ func (s *DockerAuthzV2Suite) TestAuthZPluginAllowNonVolumeRequest(c *check.C) {
...
+	testRequires(c, DaemonIsLinux, IsAmd64, Network)
+	// Install authz plugin
+	_, err := s.d.Cmd("plugin", "install", "--grant-all-permissions", authzPluginNameWithTag)
+	c.Assert(err, checker.IsNil)
+	// start the daemon with the plugin and load busybox, --net=none build fails otherwise
+	// because it needs to pull busybox
+	s.d.Restart(c, "--authorization-plugin="+authzPluginNameWithTag)
+	c.Assert(s.d.LoadBusybox(), check.IsNil)
+
+	// defer disabling the plugin
```
Comment (riyazdf) [inline integration-cli/docker_cli_authz_plugin_v2_test.go]: super non-blocking nit: `s/disabling/removing`

**Review by riyazdf — COMMENTED** [review]
thanks for updating, LGTM after nits

File: integration-cli/docker_cli_authz_plugin_v2_test.go (hunk 8 above)
Comment (anusha-ragunathan) [inline integration-cli/docker_cli_authz_plugin_v2_test.go]: if you use `cli.d` here, daemon will panic and its quite obvious that `cli.d` is assigned later on. I dont think we need a comment to explain the obvious.

File: pkg/authorization/middleware.go (hunk 7 above)
Comment (anusha-ragunathan) [inline pkg/authorization/middleware.go]: `defer` typically adds a cost. `GetAuthzPlugins` needs to have the `defer` for unlock.

File: cmd/dockerd/daemon.go (hunk 2 above)
Comment (anusha-ragunathan) [inline cmd/dockerd/daemon.go]: if you use cli.d here, daemon will panic and its quite obvious that cli.d is assigned later on. I dont think we need a comment to explain the obvious.

Comment (riyazdf) [inline cmd/dockerd/daemon.go]: I'm worried that it might not be so obvious to outside contributors, but I might be overthinking it so I'll leave it up to you.

Knowing that `cli.d` is nil here relies on carefully reading the ordering of code in `start`, which has just changed from previously being the other way around of starting the daemon before initializing middlewares

**Comment by rogaha** [comment]
@anusha-ragunathan the `disable` worked as expected. However the `enable` didn't work and if I restart the `daemon` while the plugin is disabled the `daemon` doesn't start. 

**error message:**
```
ar 21 00:33:27 moby root: time="2017-03-21T00:33:27.165290541Z" level=debug msg="/usr/local/sbin/iptables, [--wait -I FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT]"
Mar 21 00:33:27 moby root: time="2017-03-21T00:33:27.167359157Z" level=debug msg="/usr/local/sbin/iptables, [--wait -t filter -C FORWARD -j DOCKER-ISOLATION]"
Mar 21 00:33:27 moby root: time="2017-03-21T00:33:27.169540643Z" level=debug msg="/usr/local/sbin/iptables, [--wait -D FORWARD -j DOCKER-ISOLATION]"
Mar 21 00:33:27 moby root: time="2017-03-21T00:33:27.172036268Z" level=debug msg="/usr/local/sbin/iptables, [--wait -I FORWARD -j DOCKER-ISOLATION]"
Mar 21 00:33:27 moby root: time="2017-03-21T00:33:27.174231338Z" level=debug msg="/usr/local/sbin/iptables, [--wait -t filter -C DOCKER-ISOLATION -i docker0 -o br-fe1b858575e8 -j DROP]"
Mar 21 00:33:27 moby root: time="2017-03-21T00:33:27.176073215Z" level=debug msg="/usr/local/sbin/iptables, [--wait -I DOCKER-ISOLATION -i docker0 -o br-fe1b858575e8 -j DROP]"
Mar 21 00:33:27 moby root: time="2017-03-21T00:33:27.177930575Z" level=debug msg="/usr/local/sbin/iptables, [--wait -t filter -C DOCKER-ISOLATION -i br-fe1b858575e8 -o docker0 -j DROP]"
Mar 21 00:33:27 moby root: time="2017-03-21T00:33:27.179771753Z" level=debug msg="/usr/local/sbin/iptables, [--wait -I DOCKER-ISOLATION -i br-fe1b858575e8 -o docker0 -j DROP]"
Mar 21 00:33:27 moby root: time="2017-03-21T00:33:27.362095443Z" level=info msg="Loading containers: done."
Mar 21 00:33:27 moby root: Error validating authorization plugin: plugin "index-stage.docker.io/rogaha/rogaha-auth-plugin:latest" not found
```

Is it possible to check the `plugin` state during the `dockerd` start up process?

**Comment by anusha-ragunathan** [comment]
This brings up the bigger point of whether we want clients to control the behavior of the docker daemon, by installing an authz plugin that hijacks the engine-api proxy. IMO, if we want clients to be able to `disable` an authz plugin and get back to normal engine API behavior, then we should have clients be able to `enable` an authz plugin as well.

@riyazdf : WDYT?

**Comment by rogaha** [comment]
@anusha-ragunathan as you mentioned in our conversation on Slack, an `user` that controls the `daemon` should be able to handle the daemon `restart` in case the client `disabled` the authz plugin also the authz plugin can protect itself it the `disable` is not wanted. So, IMHO, I think we should keep the PR as it's (disable only) to prevent potential abuse of the `authz` plugin.

**Comment by rogaha** [comment]
I confirm that the `disable` works as expected! LGTM

**Comment by anusha-ragunathan** [comment]
@rogaha : Agree that although the `disable` request can be sent by the client, it can be disallowed by the authz plugin if needed, which is safe. The same approach doesnt hold for enable and hence we should not enable the plugin using the client and continue to keep it as a `dockerd` startup flag.

**Comment by riyazdf** [comment]
I agree with @anusha-ragunathan's point that `disable` is safer here than `enable` 👍

**Comment by rogaha** [comment]
@anusha-ragunathan 👍

**Comment by riyazdf** [comment]
we'll probably want to update [authz plugin docs](https://docs.docker.com/engine/extend/plugins_authorization/#setting-up-docker-daemon) if/when we merge this change, especially for the case if the daemon is restarted after a `plugin disable` that did not also update the daemon flags?

**Comment by anusha-ragunathan** [comment]
@riyazdf : the doc update is orthogonal to this PR. Even without this PR, the plugin will get disabled and the next dockerd start will error out unable to find the disabled plugin. I do think authz plugin docs in general need an audit and overhaul w.r.t pluginv2. We can do that in a separate PR.

**Comment by riyazdf** [comment]
agreed, can be a separate PR - just came to mind

File: daemon/config/config.go [hunk 10]
```diff
@@ -82,6 +83,7 @@ type CommonTLSOptions struct {
 // It includes json tags to deserialize configuration from a file
 // using the same names that the flags in the command line use.
 type CommonConfig struct {
+	AuthzMiddleware      *authorization.Middleware
```
Comment (tiborvass) [inline daemon/config/config.go]: Add `json:"-"`

**Comment by tiborvass** [comment]
Apart from small nit, code looks good

**Comment by vieux** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM
