### PR TITLE
Fix `docker build --label` when the label includes single quotes and a space

### LINKED ISSUE #31697: Can't build images with labels that contains space inside of quotes
**Description**
Can't build images with label that contains space ( ) between quotes(') in it's value.

**Steps to reproduce the issue:**
1. run command `docker build --label "key='first second'"`

**Describe the results you received:**
I get the following error:
```Error response from daemon: Syntax error - can't find = in "second''". Must be of the form: name=value```

**Describe the results you expected:**
I expect the build to run regularly and the resulted image to have a label with key named `key` and value `'first second'`.

**Additional information you deem important (e.g. issue happens only occasionally):**
This problem happen to me after upgrading to docker 17.03 from docker 1.12. This
bug didn't occur to me on docker 1.12.

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Mar  2 01:11:00 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: $$
 Running: $$
 Paused: $$
 Stopped: $$
Images: $$
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 299
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.52-boot2docker
Operating System: Boot2Docker 17.03.0-ce (TCL 7.2); HEAD : f11a204 - Thu Mar  2 00:14:47 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8 MiB
Name: codefresh
ID: WMNW:DC75:4663:BZTY:6B6I:SE2Z:M4SU:YGKB:H3TM:HW3H:N2N5:SQKL
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 181
 Goroutines: 229
 System Time: 2017-03-09T16:22:18.613208789Z
 EventsListeners: 2
Username: roycodefresh
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 $$$$$$$$$$$$$
 $$$$$$$$$$$$$
Live Restore Enabled: false
```

### PR DESCRIPTION
**Pull request by dnephin**
Fixes #31697

Previously labels passed with `--labels` were converted into a quoted string, and then parsed to create `Node` objects.  This PR changes the behaviour to create `Node` objects directly from the `map[string]string`, and avoids the parsing entirely. The parsing was was failing because the value was being quoted with single quotes. 

This PR also includes some refactoring, and additional unit test.
Some single-use functions were moved out of `utils.go` next to their caller.

### CODE REVIEW

**Comment by dnephin** [comment]
ping @tonistiigi since this is about the builder

**Comment by tonistiigi** [comment]
cc @duglin @simonferquel

**Comment by dnephin** [comment]
I had to add single quotes back to the value stored in the node because of #27174.

I'm thinking a better solution might be to add a new field to `parser.Node`, something like 
```
AllowEnvReplacement bool
```
The node would then be the source of truth instead of `builder/dockerfile/evaluator.go:replaceEnvAllowed`.

As it is right now, we still strip off any quotes, so there is still an inconsistency with `docker run` labels, as described in #26027.

File: builder/dockerfile/parser/line_parsers_test.go [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+		Value:    "label",
+		Original: `LABEL "foo"='bar' "weird"='first' second'`,
+		Next: &Node{
+			Value: "foo",
+			Next: &Node{
+				Value: "'bar'",
+				Next: &Node{
+					Value: "weird",
+					Next: &Node{
+						Value: "'first' second'",
```
Comment (duglin) [inline builder/dockerfile/parser/line_parsers_test.go]: you should this is right?  I would have expected `second'` to be part of the 3rd label, not part of the 2nd label's value.

Comment (dnephin) [inline builder/dockerfile/parser/line_parsers_test.go]: There are only two labels, there is no third.

Yes I'm pretty sure it's correct.

Comment (duglin) [inline builder/dockerfile/parser/line_parsers_test.go]:
```
LABEL "foo"='bar' fox'=
```
Will produce 2 labels, not one.  Now, this is a different case than yours because of the trailing "=", but w/o it I get an error about a missing "=". But, that tells me that it treated `fox'` as a 2nd label, not part of the first.

Comment (dnephin) [inline builder/dockerfile/parser/line_parsers_test.go]: The input is not a line in the Dockerfile. The input is `--label foo=bar --label weird="first' second"`. It seems pretty clear to me that this is two labels, not 3.

Comment (duglin) [inline builder/dockerfile/parser/line_parsers_test.go]: ah ok I was thinking this was from a Dockerfile.  Yes, with that quoting its 2.

Comment (duglin) [inline builder/dockerfile/parser/line_parsers_test.go]: This line: https://github.com/docker/docker/pull/31750/files#diff-1a51f742d6a2336ec5db4d69cad57513R47   sure looked like a Dockerfile line to me  :-)

Comment (duglin) [inline builder/dockerfile/parser/line_parsers_test.go]: I guess the issue here is that the "expected" Dockerfile text is misleading, at least to me

Comment (dnephin) [inline builder/dockerfile/parser/line_parsers_test.go]: Ah true, yes it does. All the nodes include the "original" input, but in the case of labels passed as command line flags we have always constructed a fake line, so I preserved that behaviour.

Comment (dnephin) [inline builder/dockerfile/parser/line_parsers_test.go]: Unfortunately I don't think there is any way to construct the line and provide the correct behaviour.

Maybe [this](https://github.com/docker/docker/pull/31750#issuecomment-286545729) would get us closer?

**Comment by dnephin** [comment]
rebased

**Comment by tonistiigi** [comment]
Too bad we have to do so much work for this thing. I'm all for `AllowEnvReplacement` or even just calling the evaluator directly. The other thing we should do is evaluate the AST before execution.

Until then this seems to fix the issue. LGTM

**Comment by dnephin** [comment]
@duglin What do you think? Can we get this merged?

**Review by vdemeester — APPROVED** [review]
LGTM 👼
