### PR TITLE
docker kill: fix bug where failed kills didnt fallback to unix kill

### LINKED ISSUE #41587: docker kill does not execute "direct kill" if initial sigkill fails
**Description**

If killPossiblyDeadProcess within the Kill function fails here: https://github.com/moby/moby/blob/master/daemon/kill.go#L141, then docker waits for 2 seconds, and if the container is not killed then dockerd returns here: https://github.com/moby/moby/blob/master/daemon/kill.go#L160

What docker should do is fall-through to the "killProcessDirectly" function here: https://github.com/moby/moby/blob/master/daemon/kill.go#L165

so if killPossiblyDeadProcess fails, the user should expect to see a log message like "failed to exit within 10 seconds of kill - trying direct SIGKILL" coming from here: https://github.com/moby/moby/blob/7cf6dfcb9e6d0bb135039c73e1e1051e9ea6f2f6/daemon/container_operations_unix.go#L348

Instead, the return at https://github.com/moby/moby/blob/master/daemon/kill.go#L160 prevents killProcessDirectly from being called.

**Steps to reproduce the issue:**
1. add `return fmt.Errorf("foo error")` here: https://github.com/moby/moby/blob/7cf6dfcb9e6d0bb135039c73e1e1051e9ea6f2f6/daemon/kill.go#L181
2. Build a docker container that captures SIGTERM:
```
cat << EOF > Dockerfile
FROM bash:5.0

COPY killtrapper.sh /

ENTRYPOINT ["/killtrapper.sh"]
EOF
```
```
cat << EOF > killtrapper.sh
#!/usr/bin/env bash

sigterm() {
    echo "caught a signal"
}

trap 'sigterm' QUIT
trap 'sigterm' INT
trap 'sigterm' HUP
trap 'sigterm' TERM

echo "test script started. My PID is $$"
while :; do
    sleep 0.5
done
EOF
```
3. build and run the container `chmod +x killtrapper.sh && docker build -t "killtrapper" . && docker run -it --rm --name "kt" killtrapper`
4. attempt to kill the container: `docker kill kt`
5. command fails without trying "direct kill"
```
% docker kill kt
Error response from daemon: Cannot kill container: kt: foo error
```

**Describe the results you expected:**

if initial docker kill signal fails, fall back to "direct kill" (ie unix kill)

**Output of `docker version`:**

```
dockerd engine is current head of master:
Client:
 Version:           19.03.6-ce
 API version:       1.40
 Go version:        go1.13.4
 Git commit:        369ce74
 Built:             Fri May 29 04:01:26 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          dev
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8a4671fb1f
  Built:            Fri Oct 23 04:07:23 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.2
  GitCommit:        ff48f57fc83a8c44cf4ad5d672424a98ba37ded6
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 7
 Server Version: dev
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ff48f57fc83a8c44cf4ad5d672424a98ba37ded6
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683 (expected: de40ad0)
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.14.198-152.320.amzn2.x86_64
 Operating System: Amazon Linux 2
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 30.96GiB
 Name: ip-10-0-0-176.us-west-2.compute.internal
 ID: J7BA:BTKN:ZD5S:FWGT:2A2Y:NKTF:DDAJ:QSNA:UE23:L6S2:W7RG:BXBK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

this test was run on an AWS m5.xlarge instance

### PR DESCRIPTION
**Pull request by sparrc**
1. fixes #41587
2. removes potential infinite Wait and goroutine leak at end of kill
function
3. refactored container state waiting out of container_operations_unix.go  
and into kill.go for consistency

fixes #41587

Signed-off-by: Cam <gh@sparr.email>

**before change**

docker kill would just return error if the first sigkill function failed:
```
% docker kill kt
Error response from daemon: Cannot kill container: kt: foo error
```

**after change**

docker falls back to unix kill and container exits:
```
% docker kill kt
kt
```
docker logs:
```
Oct 24 20:54:08 ip-10-0-0-157.us-west-2.compute.internal dockerd[13955]: time="2020-10-24T20:54:08.239338811Z" level=error msg="Container failed to exit within 10 seconds of kill - trying direct SIGKILL" container=f1df7d8bafba1d39124ff7c1edf32c9e1527e318f4df4332ffbcba537c5fc798 error="context deadline exceeded"
Oct 24 20:54:08 ip-10-0-0-157.us-west-2.compute.internal dockerd[13955]: time="2020-10-24T20:54:08.300068287Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
```

**- Description for the changelog**

fix bug where docker kill would not properly fallback to unix sigkill

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: daemon/kill.go [hunk 1]
```diff
@@ -139,39 +139,33 @@ func (daemon *Daemon) Kill(container *containerpkg.Container) error {
...
-		if status := <-container.Wait(ctx, containerpkg.WaitConditionNotRunning); status.Err() != nil {
-			return err
-		}
 	}
 
 	// 2. Wait for the process to die, in last resort, try to kill the process directly
-	if err := killProcessDirectly(container); err != nil {
-		if isErrNoSuchProcess(err) {
-			return nil
+	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
```
Comment (angelcar) [inline daemon/kill.go:149]: nit: Can we streamline this a bit? I think the following is slightly more readable:

```golang
ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
defer cancel()

status := <-container.Wait(ctx, containerpkg.WaitConditionNotRunning)
if status.Err() == nil {
	return nil
}

logrus.WithError(status.Err()).WithField("container", container.ID).Error("Container failed to exit within 10 seconds of kill - trying direct SIGKILL")

if err := killProcessDirectly(container); err != nil {
	if isErrNoSuchProcess(err) {
		return nil
	}
	return err
}


// wait for container to exit one last time, if it doesn't then kill didnt work, so return error
ctx2, cancel2 := context.WithTimeout(context.Background(), 2*time.Second)
defer cancel2()


if status := <-container.Wait(ctx2, containerpkg.WaitConditionNotRunning); status.Err() != nil {
	return errors.New("tried to kill container, but did not receive an exit event")
}
```

Comment (sparrc) [reply daemon/kill.go:149]: yes i like this better, less if-statement nesting and more readable

Comment (sparrc) [reply daemon/kill.go:148]: pushed this refactor

**Review by angelcar — APPROVED** [review]

**Comment by sparrc** [comment]
appears to be only the s390x integration tests failing again

**Comment by sparrc** [comment]
hello, we are continuing to see this issue in ECS, any chance we could get some eyes on this fix?

**Comment by zuzzas** [comment]
Can an issue describe here manifest if a PID does not exist? We've hit the exact same problem, but there was no PID even present on the system. I can see guarding `if`s, but seems like there is a problem with the logic.

```
Server: Docker Engine - Community
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       2d0083d
  Built:            Thu Jun 27 17:23:02 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Review by samuelkarp — COMMENTED** [review]
I think the code mostly looks good, I'm just not quite clear on one of the changes that was made.

File: daemon/kill.go [hunk 2]
```diff
@@ -139,40 +139,36 @@ func (daemon *Daemon) Kill(container *containerpkg.Container) error {
...
-		// we got is probably valid and so we return it to the caller.
+		// kill failed, check if process is no longer running.
 		if isErrNoSuchProcess(err) {
 			return nil
 		}
+	}
 
-		ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
-		defer cancel()
+	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
```
[the remark this answers is not in the document]
Comment (sparrc) [reply daemon/kill.go:148]: yes you are correct about the goal. The reason that was done was just for consistency. If you look across the functions in kill.go there are 3 other calls to `container.Wait`.

In container_operations_unix.go there are no other calls to `container.Wait`.

It seemed better to keep the waiting functions contained to kill.go just for consistency rather than have a call to `container.Wait` at two different levels on the call stack.

**Comment by mmerkes** [comment]
@sparrc @samuelkarp Along with [this change](https://github.com/moby/moby/pull/41586), would love to see this get merged.

**Comment by sparrc** [comment]
thanks so much @tianon and @cpuguy83 for reviewing and merging https://github.com/moby/moby/pull/41586 !

Could I ask that you please take a look at this PR too while it's fresh? It is highly related and also a situation that we regularly see customers hitting at ECS.

**Comment by sparrc** [comment]
Hello, just wanted to ping to see if this PR could be reviewed, thank you!

File: daemon/container_operations_unix.go [hunk 3]
```diff
@@ -336,38 +334,32 @@ func (daemon *Daemon) cleanupSecretDir(c *container.Container) {
...
+	// In case there were some exceptions(e.g., state of zombie and D)
+	if system.IsProcessAlive(pid) {
+		// Since we can not kill a zombie pid, add zombie check here
+		isZombie, err := system.IsProcessZombie(pid)
+		if err != nil {
+			logrus.WithError(err).WithField("container", container.ID).Warn("Container state is invalid")
+			return err
+		}
+		if isZombie {
+			return errdefs.System(errors.Errorf("container %s PID %d is zombie and can not be killed. Use the --init option when creating containers to run an init inside the container that forwards signals and reaps processes", stringid.TruncateID(container.ID), pid))
```
Comment (cpuguy83) [inline daemon/container_operations_unix.go:362]: side note: I don't think this error is accurate since the container PID would itself only be a zombie if the shim exited early for whatever reason.

**Review by cpuguy83 — COMMENTED** [review]
This looks like it makes the existing intent of the code more robust so that at least looks good.

However it seems like if we are getting to the point where we have to call `killProcessDirectly`, we should instead be calling `task.Delete` in containerd instead which will (should) ensure that certain sticky situations are cleaned up (like a blocked runc-init) and work more correctly for other runtimes.

@kolyshkin, thoughts?

**Comment by sparrc** [comment]
@cpuguy83 would it be possible to consider that question in a follow-up PR? I think it's worth breaking that out into two changes. Reason being that this PR mostly retains the same behavior as before while removing the potential for the `docker kill` function to hang forever.

Changing from a unix `kill -9` to `task.Delete` seems like a larger conceptual change to me that maybe shouldn't be bundled in with this refactor?

**Comment by cpuguy83** [comment]
@sparrc IMO, if we are going to introduce a behavior change here (which has been mostly static for awhile), I'd prefer to do it once.

**Comment by sparrc** [comment]
> This looks like it makes the existing intent of the code more robust so that at least looks good.
> 
> However it seems like if we are getting to the point where we have to call `killProcessDirectly`, we should instead be calling `task.Delete` in containerd instead which will (should) ensure that certain sticky situations are cleaned up (like a blocked runc-init) and work more correctly for other runtimes.
> 
> @kolyshkin, thoughts?

OK, just to clarify what you mean by `task.Delete`, is your suggestion that in kill.go instead of falling back to killProcessDirectly (ie [here](https://github.com/moby/moby/blob/master/daemon/kill.go#L165-L170) on master), we instead call out to [daemon.containerd.DeleteTask()](https://github.com/moby/moby/blob/master/libcontainerd/remote/client.go#L459-L470) ? Or would containerd.Delete() be better? (Im not sure exactly the distinction between these).

If that's the case then I guess we could just delete killProcessDirectly entirely, as it wouldn't be used anywhere anymore.

**Comment by kzys** [comment]
containerd's task deletion is doing some checks and asks clients to stop the task beforehand.

If your container is still running;

```
% sudo ctr image pull docker.io/library/debian:latest
...                             
unpacking linux/amd64 sha256:ba4a437377a0c450ac9bb634c3754a17b1f814ce6fa3157c0dc9eef431b29d1f...
done
% sudo ctr run --rm --tty docker.io/library/debian:latest debian
root@ip-172-31-25-68:/# 
```

Deletion wouldn't work.

```
% sudo ctr t rm debian
ERRO[0000] unable to delete debian                       error="task must be stopped before deletion: running: failed precondition"
ctr: task must be stopped before deletion: running: failed precondition
%
```

Falling back to containerd-level task deletion may introduce more error cases, like what if containerd is unhealthy. Using `task.Kill()` is possible but containerd's health is still a concern.

Since this is a fallback case, sending SIGKILL seems much robust to me.

**Comment by sparrc** [comment]
@cpuguy83 @kolyshkin thoughts?

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by sparrc** [comment]
@tianon could you take a look at this? it is similar in concept to https://github.com/moby/moby/pull/41586 but applies to `docker kill` instead of `docker stop`

**Comment by sparrc** [comment]
very keen to get this merged if anyone from docker has time to take a look, happy to walk through the changes if it would help.

**Review by samuelkarp — APPROVED** [review]
LGTM

**Review by tianon — APPROVED** [review]
LGTM, although I would love (as I've noted in #41587) if we could find a way to reproduce so we can more definitively answer @cpuguy83's questions about whether the fallback block is necessary. :sweat_smile:

**Comment by thaJeztah** [comment]
@tonistiigi interesting error on s390x; https://ci-next.docker.com/public/blue/rest/organizations/jenkins/pipelines/moby/branches/PR-41588/runs/6/nodes/181/log/?start=0

```
[2021-05-20T18:45:51.977Z] + docker build --force-rm --build-arg APT_MIRROR -t docker:593c9f3edde77558d171fd029ef9773426204ef3 .
[2021-05-20T18:45:51.977Z] #1 [internal] load .dockerignore
[2021-05-20T18:45:51.977Z] #1 ERROR: proto: CacheRecords: wiretype end group for non-group
[2021-05-20T18:45:51.977Z] 
[2021-05-20T18:45:51.977Z] #2 [internal] load build definition from Dockerfile
[2021-05-20T18:45:51.977Z] #2 transferring dockerfile: 17.07kB done
[2021-05-20T18:45:51.977Z] #2 DONE 0.0s
[2021-05-20T18:45:51.977Z] ------
[2021-05-20T18:45:51.977Z]  > [internal] load .dockerignore:
[2021-05-20T18:45:51.977Z] ------
[2021-05-20T18:45:51.977Z] failed to solve with frontend dockerfile.v0: failed to build LLB: proto: CacheRecords: wiretype end group for non-group
script returned exit code 1
```

**Comment by sparrc** [comment]
@thaJeztah could that be related to this change or do you think it's a flakey failure?

**Comment by thaJeztah** [comment]
Definitely not related, but hadn't seen that failure before (we were discussing some breaking changes in gRPC recently though, and this felt possibly related)

Let me check CI and restart

File: daemon/container_operations_unix.go [hunk 4]
```diff
@@ -336,38 +334,32 @@ func (daemon *Daemon) cleanupSecretDir(c *container.Container) {
...
-					return err
-				}
-				e := errNoSuchProcess{pid, 9}
-				logrus.Debug(e)
-				return e
-			}
+func killProcessDirectly(container *container.Container) error {
+	pid := container.GetPID()
+	// Ensure that we don't kill ourselves
+	if pid == 0 {
```
Comment (thaJeztah) [inline daemon/container_operations_unix.go:340]: Not for this PR, but we should consider making this

```suggestion
	if pid <= 0 {
```

I recall a situation where `-1` was returned (by containerd?) because it was initialised with `-1`, and killing `-1` does "fun things" 😅

**Review by thaJeztah — APPROVED** [review]
LGTM
