### PR TITLE
pkg/aaparser: support parsing version like "3.0.0-beta1"

### LINKED ISSUE #41517: Parsing AppArmor version fails on Ubuntu 20.10
**Description**

Ubuntu 20.10 uses AppArmor parser that reports the version `3.0.0-beta1`. Output from `apparmor_parser --version`:

```
AppArmor parser version 3.0.0-beta1
Copyright (C) 1999-2008 Novell Inc.
Copyright 2009-2018 Canonical Ltd.
```

This leads to the following error:

```
ERROR: Service '***' failed to build : AppArmor enabled on system but the docker-default profile could not be loaded: strconv.Atoi: parsing "0-beta1": invalid syntax
```

This issue is probably related to this function: https://github.com/moby/moby/blob/8e610b2b55bfd1bfa9436ab110d311f5e8a74dcb/pkg/aaparser/aaparser.go#L49

**Steps to reproduce the issue:**

1. Use Ubuntu 20.10 or a beta version of AppArmor.
2. Build a Docker image.

**Output of `docker version`:**

```
Docker version 19.03.13, build 4484c46d9d
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 41
  Running: 0
  Paused: 0
  Stopped: 41
 Images: 1537
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.8.0-20-generic
 Operating System: Ubuntu Groovy Gorilla (development branch)
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 15.26GiB
 Name: falcon
 ID: YBN5:BSM7:JVWU:374Q:RUU7:WLRE:VGF7:Q4UK:YND4:KBXJ:RPB5:6LTM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Ubuntu 20.10 installed on a physical device.

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Fix #41517

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Comment by thaJeztah** [comment]
@cpuguy83 @tianon ptal

**Comment by mohamedGamalAbuGalala** [comment]
Will this be merged soon?

**Review by tianon — APPROVED** [review]

File: pkg/aaparser/aaparser.go [hunk 1]
```diff
@@ -56,6 +56,9 @@ func parseVersion(output string) (int, error) {
 	words := strings.Split(lines[0], " ")
 	version := words[len(words)-1]
 
+	// trim "-beta1" suffix from version="3.0.0-beta1" if exists
+	version = strings.SplitN(version, "-", 2)[0]
```
Comment (tianon) [inline pkg/aaparser/aaparser.go:60]: @alexmurray this is pretty similar to what you applied in Ubuntu (~ one month ago :sweat_smile:) -- is there a specific reason you'd decided to also trim `~...` in addition to/after `-...`? :pray:

For reference (slash to jog your memory), here's the patch you ended up with:

```patch
Description: Handle apparmor versions like 3.0.0-beta1 appropriately
Author: Alex Murray <alex.murray@canonical.com>
--- a/components/engine/pkg/aaparser/aaparser.go
+++ b/components/engine/pkg/aaparser/aaparser.go
@@ -55,6 +55,8 @@ func parseVersion(output string) (int, e
 	lines := strings.SplitN(output, "\n", 2)
 	words := strings.Split(lines[0], " ")
 	version := words[len(words)-1]
+	version = strings.SplitN(version, "-", 2)[0]
+	version = strings.SplitN(version, "~", 2)[0]
 
 	// split by major minor version
 	v := strings.Split(version, ".")
```

cc @mwhudson

Comment (alexmurray) [reply pkg/aaparser/aaparser.go:60]: The upstream AppArmor maintainer mentioned that sometimes they have used a tilde ~ in the past and so it would be more future proof to include this as well.

Comment (tianon) [reply pkg/aaparser/aaparser.go:60]: Perfect, thank you!  Found a good example in https://gitlab.com/apparmor/apparmor/-/commit/bca67d3d27d219d11ce8c9cc70612bd637f88c10 (and will be sending a follow-up PR to include that other half shortly). :+1: :heart:
