### PR TITLE
Properly identify ingress network created with older swarm

### LINKED ISSUE #33259: Ingress network from older versions is erroneously removed on `docker network prune`
**Description**

Doing `docker network prune` removes the ingress network if it is not currently being used, and it was created on an older version.

**Steps to reproduce the issue:**
<strike>
1. `docker network prune`
2. try to create service that uses ingress network
</strike>

See below: https://github.com/moby/moby/issues/33259#issuecomment-302252274

**Describe the results you received:**

Ingress network is gone

**Describe the results you expected:**

Ingress network should not be deleted.

[I don't know what I expected](http://i0.kym-cdn.com/photos/images/newsfeed/000/617/851/56d.gif)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce-rc1
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 20:55:05 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.05.0-ce-rc1
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 20:55:05 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1197
Server Version: 17.05.0-ce-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1008
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: wymf3aau8jhl8rnbwajou3421
 Is Manager: true
 ClusterID: u77uiync8qrec2zvbnbzf0iv7
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.65.2
 Manager Addresses:
  192.168.65.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.21-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: IJDB:XKO7:BYSL:RIBX:DN3F:VFCX:6BUA:QZA3:WZXA:ALWV:PKDQ:7FC2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 101
 Goroutines: 257
 System Time: 2017-05-17T21:57:04.327922388Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: dperny
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Docker for Mac

### PR DESCRIPTION
**Pull request by aboch**
- otherwise docker network prune will remove it

Fixes #33259

### CODE REVIEW

File: daemon/cluster/convert/network.go [hunk 1]
```diff
@@ -8,6 +8,7 @@ import (
 	types "github.com/docker/docker/api/types/swarm"
 	netconst "github.com/docker/libnetwork/datastore"
 	swarmapi "github.com/docker/swarmkit/api"
+	allocator "github.com/docker/swarmkit/manager/allocator"
```
Comment (aaronlehmann) [inline daemon/cluster/convert/network.go]: Importing the package as `allocator` is redundant.

I'm not sure how I feel about importing `allocator` in the engine. To me, this package is internal to swarmkit. It might be better to copy the function.

Comment (aboch) [inline daemon/cluster/convert/network.go]: Makes sense. I am ok on duplicating the function in here as long as everybody agrees.

Comment (thaJeztah) [inline daemon/cluster/convert/network.go]: Looks pretty straightforward to me https://github.com/moby/moby/blob/8daeeacfc1126eafb2b6d00e2dc6e2f5a6ed78cc/vendor/github.com/docker/swarmkit/manager/allocator/networkallocator/networkallocator.go#L968-L976, so agree on duplicating the function

**Comment by mavenugo** [comment]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM
