### PR TITLE
Align fixed-cidr-v6 with fixed-cidr, use default ULA prefix if no fixed-cidr-v6

### LINKED ISSUE #47990: Use default ULA prefix if fixed-cidr-v6 is not specified
### Description

Custom bridge networks no longer need an IPv6 `--subnet` or entry in `default-address-pools`, if neither are specified the daemon will use a ULA prefix - https://github.com/moby/moby/pull/47853.

But, the default bridge still requires `fixed-cidr-v6`.

To make the default bridge less unusual - when `ipv6` is set and `fixed-cidr-v6` isn't, the default bridge should follow the same rules as a custom bridge.

### PR DESCRIPTION
**Pull request by robmry**
**- What I did**

- Allow an IPv6 default bridge with no `fixed-cidr-v6`.
  - Like a default bridge without `fixed-cidr`, it uses default pools (or the daemon's default ULA prefix).
  - Fixes https://github.com/moby/moby/issues/47990
- Fix bugs in `fixed-cidr`'s implementation.
- Aligned the behaviour of `fixed-cidr-v6` with `fixed-cidr`.
- Added daemon option `--bip6` (to set the default bridge's address and subnet, like `--bip`).

**- How I did it**

The existing code's intent was a bit opaque, but seemed to be: 
- Take `--bip` (if supplied for a docker-managed bridge, `docker0`), else an existing bridge address:
  - Use it to determine the `Gateway` address (the bridge's address), and the `PreferredPool` (the docker network's subnet).
- If `fixed-cidr` is provided:
  - Use it as `PreferredPool`, if it hasn't been determined from `--bip` or an existing bridge address.
  - Use it as `SubPool` (equivalent to `--ip-range` for a user-defined network, it's the range of addresses the IPAM driver can allocate from. (`SubPool` is expected to be within `PreferredPool`, but that's not enforced.)

So ...
- Added tests to capture the current behaviour of `fixed-cidr`.
  - Highlighted problems using `FIXME` comments in the tests ... mostly confusion between daemon-managed (`docker0`), and user-managed (`--bridge`) bridges, leading to surprising and incorrect behaviour.
- Incrementally fixed the issues.
  - Refactoring so that the logic that resolves `fixed-cidr`/`bip`/existing bridge addresses into an `IPAMConf` can be used  for `fixed-cidr-v6`.
  - Accepted inconsistent config where it would have done something useful before, rather failing to start the daemon. Log problems, and try to handle things approximately as they would have been before (but with consistent IPAM config where before, for example, the requested range for address allocation could end up outside the subnet).
- Added daemon option `--bip6` because it's the only way to be sure `docker0`'s address and subnet size are updated (similar to existing `-bip` for IPv4 addresses).
- Removed the requirement for a `fixed-cidr-v6` when IPv6 is enabled.
- Used the refactored logic for IPv6, including `fixed-cidr-v6`.

**_Example of confusion between daemon/user-managed default bridge network configuration:_**

- Start dockerd, get a default bridge with a subnet from `default-address-pool`, for example `172.18.0.0/16`.
- Restart dockerd, with `fixed-cidr: "10.0.0.0/24"`.
- `network inspect` says ...
```
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "IPRange": "10.0.0.0/24",
                    "Gateway": "172.18.0.1"
                }
            ]
        },
```
- **Note:**
  - The subnet hasn't changed.
  - IPRange (addresses that can be allocated from the subnet) is outside the subnet.
- The problem here is `docker0` being treated like a user-managed bridge - the bridge's existing address takes priority, even though there's no configuration saying it can't change.
- It skips IPAM validation because it doesn't go via createNetwork ... and (surprisingly, to me) it still allocates container addresses from 172.18.0.0/16 because the IPRange is only used to calculate an offset into Subnet.
- So, the default bridge network still worked (as long as IPRange's subnet size doesn't cause allocations outside Subnet), and the only real problem is that it's not possible to change fixed-cidr without deleting config.

_**Issues with existing implementation:**_

- Can't change `docker0`'s `fixed-cidr` without specifying `--bip` (the issue described in the example above).
    - Fixed by ignoring the existing address if its subnet does not overlap `fixed-cidr`, or by expanding the bridge's subnet if `fixed-cidr` encompasses the existing subnet.
  - `TestDaemonDefaultBridgeIPAM_Docker0/old_bridge_subnet_within_fixed-cidr`
  - `TestDaemonDefaultBridgeIPAM_Docker0/old_bridge_subnet_outside_fixed-cidr`
- For `docker0`, when there's no --bip to dictate the subnet, it's derived from an existing bridge address. If fixed-cidr's subnet is made smaller following a daemon restart, a user might reasonably expect the default bridge network's subnet to shrink to match. However, that has not been the behaviour - instead, only the allocatable range is reduced (as would happen with a user-managed bridge).
  -  In this case, if the user wants a smaller subnet, options are to delete `docker0`, or supply a `--bip`.
  - A change in this subtle behaviour might be best. But, it's probably not causing problems, and it'd be a breaking change if anyone is relying on it.
  - `TestDaemonDefaultBridgeIPAM_Docker0/fixed-cidr_within_old_bridge_subnet`
  - (And `TestDaemonDefaultBridgeIPAM_Docker0/fixed-cidr_within_old_bridge_subnet_with_bip` to show that `--bip` sorts things out.)
- For a user-managed bridge, selection of the existing bridge address to infer the subnet from depended on the address falling within `fixed-cidr`. But, that's just the allocatable range.
  - Fixed by picking an address with a subnet that encompasses `fixed-cidr`, even if the address itself isn't within `fixed-cidr`.
  - But also keep the existing behaviour that allowed `fixed-cidr`, the allocatable address range, to be bigger than the subnet inferred from the bridge's addresss (then fix that, as described below).
  - Test `TestDaemonDefaultBridgeIPAM_UserBr/fcidr_in_bridge_subnet_and_bridge_ip_not_in_fcidr`.
- For a user-managed bridge, if `fixed-cidr` did not overlap with the subnet belonging to any address on the bridge, or was bigger than a bridge address's subnet (the user-managed bridge version of the `docker0` example above) - any address was selected from the bridge, and the allocatable range would just be wrong.
  - Fixed by logging a warning and ignoring `fixed-cidr`, making the whole subnet inferred from the bridge address allocatable. (Before, because the allocator's implementation treats the sub-pool as an offset into the pool rather than an actual address range, this could result in an allocatable range within or bigger than the pool - so, this is a change in behaviour, but the configuration is broken ... I don't think it's worth trying to preserve the range that would have happened-to-work.)
  - `TestDaemonDefaultBridgeIPAM_UserBr/fixed-cidr_bigger_than_bridge_subnet`
  - `TestDaemonDefaultBridgeIPAM_UserBr/no_bridge_ip_within_fixed-cidr`
  - `TestDaemonDefaultBridgeIPAM_UserBr/fixed-cidr_contains_bridge_subnet`
- Code that cleared the top bits of an IP address, then checked `IsGlobalUnicast()`.
  - The intention may have been to only accept a globally routable address as the gateway address on a user-managed default bridge. But, it didn't - so, removed.
- IPAMConfig was unnecessarily set up for IPv6 if `fixed-cidr-v6` was supplied with IPv6 was disabled.
- IPv6 IPAMConfig ignored the prefix length of an existing bridge address, and just used `fixed-cidr-v6`'s prefix length.
  - It's IPv6, so that prefix is only informational. But, it's the only information there is! There was no way to make the allocatable ip-range smaller than the subnet.
  - Fixed by adding `--bip6` to make it explicitly configurable.
  - (This is a change in behaviour, a change in `fixed-cidr-v6` now behaves like a change in `fixed-cidr` rather than just being an override. But, that's important for a user-managed bridge, and overridable with `--bip6` for `docker0`).

**- How to verify it**

New integration tests...
```
Running /go/src/github.com/docker/docker/integration/daemon (arm64.integration.daemon) flags=-test.v -test.timeout=10m -test.run TestDaemonDefaultBridgeIPAM
INFO: Testing against a local daemon
=== RUN   TestDaemonDefaultBridgeIPAM_Docker0
=== RUN   TestDaemonDefaultBridgeIPAM_Docker0/no_config
=== RUN   TestDaemonDefaultBridgeIPAM_Docker0/fixed-cidr_only
=== RUN   TestDaemonDefaultBridgeIPAM_Docker0/bip_only
=== RUN   TestDaemonDefaultBridgeIPAM_Docker0/existing_bridge_address_only
=== RUN   TestDaemonDefaultBridgeIPAM_Docker0/fixed-cidr_within_old_bridge_subnet
=== RUN   TestDaemonDefaultBridgeIPAM_Docker0/fixed-cidr_within_old_bridge_subnet_with_new_bip
=== RUN   TestDaemonDefaultBridgeIPAM_Docker0/old_bridge_subnet_within_fixed-cidr
=== RUN   TestDaemonDefaultBridgeIPAM_Docker0/old_bridge_subnet_outside_fixed-cidr
=== RUN   TestDaemonDefaultBridgeIPAM_Docker0/old_bridge_subnet_outside_fixed-cidr_with_bip
--- PASS: TestDaemonDefaultBridgeIPAM_Docker0 (5.71s)
    --- PASS: TestDaemonDefaultBridgeIPAM_Docker0/no_config (0.63s)
    --- PASS: TestDaemonDefaultBridgeIPAM_Docker0/fixed-cidr_only (0.63s)
    --- PASS: TestDaemonDefaultBridgeIPAM_Docker0/bip_only (0.63s)
    --- PASS: TestDaemonDefaultBridgeIPAM_Docker0/existing_bridge_address_only (0.64s)
    --- PASS: TestDaemonDefaultBridgeIPAM_Docker0/fixed-cidr_within_old_bridge_subnet (0.63s)
    --- PASS: TestDaemonDefaultBridgeIPAM_Docker0/fixed-cidr_within_old_bridge_subnet_with_new_bip (0.67s)
    --- PASS: TestDaemonDefaultBridgeIPAM_Docker0/old_bridge_subnet_within_fixed-cidr (0.61s)
    --- PASS: TestDaemonDefaultBridgeIPAM_Docker0/old_bridge_subnet_outside_fixed-cidr (0.64s)
    --- PASS: TestDaemonDefaultBridgeIPAM_Docker0/old_bridge_subnet_outside_fixed-cidr_with_bip (0.63s)
=== RUN   TestDaemonDefaultBridgeIPAM_UserBr
=== RUN   TestDaemonDefaultBridgeIPAM_UserBr/bridge_only
=== RUN   TestDaemonDefaultBridgeIPAM_UserBr/fixed-cidr_only
=== RUN   TestDaemonDefaultBridgeIPAM_UserBr/fcidr_in_bridge_subnet_and_bridge_ip_in_fcidr
=== RUN   TestDaemonDefaultBridgeIPAM_UserBr/fcidr_in_bridge_subnet_and_bridge_ip_not_in_fcidr
=== RUN   TestDaemonDefaultBridgeIPAM_UserBr/fixed-cidr_bigger_than_bridge_subnet
=== RUN   TestDaemonDefaultBridgeIPAM_UserBr/no_bridge_ip_within_fixed-cidr
=== RUN   TestDaemonDefaultBridgeIPAM_UserBr/fixed-cidr_contains_bridge_subnet
--- PASS: TestDaemonDefaultBridgeIPAM_UserBr (4.44s)
    --- PASS: TestDaemonDefaultBridgeIPAM_UserBr/bridge_only (0.63s)
    --- PASS: TestDaemonDefaultBridgeIPAM_UserBr/fixed-cidr_only (0.63s)
    --- PASS: TestDaemonDefaultBridgeIPAM_UserBr/fcidr_in_bridge_subnet_and_bridge_ip_in_fcidr (0.63s)
    --- PASS: TestDaemonDefaultBridgeIPAM_UserBr/fcidr_in_bridge_subnet_and_bridge_ip_not_in_fcidr (0.63s)
    --- PASS: TestDaemonDefaultBridgeIPAM_UserBr/fixed-cidr_bigger_than_bridge_subnet (0.64s)
    --- PASS: TestDaemonDefaultBridgeIPAM_UserBr/no_bridge_ip_within_fixed-cidr (0.65s)
    --- PASS: TestDaemonDefaultBridgeIPAM_UserBr/fixed-cidr_contains_bridge_subnet (0.63s)
PASS

DONE 18 tests in 10.201s
```

**- Description for the changelog**
```markdown changelog
- Daemon option `--ipv6` (`"ipv6": true` in `daemon.json`) can now be used without
  `fixed-cidr-v6`. A subnet will be allocated `default-address-pools` or the daemon's
  ULA prefix.
- Added daemon option `--bip6=<cidr>` (`"bip6": "<cidr>") to specify the default
  bridge's IPv6 address and subnet, similar to `--bip` for IPv4.
- Resolved issues related to changing `fixed-cidr` for `docker0`, and inferring
   configuration from a user-managed default bridge (`--bridge).
- Aligned the behavior of `fixed-cidr-v6` with `fixed-cidr`.
```

### CODE REVIEW

File: daemon/daemon_unix.go [hunk 1]
```diff
@@ -1082,20 +1055,30 @@ func getDefaultBridgeIPAMConf(
...
 ) ([]*libnetwork.IpamConf, error) {
+	// Select v4/v6 config based on family
+	fixedCIDR, fixedCIDROpt := cfg.FixedCIDR, "fixed-cidr"
+	cfgBIP, cfgBIPOpt := cfg.IP, "bip"
+	cfgDefGw, cfgDefGwOpt := cfg.DefaultGatewayIPv4, "DefaultGatewayIPv4"
+	if family == netlink.FAMILY_V6 {
+		fixedCIDR, fixedCIDROpt = cfg.FixedCIDRv6, "fixed-cidr-v6"
+		cfgBIP, cfgBIPOpt = cfg.IP6, "bip6"
+		cfgDefGw, cfgDefGwOpt = cfg.DefaultGatewayIPv6, "DefaultGatewayIPv6"
+	}
```
Comment (akerouanton) [inline daemon/daemon_unix.go:1066]: Why not parse these outside of this function and pass them as arguments? I'm not a big fan of these `*Opt` vars.

File: daemon/daemon_unix.go [hunk 2]
```diff
@@ -940,65 +943,35 @@ func initBridgeDriver(controller *libnetwork.Controller, cfg config.BridgeConfig
...
+				return err
 			}
+			// In case user has specified the daemon flag --fixed-cidr-v6 and the passed network has
+			// at least 48 host bits, we need to guarantee the current behavior where the containers'
+			// IPv6 addresses will be constructed based on the containers' interface MAC address.
+			// We do so by telling libnetwork to defer the IPv6 address allocation for the endpoints
+			// on this network until after the driver has created the endpoint and returned the
+			// constructed address. Libnetwork will then reserve this address with the ipam driver.
+			ones, _ := fCIDRv6.Mask.Size()
+			deferIPv6Alloc = ones <= 80
```
Comment (akerouanton) [inline daemon/daemon_unix.go:965]: I think it should also apply when there's no more `--fixed-cidr-v6` / `--bip` option but the bridge already exists and has a subnet assigned.

Also, before that change there was no `--bip6`, but it should now be taken into account.

You can probably solve both issues by using `ipamV6Conf.PreferredPool`.

File: daemon/daemon_unix.go [hunk 3]
```diff
@@ -963,10 +963,7 @@ func initBridgeDriver(controller *libnetwork.Controller, cfg config.BridgeConfig
 		}
 
 		ipamV4Conf.PreferredPool = lntypes.GetIPNetCanonical(nw).String()
-		hip, _ := lntypes.GetHostPartIP(nw.IP, nw.Mask)
-		if hip.IsGlobalUnicast() {
-			ipamV4Conf.Gateway = nw.IP.String()
-		}
+		ipamV4Conf.Gateway = nw.IP.String()
```
[the remark this answers is not in the document]
Comment (robmry) [reply daemon/daemon_unix.go]: I don't think it'd be too meaningful - LL addresses have been allowed by the broken check, so they're supported now.

File: daemon/daemon_unix.go [hunk 4]
```diff
@@ -991,6 +991,23 @@ func initBridgeDriver(controller *libnetwork.Controller, cfg config.BridgeConfig
...
+			fCidrOnes, _ := fCidrIPNet.Mask.Size()
+			bIPOnes, _ := bIPNet.Mask.Size()
+			if !bIPNet.Contains(fCidrIP) || (fCidrOnes < bIPOnes) {
+				// Don't allow SubPool (the range of allocatable addresses) to be outside, or
+				// bigger than, the network itself. This is a configuration error, either the
+				// user-managed bridge is missing an address to match fixed-cidr, or fixed-cidr
+				// is wrong. But, just log rather than raise an error that would cause daemon
+				// startup to fail, because this has been allowed by earlier versions. Remove
+				// the SubPool, so that addresses are allocated from the whole of PreferredPool.
+				log.G(context.TODO()).WithFields(log.Fields{
```
[the remark this answers is not in the document]
Comment (robmry) [reply daemon/daemon_unix.go:1165]: It's a pity not to have the same behaviour for both again, but I've made it an error for IPv6 and split the testcases.

File: daemon/daemon_unix.go (hunk 1 above)
Comment (robmry) [reply daemon/daemon_unix.go]: I've tarted it up a bit ... any better?

File: daemon/daemon_unix.go (hunk 2 above)
Comment (robmry) [reply daemon/daemon_unix.go:1009]: Done, and added tests.

File: daemon/daemon_unix.go (hunk 1 above)
Comment (akerouanton) [reply daemon/daemon_unix.go]: Not sure we get it any better without touching how daemon settings are organized.

**Review by akerouanton — APPROVED** [review]

**Comment by robmry** [comment]
Rebased to resolve conflicts.

**Comment by robmry** [comment]
Added `--bip6` to `man/docker.8.md` in the final commit.

File: daemon/daemon_unix.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (thaJeztah) [reply daemon/daemon_unix.go:1169]: Is this something we should consider "deprecating" (incorrect config); possibly warn, and in future error?

File: daemon/daemon_unix.go [hunk 5]
```diff
@@ -925,6 +928,47 @@ func driverOptions(config *config.Config) nwconfig.Option {
...
+	return netlink.FAMILY_V4
+}
+func (o defBrOptsV4) fixedCIDR() (fCIDR, optName string) {
+	return o.cfg.FixedCIDR, "fixed-cidr"
+}
+func (o defBrOptsV4) bip() (bip, optName string) {
+	return o.cfg.IP, "bip"
+}
+func (o defBrOptsV4) defGw() (gw net.IP, optName string) {
+	return o.cfg.DefaultGatewayIPv4, "DefaultGatewayIPv4"
```
Comment (thaJeztah) [inline daemon/daemon_unix.go:945]: Is `DefaultGatewayIPV4` the name that will be used in the `daemon.json` ? I noticed that all other options we use hyphenated names, e.g. https://github.com/moby/moby/blob/48e43eb8601e5edaec3b4b88926413ef786e2913/daemon/config/config_linux.go#L62-L63


Also curious if it would make sense to make these options in the `internal/opts` package (but haven't looked too closely)

File: daemon/daemon_unix.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (robmry) [reply daemon/daemon_unix.go]: I don't think so ... there's not really anything special about allowing link-local addresses.

Maybe, although I'm not sure, the original idea was to disallow them. But, that would have been the special case that needed explaining.

File: daemon/daemon_unix.go [hunk 6]
```diff
@@ -952,18 +952,26 @@ func initBridgeDriver(controller *libnetwork.Controller, cfg config.BridgeConfig
 	}
 
 	if len(nwList) > 0 {
+		// Pick any address from the bridge as a starting point.
 		nw := nwList[0]
 		if len(nwList) > 1 && cfg.FixedCIDR != "" {
-			_, fCIDR, err := net.ParseCIDR(cfg.FixedCIDR)
+			fCidrIP, fCidrNet, err := net.ParseCIDR(cfg.FixedCIDR)
```
[the remark this answers is not in the document]
Comment (robmry) [reply daemon/daemon_unix.go]: `defBrOptsv4` is introduced and used in the commit after this one, and the option name is included in the error message. (But I'll update the error for failing to parse `--bip`/`--bip6` to include the option name.)

File: daemon/daemon_unix.go [hunk 7]
```diff
@@ -925,147 +928,317 @@ func driverOptions(config *config.Config) nwconfig.Option {
...
-		v6Conf = append(v6Conf, ipamV6Conf)
-	}
-	// Initialize default network on "bridge" with the same name
-	_, err = controller.NewNetwork("bridge", network.NetworkBridge, "",
-		libnetwork.NetworkOptionEnableIPv4(true),
-		libnetwork.NetworkOptionEnableIPv6(cfg.EnableIPv6),
-		libnetwork.NetworkOptionDriverOpts(netOption),
-		libnetwork.NetworkOptionIpam("default", "", v4Conf, v6Conf, nil),
-		libnetwork.NetworkOptionDeferIPv6Alloc(deferIPv6Alloc))
+	return []*libnetwork.IpamConf{ipamConf}, nil
```
Comment (thaJeztah) [inline daemon/daemon_unix.go:1170]: Probably fine to look for a future change, but my eye dropped on the `[]*libnetwork.IpamConf{}` as type used; 

- it made me curious why we use a slice with pointers (as a slice already is implicitly a pointer); also see https://andrii-kushch.medium.com/go-what-to-return-a-slice-of-structs-vs-a-slice-of-pointers-42647912530a
- This function always returns a single ipamConf, so I was curious why we convert it to a slice
- ☝️ but it looks like we use `[]*libnetwork.IpamConf{}` in many places, so this was _probably_ out of convenience
- 👉 probably something to look at in a follow-up.

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Comment by robmry** [comment]
Rebased - the conflict was just in `imports` in `bridge_linux_test.go` ... I'll let the tests run in case anything else shows up, as it was a fair way behind master.
