### PR TITLE
Dockerd rootless: make {/etc,/var/run}/cdi available

### LINKED ISSUE #47676: Default Nvidia CDI spec location on rootless kit seems to be unaccessible
### Description

I originally opened an issue on the [Nvidia-container-toolkit](https://github.com/NVIDIA/nvidia-container-toolkit) repo, but we figured the issue may actually be better placed here.

Original issue: https://github.com/NVIDIA/nvidia-container-toolkit/issues/434 @elezar 

**The Issue**
Testing rootless docker 26.0.0 with nvidia container toolkit and Nvidia CDI support, the CDI injection fails, presumably because docker cannot find the `nvidia.yaml`.
```
docker run --rm -ti --device=nvidia.com/gpu=all ubuntu nvidia-smi -L
docker: Error response from daemon: CDI device injection failed: unresolvable CDI devices nvidia.com/gpu=all.
```
The client is looking at
```
 CDI spec directories:
  /etc/cdi
  /var/run/cdi
```
by default, but unlike the rootful version, rootless is unable to access the specs.

We tested this by moving the specs to another directory and specified the new location in the docker daemon.json:
```
{
    "features": {
        "cdi": true
    },
    "cdi-spec-dirs": ["/home/username/.docker/cdi/", "/home/username/.docker/run/cdi/"],
    "runtimes": {
        "nvidia": {
            "args": [],
            "path": "nvidia-container-runtime"
        }
    }
}
```

```
CDI spec directories:
  /home/username/.docker/cdi/
  /home/username/.docker/run/cdi/
```

Which seems to have solved the issue.

### Reproduce

1. Install docker rootless 26.0.0 via [install script](https://github.com/docker/docker-install/blob/master/rootless-install.sh)
2. install the nvidia-container toolkit according to the documentation
3. run `nvidia-ctk runtime configure --runtime=docker --cdi.enabled --config=$HOME/.config/docker/daemon.json` to enable cdi mode on rootless
4. check `CDI spec directories` location via `docker info`
5. run a container with native CDI injection `docker run --rm -ti --device=nvidia.com/gpu=all ubuntu nvidia-smi -L`  

### Expected behavior

We expected the rootless client to be able to run native CDI injections by accessing the nvidia.yaml default location, or give an indication, that the default location is inaccessible to rootless:
```
/.config/docker$ docker run --rm -ti --device=nvidia.com/gpu=all ubuntu nvidia-smi -L
GPU 0: NVIDIA A100-SXM4-40GB (UUID: GPU-b6022b4d-71db-8f15-15de-26a719f6b3e1)
GPU 1: NVIDIA A100-SXM4-40GB (UUID: GPU-22420f7d-6edb-e44a-c322-4ce539cade19)
GPU 2: NVIDIA A100-SXM4-40GB (UUID: GPU-5e3444e2-8577-0e99-c6ee-72f6eb2bd28c)
GPU 3: NVIDIA A100-SXM4-40GB (UUID: GPU-dd1f811d-a280-7e2e-bf7e-b84f7a977cc1)
``` 

### docker version

```bash
Client:
 Version:           26.0.0
 API version:       1.45
 Go version:        go1.21.8
 Git commit:        2ae903e
 Built:             Wed Mar 20 15:16:45 2024
 OS/Arch:           linux/amd64
 Context:           rootless

Server: Docker Engine - Community
 Engine:
  Version:          26.0.0
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.8
  Git commit:       8b79278
  Built:            Wed Mar 20 15:18:14 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.13
  GitCommit:        7c3aca7a610df76212171d200ca3811ff6096eb8
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
 rootlesskit:
  Version:          2.0.2
  ApiVersion:       1.1.1
  NetworkDriver:    vpnkit
  PortDriver:       builtin
  StateDir:         /run/user/1010/dockerd-rootless
 vpnkit:
  Version:          7f0eff0dd99b576c5474de53b4454a157c642834
```

### docker info

```bash
Client:
 Version:    26.0.0
 Context:    rootless
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.13.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.5.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 5
  Running: 0
  Paused: 0
  Stopped: 5
 Images: 3
 Server Version: 26.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: false
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 CDI spec directories:
  /home/ver23371/.docker/cdi/
  /home/ver23371/.docker/run/cdi/
 Swarm: inactive
 Runtimes: nvidia runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7c3aca7a610df76212171d200ca3811ff6096eb8
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  rootless
  cgroupns
 Kernel Version: 5.15.0-1047-nvidia
 Operating System: Ubuntu 22.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 128
 Total Memory: 503.5GiB
 Name: DGX-Station-A100-920-23487-2530-0R0
 ID: 48ae789a-3d2d-43d8-841a-9a34c9bdc46e
 Docker Root Dir: /home/ver23371/.local/share/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpu shares support
WARNING: No cpuset support
WARNING: No io.weight support
WARNING: No io.weight (per device) support
WARNING: No io.max (rbps) support
WARNING: No io.max (wbps) support
WARNING: No io.max (riops) support
WARNING: No io.max (wiops) support
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by ereslibre**
When dockerd is executed with the `dockerd-rootless.sh` script, make /etc/cdi and /var/run/cdi available to the daemon if they exist.

This makes it possible to enable the CDI integration in rootless mode.

Fixes: #47676

Signed-off-by: Rafael Fernández López <ereslibre@ereslibre.es>

**- What I did**

When Dockerd is executed in rootless mode, the Container Device Interface won't be able to find the CDI specs at `/etc/cdi` nor `/var/run/cdi`.

The implementation of the CDI code can be found at https://github.com/cncf-tags/container-device-interface. I am focusing on the latest tagged version (v0.8.0).

This implementation uses `filepath.Walk` (https://pkg.go.dev/path/filepath@go1.23.1#Walk), which documents not following symlinks.

**- How I did it**

I modified the `contrib/dockerd-rootless.sh` script so that the contents of `/etc/cdi` and `/var/run/cdi` are made available to the Dockerd daemon, which in turn uses the CDI code to load and interpret the CDI specs, allowing us to do something like the following:

```
❯ DOCKER_HOST=unix:///run/user/1000/docker.sock docker run --rm --device=nvidia.com/gpu=all -it ubuntu:latest nvidia-smi -L
GPU 0: NVIDIA GeForce RTX 4090 (UUID: GPU-c475e08b-0cc5-f5aa-4326-99699429b449)
GPU 1: NVIDIA GeForce RTX 2080 SUPER (UUID: GPU-5cca1a6f-7cee-b649-40f0-2d3ecb0aa207)
```

**- How to verify it**

Note that you will need a valid `/etc/cdi` or `/var/run/cdi` definition of some hardware that follows the CDI specification, so that the Docker daemon can load it and make it available to you.

You can use the following script if you have nix installed:

```bash
#!/usr/bin/env -S nix shell github:ereslibre/nixities#rootlesskit github:ereslibre/nixities#slirp4netns github:ereslibre/nixities#containerd github:ereslibre/nixities#runc github:ereslibre/nixities#bash -c bash
TMPFILE=$(mktemp '/tmp/dockerd.XXXXXXXXXXXX') || exit 1
cat <<EOF > $TMPFILE
{
  "cdi-spec-dirs": [
    "/etc/cdi/",
    "/var/run/cdi/"
  ],
  "features": {
    "cdi": true
  },
  "userland-proxy": false,
  "rootless": true
}
EOF
DOCKERD=<PATH_TO_MOBY>/moby/moby/bundles/binary/dockerd <PATH_TO_MOBY>/moby/moby/contrib/dockerd-rootless.sh --config-file=$TMPFILE
```

**- Description for the changelog**

```markdown changelog
Dockerd rootless mode loads /etc/cdi and /var/run/cdi as expected by the Container Device Interface (CDI) integration.
```

**- A picture of a cute animal (not mandatory but encouraged)**

A cute Vicuña. This is NixOS 24.11 release codename :)

### CODE REVIEW

**Comment by ereslibre** [comment]
cc/ @elezar (due to https://github.com/moby/moby/issues/47676)

File: contrib/dockerd-rootless.sh [hunk 1]
```diff
@@ -139,6 +149,12 @@ if [ -z "$_DOCKERD_ROOTLESS_CHILD" ]; then
 		"$0" "$@"
 else
 	[ "$_DOCKERD_ROOTLESS_CHILD" = 1 ]
+
+	# Container Device Interface (CDI) specs can be found under {/etc,/var/run}/cdi.
+	# More information at: https://github.com/cncf-tags/container-device-interface
+	[ -d "/etc/cdi" ] && mount_directory /etc/cdi
```
Comment (elezar) [inline contrib/dockerd-rootless.sh:155]: Question: is this run once at startup, or once per container? I would expect NEW specs added to these folders to be accessible to containers without requiring a restart of the rootless daemon.

Comment (ereslibre) [reply contrib/dockerd-rootless.sh:155]: This is executed once when the Dockerd daemon is started. However, the Dockerd daemon will be watching the default CDI locations, so that if new specs are added either to `/etc/cdi` or `/var/run/cdi`, they will be available to the daemon without the need to restart it.

Just for the sake of an example, I just checked it by copying my `/var/run/cdi/nvidia-container-toolkit.json` to `/etc/cdi` modifying the `kind` to `somevendor.com/tpu`. Without any daemon restart, I can do:

```
❯ DOCKER_HOST=unix:///run/user/1000/docker.sock docker run --rm --device=somevendor.com/tpu=all -it ubuntu:latest nvidia-smi -L
GPU 0: NVIDIA GeForce RTX 4090 (UUID: GPU-c475e08b-0cc5-f5aa-4326-99699429b449)
GPU 1: NVIDIA GeForce RTX 2080 SUPER (UUID: GPU-5cca1a6f-7cee-b649-40f0-2d3ecb0aa207)
```

Comment (elezar) [reply contrib/dockerd-rootless.sh:155]: Sorry, I should have been clearer. What is the expectation if the folders *do not exist* when the rootless daemon is started (we explicitly have a `-d` conditional guard)? In the case of the rootfull daemon, I believe the underlying CDI code will detect the creation of the configured directories and refresh the internal CDI cache based on the contents added.

We should at least document that for the CDI injection to work as expected, the `/etc/cdi` and / or `/var/run/cdi` folders needs to exist when the rootless daemon is started.

Comment (elezar) [reply contrib/dockerd-rootless.sh:155]: Another question: The CDI spec directories are configurable. Should we adjust the behaviour of the rootless daemon based on that config or is it ok to always assume the defaults?

Comment (ereslibre) [reply contrib/dockerd-rootless.sh:162]: Good points @elezar. Thanks!

> What is the expectation if the folders do not exist when the rootless daemon is started (we explicitly have a -d conditional guard)? 

Yes, in this case, they won't be included and creating files under them will have no effect without a restart of the daemon.

> We should at least document that for the CDI injection to work as expected, the /etc/cdi and / or /var/run/cdi folders needs to exist when the rootless daemon is started.

I have updated the script with a explicit mention to this behavior as a comment. Please, let me know if you were thinking in other kind of documentation, more public. I'd be happy to include that too.

> Another question: The CDI spec directories are configurable. Should we adjust the behaviour of the rootless daemon based on that config or is it ok to always assume the defaults?

I think it's better to keep it simple. Using the config would mean including `jq` as another dependency and also making sure we are processing the right JSON. Adding something middle ground such a new envvar would give a wrong signal to the user (do I need to provide the envvar AND the cdi-spec-dirs in the config? what happens if they don't match?). For these reasons, I think it's better to keep it simple for now, until we have some feedback at least that signals otherwise.

File: contrib/dockerd-rootless.sh [hunk 2]
```diff
@@ -54,6 +54,16 @@ if ! [ -d "$HOME" ]; then
 	exit 1
 fi
 
+mount_directory() {
+	local directory="$1"
+	local mount_options="${2:---bind}"
+
+	directory_realpath=$(realpath "$directory")
+	rm -rf "$directory"
```
Comment (AkihiroSuda) [inline contrib/dockerd-rootless.sh:62]: It should be validated that `$directory` is inside the `copy-up` list?

File: contrib/dockerd-rootless.sh [hunk 3]
```diff
@@ -139,6 +149,25 @@ if [ -z "$_DOCKERD_ROOTLESS_CHILD" ]; then
...
+	# order for it to read the CDI specification files. Otherwise, a
+	# Docker daemon restart will be required for the daemon to discover
+	# them.
+	#
+	# If another set of CDI paths (other than the default /etc/cdi and
+	# /var/run/cdi) are configured through the Docker configuration file
+	# (using "cdi-spec-dirs"), they need to be bind mounted in rootless
+	# mode; otherwise the Docker daemon won't have access to the CDI
+	# specification files.
+	[ -d "/etc/cdi" ] && mount_directory /etc/cdi
```
Comment (AkihiroSuda) [inline contrib/dockerd-rootless.sh:168]: Does `-d` really work with `copy-up`?
It is usually a symlink

Comment (ereslibre) [reply contrib/dockerd-rootless.sh:168]: We are not `copy-upping` these directories. They will be read-only by dockerd. Do we still need to do a `copy-up`?

It is working for me as it is, but let me know if I'm missing anything.

File: contrib/dockerd-rootless.sh (hunk 2 above)
Comment (ereslibre) [reply contrib/dockerd-rootless.sh:62]: Commented on https://github.com/moby/moby/pull/48541#pullrequestreview-2341840519, we are not doing a `copy-up` as far as I understand. I extracted this logic to do a mount bind, but not necessarily a `copy-up` (well, `/etc` will be, but that's not a change introduced by this PR).

Please, let me know if I'm missing anything!

File: contrib/dockerd-rootless.sh (hunk 3 above)
Comment (AkihiroSuda) [reply contrib/dockerd-rootless.sh:168]: `/etc` is copied-up so `/etc/cdi` usually becomes a symlink.

I assumed `[ -d ]` could fail for a symlink to a dir, but TIL I was wrong.


> TEST(1)
> [...]
> Except  for -h and -L, all FILE-related tests dereference symbolic links.

File: contrib/dockerd-rootless.sh (hunk 2 above)
Comment (AkihiroSuda) [reply contrib/dockerd-rootless.sh:62]: `/etc` is copied up: https://github.com/moby/moby/blob/4001d0704ba38a82e1dbc26f0593fca66db1cb98/contrib/dockerd-rootless.sh#L136

`rm -rf $directory` w/o check might be safe with the current revision of the code, but can be potentially dangerous in future modifications to the script

Comment (ereslibre) [reply contrib/dockerd-rootless.sh:62]: > but can be potentially dangerous in future modifications to the script

I am following the script with debugging and checking the PID and their mount namespace at all times, and when we delete the directories and remount them we are doing it always inside the pseudo-root namespace.

For example, `/var/run/cdi` wouldn't be on the copy-up list, but we still want to remount it inside the pseudo-root namespace. We could add it to the `copy-up` list, but we don't need to write to it, just read. Same in principle would go for `/etc/cdi`, but since we are copy-upping /etc it's fine I think, no need for more hassle.

Comment (ereslibre) [reply contrib/dockerd-rootless.sh:62]: Maybe I could add some guardrails to `mount_directory` so that it's not called from the original namespace, even if the script evolves. I can look into what checks might give us that hint.

File: contrib/dockerd-rootless.sh (hunk 1 above)
Comment (elezar) [reply contrib/dockerd-rootless.sh:168]: I think the comment is fine for now. I'm also happy to put off trying to create this folder or monitor for its existence for the time being. Let's rather get feedback on the use of CDI in this context before making things more public or more complex.

**Comment by elezar** [comment]
LGTM from a CDI perspective.

File: contrib/dockerd-rootless.sh (hunk 2 above)
Comment (AkihiroSuda) [reply contrib/dockerd-rootless.sh:62]: If adding a guardrail is difficult, at least a comment line should be added

Comment (ereslibre) [reply contrib/dockerd-rootless.sh:62]: Thanks @AkihiroSuda, let me give it some thought and I will ping you folks back on this PR.

Comment (ereslibre) [reply contrib/dockerd-rootless.sh:67]: It was fairly trivial. I added the guardrails and now the script fails and exit if `mount_directory` is called from the wrong context.

File: contrib/dockerd-rootless.sh [hunk 4]
```diff
@@ -54,6 +54,21 @@ if ! [ -d "$HOME" ]; then
...
+	if [ -z "$_DOCKERD_ROOTLESS_CHILD" ]; then
+		echo "mount_directory should be called from the child context. Otherwise data loss is at risk"
+		exit 1
+	fi
+
+	local directory="$1"
+	local mount_options="${2:---bind}"
+
+	directory_realpath=$(realpath "$directory")
+	rm -rf "$directory"
```
Comment (AkihiroSuda) [inline contrib/dockerd-rootless.sh:67]: A comment should be added to explain that this is a "copied-up" file (usually symlink)

Comment (ereslibre) [reply contrib/dockerd-rootless.sh:73]: Updated.

File: contrib/dockerd-rootless.sh [hunk 5]
```diff
@@ -120,6 +141,7 @@ if [ -z "$_DOCKERD_ROOTLESS_CHILD" ]; then
 		_DOCKERD_ROOTLESS_SELINUX=1
 		export _DOCKERD_ROOTLESS_SELINUX
 	fi
+
```
Comment (AkihiroSuda) [inline contrib/dockerd-rootless.sh:144]: Unnecessary change, probably accidentally added

**Review by AkihiroSuda — APPROVED** [review]

File: contrib/dockerd-rootless.sh (hunk 5 above)
Comment (ereslibre) [reply contrib/dockerd-rootless.sh]: Updated, leftover.

**Comment by stevapple** [comment]
We have already been applying this patch in production and it saves our day. Is there any possibility that we can merge this PR into the upcoming Docker release so no more patch is required for GPUs in Rootless Docker?

**Comment by thaJeztah** [comment]
did a quick rebase to have a fresh run of CI

File: contrib/dockerd-rootless.sh [hunk 6]
```diff
@@ -54,6 +54,27 @@ if ! [ -d "$HOME" ]; then
...
 fi
 
+mount_directory() {
+	if [ -z "$_DOCKERD_ROOTLESS_CHILD" ]; then
+		echo "mount_directory should be called from the child context. Otherwise data loss is at risk"
+		exit 1
+	fi
+
+	local directory="$1"
+	local mount_options="${2:---bind}"
```
Comment (thaJeztah) [inline contrib/dockerd-rootless.sh:64]: Just noticed the use of `local` here, which I think is not part of POSIX, and maybe incorrect for the shebang used (`#!/bin/sh`)

Comment (ereslibre) [reply contrib/dockerd-rootless.sh:64]: Oh, great catch. I was unaware of that. Will update the PR.

Comment (thaJeztah) [reply contrib/dockerd-rootless.sh:64]: Thanks! It will _probably_ work in many cases, but the intent of some of these scripts was to keep them as portable as possible (and don't depend on bashisms); some distros may be stricter than others for `/bin/sh`, so it could fail. And _probably_ for this one, it's not critical to have.

Comment (ereslibre) [reply contrib/dockerd-rootless.sh]: Updated! Thanks for the catch! I have tested that it works as expected.

**Review by thaJeztah — APPROVED** [review]
LGTM


@tianon  @cpuguy83 want to have a look as well if there's any thing I'm overlooking?

File: contrib/dockerd-rootless.sh [hunk 7]
```diff
@@ -139,6 +160,25 @@ if [ -z "$_DOCKERD_ROOTLESS_CHILD" ]; then
...
+	# order for it to read the CDI specification files. Otherwise, a
+	# Docker daemon restart will be required for the daemon to discover
+	# them.
+	#
+	# If another set of CDI paths (other than the default /etc/cdi and
+	# /var/run/cdi) are configured through the Docker configuration file
+	# (using "cdi-spec-dirs"), they need to be bind mounted in rootless
+	# mode; otherwise the Docker daemon won't have access to the CDI
+	# specification files.
+	[ -d "/etc/cdi" ] && mount_directory /etc/cdi
```
Comment (cpuguy83) [inline contrib/dockerd-rootless.sh:179]: Won't these checks trigger the script to exit early due to `set -e`?

**Review by cpuguy83 — CHANGES_REQUESTED** [review]

File: contrib/dockerd-rootless.sh (hunk 7 above)
Comment (ereslibre) [reply contrib/dockerd-rootless.sh:179]: I think it's fine because they are in a conditional, checked that it works:

```
#!/bin/sh

set -e

mount_directory() {
    echo "mount_directory $1;"
}

[ -d "/non/existant/path" ] && mount_directory /non/existant/path
[ -d "/etc/cdi" ] && mount_directory /etc/cdi
[ -d "/var/run/cdi" ] && mount_directory /var/run/cdi
```

Yielding:

```
❯ ./test.sh
mount_directory /etc/cdi;
mount_directory /var/run/cdi;
```

Comment (cpuguy83) [reply contrib/dockerd-rootless.sh:179]: That's not a conditional, though.
It is the same as `test -d <dir>`, which exits non-zero if the directory does not exist.

```console
$ [ -d /foo ] || echo $?
1
```

In the case of this PR, if any of these tested dirs do not exist, the script will exit early.

Here's a more complete example


```bash
foo() {
  [ -d /does/not/exist ]
  echo "after dir check"
}

set -e

foo
echo "after foo"
```

The placement of `set -e` doesn't matter there so long as we put it before calling `foo`.
If you copy/paste this into your shell (maybe do it in a subshell) it will exit with code `1` and not output anything.

Comment (ereslibre) [reply contrib/dockerd-rootless.sh]: Thanks for your explanation. Updated to perform the check in a proper conditional. Hope I didn't overlook anything this time.

File: contrib/dockerd-rootless.sh [hunk 8]
```diff
@@ -54,6 +54,30 @@ if ! [ -d "$HOME" ]; then
 	exit 1
 fi
 
+mount_directory() {
+	if [ -z "$_DOCKERD_ROOTLESS_CHILD" ]; then
+		echo "mount_directory should be called from the child context. Otherwise data loss is at risk"
```
Comment (cpuguy83) [inline contrib/dockerd-rootless.sh:59]: Send to stderr `>&2`

**Review by cpuguy83 — CHANGES_REQUESTED** [review]
Minor change, but otherwise LGTM

File: contrib/dockerd-rootless.sh (hunk 8 above)
Comment (ereslibre) [reply contrib/dockerd-rootless.sh]: Done! Thanks :)

**Review by cpuguy83 — APPROVED** [review]

**Comment by ereslibre** [comment]
> @ereslibre Can you create backports of this PR to 25.x through 27.x? I'm not sure if 25.x backport will actually help anyone, but a 27.x one would be sincerely appreciated.

@stevapple Yes, I will do that later today!

**Comment by thaJeztah** [comment]
I was working on some backports, so opened cherry-picks for those branches 👍

**Comment by ereslibre** [comment]
> I was working on some backports, so opened cherry-picks for those branches 👍

Thanks @thaJeztah!

File: contrib/dockerd-rootless.sh [hunk 9]
```diff
@@ -139,6 +163,25 @@ if [ -z "$_DOCKERD_ROOTLESS_CHILD" ]; then
...
+	# Docker daemon restart will be required for the daemon to discover
+	# them.
+	#
+	# If another set of CDI paths (other than the default /etc/cdi and
+	# /var/run/cdi) are configured through the Docker configuration file
+	# (using "cdi-spec-dirs"), they need to be bind mounted in rootless
+	# mode; otherwise the Docker daemon won't have access to the CDI
+	# specification files.
+	mount_directory /etc/cdi
+	mount_directory /var/run/cdi
```
Comment (AkihiroSuda) [inline contrib/dockerd-rootless.sh:183]: Is there any reason that we don't scan `$XDG_CONFIG_HOME/cdi` and `XDG_RUNTIME_DIR/cdi` ?

Comment (AkihiroSuda) [inline contrib/dockerd-rootless.sh:183]: These mounts are probably not necessary if we can let dockerd ignore `EACCES` ?

Comment (ereslibre) [reply contrib/dockerd-rootless.sh:183]: No specific reason from my end

Comment (ereslibre) [reply contrib/dockerd-rootless.sh:183]: They would not be necessary in that case. However, I wasn’t sure about the implications so I went with the safest approach.
