### PR TITLE
28722: List of containers with networkID filter is not working

### LINKED ISSUE #28722: List of containers with networkID filter is not working (docker ps --filter "network=nwID")
**Description**
docker ps --filter does not work for partial network ID.

**Steps to reproduce the issue:**
1.  Created a network dk0

    [root@datta-bastion-dns docker]# docker network ls
  NETWORK ID          NAME                DRIVER              SCOPE
  f5c40491da47        bridge              bridge              local
  2968b0850d98        dk0                 bridge              local
  0d4ed75c8c6c        host                host                local
  e6919f3b8d9a        none                null                local

2. Create a container with a network in #1.
   docker run -it -d --net=2968b0850d98 busybox sh  

3. Filter with same network
    docker ps --filter "network=2968b0850d98"

Note: Filter with full networkID worked.

**Describe the results you received:**
able to create container with network ID ( Partial ID ) which is shown in 'docker network ls'

\# docker ps --filter "network=2968b0850d98"
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

Observed Empty output

**Describe the results you expected:**
docker ps with filter should show container with network ID "2968b0850d98"

**Output of `docker version`:**
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:
 OS/Arch:      linux/amd64

**Output of `docker info`:**
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 64
Server Version: 1.12.3
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.36.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.797 GiB
Name: datta-bastion-dns.cisco.com
ID: 7ZBB:T5UR:R7FN:ZMZS:DG4R:26W5:GOW7:5CV4:CDCE:GQ54:LVXV:OQPK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 29
 Goroutines: 43
 System Time: 2016-11-22T19:57:40.567435847Z
 EventsListeners: 0
Username: dattatrayakumbhar04
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8

### PR DESCRIPTION
**Pull request by dattatrayakumbhar**
### fixes #28722 

**- What I did**
    Added support for docker ps --filter with network=Partial networkID 

**- How I did it**
    Added has_prefix to find given network ID in full network ID because while network filter full network ID is used.

**- How to verify it**
 docker ps --filter "network=<network ID in docker network ls command>"

#docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
efe9b61af601        1net111             bridge              local
75ac60b510aa        bridge              bridge              local
e3ec0522da75        host                host                local
317a99c1d3f7        net1                bridge              local
28478de7a883        net11               bridge              local
13a77790105b        net111              bridge              local

#docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
ef7dd24d70de        busybox             "sh"                19 minutes ago      Up 19 minutes                           1net111
34b5e642b1ec        busybox             "sh"                19 minutes ago      Up 19 minutes                           bridge
b878a0a255d2        busybox             "sh"                7 minutes ago       Up 7 minutes                            host
a3dde8b8ff3c        busybox             "sh"                18 minutes ago      Up 18 minutes                           net1
fb060af4b644        busybox             "sh"                16 minutes ago      Up 15 minutes                           net11
b213f20a8309        busybox             "sh"                15 minutes ago      Up 15 minutes                           net111

and had running container one in each network:

Filter should work as follows:

1. Filter multiple container  whose network name is same (prefix)  
#docker ps -f network=net
a3dde8b8ff3c        busybox             "sh"                18 minutes ago      Up 18 minutes                           net1
fb060af4b644        busybox             "sh"                16 minutes ago      Up 15 minutes                           net11
d213f20a8309        busybox             "sh"                15 minutes ago      Up 15 minutes                           net111

2. filter with partial network ID 
#docker ps -f network=ef 
ef7dd24d70de        busybox             "sh"                19 minutes ago      Up 19 minutes                           1net111

3. if multiple contaner running with prefix 'eg. e' 
 #docker ps -f network=e
ef7dd24d70de        busybox             "sh"                19 minutes ago      Up 19 minutes                           1net111
b878a0a255d2        busybox             "sh"                7 minutes ago       Up 7 minutes                            host

4. if network name  and ID both have starting same prefix
#docker ps -f network=b 
 #docker ps -f network=b 
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
34b5e642b1ec        busybox             "sh"                19 minutes ago      Up 19 minutes                           bridge
d213f20a8309        busybox             "sh"                15 minutes ago      Up 15 minutes                           net111

### CODE REVIEW

**Comment by thaJeztah** [comment]
Given that the filter accepts both "name" and "id" of the network, we should check if this has the right behavior, e.g. 

- if multiple network ID's have the same prefix
- if both a network named `db` and a network with ID `dbdeadbeef` exists
- if networks `db` and `db1` exist

I haven't checked yet, and we should compare with other filters for consistency

**Comment by thaJeztah** [comment]
This may be an issue if people use this for automation, e.g. "remove all containers from network X", it if returns containers that are also connected to a different network, that could break them.

So we should do;

1. Match on _full id_
2. Match on _partial_ id (prefix)
3. Match on _full_ name

@dattatrayakumbhar are you willing to work on this, or need assistance?

**Comment by dattatrayakumbhar** [comment]
Sure @thaJeztah.
I will add check to match on three points which you mentioned .

**Comment by LK4D4** [comment]
@dattatrayakumbhar how is it going with this PR?

**Comment by dattatrayakumbhar** [comment]
Updating PR with networkId partial and full name now.
Stuck in , how to get and compare networkName ?
can someone help me ?

**Comment by LK4D4** [comment]
@dattatrayakumbhar `container.HostConfig.NetworkMode.NetworkName()` that's what I found. Don't know how to compare though :)

**Comment by dattatrayakumbhar** [comment]
@thaJeztah @LK4D4 
Updated PR with changes. Also updated testing steps and example which should work with this PR.

**Comment by LK4D4** [comment]
design is ok btw
ping @thaJeztah who likes to review PRs in design-review :)

**Comment by dattatrayakumbhar** [comment]
@thaJeztah 
Could you please review it when you have time ?

**Review by AkihiroSuda — COMMENTED** [review]
SGTM, but I think we need an integration test

File: daemon/list.go [hunk 1]
```diff
@@ -499,14 +499,14 @@ func includeContainerInList(container *container.Container, ctx *listContext) it
 	networkExist := fmt.Errorf("container part of network")
 	if ctx.filters.Include("network") {
 		err := ctx.filters.WalkValues("network", func(value string) error {
-			if _, ok := container.NetworkSettings.Networks[value]; ok {
-				return networkExist
-			}
```
Comment (thaJeztah) [inline daemon/list.go]: I think we can keep this shortcut, so that we don't have to loop the list of networks if there's a direct match

File: daemon/list.go [hunk 2]
```diff
@@ -499,14 +499,14 @@ func includeContainerInList(container *container.Container, ctx *listContext) it
...
 			for _, nw := range container.NetworkSettings.Networks {
 				if nw.EndpointSettings == nil {
 					continue
 				}
-				if nw.NetworkID == value {
+				if strings.HasPrefix(nw.NetworkID, value) {
+					return networkExist
+				}
+				if strings.HasPrefix(container.HostConfig.NetworkMode.NetworkName(), value) {
```
Comment (thaJeztah) [inline daemon/list.go]: I'm wondering if filtering on networks should be done on _name_ prefixes as well, or only on _id_ prefixes

**Review by thaJeztah — CHANGES_REQUESTED** [review]
left some comments

File: daemon/list.go (hunk 1 above)
Comment (dattatrayakumbhar) [inline daemon/list.go]: @thaJeztah  I have removed exact match because if two network one with net1 and net111 present,
and each having one container. I we filtered it with net1  and we added exact match scenario then it'll just return container with net1 however net1 is also comes in net111 so ideally it should have list down both container when we filter with net1.

Do we want to add exact match then we can add this ?

File: daemon/list.go (hunk 2 above)
Comment (dattatrayakumbhar) [inline daemon/list.go]: @thaJeztah  
If we removed match on networkName, it wont work if net1 and net111 network preset and filtered with netonly as commented as above.
Should we remove this also ?

File: daemon/list.go (hunk 1 above)
Comment (thaJeztah) [inline daemon/list.go]: But it would still match, because if it's not a full match, it goes to the loop below

File: daemon/list.go (hunk 2 above)
Comment (thaJeztah) [inline daemon/list.go]: Yes, I think we should not do a _partial_ match on names (at least not for now). I compared with filtering by `volume`, and that also does a _full_ match only;

```bash

$ docker volume create vol1
vol1
$docker volume create vol11
vol11
$ docker run -dit -v vol1:/foo busybox
8ce3ed958ecd9b6e2eeb63246f5b2626838a451bc57c711bc2e4c5b8530b6f38
$ docker run -dit -v vol11:/foo busybox
3ad4fe7692514e4cccfdba36c763c936b1b7729bbc46d543dda989076b36454b

$ docker ps --filter volume=vol1
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
8ce3ed958ecd        busybox             "sh"                15 seconds ago      Up 14 seconds                           hardcore_mccarthy

$ docker ps --filter volume=vol11
CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS              PORTS               NAMES
3ad4fe769251        busybox             "sh"                About a minute ago   Up About a minute                       optimistic_jones
```

Note that doing partial matching on _ID_ is ok, because that's what we do in other places

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Review by vdemeester — CHANGES_REQUESTED** [review]
I think it would be perfect with a small integration test 👼

**Comment by dattatrayakumbhar** [comment]
@vdemeeater,
Added integration test.. Also.. Thanks

**Review by vdemeester — APPROVED** [review]
LGTM 👍
