### PR TITLE
pkg/archive: fix TestTarUntarWithXattr failure on recent kernel

### LINKED ISSUE #38289: pkg/archive.TestTarUntarWithXattr fails on recent kernel
**Description**

`pkg/archive.TestTarUntarWithXattr` fails on recent kernel

**Steps to reproduce the issue:**

```console
$ TESTDIRS='github.com/docker/docker/pkg/archive' make test-unit
...
--- FAIL: TestTarUntarWithXattr (0.00s)
    archive_unix_test.go:236: assertion failed: error is not nil: invalid argument
```

https://github.com/moby/moby/blob/852542b3976754f62232f1fafca7fd35deeb1da3/pkg/archive/archive_unix_test.go#L235-L236

Tested on 852542b3976754f62232f1fafca7fd35deeb1da3, with Ubuntu 18.04.1 kernel 4.15.0-39-generic

**Describe the results you received:**

The test failed

**Describe the results you expected:**

The test should success

**Additional information you deem important (e.g. issue happens only occasionally):**

CI does not seem hitting the issue (probably using older kernel shipped with Ubuntu 16.04)

**Output of `docker version`:**

```
Client:
 Version:           master-dockerproject-2018-11-28
 API version:       1.40
 Go version:        go1.11.1
 Git commit:        69bd2728
 Built:             Wed Nov 28 23:39:38 2018
 OS/Arch:           linux/amd64
 Experimental:      true

Server:
 Engine:
  Version:          master-dockerproject-2018-11-28
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.11.2
  Git commit:       852542b
  Built:            Wed Nov 28 23:48:23 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 37
Server Version: master-dockerproject-2018-11-28
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: kata runc runnc runsc runsc-kvm
Default Runtime: runc
Init Binary: docker-init
containerd version: de1f167ab96338a9f5c2b17347abf84bdf1dd411
runc version: b1068fb9258d2cc5aa59505fbb703d914120013d
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-39-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.829GiB
Name: suda-ws01
ID: MTEP:U62V:AHM4:G7PE:XLR6:W4WR:WL4B:G5MY:VM5S:2MAV:GP25:ETL6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 43
 System Time: 2018-11-29T13:59:54.443932021+09:00
 EventsListeners: 0
Username: akihirosuda
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>

**- What I did**

Fix `TestTarUntarWithXattr` failure on recent kernel, which has strict check for `security.capability` value.
Fix #38289 

**- How I did it**

Use `setcap`/`getcap` binary with real capability value, rather than using invalid capability.

**- How to verify it**

```
$ TESTDIRS='github.com/docker/docker/pkg/archive' TESTFLAGS="-run TestTarUntarWithXattr -v" make test-unit
...
=== RUN   TestTarUntarWithXattr
--- PASS: TestTarUntarWithXattr (0.01s)
PASS
coverage: 30.7% of statements
ok      github.com/docker/docker/pkg/archive    0.018s  coverage: 30.7% of statements
```

Tested on Ubuntu 18.04.1, kernel `4.15.0-39-generic #42-Ubuntu`

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**
:penguin:

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @kolyshkin @tonistiigi PTAL

**Comment by AkihiroSuda** [comment]
cc @cpuguy83

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

File: pkg/archive/archive_unix_test.go [hunk 1]
```diff
@@ -232,8 +240,9 @@ func TestTarUntarWithXattr(t *testing.T) {
 	assert.NilError(t, err)
 	err = ioutil.WriteFile(filepath.Join(origin, "3"), []byte("will be ignored"), 0700)
 	assert.NilError(t, err)
-	err = system.Lsetxattr(filepath.Join(origin, "2"), "security.capability", []byte{0x00}, 0)
-	assert.NilError(t, err)
+	// there is no known Go implementation of setcap/getcap with support for v3 file capability
```
Comment (thaJeztah) [inline pkg/archive/archive_unix_test.go]: @AkihiroSuda should we raise an issue for this with the Go maintainers? (perhaps @tklauser knows if this is something that's being worked on, or a tracking issue exists?)

Comment (AkihiroSuda) [reply pkg/archive/archive_unix_test.go]: Yes, but can be implemented as a 3rd party library perhaps. (Go standard lib doesn't seem to have library functions even for v2 cap)

Actually https://github.com/tianon/debian-golang-gocapability/blob/master/capability/capability_linux.go seems supporting v3, I can't remember why I didn't choose this library.

Comment (tklauser) [reply pkg/archive/archive_unix_test.go]: @thaJeztah @AkihiroSuda AFAIK this is not being worked on currently, nor does there exist an issue for adding this to `golang.org/x/sys/unix` (the `syscall` package in the standard lib is frozen, so it is unlikely to be added there). But please feel free to file such an issue on https://github.com/golang/go/issues/new against the `x/sys/unix` package if you need these wrappers.
