### PR TITLE
rootless: fix getCurrentOOMScoreAdj (fix rootless docker in kubernetes)

### LINKED ISSUE #40068: rootless docker in kubernetes: "getting the final child's pid from pipe caused \"EOF\"": unknown"
I am trying to run rootless docker-in-docker deployed on Kubernetes, where the docker daemon is deployed using this manifest:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: rootless
  name: rootless
spec:
  replicas: 1
  selector:
    matchLabels:
      run: rootless
  template:
    metadata:
      labels:
        run: rootless
    spec:
      containers:
      - image: docker:19.03.1-dind-rootless
        name: rootless
        command:
        - sh
        - -c
        - dockerd-entrypoint.sh --experimental --storage-driver=vfs
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: true
          privileged: true
        resources: {}
status: {}
```

The daemon seems to start up fine but `kubectl exec`'ing into the pod, setting the DOCKER_HOST and attempting to run a container seems to break

```
kubctl create -f rootless.yml
kubectl exec -it rootless-7c94dcc5d7-gplvm sh
/ $ export DOCKER_HOST=unix:///run/user/1000/docker.sock
/ $ docker run --rm -it  busybox sh
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:303: getting the final child's pid from pipe caused \"EOF\"": unknown.
/ $ command terminated with exit code 125
```

The dockerd daemon logs are collected in this gist

https://gist.github.com/lukasheinrich/e23c00240afed83066978dab8c354f52#file-logs

`kubectl version` gives

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"archive", BuildDate:"2019-06-18T20:40:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

cc @AkihiroSuda @rochaporto

### PR DESCRIPTION
**Pull request by AkihiroSuda**
**- What I did**

Fix #40068: `rootless docker in kubernetes: "getting the final child's pid from pipe caused \"EOF\": unknown"`

**- How I did it**

Fixed `getCurrentOOMScoreAdj()` to trim "\n" before calling `strconv.Atoi`.

**- How to verify it**
`rootless.yaml`:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: rootless
spec:
  containers:
    # dind:local is from "docker:20.10.5-dind" but the following files are updated:
    # - /usr/local/bin/dockerd     (for this PR)
    # - /usr/local/bin/containerd* (for https://github.com/containerd/containerd/pull/4845)
    - image: dind:local
      imagePullPolicy: Never
      name: rootless
      env:
        - name: DOCKER_HOST
          value: unix:///run/user/1000/docker.sock
      securityContext:
        privileged: true
```

```console
$ kind create cluster
$ kubectl apply -f rootless.yaml
$ kubectl exec rootless -- docker run hello-world
...
Hello from Docker!
```

**- Description for the changelog**

Fix `rootless docker in kubernetes: "getting the final child's pid from pipe caused \"EOF\": unknown"

**- A picture of a cute animal (not mandatory but encouraged)**
:penguin:

### CODE REVIEW

File: rootless/specconv/specconv_linux.go [hunk 1]
```diff
@@ -19,10 +21,13 @@ func ToRootless(spec *specs.Spec, v2Controllers []string) error {
 func getCurrentOOMScoreAdj() int {
 	b, err := ioutil.ReadFile("/proc/self/oom_score_adj")
 	if err != nil {
+		logrus.WithError(err).Warn("failed to read /proc/self/oom_score_adj")
```
Comment (thaJeztah) [inline rootless/specconv/specconv_linux.go:24]: Do we know under what circumstances this fails? Would it be an `os.IsNotExist()`? (in that case, should we just ignore?)

File: rootless/specconv/specconv_linux.go [hunk 2]
```diff
@@ -19,10 +21,13 @@ func ToRootless(spec *specs.Spec, v2Controllers []string) error {
...
 		return 0
 	}
-	i, err := strconv.Atoi(string(b))
+	s := string(b)
+	i, err := strconv.Atoi(strings.TrimSpace(s))
 	if err != nil {
+		logrus.WithError(err).Warn("failed to parse /proc/self/oom_score_adj (%q)", s)
```
Comment (thaJeztah) [inline rootless/specconv/specconv_linux.go:30]: Should we log the value _before_ trimming? (also simplifies the code a bit)

```suggestion
	i, err := strconv.Atoi(strings.TrimSpace(string(b)))
	if err != nil {
		logrus.WithError(err).Warn("failed to parse /proc/self/oom_score_adj (%q)", b)
```

**Review by thaJeztah — CHANGES_REQUESTED** [review]
Wondering; if the issue is that we're trying to set an OOM score that's out of range; should we check limits in `toRootless`, and clip to `max` / `min` (`-1000 .... 1000`)? https://github.com/moby/moby/blob/46cdcd206c56172b95ba5c77b827a722dab426c5/rootless/specconv/specconv_linux.go#L70-L72

File: rootless/specconv/specconv_linux.go (hunk 1 above)
Comment (AkihiroSuda) [reply rootless/specconv/specconv_linux.go:24]: Never happens, IIUC

File: rootless/specconv/specconv_linux.go (hunk 2 above)
Comment (AkihiroSuda) [reply rootless/specconv/specconv_linux.go:30]: Already logging untrimmed string

Comment (thaJeztah) [reply rootless/specconv/specconv_linux.go:30]: oh! 🤦 yes, it's just the extra variable to convert `[]byte` to string

**Comment by AkihiroSuda** [comment]
No, not out of range.

Docker always attempts to launch a container with oomScoreAdj=0, but the daemon's oomScoreAdj is set to 1000 by Kube, so we need to adjust the oomScoreAdj of the container being created from 0 to 1000.

**Comment by thaJeztah** [comment]
> Docker always attempts to launch a container with oomScoreAdj=0

I recall changing the daemon itself to not adjust if no custom oom-score is set (https://github.com/moby/moby/pull/41527); in this case, the daemon runs inside a container with an OOM-score "X", but the daemon itself does not have an `--oom-score-adj` set (so we don't adjust); shouldn't we do the same for containers running in that environment? i.e., we didn't adjust their score, so inherit the current value (which on a host would be "don't adjust", but in this container would be "x")? I would consider the oom-score to be "relative to" the current environment. Would that work?

**Comment by AkihiroSuda** [comment]
I think that's possible by changing `OomScoreAdj int` to `OomScoreAdj *int` for allowing nil: https://github.com/moby/moby/blob/dea989ea2fb8015b21c22f728fe0cd0d78256f84/api/types/container/host_config.go#L415
But that doesn't work with existing client implementations.

So I suggest merging this PR, and looking into possibility of the API change in a separate PR.

**Comment by thaJeztah** [comment]
> But that doesn't work with existing client implementations.
> So I suggest merging this PR, and looking into possibility of the API change in a separate PR.

Yes, we can fix that in a follow-up; I went looking for the original commit that added `--oom-score-adj`; https://github.com/moby/moby/commit/d3af7f283d8dc0be67be48e14cd740fbeb690f7a (https://github.com/moby/moby/pull/16277). From that PR it looks like we just added `0` as default; given that that is the default value (and not a choice of the user), and effectively _should_ mean "don't adjust", I think we may even be able to change without changing it to a pointer (just consider `0` to mean "don't adjust"); I see we currently don't have an option to update the value in `docker update`, so from that perspective, it should not be ambiguous as well (if `0` could mean "reset to default" - not sure if even possible)

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@cpuguy83 PTAL

**Review by tiborvass — APPROVED** [review]
