### PR TITLE
fix race condition between list and remove volume

### LINKED ISSUE #21403: race condition in volume delete and list
I don't have an easy way to reproduce this race condition, but I was able to track it down by re-installing DTR, removing the containers, deleting volumes and trying to create theme again.

Basically, in VolumeStore when there's a Delete operation holding the named lock for a volume and a List operation has just finished listing volumes, but hasn't attempted to add them to the cache yet the list operation will try to acquire the named lock and block. When the Delete operation has finished it will release the named lock and the List operation will be unblocked and it will put the volume in the cache without checking if it still exists after acquiring the lock on the name.

This happens in docker 1.10 and 1.11/06e98f0a5cf59c040e9f753d60f33ba22256d55c. I haven't tested it in older versions.

### PR DESCRIPTION
**Pull request by vikstrous**
This PR supersedes #21405

fixes #21403 

**\- What I did**
Avoided having a race between volume List and Remove

**\- How I did it**
Made List not populate the volume names cache

**\- How to verify it**
Read the code. I don't have an easy way to reproduce the issue. It would be great if someone can come up with a test for this. Also see #21405 for an alternative solution.

**\- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by vikstrous** [comment]
I closed #21405 in favour of this one because the end result is much more understandable code and this doesn't require a second volume driver operation for every volume when listing volumes.

**Comment by calavera** [comment]
> Made List not populate the volume names cache

@cpuguy83 it looks like you were on board with this idea in #21405, but I just want to double check that you're okay with it.

**Comment by vikstrous** [comment]
none of these test failures look related to my change :/

**Comment by thaJeztah** [comment]
Hm, hitting this https://github.com/docker/docker/issues/21034, which
should've been fixed by https://github.com/docker/docker/issues/21035


https://jenkins.dockerproject.org/job/Docker-PRs-WoW-TP4/3604/console

```
21:59:14 ----------------------------------------------------------------------
21:59:14 FAIL: docker_cli_exec_test.go:297: DockerSuite.TestExecInspectID
21:59:14 
21:59:14 docker_cli_exec_test.go:332:
21:59:14     c.Assert(err, checker.IsNil, check.Commentf("failed to run the 2nd exec cmd"))
21:59:14 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc08241f260), Stderr:[]uint8(nil)} ("exit status 126")
21:59:14 ... failed to run the 2nd exec cmd
21:59:14 
21:59:15 
21:59:15 ----------------------------------------------------------------------
```

**Comment by LK4D4** [comment]
@thaJeztah It's definitely another issue. Probably has something to do with containerd integration.

**Comment by vikstrous** [comment]
I'll rebase. That'll probably help. I made this branch from before containerd, so that's probably why everything is failing.

**Comment by thaJeztah** [comment]
I reopened the flaky test issue just in case

File: volume/store/store.go [hunk 1]
```diff
@@ -120,26 +120,8 @@ func (s *VolumeStore) List() ([]volume.Volume, []string, error) {
...
 
-	for _, v := range vols {
-		name := normaliseVolumeName(v.Name())
-
-		s.locks.Lock(name)
-		storedV, exists := s.getNamed(name)
-		if !exists {
-			s.setNamed(v, "")
-		}
-		if exists && storedV.DriverName() != v.DriverName() {
```
Comment (cpuguy83) [inline volume/store/store.go]: These are the bits that worry me.
Can we still consult the cache so we don't put up potentially duplicate volumes and just not insert new items into the cache?

Comment (calavera) [inline volume/store/store.go]: @vikstrous ?

Comment (vikstrous) [inline volume/store/store.go]: Is it a problem if we display duplicate volumes if they exist?

Comment (vikstrous) [inline volume/store/store.go]: What if we just deduplicate the list within this function without using the actual cache?

Comment (cpuguy83) [inline volume/store/store.go]: Yes, we strive to make sure they don't exist, since there is no way to actually pick 1 volume or the other

Comment (vikstrous) [inline volume/store/store.go]: Okay. This makes my fix a 3 line diff. PTAL again.

**Comment by vikstrous** [comment]
@cpuguy83 ptal again, tests passed, my PR is 3 lines, it should be okay now :)

**Comment by coolljt0725** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM
