### PR TITLE
Windows - fix panic and stderr output when service

### LINKED ISSUE #31927: Daemon outputs only to stderr
**Description**

All output from the Docker Daemon is on stderr. It's been like this for a long time, so this issue is more of a discussion if this is the correct behaviour than an issue. This is a slight inconvenience on Windows when attempting to redirect the daemon output to a file.

Is there a particular reason that it is output to stderr rather than stdout?

**Steps to reproduce the issue:**
1. `dockerd > stdout 2> stderr`

**Describe the results you received:**

```
$ sudo dockerd > stdout 2> stderr
$ cat stdout
$ cat stderr
time="2017-03-17T13:43:55.374185400-07:00" level=info msg="libcontainerd: new containerd process, pid: 26105"
time="2017-03-17T13:43:55.401719265-07:00" level=warning msg="containerd: low RLIMIT_NOFILE changing to max" current=1024 max=65536
time="2017-03-17T13:43:56.376746015-07:00" level=info msg="[graphdriver] using prior storage driver: aufs"
time="2017-03-17T13:43:56.422300241-07:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2017-03-17T13:43:56.422457803-07:00" level=warning msg="Your kernel does not support swap memory limit"
time="2017-03-17T13:43:56.422489715-07:00" level=warning msg="Your kernel does not support cgroup rt period"
time="2017-03-17T13:43:56.422497518-07:00" level=warning msg="Your kernel does not support cgroup rt runtime"
time="2017-03-17T13:43:56.422766023-07:00" level=info msg="Loading containers: start."
time="2017-03-17T13:43:56.428612998-07:00" level=info msg="Firewalld running: false"
time="2017-03-17T13:43:56.544798310-07:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
time="2017-03-17T13:43:56.586924702-07:00" level=info msg="Loading containers: done."
time="2017-03-17T13:43:56.649531465-07:00" level=info msg="Daemon has completed initialization"
time="2017-03-17T13:43:56.649591888-07:00" level=info msg="Docker daemon" commit=60ccb22 graphdriver=aufs version=17.03.0-ce
time="2017-03-17T13:43:56.655241887-07:00" level=info msg="API listen on /var/run/docker.sock"
time="2017-03-17T13:45:47.757254970-07:00" level=info msg="Processing signal 'interrupt'"
time="2017-03-17T13:45:47.769260692-07:00" level=info msg="stopping containerd after receiving terminated"
```

**Describe the results you expected:**

I'd expect that it not all be output to stderr. Either both stdout and stderr, or just stdout, but it seems odd to put info logs on stderr.

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

/cc @jhowardmsft

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard <jhoward@microsoft.com>

@jstarks FYI.

There are three tiny fixes here:

When running as a Windows service, writes to stderr (eg `fmt.Fprintf(os.Stderr,...)` were being thrown away. This is because os.Stderr wasn't being reset to the panicfile FD.

Second, if a goroutine does panic when running as a service, as the built-in golangs handlers stderr handle wasn't being set to the panic file, it would also be thrown away.

Verified both the above by temporarily adding a null-pointer deference and a `fmt.FPrintf(os.stderr)`, and checking the contents of `panic.log` are populated in both cases.

Third - @thaJeztah @darrenstahlmsft  Fixes https://github.com/docker/docker/issues/31927. Without wanting to rat-hole over whether the same fix is right for non-Windows (can be addressed in a follow-up, no reason to delay this one), I've updated it so that on Windows at least, the daemon uses stdout for log messages rather than stderr, and done manual verification that it does the expected thing.

The first two fixes are critical for investigating some issues such as https://github.com/docker/docker/issues/30605#issuecomment-290556243 and it would be great to get this cherry-picked into a formal release ASAP so that @georgyturevich could continue to provide valuable debugging logs for issues on his production system with an official release, while still running as a Windows service and not resorting to the use of command-line file redirection.  @thaJeztah @vieux

### CODE REVIEW

File: cmd/dockerd/service_windows.go [hunk 1]
```diff
@@ -409,6 +410,12 @@ func initPanicFile(path string) error {
 		return err
 	}
 
+	// Reset os.Stderr to the panic file (so fmt.Fprintf(os.Stderr,...) actually gets redirected)
+	os.Stderr = os.NewFile(uintptr(panicFile.Fd()), "/dev/stderr")
```
Comment (jhowardmsft) [inline cmd/dockerd/service_windows.go]: If someone is questioning why a *nix-style path, it's copied right out of how golang initializes os.Stderr

**Comment by darrenstahlmsft** [comment]
Not a maintainer, but LGTM. Doubling the ask to get this into a formal release as soon as possible, as it is currently impossible to debug Windows daemon panics when run as a service.

File: cmd/dockerd/service_windows.go [hunk 2]
```diff
@@ -409,6 +410,12 @@ func initPanicFile(path string) error {
...
+
+	// Force panicing threads to write to stderr (the panicFile handle now), otherwise it will go into the ether
```
Comment (johnstep) [inline cmd/dockerd/service_windows.go]: Nit: s/panicing/panicking

**Review by johnstep — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🦁

**Comment by jhowardmsft** [comment]
@thaJeztah @vieux - Good to merge? And to add to cherry-pick list?

**Comment by thaJeztah** [comment]
Good to go, but I discussed with @vieux when this PR was opened, and he informed me it was too late for 17.04

**Comment by fntlnz** [comment]
@thaJeztah There's no one who knows the historical windows for which on non-windows we need to go to `stderr` ? As stated in #31927 looks like that the history can't give any advice

**Comment by allencloud** [comment]
Will this fix back ported into docker-17.03-ee enterprise edition? Because we definitely think that this is really important for us to be able to get more data when this issue occurs.
@thaJeztah @vdemeester @jhowardmsft

**Comment by friism** [comment]
@allencloud we're considering this for backport, stay tuned.

While not supported, note that you can use Docker CE 17.06 which includes this fix: https://download.docker.com/win/static/stable/x86_64/

**Comment by allencloud** [comment]
Thanks for the feedback, @friism 
And I am afraid I have another two question. That is great if we can share more details on that:

1.What kind of bug fix could be back ported to the release docker-ee, currently docker-17.03.x-ee?
2.What is the determining factor which leads docker team to back port bug fix to released docker ee version, and some other factors?

**Comment by friism** [comment]
> What kind of bug fix could be back ported to the release docker-ee, currently docker-17.03.x-ee?

Typically critical security and bug fixes.

> What is the determining factor which leads docker team to back port bug fix to released docker ee version, and some other factors?

It's a combination of the severity and customer impact of the bug.

**Comment by thaJeztah** [comment]
> It's a combination of the severity and customer impact of the bug.

Also "risk" - every back port introduces the risk that regressions are introduced, so this has to be outweighed carefully
