### PR TITLE
fix LogConfig for containers created before docker 1.12 on daemon start

### LINKED ISSUE #22536: logging broken on existing when upgrading from 1.11
**Output of `docker version`:**
master

**Steps to reproduce the issue:**
1. create container with no logging options (and no logging options on the daemon) in 1.11
2. upgrade the daemon to master
3. try to start the container

**Describe the results you received:**
container start fails with:
```
Error response from daemon: Failed to initialize logging driver: Failed to get logging factory: logger: no log driver named '' is registered
```

**Describe the results you expected:**
Container should start

**Additional information you deem important (e.g. issue happens only occasionally):**

Found this while looking at another issue, logging here to make sure it doesn't get forgotten.

### PR DESCRIPTION
**Pull request by mountkin**
**\- What I did**
Fix #22536 
**\- How I did it**
#21153 rewrite the `LogConfig` of the container at create time to merge the daemon default log config to the container's `LogConfig`. It also removed some redundant log driver validations.

But the `LogConfig.Type` of the container is empty if it was created before docker 1.12 with default log driver. This caused the containers that were created before docker 1.12 with default log driver can't start after upgrade to 1.12. See #22536 

Ths PR merges the daemon log config to the container's log config at daemon startup if the container's `LogConfig.Type` is empty.
**\- How to verify it**
1. Create a container with docker 1.11 and don't specify th `--log-driver` argument.
2. Upgrade to docker 1.12-dev
3. Check if the container can be started under docker 1.12-dev

**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**

…rtup

Signed-off-by: Shijiang Wei mountkin@gmail.com

### CODE REVIEW

**Comment by runcom** [comment]
LGTM

**Comment by thaJeztah** [comment]
Hm, looks like there's a change in behavior in 1.12, possibly caused by https://github.com/docker/docker/pull/21153 that causes containers to not follow the daemon configuration after they have been created.

In docker 1.11;

```bash
$ docker daemon -D &
$ docker run -dit --name foobar busybox
$ docker inspect --format "{{ .HostConfig.LogConfig.Type }}" foobar
json-file

$ docker daemon -D --log-driver=syslog &
$ docker inspect --format "{{ .HostConfig.LogConfig.Type }}" foobar
syslog
```

In 1.12-dev, the second inspect still outputs `json-file`, so it appears containers persist the logging-driver that the daemon used when they were created.

**Comment by mountkin** [comment]
@thaJeztah could you help to test this as well? 
```bash
$ docker daemon -D &
$ docker run -dit --name foobar --log-opt max-file=5 busybox
$ docker start foobar 

$ docker daemon -D --log-driver=syslog &
$ docker start foobar 
```
(I'm on mobile now)

**Comment by thaJeztah** [comment]
On current master, inspect output for both is;

```json
{"Type":"json-file","Config":{"max-file":"5"}}
```

And the container starts


On docker 1.11, inspect after restarting docker gives;

```json
{"Type":"syslog","Config":{"max-file":"5"}}
```

strangely, if allows to start that container, and doesn't complain, so it may be `docker inspect` being wrong there.

Will try with your branch now

**Comment by thaJeztah** [comment]
With your branch, the container also starts, so it probably uses `json-file`, as the inspect output says.

File: daemon/daemon.go [hunk 1]
```diff
@@ -286,6 +286,16 @@ func (daemon *Daemon) restore() error {
 			logrus.Errorf("Failed to register container %s: %s", c.ID, err)
 			continue
 		}
+
+		// The LogConfig.Type is empty if the container was created before docker 1.12 with default log driver.
+		// We should rewrite it to use the daemon defaults.
+		// Fixes https://github.com/docker/docker/issues/22536
+		if c.HostConfig.LogConfig.Type == "" {
+			if err := daemon.mergeAndVerifyLogConfig(&c.HostConfig.LogConfig); err != nil {
+				logrus.Errorf("Failed to verify log config for container %s: %q", c.ID, err)
```
Comment (LK4D4) [inline daemon/daemon.go]: Do you think it will hurt to stop execution here?

Comment (mountkin) [inline daemon/daemon.go]: I think one container's error should not prevent the daemon from starting (like the 2 `continue` above).

**Comment by mountkin** [comment]
@thaJeztah I think the behavior of switch the daemon's `log-driver` with existing containers is somewhat buggy in docker 1.11. The `log-opt` of the container seems to be ignored after changing the daemon `log-driver`.

**Comment by thaJeztah** [comment]
@mountkin yes, I'm actually leaning towards *not* allowing `--log-opt`, unless a driver is specified on the same "level". Currently, for example, it's possible to only set `--max-file` on a container, which works because `json-file` is the default, but if the daemon configuration is changed, that will break the container (so upon a daemon restart / reload, containers won't come up again).

For now, it should really be: "container-config = daemon-config + container-config", where container-config overrides daemon options. But it should pick up the *current* daemon configuration, not the options that were set when the container was created (I think)

**Comment by mountkin** [comment]
>  I'm actually leaning towards not allowing --log-opt, unless a driver is specified on the same "level". 

@thaJeztah that will be a breaking change :smile:  I often use `--log-opt` without specifying `--log-driver`.

**Comment by thaJeztah** [comment]
> that will be a breaking change

Yes, I know, so probably not a change we can make. I also understand the convenience of just providing the options you want to change, but it would take all the "guesswork" out of it, and give a more predictable result.

File: daemon/daemon.go (hunk 1 above)
Comment (coolljt0725) [inline daemon/daemon.go]: I'm thinking if we can move this operation above  `if err := daemon.registerName(c);`? so if this operation failed, users has no chance to start it.

Comment (mountkin) [inline daemon/daemon.go]: @coolljt0725 the user can run `docker inspect` or `docker cp` commands with the container even if it can't be started.
If move it above `if err := daemon.registerName(c);` the container will disappear from the result of `docker ps`.

**Comment by LK4D4** [comment]
@mountkin @thaJeztah where we here? Should we move to design review?

**Comment by thaJeztah** [comment]
sorry for the delay; let's do this.

I tested this by creating a container, stopping the daemon, and editing the `hostconfig.json`, then starting the daemon again, it correctly set `json-file` in the `hostconfig.json`.

LGTM
