### PR TITLE
libnet: fix duplicated port mappings in overlay networks

### LINKED ISSUE #49719: Exposed ports duplicated (once for each network) after v28.0.1
### Description

Deployments of traefik using swarm with compose files have started listing exposed ports multiple times:

```
f26e20bbd476   traefik:v3.3.3                                                                                                           "/entrypoint.sh trae…"   3 hours ago    Up 3 hours (healthy)   0.0.0.0:8080->8080/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:8080-8081->8080-8081/tcp, 0.0.0.0:8081->8081/tcp, 0.0.0.0:8081->8081/tcp, 0.0.0.0:8081->8081/tcp, 0.0.0.0:8081->8081/tcp, 0.0.0.0:8081->8081/tcp, 0.0.0.0:8081->8081/tcp, 0.0.0.0:8081->8081/tcp, 0.0.0.0:8081-8082->8081-8082/tcp, 0.0.0.0:8082->8082/tcp, 0.0.0.0:8082->8082/tcp, 0.0.0.0:8082->8082/tcp, 0.0.0.0:8082->8082/tcp, 0.0.0.0:8082->8082/tcp, 0.0.0.0:8082->8082/tcp, 0.0.0.0:8082->8082/tcp, 80/tcp, 0.0.0.0:8082->8082/tcp   traefik_proxy.vf60zpagckmt9ucpt5fk54dg2.wjit0wsw4858ysuszs271v6cl
```

That service is on 8 networks and has 9 listings for 0.0.0.0:8080->8080/tcp and looking at other instances seems to indicate that each ports is listed (networks + 1) times.

The port expose itself is just:
```
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
```

This happens on docker 28.0.4, but does not seem to on 28.0.1.

### Reproduce

Create four networks:
```
docker network create --opt encrypted=true ingress1 --scope swarm --driver overlay
docker network create --opt encrypted=true ingress2 --scope swarm --driver overlay
docker network create --opt encrypted=true ingress3 --scope swarm --driver overlay
docker network create --opt encrypted=true ingress4 --scope swarm --driver overlay
```

Create this compose file as ubuntu-compose.yaml:
```
networks:
  ingress1:
    name: ingress1
    external: true
  ingress2:
    name: ingress2
    external: true
  ingress3:
    name: ingress3
    external: true
  ingress4:
    name: ingress4
    external: true
services:
  ubuntu:
    image: ubuntu:latest
    command: tail -f /dev/null
    user: '2000'
    read_only: true
    deploy:
      mode: global
      resources:
        limits:
          cpus: '1'
          memory: 125mb
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 8082
        published: 8082
        protocol: tcp
        mode: host
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    networks:
      - ingress1
      - ingress2
      - ingress3
      - ingress4
    volumes:
      - type: tmpfs
        target: /tmp
```
Four exposed ports and four networks.

Deploy with:
```
docker stack deploy --detach --compose-file ubuntu-compose.yaml ubuntu
```

And see what docker ps gives:
```
$ docker ps | grep ubuntu
6802a791c814   ubuntu:latest                                                                                                    "tail -f /dev/null"      About a minute ago   Up About a minute      0.0.0.0:80->80/tcp, 0.0.0.0:80->80/tcp, 0.0.0.0:80->80/tcp, 0.0.0.0:80->80/tcp, 0.0.0.0:80->80/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:8080-8081->8080-8081/tcp, 0.0.0.0:8081->8081/tcp, 0.0.0.0:8081->8081/tcp, 0.0.0.0:8081->8081/tcp, 0.0.0.0:8081-8082->8081-8082/tcp, 0.0.0.0:8082->8082/tcp, 0.0.0.0:8082->8082/tcp, 0.0.0.0:8082->8082/tcp, 0.0.0.0:8082->8082/tcp   ubuntu_ubuntu.vpfr195zccninfm1ts9kq1997.tiwm573d185uys3fe0pm6tnh5
$
```
Each exposed port listed networks+1 times.

### Expected behavior

Listed exposed ports should not contain duplicates:
```
$ docker ps | grep ubuntu
6802a791c814   ubuntu:latest                                                                                                    "tail -f /dev/null"      About a minute ago   Up About a minute      0.0.0.0:80->80/tcp, 0.0.0.0:8080-8082->8080-8082/tcp   ubuntu_ubuntu.vpfr195zccninfm1ts9kq1997.tiwm573d185uys3fe0pm6tnh5
$
```

Checking with v28.0.1 I see that docker does combine consecutive ports into a single range, so I would expect it to do that, but I'd expect it to do it correctly.

### docker version

```bash
Client: Docker Engine - Community
 Version:           28.0.4
 API version:       1.48
 Go version:        go1.23.7
 Git commit:        b8034c0
 Built:             Tue Mar 25 15:07:11 2025
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          28.0.4
  API version:      1.48 (minimum version 1.24)
  Go version:       go1.23.7
  Git commit:       6430e49
  Built:            Tue Mar 25 15:07:11 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.26
  GitCommit:        753481ec61c7c8955a23d6ff7bc8e4daed455734
 runc:
  Version:          1.2.5
  GitCommit:        v1.2.5-0-g59923ef
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    28.0.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.22.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.34.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 20
  Running: 20
  Paused: 0
  Stopped: 0
 Images: 21
 Server Version: 28.0.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: awslogs
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: active
  NodeID: vf60zpagckmt9ucpt5fk54dg2
  Is Manager: true
  ClusterID: m2bk72eebhonkdgm4tgwfs8sz
  Managers: 4
  Nodes: 4
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.71.1.97
  Manager Addresses:
   10.71.0.102:2377
   10.71.1.170:2377
   10.71.1.97:2377
   10.71.2.12:2377
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 753481ec61c7c8955a23d6ff7bc8e4daed455734
 runc version: v1.2.5-0-g59923ef
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
  no-new-privileges
 Kernel Version: 6.5.0-1024-aws
 Operating System: Ubuntu 22.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 30.81GiB
 Name: uat-swarm-01-node1
 ID: fdb089f5-46d7-466c-98c3-e7ca8d27cc29
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Registry Mirrors:
  http://srv-dev-build1.groupgti.net:5000/
 Live Restore Enabled: false
```

### Additional Info

Using the repro steps on:
```
Client: Docker Engine - Community
 Version:           28.0.1
 API version:       1.48
 Go version:        go1.23.6
 Git commit:        068a01e
 Built:             Wed Feb 26 10:41:12 2025
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          28.0.1
  API version:      1.48 (minimum version 1.24)
  Go version:       go1.23.6
  Git commit:       bbd0a17
  Built:            Wed Feb 26 10:41:12 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.25
  GitCommit:        bcc810d6b9066471b0b6fa75f557a15a1cbf31bb
 runc:
  Version:          1.2.4
  GitCommit:        v1.2.4-0-g6c52b3f
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
Gives the following output:
```
$ docker ps | grep ubuntu
c72f569173b4   ubuntu:latest                                                                       "tail -f /dev/null"      52 seconds ago   Up 10 seconds           0.0.0.0:180->180/tcp, 0.0.0.0:8180-8182->8180-8182/tcp                 ubuntu_ubuntu.cflqnznbrxeaipurej64gvfb3.x98gmut0hbo58xczrzouvn4na
$ 
```
Note that I had to change the ports because they were in use on the only 28.0.1 swarm I have, so I added 100 to each port number consistently.

### PR DESCRIPTION
**Pull request by akerouanton**
- Fixes moby/moby#49719

**- What I did**

Since commit f2a183a99, `getEndpointPortMapInfo` is called for all the endpoints of a container to get its complete list of port mappings. This is required as multiple endpoints might publish different ports (e.g. IPv4-only and IPv6-only endpoints mapping an IPv4 and an IPv6 port).

`getEndpointPortMapInfo` calls `(*Endpoint).DriverInfo()` which has a dodgy behavior: if the endpoint is part of a sandbox that also has an endpoint for the `docker_gwbridge` network, then `(*Endpoint).DriverInfo()` returns the DriverInfo of that `docker_gwbridge` endpoint in place of the current Endpoint's DriverInfo.

On overlay networks, host port-mappings are made through the `docker_gwbridge` network (which is automatically attached to all Swarm tasks). This results in duplicated port mappings reported for all Swarm containers.

Since `getEndpointPortMapInfo` is the only place where `(*Endpoint).DriverInfo()` is called, just remove that dodgy behavior.

`(*Endpoint).DriverInfo()` has an OS-specific implementation. Unlike the Linux implementation, on Windows, `DriverInfo()` returns the DriverInfo of the gateway endpoint _in addition_ to the current Endpoint's DriverInfo. So it shouldn't be affected by this bug -- don't touch it.

**- How to verify it**

A new integration test is added. This can also be verified manually with:

```
$ docker swarm init --advertise-addr=127.0.0.1:2377
$ docker network create -d overlay --scope swarm --attachable testnet1
$ docker service create --network testnet1 --name fooabr --publish=published=80,target=80,mode=host busybox top
$ docker ps
CONTAINER ID   IMAGE            COMMAND   CREATED         STATUS         PORTS                                                                      NAMES
6309cdab49d8   busybox:latest   "top"     7 seconds ago   Up 6 seconds   0.0.0.0:80->80/tcp, [::]:80->80/tcp, 0.0.0.0:80->80/tcp, [::]:80->80/tcp   fooabr.1.kmtim0i5nj0an5cjf7tca9eps
```

**- Human readable description for the release notes**

```markdown changelog
Fix a bug causing host port-mappings on Swarm containers to be duplicated on `docker ps` and `docker inspect`
```

### CODE REVIEW

**Review by robmry — APPROVED** [review]

File: integration/network/overlay/overlay_test.go [hunk 1]
```diff
@@ -47,3 +54,57 @@ func TestEndpointWithCustomIfname(t *testing.T) {
...
+		swarm.ServiceWithEndpoint(&swarmtypes.EndpointSpec{
+			Ports: []swarmtypes.PortConfig{
+				{Protocol: swarmtypes.PortConfigProtocolTCP, TargetPort: 80, PublishedPort: 80, PublishMode: swarmtypes.PortConfigPublishModeHost},
+			},
+		}))
+	defer apiClient.ServiceRemove(ctx, svcID)
+
+	poll.WaitOn(t, swarm.RunningTasksCount(ctx, apiClient, svcID, 1), swarm.ServicePoll)
+
+	ctrs, err := apiClient.ContainerList(ctx, containertypes.ListOptions{})
```
Comment (thaJeztah) [inline integration/network/overlay/overlay_test.go:92]: Should we filter this list by state (to be "running")? Not sure if likely, but swarm could create a task, and on failure, create a new one (leaving the old tasks / containers in "exited" state).

I was initially thinking; we could use `swarm.GetRunningTasks()` for this, but I don't think that gives us information about the ports that are mapped, so would require listing the tasks, then getting the container-iD from them to inspect the container.

Comment (akerouanton) [reply integration/network/overlay/overlay_test.go:92]: > Should we filter this list by state (to be "running")?

`ListOptions` is empty, so only running containers should already be returned.

File: integration/network/overlay/overlay_test.go [hunk 2]
```diff
@@ -47,3 +54,57 @@ func TestEndpointWithCustomIfname(t *testing.T) {
 	assert.NilError(t, err)
 	assert.Assert(t, strings.Contains(out.Stdout, ": foobar@if"), "expected ': foobar@if' in 'ip link show':\n%s", out.Stdout)
 }
+
+// TestHostPortMappings checks that, when a Swarm task has ports mappings in
+// host mode, the ContainerList API endpoint reports the right number of ports.
+//
+// Regression test for
```
Comment (akerouanton) [inline integration/network/overlay/overlay_test.go:61]: OH! The link to the original issue is missing 🙈

**Review by vvoland — APPROVED** [review]
