### PR TITLE
docker exec: fail early on exec create if specified user doesn't exist

### LINKED ISSUE #46903: Slow exec error when no /etc/group
### Description

Trying to exec into a container that doesn't have `/etc/group` shows an error but then just lingers there for 10 seconds:

### Reproduce

```console
root@b4f40d17b559:/go/src/github.com/docker/docker# ID=$(docker run -d docker/desktop-kubernetes-pause:3.7)
Unable to find image 'docker/desktop-kubernetes-pause:3.7' locally
3.7: Pulling from docker/desktop-kubernetes-pause
aff472d3f83e: Download complete
Digest: sha256:bb6ed397957e9ca7c65ada0db5c5d1c707c9c8afc80a94acbe69f3ae76988f0c
Status: Downloaded newer image for docker/desktop-kubernetes-pause:3.7
root@b4f40d17b559:/go/src/github.com/docker/docker# docker ps
CONTAINER ID   IMAGE                                 COMMAND    CREATED         STATUS         PORTS     NAMES
d005f8037c37   docker/desktop-kubernetes-pause:3.7   "/pause"   5 seconds ago   Up 5 seconds             musing_meninsky
root@b4f40d17b559:/go/src/github.com/docker/docker# time docker exec -it -u 0:root $ID /bin/sh
unable to find group root: no matching entries in group file


real    0m10.046s
user    0m0.025s
sys     0m0.018s
```

### Expected behavior

Expected more something like this:

```console
root@b4f40d17b559:/go/src/github.com/docker/docker# ID=$(docker run -d docker/desktop-kubernetes-pause:3.7)^C
root@b4f40d17b559:/go/src/github.com/docker/docker# docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
root@b4f40d17b559:/go/src/github.com/docker/docker# ID=$(docker run -d docker/desktop-kubernetes-pause:3.7)
root@b4f40d17b559:/go/src/github.com/docker/docker# time docker exec -it $ID /bin/sh
unable to find group root: no matching entries in group file

real    0m0.067s
user    0m0.017s
sys     0m0.011s
```

### docker version

```bash
master
```

### docker info

```bash
master
```

### PR DESCRIPTION
**Pull request by thaJeztah**
- fixes https://github.com/moby/moby/issues/46903

Before this patch, and error would be produced when starting the exec, but the CLI would wait for the exec to complete, timing out after 10 seconds (default). With this change, an error is returned immediately when creating the exec.

Note that "technically" this check may have some TOCTOU issues, because '/etc/passwd' and '/etc/groups' may be mutated by the container in between creating the exec and starting it.

This is very likely a corner-case, but something we can consider changing in future (either allow creating an invalid exec, and checking before starting, or checking both before create and before start).

With this patch:

```bash
printf 'FROM alpine\nRUN rm -f /etc/group' | docker build -t nogroup -
ID=$(docker run -dit nogroup)

time docker exec -u 0:root $ID echo hello
Error response from daemon: unable to find group root: no matching entries in group file

real	0m0.014s
user	0m0.010s
sys	0m0.003s

# numericc uid/gid (should not require lookup);
time docker exec -u 0:0 $ID echo hello
hello

real	0m0.059s
user	0m0.007s
sys	0m0.008s

# no user specified (should not require lookup);
time docker exec $ID echo hello
hello

real	0m0.057s
user	0m0.013s
sys	0m0.008s

docker rm -fv $ID

# container that does have a valid /etc/groups

ID=$(docker run -dit alpine)
time docker exec -u 0:root $ID echo hello
hello

real	0m0.063s
user	0m0.010s
sys	0m0.009s

# non-existing user or group
time docker exec -u 0:blabla $ID echo hello
Error response from daemon: unable to find group blabla: no matching entries in group file

real	0m0.013s
user	0m0.004s
sys	0m0.009s

docker rm -fv $ID
```

**- What I did**

**- How I did it**

**- How to verify it**

**- Human readable description for the release notes**

```markdown changelog
Fix `docker exec` waiting for 10 seconds if a non-existing user or group was specified.
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by vvoland — APPROVED** [review]
LGTM

File: integration/container/exec_test.go [hunk 1]
```diff
@@ -280,12 +282,128 @@ func TestExecUser(t *testing.T) {
 	ctx := setupTest(t)
 	apiClient := testEnv.APIClient()
 
-	cID := container.Run(ctx, t, apiClient, container.WithTty(true), container.WithUser("1:1"))
+	ctrOpts := []func(*container.TestContainerConfig){
+		container.WithTty(true),
+		container.WithUser("1:1"),
+	}
+	withoutEtcGroups := container.WithImage(build.Do(ctx, t, apiClient, fakecontext.New(t, "", fakecontext.WithDockerfile("FROM busybox\nRUN rm /etc/group"))))
+	withoutEtcPasswd := container.WithImage(build.Do(ctx, t, apiClient, fakecontext.New(t, "", fakecontext.WithDockerfile("FROM busybox\nRUN rm /etc/passwd"))))
```
Comment (thaJeztah) [inline integration/container/exec_test.go:290]: I should point out that I had some fun with this part; if I tried to make these tests run without building an image (so running a container with `sh -c 'rm /etc/passwd && top'` as command), the test didn't fail as expected. I tried adding a `sync` in between to see if it was possibly that changes weren't written to disk, but that didn't work either. So ... something odd.

Trying to run the same scenario manually didn't reproduce that issue.

```bash
cid=$(docker run -dit --name foo busybox sh -c 'rm /etc/passwd && top') \
 && docker exec -it -u root:root $cid echo hello
```

So either it's something in how the tests runs, or there's some actual race somewhere. I decided not to continue looking into that, because failing to detect the problem would still cause the actual exec to fail (the new check is just an _extra_ check), but perhaps something to try to find what's happening.

**Comment by thaJeztah** [comment]
@dmcgowan ptal ❤️

**Review by dmcgowan — APPROVED** [review]
