### PR TITLE
Add `--force` in `docker volume rm` to fix out-of-band volume driver deletion

### LINKED ISSUE #23367: Out-of-band volume driver deletions prevents recreation of volume
We are using flocker storage driver to manage our volumes across multiple docker hosts. When deleting a volume out-of-band from a docker daemon (which is very common when there are multiple docker hosts using centralized storage driver), then any docker daemon which did not witness the deletion will fail to re-create the volume using the same name. It seems to be that docker daemon is keeping some internal in-memory cache of the state of the volumes, which becomes inconsistent when a volume is deleted from a different docker host.

**Output of `docker version`:**

```
# docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64```
```

**Output of `docker info`:**

```
Containers: 11
 Running: 1
 Paused: 0
 Stopped: 10
Images: 1477
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-202:1-272855-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 21.47 GB
 Backing Filesystem: ext4
 Data file: /dev/vg-docker/data
 Metadata file: /dev/vg-docker/metadata
 Data Space Used: 15.36 GB
 Data Space Total: 47.24 GB
 Data Space Available: 31.89 GB
 Metadata Space Used: 58.39 MB
 Metadata Space Total: 4.295 GB
 Metadata Space Available: 4.237 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Logging Driver: syslog
Plugins:
 Volume: local flocker
 Network: bridge null host
Kernel Version: 3.13.0-48-generic
Operating System: Ubuntu 14.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859 GiB
Name: ip-172-31-250-185
ID: RUXL:5HW4:ASAS:6XK5:TX6A:L5R2:GAGO:OIJO:WD4X:JCF6:BLVL:7LGE
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS
flocker

**Steps to reproduce the issue:**
You do not actually need multiple docker hosts to reproduce the issue. If the storage driver supports it, simply remove the volume out of band, then try to recreate the volume using the same name:

1. docker volume create -d flocker --name jesse
2. HTTP DELETE http://flocker_ip/v1/configuration/datasets/dataset_id
3. docker volume ls (volume will not be shown in list)
4. docker volume create -d flocker --name jesse

**Describe the results you received:**

Step 4 fails to create the volume. 

If docker-daemon is restarted, then step 4 will succeed.
If step 2 is modified to remove the volume in-band (i.e. replace step 2 with 'docker volume rm jesse'), then step 4 succeeds.

**Describe the results you expected:**

In a distributed environment involving multiple docker daemons, an out-of-band volume deletion (from the perspective of a single docker-daemon) is very common. The result of this bug is that some hosts will be able to recreate the volume (those which never seen the volume from 'docker volume ls'), whereas other hosts will be unable to recreate the volume (since from their perspective, the volume disappears from underneath the daemon)

**Additional information you deem important (e.g. issue happens only occasionally):**

Issue is 100% reproducible.

### PR DESCRIPTION
**Pull request by yongtang**
**\- What I did**
This fix tries to address the issue in raised #23367 where an out-of-band volume driver deletion leaves some data in docker. This prevent the reuse of deleted volume names (by out-of-band volume driver like flocker).

**\- How I did it**

This fix adds a `--force` flag in `docker volume rm` to forcefully purge the data of the volume that has already been deleted.
Related documentations have been updated.

**\- How to verify it**

This fix is tested manually with flocker, as is specified in #23367.

**\- Description for the changelog**

Add a `--force` flag in `docker volume rm` to forcefully purge the data of the volume that has already been deleted.

**\- A picture of a cute animal (not mandatory but encouraged)**

This fix fixes #23367.

Signed-off-by: Yong Tang yong.tang.github@outlook.com

### CODE REVIEW

File: integration-cli/docker_cli_volume_test.go [hunk 1]
```diff
@@ -299,3 +299,15 @@ func (s *DockerSuite) TestVolumeCliCreateLabelMultiple(c *check.C) {
 		c.Assert(strings.TrimSpace(out), check.Equals, v)
 	}
 }
+
+func (s *DockerSuite) TestVolumeCliRmForce(c *check.C) {
```
Comment (cpuguy83) [inline integration-cli/docker_cli_volume_test.go]: Maybe in a separate test (as it requires `SameHostDeamon`) you can create a volume, manually remove it from `<docker root>/volumes/<id>`, then `docker volume rm -f` it.

File: volume/store/store.go [hunk 2]
```diff
@@ -104,7 +104,7 @@ func (s *VolumeStore) setNamed(v volume.Volume, ref string) {
 	s.globalLock.Unlock()
 }
 
-func (s *VolumeStore) purge(name string) {
+func (s *VolumeStore) Purge(name string) {
```
Comment (cpuguy83) [inline volume/store/store.go]: I think instead of doing this, in the `Remove` function, we should just check if `force` is set, and go ahead and run `purge` if so regardless of error from the driver.

WDYT?

Comment (yongtang) [inline volume/store/store.go]: @cpuguy83 Thanks. That makes sense. Let me update the pull request.

File: integration-cli/docker_cli_volume_test.go (hunk 1 above)
Comment (yongtang) [inline integration-cli/docker_cli_volume_test.go]: Thanks @cpuguy83. I was wondering about how to write a test case for the scenario before. Let me update the pull request to add the suggested test.

**Comment by jessesuen** [comment]
Will this help in the situation where the docker daemon gets into a confused state? Can you force delete a volume that does not show up from the output of `docker volume ls`?

**Comment by cpuguy83** [comment]
@jessesuen That's the idea. `--force` would make sure docker doesn't have any internal state for that volume.

**Comment by jessesuen** [comment]
Isn't this only treating the symptom and not the underlying problem? Adding a force option allows us to recover from the situation which is nice, but the general usage for recreating a volume is still not ideal. Basically, every time we want to create a volume on a docker host in a cluster (who's internal state may or may not be consistent), we have to follow these sequence of steps:

1) docker volume create -d flocker -name volname
2) docker volume ls
3) does my volume appear in the output of step 2?
4) if no, docker volume rm -f volname, docker volume create -d flocker -name volname

It seems that the `docker volume create` itself should somehow be validating this since after step #1, it currently indicates successful volume creation without actually creating the volume. That, IMO, is the real issue. A --force option just lets us recover from that issue but we should be trying to prevent the need of a force option in the first place.

**Comment by cpuguy83** [comment]
@jessesuen These are separate concerns.

**Comment by yongtang** [comment]
@cpuguy83 @jessesuen The pull request has been updated. Please let me know if there are any issues.

**Comment by yongtang** [comment]
@jessesuen Currently the behavior of `docker volume create` is, if volume already exist, the `docker volume create` will silently success.

On the other hand, volume plugins are provided not in docker itself so whether or not a volume exists depends on the volume plugin.

I noticed that `/VolumeDriver.Get` and `/VolumeDriver.List` have not been added until 1.10.0 so it might be an issue for drivers written for old version of docker.

I haven't had a chance to look into the details of flocker but when I installed flocker on AWS with the default settings, I could see flocker is trying to send v1.15 remote API requests.

Overall I also think `docker volume create` is a separate issue. Will spend some time to investigate further.

**Comment by yongtang** [comment]
All tests passed. The only failure is due to the vendor/engine-api. Will create a pull request to engine-api if design review is passed.

**Comment by thaJeztah** [comment]
we're good with this from a design perspective

**Comment by yongtang** [comment]
Thanks @thaJeztah @cpuguy83 a pull request in engine-api has been opened:
https://github.com/docker/engine-api/pull/321
Please let me know if there are any issues.

**Comment by thaJeztah** [comment]
https://github.com/docker/engine-api/pull/321 was merged, so you can update the vendored files

**Comment by yongtang** [comment]
Thanks @thaJeztah @cpuguy83 the pull request has been updated with engine-api revendorded. Please take a look and let me know if there are any issues.

**Comment by yongtang** [comment]
It looks that I previously updated the documentation on v1.24, not v1.25. So just updated the pull request to change the documentation on v1.25 instead.

**Comment by thaJeztah** [comment]
> So just updated the pull request to change the documentation on v1.25 instead.

Awesome, thanks!

File: daemon/delete.go [hunk 3]
```diff
@@ -139,7 +139,16 @@ func (daemon *Daemon) cleanupContainer(container *container.Container, forceRemo
 // VolumeRm removes the volume with the given name.
 // If the volume is referenced by a container it is not removed
 // This is called directly from the remote API
-func (daemon *Daemon) VolumeRm(name string) error {
+func (daemon *Daemon) VolumeRm(name string, force bool) error {
+	err := daemon.volumeRm(name)
+	if force {
```
Comment (yongtang) [inline daemon/delete.go]: Thanks @cpuguy83 the pull request has been updated.

File: integration-cli/docker_cli_volume_test.go [hunk 4]
```diff
@@ -344,3 +345,43 @@ func (s *DockerSuite) TestVolumeCliCreateLabelMultiple(c *check.C) {
...
+	testRequires(c, SameHostDaemon, DaemonIsLinux)
+
+	name := "test"
+	out, _ := dockerCmd(c, "volume", "create", "--name", name)
+	id := strings.TrimSpace(out)
+	c.Assert(id, checker.Equals, name)
+
+	root := ""
+	out, _ = dockerCmd(c, "info")
```
Comment (cpuguy83) [inline integration-cli/docker_cli_volume_test.go]: Should be able to get the path of the volume from `volume inspect`

Comment (yongtang) [inline integration-cli/docker_cli_volume_test.go]: Thanks @cpuguy83. The pull request has been updated to use `volume inspect`.

**Comment by cpuguy83** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM :cat: 
Moving to docs-review

File: docs/reference/api/docker_remote_api.md [hunk 5]
```diff
@@ -117,6 +117,7 @@ This section lists each version from latest to oldest.  Each listing includes a
 [Docker Remote API v1.25](docker_remote_api_v1.25.md) documentation
 
 * `POST /containers/create` now takes `AutoRemove` in HostConfig, to enable auto-removal of the container on daemon side when the container's process exits.
+* `DELETE /volume/{name:.*}` now support `force` query parameter.
```
Comment (thaJeztah) [inline docs/reference/api/docker_remote_api.md]: Perhaps; (please check if I describe the use-case correctly)
```Markdown
* `DELETE /volumes/(name)` now accepts a `force` query parameter to force removal 
  of volumes that were already removed out of bound by the volume driver plugin.
```

File: docs/reference/commandline/volume_rm.md [hunk 6]
```diff
@@ -19,6 +19,7 @@ Aliases:
   rm, remove
 
 Options:
+  -f, --force   Force the removal of one or more volumes
```
Comment (thaJeztah) [inline docs/reference/commandline/volume_rm.md]: There's one space too many before `Force` here

File: docs/reference/api/docker_remote_api.md (hunk 5 above)
Comment (yongtang) [inline docs/reference/api/docker_remote_api.md]: Thanks @thaJeztah. Let me take a look and update the PR shortly.

File: docs/reference/commandline/volume_rm.md (hunk 6 above)
Comment (yongtang) [inline docs/reference/commandline/volume_rm.md]: Thanks. Didn't notice the misalignment with the following line `--help` before. Just updated the pull request.

**Comment by vdemeester** [comment]
@yongtang needs a rebase :angel: (probably something about `engine-api` vendoring :stuck_out_tongue_closed_eyes: )

File: docs/reference/commandline/volume_rm.md [hunk 7]
```diff
@@ -19,6 +19,7 @@ Aliases:
   rm, remove
```
Comment (thaJeztah) [inline docs/reference/commandline/volume_rm.md]: the "Usage" above needs to be updated now that we have options;

```Markdown
Usage:  docker volume rm [OPTIONS] VOLUME [VOLUME...]
```

**Comment by thaJeztah** [comment]
One nit for docs, but docs LGTM otherwise.

@yongtang do you also want to take care of the completion scripts? Or want that to be handled in a separate PR? Think these are the locations to add the flag;

- https://github.com/docker/docker/blob/master/contrib/completion/bash/docker#L2856
- https://github.com/docker/docker/blob/master/contrib/completion/zsh/_docker#L1360-L1364

**Comment by yongtang** [comment]
Thanks @thaJeztah. The documentation has been updated. I also tried to address the zsh and bash completion. Please let me know if there are any issues.

**Comment by thaJeztah** [comment]
thanks, LGTM

ping @vdemeester docs LGTY?

**Comment by vdemeester** [comment]
docs LGTM 👼
