### PR TITLE
Fix volume creates blocked by stale cache entries

### LINKED ISSUE #26831: Change Error message when volume already exist  while docker volume create
**Description**
I am creating new volume with same name and volume with same name is already exist.
and both volume names are with different. Its expected that we should get an error.
We just need small change in error message as per https://docs.docker.com/engine/reference/commandline/volume_create/

Steps to reproduce the issue:
1. Create volume no. 1 with below command 
   docker volume create --name hello
2. Create volume no. 2 with below command with same name just driver name is different 
docker volume create -d test --name hello

Describe the results you received:
We got below error message:
Error response from daemon: A volume named hello already exists. Choose a different volume name.

Describe the results you expected::
We expect error message with given link https://docs.docker.com/engine/reference/commandline/volume_create/
A volume named  "hello"  already exists with the "test" driver. Choose a different volume name.

**Additional information you deem important (e.g. issue happens only occasionally):**
I had tested same behaviour on docker version 1.9 and it seems that it worked fine.
I got below error message with docker version 1.9
Error response from daemon: A volume name hello already exists with the local driver. Choose a different volume name.

**Output of `docker version`:**
[root@datta-bastion cloud-user]# docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

**Output of `docker info`:**
[root@datta-bastion cloud-user]# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-253:1-378284-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 184 MB
 Data Space Total: 107.4 GB
 Data Space Available: 47.68 GB
 Metadata Space Used: 782.3 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.797 GiB
Name: datta-bastion
ID: VDFM:RUJF:JEEI:J3OT:N4RX:FQ4H:DKZZ:JYVG:DCM4:QIN5:REED:EZF3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VM on openstack, AWS
uname -r
3.10.0-327.22.2.el7.x86_64
hostnamectl | grep System
  Operating System: CentOS Linux 7 (Core)

### PR DESCRIPTION
**Pull request by cpuguy83**
- fixes https://github.com/moby/moby/issues/26831

When a conflict is found in the volume cache, check with the driver if that volume still actually exists. If the volume doesn't exist, purge it from the cache and allow the create to happen.

Carry of #24205

### CODE REVIEW

**Comment by cpuguy83** [comment]
Burn in hell janky... DCO is properly signed on said commit `Signed-off-by: Wentao Zhang <zhangwentao234@huawei.com>`

**Comment by ssuvasanth** [comment]
@cpuguy83 Everything is fine except that any driver should be allowed to re-create the volume. The condition fails if the same volume driver tries to create the volume again.
I have made the changes. Please review #27177 if it is fine.

**Comment by ssuvasanth** [comment]
@cpuguy83 The fix needs to allow the same volume driver to re-create the volume with the same name.

**Comment by cpuguy83** [comment]
Ok, this is all fixed up.

**Comment by thaJeztah** [comment]
@anusha-ragunathan could you have a look at this one?

**Comment by crosbymichael** [comment]
LGTM

File: volume/store/store.go [hunk 1]
```diff
@@ -251,6 +252,72 @@ func (s *VolumeStore) Create(name, driverName string, opts, labels map[string]st
...
+// particularly around locking the store.
+// TODO(cpuguy83): With v2 plugins this shouldn't be a problem. Could also potentially
+// use a connect timeout for this kind of check to ensure we aren't blocking for a
+// long time.
+func (s *VolumeStore) checkConflict(name, driverName string) (volume.Volume, error) {
+	// check the local cache
+	v, _ := s.getNamed(name)
+	if v != nil {
+		vDriverName := v.DriverName()
+		if driverName != "" && vDriverName != driverName {
```
Comment (anusha-ragunathan) [inline volume/store/store.go]: `driverName` should be non-empty for this function, else error out. This should be checked before entering the loop.

File: volume/store/store.go [hunk 2]
```diff
@@ -251,6 +252,72 @@ func (s *VolumeStore) Create(name, driverName string, opts, labels map[string]st
...
+				// TODO(cpuguy83): maybe when when v2 plugins are ubiquitous, we should
+				// just purge this from the cache
+				return nil, errors.Wrapf(errNameConflict, "found reference to volume '%s' in driver '%s', but got an error while checking the driver: %v", name, vDriverName, err)
+			}
+
+			// now check if it still exists in the driver
+			v2, err := vd.Get(name)
+			err = errors.Cause(err)
+			if err != nil {
+				if _, ok := err.(net.Error); ok {
```
Comment (cpuguy83) [inline volume/store/store.go]: Because the driver may return an error if it so desires. So we check if a volume was returned or not.
We don't have a way to differentiate an error like `no such volume` vs `some junk happened`.

File: volume/store/store.go (hunk 1 above)
Comment (cpuguy83) [inline volume/store/store.go]: `Create` can have an empty driver name. This is not really an error, just that we don't have anything to compare with.
We could (and probably should but can't right now) check with all existing drivers if the volume still exists.

File: volume/volume.go [hunk 3]
```diff
@@ -270,7 +270,6 @@ func ParseMountSpec(cfg mounttypes.Mount, options ...func(*validateOpts)) (*Moun
 		}
 		mp.CopyData = DefaultCopyMode
 
-		mp.Driver = DefaultDriverName
```
Comment (anusha-ragunathan) [inline volume/volume.go]: Why is this removed? Where is `mp.Driver` set anymore?

Comment (cpuguy83) [inline volume/volume.go]: It must be removed otherwise we end up with "local" set when we don't want it to be.
It gets set after volume creation using `v.DriverName()`

File: volume/store/store.go [hunk 4]
```diff
@@ -251,6 +252,72 @@ func (s *VolumeStore) Create(name, driverName string, opts, labels map[string]st
...
+		}
+		return v, nil
+	}
+
+	return nil, nil
+}
+
 // create asks the given driver to create a volume with the name/opts.
 // If a volume with the name is already known, it will ask the stored driver for the volume.
 // If the passed in driver name does not match the driver name which is stored for the given volume name, an error is returned.
```
Comment (anusha-ragunathan) [inline volume/store/store.go]: nit: this comment needs an update.

File: volume/store/store.go [hunk 5]
```diff
@@ -251,6 +252,72 @@ func (s *VolumeStore) Create(name, driverName string, opts, labels map[string]st
...
+
+				// a driver can return whatever it wants, so let's make sure this is nil
+				if v2 == nil {
+					// purge this reference from the cache
+					s.Purge(name)
+					return nil, nil
+				}
+			}
+			if v2 != nil {
+				return nil, errors.Wrapf(errNameConflict, "driver '%s' already has volume '%s' - %s", vDriverName, name, driverName)
```
Comment (anusha-ragunathan) [inline volume/store/store.go]: nit: Can be the same error as L278 and leave out `driverName`

File: volume/store/store.go [hunk 6]
```diff
@@ -251,6 +252,72 @@ func (s *VolumeStore) Create(name, driverName string, opts, labels map[string]st
...
+func (s *VolumeStore) checkConflict(name, driverName string) (volume.Volume, error) {
+	// check the local cache
+	v, _ := s.getNamed(name)
+	if v != nil {
+		vDriverName := v.DriverName()
+		if driverName != "" && vDriverName != driverName {
+			// we have what looks like a conflict
+			// let's see if there are existing refs to this volume, if so we don't need
+			// to go any further since we can assume the volume is legit.
+			if len(s.refs[name]) > 0 {
```
Comment (anusha-ragunathan) [inline volume/store/store.go]: lock?

Comment (cpuguy83) [inline volume/store/store.go]: This would already be locked somewhere up the stack.

**Comment by cpuguy83** [comment]
Updated

File: volume/store/store.go [hunk 7]
```diff
@@ -117,6 +118,15 @@ func (s *VolumeStore) setNamed(v volume.Volume, ref string) {
 	s.globalLock.Unlock()
 }
 
+// getRefs gets the list of refs for a given name
+// Callers of this function are expected to hold the name lock.
+func (s *volumeStore) getRefs(name string) []string {
```
Comment (anusha-ragunathan) [inline volume/store/store.go]: volumeStore should be `VolumeStore`

Comment (thaJeztah) [inline volume/store/store.go]: Looks like it was updated :)

**Comment by anusha-ragunathan** [comment]
LGTM
