### PR TITLE
Fix the since and before filter behavior

### LINKED ISSUE #20087: `ps -f before=`  vs  `ps -f since=`
Hi all,

`$docker ps -f since=` shows a result with and without `-a`, Next to this, after trying `$docker ps -f before=box`, I got nothing, but this query works with `-a`; `$docker ps -af before=box`. So while I use `since`  with two options, why I cannot use `before` without `-a`? or  does `since` have bad behavior by providing both cases?  

How reproducible:
```
$ docker ps -a
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                      PORTS               NAMES
aa99c1c1e96b        ubuntu:14.04              "bash"                   3 hours ago         Exited (0) 3 hours ago                          jolly_ritchie
8c6bd18f842e        busybox:latest            "sleep 100"              4 hours ago         Exited (143) 4 hours ago                        box
168cbe37008c        mongo:3.2                 "/entrypoint.sh mongo"   2 days ago          Exited (137) 30 hours ago   27017/tcp           mongo
1c60d589fcf6        centurylink/image-graph   "/usr/src/app/image-g"   4 days ago          Exited (137) 4 days ago                         happy_leavitt
b76fb791a1df        dockerui/dockerui         "/dockerui"              5 days ago          Exited (2) 4 days ago                           compassionate_bell

$ docker ps -f since=box
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                   PORTS               NAMES
aa99c1c1e96b        ubuntu:14.04        "bash"              3 hours ago         Exited (0) 3 hours ago                       jolly_ritchie

$ docker ps -af since=box
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                   PORTS               NAMES
aa99c1c1e96b        ubuntu:14.04        "bash"              3 hours ago         Exited (0) 3 hours ago                       jolly_ritchie

$ docker ps -f before=box
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

$ docker ps -af before=box
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                      PORTS               NAMES
168cbe37008c        mongo:3.2                 "/entrypoint.sh mongo"   2 days ago          Exited (137) 30 hours ago   27017/tcp           mongo
1c60d589fcf6        centurylink/image-graph   "/usr/src/app/image-g"   4 days ago          Exited (137) 4 days ago                         happy_leavitt
b76fb791a1df        dockerui/dockerui         "/dockerui"              5 days ago          Exited (2) 4 days ago                           compassionate_bell

```

`docker version`:
```
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:18:11 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 19:55:25 2016
 OS/Arch:      linux/amd64
```

`docker info`:
```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 103
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 122
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 4.1.17-boot2docker
Operating System: Boot2Docker 1.10.0 (TCL 6.4.1); master : b09ed60 - Thu Feb  4 20:16:08 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.2 MiB
Name: kodcu
ID: 32KK:K7BX:D2KV:SXYC:N65U:2FBX:IUQD:U24R:NBYR:EEV4:BBPU:Y66D
Debug mode (server): true
 File Descriptors: 10
 Goroutines: 22
 System Time: 2016-02-07T14:20:50.732065775Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: 
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

### PR DESCRIPTION
**Pull request by vdemeester**
Filters should not include stopped container if `-a` is not specified.
Right now, before and since filter are acting as `--before` and `--since` deprecated flags. This commit is fixing that. 🐙

There is some edge cases when using both of them at the same time.
- Should `--before=foo -f before=bar` be allowed or should one take over the other ? 
  With the changes of this PR, `--before=foo -f before=bar` is acting weird, but as `--before` is deprecated, I was wondering if it made sense to handle these case of not.
- If we do not cover these edge cases, we should decide which one takes over the other (I'm all for the _filters_ to take over the deprecated flags), and warn about it.

/cc @thaJeztah @calavera @icecrime @tiborvass @runcom 

- Fixes #20087
- Updates https://github.com/moby/moby/pull/17718

🐸

Signed-off-by: Vincent Demeester vincent@sbr.pm

### CODE REVIEW

File: daemon/list.go [hunk 1]
```diff
@@ -182,15 +192,17 @@ func (daemon *Daemon) foldFilter(config *types.ContainerListOptions) (*listConte
 		})
 	}
 
-	if config.Before != "" && beforeContFilter == nil {
```
Comment (vdemeester) [inline daemon/list.go]: This is what makes `-f before=bar` taking over `--before=bar`.

**Comment by thaJeztah** [comment]
> If we do not cover these edge cases, we should decide which one takes over the other (I'm all for the filters to take over the deprecated flags), and warn about it.

Yup, I think that makes sense; no need to allow people to combine them

**Comment by runcom** [comment]
> If we do not cover these edge cases, we should decide which one takes over the other (I'm all for the filters to take over the deprecated flags), and warn about it.
> Yup, I think that makes sense; no need to allow people to combine them

same for me, no need for both

**Comment by calavera** [comment]
> I'm all for the filters to take over the deprecated flags

Agreed

**Comment by calavera** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM @calavera I don't see why we wouldn't want this for 1.10.1

**Comment by vdemeester** [comment]
@calavera @tiborvass Right now, filters don't take over though. I would have to update the condition.

@tiborvass if we want this for `v1.10.1`, I should do the change against the release branch, right ? :angel:

**Comment by tiborvass** [comment]
@vdemeester We'll see, i'm cherrypicking things that were merged already and will open a bulk PR to the bump branch.

**Comment by thaJeztah** [comment]
I'm +1 for adding it to 1.10.1 (per https://github.com/docker/docker/issues/20087#issuecomment-181588964), but all ears if there's a reason to *not* include it

**Comment by vdemeester** [comment]
If the cherry-pick is ok, I'm +1 to 1.10.1 too :blush:.
