### PR TITLE
Send exec exit event on failures

### LINKED ISSUE #39427: "Ignoring Exit Event" Produces Confusion in Consumers (Kubernetes)
**Description**

Docker fails to exec container because the command does not exist. Docker does not send an exit event. That is probably wise... but we should send another event that describes failure such that consumers can perform some action.

See
https://github.com/docker/docker-ce/blob/master/components/engine/daemon/monitor.go#L144

In our use case our Kubernetes pod is stuck because it does not know to proceed restarting the container. It sits waiting forever in "PodInitializing" state.

**Steps to reproduce the issue:**
1. We run our Kubernetes manifest
2. Sometimes it fails (not sure why but think it amounts to order of containers booting)
3. Stuck in "PodInitializing" forever, we have one we saved that is many months old.

**Describe the results you received:**

Container runs, exits and does not produce an event through container monitor

**Describe the results you expected:**

Notifies other tooling of the fact the container failed to exec?

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
[rottaway@eksnode0007.usprz32.dd.company.com ~]$ sudo docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a215d7133c34aa18e3b72b4a21fd0c6136
 Built:             Mon Mar  4 21:25:41 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a/18.06.1-ce
  Built:            Mon Mar  4 21:27:07 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
[rottaway@eksnode0007.usprz32.dd.company.com ~]$ sudo docker info
Containers: 61
 Running: 38
 Paused: 0
 Stopped: 23
Images: 19
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.106-97.85.amzn2.x86_64
Operating System: Amazon Linux 2
OSType: linux
Architecture: x86_64
CPUs: 96
Total Memory: 369.8GiB
Name: eksnode0007.usprz32.pie.apple.com
ID: FDNB:MA75:O2O5:RHZS:WGZG:NZX6:6H5D:YVID:6LOB:FNHF:PPPM:6HRF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by crosbymichael**
Fixes #39427

This always sends the exec exit events even when the exec fails to find
the binary.  A standard 127 exit status is sent in this situation.

### Description for the changelog
Send exec exit event even then the exec fails to find the binary

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

File: daemon/monitor.go [hunk 1]
```diff
@@ -131,18 +132,14 @@ func (daemon *Daemon) ProcessEvent(id string, e libcontainerdtypes.EventType, ei
...
-			}
-			daemon.LogContainerEventWithAttributes(c, "exec_die", attributes)
-		} else {
-			logrus.WithFields(logrus.Fields{
-				"container": c.ID,
-				"exec-id":   ei.ProcessID,
-				"exec-pid":  ei.Pid,
-			}).Warn("Ignoring Exit Event, no such exec command found")
+
+			exitCode = ec
```
Comment (AkihiroSuda) [inline daemon/monitor.go]: nit: just `exitCode := int(ei.ExitCode)` and eliminate `ec`?

Comment (crosbymichael) [reply daemon/monitor.go]: no need to change this in this PR

**Review by AkihiroSuda — APPROVED** [review]
