### PR TITLE
Detect IPv6 support in containers, generate '/etc/hosts' accordingly.

### LINKED ISSUE #33099: 17.04 / 17.05: The disappearance of the link-local & loopback ipv6 addresses
**Description**

After upgrading to 17.04-ce or 17.05-ce, I no longer have a link-local ipv6 address by default (with ipv6 not enabled).

I think this might be an intentional change related to https://github.com/moby/moby/issues/20569, but I also think it's not entirely well thought out and is dangerously backwards incompatible.

Here's a simple [example](https://github.com/euank/kitchen-sink/tree/master/repros/docker-17-04-ipv6) of something that no longer works:

```go
func main() {
	conn, _ := net.Listen("tcp", ":8080")
	_, err := net.Dial("tcp", conn.Addr().String())
	if err != nil {
		fmt.Printf("did not expect error, but got: %v", err)
	}
}
```

The above program is available as `euank/ipv6-repro:latest`

The problem is that a program thinks ipv6 is available because it's enabled in my kernel, but docker has broken ipv6; it tries to listen on both (woo!), but unknowingly can't listen on ipv6 since docker tore it down when creating the netns. The program doesn't know that and will still happily think it's listening on both and `.Addr()` gives the ipv6 formatted address as a result.

Furthermore, if I *just* want a link local address (and don't want to allocate routable addresses), there's no way to configure the default bridge network to do so. Enabling ipv6 requires that I have a range of addresses to assign, but all I want is link-local addresses as we got by default before.

The workaround I've found is the following: `docker run --sysctl net.ipv6.conf.all.disable_ipv6=0 euank/ipv6-repro:latest`

**Steps to reproduce the issue:**

1. `docker run euank/ipv6-repro:latest`

2. `docker run busybox ip addr`

**Describe the results you received:**

1. `did not expect error, but got: dial tcp [::]:8080: connect: cannot assign requested address`

2.
    ```
    1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1
        link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
        inet 127.0.0.1/8 scope host lo
           valid_lft forever preferred_lft forever
    128: eth0@if129: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue 
        link/ether 02:42:ac:11:00:02 brd ff:ff:ff:ff:ff:ff
        inet 172.17.0.2/16 scope global eth0
           valid_lft forever preferred_lft forever
    ```

**Describe the results you expected:**

1. No error, as was true in previous versions of docker (1.12.x, 1.13, 17.03)

2.
    ```
    1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1
        link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
        inet 127.0.0.1/8 scope host lo
           valid_lft forever preferred_lft forever
        inet6 ::1/128 scope host 
           valid_lft forever preferred_lft forever
    128: eth0@if129: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue 
        link/ether 02:42:ac:11:00:02 brd ff:ff:ff:ff:ff:ff
        inet 172.17.0.2/16 scope global eth0
           valid_lft forever preferred_lft forever
        inet6 fe80::42:acff:fe11:2/64 scope link tentative 
           valid_lft forever preferred_lft forever
    ```
    
**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:14:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:14:18 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

Default fedora installation with ipv6 enabled on the host, config_ipv6 in the kernel, all that jazz.

### LINKED ISSUE #34070: dial udp [::1]:53: socket: operation not permitted
hi, 
i have one application, which can run pure ubuntu.
now I am moving this application into docker container, but when I run it, i got the below error:

```
dial tcp: lookup localhost on [::1]:53: dial udp [::1]:53: socket: operation not permitted.
```

could anyone give a little cue how to fix this issue?

below is the my docker and hardware information:

```bash
~# docker info
Containers: 16
 Running: 0
 Paused: 0
 Stopped: 16
Images: 1
Server Version: 1.12.6
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.65-dirty
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: aarch64
CPUs: 4
Total Memory: 7.727 GiB
Name: localhost
ID: LVMS:QC5N:2RDQ:EURF:VTQ7:NNOE:IQ6E:WN4G:ZLA3:WKSP:KILO:U2KH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 127.0.0.0/8
```

### LINKED ISSUE #35954: /etc/hosts contains IPv6 entries even when IPv6 is not enabled
**Description**

/etc/hosts contains IPv6 entries when IPv6 is not enabled in daemon.json

The container interfaces do not have IPv6 addresses assigned:
```
# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
5886: eth0@if5887: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:ac:11:00:03 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.3/16 scope global eth0
       valid_lft forever preferred_lft forever
```

**Steps to reproduce the issue:**

1. if enabled, disable IPv6 in daemon.json. By default, the Docker daemon configures the container network for IPv4 only.
2. `$ docker run debian:jessie cat /etc/hosts`

**Describe the results you received:**

```
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.17.0.3      1749a2a20d9e
```

**Describe the results you expected:**

```
127.0.0.1       localhost
172.17.0.3      1749a2a20d9e
```

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:57:21 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:19 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
$ docker info
Containers: 74
 Running: 21
 Paused: 0
 Stopped: 53
Images: 106
Server Version: 17.06.2-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.69-rancher
Operating System: RancherOS v1.1.2
OSType: linux
Architecture: x86_64
CPUs: 56
Total Memory: 251.8GiB
Name: REDACTED
ID: I6BI:SM5F:GFI3:DWLQ:6ARS:PL46:CINJ:CBEG:KKKL:RM52:NVO4:IKLH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 REDACTED
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running in RancherOS v1.1.2

### LINKED ISSUE #42748: IPv6 disabled when creating a container with network set to none
**Description**
Creating a docker-container with `--network=none` and ipv6 enabled in the docker daemon configuration will result in a container with ipv6 disabled.

**Steps to reproduce the issue:**
1. Enable ipv6 in docker configuration
```
{
    "ipv6": true,
    "fixed-cidr-v6": "fd00:ffff::/64",
}
```
2. docker run -it --network=none debian:latest /bin/bash
3. cat /proc/sys/net/ipv6/conf/all/disable_ipv6

**Describe the results you received:**
The  `disable_ipv6` is set to 1 and you cannot assign any IPv6 address to any interface created inside the container.

**Describe the results you expected:**
When having IPv6 enabled in the daemon configuration I would expect that a container with `network=none` nevertheless has IPv6 enabled inside the container.

**Use-Case**
I'm running a container which uses WireGuard as an internet uplink inside the container, as described here https://www.wireguard.com/netns/. Therefore, Docker doesn't need to create the default interface inside the docker-container, which can be disabled using `network=none`. However, I would like to assign an IPv6-address to the WireGuard interface which was moved to the network namespace of the docker-container. This isn't possible because IPv6 is disabled by default.

**Workaround**
It's possible to enable ipv6 using `echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6`, when the container is running privileged, which isn't always possible.

**Additional information you deem important (e.g. issue happens only occasionally):**
This behavior might be caused by this method call, which set `disable_ipv6` for the `all` configuration when the network sandbox is created: https://github.com/moby/moby/blob/master/libnetwork/osl/namespace_linux.go#L242

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:47 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.8
  GitCommit:        7eba5930496d9bbe375fdf71603e610ad737d2b2
 runc:
  Version:          1.0.0
  GitCommit:        v1.0.0-0-g84113ee
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 10
  Running: 1
  Paused: 0
  Stopped: 9
 Images: 21
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7eba5930496d9bbe375fdf71603e610ad737d2b2
 runc version: v1.0.0-0-g84113ee
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.10.0-0.bpo.7-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.933GiB
 Name: BA-GW-NS
 ID: HFOY:OUC6:ZZTU:ABTV:B4OJ:QHFE:AOVM:NXJ6:JH7D:GF4P:TVAG:U47S
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 35
  Goroutines: 46
  System Time: 2021-08-15T22:27:11.44505391+02:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### PR DESCRIPTION
**Pull request by robmry**
**- What I did**

Some configuration in a container depends on whether it has support for IPv6 (including default entries for `::1` etc in `/etc/hosts`).

Before this change, the container's support for IPv6 was determined by whether it was connected to any IPv6-enabled networks. But, that can change over time, it isn't a property of the container itself.

So, instead, detect IPv6 support by looking for `::1` on the container's loopback interface. That address will not be present if the kernel does not have IPv6 support, or the user has disabled it in new namespaces by other means. To disable IPv6 when creating a container, use `--sysctl net.ipv6.conf.all.disable_ipv6=1`.

This change uses the new approach to determining whether a container supports IPv6 to ensure that IPv6 entries are only included in '/etc/hosts' if IPv6 is enabled - which fixes #35954

This change is a start, further work is needed:
- Like 'hosts', 'resolv.conf' needs to be built according to this detected IPv6-ness.
- An endpoint for an IPv6 network, in a container with no IPv6 support, is allocated an IPv6 address.
  - That address won't show up on the container's interface to a network added when the container is created, but it will on interfaces to networks that are created later.
  - The address will be reserved for the lifetime of the container.
  - The internal resolver is populated with those IPv6 addreses, and will return them.
  - _Similarly, a container with IPv6 and a legacy-network `--link` to a non-IPv6 container will get that non-functional IPv6 address in its '/etc/hosts'._
- Check for more cases where the plumbing needs to change for this new way of detecting the IPv6 capability of a container.
- Check that docs describe the `--sysctl` as the way to disable IPv6 in a container.

**- How I did it**

The first commit here, written by @corhere, results in `Sandbox.SetKey()` being called after the daemon has created the container task. At that point, `sysctl` options have been applied, making it possible to use the existence of `::1` on the loopback interface to detect IPv6 support when the user provides sysctl `net.ipv6.conf.all.disable_ipv6` to explicitly enable or disable IPv6 when creating a container. (`SetKey()` will still be called from the prestart hook for buildkit, but it doesn't allow sysctl overrides.)

The second commit probes for `::1`, and uses the result to re-generate `/etc/hosts` accordingly.

The daemon no longer disables IPv6 on all interfaces during initialisation.  It now disables IPv6 only for interfaces that have not been assigned an IPv6 address:
- fixes #33099
- fixes #42748
- fixes #34070

**- How to verify it**

Updated unit tests, new integration test.

**- Description for the changelog**

By default, IPv6 will remain enabled on a container's loopback interface when the container is not connected to an IPv6-enabled network. So, for example, containers that are only connected to an IPv4-only network will now have the '::1' address on their loopback interface.

To disable IPv6 in a container, use option '--sysctl net.ipv6.conf.all.disable_ipv6=1' in the 'create' or 'run' command, or the equivalent 'sysctls' option in the service configuration section of a Compose file.

If IPv6 is not available in a container because it has been explicitly disabled for the container, the host's networking stack does not have IPv6 enabled, or for any other reason - the container's '/etc/hosts' file will not include IPv6 entries.

### CODE REVIEW

File: daemon/start.go [hunk 1]
```diff
@@ -224,6 +224,15 @@ func (daemon *Daemon) containerStart(ctx context.Context, daemonCfg *configStore
 		}
 	}()
 
+	// Finish sandbox initialisation (if there's a sandbox, so not using container networking).
+	if sb, err := daemon.netController.GetSandbox(container.ID); err == nil {
+		if err := sb.CtrTaskCreated(); err != nil {
+			log.G(ctx).WithError(err).WithField("container", container.ID).
+				Error("failed to complete network configuration")
+			return errors.Wrap(err, "failed to complete network configuration")
```
Comment (thaJeztah) [inline daemon/start.go:232]: We should probably return an appropriate `errdefs` error here (as we do for other errors returned). I guess this should be considered an internal server error (i.e., not a "user error"), in which case;


```suggestion
			return errdefs.System(errors.Wrap(err, "failed to complete network configuration"))
```

File: daemon/start.go [hunk 2]
```diff
@@ -224,6 +224,15 @@ func (daemon *Daemon) containerStart(ctx context.Context, daemonCfg *configStore
 		}
 	}()
 
+	// Finish sandbox initialisation (if there's a sandbox, so not using container networking).
+	if sb, err := daemon.netController.GetSandbox(container.ID); err == nil {
+		if err := sb.CtrTaskCreated(); err != nil {
+			log.G(ctx).WithError(err).WithField("container", container.ID).
+				Error("failed to complete network configuration")
```
Comment (thaJeztah) [inline daemon/start.go:231]: Small nit; not critical (and there's tons of locations where we have this), but there's some overhead when using multiple consecutive `WitField` / `WithError` / `WithFields`. As this is new code, perhaps use `WithFields` for this case;

```suggestion
			log.G(ctx).WithFields(log.Fields{
				"container": container.ID,
				"error":     err,
			}).Error("failed to complete network configuration")
```

File: integration/internal/container/ops.go [hunk 3]
```diff
@@ -46,6 +47,13 @@ func WithNetworkMode(mode string) func(*TestContainerConfig) {
 	}
 }
 
+// WithSysctls sets sysctl options for the container
+func WithSysctls(sysctls map[string]string) func(*TestContainerConfig) {
+	return func(c *TestContainerConfig) {
+		c.HostConfig.Sysctls = maps.Clone(sysctls)
```
Comment (thaJeztah) [inline integration/internal/container/ops.go:53]: Ah, nice! We should have a look for other cases where `maps.Clone` could be applied. I expect there's probably quite some places where we copy basic maps (`map[string]string` and the likes)

File: libnetwork/endpoint.go [hunk 4]
```diff
@@ -631,6 +621,27 @@ func (ep *Endpoint) UpdateDNSNames(dnsNames []string) error {
 	return nil
 }
 
+func (ep *Endpoint) updateHostsFile(sb *Sandbox) error {
+	ep.mu.Lock()
+	n := ep.network
+	ep.mu.Unlock()
```
Comment (thaJeztah) [inline libnetwork/endpoint.go:627]: It looks like these locks are new; I know there's a lot of "dubious" code either handling too many locks, or too little. While I do think that the signature is _nicer_ (encapsulating the locking), we should also consider that this function is not exported; for non-exported functions it's fine to specify additional requirements on callers (such as "caller must keep a lock").

- did we need the additional synchronisation here?
- I see the calling code (`sbJoin`) memoizes the network (has a local `n` variable); would passing the network as argument avoid needing the extra synchronisation?


I noitice that both `getFirstInterfaceIPv4Address` and `getFirstInterfaceIPv6Address` have locking, which in this case looks like it's actually adding complication (we must make sure to unlock before calling those), but ` sb.updateHostsFile` does not have any synchronisation.


Also, at a quick glance, `getFirstInterfaceIPv4Address` and `getFirstInterfaceIPv6Address` are not used anywhere  else (they're ONLY used here?)

If that's indeed the case, and looking at those functions, perhaps we should just inline them. We can also consider using an early return for the network-check;

```go
func (ep *Endpoint) updateHostsFile(sb *Sandbox) error {
	ep.mu.Lock()
	defer ep.mu.Unlock()

	// Do not update hosts file with internal network's endpoint IP
	if n := ep.network; n == nil || n.ingress || n.Name() == libnGWNetwork {
		return nil
	}

	var addresses []string
	if ep.iface.addr != nil {
		addresses = append(addresses, ep.iface.addr.String())
	}
	if ep.iface.addrv6 != nil {
		addresses = append(addresses, ep.iface.addrv6.String())
	}

	return sb.updateHostsFile(addresses)
}
```

**Review by thaJeztah — COMMENTED** [review]
just some quick comments (didn't finish reading all changes)

File: daemon/start.go (hunk 1 above)
Comment (robmry) [reply daemon/start.go:232]: The 'err' has been `errdefs.System()`'d by the time it gets here, in `Sandbox.ctrTaskCreatedDNS()`. The Wrap() was just to add a bit of context about what was going on at the time.

I did it that way thinking it might be best to leave the possibility of `CtrTaskCreated()` finding/returning a user/config error. (Maybe address allocation should happen at this point, after the IPv6-ness of the container is known. That might mean we can avoid allocating an IPv6 addresses from the pool if it won't be usable in case, for example, there's no address left in the pool. But, haven't thought that through properly yet, spitting the error out earlier for the common case where the container does have IPv6 might be best.)

So, could change it if you think that'd be best?

File: daemon/start.go (hunk 2 above)
Comment (robmry) [reply daemon/start.go:231]: Yes, will do ...

File: integration/internal/container/ops.go (hunk 3 above)
Comment (robmry) [reply integration/internal/container/ops.go:53]: Yes, I was quite pleased with that! I guess hunting-for / replacing other uses should be a separate change.

File: daemon/start.go (hunk 1 above)
Comment (thaJeztah) [reply daemon/start.go:232]: oh! if it's already typed, then I guess we don't need to; sorry missed that 😅

File: libnetwork/endpoint.go (hunk 4 above)
Comment (robmry) [reply libnetwork/endpoint.go]: I ended up getting rid of `Endpoint.updateHostsFile()` ...

Instead, a new `Endpoint.getEtcHostsAddrs()` acquires the lock and does the combination of now-deleted `getFirstInterfaceIPv4Address()` and `getFirstInterfaceIPv6Address()`.

Then, the two Sandbox callers use that result to call `Sandbox.updateHostsFile()`.

File: daemon/start.go [hunk 5]
```diff
@@ -224,6 +224,17 @@ func (daemon *Daemon) containerStart(ctx context.Context, daemonCfg *configStore
 		}
 	}()
 
+	// Finish sandbox initialisation (if there's a sandbox, so not using container networking).
```
Comment (corhere) [inline daemon/start.go:227]: Existence of a sandbox implies container networking, so the comment makes no sense as written. Did you mean to write this?
```suggestion
	// Finish sandbox initialisation (if there's a sandbox, so not using host networking).
```

File: libnetwork/osl/namespace_linux.go [hunk 6]
```diff
@@ -555,32 +555,25 @@ func (n *Namespace) Restore(interfaces map[Iface][]IfaceOption, routes []*types.
...
-	n.mu.Unlock()
-
-	if n.loV6Enabled == enable {
-		return
+// Enable IPv6 on the loopback interface, if possible.
+func (n *Namespace) enableLoV6() {
+	if err := setIPv6(n.path, "lo", true); err != nil {
+		log.G(context.TODO()).Warnf("Failed to enable IPv6 on loopback interface on network namespace %q: %v", n.path, err)
 	}
+}
```
Comment (corhere) [inline libnetwork/osl/namespace_linux.go:563]: Have you seen what `setIPv6()` does? It looks like all the `enableLoV6` function does is force the sysctl `net.ipv6.conf.lo.disable_ipv6=0` in the sandbox, overriding the user's wishes to `--sysctl net.ipv6.conf.lo.disable_ipv6=1`. Why does this function exist?

File: libnetwork/sandbox.go [hunk 7]
```diff
@@ -273,6 +276,12 @@ func (sb *Sandbox) Refresh(options ...SandboxOption) error {
 	return nil
 }
 
+// CtrTaskCreated is to be called after the container task has been created, before
+// it is started.
+func (sb *Sandbox) CtrTaskCreated() error {
+	return sb.ctrTaskCreatedDNS()
+}
```
Comment (corhere) [inline libnetwork/sandbox.go:283]: Please hang this stuff off the `SetKey` hook callback instead. It's the only way to hook into the container lifecycle in a way that is compatible with how we currently integrate with buildkit. Forget I ever opened #47052. I now realize it was a mistake as we can't actually make use of splitting create and start until #44385 is merged.

File: libnetwork/sandbox_dns_unix.go [hunk 8]
```diff
@@ -27,6 +29,35 @@ const (
...
+func (sb *Sandbox) ctrTaskCreatedDNS() error {
+	sb.mu.Lock()
+	osSbox := sb.osSbox
+	sb.mu.Unlock()
+
+	// Set Sandbox.ipv6Disabled according to whether the container's 'lo' interface
+	// has an IPv6 address ('::1' is assigned automatically, even when the container
+	// has no IPv6-enabled endpoints). There should be an osSbox, but default to
+	// ipv6Disabled=false if not.
+	if osSbox == nil {
```
Comment (corhere) [inline libnetwork/sandbox_dns_unix.go:44]: In which circumstances will `osSbox == nil`? Does that include `--net=host`? If so, should the host netns should be probed for IPv6-ness?

**Review by corhere — CHANGES_REQUESTED** [review]

File: daemon/start.go (hunk 5 above)
Comment (robmry) [reply daemon/start.go:227]: I do mean container networking ... in the comment I'm referring to the Sandbox object rather than the sandbox concept, perhaps that's caused the confusion - so I'll change the comment to "if there's a libnetwork.Sandbox ...", to make it less ambiguous.

But, the line of code it's commenting on calls `daemon.netController.GetSandbox(container.ID)` ... for host networking, that retrieves the host network's Sandbox. For container networking it returns nil, because there's no new Sandbox associated with the new container.

File: libnetwork/osl/namespace_linux.go (hunk 6 above)
Comment (robmry) [reply libnetwork/osl/namespace_linux.go:563]: Yes, I have seen what `setIPv6()` does - and no, it doesn't override the user's wishes.

`enableLoV6()` exists to make sure IPv6 is enabled in the container's namespace, if it can be enabled - as the comment you've highlighted explains. It is called during the SetKey(). The user's `--sysctl` is applied later.

After the user's sysctl has been applied, after the SetKey() round of initialisation has finished and before the container task is started, `IPv6LoEnabled()` is used to check the final state. Its comment says:

```
// IPv6LoEnabled checks whether the loopback interface has an IPv6 address ('::1'
// is assigned by the kernel if IPv6 is enabled). Namespace.enableLoV6() will try
// to enable it - but it will be disabled if, for example, IPv6 is not enabled in
// the kernel, or the container was started with "--sysctl
// net.ipv6.conf.all.disable_ipv6=1".
```

The new integration test verifies/demonstrates that the command line `--sysctl` does take effect.

You'll also see in the diff that `enableLoV6()` replaces `checkLoV6()` - which called `setIPv6()` to set `disable_ipv6` on `lo` depending on whether the network being connected had IPv6 enabled ... that's the behaviour we want to get away from - the container's IPv6-ness shouldn't depend on what it's connected to. So, this change makes the same `disable_ipv6` update as before, but now it's unconditionally set to `0`.

File: libnetwork/sandbox.go (hunk 7 above)
Comment (robmry) [reply libnetwork/sandbox.go:283]: Hmm - that won't work because, as described above, the `--sysctl` is applied after the SetKey excursion. So, the IPv6-ness of the container can't be determined during SetKey.

I'll dig in to it some more to understand the buildkit problem and what your PR does. Maybe the user's sysctl can be applied before the SetKey, but that's probably a rather significant change.

File: libnetwork/sandbox_dns_unix.go (hunk 8 above)
Comment (robmry) [reply libnetwork/sandbox_dns_unix.go:44]: I haven't found a case where the osSbox is `nil`. But, because its presence depends on its caller having called `withLibnetwork()` so that the SetKey stuff happens, it seemed best to be defensive rather than assume it's set and panic (or bail out) if it's not.

(Hence the comment "There should be an osSbox, but ...", and the `Warnf()`.)

File: libnetwork/sandbox.go (hunk 7 above)
Comment (robmry) [reply libnetwork/sandbox.go:283]: Is the concern that buildkit won't call `CtrTaskCreated()`?

If so, I think it's covered, because this change makes sure it'll get the old behaviour (and so will a further change I'm working on to defer IPv6 address allocation until after detecting IPv6 support in the container). I noted in this PR's description that ...

> To avoid potential problems for anything using libnetwork but not calling the new Sandbox method after container task creation - pre-start, the hosts file is created as-before (with the assumption that IPv6 is supported). Once the true IPv6 capability is known, the hosts file is re-generated.

If the remainder of your https://github.com/moby/moby/pull/44385 guarantees that's not necessary, it'll be possible to simplify the libnetwork code a little once it's merged.

Even then, without the early SetKey (before the user's `--sysctl` is applied) - we'll need to confirm that IPv6 is enabled in the container's namespace if possible. (I'm not sure if `net.ipv6.conf.[all|default].disable_ipv6 = 1` on the host could cause problems anywhere, perhaps not.)

But, as things stand, because the `--sysctl` is applied after the SetKey prestart hook runs, we need a chance to get in there afterwards.

(A simple "docker build" works fine for me with this change - but that probably doesn't mean much, as I don't know what problem you're anticipating, so I may not be testing for it.)

Comment (corhere) [reply libnetwork/sandbox.go:283]: > the `--sysctl` is applied after the SetKey excursion

Huh, you're correct. RunC behaves [contrary to the OCI runtime spec](https://github.com/opencontainers/runtime-spec/blob/main/runtime.md#start:~:text=All%20of%20the%20properties%20configured%20in%20config.json%20except%20for%20process%20MUST%20be%20applied.) and applies sysctls _after_ the `create` hooks. Sigh.

File: libnetwork/osl/namespace_linux.go (hunk 6 above)
Comment (corhere) [reply libnetwork/osl/namespace_linux.go:563]: It's a real pain that [the `create` OCI lifecycle hooks are under-specified.](https://github.com/opencontainers/runtime-spec/blob/main/config.md#createRuntime-hooks:~:text=The%20definition%20of%20createRuntime,performed%20by%20the%20runtime.) It gives runC free reign to make the hooks useless for many purposes. You're right; runC applies the sysctls in the OCI spec after the `prestart` OCI hook (read: `SetKey()`) completes.

That being said, [the initial value of `net.ipv6.conf.<iface>.disable_ipv6` in a freshly-created network namespace is `0` by default.](https://www.kernel.org/doc/html/latest/networking/ip-sysctl.html#:~:text=Default%3A%2016-,disable_ipv6%20%2D%20BOOLEAN,Default%3A%20FALSE%20(enable%20IPv6%20operation),-When%20this%20value) However, [there is a sysctl `devconf_inherit_init_net` to control this behaviour.](https://www.kernel.org/doc/html/v6.6/admin-guide/sysctl/net.html#devconf-inherit-init-net) If the sysctl is left at the default, `setIPv6()` is a no-op. And if the sysctl is modified, `setIPv6()` may override the user's wishes.

Further complicating matters is the `docker run --net=container:<ref>` flag to join a new container to another container's netns (as made famous by k8s Pods). `setIPv6()` called when adding a container to an existing pod may force-enable IPv6 in the netns after the user explicitly disabled it with `--sysctl` on the first container.

tl;dr `setIPv6()` is either a no-op, or forces IPv6 enabled when the user doesn't expect it.

File: libnetwork/sandbox_dns_unix.go (hunk 8 above)
Comment (corhere) [reply libnetwork/sandbox_dns_unix.go:44]: `--net=none`, then. That's not an exceptional case, so we shouldn't fill the daemon log with noise.
https://github.com/moby/moby/blob/df3a3211645c8b9406a74f97777c45e7b221d127/daemon/oci_linux.go#L64-L68

File: libnetwork/osl/namespace_linux.go (hunk 6 above)
Comment (robmry) [reply libnetwork/osl/namespace_linux.go:563]: Yes, if the default is IPv6-enabled , I can remove it. (Although it doesn't run for the container network / '--net=container' case, as discussed above.)

So ...

Checking for the '::1' is enough to detect a kernel that doesn't have IPv6, or any means the user has of disabling IPv6 under the daemon's feet.

If we parse the '--sysctl' option, and treat it as a "no IPv6" flag, the IPv6 config can all happen in SetKey. The '::1' still being present because of the early restart hook wouldn't matter.

(The libnetwork logic can then be simplified a bit, because the SetKey part will always run.)

Comment (robmry) [reply libnetwork/osl/namespace_linux.go]: I've done that ... removing several `setIPv6()` calls - including this one, and calls to `disable_ipv6` for `all` as a "starting point" when creating containers.

File: libnetwork/sandbox_dns_unix.go (hunk 8 above)
Comment (robmry) [reply libnetwork/sandbox_dns_unix.go]: This has gone-away now I've moved all the action into SetKey().

File: libnetwork/osl/namespace_linux.go [hunk 9]
```diff
@@ -555,32 +539,15 @@ func (n *Namespace) Restore(interfaces map[Iface][]IfaceOption, routes []*types.
...
+// is assigned by the kernel if IPv6 is enabled).
+func (n *Namespace) IPv6LoEnabled() bool {
+	iface, err := n.nlHandle.LinkByName("lo")
+	if err != nil {
+		return false
 	}
-
-	n.loV6Enabled = enable
+	addrs, err := n.nlHandle.AddrList(iface, nl.FAMILY_V6)
+	return err == nil && len(addrs) > 0
```
Comment (corhere) [inline libnetwork/osl/namespace_linux.go:550]: I wonder if we should actually check that `addrs` contains `::1`. While a fairly safe assumption today with runC and a vanilla kernel, all bets are off with custom kernels and alternative runtimes. For example, a runtime could support some custom OCI annotation which is analogous to `ip addr del ::1 dev lo`.

File: libnetwork/osl/interface_linux.go [hunk 10]
```diff
@@ -368,6 +364,9 @@ func setInterfaceIP(nlh *netlink.Handle, iface netlink.Link, i *Interface) error
 
 func setInterfaceIPv6(nlh *netlink.Handle, iface netlink.Link, i *Interface) error {
 	if i.AddressIPv6() == nil {
+		if err := setIPv6(i.ns.path, i.DstName(), false); err != nil {
+			log.G(context.TODO()).WithError(err).Debug("failed to disable IPv6")
+		}
```
Comment (corhere) [inline libnetwork/osl/interface_linux.go:369]:
```suggestion
```
All you have to do to fix #33099 is to not disable IPv6 on interfaces for arbitrary reasons. The non-existence of a routable IPv6 address on an endpoint does not imply that IPv6 should be disabled entirely.

> Furthermore, if I just want a link local address (and don't want to allocate routable addresses), there's no way to configure the default bridge network to do so. Enabling ipv6 requires that I have a range of addresses to assign, but all I want is link-local addresses as we got by default before.

If the user wants the link to not have an IPv6 link-local address, they can disable it with sysctls.

**Review by corhere — CHANGES_REQUESTED** [review]

File: daemon/start.go (hunk 5 above)
Comment (thaJeztah) [reply daemon/start.go]: The "mode" originated from before we had custom networks. At that time, the `--net` option was `bridge`, `none`, or `host` (possibly we already had `container` as well).

When custom networks were added, the `--net` / `--network` option was expanded to specify either (existing `bridge`, `none`, and `host` options, as well as `<name of custom network>`)

File: libnetwork/osl/interface_linux.go (hunk 10 above)
Comment (robmry) [reply libnetwork/osl/interface_linux.go:369]: Yes - I was aiming to preserve the old behaviour, where IPv6 was disabled on all interfaces unless they were connected to IPv6 networks. But it was broken behaviour, so I'll remove it.

Then, as you say, IPv6 link-local addresses will appear on most people's IPv4 interfaces - which might surprise some, but the sysctl stops it.

File: libnetwork/osl/namespace_linux.go (hunk 9 above)
Comment (robmry) [reply libnetwork/osl/namespace_linux.go:550]: I've been thinking of the absence of `::1` as a proxy for "no IPv6 support in this container" ... which I think is a fairly safe assumption, `::1` is a [required address](https://datatracker.ietf.org/doc/html/rfc4291#section-2.8) for an IPv6 host, and Linux's implementation of that is to add it to `lo`.

Only removal of `::1 localhost` from `/etc/hosts` is specific to `::1`.

Removal of `fe00::0 ip6-localnet` and the other defaults, or the IPv6 address of the container itself and (in later changes), not allocating IPv6 addresses, and generating an appropriate `resolv.conf` are based on deciding that the container has no IPv6 support - not specifically that it has no `::1` on `lo`.

So, checking for the presence of any IPv6 address on `lo`, rather than specifically for `::1` is equivalent for that purpose. If there is an IPv6 address it's probably `::1` but in any case, if it's there, the container supports IPv6. (And, if it's a standards-compliant implementation, `::1` will work somehow.)

If lack of a `::1` on `lo`, in a container that supports IPv6, is a real-world problem... I'll need a better test for "IPv6 enabled". Perhaps trying to assign an IPv6 address and looking for an error - but I think that's probably over-the-top.

File: libnetwork/sandbox_linux.go [hunk 11]
```diff
@@ -157,14 +157,35 @@ func (sb *Sandbox) SetKey(basePath string) error {
...
 
+// Set Sandbox.ipv6Disabled to its sysctl'd value (which runC hasn't yet
+// applied), else according to whether the container's 'lo' interface has
+// an IPv6 address ('::1' is assigned by the kernel when IPv6 is enabled).
+func (sb *Sandbox) calcIPv6Disabled(osSbox *osl.Namespace) bool {
+	for k, v := range sb.config.sysctls {
+		if k == "net.ipv6.conf.all.disable_ipv6" {
+			return v == "1"
+		}
+	}
```
[the remark this answers is not in the document]
Comment (robmry) [reply libnetwork/sandbox_linux.go:185]: Ok, we talked each other around on doing the work in SetKey to make sure buildkit is ok! (It makes things a lot simpler for follow-up changes to know that the task-created code will run). And, this was the only way try to read the user's intention at that point ... but, I agree it's got holes that only documentation would dig us out of. Not great.

So, I'll try to find a way for the daemon to promise to libnetwork that it'll make a call between task create/start where it can finalise config, without  Buildkit making that promise.

Then, for buildkit, libnetwork can finish its config during SetKey instead. As you say, luckily there's no way to set sysctls in buildkit's case.

File: libnetwork/sandbox.go [hunk 12]
```diff
@@ -98,6 +103,7 @@ type containerConfig struct {
 	useDefaultSandBox bool
 	useExternalKey    bool
 	exposedPorts      []types.TransportPort
+	sysctls           map[string]string
```
[the remark this answers is not in the document]
Comment (robmry) [reply libnetwork/sandbox.go:106]: My thinking was that the decision belongs to libnetwork, so it needs all the info - and, having a view of sysctl settings might be generally useful.

But, if I can move the logic back to between container create/start, this will go-away anyway.

File: libnetwork/osl/namespace_linux.go [hunk 13]
```diff
@@ -555,32 +539,15 @@ func (n *Namespace) Restore(interfaces map[Iface][]IfaceOption, routes []*types.
...
-
-	if err := setIPv6(n.path, "lo", enable); err != nil {
-		log.G(context.TODO()).Warnf("Failed to %s IPv6 on loopback interface on network namespace %q: %v", action, n.path, err)
+// IPv6LoEnabled checks whether the loopback interface has an IPv6 address ('::1'
+// is assigned by the kernel if IPv6 is enabled).
+func (n *Namespace) IPv6LoEnabled() bool {
+	iface, err := n.nlHandle.LinkByName("lo")
+	if err != nil {
+		return false
 	}
```
[the remark this answers is not in the document]
Comment (robmry) [reply libnetwork/osl/namespace_linux.go]: Done.

File: libnetwork/etchosts/etchosts.go [hunk 14]
```diff
@@ -71,6 +74,31 @@ func Drop(path string) {
...
+
+	return build(path, IP, hostname, domainname, ipv4ExtraContent, false)
+}
+
+func isIPv6(s string) bool {
+	addr, err := netip.ParseAddr(s)
+	return err == nil && addr.Is6()
+}
+
+func build(path, IP, hostname, domainname string, extraContent []Record, ipv6 bool) error {
```
[the remark this answers is not in the document]
Comment (robmry) [reply libnetwork/etchosts/etchosts.go]: Done.

File: libnetwork/etchosts/etchosts_test.go [hunk 15]
```diff
@@ -35,6 +38,26 @@ func TestBuildDefault(t *testing.T) {
...
+		},
+		{
+			Hosts: "another.example",
+			IP:    "10.11.12.13",
+		},
+	})
+	assert.NilError(t, err)
+	content, err := os.ReadFile(filename)
+	assert.NilError(t, err)
+	assert.Check(t, is.Equal(string(content), "127.0.0.1\tlocalhost\n10.11.12.13\tanother.example\n"))
```
Comment (corhere) [inline libnetwork/etchosts/etchosts_test.go:58]:
```suggestion
	assert.Check(t, is.DeepEqual(string(content), "127.0.0.1\tlocalhost\n10.11.12.13\tanother.example\n"))
```
gives a more readable line-by-line diff on failure

File: libnetwork/controller.go [hunk 16]
```diff
@@ -922,6 +923,11 @@ func (c *Controller) NewSandbox(containerID string, options ...SandboxOption) (_
 
 	sb.processOptions(options...)
 
+	// Set the initial value of ipv6Disabled based on whether the host has IPv6. This
+	// value will be used for host networking. For other types of networking, it will
+	// be updated once the container has been created and can be inspected.
+	sb.ipv6Disabled = !netutils.IsV6Listenable()
```
Comment (corhere) [inline libnetwork/controller.go:929]: I foresee the potential for lots of subtle bugs by having `sb.ipv6Disabled` exist. For example, if `NewSandbox` is called with the ID of a container that already has a sandbox  in `c.sandboxes`, `sb.ipv6Disabled` would get unconditionally cleared even if `sb.osSbox.IPV6LoEnabled() == false`. Or I can imagine some future contributor coming in, assuming incorrectly that `ipv6Disabled` _controls_ disabling IPv6 in a sandbox, and submitting some misguided PR that forces `sb.ipv6Disabled = true`.

We have the sources of truth readily available: `netutils.IsV6Listenable()` and `sb.osSbox.IPv6LoEnabled()`. Why do we need to cache it anywhere? If we do need to cache it for performance or other reasons, why do it in the ostensibly OS-independent `Sandbox` struct instead of the `osl.Namespace`?

File: libnetwork/sandbox_dns_unix.go (hunk 8 above)
Comment (robmry) [reply libnetwork/sandbox_dns_unix.go]: That code came back, along with the `Warnf`, because despite appearances in the code you highlighted - SetKey is called with an osSbox for a `--net=none`.

I've investigated now - `c.Config.NetworkDisabled` is only set for the default bridge during daemon startup, if the daemon's started with `--bridge none`.

So, the right thing to do here is just `return nil` ... I'll do that.

File: libnetwork/sandbox_options.go [hunk 17]
```diff
@@ -171,3 +171,13 @@ func OptionLoadBalancer(nid string) SandboxOption {
 		sb.oslTypes = append(sb.oslTypes, osl.SandboxTypeLoadBalancer)
 	}
 }
+
+// OptionCtrTaskCreated returns an option setter that says there will be a call
+// to libnetwork's Sandbox.CtrTaskCreated after container task creation, before
+// it's started. Setting this option when the container has already been started
+// (for an option-refresh) is harmless.
+func OptionCtrTaskCreated() SandboxOption {
```
[the remark this answers is not in the document]
Comment (robmry) [reply libnetwork/sandbox_options.go:179]: I'd be happy to change the name.

I guess I'm still trying to understand the rules for changing interfaces like this. I thought I'd understood that we treat packages as public interfaces that anybody could be using - so we can't be sure nothing else is "doing a buildkit", using libnetwork the way it does? That's why I figured calling the new phase-2 method would have to be opt-in. (Having free-reign over this sort of change would make life a lot easier though!)

Your third option sounds best by-far ... but still, if anything else is using `WithLibnetwork()` it'd be a breaking change. If that's not an issue, let's do it.

File: libnetwork/controller.go (hunk 16 above)
Comment (robmry) [reply libnetwork/controller.go:929]: I've added a `Sandbox.ipv6Enabled()` and, because it involves a netlink call and will be needed in a few couple places by follow-up changes, cached the result in `osl.Sandbox`.

File: libnetwork/etchosts/etchosts_test.go (hunk 15 above)
Comment (robmry) [reply libnetwork/etchosts/etchosts_test.go:58]: Done.

File: libnetwork/sandbox_linux.go [hunk 18]
```diff
@@ -3,10 +3,12 @@ package libnetwork
 import (
 	"context"
 	"fmt"
+	"github.com/docker/docker/libnetwork/netutils"
 	"net"
 	"time"
```
Comment (robmry) [inline libnetwork/sandbox_linux.go:8]: Stupid IDE ... I'll put this in the right place on the next push.

File: libnetwork/sandbox_options.go (hunk 17 above)
[the remark this answers is not in the document]
Comment (corhere) [reply libnetwork/sandbox_options.go]: The third option would not be a breaking change (even if we ignore the fact that neither `func withLibnetwork` nor its sole caller `func (*Daemon) createSpec` are exported) because the `libnetwork-setkey` reexec would continue to behave exactly the same as it currently does! The only functional difference between the existing behaviour and the "new" behaviour is at which point in the task's lifecycle `func (*Sandbox) SetKey` is called. Anything "doing a buildkit" would continue to invoke it via `libnetwork-setkey` from an OCI hook. We opt into the new behaviour by instead calling `SetKey` programmatically after any ipv6-related sysctls have been applied to the network namespace.

[the remark this answers is not in the document]
Comment (corhere) [reply libnetwork/sandbox_options.go]: (`withLibnetwork` used to be an exported function, but it was un-exported as part of #43980. Regardless, we consider the daemon tree to be de-facto internal.)

[the remark this answers is not in the document]
Comment (robmry) [reply libnetwork/sandbox_options.go]: Oh, yes - sure ... I was looking at the diff you linked to, it deletes `WithLibnetwork()` but it's been un-exported since. Sounds good then.

[the remark this answers is not in the document]
Comment (corhere) [reply libnetwork/sandbox_options.go]: I've rebased my PR so you can cherry-pick https://github.com/corhere/moby/commit/bd99fb03193b607df491aebda40910cc2f0f2514 cleanly into this one.

[the remark this answers is not in the document]
Comment (robmry) [reply libnetwork/sandbox_options.go]: Thank you!

**Review by corhere — APPROVED** [review]
🎉

File: daemon/start.go [hunk 19]
```diff
@@ -236,6 +239,19 @@ func (daemon *Daemon) containerStart(ctx context.Context, daemonCfg *configStore
...
 	}()
 
+	if runtime.GOOS == "linux" && !container.Config.NetworkDisabled {
+		nspath, ok := oci.NamespacePath(spec, specs.NetworkNamespace)
+		if ok && nspath == "" { // the runtime has been instructed to create a new network namespace for tsk.
+			sb, err := daemon.netController.GetSandbox(container.ID)
+			if err != nil {
+				return errdefs.System(err)
+			}
+			if err := sb.SetKey(fmt.Sprintf("/proc/%d/ns/net", tsk.Pid())); err != nil {
```
Comment (corhere) [inline daemon/start.go:249]: Oops, that line doesn't compile on Windows. I can fix that...

Comment (robmry) [reply daemon/start.go:249]: Oh, I've done it by adding a `SetKey()` to `sandbox_unsupported.go` and fixing up the commit - hopefully that's what you planned? If not I can do it differently.

Comment (corhere) [reply daemon/start.go:249]: https://github.com/corhere/moby/commit/4b0cf3d6f3589486cee969ef882ea8323bf48a30

I would prefer not to define a stub `SetKey` for Windows if it can be avoided. It can't do anything meaningful with the argument so can never be anything but a no-op stub. And there's already more than enough [interfaces in libnetwork which are only meaningful in one context that have to be stubbed out by all other implementations.](https://en.wikipedia.org/wiki/Interface_segregation_principle)

Comment (robmry) [reply daemon/start.go]: Ok, thank you ... I've swapped it in.

(Just had to fix a conflict in `daemon/oci_linux.go`, the list of opts changed just after your rebase.)

**Review by akerouanton — APPROVED** [review]
LGTM. Great job @robmry!

I just left a comment about a few dead params. Feel free to address it in a follow-up if you prefer.

File: libnetwork/sandbox_dns_unix.go [hunk 20]
```diff
@@ -101,7 +115,16 @@ func (sb *Sandbox) buildHostsFile() error {
 		extraContent = append(extraContent, etchosts.Record{Hosts: extraHost.name, IP: extraHost.IP})
 	}
 
-	return etchosts.Build(sb.config.hostsPath, "", sb.config.hostName, sb.config.domainName, extraContent)
+	// Assume IPv6 support, unless it's definitely disabled.
+	buildf := etchosts.Build
+	if en, ok := sb.ipv6Enabled(); ok && !en {
+		buildf = etchosts.BuildNoIPv6
+	}
+	if err := buildf(sb.config.hostsPath, "", sb.config.hostName, sb.config.domainName, extraContent); err != nil {
```
[the remark this answers is not in the document]
Comment (robmry) [reply libnetwork/sandbox_dns_unix.go:123]: Thanks Albin - I've created PR https://github.com/moby/moby/pull/47242 for that.

**Comment by dmitryuk** [comment]
Hello. How to disable net.ipv6.conf.all.disable_ipv6=1 globally without passing net.ipv6.conf.all.disable_ipv6 to every container?

**Comment by robmry** [comment]
> Hello. How to disable net.ipv6.conf.all.disable_ipv6=1 globally without passing net.ipv6.conf.all.disable_ipv6 to every container?

Hi @dmitryuk - a PR that got merged 18 months ago is a surprising place to find a question (!) ... but, for my understanding, what's the use-case or issue you're looking at? Why do you need to disable IPv6 in your containers?
