### PR TITLE
libnet/d/bridge: fix compilation on i386

### LINKED ISSUE #49523: Unable to Build Docker 28.0.0 on x86 (32-bit)
As maintainer of the Alpine Linux docker packages, I am unable to compile from source on **x86** arch _(all other archs compile fine)_.

```
>>> docker: Unpacking /var/cache/distfiles/cli-28.0.0.tar.gz...
>>> docker: Unpacking /var/cache/distfiles/moby-28.0.0.tar.gz...
>>> docker: building engine
Removing bundles/
---> Making bundle: dynbinary (in bundles/dynbinary)
Building dynamic bundles/dynbinary-daemon/dockerd (linux/386)...
+ tee /builds/alpine/aports/community/docker/src/moby-28.0.0/go.mod
module github.com/docker/docker
go 1.22.0
+ trap 'rm -f "${ROOTDIR}/go.mod"' EXIT
+ GO111MODULE=on
+ GOTOOLCHAIN=local
+ go build -mod=vendor -modfile=vendor.mod -o bundles/dynbinary-daemon/dockerd -tags seccomp -buildmode=pie -ldflags '-w -X "github.com/docker/docker/dockerversion.Version=28.0.0" -X "github.com/docker/docker/dockerversion.GitCommit=af898abe44662d9554fb15ee4d4a7307f1b8e315" -X "github.com/docker/docker/dockerversion.BuildTime=2025-02-20T18:55:44.000000000+00:00" -X "github.com/docker/docker/dockerversion.PlatformName=" -X "github.com/docker/docker/dockerversion.ProductName=" -X "github.com/docker/docker/dockerversion.DefaultProductLicense="   ' -gcflags= github.com/docker/docker/cmd/dockerd
# github.com/docker/docker/libnetwork/drivers/bridge
libnetwork/drivers/bridge/port_mapping_linux.go:679:45: undefined: syscall.SYS_SETSOCKOPT
+ rm -f /builds/alpine/aports/community/docker/src/moby-28.0.0/go.mod
>>> ERROR: docker: build failed
```
https://github.com/moby/moby/blame/459686bbea46f0a50bc81850603dc399271c078b/libnetwork/drivers/bridge/port_mapping_linux.go#L679

It appears that Go does not support `syscall.SYS_SETSOCKOPT` on **linux/x86**.

https://github.com/golang/go/issues/19043#issuecomment-279195971 suggests...
> On 386 GNU/Linux you'll need to call something along the lines of `Syscall6(syscall.SYS_SOCKETCALL, 15, /* setsockopt arguments */)`
linux/386 multiplexes all socket syscalls into a one syscall (probably because there aren't enough registers to pass the arguments.)

@robmry ^^

### PR DESCRIPTION
**Pull request by akerouanton**
- Fixes https://github.com/moby/moby/issues/49523

**- What I did**

On i386, Linux doesn't provide direct socket syscall but instead multiplexes them through the socketcall syscall (see `man 2 socketcall`).

**- How I did it**

This commit fixes compilation for i386 by wrapping the offending syscall in a new function that uses the socketcall syscall on i386, and the `setsockopt` syscall on other archs.

**- How to verify it**

`GOARCH=386 ./hack/make.sh binary`

**- Human readable description for the release notes**

```markdown changelog
Fix compilation on i386
```

### CODE REVIEW

**Review by robmry — APPROVED** [review]
LGTM

**Review by vvoland — APPROVED** [review]

File: libnetwork/drivers/bridge/port_mapping_linux.go [hunk 1]
```diff
@@ -675,14 +674,7 @@ func bindSCTP(cfg portBindingReq, port int) (_ portBinding, retErr error) {
 		syscall.SetsockoptInt(sd, syscall.IPPROTO_IPV6, syscall.IPV6_V6ONLY, 1)
 	}
 
-	options := sctp.InitMsg{NumOstreams: sctp.SCTP_MAX_STREAM}
-	if _, _, errno := syscall.Syscall6(syscall.SYS_SETSOCKOPT,
```
Comment (thaJeztah) [inline libnetwork/drivers/bridge/port_mapping_linux.go:679]: Regression point was https://github.com/moby/moby/commit/b3fabedecc0f408f674972d87803f41faedf4de8 correct? So from that, there's low risk of that getting into any of the release branches

- https://github.com/moby/moby/pull/48132

Comment (akerouanton) [reply libnetwork/drivers/bridge/port_mapping_linux.go:679]: Yup, only v28.0.0 is affected.
