### PR TITLE
awslogs: Record log line insert order for sorting

### LINKED ISSUE #24775: Logs sometimes out of order with awslogs log driver
**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:54:54 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:54:54 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
docker info
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 151
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 359
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null bridge host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-48-generic
Operating System: Ubuntu 14.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 14.69 GiB
Name: test-grid-02
ID: DKPX:PIXI:AHKL:JYZN:AVER:HDVL:43WL:JJRW:SEJV:ABJP:HCZ4:QIDM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS

**Steps to reproduce the issue:**

I've created a repository to easily reproduce this issue: https://github.com/joshpurvis/docker-awslogs

```
git clone https://github.com/joshpurvis/docker-awslogs
```

Set environment

```
export AWS_SECRET_ACCESS_KEY=YOURSECRET
export AWS_ACCESS_KEY_ID=YOURID
export AWS_DEFAULT_REGION=us-east-1
export AWS_LOGS_GROUP=YOURLOGGROUP
```

Build test image
```
docker build -t awslogtest .
```

Run a loop which logs ~20k times via awslogs driver
```
cid=$(docker run -d --log-driver=awslogs --log-opt awslogs-group=$AWS_LOGS_GROUP awslogtest python /test.py)
```

Read logs via boto -- logs come back, slightly out of order (same as on aws console)
```
docker run -it -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY awslogtest /usr/bin/python /viewer.py --group=$AWS_LOGS_GROUP --stream=$cid
```

**Describe the results you received:**

```
# ...

{u'ingestionTime': 1468876501400, u'timestamp': 1468876501111, u'message': u'INFO:__main__:19986'}
{u'ingestionTime': 1468876501400, u'timestamp': 1468876501111, u'message': u'INFO:__main__:19987'}
{u'ingestionTime': 1468876501400, u'timestamp': 1468876501111, u'message': u'INFO:__main__:19988'}
{u'ingestionTime': 1468876501400, u'timestamp': 1468876501111, u'message': u'INFO:__main__:19989'}
{u'ingestionTime': 1468876501400, u'timestamp': 1468876501111, u'message': u'INFO:__main__:19990'}
{u'ingestionTime': 1468876501400, u'timestamp': 1468876501111, u'message': u'INFO:__main__:19991'}
{u'ingestionTime': 1468876501400, u'timestamp': 1468876501111, u'message': u'INFO:__main__:19992'}
{u'ingestionTime': 1468876501400, u'timestamp': 1468876501111, u'message': u'INFO:__main__:19993'}
{u'ingestionTime': 1468876501400, u'timestamp': 1468876501111, u'message': u'INFO:__main__:19994'}
{u'ingestionTime': 1468876501400, u'timestamp': 1468876501111, u'message': u'INFO:__main__:19995'}
{u'ingestionTime': 1468876501400, u'timestamp': 1468876501111, u'message': u'INFO:__main__:19996'}
{u'ingestionTime': 1468876501400, u'timestamp': 1468876501111, u'message': u'INFO:__main__:19997'}
{u'ingestionTime': 1468876501400, u'timestamp': 1468876501111, u'message': u'INFO:__main__:19998'}
{u'ingestionTime': 1468876501400, u'timestamp': 1468876501111, u'message': u'INFO:__main__:19507'}
```

^ The numbers at the far right indicate the actual order in which the logs were sent to STDOUT according to Python. 

Note: this behavior appears in the Cloudwatch log console as well, I just found it easier to demonstrate with boto.

**Describe the results you expected:**

Lines logged in the order sent to STDOUT

**Additional information you deem important (e.g. issue happens only occasionally):**

- I would think the sequence token should prevent this from happening. It seems it's being used in the driver, but the lines are sent in bulk? I'm not too familiar with golang, so I haven't been able to get far reading the code yet

- I can pretty consistently reproduce it with ~20k lines of logs. It seems on smaller batches, it's more rare that it happens.

- Also in Docker 1.11 and likely some older versions, the problem appears to happen more often. I believe the related PR #22971 seems to help a bit in 1.12.0-rc4

**Edit:**

After reading over the code for the awslog driver and the other logging code, I found this bit:

https://github.com/docker/docker/blob/master/daemon/logger/awslogs/cloudwatchlogs.go#L360

Which is sorting the logs by `Message.Timestamp`. I assume this is the issue, given that two lines could have the same `Timestamp`. Is there something else that it can be sorted by to ensure that order is maintained, such as an index?

### PR DESCRIPTION
**Pull request by samuelkarp**
Fixes https://github.com/docker/docker/issues/24775

**\- What I did**
When multiple log lines are emitted with the same timestamp, fall back to insertion order rather than allowing `sort.Sort` to pick the order.

**\- How I did it**
Insertion order is recorded in a new wrapper struct internal to the logging driver.  `Less` now uses the insertion order when the timestamps are equal.

**\- How to verify it**
Unit tests pass.

**\- Description for the changelog**

Fixed a bug in the `awslogs` logging driver that could cause log lines to be recorded out-of-order under rare conditions.

### CODE REVIEW

**Comment by samuelkarp** [comment]
Bump.  I believe the Jenkins failure is unrelated to my change.

File: daemon/logger/awslogs/cloudwatchlogs.go [hunk 1]
```diff
@@ -270,14 +277,17 @@ func (l *logStream) collectBatch() {
...
-func (l *logStream) publishBatch(events []*cloudwatchlogs.InputLogEvent) {
+func (l *logStream) publishBatch(events []wrappedEvent) {
 	if len(events) == 0 {
 		return
 	}
 
+	// events in a batch must be sorted by timestamp
+	// see http://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.html
 	sort.Sort(byTimestamp(events))
+	cwEvents := getCWEvents(events)
```
Comment (thaJeztah) [inline daemon/logger/awslogs/cloudwatchlogs.go]: Perhaps I don't understand the problem, but wouldn't simply removing the `sort.Sort(byTimestamp(events))` solve the problem?

If I read the code correctly, the events are *added* in the correct order (in `collectBatch`), so they should arrive here in the correct order.

*However*, due to `sort.Sort(byTimestamp(events))`, the events possibly get reordered, and end up in the wrong order (if two events have exactly the same time stamp)

Could you try if simply removing that sort resolves the issue?

Comment (samuelkarp) [inline daemon/logger/awslogs/cloudwatchlogs.go]: The [`PutLogEvents` API](http://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.html) has this requirement:

> The log events in the batch must be in chronological ordered by their `timestamp`.

The sorting here is to ensure that even on a system that is experiencing some changes in the clock (e.g., skew being corrected by NTP) that the call to `PutLogEvents` will still succeed.

Comment (thaJeztah) [inline daemon/logger/awslogs/cloudwatchlogs.go]: As just discussed on Slack; I overlooked that the timestamps are not *generated* in `collectBatch`, but taken from the `msg`, so they *can* arrive in `collectBatch` in the wrong order.

Comment (thaJeztah) [inline daemon/logger/awslogs/cloudwatchlogs.go]: Perhaps rename `getCWEvents` to something like `unwrapEvents`, but that's just a nit and may be just me :smile:

**Comment by samuelkarp** [comment]
@thaJeztah I've changed the name per your suggestion.  The Jenkins failure (again) looks unrelated.

**Comment by crosbymichael** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM
