### PR TITLE
Add an integration test for bug #31392 regression

### LINKED ISSUE #31392: Linking to a container by name which was renamed before fails.
**Description**

If you have two linked containers, rename the target container and bring up a replacement with the old name, then delete and recreate the source container linking to the new target, no link is created.

In my use case, the target container failed. I wanted to keep it around for investigation but also to get back up and running ASAP. So I renamed it and started a replacement, but then replacing my dependent containers, they would not link to the new target.

**Steps to reproduce the issue:**
For the example I used postgres and redis images. However I believe any image will work. In my environment A0 is my application and B0 is nginx.
Create two named containers A0 & B0 with a link from B0 to A0. (hopefully the names ease understanding; unfortunately names must be >1 character)
1. `docker run -d --name=A0 postgres`
2. `docker run -d --name=B0 --link=A0 redis`
You can see in `docker inspect B0` the link: `"/A0:/B0/A0"`
Rename container A0.
3. `docker stop A0`
4. `docker rename A0 A1`
You can inspect B0 again and the link there has been renamed: `"/A1:/B0/A0"`
Start a replacement container A0
5. `docker run -d --name=A0 postgres`
Delete and re-create B0 to point to the new A0.
6. `docker rm -f B0`
7. `docker run -d --name=B0 --link=A0 redis`
Now inspect again B0 for links.

**Describe the results you received:**
```
            "Links": null,
```
Also verified inside the container that the link is not present - "host not found" error, etc.

**Describe the results you expected:**
```
            "Links": [
                "/A0:/B0/A0"
            ],
```

**Additional information you deem important (e.g. issue happens only occasionally):**
- This will occur if B0 existed and was linked to A0 *at any point before* the rename, and the replacement B0 is also named B0. I.e. you can run step 6 directly before step 3 and the bug will still occur.
- It will not occur if the replacement B0 is given a different name.
- Unable to reproduce on docker version 1.9.1 - link is created as expected.

**Output of `docker version`:**

```
Docker version 1.13.0, build 49bf474
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 1.13.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-24-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.858 GiB
Name: ip-172-31-6-208
ID: DFBJ:SEF4:QF2O:3RZM:GQ5L:TYEF:PQGB:XNLN:6DZA:R55T:FUCK:UZXZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS EC2 instance (not using ECS)

### PR DESCRIPTION
**Pull request by boaz0**
**- What I did**
I rebased the code and found out that the bug was fixed elsewhere.
To make sure it won't be reproduced again, I added an integration test.

Closes #31392

**- How I did it**

Created `integration/container/rename_test.go` with one integration test.

**- How to verify it**

Run unit tests.

### CODE REVIEW

File: integration-cli/docker_cli_rename_test.go [hunk 1]
```diff
@@ -136,3 +136,19 @@ func (s *DockerSuite) TestRenameContainerWithLinkedContainer(c *check.C) {
 	c.Assert(err, checker.IsNil)
 	c.Assert(strings.TrimSpace(out), checker.Equals, strings.TrimSpace(db1))
 }
+
+// Test case for #31392
```
Comment (thaJeztah) [inline integration-cli/docker_cli_rename_test.go]: Can you add a short description of what this test is testing for? It can help if the test is refactored in future and to verify that the test is still testing what it was originally written for 😅 

Also (sorry!) this test will now have to be moved to the `/integration` test-suite, as we're freezing the "old" `integration-cli` test

**Review by thaJeztah — CHANGES_REQUESTED** [review]
Thanks! left a comment on the test 😅

**Comment by thaJeztah** [comment]
Also @cpuguy83 PTAL

File: integration/container/rename_test.go [hunk 2]
```diff
@@ -0,0 +1,119 @@
...
+		},
+		&network.NetworkingConfig{},
+		"b0",
+	)
+	if err != nil {
+		t.Fatal(err)
+	}
+
+	if err := client.ContainerRename(ctx, aID, "a1"); err != nil {
+		fmt.Println("!!!!!", aID)
```
Comment (AkihiroSuda) [inline integration/container/rename_test.go]: Please remove this

Comment (ripcurld0) [reply integration/container/rename_test.go]: Oops! 🐑

File: integration/container/rename_test.go [hunk 3]
```diff
@@ -0,0 +1,90 @@
...
+	}
+	return cnt.ID
+}
+
+// This test simulates the scenario mentioned in #31392:
+// Having two linked container, renaming the target and bringing a replacement
+// and then deleting and recreating the source container linked to the new target.
+// This checks that "rename" updates source container correctly and doesn't set it to null.
+func TestRenameLinkedContainer(t *testing.T) {
+	defer setupTest(t)()
```
Comment (thaJeztah) [inline integration/container/rename_test.go]: We should add a description to `setupTest` that it returns a cleanup function (and possibly an example). I had to look twice here as I thought this had to be some `teardownTest()` instead 😅

File: integration/container/rename_test.go [hunk 4]
```diff
@@ -0,0 +1,90 @@
...
+
+	runContainer(t, client, ctx,
+		cntConfig,
+		&container.HostConfig{},
+		&network.NetworkingConfig{},
+		"a0",
+	)
+
+	if err := client.ContainerRemove(ctx, bID, types.ContainerRemoveOptions{Force: true}); err != nil {
+		t.Fatal(err)
```
Comment (thaJeztah) [inline integration/container/rename_test.go]: same here (`require.NoError(t, err)`)

File: integration/container/rename_test.go [hunk 5]
```diff
@@ -0,0 +1,90 @@
...
+		cntConfig,
+		&container.HostConfig{
+			Links: []string{"a0"},
+		},
+		&network.NetworkingConfig{},
+		"b0",
+	)
+
+	if cntJson, err := client.ContainerInspect(ctx, bID); err != nil {
+		t.Fatal(err)
```
Comment (thaJeztah) [inline integration/container/rename_test.go]: same here (`require.NoError(t, err)`)

File: integration/container/rename_test.go [hunk 6]
```diff
@@ -0,0 +1,90 @@
...
+	"github.com/docker/docker/api/types/strslice"
+	"github.com/docker/docker/client"
+	"github.com/docker/docker/integration/util/request"
+	"github.com/stretchr/testify/assert"
+)
+
+func runContainer(t *testing.T, client client.APIClient, ctx context.Context, cntCfg *container.Config, hstCfg *container.HostConfig, nwkCfg *network.NetworkingConfig, cntName string) string {
+	cnt, err := client.ContainerCreate(ctx, cntCfg, hstCfg, nwkCfg, cntName)
+	if err != nil {
+		t.Fatal(err)
```
Comment (thaJeztah) [inline integration/container/rename_test.go]: use `require.NoError(t, err)` instead?

File: integration/container/rename_test.go [hunk 7]
```diff
@@ -0,0 +1,90 @@
...
+	}
+
+	if err := client.ContainerStart(ctx, cnt.ID, types.ContainerStartOptions{}); err != nil {
+		t.Fatal(err)
```
Comment (thaJeztah) [inline integration/container/rename_test.go]: same here (`require.NoError(t, err)`)

**Review by thaJeztah — CHANGES_REQUESTED** [review]
left some nits

File: integration/container/rename_test.go (hunk 6 above)
Comment (ripcurld0) [reply integration/container/rename_test.go]: Thanks that was super duper helpful! 👍

File: integration/container/rename_test.go (hunk 3 above)
Comment (dnephin) [reply integration/container/rename_test.go]: Ya, I guess `setupTeardownTest()` would be a better name

**Review by dnephin — APPROVED** [review]
It would be nice if we could test this without running a daemon, but I don't think the code is really structured to enable that right now.

LGTM

File: integration/container/rename_test.go (hunk 3 above)
Comment (thaJeztah) [reply integration/container/rename_test.go]: Alternatively, something like this could be more clear:

```go
fnClean := setupTest(t)
defer fnClean()
```

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks @ripcurld0 !

File: integration/container/rename_test.go (hunk 3 above)
Comment (dnephin) [reply integration/container/rename_test.go]: but twice as many lines of code!

**Comment by vdemeester** [comment]
@ripcurld0 small lint errors

```
20:57:15 integration/container/rename_test.go:43:3:warning: var cntJson should be cntJSON (golint)
20:57:15 integration/container/rename_test.go:17:1:warning: context.Context should be the first parameter of a function (golint)
```

**Comment by ripcurld0** [comment]
@vdemeester OMG 😱 
Thanks... Got it fixed 😸

**Review by vdemeester — APPROVED** [review]
LGTM 🐮

**Comment by thaJeztah** [comment]
z failure os a flaky test; reported here: https://github.com/moby/moby/issues/34938

```
10:06:31 ----------------------------------------------------------------------
10:06:31 FAIL: docker_cli_update_unix_test.go:139: DockerSuite.TestUpdateKernelMemoryUninitialized
10:06:31 
10:06:31 docker_cli_update_unix_test.go:149:
10:06:31     c.Assert(err, check.NotNil)
10:06:31 ... value = nil
10:06:31 
```
