### PR TITLE
After retries, use netlink data even if the dump is still interrupted

### LINKED ISSUE #48400: networking: investigate `EINTR` regression after updating github.com/vishvananda/netlink to v1.3.0
### Description

- relates to https://github.com/moby/moby/pull/48368
- relates to https://github.com/moby/moby/pull/46982#issuecomment-2315840500
- relates to https://github.com/vishvananda/netlink/pull/793#issuecomment-2315879136

github.com/vishvananda/netlink was updated to v1.3.0 in https://github.com/moby/moby/pull/46982, but resulted in flakiness in CI;

```
Error initializing network controller: list bridge addresses failed: interrupted system call
```   

Upon first look, it was suggested that this was due to a missing condition for handling `EINTR`;  https://github.com/moby/moby/pull/46982#issuecomment-2315840500

> EINTR on netlink sockets is a new one. I suspect it has more to do with the netlink dependency bump you pulled in when rebasing than on the Go toolchain bump. I think the bug is here: https://github.com/vishvananda/netlink/blob/92645823f36c7ed03faf4baa566078d9d5e06fda/nl/nl_linux.go#L821-L824 It retries on `EWOULDBLOCK` (a.k.a. `EAGAIN`) but neglects to retry on `EINTR `.

However, it may be because of our use of `SetSocketTimeout `; see https://github.com/vishvananda/netlink/pull/793#issuecomment-2316612423

> IO calls on non-blocking sockets will never return `-EINTR`. The problem here is that Moby calls `SetSocketTimeout`, which sets `SO_SNDTIMEO` and `SO_RCVTIMEO`. These socket options are only useful for sockets in blocking mode. Setting these probably places the socket back into blocking mode.
> 
> https://github.com/moby/moby/blob/92a05cf4148adc26054a5b52b191e0b4d13112cd/libnetwork/ns/init_linux.go#L25-L40
> 
> https://github.com/vishvananda/netlink/blob/92645823f36c7ed03faf4baa566078d9d5e06fda/nl/nl_linux.go#L848-L860
> 
> I'm not very familiar with this project, but it seems to me that before this PR, only blocking IO is used. This PR adds calls to set the socket as non-blocking, but still allows setting the timeout socket options.

Those `SetSocketTimeout` uses were added in https://github.com/moby/libnetwork/commit/f459afbcfc5f1cb09051f7843c5766d2c1a6776c

- https://github.com/moby/libnetwork/pull/1557
- (moby PR: https://github.com/moby/moby/pull/29004)

to address 

- https://github.com/moby/libnetwork/issues/1474
- https://github.com/moby/libnetwork/issues/2208

Also related:

- https://github.com/vishvananda/netlink/pull/170

### PR DESCRIPTION
**Pull request by robmry**
**- What I did**

- fix https://github.com/moby/moby/issues/48400

Before version 1.2.1, the `vishvananda/netlink` package ignored `NLM_F_DUMP_INTR` in netlink responses. In 1.2.1, it started to return `EINTR` and no data in that case.

https://github.com/moby/moby/pull/48407 wrapped affected netlink calls in the `nlwrap` package. So, there would be up-to 5 attempts to make a request, get `EINTR`, and retry. After 5 attempts, the `EINTR` was returned and the caller would handle the failure.

Now, the netlink package returns data along with `netlink.ErrDumpInterrupted` in this case.

So, after 5 attempts, the `nlwrap` functions now discard the error and return the last set of data they got - which may be incomplete or inconsistent. But, this matches the behaviour of vishvananda/netlink prior to version 1.2.1, in which the NLM_F_DUMP_INTR flag was ignored.

If this ever happens, a stack trace will be logged.

**- How I did it**

- Pick up the `visvananda/netlink` package at its current-latest commit, which:
  - fixes timeouts, and
  - returns data along with `netlink.ErrDumpInterrupted` when it encounters an `NLM_F_DUMP_INTR` error (rather than discarding results and returning `EINTR`).
  - Full diff: https://github.com/vishvananda/netlink/compare/v1.3.0...084abd93d350
- Fix godoc comments in the `nlwrap` package.
- In `nlwrap`, after maxRetries, discard ErrDumpInterrupted, log a stack trace, and return data.

**- How to verify it**

Not tested directly, but after temporarily changing the `nlh.AddrList` wrapper to:

```diff
--- a/internal/nlwrap/nlwrap_linux.go
+++ b/internal/nlwrap/nlwrap_linux.go
@@ -82,6 +82,7 @@ func discardErrDumpInterrupted(err error) error {
 func (nlh Handle) AddrList(link netlink.Link, family int) (addrs []netlink.Addr, err error) {
        retryOnIntr(func() error {
                addrs, err = nlh.Handle.AddrList(link, family) //nolint:forbidigo
+               err = netlink.ErrDumpInterrupted
                return err
        })
        return addrs, discardErrDumpInterrupted(err)
 }
```

... checked that daemon startup continued normally, with log messages like this:

```
INFO[2024-10-07T13:00:44.099150679Z] netlink call interrupted after 5 attempts
WARN[2024-10-07T13:00:44.099197470Z] discarding ErrDumpInterrupted: results may be incomplete or inconsistent
github.com/docker/docker/internal/nlwrap.discardErrDumpInterrupted
	/go/src/github.com/docker/docker/internal/nlwrap/nlwrap_linux.go:75
github.com/docker/docker/internal/nlwrap.Handle.AddrList
	/go/src/github.com/docker/docker/internal/nlwrap/nlwrap_linux.go:88
github.com/docker/docker/daemon.ifaceAddrs.func1
	/go/src/github.com/docker/docker/daemon/daemon_linux.go:166
github.com/docker/docker/daemon.ifaceAddrs
	/go/src/github.com/docker/docker/daemon/daemon_linux.go:178
github.com/docker/docker/daemon.initBridgeDriver
	/go/src/github.com/docker/docker/daemon/daemon_unix.go:949
github.com/docker/docker/daemon.configureNetworking
	/go/src/github.com/docker/docker/daemon/daemon_unix.go:886
github.com/docker/docker/daemon.(*Daemon).initNetworkController
	/go/src/github.com/docker/docker/daemon/daemon_unix.go:850
github.com/docker/docker/daemon.(*Daemon).restore
	/go/src/github.com/docker/docker/daemon/daemon.go:580
github.com/docker/docker/daemon.NewDaemon
	/go/src/github.com/docker/docker/daemon/daemon.go:1241
main.(*daemonCLI).start
	/go/src/github.com/docker/docker/cmd/dockerd/daemon.go:257
main.runDaemon
	/go/src/github.com/docker/docker/cmd/dockerd/docker_unix.go:13
main.newDaemonCommand.func1
	/go/src/github.com/docker/docker/cmd/dockerd/docker.go:49
github.com/spf13/cobra.(*Command).execute
	/go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:985
github.com/spf13/cobra.(*Command).ExecuteC
	/go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:1117
github.com/spf13/cobra.(*Command).Execute
	/go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:1041
github.com/spf13/cobra.(*Command).ExecuteContext
	/go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:1034
main.main
	/go/src/github.com/docker/docker/cmd/dockerd/docker.go:113
runtime.main
	/usr/local/go/src/runtime/proc.go:271
runtime.goexit
	/usr/local/go/src/runtime/asm_arm64.s:1222
```

**- Description for the changelog**
```markdown changelog
n/a
```

### CODE REVIEW

File: internal/nlwrap/nlwrap_linux.go [hunk 1]
```diff
@@ -56,32 +59,44 @@ func (h Handle) Close() {
...
 }
 
-// AddrList calls nlh.LinkList, retrying if necessary.
+func discardErrDumpInterrupted(err error) error {
+	if errors.Is(err, netlink.ErrDumpInterrupted) {
+		// The netlink function has returned possibly-inconsistent data along with the
+		// error. Discard the error and return the data. This restores the behaviour of
+		// the netlink package prior to v1.2.1, in which NLM_F_DUMP_INTR was ignored in
+		// the netlink response.
+		log.G(context.TODO()).Warnf("discarding ErrDumpInterrupted: %+v", perrors.WithStack(err))
```
Comment (akerouanton) [inline internal/nlwrap/nlwrap_linux.go:75]: Wondering if the stack trace really needs to be logged as a Warning. Since this was the old behavior, I think we'd know by now if it was really causing any issue. I'd rather log that with debug level.

Comment (robmry) [reply internal/nlwrap/nlwrap_linux.go:75]: Maybe we wouldn't know though - "sometimes on my host" issues might have been written off as "can't repro"?

I think it's unlikely we'll see failures after five retries. But, if we do, it's probably something we want to know about. And, without a stack trace, there's no way to work out whether the error relates to any observed misbehaviour.

So, I think it's worth keeping the stack trace at info level - at least for 28.x, in case there is an issue in the real world?

Comment (akerouanton) [reply internal/nlwrap/nlwrap_linux.go:75]: Fine, let's keep it as a Warning then.

File: vendor.mod [hunk 2]
```diff
@@ -94,7 +94,7 @@ require (
 	github.com/tonistiigi/fsutil v0.0.0-20240424095704-91a3fc46842c
 	github.com/tonistiigi/go-archvariant v1.0.0
 	github.com/vbatts/tar-split v0.11.5
-	github.com/vishvananda/netlink v1.3.0
+	github.com/vishvananda/netlink v1.3.1-0.20240922070040-084abd93d350
```
Comment (thaJeztah) [inline vendor.mod:97]: Did we have any pending PRs still in nettlink?

Otherwise I want to give it a try as well to see if they're willing to tag a new release.

Comment (robmry) [reply vendor.mod:97]: Nothing pending. So, yes, it's probably worth asking.

Comment (thaJeztah) [reply vendor.mod:97]: I left a comment on your last merged PR 🤞

**Review by akerouanton — APPROVED** [review]

File: vendor.mod (hunk 2 above)
Comment (robmry) [reply vendor.mod:97]: No response yet ... shall we merge this to get tests running with it, and before it rots - then update the release tag when one's available?

File: internal/nlwrap/nlwrap_linux.go [hunk 3]
```diff
@@ -5,24 +5,27 @@
...
+// the behaviour of vishvananda/netlink versions prior to 1.2.1, in which the
+// NLM_F_DUMP_INTR flag was ignored.
 package nlwrap
 
 import (
 	"context"
 	"errors"
 
 	"github.com/containerd/log"
+	perrors "github.com/pkg/errors"
```
Comment (thaJeztah) [inline internal/nlwrap/nlwrap_linux.go:26]: We could also swap out one for the other, instead of importing both (looks like it's only using 'errors.Is' which I think is an alias in pkg/errors)

File: internal/nlwrap/nlwrap_linux.go (hunk 1 above)
Comment (thaJeztah) [reply internal/nlwrap/nlwrap_linux.go:75]: Do we need a tracking issue for updating it after 28.0?

**Review by thaJeztah — APPROVED** [review]
LGTM

one minor suggestion, but no blocker if you want this merged

File: internal/nlwrap/nlwrap_linux.go (hunk 3 above)
Comment (robmry) [reply internal/nlwrap/nlwrap_linux.go]: Done.

File: internal/nlwrap/nlwrap_linux.go (hunk 1 above)
Comment (robmry) [reply internal/nlwrap/nlwrap_linux.go]: I don't think so ... either we'll see lots of errors with stack traces or, I think more likely, we won't see any.

If we don't see any, might as well leave it in - in case an environment where it's a problem crops up. If we do see the error happening a lot, it'll need addressing anyway.

File: internal/nlwrap/nlwrap_linux.go [hunk 4]
```diff
@@ -5,24 +5,26 @@
 // wrapped. Functions that use the package handle need to be called as "nlwrap.X"
 // instead of "netlink.X".
 //
-// The wrapped functions currently return EINTR when NLM_F_DUMP_INTR flagged
-// in a netlink response, meaning something changed during the dump so results
-// may be incomplete or inconsistent.
+// When netlink.ErrDumpInterrupted is returned, the wrapped functions retry up to
```
Comment (thaJeztah) [inline internal/nlwrap/nlwrap_linux.go:8]: Oh! Definitely not an issue, but if you  put these things in square brackets, then `pkg.go.dev` will use them as docs-links, i.e.

```suggestion
// When [netlink.ErrDumpInterrupted] is returned, the wrapped functions retry up to
```

Will make `netlink.ErrDumpInterrupted` a clickable link to  the pkg.go.dev documentation of netlink (which is pretty neat).

(Custom reference links are also supported)

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!
