### PR TITLE
awslogs: account for UTF-8 normalization in limits

### LINKED ISSUE #37747: awslogs log driver: occasionally attempts to upload batch that is too large
**Description**

With `aws-logs` log driver, Docker occasionally drops logs due to errors like "InvalidParameterException: Upload too large: 1188330 bytes exceeds limit of 1048576".

It seems it fails to estimate size of request correctly, and to split request to AWS into smaller requests.

**Steps to reproduce the issue:**
1. Configure Docker to send logs to awslogs (see config below)
2. Run the following command to produce demo logs: `docker run ubuntu bash -c 'for x in 1 2 3 4 5 6 7 8; do cat /dev/urandom | tr -d "\n" | head -c 131050; echo; done' | gzip | wc -c`

**Describe the results you received:**
Observe logs did not get sent to awslogs, but instead in `/var/log/messages` we have `InvalidParameterException: Upload too large: 1188330 bytes exceeds limit of 1048576`

**Describe the results you expected:**
Logs to get into awslogs without errors.

**Additional information you deem important (e.g. issue happens only occasionally):**

Furthermore, it appears Docker somehow doubles the payload size. I.e. initially I was planning to do the following as repro: `docker run ubuntu bash -c 'for x in 1 2 3 4; do cat /dev/urandom | tr -d "\n" | head -c 262140; echo; done' | gzip | wc -c` - but it failed with "InvalidParameterException: Log event too large: 476138 bytes exceeds limit of 262144", indicating that Docker is sending log event that is 2x bigger than the original log line.

The repro steps of course are just random data, but I observe this issue happening once or twice a day with logs from ipfs daemon (in debug mode, so it is sending quite significant amount of logs).

Apart from seemingly wrong strategy of splitting data to send to AWS, it would also be great if Docker was dumping the failed blobs somewhere. It would help to diagnose this particular issue better, and also would be better from audit perspective, as currently if someone gets in the container that is monitored using awslogs, they can flood it in order to cause logs loss, and therefore hide their activity.

Config that I'm using to send data to awslogs:
```
cat /etc/docker/daemon.json
{
  "log-driver": "awslogs",
  "log-opts": {
    "awslogs-region": "us-east-1",
    "awslogs-group": "docker.i-019b04c8046828f2d",
    "awslogs-create-group": "true",
    "tag": "{{.Name}}-{{.ID}}"
  }
}
```

This is similar to https://github.com/moby/moby/issues/35725 - but I decided to open a new issue instead of reopening that one as it is quite old.

**Output of `docker version`:**

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.6
 Git commit:   3dfb8343b139d6342acfd9975d7f1068b5b1c3d3
 Built:        Wed Jul 25 00:48:56 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.6
  Git commit:   7390fc6/18.03.1-ce
  Built:        Wed Jul 25 00:51:07 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 26
 Running: 4
 Paused: 0
 Stopped: 22
Images: 68
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: awslogs
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.62-70.117.amzn2.x86_64
Operating System: Amazon Linux 2
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.853GiB
Name: ip-172-31-9-51.ec2.internal
ID: XCDZ:TO2M:DBAZ:BNT2:KKTY:3IMX:IYHT:ZOLU:FCP6:QZRK:3UVJ:7CHK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS AMI Linux 2

### PR DESCRIPTION
**Pull request by samuelkarp**
**- What I did**

The CloudWatch Logs API defines its limits in terms of bytes, but its inputs in terms of UTF-8 encoded strings.  Byte-sequences which are not valid UTF-8 encodings are normalized to the Unicode replacement character U+FFFD, which is a 3-byte sequence in UTF-8.  This replacement can cause the input to grow, exceeding the API limit and causing failed API calls.

This commit adds logic for counting the effective byte length after normalization and splitting input without splitting valid UTF-8 byte-sequences into two invalid byte-sequences.

Fixes https://github.com/moby/moby/issues/37747

**- How I did it**

Divide input into `rune`s by `range`ing through a `string`, and then using `utf8.RuneLen` to find the number of bytes it takes to correctly encode the rune (`utf8.RuneError` encodes as 3 bytes).

**- How to verify it**

From https://github.com/moby/moby/issues/37747:

Run `docker run ubuntu bash -c 'for x in 1 2 3 4 5 6 7 8; do cat /dev/urandom | tr -d "\n" | head -c 131050; echo; done' | gzip | wc -c` using the `awslogs` driver (I added `--log-driver awslogs --log-opt awslogs-group=bug --log-opt awslogs-region=us-west-2`).  Prior to this commit, errors show up in the Docker daemon log and container logs are not successfully sent to CloudWatch Logs.  After this commit, no errors show in the daemon log and container logs are successfully sent (though many characters will be replaced by U+FFFD).

Note: There appears to be another issue where stdout from a container can get split inside Docker.  If I run `docker run --log-driver awslogs --log-opt awslogs-group=bug ubuntu bash -c 'printf "%🙃.0s" {1..65530}' | wc -c`, the container generates 262120 bytes (each 🙃 is 4 bytes), but Docker calls the driver's `Log` method twice: once with 262118 bytes and once with 2 bytes, splitting the last 🙃 into two parts.  I can see this by instrumenting `Log` and dumping out the number of bytes sent in the `logger.Message`.

**- Description for the changelog**
awslogs: fixed bug in log event size calculation with invalid UTF-8 byte sequences

### CODE REVIEW

**Comment by samuelkarp** [comment]
This failure looks unrelated:

```
05:23:09 ----------------------------------------------------------------------
05:23:09 FAIL: docker_cli_daemon_plugins_test.go:72: DockerDaemonSuite.TestDaemonKillLiveRestoreWithPlugins
05:23:09 
05:23:09 [df17e233e7bf0] waiting for daemon to start
05:23:09 [df17e233e7bf0] daemon started
05:23:09 
05:23:09 docker_cli_daemon_plugins_test.go:77:
05:23:09     c.Fatalf("Could not install plugin: %v %s", err, out)
05:23:09 ... Error: Could not install plugin: exit status 1 Error response from daemon: error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/9f/9f84b4e64c82a349a91e135e797902f242d55a1088e484bce3534ecf0d12f40c/data?verify=1538892759-BHZIMbGQLMAKu96CrYWgHyPAOwg%3D: dial tcp 104.18.123.25:443: i/o timeout
05:23:09 
05:23:09 
05:23:09 [df17e233e7bf0] exiting daemon
05:23:36 
05:23:36 ----------------------------------------------------------------------
````

**Comment by thaJeztah** [comment]
ping @anusha-ragunathan @cpuguy83 PTAL

File: daemon/logger/awslogs/cloudwatchlogs.go [hunk 1]
```diff
@@ -524,16 +530,17 @@ func (l *logStream) collectBatch(created chan bool) {
...
+	for len(bytes) > 0 {
 		// Split line length so it does not exceed the maximum
-		lineBytes := len(events)
-		if lineBytes > maximumBytesPerEvent {
-			lineBytes = maximumBytesPerEvent
-		}
-		line := events[:lineBytes]
-
+		splitOffset, lineBytes := findValidSplit(string(bytes), maximumBytesPerEvent)
+		line := bytes[:splitOffset]
```
Comment (IRCody) [inline daemon/logger/awslogs/cloudwatchlogs.go]: If this comes back with both splitOffset and lineBytes as 0 do we end up adding a 0 length event incorrectly below during the batch.add call?

File: daemon/logger/awslogs/cloudwatchlogs_test.go [hunk 2]
```diff
@@ -938,6 +938,61 @@ func TestCollectBatchClose(t *testing.T) {
 	}
 }
 
+func TestEffectiveLen(t *testing.T) {
+	tests := []struct {
+		str            string
+		effectiveBytes int
+	}{
+		{"Hello", 5},
```
Comment (IRCody) [inline daemon/logger/awslogs/cloudwatchlogs_test.go]: Might make sense to add empty string as a test case also.

File: daemon/logger/awslogs/cloudwatchlogs.go [hunk 3]
```diff
@@ -495,15 +500,16 @@ func (l *logStream) collectBatch(created chan bool) {
...
 					// so flush the current eventBuffer to events and reset timestamp
 					l.processEvent(batch, eventBuffer, eventBufferTimestamp)
 					eventBufferTimestamp = msg.Timestamp.UnixNano() / int64(time.Millisecond)
 					eventBuffer = eventBuffer[:0]
 				}
-				// Append new line if event is less than max event size
-				if len(line) < maximumBytesPerEvent {
+				// Append newline if event is less than max event size
+				if lineEffectiveLen < maximumBytesPerEvent {
 					line = append(line, "\n"...)
```
[the remark this answers is not in the document]
Comment (samuelkarp) [reply daemon/logger/awslogs/cloudwatchlogs.go]: We just don't put a newline in at that point.  On the next time we go through this switch, it'll either hit the if statement right above (line 504) or we'll have a tick and it'll get handled in line 483.

File: daemon/logger/awslogs/cloudwatchlogs.go (hunk 1 above)
Comment (samuelkarp) [reply daemon/logger/awslogs/cloudwatchlogs.go]: I can add a check for that.  In practice, that shouldn't happen; there is no Unicode character that has a byte sequence greater than `maximumBytesPerEvent`, so there should always be a valid split if `bytes` is non-empty.

Comment (IRCody) [reply daemon/logger/awslogs/cloudwatchlogs.go]: Is bytes guaranteed to be non-empty?

**Review by IRCody — APPROVED** [review]
LGTM

File: daemon/logger/awslogs/cloudwatchlogs.go (hunk 1 above)
Comment (samuelkarp) [reply daemon/logger/awslogs/cloudwatchlogs.go]: I'm going to leave this as-is, since we're just processing the `logger.Message` received by the log driver.  If `bytes` is empty, I think it's fine to generate an empty `cloudwatchlogs.InputLogEvent`.

File: daemon/logger/awslogs/cloudwatchlogs_test.go (hunk 2 above)
Comment (samuelkarp) [reply daemon/logger/awslogs/cloudwatchlogs_test.go]: Done.

**Comment by samuelkarp** [comment]
This failure looks unrelated:

```
22:34:58 FAIL: docker_cli_events_test.go:316: DockerSuite.TestEventsFilterLabels
22:34:58 
22:34:58 docker_cli_events_test.go:334:
22:34:58     c.Assert(len(events), checker.Equals, 3)
22:34:58 ... obtained int = 2
22:34:58 ... expected int = 3
```

**Review by thaJeztah — APPROVED** [review]
LGTM

Does this affect performance?

**Comment by thaJeztah** [comment]
ping @anusha-ragunathan @cpuguy83 PTAL

**Review by yongtang — APPROVED** [review]
LGTM

File: daemon/logger/awslogs/cloudwatchlogs.go [hunk 4]
```diff
@@ -524,16 +530,17 @@ func (l *logStream) collectBatch(created chan bool) {
...
+func (l *logStream) processEvent(batch *eventBatch, bytes []byte, timestamp int64) {
+	for len(bytes) > 0 {
 		// Split line length so it does not exceed the maximum
-		lineBytes := len(events)
-		if lineBytes > maximumBytesPerEvent {
-			lineBytes = maximumBytesPerEvent
-		}
-		line := events[:lineBytes]
-
+		splitOffset, lineBytes := findValidSplit(string(bytes), maximumBytesPerEvent)
```
Comment (anusha-ragunathan) [inline daemon/logger/awslogs/cloudwatchlogs.go]: `maximumBytesPerEvent` dont need to be passed as arg. It's a constant that can be used directly in `findValidSplit`

Comment (anusha-ragunathan) [reply daemon/logger/awslogs/cloudwatchlogs.go]: I see that you are using it test code with variable values. Ignore.

**Comment by anusha-ragunathan** [comment]
LGTM
