### PR TITLE
docker stack deploy interpolation format error due to not escaping $ now includes a hint

### LINKED ISSUE #30629: docker stack deploy fails on "Invalid interpolation format for "command"
**Description**
when using `docker stack deploy`, the command fails on Invalid interpolation format for "command" option in service 

**Steps to reproduce the issue:**
~~~
docker stack deploy --compose-file=docker-compose.yml monitoring
~~~
the compose file I'm using is [this](https://gist.github.com/999404efd8e63ae1dfaa18ef1595d4c5)

**Describe the results you received:**
~~~
host$ docker stack deploy --compose-file=docker-compose.yml monitoring                                                            
Invalid interpolation format for "command" option in service "node-exporter": "^/(sys|proc|dev|host|etc)($|/)"
~~~

**Describe the results you expected:**
it should work, the same syntax works from the command line 
~~~

docker \
  service create --mode global \
  --name node-exporter \
  --mount type=bind,source=/proc,target=/host/proc \
  --mount type=bind,source=/sys,target=/host/sys \
  --mount type=bind,source=/,target=/rootfs \
  --mount type=bind,source=/etc/hostname,target=/etc/host_hostname \
  -e HOST_HOSTNAME=/etc/host_hostname \
  basi/node-exporter:latest \
  -collector.procfs /host/proc \
  -collector.sysfs /host/sys \
  -collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc)($|/)" \
  --collector.textfile.directory /etc/node-exporter/ \
  --collectors.enabled="conntrack,diskstats,entropy,filefd,filesystem,loadavg,mdadm,meminfo,netdev,netstat,stat,textfile,time,vmstat,ipvs"


~~~

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 7
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 66
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: c1y7qpqdobgltvwwwkzxiktod
 Is Manager: true
 ClusterID: 0m9lnp8bpx00ki5gligqmwlzh
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.0.0.139
 Manager Addresses:
  10.0.0.139:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-45-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.675 GiB
Name: ip-10-0-0-139
ID: 2MJO:BNSZ:FLU4:65YT:V7ED:3WY7:NDMM:F5X6:DKCY:VUMO:UXBX:FHU3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: odedpriva
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by adshmh**
Added code to print a hint if not escaping the '$' character in the compose file causes an interpolation format error for docker stack deploy command. Fixes #30629.

Signed-off-by: Arash Deshmeh <adeshmeh@ca.ibm.com>

**- What I did**
When the command 'docker stack deploy' fails due to not escaping the '$' in the compose file, the error message does not indicate the cause of failure. This PR fixes this by adding a hint to the error message.

**- How I did it**
Added a code which checks for '$' and '$$' patterns in the template string if an error is encountered during the interpolation, and adds a hint to the error message if needed.

**- How to verify it**
Run docker stack deploy and specify the --compose-file option. Use the compose file shown in #30629.

- Current behavior:
$ docker stack deploy --compose-file=docker-compose.yml monitoring                                                            
Invalid interpolation format for "command" option in service "node-exporter": "^/(sys|proc|dev|host|etc)($|/)"

- With this PR:
$ docker stack deploy --compose-file=docker-compose.yml monitoring                                                            
Invalid interpolation format for "command" option in service "node-exporter": "^/(sys|proc|dev|host|etc)($|/)". You may need to escape any $ with another $.

**- Description for the changelog**
The error from 'docker stack deploy' includes a hint if the error is caused by '$' delimiter not having been escaped with another '$'.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: cli/compose/interpolation/interpolation.go [hunk 1]
```diff
@@ -38,9 +39,13 @@ func interpolateSectionItem(
 	for key, value := range item {
 		interpolatedValue, err := recursiveInterpolate(value, mapping)
 		if err != nil {
+			hint := ""
+			if strings.Count(err.Template, "$") != 2*strings.Count(err.Template, "$$") {
```
Comment (dnephin) [inline cli/compose/interpolation/interpolation.go]: I'm not sure about this. This will be `true` when there are valid variables as well.

Why don't we just include the hint in all cases? I don't know of any way to detect an incorrect usage.

Comment (adshmh) [inline cli/compose/interpolation/interpolation.go]: Thank you for the review. Just updated the PR. Looking at that check again, I think it also had the issue of being a bit too "low" level for the code that was around it.

**Review by dnephin — APPROVED** [review]
LGTM

**Comment by anusha-ragunathan** [comment]
LGTM
