### PR TITLE
daemon: Improve NetworkingConfig & EndpointSettings validation

### LINKED ISSUE #19418: 1.10-rc1 docker run should not create container if network options are invalid
Related to https://github.com/docker/docker/issues/19417

Docker creates a container, even if the network options are invalid. For example;

``` bash
# docker run --ip=172.17.0.18 -itd --net=bridge busybox sh
14bed02fbc4c9901b4d562844ec3d03e7773259375a07037a2f4062ce0671b17
docker: Error response from daemon: User specified IP address is supported on user defined networks only.
```

The above instruction created a container, and apparently assigned an IP-address

(note that **the same** IP-address is used for each container that fails);

``` json
"Networks": {
    "bridge": {
        "IPAMConfig": {
            "IPv4Address": "172.17.0.18"
        },
        "Links": null,
        "Aliases": null,
        "NetworkID": "",
        "EndpointID": "",
        "Gateway": "",
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "MacAddress": ""
    }
}
```
#### Expected result

No container being created if the passed options are invalid

### PR DESCRIPTION
**Pull request by akerouanton**
- fixes https://github.com/moby/moby/issues/19418

Depends on:

- https://github.com/moby/moby/pull/46182
- https://github.com/moby/moby/pull/46188
- https://github.com/moby/moby/pull/46251

**- What I did**

So far, only a subset of `NetworkingConfig` was validated when calling `ContainerCreate`. Other parameters would be validated when the container was started. And the same goes for `EndpointSettings` on `NetworkConnect`.

Also, the validation code was early exiting as soon as it caught an error. It now tries to validate as much as it can, and returns all the errors.

**- How to verify it**

Testing with the CLI won't work because it has its own client-side layer of validation (although incomplete). Some Go code has to be written to test all validation cases.

**- Description for the changelog**

* `NetworkConnect` and `ContainerCreate` have improved data validation, and now return all validation errors at once.

### CODE REVIEW

File: daemon/create_test.go [hunk 1]
```diff
@@ -1,21 +0,0 @@
...
-import (
-	"testing"
-
-	"github.com/docker/docker/api/types/network"
-	"gotest.tools/v3/assert"
-	is "gotest.tools/v3/assert/cmp"
-)
-
-// Test case for 35752
-func TestVerifyNetworkingConfig(t *testing.T) {
```
Comment (akerouanton) [inline daemon/create_test.go:12]: I'd prefer not to delete this test, and I'd even prefer to expand it to test interesting cases. But given that `verifyNetworkingConfig` is now a method of `daemon`, it's quite hard. I'd have to instantiate a daemon with a working libnetwork controller.

To make it easier to test, I thought about keeping `verifyNetworkingConfig` as a function and add a new `networkFinder func(string) *libnetwork.Network` parameter to it. It'd take `daemon.FindNetwork` in the daemon code, and a mock in this test. However, I'm not sure if that's a common / acceptable pattern.

File: docs/api/version-history.md [hunk 2]
```diff
@@ -38,6 +38,11 @@ keywords: "API, Docker, rcli, REST, documentation"
   specifications directories. The use of the applied setting requires the daemon
   to have expermental enabled, and for non-experimental daemons an empty list is
   always returned.
+* `POST /containers/create` and `POST /networks/{id}/connect` will now catch
+  validation errors that were previously only returned during `POST /containers/{id}/start`.
+  These endpoints will also return the full set of validation errors they find,
+  instead of returning only the first one.
+  Note that this change is _unversioned_ and applies to all API versions.
```
Comment (akerouanton) [inline docs/api/version-history.md:45]: I want to double-check we agree to make this change unversioned before editing Swagger files for older versions.

File: daemon/container_operations.go [hunk 3]
```diff
@@ -574,52 +574,86 @@ func hasUserDefinedIPAddress(ipamConfig *networktypes.EndpointIPAMConfig) bool {
...
 		if len(epConfig.Aliases) > 0 && !serviceDiscoveryOnDefaultNetwork() {
-			return runconfig.ErrUnsupportedNetworkAndAlias
+			errs = append(errs, runconfig.ErrUnsupportedNetworkAndAlias)
 		}
 	}
+
 	if !hasUserDefinedIPAddress(epConfig.IPAMConfig) {
+		return errors.Join(errs...)
+	}
+	if epConfig.IPAMConfig.IPv4Address != "" && net.ParseIP(epConfig.IPAMConfig.IPv4Address).To4() == nil {
```
Comment (thaJeztah) [inline daemon/container_operations.go:599]: Looks like a bunch of these are also done in `buildCreateEndpointOptions`. Wondering if we can extract some of these checks, and make both use the same validation 🤔 https://github.com/moby/moby/blob/220fba06e7ebd6798f24fa690ba9069067ecea86/daemon/network.go#L808-L838

File: daemon/container_operations.go [hunk 4]
```diff
@@ -574,52 +574,86 @@ func hasUserDefinedIPAddress(ipamConfig *networktypes.EndpointIPAMConfig) bool {
...
+			errs = append(errs, fmt.Errorf("invalid IPv6 address: %s", epConfig.IPAMConfig.IPv6Address))
+		}
+	}
+	for _, addr := range epConfig.IPAMConfig.LinkLocalIPs {
+		if net.ParseIP(addr) == nil {
+			errs = append(errs, fmt.Errorf("invalid link-local IP address %s", addr))
+		}
+	}
+
+	if nw == nil {
```
Comment (thaJeztah) [inline daemon/container_operations.go:616]: This validation is called from 2 places;

In `Daemon.updateNetworkConfig()`;

```go
if err := validateEndpointSettings(n, n.Name(), endpointConfig); err != nil {
	return err
}
```

In `Daemon.validateNetworkingConfig()`;

```go
// The referenced network k might not exist when the container is created, so don't fail if that's the case.
// If any other error happen, it's not a validation error, so better early exit.
nw, err := daemon.FindNetwork(k)
if err != nil && !errdefs.IsNotFound(err) {
	return err
}

if err := validateEndpointSettings(nw, k, v); err != nil {
	errs = append(errs, fmt.Errorf("invalid endpoint config for network %s: %w", k, err))
}
```

- in both cases, I think we'd already barf out if the network is not to be found
- and, I think in both cases `nwName` is effectively equivalent to `nw.Name()` (although I'm not 100% sure for the second case; can it use network ID instead of name? does that matter for this case?)

So I'm wondering if we should continue to bail out early if there's no network (instead of continuing with other checks), as we probably would never reach this validation

Also slightly looking if we should split "heavy" and "lightweight" validation; e.g. validating for invalid / invalidly formatted IP-addresses is something that's relatively lightweight, whereas fetching the network (knowing libnetwork ...) may "not be". From that perspective we could potentially do a quick check on well-formed-ness of options (we should really look if we can do such parsing/conversions earlier, and get to a "strong-type" ASAP in the process, as we're sometimes parsing the same string multiple times), and only if we get that far, proceed with the heavier lifting.

File: daemon/container_operations.go [hunk 5]
```diff
@@ -574,52 +574,86 @@ func hasUserDefinedIPAddress(ipamConfig *networktypes.EndpointIPAMConfig) bool {
...
+func validateEndpointSettings(nw *libnetwork.Network, nwName string, epConfig *networktypes.EndpointSettings) error {
+	if epConfig == nil {
 		return nil
 	}
-	if !containertypes.NetworkMode(n.Name()).IsUserDefined() {
+
+	var errs []error
+	if !containertypes.NetworkMode(nwName).IsUserDefined() {
+		// On Linux, user specified IP address is accepted only for networks with user specified subnets.
 		if hasUserDefinedIPAddress(epConfig.IPAMConfig) && !enableIPOnPredefinedNetwork() {
```
Comment (thaJeztah) [inline daemon/container_operations.go:588]: Just an observation here; 

-  `hasUserDefinedIPAddress()` will always be `false` if there's no ipamConfig, which _may_ already invalidate other checks.
- ^^ slightly leaning toward inlining that function here, and just make it a `hasUserDefinedIPAddress` variable that we set (and use), as that function is _only_ used inside this check, and we're now potentially calling it twice with the same results
- _BOTH_ `enableIPOnPredefinedNetwork` and `serviceDiscoveryOnDefaultNetwork` are effectively `if runtime.GOOS == "windows"`)
- ^^ wondering if we need to split the _validation_ there, instead of having two utility functions that effectively means "different validation on windows vs linux" (not sure)

**Review by thaJeztah — COMMENTED** [review]
Just some quick comments from having a first glance.

File: daemon/container_operations.go (hunk 4 above)
Comment (akerouanton) [reply daemon/container_operations.go:616]: > in both cases, I think we'd already barf out if the network is not to be found

Nope, we actually accept a `ContainerCreate` request with a reference to a non-existant network:

https://github.com/moby/moby/blob/b227bc4c7caad4267e5c7af8cba8687a8b8ab6a8/daemon/container_operations.go#L577-L580

It's not a hypothetical case, it's how things are working right now :wink:  

```
$ docker network inspect foobar
[]
Error response from daemon: network foobar not found

$ docker container create --network foobar busybox
6697a506ee56c76d770218b49794255b8059a0f6deec836a0c26778379612b6a
```

> we should really look if we can do such parsing/conversions earlier, and get to a "strong-type" ASAP in the process

Yeah, I looked into this a bit already. I'd like to have `netip.*` instead of strings, as it'd remove the need of constantly parsing the same thing. But that's imply quite a bunch of work. I did had time to create the CLI PR that depends on this one, but it all have to do with the ability to provide multiple `--network` flags, hence I'd prefer to keep this one simple.

File: daemon/create.go [hunk 6]
```diff
@@ -324,24 +322,29 @@ func verifyNetworkingConfig(nwConfig *networktypes.NetworkingConfig) error {
...
-				if n == nil || n.To4() != nil {
-					return fmt.Errorf("invalid IPv6 address: %s", v.IPAMConfig.IPv6Address)
-				}
-			}
+
+		// The referenced network k might not exist when the container is created, so don't fail if that's the case.
+		// If any other error happen, it's not a validation error, so better early exit.
+		nw, err := daemon.FindNetwork(k)
+		if err != nil && !errdefs.IsNotFound(err) {
+			return err
```
Comment (thaJeztah) [inline daemon/create.go:336]: What error can we expect here, and would we still have a network?

oh.. I guess that's the case you described 🤦 I that's not related to lazy creating networks, I'm on the fence of being ok erroring out for that

File: docs/api/version-history.md (hunk 2 above)
Comment (akerouanton) [reply docs/api/version-history.md:45]: Discussed during maintainers' call, and that's okay.

File: daemon/container_operations.go (hunk 5 above)
Comment (akerouanton) [reply daemon/container_operations.go:588]: Hm, most of these would be better handled in their own PR. Also, the next step once we get proper support for multi `--network` flags, is to make the default bridge just a "normal" bridge (ie. no more links, no more artificial restriction, etc...). So better keep these refactorings for that time (unless you want to go ahead and do this beforehand).

File: daemon/create.go [hunk 7]
```diff
@@ -324,24 +323,29 @@ func verifyNetworkingConfig(nwConfig *networktypes.NetworkingConfig) error {
...
-				// if the address is an invalid network address (ParseIP == nil) or if it is
-				// an IPv4 address (To4() != nil), then it is an invalid IPv6 address
-				if n == nil || n.To4() != nil {
-					return fmt.Errorf("invalid IPv6 address: %s", v.IPAMConfig.IPv6Address)
-				}
-			}
+
+		// The referenced network k might not exist when the container is created, so don't fail if that's the case.
+		nw, err := daemon.FindNetwork(k)
+		if err != nil && !errdefs.IsNotFound(err) {
```
Comment (akerouanton) [inline daemon/create.go:335]: The test `TestCreateWithDuplicateNetworkNames` from the `service` suite is failing because this condition will return a validation error if two networks with conflicting names are created.

Instead of working around this, I drop `TestCreateWithDuplicateNetworkNames` in #46251.

File: daemon/container_operations.go (hunk 5 above)
Comment (akerouanton) [reply daemon/container_operations.go:589]: > * BOTH `enableIPOnPredefinedNetwork` and `serviceDiscoveryOnDefaultNetwork` are effectively if runtime.GOOS == "windows")
> * ^^ wondering if we need to split the validation there, instead of having two utility functions that effectively means "different validation on windows vs linux" (not sure)

I added a `TODO` to remind us we should remove these functions once we remove legacy networking mode from the default bridge. As such, I think we shouldn't make the validation OS-dependent here, as it's going to be addressed (hopefully) soon.

File: daemon/container_operations.go (hunk 3 above)
Comment (akerouanton) [reply daemon/container_operations.go:600]: As shared privately, for now we can't really drop the validation steps in `buildCreateEndpointOptions`. We first need to make some refactorings to make sure user-supplied data are correctly sanitized and transformed into useful structs instead of keeping literals everywhere.

This will be addressed in a follow-up PR.

File: daemon/container_operations.go [hunk 8]
```diff
@@ -562,54 +563,57 @@ func (daemon *Daemon) allocateNetwork(cfg *config.Config, container *container.C
...
-			return runconfig.ErrUnsupportedNetworkAndAlias
+			errs = append(errs, runconfig.ErrUnsupportedNetworkAndAlias)
 		}
 	}
-	if !hasUserDefinedIPAddress(epConfig.IPAMConfig) {
-		return nil
+
+	// TODO(aker): add a proper multierror.Append
+	if err := ipamConfig.Validate(); err != nil {
+		errs = append(errs, err.(interface{ Unwrap() []error }).Unwrap()...)
```
Comment (akerouanton) [inline daemon/container_operations.go:595]: I don't like this, we need a proper `multierror.Append` instead. But I think it's ok to address that in a follow-up PR. @thaJeztah Any thoughts?

File: api/types/network/endpoint.go [hunk 9]
```diff
@@ -108,7 +108,7 @@ func (ipamConfig *EndpointIPAMConfig) Validate() error {
 	}
 	for _, addr := range ipamConfig.LinkLocalIPs {
 		if net.ParseIP(addr) == nil {
-			errs = append(errs, fmt.Errorf("invalid link-local IP address %s", addr))
+			errs = append(errs, fmt.Errorf("invalid link-local IP address: %s", addr))
```
Comment (thaJeztah) [inline api/types/network/endpoint.go]: I wanted to suggest: could we use the underlying `netip.Parse` instead, so that we can return an actual error with details "what is invalid"??

... only to realise that's new in Go 1.21 https://github.com/golang/go/blob/2c1e5b05fe39fc5e6c730dd60e82946b8e67c6ba/src/net/ip.go#L489-L502

File: libnetwork/network.go [hunk 10]
```diff
@@ -173,7 +173,7 @@ type Network struct {
 	created          time.Time
 	scope            string // network data scope
 	labels           map[string]string
-	ipamType         string
+	ipamType         string // ipamType is the name of the IPAM driver
```
Comment (thaJeztah) [inline libnetwork/network.go:176]: Maybe we should rename this to `ipamDriver` at some point  😂

File: libnetwork/network.go [hunk 11]
```diff
@@ -71,6 +71,7 @@ type networkDBTable struct {
 }
 
 // IpamConf contains all the ipam related configurations for a network
+// TODO(aker): use proper net/* structs instead of string literals.
```
Comment (thaJeztah) [inline libnetwork/network.go:74]: If you're updating, can you add an empty line in between? ISTR GoDoc can hide "TODO" comments in the generated documentation as long as there's an empty comment-line in between, so;


```go
// IpamConf contains all the ipam related configurations for a network.
//
// TODO(aker): use proper net/* structs instead of string literals.
```


(LOL, also this struct should really be named `IPAMConf` (to be properly camelcase, but that's a different topic)

**Review by thaJeztah — COMMENTED** [review]
overall looks good; there were some changes that landed in the wrong commit, so left comments about those, and I left a comment about a commit (renaming `cfg => ipamConfig`) that I _think_ would be ok to squash with the commit after it)

File: daemon/container_operations.go (hunk 4 above)
Comment (akerouanton) [reply daemon/container_operations.go]: Thanks for the digging! 

> * Always have the network "available" on every node (but it could be a "definition-only" for dynamically rolled-out networks)
> * Or, for attachable networks, and a container attaching to it, we could still consider to initialize it when attaching

Once this PR is merged, I'll submit a follow-up refactor PR to move attachment requests out of `findAndAttachNetwork` to a dedicated method called before doing anything else in `initializeNetworking`. With that change:

* On `ContainerCreate`, only soundness checks will be done ;
* On `ContainerStart` (and `NetworkConnect`), we'll determine whether referenced network exists locally, attach it if it's swarm scoped, or bail out because if it doesn't. And then, we can normalize and validate the settings thoroughly ;

I started doing some work in that direction here: https://github.com/moby/moby/commit/fba50d67d4a4c461c461732c2e1bc34e7e95eff5.

I think it'd be "conceptually" better to go back to the original semantic: _you can only attach to a network that exists locally_; but it'd be more work to implement and I guess we'd probably need to gate that behind an API version check, so anyway... I think we can get the same result by shuffling a bit the order of operations.

File: daemon/create.go [hunk 12]
```diff
@@ -321,30 +320,24 @@ func (daemon *Daemon) mergeAndVerifyConfig(config *containertypes.Config, img *i
...
-				n := net.ParseIP(v.IPAMConfig.IPv6Address)
-				// if the address is an invalid network address (ParseIP == nil) or if it is
-				// an IPv4 address (To4() != nil), then it is an invalid IPv6 address
-				if n == nil || n.To4() != nil {
-					return fmt.Errorf("invalid IPv6 address: %s", v.IPAMConfig.IPv6Address)
-				}
-			}
+
+		nw, _ := daemon.FindNetwork(k)
+		if err := validateEndpointSettings(nw, k, v); err != nil {
```
[the remark this answers is not in the document]
Comment (akerouanton) [reply daemon/create.go]: > However, it may still be an indicator that this function is trying to do too much

Mh, I have fixed feelings about whether it does too much things or not. But once the refactor PR I mentioned previously is merged, `attachSwarmNetworks` will happen first and we'll be able to take for granted that _all_ networks exist when we start validation. This should make the code easier to follow, and help us draw a line between the "soundness checks" I mentioned and in-depth validation.

As some of this is already addressed in `
daemon: move most of validateEndpointSettings into api/t/net`, I'll keep the code as-is in this commit.

File: integration-cli/docker_cli_network_unix_test.go [hunk 13]
```diff
@@ -1289,9 +1289,9 @@ func (s *DockerNetworkSuite) TestDockerNetworkConnectPreferredIP(c *testing.T) {
 	verifyIPAddresses(c, "c0", "n0", "172.28.99.88", "2001:db8:1234::9988")
 
 	// connect the container to the second network specifying an ip addresses
-	dockerCmd(c, "network", "connect", "--ip", "172.30.55.44", "--ip6", "2001:db8:abcd::5544", "n1", "c0")
-	verifyIPAddressConfig(c, "c0", "n1", "172.30.55.44", "2001:db8:abcd::5544")
-	verifyIPAddresses(c, "c0", "n1", "172.30.55.44", "2001:db8:abcd::5544")
+	dockerCmd(c, "network", "connect", "--ip", "172.30.5.44", "--ip6", "2001:db8:abcd::5544", "n1", "c0")
```
[the remark this answers is not in the document]
Comment (akerouanton) [reply integration-cli/docker_cli_network_unix_test.go:1292]: Looking at the file, I guess the issue was that two tests were using the same subnet and addresses, which could lead to some collisions.

File: api/types/network/endpoint.go (hunk 9 above)
Comment (akerouanton) [reply api/types/network/endpoint.go]: Good catch!

> ... only to realise that's new in Go 1.21

`netip.ParseAddr` is actually available since go 1.18, so we can perfectly use it. But looking at the git blame, it looks like `net` parsers will use `netip` ones starting with go 1.21.

As a consequence, we might start accepting IPv6 addresses with scope zone (eg. `fe80::1cc0:3e8c:119f:c2e1%ens18`), whereas it's invalid. I need to double-check but we probably need a proper error for that.

File: api/types/network/endpoint.go [hunk 14]
```diff
@@ -46,9 +46,9 @@ type EndpointIPAMConfig struct {
...
-func (cfg *EndpointIPAMConfig) Copy() *EndpointIPAMConfig {
-	cfgCopy := *cfg
-	cfgCopy.LinkLocalIPs = make([]string, 0, len(cfg.LinkLocalIPs))
-	cfgCopy.LinkLocalIPs = append(cfgCopy.LinkLocalIPs, cfg.LinkLocalIPs...)
+func (ipamConfig *EndpointIPAMConfig) Copy() *EndpointIPAMConfig {
+	cfgCopy := *ipamConfig
+	cfgCopy.LinkLocalIPs = make([]string, 0, len(ipamConfig.LinkLocalIPs))
+	cfgCopy.LinkLocalIPs = append(cfgCopy.LinkLocalIPs, ipamConfig.LinkLocalIPs...)
 	return &cfgCopy
 }
```
[the remark this answers is not in the document]
Comment (akerouanton) [reply api/types/network/endpoint.go]: I went the other way around and dropped this commit as I think it's okay to stick to `cfg`.

File: api/types/network/endpoint.go (hunk 9 above)
Comment (akerouanton) [reply api/types/network/endpoint.go]: Huh, that's what errors `netip.ParseAddr(...)` produces: `ParseAddr("foo"): unable to parse IP`. So, it'd look like this if we use it here:

```
* invalid IPv4 address foo: ParseAddr("foo"): unable to parse IP
* invalid IPv6 address bar: ParseAddr("bar"): unable to parse IP
* invalid link-local IP address baz: ParseAddr("baz"): unable to parse IP
* invalid link-local IP address foobar: ParseAddr("foobar"): unable to parse IP
```

I think we should rather stick with `net.ParseIP`.

Comment (thaJeztah) [reply api/types/network/endpoint.go]: Ah, yes, that doesn't provide much more context indeed. I was hoping it would give the user more context what's wrong. Thanks for looking!

**Review by thaJeztah — APPROVED** [review]
LGTM

File: daemon/container_operations.go (hunk 4 above)
Comment (thaJeztah) [reply daemon/container_operations.go]: > I think it'd be "conceptually" better to go back to the original semantic: you can only attach to a network that exists locally; but it'd be more work to implement and I guess we'd probably need to gate that behind an API version check, so anyway... I think we can get the same result by shuffling a bit the order of operations.

Yes, we need to look at that! I guess overall the tricky bit is that we must assume that there's potentially many nodes and many networks, and not all of those networks to be used on each node.

- For "attachable" networks, it would be good to have a ("stub?") network on each node, so that `docker network attache` can be used for containers; we could probably still make it a stub (so that it doesn't take up resources on _all notes_ in the swarm), and make it an actual network when attaching.
- For "non-attachable" networks, I guess it's TBD; do we want to show stubs for those? (if it's a _worker_ node, the worker itself wouldn't have much purpose for it until a swarm task lands on the node).
- For _managers_ it would be more useful (as you could run `docker network rm <some swarm-scope network>`)


Either way; all of that is for a follow-up discussion. We could create a ticket for it though (perhaps copy/paste some of the above)
