### PR TITLE
volume/mounts: fix anonymous volume not being labeled

### LINKED ISSUE #48748: anonymous volumes created using `--mount` don't get AnonymousLabel set
### Description

Engine's volume service uses `com.docker.volume.anonymous` label to detect anonymous volumes created by engine.
This only applies when volume is created using the `bind` API, not when using the more recent `mount` one.

### Reproduce

1.  docker run --mount="type=volume,target=/toto" hello-world
2. docker inspect to retrieve anonymous volume created by command
3. confirm "Labels": null,

### Expected behavior

label "com.docker.volume.anonymous" is set, same as using `--volume`

### docker version

```console
Client:
 Version:           27.2.0
 API version:       1.47
 Go version:        go1.21.13
 Git commit:        3ab4256
 Built:             Tue Aug 27 14:14:45 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.34.3 (170107)
 Engine:
  Version:          27.2.0
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.21.13
  Git commit:       3ab5c7d
  Built:            Tue Aug 27 14:15:41 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.7.20
  GitCommit:        8fc6bcff51318944179630522a095cc9dbf9f353
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```console
Client:
 Version:    27.2.0
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.13.1-desktop.1
    Path:     /Users/nicolas/.pinata/downloads/docker-plugins/v0.13.1-desktop.1/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7-30-g82417bd5b
    Path:     /Users/nicolas/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.34
    Path:     /Users/nicolas/.docker/cli-plugins/docker-debug
  desktop: Docker Desktop commands (Alpha) (Docker Inc.)
    Version:  v0.0.15
    Path:     /Users/nicolas/.docker/cli-plugins/docker-desktop
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /Users/nicolas/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.25
    Path:     /Users/nicolas/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     /Users/nicolas/.docker/cli-plugins/docker-feedback
  harmonia: Extend your localhost with cloud workspaces (Docker Inc.)
    Version:  0.13.135
    Path:     /Users/nicolas/.docker/cli-plugins/docker-harmonia
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.3.0
    Path:     /Users/nicolas/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/nicolas/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.13.0
    Path:     /Users/nicolas/.docker/cli-plugins/docker-scout

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 7
 Server Version: 27.2.0
 Storage Driver: overlayfs
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fc6bcff51318944179630522a095cc9dbf9f353
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.10.4-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 10
 Total Memory: 7.655GiB
 Name: docker-desktop
 ID: 47214cae-1686-4c29-8107-9e258a860ebc
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///Users/nicolas/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Additional Info

initially reported as https://github.com/docker/compose/issues/10833

### PR DESCRIPTION
**Pull request by thaJeztah**
- fixes https://github.com/moby/moby/issues/48748
- addresses https://github.com/docker/compose/issues/10833
- relates to https://github.com/moby/moby/commit/b3b7eb2723461b1eb4be692f4bced0ae8ea9cb58 / https://github.com/moby/moby/pull/14242
- relates to https://github.com/moby/moby/commit/fc7b904dced4d18d49c8a6c47ae3f415d16d0c43 / https://github.com/moby/moby/pull/22373
- relates to https://github.com/moby/moby/pull/44216

### volume/mounts: fix anonymous volume not being labeled

`Parser.ParseMountRaw()` labels anonymous volumes with a `AnonymousLabel` label (`com.docker.volume.anonymous`) label based on whether a volume has a name (named volume) or no name (anonymous) (see [1]).

However both `VolumesService.Create()` (see [1]) and `Parser.ParseMountRaw()` (see [2], [3]) were generating a random name for anonymous volumes. The latter is called before `VolumesService.Create()` is called, resulting in such volumes not being labeled as anonymous.

Generating the name was originally done in Create (fc7b904dced4d18d49c8a6c47ae3f415d16d0c43), but duplicated in b3b7eb2723461b1eb4be692f4bced0ae8ea9cb58 with the introduction of the new Mounts field in HostConfig. Duplicating this effort didn't have a real effect until (`Create` would just skip generating the name), until 618f26ccbc3b5c314680dae4b09f5d13f9c02570 introduced the `AnonymousLabel` in (v24.0.0, backported to v23.0.0).

Parsing generally should not fill in defaults / generate names, so this patch;

- Removes generating volume names from  `Parser.ParseMountRaw()`
- Adds a debug-log entry to `VolumesService.Create()`
- Touches up some logs to use structured logs for easier correlating logs

With this patch applied:

    docker run --rm --mount=type=volume,target=/toto hello-world

    DEBU[2024-10-24T22:50:36.359990376Z] creating anonymous volume                     volume-name=0cfd63d4df363571e7b3e9c04e37c74054cc16ff1d00d9a005232d83e92eda02
    DEBU[2024-10-24T22:50:36.360069209Z] probing all drivers for volume                volume-name=0cfd63d4df363571e7b3e9c04e37c74054cc16ff1d00d9a005232d83e92eda02
    DEBU[2024-10-24T22:50:36.360341209Z] Registering new volume reference              driver=local volume-name=0cfd63d4df363571e7b3e9c04e37c74054cc16ff1d00d9a005232d83e92eda02

[1]: https://github.com/moby/moby/blob/032721ff75fe4a71a45b4a7a9b7e7c4c80c6431b/volume/service/service.go#L72-L83
[2]: https://github.com/moby/moby/blob/032721ff75fe4a71a45b4a7a9b7e7c4c80c6431b/volume/mounts/linux_parser.go#L330-L336
[3]: https://github.com/moby/moby/blob/032721ff75fe4a71a45b4a7a9b7e7c4c80c6431b/volume/mounts/windows_parser.go#L394-L400

**- How to verify it**

```bash
make TEST_FILTER='TestContainerVolumeAnonymous' TEST_SKIP_INTEGRATION_CLI=1 DOCKER_GRAPHDRIVER=vfs test-integration

=== RUN   TestContainerVolumeAnonymous
--- PASS: TestContainerVolumeAnonymous (0.02s)
PASS

DONE 1 tests in 1.225s
```

**- Description for the changelog**

```markdown changelog
Fix anonymous volumes being created through the `--mount` option not being marked as anonymous.
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
@neersighted this one's for you (https://github.com/docker/compose/issues/10833) 😄

**Review by vvoland — APPROVED** [review]
LGTM; good catch!

**Comment by thaJeztah** [comment]
> good catch!

Thanks for @ndeloof for finding the discrepancy.

I initially thought the problem was here; with `Daemon.registerMountPoints()` adding `volumeopts.WithCreateLabels()`;
https://github.com/moby/moby/blob/d3c3a74982a119220ef7086eb3aaa6c028f8977b/daemon/volumes.go#L210-L216

And `VolumeService.Create` using `opts.WithCreateLabel()` https://github.com/moby/moby/blob/032721ff75fe4a71a45b4a7a9b7e7c4c80c6431b/volume/service/service.go#L72-L76

Because if they are applied in the reverse order, then  `volumeopts.WithCreateLabels()` will overwrite the other label that's set; `WithCreateLabel()` merges, but `WithCreateLabels()` doesn't;
https://github.com/moby/moby/blob/d3c3a74982a119220ef7086eb3aaa6c028f8977b/volume/service/opts/opts.go#L15-L22

https://github.com/moby/moby/blob/d3c3a74982a119220ef7086eb3aaa6c028f8977b/volume/service/opts/opts.go#L26-L30

**Review by austinvazquez — APPROVED** [review]

**Review by ndeloof — APPROVED** [review]

**Comment by thaJeztah** [comment]
three LGTM's - works for me; thanks!

File: volume/service/service.go [hunk 1]
```diff
@@ -73,6 +73,9 @@ func (s *VolumesService) Create(ctx context.Context, name, driverName string, op
 	if name == "" {
 		name = stringid.GenerateRandomID()
 		options = append(options, opts.WithCreateLabel(AnonymousLabel, ""))
+		log.G(ctx).WithField("volume-name", name).Error("Creating anonymous volume")
+	} else {
+		log.G(ctx).WithField("volume-name", name).Error("Creating named volume")
```
Comment (thaJeztah) [inline volume/service/service.go:78]: Whoops; I left these as `Error()` log instead of `Debug()` 🙈 

- https://github.com/moby/moby/pull/48767
