### PR TITLE
TestContainerAPITop: fix flakyness

### LINKED ISSUE #37109: Flaky test: TestContainerAPITop
Seen this fail a few times; 

https://jenkins.dockerproject.org/job/Docker-PRs-powerpc/9921/console

- https://github.com/moby/moby/pull/32268#issuecomment-291645360
- https://github.com/moby/moby/pull/36511#issuecomment-382216564
- https://github.com/moby/moby/pull/37106#issuecomment-390403351

```
11:31:27 FAIL: docker_api_containers_test.go:435: DockerSuite.TestContainerAPITop
11:31:27 
11:31:27 docker_api_containers_test.go:453:
11:31:27     c.Assert(top.Processes[0][10], checker.Equals, "/bin/sh -c top")
11:31:27 ... obtained string = "top"
11:31:27 ... expected string = "/bin/sh -c top"
11:31:27 
```

### PR DESCRIPTION
**Pull request by kolyshkin**
The following failure is seen in CI from time to time:

> FAIL: docker_api_containers_test.go:435: DockerSuite.TestContainerAPITop
>
> docker_api_containers_test.go:453:
>     c.Assert(top.Processes[0][10], checker.Equals, "/bin/sh -c top")
> ... obtained string = "top"
> ... expected string = "/bin/sh -c top"

The test case expects two processes in the output:

1. /bin/sh -c top
2. top

in the given order.

Now, "ps aux" output is sorted by PID`*`, and so since the "top" is a child of "/bin/sh -c top" it has a higher PID and will come second as expected by the test... unless the PIDs on the system are exhausted and PID rollover happens, in which case PID of "top" will be lower than that of "/bin/sh".

The obvious fix is to sort ps output by command line.

Should fix https://github.com/moby/moby/issues/37109

`*`  in fact it is not sorted, but is being printed in the same order as the kernel list PID entries in /proc directory, which appears to be sorted by PID (see ls -1 -U /proc).

### CODE REVIEW

File: integration-cli/docker_api_containers_test.go [hunk 1]
```diff
@@ -442,7 +442,8 @@ func (s *DockerSuite) TestContainerAPITop(c *check.C) {
 	c.Assert(err, checker.IsNil)
 	defer cli.Close()
 
-	top, err := cli.ContainerTop(context.Background(), id, []string{"aux"})
+	// sort by comm[andline] to make sure order stays the same in case of PID rollover
+	top, err := cli.ContainerTop(context.Background(), id, []string{"aux", "--sort", "comm"})
```
Comment (cpuguy83) [inline integration-cli/docker_api_containers_test.go]: Only problem here is not all `ps` implementations support `--sort`.
Maybe we can check for either `sh` or `top` in the first assertion, and then the other in the next assertion.

**Review by cpuguy83 — CHANGES_REQUESTED** [review]

File: integration-cli/docker_api_containers_test.go (hunk 1 above)
Comment (kolyshkin) [reply integration-cli/docker_api_containers_test.go]: 1. Note that the ps is run on the host, not inside container.
2. If you refer to ps from busybox, it won't work either since it ignores the `aux` flags and so the expected fields won't be there.
3. I looked around and can't find a version of `ps` which correctly supports `aux` but does not support `--sort=comm`. The obvious exception is busybox (e.g. alpine) but see 2.

Comment (kolyshkin) [reply integration-cli/docker_api_containers_test.go]: I took a look, flag `--sort` in both procps and procps-ng can be traced back to the first CVS commit in Feb 2002, and it seems it supported `--sort=comm` at that time. For the pre-CVS time, I checked sources of procps-0.99 (from April 1996) and the --sort flag is there, but it looks like long sort field specs are not supported.

Comment (thaJeztah) [reply integration-cli/docker_api_containers_test.go]: if order is not important, we could also just split the output and check if not `top` and `/bin/sh -c top` occur in the output (at any position)

Comment (kolyshkin) [reply integration-cli/docker_api_containers_test.go]: I think this PR is good as it is, unless there is a version of `ps` which supports `aux` but does not support `--sort`. I was not able to find such a beast.

Comment (kolyshkin) [reply integration-cli/docker_api_containers_test.go]: @cpuguy83 PTAL

**Review by thaJeztah — APPROVED** [review]
LGTM

but still wondering why this has become flaky recently (and not so much before)

**Comment by thaJeztah** [comment]
interesting that this one failed; should've been fixed in https://github.com/moby/moby/pull/37076 + https://github.com/moby/moby/pull/37086 (but perhaps this wasn't rebased yet to have those changes)

```
19:14:50 FAIL: docker_cli_exec_unix_test.go:18: DockerSuite.TestExecInteractiveStdinClose
19:14:50 
19:14:50 docker_cli_exec_unix_test.go:40:
19:14:50     c.Assert(strings.TrimSpace(output), checker.Equals, "hello")
19:14:50 ... obtained string = "hello\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
19:14:50 ... expected string = "hello"
```

**Comment by kolyshkin** [comment]
> but still wondering why this has become flaky recently (and not so much before)

This is actually pretty interesting.

I guess the reason is some more tests that run before this one were added (or removed) recently, resulting in the situation when the `last_pid` (a variable in the kernel holding the value of the least recently allocated PID) is equal to `pid_max-1` (or so), resulting in PID rollover happening at the "right" moment (right before `sh` is about to fork itself to run `top`).

The theoretical probability of this happening should be something like 1/32768, or 0.003% -- so it feels like winning a jack pot (with the price being a test case failure). But given the fact our test suite is more deterministic (in terms of how many forks it generates before running this specific test case), the practical probability is higher -- all it takes to hit the snag is add (or remove) some test cases resulting in more (or less) forks.

**Comment by kolyshkin** [comment]
> interesting that this one failed

rebased

File: integration-cli/docker_api_containers_test.go [hunk 2]
```diff
@@ -450,6 +451,11 @@ func (s *DockerSuite) TestContainerAPITop(c *check.C) {
 		c.Fatalf("expected `USER` at `Titles[0]` and `COMMAND` at Titles[10]: %v", top.Titles)
 	}
 	c.Assert(top.Processes, checker.HasLen, 2, check.Commentf("expected 2 processes, found %d: %v", len(top.Processes), top.Processes))
+
+	// sort by command name to make sure order stays the same in case of PID rollover
+	sort.Slice(top, func(i, j int) bool {
+		return top.Processes[i][10] < top.Processes[j][10]
+	}
```
Comment (thaJeztah) [inline integration-cli/docker_api_containers_test.go]: Missing a closing `)` here? 

```
00:36:47 # github.com/docker/docker/integration-cli
00:36:47 integration-cli/docker_api_containers_test.go:458:3: missing ',' before newline in argument list
00:36:47 integration-cli/docker_api_containers_test.go:459:66: missing ',' before newline in argument list
00:36:47 integration-cli/docker_api_containers_test.go:460:55: missing ',' before newline in argument list
00:36:47 integration-cli/docker_api_containers_test.go:461:1: expected operand, found '}'
00:36:47 integration-cli/docker_api_containers_test.go:471:2: missing ',' in argument list
00:36:47 integration-cli/docker_api_containers_test.go:473:11: missing ',' in argument list
00:36:47 integration-cli/docker_api_containers_test.go:474:30: missing ',' before newline in argument list
00:36:47 integration-cli/docker_api_containers_test.go:475:121: missing ',' before newline in argument list
00:36:47 integration-cli/docker_api_containers_test.go:477:2: expected operand, found 'if'
00:36:47 integration-cli/docker_api_containers_test.go:478:100: missing ',' before newline in argument list
00:36:47 integration-cli/docker_api_containers_test.go:479:2: expected operand, found '}'
```

Comment (kolyshkin) [reply integration-cli/docker_api_containers_test.go]: whoops, I have committed the wrong version. fixed

**Review by vdemeester — APPROVED** [review]
LGTM :lion:

File: integration-cli/docker_api_containers_test.go (hunk 2 above)
Comment (thaJeztah) [reply integration-cli/docker_api_containers_test.go]: LOL, already was thinking: "this looked different"?

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Comment by thaJeztah** [comment]
@cpuguy83's review comment was;

> Only problem here is not all ps implementations support --sort.

But looks like that question was answered; also if we _would_ encounter that problem, it would show up as a failure, so I guess we can take that risk.

I'll go ahead and merge (because it's 💚)
