### PR TITLE
merge default address pool flags with daemon config

### LINKED ISSUE #40388: dockerd ignores the --default-address-pool option
**Description**

dockerd ignores the --default-address-pool option.

**Steps to reproduce the issue:**
```
$ cat empty.json
{}

$ cat daemon.json
{
        "default-address-pools": [ { "base": "10.123.0.0/16", "size": 24 } ]
}

$ dockerd --config-file daemon.json

$ while true; do docker network create n1 > /dev/null; docker network inspect n1 --format '{{json .}}' | jq .IPAM.Config[0].Subnet; docker network rm n1 > /dev/null; done
"10.123.1.0/24"
"10.123.2.0/24"
"10.123.3.0/24"
"10.123.4.0/24"
"10.123.5.0/24"
"10.123.6.0/24"
"10.123.7.0/24"
...

$ dockerd --default-address-pool 'base=10.123.0.0,size=24' --config-file empty.json

$ while true; do docker network create n1 > /dev/null; docker network inspect n1 --format '{{json .}}' | jq .IPAM.Config[0].Subnet; docker network rm n1 > /dev/null; done
"172.17.0.0/16"
"172.18.0.0/16"
"172.19.0.0/16"
"172.20.0.0/16"
"172.21.0.0/16"
"172.22.0.0/16"
"172.23.0.0/16"
"172.24.0.0/16"
"172.25.0.0/16"
"172.26.0.0/16"
"172.27.0.0/16"
"172.28.0.0/16"
"172.29.0.0/16"
"172.30.0.0/16"
"172.31.0.0/16"
"192.168.0.0/20"
"192.168.16.0/20"
"192.168.32.0/20"
"192.168.48.0/20"
"192.168.64.0/20"
"192.168.80.0/20"
"192.168.96.0/20"
"192.168.112.0/20"
"192.168.128.0/20"
"192.168.144.0/20"
"192.168.160.0/20"
"192.168.176.0/20"
"192.168.192.0/20"
"192.168.208.0/20"
"192.168.224.0/20"
"192.168.240.0/20"
"172.17.0.0/16"
...
```

**Describe the results you received:**
docker network create uses "172.*.0.0/16" and "192.168.*.0/20" networks.

**Describe the results you expected:**
docker network create should use "10.123.*.0/24" networks, which are specified by the --default-address-pool option.

**Additional information you deem important (e.g. issue happens only occasionally):**
```
$ dockerd --help
...
      --default-address-pool pool-options       Default address pools for node specific local networks
...
```
Can be confusing, because the name of the option in the daemon.json is plurar and the option on the CLI is singular.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-74-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.64GiB
 Name: REDACTED
 ID: SF2M:PRNH:SXW4:2MR2:WNUL:6JIA:UQUA:7BAW:Q4CW:GE3G:YL3V:V75F
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true

WARNING: No swap limit support```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by wangyumu**
**- What I did**
Fixes #40388

> - if the given configuration file does not contain `default-address-pools`, it should not reset the value set on the command-line, _Originally posted by @thaJeztah in https://github.com/moby/moby/issues/40388#issuecomment-576238514_

this PR will fix the bug that cause `dockerd ignores the --default-address-pool option`

**- How I did it**

We use `mergo.Merge` to merge the options from command-line and daemon.json, but `Mergo won't merge unexported (private) fields` (see https://github.com/imdario/mergo#usage), that's why `default-address-pool` were ignored.

So I just change `values` to `Values` of PoolsOpt struct. 

**- How to verify it**
Steps to verify:
```
# cat empty.json
{}
# dockerd --default-address-pool 'base=10.123.0.0/16,size=24' --config-file empty.json
# docker network create n1 > /dev/null && docker network inspect n1 --format '{{json .}}' | jq .IPAM.Config[0].Subnet
"10.123.1.0/24"
```
it successfully allocate from the default pool set on command-line

### CODE REVIEW

**Comment by wangyumu** [comment]
@thaJeztah PTAL, thanks.

**Comment by thaJeztah** [comment]
> Mergo won't merge unexported (private) fields

Ah, hm, good call


Do you think it would be possible to have a test for this? With https://github.com/moby/moby/issues/40388 merged, I expect it to be easier to call the API, and verify that the excepted settings were loaded 🤔 wdyt?

There are some existing tests in https://github.com/moby/moby/blob/3af8d484b132a492bd6f159e454560b7d7691fa9/daemon/config/config_test.go#L41, so it could either be added to one of the existing test (haven't looked if there's a suitable test for that), or a new test to be added

**Comment by thaJeztah** [comment]
Or otherwise in https://github.com/moby/moby/blob/3af8d484b132a492bd6f159e454560b7d7691fa9/integration/ 🤔

**Comment by wangyumu** [comment]
@thaJeztah good idea, I added a new test: `TestDaemonConfigurationMergeFlagsWitchConfigFile`
```
Test before this fix:
=== RUN   TestDaemonConfigurationMergeFlagsWitchConfigFile
    config_test.go:178: expect result not empty, but got []
--- FAIL: TestDaemonConfigurationMergeFlagsWitchConfigFile (0.00s)

Test after this fix:
=== RUN   TestDaemonConfigurationMergeFlagsWitchConfigFile
--- PASS: TestDaemonConfigurationMergeFlagsWitchConfigFile (0.00s)
PASS
```

File: daemon/config/config_test.go [hunk 1]
```diff
@@ -153,6 +153,32 @@ func TestDaemonConfigurationMergeConflictsWithInnerStructs(t *testing.T) {
 	}
 }
 
+// Test for #40711
+func TestDaemonConfigurationMergeFlagsWitchConfigFile(t *testing.T) {
```
Comment (thaJeztah) [inline daemon/config/config_test.go:157]: Typo 😅 

```suggestion
func TestDaemonConfigurationMergeFlagsWithConfigFile(t *testing.T) {
```

Perhaps rename to include the DefaultAddressPools ?

```suggestion
func TestDaemonConfigurationMergeDefaultAddressPools(t *testing.T) {
```

File: daemon/config/config_test.go [hunk 2]
```diff
@@ -153,6 +153,32 @@ func TestDaemonConfigurationMergeConflictsWithInnerStructs(t *testing.T) {
...
+	var conf = Config{}
+	flags := pflag.NewFlagSet("test", pflag.ContinueOnError)
+	flags.Var(&conf.NetworkConfig.DefaultAddressPools, "default-address-pool", "")
+	flags.Set("default-address-pool", "base=10.123.0.0/16,size=24")
+
+	config, err := MergeDaemonConfigurations(&conf, flags, configFile)
+
+	if err != nil {
+		t.Fatalf("merge error %v", err)
+	}
```
Comment (thaJeztah) [inline daemon/config/config_test.go:176]: Given that we're already importing gotest.tools, this could be;

```suggestion
	assert.NilError(t, err)
```

File: daemon/config/config_test.go [hunk 3]
```diff
@@ -153,6 +153,32 @@ func TestDaemonConfigurationMergeConflictsWithInnerStructs(t *testing.T) {
...
+	if config.DefaultAddressPools.Value() == nil || len(config.DefaultAddressPools.Value()) == 0 {
+		t.Fatalf("expect result not empty, but got %v", config.DefaultAddressPools.Value())
+	}
```
Comment (thaJeztah) [inline daemon/config/config_test.go:179]: Probably good to check that the value is what we expected. Something like;

```suggestion
	expected := []*ipamutils.NetworkToSplit{{Base: "10.123.0.0/16", Size: 24}}
	assert.DeepEqual(t, config.DefaultAddressPools.Value(), expected)
```

Comment (thaJeztah) [reply daemon/config/config_test.go:179]: I had the branch checked out locally, so perhaps easier to copy/paste here what I wrote up quickly with my suggestions;

```go
// Test for #40711
func TestDaemonConfigurationMergeDefaultAddressPools(t *testing.T) {
	emptyConfigFile := fs.NewFile(t, "config", fs.WithContent(`{}`))
	defer emptyConfigFile.Remove()
	configFile := fs.NewFile(t, "config", fs.WithContent(`{"default-address-pools":[{"base": "10.123.0.0/16", "size": 24 }]}`))
	defer configFile.Remove()

	expected := []*ipamutils.NetworkToSplit{{Base: "10.123.0.0/16", Size: 24}}

	t.Run("empty config file", func(t *testing.T) {
		var conf = Config{}
		flags := pflag.NewFlagSet("test", pflag.ContinueOnError)
		flags.Var(&conf.NetworkConfig.DefaultAddressPools, "default-address-pool", "")
		flags.Set("default-address-pool", "base=10.123.0.0/16,size=24")

		config, err := MergeDaemonConfigurations(&conf, flags, emptyConfigFile.Path())
		assert.NilError(t, err)
		assert.DeepEqual(t, config.DefaultAddressPools.Value(), expected)
	})

	t.Run("config file", func(t *testing.T) {
		var conf = Config{}
		flags := pflag.NewFlagSet("test", pflag.ContinueOnError)
		flags.Var(&conf.NetworkConfig.DefaultAddressPools, "default-address-pool", "")

		config, err := MergeDaemonConfigurations(&conf, flags, configFile.Path())
		assert.NilError(t, err)
		assert.DeepEqual(t, config.DefaultAddressPools.Value(), expected)
	})

	t.Run("with conflicting options", func(t *testing.T) {
		var conf = Config{}
		flags := pflag.NewFlagSet("test", pflag.ContinueOnError)
		flags.Var(&conf.NetworkConfig.DefaultAddressPools, "default-address-pool", "")
		flags.Set("default-address-pool", "base=10.123.0.0/16,size=24")

		_, err := MergeDaemonConfigurations(&conf, flags, configFile.Path())
		assert.ErrorContains(t, err, "the following directives are specified both as a flag and in the configuration file")
		assert.ErrorContains(t, err, "default-address-pools")
	})
}
```


Let me know if you think that looks good (and feel free to copy to your PR)

**Review by thaJeztah — CHANGES_REQUESTED** [review]
Thanks! Left some suggestions inline 🤗

File: daemon/config/config_test.go (hunk 3 above)
Comment (wangyumu) [reply daemon/config/config_test.go:179]: It looks wonderful, really appreciate your work, I will copy it. 👍

**Review by thaJeztah — APPROVED** [review]
LGTM if green; thanks so much!

**Review by tonistiigi — APPROVED** [review]

**Review by cpuguy83 — APPROVED** [review]
LGTM
