### PR TITLE
Fix DOCKER_TLS_VERIFY being ignored

### LINKED ISSUE #13964: DOCKER_TLS_VERIFY env var doesn't work in master
setting DOCKER_TLS_VERIFY=1 no longer works in master.  The command line flag works but env var does not.  Will try to track down where it broke, the code in flags.go hasn't changed so I am not yet sure why.
Client version: 1.7.0-dev
Client API version: 1.20
Go version (client): go1.4.2
Git commit (client): 6a7a757
OS/Arch (client): linux/amd64
Server version: 1.7.0-dev
Server API version: 1.20
Go version (server): go1.4.2
Git commit (server): 6a7a757
OS/Arch (server): linux/amd64

Working command line arg:
docker@testhost:~$ docker --tlsverify
Could not read CA certificate /home/docker/.docker/ca.pem: open /home/docker/.docker/ca.pem: no such file or directory

setting the ENV:
docker@testhost:~$ export DOCKER_TLS_VERIFY=1
docker@testhost:~$ env | grep -i DOCKER_TLS
DOCKER_TLS_VERIFY=1

env var does not work docker does not error:
docker@testhost:~$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

doesn't work in windows or linux.

### PR DESCRIPTION
**Pull request by cpuguy83**
DOCEKR_TLS_VERIFY was being ignored because we were just checking if the
`-tlsverify` flag was set, not the actual value, which is defaulted to
the value of `os.Getenv("DOCKER_TLS_VERIFY") != ""`

The problem that this specifically fixes is where the client has set the
`DOCKER_TLS_VERIFY` env var but is connecting to a daemon that is not
verifed.

Closes #13964

### CODE REVIEW

**Comment by cpuguy83** [comment]
Also moved this below the daemon setup because it's weird to have the daemon config from env var, and that's how it was before.

File: docker/docker.go [hunk 1]
```diff
@@ -84,12 +84,6 @@ func main() {
 
 	setDefaultConfFlag(flTrustKey, defaultTrustKeyFile)
 
-	// Regardless of whether the user sets it to true or false, if they
-	// specify --tlsverify at all then we need to turn on tls
-	if flag.IsSet("-tlsverify") {
```
Comment (tiborvass) [inline docker/docker.go]: @cpuguy83 i believe we need to keep this here. The fix could be though: `if flag.IsSet("-tlsverify") || *flTlsVerify {`. Looking in history to understand better what happened.

Comment (cpuguy83) [inline docker/docker.go]: But then if someone sets `--tlsverify=false`, `flag.IsSet` still comes back as true.

Comment (tiborvass) [inline docker/docker.go]: that's a feature, read the comment above :)

Comment (duglin) [inline docker/docker.go]: correct.  The behavior that code is trying to do is: if they specify "--tlsverify=false" then they ant TLS enabled but not tlsverify.  IOW, --tlsverify=false should imply --tls

Comment (cpuguy83) [inline docker/docker.go]: hmm.... I guess that's how it was before, even if odd.

Comment (duglin) [inline docker/docker.go]: If you look at the help for --tls you'll see this:
```
  --tls=false                          Use TLS; implied by --tlsverify
```
which, to me, means --tlsverify will turn on --tls no matter what I set --tlsverify to.

**Comment by cpuguy83** [comment]
Removed milestone since this actually wasn't in 1.7 rc.. sorry about that

**Comment by tiborvass** [comment]
For the record, here's what happened:
https://github.com/docker/docker/pull/13636/files#diff-b715a530d535012e418a564a3eafedb9L116
We used to load the CA by only checking `flTlsVerify`, (not relying on `flTls`). The refactor PR #13636 changed that to check `flTlsVerify` only if `flTls` is true (that's somewhat abstracted by the `tlsconfig` package). The fix is to set `flTls` to true, when either `--tlsverify` was set (even if to false), or if `flTlsVerify` is true. `flTlsVerify` could be true without specifying `--tlsverify` if the envvar `DOCKER_TLS_VERIFY` is set.

@cpuguy83 if you could add a one-line comment that'd be great.

**Comment by cpuguy83** [comment]
Updated with test and fixed check to both check if the flag is set or check the flag's default value.

**Comment by tiborvass** [comment]
@cpuguy83 still not good, you shouldn't move the block down, it has to stay before the daemon codepath.

**Comment by cpuguy83** [comment]
@tiborvass Ok, fixed.

**Comment by tiborvass** [comment]
LGTM

**Comment by duglin** [comment]
LGTM but janky isn't happy

**Comment by cpuguy83** [comment]
janky is once again happy.

**Comment by lalyos** [comment]
I wanted to test it with binary from: https://master.dockerproject.org
but looks like they haven't rebuilt since 4 days. Any cont build is stopped?

**Comment by cpuguy83** [comment]
@lalyos builds are fixed now.
