### PR TITLE
#28755: [experimental] Proper error handling for checkpoint conflict

### LINKED ISSUE #28755: [experimental] docker checkpoint create cryptic error message on duplicate
When creating a checkpoint for a container, and a checkpoint with that
name already exists for the container, a cryptic error message is printed;

```bash
$ docker checkpoint create cr checkpoint2
Error response from daemon: Cannot checkpoint container cr: rpc error: 
code = 6 desc = mkdir /var/lib/docker/containers/c4ba0c844c93a31db50dcda57fc0126fd17ec1c4a73cd550a501aac117685a6c/checkpoints/checkpoint2:
file exists
```

`docker checkpoint create` should;

- check if a checkpoint already exists
- if exists, print a proper error message

Expected behavior;

```bash
$ docker checkpoint create cr checkpoint2
Error response from daemon: checkpoint with name foo already exists for container cr
```

/cc @boucher

### PR DESCRIPTION
**Pull request by dattatrayakumbhar**
"fixes #28755"

**- What I did**
Currently if we created checkpoint which is being used by one container. it does not give proper error.
Provide a proper error if checkpoint is used by container.
Also if we created checkpoint in a custom checkpoint directory then we can't specify checkpoints per container as one container lists all in given custom checkpoint directory.
With this PR, we can now differentiate multiple checkpoint for multiple container in current director.
 
**- How I did it**
1. Wrote a function to check if checkpoint is being used by current container. and give a proper error if new one is already is being used.
2. With custom checkpoint directory, we were not differentiating as per container.
  With this PR, we added <checkpointDir>containerID/checkpoint/checkpointName
  So we could differentiate now.
3. Also remove redundancy and written a function to check directory before create, list, remove.

**- How to verify it**
Create two containers.
docker run -it -d --name=c1 busybox sh
docker run -it -d --name=c2 busybox sh 

1. Create checkpoint without directory
docker checkpoint create c1 check1-wo-c1
                  #should create successfully.
docker checkpoint create c1 check1-wo-c1
                   #Should give error "checkpoint with name check1-wo-c1 already exists for container /c1"
 
2. Create checkpoint with directory 
docker checkpoint create --checkpoint-dir /checkpoint-dir c1 check1-wi-c1
                 #Should get created successfully.
docker checkpoint create --checkpoint-dir /checkpoint-dir c1 check1-wi-c1
                 #checkpoint with name check1-wi-c1 already exists for container /c1

3. Create checkpoint with same as c1 container's checkpoint for c2 in same direcotry.
docker checkpoint create --checkpoint-dir /checkpoint-dir c2 check1-wi-c1
                #Should get create successfully 

4. Create new checkpoint with not a same as c1 container's checkpoint for c2 in same direcotry.
docker checkpoint create --checkpoint-dir /checkpoint-dir c2 check1-wi-c2
                #Should get created successfully. 

5. List down checkpoints with directory.
docker checkpoint ls --checkpoint-dir /checkpoint-dir c1
                 #should list down only checkpoint in given checkpoint directory for c1.
                 CHECKPOINT NAME
                  check1-wi-c1

6. 4. List down checkpoints without directory. 
docker checkpoint ls  c1
                 #Should list checkpoint in default directory only.
                 CHECKPOINT NAME
                check1-wo-c1

7. Delete checkpoint.
docker checkpoint rm --checkpoint-dir /checkpoint-dir c2 check1-wi-c2
                  #Should get deleted successfully.
8. If we listed checkpoint from same directory after deletion, it should show only remained checkpoints.
docker checkpoint ls --checkpoint-dir /checkpoint-dir c2
              CHECKPOINT NAME
               check1-wi-c1

9. #Deletion of deleted/not existing checkpoints should show proper error.
checkpoint rm --checkpoint-dir /checkpoint-dir c2 check1-wi-c2
              #Should give error as "checkpoint check1-wi-c2 is not exist container c2"

image

Signed-off-by: dattatrayakumbhar04 <dattatraya.kumbhar@gslab.com>

### CODE REVIEW

File: daemon/checkpoint.go [hunk 1]
```diff
@@ -14,6 +14,7 @@ import (
 var (
 	validCheckpointNameChars   = utils.RestrictedNameChars
 	validCheckpointNamePattern = utils.RestrictedNamePattern
+	containerDir               = "/var/lib/docker/containers/"
```
Comment (AkihiroSuda) [inline daemon/checkpoint.go]: Please avoid hard-coding and use `daemon.repository` instead

File: daemon/checkpoint.go [hunk 2]
```diff
@@ -38,6 +39,25 @@ func (daemon *Daemon) CheckpointCreate(name string, config types.CheckpointCreat
 		return fmt.Errorf("Invalid checkpoint ID (%s), only %s are allowed", config.CheckpointID, validCheckpointNameChars)
 	}
 
+	var checkpointDirs string
+	containerList := []string{}
+
+	dir, _ := ioutil.ReadDir(containerDir)
```
Comment (AkihiroSuda) [inline daemon/checkpoint.go]: Let's catch all the errors

File: daemon/checkpoint.go [hunk 3]
```diff
@@ -38,6 +39,25 @@ func (daemon *Daemon) CheckpointCreate(name string, config types.CheckpointCreat
...
+		containerList = append(containerList, d.Name())
+	}
+
+	for _, container := range containerList {
+		container, _ := daemon.GetContainer(container)
+		checkpointDirs = container.CheckpointDir()
+		checkpoints, _ := ioutil.ReadDir(checkpointDirs)
+
+		for _, checkpoint := range checkpoints {
+			if checkpoint.IsDir() && (checkpoint.Name() == config.CheckpointID) {
```
Comment (AkihiroSuda) [inline daemon/checkpoint.go]: you don't need parenthesis for the second comparison expression

File: daemon/checkpoint.go [hunk 4]
```diff
@@ -38,6 +39,25 @@ func (daemon *Daemon) CheckpointCreate(name string, config types.CheckpointCreat
...
 
+	var checkpointDirs string
+	containerList := []string{}
+
+	dir, _ := ioutil.ReadDir(containerDir)
+	for _, d := range dir {
+		containerList = append(containerList, d.Name())
+	}
+
+	for _, container := range containerList {
```
Comment (AkihiroSuda) [inline daemon/checkpoint.go]: why do you need this heavy iteration?
since the error is ` mkdir /var/lib/docker/containers/c4ba0c844c93a31db50dcda57fc0126fd17ec1c4a73cd550a501aac117685a6c/checkpoints/checkpoint2:
file exists`, you just consider the existence of `filepath.Join(daemon.repository, container.ID, "checkpoints", config.checkpointID)`

**Review by AkihiroSuda — CHANGES_REQUESTED** [review]
As commented, I think the design needs to be refined.

Also, can you add an integration test that fails without this PR but succeeds with this PR?
(Note that current code does not include any IT for checkpoint yet..)

**Comment by dattatrayakumbhar04** [comment]
@AkihiroSuda ptal.
Updated PR with changes for duplicate checkpoint.
Will be adding integration test cases.

**Comment by milindchawre** [comment]
LGTM

File: daemon/checkpoint.go [hunk 5]
```diff
@@ -38,6 +38,11 @@ func (daemon *Daemon) CheckpointCreate(name string, config types.CheckpointCreat
 		return fmt.Errorf("Invalid checkpoint ID (%s), only %s are allowed", config.CheckpointID, validCheckpointNameChars)
 	}
 
+	checkDir := filepath.Join(daemon.repository, container.ID, "checkpoints", config.CheckpointID)
+	if stat, err := os.Stat(checkDir); err == nil && stat.IsDir() {
+		return fmt.Errorf(" checkpoint with name %s already exists for container %s", config.CheckpointID, container.Name)
+	}
```
Comment (thaJeztah) [inline daemon/checkpoint.go]: This doesn't look correct, because a custom `--checkpoint-dir` can be specified, and this will not catch that.

This should probably be something like this;

```patch
diff --git a/daemon/checkpoint.go b/daemon/checkpoint.go
index 33c6001..87006ea 100644
--- a/daemon/checkpoint.go
+++ b/daemon/checkpoint.go
@@ -38,9 +38,8 @@ func (daemon *Daemon) CheckpointCreate(name string, config types.CheckpointCreat
                return fmt.Errorf("Invalid checkpoint ID (%s), only %s are allowed", config.CheckpointID, validCheckpointNameChars)
        }

-       checkDir := filepath.Join(daemon.repository, container.ID, "checkpoints", config.CheckpointID)
-       if stat, err := os.Stat(checkDir); err == nil && stat.IsDir() {
-               return fmt.Errorf(" checkpoint with name %s already exists for container %s", config.CheckpointID, container.Name)
+       if stat, err := os.Stat(filepath.Join(checkpointDir, config.CheckpointID)); err == nil && stat.IsDir() {
+               return fmt.Errorf("Checkpoint with name %s already exists for container %s", config.CheckpointID, container.Name)
        }

        err = daemon.containerd.CreateCheckpoint(container.ID, config.CheckpointID, checkpointDir, config.Exit)
```

File: daemon/checkpoint.go [hunk 6]
```diff
@@ -38,6 +38,11 @@ func (daemon *Daemon) CheckpointCreate(name string, config types.CheckpointCreat
...
+
 	err = daemon.containerd.CreateCheckpoint(container.ID, config.CheckpointID, checkpointDir, config.Exit)
 	if err != nil {
```
Comment (thaJeztah) [inline daemon/checkpoint.go]: Ideally, we should probably catch the error here, and make a nicer message, however, I'm not sure what the correct way is to get the error-code, and if they are defined;

```
ERRO[0014] Handler for POST /v1.26/containers/test/checkpoints returned error: Cannot checkpoint container test: rpc error: code = 6 desc = mkdir /var/lib/docker/containers/86292a6c7d41387bf1a95a2981e

ERRO[0311] Handler for POST /v1.26/containers/test2/checkpoints returned error: Cannot checkpoint container test2: rpc error: code = 2 desc = exit status 1: "criu failed: type NOTIFY errno 0\nlog file.....
```

**Review by thaJeztah — CHANGES_REQUESTED** [review]

File: daemon/checkpoint.go (hunk 6 above)
Comment (dattatrayakumbhar) [inline daemon/checkpoint.go]: @thaJeztah,
Thanks for the review, I will update the PR accordingly.

I observed that when I created checkpoint with custom directory(--checkpoint-dir ) option,  "docker checkpoint ls" command does not show any output.

When checkpoint is create without custom checkpoint-dir, checkpoint is created under /var/lib/docker/container/<containerID>/checkpoints/
 
How can we find dependancy between checkpoints and containers when multiple checkpoints created for different containers in same directory using --checkpoint-dir ?

Comment (thaJeztah) [inline daemon/checkpoint.go]: @dattatrayakumbhar yes, I think that's something that needs to be improved, or we should remove the functionality of a custom checkpoint-dir (and replace with, e.g., an option so save the checkpoint data to a tar, and to load from that tar).

Checkpoint/restore is still experimental, and UX needs feedback (and improvement)

**Comment by vdemeester** [comment]
ping @dattatrayakumbhar could you take care of @thaJeztah comments ?

**Comment by dattatrayakumbhar** [comment]
yes will start working on it ..

**Comment by dattatrayakumbhar** [comment]
Updated PR with changes.
Added testing instructions in description section.

Following changes are  done as part of this PR:
1. if created checkpoint with same name in default directory, it will show proper error that checkpoint with name is already exists.
2. If we created multiple checkpoints with same name in custom checkpointDir.
   **Before this PR**:  It was creating all checkpoints in given checkpoint directory only. There was no mapping of container and checkpoint, so if created same named checkpoint  as container1 for container2.
  **This PR**:  Added support so that multiple checkpoints with same can be created in one directory as (custom-checkpointDir/containerID/checkpoints/<checkpointName>) for different container.
 If we created same name of checkpoint for container1 with checkpointDir. It gives proper error.
 If we created checkpoint for container2 in same checkpointDir and used same checkpoint name for container1 then it gets created successfully for container2 also.

3.  List down checkpoint in customcheckpointDir.
  **Before this PR**: If we created checkpoint for container1 and container2 in same directory, it was listing down all checkpoints for each container.
 **This PR** :  It lists down right checkpoints for right container with same checkpointDir only.
  if checkpoint1 is for container1 in dir1 and checkpoint2 is for container2 in dir1 only then container1 shows checkpoint1 only.

4. Similarly as #3,  It also deletes right checkpoint for right container.
5. Added error handling if checkpoint is not exist in default as well as custom checkpointDir.

@thaJeztah @vdemeester @AkihiroSuda 
Please review this.  This is simple way and same way as default checkpointDir to store mapping of container asd checkpoint.

File: daemon/checkpoint.go [hunk 7]
```diff
@@ -56,13 +62,20 @@ func (daemon *Daemon) CheckpointDelete(name string, config types.CheckpointDelet
...
-		checkpointDir = config.CheckpointDir
+		checkpointDir = filepath.Join(config.CheckpointDir, container.ID, "checkpoints")
 	} else {
 		checkpointDir = container.CheckpointDir()
 	}
-
-	return os.RemoveAll(filepath.Join(checkpointDir, config.CheckpointID))
+	checkpointAbsDir = filepath.Join(checkpointDir, config.CheckpointID)
+	if stat, err := os.Stat(checkpointAbsDir); err == nil && stat.IsDir() {
+		out = os.RemoveAll(filepath.Join(checkpointDir, config.CheckpointID))
```
Comment (mlaventure) [inline daemon/checkpoint.go]: you already have the abs path in `checkpointAbsDir` might as well use it.

File: daemon/checkpoint.go [hunk 8]
```diff
@@ -56,13 +62,20 @@ func (daemon *Daemon) CheckpointDelete(name string, config types.CheckpointDelet
...
+	} else {
+		out = fmt.Errorf("checkpoint %s does not exist for container %s", config.CheckpointID, name)
```
Comment (mlaventure) [inline daemon/checkpoint.go]: We may just get a permission denied here, in which case we want to print the error.

File: daemon/checkpoint.go [hunk 9]
```diff
@@ -28,16 +28,22 @@ func (daemon *Daemon) CheckpointCreate(name string, config types.CheckpointCreat
 	}
 
 	var checkpointDir string
+	var checkpointAbsDir string
 	if config.CheckpointDir != "" {
```
Comment (mlaventure) [inline daemon/checkpoint.go]: Since this is repeated 3 times, might as well put it into a small routine.

Since there's also always a `os.Stat` following, What about something like this:
```
func getCheckpointDir(dir string, new bool) (base string, abs string, err error)
```

`new` is here to distinguish call from create and the other operations. if `new` is set then the routine should return an error if  `os.Stat` succeeds (whether the target is a directory or not), otherwise it should return an error is the target doesn't exist, is not a directory or any other system error.

**Review by mlaventure — CHANGES_REQUESTED** [review]
Also would you mind changing the string in `fmt.Errorf` to start with a lowercase?

**Comment by dattatrayakumbhar** [comment]
@mlaventure
Could you review this PR,  I have updated it with changes.

File: daemon/checkpoint.go [hunk 10]
```diff
@@ -16,6 +16,33 @@ var (
 	validCheckpointNamePattern = api.RestrictedNamePattern
 )
 
+// getCheckpointDir verifies checkpoint directory for create,remove, list options and checks if checkpoint already exists
+func getCheckpointDir(checkDir, checkpointID string, name string, containerID string, containercheckpointDir string, new bool) (checkpointDir string, err error) {
```
Comment (mlaventure) [inline daemon/checkpoint.go]: This is missing a few checks and can be simplified. what about:
```go
func getCheckpointDir(rootDir, id, containerName, containerID, defaultRootDir string, create bool) (checkpointDir string, err error) {
	if rootDir != "" {
		checkpointDir = filepath.Join(rootDir, containerID, "checkpoints")
	} else {
		checkpointDir = defaultRootDir
	}

	checkpoint := filepath.Join(checkpointDir, id)
	stat, err := os.Stat(checkpoint)
	if create {
		switch {
		case err != nil && os.IsNotExist(err):
			// all is good, we can create a new checkpoint with that id in `checkpointDir`
			err = nil
		case err != nil:
			// just return that error (e.g. permission denied)
		case err == nil && stat.IsDir():
			err = fmt.Errorf("a checkpoint with id %s already exists for container %s", id, containerName)
		case err == nil:
			err = fmt.Errorf("%s exist and is not a directory", checkpoint)
		}

		return
	}

	switch {
	case err != nil:
		// something is wrong
	case err == nil && stat.IsDir():
		// this looks like a valid checkpoint
	case err == nil:
		err = fmt.Errorf("%s exist and is not a directory", checkpoint)
	}

	return
}
```

?

File: daemon/checkpoint.go [hunk 11]
```diff
@@ -27,17 +54,16 @@ func (daemon *Daemon) CheckpointCreate(name string, config types.CheckpointCreat
...
-	}
-
 	if !validCheckpointNamePattern.MatchString(config.CheckpointID) {
 		return fmt.Errorf("Invalid checkpoint ID (%s), only %s are allowed", config.CheckpointID, validCheckpointNameChars)
 	}
 
+	checkpointDir, err := getCheckpointDir(config.CheckpointDir, config.CheckpointID, name, container.ID, container.CheckpointDir(), true)
+
+	if err != nil {
+		return fmt.Errorf("Cannot checkpoint container %s: %s", name, err)
```
Comment (mlaventure) [inline daemon/checkpoint.go]: we usually start errors strings with a lowecase letter.

**Review by mlaventure — CHANGES_REQUESTED** [review]

**Comment by dattatrayakumbhar** [comment]
@mlaventure @thaJeztah 
Could you please review this, I have implemented changes?

**Review by mlaventure — APPROVED** [review]

**Comment by mlaventure** [comment]
@dattatrayakumbhar could you change the commit message to reflect the change instead of the issue being fixed?

Something like "Properly report checkpoint directory conflicts" or similar, maybe @thaJeztah has a better phrasing.

ping @thaJeztah @AkihiroSuda for review

**Comment by mlaventure** [comment]
@dattatrayakumbhar You need a space between your first name and your last name normally :)

**Review by mlaventure — APPROVED** [review]
LGTM

**Comment by dattatrayakumbhar** [comment]
ping @thaJeztah @mlaventure to review this PR if needed to add more detail.

File: daemon/checkpoint.go [hunk 12]
```diff
@@ -16,6 +16,41 @@ var (
 	validCheckpointNamePattern = api.RestrictedNamePattern
 )
 
+// getCheckpointDir verifies checkpoint directory for create,remove, list options and checks if checkpoint already exists
+func getCheckpointDir(checkDir, checkpointID string, name string, containerID string, containercheckpointDir string, create bool) (checkpointDir string, err error) {
```
Comment (thaJeztah) [inline daemon/checkpoint.go]: Looks like the output variables aren't really used; this could be

```go
func getCheckpointDir(checkDir, checkpointID string, name string, containerID string, containercheckpointDir string, create bool) (string, error) { 
	var checkpointDir string
	var errorVar error
```

In addition, I would;

- change `errorVar` to a different name (`Var` doesn't add much value); perhaps simply `err2`
- change the `name` argument to something that explains it's the _container_'s name, not the checkpoint
- `containercheckpointDir` should use camelcase, `containerCheckpointDir`

(perhaps use `ctrName`, `ctrID`, `ctrCheckpointDir`)


I've looked at possibly use not that many arguments, and instead something like;

```go
func getCheckpointDir(ctr *container.Container, checkpoint types.CheckpointOptions, create bool) (string, error) {
```

Which would make it a lot cleaner, but that's a bigger change, so not something for this PR

File: daemon/checkpoint.go [hunk 13]
```diff
@@ -16,6 +16,41 @@ var (
...
+	if create {
+		switch {
+		case err == nil && stat.IsDir():
+			errorVar = fmt.Errorf("checkpoint with name %s already exists for container %s", checkpointID, name)
+		case err != nil && os.IsNotExist(err):
+			errorVar = nil
+		case err != nil:
+			errorVar = err
+		case err == nil:
+			errorVar = fmt.Errorf("%s exist and is not a directory", checkpointAbsDir)
```
Comment (thaJeztah) [inline daemon/checkpoint.go]: s/exist/exists/

**Review by thaJeztah — CHANGES_REQUESTED** [review]
Thanks @dattatrayakumbhar, and sorry for being so late reviewing. I tested this, and it improves things (I found some other issues while testing, but will open separate issues for that)

I left some comments inline 👍

**Comment by dattatrayakumbhar** [comment]
@thaJeztah,
Thanks for reviewing it.
I have addressed the all comments. Could you please review it again ?

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Comment by thaJeztah** [comment]
Looks like @AkihiroSuda's comments were already addressed, so let me go ahead and merge! :tada:
