### PR TITLE
Windows: Consistent build workdir handling

### LINKED ISSUE #21697: Windows paths are not usable with COPY or ADD in Dockerfiles for Windows containers
**Output of `docker version`:**

```
Docker version 1.10.0-dev, build 18c9fe0
```

**Output of `docker info`:**

```
Containers: 40
Images: 17
Server Version: 1.10.0-dev
Storage Driver: windowsfilter
 Windows:
Execution Driver:
 Name: Windows 1854
 Build: 1.10.0-dev 18c9fe0
 Default Isolation: process
Logging Driver: json-file
Plugins:
 Volume: local
 Network:
Kernel Version: 10.0 10586 (10586.162.amd64fre.th2_release_sec.160223-1728)
Operating System: Windows Server 2016 Technical Preview 4
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 3.5 GiB
Name: DockerTester
ID: MQJ2:GFIZ:4Q2P:IKNE:3PZH:4G2L:E5EC:2CRU:LLOG:6D6Y:PRUK:EL5Z
Debug mode (server): true
 File Descriptors: -1
 Goroutines: 27
 System Time: 2016-03-31T18:18:29.3411051Z
 EventsListeners: 0
 Init SHA1:
 Init Path: C:\Windows\System32\docker.exe
 Docker Root Dir: C:\ProgramData\Docker
```

Running on a Windows Server 2016 TP4 with containers instance in Azure.

When using a Dockerfile to set up a Windows container, ADD and COPY don't handle Windows paths properly. In particular,

    ADD my_batch_script.bat C:/Users/Administrator/my_batch_script.bat

prints an exception saying

    GetFileAttributesEx \\?\Volume{2f571493-f5fe-11e5-a4cd-fb1b90c1c752}\C::
    The filename, directory name, or volume label syntax is incorrect.

Whereas

    ADD my_batch_script.bat /Users/Administrator/my_batch_script.bat

does what the first command should have done.

The same issue applies to COPY.

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

Fixes https://github.com/docker/docker/issues/21697

This fixes a bug I noticed yesterday in TestBuildRelativeWorkdir where a Windows daemon is being extremely inconsistent in its handling of WORKDIR in a Dockerfile. This change guarantees that regardless of the use of any supported semantics in a Dockerfile, both the container configuration and what is passed to HCS will be in normalised Windows semantics - `uppercasedriveletter-colon-backslash-foldername`. It also copes correctly with relative paths, and the situation where a previous workdir was set. I added a fairly exhaustive set of tests too :smile:

### CODE REVIEW

**Comment by jhowardmsft** [comment]
Ugh. This has ramifications for COPY and probably ADD too. Marking [WIP] for now.

**Comment by friism** [comment]
Awesome, I'll try to test this. Also summoning @rneugeba to see if he might have opinions.

**Comment by jhowardmsft** [comment]
Don't hold your breath quite yet - the final fix will be quite a bit more involved :cry:

**Comment by jhowardmsft** [comment]
Ready for review, removing [WIP] from title. Fixed the COPY/ADD issues noted above, and added a ton of additional test cases to ensure no regressions.

@friism Should be good for testing on this.

**Comment by icecrime** [comment]
LGTM

File: builder/dockerfile/dispatchers.go [hunk 1]
```diff
@@ -263,13 +263,40 @@ func workdir(b *Builder, args []string, attributes map[string]bool, original str
...
+			workdir = filepath.Join(current, workdir)
+		}
+		workdir = strings.ToUpper(string(workdir[0])) + workdir[1:] // Upper-case drive letter
+	} else {
+		if !filepath.IsAbs(workdir) {
+			workdir = filepath.Join(string(os.PathSeparator), current, workdir)
+		}
 	}
-
+	logrus.Debugln("Setting workdir to ", workdir)
```
Comment (crosbymichael) [inline builder/dockerfile/dispatchers.go]: remove plz

File: builder/dockerfile/dispatchers.go [hunk 2]
```diff
@@ -263,13 +263,40 @@ func workdir(b *Builder, args []string, attributes map[string]bool, original str
 
 	// This is from the Dockerfile and will not necessarily be in platform
 	// specific semantics, hence ensure it is converted.
+	logrus.Debugf("Workdir handling pre-processing: input '%s' current '%s'", args[0], b.runConfig.WorkingDir)
```
Comment (crosbymichael) [inline builder/dockerfile/dispatchers.go]: remove plz

File: container/container.go [hunk 3]
```diff
@@ -250,6 +250,13 @@ func (container *Container) GetResourcePath(path string) (string, error) {
 
 	cleanPath := cleanResourcePath(path)
 	r, e := symlink.FollowSymlinkInScope(filepath.Join(container.BaseFS, cleanPath), container.BaseFS)
+
+	// Log this here on the daemon side as there's otherwise no indication apart
+	// from the error being propagated all the way back to the client. This makes
+	// debugging significantly easier and clearly indicates the error comes from the daemon.
+	if e != nil {
+		logrus.Debugf("Failed to FollowSymlinkInScope BaseFS %s cleanPath %s path %s %s\n", container.BaseFS, cleanPath, path, e)
```
Comment (crosbymichael) [inline container/container.go]: This should be `logrus.Errorf` if you are going to print this in the daemon logs

File: builder/dockerfile/internals.go [hunk 4]
```diff
@@ -213,13 +213,62 @@ func (b *Builder) runContextCommand(args []string, allowRemote bool, allowLocalD
...
+
+				dest = filepath.Join(string(os.PathSeparator), b.runConfig.WorkingDir[2:], dest)
+
+				// Make sure we preserve any trailing slash
+				if endsInSlash {
+					dest += string(os.PathSeparator)
+				}
+			}
+		}
+		logrus.Debugf("dest converted from '%s' to '%s' at workdir '%s'", origDest, dest, b.runConfig.WorkingDir)
```
Comment (crosbymichael) [inline builder/dockerfile/internals.go]: remove this debug also

**Comment by crosbymichael** [comment]
overall looks good.  I think most of the debug lines add too much verbosity to the logs for the information that they provide.  The one where I asked to change to an Errorf is good for pinpointing issues when an error occurs but the others are only useful for debugging during development and verbose under normal operation.

File: builder/dockerfile/dispatchers.go (hunk 1 above)
Comment (jhowardmsft) [inline builder/dockerfile/dispatchers.go]: k

File: builder/dockerfile/dispatchers.go (hunk 2 above)
Comment (jhowardmsft) [inline builder/dockerfile/dispatchers.go]: k

File: container/container.go (hunk 3 above)
Comment (jhowardmsft) [inline container/container.go]: updated

File: builder/dockerfile/internals.go (hunk 4 above)
Comment (jhowardmsft) [inline builder/dockerfile/internals.go]: k

**Comment by jhowardmsft** [comment]
@crosbymichael Updated and force pushed.

**Comment by crosbymichael** [comment]
@jhowardmsft thanks, i'll merge as soon as the tests are done

**Comment by crosbymichael** [comment]
LGTM

**Comment by icecrime** [comment]
Re LGTM, thanks @crosbymichael!

**Comment by icecrime** [comment]
Experimental failure:

```
15:56:41 FAIL: docker_cli_run_unix_test.go:941: DockerSuite.TestRunSeccompDefaultProfile
15:56:41 
15:56:41 docker_cli_run_unix_test.go:983:
15:56:41     c.Assert(err, checker.IsNil)
15:56:41 ... value *errors.errorString = &errors.errorString{s:"expected Operation not permitted, got: /go/src/github.com/docker/docker/bundles/1.12.0-dev/test-integration-cli/../binary-client/docker: Error response from daemon: Untar re-exec error: exit status 1: output: no such file or directory.\nSee '/go/src/github.com/docker/docker/bundles/1.12.0-dev/test-integration-cli/../binary-client/docker run --help'.\n"} ("expected Operation not permitted, got: /go/src/github.com/docker/docker/bundles/1.12.0-dev/test-integration-cli/../binary-client/docker: Error response from daemon: Untar re-exec error: exit status 1: output: no such file or directory.\nSee '/go/src/github.com/docker/docker/bundles/1.12.0-dev/test-integration-cli/../binary-client/docker run --help'.\n")
```

**Comment by jhowardmsft** [comment]
^^ Looks completely unrelated. Passed experimental on previous iteration - all that has changed is logrus.Debugf removals, and one logrus.Debugf to logrus.Errorf

**Comment by crosbymichael** [comment]
yes, unrelated

**Comment by crosbymichael** [comment]
oh gccgo
