### PR TITLE
Set up DNS names for Windows default network

### LINKED ISSUE #47370: Internal DNS does not work under Windows Server 2022 since version 25.0.0
### Description

Internal DNS does not work on windows server 2022. Pinging one container from another container in the default nat network fails in all versions after 25.0.0 but works in 24.0.9.

### Reproduce

Step 1.

Run the following test bat file under versions 25.0.0 or later:  

```
docker kill container1
docker kill container2
docker rm -v container1
docker rm -v container2

docker run -dit --name container1 --network nat mcr.microsoft.com/dotnet/framework/runtime:4.8 cmd

docker run -it --name container2 --network nat mcr.microsoft.com/dotnet/framework/runtime:4.8 cmd
```

You will be at the cmd prompt of container2.

Step 2.
At the command prompt of container2 run the following command:

```
Microsoft Windows [Version 10.0.20348.2227]
(c) Microsoft Corporation. All rights reserved.

C:\>ping container1
Ping request could not find host container1. Please check the name and try again.

C:\>exit

c:\tmp>docker -v
Docker version 25.0.0, build e758fe5
```  

### Expected behavior

Expected behavior at the command prompt of container2 in any version before version 25.0.0:

```
Microsoft Windows [Version 10.0.20348.2227]
(c) Microsoft Corporation. All rights reserved.

C:\>ping container1

Pinging container1 [172.28.57.12] with 32 bytes of data:
Reply from 172.28.57.12: bytes=32 time<1ms TTL=128
Reply from 172.28.57.12: bytes=32 time<1ms TTL=128
Reply from 172.28.57.12: bytes=32 time<1ms TTL=128
Reply from 172.28.57.12: bytes=32 time<1ms TTL=128

Ping statistics for 172.28.57.12:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms

C:\>exit

c:\tmp>docker -v
Docker version 24.0.9, build 2936816

c:\tmp\2.13.0>
```

### docker version

```bash
Client:
 Version:           25.0.0
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        e758fe5
 Built:             Thu Jan 18 17:10:49 2024
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.0
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       615dfdf
  Built:            Thu Jan 18 17:09:34 2024
  OS/Arch:          windows/amd64
  Experimental:     false
```

### docker info

```bash
Client:
 Version:    25.0.0
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc.)
    Version:  v0.9.1-beta3
    Path:     C:\Program Files\Docker\cli-plugins\docker-app.exe
  cluster: Manage Mirantis Container Cloud clusters (Mirantis Inc.)
    Version:  v1.9.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-cluster.exe
  registry: Manage Docker registries (Docker Inc.)
    Version:  0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-registry.exe

Server:
 Containers: 3
  Running: 1
  Paused: 0
  Stopped: 2
 Images: 132
 Server Version: 25.0.0
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 20348 (20348.1.amd64fre.fe_release.210507-1500)
 Operating System: Microsoft Windows Server Version 21H2 (OS Build 20348.2227)
 OSType: windows
 Architecture: x86_64
 CPUs: 2
 Total Memory: 9.999GiB
 Name: WIN-78M43QMJ96T
 ID: e38ac0ca-1d61-4aa0-b4d5-c151c3093f0d
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Username: senetas
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

### Additional Info

This has not been tested on Windows Server 2019

### PR DESCRIPTION
**Pull request by robmry**
**- What I did**

Fixes https://github.com/moby/moby/issues/47370

**- How I did it**

DNS names were only set up for user-defined networks. On Linux, none of the built-in networks (bridge/host/none) have built-in DNS, so they don't need DNS names.

But, on Windows, the default network is "nat" and it does need the DNS names.

_This is meant as a minimal change that we can ship in a patch if we make one ... but we probably need a better predicate to determine whether a container's going to get an internal resolver, here and elsewhere._

**- How to verify it**

As described in https://github.com/moby/moby/issues/47370.

Also, without the fix, in `inspect` output ...

```
"DNSNames": null
```

And, with the fix ...

```
"DNSNames": [
    "container1",
    "ac0225674b22"
]
```

_Will also need a regression test._

**- Description for the changelog**

Restore DNS names for containers in the default "nat" network on Windows.

### CODE REVIEW

**Review by corhere — APPROVED** [review]
I hate it, but you're right; it's the best we can do with the (horribly named and underspecified) predicates we have at our disposal.

**Review by vvoland — APPROVED** [review]

File: daemon/container_operations.go [hunk 1]
```diff
@@ -649,7 +649,10 @@ func cleanOperationalData(es *network.EndpointSettings) {
 }
 
 func (daemon *Daemon) updateNetworkConfig(container *container.Container, n *libnetwork.Network, endpointConfig *networktypes.EndpointSettings, updateSettings bool) error {
-	if containertypes.NetworkMode(n.Name()).IsUserDefined() {
+	// Set up DNS names for a user defined network, and for the default 'nat'
+	// network on Windows (IsBridge() returns true for nat).
+	if containertypes.NetworkMode(n.Name()).IsUserDefined() ||
+		(serviceDiscoveryOnDefaultNetwork() && containertypes.NetworkMode(n.Name()).IsBridge()) {
```
Comment (thaJeztah) [inline daemon/container_operations.go:655]: Could we ever hit the `default` network here (so not "nat")? https://github.com/moby/moby/blob/a60546b084eef87910345876e32c3db46e7c3bbc/api/types/container/hostconfig.go#L140-L143

Wondering if we should include a link to the github discussion here for future reference 🤔

Comment (robmry) [reply daemon/container_operations.go:655]: I tried to get "default" as far as this, but couldn't - so, decided not to add it. I couldn't see any problem with adding it just-in-case but, because I couldn't test it, I left it out and made a change targeted as specifically as possible at the issue being fixed. (Maybe libnetwork has a surprise to spring with "default", it usually does!)

For the github link ... I think the comment probably covers it, and git-blame is there if needed. But, could do?

As noted in the description, we need a follow-up change to clean this up properly - probably by adding a better predicate and looking at where else it should be used (and what the consequences would be). For example, I think the test in [setupPathsAndSandboxOptions](https://github.com/moby/moby/blob/97478c99f8dfe5f59d80932efb17bb699f4d7030/daemon/container_operations_unix.go#L427-L469) for whether to use systemd's resolv.conf also uses `IsUserDefined` as a proxy for "has internal resolver", so it suffers a similar problem... swarm-scoped networks, which do have an internal resolver, end up using systemd's underlying nameservers instead of `127.0.0.53`... I think they miss the `IsUserDefined()` case by having the name `default` when it matters. I think that's probably an oversight but, as-ever, changing it might break things.

Comment (thaJeztah) [reply daemon/container_operations.go:655]: Yeah, maybe the `default` is not an issue (but I'm definitely not a fan of that magic value 😂 https://github.com/moby/moby/issues/19421)

Adding a link is not a real show-stopper for me; was mostly considering if we wanted to have a crumble-path to find back the discussion around this (basically; this is really a bit of a stop-gap, pending a more solid definition of all of this).

**Review by thaJeztah — APPROVED** [review]
LGTM


let's go with what we have now, but indeed let's create a tracking ticket for further discussion. This was clearly under-defined (and inconsistent between Windows and Linux)

**Comment by robmry** [comment]
Issue to track improvement of the predicates used here and elsewhere ... https://github.com/moby/moby/issues/47378
