### PR TITLE
Fix linux mount calls not applying propagation type changes

### LINKED ISSUE #30415: Propagation types to mount.Mount calls aren't processed correctly
If a mount is requested which includes a propagation type then the propagation type is not applied to the mount.

The following code should mount ```/foo``` under ```/bar``` using a ```bind``` mount and which is read only and private.
```golang
import "github.com/docker/docker/pkg/mount"

if err := mount.Mount("/foo", "/bar", "bind,ro,private"); err != nil {
   return err
}
```

Instead the mount is created with the default propagation mode, in our case shared.

### PR DESCRIPTION
**Pull request by stevenh**
Propagation type changes must be done as a separate call, in the same way as read only bind mounts.

To fix this:
1. Ensure propagation type change flags aren't included in other calls.
2. Only apply read only bind mount changes once.
3. Make it clear which parameters are ignored by passing them as empty.
4. Apply propagation type change in a separate call.

Fixes #30415

Signed-off-by: Steven Hartland <steven.hartland@multiplay.co.uk>

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @cpuguy83 @justincormack PTAL

**Comment by stevenh** [comment]
Not sure the jenkins errors are related to this PR?
```Error processing tar file(exit status 1): no such device```

**Comment by justincormack** [comment]
Can we add some tests for these, as clearly there were not sufficient ones before or it would have been noticed...

**Comment by stevenh** [comment]
@justincormack tests added

**Comment by justincormack** [comment]
@stevenh the tests seem to be failing...

**Comment by stevenh** [comment]
I think there may be something kernel / OS specific about slave mount reporting as this latest version works fine here on ubuntu 16 LTS here, need to investigate more.

**Comment by stevenh** [comment]
The underlying issue was false assumptions about the parent mounts propagation type in the test, locally its was shared on jenkins they must be private, so the resulting Optionals where unstable.

I've restructured the test to start with a source that has known flags, so hopefully it should be good now.

**Comment by stevenh** [comment]
@justincormack this good for you now?

**Comment by LK4D4** [comment]
ping @justincormack

**Comment by justincormack** [comment]
It looked good, will review again just to check.


On 1 Feb 2017 9:18 p.m., "Alexander Morozov" <notifications@github.com>
wrote:

ping @justincormack <https://github.com/justincormack>

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/docker/docker/pull/30416#issuecomment-276785103>, or mute
the thread

**Comment by LK4D4** [comment]
ping @justincormack

File: pkg/mount/mounter_linux.go [hunk 1]
```diff
@@ -4,15 +4,48 @@ import (
...
+		return true
+	default:
+		return false
+	}
+}
+
+func mount(device, target, mType string, flags uintptr, data string) error {
+	oflags := flags &^ ptypes
+	if !isremount(device, flags) {
+		// Initial call applying all none propagation flags.
```
Comment (justincormack) [inline pkg/mount/mounter_linux.go]: typo, none->non

Comment (stevenh) [inline pkg/mount/mounter_linux.go]: fixed

File: pkg/mount/mounter_linux.go [hunk 2]
```diff
@@ -4,15 +4,48 @@ import (
...
+	pflags = ptypes | syscall.MS_REC | syscall.MS_SILENT
+
+	// broflags is the combination of bind and read only
+	broflags = syscall.MS_BIND | syscall.MS_RDONLY
+)
+
+// isremount returns true if either device name or flags identify a remount request, false otherwise.
+func isremount(device string, flags uintptr) bool {
+	switch {
+	case flags&syscall.MS_REMOUNT != 0, device == "", device == "none":
```
Comment (justincormack) [inline pkg/mount/mounter_linux.go]: ok, unsure here. Why is device=="" or device="none" a remount? I can mount a tmpfs with these options. Why is presense of `MS_REMOUNT` not sufficient?

Comment (stevenh) [inline pkg/mount/mounter_linux.go]: The problem with only looking at MS_REMOUNT is that typical use cases don't do this.

An example of this can be seen in sharedsubtree_linux:
```
Mount(mountPoint, mountPoint, "none", "bind,rw")
```

These are covered in the test case so removing the "" and "none" case you'll see the following failures:
```
--- FAIL: TestMount (0.22s)
    --- FAIL: TestMount/none-bind,slave (0.00s)
        mounter_linux_test.go:82: no such device
    --- FAIL: TestMount/none-bind,rw,slave (0.00s)
        mounter_linux_test.go:82: no such device
    --- FAIL: TestMount/none-bind,ro,slave (0.00s)
        mounter_linux_test.go:82: no such device
--- FAIL: TestSubtreePrivate (0.02s)
        sharedsubtree_linux_test.go:66: no such device
--- FAIL: TestSubtreeShared (0.00s)
        sharedsubtree_linux_test.go:143: no such device
--- FAIL: TestSubtreeSharedSlave (0.00s)
        sharedsubtree_linux_test.go:222: no such device
--- FAIL: TestSubtreeUnbindable (0.00s)
        sharedsubtree_linux_test.go:303: no such device

Comment (justincormack) [inline pkg/mount/mounter_linux.go]: Ah yes. Could we add a note in the code explaining that as it is non obvious, especially as the `pkg/` code is intended for use outside Docker and external users might be confused...

Comment (stevenh) [inline pkg/mount/mounter_linux.go]: Comment added.

**Review by justincormack — APPROVED** [review]

**Comment by justincormack** [comment]
Windows failure unrelated and passed before comments changed.

**Review by LK4D4 — APPROVED** [review]
LGTM
