### PR TITLE
Fix flakey TestStatsAllNewContainersAdded

### LINKED ISSUE #18672: Flaky test: TestStatsAllNewContainersAdded
From #18661 on janky

```
----------------------------------------------------------------------
FAIL: docker_cli_stats_test.go:94: DockerSuite.TestStatsAllNewContainersAdded

docker_cli_stats_test.go:125:
    c.Fatal("failed to observe new container created added to stats")
... Error: failed to observe new container created added to stats


----------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by cpuguy83**
Fixes #18672 maybe?

### CODE REVIEW

File: integration-cli/docker_cli_stats_test.go [hunk 1]
```diff
@@ -118,16 +118,17 @@ func (s *DockerSuite) TestStatsAllNewContainersAdded(c *check.C) {
...
 	}()
 
-	out, _ := dockerCmd(c, "run", "-d", "busybox", "top")
+	out, _ := runSleepingContainer(c, "-d")
 	c.Assert(waitRun(strings.TrimSpace(out)), check.IsNil)
 	id <- strings.TrimSpace(out)[:12]
 
 	select {
-	case <-time.After(10 * time.Second):
+	case <-time.After(30 * time.Second):
```
Comment (cpuguy83) [inline integration-cli/docker_cli_stats_test.go]: well, this was @ 5 seconds on my branch... 10 seems like it should be ok, but...

**Comment by aaronlehmann** [comment]
Don't know for sure that increasing the timeout will fix the problem, but it seems like the most likely explanation for the failure. LGTM.

**Comment by icecrime** [comment]
LGTM
