### PR TITLE
Remove output file when save/export fail

### LINKED ISSUE #17809: docker export creates empty files on failure
Should the `docker export` command create empty files when the container is not exported successfully ? The error message returned is valid, however zero byte file should not be created on-disk.

```
$ docker ps -a
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS                     PORTS               NAMES
c15dc668f4ab        hello-world:latest   "bash"                   2 minutes ago       Created                                        evil_blackwell
7769a41cfbc0        registry:2           "/bin/registry /etc/d"   10 days ago         Exited (2) 4 minutes ago                       registry

$ docker export -o hello.tar hello-world:latest 
Error response from daemon: no such id: hello-world:latest

$ ls -l hello.tar 
-rw-rw-r-- 1 abelur abelur 0 Nov  8 17:58 hello.tar    

$ docker info
Containers: 2
Images: 195
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 199
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-65-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 7.689 GiB
Name: srv-182
ID: Q7CC:FNYP:4OWW:Q4FW:HHVL:KORD:AS6L:6AGN:6I3D:LRZG:NBWO:ZDXC
Debug mode (server): true
File Descriptors: 12
Goroutines: 19
System Time: 2015-11-08T18:01:37.009613104+05:30
EventsListeners: 0
Init SHA1: 70b0cda2ecbf0d9fb1879ed198a66ad09a3dc50c
Init Path: /usr/lib/docker/dockerinit
Docker Root Dir: /var/lib/docker
Username: askb
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

$ docker version 
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:37:18 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:37:18 UTC 2015
 OS/Arch:      linux/amd64

 uname -a
Linux 3.13.0-65-generic #106-Ubuntu SMP Fri Oct 2 22:08:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

```

### PR DESCRIPTION
**Pull request by daehyeok**
Remove output file when save/export return error

Fixed #17809

### CODE REVIEW

**Comment by tonistiigi** [comment]
Maybe we can make a temp file and rename if everything was successful. At the moment this would remove the old file it was on disk, but really we shouldn't have any effect on disk layout on error.

**Comment by daehyeok** [comment]
@tonistiigi  changed source to using temple

**Comment by tonistiigi** [comment]
@daehyeok Tests are failing, probably because renames happen across devices. Try a hidden tempfile in the target files directory.

**Comment by daehyeok** [comment]
@tonistiigi oops sorry.. I changed again.

File: api/client/export.go [hunk 1]
```diff
@@ -39,8 +44,19 @@ func (cli *DockerCli) CmdExport(args ...string) error {
...
+			if err := os.Remove(tempPath); err != nil {
+				return err
+			}
+		}
 		return err
 	}
 
+	if *outfile != "" {
+		if err := os.Rename(tempPath, *outfile); err != nil {
+			return err
```
Comment (tonistiigi) [inline api/client/export.go]: remove `tempPath` here also?

**Comment by daehyeok** [comment]
Modified again.. missed too many things... :(

File: api/client/export.go [hunk 2]
```diff
@@ -21,14 +23,17 @@ func (cli *DockerCli) CmdExport(args ...string) error {
...
-		err    error
+		output   = cli.out
+		err      error
+		tempPath string
 	)
+
 	if *outfile != "" {
-		output, err = os.Create(*outfile)
-		if err != nil {
+		var f *os.File
```
Comment (cpuguy83) [inline api/client/export.go]: can remove this far statement and instead do
```go
f, err := ioutil.TempFile(...)
if err != nil {
    ....
}
output, tempPath = f, f.Name()
```

same in `save.go`

**Comment by daehyeok** [comment]
@cpuguy83 Applied

**Comment by cpuguy83** [comment]
Windows failure looks legit:
```
FAIL: docker_cli_export_import_test.go:31: DockerSuite.TestExportContainerWithOutputAndImportImage

docker_cli_export_import_test.go:36:
    dockerCmd(c, "export", "--output=testexp.tar", containerID)
C:/Jenkins/gopath/src/github.com/docker/docker/pkg/integration/dockerCmd_utils.go:35:
    c.Assert(err, check.IsNil, check.Commentf("%q failed with errors: %s, %v", strings.Join(args, " "), out, err))
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc08269a2a0)} ("exit status 1")
... "export --output=testexp.tar testexportcontainerwithoutputandimportimage" failed with errors: rename .docker_export_006698283 testexp.tar: The process cannot access the file because it is being used by another process.
, exit status 1
```

**Comment by askb** [comment]
Maybe you could add tests to check file creation on `export/save` failure condition. Something like the below might work:

```
// test export cmd on failure should not create an empty file
func (s *DockerSuite) TestExportContainerOutputFile(c *check.C) {
        testRequires(c, DaemonIsLinux)
        containerID := "nonexistingcontainer"

        dockerCmd(c, "export", "--output=nonexistingcontainer.tar", containerID)

        if fi, err := os.Stat("nonexistingcontainer.tar"); err == nil && fi.Size() == 0 {
	c.Fatalf("Zero byte file getting created when container does not exist: %v", err)
       }
}
```

**Comment by daehyeok** [comment]
Unfortunately, I don't have Windows machines... and i have no idea why it's can't not move file Windows test machine. May be i open file using `os.TempFile` and don't close??
 I changed code to use temporary directory. I hope to it will work well..

**Comment by tonistiigi** [comment]
@daehyeok Yes, close the file before renaming. Should be fine after that.

**Comment by thaJeztah** [comment]
@daehyeok have you been able to work on those suggestions?

**Comment by daehyeok** [comment]
@thaJeztah sorry, I was busy recently. I'll check tomorrow.

**Comment by thaJeztah** [comment]
@daehyeok no problem, just checking :+1:

**Comment by thaJeztah** [comment]
ping @daehyeok :innocent:

**Comment by daehyeok** [comment]
@thaJeztah Really sorry. My school semester will end this week. until then i can't afford to contribute...

**Comment by daehyeok** [comment]
Sorry for holding this issue too long time.
in that time export/save implementation little changed. so i just delayed creating file until call copy function.

**Comment by thaJeztah** [comment]
ping @tonistiigi @cpuguy83 can you review the new implementation?

thanks @daehyeok!

**Comment by cpuguy83** [comment]
LGTM

**Comment by tonistiigi** [comment]
I liked the previous implementation better as you can have an error on `io.Copy` as well. But I guess if it complicates code too much we can ignore that case atm.

**Comment by daehyeok** [comment]
@tonistiigi sorry i didn't get your point. in this implementation if error occur in the io.Copy, return that error

**Comment by tonistiigi** [comment]
@daehyeok so we remove the file, not like in the previous implementation where everything used temporary file and the file on disk was not touched if error occured.

**Comment by daehyeok** [comment]
@tonistiigi I still think it can be ignored. but if we considering that, code will be like below link.(i did not test yet)
Which is better?

https://gist.github.com/daehyeok/73a294d6958759f740ab

**Comment by tonistiigi** [comment]
I like the one in the gist more. @cpuguy83 WDYT?

**Comment by cpuguy83** [comment]
The reason I don't like the temp file approach is the file may be huge and the temp dir may be on a separate device (or in a tmpfs).

**Comment by tonistiigi** [comment]
@cpuguy83 The temp file seems to be in the same directory as the result file.

**Comment by cpuguy83** [comment]
Ah yeah, that works for me.

**Comment by cpuguy83** [comment]
vet: api/client/export.go: api/client/export.go:42:20: expected ';', found '{' (and 1 more errors)

**Comment by daehyeok** [comment]
@cpuguy83 repushed

File: api/client/export.go [hunk 3]
```diff
@@ -40,6 +38,33 @@ func (cli *DockerCli) CmdExport(args ...string) error {
...
+		output = tmpFile
+	}
 	_, err = io.Copy(output, responseBody)
-	return err
+
+	if err != nil {
+		if *outfile != "" {
+			tmpPath := tmpFile.Name()
+			tmpFile.Close()
+			os.Remove(tmpPath)
```
Comment (jfrazelle) [inline api/client/export.go]: these could probably be a defer no?

Comment (daehyeok) [inline api/client/export.go]: @jfrazelle maybe in this way? is call File.Close() two times ok?
https://gist.github.com/daehyeok/77319f3ca7025ac3a2cb

**Comment by thaJeztah** [comment]
ping @calavera can you rebase to fix the tests?

**Comment by daehyeok** [comment]
follwed @jfrazelle comments, using defer to delete temp file. it have a posiibilty that call close 2 times. but i think it will not problem.. and add  call remove right before rename.(i'm not sure rename will overwrite file in the every platform)

**Comment by thaJeztah** [comment]
ping @jfrazelle @tonistiigi @cpuguy83 ptal

**Comment by calavera** [comment]
can we remove the duplicated code? it looks like this can be simplified by extracting the code into a couple of functions.

**Comment by daehyeok** [comment]
@calavera  Simplified write new function in the api/client/utils.go like below, and just call `return saveResponeBody(responseBody, outfile)`  in the both of save.go and export.go. is it enough?

```
func saveResponeBody(responseBody io.ReadCloser, outfile string) error {
	var (
		output  = cli.out
		tmpFile *os.File
	)

	if *outfile != "" {
		tmpFile, err = ioutil.TempFile(filepath.Dir(*outfile), ".docker_temp_")
		if err != nil {
			return err
		}
		output = tmpFile
		tmpPath := tmpFile.Name()

		defer func() {
			tmpFile.Close()
			if _, err := os.Stat(tmpPath); err == nil {
				os.Remove(tmpPath)
			}
		}()
	}
	_, err = io.Copy(output, responseBody)

	if err != nil {
		return err
	}

	if *outfile != "" {
		if err = os.Remove(*outfile); err != nil && !os.IsNotExist(err) {
			return err
		}

		tmpPath := tmpFile.Name()
		tmpFile.Close()
		if err = os.Rename(tmpPath, *outfile); err != nil {
			return err
		}
	}

	return nil
}
```

File: api/client/export.go [hunk 4]
```diff
@@ -40,6 +38,39 @@ func (cli *DockerCli) CmdExport(args ...string) error {
...
+	}
 	_, err = io.Copy(output, responseBody)
-	return err
+
+	if err != nil {
+		return err
+	}
+
+	if *outfile != "" {
+		if err = os.Remove(*outfile); err != nil && !os.IsNotExist(err) {
```
Comment (tonistiigi) [inline api/client/export.go]: Can you remind me why you need to remove the old file first?

Comment (daehyeok) [inline api/client/export.go]: https://golang.org/pkg/os/#Rename
"OS-specific restrictions might apply."
I'm not sure  os.Rename always overwrite existed file in the every system.(I can't check Windows system).

Comment (tonistiigi) [inline api/client/export.go]: Go sets the `MOVEFILE_REPLACE_EXISTING` flag for windows https://github.com/golang/go/blob/release-branch.go1.5/src/internal/syscall/windows/syscall_windows.go#L129

Comment (daehyeok) [inline api/client/export.go]: @tonistiigi Oh Thanks. i will remove `Remove` function. how about write new function in the utils.go?

**Comment by calavera** [comment]
Thanks. LGTM

**Comment by icecrime** [comment]
@tonistiigi Can you finish reviewing? Thanks!

File: api/client/utils.go [hunk 5]
```diff
@@ -138,3 +141,28 @@ func (cli *DockerCli) getTtySize() (int, int) {
 	}
 	return int(ws.Height), int(ws.Width)
 }
+
+func saveResponeBody(responseBody *io.ReadCloser, outfile *string) error {
```
Comment (tonistiigi) [inline api/client/utils.go]: Could you make this func:

```
func copyToFile(outfile string, rc io.ReadCloser) error
```

So that there are no unneeded pointers and the parameters order is the same as for `io.Copy` (as they are being used next to each other).

**Comment by daehyeok** [comment]
@tonistiigi  applied

**Comment by tonistiigi** [comment]
LGTM

**Comment by thaJeztah** [comment]
Moving to "merge"; Janky's are still running

**Comment by stephenlauck** [comment]
This is still not fixed. When saving an image where the given image tag is not found docker still writes out a zero size file with the name.

**Comment by tianon** [comment]
@stephenlauck are you sure?

```console
$ docker --version
Docker version 20.10.6, build 370c289
$ docker save -o foo.tar foo:bar
Error response from daemon: reference does not exist
$ ls -l foo.tar
ls: cannot access 'foo.tar': No such file or directory
```

**Comment by tianon** [comment]
(If you can come up with a reliable reproducer on the latest release, it would be helpful to file a new issue with more details.)

**Comment by stephenlauck** [comment]
@tianon You're right, the file is being created when you do `$ docker save busybox > busybox.tar` but this is because of the `>`. Updated to the `-o` syntax and things are all good now.
