### PR TITLE
Fix shallow git clone in docker-build

### LINKED ISSUE #33701: Docker build doesn't shallow clone from github
**Description**

`docker build github.com/moby/moby.git` should only clone with depth 1. However, it's fetching the entire repository. This is because we only `git clone --depth 1` if we think the server is "smart", by checking with a HEAD request for `/info/refs?service=git-upload-pack` ([code here](https://github.com/calavera/docker/blob/1cfb307d70558110e8e88a7391ae0e6cf6ebf174/utils/git.go#L36)). However, github doesn't actually support HEAD requests ([Git documentation](https://github.com/git/git/blob/master/Documentation/technical/http-protocol.txt) never mentions HEAD requests).

**Steps to reproduce the issue:**
`docker build github.com/moby/moby.git`

**Describe the results you received:**
The entire git repository is being fetched. You can easily compare the timings against `git clone github.com/moby/moby.git` and `git clone github.com/moby/moby.git --depth 1`, and it's pretty clear. I'm sure there are other ways to verify this is happening.

Manually running `curl --head http://github.com/moby/moby.git/info/refs?service=git-upload-pack` confirms that github just denies the request.

**Describe the results you expected:**
Should be fast and only clone the latest tree.

**Additional information you deem important (e.g. issue happens only occasionally):**
Code created in #12502

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.8.1
 Git commit:   89658bed64
 Built:        Fri May  5 22:40:58 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.8.1
 Git commit:   89658bed64
 Built:        Fri May  5 22:40:58 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 5
 Running: 1
 Paused: 0
 Stopped: 4
Images: 223
Server Version: 17.05.0-ce
Storage Driver: devicemapper
 Pool Name: docker-254:3-2491281-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 6.738GB
 Data Space Total: 107.4GB
 Data Space Available: 88.06GB
 Metadata Space Used: 21.06MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.126GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.140 (2017-05-03)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.11.4-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.704GiB
Name: pandacow
ID: YPJM:6M3G:BOXR:FTIE:X74P:E7DY:FKOB:BUKK:SUNI:QWHR:NUG3:B2YC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by ecnerwala**
**- What I did**
Properly test if git servers are smart HTTP for cloning.
Fixes #33701, introduced by #12502

**- How I did it**
Change the Head request to a Get.

Requires update on https://github.com/docker/cli.

### CODE REVIEW

**Comment by ecnerwala** [comment]
Some more context (pasted from #33701)

`docker build github.com/moby/moby.git` should only clone with depth 1. However, it's fetching the entire repository. This is because we only `git clone --depth 1` if we think the server is "smart", by checking with a HEAD request for `/info/refs?service=git-upload-pack` ([code here](https://github.com/calavera/docker/blob/1cfb307d70558110e8e88a7391ae0e6cf6ebf174/utils/git.go#L36)). However, github doesn't actually support HEAD requests ([Git documentation](https://github.com/git/git/blob/master/Documentation/technical/http-protocol.txt) never mentions HEAD requests).

See also: https://github.com/moby/moby/pull/12502#issuecomment-94091784, which is the reason that we need to check for smart-vs-dumb http to begin with.

**Comment by ecnerwala** [comment]
@thaJeztah @ijc, this somewhat makes URL magic with `git@` better by offering an alternative.

File: builder/remotecontext/git/gitutils.go [hunk 1]
```diff
@@ -70,7 +70,7 @@ func fetchArgs(remoteURL *url.URL, ref string) []string {
 	shallow := true
 
 	if strings.HasPrefix(remoteURL.Scheme, "http") {
-		res, err := http.Head(fmt.Sprintf("%s/info/refs?service=git-upload-pack", remoteURL))
+		res, err := http.Get(fmt.Sprintf("%s/info/refs?service=git-upload-pack", remoteURL))
```
Comment (tonistiigi) [inline builder/remotecontext/git/gitutils.go]: Should call `res.Body.Close()` on successful request.

The `GET` request to get all remote refs is usually quite slow but it shouldn't matter here much as we are not consuming the body. I wouldn't mind actually having a whitelist with github here to avoid this request for that host.

Comment (thaJeztah) [inline builder/remotecontext/git/gitutils.go]: I think a common approach is to perform a `HEAD` request, then fallback to `GET` if not supported by the server, not sure if that works for this, but would avoid special-casing GitHub

Comment (ecnerwala) [inline builder/remotecontext/git/gitutils.go]: The `HEAD` and fallback sounds reasonable, but it doesn't solve the special case with GitHub, as GitHub doesn't support `HEAD`. In the interest of performance, we may just want to do no requests at all with GitHub.

Comment (ijc) [inline builder/remotecontext/git/gitutils.go]: I think we should avoid special casing any particular provider whenever we can so that a) all providers can benefit from improvements (be they performance, robustness, protocol compatibility) and b) we avoid building in reliance on the behaviour's of particular services as they happen to be configured today and miss out on future improvements etc.

Comment (ecnerwala) [inline builder/remotecontext/git/gitutils.go]: Alright, added the initial `HEAD` request.

**Comment by thaJeztah** [comment]
Sorry for the back and forth; discussing with @tonistiigi - we were wondering if there's still servers around that _don't_ support this option, and  what kind of error would be returned by such a server.

Perhaps we can do a "happy path" and just _assume_ it's not supported, and _if_ it fails, fall back to non-shallow clone?

Would you be interested in investigating that, and see if that would be a viable option?

**Comment by thaJeztah** [comment]
@ijc perhaps you know something about that?

**Comment by ijc** [comment]
"that" is the prevalence of smart http servers which can support shallow cloning?

I'm afraid that other than knowing that the smart server has been around for ages I don't really know how widespread it is.

**Comment by thaJeztah** [comment]
Basically considering to "just do a shallow clone" and assuming it is supported; if (e.g.) 99% of the servers out there support this, then the extra handling is resulting in extra overhead for 99% of the cases, and only used for 1%. 

I spent some time to look into what makes a "dumb" server, and how git/docker works with that. Apparently, git _should_ fallback to the "dumb" protocol, but I guess this doesn't work if `--depth 1` is set;

https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols

> If the server does not respond with a Git HTTP smart service, the Git client will try to fall back to the simpler “dumb” HTTP protocol. The Dumb protocol expects the bare Git repository to be served like normal files from the web server.


This is how to test a "dumb" server;

Build a dumb server image;

```bash
$ docker build -t dumb-git -<<EOF
FROM nginx:alpine

WORKDIR /usr/share/nginx/html/
RUN apk add --no-cache git
RUN git clone --bare https://github.com/thaJeztah/pgadmin4-docker.git \
 && cd pgadmin4-docker.git \
 && git update-server-info
EOF
```

Start the server

```bash
$ docker run -d --name gitty -p 80:80 dumb-git
```

Try to clone from this server;


With `--depth 1`

```bash
$ git clone http://localhost/pgadmin4-docker.git --depth 1

Cloning into 'pgadmin4-docker'...
fatal: dumb http transport does not support shallow capabilities
```

Without (dumb)

```bash
$ git clone http://localhost/pgadmin4-docker.git
Cloning into 'pgadmin4-docker'...
```

Next, I built a Docker CLI, but with the feature detection disabled (i.e., _always_ `--depth 1`);


```bash
$ docker build -t foo http://192.168.65.2/pgadmin4-docker.git
unable to prepare context: unable to 'git clone' to temporary context directory: error fetching: fatal: dumb http transport does not support shallow capabilities
: exit status 128
```

So, possibly we can detect the `fatal: dumb http transport does not support shallow capabilities` error, and in that case fallback?

**Comment by ijc** [comment]
Unfortunately setting up a dumb server is super trivial (expose a directory via http(s) and try to remember to run `git update-server-info` in it, even if you forget that many things still just work) compared with setting up a smart one (which involves cgi), so even though the smart one has been around for ages I would expect there will still be relatively significant numbers of dumb ones, especially internal/private (e.g. company) ones which we have no visibility onto. IOW I'm afraid I doubt it is as many as 99% of servers.

Perhaps the smart one supports some sort of `?query=foo` type syntax which the dumb one certainly doesn't and which could be used as a probe?

**Comment by thaJeztah** [comment]
Well, I was thinking if the request itself could be used; it looks to fail directly if it's not supported, so if we catch the error, and fallback to cloning _without_ `--depth=1`. Or would that be really bad?

**Comment by ijc** [comment]
My concern was that if the clone failed for some other reason we don't just assume it was due to the shallow clone, perhaps matching on `fatal: dumb http transport does not support shallow capabilities` but that might be fragile due to differences in different git versions or due to l18n?

**Comment by ecnerwala** [comment]
@ijc I think the `GET $GIT_URL/info/refs?service=git-upload-pack HTTP/1.0` is the standard probe to differentiate between smart and dumb servers (https://www.kernel.org/pub/software/scm/git/docs/technical/http-protocol.html).

**Comment by ijc** [comment]
@ecnerwala I agree. I think the code is correct but could do with some additional comments explaining why it is looking at the things it is looking at, in particular the aspect that `$GIT_URL/info/refs?service=git-upload-pack` is specified for both dumb and smart servers but with distinct `Content-Type`s specified.

For `GET` vs `HEAD` I note that the [spec](https://tools.ietf.org/html/rfc7231#section-4.3.2) says WRT `HEAD:
```
   The HEAD method is identical to GET except that the server MUST NOT
   send a message body in the response (i.e., the response terminates at
   the end of the header section).  The server SHOULD send the same
   header fields in response to a HEAD request as it would have sent if
   the request had been a GET, except that the payload header fields
   (Section 3.3) MAY be omitted. 
```
So the GH implementation (which rejects `HEAD` with `405 Method Not Allowed`) is, I suppose, compliant since it only violates a `SHOULD`, although it does go rather against the spirit of things.

I think the patch could be improved by believing the checking content type on a `2xx` response to the `HEAD` request and only falling back to a `GET` check if the `HEAD` gets a non-`2xx` response. i.e. if the `HEAD` results in a `200 OK` with `Content-Type != application/x-git-upload-pack-advertisement` then there is no need to fallback to a `GET` in that case, we know it is a dumb server. I don't think that's an absolute requirement though, it just avoids a redundant check for a dumb server which _does_ respond to the `HEAD` based probe.

**Comment by ecnerwala** [comment]
Alright, I made the change to check for a `200 OK` response.

File: builder/remotecontext/git/gitutils.go [hunk 2]
```diff
@@ -98,22 +98,45 @@ func getRefAndSubdir(fragment string) (ref string, subdir string) {
...
 	return append(args, "origin", ref)
 }
 
+func supportsShallowCheckout(remoteURL string) bool {
+	// Check if the URL is an HTTP url
+	if urlutil.IsURL(remoteURL) {
+		// Only smart-HTTP git servers support shallow clone
+
+		// URL to test for the service
+		serviceURL := fmt.Sprintf("%s/info/refs?service=git-upload-pack", remoteURL)
```
Comment (ijc) [inline builder/remotecontext/git/gitutils.go]: Nit: this can just be `remoteURL + "/info/refs?service=git-upload-pack"` rather than needing `fmt.Sprintf`.

**Comment by ijc** [comment]
You should probably use `http.StatusOK` rather than the hard coded `200` but otherwise LGTM (I left one minor nit as a comment).

I don't know enough about these things to say if you should also accept other (or all) `2xx` results, I think we can leave it as you have it unless some expert says otherwise.

File: builder/remotecontext/git/gitutils.go (hunk 2 above)
Comment (thaJeztah) [inline builder/remotecontext/git/gitutils.go]: :+1: if not needed, it's best to avoid Sprintf

**Comment by ecnerwala** [comment]
I originally wrote it to accept all `2xx` results, but the git spec actually specifies that the client should validate that the response is `200 OK` or `304 Not Modified` (for cached entries), so I went with this instead. If anyone knows better, please let me know!

File: builder/remotecontext/git/gitutils.go [hunk 3]
```diff
@@ -98,22 +97,45 @@ func getRefAndSubdir(fragment string) (ref string, subdir string) {
...
+	if urlutil.IsURL(remoteURL) {
+		// Only smart-HTTP git servers support shallow clone
+
+		// URL to test for the service
+		serviceURL := remoteURL + "/info/refs?service=git-upload-pack"
+		// Desired content type returned by smart servers
+		contentTypeResponse := "application/x-git-upload-pack-advertisement"
+
+		// First try a HEAD request
+		res, err := http.Head(serviceURL)
```
Comment (thaJeztah) [inline builder/remotecontext/git/gitutils.go]: I think you tried to reduce complexity here by keeping the `HEAD` and `GET` parts separate, however doing so probably made it harder to grasp;

- the `contentTypeResponse` variable is defined a lot further from where it's used
- explaining things like "if x succeeds", "check content type" should not be needed; the code can be self-explanatory

If you combine the paths, a single explanation of what we're doing can be sufficient;

```go
// try HEAD, fallback to GET if not supported
res, err := http.Head(serviceURL)
if err != nil {
	res, err = http.Get(serviceURL)
	if err != nil {
		return false
	}
	res.Body.Close()
}
```

After that, you'd just have to check the response code (should be self-explanatory), and the content-type (may need a comment), something like;

```go
if res.StatusCode != http.StatusOK {
	return false
}
if res.Header.Get("Content-Type") != "application/x-git-upload-pack-advertisement" {
	// not a smart server
	return false
}
return true
```

I dropped the `contentTypeResponse` variable, in favour of a comment explaining we detected it's not a "smart" server. The function description itself already explained that that means "shallow clone" is not supported

Although this would've worked for the return;

```go
return res.Header.Get("Content-Type") == "application/x-git-upload-pack-advertisement"
```

(mainly "taste"); I think it's less easy to grasp here, and having all returns `false` (early fail) makes it slightly more consistent

**Review by thaJeztah — COMMENTED** [review]
left some suggestions, but let me know what you think

File: builder/remotecontext/git/gitutils.go [hunk 4]
```diff
@@ -98,22 +97,45 @@ func getRefAndSubdir(fragment string) (ref string, subdir string) {
...
+	if supportsShallowCheckout(remoteURL) {
 		args = append(args, "--depth", "1")
 	}
 
 	return append(args, "origin", ref)
 }
 
+func supportsShallowCheckout(remoteURL string) bool {
+	// Check if the URL is an HTTP url
+	if urlutil.IsURL(remoteURL) {
```
Comment (ecnerwala) [inline builder/remotecontext/git/gitutils.go]: I left it in this form because I'm afraid we might eventually have special logic for other transport types. I think this really should look like a `switch protocol` statement with a default, but that doesn't quite work here.

File: builder/remotecontext/git/gitutils.go (hunk 3 above)
Comment (ecnerwala) [inline builder/remotecontext/git/gitutils.go]: Yup, definitely looks a bit cleaner. Thanks!

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Comment by yongtang** [comment]
ping @tonistiigi

**Review by tonistiigi — APPROVED** [review]
LGTM

**Comment by yongtang** [comment]
Thanks all for the review. The PR could be merged now as all Jenkins tests have passed as well.
