### PR TITLE
Fix handling for json-file io.UnexpectedEOF

### LINKED ISSUE #41820: Upgrade to 20.10 breaks log tailing: unexpected EOF errors
**Description**

Our E2E test suite uses [testcontainers-java](https://github.com/testcontainers/testcontainers-java) to run our microservices and their dependencies in containers for the duration of our tests. All of the tests were passing with 19.03.14 until we updated our build nodes to Docker 20.10.1, at which point we started repeatedly getting `STDOUT: $Error grabbing logs: unexpected EOF errors`, and our Wait.forLogMessage calls started timing out.

Note however, that this issue seems sporadic as about 1 out of 10 builds still passes. After we reverted to Docker 19.03.14 the issue went away. We're using the latest version of Testcontainers (1.15.1 at the time of reporting the issue).

After contacting the developers [I was told this is most likely a Docker issue](https://github.com/testcontainers/testcontainers-java/issues/3613).

**Steps to reproduce the issue:**
Unfortunately our projects are not OSS, so I cannot give you the exact containers used. I'll try to describe a matching scenario.

1. Set up a project that uses the latest version of testcontainers-java (`1.15.1`).
2. Set up a docker image that produces a lot of standard output.
3. Start the image using testcontainers-java and wait for a log message using `Wait.forLogMessage()`.
4. A huge percentage of the times this will result in the error message `STDOUT: $Error grabbing logs: unexpected EOF errors` and the wait policy will not trigger even though the messages are present in the log.

**Describe the results you received:**
Error message: `STDOUT: $Error grabbing logs: unexpected EOF errors`, wait policy for log message not triggering even though the message was present in the log.

**Describe the results you expected:**
No EOF error, wait policy for log message working.

**Additional information you deem important (e.g. issue happens only occasionally):**
As mentioned in the description the issue seems sporadic, but it happens in about 80+% of our CI runs.

**Output of `docker version`:**
Previous version where the tests were passing: 

```
Client: Docker Engine - Community
 Version:           19.03.14
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        5eb3275d40
 Built:             Tue Dec  1 19:20:26 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.14
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       5eb3275d40
  Built:            Tue Dec  1 19:18:53 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.9
  GitCommit:        ea765aba0d05254012b0b9e595e995c09186427f
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

Current version where the issue is present:
```
Client:
 Version:           20.10.1
 API version:       1.41
 Go version:        go1.15.6
 Git commit:        831ebeae96
 Built:             Tue Dec 15 22:25:01 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.15.6
  Git commit:       f0014860c1
  Built:            Tue Dec 15 22:24:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b.m
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

Previous version where the tests were passing:
```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 92
 Server Version: 19.03.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ea765aba0d05254012b0b9e595e995c09186427f
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-58-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 3
 Total Memory: 15.64GiB
 Name: build1
 ID: QWYR:EE5C:DWTE:MY65:MQ7Y:FERG:F7J2:IDTT:7LVR:VHSE:REFY:6AQH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

Current version where the issue is present:
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-tp-docker)

Server:
 Containers: 134
  Running: 8
  Paused: 0
  Stopped: 126
 Images: 1390
 Server Version: 20.10.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b.m
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.9.14-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.24GiB
 Name: RE02WL03
 ID: YC3H:JCWA:APFN:VOQ7:CWPG:B4VO:5FYW:UPVL:2H5B:PO4H:SXO7:LSGH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio weight support
WARNING: No blkio weight_device support
```

The current version and info parts were copied from an Arch box, while the previous version and info parts were copied from an Ubuntu box, but we could also reproduce the issue on Ubuntu after upgrading to 20.10.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

- Could reproduce using both Ubuntu 20.10 and Arch Linux.

### PR DESCRIPTION
**Pull request by cpuguy83**
Before this, we essentially end up doubling any buffered data from the
json decoder by storing it in both `d.dec` and `d.rdr`.

Thanks @tobiasstadler for pointing this error out.

Fixes #41820

### CODE REVIEW

**Comment by thaJeztah** [comment]
s/io.UnepxectedEOF/io.UnexpectedEOF/ ☺️

**Comment by thaJeztah** [comment]
@tonistiigi @tiborvass ptal

**Comment by thaJeztah** [comment]
@cpuguy83 regression was introduced in https://github.com/moby/moby/pull/40796, correct?

**Comment by cpuguy83** [comment]
@thaJeztah That's correct.
Test is passes before that commit (but requires some modifications due to refactoring in said PR), and fails on that PR and master.

File: daemon/logger/jsonfilelog/read.go [hunk 1]
```diff
@@ -105,8 +110,7 @@ func (d *decoder) Decode() (msg *logger.Message, err error) {
 		// If the json logger writes a partial json log entry to the disk
 		// while at the same time the decoder tries to decode it, the race condition happens.
 		if err == io.ErrUnexpectedEOF {
-			d.rdr = io.MultiReader(d.dec.Buffered(), d.rdr)
-			d.dec = json.NewDecoder(d.rdr)
+			d.dec = json.NewDecoder(io.MultiReader(d.dec.Buffered(), d.rdr))
```
Comment (tonistiigi) [inline daemon/logger/jsonfilelog/read.go:113]: iiuc the issue in here is not the resetting `d.rdr` or not (what looks more correct to me in the old version) but that we use incompatible `Reader` where after it returns `io.EOF` we can read again and it may return more data then. This does not follow the `io.Reader` interface that stdlib defines and therefore the utility functions behavior gets wrong. More specifically `io.MultiReader` caches `io.EOF` https://github.com/golang/go/blob/414fa8c35e7c2f65e2c767d6db2f25791e53b5c1/src/io/multi.go#L41 . So in the previous code if the `MultiReader` has already returned `EOF` once and now is added as a second reader to a new `MultiReader` it never gets called again and new `MultiReader` returns `EOF` without making any new `Read` calls to the original `d.rdr`.

Comment (cpuguy83) [reply daemon/logger/jsonfilelog/read.go]: Added a 2nd commit per your suggestion to replace io.MultiReader with a custom implementation that does not cache EOF's so that we can keep the full reader (with the buffered data) in `d.rdr`.

**Review by tonistiigi — APPROVED** [review]
LGTM

`SyntaxError` handler seems to require `combinedReader` as well but that can be done separately as not directly related. Although I wonder if it might be broken because it could not have been made to work before because of the multireader issue.

**Comment by cpuguy83** [comment]
Yeah there's no test for syntax reader and I think it never actually fixed anything.

File: daemon/logger/jsonfilelog/read.go [hunk 2]
```diff
@@ -105,14 +110,54 @@ func (d *decoder) Decode() (msg *logger.Message, err error) {
...
-			d.rdr = io.MultiReader(d.dec.Buffered(), d.rdr)
+			d.rdr = comineReaders(d.dec.Buffered(), d.rdr)
 			d.dec = json.NewDecoder(d.rdr)
 			continue
 		}
 	}
 	return msg, err
 }
 
+func comineReaders(pre, rdr io.Reader) io.Reader {
```
Comment (thaJeztah) [inline daemon/logger/jsonfilelog/read.go:121]:
```suggestion
func combineReaders(pre, rdr io.Reader) io.Reader {
```

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
CI was green, and only typo was fixed in last push

**Comment by cpuguy83** [comment]
> === FAIL: amd64.integration.service TestInspect (11.75s)
[2021-03-18T19:09:12.879Z]     inspect_test.go:39: timeout hit after 10s: waiting for tasks to enter run state. task failed with error: task: non-zero exit (1)


This flaky inspect test :(

**Comment by anodyne-canvas** [comment]
When will this be included in a release?

**Comment by thaJeztah** [comment]
It's backported to the 20.10 release branch through https://github.com/moby/moby/pull/42174, and will be included in the 20.10.6 patch release

**Comment by anodyne-canvas** [comment]
Thanks for following up, do you know when 20.10.6 will be released?

**Comment by aleon1220** [comment]
It seems to be fixed in docker engine 20.10.6 https://docs.docker.com/engine/release-notes/#20106

**Comment by BenasPaulikas** [comment]
almost 2am here. updating docker with this patch. Praying for this fix to solve my issues :)

**Comment by thaJeztah** [comment]
@BenasPaulikas docker 20.10.6 and 20.10.7 have already shipped with this patch, so updating to the latest patch release should bring this patch.

**Comment by oren-nonamesecurity** [comment]
Same here, docker 20.10.10 flooding:
```
![image](https://user-images.githubusercontent.com/62993794/198866772-55eef0d0-a134-408a-8dd8-4a95c5a44f7f.png)

```

**Comment by oren-nonamesecurity** [comment]
Same here, docker 20.10.10
Screenshot from 2022-10-30 09-10-58

**Comment by BenasPaulikas** [comment]
I might be wrong here.

But there was package that was using json to get docker output or something. They changed to use streams (or something simmilar) and issue was gone. + It saved so much CPU power

**Comment by thaJeztah** [comment]
> I'm still seeing this issue on 20.10.17, and so are many people on [#41820 (comment)](https://github.com/moby/moby/issues/41820#issuecomment-1142518992)
> Any chance this could be reviewed/reopened?

This PR was to address an issue where docker tried to read the JSON, got an EOF, and reused the reader (which would continue to return an EOF error). Note that the EOF error can be an actual issue with a corrupt file, in which case the `EOF` error would be legit.

**Comment by xtemp3r** [comment]
> I'm still seeing this issue on 20.10.17, and so are many people on [#41820 (comment)](https://github.com/moby/moby/issues/41820#issuecomment-1142518992)

I can confirm I have this problem again on multiple systems running docker. I would also suggest that this issue is reopened.

I'm also running version: 20.10.17

**Comment by fredsig** [comment]
Same issue here with docker 20.10.18. Getting a couple of warnings every second (but it is not affecting my ability to process container logs) This triggered by using Loki's promtail agent to collect docker logs using the API (aka, "docker logs') via the service discovery plugin for docker:

```
Apr  2 16:23:52 ip-192-168-151-3 dockerd[323961]: time="2024-04-02T16:23:52.260711951Z" level=warning msg="got error while decoding json" error="unexpected EOF" retries=0
Apr  2 16:23:52 ip-192-168-151-3 dockerd[323961]: time="2024-04-02T16:23:52.587555447Z" level=warning msg="got error while decoding json" error="unexpected EOF" retries=0
Apr  2 16:23:52 ip-192-168-151-3 dockerd[323961]: time="2024-04-02T16:23:52.648610496Z" level=warning msg="got error while decoding json" error="unexpected EOF" retries=0
```
