### PR TITLE
Remove panic in nat package on invalid hostport

### LINKED ISSUE #14621: daemon crashing on invalid ports directive
Hi folks,

Consider the following docker-compose.yml

    test:
        image: spacediver/python
        ports:
          - "127.0.0.180:80"

Notice the error in ports, originally I meant  to say "127.0.0.1:80:80"

Trying to start it we may see (with docker 1.7.0, docker-compose 1.3.0) this:

    root@17934123d4d1:~# docker-compose up                 
    Creating root_test_1...
    Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?
    
Why would this happen? 

Running docker with -D reveals (http://pastebin.com/caDWGW8Q) that there's an exception in daemon that happens at parsing invalid ports directive ("127.0.0.180:80")

Trying to run the same with docker CLI would validate ports directive well before sending to daemon:

    root@17934123d4d1:~# docker run --rm -ti -p 127.0.0.180:80 spacediver/python 
    docker: Invalid hostPort: 127.0.0.180.
    See 'docker run --help'.

Should the daemon check input data and do not crash on parsing error?

Here is my environment information: http://pastebin.com/3LaAh4YT

### PR DESCRIPTION
**Pull request by duglin**
Closes #14621

This one grew to be much more than I expected so here's the story... :-)
- when a bad port string (e.g. xxx80) is passed into container.create()
  via the API it wasn't being checked until we tried to start the container.
- While starting the container we trid to parse 'xxx80' in nat.Int()
  and would panic on the strconv.ParseUint().  We should (almost) never panic.
- In trying to remove the panic I decided to make it so that we, instead,
  checked the string during the NewPort() constructor.  This means that
  I had to change all casts from 'string' to 'Port' to use NewPort() instead.
  Which is a good thing anyway, people shouldn't assume they know the
  internal format of types like that, in general.
- This meant I had to go and add error checks on all calls to NewPort().
  To avoid changing the testcases too much I create newPortNoError() **JUST**
  for the testcase uses where we know the port string is ok.
- After all of that I then went back and added a check during container.create()
  to check the port string so we'll report the error as soon as we get the
  data.
- If, somehow, the bad string does get into the metadata we will generate
  an error during container.start() but I can't test for that because
  the container.create() catches it now.  But I did add a testcase for that.

Signed-off-by: Doug Davis dug@us.ibm.com

### CODE REVIEW

**Comment by runcom** [comment]
LGTM

File: pkg/nat/nat.go [hunk 1]
```diff
@@ -29,8 +29,25 @@ type PortSet map[Port]struct{}
...
+	}
+
+	return Port(fmt.Sprintf("%d/%s", portInt, proto)), nil
+}
+
+// NewPortNoError is the same as NewPort but ignores any parsing error.
+// This should ONLY be used by testcases where we know we don't have any
+// parsing issues.  Just because its annoying to have to check (or ignore)
+// the error each time when we know its correct.
+func NewPortNoError(proto, port string) Port {
```
Comment (cpuguy83) [inline pkg/nat/nat.go]: I don't think we need this, and is a bit dangerous to to add functions just to support a test case.
Tests can just do `p, _` just as this function is, or add a test helper called `newPort` that does this.

Comment (duglin) [inline pkg/nat/nat.go]: I like the idea of adding a test util func - will do that.

**Comment by duglin** [comment]
Updated per @cpuguy83 's suggestion

**Comment by duglin** [comment]
ping @cpuguy83 @LK4D4

**Comment by calavera** [comment]
LGTM
