### PR TITLE
Fix DockerTrustSuite SetUpTest

### LINKED ISSUE #19393: Flaky test: DockerTrustSuite.SetUpTest (more apparent on ARM?)
```
02:46:42 
02:46:42 ----------------------------------------------------------------------
02:46:42 FAIL: check_test.go:130: DockerTrustSuite.SetUpTest
02:46:42 
02:46:42 check_test.go:132:
02:46:42     s.not = setupNotary(c)
02:46:42 github.com/docker/docker/integration-cli/_test/_obj_test/trust_server.go:136:
02:46:42     ...open github.com/docker/docker/integration-cli/_test/_obj_test/trust_server.go: no such file or directory
02:46:42 ... Error: Timeout waiting for test notary to become available: Get https://localhost:4443/v2/: dial tcp [::1]:4443: getsockopt: connection refused
02:46:42 
02:46:42 
02:46:42 ----------------------------------------------------------------------
02:46:42 PANIC: docker_cli_build_test.go:5831: DockerTrustSuite.TestBuildContextDirIsSymlink
02:46:42 
02:46:42 ... Panic: Fixture has panicked (see related PANIC)
02:46:42 
02:46:42 ----------------------------------------------------------------------
```

Also, as reported by @StefanScherer https://github.com/docker/docker/pull/19379#issuecomment-172206565

> I have seen the error in DockerTrustSuite.SetUpTest in our ARM builds. Reproduceable there, but hadn't the time for a closer look.
> I guess this loop in [integration-cli/trust_server.go](https://github.com/docker/docker/blob/1db0c7bb01863f859a193246a0474f9d1b4d6027/integration-cli/trust_server.go#L113) waiting 10 .. 50 ms is very optimistic for the notary-server to become available for the tests.

### PR DESCRIPTION
**Pull request by thaJeztah**
This hopefully makes DockerTrustSuite.SetUpTest less flaky.

Increased the number of attempts to check if Notary is available before giving up.

fixes https://github.com/docker/docker/issues/19393 (fingers crossed)

### CODE REVIEW

File: integration-cli/trust_server.go [hunk 1]
```diff
@@ -106,7 +106,7 @@ func newTestNotary(c *check.C) (*testNotary, error) {
 	}
 
 	// Wait for notary to be ready to serve requests.
-	for i := 1; i <= 5; i++ {
+	for i := 1; i <= 20; i++ {
```
Comment (thaJeztah) [inline integration-cli/trust_server.go]: I thought more attempts was better than a longer "sleep", so that we don't make the tests take longer if it *does* come up fast enough

**Comment by thaJeztah** [comment]
Janky, why are you failing.. `java.lang.IllegalStateException`

**Comment by tiborvass** [comment]
LGTM

File: integration-cli/trust_server.go (hunk 1 above)
Comment (aaronlehmann) [inline integration-cli/trust_server.go]: I agree. But even after 20 attempts, that is still a 200 ms timeout. I'd suggest raising it even further. It is very possible for I/O or resource starvation to make launching a service take more than 200 ms.

**Comment by thaJeztah** [comment]
Lol, and gccgo is failing on another flaky test :cry: https://github.com/docker/docker/issues/19368

File: integration-cli/trust_server.go (hunk 1 above)
Comment (MHBauer) [inline integration-cli/trust_server.go]: it's `10 * 20 * 20 = 4000 milliseconds = 4 seconds`

**Comment by MHBauer** [comment]
LGTM. Worth a shot.

**Comment by thaJeztah** [comment]
It's green, so lets merge!

File: integration-cli/trust_server.go (hunk 1 above)
Comment (thaJeztah) [inline integration-cli/trust_server.go]: @aaronlehmann let's give this a try; we can raise it further if it's still flaky. If it is, we may want to temporarily add some logging to see how long it actually takes, sgty?

**Comment by StefanScherer** [comment]
@thaJeztah I'll let Jenkins test this with the DockerTrustSuite enabled on ARM.

**Comment by thaJeztah** [comment]
@StefanScherer thanks! As mentioned, we can still tweak this, my primary concern was to get the test at least a bit more reliable :-)

**Comment by StefanScherer** [comment]
@thaJeztah Sure! 

But look, DockerTrustSuite works on ARM:

```
09:15:39 PASS: docker_cli_build_test.go:5831: DockerTrustSuite.TestBuildContextDirIsSymlink	3.846s
09:15:45 SKIP: docker_cli_create_test.go:332: DockerTrustSuite.TestCreateWhenCertExpired (Currently changes system time, causing instability)
09:15:51 SKIP: docker_cli_pull_trusted_test.go:65: DockerTrustSuite.TestPullWhenCertExpired (Currently changes system time, causing instability)
09:15:57 SKIP: docker_cli_run_test.go:3200: DockerTrustSuite.TestRunWhenCertExpired (Currently changes system time, causing instability)
09:16:12 PASS: docker_cli_build_test.go:5779: DockerTrustSuite.TestTrustedBuild	9.048s
09:16:18 PASS: docker_cli_build_test.go:5810: DockerTrustSuite.TestTrustedBuildUntrustedTag	0.717s
09:16:32 PASS: docker_cli_create_test.go:282: DockerTrustSuite.TestTrustedCreate	7.526s
09:16:52 PASS: docker_cli_create_test.go:359: DockerTrustSuite.TestTrustedCreateFromBadTrustServer	13.584s
09:17:05 PASS: docker_cli_create_test.go:319: DockerTrustSuite.TestTrustedIsolatedCreate	6.406s
09:17:16 PASS: docker_cli_pull_trusted_test.go:35: DockerTrustSuite.TestTrustedIsolatedPull	5.467s
09:17:29 PASS: docker_cli_pull_trusted_test.go:177: DockerTrustSuite.TestTrustedOfflinePull	6.398s
09:17:40 PASS: docker_cli_pull_trusted_test.go:14: DockerTrustSuite.TestTrustedPull	5.648s
09:17:55 PASS: docker_cli_pull_trusted_test.go:205: DockerTrustSuite.TestTrustedPullDelete	9.150s
09:18:14 PASS: docker_cli_pull_trusted_test.go:93: DockerTrustSuite.TestTrustedPullFromBadTrustServer	12.909s
09:18:20 SKIP: docker_cli_pull_trusted_test.go:147: DockerTrustSuite.TestTrustedPullWithExpiredSnapshot (Currently changes system time, causing instability)
09:18:31 PASS: docker_cli_push_test.go:203: DockerTrustSuite.TestTrustedPush	4.832s
09:18:40 PASS: docker_cli_push_test.go:243: DockerTrustSuite.TestTrustedPushWithDeprecatedEnvPasswords	3.494s
09:18:51 PASS: docker_cli_push_test.go:222: DockerTrustSuite.TestTrustedPushWithEnvPasswords	4.913s
09:19:04 PASS: docker_cli_push_test.go:299: DockerTrustSuite.TestTrustedPushWithExistingSignedTag	7.386s
09:19:16 PASS: docker_cli_push_test.go:279: DockerTrustSuite.TestTrustedPushWithExistingTag	5.417s
09:19:22 SKIP: docker_cli_push_test.go:371: DockerTrustSuite.TestTrustedPushWithExpiredSnapshot (Currently changes system time, causing instability)
09:19:28 SKIP: docker_cli_push_test.go:397: DockerTrustSuite.TestTrustedPushWithExpiredTimestamp (Currently changes system time, causing instability)
09:20:11 PASS: docker_cli_push_test.go:255: DockerTrustSuite.TestTrustedPushWithFailingServer	37.082s
09:20:22 PASS: docker_cli_push_test.go:351: DockerTrustSuite.TestTrustedPushWithIncorrectDeprecatedPassphraseForNonRoot	5.328s
09:20:33 PASS: docker_cli_push_test.go:329: DockerTrustSuite.TestTrustedPushWithIncorrectPassphraseForNonRoot	5.369s
09:20:47 PASS: docker_cli_push_test.go:423: DockerTrustSuite.TestTrustedPushWithReleasesDelegation	7.828s
09:20:55 PASS: docker_cli_push_test.go:267: DockerTrustSuite.TestTrustedPushWithoutServerAndUntrusted	1.849s
09:21:11 PASS: docker_cli_run_test.go:3146: DockerTrustSuite.TestTrustedRun	10.244s
09:21:33 PASS: docker_cli_run_test.go:3238: DockerTrustSuite.TestTrustedRunFromBadTrustServer	15.162s
09:21:42 PASS: docker_cli_create_test.go:303: DockerTrustSuite.TestUntrustedCreate	3.202s
09:21:51 PASS: docker_cli_pull_trusted_test.go:49: DockerTrustSuite.TestUntrustedPull	3.195s
09:22:00 PASS: docker_cli_run_test.go:3178: DockerTrustSuite.TestUntrustedRun	3.337s
```

I'll send a PR for that :smile:

File: integration-cli/trust_server.go (hunk 1 above)
Comment (aaronlehmann) [inline integration-cli/trust_server.go]: 4 seconds should be sufficient.
