### PR TITLE
Fix 'docker stats' help message

### LINKED ISSUE #10771: Docker stats --help usage does not indicate you can monitor multiple containers
Currently the `docker stats --help` output looks like this:

```
Usage: docker stats [OPTIONS] CONTAINER

Display a live stream of one or more containers' resource usage statistics

  --help=false       Print usage
```

When I look at this, it appears the command only supports monitoring a single container.
It should really be documented as:

```
Usage: docker stats [OPTIONS] CONTAINER [CONTAINER...]
```

### PR DESCRIPTION
**Pull request by duglin**
It was missing the fact that you can pass in more than one container

Closes #10771

Signed-off-by: Doug Davis dug@us.ibm.com

### CODE REVIEW

File: api/client/commands.go [hunk 1]
```diff
@@ -2735,7 +2735,7 @@ func (cli *DockerCli) CmdStats(args ...string) error {
 	if len(errs) > 0 {
 		return fmt.Errorf("%s", strings.Join(errs, ", "))
 	}
-	for _ = range time.Tick(500 * time.Millisecond) {
+	for range time.Tick(500 * time.Millisecond) {
```
Comment (cpuguy83) [inline api/client/commands.go]: Don't we need to keep the `for _ = range time.Tick` syntax here for Go 1.3 support?

Comment (duglin) [inline api/client/commands.go]: hmm, I didn't do that on purpose, I think my gofmt did it.
I'll swap it back

**Comment by cpuguy83** [comment]
Putting docs review on this... I think that's right.

**Comment by tiborvass** [comment]
LGTM

**Comment by SvenDowideit** [comment]
LGTM - @fredlf @jamtur01

**Comment by jamtur01** [comment]
LGTM
