### PR TITLE
Clear conntrack entries for published UDP ports

### LINKED ISSUE #2423: container not able receive UDP traffic when disabled userland-proxy
Before container is started, docker daemon check available of published port by binding to published port. For sip port 5060 this looks as
```sh
[root@aeyears ~]# netstat -anp | grep 5060
udp6       0      0 :::5060                 :::*                                102113/dockerd
```
If bind successful, then configured `iptables` rules for container.
Issue rise when inbound UDP packet populate conntrack table when `dockerd` daemon bound to host port, but iptables rules for container is not populated.

In this case conntrarck tables contains row like
```
udp      17 17 src=208.68.17.52 dst=192.168.4.16 sport=5060 dport=5060 [UNREPLIED] src=192.168.4.16 dst=208.68.17.52 sport=5060 dport=5060 mark=0 secctx=system_u:object_r:unlabeled_t:s0 use=1
```
Here you can find substring
```
dst=192.168.4.16 sport=5060 dport=5060 [UNREPLIED] src=192.168.4.16
```
Where `dst` address is address is packet L3 destination address when packet is received.
And `src` address of process/daemon bind that receive packet stream.

As you can see here packets received to IP 192.168.4.16 via UDP transport to port 5060 and processed by daemon that bound to socket IP 192.168.4.16 via UDP transport to port 5060.
To this socket is bound `dockerd` daemon. This daemon silently drop received UDP traffic when `userland-proxy` disabled.

In this case permanent UDP streams like syslog messages, SIP OPTIONS check newer reach container process and always connected to `docker` daemon black hole bind.

**How it can be reproduced**
On other host need to start UDP stream like
```sh
export SERVER_IP=217.12.247.220
nc -u ${SERVER_IP} 5060 < /dev/zero
```
Then on docker host need to populate `/etc/docker/daemon.json` file like this:
```json
{
  "userland-proxy": false
}
```
Restart docker daemon
```sh
systemctl restart docker
```
Then start test using command
```sh
conntrack -D
docker run --rm=true -d --network=host --name host_bind kamailio/kamailio-ci
sleep 10 \
docker stop host_bind \
docker run -it --rm -p 5060:5060/udp --entrypoint=tcpdump --name tcpdump kamailio/kamailio-ci -ni any
```
After last command container not able to receive UDP stream started on other host.

**How to fix**
When `userland-proxy` disabled and `dockerd` daemon received packet, then need reset related connection tracking record using command like
```sh
conntrack -D \
          --reply-src {dockerd_bind_ip} \
          --proto ${dockerd_bind_proto} \
          --reply-port-src {dockerd_bind_port} \
          --src ${client_source_ip} \
          --sport ${client_source_port} \
```

### LINKED ISSUE #7540: Inconsistent source IPs in containers
Hi,

I'm running rsyslog in a container. Basically just an ubuntu image with rsyslogd installed and a template configuration like this:

    $template FILENAME,"/var/log/%fromhost-ip%/%hostname%/syslog.log"

Exposed ports in Dockerfile: `EXPOSE     514/tcp 514/udp`

Now this works in general just fine, but I discovered some strange behavior regarding the source IP of the syslog packets: Sometimes the messages for remote systems end up in `[remote-host-ip]/[container-hostname]/syslog.log`, then after some time, they end up in `[docker0-bridges-ip]/[container-hostname]/syslog.log`. This seems to flip around from now and then.

As far as I understand, the expected behavior is:

- If you connect to a exposed port from localhost, inside the container the source IP is the IP of the docker0 bridge
- If you connect to a exposed port from a remote system, the source IP is the IP of the remote system

But it seems somehow those packets get routed via the docker0 IP and sometimes not. This makes not only running a syslog server hard but also debugging request logs in general.

### LINKED ISSUE #8795: Failed to receive UDP traffic after container restart
I start a container and share a port for UDP traffic as this:

docker run —rm -p 5060:5060/udp —name host1 -i -t ubuntu:14.04

Then in that container I wait for traffic with:

nc -u -l 5060

I then generate traffic from another machine:

nc -u <docker_host_ip> 5060

Then everything works fine and I can see that I receive the UDP traffic in the container.

But when I exit the container and do the same thing again, then I can no longer receive UDP traffic in the docker container.
If I wait for about 5 minutes before I start to send it will work though. I have also noticed that if the sender change the port it is binding to locally it will also work.  So there seems to be some mapping that is not deleted when the docker container is removed.

### LINKED ISSUE #16720: UDP traffic source IP is lost
Description of problem:

I have a container created with `-p 1234:1234/udp`. When I tcpdump on the host I can see UDP traffic coming from various sources:

```
# tcpdump -nn 'udp and dst port 1234'
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 65535 bytes
02:03:58.896506 IP 192.168.1.1.514 > 192.168.1.210.1234: SYSLOG local0.info, length: 159
02:03:58.896747 IP 192.168.1.1.514 > 192.168.1.210.1234: SYSLOG local0.info, length: 148
02:03:58.902976 IP 192.168.1.1.514 > 192.168.1.210.1234: SYSLOG local0.info, length: 159
02:03:58.903310 IP 192.168.1.1.514 > 192.168.1.210.1234: SYSLOG local0.info, length: 185
02:03:59.275255 IP 192.168.153.2.514 > 192.168.1.210.1234: SYSLOG local0.info, length: 153
02:03:59.275341 IP 192.168.153.2.514 > 192.168.1.210.1234: SYSLOG local0.info, length: 149
02:03:59.726084 IP 192.168.230.1.514 > 192.168.1.210.1234: SYSLOG local0.info, length: 146
02:03:59.726174 IP 192.168.230.1.514 > 192.168.1.210.1234: SYSLOG local0.info, length: 153
02:03:59.726296 IP 192.168.230.1.514 > 192.168.1.210.1234: SYSLOG local0.info, length: 205
```

But when I tcpdump in the container, the packets all have docker0's source IP:

```
root@6dc50e49a89d:/# tcpdump -nn 'udp and dst port 1234'
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 65535 bytes
09:06:13.804038 IP 172.17.42.1.59711 > 172.17.0.5.1234: UDP, length 152
09:06:13.804321 IP 172.17.42.1.59711 > 172.17.0.5.1234: UDP, length 192
09:06:13.804520 IP 172.17.42.1.59711 > 172.17.0.5.1234: UDP, length 150
09:06:14.207527 IP 172.17.42.1.37990 > 172.17.0.5.1234: UDP, length 154
09:06:14.864310 IP 172.17.42.1.59711 > 172.17.0.5.1234: UDP, length 148
09:06:14.864566 IP 172.17.42.1.59711 > 172.17.0.5.1234: UDP, length 150
09:06:14.864866 IP 172.17.42.1.59711 > 172.17.0.5.1234: UDP, length 147
```

`docker version`:

```
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```

`docker info`:

```
Containers: 3
Images: 72
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 78
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 6
Total Memory: 23.55 GiB
Name: core01
ID: 2OJM:LL4R:PJE4:SOEZ:DX2E:EVA2:5TOS:NKIL:ZSTP:VAXH:3YG5:AYK6
WARNING: No swap limit support
```

`uname -a`:

Linux core01 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):

Bare metal ubuntu 14.04.3

How reproducible: reproducible on the machine above and another machine running 1.6.2.

Steps to Reproduce:
1. Run container with UDP port forwarded
2. Run tcpdump on host and in container to display traffic on the forwarded port
3. Send UDP traffic to the host

Actual Results: packets displayed with tcpdump have a different source address outside/inside the container

Expected Results: packets displayed with tcpdump have the same source address outside/inside the container

### LINKED ISSUE #44688: docker-proxy processes UDP packets from a remote host
### Description

A remote host (10.8.4.1) is sending a stream of UDP packets to the Docker host (10.8.4.2), e.g. 10.8.4.1:10000 → 10.8.4.2:9555, so that there is a conntrack record in the kernel. Then a container listening for this UDP stream starts. Despite originating from the remote host, the stream gets handled by docker-proxy. The source address of the packets seen in the container is replaced by the address of the Docker bridge. If conntrack records are flushed or the UDP stream is restarted, the packets start reaching the container with the original source address (10.8.4.1).

### Reproduce

On the remote host (10.8.4.1), `hping3` must be installed.
On the Docker host (10.8.4.2), `conntrack`, `ss`, and `tcpdump` must be installed.
Docker daemon settings are the default.

1. On the remote host, start sending packets:
    `sudo hping3 --udp --flood --keep --destport 9555 --data 1 10.8.4.2`
2. Check connection tracking state on the Docker host:
    `conntrack -L -p 17`
3. Run the container:
    `docker run --rm -d --name server -p 9555:9555/udp raesene/ncat -nul 0.0.0.0 9555`
4. Check that the container receives packets with the source address of the Docker bridge:
    `nsenter -n -t `docker inspect -f '{{ .State.Pid }}' server` tcpdump -nvi eth0 udp | head`
5. Check that docker-proxy is involved:
    `ss -aunp | grep docker-proxy`
6. Remove tracked connections:
    `conntrack -D -p 17 --dport 9555`
7. Check that the container now receives packets with the remote host source address:
    `nsenter -n -t $(docker inspect -f '{{ .State.Pid }}' server) tcpdump -nvi eth0 udp | head`
8. Cleanup:
    `docker stop server`

### Expected behavior

The container receives packets with the remote host source address from the start.

### docker version

```bash
Client:
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.2
 Git commit:        20.10.12-0ubuntu2~20.04.1
 Built:             Wed Apr  6 02:14:38 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.2
  Git commit:       20.10.12-0ubuntu2~20.04.1
  Built:            Thu Feb 10 15:03:35 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.9-0ubuntu1~20.04.6
  GitCommit:        
 runc:
  Version:          1.1.0-0ubuntu1~20.04.2
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-135-generic
 Operating System: Ubuntu 20.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.839GiB
 Name: ubuntu2004
 ID: 7USK:YG7W:B6OA:NTQX:2HLQ:IHPA:SED4:XYGZ:PAR7:4PQ2:DNMU:AMJP
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  docker.netdike
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by akerouanton**
**- What I did**

Conntrack entries are created for UDP flows even if there's nowhere to route these packets (ie. no listening socket and no NAT rules to apply). Moreover, iptables NAT rules are evaluated by netfilter only when creating a new conntrack entry.

When Docker adds NAT rules, netfilter will ignore them for any packet matching a pre-existing conntrack entry. In such case, when dockerd runs with userland proxy enabled, packets got routed to it and the main symptom will be bad source IP address (as shown by #44688).

If the publishing container is run through Docker Swarm or in "standalone" Docker but with no userland proxy, affected packets will be dropped (eg. routed to nowhere).

As such, Docker needs to flush all conntrack entries for published UDP ports to make sure NAT rules are correctly applied to all packets.

- Fixes #44688
- Fixes #8795
- Fixes #16720
- Fixes #7540
- Fixes moby/libnetwork#2423
- and probably more.

As a precautionary measure (suggested by @corhere), those conntrack entries are also flushed when revoking external connectivity to avoid those entries to be reused when a new sandbox is created (although the kernel should already prevent such case, see review comments).

**- How to verify it**

By running the repro case in #44688.

As a side note: I tested the repro case with the current master branch, which includes #43409, but this fix doesn't work (at least not for that issue) as it's the equivalent of these commands:

```bash
$ conntrack -D -f ipv4 --reply-src 172.17.0.2
$ conntrack -D -f ipv4 --reply-dst 172.17.0.2
```

**- Description for the changelog**

Clear conntrack entries for published UDP ports.

### CODE REVIEW

**Comment by akerouanton** [comment]
@neersighted @corhere Please take a look :slightly_smiling_face:

**Review by corhere — APPROVED** [review]
Looks great, thank you!

cc: @evol262

File: libnetwork/drivers/bridge/setup_ip_tables.go [hunk 1]
```diff
@@ -429,3 +430,15 @@ func clearEndpointConnections(nlh *netlink.Handle, ep *bridgeEndpoint) {
 	}
 	iptables.DeleteConntrackEntries(nlh, ipv4List, ipv6List)
 }
+
+func clearConnectionsToUDPPorts(nlh *netlink.Handle, ep *bridgeEndpoint) {
```
Comment (corhere) [inline libnetwork/drivers/bridge/setup_ip_tables.go:434]: I wonder if this should be folded into `clearEndpointConnections`. Should UDP connections also be flushed when revoking external connectivity? (i.e. the other caller of `clearEndpointConnections`)

Comment (akerouanton) [reply libnetwork/drivers/bridge/setup_ip_tables.go:434]: > Should UDP connections also be flushed when revoking external connectivity? (i.e. the other caller of clearEndpointConnections)

From my testings, conntrack entries are deleted when the listening UDP socket got closed. If at this time, UDP packets still flow in, we're back to the bug reported in #44688. In the other hand, if UDP packets stop coming when the socket is closed, there's no more conntrack entries to worry about.

However, clearing conntrack entries as a precautionary measure won't hurt, so I'm ok doing this.

**Review by neersighted — APPROVED** [review]
With the unconditional usage, this looks even more obviously correct and is very easy to reason about in the context of existing code. LGTM!

**Review by corhere — APPROVED** [review]

**Review by evol262 — APPROVED** [review]
LGTM!

**Comment by neersighted** [comment]
I think this is an obvious backport to 23.0; how do we feel about the 20.10 branch? It would have to go into the external copy of libnetwork.

**Comment by corhere** [comment]
I'd want to let it soak in v23.0.0 for a couple weeks to give any unintended consequences time to reveal themselves in the field before backporting to 20.10.

**Comment by rafaeltorquato** [comment]
Is there a macos equivalent command?
