### PR TITLE
stack deploy exits with error if both 'external' and other options are specified for a volume

### LINKED ISSUE #29662: Docker 1.13 rc4 (stack)- driver_opts not working from yaml compose file!
I am using Docker stack (1.13 rc4). When I am using the flowing command:
Cmd: `docker volume create --opt type=none --opt device=/my-path-on-host --opt o=bind –name try3`
everything is working fine as you can see:
cmd: “docker volume inspect try3”:

```json
[
    {
        "Driver": "local",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/volumes/try3/_data",
        "Name": "try2",
        "Options": {
            "device": "/my-path-on-host ",
            "o": "bind",
            "type": "none"
        },
        "Scope": "local"
    }
]
```

But when I am using the command in yaml compose file format for docker stack like this: 

```yaml
version: '3'
volumes:
  try3:
    driver_opts:
      device: =/my-path-on-host
      o: bind
      type: none
    external: true
```

The volume try3 is created but all under driver_opts is ignored!
Cmd: “docker volume inspect try3”:

```json
[
    {
        "Driver": "local",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/volumes/try3/_data",
        "Name": "try2",
        "Options": { },
        "Scope": "local"
    }
]
```
What am I doing wrong? Or it’s a docker bug? If so when do you going to fix it?
Thanks!

### PR DESCRIPTION
**Pull request by adshmh**
stack deploy should exit with error if both 'external' and other options are specified for a volume. Fixes #29662.

Signed-off-by: Arash Deshmeh <adeshmeh@ca.ibm.com>

**- What I did**
stack deploy command ignores options specified for a volume when the 'external' option is set to true for that volume. This PR makes it an error to specify both 'external' and other options for a volume.

**- How I did it**
Added a check to test whether both 'external' is set and other options are specified for any of the volumes in the yaml compose file.

**- How to verify it**
1. Use a compose file with the following contents:
```
version: '3'
volumes:
  external_volume:
    driver_opts:
      device: =/my-path-on-host
    external: true
```

2. run stack deploy. With this PR included:
$ docker stack deploy --compose-file=./compose.yml s1
both 'external' and options are specified for volume "external_volume". Only one is allowed

**- Description for the changelog**
docker stack deploy exits with error if both 'external' is set and other options are specified for a volume.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: cli/compose/loader/loader.go [hunk 1]
```diff
@@ -427,9 +427,14 @@ func loadVolumes(source types.Dict) (map[string]types.VolumeConfig, error) {
 		return volumes, err
 	}
 	for name, volume := range volumes {
-		if volume.External.External && volume.External.Name == "" {
-			volume.External.Name = name
-			volumes[name] = volume
+		if volume.External.External {
+			if len(volume.DriverOpts) > 0 {
+				return nil, fmt.Errorf("both 'external' and options are specified for volume %q. Only one is allowed", name)
+			}
```
Comment (AkihiroSuda) [inline cli/compose/loader/loader.go]: need to check `volume.Labels` as well?

**Comment by vdemeester** [comment]
@adshmh looking at the composefile reference, this is by design (compose does nothing with an external volume) — https://docs.docker.com/compose/compose-file/#/external.

> external cannot be used in conjunction with other volume configuration keys (driver, driver_opts).

I feel we should close but let's ping @dnephin @shin- 👼

File: cli/compose/loader/loader.go (hunk 1 above)
Comment (vdemeester) [inline cli/compose/loader/loader.go]: https://docs.docker.com/compose/compose-file/#/external it's not specified — @dnephin @shin-

**Comment by vieux** [comment]
ping @dnephin

File: cli/compose/loader/loader.go (hunk 1 above)
Comment (dnephin) [inline cli/compose/loader/loader.go]: It's not, but the doc should say "any other option". I think it was written before labels existed.

So yes, labels should be checked as well.

Comment (adshmh) [inline cli/compose/loader/loader.go]: Thank you for the reviews. I will submit a PR on docs as well to specify that external cannot be combined with any other options.

File: cli/compose/loader/loader.go [hunk 2]
```diff
@@ -427,9 +427,21 @@ func loadVolumes(source types.Dict) (map[string]types.VolumeConfig, error) {
 		return volumes, err
 	}
 	for name, volume := range volumes {
-		if volume.External.External && volume.External.Name == "" {
-			volume.External.Name = name
-			volumes[name] = volume
+		if volume.External.External {
+			template := "both external and %s are specified for volume %q. Only one is allowed."
```
Comment (aaronlehmann) [inline cli/compose/loader/loader.go]: It reads a little strangely for this to start with a lowercase letter (as errors should) and have a second sentence that starts with uppercase. In general I try to avoid multiple sentences in an error string. How about `conflicting parameters "external" and %q specified for volume %q`?

**Comment by aaronlehmann** [comment]
ping @dnephin

File: cli/compose/loader/loader.go (hunk 2 above)
Comment (adshmh) [inline cli/compose/loader/loader.go]: Thank you for the review. Yes, I think this reads a lot better. Will update the PR.

**Review by dnephin — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🦁

**Comment by thaJeztah** [comment]
Ignoring PowerPC and Z, everything else is green
