### PR TITLE
Fix AppArmor profile docker-default /proc/sys rule

### LINKED ISSUE #39791: apparmor docker-default incorrect fileglob blocks /proc/sys/*/**
**Description**

The docker-default apparmor profile blocks access to `/proc/sys/*/**` (including `/proc/sys/kernel/shm*`) which seems to conflict with the intention of the rules.

https://github.com/moby/moby/blob/2a64e344b7b1a99ff8b5ab115e71656c6fa12838/profiles/apparmor/template.go#L28-L31

**Steps to reproduce the issue:**
1. Run a container and attempt to write to /proc/sys/kernel/shmmax

```bash
docker run --privileged --security-opt apparmor=docker-default --rm -it ubuntu bash -c ">> /proc/sys/kernel/shmmax && echo success"
```

**Describe the results you received:**
```
bash: /proc/sys/kernel/shmmax: Permission denied
```

**Describe the results you expected:**
```
success
```

**Additional information you deem important (e.g. issue happens only occasionally):**

This is the line with the problematic fileglob:

https://github.com/moby/moby/blob/2a64e344b7b1a99ff8b5ab115e71656c6fa12838/profiles/apparmor/template.go#L29

Specifically the last part:
```
[^1-9][^0-9][^0-9][^0-9]
```
The last `[^0-9]` can match `/`, so this matches `sys/`, and the full expression matches `/proc/sys/*/**`.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:21:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:19:41 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-51-generic
 Operating System: Ubuntu 18.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 985.4MiB
 Name: vagrant
 ID: 6W3H:2I7B:WMH4:2UTA:QAGX:FNZ5:2S3W:O4CW:65Y4:IFRW:4ANK:PZZG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VirtualBox on macOS 10.14.6, using vagrant box: bento/ubuntu-18.04  (virtualbox, 201906.18.0)
Originally observed in Ubuntu 16.04.6 LTS with docker-ce 17.03.3-ce

### PR DESCRIPTION
**Pull request by philsphicas**
The current docker-default AppArmor profile intends to block write
access to everything in `/proc`, except for `/proc/<pid>` and
`/proc/sys/kernel/shm*`.

Currently the rules block access to everything in `/proc/sys`, and do
not successfully allow access to `/proc/sys/kernel/shm*`. Specifically,
a path like /proc/sys/kernel/shmmax matches this part of the pattern:

    deny @{PROC}/{[^1-9][^0-9][^0-9][^0-9]*     }/** w,
         /proc  / s     y     s     /     kernel /shmmax

This patch updates the rule so that it works as intended.

Closes #39791

Signed-off-by: Phil Sphicas <phil.sphicas@att.com>

**- What I did**
Updated docker-default AppArmor profile to match intention of allowing write access to /proc/sys/kernel/shm*

**- How I did it**
Modified the fileglob in the deny rule

**- How to verify it**
With the updated profile, this should return `success`:

```bash
docker run --privileged --security-opt apparmor=docker-default --rm -it ubuntu bash -c ">> /proc/sys/kernel/shmmax && echo success"
```

**- Description for the changelog**

Fix AppArmor profile docker-default /proc/sys rule

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks! Change itself SGTM, I'm looking if we can add a test somewhere. Problem with that is that current tests are in the (now frozen) `integration-cli` tests, and adding a new test there would make CI fail, so ideally we'd move those tests to the new `integration` directory first, but that might be a bit of work. https://github.com/moby/moby/blob/38ab9da0030917f154f4d1b05962d48de149d47c/integration-cli/docker_cli_run_test.go#L3165-L3198

**Comment by thaJeztah** [comment]
ping @justincormack PTAL

**Comment by philsphicas** [comment]
Agreed, it would be nice to have a test case for this. We actually only noticed the issue when trying to modify `docker-default` to allow write access to `/proc/sys/net`, and discovered that just changing `[^k]` to [^kn]` here didn't do anything:

https://github.com/moby/moby/blob/2a64e344b7b1a99ff8b5ab115e71656c6fa12838/profiles/apparmor/template.go#L30

(I saw a #22704 about having the AppArmor policy align with capabilities .. that might be nice for `NET_ADMIN`)

**Comment by andrewhsu** [comment]
A lot has changed in the master branch to the PR checks. If this could get a rebase, would then re-run with relevant tests (even though this PR doesn't have a specific test for this change) would be good to get official green before review. cc @justincormack

**Comment by thaJeztah** [comment]
ping @justincormack PTAL

**Comment by thaJeztah** [comment]
ping @justincormack @ewindisch PTAL 🤗

**Comment by thaJeztah** [comment]
@justincormack @cyphar ptal

File: profiles/apparmor/template.go [hunk 1]
```diff
@@ -26,7 +26,7 @@ profile {{.Name}} flags=(attach_disconnected,mediate_deleted) {
 
   deny @{PROC}/* w,   # deny write for all files directly in /proc (not in a subdir)
   # deny write to files not in /proc/<number>/** or /proc/sys/**
-  deny @{PROC}/{[^1-9],[^1-9][^0-9],[^1-9s][^0-9y][^0-9s],[^1-9][^0-9][^0-9][^0-9]*}/** w,
+  deny @{PROC}/{[^1-9],[^1-9][^0-9],[^1-9s][^0-9y][^0-9s],[^1-9][^0-9][^0-9][^0-9/]*}/** w,
```
Comment (cyphar) [inline profiles/apparmor/template.go:29]: I think it'd be a little bit easier to follow (though to be fair, not by much) if we added "sys" to the last case as well:

```
deny @{PROC}/{[^1-9],[^1-9][^0-9],[^1-9s][^0-9y][^0-9s],[^1-9s][^0-9y][^0-9s][^0-9/]*}/** w,
```
(AppArmor profiles make my eyes hurt :fire::eyes::fire:.)

Comment (justincormack) [reply profiles/apparmor/template.go:29]: Ugh, um yeah thats a little clearer, maybe, I would like a comment explaining this

Comment (cyphar) [reply profiles/apparmor/template.go:29]: Yeah maybe a paragraph. The fact this is necessary at all is completely insane...

Comment (cyphar) [reply profiles/apparmor/template.go:29]: Maybe I'm failing to remember something, but was there a reason why we didn't split these into separate `deny` statements?

Comment (corhere) [reply profiles/apparmor/template.go:29]: IMO adding "sys" to the last alternative does not make it any easier to follow as it extends the do-not-deny list in odd directions: e.g. `/proc/sys3foo/bar` would be not-denied by such a rule. What I think would help make it easier to understand would be to restrict all the patterns to match within a single path component. Exploding the alternation into separate rules might also help, especially as it gives more room for comments.
```suggestion
  deny @{PROC}/[^1-9]/** w,  # deny /proc/?/** except /proc/<pid>/**
  deny @{PROC}/[^1-9][^0-9/]/** w,  # deny /proc/??/** except /proc/<pid>/**
  deny @{PROC}/[^1-9s][^0-9y/][^0-9s/]/** w,  # deny /proc/???/** except /proc/<pid>/** or /proc/sys/**
  deny @{PROC}/[^1-9][^0-9/][^0-9/][^0-9/]*/** w,  # deny /proc/???*/** except /proc/<pid>/**
```

**Review by corhere — APPROVED** [review]

**Comment by thaJeztah** [comment]
I did a quick rebase earlier to get a fresh run of CI. We discussed this PR in our maintainers meeting, and were good with merging this as-is, keeping further cleaning up and/or optimisation for a follow up (if someone wants to work on those).

**Review by thaJeztah — APPROVED** [review]
LGTM

CI is still happy 👍
