### PR TITLE
Ensure Host Network Service exists

### LINKED ISSUE #34920: Failure to install container role on Windows results in utterly unhelpful error message
Docker on Windows Server 2016 requires the Hyper-V and Container roles to be installed. If the Container role is not installed the error message in the debug logs is a failure in a HNS (Host Networking Service) call and provides no clue that the Container role is missing.

**Steps to reproduce the issue:**
1. Install a WS2016 machine/VM
2. Install the Hyper-V role (`Add-WindowsFeature -Name Containers`
3. Install Docker (https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-server or https://docs.docker.com/engine/installation/windows/docker-ee/)

**Describe the results you received:**
dockerd starts and runs normally

**Describe the results you expected:**
dockerd fails to start with the following message in the debug log:
`Error starting daemon: Error initializing network controller: hnsCall failed in Win32: Class not registered (0x800040154)`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
Doesn't run in this case, but I was using `17.10.0-ee-preview-1`, commit `139fcd3`

**Output of `docker info`:**

Doesn't run in this case

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Azure VMs
Per @dineshgovindasamy there is no check for the Container role being present

### PR DESCRIPTION
**Pull request by darstahl**
**- What I did**

Fixes https://github.com/moby/moby/issues/34920

The HNS service is the host network service required for container networking. If the service does not exist, the daemon will fail when trying to restore existing networks. This moves the failure earlier in the daemon start to provide a better error message.

**- How I did it**

Prevent daemon from starting if Host Network Service does not exist.

**- How to verify it**

Due to the global state required to test this, it is not tested in CI, but the unit test tests the added ensureServicesInstalled function.

Tested manually on RS1 and RS3 with all combinations of installed roles Hyper-V and Containers. The only change is in RS3, if Hyper-V role is installed, but Containers role is not, the daemon now fails with the new error:

```
PS C:\Windows\system32> dockerd
Error starting daemon: a required service is not installed, ensure the Containers role is installed: failed to open service hns: The specified service does not exist as an installed service.
```

**- Description for the changelog**

N/A

@andrewhsu I think this should be considered for backporting to 17.06. If a currently working Docker host has the Hyper-V role installed, but not the containers role installed (an unsupported configuration that happens to work on current (pre-RS3) versions of Windows), the upgrade to RS3 may cause the daemon to fail to start with a generic sounding HNS error (see https://github.com/moby/moby/issues/34920). This fix would provide a proper error message so that they can install the Containers role to fix the issue.

### CODE REVIEW

**Comment by darrenstahlmsft** [comment]
@jhowardmsft PTAL

**Comment by msabansal** [comment]
LGTM

File: daemon/daemon_windows.go [hunk 1]
```diff
@@ -238,6 +240,29 @@ func checkSystem() error {
 		return fmt.Errorf("Failed to load vmcompute.dll. Ensure that the Containers role is installed.")
 	}
 
+	// Ensure that the required Host Network Service and vmcompute services
+	// are running. Docker will fail in unexpected ways if this is not present.
+	var requiredServices = []string{"hns", "vmcompute"}
+	if err := ensureServicesInstalled(requiredServices); err != nil {
+		return errors.Wrap(err, "a required service is not installed, ensure the Containers role is installed")
```
Comment (jhowardmsft) [inline daemon/daemon_windows.go]: Nit - it's actually a feature

File: daemon/daemon_windows.go [hunk 2]
```diff
@@ -238,6 +240,29 @@ func checkSystem() error {
...
+	if err != nil {
+		return err
+	}
+	defer m.Disconnect()
+	for _, service := range services {
+		s, err := m.OpenService(service)
+		if err != nil {
+			return errors.Wrapf(err, "failed to open service %s", service)
+		}
+		defer s.Close()
```
Comment (jhowardmsft) [inline daemon/daemon_windows.go]: Why defer this?

File: daemon/daemon_windows.go [hunk 3]
```diff
@@ -238,6 +240,29 @@ func checkSystem() error {
 		return fmt.Errorf("Failed to load vmcompute.dll. Ensure that the Containers role is installed.")
```
Comment (jhowardmsft) [inline daemon/daemon_windows.go]: This should probably be updated to `feature` too

**Review by lowenna — CHANGES_REQUESTED** [review]

File: daemon/daemon_windows.go (hunk 3 above)
Comment (darrenstahlmsft) [reply daemon/daemon_windows.go]: Since I'd like to backport this fix to 17.06, I think this should be done in a followup to prevent changing error messages in an already released version. Just in case.

File: daemon/daemon_windows.go (hunk 2 above)
Comment (darrenstahlmsft) [reply daemon/daemon_windows.go]: Ah, yep, wasn't thinking. Closing immediately.

File: daemon/daemon_windows.go (hunk 1 above)
Comment (darrenstahlmsft) [reply daemon/daemon_windows.go]: fixed

File: daemon/daemon_windows.go (hunk 3 above)
Comment (jhowardmsft) [reply daemon/daemon_windows.go]: Makes sense - can you open a follow-up PR to change this?

**Review by lowenna — APPROVED** [review]
LGTM when green

File: daemon/daemon_windows.go [hunk 4]
```diff
@@ -238,6 +240,29 @@ func checkSystem() error {
...
 	}
 
+	// Ensure that the required Host Network Service and vmcompute services
+	// are running. Docker will fail in unexpected ways if this is not present.
```
Comment (johnstep) [inline daemon/daemon_windows.go]: Nit: Consider consistency in referencing the services in the comment, either `hns` and `vmcompute` or `Host Network Service` and `Hyper-V Host Compute Service`. Also, `s/if this is not present/if these are not present/`.

**Review by johnstep — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
All green, and two LGTM's - merging
