### PR TITLE
Fix issue for `--fixed-cidr` when bridge has multiple addresses

### LINKED ISSUE #22204: Docker 1.11.0 daemon start failure after fresh install on CentOS 7
**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:40:36 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical box running CentOS 7 with kernel 3.10.0-327.13.1.el7.x86_64. Docker installed via https://yum.dockerproject.org/

**Steps to reproduce the issue:**
1. Install docker on CentOS 7 following "Install with yum" instructions on https://docs.docker.com/engine/installation/linux/centos/
2. Attempt to start the docker daemon with `sudo systemctl start docker`
3. Failure to start the daemon

**Describe the results you received:**
`sudo systemctly start docker` returns with
`Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.`

`sudo systemctl status docker -l` returns 

```
docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2016-04-20 17:20:38 UTC; 5s ago
     Docs: https://docs.docker.com
  Process: 10321 ExecStart=/usr/bin/docker daemon -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 10321 (code=exited, status=1/FAILURE)

Apr 20 17:20:37 [host redacted] docker[10321]: time="2016-04-20T17:20:37.890490133Z" level=warning msg="devmapper: Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man docker` to refer to dm.thinpooldev section."
Apr 20 17:20:37 [host redacted] docker[10321]: time="2016-04-20T17:20:37.915473736Z" level=info msg="devmapper: Creating filesystem xfs on device docker-253:0-134417280-base"
Apr 20 17:20:38 [host redacted] docker[10321]: time="2016-04-20T17:20:38.258365176Z" level=info msg="devmapper: Successfully created filesystem xfs on device docker-253:0-134417280-base"
Apr 20 17:20:38 [host redacted] docker[10321]: time="2016-04-20T17:20:38.299893813Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Apr 20 17:20:38 [host redacted] docker[10321]: time="2016-04-20T17:20:38.314537929Z" level=info msg="Firewalld running: true"
Apr 20 17:20:38 [host redacted] docker[10321]: time="2016-04-20T17:20:38.501717532Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: failed to parse pool request for address space \"LocalDefault\" pool \"\" subpool \"\": could not find an available predefined network"
Apr 20 17:20:38 [host redacted] systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Apr 20 17:20:38 [host redacted] systemd[1]: Failed to start Docker Application Container Engine.
Apr 20 17:20:38 [host redacted] systemd[1]: Unit docker.service entered failed state.
Apr 20 17:20:38 [host redacted] systemd[1]: docker.service failed.
```

**Describe the results you expected:**
I expected the service to start and allow me to verify the installation by running `sudo docker run hello-world`

**Additional information you deem important (e.g. issue happens only occasionally):**
This issue occurs 100% of the time. I have no legacy issues stemming from docker upgrades as this machine has never had docker running on it. I have seen other issues that sound similar to mine but none of the solutions (notably deleting `/var/lib/docker/network`) seem to allow the docker daemon to start.

### LINKED ISSUE #24637: Cannot start Apache Spark on multi-host in Swarm mode
I simply cannot schedule instances of Apache Spark over the multi-host network in Swarm mode.

**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 04:15:13 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 04:15:13 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 12
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: active
 NodeID: 452huztay9dzxtehh50mzgf9o
 IsManager: Yes
 Managers: 1
 Nodes: 2
 CACertHash: sha256:2445358bb26a09d3b7cf67e0324b187fc6c0c4f71f0ae1413bd7b0838b26594f
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-28-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.797 GiB
Name: master
ID: QEVB:ADKU:BJFR:U7PB:NG2T:SBQH:B5NN:ZTNT:BLED:PE57:OY32:NXZQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
DigitalOcean

**Steps to reproduce the issue:**
1. Create 2 nodes `master` and `node1`. Do `docker swarm init` & `docker swarm join`
2. Create an overlay network, in my case: `docker network create --driver overlay spark`
3. Run `docker service create --name master --network spark -p 7077:7077 -p 8080:8080 gettyimages/spark:1.6.2-hadoop-2.6 bin/spark-class org.apache.spark.deploy.master.Master`
4. Run `docker service create --name worker --network spark -p 8081:8081 gettyimages/spark:1.6.2-hadoop-2.6 bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077`
5. Scale worker to 2. You'll see it's trying to schedule a container on `node1` then failed and all 2 workers will be on master.

**Describe the results you received:**
Apache Spark instances were scheduled only on master nodes.

**Describe the results you expected:**
Apache Spark instances should be scheduled on both master and node1.
It is likely that containers on `node1` cannot resolve name `master` or cannot connect to the `master` IP correctly.

cc @mavenugo

### LINKED ISSUE #26341: --fixed-cidr doesn't work correctly when the bridge device has multiple IP addresses
**`docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64
```

**`docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 28
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-36-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 62.81 GiB
Name: censored
ID: JHCA:3763:5XK5:RPKU:TRN2:SJ67:M3NJ:USGV:JU6A:2HGN:4VZJ:W2ET
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Steps to reproduce the issue:**

1. Configure a bridge with two different IP addresses:

 ```
brctl addbr cbr0
ip addr add 10.111.111.111/20 dev cbr0 label cbr0:main
ip addr add 10.222.222.222/12 dev cbr0 label cbr0:docker
ip link set cbr0 up
ip addr show cbr0
12: cbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
    inet 10.111.111.111/20 scope global cbr0:main
       valid_lft forever preferred_lft forever
    inet 10.222.222.222/12 scope global cbr0:docker
       valid_lft forever preferred_lft forever
```

2. Run Docker:

 ```
docker daemon --bridge=cbr0 --iptables=false --ip-masq=false --fixed-cidr=10.222.222.222/24
```

3. Start a container and see its IP:

 ```
docker run --rm ubuntu:14.04 ip route get 8.8.8.8 | grep -Po 'src.*'
src 10.111.110.0

docker run --rm ubuntu:14.04 ip addr show eth0
32: eth0@if33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:0a:6f:6e:00 brd ff:ff:ff:ff:ff:ff
    inet 10.111.110.0/20 scope global eth0
       valid_lft forever preferred_lft forever
```

I expected to see the container get an IP address in the specified CIDR range (`10.222.222.222/24 = 10.222.222.0 - 10.222.222.254`).

If we reorder the IP addresses on the bridge IP allocation works as expected:

```
ip addr del 10.111.111.111/20 dev cbr0 label cbr0:main
ip addr add 10.111.111.111/20 dev cbr0 label cbr0:main
25: cbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
    inet 10.222.222.222/12 scope global cbr0:docker
       valid_lft forever preferred_lft forever
    inet 10.111.111.111/20 scope global cbr0:main
       valid_lft forever preferred_lft forever

# restart docker now (otherwise it won't work)

docker run --rm ubuntu:14.04 ip route get 8.8.8.8 | grep -Po 'src.*'
src 10.222.222.0
```

### LINKED ISSUE #27157: [swarm/networking] Cannot start a Cassandra cluster on swarm mode
**Description**

I'm not able to create a swarm service over the overlay network due to multiple IP addresses resolving `localhost` on /etc/hosts.

**Steps to reproduce the issue:**
1. docker network create -d overlay spark
2.docker service create --name cassandra --network spark cassandra:2.2.0

**Describe the results you received:**
```
root@rogaha-master1:~# docker service ls
ID            NAME       REPLICAS  IMAGE            COMMAND
4h92nrsoo21w  cassandra  0/1       cassandra:2.2.0

root@rogaha-node1:~# docker logs 5c62ccb3098b
INFO  09:17:09 Loading settings from file:/etc/cassandra/cassandra.yaml
INFO  09:17:09 Node configuration:[authenticator=AllowAllAuthenticator; authorizer=AllowAllAuthorizer; auto_snapshot=true; batch_size_fail_threshold_in_kb=50; batch_size_warn_threshold_in_kb=5; batchlog_replay_throttle_in_kb=1024; broadcast_address=10.0.0.3 172.18.0.3; broadcast_rpc_address=10.0.0.3 172.18.0.3; cas_contention_timeout_in_ms=1000; client_encryption_options=<REDACTED>; cluster_name=Test Cluster; column_index_size_in_kb=64; commit_failure_policy=stop; commitlog_directory=/var/lib/cassandra/commitlog; commitlog_segment_size_in_mb=32; commitlog_sync=periodic; commitlog_sync_period_in_ms=10000; compaction_large_partition_warning_threshold_mb=100; compaction_throughput_mb_per_sec=16; concurrent_counter_writes=32; concurrent_reads=32; concurrent_writes=32; counter_cache_save_period=7200; counter_cache_size_in_mb=null; counter_write_request_timeout_in_ms=5000; cross_node_timeout=false; data_file_directories=[/var/lib/cassandra/data]; disk_failure_policy=stop; dynamic_snitch_badness_threshold=0.1; dynamic_snitch_reset_interval_in_ms=600000; dynamic_snitch_update_interval_in_ms=100; enable_user_defined_functions=false; endpoint_snitch=SimpleSnitch; hinted_handoff_enabled=true; hinted_handoff_throttle_in_kb=1024; incremental_backups=false; index_summary_capacity_in_mb=null; index_summary_resize_interval_in_minutes=60; inter_dc_tcp_nodelay=false; internode_compression=all; key_cache_save_period=14400; key_cache_size_in_mb=null; listen_address=10.0.0.3 172.18.0.3; max_hint_window_in_ms=10800000; max_hints_delivery_threads=2; memtable_allocation_type=heap_buffers; native_transport_port=9042; num_tokens=256; partitioner=org.apache.cassandra.dht.Murmur3Partitioner; permissions_validity_in_ms=2000; range_request_timeout_in_ms=10000; read_request_timeout_in_ms=5000; request_scheduler=org.apache.cassandra.scheduler.NoScheduler; request_timeout_in_ms=10000; role_manager=CassandraRoleManager; roles_validity_in_ms=2000; row_cache_save_period=0; row_cache_size_in_mb=0; rpc_address=0.0.0.0; rpc_keepalive=true; rpc_port=9160; rpc_server_type=sync; saved_caches_directory=/var/lib/cassandra/saved_caches; seed_provider=[{class_name=org.apache.cassandra.locator.SimpleSeedProvider, parameters=[{seeds=10.0.0.3 172.18.0.3}]}]; server_encryption_options=<REDACTED>; snapshot_before_compaction=false; ssl_storage_port=7001; sstable_preemptive_open_interval_in_mb=50; start_native_transport=true; start_rpc=false; storage_port=7000; thrift_framed_transport_size_in_mb=15; tombstone_failure_threshold=100000; tombstone_warn_threshold=1000; tracetype_query_ttl=86400; tracetype_repair_ttl=604800; trickle_fsync=false; trickle_fsync_interval_in_kb=10240; truncate_request_timeout_in_ms=60000; windows_timer_interval=1; write_request_timeout_in_ms=2000]
INFO  09:17:09 DiskAccessMode 'auto' determined to be mmap, indexAccessMode is mmap
INFO  09:17:09 Global memtable on-heap threshold is enabled at 983MB
INFO  09:17:09 Global memtable off-heap threshold is enabled at 983MB
Unknown listen_address '10.0.0.3 172.18.0.3'
Exception (org.apache.cassandra.exceptions.ConfigurationException) encountered during startup: Unknown listen_address '10.0.0.3 172.18.0.3'
ERROR 09:17:09 Exception encountered during startup: Unknown listen_address '10.0.0.3 172.18.0.3'
```

**Describe the results you expected:**
```
root@rogaha-master1:~# docker service ls
ID            NAME       REPLICAS  IMAGE            COMMAND
4h92nrsoo21w  cassandra  1/1       cassandra:2.2.0
```
**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
 Client:
 Version:      1.12.2-rc2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   ad9538a
 Built:        Tue Oct  4 18:23:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2-rc2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   ad9538a
 Built:        Tue Oct  4 18:23:48 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Client:
 Version:      1.12.2-rc2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   ad9538a
 Built:        Tue Oct  4 18:23:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2-rc2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   ad9538a
 Built:        Tue Oct  4 18:23:48 2016
 OS/Arch:      linux/amd64
root@rogaha-master1:~# docker info
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 15
Server Version: 1.12.2-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 184
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: active
 NodeID: 0ssb9bjf9akhksynnyjxtc99s
 Is Manager: true
 ClusterID: 8k5xu580gk0xojxozasllt48o
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 159.203.82.121
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859 GiB
Name: rogaha-master1
ID: 53EJ:N7XD:76ER:WTHR:Y5UR:E227:WFNT:HUEI:LZUS:WYIG:MZ32:S3KS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: rogaha
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
DigitalOcean

### PR DESCRIPTION
**Pull request by yongtang**
**\- What I did**

This fix tries to address the issue raised in #26341 where multiple addresses in a bridge may cause `--fixed-cidr` to not have the correct addresses.

The issue is that `netutils.ElectInterfaceAddresses(bridgeName)` only returns the first IPv4 address.

**\- How I did it**

This fix (together with the PR created in libnetwork https://github.com/docker/libnetwork/pull/1452) changes `ElectInterfaceAddresses()` and `addresses()` so that all IPv4 addresses are returned. This will allow the possibility of selectively choose the address needed.

In `daemon_unix.go`, bridge address is chosen by comparing with the `--fixed-cidr` first, thus resolve the issue in #26341.

**\- How to verify it**
This fix is tested manually, as is described in #26341:

```
brctl addbr cbr0
ip addr add 10.111.111.111/20 dev cbr0 label cbr0:main
ip addr add 10.222.222.222/12 dev cbr0 label cbr0:docker
ip link set cbr0 up
docker daemon --bridge=cbr0 --iptables=false --ip-masq=false --fixed-cidr=10.222.222.222/24
docker run --rm busybox ip route get 8.8.8.8 | grep -Po 'src.*'
src 10.222.222.0
```

**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**

This fix fixes #26341.

This fix is related to libnetwork PR https://github.com/docker/libnetwork/pull/1452

**libnetwork vendoring:**
Fixes #22204 
Fixes #24637 
Fixes #27157 
Also, https://github.com/docker/libnetwork/pull/1333, https://github.com/docker/libnetwork/pull/1480

Signed-off-by: Yong Tang yong.tang.github@outlook.com

### CODE REVIEW

File: daemon/daemon_unix.go [hunk 1]
```diff
@@ -690,8 +690,21 @@ func initBridgeDriver(controller libnetwork.NetworkController, config *Config) e
 
 	ipamV4Conf = &libnetwork.IpamConf{AuxAddresses: make(map[string]string)}
 
-	nw, nw6List, err := netutils.ElectInterfaceAddresses(bridgeName)
+	nw, nwList, nw6List, err := netutils.ElectInterfaceAddresses(bridgeName)
 	if err == nil {
+		if config.bridgeConfig.FixedCIDR != "" {
+			_, fCIDR, err := net.ParseCIDR(config.bridgeConfig.FixedCIDR)
+			if err != nil {
+				return err
```
Comment (cpuguy83) [inline daemon/daemon_unix.go]: Can you use `errors.Wrap()` here from github.com/pkg/errors? It's already vendored.

File: vendor/src/github.com/docker/libnetwork/drivers/bridge/interface.go [hunk 2]
```diff
@@ -52,27 +52,27 @@ func (i *bridgeInterface) exists() bool {
 	return i.Link != nil
 }
 
-// addresses returns a single IPv4 address and all IPv6 addresses for the
+// addresses returns the first IPv4 address, all IPv4 addresses, and all IPv6 addresses for the
 // bridge interface.
-func (i *bridgeInterface) addresses() (netlink.Addr, []netlink.Addr, error) {
+func (i *bridgeInterface) addresses() (netlink.Addr, []netlink.Addr, []netlink.Addr, error) {
```
Comment (cpuguy83) [inline vendor/src/github.com/docker/libnetwork/drivers/bridge/interface.go]: This is pretty unwieldy and I really have no idea what each return actually is without reading the comment above.

Seems like we can at least remove the first return and just call `[0]` to get the "first ipv4 address"

File: vendor/src/github.com/docker/libnetwork/drivers/bridge/setup_ipv4.go [hunk 3]
```diff
@@ -11,11 +11,21 @@ import (
...
 
 func setupBridgeIPv4(config *networkConfiguration, i *bridgeInterface) error {
-	addrv4, _, err := i.addresses()
+	addrv4, addrv4List, _, err := i.addresses()
 	if err != nil {
 		return fmt.Errorf("failed to retrieve bridge interface addresses: %v", err)
 	}
 
+	// Iterate through all IPv4 addresses in case multiple IPv4 addresses exist
+	if config.AddressIPv4 != nil {
```
Comment (cpuguy83) [inline vendor/src/github.com/docker/libnetwork/drivers/bridge/setup_ipv4.go]: Seems like a pretty common pattern in the patch.

**Review by cpuguy83 — CHANGES_REQUESTED** [review]
ping @mavenugo

File: daemon/daemon_unix.go (hunk 1 above)
Comment (yongtang) [inline daemon/daemon_unix.go]: Fixed.

File: vendor/src/github.com/docker/libnetwork/drivers/bridge/interface.go (hunk 2 above)
Comment (yongtang) [inline vendor/src/github.com/docker/libnetwork/drivers/bridge/interface.go]: Thanks @cpuguy83 the PR has been updated.

File: vendor/src/github.com/docker/libnetwork/drivers/bridge/setup_ipv4.go (hunk 3 above)
Comment (yongtang) [inline vendor/src/github.com/docker/libnetwork/drivers/bridge/setup_ipv4.go]: Thanks @cpuguy83. The PR has been updated with the logic wrapped into a new func.

**Comment by yongtang** [comment]
@cpuguy83 Thanks for the review. The PR has been updated. Please take a look and let me know if there are any other issues.

File: daemon/daemon_unix.go [hunk 4]
```diff
@@ -690,13 +691,30 @@ func initBridgeDriver(controller libnetwork.NetworkController, config *Config) e
...
-		hip, _ := lntypes.GetHostPartIP(nw.IP, nw.Mask)
-		if hip.IsGlobalUnicast() {
-			ipamV4Conf.Gateway = nw.IP.String()
+	nwList, nw6List, err := netutils.ElectInterfaceAddresses(bridgeName)
+	if err != nil {
+		return errors.Wrap(err, "list bridge addresses failed")
+	}
+
+	nw := nwList[0]
+	if config.bridgeConfig.FixedCIDR != "" {
```
Comment (yongtang) [inline daemon/daemon_unix.go]: Thanks @aboch for the review. The PR has been updated with the changes.

**Comment by yongtang** [comment]
@aboch The PR has been rebased and libnetwork has been vendored as well. Please take a look and let me know if there are any issues.

**Comment by aboch** [comment]
Thanks @yongtang I will update the issue's description to include which docker PRs the libnetwork vendoring will fix

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Comment by rogaha** [comment]
Thanks for working on it @crosbymichael! 👍
