### PR TITLE
Revert push to v2 official registry

### LINKED ISSUE #10557: Issue pushing with 1.5.0-rc3
Okay the following failed

```
docker push rancher/agent:latest
511136ea3c5a: Image push failed 
FATA[0008] Error pushing to registry: Put ?digest=tarsum.v1%2Bsha256%3Ae3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855: unsupported protocol scheme "" 
```

But then if I run it again it works.  Here's the debug log.

When it failed
```
INFO[0071] POST /v1.17/images/rancher/agent/push?tag=latest 
INFO[0071] +job push(rancher/agent)                     
INFO[0071] +job resolve_repository(rancher/agent)       
INFO[0071] -job resolve_repository(rancher/agent) = OK (0) 
DEBU[0071] pinging registry endpoint https://index.docker.io/v1/ 
DEBU[0071] attempting v1 ping for registry endpoint https://index.docker.io/v1/ 
DEBU[0071] pinging registry endpoint https://registry-1.docker.io/v2/ 
DEBU[0071] attempting v2 ping for registry endpoint https://registry-1.docker.io/v2/ 
DEBU[0071] hostDir: /etc/docker/certs.d/registry-1.docker.io 
DEBU[0071] Checking latest against graph.Repository{"latest":"3d409ba796f9b5d392bcfaa9fb497d5b4cabade335d702c5f565efba9bbc3beb", "v0.2.0":"30110e1962c7db9f1169e47d6b25017934874a20ce3516a4731a354eeeaaef7a", "v0.3.1-rc1":"14b8f671a5df9bd20147eabdd420b44e7821dc6d6617319c915dae4f66a157bb", "v0.4.0":"5d478726652a0b5705298d02e713ab0bd77fc345b4c4ca9f8225e54c528ca3b2", "v0.2.1":"7102021a406650986a338c510993a43cfbb2387fc7d1d537a3e79016bc378d1f", "v0.3.0":"39ef1083a0be60d8f1dda758b743cd891bf12d1d60c3596cbccacc233f985cd8", "v0.3.1":"3d409ba796f9b5d392bcfaa9fb497d5b4cabade335d702c5f565efba9bbc3beb", "v0.3.1-rc2":"14b8f671a5df9bd20147eabdd420b44e7821dc6d6617319c915dae4f66a157bb", "v0.3.1-rc3":"b3d5b7de09d2381e0ec1422d0a03acce64df2406ccd521f0cc11c9d4c22d9cd2"} 
DEBU[0071] Getting authorization for rancher/agent [pull push] 
DEBU[0071] Pushing rancher/agent:latest to v2 repository 
INFO[0073] Signed manifest for rancher/agent:latest using daemon's key: FPSO:Z7SO:BZJ3:IXH4:DNKV:UPZQ:KLP2:IRXW:5CBY:PBDM:HAKO:UOC7 
INFO[0073] +job trust_key_check(/rancher/agent)         
DEBU[0073] Verification failed for /rancher/agent using key FPSO:Z7SO:BZJ3:IXH4:DNKV:UPZQ:KLP2:IRXW:5CBY:PBDM:HAKO:UOC7 
INFO[0073] -job trust_key_check(/rancher/agent) = OK (0) 
DEBU[0073] Key check result: "not verified"             
DEBU[0073] [registry] Calling "HEAD" https://registry-1.docker.io/v2/rancher/agent/blobs/tarsum.v1+sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 
DEBU[0073] https://registry-1.docker.io/v2/rancher/agent/blobs/tarsum.v1+sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 -- HEADERS: map[User-Agent:[docker/1.5.0-rc3 go/go1.4.1 git-commit/c02092d kernel/3.18.1-031801-generic os/linux arch/amd64]] 
DEBU[0073] hostDir: /etc/docker/certs.d/registry-1.docker.io 
DEBU[0079] rendered layer for 511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158 of [1024] size 
DEBU[0079] [registry] Calling "POST" https://registry-1.docker.io/v2/rancher/agent/blobs/uploads/ 
DEBU[0079] https://registry-1.docker.io/v2/rancher/agent/blobs/uploads/ -- HEADERS: map[User-Agent:[docker/1.5.0-rc3 go/go1.4.1 git-commit/c02092d kernel/3.18.1-031801-generic os/linux arch/amd64]] 
DEBU[0079] Using cached token for ibuildthecloud        
DEBU[0079] hostDir: /etc/docker/certs.d/registry-1.docker.io 
DEBU[0079] [registry] Calling "PUT"                     
DEBU[0079]  -- HEADERS: map[User-Agent:[docker/1.5.0-rc3 go/go1.4.1 git-commit/c02092d kernel/3.18.1-031801-generic os/linux arch/amd64]] 
DEBU[0079] Using cached token for ibuildthecloud        
Error pushing to registry: Put ?digest=tarsum.v1%2Bsha256%3Ae3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855: unsupported protocol scheme ""
INFO[0079] -job push(rancher/agent) = ERR (1)        
```

Now here's when it worked afterwards

```
DEBU[0451] Calling POST /images/{name:.*}/push          
INFO[0451] POST /v1.17/images/rancher/agent/push?tag=latest 
INFO[0451] +job push(rancher/agent)                     
INFO[0451] +job resolve_repository(rancher/agent)       
INFO[0451] -job resolve_repository(rancher/agent) = OK (0) 
DEBU[0451] pinging registry endpoint https://index.docker.io/v1/ 
DEBU[0451] attempting v1 ping for registry endpoint https://index.docker.io/v1/ 
DEBU[0451] pinging registry endpoint https://registry-1.docker.io/v2/ 
DEBU[0451] attempting v2 ping for registry endpoint https://registry-1.docker.io/v2/ 
DEBU[0451] hostDir: /etc/docker/certs.d/registry-1.docker.io 
INFO[0456] Unable to push to V2 registry, falling back to v1: invalid registry endpoint https://registry-1.docker.io/v2/: Get https://registry-1.docker.io/v2/: dial tcp: i/o timeout. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry registry-1.docker.io` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/registry-1.docker.io/ca.crt 
DEBU[0456] Local repo: map[v0.3.1-rc3:b3d5b7de09d2381e0ec1422d0a03acce64df2406ccd521f0cc11c9d4c22d9cd2 v0.3.1:3d409ba796f9b5d392bcfaa9fb497d5b4cabade335d702c5f565efba9bbc3beb v0.3.1-rc1:14b8f671a5df9bd20147eabdd420b44e7821dc6d6617319c915dae4f66a157bb v0.3.1-rc2:14b8f671a5df9bd20147eabdd420b44e7821dc6d6617319c915dae4f66a157bb v0.3.0:39ef1083a0be60d8f1dda758b743cd891bf12d1d60c3596cbccacc233f985cd8 v0.4.0:5d478726652a0b5705298d02e713ab0bd77fc345b4c4ca9f8225e54c528ca3b2 latest:3d409ba796f9b5d392bcfaa9fb497d5b4cabade335d702c5f565efba9bbc3beb v0.2.0:30110e1962c7db9f1169e47d6b25017934874a20ce3516a4731a354eeeaaef7a v0.2.1:7102021a406650986a338c510993a43cfbb2387fc7d1d537a3e79016bc378d1f] 
DEBU[0456] Image list: [511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158 3b363fd9d7dab4db9591058a3f43e806f6fa6f7e2744b63b2df4b84eadb0685a 607c5d1cca71dd3b6c04327c3903363079b72ab3e5e4289d74fb00a9ac7ec2aa f62feddc05dc67da9b725361f97d7ae72a32e355ce1585f9a60d090289120f73 8eaa4ff06b53ff7730c4d7a7e21b4426a4b46dee064ca2d5d90d757dc7ea040a 5c5646e3953bb7293e37cac68d25d573f3e735f2cbd9fbbd6feb77a2e636772c 98dfd1ccc4dac53c5dd240612d6eb2b4d1f64f374962509f524730f7d237e404 888b3207441e68648b4394ffef1ac8cb5bb9c9ac157b8af7a19bc8c50e09b618 0a0e24d58684e23f347500df581a7acfab8517ab1746bb763fac82d544fb6f2c 4a7c29b7d23300576a2b27e9803189183cc8ee584d1188277237cb0e1c7889cb 973a2707728b2b82013c43d62b0ce5819972ba05e9163e689b6602354f2b0450 8a04966acf35821d67a9292002e7baa8f49991a53af8720f4be3265265faa6be 2dc36ecf0b34e5cb56d8cedbe4321bb062c91c937066ee73478359871fedcda3 7582bf03bcddbef149adc65e1f9780d9e7fa86e5e44e34018cf564e063e32d21 a3bb0df279a21c0cc9d00bf7dd725395b0cd67190754591e6584e2a577c2195d eaa1056d426ad797b3cfdca9eb29108c833a6ce9a3130be23c6c54d5eaf6bfdc d7ce37176960e423eb276486e710bc36f871919d0754902bc3fcd6ee6fbf3c65 3d409ba796f9b5d392bcfaa9fb497d5b4cabade335d702c5f565efba9bbc3beb] 
DEBU[0456] Tags by image: map[3d409ba796f9b5d392bcfaa9fb497d5b4cabade335d702c5f565efba9bbc3beb:[latest]] 
DEBU[0456] Preparing to push map[v0.2.1:7102021a406650986a338c510993a43cfbb2387fc7d1d537a3e79016bc378d1f v0.3.0:39ef1083a0be60d8f1dda758b743cd891bf12d1d60c3596cbccacc233f985cd8 v0.4.0:5d478726652a0b5705298d02e713ab0bd77fc345b4c4ca9f8225e54c528ca3b2 latest:3d409ba796f9b5d392bcfaa9fb497d5b4cabade335d702c5f565efba9bbc3beb v0.2.0:30110e1962c7db9f1169e47d6b25017934874a20ce3516a4731a354eeeaaef7a v0.3.1-rc2:14b8f671a5df9bd20147eabdd420b44e7821dc6d6617319c915dae4f66a157bb v0.3.1-rc3:b3d5b7de09d2381e0ec1422d0a03acce64df2406ccd521f0cc11c9d4c22d9cd2 v0.3.1:3d409ba796f9b5d392bcfaa9fb497d5b4cabade335d702c5f565efba9bbc3beb v0.3.1-rc1:14b8f671a5df9bd20147eabdd420b44e7821dc6d6617319c915dae4f66a157bb] with the following images and tags 
DEBU[0456] Pushing ID: 511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158 with Tag:  
DEBU[0456] Pushing ID: 3b363fd9d7dab4db9591058a3f43e806f6fa6f7e2744b63b2df4b84eadb0685a with Tag:  
DEBU[0456] Pushing ID: 607c5d1cca71dd3b6c04327c3903363079b72ab3e5e4289d74fb00a9ac7ec2aa with Tag:  
DEBU[0456] Pushing ID: f62feddc05dc67da9b725361f97d7ae72a32e355ce1585f9a60d090289120f73 with Tag:  
DEBU[0456] Pushing ID: 8eaa4ff06b53ff7730c4d7a7e21b4426a4b46dee064ca2d5d90d757dc7ea040a with Tag:  
DEBU[0456] Pushing ID: 5c5646e3953bb7293e37cac68d25d573f3e735f2cbd9fbbd6feb77a2e636772c with Tag:  
DEBU[0456] Pushing ID: 98dfd1ccc4dac53c5dd240612d6eb2b4d1f64f374962509f524730f7d237e404 with Tag:  
DEBU[0456] Pushing ID: 888b3207441e68648b4394ffef1ac8cb5bb9c9ac157b8af7a19bc8c50e09b618 with Tag:  
DEBU[0456] Pushing ID: 0a0e24d58684e23f347500df581a7acfab8517ab1746bb763fac82d544fb6f2c with Tag:  
DEBU[0456] Pushing ID: 4a7c29b7d23300576a2b27e9803189183cc8ee584d1188277237cb0e1c7889cb with Tag:  
DEBU[0456] Pushing ID: 973a2707728b2b82013c43d62b0ce5819972ba05e9163e689b6602354f2b0450 with Tag:  
DEBU[0456] Pushing ID: 8a04966acf35821d67a9292002e7baa8f49991a53af8720f4be3265265faa6be with Tag:  
DEBU[0456] Pushing ID: 2dc36ecf0b34e5cb56d8cedbe4321bb062c91c937066ee73478359871fedcda3 with Tag:  
DEBU[0456] Pushing ID: 7582bf03bcddbef149adc65e1f9780d9e7fa86e5e44e34018cf564e063e32d21 with Tag:  
DEBU[0456] Pushing ID: a3bb0df279a21c0cc9d00bf7dd725395b0cd67190754591e6584e2a577c2195d with Tag:  
DEBU[0456] Pushing ID: eaa1056d426ad797b3cfdca9eb29108c833a6ce9a3130be23c6c54d5eaf6bfdc with Tag:  
DEBU[0456] Pushing ID: d7ce37176960e423eb276486e710bc36f871919d0754902bc3fcd6ee6fbf3c65 with Tag:  
DEBU[0456] Pushing ID: 3d409ba796f9b5d392bcfaa9fb497d5b4cabade335d702c5f565efba9bbc3beb with Tag: latest 
DEBU[0456] [registry] PUT https://index.docker.io/v1/repositories/rancher/agent/ 
DEBU[0456] Image list pushed to index:
[{"id":"511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158"},{"id":"3b363fd9d7dab4db9591058a3f43e806f6fa6f7e2744b63b2df4b84eadb0685a"},{"id":"607c5d1cca71dd3b6c04327c3903363079b72ab3e5e4289d74fb00a9ac7ec2aa"},{"id":"f62feddc05dc67da9b725361f97d7ae72a32e355ce1585f9a60d090289120f73"},{"id":"8eaa4ff06b53ff7730c4d7a7e21b4426a4b46dee064ca2d5d90d757dc7ea040a"},{"id":"5c5646e3953bb7293e37cac68d25d573f3e735f2cbd9fbbd6feb77a2e636772c"},{"id":"98dfd1ccc4dac53c5dd240612d6eb2b4d1f64f374962509f524730f7d237e404"},{"id":"888b3207441e68648b4394ffef1ac8cb5bb9c9ac157b8af7a19bc8c50e09b618"},{"id":"0a0e24d58684e23f347500df581a7acfab8517ab1746bb763fac82d544fb6f2c"},{"id":"4a7c29b7d23300576a2b27e9803189183cc8ee584d1188277237cb0e1c7889cb"},{"id":"973a2707728b2b82013c43d62b0ce5819972ba05e9163e689b6602354f2b0450"},{"id":"8a04966acf35821d67a9292002e7baa8f49991a53af8720f4be3265265faa6be"},{"id":"2dc36ecf0b34e5cb56d8cedbe4321bb062c91c937066ee73478359871fedcda3"},{"id":"7582bf03bcddbef149adc65e1f9780d9e7fa86e5e44e34018cf564e063e32d21"},{"id":"a3bb0df279a21c0cc9d00bf7dd725395b0cd67190754591e6584e2a577c2195d"},{"id":"eaa1056d426ad797b3cfdca9eb29108c833a6ce9a3130be23c6c54d5eaf6bfdc"},{"id":"d7ce37176960e423eb276486e710bc36f871919d0754902bc3fcd6ee6fbf3c65"},{"id":"3d409ba796f9b5d392bcfaa9fb497d5b4cabade335d702c5f565efba9bbc3beb","Tag":"latest"}] 
DEBU[0456] https://index.docker.io/v1/repositories/rancher/agent/ -- HEADERS: map[User-Agent:[docker/1.5.0-rc3 go/go1.4.1 git-commit/c02092d kernel/3.18.1-031801-generic os/linux arch/amd64]] 
DEBU[0456] hostDir: /etc/docker/certs.d/index.docker.io 
DEBU[0463] Auth token: [signature=f214b0d48219f7c24b71172b51abeadf94e865e4,repository="rancher/agent",access=write] 
DEBU[0463] https://cdn-registry-1.docker.io/v1/images/511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158/json -- HEADERS: map[User-Agent:[docker/1.5.0-rc3 go/go1.4.1 git-commit/c02092d kernel/3.18.1-031801-generic os/linux arch/amd64]] 
DEBU[0463] hostDir: /etc/docker/certs.d/cdn-registry-1.docker.io 
```

Some debug info...

```
$ docker version
Client version: 1.5.0-rc3
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): c02092d
OS/Arch (client): linux/amd64
Server version: 1.5.0-rc3
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): c02092d

$ docker info
Containers: 12
Images: 454
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 3.18.1-031801-generic
Operating System: Ubuntu 14.10
CPUs: 4
Total Memory: 7.496 GiB
Name: inotmac
ID: FPSO:Z7SO:BZJ3:IXH4:DNKV:UPZQ:KLP2:IRXW:5CBY:PBDM:HAKO:UOC7
Username: ibuildthecloud
Registry: [https://index.docker.io/v1/]
```

### PR DESCRIPTION
**Pull request by dmcgowan**
No longer push to the official v2 registry when it is available. This allows pulling images from the v2 registry without defaulting push.

Fixes #10557

### CODE REVIEW

**Comment by dmp42** [comment]
cc @jfrazelle @crosbymichael @icecrime 
This makes 1.5 behave in the same way as previous versions, like we discussed.

**Comment by dmcgowan** [comment]
Updated the logic to match exactly what we had in 1.3 and 1.4 for the official registry. This does not effect private v2 registries.

**Comment by jfrazelle** [comment]
cool thanks @dmcgowan

**Comment by crosbymichael** [comment]
looks sane so far ;)

**Comment by icecrime** [comment]
Just to give a more complete explanation of what's happening there (and hopefully checking in the process that my understanding is correct):

* Push against the official Hub will never use v2: this is the behavior we have with 1.4.1, where push is *always* v1 (be it against public Hub or a private registry).
* Pull against the official Hub of official images only (`repoInfo.Official`) will use v2: this is also the behavior we have in 1.4.1

So in this regard, patch sounds good: waiting on CI and testing locally.

**Comment by tianon** [comment]
I've applied this patch locally, but in pulling official images I'm seeing it hit v1.  Isn't that because the new v2 isn't where the official images live, and this v2 code is not using the old python-based v2 API anymore?

**Comment by jfrazelle** [comment]
I think they need to make adjustments in production. afaik?

**Comment by dmcgowan** [comment]
@tianon: @dmp42 is working on bringing these endpoints online right now.  Until then it will pull from v1

**Comment by dmp42** [comment]
On it.

**Comment by tianon** [comment]
```
time="2015-02-03T21:55:32-07:00" level="debug" msg="Calling POST /images/create" 
time="2015-02-03T21:55:32-07:00" level="info" msg="POST /v1.17/images/create?fromImage=debian%3Alatest" 
time="2015-02-03T21:55:32-07:00" level="info" msg="+job pull(debian, latest)" 
time="2015-02-03T21:55:32-07:00" level="info" msg="+job resolve_repository(debian)" 
time="2015-02-03T21:55:32-07:00" level="info" msg="-job resolve_repository(debian) = OK (0)" 
time="2015-02-03T21:55:32-07:00" level="debug" msg="pulling image from host \"docker.io\" with remote name \"library/debian\"" 
time="2015-02-03T21:55:32-07:00" level="debug" msg="pinging registry endpoint https://index.docker.io/v1/" 
time="2015-02-03T21:55:32-07:00" level="debug" msg="attempting v1 ping for registry endpoint https://index.docker.io/v1/" 
time="2015-02-03T21:55:32-07:00" level="info" msg="+job trust_update_base()" 
time="2015-02-03T21:55:32-07:00" level="debug" msg="Fetched 1 base graphs at 2015-02-03 21:55:32.538292526 -0700 MST" 
time="2015-02-03T21:55:32-07:00" level="info" msg="-job trust_update_base() = OK (0)" 
time="2015-02-03T21:55:32-07:00" level="debug" msg="pulling v2 repository with local name \"debian\"" 
time="2015-02-03T21:55:32-07:00" level="debug" msg="pinging registry endpoint https://registry-1.docker.io/v2/" 
time="2015-02-03T21:55:32-07:00" level="debug" msg="attempting v2 ping for registry endpoint https://registry-1.docker.io/v2/" 
time="2015-02-03T21:55:32-07:00" level="debug" msg="hostDir: /etc/docker/certs.d/registry-1.docker.io" 
time="2015-02-03T21:55:32-07:00" level="debug" msg="Reloaded graph with 2 grants expiring at 2015-02-22 22:47:54.722420237 +0000 UTC" 
time="2015-02-03T21:55:33-07:00" level="debug" msg="Getting authorization for library/debian [pull]" 
time="2015-02-03T21:55:33-07:00" level="debug" msg="Pulling tag from V2 registry: \"latest\"" 
time="2015-02-03T21:55:33-07:00" level="debug" msg="[registry] Calling \"GET\" https://registry-1.docker.io/v2/library/debian/manifests/latest" 
time="2015-02-03T21:55:33-07:00" level="debug" msg="https://registry-1.docker.io/v2/library/debian/manifests/latest -- HEADERS: map[User-Agent:[docker/1.4.1-dev go/go1.4.1 git-commit/165ea5c-dirty kernel/3.16.5-gentoo os/linux arch/amd64]]" 
time="2015-02-03T21:55:33-07:00" level="debug" msg="hostDir: /etc/docker/certs.d/registry-1.docker.io" 
time="2015-02-03T21:55:33-07:00" level="info" msg="+job trust_key_check(/library/debian)" 
time="2015-02-03T21:55:33-07:00" level="info" msg="-job trust_key_check(/library/debian) = OK (0)" 
time="2015-02-03T21:55:33-07:00" level="debug" msg="Key check result: \"verified\"" 
time="2015-02-03T21:55:33-07:00" level="info" msg="Image manifest for debian:latest has been verified" 
time="2015-02-03T21:55:33-07:00" level="debug" msg="Image already exists: 511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158" 
time="2015-02-03T21:55:33-07:00" level="debug" msg="Image already exists: 30d39e59ffe287f29a41a3f8bd70734afc8728329e3289945cbdc5bbf07cd980" 
time="2015-02-03T21:55:33-07:00" level="debug" msg="Image already exists: c90d655b99b2ec5b7e94d38c87f92dce015c17a313caeaae0e980d9b9bed8444" 
time="2015-02-03T21:55:33-07:00" level="info" msg="+job log(pull, debian:latest, )" 
time="2015-02-03T21:55:33-07:00" level="info" msg="-job log(pull, debian:latest, ) = OK (0)" 
time="2015-02-03T21:55:33-07:00" level="info" msg="-job pull(debian, latest) = OK (0)" 
```

Looks like v2's getting hit on my machine running with this patch now. :+1:

I would also add that `docker pull -a debian` still appears to be working correctly now that we're hitting v2, so that's also a good sign. :signal_strength:

**Comment by crosbymichael** [comment]
Just downloaded an official image and received this:

`debian:jessie: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.`

I guess that is a good sign.

**Comment by icecrime** [comment]
Same here, pulling official images look good:

Daemon:
```
DEBU[0010] Pulling tag from V2 registry: "latest"
DEBU[0010] [registry] Calling "GET" https://registry-1.docker.io/v2/library/busybox/manifests/latest
DEBU[0010] https://registry-1.docker.io/v2/library/busybox/manifests/latest -- HEADERS: map[User-Agent:[docker/1.4.1-dev go/go1.4.1 git-commit/22e2254 kernel/3.13.0-24-generic os/linux arch/amd64]]
```

Client:
```
busybox:latest: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
```

Does it mean that official images have already been rebuilt with the new TarSum version?

**Comment by icecrime** [comment]
Pushing looks suspicious:

* It seems to be pushing using v2 endpoints
* I haven't logged in yet, but the message in unrelated

```
DEBU[0301] [registry] Calling "POST" https://registry-1.docker.io/v2/icecrimedev/busybox/blobs/uploads/
DEBU[0301] https://registry-1.docker.io/v2/icecrimedev/busybox/blobs/uploads/ -- HEADERS: map[User-Agent:[docker/1.4.1-dev go/go1.4.1 git-commit/22e2254 kernel/3.13.0-24-generic os/linux arch/amd64]]
DEBU[0301] Using cached token for
DEBU[0301] hostDir: /etc/docker/certs.d/registry-1.docker.io
DEBU[0301] [registry] Calling "PUT"
DEBU[0301]  -- HEADERS: map[User-Agent:[docker/1.4.1-dev go/go1.4.1 git-commit/22e2254 kernel/3.13.0-24-generic os/linux arch/amd64]]
DEBU[0301] Using cached token for
Error pushing to registry: Put ?digest=tarsum.v1%2Bsha256%3Ae3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855: unsupported protocol scheme ""
```

**Comment by tiborvass** [comment]
@icecrime Looks like #10557 is the same issue but it's with rc3

**Comment by icecrime** [comment]
I guess something server-side must be replying positively to a `/v2/` ping request or we wouldn't be seeing pushes go over v2.

**Comment by dmcgowan** [comment]
@icecrime yes,RC3 will attempt a v2 push now that the v2 endpoint is responding but only accepting pulls. You are not seeing that with this PR though right?

**Comment by icecrime** [comment]
@dmcgowan Yes my test is with that PR. I think @tiborvass just confirmed that the Hub infra does reply to a /v2/ ping, which makes it eligible for a v2 push as far as I understand.

**Comment by dmcgowan** [comment]
Understood that /v2/ accepts a ping which turns on push, but with this PR it should not push to the official registry even with the /v2/ endpoint online.  How are you doing the push, I am not seeing the attempted push with this change.

**Comment by icecrime** [comment]
Sorry then, let me double check but I really think I had this PR compiled. However, reading through the code, I don't see where we prevent pushes to the Hub with v2: we create a session (hence doing the ping), and then: 

    if endpoint.Version == registry.APIVersion2 {

**Comment by dmcgowan** [comment]
@icecrime the endpoint in this case is actually index.docker.com which is itself only a v1 registry. When we were using the official registry we overwrote the endpoint with the v2 registry endpoint at registry-1.docker.com/v2/. We are going to refactor this code but right now the underlying code has no concept of separate domain endpoints for v1/v2.

**Comment by icecrime** [comment]
Ok I'm very sorry I must have got something wrong in my test yesterday, I rebuilt the PR and it's behaving as expected. LGTM.

File: graph/pull.go [hunk 1]
```diff
@@ -72,7 +72,7 @@ func (s *TagStore) CmdPull(job *engine.Job) engine.Status {
 		logName += ":" + tag
 	}
 
-	if len(repoInfo.Index.Mirrors) == 0 && (repoInfo.Index.Official || endpoint.Version == registry.APIVersion2) {
+	if len(repoInfo.Index.Mirrors) == 0 && ((repoInfo.Index.Official && repoInfo.Official) || endpoint.Version == registry.APIVersion2) {
```
Comment (tiborvass) [inline graph/pull.go]: @dmcgowan i would put the `repoInfo.Official` first, since that case is rarer.

**Comment by tiborvass** [comment]
Apart from small nit, LGTM

**Comment by dmcgowan** [comment]
@tiborvass fixed nit

**Comment by LK4D4** [comment]
LGTM
