### PR TITLE
return error when listNode fails

### LINKED ISSUE #29520: improper display in `docker info` when manager is out of quorum
**Description**

I ran into a situation which is described is https://github.com/docker/docker/issues/29367.
When I have only 3 nodes in swarm and all of them are manager. When I make a leader manager and a non-leader manager leave. Then something unreasonable happens on the only left manager.

Here is the display of `docker info` of left manager:
```
root@ubuntu:/var/lib/docker/network/files# docker info
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 15
Server Version: 1.12.5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 57
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: pending
 NodeID: 7byj8y4wchovhesfd4ep2r4sr
 Error: rpc error: code = 2 desc = raft: no elected cluster leader     // here has an error of swarm
 Is Manager: true                                      // here told user that this is a manager
 ClusterID:
 Managers: 0                                            // here told user that there is no managers, inconsistent with above
 Nodes: 0
 Orchestration:
  Task History Retention Limit: 0
 Raft:
  Snapshot Interval: 0
  Heartbeat Tick: 0
  Election Tick: 0
 Dispatcher:
  Heartbeat Period: Less than a second    // this is not proper to display like less than a second
 CA Configuration:
  Expiry Duration: Less than a second
 Node Address: 10.1.4.210
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: ubuntu
ID: G5Y6:4CA7:F7ES:NLYP:2CVE:RQPT:S3NS:QDV3:GEQX:R5DX:N5O2:Y4V2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 72
 System Time: 2016-12-19T13:12:47.432985459+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
root@ubuntu:/var/lib/docker/network/files# docker version
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:30:42 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:30:42 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
root@ubuntu:/var/lib/docker/network/files# docker info
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 15
Server Version: 1.12.5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 57
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: pending
 NodeID: 7byj8y4wchovhesfd4ep2r4sr
 Error: rpc error: code = 2 desc = raft: no elected cluster leader
 Is Manager: true
 ClusterID:
 Managers: 0
 Nodes: 0
 Orchestration:
  Task History Retention Limit: 0
 Raft:
  Snapshot Interval: 0
  Heartbeat Tick: 0
  Election Tick: 0
 Dispatcher:
  Heartbeat Period: Less than a second
 CA Configuration:
  Expiry Duration: Less than a second
 Node Address: 10.1.4.210
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: ubuntu
ID: G5Y6:4CA7:F7ES:NLYP:2CVE:RQPT:S3NS:QDV3:GEQX:R5DX:N5O2:Y4V2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 24
 Goroutines: 76
 System Time: 2016-12-19T13:24:41.688636419+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by allencloud**
Signed-off-by: allencloud <allen.sun@daocloud.io>

fixes #29520 

**- What I did**
1. When `c.Inspect()` and `ListNodes` fail, we set the error to Info;
2. change the client side that make swarm error stop displaying cluster info.
3. add check `LocalNodeStateError` in client side.

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by tonistiigi** [comment]
Not sure about the `ControlAvailable` change. Not only does it have a secondary meaning for detecting if a node is a manager, you could argue that the control API is actually available. Just that last time we made a request it errored. If a user sends any swarm commands we will still send them directly to Swarm API to be handled there.

I'd rather include the error state check in https://github.com/docker/docker/blob/master/cli/command/system/info.go#L106

**Comment by allencloud** [comment]
@tonistiigi Thanks for your explanation for `ControlAvailable`. Now updated within this PR.

While with changing code in client side, I found that the result shows like this:
```
Swarm: active
 NodeID: x0wvh4c67k3cqbrzl7h8w5txi
 Error: rpc error: code = 4 desc = context deadline exceeded
 Is Manager: true
 Node Address: 192.168.59.103
 Manager Addresses:
  0.0.0.0:2377
  192.168.59.103:2377
  192.168.59.104:2377
  192.168.59.105:2377
```

With no other field related to cluster info. And `0.0.0.0:2377` still makes me feel confused.

**Comment by tonistiigi** [comment]
@allencloud That looks like a possible unrelated bug. What are the steps to reproduce it? I'd assume it comes from https://github.com/docker/swarmkit/blob/master/node/node.go#L695-L699 (cc @aaronlehmann)

File: cli/command/system/info.go [hunk 1]
```diff
@@ -103,7 +103,7 @@ func prettyPrintInfo(dockerCli *command.DockerCli, info types.Info) error {
 			fmt.Fprintf(dockerCli.Out(), " Error: %v\n", info.Swarm.Error)
 		}
 		fmt.Fprintf(dockerCli.Out(), " Is Manager: %v\n", info.Swarm.ControlAvailable)
-		if info.Swarm.ControlAvailable {
+		if info.Swarm.ControlAvailable && info.Swarm.Error == "" {
```
Comment (tonistiigi) [inline cli/command/system/info.go]: I think client should be able to check with `state==LocalNodeStateError`

**Comment by aaronlehmann** [comment]
> @allencloud That looks like a possible unrelated bug. What are the steps to reproduce it? I'd assume it comes from https://github.com/docker/swarmkit/blob/master/node/node.go#L695-L699 (cc @aaronlehmann)

Note that this code is removed in https://github.com/docker/swarmkit/pull/1826

**Comment by allencloud** [comment]
> What are the steps to reproduce it?

When Swarm has only 3 managers, we can not reproduce this issue if we leave 2 non-leader managers. Only if we make one leader and one non-leader manager leave could I reproduce this issue.

this is described in issue https://github.com/docker/docker/issues/29367

File: cli/command/system/info.go (hunk 1 above)
Comment (allencloud) [inline cli/command/system/info.go]: Thanks, that is reasonable, updated within this PR: if LocalNodeStateError, do not display more swarm info. PTAL.

**Comment by allencloud** [comment]
Updated with checking `info.Swarm.LocalNodeState != swarm.LocalNodeStateError` in client side. Could you help to review this? @tonistiigi

File: cli/command/system/info.go (hunk 1 above)
Comment (tonistiigi) [inline cli/command/system/info.go]: We should still show the nodeid/error/ismanager part on error state.

Comment (allencloud) [inline cli/command/system/info.go]: Thanks a lot for your feedback @tonistiigi 
Updated now, PTAL 🐼

**Comment by tonistiigi** [comment]
LGTM
