### PR TITLE
skip solaris and allow dry run control points

### LINKED ISSUE #28326: adjust release.sh for solaris
**Description**

The [release.sh](https://github.com/docker/docker/blob/e6866492c4492db3bb9546afa2fbaed20f4c1883/hack/release.sh#L217) script used during docker's release process is failing because it cannot handle solaris builds.

**Steps to reproduce the issue:**
```
$ docker run ... docker-dev:1-13-x hack/release.sh
...
error: can't convert solaris to an appropriate value for 'uname -s'
```

**Describe the results you received:**

Most of the binaries uploaded to s3 except for solaris and windows.

**Describe the results you expected:**

Stuff to work.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

something recent

**Output of `docker info`:**

stuff

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by andrewhsu**
**- What I did**

Modified `hack/release.sh` so that it would skip over releasing solaris binaries; fixes #28326.

**- How I did it**

Added `case` statement for `solaris`. Also changed call to `aws` cli to use env variable `AWS_CLI` with default value of `aws` so that a dry-run of the script can be performed.

In addition: to skip over rebuilding the binaries again for a dry-run test, added a `SKIP_RELEASE_BUILD` env variable. When set to `1` will skip the part of rebuilding binaries. This made the script easier to verify and to re-run during deployment in case something goes wrong and it has to be re-run again.

**- How to verify it**
```
$ docker run -i -t --privileged \
  -e SKIP_RELEASE_BUILD=1 -e AWS_CLI='echo aws' \
  -e AWS_S3_BUCKET=test.docker.com -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY \
  -v `pwd`/bundles:/go/src/github.com/docker/docker/bundles \
  docker-dev:fix-release-sh hack/release.sh --release-regardless-of-test-failure
...
Releasing binaries
skipping solaris release
Releasing binaries
...
```
**- Description for the changelog**

N/A

**- A picture of a cute animal (not mandatory but encouraged)**

🎣 

Signed-off-by: Andrew Hsu <andrewhsu@docker.com>

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:
/cc @tiborvass @vieux

**Comment by thaJeztah** [comment]
sgtm

**Comment by vieux** [comment]
LGTM

File: hack/release.sh [hunk 1]
```diff
@@ -297,7 +303,7 @@ release_index() {
 }
 
 main() {
-	build_all
+	[ "$SKIP_RELEASE_BUILD" -eq 1 ] || build_all
```
Comment (tiborvass) [inline hack/release.sh]: @andrewhsu out of curiosity where is this env set? is it just a knob to be able to push without rebuilding?

Comment (andrewhsu) [inline hack/release.sh]: yup, just for human to skip the building phase if needed
