### PR TITLE
Revert environment regexp in opts

### LINKED ISSUE #16585: Docker 1.8 - no longer able to pass Spring config settings in env-file
## Problem Description
After upgrading from Docker 1.7.1 to 1.8 I'm unable to pass environment variables with "." or "-" via env-file.  Most of our app is based on Spring and is built to use Spring "style" config settings (e.g. "messaging.rmq.broker.url").

Passing the same collection of settings on the command line via "-e" still works as before.

## Actual results
Error message from Docker when parsing the env-file

## Expected results
Able to pass in app settings via env-file.

## Steps to reproduce the problem
1. Create env-file "repro.list" with the following config settings (any Spring "style" config):
```
  messaging.rmq.broker.url=localhost
  messaging.rmq.broker.username=guest
  messaging.rmq.broker.password=guest
  messaging.rmq.broker.virtualhost=reprohost
```
  
2. Run any image, passing this file
  docker run --env-file=repro.list hello-world
  
3. Observe error "docker: poorly formatted environment: variable 'messaging.rmq.broker.url' is not a valid environment variable."

### docker version:  
Docker version 1.8.1, build d12ea79

### docker info:
Containers: 0
Images: 75
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 75
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.1 (TCL 6.3); master : 7f12e95 - Thu Aug 13 03:24:56 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: riclaw
ID: SQYV:M5J4:4RAR:6DKG:4IVN:J4RB:H3AN:FRBT:N635:WVZF:OW67:O2SR
Debug mode (server): true
File Descriptors: 11
Goroutines: 19
System Time: 2015-09-24T23:41:00.367346747Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

### uname -a:
Darwin belclar1114.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64

### Provide additional environment details (AWS, VirtualBox, physical, etc.):
Mac running w/ Docker Toolbox

----------END REPORT ---------

### PR DESCRIPTION
**Pull request by vdemeester**
Remove the environment regexp introduced in #13694 as it makes some application not working anymore.

As said in #16585

> Environment variable names used by the utilities in the Shell and Utilities volume of IEEE Std 1003.1-2001 consist solely of uppercase letters, digits, and the '_' (underscore) from the characters defined in Portable Character Set and do not begin with a digit. **Other characters may be permitted by an implementation; applications shall tolerate the presence of such names**. Uppercase and lowercase letters shall retain their unique identities and shall not be folded together. The name space of environment variable names containing lowercase letters is reserved for applications.

Even if I was liking this, as @tianon said, docker should be tolerant on the environment passed as is — _separation of concern_, it's up to the application to handle this or not :sweat_smile:.

The only question I have on that one is the fact that `ParseEnvFile` behave differently from `ValidateEnv` as it checks from white spaces where the other don't. What should we do there ?

Fixes #16585

Signed-off-by: Vincent Demeester vincent@sbr.pm

### CODE REVIEW

File: opts/envfile.go [hunk 1]
```diff
@@ -31,11 +23,13 @@ func ParseEnvFile(filename string) ([]string, error) {
 		// line is not empty, and not starting with '#'
 		if len(line) > 0 && !strings.HasPrefix(line, "#") {
 			data := strings.SplitN(line, "=", 2)
-			variable := data[0]
 
-			if !EnvironmentVariableRegexp.MatchString(variable) {
-				return []string{}, ErrBadEnvVariable{fmt.Sprintf("variable '%s' is not a valid environment variable", variable)}
+			// trim the front of a variable, but nothing else
```
Comment (thaJeztah) [inline opts/envfile.go]: Perhaps you should add some of the discussion in this PR (and the linked issue) in a comment (and in the commit message) to explain *why* we're not validating that the characters are valid for environment vars. (also to prevent someone to re-introduce the regex in future)

Comment (vdemeester) [inline opts/envfile.go]: @thaJeztah true :stuck_out_tongue_closed_eyes:

Comment (vdemeester) [inline opts/envfile.go]: and done :)

File: opts/envfile.go [hunk 2]
```diff
@@ -31,11 +35,13 @@ func ParseEnvFile(filename string) ([]string, error) {
...
+			variable := strings.TrimLeft(data[0], whiteSpaces)
+			if strings.ContainsAny(variable, whiteSpaces) {
+				return []string{}, ErrBadEnvVariable{fmt.Sprintf("variable '%s' has white spaces", variable)}
```
Comment (phemmer) [inline opts/envfile.go]: why trim whitespace? It's technically allowed to have an env var with leading whitespace.

Comment (vdemeester) [inline opts/envfile.go]: @phemmer it's how it was done before the regexp so I reverted to it. But yeah.. and in ValidateEnv we do not trim leading space so.. there is something to do.. (probably removing this trim)

Comment (calavera) [inline opts/envfile.go]: let's leave this here. I'd rather have the previous behavior, that seemed to work as expected, than a new different behavior.

**Comment by calavera** [comment]
@vdemeester can we add a couple new regression tests to `opts/envfile_test.go` with special characters, like `.` and `_` to make sure this doesn't break again?

**Comment by vdemeester** [comment]
@calavera yes, will do :wink:.

**Comment by vdemeester** [comment]
@calavera done :wink:

**Comment by calavera** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM
