### PR TITLE
--rm delete container when create failed

### LINKED ISSUE #6757: Container started with --rm isn't removed after start failure
First invocation:

```
docker run --rm --name=example --link b0rk:b0rk ubuntu
2014/06/29 11:14:22 Error: Could not find entity for b0rk
```

Second invocation:

```
$ docker run --rm --name=example --link b0rk:b0rk ubuntu
2014/06/29 11:14:50 Error: Conflict, The name example is already assigned to 7e0e4f5268a8. You have to delete (or rename) that container to be able to assign example to a container again.
```

This hit me with surprise. I expected the first run to leave no garbage because of `--rm`. If this is the desired behaviour it should be documented on https://docs.docker.com/reference/run/.

This should also be handed on the daemon side not client side.

### LINKED ISSUE #12444: `docker run -d --link` behaviour issue
My script is running a bunch of commands like `id=$(docker run -d --link foo:bar busybox sleep 10000)`. A cleanup step is run at the end to remove all the containers like `docker rm -f $id`.

If the linked container doesn't exist or is not running docker will return with exit status 1 and the following message:
```
FATA[0000] Error response from daemon: Could not get container for foo
```

The container is still created, but since the ID is not returned my cleanup phase is not able to remove the container.

```
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
4d2f61f8cab1        busybox:latest      "sleep 10000"       39 seconds ago                                              lonely_einstein
```

`docker version`:

```
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): darwin/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

`docker info`:

```
Containers: 2
Images: 4
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 8
Execution Driver: native-0.2
Kernel Version: 3.18.5-tinycore64
Operating System: Boot2Docker 1.5.0 (TCL 5.4); master : a66bce5 - Tue Feb 10 23:31:27 UTC 2015
CPUs: 4
Total Memory: 1.961 GiB
Name: boot2docker
ID: DFQ4:XNJP:PMC4:7K5E:Q7CL:HCDH:2DD4:YK6M:OYYG:QLN5:ADZ5:YGZF
Debug mode (server): true
Debug mode (client): false
Fds: 11
Goroutines: 16
EventsListeners: 0
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
```

`uname -a`:

```
Darwin Voodoo-Lady.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
```

Environment details (AWS, VirtualBox, physical, etc.): OSX + Boot2docker

How reproducible: always

Steps to Reproduce:
1. docker run -d --link foo:bar busybox sleep 10000
2. docker ps -a

Actual Results: the container is created

Expected Results: the container is not created, similarly to `docker run -d --rm busybox sleep 10000`

### PR DESCRIPTION
**Pull request by azurezk**
Signed-off-by: Zhang Kun zkazure@gmail.com

fixes #12444 
fixes #6757
When daemon.newContainer(name, config, imgID) success, return the container instead of nil so client can deleted it  if following creating procedure failed

If following container creating procedure failed, the container id will add in the error info.

### CODE REVIEW

**Comment by calavera** [comment]
I'd rather return a proper json with the container id than adding the id to the error, tbh.

**Comment by azurezk** [comment]
Hi , @calavera , If server return a proper json, the http status would be 200?  How to distinguish a successful return and a create failure?

**Comment by jfrazelle** [comment]
Do we really need this? can you explain a use case. I understand --rm on run but kinda weird on create tbh

**Comment by icecrime** [comment]
This fixes a seemingly legitimate bug, but I agree the solution is not appropriate, if only because every API clients to do the same string manipulation to extract the container ID. Also, you can return a JSON with a non 200 status.

**Comment by tonistiigi** [comment]
We should evaluate if this could be solved in the daemon side. If I understand this correctly then `POST /containers/create` returns error  but container is still created. I think this shouldn't happen and if error in create code happens after container already exists server should just clean up after itself.

**Comment by azurezk** [comment]
@tonistiigi, solved in the daemon side means clean up when create failure no mater there is a --rm flag or not?

**Comment by tonistiigi** [comment]
@azurezk yes, IMHO if the container creation failed it shouldn't have side effects

**Comment by azurezk** [comment]
OK, trying to do this

**Comment by azurezk** [comment]
have fixed in daemon side, please review :)  @tonistiigi

**Comment by azurezk** [comment]
@jfrazelle, I think if a container is created failed, it is expected that it doesn't exist and you can create another container with the same name. But it will cause conflict if not cleaned up. #6757 and #12444  have discuss this

**Comment by tonistiigi** [comment]
I think we don't need a separate `Cleanup` function, partly because `daemon.Cleanup` should probably do something else. Calling just `daemon.rm()` should be enough there.

We should try to catch the other errors as well. You could use the following pattern after container is created(watch out to use single err variable though). 

```
defer func() {
  if err != nil  {
    daemon.rm()
  }
}
```

This needs integration tests.

**Comment by azurezk** [comment]
have updated

**Comment by tonistiigi** [comment]
@azurezk   This shouldn't work (and doesn't work for me) because the later errors are scoped and have their own error variable. We need to only have a single err variable to make this work. This also needs `integration-cli` tests because it's kind of tricky.

**Comment by calavera** [comment]
> We need to only have a single err variable to make this work.

try this trick, you don't really need a single err variable in the method:

```go
func (daemon *Daemon) Create(config *runconfig.Config, hostConfig *runconfig.HostConfig, name string) (c *Container, s []string, retError error) {
    defer func() {
      if retError != nil  {
        daemon.rm()
      }
    }
}
```

The returning error is always associated with the named `retError` in the method definition.

**Comment by calavera** [comment]
look at this example in the go playground: https://play.golang.org/p/SqSA-ChGOp

**Comment by azurezk** [comment]
Thanks for help!  :) @calavera , @tonistiigi , integration-cli has passed

**Comment by tonistiigi** [comment]
@azurezk Great. This looks good now but we need to add a new `integration-cli` test that makes a failed create call and tests that the container was cleaned up properly before we can merge. Let us know if you need help with that or if you want us to take over and make the test for you.

**Comment by calavera** [comment]
Indeed, this change needs new integration tests.

**Comment by azurezk** [comment]
I add a test to make it failed at "daemon.setHostConfig(container, hostConfig)", but there are many other processes I don't know how to make them failed. Please help or feel free to take over. @tonistiigi  @calavera

File: integration-cli/docker_cli_run_test.go [hunk 1]
```diff
@@ -2816,3 +2816,21 @@ func (s *DockerSuite) TestRunCapAddSYSTIME(c *check.C) {
 
 	dockerCmd(c, "run", "--cap-drop=ALL", "--cap-add=SYS_TIME", "busybox", "sh", "-c", "grep ^CapEff /proc/self/status | sed 's/^CapEff:\t//' | grep ^0000000002000000$")
 }
+
+// run create container failed should remove container
+func (s *DockerSuite) TestRunCreateContainerFaliedCleanUp(c *check.C) {
```
Comment (tonistiigi) [inline integration-cli/docker_cli_run_test.go]: s/Falied/Failed/

File: daemon/create.go [hunk 2]
```diff
@@ -75,6 +75,12 @@ func (daemon *Daemon) Create(config *runconfig.Config, hostConfig *runconfig.Hos
 	if container, err = daemon.newContainer(name, config, imgID); err != nil {
 		return nil, nil, err
 	}
+	defer func() {
+		if retErr != nil {
+			daemon.rm(container, false)
```
Comment (tonistiigi) [inline daemon/create.go]: I think we could log out if `rm()` returns an error here.

**Comment by tonistiigi** [comment]
@azurezk Don't worry about the other cases if they aren't really reproducible from client. Its important to test the invalid link thing that users are hitting.

Small comments, overall looks good to me.

File: integration-cli/docker_cli_run_test.go [hunk 3]
```diff
@@ -2816,3 +2816,21 @@ func (s *DockerSuite) TestRunCapAddSYSTIME(c *check.C) {
...
+	name := "flowers"
+	out, _, err := dockerCmdWithError("run", "--name", name, "--link", "nothing:nothing", "busybox")
+	if err == nil {
+		c.Fatal("Expected docker run to fail", out, err)
+	}
+
+	out, err = getAllContainers()
+	if err != nil {
```
Comment (cpuguy83) [inline integration-cli/docker_cli_run_test.go]: `c.Assert(err, check.IsNil, check.Commentf(out))`

File: integration-cli/docker_cli_run_test.go [hunk 4]
```diff
@@ -2816,3 +2816,21 @@ func (s *DockerSuite) TestRunCapAddSYSTIME(c *check.C) {
 
 	dockerCmd(c, "run", "--cap-drop=ALL", "--cap-add=SYS_TIME", "busybox", "sh", "-c", "grep ^CapEff /proc/self/status | sed 's/^CapEff:\t//' | grep ^0000000002000000$")
 }
+
+// run create container failed should remove container
+func (s *DockerSuite) TestRunCreateContainerFaliedCleanUp(c *check.C) {
+	name := "flowers"
+	out, _, err := dockerCmdWithError("run", "--name", name, "--link", "nothing:nothing", "busybox")
+	if err == nil {
```
Comment (cpuguy83) [inline integration-cli/docker_cli_run_test.go]: c.Assert(err, check.Not(check.IsNil))

File: integration-cli/docker_cli_run_test.go [hunk 5]
```diff
@@ -2816,3 +2816,21 @@ func (s *DockerSuite) TestRunCapAddSYSTIME(c *check.C) {
...
+		c.Fatal("Expected docker run to fail", out, err)
+	}
+
+	out, err = getAllContainers()
+	if err != nil {
+		c.Fatal(out, err)
+	}
+
+	if out != "" {
```
Comment (cpuguy83) [inline integration-cli/docker_cli_run_test.go]: c.Assert(out, check.Equals, "")

But also it may be better to instead just call `inspect

File: daemon/create.go [hunk 6]
```diff
@@ -40,7 +40,7 @@ func (daemon *Daemon) ContainerCreate(name string, config *runconfig.Config, hos
 }
 
 // Create creates a new container from the given configuration with a given name.
-func (daemon *Daemon) Create(config *runconfig.Config, hostConfig *runconfig.HostConfig, name string) (*Container, []string, error) {
+func (daemon *Daemon) Create(config *runconfig.Config, hostConfig *runconfig.HostConfig, name string) (retC *Container, retS []string, retErr error) {
```
Comment (cpuguy83) [inline daemon/create.go]: Can we not use a named return and instead initialize `err` for the defer to use?

Comment (calavera) [inline daemon/create.go]: we're using names returns to capture the error in the defer. I rather do that than trying to make sure the err in the defer is the correct one, this method is rather big for that.

Comment (cpuguy83) [inline daemon/create.go]: ok, works for me.

**Comment by azurezk** [comment]
have updated :)  add daemon rm() error handle @tonistiigi  and inspect the container in test @cpuguy83

**Comment by tonistiigi** [comment]
LGTM

**Comment by cpuguy83** [comment]
Looking at this again... shouldn't this be handled on the client since `--rm` is a client-side feature?

**Comment by tonistiigi** [comment]
@cpuguy83 This doesn't actually have anything to do with `--rm` (although the original issue describes it like that). When the request to `/containers/create` errors there shouldn't be container left behind. Whether you used `--rm` on client side or not does not change that.

**Comment by cpuguy83** [comment]
OK, I see.

LGTM.
