### PR TITLE
daemon/logger: read the length header correctly

### LINKED ISSUE #42125: OOM when following "local" logs of high-log-output container
**Description**

When logging to the `local` driver, Docker will quickly run out of memory when following the logs of a container with a lot of log output.

This also occurs when following local logs while using a driver such as `syslog` that supports dual logging.

This issue appears to be similar or identical to #39963.

**Steps to reproduce the issue:**
1. Run a container that logs heavily to the `local` driver:

    ```
    ID=$(docker run --rm -d --log-driver local alpine cat /dev/urandom)
    ```
2. Follow the container's logs:

    ```
    docker logs -f $ID > /dev/null
    ```

Alternatively:

1. Run a container that logs heavily to a driver that supports dual logging:

    ```
    ID=$(docker run --rm -d --log-driver syslog --log-opt syslog-address=udp://127.0.0.1:0 alpine cat /dev/urandom)
    ```
2. Follow the container's logs:

    ```
    docker logs -f $ID > /dev/null
    ```

**Describe the results you received:**
`dockerd` exits with `fatal error: runtime: out of memory`.

Stack trace: https://gist.github.com/2f674f1ff24c679ba4778f458facb7b2

**Describe the results you expected:**
Docker remains stable and keeps a reasonable memory footprint.

**Additional information you deem important (e.g. issue happens only occasionally):**
I have been unable to reproduce the issue when logging to the `json-file` driver.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:18:20 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:16:15 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: local
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-54-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 981.1MiB
 Name: ubuntu-focal
 ID: 5X6F:5OLY:MQHX:I5T3:AVJQ:AMIX:5OBO:XI4L:CI62:LRA7:INKW:26IT
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 30
  Goroutines: 40
  System Time: 2021-03-08T20:11:15.100104538Z
  EventsListeners: 0
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This was initially observed in a [Nomad](https://www.nomadproject.io/) environment. Nomad follows logs by default for Docker tasks. The host was a lightly loaded AWS `m5.xlarge` instance.

I have reproduced it on Ubuntu 16.04 and 20.04 using Virtualbox VMs, and on Docker for Mac 3.1.0 (20.10.2).

### PR DESCRIPTION
**Pull request by kzys**
Before this change, if Decode() couldn't read a log record fully,
the subsequent invocation of Decode() would read the record's non-header part
as a header and cause a huge heap allocation.

This change prevents such a case by having the intermediate buffer in
the decoder struct.

Fixes #42125.

Signed-off-by: Kazuyoshi Kato <katokazu@amazon.com>

**- What I did**

Changing decoder struct to fix #42125.

**- How I did it**

Changing decoder struct to keep read-but-unused bytes.

**- How to verify it**

Run `docker logs -f $(docker run --rm -d --log-driver local alpine cat /dev/urandom) > /dev/null`. It kills dockerd after a few minutes before the change.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

Havam

(from https://www.zooborns.com/zooborns/2021/05/two-very-different-babies-emerge-at-woodland-park-zoo.html)

### CODE REVIEW

**Comment by kzys** [comment]
Some tests on Windows are failing. Not really sure it is related to my change.

```
[2021-11-22T17:57:41.327Z] === Failed
[2021-11-22T17:57:41.327Z] === FAIL: github.com/docker/docker/pkg/discovery/file Test/TestWatch (0.01s)
[2021-11-22T17:57:41.327Z]     file_test.go:112: assertion failed: expression is false: <-errCh == nil
[2021-11-22T17:57:41.327Z]     --- FAIL: Test/TestWatch (0.01s)
[2021-11-22T17:57:41.327Z] 
[2021-11-22T17:57:41.327Z] === FAIL: github.com/docker/docker/pkg/discovery/file Test (0.01s)
[2021-11-22T17:57:41.327Z] 
[2021-11-22T17:57:41.327Z] DONE 2075 tests, 70 skipped, 2 failures in 298.601s
```

File: daemon/logger/local/read.go [hunk 1]
```diff
@@ -99,53 +98,65 @@ func getTailReader(ctx context.Context, r loggerutils.SizeReaderAt, req int) (io
...
+		if len(d.buf) < msgLen+encodeBinaryLen {
+			d.buf = make([]byte, msgLen+encodeBinaryLen)
 		} else {
-			d.buf = d.buf[:msgLen+encodeBinaryLen]
+			if msgLen <= initialBufSize {
+				d.buf = d.buf[:initialBufSize]
+			} else {
+				d.buf = d.buf[:msgLen+encodeBinaryLen]
+			}
 		}
```
Comment (samuelkarp) [inline daemon/logger/local/read.go:156]: This buffer resizing logic could move up into `readRecord`.  We could then additionally make it so that code reading `d.buf` explicitly tries to read `d.buf[:size]` rather than the entire buffer, meaning we don't have to reslice `d.buf` making it smaller for small records and then having to re-grow it later (e.g. we can conserve the single buffer and reuse it for the life of the `decoder`, only growing it once necessary).  (The downside of this is that a single large message means we grow the buffer up to that maximum size and may not ever need it that big again and we're preventing Go from garbage-collecting that unused portion.)

@cpuguy83 What do you think about that?

File: daemon/logger/local/read.go [hunk 2]
```diff
@@ -171,34 +184,21 @@ func decodeFunc(rdr io.Reader) loggerutils.Decoder {
...
-		return nil, errors.Wrap(err, "error unmarshalling log entry")
+		return nil, errors.Wrapf(err, "error unmarshalling log entry (size=%d)", msgLen)
 	}
 
 	msg := protoToMessage(proto)
 	if msg.PLogMetaData == nil {
 		msg.Line = append(msg.Line, '\n')
 	}
+
+	d.msgLen = 0
```
Comment (apollo13) [inline daemon/logger/local/read.go:202]: Would it make more sense to move this above the `Unmarshal` call. After all the data now has been read properly and if `Unmarshal` were to throw an error the next `Decode` will try to decode the read message again and will keep throw an error that unmarshalling fails.

Comment (kzys) [reply daemon/logger/local/read.go:202]: Good point. Will do.

File: daemon/logger/local/read.go (hunk 1 above)
Comment (kzys) [reply daemon/logger/local/read.go:156]: Does the log record have its upper limit in terms of the size? Bit worried about the downside you've mentioned.

**Comment by thaJeztah** [comment]
Looks like there's a compile failure;

```

[2021-11-23T17:35:48.032Z] _=/usr/bin/env
[2021-11-23T17:35:48.032Z] Building test suite binary /go/src/github.com/docker/docker/integration/build/test.main
[2021-11-23T17:37:24.547Z] # github.com/docker/docker/daemon/logger/local
[2021-11-23T17:37:24.547Z] daemon/logger/local/read.go:204:12: undefined: proto
[2021-11-23T17:37:24.547Z] # github.com/docker/docker/daemon/logger/local
[2021-11-23T17:37:24.547Z] daemon/logger/local/read.go:204:12: undefined: proto
[2021-11-23T17:37:56.698Z] Building test suite binary /go/src/github.com/docker/docker/integration/config/test.main
[2021-11-23T17:37:56.959Z] Building test suite binary /go/src/github.com/docker/docker/integration/container/test.main
[2021-11-23T17:38:11.866Z] # github.com/docker/docker/daemon/logger/local
[2021-11-23T17:38:11.866Z] daemon/logger/local/read.go:204:12: undefined: proto

**Comment by kzys** [comment]
@thaJeztah Oh sorry. It should be fixed in the last revision.

**Comment by kzys** [comment]
One Windows build is failing.

```
[2021-11-23T22:21:29.904Z] === Failed
[2021-11-23T22:21:29.904Z] === FAIL: github.com/docker/docker/daemon/logger/jsonfilelog TestJSONFileLoggerWithOpts (0.04s)
[2021-11-23T22:21:29.904Z]     jsonfilelog_test.go:187: open C:\Users\ContainerAdministrator\AppData\Local\Temp\docker-logger-1992056636\container.log.1: The process cannot access the file because it is being used by another process.
[2021-11-23T22:21:29.904Z] 
[2021-11-23T22:21:29.904Z] DONE 2075 tests, 68 skipped, 1 failure in 251.343s
```

Others are all green now!

**Comment by samuelkarp** [comment]
I don't see an open issue for a flake in TestJSONFileLoggerWithOpts so I've kicked off a rerun to see if that fixes it.

**Comment by samuelkarp** [comment]
It looks like there are failures related to reading logs in the tests:

```
[2021-11-24T19:29:54.941Z] === Failed
[2021-11-24T19:29:54.941Z] === FAIL: amd64.integration-cli TestDockerSuite/TestLogsAPIUntilFutureFollow (20.72s)
[2021-11-24T19:29:54.941Z]     docker_api_logs_test.go:155: timeout waiting for logs to exit
[2021-11-24T19:29:54.941Z]     --- FAIL: TestDockerSuite/TestLogsAPIUntilFutureFollow (20.72s)
[2021-11-24T19:29:54.941Z] 
[2021-11-24T19:29:54.941Z] === FAIL: amd64.integration-cli TestDockerSuite/TestLogsFollowSlowStdoutConsumer (1.39s)
[2021-11-24T19:29:54.941Z]     docker_cli_logs_test.go:246: assertion failed: 0 (actual int) != 150000 (expected int)
[2021-11-24T19:29:54.941Z]     --- FAIL: TestDockerSuite/TestLogsFollowSlowStdoutConsumer (1.39s)
[2021-11-24T19:29:54.941Z] 
[2021-11-24T19:29:54.941Z] === FAIL: amd64.integration-cli TestDockerSuite/TestLogsSinceFutureFollow (5.45s)
[2021-11-24T19:29:54.941Z]     docker_cli_logs_test.go:204: assertion failed: len(out) is 0: cannot read from empty log
[2021-11-24T19:29:54.941Z]     --- FAIL: TestDockerSuite/TestLogsSinceFutureFollow (5.45s)
```

**Comment by thaJeztah** [comment]
(But it looks green now!)

File: daemon/logger/local/read.go [hunk 3]
```diff
@@ -99,63 +98,71 @@ func getTailReader(ctx context.Context, r loggerutils.SizeReaderAt, req int) (io
...
+		}
+		d.nextMsgLen = len
+	}
+	return d.decodeLogEntry()
 }
 
 func (d *decoder) Reset(rdr io.Reader) {
+	if d.rdr == rdr {
+		return
+	}
```
Comment (kzys) [inline daemon/logger/local/read.go:155]: > It looks like there are failures related to reading logs in the tests:

Before I simply removed dec.Reset() on logfile.go's fsnotify.Write case and that broke the tests.

**Comment by kzys** [comment]
> (But it looks green now!)

Yes. Removing `dec.Reset()` was wrong. Now the code should be correct!

File: daemon/logger/local/read.go [hunk 4]
```diff
@@ -99,63 +98,71 @@ func getTailReader(ctx context.Context, r loggerutils.SizeReaderAt, req int) (io
...
+	if d.buf == nil {
+		d.buf = make([]byte, initialBufSize)
 	}
 
-	return decodeLogEntry(d.rdr, d.proto, d.buf, msgLen)
+	if d.nextMsgLen == 0 {
+		len, err := d.decodeSizeHeader()
+		if err != nil {
+			return nil, err
+		}
```
Comment (fredericdalleau) [inline daemon/logger/local/read.go:146]: I wonder if the value should be sanity checked here to avoid excessive allocation. `len` is read from a 32bits value.

**Review by fredericdalleau — COMMENTED** [review]
I gave it a try and at first I was not seeing it crash. It turned out, with enough ram, the issue may not be reproducible. There is no garantee here, and I had to reboot after a few tries. You can see in top output that dockerd is bigger. 
``` 
PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
1406 root      20   0   20.4g   9.5g  38868 S 202.3  61.1   0:16.56 dockerd
```
With the patch however, the memory is not exceeded:
```
2321 root      20   0 1864048  79484  39156 R 195.7   0.5   1:12.73 dockerd                                                                                
```
My understanding is that in some situations ` io.Readfull` return ` (0, io.EOF)`, resulting in the upper layer calling `Decode()`  again with what's following.
I'd have expected that `io.Readfull` do not return until the requested amount of data is read. Maybe the intent of the writer(@cpuguy83 ?) was that too. If this function is running in it's own goroutine, could it block there just waiting for next data instead?

With a retry (`if err == io.EOF { continue }`), I was not seeing the crash, but I can't tell if the code is spinning or blocking.

File: daemon/logger/loggerutils/logfile.go [hunk 5]
```diff
@@ -715,6 +715,7 @@ func followLogs(f *os.File, logWatcher *logger.LogWatcher, notifyRotate, notifyE
 			defer func() { oldSize = size }()
 			if size < oldSize { // truncated
 				f.Seek(0, 0)
+				dec.Reset(f)
```
[the remark this answers is not in the document]
Comment (apollo13) [reply daemon/logger/loggerutils/logfile.go:718]: Isn't any state that a decoder might have at this point broken anyways and a `Reset` the only sensible thing to do?

**Comment by kzys** [comment]
> I gave it a try and at first I was not seeing it crash. It turned out, with enough ram, the issue may not be reproducible. 

Yes. It is not a leak technically. Docker Engine allocates an unnecessary large block due to the serialization issue (interpreting the non-size part of a message as its size). This would be freed by Go's GC. That being said, due to https://github.com/golang/go/commit/05e6d28849293266028c0bc9e9b0f8d0da38a2e2, RSS may not reflect the fact if your Go version is < 1.16.

File: daemon/logger/loggerutils/logfile.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (kzys) [reply daemon/logger/loggerutils/logfile.go:718]: I hope the tests are ensuring it has no regressions. At least it caught my mistake correctly on the earlier revisions.

Regrading the Decoder interface, is it implemented by only https://github.com/moby/moby/blob/d456264580cf21de8f22d678afd0cf5decfea36a/daemon/logger/jsonfilelog/read.go#L63-L68 and https://github.com/moby/moby/blob/d456264580cf21de8f22d678afd0cf5decfea36a/daemon/logger/local/read.go#L99-L103?

File: daemon/logger/local/read.go (hunk 4 above)
Comment (kzys) [reply daemon/logger/local/read.go:146]: decodeSizeHeader is internally calling binary.BigEndian.Uint32(). So it wouldn't be larger than Unit32.

File: daemon/logger/local/read.go (hunk 3 above)
Comment (fredericdalleau) [reply daemon/logger/local/read.go:155]: Which test did it broke?
Maybe there should be two methods? (dec.FileTruncated() and dec.Reset())

File: daemon/logger/local/read.go (hunk 4 above)
Comment (kzys) [reply daemon/logger/local/read.go:146]: Yep. As you mentioned, it is ultimately depends on the host's memory situation.

File: daemon/logger/local/read.go [hunk 6]
```diff
@@ -99,63 +98,71 @@ func getTailReader(ctx context.Context, r loggerutils.SizeReaderAt, req int) (io
...
-		d.buf = make([]byte, initialBufSize)
-	}
-	var (
-		read int
-		err  error
-	)
-
+func (d *decoder) readRecord(size int) error {
+	var err error
 	for i := 0; i < maxDecodeRetry; i++ {
```
[the remark this answers is not in the document]
Comment (kzys) [reply daemon/logger/local/read.go:113]: It could be. The retry is there from the very beginning (#37092) though. @cpuguy83 What do you think?

File: daemon/logger/local/read.go (hunk 3 above)
Comment (kzys) [reply daemon/logger/local/read.go:155]: The ones @samuelkarp mentioned above were broken.

```
[2021-11-24T19:29:54.941Z] === Failed
[2021-11-24T19:29:54.941Z] === FAIL: amd64.integration-cli TestDockerSuite/TestLogsAPIUntilFutureFollow (20.72s)
[2021-11-24T19:29:54.941Z]     docker_api_logs_test.go:155: timeout waiting for logs to exit
[2021-11-24T19:29:54.941Z]     --- FAIL: TestDockerSuite/TestLogsAPIUntilFutureFollow (20.72s)
[2021-11-24T19:29:54.941Z] 
[2021-11-24T19:29:54.941Z] === FAIL: amd64.integration-cli TestDockerSuite/TestLogsFollowSlowStdoutConsumer (1.39s)
[2021-11-24T19:29:54.941Z]     docker_cli_logs_test.go:246: assertion failed: 0 (actual int) != 150000 (expected int)
[2021-11-24T19:29:54.941Z]     --- FAIL: TestDockerSuite/TestLogsFollowSlowStdoutConsumer (1.39s)
[2021-11-24T19:29:54.941Z] 
[2021-11-24T19:29:54.941Z] === FAIL: amd64.integration-cli TestDockerSuite/TestLogsSinceFutureFollow (5.45s)
[2021-11-24T19:29:54.941Z]     docker_cli_logs_test.go:204: assertion failed: len(out) is 0: cannot read from empty log
[2021-11-24T19:29:54.941Z]     --- FAIL: TestDockerSuite/TestLogsSinceFutureFollow (5.45s)
```

I prefer to keep Decoder's interface as is. It takes io.Reader and doesn't have to know the source of the reader. So mentioning files there doesn't match with the rest of the interface.

File: daemon/logger/local/read.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (cpuguy83) [reply daemon/logger/local/read.go:113]: Maybe let's just fix the original bug and make such changes separately?
This makes it easier to back port.

[the remark this answers is not in the document]
Comment (fredericdalleau) [reply daemon/logger/local/read.go:113]: Makes sense

File: daemon/logger/local/read.go (hunk 4 above)
Comment (cpuguy83) [reply daemon/logger/local/read.go:146]: I think it would be better to check size and error than alloc something that is clearly wrong.
There is a maximum for each message (raw log message max is 1MB, IIRC, not sure what that would be in proto+metadata). We could check something like 512MB, which is way to much to bother allocating.

File: daemon/logger/local/read.go [hunk 7]
```diff
@@ -171,34 +178,41 @@ func decodeFunc(rdr io.Reader) loggerutils.Decoder {
...
-			read += n
-			continue
+func (d *decoder) decodeSizeHeader() (int, error) {
+	err := d.readRecord(encodeBinaryLen)
+	if err != nil {
+		return 0, errors.Wrap(err, "could not read a size header")
+	}
+
+	msgLen := int(binary.BigEndian.Uint32(d.buf[:encodeBinaryLen]))
+	if len(d.buf) < msgLen+encodeBinaryLen {
```
Comment (cpuguy83) [inline daemon/logger/local/read.go:188]: This should probably be in `decodeLogEntry` decode logic since we aren't just decoding the header.

File: daemon/logger/local/read.go (hunk 4 above)
Comment (kzys) [reply daemon/logger/local/read.go:146]: Oh, I didn't know the 1MB cap. Is it defined by the files under docker/daemon/logger?

File: daemon/logger/local/read.go [hunk 8]
```diff
@@ -99,63 +98,71 @@ func getTailReader(ctx context.Context, r loggerutils.SizeReaderAt, req int) (io
...
-		err  error
-	)
-
+func (d *decoder) readRecord(size int) error {
+	var err error
 	for i := 0; i < maxDecodeRetry; i++ {
 		var n int
-		n, err = io.ReadFull(d.rdr, d.buf[read:encodeBinaryLen])
+		n, err = io.ReadFull(d.rdr, d.buf[d.offset:size])
+		d.offset += n
```
Comment (cpuguy83) [inline daemon/logger/local/read.go:116]: It seems like we are only using offset inside this function to handle `ErrUnexpectedEOF`. Do we need to store it on the object at all?

File: daemon/logger/loggerutils/logfile.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (cpuguy83) [reply daemon/logger/loggerutils/logfile.go:718]: This seems like the right thing to do.
Can you think of a test that we can add that will fail before this change?

**Review by cpuguy83 — CHANGES_REQUESTED** [review]
This looks pretty good. Comments are mostly on organization.

File: daemon/logger/local/read.go (hunk 4 above)
Comment (cpuguy83) [reply daemon/logger/local/read.go:146]: Oh it's even smaller, https://github.com/moby/moby/blob/d456264580cf21de8f22d678afd0cf5decfea36a/daemon/logger/copier.go#L21

Log entries are broken up at newline or 16K.

Comment (kzys) [reply daemon/logger/local/read.go:146]: But a line could be longer than 16K. Isn't it?

Comment (cpuguy83) [reply daemon/logger/local/read.go:146]: No, 16K is the max and anything longer is broken up into multiple entries.

Comment (cpuguy83) [reply daemon/logger/local/read.go:146]: The actual proto we record may be larger than 16K, of course, but that has a soft max just by virtue of the raw log message being capped.

File: daemon/logger/local/read.go (hunk 7 above)
Comment (kzys) [reply daemon/logger/local/read.go:188]: You meant the buf resizing logic below shouldn't be in decodeSizeHeader? I can agree.

```go
	if len(d.buf) < msgLen+encodeBinaryLen {
		d.buf = make([]byte, msgLen+encodeBinaryLen)
	} else {
		if msgLen <= initialBufSize {
			d.buf = d.buf[:initialBufSize]
		} else {
			d.buf = d.buf[:msgLen+encodeBinaryLen]
		}
	}
```

File: daemon/logger/local/read.go (hunk 8 above)
Comment (kzys) [reply daemon/logger/local/read.go:116]: Yes. readRecord() have no guarantees about where it ends. It would be the middle of the log message. So the decoder has to keep the fact and read the remaining in that case.

**Comment by kzys** [comment]
Let me think about testing. Luckily followLogs is not tied to any structs. We may be able to test that somehow...

File: daemon/logger/local/read.go (hunk 7 above)
Comment (kzys) [reply daemon/logger/local/read.go:188]: How about putting the if block in Decode() instead?

Comment (cpuguy83) [reply daemon/logger/local/read.go:188]: Works for me.

**Comment by kzys** [comment]
@cpuguy83 @thaJeztah The tests are all green now. Can you take a look?

**Review by cpuguy83 — APPROVED** [review]
LGTM

File: daemon/logger/local/read_test.go [hunk 9]
```diff
@@ -0,0 +1,52 @@
...
+	buf, err := marshal(&logger.Message{Line: []byte("hello")})
+	assert.NilError(t, err)
+
+	for i := 0; i < len(buf); i++ {
+		testDecode(t, buf, i)
+	}
+}
+
+func testDecode(t *testing.T, buf []byte, split int) {
+	fw, err := ioutil.TempFile("", t.Name())
```
Comment (thaJeztah) [inline daemon/logger/local/read_test.go:26]: On master, we already switched uses of `ioutil` for `os`, but we can update that in a follow-up (perhaps keeping it to use `ioutil` may make it easier to backport if we want to)

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

File: daemon/logger/loggerutils/logfile_test.go [hunk 10]
```diff
@@ -244,6 +246,77 @@ func TestFollowLogsProducerGone(t *testing.T) {
...
+
+func (d *lineDecoder) Reset(r io.Reader) {
+	d.r = bufio.NewReader(r)
+	d.resetCount++
+}
+
+func (d *lineDecoder) Close() {
+}
+
+func TestFollowLogsHandleDecodeErr(t *testing.T) {
```
Comment (thaJeztah) [inline daemon/logger/loggerutils/logfile_test.go:272]: Looks like this test is flaky (seen two failures today 😅 )

Comment (kzys) [reply daemon/logger/loggerutils/logfile_test.go:272]: Nah, let me take a look...

Comment (thaJeztah) [reply daemon/logger/loggerutils/logfile_test.go:272]: I haven't looked closely yet myself, but thought I'd at least leave a comment (thanks!)
