### PR TITLE
overlay2: use index=off if possible (fix EBUSY on mount)

### LINKED ISSUE #37970: Getting error with overlayfs: device or resource busy
This seems to be related to https://github.com/moby/moby/issues/34672. 

**Description**
We have containers fail to start up, with the error: `Error response from daemon: error creating overlay mount to /mnt/docker/10000.10000/overlay2/8cf4d4d1bcfa3c3983c260dae482513a7c10e2a38e76b5bcad35da05653abfaf/merged: device or resource busy`

In the log, we get:

```
Oct 04 22:59:40 titusagent-mainvpc-r416xlarge004-i-06067ebd1d0792b8a dockerd[1870]: time="2018-10-04T22:59:40.200321961Z" level=debug msg="SetQuota(/mnt/docker/10000.10000/overlay2/8cf4d4d1bcfa3c3983c260dae482513a7c10e2a38e76b5bcad35da05653abfaf-init, 18122539008): projectID=1078"
Oct 04 22:59:41 titusagent-mainvpc-r416xlarge004-i-06067ebd1d0792b8a dockerd[1870]: time="2018-10-04T22:59:41.516160665Z" level=debug msg="SetQuota(/mnt/docker/10000.10000/overlay2/8cf4d4d1bcfa3c3983c260dae482513a7c10e2a38e76b5bcad35da05653abfaf, 18122539008): projectID=1079"
Oct 04 22:59:41 titusagent-mainvpc-r416xlarge004-i-06067ebd1d0792b8a dockerd[1870]: time="2018-10-04T22:59:41.540898661Z" level=debug msg="container mounted via layerStore: &{/mnt/docker/10000.10000/overlay2/8cf4d4d1bcfa3c3983c260dae482513a7c10e2a38e76b5bcad35da05653abfaf/merged 0x55da380489e0 0x55da380489e0}"
Oct 04 22:59:44 titusagent-mainvpc-r416xlarge004-i-06067ebd1d0792b8a dockerd[1870]: time="2018-10-04T22:59:44.243611858Z" level=debug msg="container mounted via layerStore: &{/mnt/docker/10000.10000/overlay2/8cf4d4d1bcfa3c3983c260dae482513a7c10e2a38e76b5bcad35da05653abfaf/merged 0x55da380489e0 0x55da380489e0}"
Oct 04 22:59:45 titusagent-mainvpc-r416xlarge004-i-06067ebd1d0792b8a dockerd[1870]: time="2018-10-04T22:59:45.810327774Z" level=debug msg="container mounted via layerStore: &{/mnt/docker/10000.10000/overlay2/8cf4d4d1bcfa3c3983c260dae482513a7c10e2a38e76b5bcad35da05653abfaf/merged 0x55da380489e0 0x55da380489e0}"
Oct 04 22:59:46 titusagent-mainvpc-r416xlarge004-i-06067ebd1d0792b8a dockerd[1870]: time="2018-10-04T22:59:46.602156580Z" level=debug msg="container mounted via layerStore: &{/mnt/docker/10000.10000/overlay2/8cf4d4d1bcfa3c3983c260dae482513a7c10e2a38e76b5bcad35da05653abfaf/merged 0x55da380489e0 0x55da380489e0}"
Oct 04 22:59:46 titusagent-mainvpc-r416xlarge004-i-06067ebd1d0792b8a dockerd[1870]: time="2018-10-04T22:59:46.865366329Z" level=error msg="error unmounting /mnt/docker/10000.10000/overlay2/8cf4d4d1bcfa3c3983c260dae482513a7c10e2a38e76b5bcad35da05653abfaf/merged: invalid argument"
Oct 04 22:59:46 titusagent-mainvpc-r416xlarge004-i-06067ebd1d0792b8a dockerd[1870]: time="2018-10-04T22:59:46.946538129Z" level=debug msg="Failed to unmount 8cf4d4d1bcfa3c3983c260dae482513a7c10e2a38e76b5bcad35da05653abfaf overlay: /mnt/docker/10000.10000/overlay2/8cf4d4d1bcfa3c3983c260dae482513a7c10e2a38e76b5bcad35da05653abfaf/merged - no such file or directory"
Oct 04 22:59:46 titusagent-mainvpc-r416xlarge004-i-06067ebd1d0792b8a dockerd[1870]: time="2018-10-04T22:59:46.948102510Z" level=debug msg="FIXME: Got an API for which error does not match any expected type!!!: error creating overlay mount to /mnt/docker/10000.10000/overlay2/8cf4d4d1bcfa3c3983c260dae482513a7c10e2a38e76b5bcad35da05653abfaf/merged: device or resource busy" error_type="*errors.errorString" module=api
Oct 04 22:59:46 titusagent-mainvpc-r416xlarge004-i-06067ebd1d0792b8a dockerd[1870]: time="2018-10-04T22:59:46.948117937Z" level=error msg="Handler for POST /v1.26/containers/cec5ef92af3ddd4e938cbbb95b11dc04bf03edc4c6ed76dcf0bba991d1c577ff/start returned error: error creating overlay mount to /mnt/docker/10000.10000/overlay2/8cf4d4d1bcfa3c3983c260dae482513a7c10e2a38e76b5bcad35da05653abfaf/merged: device or resource busy"
Oct 04 22:59:46 titusagent-mainvpc-r416xlarge004-i-06067ebd1d0792b8a dockerd[1870]: time="2018-10-04T22:59:46.948134415Z" level=debug msg="FIXME: Got an API for which error does not match any expected type!!!: error creating overlay mount to /mnt/docker/10000.10000/overlay2/8cf4d4d1bcfa3c3983c260dae482513a7c10e2a38e76b5bcad35da05653abfaf/merged: device or resource busy" error_type="*errors.errorString" module=api

```

**Additional information you deem important (e.g. issue happens only occasionally):**
We're still trying to figure out the root cause of this, as it's happening quite infrequently. 

**Output of `docker version`:**

```
(nfsuper) ~ $ docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
(nfsuper) ~ $ docker info
Containers: 11
 Running: 11
 Paused: 0
 Stopped: 0
Images: 14
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: /apps/titus-executor/bin/tini-static
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: ac32c23 (expected: 949e6fa)
Security Options:
 apparmor
 seccomp
  Profile: default
 userns
Kernel Version: 4.18.10netflix-gf008452
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 64
Total Memory: 480.3GiB
Name: titusagent-mainvpc-r416xlarge004-i-06067ebd1d0792b8a
ID: 4PE2:AIBM:QNEO:CHO3:AVML:WK6P:4H6T:LESA:CTES:W7RU:Z35H:E7HH
Docker Root Dir: /mnt/docker/10000.10000
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

### PR DESCRIPTION
**Pull request by kolyshkin**
As pointed out in https://github.com/moby/moby/issues/37970,
Docker overlay driver can't work with `index=on` feature of
the Linux kernel "overlay" filesystem. In case the global
default is set to "yes", Docker will fail with EBUSY when
trying to mount, like this:

> error creating overlay mount to ...../merged: device or resource busy

and the kernel log should contain something like:

> overlayfs: upperdir is in-use by another mount, mount with '-o index=off' to override exclusive upperdir protection.

A workaround is to set index=off in overlay kernel module
parameters, or even recompile the kernel with
`CONFIG_OVERLAY_FS_INDEX=n` in `.config`. Surely this is not
always practical or even possible.

The solution, as pointed out my Amir Goldstein (as well as
the above kernel message :smile:) is to use `index=off` option
when mounting.

NOTE since older (< 4.13rc1) kernels do not support `index=`
overlayfs parameter, try to figure out whether the option
is supported by the running kernel. In case it's not possible
to figure it out, assume the kernel is new enough to support it.

NOTE the default can be changed anytime (by writing to
`/sys/module/overlay/parameters/index`) so we need to **always**
use `index=off`.

Fixes: https://github.com/moby/moby/issues/37970

### CODE REVIEW

**Comment by kolyshkin** [comment]
@amir73il @thaJeztah @dmcgowan @cpuguy83 PTAL

File: daemon/graphdriver/overlay2/overlay.go [hunk 1]
```diff
@@ -577,7 +590,7 @@ func (d *Driver) Get(id, mountLabel string) (_ containerfs.ContainerFS, retErr e
 	for i, s := range splitLowers {
 		absLowers[i] = path.Join(d.home, s)
 	}
-	opts := fmt.Sprintf("lowerdir=%s,upperdir=%s,workdir=%s", strings.Join(absLowers, ":"), path.Join(dir, "diff"), path.Join(dir, "work"))
+	opts := indexOff + "lowerdir=" + strings.Join(absLowers, ":") + ",upperdir=" + path.Join(dir, "diff") + ",workdir=%s" + path.Join(dir, "work")
```
Comment (dmcgowan) [inline daemon/graphdriver/overlay2/overlay.go]: No need to convert this from fmt.Sprint

Comment (kolyshkin) [reply daemon/graphdriver/overlay2/overlay.go]: To me, it looks more readable that way (as the option arguments are right there next to options), and `Sprintf()` does nothing but string concatenating here.

Using `fmt.Sprintf()` in Golang to merely concatenate a few strings (without doing anything else like padding, quoting etc.) looks like a coding pattern that came straight from C, where you can't concatenate more than 2 strings at once, and should be discouraged unless necessary.

Concatenation is also quite faster (not that it matters in this particular case).

**Comment by kolyshkin** [comment]
CI failures due to my careless typos :keyboard:  should now be fixed

**Comment by kolyshkin** [comment]
v2: moved the detection code to driver's `Init()` where it belongs.

File: daemon/graphdriver/overlay2/overlay.go [hunk 2]
```diff
@@ -230,6 +232,15 @@ func Init(home string, options []string, uidMaps, gidMaps []idtools.IDMap) (grap
 
 	logger.Debugf("backingFs=%s,  projectQuotaSupported=%v", backingFs, projectQuotaSupported)
 
+	// figure out whether "index=off" option is recognized by the kernel
+	_, err = os.Stat("/sys/module/overlay/parameters/index")
+	if !os.IsNotExist(err) {
+		// in case Stat() returned any other error than ENOENT,
+		// there is no way to figure out whether index= option
+		// is supported or not, so let's assume it is.
```
Comment (thaJeztah) [inline daemon/graphdriver/overlay2/overlay.go]: What's the result if it's not supported and we set this option? Will it fail?

File: daemon/graphdriver/overlay2/overlay.go (hunk 1 above)
Comment (kolyshkin) [reply daemon/graphdriver/overlay2/overlay.go]: @dmcgowan please let me know what you think about ^^^ , and I'll surrender and obey :)

File: daemon/graphdriver/overlay2/overlay.go (hunk 2 above)
Comment (kolyshkin) [reply daemon/graphdriver/overlay2/overlay.go]: Yes, it will most probably result in kernel returning `EINVAL` from `mount()` syscall. This will only happen if:
 * kernel is > 4.13rc1 (and the relevant feature is not backported);
and
 * for some reason /sys/module/overlay/parameters/index is present but `stat()` returns an error.

The former is quite possible, say on older distros.

The latter is highly unlikely to happen, from the top of my head I can only think of a severe kernel memory shortage, or using any security mechanisms (say selinux) to disallow dockerd access to e.g. /sys/module/ directory.

Comment (thaJeztah) [reply daemon/graphdriver/overlay2/overlay.go]: Right, so I was thinking if we should take the safe approach, and only add `index=off` if we're successfully able to detect that it's supported (i.e. `os.Stat()` was successfull), so:

- `os.Stat()` was successful; add `index=off`
- `os.Stat()` produces an `IsNotExist`: don't add `index=off`, and continue silently (as this is an expected situation)
- `os.Stat()` produces any other error: log a warning (`"unable to detect if index=off is supported: <original error message>"`), but continue as usual (but _don't_ add `index=off`)

Comment (thaJeztah) [reply daemon/graphdriver/overlay2/overlay.go]: Logging a warning at least makes it visible that we were unable to detect, and may assist in troubleshooting why we failed to detect.

File: daemon/graphdriver/overlay2/overlay.go (hunk 1 above)
Comment (dmcgowan) [reply daemon/graphdriver/overlay2/overlay.go]: This change is fine, neither has great readability but not worth making it an array and joining

File: daemon/graphdriver/overlay2/overlay.go (hunk 2 above)
Comment (kolyshkin) [reply daemon/graphdriver/overlay2/overlay.go]: Makes sense; please see updated commit

File: daemon/graphdriver/overlay2/check.go [hunk 3]
```diff
@@ -27,7 +26,7 @@ func doesSupportNativeDiff(d string) error {
 	}
 	defer func() {
 		if err := os.RemoveAll(td); err != nil {
-			logrus.WithField("storage-driver", "overlay2").Warnf("Failed to remove check directory %v: %v", td, err)
+			logger.Warnf("Failed to remove check directory %v: %v", td, err)
```
Comment (thaJeztah) [inline daemon/graphdriver/overlay2/check.go]: We should also start using `.WithError()` for these;

```go
logger.WithError(err).Warnf("Failed to remove check directory %v", td)
```

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Review by tonistiigi — APPROVED** [review]
@dmcgowan

**Review by dmcgowan — APPROVED** [review]
LGTM

**Comment by cody-c-lewis** [comment]
It looks like this change blocks a docker image from setting up an NFS export of a directory in the root file system (ie, what's enabled by this [overlay Linux kernel module addition](https://lwn.net/Articles/743275/)). Is there no way to export the filesystem with the overlay driver in Docker?

In the past I've used the AUFS driver, but that's deprecated and going away bit by bit.

**Comment by amir73il** [comment]
@cody-c-lewis how were you planing to enable nfs_export in overlayfs? Without changing docker?
IMO, enabling NFS export should be controlled by a docker image config and/or runtime parameter.
When NFS export is requested, docker should not use index=off and add nfs_export=on mount option instead.
This will have at least two implications:
1. If there are sill unfixed mount leaks in docker, that could lead to EBUSY errors on overlayfs mount
2. Mounting overlayfs with index=on,nfs_export=on is recommended when upper layer is empty - it is not recommended to mount the same overlay with index=off, make changes and mount with index=on,nfs_export=on again
At best case, NFS client may get ESTALE errors, at worst case, even local application may get EIO error when trying to access files in such an overlay mount

**Comment by cody-c-lewis** [comment]
> @cody-c-lewis how were you planing to enable nfs_export in overlayfs? Without changing docker?

Since there isn't any docker setting for this then my next thought was to set it via the kernel module parameters (such as `/sys/module/overlay/parameters`). But I'm searching in the dark here and open to suggestions and working backwards from a desired end state (being able to run an NFS server inside of a docker container that serves a static part of the image).

> IMO, enabling NFS export should be controlled by a docker image config and/or runtime parameter. When NFS export is requested, docker should not use index=off and add nfs_export=on mount option instead. This will have at least two implications...

It sounds like these two issues were the motivation behind this PR so I guess the real question is if they've been resolved in the intervening 3 years. If that's the case then maybe undoing this PR would be a solution, or adding first class support to docker as you describe.

**Comment by rdlarkins** [comment]
> Since there isn't any docker setting for this then my next thought was to set it via the kernel module parameters (such as `/sys/module/overlay/parameters`).

The kernel module config gets overridden by the mount options set here. I rebuilt the kernel module to ignore these two mount options and just use the default parameters set, and starting a single container with a nfs export does seem to work at least superficially.

**Comment by cpuguy83** [comment]
Just trying to understand, you are trying to create an nfs export on a path inside the container which is just part of the normal container rootfs (ie. overlay) and not a bind-mount from the host?

Have you considered bind-mounting a dir here (or just an anonymous volume) so that it bypasses overlay entirely? You can still create the nfs export in the container, just now it doesn't have to depend on the details of the container rootfs.

**Comment by rdlarkins** [comment]
That is correct. I originally posted about this on the docker forums, you might find the details there more interesting: https://forums.docker.com/t/nfs-export-disabled-with-overlay2-as-storage-driver/121325

I have considered other options for the source of the files in the nfs export, but as I would like the files to be versioned alongside the rest of the container content, updating them as a single unit is logistically easier.

**Comment by rdlarkins** [comment]
I've had some more time to work with this over the past couple days. So far it seems that for my specific use case, there aren't any issues with enabling index and nfs_export. I've created an issue so that discussion can happen there rather than a 4 year old PR. https://github.com/moby/moby/issues/43299
