### PR TITLE
Windows: Case-insensitive filename matching against builder cache

### LINKED ISSUE #33107: Builder skips changed files on COPY or ADD and uses cache
**DESCRIPTION**
Builder skips changed files on COPY or ADD unless adding a new file or changing dockerfile

**Steps to reproduce the issue:**
1. Install docker on Windows Server 2016
2. Run a build with dockerfile copying/adding a directory to a container
3. Change something in one of the files in the source folder
4. Run the same build again and notice docker used cache not including changes made in step 3

**Describe the results you received:**
Docker skipped changes in the source folder and used cached resources.

**Describe the results you expected:**
Expected docker not to use cache on the copy/add step when changes were made in sources folder.

**Additional information you deem important (e.g. issue happens only occasionally):**
Originaly i stumbled upon this problem while testing VSTS integration with docker. When i had whole environment ready (agent with docker, docker host and a repository) i noticed that application that i deployed on Windows Server 2016 didn't want to work. When i checked everything i noticed that no changes are being made on neext builds after the initial one UNLESS i change something in the dockerfile (like changing copy to add) or add new files to the sources (then the build noticed changes and properly rebuilded the step). If you look at vsts docker page in the comments on 3/29/2017 theres a user who has exact same issue https://marketplace.visualstudio.com/items?itemName=ms-vscs-rm.docker.

Another weird thing worth mentioning is that originaly this error occured to me at version 1.12 beta which came from Windows Server role installation. When i updated to current version 17.03.1 nothing has changed.

**Output of `docker version`:**

```
Docker version 17.03.1-ee-3, build 3fcee33
```

**Output of `docker info`:**

```
Containers: 10
 Running: 0
 Paused: 0
 Stopped: 10
Images: 23
Server Version: 17.03.1-ee-3
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.953.amd64fre.rs1_release_inmarket.170303-1614)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 3.5 GiB
Name: *******
ID: QKZX:YNWS:EK57:L2W3:QXK5:6K2E:LWMB:RPVH:SLD6:AARX:WA55:M6LP
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Username: *********
Registry: https://**************
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows Server 2016

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard <jhoward@microsoft.com>

This fixes #33107 where if a local directory is in uppercase and a docker build is run, then a file in that directory is altered and another build is run, it uses the cache rather than taking the update. This is because the comparison was being done exactly, where-as on Windows, c:\app and c:\APP are the same on NTFS.  See https://github.com/moby/moby/issues/33107#issuecomment-347700140

Given this build context (note the `App` directory has an upper-case letter in it):

```
PS E:\docker\build\33107> dir -r


    Directory: E:\docker\build\33107


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       12/13/2017   3:46 PM                App
-a----       11/28/2017   3:16 PM            339 dockerfile


    Directory: E:\docker\build\33107\App


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       12/13/2017  12:30 PM                UPPER
-a----       11/28/2017   2:48 PM              6 addedfile.aspx.cs
-a----       11/28/2017   3:13 PM              6 new1
-a----       11/28/2017   2:47 PM              6 somefile.aspx.cs
-a----       11/28/2017   3:28 PM            284 tEsT.txt
```

And this dockerfile content:
```
# escape=`
FROM microsoft/windowsservercore
RUN powershell md c:\app
COPY app c:\app
```

Here's the output from docker master 1cea9d3bdb427bbdd7f14c6b11a3f6cef332bd34 12/13/2017 showing the bug:

First build, forcing no-cache.
```
PS E:\docker\build\33107> docker build --no-cache .
Sending build context to Docker daemon  7.168kB
Step 1/3 : FROM microsoft/windowsservercore
 ---> 511077485562
Step 2/3 : RUN powershell md c:\app
 ---> Running in ed9b684e05e0


    Directory: C:\


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       12/13/2017   4:35 PM                app


Removing intermediate container ed9b684e05e0
 ---> 3644daaaa31f
Step 3/3 : COPY app c:\app
 ---> 9250b3aad8cd
Successfully built 9250b3aad8cd
PS E:\docker\build\33107>
```

Update the contents of `app\test.txt`
```
PS E:\docker\build\33107> type .\App\test.txt
 FROM microsoft/windowsservercore
RUN dism /online /enable-feature /all /featurename:iis-webserver /NoRestart
RUNEXPOSE 8081
RUN powershell Remove-Website -Name 'Default Web Site'
RUN powershell md c:\
RUN powershell New-Website -Name 'app' -Port 8081 -PhysicalPath 'c:\app'

changed asjdfklasjdf
PS E:\docker\build\33107> echo "foobar" > .\App\test.txt
PS E:\docker\build\33107>
```

And build again, you see the bug - step 3 is using the cache when it shouldn't.
```
PS E:\docker\build\33107> docker build .
Sending build context to Docker daemon  7.168kB
Step 1/3 : FROM microsoft/windowsservercore
 ---> 511077485562
Step 2/3 : RUN powershell md c:\app
 ---> Using cache
 ---> 3644daaaa31f
Step 3/3 : COPY app c:\app
 ---> Using cache
 ---> 9250b3aad8cd
Successfully built 9250b3aad8cd
PS E:\docker\build\33107>
```

With this fix, you get the following instead. First, build forcing a cache-miss:
```
PS E:\docker\build\33107> docker build --no-cache .
Sending build context to Docker daemon  7.168kB
Step 1/3 : FROM microsoft/windowsservercore
 ---> 511077485562
Step 2/3 : RUN powershell md c:\app
 ---> Running in d504a5d35157


    Directory: C:\


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       12/13/2017   4:39 PM                app


Removing intermediate container d504a5d35157
 ---> 2d0ba8e32f64
Step 3/3 : COPY app c:\app
 ---> e7287a3c2d5f
Successfully built e7287a3c2d5f
PS E:\docker\build\33107>
```

Next, update `app\test.txt again`

```
PS E:\docker\build\33107> type .\App\test.txt
foobar
PS E:\docker\build\33107> echo "fixed" > .\App\test.txt
PS E:\docker\build\33107>
```

And then a build showing that that cache is correctly broken through the changed file in the build context:

```
PS E:\docker\build\33107> docker build .
Sending build context to Docker daemon  7.168kB
Step 1/3 : FROM microsoft/windowsservercore
 ---> 511077485562
Step 2/3 : RUN powershell md c:\app
 ---> Using cache
 ---> 2d0ba8e32f64
Step 3/3 : COPY app c:\app
 ---> 1996084f86f8
Successfully built 1996084f86f8
PS E:\docker\build\33107>
```

### CODE REVIEW

**Comment by jhowardmsft** [comment]
@johnstep FYI

File: builder/builder.go [hunk 1]
```diff
@@ -31,7 +31,7 @@ type Source interface {
 	// delete the temporary directory in Close().
 	Close() error
 	// Hash returns a checksum for a file
-	Hash(path string) (string, error)
+	Hash(path string, targetOS string) (string, error)
```
Comment (dnephin) [inline builder/builder.go]: Instead of changing the interface I think it would be better to have the implementations of `Source()` store the `Platform`.

**Review by dnephin — CHANGES_REQUESTED** [review]

File: builder/builder.go (hunk 1 above)
Comment (jhowardmsft) [reply builder/builder.go]: @dnephin Turns out this needs to be done for LCOW as well, so it doesn't need to know the targetOS at all. These are just source files on the local machine which will be NTFS. Hence updated to be a much simpler fix.

Comment (dnephin) [reply builder/builder.go]: Ya that is a much smaller change!

File: pkg/tarsum/fileinfosums.go [hunk 2]
```diff
@@ -35,8 +39,17 @@ type FileInfoSums []FileInfoSumInterface
...
 func (fis FileInfoSums) GetFile(name string) FileInfoSumInterface {
+	// We do case insensitive matching on Windows as c:\APP and c:\app are
+	// the same. See issue #33107.
+	if runtime.GOOS == "windows" {
+		name = strings.ToUpper(name)
+	}
 	for i := range fis {
-		if fis[i].Name() == name {
+		compareTo := fis[i].Name()
+		if runtime.GOOS == "windows" {
```
Comment (tonistiigi) [inline pkg/tarsum/fileinfosums.go]: nit: could we do `strings.EqualFold`

Comment (jhowardmsft) [reply pkg/tarsum/fileinfosums.go]: @tonistiigi Sure, updated

**Comment by thaJeztah** [comment]
Ugh, this one is flaky again

```
22:27:52 ----------------------------------------------------------------------
22:27:52 PANIC: docker_api_logs_test.go:152: DockerSuite.TestLogsAPIUntil
22:27:52 
22:27:52 ... Panic: runtime error: index out of range (PC=0x45AC01)
22:27:52 
22:27:52 d:/CI/CI-7caa30e89/go/src/runtime/asm_amd64.s:509
22:27:52   in call32
22:27:52 d:/CI/CI-7caa30e89/go/src/runtime/panic.go:491
22:27:52   in gopanic
22:27:52 d:/CI/CI-7caa30e89/go/src/runtime/panic.go:28
22:27:52   in panicindex
22:27:52 docker_api_logs_test.go:175
22:27:52   in DockerSuite.TestLogsAPIUntil
22:27:52 d:/CI/CI-7caa30e89/go/src/runtime/asm_amd64.s:509
22:27:52   in call32
22:27:52 d:/CI/CI-7caa30e89/go/src/reflect/value.go:434
22:27:52   in Value.call
22:27:52 d:/CI/CI-7caa30e89/go/src/reflect/value.go:302
22:27:52   in Value.Call
22:27:52 c:/gopath/src/github.com/docker/docker/vendor/github.com/go-check/check/check.go:816
22:27:52   in suiteRunner.forkTest.func1
22:27:52 c:/gopath/src/github.com/docker/docker/vendor/github.com/go-check/check/check.go:672
22:27:52   in suiteRunner.forkCall.func1
22:27:52 d:/CI/CI-7caa30e89/go/src/runtime/asm_amd64.s:2337
22:27:52   in goexit
22:27:54 
22:27:54 ----------------------------------------------------------------------
```

**Comment by tonistiigi** [comment]
LGTM

**Review by johnstep — APPROVED** [review]
LGTM
