### PR TITLE
Logentries line-only logopt fix to maintain backwards compatibility

### LINKED ISSUE #35626: Logentries log driver line-only option breaks backwards compatibility
**Description**

New log driver option `line-only` for Logentries driver described in #31726 allows to dump raw data to Logentries without wrapping it into container data. However this flag breaks backwards compatibility so you won't be able to launch new container without specifying `--log-opt line-only=true/false` and all your swarm stacks will stop working with the engine update.

**Steps to reproduce the issue:**

`docker run --log-driver=logentries --log-opt logentries-token=... alpine`

**Describe the results you received:**

`docker: Error response from daemon: failed to initialize logging driver: error parsing lineonly option: strconv.ParseBool: parsing "": invalid syntax.`

**Describe the results you expected:**

No error should be produced, old behaviour (line-only=false) should be the default

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:39:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 10
 Running: 7
 Paused: 0
 Stopped: 3
Images: 59
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: i1hl69si1y513f8f64fcnccpu
 Is Manager: true
 ClusterID: zbyn1azkfdoi9rzbhedmd6kuv
 Managers: 5
 Nodes: 8
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 172.37.38.140
 Manager Addresses:
  172.37.12.237:2377
  172.37.18.17:2377
  172.37.33.179:2377
  172.37.38.140:2377
  172.37.8.184:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.49-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.67GiB
Name: ip-172-37-38-140.eu-west-1.compute.internal
ID: 6ETS:MRMJ:VQNJ:4AN7:IWCT:JWG3:IRMH:FUKM:S7ZC:42ZJ:5LOH:TP2P
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 140
 Goroutines: 1193
 System Time: 2017-11-28T09:12:43.721232058Z
 EventsListeners: 3
Registry: https://index.docker.io/v1/
Labels:
 os=linux
 region=eu-west-1
 availability_zone=eu-west-1c
 instance_type=m3.medium
 node_type=manager
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This is Docker for AWS 17.09-ce (Stable)

### PR DESCRIPTION
**Pull request by ikarpovich**
**- What I did**

Fixes #35626

Logentries line-only logopt breaks backwards compatibility, logentries driver won't start without this option so existing swarm stacks will stop working after the engine update.

**- How I did it**

Log driver will now ignore empty value and drop an error only in case of invalid boolean value.

**- How to verify it**

Try to do `docker run` without specifying line-only logopt at all.

**- A picture of a cute animal (not mandatory but encouraged)**

image

Signed-off-by: Igor Karpovich <igor@karpovich.me>

### CODE REVIEW

File: daemon/logger/logentries/logentries.go [hunk 1]
```diff
@@ -51,7 +51,10 @@ func New(info logger.Info) (logger.Logger, error) {
 	}
 	var lineOnly bool
 	if lineOnly, err = strconv.ParseBool(info.Config[lineonly]); err != nil {
-		return nil, errors.Wrap(err, "error parsing lineonly option")
```
Comment (thaJeztah) [inline daemon/logger/logentries/logentries.go]: Instead of this, would it work to just check if the `info.Config[lineonly]` is empty before trying to parse it?

File: daemon/logger/logentries/logentries.go [hunk 2]
```diff
@@ -50,8 +50,10 @@ func New(info logger.Info) (logger.Logger, error) {
 		return nil, errors.Wrap(err, "error connecting to logentries")
 	}
 	var lineOnly bool
-	if lineOnly, err = strconv.ParseBool(info.Config[lineonly]); err != nil {
-		return nil, errors.Wrap(err, "error parsing lineonly option")
+	if info.Config[lineonly] != "" {
+		if lineOnly, err = strconv.ParseBool(info.Config[lineonly]); err != nil {
+			return nil, errors.Wrap(err, "error parsing lineonly option")
+		}
```
Comment (thaJeztah) [inline daemon/logger/logentries/logentries.go]: Can you add a minimum test-case for this? Could be as simple as;

```go
package logentries

import (
	"testing"

	"github.com/docker/docker/daemon/logger"
	"github.com/stretchr/testify/require"
)

func TestNewWithEmptyOptions(t *testing.T) {
	_, err := New(logger.Info{})
	require.NoError(t, err)
}
```

**Review by thaJeztah — CHANGES_REQUESTED** [review]
left one comment, but LGTM after that's addressed; can you also squash your commits? I think a single commit should be ok for this change (including the added test)

File: daemon/logger/logentries/logentries.go (hunk 2 above)
Comment (ripcurld0) [reply daemon/logger/logentries/logentries.go]: Can I also suggest changing the two ifs into one:
```Go
if lineOnly, err = strconv.ParseBool(info.Config[lineonly]); info.Config[lineonly] != "" && err != nil {
    ...
}
```

**Review by boaz0 — APPROVED** [review]
LGTM minus @thaJeztah comments

File: daemon/logger/logentries/logentries.go (hunk 2 above)
Comment (ikarpovich) [reply daemon/logger/logentries/logentries.go]: @ripcurld0 Sorry but don't agree as the (unnecessary) cast statement would be executed in any case this way.

Comment (ikarpovich) [reply daemon/logger/logentries/logentries.go]: @thaJeztah You know I even have done this and this obviously worked but then I noticed that actual TCP connection to Logentries is done in New() as well. Logentries driver used is a third party with service URL hardcoded so in this case the whole driver has to be mocked to test this properly.

**Comment by thaJeztah** [comment]
> @thaJeztah You know I even have done this and this obviously worked but then I noticed that actual TCP connection to Logentries is done in New() as well. Logentries driver used is a third party with service URL hardcoded so in this case the whole driver has to be mocked to test this properly. Unless we want to test actual Logentries connection on each test pass :)

Ah, you're right; given that this is a trivial change, I think it's ok for now to merge this without a test added

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by vieux — APPROVED** [review]
LGTM
