### PR TITLE
Fix issue with cp to container volume dir

### LINKED ISSUE #27773: mounts behavior differs between 1.10.3 and 1.12
Reproducer:

```
#!/bin/bash
set -ex
docker volume rm v1 || true
docker rm t1 t2 || true
docker volume create --name v1
docker create --name t1 -v v1:/.imagebuilder-transient-mount busybox
cat a.tar | docker cp - t1:/
cat b.tar | docker cp - t1:/
docker create --name t2 \
-v $(docker volume inspect -f '{{ .Mountpoint  }}' v1)/0:/mountdir \
-v $(docker volume inspect -f '{{ .Mountpoint  }}' v1)/1:/mountfile \
busybox cat /mountfile
docker start -a t2
docker rm -f t1
docker rm -f t2
docker volume rm v1
```

`a.tar` and `b.tar` are in [testfiles.zip](https://github.com/docker/docker/files/552765/testfiles.zip)

That used to work in 1.10.3:

```
10:47:06 [~] ./testbug.sh
+ docker volume rm v1
Error response from daemon: get v1: no such volume
+ true
+ docker rm t1 t2
t2
Failed to remove container (t1): Error response from daemon: No such container: t1
+ true
+ docker volume create --name v1
v1
+ docker create --name t1 -v v1:/.imagebuilder-transient-mount busybox
665a3fc2041c1c1faf6009eae6f8713b8ecbfdb897a410231b7254bb1947a02e
+ cat a.tar
+ docker cp - t1:/
+ cat b.tar
+ docker cp - t1:/
++ docker volume inspect -f '{{ .Mountpoint  }}' v1
++ docker volume inspect -f '{{ .Mountpoint  }}' v1
+ docker create --name t2 -v /var/lib/docker/volumes/v1/_data/0:/mountdir -v /var/lib/docker/volumes/v1/_data/1:/mountfile busybox cat /mountfile
c850d9083be7d0202e649c119fb84d608e08782dcaafa61b14be0cebbde96b2f
+ docker start -a t2
FROM busybox
ENV name value
ENV name=value
ENV name=value name2=value2
ENV name="value value1"
ENV name=value\ value2
ENV name="value'quote space'value2"
ENV name='value"double quote"value2'
ENV name=value\ value2 name2=value2\ value3
ENV name="a\"b"
ENV name="a\'b"
ENV name='a\'b'
ENV name='a\'b''
ENV name='a\"b'
ENV name="''"
# don't put anything after the next line - it must be the last line of the
# Dockerfile and it must end with \
ENV name=value \
    name1=value1 \
    name2="value2a \
           value2b" \
    name3="value3a\n\"value3b\"" \
        name4="value4a\\nvalue4b" \% 
```

While on 1.12.x we get:

```
[root@centos ~]# ./testbug.sh
+ docker volume rm v1
Error response from daemon: Unable to remove volume, volume still in use: remove v1: volume is in use - [4fe62ced403a634b3156e8459ace181020acae8f4cff4851902a6120c3aa3f31]
+ true
+ docker rm t1 t2
t1
t2
+ docker volume create --name v1
v1
+ docker create --name t1 -v v1:/.imagebuilder-transient-mount busybox
dc6b0555e82c7828ed2553b0e580145f35e4bde074bdcb0cd672e9a7877c3b32
+ cat a.tar
+ docker cp - t1:/
+ cat b.tar
+ docker cp - t1:/
++ docker volume inspect -f '{{ .Mountpoint }}' v1
++ docker volume inspect -f '{{ .Mountpoint }}' v1
+ docker create --name t2 -v /var/lib/docker-latest/volumes/v1/_data/0:/mountdir -v /var/lib/docker-latest/volumes/v1/_data/1:/mountfile busybox cat /mountfile /
afb9161809ab7b4cc4b9350f0f1a1e2e69dc4136b1bc125eb062c1d93a16c427
+ docker start -a t2
cat: read error: Is a directory
cat: read error: Is a directory
```

/cc @cpuguy83

### PR DESCRIPTION
**Pull request by cpuguy83**
In some cases, attempting to `docker cp` to a container's volume dir
would fail due to the volume mounts not existing after performing a
bind-mount on the container path prior to doing a pivot_root.

This does not seem to be effecting all systems, but was found to be a
problem on centos.
The solution is to use an `rbind` rather than `bind` so that any
existing mounts are carried over.

The `MakePrivate` on `path` is no longer neccessary since we are already
doing `MakeRPrivate` on `/`.

Fixes #27773

### CODE REVIEW

File: pkg/chrootarchive/chroot_linux.go [hunk 1]
```diff
@@ -30,9 +30,11 @@ func chroot(path string) (err error) {
 	if err := mount.MakeRPrivate("/"); err != nil {
 		return err
 	}
-	// ensure path is a mountpoint
-	if err := mount.MakePrivate(path); err != nil {
```
Comment (cpuguy83) [inline pkg/chrootarchive/chroot_linux.go]: `MakePrivate` does a `bind` only (rather than `rbind`, and we don't need to `MakePrivate` anymore sense `/` is set to `rprivate` above... but we do need to make sure the path is a mounted path otherwise pivot_root will fail.

**Comment by thaJeztah** [comment]
ping @rhvgoyal @runcom

**Comment by rhvgoyal** [comment]
This patch seems reasonable and works for me.

There are some things which I still don't understand though. I tried following without this patch and it works. And I am not sure why does it work.

- mkdir foo
- cd foo
- mkdir foochild
- mount --bind /tmp/   foochild
- docker create -ti --name t2 -v foo:/foo busybox sh
- cat d.tar | docker cp - t2:/foo/

d.tar contains following.
- foochild/
- foochild/test-file.txt

After docker cp command, test-file.txt shows up in /tmp/ dir of my host. That means even with "bind", submount "foochild" was visible in chrootarchive. Otherwise file would not have gone to /tmp. It would have gone to foo/foochild/ dir instead.

So question I am trying to address is that why in this case submount is available (despite bind) while in other case submount is not available. 

Is there any way I can get something to output on console/journal from chroot()?

**Comment by cpuguy83** [comment]
Yeah, that's one thing I don't understand, it works just fine on d4mac even with the `cat foo.tar | ...`

**Comment by rhvgoyal** [comment]
I think reason being that MakePrivate() does not create another mount point if "path" is already mounted. So in my test case, normal volume code will rbind volume and `/foo` inside the container is a mount point. So MakePrivate() does not create another mount point, so any child mounts continue to be visible.

But in @runcom case, /var/lib/docker/devmapper/..../rootfs/ (/) is not a mount point and MakePrivate creates a mount point and that masks all the submounts. 

So yes, your fix looks right.

LGTM.

**Comment by tonistiigi** [comment]
Could we add a test for this please. On overlay this can be reproduced by mounting volume to `/foo/bar`, copying data to `/foo` and seeing that it doesn't end up in `/foo/bar`.

**Comment by cpuguy83** [comment]
Originally I did not b/c I thought it would not be possible to repro in the test infra... but it might actually be specifically easy to test with the vfs driver.

**Comment by tonistiigi** [comment]
@cpuguy83 Still best to use the extra subdir as that should work the same for all drivers.

**Comment by crosbymichael** [comment]
LGTM
