### PR TITLE
c8d/inspect: Fix image inspect for incomplete images

### LINKED ISSUE #51566: Under certain conditions the API output of `docker image inspect` becomes corrupted
### Description

Under certain conditions the output of `docker image inspect` becomes corrupt. 

I have it happening sometimes with the following images:

* `gotenberg/gotenberg:8.24`
* `diygod/rsshub:chromium-bundled`

Pulling those and doing something (unknown what that is) and then inspecting yields the output as seen below. 

The output is also corrupt (`"Config": null`) when asking the API directly: 

```
❯ curl --unix-socket /var/run/docker.sock --header "Content-Type: application/json" --request GET http://localhost/images/gotenberg/gotenberg:8.24/jso
n | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   542  100   542    0     0  36828      0 --:--:-- --:--:-- --:--:-- 38714
{
  "Id": "sha256:b116a40a1c24917e2bf3e153692da5acd2e78e7cd67e1b2d243b47c178f31c90",
  "RepoTags": [
    "gotenberg/gotenberg:8.24"
  ],
  "RepoDigests": [
    "gotenberg/gotenberg@sha256:b116a40a1c24917e2bf3e153692da5acd2e78e7cd67e1b2d243b47c178f31c90"
  ],
  "Config": null,
  "Architecture": "",
  "Os": "",
  "Size": 778114898,
  "RootFS": {},
  "Metadata": {
    "LastTagTime": "2025-11-20T00:16:56.098950994Z"
  },
  "Descriptor": {
    "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
    "digest": "sha256:b116a40a1c24917e2bf3e153692da5acd2e78e7cd67e1b2d243b47c178f31c90",
    "size": 1554
  }
}
```

Using version 1.44 (oldest supported on this Docker version) yields the following:

```
❯ curl --unix-socket /var/run/docker.sock --header "Content-Type: application/json" --request GET http://localhost/v1.44/images/gotenberg/gotenberg:8.
24/json | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   759  100   759    0     0  49388      0 --:--:-- --:--:-- --:--:-- 50600
{
  "Architecture": "",
  "Author": "",
  "Comment": "",
  "Config": {
    "AttachStderr": false,
    "AttachStdin": false,
    "AttachStdout": false,
    "Cmd": null,
    "Domainname": "",
    "Entrypoint": null,
    "Env": null,
    "Hostname": "",
    "Image": "",
    "Labels": null,
    "OnBuild": null,
    "OpenStdin": false,
    "StdinOnce": false,
    "Tty": false,
    "User": "",
    "Volumes": null,
    "WorkingDir": ""
  },
  "Container": "",
  "ContainerConfig": null,
  "DockerVersion": "",
  "GraphDriver": {
    "Data": null,
    "Name": "overlayfs"
  },
  "Id": "sha256:b116a40a1c24917e2bf3e153692da5acd2e78e7cd67e1b2d243b47c178f31c90",
  "Metadata": {
    "LastTagTime": "2025-11-20T00:16:56.098950994Z"
  },
  "Os": "",
  "Parent": "",
  "RepoDigests": [
    "gotenberg/gotenberg@sha256:b116a40a1c24917e2bf3e153692da5acd2e78e7cd67e1b2d243b47c178f31c90"
  ],
  "RepoTags": [
    "gotenberg/gotenberg:8.24"
  ],
  "RootFS": {},
  "Size": 778114898
}
```

### Reproduce

1. ??? Unknown, still investigating
2. ```
   ❮ docker image inspect gotenberg/gotenberg:8.24
   [
       {
           "Id": "sha256:b116a40a1c24917e2bf3e153692da5acd2e78e7cd67e1b2d243b47c178f31c90",
           "RepoTags": [
               "gotenberg/gotenberg:8.24"
           ],
           "RepoDigests": [
                "gotenberg/gotenberg@sha256:b116a40a1c24917e2bf3e153692da5acd2e78e7cd67e1b2d243b47c178f31c90"
           ],
           "Config": null,
           "Architecture": "",
           "Os": "",
           "Size": 778114898,
           "RootFS": {},
           "Metadata": {
               "LastTagTime": "2025-11-20T00:16:56.098950994Z"
           },
           "Descriptor": {
               "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
               "digest": "sha256:b116a40a1c24917e2bf3e153692da5acd2e78e7cd67e1b2d243b47c178f31c90",
               "size": 1554
           }
       }
   ]
   ```

### Expected behavior

Output should (at the very least) contain `Config: {}`, as it is not `nullable`. 

### docker version

```bash
❯ docker version
Client: Docker Engine - Community
 Version:           29.0.2
 API version:       1.52
 Go version:        go1.25.4
 Git commit:        8108357
 Built:             Mon Nov 17 12:33:33 2025
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          29.0.2
  API version:      1.52 (minimum version 1.44)
  Go version:       go1.25.4
  Git commit:       e9ff10b
  Built:            Mon Nov 17 12:33:33 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v2.1.5
  GitCommit:        fcd43222d6b07379a4be9786bda52438f0dd16a1
 runc:
  Version:          1.3.3
  GitCommit:        v1.3.3-0-gd842d771
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
❯ docker info
Client: Docker Engine - Community
 Version:    29.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.30.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.40.3
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 55
  Running: 55
  Paused: 0
  Stopped: 0
 Images: 55
 Server Version: 29.0.2
 Storage Driver: overlayfs
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 CDI spec directories:
  /etc/cdi
  /var/run/cdi
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: fcd43222d6b07379a4be9786bda52438f0dd16a1
 runc version: v1.3.3-0-gd842d771
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.17.0-6-generic
 Operating System: Ubuntu 25.10
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 30.26GiB
 Name: server
 ID: 5c592af7-7740-4833-bdb3-912db7d3fefd
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: <ommitted>
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
 Firewall Backend: iptables
```

### Additional Info

```
❯ cat --plain /etc/docker/daemon.json
{
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "10m",
    "max-file": "3",
    "tag": "{{.Name}}/{{.ImageName}}"
  },
  "ipv6": true,
  "fixed-cidr-v6": "fdb7:3bc5:1122::/48",
  "features": {
    "containerd-snapshotter": true
  }
}
```

### PR DESCRIPTION
**Pull request by vvoland**
- fixes: https://github.com/moby/moby/issues/51566

When inspecting multi-platform images where some layer blobs were missing from the content store, the image inspect operation would return too early causing some data (like config details or unpacked size) to be omitted even though are available.

This ensures that `docker image inspect` returns as much information as possible.

**- What I did**

**- How I did it**

**- How to verify it**

`TestImageInspect/inspect image with one layer missing` unit test

**- Human readable description for the release notes**

```markdown changelog
containerd image store: Fix `docker image inspect` failing to return available image data in case where not all distributable blobs are available locally.
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: integration/image/inspect_test.go [hunk 1]
```diff
@@ -82,8 +82,76 @@ func TestImageInspectDescriptor(t *testing.T) {
...
+
+// # gotenberg
+// {
+// "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
+// "size": 30781333,
+// "digest": "sha256:b96413fb491a5ed179bb2746ff3be6cbddd72e14c6503bea80d58e579a3b92bc"
+// },
+// ```
+func TestImageInspectWithoutSomeBlobs(t *testing.T) {
+	t.Skip("TODO(vvoland): Come up with minimal images for this test")
```
Comment (vvoland) [inline integration/image/inspect_test.go:115]: TODO, but perhaps still fine to merge if we were to do a patch release.

File: integration/image/inspect_test.go [hunk 2]
```diff
@@ -82,6 +82,76 @@ func TestImageInspectDescriptor(t *testing.T) {
 	assert.Check(t, inspect.Descriptor.Size > 0)
 }
 
+// Regression test for: https://github.com/moby/moby/issues/51566
+//
+// This can be reproduced with two image that share the same uncompressed layer
+// but have a different compressed blob is pulled.
+
```
Comment (thaJeztah) [inline integration/image/inspect_test.go]: Probably should add `//` comment-lines for the empty lines so that it's all considered a single comment for the test;

```suggestion
//
```

File: integration/image/inspect_test.go [hunk 3]
```diff
@@ -82,6 +82,76 @@ func TestImageInspectDescriptor(t *testing.T) {
...
+// ```json
+// # nginx
+// {
+// "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
+// "size": 29777766,
+// "digest": "sha256:8c7716127147648c1751940b9709b6325f2256290d3201662eca2701cadb2cdf"
+// }
+
+// # gotenberg
```
Comment (thaJeztah) [inline integration/image/inspect_test.go:108]: 🤔

Comment (thaJeztah) [reply integration/image/inspect_test.go:108]: oh! that's the name of the image?

Comment (vvoland) [reply integration/image/inspect_test.go:108]: Yes, see line 93

File: integration/image/inspect_test.go (hunk 1 above)
Comment (vvoland) [reply integration/image/inspect_test.go:115]: A unit test is here: https://github.com/moby/moby/blob/2e3a23c8ec0cbbd6a2e5f7b03cf57de8f3ce33ce/daemon/containerd/image_inspect_test.go#L64-L88

File: daemon/containerd/image_inspect.go [hunk 4]
```diff
@@ -104,29 +98,36 @@ func (i *ImageService) ImageInspect(ctx context.Context, refOrID string, opts im
...
-			Type: img.RootFS.Type,
-		}
-		for _, layer := range img.RootFS.DiffIDs {
-			resp.RootFS.Layers = append(resp.RootFS.Layers, layer.String())
-		}
+	resp.Author = img.Author
+	resp.Architecture = img.Architecture
+	resp.Variant = img.Variant
+	resp.Os = img.OS
+	resp.OsVersion = img.OSVersion
```
Comment (thaJeztah) [inline daemon/containerd/image_inspect.go:116]: Could possibly move some of these together with where we construct the initial response. Did a quick try to see what it would look like; https://github.com/vvoland/moby/compare/c8d-fix-images...thaJeztah:51629_suggestions?expand=1

Comment (vvoland) [reply daemon/containerd/image_inspect.go:116]: We could, not sure if that's better though - currently there's a nicer separation around which fields come from config and it's also in the same place as the special handling for `Comment` and `DiffIDs`.

**Review by thaJeztah — APPROVED** [review]
LGTM
