### PR TITLE
overlay: warn if overlay backing fs doesn't support d_type

### LINKED ISSUE #27358: Centos 7 fails to remove files or directories which are created on build of the image using overlay or overlay2.
**Description**

Centos 7 fails to remove files or directories which are created on build of the image using overlay or overlay2.

**Steps to reproduce the issue:**

**_Scenario 1**_

Try to build the following image

```
FROM centos:6

RUN \
    rm -rf /var/lib/yum/yumdb && /
    echo END
```

**_Scenario 2**_
1. `docker run -it centos`
2. `rm /bin/egrep`
3. `ls -lhart | grep egrep`

**Describe the results you received:**

**_Scenario 1**_

```
Step 1 : FROM centos:latest
 ---> 980e0e4c79ec
Step 2 : RUN rm -rf /var/lib/yum/yumdb && /
 ---> Running in 6d563251bb19
rm: cannot remove '/var/lib/yum/yumdb/a/85e19f5abe37c08a77c42f24624d852a338583bd-acl-2.2.51-12.el7-x86_64': Directory not empty
rm: cannot remove '/var/lib/yum/yumdb/a/b79b02a804fda6e4a10d4c1a68975a323363c2b2-audit-libs-2.4.1-5.el7-x86_64': Directory not empty
rm: cannot remove '/var/lib/yum/yumdb/b/4e3611aa330e1eb8c42401709d03c6b3746b8a75-binutils-2.23.52.0.1-55.el7-x86_64': Directory not empty
rm: cannot remove '/var/lib/yum/yumdb/b/62be349c36ee42d628776a98d2d4b688a9fe4203-bash-4.2.46-20.el7_2-x86_64': Directory not empty
rm: cannot remove '/var/lib/yum/yumdb/b/cdf13cd90ccdecfc009b4cb319471faa995a9fa3-bind-license-9.9.4-29.el7_2.3-noarch': Directory not empty
rm: cannot remove '/var/lib/yum/yumdb/b/ed5c44b6d81784129138935e009a5d71fcca2e22-basesystem-10.0-7.el7.centos-noarch': Directory not empty
rm: cannot remove '/var/lib/yum/yumdb/b/fdf683c5a9852bb4ccf883ff042042923b8cd33f-bzip2-libs-1.0.6-13.el7-x86_64': Directory not empty
rm: cannot remove '/var/lib/yum/yumdb/c/0ec1f87be823c6009e3635d19d9c4302e19d4575-cpio-2.11-24.el7-x86_64': Directory not empty
rm: cannot remove '/var/lib/yum/yumdb/c/57bf8951d232f117c7e19bbcebfc6a40d15f7e78-cryptsetup-libs-1.6.7-1.el7-x86_64': Directory not empty
rm: cannot remove '/var/lib/yum/yumdb/c/5a28ca24d3ccf264d0009576e41df09a4400b499-cracklib-dicts-2.9.0-11.el7-x86_64': Directory not empty
rm: cannot remove '/var/lib/yum/yumdb/c/6e1e6faa0142bab65d7342c0b67b838c9abe07ef-ca-certificates-2015.2.6-70.1.el7_2-noarch': Directory not empty
rm: cannot remove '/var/lib/yum/yumdb/c/75c7de956ef79c6d91a2049523fc4fec931e8990-coreutils-8.22-15.el7_2.1-x86_64': Directory not empty
rm: cannot remove '/var/lib/yum/yumdb/c/7c6a1ce1ee0ff382b98e0f584ad5a5b3ba523785-chkconfig-1.3.61-5.el7_2.1-x86_64': Directory not empty
rm: cannot remove '/var/lib/yum/yumdb/c/988d2338f7dc11e0c5b63c2165b488b80cec883b-centos-release-7-2.1511.el7.centos.2.10-x86_64': Directory not empty
rm: cannot remove '/var/lib/yum/yumdb/c/bc5c88cecec32eb303b45fc24611a2d859603bc9-cyrus-sasl-lib-2.1.26-20.el7_2-x86_64': Directory not empty
rm: cannot remove '/var/lib/yum/yumdb/c/c1a9cb40fa6041bdfb09fb82c63aa8c6b34b3345-cracklib-2.9.0-11.el7-x86_64': Directory not empty
rm: cannot remove '/var/lib/yum/yumdb/c/c1fefbbaf7e3b7e7c756f71d6856faa8c0fae569-curl-7.29.0-25.el7.centos-x86_64': Directory not empty
rm: cannot remove '/var/lib/yum/yumdb/d/067d41965a62020e76eea1686386e17cc178ac63-device-mapper-libs-1.02.107-5.el7_2.5-x86_64': Directory not empty
```

**_Scenario 2**_

```
[root@04f727c9abcc bin]# ls -lhart | grep egrep
ls: cannot access egrep: No such file or directory
??????????? ? ?    ?       ?            ? egrep
-rwxr-xr-x. 1 root root  123 Jul 27  2015 zegrep
lrwxrwxrwx. 1 root root    6 Sep  6 14:00 xzegrep -> xzgrep
```

**Describe the results you expected:**

Files should be removed correctly without errors.

**Output of `docker version`:**

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 21
 Running: 13
 Paused: 0
 Stopped: 8
Images: 19
Server Version: 1.12.2
Storage Driver: overlay2
 Backing Filesystem: xfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.8.1-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.848 GiB
Name: host2
ID: AEWS:D74L:S5HN:F6TX:KSYL:FMBO:KF4C:AMME:CCT6:THJB:2PRH:VW7T
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details:**

VM on Hyper-V

It looks to be a kernel Issue as it is also mentioned here: https://bugs.centos.org/view.php?id=11878&nbn=1. Posted here for visibility

### PR DESCRIPTION
**Pull request by AkihiroSuda**
**\- What I did**

Print a warning if the backing fs for overlay/overlay2 doesn't support `d_type`.
Close #27358 

Considering the discussion at https://github.com/docker/docker/issues/22937, the warning is not treated as an error.
However, I still think it is useful to treat it as an error in some future version (1.14? 1.15?).

Note that recent kernel prints a similar message: https://github.com/torvalds/linux/commit/e7c0b5991dd1be7b6f6dc2b54a15a0f47b64b007
However I think there are advantages to print the message as well in Docker:
- Can support older kernels
- Can provide much more user-friendly information (e.g. "You need to reformat with f_type=1" for XFS)
- Can be switched to an error in future Docker versions

It also shows information in `docker info`.

**\- How I did it**
Please refer to the source of `pkg/fsutils.SupportsDType`.

**\- How to verify it**
For example, XFS with ftype=0 prints this warning.

``` console
$ qemu-img create /xfs-ftype0.img 10G
$ mkfs.xfs -m crc=0 -n ftype=0 /xfs-ftype0.img
$ mount -o loop /xfs-ftype0.img /mnt
$ dockerd -s overlay2 -g /mnt
WARN[0001] overlay2 won't work properly because the backing filesystem xfs is not configured to support d_type. (The backing filesystem seems formatted with f_type=0. Please r
eformat the filesytem with f_type=1.) Note that this warning is planned to be treated as a fatal error in v1.16 

```

The warning should not be shown if ftype=1.

`docker info` shows `f_type Supported` information:

``` console
$ docker info
...
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: false
...
```

**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**

TODO
- [ ] PR for doc (after this PR gets merged)

Signed-off-by: Akihiro Suda suda.akihiro@lab.ntt.co.jp

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
CC @rhvgoyal

**Comment by rhvgoyal** [comment]
If this is just a warning, then kernel is already emitting a warning. How does it help doing another one.

**Comment by dmcgowan** [comment]
> How does it help doing another one.

This was prompted by the issue here #27358. The warning should have been shown in the kernel but not is not somewhere users will look before filing an issue. However I am not convinced that adding a warning to the Docker logs will make this situation much better.

@AkihiroSuda what if instead we added a key mentioning d_type status to the the [status output](https://github.com/docker/docker/blob/master/daemon/graphdriver/overlay/overlay.go#L176) so when issues are filed it is easier to see the problem in the `docker info` output without making users dump their logs. My feeling here is we have to add something to make diagnosis easier, mentioning in the documentation and having warning in the logs can only go so far. I also don't see it as reasonable to someday flip this to an error, the kernel update to make this a warning was done because it had an impact on users, how would that impact change in the future?

**Comment by thaJeztah** [comment]
@dmcgowan I guess we should decide how serious the situation is if someone runs docker without this. If it's a serious issue, then the `overlay` driver should probably be skipped (as "unsupported"), otherwise, we could output it as warning in `docker info` (where we already output various warnings if things are not supported). wdyt?

**Comment by AkihiroSuda** [comment]
Updated PR

* Now warning emits user-friendly guidance for xfs ("The backing filesystem seems formatted with f_type=0. Please reformat with f_type=1.")
* Now `docker info` contains `f_type Supported` information

@rhvgoyal 
* This PR can support older kernel that doesn't print warning
* This PR can provide user-friendly guidance ("The backing filesystem seems formatted with f_type=0. Please reformat with f_type=1.")

@dmcgowan 
Makes sense, I added the information to `docker info`

@thaJeztah 
IMO overlay is almost unuseful without d_type, and it should be an error after some "grace period" (1.14 or 1.15)

**Comment by thaJeztah** [comment]
> IMO overlay is almost unuseful without d_type, and it should be an error after some "grace period" (1.14 or 1.15)

If we are ok with doing that, we should add that in the warning ("running without t_type=0 will no longer be supported in 1.15" for example (needs a better sentence))

**Comment by AkihiroSuda** [comment]
If this should be considered as a "feature deprecation", the warning should remain in v1.13, v1.14. and v.1.15. So the warning will be "running without t_type=0 will no longer be supported in 1.16" in such a case. 
https://docs.docker.com/engine/#feature-deprecation-policy
> Before an existing feature is removed it will be labeled as “deprecated” within the documentation and will remain in Docker for, usually, at least 3 releases. After that time it may be removed.

IMO this is not a "feature deprecation", because "supporting overlay without  d_type"  is a bug rather than a feature.
However, I'm ok to set the grace period (when the warning is changed to an error) to v1.16 so that it won't surprise users.

**Comment by thaJeztah** [comment]
We discussed this, and suggest to:

- make this show up in docker info
- show a warning if it's not supported (as suggested above)
- make this a "fatal" error in 1.16

This allows users that currently run without this being supported to migrate/address the issue

File: pkg/fsutils/fsutils.h [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+static int supports_d_type(const char* path) {
+  int result = 1; // true
+  DIR *d = opendir(path);
+  if (d == NULL) {
+    result = -1;
+    goto ret;
+  }
+  struct dirent *ent;
+  while ((ent = readdir(d)) != NULL) {
+    if (ent->d_type == DT_UNKNOWN) {
```
Comment (tonistiigi) [inline pkg/fsutils/fsutils.h]: It should be possible to do this without c. https://golang.org/pkg/syscall/#Dirent is exposed in go.

Comment (AkihiroSuda) [inline pkg/fsutils/fsutils.h]: done

**Comment by AkihiroSuda** [comment]
@thaJeztah thank you for making the discussion. 

Updated PR and now the warning message is like this:
```
WARN[0001] overlay won't work properly because the backing filesystem xfs is not configured to support d_type. (The backing filesystem seems formatted with f_type=0. Please r
eformat the filesytem with f_type=1.) Note that this warning is planned to be treated as a fatal error in v1.16 .
```

**Comment by thaJeztah** [comment]
Trying to see if we can make this more consistent with the devmapper dev-sync message;

```
devmapper: Udev sync is not supported. This will lead to data loss and unexpected
behavior. Install a dynamic binary to use devicemapper or select a different storage
driver. For more information, see https://docs.docker.com/engine/reference/commandline/daemon/#daemon-storage-driver-option

```

Perhaps (wrapped for readability):

```
WARN[0001] overlay2: the backing xfs filesystem is configured without d_type support,
which leads to incorrect behavior. Reformat the filesytem with f_type=1 to fix this
issue. Running without d_type support will no longer be supported in Docker 1.16.
```

@mstanleyjones perhaps you have suggestions?

**Comment by AkihiroSuda** [comment]
Updated PR according to the suggestion from @mstanleyjones

**Review by mdlinville — APPROVED** [review]
Docs LGTM

**Comment by thaJeztah** [comment]
ping @justincormack @tonistiigi PTAL

File: pkg/fsutils/fsutils_linux.go [hunk 2]
```diff
@@ -0,0 +1,90 @@
...
+	visited := 0
+	supportsDType := true
+	walkFn := func(ent *syscall.Dirent) bool {
+		visited++
+		if ent.Type == syscall.DT_UNKNOWN {
+			supportsDType = false
+			// stop walking
+			return true
+		}
+		// continue walking
```
Comment (dmcgowan) [inline pkg/fsutils/fsutils_linux.go]: What is the reasoning behind checking multiple files? Is there a case where there can be a mix of unknown type and known types?

Comment (AkihiroSuda) [inline pkg/fsutils/fsutils_linux.go]: I agree that checking a single file is enough in practice.

But I wonder theoretically there can be a mix of unknown type and known types in some filesystem, so I wrote the code to check multiple files here. ( it should be very lightweight operation)

Please let me know if I should fix this.

File: pkg/fsutils/fsutils_linux.go [hunk 3]
```diff
@@ -0,0 +1,90 @@
...
+	if err = walkdir(path, walkFn); err != nil {
+		return false, err
+	}
+	if visited == 0 {
+		return false, fmt.Errorf("did not hit any dirent during walking %s", path)
+	}
+	return supportsDType, nil
+}
+
+func walkdir(path string, walkFn func(*syscall.Dirent) bool) error {
```
Comment (AkihiroSuda) [inline pkg/fsutils/fsutils_linux.go]: self-nit: `walk` maybe misleading because it is not recursive.
I'll try to change the terminology

Comment (AkihiroSuda) [inline pkg/fsutils/fsutils_linux.go]: done

**Comment by AkihiroSuda** [comment]
rebased to master
@justincormack @tonistiigi PTAL

**Comment by vieux** [comment]
ping @justincormack @tonistiigi

File: pkg/fsutils/fsutils_linux_test.go [hunk 4]
```diff
@@ -0,0 +1,90 @@
...
+
+func loUnmount(t *testing.T, mountpoint string) {
+	if err := syscall.Unmount(mountpoint, 0); err != nil {
+		t.Fatal(err)
+	}
+}
+
+// prepare creates an empty sparse image and a directory for mounting,
+// under tmpDir (can be empty)
+func prepare(t *testing.T, tmpDir string, imageSize int64) (string, string) {
```
Comment (AkihiroSuda) [inline pkg/fsutils/fsutils_linux_test.go]: done

**Comment by tonistiigi** [comment]
LGTM

**Comment by dmcgowan** [comment]
LGTM
