### PR TITLE
make xattr EPERM non-fatal in createTarFile

### LINKED ISSUE #37956: ChromeOS: ApplyLayer exit status 1: operation not permitted
**Description**

On ChromeOS, some (not all) docker images fail to be pulled. Ubuntu works, centos fails. `docker image inspect` (on another box) shows that both ubuntu and centos use overlay2?

A custom runc is in use, per [these instructions](https://www.reddit.com/r/Crostini/comments/9jabhq/docker_now_working/).

**Describe the results you received:**

```bash
$ sudo docker pull centos
Using default tag: latest
latest: Pulling from library/centos
256b176beaff: Extracting [==================================================>]  74.69MB/74.69MB
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: operation not permitted
```

**Output of `docker version`:**

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:18 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:22:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 68
 Running: 0
 Paused: 0
 Stopped: 68
Images: 49
Server Version: 18.06.1-ce
Storage Driver: btrfs
 Build Version: Btrfs v4.7.3
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc runc-chromeos
Default Runtime: runc-chromeos
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: a0b7d6dc09b58d2f44dd61c304a66d9249e56c8f (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.71-07583-g022708b4bb18
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 4.84GiB
Name: penguin
ID: UQLF:OLQL:GZVZ:VHFU:6NHC:OAHA:OP25:BJPQ:SJYL:YS5U:WPDP:PGCC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

ChromeOS, custom runc.

### PR DESCRIPTION
**Pull request by dhiltonp**
fixes #37956

**- What I did**
Centos containers could not be pulled on ChromeOS. I traced the issue to an xattr permission issue, and followed the existing exemption pattern used for AUFS.

not having permissions to change xattrs is no longer fatal

### CODE REVIEW

File: pkg/archive/archive.go [hunk 1]
```diff
@@ -660,11 +660,13 @@ func createTarFile(path, extractDir string, hdr *tar.Header, reader io.Reader, L
 	var errors []string
 	for key, value := range hdr.Xattrs {
 		if err := system.Lsetxattr(path, key, []byte(value), 0); err != nil {
-			if err == syscall.ENOTSUP {
+			if err == syscall.ENOTSUP || err == syscall.EPERM {
```
Comment (AkihiroSuda) [inline pkg/archive/archive.go]: `if err == syscall.ENOTSUP || (rsystem.RunningInUserNS() && err == syscall.EPERM)`  ?

**Review by AkihiroSuda — APPROVED** [review]
LGTM, just one nit

**Review by AkihiroSuda — APPROVED** [review]

**Comment by kolyshkin** [comment]
SGTM

**Review by tonistiigi — APPROVED** [review]

**Review by AntaresS — APPROVED** [review]
LGTM 🐈

File: pkg/archive/archive.go (hunk 1 above)
Comment (AkihiroSuda) [reply pkg/archive/archive.go]: @cyphar @giuseppe thought?

(either way, the current libcontainer implementation is wrong, because it is also possible to create userns with the full 4G map)

Comment (AkihiroSuda) [reply pkg/archive/archive.go]: Off-topic: is it possible to run any ChromeOS VM with the container feature enabled on macOS?

I tried https://developer.android.com/topic/arc/emulator but I could't enable the "Linux" feature, because it didn't allow me to upgrade the OS to the "Beta"

Comment (dhiltonp) [reply pkg/archive/archive.go]: I'd look into running CloudReady in a VM, [they added experimental Linux support recently](https://neverware.zendesk.com/hc/en-us/articles/360001737547-Experimental-Crostini-Support-64bit-Home-Edition-?mobile_site=true).

Linux is actually now available on the stable channel (ChromeOS v69). If you can update your Pixel image to v69, you should be able to enable the Linux (beta) *feature*  in your Settings (yes, it's confusing).

Comment (AkihiroSuda) [reply pkg/archive/archive.go]: thanks, it looks like Android SDK only supports ChromeOS v67. will try cloudready.

**Comment by Chekote** [comment]
I'm experiencing this bug on Docker CE 18.09.1 build 4c52b90 on ChromeOS using Crostini. How do I determine when a release will be published including this fix? Is there any way for me to use this fix before its official release?
