### PR TITLE
ProcessWord support UTF-8

### LINKED ISSUE #16793: docker client renders utf-8 encoded characters incorrectly
```dockerfile
FROM fedora
LABEL x Ý
```

```
$ docker build .
Sending build context to Docker daemon  2.56 kB
Step 0 : FROM fedora
 ---> e44d11f3b819
Step 1 : LABEL x Ý
 ---> Running in 67ae37fb9549
 ---> d443582a15b5
Removing intermediate container 67ae37fb9549
Successfully built d443582a15b5
```

`docker build` prints `Ý` correctly. `inspect` doesn't:

```
"Labels": {
    "x": "Ã"
}
```

So I tried to fetch raw data from engine via `docker-py`:

```
  u'Labels': {u'x': u'\xc3\x9d'},
```

UTF-8 encoded acting as unicode. That's not right. But the character is encoded correctly:

```ipython
In [3]: print b"\xc3\x9d"
Ý
```
```
$ docker info
Containers: 31
Images: 331
Storage Driver: btrfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.7-300.fc22.x86_64
Operating System: Fedora 22 (Twenty Two)
CPUs: 4
Total Memory: 7.682 GiB
Name: quahog
ID: PD35:TRT5:VF5I:YQBZ:WR5T:DDLP:GAGB:M374:EK7G:ITUG:6PN3:OCCI
$ docker version
Client:
 Version:      1.8.1.fc22
 API version:  1.20
 Package Version: docker-1.8.1-3.git32b8b25.fc22.x86_64
 Go version:   go1.4.2
 Git commit:   32b8b25/1.8.1
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1.fc22
 API version:  1.20
 Package Version:
 Go version:   go1.4.2
 Git commit:   32b8b25/1.8.1
 Built:
 OS/Arch:      linux/amd64
$ uname -a
Linux quahog 4.0.7-300.fc22.x86_64 #1 SMP Mon Jun 29 22:15:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by daehyeok**
modified PorcessWord to working normally for UTF-8 strings.
fixed #16793 

Signed-off-by: Daehyeok Mun daehyeok@gmail.com

### CODE REVIEW

**Comment by duglin** [comment]
nice. can we get some testcases?

**Comment by calavera** [comment]
as @duglin says, having tests would be awesome.

**Comment by daehyeok** [comment]
Sorry, I forgot to testing..... I added test case for UTF-8 strings using Korean words "안녕하세요" (it's mean hello). I write new test case based on previous test case.

**Comment by vdemeester** [comment]
Oh Cool ! *Unicode all the things 🙌*

ありがとう
고맙습니다

File: builder/dockerfile/shell_parser.go [hunk 1]
```diff
@@ -58,14 +62,21 @@ func (sw *shellWord) processStopOn(stopChar rune) (string, error) {
...
-			ch = sw.next()
+			ch = sw.scanner.Next()
+
 			if ch == '\\' {
 				// '\' escapes, except end of line
-				ch = sw.next()
+
+				ch = sw.scanner.Next()
+
 				if ch == '\000' {
```
Comment (duglin) [inline builder/dockerfile/shell_parser.go]: Do we still need to check for \000 ?

File: builder/dockerfile/shell_parser.go [hunk 2]
```diff
@@ -73,36 +84,23 @@ func (sw *shellWord) processStopOn(stopChar rune) (string, error) {
...
-	return ch
-}
-
 func (sw *shellWord) processSingleQuote() (string, error) {
 	// All chars between single quotes are taken as-is
 	// Note, you can't escape '
 	var result string
 
-	sw.next()
+	if sw.scanner.Next() == scanner.EOF {
```
Comment (duglin) [inline builder/dockerfile/shell_parser.go]: I think this will never be true - I think Next() will always return the starting single quote - which is why we just ignored the return in the old code. So I think you can remove the "if" check and just call sw.scanner.Next().

File: builder/dockerfile/shell_parser.go [hunk 3]
```diff
@@ -73,36 +84,23 @@ func (sw *shellWord) processStopOn(stopChar rune) (string, error) {
...
+		return result, nil
+	}
 
 	for {
-		ch := sw.next()
-		if ch == '\000' || ch == '\'' {
+		ch := sw.scanner.Next()
+		if ch == '\000' || ch == '\'' || ch == scanner.EOF {
```
Comment (duglin) [inline builder/dockerfile/shell_parser.go]: Will Next() ever return \000 ?  If not we can remove that from the "if".  If so, I can't help but think we should treat it like any other char and keep going.

**Comment by duglin** [comment]
thanks for the tests - very nice.
Just a few comments/questions on the code.

**Comment by daehyeok** [comment]
@duglin you right. I confused \000 need for multiline .... I remove/rewrite code related with \000

**Comment by duglin** [comment]
@daehyeok please squash your commits
Other than that, LGTM

**Comment by daehyeok** [comment]
@duglin squashed, Thanks

**Comment by vdemeester** [comment]
LGTM 🐰

**Comment by vdemeester** [comment]
Merging 😍
ping @thaJeztah putting impact/changelog maybe ?

**Comment by thaJeztah** [comment]
Yah, we can do that
