### PR TITLE
do not ignore "volume in use" errors when force-delete

### LINKED ISSUE #31446: volume rm -f allows removing volume that is in use
As reported by @intesar in https://github.com/docker/docker/issues/31436#issuecomment-283206741, `docker volume rm -f` allows deleting volume that are in use. Steps to reproduce are below, but I suspect that the reference-counter is always updated if `-f` is used, even if removing the volume isn't actually successful.

I was able to reproduce both on docker 1.13.1, and on current master (https://github.com/docker/docker/commit/7298941)

**Reproduction steps:**

Create a volume;

```bash
$ docker volume create my-volume
my-volume
```

Start a container using that volume and add some files to the volume

```bash
$ docker run -dit --name my-container -v my-volume:/volume busybox sh -c 'touch /volume/one /volume/two && exec /bin/sh'
c76a270145efd47b4363554b67fadf74e6f4fa05daf045023a93e2366b38e65e
```

Try to remove the volume;

```bash
$ docker volume rm my-volume
Error response from daemon: Unable to remove volume, volume still in use: remove my-volume: volume is in use - [c76a270145efd47b4363554b67fadf74e6f4fa05daf045023a93e2366b38e65e]
```

Try to remove the volume with `-f`;

```bash
$ docker volume rm -f my-volume
my-volume
```

This _looks_ to work, but doesn't actually remove the volume;

```bash
$ docker volume ls
DRIVER              VOLUME NAME
local               my-volume

$ docker exec my-container sh -c 'ls -la /volume/'

total 8
drwxr-xr-x    2 root     root          4096 Mar  1 11:06 .
drwxr-xr-x   19 root     root          4096 Mar  1 11:06 ..
-rw-r--r--    1 root     root             0 Mar  1 11:06 one
-rw-r--r--    1 root     root             0 Mar  1 11:06 two
```

However, running `docker volume rm` a _second_ time, the remove succeeds (no `-f` needed);

```bash
$ docker volume rm my-volume
my-volume
```

The volume is removed;

```
$ docker volume ls
DRIVER              VOLUME NAME
```

And no longer attached to the container;

```bash
$ docker exec my-container sh -c 'ls -la /volume/'
total 0
```

### PR DESCRIPTION
**Pull request by thaJeztah**
fixes https://github.com/docker/docker/issues/31446

When using `docker volume rm -f`, all errors were ignored, and volumes where Purged, even if they were still in use by a container. As a result, repeated calls to `docker volume rm -f` actually removed the volume.

The `-f` option was implemented to ignore errors in case a volume was already removed out-of-band by a volume driver plugin.

This patch changes the remove function to not ignore "volume in use" errors if `-f` is used. Other errors are still ignored as before.

**- How to verify it**

```
$ docker volume create my-volume
my-volume

$ docker create -v my-volume:/volume busybox

# then run `docker volume rm -f` multiple times; it should produce an error each time
$ docker volume rm my-volume
$ docker volume rm my-volume

# the volume should still be present
$ docker volume ls
```

**- Description for the changelog**

Fix a bug where `docker volume rm -f` was removing volumes that were still in use by a container.

**- A picture of a cute animal (not mandatory but encouraged)**

loving-mother-cow-and-calf1

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

File: integration-cli/docker_cli_volume_test.go [hunk 1]
```diff
@@ -431,6 +431,30 @@ func (s *DockerSuite) TestVolumeCLIRmForce(c *check.C) {
...
+	prefix, slash := getPrefixAndSlashFromDaemonPlatform()
+	dockerCmd(c, "create", "-v", "testvolume:"+prefix+slash+"foo", "busybox")
+
+	_, _, err := dockerCmdWithError("volume", "rm", "-f", name)
+	c.Assert(err, check.NotNil)
+	c.Assert(err.Error(), checker.Contains, "volume is in use")
+	out, _ = dockerCmd(c, "volume", "ls")
+	c.Assert(out, checker.Contains, name)
+
+	_, _, err = dockerCmdWithError("volume", "rm", "-f", name)
```
Comment (cpuguy83) [inline integration-cli/docker_cli_volume_test.go]: how come it's checking twice?

Comment (cpuguy83) [inline integration-cli/docker_cli_volume_test.go]: Would also be good to check that once the container is removed the volume rm works.

File: daemon/delete.go [hunk 2]
```diff
@@ -157,11 +161,7 @@ func (daemon *Daemon) volumeRm(name string) error {
 	}
 
 	if err := daemon.volumes.Remove(v); err != nil {
-		if volumestore.IsInUse(err) {
-			err := fmt.Errorf("Unable to remove volume, volume still in use: %v", err)
-			return errors.NewRequestConflictError(err)
-		}
-		return fmt.Errorf("Error while removing volume %s: %v", name, err)
+		return errors.Wrap(err, "Unable to remove volume")
```
Comment (cpuguy83) [inline daemon/delete.go]: This should really be lower cased

**Review by cpuguy83 — CHANGES_REQUESTED** [review]

File: integration-cli/docker_cli_volume_test.go (hunk 1 above)
Comment (thaJeztah) [inline integration-cli/docker_cli_volume_test.go]: Checking it twice, because that's how I reproduced the original issue; first `rm -f` "passed", but the volume was still present in `volume ls`. The second `rm -f` actually removed the volume (also from the list).

Was in doubt if I should add the final remove. Small change, so I can add that yes

File: daemon/delete.go (hunk 2 above)
Comment (thaJeztah) [inline daemon/delete.go]: LOL, I had it lowercase, but saw all other errors were with uppercase, so changed it; I'll update that

**Comment by thaJeztah** [comment]
updated. ping @cpuguy83 PTAL

**Comment by cpuguy83** [comment]
```
15:17:33  - integration-cli/docker_cli_volume_test.go
15:17:33 
15:17:33 Please reformat the above files using "gofmt -s -w" and commit the result.
```

**Comment by thaJeztah** [comment]
arg. looks like gogland doesn't format correctly, let me check my preferences again, and otherwise open a bugreport there.

anyway, fixed :blush:

**Comment by thaJeztah** [comment]
Test passed on Windows

```
17:02:49 PASS: docker_cli_volume_test.go:436: DockerSuite.TestVolumeCLIRmForceInUse	0.429s
```

Failure looks unrelated (flaky);

```
16:36:19 ----------------------------------------------------------------------
16:36:19 FAIL: docker_api_logs_test.go:15: DockerSuite.TestLogsAPIWithStdout
16:36:19 
16:36:19 docker_api_logs_test.go:50:
16:36:19     c.Fatal("timeout waiting for logs to exit")
16:36:19 ... Error: timeout waiting for logs to exit
16:36:19 
```

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
cherry-picked into 17.03.1 through https://github.com/docker/docker/pull/31754
