### PR TITLE
healthcheck: do not interpret exit code 2 as "starting"

### LINKED ISSUE #24396: Health checks are hard to implement because of return codes
I mentioned this during the review but it didn't get addressed so reposting this as an issue.

We ask health checks to return `0` if they were successful (good), `1` if the failed (good) and `2` if the container is still initializing (weird).

A health check scripts has no way to know whether it's in initialization period or not. This basically means that rather than being a simple command, a proper health check has to keep state and implement its own grace period.

I propose we get rid of `2`. Actually, we get rid of all return codes - in the `HEALTHCHECK` instruction we could provide what a "good" exit code is (and we default to 0).

In order to achieve the "it's still initializing" behavior, we put a grace period.

/cc @stevvooe @icecrime @tiborvass @runshenzhu

### PR DESCRIPTION
**Pull request by tiborvass**
Instead reserve exit code 2 to be future proof, document that it should
not be used. Implementation-wise, it is considered as unhealthy, but
users should not rely on this as it may change in the future.

Signed-off-by: Tibor Vass tibor@docker.com

Fixes #24396

### CODE REVIEW

**Comment by tiborvass** [comment]
Ping @talex5 @tianon @justincormack @aluzzardi

**Comment by tiborvass** [comment]
I will do proper vendoring once it is in code review.

**Comment by thaJeztah** [comment]
@tiborvass tests are failing;

```
8:08:47 --- FAIL: TestHealthStates (0.00s)
18:08:47 	health_test.go:83: Expecting starting, but got "unhealthy"
18:08:47 	health_test.go:30: Expecting event "health_status: healthy", but got "health_status: unhealthy"
18:08:47 	health_test.go:30: Expecting event "health_status: unhealthy", but got "health_status: healthy"
18:08:47 	health_test.go:30: Expecting event "health_status: healthy", but got "health_status: unhealthy"
```

**Comment by tiborvass** [comment]
Yeah I know i'm fixing them, but something is weird.

**Comment by justincormack** [comment]
Hmm, so 2 is reserved to be considered (in effect) healthy in future, but currently means unhealthy...

**Comment by talex5** [comment]
@aluzzardi can you confirm that telling probe authors they are no longer allowed to return exit code 2 solves your problem that "Health checks are hard to implement because of return codes" (#24396)?

**Comment by justincormack** [comment]
I don't think we should reserve 2, just remove it. If we add a starting state it should be a different interface, leaving health checks for just good/bad.

**Comment by tiborvass** [comment]
@justincormack I reserved `2` only in the documentation for future proofing.

File: daemon/health_test.go [hunk 1]
```diff
@@ -72,14 +72,15 @@ func TestHealthStates(t *testing.T) {
 	handleResult(c.State.StartedAt.Add(3*time.Second), 1)
 	expect("health_status: unhealthy")
 
-	// starting -> starting -> starting ->
-	// healthy -> starting (invalid transition)
+	// starting -> reserved -> reserved ->
+	// healthy -> reserved
```
Comment (justincormack) [inline daemon/health_test.go]: this is confusing! Maybe delete these comments?

Comment (tiborvass) [inline daemon/health_test.go]: along with the corresponding test?

Comment (justincormack) [inline daemon/health_test.go]: yes, its all reserved, so we should not test

**Comment by justincormack** [comment]
LGTM

**Comment by vdemeester** [comment]
@tiborvass engine-api vendored, you can update 👼

**Comment by vdemeester** [comment]
Otherwise, LGTM 🐸
