### PR TITLE
Block pulling Windows images on non-Windows daemons

### LINKED ISSUE #28892: Docker pull microsoft/nanoserver on Linux daemon fails with "unknown blob"
**Description**

When a Linux daemon attempts to pull a Windows based image, it fails to download the base layer. It attempts to retry multiple times before failing with the error message "unknown blob". 

**Steps to reproduce the issue:**
Targeting a Linux daemon:
1. docker pull microsoft/nanoserver

**Describe the results you received:**

Multiple retries on both layers followed by:
unknown blob

**Describe the results you expected:**

An error message about the platform being incompatible with the image.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

This occurs on 1.12 and 1.13

**Output of `docker info`:**

Any Linux based daemon will repro

### PR DESCRIPTION
**Pull request by darstahl**
This is an alternative solution to https://github.com/docker/docker/pull/28903

**- What I did**

fixes #28892

Block pulling Windows images on Linux daemons.

**- How I did it**

If the listed OS of an image's config is Windows, but the current daemon platform is not Windows, fail to download the image.

**- How to verify it**

Pull `microsoft/nanoserver` on a Linux daemon. See test that checks this.

**- Description for the changelog**

Block pulling of Windows images on a non-windows daemon.

Signed-off-by: Darren Stahl <darst@microsoft.com>

/cc @jhowardmsft @jstarks

### CODE REVIEW

**Comment by aaronlehmann** [comment]
Instead of downloading the config before starting to download the layers (which will add a noticeable delay), how running `p.config.DownloadManager.Download` in a goroutine and aborting it by canceling the context if the config turns out to be incompatible?

**Comment by darrenstahlmsft** [comment]
@aaronlehmann That can't be done on Windows, as some filenames in Linux images are not valid in NTFS resulting in a failure mid download. I'm not sure if it can be done in the Linux case, since the Linux daemon is not aware of foreign layers, the failure is occurring during download, rather than when attempting to run the resulting image. I can try it on Linux pulling a Windows image, but even if it works, it would be diverging the handling between platforms.

**Comment by aaronlehmann** [comment]
If the problem is foreign layers, those are easy to detect before downloading the layers. We could abort the pull if the platform is Linux and any of the descriptors in the manifest has a media type indiciating a foreign layer. That wouldn't require downloading the image config before starting the layer downloads.

**Comment by darrenstahlmsft** [comment]
The problem isn't only the foreign layers. It just happens that all Windows images have at least one foreign layer, since Windows images must be based off one of the two base images, both of which contain foreign layers. Downloading both the image config and the layers at the same time is a race between which would fail first, and produce a different error depending on which download wins.

I initially avoided this solution (reading image config before layer download), due to the expected performance impact, and did what you are suggesting (checking the layer descriptor before attempting to download a foreign layer). See https://github.com/docker/docker/pull/28903. It was suggested there to fail earlier by doing the same checks that Windows already does on Linux. Both of these solve the same problem, but have different drawbacks.

**Comment by thaJeztah** [comment]
ping @aaronlehmann @stevvooe any way to get this PR, or https://github.com/docker/docker/issues/28903, moving again?

**Comment by aaronlehmann** [comment]
My preference here is for something like this (untested, only meant to illustrate the idea):

https://github.com/aaronlehmann/docker/tree/block-wrong-os

This runs the download manager in a separate goroutine, so the `pullSchema2` function can abort the pull as soon as the config is downloaded, if that config specifies the wrong platform. This doesn't require fully downloading the config before starting the layer downloads on Linux.

The NTFS issue wouldn't be a factor because Windows daemons always download and check the config first. The foreign layer issue on Linux could be solved by adding a check for foreign layers in the loop over `mfst.Layers` at the top of `pullSchema2`, before any of these downloads start. This will let us fail even faster than when trying to download a layer.

**Comment by AkihiroSuda** [comment]
@darrenstahlmsft 

WDYT about @aaronlehmann 's comment?

**Comment by LK4D4** [comment]
ping @darrenstahlmsft

**Comment by thaJeztah** [comment]
also ping @stevvooe PTAL

**Comment by darrenstahlmsft** [comment]
Updated to be similar to the commit by @aaronlehmann except that in the case of an error downloading the layer, the config download is not cancelled so that the resulting error message takes priority over the layer download failure.

I think that lets us remove the serialization of the Windows config as well. I've left that for a follow-up PR though.

**Comment by aaronlehmann** [comment]
I see that `TestEventsPluginOps` timed out on both janky and experimental, so I suspect this is causing some problem with pulling plugins.

File: integration-cli/docker_cli_pull_test.go [hunk 1]
```diff
@@ -272,3 +272,10 @@ func (s *DockerSuite) TestPullLinuxImageFailsOnWindows(c *check.C) {
 	_, _, err := dockerCmdWithError("pull", "ubuntu")
 	c.Assert(err.Error(), checker.Contains, "cannot be used on this platform")
 }
+
+// Regression test for https://github.com/docker/docker/issues/28892
+func (s *DockerSuite) TestPullWindowsImageFailsOnLinux(c *check.C) {
+	testRequires(c, DaemonIsLinux, Network)
+	_, _, err := dockerCmdWithError("pull", "microsoft/nanoserver")
```
Comment (aaronlehmann) [inline integration-cli/docker_cli_pull_test.go]: Ideally we'd serve a minimal Windows image from a local registry instead of depending on Docker Hub. I just filed https://github.com/docker/docker/issues/30626 about something similar.

This is probably outside the scope of this PR though. I think the `download-frozen-image-v2.sh` script in the `Dockerfile` is capable of downloading the image at `docker build` time, but it would take some extra scripting work to load this image into a local registry without the use of `docker pull` / `docker push`.

File: distribution/pull_v2.go [hunk 2]
```diff
@@ -574,41 +576,50 @@ func (p *v2Puller) pullSchema2(ctx context.Context, ref reference.Named, mfst *s
...
 		}
+	}
 
-		if configRootFS == nil {
-			return "", "", errRootFSInvalid
-		}
+	select {
+	case <-downloadsDone:
+	case err = <-errChan:
+		cancel()
```
Comment (aaronlehmann) [inline distribution/pull_v2.go]: Instead of calling `cancel` here, lets add `defer cancel()` after the call to `WithCancel`. We should be making sure to always cancel the context when returning anyway, as this releases the resources associated with it.

File: distribution/pull_v2.go [hunk 3]
```diff
@@ -552,6 +553,7 @@ func (p *v2Puller) pullSchema2(ctx context.Context, ref reference.Named, mfst *s
 		configJSON       []byte        // raw serialized image config
 		downloadedRootFS *image.RootFS // rootFS from registered layers
 		configRootFS     *image.RootFS // rootFS from configuration
+		release          func()        // relase resources from rootFS download
```
Comment (aaronlehmann) [inline distribution/pull_v2.go]: typo: "relase"

**Comment by aaronlehmann** [comment]
This looks like the right approach to me. Moving to code review.

Let me know if I can be of any help in tracking down the plugin test issue. Also pinging @dmcgowan who converted plugins to use the `pull_v2` code.

**Comment by darrenstahlmsft** [comment]
Fixed the plugin error, but now it's failing on TestDaemonNoSpaceLeftOnDeviceError, which still seems related. I'll take a look at that tomorrow.

File: distribution/pull_v2.go [hunk 4]
```diff
@@ -533,7 +533,8 @@ func (p *v2Puller) pullSchema2(ctx context.Context, ref reference.Named, mfst *s
 	}
 
 	configChan := make(chan []byte, 1)
-	errChan := make(chan error, 1)
+	errChan := make(chan error, 2)
+	downloadsDone := make(chan error, 1)
```
Comment (aaronlehmann) [inline distribution/pull_v2.go]: This can be `downloadsDone := make(chan struct{})`, since no data is ever conveyed over it.

**Comment by aaronlehmann** [comment]
Ah, I think I see the problem that is causing `TestDaemonNoSpaceLeftOnDeviceError` to hang.

`receiveConfig` may get an error from the layer downloads on `errChan`, and afterwards the `select` below `receiveConfig` will wait for activity on `downloadsDone` or `errChan`, but neither will happen, because the downloading goroutine has already returned and its message on `errChan` was swallowed up by `receiveConfig`.

One way to fix this would be to use separate error channels for layer downloads and the config retrieval.

File: distribution/pull_v2.go (hunk 4 above)
Comment (darrenstahlmsft) [inline distribution/pull_v2.go]: Huh, I was certain I'd made it a struct{} chan in the first place, oops... Fixed.

**Comment by darrenstahlmsft** [comment]
Good catch @aaronlehmann. Fixed the hang.

File: distribution/config.go [hunk 5]
```diff
@@ -142,9 +142,12 @@ func (s *imageConfigStore) RootFSFromConfig(c []byte) (*image.RootFS, error) {
 		return nil, err
 	}
 
-	// fail immediately on windows
+	// fail immediately on Windows when downloading a non-Windows image
+	// and vice versa
 	if runtime.GOOS == "windows" && unmarshalledConfig.OS == "linux" {
 		return nil, fmt.Errorf("image operating system %q cannot be used on this platform", unmarshalledConfig.OS)
+	} else if runtime.GOOS != "windows" && unmarshalledConfig.OS == "windows" {
```
Comment (AkihiroSuda) [inline distribution/config.go]: why not just check `runtime.GOOS != unmarshelledConfig.OS` here?
(Although we can support `runtime.GOOS == "freebsd" && unmarshalledConfig.OS == "linux"` in future :smile:)

File: integration-cli/docker_cli_pull_test.go (hunk 1 above)
Comment (AkihiroSuda) [inline integration-cli/docker_cli_pull_test.go]: It would be even better to use some plain "scratch" image with Windows config, instead of downloading 333MB nanoserver image.

File: distribution/config.go (hunk 5 above)
Comment (aaronlehmann) [inline distribution/config.go]: > why not just check `runtime.GOOS != unmarshelledConfig.OS` here?

I'm afraid this might have some unintended consequences. For example, what if there are images out there built with nonstandard tools that don't set the `OS` field? For now I think it's best to explicitly check for incompatible configurations.

Comment (AkihiroSuda) [inline distribution/config.go]: ok

File: integration-cli/docker_cli_pull_test.go (hunk 1 above)
Comment (jhowardmsft) [inline integration-cli/docker_cli_pull_test.go]: @AkihiroSuda There is no such thing. Nanoserver is the smallest Windows image available.

**Comment by runcom** [comment]
LGTM ping @anusha-ragunathan @vdemeester

**Review by vdemeester — APPROVED** [review]
LGTM 🐸
