### PR TITLE
Fix daemon startup on a no-IPv6 host

### LINKED ISSUE #49504: 28.0.0: ipv6 cannot be disable, failed to load daemon.
### Description

For security reasons, I disable ipv6 in the Linux kernel with the grub command "ipv6.disable=1". In the past I have set `"ipv6": false` in /etc/docker/daemon.json and have no problems running the docker daemon.
Today when upgrading to 28.0.0 (on debian 12) the daemon refuses to start with the following error
```
dockerd[2681]: time="2025-02-20T11:35:27.306094149Z" level=warning msg="Failed to add inter-network communication rule" error=" (iptables failed: ip6tables --wait -t filter -A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2: ip6tables v1.8.9 (legacy): can't initialize ip6tables table `filter': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n (exit status 3))"
dockerd[2681]: time="2025-02-20T11:35:27.345646032Z" level=info msg="stopping event stream following graceful shutdown" error="<nil>" module=libcontainerd namespace=moby
dockerd[2681]: failed to start daemon: Error initializing network controller: error creating default "bridge" network: add inter-network communication rule:  (iptables failed: ip6tables --wait -t filter -A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2: ip6tables v1.8.9 (legacy): can't initialize ip6tables table `filter': Address family not supported by protocol
systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
```

### Reproduce

1. disable ipv6 in kernel
2. use iptables as firewall
3. docker service crash even if ipv6 is disable in daemon option.
### Expected behavior

If "ipv6": false is set in daemon.json, it should never try to load the ipv6 rule, like before.

### docker version

```bash
Client: Docker Engine - Community
 Version:           28.0.0
 API version:       1.48
 Go version:        go1.23.6
 Git commit:        f9ced58
 Built:             Wed Feb 19 22:10:43 2025
 OS/Arch:           linux/amd64
 Context:           default
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    28.0.0
 Context:    default
 Debug Mode: false

Server:
errors pretty printing info
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by robmry**
**- What I did**

- fix https://github.com/moby/moby/issues/49504

With ip6tables enabled (by default), the daemon should start on a host with IPv6 disabled - then error if IPv6 network creation is attempted.

In 28.0.0, it fails with ...

```
failed to start daemon: Error initializing network controller: error creating default "bridge" network: add inter-network communication rule:  (iptables failed: ip6tables --wait -t filter -A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2: ip6tables v1.8.9 (nf_tables): Chain 'DOCKER-ISOLATION-STAGE-2' does not exist
Try `ip6tables -h' or 'ip6tables --help' for more information.
 (exit status 2))
```

**- How I did it**

In 27.x, the error wasn't propagated properly, a `nil` was returned following an attempt to roll-back the rule that wasn't created, so startup continued. Commit https://github.com/moby/moby/commit/255fff4acd242c50903148c3641c9bf9bcf38fdf fixed the error propagation, breaking startup in this case.

The underlying problem was a missing check that the network had IPv6 enabled for INC rule setup. So, added that check.

**- How to verify it**

Start the daemon on host with IPv6 disabled.

**- Human readable description for the release notes**
```markdown changelog
Allow daemon startup on a host with IPv6 disabled without requiring `--ip6tables=false`.
```

### CODE REVIEW

**Review by akerouanton — APPROVED** [review]

File: libnetwork/drivers/bridge/bridge_linux.go [hunk 1]
```diff
@@ -478,12 +478,12 @@ func (n *bridgeNetwork) isolateNetwork(enable bool) error {
 	}
 
 	// Install the rules to isolate this network against each of the other networks
-	if n.driver.config.EnableIPTables {
+	if n.driver.config.EnableIPTables && (!enable || n.config.EnableIPv4) {
```
Comment (thaJeztah) [inline libnetwork/drivers/bridge/bridge_linux.go:481]: Should we use `thisConfig` here? (also in the other branch below)?


I must say that the 3 booleans combined make it hard to grasp what exactly the conditions are (perhaps a comment or breaking to a separate condition could help 🤔);

- We only manipulate if IP(6)tables is enabled
- And we want to disable, or (explicitly) enable

Is there a case where `n.config.EnableIPv4 = false` means we must disable things?

Comment (robmry) [reply libnetwork/drivers/bridge/bridge_linux.go:481]: I'll have a look ... but the intention is to only add the rules if `iptables` is enabled, and the network has IPv4 enabled.

But, in case the rule was created by an older version, it's unconditionally deleted if `iptables` is enabled (because it was unconditionally added before the `EnableIPv4` check was added).

Comment (robmry) [reply libnetwork/drivers/bridge/bridge_linux.go]: I've split the condition and added a comment ... does that help?

Comment (akerouanton) [reply libnetwork/drivers/bridge/bridge_linux.go]: > Should we use thisConfig here? (also in the other branch below)?

There are a few other code paths that locks the network before accessing its config, but it's not really needed because this field is never written after struct initialization:

https://github.com/moby/moby/blob/0de01f700d9040f70d71d16fff2ea4aafc4af36b/libnetwork/drivers/bridge/bridge_linux.go#L852

Anyway, let's keep it as is now it's been changed. We should probably refactor all those code paths after dealing with 28.0.1.

File: libnetwork/drivers/bridge/bridge_linux.go [hunk 2]
```diff
@@ -479,13 +479,23 @@ func (n *bridgeNetwork) isolateNetwork(enable bool) error {
 
 	// Install the rules to isolate this network against each of the other networks
 	if n.driver.config.EnableIPTables {
-		if err := setINC(iptables.IPv4, thisConfig.BridgeName, thisConfig.GwModeIPv4, enable); err != nil {
-			return err
+		// Only create the rules if the network has IPv4 enabled. But, always delete
+		// rules, in case they were set up by an older daemon that didn't check whether
+		// the network has IPv4.
+		if !enable || thisConfig.EnableIPv4 {
```
[the remark this answers is not in the document]
Comment (akerouanton) [reply libnetwork/drivers/bridge/bridge_linux.go:485]: `enable == true` means 'create the rules'.

`enabled == false` means 'delete the rules'. It's used to rollback something fails down the line, or when the network is deleted.

**Review by vvoland — APPROVED** [review]

File: libnetwork/drivers/bridge/bridge_linux.go (hunk 2 above)
Comment (akerouanton) [inline libnetwork/drivers/bridge/bridge_linux.go:485]: I find this version more confusing than the previous was, and now the comment right before `if n.driver.config.EnableIPTables` contradicts the inner comment as it talks about "installing" while the inner comment mentions the delete case.

But that's usual level of bikeshedding I guess, so whatever feels best for you seems okay to me.

**Review by akerouanton — APPROVED** [review]

File: libnetwork/drivers/bridge/bridge_linux.go (hunk 2 above)
Comment (robmry) [reply libnetwork/drivers/bridge/bridge_linux.go:484]: I've deleted the comment above, which mostly duplicated the function's comment - and updated the function's comment to say what "enable" does.

Comment (robmry) [reply libnetwork/drivers/bridge/bridge_linux.go:484]: (Also rebased - so I'll let the tests run, then merge.)

Comment (akerouanton) [reply libnetwork/drivers/bridge/bridge_linux.go:484]: Thanks! ❤️

**Review by akerouanton — APPROVED** [review]
