### PR TITLE
Print an info message when detaching a container started with --rm

### LINKED ISSUE #17516: docker command hangs when detaching with ctrl+p+q when --rm flag.
docker command does not respond while exiting using `<ctrl+p>` and `<ctrl-q>` and when container is run with `--rm` flag.  

```
docker version:
 docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0-dev
 API version:  1.22
 Go version:   go1.4.3
 Git commit:   b92fd9f-dirty
 Built:        Thu Oct 29 17:15:32 UTC 2015
 OS/Arch:      linux/amd64

docker info:
docker info
Containers: 31
Images: 61
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 67
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-65-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 2
Total Memory: 24.861 GiB
Name: gst-srv211
ID: 72OY:23OP:RSV2:T5II:DWX2:2U4L:OSOK:Q5TW:S5SV:QD5Y:FH5L:SNXM
Debug mode (server): true
File Descriptors: 27
Goroutines: 50
System Time: 2015-10-30T10:17:54.8029752+05:30
EventsListeners: 0
Init SHA1: 
Init Path: /home/abelur/repos/docker-fork/bundles/1.9.0-dev/binary/docker
Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
```

uname -a:
Linux srv-vm 3.13.0-65-generic #105-Ubuntu SMP Mon Sep 21 18:50:58 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Provide additional environment details (AWS, VirtualBox, physical, etc.):

List the steps to reproduce the issue:
1. docker run --rm -it ubuntu:14.04 bash
2. `ctrl+p+q` ===> to detach from the container 
3. `ctrl+c` ===> Need to send a sigterm to detach successfully
 
Note: Repeat the above steps without the `--rm` flag, which results in a expected behaviour. 

Describe the results you received:
We need to send a `ctrl-C` (sigterm) every time a container is started with `docker run --rm` or `--rm=true`. The flag works as expected which removes the container upon `exit` cmd, but the detach is does not work. 
  
```
 docker run --rm=true -it ubuntu:14.04 bash
root@65c55637d6e8:/# 

^C
```

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                 CREATED             STATUS              PORTS               NAMES
65c55637d6e8        ubuntu:14.04        "bash"                  14 seconds ago      Up 13 seconds                           silly_borg

``` 

Describe the results you expected:
* The container should not go to hang state as it would impact the application running within the container (happens occasionally). 
* Container should detach gracefully without the user requiring to provide `ctrl-c` every time. This helps in automating while running tests. 
* At-least to notify the user/admin a deviation from expected behaviour: "Warning: container `<id>` running, not exited" OR "Warning: Container `<id>` not exited on `--rm`, detached on user input `ctrl+p+q`" 

Edit: I have update the issue to avoid confusion on the issue.

### PR DESCRIPTION
**Pull request by mlaventure**
This patch aims to avoid confusion for users that detach a container (^P^Q) that was started with `--rm -ti`.

After the container is detached, the users are left with what they consider an "unresponsive" prompt but is actually the cli waiting for the container to exit in order to delete the container.

Closes #17516

Signed-off-by: Kenfe-Mickael Laventure mickael.laventure@gmail.com

### CODE REVIEW

**Comment by tiborvass** [comment]
@mlaventure golint :)

File: api/client/run.go [hunk 1]
```diff
@@ -254,6 +255,17 @@ func (cli *DockerCli) CmdRun(args ...string) error {
 
 	// Attached mode
 	if *flAutoRemove {
+		// Warn user if they detached us
+		js, err := cli.client.ContainerInspect(createResponse.ID)
+		if err != nil {
+			return runStartContainerErr(err)
+		}
+		if js.State.Running == true || js.State.Paused == true {
+			fmt.Print("\ndocker: detached from ",
```
Comment (calavera) [inline api/client/run.go]: I think this should be printed with `fmt.Fprintf`

Comment (mlaventure) [inline api/client/run.go]: I hesitated for an instant yes, I'll make the change.

File: api/client/run.go [hunk 2]
```diff
@@ -254,6 +255,16 @@ func (cli *DockerCli) CmdRun(args ...string) error {
 
 	// Attached mode
 	if *flAutoRemove {
+		// Warn user if they detached us
+		js, err := cli.client.ContainerInspect(createResponse.ID)
+		if err != nil {
+			return runStartContainerErr(err)
+		}
+		if js.State.Running == true || js.State.Paused == true {
+			fmt.Printf("\ndocker: detached from %s! Waiting for it to terminate in order to uphold \"--rm\".\n",
```
Comment (calavera) [inline api/client/run.go]: almost there @mlaventure!

You need to use `fmt.Fprintf` https://golang.org/src/fmt/print.go?s=4905:4982#L176

Hint: The cli has references to the configured error and output streams. See usages in this same file.

**Comment by icecrime** [comment]
I've been trying to find a way to avoid the extra inspect, but I can't seem to find any ¯\_(ツ)_/¯

LGTM

File: api/client/run.go [hunk 3]
```diff
@@ -254,6 +255,16 @@ func (cli *DockerCli) CmdRun(args ...string) error {
 
 	// Attached mode
 	if *flAutoRemove {
+		// Warn user if they detached us
+		js, err := cli.client.ContainerInspect(createResponse.ID)
+		if err != nil {
+			return runStartContainerErr(err)
+		}
+		if js.State.Running == true || js.State.Paused == true {
+			fmt.Fprintf(cli.out, "\ndocker: detached from %s! Waiting for it to terminate in order to uphold \"--rm\".\n",
```
Comment (calavera) [inline api/client/run.go]: please, remove the initial `\ndocker: ` from the message. Also, please, no exclamations, we don't want to be rude and yell at people :grin: 

```go
fmt.Fprintf(cli.out, "Detached from %s. Waiting for it to terminate in order to uphold \"--rm\"\n",
```

Comment (mlaventure) [inline api/client/run.go]: Done, but the extra `\n` was here to prevent this:

```
$ docker run --rm -ti busybox cat
toto^P^QDetached from ....
```

File: api/client/run.go [hunk 4]
```diff
@@ -260,6 +261,16 @@ func (cli *DockerCli) CmdRun(args ...string) error {
 
 	// Attached mode
 	if *flAutoRemove {
+		// Warn user if they detached us
+		js, err := cli.client.ContainerInspect(createResponse.ID)
+		if err != nil {
+			return runStartContainerErr(err)
```
Comment (cpuguy83) [inline api/client/run.go]: Do we need to error out if we can't determine if we should print a message?

Comment (mlaventure) [inline api/client/run.go]: My take is that if we fail here, the next api call is mostly certain to fail too.

**Comment by calavera** [comment]
LGTM
