### PR TITLE
hack/test/unit: run `libnetwork` tests sequentially

### LINKED ISSUE #42458: Flaky test: libnetwork/iptables TestConcurrencyNoWait
Looks like this failed a couple times on https://github.com/moby/moby/pull/42409

```
 === FAIL: libnetwork/iptables TestConcurrencyNoWait (0.14s)
     iptables_test.go:217:  (iptables failed: iptables -t nat -A POSTROUTING -p tcp -s 172.17.0.1 -d 172.17.0.1 --dport 4321 -j MASQUERADE: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
          (exit status 4))
```

### PR DESCRIPTION
**Pull request by rvolosatovs**
**- What I did**
Run `libnetwork` tests sequentially. See https://github.com/moby/moby/issues/42458#issuecomment-873216754 for explanation.
Closes #42458 maybe more

Note, that many tests in `libnetwork/...` already depend on the assumption that they are run sequentially and do not "easily" support things like `-run` due to that fact. E.g. this test is a prime example of such behavior: https://github.com/moby/moby/blob/45b45ad65b6f4a76f2bd0f768ef6edb10ebcc0bc/libnetwork/iptables/iptables_test.go#L1-L327

I, personally, don't think that `-p=1` is the "correct" solution here. Although, to do this "right" I think we'd have to rewrite a large portion of `libnetwork` tests and I do not think that is worth it at this point.

**- How I did it**
Run `gotestsum` at most twice and pass `-p=1` when running unit tests in `/libnetwork` namespace

**- How to verify it**
e.g. `TESTDIRS='github.com/docker/docker/libnetwork/iptables github.com/docker/docker/libnetwork/drivers/bridge' make test-unit` should pass (and sometimes fail without this change)

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by rvolosatovs** [comment]
@thaJeztah @fredericdalleau  (and anyone else) thoughts on this? Please also see https://github.com/moby/moby/issues/42458#issuecomment-873216754

Most probably refs and maybe fixes #42553

**Comment by thaJeztah** [comment]
Ah, heh. Nice find. Yes, unit tests that are not-so-unit 😞

**Comment by rvolosatovs** [comment]
CI failure (so far): #42459

**Comment by tianon** [comment]
Ah, `-p` controls the number of _packages_ that will be tested in parallel (so this doesn't disable parallelism completely, just the default of running tests for more than one package at a time, which normally defaults to the number of CPUs available).

```console
$ go help testflag
...
	-parallel n
	    Allow parallel execution of test functions that call t.Parallel.
	    The value of this flag is the maximum number of tests to run
	    simultaneously; by default, it is set to the value of GOMAXPROCS.
	    Note that -parallel only applies within a single test binary.
	    The 'go test' command may run tests for different packages
	    in parallel as well, according to the setting of the -p flag
	    (see 'go help build').
...
$ go help build
...
	-p n
		the number of programs, such as build commands or
		test binaries, that can be run in parallel.
		The default is the number of CPUs available.
...
```

I don't love it (and wish we could set it just for `libnetwork/*` somehow :disappointed:), but it seems like an acceptable workaround IMO.

**Comment by cpuguy83** [comment]
We can absolutely filter libnetwork and run it separately

File: hack/test/unit-run.go [hunk 1]
```diff
@@ -0,0 +1,220 @@
+///usr/bin/env true; exec /usr/bin/env go run "$0" "$@"
```
Comment (rvolosatovs) [inline hack/test/unit-run.go:1]: This is a little shebang hack, which lets `go` files be executable as `./hack/test/unit-run.go`.
So developers can run (json-formatted) unit tests directly bypassing `gotestsum` by `./hack/test/unit-run.go`. It would be more useful if this script would support more functionality, not sure if it's best to remove it or leave it.

File: hack/test/unit-run.go [hunk 2]
```diff
@@ -0,0 +1,220 @@
...
+	case nil, *exec.ExitError:
+		return cmd.ProcessState.ExitCode(), nil
+	default:
+		return 0, err
+	}
+}
+
+// mergeProfiles writes profile lines from each profile in profiles to final test profile at path.
+// mergeProfiles assumes that a valid profile file already exists at path.
+func mergeProfiles(path string, profiles ...*os.File) error {
```
Comment (rvolosatovs) [inline hack/test/unit-run.go:89]: AFAIK, profiles `go` testing framework outputs are sorted. This implementation does not provide such guarantees. Whether or not this is a problem for our tooling - I am not sure. Can someone confirm that simply appending is OK?

File: hack/test/unit-run.go [hunk 3]
```diff
@@ -0,0 +1,220 @@
...
+				if err := exec.Command("hack/make.sh", "binary-proxy", "install-proxy").Run(); err != nil {
+					log.Fatalf("Failed to install `docker-proxy`: %s", err)
+				}
+			}
+		}
+	}
+
+	var testFlags []string
+	if s, ok := os.LookupEnv(TESTFLAGS); ok {
+		testFlags = append(testFlags, strings.Fields(s)...) // TODO: Support flags containing spaces
```
Comment (rvolosatovs) [inline hack/test/unit-run.go:165]: Is that OK for now? If not, maybe someone can suggest a simple way to handle this, which does not involve manually parsing complete flag string - doesn't seem like this is something we should be doing?

**Comment by rvolosatovs** [comment]
I added a Go test runner, which runs `libnetwork` tests exclusively with `-p=1` and handles merging resulting profiles.
What do you think of such approach?

File: hack/test/unit [hunk 4]
```diff
@@ -12,22 +12,5 @@
...
-
 mkdir -p bundles
-gotestsum --format=standard-quiet --jsonfile=bundles/go-test-report.json --junitfile=bundles/junit-report.xml -- \
-	"${BUILDFLAGS[@]}" \
-	-cover \
-	-coverprofile=bundles/profile.out \
-	-covermode=atomic \
-	${TESTFLAGS} \
-	${pkg_list}
+gotestsum --format=standard-quiet --jsonfile=bundles/go-test-report.json --junitfile=bundles/junit-report.xml --raw-command -- go run ./hack/test/unit-run.go
```
Comment (rvolosatovs) [inline hack/test/unit:16]: See https://github.com/gotestyourself/gotestsum#custom-go-test-command for documentation

**Comment by rvolosatovs** [comment]
Still did not get any feedback, moving this out of draft

**Comment by rvolosatovs** [comment]
@tianon @cpuguy83 PTAL

**Review by cpuguy83 — COMMENTED** [review]
I don't think the added complexity here is worth it.
If we just need to ensure libnetwork tests are exclusive, we can do that in bash.

File: hack/test/unit [hunk 5]
```diff
@@ -18,16 +18,32 @@ TESTDIRS="${TESTDIRS:-./...}"
...
+    gotestsum --format=standard-quiet --jsonfile=bundles/go-test-report.json --junitfile=bundles/junit-report.xml -- \
+    	"${BUILDFLAGS[@]}" \
+    	-cover \
+    	-coverprofile=bundles/profile.out \
+    	-covermode=atomic \
+    	${TESTFLAGS} \
+    	${base_pkg_list}
+fi
+if [ "${libnetwork_pkg_list}" ]; then
+    gotestsum --format=standard-quiet --jsonfile=bundles/libnetwork-go-test-report.json --junitfile=bundles/libnetwork-junit-report.xml -- \
```
Comment (thaJeztah) [inline hack/test/unit:41]: May need to check if the Jenkinsfile uploads the new files as well

Comment (rvolosatovs) [reply hack/test/unit:41]: Don't have much experience with Jenkins - the existing functionality related to this is not trivial, I will have to study the docs, but any pointers meanwhile would be very welcome!

**Comment by rvolosatovs** [comment]
2/3 CI failures are due to:
```
[2021-07-23T12:10:33.152Z] #52 619.0 fatal: unable to access 'https://github.com/mvdan/sh.git/': GnuTLS recv error (-54): Error in the pull function.

[2021-07-23T12:10:33.152Z] #52 ERROR: executor failed running [/bin/sh -c PREFIX=/build /tmp/install/install.sh shfmt]: exit code: 128
```

**Comment by tianon** [comment]
@cpuguy83 didn't you mention something about how these are really integration tests, so maybe should be part of the integration test script?

**Comment by thaJeztah** [comment]
@tianon yes, but we discussed; let's do a fix for the immediate issue first (assuming that would be a relatively small change), then spend some time to change them / move them to integration tests (as a follow up).

Getting CI somewhat more stable is the higher priority

**Comment by rvolosatovs** [comment]
> @cpuguy83 didn't you mention something about how these are really integration tests, so maybe should be part of the integration test script?

I did evaluate possibilities of making this a part of integration test suite, but that involves quite some work. However, we also seemed to agree that it's fine to just have 2 separate runs in the unit test script "for now" and make this a part of integration test suite later.

File: hack/test/unit (hunk 5 above)
Comment (thaJeztah) [reply hack/test/unit:41]: I'm not great at Jenkinsfiles either (mostly "do by example, and a lot of Google search") 🤣

The essential bit is that each of the stages will have a step that uploads the results; we probably need to either add another one of those (for stages that run the libnetwork tests), or perhaps make it use a wildcard; see, e.g. https://github.com/moby/moby/blob/master/Jenkinsfile#L202

File: hack/test/unit [hunk 6]
```diff
@@ -18,16 +18,32 @@ TESTDIRS="${TESTDIRS:-./...}"
...
 
-echo "${pkg_list}" | grep --fixed-strings "libnetwork/drivers/bridge" \
-	&& if ! type docker-proxy; then
-		hack/make.sh binary-proxy install-proxy
-	fi
+base_pkg_list=$(echo "${pkg_list}" | grep --fixed-strings -v "/libnetwork" || :)
+libnetwork_pkg_list=$(echo "${pkg_list}" | grep --fixed-strings "/libnetwork" || :)
+
+echo "${libnetwork_pkg_list}" | grep --fixed-strings "libnetwork/drivers/bridge" \
+    && if ! type docker-proxy; then
```
Comment (thaJeztah) [inline hack/test/unit:25]: Looks like the file switched from using tabs to spaces for indentation; can you run `shfmt`  to format it?


```bash
shfmt -bn -ci -sr -w hack/test/unit
```


Options taken from https://github.com/moby/moby/blob/12f1b3ce43fe4aea5a41750bcc20f2a7dd67dbfc/hack/validate/shfmt#L4-L11

**Review by thaJeztah — CHANGES_REQUESTED** [review]

File: hack/test/unit (hunk 5 above)
Comment (rvolosatovs) [reply hack/test/unit]: I tried something, please confirm that it makes sense, since I am not sure how to test this.

**Comment by rvolosatovs** [comment]
Switched to `<base>-<suffix>.<ext>` file naming scheme, since that's also what other tests use

**Comment by rvolosatovs** [comment]
One of the runs failed with
```
[2021-07-27T11:31:52.834Z]  > [registry 2/2] RUN --mount=type=cache,target=/root/.cache/go-build     --mount=type=cache,target=/go/pkg/mod     --mount=type=tmpfs,target=/go/src/         set -x         && git clone https://github.com/docker/distribution.git .         && git checkout -q "47a064d4195a9b56133891bbb13620c3ac83a827"         && GOPATH="/go/src/github.com/docker/distribution/Godeps/_workspace:/go"            go build -buildmode=pie -o /build/registry-v2 github.com/docker/distribution/cmd/registry         && case $(dpkg --print-architecture) in                amd64|armhf|ppc64*|s390x)                git checkout -q "ec87e9b6971d831f0eff752ddb54fb64693e51cd";                GOPATH="/go/src/github.com/docker/distribution/Godeps/_workspace:/go";                    go build -buildmode=pie -o /build/registry-v2-schema1 github.com/docker/distribution/cmd/registry;                 ;;            esac:

[2021-07-27T11:31:52.834Z] ------

[2021-07-27T11:31:52.834Z] executor failed running [/bin/sh -c set -x         && git clone https://github.com/docker/distribution.git .         && git checkout -q "$REGISTRY_COMMIT"         && GOPATH="/go/src/github.com/docker/distribution/Godeps/_workspace:$GOPATH"            go build -buildmode=pie -o /build/registry-v2 github.com/docker/distribution/cmd/registry         && case $(dpkg --print-architecture) in                amd64|armhf|ppc64*|s390x)                git checkout -q "$REGISTRY_COMMIT_SCHEMA1";                GOPATH="/go/src/github.com/docker/distribution/Godeps/_workspace:$GOPATH";                    go build -buildmode=pie -o /build/registry-v2-schema1 github.com/docker/distribution/cmd/registry;                 ;;            esac]: exit code: 128

script returned exit code 1
```
which seems like an unrelated flake

File: hack/test/unit [hunk 7]
```diff
@@ -18,16 +18,32 @@ TESTDIRS="${TESTDIRS:-./...}"
...
+		${TESTFLAGS} \
+		${base_pkg_list}
+fi
+if [ "${libnetwork_pkg_list}" ]; then
+	gotestsum --format=standard-quiet --jsonfile=bundles/go-test-report-libnetwork.json --junitfile=bundles/junit-report-libnetwork.xml -- \
+		"${BUILDFLAGS[@]}" \
+		-cover \
+		-coverprofile=bundles/profile-libnetwork.out \
+		-covermode=atomic \
+		-p=1 \
```
Comment (thaJeztah) [inline hack/test/unit:46]: perhaps would be good to add a comment in this branch/block to describe what it's different from the other block (`-p 1`)

Comment (cpuguy83) [reply hack/test/unit:46]: And why :)

Comment (rvolosatovs) [reply hack/test/unit]: did it in https://github.com/moby/moby/pull/42594/commits/1135681ccb31e6e106b2141f8570d3bf06c78ea3

**Comment by rvolosatovs** [comment]
Extracted the testing command into `run_test_unit`, similar to `run_test_integration*` https://github.com/moby/moby/blob/0b39cc2e57828c411a82ffebf7f52cf724e4fbe2/hack/test/e2e-run.sh#L20-L44

To me it seems a bit cleaner this way. Did it in a separate commit, let me know if you want it dropped.

**Comment by rvolosatovs** [comment]
@cpuguy83 @thaJeztah PTAL

**Comment by rvolosatovs** [comment]
A few failures, that seem unrelated:
```
[2021-08-01T15:55:33.884Z]  > [rootlesskit 1/3] RUN --mount=type=cache,target=/root/.cache/go-build     --mount=type=cache,target=/go/pkg/mod     --mount=type=bind,src=hack/dockerfile/install,target=/tmp/install         PREFIX=/build /tmp/install/install.sh rootlesskit:

[2021-08-01T15:55:33.884Z] ------

[2021-08-01T15:55:33.884Z] executor failed running [/bin/sh -c PREFIX=/build /tmp/install/install.sh rootlesskit]: exit code: 128

script returned exit code 1
```

```
[2021-08-01T15:59:54.289Z] #32 [swagger 2/2] RUN --mount=type=cache,target=/root/.cache/go-build     --mount=type=cache,target=/go/pkg/mod     --mount=type=tmpfs,target=/go/src/         set -x         && git clone https://github.com/kolyshkin/go-swagger.git .         && git checkout -q "c56166c036004ba7a3a321e5951ba472b9ae298c"         && go build -o /build/swagger github.com/go-swagger/go-swagger/cmd/swagger

[2021-08-01T15:59:54.289Z] #32 sha256:b91ffc0025b99e48e874df39aa649930bfdbb27d79b80cdc6e030f11987f2e15

[2021-08-01T16:06:00.846Z] #32 623.7 error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.

[2021-08-01T16:06:00.846Z] #32 623.7 fatal: the remote end hung up unexpectedly

[2021-08-01T16:06:00.846Z] #32 623.7 fatal: early EOF

[2021-08-01T16:06:00.846Z] #32 623.7 fatal: index-pack failed

[2021-08-01T16:06:00.846Z] #32 ERROR: executor failed running [/bin/sh -c set -x         && git clone https://github.com/kolyshkin/go-swagger.git .         && git checkout -q "$GO_SWAGGER_COMMIT"         && go build -o /build/swagger github.com/go-swagger/go-swagger/cmd/swagger]: exit code: 128

[2021-08-01T16:06:00.846Z] ------

[2021-08-01T16:06:00.846Z]  > [swagger 2/2] RUN --mount=type=cache,target=/root/.cache/go-build     --mount=type=cache,target=/go/pkg/mod     --mount=type=tmpfs,target=/go/src/         set -x         && git clone https://github.com/kolyshkin/go-swagger.git .         && git checkout -q "c56166c036004ba7a3a321e5951ba472b9ae298c"         && go build -o /build/swagger github.com/go-swagger/go-swagger/cmd/swagger:

[2021-08-01T16:06:00.846Z] ------

[2021-08-01T16:06:00.846Z] executor failed running [/bin/sh -c set -x         && git clone https://github.com/kolyshkin/go-swagger.git .         && git checkout -q "$GO_SWAGGER_COMMIT"         && go build -o /build/swagger github.com/go-swagger/go-swagger/cmd/swagger]: exit code: 128

script returned exit code 1
```

```
[2021-08-01T16:23:00.228Z] === Failed

[2021-08-01T16:23:00.228Z] === FAIL: github.com/docker/docker/integration/build TestBuildWCOWSandboxSize (651.44s)

[2021-08-01T16:23:00.228Z]     build_test.go:572: assertion failed: value "{\"stream\":\"Step 1/8 : FROM busybox AS intermediate\"}\r\n{\"stream\":\"\\n\"}\r\n{\"stream\":\" ---\\u003e 64a7ef3b89f1\\n\"}\r\n{\"stream\":\"Step 2/8 : WORKDIR C:\\\\\\\\stuff\"}\r\n{\"stream\":\"\\n\"}\r\n{\"stream\":\" ---\\u003e Running in b7a0e518e389\\n\"}\r\n{\"stream\":\"Removing intermediate container b7a0e518e389\\n\"}\r\n{\"stream\":\" ---\\u003e 17c807ffb38c\\n\"}\r\n{\"stream\":\"Step 3/8 : RUN fsutil file createnew C:\\\\\\\\stuff\\\\\\\\bigfile_0.txt 22548578304 \\u0026\\u0026 del bigfile_0.txt\"}\r\n{\"stream\":\"\\n\"}\r\n{\"stream\":\" ---\\u003e Running in 7745fac8e671\\n\"}\r\n{\"stream\":\"File C:\\\\stuff\\\\bigfile_0.txt is created\\r\\n\"}\r\n{\"stream\":\"Removing intermediate container 7745fac8e671\\n\"}\r\n{\"stream\":\" ---\\u003e 9d9556f09ffe\\n\"}\r\n{\"stream\":\"Step 4/8 : RUN fsutil file createnew C:\\\\\\\\stuff\\\\\\\\bigfile_1.txt 7516192768\"}\r\n{\"stream\":\"\\n\"}\r\n{\"stream\":\" ---\\u003e Running in 697045102b5a\\n\"}\r\n{\"stream\":\"File C:\\\\stuff\\\\bigfile_1.txt is created\\r\\n\"}\r\n{\"stream\":\"Removing intermediate container 697045102b5a\\n\"}\r\n{\"stream\":\" ---\\u003e 9b7467f32168\\n\"}\r\n{\"stream\":\"Step 5/8 : RUN fsutil file createnew C:\\\\\\\\stuff\\\\\\\\bigfile_2.txt 7516192768\"}\r\n{\"stream\":\"\\n\"}\r\n{\"stream\":\" ---\\u003e Running in ba733f5ff4f8\\n\"}\r\n{\"stream\":\"File C:\\\\stuff\\\\bigfile_2.txt is created\\r\\n\"}\r\n{\"stream\":\"Removing intermediate container ba733f5ff4f8\\n\"}\r\n{\"stream\":\" ---\\u003e bace7e0e6946\\n\"}\r\n{\"stream\":\"Step 6/8 : RUN fsutil file createnew C:\\\\\\\\stuff\\\\\\\\bigfile_3.txt 7516192768\"}\r\n{\"stream\":\"\\n\"}\r\n{\"stream\":\" ---\\u003e Running in f1588afe20ae\\n\"}\r\n{\"stream\":\"File C:\\\\stuff\\\\bigfile_3.txt is created\\r\\n\"}\r\n{\"stream\":\"Removing intermediate container f1588afe20ae\\n\"}\r\n{\"stream\":\" ---\\u003e 7758de385ecc\\n\"}\r\n{\"aux\":{\"ID\":\"sha256:7758de385ecc0248d5c3f029c805a3eec51e319262330fd1cdab0bd0f5151bf8\"}}\r\n{\"stream\":\"Step 7/8 : FROM busybox\"}\r\n{\"stream\":\"\\n\"}\r\n{\"stream\":\" ---\\u003e 64a7ef3b89f1\\n\"}\r\n{\"stream\":\"Step 8/8 : COPY --from=intermediate C:\\\\\\\\stuff C:\\\\\\\\stuff\"}\r\n{\"stream\":\"\\n\"}\r\n{\"errorDetail\":{\"message\":\"re-exec error: exit status 1: output: hcsshim::ImportLayer - failed failed in Win32: The system cannot find the path specified. (0x3)\"},\"error\":\"re-exec error: exit status 1: output: hcsshim::ImportLayer - failed failed in Win32: The system cannot find the path specified. (0x3)\"}\r\n" does not match regexp "Successfully built|re-exec error: exit status 1: output: write.*daemon\\\\\\\\tmp\\\\\\\\hcs.*bigfile_[1-3].txt: There is not enough space on the disk."
```

File: hack/test/unit [hunk 8]
```diff
@@ -12,22 +12,42 @@
...
-	-coverprofile=bundles/profile.out \
-	-covermode=atomic \
-	${TESTFLAGS} \
-	${pkg_list}
+if [ "${base_pkg_list}" ]; then
+	run_test_unit '' "${base_pkg_list}"
+fi
+if [ "${libnetwork_pkg_list}" ]; then
+	# Run only one test binary in parallel to ensure sequential execution.
+	TESTFLAGS="-p=1 ${TESTFLAGS:-}" run_test_unit '-libnetwork' "${libnetwork_pkg_list}"
```
Comment (thaJeztah) [inline hack/test/unit:52]: Hm.. I'm a bit on the fence on the second commit abstracting away things into `run_test_unit` - as seen here, it still needs various parameters to be passed (test flags, prefix, package-list), but now it requires me to look back-and-forth between this line and the function above to understand what each of those do.

I think it's fine to keep the code inline here. It's not "pretty", but reduces the cognitive overhead of having to look up what `run_test_unit` does, and what parameters it takes.

File: hack/test/unit [hunk 9]
```diff
@@ -12,22 +12,42 @@
...
-	-cover \
-	-coverprofile=bundles/profile.out \
-	-covermode=atomic \
-	${TESTFLAGS} \
-	${pkg_list}
+if [ "${base_pkg_list}" ]; then
+	run_test_unit '' "${base_pkg_list}"
+fi
+if [ "${libnetwork_pkg_list}" ]; then
+	# Run only one test binary in parallel to ensure sequential execution.
```
Comment (thaJeztah) [inline hack/test/unit:51]: Perhaps combine the "NOTE" above with this comment; I think the comments combined makes it clearer what's happening. Something like;

```suggestion
	# libnetwork tests invoke iptables, and cannot be run in parallel. Execute
	# tests within /libnetwork with '-p=1' to run them sequentially. See
	# https://github.com/moby/moby/issues/42458#issuecomment-873216754 for details.
```

**Comment by thaJeztah** [comment]
Oh; forgot to leave a comment about that; I think we also will have to fix the Windows counterparts of this. i.e.; https://github.com/moby/moby/blob/0b39cc2e57828c411a82ffebf7f52cf724e4fbe2/hack/make.ps1#L315-L325

and https://github.com/moby/moby/blob/0b39cc2e57828c411a82ffebf7f52cf724e4fbe2/hack/ci/windows.ps1#L772-L776

**Comment by thaJeztah** [comment]
🤔 although; if it's only the iptables issue that's a problem, I guess that's not needed for Windows 😂

**Comment by rvolosatovs** [comment]
> :thinking: although; if it's only the iptables issue that's a problem, I guess that's not needed for Windows :joy:

I would think the same in this case. Are the tests in question known to be flaky on Windows in particular?

**Comment by rvolosatovs** [comment]
`-p=1` on the whole `/libnetwork` package tree actually disables some of the tests:
```
[2021-08-02T08:58:37.153Z] === Skipped

[2021-08-02T08:58:37.153Z] === SKIP: libnetwork TestParallel3 (0.00s)

[2021-08-02T08:58:37.153Z]     libnetwork_linux_test.go:966: Skipped because t.parallel was less than  3

[2021-08-02T08:58:37.153Z] 

[2021-08-02T08:58:37.153Z] === SKIP: libnetwork TestParallel1 (0.00s)

[2021-08-02T08:58:37.153Z]     libnetwork_linux_test.go:966: Skipped because t.parallel was less than  3

[2021-08-02T08:58:37.153Z] 

[2021-08-02T08:58:37.153Z] === SKIP: libnetwork TestParallel2 (0.00s)

[2021-08-02T08:58:37.153Z]     libnetwork_linux_test.go:966: Skipped because t.parallel was less than  3

[2021-08-02T08:58:37.153Z] 

[2021-08-02T08:58:37.154Z] === SKIP: libnetwork/ipam TestParallelPredefinedRequest4 (0.00s)

[2021-08-02T08:58:37.154Z]     allocator_test.go:1423: Skipped because t.parallel was less than  5

[2021-08-02T08:58:37.154Z] 

[2021-08-02T08:58:37.154Z] === SKIP: libnetwork/ipam TestParallelPredefinedRequest5 (0.00s)

[2021-08-02T08:58:37.154Z]     allocator_test.go:1423: Skipped because t.parallel was less than  5

[2021-08-02T08:58:37.154Z] 

[2021-08-02T08:58:37.154Z] === SKIP: libnetwork/ipam TestParallelPredefinedRequest3 (0.00s)

[2021-08-02T08:58:37.154Z]     allocator_test.go:1423: Skipped because t.parallel was less than  5

[2021-08-02T08:58:37.154Z] 

[2021-08-02T08:58:37.154Z] === SKIP: libnetwork/ipam TestParallelPredefinedRequest2 (0.00s)

[2021-08-02T08:58:37.154Z]     allocator_test.go:1423: Skipped because t.parallel was less than  5

[2021-08-02T08:58:37.154Z] 

[2021-08-02T08:58:37.154Z] === SKIP: libnetwork/ipam TestParallelPredefinedRequest1 (0.00s)

[2021-08-02T08:58:37.154Z]     allocator_test.go:1423: Skipped because t.parallel was less than  5
```

Looks like we actually need to apply this flag to a smaller set of packages, I guess only the ones depending on `iptables`. `libnetwork_linux_test.go` then probably will have to be moved, I will investigate...

**Comment by thaJeztah** [comment]
> -p=1 on the whole /libnetwork package tree actually disables some of the tests:

Wondering; Can we re-enable parallel as part of those tests itself?

**Comment by rvolosatovs** [comment]
> > -p=1 on the whole /libnetwork package tree actually disables some of the tests:
> 
> Wondering; Can we re-enable parallel as part of those tests itself?

I don't think we can do that. We could try to do some trickery in `TestMain`, but I doubt that would be maintainable.
If we want to handle this within the tests themselves, I think our best bet would be to use an on-disk lock, which would be used by the flaky tests using `iptables`.

**Comment by thaJeztah** [comment]
Yeah, so I was wondering `-p=1` disables multiple _packages_ to be run in parallel, but would it still allow `t.Parallel()` to be used to enable parallel runs within a test (subtests to be run in parallel)

**Comment by rvolosatovs** [comment]
Oh, nevermind, it turns out that those tests are never actually run on CI, e.g. on latest master arm64 build (https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/master/1006/pipeline/363):
```
[2021-08-02T08:11:56.627Z] === SKIP: libnetwork/ipam TestParallelPredefinedRequest1 (0.00s)

[2021-08-02T08:11:56.627Z]     allocator_test.go:1423: Skipped because t.parallel was less than  5

[2021-08-02T08:11:56.627Z] 

[2021-08-02T08:11:56.627Z] === SKIP: libnetwork/ipam TestParallelPredefinedRequest5 (0.00s)

[2021-08-02T08:11:56.627Z]     allocator_test.go:1423: Skipped because t.parallel was less than  5

[2021-08-02T08:11:56.627Z] 

[2021-08-02T08:11:56.627Z] === SKIP: libnetwork/ipam TestParallelPredefinedRequest3 (0.00s)

[2021-08-02T08:11:56.627Z]     allocator_test.go:1423: Skipped because t.parallel was less than  5

[2021-08-02T08:11:56.627Z] 

[2021-08-02T08:11:56.627Z] === SKIP: libnetwork/ipam TestParallelPredefinedRequest2 (0.00s)

[2021-08-02T08:11:56.627Z]     allocator_test.go:1423: Skipped because t.parallel was less than  5

[2021-08-02T08:11:56.627Z] 

[2021-08-02T08:11:56.627Z] === SKIP: libnetwork/ipam TestParallelPredefinedRequest4 (0.00s)

[2021-08-02T08:11:56.627Z]     allocator_test.go:1423: Skipped because t.parallel was less than  5
```

**Comment by rvolosatovs** [comment]
cc @samuelkarp

**Review by thaJeztah — APPROVED** [review]
LGTM

perhaps we should create a tracking issue for the tests that are currently skipped because we don't have `-parallel` enabled

File: hack/test/unit [hunk 10]
```diff
@@ -18,16 +18,35 @@ TESTDIRS="${TESTDIRS:-./...}"
...
 mkdir -p bundles
-gotestsum --format=standard-quiet --jsonfile=bundles/go-test-report.json --junitfile=bundles/junit-report.xml -- \
-	"${BUILDFLAGS[@]}" \
-	-cover \
-	-coverprofile=bundles/profile.out \
-	-covermode=atomic \
-	${TESTFLAGS} \
-	${pkg_list}
+
+if [ "${base_pkg_list}" ]; then
```
Comment (samuelkarp) [inline hack/test/unit:31]: @tianon can correct me, but I think you want `-n` here

```suggestion
if [ -n "${base_pkg_list}" ]; then
```

File: hack/test/unit [hunk 11]
```diff
@@ -18,16 +18,35 @@ TESTDIRS="${TESTDIRS:-./...}"
...
+	gotestsum --format=standard-quiet --jsonfile=bundles/go-test-report.json --junitfile=bundles/junit-report.xml -- \
+		"${BUILDFLAGS[@]}" \
+		-cover \
+		-coverprofile=bundles/profile.out \
+		-covermode=atomic \
+		${TESTFLAGS} \
+		${base_pkg_list}
+fi
+if [ "${libnetwork_pkg_list}" ]; then
```
Comment (samuelkarp) [inline hack/test/unit:40]: Same as above with `-n`

File: hack/test/unit (hunk 10 above)
Comment (rvolosatovs) [reply hack/test/unit:31]: These are all identical:
```bash
#!/usr/bin/env bash

empty=''
nonempty='nonempty'

[ "${empty}" ] && echo "non-empty" || echo "empty"
[ -n "${empty}" ] && echo "non-empty" || echo "empty"
[ ! -z "${empty}" ] && echo "non-empty" || echo "empty"
[ "${empty}" != "" ] && echo "non-empty" || echo "empty"

[ "${nonempty}" ] && echo "non-empty" || echo "empty"
[ -n "${nonempty}" ] && echo "non-empty" || echo "empty"
[ ! -z "${nonempty}" ] && echo "non-empty" || echo "empty"
[ "${nonempty}" != "" ] && echo "non-empty" || echo "empty"
```

Produces:
```
empty
empty
empty
empty
non-empty
non-empty
non-empty
non-empty
```

```
$ bash --version                                              
GNU bash, version 4.4.23(1)-release (x86_64-unknown-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

Additionally, from `man test` (which is used by `[`):
```
       -n STRING
              the length of STRING is nonzero

       STRING equivalent to -n STRING
```

Both styles are used across repo, sometimes even mixed within one file. In `/hack`, for example:
https://github.com/moby/moby/blob/656a5e2bdf8cc2be64fee1459821b7045b755b0d/hack/make.sh#L44
https://github.com/moby/moby/blob/656a5e2bdf8cc2be64fee1459821b7045b755b0d/hack/make.sh#L67
https://github.com/moby/moby/blob/656a5e2bdf8cc2be64fee1459821b7045b755b0d/hack/validate/swagger-gen#L14
https://github.com/moby/moby/blob/656a5e2bdf8cc2be64fee1459821b7045b755b0d/hack/make/run#L31

https://github.com/moby/moby/blob/656a5e2bdf8cc2be64fee1459821b7045b755b0d/hack/make.sh#L144
https://github.com/moby/moby/blob/656a5e2bdf8cc2be64fee1459821b7045b755b0d/hack/make/run#L35

Is there a guideline, which clearly defines how this is to be done?

File: hack/test/unit (hunk 11 above)
Comment (rvolosatovs) [reply hack/test/unit:40]: That should not matter, see above

File: hack/test/unit (hunk 10 above)
Comment (thaJeztah) [reply hack/test/unit:31]: > Is there a guideline, which clearly defines how this is to be done?

Where possible, we try to use POSIX (and avoid "bashisms") for portability, e.g. to allow some scripts to be run in an environment where `bash` may not be present, or where `/bin/sh` is not an alias for `bash` (which it is in many environments). Referring to the posix docs; https://pubs.opengroup.org/onlinepubs/9699919799/utilities/test.html

> The two commands:
> 
> ```bash
> test "$1"
> test ! "$1"
> ```
>
> could not be used reliably on some historical systems. Unexpected results would occur if such a string expression were used and `$1` expanded to `'!'`, `'('`, or a known unary primary. Better constructs are:
> 
> ```bash
> test -n "$1"
> test -z "$1"
> ```

So from the above, looks like `-n` or `-z` is the recommended approach.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by samuelkarp — APPROVED** [review]
LGTM, thanks!
