### PR TITLE
Fix fd leak on attach

### LINKED ISSUE #37182: Docker daemon is leaking file descriptors (with reproduction)
**Description**

Not sure this is related, but I have in production after a few days / weeks that dockerd starts leaking tons of file descriptors of dead connections that it simply stops responding at all (not even to SIGUSR1).

While trying to understand how this can happen (since when it happens I can't do anything but kill it), I tried to figure out how you get a dead connection, and have found some conclusions on how to get dockerd to leak such file descriptors, although I'm not sure that what I'm about to say is the issue that is happening in production.

How do those leaked file descriptors look ? I run the command on linux:
ss | grep docker.sock
and I see tons of entries that most look like this:
u_str  ESTAB      0      0      /var/run/docker.sock 272245                * 0                    
u_str  ESTAB      0      0      /var/run/docker.sock 279780                * 0                    
u_str  ESTAB      0      0      /var/run/docker.sock 279118                * 0                    
u_str  ESTAB      0      0      /var/run/docker.sock 272201                * 0                    
u_str  ESTAB      0      0      /var/run/docker.sock 272217                * 0

You can see this are dead connections because the peer info (the * 0 in the end) points to nothing which means the other side closed the unix domain socket, but the docker daemon did not.

also this sockets take up file descriptors (as expected):
ls -l /proc/$(pidof dockerd)/fd
...
lrwx------ 1 root root 64 may 31 08:37 33 -> socket:[272217]
...

an alive connection looks like this (there is peer info):
u_str  ESTAB      0      0      /var/run/docker.sock 280489                * 279381               

I'm going now to show you a convoluted way to cause this resource leak, but remember that still dockerd shouldn't leak resources and that in the end there might be similar code that really needs to do something like this...

This also seems to happen on variety of docker versions from old to new.

**Steps to reproduce the issue:**
1. docker create -it --rm python:2.7 python -c "while True: print 1;"
\<container id>
2. docker start \<container id>
\<container id>
3. python2
```python
import socket
s = socket.socket(socket.AF_UNIX)
s.connect('/var/run/docker.sock')
s.send('POST /v1.24/containers/<container id>/attach?logs=1&stream=0&stdout=1 HTTP/1.1\r\nHost: localhost\r\n\r\n')
s.recv(1024)
s.close()
```
You can also try changing the logs=1&stream=0 with logs=0&stream=1
Also don't think the v1.24 is of particulate importance.
Also you can kill the python instead of s.close() (sometimes it acts differently)

4. ss | grep docker.sock
u_str  ESTAB      0      0      /var/run/docker.sock 280489                * 0

**Describe the results you received:**

There is a dead unclosed unix domain socket on the docker daemon side.

**Describe the results you expected:**

The docker daemon should figure the socket has been closed on the other side, and close it's side as well.

**Versions**

Tried on multiple versions, now both client and server: 17.12.1-ce and on ubuntu 16.04.4 with kernel 4.13.0-36-generic with default settings.

### PR DESCRIPTION
**Pull request by cpuguy83**
With a full attach, each attach was leaking 4 goroutines.
This updates attach to use errgroup instead of the hodge-podge of
waitgroups and channels.

In addition, the detach event was never being sent.

Fixes #37182

### CODE REVIEW

File: daemon/attach.go [hunk 1]
```diff
@@ -176,7 +176,7 @@ func (daemon *Daemon) containerAttach(c *container.Container, cfg *stream.Attach
 	ctx := c.InitAttachContext()
 	err := <-c.StreamConfig.CopyStreams(ctx, cfg)
 	if err != nil {
-		if _, ok := err.(term.EscapeError); ok {
+		if _, ok := errors.Cause(err).(term.EscapeError); ok || err == context.Canceled {
 			daemon.LogContainerEvent(c, "detach")
```
Comment (cpuguy83) [inline daemon/attach.go]: I'm wording if we should always log this event since the stream is detached.

**Comment by thaJeztah** [comment]
ping @tonistiigi @dmcgowan PTAL

**Review by vdemeester — APPROVED** [review]
LGTM :frog:

**Comment by dmcgowan** [comment]
LGTM

I still don't understand how 4 goroutines were leaked since the channel is created with a buffer of 3. The last one is a very obvious leak. Either way the code is much more correct, but want to make sure I am not missing something.

**Comment by thaJeztah** [comment]
experimental https://jenkins.dockerproject.org/job/Docker-PRs-experimental/40988/console failing on a known flaky: https://github.com/moby/moby/issues/37132


```
17:55:16 --- FAIL: TestServicePlugin (59.51s)
17:55:16 	daemon.go:289: [d01a95a9893fd] waiting for daemon to start
17:55:16 	daemon.go:321: [d01a95a9893fd] daemon started
17:55:16 	daemon.go:279: [d01a95a9893fd] exiting daemon
17:55:16 	daemon.go:289: [d924b90ed254e] waiting for daemon to start
17:55:16 	daemon.go:321: [d924b90ed254e] daemon started
17:55:16 	daemon.go:289: [dfafe426ae3c8] waiting for daemon to start
17:55:16 	daemon.go:321: [dfafe426ae3c8] daemon started
17:55:16 	daemon.go:289: [d2eebdb5cabf3] waiting for daemon to start
17:55:16 	daemon.go:321: [d2eebdb5cabf3] daemon started
17:55:16 	plugin_test.go:92: timeout hit after 30s: plugin "test" exists
17:55:16 	daemon.go:279: [d2eebdb5cabf3] exiting daemon
17:55:16 	daemon.go:279: [dfafe426ae3c8] exiting daemon
17:55:16 	daemon.go:279: [d924b90ed254e] exiting daemon
```

Windows https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS1/21104/console failed on a test that looks racy; seen it fail on some others, and looks like it's comparing timestamps (which can obviously fail);


```
17:47:17 ok  	github.com/docker/docker/volume/mounts	0.084s	coverage: 66.9% of statements
17:47:17 --- FAIL: TestServiceGet (0.09s)
17:47:17 	service_test.go:144: assertion failed: 
17:47:17 		{*types.Volume}.CreatedAt:
17:47:17 			-: "2018-06-08T17:46:53Z"
17:47:17 			+: "2018-06-08T17:46:54Z"
17:47:17 		
17:47:17 time="2018-06-08T17:46:54Z" level=warning msg="could not determine size of volume" error="GetFileAttributesEx fake: The system cannot find the file specified." volume=test
17:47:17 time="2018-06-08T17:46:54Z" level=warning msg="could not determine size of volume" error="GetFileAttributesEx fake: The system cannot find the file specified." volume=test
17:47:17 time="2018-06-08T17:46:54Z" level=warning msg="could not determine size of volume" error="GetFileAttributesEx fake: The system cannot find the file specified." volume=test
17:47:17 time="2018-06-08T17:46:54Z" level=warning msg="could not determine size of volume" error="GetFileAttributesEx fake: The system cannot find the file specified." volume=test3
17:47:17 time="2018-06-08T17:46:54Z" level=warning msg="could not determine size of volume" error="GetFileAttributesEx fake: The system cannot find the file specified." volume=test
17:47:17 FAIL
```

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
All green; ignoring codecov

**Comment by tzickel** [comment]
It should be noted that this is a partial fix that does not fix the bug report

**Comment by cpuguy83** [comment]
@dmcgowan I can't remember where exactly now, but... it was blocking on send preventing goroutines from exiting.
