### PR TITLE
Fix flaky test TestJSONFormatProgress (#21124)

### LINKED ISSUE #21124: Flaky test: TestJSONFormatProgress
On Windows TP4 (https://github.com/docker/docker/pull/21106 ) https://jenkins.dockerproject.org/job/Docker-PRs-WoW-TP4/2485/console

```
09:53:39 ok  	github.com/docker/docker/pkg/stdcopy	0.035s	coverage: 100.0% of statements
09:53:39 --- FAIL: TestJSONFormatProgress (0.00s)
09:53:39 	streamformatter_test.go:88: ProgressMessage must be [=========================>                         ]     15 B/30 B 404913h53m30s, got: [=========================>                         ]     15 B/30 B 404913h53m29s
09:53:39 FAIL
09:53:39 coverage: 42.2% of statements
```

Difference is the 1 second at the end;

```
[=========================>                         ]     15 B/30 B 404913h53m30s
[=========================>                         ]     15 B/30 B 404913h53m29s
```

### PR DESCRIPTION
**Pull request by yongtang**
In TestJSONFormatProgress, the progress string was used for comparison.

However, the progress string (progress.String()) uses time.Now().UTC() to generate the timeLeftBox which is not a fixed value and cannot be compared reliably.

This PR fixes the issue by stripping the timeLeftBox field before doing the comparison.

This PR fixes #21124.

Signed-off-by: Yong Tang yong.tang.github@outlook.com

### CODE REVIEW

File: pkg/streamformatter/streamformatter_test.go [hunk 1]
```diff
@@ -84,9 +85,25 @@ func TestJSONFormatProgress(t *testing.T) {
...
+	// Save the progress.String()
+	progressString := progress.String()
+
+	// Find the index before the timeLeftBox
+	stringIndex := strings.LastIndex(progressString, " ")
+	messageIndex := strings.LastIndex(msg.ProgressMessage, " ")
+
+	// Compare the progress strings before the timeLeftBox
+	if msg.ProgressMessage[:messageIndex] != progressString[:stringIndex] {
+		t.Fatalf("ProgressMessage without the timeLeftBox must be %s, got: %s", progressString[:stringIndex], msg.ProgressMessage[:messageIndex])
```
Comment (thaJeztah) [inline pkg/streamformatter/streamformatter_test.go]: Wonder if we should just do;

    strings.HasPrefix(msg.ProgressMessage, progress.String())

Or even

    strings.HasPrefix(msg.ProgressMessage, "[=========================>                         ]     15 B/30 B")


@vdemeester wdyt? (haven't tested the above, just thinking)

Comment (yongtang) [inline pkg/streamformatter/streamformatter_test.go]: Yes I think compare against 
```"[=========================>                         ]     15 B/30 B"```
will do it as the current (15) and total (30) values of the progress are fixed. Let me update the PR.

**Comment by thaJeztah** [comment]
WindowsTP4 failure is a flaky test; https://github.com/docker/docker/issues/20922

File: pkg/streamformatter/streamformatter_test.go [hunk 2]
```diff
@@ -84,9 +85,18 @@ func TestJSONFormatProgress(t *testing.T) {
...
-		t.Fatalf("ProgressMessage must be %s, got: %s", progress.String(), msg.ProgressMessage)
+
+	// The progress will always be in the format of:
+	// [=========================>                         ]     15 B/30 B 404933h7m11s
+	// The last entry '404933h7m11s' is the timeLeftBox.
+	// However, the timeLeftBox field may change as progress.String() depends on time.Now().
+	// Therefore, we have to strip the timeLeftBox from the strings to do the comparison.
+
+	// Compare the progress strings before the timeLeftBox
+	if !strings.HasPrefix(msg.ProgressMessage, "[=========================>                         ]     15 B/30 B") {
```
Comment (vdemeester) [inline pkg/streamformatter/streamformatter_test.go]: You could use a variable for the expected string to not write it twice :angel: :

```go
expectedProgress := "[=========================>                         ]     15 B/30 B"
```

**Comment by thaJeztah** [comment]
LGTM, thanks @yongtang

File: pkg/streamformatter/streamformatter_test.go (hunk 2 above)
Comment (yongtang) [inline pkg/streamformatter/streamformatter_test.go]: Thanks for the suggestion @vdemeester. I just updated the pull request. Let me know if there are any other issues.

**Comment by vdemeester** [comment]
LGTM 🐶, thanks @yongtang

**Comment by calavera** [comment]
LGTM. WindowsTP4 error unrelated, but we're investigating it after merging this.
