### PR TITLE
Fix docker cp when container source path is /

### LINKED ISSUE #39348: Regression due to CVE mitigation from 39292
https://github.com/moby/moby/pull/39292 broke `docker cp` (discovered by @ehazlett trying to run `make` on buildkit repo)

@cpuguy83 @thaJeztah @AkihiroSuda @tonistiigi 

Repro:
```
rm -rf /tmp/out
docker build --iidfile=/tmp/iid - <<EOF
FROM scratch
COPY --from=alpine /etc/os-release /
EOF

cid=$(docker create $(cat /tmp/iid) foo)
mkdir -p /tmp/out
docker cp $cid:/ /tmp/out
ls /tmp/out/os-release
```

### PR DESCRIPTION
**Pull request by tiborvass**
Another attempt at fixing #39348
Fixes #39348
Previous attempt at #39351

Before 7a7357d, archive.TarResourceRebase was being used to copy files
and folders from the container. That function splits the source path
into a dirname + basename pair to support copying a file:
if you wanted to tar `dir/file` it would tar from `dir` the file `file`
(as part of the IncludedFiles option).

However, that path splitting logic was kept for folders as well, which
resulted in weird inputs to archive.TarWithOptions:
if you wanted to tar `dir1/dir2` it would tar from `dir1` the directory
`dir2` (as part of IncludedFiles option).

Although it was weird, it worked fine until we started chrooting into
the container rootfs when doing a `docker cp` with container source set
to `/` (cf 3029e76 (https://github.com/moby/moby/pull/39292)).

The fix is to only do the path splitting logic if the source is a file.

Unfortunately, 7a7357d added support for LCOW by duplicating some of
this subtle logic. Ideally we would need to do more refactoring of the
archive codebase to properly encapsulate these behaviors behind well-
documented APIs.

This fix does not do that. Instead, it fixes the issue inline.

Signed-off-by: Tibor Vass <tibor@docker.com>

I added a couple of more tests than the actual issue needs, just to make sure there are no other regressions compared to before the cve fix (3029e76).

Huge thanks to @cpuguy83 ❤️who worked tirelessly with me to understand the code and make this PR.

### CODE REVIEW

**Comment by cpuguy83** [comment]
```
15:29:30 --- FAIL: TestCopyFromContainerRoot (1.83s)
15:29:30     copy_test.go:146: assertion failed: expression is false: found["/foo"]: /foo file not found in archive
15:29:30     copy_test.go:147: assertion failed: expression is false: found["/bar/baz"]: /bar/baz file not found in archive
```

**Comment by tiborvass** [comment]
Ping @cpuguy83 @thaJeztah @tonistiigi @justincormack

File: pkg/archive/archive_unix.go [hunk 1]
```diff
@@ -26,6 +26,9 @@ func fixVolumePathPrefix(srcPath string) string {
 // can't use filepath.Join(srcPath,include) because this will clean away
 // a trailing "." or "/" which may be important.
 func getWalkRoot(srcPath string, include string) string {
+	if srcPath == string(filepath.Separator) {
```
Comment (tiborvass) [inline pkg/archive/archive_unix.go]: FWIW this is not needed for the main fix. It is just fixing a weird input (`getWalkRoot("/", ".")` used to return `//.`, now just `/.`)

File: daemon/archive.go [hunk 2]
```diff
@@ -426,9 +432,6 @@ func (daemon *Daemon) containerCopy(container *container.Container, resource str
 		d, f := driver.Split(basePath)
 		basePath = d
 		filter = []string{f}
-	} else {
-		filter = []string{driver.Base(basePath)}
```
Comment (thaJeztah) [inline daemon/archive.go]: No filter is needed in this case?

**Review by thaJeztah — CHANGES_REQUESTED** [review]

**Review by cpuguy83 — APPROVED** [review]
LGTM

File: pkg/archive/archive_unix.go [hunk 3]
```diff
@@ -26,6 +26,9 @@ func fixVolumePathPrefix(srcPath string) string {
...
+		return srcPath + include
+	}
 	return srcPath + string(filepath.Separator) + include
```
[the remark this answers is not in the document]
Comment (thaJeztah) [reply pkg/archive/archive_unix.go]: ^^ not a blocker, but worth considering

File: daemon/archive.go (hunk 2 above)
Comment (tiborvass) [reply daemon/archive.go]: This was to keep it symmetrical and I believe is used by older docker CLIs (this codepath is dead code for newer APIs, but not older ones). @cpuguy83 confirmed as well that cp works as intended for an older docker CLI (like 1.8).

File: pkg/archive/archive_unix.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (tiborvass) [reply pkg/archive/archive_unix.go]: In that case I would use strings.Index to determine if there is one, instead of removing it to add it back.

File: daemon/archive.go (hunk 2 above)
Comment (tiborvass) [reply daemon/archive.go]: Correct, because no filter means everything.

File: pkg/archive/archive_unix.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (thaJeztah) [reply pkg/archive/archive_unix.go]: Could work as well; thought there would not be much overhead in normalizing and unconditionally adding

File: pkg/archive/archive_unix.go (hunk 1 above)
Comment (kolyshkin) [reply pkg/archive/archive_unix.go]: Hmm, why can't we just use `path.Join(srcPath, include)` which should handle this and other similar cases? Say, https://play.golang.org/p/jG-JpZ-Kun5

Comment (kolyshkin) [reply pkg/archive/archive_unix.go]: Nevermind, I missed the comment explaining why :man_facepalming:

**Review by tonistiigi — APPROVED** [review]

File: daemon/archive.go [hunk 4]
```diff
@@ -236,7 +236,13 @@ func (daemon *Daemon) containerArchivePath(container *container.Container, path
 	if driver.Base(resolvedPath) == "." {
 		resolvedPath += string(driver.Separator()) + "."
 	}
-	sourceDir, sourceBase := driver.Dir(resolvedPath), driver.Base(resolvedPath)
+
+	sourceDir := resolvedPath
+	sourceBase := "."
+
+	if stat.Mode&os.ModeDir == 0 { // not dir
```
Comment (tonistiigi) [inline daemon/archive.go]: I think this should be

```
if symlink {
opts = rebase
}
```

and always `archivePath(resolvedPath)`.

Would be more understandable what is actually happening and wouldn't need the hack for removing the slash in the walker. But functionally they seem equivalent.

Comment (tiborvass) [reply daemon/archive.go]: Agreed. Can be done in a follow up.

**Comment by tiborvass** [comment]
@thaJeztah @kolyshkin updated with small requested change.

**Comment by tiborvass** [comment]
Failure is TestAPISwarmLeaderElection which is unrelated

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Looks like s390x passed, but is hanging on the cleanup; https://jenkins.dockerproject.org/job/Docker-PRs-s390x/14591/console

```
06:06:03 OK: 1421 passed, 81 skipped
06:06:03 PASS
06:06:03 ---> Making bundle: .integration-daemon-stop (in bundles/test-integration)
06:06:16 Clearing AppArmor profiles cache:.
06:06:16 All profile caches have been cleared, but no profiles have been unloaded.
06:06:16 Unloading profiles will leave already running processes permanently
06:06:16 unconfined, which can lead to unexpected situations.
06:06:16 
06:06:16 To set a process to complain mode, use the command line tool
06:06:16 'aa-complain'. To really tear down all profiles, run the init script
06:06:16 with the 'teardown' option."
06:06:16 Removing test suite binaries
```
