### PR TITLE
Windows: Fix regression pulling linux images

### LINKED ISSUE #26429: Windows: Pulling Ubuntu images no longer provides expected error
Windows daemon should provide an error message when attempting to pull an image based off a Linux base image. This is a regression of the behaviour added in https://github.com/docker/docker/pull/24819.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows daemon

**Steps to reproduce the issue:**
1. docker pull ubuntu

**Describe the results you received:**
```
C:\Users\Administrator>docker pull ubuntu
Using default tag: latest
latest: Pulling from library/ubuntu
952132ac251a: Extracting [==================================================>] 49.73 MB/49.73 MB
82659f8f1b76: Download complete
c19118ca682d: Download complete
8296858250fe: Download complete
24e0251a0e2c: Download complete
failed to register layer: re-exec error: exit status 1: output: Failed to OpenForBackup failed in Win32: open \\?\C:\ProgramData\docker\windowsfilter\f418f4ac43d51c1c1123b48c8025ceb6125e840a0df9f525755e9e55506a586f\usr\share\man\man7\pam.7.gz: The file exists. (0x1f) \\?\C:\ProgramData\docker\windowsfilter\f418f4ac43d51c1c1123b48c8025ceb6125e840a0df9f525755e9e55506a586f\usr\share\man\man7\pam.7.gz
```

**Describe the results you expected:**

Expected an error that states a Linux image cannot be pulled on a Windows platform

/cc @jhowardmsft

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

Fixes #26429.  https://github.com/docker/docker/commit/f342b27145d8f5af27cd5de1501551af275e899b from https://github.com/docker/docker/pull/25090 had regressed the check on Windows when attempting to pull Linux images. The original fix was in https://github.com/docker/docker/pull/24819. 

Re-fixed, and added a test case to make sure this doesn't regress in the future.

@aaronlehmann @stevvooe PTAL. Thanks!

@swernli @darrenstahlmsft FYI.

### CODE REVIEW

**Comment by aaronlehmann** [comment]
One concern I have about reordering this code is that it will cause pulls to wait for the image config to be received before starting to download any layers. This can make the pull take significantly longer overall, because registries often have high latencies (i.e. due to fetching the object from a backend cloud object store).

Originally, the code downloaded the image config first on Windows, so it could get the base layer info that was needed by layer downloads, but it was downloaded concurrently with the layers on Linux. When the base layer stuff was removed, we made both platforms download the layers and image config a the same time (which caused the regression). #26310 did a further cleanup that simplified the code because this OS-specific difference in order of operations no longer exists.

We could go back to having Windows always download the image config first, by reverting #26310 and the relevant part of #25090. But that does move the code back in a more complicated direction, and we'll probably eventually want similar compatibility checks for Linux. On the other hand, it would be unfortunate if Docker 1.13 has slower pulls than Docker 1.12 because of this reordering.

One idea would be to block extraction of any layers until we've retrieved the image config and confirmed that the image is compatible, but that would also add complexity.

I'm not completely sure what do to here.

cc @dmcgowan @tonistiigi

**Comment by dmcgowan** [comment]
While this is mostly a windows specific problem now will we have the same problem if it was a windows image attempted to be pulled on a linux machine? I am OK with in the short term just changing the behavior for windows to pull image config first, but I agree the correct long term fix is to have the config complete before doing the first extraction. Would be worth seeing how complicate the change will be, extractions are already ordered so I wouldn't think it would be a huge change to block the first one.

**Comment by jhowardmsft** [comment]
@aaronlehmann @dmcgowan The change isn't that complicated. Updated. And put a note in there explaining the serialisation, and that it may be necessary to do similar on *nix in the future if a similar check is needed. There shouldn't be any impact to pull performance on *nix with this updated change, and effectively puts it back to where it was before 25090.

File: distribution/pull_v2.go [hunk 1]
```diff
@@ -573,13 +590,15 @@ func (p *v2Puller) pullSchema2(ctx context.Context, ref reference.Named, mfst *s
 	}
 	defer release()
 
-	configJSON, unmarshalledConfig, err = receiveConfig(configChan, errChan)
-	if err != nil {
-		return "", "", err
-	}
+	if runtime.GOOS != "windows" {
```
Comment (aaronlehmann) [inline distribution/pull_v2.go]: This could be `if configJSON == nil` so we don't have to worry about updating the conditional in two places.

**Comment by aaronlehmann** [comment]
In the code handling an error after `DownloadManager.Download`, add this before the select to make sure it doesn't block forever waiting for the config download goroutine again:

```go
		if configJSON != nil {		
			// Already received the config		
			return "", "", err		
		}
```

(see the code removed in #26310)

**Comment by jhowardmsft** [comment]
Ah yes, of course. Updated. Pushing shortly.

File: distribution/pull_v2.go (hunk 1 above)
Comment (jhowardmsft) [inline distribution/pull_v2.go]: Yup, updated. Pushing shortly.

**Comment by jhowardmsft** [comment]
Updated. Thanks for the keen eye on the review :smile:

File: integration-cli/docker_cli_pull_test.go [hunk 2]
```diff
@@ -272,3 +272,10 @@ func (s *DockerRegistryAuthHtpasswdSuite) TestPullNoCredentialsNotFound(c *check
 	c.Assert(err, check.NotNil, check.Commentf(out))
 	c.Assert(out, checker.Contains, "Error: image busybox:latest not found")
 }
+
+// Regression test for https://github.com/docker/docker/issues/26429
+func (s *DockerSuite) TestPullLinuxImageFailsOnWindows(c *check.C) {
+	testRequires(c, DaemonIsWindows)
```
Comment (dmcgowan) [inline integration-cli/docker_cli_pull_test.go]: Also add requirement for network since this will hit the hub

Comment (jhowardmsft) [inline integration-cli/docker_cli_pull_test.go]: Sure, updated.

**Comment by aaronlehmann** [comment]
LGTM

**Comment by dmcgowan** [comment]
LGTM

**Comment by LK4D4** [comment]
Nice! two LGTMs
