### PR TITLE
Inconsistent --tmpfs behavior

### LINKED ISSUE #22420: Inconsistent --tmpfs behavior
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Sat Mar 12 19:18:57 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Sat Mar 12 19:18:57 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 57
Server Version: 1.10.3
Storage Driver: btrfs
 Build Version: Btrfs v4.4.1
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: journald
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.5.1-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.784 GiB
Name: royalarch
ID: 4QHC:NNCF:4N6F:XAXA:CUXL:Y6ZX:YIW5:DPDJ:AXHI:5VPR:DFNZ:ZXV5
Debug mode (server): true
 File Descriptors: 43
 Goroutines: 71
 System Time: 2016-04-29T17:39:26.474624153+02:00
 EventsListeners: 0
 Init SHA1: b8a56fbe8389e4086811723064e36c136fc31d27
 Init Path: /usr/lib/docker/dockerinit
 Docker Root Dir: /var/lib/docker
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical

**Steps to reproduce the issue:**
1. `docker run --rm -it --tmpfs /tmp:rw fedora:23 findmnt /tmp`

**Describe the results you received:**
```
TARGET SOURCE FSTYPE OPTIONS
/tmp   tmpfs  tmpfs  rw,relatime
```

**Describe the results you expected:**
```
TARGET SOURCE FSTYPE OPTIONS
/tmp   tmpfs  tmpfs  rw,nosuid,nodev,noexec,relatime,size=65536k
```

What is wrong? Nothing is mentioned in `--tmpfs` options about `nosuid`, `nodev`, `noexec`, `size` but the values get changed. So it looks like trying to explicitly make `/tmp` `rw` it also changes executability, suidity etc. I expect that only option changed is the one that is put in `--tmpfs` argument list and others are untouched.

**Additional information you deem important (e.g. issue happens only occasionally):**
Nothing I can add here, sorry.

### PR DESCRIPTION
**Pull request by yongtang**
**\- What I did**

This fix tries to address the issue raised in #22420. When `--tmpfs` is specified with `/tmp`, the default value is `rw,nosuid,nodev,noexec,relatime,size=65536k`. When `--tmpfs` is specified with `/tmp:rw`, then the value changed to `rw,nosuid,nodev,noexec,relatime`.

The reason for such an inconsistency is because docker tries to add `size=65536k` option only when user provides no option.

**\- How I did it**

This fix tries to address this issue by always pre-probating `size=65536k` along with `rw,nosuid,nodev,noexec,relatime`. If user provides a different value (e.g., `size=8192k`), it will override the `size=65536k` anyway.

**\- How to verify it**

Additional test cases have been added to cover the changes in this fix.

**\- Description for the changelog**

Address the inconsistent --tmpfs behavior by so that `size=65536k` will always be the default value.

**\- A picture of a cute animal (not mandatory but encouraged)**

This fix fixes #22420.

Signed-off-by: Yong Tang yong.tang.github@outlook.com

### CODE REVIEW

File: daemon/oci_linux.go [hunk 1]
```diff
@@ -463,11 +463,9 @@ func setMounts(daemon *Daemon, s *specs.Spec, c *container.Container, mounts []c
 		}
 
 		if m.Source == "tmpfs" {
-			opt := []string{"noexec", "nosuid", "nodev", volume.DefaultPropagationMode}
+			opt := []string{"noexec", "nosuid", "nodev", volume.DefaultPropagationMode, "size=65536k"}
```
Comment (cpuguy83) [inline daemon/oci_linux.go]: Could you add a test for specifying a custom propagation mode as well?
Also wondering how deterministic the behavior of having duplicate keys is.

Comment (yongtang) [inline daemon/oci_linux.go]: Thanks @cpuguy83 I just added a test for custom propagation mode. Since busybox does not have the `findmnt` I used `debian:jessie` so that 
```
 findmnt -o TARGET,PROPAGATION /tmp
```
could be specified.

I also take a look at the mount command:
http://man7.org/linux/man-pages/man8/mount.8.html
> The usual behavior is that the last option wins if there are conflicting ones.

So I think it should be ok to having duplicate options as long as the last one is the one we want.

Comment (thaJeztah) [inline daemon/oci_linux.go]: The "usual" part bothers me a bit, it sounds like something that *may* be different between distros. So perhaps we should explicitly merge user options with the defaults?

Comment (yongtang) [inline daemon/oci_linux.go]: Thanks @thaJeztah I just updated the PR to merge the duplicate options. Please let me know if there are any issues.

**Comment by yongtang** [comment]
@thaJeztah @cpuguy83 The removal of duplicate options was handled by `MergeTmpfsOptions()` in pkg/mount/flags.go of the updated PR. Please take a look and let me know if there are any issues.

**Comment by thaJeztah** [comment]
Thanks @yongtang, I tested this, and it works correctly. I was a bit unsure if we needed the level of validation that we have now in `MergeTmpfsOptions` (or delegate to Linux and capture errors in case invalid options are specified, if possible), but perhaps it's good to do.

LGTM


ping @cpuguy83 ptal

File: daemon/oci_linux.go [hunk 2]
```diff
@@ -463,13 +463,17 @@ func setMounts(daemon *Daemon, s *specs.Spec, c *container.Container, mounts []c
 		}
 
 		if m.Source == "tmpfs" {
-			opt := []string{"noexec", "nosuid", "nodev", volume.DefaultPropagationMode}
+			options := "noexec,nosuid,nodev," + volume.DefaultPropagationMode + ",size=65536k"
```
Comment (LK4D4) [inline daemon/oci_linux.go]: I don't understand point of using string here if you're immediately splitting it in `MergeTmpfsOptions`

File: pkg/mount/flags.go [hunk 3]
```diff
@@ -5,6 +5,111 @@ import (
...
+	"runbindable": true,
+	"private":     true,
+	"rprivate":    true,
+	"shared":      true,
+	"rshared":     true,
+	"slave":       true,
+	"rslave":      true,
+}
+
+// MergeTmpfsOptions merge mount options to make sure there is no duplicate.
```
Comment (LK4D4) [inline pkg/mount/flags.go]: I wonder if it's specific to `tmpfs` or more generic merge function?

File: pkg/mount/flags.go [hunk 4]
```diff
@@ -5,6 +5,111 @@ import (
...
+
+	// We use collisions maps to remove duplicates.
+	// For flag, the key is the flag value (the key for propagation flag is -1)
+	// For data=value, the key is the data
+	flagCollisions := map[int]bool{}
+	dataCollisions := map[string]bool{}
+
+	var newOptions []string
+	// We process in reverse order
+	for i := 0; i < len(oldOptions); i++ {
```
Comment (LK4D4) [inline pkg/mount/flags.go]: Why don't just go from `len(oldOptions)-1` to `0`?

File: pkg/mount/flags.go [hunk 5]
```diff
@@ -5,6 +5,111 @@ import (
...
+		option := oldOptions[len(oldOptions)-1-i]
+		if f, ok := flags[option]; ok && f.flag != 0 {
+			// There is only one propagation mode
+			key := f.flag
+			if _, ok := propagationFlags[option]; ok {
+				key = -1
+			}
+			// Check to see if there is collision for flag
+			if _, ok := flagCollisions[key]; !ok {
```
Comment (LK4D4) [inline pkg/mount/flags.go]: this can be just `!flagCollistions[key]`

File: pkg/mount/flags.go [hunk 6]
```diff
@@ -5,6 +5,111 @@ import (
...
+
+	var newOptions []string
+	// We process in reverse order
+	for i := 0; i < len(oldOptions); i++ {
+		option := oldOptions[len(oldOptions)-1-i]
+		if f, ok := flags[option]; ok && f.flag != 0 {
+			// There is only one propagation mode
+			key := f.flag
+			if _, ok := propagationFlags[option]; ok {
+				key = -1
```
Comment (LK4D4) [inline pkg/mount/flags.go]: I'm not sure that I understand trick here :/ Doesn't it mean that only first propagation flag will be added?

File: daemon/oci_linux.go (hunk 2 above)
Comment (yongtang) [inline daemon/oci_linux.go]: Thanks @LK4D4. The pull request has been updated to use `[]string` directly.

File: pkg/mount/flags.go (hunk 3 above)
Comment (yongtang) [inline pkg/mount/flags.go]: @LK4D4 The MergeTmpfsOptions here can only be used for tmpfs. Command `mount` consists of both filesystem independent options and filesystem specific options. However, the possible scope of the filesystem specific options are very large:
http://man7.org/linux/man-pages/man8/mount.8.html

The implementation in this pull request only covers tmpfs specific options.

File: pkg/mount/flags.go (hunk 4 above)
Comment (yongtang) [inline pkg/mount/flags.go]: Thanks @LK4D4. Just updated the pull request to cover this issue.

File: pkg/mount/flags.go (hunk 5 above)
Comment (yongtang) [inline pkg/mount/flags.go]: Thanks @LK4D4 the pull request has been updated to simplify the check.

File: pkg/mount/flags.go (hunk 6 above)
Comment (yongtang) [inline pkg/mount/flags.go]: Thanks @LK4D4. This line (Ln 87) is to see if the current option being checked belongs to propagationFlags or not. If it belongs to propagationFlags then `-1` will be used to check the `key` for collision. The actual check of collision is done in the following (Ln 90).

Since the iteration is done in reverse order, only the the first encountered propagation flag (the last of the array) will stay.

**Comment by yongtang** [comment]
Thanks for the review @LK4D4. The pull request has been updated to cover the raised issues. Please let me know if there are any other issues.

File: pkg/mount/flags.go (hunk 3 above)
Comment (LK4D4) [inline pkg/mount/flags.go]: Yup, thanks, probably just bad place for those functions.

File: pkg/mount/flags.go [hunk 7]
```diff
@@ -5,6 +5,109 @@ import (
...
+	dataCollisions := map[string]bool{}
+
+	var newOptions []string
+	// We process in reverse order
+	for i := len(options) - 1; i >= 0; i-- {
+		option := options[i]
+		if f, ok := flags[option]; ok && f.flag != 0 {
+			// There is only one propagation mode
+			key := f.flag
+			if _, ok := propagationFlags[option]; ok {
```
Comment (LK4D4) [inline pkg/mount/flags.go]: `if propagationFlags[option]`

File: pkg/mount/flags.go [hunk 8]
```diff
@@ -5,6 +5,109 @@ import (
...
+				// We prepend the option and add to collision map
+				newOptions = append([]string{option}, newOptions...)
+				flagCollisions[key] = true
+			}
+		} else {
+			opt := strings.SplitN(option, "=", 2)
+			if len(opt) != 2 || !validFlags[opt[0]] {
+				return nil, fmt.Errorf("Invalid tmpfs option %q", opt)
+			}
+			if _, ok := dataCollisions[opt[0]]; !ok {
```
Comment (LK4D4) [inline pkg/mount/flags.go]: `if !dataCollisions...`

File: pkg/mount/flags.go [hunk 9]
```diff
@@ -5,6 +5,109 @@ import (
...
+				key = -1
+			}
+			// Check to see if there is collision for flag
+			if !flagCollisions[key] {
+				// We prepend the option and add to collision map
+				newOptions = append([]string{option}, newOptions...)
+				flagCollisions[key] = true
+			}
+		} else {
+			opt := strings.SplitN(option, "=", 2)
```
Comment (LK4D4) [inline pkg/mount/flags.go]: if I understand correctly `defaults` flag will come here, right?

File: pkg/mount/flags.go [hunk 10]
```diff
@@ -5,6 +5,109 @@ import (
...
+			key := f.flag
+			if _, ok := propagationFlags[option]; ok {
+				key = -1
+			}
+			// Check to see if there is collision for flag
+			if !flagCollisions[key] {
+				// We prepend the option and add to collision map
+				newOptions = append([]string{option}, newOptions...)
+				flagCollisions[key] = true
+			}
```
Comment (LK4D4) [inline pkg/mount/flags.go]: put continue here and remove else.

File: pkg/mount/mount_unix_test.go [hunk 11]
```diff
@@ -137,3 +137,26 @@ func TestGetMounts(t *testing.T) {
 		t.Fatal("/ should be mounted at least")
 	}
 }
+
+func TestMergeTmpfsOptions(t *testing.T) {
+	options := []string{"noatime", "ro", "size=10k", "atime", "rw", "rprivate", "size=1024k", "slave"}
```
Comment (LK4D4) [inline pkg/mount/mount_unix_test.go]: please include `defaults` here.

File: pkg/mount/flags.go (hunk 9 above)
Comment (yongtang) [inline pkg/mount/flags.go]: Thanks @LK4D4. The `defaults` will goes here and will result in an error. This is the same behavior as docker `1.11.1`. For example, the following command with docker `1.11.1` will return:
```
$ sudo docker run --rm -it --tmpfs /tmp:defaults fedora:23 findmnt /tmp
docker: Invalid tmpfs option ["defaults"].
See 'docker run --help'.
```

I do notice that `mount` itself actually allows to specify the `defaults` and will treat as if it `defaults` is not specified. For example:
```
$ sudo mount -t tmpfs -o defaults,defaults,defaults tmpfs /tmp1
$ findmnt /tmp1
TARGET SOURCE FSTYPE OPTIONS
/tmp1  tmpfs  tmpfs  rw,relatime
```


```
$ sudo mount -t tmpfs -o defaults,defaults,ro,defaults tmpfs /tmp1
$ findmnt /tmp1
TARGET SOURCE FSTYPE OPTIONS
/tmp1  tmpfs  tmpfs  ro,relatime
```
Maybe we should support `defaults` as well?

File: pkg/mount/flags.go (hunk 10 above)
Comment (yongtang) [inline pkg/mount/flags.go]: Thanks @LK4D4 just updated the pull request.

File: pkg/mount/flags.go (hunk 8 above)
Comment (yongtang) [inline pkg/mount/flags.go]: Thanks @LK4D4 the PR has been updated.

File: pkg/mount/flags.go (hunk 7 above)
Comment (yongtang) [inline pkg/mount/flags.go]: Updated the PR. Thanks @LK4D4.

**Comment by yongtang** [comment]
Thanks @LK4D4 for the review. I updated the pull request and covered most of the issues.

For the `defaults` case, I noticed that in Docker `1.11.1` this option is treated as an error case.

Let me know if we want to make the change for `defaults` (as the behavior will be slightly different) and I will update the pull request accordingly.

File: pkg/mount/flags.go [hunk 12]
```diff
@@ -5,6 +5,109 @@ import (
...
+			continue
+		}
+		opt := strings.SplitN(option, "=", 2)
```
Comment (LK4D4) [inline pkg/mount/flags.go]: I had a comment here about "defaults", it has `f.flag == 0`, so this func will return error.

File: pkg/mount/mount_unix_test.go (hunk 11 above)
Comment (LK4D4) [inline pkg/mount/mount_unix_test.go]: That's why I asked to add it here.

File: pkg/mount/flags.go (hunk 12 above)
Comment (yongtang) [inline pkg/mount/flags.go]: Thanks @LK4D4. I had some confusion initially. The pull request has been updated.

**Comment by yongtang** [comment]
Thanks @LK4D4 the pull request has been updated. Please let me know if there are any other issues.

**Comment by LK4D4** [comment]
LGTM
janky failure is unrelated
Thanks @yongtang !

**Comment by cpuguy83** [comment]
LGTM

**Comment by thaJeztah** [comment]
:tada: thank you so much @yongtang!
