### PR TITLE
cgroup2: unshare cgroupns by default regardless to API version

### LINKED ISSUE #41071: cgroup2: cgroupns is not unshared when DOCKER_API_VERSION < 1.41
**Description**

Docker is expected to unshare cgroup namespace by default on cgroup v2 hosts.
However, the cgroup namespace is not unshared when a container was created by an older API client.

**Steps to reproduce the issue:**
Inspect the host cgroup namespace (4026531835):
```console
$ sudo ls -l /proc/1/ns/cgroup
lrwxrwxrwx 1 root root 0 Jun  5 16:36 /proc/1/ns/cgroup -> 'cgroup:[4026531835]'
```

API 1.41 creates a container with a new namespace (4026533000) as expected:
```console
$ DOCKER_API_VERSION=1.41 docker run --rm alpine ls -l /proc/1/ns/cgroup
lrwxrwxrwx    1 root     root             0 Jun  5 07:36 /proc/1/ns/cgroup -> cgroup:[4026533000]
```

OTOH API 1.40 creates a container with the host cgroup namespace (4026531835):
```console
$ DOCKER_API_VERSION=1.40 docker run --rm alpine ls -l /proc/1/ns/cgroup
lrwxrwxrwx    1 root     root             0 Jun  5 07:36 /proc/1/ns/cgroup -> cgroup:[4026531835]
```

**Describe the results you received:**
API 1.40 creates a container with the host cgroup namespace (4026531835).

**Describe the results you expected:**
A new cgroup namespace should be always created by default on cgroup v2 hosts..

**Output of `docker version`:**

```
Client:
 Version:           20.03.0-dev
 API version:       1.41
 Go version:        go1.13.11
 Git commit:        8f14db8df
 Built:             Fri Jun  5 07:30:25 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          dev
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.11
  Git commit:       fa38a6cd21
  Built:            Fri Jun  5 07:28:36 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.4.0-beta.1-18-g38cb1c1a
  GitCommit:        38cb1c1a54e3180edd29933974d715b69334f0f1
 runc:
  Version:          1.0.0-rc10+dev
  GitCommit:        2a0466958d9af23af2ad12bd79d06ed0af4091e2
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.4.1)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: dev
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 38cb1c1a54e3180edd29933974d715b69334f0f1
 runc version: 2a0466958d9af23af2ad12bd79d06ed0af4091e2
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.4.0-33-generic
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.748GiB
 Name: suda-ws01
 ID: E2YB:EGZO:6BNW:EPHS:4WFQ:EIDV:ZZ6D:QBZK:6673:CIOR:DLZ6:SI3D
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 32
  Goroutines: 56
  System Time: 2020-06-05T16:42:51.430978282+09:00
  EventsListeners: 0
 Username: akihirosuda
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No kernel memory limit support
WARNING: No kernel memory TCP limit support
WARNING: No oom kill disable support
WARNING: Support for cgroup v2 is experimental
```

### PR DESCRIPTION
**Pull request by AkihiroSuda**
**- What I did**
Fix #41071

[cgroup2 mode sets `cgroupns=private` by default ](https://github.com/moby/moby/blob/fa38a6cd21fec539066a2e3429b98b33f6427dfe/cmd/dockerd/config_unix.go#L68-L72]), but the default was overridden to `host` when API < 1.41.

**- How to verify it**

```console
$ sudo ls -l /proc/1/ns/cgroup
lrwxrwxrwx 1 root root 0 Jun  5 18:04 /proc/1/ns/cgroup -> 'cgroup:[4026531835]'
$ DOCKER_API_VERSION=1.40 docker run --rm alpine ls -l /proc/1/ns/cgroup
lrwxrwxrwx    1 root     root             0 Jun  5 09:04 /proc/1/ns/cgroup -> cgroup:[4026532639]
```

**- A picture of a cute animal (not mandatory but encouraged)**
:penguin:

### CODE REVIEW

File: api/server/router/container/container_routes.go [hunk 1]
```diff
@@ -498,8 +499,8 @@ func (s *containerRouter) postContainersCreate(ctx context.Context, w http.Respo
 		}
 	}
 	if hostConfig != nil && versions.LessThan(version, "1.41") {
-		// Older clients expect the default to be "host"
-		if hostConfig.CgroupnsMode.IsEmpty() {
+		// Older clients expect the default to be "host" on cgroup v1 hosts
+		if hostConfig.CgroupnsMode.IsEmpty() && !cgroups.IsCgroup2UnifiedMode() {
 			hostConfig.CgroupnsMode = container.CgroupnsMode("host")
```
Comment (thaJeztah) [inline api/server/router/container/container_routes.go:504]: IIUC, cgroupv2 does not support "non-private"?

So, should we handle this when creating the actual container (as well / instead) ? Thinking of a scenario where a container was created with an older API version and the host is running cgroupv1, then the host is switched to cgroupv2. In that case existing containers would no longer be functional?

Comment (AkihiroSuda) [reply api/server/router/container/container_routes.go:504]: v2 still supports `--cgroupns=host`, we just switched the default

Comment (thaJeztah) [reply api/server/router/container/container_routes.go:503]: Ignoring the API version means that we change behaviour of an already release API version?

File: cmd/dockerd/daemon.go [hunk 2]
```diff
@@ -462,7 +462,7 @@ func initRouter(opts routerOptions) {
 	routers := []router.Router{
 		// we need to add the checkpoint router before the container router or the DELETE gets masked
 		checkpointrouter.NewRouter(opts.daemon, decoder),
-		container.NewRouter(opts.daemon, decoder),
+		container.NewRouter(opts.daemon, decoder, opts.daemon.RawSysInfo(true).CgroupUnified),
```
Comment (thaJeztah) [inline cmd/dockerd/daemon.go:465]: We already pass `opts.daemon` here, should we just use that inside `NewRouter` ?

File: api/server/router/container/container_routes.go (hunk 1 above)
Comment (AkihiroSuda) [reply api/server/router/container/container_routes.go:503]: Yes and no, depending on the definition of the previous behavior.
Yes if we define the previous behavior as `always defaults to "host"`".  
No if `defaults to the most typical config, depending on the cgroup version`.

As there hadn't been support for cgroup v2 in previous versions, it is hard to say which definition is correct.
In this PR, I adopted the latter definition.

File: cmd/dockerd/daemon.go (hunk 2 above)
Comment (AkihiroSuda) [reply cmd/dockerd/daemon.go:465]: I'm not sure. It might not be consistent with router `Backend` interfaces.

**Comment by thaJeztah** [comment]
ping @kolyshkin PTAL

File: api/server/router/container/container_routes.go (hunk 1 above)
Comment (kolyshkin) [reply api/server/router/container/container_routes.go:503]: Since we haven't supported cgroupv2 before, I think there is no expectation that cgroupv2 default will be different for older API version

File: api/server/router/container/container_routes.go [hunk 3]
```diff
@@ -497,8 +497,8 @@ func (s *containerRouter) postContainersCreate(ctx context.Context, w http.Respo
 			hostConfig.IpcMode = container.IpcMode("shareable")
 		}
 	}
-	if hostConfig != nil && versions.LessThan(version, "1.41") {
-		// Older clients expect the default to be "host"
+	if hostConfig != nil && versions.LessThan(version, "1.41") && !s.cgroup2 {
```
Comment (kolyshkin) [inline api/server/router/container/container_routes.go:500]: I would just use `cgroups.IsCgroup2UnifiedMode()` right here. It's a very cheap call and we're definitely on the same host, and there's no need to pass the data around

File: cmd/dockerd/daemon.go (hunk 2 above)
Comment (kolyshkin) [reply cmd/dockerd/daemon.go:465]: Please see my suggestion above. If you don't like it, at least use `cgroups.IfCgroupUnifiedMode()` here, as RawSysInfo() is relatively expensive call and we only use a tiny bit of info it provides here.

File: api/server/router/container/container_routes.go (hunk 3 above)
Comment (kolyshkin) [reply api/server/router/container/container_routes.go:500]: ... and maybe put `!cgroups.IsCgroup2UnifiedMode()` before the version check since it's a cheaper check to make.

Comment (AkihiroSuda) [reply api/server/router/container/container_routes.go:500]: I'm not sure. The router interface is designed to be decoupled from the host codes.

**Review by kolyshkin — CHANGES_REQUESTED** [review]
Can simplify it a lot by using `cgroups.IsCgroup2UnifiedMode()` in place

File: api/server/router/container/container_routes.go (hunk 3 above)
Comment (kolyshkin) [reply api/server/router/container/container_routes.go:500]: You're right.

I think the best way then is to leave all this as is, just replacing `opts.daemon.RawSysInfo(true).CgroupUnified` with `cgroups.IfCgroupUnifiedMode()` in `initRouter()` as suggested below in https://github.com/moby/moby/pull/41072/commits/938a00ffcd50932a40c92e97d875274a12599709#r439165398.

There are a few other ways to handle it, such as forcibly set hostconfig.CgroupfsMode to private in container's hostconfig if it is not set and cgroupv2 is used, but I like it less.

Comment (AkihiroSuda) [reply api/server/router/container/container_routes.go:500]: updated

File: cmd/dockerd/daemon.go (hunk 2 above)
Comment (AkihiroSuda) [reply cmd/dockerd/daemon.go:465]: updated

File: api/server/router/container/container_routes.go (hunk 3 above)
Comment (AkihiroSuda) [reply api/server/router/container/container_routes.go:500]: reverted due to compilation failure on Windows

**Comment by AkihiroSuda** [comment]
@kolyshkin That package only compiles on Linux and cannot be imported in ` cmd/dockerd/daemon.go`.

**Comment by AkihiroSuda** [comment]
@kolyshkin @thaJeztah @cpuguy83 PTAL

**Comment by cpuguy83** [comment]
Should this be in the router? If we are doing this regardless of API version, seems like the router doesn't need to know about v2.

**Comment by thaJeztah** [comment]
^ good point

**Comment by kolyshkin** [comment]
> Should this be in the router? If we are doing this regardless of API version, seems like the router doesn't need to know about v2.

It's the router who resets the `cgroupns=private` (default for cgroupv2) setting for older clients. Chances are, older clients don't know/care about cgroupv2, so the reset should only be done for cgroupv1, thus the need for router to know whether its v1 or v2.

**Review by kolyshkin — APPROVED** [review]
LGTM

**Comment by cpuguy83** [comment]
I don't think we should contort the router to have system level information because we can't tell if a value passed from the router is a default value or not.

**Comment by kolyshkin** [comment]
> I don't think we should contort the router to have system level information

So, you are suggesting we should perform the change somewhere else. Fine, but...

> we can't tell if a value passed from the router is a default value or not

...this is exactly what the problem is. We do not know if a `cgroupns` value that comes from the router is default or not, so we don't know if we need to change it or not :-\

IOW, if you don't like the way how it's currently done, can you please propose an alternative way to do the same thing?

**Comment by cpuguy83** [comment]
Maybe not perfect for future (albeit highly unlikely to have changes around this case), but telling the router what the default should be seems cleaner.

I also opened https://github.com/moby/moby/issues/41129 to discuss how to handle this across the board because it is problematic in other places as well.

**Comment by AkihiroSuda** [comment]
Can we merge this PR and discuss the router design in  https://github.com/moby/moby/issues/41129 ?

**Comment by cpuguy83** [comment]
I would rather not add extra compexity like this just to get the change in.
I think it's also a bit of a stretch to make this change to older API versions.

**Comment by justincormack** [comment]
Its not safe to run cgroupsv2 unnamespaced it appears, so I think we have to make this change for previous API versions.

**Comment by cpuguy83** [comment]
@justincormack I was curious about that. Good catch.

So we can implement this totally in the daemon and not touch the API side.

**Comment by AkihiroSuda** [comment]
>  not touch the API side.

API server has `if hostConfig.CgroupnsMode.IsEmpty() { hostConfig.CgroupnsMode = container.CgroupnsMode("host") }` , so this PR modifies API server to disable this block for cgroup v2

**Review by kolyshkin — APPROVED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM

It'd be nice to rework this a bit, but we need this in.
