### PR TITLE
Return error code when `volume inspect` fails with a template.

### LINKED ISSUE #18328: volume inspect with bad format should return nonzero code
Hi,

If, for example, I trying to inspect not existing container return code is 1, which is ok:
```
$ docker volume inspect -f "{{ .Mountpoint }}" non-existent-container
$ echo $?
1
```

But if I inspect with bad format string, return code is 0:
```
$ docker volume inspect -f "{{ .Bad }}" existing-container
$ echo $?
0
```

Return nonzero codes on any errors important for managment tools like Ansible.

```
$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64
```

### PR DESCRIPTION
**Pull request by calavera**
Following `docker inspect` conventions:
- Keep partial info in a buffer to not print incomplete template outputs.
- Break execution when template parsing or decoding fail.

Fixes #18328

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by calavera** [comment]
@cpuguy83 you might want to take a look at this patch :wink:

**Comment by LK4D4** [comment]
LGTM

File: integration-cli/docker_cli_volume_test.go [hunk 1]
```diff
@@ -165,3 +165,13 @@ func (s *DockerSuite) TestVolumeCliNoArgs(c *check.C) {
 	c.Assert(stderr, checker.Contains, usage)
 	c.Assert(stderr, checker.Contains, "flag provided but not defined: --no-such-flag")
 }
+
+func (s *DockerSuite) TestVolumeCliInspectTmplError(c *check.C) {
+	out, _ := dockerCmd(c, "volume", "create")
+	name := strings.TrimSpace(out)
+
+	out, exitCode, err := dockerCmdWithError("volume", "inspect", "--format='{{ .FooBar }}'", name)
+	c.Assert(err, checker.NotNil, check.Commentf("%s", exitCode))
```
Comment (cpuguy83) [inline integration-cli/docker_cli_volume_test.go]: %d instead of %s

Comment (cpuguy83) [inline integration-cli/docker_cli_volume_test.go]: Also maybe `out` as well so when there is an error hopefully it will give us some detail.

File: integration-cli/docker_cli_volume_test.go [hunk 2]
```diff
@@ -165,3 +165,13 @@ func (s *DockerSuite) TestVolumeCliNoArgs(c *check.C) {
...
+	c.Assert(exitCode, checker.Equals, 1, check.Commentf("%s", err))
```
Comment (cpuguy83) [inline integration-cli/docker_cli_volume_test.go]: `err` here will just say `exit code <code>` and is not helpful.

**Comment by cpuguy83** [comment]
Couple of nits in the tests, otherwise LGTM

**Comment by calavera** [comment]
@cpuguy83 I added the output to both checkers, I think it's more useful than any other comment.

**Comment by cpuguy83** [comment]
LGTM

**Comment by calavera** [comment]
Self :pray: :tada:
