### PR TITLE
Fix panic in parsing /etc/os-release

### LINKED ISSUE #16690: crash on parsing incorrect /etc/os-release file
Docker 1.8.2 built from source, on x86_64.

```
time="2015-10-01T07:30:11.123679154+03:00" level=info msg="GET /v1.20/info" 
2015/10/01 07:30:11 http: panic serving @: runtime error: slice bounds out of range
goroutine 56 [running]:
net/http.func·011()
	/opt/go/src/net/http/server.go:1130 +0xbb
github.com/docker/docker/pkg/parsers/operatingsystem.GetOperatingSystem(0x0, 0x0, 0x0, 0x0)
	/usr/src/docker-1.8.2/.gopath/src/github.com/docker/docker/pkg/parsers/operatingsystem/operatingsystem_linux.go:24 +0x230
github.com/docker/docker/daemon.(*Daemon).SystemInfo(0xc2080a3260, 0xc2082385a0, 0x0, 0x0)
	/usr/src/docker-1.8.2/.gopath/src/github.com/docker/docker/daemon/info.go:33 +0xf8
github.com/docker/docker/api/server.(*Server).getInfo(0xc20809ef40, 0xc20827b606, 0x4, 0x7f0817e61d00, 0xc2081f2460, 0xc2080bc9c0, 0xc208246720, 0x0, 0x0)
	/usr/src/docker-1.8.2/.gopath/src/github.com/docker/docker/api/server/server.go:377 +0x43
github.com/docker/docker/api/server.*Server.(github.com/docker/docker/api/server.getInfo)·fm(0xc20827b606, 0x4, 0x7f0817e61d00, 0xc2081f2460, 0xc2080bc9c0, 0xc208246720, 0x0, 0x0)
	/usr/src/docker-1.8.2/.gopath/src/github.com/docker/docker/api/server/server.go:1634 +0x7b
github.com/docker/docker/api/server.func·008(0x7f0817e61d00, 0xc2081f2460, 0xc2080bc9c0)
	/usr/src/docker-1.8.2/.gopath/src/github.com/docker/docker/api/server/server.go:1614 +0xc8f
net/http.HandlerFunc.ServeHTTP(0xc20814dd40, 0x7f0817e61d00, 0xc2081f2460, 0xc2080bc9c0)
	/opt/go/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc208138c30, 0x7f0817e61d00, 0xc2081f2460, 0xc2080bc9c0)
	/usr/src/docker-1.8.2/vendor/src/github.com/gorilla/mux/mux.go:98 +0x297
net/http.serverHandler.ServeHTTP(0xc2081042a0, 0x7f0817e61d00, 0xc2081f2460, 0xc2080bc9c0)
	/opt/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2081f23c0)
	/opt/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/opt/go/src/net/http/server.go:1751 +0x35e
```

Steps to reproduce:
1. create some not well-formed /etc/os-release file, containing, e.g. `PRETTY_NAME=Source Mage GNU/Linux
` instead of: `PRETTY_NAME="Source Mage GNU/Linux"`
2. run `docker info`

### PR DESCRIPTION
**Pull request by vdemeester**
Fixes #16690

I'm not sure if this is the right way to handle that : If the `/etc/os-release` file is not well-formed in a way that still might be used (like with `PRETTY_NAME=Source Mage GNU/Linux`), this makes it currently throw an error (and return a blank name).

Signed-off-by: Vincent Demeester vincent@sbr.pm

### CODE REVIEW

File: pkg/parsers/operatingsystem/operatingsystem_linux.go [hunk 1]
```diff
@@ -24,6 +24,11 @@ func GetOperatingSystem() (string, error) {
 	}
 	if i := bytes.Index(b, []byte("PRETTY_NAME")); i >= 0 {
 		b = b[i+13:]
```
Comment (phemmer) [inline pkg/parsers/operatingsystem/operatingsystem_linux.go]: This can still panic right here if `b` is less than 13 characters (e.g. `PRETTY_NAME`, with nothing after it)

**Comment by phemmer** [comment]
The standard on this file is defined at http://www.freedesktop.org/software/systemd/man/os-release.html
The proposal in this PR doesn't follow that. Quotes on values are not required, and quotes can be either double, or single.

Perhaps it would be better to use something like https://github.com/mattn/go-shellwords for parsing.

**Comment by duglin** [comment]
if you're looking for space & quote parsers, we have one in the builder.

File: pkg/parsers/operatingsystem/operatingsystem_linux.go (hunk 1 above)
Comment (vdemeester) [inline pkg/parsers/operatingsystem/operatingsystem_linux.go]: @phemmer oh you're right.. I'll add a test for that too. :wink:

**Comment by vdemeester** [comment]
@phemmer oh, thanks for the pointer ! I'll update the PR (and thus the code) to follow it then.
@duglin taking a look :stuck_out_tongue:

**Comment by vdemeester** [comment]
Updated according to @phemmer comments : handle the case with or without double quotes `"`, and return "Linux" by default if not found (it changes a bit the rest so i wonder about this change, but it's to be more close to http://www.freedesktop.org/software/systemd/man/os-release.html).

**Comment by phemmer** [comment]
It still has a few important (in my own opinion) issues:

* Single quotes aren't handled.
* `PRETTY_NAME=foo bar` will parse as `foo bar` instead of throwing an error (maybe this is what we want, but the spec doesn't allow it).
* `PRETTY_NAME="foo` (no trailing quote) will parse as `foo` instead of throwing an error (again, maybe this is intentional).

A shellwords parser, or this other thing @duglin alluded to would help solve these, along with other minor issues I didn't bother mentioning.

**Comment by vdemeester** [comment]
> Single quotes aren't handled.

True :sweat:.

> PRETTY_NAME=foo bar will parse as foo bar instead of throwing an error, or parsing as just foo (maybe this is what we want, but the spec doesn't allow it).

Ah true, misread a bit the `man`.

> PRETTY_NAME="foo (no trailing quote) will parse as foo instead of throwing an error (again, maybe this is intentional).

True.

Back to the drawing board, thanks again (and again :stuck_out_tongue_closed_eyes: and multiple more time by anticipation) for the review @phemmer.

**Comment by vdemeester** [comment]
@phemmer [go-shellwords](https://github.com/mattn/go-shellwords/) looks cool but it does shell expansion that http://www.freedesktop.org/software/systemd/man/os-release.html tells to not support. And there is no way to tell it not to do it. But I'll probably have to implement something similar (but simpler).

> The basic file format of os-release is a newline-separated list of environment-like shell-compatible variable assignments. It is possible to source the configuration from shell scripts, however, beyond mere variable assignments, no **shell features are supported** (**this means variable expansion is explicitly not supported**), allowing applications to read the file without implementing a shell compatible execution engine. Variable assignment values must be enclosed in double or single quotes if they include spaces, semicolons or other special characters outside of A-Z, a-z, 0-9. Shell special characters ("$", quotes, backslash, backtick) must be escaped with backslashes, following shell style. All strings should be in UTF-8 format, and non-printable characters should not be used. It is not supported to concatenate multiple individually quoted strings. Lines beginning with "#" shall be ignored as comments.

@duglin Not sure which function you're talking about : is it `parseWords` or could you point me to it :sweat_smile: ?

**Comment by phemmer** [comment]
@vdemeester: you have to explicitly turn on variable expansion for it to do that.

**Comment by vdemeester** [comment]
@phemmer oh you're right.. I mis-read the source :sweat:

**Comment by duglin** [comment]
@vdemeester yes builder.parseWords() should split a line of text up into words - taking into account quotes, spaces, \\'s etc...

**Comment by vdemeester** [comment]
@phemmer with go-shellwords it's kinda easy to implement. I hope I got most of the case in the testcases.

I'm taking a look using `ParseWords` from `builder/parser` package but feels a little harder/hacky to handle.

**Comment by LK4D4** [comment]
LGTM

**Comment by thaJeztah** [comment]
ping @duglin PTAL

File: pkg/parsers/operatingsystem/operatingsystem_linux.go [hunk 2]
```diff
@@ -18,15 +23,29 @@ var (
...
 	}
-	if i := bytes.Index(b, []byte("PRETTY_NAME")); i >= 0 {
-		b = b[i+13:]
-		return string(b[:bytes.IndexByte(b, '"')]), nil
+	defer osReleaseFile.Close()
+
+	scanner := bufio.NewScanner(osReleaseFile)
+	for scanner.Scan() {
+		line := scanner.Text()
+		if strings.HasPrefix(line, "PRETTY_NAME") {
```
Comment (duglin) [inline pkg/parsers/operatingsystem/operatingsystem_linux.go]: I think this should be "PRETTY_NAME=" so that we don't pickup "PRETTY_NAME_FOO" by mistake since I believe can extend the file with new fields.

File: pkg/parsers/operatingsystem/operatingsystem_linux.go [hunk 3]
```diff
@@ -18,15 +23,29 @@ var (
...
+			data := strings.SplitN(line, "=", 2)
+			if len(data) == 2 {
+				prettyNames, err := shellwords.Parse(data[1])
+				if err == nil && len(prettyNames) == 1 {
+					return prettyNames[0], nil
+				}
```
Comment (duglin) [inline pkg/parsers/operatingsystem/operatingsystem_linux.go]: I think we should return "err" here so that people know why we didn't like the value.

File: pkg/parsers/operatingsystem/operatingsystem_linux.go [hunk 4]
```diff
@@ -18,15 +23,29 @@ var (
...
+			}
+			return "", fmt.Errorf("PRETTY_NAME is invalid")
```
Comment (duglin) [inline pkg/parsers/operatingsystem/operatingsystem_linux.go]: Can we elaborate on why its invalid?  Although, if we add "=" to the "HasPrefix" up above, I think the `if len(data) == 2` will always be `true` and we'll never get here.
If you're worried about the case of an invalid file where they just have `PRETTY_NAME` on a line all by itself (w/o "=") then you could add a specific check for that:
```
if line == "PRETTY_NAME" {
  return "", fmt.Errorf("PRETTY_NAME property is missing '=value'")
}
```
before line 35.

File: pkg/parsers/operatingsystem/operatingsystem_linux.go (hunk 2 above)
Comment (phemmer) [inline pkg/parsers/operatingsystem/operatingsystem_linux.go]: What about splitting first, and then `if data[0] == "PRETTY_TEXT"`.

Comment (duglin) [inline pkg/parsers/operatingsystem/operatingsystem_linux.go]: that works too :-)

Comment (vdemeester) [inline pkg/parsers/operatingsystem/operatingsystem_linux.go]: Hum right, didn't though of that :smile_cat:

File: pkg/parsers/operatingsystem/operatingsystem_linux.go (hunk 3 above)
Comment (vdemeester) [inline pkg/parsers/operatingsystem/operatingsystem_linux.go]: fair enough :)

**Comment by vdemeester** [comment]
@duglin @phemmer  Updated :wink:

File: pkg/parsers/operatingsystem/operatingsystem_test.go [hunk 5]
```diff
@@ -8,34 +8,98 @@ import (
...
+ID_LIKE=debian
+PRETTY_NAME='Ubuntu 14.04 LTS'`,
+			"Ubuntu 14.04 LTS",
+		},
+		{
+			`PRETTY_NAME=Source
+PRETTY_NAME=Ubuntu 14.04.LTS`,
+			"Source",
+		},
+	}
```
Comment (duglin) [inline pkg/parsers/operatingsystem/operatingsystem_test.go]: I may have missed it, but if not, can you add a test where the PRETTY_NAME is valid but doesn't use quotes?
And it might be good to add a test using single quotes.

Comment (vdemeester) [inline pkg/parsers/operatingsystem/operatingsystem_test.go]: It's right up [there](https://github.com/docker/docker/pull/16692/files#diff-e00fe97ae19575cdb783df81debca038R98) for the one without quotes, but I though I added simple quotes tests.. but guess not, I'll add some :wink:.

Comment (vdemeester) [inline pkg/parsers/operatingsystem/operatingsystem_test.go]: oh but this test looks a little bit weird too (2 `PRETTY_NAME`)

Comment (duglin) [inline pkg/parsers/operatingsystem/operatingsystem_test.go]: yea, I got confused by the double PRETTY_NAME  :-)

Comment (vdemeester) [inline pkg/parsers/operatingsystem/operatingsystem_test.go]: Me too, gonna change this one :sweat_smile:

Comment (vdemeester) [inline pkg/parsers/operatingsystem/operatingsystem_test.go]: Ah, single quotes are there : https://github.com/docker/docker/pull/16692/files#diff-e00fe97ae19575cdb783df81debca038R94 :smile_cat:.

**Comment by duglin** [comment]
And a squash....  :-)

**Comment by vdemeester** [comment]
@duglin sqaushing the dep vendoring ? :stuck_out_tongue:

**Comment by duglin** [comment]
oh, that's up to you I guess. I just tend to prefer one commit, unless there are overlapping changes that should be viewed independently, which isn't the case here.  No biggie.

**Comment by thaJeztah** [comment]
@duglin we try to keep vendoring updates separate to keep clear what was created externally, and what was "created here" (although there was some discussion about that)

File: pkg/parsers/operatingsystem/operatingsystem_linux.go [hunk 6]
```diff
@@ -18,15 +23,27 @@ var (
...
+	defer osReleaseFile.Close()
+
+	scanner := bufio.NewScanner(osReleaseFile)
+	for scanner.Scan() {
+		line := scanner.Text()
+		if strings.HasPrefix(line, "PRETTY_NAME=") {
+			data := strings.SplitN(line, "=", 2)
+			prettyNames, err := shellwords.Parse(data[1])
+			if err != nil || len(prettyNames) != 1 {
+				return "", fmt.Errorf("PRETTY_NAME is invalid")
```
Comment (duglin) [inline pkg/parsers/operatingsystem/operatingsystem_linux.go]: If we have a value for 'err' I'd prefer if we returned that to the user so they know what we don't like their string.
Likewise, if len != 1 then we should say that they can't have more than one value, or they need to use quotes if they have spaces.
Minor things, but I'd prefer to be as helpful as possible since the current error message doesn't give a clue as to why we think its invalid.

**Comment by duglin** [comment]
I was looking at: http://www.dsm.fordham.edu/cgi-bin/man-cgi.pl?topic=os-release&ampsect=5
and noticed this:  `It is possible to source the configuration from shell scripts...`
This would seem to imply a "last one wins" model, where this code assumes a "first one wins" because it uses the first `PRETTY_NAME` it finds, not the last.
Any else more familiar with this file who can confirm or deny this?

**Comment by phemmer** [comment]
Well, I would concur, by that statement you quoted, last should win.

**Comment by vdemeester** [comment]
Hum.. right, make sense, I can update my code to handle that case then :)

File: pkg/parsers/operatingsystem/operatingsystem_linux.go (hunk 6 above)
Comment (vdemeester) [inline pkg/parsers/operatingsystem/operatingsystem_linux.go]: Sounds good to me :wink:

**Comment by vdemeester** [comment]
@duglin @phemmer if there is two `PRETTY_NAME` and the first one is KO, should it fail or returns the only one valid ? (kinda have an answer to that, but I want your opinion)

```
PRETTY_NAME=Invalid Pretty Name
PRETTY_NAME="Valid Pretty Name"
```

**Comment by duglin** [comment]
@vdemeester I'd say it should fail

**Comment by phemmer** [comment]
I think either would be acceptable. Though if the last one is valid, it might be nice to use it.
But this is probably a huge edge case that will never be seen :-)

**Comment by vdemeester** [comment]
@duglin @phemmer Updated and rebased, it errors out right now, and keep the last one if no failure.

**Comment by duglin** [comment]
LGTM thanks!

**Comment by phemmer** [comment]
LGTM, if that means anything from a non-collaborator :-)

**Comment by vdemeester** [comment]
@phemmer you're doing a lot around here :+1:, so at least it means something to me :stuck_out_tongue_closed_eyes:.

File: hack/vendor.sh [hunk 7]
```diff
@@ -13,6 +13,7 @@ clone git github.com/go-check/check 11d3bc7aa68e238947792f30573146a3231fc0f1
 clone git github.com/gorilla/context 14f550f51a
 clone git github.com/gorilla/mux e444e69cbd
 clone git github.com/kr/pty 5cf931ef8f
+clone git github.com/mattn/go-shellwords f4e566c536cf69158e808ec28ef4182a37fdc981
```
Comment (thaJeztah) [inline hack/vendor.sh]: just a nit ®, perhaps we should ask @mattn if he can tag a release?

**Comment by thaJeztah** [comment]
> you're doing a lot around here :+1:, so at least it means something to me :stuck_out_tongue_closed_eyes:.

Double that, thanks @phemmer!

File: hack/vendor.sh (hunk 7 above)
Comment (vdemeester) [inline hack/vendor.sh]: true :+1: @mattn wdyt ?

**Comment by thaJeztah** [comment]
I'm for merging, unless @mattn is willing to create a tag https://github.com/docker/docker/pull/16692#discussion_r44026474 (but we can do that in a follow-up)

ping @LK4D4 up to you!

File: hack/vendor.sh (hunk 7 above)
Comment (mattn) [inline hack/vendor.sh]: tagged `v1.0.0` just now.

Comment (thaJeztah) [inline hack/vendor.sh]: That's really awesome @mattn! Thanks so much!

**Comment by vdemeester** [comment]
Will update vendor with the tags then :wink:

File: hack/vendor.sh (hunk 7 above)
Comment (vdemeester) [inline hack/vendor.sh]: @mattn :+1: Thanks a lot ! :wink:

**Comment by calavera** [comment]
Thanks for keeping an eye on this @phemmer, your LGTMs are very well considered among maintainers.

LGTM
