### PR TITLE
devmapper: Make sure device is a thin pool device

### LINKED ISSUE #16092: dm.thinpooldev lacks error handling
I created an LVM2 thin-pool.  I then created a logical volume inside that pool, just to play with it.

I deleted my logical volume and then tried to use `docker daemon` with it and it would crash:

```
◀︎root@elastic01 ~▶︎ rm -rf /var/lib/docker ; /usr/bin/docker daemon --debug --storage-driver 'devicemapper' --storage-opt 'dm.thinpooldev=/dev/mapper/docker-pool0' --storage-opt 'dm.fs=xfs' --storage-opt 'dm.use_deferred_removal=true'
DEBU[0000] Registering PUT, /containers/{name:.*}/archive
DEBU[0000] Registering DELETE, /images/{name:.*}
DEBU[0000] Registering DELETE, /containers/{name:.*}
DEBU[0000] Registering OPTIONS,
DEBU[0000] Registering HEAD, /containers/{name:.*}/archive
DEBU[0000] Registering GET, /info
DEBU[0000] Registering GET, /images/{name:.*}/get
DEBU[0000] Registering GET, /images/{name:.*}/history
DEBU[0000] Registering GET, /containers/{name:.*}/changes
DEBU[0000] Registering GET, /containers/{name:.*}/json
DEBU[0000] Registering GET, /containers/{name:.*}/stats
DEBU[0000] Registering GET, /_ping
DEBU[0000] Registering GET, /images/search
DEBU[0000] Registering GET, /containers/{name:.*}/top
DEBU[0000] Registering GET, /exec/{id:.*}/json
DEBU[0000] Registering GET, /version
DEBU[0000] Registering GET, /images/json
DEBU[0000] Registering GET, /containers/ps
DEBU[0000] Registering GET, /containers/{name:.*}/export
DEBU[0000] Registering GET, /containers/{name:.*}/logs
DEBU[0000] Registering GET, /containers/{name:.*}/archive
DEBU[0000] Registering GET, /events
DEBU[0000] Registering GET, /images/{name:.*}/json
DEBU[0000] Registering GET, /containers/json
DEBU[0000] Registering GET, /containers/{name:.*}/attach/ws
DEBU[0000] Registering GET, /images/get
DEBU[0000] Registering POST, /containers/create
DEBU[0000] Registering POST, /containers/{name:.*}/stop
DEBU[0000] Registering POST, /containers/{name:.*}/wait
DEBU[0000] Registering POST, /containers/{name:.*}/rename
DEBU[0000] Registering POST, /images/create
DEBU[0000] Registering POST, /images/{name:.*}/push
DEBU[0000] Registering POST, /images/{name:.*}/tag
DEBU[0000] Registering POST, /containers/{name:.*}/attach
DEBU[0000] Registering POST, /auth
DEBU[0000] Registering POST, /containers/{name:.*}/kill
DEBU[0000] Registering POST, /containers/{name:.*}/pause
DEBU[0000] Registering POST, /containers/{name:.*}/unpause
DEBU[0000] Registering POST, /containers/{name:.*}/restart
DEBU[0000] Registering POST, /containers/{name:.*}/start
DEBU[0000] Registering POST, /exec/{name:.*}/start
DEBU[0000] Registering POST, /images/load
DEBU[0000] Registering POST, /build
DEBU[0000] Registering POST, /containers/{name:.*}/resize
DEBU[0000] Registering POST, /containers/{name:.*}/copy
DEBU[0000] Registering POST, /containers/{name:.*}/exec
DEBU[0000] Registering POST, /exec/{name:.*}/resize
DEBU[0000] Registering POST, /commit
DEBU[0000] [graphdriver] trying provided driver "devicemapper"
DEBU[0000] devicemapper: driver version is 4.29.0
DEBU[0000] devmapper: Deferred removal support enabled.
DEBU[0000] Generated prefix: docker-253:0-375713300
DEBU[0000] Checking for existence of the pool 'docker-pool0'
FATA[0000] Error starting daemon: error initializing graphdriver: EOF
```

After much digging around, I found the problem in the commit message for 2b10749c:

> Docker will not take ownership of the specified thin-pool device unless it has 0 data blocks used and a transaction id of 0.  This should help guard against using a thin-pool that is already in use.

I rebuilt my LVM2 thin pool and now it works.

I would expect that instead of `error initializing graphdriver: EOF` it would display a message about the LVM2 thin pool have been used already or that it was invalid or *something* I could use to figure out the problem.

I also (stupidly, I admit) didn't understand the documentation and instead of doing a `man lvmthin` and working things out from there, I tried using `/dev/sdb2` as the thinpool.

I would suggest a good error message for that would be handy. :-)

### PR DESCRIPTION
**Pull request by rhvgoyal**
Fixes #16092 

Right now we check for the existence of device but don't make sure it is
a thin pool device. We assume it is a thin pool device and call poolStatus()
on the device which returns an error EOF. And that error does not tell
anything.

So before we reach the stage of calling poolStatus() make sure we are working
with a thin pool device otherwise error out.

Signed-off-by: Vivek Goyal vgoyal@redhat.com

### CODE REVIEW

File: daemon/graphdriver/devmapper/deviceset.go [hunk 1]
```diff
@@ -897,6 +897,33 @@ func (devices *DeviceSet) createBaseImage() error {
...
+	}
+
+	// Device does not exist.
+	if info.Exists == 0 {
+		return false, nil
+	}
+
+	_, _, deviceType, _, err := devicemapper.GetStatus(thinPoolDevice)
+	if err != nil {
+		return true, fmt.Errorf("devmapper: GetStatus() on device %s failed: %v", thinPoolDevice, err)
```
Comment (LK4D4) [inline daemon/graphdriver/devmapper/deviceset.go]: this signature slightly bother me, let's return false(default bool value) on errors, that value shouldn't be used in case of error anyway.

Comment (rhvgoyal) [inline daemon/graphdriver/devmapper/deviceset.go]: Ok, will change it.

**Comment by rhvgoyal** [comment]
@LK4D4 Did the change. PTAL.

**Comment by LK4D4** [comment]
LGTM

**Comment by rhvgoyal** [comment]
@vbatts Please have a look.

**Comment by vbatts** [comment]
LGTM
