### PR TITLE
macvlan, ipvlan-l2: only configure a default route when a gateway address is supplied

### LINKED ISSUE #50898: macvlan: "failed to set IPv6 gateway: file exists" on network connect
### Description

_Reported in community Slack, but the user doesn't wish to share details here._

Broadly - with a container attached to one macvlan network, connect it to a second network, disconnect the first network, then re-connect. Some/most of the time, the final re-connect fails with:
```
Error response from daemon: updating gateway endpoint: failed to set IPv6 gateway: file exists
```

### Reproduce

I'm able to reliably repro the error in a macvlan network connected to a network with a router, using:
```
docker network create -d macvlan --ipv4=false --ipv6 --subnet fdf0:a9dd:e362:b301::/64 -o parent=enp0s1 mv1
docker network create -d macvlan --ipv4=false --ipv6 --subnet fdf0:a9dd:e362:b364::/64 -o parent=enp0s1 mv2
docker run --rm -d --network mv1 --ip6 fdf0:a9dd:e362:b301::1234 --name c1 busybox sleep infinity
docker network connect mv2 c1 --ip6 fdf0:a9dd:e362:b364::1234
sleep 2
docker network disconnect mv1 c1
sleep 2
docker network connect mv1 c1 --ip6 fdf0:a9dd:e362:b301::1234
```

But, can't repro in a dev container - I think Docker's gateway assignment is racing IPv6 autoconfig.

### Expected behavior

_No response_

### docker version

```bash
28.3.3 or current-latest master, on a Debian Trixie VM with a bridged network.
```

### docker info

```bash
.
```

### Additional Info

_No response_

### LINKED ISSUE #50985: First address of non-internal MACVLAN network not allocatable
### Description

The first address of a MACVLAN network is not allocatable to containers, unless the network was created with `--internal`. This doesn't make sense, as external connectivity is provided by the parent interface, and so reserving the first address for some sort of "gateway" is wrong.

I suspect the same problem occues with IPVLAN, though I have yet to test it.

### Reproduce

```shell
docker network create -d macvlan -o parent=eth0 --subnet=172.18.0.0/24 test
docker run --rm -it --net=test --ip=172.18.0.1 alpine
```

In particular, in `docker network inspect test`, there's no `Gateway`.

### Expected behavior

An Alpine Linux container launches with IP address `172.18.0.1`.

Instead Docker says:

```text
docker: Error response from daemon: Address already in use.
```

and the container was not created.

### docker version

```bash
Three Docker Engine instances tested:

<details>
<summary>1. Debian-provided `docker.io` on Trixie (26.1.5)</summary>

Client:
 Version:           26.1.5+dfsg1
 API version:       1.45
 Go version:        go1.24.4
 Git commit:        a72d7cd
 Built:             Wed Jul 30 19:37:00 2025
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          26.1.5+dfsg1
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.24.4
  Git commit:       411e817
  Built:            Wed Jul 30 19:37:00 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.24~ds1
  GitCommit:        1.7.24~ds1-6+b4
 runc:
  Version:          1.1.15+ds1
  GitCommit:        1.1.15+ds1-2+b4
 docker-init:
  Version:          0.19.0
  GitCommit:

</details>

<details>
<summary>2. Ubuntu-provided `docker.io` on Noble (27.5.1)</summary>

Client:
 Version:           27.5.1
 API version:       1.47
 Go version:        go1.22.2
 Git commit:        27.5.1-0ubuntu3~24.04.2
 Built:             Mon Jun  2 11:51:53 2025
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          27.5.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.2
  Git commit:       27.5.1-0ubuntu3~24.04.2
  Built:            Mon Jun  2 11:51:53 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.27
  GitCommit:
 runc:
  Version:          1.2.5-0ubuntu1~24.04.1
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:

</details>

<details>
<summary>3. Docker-provided `docker-ce` on Trixie (28.3.3)</summary>

Client: Docker Engine - Community
 Version:           28.3.3
 API version:       1.51
 Go version:        go1.24.5
 Git commit:        980b856
 Built:             Fri Jul 25 11:34:13 2025
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          28.3.3
  API version:      1.51 (minimum version 1.24)
  Go version:       go1.24.5
  Git commit:       bea959c
  Built:            Fri Jul 25 11:34:13 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.27
  GitCommit:        05044ec0a9a75232cad458027ca83437aae3f4da
 runc:
  Version:          1.2.5
  GitCommit:        v1.2.5-0-g59923ef
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

</details>
```

### docker info

```bash
Three Docker Engine instances tested:

<details>
<summary>1. Debian-provided `docker.io` on Trixie (26.1.5)</summary>

Client:
 Version:    26.1.5+dfsg1
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 26.1.5+dfsg1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1.7.24~ds1-6+b4
 runc version: 1.1.15+ds1-2+b4
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.12.41+deb13-cloud-amd64
 Operating System: Debian GNU/Linux 13 (trixie)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.36GiB
 Name: localhost
 ID: be2238d2-6081-4408-9aed-fb7e556153ac
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true

</details>

<details>
<summary>2. Ubuntu-provided `docker.io` on Noble (27.5.1)</summary>

Client:
 Version:    27.5.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  0.20.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  2.33.0+ds1-0ubuntu1~24.04.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 11
  Running: 10
  Paused: 0
  Stopped: 1
 Images: 48
 Server Version: 27.5.1
 Storage Driver: overlay2
  Backing Filesystem: zfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-78-generic
 Operating System: Ubuntu 24.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 125.7GiB
 Name: localhost
 ID: 1041d153-ba77-488f-8341-9df7242429ba
 Docker Root Dir: /srv/docker
 Debug Mode: false
 Username: localhost
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://registry-1.docker.io/
 Live Restore Enabled: true
 Default Address Pools:
   Base: 172.17.2.0/23, Size: 28
   Base: fd00::10:0:0:0/76, Size: 80

</details>

<details>
<summary>3. Docker-provided `docker-ce` on Trixie (28.3.3)</summary>

Client: Docker Engine - Community
 Version:    28.3.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.26.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.39.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 8
 Server Version: 28.3.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 CDI spec directories:
  /etc/cdi
  /var/run/cdi
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05044ec0a9a75232cad458027ca83437aae3f4da
 runc version: v1.2.5-0-g59923ef
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.12.41+deb13-cloud-amd64
 Operating System: Debian GNU/Linux 13 (trixie)
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 62.64GiB
 Name: localhost
 ID: 35c95837-943f-4f19-bfe6-9b16a5b94b15
 Docker Root Dir: /data00/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: true

</details>
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by robmry**
**- What I did**

- fix https://github.com/moby/moby/issues/50898
- fix https://github.com/moby/moby/issues/50985

When no `--gateway` is supplied for a macvlan or "l2" ipvlan, an address is allocated from IPAM and configured as the default route.

When IPv6 autoconfiguration is enabled on the parent interface's network, it may also set up a default route. If the kernel wins the race, container creation fails with an error because a default route already exists when Docker tries to set it up.

So, don't try to guess the gateway address by picking one from IPAM (it's not like the bridge driver, where the gateway address is assigned to the bridge - all the drivers do with the address is configure the default route).

Also, when no gateway is configured, don't let the libnet code assume the `docker_gwbridge` is needed.

This will be a breaking change if there are users who haven't been configuring a gateway address, where the gateway is using the first host address in the Docker network's ip-range (the address that'll have been picked for IPAM). Those users will now need to explicitly configure the gateway.

**- How I did it**

**- How to verify it**

Updated integration tests.

The commands noted in the linked issue no longer fail.

**- Human readable description for the release notes**
```markdown changelog
- macvlan and ipvlan-l2 networks: no default gateway will be configured unless a `--gateway` is explicitly included in IPAM configuration. This addresses an issue which could cause container startup to fail in networks with IPv6 auto-configuration enabled.
```

### CODE REVIEW

File: daemon/libnetwork/drivers/macvlan/macvlan_joinleave.go [hunk 1]
```diff
@@ -56,37 +56,49 @@ func (d *driver) Join(ctx context.Context, nid, eid string, sboxKey string, jinf
...
-			}
-			err = jinfo.SetGateway(v4gw)
-			if err != nil {
-				return err
+			if s.GwIP == "" {
+				// Can't set up a default gateway, but the network is not internal, so it should
+				// be treated as having external connectivity. (This preserves old behavior,
+				// where a gateway address was assigned from IPAM that did not necessarily
+				// correspond with a working gateway.)
+				jinfo.ForceGw4()
```
Comment (akerouanton) [inline daemon/libnetwork/drivers/macvlan/macvlan_joinleave.go:64]: If we find out that this doesn't work that well for some use cases, we could also consider using [netlink.LinkSubscribeAt](https://pkg.go.dev/github.com/vishvananda/netlink#RouteSubscribeAt) to watch changes made to the container's routing table and update libnet state accordingly.

File: integration/network/macvlan/macvlan_test.go [hunk 2]
```diff
@@ -433,7 +426,8 @@ func testMacvlanAddressing(t *testing.T, ctx context.Context, client client.APIC
 	// Validate macvlan bridge mode defaults gateway sets the default IPAM next-hop inferred from the subnet
```
Comment (akerouanton) [inline integration/network/macvlan/macvlan_test.go]: I think this comment should be updated.

**Review by akerouanton — APPROVED** [review]
LGTM

File: integration/network/macvlan/macvlan_test.go (hunk 2 above)
Comment (robmry) [reply integration/network/macvlan/macvlan_test.go]: Fixed - along with one in ipvlan_test.go.

File: daemon/libnetwork/drivers/macvlan/macvlan_joinleave.go (hunk 1 above)
Comment (robmry) [reply daemon/libnetwork/drivers/macvlan/macvlan_joinleave.go:64]: Yes, it could get quite fiddly because it takes some time for the autoconfig to work, so it'd be difficult to do during the join because we wouldn't know how long to wait. We'd end up reconfiguring gateways asynchronously, so debug might get trickier ("something worked for a couple of seconds, then broke").

If a container with a macvlan/ipvlan-l2 interface has gained a default route via autoconfig, moby doesn't know about it. So, if another network is connected and becomes the gateway, that connection fails because a second default route can't be set up. With https://github.com/moby/moby/pull/50945, it's at-least cleaned up properly - so the connection can be tried again with a lower gateway priority, so that the macvlan/ipvlan endpoint keeps the gateway. Or, sysctls can be used to prevent the autoconfig. But those remedies aren't obvious. And, actually handing over gateway-ness between an autoconfgured endpoint (if someone has a reason to want that) isn't easily do-able.

So there is more we could do here if folks hit issues.

**Review by thaJeztah — APPROVED** [review]
LGTM, but letting Cory have a peek

**Review by corhere — APPROVED** [review]
