### PR TITLE
stack deploy: handle external network when deploying

### LINKED ISSUE #28835: Docker deploy compose external network does not work
**Description**

Using external network with docker stack deploy does not work.

**Steps to reproduce the issue:**
1. Create external network
```
docker network create -d overlay external-network
```
2. Create docker-compose.yml
```
version: '3'

services:
    web:
        image: nginx
        networks:
            - external-network
networks:
    external-network:
        external: true
```
3.
```
docker stack deploy --compose-file=docker-compose.yml oops
```

**Describe the results you received:**
```
Creating network oops_default
Creating service oops_web
Error response from daemon: network oops_external-network not found
```

**Describe the results you expected:**
Expected created stack with web service hooked to external-network.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc2
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   1f9b3ef
 Built:        Wed Nov 23 06:32:39 2016
 OS/Arch:      linux/amd64

Server:
 Version:             1.13.0-rc2
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          1f9b3ef
 Built:               Wed Nov 23 06:32:39 2016
 OS/Arch:             linux/amd64
 Experimental:        false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.13.0-rc2
Storage Driver: btrfs
 Build Version: Btrfs v4.4
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: jk6fwe5660zrvcuq1llde7gec
 Is Manager: true
 ClusterID: jcl1oio3gvyzjn1upm11s5gqo
 Managers: 2
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.223.118.166
 Manager Addresses:
  10.223.118.166:2377
  10.223.118.239:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-47-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.4 MiB
Name: manager1
ID: ICOL:PRKO:DNCW:SFRG:KS7Y:YF6F:MYBT:7MKY:CK2A:2EVB:VMTW:HXJR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Labels:
 provider=generic
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ran on LXD with Ubuntu 16.04. LXD container is privileged.

### PR DESCRIPTION
**Pull request by vdemeester**
Fixes #28835. There is two commits :

- If the network is marked as external, don't use the namespace on it. Otherwise, it's not found.
- It also validate that the existing networks are available `before` scheduling any services. This is more consistent with the way `docker-compose` does it and helps making sure we don't schedule an incomplete stack.

```
$ docker stack deploy --compose-file docker-compose.yml foo
Ignoring unsupported options: build

Ignoring deprecated options:

container_name: Setting the container name is not supported.

network "outside" is declared as external, but could not be found. You need to create the network before the stack is deployed (with overlay driver)

```

/cc @dnephin @aanand @thaJeztah @mavenugo 

:frog: 

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by aanand** [comment]
LGTM (IANAM)

File: cli/command/stack/deploy.go [hunk 1]
```diff
@@ -179,18 +183,20 @@ func getConfigFile(filename string) (*composetypes.ConfigFile, error) {
...
 
 	// TODO: only add default network if it's used
 	networks["default"] = composetypes.NetworkConfig{}
 
+	externalNetworks := []string{}
 	result := make(map[string]types.NetworkCreate)
 
 	for internalName, network := range networks {
 		if network.External.Name != "" {
+			externalNetworks = append(externalNetworks, network.External.Name)
```
Comment (dnephin) [inline cli/command/stack/deploy.go]: I didn't notice this before but this check `network.Externalk.Name != ""` is wrong. I think it should be `if network.External.External`.

**Review by dnephin — COMMENTED** [review]
one minor thing, otherwise LGTM

File: cli/command/stack/deploy.go (hunk 1 above)
Comment (vdemeester) [inline cli/command/stack/deploy.go]: @dnephin ok, it bothered me a little, I'll update :angel:

**Review by dnephin — APPROVED** [review]
LGTM

**Comment by vieux** [comment]
LGTM
