### PR TITLE
Set OOMKilled state on any OOM event

### LINKED ISSUE #18470: OOM of exec stops OOM detection for the PID1 container process and following execs
To reproduce:
```
rm -rf /tmp/oomeventstest && \
mkdir /tmp/oomeventstest && \
cd /tmp/oomeventstest && \
wget https://gist.githubusercontent.com/garagatyi/f3643cc448e1a7550853/raw/eb84488cf8efccf0fe1df5b47a54d28c30121183/Dockerfile && \
docker build .
```
Then in other terminal:
```
curl -s http://localhost:2375/events
```

When we get OOM of PID1 process only docker generates correct events.
```
docker run -m 64M -e "SLEEP_DELAY=10s" {imageID}
WARNING: Your kernel does not support swap limit capabilities, memory limited without swap.
sleep 10s
begin allocating memory...
```
```
{"status":"create","id":"36eb96d6c134895854e77f65ac47955b6ee08eb62bceee37cc605157f1c9482b","from":"9e0d5e071a2b","time":1449497856,"timeNano":1449497856620037149}
{"status":"attach","id":"36eb96d6c134895854e77f65ac47955b6ee08eb62bceee37cc605157f1c9482b","from":"9e0d5e071a2b","time":1449497856,"timeNano":1449497856670112786}
{"status":"start","id":"36eb96d6c134895854e77f65ac47955b6ee08eb62bceee37cc605157f1c9482b","from":"9e0d5e071a2b","time":1449497856,"timeNano":1449497856984903035}
{"status":"oom","id":"36eb96d6c134895854e77f65ac47955b6ee08eb62bceee37cc605157f1c9482b","from":"9e0d5e071a2b","time":1449497871,"timeNano":1449497871593721048}
{"status":"die","id":"36eb96d6c134895854e77f65ac47955b6ee08eb62bceee37cc605157f1c9482b","from":"9e0d5e071a2b","time":1449497871,"timeNano":1449497871701251889}
```
When we get OOM of exec and then get OOM of PID1 process docker doesn't send event about PID1 process OOM
```
docker run -m 64M -e "SLEEP_DELAY=3m" 9e0d5e071a2b                                                                                                                                         
WARNING: Your kernel does not support swap limit capabilities, memory limited without swap.
sleep 3m
```
```
docker exec -it ca1f50deaca6 bash
root@ca1f50deaca6:/# export SLEEP_DELAY=1s
root@ca1f50deaca6:/# /script.sh
sleep 1s
begin allocating memory...
Killed
```
```
{"status":"create","id":"ca1f50deaca6857da867e1abe47d0c338f2c9a478716245215e99804ebe38116","from":"9e0d5e071a2b","time":1449497892,"timeNano":1449497892815550422}
{"status":"attach","id":"ca1f50deaca6857da867e1abe47d0c338f2c9a478716245215e99804ebe38116","from":"9e0d5e071a2b","time":1449497892,"timeNano":1449497892857804285}
{"status":"start","id":"ca1f50deaca6857da867e1abe47d0c338f2c9a478716245215e99804ebe38116","from":"9e0d5e071a2b","time":1449497893,"timeNano":1449497893160319023}
{"status":"exec_create: bash ","id":"ca1f50deaca6857da867e1abe47d0c338f2c9a478716245215e99804ebe38116","from":"9e0d5e071a2b","time":1449497912,"timeNano":1449497912019407009}
{"status":"exec_start: bash ","id":"ca1f50deaca6857da867e1abe47d0c338f2c9a478716245215e99804ebe38116","from":"9e0d5e071a2b","time":1449497912,"timeNano":1449497912020034187}
{"status":"oom","id":"ca1f50deaca6857da867e1abe47d0c338f2c9a478716245215e99804ebe38116","from":"9e0d5e071a2b","time":1449497946,"timeNano":1449497946969112286}
{"status":"die","id":"ca1f50deaca6857da867e1abe47d0c338f2c9a478716245215e99804ebe38116","from":"9e0d5e071a2b","time":1449498204,"timeNano":1449498204305209257}
```
Delay between OOM and DIE events more than 4 minutes. It's because OOM event was generated for exec OOM only.

### LINKED ISSUE #18510: Docker 1.9: OOMKilled not reliably set
As of Docker 1.9, the `State.OOMKilled` flag is not set very reliably (see repro script below).

I've got a PR coming shortly to address this issue hopefully.

`docker version`: 
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:
 ```
Containers: 21
Images: 2
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 44
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-63-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 2
Total Memory: 3.676 GiB
Name: ip-172-31-3-236
ID: UTDE:EJZD:RU5B:JC7G:7WCS:RBUO:Q2YM:S3ON:W5GK:BJQH:RJZJ:BAQQ
Debug mode (server): true
 File Descriptors: 20
 Goroutines: 21
 System Time: 2015-12-08T21:09:14.614798421Z
 EventsListeners: 0
 Init SHA1: 4fc7c03a06c675f115b39958c13486d53df10a14
 Init Path: /usr/lib/docker/dockerinit
 Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
```

`uname -a`: `Linux ip-172-31-3-233 3.13.0-63-generic #103-Ubuntu SMP Fri Aug 14 21:42:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

Environment details (AWS, VirtualBox, physical, etc.): AWS, but should affect all environments.

How reproducible: Very

Steps to Reproduce:
The following bash script is an easy way to reproduce this:
```bash
#!/bin/bash
echo -e "Init process OOMs"
docker run -d --name oom -m 10M busybox sh -c 'x="a"; while true; do x=$x$x$x; done' > /dev/null
sleep 1
docker inspect -f '{{ .State.ExitCode }} - {{ .State.OOMKilled }}' oom
docker rm oom >/dev/null

echo -e "\nChild process OOMs"
docker run -d --name oom -m 10M busybox sh -c "sh -c \"x='a'; while true; do x=\\\$x\\\$x\\\$x; done\"; exit 0" > /dev/null
sleep 1
docker inspect -f '{{ .State.ExitCode }} - {{ .State.OOMKilled }}' oom
docker rm oom >/dev/null

echo -e "\nExec process OOMs; init does too"
docker run -d --name oom -m 10M busybox sh -c 'sleep 3; x="a"; while true; do x=$x$x$x; done' > /dev/null
sleep 1
docker exec oom sh -c 'x="a"; while true; do x=$x$x$x; done'
sleep 3
docker inspect -f '{{ .State.ExitCode }} - {{ .State.OOMKilled }}' oom
docker rm oom >/dev/null

echo -e "\nExec process OOMs; init does not"
docker run -d --name oom -m 10M busybox sh -c 'sleep 3; exit 0' > /dev/null
sleep 1
docker exec oom sh -c 'x="a"; while true; do x=$x$x$x; done'
sleep 3
docker inspect -f '{{ .State.ExitCode }} - {{ .State.OOMKilled }}' oom
docker rm oom >/dev/null
```

Actual Results:
After #16235, the output is:
```
Init process OOMs
137 - false

Child process OOMs
0 - false

Exec process OOMs; init does too
137 - true

Exec process OOMs; init does not
0 - false
```

Expected Results:
It's not totally clear what the expected behavior should be since I don't think the output for older versions was ideal.
Prior to #16235 the output was:
```
Init process OOMs
137 - true

Child process OOMs
0 - true

Exec process OOMs; init does too
137 - true

Exec process OOMs; init does not
0 - true
```

Effectively, any time any oom event happened, you had the OOMKilled flag set.
I think it would make more sense for it to only set the OOMKilled flag if the init process directly OOMs (the 1st and 3rd cases) and not otherwise.

### PR DESCRIPTION
**Pull request by euank**
This restores the behavior that existed prior to #16235 for setting
OOMKilled, while retaining the additional benefits it introduced around
emitting oom events.

This also adds a test for the most obvious OOM cases which would have
caught this regression.

Fixes #18510

This also fixes #18470, via ranging over the channel, though I've only manually tested that.

I also wanted some input on whether it would be better to make the behavior differ from the original behavior by trying to figure out that an OOM event is for the init process / is the event that caused the container to exit, though after reading libcontainer and what the kernel's cgroup notifications give you, it seems like whatever we do there would probably be a heuristic at best.

### CODE REVIEW

File: daemon/execdriver/native/driver.go [hunk 1]
```diff
@@ -198,7 +201,17 @@ func (d *Driver) Run(c *execdriver.Command, pipes *execdriver.Pipes, hooks execd
 	}
 	cont.Destroy()
 	destroyed = true
-	_, oomKill := <-oom
+	// Note: oomKilled will have an oom event if any process within the container
+	// died at any time, not only if the init process OOMed
+	// TODO, perhaps we only want the OOMKilled flag to be set if the OOM
+	// resulted in a container death (pid1 OOMd)
+	// Loop through all oomKilled values so we don't leak a goroutine in
```
Comment (euank) [inline daemon/execdriver/native/driver.go]: Is this actually true? I thought it might be after briefly skimming the codepath here, but I'm not completely sure.

I don't think there can be any harm in looping over all the channel's events anyways, but I wouldn't want to leave a misleading comment if that's not the case.

**Comment by euank** [comment]
Quick ping on this.

Since this addresses a regression (that OOMKilled isn't set) in 1.9, should this be part of the 1.9.2 milestone?

**Comment by thaJeztah** [comment]
Hm good call, I'll add it :)

**Comment by thaJeztah** [comment]
ping @LK4D4 can you have a look at this one?

File: container/monitor.go [hunk 2]
```diff
@@ -304,8 +304,7 @@ func (m *containerMonitor) shouldRestart(exitCode int) bool {
 // received ack from the execution drivers
 func (m *containerMonitor) callback(processConfig *execdriver.ProcessConfig, pid int, chOOM <-chan struct{}) error {
 	go func() {
-		_, ok := <-chOOM
-		if ok {
+		for range chOOM {
```
Comment (cpuguy83) [inline container/monitor.go]: This will loop forever which is also not good.

Comment (euank) [inline container/monitor.go]: The channel from libcontainer's `NotifyOOM` is reliably closed afaict, and in every other case an already closed channel is passed in.

The loop should end as soon as the channel is closed.

In addition, if I run a build of this, while a container is running the SIGUSR1 output indicates one goroutine at `monitor.go:307`, and then after stopping the container (with OOM or otherwise), the SIGUSR1 output shows no goroutines in `monitor.go` at all.

Comment (cpuguy83) [inline container/monitor.go]: Oh you are right, I read this wrong.  Sorry.

**Comment by crosbymichael** [comment]
LGTM

**Comment by anusha-ragunathan** [comment]
LGTM

**Comment by icecrime** [comment]
Thank you all! LGTM

**Comment by thaJeztah** [comment]
Failures on gccgo;

```
20:27:02 ----------------------------------------------------------------------
20:27:02 FAIL: docker_cli_oom_killed_test.go:23: TestInspectOomKilledFalse.pN52_github_com_docker_docker_integration_cli.DockerSuite
20:27:02 
20:27:02 /go/src/github.com/docker/docker/pkg/integration/dockerCmd_utils.go:35:
20:27:02     c.Assert(err, check.IsNil, check.Commentf("%q failed with errors: %s, %v", strings.Join(args, " "), out, err))
20:27:02 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc2082ed5a0)} ("exit status 125")
20:27:02 ... "run --name testoomkilled -m 10MB busybox sh -c echo hello world" failed with errors: WARNING: Your kernel does not support swap limit capabilities, memory limited without swap.
20:27:02 docker: Error response from daemon: Cannot start container 4758080e6bf12230cbb60cb2fef5b642e4eb15033fb3495cbbb20b7409da416c: [9] System error: read parent: connection reset by peer.
20:27:02 , exit status 125
20:27:02 
20:27:03 
20:27:03 ----------------------------------------------------------------------
20:27:03 FAIL: docker_cli_oom_killed_test.go:10: TestInspectOomKilledTrue.pN52_github_com_docker_docker_integration_cli.DockerSuite
20:27:03 
20:27:03 docker_cli_oom_killed_test.go:16:
20:27:03     c.Assert(exitCode, checker.Equals, 137, check.Commentf("OOM exit should be 137"))
20:27:04 ... obtained int = 125
20:27:04 ... expected int = 137
20:27:04 ... OOM exit should be 137
20:27:04 
```

**Comment by anusha-ragunathan** [comment]
TestInspectOomKilledFalse cannot start container, which is unrelated to this change. Strange. Maybe restarting tests can help.

**Comment by euank** [comment]
I noticed those tests have the lowest memory limits of any of the others.
I've seen issues before where the dockerinit takes more memory than the limit and causes a breakage similar to this with suitably small limits, so I increased them a bit to see if that's what's causing this. If that doesn't work, I'll grab the gccgo PR and play around locally to see if I can get a better idea of what's going on.

**Comment by anusha-ragunathan** [comment]
TestRunOOMExitCode has a comment for what you noted. Someone has already figured out that 40M works.

**Comment by euank** [comment]
The failures don't look related now.

**Comment by thaJeztah** [comment]
Janky is failing because llvm.org is down/having issues

**Comment by thaJeztah** [comment]
All green! Merging :dancer:
