### PR TITLE
Mount (accessible) host devices in `--privileged` rootless containers

### LINKED ISSUE #42406: Host devices not available inside --privileged rootless containers
**Description**

When running Docker in *Rootless mode*, giving extended privileges (`--privileged`) to a container doesn't add all the (user-accessible) host's device nodes to the container's spec.

https://docs.docker.com/engine/reference/run
> **When the operator executes docker run --privileged, Docker will enable access to all devices on the host** as well as set some configuration in AppArmor or SELinux to allow the container nearly all the same access to the host as processes running outside containers on the host.

This is how `containerd`/`nerdctl` handle it:
https://github.com/containerd/containerd/blob/master/oci/spec_opts_unix.go#L27-L37

**Steps to reproduce the issue:**
1. Run the Docker daemon as a non-root user (Rootless mode)
2. Start a `--privileged` container
3. List the available devices

**Describe the results you received:**

```
$ ls /dev/usb
hiddev0
$ docker run -it --rm --privileged alpine ls /dev/usb
ls: /dev/usb: No such file or directory
```

**Describe the results you expected:**

```
$ ls /dev/usb
hiddev0
$ docker run -it --rm --privileged alpine ls /dev/usb
hiddev0
```

**Output of `docker version`:**

```
Client:
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:42:10 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:13 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.7.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: none
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  rootless
 Kernel Version: 4.15.0-142-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 Name: $HOSTNAME
 Docker Root Dir: $HOME/.local/share/docker
 Debug Mode: false
 Username: $USER
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: Running in rootless-mode without cgroups. To enable cgroups in rootless-mode, you need to boot the system in cgroup v2 mode.
```

### PR DESCRIPTION
**Pull request by eliaskoromilas**
fixes #42406

**- What I did**

* Enabled host-device discovery in `--privileged` rootless containers.
* ~Use `containerd/oci.HostDevices()` that skips device sub-directories which are not accessible by the user.~
    Merged in https://github.com/moby/moby/pull/43053

**- How I did it**

* Removed the condition that skipped that process in rootless mode.
* `containerd/oci.HostDevices()` ignores permission errors when running in a user namespace.

**- How to verify it**

Integration tests are included.

**- Description for the changelog**

Mount (accessible) host devices in `--privileged` rootless containers

### CODE REVIEW

**Comment by eliaskoromilas** [comment]
rebase

**Comment by AkihiroSuda** [comment]
Can we have integration tests too?

File: daemon/device_unix.go [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+
+// HostDevices returns all devices that can be found under /dev directory.
+// Based on HostDevices from runc (libcontainer/devices/device_unix.go).
+func HostDevices() ([]*devices.Device, error) {
+	return GetDevices("/dev")
+}
+
+// GetDevices recursively traverses a directory specified by path
+// and returns all devices found there.
+// Based on GetDevices from runc (libcontainer/devices/device_unix.go).
```
Comment (AkihiroSuda) [inline daemon/device_unix.go:29]: Better to use a permalink here https://github.com/opencontainers/runc/blob/v1.0.0/libcontainer/devices/device_unix.go

Comment (thaJeztah) [reply daemon/device_unix.go:29]: 👆 Same for `HostDevices` above (permalink)

File: daemon/device_unix_test.go [hunk 2]
```diff
@@ -0,0 +1,146 @@
...
+	"github.com/containerd/containerd/pkg/userns"
+	"github.com/opencontainers/runc/libcontainer/devices"
+)
+
+func cleanupTest() {
+	ioutilReadDir = ioutil.ReadDir
+	usernsRunningInUserNS = userns.RunningInUserNS
+}
+
+// Based on test from runc (libcontainer/devices/device_unix_test.go).
```
Comment (thaJeztah) [inline daemon/device_unix_test.go:21]: For these as well. 

For permalinks, It would be good to provide a permalink to the actual code / lines that these were based on, e.g. https://github.com/opencontainers/runc/blob/v1.0.0/libcontainer/devices/device_unix.go#L76-L120 for the earlier example.

**Comment by eliaskoromilas** [comment]
rebase

**Comment by AkihiroSuda** [comment]
Please squash commits

**Comment by eliaskoromilas** [comment]
Should we skip these tests somehow? It fails for every privileged container test.

https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-42638/12/pipeline/348#step-351-log-796

**Review by AkihiroSuda — APPROVED** [review]

File: daemon/device_unix.go [hunk 3]
```diff
@@ -0,0 +1,81 @@
...
+// and returns all devices found there.
+// Based on GetDevices from runc:
+// https://github.com/opencontainers/runc/blob/v1.0.0/libcontainer/devices/device_unix.go#L76-L120
+func GetDevices(path string) ([]*devices.Device, error) {
+	files, err := ioutilReadDir(path)
+	if err != nil {
+		if errors.Is(err, os.ErrPermission) && usernsRunningInUserNS() {
+			// ignore the "permission denied" error if running in userns
+			return nil, nil
+		}
```
Comment (thaJeztah) [inline daemon/device_unix.go:39]: So, I'm not "super" happy with us having to maintain a copy of this function. With my other suggestions applied, I went looking what the difference was between the upstream version in runc, and it looks like this is the only difference (compared to https://github.com/opencontainers/runc/blob/55162941720ba91b87c7d05f9e6a91b9f308f33d/libcontainer/devices/device_unix.go#L76-L120);

[rootless_version.txt](https://github.com/moby/moby/files/7632861/rootless_version.txt)
[runc_version.txt](https://github.com/moby/moby/files/7632862/runc_version.txt)


```patch
diff --git a/runc_version.txt b/rootless_version.txt
index 21ead00a57..7dcd6df5c8 100644
--- a/runc_version.txt
+++ b/rootless_version.txt
@@ -1,9 +1,13 @@
-func GetDevices(path string) ([]*Device, error) {
+func GetDevices(path string) ([]*devices.Device, error) {
 	files, err := osReadDir(path)
 	if err != nil {
+		if errors.Is(err, os.ErrPermission) && usernsRunningInUserNS() {
+			// ignore the "permission denied" error if running in userns
+			return nil, nil
+		}
 		return nil, err
 	}
-	var out []*Device
+	var out []*devices.Device
 	for _, f := range files {
 		switch {
 		case f.IsDir():
@@ -24,9 +28,9 @@ func GetDevices(path string) ([]*Device, error) {
 		case f.Name() == "console":
 			continue
 		}
-		device, err := DeviceFromPath(filepath.Join(path, f.Name()), "rwm")
+		device, err := devices.DeviceFromPath(filepath.Join(path, f.Name()), "rwm")
 		if err != nil {
-			if errors.Is(err, ErrNotADevice) {
+			if errors.Is(err, devices.ErrNotADevice) {
 				continue
 			}
 			if os.IsNotExist(err) {
@@ -34,7 +38,7 @@ func GetDevices(path string) ([]*Device, error) {
 			}
 			return nil, err
 		}
-		if device.Type == FifoDevice {
+		if device.Type == devices.FifoDevice {
 			continue
 		}
 		out = append(out, device)
```

To make things worse, containerd _also_ keeps a copy of this exact function (with some slight changes). I'm concerned that these implementations will start to diverge more, and we'll be trying to catch up with any change made (the `ioutil` -> `os` switch already being a (although not "important") example.


So, I'm wondering if this is a change that would be acceptable for upstream. Given that the runc maintainers prefer to keep `libcontainer` "internal" (reduce the number of external uses), perhaps we should use the containerd implementation instead. If we use the containerd variant, we also wouldn't have to convert the type to `oci.Device`;

https://github.com/moby/moby/blob/30413e5efb6c29da0df23dc95ae4625f31dd8d71/daemon/oci_linux.go#L882


Comparing the runc implementation with the  containerd implementation; [containerd_version.txt](https://github.com/moby/moby/files/7632956/containerd_version.txt) (expand the "details" section below)

<details>

```patch
diff --git a/runc_version.txt b/containerd_version.txt
index 21ead00a57..d195224696 100644
--- a/runc_version.txt
+++ b/containerd_version.txt
@@ -1,9 +1,25 @@
-func GetDevices(path string) ([]*Device, error) {
-	files, err := osReadDir(path)
+func getDevices(path, containerPath string) ([]specs.LinuxDevice, error) {
+	stat, err := os.Stat(path)
+	if err != nil {
+		return nil, errors.Wrap(err, "error stating device path")
+	}
+
+	if !stat.IsDir() {
+		dev, err := deviceFromPath(path)
+		if err != nil {
+			return nil, err
+		}
+		if containerPath != "" {
+			dev.Path = containerPath
+		}
+		return []specs.LinuxDevice{*dev}, nil
+	}
+
+	files, err := ioutil.ReadDir(path)
 	if err != nil {
 		return nil, err
 	}
-	var out []*Device
+	var out []specs.LinuxDevice
 	for _, f := range files {
 		switch {
 		case f.IsDir():
@@ -13,7 +29,11 @@ func GetDevices(path string) ([]*Device, error) {
 			case "pts", "shm", "fd", "mqueue", ".lxc", ".lxd-mounts", ".udev":
 				continue
 			default:
-				sub, err := GetDevices(filepath.Join(path, f.Name()))
+				var cp string
+				if containerPath != "" {
+					cp = filepath.Join(containerPath, filepath.Base(f.Name()))
+				}
+				sub, err := getDevices(filepath.Join(path, f.Name()), cp)
 				if err != nil {
 					return nil, err
 				}
@@ -24,9 +44,9 @@ func GetDevices(path string) ([]*Device, error) {
 		case f.Name() == "console":
 			continue
 		}
-		device, err := DeviceFromPath(filepath.Join(path, f.Name()), "rwm")
+		device, err := deviceFromPath(filepath.Join(path, f.Name()))
 		if err != nil {
-			if errors.Is(err, ErrNotADevice) {
+			if err == errNotADevice {
 				continue
 			}
 			if os.IsNotExist(err) {
@@ -34,10 +54,10 @@ func GetDevices(path string) ([]*Device, error) {
 			}
 			return nil, err
 		}
-		if device.Type == FifoDevice {
-			continue
+		if containerPath != "" {
+			device.Path = filepath.Join(containerPath, filepath.Base(f.Name()))
 		}
-		out = append(out, device)
+		out = append(out, *device)
 	}
 	return out, nil
 }
```

</details>

We can ignore the `containerPath` argument (it's not used for `HostDevices()`, and we have our own logic for this)

The containerd version looks to be missing the part that skips FIFO devices;

```go
if device.Type == FifoDevice {
	continue
}
```

Which was added in https://github.com/opencontainers/runc//commit/95a59bf206f86bc449c4ccc22e2c08e78c707eb6 (https://github.com/opencontainers/runc/pull/2529), so I'm wondering if that's an omission in containerd @AkihiroSuda  ?

Comment (thaJeztah) [reply daemon/device_unix.go:39]: I opened https://github.com/containerd/containerd/pull/6306 for that last bit

File: daemon/device_unix.go [hunk 4]
```diff
@@ -0,0 +1,81 @@
...
+				continue
+			default:
+				sub, err := GetDevices(filepath.Join(path, f.Name()))
+				if err != nil {
+					return nil, err
+				}
+
+				if sub != nil {
+					out = append(out, sub...)
+				}
```
[the remark this answers is not in the document]
Comment (eliaskoromilas) [reply daemon/device_unix.go:59]: You are right! I probably got it, as is, from there: https://github.com/containers/podman/blob/v3.4.2/pkg/specgen/generate/config_linux.go#L210-L212

Yes... Podman also has it's own version of `GetDevices`.

File: daemon/device_unix.go [hunk 5]
```diff
@@ -0,0 +1,81 @@
...
+	"os"
+	"path/filepath"
+
+	"github.com/containerd/containerd/pkg/userns"
+	"github.com/opencontainers/runc/libcontainer/devices"
+)
+
+// Testing dependencies
+var (
+	ioutilReadDir         = ioutil.ReadDir
```
[the remark this answers is not in the document]
Comment (eliaskoromilas) [reply daemon/device_unix.go]: Sure.

File: daemon/device_unix.go (hunk 3 above)
Comment (eliaskoromilas) [reply daemon/device_unix.go:38]: That's true. Since we can't rely on `libcontainer`, if you think that `containerd` should be the upstream, let's move it there.

Comment (thaJeztah) [reply daemon/device_unix.go:38]: I was giving it a quick try; let me push what I have as a PR there (but feel free to pick it up from there)

File: daemon/device_unix_test.go [hunk 6]
```diff
@@ -0,0 +1,152 @@
...
+		}
+		called = true
+
+		// Provoke a second call.
+		fi, err := os.Lstat("/tmp")
+		if err != nil {
+			t.Fatalf("Unexpected error %v", err)
+		}
+
+		return []fs.DirEntry{fs.FileInfoToDirEntry(fi)}, nil
```
Comment (thaJeztah) [inline daemon/device_unix_test.go:116]: Just a note; this won't work on Go 1.16, but we currently don't run that version in CI; given that this only affects testing code (and master moved to go1.17), perhaps that's not a problem; we added code in https://github.com/moby/moby/pull/42797 to work around that, but not sure if it's worth going through that to make the test work on Go 1.16
(Perhaps a build-tag for this file _could_ work as a quick fix)

Comment (eliaskoromilas) [reply daemon/device_unix_test.go:116]: I added a build tag. In `runc` there is a similar workaround, too. Most probably we are going to move the missing unit tests to `containerd` anyway.

**Comment by eliaskoromilas** [comment]
I will rebase this after vendoring `containerd`.

**Comment by eliaskoromilas** [comment]
@thaJeztah Should we vendor **github.com/containerd/containerd v1.5.9** now?

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
oh! almost forgot we had this one; thanks for the rebase, and good that it's all working as expected with the changes in containerd 👍 🎉

**Review by thaJeztah — APPROVED** [review]
LGTM!
