### PR TITLE
Terminate template containers before delting a layer

### LINKED ISSUE #28087: Can't rmi an image after running a Hyper-V container from it, and directory leaked.
On master

@swernli @darrenstahlmsft @jstarks 

The "rename on delete" PR has broken the ability to docker rmi images. See repro below:

```
PS C:\baseimages> docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
PS C:\baseimages> docker load -i .\nanoserver.tar
Loaded image: microsoft/nanoserver:10.0.14393.321
Loaded image: microsoft/nanoserver:latest
PS C:\baseimages> docker run --rm --isolation=hyperv microsoft/nanoserver powershell echo hello
hello
PS C:\baseimages> docker images
REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE
microsoft/nanoserver   10.0.14393.321      22738ff49c6d        4 weeks ago         686 MB
microsoft/nanoserver   latest              22738ff49c6d        4 weeks ago         686 MB
PS C:\baseimages> docker rmi microsoft/nanoserver
Untagged: microsoft/nanoserver:latest
PS C:\baseimages> docker rmi 22738
Error response from daemon: rename C:\a\b\c\windowsfilter\c600d489c09f07aeb05b55ad2c8db12fd0051d28409073eda4bbdcde67397ea3 C:\a\b\c\windowsfilter\c600d489c09f07aeb05b55ad2c8db12fd0051d28409073eda4bbdcde67397ea3-removing: Access is denied.
PS C:\baseimages> docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
PS C:\baseimages> docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
PS C:\baseimages> get-computeprocess


Id                : 82788C08-FCC9-4610-AF8B-3A84F97E74DC
Type              : Container
Isolation         : HyperV
IsTemplate        : True
RuntimeId         : 82788c08-fcc9-4610-af8b-3a84f97e74dc
RuntimeTemplateId :
RuntimeImagePath  : C:\a\b\c\windowsfilter\c600d489c09f07aeb05b55ad2c8db12fd0051d28409073eda4bbdcde67397ea3\UtilityVM
Owner             :



PS C:\baseimages> get-computeprocess | stop-computeprocess

Confirm
Are you sure you want to stop the compute process with ID '82788C08-FCC9-4610-AF8B-3A84F97E74DC'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): A
PS C:\baseimages> docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
PS C:\baseimages> cd C:\a\b\c\windowsfilter\
PS C:\a\b\c\windowsfilter> dir


    Directory: C:\a\b\c\windowsfilter


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        11/4/2016   6:25 PM                c600d489c09f07aeb05b55ad2c8db12fd0051d28409073eda4bbdcde67397ea3


PS C:\a\b\c\windowsfilter> cd .\c600d489c09f07aeb05b55ad2c8db12fd0051d28409073eda4bbdcde67397ea3\
PS C:\a\b\c\windowsfilter\c600d489c09f07aeb05b55ad2c8db12fd0051d28409073eda4bbdcde67397ea3> dir


    Directory: C:\a\b\c\windowsfilter\c600d489c09f07aeb05b55ad2c8db12fd0051d28409073eda4bbdcde67397ea3


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        10/5/2016   5:04 PM                Files
d-----        11/4/2016   6:25 PM                Hives
d-----        11/4/2016   6:25 PM                UtilityVM
-a----        11/4/2016   6:25 PM          16384 bcd.bak
-a----        11/4/2016   6:25 PM          12288 bcd.log.bak
-a----        11/4/2016   6:25 PM              0 bcd.log1.bak
-a----        11/4/2016   6:25 PM              0 bcd.log2.bak
-a----        11/4/2016   6:25 PM       42991616 blank-base.vhdx
-a----        11/4/2016   6:25 PM        4194304 blank.vhdx
-a----        11/4/2016   6:25 PM              4 layerchain.json


PS C:\a\b\c\windowsfilter\c600d489c09f07aeb05b55ad2c8db12fd0051d28409073eda4bbdcde67397ea3> docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
PS C:\a\b\c\windowsfilter\c600d489c09f07aeb05b55ad2c8db12fd0051d28409073eda4bbdcde67397ea3> docker images -a
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
PS C:\a\b\c\windowsfilter\c600d489c09f07aeb05b55ad2c8db12fd0051d28409073eda4bbdcde67397ea3>
```

### PR DESCRIPTION
**Pull request by darstahl**
fixes https://github.com/docker/docker/issues/28087

**- What I did**

When deleting a layer, make sure to terminate any template VMs that are using the layer.

**- How I did it**

Add GetContainers to hcsshim, used to check if the layer is in use by any containers on the system. Terminate all template VMs that are using the layer being deleted.

**- How to verify it**

See repro steps for https://github.com/docker/docker/issues/28087. Will add a test to this PR soon.

NOTE: This needs a vendor update to hcsshim after https://github.com/Microsoft/hcsshim/pull/86 and https://github.com/Microsoft/hcsshim/pull/85 are merged.

Signed-off-by: Darren Stahl <darst@microsoft.com>

/cc @jhowardmsft @jstarks

### CODE REVIEW

File: daemon/graphdriver/windows/windows.go [hunk 1]
```diff
@@ -244,6 +244,31 @@ func (d *Driver) Remove(id string) error {
 		return err
 	}
 
+	computeSystems, err := hcsshim.GetContainers(hcsshim.ComputeSystemQuery{})
```
Comment (jstarks) [inline daemon/graphdriver/windows/windows.go]: Needs a comment on why we're doing this.

**Comment by cpuguy83** [comment]
Can you put vendor into a separate commit?

**Comment by darrenstahlmsft** [comment]
I think @jhowardmsft is also needing an hcsshim vendor, so it should go in as a separate PR.

**Comment by jhowardmsft** [comment]
Yes, I do :smile:. Will open shortly.

**Comment by darrenstahlmsft** [comment]
Vendor got merged in https://github.com/docker/docker/pull/28175, this is good for review.

**Comment by darrenstahlmsft** [comment]
@thaJeztah FYI this is a critical bugfix needed for 1.13

**Comment by jhowardmsft** [comment]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM
