### PR TITLE
only close LogDriver after LogCopier is done

### LINKED ISSUE #19371: Orphaned logs when the container exits
When an application sending logs fast enough to populate the log buffers, but then exits before the log buffer is completely flushed, the buffer will still be drained even if the log driver is closed.

This is easily replicable in 1.9 and 1.10-dev ( 1.10 is abit harder because of the new fixed buffer ). 
The symptom is that the container after flushing all its logs into the docker's buffer will exit, the udp connection in the log driver is closed, but the log copier will still flushing the current buffer into the log driver, which leads to these errors:

```
Jan 15 15:41:18 cf docker[21652]: time="2016-01-15T15:41:18.181604406Z" level=error msg="Failed to log msg \"0123456789 18180\" for logger gelf: gelf: cannot send GELF message: write udp 127.0.0.1:58356->127.0.0.1:23010: use of closed network connection"
```

This is particularly bad in 1.9, a bit more managable in 1.10 because the buffer size is only 1mb now, but this should still be fixed.

### How to replicate

```
# container
> docker run --log-driver=gelf --log-opt=gelf-address=udp://127.0.0.1:23010 debian:jessie sh -c 'for i in $(seq 1 20000); do echo 0123456789 $i; done'

# run a udp listener, i use this program, but you can probable use netcat -ulp 23010 as well
package main

import (
        "log"
        "net"
)

func main() {
        addr, err := net.ResolveUDPAddr("udp", ":23010")
        if err != nil {
                panic(err)
        }
        c, err := net.ListenUDP("udp", addr)
        if err != nil {
                panic(err)
        }
        log.Printf("listened to %s", addr.String())
        b := make([]byte, 1000)
        i := 1
        for {
                count, err := c.Read(b)
                if err != nil {
                        log.Printf("ERROR: %v", err)
                }
                i += 1
                log.Printf("%d: received %d", i, count)
        }
}
```

Instead of closing the driver prematurely, we should only close it when we make sure that the log copier is closed i.e. nothing will be sent into a closed log driver.

### System info

```
Client:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9b63019
 Built:        Fri Jan 15 12:15:39 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9b63019
 Built:        Fri Jan 15 12:15:39 2016
 OS/Arch:      linux/amd64
```

```
Containers: 49
 Running: 0
 Paused: 0
 Stopped: 49
Images: 502
Server Version: 1.10.0-dev
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.18.13
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.864 GiB
ID: CVPU:RQBK:OU2T:PW7R:2XMU:G2IA:LXJG:HU57:MTJJ:M2UD:7OZA:RJVE
Username: dqminh
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

### PR DESCRIPTION
**Pull request by dqminh**
Fix #19371

This prevents the copier from sending messages in the buffer to the closed
driver. If the copied took longer than the timeout to drain the buffer, this
aborts the copier read loop and return back so we can cleanup resources
properly.

cc @LK4D4

### CODE REVIEW

File: container/monitor.go [hunk 1]
```diff
@@ -369,10 +369,15 @@ func (m *containerMonitor) resetContainer(lock bool) {
 			select {
 			case <-time.After(loggerCloseTimeout):
 				logrus.Warnf("Logger didn't exit in time: logs may be truncated")
+				container.LogCopier.Close()
+				// always waits for the LogCopier to finished before closing
+				<-exit
 			case <-exit:
 			}
+			container.LogDriver.Close()
```
Comment (LK4D4) [inline container/monitor.go]: Seems like this call will be executed in any case. So there is no need in else.

File: daemon/logger/copier.go [hunk 2]
```diff
@@ -69,3 +73,8 @@ func (c *Copier) copySrc(name string, src io.Reader) {
 func (c *Copier) Wait() {
 	c.copyJobs.Wait()
 }
+
+// Closed closed the copier
+func (c *Copier) Close() {
+	c.closed = true
```
Comment (LK4D4) [inline daemon/logger/copier.go]: There is an obvious race between this and check in `copySrc`.

Comment (dqminh) [inline daemon/logger/copier.go]: yes, which is why we wait for <-exit after Close() is called. I think that should suffice ?

File: container/monitor.go (hunk 1 above)
Comment (dqminh) [inline container/monitor.go]: right this is redundant now, i will change.

File: daemon/logger/copier.go (hunk 2 above)
Comment (LK4D4) [inline daemon/logger/copier.go]: Hmm, go race detector will complain that you're reading and writing to the same variable at the same time. The runtime can even crash because of this.
I'd prefer to protect this var somehow or use a channel for that task.

Comment (dqminh) [inline daemon/logger/copier.go]: added a RWMutex for this.

**Comment by LK4D4** [comment]
LGTM

**Comment by cpuguy83** [comment]
Can we implement this with a channel instead of an RWMutex?

```
BenchmarkMu-8  	100000000	        21.4 ns/op	       0 B/op	       0 allocs/op
BenchmarkRWMu-8	100000000	        20.5 ns/op	       0 B/op	       0 allocs/op
BenchmarkChan-8	200000000	         9.64 ns/op	       0 B/op	       0 allocs/op

BenchmarkMu  	100000000	        21.4 ns/op	       0 B/op	       0 allocs/op
BenchmarkRWMu	100000000	        20.7 ns/op	       0 B/op	       0 allocs/op
BenchmarkChan	100000000	        10.4 ns/op	       0 B/op	       0 allocs/op
```

Seems to be about 2x as fast.
https://gist.github.com/cpuguy83/9abc82cec3a2286b000e

**Comment by dqminh** [comment]
@cpuguy83 makes sense. Updated.

**Comment by cpuguy83** [comment]
LGTM
