### PR TITLE
api/types: fix Plugin.Config.Interface.Types Swagger definition

### LINKED ISSUE #42593: Remove use of "go-swagger" fork, and update to current version
related to https://github.com/moby/moby/pull/36714

We currently use go-swagger for two purposes:

1. to validate the swagger file (against the swagger/openapi specs)
2. to generate some Go types from the swagger YAML, and to validate that (generated) types match the definition in the swagger file (see https://github.com/moby/moby/pull/27117)

For `1.`, we should be able to switch to use upstream/latest. However, for `2.`, things are more "complicated"; our code depends on a feature in go-swagger (see https://github.com/go-swagger/go-swagger/issues/676, https://github.com/go-swagger/go-swagger/pull/680) that was removed (or refactored/changed) https://github.com/go-swagger/go-swagger/issues/2077. For our purpose we only want to generate some _types_ from the Swagger file, and not generate other code (i.e., we don't want it to generate a full client);
Given that the feature was removed (or at least, no longer works with how we call it), we are currently not able to update go-swagger (for `2.`). Unfortunately, the version we rely on has some issues;

- compatibility with recent go versions broke (forcing us to use a fork of go-swagger, in which we maintain patches)
- the version we use has a bug; when generating types, the order in which fields end up in the generated code is randomized (due to some code in go-swagger iterates over `map[string]` which (by design) is randomized by golang). This causes CI to be "flaky" (swagger validation randomly failing if changes are made to the swagger file).

In short, we should: remove use of our go-swagger fork, so that we can consume fixes and features from newer versions in upstream.

- As a short term solution for `1.`, we could "split" the use; use upstream go-swagger for validating against the spec, and our fork only for generating.
- Look (again) what features are missing in upstream, or if we can rewrite our use to make it work again with current versions (see https://github.com/go-swagger/go-swagger/issues/2077)
- Alternatively, use go-swaggger _only_ for validating, and replace the "generator" code with an alternative implementation; work on that was started in https://github.com/moby/moby/pull/36714, but there were some issues with that PR (_plus_ it required us to maintain our own generator code, which wasn't ideal either).

### LINKED ISSUE #42809: [Documentation] PluginInterfaceType does not match data returned
**Description**
The http API for [Inspect Plugin](https://docs.docker.com/engine/api/v1.41/#operation/PluginInspect) shows the returned property "Types" of subobject Interface inside Config to be of type "array of PluginInterfaceType" which in turn is a object. However the example show an array of strings, which matches the data returned by docker. So either the api and example is wrong or the described return type is wrong.

**Steps to reproduce the issue:**
1. RTFM
2. Wonder why the manual does not match the returned data
3. Cry

**Describe the results you received:**
```json
[
    {
        "Config": {
            ...
            "Interface": {
                "Socket": "sshfs.sock",
                "Types": [
                    "docker.volumedriver/1.0"
                ]
            },
           ...
        },
        ...
    }
]
```

**Describe the results you expected:**
```json
[
    {
        "Config": {
            ...
            "Interface": {
                "Socket": "sshfs.sock",
                "Types": [{
                    "prefix":"docker",
                    "capability":"volumedriver",
                    "version":"1.0"
                }]
            },
           ...
        },
        ...
    }
]
```

**Additional information you deem important (e.g. issue happens only occasionally):**
Documentation issue. Changing the returned data would make it easier to parse but breaks backwards compatibility.

**Output of `docker version`:**
N/A

**Output of `docker info`:**
N/A

**Additional environment details (AWS, VirtualBox, physical, etc.):**
N/A

### PR DESCRIPTION
**Pull request by corhere**
**- What I did**
- Fixes #42593 
- Fixes #42809 
- Closes #47827 

I fixed up the Swagger definition for `Plugin.Config.Interface.Types` to accurately express that it is an array of strings over the wire while maintaining the parsed struct type on the Go side.

**- How I did it**
I upgraded to the latest go-swagger to make use of [`x-go-type` external type extensions](https://goswagger.io/go-swagger/reference/models/schemas/#external-types) so the generated Go struct field uses the type of my choice instead of plain strings. I customized the Swagger generation templates to suppress generating validators or marshal/unmarshal code.

**- How to verify it**
CI

**- Human readable description for the release notes**

```markdown changelog

```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: api/types/image/image_history.go [hunk 1]
```diff
@@ -8,6 +8,7 @@ package image
 
 // HistoryResponseItem individual image layer information in response to ImageHistory operation
 // swagger:model HistoryResponseItem
+
```
Comment (thaJeztah) [inline api/types/image/image_history.go]: Looks like the template adds an empty line between the GoDoc and the type

**Comment by corhere** [comment]
I tried putting the CapabilityID definition into pkg/plugins but that would lead to a module dependency cycle (github.com/moby/moby -> github.com/moby/moby/api -> github.com/moby/moby) so I took the path of least resistance and moved the type definition back into the api module.

**Review by dmcgowan — APPROVED** [review]

**Comment by thaJeztah** [comment]
do we want to do the move of these types to api/types/plugin (and remove the "Plugin" prefix) as well as part of this PR, or in a follow up?

**Comment by corhere** [comment]
@thaJeztah I structured this PR to not conflict with your PR that moves the plugin type definitions. I say we keep the PRs separate

**Comment by thaJeztah** [comment]
Gotcha! Happy to do the follow up; I wasn't sure if it was intentional.

@corhere this one needs a rebase now (as the module PR was merged)

**Review by thaJeztah — APPROVED** [review]
LGTM

Thank YOU! Really happy we finally got rid of that swagger fork 🎉

File: api/types/plugin/capability.go [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+	t.Version = string(version)
+	return nil
+}
+
+// MarshalText implements [encoding.TextMarshaler] for CapabilityID
+func (t CapabilityID) MarshalText() ([]byte, error) {
+	// Assert that the value can be round-tripped successfully.
+	if strings.Contains(t.Capability, ".") {
+		return nil, fmt.Errorf("capability %q cannot contain a dot", t.Capability)
+	}
```
Comment (thaJeztah) [inline api/types/plugin/capability.go:47]: Interesting; getting a failure in some e2e test in the CLI - not unlikely that the dummy value it used was _supposed_ to be valid 🤔 ;

```
=== Failed
=== FAIL: e2e/global TestPromptExitCode/plugin_install (0.28s)
    cli_test.go:203: assertion failed: error is not nil: json: error calling MarshalText for type plugin.CapabilityID: capability "docker.dummy/1.0" cannot contain a dot

=== FAIL: e2e/global TestPromptExitCode/plugin_upgrade (0.26s)
    cli_test.go:203: assertion failed: error is not nil: json: error calling MarshalText for type plugin.CapabilityID: capability "docker.dummy/1.0" cannot contain a dot
```

Comment (corhere) [reply api/types/plugin/capability.go:47]: Yes; `PluginInterfaceType` was frequently misused by setting the `Capability` field to the fully-qualified capability ID and leaving the other two fields blank. A value such as `PluginInterfaceType{Capability: "docker.dummy/1.0"}` would marshal to the string `".docker.dummy/1.0/"` which is not well-formed and [does not round-trip to the same value even with the old parser](https://go.dev/play/p/KFSl2GVK68D)

Comment (thaJeztah) [reply api/types/plugin/capability.go:47]: Yes, I later realised that was probably what happened.


In all honesty, I don't think there will be many (if any) users of these types; plugins are not widely used, and I doubt there's many users that consume that part of the client (and API).
