### PR TITLE
c8d/inspect: Handle dangling images

### LINKED ISSUE #45230: `inspect` on dangling image doesn't work
### Description

Reported by @tianon

Inspecting a dangling image doesn't work with containerd integration.

### Reason
Inspect doesn't explicitly check if image is dangling at tries to parse its reference (which is a special, non-canonical `moby-dangling@sha256:...` format).
https://github.com/moby/moby/blob/d0f6fa036b91a2e0776eae2bd2e2908488530d7d/daemon/containerd/image.go#L102-L111

### Reproduce

```bash
$ docker images
REPOSITORY                       TAG       IMAGE ID       CREATED          SIZE
<none>                           <none>    9a63cd0416de   16 minutes ago   27.3MB
ubuntu                           latest    67211c14fa74   20 hours ago     27.4MB

$ docker inspect 9a63cd0416de # dangling
[]
Error response from daemon: repository name must be canonical

$ docker inspect 67211c14fa74 | head -n3 # ubuntu
[
    {
        "Id": "sha256:ca620b6a713882989f2dfb31dd34705834c95bc23e493687828080f6e5ad1be6",
```

### Expected behavior

The following commands should work:
```
$ docker inspect 9a63cd0416de
$ docker inspect 9a63cd0416de5b57259fa340d1
$ docker inspect sha256:sha256:9a63cd0416de5b57259fa340d1b8aff476065c4ab5f626232370504124e222c3
```

### docker version

```bash
master - d0f6fa036b91a2e0776eae2bd2e2908488530d7d
```

### docker info

```bash
containerd integration
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by vvoland**
- Fixes: https://github.com/moby/moby/issues/45230

**- What I did**
Fix `Error response from daemon: repository name must be canonical` error when calling `docker image inspect` with a dangling image id (short or full digest).

**- How I did it**
Don't try to parse dangling images name (they have a non-canonical format - `moby-dangling@sha256:...`) as a reference. Log a warning if the image is not dangling and its name is not a valid named reference.

**- How to verify it**
```bash
$ docker images
REPOSITORY   TAG       IMAGE ID       CREATED              SIZE
busybox      latest    b5d6fe071263   About a minute ago   2.01MB
<none>       <none>    124c7d270790   18 seconds ago       3.27MB

$ docker inspect 124c7d270790 -f '{{.ID}}'
sha256:124c7d2707904eea7431fffe91522a01e5a861a624ee31d03372cc1d138a3126

$docker inspect 124c7d -f '{{.ID}}'
sha256:124c7d2707904eea7431fffe91522a01e5a861a624ee31d03372cc1d138a3126

$ docker inspect sha256:124c7d2707904eea7431fffe91522a01e5a861a624ee31d03372cc1d138a3126 -f '{{.ID}}'
sha256:124c7d2707904eea7431fffe91522a01e5a861a624ee31d03372cc1d138a3126

$ docker inspect 124c7d2707904eea7431fffe91522a01e5a861a624ee31d03372cc1d138a3126 -f '{{.ID}}'
sha256:124c7d2707904eea7431fffe91522a01e5a861a624ee31d03372cc1d138a3126

```

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: daemon/containerd/image.go [hunk 1]
```diff
@@ -103,9 +104,22 @@ func (i *ImageService) GetImage(ctx context.Context, refOrID string, options ima
...
+				continue
+			}
+
 			name, err := reference.ParseNamed(i.Name)
 			if err != nil {
-				return nil, err
+				// This is inconsistent with `docker image ls` which will
+				// still include the malformed name in RepoTags.
+				logrus.WithField("name", name).WithError(err).Error("failed to parse image name as reference")
+				continue
```
Comment (vvoland) [inline daemon/containerd/image.go:122]: https://github.com/moby/moby/blob/d0f6fa036b91a2e0776eae2bd2e2908488530d7d/daemon/containerd/image_list.go#L177
We can't pass the "bad" name here, because `References` is a `[]reference.Named` instead of `[]string` like in List...

Related discussion on `RepoTags` in list: https://github.com/moby/moby/pull/44840#discussion_r1084088210

IMO the inconsistency is worse than not showing the bad name in RepoTags, so maybe we should change the List behavior to match this?

File: daemon/containerd/image.go [hunk 2]
```diff
@@ -103,9 +104,22 @@ func (i *ImageService) GetImage(ctx context.Context, refOrID string, options ima
 			if i.UpdatedAt.After(lastUpdated) {
 				lastUpdated = i.UpdatedAt
 			}
+			if isDanglingImage(i) {
+				if len(tagged) > 1 {
```
Comment (tianon) [inline daemon/containerd/image.go:108]: Doesn't this line only run if `tagged` is non-empty since it's inside a loop that's looping over `tagged`'s entries? :sweat_smile:

Comment (tianon) [reply daemon/containerd/image.go:108]: (what I mean is that this `if`'s condition will always be true)

Comment (vvoland) [reply daemon/containerd/image.go:108]: It won't be true if tagged has only one element (which we are currently iterating) AND it's dangling.

If any image from tagged has the dangling name AND tagged is more than 1 element, then it means that the image itself is not dangling and there shouldn't be any image with the special dangling name.

**Review by tianon — APPROVED** [review]

**Review by thaJeztah — APPROVED** [review]
LGTM
