### PR TITLE
Fix host_ipv4 bridge option when IPv6 and ip6tables are enabled

### LINKED ISSUE #46445: ip6tables fails during network creation when com.docker.network.host_ipv4 bridge option is set
### Description

With IPv6 and the experimental `ip6tables` option enabled in the daemon, creating an IPv6-enabled bridge network with the `com.docker.network.host_ipv4` option set fails with:

```
Error response from daemon: Failed to Setup IP tables: Unable to enable NAT rule:  (iptables failed: ip6tables --wait -t nat -I POSTROUTING -s fd01::/64 ! -o br-f15cb6308dee -j SNAT --to-source 192.168.0.2: ip6tables v1.8.7 (legacy): Bad IP address "192.168.0.2"

Try `ip6tables -h' or 'ip6tables --help' for more information.
 (exit status 2))
```

This is because the IPv4 address is used when setting up both the IPv4 rules and the IPv6 rules:  https://github.com/moby/moby/blob/6ce5aa1cd5a46e02ffaa3fe0c794642b35601676/libnetwork/drivers/bridge/setup_ip_tables_linux.go#L160-L165

### Reproduce

1. `dockerd --ipv6 --fixed-cidr-v6=fd00::/64 --experimental --ip6tables`
2. `docker network create -d bridge --ipv6 --subnet fd01::/64 --opt com.docker.network.host_ipv4=192.168.0.2 test-network`

### Expected behavior

Docker should create a bridge network with IPv4 SNAT (to the given IP) and IPv6 masquerade.

### docker version

```bash
Client: Docker Engine - Community
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:31:44 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:44 2023
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 5
  Running: 5
  Paused: 0
  Stopped: 0
 Images: 1159
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.2.0-26-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 23.46GiB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 172.17.0.0/16, Size: 24
   Base: 172.18.0.0/15, Size: 23
   Base: 172.20.0.0/14, Size: 22
   Base: 172.24.0.0/13, Size: 21
   Base: fd01::/64, Size: 64
```

### Additional Info

The following change should fix it (I'll open a new pull request once I write a regression test):

```diff
diff --git a/libnetwork/drivers/bridge/setup_ip_tables_linux.go b/libnetwork/drivers/bridge/setup_ip_tables_linux.go
index c98781f3b0..5d2289014b 100644
--- a/libnetwork/drivers/bridge/setup_ip_tables_linux.go
+++ b/libnetwork/drivers/bridge/setup_ip_tables_linux.go
@@ -157,11 +157,15 @@ func (n *bridgeNetwork) setupIPTables(ipVersion iptables.IPVersion, maskedAddr *
                        return setupInternalNetworkRules(config.BridgeName, maskedAddr, config.EnableICC, false)
                })
        } else {
-               if err = setupIPTablesInternal(config.HostIP, config.BridgeName, maskedAddr, config.EnableICC, config.EnableIPMasquerade, hairpinMode, true); err != nil {
+               hostIP := config.HostIP
+               if ipVersion != iptables.IPv4 {
+                       hostIP = nil
+               }
+               if err = setupIPTablesInternal(hostIP, config.BridgeName, maskedAddr, config.EnableICC, config.EnableIPMasquerade, hairpinMode, true); err != nil {
                        return fmt.Errorf("Failed to Setup IP tables: %s", err.Error())
                }
                n.registerIptCleanFunc(func() error {
-                       return setupIPTablesInternal(config.HostIP, config.BridgeName, maskedAddr, config.EnableICC, config.EnableIPMasquerade, hairpinMode, false)
+                       return setupIPTablesInternal(hostIP, config.BridgeName, maskedAddr, config.EnableICC, config.EnableIPMasquerade, hairpinMode, false)
                })
                natChain, filterChain, _, _, err := n.getDriverChains(ipVersion)
                if err != nil {
```

### PR DESCRIPTION
**Pull request by rhansen**
Before this commit, setting the `com.docker.network.host_ipv4` bridge option when `enable_ipv6` is true and the experimental `ip6tables` option is enabled would cause Docker to fail to create the network:

> failed to create network `test-network`: Error response from daemon: Failed to Setup IP tables: Unable to enable NAT rule: (iptables failed: `ip6tables --wait -t nat -I POSTROUTING -s fd01::/64 ! -o br-test -j SNAT --to-source 192.168.0.2`: ip6tables v1.8.7 (nf_tables): Bad IP address "192.168.0.2"
>
> Try `ip6tables -h` or `ip6tables --help` for more information.
>  (exit status 2))

Fix this error by passing nil—not the `host_ipv4` address—when creating the IPv6 rules.

**- How to verify it**

Unit tests:

`make TESTDIRS=github.com/docker/docker/libnetwork/drivers/bridge test-unit`

Testing a fully built binary:

```
dockerd --ipv6 --fixed-cidr-v6=fd00::/64 --experimental --ip6tables
docker network create -d bridge --ipv6 --subnet fd01::/64 --opt com.docker.network.host_ipv4=192.168.0.2 test-network
```

**- Description for the changelog**

Fixed `com.docker.network.host_ipv4` option when IPv6 and `ip6tables` are enabled.

Fixes #46445

### CODE REVIEW

**Review by akerouanton — APPROVED** [review]
LGTM

File: libnetwork/drivers/bridge/setup_ip_tables_linux_test.go [hunk 1]
```diff
@@ -92,6 +93,11 @@ func createTestBridge(config *networkConfiguration, br *bridgeInterface, t *test
 	if err := setupBridgeIPv4(config, br); err != nil {
 		t.Fatalf("Failed to bring up the testing Bridge: %s", err.Error())
 	}
+	if config.EnableIPv6 {
+		if err := setupBridgeIPv6(config, br); err != nil {
```
Comment (thaJeztah) [inline libnetwork/drivers/bridge/setup_ip_tables_linux_test.go:97]: Given that we're passing `config` to the function , would it make sense to sense to have `setupBridgeIPv6` return early if `EnableIPv6` is not set?


```go
func setupBridgeIPv6(config *networkConfiguration, i *bridgeInterface) error {
	if !config.EnableIPv6 {
		return nil
	}
	// .....	
}

File: libnetwork/drivers/bridge/setup_ip_tables_linux.go [hunk 2]
```diff
@@ -157,11 +157,15 @@ func (n *bridgeNetwork) setupIPTables(ipVersion iptables.IPVersion, maskedAddr *
 			return setupInternalNetworkRules(config.BridgeName, maskedAddr, config.EnableICC, false)
 		})
 	} else {
-		if err = setupIPTablesInternal(config.HostIP, config.BridgeName, maskedAddr, config.EnableICC, config.EnableIPMasquerade, hairpinMode, true); err != nil {
+		hostIP := config.HostIP
+		if ipVersion != iptables.IPv4 {
+			hostIP = nil
+		}
+		if err = setupIPTablesInternal(hostIP, config.BridgeName, maskedAddr, config.EnableICC, config.EnableIPMasquerade, hairpinMode, true); err != nil {
```
Comment (thaJeztah) [inline libnetwork/drivers/bridge/setup_ip_tables_linux.go:164]: I see `setipIPTablesInternal` already has some handling for IPv4 <--> IPv6. I haven't looked closely, but wondering the same for this function, and if it should either

- get passed `config` (as a whole)
- or check if `hostIP.To4() == nil` (as it does for other addresses)

https://github.com/moby/moby/blob/6ce5aa1cd5a46e02ffaa3fe0c794642b35601676/libnetwork/drivers/bridge/setup_ip_tables_linux.go#L205-L230

File: libnetwork/drivers/bridge/setup_ip_tables_linux.go [hunk 3]
```diff
@@ -157,11 +157,15 @@ func (n *bridgeNetwork) setupIPTables(ipVersion iptables.IPVersion, maskedAddr *
...
 			return fmt.Errorf("Failed to Setup IP tables: %s", err.Error())
 		}
 		n.registerIptCleanFunc(func() error {
-			return setupIPTablesInternal(config.HostIP, config.BridgeName, maskedAddr, config.EnableICC, config.EnableIPMasquerade, hairpinMode, false)
+			return setupIPTablesInternal(hostIP, config.BridgeName, maskedAddr, config.EnableICC, config.EnableIPMasquerade, hairpinMode, false)
```
Comment (thaJeztah) [inline libnetwork/drivers/bridge/setup_ip_tables_linux.go:168]: Is cleanup needed in cases where `hosIP` is `nil` (or if it's an IPv6 address?)

File: libnetwork/drivers/bridge/setup_ip_tables_linux_test.go [hunk 4]
```diff
@@ -123,13 +129,20 @@ func assertChainConfig(d *driver, t *testing.T) {
...
 }
 
 // Assert function which pushes chains based on bridge config parameters.
 func assertBridgeConfig(config *networkConfiguration, br *bridgeInterface, d *driver, t *testing.T) {
 	nw := bridgeNetwork{
-		portMapper: portmapper.New(""),
-		config:     config,
+		portMapper:   portmapper.New(""),
+		portMapperV6: portmapper.New(""),
+		config:       config,
```
Comment (thaJeztah) [inline libnetwork/drivers/bridge/setup_ip_tables_linux_test.go:145]: Interesting (not new in this PR, so something to look at separately), but it looks like we _never_ pass a value to `portmapper.New()`, so perhaps we should remove the argument. From that, also wondering if these should be initialised, or if we should make this struct have `nil` if not used (and only initialise a portmapper for those IP-versions that we use) 🤔 

Screenshot 2023-09-11 at 13 09 36

File: libnetwork/drivers/bridge/setup_ip_tables_linux_test.go (hunk 1 above)
Comment (rhansen) [reply libnetwork/drivers/bridge/setup_ip_tables_linux_test.go:97]: Maybe.  This test code is mimicking the following:
https://github.com/moby/moby/blob/51d647122ad34628a92252c2b2a9f865f4b20613/libnetwork/drivers/bridge/bridge_linux.go#L743-L747
If `setupBridgeIPv6` is changed then we should change that code too, and I think that deserves its own consideration in a separate pull request.

File: libnetwork/drivers/bridge/setup_ip_tables_linux.go (hunk 2 above)
Comment (rhansen) [reply libnetwork/drivers/bridge/setup_ip_tables_linux.go:164]: I think it would be cleaner to pass `config` as a whole, but I wanted this commit to be the minimal needed to fix the bug  (and add a regression test).  I'll open a separate PR to do some refactoring for code health.

File: libnetwork/drivers/bridge/setup_ip_tables_linux.go (hunk 3 above)
Comment (rhansen) [reply libnetwork/drivers/bridge/setup_ip_tables_linux.go:168]: Yes, it is still needed—`setupIPTablesInternal` does much more than NAT, for both IPv4 and IPv6.

File: libnetwork/drivers/bridge/setup_ip_tables_linux_test.go (hunk 4 above)
Comment (rhansen) [reply libnetwork/drivers/bridge/setup_ip_tables_linux_test.go:145]: I'll take a look and include any worthwhile cleanups in a separate PR.

File: libnetwork/drivers/bridge/setup_ip_tables_linux_test.go [hunk 5]
```diff
@@ -138,4 +151,37 @@ func assertBridgeConfig(config *networkConfiguration, br *bridgeInterface, d *dr
 	if err != nil {
 		t.Fatalf("%v", err)
 	}
+	if d.config.EnableIP6Tables {
+		if err := nw.setupIP6Tables(config, br); err != nil {
+			t.Fatalf("%v", err)
```
Comment (thaJeztah) [inline libnetwork/drivers/bridge/setup_ip_tables_linux_test.go:156]: nit:

```suggestion
			t.Fatal(err)
```

File: libnetwork/drivers/bridge/setup_ip_tables_linux_test.go [hunk 6]
```diff
@@ -138,4 +151,37 @@ func assertBridgeConfig(config *networkConfiguration, br *bridgeInterface, d *dr
...
+func TestSetupIP6TablesWithHostIP(t *testing.T) {
+	defer netnsutils.SetupTestOSContext(t)()
+	d := newDriver()
+	dc := &configuration{
+		EnableIPTables:  true,
+		EnableIP6Tables: true,
+	}
+	if err := d.configure(map[string]interface{}{netlabel.GenericData: dc}); err != nil {
+		t.Fatal(err)
+	}
```
Comment (thaJeztah) [inline libnetwork/drivers/bridge/setup_ip_tables_linux_test.go:171]: nit: perhaps inline `dc` as it's only used in a single place;

```suggestion
	if err := d.configure(map[string]interface{}{netlabel.GenericData: &configuration{
		EnableIPTables:  true,
		EnableIP6Tables: true,
	}}); err != nil {
		t.Fatal(err)
	}
```

**Review by thaJeztah — APPROVED** [review]
LGTM
