### PR TITLE
Fix symlink handling in builder ADD/COPY commands

### LINKED ISSUE #17290: 1.9: build caching broken from symlink??
This is an odd one but I tried to extract out the offending files out of a real build.  In the end second build in the below script will end up using the cached image for `CP . ./` when it shouldn't

```bash
#!/bin/bash

cat > Dockerfile << "EOF"
FROM busybox
COPY . ./
EOF

mkdir -p Godeps/_workspace/src/github.com/fsouza/go-dockerclient/testing/data
ln -s doesnotexist Godeps/_workspace/src/github.com/fsouza/go-dockerclient/testing/data/symlink

docker build -f Dockerfile .
echo ${RANDOM} > "$(date)"
docker build  -f Dockerfile .
```

This will output

```
Sending build context to Docker daemon  12.8 kB
Step 1 : FROM busybox
 ---> 8c2e06607696
Step 2 : COPY . ./
 ---> Using cache
 ---> 09b76d77bc36
Successfully built 09b76d77bc36
Sending build context to Docker daemon 13.82 kB
Step 1 : FROM busybox
 ---> 8c2e06607696
Step 2 : COPY . ./
 ---> Using cache
 ---> 09b76d77bc36
Successfully built 09b76d77bc36
```

Notice the offending lines

```
Step 2 : COPY . ./
 ---> Using cache
 ---> 09b76d77bc36
```

Version stuff

```
docker version; docker info
Client:
 Version:      1.9.0-rc2
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   60d36f7
 Built:        Fri Oct 23 00:20:59 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0-rc2
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   60d36f7
 Built:        Fri Oct 23 00:20:59 UTC 2015
 OS/Arch:      linux/amd64
Containers: 17
Images: 1249
Server Version: 1.9.0-rc2
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.1-040001-generic
Operating System: Ubuntu 14.10
CPUs: 4
Total Memory: 15.4 GiB
Name: inotmac
ID: FPSO:Z7SO:BZJ3:IXH4:DNKV:UPZQ:KLP2:IRXW:5CBY:PBDM:HAKO:UOC7
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 20
 System Time: 2015-10-22T19:45:15.96379998-07:00
 EventsListeners: 0
 Init SHA1: 
 Init Path: /home/darren/Downloads/docker-1.9.0-rc2
 Docker Root Dir: /var/lib/docker
Username: ibuildthecloud
Registry: https://index.docker.io/v1/
```

### PR DESCRIPTION
**Pull request by tonistiigi**
Fixes #17290

Fixes following issues:
- Cache checksums turning off while walking a broken symlink.
- Cache checksums were taken from symlinks while target files were actually copied.
- Copying a symlink pointing to a file to a directory used the basename of the target as a destination basename, instead of basename of the symlink.

cc @tiborvass 

Signed-off-by: Tonis Tiigi tonistiigi@gmail.com

### CODE REVIEW

File: builder/dockerfile/internals.go [hunk 1]
```diff
@@ -383,11 +383,9 @@ func (b *Builder) calcCopyInfo(cmdName, origPath string, allowLocalDecompression
 		hfi.SetHash("file:" + hfi.Hash())
 		return copyInfos, nil
 	}
-
 	// Must be a dir
-
 	var subfiles []string
-	b.context.Walk(origPath, func(path string, info builder.FileInfo, err error) error {
+	b.context.Walk(statPath, func(path string, info builder.FileInfo, err error) error {
```
Comment (ibuildthecloud) [inline builder/dockerfile/internals.go]: Part of the problem with the bug is that the error was never checked here.  Should we at least warn if an error is encountered, if not fail completely?

File: builder/tarsum.go [hunk 2]
```diff
@@ -43,26 +43,30 @@ func (c *tarSumContext) Open(path string) (io.ReadCloser, error) {
...
 	// we set sum to path by default for the case where GetFile returns nil.
 	// The usual case is if cleanpath is empty.
 	sum := path
-	if tsInfo := c.sums.GetFile(cleanpath); tsInfo != nil {
+	if tsInfo := c.sums.GetFile(rel); tsInfo != nil {
 		sum = tsInfo.Sum()
 	}
-	fi = &HashedFileInfo{fi, sum}
-	return fi, nil
+	fi := &HashedFileInfo{PathFileInfo{st, fullpath, filepath.Base(filepath.Clean(path))}, sum}
```
Comment (tiborvass) [inline builder/tarsum.go]: can't you use `cleanpath` directly here? `filepath.Base(cleanpath)`

File: builder/tarsum.go [hunk 3]
```diff
@@ -43,26 +43,30 @@ func (c *tarSumContext) Open(path string) (io.ReadCloser, error) {
...
+	}
+
+	rel, err := filepath.Rel(c.root, fullpath)
+	if err != nil {
+		return "", nil, convertPathError(err, cleanpath)
 	}
 
-	fi = PathFileInfo{st, fullpath}
 	// we set sum to path by default for the case where GetFile returns nil.
 	// The usual case is if cleanpath is empty.
```
Comment (tiborvass) [inline builder/tarsum.go]: you might want to rename `cleanpath` in the comment

File: builder/tarsum.go [hunk 4]
```diff
@@ -43,26 +43,30 @@ func (c *tarSumContext) Open(path string) (io.ReadCloser, error) {
...
 	sum := path
-	if tsInfo := c.sums.GetFile(cleanpath); tsInfo != nil {
+	if tsInfo := c.sums.GetFile(rel); tsInfo != nil {
```
Comment (tiborvass) [inline builder/tarsum.go]: I'm trying to understand why `rel` here makes sense :S

Comment (tonistiigi) [inline builder/tarsum.go]: We want to get the checksum of the target file, not the checksum of a symlink.

Comment (tiborvass) [inline builder/tarsum.go]: yes that's what I was thinking, so this means that the tarsum is resolving the symlinks, right?

Comment (tonistiigi) [inline builder/tarsum.go]: Yes, its important that tarsum checksums the same files that are actually copied. So if you actually copy the target file and not the symlink then you should use the target file for the cache as well.

Comment (tiborvass) [inline builder/tarsum.go]: Ok, can we just add a comment to make it more obvious?

File: builder/dockerfile/internals.go (hunk 1 above)
Comment (tiborvass) [inline builder/dockerfile/internals.go]: @tonistiigi I don't know why we're not checking for the error here. Do you see any reason not to return the error?

**Comment by tiborvass** [comment]
Apart from small nits, this is I think what we want for 1.9.1. Will approve once updated

**Comment by tiborvass** [comment]
LGTM

File: builder/dockerfile/internals.go (hunk 1 above)
Comment (tonistiigi) [inline builder/dockerfile/internals.go]: Error handling has been added. I had to switch to a filesystem backed walker because otherwise there could be errors on walking the context if files had been removed with `context.Remove()`.

**Comment by cpuguy83** [comment]
LGTM

**Comment by zanemcca** [comment]
The broken symlink still does not invalidate the cache if the modified file is in a subdirectory.

**Comment by tonistiigi** [comment]
@zanemcca do you have an example?

**Comment by zanemcca** [comment]
Here is a test [script](https://gist.github.com/zanemcca/aceb1172c61b71c455d2) that outlines the issue. The results I got are given as well.

**Comment by tonistiigi** [comment]
@zanemcca I couldn't reproduce with your script. Looking at your `docker version` you are still using `1.9.0` in server. This fix requires the server to be updated to `1.9.1-rc1`.

**Comment by zanemcca** [comment]
Thanks @tonistiigi I missed the server version.

**Comment by envygeeks** [comment]
This fix breaks being able to use full paths of files not symlinked, after updating to 1.9.1 we can no longer do what we have been doing since 1.7: `ADD /tmp/envygeeks-alpine-dev-20151122-8757-deyq13/envygeeks-alpine-dev-archive-20151122-8757-oky956.tar.gz` now we have to basename all the files because of this "fix"

**Comment by thaJeztah** [comment]
@envygeeks can you open a new issue for that, preferably with a simple example to reproduce?
