### PR TITLE
Fix processing of unset build-args during build

### LINKED ISSUE #29084: Build arg validation changes the API
**Description**

Previous to today's upgrade to 1.13.0-rc2, I was able to use --build-arg FOO, meaning "set the build arg FOO to the current value of the env var FOO in the environment".  (This behavior matches how environment variables are handled by -e.)  Now, that same behavior fails, and I have to do --build-arg FOO=$FOO.

**Steps to reproduce the issue:**
1.  Run `docker build -t foo --build-arg FOOVAR=$FOOVAR .` as a working case; no error.
2. Run `docker build -t foo --build-arg FOOVAR .` as error case.

**Describe the results you received:**
```
$ docker build -t foo --build-arg FOOVAR .
invalid argument "FOOVAR" for --build-arg: bad format for build-arg: FOOVAR
See 'docker build --help'.
```

**Describe the results you expected:**
Expected `--build-arg FOOVAR` to use the value of the environment variable FOOVAR, and proceed without error.

**Additional information you deem important (e.g. issue happens only occasionally):**
I believe this was introduced in https://github.com/docker/docker/commit/5426510bea290a8; prior to that commit, --build-arg was using ValidateEnv, and that commit introduced ValidateArg.

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.13.0-rc2
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   1f9b3ef
 Built:        Wed Nov 23 17:40:58 2016
 OS/Arch:      darwin/amd64

Server:
 Version:             1.13.0-rc2
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          1f9b3ef
 Built:               Wed Nov 23 17:40:58 2016
 OS/Arch:             linux/amd64
 Experimental:        true
```

**Output of `docker info`:**

```
Containers: 15
 Running: 0
 Paused: 0
 Stopped: 15
Images: 206
Server Version: 1.13.0-rc2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.8.10-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: OQWZ:7VAW:36RJ:57U5:PLXK:J6CD:RHOP:GWA3:WRL6:4ASG:V32S:UNVA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 28
 System Time: 2016-12-02T20:08:41.405406736Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### PR DESCRIPTION
**Pull request by duglin**
Fix processing of unset build-args during build
    
This reverts 26103.  26103 was trying to make it so that if someone did:
`docker build --build-arg FOO .`
and FOO wasn't set as an env var then it would pick-up FOO from the 
Dockerfile's ARG cmd.  However, it went too far and removed the ability
to specify a build arg w/o any value. Meaning it required the --build-arg
param to always be in the form "name=value", and not just "name".
    
This PR does the right fix - it allows just "name" and it'll grab the value
from the env vars if set. If "name" isn't set in the env then it still needs
to send "name" to the server so that a warning can be printed about an
unused --build-arg. And this is why buildArgs in the options is now a
*string instead of just a string - 'nil' == mentioned but no value.
    
Closes #29084
    
Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

File: api/server/router/build/build_routes.go [hunk 1]
```diff
@@ -84,14 +84,28 @@ func newImageBuildOptions(ctx context.Context, r *http.Request) (*types.ImageBui
 		options.Ulimits = buildUlimits
 	}
 
-	var buildArgs = map[string]string{}
+	var buildArgs = map[string]*string{}
 	buildArgsJSON := r.FormValue("buildargs")
+
+	// Note that there are two ways a --build-arg might appear in the
+	// jason of the query param:
```
Comment (vdemeester) [inline api/server/router/build/build_routes.go]: s/jason/json 👼

Comment (duglin) [inline api/server/router/build/build_routes.go]: fixed

**Comment by cpuguy83** [comment]
I'm a bit confused why this requires changing types around, and particularly a string pointer.
Shouldn't this just be an issue on the CLI?

**Comment by duglin** [comment]
@cpuguy83 I tried that but due to the way we send the data to the daemon (as a json object) we needed to support an arg having a value of "nil" - meaning it was mentioned on the cmd line but no value is associated with it.  The only way to keep the "nil" for an ARG is to have the json property be a *string. When its just a string we can't tell the different between "" meaning "just mentioned" vs "an empty string" value.

**Comment by cpuguy83** [comment]
@duglin But couldn't we not send the arg at all if there's nothing to send?
E.g., user does `--build-arg FOO`, `FOO` is not set as environment variable, don't send the the argument.

**Comment by duglin** [comment]
@cpuguy83 the problem with not sending it all is then the user won't see the warning about specifying a build-arg that's not used in the Dockerfile.

So, for example, `docker build --build-arg FOO=bar` will generate:
```
[Warning] One or more build-args [FOO] were not consumed
```
if there is no `ARG FOO` in the Dockerfile.

I can't remember when we added the warning, but the decision was made to tell the user that they messed up by including a build-arg that's never mentioned in the Dockerfile. This would avoid them thinking that they were providing info that actually was never going to be used.

In order to keep these semantics we need to include the data that they specified it on the cmd line to the daemon.  I decided that even if there is no env var **currently** specified, we should still tell the use they messed up because I would expect the same results no matter what my env looked like. In both cases I specified a build-arg that isn't actually defined in the Dockerfile.

Note - this doesn't change the API at all. I made sure of that. This is just changing how we deal with the data internally to capture the 3 possible states (mentioned/no-value, "", "value").

File: builder/dockerfile/dispatchers.go [hunk 2]
```diff
@@ -756,9 +756,12 @@ func arg(b *Builder, args []string, attributes map[string]bool, original string)
...
 	// If there is a default value associated with this arg then add it to the
 	// b.buildArgs if one is not already passed to the builder. The args passed
-	// to builder override the default value of 'arg'.
-	if _, ok := b.options.BuildArgs[name]; !ok && hasDefault {
-		b.options.BuildArgs[name] = value
+	// to builder override the default value of 'arg'. Note that a 'nil' for
+	// a value means that the user specified "--build-arg FOO" and "FOO" wasn't
+	// defined as an env var - and in that case we DO want to use the default
+	// value specified in the ARG cmd.
+	if val, ok := b.options.BuildArgs[name]; (!ok || val == nil) && hasDefault {
```
Comment (cpuguy83) [inline builder/dockerfile/dispatchers.go]: Naming here is a bit confusing `val` and `value`.

**Review by cpuguy83 — CHANGES_REQUESTED** [review]
I guess this makes sense due to the Dockerfile parsing needing to happen in the daemon :(

Would also have preferred `FOO=` to be a nil value rather than an empty string, but we're passed that I guess.

File: builder/dockerfile/dispatchers.go (hunk 2 above)
Comment (duglin) [inline builder/dockerfile/dispatchers.go]: yep - renamed "val" to "baValue" (BuildArgValue) and renamed "value" to be "newValue".
Hopefully that helps.

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by vdemeester** [comment]
@duglin oh 

```
15:36:34 # github.com/docker/docker/builder/dockerfile
15:36:34 ..\..\builder\dockerfile\dispatchers.go:748: undefined: newValue
15:36:34 ..\..\builder\dockerfile\dispatchers.go:764: undefined: newValue
```

**Comment by duglin** [comment]
@cpuguy83 yea, if we were sending the data as just strings (like we do with env vars) then we could have use:  "FOO" vs "FOO=" vs "FOO=value" to differentiate between the cases.

However, even with that, we'd still probably need to use *string in the code itself because "string" can be used to represent "no value".  Unlike the env vars, that are stored in memory as a []string, we store buildArgs in a map[string]string - well, now map[string]*string.  We could store them as []string too but that would make the look-up slower.  A long time ago I tried to switch env vars to use a map too but that's a different story for another day. :-)

**Comment by duglin** [comment]
@vdemeester oops - push coming in a sec....
thanks!

**Comment by duglin** [comment]
ok fixed -sorry for being lazy

**Comment by tonistiigi** [comment]
LGTM
