### PR TITLE
Keep backwards compatibility in kill api.

### LINKED ISSUE #15080: Error when attempting to kill a non-running container breaks backwards compatibility
As I understand it, #12371 made it an error to attempt to kill a non-running container. This makes sense, but it's very likely that lots of code out there relies on the current idempotency of the kill operation. The old behaviour should be preserved for older API versions.

### LINKED ISSUE #22371: Xenial (16.04) - Failed to start Docker Application Container Engine
Even though i read all other issues reported already concerning docker support for xenial it still doesn't work for me. I cannot successfully install it neither via the suggested method on the official documentation nor with the fast-install via `wget` and `sudo dpkg`.

Following i report some information i could find:
```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mit 2016-04-27 18:46:28 CEST; 7min ago
     Docs: https://docs.docker.com
  Process: 7537 ExecStart=/usr/bin/docker daemon -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 7537 (code=exited, status=1/FAILURE)

Apr 27 18:46:27 gbeschbacher-xps docker[7537]: time="2016-04-27T18:46:27.366619877+02:00" level=info msg="New containerd process, pid: 7552\n"
Apr 27 18:46:28 gbeschbacher-xps docker[7537]: time="2016-04-27T18:46:28.416215408+02:00" level=error msg="devmapper: Unable to delete device: devicemapper: Can't set task name /dev/mapper/docker-259:2-5395073-pool"
Apr 27 18:46:28 gbeschbacher-xps docker[7537]: time="2016-04-27T18:46:28.416290179+02:00" level=warning msg="devmapper: Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or
Apr 27 18:46:28 gbeschbacher-xps docker[7537]: time="2016-04-27T18:46:28.423610137+02:00" level=error msg="[graphdriver] prior storage driver \"devicemapper\" failed: devicemapper: Can't set task name /dev/mapper/docker-259:2-5395073-
Apr 27 18:46:28 gbeschbacher-xps docker[7537]: time="2016-04-27T18:46:28.423644646+02:00" level=fatal msg="Error starting daemon: error initializing graphdriver: devicemapper: Can't set task name /dev/mapper/docker-259:2-5395073-pool"
Apr 27 18:46:28 gbeschbacher-xps systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Apr 27 18:46:28 gbeschbacher-xps docker[7537]: time="2016-04-27T18:46:28+02:00" level=info msg="stopping containerd after receiving terminated"
Apr 27 18:46:28 gbeschbacher-xps systemd[1]: Failed to start Docker Application Container Engine.
Apr 27 18:46:28 gbeschbacher-xps systemd[1]: docker.service: Unit entered failed state.
Apr 27 18:46:28 gbeschbacher-xps systemd[1]: docker.service: Failed with result 'exit-code'.
```

```
Apr 27 18:46:26 gbeschbacher-xps sudo[7455]: pam_unix(sudo:session): session opened for user root by (uid=0)
Apr 27 18:46:27 gbeschbacher-xps systemd[1]: Reloading.
Apr 27 18:46:27 gbeschbacher-xps systemd[1]: apt-daily.timer: Adding 8h 56min 38.349166s random time.
Apr 27 18:46:27 gbeschbacher-xps systemd[1]: Started ACPI event daemon.
-- Subject: Unit acpid.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit acpid.service has finished starting up.
-- 
-- The start-up result is done.
Apr 27 18:46:27 gbeschbacher-xps systemd[1]: Started CUPS Scheduler.
-- Subject: Unit cups.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit cups.service has finished starting up.
-- 
-- The start-up result is done.
Apr 27 18:46:27 gbeschbacher-xps systemd[1]: Reloading.
Apr 27 18:46:27 gbeschbacher-xps systemd[1]: apt-daily.timer: Adding 5h 49min 22.325636s random time.
Apr 27 18:46:27 gbeschbacher-xps systemd[1]: Started ACPI event daemon.
-- Subject: Unit acpid.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit acpid.service has finished starting up.
-- 
-- The start-up result is done.
Apr 27 18:46:27 gbeschbacher-xps systemd[1]: Started CUPS Scheduler.
-- Subject: Unit cups.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit cups.service has finished starting up.
-- 
-- The start-up result is done.
Apr 27 18:46:27 gbeschbacher-xps systemd[1]: Starting Docker Application Container Engine...
-- Subject: Unit docker.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has begun starting up.
Apr 27 18:46:27 gbeschbacher-xps docker[7537]: time="2016-04-27T18:46:27.366619877+02:00" level=info msg="New containerd process, pid: 7552\n"
Apr 27 18:46:28 gbeschbacher-xps audit[7571]: AVC apparmor="STATUS" operation="profile_replace" name="docker-default" pid=7571 comm="apparmor_parser"
Apr 27 18:46:28 gbeschbacher-xps kernel: audit: type=1400 audit(1461775588.391:28): apparmor="STATUS" operation="profile_replace" name="docker-default" pid=7571 comm="apparmor_parser"
Apr 27 18:46:28 gbeschbacher-xps docker[7537]: time="2016-04-27T18:46:28.416215408+02:00" level=error msg="devmapper: Unable to delete device: devicemapper: Can't set task name /dev/mapper/docker-259:2-5395073-pool"
Apr 27 18:46:28 gbeschbacher-xps docker[7537]: time="2016-04-27T18:46:28.416290179+02:00" level=warning msg="devmapper: Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or
Apr 27 18:46:28 gbeschbacher-xps docker[7537]: time="2016-04-27T18:46:28.423610137+02:00" level=error msg="[graphdriver] prior storage driver \"devicemapper\" failed: devicemapper: Can't set task name /dev/mapper/docker-259:2-5395073-
Apr 27 18:46:28 gbeschbacher-xps docker[7537]: time="2016-04-27T18:46:28.423644646+02:00" level=fatal msg="Error starting daemon: error initializing graphdriver: devicemapper: Can't set task name /dev/mapper/docker-259:2-5395073-pool"
Apr 27 18:46:28 gbeschbacher-xps systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Apr 27 18:46:28 gbeschbacher-xps docker[7537]: time="2016-04-27T18:46:28+02:00" level=info msg="stopping containerd after receiving terminated"
Apr 27 18:46:28 gbeschbacher-xps systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has failed.
-- 
-- The result is failed.
Apr 27 18:46:28 gbeschbacher-xps systemd[1]: docker.service: Unit entered failed state.
Apr 27 18:46:28 gbeschbacher-xps systemd[1]: docker.service: Failed with result 'exit-code'.
Apr 27 18:46:30 gbeschbacher-xps sudo[7455]: pam_unix(sudo:session): session closed for user root
Apr 27 18:48:19 gbeschbacher-xps pkexec[7655]: pam_unix(polkit-1:session): session opened for user root by (uid=1000)
Apr 27 18:48:19 gbeschbacher-xps pkexec[7655]: pam_systemd(polkit-1:session): Cannot create session: Already running in a session
Apr 27 18:48:19 gbeschbacher-xps pkexec[7655]: gbeschbacher: Executing command [USER=root] [TTY=unknown] [CWD=/home/gbeschbacher] [COMMAND=/usr/lib/update-notifier/package-system-locked]
Apr 27 19:00:10 gbeschbacher-xps upowerd[1114]: (upowerd:1114): UPower-Linux-WARNING **: energy 57,532000 bigger than full 53,405200
Apr 27 19:00:10 gbeschbacher-xps kernel: ACPI Error: Cannot release Mutex [PATM], not acquired (20160108/exmutex-393)
Apr 27 19:00:10 gbeschbacher-xps kernel: ACPI Error: Method parse/execution failed [\_SB.PCI0.LPCB.ECDV._Q66] (Node ffff8802780e88c0), AE_AML_MUTEX_NOT_ACQUIRED (20160108/psparse-542)
```

```
~ ❯❯❯ uname -a
Linux xenial 4.6.0-999-generic #201603262200 SMP Sun Mar 27 02:02:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

I appreciate any information on this case and am willing to try out everything possible to get this to work :)
Thanks in advance,
Georg

### PR DESCRIPTION
**Pull request by calavera**
Return an error when the container is stopped only in api versions
equal or greater than 1.20 (docker 1.8).

- Fixes #15080
- relates to https://github.com/moby/moby/pull/12371

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Updated the issue number, I think this is the one you meant.

File: integration-cli/docker_cli_kill_test.go [hunk 1]
```diff
@@ -87,3 +89,12 @@ func (s *DockerSuite) TestKillWithInvalidSignal(c *check.C) {
 		c.Fatal("Container should be in running state after an invalid signal")
 	}
 }
+
+func (s *DockerSuite) TestKillofStoppedContainerOldAPI(c *check.C) {
```
Comment (cpuguy83) [inline integration-cli/docker_cli_kill_test.go]: instead of `OldApi`, can we specify either `119` or `Pre120`

**Comment by cpuguy83** [comment]
@thaJeztah issue number now refers to this PR

LGTM other than being specific about API versions in the test name.

**Comment by thaJeztah** [comment]
@cpuguy83 oh darn! the previous number was a non existing issue, but was 10000 off of the PR that introduced this. Probably had the wrong issue on my clipboard, I'll search the right one.

**Comment by thaJeztah** [comment]
third time's a charm, think I got the right one now. Thanks Brian

**Comment by calavera** [comment]
Test name fixed. Thank you guys!

**Comment by thaJeztah** [comment]
LGTM (jankies are running)

**Comment by icecrime** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Comment by icecrime** [comment]
Green janky: merging.

**Comment by calavera** [comment]
cherry picked into #15091
