### PR TITLE
When calling volume driver Mount, send opaque ID

### LINKED ISSUE #20939: Docker calls "unmount" operation even for containers that failed to start
ping @cpuguy83 

Sorry if this is a dupe! I peeked but might have missed this one.

```
docker volume create -d remote foo # Create
docker run -itd -v foo:/bar ubuntu # Mount
```

now, because of our 'remote' driver the second command twice fail to start because the volume cannot be shared. However, what will actually happen is that both Mount (which fails) and Unmount (!!!) will get reported to the volume plugin, which without specific container information in the api makes it impossible to track backwards where the mount came from. 

Since the volume never got mounted in the first place, it seems that it should not be required to be unmounted.

Relevant volplugin log with the activations and json payloads shown: https://gist.github.com/14730f2c7c1ab35a95c6

Here's a docker log. I'll run another in debug mode in a minute. This mess locks up my whole cluster as it stands right now (not your fault). https://gist.github.com/c8d1e5d10c9fd675b336

Thanks!

### PR DESCRIPTION
**Pull request by cpuguy83**
This generates an ID string for calls to Mount/Unmount, allowing drivers
to differentiate between two callers of `Mount` and `Unmount`.

Fixes #20939

### CODE REVIEW

**Comment by erikh** [comment]
yay

File: container/container_unix.go [hunk 1]
```diff
@@ -485,16 +486,18 @@ func (container *Container) CopyImagePathContent(v volume.Volume, destination st
 		return err
 	}
 
-	path, err := v.Mount()
+	id := stringid.GenerateNonCryptoID()
```
Comment (aaronlehmann) [inline container/container_unix.go]: Why a non-cryptographically strong ID? Presumably uniqueness is important.

Comment (cpuguy83) [inline container/container_unix.go]: We generally use non-crypto for these sort of IDs (even container ID's are non-crypto). These are going to be relatively short-lived and not likely to conflict (and not catastrophic if they happen to).

Comment (erikh) [inline container/container_unix.go]: It'd be pretty catastrophic for me (the bug that got us here in the 
first place) if there were duplicates. Can we just ensure no other 
containers have the ID and re-roll if needed?

-Erik

Comment (thaJeztah) [inline container/container_unix.go]: Not sure, but `non-cryptographically` doesn't say `non-unique`, only "possibly predictable", or am I mistaken here? i.e. a UUID may be predictable, thus "non-crypto", but still is unique

Comment (cpuguy83) [inline container/container_unix.go]: In addition, we could never guarantee this across hosts anyway.

Comment (erikh) [inline container/container_unix.go]: yeah I didn't mean that, sorry if I was implying otherwise. just ensure that no two existing mounts have the same ID and I'll be fine at least, I think.

**Comment by erikh** [comment]
Is this going to be available in 1.11?

**Comment by thaJeztah** [comment]
ping @cpuguy83 looks like this needs a rebase

**Comment by cpuguy83** [comment]
I'll deal with rebase if we move this to code-review.

**Comment by erikh** [comment]
@cpuguy83 please tell me this is going to be in 1.11...

**Comment by cpuguy83** [comment]
@erikh Nope.

**Comment by tiborvass** [comment]
@cpuguy83 REBASE!! :P

**Comment by cpuguy83** [comment]
@tiborvass DONE!!

**Comment by vdemeester** [comment]
LGTM 🐯

**Comment by thaJeztah** [comment]
ping @cpuguy83 needs a rebase again :cry:

ping @tiborvass PTAL

**Comment by SvenDowideit** [comment]
yay!, one more part i needed :) and docs LGTM

**Comment by cpuguy83** [comment]
rebased

**Comment by estesp** [comment]
LGTM

**Comment by vdemeester** [comment]
docs LGTM 🐸

**Comment by e4jet** [comment]
I'm playing with docker 1.12.0-rc5.  I see the unique id in the /VolumeDriver.Mount request, but always see an empty string in the /VolumeDriver.Unmount request.  Is this expected?  

I was hoping to verify the ID during the unmount request.  Perhaps I'm overthinking this.

Below is an example where 2 containers request the same volume (called swarm5), then exit.  Note that the ID is sent in the Mount request, but not the Unmount request.

Thanks!

/VolumeDriver.Mount request={"Name":"swarm5","ID":"dfce4a5f374a573a6f36f2bd78907e2b90191aae54b70957e46a79629ba7af02"} response={"Mountpoint":"/data/swarm5","Err":null}

/VolumeDriver.Mount request={"Name":"swarm5","ID":"ddce68c10c1afe245af1880df68076074c578d2bdb2a22731263a65bc2a97c38"} response={"Mountpoint":"/data/swarm5","Err":null}

/VolumeDriver.Unmount request={"Name":"swarm5","ID":""} response={"Err":null}
/VolumeDriver.Unmount request={"Name":"swarm5","ID":""} response={"Err":null}

**Comment by erikh** [comment]
that is definitely going to make this ineffective for my needs.

**Comment by thaJeztah** [comment]
@e4jet @erikh if it's a bug, please open a new issue; I can add it to the 1.12.1 milestone for consideration

**Comment by erikh** [comment]
I worked around it by tracking state outside docker in both copy and nocopy
modes, so I'm good. File it if you feel it needs to be fixed.

**Comment by e4jet** [comment]
@thaJeztah & @erikh thanks for the quick response.  I can't think of a compelling reason for the engine to have to track this, so I'll take the same approach as @erikh.  The only enhancement that I can think of would be to pass the container's uuid instead of creating an opaque one.  This would allow some correlation for reporting and debugging.  Cheers

**Comment by erikh** [comment]
Unfortunately even though I originally asked for this feature, I agree;
without mount+container data I'm still querying docker no matter what to
assert runtime state.

**Comment by cpuguy83** [comment]
@erikh @e4jet Please open an issue to discuss.
I do not see why you would need to query docker (outside of the potential bug in not sending the ID on unmount).

**Comment by erikh** [comment]
the state tracking is independent, I just have a global mutex protecting a
counter for each volume. I increment it when you send me a mount and
decrement it when you send me an unmount. this is the only way to safely
manage both copy and nocopy mode.

as for querying docker, it'd be *great* if I could send a signal or when
docker auto-discovers the plugin, sends it a payload (maybe on activate?)
of all the volumes it currently knows about. I have to query docker for
this now when the plugin itself is restarted. This leads to an interesting
race where my poller (which must succeed before the program can continue
safely) races a restart of docker because docker tries to query volplugin,
but volplugin is busy waiting on docker. I think these operations should be
decoupled somehow as well.

Sorry for the braindump but I have extremely little time these days and am
trying to give you the feedback you need in the most efficient way possible.

File: docs/extend/plugins_volume.md [hunk 2]
```diff
@@ -124,6 +125,8 @@ name. This is called once per container start. If the same volume_name is reques
 more than once, the plugin may need to keep track of each new mount request and provision
 at the first mount request and deprovision at the last corresponding unmount request.
 
+`ID` is a unqiue ID for the caller that is requesting the mount.
```
Comment (wallrj) [inline docs/extend/plugins_volume.md]: typo "unqiue"

File: docs/extend/plugins_volume.md [hunk 3]
```diff
@@ -162,14 +165,17 @@ available, and/or a string error if an error occurred.
...
+    "Name": "volume_name",
+    "ID": "b87d7442095999a92b65b3d9691e697b61713829cc0ffd1bb72e4ccd51aa4d6c"
 }
 ```
 
 Indication that Docker no longer is using the named volume. This is called once
 per container stop.  Plugin may deduce that it is safe to deprovision it at
 this point.
 
+`ID` is a unqiue ID for the caller that is requesting the mount.
```
Comment (wallrj) [inline docs/extend/plugins_volume.md]: typo "unqiue"
