### PR TITLE
De-flake TestSwarmClusterRotateUnlockKey... again... maybe?

### LINKED ISSUE #38885: Flaky test: DockerSwarmSuite.TestSwarmClusterRotateUnlockKey
Let's create a separate issue for this one (also tracked in https://github.com/moby/moby/issues/33041 and https://github.com/moby/moby/issues/37306

Seen failing in https://jenkins.dockerproject.org/job/Docker-PRs-experimental/44501/console (and many other times)

```
03:25:28 FAIL: docker_cli_swarm_test.go:1316: DockerSwarmSuite.TestSwarmClusterRotateUnlockKey
03:25:28
03:25:28 Creating a new daemon
03:25:28 [dcd909916369d] waiting for daemon to start
03:25:28 [dcd909916369d] daemon started
03:25:28
03:25:28 Creating a new daemon
03:25:28 [de6869a9c7827] waiting for daemon to start
03:25:28 [de6869a9c7827] daemon started
03:25:28
03:25:28 Creating a new daemon
03:25:28 [d899b634e4c28] waiting for daemon to start
03:25:28 [d899b634e4c28] daemon started
03:25:28
03:25:28 [de6869a9c7827] exiting daemon
03:25:28 [de6869a9c7827] waiting for daemon to start
03:25:28 [de6869a9c7827] daemon started
03:25:28
03:25:28 [d899b634e4c28] exiting daemon
03:25:28 [d899b634e4c28] waiting for daemon to start
03:25:28 [d899b634e4c28] daemon started
03:25:28
03:25:28 [de6869a9c7827] exiting daemon
03:25:28 [de6869a9c7827] waiting for daemon to start
03:25:28 [de6869a9c7827] daemon started
03:25:28
03:25:28 [d899b634e4c28] exiting daemon
03:25:28 [d899b634e4c28] waiting for daemon to start
03:25:28 [d899b634e4c28] daemon started
03:25:28
03:25:28 docker_cli_swarm_test.go:1386:
03:25:28     c.Assert(err, checker.IsNil, check.Commentf("%s", outs))
03:25:28 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc0008f00a0), Stderr:[]uint8(nil)} ("exit status 1")
03:25:28 ... Error response from daemon: rpc error: code = Unknown desc = The swarm does not have a leader. It's possible that too few managers are online. Make sure more than half of the managers are online.
03:25:28
03:25:28
03:25:28 [dcd909916369d] exiting daemon
03:25:28 [de6869a9c7827] exiting daemon
03:25:28 [d899b634e4c28] exiting daemon
03:25:32
```

This is the test:

https://github.com/moby/moby/blob/0e54f5e3a9103131f71329d31068a7393757bf36/integration-cli/docker_cli_swarm_test.go#L1313-L1392

`d1` = `dcd909916369d`
`d2` = `de6869a9c7827`
`d3` = `d899b634e4c28`

```
03:25:28 FAIL: docker_cli_swarm_test.go:1316: DockerSwarmSuite.TestSwarmClusterRotateUnlockKey
03:25:28
```

Create 3 daemons;

Daemon 1 (`d1` = `dcd909916369d`)

https://github.com/moby/moby/blob/0e54f5e3a9103131f71329d31068a7393757bf36/integration-cli/docker_cli_swarm_test.go#L1324

```
03:25:28 Creating a new daemon
03:25:28 [dcd909916369d] waiting for daemon to start
03:25:28 [dcd909916369d] daemon started
03:25:28
```

Daemon 2 (`d2` = `de6869a9c7827`)

https://github.com/moby/moby/blob/0e54f5e3a9103131f71329d31068a7393757bf36/integration-cli/docker_cli_swarm_test.go#L1325

```
03:25:28 Creating a new daemon
03:25:28 [de6869a9c7827] waiting for daemon to start
03:25:28 [de6869a9c7827] daemon started
03:25:28
```

Daemon 3 (`d3` = `d899b634e4c28`)

https://github.com/moby/moby/blob/0e54f5e3a9103131f71329d31068a7393757bf36/integration-cli/docker_cli_swarm_test.go#L1326

```
03:25:28 Creating a new daemon
03:25:28 [d899b634e4c28] waiting for daemon to start
03:25:28 [d899b634e4c28] daemon started
03:25:28
```

In a loop (3 times);

Iteration 1:

Restart daemon `d2` https://github.com/moby/moby/blob/0e54f5e3a9103131f71329d31068a7393757bf36/integration-cli/docker_cli_swarm_test.go#L1341

```
03:25:28 [de6869a9c7827] exiting daemon
03:25:28 [de6869a9c7827] waiting for daemon to start
03:25:28 [de6869a9c7827] daemon started
03:25:28
```

Restart daemon `d3` https://github.com/moby/moby/blob/0e54f5e3a9103131f71329d31068a7393757bf36/integration-cli/docker_cli_swarm_test.go#L1342

```
03:25:28 [d899b634e4c28] exiting daemon
03:25:28 [d899b634e4c28] waiting for daemon to start
03:25:28 [d899b634e4c28] daemon started
03:25:28
```

Iteration 2:

Restart daemon `d2` https://github.com/moby/moby/blob/0e54f5e3a9103131f71329d31068a7393757bf36/integration-cli/docker_cli_swarm_test.go#L1341

```
03:25:28 [de6869a9c7827] exiting daemon
03:25:28 [de6869a9c7827] waiting for daemon to start
03:25:28 [de6869a9c7827] daemon started
03:25:28
```

Restart daemon `d3` https://github.com/moby/moby/blob/0e54f5e3a9103131f71329d31068a7393757bf36/integration-cli/docker_cli_swarm_test.go#L1342

```
03:25:28 [d899b634e4c28] exiting daemon
03:25:28 [d899b634e4c28] waiting for daemon to start
03:25:28 [d899b634e4c28] daemon started
03:25:28
```

Failing here; https://github.com/moby/moby/blob/0e54f5e3a9103131f71329d31068a7393757bf36/integration-cli/docker_cli_swarm_test.go#L1385-L1386

```
03:25:28 docker_cli_swarm_test.go:1386:
03:25:28     c.Assert(err, checker.IsNil, check.Commentf("%s", outs))
03:25:28 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc0008f00a0), Stderr:[]uint8(nil)} ("exit status 1")
03:25:28 ... Error response from daemon: rpc error: code = Unknown desc = The swarm does not have a leader. It's possible that too few managers are online. Make sure more than half of the managers are online.
03:25:28
03:25:28
```

Teardown:

```
03:25:28 [dcd909916369d] exiting daemon
03:25:28 [de6869a9c7827] exiting daemon
03:25:28 [d899b634e4c28] exiting daemon
03:25:32
```

Logs:

- [test.log.txt](https://github.com/moby/moby/files/2974004/test.log.txt)
- [daemon d1 - dcd909916369d - docker.log.txt](https://github.com/moby/moby/files/2974007/daemon.d1.-.dcd909916369d.-.docker.log.txt)
- [daemon d2 - de6869a9c7827 - docker.log.txt](https://github.com/moby/moby/files/2974008/daemon.d2.-.de6869a9c7827.-.docker.log.txt)
- [daemon d3 - d899b634e4c28 - docker.log.txt](https://github.com/moby/moby/files/2974009/daemon.d3.-.d899b634e4c28.-.docker.log.txt)

### PR DESCRIPTION
**Pull request by cpuguy83**
- (hopefully) fixes https://github.com/moby/moby/issues/38885
- related: https://github.com/moby/moby/pull/39885

This hopefully makes the test less flakey (or removes any flake that would be caused by the test itself).

1. Adds tail of cluster daemon logs when there is a test failure so we can more easily see what may be happening
2. Scans the daemon logs to check if the key is rotated before restarting the daemon. This is a little hacky but a little better than assuming it is done after a hard-coded 3 seconds.
3. Cleans up the `node ls` check such that it uses a poll function

### CODE REVIEW

**Comment by thaJeztah** [comment]
@dperny ptal

File: integration-cli/docker_cli_swarm_test.go [hunk 1]
```diff
@@ -27,6 +27,7 @@ import (
 	remoteipam "github.com/docker/docker/libnetwork/ipams/remote/api"
 	"github.com/docker/docker/pkg/plugins"
 	"github.com/docker/docker/testutil"
+	tudaemon "github.com/docker/docker/testutil/daemon"
```
Comment (thaJeztah) [inline integration-cli/docker_cli_swarm_test.go:30]: Could you use `testdaemon` as alias for this one? It looks like that's the alias we converged on (I should probably add a check for that in golang-ci)

```bash
git grep ' "github.com/docker/docker/testutil/daemon"'
integration-cli/check_test.go:  testdaemon "github.com/docker/docker/testutil/daemon"
integration-cli/docker_api_swarm_service_test.go:       testdaemon "github.com/docker/docker/testutil/daemon"
integration-cli/docker_api_swarm_test.go:       testdaemon "github.com/docker/docker/testutil/daemon"
integration-cli/docker_cli_daemon_test.go:      testdaemon "github.com/docker/docker/testutil/daemon"
integration-cli/docker_cli_external_volume_driver_test.go:      testdaemon "github.com/docker/docker/testutil/daemon"
integration-cli/docker_cli_logs_test.go:        testdaemon "github.com/docker/docker/testutil/daemon"
integration-cli/docker_cli_network_unix_test.go:        testdaemon "github.com/docker/docker/testutil/daemon"
integration-cli/docker_cli_run_test.go: testdaemon "github.com/docker/docker/testutil/daemon"
integration-cli/docker_hub_pull_suite_test.go:  testdaemon "github.com/docker/docker/testutil/daemon"
```

**Review by corhere — APPROVED** [review]

**Review by thaJeztah — APPROVED** [review]
LGTM
