### PR TITLE
Run btrfs rescan only if userDiskQuota is enabled

### LINKED ISSUE #29810: Run btrfs rescan only, if userDiskQuota is enabled
**Description**

**Steps to reproduce the issue:**
1. Setup a lxc (or lxd) environment with btrfs as backend
2. Create a unprivileged lxc container 
3. Install docker, run a Container and stop it 

**Describe the results you received:**

```
docker run --rm java:8-jdk java -version
Unable to find image 'java:8-jdk' locally
8-jdk: Pulling from library/java
75a822cd7888: Pull complete
57de64c72267: Pull complete
4306be1e8943: Pull complete
1e6944bfb718: Pull complete
3521f2f45ed2: Pull complete
9c2f0d9b5f90: Pull complete
8cedcf6d2527: Pull complete
31f99da7583d: Pull complete
Digest: sha256:6bfae6cf8902a28d3f0209f5cdbb269032762a94835d331811df33498970aa7e
Status: Downloaded newer image for java:8-jdk
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2~bpo8+1-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)
Error response from daemon: Driver btrfs failed to remove root filesystem 564cc6dfd81f417a075ab8d3d12fc60d5c83f648b9f3006393e5b7a75909a779: Failed to rescan btrfs quota for &{}: operation not permitted
```

**Describe the results you expected:**

btrfs subvolume and container are removed.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker info`:**

```
root@gitlab:~# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.1
Storage Driver: btrfs
 Build Version: Btrfs v4.4
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-57-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 2.5 GiB
Name: gitlab
ID: HLAE:VWC6:XEYO:TGPC:JPHJ:MCV7:PNFY:W4EN:4XZQ:WHVA:QU7G:M33M
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://proxy:3128
Https Proxy: http://proxy:3128
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
LXC Container

Issue appears since this commit: https://github.com/docker/docker/commit/401c8d17674379d9b727d25df2d560a2dfe07f27

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to address the issue raised in #29810 where btrfs subvolume removal failed when docker
is in an unprivileged lxc container. The failure was caused by `Failed to rescan btrfs quota` with `operation not permitted`.

However, if disk quota is not enabled, there is no need to run a btrfs rescan at the first place.

This fix checks for `quotaEnabled` and only run btrfs rescan if `quotaEnabled` is true.

This fix fixes #29810.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

/cc @zhuguihua

### CODE REVIEW

**Comment by Keno** [comment]
👍  I did the same patch locally earlier today and works for me.

**Comment by zhuguihua** [comment]
Thanks for your fix. Good to me.

File: daemon/graphdriver/btrfs/btrfs.go [hunk 1]
```diff
@@ -494,8 +494,10 @@ func (d *Driver) Remove(id string) error {
 	if err := os.RemoveAll(dir); err != nil && !os.IsNotExist(err) {
 		return err
 	}
-	if err := subvolRescanQuota(d.home); err != nil {
-		return err
+	if quotaEnabled {
```
Comment (thaJeztah) [inline daemon/graphdriver/btrfs/btrfs.go]: I was looking at the code, and a bit in doubt. The `quotaEnabled` boolean
is set _either_ if [`--storage-opt size=btrfs.min_space`](https://github.com/docker/docker/blob/v1.12.5/docs/reference/commandline/dockerd.md#btrfs-options) is set globally (on the daemon), or if a `size` is passed when creating a container (see [set storage driver options per container](https://github.com/docker/docker/blob/v1.12.5/docs/reference/commandline/run.md#set-storage-driver-options-per-container))

I'm not too familiar with this part of the code; is the [`Create()` method](https://github.com/docker/docker/blob/v1.12.5/daemon/graphdriver/btrfs/btrfs.go#L384) also called when _starting_ an existing container, or only the first time its filesystem is created?

Otherwise, this may not work, because the `quotaEnabled` variable is only set here; https://github.com/docker/docker/blob/v1.12.5/daemon/graphdriver/btrfs/btrfs.go#L461-L466
(in situations where `btrfs.min_space` is not set on the daemon)

So, maybe this is the right change, but I'm just writing down my thoughts, in case it's useful.

ping @cpuguy83 you probably know

Comment (tonistiigi) [inline daemon/graphdriver/btrfs/btrfs.go]: Create is not called on container startup. `Cleanup` has a similar check.

Comment (cpuguy83) [inline daemon/graphdriver/btrfs/btrfs.go]: Yes, this will be a problem on restore, for sure.
We need a better way to determine if quota is enabled.

File: daemon/graphdriver/btrfs/btrfs.go [hunk 2]
```diff
@@ -35,11 +35,6 @@ func init() {
 	graphdriver.Register("btrfs", Init)
 }
 
-var (
-	quotaEnabled  = false
-	userDiskQuota = false
-)
-
```
Comment (yongtang) [inline daemon/graphdriver/btrfs/btrfs.go]: Think the two global variables could be avoided. the `quotaEnabled` could be wrapped into `driver *`, and `userDiskQuota` is only a temporary variable.

File: daemon/graphdriver/btrfs/btrfs.go [hunk 3]
```diff
@@ -150,10 +146,8 @@ func (d *Driver) GetMetadata(id string) (map[string]string, error) {
 
 // Cleanup unmounts the home directory.
 func (d *Driver) Cleanup() error {
-	if quotaEnabled {
```
Comment (yongtang) [inline daemon/graphdriver/btrfs/btrfs.go]: Move `quotaEnabled` inside the `d *Driver` to hide the logic of quotaEnabled checking.

File: daemon/graphdriver/btrfs/btrfs.go [hunk 4]
```diff
@@ -294,8 +288,17 @@ func subvolDelete(dirpath, name string) error {
...
-func subvolEnableQuota(path string) error {
-	dir, err := openDir(path)
+func (d *Driver) subvolEnableQuota() error {
+	if d.quotaEnabled {
+		return nil
+	}
+	// In case quotaEnabled is not set, check qgroup and update quotaEnabled as needed
+	if _, err := subvolLookupQgroup(d.home); err == nil {
+		d.quotaEnabled = true
+		return nil
```
Comment (yongtang) [inline daemon/graphdriver/btrfs/btrfs.go]: Perform a qgroup lookup and sync `quotaEnabled` as needed.

**Comment by LK4D4** [comment]
ping @cpuguy83 @tonistiigi

**Comment by tonistiigi** [comment]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM
