### PR TITLE
Fix lxc-start in lxc>1.1.0 where containers start daemonized by default

### LINKED ISSUE #10525: "Process could not be started" during docker build
I can see following error in Docker logs that appears every time I execute 'docker build -t IMAGE_NAME .':

UPDATE: Same error when doing 'docker run'...

```
Feb 03 09:44:22 naboo docker[1649]: time="2015-02-03T09:44:22+01:00" level="info" msg="POST /v1.16/build?rm=1&t=openshift%2Fsti-image-builder"
Feb 03 09:44:22 naboo docker[1649]: time="2015-02-03T09:44:22+01:00" level="info" msg="+job build()"
Feb 03 09:44:23 naboo docker[1649]: time="2015-02-03T09:44:23+01:00" level="info" msg="+job allocate_interface(05f15f34998f4d01973bf4097bc1b6a6479294d75daac7ef8737a02d4ae086b5)"
Feb 03 09:44:23 naboo docker[1649]: time="2015-02-03T09:44:23+01:00" level="info" msg="-job allocate_interface(05f15f34998f4d01973bf4097bc1b6a6479294d75daac7ef8737a02d4ae086b5) = OK (0)"
Feb 03 09:44:23 naboo docker[1649]: time="2015-02-03T09:44:23+01:00" level="info" msg="+job log(start, 05f15f34998f4d01973bf4097bc1b6a6479294d75daac7ef8737a02d4ae086b5, centos:centos7)"
Feb 03 09:44:23 naboo docker[1649]: time="2015-02-03T09:44:23+01:00" level="info" msg="-job log(start, 05f15f34998f4d01973bf4097bc1b6a6479294d75daac7ef8737a02d4ae086b5, centos:centos7) = OK (0)"
Feb 03 09:44:28 naboo docker[1649]: time="2015-02-03T09:44:28+01:00" level="info" msg="+job release_interface(05f15f34998f4d01973bf4097bc1b6a6479294d75daac7ef8737a02d4ae086b5)"
Feb 03 09:44:28 naboo docker[1649]: time="2015-02-03T09:44:28+01:00" level="info" msg="-job release_interface(05f15f34998f4d01973bf4097bc1b6a6479294d75daac7ef8737a02d4ae086b5) = OK (0)"
Feb 03 09:44:28 naboo docker[1649]: time="2015-02-03T09:44:28+01:00" level="info" msg="+job release_interface(05f15f34998f4d01973bf4097bc1b6a6479294d75daac7ef8737a02d4ae086b5)"
Feb 03 09:44:28 naboo docker[1649]: time="2015-02-03T09:44:28+01:00" level="info" msg="-job release_interface(05f15f34998f4d01973bf4097bc1b6a6479294d75daac7ef8737a02d4ae086b5) = OK (0)"
Feb 03 09:44:28 naboo docker[1649]: time="2015-02-03T09:44:28+01:00" level="error" msg="Warning: error unmounting device 05f15f34998f4d01973bf4097bc1b6a6479294d75daac7ef8737a02d4ae086b5: UnmountDevice: device not-mounted id 05f15f34998f4d01973bf4097bc1b6a6479294d75daac7ef8737a02d4ae086b5\n"
Feb 03 09:44:28 naboo docker[1649]: Process could not be started
Feb 03 09:44:28 naboo docker[1649]: time="2015-02-03T09:44:28+01:00" level="info" msg="-job build() = ERR (1)"
```

The `docker info` output:

```
Containers: 3
Images: 71
Storage Driver: devicemapper
 Pool Name: docker-8:3-17071968-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 4.027 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 4.895 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.92 (2014-11-28)
Execution Driver: lxc-1.1.0
Kernel Version: 3.18.5-1-ARCH
Operating System: Arch Linux
CPUs: 4
Total Memory: 7.532 GiB
Name: naboo
ID: NZI2:LBG7:K7IA:7U4J:2P3I:Q5XS:IJX6:QFHE:Z6OQ:JFAM:BVFI:HLAF
Username: mfojtik
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support
```

### PR DESCRIPTION
**Pull request by mfojtik**
Fixes: #10525

### CODE REVIEW

**Comment by mfojtik** [comment]
@vbatts fyi

**Comment by dqminh** [comment]
`-F` option in `lxc-start` is only added in lxc 1.0.6 though, so I think this change may not work for system with older lxc.

**Comment by mfojtik** [comment]
@dqminh added if to protect the lxc version, since they changed this to default behavior from 1.1, I think it is safe to append that option this way.

**Comment by tianon** [comment]
https://jenkins.dockerproject.com/job/Docker-PRs/216/label=ubuntu-prs2/console
```
---> Making bundle: validate-dco (in bundles/1.4.1-dev/validate-dco)
These commits do not have a proper 'Signed-off-by:' marker:
 - 715db3677d8570d7ef3393107eb4ad4ee4549e0f

Please amend each commit to include a properly formatted DCO marker.

Visit the following URL for information about the Docker DCO:
 https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
```

**Comment by vbatts** [comment]
@tianon where was that?... the build logs I saw looked like a failure to
run `docker rmi` ... :sad:

**Comment by tianon** [comment]
@vbatts yeah...  the Janky UI isn't exactly friendly.  I found that by clicking "Details" here on the PR (https://jenkins.dockerproject.com/job/Docker-PRs/216/), then "default" at the bottom of that page (https://jenkins.dockerproject.com/job/Docker-PRs/216/label=ubuntu-prs2/), then "Console Output" on the sidebar of that page (https://jenkins.dockerproject.com/job/Docker-PRs/216/label=ubuntu-prs2/console).

**Comment by vbatts** [comment]
:-|

**Comment by mfojtik** [comment]
@tianon @vbatts sorry for that, updated with --signoff

**Comment by crosbymichael** [comment]
ping @ashahab-altiscale   can you review this?

File: daemon/execdriver/lxc/driver.go [hunk 1]
```diff
@@ -87,6 +87,12 @@ func (d *driver) Run(c *execdriver.Command, pipes *execdriver.Pipes, startCallba
 		"-n", c.ID,
 		"-f", configPath,
 	}
+
+	// From lxc>=1.1 the default behavior is to daemonize containers after start
+	if d.version() >= "1.1" {
```
Comment (ashahab-altiscale) [inline daemon/execdriver/lxc/driver.go]: How certain are we about the correctness of d.version()?

Comment (tianon) [inline daemon/execdriver/lxc/driver.go]: Also, isn't a string comparison here kind of dangerous since we really need
a numeric comparison?

Comment (dqminh) [inline daemon/execdriver/lxc/driver.go]: i'm also not fond of comparing version. However the check here will *probably* always work because the version we are comparing to is "1.1.x". But may be a check to see if `foreground` option is available via `lxc-start --help` is better ?

Comment (mfojtik) [inline daemon/execdriver/lxc/driver.go]: @tianon @dqminh I think the string comparison should just work fine: see https://play.golang.org/p/qIaNw2JRz1

Comment (vbatts) [inline daemon/execdriver/lxc/driver.go]: both approaches are similar enough. the version comparison though, may eventually have additional cases where greater X has the option, but less than Y. Though I don't care to add additional execs, if we did check for the presence of the flag being used, then we really don't care _which_ version is being used ...

```
cmd := exec.Command("lxc-start", "--help")
  out, err := cmd.CombinedOutput()
  if err != nil {
    log.Fatal(err)
  }
  flag := []byte("--foreground")
  if bytes.Contains(out, flag) {
//...
```

Comment (ashahab-altiscale) [inline daemon/execdriver/lxc/driver.go]: I actually think the string comparison is better here as we'd rather avoid another exec call.

Comment (jfrazelle) [inline daemon/execdriver/lxc/driver.go]: wow I have no idea how that works but it does can we add something like https://play.golang.org/p/38fyne_F0y as a unit test

Comment (tianon) [inline daemon/execdriver/lxc/driver.go]: More like https://play.golang.org/p/Vjzpva-Hqj
```
false, 1.1.1 >= 1.2
true, 1.2.3 >= 1.2
false, 1.12.0 >= 1.2
```

Comment (vbatts) [inline daemon/execdriver/lxc/driver.go]: Wat...

Comment (vbatts) [inline daemon/execdriver/lxc/driver.go]: If `"1.12.0" >= "1.2"` returns `false` then we can't rely on that as a check

Comment (icecrime) [inline daemon/execdriver/lxc/driver.go]: We have a [`pkg/version` package](https://github.com/docker/docker/blob/master/pkg/version/version.go#L11) that I believe could do the job.

**Comment by icecrime** [comment]
Hello @mfojtik! There has been many comments here: would you please be available to follow through, or do we want us to take it over?

**Comment by mfojtik** [comment]
@icecrime sorry the delay, I'm going to update this today

**Comment by crosbymichael** [comment]
LGTM

**Comment by crosbymichael** [comment]
ping @jfrazelle

**Comment by jfrazelle** [comment]
LGTM
