### PR TITLE
errdefs: FromStatusCode() don't log "FIXME" debug message

### LINKED ISSUE #38877: FIXME: Got an API for which error does not match any expected type!!!
docker rm -f $(docker ps -af)

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
kill containers failed

**Describe the results you expected:**
kill containers success

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 31
 Running: 31
 Paused: 0
 Stopped: 0
Images: 31
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-134-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.54GiB
Name: supos103
ID: J7FJ:IGD3:GT2L:IUSY:5O4V:HBH4:ZDWH:62YZ:UM6I:4EDU:WWE3:C4LR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 registry.supos.ai
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
docker daemon log:
```
Mar 14 09:15:21 supos103 dockerd[1129]: time="2019-03-14T09:15:21.981733328+08:00" level=error msg="Handler for POST /v1.37/containers/4de08b91e26a/stop returned error: cannot stop container: 4de08b91e26a: Cannot kill container 4de08b91e26ada75f377df2a45b46a598bd0c652c759cde90eb918c8ac614c9f: connection error: desc = \"transport: dial unix:///var/run/docker/containerd/docker-containerd.sock: timeout\": unknown"
Mar 14 09:15:21 supos103 dockerd[1129]: time="2019-03-14T09:15:21.981858615+08:00" level=debug msg="FIXME: Got an API for which error does not match any expected type!!!: unknown\ngithub.com/docker/docker/vendor/github.com/containerd/containerd/errdefs.init\n\t/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/errdefs/errors.go:23\ngithub.com/docker/docker/vendor/github.com/containerd/containerd/content.init\n\t<autogenerated>:1\ngithub.com/docker/docker/vendor/github.com/containerd/containerd.init\n\t<autogenerated>:1\ngithub.com/docker/docker/libcontainerd.init\n\t<autogenerated>:1\ngithub.com/docker/docker/daemon.init\n\t<autogenerated>:1\ngithub.com/docker/docker/daemon/cluster/executor/container.init\n\t<autogenerated>:1\ngithub.com/docker/docker/daemon/cluster.init\n\t<autogenerated>:1\ngithub.com/docker/docker/api/server/router/network.init\n\t<autogenerated>:1\nmain.init\n\t<autogenerated>:1\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:183\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:2337" error_type="*errors.fundamental" module=api
Mar 14 09:15:21 supos103 dockerd[1129]: time="2019-03-14T09:15:21.985533098+08:00" level=debug msg="FIXME: Got an API for which error does not match any expected type!!!: unknown\ngithub.com/docker/docker/vendor/github.com/containerd/containerd/errdefs.init\n\t/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/errdefs/errors.go:23\ngithub.com/docker/docker/vendor/github.com/containerd/containerd/content.init\n\t<autogenerated>:1\ngithub.com/docker/docker/vendor/github.com/containerd/containerd.init\n\t<autogenerated>:1\ngithub.com/docker/docker/libcontainerd.init\n\t<autogenerated>:1\ngithub.com/docker/docker/daemon.init\n\t<autogenerated>:1\ngithub.com/docker/docker/daemon/cluster/executor/container.init\n\t<autogenerated>:1\ngithub.com/docker/docker/daemon/cluster.init\n\t<autogenerated>:1\ngithub.com/docker/docker/api/server/router/network.init\n\t<autogenerated>:1\nmain.init\n\t<autogenerated>:1\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:183\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:2337" error_type="*errors.fundamental" module=api
```

### PR DESCRIPTION
**Pull request by thaJeztah**
- fixes https://github.com/moby/moby/issues/38877#issuecomment-1359329062
- relates to https://github.com/moby/moby/pull/38689

This utility is used by the client, which cannot do anything about errors received from the API. In situations where no API connection was possible, for example, if the client has no permissions to connect to the socket, the request would have a "-1" status-code;
https://github.com/moby/moby/blob/3e39ec60dab859f70577ea8561fe5bda5236749e/client/request.go#L133-L134

In this case, a client with "debug" enabled, would print _and_ log a confusing error message:

    DEBU[0000] FIXME: Got an status-code for which error does not match any expected type!!!  error="Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post \"http://%2Fvar%2Frun%2Fdocker.sock/v1.24/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile.repro&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=repro&target=&ulimits=null&version=1\": dial unix /var/run/docker.sock: connect: permission denied" module=api status_code=-1
    Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile.repro&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=repro&target=&ulimits=null&version=1": dial unix /var/run/docker.sock: connect: permission denied

In the above; `DEBU` logs the error (including the "FIXME"), and the second line is the error message printed.

This was a mistake on my side when I added the `FromStatusCode` utility. I implemented that to be the counterpart to `FromError`, but in doing so also copied over the logging (see 1af30c50ca0ad81e2839ff4f2c5e70413f021d52). That log-message is only intended to be logged on the daemon side, for situations where we return an error without a proper errdefs (which would result in an 500 "internal server error" to be returned by the API).

This patch removes the debug log, and a minor cleanup to explicitly return "nil" if we didn't get an error in the first place.

**- Description for the changelog**

```
Remove unneeded "FIXME" debug logs printed by the client
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: errdefs/http_helpers.go [hunk 1]
```diff
@@ -33,11 +31,6 @@ func FromStatusCode(err error, statusCode int) error {
...
 		}
 	default:
-		logrus.WithError(err).WithFields(logrus.Fields{
-			"module":      "api",
-			"status_code": statusCode,
-		}).Debug("FIXME: Got an status-code for which error does not match any expected type!!!")
-
 		switch {
 		case statusCode >= 200 && statusCode < 400:
 			// it's a client error
```
Comment (thaJeztah) [inline errdefs/http_helpers.go:36]: Perhaps we should consider adding `-1` to this as well, but I kept that as-is for now (related to https://github.com/moby/moby/blob/3e39ec60dab859f70577ea8561fe5bda5236749e/client/request.go#L133-L134

**Review by corhere — APPROVED** [review]

**Review by tianon — APPROVED** [review]
