### PR TITLE
Windows DNS resolver forwarding

### LINKED ISSUE #46792: External DNS forwarding is broken on Windows container NAT networks
### Description

A 'feature' was implemented back in 2016 that sets the default gateway as the primary DNS server for Windows containers. This is currently a bool 'DisableGatewayDNS' and the issue is that no DNS servers are at the address thus resulting in the primary failing and then making use of the secondary DNS server. This being the default behavior causes issues if the user does not have a DNS server listening on the node itself. 

Link to DisableGatewayDNS property: https://github.com/moby/moby/blob/7e66d9900c81e872e5ecc89aa0bb03e52901447f/libnetwork/drivers/windows/windows.go#L49C2-L49C19

Original Commit:
https://github.com/moby/moby/commit/5a5b7fee330867bc313a7b33a2e9611ffeea6328

We have several options here and I am willing to do the work to resolve this. 

1. Remove the feature entirely
2. Change the name of property to EnableGatewayDNS
3. If the option is not set, default to true
4. Fix issue with DNS

For option 3:
https://github.com/moby/moby/blob/5a5b7fee330867bc313a7b33a2e9611ffeea6328/libnetwork/drivers/windows/windows_store.go#L154

The user still has the ability to set custom DNS servers via the "com.docker.network.windowsshim.dnsservers" option as a comma separated string on network creation or by using the --dns flag on docker run. Note that when using these options, the default gateway is still used as the primary however the fail behavior goes to the additional DNS servers. 

Issues: 
https://forums.docker.com/t/dns-broken-on-docker-desktop-for-windows/130121
https://github.com/microsoft/Windows-Containers/issues/216

More issues exist. It does seem that most people are setting "com.docker.network.windowsshim.disable_gatewaydns=true" as the default behavior of false is not applicable to 99% of users. 

In this comment, I propose a work around: 
https://github.com/microsoft/Windows-Containers/issues/216#issuecomment-1775709793

### PR DESCRIPTION
**Pull request by robmry**
**- What I did**

* Fix https://github.com/moby/moby/issues/46792

Make the internal DNS resolver for Windows containers forward requests to upsteam DNS servers when it cannot respond itself, rather than returning SERVFAIL.

Windows containers are normally configured with the internal resolver first for service discovery (container name lookup), then external resolvers from '--dns' or the host's networking configuration.

When a tool like ping gets a SERVFAIL from the internal resolver, it tries the other nameservers. But, nslookup does not, and with this change it does not need to.

**- How I did it**

The internal resolver learns external server addresses from the container's HNSEndpoint configuration, so it will use the same DNS servers as processes in the container.

The internal resolver for Windows containers listens on the network's gateway address, and each container may have a different set of external DNS servers. So, the resolver uses the source address of the DNS request to select external resolvers.

A [feature option](https://docs.docker.com/reference/cli/dockerd/#feature-options) can be used to enable forwarding from the internal resolver. In `daemon.json` ...

```
  "features": {
	  "windows-dns-proxy": true
  },
```

The plan is for the default in release 26.1 to be no-proxying (no change in behaviour), then to enable it by-default in 27.0.

**- How to verify it**

New unit and integration tests. (Although, the integration test can only check that external DNS requests are not forwarded, until the default is changed to enable forwarding.)

Before the change, with no `features` config, or with `"features": { "windows-dns-proxy": false }` in daemon.json ...
```
...
docker run -ti --rm --network mynat --name c1 mcr.microsoft.com/windows/servercore:ltsc2022 powershell.exe
...
PS C:\> nslookup google.com
Server:  UnKnown
Address:  172.31.144.1
```

Now, with `"features": { "windows-dns-proxy": true }` in daemon.json  ...
```
.\dockerd.exe
...
docker run -ti --rm --network mynat --name c1 mcr.microsoft.com/windows/servercore:ltsc2022 powershell.exe
...
PS C:\> nslookup google.com
Server:  UnKnown
Address:  172.31.144.1

Non-authoritative answer:
Name:    google.com
Addresses:  2a00:1450:4009:817::200e
          172.217.169.14
```

**- Description for the changelog**
```markdown changelog
Native Windows containers are configured with an internal DNS server for container name
resolution, and external DNS servers for other lookups. Not all resolvers, including `nslookup`
fall back to the external resolvers when they get a SERVFAIL from the internal server. So, the
internal DNS server can now be configured to forward requests to the external resolvers, by
using a feature option in the `daemon.json` file: `"features": { "windows-dns-proxy": true }`.
This will become the default behaviour in a future release.
```

### CODE REVIEW

File: libnetwork/network_windows.go [hunk 1]
```diff
@@ -66,6 +77,144 @@ func (n *Network) startResolver() {
...
+	}
+
+	return nil
+}
+
+// Allow unit tests to supply their own function for fetching HNSEndpoints.
+var hnsListEndpointRequest = hcsshim.HNSListEndpointRequest
+
+func findHNSEp(ip4, ip6 *net.IPNet) *hcsshim.HNSEndpoint {
+	hnsEndpoints, err := hnsListEndpointRequest()
```
Comment (corhere) [inline libnetwork/network_windows.go:187]: The call to `HNSListEndpointRequest` has no arguments and is unconditionally called, so could trivially be substituted with the `[]HNSEndpoint` value it would have returned. With just a little bit of refactoring, you could simply pass the mock `[]HNSEndpoint` slice directly to the code under test instead of having to mock out the function with a package-global variable.

```go
func findHNSEp(ip4, ip6 *net.IPNet, haystack []hcsshim.HNSEndpoint) *hcsshim.HNSEndpoint

func addEpToResolverImpl(netName, epName string, epIface *EndpointInterface, resolvers []*Resolver, hnsEPs []hcsshim.HNSEndpoint) error

func addEpToResolver(netName, epName string, epIface *EndpointInterface, resolvers []*Resolver) error {
	return addEpToResolverImpl(netName, epName, epIface, resolvers, hcsshim.HNSListEndpointRequest())
}
```

File: libnetwork/network_windows.go [hunk 2]
```diff
@@ -66,6 +77,144 @@ func (n *Network) startResolver() {
...
+			(hnsEp.IPv6Address != nil && hnsEp.IPv6Address.Equal(ip6.IP)) {
+			return &hnsEp
+		}
+	}
+	return nil
+}
+
+func findResolver(resolvers []*Resolver, gw4, gw6 string) *Resolver {
+	for _, resolver := range resolvers {
+		ns := resolver.NameServer()
```
Comment (corhere) [inline libnetwork/network_windows.go:202]: `func (*Resolver) NameServer() string` is only used in one place in existing code.
https://github.com/moby/moby/blob/790c3039d0ca5ed86ecd099b4b571496607628bc/libnetwork/sandbox_dns_unix.go#L346
There's no reason I can see—aside from inertia—not to just refactor it (and the `listenAddress` struct field) to be a pre-parsed `netip.Addr`.

File: libnetwork/network_windows.go [hunk 3]
```diff
@@ -66,6 +77,144 @@ func (n *Network) startResolver() {
...
+		if sameAddrs(ns, gw4) || sameAddrs(ns, gw6) {
```
Comment (corhere) [inline libnetwork/network_windows.go:203]: You're paying to re-parse the constants `gw4` and `gw6` in each iteration of the loop.

**Review by corhere — COMMENTED** [review]
Looking good. I have some nits to pick with the implementation details, but the design looks good to me.

File: daemon/container_operations.go [hunk 4]
```diff
@@ -73,6 +73,9 @@ func (daemon *Daemon) buildSandboxOptions(cfg *config.Config, container *contain
 	} else if len(cfg.DNSOptions) > 0 {
 		sboxOptions = append(sboxOptions, libnetwork.OptionDNSOptions(cfg.DNSOptions))
 	}
+	if cfg.DNSNoProxy {
+		sboxOptions = append(sboxOptions, libnetwork.OptionDNSNoProxy())
```
[the remark this answers is not in the document]
Comment (robmry) [reply daemon/container_operations.go:77]: > I can understand if you would want it to be consistent with how daemon config reload does not affect the DNS configuration of containers until the containers are restarted, though.

Let's go with that. Also...
- there's a list of the [things reload does](https://docs.docker.com/reference/cli/dockerd/#configuration-reload-behavior), I don't know how complete it is, but of course this isn't on it.
- the flag is mainly intended for emergency use, in case this change causes problems for Windows containers. But, daemon reload doesn't seem particularly useable on Windows, I'm not sure it works.
- if we find out that people need to change the setting on reload, or per-container, we can add support for that later. I think there's a fair chance nobody will need it.

File: libnetwork/network_unix.go [hunk 5]
```diff
@@ -2,13 +2,28 @@
...
 
 // Stub implementations for DNS related functions
 
 func (n *Network) startResolver() {
 }
 
+func (n *Network) ExecFunc(f func()) error {
+	return types.NotImplementedErrorf("ExecFunc not supported by network")
+}
+
```
[the remark this answers is not in the document]
Comment (robmry) [reply libnetwork/network_unix.go]: Ah yes, done.

File: libnetwork/resolver.go [hunk 6]
```diff
@@ -99,6 +103,36 @@ func NewResolver(address string, proxyDNS bool, backend DNSBackend) *Resolver {
...
+type addrToExtDNSMap struct {
+	mu   sync.Mutex
+	eMap map[netip.Addr][maxExtDNS]extDNSEntry
+}
+
+func newAddrToExtDNSMap() *addrToExtDNSMap {
+	return &addrToExtDNSMap{
+		eMap: map[netip.Addr][maxExtDNS]extDNSEntry{},
+	}
+}
```
[the remark this answers is not in the document]
Comment (robmry) [reply libnetwork/resolver.go]: Done.

File: libnetwork/resolver.go [hunk 7]
```diff
@@ -99,6 +103,36 @@ func NewResolver(address string, proxyDNS bool, backend DNSBackend) *Resolver {
...
+	return entries, ok
+}
+
+func (am *addrToExtDNSMap) set(addr netip.Addr, entries []extDNSEntry) {
+	var e [maxExtDNS]extDNSEntry
+	copy(e[:], entries)
+	am.mu.Lock()
+	defer am.mu.Unlock()
+	if len(entries) > 0 {
+		am.eMap[addr] = e
```
[the remark this answers is not in the document]
Comment (robmry) [reply libnetwork/resolver.go:128]: Done.

File: libnetwork/network.go [hunk 8]
```diff
@@ -193,6 +193,7 @@ type Network struct {
 	persist          bool
 	drvOnce          *sync.Once
 	resolverOnce     sync.Once //nolint:nolintlint,unused // only used on windows
+	dnsCompartment   uint32    //nolint:nolintlint,unused // only used on windows
```
[the remark this answers is not in the document]
Comment (robmry) [reply libnetwork/network.go]: Done.

File: libnetwork/network_windows.go (hunk 1 above)
Comment (robmry) [reply libnetwork/network_windows.go]: Doh - that's how I did it initially, but I second-guessed myself into thinking you'd prefer it the other way! It's split again now.

File: libnetwork/network_windows.go (hunk 2 above)
Comment (robmry) [reply libnetwork/network_windows.go:238]: Done.

File: libnetwork/network_windows.go (hunk 3 above)
Comment (robmry) [reply libnetwork/network_windows.go]: It's much more environmentally friendly now.

File: libnetwork/sandbox.go [hunk 9]
```diff
@@ -89,6 +89,7 @@ type resolvConfPathConfig struct {
 	dnsList              []string
 	dnsSearchList        []string
 	dnsOptionsList       []string
+	dnsNoProxy           bool
```
Comment (corhere) [inline libnetwork/sandbox.go:92]: This field is not like the others. It does not affect the container /etc/resolv.conf file. Move it to `containerConfig`?

File: libnetwork/sandbox_dns_unix.go [hunk 10]
```diff
@@ -48,7 +49,8 @@ func (sb *Sandbox) startResolver(restore bool) {
 		// have a gateway. So, if the Sandbox is only connected to an 'internal' network,
 		// it will not forward DNS requests to external resolvers. The resolver's
 		// proxyDNS setting is then updated as network Endpoints are added/removed.
-		sb.resolver = NewResolver(resolverIPSandbox, sb.getGatewayEndpoint() != nil, sb)
+		proxyDNS := !sb.config.dnsNoProxy && sb.getGatewayEndpoint() != nil
+		sb.resolver = NewResolver(resolverIPSandbox, proxyDNS, sb)
```
Comment (corhere) [inline libnetwork/sandbox_dns_unix.go:53]: What's stopping `sb.resolver.SetForwardingPolicy()` calls (#47538) from overriding the `dnsNoProxy` config when joining and leaving endpoints to the sandbox?

**Review by corhere — CHANGES_REQUESTED** [review]
I am only requesting changes because I spotted a (potential) bug with `OptionDNSNoProxy` under Linux. All my other review comments this round are optional nitpicks.

File: libnetwork/sandbox_dns_unix.go (hunk 10 above)
Comment (robmry) [reply libnetwork/sandbox_dns_unix.go:53]: Oh! Thank you, that was silly of me.

I can only think of ugly fixes. `Resolver` could have an `allowProxyDNS` to use as ...

```
func (r *Resolver) serveDNS(w dns.ResponseWriter, query *dns.Msg) {
	...
	if r.allowProxyDNS && r.proxyDNS.Load() {
```

Making it an enum, disable/on/off, would be nicer but then `SetForwardingPolicy()` and the atomic.Bool get messier.

To initialise it, could have an extra constructor ...

```
	if sb.config.dnsNoProxy {
		sb.resolver = NewResolverNoProxy(resolverIPSandbox, sb)
	} else {
		sb.resolver = NewResolver(resolverIPSandbox, sb.getGatewayEndpoint() != nil, sb)
	}
```

Or, initialise it to `proxyDNS` and requiring a `SetForwardingPolicy(false)` to disable it if the initial networks are all internal ...

```
	sb.resolver = NewResolver(resolverIPSandbox, !sb.config.dnsNoProxy, sb)
	sb.resolver.SetForwardingPolicy(sb.getGatewayEndpoint() != nil)
```

(Or an extra flag in the existing constructor, or enum instead of two flags - but that's a bit awkward.)

Can you think of something pretty?

Comment (corhere) [reply libnetwork/sandbox_dns_unix.go:53]: Instead of the Endpoint reaching into `sb.resolver`, have the sandbox be in charge of calling `sb.resolver.SetForwardingPolicy` somehow so that it can gate enabling of forwarding on `sb.config.dnsNoProxy`. While it'd be really elegant if that could be piggybacked off an existing sandbox method called by `func (*Endpoint) sbJoin`, I didn't spot an obvious choice that wouldn't be problematic in some way. `sb.updateDNS` looks like a promising candidate, but the call would have to be moved to after the `sb.addEndpoint(ep)` call, which risks unintended side effects. Go with the pragmatic solution of writing a new sandbox method which `func (*Endpoint) sbJoin` and `func (*Endpoint) sbLeave` call instead of `sb.resolver.SetForwardingPolicy`?
```go
func (sb *Sandbox) RefreshResolverPolicy() {
	sb.resolver.SetForwardingPolicy(!sb.config.dnsNoProxy && sb.getGatewayEndpoint() != nil)
}
```

File: libnetwork/network_windows.go [hunk 11]
```diff
@@ -66,6 +83,166 @@ func (n *Network) startResolver() {
...
+		}).Debug("Endpoint is not configured to use internal DNS resolver")
+		return nil
+	}
+
+	// If the internal resolver is configured as one of this endpoint's DNS servers,
+	// tell it which ext servers to use for requests from this endpoint's addresses.
+	s := make([]string, len(dnsList))
+	for i, d := range dnsList {
+		s[i] = d.IPStr
+	}
```
[the remark this answers is not in the document]
Comment (robmry) [reply libnetwork/network_windows.go]: Done.

File: libnetwork/resolver.go [hunk 12]
```diff
@@ -87,18 +90,47 @@ type Resolver struct {
...
-		logInverval:   rate.Sometimes{Interval: logInterval},
+		backend:     backend,
+		err:         fmt.Errorf("setup not done yet"),
+		startCh:     make(chan struct{}, 1),
+		fwdSem:      semaphore.NewWeighted(maxConcurrent),
+		logInverval: rate.Sometimes{Interval: logInterval},
+	}
+	if la, err := netip.ParseAddr(address); err == nil {
+		r.listenAddress = la
 	}
```
[the remark this answers is not in the document]
Comment (robmry) [reply libnetwork/resolver.go]: Done.

File: libnetwork/resolver.go [hunk 13]
```diff
@@ -114,7 +146,7 @@ func (r *Resolver) SetupFunc(port int) func() {
 
 		// DNS operates primarily on UDP
 		r.conn, err = net.ListenUDP("udp", &net.UDPAddr{
-			IP:   net.ParseIP(r.listenAddress),
+			IP:   r.listenAddress.AsSlice(),
 			Port: port,
 		})
```
[the remark this answers is not in the document]
Comment (robmry) [reply libnetwork/resolver.go]: Done.

File: libnetwork/sandbox.go (hunk 9 above)
Comment (robmry) [reply libnetwork/sandbox.go]: Done.

File: libnetwork/sandbox_dns_unix.go (hunk 10 above)
Comment (robmry) [reply libnetwork/sandbox_dns_unix.go:53]: Perfect - thank you.

(I'm about to publish a PR that removes `sb.UpdateDNS`, so I'm glad it wasn't the right place!)

**Review by corhere — APPROVED** [review]

**Comment by robmry** [comment]
@akerouanton - suggested replacing "--dns-no-proxy" with a feature-flag ... as it's only intended as an emergency off-switch for this change, and we'll want to get rid of it.

I've made it Windows-only, as we don't really have a use-case for it on Linux. So, removed it from the regression test. But I left in `Sandbox.RefreshResolverPolicy()` as it seems a bit neater anyway.

To disable this change, it's now something like this in `daemon.json` ...

```
  "features": {
	  "windows-no-dns-proxy": true
  },
```

File: daemon/container_operations.go [hunk 14]
```diff
@@ -73,6 +73,9 @@ func (daemon *Daemon) buildSandboxOptions(cfg *config.Config, container *contain
 	} else if len(cfg.DNSOptions) > 0 {
 		sboxOptions = append(sboxOptions, libnetwork.OptionDNSOptions(cfg.DNSOptions))
 	}
+	if cfg.Features["windows-no-dns-proxy"] {
```
Comment (corhere) [inline daemon/container_operations.go:76]:
```suggestion
	if runtime.GOOS == "windows" && cfg.Features["windows-no-dns-proxy"] {
```

Should it be a validation error (or a daemon warning log) to have that feature set in a non-Windows daemon config? Do we have any existing validation for configured feature flags, e.g. to catch typos or removed flags?

File: libnetwork/sandbox.go [hunk 15]
```diff
@@ -347,6 +348,15 @@ func (sb *Sandbox) GetEndpoint(id string) *Endpoint {
 	return nil
 }
 
+// RefreshResolverPolicy makes sure the resolver will only forward DNS requests to
+// upstream resolvers if proxying is enabled, and there's at least one endpoint with
+// external connectivity.
+func (sb *Sandbox) RefreshResolverPolicy() {
+	if sb.resolver != nil {
+		sb.resolver.SetForwardingPolicy(sb.getGatewayEndpoint() != nil)
```
Comment (corhere) [inline libnetwork/sandbox.go:356]: While it technically functions as intended given that `runtime.GOOS == "windows"` implies `sb.resolver == nil`, neither the `dnsNoProxy` flag nor `OptionDNSNoProxy` are in Windows-only code. As long as the option can be set on Linux sandboxes, the option should be effective.
```suggestion
		sb.resolver.SetForwardingPolicy(!sb.config.dnsNoProxy && sb.getGatewayEndpoint() != nil)
```
(Corollary: the option does not need to be effective on Linux sandboxes if it is a compile or runtime error to create a sandbox with `OptionDNSNoProxy()`.)

File: libnetwork/sandbox_dns_unix.go
Comment (corhere) [inline libnetwork/sandbox_dns_unix.go:1]: As long as `OptionDNSNoProxy()` is allowed when constructing a Linux sandbox, `func (*Sandbox) startResolver` needs to respect the value of `sb.config.dnsNoProxy`.

**Review by corhere — CHANGES_REQUESTED** [review]
The only thing Windows-only about `OptionDNSNoProxy` is the conditions under which the daemon could pass the option. It is violation of the principle of least surprise for constructing sandboxes with `OptionDNSNoProxy()` to be a no-op on some platforms. IMO it's a footgun: someone might try to contribute a change which relies on passing `OptionDNSNoProxy` on non-Windows platforms and nobody notices until it's a CVE. Either make `OptionDNSNoProxy()` disable DNS proxying irrespective of platform, or make it so passing `OptionDNSNoProxy()` on platforms where it is ineffective would fail fast and loudly. Compile error would be ideal since the bugged code would never make it past CI, but I would also be happy with `func (*Controller) NewSandbox` returning an error.

File: daemon/container_operations.go (hunk 14 above)
Comment (robmry) [reply daemon/container_operations.go]: > Should it be a validation error (or a daemon warning log) to have that feature set in a non-Windows daemon config?

Now, this happens ...

```
# /usr/local/bin/dockerd
unable to configure the Docker daemon with file /etc/docker/daemon.json: feature option 'windows-no-dns-proxy' is only available on Windows
```

> Do we have any existing validation for configured feature flags, e.g. to catch typos or removed flags?

I don't think so.

File: libnetwork/sandbox.go (hunk 15 above)
Comment (robmry) [reply libnetwork/sandbox.go:356]: `OptionDNSNoProxy()` now only exists on Windows.

File: libnetwork/sandbox_dns_unix.go
Comment (robmry) [reply libnetwork/sandbox_dns_unix.go:1]: Ditto.

File: libnetwork/endpoint.go [hunk 16]
```diff
@@ -543,6 +544,12 @@ func (ep *Endpoint) sbJoin(sb *Sandbox, options ...EndpointOption) (err error) {
 		return err
 	}
 
+	if !sb.config.dnsNoProxy {
```
Comment (corhere) [inline libnetwork/endpoint.go:547]: There's already more than enough code peppering libnetwork which looks at a glance like it's platform-independent but is revealed to be platform-specific once you trace through enough code. I would really like new platform-specific code to obviously and unambiguously read as such. While comments and naming go a long way, writing code which constant-folds the platform specific code on irrelevant platforms is impossible to get out of sync with runtime behaviour and is the rare exception of a premature optimization which _improves_ readability of the code.
```suggestion
	if runtime.GOOS != "windows" || !sb.config.dnsNoProxy {
```

Alternatively, do you see a clean way to lower the `!sb.config.dnsNoProxy` test into `_windows.go` code? Indirect through a method on `*Network` or `*Sandbox`?

File: libnetwork/sandbox.go [hunk 17]
```diff
@@ -98,6 +98,7 @@ type containerConfig struct {
 	useDefaultSandBox bool
 	useExternalKey    bool
 	exposedPorts      []types.TransportPort
+	dnsNoProxy        bool
```
Comment (corhere) [inline libnetwork/sandbox.go:101]:
```suggestion
	dnsNoProxyOnWindowsOnly        bool // Only used on Windows; has no effect on other platforms
```
Overkill?

File: libnetwork/sandbox.go [hunk 18]
```diff
@@ -347,6 +348,15 @@ func (sb *Sandbox) GetEndpoint(id string) *Endpoint {
 	return nil
 }
 
+// RefreshResolverPolicy makes sure the resolver will only forward DNS requests to
+// upstream resolvers if proxying is enabled, and there's at least one endpoint with
+// external connectivity.
+func (sb *Sandbox) RefreshResolverPolicy() {
```
Comment (corhere) [inline libnetwork/sandbox.go:354]: We're setting up a trap for future code archaeologists (read: ourselves in a year) by including the `RefreshResolverPolicy` refactor—which is now _only_ relevant for Linux—in a commit titled "Windows DNS resolver forwarding," for which the only other change in this source file is the addition of a Windows-only struct field. I think this refactor should be split into a separate PR, or at least its own commit, for the benefit of our future selves.

File: libnetwork/endpoint.go (hunk 16 above)
Comment (robmry) [reply libnetwork/endpoint.go:547]: I nearly passed `&sb.config` into `addEpToResolver()` ... then decided it wasn't worthwhile with `config.dnsNoProxy` defined for all platforms anyway.

So, I can do that - and add a `containerConfigOS struct` to include in `libnetwork.containerConfig`. It'll be an empty struct on Linux, just `dnsNoProxy` on Windows.

We already have `sandbox.go`, `sandbox_linux.go`, and `sandbox_unsupported.go` (which is `go:build !linux`).

Putting the Windows version of `containerConfigOS` into `sandbox_unsupported.go` would be bad. So, I'll have to make a `sandbox_windows.go` as well.

(Although, I think the only platforms we build for are "windows" and "linux" - "freebsd" doesn't work? So, there's probably no need to add a `containerConfigOS` to `sandbox_unsupported.go`. In which case, I could rename `sandbox_unsupported.go` to `sandbox_windows.go` to avoid the extra `sandbox_blah.go` and make things clearer?)

**Review by akerouanton — APPROVED** [review]
LGTM

File: libnetwork/endpoint.go (hunk 16 above)
Comment (robmry) [reply libnetwork/endpoint.go]: I've done that, including renaming `sandbox_upsupported.go`.

File: libnetwork/sandbox.go (hunk 17 above)
Comment (robmry) [reply libnetwork/sandbox.go]: `dnsNoProxy` only exists on Windows now.

File: libnetwork/sandbox.go (hunk 18 above)
Comment (robmry) [reply libnetwork/sandbox.go]: I've un-done that change.

**Review by corhere — APPROVED** [review]

File: daemon/config/config.go [hunk 19]
```diff
@@ -514,6 +515,12 @@ func getConflictFreeConfiguration(configFile string, flags *pflag.FlagSet) (*Con
 		return nil, err
 	}
 
+	if runtime.GOOS != "windows" {
+		if _, ok := config.Features["windows-no-dns-proxy"]; ok {
```
Comment (thaJeztah) [inline daemon/config/config.go:519]: Bike-shedding; would `(windows)-disable-dns-proxy` be clearer?

Also (question); is this an option we could see becoming opt-in/opt-out for non-Windows? And in that case, do we need the `windows-` prefix? (we can still document - and error- when used on other platforms)

File: daemon/container_operations.go [hunk 20]
```diff
@@ -54,7 +54,8 @@ func (daemon *Daemon) buildSandboxOptions(cfg *config.Config, container *contain
 		sboxOptions = append(sboxOptions, libnetwork.OptionUseExternalKey())
 	}
 
-	if err := setupPathsAndSandboxOptions(container, cfg, &sboxOptions); err != nil {
+	// Add OS-specific Sandbox options.
+	if err := buildSandboxOptionsOS(container, cfg, &sboxOptions); err != nil {
```
Comment (thaJeztah) [inline daemon/container_operations.go:58]: More bike-shedding; I know we have some other "options" / platform-specific code for which we use `platform` as term for this, e.g. `ValidatePlatformConfig` and `setPlatformDefaults` in the daemon/config package. Perhaps it would be clear to follow that convention.

File: daemon/config/config.go [hunk 21]
```diff
@@ -514,6 +515,12 @@ func getConflictFreeConfiguration(configFile string, flags *pflag.FlagSet) (*Con
...
+			return nil, errors.New("feature option 'windows-no-dns-proxy' is only available on Windows")
```
Comment (thaJeztah) [inline daemon/config/config.go:520]: Oh! Other comment just made me realise we have a `Config.ValidatePlatformConfig` function with implementations for Linux and Windows, so wondering if this should belong there; https://github.com/moby/moby/blob/484480f56aa38053493e100dbd1c25da0c831df6/daemon/config/config_linux.go#L175-L176

File: daemon/config/config.go (hunk 19 above)
Comment (robmry) [reply daemon/config/config.go:519]: On the name ... they look quite equivalent to me (and the current name is less typing!), but happy to change it if you like?

It started off as a Windows and Linux option - but there's no known use-case for disabling it on Linux, and we don't really need more options to maintain. It's really only meant as an emergency off-switch ... hopefully nobody will need it but, if there's something we didn't think of, being able to restore the old behaviour might save us from having to make a patch in a hurry. So, Albin suggested making it a Windows-only feature flag - which will make it easier to remove in future if it's not useful.

File: daemon/container_operations.go (hunk 20 above)
Comment (robmry) [reply daemon/container_operations.go:58]: Oh, yes - I'll change it.

File: daemon/config/config.go (hunk 21 above)
Comment (robmry) [reply daemon/config/config.go:520]: Yes, I'd missed that - thank you, I'll move it.

**Review by vvoland — CHANGES_REQUESTED** [review]
Chatting with @corhere - we should turn it into an opt-in for 26.1, and then turn into opt-out in 27.0.

File: daemon/container_operations_windows.go [hunk 22]
```diff
@@ -163,7 +163,13 @@ func serviceDiscoveryOnDefaultNetwork() bool {
 	return true
 }
 
-func setupPathsAndSandboxOptions(container *container.Container, cfg *config.Config, sboxOptions *[]libnetwork.SandboxOption) error {
+func buildSandboxPlatformOptions(container *container.Container, cfg *config.Config, sboxOptions *[]libnetwork.SandboxOption) error {
+	// By default, the Windows internal resolver does not forward requests to
+	// external resolvers - but forwarding can be enabled using feature flag
+	// "windows-dns-proxy":true.
+	if doproxy, exists := cfg.Features["windows-dns-proxy"]; !exists || !doproxy {
```
Comment (vvoland) [inline daemon/container_operations_windows.go:170]: Wondering if we should leave the old name `windows-dns-no-proxy` and turn the conditional here into `exists || !doproxy`.

The reason why I think it could be better is that it's a bit confusing to set feature to `false` to opt-in into a new behavior and IMO it's more intuitive if the missing value is equivalent to explicit `false` rather than `true`.

The alternative would be to change the `windows-dns-proxy` into `windows-dns-no-proxy` later, but that would mean that users that opt-in now, will have to adjust their config again.

WDYT?

Comment (robmry) [reply daemon/container_operations_windows.go:170]: I changed it because it got a bit double-negative-y, I think this naming is a bit simpler. Disabling it, if needed, in 27.0 will look like this - I think its meaning is clear? ...

```
  "features": {
	  "windows-dns-proxy": false
  },
```

Docs also have an example of an enabled-by-default feature that can be disabled ... https://docs.docker.com/reference/cli/dockerd/#feature-options 

So, I prefer it this way - but can change it back if needed?

Comment (robmry) [reply daemon/container_operations_windows.go:170]: (Either way - I'll raise a new PR to change the default, and mark it for milestone 27.0, as soon as this one's merged.)

Comment (vvoland) [reply daemon/container_operations_windows.go:170]: No strong opinion on my side, but maybe @thaJeztah has some preference?

Comment (thaJeztah) [reply daemon/container_operations_windows.go:170]: Hm... yeah, the ones where defaults change are always a bit tricky I guess. So the new default will become "disabled by default" (but currently it's "enabled by default"?)

From some perspective `windows-dns-no-proxy` or `windows-disable-dns-proxy`  or `windows-dns-proxy-disabled` would be more friendly, but also considering what it would look like if we would be showing the features as part of `docker info`


I don't think we currently expose the `features`, but I think that's something we could consider, and if we do, for those to reflect the defaults (in this case, that would mean `windows-dns-proxy: false`?)

Comment (robmry) [reply daemon/container_operations_windows.go:170]: Yes, for release 26.1.0 the default will be `windows-dns-proxy: false`.

In 27.0.0, we'll change the default to `windows-dns-proxy: true`.

If those were displayed in `docker info`, that's what they'd look like ... clear, I think?

(I reckon our minds are corrupted by Go's zero-values ... we think a default needs to be `false`, that's why I originally used `windows-dns-no-proxy`. But, for normal people (!), I think getting rid of the double-negative in `windows-dns-no-proxy: false` is a good thing.)

Comment (akerouanton) [reply daemon/container_operations_windows.go:170]: FWIW, I think getting rid of the double-negative is great. IMHO it feels more natural to have to turn a feature-flag 'true' to get it enabled and 'false' to opt-out.

**Review by vvoland — APPROVED** [review]
I'm fine as long as we don't mutate the `Features` (which this PR doesn't do) - so if we ever want to expose the `features` (for example in `docker info`), we don't pollute it by default with features that are opt-out and are considered a "normal" code path.

**Comment by akerouanton** [comment]
> I'm fine as long as we don't mutate the Features (which this PR doesn't do) - so if we ever want to expose the features (for example in docker info), we don't pollute it by default with features that are opt-out and are considered a "normal" code path.

Then, how would you show that a specific flag is opt-out? I think something like that would be the best:

```
Feature:
    windows-dns-proxy: enabled (default)
    foobar: disabled (default)
    somethingsomething: enabled (user-defined)
```

**Comment by vvoland** [comment]
Hmm, I think I wouldn't mind that output for the actual features like:
```
Feature:
    containerd-snapshotter: disabled (default)
    buildkit: enabled (default)
```

But, I don't really like showing `windows-dns-proxy: enabled (default)` because it's not really a feature, but an escape hatch out of a new, default behavior, which most users don't even care about because it's not really relevant outside of WCOW (which is a niche on its own).
