### PR TITLE
Fix layer compression regression

### LINKED ISSUE #17038: [1.9.0-rc1] docker push performance regression
Pushing to an S3-backed private registry takes much longer on 1.9.0-rc1 than on 1.8.2, even though pushing to a local registry is substantially faster. When attached to a TTY, most of the time is spent after the "Pushing" progress bar hits completion, but before printing "Pushed". This time is negligible when pushing to a registry on the same machine backed by the local filesystem.

In 1.8.2, we spent *way* more time creating the tarball to send ("Buffering to Disk"), but there was no wait between the upload and "Image successfully pushed".

### Some logs

In the comparisons below:

* Same server is used, before and after the upgrade from 1.8.2 to 1.9.0-rc1
* The top layers, `7191` and `8469` are both almost exactly 400MB
* `registry.shopify.io` is an S3-backed private registry, hosted in EC2 along with the machine we're pushing from here.
* This is actually indicative of a trend on sample sizes > 1 :)

##### Docker 1.8.2

```
Oct 14 18:56:19.277:	The push refers to a repository [registry.shopify.io/shopify-ci-branches] (len: 1)
Oct 14 18:56:19.294:	7191157cb30d: Buffering to Disk
Oct 14 18:56:32.647:	7191157cb30d: Image successfully pushed
Oct 14 18:56:32.928:	fa1c81cb6b28: Image already exists
Oct 14 18:56:33.267:	03c5add71c1d: Image already exists
Oct 14 18:56:33.686:	b25524db876d: Image already exists
Oct 14 18:56:34.024:	c290db7a5070: Image already exists
Oct 14 18:56:34.283:	454c2d886fcc: Image already exists
Oct 14 18:56:35.774:	ba5e0000ba5c: Image already exists
Oct 14 18:56:35.777:	ac192e88bf8434b72d6b237634ebf3bac5ab9ace: digest: sha256:30b3430df4b7d4bbd9f56b678b5a1c35b3632c7fd088eeca86ff93d8070065fe size: 12862
```

##### Docker 1.9.0-rc1

```
Oct 14 19:00:09.679:	The push refers to a repository [registry.shopify.io/shopify-ci-branches] (len: 1)
Oct 14 19:00:09.712:	8469016332f7: Preparing
Oct 14 19:00:09.807:	8469016332f7: Pushing
Oct 14 19:01:36.139:	8469016332f7: Pushed
Oct 14 19:01:36.388:	a5323a34b08b: Image already exists
Oct 14 19:01:36.749:	03c5add71c1d: Image already exists
Oct 14 19:01:37.170:	b25524db876d: Image already exists
Oct 14 19:01:38.101:	c290db7a5070: Image already exists
Oct 14 19:01:38.369:	454c2d886fcc: Image already exists
Oct 14 19:01:38.684:	ba5e0000ba5c: Image already exists
Oct 14 19:01:38.687:	23168f9ff831f4097bed8cb6aeab38e3db9ea3c7: digest: sha256:17092b886b66afb5ec9f66c2df760533dc43c4fd13fd99a1238f51a88f307caf size: 11567
```

### LINKED ISSUE #17209: Docker 1.9.0-rc1: compression when pushing to V2 registry
Push performance is significantly better in 1.9 compared to 1.8  thanks to #15493. What someone could consider to be a regression is that images pushed to V2 are not compressed, or compression level was changed significantly. 

Pushing large image layer (exactly the same image layer in both cases) to V2 docker registry (registry 2.1.1):

Daemon 1.8.1 => **2.7GB**
Daemon 1.9.0-rc1 => **4.5GB**

`docker version`:

    version
    Client:
     Version:      1.9.0-rc1
     API version:  1.21
     Go version:   go1.4.2
     Git commit:   9291a0e
     Built:        Wed Oct 14 03:04:22 UTC 2015
     OS/Arch:      linux/amd64
    
    Server:
     Version:      1.9.0-rc1
     API version:  1.21
     Go version:   go1.4.2
     Git commit:   9291a0e
     Built:        Wed Oct 14 03:04:22 UTC 2015
     OS/Arch:      linux/amd64
	 
`docker info`:

    Containers: 2
    Images: 389
    Engine Version: 1.9.0-rc1
    Storage Driver: aufs
     Root Dir: /data/docker/aufs
     Backing Filesystem: extfs
     Dirs: 393
     Dirperm1 Supported: false
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 3.13.0-65-generic
    Operating System: Ubuntu 14.04.3 LTS
    CPUs: 4
    Total Memory: 15.56 GiB
    Name: ICM-YELLOW
    ID: VZ4T:7XFC:LTCS:G5KQ:JZTF:CMIN:7QGW:OAPI:ELCR:CDTU:F6MT:R3DZ
    WARNING: No swap limit support

`uname -a`:

    Linux xyz 3.13.0-65-generic #106-Ubuntu SMP Fri Oct 2 22:08:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by aaronlehmann**
PR #15493 removed compression of layers when pushing them to a V2
registry. This this makes layer uploads larger than they should be.

This commit restores the compression. It uses an io.Pipe to turn the
gzip compressor output Writer into a Reader, so the ReadFrom method can
be used on the BlobWriter (which is very important for avoiding many
PATCH requests per layer).

Fixes #17209
Fixes #17038 

@stevvooe @tonistiigi @icecrime

### CODE REVIEW

**Comment by tonistiigi** [comment]
Code LGTM, but we should see if #15493 really increased performance or it was all just because compression was skipped. Reverting #15493 would leave us with cleaner code and correct values on progressbars(currently they show the uncompressed size not what is actually pushed).

**Comment by tiborvass** [comment]
@aaronlehmann what did the last push change?

**Comment by aaronlehmann** [comment]
> @aaronlehmann what did the last push change?
> 

I made the function explicitly call layerUpload's ReadFrom method instead of using io.Copy. These are equivalent, but it makes it harder to accidentally break something so that ReadFrom is no longer used.

**Comment by stevvooe** [comment]
@tonistiigi #15493 increased performance by not writing to disk. The performance increase was about 2x, since we aren't writing the file then reading it back from disk. 

I'm not sure what you even mean by "cleaner code". The compression stage was hidden in a function called `bufferToFile`. This makes the abstraction of a serialized layer reliant on the side-effect of writing to file to disk. This is another case of the push code managing something that should be abstracted away. That is the exact opposite of clean code.

**Comment by tiborvass** [comment]
@stevvooe can you review this PR please? would help a lot

**Comment by tonistiigi** [comment]
@stevvooe 
> I'm not sure what you even mean by "cleaner code"

I mean extra goroutine and the block marked with a comment `HACK:`

File: graph/push_v2.go [hunk 1]
```diff
@@ -254,8 +252,28 @@ func (p *v2Pusher) pushV2Image(bs distribution.BlobService, img *image.Image) (d
...
 	})
 
+	digester := digest.Canonical.New()
+	// HACK: The MultiWriter doesn't write directly to layerUpload because
+	// we must make sure the ReadFrom is used, not Write. Using Write would
+	// send a PATCH request for every Write call.
+	pipeReader, pipeWriter := io.Pipe()
+	compressor := gzip.NewWriter(io.MultiWriter(pipeWriter, digester.Hash()))
+
+	go func() {
```
Comment (stevvooe) [inline graph/push_v2.go]: Would be worthwhile to make a function like this?

```
// Compress compresses the contents of Reader rd into a new io.Reader.
func Compress(rd io.Reader) (io.Reader, error)
```

File: graph/push_v2.go [hunk 2]
```diff
@@ -254,8 +252,28 @@ func (p *v2Pusher) pushV2Image(bs distribution.BlobService, img *image.Image) (d
...
+		if err != nil {
+			pipeWriter.CloseWithError(err)
+		} else {
+			pipeWriter.Close()
+		}
+	}()
+
 	out.Write(p.sf.FormatProgress(stringid.TruncateID(img.ID), "Pushing", nil))
-	nn, err := io.Copy(layerUpload, reader)
+	nn, err := layerUpload.ReadFrom(pipeReader)
```
Comment (stevvooe) [inline graph/push_v2.go]: `io.Copy` should call `layerUpload.ReadFrom`. Is it not?

File: graph/push_v2.go [hunk 3]
```diff
@@ -254,8 +252,28 @@ func (p *v2Pusher) pushV2Image(bs distribution.BlobService, img *image.Image) (d
...
+	// HACK: The MultiWriter doesn't write directly to layerUpload because
+	// we must make sure the ReadFrom is used, not Write. Using Write would
+	// send a PATCH request for every Write call.
+	pipeReader, pipeWriter := io.Pipe()
+	compressor := gzip.NewWriter(io.MultiWriter(pipeWriter, digester.Hash()))
+
+	go func() {
+		_, err := io.Copy(compressor, reader)
+		if err == nil {
+			err = compressor.Close()
```
Comment (stevvooe) [inline graph/push_v2.go]: Should this be closed no matter what?

**Comment by stevvooe** [comment]
@tonistiigi Agreed. I'm not sure if we want to pay the disk IO penalty. Disks are slower than networks these days. I'm not even really sure I consider that a hack verses a workaround. `io.MultiWriter` may not be the right thing to use. `io.TeeReader` might be better but the gzip interface makes that awkward.

File: graph/push_v2.go (hunk 3 above)
Comment (aaronlehmann) [inline graph/push_v2.go]: The purpose of Close is to flush buffered data and finalize the gzip stream. If we're terminating early due to an error, I don't think it's necessary.

File: graph/push_v2.go (hunk 2 above)
Comment (aaronlehmann) [inline graph/push_v2.go]: It does indeed. I changed this to call `ReadFrom` directly to make it more explicit. This is not functionally different. It's mainly so that the code is consistent with the comment mentioning `ReadFrom`.

File: graph/push_v2.go (hunk 3 above)
Comment (stevvooe) [inline graph/push_v2.go]: Cheers!

File: graph/push_v2.go (hunk 2 above)
Comment (stevvooe) [inline graph/push_v2.go]: SGTM.

File: graph/push_v2.go (hunk 3 above)
Comment (tiborvass) [inline graph/push_v2.go]: @aaronlehmann would love more comments in the code explaining all this

Comment (stevvooe) [inline graph/push_v2.go]: @tiborvass `ReadFrom` let's the target writer select the buffer size. We are being explicit about it here. We should probably capture this in best practices some where.

**Comment by stevvooe** [comment]
LGTM

**Comment by jchesterpivotal** [comment]
This is probably bullshit, since I last looked at compression algos nearly 10 years ago. But here goes.

You might like to investigate other compression algorithms. Gzip -- the DEFLATE algorithm -- has two steps, one of which is a Lempel-Ziv 77 compression, followed by a Huffman encoding step to squeeze it down still further.

The downside is that the Huffman step only runs after you finish the LZ77 step. So you either wait for the entire input to be run through LZ77, or you chunk your uploads and then reassemble on the hub side.

Gzip is commonly used for web traffic because it's patent-free and because historically web payloads are small enough that both compression steps can finish faster than it would take to stream out the uncompressed payload.

As an alternative, descendants of Lempel-Ziv that do not include a Huffman step would allow images to be compressed and streamed simultaneously. I think this would obviate the need to double-cache images (compressed, then uncompressed, before streaming). Instead, a compressed stream could immediately begin flowing to the hub.

The ZFS folks came up with a LZ descendant, [LZJB](https://en.wikipedia.org/wiki/LZJB), because they needed a fast "good enough" streaming compression algorithm.

A later alternative for ZFS is [LZ4](https://en.wikipedia.org/wiki/LZ4_(compression_algorithm)), which is designed to be threadable.

**Comment by stevvooe** [comment]
@jchesterpivotal Thanks for the analysis, but this might not be the right venue for such a discussion. I'd recommend the mailing list or another issue.
