### PR TITLE
Fix issue with plugin scanner going to deep

### LINKED ISSUE #35992: Plugin not found message in daemon log
**Description**

After installing a plugin (netapp/ndvp), some repetitive error messages appear in the daemon log.

```
Jan 12 09:44:00 host1 dockerd[14753]: time="2018-01-12T09:44:00.014410367+01:00" level=error msg="plugin not found"
Jan 12 09:43:55 host1 dockerd[14753]: time="2018-01-12T09:43:55.798532970+01:00" level=error msg="plugin not found"
Jan 12 09:43:18 host1 dockerd[14753]: time="2018-01-12T09:43:18.554964465+01:00" level=error msg="plugin not found"
Jan 12 09:43:10 host1 dockerd[14753]: time="2018-01-12T09:43:10.415306479+01:00" level=error msg="plugin not found"
Jan 12 09:43:01 host1 dockerd[14753]: time="2018-01-12T09:43:01.650009043+01:00" level=error msg="plugin not found"
Jan 12 09:42:29 host1 dockerd[14753]: time="2018-01-12T09:42:29.129704504+01:00" level=error msg="plugin not found"
Jan 12 09:42:26 host1 dockerd[14753]: time="2018-01-12T09:42:26.203150845+01:00" level=error msg="plugin not found"
Jan 12 09:42:08 host1 dockerd[14753]: time="2018-01-12T09:42:08.936892945+01:00" level=error msg="plugin not found"
Jan 12 09:41:57 host1 dockerd[14753]: time="2018-01-12T09:41:57.008843300+01:00" level=error msg="plugin not found"
```

**Steps to reproduce the issue:**
1. Install netapp/ndvp plugin ( http://netappdvp.readthedocs.io/en/latest/install/host_config.html )
2. journalctl -u docker.service

**Describe the results you received:**
```
Jan 12 09:44:00 host1 dockerd[14753]: time="2018-01-12T09:44:00.014410367+01:00" level=error msg="plugin not found"
Jan 12 09:43:55 host1 dockerd[14753]: time="2018-01-12T09:43:55.798532970+01:00" level=error msg="plugin not found"
Jan 12 09:43:18 host1 dockerd[14753]: time="2018-01-12T09:43:18.554964465+01:00" level=error msg="plugin not found"
Jan 12 09:43:10 host1 dockerd[14753]: time="2018-01-12T09:43:10.415306479+01:00" level=error msg="plugin not found"
Jan 12 09:43:01 host1 dockerd[14753]: time="2018-01-12T09:43:01.650009043+01:00" level=error msg="plugin not found"
Jan 12 09:42:29 host1 dockerd[14753]: time="2018-01-12T09:42:29.129704504+01:00" level=error msg="plugin not found"
Jan 12 09:42:26 host1 dockerd[14753]: time="2018-01-12T09:42:26.203150845+01:00" level=error msg="plugin not found"
Jan 12 09:42:08 host1 dockerd[14753]: time="2018-01-12T09:42:08.936892945+01:00" level=error msg="plugin not found"
Jan 12 09:41:57 host1 dockerd[14753]: time="2018-01-12T09:41:57.008843300+01:00" level=error msg="plugin not found"
```

**Describe the results you expected:**
No error in the log

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:11:19 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:09:53 2017
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 13
 Running: 13
 Paused: 0
 Stopped: 0
Images: 15
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
 userns
Kernel Version: 4.4.0-109-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67GiB
Name: host1
ID: MIFR:GSOU:P4FI:ZIFY:FTD6:BZ4M:U6KV:NDX2:W3VV:J6AM:MYIQ:POSN
Docker Root Dir: /var/lib/docker/100000.100000
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Cluster Store: etcd://localhost:2379
Cluster Advertise: 192.168.1.29:2376
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://myregistry.com/
Live Restore Enabled: true

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ubuntu VM:
```
Linux host1 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by cpuguy83**
The plugin spec says that plugins can live in one of:

- `/var/run/docker/plugins/<name>.sock`
- `/var/run/docker/plugins/<name>/<name>.sock`
- `/etc/docker/plugins/<name>.[json,spec]`
- `/etc/docker/plugins/<name>/<name>.<json,spec>`
- `/usr/lib/docker/plugins/<name>.<json,spec>`
- `/usr/lib/docker/plugins/<name>/<name>.<json,spec>`

However, the plugin scanner which is used by the volume list API was
doing `filepath.Walk`, which will walk the entire tree for each of the
supported paths.
This means that even v2 plugins in
`/var/run/docker/plugins/<id>/<name>.sock` were being detected as a v1
plugin.
When the v1 plugin loader tried to load such a plugin it would log an
error that it couldn't find it because it doesn't match one of the
supported patterns... e.g. when in a subdir, the subdir name must match
the plugin name for the socket.

There is no behavior change as the error is only on the `Scan()` call,
which is passing names to the plugin registry when someone calls the
volume list API.

Fixes #35992

### CODE REVIEW

**Comment by thaJeztah** [comment]
CI is failing;

```
01:53:41 pkg/plugins/discovery_unix_test.go:157::error: possible formatting directive in Fatal call (vet)
01:53:41 Build step 'Execute shell' marked build as failure
```

File: pkg/plugins/discovery_unix_test.go [hunk 1]
```diff
@@ -97,7 +97,63 @@ func TestScan(t *testing.T) {
...
+
+	names, err = Scan()
+	if err != nil {
+		t.Fatal(err)
+	}
+	if len(names) != 1 {
+		t.Fatalf("expected 1 entry in result: %v", names)
+	}
+	if names[0] != "not-a-plugin" {
+		t.Fatal("expected plugin named `not-a-plugin`, got: %s", names[0])
```
Comment (thaJeztah) [inline pkg/plugins/discovery_unix_test.go]: `s/t.Fatal/t.Fatalf/`

**Review by thaJeztah — CHANGES_REQUESTED** [review]

**Comment by cpuguy83** [comment]
Fixed

File: pkg/plugins/discovery.go [hunk 2]
```diff
@@ -28,30 +29,54 @@ func newLocalRegistry() localRegistry {
...
+
+			ext := filepath.Ext(fi.Name())
+			switch ext {
+			case ".spec", ".json":
+			default:
+				continue
+			}
+
+			plugin := strings.TrimSuffix(fi.Name(), ext)
+			names = append(names, plugin)
```
Comment (thaJeztah) [inline pkg/plugins/discovery.go]: Perhaps put these lines inside the `switch ext {` above?

**Review by thaJeztah — CHANGES_REQUESTED** [review]
one nit, but otherwise looks good


ping @anusha-ragunathan @tiborvass PTAL

File: pkg/plugins/discovery.go [hunk 3]
```diff
@@ -81,7 +106,7 @@ func (l *localRegistry) Plugin(name string) (*Plugin, error) {
 			return readPluginInfo(name, p)
 		}
 	}
-	return nil, ErrNotFound
+	return nil, errors.Wrapf(ErrNotFound, "could not find plugin %s in v1 plugin registry", name)
```
Comment (anusha-ragunathan) [inline pkg/plugins/discovery.go]: can you add the plugin name to the pluginv2 error msg as well? https://github.com/moby/moby/blob/6d4d3c52ae7c3f910bfc7552a2a673a8338e5b9f/plugin/backend_linux.go#L527

**Comment by anusha-ragunathan** [comment]
Other than the nit, the rest LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by anusha-ragunathan** [comment]
LGTM
