### PR TITLE
Fix error handling

### LINKED ISSUE #41666: client: weird error handling
**Description**

Unknown error is missing `Unwrap()` implementation
```go
type errUnknown struct{ error }

func (errUnknown) Unknown() {}

func (e errUnknown) Cause() error {
	return e.error
}
```

Therefore in case of:
```go
ctx, cancel := context.WithCancel(context.Background())
cancel()

out, err := client.ImagePull(ctx, img, types.ImagePullOptions{})

errors.Is(err, context.Canceled) // false

err.String() // pulling image: Post \"http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/create?fromImage=<removed>&tag=latest\": context canceled"
```

In the same scenario, `err` is of type:
```go
type withStack struct {
	error
	*stack
}

func (w *withStack) Cause() error { return w.error }

// Unwrap provides compatibility for Go 1.13 error chains.
func (w *withStack) Unwrap() error { return w.error }
```
and `w.error`:
```go
type errUnknown struct{ error }
```

**Describe the results you expected:**

```go
ctx, cancel := context.WithCancel(context.Background())
cancel()

out, err := client.ImagePull(ctx, img, types.ImagePullOptions{})

errors.Is(err, context.Canceled) // true
```

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc92+dev
  GitCommit:        6e5320ffa83af3ea92e464e82f9e3ba665ff7541
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:                                                                                                                                 
 Debug Mode: false                                                                                                                      
                                                                                                                                                                                                                                     
 Server Version: 19.03.13                                                                                                               
 Storage Driver: overlay2                                                                                                               
  Backing Filesystem: extfs                                                                                                             
  Supports d_type: true                                                                                                                 
  Native Overlay Diff: true                                                                                                             
 Logging Driver: json-file                                                                                                              
 Cgroup Driver: cgroupfs                                                                                                                
 Plugins:                                                                                                                               
  Volume: local                                                                                                                         
  Network: bridge host ipvlan macvlan null overlay                                                                                      
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: 6e5320ffa83af3ea92e464e82f9e3ba665ff7541
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-52-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
```

### PR DESCRIPTION
**Pull request by kplachkov**
closes https://github.com/moby/moby/issues/41666

**- What I did**
added Unwrap()

**- How I did it**
magic

**- How to verify it**
https://github.com/moby/moby/pull/41667/commits/d5a79f81c7fc72cb3d746464f1a084384fe87817

**- Description for the changelog**
Fix error handling https://github.com/moby/moby/issues/41666

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Please squash commits

File: errdefs/defs.go [hunk 1]
```diff
@@ -51,6 +51,7 @@ type ErrNotImplemented interface {
 // ErrUnknown signals that the kind of error that occurred is not known.
 type ErrUnknown interface {
 	Unknown()
+	Unwrap() error
```
Comment (thaJeztah) [inline errdefs/defs.go:54]: My concern here would be that currently, the types are detected only by the `Unknown()` function being present (to match the interface). Adding `Unwrap()` to the interface could mean there's errors generated that are no nonger satisfying the interface, and thus longer detected as this error-type. (I recall having a discussion at some point to add `Error()` to the interface, so that it would only match if it implemented the `error` interface)

Does it actually have to be added to the _interface_, or only to the `errdefs/helpers` ?

/cc @cpuguy83

**Review by thaJeztah — CHANGES_REQUESTED** [review]

File: errdefs/defs.go (hunk 1 above)
Comment (cpuguy83) [reply errdefs/defs.go:54]: We do not need this define don the interface types.

If we do add `Unwrap()`, we should add it to all the implementations (but not the interfaces).

Comment (kplachkov) [reply errdefs/defs.go]: yes indeed, the `Unwrap()` is not needed in the interface

**Comment by thaJeztah** [comment]
Thanks! Could you perhaps add `Unwrap()` to all the errors in this file? I think the other error types would have the same problem as this one

**Comment by kplachkov** [comment]
any program that uses the standard logrus logger, set to debug, every time when the context is canceled the docker client will log this:
```
...
DEBU[2020-11-22T20:48:52+01:00] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_c
ode=-1
...
```
is this really necessary:
https://github.com/moby/moby/blob/d5a79f81c7fc72cb3d746464f1a084384fe87817/errdefs/http_helpers.go#L103-L106

if yes, why not use a separate logger instance?

**Comment by thaJeztah** [comment]
> any program that uses the standard logrus logger, set to debug, every time when the context is canceled the docker client will log this:

Hm, so that would indicate that the `context cancelled` case is not converted properly to a `ErrCancelled` https://github.com/moby/moby/blob/9f0b3f5609faf69537cdf1882c251deec6e9eb26/errdefs/defs.go#L56-L59

Do you know what code-path is hit that results in a cancelled context, but doesn't convert it to a known error-type?

**Comment by thaJeztah** [comment]
Interesting; wondering why ppc64le is hitting this error (is it not handling the rate-limits error?) https://ci-next.docker.com/public/blue/rest/organizations/jenkins/pipelines/moby/branches/PR-41667/runs/6/nodes/185/log/?start=0

```
[2020-11-21T15:40:42.889Z] + make bundles/buildx
[2020-11-21T15:40:43.182Z] make: command: Command not found
[2020-11-21T15:40:43.182Z] make: command: Command not found
[2020-11-21T15:40:43.182Z] mkdir bundles
[2020-11-21T15:40:43.182Z] docker build -f ${BUILDX_DOCKERFILE:-Dockerfile.buildx} -t "moby-buildx:${BUILDX_COMMIT:-latest}" \
[2020-11-21T15:40:43.182Z] 	--build-arg BUILDX_COMMIT \
[2020-11-21T15:40:43.182Z] 	--build-arg BUILDX_REPO \
[2020-11-21T15:40:43.182Z] 	--build-arg GOOS=$(if [ -n "" ]; then echo ; else go env GOHOSTOS || uname | awk '{print tolower($0)}' || true; fi) \
[2020-11-21T15:40:43.182Z] 	--build-arg GOARCH=$(if [ -n "" ]; then echo ; else go env GOHOSTARCH || true; fi) \
[2020-11-21T15:40:43.182Z] 	.
[2020-11-21T15:40:43.182Z] /bin/sh: 4: go: not found
[2020-11-21T15:40:43.182Z] /bin/sh: 5: go: not found
[2020-11-21T15:40:45.300Z] Sending build context to Docker daemon  57.21MB

[2020-11-21T15:40:45.300Z] Step 1/15 : ARG GO_VERSION=1.13.15
[2020-11-21T15:40:45.300Z] Step 2/15 : ARG BUILDX_COMMIT=v0.3.1
[2020-11-21T15:40:45.300Z] Step 3/15 : ARG BUILDX_REPO=https://github.com/docker/buildx.git
[2020-11-21T15:40:45.300Z] Step 4/15 : FROM golang:${GO_VERSION}-buster AS build
[2020-11-21T15:40:45.592Z] Get https://registry-1.docker.io/v2/library/golang/manifests/1.13.15-buster: unauthorized: incorrect username or password
[2020-11-21T15:40:45.592Z] Makefile:280: recipe for target 'bundles/buildx' failed
[2020-11-21T15:40:45.592Z] make: *** [bundles/buildx] Error 1
script returned exit code 2
```

s390x also hitting some weird error; https://ci-next.docker.com/public/blue/rest/organizations/jenkins/pipelines/moby/branches/PR-41667/runs/6/nodes/149/log/?start=0

```
[2020-11-21T15:40:33.435Z] + docker build --force-rm --build-arg APT_MIRROR -t docker:e8af3f79032b0e21a6cce3fc5dcee824d3365926 .
[2020-11-21T15:40:33.435Z] #1 [internal] load .dockerignore
[2020-11-21T15:40:33.435Z] #1 transferring context: 87B done
[2020-11-21T15:40:33.435Z] #1 DONE 0.0s
[2020-11-21T15:40:33.435Z]
[2020-11-21T15:40:33.435Z] #2 [internal] load build definition from Dockerfile
[2020-11-21T15:40:33.435Z] #2 transferring dockerfile: 16.58kB done
[2020-11-21T15:40:33.435Z] #2 DONE 0.0s
[2020-11-21T15:40:33.435Z]
[2020-11-21T15:40:33.435Z] #3 resolve image config for docker.io/docker/dockerfile:1.1.7-experimental
[2020-11-21T15:40:33.731Z] #3 ERROR: failed to fetch oauth token: unexpected status: 401 Unauthorized
[2020-11-21T15:40:33.731Z] ------
[2020-11-21T15:40:33.731Z]  > resolve image config for docker.io/docker/dockerfile:1.1.7-experimental:
[2020-11-21T15:40:33.731Z] ------
[2020-11-21T15:40:33.731Z] failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: failed to fetch oauth token: unexpected status: 401 Unauthorized
script returned exit code 1
```

Let me kick CI again

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM
