### PR TITLE
rootless: properly support `--net=host` and localhost registries

### LINKED ISSUE #40865: --net host does not allow access to open sockets with rootless Docker, except from other containers on the same host
**Description**
When using rootless Docker, `--net host` does not allow for accessing ports opened inside a container, except from another container.

**Steps to reproduce the issue:**
1. Start a container with `--net host`.
2. `netcat -l 12345`
3. From outside the container, on the same host, `netcat localhost 12345`

**Describe the results you received:**
`netcat` does not allow for sending messages.

**Describe the results you expected:**
`netcat` should work as usual and forward any line typed on the host to the container, like it happens when running `netcat -l 12345` followed by `netcat localhost 12345` on the host itself.

**Additional information you deem important (e.g. issue happens only occasionally):**
1. I originally noticed this with [ROS](https://hub.docker.com/_/ros/): if you start `roscore` on a container and then `curl http://localhost:11311` from the host, curl fails with a "connection refused"  message, while if you run the same command from inside a different container, an (expected) HTML error page is returned, so this means other containers can access open ports on containers, but not the host. I could not reproduce this behavior with netcat, though. 
2. With normal ("rootful") Docker, ROS works as expected.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:22:56 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:30:32 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 50
  Running: 1
  Paused: 0
  Stopped: 49
 Images: 98
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: none
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
  rootless
 Kernel Version: 5.4.0-26-generic
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.677GiB
 Name: nymeria
 ID: 24YU:BPGQ:GEO6:VSBU:37AZ:VCOW:6UCB:WJ4V:335Y:25VV:J5C7:WZPO
 Docker Root Dir: /home/kmfrick/.local/share/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
N/A

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Now `dockerd-rootless.sh` launches RootlessKit with `--detach-netns`
so as to run the daemon in the host network namespace.

The libnetwork namespaces are allocated inside the "detached" netns
(`$ROOTLESSKIT_STATE_DIR/netns`) that is associated with slirp4netns,
vpnkit, pasta, etc., as the rootless daemon has no `CAP_NET_ADMIN` for
the host network namespace.

This will enable:
- Accelerated (and deflaked) `docker pull`, `docker push`, `docker build`, etc
- Proper support for `docker pull 127.0.0.1:.../...`
- Proper support for `dockern run --net=host`

See also:
- rootless-containers/rootlesskit#379
- containerd/nerdctl#2723

NOTE: libnetwork contains code generated by Claude Code
- - -

**- What I did**
- Accelerated (and deflaked) `docker pull`, `docker push`, `docker build`, etc
- Proper support for `docker pull 127.0.0.1:.../...`
- Proper support for `dockern run --net=host`

**- How I did it**
Execute the rootless daemon in the host network namespace.

Prior to this PR, the daemon was executed in a network namespace created by RootlessKit.

**- How to verify it**
CI should be green

**- Description for the changelog**

```markdown changelog
Rootless: Properly support `--net=host` and localhost registries
```

**- A picture of a cute animal (not mandatory but encouraged)**
🐧

### CODE REVIEW

File: contrib/dockerd-rootless.sh [hunk 1]
```diff
@@ -15,6 +15,9 @@
 # * DOCKERD_ROOTLESS_ROOTLESSKIT_PORT_DRIVER=(builtin|slirp4netns|implicit): the rootlesskit port driver. Defaults to "builtin".
 # * DOCKERD_ROOTLESS_ROOTLESSKIT_SLIRP4NETNS_SANDBOX=(auto|true|false): whether to protect slirp4netns with a dedicated mount namespace. Defaults to "auto".
 # * DOCKERD_ROOTLESS_ROOTLESSKIT_SLIRP4NETNS_SECCOMP=(auto|true|false): whether to protect slirp4netns with seccomp. Defaults to "auto".
+# * DOCKERD_ROOTLESS_ROOTLESSKIT_DETACH_NETNS=(auto|true|false): whether to launch rootlesskit with the "detach-netns" mode.
+#   Defaults to "auto", which is resolved to "true" if RootlessKit >= 2.0 is installed.
+#   The "detached-netns" mode accelerates `docker (pull|push|build)` and enables `docker run --net=host`
```
Comment (AkihiroSuda) [inline contrib/dockerd-rootless.sh:20]: (TODO: CI should cover `false` too)

**Comment by AkihiroSuda** [comment]
https://github.com/moby/moby/actions/runs/7570750383/job/20616830214?pr=47103

```
=== Failed
=== FAIL: amd64.integration.capabilities TestNoNewPrivileges/CapabilityRequested=true (0.00s)
    capabilities_linux_test.go:83: assertion failed: error is not nil: Error response from daemon: No such image: captest:latest
    --- FAIL: TestNoNewPrivileges/CapabilityRequested=true (0.00s)

=== FAIL: amd64.integration.capabilities TestNoNewPrivileges/CapabilityRequested=false (0.00s)
    capabilities_linux_test.go:83: assertion failed: error is not nil: Error response from daemon: No such image: captest:latest
    --- FAIL: TestNoNewPrivileges/CapabilityRequested=false (0.00s)

=== FAIL: amd64.integration.capabilities TestNoNewPrivileges (0.29s)
```

```
=== Failed
=== FAIL: amd64.integration.image TestImagePullNonExisting/asdfasdf:latest (0.00s)
    pull_test.go:187: assertion failed: expected error to contain "pull access denied for asdfasdf, repository does not exist or may require 'docker login'", got "Error response from daemon: Get \"https://registry-1.docker.io/v2/\": dial tcp: lookup registry-1.docker.io on 168.63.129.16:53: dial udp 168.63.129.16:53: connect: network is unreachable"
        Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 168.63.129.16:53: dial udp 168.63.129.16:53: connect: network is unreachable
    --- FAIL: TestImagePullNonExisting/asdfasdf:latest (0.00s)

=== FAIL: amd64.integration.image TestImagePullNonExisting/library/asdfasdf:latest (0.00s)
    pull_test.go:187: assertion failed: expected error to contain "pull access denied for asdfasdf, repository does not exist or may require 'docker login'", got "Error response from daemon: Get \"https://registry-1.docker.io/v2/\": dial tcp: lookup registry-1.docker.io on 168.63.129.16:53: dial udp 168.63.129.16:53: connect: network is unreachable"
        Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 168.63.129.16:53: dial udp 168.63.129.16:53: connect: network is unreachable
    --- FAIL: TestImagePullNonExisting/library/asdfasdf:latest (0.00s)

=== FAIL: amd64.integration.image TestImagePullNonExisting/asdfasdf (0.00s)
    pull_test.go:187: assertion failed: expected error to contain "pull access denied for asdfasdf, repository does not exist or may require 'docker login'", got "Error response from daemon: Get \"https://registry-1.docker.io/v2/\": dial tcp: lookup registry-1.docker.io on 168.63.129.16:53: dial udp 168.63.129.16:53: connect: network is unreachable"
        Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 168.63.129.16:53: dial udp 168.63.129.16:53: connect: network is unreachable
    --- FAIL: TestImagePullNonExisting/asdfasdf (0.00s)

=== FAIL: amd64.integration.image TestImagePullNonExisting/asdfasdf:foobar (0.01s)
    pull_test.go:187: assertion failed: expected error to contain "pull access denied for asdfasdf, repository does not exist or may require 'docker login'", got "Error response from daemon: Get \"https://registry-1.docker.io/v2/\": dial tcp: lookup registry-1.docker.io on 168.63.129.16:53: dial udp 168.63.129.16:53: connect: network is unreachable"
        Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 168.63.129.16:53: dial udp 168.63.129.16:53: connect: network is unreachable
    --- FAIL: TestImagePullNonExisting/asdfasdf:foobar (0.01s)

=== FAIL: amd64.integration.image TestImagePullNonExisting/library/asdfasdf (0.00s)
    pull_test.go:187: assertion failed: expected error to contain "pull access denied for asdfasdf, repository does not exist or may require 'docker login'", got "Error response from daemon: Get \"https://registry-1.docker.io/v2/\": dial tcp: lookup registry-1.docker.io on 168.63.129.16:53: dial udp 168.63.129.16:53: connect: network is unreachable"
        Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 168.63.129.16:53: dial udp 168.63.129.16:53: connect: network is unreachable
    --- FAIL: TestImagePullNonExisting/library/asdfasdf (0.00s)

=== FAIL: amd64.integration.image TestImagePullNonExisting/library/asdfasdf:foobar (0.00s)
    pull_test.go:187: assertion failed: expected error to contain "pull access denied for asdfasdf, repository does not exist or may require 'docker login'", got "Error response from daemon: Get \"https://registry-1.docker.io/v2/\": dial tcp: lookup registry-1.docker.io on 168.63.129.16:53: dial udp 168.63.129.16:53: connect: network is unreachable"
        Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 168.63.129.16:53: dial udp 168.63.129.16:53: connect: network is unreachable
    --- FAIL: TestImagePullNonExisting/library/asdfasdf:foobar (0.00s)

=== FAIL: amd64.integration.image TestImagePullNonExisting (0.01s)
```

```
=== Failed
=== FAIL: amd64.integration.system TestLoginFailsWithBadCredentials (0.39s)
    login_test.go:28: assertion failed: expected error to contain "unauthorized: incorrect username or password", got "Error response from daemon: Get \"https://registry-1.docker.io/v2/\": dial tcp: lookup registry-1.docker.io on 168.63.129.16:53: dial udp 168.63.129.16:53: connect: network is unreachable"
        Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 168.63.129.16:53: dial udp 168.63.129.16:53: connect: network is unreachable
```

- - -

```
$ docker --context=rootless pull hello-world
                         
Using default tag: latest
latest: Pulling from library/hello-world
Digest: sha256:4bd78111b6914a99dbc560e6a20eab57ff6655aea4a80c50b0c5491968cbc2e6
Status: Image is up to date for hello-world:latest
docker.io/library/hello-world:latest

$ docker --context=rootless run --rm hello-world

Hello from Docker!
...

$ docker --context=rootless pull hello-world
Using default tag: latest
Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp [2600:1f18:2148:bc00:41e1:f57f:e2e2:5e54]:443: connect: network is unreachable
```

It looks like the daemon accidentally leaves the host network namespace after running a container


~**EDIT**: this issue happens with Go 1.22.8, but apparently doesn't with Go 1.23.2~  Still happens https://github.com/moby/moby/actions/runs/11443077600/job/31869250145?pr=47103

**Comment by AkihiroSuda** [comment]
Some tests are still failing even with Go 1.23


https://github.com/moby/moby/actions/runs/11443077600/job/31869250145?pr=47103

```
=== FAIL: amd64.integration.capabilities TestNoNewPrivileges/CapabilityRequested=true (0.00s)
    capabilities_linux_test.go:83: assertion failed: error is not nil: Error response from daemon: No such image: captest:latest
    --- FAIL: TestNoNewPrivileges/CapabilityRequested=true (0.00s)

=== FAIL: amd64.integration.capabilities TestNoNewPrivileges/CapabilityRequested=false (0.00s)
    capabilities_linux_test.go:83: assertion failed: error is not nil: Error response from daemon: No such image: captest:latest
    --- FAIL: TestNoNewPrivileges/CapabilityRequested=false (0.00s)
```

```
=== FAIL: amd64.integration.image TestImagePullNonExisting/library/asdfasdf:foobar (0.01s)
    pull_test.go:191: assertion failed: expected error to contain "pull access denied for asdfasdf, repository does not exist or may require 'docker login'", got "Error response from daemon: Get \"https://registry-1.docker.io/v2/\": dial tcp: lookup registry-1.docker.io on 168.63.129.16:53: dial udp 168.63.129.16:53: connect: network is unreachable"
        Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 168.63.129.16:53: dial udp 168.63.129.16:53: connect: network is unreachable
    pull_test.go:192: assertion failed: error is Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 168.63.129.16:53: dial udp 168.63.129.16:53: connect: network is unreachable (errdefs.errSystem), not errdefs.IsNotFound
    --- FAIL: TestImagePullNonExisting/library/asdfasdf:foobar (0.01s)

=== FAIL: amd64.integration.image TestImagePullNonExisting/asdfasdf:latest (0.01s)
    pull_test.go:191: assertion failed: expected error to contain "pull access denied for asdfasdf, repository does not exist or may require 'docker login'", got "Error response from daemon: Get \"https://registry-1.docker.io/v2/\": dial tcp: lookup registry-1.docker.io on 168.63.129.16:53: dial udp 168.63.129.16:53: connect: network is unreachable"
        Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 168.63.129.16:53: dial udp 168.63.129.16:53: connect: network is unreachable
    pull_test.go:192: assertion failed: error is Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 168.63.129.16:53: dial udp 168.63.129.16:53: connect: network is unreachable (errdefs.errSystem), not errdefs.IsNotFound
    --- FAIL: TestImagePullNonExisting/asdfasdf:latest (0.01s)

=== FAIL: amd64.integration.image TestImagePullNonExisting/asdfasdf:foobar (0.01s)
    pull_test.go:191: assertion failed: expected error to contain "pull access denied for asdfasdf, repository does not exist or may require 'docker login'", got "Error response from daemon: Get \"https://registry-1.docker.io/v2/\": dial tcp: lookup registry-1.docker.io on 168.63.129.16:53: dial udp 168.63.129.16:53: connect: network is unreachable"
        Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 168.63.129.16:53: dial udp 168.63.129.16:53: connect: network is unreachable
    pull_test.go:192: assertion failed: error is Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 168.63.129.16:53: dial udp 168.63.129.16:53: connect: network is unreachable (errdefs.errSystem), not errdefs.IsNotFound
    --- FAIL: TestImagePullNonExisting/asdfasdf:foobar (0.01s)

=== FAIL: amd64.integration.image TestImagePullNonExisting/asdfasdf (0.01s)
    pull_test.go:191: assertion failed: expected error to contain "pull access denied for asdfasdf, repository does not exist or may require 'docker login'", got "Error response from daemon: Get \"https://registry-1.docker.io/v2/\": dial tcp: lookup registry-1.docker.io on 168.63.129.16:53: dial udp 168.63.129.16:53: connect: network is unreachable"
        Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 168.63.129.16:53: dial udp 168.63.129.16:53: connect: network is unreachable
    pull_test.go:192: assertion failed: error is Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 168.63.129.16:53: dial udp 168.63.129.16:53: connect: network is unreachable (errdefs.errSystem), not errdefs.IsNotFound
    --- FAIL: TestImagePullNonExisting/asdfasdf (0.01s)

=== FAIL: amd64.integration.image TestImagePullNonExisting/library/asdfasdf (0.01s)
    pull_test.go:191: assertion failed: expected error to contain "pull access denied for asdfasdf, repository does not exist or may require 'docker login'", got "Error response from daemon: Get \"https://registry-1.docker.io/v2/\": dial tcp: lookup registry-1.docker.io on 168.63.129.16:53: dial udp 168.63.129.16:53: connect: network is unreachable"
        Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 168.63.129.16:53: dial udp 168.63.129.16:53: connect: network is unreachable
    pull_test.go:192: assertion failed: error is Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 168.63.129.16:53: dial udp 168.63.129.16:53: connect: network is unreachable (errdefs.errSystem), not errdefs.IsNotFound
    --- FAIL: TestImagePullNonExisting/library/asdfasdf (0.01s)

=== FAIL: amd64.integration.image TestImagePullNonExisting/library/asdfasdf:latest (1.03s)
    pull_test.go:191: assertion failed: expected error to contain "pull access denied for asdfasdf, repository does not exist or may require 'docker login'", got "Error response from daemon: Get \"https://registry-1.docker.io/v2/\": dial tcp [2600:1f18:2148:bc00:8d61:9b62:40aa:8bb8]:443: connect: network is unreachable"
        Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp [2600:1f18:2148:bc00:8d61:9b62:40aa:8bb8]:443: connect: network is unreachable
    pull_test.go:192: assertion failed: error is Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp [2600:1f18:2148:bc00:8d61:9b62:40aa:8bb8]:443: connect: network is unreachable (errdefs.errSystem), not errdefs.IsNotFound
    --- FAIL: TestImagePullNonExisting/library/asdfasdf:latest (1.03s)
```

**Comment by AkihiroSuda** [comment]
Looks like the daemon threads are associated with random netns

```console
$ docker --context=rootless run --name hello hello-world

$ docker --context=rootless pull hello-world
Using default tag: latest
latest: Pulling from library/hello-world
Digest: sha256:d211f485f2dd1dee407a80973c8f129f00d54604d2c90732e8e320e5038a0348
Status: Image is up to date for hello-world:latest
docker.io/library/hello-world:latest

$ docker --context=rootless pull hello-world
Using default tag: latest
Error response from daemon: Head "https://registry-1.docker.io/v2/library/hello-world/manifests/latest": Get "https://auth.docker.io/token?account=akihirosuda&scope=repository%3Alibrary%2Fhello-world%3Apull&service=registry.docker.io": dial tcp: lookup auth.docker.io: no such host

$ docker --context=rootless pull hello-world
Using default tag: latest
Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io: no such host

$ docker --context=rootless pull hello-world
Using default tag: latest
latest: Pulling from library/hello-world
Digest: sha256:d211f485f2dd1dee407a80973c8f129f00d54604d2c90732e8e320e5038a0348
Status: Image is up to date for hello-world:latest
docker.io/library/hello-world:latest
```
```
$ readlink /proc/$(pgrep -x -u $(id -u) dockerd)/task/*/ns/net | sort
net:[4026531840]
net:[4026531840]
net:[4026531840]
net:[4026531840]
net:[4026531840]
net:[4026531840]
net:[4026531840]
net:[4026531840]
net:[4026531840]
net:[4026531840]
net:[4026531840]
net:[4026532722]
```

**Comment by AkihiroSuda** [comment]
The PR was stuck for more than two years due to the goroutine issue above, but Claude Code now solved it 🤖

**Comment by AkihiroSuda** [comment]
Still lots of failures https://github.com/moby/moby/actions/runs/23023562615/job/66866213759?pr=47103

```
=== RUN   TestNetworkNat
    nat_test.go:30: assertion failed: error is not nil: Error response from daemon: failed to set up container networking: driver failed programming external connectivity on endpoint server-TestNetworkNat (48354ab8df8fb718e161b5ed11ea9e14e61a88634b76cafc5aa909fd215dbb0c): error while calling RootlessKit PortManager.AddPort(): listen tcp4 0.0.0.0:8080: bind: address already in use
--- FAIL: TestNetworkNat (0.25s)
=== RUN   TestNetworkLocalhostTCPNat
    nat_test.go:60: assertion failed: error is not nil: Error response from daemon: failed to set up container networking: driver failed programming external connectivity on endpoint server-TestNetworkLocalhostTCPNat (4f1a7c8bbb5d319988f8b7c5e72c6dd0c57be18f177bb5bae77622bec86b0ddd): error while calling RootlessKit PortManager.AddPort(): listen tcp4 0.0.0.0:8081: bind: address already in use
--- FAIL: TestNetworkLocalhostTCPNat (0.24s)
```

```
=== RUN   TestRenameAnonymousContainer
    rename_test.go:151: assertion failed: 0 (int) != 1 (inspect.Container.State.ExitCode int): container 062730b987a254e6d4c68cf2f1f04adae53286f4597d28d434abefdc70cd16e9 exited with the wrong exitcode: 
--- FAIL: TestRenameAnonymousContainer (0.86s)
```

```
=== RUN   TestHostnameDnsResolution
    run_linux_test.go:102: assertion failed: 
        --- ←
        +++ →
        @@ -1 +1,2 @@
        +ping: bad address 'foobar'
         
        
    run_linux_test.go:103: assertion failed: 0 (int) != 1 (res.ExitCode int)
--- FAIL: TestHostnameDnsResolution (0.45s)
```

```
=== RUN   TestDaemonDNSFallback
    dns_test.go:37: polling check failed: expected exit code 0, got 1
--- FAIL: TestDaemonDNSFallback (3.05s)
=== RUN   TestIntDNSAsExtDNS
=== RUN   TestIntDNSAsExtDNS/only_self
    dns_test.go:91: assertion failed: string ";; connection timed out; no servers could be reached\n\n" does not contain "SERVFAIL"
=== RUN   TestIntDNSAsExtDNS/self_then_ext
    dns_test.go:90: assertion failed: 1 (res.ExitCode int) != 0 (tc.expExitCode int)
    dns_test.go:91: assertion failed: string ";; connection timed out; no servers could be reached\n\n" does not contain "Non-authoritative answer"
--- FAIL: TestIntDNSAsExtDNS (2.42s)
    --- FAIL: TestIntDNSAsExtDNS/only_self (0.35s)
    --- FAIL: TestIntDNSAsExtDNS/self_then_ext (0.38s)
```

```
=== RUN   TestPointToPoint
=== RUN   TestPointToPoint/inhibit_ipv4
    bridge_linux_test.go:421: assertion failed: 1 (res.ExitCode int) != 0 (int)
    bridge_linux_test.go:422: assertion failed: 25 (int) != 0 (int)
    bridge_linux_test.go:423: assertion failed: string "" does not contain "1 packets transmitted, 1 packets received"
=== RUN   TestPointToPoint/isolated
    bridge_linux_test.go:421: assertion failed: 1 (res.ExitCode int) != 0 (int)
    bridge_linux_test.go:422: assertion failed: 25 (int) != 0 (int)
    bridge_linux_test.go:423: assertion failed: string "" does not contain "1 packets transmitted, 1 packets received"
--- FAIL: TestPointToPoint (2.75s)
    --- FAIL: TestPointToPoint/inhibit_ipv4 (0.53s)
    --- FAIL: TestPointToPoint/isolated (0.51s)
```

```
--- FAIL: TestPublishedPortAlreadyInUse (0.25s)
=== RUN   TestAllPortMappingsAreReturned
    bridge_linux_test.go:564: assertion failed: error is not nil: Error response from daemon: failed to set up container networking: driver failed programming external connectivity on endpoint elated_galois (3d3751bddf8016b09d8275626dd07aa4cdd60dabada78641366b790ef91d1761): error while calling RootlessKit PortManager.AddPort(): listen tcp4 0.0.0.0:8000: bind: address already in use
--- FAIL: TestAllPortMappingsAreReturned (3.20s)
```

```
--- FAIL: TestBridgeICC (13.82s)
    --- FAIL: TestBridgeICC/IPv4_non-internal_network (0.63s)
    --- FAIL: TestBridgeICC/IPv4_internal_network (0.53s)
    --- FAIL: TestBridgeICC/IPv6_ULA_on_non-internal_network (0.79s)
    --- FAIL: TestBridgeICC/IPv6_ULA_on_internal_network (0.60s)
    --- PASS: TestBridgeICC/IPv6_link-local_address_on_non-internal_network (0.76s)
    --- PASS: TestBridgeICC/IPv6_link-local_address_on_internal_network (0.57s)
    --- FAIL: TestBridgeICC/IPv6_link-local_address_on_non-internal_network_ping_by_name (0.77s)
    --- FAIL: TestBridgeICC/IPv6_nonstandard_link-local_subnet_on_non-internal_network_ping_by_name (0.82s)
    --- PASS: TestBridgeICC/IPv6_non-internal_network_with_SLAAC_LL_address (2.83s)
    --- PASS: TestBridgeICC/IPv6_internal_network_with_SLAAC_LL_address (1.82s)
```

```
--- FAIL: TestInterNetworkDirectRouting (26.77s)
    --- FAIL: TestInterNetworkDirectRouting/server=nat/proxy=true (2.14s)
    --- FAIL: TestInterNetworkDirectRouting/server=nat/proxy=false (4.15s)
    --- PASS: TestInterNetworkDirectRouting/server=routed/proxy=true (7.06s)
        --- PASS: TestInterNetworkDirectRouting/server=routed/proxy=true/w (0.00s)
            --- PASS: TestInterNetworkDirectRouting/server=routed/proxy=true/w/ipv4/pub (0.41s)
            --- PASS: TestInterNetworkDirectRouting/server=routed/proxy=true/w/ipv6/pub (0.43s)
            --- PASS: TestInterNetworkDirectRouting/server=routed/proxy=true/w/ipv4/unpub (3.40s)
            --- PASS: TestInterNetworkDirectRouting/server=routed/proxy=true/w/ipv6/unpub (3.41s)
    --- PASS: TestInterNetworkDirectRouting/server=routed/proxy=false (8.14s)
        --- PASS: TestInterNetworkDirectRouting/server=routed/proxy=false/w (0.00s)
            --- PASS: TestInterNetworkDirectRouting/server=routed/proxy=false/w/ipv6/pub (0.39s)
            --- PASS: TestInterNetworkDirectRouting/server=routed/proxy=false/w/ipv4/pub (0.40s)
            --- PASS: TestInterNetworkDirectRouting/server=routed/proxy=false/w/ipv6/unpub (3.43s)
            --- PASS: TestInterNetworkDirectRouting/server=routed/proxy=false/w/ipv4/unpub (3.45s)
    --- FAIL: TestInterNetworkDirectRouting/server=nat-unprotected/proxy=true (3.10s)
    --- FAIL: TestInterNetworkDirectRouting/server=nat-unprotected/proxy=false (2.12s)
```

```
--- FAIL: TestDisableIPv6OnInterface (3.17s)
    --- FAIL: TestDisableIPv6OnInterface/bridge (0.23s)
    --- FAIL: TestDisableIPv6OnInterface/testnet (0.25s)
```

```
=== RUN   TestContainerDisabledIPv6
    bridge_linux_test.go:1451: assertion failed: 1 (res.ExitCode int) != 0 (int)
    bridge_linux_test.go:1452: assertion failed: string "" does not contain "1 packets transmitted, 1 packets received"
    bridge_linux_test.go:1453: assertion failed: 
        --- ←
        +++ →
        @@ -1,2 +1 @@
        -ping: bad address 'ctrNo6'
         
        
--- FAIL: TestContainerDisabledIPv6 (3.51s)
```

```
=== RUN   TestDNSNamesForNonSwarmScopedNetworks
    bridge_linux_test.go:2185: assertion failed: 1 (res.ExitCode int) != 0 (int): exit code: 1, expected 0; stdout:
        ;; connection timed out; no servers could be reached
        
        
--- FAIL: TestDNSNamesForNonSwarmScopedNetworks (8.26s)
```

```
=== RUN   TestPublishAllWithNilPortBindings
    build.go:57: Step 1/2 : FROM busybox
    build.go:57: 
        
    build.go:57:  ---> 328dac05c07e
        
    build.go:57: Step 2/2 : EXPOSE 80/tcp
    build.go:57: 
        
    build.go:57:  ---> Running in 0e483e694619
        
    build.go:57:  ---> 85830a13cc52
        
    build.go:57: 
        
    build.go:57: Successfully built 85830a13cc52
        
    bridge_linux_test.go:2277: assertion failed: error is not nil: Error response from daemon: failed to set up container networking: driver failed programming external connectivity on endpoint reverent_nightingale (079682f4291b908a33b9bd91e3400bed8113ca3fe68f0c08efa95d49c4c7c08b): error while calling RootlessKit PortManager.AddPort(): listen tcp4 0.0.0.0:32768: bind: address already in use
--- FAIL: TestPublishAllWithNilPortBindings (0.44s)
```

```
=== RUN   TestDisableNAT
=== RUN   TestDisableNAT/defaults
    port_mapping_linux_test.go:124: assertion failed: error is not nil: Error response from daemon: failed to set up container networking: driver failed programming external connectivity on endpoint admiring_hamilton (980d88f394e4b1d3f51e1f263ea80a7c6b6ea2a00d7368a0cc45e5370b02beb8): error while calling RootlessKit PortManager.AddPort(): listen tcp4 0.0.0.0:8080: bind: address already in use
=== RUN   TestDisableNAT/nat4_routed6
    port_mapping_linux_test.go:124: assertion failed: error is not nil: Error response from daemon: failed to set up container networking: driver failed programming external connectivity on endpoint serene_greider (b325eff1c70a9a6e4e31df7ad9e21f9a20ab6fd5a67eac2094e87d1a52cff902): error while calling RootlessKit PortManager.AddPort(): listen tcp4 0.0.0.0:8080: bind: address already in use
=== RUN   TestDisableNAT/nat6_routed4
    port_mapping_linux_test.go:124: assertion failed: error is not nil: Error response from daemon: failed to set up container networking: driver failed programming external connectivity on endpoint gracious_proskuriakova (06ef9bc617e6cf7331eda9efe8341eea3b818bf2b6585a960b4e51fc29573e87): error while calling RootlessKit PortManager.AddPort(): listen tcp6 [::]:8080: bind: address already in use
--- FAIL: TestDisableNAT (3.16s)
    --- FAIL: TestDisableNAT/defaults (0.47s)
    --- FAIL: TestDisableNAT/nat4_routed6 (0.50s)
    --- FAIL: TestDisableNAT/nat6_routed4 (0.48s)
```

[...]

**Comment by AkihiroSuda** [comment]
Rebased

**Comment by thaJeztah** [comment]
Changed the milestone; assuming this is not a breaking change, right?

**Comment by AkihiroSuda** [comment]
> Changed the milestone; assuming this is not a breaking change, right?

Assumed so, but [Hyrum's Law](https://www.hyrumslaw.com) may potentially apply 🤷‍♂️

**Comment by thaJeztah** [comment]
Yeah, I think we should be able to ignore Hyrum for now; we'll see if there's a large outcry


Oh! Let me put this on the v29.3.2 milestone; I think we'll be renaming that one (easier than "moving")

File: daemon/internal/rootless/specconv/specconv_linux.go [hunk 2]
```diff
@@ -120,6 +122,31 @@ func toRootless(spec *specs.Spec, v2Controllers []string, currentOOMScoreAdj int
...
+		}
+		if netHost {
+			// For rootless + host netns, we can't mount sysfs.
+			// We can't (non-recursively) bind mount /sys, either.
+			//
+			// TODO: consider to just rbind /sys from the host with rro,
+			// when rro is available (kernel >= 5.12, runc >= 1.1).
+			//
+			// Relevant: https://github.com/moby/buildkit/blob/v0.12.4/util/rootless/specconv/specconv_linux.go#L15-L34
+			// https://github.com/containerd/nerdctl/pull/2723
```
Comment (thaJeztah) [inline daemon/internal/rootless/specconv/specconv_linux.go:143]: Thanks for the comments with links; always useful as bread-crumb ❤️ 

Should we create a tracking-ticket for the TODO? (kernel-versions came up recently; we should probably look if we can do feature-detection if we don't have that yet, but also look what distros are still on < v5(.12)

File: daemon/internal/rootless/specconv/specconv_linux.go [hunk 3]
```diff
@@ -139,7 +166,11 @@ func isHostNS(spec *specs.Spec, nsType specs.LinuxNamespaceType) (bool, error) {
 			if err != nil {
 				return false, err
 			}
-			selfNS, err := os.Readlink(filepath.Join("/proc/self/ns", string(nsType)))
+			procfsNSType := string(nsType)
+			if nsType == specs.NetworkNamespace {
+				procfsNSType = "net"
+			}
+			selfNS, err := os.Readlink(filepath.Join("/proc/self/ns", procfsNSType))
```
Comment (thaJeztah) [inline daemon/internal/rootless/specconv/specconv_linux.go:173]: WAIT: did we set the wrong value all this time, and nothing ... failed?


It's really unfortunate for the spec to use a name not matching the  name used in `/proc` (for this one only!). Wondering if we can somehow fix that (or have a utility in the specs repo).

File: daemon/internal/rootless/rootless_linux.go [hunk 4]
```diff
@@ -0,0 +1,139 @@
+// From https://github.com/containerd/nerdctl/pull/2723
```
Comment (thaJeztah) [inline daemon/internal/rootless/rootless_linux.go]: Wondering if there'd be some good place to keep these if they're used in multiple projects; not sure where'd be the best place though.

File: daemon/libnetwork/internal/nftables/nft_exec_linux.go [hunk 5]
```diff
@@ -19,7 +20,21 @@ func (t *table) nftApply(ctx context.Context, nftCmd []byte) error {
 	ctx, span := otel.Tracer("").Start(ctx, spanPrefix+".nftApply.exec")
 	defer span.End()
 
-	cmd := exec.Command(nftPath, "-f", "-")
+	cmdPath := nftPath
+	cmdArgs := []string{nftPath, "-f", "-"}
+	detachedNetNS, detachedErr := rootless.DetachedNetNS()
+	if detachedErr != nil {
```
Comment (thaJeztah) [inline daemon/libnetwork/internal/nftables/nft_exec_linux.go]: Really tiny nit (not a blocker, unless you're updating) this could probably just use `err` as name; "special" names always make me go look "where else is this needed?"


```suggestion
	detachedNetNS, err := rootless.DetachedNetNS()
	if err != nil {
```

File: daemon/libnetwork/internal/nftables/nft_exec_linux.go [hunk 6]
```diff
@@ -19,7 +20,21 @@ func (t *table) nftApply(ctx context.Context, nftCmd []byte) error {
...
+		return fmt.Errorf("could not check for detached netns: %w", detachedErr)
+	}
+	if detachedNetNS != "" && !rootless.InSandboxNS() {
+		nsenterPath, err := exec.LookPath("nsenter")
+		if err != nil {
+			return fmt.Errorf("nsenter not found: %w", err)
+		}
+		cmdPath = nsenterPath
+		cmdArgs = append([]string{nsenterPath, "-n" + detachedNetNS, "-F", "--"}, cmdArgs...)
```
Comment (thaJeztah) [inline daemon/libnetwork/internal/nftables/nft_exec_linux.go:40]: Should `"-n" + detachedNetNS` have a space (or `=`) after the flag-name, or should they be two elements?


```suggestion
		cmdArgs = append([]string{nsenterPath, "-n", detachedNetNS, "-F", "--"}, cmdArgs...)
```

File: daemon/libnetwork/iptables/iptables.go [hunk 7]
```diff
@@ -364,7 +364,20 @@ func (iptable IPTable) raw(args ...string) ([]byte, error) {
 	log.G(context.TODO()).Debugf("%s, %v", path, args)
 
 	startTime := time.Now()
-	output, err := exec.Command(path, args...).CombinedOutput()
+	cmd := exec.Command(path, args...)
+	detachedNetNS, detachedErr := rootless.DetachedNetNS()
+	if detachedErr != nil {
```
Comment (thaJeztah) [inline daemon/libnetwork/iptables/iptables.go]: Same nit here (non-blocking)

```suggestion
	detachedNetNS, err := rootless.DetachedNetNS()
	if err != nil {
```

File: daemon/libnetwork/iptables/iptables.go [hunk 8]
```diff
@@ -364,7 +364,20 @@ func (iptable IPTable) raw(args ...string) ([]byte, error) {
...
+		return nil, fmt.Errorf("could not check for detached netns: %w", detachedErr)
+	}
+	if detachedNetNS != "" && !rootless.InSandboxNS() {
+		nsenterPath, err := exec.LookPath("nsenter")
+		if err != nil {
+			return nil, fmt.Errorf("nsenter not found: %w", err)
+		}
+		cmd.Args = append([]string{nsenterPath, "-n" + detachedNetNS, "-F", "--"}, cmd.Args...)
```
Comment (thaJeztah) [inline daemon/libnetwork/iptables/iptables.go:377]: And same question 😅 

```suggestion
		cmd.Args = append([]string{nsenterPath, "-n", detachedNetNS, "-F", "--"}, cmd.Args...)
```

File: daemon/libnetwork/internal/nftables/nft_exec_linux.go [hunk 9]
```diff
@@ -19,7 +20,21 @@ func (t *table) nftApply(ctx context.Context, nftCmd []byte) error {
...
+	}
+	cmd := exec.Command(cmdPath, cmdArgs[1:]...)
```
Comment (thaJeztah) [inline daemon/libnetwork/internal/nftables/nft_exec_linux.go]: Nit: looks like we have a context available; perhaps we should pass it;


```suggestion
	cmd := exec.CommandContext(ctx, cmdPath, cmdArgs[1:]...)
```

File: daemon/libnetwork/iptables/iptables.go [hunk 10]
```diff
@@ -364,7 +364,20 @@ func (iptable IPTable) raw(args ...string) ([]byte, error) {
 	log.G(context.TODO()).Debugf("%s, %v", path, args)
 
 	startTime := time.Now()
-	output, err := exec.Command(path, args...).CombinedOutput()
+	cmd := exec.Command(path, args...)
```
Comment (thaJeztah) [inline daemon/libnetwork/iptables/iptables.go]: If you're updating; perhaps won't hurt to add a `context.TODO()` here if we'll be wiring up a context here (looks like that needs a lot of wiring though, but we already have other `context.TODO` here)


```suggestion
	cmd := exec.CommandContext(context.TODO(), path, args...)
```

File: daemon/libnetwork/nlwrap/nlwrap_linux.go [hunk 11]
```diff
@@ -42,12 +44,71 @@ func NewHandle(nlFamilies ...int) (Handle, error) {
...
+			ch <- result{err: err}
+			return
+		}
+
+		if err := netns.Set(origNS); err != nil {
+			// Cannot restore the thread's network namespace. Keep the
+			// goroutine locked to this thread so the Go runtime terminates
+			// it instead of returning a tainted thread to the pool.
+			ch <- result{handle: nlh}
+			return
```
Comment (thaJeztah) [inline daemon/libnetwork/nlwrap/nlwrap_linux.go:101]: Ah! I was about to ask if we could use `defer runtime.UnlockOSThread()`, but looks like this was the reason we couldn't 👍

File: daemon/libnetwork/nlwrap/nlwrap_linux.go [hunk 12]
```diff
@@ -160,10 +221,56 @@ func LinkList() (links []netlink.Link, err error) {
...
+				return
+			}
+
+			// Create the subscribe socket in the target namespace.
+			// With Namespace cleared, the netlink library will not
+			// attempt any namespace switching internally.
+			retryOnIntr(func() error {
+				err = netlink.LinkSubscribeWithOptions(ch, done, options) //nolint:forbidigo
+				return err
+			})
```
Comment (thaJeztah) [inline daemon/libnetwork/nlwrap/nlwrap_linux.go:261]: Probably OK for a follow-up; I was slightly wondering if it'd be cleaner to have something like this (but I'd have to try to see if it's cleaner (just thinking out loud here));

```go
func LinkSubscribeWithOptions(ch chan<- netlink.LinkUpdate, done <-chan struct{}, options netlink.LinkSubscribeOptions) (err error) {
    if options.Namespace != nil && options.Namespace.IsOpen() {
		return linkSubscribeWithOptionsLockOSThread(ch, done, options)
    }
	return linkSubscribeWithOptions(ch, done, options)
}

func linkSubscribeWithOptions(ch chan<- netlink.LinkUpdate, done <-chan struct{}, options netlink.LinkSubscribeOptions) (err error) {
    retryOnIntr(func() error {
        err = netlink.LinkSubscribeWithOptions(ch, done, options) //nolint:forbidigo
        return err
    })
    return err
}

func linkSubscribeWithOptionsLockOSThread(ch chan<- netlink.LinkUpdate, done <-chan struct{}, options netlink.LinkSubscribeOptions) (err error) {
	// special handling
}
```

Then `linkSubscribeWithOptionsLockOSThread` could even call `linkSubscribeWithOptions`

File: daemon/libnetwork/ns/init_linux.go [hunk 13]
```diff
@@ -22,12 +23,28 @@ var initNamespace = sync.OnceValues(initHandles)
 
 // initHandles initializes a new network namespace
 func initHandles() (netns.NsHandle, nlwrap.Handle) {
-	initNs, err := netns.Get()
-	if err != nil {
-		log.G(context.Background()).WithError(err).Error("could not get initial namespace: falling back to using netns.None")
-		initNs = netns.None()
+	var initNs netns.NsHandle
+	var initNl nlwrap.Handle
+	var err error
```
Comment (thaJeztah) [inline daemon/libnetwork/ns/init_linux.go]: Also non-blocking, but I know `gofumpt` will likely reformat this so if you're updating;


```suggestion
	var (
		initNs netns.NsHandle
		initNl nlwrap.Handle
		err error
	)
```

File: daemon/libnetwork/ns/init_linux.go [hunk 14]
```diff
@@ -22,12 +23,28 @@ var initNamespace = sync.OnceValues(initHandles)
...
+	detachedNetNS, detachedErr := rootless.DetachedNetNS()
+	if detachedErr != nil {
+		log.G(context.Background()).WithError(detachedErr).Error("could not check for detached netns")
```
Comment (thaJeztah) [inline daemon/libnetwork/ns/init_linux.go]:
```suggestion
	detachedNetNS, err := rootless.DetachedNetNS()
	if err != nil {
		log.G(context.Background()).WithError(err).Error("could not check for detached netns")
```

File: daemon/internal/rootless/rootless_linux.go [hunk 15]
```diff
@@ -0,0 +1,139 @@
...
+
+var (
+	detachedNetNS     string
+	detachedNetNSErr  error
+	detachedNetNSOnce sync.Once
+)
+
+// DetachedNetNS returns non-empty netns path if RootlessKit is running with --detach-netns mode.
+// Otherwise returns "" without an error.
+func DetachedNetNS() (string, error) {
```
Comment (thaJeztah) [inline daemon/internal/rootless/rootless_linux.go]: Looks like we can use a `sync.OnceValues` for this, then we don't have to manage the package-level `detachedNetNS` and `detachedNetNSErr`

Something like;

```suggestion
// DetachedNetNS returns non-empty netns path if RootlessKit is running with --detach-netns mode.
// Otherwise returns "" without an error.
var DetachedNetNS = sync.OnceValues(detachedNetNS)

func detachedNetNS() (string, error) {
```

File: daemon/libnetwork/osl/namespace_linux.go [hunk 16]
```diff
@@ -115,6 +116,15 @@ func NewSandbox(key string, osCreate, isRestore bool) (*Namespace, error) {
 
 	n := &Namespace{path: key, isDefault: !osCreate}
 
+	detachedNetNS, err := rootless.DetachedNetNS()
+	if err != nil {
+		log.G(context.TODO()).Warn(err)
+	}
+	if detachedNetNS != "" && !osCreate {
+		// n refers to the host netns and we do not have a permission to do the netlink stuff
+		return n, nil
```
Comment (thaJeztah) [inline daemon/libnetwork/osl/namespace_linux.go:125]: The logic with ignoring errors, and still consuming the value feels a bit like a trip-hazard; wondering if we can find some way around that (so that errors must be handled and/or some sentinel error is used).

File: daemon/apparmor_default.go [hunk 17]
```diff
@@ -18,13 +19,25 @@ const (
...
 		return defaultAppArmorProfile
 	}
 	return ""
 }
 
 func ensureDefaultAppArmorProfile() error {
-	if apparmor.HostSupports() {
+	hostSupports := apparmor.HostSupports()
+	if hostSupports {
+		if detachedNetNS, _ := rootless.DetachedNetNS(); detachedNetNS != "" {
```
Comment (thaJeztah) [inline daemon/apparmor_default.go:34]: Related to my other comment; wondering if `""` should come with some (sentinel) error 🤔 (haven't looked at all the call-sites though). Alternatively we could have a utility function that returns a boolean if it's running with detached NetNS.

File: daemon/internal/rootless/rootless_others.go [hunk 18]
```diff
@@ -0,0 +1,41 @@
...
+// Otherwise returns "" without an error.
+func DetachedNetNS() (string, error) {
+	return "", nil
+}
+
+// RunInDetachedNetNS runs f in the detached network namespace if one is
+// configured, otherwise runs f directly.
+func RunInDetachedNetNS(f func() error) error {
+	return f()
+}
```
Comment (thaJeztah) [inline daemon/internal/rootless/rootless_others.go]: Looks like this is the ONLY function that's called from non-Linux files, so we can remove all the other stubs

File: daemon/container_operations.go [hunk 19]
```diff
@@ -1027,7 +1032,9 @@ func (daemon *Daemon) releaseNetwork(ctx context.Context, ctr *container.Contain
 		return
 	}
 
-	if err := sb.Delete(ctx); err != nil {
+	if err := rootless.RunInDetachedNetNS(func() error {
+		return sb.Delete(ctx)
+	}); err != nil {
```
Comment (thaJeztah) [inline daemon/container_operations.go:1036]: Given the many locations where we call this; it's slightly confusing to see `rootless`, but what it means is "IF we're rootless AND in a detached NetNS THEN we run this inside it".

Possibly we could add a method to the daemon;

```go
func (daemon *Daemon) runInNetNS(f func() error) error {
	if rootless.IsDetachedNetNS() {
		return rootless.RunInNetNS(f)
	}
	return f()
}
```

(perhaps even `rootless.RunningWithRootlessKit()` as gate, and do the other handling inside `rootless.RunInNetNS`)

**Review by thaJeztah — COMMENTED** [review]
🙈 left some comments; let me know what you think. Could also use input from others 😅

File: daemon/internal/rootless/specconv/specconv_linux.go (hunk 3 above)
Comment (AkihiroSuda) [reply daemon/internal/rootless/specconv/specconv_linux.go:173]: Nothing failed because the function was never used for netns so far

File: daemon/internal/rootless/specconv/specconv_linux.go (hunk 2 above)
Comment (AkihiroSuda) [reply daemon/internal/rootless/specconv/specconv_linux.go:143]: Yes, let's open a tracking ticket when this PR is merged

File: daemon/internal/rootless/rootless_linux.go (hunk 4 above)
Comment (AkihiroSuda) [reply daemon/internal/rootless/rootless_linux.go]: Almost everything in the file has diverged from the nerdctl PR, except `DetachedNetNS`.

File: daemon/libnetwork/internal/nftables/nft_exec_linux.go (hunk 6 above)
Comment (AkihiroSuda) [reply daemon/libnetwork/internal/nftables/nft_exec_linux.go:40]: No, nsenter doesn't allow it.
Tested with util-linux 2.41 and Busybox 1.37.

File: daemon/libnetwork/iptables/iptables.go (hunk 8 above)
Comment (AkihiroSuda) [reply daemon/libnetwork/iptables/iptables.go:377]: nsenter doesn't allow it.

File: daemon/libnetwork/internal/nftables/nft_exec_linux.go (hunk 5 above)
Comment (AkihiroSuda) [reply daemon/libnetwork/internal/nftables/nft_exec_linux.go]: done

File: daemon/libnetwork/iptables/iptables.go (hunk 7 above)
Comment (AkihiroSuda) [reply daemon/libnetwork/iptables/iptables.go]: done

File: daemon/libnetwork/internal/nftables/nft_exec_linux.go (hunk 9 above)
Comment (AkihiroSuda) [reply daemon/libnetwork/internal/nftables/nft_exec_linux.go]: done

File: daemon/libnetwork/iptables/iptables.go (hunk 10 above)
Comment (AkihiroSuda) [reply daemon/libnetwork/iptables/iptables.go]: done

File: daemon/libnetwork/ns/init_linux.go (hunk 13 above)
Comment (AkihiroSuda) [reply daemon/libnetwork/ns/init_linux.go]: done

File: daemon/libnetwork/ns/init_linux.go (hunk 14 above)
Comment (AkihiroSuda) [reply daemon/libnetwork/ns/init_linux.go]: done

File: daemon/internal/rootless/rootless_linux.go (hunk 15 above)
Comment (AkihiroSuda) [reply daemon/internal/rootless/rootless_linux.go]: done

File: daemon/internal/rootless/rootless_others.go (hunk 18 above)
Comment (AkihiroSuda) [reply daemon/internal/rootless/rootless_others.go]: done

File: daemon/libnetwork/nlwrap/nlwrap_linux.go (hunk 12 above)
Comment (AkihiroSuda) [reply daemon/libnetwork/nlwrap/nlwrap_linux.go:261]: Not sure. Maybe discuss as a follow-up refactoring?

File: daemon/libnetwork/osl/namespace_linux.go (hunk 16 above)
Comment (AkihiroSuda) [reply daemon/libnetwork/osl/namespace_linux.go:125]: fixed to handle the error

File: daemon/apparmor_default.go (hunk 17 above)
Comment (AkihiroSuda) [reply daemon/apparmor_default.go:34]: It is legit to have "" here without an error when `DOCKERD_ROOTLESS_ROOTLESSKIT_DETACH_NETNS=false`.

I can modify `func DetachedNetNS() (string, error)` to return `(string, bool, error`) if needed, but I feel it is redundant

File: daemon/container_operations.go (hunk 19 above)
Comment (AkihiroSuda) [reply daemon/container_operations.go:1036]: done

File: daemon/libnetwork/nlwrap/nlwrap_linux.go (hunk 12 above)
Comment (thaJeztah) [reply daemon/libnetwork/nlwrap/nlwrap_linux.go:261]: Yes, definitely fine for a follow-up

File: daemon/daemon_unix.go [hunk 20]
```diff
@@ -837,7 +837,9 @@ func (daemon *Daemon) initNetworkController(cfg *config.Config, activeSandboxes
 
 	if len(activeSandboxes) > 0 {
 		log.G(ctx).Info("there are running containers, updated network configuration will not take affect")
-	} else if err := configureNetworking(ctx, daemon.netController, cfg); err != nil {
+	} else if err := daemon.runInNetNS(func() error {
```
Comment (thaJeztah) [inline daemon/daemon_unix.go:840]: Thanks! Yes, I think this looks cleaner this way ❤️ 

(sorry for all the nit-picks)

**Review by thaJeztah — APPROVED** [review]
LGTM

@vvoland @robmry PTAL

**Comment by AkihiroSuda** [comment]
CI failure is irrelevant:
- https://github.com/moby/moby/issues/52300

File: contrib/dockerd-rootless.sh [hunk 21]
```diff
@@ -177,6 +181,20 @@ if [ -z "$_DOCKERD_ROOTLESS_CHILD" ]; then
 		_DOCKERD_ROOTLESS_SELINUX=1
 		export _DOCKERD_ROOTLESS_SELINUX
 	fi
+
+	case "$DOCKERD_ROOTLESS_ROOTLESSKIT_DETACH_NETNS" in
+		1 | true)
+			DOCKERD_ROOTLESS_ROOTLESSKIT_FLAGS=--detach-netns $DOCKERD_ROOTLESS_ROOTLESSKIT_FLAGS
```
Comment (vvoland) [inline contrib/dockerd-rootless.sh]: nit: This could be mistakenly read as executing `$DOCKERD_ROOTLESS_ROOTLESSKIT_FLAGS` with `DOCKERD_ROOTLESS_ROOTLESSKIT_FLAGS` env set to `-detach-netns`.


Enclosing with quotes would be a little bit more explicit:
```suggestion
			DOCKERD_ROOTLESS_ROOTLESSKIT_FLAGS="--detach-netns $DOCKERD_ROOTLESS_ROOTLESSKIT_FLAGS"
```

File: daemon/libnetwork/internal/nftables/nft_exec_linux.go [hunk 22]
```diff
@@ -19,7 +20,21 @@ func (t *table) nftApply(ctx context.Context, nftCmd []byte) error {
...
 
-	cmd := exec.Command(nftPath, "-f", "-")
+	cmdPath := nftPath
+	cmdArgs := []string{nftPath, "-f", "-"}
+	detachedNetNS, err := rootless.DetachedNetNS()
+	if err != nil {
+		return fmt.Errorf("could not check for detached netns: %w", err)
+	}
+	if detachedNetNS != "" && !rootless.InSandboxNS() {
+		nsenterPath, err := exec.LookPath("nsenter")
```
Comment (vvoland) [inline daemon/libnetwork/internal/nftables/nft_exec_linux.go]: Is this happening for each container setup? Should we cache this so we don't do this every time?

File: contrib/dockerd-rootless.sh (hunk 21 above)
Comment (AkihiroSuda) [reply contrib/dockerd-rootless.sh]: Fixed

File: daemon/libnetwork/internal/nftables/nft_exec_linux.go (hunk 22 above)
Comment (AkihiroSuda) [reply daemon/libnetwork/internal/nftables/nft_exec_linux.go]: Fixed

**Review by vvoland — APPROVED** [review]
LGTM, thanks!

**Comment by AkihiroSuda** [comment]
Merged, as the PR has been approved and the master branch is now  thawed for v29.5.

Docs PR:
- https://github.com/docker/docs/pull/24645
