### PR TITLE
Fix dockerfile parser with empty line after escape

### LINKED ISSUE #24693: bug: comment on preceding line in Dockerfile causes subsequent run comments to be ignored
maybe a the same as #20273, though the issue there doesn't seem as severe.

**Output of `docker version`:**

```
docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   b9f10c9
 Built:        Tue Jun 21 00:43:14 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   b9f10c9
 Built:        Tue Jun 21 00:43:14 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 11
 Running: 0
 Paused: 0
 Stopped: 11
Images: 254
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-254:0-5513598-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 17.35 GB
 Data Space Total: 107.4 GB
 Data Space Available: 69.74 GB
 Metadata Space Used: 20.98 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.127 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.127 (2016-06-17)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.5.4-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.33 GiB
Name: dieter-m6800
ID: AMPP:4IZ5:BFKQ:LZVT:IAGF:OCS6:4BMI:RI4W:4EZY:6TK3:ZZJV:CBBX
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

The problem is, with the below dockerfile - as the run output below that shows - the line with `RUN go get github.com/tsenart/vegeta` gets parsed as if its part of the previous command, and gets prepended with `#`, so the command is not run.

what is expected: run `RUN go get github.com/tsenart/vegeta` as its own run command.

```
FROM raintank/nodejsgo

ENV GOPATH /go
ENV PATH $PATH:/usr/local/go/bin:$GOPATH/bin

RUN apt-get -y install wget vim bc supervisor
RUN mkdir -p /go/src/github.com/grafana
RUN cd /go/src/github.com/grafana && \
    git clone https://github.com/raintank/grafana-api-golang-client.git && \
    cd grafana-api-golang-client && \
    git checkout raintank #&& \
    #go get github.com/raintank/env-load

RUN go get github.com/tsenart/vegeta
RUN go get github.com/raintank/inspect/inspect-es

CMD ["/usr/bin/supervisord"]
```

```
docker build .
Sending build context to Docker daemon 3.072 kB
Step 1 : FROM raintank/nodejsgo
 ---> b7aacd1c2f48
Step 2 : ENV GOPATH /go
 ---> Using cache
 ---> 420832244d3e
Step 3 : ENV PATH $PATH:/usr/local/go/bin:$GOPATH/bin
 ---> Using cache
 ---> 7c875ee90ed4
Step 4 : RUN apt-get -y install wget vim bc supervisor
 ---> Using cache
 ---> 18e36c697f9a
Step 5 : RUN mkdir -p /go/src/github.com/grafana
 ---> Using cache
 ---> c339b442715c
Step 6 : RUN cd /go/src/github.com/grafana &&   git clone https://github.com/raintank/grafana-api-golang-client.git &&      cd grafana-api-golang-client &&     git checkout raintank #&& RUN go get github.com/tsenart/vegeta
 ---> Using cache
 ---> 2ef4a1c65071
Step 7 : RUN go get github.com/raintank/inspect/inspect-es
 ---> Using cache
 ---> 9d10cd05695c
Step 8 : CMD /usr/bin/supervisord
 ---> Running in 68942f5f7bb9
 ---> 1a8760d6fae8
Removing intermediate container 68942f5f7bb9
Successfully built 1a8760d6fae8
```

### PR DESCRIPTION
**Pull request by yongtang**
**\- What I did**

This fix tries to fix the bug reported by #24693 where an empty line after escape will not be stopped by the parser.

**\- How I did it**

This fix addresses this issue by stop the parser from continue with an empty line after escape.

**\- How to verify it**

An additional integration test has been added.

**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**

This fix fixes #24693.

Signed-off-by: Yong Tang yong.tang.github@outlook.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM

ping @duglin

**Comment by thaJeztah** [comment]
Looks like tests are failing, think there may be more to look into

**Comment by duglin** [comment]
Don't have time right now to full review but I do recall that we had some really funky rules w.r.t. auto-continuing lines when they're blank. Wouldn't surprise me if the failures are related to that. And the last time we thought about "fixing" this we didn't because we didn't want to break existing Dockerfiles that might count on this odd behavior.

**Comment by thaJeztah** [comment]
Yes, I was wondering, perhaps we strip the continuation character before we arrive here, in case this may see `      \` as an empty line (but I should look as well)

**Comment by yongtang** [comment]
Thanks @duglin @thaJeztah. The failed test has the following file:
```
RUN apt-get \update && \
  apt-get \"install znc -y
ADD \conf\\" /.znc

RUN foo \

bar \

baz

CMD [ "\/usr\\\"/bin/znc", "-f", "-r" ]
```

and expect the result to be:
```
RUN foo bar baz
```

In other words, the previous behavior of docker considers empty lines (and comments) as continuation. And you could place many empty lines (or comment) in between:
```
FROM busybox
RUN echo foo \




RUN bar


CMD [ "\/usr\\\"/bin/znc", "-f", "-r" ]
```
The result of the above would be one command RUN:
```
RUN echo foo RUN bar
CMD [ "\/usr\\\"/bin/znc", "-f", "-r" ]
```

I think it makes sense to at least not allow empty lines to continue as it is quite misleading. People may place an escape by mistake, then it will continue forever, no matter how many empty lines have passed.

We could keep the comment for continuation to not break many existing behaviors, i.e., 
```
FROM busybox
RUN  \
# my comment
# some other comment 
# and some script, etc
echo bar
```
will be
```
RUN echo bar
```
and the old behavior is maintained in this case.

I updated pull request for the test cases to allow the test pass. But let me know the best way to handle them in these situations, or we could leave the old behavior alone if needed.

**Comment by thaJeztah** [comment]
Sounds good, but we may want to look at the history of that test; if it was testing a specific case, or just confirming "broken" behavior

File: builder/dockerfile/parser/testfiles/continueIndent/Dockerfile [hunk 1]
```diff
@@ -30,7 +30,5 @@ frog
 
 RUN echo hello \
 # this is a comment
-
 # this is a comment with a blank line surrounding it
```
Comment (cyphar) [inline builder/dockerfile/parser/testfiles/continueIndent/Dockerfile]: This comment makes me believe this was intentional functionality.

**Comment by cyphar** [comment]
I think that the bug is not with our treatment of multi-line commands, but with comments:

```
RUN cd /go/src/github.com/grafana && \
    git clone https://github.com/raintank/grafana-api-golang-client.git && \
    cd grafana-api-golang-client && \
    git checkout raintank #&& \
    #go get github.com/raintank/env-load

RUN go get github.com/tsenart/vegeta
RUN go get github.com/raintank/inspect/inspect-es
```

Currently the `#go get github.com/raintank/env-load` line seems to be stripped but the trailing `#&& \` is not on the previous line. We should fix how we strip comments, not remove a (questionable) feature of the parser as a hotfix.

**Comment by thaJeztah** [comment]
@cyphar yes, it surprised be that the `#go get` line is stripped, because the Dockerfile syntax says that comments **must** begin at position 1, and cannot have spaces before them.

If we stick to that then, in this case, the `#go get` line would be treated as part of the `RUN`, and just concatenation with the previous line.

I'm not sure why we ever wanted to support the blank lines though, or if that was a bug in the past, that we decided to keep supporting

**Comment by cyphar** [comment]
TBH, I do actually prefer more lax commenting. But it's weird to me (coming from shell scripts) that `#&& \` isn't stripped.

**Comment by thaJeztah** [comment]
Looks like the blank line behavior was introduced here; https://github.com/docker/docker/pull/8580

**Comment by thaJeztah** [comment]
@cyphar it's because everything inside the `RUN` should be passed as-is to the shell inside the comtainer, basically no processing should take place, especially since we now have a `SHELL` directive, and `#` may not even be a comment in the shell that is selected

**Comment by yongtang** [comment]
Thanks @cyphar @thaJeztah. Not knowing enough history of docker, I can only guess the reason comment line is continued might be related to the ambiguity when `#` and `\` exist at the same line. 

For example, in case of 
```
\ # Should the comment be removed first so that `\` is line escape,
\ # or should we consider this is the escape of space ` ` followed by `#` and comment?
```
and
```
# Should the end of line `\` be considered as part of the comment , \
# or the end of line `\` be considered as an escape and not part of the comment ? \
```
The outputs of the above likely depends on if we parse from the left, or parse from the right.

So continuation with comment lines avoids the issue mentioned above.

Again, I don't know enough history of docker so I could be totally wrong here.

On the other hand, I feel like the continuation on empty line is quite misleading. The issue is that, if the user adds an escape `\` at one line, then the user will be forced to adds *something* other than comment lines or empty lines to stop the escape. And this could easily getting into the next `RUN XXX` if not careful.

**Comment by cyphar** [comment]
I personally don't like the fact that we are acting differently to shells with `\` continuation. But to be clear, my point was that I don't think this patch fixes the underlying problem (if you remove the newline between the two `RUN`s I think it will still act incorrectly). We need to fix how comments are dealt with -- and fixing up line continuation is a separate thing that we should probably also do.

**Comment by cpuguy83** [comment]
What are we doing with this?

File: builder/dockerfile/parser/testfiles/continueIndent/Dockerfile (hunk 1 above)
Comment (duglin) [inline builder/dockerfile/parser/testfiles/continueIndent/Dockerfile]: yes this was intentionally weird and while I'm 100% in favor of "fixing" this, it needs to be discussed by the maintainers because this was purposely kept weird all this time.

**Comment by duglin** [comment]
my vote is to "fix" this but since it has been this way for ages (intentionally) we'd need agreement to break backwards compatibility.

**Comment by duglin** [comment]
to be clear, I'd like to see two fixes:
1) make blank lines end a continuation sequence
2) allow for blanks in front of a comment (#) - remove requirement that "#" be only in the first column

While I think supporting comments at the end of lines would be good, that's a bigger change that would be trickier since we don't have a formal "end of statement" in Dockerfiles so knowing when "#" isn't part of the RUN command itself could be tricky. So for now I think doing the two things above would be a good first step.

**Comment by yongtang** [comment]
Thanks for the comment @duglin. I updated the pull request and the following should have been addressed in this PR:
> 1) make blank lines end a continuation sequence
> 2) allow for blanks in front of a comment (#) - remove requirement that "#" be only in the first column

Also, now all tests should have passed. Please take a look and let me know if there are any issues.

File: builder/dockerfile/parser/parser.go [hunk 2]
```diff
@@ -176,6 +176,10 @@ func Parse(rwc io.Reader, d *Directive) (*Node, error) {
 				newline := scanner.Text()
 				currentLine++
 
+				// If escape followed by an empty line then stop
+				if strings.TrimSpace(newline) == "" {
```
Comment (duglin) [inline builder/dockerfile/parser/parser.go]: even though speed isn't a huge issue since I doubt we're parsing 1000's of lines, can we save the result of `strings.TrimSpace(newLine)` and re-use it above and below so we don't call it twice?

File: builder/dockerfile/parser/testfiles/continueIndent/Dockerfile (hunk 1 above)
Comment (duglin) [inline builder/dockerfile/parser/testfiles/continueIndent/Dockerfile]: Let's remove, or edit, this command to be more accurate

File: builder/dockerfile/parser/testfiles/escapes/Dockerfile [hunk 3]
```diff
@@ -6,9 +6,7 @@ RUN apt-get \update && \
 ADD \conf\\" /.znc
 
 RUN foo \
-
 bar \
-
```
Comment (duglin) [inline builder/dockerfile/parser/testfiles/escapes/Dockerfile]: since you've remove all of the tests for "blank lines" as continutations, let's make sure we add a test to ensure that a blank line end the continution. E.g. Make sure that:
```
RUN foo \

bar
```
gives an error of "unknown command 'bar'`

Comment (duglin) [inline builder/dockerfile/parser/testfiles/escapes/Dockerfile]: I see you test for it in the integration tests, but let's add one to the unit tests too since we should test the parser in isolation of the builder.

File: integration-cli/docker_cli_build_test.go [hunk 4]
```diff
@@ -6918,3 +6918,38 @@ func (s *DockerSuite) TestBuildStepsWithProgress(c *check.C) {
...
+
+	// With comment, see #24693
+	name = "testbuildcommentandemptylineafterescape"
+	_, out, err = buildImageWithOut(name,
+		`
+FROM busybox
+RUN echo grafana && \
+    echo raintank \
+    #echo env-load
+
```
Comment (duglin) [inline integration-cli/docker_cli_build_test.go]: remove this blank line to make sure that the comment is the thing that ends the previous RUN and not the blank line.

File: builder/dockerfile/parser/parser.go (hunk 2 above)
Comment (yongtang) [inline builder/dockerfile/parser/parser.go]: Thanks @duglin. The PR has been updated.

File: builder/dockerfile/parser/testfiles/escapes/Dockerfile (hunk 3 above)
Comment (yongtang) [inline builder/dockerfile/parser/testfiles/escapes/Dockerfile]: Thanks @duglin. The comment has been removed and a new unit test has been added.

File: integration-cli/docker_cli_build_test.go (hunk 4 above)
Comment (yongtang) [inline integration-cli/docker_cli_build_test.go]: @duglin I thought blank line will end the continuation. Do we also want to end the escape continuation with comment line?

Comment (duglin) [inline integration-cli/docker_cli_build_test.go]: @yongtang yes I think we do. See this:
```
$ cat a
echo hi \
 #
echo bye

echo hi \
 # \
echo bye

$ ./a
hi
bye
hi
bye
```
A comment line is basically a blank line, once you remove the `# ...`.

**Comment by duglin** [comment]
Also, please squash your commits

File: integration-cli/docker_cli_build_test.go (hunk 4 above)
Comment (yongtang) [inline integration-cli/docker_cli_build_test.go]: Thanks @duglin. Previously I though the comment `#` as part of "shell comment" after the `RUN` when escape is in place. Now I understand we actually treat the comment `#` as "dockerfile comment" even if escape is there. (There were some confusion about the dockerfile's comment/escape/continuation).

Let me update the PR based on that.

**Comment by yongtang** [comment]
Thanks @duglin for the review and help. The PR has been updated and squashed. Please take a look and let me know if there are any issues.

**Comment by thaJeztah** [comment]
@yongtang test is failing; https://jenkins.dockerproject.org/job/Docker-PRs/33030/console

```
12:23:04 ----------------------------------------------------------------------
12:23:04 FAIL: docker_cli_build_test.go:3563: DockerSuite.TestBuildUsersAndGroups
12:23:04 
12:23:04 docker_cli_build_test.go:3619:
12:23:04     c.Fatal(err)
12:23:04 ... Error: failed to build the image: Sending build context to Docker daemon 4.608 kB


12:23:04 Error response from daemon: Unknown instruction: ECHO
12:23:04 
```

**Comment by yongtang** [comment]
Thanks @thaJeztah. The PR has been updated for the jenkins failure.

**Comment by yongtang** [comment]
There is still one Jenkins failure that seems to be unrelated. I will take a look at it:
```
20:54:40 ----------------------------------------------------------------------
20:54:40 FAIL: docker_api_stats_test.go:164: DockerSuite.TestApiStatsNetworkStatsVersioning
20:54:40 
20:54:40 docker_api_stats_test.go:215:
20:54:40     c.Assert(err, checker.IsNil, check.Commentf("failed to decode stat: %s", err))
20:54:40 ... value *json.SyntaxError = &json.SyntaxError{msg:"invalid character 'A' looking for beginning of value", Offset:1} ("invalid character 'A' looking for beginning of value")
20:54:40 ... failed to decode stat: invalid character 'A' looking for beginning of value
20:54:40 
20:54:40 
20:54:40 ----------------------------------------------------------------------
```

**Comment by thaJeztah** [comment]
> 2) allow for blanks in front of a comment (#) - remove requirement that "#" be only in the first column

@duglin catching up on the discussion here; any reason you want to include that change in this PR? As far as I know, that is not a _bug_, but by design; including that change as part of a bug fix PR may make it more difficult to move this forward. I really would prefer that as separate from this.

**Comment by duglin** [comment]
@thaJeztah that's fine - its just that this PR migrated a bit into fixing some of the oddities in our parser so I tossed in one that was related.  Either way is fine with me.

**Comment by thaJeztah** [comment]
@duglin thanks - I wasn't sure if everyone would be on board with changing that, and potentially block this PR (which is already quite old) from being merged.

@yongtang could you keep the change for comments out of this PR, that way I hope we'd be able to get this moving forward quicker. I'm open to doing it in a separate PR so that it can be discussed separately

**Comment by yongtang** [comment]
Thanks @duglin @thaJeztah. The PR has been updated so that now only `^#` is considered as the comment. Please take a look and let me know if there are any issues.

**Comment by mlaventure** [comment]
The current version seems to correctly break the continuation sequence.

Provided that we're still ok to have a subsequent PR to fix the rest, LGTM

ping @duglin @thaJeztah

**Comment by yongtang** [comment]
The PR has been rebased to fix the merge conflict. All tests passed. Ping @duglin @thaJeztah

**Comment by duglin** [comment]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by tianon** [comment]
This is a pretty huge breaking change for `Dockerfile` parsing -- are we sure we're committed to making this change?

The failure mode is pretty awful too; here's an example error from trying to build one of the `php` official image variants:
```console
$ docker version
Client:
 Version:      1.13.0-rc2
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   1f9b3ef
 Built:        Wed Nov 23 17:40:58 2016
 OS/Arch:      linux/amd64

Server:
 Version:             1.13.0-rc2
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          1f9b3ef
 Built:               Wed Nov 23 17:40:58 2016
 OS/Arch:             linux/amd64
 Experimental:        false
$ docker build 7.0/alpine
Sending build context to Docker daemon 13.82 kB
Error response from daemon: Unknown instruction: --ENABLE-FTP
```

**Comment by tianon** [comment]
For reference, here's the exact line that's failing on: https://github.com/docker-library/php/blob/7d058f79e6fdf7b8e97d5004d1098c436d348a47/7.0/alpine/Dockerfile#L97

File: builder/dockerfile/parser/testfiles/continueIndent/Dockerfile [hunk 5]
```diff
@@ -27,8 +27,5 @@ bye\
 frog
 
 RUN echo hello \
-# this is a comment
-
-# this is a comment with a blank line surrounding it
-
-this is some more useful stuff
+# this is a comment that breaks escape continuation
+RUN echo this is some more useful stuff
```
Comment (tianon) [inline builder/dockerfile/parser/testfiles/continueIndent/Dockerfile]: This is the offending test change -- a comment by itself _should_ still be valid in the middle of a continuation (very, very common, useful pattern, supported by Docker for ages now).

**Comment by yongtang** [comment]
@tianon @duglin 
Before this PR, the behavior of parser is (See https://github.com/docker/docker/pull/24725#issuecomment-233151746):
 - Space is continued as long as it begins with `\`:
```
FROM busybox
RUN echo foo \




RUN bar

CMD [ "\/usr\\\"/bin/znc", "-f", "-r" ]
```
will result in (May empty lines will continue):
```
RUN echo foo RUN bar
CMD [ "\/usr\\\"/bin/znc", "-f", "-r" ]
```

- Comment is continued as long as it begins with `\`:
```
FROM busybox
RUN  \
# my comment
# some other comment 
# and some script, etc
echo bar
```
will result in (may comment lines will continue):
```
RUN echo bar
```

This PR changed both based on discussions.

If there are concerns with "no-continuation-for-comments", maybe we could revert back?

We probably could keep the other changes "no-continuation-for-empty-lines" alone as it is confusing. The reason is that, in case an user have placed a `\` at the end of one line, then this s`\` will continue even if many empty lines has been added.

Alternatively, I am wondering if it makes sense to add a `VERSION` for Dockerfile? This should allows for backward-compatibility in the future.

**Comment by thaJeztah** [comment]
@yongtang was discussing with Tianon; problem is here; https://github.com/docker/docker/pull/24725/files#diff-a70e690b6dc1bcdbae36a5f54c868bbeR183

It breaks on a comment line, but should probably detect if it's a comment-only line, and if so, continue

Due to the previous behavior, inside `RUN`, that means also if there's whitespace before the `#`

**Comment by yongtang** [comment]
Thanks @thaJeztah. Let me take a look and see if I could provide a quick fix for it.

**Comment by kinghuang** [comment]
The behaviour in 1.13-RC2 has broken all of my Dockerfiles as I depend on both spaces and comments being allowed after continuations in the RUN and ENV instructions. As a user, this is a huge and unwelcome breaking change for 1.13 if it stays.

**Comment by thaJeztah** [comment]
@kinghuang we are aware of this change, and will address before 1.13 GA. The discussion is taking place here; https://github.com/docker/docker/issues/29005, and is currently focussed on the "blank lines", perhaps you can add a minimal example of this from your Dockerfile.

I'll lock the discussion here, so that the discussion does not take place on multiple places, but you're welcome to join in the discussion on https://github.com/docker/docker/issues/29005
