### PR TITLE
Fix 19575: Docker events doesn't work with authorization plugin

### LINKED ISSUE #19575: docker events return null when I use authorization plugin
Docker Version:

Client:
 Version:      1.10.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   7faff24-unsupported
 Built:        Thu Jan 21 06:06:47 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   7faff24-unsupported
 Built:        Thu Jan 21 06:06:47 2016
 OS/Arch:      linux/amd64

Docker Info:

Containers: 15
 Running: 0
 Paused: 0
 Stopped: 15
Images: 5
Server Version: 1.10.0-dev
Storage Driver: devicemapper
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host overlay bridge
 Authorization: leeProcess
Kernel Version: 4.1.8-200.fc22.x86_64
Operating System: Fedora 22 (Twenty Two)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.46 GiB
Cluster store: etcd://192.168.0.19:4001/docker-cluster1
Cluster advertise: 127.0.0.1:2375

step:
1.docker daemon -s devicemapper  --authorization-plugin=leeProcess
2.docker events
3.at the same time,I command "docker start {CID}"

I don't get any message from events terminal
If I run other docker command ,I get the result that i expected

### PR DESCRIPTION
**Pull request by liron-l**
To support the requirement of blocking the request after the daemon
responded the authorization plugin use a `response recorder` that replay
the response after the flow ends.

This commit adds support for commands that hijack the connection and
flushes data via the http.Flusher interface. This resolves the error
with the event endpoint.

Signed-off-by: Liron Levin liron@twistlock.com

fixes #19575

### CODE REVIEW

**Comment by liron-l** [comment]
@runcom please review.

File: pkg/authorization/response.go [hunk 1]
```diff
@@ -5,6 +5,7 @@ import (
 	"bytes"
 	"encoding/json"
 	"fmt"
+	"github.com/docker/docker/vendor/src/github.com/Sirupsen/logrus"
```
Comment (LK4D4) [inline pkg/authorization/response.go]: this import is wrong :)

**Comment by calavera** [comment]
can we have an integration test for this?

**Comment by runcom** [comment]
> can we have an integration test for this?

+1 having an integration test would be great here

**Comment by liron-l** [comment]
Thanks @calavera and @runcom for looking into this change. Added integration test for the event endpoint. Please note that I've reused the code from the events integration test.

**Comment by calavera** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Comment by StefanScherer** [comment]
@liron-l We encounter problems with the integration test `TestAuthZPluginAllowEventStream` on ARM.

```
01:46:48 ----------------------------------------------------------------------
01:46:48 FAIL: docker_cli_authz_unix_test.go:230: DockerAuthzSuite.TestAuthZPluginAllowEventStream
01:46:48 
01:46:48 [d15565931] waiting for daemon to start
01:46:48 [d15565931] received status != 200 OK: 500 Internal Server Error
01:46:48 [d15565931] daemon started
01:46:48 docker_cli_authz_unix_test.go:262:
01:46:48     c.Assert(err, check.IsNil)
01:46:48 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0x114b0450)} ("exit status 125")
01:46:48 
01:46:48 [d15565931] exiting daemon
01:46:57 
01:46:57 ----------------------------------------------------------------------
```

Do you have a short advice how to investigate this test?
My first thought is just a timing problem because of the slower CPU's used running the tests.

**Comment by liron-l** [comment]
Thanks @StefanScherer. This error does not directly relates to the authentication plugin:
line 262 (run a new container):
out, err := s.d.Cmd("run", "-d", "busybox", "top")
c.Assert(err, check.IsNil)

Can you fetch to daemon logs? Is this error sporadic?

**Comment by StefanScherer** [comment]
@liron-l I can try to fetch the daemon logs. It occurs in our regression tests which fetches latest master from docker/docker repo. This helps us keeping an eye on what happens after new PR's get merged until the arm builder will check PR's before the merge.

jenkins-on-scaleway-regression

It seems reproducable on ARM.

**Comment by runcom** [comment]
@StefanScherer to debug this further, can you put a `c.Assert(err, check.IsNil, check.Commentf(out)` after the failing line? cause right now it's only showing the error but not what's in the command output, make sense?

**Comment by runcom** [comment]
like this http://ur1.ca/ohwca

**Comment by StefanScherer** [comment]
@runcom Thanks! I'll add this line.

**Comment by StefanScherer** [comment]
Ok, got an exec format error. Seems that the docker engine doesn't have the images preloaded and pulls busybox from Docker Hub. This is a typical problem for multiarch support at the moment. I'll have a closer look later.

**Comment by runcom** [comment]
@StefanScherer alright :)

**Comment by StefanScherer** [comment]
Here are the details, couldn't enter multi line from mobile phone earlier:

```
12:58:23 ----------------------------------------------------------------------
12:58:23 FAIL: docker_cli_authz_unix_test.go:231: DockerAuthzSuite.TestAuthZPluginAllowEventStream
12:58:23 
12:58:23 [d92814143] waiting for daemon to start
12:58:23 [d92814143] received status != 200 OK: 500 Internal Server Error
12:58:23 [d92814143] daemon started
12:58:23 docker_cli_authz_unix_test.go:263:
12:58:23     c.Assert(err, check.IsNil, check.Commentf(out))
12:58:23 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0x11437450)} ("exit status 125")
12:58:24 ... 47c4a2d30c4cea577d9b3366e4e05e585763c719d7c03225af91bf8e583c4639
12:58:24 /go/src/github.com/docker/docker/bundles/1.11.0-dev/test-integration-cli/../dynbinary/docker: Error response from daemon: Cannot start container 47c4a2d30c4cea577d9b3366e4e05e585763c719d7c03225af91bf8e583c4639: [9] System error: exec format error.
12:58:24 
12:58:24 
12:58:24 [d92814143] exiting daemon
12:58:32 
12:58:32 ----------------------------------------------------------------------
12:58:32 PASS: docker_cli_authz_unix_test.go:171: DockerAuthzSuite.TestAuthZPluginAllowRequest	6.461s
```

The other test `TestAuthZPluginAllowRequest` works on ARM. And the code does the daemon start a little different which is multiarch-friendly: https://github.com/docker/docker/blob/5ffc810df22c3779b4df8ce28d94e4bf89d34e2f/integration-cli/docker_cli_authz_unix_test.go#L171-L176

It starts with the busybox image and restarts with the options needed. Little workarounds here and there.
I'll check this with ARM and send a PR to fix the test case.

**Comment by runcom** [comment]
Thx @StefanScherer :)

**Comment by tophj-ibm** [comment]
@StefanScherer I can confirm this is broken on power also. Also I ran the test using your proposed changes and that works for me :+1:
