### PR TITLE
Swarm-mode overlay networking support for windows

### LINKED ISSUE #26912: Subnets with conflicting ranges in Docker
**Description**

Docker allows a creation of subnets with conflicting ranges. Additionally it assigns the same IP multiple times (both to a same docker container or a multiple ones).

**Steps to reproduce the issue:**
When using docker overlay network (with zookeeper), docker allows to create subnets with conflicting ranges (possibly not necessarily related to an overlay feature). Additionally, docker assigns the same IP to 
- multiple containers
- to a single container within 2 subnets

For instance, Docker with the implicit overlay bridge `docker_gwbridge` with subnet `172.19.0.0/16`, allows a creation of a conflicting overlay network:

```
docker network create --driver overlay --subnet=172.19.0.0/16 conflicting_subnet
```

and then running a docker container with `--net conflicting_subnet`

```
docker run -ti --net conflicting_subnet alpine /bin/sh
```

which results with a container connected to both subnets (Additionally, it assigns the same IP `172.19.0.2` multiple times as listed bellow. Here, it assigns the same IP to the same container.)

```

/ # ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
4909: eth0@if4910: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue state UP
    link/ether 02:42:ac:13:00:02 brd ff:ff:ff:ff:ff:ff
    inet 172.19.0.2/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe13:2/64 scope link
       valid_lft forever preferred_lft forever
4911: eth1@if4912: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP
    link/ether 02:42:ac:13:00:02 brd ff:ff:ff:ff:ff:ff
    inet 172.19.0.2/16 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe13:2/64 scope link
       valid_lft forever preferred_lft forever
```

**Describe the results you expected:**
I would expect docker to protect the subnets it manages either by
1. disallowing a creation of subnets with conflicting ranges
2. disallowing connecting a container to subnets with conflicting ranges
3. not assigning a single IP address to multiple containers or multiple times to a single container

**Output of `docker version`:**

```
# docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
# docker info
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 3
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-251:0-6815748-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 21.47 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 809.9 MB
 Data Space Total: 107.4 GB
 Data Space Available: 106.6 GB
 Metadata Space Used: 1.581 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /scratch/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /scratch/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.1.12-37.6.2.el7uek.x86_64
Operating System: Oracle Linux Server 7.1
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 29.47 GiB
Name: foobar.my.com
ID: 2GL5:LWVG:MB6F:OBS7:KDVF:ZWUG:6KED:U5SJ:SPBW:66RI:RZGS:AZX6
Docker Root Dir: /scratch/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://proxy.my.com:80
Https Proxy: http://proxy.my.com:80
No Proxy: localhost,127.0.0.1,.my.com,/var/run/docker.sock
Registry: https://index.docker.io/v1/
Cluster Store: zk://zoo.my.com:2181/docker
Cluster Advertise: 10.170.105.79:2376
Insecure Registries:
 mic2.my.com
 127.0.0.0/8
```

### PR DESCRIPTION
**Pull request by msabansal**
**- What I did**
Enable overlay networking support on windows

**- How I did it**
The latest libnetwork has windows overlay network support. This PR vendors the latest libnetwork with minor changes that are required to enable overlay networking. For overlay networks there is an additional gateway endpoint attached to the container. We have added support to docker to enable querying this endpoint to pass it to HCS. 

**- How to verify it**
The windows binaries required to enable overlay networking are not yet released. We have validated the support internally and validated the existing scenarios.
**- Description for the changelog**

- Added support for overlay networking for windows
- Vendors latest libnetwork 

**- A picture of a cute animal (not mandatory but encouraged)**

**libnetwork vendoring:** Fixes #26912

### CODE REVIEW

**Comment by mavenugo** [comment]
@msabansal I pushed https://github.com/docker/swarmkit/pull/1737 to take care of the swarmkit fix. once it is merged, pls vendor swarmkit properly and remove the WIP tag.

File: daemon/daemon_windows.go [hunk 1]
```diff
@@ -261,9 +261,12 @@ func (daemon *Daemon) initNetworkController(config *Config, activeSandboxes map[
 		}
 
 		if !found {
-			err = v.Delete()
-			if err != nil {
-				return nil, err
+			// overlay networks are global and should not be deleted by local HNS
+			if v.Type() != "overlay" {
```
Comment (mavenugo) [inline daemon/daemon_windows.go]: Instead of v.Type() variable, you can use v.Info().Scope() constant and compare it against `datastore.GlobalScope` or simple "global" string.

File: daemon/daemon_windows.go [hunk 2]
```diff
@@ -288,6 +291,11 @@ func (daemon *Daemon) initNetworkController(config *Config, activeSandboxes map[
 	// discover and add HNS networks to windows
 	// network that exist are removed and added again
 	for _, v := range hnsresponse {
+		if strings.ToLower(v.Type) == "overlay" {
```
Comment (mavenugo) [inline daemon/daemon_windows.go]: same here

File: daemon/daemon_windows.go (hunk 1 above)
Comment (msabansal) [inline daemon/daemon_windows.go]: Accepted. Fixing.

File: daemon/daemon_windows.go (hunk 2 above)
Comment (msabansal) [inline daemon/daemon_windows.go]: Accepted. Fixing.

**Comment by mavenugo** [comment]
@msabansal Thanks for your patience. The docker changes are very minimal and LGTM.

My only comment is the confusion people might have due to the lack of overlay support on the released WS2016 software and it requires update in the future. It would be great if we can add a check for this and not show the overlay driver. But given that the current behavior is consistent with other windows drivers such as `l2bridge` and `l2tunnel`, i wouldn't make that as a blocker for this PR. But I urge you to consider a follow-up patch for this.

**Comment by vieux** [comment]
LGTM

File: daemon/daemon_windows.go [hunk 3]
```diff
@@ -261,9 +262,12 @@ func (daemon *Daemon) initNetworkController(config *Config, activeSandboxes map[
 		}
 
 		if !found {
-			err = v.Delete()
-			if err != nil {
-				return nil, err
+			// global networks should not be deleted by local HNS
+			if v.Info().Scope() == datastore.GlobalScope {
```
Comment (mavenugo) [inline daemon/daemon_windows.go]: Shouldn't this be `!=` ?

**Comment by mavenugo** [comment]
@msabansal i know you are blocked by https://github.com/docker/swarmkit/pull/1740. Could you pls validate this fix (after addressing my comment above) along with https://github.com/docker/swarmkit/pull/1740 and make sure things work as expected ?

File: daemon/start_windows.go [hunk 4]
```diff
@@ -78,6 +79,14 @@ func (daemon *Daemon) getLibcontainerdCreateOptions(container *container.Contain
 			if err != nil {
 				continue
 			}
+
+			if data["GW_INFO"] != nil {
+				gwInfo := data["GW_INFO"].(map[string]interface{})
+				if gwInfo["hnsid"] != nil {
+					gwHNSID = gwInfo["hnsid"].(string)
```
Comment (thaJeztah) [inline daemon/start_windows.go]: Can different networks on the same container have different `GW_INFO.hnsid`'s? Only the last one is added to the endpoint list, correct?

File: vendor/github.com/docker/libnetwork/drivers/solaris/overlay/ov_network.go [hunk 5]
```diff
@@ -0,0 +1,791 @@
...
+
+func (d *driver) deleteNetwork(nid string) {
+	d.Lock()
+	delete(d.networks, nid)
+	d.Unlock()
+}
+
+func (d *driver) network(nid string) *network {
+	d.Lock()
+	networks := d.networks
```
Comment (cpuguy83) [inline vendor/github.com/docker/libnetwork/drivers/solaris/overlay/ov_network.go]: This is not safe.

File: vendor/github.com/docker/libnetwork/drivers/solaris/overlay/ov_network.go [hunk 6]
```diff
@@ -0,0 +1,791 @@
...
+	if err != nil {
+		return []byte{}
+	}
+
+	m["secure"] = n.secure
+	m["subnets"] = netJSON
+	m["mtu"] = n.mtu
+	b, err = json.Marshal(m)
+	if err != nil {
+		return []byte{}
```
Comment (cpuguy83) [inline vendor/github.com/docker/libnetwork/drivers/solaris/overlay/ov_network.go]: Why the allocation? Can this be a nil slice?

File: vendor/github.com/docker/libnetwork/drivers/windows/overlay/ov_endpoint_windows.go [hunk 7]
```diff
@@ -0,0 +1,346 @@
...
+	}
+
+	ep := n.endpoint(eid)
+	if ep == nil {
+		return nil, fmt.Errorf("endpoint id %q not found", eid)
+	}
+
+	data := make(map[string]interface{}, 1)
+	data["hnsid"] = ep.profileId
+	data["AllowUnqualifiedDNSQuery"] = true
```
Comment (cpuguy83) [inline vendor/github.com/docker/libnetwork/drivers/windows/overlay/ov_endpoint_windows.go]: Curious why we aren't using a struct for this.

File: vendor/github.com/docker/libnetwork/drivers/windows/overlay/ov_network_windows.go [hunk 8]
```diff
@@ -0,0 +1,512 @@
...
+
+func (d *driver) deleteNetwork(nid string) {
+	d.Lock()
+	delete(d.networks, nid)
+	d.Unlock()
+}
+
+func (d *driver) network(nid string) *network {
+	d.Lock()
+	networks := d.networks
```
Comment (cpuguy83) [inline vendor/github.com/docker/libnetwork/drivers/windows/overlay/ov_network_windows.go]: This is not safe

File: vendor/github.com/docker/libnetwork/drivers/windows/overlay/peerdb_windows.go [hunk 9]
```diff
@@ -0,0 +1,154 @@
...
+
+const ovPeerTable = "overlay_peer_table"
+
+func (d *driver) pushLocalDb() {
+	if !d.isSerfAlive() {
+		return
+	}
+
+	d.Lock()
+	networks := d.networks
```
Comment (cpuguy83) [inline vendor/github.com/docker/libnetwork/drivers/windows/overlay/peerdb_windows.go]: This is not safe

File: vendor/github.com/docker/libnetwork/drivers/windows/overlay/peerdb_windows.go [hunk 10]
```diff
@@ -0,0 +1,154 @@
...
+	d.Unlock()
+
+	for _, n := range networks {
+		n.Lock()
+		endpoints := n.endpoints
```
Comment (cpuguy83) [inline vendor/github.com/docker/libnetwork/drivers/windows/overlay/peerdb_windows.go]: This is not safe

File: vendor/github.com/docker/libnetwork/drivers/windows/windows.go [hunk 11]
```diff
@@ -440,6 +448,31 @@ func parseEndpointOptions(epOptions map[string]interface{}) (*endpointConfigurat
 	return ec, nil
 }
 
+func parseEndpointConnectivity(epOptions map[string]interface{}) (*endpointConnectivity, error) {
```
Comment (cpuguy83) [inline vendor/github.com/docker/libnetwork/drivers/windows/windows.go]: This pattern of using `map[string]interface{}` as a struct in multiple places is worrying.

**Review by cpuguy83 — COMMENTED** [review]
Couple of comments on some of the libnetwork code. I don't think they are blockers for merging, but we probably need to address at least some of them before release.

What's the easiest way to get a box up and running with a build from this PR?

File: daemon/daemon_windows.go (hunk 3 above)
Comment (msabansal) [inline daemon/daemon_windows.go]: Accepted. Fixed

File: daemon/start_windows.go (hunk 4 above)
Comment (msabansal) [inline daemon/start_windows.go]: No. If the container has N endpoints which don't have gateway libnetwork only adds one gateway. This will be common across all endpoints. This is to provide external connectivity.

Comment (mavenugo) [inline daemon/start_windows.go]: I agree. this is not different from Linux as well. But windows has a specific requirement for gw-info due to the way HNS works. So am okay with this change.

**Comment by mavenugo** [comment]
Thanks @cpuguy83. I agree. those should not block this PR. Also some of these are unrelated to Solaris and I will check with the contributor who contributed the solaris support.

File: vendor/github.com/docker/libnetwork/drivers/windows/windows.go (hunk 11 above)
Comment (mavenugo) [inline vendor/github.com/docker/libnetwork/drivers/windows/windows.go]: this is purely the endpoint options that are passed to the driver which is transparent to libnetwork core. It is key-value pair for the drivers per endpoint. So, this is okay (these are essentially map[string]string ... but historically it was `interface{}` and changing APIs is a pain and hence we left it that way. Again, this is not related to this change per-se.

**Review by mavenugo — APPROVED** [review]
Thanks @msabansal for addressing the comments.

LGTM

**Comment by mavenugo** [comment]
@cpuguy83 

> What's the easiest way to get a box up and running with a build from this PR?

I will help you with this

**Comment by msabansal** [comment]
@mavenugo Validated the basic scenarios with the latest swarmkit vendoring

**Comment by cpuguy83** [comment]
LGTM

**Comment by thaJeztah** [comment]
all green! merging :smile:

**Comment by git-jiby-me** [comment]
@marsmensch any ideas when the windows updates needed for overlay network will be released ?

**Comment by marsmensch** [comment]
you probably meant to ask @mavenugo ;-)

**Comment by thaJeztah** [comment]
@git-jiby-me I don't think there's a (public) ETA. @msabansal may know, but not sure if that information can be shared

**Comment by git-jiby-me** [comment]
@marsmensch yes exactly, sorry for the confusion there :), @thaJeztah thanks for the info, @msabansal not a problem if the information is private, i was just curious when i can try overlay.

**Comment by msabansal** [comment]
Timelines are yet to be worked out for this. Will get back as soon as we have something defined.

**Comment by git-jiby-me** [comment]
@msabansal thanks

**Comment by seankel** [comment]
@msabansal is there anyway to install the driver before the windows update? any update on timelines?

**Comment by msabansal** [comment]
@seankel Not that I can think of. I don't have any updates on timelines of the next update aswell. Perhaps @jmesser81 or @PatrickLang can help

**Comment by git-jiby-me** [comment]
@msabansal @jmesser81  @PatrickLang any updates, or any ways to try it out ?

**Comment by JMesser81** [comment]
We're working through this (bureaucratic) process now but unfortunately don't have any timelines we can provide. Feel free to ping me directly (jmesser@microsoft.com) if you have a specific Customer Proof-of-Concept you're interested in running and I'll see what I can do.

**Comment by seankel** [comment]
Were the drivers released in the latest windows update?

**Comment by git-jiby-me** [comment]
@JMesser81 i sent a mail around a month ago, but didn't get any sort of reply.

**Comment by JMesser81** [comment]
Sorry for not replying... I do have you on my list @git-jiby-me . I'm hoping in the next week or so I will have something to share. Thanks for your patience with our processes. :-(

**Comment by git-jiby-me** [comment]
@JMesser81 no worries, i just wanted to make sure that the mail got through :)

**Comment by jkaberg** [comment]
@JMesser81 I guess there is still no ETA on this? I need this particular feature to proceed with an bachelor essay I'm writing

Is it possible to simply replace this binary files with the new 1.13.1 release?

**Comment by jkaberg** [comment]
@git-jiby-me my bad, I failed to specify Windows 2016 Server which is an requirement. Updated my initial comment to make this more clear

**Comment by git-jiby-me** [comment]
@jkaberg it would take a while to see this on windows server 2016 i guess, and that would be when the feature comes out of insider previous and is considered stable.

**Comment by robymes** [comment]
I agree, Win 10 availability is good for dev environments, but the most important concern is Win 2016 Server Core: in a Swarm cluster mixed scenario (Linux _and_ Windows workers), we need the overlay network support to share the same vn between containers both on Linux workers and Windows workers.

**Comment by mllrjb** [comment]
Available on Server 2016 via https://support.microsoft.com/en-us/help/4015217/windows-10-update-kb4015217
