### PR TITLE
Fix migration diffid atomic write

### LINKED ISSUE #20267: Cannot start daemon - Failed to load layer - failed to get diff id - invalid checksum digest format
Description of problem: I cannot start the docker daemon:

```
# /usr/bin/docker daemon -H unix:///var/run/docker.sock -D

DEBU[0000] docker group found. gid: 142                 
DEBU[0000] Server created for HTTP on unix (/var/run/docker.sock) 
DEBU[0000] Using default logging driver json-file       
DEBU[0000] devicemapper: driver version is 4.34.0       
DEBU[0000] devmapper: Generated prefix: docker-8:2-3189280 
DEBU[0000] devmapper: Checking for existence of the pool docker-8:2-3189280-pool 
DEBU[0000] devmapper: Pool doesn't exist. Creating it.  
DEBU[0000] devmapper: loadDeviceFilesOnStart()          
DEBU[0000] devmapper: Loading data for file ...
...
DEBU[0000] devmapper: Skipping file /var/lib/docker/devicemapper/metadata/transaction-metadata 
DEBU[0000] devmapper: loadDeviceFilesOnStart() END      
DEBU[0000] devmapper: constructDeviceIDMap()            
DEBU[0000] devmapper: Added deviceId=5201 to DeviceIdMap 
...
DEBU[0000] devmapper: constructDeviceIDMap() END        
WARN[0000] devmapper: Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man docker` to refer to dm.thinpooldev section. 
DEBU[0000] devmapper: activateDeviceIfNeeded()          
DEBU[0000] devmapper: UUID for device: /dev/mapper/docker-8:2-3189280-base is:8a0d9344-8414-4923-8eca-214e835384d5 
WARN[0000] devmapper: Base device already exists and has filesystem ext4 on it. User specified filesystem  will be ignored. 
DEBU[0000] devmapper: deactivateDevice()                
DEBU[0000] devmapper: removeDevice START(docker-8:2-3189280-base) 
DEBU[0000] devmapper: removeDevice END(docker-8:2-3189280-base) 
DEBU[0000] devmapper: deactivateDevice END()            
INFO[0000] [graphdriver] using prior storage driver "devicemapper" 
DEBU[0000] Using graph driver devicemapper              
DEBU[0000] Failed to load layer sha256:541b14873e1aabcdf967e1205ce3be564d6f4bf7d2c895250ab80a9211390e62: failed to get diff id for sha256:541b14873e1aabcdf967e1205ce3be564d6f4bf7d2c895250ab80a9211390e62: invalid checksum digest format 
DEBU[0000] devmapper: [deviceset docker-8:2-3189280] Shutdown() 
DEBU[0000] devmapper: Shutting down DeviceSet: /var/lib/docker/devicemapper 
DEBU[0000] devmapper: deactivateDevice()                
DEBU[0000] devmapper: deactivateDevice END()            
DEBU[0000] devmapper: deactivatePool()                  
DEBU[0000] devmapper: deactivatePool END                
DEBU[0000] devmapper: [deviceset docker-8:2-3189280] Shutdown() END 
DEBU[0000] Cleaning up old shm/mqueue mounts: start.    
FATA[0000] Error starting daemon: layer does not exist  
```

`docker version`:
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Fri Feb 12 00:52:02 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

`docker info`:
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

Environment details (AWS, VirtualBox, physical, etc.):
physical, Arch Linux, kernel 4.4.1-2-ARCH

Additional info:
The file `/var/lib/docker/image/devicemapper/layerdb/sha256/541b14873e1aabcdf967e1205ce3be564d6f4bf7d2c895250ab80a9211390e62/diff` exists but it is empty. All other `diff` files in `layerdb/sha256` are 71 bytes

### PR DESCRIPTION
**Pull request by tonistiigi**
Fixes #20267

From the  #20267 debug info it seems that empty diffid file was created during the calculation phase. This makes sure that if calculation is cancelled it can not leave a layer in a broken state. There is also added validation that we don't create broken image configurations but error out if a layer diffid is not a valid digest.

cc @dmcgowan @aaronlehmann 

Signed-off-by: Tonis Tiigi tonistiigi@gmail.com

### CODE REVIEW

File: migrate/v1/migratev1.go [hunk 1]
```diff
@@ -160,7 +160,12 @@ func calculateLayerChecksum(graphDir, id string, ls checksumCalculator) error {
 		return err
 	}
 
-	if err := ioutil.WriteFile(filepath.Join(graphDir, id, migrationDiffIDFileName), []byte(diffID), 0600); err != nil {
+	tmpFile := filepath.Join(graphDir, id, migrationDiffIDFileName+".tmp")
```
Comment (aaronlehmann) [inline migrate/v1/migratev1.go]: I wonder if we should use an extension like `.migrate` to make it clearer where a stray file came from.

Comment (tonistiigi) [inline migrate/v1/migratev1.go]: All these files already have `.migration-` prefix

**Comment by aaronlehmann** [comment]
LGTM

**Comment by dmcgowan** [comment]
LGTM

**Comment by thaJeztah** [comment]
LGTM

**Comment by thaJeztah** [comment]
WindowsTP4 https://jenkins.dockerproject.org/job/Docker-PRs-WoW-TP4/1138/console :cry:

```
fatal: unable to access 'https://github.com/docker/docker.git/': transfer closed with outstanding read data remaining
21:52:38 + ec=128
21:52:38 + set +x
```

**Comment by cpuguy83** [comment]
LGTM
