### PR TITLE
Fix network inspect for default networks.

### LINKED ISSUE #17494: Can't fetch IP of container on RC3
```
docker inspect --format '{{ .NetworkSettings.IPAddress }}' workload1' 
Template parsing error: template: :1:19: executing "" at <.NetworkSettings.IPA...>: IPAddress is not a field of struct type *types.NetworkSettings
```

```
 "NetworkSettings": {
        "Bridge": "",
        "SandboxID": "be0dc9c1631d5024164dfab1adb339708efffa141cd71161195f616ae1176d18",
        "HairpinMode": false,
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "Ports": {},
        "SandboxKey": "/var/run/docker/netns/be0dc9c1631d",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null,
        "Networks": {
            "calnet": {
                "EndpointID": "266aa806f0138f29960982702694c61c11b17563d3a03b9bd8e73ef94b265d04",
                "Gateway": "\u003cnil\u003e",
                "IPAddress": "10.0.0.2",
                "IPPrefixLen": 24,
                "IPv6Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "MacAddress": ""
            }
        }
    }
```

```
$ docker version
Client:
 Version:      1.9.0-rc3
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   2100b94
 Built:        Wed Oct 28 01:32:55 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0-rc3
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   2100b94
 Built:        Wed Oct 28 01:32:55 UTC 2015
 OS/Arch:      linux/amd64

$ uname -a
Linux gulfstream 3.19.0-31-generic #36-Ubuntu SMP Wed Oct 7 15:04:02 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ docker info
Containers: 4
Images: 50
Server Version: 1.9.0-rc3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 58
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-31-generic
Operating System: Ubuntu 15.04
CPUs: 4
Total Memory: 3.86 GiB
Name: gulfstream
ID: DMI2:W6NH:AFHI:6YWS:PEND:LXD7:3GDL:YK62:4437:EATW:DW2R:AF6X
Debug mode (server): true
 File Descriptors: 38
 Goroutines: 78
 System Time: 2015-10-28T14:41:37.005300886-07:00
 EventsListeners: 0
 Init SHA1: 5e8a6db3eec2807593ebd7797fb153c6b3c331ef
 Init Path: /usr/lib/docker/dockerinit
 Docker Root Dir: /var/lib/docker
Username: tomdee
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Cluster store: etcd://127.0.0.1:2379

```

### PR DESCRIPTION
**Pull request by calavera**
- Keep old fields in NetworkSetting to respect the deprecation policy.

@tiborvass, @mavenugo please, take a look.

Fixes #17494

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

File: api/types/types.go [hunk 1]
```diff
@@ -286,6 +286,7 @@ type ContainerJSON struct {
 // NetworkSettings exposes the network settings in the api
 type NetworkSettings struct {
 	NetworkSettingsBase
+	DefaultNetworkSettings
```
Comment (tiborvass) [inline api/types/types.go]: As a note before people freak out: this is embedded, so there won't be any `DefaultNetworkSettings` key.

**Comment by dave-tucker** [comment]
:+1:

**Comment by mrjana** [comment]
:+1: on the design

**Comment by calavera** [comment]
As discussed, the api 1.20 won't show the default network IP unless the network name is bridge. Please, take another look.

File: api/types/versions/v1p20/types.go [hunk 2]
```diff
@@ -36,12 +36,6 @@ type StatsJSON struct {
...
-	EndpointID          string
-	Gateway             string
-	GlobalIPv6Address   string
-	GlobalIPv6PrefixLen int
-	IPAddress           string
-	IPPrefixLen         int
-	IPv6Gateway         string
-	MacAddress          string
+	types.DefaultNetworkSettings
+	Networks []string
```
Comment (tiborvass) [inline api/types/versions/v1p20/types.go]: we dont want Networks here

**Comment by tiborvass** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Comment by vieux** [comment]
LGTM

**Comment by vieux** [comment]
will start doing the same on swarm

**Comment by vieux** [comment]
I'm adding a test in swarm to make sure we are notified if the output change again https://github.com/vieux/swarm/blob/improve_network_inspect_test/test/integration/api/network.bats#L31

**Comment by tiborvass** [comment]
Thanks @abronan
