### PR TITLE
closes #35702 introduce « exec_die » event

### LINKED ISSUE #35702: docker event for exec_die
**Description**

As a container terminate by itself (main PID 1 process complete) an `container die` event is reported with exit code. 
As an exec process completes, docker inspect do report updated `ExecIDs` set but no event is logged. As a result, one only can monitor exec completion by polling. An `container exec_die` event would allow an asynchronous implementation.

My actual use case is to run build processes in an existing containers from a Jenkins plugin. I'd like to avoid polling this container for exec completion.

**Steps to reproduce the issue:**
1. run `docker event`
2. start a container with `sleep 100`
3. run docker exec ID echo hello

**Describe the results you received:**

logged events:
- container exec_create
- container exec_start
- container die

**Describe the results you expected:**

logged events:
- container exec_create
- container exec_start
- container exec_die
- container die

### PR DESCRIPTION
**Pull request by ndeloof**
Signed-off-by: Nicolas De Loof <nicolas.deloof@gmail.com>

**- What I did**

Implemented a new event "exec_die" when containerd report exec termination

**- How I did it**

execConfig is already updated in daemon, just added event logging

**- How to verify it**

* docker run -d ubuntu sleep 100
* docker events (on another terminal)
* docker exec $ID echo hello

events console will show "exec_die" event

**- Description for the changelog**

introduce new `exec_die` event on exec termination

**- A picture of a cute animal (not mandatory but encouraged)**

download

### CODE REVIEW

File: integration/system/event_test.go [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+			Tty:    false,
+		},
+	)
+	require.NoError(t, err)
+
+	select {
+	case m := <-msg:
+		require.Equal(t, m.Actor.Attributes["execId"], id.ID)
+	case _ = <-errors:
+		t.FailNow()
```
Comment (dnephin) [inline integration/system/event_test.go]: Would be good to `t.Fatal(err)` here so we have more information about the failure.

File: integration/system/event_test.go [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+	case <-time.After(time.Second * 3):
+		t.FailNow()
```
Comment (dnephin) [inline integration/system/event_test.go]: `t.Fatal("timeout hit")`

File: integration/system/event_test.go [hunk 3]
```diff
@@ -0,0 +1,69 @@
...
+		types.ExecStartCheck{
+			Detach: true,
+			Tty:    false,
+		},
+	)
+	require.NoError(t, err)
+
+	select {
+	case m := <-msg:
+		require.Equal(t, m.Actor.Attributes["execId"], id.ID)
```
Comment (dnephin) [inline integration/system/event_test.go]: This should probably check the other fields of the event as well, at least the event name

**Review by dnephin — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Some lint issues;

```
16:11:50 integration/system/event_test.go:1::warning: file is not gofmted with -s (gofmt)
16:11:50 integration/system/event_test.go:1::warning: file is not goimported (goimports)
```

**Comment by thaJeztah** [comment]
Can you also squash your commits? Changes look small enough to be in a single commit

File: daemon/monitor.go [hunk 4]
```diff
@@ -128,6 +128,11 @@ func (daemon *Daemon) ProcessEvent(id string, e libcontainerd.EventType, ei libc
 			// remove the exec command from the container's store only and not the
 			// daemon's store so that the exec command can be inspected.
 			c.ExecCommands.Delete(execConfig.ID, execConfig.Pid)
+			attributes := map[string]string{
+				"execId":   execConfig.ID,
```
Comment (thaJeztah) [inline daemon/monitor.go]: Generally, I think this PR looks good; I want to double check on this one with other maintainers. I think the other `exec` requests;

- have `exec_foo:<command and arguments>` as event (this was actually a mistake, but we had to keep it for backward-compatibility, and still have to work on improving that)
- do _not_ have an `execId` property; I think it's useful, but wondering if we should see this as a separate feature, and also consider adding the attribute to other `exec_xx` events (so that events can be related to each other)

FWIW, there's some weird things still with the events endpoint (e.g. "custom attributes" and "actual attributes" are merged, and can "overlap"); something that should be looked at

**Review by thaJeztah — CHANGES_REQUESTED** [review]
I'd like to have a quick check with other maintainers tomorrow at the maintainers meeting, but overall this looks good 👍

File: daemon/monitor.go (hunk 4 above)
Comment (cpuguy83) [reply daemon/monitor.go]: nit "exec_id"

**Comment by thaJeztah** [comment]
Discussing in the maintainers meeting; can you add a second commit that adds the `execId` to the other `exec` events as well? (Where possible) Then we should be able to move this forward 👍

**Comment by thaJeztah** [comment]
Thanks @ndeloof; overall this LGTM, but I have a couple of small things;

Regarding `execId` vs `exec_id` (https://github.com/moby/moby/pull/35744#discussion_r157034468), I had a quick look at existing properties (excluding top-level `ID`, `Status`, and `From` because those are deprecated),
I found `timeNano` (camelcase) and `Actor.Attributes.exitCode` (also camelcase), so I think it should be camelcase.

However, it should likely be `execID` instead of `execId`

@ndeloof can you change;

- `execId` to `execID`? (unless @cpuguy83 has objections :sweat_smile:)
- add a note to the [API version history](https://github.com/moby/moby/blob/master/docs/api/version-history.md), and document:
  - the new `exec_die` event type
  - document that the `exec_create` and `exec_start` events now also get an additional `Actor.Attributes.execID` property

Also, we should document properties in the swagger file. Looks like so far we didn't do so, so I'm ok with doing that separately in a follow-up


(example event stream below)

<details>

```json
[
  {
    "status": "pull",
    "id": "nginx:alpine",
    "Type": "image",
    "Action": "pull",
    "Actor": {
      "ID": "nginx:alpine",
      "Attributes": {
        "maintainer": "NGINX Docker Maintainers <docker-maint@nginx.com>",
        "name": "nginx"
      }
    },
    "scope": "local",
    "time": 1514553990,
    "timeNano": 1514553990091358700
  },
  {
    "status": "create",
    "id": "9833812e5cd5abd48b4c55a10cb8276b1790cc142037971c534ba885b2307e05",
    "from": "nginx:alpine",
    "Type": "container",
    "Action": "create",
    "Actor": {
      "ID": "9833812e5cd5abd48b4c55a10cb8276b1790cc142037971c534ba885b2307e05",
      "Attributes": {
        "image": "nginx:alpine",
        "maintainer": "NGINX Docker Maintainers <docker-maint@nginx.com>",
        "name": "foo"
      }
    },
    "scope": "local",
    "time": 1514553990,
    "timeNano": 1514553990219607300
  },
  {
    "Type": "network",
    "Action": "connect",
    "Actor": {
      "ID": "1d402bbfdaf4adba234cd5c09e66127cc9066e05b383d80c5a8eb734521bbbcc",
      "Attributes": {
        "container": "9833812e5cd5abd48b4c55a10cb8276b1790cc142037971c534ba885b2307e05",
        "name": "bridge",
        "type": "bridge"
      }
    },
    "scope": "local",
    "time": 1514553990,
    "timeNano": 1514553990237711000
  },
  {
    "status": "start",
    "id": "9833812e5cd5abd48b4c55a10cb8276b1790cc142037971c534ba885b2307e05",
    "from": "nginx:alpine",
    "Type": "container",
    "Action": "start",
    "Actor": {
      "ID": "9833812e5cd5abd48b4c55a10cb8276b1790cc142037971c534ba885b2307e05",
      "Attributes": {
        "image": "nginx:alpine",
        "maintainer": "NGINX Docker Maintainers <docker-maint@nginx.com>",
        "name": "foo"
      }
    },
    "scope": "local",
    "time": 1514553990,
    "timeNano": 1514553990660905000
  },
  {
    "status": "exec_create: sh ",
    "id": "9833812e5cd5abd48b4c55a10cb8276b1790cc142037971c534ba885b2307e05",
    "from": "nginx:alpine",
    "Type": "container",
    "Action": "exec_create: sh ",
    "Actor": {
      "ID": "9833812e5cd5abd48b4c55a10cb8276b1790cc142037971c534ba885b2307e05",
      "Attributes": {
        "execId": "526c1b75e58f8d66344894ecbf6645e53382ec261e3022b95211f53f959f3138",
        "image": "nginx:alpine",
        "maintainer": "NGINX Docker Maintainers <docker-maint@nginx.com>",
        "name": "foo"
      }
    },
    "scope": "local",
    "time": 1514554002,
    "timeNano": 1514554002318149400
  },
  {
    "status": "exec_start: sh ",
    "id": "9833812e5cd5abd48b4c55a10cb8276b1790cc142037971c534ba885b2307e05",
    "from": "nginx:alpine",
    "Type": "container",
    "Action": "exec_start: sh ",
    "Actor": {
      "ID": "9833812e5cd5abd48b4c55a10cb8276b1790cc142037971c534ba885b2307e05",
      "Attributes": {
        "execId": "526c1b75e58f8d66344894ecbf6645e53382ec261e3022b95211f53f959f3138",
        "image": "nginx:alpine",
        "maintainer": "NGINX Docker Maintainers <docker-maint@nginx.com>",
        "name": "foo"
      }
    },
    "scope": "local",
    "time": 1514554002,
    "timeNano": 1514554002319235000
  },
  {
    "status": "exec_die",
    "id": "9833812e5cd5abd48b4c55a10cb8276b1790cc142037971c534ba885b2307e05",
    "from": "nginx:alpine",
    "Type": "container",
    "Action": "exec_die",
    "Actor": {
      "ID": "9833812e5cd5abd48b4c55a10cb8276b1790cc142037971c534ba885b2307e05",
      "Attributes": {
        "execId": "526c1b75e58f8d66344894ecbf6645e53382ec261e3022b95211f53f959f3138",
        "exitCode": "0",
        "image": "nginx:alpine",
        "maintainer": "NGINX Docker Maintainers <docker-maint@nginx.com>",
        "name": "foo"
      }
    },
    "scope": "local",
    "time": 1514554021,
    "timeNano": 1514554021038903600
  },
  {
    "status": "kill",
    "id": "9833812e5cd5abd48b4c55a10cb8276b1790cc142037971c534ba885b2307e05",
    "from": "nginx:alpine",
    "Type": "container",
    "Action": "kill",
    "Actor": {
      "ID": "9833812e5cd5abd48b4c55a10cb8276b1790cc142037971c534ba885b2307e05",
      "Attributes": {
        "image": "nginx:alpine",
        "maintainer": "NGINX Docker Maintainers <docker-maint@nginx.com>",
        "name": "foo",
        "signal": "9"
      }
    },
    "scope": "local",
    "time": 1514554062,
    "timeNano": 1514554062808309000
  },
  {
    "status": "die",
    "id": "9833812e5cd5abd48b4c55a10cb8276b1790cc142037971c534ba885b2307e05",
    "from": "nginx:alpine",
    "Type": "container",
    "Action": "die",
    "Actor": {
      "ID": "9833812e5cd5abd48b4c55a10cb8276b1790cc142037971c534ba885b2307e05",
      "Attributes": {
        "exitCode": "137",
        "image": "nginx:alpine",
        "maintainer": "NGINX Docker Maintainers <docker-maint@nginx.com>",
        "name": "foo"
      }
    },
    "scope": "local",
    "time": 1514554063,
    "timeNano": 1514554063068919300
  },
  {
    "Type": "network",
    "Action": "disconnect",
    "Actor": {
      "ID": "1d402bbfdaf4adba234cd5c09e66127cc9066e05b383d80c5a8eb734521bbbcc",
      "Attributes": {
        "container": "9833812e5cd5abd48b4c55a10cb8276b1790cc142037971c534ba885b2307e05",
        "name": "bridge",
        "type": "bridge"
      }
    },
    "scope": "local",
    "time": 1514554063,
    "timeNano": 1514554063337964000
  },
  {
    "status": "destroy",
    "id": "9833812e5cd5abd48b4c55a10cb8276b1790cc142037971c534ba885b2307e05",
    "from": "nginx:alpine",
    "Type": "container",
    "Action": "destroy",
    "Actor": {
      "ID": "9833812e5cd5abd48b4c55a10cb8276b1790cc142037971c534ba885b2307e05",
      "Attributes": {
        "image": "nginx:alpine",
        "maintainer": "NGINX Docker Maintainers <docker-maint@nginx.com>",
        "name": "foo"
      }
    },
    "scope": "local",
    "time": 1514554063,
    "timeNano": 1514554063457728000
  }
]
```
</details>

**Comment by ndeloof** [comment]
@thaJeztah udpated to use "execID" as requested.

**Comment by thaJeztah** [comment]
Can you update the https://github.com/moby/moby/blob/master/docs/api/version-history.md as well? Then I think we'd be ready to merge 😅

**Comment by thaJeztah** [comment]
oh, and squash commits where needed

**Review by vdemeester — APPROVED** [review]
LGTM 🐮

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Argh it's doing this again;

```
15:28:41 The swagger spec at "api/swagger.yaml" is valid against swagger specification 2.0
15:28:45 The result of hack/generate-swagger-api.sh differs
15:28:45 
15:28:45  M api/types/container/container_wait.go
15:28:45 
15:28:45 Please update api/swagger.yaml with any api changes, then 
```

Let me try to add a diff to that output (because we had the same problem last time)

**Comment by mistyhacks** [comment]
@vdemeester Please add an example of this to https://github.com/docker/cli/blob/master/docs/reference/commandline/events.md so that the docs will be updated. That will need to be cherry-picked into `docker/docker-ce`. @thaJeztah CC
