### PR TITLE
Download support of images with multi-arch manifest

### LINKED ISSUE #35841: "unknown manifest mediaType" when build the binary on AArch64
**Description**
PR #35773 replace the legacy docker images with multi-arch ones on AArch64, but this PR depends on PR #35772 to support `fat manifest` images download, so it we don't have this PR merged, the `make binary` build will always trigger below error messages:
```
Step 27/34 : RUN ./contrib/download-frozen-image-v2.sh /docker-frozen-images    buildpack-deps:jessie@sha256:dd86dced7c9cd2a724e779730f0a53f93b7ef42228d4344b25ce9a42a1486251   busybox:latest@sha256:bbc3a03235220b170ba48a157dd097dd1379299370e1ed99ce976df0355d24f0    debian:jessie@sha256:287a20c5f73087ab406e6b364833e3fb7b3ae63ca0eb3486555dc27ed32c6e60   hello-world:latest@sha256:be0cd392e45be79ffeffa6b05338b98ebb16c87b255f48e297ec7f98e123905c
 ---> Running in db4f4f2bca0f
error: unknown manifest mediaType (library/buildpack-deps:jessie@sha256:dd86dced7c9cd2a724e779730f0a53f93b7ef42228d4344b25ce9a42a1486251): 'application/vnd.docker.distribution.manifest.list.v2+json'
The command '/bin/sh -c ./contrib/download-frozen-image-v2.sh /docker-frozen-images     buildpack-deps:jessie@sha256:dd86dced7c9cd2a724e779730f0a53f93b7ef42228d4344b25ce9a42a1486251   busybox:latest@sha256:bbc3a03235220b170ba48a157dd097dd1379299370e1ed99ce976df0355d24f0    debian:jessie@sha256:287a20c5f73087ab406e6b364833e3fb7b3ae63ca0eb3486555dc27ed32c6e60   hello-world:latest@sha256:be0cd392e45be79ffeffa6b05338b98ebb16c87b255f48e297ec7f98e123905c' returned a non-zero code: 1
Makefile:124: recipe for target 'build' failed
make: *** [build] Error 1
```

**Steps to reproduce the issue:**
On AArch64 platforms(If we replace the legacy with multi-arch ones on other platforms, I believe it will have the same issue):
1. pull the latest moby code
2. make binary
3. build of above step 2 will fail

**Describe the results you received:**
Build fails since it can't handle `fat manifest` with  current `contrib/download-frozen-image-v2.sh`

**Describe the results you expected:**
Build succeed to generate the binaries no matter the frozen images are legacy or multi-arch.

**Additional information you deem important (e.g. issue happens only occasionally):**
Always on AArch64 platforms.
**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 06:39:28 2017
 OS/Arch:      linux/arm64

Server:
 Version:      dev
 API version:  1.35 (minimum version 1.12)
 Go version:   go1.9.2
 Git commit:   72a3770
 Built:        Fri Dec  8 05:10:03 2017
 OS/Arch:      linux/arm64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 63
 Running: 0
 Paused: 0
 Stopped: 63
Images: 574
Server Version: dev
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729 (expected: v1.0.0)
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.9.0-16-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: aarch64
CPUs: 46
Total Memory: 94.26 GiB
Name: ubuntu
ID: 3SLK:XAG2:2XMR:JADN:2NQ4:DGGO:PV7G:T5LN:FXSD:N5VU:JCZX:SWZS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: arm64b
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by arm64b**
Currently we only support 'application/vnd.docker.distribution.manifest.v2+json'
manifest images download, with more multi-arch images used, we need to support
download images with 'application/vnd.docker.distribution.manifest.list.v2+json'
format(aka "fat manifest"), else we will fail to download those multi-arch images.

This PR adds 'application/vnd.docker.distribution.manifest.list.v2+json' manifest
support, thus we can download both multi-arch and legacy images.

Fix: #35841

Signed-off-by: Dennis Chen <dennis.chen@arm.com>

**- What I did**
Add 'application/vnd.docker.distribution.manifest.list.v2+json' manifest images download support. 
**- How I did it**
Get the first level manifest, if it's a 'fat manifest', then get the 2nd level manifest which can match the run time arch.
**- How to verify it**
After apply the patch, `make binary` & `make  test-integration` upon both legacy and multi-arch docker images, on both arm64 and amd64 platforms.
**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**
summit

### CODE REVIEW

**Comment by arm64b** [comment]
This PR doesn't affect the existing behavior of current implementation, but it adds 'fat manifest' support thus we can download those multi-arch ones. As a easy way to test it, we can change the 4 docker images on amd64 to the counterparts in #35773 , the download will still succeed. 
/cc @tianon @dnephin , any comments? 🎉

File: contrib/download-frozen-image-v2.sh [hunk 1]
```diff
@@ -28,6 +27,9 @@ shift || usage 1 >&2
 [ $# -gt 0 -a "$dir" ] || usage 2 >&2
 mkdir -p "$dir"
 
+# get runtime arch (current for arm64 and amd64 only)
+arch=`uname -m | sed 's/aarch64/arm64/;s/x86_64/amd64/'`
```
Comment (tianon) [inline contrib/download-frozen-image-v2.sh]: Any arch detection based on `uname` makes me queasy (I too often build 32bit userspace on a 64bit kernel, for example), so I'd prefer if we used `go env GOARCH` or `dpkg --print-architecture` or something userspace-based for this sort of detection.  One benefit of using `go env GOARCH` would be that it should return the expected values out-of-the-box, and only `arm` will be slightly complicated.

File: contrib/download-frozen-image-v2.sh [hunk 2]
```diff
@@ -80,6 +82,109 @@ fetch_blob() {
 	fi
 }
 
+# handle 'application/vnd.docker.distribution.manifest.v2+json' manifest
+handle_single_manifest_v2() {
+	local manifestJson="$1"; shift
+
+	configDigest="$(echo "$manifestJson" | jq --raw-output '.config.digest')"
+	imageId="${configDigest#*:}" # strip off "sha256:"
```
Comment (tianon) [inline contrib/download-frozen-image-v2.sh]: Please use `local` for all variables introduced/local to this function, as in `fetch_blob`.

File: contrib/download-frozen-image-v2.sh [hunk 3]
```diff
@@ -119,105 +225,39 @@ while [ $# -gt 0 ]; do
...
-										"Image": "",
-										"Volumes": null,
-										"WorkingDir": "",
-										"Entrypoint": null,
-										"OnBuild": null,
-										"Labels": null
-									}
-								}
-							EOJSON
+						m_arch="$(echo "$layerMeta" | jq --raw-output '.platform.architecture')"
```
Comment (tianon) [inline contrib/download-frozen-image-v2.sh]: Let's stick to a single variable naming format -- the rest of this file uses `camelCase`.

File: contrib/download-frozen-image-v2.sh [hunk 4]
```diff
@@ -119,105 +225,39 @@ while [ $# -gt 0 ]; do
...
+						if [ $m_arch = "$arch" ]; then
```
Comment (tianon) [inline contrib/download-frozen-image-v2.sh]: `$m_arch` here should be quoted too

File: contrib/download-frozen-image-v2.sh [hunk 5]
```diff
@@ -119,105 +225,39 @@ while [ $# -gt 0 ]; do
...
+							submanifestJson="$(
+								curl -fsSL \
+									-H "Authorization: Bearer $token" \
+									-H 'Accept: application/vnd.docker.distribution.manifest.v2+json' \
+									-H 'Accept: application/vnd.docker.distribution.manifest.list.v2+json' \
+									-H 'Accept: application/vnd.docker.distribution.manifest.v1+json' \
+									"$registryBase/v2/$image/manifests/$digest"
+							)"
+							handle_single_manifest_v2 "$submanifestJson"
+							found=1
```
Comment (tianon) [inline contrib/download-frozen-image-v2.sh]: Shouldn't this `break` so that we don't continue parsing entries? (I believe Docker's current implementation uses the first entry which matches)

File: contrib/download-frozen-image-v2.sh [hunk 6]
```diff
@@ -119,105 +225,39 @@ while [ $# -gt 0 ]; do
...
-
-					manifestJsonEntry="$(
-						echo '{}' | jq --raw-output '. + {
-							Config: "'"$configFile"'",
-							RepoTags: ["'"${image#library\/}:$tag"'"],
-							Layers: '"$(echo '[]' | jq --raw-output ".$(for layerFile in "${layerFiles[@]}"; do echo " + [ \"$layerFile\" ]"; done)")"'
-						}'
-					)"
-					manifestJsonEntries=( "${manifestJsonEntries[@]}" "$manifestJsonEntry" )
+					if [ $found -eq 0 ]; then
```
Comment (tianon) [inline contrib/download-frozen-image-v2.sh]: `$found` should be quoted here too, and if we initialize it to the empty string instead of `0`, this could instead simply be `[ -z "$found" ]`

File: hack/make/.detect-daemon-osarch [hunk 7]
```diff
@@ -62,6 +62,9 @@ case "$PACKAGE_ARCH" in
 				;;
 		esac
 		;;
+	aarch64)
+		DOCKERFILE="Dockerfile.$PACKAGE_ARCH"
+		;;
```
Comment (tianon) [inline hack/make/.detect-daemon-osarch]: Is this here simply to skip `TEST_IMAGE_NAMESPACE`?  It seems like it'd be more appropriate to put an `if` in the `*` block here, wouldn't it?  Don't we still need to set it to _something_, or is the empty value handled OK elsewhere?

**Review by tianon — COMMENTED** [review]
Approach seems generally OK to me, just a few comments on the implementation.

File: contrib/download-frozen-image-v2.sh (hunk 1 above)
Comment (arm64b) [reply contrib/download-frozen-image-v2.sh]: Absolutely 👍  "$(go env GOARCH)"

File: contrib/download-frozen-image-v2.sh (hunk 5 above)
Comment (arm64b) [reply contrib/download-frozen-image-v2.sh]: Yes, should `break` the loop if find the first matched entry.

**Review by arm64b — COMMENTED** [review]
Done!

File: hack/make/.detect-daemon-osarch (hunk 7 above)
Comment (arm64b) [reply hack/make/.detect-daemon-osarch]: The reason to skip `TEST_IMAGE_NAMESPACE` here is we've already switched to the multi-arch images on AArch64, so we don't need a name space like `aarch64/` any more order to pass the `test-integration`. I think we will not need `TEST_IMAGE_NAMESPACE` if we switch all the legacy images to  multi-arch ones in the future. But now let's it be and I add a `if` in the `*` block to handle AArch64 specific.

**Comment by arm64b** [comment]
Thanks @tianon  for the careful review! Sincerely I want to give you a "赞"(a.k.a 👍 ) 😂😂
I've finished the changes according to your comments and will force a push soon.

**Comment by thaJeztah** [comment]
restarting janky; https://jenkins.dockerproject.org/job/Docker-PRs/47116/console

```
07:04:21 ----------------------------------------------------------------------
07:04:21 FAIL: check_test.go:366: DockerSwarmSuite.TearDownTest
07:04:21 
07:04:21 check_test.go:371:
07:04:21     d.Stop(c)
07:04:21 daemon/daemon.go:395:
07:04:21     t.Fatalf("Error while stopping the daemon %s : %v", d.id, err)
07:04:21 ... Error: Error while stopping the daemon d4cd7d275ce84 : exit status 130
07:04:21 
07:04:21 
07:04:21 ----------------------------------------------------------------------
07:04:21 PANIC: docker_api_swarm_service_test.go:201: DockerSwarmSuite.TestAPISwarmServicesUpdateStartFirst
07:04:21 
07:04:21 [d4cd7d275ce84] waiting for daemon to start
07:04:21 [d4cd7d275ce84] daemon started
07:04:21 
07:04:21 [d4cd7d275ce84] daemon started
07:04:21 Attempt #2: daemon is still running with pid 8906
07:04:21 Attempt #3: daemon is still running with pid 8906
07:04:21 Attempt #4: daemon is still running with pid 8906
07:04:21 [d4cd7d275ce84] exiting daemon
07:04:21 ... Panic: Fixture has panicked (see related PANIC)
07:04:21 
```

**Comment by arm64b** [comment]
hmm, this is so nice 😂 I really don't want to see the 'red-cross' :) Thanks @thaJeztah !

**Comment by arm64b** [comment]
ping @tianon @dnephin @estesp @coolljt0725 , Hi guys, I know this is a holiday season(I am in vacation too now), but I still want to get connect to some of yous about this PR. I just kick of a new issue #35841 which is depends on this PR. I hope can get some feedback/comments from you guys and see how we can move forward for the next step.

**Comment by seemethere** [comment]
Can confirm that this fixes build issues on aarch64

**Review by tianon — APPROVED** [review]
Looks great to me generally, just one more point of clarification.  I'm happy with it! :+1:

File: hack/make/.detect-daemon-osarch [hunk 8]
```diff
@@ -64,7 +64,9 @@ case "$PACKAGE_ARCH" in
 		;;
 	*)
 		DOCKERFILE="Dockerfile.$PACKAGE_ARCH"
-		TEST_IMAGE_NAMESPACE="$PACKAGE_ARCH"
+		if [ "$PACKAGE_ARCH" != "aarch64" ]; then
+			TEST_IMAGE_NAMESPACE="$PACKAGE_ARCH"
+		fi
```
Comment (tianon) [inline hack/make/.detect-daemon-osarch]: The idea here is that eventually we can remove this per-arch block entirely, right? (and possibly even use the same `Dockerfile` verbatim across arches?)

(Forgot to add this comment to my "review" hahaha :innocent:)

Comment (arm64b) [reply hack/make/.detect-daemon-osarch]: Right. With multi-arch images used across all the platforms supported, IMO it does make sense to unify the `Dockerfile` across arches, consequently `TEST_IMAGE_NAMESPACE` here should be removed in the future in that case(suppose I am not missing something for this reply😂)

**Review by estesp — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
looks like @tianon's question was answered, so let's merge 👍
