### PR TITLE
c8d/save-load: Reimplement non-c8d idiosyncrasies

### LINKED ISSUE #45461: possible `docker save -o` regression with containerd storage: now only looks for `:latest` tag?
### Description

When [using](https://docs.docker.com/engine/reference/commandline/save/) `docker save -o` on `docker-ce 24.0.0-rc.1` on `Ubuntu 22.04 LTS (arm64)` with `containerd` storage enabled, the command seems to always look for the `:latest` tag and does not save images from all tags. If no `:latest` tag exists for the image, the `tar` archive is not created:

> Error response from daemon: No such image: debian-test-save:latest

I believe this is a regression as without `containerd`, all images that match the specified name are saved to the `tar` file, even if there is no image with the `:latest` tag.

### With `containerd` storage ENABLED: (`tar` file is NOT created if `:latest` tag doesn't exist for the image) ❌
````bash
root@ubuntu-linux-22-04-desktop:/home/parallels/docker-save# cat /etc/docker/daemon.json 
{"features":{"containerd-snapshotter":true}}
````

````bash
 Server Version: 24.0.0-rc.1
 Storage Driver: overlayfs
  driver-type: io.containerd.snapshotter.v1
````

````bash
root@ubuntu-linux-22-04-desktop:/home/parallels/docker-save# echo "FROM debian" > Dockerfile && docker build -t debian-test-save:not-latest . && docker build -t debian-test-save:another-tag .

root@ubuntu-linux-22-04-desktop:/home/parallels/docker-save# docker images | grep debian-test-save
debian-test-save                     another-tag   fdfb3f4e3609   25 hours ago   118MB
debian-test-save                     not-latest    fdfb3f4e3609   25 hours ago   118MB

root@ubuntu-linux-22-04-desktop:/home/parallels/docker-save# docker save -o debian-test-save.tar debian-test-save
Error response from daemon: No such image: debian-test-save:latest

root@ubuntu-linux-22-04-desktop:/home/parallels/docker-save# ls
Dockerfile
````

### With `containerd` storage DISABLED: (`tar` file is created even if `:latest` tag doesn't exist for the image) ✅
````bash
root@ubuntu-linux-22-04-desktop:/home/parallels/docker-save# mv /etc/docker/daemon.json /etc/docker/daemon.json.bk
root@ubuntu-linux-22-04-desktop:/home/parallels/docker-save# systemctl restart docker
````

````
Server Version: 24.0.0-rc.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
````

````
root@ubuntu-linux-22-04-desktop:/home/parallels/docker-save# docker images | grep debian-test-save
debian-test-save                     another-tag   fdfb3f4e3609   25 hours ago   118MB
debian-test-save                     not-latest    fdfb3f4e3609   25 hours ago   118MB

root@ubuntu-linux-22-04-desktop:/home/parallels/docker-save# docker save -o debian-test-save.tar debian-test-save

root@ubuntu-linux-22-04-desktop:/home/parallels/docker-save# ls
Dockerfile  debian-test-save.tar
````

Thank you for looking into this and please let me know if you need any other info from my end!

### Reproduce

1. `echo "FROM debian" > Dockerfile && docker build -t debian-test-save:not-latest . && docker build -t debian-test-save:another-tag .`
2. `docker images | grep debian-test-save`
3. `docker save -o debian-test-save.tar debian-test-save`

### Expected behavior

A `debian-test-save.tar` file should be created with these two images:

1. `debian-test-save:not-latest`
2. `debian-test-save:another-tag`

### docker version

```bash
Client: Docker Engine - Community
 Version:           24.0.0-rc.1
 API version:       1.43
 Go version:        go1.20.3
 Git commit:        eabb927
 Built:             Thu Apr 27 00:54:39 2023
 OS/Arch:           linux/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.0-rc.1
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.3
  Git commit:       f117aef
  Built:            Thu Apr 27 00:54:39 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:        v1.1.5-0-gf19387a
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    24.0.0-rc.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.3
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 24.0.0-rc.1
 Storage Driver: overlayfs
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-41-generic
 Operating System: Ubuntu 22.04 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.743GiB
 Name: ubuntu-linux-22-04-desktop
 ID: 92a5937f-8fcf-4a96-bec4-6f0d89281ce6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by vvoland**
- Fixes: https://github.com/moby/moby/issues/45461

Changes:
1. Implement a behavior from the graphdriver's export where `docker save something` (untagged reference) would export all images matching the specified repository.

2. Don't save image name/reference if it was selected by a digest. This is a bit weird behavior, and we probably should have a flag to allow to opt-out/opt-in, but it seems to be an explicit behavior and there's a test that checks for it (`TestSaveLoadNoTag`).

3. Fix `docker load` message not outputting image tag.

**- How to verify it**
```bash
$ make TEST_FILTER='(TestSave|TestLoad)' \
             TEST_IGNORE_CGROUP_CHECK=1 \
             DOCKER_GRAPHDRIVER=overlayfs \
             TEST_INTEGRATION_USE_SNAPSHOTTER=1 \
             test-integration
```

<details>
<summary>Diff</summary>

```diff
-=== Failed
-=== FAIL: arm64.integration.image TestSaveRepoWithMultipleImages (1.69s)
-    save_test.go:126: assertion failed: error is not nil: Error response from daemon: No such image: foobar-save-multi-images-test:latest
-
=== FAIL: arm64.integration.image TestSaveCheckTimes (0.23s)
    save_test.go:81: assertion failed: 2020-06-02T21:39:45Z (string) != 1970-01-01T00:00:00Z (string): expected: 2020-06-02 21:39:45.374289041 +0000 UTC, actual: 1970-01-01 00:00:00 +0000 UTC
There was a fire near the place I live and I feel as though I have been smoking smuggled russian ciggarettes every day for 50 years.
-DONE 3 tests, 2 failures in 4.721s
+DONE 3 tests, 1 failure in 4.723s
...
-=== Skipped
-=== SKIP: arm64.integration-cli TestDockerSchema1RegistrySuite (0.01s)
-    check_test.go:368: testEnv.UsingSnapshotter()
-
-=== Failed
-=== FAIL: arm64.integration-cli TestDockerCLISaveLoadSuite/TestLoadZeroSizeLayer (0.19s)
-    docker_cli_save_load_test.go:199: assertion failed:
-        Command:  /usr/local/cli-integration/docker load -i testdata/emptyLayer.tar
-        ExitCode: 1
-        Error:    exit status 1
-        Stdout:
-        Stderr:   unrecognized image format
-
-
-        Failures:
-        ExitCode was 1 expected 0
-        Expected no error
-    --- FAIL: TestDockerCLISaveLoadSuite/TestLoadZeroSizeLayer (0.19s)
-
-=== FAIL: arm64.integration-cli TestDockerCLISaveLoadSuite/TestSaveAndLoadRepoFlags (0.84s)
-    docker_cli_save_load_test.go:160: assertion failed:
-        --- before
-        +++ after
-        @@ -71,5 +71,5 @@
-                 },
-                 "Metadata": {
-        -            "LastTagTime": "2023-09-22T11:20:58.556805794Z"
-        +            "LastTagTime": "2023-09-22T11:20:58.64523996Z"
-                 }
-             }
-        : inspect is not the same after a save / load
-    --- FAIL: TestDockerCLISaveLoadSuite/TestSaveAndLoadRepoFlags (0.84s)
-
-=== FAIL: arm64.integration-cli TestDockerCLISaveLoadSuite/TestSaveAndLoadWithProgressBar (4.66s)
-    docker_cli_save_load_unix_test.go:87: assertion failed: expression is false: strings.Contains(out, expected)
-    --- FAIL: TestDockerCLISaveLoadSuite/TestSaveAndLoadWithProgressBar (4.66s)
-
-=== FAIL: arm64.integration-cli TestDockerCLISaveLoadSuite/TestSaveLoadNoTag (0.78s)
-    docker_cli_save_load_test.go:254: assertion failed: strings.Contains(out, "Loaded image: ") is true
-    --- FAIL: TestDockerCLISaveLoadSuite/TestSaveLoadNoTag (0.78s)
-
-=== FAIL: arm64.integration-cli TestDockerCLISaveLoadSuite/TestSaveLoadParents (1.68s)
-    docker_cli_save_load_test.go:224: tmpdir /tmp/save-load-parents1920803891
-    docker_cli_save_load_test.go:233: assertion failed:  (inspectOut string) != sha256:895384f1ece8c022db097c18c965b586b69a52cec7ea3d8ea5d4befe37c1c4a1 (idFoo string)
-    --- FAIL: TestDockerCLISaveLoadSuite/TestSaveLoadParents (1.68s)
-
-=== FAIL: arm64.integration-cli TestDockerCLISaveLoadSuite/TestSaveMultipleNames (0.20s)
-    docker_cli_save_load_test.go:188: assertion failed: error is not nil: exit status 1: failed to save multiple repos: , exit status 1
-    --- FAIL: TestDockerCLISaveLoadSuite/TestSaveMultipleNames (0.20s)
-
-=== FAIL: arm64.integration-cli TestDockerCLISaveLoadSuite/TestSaveSingleTag (0.22s)
-    docker_cli_save_load_test.go:100: assertion failed: error is not nil: exit status 1: failed to save repo with image ID and 'repositories' file: , exit status 1
-    --- FAIL: TestDockerCLISaveLoadSuite/TestSaveSingleTag (0.22s)
-
-=== FAIL: arm64.integration-cli TestDockerCLISaveLoadSuite (11.84s)
-
-DONE 62 tests, 1 skipped, 8 failures in 12.239s
+PASS
+
+=== Skipped
+=== SKIP: arm64.integration-cli TestDockerCLISaveLoadSuite/TestLoadZeroSizeLayer (0.11s)
+    docker_cli_save_load_test.go:230: testEnv.UsingSnapshotter(): input archive is not OCI compatible
+    --- SKIP: TestDockerCLISaveLoadSuite/TestLoadZeroSizeLayer (0.11s)
+
+=== SKIP: arm64.integration-cli TestDockerCLISaveLoadSuite/TestSaveAndLoadWithProgressBar (0.09s)
+    docker_cli_save_load_unix_test.go:76: testEnv.UsingSnapshotter(): TODO: Not implemented yet
+    --- SKIP: TestDockerCLISaveLoadSuite/TestSaveAndLoadWithProgressBar (0.09s)
+
+=== SKIP: arm64.integration-cli TestDockerCLISaveLoadSuite/TestSaveLoadParents (0.10s)
+    docker_cli_save_load_test.go:241: testEnv.UsingSnapshotter(): Parent image property is not supported with containerd
+    --- SKIP: TestDockerCLISaveLoadSuite/TestSaveLoadParents (0.10s)
+
+=== SKIP: arm64.integration-cli TestDockerSchema1RegistrySuite (0.01s)
+    check_test.go:368: testEnv.UsingSnapshotter()
+
+DONE 62 tests, 4 skipped in 10.034s
```

</details>

**- Description for the changelog**
```release-note
- containerd-integration: `docker save` is now able to export images from all tags of the repository
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: integration-cli/docker_cli_save_load_unix_test.go [hunk 1]
```diff
@@ -71,6 +72,9 @@ func (s *DockerCLISaveLoadSuite) TestSaveAndLoadRepoStdout(c *testing.T) {
 }
 
 func (s *DockerCLISaveLoadSuite) TestSaveAndLoadWithProgressBar(c *testing.T) {
+	// TODO(vvoland): https://github.com/moby/moby/issues/43910
+	skip.If(c, testEnv.UsingSnapshotter(), "TODO: Not implemented yet")
```
Comment (vvoland) [inline integration-cli/docker_cli_save_load_unix_test.go:76]: Added a skip, because it's just a visual nuisance which doesn't affect the save/load itself and we have a tracking issue for  it.

Let me know if you think we should leave this one failing until we really fix it.

File: daemon/containerd/image_exporter.go [hunk 2]
```diff
@@ -115,6 +129,84 @@ func (i *ImageService) ExportImage(ctx context.Context, names []string, outStrea
...
+				continue
+			}
+		}
+
+		if resolveErr != nil {
+			return resolveErr
+		}
+		if refErr != nil {
+			return refErr
+		}
```
Comment (vvoland) [inline daemon/containerd/image_exporter.go:201]: This is gross and ugly, but I didn't had an idea how to make it better while maintaining the overall behavior 🙈 

Please let me know if you have suggestions here.

File: integration-cli/docker_cli_save_load_unix_test.go (hunk 1 above)
Comment (rumpl) [reply integration-cli/docker_cli_save_load_unix_test.go:76]: Let's leave it failing for now, we should only skip those that don't make sense with containerd, and this one looks like a low hanging fruit?

File: daemon/containerd/image_exporter.go (hunk 2 above)
Comment (thaJeztah) [reply daemon/containerd/image_exporter.go:201]: I think it's good to implement these oddities, but we should keep a list, and create tracking issues. Some of those (from the top of my head);


- API: `image` (without `:tag`) on `push` and `pull` meaning "all tags".
    - I _THINK_ there's a tracking issue for that, but we should deprecate that (possibly as breaking change or "versioned"), and require an `?all-tags` option in the API.
    - For `pull` we could even consider deprecating _entirely_, as this involves querying (scraping) the registry to get a list of all tags
    - Instead, we could _require_ a list of tags to pull (or just one "request per tag") (TBD)
- For `image save`: similar;
    - Make sure we have some endpoint that allows returning a list of tags for images with the same `name`
    - That endpoint can be used by the client to query the list
    - After which the client can send the list of `image:tag`'s to save
    - (We can provide a utility function for this in the sdk / client to handle all this)

File: integration-cli/docker_cli_save_load_unix_test.go (hunk 1 above)
Comment (vvoland) [reply integration-cli/docker_cli_save_load_unix_test.go:76]: It's not that easy, as we need to show the progress for each imported layer (like pull) which isn't directly exposed by the containerd's `archive.ImportIndex`.

Comment (vvoland) [reply integration-cli/docker_cli_save_load_unix_test.go:76]: For reference, this is the progress that's missing:
```
$ docker load -i b.tar
3694737149b1: Loading layer [==================================================>]  1.917MB/1.917MB
Loaded image ID: sha256:1e9bbbbb28889a02334e8003b19c81bd7fc778d9257a82cd308730890fe2c4a7
```

Currently with c8d it's only:
```
$ docker load -i b.tar
Loaded image ID: sha256:1e9bbbbb28889a02334e8003b19c81bd7fc778d9257a82cd308730890fe2c4a7
```

File: daemon/containerd/image_exporter.go (hunk 2 above)
Comment (rumpl) [reply daemon/containerd/image_exporter.go:201]: @thaJeztah maybe open an issue, this comment will be lost

File: integration-cli/docker_cli_save_load_unix_test.go (hunk 1 above)
Comment (rumpl) [reply integration-cli/docker_cli_save_load_unix_test.go:76]: OK let's not skip this one for now, we might be able to use the same thing we use to track pull progress.

File: integration-cli/docker_cli_save_load_test.go [hunk 3]
```diff
@@ -199,6 +200,9 @@ func (s *DockerCLISaveLoadSuite) TestSaveMultipleNames(c *testing.T) {
 // The layer.tar file is actually zero bytes, no padding or anything else.
 // See issue: 18170
 func (s *DockerCLISaveLoadSuite) TestLoadZeroSizeLayer(c *testing.T) {
+	// TODO(vvoland): Create an OCI image with 0 bytes layer.
+	skip.If(c, testEnv.UsingSnapshotter(), "input archive is not OCI compatible")
```
[the remark this answers is not in the document]
Comment (vvoland) [reply integration-cli/docker_cli_save_load_test.go]: Extracted to separate PRs

File: daemon/containerd/image_exporter.go [hunk 4]
```diff
@@ -115,6 +129,84 @@ func (i *ImageService) ExportImage(ctx context.Context, names []string, outStrea
...
+	for _, name := range names {
+		target, resolveErr := i.resolveDescriptor(ctx, name)
+
+		// Check if the requested name is a truncated digest of the resolved descriptor.
+		// If yes, that means that the user specified a specific image ID so
+		// it's not referencing a repository.
+		specificDigestResolved := false
+		if resolveErr == nil {
+			nameWithoutDigestAlgorithm := strings.TrimPrefix(name, target.Digest.Algorithm().String()+":")
+			specificDigestResolved = strings.HasPrefix(target.Digest.Encoded(), nameWithoutDigestAlgorithm)
```
[the remark this answers is not in the document]
Comment (rumpl) [reply daemon/containerd/image_exporter.go:173]: Ha! indeed

File: daemon/containerd/image_exporter.go (hunk 2 above)
Comment (vvoland) [reply daemon/containerd/image_exporter.go:201]: > Make sure we have some endpoint that allows returning a list of tags for images with the same name

Wouldn't `docker images --filter "reference=<repository>:*"` be enough here?

**Review by rumpl — APPROVED** [review]

File: daemon/containerd/image_exporter.go (hunk 2 above)
Comment (thaJeztah) [reply daemon/containerd/image_exporter.go:201]: > Although, it's slightly less atomic, as theoretically the image could be deleted/some other image be added in between.

Yeah, but also not sure if the current daemon-side code _actually_ protects against that case; we're also iterating over names, and don't "lock the world" during the export, so it's gonna be racy in either case.  Time between getting that list and using it will be shorter, but we can't provide any certainty as well (just "slightly less likely to be hit")

**Review by thaJeztah — APPROVED** [review]
changes LGTM; left one comment (but let me know if you agree or want to merge as-is)

**Review by thaJeztah — APPROVED** [review]
still LGTM, thanks!
