### PR TITLE
Fix volume not working after daemon restart

### LINKED ISSUE #25821: [v1.12.1] Named volume can't be used after daemon reboot
1) Create a named volume `docker volume create --name myvol`
2) Using this volume works fine: `docker run -it -v myvol:/foo busybox sh`
3) Restart daemon
4) Try to start a container using the volume `docker run -it -v myvol:/foo busybox sh` returns `docker: Error response from daemon: missing device in volume options.`

Reproduced in `v1.12.1-rc2` and `master`. `v1.12.0` seems ok.

cc @tiborvass @cpuguy83 @mlaventure

### PR DESCRIPTION
**Pull request by cpuguy83**
When the daemon is started, it looks at all the volumes and checks to
see if any of them have mount options persisted to disk, and loads them
from disk if it does.

In some cases a volume will be created with an empty map causing the
options file to be persisted and volume options set to a non-nil value
on daemon restart... this causes problems later when the driver checks
for a non-nil value to determine if it should try and mount with the
persisted volume options.

Ensures 2 things:
1. Instead of only checking nilness for the opts map, use `len` to make
   sure it is not an empty map, which we don't really need to persit.
2. An empty (or nulled) opts.json will not inadvertnatly set volume
   options on daemon restart.

Fixes #25821

### CODE REVIEW

**Comment by tiborvass** [comment]
LGTM

File: volume/local/local.go [hunk 1]
```diff
@@ -90,10 +91,13 @@ func New(scope string, rootUID, rootGID int) (*Root, error) {
 		r.volumes[name] = v
 		optsFilePath := filepath.Join(rootDirectory, name, "opts.json")
 		if b, err := ioutil.ReadFile(optsFilePath); err == nil {
-			v.opts = &optsConfig{}
-			if err := json.Unmarshal(b, v.opts); err != nil {
+			opts := optsConfig{}
+			if err := json.Unmarshal(b, &opts); err != nil {
 				return nil, err
 			}
+			if !reflect.DeepEqual(opts, optsConfig{}) {
```
Comment (tonistiigi) [inline volume/local/local.go]: nit: would be good to add a comment that this is here for backwards compatibility with buggy versions.

**Comment by tonistiigi** [comment]
LGTM

File: volume/local/local.go (hunk 1 above)
Comment (tiborvass) [inline volume/local/local.go]: @cpuguy83 if you could do this in a followup that'd be appreciated :)

**Comment by samueltardieu** [comment]
What is the workaround to start containers with named volumes in 1.12 until this bug is fixed?

**Comment by cpuguy83** [comment]
I don't think there was ever a release where it was broken
