### PR TITLE
Ensure reader position is at the end after tailing

### LINKED ISSUE #15199: unable tail logs
docker version:
Client:
 Version:      1.8.0-rc1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   4f1c66a
 Built:        Sat Jul 25 05:54:28 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.0-rc1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   4f1c66a
 Built:        Sat Jul 25 05:54:28 UTC 2015
 OS/Arch:      linux/amd64

docker info:

Containers: 1
Images: 41
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 45
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-59-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 1.955 GiB
Name: aliyun
ID: 4F2J:TRGP:BCNT:WP5C:E62W:QV3B:6GBZ:A7B7:F7OX:5DBG:H7R6:2DMK
WARNING: No swap limit support

uname -a:

Linux aliyun 3.13.0-59-generic #98-Ubuntu SMP Fri Jul 24 21:05:26 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Provide additional environment details (AWS, VirtualBox, physical, etc.):

List the steps to reproduce the issue:
1. execute command "docker logs -f --tail 100 container_name"
2.
3.

Describe the results you received:
It output some logs and then break back to shell prompt.

Describe the results you expected:
the logs output continuous.

### PR DESCRIPTION
**Pull request by cpuguy83**
After tailing a file, if the number of lines requested is > the number
of lines in the file, this would cause a json unmarshalling error to
occur when we later try to go follow the file.
So brute force set it to the end if any tailing occurred.

There is potential that there could be some missing log messages if logs
are being written very quickly, however I was not able to make this
happen even with `while true; do echo hello; done`, so this is probably
acceptable.

While testing this I also found a panic in LogWatcher.Close can be
called twice due to a race. So instead of using a plain channel for this
notification, use pubsub Publisher to ensure close isn't called 2x on a
channel.

Fixes #15199

### CODE REVIEW

**Comment by calavera** [comment]
@cpuguy83 do you think we can have a regression test for this? code LGTM.

File: daemon/logger/logger.go [hunk 1]
```diff
@@ -57,7 +58,7 @@ type LogWatcher struct {
 	Msg chan *Message
 	// For sending error messages that occur while while reading logs.
 	Err           chan error
-	closeNotifier chan struct{}
+	closeNotifier *pubsub.Publisher
```
Comment (LK4D4) [inline daemon/logger/logger.go]: I don't get this change. Pubsub isn't intended to be used as notifier.

Comment (cpuguy83) [inline daemon/logger/logger.go]: Otherwise I'd either have to store some state about the LogWatcher having already been closed and use a mutex, or essentially implement what the publisher's Close function does.
I can change, this just made it super tiny.

The reason for the change is I found a race while testing this issue where by the client has closed so Close is called, and then called `docker rm -f` on the container, and Close was called again because the reader was not yet evicted.

Comment (calavera) [inline daemon/logger/logger.go]: I wonder if we could use `sync.Once` to close the channel only once.

Comment (cpuguy83) [inline daemon/logger/logger.go]: That makes sense!

Comment (LK4D4) [inline daemon/logger/logger.go]: Also, we already used close-only-once pattern in code(should be in monitor), it includes select on this channel and close in default.

Comment (tiborvass) [inline daemon/logger/logger.go]: @cpuguy83 Let's try with sync.Once

File: daemon/logger/jsonfilelog/jsonfilelog.go [hunk 2]
```diff
@@ -301,7 +302,7 @@ func tailFile(f io.ReadSeeker, logWatcher *logger.LogWatcher, tail int, since ti
 		msg, err := decodeLogLine(dec, l)
 		if err != nil {
 			if err != io.EOF {
-				logWatcher.Err <- err
+				logWatcher.Err <- fmt.Errorf("error while tailing logs: %v", err)
```
Comment (crosbymichael) [inline daemon/logger/jsonfilelog/jsonfilelog.go]: this will shodow the real error if anything above this function is trying to check for error types like io.EOF or os.IsNotExist

**Comment by cpuguy83** [comment]
@calavera I had a test, but it's quite difficult to trigger via test and can't make it fail on master.

**Comment by cpuguy83** [comment]
Also updated with sync.Once.

File: daemon/logger/logger.go [hunk 3]
```diff
@@ -71,7 +73,9 @@ func NewLogWatcher() *LogWatcher {
 
 // Close notifies the underlying log reader to stop.
 func (w *LogWatcher) Close() {
-	close(w.closeNotifier)
+	w.closeOnce.Do(func() {
```
Comment (LK4D4) [inline daemon/logger/logger.go]: Told about this https://github.com/docker/docker/blob/master/daemon/monitor.go#L262
Once ok too.

Comment (cpuguy83) [inline daemon/logger/logger.go]: Oh that's cool, I like that better.

Comment (cpuguy83) [inline daemon/logger/logger.go]: updated again.

**Comment by LK4D4** [comment]
@cpuguy83 LGTM, but you would mind to update commit message before merge?

**Comment by cpuguy83** [comment]
@LK4D4 Done.

**Comment by LK4D4** [comment]
LGTM

**Comment by calavera** [comment]
cherry picked into #15091
