### PR TITLE
Use certs.d from XDG_CONFIG_HOME when in rootless mode (fixes #40236)

### LINKED ISSUE #40236: Docker rootless dies when unable to read /etc/docker/certs.d
**Description**

**Steps to reproduce the issue:**
1. sudo mkdir -p /etc/docker/certs.d/quay.io && sudo touch /etc/docker/certs.d/quay.io/{client.cert,client.key,ca.crt} && sudo chmod 700 /etc/docker/certs.d/quay.io
2.  ./dockerd-rootless.sh --experimental
3.  docker -H unix:///run/user/<UID>/docker.sock pull quay.io/benyoo/gitlab

**Describe the results you received:**
```bash
docker -H unix:///run/user/1000/docker.sock pull quay.io/benyoo/gitlab
Using default tag: latest
Error response from daemon: open /etc/docker/certs.d/quay.io: permission denied
```

**Describe the results you expected:**
If the rootless daemon cannot read /etc/docker/certs.d, it should ignore the directory.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:52:22 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          dev
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.3
  Git commit:       649e4c8
  Built:            Mon Nov 11 12:42:03 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.3.0
  GitCommit:        36cf5b690dcc00ff0f34ff7799209050c3d0c59a
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: dev
 Storage Driver: vfs
 Logging Driver: json-file
 Cgroup Driver: none
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 36cf5b690dcc00ff0f34ff7799209050c3d0c59a
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
  rootless
 Kernel Version: 3.10.0-1062.4.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.699GiB
 Name: localhost.localdomain
 ID: ZGPZ:WCD7:AL65:BPHK:FEDC:XROH:BTT2:GS6N:V4ZJ:2W5Y:ZS7A:RPMY
 Docker Root Dir: /home/brian/.local/share/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
N/A

### PR DESCRIPTION
**Pull request by dsseng**
**- What I did**
Made Docker look for `cert.d` in `XDG_CONFIG_HOME` in rootless mode
**- How I did it**
In rootless mode, path for `certs.d` is changed to `$XDG_CONFIG_HOME/docker/certs.d`
**- How to verify it**
Check it. I think that's too simple to have a dedicated test.
**- Description for the changelog**

Use certs.d from XDG_CONFIG_HOME when in rootless mode (#40236)

**- A picture of a cute animal (not mandatory but encouraged)**
image

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]
LGTM, but we should also let rootless mode use `$XDG_CONFIG_HOME/certs.d` rather than `/etc/docker/certs.d`

**Comment by sh7dm** [comment]
@AkihiroSuda hello! Should that change go into another PR or go here too?

**Comment by AkihiroSuda** [comment]
Either is fine to me

**Comment by AkihiroSuda** [comment]
Please use real name for signing the commit

**Comment by sh7dm** [comment]
@AkihiroSuda can't you change the signoff on merge manually? if not or it's hard for you, I can recommit and force-push with my real name.

**Comment by sh7dm** [comment]
> Either is fine to me

Let's do it in a new PR, I'll try to implement that soon. New PR for logic: this one fixes a bug, the second adds a feature. Am I correct, that's a new feature?

**Comment by AkihiroSuda** [comment]
> can't you change the signoff on merge manually? if not or it's hard for you, I can recommit and force-push with my real name.

Please sign by yourself :pray:
Just `git commit -a -s --amend && git push -f`

>  New PR for logic: this one fixes a bug, the second adds a feature. Am I correct, that's a new feature?

I feel this one is a quick workaround, the second is the official bug fix.

**Comment by sh7dm** [comment]
Ahh, okay, will signoff manually. If `$XDG_CONFIG_HOME/certs.d` is a proper fix I'll implement that.

**Comment by sh7dm** [comment]
Signoff now uses my real name.

**Comment by sh7dm** [comment]
@AkihiroSuda I completed that fix, let's wait for CI to pass. Sorry, I couldn't find any test that would simulate rootless mode to check for something, so I didn't create a test.

**Review by AkihiroSuda — APPROVED** [review]

File: registry/registry.go [hunk 1]
```diff
@@ -16,6 +16,9 @@ import (
 	"github.com/docker/distribution/registry/client/transport"
 	"github.com/docker/go-connections/tlsconfig"
 	"github.com/sirupsen/logrus"
+
+	"github.com/docker/docker/pkg/homedir"
```
Comment (thaJeztah) [inline registry/registry.go]: nit: these imports should be in the same group as the previous one (not a blocker)

**Review by thaJeztah — APPROVED** [review]
LGTM

File: registry/registry.go (hunk 1 above)
Comment (sh7dm) [reply registry/registry.go]: okay, thanks.

Comment (sh7dm) [reply registry/registry.go]: okay, thanks
