### PR TITLE
Fix high cpu usage caused by docker stats.

### LINKED ISSUE #24999: [1.12rc4] docker stats infinite loop after removing containers
Removing a container with `docker rm -f` while watching its stats with `docker stats` creates a bug with docker stats that takes 99% of the CPU (or more according to the number of cores you have).

It seems to happen each time a container that 'has been seen' by `docker stats` is removed.

As indicated below, the problem is probably in the daemon rather than in the client, as it is reproducible with docker-py.

**Output of `docker version`:**
(also tested on a Fedora 24 VM with the same version of Docker client/server)
```
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 26
 Running: 1
 Paused: 0
 Stopped: 25
Images: 75
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 124
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null bridge host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: moby
ID: HFSP:6PBA:U5F4:5ZV7:EH7F:7OKJ:3ALL:PXGV:RWTY:F2RQ:JDCF:YTUW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 42
 System Time: 2016-07-25T07:44:01.746691065Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Problem occurs, at least, on the current Docker for Mac 1.12rc4-beta20 and on a Fedora 24 VM with Docker 1.12rc4.

**Steps to reproduce the issue:**
1. start a random container: `docker run -ti --name arandomname centos`, and leave it alive
2. start `docker stats`
3. remove the first container with `docker rm -f arandomname`

It also happens when I do this:
1. start `docker stats`
2. start a random container: `docker run --name arandomname centos sleep 5`, wait until it ends
3. (docker stats is still behaving properly)
4. `docker rm arandomname`

**Describe the results you received:**
CPU usage skyrockets

**Describe the results you expected:**
CPU usage remains low, as usual when using docker stats.

**Additional information you deem important (e.g. issue happens only occasionally):**
When I test the issue with docker-py, `client.stats` returns me an infinite number of None, so it probably means the issue is on the daemon side.

### PR DESCRIPTION
**Pull request by capkurmagati**
**\- How to reproduce the problem**

```
$ docker stats
# in a other terminal
$ docker run --rm alpine ping localhost
# kill it by ctrl-c
# CPU will go very high 
```

**\- What I did**
1. Close event stream when receives a `EOF` sent by server
2. Put the gorutine to sleep for 200 millisecond when the `err` is not `EOF` 
3. Terminate the command when no container is alive  

**\- How to verify it**

```
$ docker stats
# in a other terminal
$ docker run --rm alpine ping localhost
# kill it by ctrl-c
# everything is fine
```

Signed-off-by: Tianyi Wang capkurmagati@gmail.com

Fixes #24999

### CODE REVIEW

File: api/client/container/stats.go [hunk 1]
```diff
@@ -192,12 +192,23 @@ func runStats(dockerCli *client.DockerCli, opts *statsOptions) error {
...
-		for _, s := range cStats.cs {
+		for i, s := range cStats.cs {
 			if err := s.Display(w); err != nil && !opts.noStream {
 				logrus.Debugf("stats: got error for %s: %v", s.Name, err)
+				if err == io.EOF {
+					toRemove = append(toRemove, i)
+				}
 			}
 		}
+		for j := len(toRemove) - 1; j >= 0; j-- {
```
Comment (tonistiigi) [inline api/client/container/stats.go]: Isn't the `die` events already handling this part?

Comment (detheo) [inline api/client/container/stats.go]: Yes.
But when you `docker stats` with partial container id or container name, the name stored in `cStats.cs` will be the the args which could be not easy to compare to the event sent by server.

for example:
```
$docker stats 5es test  #5es is container id, test is container name
```
We can only get the container id from event, so we cannot simply remove container with name.
And for container id we don't know the length we should slice.

Please correct me if I was wrong.
And if the problem need to be solved, I would like to do that.

Comment (capkurmagati) [inline api/client/container/stats.go]: Yes. I tried to use that.
But I found if you `docker stats` with partial container id or container name, the name stored in `cStats.cs` will be the the args which could be not easy to compare to the event sent by server.

for example:
```
$docker stats 5es test  #5es is container id, test is container name
```
We can only get the container id from event, so we cannot simply remove container with name.
And for container id we don't know the length we should slice.

Please correct me if I was wrong.
And if the problem need to be solved, I would like to do that.

**Comment by capkurmagati** [comment]
@tonistiigi 
Yes. I tried to use that.
But I found that if I run `docker stats` with partial container id or container name, the name stored in `cStats.cs` will be the the args I passed with the command which causes problems.

for example:
```
$docker stats 5es test  #5es is container id, test is container name
```
We can only get the container id from event, so we cannot simply remove container with a name.
And for container id we don't know the length to slice.

Please correct me if I was wrong.
And if the problem need to be solved, I would like to do that.

**Comment by capkurmagati** [comment]
@thaJeztah Can you check on this and give me some advices please? Thank you.

**Comment by tonistiigi** [comment]
LGTM

I think this is fine for now but in the future  we should use the event handling for containers specified by the user. Probably just extend the prefixes into real IDs first.

**Comment by capkurmagati** [comment]
@tonistiigi 
Yeah, I think extending the prefixes into real IDs is a good idea.
I wonder if we can merge this pr to fix the bug and then create an another pr to implement the event handing parts.

**Comment by cpuguy83** [comment]
LGTM

**Comment by cpuguy83** [comment]
Adding to 1.12 cherry pick.
