### PR TITLE
Fix #30311: dockerd leaks ExecIds on failed exec -i

### LINKED ISSUE #30311: dockerd leaks ExecIds on failed exec -i
Each ```docker exec -i``` command leaks ExecID (and consumes dockerd memory) if command is not present in the target container. The leak is permanent. ExecIDs will not be collected by dockerd background jobs

**Steps to reproduce the issue:**
1. sudo docker run -ti --rm --name test ubuntu bash
2. sudo docker exec -i test invalidcommand
3. sudo docker inspect test | grep -A 10 ExecIDs

**Describe the results you received:**
1. number of ExecIDs increasing by one per docker exec
2. dockerd memory usage is increasing

**Describe the results you expected:**
1. number of ExecIDs is zero
2. dockerd memory usage is not increasing

**Additional information you deem important (e.g. issue happens only occasionally):**
This issue may cause more problems than someone could expect from the description. For example: I have a zabbix monitoring which collects information each minute from each container by executing ```ifconfig eth0```. But not every container contains ```ifconfig```. In such situation I have observed about 2Gb memory leak per day for dockerd.

**Output of `docker version`:**

```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:38:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:38:45 2017
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 19
 Running: 19
 Paused: 0
 Stopped: 0
Images: 31
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 136
 Dirperm1 Supported: true
Logging Driver: none
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 62.63 GiB
Name: forge
ID: ZPOD:35LZ:RAF6:RFIG:662U:2CKK:22HE:MYBM:FUBV:N2Q3:CG4Z:FQOH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

### PR DESCRIPTION
**Pull request by ijrandom**
If libcontainerd failed to start process there will be no callback about "exec done" so cleanup code should be added to ContainerExecStart
Signed-off-by: Dmitry Shyshkin <dmitry@shyshkin.org.ua>

**- What I did**
Close streams and removed ExecConfig from container in case of process failed to start
**- How I did it**
Copy part of cleanup code from containerd exec callback
**- How to verify it**
1. execute docker exec -i anycontainer invalidcommand
2. check for ExecIDs. docker inspect anycontainer | grep -A 10 ExecIDs

**- Description for the changelog**
Fix #30311: dockerd leaks ExecIds on failed exec -i

### CODE REVIEW

File: daemon/exec.go [hunk 1]
```diff
@@ -164,18 +164,23 @@ func (d *Daemon) ContainerExecStart(ctx context.Context, name string, stdin io.R
...
 			ec.Running = false
 			exitCode := 126
 			ec.ExitCode = &exitCode
+			if err := ec.CloseStreams(); err != nil {
+				logrus.Errorf("%s: %s", c.ID, err)
+			}
+			c.ExecCommands.Delete(ec.ID)
 		}
 	}()
-	ec.Unlock()
```
Comment (AkihiroSuda) [inline daemon/exec.go]: Probably no need to move these lines?

**Review by AkihiroSuda — COMMENTED** [review]
Can you please add an automated test?

**Comment by ijrandom** [comment]
added tests

**Comment by ijrandom** [comment]
On windows ```docker exec invalidcommand``` produce 500 and on linux 404. Which one need to be corrected?

**Comment by justincormack** [comment]
Should be a 4xx error.

File: daemon/exec.go (hunk 1 above)
Comment (LK4D4) [inline daemon/exec.go]: It's necessary to use `c` in defer

**Review by LK4D4 — APPROVED** [review]
LGTM

**Comment by LK4D4** [comment]
ping @docker/core-engine-maintainers

File: api/server/httputils/errors.go [hunk 2]
```diff
@@ -54,6 +54,7 @@ func GetHTTPErrorStatusCode(err error) int {
 			code    int
 		}{
 			{"not found", http.StatusNotFound},
+			{"cannot find", http.StatusNotFound},
```
Comment (dnephin) [inline api/server/httputils/errors.go]: Can we avoid expanding this "guess the status code" system further and return a specific http error instead?

File: daemon/exec.go [hunk 3]
```diff
@@ -164,18 +164,23 @@ func (d *Daemon) ContainerExecStart(ctx context.Context, name string, stdin io.R
...
 	ec.Running = true
+	ec.Unlock()
+
+	c := d.containers.Get(ec.ContainerID)
+	logrus.Debugf("starting exec command %s in container %s", ec.ID, c.ID)
+	d.LogContainerEvent(c, "exec_start: "+ec.Entrypoint+" "+strings.Join(ec.Args, " "))
+
 	defer func() {
 		if err != nil {
 			ec.Running = false
```
Comment (mlaventure) [inline daemon/exec.go]: Doesn't this needs to be protected by the lock?

File: daemon/exec.go [hunk 4]
```diff
@@ -164,18 +164,23 @@ func (d *Daemon) ContainerExecStart(ctx context.Context, name string, stdin io.R
...
 			exitCode := 126
 			ec.ExitCode = &exitCode
+			if err := ec.CloseStreams(); err != nil {
+				logrus.Errorf("%s: %s", c.ID, err)
```
Comment (mlaventure) [inline daemon/exec.go]: maybe add some context? e.g. `"failed to cleanup exec %s streams: %s"`?

**Review by mlaventure — CHANGES_REQUESTED** [review]

File: daemon/exec.go (hunk 3 above)
Comment (ijrandom) [inline daemon/exec.go]: Only if changes to ec.Running and ec.ExitCode need to be atomic. There were no lock protection in containerd callback - so I added no lock here. Should I  add the lock? Add the lock in containerd callback as well?

Comment (ijrandom) [inline daemon/exec.go]: Sorry. There was a lock. Added lock/unlock and changed message

File: daemon/exec.go (hunk 4 above)
Comment (ijrandom) [inline daemon/exec.go]: done, also changed message in  monitor.go

**Review by mlaventure — APPROVED** [review]
LGTM

File: api/server/httputils/errors.go (hunk 2 above)
Comment (LK4D4) [inline api/server/httputils/errors.go]: @dnephin can you explain a little bit more for @ijrandom ?

Comment (dnephin) [inline api/server/httputils/errors.go]: Sure, I'd be happy to.

This code that you've added to is trying to guess which http status code to return based on an error message string. Instead of guessing based on string matching, we'd like to be explicit about the error.

The explicit error is in `api/errors/errors.go` `NewRequestNotFoundError()`. Could you return that directly from the function that causes this error, instead of adding a new string to this list?

**Comment by LK4D4** [comment]
@ijrandom would you mind to fix @dnephin suggestion? Thanks!

File: integration-cli/docker_api_exec_test.go [hunk 5]
```diff
@@ -198,3 +219,29 @@ func inspectExec(c *check.C, id string, out interface{}) {
...
+		}
+
+		inspectExec(c, id, &execJSON)
+		if !execJSON.Running {
+			break
+		}
+	}
+}
+
+func inspectContainer(c *check.C, id string, out interface{}) {
```
Comment (coolljt0725) [inline integration-cli/docker_api_exec_test.go]: you can use `inspectFieldJSON` (https://github.com/docker/docker/blob/master/integration-cli/docker_utils_test.go#L554) instead.

The fix LGTM. 

It's better to squash your commits :)

File: api/server/httputils/errors.go (hunk 2 above)
Comment (ijrandom) [inline api/server/httputils/errors.go]: Just to be clear. You want to return NewRequestNotFoundError from platform specific wrapper to execv/CreateProcess?

Comment (dnephin) [inline api/server/httputils/errors.go]: Where is the error which contains the text "cannot find"?

Comment (ijrandom) [inline api/server/httputils/errors.go]: It come from the windows os when CreateProcess failed

Comment (dnephin) [inline api/server/httputils/errors.go]: Ok, is there an issue about this? I don't think we return a 404 on other platforms when  the path to a binary is incorrect.

**Review by cpuguy83 — CHANGES_REQUESTED** [review]
Let's makes sure to squash to 1 commit

File: api/server/httputils/errors.go (hunk 2 above)
Comment (ijrandom) [inline api/server/httputils/errors.go]: on linux message contains "not found" those producing 404

**Comment by ijrandom** [comment]
rebased and squashed

**Review by vdemeester — APPROVED** [review]
LGTM 🐸
