### PR TITLE
Fix volume filter validation

### LINKED ISSUE #18890: docker volume not vailidate filters for dangling value
For docker image it add related validation, but docker volume not validation for that,
we need add check for dangling value
$ docker volume ls -f dangling=trued
DRIVER              VOLUME NAME
local               myvol
local               0e86f41c7db40f1314062b68ba05a03c96ed8b3c6f72e274419ce1621ddad818
local               b2d6be23626b5a73fcef5acbd359ed6ac1a58bcb8fbdf67dbf0d6ad6e717c859
local               420aa8064029961ce34871c587fc0a346c2871cd0be0e410d9bf7730fabf096d

We should do  like this
$ docker volume ls -f dangling=trued
Error response from daemon: Invalid filter 'dangling=trued'

$docker version
Client:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   94997e5
 Built:        Mon Nov 30 23:37:05 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   94997e5
 Built:        Mon Nov 30 23:37:05 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

### PR DESCRIPTION
**Pull request by HackToday**
Fixes: #18890
This fix add same filter validation logic as images. We should
add such check to make sure filters work make sense to end-users

Here just keep old "1" here, because I think for image and volume need
further address to improve api filter interface, like both accept same, 1 or not. 
Should not different. It could be in other patch.

Signed-off-by: Kai Qiang Wu(Kennan) wkqwu@cn.ibm.com

### CODE REVIEW

**Comment by HackToday** [comment]
ping @cpuguy83

File: daemon/list.go [hunk 1]
```diff
@@ -393,15 +397,24 @@ func (daemon *Daemon) transformContainer(container *container.Container, ctx *li
...
 	}
-
-	filterUsed := volFilters.Include("dangling") &&
-		(volFilters.ExactMatch("dangling", "true") || volFilters.ExactMatch("dangling", "1"))
-
+	if err := volFilters.Validate(acceptedVolumeFilterTags); err != nil {
+		return nil, err
+	}
+	if volFilters.Include("dangling") {
+		if volFilters.ExactMatch("dangling", "true") {
```
Comment (cpuguy83) [inline daemon/list.go]: Missing the case where the value could be `"1"`

File: daemon/list.go [hunk 2]
```diff
@@ -393,15 +397,24 @@ func (daemon *Daemon) transformContainer(container *container.Container, ctx *li
...
+			filterUsed = true
+		} else if !volFilters.ExactMatch("dangling", "false") {
```
Comment (cpuguy83) [inline daemon/list.go]: Shouldn't the validator handle this case?

File: daemon/list.go (hunk 1 above)
Comment (HackToday) [inline daemon/list.go]: Hi @cpuguy83 if we checked docker images filter with dangling, it not allowed 1, only allow true.
$ docker images -f dangling=1
Error response from daemon: Invalid filter 'dangling=1'

So I think it is better to keep consistent, whether change image part, or not used "1" in volume

File: daemon/list.go (hunk 2 above)
Comment (HackToday) [inline daemon/list.go]: It follows same logic as docker images, and the Validate only check allowed name

**Comment by HackToday** [comment]
Jenkins failed for connection timeout issue, not quite sure what happened:

Cloning into '/usr/local/lvm2'...
fatal: unable to access 'https://git.fedorahosted.org/git/lvm2.git/': Failed to connect to git.fedorahosted.org port 443: Connection timed out
Removing intermediate container 57be5f6a1e52
The command '/bin/s

**Comment by thaJeztah** [comment]
I restarted the tests :)

**Comment by calavera** [comment]
We should consolidate both, volumes and images dangling validation. I don't really care which one we decide on, but we should have only 1 validation for the dangling filter, with only 1 implementation.

Removing `dangling=1` sounds like a breaking change, if anyone uses it, so maybe we should support it in the image filtering too.

**Comment by thaJeztah** [comment]
@HackToday can you address @calavera's comment? It also looks like this needs a rebase :cry:

**Comment by HackToday** [comment]
@calavera sure, 
1) I could add dangling=1 in volume, but I did not know why we just have "1"(to present true), not have "0" (false)  its inconsistent with  user interface.

2) For image, it just use dangling= true, not have "1", I did not think add another 1 to images is good idea.

@calavera  Wdyt?  
Thanks

**Comment by HackToday** [comment]
@clnperez  thanks, seems it is filter name here( filter value means dangling = "true" or "false")

**Comment by clnperez** [comment]
@HackToday , I mean the one that passes in "dangling=invalid"

**Comment by calavera** [comment]
@HackToday supporting different values in different commands is very inconsistent. Every command that supports a `dangling` filter should support the same values. Adding values to the image command is easier than removing from the volume command, because removing creates friction to users. I'm okay with adding `0` as `false` too.

This are the values I think we should support in both commands:

Truthy: `true`, `1`
Falsy: `false`, `0`

**Comment by HackToday** [comment]
@calavera PTAL for based on what we discussed so far. Thanks

File: api/types/filters/parse.go [hunk 3]
```diff
@@ -230,6 +230,24 @@ func (filters Args) Validate(accepted map[string]bool) error {
 	return nil
 }
 
+// ValidateBoolValue ensures that the field filter are valid boolean value.
+// It returns an error as soon as it finds an invalid field value.
+func (filters Args) ValidateBoolValue(field string) (bool, error) {
```
Comment (thaJeztah) [inline api/types/filters/parse.go]: Wondering if we should standardize on something like https://golang.org/pkg/strconv/#ParseBool

Comment (HackToday) [inline api/types/filters/parse.go]: Hi @thaJeztah The issue is that that function
 support 1, t, T, TRUE, true, True, 

Docker CLI/API support  just true and 1.

Wdyt ?

**Comment by HackToday** [comment]
ping @calavera  Could you take a look at this code ?


As the jenkins failed, seems that parse.go are moved in https://github.com/docker/engine-api/tree/master/types

So do I need to change engine-api first ?  Or something else ?

**Comment by HackToday** [comment]
The jenkins failed for this 
3 
04:38:23 ----------------------------------------------------------------------
04:38:23 FAIL: docker_cli_network_unix_test.go:884: TestDockerNetworkHostModeUngracefulDaemonRestart.pN59_github_com_docker_docker_integration_cli.DockerNetworkSuite
04:38:23 
04:38:23 [d86065000] waiting for daemon to start
04:38:23 [d86065000] daemon started
04:38:23 [d86065000] exiting daemon
04:38:23 [d86065000] waiting for daemon to start
04:38:23 [d86065000] daemon started
04:38:23 docker_cli_network_unix_test.go:905:
04:38:23     c.Assert(err, checker.IsNil)
04:38:23 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc208143080)} ("exit status 1")
04:38:23 
04:38:23 [d86065000] exiting daem


Seems not related with my change

**Comment by HackToday** [comment]
ping @calavera @thaJeztah

**Comment by HackToday** [comment]
PTAL, if the code is what we want. Thanks

File: daemon/list.go [hunk 4]
```diff
@@ -410,20 +414,32 @@ func (daemon *Daemon) transformContainer(container *container.Container, ctx *li
...
-	filterUsed := volFilters.Include("dangling") &&
-		(volFilters.ExactMatch("dangling", "true") || volFilters.ExactMatch("dangling", "1"))
+	if err := volFilters.Validate(acceptedVolumeFilterTags); err != nil {
+		return nil, nil, err
+	}
+
+	if volFilters.Include("dangling") {
+		if volFilters.ExactMatch("dangling", "true") || volFilters.ExactMatch("dangling", "1") {
+			danglingOnly = true
+		} else if !volFilters.ExactMatch("dangling", "false") {
```
Comment (thaJeztah) [inline daemon/list.go]: If we accept "1", I think we should also accept "0" here

Comment (thaJeztah) [inline daemon/list.go]: Oh, I see @calavera mentioned the same above here; https://github.com/docker/docker/pull/19044#issuecomment-169384131

Comment (coolljt0725) [inline daemon/list.go]: Agree with @thaJeztah 
otherwise LGTM

**Comment by HackToday** [comment]
@thaJeztah  and @calavera PTAL the new changes

**Comment by thaJeztah** [comment]
LGTM, thanks!

**Comment by HackToday** [comment]
ping @calavera  PTAL. Thanks

**Comment by calavera** [comment]
LGTM
