### PR TITLE
Remove engine

### LINKED ISSUE #10389: engine: Write to closed Output should cause an error
Currently, when `engine.Output` objects are closed, there is no state which marks it as `closed` and writes to the output after closing will fail silently.

Before [this fix](https://github.com/docker/docker/pull/10244) was merged, writes after close actually still worked and some areas of the project relied on this buggy behavior!

related to #10364 and #10371

### LINKED ISSUE #12151: Remove engine mechanism
The whole `/engine` mechanism is complicated, provides not obvious value, makes it harder to follow through the code, and ultimately complicates maintenance: let's get rid of it! 

This includes `engine.Env` as well as it is the primary motivation for this removal.  The ultimate goal is that `/engine` is deleted.

- [x] Remove jobs from `attach` #12120
- [x] Remove jobs from `builder` (wip @calavera)
- [x] Remove jobs from `builtins` #12486
- [x] Remove jobs from `commit` #12279
- [x] Remove jobs from `container_inspect` #12406
- [x] Remove jobs from `copy` #12247
- [x] Remove jobs from `daemon.networkdriver.bridge` #12092
- [x] Remove jobs from `diff` #12183
- [X] Remove jobs from `events` #12066
- [x] Remove jobs from `execCreate` #12472
- [x] Remove jobs from `execStart` (wip @wonderflow)
- [x] Remove jobs from `exec_inspect` (#12305)
- [x] Remove jobs from `export` #12313
- [x] Remove jobs from `graph` #12710
- [X] Remove jobs from `history` #12260
- [x] Remove jobs from `image_export` #12703 
- [x] Remove jobs from `image_set` #12600 
- [x] Remove jobs from `image_get` #12601
- [x] Remove jobs from `images` #12184
- [x] Remove jobs from `info` #12266
- [x] Remove jobs from `kill` #12248
- [x] Remove jobs from `load` #12579 
- [x] Remove jobs from `logs` #12304
- [x] Remove jobs from `ps` #12163
- [x] Remove jobs from `pause`/`unpause` #12249
- [x] Remove jobs from `pull`/`import` #12490
- [x] Remove jobs from `push` #12505
- [X] Remove jobs from `registry.Service` #11974
- [x] Remove jobs from `rename` #12227
- [x] Remove jobs from `resize`/`execResize` #12254
- [x] Remove jobs from `restart` #12350
- [x] Remove jobs from `rm` #12197
- [x] Remove jobs from `rmi` #12234
- [x] Remove jobs from `start`/`create` #12253
- [x] Remove jobs from `stats` #12312
- [x] Remove jobs from `stop` #12306
- [x] Remove jobs from `tag` #12358
- [x] Remove jobs from `top` #12259
- [x] Remove jobs from `wait` #12250
- [x] Remove jobs from `stats` #12312 
- [x] Remove jobs from `trust` #12564

Who will get the final PR that removes `/engine` altogether and closes the issue? :-)

### LINKED ISSUE #12255: move all integration tests to integration-cli so we can remove finally
all the tests in integration/ need to be converted to integration-cli/ so we can get rid of those tests once and for all.

### LINKED ISSUE #12713: Remove `engine` package
This one for @runcom

### PR DESCRIPTION
**Pull request by runcom**
close #12255
close #12151 
close #12713
close #10389

Related to #12905

Signed-off-by: Antonio Murdaca me@runcom.ninja

### CODE REVIEW

**Comment by jfrazelle** [comment]
:ribbon:

**Comment by runcom** [comment]
I think docs should be modified too because no more test-integration

File: api/server/server.go [hunk 1]
```diff
@@ -53,26 +51,29 @@ type ServerConfig struct {
...
 		start: make(chan struct{}),
-		eng:   eng,
 	}
-	r := createRouter(srv, eng)
+	r := createRouter(srv)
 	srv.router = r
 	return srv
 }
 
+func (s *Server) Close() {
```
Comment (runcom) [inline api/server/server.go]: maybe `Shutdown`

File: docker/daemon.go [hunk 2]
```diff
@@ -120,16 +117,15 @@ func mainDaemon() {
...
+	sup := daemon.NewSupervisor()
+	d, err := daemon.NewDaemon(daemonCfg, registryService, sup)
 	if err != nil {
-		eng.Shutdown()
-		logrus.Fatalf("Error starting daemon: %v", err)
-	}
-
-	if err := d.Install(eng); err != nil {
-		eng.Shutdown()
+		sup.ShutdownDaemon()
```
Comment (jfrazelle) [inline docker/daemon.go]: i think api.Close() should be first

File: docker/daemon.go [hunk 3]
```diff
@@ -145,9 +141,9 @@ func mainDaemon() {
 	api.AcceptConnections(d)
 
 	// Daemon is fully initialized and handling API traffic
-	// Wait for serve API job to complete
+	// Wait for serve API to complete
 	errAPI := <-serveAPIWait
-	eng.Shutdown()
+	sup.ShutdownDaemon()
```
Comment (jfrazelle) [inline docker/daemon.go]: where is the api closed here

File: docker/daemon.go (hunk 2 above)
Comment (LK4D4) [inline docker/daemon.go]: I think so too

Comment (runcom) [inline docker/daemon.go]: fixed

File: docker/daemon.go (hunk 3 above)
Comment (LK4D4) [inline docker/daemon.go]: If channel returned, then api already finished serve.

Comment (runcom) [inline docker/daemon.go]: isn't api finished here since serveAPIWait is closed/received (don't remember)

Comment (runcom) [inline docker/daemon.go]: fixed

File: api/server/server.go [hunk 4]
```diff
@@ -99,12 +100,8 @@ func (s *Server) ServeApi(protoAddrs []string) error {
...
 				return
 			}
-			s.eng.OnShutdown(func() {
-				if err := srv.Close(); err != nil {
-					logrus.Error(err)
-				}
-			})
-			if err = srv.Serve(); err != nil && strings.Contains(err.Error(), "use of closed network connection") {
+			s.servers = append(s.servers, srv)
+			if err := srv.Serve(); err != nil && strings.Contains(err.Error(), "use of closed network connection") {
```
Comment (LK4D4) [inline api/server/server.go]: You should wait for some time until ALL servers will try to close. This will return on first error IIRC.

File: api/server/server.go (hunk 1 above)
Comment (LK4D4) [inline api/server/server.go]: I like Close much more

**Comment by LK4D4** [comment]
Yeah, iptables clean is fun :)
@jfrazelle What job was protected against shutdown for this?

File: api/server/server.go (hunk 4 above)
Comment (LK4D4) [inline api/server/server.go]: I think this whole function should be rewritten:
* you need to collect errors from you need to collect errors from serving goroutines before return
* I think it is better first to collect pairs proto/addr and create all servers before serving in goroutines, which allow you to catch errors before any serve and avoid race in appending to `s.servers`. So, just reduce goroutine code to `srv.Serve`.

**Comment by LK4D4** [comment]
@runcom Just noticed that you still have supervisor. Maybe will be simpler to fix bug after moving all to `daemon.Shutdown`.

**Comment by LK4D4** [comment]
About cleanup: you probably should create `sync.Onces` for `api.Close()` and `daemon.Shutdown` and just call them in defer of `NewDaemon` too.

**Comment by LK4D4** [comment]
@runcom Ok, bug in calling `shutdowns from daemon` in `Trap`. I think all will be cool when you'll refactor it to only `api.Close` in `Trap`.

**Comment by runcom** [comment]
@LK4D4 there are still issues..
if `signal.Trap` is only used for `api.Close` then kill -9 or ctrl^c doesn't clean the daemon (nor pidfile) because only `api.Close` gets executed, instead `eng.Shutdown` was doing both close api + daemon clean
Cleaning of pidfile in docker/daemon in a defer func could work but suffers the same problem of daemon shutdown if only api.Close is trapped

**Comment by LK4D4** [comment]
@runcom Yeah, because Trap is sucks. Cleanup of graph and stuff on daemon initialization fail should be inside `NewDaemon`.
Makes sense to refactor api.Server to have `Wait()` to wait until all servers are closed, then cleanup for trap will be:
```
api.Close()
api.Wait()
daemon.Shutdown()
```
But for now you can use channel `waitAPI` or smth like this from mainDaemon.

**Comment by runcom** [comment]
@LK4D4 cool, but then how do you Trap api.Close + daemon.Shutdown? because old behaviour was trap api.Close + d.Shutdown from engine.Shutdown

**Comment by LK4D4** [comment]
You can create closure with any functions you want.

**Comment by LK4D4** [comment]
I wonder why janky is red :/

**Comment by runcom** [comment]
@LK4D4 I've pushed forced integration tests that I'm moving to integration-cli but seems like pidfile aren't cleaned properly

File: daemon/daemon.go [hunk 5]
```diff
@@ -964,22 +920,36 @@ func NewDaemonFromDirectory(config *Config, eng *engine.Engine, registryService
...
-	eng.OnShutdown(func() {
-		if err := daemon.shutdown(); err != nil {
-			logrus.Errorf("Error during daemon.shutdown(): %v", err)
+	graphdbPath := path.Join(config.Root, "linkgraph.db")
+	graph, err := graphdb.NewSqliteConn(graphdbPath)
+	if err != nil {
+		return nil, err
+	}
+	daemon.containerGraph = graph
+	//defer func() {
```
Comment (LK4D4) [inline daemon/daemon.go]: wut?

Comment (runcom) [inline daemon/daemon.go]: forgot to decomment

**Comment by LK4D4** [comment]
@runcom When you have time - you need to wrap `d.Shutdown` to timeout in `Trap`. Also your defer for pidfile not working because `Fatalf` is not return, it is `os.Exit(1)`

**Comment by LK4D4** [comment]
```
TESTFLAGS="-check.f DockerSuite.TestDaemonExitOnFailure" make test-integration-cli
```
for test

**Comment by LK4D4** [comment]
I think this PR opening new era in docker development :)
So, pls review when you have time @icecrime @jfrazelle @tiborvass @duglin @estesp @crosbymichael @cpuguy83

**Comment by icecrime** [comment]
:tada: Will try to review tomorrow :-) Thanks again @runcom!

**Comment by runcom** [comment]
@LK4D4 thanks!!! I'll fix what you said asap
@icecrime no prorblem :)

**Comment by tiborvass** [comment]
@runcom would you mind putting rm -rf engine and rm -rf integration in two different commits?

**Comment by icecrime** [comment]
Epic PR: +304 −4,527 :-) LGTM on first read, will keep testing.

File: docker/daemon.go [hunk 6]
```diff
@@ -83,14 +84,41 @@ func mainDaemon() {
...
-	signal.Trap(eng.Shutdown)
-
 	if err := migrateKey(); err != nil {
 		logrus.Fatal(err)
 	}
 	daemonCfg.TrustKeyPath = *flTrustKey
 
+	var pfile *pidfile.PidFile
+	if daemonCfg.Pidfile != "" {
+		pf, err := pidfile.New(daemonCfg.Pidfile)
```
Comment (LK4D4) [inline docker/daemon.go]: Probably should be called before `migrateKey`

File: docker/daemon.go [hunk 7]
```diff
@@ -119,40 +147,45 @@ func mainDaemon() {
...
 	api.AcceptConnections(d)
 
 	// Daemon is fully initialized and handling API traffic
-	// Wait for serve API job to complete
+	// Wait for serve API to complete
 	errAPI := <-serveAPIWait
-	eng.Shutdown()
+	shutdownDaemon(d)
 	if errAPI != nil {
 		logrus.Fatalf("Shutting down due to ServeAPI error: %v", errAPI)
```
Comment (LK4D4) [inline docker/daemon.go]: Shouldn't `pfile` be removed here too?

File: docker/daemon.go (hunk 6 above)
Comment (runcom) [inline docker/daemon.go]: :+1:

File: docker/daemon.go (hunk 7 above)
Comment (runcom) [inline docker/daemon.go]: yes but should be done  here in defer https://github.com/runcom/docker/commit/0bb37c3913cef07e6f4a5ccd54989eeca97093e7#diff-9d18a6929859b5f9739035de6065951dR99 

correct @LK4D4 ? because here everything went well or timeout but function returns and in case execute defer func

Comment (LK4D4) [inline docker/daemon.go]: `logrus.Fatalf`, there won't be defer here.

Comment (runcom) [inline docker/daemon.go]: yes then

File: daemon/daemon.go [hunk 8]
```diff
@@ -913,12 +881,13 @@ func NewDaemonFromDirectory(config *Config, eng *engine.Engine, registryService
 	if err != nil {
 		return nil, err
 	}
-	// register graph close on shutdown
-	eng.OnShutdown(func() {
-		if err := graph.Close(); err != nil {
-			logrus.Errorf("Error during container graph.Close(): %v", err)
+	defer func() {
+		if err != nil {
```
Comment (cpuguy83) [inline daemon/daemon.go]: Only closing graph if there was no error? Don't we want to close no matter what?

**Comment by LK4D4** [comment]
LGTM

File: docker/daemon.go [hunk 9]
```diff
@@ -119,40 +151,52 @@ func mainDaemon() {
...
+	ch := make(chan struct{})
+	go func() {
+		d.Shutdown()
+		close(ch)
+	}()
+	select {
+	case <-ch:
+		logrus.Debug("Clean shutdown succeded")
+	case <-time.After(seconds * time.Second):
+		logrus.Error("Force shutdown daemon")
```
Comment (cpuguy83) [inline docker/daemon.go]: So we're just logging that the daemon needs to be force stopped?

**Comment by cpuguy83** [comment]
Looks really good, just one question, but otherwise LGTM.

File: docker/daemon.go (hunk 9 above)
Comment (LK4D4) [inline docker/daemon.go]: It means that probably not all containers died in 15 seconds and we just brutally kill daemon.

Comment (cpuguy83) [inline docker/daemon.go]: But where are we killing it?

Comment (LK4D4) [inline docker/daemon.go]: in `signal.Trap`

Comment (cpuguy83) [inline docker/daemon.go]: I know `signal.Trap` has it's own bail stuff (3 sigs from the user)... but before engine was exiting after ~10s timeout period, now this timeout could probably be increased, but still seems like we should kill it after the timeout.

Comment (LK4D4) [inline docker/daemon.go]: @cpuguy83 Who should we kill? :) if `mainDaemon` function exits, then process just stops, nothing can stand this.

Comment (cpuguy83) [inline docker/daemon.go]: So as is the daemon will just hang until someone sends 2 more kill sigs to it.

**Comment by LK4D4** [comment]
@runcom Is it ready?

**Comment by LK4D4** [comment]
@runcom Oh, requires rebase, sorry :)

**Comment by runcom** [comment]
@LK4D4 almost, there were many tests inside integration/ that have to be ported to integration-cli/ :smile:

**Comment by estesp** [comment]
is this ready to go?

**Comment by LK4D4** [comment]
Fails looks like registry down.

**Comment by runcom** [comment]
@LK4D4 yup, need a rebuild

**Comment by tiborvass** [comment]
LGTM

**Comment by runcom** [comment]
:tada:

**Comment by tiborvass** [comment]
Huge thanks to @runcom and everyone involved in #12151 !!

RIP engine
