### PR TITLE
[20.10 backport] Fix setting swaplimit=true without checking

### LINKED ISSUE #41926: [cgroup2] docker info: `SwapLimit = true` is set without checking
**Description**

https://github.com/moby/moby/blob/v20.10.2/pkg/sysinfo/cgroup2_linux.go#L69-L84

`info.SwapLimit = true` should be set only if `memory.swap.max` exists.

When the swap support is present (with `swapaccount=1` in kernel cmdline), `memory.swap.max` appears in a non-top cgroup.
i.e., `/sys/fs/cgroup/${dockerd_cgroup}/memory.swap.max` appears, but `/sys/fs/cgroup/memory.swap.max` does not appear (unless we are in dind)

Related: https://github.com/containers/podman/pull/8197/files

** `docker version` **
20.10.2

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Cherry-pick https://github.com/moby/moby/pull/42071

- - -

**- What I did**
fixes #41926

**- How I did it**
Added one condition to moby/pkg/sysinfo/cgroup2_linux.go 

**- How to verify it**
Actually, I wanted to create unit tests for this one. The problem is certain files must be present on FS, so I see 2 solutions:
1) use mocks (of os.Stat for example)
2) since part of the path is passed as an argument, choose a different dir for tests (eg /tmp?)

I do not know what is the common practice in the project (1st PR), so I decided just to simply open a PR and ask.

**- Description for the changelog**

Fixes setting swaplimit=true without checking memory.swap.max

**- A picture of a cute animal (not mandatory but encouraged)**
Another time :)

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
@thaJeztah @kolyshkin PTAL

**Review by kolyshkin — APPROVED** [review]
LGTM

**Review by tonistiigi — APPROVED** [review]

**Review by thaJeztah — APPROVED** [review]
LGTM

File: pkg/sysinfo/cgroup2_linux.go [hunk 1]
```diff
@@ -74,7 +94,7 @@ func applyMemoryCgroupInfoV2(info *SysInfo, controllers map[string]struct{}, _ s
 	}
 
 	info.MemoryLimit = true
-	info.SwapLimit = true
```
Comment (cpuguy83) [inline pkg/sysinfo/cgroup2_linux.go:77]: I feel like the old method is a lot faster 🤣

**Review by cpuguy83 — APPROVED** [review]
LGTM
