### PR TITLE
Ensure vmcompute.dll exists during daemon start

### LINKED ISSUE #28327: [Windows Server 2016 Essentials] Error starting daemon: Error initializing network controller: Failed to load vmcompute.dll:
**Description**
I attempted to follow the steps listed on [Windows Containers on Windows Server](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_server) on a fresh Windows Server 2016 Essentials installation, and running the updates as hinted. Unfortunately the docker service has failed starting up with the following Event Viewer message.
`Error starting daemon: Error initializing network controller: Failed to load vmcompute.dll: The specified module could not be found.`

**Output of `docker version`:**
```
Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.25/version: open //./pipe/docker_engine: The system cannot find the file specified.
```
**Output of `docker info`:**
```
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.25/info: open //./pipe/docker_engine: The system cannot find the file specified.
```

### PR DESCRIPTION
**Pull request by darstahl**
**- What I did**

fixes #28327 

Ensure that vmcompute.dll exists on the system during daemon startup, and fail with a message to install the Containers role to fix the problem.

**- How I did it**

Load vmcompute.dll during checkSystem.

**- How to verify it**

On a system without `vmcompute.dll` installed.

Prior to fix:
```
C:\Users\Administrator>dockerd
time="2016-11-18T12:32:00.001314800-08:00" level=info msg="Windows default isolation mode: process"
time="2016-11-18T12:32:00.006612100-08:00" level=info msg="[graphdriver] using prior storage driver: windowsfilter"
time="2016-11-18T12:32:00.109140500-08:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2016-11-18T12:32:00.109140500-08:00" level=info msg="Loading containers: start."
Error starting daemon: Error initializing network controller: Failed to load vmcompute.dll: The specified module could not be found.
```

With fix:
```
C:\Users\Administrator>dockerd
Error starting daemon: Failed to load vmcompute.dll. Ensure that the Containers role is installed.
```

/cc @jhowardmsft @jstarks 

Signed-off-by: Darren Stahl <darst@microsoft.com>

### CODE REVIEW

**Comment by jhowardmsft** [comment]
LGTM

**Comment by jhowardmsft** [comment]
@thaJeztah @vieux Not critical, but eases a couple of debugging cases, so could be very useful to cherry-pick for 1.13.

**Comment by thaJeztah** [comment]
Almost expected a Microsoft "kb" link in the error message :smile:

**Comment by thaJeztah** [comment]
Is this of any concern here? https://golang.org/src/syscall/dll_windows.go

```
// If name is not an absolute path and is not a known system DLL used by
// Go, Windows will search for the named DLL in many locations, causing
// potential DLL preloading attacks.
// Use LazyDLL in golang.org/x/sys/windows for a secure way to
// load system DLLs.
```

**Comment by jhowardmsft** [comment]
Interesting. Hadn't thought about that. @darrenstahlmsft Although orthogonal to this PR, we probably should be consistent everywhere.

**Comment by darrenstahlmsft** [comment]
@thaJeztah Not in this case, as this DLL is only being used to check for presence for later loading by hcsshim, so it doesn't really matter what is loaded. That's up to hcsshim to deal with.

**Comment by thaJeztah** [comment]
> Not in this case, as this DLL is only being used to check for presence for later loading by hcsshim, so it doesn't really matter what is loaded

Agreed; my train of thoughts was that It _could_ result in a false "detection" (i.e. if a rogue `vmcompute.dll` is found), not a major issue. I initially thought it could lead to an incorrect dll being used later on, but it's unloaded (`Release()`) afterwards, so no problem there.

[daemon/logger/etwlogs/etwlogs_windows.go#L109](https://github.com/docker/docker/blob/b248de7e332b6e67b08a8981f68060e6ae629ccf/daemon/logger/etwlogs/etwlogs_windows.go#L109) should probably be fixed though.

File: daemon/daemon_windows.go [hunk 1]
```diff
@@ -230,6 +231,12 @@ func checkSystem() error {
 	if osv.Build < 14393 {
 		return fmt.Errorf("The docker daemon requires build 14393 or later of Windows Server 2016 or Windows 10")
 	}
+
+	vmcompute, err := syscall.LoadDLL("vmcompute.dll")
+	if err != nil {
+		return fmt.Errorf("Failed to load vmcompute.dll. Ensure that the Containers role is installed.")
+	}
+	defer vmcompute.Release()
```
Comment (thaJeztah) [inline daemon/daemon_windows.go]: nit: looks like we don't need a `defer` here?

Comment (darrenstahlmsft) [inline daemon/daemon_windows.go]: fixed

**Comment by jstarks** [comment]
@darrenstahlmsft I don't agree. Although I'm not convinced that the DLL preload attack is real (the DLL search path for the Docker engine should not include any paths that non-administrators control), just loading the DLL is enough to run code in it (`DllMain` gets called). We should use `syscall.LoadSystemDLL` here if we're going to do so elsewhere (e.g. hcsshim, go-winio).

**Comment by darrenstahlmsft** [comment]
As per @jstarks's comment, updated to use the `NewLazySystemDLL` method to load.

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Comment by jhowardmsft** [comment]
Still LGTM after update.
