### PR TITLE
Closes #26761 Updated the client/request.go sendClientRequest method to return a Pe…

### LINKED ISSUE #26761: bad error message when wrong permissions
**Description**

The error message when running with insufficient permissions is misleading. It says it cannot connect to the Docker daemon, but then if I run it with root, it connects fine. While this error message is true, a check for file permissions could give a much more helpful error message.
```
mdg@mgraham:~$ docker run hello-world
docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
```

**Steps to reproduce the issue:**
1. Restrict permissions on /var/run/docker.sock
2. Run `sudo docker info`, see expected results
3. Run `docker info`, see the message `Cannot connect to the Docker daemon. Is the docker daemon running on this host?`

**Describe the results you received:**

I got an error message suggesting that the docker daemon is not running on this host, even though it is.

**Describe the results you expected:**

I get a message telling me that I don't have the necessary permissions.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
mdg@mgraham:~$ sudo docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   b9f10c9
 Built:        Thu, 16 Jun 2016 21:17:51 +1200
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   b9f10c9
 Built:        Thu, 16 Jun 2016 21:17:51 +1200
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
mdg@mgraham:~$ sudo docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 1
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 5
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-28-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.227 GiB
Name: mgraham
ID: GZYC:P7HQ:ZA7T:SOCK:3J26:S3JY:N4I3:I7BB:VJ7E:MXMM:YZ7X:EZA3
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Lenovo laptop with Ubuntu 16.04, using default Ubuntu install.

### PR DESCRIPTION
**Pull request by srodman7689**
**\- What I did**
I added a new error message for when a user tries to connect with the docker client to the docker daemon via a unix socket and does not have permissions to the socket.
**\- How I did it**
by checking if the returned error message string contains connect: permission denied and return the error created by the client.PermissionDenied function. 
**\- How to verify it**
run the docker daemon as root, then create a non privileged user and run docker ps -a with that user. you should see the new error message.

**\- Description for the changelog**

Adds a more informative error message when a user does not have permissions to connect on the unix socket.

**\- A picture of a cute animal (not mandatory but encouraged)**

Updated the client/request.go sendClientRequest method to return a PermissionDenied error if the connection failed due to permissions.

Signed-off-by: Sean Rodman srodman7689@gmail.com

### CODE REVIEW

**Comment by srodman7689** [comment]
This is a pull request for https://github.com/docker/docker/issues/26761

**Comment by srodman7689** [comment]
Hey guys. Is there anything I can do to get this merged in. Are there any changes that need to be made or anything?

File: client/errors.go [hunk 1]
```diff
@@ -8,6 +8,11 @@ import (
 // ErrConnectionFailed is an error raised when the connection between the client and the server failed.
 var ErrConnectionFailed = errors.New("Cannot connect to the Docker daemon. Is the docker daemon running on this host?")
 
+// PermissionDenied returns an error with socketFile in the error message when a unix socket can not be opened.
+func PermissionDenied(socketFile string) error {
+	return fmt.Errorf("Cannot open %s. Permission Denied.", socketFile)
```
Comment (thaJeztah) [inline client/errors.go]: I was wondering if we should be really explicit and mention that they should try "sudo", but perhaps that's taking it too far.

@vdemeester @cpuguy83 wdyt?

Comment (srodman7689) [inline client/errors.go]: Maybe something like "Cannot open %s. Permission Denied. If you are running the docker command as a non root user try using sudo before your command." ?

Comment (thaJeztah) [inline client/errors.go]: "Cannot connect to _socket_" perhaps. Open to more suggestions; it's always tough to find the right balance between "holding hands" and "useful messages" :smile:

Comment (cpuguy83) [inline client/errors.go]: Can we just define an error like we have for connection failed and use `errors.Wrap` (from github.com/pkg/errors) to provide the extra context?

Comment (srodman7689) [inline client/errors.go]: I don't mind doing that at all, The reason I went with the PermissionDenied function like that is because it is following how the ErrorConnectionFailed function is setup. I don't mind making any changes you guys think are needed though.

Comment (thaJeztah) [inline client/errors.go]: @cpuguy83 probably the solution for https://github.com/docker/docker/issues/26773 as well?

File: client/request.go [hunk 2]
```diff
@@ -134,6 +134,9 @@ func (cli *Client) sendClientRequest(ctx context.Context, method, path string, q
 				return serverResp, ErrorConnectionFailed(cli.host)
 			}
 			if !err.Temporary() {
+				if strings.Contains(err.Error(), "connect: permission denied") {
```
Comment (cpuguy83) [inline client/request.go]: We can also test the error like so:

```go
if nErr, ok := err.(*net.OpError); ok {
  if os.IsPermission(nErr.Err) {
    
  }
}
```

Comment (srodman7689) [inline client/request.go]: I like that a lot better. Working on adding that now.

Comment (srodman7689) [inline client/request.go]: @cpuguy83 I added this change and the code looks a lot better. I also changed the PermissionDenied method to just a var with a errors.new call. To match what @thaJeztah was talking about. What do you guys think?

File: client/errors.go [hunk 3]
```diff
@@ -8,6 +8,9 @@ import (
 // ErrConnectionFailed is an error raised when the connection between the client and the server failed.
 var ErrConnectionFailed = errors.New("Cannot connect to the Docker daemon. Is the docker daemon running on this host?")
 
+// PermissionDenied is an error raised when a unix socket can not be opened.
```
Comment (cpuguy83) [inline client/errors.go]: `ErrPermissionDenied is an...`

File: client/request.go [hunk 4]
```diff
@@ -129,6 +130,12 @@ func (cli *Client) sendClientRequest(ctx context.Context, method, path string, q
 			return serverResp, err
 		}
 
+		if err, ok := err.(*net.OpError); ok {
+			if os.IsPermission(err.Err) {
+				return ServerResp, ErrPermissionDenied
```
Comment (cpuguy83) [inline client/request.go]: I think this needs a lower `s` on `serverResp`

Comment (cpuguy83) [inline client/request.go]: Would be nice to wrap the error via `errors.Wrap` with some context like the socket path.

**Comment by srodman7689** [comment]
Sorry for the failures guys. I am working on the code locally until I can integrate your suggestions and get the code working. Will push up again in just a few minutes.

File: client/errors.go [hunk 5]
```diff
@@ -8,6 +8,9 @@ import (
...
+var ErrPermissionDenied = errors.New("Cannot open socket. Permission Denied.")
```
Comment (cpuguy83) [inline client/errors.go]: Maybe a more friendly message: `got permission denied while trying to connect`

**Review by cpuguy83 — CHANGES_REQUESTED** [review]

File: client/errors.go (hunk 5 above)
Comment (srodman7689) [inline client/errors.go]: Cool. Will add that as well.

File: client/request.go (hunk 4 above)
Comment (srodman7689) [inline client/request.go]: I will look into this too.

**Comment by srodman7689** [comment]
@cpuguy83 I had to unwrap the url.Error and then the net.OpError to get to the error that would let me know if it was a permissions error or not but it seems to be working now. Please let me know if you would like for me to change anything else. Also, I used errors.Wrap to add the socket file path to the error message.

File: client/request.go (hunk 4 above)
Comment (srodman7689) [inline client/request.go]: This is done as well now.

File: client/errors.go (hunk 3 above)
Comment (srodman7689) [inline client/errors.go]: Fixed this too now.

File: client/request.go (hunk 4 above)
Comment (srodman7689) [inline client/request.go]: Added.

File: client/errors.go (hunk 5 above)
Comment (srodman7689) [inline client/errors.go]: Done.

**Comment by srodman7689** [comment]
@cpuguy83 and @thaJeztah hey guys. Do you have anything else you want me to change on this pull request?

**Comment by srodman7689** [comment]
I have been squashing my commits on this. Should I continue to squash them or should I have them all visible?

File: client/errors.go [hunk 6]
```diff
@@ -8,6 +8,9 @@ import (
 // ErrConnectionFailed is an error raised when the connection between the client and the server failed.
 var ErrConnectionFailed = errors.New("Cannot connect to the Docker daemon. Is the docker daemon running on this host?")
 
+// ErrPermissionDenied is an error raised when a unix socket can not be opened.
+var ErrPermissionDenied = errors.New("Got permission denied while trying to connect to the Docker daemon.")
```
Comment (thaJeztah) [inline client/errors.go]: Sorry for the delay; I like this better, _but_ think the message should contain something about "socket".

**Review by thaJeztah — CHANGES_REQUESTED** [review]
Left another node (sorry for all the bike shedding here)

Also looks like your latest rebase pulled a non-related commit in

File: client/errors.go (hunk 6 above)
Comment (srodman7689) [inline client/errors.go]: How about Got permission denied while trying to connect to the Docker daemon's socket.

Comment (srodman7689) [inline client/errors.go]: or Got permission denied while trying to connect to the Docker daemon's socket file.

Comment (srodman7689) [inline client/errors.go]: Also, I removed the unrelated commit.

Comment (justincormack) [inline client/errors.go]: yes should definitely say `socket` else user might get confused.

`"Got permission denied while trying to connect to the Docker daemon socket."` seems fine.

Comment (thaJeztah) [inline client/errors.go]: how about;
```
Got permission denied while trying to connect to the Docker daemon socket
```

Comment (thaJeztah) [inline client/errors.go]: LOL sorry for the double post; Justin and I were just discussing this, and GitHub didn't show his comment yet

Comment (srodman7689) [inline client/errors.go]: This should be fixed now.

File: client/request.go [hunk 7]
```diff
@@ -129,6 +130,14 @@ func (cli *Client) sendClientRequest(ctx context.Context, method, path string, q
 			return serverResp, err
 		}
 
+		if nErr, ok := err.(*url.Error); ok {
+			if nErr, ok := nErr.Err.(*net.OpError); ok {
+				if os.IsPermission(nErr.Err) {
+					return serverResp, errors.Wrap(ErrPermissionDenied, cli.host)
```
Comment (stevvooe) [inline client/request.go]: Never hide the causing error.

Comment (stevvooe) [inline client/request.go]: Should be:

```
errors.Wrap(err, "permission denied making request to %v", cli.host)
```

**Review by stevvooe — CHANGES_REQUESTED** [review]

File: client/request.go (hunk 7 above)
Comment (thaJeztah) [inline client/request.go]: `errors.Wrapf` probably?

Comment (srodman7689) [inline client/request.go]: used this
`errors.Wrapf(err, "Got permission denied while trying to connect to the Docker daemon socket at %v", cli.host)`
and go this output when reproducing the error. Is this more what we want?
`Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.25/containers/json?all=1: dial unix /var/run/docker.sock: connect: permission denied`

Comment (thaJeztah) [inline client/request.go]: Looks good! Think that provides all the information needed

**Comment by srodman7689** [comment]
Finally push up the requested changes. sorry it took so long guys.

**Comment by srodman7689** [comment]
Merged master and it went crazy. Let me know if I need to recreate this pull request.

**Comment by thaJeztah** [comment]
Looks like you need to do a rebase; make sure your "upstream" and "origin" branches are up to date, then you can rebase on top of master (which _should_ make those extra commits go away) see
https://docs.docker.com/opensource/workflow/work-issue/#/pull-and-rebase-frequently

**Comment by srodman7689** [comment]
Looks like it is fixed now. Thank you for the help.

**Comment by srodman7689** [comment]
@thaJeztah this is good now if you have a chance to look at it one more time lol.

**Comment by stevvooe** [comment]
Lgtm

**Review by thaJeztah — APPROVED** [review]
Perfect, thanks so much @srodman7689!

LGTM
