### PR TITLE
Do not drop effective&permitted set

### LINKED ISSUE #45491: Process capabilities cannot be retained when starting a container as non-root with `--security-opt=no-new-privileges`
### Description

When using docker as a runtime in kubernetes, the capabilities specified in the container's security context (in the pod yaml manifests) are not respected if running as **non-root** user:
```yaml
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - NET_BIND_SERVICE
        drop:
        - ALL
      privileged: false
      runAsGroup: 107
      runAsNonRoot: true
      runAsUser: 107
```
```bash
$ k exec -ti virt-launcher-testvm-XXXX -- bash
bash-5.1$ grep Cap /proc/1/status 
CapInh:	0000000000000000
CapPrm:	0000000000000000 # permitted caps zeroed
CapEff:	0000000000000000 # effective caps zeroed
CapBnd:	0000000000000400 # cap_net_bind_service
CapAmb:	0000000000000000
````

In KubeVirt project we had several similar issues reported: https://github.com/kubevirt/kubevirt/issues/9465

This can be easily reproduced with minikube. Other runtimes (containerd and crio) handle the capabilities correctly:
```
CapInh:	0000000000000000
CapPrm:	0000000000000400 # cap_net_bind_service
CapEff:	0000000000000400 # cap_net_bind_service
CapBnd:	0000000000000400 # cap_net_bind_service
CapAmb:	0000000000000000
```

I briefly looked at the sources. Though I am not 100% confident that this snippet is actually causing the problem, but the bellow code looked suspicious to me:
https://github.com/moby/moby/blob/c651a535588402f27d8f1a1408c794fc3289f39f/oci/oci.go#L31-L35

It was introduced by this commit https://github.com/moby/moby/commit/349aeeab7c5e878ddc6c0c95a0a937476816c43e (and refactored in https://github.com/moby/moby/commit/0d9a37d0c249e871af0e667317be3169054a989f). 

### Reproduce

```bash
$ minikube start --driver=kvm2
$ k create -f https://github.com/kubevirt/kubevirt/releases/download/v0.59.0/kubevirt-operator.yaml
$ k create -f https://github.com/kubevirt/kubevirt/releases/download/v0.59.0/kubevirt-cr.yaml
$ wget https://kubevirt.io/labs/manifests/vm.yaml
$ vim vm.yaml # add annotation `kubevirt.io/keep-launcher-alive-after-failure: "true"`
$ k create -f vm.yaml
$ k edit vm testvm # set `running: true`
$ k logs -f virt-launcher-testvm-XXXX
...
{"component":"virt-launcher","level":"error","msg":"failed to start virtqemud","pos":"libvirt_helper.go:250","reason":"fork/exec /usr/sbin/virtqemud: errno 0","timestamp":"2023-05-08T09:34:32.370373Z"}
panic: fork/exec /usr/sbin/virtqemud: errno 0
...
$ k exec -ti virt-launcher-testvm-XXXX -- bash
bash-5.1$ grep Cap /proc/1/status 
CapInh:	0000000000000000
CapPrm:	0000000000000000 # permitted caps zeroed
CapEff:	0000000000000000 # effective caps zeroed
CapBnd:	0000000000000400 # cap_net_bind_service
CapAmb:	0000000000000000
```

### Expected behavior

Effective/permitted caps should be set correctly:
```
CapPrm:	0000000000000400
CapEff:	0000000000000400
```

### docker version

```bash
Client:
 Version:           20.10.23
 API version:       1.41
 Go version:        go1.18.10
 Git commit:        7155243
 Built:             Thu Jan 19 17:30:35 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.23
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.10
  Git commit:       6051f14
  Built:            Thu Jan 19 17:36:08 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.0
  GitCommit:        1fbd70374134b891f97ce19c70b6e50c7b9f4e0d
 runc:
  Version:          1.1.5
  GitCommit:        f19387a6bec4944c770f7668ab51c4348d9c2f38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 34
  Running: 28
  Paused: 0
  Stopped: 6
 Images: 14
 Server Version: 20.10.23
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1fbd70374134b891f97ce19c70b6e50c7b9f4e0d
 runc version: f19387a6bec4944c770f7668ab51c4348d9c2f38
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.57
 Operating System: Buildroot 2021.02.12
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.22GiB
 Name: minikube
 ID: 462Q:TJOC:6UQE:VT5O:7XAO:AS3J:5M6Q:VOT3:HXV2:HTVP:4TFY:4W7K
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
  provider=kvm2
 Experimental: false
 Insecure Registries:
  10.96.0.0/12
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

### Additional Info

This can also be reproduced without KubeVirt:
```
$ k apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: sleeper
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 30
  containers:
  - name: sleeper
    image: busybox
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - NET_BIND_SERVICE
        drop:
        - ALL
      privileged: false
      runAsGroup: 107
      runAsNonRoot: true
      runAsUser: 107
    command:
    - /bin/sh
    - "-euxc"
    - |
      sleep infinity
EOF
$ k exec -ti sleeper -- sh
~ $ ps aux
PID   USER     TIME  COMMAND
    1 107       0:00 /bin/sh -euxc sleep infinity 
   13 107       0:00 sh
   19 107       0:00 ps aux
~ $ grep Cap /proc/1/status
CapInh:	0000000000000000
CapPrm:	0000000000000000
CapEff:	0000000000000000
CapBnd:	0000000000000400
CapAmb:	0000000000000000
```

### PR DESCRIPTION
**Pull request by xpivarc**
- Fixes #45491

**- What I did**

Currently moby drops ep sets before the entrypoint is executed. This does mean that with combination of no-new-privileges the file capabilities stops working with non-root containers. This is undesired as the usability of such containers is harmed comparing to running root containers.

This commit therefore sets the effective/permitted set in order to allow use of file capabilities or libcap(3)/prctl(2) respectively with combination of no-new-privileges and without respectively.

For no-new-privileges the container will be able to obtain capabilities that are requested.

**- How I did it**

**- How to verify it**

Use the below as Dockerfile
```
FROM alpine
RUN apk add --update libcap

RUN ls -la /usr/sbin/capsh
RUN setcap 'cap_sys_admin=ep' /usr/sbin/capsh
```

`docker run --security-opt=no-new-privileges --user=100 --cap-add sys_admin <tag of the build Dockerfile> capsh --print`

You should see `Current: = cap_sys_admin+ep` rather than `Current:`

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by xpivarc** [comment]
ref https://github.com/moby/moby/issues/45491

**Comment by corhere** [comment]
There's little point in making this change against master as it will have no effect. An unintended consequence of #44804 is that `s.Process.User.UID == 0` is always true when `SetCapabilities` is called. (cc @rumpl: `in (*daemon).createSpec`, the relative ordering of `WithUser` and `WithCapabilities` is significant.)

**Review by corhere — APPROVED** [review]
[I am now convinced that zeroing out the Effective and Permitted sets was never the right thing to do.](https://github.com/moby/moby/issues/45491#issuecomment-1542710502) This change is not strictly necessary to fix the bug on v24 or master because of the aforementioned oversight, but is still good to have in so we don't accidentally regress.

Note for reviewers: despite setting the Effective and Permitted sets in the container spec, in practice the container's PID 1 will have the respective capability sets zeroed out in most cases when `UID > 0` _because that's what `execve` does._ The only exception is when the entrypoint has file capabilities set, which is the case that is being fixed.

File: oci/oci.go [hunk 1]
```diff
@@ -20,19 +20,10 @@ var deviceCgroupRuleRegex = regexp.MustCompile("^([acb]) ([0-9]+|\\*):([0-9]+|\\
...
-	} else {
-		// Do not set Effective and Permitted capabilities for non-root users,
-		// to match what execve does.
-		s.Process.Capabilities = &specs.LinuxCapabilities{
-			Bounding: caplist,
-		}
+	s.Process.Capabilities = &specs.LinuxCapabilities{
+		Effective: caplist,
+		Bounding:  caplist,
+		Permitted: caplist,
```
Comment (AkihiroSuda) [inline oci/oci.go:26]: Can we have ab integration test?

**Comment by thaJeztah** [comment]
@xpivarc could you have a look at adding an integration test for this? (let us know if you need help doing so 🤗 )

**Comment by xpivarc** [comment]
@thaJeztah I should have some time this week. Sorry for the delay.

**Comment by thaJeztah** [comment]
@justincormack PTAL

**Review by thaJeztah — CHANGES_REQUESTED** [review]
Still some discussion happening on the change. Let me put a "request changes" until those are all settled

File: integration/capabilities/capabilities_test.go [hunk 2]
```diff
@@ -0,0 +1,121 @@
...
+		stdOut     string
+		stdErr     string
+	}{
+		{
+			doc:        "Non-root user with file capability and with capability requested",
+			dockerFile: withFileCapability,
+			opts: []func(*container.TestContainerConfig){
+				container.WithUser("test"),
+				container.WithCapability("CAP_DAC_OVERRIDE"),
+				// TODO where is the nonewprivilages specified
```
Comment (corhere) [inline integration/capabilities/capabilities_test.go:47]: It is specified by appending the string `"no-new-privileges=true"` to `(*container.TestContainerConfig).HostConfig.SecurityOpt`. Looks like you'll have to implement a new option for it.

```go
func WithSecurityOpt(opt string) func(*TestContainerConfig) {
	return func(c *TestContainerConfig) {
		c.HostConfig.SecurityOpts = append(c.HostConfig.SecurityOpts, opt)
	}
}
```
```suggestion
				container.WithSecurityOpt("no-new-privileges=true")
```

File: integration/internal/container/ops.go [hunk 3]
```diff
@@ -255,3 +255,15 @@ func WithCDIDevices(cdiDeviceNames ...string) func(*TestContainerConfig) {
...
+	return func(c *TestContainerConfig) {
+		c.HostConfig.CapAdd = strslice.StrSlice([]string{capability})
+	}
+}
+
+func WithDropCapability(capability string) func(*TestContainerConfig) {
+	return func(c *TestContainerConfig) {
+		c.HostConfig.CapDrop = strslice.StrSlice([]string{capability})
+	}
+}
```
Comment (corhere) [inline integration/internal/container/ops.go:269]: These options should take a variable number of arguments and append to the config instead of overriding it, like `WithCDIDevices` above.

```suggestion
func WithCapabilities(caps ...string) func(*TestContainerConfig) {
	return func(c *TestContainerConfig) {
		c.HostConfig.CapAdd = append(c.HostConfig.CapAdd, strslice.StrSlice(caps))
	}
}

func WithDropCapabilities(caps ...string) func(*TestContainerConfig) {
	return func(c *TestContainerConfig) {
		c.HostConfig.CapDrop = append(c.HostConfig.CapDrop, strslice.StrSlice(caps))
	}
}
```

**Comment by xpivarc** [comment]
Thanks @corhere

**Review by thaJeztah — APPROVED** [review]
LGTM after the tests are fixed

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by neersighted — APPROVED** [review]
