### PR TITLE
Fix `before` and `since` filter for `docker ps`

### LINKED ISSUE #35931: Filter "before" stopped working
**Description**
When I try to use filter before to find earlier containers I got:
```Error response from daemon: no such container <container_name>```

**Steps to reproduce the issue:**
1. docker run -d --name=ubuntu -it ubuntu bash
2. docker ps -a -f name=ubuntu
3. docker ps -a -f before=ubuntu

**Describe the results you received:**
when filter is ```name=ubuntu``` then i get container in list
and when filter is: ```before=ubuntu``` i get the error

**Describe the results you expected:**
nothing or container created before this one

**Output of `docker version`:**

```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:11:19 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:53 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**

```
Containers: 14
 Running: 11
 Paused: 0
 Stopped: 3
Images: 8
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.58-xxxx-std-ipv6-64
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 62.87GiB
Name: temp1
ID: DJML:ZOE7:4LM3:A46E:CECU:ZN6J:7PRD:QCS6:E3PW:5V2B:XXPK:PGKC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical machine

**PS** 
On old docker-ce 17.03.1-ce it works perfectly

### PR DESCRIPTION
**Pull request by yongtang**
**- What I did**

This fix tries to address the issue raised in #35931 where `before` and `since` filter for `docker ps` does not work and returns an error:

```
Error response from daemon: no such container <container_name>
```

**- How I did it**

The issue was that `before` and `since` filter are matched with `view.Get()` which does not take into considerations of name match.

This fix fixes the issue by adding additional logic for name match.

**- How to verify it**

An integration test has been added.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**
cute-baby-penguin-10

This fix fixes #35931.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

File: daemon/list.go [hunk 1]
```diff
@@ -303,6 +303,24 @@ func (daemon *Daemon) foldFilter(view container.View, config *types.ContainerLis
 
 	err = psFilters.WalkValues("before", func(value string) error {
 		beforeContFilter, err = view.Get(value)
+		switch err.(type) {
```
Comment (dnephin) [inline daemon/list.go]: It looks like both of these `func(value string) error` are identical, so it should probably be a function called in both places to return the filter.

**Review by dnephin — COMMENTED** [review]
It seems strange to me that before/after accept container names/ids instead of timestamps, but I guess that's what is documented.

File: daemon/list.go (hunk 1 above)
Comment (yongtang) [reply daemon/list.go]: Thanks @dnephin, the PR has been updated.

File: integration/container/ps_test.go [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+	require.NoError(t, err)
+
+	filters := filters.NewArgs()
+	filters.Add("since", "top")
+	filters.Add("before", "top")
+	_, err = client.ContainerList(ctx, types.ContainerListOptions{
+		All:     true,
+		Filters: filters,
+	})
+	require.NoError(t, err)
```
Comment (dnephin) [inline integration/container/ps_test.go]: If we're going to spend the time on an integration test, I think it should at least test the "success" case where it finds something.

I would say that ideally we could test  this with a unit test, but I understand that is difficult with `Daemon`.

Comment (yongtang) [reply integration/container/ps_test.go]: Thanks @dnephin. The PR has been updated. Please take a look.

File: integration/container/ps_test.go [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+	prev, err := client.ContainerCreate(ctx,
+		&container.Config{
+			Cmd:   []string{"top"},
+			Image: "busybox",
+		},
+		&container.HostConfig{},
+		&network.NetworkingConfig{},
+		"prev",
+	)
+	require.NoError(t, err)
```
Comment (dnephin) [inline integration/container/ps_test.go]: Maybe move this into a helper so that the test can read:

```go
prev := createContainerForFilter(t, "prev")
top  := createContainerForFilter(t, "top")
next  := createContainerForFilter(t, "next")
```

File: integration/container/ps_test.go [hunk 4]
```diff
@@ -0,0 +1,79 @@
...
+	}
+
+	f1 := filters.NewArgs()
+	f1.Add("since", "top")
+	q1, err := client.ContainerList(ctx, types.ContainerListOptions{
+		All:     true,
+		Filters: f1,
+	})
+	require.NoError(t, err)
+	assert.Contains(t, containerID(q1), next.ID)
```
Comment (dnephin) [inline integration/container/ps_test.go]: Can this be `Equal()` instead of `Contains()`?

File: integration/container/ps_test.go [hunk 5]
```diff
@@ -0,0 +1,79 @@
...
+			Cmd:   []string{"top"},
+			Image: "busybox",
+		},
+		&container.HostConfig{},
+		&network.NetworkingConfig{},
+		"next",
+	)
+	require.NoError(t, err)
+
+	containerID := func(containers []types.Container) []string {
```
Comment (dnephin) [inline integration/container/ps_test.go]: `containerIDs` since this is a slice?

**Review by dnephin — APPROVED** [review]
LGTM

Thanks, just a few nits about the test

File: integration/container/ps_test.go (hunk 3 above)
Comment (yongtang) [reply integration/container/ps_test.go]: @dnephin Updated. Thanks.

File: integration/container/ps_test.go (hunk 5 above)
Comment (yongtang) [reply integration/container/ps_test.go]: Thanks @dnephin. Done.

File: integration/container/ps_test.go (hunk 4 above)
Comment (yongtang) [reply integration/container/ps_test.go]: @dnephin When I run locally with:
```
TESTFLAGS="-test.run TestPsFilter" make test-integration
```
It could be `Equal()` without issues.

However, on Jenkins I noticed there are some other containers running so just used `Contains()`. As full ID is used I think it is fine.

**Review by vdemeester — APPROVED** [review]
LGTM 🍸
