### PR TITLE
Fix for the issue #17225 flaky test DockerSuite.TestExecEnv test case.

### LINKED ISSUE #17225: Flaky test: DockerSuite.TestExecEnv
Found in #16890 (userns build)
```
----------------------------------------------------------------------
FAIL: docker_cli_exec_test.go:126: DockerSuite.TestExecEnv

docker_cli_exec_test.go:135:
    c.Errorf("exec env(%q), expect %q, %q", out, "LALA=value2", "HOME=/root")
... Error: exec env(""), expect "LALA=value2", "HOME=/root"


----------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by askb**
This is done by calling waitRun() followed by the docker run, which ensures the container is loaded
before calling docker exec to obtain the env variable set previously. Fixes #17225

Signed-off-by: Anil Belur askb23@gmail.com

### CODE REVIEW

File: integration-cli/docker_cli_exec_test.go [hunk 1]
```diff
@@ -125,10 +125,12 @@ func (s *DockerDaemonSuite) TestExecAfterDaemonRestart(c *check.C) {
 // Regression test for #9155, #9044
 func (s *DockerSuite) TestExecEnv(c *check.C) {
 	testRequires(c, DaemonIsLinux)
-	dockerCmd(c, "run", "-e", "LALA=value1", "-e", "LALA=value2",
+	out, _ := dockerCmd(c, "run", "-e", "LALA=value1", "-e", "LALA=value2",
 		"-d", "--name", "testing", "busybox", "top")
+	id := strings.TrimSpace(out)
+	c.Assert(waitRun(id), check.IsNil)
```
Comment (duglin) [inline integration-cli/docker_cli_exec_test.go]: if you use "testing" instead of an ID in the Assert then you don't need "out" or "id" and the dockerCmd above and below can remain unchanged.  IOW, just add `c.Assert(waitRun("testing"), check.IsNil)` to the original code, I think.

**Comment by duglin** [comment]
LGTM

**Comment by duglin** [comment]
and thanks btw

**Comment by vdemeester** [comment]
LGTM 🐻
Thanks @askb
