### PR TITLE
better vendor.sh to break when fail in grep

### LINKED ISSUE #25520: fail to report error in vendor.sh and workdir is stubborn
Hi, All,

Yesterday, I tried to update go-units to the newest version.

When I use vendor.sh to achieve this, I failed at the first time.

Here are my steps:
1. `cd hack`
2. change commit id of go-units in vendor.sh
3. `./vendor github.com/docker/go-units`

I got results like below:
```
hack $  ./vendor.sh github.com/docker/go-units
grep: ./vendor.sh: No such file or directory

collecting import graph, ^C
```

I think there are two kinds of problem here:
1. cannot execute command in directory `docker/hack`, only works in directory `docker`;
2. when ran into an error, the script still keeps running rather than exits immediately.

### PR DESCRIPTION
**Pull request by allencloud**
**\- What I did**
fixed #25520

this pr did:
1. exit when grep fails
2. make this script work in most workdir

Signed-off-by: allencloud allen.sun@daocloud.io

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @tianon please take a look, thanks!

**Comment by allencloud** [comment]
PTAL @tianon 
If it is not on the right direction, feel free to close this one. :)

File: hack/vendor.sh [hunk 1]
```diff
@@ -19,7 +19,15 @@ case $# in
 	;;
 # If user passed arguments to the script
 1)
-	eval "$(grep -E "^clone [^ ]+ $1" "$0")"
+	set +e
```
Comment (tianon) [inline hack/vendor.sh]: Rather than using `set +e` (which disables completely the "failure protections" it provides), we should look into using either `set -o pipefail` (which I'm not sure will actually work here), or using a variable, which will force the `grep` to be evaluated outside the "complex expression", and thus let `set -e` fail it (or let us `if` it and provide a good message).

For example:
```bash
if ! cloneGrep="$(grep -E "^clone [^ ]+ $1" "$0")"; then
    echo >&2 "error: failed to find 'clone ... $1' in $0"
    exit 1
fi
eval "$cloneGrep"
```

Comment (allencloud) [inline hack/vendor.sh]: Thanks for your review. @tianon 
Actually I like the latter one which uses a variable.
Updated the PR. PTAL

File: hack/vendor.sh [hunk 2]
```diff
@@ -19,7 +19,12 @@ case $# in
 	;;
 # If user passed arguments to the script
 1)
-	eval "$(grep -E "^clone [^ ]+ $1" "$0")"
+	path=$(pwd)"/hack/vendor.sh"
+	if ! cloneGrep="$(grep -E "^clone [^ ]+ $1" $path)"; then
+    	echo >&2 "error: failed to find 'clone ... $1' in $0"
+    	exit 1
```
Comment (tianon) [inline hack/vendor.sh]: Looks like you've got a mix of tabs and spaces here. :smile: (should be all tabs)

Also, `$path` is the same as `$BASH_SOURCE`, so I think we should just use that (and quote it, in case users have spaces in their path).

ie:
```diff
+	if ! cloneGrep="$(grep -E "^clone [^ ]+ $1" "$BASH_SOURCE")"; then
+		echo >&2 "error: failed to find 'clone ... $1' in $BASH_SOURCE"
+		exit 1
+	fi
+	eval "$cloneGrep"
```

Comment (allencloud) [inline hack/vendor.sh]: Thanks for your review. @tianon  😄
fixed the space issue.
In addition, I think there is some difference between $path and $BASH_SOURCE. With the $path, we can either execute `./hack/vendor.sh github.com/docker/go-units` or `./vendor.sh github.com/docker/go-units`. While with $BASH_SOURCE, we can only execute `./hack/vendor.sh github.com/docker/go-units`.

Then $path expand the work directory for vendor.sh. Actually at first time, I ran ./vendor.sh, while it does not work for me as the pwd problem.

Comment (tianon) [inline hack/vendor.sh]: "$BASH_SOURCE" will always refer to the current file in Bash, regardless of
how the script was invoked (even if it was "source"d from another file).  I
think the issue you describe is the difference between "$0" and
"$BASH_SOURCE" -- "$0" is the command/file which the user invoked, which
may not be the same as the path to the script.

Comment (allencloud) [inline hack/vendor.sh]: "$BASH_SOURCE" will always refer to the current file in Bash. Totally agree.

Here is my reason why not choose $BASH_SOURCE, correct me if there is something wrong.😄
In the head of vendor.sh, there is `cd "$(dirname "$BASH_SOURCE")/.."`, and after this command the current dir will be `.../github/docker/docker`, right?

Then the grep Command `grep -E "^clone [^ ]+ $1" "$BASH_SOURCE"` will try to work under `.../github/docker/docker`. While `$BASH_SOURCE` will be `./vendor.sh`, not in `.../github/docker/docker`, but in `.../github/docker/docker/hack`. As a result, the grep command will always fail with the error `grep: ./vendor.sh: No such file or directory`.

Comment (tianon) [inline hack/vendor.sh]: "$BASH_SOURCE" should be absolute (unlike "$0", which can be relative)
:smile:

Comment (allencloud) [inline hack/vendor.sh]: Oh, I think this is the key
> "$BASH_SOURCE" should be absolute

I did all the test on OS X, is this be the root cause? And on Linux $BASH_SOURCE is absolute?

Comment (tianon) [inline hack/vendor.sh]: Oh, you are correct :disappointed:

Ok, can we use "$PWD/hack/vendor.sh" then (instead of shelling out to
"pwd")?

Comment (allencloud) [inline hack/vendor.sh]: I updated the pr. PTAL.
Sorry for my not offering the operating system info. I think it bothers you a lot.
Thanks for your patience.

**Comment by tianon** [comment]
LGTM :+1: (thanks for your work on this!)

**Comment by vdemeester** [comment]
LGTM 🐸

**Comment by allencloud** [comment]
Any update? @tianon @vdemeester
