### PR TITLE
API: Add test for status code on conflicting service names

### LINKED ISSUE #38140: Service create API returns 5xx status instead of 4xx
(as reported by @waseemshahwan in https://github.com/moby/moby/issues/31909#issuecomment-435742609)

Looks like a regression was introduced somewhere between Docker 17.07 and 17.09.1, causing the status code for a "conflict" to change from a 409 to a 500;

To reproduce; run a "service create" request _twice_ (second time should return a "conflict";

```bash
curl -v \
  --unix-socket /var/run/docker.sock \
  -X POST \
  "http://localhost/v1.30/services/create" \
  -H "Content-Type: application/json" \
  -d '{"EndpointSpec":{"Mode":"vip"},"Labels":{},"Mode":{"Replicated":{}},"Name":"testing","TaskTemplate":{"ContainerSpec":{"DNSConfig":{},"Image":"nginx:alpine@sha256:ae5da813f8ad7fa785d7668f0b018ecc8c3a87331527a61d83b3b5e816a0f03c","Init":false},"ForceUpdate":0,"Placement":{"Platforms":[{"Architecture":"amd64","OS":"linux"},{"OS":"linux"},{"Architecture":"arm64","OS":"linux"},{"Architecture":"386","OS":"linux"},{"Architecture":"ppc64le","OS":"linux"},{"Architecture":"s390x","OS":"linux"}]},"Resources":{"Limits":{},"Reservations":{}}}}'
```

On Docker 17.07.0-ce

```
> POST /v1.30/services/create HTTP/1.1
> Host: localhost
> User-Agent: curl/7.61.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 536
> 
* upload completely sent off: 536 out of 536 bytes
< HTTP/1.1 409 Conflict
< Api-Version: 1.31
< Content-Type: application/json
< Docker-Experimental: false
< Ostype: linux
< Server: Docker/17.07.0-ce (linux)
< Date: Mon, 05 Nov 2018 16:10:58 GMT
< Content-Length: 86
< 
{"message":"rpc error: code = Unknown desc = name conflicts with an existing object"}
```

On Docker 17.09.1-ce

```
> POST /v1.30/services/create HTTP/1.1
> Host: localhost
> User-Agent: curl/7.61.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 536
> 
* upload completely sent off: 536 out of 536 bytes
< HTTP/1.1 500 Internal Server Error
< Api-Version: 1.32
< Content-Type: application/json
< Docker-Experimental: false
< Ostype: linux
< Server: Docker/17.09.1-ce (linux)
< Date: Mon, 05 Nov 2018 16:11:59 GMT
< Content-Length: 86
< 
{"message":"rpc error: code = Unknown desc = name conflicts with an existing object"}
```

On 18.06.1-ce (still reproduces)

```
*   Trying /var/run/docker.sock...
* Connected to localhost (/var/run/docker.sock) port 80 (#0)
> POST /v1.30/services/create HTTP/1.1
> Host: localhost
> User-Agent: curl/7.61.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 536
> 
* upload completely sent off: 536 out of 536 bytes
< HTTP/1.1 500 Internal Server Error
< Api-Version: 1.38
< Content-Type: application/json
< Docker-Experimental: false
< Ostype: linux
< Server: Docker/18.06.1-ce (linux)
< Date: Mon, 05 Nov 2018 10:31:29 GMT
< Content-Length: 86
< 
{"message":"rpc error: code = Unknown desc = name conflicts with an existing object"}
* Connection #0 to host localhost left intact
```

### PR DESCRIPTION
**Pull request by thaJeztah**
fixes https://github.com/moby/moby/issues/38140

Before this change, attempting to create a service with a name that already exists produces a 500 error;

```bash
curl -v \
  --unix-socket /var/run/docker.sock \
  -X POST \
  "http://localhost/v1.30/services/create" \
  -H "Content-Type: application/json" \
  -d '{"EndpointSpec":{"Mode":"vip"},"Labels":{},"Mode":{"Replicated":{}},"Name":"testing","TaskTemplate":{"ContainerSpec":{"DNSConfig":{},"Image":"nginx:alpine@sha256:ae5da813f8ad7fa785d7668f0b018ecc8c3a87331527a61d83b3b5e816a0f03c","Init":false},"ForceUpdate":0,"Placement":{"Platforms":[{"Architecture":"amd64","OS":"linux"},{"OS":"linux"},{"Architecture":"arm64","OS":"linux"},{"Architecture":"386","OS":"linux"},{"Architecture":"ppc64le","OS":"linux"},{"Architecture":"s390x","OS":"linux"}]},"Resources":{"Limits":{},"Reservations":{}}}}'
```

```
> POST /v1.30/services/create HTTP/1.1
> Host: localhost
> User-Agent: curl/7.61.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 536
> 
* upload completely sent off: 536 out of 536 bytes
< HTTP/1.1 500 Internal Server Error
< Api-Version: 1.38
< Content-Type: application/json
< Docker-Experimental: false
< Ostype: linux
< Server: Docker/18.06.1-ce (linux)
< Date: Mon, 05 Nov 2018 10:31:29 GMT
< Content-Length: 86
< 
{"message":"rpc error: code = Unknown desc = name conflicts with an existing object"}
```

After this change, a 409 (conflict) is returned:

```bash
curl -v \
  --unix-socket /var/run/docker.sock \
  -X POST \
  "http://localhost/v1.30/services/create" \
  -H "Content-Type: application/json" \
  -d '{"EndpointSpec":{"Mode":"vip"},"Labels":{},"Mode":{"Replicated":{}},"Name":"testing","TaskTemplate":{"ContainerSpec":{"DNSConfig":{},"Image":"nginx:alpine@sha256:ae5da813f8ad7fa785d7668f0b018ecc8c3a87331527a61d83b3b5e816a0f03c","Init":false},"ForceUpdate":0,"Placement":{"Platforms":[{"Architecture":"amd64","OS":"linux"},{"OS":"linux"},{"Architecture":"arm64","OS":"linux"},{"Architecture":"386","OS":"linux"},{"Architecture":"ppc64le","OS":"linux"},{"Architecture":"s390x","OS":"linux"}]},"Resources":{"Limits":{},"Reservations":{}}}}'
```

```
> POST /v1.30/services/create HTTP/1.1
> Host: localhost
> User-Agent: curl/7.52.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 536
> 
* upload completely sent off: 536 out of 536 bytes
< HTTP/1.1 409 Conflict
< Api-Version: 1.40
< Content-Type: application/json
< Docker-Experimental: false
< Ostype: linux
< Server: Docker/dev (linux)
< Date: Mon, 05 Nov 2018 11:33:20 GMT
< Content-Length: 84
< 
{"message":"rpc error: code = AlreadyExists desc = service testing already exists"}
```

### CODE REVIEW

**Comment by thaJeztah** [comment]
depends on https://github.com/docker/swarmkit/pull/2779 to be vendored

**Comment by thaJeztah** [comment]
ok; swarmkit changes were merged and vendored, so this is no longer WIP

@vdemeester @cpuguy83 PTAL

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

File: integration/service/create_test.go [hunk 1]
```diff
@@ -123,6 +125,34 @@ func TestCreateServiceMultipleTimes(t *testing.T) {
 	poll.WaitOn(t, networkIsRemoved(client, overlayID), poll.WithTimeout(1*time.Minute), poll.WithDelay(10*time.Second))
 }
 
+func TestCreateServiceConflict(t *testing.T) {
+	skip.If(t, testEnv.DaemonInfo.OSType == "windows")
```
Comment (cpuguy83) [inline integration/service/create_test.go]: Why skip?

Comment (thaJeztah) [reply integration/service/create_test.go]: Setting up a swarm in tests is currently not working, that's why all these tests are currently skipped on Windows; see https://github.com/moby/moby/blob/5d82d77a6df0c95bb5986ace1255de424c700b33/integration/internal/swarm/service.go#L50-L61

**Review by cpuguy83 — APPROVED** [review]
LGTM
