### PR TITLE
Fix docker startup failure due to dangling endpoints

### LINKED ISSUE #17083: Docker engine 1.9.0-rc1 does not gracefully restart
Description of problem: When stopping the docker daemon via `service docker stop`, it's possible to get in a state where the engine immediately crashes on start with a network configuration issue. This is not resolved by restarting the docker host.

`docker version`:
```
Client:
 Version:      1.9.0-rc1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   9291a0e
 Built:        Wed Oct 14 03:04:22 UTC 2015
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```
(Server version is same as client)

`docker info`:
?

`uname -a`:
`Linux vagrant-ubuntu-trusty-64 3.13.0-39-generic #66-Ubuntu SMP Tue Oct 28 13:30:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

Environment details (AWS, VirtualBox, physical, etc.):
Ubuntu 14.04, VirtualBox (vagrant)

How reproducible:
Not sure, happened on the 2nd time I restarted my daemon after upgrading from 1.8.2 to 1.9.0-rc1

Steps to Reproduce:
1. Run a container
2. Stop docker daemon
3. Try starting docker daemon

Actual Results:
```bash
$ sudo service docker start
docker start/running, process 19174
$ sudo docker ps
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
$ sudo tail /var/log/upstart/docker.log
/var/run/docker.sock is up
INFO[0000] [graphdriver] using prior storage driver "aufs" 
INFO[0000] API listen on /var/run/docker.sock           
INFO[0000] Firewalld running: false                     
FATA[0000] Error starting daemon: Error initializing network controller: could not delete the default bridge network: network bridge has active endpoints 
```

Expected Results:
Docker daemon does not crash immediately

Additional info:

### PR DESCRIPTION
**Pull request by mrjana**
There could be dangling endpoints in libnetwork database in the following case:
- Docker daemon crashes/exits in the middle of startup of containers
- Docker daemon crashes/exits/killed in the middle of stopping of containers

Also when there is a failure in `endpoint.Join` after `network.CreateEndpoint` is successfull, then we forget to cleanup the endpoint. 

This PR fixes all these scenario. Since these failure modes are only possible in racy situations it will be very difficult to add integration tests for these without spending too much time. All of these racy situations were manually simulated and verified to fix them. 

Fixes #17083

### CODE REVIEW

File: daemon/container_unix.go [hunk 1]
```diff
@@ -1124,14 +1135,6 @@ func (container *Container) releaseNetwork() {
 		return
 	}
 
-	for _, ns := range networks {
-		n, err := container.daemon.FindNetwork(ns)
-		if err != nil {
-			continue
-		}
-		container.disconnectFromNetwork(n, false)
```
Comment (mavenugo) [inline daemon/container_unix.go]: Now that `disconnectFromNetwork` is removed from the releseNetwork, can you also make the correction to the
disconnectFromNetwork definition by removing the `updateSettings` parameter altogether ?
We use in only 2 places (one is here) and the other from the actual user triggered DisconnectFromNetwork.
And hence making the suggested changes will make the code read better.

File: daemon/container_unix.go [hunk 2]
```diff
@@ -938,22 +940,31 @@ func (container *Container) connectToNetwork(idOrName string, updateSettings boo
 	}
 
 	ep, err := container.getEndpointInNetwork(n)
-	if err != nil {
-		if _, ok := err.(libnetwork.ErrNoSuchEndpoint); !ok {
-			return err
-		}
+	if err == nil {
```
Comment (mavenugo) [inline daemon/container_unix.go]: thanks for cleaning this up and making it more explicit.

**Comment by mavenugo** [comment]
@mrjana thanks for the changes. I had already reviewed the vendor-in changes in libnetwork project. Couple of minor comments on the docker daemon fix. PTAL.

File: daemon/container_unix.go [hunk 3]
```diff
@@ -976,9 +987,9 @@ func (container *Container) connectToNetwork(idOrName string, updateSettings boo
 		if err != nil {
 			return err
 		}
-	}
 
-	container.updateSandboxNetworkSettings(sb)
+		container.updateSandboxNetworkSettings(sb)
```
Comment (mavenugo) [inline daemon/container_unix.go]: I can see how this change makes the code more readable. 
Is there any other functional reason for moving this inside the if check ?
am fine with it BTW.

Comment (tiborvass) [inline daemon/container_unix.go]: @mrjana does `controller.WalkSandboxes` return something on line 974?

File: vendor/src/github.com/docker/libnetwork/sandbox_store.go [hunk 4]
```diff
@@ -132,7 +134,16 @@ func (sb *sandbox) storeUpdate() error {
...
 	}
 
-	return sb.controller.updateToStore(sbs)
+	err := sb.controller.updateToStore(sbs)
+	if err == datastore.ErrKeyModified {
+		// When we get ErrKeyModified it is sufficient to just
+		// go back and retry.  No need to get the object from
+		// the store because we always regenerate the store
+		// state from in memory sandbox state
+		goto retry
```
Comment (tiborvass) [inline vendor/src/github.com/docker/libnetwork/sandbox_store.go]: can't this be an infinite loop?

File: daemon/container_unix.go (hunk 3 above)
Comment (tiborvass) [inline daemon/container_unix.go]: ok apparently it doesn't return anything.
I'm also not sure why this was moved inside the if.
If WalkSandboxes sets `sb` to something else than `nil`, then in the previous code we call updateSandboxNetworkSettings with that `sb`, whereas in your current PR, we wouldn't call it.

File: daemon/container_unix.go (hunk 2 above)
Comment (cpuguy83) [inline daemon/container_unix.go]: when/why would this ever be true?

**Comment by tiborvass** [comment]
@mrjana needs test for fixing the issue

File: daemon/container_unix.go (hunk 2 above)
Comment (tiborvass) [inline daemon/container_unix.go]: @cpuguy83 if an endpoint already exists

Comment (mrjana) [inline daemon/container_unix.go]: @cpuguy83 This is protect and give a meaningful error message to a user who is trying to connect the container to a network with which it is already connected

File: daemon/container_unix.go (hunk 3 above)
Comment (mrjana) [inline daemon/container_unix.go]: It should not happen like that. Only the first time when WalkSandboxes yields should the sandbox Id be set in the NetworkSettings. Not for every connect.

File: vendor/src/github.com/docker/libnetwork/sandbox_store.go (hunk 4 above)
Comment (mrjana) [inline vendor/src/github.com/docker/libnetwork/sandbox_store.go]: It cannot be an infinite loop. If there are two racing go routines who end up here, one of them will regenerate the index properly so the other which goes through a retry will use the correct index in the next retry.

**Comment by mrjana** [comment]
@tiborvass What test do you suggest for the failure cases that I described in the PR description?

File: daemon/container_unix.go (hunk 1 above)
Comment (mrjana) [inline daemon/container_unix.go]: Will fix in the next update.

**Comment by tiborvass** [comment]
@mrjana my bad didn't realize it was something hard to test.

File: vendor/src/github.com/docker/libnetwork/sandbox_store.go (hunk 4 above)
Comment (tiborvass) [inline vendor/src/github.com/docker/libnetwork/sandbox_store.go]: @mrjana the question is more, can `err == datastore.ErrKeyModified` happen multiple times in the same goroutine, resulting in multiple retries, and if so, can it happen indefinitely in some case?

File: daemon/container_unix.go (hunk 3 above)
Comment (tiborvass) [inline daemon/container_unix.go]: @mrjana Sorry I'm not sure I understand. I guess I don't see how that answers my question: why don't we need to call `updateSandboxNetworkSettings` with the `sb` returned from the walk, when currently in master that's what we do?

Comment (mrjana) [inline daemon/container_unix.go]: Because it is supposed to be called only once, when the sandbox is created. Not every time the sandbox is retrieved from the sandbox database. You can call it multiple times but there really is no need. Please let me know if you need more clarification.

File: vendor/src/github.com/docker/libnetwork/sandbox_store.go (hunk 4 above)
Comment (mrjana) [inline vendor/src/github.com/docker/libnetwork/sandbox_store.go]: It depends on how many go routines are racing at any point in time. If there are 10 racing go routines then a particular unfortunate go routine may retry a max of 10 times. The worst case number of retries by any one go routine increases linearly with the number of racing go routines. But still finite.

Comment (tiborvass) [inline vendor/src/github.com/docker/libnetwork/sandbox_store.go]: ok

File: daemon/container_unix.go (hunk 3 above)
Comment (tiborvass) [inline daemon/container_unix.go]: ok that makes sense

**Comment by tiborvass** [comment]
@mrjana please update to address https://github.com/docker/docker/pull/17191#discussion_r42445131 then we should be good.

**Comment by mavenugo** [comment]
thanks @mrjana. LGTM.

**Comment by tiborvass** [comment]
LGTM

**Comment by Sabya1981** [comment]
Still the issue exists  at v17

**Comment by thaJeztah** [comment]
@Sabya1981 please don't comment on closed pulled requests; if you are running into an issue and suspect there's a bug, open a ticket with the details requested in the [issue template](https://raw.githubusercontent.com/moby/moby/9b094fc4a3845c1f1c8aed9730421aab096dadc1/.github/ISSUE_TEMPLATE.md)
