### PR TITLE
Fix flaky test, TestDockerNetworkHostModeUngracefulDaemonRestart

### LINKED ISSUE #19368: Flaky test: TestDockerNetworkHostModeUngracefulDaemonRestart
Description of problem:
This one has failed a few times in the past couple of days with gccgo:
https://jenkins.dockerproject.org/job/Docker%20Master%20%28gccgo%29/1285/consoleFull
https://jenkins.dockerproject.org/job/Docker%20Master%20%28gccgo%29/1287/consoleFull
https://jenkins.dockerproject.org/job/Docker%20Master%20%28gccgo%29/1294/consoleFull

`docker version`:
1.10.10-dev  (latest upstream)

`docker info`:
:exclamation:  This is to make Gordon happy, and should be ignored since it's from my laptop (running in a container), not one of Docker's test nodes.

# ./docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.10.0-dev
Storage Driver: devicemapper
 Pool Name: docker-253:2-5914896-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop2
 Metadata file: /dev/loop3
 Data Space Used: 11.8 MB
 Data Space Total: 107.4 GB
 Data Space Available: 84.95 GB
 Metadata Space Used: 581.6 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: false
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82 (2013-10-04)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.2.8-200.fc22.x86_64
Operating System: Ubuntu 14.04.3 LTS (containerized)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.678 GiB
Name: 703f7cbf4c89
ID: 5VYE:UHVY:NVE7:FXOH:6XFB:MT4G:2WOX:BXUT:5E7S:VFRS:EL4S:6HOX
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

`uname -a`:
:exclamation: same comment as above. 
4.2.8-200.fc22.x86_64

Environment details (AWS, VirtualBox, physical, etc.):
docker's jenkins (see above links)

How reproducible:
flaky. always seen by me in docker's jenkins builds

Steps to Reproduce:
1. someone commits something
2. it gets merged
3. the jenkins build is triggered

Actual Results:
Test always passes

Expected Results:
Sometimes it doesn't

Additional info:
I'll try to look into it today. I haven't tried recreating it locally but wanted to get it into an issue so others can "me too" it and so I don't forget about it.

### PR DESCRIPTION
**Pull request by tophj-ibm**
Fixes #19368 by waiting until all container statuses are running
before killing the daemon

Signed-off-by: Christopher Jones tophj@linux.vnet.ibm.com

### CODE REVIEW

**Comment by icecrime** [comment]
Thanks @tophj-ibm :heartbeat:

**Comment by tiborvass** [comment]
LGTM and :popcorn:

**Comment by jfrazelle** [comment]
LGTM

**Comment by mavenugo** [comment]
Thanks @tophj-ibm... good catch. LGTM

File: integration-cli/docker_cli_network_unix_test.go [hunk 1]
```diff
@@ -1012,6 +1012,10 @@ func (s *DockerNetworkSuite) TestDockerNetworkHostModeUngracefulDaemonRestart(c
 		cName := fmt.Sprintf("hostc-%d", i)
 		out, err := s.d.Cmd("run", "-d", "--name", cName, "--net=host", "--restart=always", "busybox", "top")
 		c.Assert(err, checker.IsNil, check.Commentf(out))
+
+		// verfiy container has finished starting before killing daemon
+		err = s.d.waitRun(fmt.Sprintf("hostc-%d", i))
```
Comment (MHBauer) [inline integration-cli/docker_cli_network_unix_test.go]: refactor `fmt.Sprintf("hostc-%d", i)` on this line and L#1012 into a var?

Comment (MHBauer) [inline integration-cli/docker_cli_network_unix_test.go]: oh wait, it already is. Can we reuse `cName` from L#1012, or am I missing something?

Comment (calavera) [inline integration-cli/docker_cli_network_unix_test.go]: oh, sorry, I didn't see these comments before merging :pensive:

Comment (MHBauer) [inline integration-cli/docker_cli_network_unix_test.go]: @calavera no biggie. It is not wrong.

Comment (tophj-ibm) [inline integration-cli/docker_cli_network_unix_test.go]: @MHBauer nope you're correct. I made a new branch because I didn't want to remove my debug statements and see what happens :sob:

**Comment by cpuguy83** [comment]
:100:
