### PR TITLE
Fallback to file polling for jsonlog reader on err

### LINKED ISSUE #15815: docker 1.8.1 `docker logs -f container_name`  runs into unexpected error, always return at once with different results?
`docker version`:
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

`docker info`:
Containers: 110
Images: 15685
Storage Driver: devicemapper
 Pool Name: docker-253:16-24641542-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 330.9 GB
 Data Space Total: 536.9 GB
 Data Space Available: 197.1 GB
 Metadata Space Used: 667.4 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 1.48 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /data/docker/devicemapper/devicemapper/data
 Metadata loop file: /data/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-62-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 2
Total Memory: 11.74 GiB
Name: ubuntu
ID: SDGY:EEUT:QTMG:KODE:AJHB:T7YX:ZB2Z:ZVWP:5BM3:I2VR:GVYK:Y3ON

`uname -a`:
Linux ubuntu 2-Ubuntu SMP Tue Aug 11 14:29:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Description of problem:
I am really sorry that I can not reproduce this kind of problem, as in my experiement environment, 2 docker work fine, and 2 failed to run command `docker logs -f container_name`.

Below is my running error display:
```
root@ubuntu:~# docker logs -f 0426992ca9c2
root@ubuntu:~# docker logs -f 0426992ca9c2
root@ubuntu:~# docker logs -f 0426992ca9c2
=> Creating and admin user with a random password in Tomcat
=> Done!
root@ubuntu:~# docker logs -f 0426992ca9c2
=> Creating and admin user with a random password in Tomcat
root@ubuntu:~# docker logs -f 0426992ca9c2
root@ubuntu:~# docker logs -f 0426992ca9c2
=> Creating and admin user with a random password in Tomcat
You have new mail in /var/mail/root
root@ubuntu:~# docker logs -f 0426992ca9c2
root@ubuntu:~# docker logs -f 0426992ca9c2
=> Creating and admin user with a random password in Tomcat
=> Done!
========================================================================
root@ubuntu:~# docker logs -f 0426992ca9c2
=> Creating and admin user with a random password in Tomcat
root@ubuntu:~# docker logs -f 0426992ca9c2
root@ubuntu:~# docker logs -f 0426992ca9c2
root@ubuntu:~# docker logs -f 0426992ca9c2
=> Creating and admin user with a random password in Tomcat
root@ubuntu:~# docker logs -f 0426992ca9c2
root@ubuntu:~# docker logs -f 0426992ca9c2
root@ubuntu:~# docker logs -f 0426992ca9c2
root@ubuntu:~# docker logs -f 0426992ca9c2
```

While command `docker logs -f  0426992ca9c2` should be blocked as the parameter `-f`. However, in my machine it returns at once.
When I ran this command several times, <b>no one will be blocked</b> and <b>return different results</b>.It is definitely a severe BUG.

Below is the actual log json file on the disk:

```
{"log":"=\u003e Creating and admin user with a random password in Tomcat\n","stream":"stdout","time":"2015-08-25T03:52:08.284018814Z"}
{"log":"=\u003e Done!\n","stream":"stdout","time":"2015-08-25T03:52:08.285392692Z"}
{"log":"========================================================================\n","stream":"stdout","time":"2015-08-25T03:52:08.285410189Z"}
{"log":"You can now configure to this Tomcat server using:\n","stream":"stdout","time":"2015-08-25T03:52:08.285417819Z"}
{"log":"\n","stream":"stdout","time":"2015-08-25T03:52:08.285423802Z"}
{"log":"    admin:1W3EIMQmQ89N\n","stream":"stdout","time":"2015-08-25T03:52:08.285429289Z"}
{"log":"\n","stream":"stdout","time":"2015-08-25T03:52:08.285434852Z"}
{"log":"========================================================================\n","stream":"stdout","time":"2015-08-25T03:52:08.285440298Z"}
{"log":"Aug 25, 2015 3:52:28 AM org.apache.catalina.core.AprLifecycleListener init\n","stream":"stderr","time":"2015-08-25T03:52:29.082414705Z"}
{"log":"INFO: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib\n","stream":"stderr","time":"2015-08-25T03:52:29.084458481Z"}
{"log":"Aug 25, 2015 3:52:39 AM org.apache.coyote.AbstractProtocol init\n","stream":"stderr","time":"2015-08-25T03:52:39.601750274Z"}
{"log":"INFO: Initializing ProtocolHandler [\"http-bio-8080\"]\n","stream":"stderr","time":"2015-08-25T03:52:39.601826153Z"}
{"log":"Aug 25, 2015 3:52:40 AM org.apache.coyote.AbstractProtocol init\n","stream":"stderr","time":"2015-08-25T03:52:40.19324596Z"}
{"log":"INFO: Initializing ProtocolHandler [\"ajp-bio-8009\"]\n","stream":"stderr","time":"2015-08-25T03:52:40.193303832Z"}
{"log":"Aug 25, 2015 3:52:40 AM org.apache.catalina.startup.Catalina load\n","stream":"stderr","time":"2015-08-25T03:52:40.23796512Z"}
{"log":"INFO: Initialization processed in 25971 ms\n","stream":"stderr","time":"2015-08-25T03:52:40.238035231Z"}
{"log":"Aug 25, 2015 3:52:41 AM org.apache.catalina.core.StandardService startInternal\n","stream":"stderr","time":"2015-08-25T03:52:41.224497076Z"}
{"log":"INFO: Starting service Catalina\n","stream":"stderr","time":"2015-08-25T03:52:41.224572273Z"}
{"log":"Aug 25, 2015 3:52:41 AM org.apache.catalina.core.StandardEngine startInternal\n","stream":"stderr","time":"2015-08-25T03:52:41.225001973Z"}
{"log":"INFO: Starting Servlet Engine: Apache Tomcat/7.0.55\n","stream":"stderr","time":"2015-08-25T03:52:41.225001973Z"}
{"log":"Aug 25, 2015 3:52:41 AM org.apache.catalina.startup.HostConfig deployDirectory\n","stream":"stderr","time":"2015-08-25T03:52:41.630898209Z"}
``` 

Sorry that I can not reproduce this situation, but I think this issue is really important. What I can provide more is that  It seems that this situation happens on some high load machine, as all docker daemons in my environment are the same, however docker with low load did not run into `docker logs -f` error. 

Allen Sun
DaoCloud

### PR DESCRIPTION
**Pull request by cpuguy83**
Fixes #15815

### CODE REVIEW

File: daemon/logger/jsonfilelog/read.go [hunk 1]
```diff
@@ -0,0 +1,216 @@
...
+					retries++
+					continue
+				}
+				logWatcher.Err <- err
+				return
+			}
+
+			logrus.WithField("logger", "json-file").Debugf("waiting for events")
+			if err := fileWatcher.Add(f.Name()); err != nil {
+				logrus.WithField("logger", "json-file").Warn("falling pack to file poller")
```
Comment (calavera) [inline daemon/logger/jsonfilelog/read.go]: `s/falling pack/falling back/`

**Comment by calavera** [comment]
small typo. Otherwise LGTM.

**Comment by LK4D4** [comment]
LGTM
