### PR TITLE
libnetwork: minor cleanup related to GenerateRandomName

### LINKED ISSUE #44362: Crash in netutils.GenerateRandomName
### Description

We used the Fuzz engine to modify some Test(TestGenerateRandomName) data, and then the following crash appeared. We hope to get the help of the developer to confirm whether it is a real bug.

### Reproduce

Part of the modified Test Code

```go
name1, err := GenerateRandomName("veth", 7902739824647)
```

Crash Log

```
panic: runtime error: slice bounds out of range [:7902739824647] with length 64 [recovered]
	panic: runtime error: slice bounds out of range [:7902739824647] with length 64

goroutine 77 [running]:
testing.tRunner.func1.2({0x5a2080, 0xc00001a558})
	/home/gogen/.local/go/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	/home/gogen/.local/go/src/testing/testing.go:1212 +0x218
panic({0x5a2080, 0xc00001a558})
	/home/gogen/.local/go/src/runtime/panic.go:1038 +0x215
github.com/docker/docker/libnetwork/netutils.GenerateRandomName({0x5b3d96, 0x4}, 0x73000000007)
	/home/gogen/workspace/gowork/src/topproj/moby/libnetwork/netutils/utils.go:131 +0x107
```

### Expected behavior

-

### docker version

```bash
-
```

### docker info

```bash
-
```

### Additional Info

Implemented only with go test

### PR DESCRIPTION
**Pull request by neersighted**
- Alternative to #44743
- Fixes #44362

**- What I did**
Moderate cleanup in areas related to libnetwork/netutils, especially GenerateRandomName; consult commit messages for details.

**- How to verify it**
Unit tests, and commit-wise review. The changes are minimal and focused on the immediate areas related to GenerateRandomName

**- Description for the changelog**
N/A

**- A picture of a cute animal (not mandatory but encouraged)**
image

### CODE REVIEW

File: libnetwork/netutils/utils.go [hunk 1]
```diff
@@ -121,14 +121,24 @@ func GenerateMACFromIP(ip net.IP) net.HardwareAddr {
...
-	if _, err := io.ReadFull(rand.Reader, id); err != nil {
+// GenerateRandomName returns a string of the specified length, created by joining the prefix to
+// random hex characters sufficient to create a string of the specified length.
+// If the specified length is less than or equal to the length of the prefix, an error will be
+// returned instead.
+func GenerateRandomName(prefix string, length uint8) (string, error) {
+	prefixLen := uint8(len(prefix))
+	if length <= prefixLen {
+		return "", fmt.Errorf("prefix %s is too long for length %d", prefix, length)
+	}
```
Comment (corhere) [inline libnetwork/netutils/utils.go:132]: As much as I like choosing types which can only represent in-range values, I don't think it helps prevent bugs to make `length` a small unsigned integer. The theoretical valid range for `length` is the interval

    (len(prefix), MaxInt-len(prefix)]

which always excludes zero, but every type in Go has a zero value so there is no way around having the runtime range check. And by the way, the runtime range check has a bug when `len(prefix) > 255`. The `len` builtin evaluates to `int` so it's an uphill battle to use any other type to represent lengths. Even `uint` is troublesome as it can represent a larger range of positive values than `int`.

File: libnetwork/netutils/utils_linux_test.go [hunk 2]
```diff
@@ -186,22 +189,28 @@ func TestNetworkRange(t *testing.T) {
...
-	if name1 == name2 {
-		t.Fatalf("Expected differing values but received %s and %s", name1, name2)
-	}
+	const vethPrefix = "veth"
+	const vethLen = 11
+
+	name1, err := GenerateRandomName(vethPrefix, vethLen)
+	assert.NilError(t, err)
+	assert.Assert(t, strings.HasPrefix(name1, vethPrefix), "Expected name to start with %s", vethPrefix)
+	assert.Equal(t, len(name1), vethLen, "Expected %d characters, instead received %d characters", vethLen, len(name1))
```
Comment (corhere) [inline libnetwork/netutils/utils_linux_test.go:198]:
```suggestion
	assert.Check(t, is.Len(name1, vethLen))
```
(Moby convention is to import [`"gotest.tools/v3/assert/cmp"`](https://pkg.go.dev/gotest.tools/v3@v3.4.0/assert/cmp) as `is`.)

File: libnetwork/netutils/utils_linux_test.go [hunk 3]
```diff
@@ -186,22 +189,28 @@ func TestNetworkRange(t *testing.T) {
...
+
+	name2, err := GenerateRandomName(vethPrefix, vethLen)
+	assert.NilError(t, err)
+	assert.Assert(t, name1 != name2, "Expected differing values but received %s and %s", name1, name2)
```
Comment (corhere) [inline libnetwork/netutils/utils_linux_test.go:202]:
```suggestion
	assert.Check(t, name1 != name2, "Expected differing values but received %q and %q", name1, name2)
```

File: libnetwork/netutils/utils_linux_test.go [hunk 4]
```diff
@@ -186,22 +189,28 @@ func TestNetworkRange(t *testing.T) {
...
+	_, err = GenerateRandomName(vethPrefix, uint8(len(vethPrefix)))
+	assert.ErrorContains(t, err, "too long for length", "Expected error when len(prefix) is equal to length")
+	_, err = GenerateRandomName(vethPrefix, uint8(len(vethPrefix)-1))
+	assert.ErrorContains(t, err, "too long for length", "Expected error when len(prefix) is less than length")
+	_, err = GenerateRandomName(vethPrefix, 0)
+	assert.ErrorContains(t, err, "too long for length", "Expected error when length is 0")
+
+	name3, err := GenerateRandomName(vethPrefix, math.MaxUint8)
+	assert.NilError(t, err, "Expected no error when length is max uint8")
+	assert.Equal(t, len(name3), math.MaxUint8, "Expected %d characters, instead received %d characters", math.MaxUint8, len(name3))
```
Comment (corhere) [inline libnetwork/netutils/utils_linux_test.go:213]: Subtests?

**Comment by neersighted** [comment]
Dropped the change to uint and made the tests composable/declarative.

File: libnetwork/netutils/utils_linux_test.go [hunk 5]
```diff
@@ -186,21 +190,44 @@ func TestNetworkRange(t *testing.T) {
...
+	}{
+		{vethPrefix, -1, true},
+		{vethPrefix, 0, true},
+		{vethPrefix, len(vethPrefix) - 1, true},
+		{vethPrefix, len(vethPrefix), true},
+		{vethPrefix, len(vethPrefix) + 1, false},
+		{vethPrefix, 255, false},
+	}
+	for _, tc := range testCases {
+		t.Run(fmt.Sprintf("prefix=%s,length=%d", tc.prefix, tc.length), func(t *testing.T) {
```
Comment (corhere) [inline libnetwork/netutils/utils_linux_test.go:209]: Generally, slash (`/`) characters are the preferred choice to delimit the parts of a subtest name [due to the behaviour of the `go test -run` flag.](https://pkg.go.dev/cmd/go#hdr-Testing_flags:~:text=%2Drun%20regexp%0A%20%20%20%20Run,those%20sub%2Dtests.) E.g.:
```console
$ go test -run TestGenerateRandomName//length=0 ./libnetwork/netutils
```
will focus on the subtests where length=0, irrespective of the prefix.

```suggestion
		t.Run(fmt.Sprintf("prefix=%s/length=%d", tc.prefix, tc.length), func(t *testing.T) {
```

(This is one of those obscure pieces of tribal knowledge tucked away in the documentation for the `go` command instead of somewhere actually discoverable, like the `"testing"` package docs)

File: libnetwork/netutils/utils_linux_test.go [hunk 6]
```diff
@@ -186,21 +190,44 @@ func TestNetworkRange(t *testing.T) {
...
+				assert.Check(t, is.ErrorContains(err, "invalid length"))
+			} else {
+				assert.NilError(t, err)
+				assert.Check(t, strings.HasPrefix(name, tc.prefix), "Expected name to start with %s", tc.prefix)
+				assert.Check(t, is.Equal(len(name), tc.length), "Expected %d characters, instead received %d characters", tc.length, len(name))
+			}
+		})
+	}
+
+	var randomNames [16]string
```
Comment (corhere) [inline libnetwork/netutils/utils_linux_test.go:221]: `randomNames` is never assigned to, which invalidates the no-duplicates test.

**Review by corhere — CHANGES_REQUESTED** [review]
The no-duplicates test is busted. Otherwise LGTM

File: libnetwork/netutils/utils_linux_test.go (hunk 5 above)
Comment (neersighted) [reply libnetwork/netutils/utils_linux_test.go:209]: I did not know that you could leave path segments empty -- neat!

File: libnetwork/netutils/utils_linux_test.go [hunk 7]
```diff
@@ -186,21 +190,45 @@ func TestNetworkRange(t *testing.T) {
...
+	for _, randomName := range randomNames {
+		randomName, err = GenerateRandomName(vethPrefix, vethLen)
+		assert.NilError(t, err)
+
+		for _, oldName := range randomNames {
+			if randomName == oldName {
+				t.Fatalf("Duplicate random name generated: %s", randomName)
+			}
+		}
 	}
```
Comment (corhere) [inline libnetwork/netutils/utils_linux_test.go:232]: That still doesn't assign to `randomNames`. This will:
```suggestion
	var randomNames [16]string
	for i := range randomNames {
		randomName, err := GenerateRandomName(vethPrefix, vethLen)
		assert.NilError(t, err)

		for _, oldName := range randomNames {
			if randomName == oldName {
				t.Fatalf("Duplicate random name generated: %s", randomName)
			}
		}
		
		randomNames[i] = randomName
	}
```

**Review by corhere — APPROVED** [review]
