### PR TITLE
Sanitize docker labels when used as journald field names

### LINKED ISSUE #23528: Should sanitize docker labels/env when using as journald field names
**Output of `docker version`:**

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   4419fdb-dirty
 Built:        Fri Dec 18 00:01:03 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   4419fdb-dirty
 Built:        Fri Dec 18 00:01:03 UTC 2015
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 26
Images: 75
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: journald
Kernel Version: 4.3.3-coreos
Operating System: CoreOS 899.1.0
CPUs: 16
Total Memory: 62.91 GiB
Name: ip-10-20-9-13.us-west-2.compute.internal
ID: ZXQE:OKTS:EA6K:2F27:CYMJ:3GQJ:2V3B:CQMG:KIJG:5VW2:P6O3:4QLY
```

**Additional environment details (AWS, VirtualBox, physical, etc.):** AWS

**Steps to reproduce the issue:**
1. Start docker daemon

  ```
docker daemon --log-driver=journald --log-opt labels=io.kubernetes.pod.name
  ```

2. Launch a container that has label `io.kubernetes.pod.name`. For example

  ```
docker run -l io.kubernetes.pod.name=foo -d ubuntu bash -c "while true; do echo 'Hello World'; sleep 5; done"
  ```

**Describe the results you received:**
`io.kubernetes.pod.name=foo` passed to journald for the logs of this container, with the label name changed to `IO_KUBERNETES_POD_NAME` due to the requirements on the field names imposed by journald

**Describe the results you expected:**
Getting `journal error: variable name contains invalid character, ignoring` in the docker daemon log.

**Additional information you deem important (e.g. issue happens only occasionally):**
Seems related to this line: https://github.com/docker/docker/blob/11a24f19c2da88b6c3b50114863f24c06c5ce2fd/daemon/logger/journald/journald.go#L56

The `keyMod` function should change all letters to upper case, any non-alphanumeric character to underscores, and remove any leading underscores.

I couldn't find any definitive documentation on journald field name requirements, but found this: https://github.com/coreos/go-systemd/blob/master/journal/journal.go#L68

### PR DESCRIPTION
**Pull request by yongtang**
**\- What I did**

This fix tries to address the issue raised in #23528 where docker labels caused journald log error because journald has special requirements on field names.

**\- How I did it**

This fix addresses this issue by sanitize the labels per requirements of journald.

**\- How to verify it**

Additional unit tests have been added to cover the changes.

In addition, tests have been done manually based on the description in #23528.

**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**

This fix fixes #23528.

Signed-off-by: Yong Tang yong.tang.github@outlook.com

### CODE REVIEW

File: daemon/logger/journald/journald.go [hunk 1]
```diff
@@ -36,6 +36,22 @@ func init() {
 	}
 }
 
+func sanitizeKeyMod(s string) string {
```
Comment (LK4D4) [inline daemon/logger/journald/journald.go]: Can you pls describe in docstring to this function what it does.

**Comment by yongtang** [comment]
Thanks @LK4D4 the pull request has been updated with the description of `sanitizeKeyMod(s string)` in comment. Let me know if there are any issues.

File: daemon/logger/journald/journald.go [hunk 2]
```diff
@@ -36,6 +36,26 @@ func init() {
 	}
 }
 
+// sanitizeKeyMode returns the sanitized string so that it could be used in journald.
+// In journald log, there are special requirements for fields.
+// Fields must be composed of uppercase letters, numbers, and underscores, but must
```
Comment (LK4D4) [inline daemon/logger/journald/journald.go]: So, it can be only ascii characters?

**Comment by LK4D4** [comment]
Ok, thanks!
LGTM

File: daemon/logger/journald/journald.go (hunk 2 above)
Comment (yongtang) [inline daemon/logger/journald/journald.go]: Yes, ascii only.

File: daemon/logger/journald/journald.go [hunk 3]
```diff
@@ -36,6 +36,26 @@ func init() {
...
+// not start with an underscore.
```
Comment (vdemeester) [inline daemon/logger/journald/journald.go]: Should we have a test on that (the fact that a string starting with an underscore is handled somehow 👼).

Comment (yongtang) [inline daemon/logger/journald/journald.go]: Thanks @vdemeester. The pull request has been updated with a couple of test cases for strings starting with underscore. Let me know if there are any issues.

**Comment by vdemeester** [comment]
Thanks @yongtang !
LGTM 🐮
