### PR TITLE
Change gelf logger to comply with gelf spec

### LINKED ISSUE #37572: Gelf logdriver: empty lines not allowed by spec
The Gelf specification says: short_message is a required field. (http://docs.graylog.org/en/2.4/pages/gelf.html#gelf-payload-specification)

but docker logs even empty lines:
https://github.com/moby/moby/blob/3a633a712c8bbb863fe7e57ec132dd87a9c4eff7/daemon/logger/gelf/gelf.go#L177

which will throw errors e.g. in GrayLog:
> java.lang.IllegalArgumentException: GELF message <b8249660-94e4-11e8-af83-0242ac140004> (received from <172.20.0.1:52615>) has empty mandatory "short_message" field.

### LINKED ISSUE #40232: Logging driver for GELF sends message with empty mandatory field "short_message"
**Description**

Docker, or rather the logging driver for *GELF*, sends its output without checking
if messages have any content in the mandatory field `short_message`. According to the [*GELF* payload specification](http://docs.graylog.org/en/2.4/pages/gelf.html#gelf-payload-specification) this is explicitly forbidden and may result in exceptions.

In the following bug report I am using Graylog as an example for the consequences that
result downstream.

**Steps to reproduce the issue:**

- Run a local instance of Graylog 3 with docker compose version 3 in a default configuration as described [here](https://docs.graylog.org/en/3.1/pages/installation/docker.html).

Note that this is not core to the issue at hand, but merely serves as a nice demonstration of the consequences:

```version: '3'
services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongo:
    image: mongo:3
    networks:
      - graylog
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.2
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - graylog
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:3.1
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    networks:
      - graylog
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
networks:
  graylog:
    driver: bridge
```

- Run the hello-world docker container with gelf as a log driver:

```bash
docker run \
    --log-driver gelf \
    --log-opt gelf-address=udp://localhost:12201 \
    hello-world
```

**Describe the results you received:**

Docker now takes the output below, formats it into *GELF* and sends it to graylog:

```
Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/
```

This includes the empty lines that you see in the message above. With empty messages being forbidden in *GELF*, this may result in processing difficulties for a log handler downstream.

In the case of Graylog, this results in several exceptions (here is just one):

```
graylog_1        | 2019-11-21 11:10:39,416 ERROR: org.graylog2.shared.buffers.processors.DecodingProcessor - Unable to decode raw message RawMessage{id=8cd524f1-0c4f-11ea-86f4-0242ac170004, journalOffset=12, codec=gelf, payloadSize=308, timestamp=2019-11-21T11:10:39.295Z, remoteAddress=/172.23.0.1:41406} on input <5dd670a67fa7b70012e2ef6a>.
graylog_1        | 2019-11-21 11:10:39,417 ERROR: org.graylog2.shared.buffers.processors.DecodingProcessor - Error processing message RawMessage{id=8cd524f1-0c4f-11ea-86f4-0242ac170004, journalOffset=12, codec=gelf, payloadSize=308, timestamp=2019-11-21T11:10:39.295Z, remoteAddress=/172.23.0.1:41406}
graylog_1        | java.lang.IllegalArgumentException: GELF message <8cd524f1-0c4f-11ea-86f4-0242ac170004> (received from <172.23.0.1:41406>) has empty mandatory "short_message" field.
graylog_1        | 	at org.graylog2.inputs.codecs.GelfCodec.validateGELFMessage(GelfCodec.java:252) ~[graylog.jar:?]
graylog_1        | 	at org.graylog2.inputs.codecs.GelfCodec.decode(GelfCodec.java:134) ~[graylog.jar:?]
graylog_1        | 	at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:150) ~[graylog.jar:?]
graylog_1        | 	at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:91) [graylog.jar:?]
graylog_1        | 	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:86) [graylog.jar:?]
graylog_1        | 	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:45) [graylog.jar:?]
graylog_1        | 	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
graylog_1        | 	at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
graylog_1        | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

**Describe the results you expected:**

Normally, I would expect no error in Graylog since it would not have to deal with empty mandatory fields in the first place.

**Additional information you deem important (e.g. issue happens only occasionally):**

This bug affects all projects that use *GELF* as a logging format, including the elastic stack (though it may be handled differently there). It also extends to use in `docker-compose` files:

```
version: '3'
services:
  hello:
    image: hello-world
    logging:
      driver: "gelf"
      options:
        gelf-address: udp://localhost:12201
        tag: "hello"
```

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 3
  Paused: 0
  Stopped: 1
 Images: 4
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.0.0-36-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.764GiB
 Name: ubuntu
 ID: VRJA:MIFX:EADV:AZ4W:EPIK:J6YZ:22ZY:VPUJ:QPQH:7ALR:VCCQ:HKBS
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

- Run on a fresh install of Ubuntu 18.04 in VMWare Workstation Pro

### PR DESCRIPTION
**Pull request by Jonas-Heinrich**
The [gelf payload specification](http://docs.graylog.org/en/2.4/pages/gelf.html#gelf-payload-specification) demands that the field `short_message` *MUST* be set by the client library.
Since docker logging via the gelf driver sends messages line by line, it can happen that messages with an empty `short_message` are passed on. This causes strict downstream processors (like graylog) to raise an exception.

The logger now replaces message lines of length zero with the content `<empty-line>`. This is done
for the following reasons:

- Keeps it possible to reconstruct the logging output in its entirety
- Does not break logging setups that need the information from empty logs (e.g. Logstash rules)

fixes https://github.com/moby/moby/issues/40232 Logging driver for GELF sends message with empty mandatory field "short_message"
fixes https://github.com/moby/moby/issues/37572 Gelf logdriver: empty lines not allowed by spec

### CODE REVIEW

**Comment by Jonas-Heinrich** [comment]
I am open to changing the content of the substituted message or even disregarding the log message completely.

File: daemon/logger/gelf/gelf.go [hunk 1]
```diff
@@ -171,6 +171,10 @@ func (s *gelfLogger) Log(msg *logger.Message) error {
 		level = gelf.LOG_ERR
 	}
 
+	if len(msg.Line) == 0 {
+		msg.Line = []byte("<empty-line>")
```
Comment (thaJeztah) [inline daemon/logger/gelf/gelf.go]: Not a fan of the `<empty-line>` magic value; I expect empty lines being important to be a bit of a corner-case, and  recall we had something similar with the Splunk logging driver; for that driver we're skipping empty lines (see https://github.com/moby/moby/pull/34520)

So, unless there's a strong case for preserving empty lines, I'd suggest skipping them entirely.

In that case, I would prefer this check to be the very first in the function (so before the `level := ....` line), and return early;

```go
if len(msg.Line) == 0 {
	return nil
}
```

**Review by thaJeztah — CHANGES_REQUESTED** [review]
thanks! I left a comment; could you perhaps also change the first line of the commit message to mention what the actual change is? e.g. 

```
logger/gelf: skip empty lines to comply with spec

....
```

**Comment by thaJeztah** [comment]
ping @mariussturm PTAL 🤗

File: daemon/logger/gelf/gelf.go (hunk 1 above)
Comment (Jonas-Heinrich) [reply daemon/logger/gelf/gelf.go]: Given #34520 and no strong case for empty lines, I agree that it is better to skip them entirely. Consistency is increased between drivers and to be honest most processing logic (e.g. via Logstash) ignores them anyway.

I'll change it to your suggested version.

**Comment by Jonas-Heinrich** [comment]
@thaJeztah By changing the commit message I assume you meant me to `git rebase` and `git push -f`.

As this is my first contribution to such a big project I hope I did everything in the right way. If not, please correct me 😅

**Comment by mariussturm** [comment]
LGTM, also +1 for the deletion of empty lines.

**Comment by thaJeztah** [comment]
Thanks for reviewing, @mariussturm 👍 

> By changing the commit message I assume you meant me to git rebase and git push -f.

Yes, that's what I meant 🤗. I see your commit now looks ok, but I suspect your local fork of the repository was a few commits behind, which caused some additional commits to be pulled in into this PR.

Let me do a quick rebase of your PR to resolve that, but let me know if you want to know the steps to do that (if you're on the Docker community slack, also feel free to ping / DM me there)

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
ping @kolyshkin @cpuguy83 PTAL

**Review by kolyshkin — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
s390x failure looks unrelated; https://ci.docker.com/public/blue/rest/organizations/jenkins/pipelines/moby/branches/PR-40234/runs/3/nodes/47/log/?start=0

```
=== RUN TestCreateServiceMultipleTimes
--- FAIL: TestCreateServiceMultipleTimes (11.55s)
create_test.go:121: assertion failed: error is not nil: Error response from daemon: rpc error: code = FailedPrecondition desc = network fdbqmrselg04mozkbkpctl74j is in use by task 7inqk0za3h0sqix1rt8hq1i22
```

Gelf tests passed on that same run;

```
[2019-11-25T11:08:54.238Z] ok  	github.com/docker/docker/daemon/logger/gelf	0.030s	coverage: 67.0% of statements
```

I'll kick CI one more time to be sure, but moving to "merge"
