### PR TITLE
Windows: Try to detach sandbox on cleanup to avoid permission denied

### LINKED ISSUE #36218: Unable to Remove Containers: driver "windowsfilter" failed to remove root filesystem
**Description**

While conducting a load test with Windows containers, Docker commands became unresponsive (expected). In order to recover the system, the Docker service was restarted. After the restart, the previously created containers can't be started or removed. 

**Steps to reproduce the issue:**
1. Add containers until the system becomes unresponsive.
2. Restart the Docker service.
3. Try to remove one of the containers [**FAIL**]:
```
docker rm -f testsite1
```
4. Try to start on of the containers [**FAIL**].
```
docker start testsite1
```

**Describe the results you received:**

Trying to remove the container fails:
```
> docker rm -f testsite1
Error response from daemon: driver "windowsfilter" failed to remove root filesystem for 9442da524e13337b7b8b69ad9a26882c94140dfa39460034e2f62f9cf0296837: rename C:\ProgramData\docker\windowsfilter\9442da524e13337b7b8b69ad9a26882c94140dfa39460034e2f62f9cf0296837 C:\ProgramData\docker\windowsfilter\9442da524e13337b7b8b69ad9a26882c94140dfa39460034e2f62f9cf0296837-removing: Access is denied.
```

Trying to start the container fails:

```
> docker start testsite1
Error response from daemon: Container is marked for removal and cannot be started.
Error: failed to start containers: testsite1
```

**Describe the results you expected:**

I expected after restarting the Docker service for the containers to be stopped (but visible when running "docker ps -a". Running "docker start <containerName>" should restart the containers. Running "docker rm -f <containerName>" should remove them.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
> docker version
Client:
 Version:      17.06.2-ee-6
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   e75fdb8
 Built:        Mon Nov 27 22:46:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.2-ee-6
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   e75fdb8
 Built:        Mon Nov 27 22:55:16 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 18
 Running: 0
 Paused: 0
 Stopped: 18
Images: 10
Server Version: 17.06.2-ee-6
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows Server Datacenter
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 16GiB
Name: DockerTest
ID: 5IKI:MYU2:AC2W:RABM:W7SX:NPUC:Z2VF:R5BA:43W2:BUM3:V7VR:JSTQ
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Username: harbertc
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

The Docker host is running in Azure.

### PR DESCRIPTION
**Pull request by lowenna**
Fixes https://github.com/moby/moby/issues/36218

A few different scenarios, but it's possible that the daemon can leak sandbox/scratch layers in the Windows graphdriver, and have side effects where containers can't be removed. Here's one such case:

Before:
```
C:\>start dockerd -g c:\control

C:\>docker run --rm -d --name test microsoft/windowsservercore powershell sleep 30
8058fa79bb1c1b580b32bc2e4e27f22090a27fd8cef17aaa31ae02342982e7d3

C:\>taskkill /T /IM dockerd.exe
SUCCESS: Sent termination signal to process with PID 21396, child of PID 21248.
SUCCESS: Sent termination signal to process with PID 21248, child of PID 29336.

C:\>start dockerd -g c:\control

C:\>docker ps -a
CONTAINER ID        IMAGE                         COMMAND                 CREATED             STATUS                PORTS               NAMES
8058fa79bb1c        microsoft/windowsservercore   "powershell sleep 30"   16 seconds ago      Removal In Progress                       test

C:\>docker rm -f 8058
Error response from daemon: container 8058fa79bb1c1b580b32bc2e4e27f22090a27fd8cef17aaa31ae02342982e7d3: driver "windowsfilter" failed to remove root filesystem: rename C:\control\windowsfilter\8058fa79bb1c1b580b32bc2e4e27f22090a27fd8cef17aaa31ae02342982e7d3 C:\control\windowsfilter\8058fa79bb1c1b580b32bc2e4e27f22090a27fd8cef17aaa31ae02342982e7d3-removing: Access is denied.

C:\>dir control\windowsfilter
 Volume in drive C has no label.
 Volume Serial Number is 2E9A-473A

 Directory of C:\control\windowsfilter

08/23/2018  04:16 PM    <DIR>          .
08/23/2018  04:16 PM    <DIR>          ..
08/23/2018  04:16 PM    <DIR>          8058fa79bb1c1b580b32bc2e4e27f22090a27fd8cef17aaa31ae02342982e7d3
08/23/2018  09:04 AM    <DIR>          efa7700f8e4b54cdb068d0c08d600b483846091611cf913f3ba411525207bf93
               0 File(s)              0 bytes
               4 Dir(s)  117,058,809,856 bytes free

C:\>
```

After:

```
C:\>start dockerd -g c:\control

C:\>docker run --rm -d --name test microsoft/windowsservercore powershell sleep 30
01779097b29c3d0b04373c6f1b929f79ccce72a6f43689ade7e9f4cce9a977cd

C:\>taskkill /T /IM dockerd.exe
SUCCESS: Sent termination signal to process with PID 6172, child of PID 27248.
SUCCESS: Sent termination signal to process with PID 27248, child of PID 29336.

C:\>start dockerd -g c:\control

C:\>docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

C:\>dir control\windowsfilter
 Volume in drive C has no label.
 Volume Serial Number is 2E9A-473A

 Directory of C:\control\windowsfilter

08/23/2018  04:14 PM    <DIR>          .
08/23/2018  04:14 PM    <DIR>          ..
08/23/2018  09:04 AM    <DIR>          efa7700f8e4b54cdb068d0c08d600b483846091611cf913f3ba411525207bf93
               0 File(s)              0 bytes
               3 Dir(s)  117,096,996,864 bytes free

C:\>
```

### CODE REVIEW

**Comment by jhowardmsft** [comment]
@carlfischer1. Another backport candidate.

File: daemon/graphdriver/windows/windows.go [hunk 1]
```diff
@@ -331,7 +332,23 @@ func (d *Driver) Remove(id string) error {
 	tmpID := fmt.Sprintf("%s-removing", rID)
 	tmpLayerPath := filepath.Join(d.info.HomeDir, tmpID)
 	if err := os.Rename(layerPath, tmpLayerPath); err != nil && !os.IsNotExist(err) {
-		return err
+		// If permission denied, it's possible that the scratch is still mounted, an
+		// artifact after a hard daemon crash for example. Worth a shot to try detaching it
+		// before retrying the rename.
+		if os.IsPermission(err) {
+			f := filepath.Join(layerPath, "sandbox.vhdx")
+			if _, exists := os.Stat(f); exists == nil {
```
Comment (johnstep) [inline daemon/graphdriver/windows/windows.go]: Kind of strange the call the error `exists`, since the true case is `nil`, but okay, I guess.

**Review by johnstep — APPROVED** [review]

File: daemon/graphdriver/windows/windows.go [hunk 2]
```diff
@@ -331,7 +332,23 @@ func (d *Driver) Remove(id string) error {
...
+				if detach := vhd.DetachVhd(f); detach != nil {
+					return err // the original error from rename
+				}
+			}
+			err = os.Rename(layerPath, tmpLayerPath)
```
Comment (johnstep) [inline daemon/graphdriver/windows/windows.go]: Is it really worth retrying if nothing changed (the detach did not succeed)?

File: daemon/graphdriver/windows/windows.go (hunk 1 above)
Comment (cpuguy83) [reply daemon/graphdriver/windows/windows.go]: Agree this is confusing to read. Does can we just call `DetachVhd` directly instead of checking existence first?

Comment (jhowardmsft) [reply daemon/graphdriver/windows/windows.go]: I'll update to address both of these.

**Comment by jhowardmsft** [comment]
@cpuguy83 @johnstep Updated. Still requires a rebase after #37674 is merged before it will fully pass CI

**Review by swernli — APPROVED** [review]

**Comment by jhowardmsft** [comment]
Rebased. Windows CI and vendor passed (the only path affected here). Rest are completing.

@cpuguy83 are you OK with this now? 

@thaJeztah Could you take a look too please?

File: daemon/graphdriver/windows/windows.go [hunk 3]
```diff
@@ -331,7 +332,19 @@ func (d *Driver) Remove(id string) error {
...
+		// artifact after a hard daemon crash for example. Worth a shot to try detaching it
+		// before retrying the rename.
+		if os.IsPermission(err) {
+			if detachErr := vhd.DetachVhd(filepath.Join(layerPath, "sandbox.vhdx")); detachErr != nil {
+				return err
+			}
+			if err = os.Rename(layerPath, tmpLayerPath); err != nil && !os.IsNotExist(err) {
+				return err
+			}
+		} else {
```
Comment (cpuguy83) [inline daemon/graphdriver/windows/windows.go]: Nit, but a little cleaner if we return early when "!os.IsPermission(err)"

**Review by cpuguy83 — COMMENTED** [review]
Can we add some additional context to the error messages?

File: daemon/graphdriver/windows/windows.go (hunk 3 above)
Comment (jhowardmsft) [reply daemon/graphdriver/windows/windows.go]: Oooh, missed that comment @cpuguy83. Yes, that's a lot cleaner. Updated.

**Comment by cpuguy83** [comment]
Can you just add some extra context to the new errors, e.g. `errors.Wrap(err, "failed to detach VHD")`

**Comment by jhowardmsft** [comment]
> Can you just add some extra context to the new errors, e.g. errors.Wrap(err, "failed to detach VHD")

@cpuguy83 Done.

**Review by cpuguy83 — APPROVED** [review]
LGTM

File: daemon/graphdriver/windows/windows.go [hunk 4]
```diff
@@ -6,7 +6,7 @@ import (
 	"bufio"
 	"bytes"
 	"encoding/json"
-	"errors"
+	//"errors"
```
Comment (cpuguy83) [inline daemon/graphdriver/windows/windows.go]: Oops.

Comment (jhowardmsft) [reply daemon/graphdriver/windows/windows.go]: Doh. Fixing....

Comment (jhowardmsft) [reply daemon/graphdriver/windows/windows.go]: Fixed now. Good catch 👍

**Comment by jhowardmsft** [comment]
@thaJeztah Do you know if this will make it into 18.09 EE? Not sure what the cut-off was.

**Comment by thaJeztah** [comment]
@jhowardmsft looks like it didn't (but will double check when I'm back at my keyboard), I can see I opened a backport request for it, but it slipped of my radar. 

I think a patch release is scheduled, so I'll open backports where needed, so that it will be included in that release

**Comment by jhowardmsft** [comment]
@thaJeztah Thanks. Kind of an important one as I know it fixes multiple production issues I've had to debug.

**Comment by drnybble** [comment]
Still seeing this with 19.03.2 on a clean Windows 2016 VM created from ISO image and fully patched.

driver "windowsfilter" failed to remove root filesystem: hcsshim::GetComputeSystems: Access is denied.

**Comment by thaJeztah** [comment]
@drnybble that error message looks slightly different than the one mentioned here; perhaps it's a different issue; could you open a new ticket? (and include a link to this PR and the related issue https://github.com/moby/moby/issues/36218 to make it easier to find)?

**Comment by Bernolt** [comment]
We had the same issue as @drnybble. (We used Unlocker Windows to delete the files)

**Comment by leiwang008** [comment]
I am still facing this problem. I use  the "Docker Desktop" in Windows 10 OS, I built image with "mcr.microsoft.com/windows/servercore:1709", during the build I got the following message
-------------------------------------------------------------------------------------------------
Error removing intermediate container 720292babe10: container 720292babe105f947428d0ca5fd02533277fc8788f9303e0752ee3eadf2b4439: driver "windowsfilter" failed to remove root filesystem: failed to detach VHD: The device is not ready.: rename C:\ProgramData\Docker\windowsfilter\720292babe105f947428d0ca5fd02533277fc8788f9303e0752ee3eadf2b4439 C:\ProgramData\Docker\windowsfilter\720292babe105f947428d0ca5fd02533277fc8788f9303e0752ee3eadf2b4439-removing: Access is denied.
--------------------------------------------------------------------------------------------------

I could not remove the left-behind containers with command "docker container prune --force", after I restarted my computer, I could use that command to delete the left-behind containers.

Below is the information of "Docker" that I am using
---------------------------------------------------------------------
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:36:50 2019
  OS/Arch:          windows/amd64
  Experimental:     true
---------------------------------------------------------------

**Comment by aries1980** [comment]
I have the same issue as https://github.com/moby/moby/pull/37712#issuecomment-603106889 . 

```
PS C:\Windows\system32> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      17763  0
```

aka `/aws/service/ami-windows-latest/Windows_Server-2019-English-Core-ECS_Optimized` 

```
PS C:\Windows\system32> docker version
Client: Mirantis Container Runtime
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        0c38b2d
 Built:             11/12/2020 21:33:08
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Mirantis Container Runtime
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       5b5efb2d49
  Built:            11/12/2020 21:31:44
  OS/Arch:          windows/amd64
  Experimental:     false
```

running the `jenkins/inbound-agent:windowsservercore-ltsc2019` container image.
