### PR TITLE
TestResumableRequestHeaderTooMuchFailures: prepare for Go 1.14 changes

### LINKED ISSUE #40434: registry/resumable: TestResumableRequestHeaderTooMuchFailures fails with Go 1.14 beta1
Fedora Rawhide with Go 1.14 beta1, Docker Engine v19.03.5

```
--- FAIL: TestResumableRequestHeaderTooMuchFailures (0.00s)
    resumablerequestreader_test.go:80: assertion failed: expected error "Get I%27m%20not%20an%20url: unsupported protocol scheme \"\"", got "Get \"I%27m%20not%20an%20url\": unsupported protocol scheme \"\""
time="2020-01-30T01:23:53Z" level=info msg="encountered error during pull and clearing it before resume: An error occurred"
FAIL
```

See golang/go@64cfe9f
and
golang/go#29261

### PR DESCRIPTION
**Pull request by thaJeztah**
fixes https://github.com/moby/moby/issues/40434
relates to https://github.com/moby/moby/pull/40353

Go 1.14 adds quotes around the invalid scheme in the error returned (See golang/go@64cfe9f and golang/go#29261)

Go 1.13:

    Get I%27m%20not%20an%20url: unsupported protocol scheme ""

Go 1.14:

    Get "I%27m%20not%20an%20url": unsupported protocol scheme ""

This patch updates the test to detect both versions of the error

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]
LGTM

File: registry/resumable/resumablerequestreader_test.go [hunk 1]
```diff
@@ -75,9 +75,10 @@ func TestResumableRequestHeaderTooMuchFailures(t *testing.T) {
 	}
 	defer resreq.Close()
 
-	expectedError := `Get I%27m%20not%20an%20url: unsupported protocol scheme ""`
 	read, err := resreq.Read([]byte{})
-	assert.Check(t, is.Error(err, expectedError))
+	assert.Assert(t, err != nil)
+	assert.ErrorContains(t, err, "unsupported protocol scheme")
```
Comment (cpuguy83) [inline registry/resumable/resumablerequestreader_test.go]: Though maybe we should keep this as a check instead of assert.

Comment (thaJeztah) [reply registry/resumable/resumablerequestreader_test.go]: Ah, yes, I can update to `is.ErrorContains()`

Comment (thaJeztah) [reply registry/resumable/resumablerequestreader_test.go]: updated; PTAL

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by tiborvass — APPROVED** [review]
