### PR TITLE
cliconfig: credentials: support getting all auths

### LINKED ISSUE #20830: docker build broken if used with credentials store
`docker build` needs to provide all auth configs to the builder in order to pull from private registries or from images that are private on the docker hub.
Right now the credentials store do not support retrieving all auth configs and the build fails to lookup the registries that have auth configured.

### PR DESCRIPTION
**Pull request by runcom**
Fixes #20830

`docker build` broke after the client credentials store PR because building `FROM` images that are on a registry which requires auth gets you:

```
$ docker --config `pwd` build .               

Sending build context to Docker daemon 3.072 kB
Step 1 : FROM myregistrydomain.com:5001/busybox
Pulling repository myregistrydomain.com:5001/busybox
Error: image busybox not found
```

`myregistrydomain.com:5001/busybox` is on the registry but the registry has auth, credentials aren't sent to the registry because the credentials will send only an empty config.json (the one configured with --config which just has "credsStore":"something")

after my patch:

```
$ docker -D --config `pwd` build .                    

Sending build context to Docker daemon 3.072 kB
Step 1 : FROM myregistrydomain.com:5001/busybox
latest: Pulling from busybox
Digest: sha256:c431ca187a895d44e25947d55d51fd54709a28f7b75b48e3a68cd2106b72f007
Status: Downloaded newer image for myregistrydomain.com:5001/busybox:latest
 ---> 3240943c9ea3
Step 2 : RUN echo "foobar"
 ---> Using cache
 ---> 24458a2b10cc
Successfully built 24458a2b10cc
```

Signed-off-by: Antonio Murdaca runcom@redhat.com

### CODE REVIEW

File: cliconfig/credentials/native_store.go [hunk 1]
```diff
@@ -35,8 +35,9 @@ type credentialsRequest struct {
 // credentialsGetResponse is the information serialized from a remote store
 // when the plugin sends requests to get the user credentials.
 type credentialsGetResponse struct {
-	Username string
-	Password string
+	ServerURL string
```
Comment (runcom) [inline cliconfig/credentials/native_store.go]: I had to store this in the response so I can retrieve them all

**Comment by calavera** [comment]
This looks very scary, tbh, and hard to do correctly. There is no way to "get all" credentials from native stores, and I'd argue that it's even a potential security vulnerability.

**Comment by calavera** [comment]
Just a clarification. The fact that you can get the credentials from my mock script doesn't mean that you can do it with the OS X Keychain or Windows Credentials Provider.

**Comment by runcom** [comment]
@calavera isn't `cat $HOME/.docker/config.json` also?

**Comment by runcom** [comment]
> Just a clarification. The fact that you can get the credentials from my mock script doesn't mean that you can do it with the OS X Keychain or Windows Credentials Provider.

I get this of course.

**Comment by runcom** [comment]
Also, I suppose `docker build` is broken also for images on the hub that are private

**Comment by calavera** [comment]
What you can do is to get the list of serverURLS from the file and then run a `get` command per server.

**Comment by runcom** [comment]
> What you can do is to get the list of serverURLS from the file and then run a get command per server.

alright

**Comment by runcom** [comment]
@calavera updated to issue multiple *get* requests to implement the *getAll* functionality - added unit and integration-cli tests and now docker build works as expected. (I removed the design review label but feel free to put it back if you think this is not ready to code review)

**Comment by calavera** [comment]
LGTM but there is a test failing:

```
16:08:20 FAIL: docker_cli_build_test.go:6593: DockerRegistryAuthSuite.TestBuildWithExternalAuth
```

I don't even know how it passed after #20565 was merged :pensive:

File: integration-cli/docker_cli_build_test.go [hunk 2]
```diff
@@ -6589,3 +6589,46 @@ func (s *DockerRegistryAuthSuite) TestBuildFromAuthenticatedRegistry(c *check.C)
...
+	configPath := filepath.Join(tmp, "config.json")
+	err = ioutil.WriteFile(configPath, []byte(externalAuthConfig), 0644)
+	c.Assert(err, checker.IsNil)
+
+	dockerCmd(c, "--config", tmp, "login", "-u", s.reg.username, "-p", s.reg.password, "-e", s.reg.email, privateRegistryURL)
+
+	b, err := ioutil.ReadFile(configPath)
+	c.Assert(err, checker.IsNil)
+	c.Assert(string(b), checker.Not(checker.Contains), "\"auth\":")
+	c.Assert(string(b), checker.Contains, "email")
```
Comment (calavera) [inline integration-cli/docker_cli_build_test.go]: email is not mandatory anymore, we should not check it.

Comment (runcom) [inline integration-cli/docker_cli_build_test.go]: copy/pasted from pull_local test - but this is actually checking something which is now broken, I guess it won't hurt to leave it cause I explicitly logged in with the email. I'll fix the bug

Comment (runcom) [inline integration-cli/docker_cli_build_test.go]: oh right, I see I'll remove it, doh

Comment (runcom) [inline integration-cli/docker_cli_build_test.go]: fixed

**Comment by runcom** [comment]
fixed

**Comment by calavera** [comment]
:raised_hands:

**Comment by runcom** [comment]
ping @cpuguy83 @vdemeester

**Comment by tiborvass** [comment]
This is really bad that we have to do this :( Since we already have a hack for docker content trust to read the `FROM` line before sending it to the server, can't we do something similar and send only those auths?

**Comment by runcom** [comment]
> Since we already have a hack for docker content trust to read the FROM line before sending it to the server, can't we do something similar and send only the auths associated with that image?

can we rather fix the original issue instead of introducing another hack? (I haven't seen it though)
otherwise, I still prefer this approach

**Comment by runcom** [comment]
@tiborvass this https://github.com/docker/docker/blob/master/api/client/build.go#L318 ?

**Comment by runcom** [comment]
I'm ok with doing something like that to just resolve the correct auth config. @calavera thoughts?

**Comment by tiborvass** [comment]
@runcom fixing the original issue is client side builder.

**Comment by tiborvass** [comment]
@runcom wait how did we handle this before the `credentials` PR? We would just send the whole auth in dockercfg to the daemon?

**Comment by runcom** [comment]
> @runcom wait how did we handle this before the credentials PR? We would just send the whole auth in dockercfg to the daemon?

correct

**Comment by runcom** [comment]
I'm reworking the patch to remove `GetAll` from the interface since it's only needed for build (which will somehow have a way to resolve just the auth config needed for the FROM image)

**Comment by calavera** [comment]
TBH, I rather solve the issue, like @runcom than changing the design. Let's open an issue to discuss the design if we want to, but not hold bugs in the code because we don't like how our past selves designed it.

**Comment by calavera** [comment]
this change LGTM.

**Comment by vdemeester** [comment]
LGTM 🐭
@calavera creating the issue ?

**Comment by runcom** [comment]
@calavera you're right, but @tiborvass and I would rather avoid adding `GetAll` to the interface (even if this code it's not yet released) so he thought we could have the `GetAll` method just as a utility functions in utils (nothing huge will change from what I've already implemented here and we won't clutter the interface). If you think this can be merged as is I'd make a follow up PR to remove that method from the interface.

**Comment by calavera** [comment]
I think having `GetAll` in the interface makes sense.

**Comment by tiborvass** [comment]
Fair enough

**Comment by runcom** [comment]
alright

**Comment by runcom** [comment]
this should be ready to merge then
