### PR TITLE
Correct CPU usage calculation in presence of offline CPUs and newer Linux

### LINKED ISSUE #28941: docker stats CPU usage greater than 100% times number of cores on Azure VM
**Description**

I have an Azure VM with 2 cores. From my understanding, the CPU % returned by docker stats can be greater than 100% if multiple cores are used. So, this should max out at 200% for this VM. However, I get results like this with CPU % greater than 1000%:

```
CONTAINER           CPU %               MEM USAGE / LIMIT       MEM %               NET I/O               BLOCK I/O             PIDS
545d4c69028f        3.54%               94.39 MiB / 6.803 GiB   1.35%               3.36 MB / 1.442 MB    1.565 MB / 5.673 MB   6
008893e3f70c        625.00%             191.3 MiB / 6.803 GiB   2.75%               0 B / 0 B             0 B / 24.58 kB        35
f49c94dc4567        0.10%               46.85 MiB / 6.803 GiB   0.67%               2.614 MB / 5.01 MB    61.44 kB / 0 B        31
08415d81c355        0.00%               28.76 MiB / 6.803 GiB   0.41%               619.1 kB / 3.701 MB   0 B / 0 B             11
03f54d35a5f8        1.04%               136.5 MiB / 6.803 GiB   1.96%               83.94 MB / 7.721 MB   0 B / 0 B             22
f92faa7321d8        0.15%               19.29 MiB / 6.803 GiB   0.28%               552.5 kB / 758.6 kB   0 B / 2.798 MB        7
2f4a27cc3e44        0.07%               303.8 MiB / 6.803 GiB   4.36%               32.52 MB / 20.27 MB   2.195 MB / 0 B        11
ac96bc45044a        0.00%               19.34 MiB / 6.803 GiB   0.28%               37.28 kB / 12.76 kB   0 B / 3.633 MB        7
7c1a45e92f52        2.20%               356.9 MiB / 6.803 GiB   5.12%               86.36 MB / 156.2 MB   806.9 kB / 0 B        16
0bc4f319b721        14.98%              101.8 MiB / 6.803 GiB   1.46%               138.1 MB / 64.33 MB   0 B / 73.74 MB        75
66aa24598d27        2269.46%            1.269 GiB / 6.803 GiB   18.65%   
```

**Steps to reproduce the issue:**
1. Provision an Ubuntu VM in Azure with 2 cores
2. Install Docker and start some containers -- one of the offending containers above is GitLab
3. Run docker stats

**Describe the results you received:**
CPU percent > 200% on 2 core machine

**Describe the results you expected:**
CPU percent should max at 100 times the number of cores (200%)

**Additional information you deem important (e.g. issue happens only occasionally):**
```
$ grep -c ^processor /proc/cpuinfo
2
```

However, `lshw` shows more than 50 disabled processors and I'm wondering if this is skewing the results.

**Output of `docker version`:**

```
root@server:~# docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Mon, 10 Oct 2016 21:38:17 +1300
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Mon, 10 Oct 2016 21:38:17 +1300
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
root@server:~# docker info
Containers: 13
 Running: 13
 Paused: 0
 Stopped: 0
Images: 56
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 136
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null overlay host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.8.0-26-generic
Operating System: Ubuntu 16.10
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 6.803 GiB
Name: david
ID: ABLT:GB2P:N76B:2EDT:CD6M:VWFY:QI6B:LQND:W55P:TLM3:PZGD:523C
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Azure Standard DS2 v2 (2 cores, 7 GB memory)

### PR DESCRIPTION
**Pull request by ijc**
In https://github.com/torvalds/linux/commit/5ca3726 (released in v4.7-rc1) the
content of the `cpuacct.usage_percpu` file in sysfs was changed to include both
online and offline cpus. This broke the arithmetic in the stats helpers used by
`docker stats`, since it was using the length of the PerCPUUsage array as a
proxy for the number of online CPUs.

Add current number of online CPUs to types.StatsJSON and use it in the
calculation.

Keep a fallback to `len(v.CPUStats.CPUUsage.PercpuUsage)` so this code
continues to work when talking to an older daemon. An old client talking to a
new daemon will ignore the new field and behave as before.

Fixes #28941.

Signed-off-by: Ian Campbell <ian.campbell@docker.com>

**- What I did**

Corrected `docker stats` output for %age CPU used in the presence of offline CPUs.

**- How I did it**

Updated the `types.CPUStats` struct to include number of currently online CPUs (from `sysconf(_SC_NPROCESSORS_ONLN`) and used that in the stats code to correctly calculate percentage CPU usage.

**- How to verify it**

Install a system with more possible CPUs than online CPUs (e.g. in a VM with max vcpus set to 4 but actual set to 2).

This command should show 100% CPU usage:
```
docker run -d --rm --name spin debian:latest timeout 30s bash -c 'while : ; do : ; done' ; docker stats
```

This one should show 200% CPU usage:
```
docker run -d --rm --name spin debian:latest timeout 30s bash -c 'while : ; do : ; done & while : ; do : ; done' ; docker stats
```

Previous in the 2/4 CPUs present scenario they would incorrectly report 200% and 400% respectively.

**- Description for the changelog**

Correct CPU usage accounting with Linux v4.7-rc1 onwards when some CPUs are offline.

**- A picture of a cute animal (not mandatory but encouraged)**

David Coverdale, Whitesnake
(By [Samboob at English Wikipedia, CC BY-SA 3.0](https://commons.wikimedia.org/w/index.php?curid=15517420))

### CODE REVIEW

**Comment by ijc25** [comment]
Could possibly also have done this by counting the number of `cpu[0-9]+` lines in `/proc/stat` and avoided some cgo, but despite the [comment above `getSystemCPUUsage`](https://github.com/docker/docker/blob/master/daemon/stats/collector_unix.go#L26..L29) saying the file is defined by POSIX I couldn't find any sign of it in any spec so I couldn't confirm it wasn't a Linux specific extension (which I strongly suspect it is). In any case `sysconf` has much less overhead.

I discounted [`runtime.NumCPU`](https://golang.org/pkg/runtime/#NumCPU) since it is cached at start of day and so doesn't react to hotplug.

File: cli/command/container/stats_helpers.go [hunk 1]
```diff
@@ -178,10 +178,14 @@ func calculateCPUPercentUnix(previousCPU, previousSystem uint64, v *types.StatsJ
 		cpuDelta = float64(v.CPUStats.CPUUsage.TotalUsage) - float64(previousCPU)
 		// calculate the change for the entire system between readings
 		systemDelta = float64(v.CPUStats.SystemUsage) - float64(previousSystem)
+		onlineCPUs = float64(v.CPUStats.OnlineCPUs)
 	)
 
+	if onlineCPUs == 0.0 {
+		onlineCPUs = float64(len(v.CPUStats.CPUUsage.PercpuUsage))
```
Comment (thaJeztah) [inline cli/command/container/stats_helpers.go]: To prevent having to update the API; would it be an option to add dummy entries daemon-side, (based on the amount of online cpus?)

Comment (ijc25) [inline cli/command/container/stats_helpers.go]: This code is on the client side and is to handle the case where the client is talking to an older daemon, so making changes to the daemon side is by definition not an option.

Or perhaps that's not what you meant? I'm not entirely sure where you are coming from, but it seems likely to be relevant to mention that the issue is that the kernel (and hence the daemon) are providing too many entries after the Linux change not too few so adding more dummy entries wouldn't help.

Comment (thaJeztah) [inline cli/command/container/stats_helpers.go]: oh, hm, the opposite then, sorry; can we make the daemon only return entries for online CPUs? Or is that gonna be very hairy?

Comment (ijc25) [inline cli/command/container/stats_helpers.go]: Pretty hairy unfortunately. Mostly down to the first paragraph of https://github.com/docker/docker/pull/31579#issuecomment-284477640. Or we could scan sysfs and try and work it out, but that would mean opening "number of possible cpus" files in sysfs for every stats iteration and is Linux specific.

**Comment by ijc25** [comment]
Force pushed to run `gofmt` to placate janky.

File: cli/command/container/stats_helpers.go (hunk 1 above)
Comment (thaJeztah) [inline cli/command/container/stats_helpers.go]: 😞 alright, guess we don't have much choice :smile:

**Comment by justincormack** [comment]
We don't currently support hotplug CPUs in any meaningful way, due to cgroups limitations, but sysconf does seem better anyway.

**Review by justincormack — APPROVED** [review]

**Comment by justincormack** [comment]
I have marked this for 17.03.1 as it is affecting a fair number of users as distros update their kernels.

**Comment by justincormack** [comment]
P, Z CI were restarted, can be ignored.

**Comment by thaJeztah** [comment]
@ijc25 can you;

- Add the new field to https://github.com/docker/docker/blob/master/api/swagger.yaml
- Add a line to https://github.com/docker/docker/blob/master/docs/api/version-history.md

**Comment by ijc25** [comment]
@thaJeztah for `api/version-history.md` I'm supposed to add it to the existing v1.27 list, rather than start v1.28, right?

**Comment by ijc25** [comment]
Updated according to my supposition in https://github.com/docker/docker/pull/31579#issuecomment-285423882. There was no schema in the swagger file for this call, but I added the fields to the example and some words about compat in both places.

**Comment by justincormack** [comment]
ping @thaJeztah

**Comment by justincormack** [comment]
cc @vdemeester

**Review by thaJeztah — APPROVED** [review]
LGTM

File: daemon/stats/collector_unix.go [hunk 2]
```diff
@@ -11,6 +11,11 @@ import (
 	"github.com/opencontainers/runc/libcontainer/system"
 )
 
+/*
```
Comment (vdemeester) [inline daemon/stats/collector_unix.go]: Would it be possible to do this in `go` only ? If not, would we extract this (i.e. `getNumberOnlineCPUs`) into another package, probably in `pkg` instead ?

Comment (justincormack) [inline daemon/stats/collector_unix.go]: Not possibly in Go, see discussion on PR.

Comment (ijc25) [inline daemon/stats/collector_unix.go]: It is sadly not possible to do this in go only, `sysconf` isn't exposed. I discussed some other alternative options in https://github.com/docker/docker/pull/31579#issuecomment-284477640 but they are all IMHO worse.

I've no opinion on `pkg` vs not, but perhaps we could leave that refactoring until after 17.04?

**Review by justincormack — APPROVED** [review]

**Review by vdemeester — APPROVED** [review]
LGTM 🐮

**Comment by thaJeztah** [comment]
cherry-picked into 17.03.1 through https://github.com/docker/docker/pull/31802
