### PR TITLE
Fix issue in disconnecting a container from network

### LINKED ISSUE #26220: can't disconnect container from default network before starting it
**Output of `docker version`:**

```
master / bdae52a23dd69be29f0d5b871ee791180329e458
```

**Output of `docker info`:**

```
n/a
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Steps to reproduce the issue:**

1. docker create --name tmp -it alpine sh
2. docker network disconnect $(docker network ls | grep bridge | awk '{print $1}') tmp

**Describe the results you received:**
```
Error response from daemon: container 56f1cef3d80ede48d61ffbb90554055ea3255c98475e085ab12337251108d503 is not connected to the network 72787bea99a0
```

**Describe the results you expected:**
success

**Additional information you deem important (e.g. issue happens only occasionally):**

### PR DESCRIPTION
**Pull request by yongtang**
**\- What I did**

This fix tries to address the issue raised in #26220 where disconnecting a container from network does not work if the network id (instead of network name) has been specified.

The issue was that internally when trying to disconnecting a contaienr fromt the network, the originally passed network name or id has been used.

**\- How I did it**

This fix uses the resolved network name (e.g., `bridge`).

**\- How to verify it**

An integration test has been added to cover the changes.

**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**

This fix fixes #26220.

Signed-off-by: Yong Tang yong.tang.github@outlook.com

### CODE REVIEW

File: daemon/container_operations_unix.go [hunk 1]
```diff
@@ -129,10 +129,10 @@ func (daemon *Daemon) DisconnectFromNetwork(container *container.Container, netw
 		if container.RemovalInProgress || container.Dead {
 			return errRemovalContainer(container.ID)
 		}
-		if _, ok := container.NetworkSettings.Networks[networkName]; !ok {
-			return fmt.Errorf("container %s is not connected to the network %s", container.ID, networkName)
+		if _, ok := container.NetworkSettings.Networks[n.Name()]; !ok {
```
Comment (mavenugo) [inline daemon/container_operations_unix.go]: This will fail in the case where the Network (`n`) is nil. This is a recent fix to support a case of disconnecting a container from a network even if the network is not in the DB.

**Comment by yongtang** [comment]
Thanks @mavenugo for pointing out the issue. The pull request has been updated to address the case. Please take a look and let me know if there are any issues.

File: daemon/container_operations_unix.go [hunk 2]
```diff
@@ -129,6 +129,11 @@ func (daemon *Daemon) DisconnectFromNetwork(container *container.Container, netw
 		if container.RemovalInProgress || container.Dead {
 			return errRemovalContainer(container.ID)
 		}
+		// In case networkName is resolved we will use n.Name()
+		// this will cover the case where network id is passed.
+		if err == nil && n != nil && n.Name() != "" {
```
Comment (mavenugo) [inline daemon/container_operations_unix.go]: I guess you can remove `n.Name() != ""`. Otherwise LGTM.

**Comment by yongtang** [comment]
Thanks @mavenugo. The pull request has been updated. Please let me know if there are any other issues.

**Comment by vdemeester** [comment]
LGTM 🐸

**Comment by mavenugo** [comment]
LGTM
