### PR TITLE
Windows: return err instead of panic when convert string to utf16

### LINKED ISSUE #30074: Docker Etwlogs driver causes docker service crash
**Description**

I am running docker with log-driver `etwlogs`. Seems this driver cause docker crash

**Steps to reproduce the issue:**
1.  ```docker run --log-driver etwlogs someimage```

by inspect
```
        "HostConfig": {
            "LogConfig": {
                "Type": "etwlogs",
                "Config": {}
            },
```

2. image writes into stdout/stderr

3. docker service crashed occasionally

**Describe the results you received:**

Found in `panic.log`

```
panic: syscall: string with NUL passed to StringToUTF16

goroutine 6641 [running]:
panic(0x127ada0, 0xc0425f4cc0)
	/usr/local/go/src/runtime/panic.go:500 +0x1af
syscall.StringToUTF16(0xc04226e000, 0x9bf, 0xc04226e000, 0x9bf, 0x9bf)
	/usr/local/go/src/syscall/syscall_windows.go:31 +0xc2
syscall.StringToUTF16Ptr(0xc04226e000, 0x9bf, 0x10)
	/usr/local/go/src/syscall/syscall_windows.go:66 +0x3c
github.com/docker/docker/daemon/logger/etwlogs.callEventWriteString(0xc04226e000, 0x9bf, 0xc04226e000, 0x9bf)
	/go/src/github.com/docker/docker/daemon/logger/etwlogs/etwlogs_windows.go:164 +0x96
github.com/docker/docker/daemon/logger/etwlogs.(*etwLogs).Log(0xc04291ce00, 0xc043165d10, 0xc042c56a20, 0xc042925e00)
	/go/src/github.com/docker/docker/daemon/logger/etwlogs/etwlogs_windows.go:73 +0x154
github.com/docker/docker/daemon/logger.(*Copier).copySrc(0xc04291d080, 0x14c8beb, 0x6, 0x22fc438, 0xc04291ce40)
	/go/src/github.com/docker/docker/daemon/logger/copier.go:88 +0x3de
created by github.com/docker/docker/daemon/logger.(*Copier).Run
	/go/src/github.com/docker/docker/daemon/logger/copier.go:41 +0x11f

```

**Describe the results you expected:**

No Crash

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 3
Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.576.amd64fre.rs1_release_inmarket.161208-2252)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 28 GiB
Name: vme1f7682836
ID: G6NE:BKJN:TETO:LHFW:7STN:T2XA:NE2R:H4Z2:PSAO:R6BB:HNPJ:RGH3
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Azure

### PR DESCRIPTION
**Pull request by tg123**
Signed-off-by: Boshi Lian <farmer1992@gmail.com>

**- What I did**
Fix #30074 

**- How I did it**

change `StringToUTF16Ptr` to `UTF16FromString` which will not panic docker daemon

<https://golang.org/src/syscall/syscall_windows.go>

**- How to verify it**

test with NUL string

**- Description for the changelog**

return err instead of panic when convert string to utf16

**- A picture of a cute animal (not mandatory but encouraged)**

// lamina etuc
🐱

### CODE REVIEW

File: daemon/logger/etwlogs/etwlogs_windows.go [hunk 1]
```diff
@@ -146,7 +146,13 @@ func callEventRegister() error {
 }
 
 func callEventWriteString(message string) error {
-	ret, _, _ := procEventWriteString.Call(uintptr(providerHandle), 0, 0, uintptr(unsafe.Pointer(syscall.StringToUTF16Ptr(message))))
+	utf16message, err := syscall.UTF16FromString(message)
```
Comment (thaJeztah) [inline daemon/logger/etwlogs/etwlogs_windows.go]: Should this be `UTF16PtrFromString`?

Comment (tg123) [inline daemon/logger/etwlogs/etwlogs_windows.go]: I expand `StringToUTF16Ptr` to `UTF16FromString`

the `StringToUTF16Ptr` code can be found in <https://golang.org/src/syscall/syscall_windows.go>

```
func StringToUTF16Ptr(s string) *uint16 { return &StringToUTF16(s)[0] }

func StringToUTF16(s string) []uint16 {
	a, err := UTF16FromString(s)
	if err != nil {
		panic("syscall: string with NUL passed to StringToUTF16")
	}
	return a
}
```

**Review by LK4D4 — APPROVED** [review]
LGTM

**Comment by LK4D4** [comment]
ping @jhowardmsft

**Comment by jhowardmsft** [comment]
LGTM
