### PR TITLE
Windows: Temporarily disable TestBuildLastModified

### LINKED ISSUE #30890: TestBuildLastModified failing consistently on Windows
https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS1/10267/console (https://github.com/docker/docker/pull/30871)
```
00:26:05.567 ----------------------------------------------------------------------
00:26:05.567 FAIL: docker_cli_build_test.go:380: DockerSuite.TestBuildLastModified
00:26:05.567 
00:26:05.567 docker_cli_build_test.go:395:
00:26:05.567     out, _ = dockerCmd(c, "run", name, "ls", "-le", "/file")
00:26:05.567 docker_utils_test.go:247:
00:26:05.567     c.Assert(result, icmd.Matches, icmd.Success)
00:26:05.567 ... result *cmd.Result = &cmd.Result{Cmd:(*exec.Cmd)(0xc04208ec60), ExitCode:1, Error:(*exec.ExitError)(0xc04229a080), Timeout:false, outBuffer:(*cmd.lockedBuffer)(0xc042394e10), errBuffer:(*cmd.lockedBuffer)(0xc042394ea0)} ("\nCommand: d:\\CI\\CI-a82ae5db7\\binary\\docker.exe run testbuildlastmodified ls -le /file\nExitCode: 1, Error: exit status 1\nStdout: \nStderr: BusyBox v1.27.0-FRP-1035-g74163a5 (2017-02-09 08:42:39 GMT) multi-call binary.\n\nUsage: ls [-1AaCxdLHRFplinshrSXvctu] [-w WIDTH] [FILE]...\n\nList directory contents\n\n\t-1\tOne column output\n\t-a\tInclude entries which start with .\n\t-A\tLike -a, but exclude . and ..\n\t-x\tList by lines\n\t-d\tList directory entries instead of contents\n\t-L\tFollow symlinks\n\t-H\tFollow symlinks on command line\n\t-R\tRecurse\n\t-p\tAppend / to dir entries\n\t-F\tAppend indicator (one of */=@|) to entries\n\t-l\tLong listing format\n\t-i\tList inode numbers\n\t-n\tList numeric UIDs and GIDs instead of names\n\t-s\tList allocated blocks\n\t-lc\tList ctime\n\t-lu\tList atime\n\t--full-time\tList full date and time\n\t-h\tHuman readable sizes (1K 243M 2G)\n\t--group-directories-first\n\t-S\tSort by size\n\t-X\tSort by extension\n\t-v\tSort by version\n\t-t\tSort by mtime\n\t-tc\tSort by ctime\n\t-tu\tSort by atime\n\t-r\tReverse sort order\n\t-w N\tFormat N columns wide\n\t--color[={always,never,auto}]\tControl coloring\nC:/busybox/busybox.exe: unknown option -- e\n\n")
00:26:05.569 ... expected cmd.Expected = cmd.Expected{ExitCode:0, Timeout:false, Error:"", Out:"", Err:""}
00:26:05.569 ... 
00:26:05.569 Command: d:\CI\CI-a82ae5db7\binary\docker.exe run testbuildlastmodified ls -le /file
00:26:05.569 ExitCode: 1, Error: exit status 1
00:26:05.569 Stdout: 
00:26:05.569 Stderr: BusyBox v1.27.0-FRP-1035-g74163a5 (2017-02-09 08:42:39 GMT) multi-call binary.
00:26:05.569 
00:26:05.569 Usage: ls [-1AaCxdLHRFplinshrSXvctu] [-w WIDTH] [FILE]...
00:26:05.569 
00:26:05.569 List directory contents
00:26:05.569 
00:26:05.569 	-1	One column output
00:26:05.569 	-a	Include entries which start with .
00:26:05.569 	-A	Like -a, but exclude . and ..
00:26:05.569 	-x	List by lines
00:26:05.569 	-d	List directory entries instead of contents
00:26:05.569 	-L	Follow symlinks
00:26:05.569 	-H	Follow symlinks on command line
00:26:05.570 	-R	Recurse
00:26:05.570 	-p	Append / to dir entries
00:26:05.570 	-F	Append indicator (one of */=@|) to entries
00:26:05.570 	-l	Long listing format
00:26:05.570 	-i	List inode numbers
00:26:05.570 	-n	List numeric UIDs and GIDs instead of names
00:26:05.570 	-s	List allocated blocks
00:26:05.570 	-lc	List ctime
00:26:05.570 	-lu	List atime
00:26:05.570 	--full-time	List full date and time
00:26:05.570 	-h	Human readable sizes (1K 243M 2G)
00:26:05.570 	--group-directories-first
00:26:05.570 	-S	Sort by size
00:26:05.570 	-X	Sort by extension
00:26:05.570 	-v	Sort by version
00:26:05.570 	-t	Sort by mtime
00:26:05.570 	-tc	Sort by ctime
00:26:05.570 	-tu	Sort by atime
00:26:05.570 	-r	Reverse sort order
00:26:05.570 	-w N	Format N columns wide
00:26:05.570 	--color[={always,never,auto}]	Control coloring
00:26:05.570 C:/busybox/busybox.exe: unknown option -- e
00:26:05.570 
00:26:05.570 
00:26:05.570 Failures:
00:26:05.570 ExitCode was 1 expected 0
00:26:05.570 Expected no error
00:26:05.570 
00:26:05.570 
00:26:05.672 
00:26:05.672 ----------------------------------------------------------------------
```

Something seems changed in the Windows port of busybox?

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard <jhoward@microsoft.com>

@thaJeztah @AkihiroSuda Temporarily fixes #30890 - Looks like something has changed in the master busybox image so that -e is no longer working on ls.

### CODE REVIEW

File: integration-cli/docker_cli_build_test.go [hunk 1]
```diff
@@ -2579,7 +2583,7 @@ USER 1042:1043
 RUN [ "$(id -u):$(id -g)/$(id -un):$(id -gn)/$(id -G):$(id -Gn)" = '1042:1043/1042:1043/1043:1043' ]`))
 }
 
-// FIXME(vdemeester) rename this test (and probably "merge" it with the one below TestBuildEnvUsage2)
+// FIXME(vdemeester) rename this test (and probably "merge" it with the one below TestBuildEnvUsage2)
```
Comment (thaJeztah) [inline integration-cli/docker_cli_build_test.go]: 🤔 ?

**Review by thaJeztah — APPROVED** [review]
other than the unrelated whitespace changes, LGTM :smile:

**Comment by AkihiroSuda** [comment]
How about pinning the busybox image to an older version instead?

If we need to use the latest busybox, this PR SGTM.

**Comment by jhowardmsft** [comment]
I don't believe the hosting site holds prior versions...

The white spaces are a result of gofmt - not sure how they were missed before....

**Comment by thaJeztah** [comment]
> The white spaces are a result of gofmt - not sure how they were missed before.... (as in I think it's right)

Ah, alright. I think `gofmt` check is not performed on test files, so that would explain 👍

**Comment by AkihiroSuda** [comment]
OK, LGTM

**Comment by jhowardmsft** [comment]
Moving to merge status for when CI completes successfully
