### PR TITLE
c8d/load: Handle compressed archives

### LINKED ISSUE #46600: docker load fails with compressed image with containerd-snapshotter
### Description

docker load fails with compressed image with containerd-snapshotter.

### Reproduce

```
$ cat /etc/docker/daemon.json 
{
	"features": {
		"containerd-snapshotter": true
	}
}
```

then, run:

```
docker pull alpine
docker save alpine | gzip > alpine.tar.gz
docker rmi alpine
docker load -i alpine.tar.gz
```

### Expected behavior

alpine image should be loaded

### docker version

```bash
Client: Docker Engine - Community
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:32:16 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:32:16 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 7
 Server Version: 24.0.6
 Storage Driver: overlayfs
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 6.1.0-0.deb11.11-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.05GiB
 Name: ______
 ID: 33WU:U6IN:FCMC:4KP7:EOTO:RTSY:XW2B:ZRAK:A5VM:VCKQ:3DNL:F7HJ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

Error is shown: `archive/tar: invalid tar header`

### PR DESCRIPTION
**Pull request by vvoland**
- Closes: https://github.com/moby/moby/issues/46600

Allow to load images from compressed tars.

**- How to verify it**
```diff
$ docker pull alpine
Using default tag: latest
latest: Pulling from library/alpine
579b34f0a95b: Download complete
Digest: sha256:eece025e432126ce23f223450a0326fbebde39cdf496a85d8c016293fc851978
Status: Downloaded newer image for alpine:latest
docker.io/library/alpine:latest

$ docker save alpine > alpine.tar
$ gzip <alpine.tar >alpine.tar.gz

$ docker rmi alpine
Untagged: alpine:latest
Deleted: sha256:eece025e432126ce23f223450a0326fbebde39cdf496a85d8c016293fc85197

$ docker load -i alpine.tar
Loaded image: alpine

$ docker load -i alpine.tar.gz
-archive/tar: invalid tar header
+Loaded image: alpine

```

**- Description for the changelog**
```release-note
- containerd image store: Fix `docker load` not being able to load images from compressed tar archives.
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by rumpl — APPROVED** [review]

File: daemon/containerd/image_exporter.go [hunk 1]
```diff
@@ -148,6 +149,12 @@ func leaseContent(ctx context.Context, store content.Store, leasesManager leases
 // complement of ExportImage.  The input stream is an uncompressed tar
 // ball containing images and metadata.
 func (i *ImageService) LoadImage(ctx context.Context, inTar io.ReadCloser, outStream io.Writer, quiet bool) error {
+	decompressed, err := dockerarchive.DecompressStream(inTar)
```
Comment (AkihiroSuda) [inline daemon/containerd/image_exporter.go:152]: Any reason not to use https://pkg.go.dev/github.com/containerd/containerd@v1.7.7/archive/compression#DecompressStream ?

Comment (vvoland) [reply daemon/containerd/image_exporter.go:152]: The only reason I can see is that this implementation doesn't support bzip2 and xz whereas Moby's does.

**Review by laurazard — APPROVED** [review]
LGTM

**Review by AkihiroSuda — APPROVED** [review]
