### PR TITLE
skip container ID remapping, if the file is overlayfs whiteout.

### LINKED ISSUE #35709: [Build] File deletion does not work in userns enabled engine
**Description**

In docker with userns-remap option activated, removing a file from a previous layer is not taken into account. In syslog, we find errors like:

```
Can't add file /var/lib/docker/500000.500000/overlay2/xxxx/diff/path/to/file to tar: Host ID 0 cannot be mapped to a container ID
```

**Steps to reproduce the issue:**
1. Run docker with `--user-remap=default`
2. Use the Dockerfile
```
FROM busybox

RUN echo "foo" > /bar

RUN rm -f /bar

RUN ls -la /bar
```
3. `docker build --cache .`

**Describe the results you received:**

You will see the last step still shows /bar exists

In syslog, you find a:
```
msg="Can't add file /var/lib/docker/500000.500000/overlay2/ae3d56600bb897918129265a43f0b54a7693d190ce1a4d8ab333787673c41dd0/diff/bar to tar: Host ID 0 cannot be mapped to a container ID"
```

**Describe the results you expected:**

/bar should not be visible in the last layer

**Additional information you deem important (e.g. issue happens only occasionally):**

Issue is reproductible

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:48 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 47
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
 userns
Kernel Version: 4.9.0-4-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 492.4MiB
Name: stretch
ID: HJSC:OKNJ:FNOI:2G52:OYNL:KULV:C3P5:W5YC:Y4NX:LH2C:QZVB:SQCN
Docker Root Dir: /var/lib/docker/500000.500000
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Reproductible on a vagrant box running Debian 9

### PR DESCRIPTION
**Pull request by keyolk**
fixes #35709 

Signed-off-by: Chanhun Jeong <chanhun.jeong@navercorp.com>

**- What I did**
during docker image build,
do check whether the file in intermediate container is overlayfs whiteout (0/0 device).
if then, skip uid/gid remapping.

**- How I did it**
using AUFS, dockerd skips its whiteout file,
but not for overlayfs.

**- How to verify it**
with userns, overlay2 storage driver,
do below,
```
docker build -f - . <<<$'FROM centos\nRUN ls -lad /etc/se*; rm -v /etc/services\nRUN ls -lad /etc/se*'
```
then check whether the file /etc/services is removed.

**- Description for the changelog**
skip container ID remapping, if the file is overlayfs whiteout.

**- A picture of a cute animal (not mandatory but encouraged)**
: - ()

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @estesp @dmcgowan @kolyshkin PTAL

**Review by estesp — APPROVED** [review]
LGTM

**Comment by keyolk** [comment]
If I wanna do change my email here.
Do I have to re-sign and send PR again ?

File: pkg/archive/archive.go [hunk 1]
```diff
@@ -456,10 +456,19 @@ func (ta *tarAppender) addTarFile(path, name string) error {
 		}
 	}
 
+	//check whether the file is overlayfs whiteout
+	//if yes, skip re-mapping container ID mappings.
+	isOverlayWhiteout := false
+	if fi.Mode()&os.ModeCharDevice != 0 && hdr.Devmajor == 0 && hdr.Devminor == 0 {
+		isOverlayWhiteout = true
```
Comment (yongtang) [inline pkg/archive/archive.go]: nit: looks like this line might be changed to:
```
isOverlayWhiteout := fi.Mode()&os.ModeCharDevice != 0 && hdr.Devmajor == 0 && hdr.Devminor == 0
```
?

**Review by yongtang — APPROVED** [review]
One nit, LGTM overall.

**Review by yongtang — APPROVED** [review]
Looks like the comment has been addressed and all tests passed, LGTM. Thanks!
