### PR TITLE
daemon: fix hanging attaches on initial start failures

### LINKED ISSUE #9797: If container failed on start, then there will be goroutine leak
example:
```
nc -l -p 6379
docker run -p 6379:6379 busybox true
```
After each run we will have +6 goroutines - this is attach jobs which was called before start by docker client. This goroutines never dies, even if you remove container. I noted that this issue appears only when failure is before actual process start.

### PR DESCRIPTION
**Pull request by LK4D4**
Attach can hang forever if there is no data to send. This PR adds notification
of Attach goroutine about container stop.
Fix #9797

### CODE REVIEW

File: container/container.go [hunk 1]
```diff
@@ -345,12 +349,13 @@ func (container *Container) GetExecIDs() []string {
...
 func (container *Container) Attach(stdin io.ReadCloser, stdout io.Writer, stderr io.Writer, keys []byte) chan error {
-	return AttachStreams(container.StreamConfig, container.Config.OpenStdin, container.Config.StdinOnce, container.Config.Tty, stdin, stdout, stderr, keys)
+	ctx := container.InitAttachContext()
+	return AttachStreams(ctx, container.StreamConfig, container.Config.OpenStdin, container.Config.StdinOnce, container.Config.Tty, stdin, stdout, stderr, keys)
 }
 
 // AttachStreams connects streams to a TTY.
 // Used by exec too. Should this move somewhere else?
-func AttachStreams(streamConfig *runconfig.StreamConfig, openStdin, stdinOnce, tty bool, stdin io.ReadCloser, stdout io.Writer, stderr io.Writer, keys []byte) chan error {
+func AttachStreams(ctx context.Context, streamConfig *runconfig.StreamConfig, openStdin, stdinOnce, tty bool, stdin io.ReadCloser, stdout io.Writer, stderr io.Writer, keys []byte) chan error {
```
Comment (aaronlehmann) [inline container/container.go]: There are multiple nested closures in this function so it's long and a bit awkward. Do you think it would make sense to split out `attachStream`, and maybe the first goroutine, into separate functions? I am not very familiar with this code so I'm not sure this is a good suggestion.

Comment (LK4D4) [inline container/container.go]: I'll try, maybe it'll be cleaner.

**Comment by aaronlehmann** [comment]
I wonder if there could be a unified `select` statement for the streams inside the final goroutine (`promise.Go` at the end of the function). Something like:

```go
		select {
		case <-stdinDone:
			cleanup()
                case <-stdoutDone:
			cleanup()
		case <-stderrDone:
			cleanup()
		case err := <-errors:
			return err
		case <-ctx.Done():
			cleanup()
		}
		wg.Wait() // might be possible to avoid the wait group
```

Again, I'm not familiar enough with the code to know for sure if this is the right approach, but it seems like it could simplify things if it's possible.

**Comment by thaJeztah** [comment]
WindowsTP4 failure is genuine https://jenkins.dockerproject.org/job/Docker-PRs-WoW-TP4/2308/console

```
03:36:09 
03:36:09 ----------------------------------------------------------------------
03:36:09 FAIL: docker_cli_run_test.go:4203: DockerSuite.TestRunAttachFailedNoLeak
03:36:09 
03:36:09 docker_cli_run_test.go:4217:
03:36:09     dockerCmd(c, "run", "-d", "--name=test", "-p", "8000:8000", "busybox", "top")
03:36:09 github.com/docker/docker/integration-cli/_test/_obj_test/docker_utils.go:634:
03:36:09     ...open github.com/docker/docker/integration-cli/_test/_obj_test/docker_utils.go: The system cannot find the path specified.
03:36:09 ... Error: Cannot use 'busybox top' in tests on Windows. Use runSleepingContainer()
03:36:22 ----------------------------------------------------------------------
```

File: integration-cli/docker_cli_run_test.go [hunk 2]
```diff
@@ -4187,3 +4188,41 @@ func (s *DockerSuite) TestRunNamedVolumesFromNotRemoved(c *check.C) {
...
+		var i info
+		status, b, err := sockRequest("GET", "/info", nil)
+		c.Assert(err, checker.IsNil)
+		c.Assert(status, checker.Equals, 200)
+		c.Assert(json.Unmarshal(b, &i), checker.IsNil)
+		return i.NGoroutines
+	}
+	nroutines := getNGoroutines()
+
+	dockerCmd(c, "run", "-d", "--name=test", "-p", "8000:8000", "busybox", "top")
```
Comment (thaJeztah) [inline integration-cli/docker_cli_run_test.go]: this should use `runSleepingContainer(.....` to make it work on Windows

**Comment by LK4D4** [comment]
@aaronlehmann we use WaitGroup to wait for all goroutines to finish for collecting all errors. I agree that it's possible to get rid of wg, but I reluctant to do it in this PR.
However, I tried to get rid of some closures, pls take a look.

**Comment by aaronlehmann** [comment]
Thanks, I think this is much better.

LGTM if the Windows test failure is resolved.

**Comment by LK4D4** [comment]
I think TP4 failure is unrelated, but I changed test container call to `runSleepContainer`

**Comment by LK4D4** [comment]
```
19:57:28 
19:57:28 docker_cli_run_test.go:4243:
19:57:28     c.Assert(strings.Contains(string(out), "port is already allocated"), checker.Equals, true, check.Commentf("Output: %s", out))
19:57:28 ... obtained bool = false
19:57:28 ... expected bool = true
19:57:28 ... Output: D:\CI\CI-dcd1a32\binary\docker.exe: Error response from daemon: Cannot start container 7435143eeb41b94e782eafe9103ea07b0c19e5e0009abb0e82da4a8e3fc2095e: HCSShim::CreateComputeSystem failed in Win32: You were not connected because a duplicate name exists on the network. If joining a domain, go to System in Control Panel to change the computer name and try again. If joining a workgroup, choose another workgroup name. (0x34) id=7435143eeb41b94e782eafe9103ea07b0c19e5e0009abb0e82da4a8e3fc2095e configuration={"SystemType":"Container","Name":"7435143eeb41b94e782eafe9103ea07b0c19e5e0009abb0e82da4a8e3fc2095e","Owner":"docker","IsDummy":false,"VolumePath":"\\\\?\\Volume{4ae39164-e630-11e5-a382-8131a189438d}","Devices":[{"DeviceType":"Network","Connection":{"NetworkName":"Virtual Switch","EnableNat":false,"Nat":{"Name":"ContainerNAT","PortBindings":[{"Protocol":"TCP","InternalPort":8000,"ExternalPort":8000}]}},"Settings":null}],"IgnoreFlushesDuringBoot":true,"LayerFolderPath":"D:\\CI\\CI-dcd1a32\\daemon\\graph\\windowsfilter\\7435143eeb41b94e782eafe9103ea07b0c19e5e0009abb0e82da4a8e3fc2095e","Layers":[{"ID":"9feaf445-62bf-5e30-9aa7-6d57970eb604","Path":"D:\\CI\\CI-dcd1a32\\daemon\\graph\\windowsfilter\\3e1aca36f1ba52aefa1ac18607ca8ed4f3f1057c23ee74fdd3b51373972b40a6"},{"ID":"3dcabd41-eb99-58c7-bae8-a2cfa3ed697d","Path":"D:\\CI\\CI-dcd1a32\\daemon\\graph\\windowsfilter\\bbf5fb2793724fea09d6e7c6ae56986d8740bc529a7c63d0b782c257045cb855"},{"ID":"4624eab0-61f6-5ed8-b4a9-486a34cc638f","Path":"D:\\CI\\CI-dcd1a32\\daemon\\graph\\windowsfilter\\76cdbbd4d188ec9c8ab14b3e5787f0f89737f87470f01c55962ebe93fc5a498c"},{"ID":"831796c3-87ec-5ece-b777-e96aeae8a87a","Path":"D:\\CI\\CI-dcd1a32\\daemon\\graph\\windowsfilter\\f73aaddaf87d3989db0d20c70f050ab9fa6e8ee834866e48ae2eb34ee134c4dc"},{"ID":"3ae3cedd-0974-5eb8-a175-f3e1bc2f45d0","Path":"D:\\CI\\CI-dcd1a32\\daemon\\graph\\windowsfilter\\79a77b8f1dafa1a1da75f279343b47215e0c1369ff706a5491254141a205cb8d"},{"ID":"84ea5d62-64ed-574d-a0b6-2d19ec831a27","Path":"C:\\ProgramData\\Microsoft\\Windows\\Images\\CN=Microsoft_WindowsServerCore_10.0.10586.0"}],"HostName":"7435143eeb41","MappedDirectories":[],"SandboxPath":"","HvPartition":false}.
```
WAT? I'm going to skip test on windows.

**Comment by LK4D4** [comment]
@jhowardmsft Is that legit error from windows libnetwork implementation?

**Comment by jhowardmsft** [comment]
The libnetwork PR for Windows hasn't been merged. That looks like a common error which a !rebuild should fix

**Comment by LK4D4** [comment]
@jhowardmsft thanks, let's see.

**Comment by LK4D4** [comment]
Seems like get TP4 approval is pretty hard :)

**Comment by jhowardmsft** [comment]
TP=Technical Preview as in things break, known bugs etc. Will restart.

**Comment by thaJeztah** [comment]
Got the same failure again https://jenkins.dockerproject.org/job/Docker-PRs-WoW-TP4/2391/console but don't know if a new `!rebuild` was done since, so I'll start it again

**Comment by LK4D4** [comment]
I changed check for windows too. I think it's valid error for it.

**Comment by thaJeztah** [comment]
ping @jhowardmsft PTAL (it's greeeeen now :green_heart: )

**Comment by calavera** [comment]
LGTM

> LGTM if the Windows test failure is resolved.

Merging :tada:
