### PR TITLE
image/save: Fix untagged images not present in index.json

### LINKED ISSUE #47165: integration test: Check OCI Manifest layers order
### Description

Regression test for: https://github.com/moby/moby/pull/47160

This would require a [frozen](https://github.com/moby/moby/blob/f0eef502739611f00d2d5f91c80a0436eec2983a/Dockerfile#L129-L134). or a [special](https://github.com/moby/moby/tree/v25.0.0/internal/testutils/specialimage) image that has more than one layer (probably even more than 2).

### LINKED ISSUE #47210: [v25] `docker save <IMAGE>@<DIGEST>` produces `index.json` with `"manifest": null`
### Description

`docker save <IMAGE>@<DIGEST>` produces `index.json` with `"manifest": null`.

This violates the spec: https://github.com/opencontainers/image-spec/blob/v1.1.0-rc6/image-index.md?plain=1#L30-L33

> ```
> - **`manifests`** *array of objects*
> 
>   This REQUIRED property contains a list of [manifests](manifest.md) for specific platforms.
>   While this property MUST be present, the size of the array MAY be zero.
> ```
> 

`docker save <IMAGE>` without `@<DIGEST>` still produces a valid `index.json`.

### Reproduce

```console
$ docker pull hello-world
Using default tag: latest
latest: Pulling from library/hello-world
Digest: sha256:4bd78111b6914a99dbc560e6a20eab57ff6655aea4a80c50b0c5491968cbc2e6
Status: Image is up to date for hello-world:latest
docker.io/library/hello-world:latest

$ docker save hello-world | tar x && jq . <index.json
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.index.v1+json",
  "manifests": [
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:c55c4ab38c73b5b59d76afd01083be207b1897142fee10222e56d1fd708efb62",
      "size": 447,
      "annotations": {
        "io.containerd.image.name": "docker.io/library/hello-world:latest",
        "org.opencontainers.image.ref.name": "latest"
      },
      "platform": {
        "architecture": "amd64",
        "os": "linux"
      }
    }
  ]
}

$ docker save hello-world@sha256:4bd78111b6914a99dbc560e6a20eab57ff6655aea4a80c50b0c5491968cbc2e6 | tar x && jq . <index.json
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.index.v1+json",
  "manifests": null
}
```

### Expected behavior

A valid `index.json` with proper manifests

### docker version

```bash
Client: Docker Engine - Community
 Version:           25.0.1
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        29cf629
 Built:             Tue Jan 23 23:09:23 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.1
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       71fa3ab
  Built:            Tue Jan 23 23:09:23 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.27
  GitCommit:        a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc:
  Version:          1.1.11
  GitCommit:        v1.1.11-0-g4bccb38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    25.0.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 25.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc version: v1.1.11-0-g4bccb38
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-91-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.814GiB
 Name: lima-default
 ID: 9677585b-b0d1-4f48-a858-dc64cc071333
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by vvoland**
- fixes: https://github.com/moby/moby/issues/47210
- closes: https://github.com/moby/moby/issues/47165

Saving an image via digested reference, ID or truncated ID doesn't store the image reference in the archive. This also causes the save code to not add the image's manifest to the index.json.
This PR explicitly adds the untagged manifests to the index.json if no tagged manifests were added.

**- How to verify it**

- TestSaveOCI integration test

#### By digest
```bash
$ docker save hello-world@sha256:4bd78111b6914a99dbc560e6a20eab57ff6655aea4a80c50b0c5491968cbc2e6 | tar xO index.json | jq
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.index.v1+json",
  "manifests": [
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:411caf340c828657e915a83ed561a79d2b8150dabad4dc079d881cbfe6f86afe",
      "size": 447,
      "platform": {
        "architecture": "arm64",
        "os": "linux"
      }
    }
  ]
}

```

#### By tag
```bash
$ docker save hello-world | tar xO index.json | jq
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.index.v1+json",
  "manifests": [
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:411caf340c828657e915a83ed561a79d2b8150dabad4dc079d881cbfe6f86afe",
      "size": 447,
      "annotations": {
        "io.containerd.image.name": "docker.io/library/hello-world:latest",
        "org.opencontainers.image.ref.name": "latest"
      },
      "platform": {
        "architecture": "arm64",
        "os": "linux"
      }
    }
  ]
}

```

#### Tag and digest
```bash
$ docker tag hello-world my:hello
$ docker save hello-world my:hello \
   hello-world@sha256:4bd78111b6914a99dbc560e6a20eab57ff6655aea4a80c50b0c5491968cbc2e6 | \
   tar xO index.json | jq
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.index.v1+json",
  "manifests": [
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:411caf340c828657e915a83ed561a79d2b8150dabad4dc079d881cbfe6f86afe",
      "size": 447,
      "annotations": {
        "io.containerd.image.name": "docker.io/library/hello-world:latest",
        "org.opencontainers.image.ref.name": "latest"
      },
      "platform": {
        "architecture": "arm64",
        "os": "linux"
      }
    },
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:411caf340c828657e915a83ed561a79d2b8150dabad4dc079d881cbfe6f86afe",
      "size": 447,
      "annotations": {
        "io.containerd.image.name": "docker.io/library/my:hello",
        "org.opencontainers.image.ref.name": "hello"
      },
      "platform": {
        "architecture": "arm64",
        "os": "linux"
      }
    }
  ]
}

```

**- Description for the changelog**
```release-note
- Fix `docker save <image>@<digest>` producing an OCI archive with index without manifests
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: pkg/archive/archive.go [hunk 1]
```diff
@@ -1501,3 +1502,19 @@ func (archive *TempArchive) Read(data []byte) (int, error) {
 	}
 	return n, err
 }
+
+// UncompressedDigest returns the digest of the uncompressed tar stream.
+func UncompressedDigest(alg digest.Algorithm, compressedTar io.Reader) (digest.Digest, error) {
```
Comment (thaJeztah) [inline pkg/archive/archive.go:1507]: It looks like this is only used in a test, but introduces a new exported function in `pkg/archive` (used in other projects), as well as a new dependency for the package (`github.com/opencontainers/go-digest`).


It feels like "digest" feels not _directly_ relate to "archives" (only in context of handling an archive for an image(-layer). Perhaps we should look at a different package to put this in (could even be in the `internal/testutils` for now if we only use it for tests, or perhaps otherwise in the `image/` package (if we need to have it available elsewhere)?

File: pkg/archive/archive.go [hunk 2]
```diff
@@ -1501,3 +1502,19 @@ func (archive *TempArchive) Read(data []byte) (int, error) {
...
+	rd, err := DecompressStream(compressedTar)
+	if err != nil {
+		return "", err
+	}
+
+	defer rd.Close()
+
+	digester := alg.Digester()
```
Comment (thaJeztah) [inline pkg/archive/archive.go:1515]: Also note that this will panic if `"crypto/sha256"` is not imported (which is currently not by default, see https://github.com/opencontainers/go-digest/pull/64)

https://github.com/moby/moby/blob/794f7127efd841e023dbd88051c577489f6cd3cf/vendor/github.com/opencontainers/go-digest/algorithm.go#L112

https://github.com/moby/moby/blob/794f7127efd841e023dbd88051c577489f6cd3cf/vendor/github.com/opencontainers/go-digest/algorithm.go#L116-L136

Comment (vvoland) [reply pkg/archive/archive.go]: Oh, TIL, thanks!

File: pkg/archive/archive.go (hunk 1 above)
Comment (vvoland) [reply pkg/archive/archive.go]: Moved to `internal/testutils`.

**Review by cpuguy83 — CHANGES_REQUESTED** [review]

**Comment by thaJeztah** [comment]
@vvoland could you have a peek at the review comment above?

File: internal/testutils/specialimage/multilayer.go [hunk 3]
```diff
@@ -0,0 +1,184 @@
...
+		MediaType: ocispec.MediaTypeImageManifest,
+		Config:    configDesc,
+		Layers:    []ocispec.Descriptor{layer1Desc, layer2Desc, layer3Desc},
+	})
+	if err != nil {
+		return err
+	}
+
+	manifestDesc.Annotations = map[string]string{
+		"io.containerd.image.name": "docker.io/library/multilayer:latest",
```
[the remark this answers is not in the document]
Comment (vvoland) [reply internal/testutils/specialimage/multilayer.go]: Extracted another function and moved the hardcoded values up. Let me know if that works for you!

**Comment by thaJeztah** [comment]
Failures are Windows + containerd snapshotter, and are known to still fail, so can be ignored

**Review by cpuguy83 — APPROVED** [review]

**Review by thaJeztah — COMMENTED** [review]
quick blurb, as I started to look (so far nothing _blocking_) but had to drop off, so let me post what I had

**Review by thaJeztah — APPROVED** [review]
LGTM

File: image/tarexport/save.go [hunk 4]
```diff
@@ -268,16 +274,17 @@ func (s *saveSession) save(outStream io.Writer) error {
...
-				Platform:  m.Config.Platform,
-				Annotations: map[string]string{
-					images.AnnotationImageName: ref.String(),
-					ocispec.AnnotationRefName:  ref.Tag(),
-				},
-			})
+			taggedManifest := untaggedMfstDesc
+			taggedManifest.Annotations = map[string]string{
+				images.AnnotationImageName: ref.String(),
+				ocispec.AnnotationRefName:  ref.Tag(),
```
[the remark this answers is not in the document]
Comment (thaJeztah) [reply image/tarexport/save.go:280]: Hm.. interesting; so that would mean duplicating the same information (and implicitly; requiring the reader of that information having to parse the format to get the tag only?).

One thing I notice in that section is that it looks like `separator` as part of components seems to have been conflated with `separator` between name and tag (or digest);

> - **org.opencontainers.image.ref.name** Name of the reference for a target (string).
>     - SHOULD only be considered valid when on descriptors on `index.json` within [image layout](image-layout.md).
>     - Character set of the value SHOULD conform to alphanum of `A-Za-z0-9` and separator set of `-._:@/+`
>     - A valid reference matches the following [grammar](considerations.md#ebnf):
> 
>       ```ebnf
>       ref       ::= component ("/" component)*
>       component ::= alphanum (separator alphanum)*
>       alphanum  ::= [A-Za-z0-9]+
>       separator ::= [-._:@+] | "--"
>       ```

The [distribution/reference grammar](https://pkg.go.dev/github.com/distribution/reference) uses a different definition;

```
separator := /[_.]|__|[-]*/
```

- it only allows `-._` as separators
- 2 consecutive underscores (`__`)
- zero or more hypens (`-`)

The  `:`, `@` would be to separate tag or digest, and 


If I read the OCI spec there correctly, something like `docker.io/github.com/he:llo@sha256+fo--b_ar` would be a valid value, but not parseable with the distribution/reference package :grimace:

[the remark this answers is not in the document]
Comment (thaJeztah) [reply image/tarexport/save.go:280]: Hm.. for `org.opencontainers.image.base.name`, there's a mention that it should be in the format described in distribution/reference; should that also be done for the above?

> - **org.opencontainers.image.base.name** Image reference of the image this image is based on (string)
>  - This SHOULD be image references in the format defined by [distribution/distribution][distribution-reference].
