### PR TITLE
volume/local: Make host resolution backwards compatible

### LINKED ISSUE #47184: container with cifs volume and "addr"-option does not start with version 25
- relates to https://github.com/docker/cli/issues/4816

### Description

The fix for resolving FQDN with cifs volumes did break the old workaround with the addr-option.
Container that run with v24 does not start with v25.

Even if it is no longer necessary to include the "addr" option, it should still work.

https://github.com/moby/moby/pull/46863

And the documentation still shows the old workaround as necessary:
https://docs.docker.com/storage/volumes/#create-cifssamba-volumes

### Reproduce

```
services:

cifs-test:
    image: ubuntu
    volumes:
      - inputdir:/opt/input

volumes:
  inputdir:
    driver: local
    driver_opts:
      type: "cifs"
      o: "addr=domain.local,user=${env:user},password=${env:userpw},file_mode=0666,dir_mode=0666,iocharset=utf8"
      device: "//dummy-fs/data"

```      
      
docker compose up

> Error response from daemon: error while mounting volume '/var/lib/docker/volumes/jenkins_inputdir/_data': failed to mount local volume: mount //XXX.XXX.XXX.XXX/data:/var/lib/docker/volumes/jenkins_inputdir/_data, data: addr=domain.local,user=********,password=********,file_mode=0666,dir_mode=0666,iocharset=utf8: invalid argument

### Expected behavior

Starting the container with volume as it worked with v24

### docker version

```bash
Client: Docker Engine - Community
 Version:           25.0.0
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        e758fe5
 Built:             Thu Jan 18 17:09:49 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.0
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       615dfdf
  Built:            Thu Jan 18 17:09:49 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.27
  GitCommit:        a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc:
  Version:          1.1.11
  GitCommit:        v1.1.11-0-g4bccb38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    25.0.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 49
  Running: 49
  Paused: 0
  Stopped: 0
 Images: 27
 Server Version: 25.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc version: v1.1.11-0-g4bccb38
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.2.0-39-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 50.91GiB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

To successfully start the above compose with version 25, the option "addr" must be removed and the FQDN must be used inside device

### PR DESCRIPTION
**Pull request by vvoland**
- fixes: https://github.com/moby/moby/issues/47184
- relates to https://github.com/docker/cli/issues/4816

Commit 8ae94cafa50a90192a0c0189f54443abac7a9b44 added a DNS resolution of the `device` part of the volume option.

The previous way to resolve the passed hostname was to use `addr` option, which was handled by the same code path as the `nfs` mount type.

The issue is that `addr` is also an SMB module option handled by kernel and passing a hostname as `addr` produces an invalid argument error.

To fix that, restore the old behavior to handle `addr` the same way as before, and only perform the new DNS resolution of `device` if there is no `addr` passed.

NOTE: While kernel docs don't mention the `addr` option (https://www.kernel.org/doc/html/latest/admin-guide/cifs/usage.html#use-instructions), it's actually present in the source: https://github.com/torvalds/linux/blob/7ed2632ec7d72e926b9e8bcc9ad1bb0cd37274bf/fs/smb/client/fs_context.c#L166

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**
```release-note
- Fix CIFS volume mount error when passing an `addr` mount option
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: volume/local/local_unix.go [hunk 1]
```diff
@@ -136,6 +138,22 @@ func (v *localVolume) mount() error {
...
 		}
 	case "cifs":
+		resolveDeviceName := true
+		// Don't perform the DNS resolution if the addr or ip option was passed
+		// explicitly by the user.
+		opts := strings.Split(mountOpts, ",")
+		for _, optKV := range opts {
+			opt, _, ok := strings.Cut(optKV, "=")
+			if ok && (opt == "addr" || opt == "ip") {
+				log.G(context.TODO()).Debugf("not performing dns resolution of device %q, because \"addr\" or \"ip\" opt was passed", v.opts.MountDevice)
```
[the remark this answers is not in the document]
Comment (vvoland) [reply volume/local/local_unix.go]: Thanks, fixed!

File: volume/local/local_unix.go [hunk 2]
```diff
@@ -136,6 +138,22 @@ func (v *localVolume) mount() error {
...
+		// Don't perform the DNS resolution if the addr or ip option was passed
+		// explicitly by the user.
+		opts := strings.Split(mountOpts, ",")
+		for _, optKV := range opts {
+			opt, _, ok := strings.Cut(optKV, "=")
+			if ok && (opt == "addr" || opt == "ip") {
+				log.G(context.TODO()).Debugf(`not performing dns resolution of device %q, because "addr" or "ip" opt was passed`, v.opts.MountDevice)
+				resolveDeviceName = false
+				break
+			}
```
Comment (robmry) [inline volume/local/local_unix.go:151]: Because `addr` is an alias for `ip` (both expect an address), I think we should preserve the old behaviour for CIFS by resolving `addr` if it's a hostname.

Then it'll continue to work for people who've been following [our docs](https://docs.docker.com/storage/volumes/#create-cifssamba-volumes), and it won't be necessary for them to [rebuild the volume with 'addr=' removed](https://github.com/moby/moby/pull/46863#issuecomment-1904472670).

That rewrite of the `addr` option before passing it to the kernel is what we were doing in v24, and we're still doing in v25 for NFS, to allow people to avoid hard-coding an address.

File: volume/local/local_unix.go [hunk 3]
```diff
@@ -136,6 +138,22 @@ func (v *localVolume) mount() error {
 			mountOpts = strings.Replace(mountOpts, "addr="+addrValue, "addr="+ipAddr.String(), 1)
 		}
 	case "cifs":
+		resolveDeviceName := true
```
Comment (thaJeztah) [inline volume/local/local_unix.go:141]: I see you pushed; just now thinking (it’s a nit really!); perhaps use `skipResolve` or skipXXXX for the variable? (false by default)

Comment (vvoland) [reply volume/local/local_unix.go]: Done! 😄

**Review by thaJeztah — DISMISSED** [review]
~LGTM~

File: volume/local/local_unix.go (hunk 2 above)
Comment (thaJeztah) [reply volume/local/local_unix.go]: Yeah, honestly, it was a bit hacky from the start (and we don't have a setup in our CI to verify). I agree though that we should probably preserve existing behavior (if that worked for some?)

Comment (vvoland) [reply volume/local/local_unix.go]: Restored the old behavior for `addr`.

**Review by robmry — APPROVED** [review]
LGTM - although duplicating the code seems like a bit of a shame... could factor it out into a closure that returns a bool to say whether it did anything?

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by robmry — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Seeing failures like this quite frequently in the BuildKit integration tests. Not specifically this address, but seems to be general lookup / "not found" failures (?)

```
=== FAIL: client TestIntegration (2.05s)
time="2024-01-23T14:01:29Z" level=info msg="trying next host - response was http.StatusNotFound" host="localhost:42291"
time="2024-01-23T14:01:29Z" level=info msg=request digest="sha256:be691b1535726014cdf3b715ff39361b19e121ca34498a9ceea61ad776b9c215" mediatype=application/vnd.docker.image.rootfs.foreign.diff.tar size=10240 url="https://gist.github.com/cpuguy83/fcf3041e5d8fb1bb5c340915aabeebe0/raw/eebc59ee14939fc38067aa8b8dfbfba053d0af94/base.tar"
    run.go:266: copied docker.io/cpuguy83/buildkit-foreign:latest to local mirror localhost:42291/cpuguy83/buildkit-foreign:latest
time="2024-01-23T14:01:29Z" level=info msg="trying next host - response was http.StatusNotFound" host="localhost:42291"
    run.go:266: copied docker.io/amd64/alpine:latest@sha256:25fad2a32ad1f6f510e528448ae1ec69a28ef81916a004d3629874104f8a7f70 to local mirror localhost:42291/library/alpine:latest
time="2024-01-23T14:01:30Z" level=info msg="trying next host - response was http.StatusNotFound" host="localhost:42291"
    run.go:266: copied docker.io/tonistiigi/test:nolayers to local mirror localhost:42291/tonistiigi/test:nolayers
```


Either way; it's not related to this PR, so kicked CI again.


Hoping one day we have stats / metrics from CI, so that we can identify flaky tests.
