### PR TITLE
Active endpoints error error

### LINKED ISSUE #49887: Network removal fails with "network has active endpoints" error during docker-compose down
### Description

When shutting down Docker Compose environments with docker-compose down, I consistently get errors about networks having active endpoints. This happens even though all containers appear to be removed properly.

Error message example:

```
[+] Running 12/12
 ✔ Container XXX-abc-1    Removed
 ✔ Container XXX-bcd-1    Removed
 ✔ Container XXX-cdf-1    Removed
 ✔ Container XXX-dfg-1    Removed
 ✔ Container XXX-fgh-1    Removed
 ✔ Container XXX-ghi-1    Removed
 ✔ Container XXX-hij-1    Removed
 ✔ Container XXX-ijk-1    Removed
 ✔ Volume XXX_cdf-storage Removed
 ✔ Volume XXX_cdf-public  Removed
 ✘ Network XXX_storage    Error
 ✘ Network XXX_frontend   Error
failed to remove network XXX_storage: Error response from daemon: error while removing network: network XXX_storage has active endpoints (, , )
```

The issue affects multiple environments with the same pattern. I can temporarily fix it by running:

1. docker compose down -v for all environments
2. service docker restart && docker network prune
3. docker compose up -d for all environments

However, the error returns after server or Docker service restart.

### Reproduce

1. Create a Docker Compose setup with multiple services connected to custom networks (similar to my config)
2. Run `docker-compose up -d` to start everything
3. Restart the server or Docker service (e.g., using `systemctl restart docker` or server reboot)
4. After restart, try to stop the environment with `docker-compose down`
5. Observe network removal errors in the output
6. This pattern repeats after each server or Docker service restart

### Expected behavior

_No response_

### docker version

```bash
Client: Docker Engine - Community
 Version:           28.1.1
 API version:       1.49
 Go version:        go1.23.8
 Git commit:        4eba377
 Built:             Fri Apr 18 09:52:57 2025
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          28.1.1
  API version:      1.49 (minimum version 1.24)
  Go version:       go1.23.8
  Git commit:       01f442b
  Built:            Fri Apr 18 09:52:57 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.27
  GitCommit:        05044ec0a9a75232cad458027ca83437aae3f4da
 runc:
  Version:          1.2.5
  GitCommit:        v1.2.5-0-g59923ef
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    28.1.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.35.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 145
  Running: 145
  Paused: 0
  Stopped: 0
 Images: 17
 Server Version: 28.1.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05044ec0a9a75232cad458027ca83437aae3f4da
 runc version: v1.2.5-0-g59923ef
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-28-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 30.61GiB
 Name: XXXX
 ID: XXXX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 172.16.0.0/12, Size: 24
```

### Additional Info

This appears to be related to containers not properly disconnecting from networks before network removal is attempted. I've attached my full docker-compose.yml for reference.

I've noticed the issue occurs specifically with the "storage" and "frontend" networks I've defined in the compose file. The issue affects all environments using this docker-compose template.

Workarounds I've tried:
- Adding depends_on to ensure proper shutdown order
- Manual removal of networks with docker network rm

None of these solves the root problem permanently.

[docker-compose.yml.txt](https://github.com/user-attachments/files/19935688/docker-compose.yml.txt)
(File had to be renamed due to upload conditions)

Linked to https://github.com/docker/compose/issues/12770

### LINKED ISSUE #49888: "network XXX has active endpoints" error should account for empty endpoint names
### Description

- related to https://github.com/moby/moby/pull/49773
- related to https://github.com/moby/moby/issues/49887
- related to https://github.com/docker/compose/issues/12770#issuecomment-2829556006

PR https://github.com/moby/moby/pull/49773 improved this error, adding the list of endpoints still connected to the network, however it didn't account for endpoints without a name, which could cause the error to include an empty list of names;

```
error while removing network: network XXX_storage has active endpoints (, , )
```

### Reproduce

No consistent reproducer.

### Expected behavior

The list of endpoints to

- not include empty values (could be either "id" or "name")
- not include duplicate values (i.e., we should account for "name" and "id" being for the same endpoint?)

### docker version

```bash
Client: Docker Engine - Community
 Version:           28.1.1
 API version:       1.49
 Go version:        go1.23.8
 Git commit:        4eba377
 Built:             Fri Apr 18 09:52:57 2025
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          28.1.1
  API version:      1.49 (minimum version 1.24)
  Go version:       go1.23.8
  Git commit:       01f442b
  Built:            Fri Apr 18 09:52:57 2025
  OS/Arch:          linux/amd64
  Experimental:     false
```

### docker info

```bash
not relevant for this
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by robmry**
**- What I did**

- fix https://github.com/moby/moby/issues/49887
  - introduced by https://github.com/moby/moby/pull/49736
  - related to https://github.com/moby/moby/commit/c8a66f5e72d085d0f3550f70adde82ad3e9121b0
- fix https://github.com/moby/moby/issues/49888
  - introduced by https://github.com/moby/moby/pull/49773

When a `Sandbox` is restored on startup (either to be used, because live-restore is enabled, or to clean up a container that was left running on shutdown) ... if the `Network` or `Endpoint` objects can't be loaded from store, stub objects are created.

If the `Sandbox` is being live-restored, the stub `Endpoint` is then just discarded. Otherwise, the `Endpoint` is added to the `Sandbox` then `sb.delete` is called to do the cleanup.

`sb.delete` calls `Endpoint.Delete` on each `Endpoint` - and `Endpoint.Delete` does nothing if it can't load both `Network` and `Endpoint` from the disk store.

So, either way, the stub `Network`/`Endpoint` objects end up having no effect.

https://github.com/moby/moby/issues/49887 added in-memory caches of `Network` and `Endpoint` objects. The caches are populated whenever those objects are read from or written to the on-disk store - but most readers don't use the cached objects (yet), they just load a new copy of the object from the disk store and use that.

That change added the stub objects to the in-memory cache - but they were never deleted from cache... if live-restore, they'd just be orphaned (the Endpoint wasn't added to the Sandbox). It not-live-restore, `Endpoint.Delete` returned early, before removing the cached `Endpoint` object so, again, the stub objects were orphaned.

That caused a problem for the one of the only uses (so far) of the in-memory caches, replacing the stored Endpoint Count  for a network with a search of the cache. The orphaned stub Endpoints referred to the network, so network deletion would fail with `ActiveEndpointsError`. I've not been able to reproduce the problem reported in https://github.com/moby/moby/issues/49887, so don't have logs to prove it and none have been provided on the issue yet... but the error message has an empty Endpoint name, so it looks very much like the endpoints are stub objects.

If all that theorising is correct ...
- it's a regression, it's no longer possible to delete a network after restore on startup has failed to read load an Endpoint from the store - and that's fixable.
- but, the root cause, a stored Sandbox having a reference to an Endpoint that isn't stored is a separate issue.
  - I guess it'll have been caused by the issue the in-memory caches should eventually resolve... multiple copies of the same object in memory, racing/trampling each other to the store. Although a race like that is detected, it's handled by just [forcing a write to store anyway](https://github.com/moby/moby/blob/d377cd3810bf6e7a328371402a23ab76043a37a5/libnetwork/sandbox_store.go#L134).

**- How I did it**

#### Report endpoint id as well as name in ActiveEndpointsError

When a network genuinely has active endpoints, the new error looks like this ...
```
# docker network rm nnn
Error response from daemon: error while removing network: network nnn has active endpoints (name:"romantic_cerf" id:"6e6ce97cc986", name:"charming_rubin" id:"2f704afa034c")
```

#### Improve logging and readability of Controller.sandboxRestore

- Use structured logging.
  - Which means ids are logged consistently.
- Use variable 'isRestore' instead of extra map lookups.

#### Don't add stub Endpoint/Network object to cache on Sandbox restore

The stub objects were introduced by https://github.com/moby/moby/commit/c8a66f5e72d085d0f3550f70adde82ad3e9121b0 - I don't think that logic applies any more, and ...
- a stub `Network` that doesn't know which network driver it should have isn't going to be able to get involved in much cleanup, I think it was just a way to load an `Endpoint` object.
- a stub `Endpoint` can't clean up anything like addresses/dns-entries etc, because it doesn't know what they are. But, that's ok because those things couldn't have been restored to internal structures anyway.
- worst-case, an Endpoint object that couldn't be loaded because of a missing `Network` gets leaked in the disk-store (but, quite likely, it's not there anyway!).

So, removed them.

**- How to verify it**

Tricky - no repro, and I can't add a unit test for deleted code.

**- Human readable description for the release notes**
```markdown changelog
Fix an issue that could cause network deletion to fail after a daemon restart, with error "has active endpoints" listing empty endpoint names.
```

### CODE REVIEW

File: libnetwork/network.go [hunk 1]
```diff
@@ -1048,9 +1048,11 @@ func (n *Network) delete(force bool, rmLBEndpoint bool) error {
 	eps := c.findEndpoints(filterEndpointByNetworkId(n.id))
 	if !force && len(eps) > emptyCount {
 		return &ActiveEndpointsError{
-			name:      n.name,
-			id:        n.id,
-			endpoints: sliceutil.Map(eps, func(ep *Endpoint) string { return ep.name }),
+			name: n.name,
+			id:   n.id,
+			endpoints: sliceutil.Map(eps, func(ep *Endpoint) string {
+				return fmt.Sprintf("name:%q id:%q", ep.name, stringid.TruncateID(ep.id))
```
Comment (thaJeztah) [inline libnetwork/network.go:1054]: I know `%q` sometimes leads to additional escaping in output (`foo:\"\"`) which can reduce readability; for `id`, I don't _THINK_ we'd ever have an empty value(?) in that case at least for `id` we probably don't need `%q`.

For name (which from reports ended up being empty), I wonder if we could make the output "optional", e.g.

- `deadbeef` (only ID was set)
- `deadbeef (happy_torvalds)` (name was set)

Although .. I guess we list all of the endpoints within `()` in the error, so that would end up as;

```
has active endpoints (deadbeef (happy_torvalds), cafebeef (boring_wozniak))`
```

(not sure if the extra braces would make it hard to read, but perhaps that's .. "OK"?)

Comment (robmry) [reply libnetwork/network.go:1054]: Ok, I'll change the `%q` to `%s`.

But an Endpoint should always have a name - particularly now I've deleted the stub instantiations made when a load from store failed. So, I don't think it's worth changing the message to deal with empty strings.

I put an example of the error in the description ...
```
network nnn has active endpoints (name:"romantic_cerf" id:"6e6ce97cc986", name:"charming_rubin" id:"2f704afa034c")
```

If there's something wrong with it - I think it's that it lists endpoint names and ids, and those aren't things users should need to know or care about. Listing the container name/id (if they can be tracked down) would be more meaningful. That's not this change - but, because the fields aren't anonymous, there's scope for adding container name/id if known.

File: libnetwork/sandbox_store.go [hunk 2]
```diff
@@ -229,35 +228,13 @@ func (c *Controller) sandboxRestore(activeSandboxes map[string]interface{}) erro
...
-				if err != nil {
-					log.G(ctx).WithError(err).Error("getEndpointFromStore failed while trying to build sandbox")
-					ep = &Endpoint{
-						id:        eps.Eid,
-						network:   n,
-						sandboxID: sbs.ID,
-					}
-					c.cacheEndpoint(ep)
-				}
+				log.G(ctx).WithError(err).Error("Failed to restore endpoint, getNetworkFromStore failed")
```
[the remark this answers is not in the document]
Comment (robmry) [reply libnetwork/sandbox_store.go:232]: I think the same applies to most of libnetwork's error-ignoring ... errors shouldn't be ignored, but handling them can have [highly unpredictable consequences](https://github.com/moby/moby/pull/49525#:~:text=In%2027.x%2C%20the%20error%20wasn%27t%20propagated%20properly%2C%20a%20nil%20was%20returned%20following%20an%20attempt%20to%20roll%2Dback%20the%20rule%20that%20wasn%27t%20created%2C%20so%20startup%20continued.%20Commit%20255fff4%20fixed%20the%20error%20propagation%2C%20breaking%20startup%20in%20this%20case.).

Not finding these objects in the store should mean something really bad happened, like the data store on disk got corrupted. In which case, the right thing would be to abort and get the underlying issue fixed. (Particularly for the live-restore case... better not to restore anything than get to a broken state that'll be hard to debug.)

But, as the issue linked from this PR suggests, it does happen - probably because of the known races in the way libnetwork uses its data store. That's the issue Albin's new in-memory caches should eventually help with, and this issue/PR demonstrates how difficult it is to untangle without breaking things.

So, there's no way for this code to tell whether something bad is going to happen, or has already happened. I can add a comment to that effect. Not sure about Error vs Warning ... perhaps not knowing for-sure that we broke things means it can be a Warning, but it's not ideal.

File: libnetwork/sandbox_store.go [hunk 3]
```diff
@@ -193,11 +194,9 @@ func (c *Controller) sandboxRestore(activeSandboxes map[string]interface{}) erro
 			dbExists:           true,
 		}
 
-		msg := " for cleanup"
 		create := true
 		isRestore := false
 		if val, ok := activeSandboxes[sb.ID()]; ok {
-			msg = ""
```
Comment (thaJeztah) [inline libnetwork/sandbox_store.go:200]: Ever so slightly considering if including a  message in the log-message itself would still be useful (would it be easier to grep?) Not sure if the existing messages were accurate, but I could imagine "Failed to xxxx for cleanup" or "Failed to xxx during restore" (or whatever covers it best), would help debugging logs provided by users.

Not a blocker for sure!

File: libnetwork/sandbox_store.go [hunk 4]
```diff
@@ -206,9 +205,17 @@ func (c *Controller) sandboxRestore(activeSandboxes map[string]interface{}) erro
 			sb.restoreResolvConfPath()
 			create = !sb.config.useDefaultSandBox
 		}
+
+		ctx := context.TODO()
```
Comment (thaJeztah) [inline libnetwork/sandbox_store.go:208]: Looks like punching-through the context is a realistic option (as a follow-up); I see this function is called from `libnetwork.New`, which already has a context and spans set up.

(Not sure if context-cancelation is expected to be handled in this function though, or if it would require a `context.WithoutCancel()`.

**Review by thaJeztah — APPROVED** [review]
LGTM

File: libnetwork/sandbox_store.go (hunk 3 above)
Comment (robmry) [reply libnetwork/sandbox_store.go:200]: Before, `msg` was only used by "failed to create osl sandbox". The two per-Endpoint log lines just said "for cleanup", whether it was or not ...
```
log.G(context.TODO()).Errorf("getNetworkFromStore for nid %s failed while trying to build sandbox for cleanup: %v", eps.Nid, err)
log.G(context.TODO()).Errorf("getEndpointFromStore for eid %s failed while trying to build sandbox for cleanup: %v", eps.Eid, err)
```

Now, `isRestore` is always included as a logger field.

**Review by dmcgowan — APPROVED** [review]
