### PR TITLE
Avoid setting default truthy values from flags that are not set.

### LINKED ISSUE #20289: Option in daemon.json file for userland-proxy being ignored
Description of problem:
When using the option in daemon.json file for userland-proxy, it is being ignored.

`docker version`:
```
$ docker version
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:15:20 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:15:20 2016
 OS/Arch:      linux/amd64
```

`docker info`:
```
$ docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 403
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 413
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux stretch/sid
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.963 GiB
Name: localdev
ID: ABO2:4REM:BS7R:OXYG:R7V6:UJGL:2YTX:CJ7H:UEYY:IK7O:JXYQ:YBYX
Username: mbentley
Registry: https://index.docker.io/v1/
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

`uname -a`:
```
$ uname -a
Linux localdev 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u2 (2016-01-02) x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.):
Debian Sid on VirtualBox; running kernel from jessie

How reproducible:
Happens when specifying `userland-proxy` in my `daemon.json` file

Steps to Reproduce:
1. Reconfigure the daemon to use a `daemon.json` file with `"userland-proxy": false` set in the file (see my file at the end of this issue)
2. Restart the docker daemon
3. Run a container with a port exposed and see the `docker-proxy` process running

Actual Results:
```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─10-execstart.conf
   Active: active (running) since Fri 2016-02-12 17:16:11 EST; 6min ago
     Docs: https://docs.docker.com
 Main PID: 8310 (docker)
   Memory: 22.9M
      CPU: 485ms
   CGroup: /system.slice/docker.service
           ├─8310 /usr/bin/docker daemon
           ├─8508 docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 80 -container-ip 172.17.0.2 -container-port 80
           ├─8515 nginx: master process nginx -c /etc/nginx/nginx.con
           ├─8522 nginx: worker process
           └─8523 nginx: worker process
```

Expected Results:
No `docker-proxy` process running indicating that the username proxy is not being used

Additional info:

`daemon.json`:
```
{
        "debug": false,
        "hosts": ["fd://"],
        "log-config": {
                "log-driver": "json-file",
                "log-opts": ["max-size=10m", "max-file=2"]
        },
        "storage-driver": "aufs",
        "graph": "/var/lib/docker",
        "userland-proxy": false
}
```

### PR DESCRIPTION
**Pull request by calavera**
When the value for a configuration option in the file is `false`,
and the default value for a flag is `true`, we should not
take the value from the later as final value for the option,
because the user explicitly set `false`.

This change overrides the default value in the flagSet with
the value in the configuration file so we get the correct
result when we merge the two configurations together.

Fixes #20289.

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM 🐰

**Comment by tiborvass** [comment]
janky failed on authz test only, thats a known issue.

**Comment by anusha-ragunathan** [comment]
AFAICT, mergo.Merge(dst, src) overwrites any field in dst that has zero or false with the src field's value. Wouldnt this affect fields with 0 int values in the fileConfig that have non-zero defaults in flagConfig? i.e issue is more than just bools?

**Comment by calavera** [comment]
@anusha-ragunathan that is correct. However, we only have one `Int` flag option, Mtu, which default is `0`, making it not an issue like boolean flags:

https://github.com/docker/docker/blob/master/daemon/config.go#L117

**Comment by anusha-ragunathan** [comment]
Ulimit (part of InstallFlags) is also int, but has null initialization. So we should be okay there as well. I'd like a comment about ints, so that in future if we add such a integer flag, we also add a corresponding patch to handle this case.

File: daemon/config.go [hunk 1]
```diff
@@ -206,6 +212,34 @@ func getConflictFreeConfiguration(configFile string, flags *flag.FlagSet) (*Conf
...
+				namedOptions[key] = value
+				continue
+			}
+
+			if _, ok := f.Value.(boolValue); ok {
+				f.Value.Set(fmt.Sprintf("%v", value))
+			}
+		}
+		if len(namedOptions) > 0 {
+			// set also default for mergeVal flags that are boolValue at the same time.
```
Comment (anusha-ragunathan) [inline daemon/config.go]: In the above loop, we are looping through the configSet, looking up their corresponding flags and setting flag values.

In this loop, we are looping through all flags, looking up their config values and again setting the flags.

Can you please explain with an example, why the second set is necessary?

File: daemon/config.go [hunk 2]
```diff
@@ -206,6 +212,34 @@ func getConflictFreeConfiguration(configFile string, flags *flag.FlagSet) (*Conf
 			return nil, err
 		}
 
+		// make sure that values set in the config file with nullable values, like `false`,
```
Comment (anusha-ragunathan) [inline daemon/config.go]: Update function getConflictFreeConfiguration comment to say that "flags will be updated, if necessary".

File: daemon/config.go [hunk 3]
```diff
@@ -206,6 +212,34 @@ func getConflictFreeConfiguration(configFile string, flags *flag.FlagSet) (*Conf
...
+		// are not overriden by default truthy values from the flags that were not explicitly set.
```
Comment (anusha-ragunathan) [inline daemon/config.go]: Infact, this entire new code can be moved down to findConfigurationConflicts and merged with L 272-278.

Comment (calavera) [inline daemon/config.go]: I rather not mix both function together, they serve two very different purposes.

File: daemon/config.go (hunk 1 above)
Comment (calavera) [inline daemon/config.go]: not all option names match 1-to-1 with flag names, like `label` and `labels`. We only perform the second loop if there are in fact any of those options specified in the configuration file.

File: daemon/config.go (hunk 2 above)
Comment (calavera) [inline daemon/config.go]: fair

File: daemon/config.go (hunk 3 above)
Comment (calavera) [inline daemon/config.go]: moving it there might create side effects with the conflict detection, I rather leave it working for now.

**Comment by calavera** [comment]
> I'd like a comment about ints, so that in future if we add such a integer flag, we also add a corresponding patch to handle this case.

I don't think a code comment can prevent that to happen unfortunately. I'd like to have more tests around those kind of cases, but they don't apply here.

**Comment by anusha-ragunathan** [comment]
There's already a comment about 'config file with nullable values". Add a line about how this behavior affects integers as well. That's it.

File: daemon/config.go (hunk 3 above)
Comment (anusha-ragunathan) [inline daemon/config.go]: Looking further, findConfigurationConflicts seems to be meant as a read-only/error reporting function that can also be called independent of getConflictFreeConfiguration. So its fair that you dont want to merge them.

**Comment by tiborvass** [comment]
LGTM

**Comment by anusha-ragunathan** [comment]
LGTM!
