### PR TITLE
pkg/archive: escape ":" symbol in overlay lowerdir

### LINKED ISSUE #40939: Failed to registrer layer when docker pull with Docker Rootless
Hi,

I am using Docker Rootless mode and encounter a problem while pulling an image.

A `docker pull osixia/phpldapadmin:stable` or any of its version (`:latest`, `:0.9.0` etc...) leads to this error message :

```
latest: Pulling from osixia/phpldapadmin
1ab2bdfe9778: Already exists
0abcaf321aa9: Already exists
6d688c3d4e02: Already exists
454331b99b9a: Pull complete
5cada7c8cb4e: Pull complete
b0f406024ee7: Pull complete
b04a43f9c3ac: Pull complete
92a3a5c2b5a5: Extracting [==================================================>]  34.17kB/34.17kB
e4955dcfbe65: Download complete
failed to register layer: Error processing tar file(exit status 1): failed to mknodChar0UserNS("/container/service/:apache2/install.sh"): failed to mount overlay (lowerdir=/container/service/:apache2/mc0o793276857/l,upperdir=/container/service/:apache2/mc0o793276857/u,workdir=/container/service/:apache2/mc0o793276857/w) on /container/service/:apache2/mc0o793276857/m: no such file or directory
```

Docker version : `19.03.8, build afacb8b7f0`  
OS : Ubuntu 18.04 (bionic)

It works perfectly fine on a classic non-rootless Docker install.   
I did not experience the problem with any other image yet.

- Would you have an idea why it fails ?

Thank you,

### PR DESCRIPTION
**Pull request by AkihiroSuda**
**- What I did**

Fix #40939

**- How I did it**

`ReplaceAll(lower, ":", "\\:")`, because lowerdir needs escaping:
https://github.com/torvalds/linux/blob/v5.4/fs/overlayfs/super.c#L835-L853

**- How to verify it**

Run `docker pull osixia/phpldapadmin:stable` on rootless with overlay2 on Ubuntu/Debian.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

🐧

### CODE REVIEW

File: pkg/archive/archive_linux.go [hunk 1]
```diff
@@ -236,7 +238,9 @@ func createDirWithOverlayOpaque(tmp string) (string, error) {
 	if err := os.MkdirAll(lowerDummy, 0700); err != nil {
 		return "", errors.Wrapf(err, "failed to create a dummy lower directory %s", lowerDummy)
 	}
-	mOpts := fmt.Sprintf("lowerdir=%s,upperdir=%s,workdir=%s", lower, upper, work)
+	// lowerdir needs ":" to be escaped: https://github.com/moby/moby/issues/40939#issuecomment-627098286
+	lowerEscaped := strings.ReplaceAll(lower, ":", "\\:")
+	mOpts := fmt.Sprintf("lowerdir=%s,upperdir=%s,workdir=%s", lowerEscaped, upper, work)
```
Comment (thaJeztah) [inline pkg/archive/archive_linux.go:243]: Does the same apply  to `upper` and `work`?

Wondering if we should have a `clean(path string)` function to handle this, and then;

```suggestion
	mOpts := fmt.Sprintf("lowerdir=%s,upperdir=%s,workdir=%s", clean(lower), clean(upper), clean(work))
```

Or perhaps do it in one go, something like;

```suggestion
	mOpts := fmt.Sprintf("lowerdir=%s,upperdir=%s,workdir=%s", lowerEscaped, upper, work)
	mOpts = clean(mOpts)
```

Comment (AkihiroSuda) [reply pkg/archive/archive_linux.go:243]: Specific to lowerdir (because it can be comma-sepatated list)

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by tonistiigi — APPROVED** [review]

**Comment by AkihiroSuda** [comment]
cherry-pick: https://github.com/moby/moby/pull/40970
