### PR TITLE
Fix converting status code to error canceled

### LINKED ISSUE #41752: Cancelled context is not converted properly to an ErrCancelled
**Steps to reproduce the issue:**

1. any program that uses the standard `logrus` logger, set to debug
2. every time when the context is canceled

**Describe the results you received:**

docker client:
```
...
DEBU[2020-11-22T20:48:52+01:00] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_c
ode=-1
...
```

**Describe the results you expected:**  

The result should not be `errUnknown`

_Originally posted by @kplachkov in https://github.com/moby/moby/issues/41667#issuecomment-731845505_

### PR DESCRIPTION
**Pull request by kplachkov**
closes #41752 

**- How to verify it**
go test errdefs/http_helpers_test.go 

**- Description for the changelog**
Fix converting status code to error canceled

### CODE REVIEW

File: errdefs/http_helpers.go [hunk 1]
```diff
@@ -99,6 +101,12 @@ func FromStatusCode(err error, statusCode int) error {
 		if !IsSystem(err) && !IsUnknown(err) && !IsDataLoss(err) && !IsDeadline(err) && !IsCancelled(err) {
 			err = System(err)
 		}
+	case -1:
+		if errors.Is(err, context.Canceled) {
+			err = Cancelled(err)
+		} else {
+			err = Unknown(err)
+		}
```
Comment (thaJeztah) [inline errdefs/http_helpers.go:109]: I'm a bit on the fence if this is the right location for this; if we _do_ want to include it here, perhaps it should be in the `default` section below.

That said; this function was specifically to convert a HTTP status to a typed error. IIUC, in the context cancelled cases we're handling here, it's not a "context cancelled" that's returned by the API (i.e., if a context was cancelled in the daemon code), but a "context cancelled" on the client side? 🤔

If that's indeed the case, perhaps these errors should be handled _before_ we try to convert a HTTP status returned by the daemon, e.g. in https://github.com/moby/moby/blob/46cdcd206c56172b95ba5c77b827a722dab426c5/client/request.go#L113-L116

or in https://github.com/moby/moby/blob/46cdcd206c56172b95ba5c77b827a722dab426c5/client/request.go#L121-L126

**Review by thaJeztah — CHANGES_REQUESTED** [review]
Left some thoughts. Perhaps @cpuguy83 could also have a quick peek

File: errdefs/http_helpers.go (hunk 1 above)
Comment (kplachkov) [reply errdefs/http_helpers.go:109]: i agree, in fact there is already a check for that in `doRequest`:

https://github.com/moby/moby/blob/46cdcd206c56172b95ba5c77b827a722dab426c5/client/request.go#L135-L139

but this does not solve the problem  

i think that a better solution will be to change: 
https://github.com/moby/moby/blob/46cdcd206c56172b95ba5c77b827a722dab426c5/client/request.go#L113-L118
to:
```go
	resp, err := cli.doRequest(ctx, req)
	switch {
	case errors.Is(err, context.Canceled), errors.Is(err, context.DeadlineExceeded):
		return serverResponse{}, err
	case err == nil:
		err = cli.checkResponseErr(resp)
	}

	return resp, errdefs.FromStatusCode(err, resp.statusCode)
```

Comment (thaJeztah) [reply errdefs/http_helpers.go:109]: Thanks; yes (at least at a quick glance), I think your proposed changes look good

**Comment by kplachkov** [comment]
sorry for the spam... note to self: dont drink and code 😂 wish you merry christmas and happy new year 🍺

**Comment by kplachkov** [comment]
what is the status of the review

File: client/request_test.go [hunk 2]
```diff
@@ -105,3 +107,41 @@ func TestInfiniteError(t *testing.T) {
...
+		client: newMockClient(func(req *http.Request) (*http.Response, error) {
+			assert.Equal(t, req.Context().Err(), context.DeadlineExceeded)
+
+			return &http.Response{}, context.DeadlineExceeded
+		}),
+	}
+
+	ctx, cancel := context.WithDeadline(context.Background(), time.Now())
+	defer cancel()
+
```
Comment (cpuguy83) [inline client/request_test.go:143]: Just a nit, I'd wait for `<-ctx.Done()`

**Comment by kplachkov** [comment]
its ready

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!!
