### PR TITLE
Use ID rather than Name to identify a container when sharing namespace

### LINKED ISSUE #34307: "docker run --net,--pid,--ipc" to a container is invalid after rename and restart
**Description**

**Steps to reproduce the issue:**
1.docker run -tid --name=test0 ubuntu bash
2.docker run -tid --name=test1 --net=container:test0 ubuntu bash
3.docker rename test0 test2
4.docker restart test1

**Describe the results you received:**
Error response from daemon: Cannot restart container test1: No such container: test0

When replace the "--net" to "--pid" or "--ipc" will get :
Post http://%2Fvar%2Frun%2Fdocker.sock/v1.29/containers/test3/restart: EOF

**Describe the results you expected:**
test1 restart succuss

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Fri May  5 15:36:11 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Fri May  5 15:36:11 2017
 OS/Arch:      linux/amd64
 Experimental: false

```
**Output of `docker info`:**

```
Containers: 15
 Running: 13
 Paused: 0
 Stopped: 2
Images: 60
Server Version: 17.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: false
 Native Overlay Diff: false
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.21.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.639GiB
Name: 16
ID: 5PRJ:JAJY:H6IP:OBMF:7QQ6:AQJ2:JHGD:KOHN:K4PZ:ETTR:JPUA:KZ2P
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 95
 Goroutines: 128
 System Time: 2017-07-30T02:26:57.040522467+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 demoregistry.dataman-inc.com
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by ChenMin46**
Fix: https://github.com/moby/moby/issues/34307

Signed-off-by: Chen Min <chenmin46@huawei.com>

**- What I did**
Convert from the connected container name to its ID when we create the container.

**- How I did it**
Modify PidMode、Ipcmode and NetworkMode of hostConfig in /daemon/daemon_unix.go

**- How to verify it**
I wrote a test case,which names "TestAdaptSharedNamespaceContainer".

**- Description for the changelog**

 daemon/daemon_unix.go                     | 31 +++++++++++++++++++++++++++++++
 integration-cli/docker_cli_create_test.go | 13 +++++++++++++
 2 files changed, 44 insertions(+)

**- A picture of a cute animal (not mandatory but encouraged)**
：）

### CODE REVIEW

**Review by AkihiroSuda — CHANGES_REQUESTED** [review]
The test result is unchecked.
Also, please add an API test instead of CLI one

File: daemon/daemon_unix.go [hunk 1]
```diff
@@ -290,6 +293,34 @@ func (daemon *Daemon) adaptContainerSettings(hostConfig *containertypes.HostConf
 	return nil
 }
 
+// When a container shares its namespace by container name,
```
Comment (ripcurld0) [inline daemon/daemon_unix.go]: Can you change the comment to `adaptSharedNamespaceContainer replaces a container name with its container ID when ...` or something similar.

File: daemon/daemon_unix.go [hunk 2]
```diff
@@ -290,6 +293,34 @@ func (daemon *Daemon) adaptContainerSettings(hostConfig *containertypes.HostConf
...
+// use container id rather than name to identify a container.
+func (daemon *Daemon) adaptSharedNamespaceContainer(hostConfig *containertypes.HostConfig) error {
+	containerPrefix := "container:"
+	if hostConfig.PidMode.IsContainer() {
+		c, err := daemon.GetContainer(hostConfig.PidMode.Container())
```
Comment (ripcurld0) [inline daemon/daemon_unix.go]: Maybe there is a way to call `daemon.GetContainer` once and avoid all these verbose code lines

**Review by boaz0 — CHANGES_REQUESTED** [review]
All in all LGTM minus the comment.

File: daemon/daemon_unix.go (hunk 2 above)
Comment (yummypeng) [inline daemon/daemon_unix.go]: @ripcurld0 I dont think there is a way to call `daemon.GetContainer` once since we may want to share different namespaces with different containers.

File: integration-cli/docker_cli_create_test.go [hunk 3]
```diff
@@ -441,3 +441,16 @@ func (s *DockerSuite) TestCreateStopTimeout(c *check.C) {
...
+	testRequires(c, DaemonIsLinux, SameHostDaemon, NotUserNamespace)
+	dockerCmd(c, "run", "-tid", "--name=test", "busybox")
+	dockerCmd(c, "run", "--name=testa", "--ipc=container:test", "busybox")
+	dockerCmd(c, "run", "--name=testb", "--pid=container:test", "busybox")
+	dockerCmd(c, "run", "--name=testc", "--net=container:test", "busybox")
+	dockerCmd(c, "rename", "test", "test2")
+	dockerCmd(c, "restart", "testa")
+	dockerCmd(c, "restart", "testb")
+	dockerCmd(c, "restart", "testc")
+}
```
Comment (yummypeng) [inline integration-cli/docker_cli_create_test.go]: This file is for `docker create` tests. Maybe you should put this testcase in another place.

**Comment by ChenMin46** [comment]
I have a doubt, when we create a container named AA but not start it, after another container BB created and BB shares AA's namespaces, we delete container AA, and then recreate a container named AA. Finally
，we start container BB. It comes out an error, the container ID（former AA） is not exists.

This case also confused users.

So, I wonder which logic is better, name or ID ?

**Comment by ChenMin46** [comment]
ping @AkihiroSuda 

I add an api test suite to check the results , PTAL. :)

**Comment by ChenMin46** [comment]
ping @ripcurld0 

The comments are updated, and some codes  are simplified. PTAL :^)

**Comment by ChenMin46** [comment]
The Jenkins control platform checks failed, I have no idea what caused this error.
 ping @ripcurld0 @AkihiroSuda 
```
00:44:09 + docker stop docker-pr-power5093
00:44:09 Error response from daemon: No such container: docker-pr-power5093
```

**Comment by ChenMin46** [comment]
All checks have passed , PTAL ,looking forward to your replies, ping @ripcurld0  @AkihiroSuda .  
image

**Review by boaz0 — APPROVED** [review]
LGTM 👍

**Comment by ChenMin46** [comment]
PTAL   ：）   
ping @AkihiroSuda

**Comment by AkihiroSuda** [comment]
Which function requires this to be ID string?

**Comment by ChenMin46** [comment]
When I rename a container which namespace is shared by another container B ,then we restart the container B,it will come out an error .see https://github.com/moby/moby/issues/34307

I try to use ID to keep the connection between the namespace shared and sharing containers.
ping @AkihiroSuda

File: daemon/daemon_unix.go [hunk 4]
```diff
@@ -290,6 +293,33 @@ func (daemon *Daemon) adaptContainerSettings(hostConfig *containertypes.HostConf
 	return nil
 }
 
+// adaptSharedNamespaceContainer replaces a container name with its container ID
+// when a container shares its namespace by container name.
```
Comment (AkihiroSuda) [inline daemon/daemon_unix.go]: Please add a comment so as to clarify that this conversion is needed for supporting rename operation

File: integration-cli/docker_api_containers_test.go [hunk 5]
```diff
@@ -1948,3 +1948,34 @@ func (s *DockerSuite) TestContainerKillCustomStopSignal(c *check.C) {
 	err = waitInspect(id, "{{.State.Running}} {{.State.Restarting}}", "false false", 30*time.Second)
 	c.Assert(err, checker.IsNil)
 }
+
+// Make sure that a container shares its namespace with ID.
+func (s *DockerSuite) TestContainerShareNamespaceByName(c *check.C) {
```
Comment (AkihiroSuda) [inline integration-cli/docker_api_containers_test.go]: This needs to be an API test with rename operation

**Comment by mlaventure** [comment]
ping @ChenMin46

**Comment by ChenMin46** [comment]
ping @mlaventure sorry for the late response. I have fixed the conflicts and update the api testsuit.PTAL
:>)

**Review by AkihiroSuda — APPROVED** [review]
LGTM

**Review by vdemeester — COMMENTED** [review]
SGTM 👼
/cc @dnephin @mlaventure @vieux

File: daemon/daemon_unix.go [hunk 6]
```diff
@@ -299,6 +301,34 @@ func (daemon *Daemon) adaptContainerSettings(hostConfig *containertypes.HostConf
 	return nil
 }
 
+// adaptSharedNamespaceContainer replaces a container name with its container ID when
+// a container shares its namespace by container name,so as to keep the namespace
+// sharing connection when renaming the container which namespaces be shared.
```
Comment (mlaventure) [inline daemon/daemon_unix.go]: nit: `it shared`?

**Review by mlaventure — APPROVED** [review]
one nit

LGTM

**Review by dnephin — COMMENTED** [review]
This should really be tested with a unit test. Unfortunately `Daemon` is heavily overloaded and makes this difficult.

I'd like to suggest a change which should make it easier to unit test. Instead of making `adaptSharedNamespaceContainer()` a method on `Daemon` (which already has way too many methods) make it a function that accepts an interface

```go
type containerGetter interface {
    func GetContainer(string) container.Container
}
```

That way you can easily provide a fake which returns the values you care about, and test the function behaviour (modifying hostConfig) without all the overhead of the existing integration tests.

**Review by dnephin — CHANGES_REQUESTED** [review]
Sorry, meant to comment as "Request changes" so doing that now

File: integration-cli/docker_api_containers_test.go [hunk 7]
```diff
@@ -1947,3 +1947,46 @@ func (s *DockerSuite) TestContainerKillCustomStopSignal(c *check.C) {
...
+	// Namespace is not supported on Windows
+	testRequires(c, DaemonIsLinux, SameHostDaemon, NotUserNamespace)
+
+	name := "base"
+	out := runSleepingContainer(c, "--name", name)
+	id := strings.TrimSpace(out)
+	expected := "container:" + id
+
+	dockerCmd(c, "run", "--name=share", "--ipc", "container:"+name, "--pid", "container:"+name, "--net", "container:"+name, "busybox")
```
Comment (ChenMin46) [inline integration-cli/docker_api_containers_test.go]: @dnephin I have modified `adaptSharedNamespaceContainer()` to accept a `containerGetter` interface as you suggested, here is the demo:
```go
diff --git a/daemon/daemon_unix.go b/daemon/daemon_unix.go
index b3eaa2f68..8bed31da3 100644
--- a/daemon/daemon_unix.go
+++ b/daemon/daemon_unix.go
@@ -64,6 +64,10 @@ const (
        cgroupSystemdDriver = "systemd"
 )

+type containerGetter interface {
+       GetContainer(string) (*container.Container, error)
+}
+
 func getMemoryResources(config containertypes.Resources) *specs.LinuxMemory {
        memory := specs.LinuxMemory{}

@@ -285,7 +289,7 @@ func (daemon *Daemon) adaptContainerSettings(hostConfig *containertypes.HostConf
                hostConfig.IpcMode = containertypes.IpcMode(m)
        }

-       daemon.adaptSharedNamespaceContainer(hostConfig)
+       adaptSharedNamespaceContainer(daemon, hostConfig)

        var err error
        opts, err := daemon.generateSecurityOpt(hostConfig)
@@ -304,7 +308,7 @@ func (daemon *Daemon) adaptContainerSettings(hostConfig *containertypes.HostConf
 // adaptSharedNamespaceContainer replaces a container name with its container ID when
 // a container shares its namespace by container name,so as to keep the namespace
 // sharing connection when renaming the container which namespaces be shared.
-func (daemon *Daemon) adaptSharedNamespaceContainer(hostConfig *containertypes.HostConfig) error {
+func adaptSharedNamespaceContainer(daemon containerGetter, hostConfig *containertypes.HostConfig) error {
        containerPrefix := "container:"
        if hostConfig.PidMode.IsContainer() {
                pidContainer := hostConfig.PidMode.Container()
```

> That way you can easily provide a fake which returns the values you care about

But what do you mean by `a fake`? If I understood correctly, you meant I should define a `fakedaemon`  and implement `GetContainer()` ( I think it's complicated to implement this method ), then use that `fakedaemon` to test func `adaptSharedNamespaceContainer`? Could you please give me more infomation?

I noticed a unittest named `TestAdjustCPUShares`, I think I can write a similar one without any change of `adaptSharedNamespaceContainer()` if it's acceptable.

Comment (dnephin) [inline integration-cli/docker_api_containers_test.go]: diff looks good.

Yes, a fake `containerGetter` really (not the whole daemon). It shouldn't be hard to implement, it's something like this:

```go

type fakeContainerGetter struct {
    containers map[string]*container.Container
}

func (f *fakeContainerGetter) GetContainer(cid string) (*container.Container, error) {
    container, ok := f.containers[cid]
    if !ok {
         return nil, errors.New("container not found")
    }
    return container, nil
}
```

A test like `TestAdjustCPUShares` would also be ok.

**Comment by ChenMin46** [comment]
image
ping @dnephin All the checks are passed except an irrelevant case. PTAL .：）

**Review by dnephin — APPROVED** [review]
LGTM
