### PR TITLE
Handle blocked I/O of exec'd processes, and remove flaky TestExecWindowsOpenHandles

### LINKED ISSUE #39326: Zombie reaping not occurring as expected
I'm working on an issue, where I've got a test harness for reliable reproduction (and it's fairly simple), and I think I've tracked the source of the issue down to containerd. In any version after 17.09.1, the test fails. I think this is because of a change introduced in containerd 1.0.0. The test is essentially this:

1) create a container called bad_parent (we're using ubuntu:xenial) 
`docker run --init -itd --name bad_parent bad_parent /bin/bash`
2) run `docker exec bad_parent date` on a loop to show that the container is responsive
3) create a zombie pid
```
#!/usr/bin/env python
import os
import subprocess
import time


pid = os.fork()
if pid == 0:  # child
    # time.sleep(100)
    pid2 = os.fork()
    if pid2 != 0:  # parent
        while True:
            print('The zombie pid will be: {}'.format(pid2))
            time.sleep(30)
else:  # parent
    # os.waitpid(pid, 0)
    subprocess.check_call(('ps', 'xawuf'))
    time.sleep(5)
```
4) observe that the container stops responding

I've tried the latest containerd (compiled from git source). I've tried 18.09, but haven't been able to build rpms for 18.10 (build errors) from master. Any thoughts on where to go with this?

Here are the log files (in debug) for the issue: https://gist.github.com/cwpenhale/2eb23ffcb2abd2b4fccc509a50f2fd0a

Testing with the following host, virtualized in VirtualBox:
```
[root@localhost docker_exec_hang_issue]# uname -a
Linux localhost.localdomain 5.1.5-1.el7.elrepo.x86_64 #1 SMP Sat May 25 16:10:51 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost docker_exec_hang_issue]# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 
```

### PR DESCRIPTION
**Pull request by crosbymichael**
fixes https://github.com/moby/moby/issues/39326

This is the second part to
https://github.com/containerd/containerd/pull/3361 and will help process
delete not block forever when the process exists but the I/O was
inherited by a subprocess that lives on.

Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
addresses https://github.com/containerd/containerd/issues/3286 docker exec hang if earlier docker exec left a zombie process


@crosbymichael does this also relate to;

- https://github.com/moby/moby/issues/38978 Zombie reaping not occurring as expected
- https://github.com/moby/moby/issues/38978 docker cannot terminate a container when processes linger after TERM


Should we have a test-case for this? (not sure if it's easy to test)

File: container/stream/streams.go [hunk 1]
```diff
@@ -144,3 +147,20 @@ func (c *Config) CopyToPipe(iop *cio.DirectIO) {
 		}
 	}
 }
+
+func (c *Config) Wait(ctx context.Context) {
```
Comment (thaJeztah) [inline container/stream/streams.go]: Oh; linting failure;

```
20:37:38 container/stream/streams.go:151:1:warning: exported method Config.Wait should have comment or be unexported (golint)
20:37:41 Build step 'Execute shell' marked build as failure
```

**Review by thaJeztah — CHANGES_REQUESTED** [review]

**Comment by thaJeztah** [comment]
Haven't seen this one before; https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS1/25656/console

```
21:06:29 FAIL: docker_cli_exec_test.go:538: DockerSuite.TestExecWindowsOpenHandles
21:06:29
21:06:29 assertion failed: 2 (int) != 1 (int)
```


I'll kick CI for RS1 to see if it was just flaky

**Comment by crosbymichael** [comment]
I read through that test and its depending on the "bad" functionality, forking off the sleeps into the background and the actually cmd.exe is exiting. I think it's safe for this test to be removed with this change as well as the test is horribly racy and depending on how many seconds the sleeps wait until they exit, its bad!

**Review by thaJeztah — APPROVED** [review]
SGTM

@kolyshkin @dmcgowan PTAL

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by cpuguy83** [comment]
I/O waiters seems like a good candidate for metrics as well.
