### PR TITLE
Natively support gRPC on the docker socket

### LINKED ISSUE #44369: Proposal: c8d: expose contentstore API
### Description

Currently, the only way to load and save images in/from Docker is to use `docker save/load` commands that require a tarball to be created that contains all layers and manifests of the image.

For example, when doing builds and loading the build result into Docker, this full tarball needs to be created by the builder and transferred to Docker which then extracts it on disk before processing it. When doing these builds repeatedly, usually only a couple of these layers actually change but because of the inefficiency of this API full tarball needs to be transferred every time even though eventually Docker will discard most of it.

A similar case appears when you would want to transfer an image from one Docker instance to another(without a registry in between). If the target Docker instance already has the older version of the image and just needs an updated version it is again likely that only one layer actually needs to be exported from the daemon and imported on the other side. But no API exists today that would allow running this efficiently.

With the move to containerd image backend that is currently in progress, we have some new options to solve this issue. I propose exposing containerd's contentstore API https://pkg.go.dev/github.com/containerd/containerd@v1.6.9/api/services/content/v1#ContentServer so it can be used with Docker, but do it in a safe manner.

These APIs allow creating individual blobs in content-addressable storage, checking if blob with a specific digest already exists and pulling the blob's contents.

We can use the existing `/grpc` endpoint that can be upgraded to gRPC connection(currently used by BuildKit).

Containerd APIs on their own are unsafe, and calling them with incorrect parameters can completely corrupt the internal storage, delete objects that are in use by other users, or leak objects forever, so they never release their storage. These cases should be avoided by the Docker API.

Before client would call the content API methods it would need to make a call that creates a **lease** Leases and GC labels are how containerd controls what objects can be deleted by the GC. All the subsequent content API calls need to contain a lease ID and will error otherwise. A lease has a timeout (for example 10 min by default). If client needs more time to finish its transactions, it can ask for the timeout to be extended. If the client crashes and terminates the connection to the daemon all objects associated with the lease get their reference count reduced when the timeout is reached. If the reference count reaches 0, the object is deleted by containerd GC.

With the lease, client can check which blobs daemon already knows about. If it needs to, it can upload the newer blobs that remain associated with the lease. Blobs containing the image manifest and config are uploaded in the same way. Finally, client will make a `CreateImage()` call that contains the digest of the root manifest(either image manifest or manifest index for multi-platform). This method will validate that the digest points to a valid manifest with all layers present in contentstore and create a new record under `docker images`. Now all the blobs are associated with the image itself and the lease is not needed anymore to keep the blobs from getting deleted.

For safety, the `Delete()` method in contentstore API in Moby is completely disabled. Only way to manage storage is to create leases and delete them.

These APIs enable clients to efficiently create new images when the daemon already knows about some of the layers(iterative builds, deployments) as well as only export the layers the client needs out of the image instead of downloading the full `docker save` tarball.

@rumpl @AkihiroSuda

### PR DESCRIPTION
**Pull request by dmcgowan**
- relates to / addresses https://github.com/moby/moby/issues/49836
- relates to https://github.com/moby/buildkit/issues/5927

Adds support for directly serving the gRPC server on the Docker socket. The requests can be easily detected from the content-type and use of HTTP 2.  Explicitly adds the HTTP 2 protocol when using tcp+tls or unencrypted HTTP 2 when using a unix socket.

Only registers the buildkit service, which will allow deprecating the hijacking `/session` and `/grpc` endpoints. In the future, we can register more services using containerd style plugins.

**- Human readable description for the release notes**

```markdown changelog
Natively support gRPC on the listening socket
```

### CODE REVIEW

File: integration/build/build_traces_test.go [hunk 1]
```diff
@@ -34,15 +34,8 @@ func TestBuildkitHistoryTracePropagation(t *testing.T) {
 	ctx := testutil.StartSpan(baseContext, t)
 
 	c := testEnv.APIClient()
-	opts := []client.ClientOpt{
-		client.WithSessionDialer(func(ctx context.Context, proto string, meta map[string][]string) (net.Conn, error) {
-			return c.DialHijack(ctx, "/session", proto, meta)
-		}),
-		client.WithContextDialer(func(ctx context.Context, _ string) (net.Conn, error) {
-			return c.DialHijack(ctx, "/grpc", "h2c", nil)
-		}),
```
Comment (thaJeztah) [inline integration/build/build_traces_test.go:43]: Do we need to keep the `/grpc` and `/session` endpoints? IIUC removing these means that any existing version of buildx or the CLI will break?

Comment (thaJeztah) [reply integration/build/build_traces_test.go:43]: Oh, ignore me; this is client-side 🙈 

I guess clients should still try both to stay compatible, right?

**Comment by thaJeztah** [comment]
This failure looks potentially related;

```
=== RUN   TestDockerDaemonSuite/TestTLSVerify
    docker_cli_daemon_test.go:708: Daemon should not have started due to missing certs: exit status 2
        panic: runtime error: invalid memory address or nil pointer dereference
        [signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x55aaeba7cbfa]

```

<details>

```
=== RUN   TestDockerDaemonSuite/TestTLSVerify
    docker_cli_daemon_test.go:708: Daemon should not have started due to missing certs: exit status 2
        panic: runtime error: invalid memory address or nil pointer dereference
        [signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x55aaeba7cbfa]
        
        goroutine 1 [running, locked to thread]:
        github.com/moby/moby/v2/daemon/command.newAPIServerTLSConfig(0xc0001db700?)
        	/go/src/github.com/docker/docker/daemon/command/daemon.go:822 +0x15a
        github.com/moby/moby/v2/daemon/command.newDaemonCLI(0xc0001db700)
        	/go/src/github.com/docker/docker/daemon/command/daemon.go:90 +0x33
        github.com/moby/moby/v2/daemon/command.newDaemonCommand.func1(0xc000576008, {0xc0002d2940?, 0x7?, 0x55aaebafb48e?})
        	/go/src/github.com/docker/docker/daemon/command/docker.go:35 +0x65
        github.com/spf13/cobra.(*Command).execute(0xc000576008, {0xc0000500f0, 0x1, 0x1})
        	/go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:1015 +0xaaa
        github.com/spf13/cobra.(*Command).ExecuteC(0xc000576008)
        	/go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:1148 +0x46f
        github.com/spf13/cobra.(*Command).Execute(...)
        	/go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:1071
        github.com/spf13/cobra.(*Command).ExecuteContext(...)
        	/go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:1064
        github.com/moby/moby/v2/daemon/command.daemonRunner.Run({0x55aaec77d9d8?}, {0x55aaec7acfd0, 0x55aaede48200})
        	/go/src/github.com/docker/docker/daemon/command/docker.go:111 +0x6e
        main.main()
        	/go/src/github.com/docker/docker/cmd/dockerd/main.go:38 +0x126
        
        goroutine 8 [select]:
        go.opencensus.io/stats/view.(*worker).start(0xc0004dab00)
        	/go/src/github.com/docker/docker/vendor/go.opencensus.io/stats/view/worker.go:292 +0x9f
        created by go.opencensus.io/stats/view.init.0 in goroutine 1
        	/go/src/github.com/docker/docker/vendor/go.opencensus.io/stats/view/worker.go:34 +0x8d
        
        goroutine 43 [select]:
        io.(*pipe).read(0xc000113980, {0xc000610000, 0x10000, 0x0?})
        	/usr/local/go/src/io/pipe.go:57 +0xa5
        io.(*PipeReader).Read(0xc0004d9e08?, {0xc000610000?, 0x55aaede4b880?, 0xc0004d9e60?})
        	/usr/local/go/src/io/pipe.go:134 +0x1a
        bufio.(*Scanner).Scan(0xc0004d9f28)
        	/usr/local/go/src/bufio/scan.go:219 +0x81e
        github.com/sirupsen/logrus.(*Entry).writerScanner(0xc0001acf50, 0xc000113980, 0xc0002d2550)
        	/go/src/github.com/docker/docker/vendor/github.com/sirupsen/logrus/writer.go:86 +0x11d
        created by github.com/sirupsen/logrus.(*Entry).WriterLevel in goroutine 1
        	/go/src/github.com/docker/docker/vendor/github.com/sirupsen/logrus/writer.go:57 +0x31f
        
        goroutine 42 [select]:
        io.(*pipe).read(0xc000113920, {0xc00058c000, 0x10000, 0x0?})
        	/usr/local/go/src/io/pipe.go:57 +0xa5
        io.(*PipeReader).Read(0xc0004d8e08?, {0xc00058c000?, 0xc0005cc000?, 0xc0004d8e60?})
        	/usr/local/go/src/io/pipe.go:134 +0x1a
        bufio.(*Scanner).Scan(0xc0004d8f28)
        	/usr/local/go/src/bufio/scan.go:219 +0x81e
        github.com/sirupsen/logrus.(*Entry).writerScanner(0xc0001acf50, 0xc000113920, 0xc0002d2540)
        	/go/src/github.com/docker/docker/vendor/github.com/sirupsen/logrus/writer.go:86 +0x11d
        created by github.com/sirupsen/logrus.(*Entry).WriterLevel in goroutine 1
        	/go/src/github.com/docker/docker/vendor/github.com/sirupsen/logrus/writer.go:57 +0x31f
        
        goroutine 44 [select]:
        io.(*pipe).read(0xc0001139e0, {0xc000680000, 0x10000, 0x0?})
        	/usr/local/go/src/io/pipe.go:57 +0xa5
        io.(*PipeReader).Read(0xc0004d4608?, {0xc000680000?, 0x55aaede4b880?, 0xc0004d4660?})
        	/usr/local/go/src/io/pipe.go:134 +0x1a
        bufio.(*Scanner).Scan(0xc000094f28)
        	/usr/local/go/src/bufio/scan.go:219 +0x81e
        github.com/sirupsen/logrus.(*Entry).writerScanner(0xc0001acf50, 0xc0001139e0, 0xc0002d2570)
        	/go/src/github.com/docker/docker/vendor/github.com/sirupsen/logrus/writer.go:86 +0x11d
        created by github.com/sirupsen/logrus.(*Entry).WriterLevel in goroutine 1
        	/go/src/github.com/docker/docker/vendor/github.com/sirupsen/logrus/writer.go:57 +0x31f
```

</details>

**Comment by thaJeztah** [comment]
Looks like this requires updating the `github.com/moby/moby/v2` module to use `go1.24` as minimum;

```
INFO [runner] linters took 2m14.274822457s with stages: goanalysis_metalinter: 2m14.21043666s 
daemon/command/daemon.go:313:14: stdversion: http.Protocols requires go1.24 or later (file is go1.23) (govet)
		httpServer.Protocols = &p
		           ^
daemon/command/daemon.go:318:14: stdversion: http.Protocols requires go1.24 or later (file is go1.23) (govet)
		httpServer.Protocols = &p
		           ^
daemon/command/httphandler.go:73:84: stdversion: http.Protocols requires go1.24 or later (file is go1.23) (govet)
func supportGRPC(ctx context.Context, lss []net.Listener, hasTLS bool) (bool, http.Protocols) {
                                                                                   ^
daemon/command/httphandler.go:74:13: stdversion: http.Protocols requires go1.24 or later (file is go1.23) (govet)
	var p http.Protocols
	           ^
```

From https://github.com/moby/moby/issues/49836#issuecomment-2864104423, I saw that @corhere originally suggested some approach through `golang.org/x/net`, but not sure if that would allow working without go1.24;


> It would be trivial for us to support HTTP/2 with Prior Knowledge – and also properly support the deprecated `Upgrade: h2c` mechanism in a way that actually complies with RFC 7540 Section 3.2 by wrapping the daemon's HTTP handler in https://pkg.go.dev/golang.org/x/net@v0.40.0/http2/h2c

Also;

https://github.com/moby/moby/issues/49836#issuecomment-2864386119

> > I suspected the Upgrade connected more directly with a grpc-go server, and that's why it needed to be POST specifically to `/grpc`
>
> It's more straightforward than that. We [implemented the h2c upgrade incorrectly](https://github.com/moby/moby/blob/6f477852a1d43941afc37901597ec21edd11a342/api/server/router/grpc/grpc_routes.go) and [added it as a route to the HTTP server mux](https://github.com/moby/moby/blob/6f477852a1d43941afc37901597ec21edd11a342/api/server/router/grpc/grpc.go#L57-L61) instead of wrapping the HTTP server mux like we should have.

**Comment by thaJeztah** [comment]
I pushed a commit to update the Go version in `go.mod` so that CI can run with that change.

**Comment by corhere** [comment]
100% using golang.org/x/net like I suggested would not require bumping the go version. And I would still prefer that approach over open-coding it again since we got it wrong open-coding it the first time around.

File: integration/build/build_traces_test.go (hunk 1 above)
Comment (dmcgowan) [reply integration/build/build_traces_test.go:43]: https://github.com/docker/buildx/pull/3369 handles both, I don't know if any other clients are using and if we can just safely deprecate those endpoints since using them requires a very delicate dance.

Comment (thaJeztah) [reply integration/build/build_traces_test.go:43]: Basically any version of buildx that currently exists; i.e., we can't remove the old endpoints, as they're part of the API

**Comment by dmcgowan** [comment]
> 100% using golang.org/x/net like I suggested would not require bumping the go version. 

1.23 is deprecated, the min version will get bumped as soon as we vendor in a project which bumps it (containerd 2.2 or anything that has a transitive Kubernetes dep)

> And I would still prefer that approach over open-coding it again since we got it wrong open-coding it the first time around.

Can you explain this one further. I usually think the preferred solution is using the standard library as the Go maintainers have encouraged not using those lower level libraries. "This package is low-level and intended to be used directly by very few people", we aren't doing anything that special here. Not sure what "over open-coding it again" refers to or how it relates to the existing hijack approach, which I think we all agree isn't great.

**Comment by akerouanton** [comment]
I’ve rebased this PR and removed the `supportGRPC` function, which previously determined whether gRPC and h2c were enabled. h2c is now always enabled.

When a TLS listener receives a connection, it returns an error if the handshake can’t be completed. As a result, h2c won’t be used for TLS listeners, but it will be used for non-TLS TCP connections and the UNIX socket.

In the previous iteration, gRPC was disabled when running the dev container with the API exposed over TCP. This is now resolved.

File: daemon/command/daemon.go [hunk 2]
```diff
@@ -306,13 +306,23 @@ func (cli *daemonCLI) start(ctx context.Context) (err error) {
...
+
 	routers := buildRouters(routerOptions{
 		features: d.Features,
 		daemon:   d,
 		cluster:  c,
 		builder:  b,
 	})
-	httpServer.Handler = apiServer.CreateMux(ctx, routers...)
+	gs := newGRPCServer(ctx)
+	b.backend.RegisterGRPC(gs)
```
Comment (vvoland) [inline daemon/command/daemon.go:323]: Note: This will implicitly expose the containerd content store via buildkit:

https://github.com/moby/moby/blob/c64b781df2387bea01720a3a3411f7d29dd40ea8/vendor/github.com/moby/buildkit/control/control.go#L164

It's read-only so that's good, but we should make that explicitly registered by the Moby and not implicitly by Buildkit.

**Review by vvoland — APPROVED** [review]
LGTM

File: integration/build/build_traces_test.go (hunk 1 above)
Comment (ndeloof) [reply integration/build/build_traces_test.go:43]: Could we use HTTP `301 Moved Permanently` for legacy clients to switch to the updated endpoint?

Comment (thaJeztah) [reply integration/build/build_traces_test.go:43]: FWIW; this is only the test, not the endpoint being removed (🙈); so probably fine, but we can consider officially deprecating the old endpoints

**Review by thaJeztah — APPROVED** [review]
LGTM

File: daemon/command/daemon.go (hunk 2 above)
Comment (vvoland) [reply daemon/command/daemon.go:323]: @copilot can you open a ticket for this

Comment (vvoland) [reply daemon/command/daemon.go:323]: thanks for nothing @copilot! I did it myself: https://github.com/moby/moby/issues/51698

**Review by sssalrawahi9-coder — APPROVED** [review]

**Review by sssalrawahi9-coder — APPROVED** [review]
