### PR TITLE
Windows: Terminate on failed shutdown, fixes dockerd deadlock

### LINKED ISSUE #22543: Windows libcontainerd should call TerminateComputeSystem on failed ShutdownComputeSystem
**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.Start Hyper-v container 
2. Make sue container bugcheck
3. Now query the containers using docker ps command 

**Describe the results you received:**
The command hangs.

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

Fixes #22543 

Found on an internal test run against Hyper-V containers. Dockerd can become unresponsive (deadlocked on a container lock) to any CLI call which needs to take the same individual container lock (eg `docker ps`, `docker stop` on the container) if Windows gets into a  situation where the it returns an unexpected failure from the vmcompute `ShutdownComputeSystem` call. This may happen for example if HCS become out of sync with GCS, or the utility VM crashes.

@swernli

### CODE REVIEW

File: libcontainerd/client_windows.go [hunk 1]
```diff
@@ -362,7 +362,19 @@ func (clnt *client) Signal(containerID string, sig int) error {
...
-		if err := hcsshim.ShutdownComputeSystem(containerID, hcsshim.TimeoutInfinite, context); err != nil {
+		const shutdownTimeout = 5 * 60 * 1000 // 5 minutes
+		if err := hcsshim.ShutdownComputeSystem(containerID, shutdownTimeout, context); err != nil {
+			if herr, ok := err.(*hcsshim.HcsError); !ok ||
+				(herr.Err != hcsshim.ERROR_SHUTDOWN_IN_PROGRESS &&
+					herr.Err != ErrorBadPathname &&
+					herr.Err != syscall.ERROR_PATH_NOT_FOUND) {
+				logrus.Warnf("signal - error from ShutdownComputeSystem %s. Calling TerminateComputeSystem", err)
+				if err := hcsshim.TerminateComputeSystem(containerID, shutdownTimeout, "signal"); err != nil {
+					logrus.Warnf("signal - ignoring error from TerminateComputeSystem %s.", err)
```
Comment (LK4D4) [inline libcontainerd/client_windows.go]: we usually using %v for errors and also doesn't end log messages with `.`

Comment (jhowardmsft) [inline libcontainerd/client_windows.go]: Updated (in both files)

**Comment by swernli** [comment]
LGTM

**Comment by thaJeztah** [comment]
Flaky test, or network hiccup?

https://jenkins.dockerproject.org/job/Docker-PRs-experimental/18354/console

https://jenkins.dockerproject.org/job/Docker-PRs-gccgo/5186/console


```
----------------------------------------------------------------------
FAIL: docker_cli_pull_test.go:201: DockerHubPullSuite.TestPullAllTagsFromCentralRegistry

docker_cli_pull_test.go:208:
    s.Cmd(c, "pull", "--all-tags=true", "busybox")
docker_hub_pull_suite_test.go:73:
    c.Assert(err, checker.IsNil, check.Commentf("%q failed with errors: %s, %v", strings.Join(arg, " "), out, err))
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc82301c020)} ("exit status 1")
... "--all-tags=true busybox" failed with errors: 1-glibc: Pulling from library/busybox
```

**Comment by jhowardmsft** [comment]
Looks like a blip - this change doesn't affect Linux at all...

**Comment by thaJeztah** [comment]
Yeah, just saw the same thing on a couple other PR's so, not related to this PR at least

File: libcontainerd/client_windows.go [hunk 2]
```diff
@@ -362,7 +362,19 @@ func (clnt *client) Signal(containerID string, sig int) error {
...
+		if err := hcsshim.ShutdownComputeSystem(containerID, shutdownTimeout, context); err != nil {
+			if herr, ok := err.(*hcsshim.HcsError); !ok ||
+				(herr.Err != hcsshim.ERROR_SHUTDOWN_IN_PROGRESS &&
+					herr.Err != ErrorBadPathname &&
+					herr.Err != syscall.ERROR_PATH_NOT_FOUND) {
+				logrus.Warnf("signal - error from ShutdownComputeSystem %v. Calling TerminateComputeSystem", err)
+				if err := hcsshim.TerminateComputeSystem(containerID, shutdownTimeout, "signal"); err != nil {
+					logrus.Warnf("signal - ignoring error from TerminateComputeSystem %v", err)
+				} else {
+					logrus.Infof("Successful TerminateComputeSystem after failed ShutdownComputeSystem on %s during signal %v", containerID, sig)
```
Comment (cpuguy83) [inline libcontainerd/client_windows.go]: Seems like a `Debugf` at best, but probably not needed at all?

File: libcontainerd/client_windows.go [hunk 3]
```diff
@@ -362,7 +362,19 @@ func (clnt *client) Signal(containerID string, sig int) error {
...
-		if err := hcsshim.ShutdownComputeSystem(containerID, hcsshim.TimeoutInfinite, context); err != nil {
+		const shutdownTimeout = 5 * 60 * 1000 // 5 minutes
+		if err := hcsshim.ShutdownComputeSystem(containerID, shutdownTimeout, context); err != nil {
+			if herr, ok := err.(*hcsshim.HcsError); !ok ||
+				(herr.Err != hcsshim.ERROR_SHUTDOWN_IN_PROGRESS &&
+					herr.Err != ErrorBadPathname &&
+					herr.Err != syscall.ERROR_PATH_NOT_FOUND) {
+				logrus.Warnf("signal - error from ShutdownComputeSystem %v. Calling TerminateComputeSystem", err)
+				if err := hcsshim.TerminateComputeSystem(containerID, shutdownTimeout, "signal"); err != nil {
+					logrus.Warnf("signal - ignoring error from TerminateComputeSystem %v", err)
```
Comment (cpuguy83) [inline libcontainerd/client_windows.go]: Will be helpful to make sure the container ID is included here.
Also is this a real warning or can it be debug?

File: libcontainerd/client_windows.go (hunk 2 above)
Comment (jhowardmsft) [inline libcontainerd/client_windows.go]: This is a warn. Changing

File: libcontainerd/client_windows.go (hunk 3 above)
Comment (jhowardmsft) [inline libcontainerd/client_windows.go]: Yeah, these can go to debug. Changing. And including ID - good idea :+1:

File: libcontainerd/client_windows.go (hunk 2 above)
Comment (jhowardmsft) [inline libcontainerd/client_windows.go]: Still a useful debugf

File: libcontainerd/client_windows.go (hunk 3 above)
Comment (jhowardmsft) [inline libcontainerd/client_windows.go]: Updated.

**Comment by LK4D4** [comment]
LGTM
