### PR TITLE
Wait for container dependencies upon daemon start up

### LINKED ISSUE #50326: Containers with "restart: always" and shared network namespace may fail to start with "cannot join network namespace of a non running container"
### Description

When using the `restart: always` policy in combination with network_mode: "container:<container_name>", containers can fail to start after a reboot or Docker daemon restart if the target container is not yet running. This results in errors like:

`Error response from daemon: cannot join network namespace of a non running container: container <container_name> is exited`

This seems to be a race condition depending on the startup order of containers after a system reboot or Docker restart. Even with `restart: always`, containers relying on another container’s network namespace may end up permanently exited unless manually restarted.

### Reproduce

1. Create a "network host" container:

```
services:
  net-host:
    image: alpine
    command: sleep infinity
    restart: always
```

2. Create another container that uses the first container’s network namespace:

```
services:
  net-client:
    image: alpine
    command: sleep infinity
    network_mode: "container:net-host"
    restart: always
```

3. Deploy the stack or start both containers with Docker Compose or manually.

4. Reboot the host or restart the Docker daemon:

`sudo systemctl restart docker`

### Expected behavior

All containers with `restart: always` should come back up reliably, respecting dependencies implied by network_mode.

### docker version

```bash
Client: Docker Engine - Community
 Version:           28.3.1
 API version:       1.51
 Go version:        go1.24.4
 Git commit:        38b7060
 Built:             Wed Jul  2 20:56:22 2025
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          28.3.1
  API version:      1.51 (minimum version 1.24)
  Go version:       go1.24.4
  Git commit:       5beb93d
  Built:            Wed Jul  2 20:56:22 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.27
  GitCommit:        05044ec0a9a75232cad458027ca83437aae3f4da
 runc:
  Version:          1.2.5
  GitCommit:        v1.2.5-0-g59923ef
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    28.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.25.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.38.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 5
  Running: 4
  Paused: 0
  Stopped: 1
 Images: 38
 Server Version: 28.3.1
 Storage Driver: overlayfs
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 CDI spec directories:
  /etc/cdi
  /var/run/cdi
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05044ec0a9a75232cad458027ca83437aae3f4da
 runc version: v1.2.5-0-g59923ef
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-60-generic
 Operating System: Ubuntu 22.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.02GiB
 Name: adrien-Latitude-5420
 ID: RGG6:FFJ6:VQQE:4GZH:AJCY:YEHD:ZMEW:47X4:KEBD:NAJZ:265M:BCFE
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by Adrien-Atmosphere**
- Fixes: #50326

**- What I did**
Wait for container dependencies upon daemon start up 

**- How I did it**
- List all dependent containers upon registration
- Dependent containers can be either from legacy link or container network
- Wait on a best effort basis for the dependent containers

**- How to verify it**
 1. Create a docker-dind container with bind mounted /var/lib/docker : 
`docker run -d --privileged --name docker -v ./docker:/var/lib/docker docker-dind:latest --debug`
 
 2. Launch a compose application that creates 500 containers in docker-dind image to maximize the chances to encounter the issue
```
services:
  net:
    image: alpine
    command: sleep infinity
    restart: always

  app:
    image: alpine
    command: sleep infinity
    network_mode: "service:net"
    restart: always
    scale: 500

```

3. Stop and restart the docker-dind container and check for stopped containers 
```
CONTAINER=docker
EXEC="docker exec $CONTAINER"
while true;
do 
	echo "Stopping $CONTAINER"
	docker stop $CONTAINER
	echo "Removing $CONTAINER" 
	docker rm -v $CONTAINER
	echo "Starting $CONTAINER"
        docker run -d --privileged --name docker -v ./docker:/var/lib/docker docker-dind:latest --debug
	timeout 30 bash -c "until $EXEC docker info >/dev/null 2>&1; do sleep 1; done"
	echo "$CONTAINER started successfully"

	containers=$($EXEC docker ps -aq   --filter status=created   --filter status=exited   --filter status=dead)
        if [ -n "$containers" ]
	then 
    		echo "Inspecting stopped/exited/dead containers:"
    		for i in $containers; do
		      echo "Container ID: $i"
		      $EXEC docker inspect "$i" -f "{{ .State | json }}" | jq
	        done
		exit 
	else
		echo "No created/exited/dead containers found."
	fi
done 
```

**- Human readable description for the release notes**
```markdown changelog
- On daemon startup, restart containers that share their network stacks before containers that need those stacks.
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks for contributing. This may need some review/discussion; I'm a bit concerned about possible consequences of this - at least it could use more eyes.


Currently, we create somewhat of a hard dependency when joining namespaces with another container; while this "works", it's also causing issues (like the one this PR is trying to address). Ultimately, we should try to make things more dynamic and resilient against situations where (e.g.) the linked container is restarted, removed, fails to start, or otherwise; we could still have some dependency, but ideally, it would be more dynamic.

For the legacy-links, it's definitely something we want to move away from; it's a broken concept, has security implications, and has many limitations and side-effects (also see https://github.com/moby/moby/issues/22295); non-legacy (DNS-based) links are more flexible in this respect.

The `--network=container:XX` is something we should look at, and possibly re-architect (I recall I brought this idea up in some discussions we had, but never wrote it up; I'll probably write up something in a separate ticket for further discussion).


Effectively, `--network=container:XX` indicates that a container wants to share its networking-namespace with an existing network-namespace; in this case a namespace that was created as part of another container. 

- container-A is created, and a network namespace is created for it
- container-B -> network=container-A (IOW: "share network-namespace with container A") joins the network namespace that was created for container-A
- container-A and container-B now both use the same network namespace

For convenience (and UX), it uses the `--network` flag, but to some extent it's a bit of an odd-one-out; for other namespaces, we use a flag more specific to "namespace". From the `docker run --help` output;

```console
--pid string                       PID namespace to use
--userns string                    User namespace to use
--uts string                       UTS namespace to use
```

While the original "donor" container is required when creating the container to join its networking namespace, ultimately that's only when _creating_ the container. Currently we still consider that namespace to be owned by the original container, but I think we should consider it more closely to a "co-ownership". _Both_ containers share the same namespace, and we can consider the namespace to be no longer needed once the last container is gone.

If we take that approach, things become more similar to, for example, `--volumes-from`; 

```console
--volumes-from list                Mount volumes from the specified container(s)
```

Similar to `--network=container:XXX`,  the container using the `--volumes-from` option needs the donor container to exist when creating. Volumes are created (or defined) on the donor's container, but 


```bash
docker run -d -v shared:/foo --name container-a nginx:alpine
docker run -d --volumes-from=container-a --name container-b nginx:alpine
```

But once created, there's no longer a hard dependency; container-b now just shares the same volume(s);

```bash
docker system df --verbose
...
Local Volumes space usage:

VOLUME NAME                                                        LINKS     SIZE
docker-dev-cache                                                   1         2.209GB
shared                                                             2         0B
acd3650aa324548e56d29276001b13c8ad7e493a881b63106aaec0b6be542e9d   0         3.997MB
```

The original "donor" container (`container-a`) can be removed without impacting `container-b`;

```bash
docker container rm -f container-a
container-a

docker system df --verbose
...
Local Volumes space usage:

VOLUME NAME                                                        LINKS     SIZE
docker-dev-cache                                                   1         2.209GB
shared                                                             1         0B
acd3650aa324548e56d29276001b13c8ad7e493a881b63106aaec0b6be542e9d   0         3.997MB
```

I'm wondering if we could get to a similar state for networking; the devil may be in the detail though!

**Comment by Adrien-Atmosphere** [comment]
Thank you for your feedback. I thought it could be useful to have a simple "wait on dependent containers" functionality to have the possibility in the future to add a flag "--depends_on" like in docker compose. 
I understand that you would prefer to rework completely the container network namespace sharing functionality. In that case, adding the possibility to make them work with linux "ip netns" would be great.

**Comment by robmry** [comment]
I'll take a more detailed look at the code if we can agree this change is needed - but, I think it is ...

@thaJeztah - as you say, un-hooking netns's is probably a separate discussion ... but, as you also say, the container that shares its netns would need to start first - even if we allow it to exit before its dependents and leave its netns behind. (Maybe the first container has CAP_NET_ADMIN and needs to do some setup before other containers arrive.) So, we'd still need restart dependencies like this? (At least on initial startup, maybe we could allow a restart without the dependency if another container sharing the netns has held it open - but that's about design for a future feature, and this change wouldn't hold it back.)

At the moment - if containers with netns dependencies don't necessarily restart when they should, that's a bug. Even if we want to re-design the way container-networking works in future, it should work properly until then. The mechanism for queuing container-starts exists, this change adds a missing dependency. I think it makes sense?

**Comment by akerouanton** [comment]
I think this PR makes sense overall. As @robmry outlined, whether we want to rearchitect `--network=container:…` is a separate matter, and until we settle on that, we should treat the restart scenario as a bug that should be fixed.

**Comment by robmry** [comment]
(The Windows test failures are unrelated to this PR.)

File: daemon/container.go [hunk 1]
```diff
@@ -196,6 +197,53 @@ func (daemon *Daemon) GetByName(name string) (*container.Container, error) {
 	return e, nil
 }
 
+// GetDependentContainers returns a list of containers that depend on the given container.
+func (daemon *Daemon) GetDependentContainers(c *container.Container) []*container.Container {
+	// This function is used to retrieve the containers that depend on the given container.
+	// It is used to determine which containers need to be restarted when the given container is restarted.
+	// It returns a list of containers that depend on the given container.
+	// Upon error, it returns the last known dependent containers, which may be empty.
+	dependentContainers := make([]*container.Container, 0)
```
Comment (corhere) [inline daemon/container.go]: Nit: https://go.dev/wiki/CodeReviewComments#declaring-empty-slices
```suggestion
	var dependentContainers []*container.Container
```

File: daemon/container.go [hunk 2]
```diff
@@ -196,6 +197,53 @@ func (daemon *Daemon) GetByName(name string) (*container.Container, error) {
...
+				}
+				log.G(context.TODO()).WithError(err).Errorf("Could not get container for %s", name)
+				return dependentContainers
+			}
+
+			dependentContainers = append(dependentContainers, child)
+		}
+	}
+	return dependentContainers
+
```
Comment (corhere) [inline daemon/container.go]: There's a more efficient way to do this.
```suggestion
	return append(dependentContainers, maps.Values(daemon.linkIndex.children(c)))

```

File: daemon/container.go [hunk 3]
```diff
@@ -196,6 +197,53 @@ func (daemon *Daemon) GetByName(name string) (*container.Container, error) {
 	return e, nil
 }
 
+// GetDependentContainers returns a list of containers that depend on the given container.
+func (daemon *Daemon) GetDependentContainers(c *container.Container) []*container.Container {
+	// This function is used to retrieve the containers that depend on the given container.
+	// It is used to determine which containers need to be restarted when the given container is restarted.
+	// It returns a list of containers that depend on the given container.
+	// Upon error, it returns the last known dependent containers, which may be empty.
```
Comment (corhere) [inline daemon/container.go]: How come this isn't part of the function's doc comment?

File: daemon/daemon.go [hunk 4]
```diff
@@ -575,8 +577,8 @@ func (daemon *Daemon) restore(cfg *configStore) error {
 			logger.Debug("starting container")
 
 			// ignore errors here as this is a best effort to wait for children
-			// (legacy links) to be running before we try to start the container
-			if children := daemon.linkIndex.children(c); len(children) > 0 {
+			// (legacy links or container network) to be running before we try to start the container
+			if children := dependentContainers[c]; len(children) > 0 {
```
Comment (corhere) [inline daemon/daemon.go]: Accumulating the dependent containers into a map doesn't really afford us anything, at the cost of some memory.
```suggestion
			if children := daemon.GetDependentContainers(c); len(children) > 0 {
```

**Review by corhere — COMMENTED** [review]
I agree that this change makes a lot of sense. The PR could use another iteration, though.

**Review by robmry — COMMENTED** [review]
Looks good - thank you ... but please could you squash the commits? Looks like it needs a rebase too, just a conflict in imports.

**Comment by robmry** [comment]
Looks like something odd happened in the rebase, an already merged commit ended up in this PR?

**Comment by Adrien-Atmosphere** [comment]
Thanks, I didn't notice

**Review by corhere — APPROVED** [review]
LGTM!

**Comment by robmry** [comment]
There's a test failure in https://github.com/moby/moby/actions/runs/16349928056/job/46194686893?pr=50327 ...
```
# github.com/docker/docker/daemon
../../daemon/container.go:223:52: implicit function instantiation requires go1.18 or later (-lang was set to go1.16; check go.mod)
```

That means we need this comment at the top of `daemon/container.go` (because of the templated slices/maps functions) ...
```
// FIXME(thaJeztah): remove once we are a module; the go:build directive prevents go from downgrading language version to go1.16:
//go:build go1.23
```

**Comment by robmry** [comment]
I've added a changelog comment to the description - hopefully it makes sense?!

**Comment by Adrien-Atmosphere** [comment]
For the comment at the top of container.go, do I make a separate commit or do I squash them?

**Comment by robmry** [comment]
> For the comment at the top of container.go, do I make a separate commit or do I squash them?

Squash please!

**Comment by robmry** [comment]
Sorry this is getting a bit tedious - nearly there, but ...

```
daemon/container.go:1:1: File is not properly formatted (gofmt)
// FIXME(thaJeztah): remove once we are a module; the go:build directive prevents go from downgrading language version to go1.16:
```

I think it wants a blank like after the build directive ...
```
// FIXME(thaJeztah): remove once we are a module; the go:build directive prevents go from downgrading language version to go1.16:
//go:build go1.23

package daemon
```

**Comment by Adrien-Atmosphere** [comment]
I just did a gofmt -s and it reversed both comments like so  :
```
//go:build go1.23

// FIXME(thaJeztah): remove once we are a module; the go:build directive prevents go from downgrading language version to go1.16:
```
I think I should push this, no?

**Comment by robmry** [comment]
It should be ok the original way around - we've got quite a few of these now (and should be able to remove them soon), so it's best if they're all the same. For example ...

https://github.com/moby/moby/blob/c616e7690f8ea33550038dff8743124ff5621915/daemon/create.go#L1-L5

(Oh, except I see we have a mix of `TODO` and `FIXME`! Either is ok, most are `FIXME`.)

**Review by robmry — APPROVED** [review]
LGTM - thank you @Adrien-Atmosphere!

The BuildKit Windows test failure is unrelated ... I'll get this merged.
