### PR TITLE
Fix `docker inspect <unkown object>` issue on Windows

### LINKED ISSUE #29185: [1.13.0-rc3] docker inspect <foobar> fails on Windows
@anusha-ragunathan 

The plugin infrastructure coming into the engine in 1.13 has regressed `docker inspect <something-that-doesn't-exist>` on Windows.

```
PS E:\docker\build\getenv> docker version
Client:
 Version:      1.13.0-rc3
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        12/06/2016 17:54:56
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-rc3
 API version:  1.25 (minimum version 1.24)
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        12/06/2016 17:54:56
 OS/Arch:      windows/amd64
 Experimental: false
PS E:\docker\build\getenv> docker inspect foobar
[]
Error response from daemon: plugins are not supported on this platform
PS E:\docker\build\getenv>
```

(Found on master, but present in 1.13.0-rc3 as well). Expected to see `Error: no such object: <ID>`

@thaJeztah @vieux FYI

### PR DESCRIPTION
**Pull request by yongtang**
**- What I did**

This fix tries to address the issue raised on #29185 where `docker inspect <unknown object>` on Windows will return:
```
Error response from daemon: plugins are not supported on this platform
```

The reason was that in case `--type` is not specified, `docker inspect` will iterate through different types `container`, `image`, `network`, `plugin` etc. The `plugin` object is the last type to check.

However, as `plugin` is not supported on Windows yet, the error message is not very informative for `plugins are not supported on this platform`.

**- How I did it**

This fix tries to fix the issue by return a `not found` error on unsupported platforms as well for plugin types.

**- How to verify it**

An integration test has been added to cover the changes for Windows/Linux.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

40-beautiful-and-cute-kitten-pictures-2

This fix fixes #29185.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by jhowardmsft** [comment]
Nice! This fixes it. Just one nit, but otherwise LGTM.

```
PS E:\go\src\github.com\docker\docker> docker inspect foobar
[]
Error: No such object: foobar
PS E:\go\src\github.com\docker\docker> docker version
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.3
 Git commit:   7b8d958
 Built:        12/06/2016 19:59:57
 OS/Arch:      windows/amd64

Server:
 Version:      1.14.0-dev
 API version:  1.26 (minimum version 1.24)
 Go version:   go1.7.3
 Git commit:   7b8d958
 Built:        12/06/2016 19:59:57
 OS/Arch:      windows/amd64
 Experimental: false
PS E:\go\src\github.com\docker\docker>
```


@vieux @thaJeztah Marking for 1.13

File: plugin/backend_unsupported.go [hunk 1]
```diff
@@ -24,8 +25,11 @@ func (pm *Manager) Enable(name string, config *types.PluginEnableConfig) error {
 }
 
 // Inspect examines a plugin config
-func (pm *Manager) Inspect(name string) (tp types.Plugin, err error) {
-	return tp, errNotSupported
+func (pm *Manager) Inspect(refOrID string) (tp types.Plugin, err error) {
+	// TODO: Even though plugin is not supported, we still want to return `not found`
```
Comment (jhowardmsft) [inline plugin/backend_unsupported.go]: Should "TODO:" be removed?

Comment (yongtang) [inline plugin/backend_unsupported.go]: Ah yes, there is no `TODO` anymore 😅

**Comment by yongtang** [comment]
Thanks @jhowardmsft for the review. The PR has been updated.

**Comment by jhowardmsft** [comment]
LGTM

**Comment by AkihiroSuda** [comment]
LGTM if CI green

**Comment by jhowardmsft** [comment]
Green. Merging

File: plugin/backend_unsupported.go [hunk 2]
```diff
@@ -24,8 +25,11 @@ func (pm *Manager) Enable(name string, config *types.PluginEnableConfig) error {
 }
 
 // Inspect examines a plugin config
-func (pm *Manager) Inspect(name string) (tp types.Plugin, err error) {
-	return tp, errNotSupported
+func (pm *Manager) Inspect(refOrID string) (tp types.Plugin, err error) {
+	// Even though plugin is not supported, we still want to return `not found`
+	// error so that `docker inspect` (without `--type` specified) returns correct
+	// `not found` message
+	return tp, fmt.Errorf("no such plugin name or ID associated with %q", refOrID)
```
Comment (thaJeztah) [inline plugin/backend_unsupported.go]: Is this the correct change? What happens if I run `docker plugin inspect` on a Windows daemon?

@jhowardmsft ^^

Comment (thaJeztah) [inline plugin/backend_unsupported.go]: The correct fix would probably be to skip `errNotSupported` errors if no `--type` is specified on `docker inspect`; https://github.com/docker/docker/blob/24ffa2fa7751e2f1fbdd7e0d5a640f24e8a5b803/cli/command/system/inspect.go#L131-L133

Comment (yongtang) [inline plugin/backend_unsupported.go]: @thaJeztah @jhowardmsft Yes the change should be made in `docker inspect` part, not the `plugin inspect` part. Sorry about that.

I created another PR #29212 to address `docker plugin inspect` issue. Please take a look.
