### PR TITLE
registry: allow mirror paths in config

### LINKED ISSUE #36598: Docker daemon won't start if a registry-mirror is configured in /etc/docker/daemon.json
**Description**

I have a Nexus 3 docker mirror running in a local server, which my machine points to using /etc/docker/daemon.json. I've tested it a few times, got it working, all good.

However, I was using a ridiculously old version of docker and decided to update it in order to use multistage builds (the version I was using couldn't handle the "AS" alias for stages), in fact, the newest I found(stable).

I completely removed docker, but left the daemon.json there, since I would need it anyway. Installed version 17.12.1 using a ".deb" and it immediately showed an error after the installation was done, showing that docker daemon was unable to start.

When trying to manually start it using dockerd, I got the following message:
>invalid mirror: path, query, or fragment at end of the URI "http://192.168.1.201:8081/repository/docker-public/"

After about 30 minutes of searching, I've decided to try a different version, just to see what happens, and after downloading version 17.09.1, it started working again

**Steps to reproduce the issue:**
1. Create /etc/docker/daemon.json and insert a registry-mirror, like the following: 
```
{
        "registry-mirrors": ["http://192.168.1.201:8081/repository/docker-public/"]
}
```
2. Update docker to version 17.12.1 using this [link](https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/docker-ce_17.12.1~ce-0~ubuntu_amd64.deb)

**Describe the results you received:**
Error when starting docker daemon

**Describe the results you expected:**
Docker daemon should've started as usual

**Additional information you deem important (e.g. issue happens only occasionally):**
Also happens with 17.12.0

**Output of `docker version`:**

```
Client:
 Version:	17.12.1-ce
 API version:	1.35
 Go version:	go1.9.4
 Git commit:	7390fc6
 Built:	Tue Feb 27 22:17:40 2018
 OS/Arch:	linux/amd64
```

**Output of `docker info`:**

```
Can't print, since daemon won't start.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Using a regular ubuntu 16.04 installation behind a corporate firewall (usually a problem, but not this time I guess)

### PR DESCRIPTION
**Pull request by regisb**
Close #36598

Note that this is my first PR in the Moby project, or in any go-language project for that matter. Please forgive my mistakes, and give detailed instructions if changes are necessary.

**- What I did**

Allow users to run registry mirrors that are rooted at a subpath of a domain.

**- How I did it**

In the registry configuration validation step, I removed the parts that check that there is no path in the mirror URIs.

**- How to verify it**

Run a registry with docker.io proxy config:

docker-compose.yml:

```
services:

  registry:
    image: docker.io/registry:2
    volumes:
      - ./registry.yml:/etc/docker/registry/config.yml:ro
      - ./data/registry:/var/lib/registry
    restart: unless-stopped

  proxy:
    image: docker.io/caddy
    ports:
      - "5001:5001"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    restart: unless-stopped
 ```

registry.yml:

```
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
proxy:
  remoteurl: https://registry-1.docker.io
```

Caddyfile:

```
:5001 {
    handle_path /hub/* {
        reverse_proxy http://registry:5000
    }
}
```

Run a Docker daemon with the following configuration in /etc/docker/daemon.json:

```
{
    "registry-mirrors": [
        "http://localhost:5001/hub"
    ]
}
```

Then pull an image: `docker pull ubuntu` and verify that the request goes through the self-hosted registry.

**- Description for the changelog**

Make it possible to run a registry mirror with an URI that includes a path.

**- A picture of a cute animal (not mandatory but encouraged)**

cute

### CODE REVIEW

**Comment by corhere** [comment]
Disallowing path, query and fragment components in the registry mirror URL config was not an accident. The restriction was added deliberately, with unit tests no less! There must have been a reason behind it. It might not have been a _good_ reason, or maybe it was a historical reason which is no longer relevant. Regardless, [we have to understand why the restrictions were added before they can be removed.](https://josephwoodward.co.uk/2020/04/software-the-chestertons-fence-principle) Please update the PR description with an explanation as to why path, query and fragment components were historically disallowed in registry mirror URLs and why the rationale is no longer applicable.

How do non-empty path, query and fragment components in a configured mirror URL affect the requests made to the registry mirror? [The OCI distribution spec](https://github.com/opencontainers/distribution-spec/blob/main/spec.md) defines all registry API endpoints as fully-qualified paths beginning with `/v2/`. Is the configured mirror URL path a path prefix, or a prefix to the repository namespace? How is the query component of the mirror config URL merged with the query parameters for e.g. [listing tags?](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#listing-tags) What happens if the query parameters in the configured mirror URL conflict with query parameters defined by the distribution API spec? (For the case of listing tags, the query parameters `n` and `last` would conflict.)

I can tell you immediately that [the fragment component](https://datatracker.ietf.org/doc/html/rfc3986#section-3.5) should continue to be disallowed. The URL fragment has no effect on HTTP semantics (it is not transmitted in HTTP requests) and thus is not needed for compatibility with any registry. Only the registry client—the moby daemon—ever sees the fragment component of the mirror URL, and so is the only part of the system which could imbue the mirror URL fragment with some semantic meaning. No such semantics are currently defined. Disallowing fragments in the mirror URLs effectively reserves fragments for future use. Lifting that restriction would effectively define the semantics as "permitted and ignored," making any future use of the fragment into a breaking change.

**Comment by gabor-boros** [comment]
@corhere Although I believe you didn't mean it, your comment feels a little bit passive-aggressive.

> Disallowing path, query and fragment components in the registry mirror URL config was not an accident. The restriction was added deliberately, with unit tests no less! There must have been a reason behind it. It might not have been a good reason, or maybe it was a historical reason which is no longer relevant. Regardless, [we have to understand why the restrictions were added before they can be removed.](https://josephwoodward.co.uk/2020/04/software-the-chestertons-fence-principle) Please update the PR description with an explanation as to why path, query and fragment components were historically disallowed in registry mirror URLs and why the rationale is no longer applicable.

In my opinion, linking the great article about fence principle is not helping much here, instead generates disappointment as contributors, especially those who are contributing for the first time, would expect help rather than indoctrination -- speaking only in my name.

Before opening the pull request, both @regisb and I looked up the historical reasons, though similarly to docker-related contributors, we didn't find much information. I assume you tried to look up the reason as well, and ended up with similar results as we did. However, reading through the GitHub issue carefully, it turns out the relevant missing information is stated in a [comment](https://github.com/moby/moby/issues/36598#issuecomment-677697890). Also, the other reference was linked in that comment, that [explicitly states](https://github.com/moby/moby/pull/38991#discussion_r271517220) the _original_ root cause:

> containerd does not currently support subpaths either so its not only validation

but as the first linked comment mentions,

> Since then, containerd looks to have added support [...]

So, now we know the historical reasons of the issue, and it is already stated that it is not an issue anymore from `containerd`'s side. However, the comment continues as

> however, it has not yet been looked into if that can be used (and BuildKit would have to be updated to user/support it, as it currently doesn't)

The comment is three years old and BuildKit evolved a lot over time. Neither of us (@regisb and I) are familiar with the BuildKit code base, however, as a core maintainer I assume you have better understanding than us and if you don't have time to look it up, at least you could help us pointing to the right direction to figure out if BuildKit added the support or not. **If my assumptions are correct, could you please help out with that?** Either pointing us to the right direction or validating if BuildKit added support by yourself would help I think.

> How do non-empty path, query and fragment components in a configured mirror URL affect the requests made to the registry mirror? [The OCI distribution spec](https://github.com/opencontainers/distribution-spec/blob/main/spec.md) defines all registry API endpoints as fully-qualified paths beginning with /v2/.

Although this is the first time I read the specification, the [original specification that the one you linked builds on](https://github.com/distribution/distribution/blob/5cb406d511b7b9163bff9b6439072e4892e5ae3b/docs/spec/api.md#overview) says that 

> All endpoints will be prefixed by the API version and the repository name: /v2/<name>/

though it does not mean that fully qualified API endpoints must start with `/v2/`. It only says that the endpoints serving the images/metadata/etc. must be prefixed by `/v2`, which means that `/hub/v2/...` should still be correct. If that's not the case, then it may worth clarifying this in the specification. 

> I can tell you immediately that [the fragment component](https://datatracker.ietf.org/doc/html/rfc3986#section-3.5) should continue to be disallowed. [...]

Regarding this, I agree that query and fragment components should not be allowed, but allowing the path would solve many companies' and individuals' issues without breaking the specification or the ecosystem.

**Comment by regisb** [comment]
Thanks for your detailed response @corhere, you are raising very valid points.

Based on your comment, I think it's quite clear that fragments and queries should *not* be allowed in the registry mirror URIs. I'll amend the PR in that direction. But for now let's focus on the path prefix, which is our (Gabor and I) primary subject of concern.

> Is the configured mirror URL path a path prefix, or a prefix to the repository namespace?

I'm not sure I understand the difference. Would you care to explain?

> Disallowing path, query and fragment components in the registry mirror URL config was not an accident. The restriction was added deliberately, with unit tests no less! There must have been a reason behind it. It might not have been a good reason, or maybe it was a historical reason which is no longer relevant. Regardless, [we have to understand why the restrictions were added before they can be removed.](https://josephwoodward.co.uk/2020/04/software-the-chestertons-fence-principle)

Yes, I agree with that. We would be very grateful if you helped us navigate the design decisions bethind the spec.

I may have found a clue in the "Historical context" section of the OCI distribution spec you linked to: https://github.com/opencontainers/distribution-spec/blob/main/spec.md#historical-context This spec points to issue https://github.com/moby/moby/issues/8093 This issue in turn includes the following paragraph:

> Unlike the present /v1/... which is locked to the root of the URI path, the /v2/... is expected be the relative root of the path, for easier route handling.

This sentence seems to indicate that the v1 API was not designed to be compatible with a path prefix, as opposed to v2. Is my understanding correct? That would be confirmed by the PR that initially introduced the `--registry-mirrors` option: https://github.com/moby/moby/pull/7202/files

```
return fmt.Sprintf("%s://%s/v1/", uri.Scheme, uri.Host), nil
```

That mirroring scheme seems to have ignored path prefixes either for the sake of simplicity, or because the `v1/` prefix needed to be at the root.

**Comment by corhere** [comment]
> > Is the configured mirror URL path a path prefix, or a prefix to the repository namespace?
> 
> I'm not sure I understand the difference. Would you care to explain?

Consider the case of [pulling the image manifest](https://github.com/distribution/distribution/blob/5cb406d511b7b9163bff9b6439072e4892e5ae3b/docs/spec/api.md#pulling-an-image-manifest) of `docker.io/library/hello-world:latest` through a configured mirror `https://example.com/hub`. If the path is a prefix, the daemon would prepend the mirror URL path to the API endpoint path:
```
GET /hub/v2/library/hello-world/manifests/latest
    \--/   \-------------------/         \------/
      \_ Path prefix  |                      \_ Reference (tag)
                       \_ Repository namespace
```
This is the interpretation you seem to want, given the verification steps in the PR description. It allows for registries "mounted" at a subpath of a domain to be used as Docker Hub mirrors. However, the Moby daemon would _only_ be able to use a repository deployed on a subpath as a Hub mirror as the [Docker image reference](https://pkg.go.dev/github.com/distribution/reference) syntax used in Dockerfiles and on the `docker` command line only has affordances for registries hosted at the root of a domain. That is to say, there is no way to instruct `docker pull` to pull an image from the repository namespace `foo/bar` hosted on the registry `example.com/my-private-registry`. Kubernetes (cri-containerd) uses the same image reference syntax, and will have the same limitations. I can't speak for the wider OCI ecosystem, however, as the image reference syntax is merely a de facto standard. [Containerd supports arbitrary path prefixes (and mirrors in general) as of v1.6.0](https://github.com/containerd/containerd/pull/3400) but BuildKit support is still an unknown as I am not personally familiar with that codebase. @tonistiigi may be able to answer.

> I may have found a clue in the "Historical context" section of the OCI distribution spec you linked to: https://github.com/opencontainers/distribution-spec/blob/main/spec.md#historical-context This spec points to issue #8093 This issue in turn includes the following paragraph:
> 
> > Unlike the present /v1/... which is locked to the root of the URI path, the /v2/... is expected be the relative root of the path, for easier route handling.
> 
> This sentence seems to indicate that the v1 API was not designed to be compatible with a path prefix, as opposed to v2. Is my understanding correct?

I can't really say. I wasn't around when the registry API was being designed, and the language about paths being relative does not appear to have made it into either the [Docker Registry v2](https://github.com/distribution/distribution/blob/main/docs/spec/api.md) spec nor the OCI Distribution spec. I suggest opening an issue on https://github.com/opencontainers/distribution-spec asking for clarification.

-----

Whereas if the path is a prefix to the repository namespace, the daemon would prepend the mirror URL path to the _repository namespace_ before interpolating the repository namespace into the API endpoint path:
```
GET /v2/hub/library/hello-world/manifests/latest
       \-----------------------/         \------/
             \_ Repository namespace        \_ Reference (tag)
```
This is equivalent to the daemon pulling the image reference `example.com/hub/library/hello-world:latest`. The registry would need to be hosted at the root of the domain, but would allow the same registry deployment to be used both as a Docker Hub mirror and as a private registry. From what I can tell, [this is the interpretation which would interoperate with Harbor.](https://goharbor.io/docs/main/administration/configure-proxy-cache/) It is also the interpretation I would prefer as it can be explained in terms of mapping one image reference to another, requires no understanding of how image pulls work over the wire, and avoids any ambiguities in the OCI Distribution spec.

File: registry/config.go [hunk 1]
```diff
@@ -330,8 +330,8 @@ func ValidateMirror(val string) (string, error) {
 	if uri.Scheme != "http" && uri.Scheme != "https" {
 		return "", invalidParamf("invalid mirror: unsupported scheme %q in %q", uri.Scheme, uri)
 	}
-	if (uri.Path != "" && uri.Path != "/") || uri.RawQuery != "" || uri.Fragment != "" {
-		return "", invalidParamf("invalid mirror: path, query, or fragment at end of the URI %q", uri)
+	if uri.RawQuery != "" || uri.Fragment != "" {
+		return "", invalidParamf("invalid mirror: query, or fragment at end of the URI %q", uri)
```
Comment (corhere) [inline registry/config.go:334]:
```suggestion
		return "", invalidParamf("invalid mirror: query or fragment at end of the URI %q", uri)
```

**Review by corhere — APPROVED** [review]
Come to think of it, we don't have to decide between allowing a path prefix _or_ a repository namespace prefix to be configured for a Docker Hub mirror. I've set up a false dichotomy: different situations could call for some combination of both! We still have to pick which one of the prefixes the path component of the URL represents, though.

I propose that we stick with the interpretation as currently implemented in this PR: the path component of the mirror URL is defined to be the path prefix for API requests to the mirror. (`https://example.com/hub` -> `GET /hub/v2/...`) And in the future, (read: in another PR,) we could allow the repository namespace prefix to be configured _through the fragment component_ to support the Harbor use-case!

Let's see what the other maintainers think.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by regisb** [comment]
Thanks for the quick review everyone! This was my first experience contributing to moby, and it's been a very pleasant one.
