### PR TITLE
Fix issue in `docker import -c` with quoted flags

### LINKED ISSUE #26173: docker import -c 'ENTRYPOINT ["/entrypoint.sh"]' fails
**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 11
 Running: 4
 Paused: 0
 Stopped: 7
Images: 57
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 120
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local-persist convoy local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.2.0-36-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.33 GiB
Name: minionS
ID: UG67:JBFC:ONKM:BTWN:COQW:6PMK:AWU7:UMJY:7FGM:NUTX:QTLQ:PKQG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: sayashk
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 dc=p4
 geo=us
 provider=generic
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical

**Steps to reproduce the issue:**
1.` CONT=$(docker run -d centos:7)`
2. `docker export $CONT | docker import -c 'ENTRYPOINT ["/entrypoint.sh"]' - some-name`

**Describe the results you received:**
Get the following error:
```
invalid argument "ENTRYPOINT [\"/entrypoint.sh\"]" for c: line 1, column 12: bare " in non-quoted-field
```

**Describe the results you expected:**
Image to be created.

**Additional information you deem important (e.g. issue happens only occasionally):**
The same syntax does work for `docker commit`

### PR DESCRIPTION
**Pull request by yongtang**
**\- What I did**

This fix tries to address the issue in #26173 where `docker import -c` with quoted flags returns an error.

The issue was that in `api/client/image/import.go` the flag `--change/-c` was handled by `StringSliceVarP` which does not handle the quote well.

The similiar issue was enountered for #23309 (`docker commit`):
https://github.com/docker/docker/pull/23309#discussion_r66090808

**\- How I did it**

This fix takes the same approach as 23309 where `StringSliceVarP` was replaced with `VarP` and `opts.ListOpts`.

**\- How to verify it**

An integration test has been added to cover the changes.

**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**

This fix fixes #26173.

Signed-off-by: Yong Tang yong.tang.github@outlook.com

### CODE REVIEW

**Comment by yongtang** [comment]
cc @dnephin Please take a look.

**Comment by vdemeester** [comment]
LGTM 🐸

File: integration-cli/docker_cli_import_test.go [hunk 1]
```diff
@@ -124,3 +124,25 @@ func (s *DockerSuite) TestImportFileNonExistentFile(c *check.C) {
...
+
+	temporaryFile, err := ioutil.TempFile("", "exportImportTest")
+	c.Assert(err, checker.IsNil, check.Commentf("failed to create temporary file"))
+	defer os.Remove(temporaryFile.Name())
+
+	runCmd := exec.Command(dockerBinary, "export", "test-import")
+	runCmd.Stdout = bufio.NewWriter(temporaryFile)
+
+	_, err = runCommand(runCmd)
+	c.Assert(err, checker.IsNil, check.Commentf("failed to export a container"))
```
Comment (dnephin) [inline integration-cli/docker_cli_import_test.go]: You can this with `pkg/integration/cmd` which will gives you a better error message when it fails:

```go

result := icmd.RunCmd(icmd.Cmd{
    Command: binaryWithArgs("export", "test-import"),
    Stdout: bufio.NewWriter(temporaryFile),
})
c.Assert(result, icmd.Matches, icmd.Success)

```

File: integration-cli/docker_cli_import_test.go [hunk 2]
```diff
@@ -124,3 +124,25 @@ func (s *DockerSuite) TestImportFileNonExistentFile(c *check.C) {
...
+
+	out, _ := dockerCmd(c, "import", "-c", `ENTRYPOINT ["/bin/sh", "-c"]`, temporaryFile.Name())
+	c.Assert(out, checker.Count, "\n", 1, check.Commentf("display is expected 1 '\\n' but didn't"))
+	image := strings.TrimSpace(out)
+
+	out, _ = dockerCmd(c, "run", "--rm", image, "true")
+	c.Assert(out, checker.Equals, "", check.Commentf("command output should've been nothing."))
```
Comment (dnephin) [inline integration-cli/docker_cli_import_test.go]: same here:

```go
result := dockerCmdWithResult("run", "--rm", image, "true")
c.Assert(result, icmd.Matches, icmd.Expected{Stdout: icmd.None})

```

**Comment by dnephin** [comment]
Fix looks good, just some suggestions for the tests.

**Comment by yongtang** [comment]
Thanks @dnephin the pull request has been updated.

**Comment by dnephin** [comment]
LGTM
