### PR TITLE
Fix error messages for `--cpus` from daemon

### LINKED ISSUE #28456: Problem with `--cpus` error message
**Description**

Using 1.13 RC1 on Linux, I try to run a container with `--cpus=2` when I only have one CPU. The error message I get seems like a bug, and the `--help` text also says the unit is a "decimal" when that makes me wonder if it would accept a floating-point number.

```
ubuntu@ip-172-31-46-109:~$ docker run --help

Usage:	docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Run a command in a new container

Options:
...
      --cpus decimal                          Number of CPUs (default 0.000)
...
```

```bash
$ docker run --cpus=2 hello-world

docker: Error response from daemon: Range of Nano CPUs is from 1 to 1000000000.
See 'docker run --help'.

$ docker run --cpus=2.0 hello-world

docker: Error response from daemon: Range of Nano CPUs is from 1 to 1000000000.
See 'docker run --help'.

$ docker run --cpus=1 hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker Hub account:
 https://hub.docker.com

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/
```

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc1
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   75fd88b
 Built:        Fri Nov 11 19:47:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:             1.13.0-rc1
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          75fd88b
 Built:               Fri Nov 11 19:47:07 2016
 OS/Arch:             linux/amd64
 Experimental:        false
```

**Output of `docker info`:**

```
Containers: 5
 Running: 2
 Paused: 0
 Stopped: 3
Images: 55
Server Version: 1.13.0-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 64
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 0p14wy00b3h8nfkumrjucmhln
 Is Manager: true
 ClusterID: lkln9som0ao5w3o4vppafe9wh
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.31.46.109
 Manager Addresses:
  172.31.46.109:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 8517738ba4b82aff5662c97ca4627e7e4d03b531
runc version: ac031b5bf1cc92239461125f4c1ffb760522bbf2
init version: N/A (expected: v0.13.0)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-45-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.952 GiB
Name: ip-172-31-46-109
ID: IAXO:F4VE:QY6K:DYL7:QHEJ:XA47:2FDM:BITI:XSAL:OTJH:4LDS:TSCA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running 1.13 binary on an EC2 Ubuntu 16.04 box.

### PR DESCRIPTION
**Pull request by yongtang**
This fix fixes error messages for `--cpus` from daemon.

When `docker run` takes `--cpus`, it will translate into NanoCPUs and pass the value to daemon. The `NanoCPU` is not visible to the user. The error message generated from daemon used 'NanoCPU' which may cause some confusion to the user.

This fix fixes this issue by returning the error in CPUs instead.

This fix fixes #28456.

cc @crosbymichael @mstanleyjones @thaJeztah 

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by yongtang** [comment]
Here is an example output (on a 2 CPU machine):
```
ubuntu@ubuntu:~/docker$ docker run --cpus 100 busybox
docker: Error response from daemon: Range of CPUs is from 0.01 to 2.00, as there are only 2 CPUs available.
See 'docker run --help'.
ubuntu@ubuntu:~/docker$ docker run --cpus 2.00 busybox
ubuntu@ubuntu:~/docker$ docker run --cpus 1.00 busybox
ubuntu@ubuntu:~/docker$ docker run --cpus 0.05 busybox
ubuntu@ubuntu:~/docker$ docker run --cpus 0.01 busybox
ubuntu@ubuntu:~/docker$ docker run --cpus 0.001 busybox
docker: Error response from daemon: Range of CPUs is from 0.01 to 2.00, as there are only 2 CPUs available.
See 'docker run --help'.
```

**Comment by crosbymichael** [comment]
Maybe the docs should state .01 as the low but do you think we should enforce this in the code?  Maybe we don't have to enforce the lower side incase someone needs to set it?

**Comment by yongtang** [comment]
Thanks @crosbymichael. I updated the PR. The error message has been changed though true lower limit is only decided by the underlying platform (Windows, Linux).

Previously, it was only possible to get the precision to `0.01` on Linux, as `cpu.cfs_period_us` was set with `100ms`. (And `cpu.cfs_quota` could be as low as `1ms`)

This PR changed the base value of `cpu.cfs_period_us` to `1s`. `1s` is the highest value we could get according to:
https://www.kernel.org/doc/Documentation/scheduler/sched-bwc.txt

In this way, it is possible to have a CPU precision of `0.001` on Linux:

```
ubuntu@ubuntu:~/docker$ docker run --cpus 100 busybox
docker: Error response from daemon: Range of CPUs is from 0.01 to 2.00, as there are only 2 CPUs available.
See 'docker run --help'.
ubuntu@ubuntu:~/docker$ docker run --cpus 3.0 busy box
docker: Error response from daemon: Range of CPUs is from 0.01 to 2.00, as there are only 2 CPUs available.
See 'docker run --help'.
ubuntu@ubuntu:~/docker$ docker run --cpus 2.00 busybox
ubuntu@ubuntu:~/docker$ docker run --cpus 1.00 busybox
ubuntu@ubuntu:~/docker$ docker run --cpus 0.05 busybox
ubuntu@ubuntu:~/docker$ docker run --cpus 0.01 busybox
ubuntu@ubuntu:~/docker$ docker run --cpus 0.005 busybox
ubuntu@ubuntu:~/docker$ docker run --cpus 0.001 busybox
ubuntu@ubuntu:~/docker$ docker run --cpus 0.0001 busybox
container_linux.go:247: starting container process caused "process_linux.go:291: setting cgroup config for ready process caused \"failed to write 100 to cpu.cfs_quota_us: write /sys/fs/cgroup/cpu,cpuacct/docker/0d5d5a41185a184f069d2c7ee3e8f850c70abb24fab2ce15a0728904f6d30501/cpu.cfs_quota_us: invalid argument\""
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:291: setting cgroup config for ready process caused \"failed to write 100 to cpu.cfs_quota_us: write /sys/fs/cgroup/cpu,cpuacct/docker/0d5d5a41185a184f069d2c7ee3e8f850c70abb24fab2ce15a0728904f6d30501/cpu.cfs_quota_us: invalid argument\"".
ERRO[0000] error getting events from daemon: net/http: request canceled 
ubuntu@ubuntu:~/docker$ 
```

**Comment by thaJeztah** [comment]
ping @crosbymichael PTAL, as this changes more than just the error message IIUC

**Review by mdlinville — APPROVED** [review]
LGTM, this is a ton easier to understand for the end-user, who will not like to think of their CPUs at the nano-scale. It is also helpful to show the number of CPUs actually detected on the system in the error message.

**Comment by crosbymichael** [comment]
LGTM

File: daemon/daemon_unix.go [hunk 1]
```diff
@@ -112,10 +112,11 @@ func getCPUResources(config containertypes.Resources) *specs.CPU {
...
 
 	if config.NanoCPUs > 0 {
-		// Use the default setting of 100ms, as is specified in:
+		// We set the highest value possible (1s), as is specified in:
 		// https://www.kernel.org/doc/Documentation/scheduler/sched-bwc.txt
-		//    	cpu.cfs_period_us=100ms
-		period := uint64(100 * time.Millisecond / time.Microsecond)
+		//    	cpu.cfs_period_us=1s
+		// The purpose is to get the highest precision
+		period := uint64(1 * time.Second / time.Microsecond)
```
Comment (crosbymichael) [inline daemon/daemon_unix.go]: This change looks much more correct to me, I think its originally wrong in swarm for the calculation

**Comment by crosbymichael** [comment]
@yongtang since quota depends on period, do we have validation anywhere that prevents someone from setting `--cpu-quota` and `--cpu-period` when `--cpus` or `NanoCPUs` is specified?  If not we should add it because it will throw off the calculation.

**Comment by yongtang** [comment]
Thanks @crosbymichael. The conflict of `--cpus`, `--cpu-quota` and `--cpu-period` are detected in:
https://github.com/docker/docker/blob/v1.13.0-rc1/daemon/daemon_unix.go#L354-L360
