### PR TITLE
reset bufReader to avoid extreme growth of buffers

### LINKED ISSUE #8502: High memory usage for docker daemon process
Docker process was using almost all of my memory (4 gig total)
```
$ top
PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND 
838 root      20   0 6698.0m 3.185g   1.7m S  0.3 82.5  10:34.55 docker
```

It sorted itself out (killing _all_ my containers in the process), but not before bringing the entire system down to its knees.

Any hints on how to debug/prevent this in the future?

## Docker Info
```
# docker version
Client version: 1.2.0
Client API version: 1.14
Go version (client): go1.3.1
Git commit (client): fa7b24f
OS/Arch (client): linux/amd64
Server version: 1.2.0
Server API version: 1.14
Go version (server): go1.3.1
Git commit (server): fa7b24f
```
```
# docker info
Containers: 14
Images: 202
Storage Driver: btrfs
Execution Driver: native-0.2
Kernel Version: 3.13.0-36-generic
Operating System: Ubuntu 14.04.1 LTS
Username: ...
Registry: [https://index.docker.io/v1/]
```

### LINKED ISSUE #8539: Error response from daemon: Cannot start container (fork/exec /usr/sbin/iptables: cannot allocate memory)
We are running some coreos clusters. Over time (after a week) we see the following error taking place.

```bash
# systemd error log
2014/10/13 16:12:08 Error response from daemon: Cannot start container f9e42f092597e46f5cf6a507d7e70662e6ef1035a8f01d95f56c1f2934234361: iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 172.31.31.159 --dport 49450 ! -i docker0 -j DNAT --to-destination 172.17.0.95:80:  (fork/exec /usr/sbin/iptables: cannot allocate memory)
```

Here we need to restart the docker daemon and everything is back to normal. Is there a memory leak? I see there is enough memory available. Is it because of the swap?

environment information
```bash
# top
top - 16:13:01 up 22 days,  7:56,  1 user,  load average: 6.50, 5.44, 4.58
Tasks: 186 total,   3 running, 183 sleeping,   0 stopped,   0 zombie
Cpu(s):  0.0%us,  0.0%sy,  0.0%ni, 14.2%id,  1.3%wa, 33.7%hi,  0.0%si, 50.8%st
Mem:   4051204k total,  3886188k used,   165016k free,     3168k buffers
Swap:        0k total,        0k used,        0k free,  1681572k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
20318 root      20   0 3449m 1.3g  10m S    0 34.0  18:27.87 docker

# memory stats
$ free
             total       used       free     shared    buffers     cached
Mem:       4051204    3884208     166996          0       3168    1681744
-/+ buffers/cache:    2199296    1851908
Swap:            0          0          0

# coreos version
$ cat /etc/lsb-release
DISTRIB_ID=CoreOS
DISTRIB_RELEASE=410.0.0
DISTRIB_CODENAME="Red Dog"
DISTRIB_DESCRIPTION="CoreOS 410.0.0"

# docker info 
$ docker info
Containers: 22
Images: 332
Storage Driver: btrfs
Execution Driver: native-0.2
Kernel Version: 3.15.8+

# docker version
$ docker -v
Docker version 1.1.2, build d84a070

### LINKED ISSUE #9139: memory leak in buffer grow
Hi!
I've experienced problem with memory leak which  looks pretty simular to #8084 . 

docker 1.3.0

go tool pprof on heap looks like: 

```
Total: 8659.9 MB
     0.0   0.0%   0.0%   8658.9 100.0% runtime.gosched0
     0.0   0.0%  99.8%   8638.3  99.7% github.com/docker/docker/daemon.func·006
     4.5   0.1%   0.1%   8643.9  99.8% io.Copy
     0.0   0.0%  99.8%   8637.8  99.7% github.com/docker/docker/engine.(*Output).Write
     0.0   0.0%   0.1%   8639.9  99.8% bytes.(*Buffer).Write
     0.0   0.0%   0.1%   8639.9  99.8% bytes.(*Buffer).grow
  8639.9  99.8%  99.8%   8639.9  99.8% bytes.makeSlice

```
I don't know how to reproduce it with simple example but if you need any additional information I can gather it from out production project.

### PR DESCRIPTION
**Pull request by unclejack**
This PR is an attempt to help solve problems like #9139 and #8502.

This PR changes bufReader to try to avoid the growth of bytes.Buffer to extreme sizes (hundreds of megabytes or even gigabytes). This makes long running containers which need to log to the console more reliable over time.

Please note that this PR only fixes this problem for now. Proper logging support is still needed.

Fixes #9139
Fixes #8539
Fixes #8502

### CODE REVIEW

**Comment by unclejack** [comment]
ping @LK4D4

**Comment by LK4D4** [comment]
I tested - this fixing problem. I'm not reviewed code though.

**Comment by unclejack** [comment]
@LK4D4 Thanks for trying it out!

**Comment by unclejack** [comment]
This PR fixes 3 issues and it needs to be reviewed so that I can make any necessary changes after review and feedback.

ping @crosbymichael @dmcgowan @duglin @erikh @icecrime @jfrazelle @jlhawn @LK4D4 @tiborvass @vbatts

File: pkg/ioutils/readers.go [hunk 1]
```diff
@@ -74,14 +93,61 @@ func NewBufReaderWithDrainbufAndBuffer(r io.Reader, drainBuffer []byte, buffer *
...
+		reuseBufLen    int64
+		reuseCount     int64
+	)
+	reuseBufLen = int64(len(r.reuseBuf))
+	lastReset = time.Now()
 	for {
 		n, err := r.reader.Read(r.drainBuf)
+		dataSinceReset += int64(n)
 		r.Lock()
+		bufLen = int64(r.buf.Len())
```
Comment (erikh) [inline pkg/ioutils/readers.go]: isn't there potential here to overstep bounds with the type conversions? Should these really be `int` instead?

Comment (unclejack) [inline pkg/ioutils/readers.go]: @erikh I've made this explicit to avoid problems on 32bit platforms. I'm not sure how this could cause a problem.

File: pkg/ioutils/readers.go [hunk 2]
```diff
@@ -74,14 +93,61 @@ func NewBufReaderWithDrainbufAndBuffer(r io.Reader, drainBuffer []byte, buffer *
...
+			now = time.Now()
+			duration = now.Sub(lastReset)
+			timeoutReached := duration >= r.resetTimeout
+			if timeoutReached && bufLen > reuseBufLen {
+				reset = true
+			}
+			if timeoutReached && maxBufLen >= r.bufLenResetThreshold {
+				reset = true
+			}
+			if timeoutReached && dataSinceReset >= r.maxReadDataReset {
```
Comment (jlhawn) [inline pkg/ioutils/readers.go]: For more readability, we could define these functions at the top of `drain()`, after declaring all of the `var`s:
```go
timeoutReached = func() bool { return time.Now().Sub(lastReset) >= r.resetTimeout }
resetCond1 = func() bool { return bufLen > reuseBufLen }
resetCond2 = func() bool { return maxBufLen >= r.bufLenResetThreshold }
resetCond3 = func() bool { return dataSinceReset >= r.maxReadDataReset }
shouldReset = func() bool { return timeoutReached() && (resetCond1() || resetCond2() || resetCond3()) }
```
Then you can say:
```go
if shouldReset() {
	newbuf := &bytes.Buffer{}
	newbuf.ReadFrom(r.buf)
	r.buf = newbuf
	lastReset = time.Now()
	dataSinceReset = 0
	maxBufLen = 0
	reuseCount = 0
}
```

File: pkg/ioutils/readers.go [hunk 3]
```diff
@@ -74,14 +93,61 @@ func NewBufReaderWithDrainbufAndBuffer(r io.Reader, drainBuffer []byte, buffer *
...
+	)
+	reuseBufLen = int64(len(r.reuseBuf))
+	lastReset = time.Now()
 	for {
 		n, err := r.reader.Read(r.drainBuf)
+		dataSinceReset += int64(n)
 		r.Lock()
+		bufLen = int64(r.buf.Len())
+		if bufLen > maxBufLen {
+			maxBufLen = int64(bufLen)
```
Comment (dmcgowan) [inline pkg/ioutils/readers.go]: nit: already in64

**Comment by dmcgowan** [comment]
looks good, the branching logic for reset should be cleaned up for readability and reduce the if blocks as Josh suggested

File: pkg/ioutils/readers.go [hunk 4]
```diff
@@ -74,14 +93,61 @@ func NewBufReaderWithDrainbufAndBuffer(r io.Reader, drainBuffer []byte, buffer *
...
+		}
+		if bufLen > 0 && reuseBufLen >= bufLen {
+			n, _ := r.buf.Read(r.reuseBuf)
+			r.buf.Reset()
+			r.buf.Write(r.reuseBuf[0:n])
+		} else if reuseCount >= r.maxReuse && bufLen > 0 {
+			now = time.Now()
+			duration = now.Sub(lastReset)
```
Comment (LK4D4) [inline pkg/ioutils/readers.go]: I believe there is `time.Since` for such thing.

File: pkg/ioutils/readers.go [hunk 5]
```diff
@@ -74,14 +93,61 @@ func NewBufReaderWithDrainbufAndBuffer(r io.Reader, drainBuffer []byte, buffer *
...
+		lastReset      time.Time
+		now            time.Time
+		reset          bool
+		bufLen         int64
+		dataSinceReset int64
+		maxBufLen      int64
+		reuseBufLen    int64
+		reuseCount     int64
+	)
+	reuseBufLen = int64(len(r.reuseBuf))
```
Comment (LK4D4) [inline pkg/ioutils/readers.go]: How about to make this constant?

Comment (LK4D4) [inline pkg/ioutils/readers.go]: Also I'm not sure about conversion all to `int64`. We operating numbers not even nearly as great as MAXINT on 32-bit systems. Why we need complicate code here?

File: pkg/ioutils/readers_test.go [hunk 6]
```diff
@@ -32,3 +32,58 @@ func TestBufReader(t *testing.T) {
...
+	b.SetBytes(1024 * int64(reads))
+	b.ResetTimer()
+	for i := 0; i < b.N; i++ {
+		testWithData(data, reads)
+	}
+}
+
+func Benchmark10k32KBytesReads(b *testing.B) {
+	reads := 10000
+	data := make([]byte, 32768)
```
Comment (LK4D4) [inline pkg/ioutils/readers_test.go]: Something wrong with this benchmark. Only `10240000` copied to `ioutil.Discard`, but should be `327680000`.

File: pkg/ioutils/readers.go [hunk 7]
```diff
@@ -74,14 +93,61 @@ func NewBufReaderWithDrainbufAndBuffer(r io.Reader, drainBuffer []byte, buffer *
...
 		n, err := r.reader.Read(r.drainBuf)
+		dataSinceReset += int64(n)
 		r.Lock()
+		bufLen = int64(r.buf.Len())
+		if bufLen > maxBufLen {
+			maxBufLen = int64(bufLen)
+		}
+		if bufLen > 0 && reuseBufLen >= bufLen {
+			n, _ := r.buf.Read(r.reuseBuf)
+			r.buf.Reset()
```
Comment (LK4D4) [inline pkg/ioutils/readers.go]: Do we really need reset here?

Comment (dmcgowan) [inline pkg/ioutils/readers.go]: Or are you asking if this entire block should be removed? Without reset this would be a no-op.  The reset allows the buffer to be reused and reduces the chance of a growth allocation if I understand correctly.

File: pkg/ioutils/readers.go (hunk 4 above)
Comment (unclejack) [inline pkg/ioutils/readers.go]: @LK4D4 I'm using `now` later on in the code and I'm avoiding getting a timestamp twice using this.

File: pkg/ioutils/readers.go (hunk 5 above)
Comment (unclejack) [inline pkg/ioutils/readers.go]: Ok, I'll make the necessary changes. However, I wanted to make sure we don't wrap around if we've read more than 4 GB or if the buffer has grown above 4 GB since the last reset on 32 bit platforms.

File: pkg/ioutils/readers.go (hunk 7 above)
Comment (LK4D4) [inline pkg/ioutils/readers.go]: I think buffer will be reused anyway, I'm not sure, but seems like this branch is no-op in any case.

File: pkg/ioutils/readers.go (hunk 2 above)
Comment (LK4D4) [inline pkg/ioutils/readers.go]: I dunno, is five nested closures good idea in such critical part? Maybe we can just write one with big condition.

File: pkg/ioutils/readers.go (hunk 7 above)
Comment (unclejack) [inline pkg/ioutils/readers.go]: It's not a no-op. This piece of code is meant to keep the buffered data at the front of the buffer if there's less data buffered than the size of the "reuseBuf".

If this branch isn't triggered because there's a whole lot more data, the others are hit after the timeout, thus avoiding a pathological buffer growth.

File: pkg/ioutils/readers.go (hunk 2 above)
Comment (unclejack) [inline pkg/ioutils/readers.go]: I'm not a fan of that. It makes the code even weirder and I don't know if having this number of closures per goroutine multiplied by 2 for every container and then multiplied again by the number of containers would be a good idea.

File: pkg/ioutils/readers.go [hunk 8]
```diff
@@ -44,18 +47,34 @@ func NewReaderErrWrapper(r io.Reader, closer func()) io.Reader {
 
 type bufReader struct {
```
Comment (stevvooe) [inline pkg/ioutils/readers.go]: Unrelated to this PR: this should contain some commentary on why `bufio.Reader`, from the stdlib, is insufficient.

File: pkg/ioutils/readers.go (hunk 7 above)
Comment (LK4D4) [inline pkg/ioutils/readers.go]: ok

File: pkg/ioutils/readers.go (hunk 1 above)
Comment (erikh) [inline pkg/ioutils/readers.go]: I guess int automatically gets promoted, or something. Sorry to waste your time.

File: pkg/ioutils/readers.go (hunk 8 above)
Comment (dqminh) [inline pkg/ioutils/readers.go]: +1. I've had the same question before.

File: pkg/ioutils/readers_test.go (hunk 6 above)
Comment (unclejack) [inline pkg/ioutils/readers_test.go]: Thanks for finding this! You're right, I'll update it.

**Comment by unclejack** [comment]
@LK4D4 I've made some of the changes, but I'd like to keep those numbers as 64 ints everywhere to avoid having to sprinke `int64(var)` in some places.

@stevvooe There's a description now. Please take a look and let me know if it looks good to you.

**Comment by unclejack** [comment]
I've updated the PR to remove the truncate.

**Comment by thaJeztah** [comment]
@unclejack should this be moved to the 1.6 milestone? iiuc, there won't be a 1.5.1 release?

Also wondering if something is holding up this PR (apart from time constraint), as it seems to be resolving quite some issues :+1:

**Comment by unclejack** [comment]
I've rebased this PR on master and I'm using a binary built from this branch as my Docker daemon.

@thaJeztah It needs more testing and reviews at this point. This was the simplest change which could have been made to fix this problem without hurting performance after trying many other options. There's not much left to change regarding the design itself.

**Comment by stevvooe** [comment]
@unclejack Thanks for the explanation. So, this is effectively a buffer reader that does some read ahead?

**Comment by lqez** [comment]
:+1:

**Comment by unclejack** [comment]
@stevvooe Yes, it does read ahead so that it doesn't block the other readers by avoiding a reader to take too long to read everything.

We need to figure out what else needs to be done for this and get it merged. Many users are affected by the problem this PR fixes.

**Comment by unclejack** [comment]
The PR has been rebased on master and comments have been added.
@tiborvass PTAL

**Comment by unclejack** [comment]
This PR needs to be in 1.6.0.

**Comment by LK4D4** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM
