### PR TITLE
test: Fix "--raw-logs=true" option test in TestDaemonStartWithoutColors

### LINKED ISSUE #29772: Invalid assert in TestDaemonStartWithoutColors integration test
**Description**

TestDaemonStartWithoutColors test for "--raw-logs=true" option will always get empty output, but it can pass the assert:

  `c.Assert(b.String(), check.Not(checker.Contains), infoLog)`

This is because "tty" is closed in s.d.Stop() for "--raw-logs=false" test, so the "--raw-logs=true" test will receive empty output.

**Steps to reproduce the issue:**
1. add following assert to TestDaemonStartWithoutColors
```
--- a/integration-cli/docker_cli_daemon_test.go
+++ b/integration-cli/docker_cli_daemon_test.go
@@ -2194,6 +2194,7 @@ func (s *DockerDaemonSuite) TestDaemonStartWithoutColors(c *check.C) {
        // Disable coloring explicitly
        s.d.StartWithLogFile(tty, "--raw-logs=true")
        s.d.Stop(c)
+       c.Assert(b.String(), check.Not(check.Equals), "")
        c.Assert(b.String(), check.Not(checker.Contains), infoLog)
 }
```
2. run integration test

`TESTFLAGS='-check.f TestDaemonStartWithoutColors' make test-integration-cli`

**Describe the results you received:**

```
----------------------------------------------------------------------
FAIL: docker_cli_daemon_test.go:2172: DockerDaemonSuite.TestDaemonStartWithoutColors

[dab45615d06d6] waiting for daemon to start
[dab45615d06d6] daemon started

[dab45615d06d6] exiting daemon
[dab45615d06d6] waiting for daemon to start
[dab45615d06d6] daemon started

[dab45615d06d6] exiting daemon
docker_cli_daemon_test.go:2197:
    c.Assert(b.String(), check.Not(check.Equals), "")
... obtained string = ""
... expected string = ""

OOPS: 0 passed, 1 FAILED
--- FAIL: Test (15.07s)
FAIL
```

**Describe the results you expected:**

Test should passed.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.4
 Git commit:   a2b12b5
 Built:        Thu Dec 29 08:20:27 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.14.0-dev
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.4
 Git commit:   a2b12b5
 Built:        Thu Dec 29 08:20:27 2016
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

Not required.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by forever043**
Because "tty" is closed in s.d.Stop() for "--raw-logs=false" test, we need to open another pair of pty before test "--raw-logs=true" option.

This patch fix #29772.

Signed-off-by: Jiuyue Ma <majiuyue@huawei.com>

### CODE REVIEW

File: integration-cli/docker_cli_daemon_test.go [hunk 1]
```diff
@@ -2174,27 +2174,33 @@ func (s *DockerDaemonSuite) TestDaemonStartWithoutColors(c *check.C) {
...
-	b := bytes.NewBuffer(nil)
 	go io.Copy(b, p)
 
 	// Enable coloring explicitly
 	s.d.StartWithLogFile(tty, "--raw-logs=false")
 	s.d.Stop(c)
 	c.Assert(b.String(), checker.Contains, infoLog)
 
+	// "tty" is closed in s.d.Stop(), we need open another pair of pty
+	tty.Close()
```
Comment (tonistiigi) [inline integration-cli/docker_cli_daemon_test.go]: Why the double close of `tty` if it is closed in `Stop()`. I think defer before protected tty being closed in case of early failure.

File: integration-cli/docker_cli_daemon_test.go [hunk 2]
```diff
@@ -2174,27 +2174,33 @@ func (s *DockerDaemonSuite) TestDaemonStartWithoutColors(c *check.C) {
...
+
 	p, tty, err := pty.Open()
 	c.Assert(err, checker.IsNil)
-	defer func() {
-		tty.Close()
-		p.Close()
-	}()
-
-	b := bytes.NewBuffer(nil)
 	go io.Copy(b, p)
```
Comment (tonistiigi) [inline integration-cli/docker_cli_daemon_test.go]: Not directly related to this fix but shouldn't we wait for this copy to finish. Something like:
```
ch := make(chan struct{})
go func() {
  io.Copy()
  close(ch)
}()
...
d.stop()
<-ch
```

Comment (forever043) [inline integration-cli/docker_cli_daemon_test.go]: good idea : )

File: integration-cli/docker_cli_daemon_test.go (hunk 1 above)
Comment (forever043) [inline integration-cli/docker_cli_daemon_test.go]: fixed

**Comment by forever043** [comment]
I have no idea why `windowsRS1` failed in `DockerSuite.TestSlowStdinClosing`
```
03:47:44 ----------------------------------------------------------------------
03:47:44 FAIL: docker_cli_run_test.go:4606: DockerSuite.TestSlowStdinClosing
03:47:44 
03:47:44 docker_cli_run_test.go:4622:
03:47:44     c.Fatal("running container timed out") // cleanup in teardown
03:47:44 ... Error: running container timed out
03:47:44 
03:47:44 
03:47:44 ----------------------------------------------------------------------
```

**Comment by thaJeztah** [comment]
Looks like it's all green now

ping @tonistiigi PTAL

**Comment by tonistiigi** [comment]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐸
