### PR TITLE
Fix issue of filter in `docker ps` where `health=starting` returns nothing

### LINKED ISSUE #35920: Docker ps: filter container by health=starting
**Description**

The filter option of docker ps should support filtering containers by health=starting as stated in the [docker ps documentation](https://docs.docker.com/engine/reference/commandline/ps/#filtering).
Unfortunately the output listing is empty even though containers are currently in health check state starting.

**Steps to reproduce the issue:**
1. Start a container with health check
2. Make sure the container is health check state starting
3. Run `docker ps -f health=starting`
4. Make sure the container is still in health check state starting and did change state in the meantime

**Describe the results you received:**
Step 3. should display a list of running containers current in health check starting state.

**Describe the results you expected:**
Step 3. simply returns an empty table with no containers at all.

**Additional information you deem important (e.g. issue happens only occasionally):**
Filtering for `health=healthy`, `health=unhealthy`, `health=none` is working correctly.
The Filter option `health=starting` is understood correctly. `health=stopping` returns "Unrecognised filter value".

**Output of `docker version`:**

```
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:10:45 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:09:19 2017
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 65
Server Version: 17.12.0-ce
Storage Driver: aufs
 Root Dir: /app/docker/aufs
 Backing Filesystem: extfs
 Dirs: 126
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-37-generic
Operating System: Ubuntu 17.04
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.2GiB
Name: ets-20170744
ID: UQEP:CSSG:3PZN:ONR7:TR5Y:RSDZ:4I7I:5EL2:WYJE:O57Y:X5C4:N4XH
Docker Root Dir: /app/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: http://localhost:3128/
HTTPS Proxy: http://localhost:3128
No Proxy: localhost,127.0.0.1,mgrsfxrepned001.fx.eos.lcl
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical on Ubuntu 17.04

### PR DESCRIPTION
**Pull request by yongtang**
**- What I did**

This fix tries to address the issue raised in 35920 where the filter of `docker ps` with  `health=starting` always returns nothing.

**- How I did it**

The issue was that in container view, the human readable string (`HealthString()` => `Health.String()`) of health status was used. In case of starting it is `"health: starting"`. However, the filter still uses `starting` so no match returned.

This fix fixes the issue by using `container.Health.Status()` instead so that it matches the string (`starting`) passed by filter.

**- How to verify it**

An integration test has been added.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

arhero-rabbits-20161209

This fix fixes #35920.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

File: container/view.go [hunk 1]
```diff
@@ -313,7 +317,7 @@ func (v *memdbView) transform(container *Container) *Snapshot {
 		Managed:      container.Managed,
 		ExposedPorts: make(nat.PortSet),
 		PortBindings: make(nat.PortSet),
-		Health:       container.HealthString(),
+		Health:       health,
```
Comment (dnephin) [inline container/view.go]: I believe this was the only place that `(s *State) HealthString()` was called, so please remove that method.

File: integration/container/health_test.go [hunk 2]
```diff
@@ -45,6 +47,44 @@ func TestHealthCheckWorkdir(t *testing.T) {
 	poll.WaitOn(t, pollForHealthStatus(ctx, client, c.ID, types.Healthy), poll.WithDelay(100*time.Millisecond))
 }
 
+func TestHealthCheckFilter(t *testing.T) {
```
Comment (dnephin) [inline integration/container/health_test.go]: This change seems like it could be easily tested with a unit test of `transform()` instead of an integration test.

**Comment by yongtang** [comment]
Thanks @dnephin for the review. The PR has been updated with unit test. Please take a look.

**Review by dnephin — APPROVED** [review]
LGTM

**Review by boaz0 — APPROVED** [review]
LGTM 👍

**Review by vdemeester — APPROVED** [review]
LGTM 🎉
