### PR TITLE
c8d/exec: Add additional groups on exec

### LINKED ISSUE #46712: c8d/exec: `GroupAdd` isn't considered if setting `User`
### Description

With the containerd integration enabled, when running a container, extra groups (`docker run --group-add`) are not respected if user (`docker run --user`) is also specified.

### Reproduce

1. `docker run -d --name test --user root:root --group-add staff --group-add wheel --group-add audio --group-add 777 busybox top`
2. `docker exec test id`

### Expected behavior

Expected:
```
uid=0(root) gid=0(root) groups=0(root),10(wheel),29(audio),50(staff),777
```
Actual:
```
uid=0(root) gid=0(root) groups=0(root)
```

(however, if `--user root:root` is omitted from `docker run`, things work as expected)

### Additional Info

This is what's causing `TestDockerSwarmSuite/TestSwarmServiceWithGroup` (https://github.com/moby/moby/actions/runs/6614054276/job/17963338446?pr=46634) to fail.

### PR DESCRIPTION
**Pull request by laurazard**
Closes #46712

**- What I did**

Add configured additional groups from the container's host config on exec.

**- How I did it**

With 1 extra line!

**- How to verify it**

1. `docker run -d --name test --user root:root --group-add staff --group-add wheel --group-add audio --group-add 777 busybox top`
2. `docker exec test id`
3. (find expected groups)

**- Description for the changelog**

``

**- A picture of a cute animal (not mandatory but encouraged)**

image

### CODE REVIEW

**Comment by thaJeztah** [comment]
You mentioned `TestDockerSwarmSuite/TestSwarmServiceWithGroup` failing because of this; is there a test we can add (or extend) to cover this for `docker run` and `docker exec` ?


I see there's some existing tests in `integration-cli`, but ideally it would be in `integration/` instead of `integration-cli` (perhaps those existing integration-cli tests should be moved to `integration/`, but I haven't looked how complicated that is)

Found these through a pretty naive search for `gid=0(`, but perhaps there's other tests that don't depend on the output

```bash
git grep 'gid=0('
integration-cli/docker_cli_exec_test.go:        assert.Assert(c, strings.Contains(out, "uid=0(root) gid=0(root)"), "exec with user by id expected daemon user got %s", out)
integration-cli/docker_cli_run_test.go: expected := "uid=0(root) gid=0(root)"
integration-cli/docker_cli_run_test.go:         expected = "uid=0(root) gid=0(root) groups=0(root)"
integration-cli/docker_cli_run_test.go: if !strings.Contains(out, "uid=0(root) gid=0(root)") {
integration-cli/docker_cli_run_test.go: if !strings.Contains(out, "uid=0(root) gid=0(root) groups=0(root),10(wheel)") {
integration-cli/docker_cli_run_test.go: groupsList := "uid=0(root) gid=0(root) groups=0(root),10(wheel),29(audio),50(staff),777"
integration-cli/docker_cli_swarm_test.go:       assert.Equal(c, strings.TrimSpace(out), "uid=0(root) gid=0(root) groups=0(root),10(wheel),29(audio),50(staff),777")
```

File: daemon/exec_linux.go [hunk 1]
```diff
@@ -41,6 +41,7 @@ func getUserFromContainerd(ctx context.Context, containerdCli *containerd.Client
 		coci.WithUser(ec.User),
 		withResetAdditionalGIDs(),
 		coci.WithAdditionalGIDs(ec.User),
+		coci.WithAppendAdditionalGroups(ec.Container.HostConfig.GroupAdd...),
```
Comment (thaJeztah) [inline daemon/exec_linux.go:44]: Somewhat orthogonal to this PR, but looking at the code, I went a bit down the rabbit-hole 🐰 ;

`execSetPlatformOpt` also has a Windows implementation, and it looks like we're currently fully ignoring these options on Windows; disclaimer: perhaps we document these to not be supported, and perhaps we don't support them at the API level; https://github.com/moby/moby/blob/a66ddb7c59781ab4b7d8b931658fa315157bc29b/daemon/exec_windows.go#L11-L16

_However_, I see this function is _also_ stubbed out in containerd; I'm wondering if we should call it in the Windows counterpart (and leave it up to containerd's implementation to do what's needed) ❓ ; it's a bit ambiguous though, because the comment describes LCOW (not "WCOW" :thinking:)
https://github.com/moby/moby/blob/a66ddb7c59781ab4b7d8b931658fa315157bc29b/vendor/github.com/containerd/containerd/oci/spec_opts.go#L812-L820

Further down the rabbit-hole; the `WithUser` and `WithUIDGID` functions look really scary, as they **unconditionally reset `AdditionalGids`** that means that _order of these options matters_. ⚠️ 
https://github.com/moby/moby/blob/a66ddb7c59781ab4b7d8b931658fa315157bc29b/vendor/github.com/containerd/containerd/oci/spec_opts.go#L594-L602
https://github.com/moby/moby/blob/a66ddb7c59781ab4b7d8b931658fa315157bc29b/vendor/github.com/containerd/containerd/oci/spec_opts.go#L697-L702

- On our side, we should consider adding a comment; it's currently somewhat clear because we _also_ call our own `withResetAdditionalGIDs` (which resets the field)
- ^^ but (looking at the code above), it looks like that function is redundant, so we can remove it (?)
- We should contribute a patch to containerd to _at least_ update the GoDoc for these functions to call that out
- _Perhaps_ consider making it an error-condition when setting a `User` and `AdditionalGids` is _not empty_ (?)

**Comment by rumpl** [comment]
image

Music to my eyes

File: daemon/exec_linux.go (hunk 1 above)
Comment (rumpl) [reply daemon/exec_linux.go:44]: Note: we had to reset the additional GIDs because containerd didn't do it at the time this was implemented, containerd changed its implementation since, was added here: https://github.com/moby/moby/commit/174802e15f12ee4384c7672676247aaf28997f76#diff-ebde8092f4da3b1f60a5d5b7d805276d2c831362b528c385e8792a9168a34444

So yeah, we can remove this call now I guess, maybe in a new PR

**Comment by rumpl** [comment]
> Found these through a pretty naive search for `gid=0(`, but perhaps there's other tests that don't depend on the output

A better search is `group-add` and indeed there is none that tests additional groups, might be a good idea to add one

File: daemon/exec_linux.go (hunk 1 above)
Comment (vvoland) [inline daemon/exec_linux.go:44]: This function (and also other `WithUser`/`With*GID`) mounts the container snapshot in a read-only mode:
https://github.com/moby/moby/blob/a66ddb7c59781ab4b7d8b931658fa315157bc29b/vendor/github.com/containerd/containerd/oci/spec_opts.go#L750-L754

which is undefined behavior for overlayfs when a directory is also mounted as a work-dir of other mount.

And this condition is true in this case, because for `exec`, the container will already be running and so the container snapshot (with container working layer) is already mounted.

This is not a new problem though, because this is already happening in the other `WithAdditionalGIDs`.

**Review by vvoland — COMMENTED** [review]
Overall the change looks LGTM on our side, but I have some some suspicions on the containerd implementation.

File: daemon/exec_linux.go (hunk 1 above)
Comment (rumpl) [reply daemon/exec_linux.go:44]: We (@laurazard did) fixed this in containerd https://github.com/containerd/containerd/pull/8299

**Comment by thaJeztah** [comment]
This looks to be unrelated (as this PR doesn't touch Windows code), but I notice that Windows (snapshotter) is fully failing;

```
Waiting for the test daemon to start...
Client:
 Version:      17.06.2-ce
 API version:  1.30
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.30/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:57:19 2017
 OS/Arch:      windows/amd64
.Client:
```

I'm somewhat expecting that would be "expected"; wondering if we should skip Windows CI though, if that's the case.

**Comment by thaJeztah** [comment]
For this PR; change itself LGTM; do we want to look at having a test before merging, or merge this, and move from there? (if we do, we should keep some tracking issue so that we don't forget to look at follow up(s)

**Review by rumpl — APPROVED** [review]
LGTM, I'm fine if we create an issue so that we can have a test for this case

**Comment by laurazard** [comment]
> You mentioned TestDockerSwarmSuite/TestSwarmServiceWithGroup failing because of this; is there a test we can add (or extend) to cover this for docker run and docker exec 
Yeah, I meant to do that (and put it on my list) but omitted it from this PR since I wanted to think about it some more.

We definitely should have a test specifically for this/outside of Swarm tests, since this isn't really swarm functionality. I'll make another PR (and think about where to put the test).

File: daemon/exec_linux.go (hunk 1 above)
Comment (laurazard) [reply daemon/exec_linux.go:44]: Will do! :)

Comment (vvoland) [reply daemon/exec_linux.go:44]: Ah, I missed that this removes the work-dir completely, instead of just moving to the lower-dir.
That solves the issue I think, although that probably means that changes to `/etc/passwd` during the container lifetime won't be picked up by this code? It's probably not a big problem though.

Comment (laurazard) [reply daemon/exec_linux.go:44]: > Perhaps consider making it an error-condition when setting a User and AdditionalGids is not empty (?)

In `WithUser`, or on our side?

Comment (rumpl) [reply daemon/exec_linux.go:44]: Why wouldn't they be picked up?

Comment (rumpl) [reply daemon/exec_linux.go:44]: > In `WithUser`, or on our side?

In another PR :) And surely with an issue so that we can discuss about this in a more approriate place

Comment (vvoland) [reply daemon/exec_linux.go:44]: Ah, nevermind, I'm talking nonsense, the upperdir is still in the lower-dir.

In that case, I think the readonly mount will still cause undefined behavior because we mount the container rw-layer (which is an upper-dir of the other mount) as lower-dir.

BUT! It's actually not going to happen there, because we don't even hit this mount code.
We don't even set the `Snapshotter` and `SnapshotterKey` for exec so it will end up taking this branch:
https://github.com/moby/moby/blob/a66ddb7c59781ab4b7d8b931658fa315157bc29b/vendor/github.com/containerd/containerd/oci/spec_opts.go#L732-L736

and will just use the `s.Root.Path` directly.

So, it's fine in this case, but we must remember about it if at some point in future we set `Snapshotter` and `SnapshotterKey` in exec config.

**Comment by laurazard** [comment]
Issue for tests: https://github.com/moby/moby/issues/46721

File: daemon/exec_linux.go (hunk 1 above)
Comment (thaJeztah) [reply daemon/exec_linux.go:44]: > So, it's fine in this case, but we must remember about it if at some point in future we set Snapshotter and SnapshotterKey in exec config.

@vvoland can you create a ticket for this if changes are needed somewhere? (this repo and/or containerd)?

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
- opened https://github.com/moby/moby/pull/46722 to remove the redundant `withResetAdditionalGIDs` option.

File: daemon/exec_linux.go (hunk 1 above)
Comment (rumpl) [reply daemon/exec_linux.go:44]: Yeah, we will always only set the root path since we are the ones doing the mounting (so that we can reference count things)

But we did set the `Snapshotter` in the past https://github.com/moby/moby/pull/45698/files#diff-034d55db8b341bd127a5394a84226b04c91d54669dd856051ceb0bcbbb50b380L182
