### PR TITLE
fix 11646 to check volume path in server side

### LINKED ISSUE #11646: create volume path validations
Right now volume paths are not checked until after the container is created, which can cause a container to fail to start, but not fail to be created in certain circumstances.

Need a set of validations on the volume paths prior to volume initialization.
This would include, but not limited to:

1) Is the path an empty string?
2) Is the path relative?
3) Is the path a file
4) Is the bind-path relative
...

### PR DESCRIPTION
**Pull request by resouer**
fixes #11646
1. fix `2) Is the path relative?` in docker server side.
2. move checks from createContainerPlatformSpecificSettings to parseVolumes

ping @cpuguy83  can you review this for us

/cc @resouer @xlgao-zju

Signed-off-by: xlgao-zju xlgao@zju.edu.cn

### CODE REVIEW

**Comment by calavera** [comment]
I put it in `design-review` because I'm not completely sure if this is what people expects. It looks like this patch changes the current behavior of `VOLUME` arguments in dockerfiles. Dunno what to think about that.

File: integration-cli/docker_cli_build_test.go [hunk 1]
```diff
@@ -317,7 +317,7 @@ func (s *DockerSuite) TestBuildHandleEscapes(c *check.C) {
 		`
   FROM scratch
   ENV FOO bar
-  VOLUME \${FOO}
+  VOLUME /\${FOO}
```
Comment (cpuguy83) [inline integration-cli/docker_cli_build_test.go]: This change should be on the `ENV` not on `VOLUME`, so... `ENV FOO /bar`

**Comment by cpuguy83** [comment]
The changes to the dockerfile are required because docker will refuse to create the container with this cahnge if the volume spec is incorrect... and a volume with a relative path is incorrect... so really the tests are wrong.

Adding an explicit test for `VOLUME` with a relative path would also be good.

**Comment by xlgao-zju** [comment]
@cpuguy83  I have already added this test as below: 

      func TestParseVolumes(t *testing.T)

Do you mean to add another one? And what explicit test do you want?

**Comment by cpuguy83** [comment]
@xlgao-zju Yes, we should add an integration-cli test for build to explicitly test that `VOLUME relative/path` causes the build to fail.

**Comment by calavera** [comment]
I'm very scared of this change. It has the potential to break thousands of dockerfiles and I don't like that. Can we make the builder to fix the path before saving the image, so the validation passes only in that case?

**Comment by xlgao-zju** [comment]
@cpuguy83  I have added a validation for VOLUME path and an integration-cli test for build. please review the code.
@calavera  I think you're right, but the conflict behaviors are kind of awful. So, what do you think, @cpuguy83 ?

**Comment by calavera** [comment]
@xlgao-zju I think that I don't want this pull request if the price to pay is thousands of images broken :wink:

**Comment by xlgao-zju** [comment]
@calavera  So,  should we fix the path instead of making the build fail?

**Comment by cpuguy83** [comment]
Yep, you're right. I could have sworn at some point `VOLUME foo` would create an un-startable container... however testing against 1.6 the dockerfile seems valid. So indeed the relative path needs to be ok in the Dockerfile.

**Comment by xlgao-zju** [comment]
For now,  VOLUME foo  and  VOLUME /foo  will get the same volume in containers...they all get /foo in container. So, all I need to do is to check the destination path in -v src:dest?
@cpuguy83

**Comment by xlgao-zju** [comment]
So, I prepare to check the destination path in -v /src:dest in server side? And I will not touch the behavior of VOLUME. And I will give a detailed description about this in the document. What do you think,  @cpuguy83  @calavera ?

**Comment by calavera** [comment]
that sounds like a very good plan @xlgao-zju, thank you!

LGTM

**Comment by tiborvass** [comment]
LGTM
