### PR TITLE
seccomp: allow specifying a custom profile with `--privileged`

### LINKED ISSUE #47499: `--privileged --security-opt seccomp=<CUSTOM.json>` ignores `<CUSTOM.json>`
### Description

`docker run --privileged --security-opt seccomp=<CUSTOM.json>` ignores `<CUSTOM.json>`

### Reproduce

1. Create `foo.json`:
 ```json
{
  "defaultAction": "SCMP_ACT_ALLOW",
  "syscalls": [ { "names": [ "connect" ], "action": "SCMP_ACT_ERRNO" } ]
}
```

2. Make sure that `docker run --security-opt seccomp=foo.json busybox wget -O- http://1.1.1.1/` fails:
```console
$ docker run --security-opt seccomp=foo.json busybox wget -O- http://1.1.1.1/
Connecting to 1.1.1.1 (1.1.1.1:80)
wget: can't connect to remote host (1.1.1.1): Operation not permitted
```

3. Repeat the previous step, but with `--privileged`

### Expected behavior

Expected behavior: it should consume `foo.json` and let `wget` fail

Actual behavior: it does not consume `foo.json`, so `wget` does not fail

### docker version

```bash
Client: Docker Engine - Community
 Version:           25.0.2
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        29cf629
 Built:             Thu Feb  1 00:22:57 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.2
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       fce6e0c
  Built:            Thu Feb  1 00:22:57 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    25.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.5
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 25.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-92-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.818GiB
 Name: lima-vm0
 ID: 095cc593-bf50-4b63-9ebb-6168ad3a60e4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info
- I assume this is *not* a vulnerability, as `--privileged` is never intended to be secure
- `--security-opt apparmor=<CUSTOM>` doesn't seem ignored

### PR DESCRIPTION
**Pull request by AkihiroSuda**
**- What I did**

Fix #47499

**- How I did it**

Updated `daemon/seccomp_linux.go`

**- How to verify it**

```console
$ cat <<EOF >foo.json
{
 "defaultAction": "SCMP_ACT_ALLOW",
 "syscalls": [ { "names": [ "connect" ], "action": "SCMP_ACT_ERRNO" } ]
}
EOF

$ docker run --security-opt seccomp=foo.json --privileged busybox wget -O- http://1.1.1.1/
Connecting to 1.1.1.1 (1.1.1.1:80)
wget: can't connect to remote host (1.1.1.1): Operation not permitted
```
"Operation not permitted" is the expected error here.

**- Description for the changelog**

```markdown changelog
seccomp: allow specifying a custom profile with `--privileged`
```

**- A picture of a cute animal (not mandatory but encouraged)**
🐧

### CODE REVIEW

**Review by neersighted — DISMISSED** [review]
I'm not sure this is correct or incorrect yet. As of late we have been discussing how `--privileged` and LSMs should combine (see the revival of https://github.com/moby/moby/issues/38075); so I'm registering my -1 for now until we decide how these options should (or should not) combine overall.

**Comment by AkihiroSuda** [comment]
To clarify the background, I'm proposing this for capturing socket syscalls with `SCMP_ACT_NOTIFY` to accelerate rootless containers: https://github.com/rootless-containers/bypass4netns

This is not an attempt to harden privileged containers beyond as it is.

**Review by tonistiigi — APPROVED** [review]
Overall LGTM and I think this is correct design.

But we should verify that all the individually controllable options also bundled into `--privileged` behave the same way. Atm. it looks like they do but it has not been verified and ideally should have individual test cases.

It would also be nice if there was a clear security scope definition(if there isn't already) , for example https://github.com/moby/buildkit/blob/master/PROJECT.md#security-boundary that would make it clear that `--privileged` is still considered insecure for security, no matter if you also use a different flag as well.

**Comment by thaJeztah** [comment]
@neersighted do you have a strong objection against this one? Overall, I think it's fine to do this, and it seems like a more logical option than silently discarding the user's preference (we should either _error_ or _accept_, not "discard").

We should make sure that we're clear in the docs what the expectation is though; @dvdksn has a PR pending in the CLI;

- https://github.com/docker/cli/pull/4929

I think that one is "good enough" for now, but we should probably outline that _even if_ we accept options like this, a `--privileged` container won't be able to provide full guarantees, as the reduced security could allow a compromised container to "undo" some of the (security) options that were set. (e.g., escaping the container's filesystem, and modify the container's config).

**Comment by neersighted** [comment]
Ah, circling back, we talked about this in a recent maintainers' call, and my takeaway is we probably should allow it, but we'd like to figure out what the semantics for all security-opt combinations with `--privileged` (ideally making them as consistent as possible) are and add some decent tests here, as the current semantics are quite unclear from the code.

I don't necessarily think we need to block everything on reaching that ideal state, but given there is more and more demand re: combining or decomposing `--privileged`, I think we need to make this happen sooner than later/spend some serious effort on it (cc @klueska).

File: integration/container/run_linux_test.go [hunk 1]
```diff
@@ -326,3 +326,49 @@ func TestStaticIPOutsideSubpool(t *testing.T) {
...
+		{
+			// A custom profile should be still enabled, even when --privileged is set
+			// https://github.com/moby/moby/issues/47499
+			ops:              []func(*container.TestContainerConfig){container.WithPrivileged(true), container.WithSecurityOpt("seccomp=" + confined)},
+			expectedExitCode: 1,
+		},
+	}
+	for _, tc := range testCases {
+		cID := container.Run(ctx, t, apiClient, tc.ops...)
+		res, err := container.Exec(ctx, apiClient, cID, []string{"wget", "-O-", "http://1.1.1.1"})
```
Comment (cpuguy83) [inline integration/container/run_linux_test.go:367]: Maybe this should be connecting to a local service?

**Review by cpuguy83 — CHANGES_REQUESTED** [review]

File: integration/container/run_linux_test.go (hunk 1 above)
Comment (AkihiroSuda) [reply integration/container/run_linux_test.go:367]: Why?

Comment (cpuguy83) [reply integration/container/run_linux_test.go:367]: One of the tests is going to hit it, why make it hit an external endpoint?

Comment (AkihiroSuda) [reply integration/container/run_linux_test.go:397]: Sounds complicated, maybe the test should be modified to avoid socket syscalls

Comment (cpuguy83) [reply integration/container/run_linux_test.go:396]: If you have another syscall in mind that seems ok.
The container could also setup netcat or something on localhost.

Comment (cpuguy83) [reply integration/container/run_linux_test.go:396]: Maybe the profile could block `socket` and we don't need to do anything special?

Comment (thaJeztah) [reply integration/container/run_linux_test.go:396]: Was `connect` picked on purpose here? Or we just needed "something to block"?

Could we block something silly like `chown` or `chmod` ?

Comment (AkihiroSuda) [reply integration/container/run_linux_test.go]: Updated to use `chown`

**Review by cpuguy83 — APPROVED** [review]

**Comment by thaJeztah** [comment]
One thing I'm wondering, but perhaps could be handled in a follow-up; should this combination be ignored for old API versions? On current versions of Moby (thus API v1.45 and before), passing a seccomp profile will be ignore, so effectively reset to `seccomp=unconfined`. This PR changes that, but also means that the change is regardless of API version used, so when making the same API call on an older version of the engine with the same API version will produce a different outcome.

**Review by thaJeztah — APPROVED** [review]
change otherwise still LGTM

but happy to hear what we should do with API version 🙈

**Comment by thaJeztah** [comment]
Added a docs/revisit label because we may have to touch-up some documentation related to this; for example this section mentions "disables the _DEFAULT_ seccomp profile" which is somewhat ambiguous; https://docs.docker.com/reference/cli/docker/container/run/#privileged

Screenshot 2024-06-10 at 18 47 07

**Comment by thaJeztah** [comment]
@AkihiroSuda failure on ARM64 (Jenkins) could be related; could you have a look?

```
=== RUN   TestSeccomp
    run_linux_test.go:398: assertion failed: 1 (tc.expectedExitCode int) != 0 (res.ExitCode int)
--- FAIL: TestSeccomp (1.49s)
```

**Comment by AkihiroSuda** [comment]
TIL: "The chmod/chown/rename syscalls never existed on AArch64" 👀 
https://gitlab.torproject.org/tpo/core/tor/-/merge_requests/574

**Comment by thaJeztah** [comment]
> TIL: "The chmod/chown/rename syscalls never existed on AArch64" 👀

TIL as well!

And there I thought it was a good suggestion (simple syscall to use for the test)

**Review by thaJeztah — APPROVED** [review]
still LGTM
