### PR TITLE
Fix cpu spin waiting for log write events

### LINKED ISSUE #31060: 100% CPU usage on docker 1.13.1
Getting 100% CPU erratically on 1.13.1 once this starts happening `dockerd` uses 100% on all cores till restarted. 

```
~# docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:42:29 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:42:29 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
root@tiefighter21:~# docker info
Containers: 10
 Running: 10
 Paused: 0
 Stopped: 0
Images: 309
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 521
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.19.0-65-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.37 GiB
Name: tiefighter21.sjc1.discourse.org
ID: OUAL:ATX4:IVBF:YGEV:XXSH:CZZG:B634:PGUZ:2ZK6:7QTL:TY7E:ZWWI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: 5eedb751
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true
```

I have a data-structure dump but it contains sensitive env vars, thread dump is:

https://gist.github.com/SamSaffron/84da3bb794cb901cd9a36194100ffc71

Also while this is happening noticing this in the logs: 

```
time="2017-02-15T21:20:51.744872734Z" level=error msg="Error closing logger: invalid argument"
time="2017-02-15T21:21:03.907878784Z" level=error msg="Error closing logger: invalid argument"
```

Anything else I can provide to help debugging this?

### PR DESCRIPTION
**Pull request by cpuguy83**
This loop is not ever going to return since it's never actually setting
the `err` var except on the first iteration.

Fixes #31060

### CODE REVIEW

**Comment by tonistiigi** [comment]
LGTM

File: daemon/logger/jsonfilelog/read.go [hunk 1]
```diff
@@ -256,7 +256,7 @@ func followLogs(f *os.File, logWatcher *logger.LogWatcher, notifyRotate chan int
 
 	handleDecodeErr := func(err error) error {
 		if err == io.EOF {
-			for err := waitRead(); err != nil; {
+			for err := waitRead(); err != nil; err = waitRead() {
```
Comment (LK4D4) [inline daemon/logger/jsonfilelog/read.go]: this construction looks extremely confusing for me, why don't just use for {} and do stuff inside?

Comment (cpuguy83) [inline daemon/logger/jsonfilelog/read.go]: Yep, makes sense.
Updated.

**Comment by cpuguy83** [comment]
This is ready.

**Review by dnephin — APPROVED** [review]
LGTM
