### PR TITLE
logger/journald: fix tailing logs with systemd 255

### LINKED ISSUE #46983: Logs are not followed when using journald log-driver with systemd 255
### Description

When `journald` log-driver is used, running `docker logs --follow --tail` would not follow logs if started before any output is produced.

### Reproduce

1. Enable journald logging driver by putting `{ "log-driver": "journald" }` into `/etc/docker/daemon.json`.

2. Run the following script:

```sh
#!/bin/sh
trap 'docker kill logs-test' EXIT
docker kill logs-test

docker run --rm --name logs-test --detach alpine sh -c 'sleep 1; while sleep 0.1; do echo $((N++)); done'
# sleep 2
docker logs --follow --tail 1 logs-test
```

### Expected behavior

Expected result: it should print container output, i.e.,`0`,  `1`, `2`, `3`, and so on.

Actual result: it prints nothing. However, if you un-comment the `sleep 2` line, it will print the numbers as expected.

### docker version

```bash
Client:
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.21.3
 Git commit:        afdd53b4e3
 Built:             Sun Oct 29 15:42:02 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.21.3
  Git commit:       311b9ff0aa
  Built:            Sun Oct 29 15:42:02 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.11
  GitCommit:        64b8a811b07ba6288238eefc14d898ee0b5b99ba.m
 runc:
  Version:          1.1.10
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.7
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: btrfs
  Supports d_type: true
  Using metacopy: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: journald
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 64b8a811b07ba6288238eefc14d898ee0b5b99ba.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.6.7-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.926GiB
 Name: archlinux
 ID: bb0ac9f5-421b-45df-9718-ef4d1d752224
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by corhere**
- Fixes #46983 

**- What I did**
- Made journald read tests compatible with systemd version 255
- Made journald reader compatible with systemd version 255

**- How I did it**
By fixing the journald reader to no longer rely upon an invalid assumption about the `sd-journal` reader API. See the individual commit messages for more details.

**- How to verify it**
The journald reader tests pass in the dev container / CI (systemd 253) and in an archlinux container with systemd 255 installed.

**- Description for the changelog**

- Fixed an issue with the journald log driver which prevented container logs from being followed correctly in certain circumstances when used with systemd version 255.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: daemon/logger/journald/read.go [hunk 1]
```diff
@@ -99,101 +101,163 @@ func getAttrs(d map[string]string) []backend.LogAttr {
...
+	for {
+		dur := 250 * time.Millisecond
+		if !r.drainDeadline.IsZero() {
+			now := time.Now()
+			if now.Add(dur).After(r.drainDeadline) {
+				dur = r.drainDeadline.Sub(now)
+				if dur < 0 {
+					return false, nil
+				}
 			}
```
Comment (vvoland) [inline daemon/logger/journald/read.go:204]: Isn't `dur < 0` only true if `now.After(r.drainDeadline)`? Which would effectively reduce this into:

```suggestion
			if time.Now().After(r.drainDeadline) {
			    return false, nil
			}
```

making the `dur` irrelevant?

File: daemon/logger/journald/read.go [hunk 2]
```diff
@@ -99,101 +101,163 @@ func getAttrs(d map[string]string) []backend.LogAttr {
...
+		return r.j.Next()
+	}
+	return true, nil
+}
+
+// wait blocks until the journal has new data to read, the reader's drain
+// deadline is exceeded, or the log reading consumer is gone.
+func (r *reader) wait() (bool, error) {
+	for {
+		dur := 250 * time.Millisecond
```
[the remark this answers is not in the document]
Comment (corhere) [reply daemon/logger/journald/read.go:196]: 🤦 Yes, yes it is. How'd I manage to define and use that constant in one commit, then drop it in the following commit?

[the remark this answers is not in the document]
Comment (thaJeztah) [reply daemon/logger/journald/read.go:196]: Proof that you're _human_ 

(also: thanks @vvoland for reviewing!! ❤️)

File: daemon/logger/journald/read.go (hunk 1 above)
Comment (corhere) [reply daemon/logger/journald/read.go:204]: > Isn't `dur < 0` only true if `now.After(r.drainDeadline)`?

Yes, but it is not necessarily true if `now.Add(dur).After(r.drainDeadline)`. This code is capping the wait duration to not overshoot the drain deadline, with an early exit if the deadline has already passed.

Comment (vvoland) [reply daemon/logger/journald/read.go:204]: Ugh, right! I missed the `status, err := r.j.Wait(dur)` below 🤦🏻

Comment (corhere) [reply daemon/logger/journald/read.go]: Now this code block is what it should have been all along, moving but not rewriting https://github.com/moby/moby/pull/47019/commits/afb3921dcedccd84874353399289cacae6f170a8. (It's easy to make mistakes when rewriting history if you're not careful!)

**Comment by vvoland** [comment]
LGTM; the linter has some very arguable complaint though 😭 

```
 daemon/logger/journald/read.go:198:10: S1024: should use time.Until instead of t.Sub(time.Now()) (gosimple)
			dur = r.drainDeadline.Sub(time.Now())
			      ^
```

**Review by vvoland — APPROVED** [review]

**Review by cpuguy83 — APPROVED** [review]
