### PR TITLE
Fix AppArmor not being applied to Exec processes

### LINKED ISSUE #36456: apparmor profile is not effect
**Description**

When I apply a custom apparmor to a container that uses docker-ce 17.12 docker neglects the apparmor profile as if it uses the docker-default apparmor profile.
This behaviour is ONLY reproducible with docker-ce 17.12.0~ce-0~ubuntu, but it works correctly with docker-ce 17.09.1~ce-0~ubuntu

**Steps to reproduce the issue:**
1. Add a custom apparmor profile that denies writes under /tmp/:

```
$ apparmor_parser -q -r <<EOF
#include <tunables/global>
profile deny-write flags=(attach_disconnected) {
  #include <abstractions/base>
  file,
  network,
  deny /tmp/** w,
  capability,
}
EOF
```

2. Run any test container with the "deny-write" apparmor profile:

```
$ docker run -itd --security-opt "apparmor=deny-write" --name httpd-aa httpd
```

3. Exec into the container:

```
$ docker exec -it httpd-aa bash
root@e48cf7443752:/usr/local/apache2#
```

4- Create a dir/file under /tmp

```
$ root@e48cf7443752:/usr/local/apache2# mkdir /tmp/test
```

**Describe the results you received:**

```
root@e48cf7443752:/usr/local/apache2# mkdir /tmp/test
root@e48cf7443752:/usr/local/apache2#
```

**Describe the results you expected:**

```
root@e48cf7443752:/usr/local/apache2# mkdir /tmp/test
mkdir: cannot create directory '/tmp/test': Permission denied
root@e48cf7443752:/usr/local/apache2#   
```

**Additional information you deem important (e.g. issue happens only occasionally):**

This happens with docker-ce 17.12.0~ce-0~ubuntu, and does not happen with docker-ce 17.09.1~ce-0~ubuntu

**Output of `docker version`:**

```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:11:19 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:53 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 17.12.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 11
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1052-aws
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.303GiB
Name: ip-10-66-97-65
ID: IIXT:5RGZ:QLTU:JXGI:B2W3:JJXD:Q6H7:KQMY:OATP:DSOI:SDUY:4XQ2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS EC2 m3.large
Ubuntu 16.04.3 LTS
Kernel: 4.4.0-1052-aws

### PR DESCRIPTION
**Pull request by thaJeztah**
fixes https://github.com/moby/moby/issues/36456

Exec processes do not automatically inherit AppArmor profiles from the container.

This patch sets the AppArmor profile for the exec process.

Before this change:

```bash
apparmor_parser -q -r <<EOF
#include <tunables/global>
profile deny-write flags=(attach_disconnected) {
  #include <abstractions/base>
  file,
  network,
  deny /tmp/** w,
  capability,
}
EOF

docker run -dit --security-opt "apparmor=deny-write" --name aa busybox
```

Running `docker exec` doesn't get the profile applied:

```bash
docker exec aa sh -c 'mkdir /tmp/test'
(no error)
```

With this change:

Running `docker exec` gets the AppArmor profile applied

```bash
docker exec aa sh -c 'mkdir /tmp/test'
mkdir: can't create directory '/tmp/test': Permission denied
```

**- How to verify it**

Build a `.deb` from this PR, using the Docker CE packaging scripts; https://github.com/docker/docker-ce-packaging/tree/master/deb

```bash
make \
  ENGINE_DIR=$GOPATH/src/github.com/docker/docker \
  CLI_DIR=$GOPATH/src/github.com/docker/cli \
  ubuntu-xenial  
```

Which puts the package in `debbuild/ubuntu-xenial`

On an Ubuntu 16.04 machine, install the package:

```bash
dpkg -i ./docker-ce_0.0.0~dev~git20180302.121756.0.dae4588d4-0~ubuntu_amd64.deb
```

Run the reproduction steps above

**- Description for the changelog**

```Markdown
* Fix AppArmor profiles not being applied to `docker exec` processes [moby/moby#36466](https://github.com/moby/moby/pull/36466)
```

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @justincormack @mlaventure PTAL

File: daemon/exec_linux_test.go [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+	containertypes "github.com/docker/docker/api/types/container"
+	"github.com/docker/docker/container"
+	"github.com/docker/docker/daemon/exec"
+	"github.com/gotestyourself/gotestyourself/assert"
+	"github.com/opencontainers/runc/libcontainer/apparmor"
+	"github.com/opencontainers/runtime-spec/specs-go"
+)
+
+func TestExecSetPlatformOpt(t *testing.T) {
+	if !apparmor.IsEnabled() {
```
Comment (thaJeztah) [inline daemon/exec_linux_test.go]: For reference; looks like this check also checks for an `CONTAINER` env-var; https://github.com/moby/moby/blob/f58aa31075bf74ab8d2369dafb591ae43ed36ee6/vendor/github.com/opencontainers/runc/libcontainer/apparmor/apparmor.go#L11-L20

But our integration-cli checks in a different way; https://github.com/moby/moby/blob/f58aa31075bf74ab8d2369dafb591ae43ed36ee6/integration-cli/requirements_test.go#L110-L113

**Review by mlaventure — APPROVED** [review]
LGTM.

Failure seems to be related to libnetwork, restarting the ci

**Review by justincormack — APPROVED** [review]
