### PR TITLE
pkg/archive: adjust chmod bits on windows

### LINKED ISSUE #11047: Proposal: Handling of permission bits for image context created via Windows
## Problem

Converting Windows file attributes + ACLs to 9-bit UNIX permissions when
docker images are built from windows CLI. Concept of 'execute' doesn't
match 1:1 on Windows vs POSIX.

### Scenario

1. User downloads Docker client for Windows (docker.exe)
2. User develops an "app" to run on Linux containers.
3. User runs the command `docker build .`
4. Context tar is created on client-side and transferred to daemon (running on Linux) for building.

### Problem steps:

1. Let's say the "app" is actually something user cloned from a remote git repo.
2. Repo had a `setup.sh` script (`chmod +x`ed)
3. There's no `x` bit on windows, so during `git clone` we lost that bit
4. Today all files packaged to context from windows get `-rw-rw-rw-` permissions.
5. This can also happen if user unzips a file or downloads from ftp etc.
6. If user tries to `RUN ./setup.sh` or `ENTRYPOINT ./setup.sh` it will fail
   due to a vague "permission denied" error because script was not `chmod +x`ed.
7. Result: a dockerfile that builds correctly fine from OS X/Linux cli has failed on windows.
8. User will take a lot of time to figure `+x` bit was missing.
9. User will go add `RUN chmod +x setup.sh` as a dockerfile instruction if they're
   building from Windows.

### Root cause 1: No 'x' (execute) bit on Windows

* Windows does not have an execute permission as the 'x' bit in Unix
* By default, almost all files are executable on windows. (different than unix)
* You can execute a binary if the extension is exe/bat/cmd/com/ps1 etc.
* Windows executable permission is more about dynamically linked libraries (dlls) etc.
* It's not widely used.
* Does not correspond to executability concept in Unix.
* Every time user grabs a `+x`ed file from ftp/git/unzip/samba, we lose that
  unix bit on windows, because it's not the same thing.

Quoting from [SAMBA book](http://www.oreilly.com/openbook/samba/book/ch05_03.html):

> “Note that there is no bit to specify that a file is executable. DOS and Windows NT filesystems identify executable files by giving them the extensions .EXE, .COM, .CMD, or .BAT. [...] Samba can preserve these bits by reusing the executable permission bits of the file on the Unix side - if it is instructed to do so. Mapping these bits, however, has an unfortunate side-effect: if a Windows user stores a file in a Samba share, and you view it on Unix with the ls -al command, some of the executable bits won't mean what you'd expect them to.”

### Root cause 2: Go Windows Problems

Golang's os.Stat implementation is **very poor**:
 
* It cannot figure out executability. (because it's not a file attribute on
  Windows but an ACL setting –found out through a separate syscall, not implemented in golang)
* It returns same permissions for all user/group/others sections:
    * Because there's no group/everybody concept on Windows as in chmod bits.
    * That's why it returns `-rw-rw-rw-` for all files on Windows and that's the permission what files copied to a docker build context gets by default.
    * This is dangerous (imagine a private key being set to `-rw-rw-rw-` permissions by default, that's the state we're in now).

We are hoping to address problems in golang in the long term. (fingers crossed)

## Solution

1. We are going to clear all 'group/others' bits: `-???------`
    * Since we're clearing `r` from group/others, this might break multi-user docker images.
2. We are going to copy r/w bits we got from golang os.Stat(). 
3. **We are going to add `+x` to all files packaged from windows.** :boom:
    * This way we can at least have `+x` on all files and can support executing `./binary` or `./script.sh` from shell.
    * This may break some apps that decline `+x`ed files as input. I haven't really heard of anything like that,
      must be a really rare case. Even so user can have `RUN chmod -x` to remove that bit manually
    * Security issue: We are making **everything** executable. Could be. :exclamation: Please discuss.
4. We are going to add a notice for windows CLI: `WARNING: Permission bits on files added to image might not be correctly set.` :new:

### Proposed Fix

We modify the perm bits of the tar header created via `tar.FileInfoHeader`
with a simple platform-specific helper method. (see code)

We are also going to change the expected permission string
on the integration-cli test cases when executed on windows.

### Result

We will end up with a docker image in which all files copied from
Windows filesystem have (1) grp/others bits cleared (2) `+x` added
regardless of it should have `+x` because it does no harm.

Behavior on Linux/Mac CLIs are unchanged.

-----

I really appreciate your input on this. That's the only thing left prevents us from getting green on Windows client CI.

cc: @ewindisch @crosbymichael @cpuguy83 @tianon @tiborvass @jfrazelle @icecrime @johngossman @sachin-jayant-joshi @jhowardmsft

### PR DESCRIPTION
**Pull request by ahmetb**
- Followup to proposal at #11047

This change modifies the chmod bits of build context archives built on
windows to preserve the execute bit and remove the r/w bits from
grp/others.

I just created a post-processing step to modify tar headers retrieved from
tar.FileInfoHeader() method. This fixes tests:
- TestBuildAddSingleFileToRoot
- TestBuildAddWholeDirToRoot
- TestBuildCopySingleFileToRoot
- TestBuildCopyWholeDirToRoot

Also adjusted integration-cli tests to verify permissions based on the platform
the tests are running. Fixes #11047.

Signed-off-by: Ahmet Alp Balkan ahmetalpbalkan@gmail.com
cc: @duglin @tiborvass @icecrime @jfrazelle @tianon

### CODE REVIEW

**Comment by tianon** [comment]
LGTM although I'm uncertain on what the best path might be for group/other bits

File: integration-cli/test_vars_windows.go [hunk 1]
```diff
@@ -5,4 +5,6 @@ package main
 const (
 	// identifies if test suite is running on a unix platform
 	isUnixCli = false
+
+	expectedFileChmod = "-rwx------"
```
Comment (tiborvass) [inline integration-cli/test_vars_windows.go]: @ahmetalpbalkan could you please reference #11047 in a comment ?

Comment (ahmetalpbalkan) [inline integration-cli/test_vars_windows.go]: fixed

**Comment by duglin** [comment]
LGTM

**Comment by ahmetalpbalkan** [comment]
> https://jenkins.dockerproject.com/job/Windows-PRs/96/console
--- PASS: TestBuildAddSingleFileToRoot (4.11s)
--- PASS: TestBuildAddWholeDirToRoot (4.09s)
--- PASS: TestBuildCopySingleFileToRoot (3.25s)
--- PASS: TestBuildCopyWholeDirToRoot (4.37s)

Tests fixed on windows.

File: pkg/archive/archive_windows.go [hunk 2]
```diff
@@ -23,6 +24,17 @@ func CanonicalTarNameForPath(p string) (string, error) {
 	return strings.Replace(p, "\\", "/", -1), nil
 }
 
+// chmodTarEntry is used to adjust the file permissions used in tar header based
+// on the platform the archival is done.
+func chmodTarEntry(perm os.FileMode) os.FileMode {
+	// Clear r/w on grp/others: no precise equivalen of group/others on NTFS.
+	perm &= 0711
```
Comment (tiborvass) [inline pkg/archive/archive_windows.go]: @ahmetalpbalkan is it `11` just in case the `x` bit is set for some magical reasons? :)

Comment (ahmetalpbalkan) [inline pkg/archive/archive_windows.go]: @tiborvass I didn't want to clear the +x on grp/others. (i.e. directories)

Comment (ahmetalpbalkan) [inline pkg/archive/archive_windows.go]: @tiborvass so direct answer to your question is, directory entries are also passed to this method and we already have `x` bit on those from os.Stat, we don't want to clear those bits.

Comment (ahmetalpbalkan) [inline pkg/archive/archive_windows.go]: ping @tiborvass for review

Comment (jhowardmsft) [inline pkg/archive/archive_windows.go]: in archive_windows.go, should you be using os.PathSeparator rather than hard coding?

Comment (ahmetalpbalkan) [inline pkg/archive/archive_windows.go]: @jhowardmsft i'm not sure which one are you referring to can you please come out on that line?

File: pkg/archive/archive_windows.go [hunk 3]
```diff
@@ -23,6 +24,17 @@ func CanonicalTarNameForPath(p string) (string, error) {
 	return strings.Replace(p, "\\", "/", -1), nil
```
Comment (jhowardmsft) [inline pkg/archive/archive_windows.go]: This line should be using os.PathSeparator rather than "\\"

Comment (ahmetalpbalkan) [inline pkg/archive/archive_windows.go]: that's probably out of scope of this PR. but you're right. I'll submit a PR separately.

**Comment by ahmetalpbalkan** [comment]
@tianon re-LGTM maybe?

**Comment by tiborvass** [comment]
LGTM

**Comment by tiborvass** [comment]
I wonder whether we need docs to explain the "issue".

**Comment by ahmetalpbalkan** [comment]
@tiborvass hmm we don't have any windows docs at all at this point. I will create an issue now and you can assign that to me.

**Comment by ahmetalpbalkan** [comment]
@tiborvass :heart: :cocktail: :notes:

**Comment by mitchcapper** [comment]
This is a bit overkill for windows as you have the default windows permissions now at "-rwx------" rather than the linux permissions of "-rw-r--r--".   Having new files added to containers not be group/world readable is a big downside and probably not expected.  I agree group/world writeable is not a good idea but removing all read permissions is probably too far.  I would assume a 0755 would be a more appropriate mask override.   In addition windows users can build tar archives with proper permissions (ie --owner 0 --mode 755)  so it may be better rather than masking all permissions in windows to only look for the bad permission of 666 (default for tarred items for windows) and changing that to 755 or 644.  

I don't think this commit is also the cause of the ADD/COPY behavior change but I may be wrong.  As now with Add doing similar doing an ADD then running as a restricted user will now fail if a chown is not done so:
FROM busybox
RUN adduser -D bob
ADD test.conf /tmp/
USER bob
CMD cat /tmp/test.conf

will fail with permission denied.  (Also while the commit seems to primarily deal with archives I noticed the change to default file permissions above.

**Comment by ahmetalpbalkan** [comment]
@mitchcapper main reason we cleared the permissions from others/group is because people might assume they set the correct permissions on NTFS and those ACLs cannot be translated to unix formats. Assumption here was people are not very commonly using `USER ...` in their dockerfiles. I don't really think it's extreme, as IMO it's better than stuff like private keys being '-rw-r--r--' without letting the user know. We should also add some warning probably here to let people know they're running on windows and they will not achieve the same high fidelity ACLs against linux hosts (in fact I forgot to add that).

Feel free to come up with other proposal, I'd happily review but this is basically result of what we discussed in #11047.

**Comment by mitchcapper** [comment]
I 100% agree with you on the fact  people are not commonly using USER,  the problem is this is recommended practice from a security perspective.   Running as root (even containered root priv dropped rooot) is probably a bad idea.   Docker is fairly hard to run as non-user, which is a whole separate discussion, but I figured this behavior is only making it all the harder to run as a non-root user.     I am not sure I agree with the private key aspect.   

1) As most people run the container as root anyway unless they are priv dropping once inside the container (which would still not be as good as running the container as a user)  its not really keeping the private key more secure.

2) Sensitive information should generally not be inserted into containers (I believe that is also best practice) and why there is a whole other discussion on how to keep it out of containers.

3)  Private keys are probably a very small fraction of what is added to the container, with other items far more common, and while convenience over security is not great there has to be some line

4) You shouldn't ever make permissions less strict down the road.  Right now this is just in HEAD but once it goes to a release you don't want to ever say well, maybe we shouldn't be removing all global/group permissions and change it (as then you have made peoples builds less secure).  It would be far better to apply a less aggressive masking leaving read access (or preferably even read/execute) for group/user alone.  It would break fewer peoples current builds, and I don't think there is a whole lot of expectation of security in windows that when you call ADD or COPY on a windows files it will by default be root only readable. 

I missed the boat on the other proposal and realize the input is far after the fact, but figured I would comment my 2cents.  I am all for security, and do a decent bit of work to run containers with least privs possible, but am not sure this will work to improve it (even at the cost of convenience).   This masking I think will truly weaken good user behavior (as more dockerfiles just wont work as users other than root out of the box), in exchange for protecting bad user behavior (adding sensitive information into containers and expecting privacy by default).
