### PR TITLE
fix flaky test TestImportFileWithMessage

### LINKED ISSUE #23045: Flaky test: TestImportFileWithMessage
Observed in https://github.com/docker/docker/pull/23041

https://jenkins.dockerproject.org/job/Docker-PRs-experimental/19025/console
```
04:33:40 ----------------------------------------------------------------------
04:33:40 FAIL: docker_cli_import_test.go:88: DockerSuite.TestImportFileWithMessage
04:33:40 
04:33:40 docker_cli_import_test.go:103:
04:33:40     out, _ := dockerCmd(c, "import", "-m", message, temporaryFile.Name())
04:33:40 /go/src/github.com/docker/docker/pkg/integration/dockerCmd_utils.go:42:
04:33:40     c.Assert(err, check.IsNil, check.Commentf(quote+"%v"+quote+" failed with errors: %s, %v", strings.Join(args, " "), out, err))
04:33:40 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc8202a2540)} ("exit status 1")
04:33:40 ... "import -m Testing commit message /tmp/exportImportTest239460469" failed with errors: An error occurred trying to connect: Post http://%2Fgo%2Fsrc%2Fgithub.com%2Fdocker%2Fdocker%2Fbundles%2F1.12.0-dev%2Ftest-integration-cli%2Fdocker.sock/v1.24/images/create?fromSrc=-&message=Testing+commit+message&repo=&tag=: read unix @->/go/src/github.com/docker/docker/bundles/1.12.0-dev/test-integration-cli/docker.sock: read: connection reset by peer
04:33:40 , exit status 1
04:33:40 
04:33:41 
04:33:41 ----------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by mountkin**
**\- What I did**
Fixes #23045
**\- How I did it**
Fixed the `index out of range` error in the  `MalformedHostHeaderOverrideConn` reader.

**\- How to verify it**
`TESTFLAGS='-check.f DockerSuite.TestImportFileWithMessage' make test-integration-cli`
**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**

Signed-off-by: Shijiang Wei mountkin@gmail.com

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
(non-binding) could you please add a test to malformed_host_override_test.go?

**Comment by mountkin** [comment]
Test updated.
It seems that the former test of `TestHeaderOverrideHack` is incorrect. It only tested the first case, all the other cases were constantly passing because length of the `read` slice was truncated to zero after the first test.
Moreover, the former test reused the pipe for each test, the 5th test would read the remaining data in the pipe that had been written by the 4th case rather than the real test data of itself.

**Comment by mountkin** [comment]
Janky failure seems unrelated to this change.

**Comment by runcom** [comment]
How do I trigger that index out of range error? Ping @cpuguy83 @LK4D4 also

File: cmd/dockerd/hack/malformed_host_override_test.go [hunk 1]
```diff
@@ -33,27 +41,32 @@ func TestHeaderOverrideHack(t *testing.T) {
...
+			[]byte("GET /foo\nUser-Agent: Docker\r\n\r\n" + strings.Repeat("test", 15000)),
+			[]byte("GET /foo\nUser-Agent: Docker\r\n\r\n" + strings.Repeat("test", 15000)),
+		},
 	}
-	l := MalformedHostHeaderOverrideConn{client, true}
-	read := make([]byte, 4096)
+
+	h0 := "GET /foo\nUser-Agent: Docker\r\n\r\n"
+	h0 = h0 + strings.Repeat("a", 4096-len(h0)-1) + "\n"
+	tests = append(tests, [2][]byte{[]byte(h0), []byte(h0)})
```
Comment (mountkin) [inline cmd/dockerd/hack/malformed_host_override_test.go]: @runcom  This triggered the `index out of range`

Comment (runcom) [inline cmd/dockerd/hack/malformed_host_override_test.go]: I meant, this index out of range was from some failed test in some pull request or?

Comment (mountkin) [inline cmd/dockerd/hack/malformed_host_override_test.go]: More precisely, if '\n' appears in the last 7 bytes of the first 4096 bytes, the `index out of range` error will be triggered because `i+n` will be greater than 4095.

Comment (mountkin) [inline cmd/dockerd/hack/malformed_host_override_test.go]: @runcom Please take a look at https://jenkins.dockerproject.org/job/Docker-PRs-experimental/19025/artifact/bundles.tar.gz

Comment (mountkin) [inline cmd/dockerd/hack/malformed_host_override_test.go]: And this one https://jenkins.dockerproject.org/job/Docker-PRs-userns/10037/artifact/bundles.tar.gz

**Comment by runcom** [comment]
alright, I got the panic as well, I'll test this out now

**Comment by runcom** [comment]
LGTM thanks!!! ping @cpuguy83 @LK4D4

**Comment by LK4D4** [comment]
LGTM

**Comment by bboreham** [comment]
Note the title understates what this fixes - a suitably malformed request would have crashed the daemon.
