### PR TITLE
Use naive diff for overlay2 when opaque copy up bug present

### LINKED ISSUE #25244: Disappearing npm packages when building with overlay2
We're having an issue where a Dockerfile that used to build with overlay FS fails to build in overlay2. After some investigation I've cut it down to a very simple Dockerfile that reproduces the issue:

```
FROM node:4.4.7

RUN npm install -g npm

RUN npm install -g jshint

RUN npm install -g mocha
```

Building this with overlay works as expected, however building it with overlay2 fails on the final step with:
`/bin/sh: 1: npm: not found`
Looking at the individual layers reveals that this is because the /usr/local/lib/node_modules/npm directory has disappeared during the second RUN command. In our real Dockerfile, there are several npm packages installed in that directory which all disappear. The only package left is the new one in that command (jshint in the above example)
Note that running a container from node:4.4.7 and running those commands manually works perfectly fine, with both overlay and overlay2.

**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 1.12.0
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.35 GiB
Name: lp02488
ID: 6KEQ:SM2A:GBFZ:NIW4:72MA:LEN5:QR6J:QMSU:Y4M6:6DKA:ITNK:EE75
Docker Root Dir: /space/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
The node:4.4.7 image uses debian 8.5, however I've tried similar steps with an ubuntu-based container with npm installed and have had the same problem.

**Steps to reproduce the issue:**
1. Run `docker build --no-cache -t test .` using the above Dockerfile
2. If successful, run `docker run --rm -ti test npm list -g --depth 0` to list the installed packages

**Describe the results you received:**
Using overlay:
The Dockerfile builds as expected. The npm command lists all three installed packages.
Using overlay2:
The Dockerfile fails at the last RUN command with:
`/bin/sh: 1: npm: not found`
Investigation shows that the npm global install folder has been replaced with just the most recent package (which has therefore removed the globally-installed npm)

**Describe the results you expected:**
The Dockerfile should build properly on both overlay and overlay2

**Additional information you deem important (e.g. issue happens only occasionally):**
This seems to occur regardless of what the second two packages are, however it only goes wrong if the command `npm install -g npm` is first, in which case it goes wrong in the next command that plays with /usr/local/lib/node_modules , e.g.:

This fails on `RUN npm install -g mocha`:

```
FROM node:4.4.7

RUN npm install -g npm

RUN npm install -g jshint

RUN npm install -g mocha

RUN npm install -g supertest

RUN npm install -g chai
```

This fails on `RUN npm install -g jshint`:

```
FROM node:4.4.7

RUN npm install -g npm

RUN touch /usr/local/lib/node_modules/test

RUN npm install -g jshint

RUN npm install -g mocha

RUN npm install -g supertest

RUN npm install -g chai
```

This fails on `RUN npm install -g mocha` again:

```
FROM node:4.4.7

RUN npm install -g npm

RUN touch /test.txt

RUN npm install -g jshint

RUN npm install -g mocha

RUN npm install -g supertest

RUN npm install -g chai
```

However this completes successfully:

```
FROM node:4.4.7

RUN npm install -g jshint

RUN npm install -g npm

RUN npm install -g mocha

RUN npm install -g supertest

RUN npm install -g chai
```

As does this (though obviously the npm list doesn't work because of the touched file):

```
FROM node:4.4.7

RUN touch /usr/local/lib/node_modules/test

RUN npm install -g npm

RUN npm install -g jshint

RUN npm install -g mocha

RUN npm install -g supertest

RUN npm install -g chai
```

But this fails on `RUN npm install -g mocha` again:

```
FROM node:4.4.7

RUN touch /usr/local/lib/node_modules/test && rm -f /usr/local/lib/node_modules/test

RUN npm install -g npm

RUN npm install -g jshint

RUN npm install -g mocha

RUN npm install -g supertest

RUN npm install -g chai
```

All the above were built with `docker build --no-cache -t test .`. When I say "fails on", I mean that that step reported npm as not found (so it had disappeared by then). They all work perfectly fine (as in, they don't accidentally delete npm) in overlay.

### PR DESCRIPTION
**Pull request by dmcgowan**
**- What I did**

Update overlay2 driver to use naive diff when kernel has bug which copies up opaque directory flag

**- How I did it**

Added a check on kernels older than 4.8 for the bug.

**- How to verify it**

Run this Dockerfile on kernel without patched fix and should work

```
FROM alpine

RUN mkdir /dir1 && touch /dir1/f1
RUN rm -rf /dir1 && mkdir /dir1 && touch /dir1/f2
RUN touch /dir1/f3 
RUN [ -f /dir1/f2 ]
```

Closes #25244
... for all kernels which support overlay2

Ping @tonistiigi

### CODE REVIEW

File: daemon/graphdriver/overlay2/overlay.go [hunk 1]
```diff
@@ -174,6 +175,14 @@ func Init(home string, options []string, uidMaps, gidMaps []idtools.IDMap) (grap
 		}
 	}
 
+	// If kernel is older than 4.8, check whether opaque copy up bug has been patched
+	if kernel.CompareKernelVersion(*v, kernel.VersionInfo{Kernel: 4, Major: 8, Minor: 0}) < 0 {
```
Comment (tonistiigi) [inline daemon/graphdriver/overlay2/overlay.go]: We could do this like https://github.com/docker/docker/blob/master/daemon/graphdriver/aufs/aufs.go#L643 with `sync.Once` and lazy loading. Kernel check could probably be skipped then.

**Review by tonistiigi — COMMENTED** [review]
Would be good to add a test for #25244

File: daemon/graphdriver/overlay2/overlay.go [hunk 2]
```diff
@@ -174,6 +175,14 @@ func Init(home string, options []string, uidMaps, gidMaps []idtools.IDMap) (grap
...
+		if err := hasOpaqueCopyUpBug(home); err != nil {
+			logrus.Warnf("Not using native diff for overlay2: %v", err)
```
Comment (AkihiroSuda) [inline daemon/graphdriver/overlay2/overlay.go]: How about printing something like "Please consider updating the kernel to 4.8.0 or later" here

File: daemon/graphdriver/overlay2/overlay.go (hunk 1 above)
Comment (dmcgowan) [inline daemon/graphdriver/overlay2/overlay.go]: Why should we skip the kernel check though? The fix was merged before 4.8 was released so we can be confident that 4.8 or later have the fixed. Kernel tests were also added around this issue to prevent regression in later versions. Ideally users on newer Kernels won't have to incur the additional startup time required for this check.

Comment (tonistiigi) [inline daemon/graphdriver/overlay2/overlay.go]: We can keep that check if you like it, although kernel versions are abused all the time and it is hard to predict who will decide to release something with a wrong version. With lazy loading, the additional time for full check should be very small.

**Comment by dmcgowan** [comment]
@AkihiroSuda added build tag, updated the error to mention updating to fix, and also added to the status output (if this merges first you will need to rebase your other PR).

**Comment by tonistiigi** [comment]
@dmcgowan Need to mark that test for linux as well.

**Comment by tonistiigi** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Comment by tristanz** [comment]
Am I correct to read that this patch means that for kernels without backports yet (RHEL 7), overlay2 will now have same issues with inode exhaustion as overlay in 1.13?

If so, the documentation (https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/) should be updated to reflect that the overlay2 benefits do not apply to kernels older than 4.8 without backports, even though it will work.

**Comment by tonistiigi** [comment]
@tristanz No, this only changes the diff algorithm, making `docker commit` bit slower. The optimizations from on disk layout still apply.

**Comment by dmcgowan** [comment]
@tristanz the backport does not impact storage for `overlay2`. The only potential impact is running into #21555.

**Comment by tristanz** [comment]
@tonistiigi @dmcgowan thanks!   Reading #21555 it looks like this is no longer critical bug after #27209 mitigation.  With this PR and #27209 are any known major issues with overlay2 on RHEL 7.2+ beyond SELinux not working yet?
