### PR TITLE
Retry AttachNetwork when it fails to find network

### LINKED ISSUE #26588: DockerSwarmSuite.TestSwarmContainerAutoStart is flaky
Noticed in https://github.com/docker/docker/pull/26584 on experimental CI.

```
01:14:43 ----------------------------------------------------------------------
01:14:43 FAIL: docker_cli_swarm_test.go:246: DockerSwarmSuite.TestSwarmContainerAutoStart
01:14:43 
01:14:43 [d20f68f1ba9c8] waiting for daemon to start
01:14:43 [d20f68f1ba9c8] daemon started
01:14:43 [d20f68f1ba9c8] exiting daemon
01:14:43 [d20f68f1ba9c8] waiting for daemon to start
01:14:43 [d20f68f1ba9c8] daemon started
01:14:43 docker_cli_swarm_test.go:265:
01:14:43     c.Assert(strings.TrimSpace(out), checker.Not(checker.Equals), "")
01:14:43 ... obtained string = ""
01:14:43 ... expected string = ""
01:14:43 
01:14:43 [d20f68f1ba9c8] exiting daemon
01:14:45 
01:14:45 ----------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by mrjana**
When trying to attach to swarm scope network for an unmanaged container
sometimes even if attaching to network succeeds, we may not find the
network because some other container which was using the network went
down and removed the network. So if it is not found, try to detach and
reattach to re-download the network from the manager.

Fixes #26588

Signed-off-by: Jana Radhakrishnan mrjana@docker.com

### CODE REVIEW

File: daemon/container_operations.go [hunk 1]
```diff
@@ -351,26 +351,41 @@ func (daemon *Daemon) findAndAttachNetwork(container *container.Container, idOrN
...
 
-	// In all other cases, attempt to attach to the network to
-	// trigger attachment in the swarm cluster manager.
 	var config *networktypes.NetworkingConfig
-	if daemon.clusterProvider != nil {
-		var err error
-		config, err = daemon.clusterProvider.AttachNetwork(idOrName, container.ID, addresses)
-		if err != nil {
-			return nil, nil, err
+	for {
```
Comment (xiaods) [inline daemon/container_operations.go]: why for?

Comment (xiaods) [inline daemon/container_operations.go]: OK

**Comment by mrjana** [comment]
ping @mavenugo

**Comment by mavenugo** [comment]
LGTM

**Review by mavenugo — APPROVED** [review]

File: daemon/container_operations.go (hunk 1 above)
Comment (thaJeztah) [inline daemon/container_operations.go]: @mrjana discussing this; should we have a limit on this loop? And a delay?

**Review by thaJeztah — CHANGES_REQUESTED** [review]

File: daemon/container_operations.go (hunk 1 above)
Comment (mrjana) [inline daemon/container_operations.go]: @thaJeztah The retry should only happen when the last container on a network is going away or disconnecting while  at some short time window a new container is trying to connect to the same network. So even though in theory this might loop indefinitely in practice it should never retry more than once. Also we should probably not add a delay since the chance of getting into the another such time window probably increases with more delay so the best possible course to retry immediately rather than waiting.

**Comment by mrjana** [comment]
@thaJeztah Added a retry limit.

**Comment by dongluochen** [comment]
SGTM (not a maintainer)

**Comment by mrjana** [comment]
ping @thaJeztah

File: daemon/container_operations.go [hunk 2]
```diff
@@ -357,26 +357,51 @@ func (daemon *Daemon) findAndAttachNetwork(container *container.Container, idOrN
...
+			// Retry network attach again if we failed to
+			// find the network after successfull
+			// attachment because the only reason that
+			// would happen is if some other container
+			// attached to the swarm scope network went down
+			// and removed the network while we were in
+			// the process of attaching.
+			if config != nil {
+				if _, ok := err.(libnetwork.ErrNoSuchNetwork); ok {
+					if retryCount >= 5 {
```
Comment (thaJeztah) [inline daemon/container_operations.go]: Any reason for doing this, instead of `for i := 0; i < 5; i++ {` (or `for retries := 0; retries < 5; retries++ {`)?

Comment (thaJeztah) [inline daemon/container_operations.go]: (On the outer `for` loop)

Comment (xiaods) [inline daemon/container_operations.go]: same question

Comment (vieux) [inline daemon/container_operations.go]: ping @mrjana

Comment (mrjana) [inline daemon/container_operations.go]: Because I need to return a specific error if this failed because of exceeding number of retries.

Comment (thaJeztah) [inline daemon/container_operations.go]: Ah, hm, I'd have expected the error to be after the for loop (i.e., if no network was found after 5 attempts, generate, and return an error).

It's just a nit, so let's keep it

**Review by thaJeztah — APPROVED** [review]
LGTM
