### PR TITLE
[Carry 22033] Add a check for size field in custom format string

### LINKED ISSUE #21991: docker ps --format Output
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Output of `docker version`:**

```
Client:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-25.el7.x86_64
 Go version:      go1.4.2
 Git commit:      78ee77d/1.9.1
 Built:
 OS/Arch:         linux/amd64

Server:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-25.el7.x86_64
 Go version:      go1.4.2
 Git commit:      78ee77d/1.9.1
 Built:
 OS/Arch:         linux/amd64
```

**Output of `docker info`:**

```
Containers: 3
Images: 2
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: system-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 733.5 MB
 Data Space Total: 4.295 GB
 Data Space Available: 3.561 GB
 Metadata Space Used: 155.6 kB
 Metadata Space Total: 33.55 MB
 Metadata Space Available: 33.4 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.11.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.1 (Maipo)
CPUs: 2
Total Memory: 7.637 GiB
Name: vimapssp-cfgo01.it.bwns.ch
ID: MWIC:WO3X:66ZX:RO2I:PLV7:GL5W:52RC:ZFHO:5ZJX:M2BI:VWGC:6KDD
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Virtual (ESX)

**Steps to reproduce the issue:**
1. run `docker ps -a -s`
2. run `docker ps -a --format "table {{.ID}}\t{{.Names}}\t{{.Size}}"`
3. Compare the size

**Describe the results you received:**
The size of the container is not identical.
```
# docker ps -a -s
c943c4c65617        debian              "bash"              About an hour ago   Exited (0) About an hour ago                       loving_hugle        209.7 MB (virtual 334.8 MB)

# docker ps -a --format "table {{.ID}}\t{{.Names}}\t{{.Size}}"
CONTAINER ID        NAMES               SIZE
c943c4c65617        loving_hugle        0 B
```

**Describe the results you expected:**
I would expect the same size of the container.
```
# docker ps -a --format "table {{.ID}}\t{{.Names}}\t{{.Size}}"
CONTAINER ID        NAMES               SIZE
c943c4c65617        loving_hugle        209.7 MB
```

**Additional information you deem important (e.g. issue happens only occasionally):**

### PR DESCRIPTION
**Pull request by thaJeztah**
carry of https://github.com/docker/docker/pull/22033

closes https://github.com/docker/docker/pull/22033
fixes #21991

This fix addresses an issue where including the `{{.Size}}` format
field in conjunction with `docker ps --format`, without the `--size`
flag, would not correctly display the size of containers.

This is done by doing a check on the custom format string, and setting
the size flag on the options struct if the field is found. This struct
gets passed to the engine API which then generates the correct query.

An integration test is included which runs `docker ps --format "table
{{.Size}}"` without `--size`, and checks that the returned output is
not `0 B`.

Fixes #21991

As suggested by @cpuguy83, a parser is implemented to process the format
string as a template, and then traverses the template tree to determine
if `.Size` was called.

This was then reworked by making use of template execution with a
pre-processor struct that will set the `--size` option if the template
calls for the field.

The pre-processor now also sets a boolean in the context passed to the
writer. There is an integration test for this that calls `docker ps
--size --format "{{.Size}}"` and then checks that `size: {{.Size}}` is
not appended, as it would with previous behavior.

Finally, a change was made to the formatter to not automatically
add a `{{.Size}}` if a custom format is provided.

### CODE REVIEW

**Comment by thaJeztah** [comment]
I simplified some things, and fixed an issue that I think should be considered a bug. 

In the old (current) behavior; this `docker ps --size --format 'table {{.Name}}'` outputs:

```
IMAGE     SIZE
busybox   0 B (virtual 1.113 MB)
```

However, doing `docker ps --size --format '{{.Image}}'` (not "table"), this is the output:
```
busybox
```

I think this is a bug, because as a user, I should have control over my template
(`--format`) and Docker should not automatically add columns to that (so use the behavior of "non-table").


Because of this, the `sizeSetByFormat` property is no longer needed, and some logic could be simplified a bit.

**Comment by thaJeztah** [comment]
ping @calavera @cpuguy83 ptal

File: api/client/formatter/formatter.go [hunk 1]
```diff
@@ -114,35 +114,27 @@ type ImageContext struct {
...
-			ctx.Format = `container_id: {{.ID}}
-image: {{.Image}}
-command: {{.Command}}
-created_at: {{.CreatedAt}}
-status: {{.Status}}
-names: {{.Names}}
-labels: {{.Labels}}
-ports: {{.Ports}}
-`
+			ctx.Format = `container_id: {{.ID}}\nimage: {{.Image}}\ncommand: {{.Command}}\ncreated_at: {{.CreatedAt}}\nstatus: {{.Status}}\nnames: {{.Names}}\nlabels: {{.Labels}}\nports: {{.Ports}}\n`
```
Comment (vdemeester) [inline api/client/formatter/formatter.go]: @thaJeztah why using `\n` ?

**Comment by vdemeester** [comment]
Make sence. LGTM :+1:

File: api/client/formatter/formatter.go (hunk 1 above)
Comment (thaJeztah) [inline api/client/formatter/formatter.go]: Hm, yes, partly personal preference here (it doesn't visually "break" the `if/else` here, making it slightly easier to follow the flow). Also, to be consistent with the constants that are used (https://github.com/docker/docker/pull/23247/files#diff-6f00957a36268c4d5f8e6b15054b4a06R20), I was considering to move this format to a constant as well.

File: api/client/formatter/formatter.go [hunk 2]
```diff
@@ -114,35 +114,27 @@ type ImageContext struct {
...
 			if ctx.Size {
-				ctx.Format += `size: {{.Size}}
-`
```
Comment (thaJeztah) [inline api/client/formatter/formatter.go]: @vdemeester w.r.t. the `\n`; if found this particularly easy to miss (just a back-tick on an empty line); using `\n` is less likely to be missed (again, may be personal :smile:)

Comment (vdemeester) [inline api/client/formatter/formatter.go]: yep, you're right 😂

**Comment by cpuguy83** [comment]
LGTM
