### PR TITLE
Fix removing containers on leaving from pending state

### LINKED ISSUE #23629: docker swarm leave should not kill my running containers
Or at least it should warm me.

**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   1f136c1
 Built:        Wed Jun 15 05:11:00 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   1f136c1
 Built:        Wed Jun 15 05:11:00 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 70
Server Version: 1.12.0-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 111
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: default
Default Runtime: default
Kernel Version: 4.2.0-36-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.56 GiB
Name: emu
ID: LKRP:5O4R:KBMJ:MAMD:BDVP:RUTH:SDKP:UNOZ:G44Q:3H3E:HMZ3:5LTH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Steps to reproduce the issue:**
1. run some containers
2. `docker swarm join <random-address`. As the address is unknown, this fails. This let the swarm in an inconsistent state (see #23611)
3. `docker swarm leave` to fix the inconsistent state

**Describe the results you received:**

all your initial containers are killed

**Describe the results you expected:**

either don't kill my containers or at least tell me that you will do it. So I can abort the operation.

### PR DESCRIPTION
**Pull request by tonistiigi**
fixes #23629

Signed-off-by: Tonis Tiigi tonistiigi@gmail.com

### CODE REVIEW

**Comment by vieux** [comment]
LGTM

**Comment by icecrime** [comment]
LGTM :+1:

**Comment by thaJeztah** [comment]
experimental timed out after all tests were completed

```
23:51:22 PASS: docker_api_swarm_test.go:554: DockerSwarmSuite.TestApiSwarmLeaveOnPendingJoin	3.596s
```

File: integration-cli/docker_api_swarm_test.go [hunk 1]
```diff
@@ -550,6 +550,32 @@ func (s *DockerSwarmSuite) TestApiSwarmLeaveRemovesContainer(c *check.C) {
...
+	s.AddDaemon(c, true, true)
+	d2 := s.AddDaemon(c, false, false)
+
+	id, err := d2.Cmd("run", "-d", "busybox", "top")
+	c.Assert(err, checker.IsNil)
+	id = strings.TrimSpace(id)
+
+	go d2.Join("nosuchhost:1234", "", "", false) // will block on pending state
+
+	time.Sleep(1 * time.Second)
```
Comment (cpuguy83) [inline integration-cli/docker_api_swarm_test.go]: Can we do a:

```go
started := make(chan struct{})
go func() {
    close(started)
    d2.Join(...)
}()

<-started
```

Comment (tonistiigi) [inline integration-cli/docker_api_swarm_test.go]: I don't think this would work. We could loop with `100ms` intervals and check when the swarm state changes from `inactive` to `pending`.
