### PR TITLE
c8d/images: handle images without manifests for default platform

### LINKED ISSUE #44578: containerd-integration: cannot interact with images that don't have the default platform
### Description

Commands, such as `docker image inspect` and `docker image rm` default to use the default platform. If the default platform is not present for an image, the command fails.

### Reproduce

Make sure no image is present:

```bash
docker image rm busybox:latest
```

Pull the image for a platform that's not the default:

```bash
docker image pull --platform=linux/s390x busybox:latest
59f225fdf34f: Download complete
8e8f614949c5: Download complete
8460717a482e: Download complete
53b6cfce1626: Download complete
docker.io/library/busybox:latest
```

Verify that the image is present:

```bash
docker image ls
REPOSITORY       TAG          IMAGE ID       CREATED              SIZE
busybox          latest       59f225fdf34f   About a minute ago   2.01MB
```

Try to remove or inspect the image:

```bash
docker image rm busybox:latest
Error: No such image: busybox:latest

docker image rm 59f225fdf34f
Error: No such image: busybox:latest

docker image inspect busybox:latest
[]
Error: No such image: busybox:latest
```

### Workaround: to remove or inspect the image, pull the default platform:

```bash
docker image pull busybox:latest
59f225fdf34f: Exists
e68659cdc5b2: Download complete
73a648b1404c: Download complete
3e32979327a9: Download complete
docker.io/library/busybox:latest
```

```bash
docker image rm busybox:latest
Untagged: docker.io/library/busybox:latest
```

### Expected behavior

Interacting with the image to work

A "quick fix" would be to pick the first available architecture if the default is not available, but we need to look at a better UX (I'm writing up some ideas for that).

### docker version

```bash
Client:
 Cloud integration: v1.0.29
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:01:18 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.15.0 (93002)
 Engine:
  Version:          22.06.0-beta.0-902-g2708be0db4.m
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.18.4
  Git commit:       2708be0db4
  Built:            Wed Nov 23 09:32:50 2022
  OS/Arch:          linux/arm64
  Experimental:     true
 containerd:
  Version:          1.6.10
  GitCommit:        770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  base: Identify base image (Docker Inc., vn/a)
  buildx: Docker Buildx (Docker Inc., v0.9.1)
  compose: Docker Compose (Docker Inc., v2.13.0)
  dev: Docker Dev Environments (Docker Inc., v0.0.5)
  extension: Manages Docker extensions (Docker Inc., v0.2.16)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.22.0)
  shell: Open a browser shell on the Docker Host. (thaJeztah, v0.0.1)

Server:
 Containers: 48
  Running: 12
  Paused: 0
  Stopped: 36
 Images: 11
 Server Version: 22.06.0-beta.0-902-g2708be0db4.m
 Storage Driver: stargz
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: bfpr7gj1w767qwq37qta7kqts
  Is Manager: true
  ClusterID: crv7mpxcck85em4ocnfci4esi
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.65.3
  Manager Addresses:
   192.168.65.3:2377
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.49-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 5
 Total Memory: 5.8GiB
 Name: docker-desktop
 ID: c8ca0b32-cd5f-4ad2-9a97-bc30ebe413d4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

This is on Docker Desktop 4.15 with containerd integration enabled

### PR DESCRIPTION
**Pull request by laurazard**
**- What I did**
Fix https://github.com/moby/moby/issues/44578

**- How I did it**

For clarity: what was previously not working was the following block:

https://github.com/moby/moby/blob/b1569b9c185b9d5371d30fb59c14f4694239a4f3/daemon/containerd/image.go#L41-L50

passing 
```go
platform := platforms.AllPlatformsWithPreference(cplatforms.Default())
```
into
```go
containerdimages.Config(ctx, cs, desc, platform)
```
breaks because, after listing all the manifests in the index for the passed-in descriptor in:
https://github.com/moby/moby/blob/b1569b9c185b9d5371d30fb59c14f4694239a4f3/vendor/github.com/containerd/containerd/images/image.go#L215
they get sorted according to the `platform := platforms.AllPlatformsWithPreference(cplatforms.Default())` in:
https://github.com/moby/moby/blob/b1569b9c185b9d5371d30fb59c14f4694239a4f3/vendor/github.com/containerd/containerd/images/image.go#L221-L229
and then, in order of sorting, this block gets called:
https://github.com/moby/moby/blob/b1569b9c185b9d5371d30fb59c14f4694239a4f3/vendor/github.com/containerd/containerd/images/image.go#L150-L156

Which breaks since we don't have the manifests for the other platforms and the platform we do have isn't the first on the list.

**- How to verify it**
- `docker pull --platform=[non-default-platform] alpine`
- `docker inspect alpine`
- `docker history alpine`

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

image

### CODE REVIEW

File: daemon/containerd/image_history.go [hunk 1]
```diff
@@ -18,31 +17,41 @@ import (
...
-	// TODO: pass the platform from the cli
-	conf, err := containerdimages.Config(ctx, cs, desc, platforms.AllPlatformsWithPreference(cplatforms.Default()))
-	if err != nil {
-		return nil, err
-	}
+	// TODO: pass platform in from the CLI
+	platform := platforms.AllPlatformsWithPreference(cplatforms.Default())
 
-	diffIDs, err := containerdimages.RootFS(ctx, cs, conf)
+	var manifests []ocispec.Manifest
```
Comment (neersighted) [inline daemon/containerd/image_history.go:29]: This seems to be largely the same as in `image.go` -- is this generic enough to hoist into a helper?

File: daemon/containerd/image.go [hunk 2]
```diff
@@ -44,19 +44,33 @@ func (i *ImageService) GetImage(ctx context.Context, refOrID string, options ima
...
+	for _, mfst := range manifests {
+		imageConfigBytes, err := content.ReadBlob(ctx, cs, mfst.Config)
+		if err != nil {
+			return nil, err
+		}
+
+		if err := json.Unmarshal(imageConfigBytes, &ociimage); err != nil {
+			return nil, err
+		}
+		if platform.Match(ociimage.Platform) {
```
Comment (vvoland) [inline daemon/containerd/image.go:71]: This will always be true if no platform is provided:

`platform := platforms.AllPlatformsWithPreference(cplatforms.Default())`
will match all platform (`Match` will be true for any argument).
In this context, we should use its `Less` method to get an ordered slice of the platforms, and then pick the first one.

File: daemon/containerd/image.go [hunk 3]
```diff
@@ -44,19 +44,33 @@ func (i *ImageService) GetImage(ctx context.Context, refOrID string, options ima
...
 	cs := i.client.ContentStore()
-	conf, err := containerdimages.Config(ctx, cs, desc, platform)
-	if err != nil {
-		return nil, err
-	}
 
-	imageConfigBytes, err := content.ReadBlob(ctx, cs, conf)
+	var manifests []ocispec.Manifest
+	err = i.walkImageManifests(ctx, desc, func(img *ImageManifest) error {
+		mfst, err := img.Manifest(ctx)
```
Comment (vvoland) [inline daemon/containerd/image.go:50]: If we don't need the full `ocispec.Manifest`, we can just directly read the config with `img.Config(ctx)`.

File: daemon/containerd/image.go (hunk 2 above)
Comment (vvoland) [reply daemon/containerd/image.go:71]: It might be simpler to just move the Config picking inside the `walkImageManifests`:
```go
defaultPlatformMatcher = platforms.Default()
var ociimage ocispec.Image
err := i.walkImageManifests(ctx, desc, func(img *ImageManifest) error {
  cfg, err := img.Config(ctx)
  if err != nil {
     return err
  }
  ociimage = cfg
  if defaultPlatformMatcher.Match(cfg.Platform) {
     break
  }
})
```

**Review by vvoland — CHANGES_REQUESTED** [review]

File: daemon/containerd/image.go (hunk 2 above)
Comment (laurazard) [reply daemon/containerd/image.go]: > It might be simpler to just move the Config picking inside the `walkImageManifests`:

Can't do that afaict since that's not really a loop, but I removed the second loop and instead sort the slice of images and picked the first one as per your suggestion. Lmk if that sounds good or if you have a better idea of how to handle that.

File: daemon/containerd/image_history.go (hunk 1 above)
Comment (laurazard) [reply daemon/containerd/image_history.go]: I looked around and didn't see anywhere else where this would make sense (for now), so I'll leave it as-is for now and do a larger refactor/review in another PR.

File: daemon/containerd/image_history.go [hunk 4]
```diff
@@ -18,39 +19,54 @@ import (
...
-	if err := json.Unmarshal(blob, &image); err != nil {
-		return nil, err
+	if len(presentImages) == 0 {
+		return nil, errdefs.NotFound(errors.New("failed to find image manifest"))
 	}
 
+	sort.SliceStable(presentImages, func(i, j int) bool {
+		return platform.Less(presentImages[i].Platform, presentImages[j].Platform)
+	})
+	ociimage := presentImages[0]
```
Comment (tianon) [inline daemon/containerd/image_history.go:61]: Should this block go into a helper?  Does it exist in other places too? :sweat_smile:

Comment (tianon) [reply daemon/containerd/image_history.go:61]: Oh LOL, https://github.com/moby/moby/pull/45816#pullrequestreview-1498928513; my bad :facepalm:

File: daemon/containerd/image.go [hunk 5]
```diff
@@ -44,21 +45,39 @@ func (i *ImageService) GetImage(ctx context.Context, refOrID string, options ima
...
+		imageConfigBytes, err := content.ReadBlob(ctx, cs, conf)
+		if err != nil {
+			return err
+		}
+
+		var ociimage ocispec.Image
+		if err := json.Unmarshal(imageConfigBytes, &ociimage); err != nil {
+			return err
+		}
+
```
Comment (vvoland) [inline daemon/containerd/image.go:65]: nit: we have a helper for that

```suggestion
		var ociimage ocispec.Image
		if err := readConfig(ctx, cs, conf, &ociimage); err != nil {
			return err
		}
```

**Review by vvoland — APPROVED** [review]

**Review by neersighted — APPROVED** [review]
LGTM

**Comment by neersighted** [comment]
I think so; we're not 100% sure when 25 will drop, so I think it will be good to get this out in the 24 patch release we intend to do this week.

File: daemon/containerd/image.go [hunk 6]
```diff
@@ -44,21 +43,32 @@ func (i *ImageService) GetImage(ctx context.Context, refOrID string, options ima
...
+	})
 	if err != nil {
 		return nil, err
 	}
-
-	var ociimage ocispec.Image
-	if err := json.Unmarshal(imageConfigBytes, &ociimage); err != nil {
-		return nil, err
+	if len(presentImages) == 0 {
+		return nil, errdefs.NotFound(errors.New("failed to find image manifest"))
```
Comment (thaJeztah) [inline daemon/containerd/image.go:64]: Need to check if this is one of the magic errors that "MUST" be "No such image"

Comment (thaJeztah) [reply daemon/containerd/image.go:64]: ^^ discussed, and we can take the risk
