### PR TITLE
inherit the daemon log options when creating containers

### LINKED ISSUE #21118: docker run logging options do not merge with default docker daemon logging options.
**Output of `docker version`:**

```
‣ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd6
```

**Output of `docker info`:**

```
137‣ docker info
Containers: 21
 Running: 0
 Paused: 0
 Stopped: 21
Images: 1
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 46
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: fluentd
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-44-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859 GiB
Name: dockermachine
ID: CXNO:G3D4:IWTC:W6G3:G7ES:EOFO:5OEU:POFE:LJ6L:K4ZU:PFB7:IUSV
WARNING: No swap limit support
Labels:
 provider=amazonec2
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Host OS Info

```
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
```

**Steps to reproduce the issue:**

1. Start docker daemon with following options

```
root@dockermachine:~# cat /etc/default/docker

DOCKER_OPTS='
-H tcp://0.0.0.0:2376
-H unix:///var/run/docker.sock
--storage-driver aufs
--tlsverify
--tlscacert /etc/docker/ca.pem
--tlscert /etc/docker/server.pem
--tlskey /etc/docker/server-key.pem
--label provider=amazonec2
--log-driver=fluentd
--log-opt fluentd-address=elb:80
--log-opt tag=docker.{{.Name}}'
root@dockermachine:~#
```

2. Trying to launch a container with following command

```
‣ docker run --log-opt tag=mailer ubuntu bash -c "i=1;while [ true ]; do echo log this  $RANDOM;sleep 1;done"
docker: Error response from daemon: unknown log opt 'tag' for json-file log driver.
```

3.  As in the docker daemon command I've provided the fluentd driver info and in the second step I am running a container with one more opt supported by fluentd  "--log-opt tag=mailer"

**Describe the results you received:**

The container is not started, docker run exits with the following error.

```
docker: Error response from daemon: unknown log opt 'tag' for json-file log driver.
```

**Describe the results you expected:**

Providing the log driver information in the daemon and providing one more opt related to the same driver, they should be appended.  Passing `--log-driver=fluentd` to `docker run`
requires passing all the related options again instead of picking and merging the defaults from daemon
configuration.

**Additional information you deem important (e.g. issue happens only occasionally):**

We are trying to override logging tags per container run, for example pass additional tags
like version of the application.

### PR DESCRIPTION
**Pull request by mountkin**
**\- What I did**
1. Inherit all the daemon log options when creating containers if using the default log driver of daemon. (Fixed #21118)
2. Expose the merged log config to `docker inspect` result.
3. Remove some redundant log driver related validations. 

**\- How I did it**

**\- How to verify it**
Start daemon with some log options, then create a container and inspect it to see if the daemon log options are shown in the result of the inspect output.

**\- A picture of a cute animal (not mandatory but encouraged)**

Signed-off-by: Shijiang Wei mountkin@gmail.com

### CODE REVIEW

File: daemon/logger/factory.go [hunk 1]
```diff
@@ -46,7 +53,7 @@ func (lf *logdriverFactory) get(name string) (Creator, error) {
 
 	c, ok := lf.registry[name]
 	if !ok {
-		return c, fmt.Errorf("logger: no log driver named '%s' is registered", name)
+		return c, fmt.Errorf("unsupported log driver '%s'", name)
```
Comment (mountkin) [inline daemon/logger/factory.go]: I think the error message `logger: no log driver named '%s' is registered` is a bit misleading, the user might ask "how do I register log drivers?"
But this change caused the `docker-py` test failing at https://github.com/docker/docker-py/blob/master/tests/integration/container_test.py#L288

File: daemon/logger/factory.go [hunk 2]
```diff
@@ -19,16 +19,23 @@ type logdriverFactory struct {
...
+
+	lf.m.Lock()
 	lf.registry[name] = c
+	lf.m.Unlock()
 	return nil
 }
 
+func (lf *logdriverFactory) driverRegistered(name string) bool {
+	lf.m.Lock()
+	defer lf.m.Unlock()
```
Comment (cyphar) [inline daemon/logger/factory.go]: There's no reason to use `defer` here (it actually can make the function ~20% slower).

File: daemon/logger/factory.go (hunk 1 above)
Comment (thaJeztah) [inline daemon/logger/factory.go]: perhaps "log driver .. not found"? Because it may be *supported*, just not installed. Just thinking out loud here

Comment (mountkin) [inline daemon/logger/factory.go]: @thaJeztah in theory it's indeed `unsupported` because the log drivers is _installed_ at build time, not runtime.
To make jenkins happy I'll restore the error message in this PR.

File: daemon/logger/factory.go (hunk 2 above)
Comment (mountkin) [inline daemon/logger/factory.go]: Updated. Thanks @cyphar :smile:

File: daemon/logger/factory.go (hunk 1 above)
Comment (thaJeztah) [inline daemon/logger/factory.go]: Doh! Yes, had my head around other plugins, we don't have logging plugins (*yet*)

**Comment by thaJeztah** [comment]
Related failure? https://jenkins.dockerproject.org/job/Docker-PRs-experimental/16230/console

```
03:07:01 
03:07:01 =================================== FAILURES ===================================
03:07:01 _________ CreateContainerTest.test_invalid_log_driver_raises_exception _________
03:07:01 /docker-py/tests/integration/container_test.py:286: in test_invalid_log_driver_raises_exception
03:07:01     host_config=self.client.create_host_config(log_config=log_config)
03:07:01 /docker-py/docker/api/container.py:118: in create_container
03:07:01     return self.create_container_from_config(config, name)
03:07:01 /docker-py/docker/api/container.py:129: in create_container_from_config
03:07:01     return self._result(res, True)
03:07:01 /docker-py/docker/client.py:146: in _result
03:07:01     self._raise_for_status(response)
03:07:01 /docker-py/docker/client.py:142: in _raise_for_status
03:07:01     raise errors.APIError(e, response, explanation=explanation)
03:07:01 E   APIError: 500 Server Error: Internal Server Error ("logger: no log driver named 'asdf-nope' is registered")
03:07:01 =========================== short test summary info ============================
```

**Comment by mountkin** [comment]
@thaJeztah it's failing because before this change, when you create a container with invalid log driver, the 'create' will succeed but it'll fail if you try to start it. This PR moved the validation logic to the create phase.

**Comment by thaJeztah** [comment]
@mountkin should those test be updated in docker-py?

**Comment by mountkin** [comment]
The docker-py test should be updated if this pr get merged. I think it makes no sense to let the user create a container that can never be started.😇

**Comment by thaJeztah** [comment]
@mountkin I agree, point is that if we merge this PR, all PR's will go red, so we should have a fix in docker-py before this is merged. Can you make that change, or do you need someone to take care of that?

**Comment by mountkin** [comment]
@thaJeztah it would be greatly appreciated if someone help to make the docker-py change. It's late at night here 😀

**Comment by thaJeztah** [comment]
ping @shin- would you be able to assist?

**Comment by shin-** [comment]
https://github.com/docker/docker-py/pull/990

**Comment by shin-** [comment]
Merged, please update the docker-py commit to `fa7068cb7cf2ae1efcc2b3b99f24f4c7aa29e989`

**Comment by thaJeztah** [comment]
Thank you @shin-! Really appreciated

**Comment by mountkin** [comment]
Thanks a lot @shin- .
But the docker-py master is still breaking the integration test. The reason is stated here https://github.com/docker/docker-py/pull/924#issuecomment-196676157

**Comment by mountkin** [comment]
@thaJeztah test passed after vending in docker-py 7befe694bd21e3c54bb1d7825270ea4bd6864c13.
Perhaps this PR needs design review? Can you help to add the corresponding labels?

**Comment by thaJeztah** [comment]
@mountkin so sorry, but it needs a rebase now :cry:

**Comment by mountkin** [comment]
@thaJeztah rebased :smile:

**Comment by calavera** [comment]
LGTM

**Comment by thaJeztah** [comment]
ping @duglin could you have a look?

**Comment by cpuguy83** [comment]
Can you do a rebase to make sure we don't have any conflicts (outside of merge conflicts)?

**Comment by cpuguy83** [comment]
In general I don't like modifying hostconfig since it makes figuring out what config was actually passed in difficult... but we do it other places.

Otherwise code LGTM.

**Comment by cpuguy83** [comment]
LGTM, thanks!
