### PR TITLE
daemon/&container/: enable `--security-opt writable-cgroups=true|false` as an option

### LINKED ISSUE #42040: make /sys/fs/cgroup rw by default with cgroup2
**Description**

Make /sys/fs/cgroup rw by default within the container if cgroup2 is used. Currently running e.g. systemd within the container fails because it cannot create it's cgroups as /sys/fs/cgroup is mounted ro. Also now with cgroup2 being supported the old container escapes of v1 are no longer an issue.

For anyone wanting a q'n'd fix for this problem I've attached: https://github.com/moby/moby/pull/42043

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**
Applications within the container being able to create child cgroups and "manage" there own assigned scope.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 20.10.3, build 48d30b5b32
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-tp-docker)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 57
 Server Version: 20.10.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b.m
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.16-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 27.11GiB
 Name: ArchBook
 ID: ARJ3:2WKK:VWM6:MEG5:SVQF:NKWZ:SVQQ:2KNQ:P7WI:MG3W:SGX6:3TX6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: agowa338
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### LINKED ISSUE #42275: Unable to run systemd in docker with ro /sys/fs/cgroup after systemd 248 host upgrade
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

I used to run docker containers with systemd as CMD without having to expose /sys/fs/cgroup as rw; this worked until systemd 248 on the host. Now it fails with 

```
Failed to create /init.scope control group: Read-only file system
Failed to allocate manager object: Read-only file system
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...
```
I opened a related issue on the systemd github repo: https://github.com/systemd/systemd/issues/19245

**Workarounds**

* boot host with systemd.unified_cgroup_hierarchy=0
* remove ro flag from docker run arg -v /sys/fs/cgroup:/sys/fs/cgroup:ro but this contaminates the host cgroup, causing e.g. docker top to get confused:

```
docker top debian-systemd
Error response from daemon: runc did not terminate successfully: container_linux.go:186: getting all container pids from cgroups caused: lstat /sys/fs/cgroup/system.slice/docker-817dfec3facbeb10c64d7b0fae478804b1177ae949e695e111b7c693569dd21a.scope: no such file or directory
: unknown
```

**Steps to reproduce the issue:**

Dockerfile:

```
FROM debian:buster-slim

ENV container docker
ENV LC_ALL C
ENV DEBIAN_FRONTEND noninteractive

USER root
WORKDIR /root

RUN set -x

RUN apt-get update -y \
    && apt-get install --no-install-recommends -y systemd \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && rm -f /var/run/nologin

RUN rm -f /lib/systemd/system/multi-user.target.wants/* \
    /etc/systemd/system/*.wants/* \
    /lib/systemd/system/local-fs.target.wants/* \
    /lib/systemd/system/sockets.target.wants/*udev* \
    /lib/systemd/system/sockets.target.wants/*initctl* \
    /lib/systemd/system/sysinit.target.wants/systemd-tmpfiles-setup* \
    /lib/systemd/system/systemd-update-utmp*

VOLUME [ "/sys/fs/cgroup" ]

CMD ["/lib/systemd/systemd"]
```

**Expected behaviour**

```$ /lib/systemd/systemd --version
systemd 247 (247.4-2-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
$ docker build -t debian-systemd .
$ docker run -t --tmpfs /run --tmpfs /run/lock --tmpfs /tmp -v /sys/fs/cgroup:/sys/fs/cgroup:ro debian-systemd
systemd 241 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid)
Detected virtualization docker.
Detected architecture x86-64.

Welcome to Debian GNU/Linux 10 (buster)!

Set hostname to <bf431002c7c1>.
Couldn't move remaining userspace processes, ignoring: Input/output error
File /lib/systemd/system/systemd-journald.service:12 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.
Proceeding WITHOUT firewalling in effect! (This warning is only shown for the first loaded unit using IP firewalling.)
[  OK  ] Listening on Journal Socket.
...
[  OK  ] Reached target Graphical Interface.
```

**Actual behaviour**

Since systemd v248

```
$ /lib/systemd/systemd --version
systemd 248 (248-3-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified

$ docker build -t debian-systemd .
$ docker run -t --tmpfs /run --tmpfs /run/lock --tmpfs /tmp -v /sys/fs/cgroup:/sys/fs/cgroup:ro debian-systemd
systemd 241 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid)
Detected virtualization docker.
Detected architecture x86-64.

Welcome to Debian GNU/Linux 10 (buster)!

Set hostname to <fbb4fc19cb95>.
Failed to create /init.scope control group: Read-only file system
Failed to allocate manager object: Read-only file system
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...
```

**Output of `docker version`:**

```
$ docker version
Client:
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.16
 Git commit:        55c4c88966
 Built:             Wed Mar  3 16:51:54 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16
  Git commit:       363e9a88a1
  Built:            Wed Mar  3 16:51:28 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e.m
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-tp-docker)

Server:
 Containers: 10
  Running: 1
  Paused: 0
  Stopped: 9
 Images: 61
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e.m
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.11.11-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.712GiB
 Name: homepc
 ID: 67YO:62DZ:3NIF:TZT3:HTXP:BU6I:YBR3:XETA:7YCB:YGNN:MV6Q:QYN4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://mirror.gcr.io/
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

x86_64 Intel hw, Arch Linux 5.11.11-arch1-1

### PR DESCRIPTION
**Pull request by vbatts**
Fixes #42040
Fixes #42275
Closes #42043

Rather than making cgroups read-write by default, instead have a flag for making it possible.

Since these security options are passed through the cli to daemon API, no changes are needed to docker-cli.

Since this is currently only a single toggle, I also considered making it a `bool` like `cgroups-rw=true`. I could go either way. It being a string makes the intuitive value kindof hidden to users even moreso than the args to --security-opt already are.

**- What I did**

Summoned the strong desire to run systemd inside a container. Particularly a docker container, not podman.
Sought out what is blocking it.
Talked to fine humans like @tianon.

**- How I did it**

wrote the code.

**- How to verify it**

- build and run this branch of `dockerd`. Nothing special.
- run:
```shell
vbatts@jungle:~$ docker run -it --rm --security-opt cgroups=rw debian:testing findmnt | grep cgroup.*rw
| `-/sys/fs/cgroup   cgroup                          cgroup2 rw,nosuid,nodev,noe
```

Further, with a base container like:

```Dockerfile
FROM debian:testing
RUN apt update && \
    apt install -y --no-install-recommends systemd && \
    rm -rf /var/lib/apt/lists/*
ENTRYPOINT ["/usr/lib/systemd/systemd"]
```

image

**- Description for the changelog**

```markdown changelog
 `POST /containers/create` now accepts a `writable-cgroups=true` option in `HostConfig.SecurityOpt`
  to mount the container's cgroups writable. This provides a more granular
  approach than `HostConfig.Privileged`.
```

**- A picture of a cute animal (not mandatory but encouraged)**

image

### CODE REVIEW

**Comment by vbatts** [comment]
Tested the above with:
```shell
vbatts@jungle:~/src/moby$ docker version
Client:
 Version:           26.1.5+dfsg1
 API version:       1.45
 Go version:        go1.23.2
 Git commit:        a72d7cd
 Built:             Sun Oct 20 11:38:38 2024
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          library-import
  API version:      1.48 (minimum version 1.24)
  Go version:       go1.22.5
  Git commit:       library-import
  Built:            library-import
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v2.0.0
  GitCommit:        207ad711eabd375a01713109a8a197d197ff6542
 runc:
  Version:          1.2.0+dev
  GitCommit:        v1.2.0-44-gd9eecde9
 docker-init:
  Version:          0.19.0
  GitCommit:        
```

and 

```shell
vbatts@jungle:~$ docker version
Client:
 Version:           26.1.5+dfsg1
 API version:       1.45
 Go version:        go1.23.2
 Git commit:        a72d7cd
 Built:             Sun Oct 20 11:38:38 2024
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          library-import
  API version:      1.48 (minimum version 1.24)
  Go version:       go1.22.5
  Git commit:       library-import
  Built:            library-import
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.22~ds1
  GitCommit:        1.7.22~ds1-1+b1
 runc:
  Version:          1.1.12+ds1
  GitCommit:        1.1.12+ds1-5.1+b1
 docker-init:
  Version:          0.19.0
  GitCommit:        
```

File: daemon/daemon_unix.go [hunk 1]
```diff
@@ -249,6 +249,11 @@ func parseSecurityOpt(securityOptions *container.SecurityOptions, config *contai
 				return fmt.Errorf("invalid --security-opt 2: %q", opt)
 			}
 			securityOptions.NoNewPrivileges = noNewPrivileges
+		case "cgroups":
```
Comment (thaJeztah) [inline daemon/daemon_unix.go:252]: As this introduces a new option accepted by the API, can you add a bullet to the API version-history for v1.48? https://github.com/moby/moby/blob/20062ef3580a15e53c48e8e0e5aa2c43eb4982f1/docs/api/version-history.md#v148-api-changes

Something like (better suggestions welcome!)

```markdown
* `POST /containers/create` now accepts a `cgroups=rw` option in `HostConfig.SecurityOpt`
  to mount the container's cgroups writable. This provides a more granular
  approach than `HostConfig.Privileged`.
```

We should also include these options in our swagger / OpenAPI, but looks like we currently don't, so that's something we can do in a follow-up (I can create a tracking ticket for that).

**Review by thaJeztah — COMMENTED** [review]
Good seeing you, @vbatts!

OHMAN this one brought me down the rabit-hole a bit while looking at some parts of the code (bear with me!)

Some thoughts on the "API" impact on this, and some pretty random thoughts on a possible alternative implementation (but pretty much open to suggestions to all of this)

### Creating containers;

- We've started to be more strict on new features introduced in newer API version, to prevent things working on the _same_ API version, but older/newer version of the daemon
- Unfortunately, currently we don't have a good approach for these options (i.e., the code parsing these isn't aware of the API version); we could add something to the router and either explicitly _ignore_ or error if it's passed on older API versions, similar to https://github.com/moby/moby/blob/20062ef3580a15e53c48e8e0e5aa2c43eb4982f1/api/server/router/container/container_routes.go#L638-L644
- :point_up: we can probably do so in a follow up (not a hard blocker)

### Inspecting containers;

Running `docker inspect` uses `InspectResponse ` for the response; https://github.com/moby/moby/blob/20062ef3580a15e53c48e8e0e5aa2c43eb4982f1/api/types/container/container.go#L169

This PR currently doesn't include the new option (but will include the option in `HostConfig.SecurityOpt`); do we think it'd be good to also show that it's set as part of the `inspect` response?

### Alternative implementation 🎲 🎲 

This is a bit of a wild-card; while looking at this PR, I was considering; "don't we already have an option for this????" and... well, we do; https://github.com/moby/moby/blob/20062ef3580a15e53c48e8e0e5aa2c43eb4982f1/daemon/create_unix.go#L40-L43


But for some reason we don't use that options for either `/sys/fs/cgroup` (or `/sys`); for those we set the `ro` option as part of the mount itself https://github.com/moby/moby/blob/20062ef3580a15e53c48e8e0e5aa2c43eb4982f1/oci/defaults.go#L79-L90


Which got me thinking;

- Should we consider removing the `ro` option there,
- Instead add those to the [default set of `ReadOnlyPaths`](https://github.com/moby/moby/blob/20062ef3580a15e53c48e8e0e5aa2c43eb4982f1/oci/defaults.go#L118-L124)
- For `Privileged` we already clear `ReadOnlyPaths` (so the "special" handling of `cgroups` would no longer be needed)
- For this new option, we can remove `/sys/fs/cgroup` from the list of `ReadOnlyPaths`
- :point_up: in which case, I'm even wondering; do we need to store that `SecurityOpts` on disk for this? (not sure about that one!) 

Ironically, I also stumbled on an `WithWriteableCgroupfs` option provided by containerd that we currently don't use (that's more something we could consider for a follow-up though)
https://github.com/moby/moby/blob/20062ef3580a15e53c48e8e0e5aa2c43eb4982f1/vendor/github.com/containerd/containerd/oci/spec_opts.go#L1144-L1156

**Comment by vbatts** [comment]
- re API gating, I can look into adding that check.
- re "inspect" output, like you said it **_is_** there in the `HostConfig`
[inspect.json](https://github.com/user-attachments/files/17649024/inspect.json)
- re alternatives:
  - There was palpable resistance to making cgroups rw by default in #42043. This would need further agreement and review of "how bad could it be??". 
  - as for making this more like a "default" behaviour, running systemd as pid 1 in the container is honestly what I _feel_ when I see the `--init` flag, despite _knowing_ that it's just for the subreaper pid cleanup nonsense. But this is not a hill I am caring to consider, much less die on.
  - regarding the other Privileged related ponderings, I have no idea. Seems like a different investigation. It would be not good to require users to use `--privileged` just to run systemd in the container though. 
- I'm flexible on the field name. 
- Will add the json tag stuffs
-

**Comment by thaJeztah** [comment]
> There was palpable resistance to making cgroups rw by default

Yeah, the approach would still be to make it read-only by default, but instead of as part of the [default mounts that are defined](https://github.com/moby/moby/blob/20062ef3580a15e53c48e8e0e5aa2c43eb4982f1/oci/defaults.go#L60), the mount itself wouldn't have `ro`, but instead `/sys/fs/cgroup` (and `/sys`) would be added to the [`ReadOnlyPaths`](https://github.com/moby/moby/blob/20062ef3580a15e53c48e8e0e5aa2c43eb4982f1/oci/defaults.go#L118-L124) list.

I _THINK_ (but didn't try) that would have the same net-result, but using a different mechanism. But it was really thinking out loud here (also wondering _"why didn't we do that in the first place?"_).

My train of thought there was that both would end up in `HostConfig` on disk, but adding (or removing for the `rw` case) `/sys/fs/cgroup` to the `ReadonlyPaths` would mean that there's no schema changes needed in `HostConfig`.

**Comment by thaJeztah** [comment]
> I _THINK_ (but didn't try) that would have the same net-result

Ignore me for now; I tried doing so, but looks like it doesn't work (but would have to dig "why")

**Comment by thaJeztah** [comment]
> but that is not right as an older cli now fails to talk to this newer dockerd, even though it works fine without this check. I'm missing the goal here. I'm going to punt that gating.

Yes, that's the intent; a docker < v28 (which is the release this would go in) CLI only supports up until API version X, for example, a docker 27.3.1 supports API v1.47;

```
docker version
Client:
 Version:           26.1.4
 API version:       1.45
```

When connecting with the daemon, it negotiates the highest API version that's supported by both the client and the daemon (which can either be limited by the daemon (e.g. a v23.0 daemon would support anything up to API v1.42) or the client). If the client is older than the daemon, the API version used is downgraded, and only features available in that API version can be used.

For testing, you can override the API version, e.g. `DOCKER_API_VERSION=1.48 docker ........`, which makes the cli pretend it supports an API version it doesn't support.

**Comment by vbatts** [comment]
still seems funny, but whatever.

image

**Comment by AkihiroSuda** [comment]
`podman` and `nerdctl` have `--systemd=(true|false|always)` flag.

Maybe  `docker` should follow the same convention?

File: daemon/oci_linux.go [hunk 2]
```diff
@@ -666,7 +666,7 @@ func withMounts(daemon *Daemon, daemonCfg *configStore, c *container.Container,
 
 		// TODO: until a kernel/mount solution exists for handling remount in a user namespace,
 		// we must clear the readonly flag for the cgroups mount (@mrunalp concurs)
-		if uidMap := daemon.idMapping.UIDMaps; uidMap != nil || c.HostConfig.Privileged {
+		if uidMap := daemon.idMapping.UIDMaps; uidMap != nil || c.HostConfig.Privileged || c.Cgroups == "rw" {
```
Comment (AkihiroSuda) [inline daemon/oci_linux.go:669]: "rw" should be prohibited on cgroup v1 hosts, as the container can be escaped via a write access to the device controller

**Review by AkihiroSuda — DISMISSED** [review]
"rw" should be prohibited on cgroup v1 hosts, as the container can be escaped via a write access to the device controller

**Comment by vbatts** [comment]
> `podman` and `nerdctl` have `--systemd=(true|false|always)` flag.
> 
> Maybe `docker` should follow the same convention?

That would be amazing consistency to have. First step would be even the ability to run systemd though.

File: daemon/oci_linux.go (hunk 2 above)
Comment (vbatts) [reply daemon/oci_linux.go:669]: good catch. Will need to cover that situation.

Comment (tianon) [reply daemon/oci_linux.go:669]: To put that another way, IMO the v1 concerns are more of a documentation problem than something we should block in the code.

**Comment by tianon** [comment]
I'm personally pretty strongly opposed to a `--systemd` flag, especially one that amounts to being just a helper for setting a couple of other flags that are otherwise unrelated to systemd except that it happens to be a bit of software that requires them (I believe one could accomplish that via the CDI integration and a CDI definition that specifies the required parameters in aggregate).

**Comment by tianon** [comment]
I also don't understand the reason for blocking this for older clients -- it's not breaking functionality, and the default still matches the prior default, so it seems harmless for an older client to be able to specify it? :thinking:

**Comment by cpuguy83** [comment]
This looks like a good addition.
Only comment is to make the opt a boolean like `no-new-privileges`, e.g. `writeable-cgroups=true|false`

**Comment by vbatts** [comment]
image

**Comment by vbatts** [comment]
#realtalk I think it is spelled "writable"  not "writeable"

**Comment by vbatts** [comment]
image

File: container/container.go [hunk 3]
```diff
@@ -122,6 +122,7 @@ type SecurityOptions struct {
 	AppArmorProfile string
 	SeccompProfile  string
 	NoNewPrivileges bool
+	WritableCgroups bool `json:"writable-cgroups,omitempty"`
```
Comment (AkihiroSuda) [inline container/container.go:125]: This json tag doesn't seem consistent with others

Comment (vbatts) [reply container/container.go:125]: how come?

Comment (AkihiroSuda) [reply container/container.go:125]: Other options in the struct do not have `json` tags

File: daemon/oci_linux.go (hunk 2 above)
Comment (AkihiroSuda) [reply daemon/oci_linux.go]: > this has security implications on the current v2 implementation also, so why block it for v1?

Because the issue is more critical on v1.

File: container/container.go (hunk 3 above)
Comment (vbatts) [reply container/container.go:125]: oh oh, you said json tag, and my brain read variable name.
yes. @thaJeztah said about having the json tag, but to smooth it out, would mean changes on lines that have nothing to do with this PR ... so I didn't touch them.

Comment (AkihiroSuda) [reply container/container.go:125]: So, `json:"writable-cgroups,omitempty"` should be removed too?

File: api/server/router/container/container_routes.go [hunk 4]
```diff
@@ -643,6 +643,20 @@ func (c *containerRouter) postContainersCreate(ctx context.Context, w http.Respo
 		}
 	}
 
+	if versions.LessThan(version, "1.48") {
```
Comment (cpuguy83) [inline api/server/router/container/container_routes.go:646]: Oh we also discussed not gating this on API.
@tianon @thaJeztah Did we come to a conclusion on this?

File: container/container.go (hunk 3 above)
Comment (vbatts) [reply container/container.go:125]: I'm ok with that. Since I've heard both for and against, I would welcome a tie-breaker from other maintainers.

File: daemon/oci_linux.go (hunk 2 above)
Comment (tianon) [reply daemon/oci_linux.go]: https://github.com/moby/moby/pull/42043#issuecomment-781990747

and sure, but `--privileged` does it, so this is more about having a way to get that bit of `--privileged` without the full hammer (https://github.com/moby/moby/issues/47663) than it is about babysitting a user who's explicitly asking for an insecure (or potentially insecure) configuration -- all the `--security-opt` settings are "user accepts the risk" type peeling back of the security boundary of the container, and it's already up to users to determine how that affects them, their use case, and their security model (and v1 is on the way out completely anyhow)

File: api/server/router/container/container_routes.go (hunk 4 above)
Comment (tianon) [reply api/server/router/container/container_routes.go:646]: I'm +1(00) on dropping the API version limitations (with thanks and apologies to vbatts for having implemented it successfully), but I think Seb still had some reservations unless I managed to be convincing enough. :bow: :heart:

**Comment by vbatts** [comment]
I've stashed the API gating in a branch here: https://github.com/moby/moby/compare/master...vbatts:moby:cgroups-rw-api-gate
dropped that gating comit, and dropped the json tag so that the field is consistent.

PTAL

File: container/container.go (hunk 3 above)
Comment (thaJeztah) [reply container/container.go]: Sorry, I'm lagging behind on my notifications; yeah, so my comment was related to some situations whree we didn't define the casing to use for fields, and some `ID` field renamed (`Id -> ID`). Golang itself is (sigh) case-insensitive for JSON fields, so all seemed fine, but we broke some non-Go tools, so we now had to explicitly set `Id` after-the-fact to preserve the `Id` casing. So my thinking here was that it's better to be explicit instead of depending on Go's behavior. 

The `omitempty` was from a perspective that it's a new field, and adding the `omitempty` could possibly prevent container configs being updated on-disk during the "restore" cycle on daemon startup.

**Comment by vbatts** [comment]
On 12/11/24 05:30 -0800, Sebastiaan van Stijn wrote:
>@thaJeztah commented on this pull request.

>Sorry, I'm lagging behind on my notifications; yeah, so my comment was related to some situations whree we didn't define the casing to use for fields, and some `ID` field renamed (`Id -> ID`). Golang itself is (sigh) case-insensitive for JSON fields, so all seemed fine, but we broke some non-Go tools, so we now had to explicitly set `Id` after-the-fact to preserve the `Id` casing. So my thinking here was that it's better to be explicit instead of depending on Go's behavior.
>
>The `omitempty` was from a perspective that it's a new field, and adding the `omitempty` could possibly prevent container configs being updated on-disk during the "restore" cycle on daemon startup.

Should I add a commit that also tags the other fields as well? 
(that feels like venturing into ensuring and fixing marshalling issues
that are unrelated to this PR...)

File: container/container.go (hunk 3 above)
Comment (vbatts) [reply container/container.go]: Should I add a commit that also tags the other fields as well?
(that feels like venturing into ensuring and fixing marshalling issues
that are unrelated to this PR...)

**Review by cpuguy83 — CHANGES_REQUESTED** [review]
LGTM but needs an integration test in integration/

Thanks!

**Comment by kolyshkin** [comment]
In podman, the relevant CLI option is `--security-opt=unmask=/sys/fs/cgroup`, described [here](https://docs.podman.io/en/v5.2.2/markdown/podman-run.1.html) (look for `unmask).

If at all possible, can the option being added be made compatible with podman?

**Comment by tianon** [comment]
I'm not totally opposed, but it is definitely a weird way to say it -- `/sys/fs/cgroup` isn't currently "masked", it's just mounted read-only, so it's a really awkward UX for "unmask" to be the way to swap it to be writeable.

**Comment by vbatts** [comment]
that seems like an open ended option to not mount over various paths. I get it that podman has that functionality before this PR, but it does seem a bit confusing behavior to expect end users to keep track of having to pass the path specifically. :-\

**Comment by vbatts** [comment]
> On 13/11/24 07:18 -0800, Brian Goff wrote: @cpuguy83 requested changes on this pull request. LGTM but needs an integration test in integration/
> can you point to where similar `docker run --security-options ...` are being tested?

This is an honest request. 
I was looking at some of the tests in integration/ and not entirely grokking what I need to do here

**Comment by cpuguy83** [comment]
Sorry, this fell off my radar last week.
Here's an example of a security opt test: https://github.com/moby/moby/blob/54fff36d956a82fae2664b34038ae7cf778be04a/integration/container/run_linux_test.go#L358-L402

I think we can add the new test to the file.

**Comment by vbatts** [comment]
Thanks for that. I tried a bit this weekend, and not sure if the
failures I'm seeing are due to the tests running inside docker or not. 
Haven't gotten to the bottom of it yet, but it was like the build of
dockerd didn't have my changeset at all.

**Comment by cpuguy83** [comment]
@vbatts If you want to push up your changes we can take a look.
Note that in order to run the test you need to execute `make test-integration`
You can set `TEST_FILTER=<go test filter>` to execute the individual test.

**Comment by vbatts** [comment]
Thanks for that FILTER. I've pushed what I was working from.

File: integration/container/run_linux_test.go [hunk 5]
```diff
@@ -401,3 +401,52 @@ func TestSeccomp(t *testing.T) {
...
+		},
+		{
+			ops:              []func(*container.TestContainerConfig){container.WithSecurityOpt("writable-cgroups=potato")},
+			expectedExitCode: 1,
+		},
+	}
+	for _, tc := range testCases {
+		cID := container.Run(ctx, t, apiClient, tc.ops...)
+		res, err := container.Exec(ctx, apiClient, cID, []string{"/bin/true"})
+		assert.NilError(t, err)
```
Comment (cpuguy83) [inline integration/container/run_linux_test.go:445]: This assert is failing for negative test cases.
Maybe only do this assert if `tc.expectedExitCode == 0`

**Review by cpuguy83 — CHANGES_REQUESTED** [review]

**Comment by kolyshkin** [comment]
> I'm not totally opposed, but it is definitely a weird way to say it -- `/sys/fs/cgroup` isn't currently "masked", it's just mounted read-only, so it's a really awkward UX for "unmask" to be the way to swap it to be writeable.

My guess it's a broad definition of "masking", which includes not only overmounts, but also read-only mounts.

Making the naming consistent (or at least adding a compatible alias) will improve interoperability.

**Comment by vbatts** [comment]
@kolyshkin I get that interpretation of "masking" but is still confusing. Also, for a user to have to provide the explicit path is not great.

File: integration/container/run_linux_test.go (hunk 5 above)
Comment (vbatts) [reply integration/container/run_linux_test.go]: ok. I went about it in a slightly deconstructed way.

**Comment by vbatts** [comment]
updated PTAL

File: integration/container/run_linux_test.go [hunk 6]
```diff
@@ -401,3 +401,48 @@ func TestSeccomp(t *testing.T) {
 		}
 	}
 }
+
+func TestCgroupRW(t *testing.T) {
```
Comment (cpuguy83) [inline integration/container/run_linux_test.go:405]: For the cases that don't error out currently, can we validate that cgroups rw/ro respectively?

**Review by cpuguy83 — CHANGES_REQUESTED** [review]

File: integration/container/run_linux_test.go (hunk 6 above)
Comment (vbatts) [reply integration/container/run_linux_test.go:405]: k, i've added that, but now am curious why the build of `dockerd` from this branch works for me on my machine with the command `docker run -it --rm --security-opt writable-cgroups=true debian mkdir /sys/fs/cgroup/foo`, but it fails in this test as permission denied read-only file system.

Comment (vbatts) [reply integration/container/run_linux_test.go:405]: hrm. I'm puzzling on why this works on the host, but not in the tests...

**Review by Blgwp21 — APPROVED** [review]

File: integration/container/run_linux_test.go [hunk 7]
```diff
@@ -401,3 +401,62 @@ func TestSeccomp(t *testing.T) {
...
+
+	type testCase struct {
+		ops              []func(*container.TestContainerConfig)
+		expectedErrMsg   string
+		expectedExitCode int
+	}
+	testCases := []testCase{
+		{
+			ops: nil,
+			// no err msg, so, success
```
Comment (cpuguy83) [inline integration/container/run_linux_test.go:419]: Looks like this one needs `expectedExitCode: 1` since its using the default case which should be non-writable.

File: integration/container/run_linux_test.go [hunk 8]
```diff
@@ -401,3 +401,62 @@ func TestSeccomp(t *testing.T) {
...
 	}
 }
+
+func TestCgroupRW(t *testing.T) {
+	skip.If(t, testEnv.DaemonInfo.OSType != "linux")
+
+	ctx := setupTest(t)
+	apiClient := testEnv.APIClient()
+
+	type testCase struct {
```
Comment (cpuguy83) [inline integration/container/run_linux_test.go:411]: Can you add a name to the test cases and run them as subtests?

**Comment by tianon** [comment]
@vbatts I hope you don't mind; I took the liberty of pulling your change down locally, adding the subtests @cpuguy83 asked for, and then it was very obvious that the (nil) case he pointed out is why the test fails so I fixed that as well -- I'll look at applying the necessary rebase now

**Review by tianon — APPROVED** [review]

**Review by cpuguy83 — APPROVED** [review]

**Comment by tianon** [comment]
Heh, tests fail on rootless, which I guess we maybe should've foreseen?

```
--- FAIL: TestCgroupRW (1.48s)
    --- FAIL: TestCgroupRW/nil (0.21s)
    --- PASS: TestCgroupRW/writable=true (0.20s)
    --- FAIL: TestCgroupRW/writable=false (0.19s)
    --- PASS: TestCgroupRW/writeable=true (0.01s)
    --- PASS: TestCgroupRW/writable=1 (0.20s)
    --- PASS: TestCgroupRW/writable=potato (0.01s)
...
=== Failed
=== FAIL: amd64.integration.container TestCgroupRW/nil (0.21s)
    run_linux_test.go:465: assertion failed: 1 (tc.expectedExitCode int) != 0 (res.ExitCode int)
    --- FAIL: TestCgroupRW/nil (0.21s)

=== FAIL: amd64.integration.container TestCgroupRW/writable=false (0.19s)
    run_linux_test.go:465: assertion failed: 1 (tc.expectedExitCode int) != 0 (res.ExitCode int)
    --- FAIL: TestCgroupRW/writable=false (0.19s)

=== FAIL: amd64.integration.container TestCgroupRW (1.48s)

DONE 352 tests, 28 skipped, 3 failures in 151.365s
```

**Comment by tianon** [comment]
```go
		// TODO: until a kernel/mount solution exists for handling remount in a user namespace,
		// we must clear the readonly flag for the cgroups mount (@mrunalp concurs)
		if uidMap := daemon.idMapping.UIDMaps; uidMap != nil || c.HostConfig.Privileged || c.WritableCgroups {
```

So accordingly, should specifying this security-opt on rootless be an error for now (and an appropriate skip in the test)?  Or perhaps only trying to disable it explicitly should be an error on rootless?

**Comment by tianon** [comment]
Oh, it fails on Ubuntu 20.04 generally, which is interesting:

```
--- FAIL: TestCgroupRW (1.40s)
    --- FAIL: TestCgroupRW/nil (0.18s)
    --- PASS: TestCgroupRW/writable=true (0.18s)
    --- FAIL: TestCgroupRW/writable=false (0.20s)
    --- PASS: TestCgroupRW/writeable=true (0.01s)
    --- PASS: TestCgroupRW/writable=1 (0.19s)
    --- PASS: TestCgroupRW/writable=potato (0.01s)
...
=== Failed
=== FAIL: amd64.integration.container TestCgroupRW/nil (0.18s)
    run_linux_test.go:465: assertion failed: 1 (tc.expectedExitCode int) != 0 (res.ExitCode int)
    --- FAIL: TestCgroupRW/nil (0.18s)

=== FAIL: amd64.integration.container TestCgroupRW/writable=false (0.20s)
    run_linux_test.go:465: assertion failed: 1 (tc.expectedExitCode int) != 0 (res.ExitCode int)
    --- FAIL: TestCgroupRW/writable=false (0.20s)

=== FAIL: amd64.integration.container TestCgroupRW (1.40s)

DONE 387 tests, 4 skipped, 3 failures in 165.689s
```

**Comment by tianon** [comment]
> This looks like a good addition. Only comment is to make the opt a boolean like `no-new-privileges`, e.g. `writeable-cgroups=true|false`

While working on that, I tried to add support for `--security-opt writable-cgroups` (no `=true`, matching `no-new-privileges`), and ran into https://github.com/docker/cli/blob/f4a68da19595d64c50b0bbc2b1f15e645943ed82/cli/command/container/opts.go#L920-L926 and was sad (why do we validate in both daemon _and_ CLI??)

**Comment by tianon** [comment]
Testing locally, I can reproduce the failures with user namespaces (`--userns-remap=default` on the daemon); everything is "permission denied" -- however, I can't reproduce with rootless (`mkdir /sys/fs/cgroup/foo` inside a privileged container on a rootless daemon works fine) :thinking:

**Comment by tianon** [comment]
I'm going to swap the order of the test asserts so they test the output/stderr first to hopefully give us better clues than the exit code alone as to why this is failing.

**Comment by tianon** [comment]
> I can't reproduce with rootless (`mkdir /sys/fs/cgroup/foo` inside a privileged container on a rootless daemon works fine) 🤔

I've got `WARNING: Running in rootless-mode without cgroups. Systemd is required to enable cgroups in rootless-mode.` in `docker info`, but the container appears to have cgroups and the mkdir works, so uh, I don't know where to go with that, but Ubuntu 20.04 I think might be cgroupsv1 (which the test as-written likely can't handle)?

**Comment by tianon** [comment]
Ok, that's better; rootless:

```
=== RUN   TestCgroupRW
=== RUN   TestCgroupRW/nil
=== RUN   TestCgroupRW/writable=true
    run_linux_test.go:469: assertion failed: 
        --- ←
        +++ →
        @@ -1,2 +1 @@
        -mkdir: can't create directory '/sys/fs/cgroup/foo': Permission denied
         
        
=== RUN   TestCgroupRW/writable=false
=== RUN   TestCgroupRW/writeable=true
=== RUN   TestCgroupRW/writable=1
    run_linux_test.go:469: assertion failed: 
        --- ←
        +++ →
        @@ -1,2 +1 @@
        -mkdir: can't create directory '/sys/fs/cgroup/foo': Permission denied
         
        
=== RUN   TestCgroupRW/writable=potato
--- FAIL: TestCgroupRW (1.21s)
    --- PASS: TestCgroupRW/nil (0.17s)
    --- FAIL: TestCgroupRW/writable=true (0.19s)
    --- PASS: TestCgroupRW/writable=false (0.17s)
    --- PASS: TestCgroupRW/writeable=true (0.00s)
    --- FAIL: TestCgroupRW/writable=1 (0.15s)
    --- PASS: TestCgroupRW/writable=potato (0.00s)
```

**Comment by tianon** [comment]
Ubuntu 20.04:

```
=== RUN   TestCgroupRW
=== RUN   TestCgroupRW/nil
    run_linux_test.go:467: assertion failed: string "" does not contain "Read-only file system"
    run_linux_test.go:472: assertion failed: 1 (tc.expectedExitCode int) != 0 (res.ExitCode int)
=== RUN   TestCgroupRW/writable=true
=== RUN   TestCgroupRW/writable=false
    run_linux_test.go:467: assertion failed: string "" does not contain "Read-only file system"
    run_linux_test.go:472: assertion failed: 1 (tc.expectedExitCode int) != 0 (res.ExitCode int)
=== RUN   TestCgroupRW/writeable=true
=== RUN   TestCgroupRW/writable=1
=== RUN   TestCgroupRW/writable=potato
--- FAIL: TestCgroupRW (1.27s)
    --- FAIL: TestCgroupRW/nil (0.17s)
    --- PASS: TestCgroupRW/writable=true (0.19s)
    --- FAIL: TestCgroupRW/writable=false (0.17s)
    --- PASS: TestCgroupRW/writeable=true (0.00s)
    --- PASS: TestCgroupRW/writable=1 (0.16s)
    --- PASS: TestCgroupRW/writable=potato (0.00s)
```

I think this confirms my hunch, because on cgroupsv1 /sys/fs/cgroup would be a tmpfs so naturally writeable without error in all cases.

**Comment by tianon** [comment]
It'll need a squash, but fingers crossed that finally does it. :see_no_evil:

**Comment by tianon** [comment]
Ubuntu 20.04, grrrrrrrr

```
=== RUN   TestCgroupRW
=== RUN   TestCgroupRW/nil
    run_linux_test.go:483: assertion failed: 1 (tc.expectedExitCode int) != 0 (res.ExitCode int)
=== RUN   TestCgroupRW/writable
=== RUN   TestCgroupRW/writable=true
=== RUN   TestCgroupRW/writable=false
    run_linux_test.go:483: assertion failed: 1 (tc.expectedExitCode int) != 0 (res.ExitCode int)
=== RUN   TestCgroupRW/writeable=true
=== RUN   TestCgroupRW/writable=1
=== RUN   TestCgroupRW/writable=potato
--- FAIL: TestCgroupRW (1.75s)
    --- FAIL: TestCgroupRW/nil (0.18s)
    --- PASS: TestCgroupRW/writable (0.19s)
    --- PASS: TestCgroupRW/writable=true (0.20s)
    --- FAIL: TestCgroupRW/writable=false (0.18s)
    --- PASS: TestCgroupRW/writeable=true (0.01s)
    --- PASS: TestCgroupRW/writable=1 (0.18s)
    --- PASS: TestCgroupRW/writable=potato (0.01s)
```

hopefully it's something obvious (maybe something I'll see more clearly with fresh eyes tomorrow or someone else will before then)

https://github.com/moby/moby/blob/033f97519cded22411eb279a6866be12dd8c8745/contrib/check-config.sh#L153

Using this same test is probably what we need to do, and might even fix this, so I'm going to commit that now before I logoff in case it Does The Thing.

**Comment by tianon** [comment]
Whoa, that really did it. :partying_face:

I guess we need to squash now and reset the CI? :see_no_evil:

**Comment by tianon** [comment]
@vbatts I'd also love you to re-review what I've done to make sure I haven't totally ruined your intent :bow: :heart:

**Comment by thaJeztah** [comment]
@AkihiroSuda PTAL as well (you have a "changes requested" pending)

**Comment by vbatts** [comment]
On 16/01/25 17:19 -0800, Tianon Gravi wrote:
>Ubuntu 20.04, grrrrrrrr

yeah, so cgroups v1. Should we even support that or just stick to v2?

**Comment by tianon** [comment]
https://github.com/moby/moby/pull/48828#discussion_r1833230967

(and it's working now, including the test)

**Comment by thaJeztah** [comment]
Discussing in the maintainers call,  and while allowing this  for cgroups v1  might be less  secure; it's an opt-in feature, and cgroup  v1  should  be  going away at  some point, which means that less special  cases  makes that easier.

I think we  should bring this  in

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by AkihiroSuda** [comment]
LGTM

**Comment by vbatts** [comment]
hah, I opened the tab this morning to review again and LGTM. That's the nudge that the cosmos needed. :-D

**Comment by thaJeztah** [comment]
> hah, I opened the tab this morning to review again and LGTM. That's the nudge that the cosmos needed. :-D

It was good seeing you here!

**Comment by thaJeztah** [comment]
Ha! Jinx https://github.com/docker/cli/pull/3936#issuecomment-1367407283 (so, yes, I :100: share that opinion)

>  (I'd love to get rid of some of that logic in the ParseSecurityOpts; I don't think it should all belong in that function, or even in the CLI code)

I think this was one of the cases where we either tried to repurpose/share code for "daemon" and "client", or (when the CLI was still in this repository), validation was added in the CLI, and (due to "integration-cli" tests highly depending on the CLI) nobody noticed validation was done in the CLI and missing in the API (but the code moved to the CLI when the repositories were split).

I think there's various other examples of this, and we need to work on those, but before ripping it ouf ot the CLI we need to double-check if corresponding validation exists on the daemon side (I think I spotted a few where that was not the case).

For validation in general, I once wrote some notes https://github.com/docker/cli/pull/1859 (highly WIP, but pushed it at the time to share with others that were working on an actual guide); 

> ## Validation
> 
> Docker uses a client/server architecture. As a consequence, the environment in
> which the Docker CLI runs may not match the environment of the _daemon_. For
> this reason, validation on the client-side should be limited, and deferred as
> much as possible to the daemon.
> 
> Offloading validation to the daemon prevents validation-rules from diverging
> between both, and prevents the similar code having to be maintained _twice_. Or
> (worse) having validation code in the client, but unhandled by the daemon.
> 
> In addition; do not expect what's valid to never change (what's invalid today,
> may be supported by the daemon, or the kernel, tomorrow).
> 
> As a rule of thumb: it's the CLI's responsibility to convert commands and arguments
> into API requests. If the CLI is able to handle a value, and turn it into an a
> valid API request (even if values in the request are invalid), that responsibility
> is met. If the request fails, it should handle the error, and (where  needed)
> present it to the user.

There's some nuances there, e.g.  if the client is aware of some options not  being supported on older APIs (and silently ignored), in which case we tend to add some guardrails.

**Comment by vbatts** [comment]
> IMO a good follow up to make the experience even better would be to completely remove all of the cli-side validation in https://github.com/docker/cli/blob/f4a68da19595d64c50b0bbc2b1f15e645943ed82/cli/command/container/opts.go#L920-L926 (but I'm not a CLI maintainer; they may feel differently and might prefer to add this as yet another special case)

It still confuses me how these projects are separate ...
