### PR TITLE
daemon_unix: set golang runtime max threads

### LINKED ISSUE #15258: Docker crashes when MaxThreads is reached
According to [1], the idea of SetMaxThreads is to kill the program to save the OS (similar to oomkill).

The behavior of Docker when the limit is reached is that Docker itself crashes.  This should not happen of course; Docker should be hardened to return a sensible error to the client when it is nearing the MaxThreads limit.

[1] https://github.com/golang/go/blob/master/src/runtime/debug/garbage.go#L136

### PR DESCRIPTION
**Pull request by runcom**
set Go runtime max threads threshold to 90% of `/proc/sys/kernel/threads-max`
relates to #15256 and #15258 

/cc @jeremyeder

Signed-off-by: Antonio Murdaca runcom@redhat.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
I think this closes https://github.com/docker/docker/issues/15256 as well, and https://github.com/docker/docker/issues/18275 (which is a duplicate, and closed already)

**Comment by runcom** [comment]
Yup already added Closes in the first comment 
There's another about the daemon crashing because of reaching this limit but it can't be addressed now (not with this pr)

**Comment by thaJeztah** [comment]
Ah, thanks, I think you referenced that one (https://github.com/docker/docker/issues/15258) initially :D

**Comment by cpuguy83** [comment]
Not sure how I feel about this one. It's bandaging a very real problem (there is a max # of containers that can be run), but we should really solve the issue such that we don't need to fire up ****9**** goroutines per container.

**Comment by thaJeztah** [comment]
I'll /cc

@crosbymichael and @calavera because I think they had plans to do some refactoring; if this issue is redundant after that, we may decide to not implement this feature and accept that there currently are some limitations.

**Comment by runcom** [comment]
> Not sure how I feel about this one. It's bandaging a very real problem (there is a max # of containers that can be run), but we should really solve the issue such that we don't need to fire up *9* goroutines per container.

I understand this and yes that issue should be tackled as well. But I feel something like this, even after lowering the number of goroutines needed for a container, could be something desiderable to better tune the daemon wrt the host on which is running

**Comment by rhatdan** [comment]
If this patch stops the crashing when docker runs out of threads we should add it in addition to fixing the number of threads we use per container.  We just want to eliminate the crash which brings down all containers.

**Comment by jeremyeder** [comment]
Right.  We simply cannot have Docker crash.  The form/shape of the fix seems fine here.  I do think the new "limit" of ~2500 containers is unfortunate though, especially since it came in sideways from golang and was entirely unplanned from Docker's perspective.  Agreed with @cpuguy83 that reducing the number of routines per container is the correct fix, if that's possible.

**Comment by rhatdan** [comment]
Is the option worth it, or should we just set the max threads to 90% Kernel.Max.  Only reason I can see for having the option would be for testing what happens when the max gets hit.

**Comment by LK4D4** [comment]
I agree with @rhatdan that this probably should be hardcoded.
Reducing number of goroutines can be tough :/

**Comment by runcom** [comment]
will do!

**Comment by LK4D4** [comment]
The bad thing about this is that golang never returning threads back.

**Comment by runcom** [comment]
> Right. We simply cannot have Docker crash.

@jeremyeder I tried I think almost everything to try to recover there but that panic isn't even recoverable :/ any other ideas? maybe containers and daemon should be more decoupled so if daemon crashes containers don't die (other than lowering the # of goroutines per container ofc)

**Comment by runcom** [comment]
updated to not be tunable anymore

**Comment by runcom** [comment]
as an example, on my laptop with this patch I can run with a limit of 85k as opposed to the default 10k

**Comment by rhatdan** [comment]
This patch would make it a lot harder to crash based on the number of containers, you would probably run out of Memory before hitting this limit.  (Correct?)

**Comment by runcom** [comment]
@rhatdan yes

**Comment by jeremyeder** [comment]
Can't every really say what the first bottleneck will be, because it all depends on what's running in the containers.  I would say that regardless of what Docker does, and if you don't run out of some other resource first, the kernel task scheduler will be spending a ton of time in tg_load_down (and friends) trying to figure out what to run out of the 85,000 time-sharing threads :-) This has always been a problem, particularly with Java apps that rely on many thousands of threads and is not Docker specific.

BTW @runcom your point about decoupling the daemon from the container processes: this is so important.  IMHO the biggest problem in the whole project right now.

**Comment by thaJeztah** [comment]
Where are we on this? I see some concerns ("The bad thing about this is that golang never returning threads back."), and the preference of fixing the underlying cause ("number of goroutines per container").

Is this something we need fixed now, or should we go for the longer term solution?

**Comment by thaJeztah** [comment]
also /cc @unclejack

**Comment by unclejack** [comment]
I think it'd be best to work towards splitting up various parts of the daemon. Adding a max threads option would only sweep the dirt under the rug because it's treating the symptom, not addressing the real underlying issue which represents the cause.

**Comment by LK4D4** [comment]
I'm not sure, but I think that splitting daemon will only increase the number of goroutines. So it won't be fix for this issue.

**Comment by unclejack** [comment]
It seems it's going to take a while before any other alternative solutions will be ready. Perhaps we should get this PR (or something similar) moving along.

**Comment by rhatdan** [comment]
I agree.  Getting an intermediary fix for this, until we get to the final solution, seems like a good idea.

**Comment by thaJeztah** [comment]
ping @runcom can you rebase this? Might help moving it forward quickly if design is approved :-)

**Comment by runcom** [comment]
@thaJeztah sure :)

**Comment by runcom** [comment]
rebased

**Comment by thaJeztah** [comment]
ping @unclejack @LK4D4 could you have another look at this?

**Comment by runcom** [comment]
rebased again :)

**Comment by runcom** [comment]
@thaJeztah should we add this into 1.10 milestone? I think it's a pretty tiny improvement @LK4D4 wdyt

**Comment by thaJeztah** [comment]
I think the consensus is that other improvements are not yet within reach, so this can be done in the meantime, but I'd like to have a clear picture what the consequences can be of "The bad thing about this is that golang never returning threads back."

ping @LK4D4 wdyt?

**Comment by calavera** [comment]
There are plans in place to solve this problem in a better way for Docker 1.11. See https://github.com/docker/containerd. I don't think we should merge this PR, specially for 1.10.

**Comment by icecrime** [comment]
I agree containerd integration should be a huge win on this regard, and yes it's indeed a top priority for 1.11.

That being said, what could go wrong with this patch? I'm personally tempted to take it in.

**Comment by thaJeztah** [comment]
Alright, I'd say let's get this in; we can remove it if we have solved the problem in another way for 1.11

File: daemon/daemon.go [hunk 1]
```diff
@@ -689,6 +689,10 @@ func NewDaemon(config *Config, registryService *registry.Service) (daemon *Daemo
 	}
 	logrus.Debugf("Using default logging driver %s", config.LogConfig.Type)
 
+	if err := configureMaxThreads(config); err != nil {
+		return nil, err
```
Comment (cpuguy83) [inline daemon/daemon.go]: On err, shouldn't we just log and continue?

File: daemon/daemon_unix.go [hunk 2]
```diff
@@ -433,6 +435,22 @@ func checkSystem() error {
...
+	mt, err := ioutil.ReadFile("/proc/sys/kernel/threads-max")
+	if err != nil {
+		return err
+	}
+	mtint, err := strconv.Atoi(strings.TrimSpace(string(mt)))
+	if err != nil {
+		return err
+	}
+	maxThreads := (mtint / 100) * 90
+	debug.SetMaxThreads(maxThreads)
```
Comment (MHBauer) [inline daemon/daemon_unix.go]: Could we get a log statement in here? I feel like it might help debugging if the threads happen to be set to some strange value to know what value it was set to.

**Comment by tiborvass** [comment]
Apart from the two nits, this is fine by me.

File: daemon/daemon.go (hunk 1 above)
Comment (runcom) [inline daemon/daemon.go]: Agree, no need to error out

File: daemon/daemon_unix.go (hunk 2 above)
Comment (runcom) [inline daemon/daemon_unix.go]: Right

**Comment by runcom** [comment]
Fixed @cpuguy83's and @MHBauer's  comments, PTAL

**Comment by cpuguy83** [comment]
LGTM

**Comment by unclejack** [comment]
Isn't it a bit late to include this in 1.10? I'm just wondering if that's a good idea because we haven't had a chance to see if this could go wrong. If you think we really have enough time to test this properly and that we have enough people testing this, I'm OK with having it in 1.10, even more so because I've commented previously to say we should get this in until the final solution is ready. I'll test this, too.

if we have enough time to test for 1.10 and we keep in mind we might be forced to revert this, LGTM

**Comment by runcom** [comment]
> Isn't it a bit late to include this in 1.10?

I'm not sure either, but it's easy to remove it.
Though, if plans are to remove this patch in 1.11 I don't see why we shouldn't merge it now

**Comment by icecrime** [comment]
I agree, I don't think it's a good idea for 1.10: what I meant earlier is that I was +1 to take it in master.

**Comment by MHBauer** [comment]
I'd LGTM that.

**Comment by unclejack** [comment]
LGTM for master

**Comment by icecrime** [comment]
Can't see to get the WIndows tests to pass (cc @jhowardmsft):

```
16:04:56 ----------------------------------------------------------------------
16:04:56 FAIL: docker_cli_ps_test.go:209: DockerSuite.TestPsListContainersFilterID
16:04:56 
16:04:56 docker_cli_ps_test.go:215:
16:04:56     // start another container
16:04:56     runSleepingContainer(c)
16:04:56 C:/gopath/src/github.com/docker/docker/pkg/integration/dockerCmd_utils.go:35:
16:04:56     c.Assert(err, check.IsNil, check.Commentf("%q failed with errors: %s, %v", strings.Join(args, " "), out, err))
16:04:56 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc0823c7760)} ("exit status 125")
16:04:56 ... "run -d busybox sleep 60" failed with errors: 00a5fcd7ff2ab665d5b5221470995c2deeb7a19bc13cac043649a9201aa01150
16:04:56 D:\CI\CI-933736b\binary\docker.exe: Error response from daemon: Cannot start container 00a5fcd7ff2ab665d5b5221470995c2deeb7a19bc13cac043649a9201aa01150: HCSShim::CreateComputeSystem- Win32 API call returned error r1=0x800401f3 err=Invalid class stringid=00a5fcd7ff2ab665d5b5221470995c2deeb7a19bc13cac043649a9201aa01150 configuration={"SystemType":"Container","Name":"00a5fcd7ff2ab665d5b5221470995c2deeb7a19bc13cac043649a9201aa01150","Owner":"docker","IsDummy":false,"VolumePath":"\\\\?\\Volume{1281b70f-c9c6-11e5-a38a-f171ad98e8f8}","Devices":[{"DeviceType":"Network","Connection":{"NetworkName":"Virtual Switch","EnableNat":false,"Nat":{"Name":"ContainerNAT","PortBindings":null}},"Settings":null}],"IgnoreFlushesDuringBoot":true,"LayerFolderPath":"D:\\CI\\CI-933736b\\daemon\\graph\\windowsfilter\\00a5fcd7ff2ab665d5b5221470995c2deeb7a19bc13cac043649a9201aa01150","Layers":[{"ID":"fa850cc5-e658-5e24-be6f-bd86e84967db","Path":"D:\\CI\\CI-933736b\\daemon\\graph\\windowsfilter\\d12d430ab89dfbfbd57aada7dca50f7628814c5ab8edf0d46ea57b4e31507299"},{"ID":"b76b2a4e-4c39-52d4-954b-58f8e0beca05","Path":"D:\\CI\\CI-933736b\\daemon\\graph\\windowsfilter\\baf6ba49c9b4254ff0705a2da6dda241c0075e7a7bf533cfd93db2ba803d5df2"},{"ID":"b98de07a-552a-59cb-9073-66e6709322ef","Path":"D:\\CI\\CI-933736b\\daemon\\graph\\windowsfilter\\2515c81aca6b6f7fe9cce8fb297a2c6f7ed8d3cca47154716b7d672dce8170cc"},{"ID":"e0547596-9330-53de-b69f-f36ec7dce687","Path":"D:\\CI\\CI-933736b\\daemon\\graph\\windowsfilter\\119745ce2f1830254a34eb27cc6a82011caed493209539cc8babf6ed9555cb69"},{"ID":"38fd1617-0fea-565c-891a-bd61dea46a22","Path":"D:\\CI\\CI-933736b\\daemon\\graph\\windowsfilter\\6f2628df2f803003c980d74ebf2c0ab149f7f43a8be01207cfc7396ba4870a56"},{"ID":"84ea5d62-64ed-574d-a0b6-2d19ec831a27","Path":"C:\\ProgramData\\Microsoft\\Windows\\Images\\CN=Microsoft_WindowsServerCore_10.0.10586.0"}],"HostName":"00a5fcd7ff2a","MappedDirectories":[],"SandboxPath":"","HvPartition":false}.
16:04:56 , exit status 125
16:04:56 
16:05:18 
16:05:18 ----------------------------------------------------------------------
```

**Comment by icecrime** [comment]
I'm taking the liberty of merging anyway as this seems entirely unrelated.
