### PR TITLE
Fix hung docker stop if stop signal and daemon.Kill both fail

### LINKED ISSUE #41579: docker stop hangs forever if it falls back to docker kill and docker kill fails
**Description**

ContainerStop has the potential to deadlock here: https://github.com/moby/moby/blob/7cf6dfcb9e6d0bb135039c73e1e1051e9ea6f2f6/daemon/stop.go#L77-L85

If container stop (signal 15) did not work to kill the container, dockerd tries to do a SIGKILL (9). However, if daemon.Kill returns an error, then dockerd calls the container.Wait function without a timeout. Inside the wait function there are numerous code-paths that obtain a lock on both the container and state objects. So if the SIGKILL also did not work, dockerd will essentially be waiting forever. Subsequent calls to ContainerStop will also hang forever, and potentially deadlock on one of the locks that a previous ContainerStop call is holding.

**Steps to reproduce the issue:**
1. add `return fmt.Errorf("foo error")` here: https://github.com/moby/moby/blob/7cf6dfcb9e6d0bb135039c73e1e1051e9ea6f2f6/daemon/kill.go#L139 
2. Build a docker container that captures SIGTERM:
```
cat << EOF > Dockerfile
FROM bash:5.0

COPY killtrapper.sh /

ENTRYPOINT ["/killtrapper.sh"]
EOF
```
```
cat << EOF > killtrapper.sh
#!/usr/bin/env bash

sigterm() {
    echo "caught a signal"
}

trap 'sigterm' QUIT
trap 'sigterm' INT
trap 'sigterm' HUP
trap 'sigterm' TERM

echo "test script started. My PID is $$"
while :; do
    sleep 0.5
done
EOF
```
3. build and run the container `chmod +x killtrapper.sh && docker build -t "killtrapper" . && docker run -it --rm --name "kt" killtrapper`
4. attempt to stop the container: `docker stop kt`
5. observe that the command hangs forever and this is logged into docker logs:
```
Oct 23 04:17:23 ip-10-0-0-176.us-west-2.compute.internal dockerd[29371]: time="2020-10-23T04:17:23.883792164Z" level=info msg="Container e0d10e9ca9d06815a903de8bab96c98b7b7d2435f6afc41bbe54e188f112564c failed to exit within 10 seconds of signal 15 - using the force"
```

**Describe the results you expected:**

If docker stop fails, log the error and return

**Output of `docker version`:**

```
dockerd engine is current head of master:
Client:
 Version:           19.03.6-ce
 API version:       1.40
 Go version:        go1.13.4
 Git commit:        369ce74
 Built:             Fri May 29 04:01:26 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          dev
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8a4671fb1f
  Built:            Fri Oct 23 04:07:23 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.2
  GitCommit:        ff48f57fc83a8c44cf4ad5d672424a98ba37ded6
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 7
 Server Version: dev
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ff48f57fc83a8c44cf4ad5d672424a98ba37ded6
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683 (expected: de40ad0)
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.14.198-152.320.amzn2.x86_64
 Operating System: Amazon Linux 2
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 30.96GiB
 Name: ip-10-0-0-176.us-west-2.compute.internal
 ID: J7BA:BTKN:ZD5S:FWGT:2A2Y:NKTF:DDAJ:QSNA:UE23:L6S2:W7RG:BXBK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

this test was run on an AWS m5.xlarge instance

### PR DESCRIPTION
**Pull request by sparrc**
replaces https://github.com/moby/moby/pull/41580

this refactors the Stop command to fix a few issues and behaviors that
dont seem completely correct:

1. first it fixes a situation where stop could hang forever (#41579)
2. fixes a behavior where if sending the
stop signal failed, then the code directly sends a -9 signal. If that
fails, it returns without waiting for the process to exit or going
through the full docker kill codepath.
3. fixes a behavior where if sending the stop signal failed, then the
code sends a -9 signal. If that succeeds, then we still go through the
same stop waiting process, and may even go through the docker kill path
again, even though we've already sent a -9.
4. fixes a behavior where the code would wait the full 30 seconds after
sending a stop signal, even if we already know the stop signal failed.

(2 and 3 were both fixed to not send a -9 directly, and instead rely on the docker kill codepath)

fixes #41579

**- What I did**

remove waiting without a timeout when docker kill fails within docker stop

**before change:**

cli:
```
% docker stop # hangs forever
```
```
Oct 23 04:17:23 ip-10-0-0-176.us-west-2.compute.internal dockerd[29371]: time="2020-10-23T04:17:23.883792164Z" level=info msg="Container e0d10e9ca9d06815a903de8bab96c98b7b7d2435f6afc41bbe54e188f112564c failed to exit within 10 seconds of signal 15 - using the force"
```

**after change:**
cli:
```
% docker stop kt
Error response from daemon: cannot stop container: kt: foo error
```

docker logs:
```
Oct 24 20:30:08 ip-10-0-0-157.us-west-2.compute.internal dockerd[30001]: time="2020-10-24T20:30:08.683984540Z" level=info msg="Container failed to exit within 10 seconds of signal 15 - using the force" container=ae525e8f6493cdebe26ba275b7c8f02509827b27d6b637dc99614fd90fe67f4c
Oct 24 20:30:10 ip-10-0-0-157.us-west-2.compute.internal dockerd[30001]: time="2020-10-24T20:30:10.684154746Z" level=error msg="Error killing the container" container=ae525e8f6493cdebe26ba275b7c8f02509827b27d6b637dc99614fd90fe67f4c error="foo error"
Oct 24 20:30:10 ip-10-0-0-157.us-west-2.compute.internal dockerd[30001]: time="2020-10-24T20:30:10.684256073Z" level=error msg="Handler for POST /v1.40/containers/kt/stop returned error: cannot stop container: kt: foo error"
```

**- Description for the changelog**

Fix hung docker stop if SIGTERM and SIGKILL both fail

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by angelcar — APPROVED** [review]

**Comment by sparrc** [comment]
hello, any chance I could get some eyes on this and https://github.com/moby/moby/pull/41588 ? Im free to do a skype call if it would help to talk through the changes

**Comment by thaJeztah** [comment]
@cpuguy83 PTAL; looks like this is making changes in the same area as your PR https://github.com/moby/moby/pull/41698

**Comment by sparrc** [comment]
hello, we are continuing to see this issue in ECS, any chance we could get some eyes on this fix?

File: daemon/stop.go [hunk 1]
```diff
@@ -41,49 +41,48 @@ func (daemon *Daemon) containerStop(container *containerpkg.Container, seconds i
...
-			logrus.Infof("Container failed to stop after sending signal %d to the process, force killing", stopSignal)
-			if err := daemon.killPossiblyDeadProcess(container, 9); err != nil {
-				return err
-			}
+		if status := <-container.Wait(ctx, containerpkg.WaitConditionNotRunning); status.Err() == nil {
+			// container did exit, so ignore error and return
+			return success()
+		}
+		logrus.WithError(err).WithField("container", container.ID).Errorf("Error sending stop (signal %d) to container", stopSignal)
+	} else {
```
Comment (cpuguy83) [inline daemon/stop.go:60]: I'm not sure what this else is accomplishing here (other than changing the time we wait).
Can we do something like set `wait := seconds`, and change `wait` to `2`  if `daemon.killPossiblyDeadProcess` errors?

**Review by cpuguy83 — CHANGES_REQUESTED** [review]
Just a nit about the `else` but otherwise this seems ok.

I don't see what this is fixing, though, other than waiting indefinitely (which is itself worthy of fixing of course).
In which case it's probably also good to plumb a context through from the http request.

File: daemon/stop.go (hunk 1 above)
Comment (sparrc) [reply daemon/stop.go:60]: sure, will make that change

Comment (sparrc) [reply daemon/stop.go]: done

File: daemon/stop.go [hunk 2]
```diff
@@ -41,49 +41,46 @@ func (daemon *Daemon) containerStop(container *containerpkg.Container, seconds i
...
-		defer cancel()
 
-		if status := <-container.Wait(ctx, containerpkg.WaitConditionNotRunning); status.Err() != nil {
-			logrus.Infof("Container failed to stop after sending signal %d to the process, force killing", stopSignal)
-			if err := daemon.killPossiblyDeadProcess(container, 9); err != nil {
-				return err
-			}
+	// 1. Send a stop signal
+	err := daemon.killPossiblyDeadProcess(container, stopSignal)
+	wait := 2 * time.Second
```
Comment (cpuguy83) [inline daemon/stop.go:52]: For defaults here I'd start with 10s (if no duration was passed in).
In the error condition we can drop that down to 2 seconds.

**Review by cpuguy83 — CHANGES_REQUESTED** [review]

File: daemon/stop.go (hunk 2 above)
Comment (sparrc) [reply daemon/stop.go]: Okay, this is done, but also I should not that I refactored the default handling and stop timeout a little bit after realizing that waiting forever is the intended behavior when this function is called with seconds < 0. At least according to the comment on the ContainerStop function: https://github.com/moby/moby/blob/46cdcd206c56172b95ba5c77b827a722dab426c5/daemon/stop.go#L13-L21

File: daemon/stop.go [hunk 3]
```diff
@@ -41,49 +41,54 @@ func (daemon *Daemon) containerStop(container *containerpkg.Container, seconds i
...
-		}
+	// 1. Send a stop signal
+	err := daemon.killPossiblyDeadProcess(container, stopSignal)
+	if err != nil {
+		wait = 2 * time.Second
 	}
 
-	// 2. Wait for the process to exit on its own
-	ctx := context.Background()
+	var ctx context.Context
```
Comment (cpuguy83) [inline daemon/stop.go:60]: Lets set this explicitly to `context.TODO()`, especially since context should never be nil.

Comment (cpuguy83) [reply daemon/stop.go:60]: Then there is no need for `var cancel`, since that can be dealt with inside the `if`

Comment (cpuguy83) [reply daemon/stop.go:60]: `TODO()` because we really need to propagate a context down to this function, I have a separate PR that does that.
This will effectively allow an API request to cancel the wait instead of detaching from it.

**Review by cpuguy83 — CHANGES_REQUESTED** [review]

File: daemon/stop.go (hunk 3 above)
Comment (sparrc) [reply daemon/stop.go:60]: okay will do

Comment (sparrc) [reply daemon/stop.go]: this is done, I have added the TODO context and made new contexts with timeouts internal to this func "subCtx"

File: daemon/stop.go [hunk 4]
```diff
@@ -38,52 +38,56 @@ func (daemon *Daemon) ContainerStop(name string, timeout *int) error {
...
+	if err != nil {
+		// the container has still not exited, and the kill function errored, so log the error here:
+		logrus.WithError(err).WithField("container", container.ID).Errorf("Error sending stop (signal %d) to container", stopSignal)
+	}
+	logrus.WithField("container", container.ID).Infof("Container failed to exit within %d seconds of signal %d - using the force", seconds, stopSignal)
+
+	// Stop either failed or container didnt exit, so fallback to kill.
+	if err := daemon.Kill(container); err != nil {
+		// got a kill error, but give container 2 more seconds to exit just in case
+		subCtx, cancel := context.WithTimeout(ctx, 2*time.Second)
```
Comment (cpuguy83) [inline daemon/stop.go:82]: I would bump this up to a higher value just because if the system is loaded this could have cause more issues.... maybe a minute?

I don't think we have the container lock here. Presuming I'm right waiting shouldn't cause any problems just so long as we eventually give up.

Comment (sparrc) [reply daemon/stop.go:82]: At this point the kill signal has failed for some reason, waiting for 1 minute seems overly long to me. Reason being that a caller of this function may set a timeout for how long they are willing to wait at a higher level than this function. If they passed in 10s as the timeout (the default) to container stop it seems a bit excessive to wait for an entire minute after the kill signal has failed.

If you'd really like to wait longer here, perhaps something on the order of 10 seconds?

Comment (cpuguy83) [reply daemon/stop.go:82]: @sparrc Currently the only way for the caller to set a timeout is from the passed in wait value. We could use that, but I think 2 seconds is too small and indefinite is too long.

Comment (sparrc) [reply daemon/stop.go:82]: In ECS we implemented a timeout to avoid our code waiting forever on docker returning from the ContainerStop function call. In my opinion this function shouldn't wait much longer than what the user passes in via the `seconds` argument.

If we use `wait` again here, then this function will usually take around `wait` seconds, with the possibility to take `2 * wait` seconds. To me this is probably better than `wait + 60s`

I guess this is all a moot point anyways if you say that you have a change incoming to add the ability for the user to pass in a context anyways. I will amend this PR to use `wait` again here.

Comment (sparrc) [reply daemon/stop.go:82]: That being said, in the above code we lower `wait` to 2s when SIGTERM fails, so this logic may start to get complicated unless you would like me to also increase the wait after SIGTERM failure to something else?

File: daemon/stop.go [hunk 5]
```diff
@@ -38,52 +38,56 @@ func (daemon *Daemon) ContainerStop(name string, timeout *int) error {
...
-		if status := <-container.Wait(ctx, containerpkg.WaitConditionNotRunning); status.Err() != nil {
-			logrus.Infof("Container failed to stop after sending signal %d to the process, force killing", stopSignal)
-			if err := daemon.killPossiblyDeadProcess(container, 9); err != nil {
-				return err
-			}
-		}
+	// 1. Send a stop signal
+	err := daemon.killPossiblyDeadProcess(container, stopSignal)
+	if err != nil {
+		wait = 2 * time.Second
```
Comment (samuelkarp) [inline daemon/stop.go:59]: We lost the comment explaining the reasoning for 2 seconds here.  Can we add something back in?  Otherwise this looks like a magic number without an explanation.

Also: this clobbers the value assigned to `wait` on line 48

File: daemon/stop.go [hunk 6]
```diff
@@ -38,52 +38,56 @@ func (daemon *Daemon) ContainerStop(name string, timeout *int) error {
...
-	// 2. Wait for the process to exit on its own
-	ctx := context.Background()
+	subCtx, cancel := context.WithCancel(ctx)
 	if seconds >= 0 {
-		var cancel context.CancelFunc
-		ctx, cancel = context.WithTimeout(ctx, time.Duration(seconds)*time.Second)
-		defer cancel()
+		// if seconds has been set, then set a timeout on the context so we dont wait forever
+		subCtx, cancel = context.WithTimeout(ctx, wait)
+	}
```
Comment (samuelkarp) [inline daemon/stop.go:66]: If `seconds` is 0, even if we set a value for `wait` on line 59 we're still not setting a timeout on the context?  Is that intentional?  Would it be better to check whether `wait` is zero here?

File: daemon/stop.go [hunk 7]
```diff
@@ -38,52 +38,56 @@ func (daemon *Daemon) ContainerStop(name string, timeout *int) error {
...
 
-	if status := <-container.Wait(ctx, containerpkg.WaitConditionNotRunning); status.Err() != nil {
-		logrus.Infof("Container %v failed to exit within %d seconds of signal %d - using the force", container.ID, seconds, stopSignal)
-		// 3. If it doesn't, then send SIGKILL
-		if err := daemon.Kill(container); err != nil {
-			// Wait without a timeout, ignore result.
-			<-container.Wait(context.Background(), containerpkg.WaitConditionNotRunning)
-			logrus.Warn(err) // Don't return error because we only care that container is stopped, not what function stopped it
+	if err != nil {
+		// the container has still not exited, and the kill function errored, so log the error here:
```
Comment (samuelkarp) [inline daemon/stop.go:74]: I think it's worth inverting the conditional and out-denting the logic here since there's nothing left to do if there was no error

```suggestion
	if err == nil {
		return success()
	}

	// the container has still not exited, and the kill function errored, so log the error here:
```

File: daemon/stop.go (hunk 5 above)
Comment (sparrc) [reply daemon/stop.go:59]: it is a bit of a magic number, I can add a comment but Im not sure I have anything great to say about it. If you look around these files and kill functions there are quite a lot places where it does "this failed but wait 2 seconds to see if the container exited anyways", so I was just following that pattern.

File: daemon/stop.go (hunk 6 above)
Comment (sparrc) [reply daemon/stop.go:66]: `docker stop` explicitly allows disabling the `docker kill` fallback by setting a negative timeout value (and thus waiting forever after SIGTERM). That's why it's checking `>=`.

If the user explicitly set the timeout for the wait after sending a stop signal to 0, then I guess we should respect that.

File: daemon/stop.go (hunk 7 above)
Comment (sparrc) [reply daemon/stop.go:74]: sure i can do that

File: daemon/stop.go (hunk 6 above)
Comment (samuelkarp) [reply daemon/stop.go:66]: > If the user explicitly set the timeout for the wait after sending a stop signal to 0, then I guess we should respect that.

You're doing that on line 59 irrespective of whether `seconds` was `>= 0` which is why I'm confused.

File: daemon/stop.go (hunk 5 above)
Comment (samuelkarp) [reply daemon/stop.go:59]: Are you intentionally overwriting the value passed in as `seconds` though?

Comment (sparrc) [reply daemon/stop.go:59]: yes it's intentionally being overwritten, I'm not sure I agree with the behavior but the intention was to preserve the existing behavior as much as possible while getting rid of the infinite hang.

If you look at the deleted code in line 58 you can see that if killPossiblyDeadProcess failed then the container would be given 2 seconds to exit, so the intention here was just to maintain that behavior.

**Comment by sparrc** [comment]
Just wanted to check in here with @samuelkarp and @cpuguy83 and summarize the current behavior in this PR, you can see it below.

For next steps on this PR, which of these behaviors do we want to change? My understanding is that @cpuguy83 would like to increase the 2 second wait after SIGKILL failures. @samuelkarp would possibly like to remove the potential to wait forever after SIGTERM fails (ie, keep the wait at 2s even if `seconds` is negative). Is that correct?

### sunny day scenario:
1. send SIGTERM to container
2. wait up to `seconds` seconds for it to exit (or wait forever if seconds is negative)
3. send SIGKILL to container
4. return nil (success)

### SIGTERM fails scenario:
1. send SIGTERM to container, it fails
2. wait 2 seconds to see if container exited anyways (or wait forever is seconds is negative)
3. send SIGKILL to container
4. return nil (success)

### SIGKILL fails scenario:
1. send SIGTERM to container
2. wait up to `seconds` seconds for it to exit (or wait forever if seconds is negative)
3. send SIGKILL to container, it fails
4. wait 2 seconds to see if container exited anyways
5. if container exits, return nil (success), if it doesn't exit then return error

File: daemon/stop.go (hunk 6 above)
Comment (sparrc) [reply daemon/stop.go:66]: see comment below: https://github.com/moby/moby/pull/41586#issuecomment-786871667

File: daemon/stop.go (hunk 5 above)
Comment (sparrc) [reply daemon/stop.go:59]: see comment below: https://github.com/moby/moby/pull/41586#issuecomment-786871667

**Comment by mmerkes** [comment]
@sparrc @cpuguy83 @samuelkarp What's the status of this PR? Would love to get it merged. Sounds like it would fix somewhat frequent issues with see on Kubernetes nodes.

**Comment by sparrc** [comment]
@cpuguy83 more thoughts on this?

**Comment by sparrc** [comment]
@cpuguy83 any time to take another look at this? We're still regularly seeing customers running into this issue

**Review by cpuguy83 — APPROVED** [review]
I'm fine with it like this. LGTM.

**Comment by cpuguy83** [comment]
Can you re-push so we can trigger CI again?

**Comment by sparrc** [comment]
yes will do

**Comment by sparrc** [comment]
from what I can tell most of the tests passed except on s390x and win rs5, which seem to be unrelated failures, does it look OK @cpuguy83 ?

**Comment by cpuguy83** [comment]
```
[2021-04-05T17:18:29.821Z] daemon/stop.go:41:10: `propogate` is a misspelling of `propagate` (misspell)
[2021-04-05T17:18:29.821Z] 	// TODO propogate a context down to this function
```

**Comment by sparrc** [comment]
> ```
> [2021-04-05T17:18:29.821Z] daemon/stop.go:41:10: `propogate` is a misspelling of `propagate` (misspell)
> [2021-04-05T17:18:29.821Z] 	// TODO propogate a context down to this function
> ```

oops! fixed ✅

**Comment by sparrc** [comment]
Now it seems to only be failing on the s390x integration tests, so i think this time it's an unrelated failure. How does it look @cpuguy83 ?

**Comment by sparrc** [comment]
Is there anything we are waiting on to get this merged? Does it need to be reviewed by another maintainer?

**Comment by cpuguy83** [comment]
@sparrc Yes, still needs another review.

File: daemon/stop.go (hunk 7 above)
Comment (tianon) [reply daemon/stop.go:74]: I agree, but I also feel like there's an edge case here when the user specifies `seconds < 0` (thus no timeout), but the "wait for container to stop" context gets cancelled for other reasons, such as the client disconnecting.

My interpretation of `seconds < 0` is "client requested we wait forever" but that implies "client requested we 'stop' but never kill" so I think after the `if err == nil` block, we probably should also handle that edge case, right?

```suggestion
	if err == nil {
		return success()
	}
	if seconds < 0 {
		// if the client requested that we never kill / wait forever, but container.Wait was still interrupted (parent context cancelled, for example), we should propagate the signal failure
		return err
	}
	// the container has still not exited, and the kill function errored, so log the error here:
```

(Have to admit I'm a little bit out of my depth, so I might be misunderstanding the flow.)

Should we also explicitly invoke `cancel()` here since we know for sure that the current `subCtx` is finished? (before we confusingly reuse/shadow those variable names later in the "kill" block)

**Review by tianon — COMMENTED** [review]
Not sure I'm the right maintainer to have review this, but I've left a few comments/questions. :sweat_smile:

File: daemon/stop.go [hunk 8]
```diff
@@ -38,52 +38,56 @@ func (daemon *Daemon) ContainerStop(name string, timeout *int) error {
...
 
-	// 2. Wait for the process to exit on its own
-	ctx := context.Background()
+	subCtx, cancel := context.WithCancel(ctx)
 	if seconds >= 0 {
-		var cancel context.CancelFunc
-		ctx, cancel = context.WithTimeout(ctx, time.Duration(seconds)*time.Second)
-		defer cancel()
+		// if seconds has been set, then set a timeout on the context so we dont wait forever
+		subCtx, cancel = context.WithTimeout(ctx, wait)
```
[the remark this answers is not in the document]
Comment (sparrc) [reply daemon/stop.go:65]: yes i can make this change

**Comment by sparrc** [comment]
> I agree, but I also feel like there's an edge case here when the user specifies seconds < 0 (thus no timeout), but the "wait for container to stop" context gets cancelled for other reasons, such as the client disconnecting.

> My interpretation of seconds < 0 is "client requested we wait forever" but that implies "client requested we 'stop' but never kill" so I think after the if err == nil block, we probably should also handle that edge case, right?

	if err == nil {
		return success()
	}
	if seconds < 0 {
		// if the client requested that we never kill / wait forever, but container.Wait was still interrupted (parent context cancelled, for example), we should propagate the signal failure
		return err
	}
	// the container has still not exited, and the kill function errored, so log the error here:

(Have to admit I'm a little bit out of my depth, so I might be misunderstanding the flow.)

> Should we also explicitly invoke cancel() here since we know for sure that the current subCtx is finished? (before we confusingly reuse/shadow those variable names later in the "kill" block)

(Github won't let me comment in-line for some reason)

1. I disagree that we should return success() when err == nil. At this point that would mean that SIGTERM sent to the container succeeded, yet the container never exited. I think in this case we should log that the container never exited and move on to SIGKILL, as the code is currently doing.
2. Yes you're correct...there is an edge case where seconds is less than 0 and the context could be cancelled during the wait function for some reason. I can add in the second if-statement as you've suggested.

File: daemon/stop.go (hunk 6 above)
Comment (sparrc) [reply daemon/stop.go]: yep that's correct

**Comment by sparrc** [comment]
Okay, I have pushed some changes addressing comments, @tianon can you please take another look?

**Review by tianon — APPROVED** [review]
LGTM

(I guess there's technically a tiny edge case for where `SIGKILL` succeeds but doesn't kill the process/container, but I've only ever seen that with much deeper underlying system issues like a kernel lockup, so IMO it isn't worth handling in any special way here.)

**Comment by cpuguy83** [comment]
I think that can, and probably should be, dealt with by deleting the task in containerd, but not necessary to deal with here.

**Review by cpuguy83 — APPROVED** [review]
LGTM
