### PR TITLE
Ensure clean engine shutdown on startup errors

### LINKED ISSUE #7585: Daemon fails to start, emits "invalid argument" message
Environment:
```
$ uname -a
Linux ip-10-5-152-136 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

$ sudo docker version
Client version: 1.1.2
Client API version: 1.13
Go version (client): go1.2.1
Git commit (client): d84a070
2014/08/14 19:44:15 Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
```

Trying to start Docker:
```
$ sudo docker -d -D
2014/08/14 19:45:07 docker daemon: 1.1.2 d84a070; execdriver: native; graphdriver:
[cecc9e7f] +job serveapi(unix:///var/run/docker.sock)
[cecc9e7f] +job initserver()
[cecc9e7f.initserver()] Creating server
2014/08/14 19:45:07 Listening for HTTP on unix (/var/run/docker.sock)
[debug] server.go:1137 Registering GET, /images/search
[debug] server.go:1137 Registering GET, /images/{name:.*}/get
[debug] server.go:1137 Registering GET, /containers/{name:.*}/logs
[debug] server.go:1137 Registering GET, /_ping
[debug] server.go:1137 Registering GET, /version
[debug] server.go:1137 Registering GET, /images/json
[debug] server.go:1137 Registering GET, /images/{name:.*}/history
[debug] server.go:1137 Registering GET, /images/{name:.*}/json
[debug] server.go:1137 Registering GET, /containers/ps
[debug] server.go:1137 Registering GET, /containers/{name:.*}/changes
[debug] server.go:1137 Registering GET, /containers/{name:.*}/attach/ws
[debug] server.go:1137 Registering GET, /info
[debug] server.go:1137 Registering GET, /containers/json
[debug] server.go:1137 Registering GET, /containers/{name:.*}/json
[debug] server.go:1137 Registering GET, /containers/{name:.*}/top
[debug] server.go:1137 Registering GET, /events
[debug] server.go:1137 Registering GET, /images/viz
[debug] server.go:1137 Registering GET, /containers/{name:.*}/export
[debug] server.go:1137 Registering POST, /auth
[debug] server.go:1137 Registering POST, /containers/create
[debug] server.go:1137 Registering POST, /containers/{name:.*}/pause
[debug] server.go:1137 Registering POST, /containers/{name:.*}/unpause
[debug] server.go:1137 Registering POST, /containers/{name:.*}/restart
[debug] server.go:1137 Registering POST, /images/create
[debug] server.go:1137 Registering POST, /images/{name:.*}/tag
[debug] server.go:1137 Registering POST, /containers/{name:.*}/wait
[debug] server.go:1137 Registering POST, /containers/{name:.*}/resize
[debug] server.go:1137 Registering POST, /containers/{name:.*}/attach
[debug] server.go:1137 Registering POST, /build
[debug] server.go:1137 Registering POST, /images/{name:.*}/push
[debug] server.go:1137 Registering POST, /containers/{name:.*}/kill
[debug] server.go:1137 Registering POST, /containers/{name:.*}/start
[debug] server.go:1137 Registering POST, /containers/{name:.*}/copy
[debug] server.go:1137 Registering POST, /commit
[debug] server.go:1137 Registering POST, /images/load
[debug] server.go:1137 Registering POST, /containers/{name:.*}/stop
[debug] server.go:1137 Registering DELETE, /containers/{name:.*}
[debug] server.go:1137 Registering DELETE, /images/{name:.*}
[debug] server.go:1137 Registering OPTIONS,
[debug] server.go:1227 docker group found. gid: 111
[debug] deviceset.go:552 Generated prefix: docker-202:16-2752542
[debug] deviceset.go:555 Checking for existence of the pool 'docker-202:16-2752542-pool'
invalid argument
[cecc9e7f] -job initserver() = ERR (1)
2014/08/14 19:45:07 invalid argument
```

strace:
```
$ sudo strace -o docker.log docker -d -D
```
[**strace output gist**](https://gist.github.com/sbward/ddb509379f16a852fd2c)

In strace I see [these lines](https://gist.github.com/sbward/ddb509379f16a852fd2c#file-docker-log-L784-L785) which appear to be the source of the "invalid argument" message:
```
mount("", "/mnt/image/docker/devicemapper", "none", MS_PRIVATE, NULL) = -1 EINVAL (Invalid argument)
write(2, "invalid argument\n", 17)      = 17
```

Other relevant info:
- `/var/lib/docker` is a symlink to an ext4 mounted filesystem (AWS EBS), specifically `/mnt/image/docker` as you can see in the strace

### PR DESCRIPTION
**Pull request by cpuguy83**
Previously on error either from the daemon or from the api it is just
exiting with exit status 1 but not performing a shutdown.
This can produce insconsistent state depending on where the error came
from.

This makes sure that before we exit on error that the engine gets fully
shutdown.

I'm hoping this fixes #7585
For sure I can reliably reproduce dangling mounts with something as simple as having invalid tls keys specified (or anything that causes the `serveapi` job to error out)

### CODE REVIEW

File: docker/daemon.go [hunk 1]
```diff
@@ -113,8 +119,9 @@ func mainDaemon() {
 			d.GraphDriver().String(),
 		)
 
-		if err := d.Install(eng); err != nil {
-			log.Fatal(err)
+		if err = d.Install(eng); err != nil {
```
Comment (tiborvass) [inline docker/daemon.go]: @cpuguy83 either do `err = d.Install(eng)` on a separate line, or use `if err := ...` :)

File: docker/daemon.go [hunk 2]
```diff
@@ -123,10 +130,15 @@ func mainDaemon() {
 		// after the daemon is done setting up we can tell the api to start
 		// accepting connections
 		if err := eng.Job("acceptconnections").Run(); err != nil {
-			log.Fatal(err)
+			log.Error(err)
+			return
 		}
+
+		log.Debugf("daemon goroutine finished")
+		return
```
Comment (tiborvass) [inline docker/daemon.go]: no need for return here

File: docker/daemon.go [hunk 3]
```diff
@@ -101,11 +102,16 @@ func mainDaemon() {
 	// load the daemon in the background so we can immediately start
 	// the http api so that connections don't fail while the daemon
 	// is booting
+	var wg sync.WaitGroup
+	wg.Add(1)
 	go func() {
+		defer wg.Done()
```
Comment (tiborvass) [inline docker/daemon.go]: no need for the `sync` package for this one, you can use a channel.

```Go
wait := make(chan struct{})
go func() {
    defer close(wait)
}()
select {
    case <-wait:
    case <-time.After(time.Minute):
        // handle timeout
}
```

File: docker/daemon.go [hunk 4]
```diff
@@ -141,7 +153,17 @@ func mainDaemon() {
...
+	err = job.Run()
+
+	// Wait for the daemon startup goroutine to finish
+	// This makes sure we can actually cleanly shutdown the daemon
+	wg.Wait()
+	eng.Shutdown()
+	if err != nil {
+		// log errors here so the log output looks more consistent
+		log.Error(err)
+		log.Error("shutting down daemon due to errors")
```
Comment (tiborvass) [inline docker/daemon.go]: might as well do `log.Fatalf("shutting down daemon due to errors %v", err)` for this one :)

File: docker/daemon.go [hunk 5]
```diff
@@ -141,7 +153,17 @@ func mainDaemon() {
 	job.Setenv("TlsCert", *flCert)
 	job.Setenv("TlsKey", *flKey)
 	job.SetenvBool("BufferRequests", true)
-	if err := job.Run(); err != nil {
-		log.Fatal(err)
+	err = job.Run()
```
Comment (tiborvass) [inline docker/daemon.go]: why don't you declare the variable here instead of on line 141 ?

Comment (cpuguy83) [inline docker/daemon.go]: Just didn't clean up from a slightly different implementation, I'll take care of it.

File: docker/daemon.go (hunk 3 above)
Comment (cpuguy83) [inline docker/daemon.go]: As discussed on IRC, can't use timeout since there's really no way to know how long the daemon will take to load since this depends on number of images/containers.

**Comment by cpuguy83** [comment]
@tiborvass updated with your suggestions

File: docker/daemon.go [hunk 6]
```diff
@@ -141,7 +151,17 @@ func mainDaemon() {
...
 	job.Setenv("TlsKey", *flKey)
 	job.SetenvBool("BufferRequests", true)
-	if err := job.Run(); err != nil {
-		log.Fatal(err)
+	err := job.Run()
+
+	// Wait for the daemon startup goroutine to finish
+	// This makes sure we can actually cleanly shutdown the daemon
+	log.Infof("waiting for daemon to initialize")
+	wg.Wait()
```
Comment (tiborvass) [inline docker/daemon.go]: shouldnt this be before the job.Run ?

Comment (cpuguy83) [inline docker/daemon.go]: No, the whole reason this is setup the way it is is so the API can be available to take requests while the daemon is still booting.

File: docker/daemon.go [hunk 7]
```diff
@@ -101,11 +101,17 @@ func mainDaemon() {
 	// load the daemon in the background so we can immediately start
 	// the http api so that connections don't fail while the daemon
 	// is booting
+	daemonWait := make(chan struct{}, 1)
```
Comment (tiborvass) [inline docker/daemon.go]: Doesn't it work with an unbuffered channel?

File: docker/daemon.go [hunk 8]
```diff
@@ -101,11 +101,17 @@ func mainDaemon() {
...
 	go func() {
+		defer func() {
+			daemonWait <- struct{}{}
```
Comment (tiborvass) [inline docker/daemon.go]: i would simply close the channel

File: docker/daemon.go [hunk 9]
```diff
@@ -141,7 +151,17 @@ func mainDaemon() {
...
+	err := job.Run()
+
+	// Wait for the daemon startup goroutine to finish
+	// This makes sure we can actually cleanly shutdown the daemon
+	log.Infof("waiting for daemon to initialize")
+	<-daemonWait
+	eng.Shutdown()
+	if err != nil {
+		// log errors here so the log output looks more consistent
+		log.Errorf("shutting down daemon due to errors: %v", err)
```
Comment (tiborvass) [inline docker/daemon.go]: you can use Fatalf directly, it calls os.Exit

File: docker/daemon.go (hunk 8 above)
Comment (cpuguy83) [inline docker/daemon.go]: Oh yeah, nice.  Updated.

File: docker/daemon.go (hunk 9 above)
Comment (cpuguy83) [inline docker/daemon.go]: Done.

File: docker/daemon.go [hunk 10]
```diff
@@ -101,11 +101,17 @@ func mainDaemon() {
 	// load the daemon in the background so we can immediately start
 	// the http api so that connections don't fail while the daemon
 	// is booting
+	daemonWait := make(chan struct{})
 	go func() {
+		defer func() {
+			close(daemonWait)
+		}()
```
Comment (jfrazelle) [inline docker/daemon.go]: this can be `defer close(daemonWait)`

**Comment by jfrazelle** [comment]
LGTM other than the nit

**Comment by jfrazelle** [comment]
LGTM from @crosbymichael who is sitting here too

**Comment by LK4D4** [comment]
@jfrazelle Now you need fix nit yourself! :D
