### PR TITLE
Fixes issue #10184.

### LINKED ISSUE #10184: Cannot control permissions of /dev/fuse device
The device always ends up without permissions:

```
$ docker run --rm ubuntu:14.04 ls -l /dev/fuse 
c--------- 1 root root 10, 229 Jan 19 13:52 /dev/fuse

$ docker run --rm --device /dev/fuse:/dev/fuse:mrw ubuntu:14.04 ls -l /dev/fuse  
c--------- 1 root root 10, 229 Jan 19 13:50 /dev/fuse

docker run --rm --device /dev/fuse:/dev/fuse2:mrw ubuntu:14.04 ls -l /dev/fuse /dev/fuse2
c--------- 1 root root 10, 229 Jan 19 13:53 /dev/fuse
crw-rw-rw- 1 root root 10, 229 Jan 19 13:53 /dev/fuse2
```

I exepct it's something to do with this code: https://github.com/docker/docker/blob/487a417d9fd074d0e78876072c7d1ebfd398ea7a/vendor/src/github.com/docker/libcontainer/devices/defaults.go#L144

Here's some system info:

```
$ docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
 
$  docker info
Containers: 1
Images: 410
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 412
Execution Driver: native-0.2
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 7.681 GiB
Name: kohlenstoff
ID: A2Z5:S5HC:B3ZL:AI4R:TSKW:3HTP:5K4D:22GZ:BTZL:AV4T:ZA73:BRKO
WARNING: No swap limit support
```

### PR DESCRIPTION
**Pull request by davidrjenni**
Fixes #10184.
Merge user specified devices correctly with default devices.
Otherwise the user specified devices end up without permissions.

Signed-off-by: David R. Jenni david.r.jenni@gmail.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @timthelion @cpuguy83 @calavera

**Comment by calavera** [comment]
code LGTM. @davidrjenni do you think it would be possible to provide a test case to avoid future regressions?

**Comment by calavera** [comment]
Can we do something like this to merge devices to avoid that On^2 loop?

```go
paths := map[string]*config.Device{}
for _, d := range userDevices {
  paths[d.Path] = d
}

var devs []*config.Device
for _, d := range defaultDevices {
  if _, defined := paths[d.Path]; !defined {
    devs = append(devs, d)
  }
}

return append(devs, userDevices)
```

**Comment by davidrjenni** [comment]
@calavera, sure we can avoid the O(n^2) loop.

Would you leave the first if statement?
```
if len(userSpecifiedDevices) == 0 {
	return defaultDevices
}
```
 I think it covers most of the cases in which we would loop unnecessarily.

Do you think the comments I made in the `mergeDevices` function bring any benefit?
Reading them now, I'm in favor of removing them. 

Regarding the tests: in which file should I put the tests?
I guess the test file should only build if `GOOS=linux` (because of the `// +build linux` in `container_linux.go`).
So should I put the tests in a new file, say `container_linux_unit_test.go`, with `// +build linux` on top?

**Comment by calavera** [comment]
> Would you leave the first if statement?

yes, that looks good to me.

> So should I put the tests in a new file, say container_linux_unit_test.go, with // +build linux on top?

yes, that's a good option. You can also write an integration-cli test if you feel more conformable with them.

File: daemon/container_linux.go [hunk 1]
```diff
@@ -306,6 +307,24 @@ func populateCommand(c *Container, env []string) error {
...
+	if len(userSpecifiedDevices) == 0 {
+		return defaultDevices
+	}
+
+	// Only add those default devices, which are not specified by the user.
+	// Otherwise, the user specified devices end up without permissions.
+	var devs []*configs.Device
+	for _, defaultDevice := range defaultDevices {
+		for _, userSpecified := range userSpecifiedDevices {
+			if defaultDevice.Path != userSpecified.Path {
```
Comment (timthelion) [inline daemon/container_linux.go]: I'm confused, but maybe it's because I don't know go. Does this add a copy of each default device for every user specified device which doesn't have the same path as the default device? If so, that would be wrong. But then again, I really don't know golang so...

Comment (davidrjenni) [inline daemon/container_linux.go]: It adds all `defaultDevices` except those which are in `userSpecifiedDevices`. In the last line it adds the `userSpecifiedDevices`.

It merges `defaultDevices` and `userSpecifiedDevices`, but prefers a device in `userSpecifiedDevices` over a device in `defaultDevices`.
Say, there is `{"/dev/fuse", "/dev/null"}`in `defaultDevices` and `{"/dev/fuse"}`in `userSpecifiedDevices`, you get `{"/dev/null", "/dev/fuse"}` where `"/dev/fuse"` is taken from `userSpecifiedDevices`.

Does this make sense?

Comment (timthelion) [inline daemon/container_linux.go]: I understand what you are trying to do, but I don't get how your code does this. My python adled brain is reading this as:

````
for defaultDevice in defaultDevices:
  for userSpecified in userSpecifiedDevices:
    if defaultDevice.Path != userSpecified.Path:
      devs = append(devs, defaultDevice)
````

Which would be wrong.

Comment (davidrjenni) [inline daemon/container_linux.go]: Yes, this would be wrong.
But I think if we take the last line of `mergeDevices` into account:
```return append(devs, userSpecifiedDevices...)```
it does what I tried to describe.

**Comment by calavera** [comment]
The new code is correct, although it needs a rebase with master. Thanks for adding the test.

LGTM.

File: daemon/container_linux.go [hunk 2]
```diff
@@ -306,6 +307,25 @@ func populateCommand(c *Container, env []string) error {
...
+		paths[d.Path] = d
+	}
+
+	var devs []*configs.Device
+	for _, d := range defaultDevices {
+		if _, defined := paths[d.Path]; !defined {
+			devs = append(devs, d)
+		}
+	}
+	return append(devs, userDevices...)
```
Comment (timthelion) [inline daemon/container_linux.go]: I think that the current code is clear and correct. Did it occure to you to do it the other way around and write first the default devices into the map and then overwrite the map using the userDevices?

````
paths := map[string]*configs.Device{}
// First add the default devices to the path map.
for _, d := range defaultDevices {
 paths[d.Path] = d
}
//Then over-ride those defaults when necessary.
for _, d := range userDevices {
 paths[d.Path] = d
}
var devs []*configs.Device
for _, d := range paths {
  devs = append(devs,d)
}
return devs
````

I'm actually not sure if this works in golang, it's the pythonic way of doing this though.

Comment (calavera) [inline daemon/container_linux.go]: it should work too, I don't think a third loop provides any additional value though. I only wanted to get rid of that O(n^2) :smile:

**Comment by calavera** [comment]
LGTM

**Comment by calavera** [comment]
@jfrazelle I think it would be good to have this in the release, and it's just a LGTM away from merging :smile:

File: integration-cli/docker_cli_daemon_test.go [hunk 3]
```diff
@@ -1165,3 +1165,18 @@ func (s *DockerDaemonSuite) TestRunContainerWithBridgeNone(c *check.C) {
 	c.Assert(strings.Contains(out, "eth0"), check.Equals, false,
 		check.Commentf("There shouldn't be eth0 in container when network is disabled: %s", out))
 }
+
+// Issue #10184.
+func (s *DockerDaemonSuite) TestDevicePermissions(c *check.C) {
```
Comment (cpuguy83) [inline integration-cli/docker_cli_daemon_test.go]: This shouldn't be a daemon test.

**Comment by cpuguy83** [comment]
Just need to move the test from the `DockerDaemonSuite` the normal `DockerSuite`, and put it in `integration-cli/docker_cli_run_test.go`

**Comment by cpuguy83** [comment]
Otherwise LGTM

File: integration-cli/docker_cli_run_test.go [hunk 4]
```diff
@@ -3191,3 +3191,18 @@ func (s *DockerSuite) TestRunPublishPort(c *check.C) {
 		c.Fatalf("run without --publish-all should not publish port, out should be nil, but got: %s", out)
 	}
 }
+
+// Issue #10184.
+func (s *DockerDaemonSuite) TestDevicePermissions(c *check.C) {
+	const permissions = "crw-rw-rw-"
+	if err := s.d.StartWithBusybox(); err != nil {
```
Comment (cpuguy83) [inline integration-cli/docker_cli_run_test.go]: drop this

File: integration-cli/docker_cli_run_test.go [hunk 5]
```diff
@@ -3191,3 +3191,18 @@ func (s *DockerSuite) TestRunPublishPort(c *check.C) {
...
+		c.Fatalf("could not start daemon with busybox: %v", err)
+	}
+	out, err := s.d.Cmd("run", "--device", "/dev/fuse:/dev/fuse:mrw", "busybox:latest", "ls", "-l", "/dev/fuse")
```
Comment (cpuguy83) [inline integration-cli/docker_cli_run_test.go]: change this to `out, err := dockerCmd(c, "run", "--device", "/dev/fuse:/dev/fuse:mrw", "busybox", "ls", "-l", "/dev/fuse")`

**Comment by cpuguy83** [comment]
LGTM with the new test, thanks!

**Comment by thaJeztah** [comment]
ping @calavera @jfrazelle for one more look and cherry-pick for 1.7

**Comment by calavera** [comment]
Merging! thank you!

**Comment by jfrazelle** [comment]
cherry-picked

**Comment by calavera** [comment]
:metal:

**Comment by davidrjenni** [comment]
Thank you all for reviewing.
