### PR TITLE
Fix concurrent map access in bytespipe

### LINKED ISSUE #22612: Test integration cli daemon sometimes dies while running tests
Opening this because it may not be a power specific issue, but on ppc64le sometimes the docker daemon gets killed while running the integration tests. As seen here :

https://jenkins.dockerproject.org/job/Docker%20Master%20(powerpc)/136/console

```sh
PASS: docker_cli_run_test.go:2021: DockerSuite.TestRunSetMacAddress	0.573s
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

Cannot connect to the Docker daemon. Is the docker daemon running on this host?


----------------------------------------------------------------------
FAIL: docker_cli_run_test.go:2285: DockerSuite.TestRunSlowStdoutConsumer

docker_cli_run_test.go:2306:
     c.Fatalf("Expected %d, got %d", expected, n)
 ... Error: Expected 4096000, got 1179648

Cannot connect to the Docker daemon. Is the docker daemon running on this host?

Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```
and it continues like this until the end.

It only fails during TestRunSlowStdoutConsumer, and furthermore only during a full integration-cli run. It passes if running the specific suite or test. 

Some interesting info from the docker.log:
```sh
time="2016-05-09T15:49:27.971217000Z" level=debug msg="received containerd event: &types.Event{Type:\"start-container\", Id:\"7b7864c0e7998c1585eb0d85b17dfb06c5641badbf6be618e60fab70c717d944\", Status:0x0, Pid:\"\", Timestamp:0x5730b187}"
fatal error: concurrent map read and map write
```

### PR DESCRIPTION
**Pull request by cpuguy83**
When getting and returning a buffer, need to make sure to synchronize
access to the pools map.

Fixes #22612

### CODE REVIEW

**Comment by tophj-ibm** [comment]
thanks! appears to have solved the issue for me

**Comment by LK4D4** [comment]
LGTM

File: pkg/ioutils/bytespipe.go [hunk 1]
```diff
@@ -164,17 +165,21 @@ func (bp *BytesPipe) Read(p []byte) (n int, err error) {
...
 	if pool != nil {
 		pool.Put(b)
 	}
 }
 
 func getBuffer(size int) *fixedBuffer {
+	bufPoolsLock.Lock()
 	pool, ok := bufPools[size]
 	if !ok {
 		pool = &sync.Pool{New: func() interface{} { return &fixedBuffer{buf: make([]byte, 0, size)} }}
```
Comment (anusha-ragunathan) [inline pkg/ioutils/bytespipe.go]: Returning without Unlock.

Comment (cpuguy83) [inline pkg/ioutils/bytespipe.go]: hmm? that's the func used by the Pool.

Comment (anusha-ragunathan) [inline pkg/ioutils/bytespipe.go]: You're right! LGTM.

**Comment by runcom** [comment]
LGTM
