### PR TITLE
Fix the pull events test to use v2 local server

### LINKED ISSUE #10964: [integration-cli] [--net none] Fix TestEventsImagePull
Fix TestEventsImagePull so it will still be a functional test, but will pass when the test container has --net none.

Use the local registry in the container to pull an image.

Error output when tests are run with --net none:

```
--- FAIL: TestEventsImagePull (0.13s)
	docker_cli_events_test.go:188: pulling the hello-world image from has failed: Pulling repository hello-world
		time="2015-02-11T23:19:05Z" level="fatal" msg="Get https://index.docker.io/v1/repositories/library/hello-world/images: dial tcp: lookup index.docker.io on 8.8.8.8:53: dial udp 8.8.8.8:53: network is unreachable" 
		, exit status 1
```

### PR DESCRIPTION
**Pull request by brahmaroutu**
Closes #10964
Signed-off-by: Srini Brahmaroutu srbrahma@us.ibm.com

### CODE REVIEW

File: integration-cli/docker_cli_events_test.go [hunk 1]
```diff
@@ -146,9 +146,21 @@ func TestEventsImageUntagDelete(t *testing.T) {
...
+	defer setupRegistry(t)()
+	repoName := fmt.Sprintf("%v/dockercli/hello-world", privateRegistryURL)
+	defer deleteImages(repoName)
 
-	pullCmd := exec.Command(dockerBinary, "pull", "hello-world")
+	repo := fmt.Sprintf("%v:%v", repoName, "latest")
+	if out, _, err := runCommandWithOutput(exec.Command(dockerBinary, "tag", "busybox", repo)); err != nil {
+		t.Fatalf("Failed to tag image %v: error %v, output %q", repo, err, out)
+	}
+	defer deleteImages(repo)
```
Comment (ahmetalpbalkan) [inline integration-cli/docker_cli_events_test.go]: doesn't `deleteImages(repoName)` also cover `deleteImages(repo)`?
shouldn't the `"repo:tag"` be using variable name `image` instead of `repo`?

File: integration-cli/docker_cli_events_test.go [hunk 2]
```diff
@@ -146,9 +146,21 @@ func TestEventsImageUntagDelete(t *testing.T) {
...
+
+	if out, err := exec.Command(dockerBinary, "push", repo).CombinedOutput(); err != nil {
```
Comment (ahmetalpbalkan) [inline integration-cli/docker_cli_events_test.go]: why not `runCommandWithOutput` here?

File: integration-cli/docker_cli_events_test.go (hunk 1 above)
Comment (brahmaroutu) [inline integration-cli/docker_cli_events_test.go]: @ahmetalpbalkan we are deleting two different tags

File: integration-cli/docker_cli_events_test.go (hunk 2 above)
Comment (brahmaroutu) [inline integration-cli/docker_cli_events_test.go]: @ahmetalpbalkan Changed as per review.

File: integration-cli/docker_cli_events_test.go (hunk 1 above)
Comment (ahmetalpbalkan) [inline integration-cli/docker_cli_events_test.go]: I see, it's just variable names `repoName` vs `repo` sounded a bit same.

**Comment by ahmetalpbalkan** [comment]
There's an outstanding PR to skip tests requiring registry-v2 #11005. By converting these tests to use same-host local registry, we're losing our coverage here. Perhaps we should have 2 version of those *pull* tests:

- if running in-container: spin up registry-v2 instance, pull from there
- if running outside container (cli CIs for example): pull from docker hub online.

based on the situation, test can be smart enough to figure which one to do. wdyt @jfrazelle @tianon

File: integration-cli/docker_cli_events_test.go (hunk 1 above)
Comment (dmcgowan) [inline integration-cli/docker_cli_events_test.go]: The only tag I see being created is "<privateregistry>/dockercli/hello-world:latest".  After push an "rmi" should be called to ensure the pull actually pulls the content from the registry.  See the test pull aliases in the pull cli tests.

File: integration-cli/docker_cli_events_test.go [hunk 3]
```diff
@@ -146,9 +146,21 @@ func TestEventsImageUntagDelete(t *testing.T) {
 func TestEventsImagePull(t *testing.T) {
 	since := time.Now().Unix()
 
-	defer deleteImages("hello-world")
+	defer setupRegistry(t)()
+	repoName := fmt.Sprintf("%v/dockercli/hello-world", privateRegistryURL)
```
Comment (dmcgowan) [inline integration-cli/docker_cli_events_test.go]: This can be updated to be named busybox since it is actually a busybox image. "hello-world" is only used when pulling from the registry because it is a very small image.

**Comment by brahmaroutu** [comment]
@dmcgowan Thanks for the review. On second thoughts I want to change this PR to skip the network based test and add the new test instead. Please see that this PR is related to my other two PRs #11048 and #11264

File: integration-cli/requirements.go [hunk 4]
```diff
@@ -88,3 +96,14 @@ func testRequires(t *testing.T, requirements ...TestRequirement) {
 		}
 	}
 }
+
+// testRequires checks if the environment satisfies the requirements
+// for the test to run or skips the tests.
+func testRequiresWithLog(t *testing.T, msg string, requirements ...TestRequirement) {
```
Comment (LK4D4) [inline integration-cli/requirements.go]: This kinda weird that we using this only for one test.

Comment (ahmetalpbalkan) [inline integration-cli/requirements.go]: @LK4D4 more discussion about this is here: https://github.com/docker/docker/pull/11048#discussion_r26081777

**Comment by dmcgowan** [comment]
Waiting for #11264 to be merged, then this PR should be rebased.

**Comment by brahmaroutu** [comment]
@dmcgowan I will wait until #11264 is merged as that already got 2 LGTMs. Thanks.

File: integration-cli/docker_cli_events_test.go (hunk 1 above)
Comment (dmcgowan) [inline integration-cli/docker_cli_events_test.go]: This `defer deleteImages(repo)` should be moved to the line after `repo` is created and `defer deleteImages(repoName)` can be removed.  `repoName` does not represent an image or tag and therefore does not need to be explicitly deleted, `repo` represents the tagged image to be removed.

**Comment by dmcgowan** [comment]
LGTM

**Comment by dmp42** [comment]
LGTM
