### PR TITLE
image/cache: Ignore Build and Revision on Windows

### LINKED ISSUE #47307: Docker build cache broken after v24.0.7 when building "ltsc2019/1809" Windows container images on Windows 11
### Description

Docker Desktop 4.27.x was release which now comes with Docker Engine v25.0.2, previous version 4.26.1 came with Docker Engine v24.0.7.

Using Docker Engine v25.0.2 to build images based on ltsc2019/1809 Windows container images breaking the build cache and nothing is cache or it is never used.

### Reproduce

Using this Dockerfile:

```Dockerfile
FROM mcr.microsoft.com/windows/nanoserver:ltsc2022

RUN echo "hello"
```

run `docker image build .` and you get expected first build output:

```
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM mcr.microsoft.com/windows/nanoserver:ltsc2022
 ---> e2547c7dd84d
Step 2/2 : RUN echo "hello"
 ---> Running in 7e39ef7bbc05
"hello"
 ---> Removed intermediate container 7e39ef7bbc05
 ---> b8baf9fb556c
 ```

run `docker image build .` again and you get expected build output where the `RUN` statement is cached:

```
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM mcr.microsoft.com/windows/nanoserver:ltsc2022
 ---> e2547c7dd84d
Step 2/2 : RUN echo "hello"
 ---> Using cache
 ---> b8baf9fb556c
Successfully built b8baf9fb556c
```

Now change the image to use `ltsc2019`:

```Dockerfile
FROM mcr.microsoft.com/windows/nanoserver:ltsc2019

RUN echo "hello"
```

run `docker image build .` and you get expected first build output:

```
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM mcr.microsoft.com/windows/nanoserver:ltsc2019
 ---> 82ef3885248c
Step 2/2 : RUN echo "hello"
 ---> Running in 3c6de6846b97
"hello"
 ---> Removed intermediate container 3c6de6846b97
 ---> f55e40c44f69
Successfully built f55e40c44f69
```

run `docker image build .` yet again and now you can see the `RUN` statement is NOT CACHED:

```
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM mcr.microsoft.com/windows/nanoserver:ltsc2019
 ---> 82ef3885248c
Step 2/2 : RUN echo "hello"
 ---> Running in 3c6de6846b97
"hello"
 ---> Removed intermediate container 3c6de6846b97
 ---> f55e40c44f69
Successfully built f55e40c44f69
```

### Expected behavior

Building ltsc2019/1809 images should use the build cache as it did before on v24.0.7.

### docker version

```bash
failed to get console mode for stdout: The handle is invalid.
Client:
 Cloud integration: v1.0.35+desktop.10
 Version:           25.0.2
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        29cf629
 Built:             Thu Feb  1 00:24:09 2024
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.27.1 (136059)
 Engine:
  Version:          25.0.2
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       fce6e0c
  Built:            Thu Feb  1 00:23:01 2024
  OS/Arch:          windows/amd64
  Experimental:     false
```

### docker info

```bash
failed to get console mode for stdout: The handle is invalid.
Client:
 Version:    25.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.3-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.22
    Path:     C:\Program Files\Docker\cli-plugins\docker-debug.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.3.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 970
 Server Version: 25.0.2
 Storage Driver: windowsfilter
  Windows: 
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 22631 (22621.1.amd64fre.ni_release.220506-1250)
 Operating System: Microsoft Windows Version 23H2 (OS Build 22631.3085)
 OSType: windows
 Architecture: x86_64
 CPUs: 24
 Total Memory: 63.91GiB
 Name: amd
 ID: d27c76ac-01ee-4ca5-b776-e0a90411f084
 Docker Root Dir: D:\Data\Docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by vvoland**
- fixes: https://github.com/moby/moby/issues/47307

The compatibility depends on whether `hyperv` or `process` container isolation is used.
This fixes cache not being used when building images based on older Windows versions on a newer Windows host.

**- How to verify it**

**- Description for the changelog**
```release-note
- Windows: Fix cache not being used when building images based on Windows versions older than the host's version
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: image/cache/compare.go [hunk 1]
```diff
@@ -10,6 +14,29 @@ func CompareConfig(a, b *container.Config) bool {
...
+func comparePlatform(builderPlatform, imagePlatform ocispec.Platform) bool {
+	// On Windows, only check the Major and Minor versions.
+	// The Build and Revision compatibility depends on whether `process` or
+	// `hyperv` isolation used.
+	//
+	// Fixes https://github.com/moby/moby/issues/47307
+	if builderPlatform.OS == "windows" && imagePlatform.OS == builderPlatform.OS {
+		// OSVersion format is:
+		// Major.Minor.Build.Revision
+		builderParts := strings.Split(builderPlatform.OSVersion, ".")
```
Comment (thaJeztah) [inline image/cache/compare.go:26]: Interesting; I thought https://github.com/microsoft/hcsshim/tree/main/osversion would have a utility for this, but it doesn't. Perhaps we should contribute one (not urgent for sure!)

Curious; do we know what isolation (hyper-v / host) is used, and if so, if we can ignore os-version altogether?

Comment (vvoland) [reply image/cache/compare.go:26]: There's one in containerd/platforms: https://github.com/containerd/containerd/blob/88fd474e4c0a3dd3865dfcbf0ca99fff12f5c7b7/platforms/defaults_windows.go#L67-L82

but it's in `_windows.go` file so we'd have to split the implementation into Windows and non-Windows, which would make it only testable on Windows and IMO that's too much fuss for a glorified `strings.Split` call 😅

Comment (vvoland) [reply image/cache/compare.go:26]: In general hyperv is the default, but even then, I'm not sure if it's okay to ignore Major/Minor versions. AFAIK there are no other images than `10.0` as of now, so can't test it.

We can always remove that check later, while the reverse might be more problematic.

Comment (thaJeztah) [reply image/cache/compare.go:26]: > but it's in _windows.go file so we'd have to split the implementation into Windows and non-Windows,

Yeah, perhaps we should have a look at that, and discuss with the Microsoft maintainers. Agreed that it's mostly a `strings.Split`, but ideally there would be a (cross-platform) utility here. There's been too many oh-so-subtle things over the Years in this area, which really wants me to have a canonical source of truth for handling anything in this area.

> In general hyperv is the default

On moby/moby it is. I think for containerd it may be the reverse (which should likely not be an issue for this PR, but something we need to keep in the back of our head).

I honestly don't know the compatibility matrix for Hyper-V. ISTR there were some constraints there as well (which could even be "lower versions, or compatible only"), but ... nope... really don't know.

> We can always remove that check later, while the reverse might be more problematic.

Yes, agreed; not a blocker for me!

Comment (vvoland) [reply image/cache/compare.go:26]: Opened https://github.com/microsoft/hcsshim/pull/2019

**Review by thaJeztah — APPROVED** [review]
LGTM

(sorry, thought I already LGTM'd 🙈)
