### PR TITLE
do not create init-dir if not needed

### LINKED ISSUE #29833: Error response from daemon: linux init cgroups path: mkdir /init.scope: read-only file system
**Description**

docker run fails to start the container

**Steps to reproduce the issue:**
1. use `docker run --rm armhf/hello-world`

**Describe the results you received:**

```
docker: Error response from daemon: linux init cgroups path: mkdir /init.scope: read-only file system.
```

**Describe the results you expected:**

for the container to be run successfully

**Additional information you deem important (e.g. issue happens only occasionally):**

I think the error is a red herring. I'm not sure how else to debug. starting docker daemon in debug mode doesn't yield anything else. I'm not sure if it is a kernel issue or a docker issue.

I am testing docker 1.13 on LibreELEC. LibreELEC uses a squashfs, read-only file system, however, everything works fine with 1.12

dockerd is run via

```
/storage/.kodi/addons/service.system.docker/bin/dockerd --exec-opt native.cgroupdriver=systemd --group=root --graph=/storage/.kodi/userdata/addon_data/service.system.docker/docker --storage-driver=overlay2
```

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc4
 API version:  1.25
 Go version:   go1.7.4
 Git commit:   1.13.0-rc4
 Built:        Mon Jan  2 23:56:09 UTC 2017
 OS/Arch:      linux/arm

Server:
 Version:      1.13.0-rc4
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.4
 Git commit:   1.13.0-rc4
 Built:        Mon Jan  2 23:56:09 UTC 2017
 OS/Arch:      linux/arm
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.13.0-rc4
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862 (expected: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e)
runc version: N/A (expected: 51371867a01c467f08af739783b8beafc154c4d7)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Kernel Version: 4.9.0
Operating System: LibreELEC (community) - Version: devel-20161213102424-r24950-g2c4fd3c
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 735.7 MiB
Name: LibreELEC
ID: YILE:FLLX:VW3C:SJAZ:LZYR:MX2L:6B6B:MRAQ:PFS2:BYBJ:NFI4:AHCY
Docker Root Dir: /storage/.kodi/userdata/addon_data/service.system.docker/docker
Debug Mode (client): true
Debug Mode (server): false
Username: lrusak
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpu shares support
WARNING: No cpuset support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

uname -a
```
Linux LibreELEC 4.9.0 #1 SMP Tue Dec 13 10:24:02 PST 2016 armv7l GNU/Linux
```
Raspberry Pi 2

### PR DESCRIPTION
**Pull request by thaJeztah**
fixes https://github.com/docker/docker/issues/29833

Commit 56f77d5ade945b3b8816a6c8acb328b7c6dce9a7 (https://github.com/docker/docker/pull/23430) added support for cpu-rt-period and cpu-rt-runtime, but always initialized the cgroup path, even if not used.

As a result, containers failed to start on a read-only filesystem.

This patch only creates the cgroup path if one of these options is set.

ping @erikstmartin @mlaventure PTAL. I _think_ this should still do all that's required, but please double check.

### CODE REVIEW

File: daemon/daemon_unix.go [hunk 1]
```diff
@@ -1190,7 +1190,9 @@ func (daemon *Daemon) initCgroupsPath(path string) error {
 		return nil
 	}
 
-	daemon.initCgroupsPath(filepath.Dir(path))
```
Comment (thaJeztah) [inline daemon/daemon_unix.go]: This recursive call confused me; not sure if that was needed, but perhaps I misunderstood :blush:

**Comment by lrusak** [comment]
I can confirm that this fixes #29833

**Comment by thaJeztah** [comment]
Thanks @lrusak! Now we need to check if it still does everything that it needs to do :blush: not too familiar with this part, so I'm awaiting some reviews :smile:

File: daemon/daemon_unix.go (hunk 1 above)
Comment (mlaventure) [inline daemon/daemon_unix.go]: I think the recursion is needed because all of the parents have to have a value `<=` than the targeted one in the path for this to work if I'm not mistaken

Comment (thaJeztah) [inline daemon/daemon_unix.go]: Oh, right, so a cgroup has to be created at every level if it doesn't exist? (I don't think this function actually _checks_ it's values, only creates)

Comment (mlaventure) [inline daemon/daemon_unix.go]: Yes, from what I could gather from the original code.

Also, reading the original PR, the following is in the description:
>You will also need to ensure that the system and all parent cgroups have values set for the period and runtime as this limits what the children can be set to.

Comment (thaJeztah) [inline daemon/daemon_unix.go]: I added back the recursive call, but moved it after the new checks

**Review by mlaventure — APPROVED** [review]
LGTM

`TestSwarmContainerAutoStart` seems to still be flaky unfortunately.

**Review by LK4D4 — APPROVED** [review]
LGTM

**Comment by lrusak** [comment]
Can this go in for 1.13 as a bug fix?

**Comment by thaJeztah** [comment]
We've frozen 1.13.0 rc's to only add critical issues, but if there's a patch release for 1.13, i'll bring this up for consideration
