### PR TITLE
Fix spurious error from "docker load"

### LINKED ISSUE #41829: "docker load" gives error "...not a valid parent for..." on Windows
**Description**

On Windows, `docker load` gives an error when loading a tar file produced by `docker save` on the same machine and OS. So far I've only seen this happen when the tar file contains:
1) An image which is a direct child of windows/nanoserver:1809 or windows/servercore:ltsc2019
2) The parent image: windows/nanoserver:1809 or windows/servercore:ltsc2019

This may affect more base images, the above are the ones I've tried so far.

**Steps to reproduce the issue:**

With the following Dockerfile, on a Windows machine:
```
FROM mcr.microsoft.com/windows/nanoserver:1809
CMD ["cmd", "/C", "echo hello world"]
```
1. Run `docker build -t test-image .`
2. Run `docker save -o images.tar test-image mcr.microsoft.com/windows/nanoserver:1809`
3. Run `docker load -i images.tar`

This is already set up here: https://github.com/rcowsill/test-nanoserver-load. That repo includes a GitHub Actions workflow which builds the image, saves it with the base image and tries to load them back in.

**Describe the results you received:**
The `docker load` command fails with the error message:
```
image sha256:6795354d435f[...] is not a valid parent for sha256:d9a7d88ed5b0[...]
```
(Full logs here: https://github.com/rcowsill/test-nanoserver-load/runs/1586120647)

**Describe the results you expected:**

Images load successfully from the tar file

**Additional information you deem important (e.g. issue happens only occasionally):**

Looking at [the code](https://github.com/moby/moby/blob/b5f863c67e6ffbaadedb94c885c3c50c625e4eb8/image/tarexport/load.go#L401) that produces this error message, it looks like the history for the parent image doesn't match the child image (ignoring the last step). Here are the json files for the two images as output by `docker save`:

[6795354d435f89ae3a76f71e9c4e8e8b29b70a69fefaba2b4d13581e20c19d71.json.txt](https://github.com/moby/moby/files/5721691/6795354d435f89ae3a76f71e9c4e8e8b29b70a69fefaba2b4d13581e20c19d71.json.txt)
[d9a7d88ed5b05d7f39f705b85717eab568e38ba8533211c862a20990fa7a0dac.json.txt](https://github.com/moby/moby/files/5721692/d9a7d88ed5b05d7f39f705b85717eab568e38ba8533211c862a20990fa7a0dac.json.txt)

Notice that the format of the "created" dates in the first history entry is different: `2020-12-03T08:05:47.704+00:00` vs `2020-12-03T08:05:47.704Z`

**Output of `docker version`:**

```
Client: Mirantis Container Runtime
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        0c38b2d
 Built:             11/12/2020 21:33:08
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Mirantis Container Runtime
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       5b5efb2d49
  Built:            11/12/2020 21:31:44
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false
 Plugins:
  cluster: Manage Mirantis Container Cloud clusters (Mirantis Inc., v1.9.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 19.03.13
 Storage Driver: windowsfilter
  Windows: 
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.1637)
 OSType: windows
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7GiB
 Name: fv-az41-664
 ID: 36N4:GU5B:533U:A3DM:WWG7:K7S4:EFNH:HY23:PFOE:NGGL:FS4E:N2LA
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on windows-latest in GitHub Actions

### PR DESCRIPTION
**Pull request by rcowsill**
**- What I did**
Fixed the spurious error "...is not a valid parent for..." when using `docker load`. Closes #41829

**- How I did it**
Added an `Equal` method to History, which normalizes UTC-equivalent times into UTC before comparison. This is used instead of `reflect.DeepEqual` in checkValidParent.

**- How to verify it**
With the following Dockerfile, on a Windows machine:
```
FROM mcr.microsoft.com/windows/nanoserver:1809
CMD ["cmd", "/C", "echo hello world"]
```
1. Run `docker build -t test-image .`
2. Run `docker save -o images.tar test-image mcr.microsoft.com/windows/nanoserver:1809`
3. Run `docker load -i images.tar`

With the patch this should work without giving an "is not a valid parent for" error message in step 3.

**- Description for the changelog**
Fix "is not a valid parent for" error from `docker load`

**- A picture of a cute animal (not mandatory but encouraged)**
🦊

### CODE REVIEW

File: image/image.go [hunk 1]
```diff
@@ -218,6 +219,30 @@ func NewHistory(author, comment, createdBy string, isEmptyLayer bool) History {
 	}
 }
 
+// Equal compares two history structs for equality
+func (h History) Equal(i History) bool {
+	h.normalize()
+	i.normalize()
+
+	return reflect.DeepEqual(h, i)
```
Comment (tonistiigi) [inline image/image.go:227]: Should be cleaner to reset `Created` property and run `h.Created.Equal(i.Created)` for it specifically.

Comment (rcowsill) [reply image/image.go:227]: I considered doing that, but it would mean that 14:00:00+01:00 would equal 16:00:00+03:00, for example.

Since the difference between those times is preserved across Unmarshal/Marshal (unlike "+00:00" vs "Z") I went for this approach.

Comment (thaJeztah) [reply image/image.go:227]: (Thinking out loud); At a quick glance, I'd say that'd be correct 🤔; if we'd treat them as "different", that would mean that setting a different timezone on a server would be considered a different artefact even if the time was actually the same.

Comment (rcowsill) [reply image/image.go:227]: For a valid parent the histories being compared were copied directly from parent to child. The only difference is that the child's copies took an extra round trip through UnmarshalJSON/MarshalJSON. In that case I don't think changing the server TZ can change the result of the comparison.

That said, I'll take another look at Time.Unmarshal to make sure it isn't doing anything unexpected with the current TZ.

Comment (rcowsill) [reply image/image.go:227]: @thaJeztah, here's what I found: 

- The system timezone is read once per execution and cached; the new zone isn't used until the daemon restarts
- There's a quirk in the [unmarshaling of non-local times](https://play.golang.org/p/MnqaDk-7VnL) (doesn't affect checkValidParent as it uses reflect.DeepEqual)

These points don't have any negative impact on this approach or using time.Equal instead.

To clarify, I chose this approach as it only modifies behaviour in the specific case reported in #41829. Using time.Equal would fix that issue too, but it may have knock-on effects such as failing to detect a non-valid parent.

Comment (thaJeztah) [reply image/image.go:227]: Thanks!

> such as failing to detect a non-valid parent.

Let me defer that one to @tonistiigi as he's more familiar with this.

We should consider consistently using UTC for these. I did a very quick check on what variants are used in the code base; looks like many paths already use `.UTC()` or `.Unix()` (which implicitly uses UTC) when reading.

I found one place that didn't use UTC; opened https://github.com/moby/moby/pull/41905 for that.

Comment (rcowsill) [reply image/image.go:227]: @thaJeztah I don't know if this is important, but buildkit uses local times (time.Now()) in the history when making new images. The legacy build system uses time.Now().UTC().

Comment (thaJeztah) [reply image/image.go:227]: Interesting. Wondering if there was a reason for that, or if that was overlooked 🤔. For "internal" use, it probably wouldn't make a difference if `.Equal()` is used, mostly thinking about what will end up in JSON (manifests, local storage), and if _not_ using `.UTC()` would make things less reproducible/consistent. That said; fully "reproducible" is still hard, and may require things like `SOURCE_DATE_EPOCH`

**Comment by thaJeztah** [comment]
s390 and ppc64 failures are unrelated


@tonistiigi PTAL if this looks good to you

**Review by tonistiigi — APPROVED** [review]
SGTM

**Review by cpuguy83 — DISMISSED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM
