### PR TITLE
Fix Windows layer leak when write fails

### LINKED ISSUE #31253: windows: docker system prune not reclaiming expected space
**Description**

I am running a CI process that builds images on a windows 2016 host Virtual Machine. A scheduled job runs every 4 hours to clear up space, but this does not seem to be reclaiming the space that docker is suggesting. The amount reclaimed has been decreasing.

Currently I have a 60Gb virtual machine that is running server core and when I run ```docker system prune -fa``` i get the following output

TYPE                TOTAL               ACTIVE              SIZE                RECLAIMABLE
Images              0                   0                   0 B                 0 B
Containers          0                   0                   0 B                 0 B
Local Volumes       0                   0                   0 B                 0 B

However running a scan of C:\ProgramData\docker I can see that there are many Gb's of files here, especially under windows filter. With a scan in progress, where docker is reporting zero images I currently have:

C:\ProgramData\docker -  20.5Gb - 188398 files - 66838 directories
C:\ProgramData\docker\windowsfilter - 20.4Gb - 145451 files - 66752 directories

If i run ```docker images``` and ```docker ps -a``` these are both empty.

There seems to be a gradual decline in the space that is reclaimed, like dangling images are not being detected and not picked up.

One thing to note is that I am trying to delete all images to free up space; then on my next builds I am pulling in windowsservercore or nanoserver from the build of the images, i am not explicitly pulling windowsservercore or nanoserver. 

**Output of `docker version`:**

```
docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.13.1
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.693.amd64fre.rs1_release.161220-1747)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 3.997 GiB
Name: winch03
ID: 6QNU:V7HZ:D7DG:RTJH:SIQ2:BKRE:WBDD:UHBB:RIVA:3RXB:PI4R:TAX2
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 22
 System Time: 2017-02-22T12:04:10.5920341Z
 EventsListeners: 0
Username: xxxx
Registry: https://index.docker.io/v1/
Labels:
 hosttype=windows
 dc=ashford
 hostrole=dev
Experimental: false
Insecure Registries:
 192.168.xxx.xx:5000
 localhost:5000
 127.0.0.0/8
Live Restore Enabled: false
```

Running windows server 2016 on Hyper-V, fully patched with latest Windows Updates/

**Expected Outcome**
As I am deleting all images I would expect the amount of space reclaimed to be consistent and not reducing over time to a point where very little is reclaimed. It seems like there are dangling or orphaned images that are remaining that are not being detected.

### PR DESCRIPTION
**Pull request by darstahl**
Signed-off-by: Darren Stahl <darst@microsoft.com>

fixes https://github.com/moby/moby/issues/31253

**- What I did**

Fixed a leaked handle that was causing layer deletion to fail when the write of the tar contents failed. This was preventing layer deletion, resulting in a lot of  un-removable layers left on disk.

**- How I did it**

Fixed a leaked handle that occurred when `writeLayerFromTar` failed, as the `hcsshim.LayerWriter` was never closed in this case.

**- How to verify it**

Verified locally during stress tests that were causing leaked layers. I've not leaked a layer in days, where before this fix they were leaking regularily.

**- Description for the changelog**

Fixed a layer leak on Windows.

@johnstep @jhowardmsft

### CODE REVIEW

**Review by johnstep — APPROVED** [review]
LGTM

**Comment by jhowardmsft** [comment]
LGTM. Nice find. (Although nit, I'm not a fan of named return variables)

**Comment by jhowardmsft** [comment]
@carlfischer1 - for backport consideration

**Review by lowenna — APPROVED** [review]

**Comment by darrenstahlmsft** [comment]
@jhowardmsft Agreed, but in cases like this, named return values are the only safe way to prevent variable shadowing causing `err` in the defer to be a different `err` than what is being returned. I think this pattern is the safest way to do this.

File: daemon/graphdriver/windows/windows.go [hunk 1]
```diff
@@ -779,8 +779,8 @@ func writeLayerReexec() {
 }
 
 // writeLayer writes a layer from a tar file.
-func writeLayer(layerData io.Reader, home string, id string, parentLayerPaths ...string) (int64, error) {
-	err := winio.EnableProcessPrivileges([]string{winio.SeBackupPrivilege, winio.SeRestorePrivilege})
+func writeLayer(layerData io.Reader, home string, id string, parentLayerPaths ...string) (size int64, err error) {
+	err = winio.EnableProcessPrivileges([]string{winio.SeBackupPrivilege, winio.SeRestorePrivilege})
```
Comment (thaJeztah) [inline daemon/graphdriver/windows/windows.go]: @jhowardmsft would renaming the `err` output variable to `retErr` address your concerns?

I know we've had cases where the output variable was overlooked, and naming it `retErr` instead of plain `err` makes it a bit more apparent that it's an output variable

Comment (darrenstahlmsft) [reply daemon/graphdriver/windows/windows.go]: I like that change. Changed to use `retErr` to prevent confusion.

**Comment by thaJeztah** [comment]
ping @jhowardmsft @johnstep PTAL if the latest version still LGTY

File: daemon/graphdriver/windows/windows.go [hunk 2]
```diff
@@ -804,17 +804,17 @@ func writeLayer(layerData io.Reader, home string, id string, parentLayerPaths ..
...
-	if err != nil {
-		return 0, err
-	}
-
-	err = w.Close()
-	if err != nil {
-		return 0, err
-	}
+	defer func() {
+		if err2 := w.Close(); err2 != nil {
```
Comment (johnstep) [inline daemon/graphdriver/windows/windows.go]: Does it make sense to rename `err2` to `err` since that no longer conflicts with the return name?

Comment (darrenstahlmsft) [reply daemon/graphdriver/windows/windows.go]: Yep. Done.

**Review by thaJeztah — APPROVED** [review]
LGTM - looks like all comments are addressed (thanks!)

**Comment by mback2k** [comment]
LGTM 👍
