### PR TITLE
Fix for lack of synchronization in daemon/update.go

### LINKED ISSUE #41988: Lack of synchronization. The "Dead" flag must be checked under locked container mutex.
https://github.com/moby/moby/blob/0af8ed47bbf51f796ab22797334f69fda10840e5/daemon/update.go#L54

Because the "Dead" set to "true" under container lock, there is a race in case If the 'update' method will be called concurrently with container removing.

### PR DESCRIPTION
**Pull request by diakovliev**
fixes https://github.com/moby/moby/issues/41988

Signed-off-by: dmytro.iakovliev <dmytro.iakovliev@zodiacsystems.com>

**- What I did**

Reordered operations to fix race.

**- How I did it**

The container state checking has been placed between container.Lock() and container.Unlock(). Added container state checking into the defer handler.

**- How to verify it**

See script to reproduce failing conditions in https://github.com/moby/moby/issues/41988.

**- Description for the changelog**

Fix for lack of syncronization in daemon/update.go.

### CODE REVIEW

File: daemon/update.go [hunk 1]
```diff
@@ -40,22 +40,27 @@ func (daemon *Daemon) update(name string, hostConfig *container.HostConfig) erro
...
-	restoreConfig := false
 	backupHostConfig := *ctr.HostConfig
+
+	restoreConfig := false
 	defer func() {
 		if restoreConfig {
 			ctr.Lock()
-			ctr.HostConfig = &backupHostConfig
-			ctr.CheckpointTo(daemon.containersReplica)
+			if !ctr.RemovalInProgress && !ctr.Dead {
```
Comment (thaJeztah) [inline daemon/update.go:49]: Should this use `restoreConfig` instead? (looks like that variable is for that purpose)

```suggestion
			if restoreConfig {
```

File: daemon/update.go [hunk 2]
```diff
@@ -40,22 +40,27 @@ func (daemon *Daemon) update(name string, hostConfig *container.HostConfig) erro
 		return err
 	}
 
-	restoreConfig := false
 	backupHostConfig := *ctr.HostConfig
+
+	restoreConfig := false
```
Comment (thaJeztah) [inline daemon/update.go:45]: Why was this moved?

Comment (diakovliev) [reply daemon/update.go:45]: This change can be dropped. It just my style - make variables declaration as near as possible to first variable usage.

File: daemon/update.go (hunk 1 above)
Comment (diakovliev) [reply daemon/update.go:49]: No, at least because restoreConfig is set without container lock in line https://github.com/moby/moby/blob/1e1b8bf88ab03bb7dbdfb9b44039b1ba5c0090e1/daemon/update.go#L88.  As a result it possible what the restoreConfig will be true when container is dead and/or container removing will be activated.

Comment (thaJeztah) [reply daemon/update.go:49]: oh 🤦 I see this whole block is already in a `if  restoreConfig {` block. Ignore me

**Review by iurii-ovcharenko — APPROVED** [review]

**Comment by iurii-ovcharenko** [comment]
We experiencing this issue in our organization several times a day.
When could we expect this fix to be merged?

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM
