### PR TITLE
Refix COPY file . after WORKDIR (now always created)

### LINKED ISSUE #27545: Inconsistent Dockerfile behavior between Windows Containers and Linux
**Description**

It appears the Windows Containers behavior of the `COPY` command is slightly different than on Linux when the destination is `.`

**Steps to reproduce the issue:**
1. Get a working Windows Container environment.
2. Create a directory with some files with one of them named `project.json`
3. Add the following Dockerfile to the directory.  Note:  This is a simplified Dockerfile.  In the real usage there are commands in between the COPY commands that don't need to be re-run if the project.json doesn't change.

```
FROM microsoft/nanoserver

WORKDIR app
COPY project.json .
COPY . .
```

**Describe the results you received:**
Output of building is:

```
Sending build context to Docker daemon 6.144 kB
Step 1/4 : FROM microsoft/nanoserver
 ---> 105d76d0f40e
Step 2/4 : WORKDIR app
 ---> Using cache
 ---> 5c0466311dc7
Step 3/4 : COPY project.json .
 ---> Using cache
 ---> 0d4a942fa0c6
Step 4/4 : COPY . .
mkdir \\?\Volume{c0949f92-8c99-11e6-b9a3-adda2ced055a}\app: The system cannot find the path specified.
```

**Describe the results you expected:**
The same Dockerfile with the exception of `FROM debian:jessie` builds and produces the expected results (all files are copied into the app dir) in my Ubuntu environment.

**Additional information you deem important (e.g. issue happens only occasionally):**
There are two ways to get the Dockerfile to work on Windows Containers
1. Add `RUN mkdir c:\app` before the `WORKDIR` command
2. Change the two `COPY` destinations to `./` 

**Output of `docker version`:**

```
Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
Containers: 18
 Running: 1
 Paused: 0
 Stopped: 17
Images: 302
Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.206.amd64fre.rs1_release.160915-0644)
Operating System: Windows Server 2016 Standard Evaluation
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 1.159 GiB
Name: WIN-F6RFOUBH784
ID: R644:EESZ:OP6H:7Z62:UABL:VAFV:7TZC:BIR7:KXD7:ISDG:SP37:FXUY
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard <jhoward@microsoft.com>

Fixes #27545 (again). @duglin @thaJeztah @vieux @cpuguy83 

The fix for the above issue was in #27884, but reverted in https://github.com/docker/docker/pull/28505 as doing a mount/unmount for each container create is prohibitively expensive in terms of performance (as discovered by our performance team). Instead, this extends the interface from the builder back into the daemon so that the mount/unmount in container creation is done (on Windows) in the WORKDIR processing itself. The overall solution should still be in 1.13.

Edit: From comments below. The Linux behaviour has been updated to mirror the new Windows behaviour - WORKDIR in the builder always calls back into the daemon to create the directory rather than deferring it to the next statement.

@swernli @jstarks FYI.

### CODE REVIEW

**Comment by thaJeztah** [comment]
https://github.com/docker/docker/pull/28505 was merged, so this can be rebased

**Comment by thaJeztah** [comment]
@cpuguy83 @vieux up to you if it should be added to 1.13

**Comment by jhowardmsft** [comment]
Rebased

**Comment by thaJeztah** [comment]
@jhowardmsft grmbl, needs another one already 😢

**Comment by jhowardmsft** [comment]
Rebased again...

**Comment by duglin** [comment]
@jhowardmsft I'm not sure I fully understand the issue so let me ask this... right now someone can do `docker run --workdir foo ...` and if `foo` doesn't exist it'll create it. This PR doesn't change that behavior, nor should it, so I'm wondering if the performance issue you're referring to would be seen, and an issue, in this case?

**Comment by jhowardmsft** [comment]
@duglin The performance issue is that with the old fix, every single docker run (which is really a create then a start) calls an extra mount/unmount regardless to setup the working directory in the create. While on Linux, that is a relatively cheap operation (very cheap); on Windows, to mount/unmount the scratchspace and initialize it added (I can't recall the exact figure without going back to email) something IRO 100+ms. That was an unacceptable performance regression in their opinion when everyone is working extremely hard to do everything possible to reduce container start times on Windows. Hence why this alternate fix only performs the mount/unmount in the WORKDIR builder call itself, rather than relying on it being done in a subsequent operation. Does that make sense?

**Comment by duglin** [comment]
ok I think I get it - let me just confirm.... the mount/unmount you're referring to only happens when the "working dir" isn't there in the image. So, in my previous comment when I talked about how specifying `-w` on `docker run` will still expose the performance hit there isn't much you can do about it - but in the case of the build's `WORKDIR` you can.  Do I have that right?

If so, then this looks ok.  One question I have, and its less for you and more for @tiborvass, would it make sense to have the build's `WORKDIR` logic do a `mkdir` even for Linux? This would then make the Windows and Linux flows the same. It might look odd to have different results between the two worlds.

**Comment by jhowardmsft** [comment]
@duglin - yes, you've got it :+1:

**Comment by duglin** [comment]
I suspect @jhowardmsft wants this ASAP so I'll:
LGTM
for now and we can do a follow-on PR if we want to make Linux look the same as Windows.

**Comment by jhowardmsft** [comment]
@tiborvass Any chance of looking at this. Thanks :smile:

File: builder/dockerfile/dispatchers.go [hunk 1]
```diff
@@ -279,12 +280,31 @@ func workdir(b *Builder, args []string, attributes map[string]bool, original str
 		return err
 	}
 
-	// NOTE: You won't find the "mkdir" for the directory in here. Rather we
+	comment := fmt.Sprintf("WORKDIR %v", b.runConfig.WorkingDir)
```
Comment (tiborvass) [inline builder/dockerfile/dispatchers.go]: I know this was this way before, but should probably just be `comment := "WORKDIR " + b.runConfig.WorkingDir`

File: daemon/workdir.go [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+	container, err := daemon.GetContainer(cID)
+	if err != nil {
+		return err
+	}
+	err = daemon.Mount(container)
+	if err != nil {
+		return err
+	}
+	defer daemon.Unmount(container)
+	if err := container.SetupWorkingDirectory(0, 0); err != nil {
```
Comment (tiborvass) [inline daemon/workdir.go]: `return container.SetupWorkingDirectory(0, 0)`

**Comment by tiborvass** [comment]
@jhowardmsft these are just small nits, otherwise LGTM

**Comment by duglin** [comment]
@tiborvass any thoughts on this comment:  https://github.com/docker/docker/pull/28514#issuecomment-261535250  ?

**Comment by tiborvass** [comment]
@duglin From a code perspective it's better to mutualize as much as possible between windows and linux, so I would say yes I'm in favor. However is there anything that could break existing users? I couldn't think of anything.

**Comment by duglin** [comment]
I can't think of anything either and I like the consistency of it.

**Comment by jhowardmsft** [comment]
OK, I'll make the Linux change too.

**Comment by duglin** [comment]
@jhowardmsft thanks!

File: builder/dockerfile/dispatchers.go (hunk 1 above)
Comment (jhowardmsft) [inline builder/dockerfile/dispatchers.go]: Fixed in the forthcoming push with the Linux updates.

File: daemon/workdir.go (hunk 2 above)
Comment (jhowardmsft) [inline daemon/workdir.go]: Will be fixed in the forthcoming update. But I need some more work here to support Linux anyway for the UID/GID mapping calls for UserNS

**Comment by jhowardmsft** [comment]
@duglin @tiborvass Updated to matching behaviour on Linux and Windows, and fixed the nits from the previous review.

**Comment by duglin** [comment]
LGTM if janky is happy

**Comment by jhowardmsft** [comment]
Hmmm. TestCommitChange fails (doesn't run on Windows). Investigating....

**Comment by jhowardmsft** [comment]
@duglin. Fixed. The update to the previous commit is to not call back into the daemon if `b.DisableCommit` is set - it was causing the daemon to panic. In the process, I've also ported `TestCommitChange` to Windows to verify it passes there too (that was the test which was failing on Linux) before the latest update.

File: builder/dockerfile/dispatchers_test.go [hunk 3]
```diff
@@ -256,27 +256,6 @@ func TestOnbuild(t *testing.T) {
 	}
 }
 
-func TestWorkdir(t *testing.T) {
```
Comment (duglin) [inline builder/dockerfile/dispatchers_test.go]: Why was this test removed?

**Comment by duglin** [comment]
looks good, just one question

File: builder/dockerfile/dispatchers_test.go (hunk 3 above)
Comment (jhowardmsft) [inline builder/dockerfile/dispatchers_test.go]: In the previous commit, I skipped the test on Windows as the new path sent us calling through the backend into the daemon which wasn't setup in unit tests. Of course, with the latest fix described above, now that we only callback if the disableCommit flag isn't set, the test can be fully re-instated. So it'll be back in for the next update coming shortly.

**Comment by jhowardmsft** [comment]
Updated to re-instate the unit test after comment from @duglin

**Comment by jhowardmsft** [comment]
@duglin Still looks good? Could you give a final LGTM if so. Thanks. @tiborvass You OK with this too?

**Comment by duglin** [comment]
yup - still LGTM !

**Comment by tiborvass** [comment]
LGTM
