### PR TITLE
Move registry service options to the daemon configuration.

### LINKED ISSUE #21000: registry-mirror doesn't work in docker.conf
Output of `docker version`:

    Client:
     Version:      1.10.2
     API version:  1.22
     Go version:   go1.5.3
     Git commit:   c3959b1
     Built:        Mon Feb 22 21:22:53 2016
     OS/Arch:      linux/amd64

    Server:
     Version:      1.10.2
     API version:  1.22
     Go version:   go1.5.3
     Git commit:   c3959b1
     Built:        Mon Feb 22 21:22:53 2016
     OS/Arch:      linux/amd64

Output of `docker info`:

```
Containers: 8
 Running: 1
 Paused: 0
 Stopped: 7
Images: 12
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 124
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.92 GiB
Name: docker
ID: F4HO:FGVX:NCON:OA7C:SZON:WTYM:4N6A:RYUG:HGIJ:FGUK:YSWI:JXNO
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
(paste your output here)
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):

Fresh Docker install on a Debian VM.

List the steps to reproduce the issue:

1. Put `{"registry-mirror": "http://127.0.0.1:5000"}` in `docker.conf` (and restart daemon).
2. `docker pull i-dont-exist`
3. Note that local mirror is not contacted (it produces no log output).
4. Add `--registry-mirror=http://127.0.0.1:5000` command line argument.
5. Docker complains: `unable to configure the Docker daemon with file /root/docker.conf: the following directives are specified both as a flag and in the configuration file: registry-mirror: (from flag: [http://127.0.0.1:5000/], from file: [http://127.0.0.1:5000/])`
6. Remove line from `docker.conf` and retry.
7. The request now goes to the proxy (log output appears).

Describe the results you received:

The argument form works but the setting in the file doesn't, even though Docker clearly reads it.

Describe the results you expected:

The setting should work the same in either place.

Provide additional info you think is important:

### PR DESCRIPTION
**Pull request by calavera**
This change allows to to set the registry service options in the daemon configuration file.
Fixes #21000.

I moved the options inside `daemon.CommonConfig`, so they're not global anymore.

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by aaronlehmann** [comment]
LGTM

File: docker/daemon_test.go [hunk 1]
```diff
@@ -247,3 +248,42 @@ func TestLoadDaemonConfigWithEmbeddedOptions(t *testing.T) {
 		t.Fatalf("expected LogConfig type syslog, got %v", loadedConfig.LogConfig.Type)
 	}
 }
+
+func TestLoadDaemonConfigWithRegistryOptions(t *testing.T) {
+	c := &daemon.Config{}
+	common := &cli.CommonFlags{}
+	flags := mflag.NewFlagSet("test", mflag.ContinueOnError)
+
+	f, err := ioutil.TempFile("", "docker-config-")
```
Comment (cpuguy83) [inline docker/daemon_test.go]: defer remove

Comment (calavera) [inline docker/daemon_test.go]: fixed

**Comment by cpuguy83** [comment]
LGTM

**Comment by calavera** [comment]
there are no "real" docs changes, I've only added the missing options to the configuration example :grin:

**Comment by thaJeztah** [comment]
LGTM

**Comment by thaJeztah** [comment]
:zzz:

**Comment by avsm** [comment]
One inconsistency here is that the command line option is `--registry-mirror` and the daemon configuration refers to `--registry-mirrors`.
