### PR TITLE
cli: fix images filter when use multi reference filter

### LINKED ISSUE #38164: bug: docker images filter undefined behavior when use multi reference filter
**Description**

As the title desc, add example later.

**Steps to reproduce the issue:**
1.just use `docker images -f reference`
2.
3.

**Describe the results you received:**
```
$ sudo docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
mysql               latest              29e0ae3b69b9        2 months ago        484MB
redis               latest              4e8db158f18d        3 months ago        83.4MB
busybox             latest              e1ddd7948a1c        3 months ago        1.16MB
hello-world         latest              2cb0d9787c4d        4 months ago        1.85kB
busybox             1.28                8c811b4aec35        5 months ago        1.15MB
pouch               test                8c811b4aec35        5 months ago        1.15MB

$ sudo docker images -f reference=mysql:*
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
mysql               latest              29e0ae3b69b9        2 months ago        484MB

// not correct because of this bug
$ sudo docker images -f reference=mysql:* -f reference=redis:*
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE

// not correct because of this bug
$ sudo docker images -f reference=mysql:* -f reference=busybox:*
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
mysql               latest              29e0ae3b69b9        2 months ago        484MB

// not correct because of this bug
$ sudo docker images -f reference=mysql:* -f reference=busybox:* -f reference=hello-world:*
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
mysql               latest              29e0ae3b69b9        2 months ago        484MB
busybox             latest              e1ddd7948a1c        3 months ago        1.16MB
```

**Describe the results you expected:**
As the example show, when use multi reference image filter, didn't show any relationship between multi reference filter.
For example, if we use `docker images -f reference=A -f reference=B`, Then the output is images which match A or B, or match A and B? I didn't see it in current impl.
In my view, I suggest use `or `relationship, as match A reference or B reference filter.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 18.06.1-ce, build e68fc7a
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc runsc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-36-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.23GiB
Name: zhangyue-ThinkPad-W530
ID: PGRR:SGFC:IDKA:SXJM:FVL3:KNVU:DILX:HUXJ:YA7W:HGK7:XCNK:L6IU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by ZYecho**
Signed-off-by: zhangyue <zy675793960@yeah.net>

**- What I did**
fix #38164 , to refuse `docker images -f ` undefined behavior when use multi reference filter.

**- How I did it**
just add a judge statement when filter image ref.

**- How to verify it**
run `docker images`
```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
hello-world         latest              4ab4c602aa5e        2 months ago        1.84kB
img2                test1               4ab4c602aa5e        2 months ago        1.84kB
img                 test1               4ab4c602aa5e        2 months ago        1.84kB
img                 test2               4ab4c602aa5e        2 months ago        1.84kB
```
run `docker images -f reference=img:* -f reference=hello-*`
```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
hello-world         latest              4ab4c602aa5e        2 months ago        1.84kB
img                 test1               4ab4c602aa5e        2 months ago        1.84kB
img                 test2               4ab4c602aa5e        2 months ago        1.84kB
```

run `docker images -f reference=img:* -f reference=hello-* -f reference=img2:*`

```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
hello-world         latest              4ab4c602aa5e        2 months ago        1.84kB
img2                test1               4ab4c602aa5e        2 months ago        1.84kB
img                 test1               4ab4c602aa5e        2 months ago        1.84kB
img                 test2               4ab4c602aa5e        2 months ago        1.84kB
```

**- Description for the changelog**

fix #38164 , to refuse `docker images -f ` undefined behavior when use multi reference filter.

**- A picture of a cute animal (not mandatory but encouraged)**
None.

### CODE REVIEW

**Comment by ZYecho** [comment]
@yongtang @thaJeztah PTAL, thanks.

**Comment by thaJeztah** [comment]
Relates to https://github.com/moby/moby/pull/28477, which implemented this filter


This looks to be consistent with `docker ps` / `docker container ls` and `docker service ls`, which treat multiple `--filter name=...` as an `or` (not an `and`);

Containers

```
docker run -dit --name foobar busybox
docker run -dit --name something busybox

docker container ls --filter name=foobar
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
81ada6c88e9f        busybox             "sh"                     26 seconds ago      Up 25 seconds                           foobar

docker container ls --filter name=foobar --filter name=something 
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS               NAMES
d05e62da1ba4        busybox             "sh"                     51 seconds ago       Up 50 seconds                           something
81ada6c88e9f        busybox             "sh"                     52 seconds ago       Up 51 seconds                           foobar
```

Services


```
docker service create --name foobar nginx:alpine
docker service create --name something nginx:alpine

docker service ls --filter name=foobar
ID                  NAME                MODE                REPLICAS            IMAGE               PORTS
so8i1x1sjdl1        foobar              replicated          1/1                 nginx:alpine        

docker service ls --filter name=foobar --filter name=something
ID                  NAME                MODE                REPLICAS            IMAGE               PORTS
so8i1x1sjdl1        foobar              replicated          1/1                 nginx:alpine        
gcaogsysqvjh        something           replicated          1/1                 nginx:alpine        
```


Some things to change;

- Add a simple test to test for this behavior
- (As a follow-up, because it's in a different repository) update the cli reference documentation (https://github.com/docker/cli/blob/master/docs/reference/commandline/images.md#filter-images-by-reference), and;
  - add an example that shows multiple `--filter reference` filters
  - explain that combining multiple reference filters acts as an "or" (image _either_ has X as a name, _or_ Y as name)


I'd like some more eyes on this change though, because it's a change in behavior, so there's a risk that this breaks people 😓

**Comment by thaJeztah** [comment]
ping @vdemeester PTAL

File: integration-cli/docker_api_images_test.go [hunk 1]
```diff
@@ -206,3 +206,33 @@ func (s *DockerSuite) TestAPIImagesSizeCompatibility(c *check.C) {
 		c.Assert(image.Size, checker.Not(checker.Equals), int64(-1))
 	}
 }
+
+// Regression : #38171
+func (s *DockerSuite) TestAPIImagesFilterMultiReferenceMatch(c *check.C) {
```
Comment (vdemeester) [inline integration-cli/docker_api_images_test.go]: Ideally, those need to be in the `integration` package (`integration-cli` is deprecated — see #32866). That said it's weird that the CI is green (aka this means it doesn't validate correctly this anymore…)

**Review by vdemeester — CHANGES_REQUESTED** [review]
> I'd like some more eyes on this change though, because it's a change in behavior, so there's a risk that this breaks people :sweat: 

That's my concern too, but I think it should be ok — having multiple `--filter=reference=*` makes it pretty useless to have multiple `reference` filter, so I don't think too many people uses that.

File: integration-cli/docker_api_images_test.go (hunk 1 above)
Comment (ZYecho) [reply integration-cli/docker_api_images_test.go]: Thanks for remind me, update.

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Comment by ZYecho** [comment]
@thaJeztah Hi, what's the next step before merge this pr?

**Review by thaJeztah — APPROVED** [review]
no other steps needed, other than a second maintainer reviewing the last code changes (the updated tests)  :smile:

And, those look good to me (thanks!)


LGTM

**Comment by thaJeztah** [comment]
Experimental failure is a known flaky test (see https://github.com/moby/moby/issues/32673);

```
03:34:29 FAIL: docker_api_swarm_test.go:296: DockerSwarmSuite.TestAPISwarmLeaderElection
```

Ignoring that failiure

**Comment by thaJeztah** [comment]
Thanks! And congratulations with your first contribution merged 🎉
