### PR TITLE
#26639: Local NFS volumes do not resolve hostnames

### LINKED ISSUE #26639: Local NFS volumes do not resolve hostnames
**Description**

If you create an NFS volume using the local storage driver, you have to use the IP address of the NFS host.  If you use the host name, your container will fail to start and will return "docker: Error response from daemon: invalid argument."

**Steps to reproduce the issue:**
1. create an NFS server and export a directory
2. create a docker volume using "docker volume create -o type=nfs -o o=addr=my_host,rw -o device=:/exports --name foo"
3. start a container mounting that volume with "docker run -it --rm -v foo:/storage alpine sh"

**Describe the results you received:**

$ docker run -it -v foo:/storage alpine sh
docker: Error response from daemon: invalid argument.

**Describe the results you expected:**

If you use it with an IP address you get:
$ docker run -it -v foo:/storage alpine sh
/ # ls /storage/
docker

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

**Output of `docker info`:**

Containers: 11
 Running: 10
 Paused: 0
 Stopped: 1
Images: 45
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 99
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-22-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 975.1 MiB
Name: clone13
ID: VCBT:FE4P:AA65:W5NF:53RX:7D7U:MECQ:G2IQ:EP23:MVWQ:DCGC:MAA7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Cluster Store: etcd://192.168.36.247:12379
Cluster Advertise: 192.168.36.247:12376
Insecure Registries:
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This is using VMware Fusion.  The NFS server is the standard one packaged with Ubuntu 16.04.

### PR DESCRIPTION
**Pull request by dattatrayakumbhar**
fixes #26639

**\- What I did**
Implemented code for mounting local NFS with hostname
- **How I did it**
  Added method GetAddress, to get address/hostname from options. Added another Method IsIP, to verify if option has IP or Address. If option has hostname then used LookupHost built in function to convert to IPAddress.

**\- How to verify it**
1. Build a developer container with latest docker/master and this PR
2. Start docker daemon with copying binaries with hack/make.sh binary.
3. Create docker volume with "docker volume create -o type=nfs -o o=addr=nfs-server,rw -o device=:/nfsdir --name test4"
  Note. Please make sure “nfs-server” is resolvable with Ip address.
4. Create container with “docker run -it  --rm -v test4:/storage datkumbh/nfs sh”
5. Verify that container created successfully and nfsdir mounted in /storage.

**\- Description for the changelog**
1. Added a GetAddress  method in volume/local/local_unix.go
2. Added a IsIP method in volume/local/local_unix.go to verify if hostname is IP or return blank
3. Added a support to convert hostname to IpAddress if option is wit hostname 

*_\- A picture of a cute animal *_

image

### CODE REVIEW

File: volume/local/local_unix.go [hunk 1]
```diff
@@ -71,6 +68,44 @@ func (v *localVolume) mount() error {
 	if v.opts.MountDevice == "" {
 		return fmt.Errorf("missing device in volume options")
 	}
+	if strings.Contains(v.opts.MountOpts, "addr=") && v.opts.MountOpts != "" && v.opts.MountType != "" {
```
Comment (cpuguy83) [inline volume/local/local_unix.go]: No need for `strings.Contains`, a lookup to `if addr := GetAddress(v.opts.MountOpts); addr != "" { ... }` should suffice.

File: volume/local/local_unix.go [hunk 2]
```diff
@@ -71,6 +68,44 @@ func (v *localVolume) mount() error {
...
+		addrValue := GetAddress(v.opts.MountOpts)
+		if addrValue != "" {
+			if !IsIP(addrValue) {
```
Comment (cpuguy83) [inline volume/local/local_unix.go]: No need for `IsIP`. `net.ResolveIPAddr` will work just fine here if it is a hostname or an IP.

File: volume/local/local_unix.go [hunk 3]
```diff
@@ -71,6 +68,44 @@ func (v *localVolume) mount() error {
...
+		} else {
+			logrus.Debugf("Addr/hostname in option is not configured..IP Address...")
+		}
+	}
 	err := mount.Mount(v.opts.MountDevice, v.path, v.opts.MountType, v.opts.MountOpts)
 	return errors.Wrapf(err, "error while mounting volume with options: %s", v.opts)
 }
+
+// GetAddress finds out address/hostname from options
+func GetAddress(opts string) string {
```
Comment (cpuguy83) [inline volume/local/local_unix.go]: Please don't export this.

File: volume/local/local_unix.go [hunk 4]
```diff
@@ -71,6 +68,44 @@ func (v *localVolume) mount() error {
...
+		if strings.Contains(optsList[i], "addr") {
+			addr := (strings.SplitN(optsList[i], "=", 2)[1])
+			return addr
+		}
+	}
+	return ""
+}
+
+// IsIP verified if option is type of ip
+func IsIP(addr string) bool {
```
Comment (cpuguy83) [inline volume/local/local_unix.go]: function is not needed.

File: volume/local/local_unix.go [hunk 5]
```diff
@@ -7,12 +7,12 @@ package local
 
 import (
 	"fmt"
+	"github.com/Sirupsen/logrus"
+	"github.com/docker/docker/pkg/mount"
+	"net"
 	"path/filepath"
+	"src/github.com/pkg/errors"
```
Comment (cpuguy83) [inline volume/local/local_unix.go]: No `src/`

**Review by cpuguy83 — CHANGES_REQUESTED** [review]
The host lookup should be done before every `mount()` syscall rather than caching addresses.

**Comment by cpuguy83** [comment]
08:35:30 These files are not properly gofmt'd:
08:35:30  - volume/local/local_unix.go

**Review by justincormack — CHANGES_REQUESTED** [review]

File: volume/local/local_unix.go [hunk 6]
```diff
@@ -7,12 +7,13 @@ package local
 
 import (
 	"fmt"
+	//	"github.com/Sirupsen/logrus"
```
Comment (thaJeztah) [inline volume/local/local_unix.go]: Looks like this can be removed instead of commented

File: volume/local/local_unix.go [hunk 7]
```diff
@@ -71,6 +70,30 @@ func (v *localVolume) mount() error {
...
+	r1, _ := regexp.Compile(`\baddr=*`)
+	r2, _ := regexp.Compile(`\bnfs\b`)
+	if r1.MatchString(v.opts.MountOpts) && r2.MatchString(v.opts.MountType) {
+		if addrValue := getAddress(v.opts.MountOpts); addrValue != "" {
+			ipAddr, err := net.ResolveIPAddr("ip", addrValue)
+			if err == nil {
+				v.opts.MountOpts = strings.Replace(v.opts.MountOpts, addrValue, ipAddr.String(), 1)
+			} else {
+				return errors.Wrapf(err, "Unable to resolve hostname")
+			}
```
Comment (thaJeztah) [inline volume/local/local_unix.go]: You can do

```go
if err != nil {
    return errors.Wrapf(err, "unable to resolve hostname"
}
```

So that you don't need an "else".

Perhaps include the actual hostname in the error message, as that may be valuable information

File: volume/local/local_unix.go [hunk 8]
```diff
@@ -71,6 +70,30 @@ func (v *localVolume) mount() error {
 	if v.opts.MountDevice == "" {
 		return fmt.Errorf("missing device in volume options")
 	}
+	r1, _ := regexp.Compile(`\baddr=*`)
+	r2, _ := regexp.Compile(`\bnfs\b`)
+	if r1.MatchString(v.opts.MountOpts) && r2.MatchString(v.opts.MountType) {
```
Comment (thaJeztah) [inline volume/local/local_unix.go]: Do we need a regex here for MountType? Or simply `v.opts.MountType == "nfs"`

Comment (thaJeztah) [inline volume/local/local_unix.go]: Also, given that we'll still check if an addr is actually set below, checking `addr=` may not even be nescessary here (but open to suggestions)

**Review by thaJeztah — CHANGES_REQUESTED** [review]

File: volume/local/local_unix.go [hunk 9]
```diff
@@ -71,6 +70,30 @@ func (v *localVolume) mount() error {
...
+		if addrValue := getAddress(v.opts.MountOpts); addrValue != "" {
+			ipAddr, err := net.ResolveIPAddr("ip", addrValue)
+			if err == nil {
+				v.opts.MountOpts = strings.Replace(v.opts.MountOpts, addrValue, ipAddr.String(), 1)
```
Comment (thaJeztah) [inline volume/local/local_unix.go]: Should we replace the value of `v.opts.MountOps` here, or should we use a copy, and leave the original options as-is? @cpuguy83 ?

Comment (cpuguy83) [inline volume/local/local_unix.go]: Copy please

**Comment by dattatrayakumbhar04** [comment]
Updated PR with changed.Can someone please review it ?

**Comment by dattatrayakumbhar04** [comment]
@thaJeztah @cpuguy83 
Updated PR. Please take a look.

**Review by thaJeztah — APPROVED** [review]
LGTM, but left one suggestion

File: volume/local/local_unix.go [hunk 10]
```diff
@@ -71,6 +69,31 @@ func (v *localVolume) mount() error {
...
+	if r1.MatchString(v.opts.MountOpts) && v.opts.MountType == "nfs" {
+		if addrValue := getAddress(v.opts.MountOpts); addrValue != "" && net.ParseIP(addrValue).To4() == nil {
+			ipAddr, err := net.ResolveIPAddr("ip", addrValue)
+			if err != nil {
+				return errors.Wrapf(err, "Unable to resolve hostname %s", addrValue)
+			}
+			opts1 := v.opts.MountOpts
+			opts1 = strings.Replace(opts1, addrValue, ipAddr.String(), 1)
+			err = mount.Mount(v.opts.MountDevice, v.path, v.opts.MountType, opts1)
+			return errors.Wrapf(err, "error while mounting volume with options: %s", v.opts)
```
Comment (dattatrayakumbhar04) [inline volume/local/local_unix.go]: Thanks @thaJeztah. 
Removed duplication. Updated PR with same detail

**Comment by thaJeztah** [comment]
ping @justincormack PTAL

**Comment by dattatrayakumbhar04** [comment]
@justincormack , Can you please take a look ?

File: volume/local/local_unix.go [hunk 11]
```diff
@@ -71,6 +69,29 @@ func (v *localVolume) mount() error {
 	if v.opts.MountDevice == "" {
 		return fmt.Errorf("missing device in volume options")
 	}
-	err := mount.Mount(v.opts.MountDevice, v.path, v.opts.MountType, v.opts.MountOpts)
+	r1, _ := regexp.Compile(`\baddr=*`)
```
Comment (cpuguy83) [inline volume/local/local_unix.go]: Should be compiled at the package level rather than on every mount call.

But do we really need to match the regex here vs just iterating the opts with `getAddress`?
In most cases the opts list should be small enough to not matter.
WDYT?

Comment (cpuguy83) [inline volume/local/local_unix.go]: Should also always check errors.

File: volume/local/local_unix.go [hunk 12]
```diff
@@ -71,6 +69,29 @@ func (v *localVolume) mount() error {
...
+	mountOpts := v.opts.MountOpts
+	if r1.MatchString(v.opts.MountOpts) && v.opts.MountType == "nfs" {
+		if addrValue := getAddress(v.opts.MountOpts); addrValue != "" && net.ParseIP(addrValue).To4() == nil {
+			ipAddr, err := net.ResolveIPAddr("ip", addrValue)
+			if err != nil {
+				return errors.Wrapf(err, "Unable to resolve hostname %s", addrValue)
```
Comment (cpuguy83) [inline volume/local/local_unix.go]: This wrap message is not really adding any context and just duplicating what is already there since the error from `net` will be `lookup <addrValue>: no such host`.

Maybe something like `error resolving passed in nfs address`.
Also, errors should always be started as lower case.

**Review by cpuguy83 — CHANGES_REQUESTED** [review]

File: volume/local/local_unix.go (hunk 11 above)
Comment (thaJeztah) [inline volume/local/local_unix.go]: Yes, I suggested doing that in https://github.com/docker/docker/pull/27329#discussion_r83539559, perhaps we should skip the regex (since `getAddress` is checking for it anyway to verify it's not empty)

Comment (dattatrayakumbhar04) [inline volume/local/local_unix.go]: Yes I think It can be in getAddress function ,Will remove it.

File: volume/local/local_unix.go (hunk 12 above)
Comment (dattatrayakumbhar04) [inline volume/local/local_unix.go]: changed error message

**Comment by thaJeztah** [comment]
ping @cpuguy83 PTAL

@dattatrayakumbhar04 can you squash your commits?

File: volume/local/local_test.go [hunk 13]
```diff
@@ -12,6 +12,22 @@ import (
...
 
+func TestGetAddress(t *testing.T) {
+	cases := map[string]string{
+		"addr=11.11.11.1":   "11.11.11.1",
+		" ":                 "",
+		"addr=":             "",
+		"addr=2001:db8::68": "2001:db8::68",
+	}
+	for name, success := range cases {
+		v := getAddress(name)
```
Comment (cpuguy83) [inline volume/local/local_test.go]: `getAddress` is only defined for linux, but not for Windows.
Can probably move to a platform independent file.

**Comment by dattatrayakumbhar04** [comment]
Updated PR and all checks are passed now.

**Review by cpuguy83 — APPROVED** [review]
LGTM

File: volume/local/local_unix.go [hunk 14]
```diff
@@ -71,6 +70,16 @@ func (v *localVolume) mount() error {
...
 	}
-	err := mount.Mount(v.opts.MountDevice, v.path, v.opts.MountType, v.opts.MountOpts)
+	mountOpts := v.opts.MountOpts
+	if v.opts.MountType == "nfs" {
+		if addrValue := getAddress(v.opts.MountOpts); addrValue != "" && net.ParseIP(addrValue).To4() == nil {
+			ipAddr, err := net.ResolveIPAddr("ip", addrValue)
+			if err != nil {
+				return errors.Wrapf(err, "error resolving passed in nfs address")
+			}
+			mountOpts = strings.Replace(mountOpts, addrValue, ipAddr.String(), 1)
```
Comment (thaJeztah) [inline volume/local/local_unix.go]: should we replace, including the `addr=`? Is there a change another option has the same string?

Comment (thaJeztah) [inline volume/local/local_unix.go]: e.g.

```go
mountOpts = strings.Replace(mountOpts, "addr=" + addrValue, "addr=" + ipAddr.String(), 1)
```

(maybe not needed, just wondering)

Comment (cpuguy83) [inline volume/local/local_unix.go]: Good idea

**Comment by dattatrayakumbhar04** [comment]
@cpuguy83 @thaJeztah @justincormack 
Updated PR with changes.

**Review by thaJeztah — APPROVED** [review]
LGTM

File: volume/local/local.go [hunk 15]
```diff
@@ -349,3 +350,15 @@ func validateOpts(opts map[string]string) error {
 func (v *localVolume) Status() map[string]interface{} {
 	return nil
 }
+
+// getAddress finds out address/hostname from options
+func getAddress(opts string) string {
+	optsList := strings.Split(opts, ",")
+	for i := 0; i < len(optsList); i++ {
+		if strings.Contains(optsList[i], "addr=") {
```
Comment (justincormack) [inline volume/local/local.go]: This needs to check for `addr=` at the start of the item.

File: volume/local/local_unix.go [hunk 16]
```diff
@@ -50,15 +51,13 @@ func (r *Root) scopedPath(realPath string) bool {
 
 	return false
 }
-
```
Comment (justincormack) [inline volume/local/local_unix.go]: please avoid unrelated whitespace changes

File: volume/local/local_unix.go [hunk 17]
```diff
@@ -50,15 +51,13 @@ func (r *Root) scopedPath(realPath string) bool {
...
 func setOpts(v *localVolume, opts map[string]string) error {
 	if len(opts) == 0 {
 		return nil
 	}
 	if err := validateOpts(opts); err != nil {
 		return err
 	}
-
```
Comment (justincormack) [inline volume/local/local_unix.go]: and here

**Review by justincormack — CHANGES_REQUESTED** [review]

File: volume/local/local_unix.go (hunk 17 above)
Comment (dattatrayakumbhar04) [inline volume/local/local_unix.go]: @justincormack 
I have made changes PTAL

**Review by justincormack — APPROVED** [review]

**Comment by justincormack** [comment]
LGTM from under the sea!
