### PR TITLE
remove btrfs subvolumes when destroying containers (recursive)

### LINKED ISSUE #9399: Docker daemon failing to push (trying to write 8.8.8.8:53?)
I'm trying to push a number of images like this: 

    docker images | grep ^hamiltont/tf | awk '{print $1}' | xargs docker --debug=true push

And I get this output

```
The push refers to a repository [hamiltont/tfb-python-falcon] (len: 1)
Sending image list
Pushing repository hamiltont/tfb-python-falcon (1 tags)
511136ea3c5a: Pushing
2014/11/28 11:21:09 Failed to upload metadata: Put https://cdn-registry-1.docker.io/v1/images/511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158/json: dial tcp: write udp 8.8.8.8:53: operation not permitted
```

My setup:

    DOCKER_OPTS="--exec-driver=lxc -H=unix:///var/run/docker.sock -H=0.0.0.0:4243"

and
```
root@3:/home/hamiltont# docker info
Containers: 1813
Images: 323
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 3949
Execution Driver: lxc-1.0.6
Kernel Version: 3.13.0-39-generic
Operating System: Ubuntu 14.04.1 LTS
Username: hamiltont
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support
root@3:/home/hamiltont# docker version
Client version: 1.2.0
Client API version: 1.14
Go version (client): go1.3.1
Git commit (client): fa7b24f
OS/Arch (client): linux/amd64
Server version: 1.2.0
Server API version: 1.14
Go version (server): go1.3.1
Git commit (server): fa7b24f
```

### LINKED ISSUE #9939: docker does not remove btrfs subvolumes when destroying container
I receive the following error when deleting a container which created a btrfs subvolume (as happens when you run docker in docker).

```
# docker run --rm fedora:20 sh -c 'yum -y -q install btrfs-progs && btrfs subvolume create /test'
Public key for lzo-2.08-1.fc20.x86_64.rpm is not installed
Public key for e2fsprogs-libs-1.42.8-3.fc20.x86_64.rpm is not installed
Importing GPG key 0x246110C1:
 Userid     : "Fedora (20) <fedora@fedoraproject.org>"
 Fingerprint: c7c9 a9c8 9153 f201 83ce 7cba 2eb1 61fa 2461 10c1
 Package    : fedora-release-20-3.noarch (@fedora-updates/$releasever)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-20-x86_64
Create subvolume '//test'
FATA[0033] Error response from daemon: Cannot destroy container c9badf5fc87bb9bfb50a3ee6e5e7c840476bd704e62404c9136aab4d27239d1e: Driver btrfs failed to remove root filesystem c9badf5fc87bb9bfb50a3ee6e5e7c840476bd704e62404c9136aab4d27239d1e: Failed to destroy btrfs snapshot: directory not empty 
```

Info:

```
# docker info
docContainers: 22
Images: 47
Storage Driver: btrfs
Execution Driver: native-0.2
Kernel Version: 3.13.2-gentoo
Operating System: Gentoo/Linux
CPUs: 8
Total Memory: 15.64 GiB
Name: whistler
ID: RL3I:O6RS:UJRN:UU74:WAGE:4X5B:T2ZU:ZRSU:BN6Q:WN7L:QTPM:VCLN
Username: phemmer
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support

# docker version
Client API version: 1.16
Go version (client): go1.3.3
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
```

### PR DESCRIPTION
**Pull request by jessfraz**
carry of #15355 

close #15355 
fix #9939

### CODE REVIEW

**Comment by jfrazelle** [comment]
previously btrfs tested on btrfs would fail because of this, so a fast way to check this is fixed is running the integration-cli tests for btrfs on btrfs

seen here; https://jenkins.dockerproject.org/job/Docker%20Master%20(btrfs%20on%20btrfs)/1/consoleFull

File: daemon/graphdriver/btrfs/btrfs.go [hunk 1]
```diff
@@ -6,6 +6,7 @@ package btrfs
 #include <stdlib.h>
 #include <dirent.h>
 #include <btrfs/ioctl.h>
+#include <btrfs/ctree.h>
```
Comment (tianon) [inline daemon/graphdriver/btrfs/btrfs.go]: We probably want to run this at least through a compile test on all our deb/rpm target platforms to make sure this header is available too.  (Isn't there a different Jenkins job that can test that now, too?)

Comment (jfrazelle) [inline daemon/graphdriver/btrfs/btrfs.go]: I don't even know if we need that I ended up cleaning up a bunch of the code in a second commit, but will def check ;)

Comment (tianon) [inline daemon/graphdriver/btrfs/btrfs.go]: :metal:

**Comment by calavera** [comment]
LGTM

**Comment by jfrazelle** [comment]
Hang on gotta do more testing jic ;) but I think we are almost there






On Tue, Aug 25, 2015 at 1:00 AM -0700, "David Calavera" <notifications@github.com> wrote:












LGTM

**Comment by jfrazelle** [comment]
ok so the btrfs header breaks the wheezy deb, looking into it..

**Comment by jfrazelle** [comment]
ok so fixed the debs, and ready!

File: contrib/builder/deb/generate.sh [hunk 2]
```diff
@@ -73,6 +73,13 @@ for version in "${versions[@]}"; do
 		extraBuildTags+=' exclude_graphdriver_btrfs'
 	fi
 
+	# make backports the default for installing packages
+	if [ "$suite" = 'wheezy' ]; then
+		#   remove btrfs-tools so we can readd it and pull from backports
+		packages=( "${packages[@]/btrfs-tools}" )
+		packages+=('--no-install-recommends && apt-get install -y -t wheezy-backports btrfs-tools')
```
Comment (tianon) [inline contrib/builder/deb/generate.sh]: Wouldn't this work as `btrfs-tools/wheezy-backports`?  ie, something like:
```bash
backports="/$suite-backports"
packages=( "${packages[@]/btrfs-tools/btrfs-tools$backports}" )
```

```console
$ docker run -it --rm debian:wheezy-backports
root@243f36b637b1:/# apt-get update -qq
root@243f36b637b1:/# apt-get install -V btrfs-tools/wheezy-backports
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Selected version '3.17-1.1~bpo70+1' (Debian Backports:/wheezy-backports [amd64]) for 'btrfs-tools'
The following extra packages will be installed:
   liblzo2-2 (2.06-1+deb7u1)
The following NEW packages will be installed:
   btrfs-tools (3.17-1.1~bpo70+1)
   liblzo2-2 (2.06-1+deb7u1)
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 1497 kB of archives.
After this operation, 3082 kB of additional disk space will be used.
Do you want to continue [Y/n]? 
```

Comment (tianon) [inline contrib/builder/deb/generate.sh]: Also, I think this means we need to update `project/PACKAGERS.md` too, since it says:
> - btrfs-progs version 3.16.1 or later (unless using an older version is absolutely necessary, in which case 3.8 is the minimum)

Comment (tianon) [inline contrib/builder/deb/generate.sh]: Although from what I can find, it does appear that this restriction is "good enough" still (ie, 3.8 appears to contain the header fields we require).

**Comment by jfrazelle** [comment]
updated! also the btrfs in btrfs build is broken on master for other reasons, so I need to look into those but its not related to this patch and this patch does fix the child subvolume delete issue ;)

**Comment by tianon** [comment]
Bombin' :bomb:; LGTM :+1:

**Comment by LK4D4** [comment]
LGTM

**Comment by rgbkrk** [comment]
OMG, thank you as always @jfrazelle.

**Comment by jfrazelle** [comment]
HTH it was mostly @Mashimiao ;)

**Comment by rgbkrk** [comment]
Thank you @Mashimiao!

**Comment by nuxlli** [comment]
thank you @Mashimiao and @jfrazelle!
@jfrazelle: Any idea about in which release this fix should be published?

**Comment by tianon** [comment]
Should be in 1.9.
