### PR TITLE
RunOOM test should check to see if Oom Control is enabled

### LINKED ISSUE #13766: fix DockerSuite.TestRunOOMExitCode
Should not error like this:

```
----------------------------------------------------------------------
FAIL: docker_cli_run_test.go:2868: DockerSuite.TestRunOOMExitCode

docker_cli_run_test.go:2881:
    c.Assert(err, check.IsNil)
... value *errors.errorString = &errors.errorString{s:"wrong exit code for OOM container: expected 137, got 1 (output: \"WARNING: Your kernel does not support memory limit capabilities. Limitation discarded.\\nsh: out of memory\\n\")"} ("wrong exit code for OOM container: expected 137, got 1 (output: \"WARNING: Your kernel does not support memory limit capabilities. Limitation discarded.\\nsh: out of memory\\n\")")
```

### PR DESCRIPTION
**Pull request by brahmaroutu**
closes #13766
Signed-off-by: Srini Brahmaroutu srbrahma@us.ibm.com

### CODE REVIEW

File: integration-cli/requirements.go [hunk 1]
```diff
@@ -96,6 +98,26 @@ var (
 		},
 		"Test requires underlying root filesystem not be backed by overlay.",
 	}
+	OomControl = TestRequirement{
+		func() bool {
+			if cgroupMemoryMountpoint, err := cgroups.FindCgroupMountpoint("memory"); err != nil {
+				return false
+			} else {
```
Comment (runcom) [inline integration-cli/requirements.go]: this `else` is not needed as you're returning before

**Comment by crosbymichael** [comment]
LGTM
