### PR TITLE
Fix TestDockerCmd*Timeout racey tests

### LINKED ISSUE #16360: Fix TestDockerCmdWithTimeout
`TestDockerCmdWithTimeout` from `pkg/integration` is racey and is currently being skipped.

### PR DESCRIPTION
**Pull request by vdemeester**
A <del>very</del> less Naǐve way to fix these racey tests 🐻, but it seems to do the work :sweat_smile:.

I'm gonna re-run janky & friends a bunch times on it to make sure it's not failing..

Fixes #16360 

🐸

Signed-off-by: Vincent Demeester vincent@sbr.pm

### CODE REVIEW

File: pkg/integration/dockerCmd_utils_test.go [hunk 1]
```diff
@@ -389,7 +387,7 @@ func TestHelperProcess(t *testing.T) {
 			fmt.Fprintf(os.Stderr, "an error has occurred")
 			os.Exit(1)
 		case "a command that times out":
-			time.Sleep(10 * time.Millisecond)
+			time.Sleep(10 * time.Second)
```
Comment (vdemeester) [inline pkg/integration/dockerCmd_utils_test.go]: It's probably not needed (given the change in `utils.go`).

**Comment by duglin** [comment]
@vdemeester where is the racey-ness coming from?

**Comment by vdemeester** [comment]
@duglin in `RunCommandWithOutputForDuration` we run the command inside a goroutine, [here](https://github.com/docker/docker/pull/16582/files#diff-022bbe981f977c5e00ff160d578e5105L109) and then we wait for some time to kill it.

The problem is that the code that started the command `cmd.Run()` might not have been call in time (depending on the timeout duration we specify), there is no real guarantee when it's gonna be called.. So when killing the process, using `cmd.Process.Kill()` ([here](https://github.com/docker/docker/pull/16582/files#diff-022bbe981f977c5e00ff160d578e5105L116)), the goroutine might have not been called yet (and that's what was happening).

So I changed it to make sure the command have at least been started (using the `started` channel) by splitting `cmd.Run()` into `cmd.Start()`, updating the `started` channel to get to the `select` and *start the timer* and do a `cmd.Wait()` inside the goroutine to wait for the command to finish (if not killed because of timeout).

Hopefully my explanation is clear :stuck_out_tongue_closed_eyes:, let me know :wink:.

**Comment by cpuguy83** [comment]
Yeah never really any guarantee.
Try adding s 'runtime.Gosched()' call in there.

**Comment by duglin** [comment]
@vdemeester thanks for the explanation. I guess you could have also just done the cmd.Start() logic outside of the go routine, leaving just the Wait() and exit code processing in there - then you never create the goroutine at all if the cmd fails to start.  But the 'started' stuff works too.

And I agree with removing the sleep.

**Comment by vdemeester** [comment]
@duglin ah true, I didn't though of making it like that but it would work too. I'm wondering what cost more (but I think it's probably at an level of optimization that's not needed :stuck_out_tongue_closed_eyes: ).

@cpuguy83 Using `runtime.Gosched()` will make it work without my channel, right ? I don't which solution is the cleaner :baby_chick:.

**Comment by duglin** [comment]
If the cmd won't start then you'll save the cost of the additional thread - not a big deal but I think it'll be cleaner to read/follow in those failure cases.

I'm not sure a call to Gosched will fix it since it just switches over to another thread but it doesn't guarantee that the other thread will complete what you think it'll do before it switches back. I think being explicit about waiting for the cmd to start (or fail) is safer.

**Comment by vdemeester** [comment]
> If the cmd won't start then you'll save the cost of the additional thread - not a big deal but I think it'll be cleaner to read/follow in those failure cases.

True, I'll update the code to reflect that :wink:.

**Comment by vdemeester** [comment]
@duglin done :)

File: pkg/integration/dockerCmd_utils_test.go [hunk 2]
```diff
@@ -389,7 +387,7 @@ func TestHelperProcess(t *testing.T) {
 			fmt.Fprintf(os.Stderr, "an error has occurred")
 			os.Exit(1)
 		case "a command that times out":
-			time.Sleep(10 * time.Millisecond)
+			time.Sleep(30 * time.Millisecond)
```
Comment (duglin) [inline pkg/integration/dockerCmd_utils_test.go]: Is this change related to this PR?

I'm not familiar with this func, but what is this 'case' doing? It seems like this isn't much different than the 'echo hello' case below, especially since I wouldn't have expected a process that was killed due to a timeout to exit with non-zero.

**Comment by duglin** [comment]
@vdemeester I like the change - thanks!  Just one other question

File: pkg/integration/dockerCmd_utils_test.go (hunk 2 above)
Comment (vdemeester) [inline pkg/integration/dockerCmd_utils_test.go]: This is used there : https://github.com/docker/docker/blob/master/pkg/integration/dockerCmd_utils_test.go#L190.

Basically, `TestDockerCmdWithTimeout`, will call the fake `dockerBinary` command that runs the test binary with special flags and gets to there : `TestHelperProcess` (This is basically what's done in the golang exec tests :smile_cat:). The idea behind that case is that if I do some `exec.Command(dockerBinary, "a", "command", "that", "times", "out")`, I want a long running command so that it will be killed by my test case. And I'm checking afterwards that it has failed — although you make a point.. I should change the `os.Exit(0)` to something else to make sure it did not complete (and then didn't get a different exit code).

And also, I don't remember why I did change `10` to `30` :sweat:. Guess it's from my early tests on this racey thingy.

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
ping @duglin

**Comment by duglin** [comment]
sorry for the delay.
LGTM
