### PR TITLE
rootless: prevent the service hanging when stopping (set systemd KillMode to mixed)

### LINKED ISSUE #41944: Docker rootless does not exit properly if containers are running
**Description**

I'm running docker rootless (as a systemd service).

When stopping the service:

- ... if containers are NOT running, docker exits fine.
- ... if containers are running, docker stops the containers immediately, but **does not** exit fine, but is killed by systemd after the 90s timeout (service had 90s to exit cleanly before being `SIGKILL`'d.

This initial became evident since, when shutting down the system, systemd waits 90s for docker to stop, and _then_ kills it, so it's been slowing down people's shutdown.

I'm the maintainer for the docker-rootless [ArchLinux AUR package](https://aur.archlinux.org/packages/docker-rootless-extras-bin/), and several other users report the same issue.

**Steps to reproduce the issue:**

1. Run docker rootless
2. Run a container (e.g.: `docker run --rm -it node:12 bash`)
3. Stop the service (e.g.: `systemctl --user stop docker.service`)

**Describe the results you received:**

The container is killed immediately, but the docker service does not stop until the 90s timeout (systemd sends a SIGKILL after that time). Changing the systemd's timeout makes docker take that long to exit.

This _does not_ happen is no containers are running.

**Describe the results you expected:**

The docker service should exit immediately.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
$ docker version
Client:
 Version:           20.10.1
 API version:       1.41
 Go version:        go1.15.6
 Git commit:        2291f610ae
 Built:             Tue Jan 19 17:19:21 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
```

**Output of `docker info`:**

```
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-tp-docker)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I'm having this issue on a physical ArchLinux machine, and other Arch users report the same issue.

### PR DESCRIPTION
**Pull request by AkihiroSuda**
**- What I did**
Fix  #41944 ("Docker rootless does not exit properly if containers are running")

Now `systemctl --user stop docker` completes just with in 1 or 2 seconds.

**- How I did it**
Changed the KillMode from "control-group" (default) to "mixed"

See systemd.kill(5) https://www.freedesktop.org/software/systemd/man/systemd.kill.html

> Specifies how processes of this unit shall be killed. One of control-group, mixed, process, none.

> If set to control-group, all remaining processes in the control group of this unit will be killed on unit stop (for services: after the stop command is executed, as configured with ExecStop=). If set to mixed, the SIGTERM signal (see below) is sent to the main process while the subsequent SIGKILL signal (see below) is sent to all remaining processes of the unit's control group. If set to process, only the main process itself is killed (not recommended!). If set to none, no process is killed (strongly recommended against!). In this case, only the stop command will be executed on unit stop, but no process will be killed otherwise. Processes remaining alive after stop are left in their control group and the control group continues to exist after stop unless empty.

> Note that it is not recommended to set KillMode= to process or even none, as this allows processes to escape the service manager's lifecycle and resource management, and to remain running even while their service is considered stopped and is assumed to not consume any resources.

> Processes will first be terminated via SIGTERM (unless the signal to send is changed via KillSignal= or RestartKillSignal=). Optionally, this is immediately followed by a SIGHUP (if enabled with SendSIGHUP=). If processes still remain after the main process of a unit has exited or the delay configured via the TimeoutStopSec= has passed, the termination request is repeated with the SIGKILL signal or the signal specified via FinalKillSignal= (unless this is disabled via the SendSIGKILL= option). See kill(2) for more information.

> Defaults to control-group.

"mixed" is available since systemd 209 (2014-02-20) https://github.com/systemd/systemd/blob/57353d2909e503e3e5c7e69251ba95a31e1a72ce/NEWS#L9318

**- How to verify it**

Run some containers with rootless, and make sure `systemctl --user stop docker.service` completes in a few seconds.

```bash
$ docker --context=rootless run --name nginx -d -p 8080:80 --restart=always nginx:alpine
$ time systemctl --user stop docker

real    0m1.266s
user    0m0.005s
sys     0m0.000s

```

**- Description for the changelog**

rootless: prevent the service hanging when stopping (set systemd KillMode to mixed)

**- A picture of a cute animal (not mandatory but encouraged)**

:penguin:

### CODE REVIEW

File: contrib/dockerd-rootless-setuptool.sh [hunk 1]
```diff
@@ -307,6 +307,7 @@ install_systemd() {
 			TasksMax=infinity
 			Delegate=yes
 			Type=simple
+			KillMode=mixed
```
Comment (thaJeztah) [inline contrib/dockerd-rootless-setuptool.sh:310]: Does/should rootless mode support "live-restore"? ISTR we use "process" in the regular systemd unit because of that; https://github.com/docker/docker-ce-packaging/blob/master/systemd/docker.service#L43

Comment (AkihiroSuda) [reply contrib/dockerd-rootless-setuptool.sh:310]: No, at least for now

**Review by thaJeztah — APPROVED** [review]
LGTM

@tianon ptal

**Comment by WhyNotHugo** [comment]
Minor nitpick: the changelog entry should describe _what_ is done, not _how_ it's done. E.g.:

> rootless: prevent the service hanging when stopping

**Comment by AkihiroSuda** [comment]
updated PR description, thanks for suggestion

File: contrib/dockerd-rootless-setuptool.sh (hunk 1 above)
Comment (tianon) [reply contrib/dockerd-rootless-setuptool.sh:310]: "process" does seem more correct eventually, but mixed sounds good for now :+1:

**Review by tianon — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
s390x failure is unrelated; rootless CI is green. I consider it not worth restarting CI for that

**Comment by WhyNotHugo** [comment]
Thanks!

**Comment by AkihiroSuda** [comment]
This was not included in v20.10.3. Proposing to v20.10.4 in #41956.
