### PR TITLE
Convert Unused ARG error to warning

### LINKED ISSUE #26249: Unconsumed build-arg should not fail docker build
---
## BUG REPORT INFORMATION

**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 24
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 29
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.0-30-generic
Operating System: Ubuntu 14.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: localhost
ID: WLEB:43M4:CAE3:SKQF:5SMS:EFWL:JRJF:S3O7:D2AC:S6ZO:R3M3:SDYC
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Username: rzachariah
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

VirtualBox VM running on Windows 7 machine. Accessed via Vagrant.

**Steps to reproduce the issue:**
1. Create a valid Dockerfile (in my case, for a node service). DO NOT consume the build-arg we will pass in next.
2. Build the docker image passing in an unused build-arg
docker build --build-arg VERSION=3.1.4 -t hello-error .

**Describe the results you received:**
Docker build fails with this error:
Step 11 : EXPOSE 80
 ---> Using cache
 ---> aed38f6ddf88
Step 12 : CMD npm start
 ---> Using cache
 ---> c33d33264d01
One or more build-args [VERSION] were not consumed, failing build.

**Describe the results you expected:**
Build should succeed.

**Additional information you deem important (e.g. issue happens only occasionally):**
I think it makes more sense for build-args to be optional. We have a CI build script that runs the docker build command. It's shared across our org. Not everyone needs the variable we pass in.

### PR DESCRIPTION
**Pull request by addamh**
**\- How I did it**

Convert error message and failure of build when an unused build-arg is supplied to a successful build and a warning message. Resolves #26249 

**\- How to verify it**
1. Create a valid Dockerfile. DO NOT consume the build-arg `test-arg`
2. Build the docker image passing in an unused build-arg
   docker build --build-arg test-arg=value -t hello .

**\- Description for the changelog**

Unused build-args are now allowed. A warning is presented instead of an error and failed build.

### CODE REVIEW

File: integration-cli/docker_cli_build_test.go [hunk 1]
```diff
@@ -6027,11 +6027,8 @@ func (s *DockerSuite) TestBuildBuildTimeArgUnconsumedArg(c *check.C) {
 		RUN echo $%s
 		CMD echo $%s`, envKey, envKey)
 
-	errStr := "One or more build-args"
-	if _, out, err := buildImageWithOut(imgName, dockerfile, true, args...); err == nil {
-		c.Fatalf("build succeeded, expected to fail. Output: %v", out)
-	} else if !strings.Contains(out, errStr) {
-		c.Fatalf("Unexpected error. output: %q, expected error: %q", out, errStr)
+	if _, out, err := buildImageWithOut(imgName, dockerfile, true, args...); err != nil {
+		c.Fatalf("build failed to complete: %q %q", out, err)
```
Comment (duglin) [inline integration-cli/docker_cli_build_test.go]: Can we search for the warning message and make sure its there?

Comment (addamh) [inline integration-cli/docker_cli_build_test.go]: I think that's a good idea. Will update tomorrow :+1:

File: builder/dockerfile/builder.go [hunk 2]
```diff
@@ -271,15 +271,16 @@ func (b *Builder) build(stdout io.Writer, stderr io.Writer, out io.Writer) (stri
...
 	leftoverArgs := []string{}
 	for arg := range b.options.BuildArgs {
 		if !b.isBuildArgAllowed(arg) {
 			leftoverArgs = append(leftoverArgs, arg)
 		}
 	}
+
 	if len(leftoverArgs) > 0 {
-		return "", fmt.Errorf("One or more build-args %v were not consumed, failing build.", leftoverArgs)
+		fmt.Fprintf(b.Stdout, "[Warning] One or more build-args %v were not consumed\n", leftoverArgs)
```
Comment (thaJeztah) [inline builder/dockerfile/builder.go]: should this be printed to stdout or stderr? (not sure)

Comment (addamh) [inline builder/dockerfile/builder.go]: IMO shouldn't be stderr since not an error, but could see argument for either option

Comment (duglin) [inline builder/dockerfile/builder.go]: A while ago someone posted a link to a web site that made an argument for when to use stdout vs stderr for things like info/warning messages. Their basic premise was that stdout should be reserved for normal/expected output - and therefore including things like info/warning messages in there would do nothing but muck-up any output processing (like grep, sed, ...) that people may have. It convinced me that stderr should be used.  But YMMV

Comment (addamh) [inline builder/dockerfile/builder.go]: Definitely an interesting perspective. I can switch output if that's where the consensus is.

**Comment by addamh** [comment]
Apologies for the delay, but updated per review comments and tests are passing. Ready for another pass. Thanks!

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
ping @duglin PTAL

**Comment by duglin** [comment]
just a couple of minor doc edits, otherwise it looks good.

**Comment by thaJeztah** [comment]
ping @addamh can you update the PR with the changes @duglin requested?

**Comment by addamh** [comment]
Yes I definitely will before Monday. Sorry for the delay!

File: docs/reference/builder.md [hunk 3]
```diff
@@ -1274,12 +1274,12 @@ The output of the final `pwd` command in this `Dockerfile` would be
...
-the builder with the `docker build` command using the
-`--build-arg <varname>=<value>` flag. If a user specifies a build argument
-that was not defined in the Dockerfile, the build outputs an error.
+the builder with the `docker build` command using the `--build-arg
+<varname>=<value>` flag. If a user specifies a build argument that was not
+defined in the Dockerfile, the build outputs a warning.
 
 ```
-One or more build-args were not consumed, failing build.
+[Warning] One or more build-args %v were not consumed.
```
Comment (thaJeztah) [inline docs/reference/builder.md]: Oh, i see you included the literal `%v` in the docs; @duglin meant to say that this should show what it looks like if one or more ARGS were not used

File: man/Dockerfile.5.md [hunk 4]
```diff
@@ -326,10 +326,10 @@ A Dockerfile is similar to a Makefile.
   The `ARG` instruction defines a variable that users can pass at build-time to
   the builder with the `docker build` command using the `--build-arg
   <varname>=<value>` flag. If a user specifies a build argument that was not
-  defined in the Dockerfile, the build outputs an error.
+  defined in the Dockerfile, the build outputs a warning.
 
   ```
-  One or more build-args were not consumed, failing build.
+  [Warning] One or more build-args %v were not consumed
```
Comment (thaJeztah) [inline man/Dockerfile.5.md]: Same here

**Review by thaJeztah — CHANGES_REQUESTED** [review]

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by duglin** [comment]
LGTM

**Comment by slawomirfurtak** [comment]
Hi!
What do you think about disabling/hiding this warning for predefined build ARG variables (like *_proxy)? There is no need setting it inside Dockerfile, but are in fact "consumed" by tools (i.e. yum, apt-get, curl, wget...) inside RUN instruction. This warning  in that case is misleading. Docs says about it:  _"Docker has a set of predefined ARG variables that you can use without a corresponding ARG instruction in the Dockerfile."_

**Comment by thaJeztah** [comment]
@slawomirfurtak that warning is a bug in docker 17.05 (see https://github.com/moby/moby/issues/33067), and will be addressed in 17.06 through https://github.com/moby/moby/pull/33114

**Comment by slawomirfurtak** [comment]
Couldn't find that, thank you for fast response!
