### PR TITLE
daemon: daemon.prepareMountPoints(): fix panic if mount is not a volume

### LINKED ISSUE #919: docker.service fails to start after upgrade from 24.0.2 to 24.0.3
Hello,

We have encountered issues with our docker installation after the upgrade from 24.0.2 to 24.0.3 on the following systems:
- Debian 10
- Debian 11
- Ubuntu 20.04
- Ubuntu 22.04

According to the logs, it looks like the upgrade failed but we could not find the reason why:

```
~$ dpkg -l | grep docker-ce
iF  docker-ce                            5:24.0.3-1~ubuntu.20.04~focal     amd64        Docker: the open-source application container engine
```
When running the upgrade command it fails when starting the docker service:

```
$ sudo apt-get upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up docker-ce (5:24.0.3-1~ubuntu.20.04~focal) ...
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "restart" failed.
● docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/docker.service.d
             └─service-overrides.conf
     Active: activating (auto-restart) (Result: exit-code) since Fri 2023-07-07 10:12:43 CEST; 23ms ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
    Process: 3601344 ExecStart=/usr/bin/dockerd $OPTIONS $DOCKER_STORAGE_OPTIONS (code=exited, status=2)
   Main PID: 3601344 (code=exited, status=2)

Jul 07 10:12:43 systemd[1]: docker.service: Failed with result 'exit-code'.
Jul 07 10:12:43 systemd[1]: Failed to start Docker Application Container Engine.
dpkg: error processing package docker-ce (--configure):
 installed docker-ce package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 docker-ce
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
Tried to uninstall docker-ce and install it but that also did not help. For now we downgraded the servers that are affected to 24.0.2 and it works fine.

### LINKED ISSUE #45898: Failed to restart daemon after 24.0.2 -> 24.0.3 upgrade
### Description

After update on all hosts (20+, all that I'm running) docker daemon is failed.

error is:

```
Jul 07 03:03:17 server systemd[1]: Starting Docker Application Container Engine...
Jul 07 03:03:17 server dockerd[52024]: time="2023-07-07T03:03:17.076517762Z" level=info msg="Starting up"
Jul 07 03:03:17 server dockerd[52024]: time="2023-07-07T03:03:17.086137356Z" level=info msg="[graphdriver] using prior storage driver: fuse-overlayfs"
Jul 07 03:03:17 server dockerd[52024]: time="2023-07-07T03:03:17.103391077Z" level=info msg="Loading containers: start."
Jul 07 03:03:17 server dockerd[52024]: time="2023-07-07T03:03:17.411734779Z" level=info msg="there are running containers, updated network configuration will not take affect"
Jul 07 03:03:17 server dockerd[52024]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 07 03:03:17 server dockerd[52024]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x564e9be4c7c0]
Jul 07 03:03:17 server dockerd[52024]: goroutine 607 [running]:
Jul 07 03:03:17 server dockerd[52024]: github.com/docker/docker/daemon.(*Daemon).prepareMountPoints(0xc00054b7b8?, 0xc0007c2500)
Jul 07 03:03:17 server dockerd[52024]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/mounts.go:24 +0x1c0
Jul 07 03:03:17 server dockerd[52024]: github.com/docker/docker/daemon.(*Daemon).restore.func5(0xc0007c2500, 0x0?)
Jul 07 03:03:17 server dockerd[52024]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/daemon.go:552 +0x271
Jul 07 03:03:17 server dockerd[52024]: created by github.com/docker/docker/daemon.(*Daemon).restore
Jul 07 03:03:17 server dockerd[52024]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/daemon.go:530 +0x8d8
Jul 07 03:03:17 server dockerd[52024]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 07 03:03:17 server dockerd[52024]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x564e9be4c7c0]
Jul 07 03:03:17 server dockerd[52024]: goroutine 601 [running]:
Jul 07 03:03:17 server dockerd[52024]: github.com/docker/docker/daemon.(*Daemon).prepareMountPoints(0xc00054b7b8?, 0xc000cb2000)
Jul 07 03:03:17 server dockerd[52024]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/mounts.go:24 +0x1c0
Jul 07 03:03:17 server dockerd[52024]: github.com/docker/docker/daemon.(*Daemon).restore.func5(0xc000cb2000, 0x0?)
Jul 07 03:03:17 server dockerd[52024]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/daemon.go:552 +0x271
Jul 07 03:03:17 server dockerd[52024]: created by github.com/docker/docker/daemon.(*Daemon).restore
Jul 07 03:03:17 server dockerd[52024]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/daemon.go:530 +0x8d8
Jul 07 03:03:17 server dockerd[52024]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 07 03:03:17 server dockerd[52024]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x564e9be4c7c0]
Jul 07 03:03:17 server dockerd[52024]: goroutine 603 [running]:
Jul 07 03:03:17 server dockerd[52024]: github.com/docker/docker/daemon.(*Daemon).prepareMountPoints(0xc00054b7b8?, 0xc000187680)
Jul 07 03:03:17 server dockerd[52024]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/mounts.go:24 +0x1c0
Jul 07 03:03:17 server dockerd[52024]: github.com/docker/docker/daemon.(*Daemon).restore.func5(0xc000187680, 0x0?)
Jul 07 03:03:17 server dockerd[52024]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/daemon.go:552 +0x271
Jul 07 03:03:17 server dockerd[52024]: created by github.com/docker/docker/daemon.(*Daemon).restore
Jul 07 03:03:17 server dockerd[52024]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/daemon.go:530 +0x8d8
Jul 07 03:03:17 server dockerd[52024]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 07 03:03:17 server dockerd[52024]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x564e9be4c7c0]
Jul 07 03:03:17 server dockerd[52024]: goroutine 600 [running]:
Jul 07 03:03:17 server dockerd[52024]: github.com/docker/docker/daemon.(*Daemon).prepareMountPoints(0xc00054b7b8?, 0xc00063e500)
Jul 07 03:03:17 server dockerd[52024]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/mounts.go:24 +0x1c0
Jul 07 03:03:17 server dockerd[52024]: github.com/docker/docker/daemon.(*Daemon).restore.func5(0xc00063e500, 0xc00005e600?)
Jul 07 03:03:17 server dockerd[52024]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/daemon.go:552 +0x271
Jul 07 03:03:17 server dockerd[52024]: created by github.com/docker/docker/daemon.(*Daemon).restore
Jul 07 03:03:17 server dockerd[52024]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/daemon.go:530 +0x8d8
```

I'm running daemon with config:

```
{
  "live-restore": true
}
```

any chance to manage restart daemon without restarting containers?

### Reproduce

systemctl restart docker

### Expected behavior

systemd service to start

### docker version

```bash
unable to provide, as service is down
```

### docker info

```bash
unable to provide, as service is down
```

### Additional Info

cant provide docker info as service do not start, I have containers running on servers.

If i reboot server (i.e. containers get stopped, docker starts without issues)

### LINKED ISSUE #45907: dockerd segfaults when patching 24.0.2 to 24.0.3 with live-restore enabled
### Description

During an upgrade from 24.0.2 to 24.0.3, via apt-get on Debian 11, with live-restore enabled and running containers, the docker daemon fails to start. Running `sudo dockerd --debug` shows that a segfault is happening. The only possible solution is to reinstall 24.0.2, stop all running containers, then upgrade to 24.0.3. This defeats the purpose of live-restore.

### Reproduce

1. Using docker's debian repository for Debian 11
2. Create `/etc/docker/daemon.json` with `live-restore: true`
3. `sudo apt-get install docker=5:24.0.2*`
4. Run a persistent container, such as nginx.
5. `sudo apt-get install docker=5:24.0.3*`
6. Docker daemon cannot start. 

### Expected behavior

Docker daemon should be able to restart between maintanence patches with live-restore enabled, per docs: https://docs.docker.com/config/containers/live-restore/

### docker version

```bash
Client: Docker Engine - Community
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:52:17 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.3
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.5
  Git commit:       1d9c861
  Built:            Wed Jul  5 20:44:59 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  v2.19.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 24.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.10.0-23-cloud-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 864MiB
 Name: codered-dev-vince
 ID: e7d8687c-6eb5-4f60-91bf-e3299544ef7b
 Docker Root Dir: /cr/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true

WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpu shares support
```

### Additional Info

Output of `sudo dockerd --debug`

```
INFO[2023-07-07T18:55:57.751488129Z] Starting up
DEBU[2023-07-07T18:55:57.752189772Z] Listener created for HTTP on unix (/var/run/docker.sock)
DEBU[2023-07-07T18:55:57.754117291Z] Golang's threads limit set to 6030
DEBU[2023-07-07T18:55:57.755639384Z] metrics API listening on /var/run/docker/metrics.sock
DEBU[2023-07-07T18:55:57.763404663Z] Using default logging driver json-file
DEBU[2023-07-07T18:55:57.763552272Z] No quota support for local volumes in /cr/docker/volumes: Filesystem does not support, or has not enabled quotas
DEBU[2023-07-07T18:55:57.774065420Z] processing event stream                       module=libcontainerd namespace=plugins.moby
DEBU[2023-07-07T18:55:57.777944159Z] [graphdriver] priority list: [overlay2 fuse-overlayfs btrfs zfs devicemapper vfs]
DEBU[2023-07-07T18:55:57.811403321Z] successfully detected metacopy status         storage-driver=overlay2 usingMetacopy=false
DEBU[2023-07-07T18:55:57.826099126Z] backingFs=extfs, projectQuotaSupported=false, usingMetacopy=false, indexOff="index=off,", userxattr=""  storage-driver=overlay2
INFO[2023-07-07T18:55:57.826246635Z] [graphdriver] using prior storage driver: overlay2
DEBU[2023-07-07T18:55:57.826298139Z] Initialized graph driver overlay2
DEBU[2023-07-07T18:55:57.836367259Z] Max Concurrent Downloads: 3
DEBU[2023-07-07T18:55:57.836486966Z] Max Concurrent Uploads: 5
DEBU[2023-07-07T18:55:57.836538670Z] Max Download Attempts: 5
INFO[2023-07-07T18:55:57.836602674Z] Loading containers: start.
DEBU[2023-07-07T18:55:57.838309879Z] loaded container                              container=af36b7292360b6e372a58551fe52bc51248853851af42526cf8a549ca08d72a7 paused=false running=true
DEBU[2023-07-07T18:55:57.836745882Z] processing event stream                       module=libcontainerd namespace=moby
DEBU[2023-07-07T18:55:57.885338677Z] restoring container                           container=af36b7292360b6e372a58551fe52bc51248853851af42526cf8a549ca08d72a7 paused=false restarting=false running=true
DEBU[2023-07-07T18:55:57.888267257Z] syncing container on disk state with real state  container=af36b7292360b6e372a58551fe52bc51248853851af42526cf8a549ca08d72a7 paused=false restarting=false running=true
DEBU[2023-07-07T18:55:57.888298759Z] restoring healthcheck                         container=af36b7292360b6e372a58551fe52bc51248853851af42526cf8a549ca08d72a7 paused=false restarting=false running=true
DEBU[2023-07-07T18:55:57.888357463Z] container mounted via layerStore: /cr/docker/overlay2/96a2abf701eca59edc0e734cb0a5c62ebdf44e457ee018c7e62e7e92530842c1/merged  container=af36b7292360b6e372a58551fe52bc51248853851af42526cf8a549ca08d72a7
DEBU[2023-07-07T18:55:57.888428467Z] done restoring container                      container=af36b7292360b6e372a58551fe52bc51248853851af42526cf8a549ca08d72a7 paused=false restarting=false running=true
DEBU[2023-07-07T18:55:57.888551875Z] Option DefaultDriver: bridge
DEBU[2023-07-07T18:55:57.888629479Z] Option DefaultNetwork: bridge
DEBU[2023-07-07T18:55:57.888683383Z] Network Control Plane MTU: 1500
DEBU[2023-07-07T18:55:57.893365471Z] /usr/sbin/iptables, [--wait -t filter -C FORWARD -j DOCKER-ISOLATION]
DEBU[2023-07-07T18:55:57.894799360Z] /usr/sbin/iptables, [--wait -t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]
DEBU[2023-07-07T18:55:57.896609071Z] /usr/sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER]
DEBU[2023-07-07T18:55:57.898118964Z] /usr/sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER]
DEBU[2023-07-07T18:55:57.899599055Z] /usr/sbin/iptables, [--wait -t nat -D PREROUTING]
DEBU[2023-07-07T18:55:57.901662883Z] /usr/sbin/iptables, [--wait -t nat -D OUTPUT]
DEBU[2023-07-07T18:55:57.902973563Z] /usr/sbin/iptables, [--wait -t nat -F DOCKER]
DEBU[2023-07-07T18:55:57.904232641Z] /usr/sbin/iptables, [--wait -t nat -X DOCKER]
DEBU[2023-07-07T18:55:57.905375311Z] /usr/sbin/iptables, [--wait -t filter -F DOCKER]
DEBU[2023-07-07T18:55:57.906590686Z] /usr/sbin/iptables, [--wait -t filter -X DOCKER]
DEBU[2023-07-07T18:55:57.907927369Z] /usr/sbin/iptables, [--wait -t filter -F DOCKER-ISOLATION-STAGE-1]
DEBU[2023-07-07T18:55:57.909146644Z] /usr/sbin/iptables, [--wait -t filter -X DOCKER-ISOLATION-STAGE-1]
DEBU[2023-07-07T18:55:57.910443024Z] /usr/sbin/iptables, [--wait -t filter -F DOCKER-ISOLATION-STAGE-2]
DEBU[2023-07-07T18:55:57.911776906Z] /usr/sbin/iptables, [--wait -t filter -X DOCKER-ISOLATION-STAGE-2]
DEBU[2023-07-07T18:55:57.913032683Z] /usr/sbin/iptables, [--wait -t filter -F DOCKER-ISOLATION]
DEBU[2023-07-07T18:55:57.914283160Z] /usr/sbin/iptables, [--wait -t filter -X DOCKER-ISOLATION]
DEBU[2023-07-07T18:55:57.915544138Z] /usr/sbin/iptables, [--wait -t nat -n -L DOCKER]
DEBU[2023-07-07T18:55:57.916962425Z] /usr/sbin/iptables, [--wait -t nat -N DOCKER]
DEBU[2023-07-07T18:55:57.918170600Z] /usr/sbin/iptables, [--wait -t filter -n -L DOCKER]
DEBU[2023-07-07T18:55:57.920127520Z] /usr/sbin/iptables, [--wait -t filter -n -L DOCKER-ISOLATION-STAGE-1]
DEBU[2023-07-07T18:55:57.921569509Z] /usr/sbin/iptables, [--wait -t filter -n -L DOCKER-ISOLATION-STAGE-2]
DEBU[2023-07-07T18:55:57.922907192Z] /usr/sbin/iptables, [--wait -t filter -N DOCKER-ISOLATION-STAGE-2]
DEBU[2023-07-07T18:55:57.924143468Z] /usr/sbin/iptables, [--wait -t filter -C DOCKER-ISOLATION-STAGE-1 -j RETURN]
DEBU[2023-07-07T18:55:57.925841273Z] /usr/sbin/iptables, [--wait -A DOCKER-ISOLATION-STAGE-1 -j RETURN]
DEBU[2023-07-07T18:55:57.927130152Z] /usr/sbin/iptables, [--wait -t filter -C DOCKER-ISOLATION-STAGE-2 -j RETURN]
DEBU[2023-07-07T18:55:57.928807255Z] /usr/sbin/iptables, [--wait -A DOCKER-ISOLATION-STAGE-2 -j RETURN]
DEBU[2023-07-07T18:55:57.935165247Z] /usr/sbin/iptables, [--wait -t nat -C POSTROUTING -s 172.18.0.0/16 ! -o br-40eb041fff2c -j MASQUERADE]
DEBU[2023-07-07T18:55:57.937966420Z] /usr/sbin/iptables, [--wait -t nat -C DOCKER -i br-40eb041fff2c -j RETURN]
DEBU[2023-07-07T18:55:57.939362706Z] /usr/sbin/iptables, [--wait -t nat -I DOCKER -i br-40eb041fff2c -j RETURN]
DEBU[2023-07-07T18:55:57.940792394Z] /usr/sbin/iptables, [--wait -t nat -C POSTROUTING -m addrtype --src-type LOCAL -o br-40eb041fff2c -j MASQUERADE]
DEBU[2023-07-07T18:55:57.942389992Z] /usr/sbin/iptables, [--wait -D FORWARD -i br-40eb041fff2c -o br-40eb041fff2c -j DROP]
DEBU[2023-07-07T18:55:57.944353513Z] /usr/sbin/iptables, [--wait -t filter -C FORWARD -i br-40eb041fff2c -o br-40eb041fff2c -j ACCEPT]
DEBU[2023-07-07T18:55:57.945916610Z] /usr/sbin/iptables, [--wait -t filter -C FORWARD -i br-40eb041fff2c ! -o br-40eb041fff2c -j ACCEPT]
DEBU[2023-07-07T18:55:57.947477006Z] /usr/sbin/iptables, [--wait -t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]
DEBU[2023-07-07T18:55:57.948950497Z] /usr/sbin/iptables, [--wait -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]
DEBU[2023-07-07T18:55:57.950282879Z] /usr/sbin/iptables, [--wait -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8]
DEBU[2023-07-07T18:55:57.951860776Z] /usr/sbin/iptables, [--wait -t nat -A OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8]
DEBU[2023-07-07T18:55:57.953212859Z] /usr/sbin/iptables, [--wait -t filter -C FORWARD -o br-40eb041fff2c -j DOCKER]
DEBU[2023-07-07T18:55:57.954762455Z] /usr/sbin/iptables, [--wait -t filter -C FORWARD -o br-40eb041fff2c -j DOCKER]
DEBU[2023-07-07T18:55:57.956406456Z] /usr/sbin/iptables, [--wait -t filter -C FORWARD -o br-40eb041fff2c -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT]
DEBU[2023-07-07T18:55:57.957920749Z] /usr/sbin/iptables, [--wait -t filter -C FORWARD -o br-40eb041fff2c -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT]
DEBU[2023-07-07T18:55:57.959478845Z] /usr/sbin/iptables, [--wait -t filter -C FORWARD -j DOCKER-ISOLATION-STAGE-1]
DEBU[2023-07-07T18:55:57.960980838Z] /usr/sbin/iptables, [--wait -D FORWARD -j DOCKER-ISOLATION-STAGE-1]
DEBU[2023-07-07T18:55:57.962292619Z] /usr/sbin/iptables, [--wait -I FORWARD -j DOCKER-ISOLATION-STAGE-1]
DEBU[2023-07-07T18:55:57.963434589Z] /usr/sbin/iptables, [--wait -t filter -C DOCKER-ISOLATION-STAGE-1 -i br-40eb041fff2c ! -o br-40eb041fff2c -j DOCKER-ISOLATION-STAGE-2]
DEBU[2023-07-07T18:55:57.964790573Z] /usr/sbin/iptables, [--wait -t filter -I DOCKER-ISOLATION-STAGE-1 -i br-40eb041fff2c ! -o br-40eb041fff2c -j DOCKER-ISOLATION-STAGE-2]
DEBU[2023-07-07T18:55:57.965981946Z] /usr/sbin/iptables, [--wait -t filter -C DOCKER-ISOLATION-STAGE-2 -o br-40eb041fff2c -j DROP]
DEBU[2023-07-07T18:55:57.967378032Z] /usr/sbin/iptables, [--wait -t filter -I DOCKER-ISOLATION-STAGE-2 -o br-40eb041fff2c -j DROP]
DEBU[2023-07-07T18:55:57.968765518Z] Network (40eb041) restored
DEBU[2023-07-07T18:55:57.969000632Z] /usr/sbin/iptables, [--wait -t nat -C POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE]
DEBU[2023-07-07T18:55:57.970363516Z] /usr/sbin/iptables, [--wait -t nat -C DOCKER -i docker0 -j RETURN]
DEBU[2023-07-07T18:55:57.971877409Z] /usr/sbin/iptables, [--wait -t nat -I DOCKER -i docker0 -j RETURN]
DEBU[2023-07-07T18:55:57.973184090Z] /usr/sbin/iptables, [--wait -t nat -C POSTROUTING -m addrtype --src-type LOCAL -o docker0 -j MASQUERADE]
DEBU[2023-07-07T18:55:57.974769688Z] /usr/sbin/iptables, [--wait -D FORWARD -i docker0 -o docker0 -j DROP]
DEBU[2023-07-07T18:55:57.976463292Z] /usr/sbin/iptables, [--wait -t filter -C FORWARD -i docker0 -o docker0 -j ACCEPT]
DEBU[2023-07-07T18:55:57.978108393Z] /usr/sbin/iptables, [--wait -t filter -C FORWARD -i docker0 ! -o docker0 -j ACCEPT]
DEBU[2023-07-07T18:55:57.979595385Z] /usr/sbin/iptables, [--wait -t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]
DEBU[2023-07-07T18:55:57.981135780Z] /usr/sbin/iptables, [--wait -t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]
DEBU[2023-07-07T18:55:57.982903789Z] /usr/sbin/iptables, [--wait -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8]
DEBU[2023-07-07T18:55:57.984379980Z] /usr/sbin/iptables, [--wait -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8]
DEBU[2023-07-07T18:55:57.985800067Z] /usr/sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -j DOCKER]
DEBU[2023-07-07T18:55:57.987381265Z] /usr/sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -j DOCKER]
DEBU[2023-07-07T18:55:57.988918159Z] /usr/sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT]
DEBU[2023-07-07T18:55:57.990569961Z] /usr/sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT]
DEBU[2023-07-07T18:55:57.992523882Z] /usr/sbin/iptables, [--wait -t filter -C FORWARD -j DOCKER-ISOLATION-STAGE-1]
DEBU[2023-07-07T18:55:57.993894966Z] /usr/sbin/iptables, [--wait -D FORWARD -j DOCKER-ISOLATION-STAGE-1]
DEBU[2023-07-07T18:55:57.995232949Z] /usr/sbin/iptables, [--wait -I FORWARD -j DOCKER-ISOLATION-STAGE-1]
DEBU[2023-07-07T18:55:57.996531229Z] /usr/sbin/iptables, [--wait -t filter -C DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2]
DEBU[2023-07-07T18:55:57.998001219Z] /usr/sbin/iptables, [--wait -t filter -I DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2]
DEBU[2023-07-07T18:55:57.999244596Z] /usr/sbin/iptables, [--wait -t filter -C DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP]
DEBU[2023-07-07T18:55:58.000712486Z] /usr/sbin/iptables, [--wait -t filter -I DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP]
DEBU[2023-07-07T18:55:58.002171776Z] Network (e7bbe28) restored
DEBU[2023-07-07T18:55:58.002526798Z] /usr/sbin/iptables, [--wait -t nat -C DOCKER -p tcp -d 0/0 --dport 443 -j DNAT --to-destination 172.18.0.2:443 ! -i br-40eb041fff2c]
DEBU[2023-07-07T18:55:58.004986950Z] /usr/sbin/iptables, [--wait -t nat -A DOCKER -p tcp -d 0/0 --dport 443 -j DNAT --to-destination 172.18.0.2:443 ! -i br-40eb041fff2c]
DEBU[2023-07-07T18:55:58.007176784Z] /usr/sbin/iptables, [--wait -t filter -C DOCKER ! -i br-40eb041fff2c -o br-40eb041fff2c -p tcp -d 172.18.0.2 --dport 443 -j ACCEPT]
DEBU[2023-07-07T18:55:58.010413984Z] /usr/sbin/iptables, [--wait -t filter -A DOCKER ! -i br-40eb041fff2c -o br-40eb041fff2c -p tcp -d 172.18.0.2 --dport 443 -j ACCEPT]
DEBU[2023-07-07T18:55:58.013036646Z] /usr/sbin/iptables, [--wait -t nat -C POSTROUTING -p tcp -s 172.18.0.2 -d 172.18.0.2 --dport 443 -j MASQUERADE]
DEBU[2023-07-07T18:55:58.021809286Z] /usr/sbin/iptables, [--wait -t nat -C DOCKER -p tcp -d 0/0 --dport 80 -j DNAT --to-destination 172.18.0.2:80 ! -i br-40eb041fff2c]
DEBU[2023-07-07T18:55:58.024442548Z] /usr/sbin/iptables, [--wait -t nat -A DOCKER -p tcp -d 0/0 --dport 80 -j DNAT --to-destination 172.18.0.2:80 ! -i br-40eb041fff2c]
DEBU[2023-07-07T18:55:58.026232659Z] /usr/sbin/iptables, [--wait -t filter -C DOCKER ! -i br-40eb041fff2c -o br-40eb041fff2c -p tcp -d 172.18.0.2 --dport 80 -j ACCEPT]
DEBU[2023-07-07T18:55:58.028130676Z] /usr/sbin/iptables, [--wait -t filter -A DOCKER ! -i br-40eb041fff2c -o br-40eb041fff2c -p tcp -d 172.18.0.2 --dport 80 -j ACCEPT]
DEBU[2023-07-07T18:55:58.029806379Z] /usr/sbin/iptables, [--wait -t nat -C POSTROUTING -p tcp -s 172.18.0.2 -d 172.18.0.2 --dport 80 -j MASQUERADE]
DEBU[2023-07-07T18:55:58.037786271Z] Endpoint (eb43f00) restored to network (40eb041)
DEBU[2023-07-07T18:55:58.042775178Z] Allocating IPv4 pools for network crhost-proxy (40eb041fff2c1784af2fffcfeb0375a1dcf108a57ea48bd9fcc21fd4ace06746)
DEBU[2023-07-07T18:55:58.042891385Z] RequestPool(LocalDefault, 172.18.0.0/16, , map[], false)
DEBU[2023-07-07T18:55:58.042998392Z] RequestAddress(LocalDefault/172.18.0.0/16, 172.18.0.1, map[RequestAddressType:com.docker.network.gateway])
DEBU[2023-07-07T18:55:58.043114599Z] Request address PoolID:172.18.0.0/16 Bits: 65536, Unselected: 65534, Sequence: (0x80000000, 1)->(0x0, 2046)->(0x1, 1)->end Curr:0 Serial:false PrefAddress:172.18.0.1
DEBU[2023-07-07T18:55:58.043505223Z] Assigning addresses for endpoint cr-proxy's interface on network crhost-proxy
DEBU[2023-07-07T18:55:58.043599629Z] RequestAddress(LocalDefault/172.18.0.0/16, 172.18.0.2, map[])
DEBU[2023-07-07T18:55:58.043684434Z] Request address PoolID:172.18.0.0/16 Bits: 65536, Unselected: 65533, Sequence: (0xc0000000, 1)->(0x0, 2046)->(0x1, 1)->end Curr:0 Serial:false PrefAddress:172.18.0.2
DEBU[2023-07-07T18:55:58.044068558Z] Allocating IPv4 pools for network bridge (e7bbe281e063fbf7cff8fe4dd468c98bbb432e447913dfac7fb177a3dc20c224)
DEBU[2023-07-07T18:55:58.044144663Z] RequestPool(LocalDefault, 172.17.0.0/16, , map[], false)
DEBU[2023-07-07T18:55:58.044201866Z] RequestAddress(LocalDefault/172.17.0.0/16, 172.17.0.1, map[RequestAddressType:com.docker.network.gateway])
DEBU[2023-07-07T18:55:58.044252569Z] Request address PoolID:172.17.0.0/16 Bits: 65536, Unselected: 65534, Sequence: (0x80000000, 1)->(0x0, 2046)->(0x1, 1)->end Curr:0 Serial:false PrefAddress:172.17.0.1
DEBU[2023-07-07T18:55:58.044951612Z] /usr/sbin/iptables, [--wait -t nat -C OUTPUT -d 127.0.0.11 -j DOCKER_OUTPUT]
DEBU[2023-07-07T18:55:58.046358999Z] /usr/sbin/iptables, [--wait -t nat -F DOCKER_OUTPUT]
DEBU[2023-07-07T18:55:58.047560373Z] /usr/sbin/iptables, [--wait -t nat -C POSTROUTING -d 127.0.0.11 -j DOCKER_POSTROUTING]
DEBU[2023-07-07T18:55:58.048855853Z] /usr/sbin/iptables, [--wait -t nat -F DOCKER_POSTROUTING]
DEBU[2023-07-07T18:55:58.050030725Z] /usr/sbin/iptables, [--wait -t nat -I DOCKER_OUTPUT -d 127.0.0.11 -p udp --dport 53 -j DNAT --to-destination 127.0.0.11:33982]
DEBU[2023-07-07T18:55:58.051836136Z] /usr/sbin/iptables, [--wait -t nat -I DOCKER_POSTROUTING -s 127.0.0.11 -p udp --sport 33982 -j SNAT --to-source :53]
DEBU[2023-07-07T18:55:58.053549242Z] /usr/sbin/iptables, [--wait -t nat -I DOCKER_OUTPUT -d 127.0.0.11 -p tcp --dport 53 -j DNAT --to-destination 127.0.0.11:38945]
DEBU[2023-07-07T18:55:58.055260747Z] /usr/sbin/iptables, [--wait -t nat -I DOCKER_POSTROUTING -s 127.0.0.11 -p tcp --sport 38945 -j SNAT --to-source :53]
INFO[2023-07-07T18:55:58.057388779Z] there are running containers, updated network configuration will not take affect
DEBU[2023-07-07T18:55:58.057598892Z] starting container                            container=af36b7292360b6e372a58551fe52bc51248853851af42526cf8a549ca08d72a7
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x55c06be7e000]

goroutine 196 [running]:
github.com/docker/docker/daemon.(*Daemon).prepareMountPoints(0xc000c291d0?, 0xc000b66f00)
        /go/src/github.com/docker/docker/daemon/mounts.go:24 +0x1c0
github.com/docker/docker/daemon.(*Daemon).restore.func5(0xc000b66f00, 0xc000b66f00?)
        /go/src/github.com/docker/docker/daemon/daemon.go:552 +0x271
created by github.com/docker/docker/daemon.(*Daemon).restore
        /go/src/github.com/docker/docker/daemon/daemon.go:530 +0x8d8
```

### PR DESCRIPTION
**Pull request by thaJeztah**
- fixes https://github.com/moby/moby/issues/45898
- fixes https://github.com/moby/moby/issues/45907
- fixes https://github.com/docker/docker-ce-packaging/issues/919
- relates to https://github.com/moby/moby/pull/45754

The daemon.lazyInitializeVolume() function only handles restoring Volumes if a Driver is specified. The Container's MountPoints field may also contain other kind of mounts (e.g., bind-mounts). Those were ignored, and don't return an error; https://github.com/moby/moby/blob/1d9c8619cded4657af1529779c5771127e8ad0e7/daemon/volumes.go#L243-L252C2

However, the prepareMountPoints() assumed each MountPoint was a volume, and logged an informational message about the volume being restored; https://github.com/moby/moby/blob/1d9c8619cded4657af1529779c5771127e8ad0e7/daemon/mounts.go#L18-L25

This would panic if the MountPoint was not a volume;

    github.com/docker/docker/daemon.(*Daemon).prepareMountPoints(0xc00054b7b8?, 0xc0007c2500)
            /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/mounts.go:24 +0x1c0
    github.com/docker/docker/daemon.(*Daemon).restore.func5(0xc0007c2500, 0x0?)
            /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/daemon.go:552 +0x271
    created by github.com/docker/docker/daemon.(*Daemon).restore
            /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/daemon.go:530 +0x8d8
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x564e9be4c7c0]

This issue was introduced in 647c2a6cdd86d79230df1bf690d0b6a2930d6db2

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Ah, dang failing on rootless; 

```
=== FAIL: amd64.integration.daemon TestLiveRestore/volume_references/container_with_bind-mounts (0.00s)
    daemon_test.go:449: assertion failed: error is not nil: Error response from daemon: invalid mount config for type "bind": stat /tmp/TestLiveRestorevolume_referencescontainer_with_bind-mounts645691285/001: permission denied
        --- FAIL: TestLiveRestore/volume_references/container_with_bind-mounts (0.00s)
```

File: daemon/mounts.go [hunk 1]
```diff
@@ -18,6 +18,10 @@ func (daemon *Daemon) prepareMountPoints(container *container.Container) error {
 		if err := daemon.lazyInitializeVolume(container.ID, config); err != nil {
 			return err
 		}
+		if config.Volume == nil {
```
Comment (neersighted) [inline daemon/mounts.go:21]: This looks to be the best fix for now; though we should probably come up with a better interface for mountpoints (e.g. a method to check if they're volume-like/convert them into a volume), since they currently feel like a very leaky abstraction.

**Review by neersighted — APPROVED** [review]

**Review by cpuguy83 — APPROVED** [review]
