### PR TITLE
Allocate resources for server API before daemon creation

### LINKED ISSUE #15912: ServeAPI error: is a directory
New docker nodes that I bring up are getting this error. Any suggestions or ideas?

I've tried it now on two completely fresh boxes. This is Docker 1.7.1

Note: because Linode uses custom kernels, I've always fallen back to devicemapper since aufs support isn't possible without a bootloader.

```
root@localhost:~# docker -d
WARN[0000] Udev sync is not supported. This will lead to unexpected behavior, data loss and errors. For more information, see https://docs.docker.com/reference/commandline/cli/#daemon-storage-driver-option
ERRO[0000] ServeAPI error: is a directory
INFO[0000] [graphdriver] using prior storage driver "devicemapper"
WARN[0000] Running modprobe bridge nf_nat failed with message: , error: exit status 1
WARN[0000] Your kernel does not support swap memory limit.
INFO[0000] Loading containers: start.
......ERRO[0000] Error unmounting device 90562e5df6b554a1bc41196f6c24f1d9bdd452818377913773b475d940839897: UnmountDevice: device not-mounted id 90562e5df6b554a1bc41196f6c24f1d9bdd452818377913773b475d940839897
ERRO[0000] error locating network id f4428f1834021aaba328334c1dd2d56279cf04f9c88215658111e15ce84d725a: network f4428f1834021aaba328334c1dd2d56279cf04f9c88215658111e15ce84d725a not found
ERRO[0000] Error unmounting device 90562e5df6b554a1bc41196f6c24f1d9bdd452818377913773b475d940839897: UnmountDevice: device not-mounted id 90562e5df6b554a1bc41196f6c24f1d9bdd452818377913773b475d940839897

INFO[0000] Loading containers: done.
INFO[0000] Daemon has completed initialization
INFO[0000] Docker daemon                                 commit=786b29d execdriver=native-0.2 graphdriver=devicemapper version=1.7.1
ERRO[0001] Error during graph storage driver.Cleanup(): device or resource busy
ERRO[0001] remove /var/run/docker.pid: no such file or directory
FATA[0001] Shutting down due to ServeAPI error: is a directory
```

### PR DESCRIPTION
**Pull request by LK4D4**
It prevents occupying of those resources (ports, unix-sockets) by
containers.
Also fixed false-positive test for that case.

Fix #15912

### CODE REVIEW

**Comment by runcom** [comment]
LGTM

File: integration-cli/docker_cli_daemon_test.go [hunk 1]
```diff
@@ -1462,7 +1462,7 @@ func (s *DockerDaemonSuite) TestDaemonRestartWithSocketAsVolume(c *check.C) {
 
 	socket := filepath.Join(s.d.folder, "docker.sock")
 
-	out, err := s.d.Cmd("run", "-d", "-v", socket+":/sock", "busybox")
+	out, err := s.d.Cmd("run", "-d", "--restart=always", "-v", socket+":/sock", "busybox")
```
Comment (vdemeester) [inline integration-cli/docker_cli_daemon_test.go]: Why this change ? :sweat_smile:

Comment (LK4D4) [inline integration-cli/docker_cli_daemon_test.go]: "Also fixed false-positive test for that case." from top-comment. Sorry I wasn't too specific.

Comment (vdemeester) [inline integration-cli/docker_cli_daemon_test.go]: oohh ok :+1: :stuck_out_tongue_closed_eyes:

**Comment by vdemeester** [comment]
LGTM 🐼

**Comment by runcom** [comment]
@LK4D4 something wrong with this patch, compiled a dynbinary, restarting the daemon with `sudo systemctl restart docker` hangs till it fails with:

```
Oct 06 02:17:00 localhost.localdomain systemd[1]: docker.service start operation timed out. Terminating.
Oct 06 02:17:00 localhost.localdomain systemd[1]: docker.service: main process exited, code=exited, status=2/INVALIDA
Oct 06 02:17:00 localhost.localdomain systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has failed.
-- 
-- The result is failed.
Oct 06 02:17:00 localhost.localdomain systemd[1]: Unit docker.service entered failed state.
```

Reverting this will make everything working again :/
if  I do a strace while it's trying to start I get the following gist https://gist.github.com/runcom/a6194e9d71783b068e54

**Comment by LK4D4** [comment]
@runcom I'll try, thanks for report.
