### PR TITLE
IPAM: handle subnets bigger than "/64"

### LINKED ISSUE #21199: `docker run --ip6` does not work properly when IPv6 prefix is shorter (larger) than /64
---
## BUG REPORT INFORMATION

**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:52:22 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:52:22 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 49
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-253:0-4980835-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.413 GB
 Data Space Total: 107.4 GB
 Data Space Available: 66.86 GB
 Metadata Space Used: 3.715 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.109 (2015-09-22)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.4-301.fc23.x86_64
Operating System: Fedora 23 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.61 GiB
Name: rayson-blackchan.localdomain
ID: RUBG:PGRF:DNLS:CFE4:SVH7:EU3U:4R3F:PJBX:GUYM:DEOE:WX7O:YC4Z

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Steps to reproduce the issue:**
1. Create a new bridge network

```
sudo brctl addbr br-ctn
docker network create \
  -d bridge --subnet=fd12:3456:7890::/48 --gateway=fd12:3456:7890::1 \
  -o "com.docker.network.bridge.name"="br-ctn" \
  -o "com.docker.network.enable_ipv6"=1 \
  testnet
```
1. Launch a container on this network

```
docker run -ti --net testnet --ip6 fd12:3456:7890:abcd:ef12:3456:7890:abcd debian:7 /bin/bash

```

**Describe the results you received:**

The IPv6 address assigned to the container is incorrect.

```
$ docker network inspect testnet 
[
    {
        "Name": "testnet",
        "Id": "7705574587cd3ba0209b1dfee5257be15a0d135c8a6692464f58f86a82a5263b",
        "Scope": "local",
        "Driver": "bridge",
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1/16"
                },
                {
                    "Subnet": "fd12:3456:7890::/48",
                    "Gateway": "fd12:3456:7890::1"
                }
            ]
        },
        "Containers": {
            "65b8cb4ef8a98d538b132ada9a61d35a6941105419b480035a04479cb5419819": {
                "Name": "distracted_galileo",
                "EndpointID": "7927f09895017f3998865e1b7dfab1f39d47380fd51f5f01d0972328ab02ee01",
                "MacAddress": "02:42:ac:12:00:02",
                "IPv4Address": "172.18.0.2/16",
                "IPv6Address": "fd12:3456:7890:0:ef12:3456:7890:abcd/48"
            }
        },
        "Options": {
            "com.docker.network.bridge.name": "br-ctn",
            "com.docker.network.enable_ipv6": "1"
        }
    }
]

root@65b8cb4ef8a9:/# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
15: eth0@if16: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP 
    link/ether 02:42:ac:12:00:02 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.2/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fd12:3456:7890:0:ef12:3456:7890:abcd/48 scope global nodad 
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe12:2/64 scope link tentative 
       valid_lft forever preferred_lft forever

```

**Describe the results you expected:**
The IPv6 address assigned to my container is `fd12:3456:7890:0:ef12:3456:7890:abcd/48`, which is not what expected  `fd12:3456:7890:abcd:ef12:3456:7890:abcd/48`.

**Additional information you deem important (e.g. issue happens only occasionally):**
Always

### LINKED ISSUE #35195: Containers not accessible over IPv6 from internet, gateway incorrect.
**Description**

Setup Docker with IPv6 (tested on a fresh machine), where the IPv6 gateway is not at the traditional address. `daemon.json` with following content:

```json
{
  "storage-driver": "overlay2",
  "ipv6": true,
  "fixed-cidr-v6": "2001:41d0:1:dbc4::/56",
  "default-gateway-v6": "2001:41d0:1:dbff:ff:ff:ff:ff"
}
```

On the host: 

`ifconfig` returns:

```bash
docker0   Link encap:Ethernet  HWaddr 02:42:c1:7e:25:b4
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::1/64 Scope:Link
          inet6 addr: 2001:41d0:1:db00::1/56 Scope:Global
          inet6 addr: fe80::42:c1ff:fe7e:25b4/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:91 errors:0 dropped:0 overruns:0 frame:0
          TX packets:95 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:9003 (9.0 KB)  TX bytes:9523 (9.5 KB)

eth0      Link encap:Ethernet  HWaddr 00:25:90:50:d5:10
          inet addr:91.121.154.196  Bcast:91.121.154.255  Mask:255.255.255.0
          inet6 addr: fe80::225:90ff:fe50:d510/64 Scope:Link
          inet6 addr: 2001:41d0:1:dbc4::1/56 Scope:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:4152393 errors:0 dropped:0 overruns:0 frame:0
          TX packets:288620 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:415777011 (415.7 MB)  TX bytes:29767545 (29.7 MB)
          Interrupt:16 Memory:fbce0000-fbd00000

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:2368 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2368 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:365057 (365.0 KB)  TX bytes:365057 (365.0 KB)

vethb9812af Link encap:Ethernet  HWaddr 66:bb:f0:5b:71:f8
          inet6 addr: fe80::64bb:f0ff:fe5b:71f8/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:42 errors:0 dropped:0 overruns:0 frame:0
          TX packets:60 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:5327 (5.3 KB)  TX bytes:5433 (5.4 KB)

vethf7f5125 Link encap:Ethernet  HWaddr 32:d2:9f:d4:23:64
          inet6 addr: fe80::30d2:9fff:fed4:2364/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:41 errors:0 dropped:0 overruns:0 frame:0
          TX packets:64 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:4302 (4.3 KB)  TX bytes:6764 (6.7 KB)
```

`ip -6 route` returns:
```bash
2001:41d0:1:dbff:ff:ff:ff:ff dev eth0  metric 1024  pref medium
2001:41d0:1:db00::/56 dev docker0  proto kernel  metric 256  pref medium
2001:41d0:1:db00::/56 dev eth0  proto kernel  metric 256  pref medium
2001:41d0:1:db00::/56 dev docker0  metric 1024  pref medium
fe80::/64 dev docker0  proto kernel  metric 256  pref medium
fe80::/64 dev vethf7f5125  proto kernel  metric 256  pref medium
fe80::/64 dev vethb9812af  proto kernel  metric 256  pref medium
fe80::/64 dev eth0  proto kernel  metric 256  pref medium
default via 2001:41d0:1:dbff:ff:ff:ff:ff dev eth0  metric 1024  pref medium
```

`ip -6 addr` returns:
```bash
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 state UNKNOWN qlen 1
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 2001:41d0:1:dbc4::1/56 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::225:90ff:fe50:d510/64 scope link
       valid_lft forever preferred_lft forever
4: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP
    inet6 2001:41d0:1:db00::1/56 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::42:c1ff:fe7e:25b4/64 scope link
       valid_lft forever preferred_lft forever
    inet6 fe80::1/64 scope link
       valid_lft forever preferred_lft forever
8: vethf7f5125@if7: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP
    inet6 fe80::30d2:9fff:fed4:2364/64 scope link
       valid_lft forever preferred_lft forever
10: vethb9812af@if9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP
    inet6 fe80::64bb:f0ff:fe5b:71f8/64 scope link
       valid_lft forever preferred_lft forever
```
The gateway is at an address provided by my server provider/ISP and cannot be changed.

In a docker container:

executing `ip -6 route` returns:
```bash
2001:41d0:1:db00::/56 dev eth0  metric 256
fe80::/64 dev eth0  metric 256
default via 2001:41d0:1:db00:ff:ff:ff:ff dev eth0  metric 1024
unreachable default dev lo  metric -1  error -101
ff00::/8 dev eth0  metric 256
unreachable default dev lo  metric -1  error -101
```

executing `ip -6 addr` returns:
```bash
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 state UNKNOWN qlen 1
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
7: eth0@if8: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 state UP
    inet6 2001:41d0:1:db00::242:ac11:2/56 scope global flags 02
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe11:2/64 scope link
       valid_lft forever preferred_lft forever
```

Executing `docker inspect {containerId}` for the container in question returns (cut to pertinent info)

```json
[
    {
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "0cd3f4b2f9ca653fa8c7782e4e839c017894d0d30aa5d7a2cdd314964782afd9",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/0cd3f4b2f9ca",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "4a5df933f52c2789838f0d4a1822df997a30c988894982bdcd29d4cc3c3ccdd5",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "2001:41d0:1:db00:0:242:ac11:2",
            "GlobalIPv6PrefixLen": 56,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "2001:41d0:1:db00:ff:ff:ff:ff",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "71e4ff9707a415ec13fecf2bce4bffe1042b0718a9c6005455970ea4d87889db",
                    "EndpointID": "4a5df933f52c2789838f0d4a1822df997a30c988894982bdcd29d4cc3c3ccdd5",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "2001:41d0:1:db00:ff:ff:ff:ff",
                    "GlobalIPv6Address": "2001:41d0:1:db00:0:242:ac11:2",
                    "GlobalIPv6PrefixLen": 56,
                    "MacAddress": "02:42:ac:11:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

I will highlight that the `IPv6Gateway` is returning as `2001:41d0:1:db00:ff:ff:ff:ff` which does not match what I have set in my `daemon.json`

**Describe the results you received:**

I will highlight that the `IPv6Gateway` is returning as `2001:41d0:1:db00:ff:ff:ff:ff` which does not match what I have set in my `daemon.json`

**Describe the results you expected:**

Containers should respond to requests on exposed ports over the internet.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:17 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:11 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 17.06.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-96-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.66GiB
Name: docker.example.com
ID: S5F3:T2DN:SGEJ:EAG2:PNK3:HMHY:YEZL:BYXK:MHCK:6SW7:KOGP:TTPO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical server, provided by OVH/Kimsufi.

### LINKED ISSUE #45402: statically assigned ipv6 address only last(?) block into account
### Description

It seems like any other then the last block in an ipv6 address is ignored when trying to assign static IPs.

### Reproduce

```
# create a network with v6 enabled
mava@server01:~/projects/schema-server$ docker network create --ipv6 --subnet fd1a:b128::/32 mynet123
ebba0bf437a9d8f9ff4f1e245c3b09e65cbaa7c58ad235efd7bdd14bb91b0e38
# create first container
mava@server01:~/projects/schema-server$ docker run --name u1 -d --net mynet123 --ip6 fd1a:b128:5901::101 ubuntu sleep 999
ca4d0eaf28ba46a61cd75a17ff73b4679d2c2f3624e739dc4fca7a190763c6a7
# create second container
mava@server01:~/projects/schema-server$ docker run --name u2 -d --net mynet123 --ip6 fd1a:b128:5902::101 ubuntu sleep 999
50dbecfb20b881cddd9488839d464c7a10d63f72cb5a2261824e8db8db2f863c
docker: Error response from daemon: Address already in use.
```

Also after removing the u1 container and starting u2 alone the assigned address is incorrect
```
mava@server01:~/projects/schema-server$ docker run --name u2 -d --net mynet123 --ip6 fd1a:b128:5902::101 ubuntu sleep 999
b1690c53cde7cbbe154e84cfbb6e13d0a44eccdc1f0fb9d615ce6e50646189eb
mava@server01:~/projects/schema-server$ docker inspect u2 | jq ".[0].NetworkSettings.
Networks"
{
  "mynet123": {
    "IPAMConfig": {
      "IPv6Address": "fd1a:b128:5902::101"
    },
    "Links": null,
    "Aliases": [
      "b1690c53cde7"
    ],
    "NetworkID": "e55acf5bb5a72a755d791c7b6dcde060e7bba33c3ae7c352c5c48d63b40aa9f4",
    "EndpointID": "b908bdb736888b861e1458e46bc5301bd4c7e8cb3dba0af3d016883c7af201bb",
    "Gateway": "172.28.0.1",
    "IPAddress": "172.28.0.2",
    "IPPrefixLen": 16,
    "IPv6Gateway": "fd1a:b128::1",
    "GlobalIPv6Address": "fd1a:b128::101",
    "GlobalIPv6PrefixLen": 32,
    "MacAddress": "02:42:ac:1c:00:02",
    "DriverOpts": null
  }
}
```

### Expected behavior

u1 should have ipv6 address fd1a:b128:5901::101 and u2 should have ipv6 address fd1a:b128:5902::101 assigned.

### docker version

```bash
Client: Docker Engine - Community
 Version:           23.0.4
 API version:       1.42
 Go version:        go1.19.8
 Git commit:        f480fb1
 Built:             Fri Apr 14 10:32:03 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.4
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.8
  Git commit:       cbce331
  Built:            Fri Apr 14 10:32:03 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:        v1.1.5-0-gf19387a
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 32
  Running: 0
  Paused: 0
  Stopped: 32
 Images: 26
 Server Version: 23.0.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-70-generic
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 62.7GiB
 Name: server01
 ID: 4d9b7b88-00a5-4658-9a37-a1d6f11f745d
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

_No response_

### LINKED ISSUE #48527: Gateway IP Address is wrong when using small IPv6 prefixes for subnets
### Description

When configuring manually a gateway IP address on a subnet, if the subnet is large enough, IP address actually used is not the expected one despite `docker inspect` displaying it.

### Reproduce

1. Create the following `compose.yaml`  and run `docker compose up`
```yaml
services:
  nginx:
    image: nginx
    networks:
      n1:
      n2:
networks:
  n1:
    name: n1
    enable_ipv6: true
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-n1
    ipam:
      driver: default
      config:
        - subnet: fd32:f7ff:393f::/48
          ip_range: fd32:f7ff:393f::/64
          gateway: fd32:f7ff:393f:1::1
  n2:
    name: n2
    enable_ipv6: true
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-n2
    ipam:
      driver: default
      config:
        - subnet: fd83:b442:5c7e::/64
          ip_range: fd83:b442:5c7e:0:8000::/65
          gateway: fd83:b442:5c7e:0:8000::1
```
2.  Check gateway configuration using docker inspect:
2.1. `docker inspect n1` (gateway IP address is correct)
```text
[
    {
        "Name": "n1",
        "Id": "b2669ae9d9da74363ca976e19b61bd526223eded5fcef02158d9aa88cf107ad1",
        "Created": "2024-09-18T15:10:44.338593812+02:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": true,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "fd32:f7ff:393f::/48",
                    "IPRange": "fd32:f7ff:393f::/64",
                    "Gateway": "fd32:f7ff:393f:1::1"
                },
                {
                    "Subnet": "10.0.1.0/24",
                    "Gateway": "10.0.1.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "d598e5148c48b37a297440b7b0158b74848e0f3b1f7db11c1a9237b68e1e4b87": {
                "Name": "test-docker-nginx-1",
                "EndpointID": "48766a6ec42faf995f7ef385a98127a23920eed1236d0a4bd0cb6254bede4314",
                "MacAddress": "02:42:0a:00:01:02",
                "IPv4Address": "10.0.1.2/24",
                "IPv6Address": "fd32:f7ff:393f::2/48"
            }
        },
        "Options": {
            "com.docker.network.bridge.name": "br-n1"
        },
        "Labels": {
            "com.docker.compose.network": "n1",
            "com.docker.compose.project": "test-docker",
            "com.docker.compose.version": "2.29.2"
        }
    }
]
```
2.2. `docker inspect n2` (gateway IP address is correct)
```text
[
    {
        "Name": "n2",
        "Id": "642a85683be7976a3c0d4f8382d97cd5b4cedf74580ac7067b8e442312ca4f8c",
        "Created": "2024-09-18T15:10:44.669753347+02:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": true,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "fd83:b442:5c7e::/64",
                    "IPRange": "fd83:b442:5c7e:0:8000::/65",
                    "Gateway": "fd83:b442:5c7e:0:8000::1"
                },
                {
                    "Subnet": "10.0.2.0/24",
                    "Gateway": "10.0.2.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "d598e5148c48b37a297440b7b0158b74848e0f3b1f7db11c1a9237b68e1e4b87": {
                "Name": "test-docker-nginx-1",
                "EndpointID": "fbcef6fec5dc32aebd7222f8d5ba95278d8a4492d5070b81982390f6e303173d",
                "MacAddress": "02:42:0a:00:02:02",
                "IPv4Address": "10.0.2.2/24",
                "IPv6Address": "fd83:b442:5c7e:0:8000::/64"
            }
        },
        "Options": {
            "com.docker.network.bridge.name": "br-n2"
        },
        "Labels": {
            "com.docker.compose.network": "n2",
            "com.docker.compose.project": "test-docker",
            "com.docker.compose.version": "2.29.2"
        }
    }
]
```
3.  Check actual gateway ip using iproute2:
3.1. `ip a show br-n1` (here gateway IP address is not correct)
```text
6031: br-n1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:d8:26:28:16 brd ff:ff:ff:ff:ff:ff
    inet 10.0.1.1/24 brd 10.0.1.255 scope global br-n1
       valid_lft forever preferred_lft forever
    inet6 fd32:f7ff:393f::1/48 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::42:d8ff:fe26:2816/64 scope link 
       valid_lft forever preferred_lft forever
```
3.2. `ip a show br-n2` (here gateway IP address is correct)
```text
6032: br-n2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:8a:47:88:dc brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.1/24 brd 10.0.2.255 scope global br-n2
       valid_lft forever preferred_lft forever
    inet6 fd83:b442:5c7e:0:8000::1/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::42:8aff:fe47:88dc/64 scope link 
       valid_lft forever preferred_lft forever
```

### Expected behavior

Step 3.1. (`ip a show br-n1`) should show `fd32:f7ff:393f:1::1/48` instead of `fd32:f7ff:393f::1/48`
```diff
6031: br-n1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:d8:26:28:16 brd ff:ff:ff:ff:ff:ff
    inet 10.0.1.1/24 brd 10.0.1.255 scope global br-n1
       valid_lft forever preferred_lft forever
-    inet6 fd32:f7ff:393f::1/48 scope global
+    inet6 fd32:f7ff:393f:1::1/48 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::42:d8ff:fe26:2816/64 scope link 
       valid_lft forever preferred_lft forever
```

### docker version

```bash
Client: Docker Engine - Community
 Version:           27.2.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        9e34c9b
 Built:             Fri Sep  6 12:08:06 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.2.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       8b539b8
  Built:            Fri Sep  6 12:08:06 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.21
  GitCommit:        472731909fa34bd7bc9c087e4c27943f9835f111
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    27.2.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 31
 Server Version: 27.2.1
 Storage Driver: btrfs
  Btrfs: 
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 472731909fa34bd7bc9c087e4c27943f9835f111
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-25-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.29GiB
 Name: CometTail
 ID: b72da995-0839-4c58-afc5-a42b17d9b1ae
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 10.0.0.0/8, Size: 24
   Base: fd3f:f9ac:f32b::/48, Size: 64
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by robmry**
**- What I did**

- fix https://github.com/moby/moby/issues/21199
- fix https://github.com/moby/moby/issues/35195
- fix https://github.com/moby/moby/issues/45402
- fix https://github.com/moby/moby/issues/48527
- replaces the workaround added in https://github.com/moby/moby/pull/48322

The default IPAM allocator is unable to represent subnets larger than 64-bits (subnets with a smaller prefix), because it uses a Bitmap that's limited to 64-bits.

When it's used to represent a 64-bit subnet, the top address can't be allocated (because bitmap.Bitmap is initialised with the number of bits it needs to represent in a uint64, so it's one short).

The rest of the daemon doesn't know about these limitations, so strange things happen when a large IPv6 subnet is used. No errors are reported, addresses/subnets are just set up incorrectly.  The IPAM code calculates offsets into the bitmap itself, details it shouldn't need to understand and, because it's working on offsets into a range it doesn't always notice when it's asked to set a bit outside the range (see the notes about "offset" in https://github.com/moby/moby/pull/48319).

It's unusual to need a big subnet but, for example, it may be useful for modelling an ISP network, or an ISP's gateway may be in a "/56" subnet that's outside a 64-bit range used by hosts.

**- How I did it**

- Don't increment "unselected" in Bitmap when clearing a 0
  - Bug fix in the bitmap.Bitmap code
- Add addrset.AddrSet to track a set of IP addresses
  - A new internal package to track IP addresses.
  - It owns a `bitmap.Bitmap` for each range of up to 63-bits that has a bit set, within the subnet it's asked to represent.
- Use addrset.AddrSet instead of bitmap.Bitmap in IPAM

**- How to verify it**

New unit tests for `AddrSet`, plus existing tests (including the two "XFAIL" tests that now pass).

**- Description for the changelog**
```markdown changelog
- IPAM now handles subnets bigger than "/64".
```

### CODE REVIEW

File: libnetwork/bitmap/sequence.go [hunk 1]
```diff
@@ -481,14 +484,16 @@ func findSequence(head *sequence, bytePos uint64) (*sequence, *sequence, uint64,
 // A) block is first in current:         [prev seq] [new] [modified current seq] [next seq]
 // B) block is last in current:          [prev seq] [modified current seq] [new] [next seq]
 // C) block is in the middle of current: [prev seq] [curr pre] [new] [curr post] [next seq]
-func pushReservation(bytePos, bitPos uint64, head *sequence, release bool) *sequence {
+//
+// The bool return is true if the bit value was changed.
+func pushReservation(bytePos, bitPos uint64, head *sequence, release bool) (*sequence, bool) {
```
Comment (thaJeztah) [inline libnetwork/bitmap/sequence.go:489]: This would be a case where possibly a named output variable could be OK;


```suggestion
// The bool return is true if the bit value was changed.
func pushReservation(bytePos, bitPos uint64, head *sequence, release bool) (_ *sequence, changed bool) {
```

or

```suggestion
// The bool return is true if the bit value was changed.
func pushReservation(bytePos, bitPos uint64, head *sequence, release bool) (newHead *sequence, changed bool) {
```

File: libnetwork/bitmap/sequence_test.go [hunk 2]
```diff
@@ -513,7 +513,7 @@ func TestPushReservation(t *testing.T) {
 	}
 
 	for n, i := range input {
-		mask := pushReservation(i.bytePos, i.bitPos, i.mask, false)
+		mask, _ := pushReservation(i.bytePos, i.bitPos, i.mask, false)
 		if !mask.equal(i.newMask) {
```
Comment (thaJeztah) [inline libnetwork/bitmap/sequence_test.go:517]: If we want to verify the new output var, I guess this could have something like;

```go
mask, changed := pushReservation(i.bytePos, i.bitPos, i.mask, false)
if mask.equal(i.mask) != changed {
....
```

Or something along those lines

File: libnetwork/ipams/defaultipam/allocator_test.go [hunk 3]
```diff
@@ -948,11 +944,7 @@ func assertGetAddress(t *testing.T, subnet string) {
 	)
 
 	sub := netip.MustParsePrefix(subnet)
-	ones, bits := sub.Bits(), sub.Addr().BitLen()
-	zeroes := bits - ones
-	numAddresses := 1 << uint(zeroes)
-
-	bm := bitmap.New(uint64(numAddresses))
+	bm := addrset.New(sub)
```
Comment (thaJeztah) [inline libnetwork/ipams/defaultipam/allocator_test.go:947]: Curious; can the new package fully replace (direct uses of) the  `bitmap` package? After this PR it's imported in 2 locations, so I was wondering if those would also switch over?

```bash
git grep '"github.com/docker/docker/libnetwork/bitmap"'
libnetwork/drivers/overlay/ovmanager/ovmanager.go:      "github.com/docker/docker/libnetwork/bitmap"
libnetwork/internal/addrset/addrset.go: "github.com/docker/docker/libnetwork/bitmap"
```

File: libnetwork/internal/addrset/addrset.go [hunk 4]
```diff
@@ -0,0 +1,198 @@
...
+	"strings"
+
+	"github.com/docker/docker/libnetwork/bitmap"
+	"github.com/docker/docker/libnetwork/internal/netiputil"
+	"github.com/docker/docker/libnetwork/ipbits"
+)
+
+var (
+	// ErrBadAddress is returned when a requested address is not in the pool
+	ErrBadAddress = errors.New("address not in pool")
```
Comment (thaJeztah) [inline libnetwork/internal/addrset/addrset.go:18]: Looks like this one is not used outside of the package, so could be un-exported, or should the other check in `getAddress` map this to some  `ipamapi` type? The `ipamapi` errors look to implement `errdefs` types, whereas this one doesn't 🤔

File: libnetwork/internal/addrset/addrset.go [hunk 5]
```diff
@@ -0,0 +1,198 @@
...
+	// ErrNotAvailable is returned when no more addresses are available to set
+	ErrNotAvailable = errors.New("address not available")
+	// ErrAllocated is returned when the specific address requested is already allocated
+	ErrAllocated = errors.New("address already allocated")
```
Comment (thaJeztah) [inline libnetwork/internal/addrset/addrset.go:22]: I guess I was wondering if we have some option to alias some of the types so that we don't have to introduce yet-another set of errors 😅, e.g.


```suggestion
	// ErrNotAvailable is returned when no more addresses are available to set
	ErrNotAvailable = ipamapi.ErrNoAvailableIPs
	// ErrAllocated is returned when the specific address requested is already allocated
	ErrAllocated = ipamapi.ErrIPAlreadyAllocated
```

or

```suggestion
	// ErrNotAvailable is returned when no more addresses are available to set
	ErrNotAvailable = bitmap.ErrBitAllocated
	// ErrAllocated is returned when the specific address requested is already allocated
	ErrAllocated = bitmap.ErrNoBitAvailable
```

(but the bitmap errors don't implement `errdefs` types)

File: libnetwork/bitmap/sequence.go (hunk 1 above)
Comment (robmry) [reply libnetwork/bitmap/sequence.go]: Done.

File: libnetwork/bitmap/sequence_test.go (hunk 2 above)
Comment (robmry) [reply libnetwork/bitmap/sequence_test.go]: Ok, done. (It's also tested by the new `AddrSet` unit tests clearing unset bits.)

File: libnetwork/ipams/defaultipam/allocator_test.go (hunk 3 above)
Comment (robmry) [reply libnetwork/ipams/defaultipam/allocator_test.go:947]: The overlay network's bitmap is tracking vlan ids (not IP addresses).

The other one is the new `AddrSet`, which is implemented using the bitmap.

File: libnetwork/internal/addrset/addrset.go (hunk 4 above)
Comment (robmry) [reply libnetwork/internal/addrset/addrset.go]: IPAM had a tendency to ask for addresses that weren't in the subnet it thought it was dealing with, and not notice the problem ... initially, I thought it might be useful for it to spot that happening, but didn't use it in the end. So, it's gone now.

File: libnetwork/internal/addrset/addrset.go (hunk 5 above)
Comment (robmry) [reply libnetwork/internal/addrset/addrset.go:20]: The bitmap error texts talk about "bits" being available, but this new package is dealing with a set of addresses. So, bitmap's error messages didn't really make sense - and maybe we'll want to represent the address set differently at some point.

It didn't seem right for `AddrSet` to return IPAM errors, even though it's only used by `defaultipam` at the moment. But if you think it should, I can do that? (Could make package `addrset` internal to `defaultipam` so that it can't be used by anything else?)

File: libnetwork/bitmap/sequence.go (hunk 1 above)
Comment (thaJeztah) [reply libnetwork/bitmap/sequence.go]: Thanks!

File: libnetwork/bitmap/sequence_test.go (hunk 2 above)
Comment (thaJeztah) [reply libnetwork/bitmap/sequence_test.go]: Ah, good call; thanks for updating, it was only a minor nit

File: libnetwork/ipams/defaultipam/allocator_test.go (hunk 3 above)
Comment (thaJeztah) [reply libnetwork/ipams/defaultipam/allocator_test.go:947]: Ah! Gotcha! Didn't go that deep comparing 👍

File: libnetwork/internal/addrset/addrset.go (hunk 5 above)
Comment (thaJeztah) [reply libnetwork/internal/addrset/addrset.go:20]: Yeah, it was mostly wishful thinking on this one; libnetwork had a bit of a tendency to define errors for everything, even for those not actually checked for; in some cases that led to tighter coupling than needed.

So I was looking if it would be possible somehow to get closer to our errdefs definitions for matching specific conditions, but otherwise keep things generic.

This is all internal, so not a huge deal (doesn't expand public APIs / contracts.

File: libnetwork/internal/addrset/addrset.go [hunk 6]
```diff
@@ -0,0 +1,195 @@
...
+	}
+	bit := netiputil.HostID(addr, as.prefixLenPerBitmap())
+	if err := bm.Set(bit); err != nil {
+		return fmt.Errorf("setting bit %d for %s in pool '%s': %w", bit, addr, as.pool, mapErr(err))
+	}
+	return nil
+}
+
+// AddAny adds an arbitrary address to the set, and returns that address. Or, if
+// no addresses are available, it returns a wrapped [ErrNotAvailable].
```
Comment (corhere) [inline libnetwork/internal/addrset/addrset.go:71]: Document the limitations of this function. An ErrNotAvailable returned from this function does not necessarily mean that all host IDs in the prefix have been allocated.

File: libnetwork/internal/addrset/addrset.go [hunk 7]
```diff
@@ -0,0 +1,195 @@
...
+	}
+	return ipbits.Add(as.pool.Addr(), ordinal, 0), nil
+}
+
+// AddAnyInRange adds an arbitrary address from ipr to the set, and returns that
+// address. Or, if no addresses are available, it returns a wrapped [ErrNotAvailable].
+// If ipr is not fully contained within the set's range, it returns an error.
+//
+// When serial=true, the set is scanned starting from the address following
+// the address most recently set by [AddrSet.SetAny] or [AddrSet.SetAnyInRange].
```
Comment (corhere) [inline libnetwork/internal/addrset/addrset.go:96]:
```suggestion
// the address most recently set by [AddrSet.AddAny] or [AddrSet.AddAnyInRange].
```

File: libnetwork/internal/addrset/addrset.go [hunk 8]
```diff
@@ -0,0 +1,195 @@
...
+	return AddrSet{
+		pool:    pool.Masked(),
+		bitmaps: map[netip.Prefix]*bitmap.Bitmap{},
+	}
+}
+
+// Add adds address addr to the set. If addr is already in the set, it returns a
+// wrapped [ErrAllocated]. If addr is not in the set's address range, it returns
+// an error.
+func (as AddrSet) Add(addr netip.Addr) error {
```
[the remark this answers is not in the document]
Comment (robmry) [reply libnetwork/internal/addrset/addrset.go]: Changed to pointers.

File: libnetwork/internal/addrset/addrset.go (hunk 6 above)
Comment (robmry) [reply libnetwork/internal/addrset/addrset.go:71]: As above.

File: libnetwork/internal/addrset/addrset.go (hunk 7 above)
Comment (robmry) [reply libnetwork/internal/addrset/addrset.go]: Fixed.

File: libnetwork/internal/addrset/addrset.go [hunk 9]
```diff
@@ -0,0 +1,195 @@
...
+// AddAny adds an arbitrary address to the set, and returns that address. Or, if
+// no addresses are available, it returns a wrapped [ErrNotAvailable].
+//
+// When serial=true, the set is scanned starting from the address following
+// the address most recently set by [AddrSet.SetAny] or [AddrSet.SetAnyInRange].
+func (as AddrSet) AddAny(serial bool) (netip.Addr, error) {
+	// If the pool has maxBitsPerBitmap or fewer, the key for the only bitmap is the pool's address.
+	// If there's more than one bitmap, they all have maxBitsPerBitmap. So, assume there's a free
+	// address in the bitmap keyed on the pool's address (no need to search other bitmaps, or work
+	// out if more bitmaps could be created).
```
[the remark this answers is not in the document]
Comment (robmry) [reply libnetwork/internal/addrset/addrset.go]: The "unsound" assumption would be that anything in libnetwork is capable of tracking, or needs to track, 2^63 different IP addresses (9,223,372,036,854,775,808 addresses). Let alone more than that.

But, for the overly ambitious or concerned, I've reworded and included it in the godoc comment.

**Comment by robmry** [comment]
I've added an extra commit, just to clarify the code that reserves network/broadcast addresses.

**Review by thaJeztah — APPROVED** [review]
LGTM

File: libnetwork/internal/addrset/addrset_test.go [hunk 10]
```diff
@@ -0,0 +1,215 @@
...
+	assert.Assert(t, err)
+	assert.Check(t, is.Len(as.bitmaps, 1))
+	bm := as.bitmaps[subnet.Masked()]
+	assert.Check(t, is.Equal(bm.Bits(), uint64(65536)))
+	assert.Check(t, is.Equal(bm.Unselected(), uint64(65534)))
+
+	// Add an address that's already present. Expect an error.
+	err = as.Add(netip.MustParseAddr("10.20.255.255"))
+	assert.Check(t, is.ErrorIs(err, ErrAllocated))
+	assert.Check(t, is.ErrorIs(err, ErrAllocated))
```
Comment (akerouanton) [inline libnetwork/internal/addrset/addrset_test.go:36]:
```suggestion
```

**Review by akerouanton — APPROVED** [review]
Small nit, otherwise LGTM

File: libnetwork/internal/addrset/addrset_test.go (hunk 10 above)
Comment (robmry) [reply libnetwork/internal/addrset/addrset_test.go]: Oops, thank you - fixed.
