### PR TITLE
awslogs: fix non-blocking log drop bug

### LINKED ISSUE #45217: non-blocking bug in AWSLogs driver code
### Impact to AWS Customers

**Amazon ECS for EC2 only**. Amazon ECS on Fargate is not affected because as explained below, the log driver is always started in blocking mode and is wrapped by a buffer in non-blocking mode.

This can be seen in the aws/amazon-ecs-shim-loggers-for-containerd code, it initially starts the log driver in blocking mode always:

1. AWSLogs driver options are configured without mode thus using the default blocking mode: https://github.com/aws/amazon-ecs-shim-loggers-for-containerd/blob/4bcb0f7126a3eee95a31d8a93e3b0a0d2f7c3e91/logger/awslogs/logger.go#L132
2. Failure to create group/stream is logged and causes exit: https://github.com/aws/amazon-ecs-shim-loggers-for-containerd/blob/4bcb0f7126a3eee95a31d8a93e3b0a0d2f7c3e91/logger/awslogs/logger.go#L92
3. For non-blocking mode, after the log driver is initialized, it is wrapped by the shim logger implementation of the RingBuffer (largely copied from Docker code base): https://github.com/aws/amazon-ecs-shim-loggers-for-containerd/blob/4bcb0f7126a3eee95a31d8a93e3b0a0d2f7c3e91/logger/awslogs/logger.go#L108

See this comment for testing data on the bug's impact to log loss: https://github.com/moby/moby/issues/45217#issuecomment-1509272084

### Summary

Currently `non-blocking` mode has a bug that can cause unnecessary log loss in the AWSLogs driver and thus may not be safe for customers to use. Unless customers configure a large enough value for both `max-buffer-size` and `awslogs-max-buffered-events`, logs can be lost. As explained in the deep dive section below, setting `awslogs-max-buffered-events` should not be required to prevent log loss. 

This bug occurs because the AWSLogs driver code attempts to [handle the `non-blocking` behavior itself](https://github.com/moby/moby/blob/master/daemon/logger/awslogs/cloudwatchlogs.go#L440-L447) and drops events if its internal buffer is full. However, `non-blocking` mode is supposed to be implemented purely by the Docker [RingBuffer](https://github.com/moby/moby/blob/master/daemon/logger/ring.go#L160) which wraps the log driver. 

When this bug causes log loss, the following message will be logged in the Docker Daemon logs:

```
Mar 02 21:40:55 ip-10-192-11-106.us-west-2.compute.internal dockerd[12093]: 
 time="2023-03-02T21:40:55.527136424Z" 
 level=error msg="Error writing log message" 
 driver=awslogs error=" buffer is full"
```

### Deep Dive Explanation

AWSLogs buffering (3)

The above diagram shows the series of buffers when the AWSLogs driver is used in `non-blocking` mode. The `non-blocking` feature ensures that the stdout and stderr pipes do not block in the application container. This is achieved via the Docker [RingBuffer](https://github.com/moby/moby/blob/master/daemon/logger/ring.go#L160) which holds messages before the AWSLogs driver code is ready to accept them. While the Docker docs claim the oldest messages are removed when this buffer fills up, it is actually the newest message, see: [moby/moby:45200](https://github.com/moby/moby/issues/45200). The AWSLogs driver ingests the messages via its ingestion buffer which can be configured with `awslogs-max-buffered-events`. They are then moved to its send buffer for the API call to `cloudwatch:PutLogEvents`. 

The non-blocking behavior is implemented in Docker in the [RingBuffer](https://github.com/moby/moby/blob/master/daemon/logger/ring.go#L160). The [RingBuffer](https://github.com/moby/moby/blob/master/daemon/logger/ring.go#L160) holds messages and has a [goroutine which attempts to continually ingest messages into the actual log driver](https://github.com/moby/moby/blob/master/daemon/logger/ring.go#L129). The call to ingest the message into the log driver can/should block until the log driver is ready to uptake the message. 

Unfortunately, the AWSLogs code has a [custom code path for `non-blocking` mode](https://github.com/moby/moby/blob/master/daemon/logger/awslogs/cloudwatchlogs.go#L440-L447) wherein it discards the message if the call to uptake it from the [RingBuffer](https://github.com/moby/moby/blob/master/daemon/logger/ring.go#L160) would block. This means that messages are discarded if the ingestion buffer controlled by `awslogs-max-buffered-events` is full. This is entirely unnecessary and undesirable because the `non-blocking` behavior and discarding of messages is supposed to be implemented solely by the Docker [RingBuffer](https://github.com/moby/moby/blob/master/daemon/logger/ring.go#L160). *None of the other log drivers have custom code paths for `non-blocking` mode.* 

### Solution

Simply remove the lines of code here in the **Docker** upstream code base: https://github.com/moby/moby/blob/master/daemon/logger/awslogs/cloudwatchlogs.go#L440-L447

And test the change.

### Reproduce

See above issue/design doc

### Expected behavior

non-blocking is handled entirely by RingBuffer and not in the AWSLogs Driver code. AWSLogs should not proactively lose logs when its internal buffer is full. 

### docker version

```bash
All.
```

### docker info

```bash
All.
```

### Additional Info

I will work on fixing this.

### PR DESCRIPTION
**Pull request by PettitWesley**
Previously, the AWSLogs driver attempted to implement non-blocking itself. Non-blocking is supposed to
implemented solely by the Docker RingBuffer that
wraps the log driver.

Please see issue and explanation here:
https://github.com/moby/moby/issues/45217

**- What I did**

- fixes #45217

**- How I did it**

**- How to verify it**

WIP/TODO, working on testing it

**- Description for the changelog**

* Resolve AWSLogs driver non-blocking log drop bug #45217 

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by corhere — COMMENTED** [review]
The rationale and code change look good to me. My only complaint is that some now-dead code is left around. Please remove the `logNonBlocking` field from the `logStream` ~and `logStreamConfig`~ struct.

**Comment by samuelkarp** [comment]
> Previously, the AWSLogs driver attempted to implement non-blocking itself. Non-blocking is supposed to implemented solely by the Docker RingBuffer

If I remember correctly, the code in this driver predates the ringbuffer.

The non-blocking config is also used to compensate for `CreateLogStream` failures, so a change to the logic needs to still account for that.

**Comment by PettitWesley** [comment]
@samuelkarp This PR will not/does not change the create stream blocking/non-blocking behavior here: https://github.com/moby/moby/blob/master/daemon/logger/awslogs/cloudwatchlogs.go#L166

@corhere Its still used in the logStream struct here: https://github.com/moby/moby/blob/master/daemon/logger/awslogs/cloudwatchlogs.go#L166

I can remove it from the other one.

**Comment by PettitWesley** [comment]
@samuelkarp @corhere I have removed the unnneeded `logNonBlocking` struct field.

File: daemon/logger/awslogs/cloudwatchlogs.go [hunk 1]
```diff
@@ -150,12 +149,14 @@ func New(info logger.Info) (logger.Logger, error) {
...
 
+	logNonBlocking := info.Config["mode"] == "non-blocking"
+
 	containerStream := &logStream{
 		logStreamName:      containerStreamConfig.logStreamName,
 		logGroupName:       containerStreamConfig.logGroupName,
 		logCreateGroup:     containerStreamConfig.logCreateGroup,
 		logCreateStream:    containerStreamConfig.logCreateStream,
-		logNonBlocking:     containerStreamConfig.logNonBlocking,
+		logNonBlocking:     logNonBlocking,
```
Comment (corhere) [inline daemon/logger/awslogs/cloudwatchlogs.go:159]: The only place this field is read is inside this very function, eight lines down. Change line 167 to `if logNonBlocking {` and the `logStream.logNonBlocking` field can also go away.

**Review by corhere — APPROVED** [review]

**Comment by corhere** [comment]
Unit tests are likely going to fail because there are a couple of tests which reference the `logNonBlocking` field which no longer exists. https://github.com/moby/moby/blob/878ee341d6fad3c0a28f9bd5471eb56736579010/daemon/logger/awslogs/cloudwatchlogs_test.go#L407-L440

File: daemon/logger/awslogs/cloudwatchlogs.go (hunk 1 above)
Comment (PettitWesley) [reply daemon/logger/awslogs/cloudwatchlogs.go]: Good call. It is silly that I didn't realize that. Thanks/updated!

File: daemon/logger/awslogs/cloudwatchlogs_test.go [hunk 2]
```diff
@@ -404,40 +404,16 @@ func TestLogBlocking(t *testing.T) {
...
 	stream := &logStream{
 		client:         mockClient,
 		messages:       make(chan *logger.Message, 1),
-		logNonBlocking: true,
 	}
 	err := stream.Log(&logger.Message{})
 	assert.NilError(t, err)
 }
 
-func TestLogNonBlockingBufferFull(t *testing.T) {
```
Comment (PettitWesley) [inline daemon/logger/awslogs/cloudwatchlogs_test.go:418]: @corhere so this test tests the buggy behavior... so I just removed it..

(a bug that has a test to check that the bug exists xD!)

File: daemon/logger/awslogs/cloudwatchlogs_test.go [hunk 3]
```diff
@@ -404,40 +404,16 @@ func TestLogBlocking(t *testing.T) {
 	}
 }
 
-func TestLogNonBlockingBufferEmpty(t *testing.T) {
+func TestLogBufferEmpty(t *testing.T) {
```
Comment (PettitWesley) [inline daemon/logger/awslogs/cloudwatchlogs_test.go:407]: I'm not sure I understand the point of this test, but it should still pass with the non-blocking config removed, so I kept it. 

Running the tests locally now..

**Review by corhere — APPROVED** [review]
LGTM!

**Review by kzys — APPROVED** [review]
Looks good to me!

cc @austinvazquez

**Review by thaJeztah — APPROVED** [review]
copying @kzys's LGTM (and looks good AFAICS)

**Comment by PettitWesley** [comment]
@thaJeztah @corhere @samuelkarp Can we get this merged? Also is this eligible for a patch release if I submit a PR against the `20.10` and `23.0` branches?

I have created a log loss benchmarking framework and have tested both the bug and the patch, results are here: https://github.com/moby/moby/issues/45217#issuecomment-1509272084

The patch does reduce the amount of log loss at higher throughputs (6+ MB/s).

**Comment by thaJeztah** [comment]
Yes, let's get this one merged. I see a cherry-pick label was already added, so feel free to open a backport for the 23.0 branch at least (perhaps 20.10 as well)

I'm not sure if it will still make it for the 23.0.4 patch release, but if not, it can be in 23.0.5 after that.

Oh! In case you are planning to do a cherry-pick to those branches; we prefer to use the `-x` option when cherry-picking, so that a reference to the original commit is included in the commit message.

**Comment by toluphene91** [comment]
Am not enjoying github it use to swallow all my coin

**Comment by toluphene91** [comment]
Am regretting partner with github
