### PR TITLE
daemon: Fix panic on Windows when restoring pre v28 container

### LINKED ISSUE #49625: Docker Engine no longer starts on Windows after upgrading to 28.0.0 and 28.0.1
### Description

After installing the new versions, the Windows Service no longer starts on Windows 11, Windows Server 2022, and Windows Server 2019. See panic log:
[panic.log](https://github.com/user-attachments/files/19177183/panic.log)

### Reproduce

1. Stop Docker Engine Windows Service
2. Replace `dockerd` executable with the newer version
3. Start Docker Engine Windows Service

### Expected behavior

Docker Engine should start without any errors.

### docker version

```bash
Client:
 Version:           28.0.1
 API version:       1.48
 Go version:        go1.23.6
 Git commit:        068a01e
 Built:             Wed Feb 26 10:41:52 2025
 OS/Arch:           windows/amd64
 Context:           default
error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.48/version": open //./pipe/docker_engine: The system cannot find the file specified.
```

### docker info

```bash
Client:
 Version:    28.0.1
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  v2.33.1
    Path:     C:\Program Files\docker\cli-plugins\docker-compose.exe

Server:
ERROR: error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.48/info": open //./pipe/docker_engine: The system cannot find the file specified.
errors pretty printing info
```

### Additional Info

Please keep in mind that the information about the engine can't be provided through docker commands because the engine is not running.

### PR DESCRIPTION
**Pull request by vvoland**
- fixes: https://github.com/moby/moby/issues/49625

The container platform migration tries to deduce the platform data from the containerd content store if it's available.

However, on Windows we currently default to a non-containerd runtime setup, so the containerd client is nil and accessing its content store paniced:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x11b48e4]

goroutine 87 [running]:
github.com/containerd/containerd/v2/client.(*Client).ContentStore(0xc0003a0008?)
	/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/v2/client/client.go:645 +0x24
github.com/docker/docker/daemon.(*Daemon).load(0xc00026e488, {0xc000c13d40, 0x40})
	/go/src/github.com/docker/docker/daemon/container.go:84 +0x289
github.com/docker/docker/daemon.(*Daemon).restore.func1({0xc000c13d40, 0x40})
	/go/src/github.com/docker/docker/daemon/daemon.go:236 +0x207
created by github.com/docker/docker/daemon.(*Daemon).restore in goroutine 1
	/go/src/github.com/docker/docker/daemon/daemon.go:229 +0x1a7
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x11b48e4]

goroutine 90 [running]:
github.com/containerd/containerd/v2/client.(*Client).ContentStore(0xc000313608?)
	/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/v2/client/client.go:645 +0x24
github.com/docker/docker/daemon.(*Daemon).load(0xc00026e488, {0xc000c13e00, 0x40})
	/go/src/github.com/docker/docker/daemon/container.go:84 +0x289
github.com/docker/docker/daemon.(*Daemon).restore.func1({0xc000c13e00, 0x40})
	/go/src/github.com/docker/docker/daemon/daemon.go:236 +0x207
created by github.com/docker/docker/daemon.(*Daemon).restore in goroutine 1
	/go/src/github.com/docker/docker/daemon/daemon.go:229 +0x1a7
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x11b48e4]
```

**- What I did**

**- How I did it**

**- How to verify it**

**- Human readable description for the release notes**

```markdown changelog
Fix the daemon failing to start on Windows when a container created before v28.0.0 was present.
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: daemon/container.go [hunk 1]
```diff
@@ -81,7 +81,9 @@ func (daemon *Daemon) load(id string) (*container.Container, error) {
 	if ctr.ImagePlatform.Architecture == "" {
 		migration := daemonPlatformReader{
 			imageService: daemon.imageService,
-			content:      daemon.containerdClient.ContentStore(),
+		}
+		if daemon.containerdClient != nil {
+			migration.content = daemon.containerdClient.ContentStore()
 		}
 		migrateContainerOS(context.TODO(), migration, ctr)
```
Comment (thaJeztah) [inline daemon/container.go:88]: Other things are still needed in this case, or could this be skipped as a whole?

Comment (vvoland) [reply daemon/container.go:88]: No, we still want to deduce the `Architecture` from the image (but without using the containerd content store).

**Review by neersighted — APPROVED** [review]

**Review by akerouanton — APPROVED** [review]

**Review by CharityKathure — APPROVED** [review]
