### PR TITLE
Fix escape-keys by preserving input if invalid

### LINKED ISSUE #21769: The behavior of the prefix of the detachkey, it is undocumented intended behavior or BUG ?
If I set the escapekeys to 'ctrl-p,ctrl-q', and

type(press) | result 
---- | ------
ctrl-p A | A 
ctrl-p ctrl-p | ctrl-p 
ctrl-p ctrl-p ctrl-q | ctrl-p ctrl-q 

it seems excellent, 'ctrl-p' is the escapekey of the escapekeys, it means typing 'ctrl-p' at first give us a way to send the whole escapekeys into container. But it is **undocumented**! Is it *intended* or **BUG**?
And it('ctrl-p') is always eaten.

If it is intended, escapekeys 'A,B,C,D' will give me another shock,
any prefixes of the 'A,B,C,D' will become the escapekeys of the escapekeys, any prefix will be eaten and any prefix will help to send the full escapekeys into container. (this example is at the end of this issue)

IMO, if we allow escapekeys of the escapekeys, it is better ONLY to use the first key as the escapekey of the escapekeys, rather than any prefix. But, again, it requires documentation.

But if we only use the first key as the escapekey of the escapekeys, and the user set the escapekeys to "A,A" or "ctrl-p,ctrl-p", we have no way to send A or ctrl-p into container.

 ==========
other solution (I prefer this one, it matches the document but it changes the current behavior): disallow any way to send escapekeys into container
if the type sequeue is the  escapekeys, we do the detach
if the type sequeue is any prefix of the escapekeys, we put it into container, rather than eat(discard) it.

**Output of `docker version`:**

```
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:18:46 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:18:46 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 28
 Running: 3
 Paused: 0
 Stopped: 25
Images: 2
Server Version: 1.10.1
Storage Driver: overlay
 Backing Filesystem: xfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.4.5.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.694 GiB
Name: sbox
ID: X3HY:KHO6:CAFD:R4D6:QIFV:MS5H:HLXS:4QT7:MYIR:4PM3:OJZV:JJEZ
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. docker run -ti --detach-keys 'A,B,C,D' ubuntu
2. press 'Atesta'
3. press 'ABtestab'
4. press 'ABCtestabc'
5. press 'AABCD'
6. press 'ABABCD'
7. press 'ABCABCD'

**Describe the results you received:**
testa
testab
testabc
ABCD
ABCD
ABCD

**Describe the results you expected:**
I don't know.

**Additional information you deem important (e.g. issue happens only occasionally):**

### PR DESCRIPTION
**Pull request by vdemeester**
Currently, using a custom detach key with an invalid sequence, eats a part of the sequence, making it weird and difficult to enter some key sequence 🐯.

This fixes by keeping the input read when trying to see if it's the key sequence or not, and "writing" then is the key sequence is not the right one, preserving the initial input 🐹.

```
$ docker run --detach-keys=a,b,c -it busybox /bin/sh
/ #
# press a and a on the keyboard
/ # aa
/ #
# press a, b and d
/ # abd
# press a, b and c
# escape \o/
```

Fixes #21769

/cc @thaJeztah @cpuguy83  @LK4D4 @runcom @calavera 

🐸

Signed-off-by: Vincent Demeester vincent@sbr.pm

### CODE REVIEW

**Comment by duglin** [comment]
+1 see: https://github.com/docker/docker/pull/15666#issuecomment-165482070

**Comment by thaJeztah** [comment]
Heh, it works. Bit of a weird side-effect is that typing `a` twice, will not output the first `a`, until the second `a` is pressed. Guess that's ok, because using `a,b,c` as detach-key is not really a smart choice

**Comment by duglin** [comment]
any chance of getting some testcases?

**Comment by vdemeester** [comment]
@duglin I'm thinking of it, but I'm not sure how still... :sweat:

**Comment by thaJeztah** [comment]
Perhaps you can add the "test" case to the commit message at least

**Comment by duglin** [comment]
@vdemeester you may get some inspiration from the tests that use a tty - e.g. TestRunAttachDetach

**Comment by vdemeester** [comment]
@duglin oh you are right. Remembered the way we pty to send input and detach the container but I did not remembered if we check the output content or not… and it seems we do `\o/`. Test incoming :angel:.

**Comment by vdemeester** [comment]
Updated with tests :wink:

**Comment by LK4D4** [comment]
LGTM
ping @duglin

**Comment by calavera** [comment]
LGTM

File: container/container.go [hunk 1]
```diff
@@ -484,7 +484,9 @@ func copyEscapable(dst io.Writer, src io.ReadCloser, keys []byte) (written int64
 		nr, er := src.Read(buf)
 		if nr > 0 {
 			// ---- Docker addition
+			preservBuf := []byte{}
```
Comment (duglin) [inline container/container.go]: Trying to follow the flow here, but it seems to me that "preservBuf" shouldn't be needed since it MUST match the keys, right?  meaning if we're on the 3rd char of 'keys' then preservBuf must be the same as the first 2 chars of keys, right?

Comment (vdemeester) [inline container/container.go]: @duglin hum it matches a part of the key, true, until the last *wrong* key is entered. Could have done something with `keys`, `i` and the latest read but it failed a little less readable to me :sweat_smile:

Comment (duglin) [inline container/container.go]: yea, I just wanted to avoid all of the alloc's and appends as we work our way thru the input.
