### PR TITLE
docker rename fix to address the issue of renaming with the same name

### LINKED ISSUE #23319: Docker rename "oldname" "oldname" bug
Renaming a container to the same name it already has, removes its name from the output of `docker ps`, and subsequent renames seem to fail;

```
docker run -dit --name oldname busybox

docker rename oldname oldname

docker rename oldname newname
Error response from daemon: No such container: oldname

docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS              PORTS               NAMES
28769c9aad42        busybox             "sh"                About a minute ago   Up About a minute
```

Docker also no longer seems to detect that name when creating a new container, but libnetwork *does*;

```
docker run -dit --name oldname busybox                                                                                                                                                                                                                                                                                                       22a03f4411a06123f16a7ebd9f957a1091f842806bf0340b2439e05a586a0c1f
docker: Error response from daemon: service endpoint with name oldname already exists.
```

However, `docker inspect` still shows it has a name;

```
docker inspect --format "{{.Name}}" 28769c9aad42
/oldname
```

And, so has the newly created container:

```
docker inspect --format "{{.Name}}" 22a03f4411a0
/oldname
```

### PR DESCRIPTION
**Pull request by sainath14**
Fixes #23319 

**\- What I did**
docker rename cont_name cont_name , using same name to rename creates an inconsistent nameIndex for daemon. Added a check in daemon rename code to see if oldname is same as newname. If so return an error

**\- How to verify it**
Before the fix
docker run -itd --name=old busybox
docker rename old old - successful without any error
docker rename old old - should complain there is no container with name old

After the fix
docker run -itd --name=old busybox
docker rename old old - error "Renaming a container with the same name as its current name"
docker rename old old - error "Renaming a container with the same name as its current name"

**\- Description for the changelog**
A check in the docker daemon rename function to see if the current name of the container is same as the passed in new name. If the names match, daemon returns an error saying "names matched"

Signed-off-by: Sainath Grandhi sainath.grandhi@intel.com

### CODE REVIEW

File: daemon/rename.go [hunk 1]
```diff
@@ -21,6 +21,10 @@ func (daemon *Daemon) ContainerRename(oldName, newName string) error {
 		return fmt.Errorf("Neither old nor new names may be empty")
 	}
 
+        if oldName == newName {
```
Comment (cpuguy83) [inline daemon/rename.go]: We should probably error out instead of returning nil.

File: daemon/rename.go [hunk 2]
```diff
@@ -38,6 +42,8 @@ func (daemon *Daemon) ContainerRename(oldName, newName string) error {
 	container.Name = newName
 	container.NetworkSettings.IsAnonymousEndpoint = false
 
+        logrus.Errorf("container name after reserving newname"+container.Name)
```
Comment (cpuguy83) [inline daemon/rename.go]: Can you remove this?

File: daemon/rename.go [hunk 3]
```diff
@@ -84,6 +90,8 @@ func (daemon *Daemon) ContainerRename(oldName, newName string) error {
 		}
 	}
 
+        logrus.Errorf("container name at end"+container.Name)
```
Comment (cpuguy83) [inline daemon/rename.go]: Can you remove this?

**Comment by cpuguy83** [comment]
Thanks for working on this!
Can you also add a test?

**Comment by sainath14** [comment]
@cpuguy83 regarding returning nil, it is safe to silently ignore renaming with same name. Silently ignoring would become a problem in case a user tries using old name and new name that are very close and makes a typo to make them same. He will not realize that he made a typo :)

**Comment by cpuguy83** [comment]
No we should return an error.

**Comment by vdemeester** [comment]
Agree with @cpuguy83, we should return an error. Client is then free to handle or ignore it 😇

**Comment by thaJeztah** [comment]
hm, still slightly in favor of ignoring (there is no error, because the operation basically succeeded), but looks like I'm the minority :sweat_smile:

**Comment by justincormack** [comment]
What is the justification for returning an error? I really think it should return success. It just means "I want this container to be called x", no reason to fail if it already is. Idempotency FTW.

**Comment by cpuguy83** [comment]
Because it's odd to rename something to the same name and is most likely a mistake.
Signaling to the user "hey, you screwed something up" is a good thing.

**Comment by justincormack** [comment]
Hi, I don't think this PR is actually addressing the underlying issue, as the rename is currently also failing if I use the container id not the name:

```
whale:com.docker.driver.amd64-linux justin$ docker run --name=test -d -P nginx
284fb05acdd7d30d7d893ffed5e9eb157c179f55061cc7349de15a321788c171
whale:com.docker.driver.amd64-linux justin$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                           NAMES
284fb05acdd7        nginx               "nginx -g 'daemon off"   2 seconds ago       Up 1 seconds        0.0.0.0:32769->80/tcp, 0.0.0.0:32768->443/tcp   test
whale:com.docker.driver.amd64-linux justin$ docker rename 284fb05acdd7 test
whale:com.docker.driver.amd64-linux justin$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                           NAMES
284fb05acdd7        nginx               "nginx -g 'daemon off"   19 seconds ago      Up 17 seconds       0.0.0.0:32769->80/tcp, 0.0.0.0:32768->443/tcp   
whale:com.docker.driver.amd64-linux justin$ docker rename 284fb05acdd7 test
whale:com.docker.driver.amd64-linux justin$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                           NAMES
284fb05acdd7        nginx               "nginx -g 'daemon off"   25 seconds ago      Up 23 seconds       0.0.0.0:32769->80/tcp, 0.0.0.0:32768->443/tcp   
whale:com.docker.driver.amd64-linux justin$ docker rename 284fb05acdd7 test2
whale:com.docker.driver.amd64-linux justin$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                           NAMES
284fb05acdd7        nginx               "nginx -g 'daemon off"   31 seconds ago      Up 30 seconds       0.0.0.0:32769->80/tcp, 0.0.0.0:32768->443/tcp   test2
whale:com.docker.driver.amd64-linux justin$ docker rename 284fb05acdd7 test
whale:com.docker.driver.amd64-linux justin$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                           NAMES
284fb05acdd7        nginx               "nginx -g 'daemon off"   47 seconds ago      Up 46 seconds       0.0.0.0:32769->80/tcp, 0.0.0.0:32768->443/tcp   test
```

**Comment by cpuguy83** [comment]
This is because the name registrar doesn't return an error if the name is already reserved to the passed in reference.

Could update it to go ahead and return an error there or just explicitly check if the new name matches the container's ID/Name...
I think the latter is likely less work.

**Comment by sainath14** [comment]
I agree @cpuguy83. Only other places where they call Reserve API from registrar package are in the new container creation flow. So it might not have made sense to check the name against the passed in id.

File: daemon/rename.go [hunk 4]
```diff
@@ -21,6 +21,13 @@ func (daemon *Daemon) ContainerRename(oldName, newName string) error {
 		return fmt.Errorf("Neither old nor new names may be empty")
 	}
 
+	if newName[0] != '/' {
+		newName = "/" + newName
+	}
```
Comment (sainath14) [inline daemon/rename.go]: I moved container.Lock up as there could be a chance where two requests "docker rename old new" and "docker rename old new" can land in parallel. We should fail the second request as after the first request there would not be a container by name old.

**Comment by sainath14** [comment]
ping @cpuguy83 @thaJeztah @vdemeester

**Comment by LK4D4** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐯

**Comment by vdemeester** [comment]
@sainath14 could you update the "changelog" part of the PR description so that it matches the current behaviour ? :angel:

**Comment by sainath14** [comment]
@vdemeester change log updated.

File: daemon/rename.go [hunk 5]
```diff
@@ -31,6 +35,11 @@ func (daemon *Daemon) ContainerRename(oldName, newName string) error {
 
 	container.Lock()
 	defer container.Unlock()
+
+	if oldName == newName {
```
Comment (thaJeztah) [inline daemon/rename.go]: Should we move this before the `container.Lock()`?

Comment (thaJeztah) [inline daemon/rename.go]: Just discussed this with @vdemeester and we saw some other things that may need to be improved (not related to this PR), so he's going to do a follow up
