### PR TITLE
Do not DNAT packets from WSL2's loopback0

### LINKED ISSUE #48056: In WSL using networkingMode=mirrored, "docker run -d -p 8080:80 nginx:alpine" results in localhost:8080 not being accessible from Windows
### Description

After investigating from WSL side the following issue https://github.com/microsoft/WSL/issues/10494, we found the root cause and a fix that can be made by Docker

more details added in the "Additional info" section

### Reproduce

1. Setup WSL with networkingMode=mirrored in the .wslconfig file
2. In WSL, run docker run -d -p 8080:80 nginx:alpine
3. In a Windows browser, go to localhost:8080

### Expected behavior

Windows browser is able to access the nginx server running in the Docker container

### docker version

```bash
Client:
Version:           24.0.7
API version:       1.43
Go version:        go1.21.1
Git commit:        24.0.7-0ubuntu2~22.04.1
Built:             Wed Mar 13 20:23:54 2024
OS/Arch:           linux/amd64
Context:           default
 
Server:
Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.21.1
  Git commit:       24.0.7-0ubuntu2~22.04.1
  Built:            Wed Mar 13 20:23:54 2024
  OS/Arch:          linux/amd64
  Experimental:     false
containerd:
  Version:          1.7.12
  GitCommit:
runc:
  Version:          1.1.12-0ubuntu2~22.04.1
  GitCommit:
docker-init:
  Version:          0.19.0
  GitCommit:
```

### docker info

```bash
Client:
Version:    24.0.7
Context:    default
Debug Mode: false
 
Server:
Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
Images: 1
Server Version: 24.0.7
Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Cgroup Version: 1
Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: io.containerd.runc.v2 runc
Default Runtime: runc
Init Binary: docker-init
containerd version:
runc version:
init version:
Security Options:
  seccomp
   Profile: builtin
Kernel Version: 5.15.153.1-microsoft-standard-WSL2
Operating System: Ubuntu 22.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.758GiB
Name: wsl-test
ID: d62f9024-99e1-4774-8d65-b5554f8f2b11
Docker Root Dir: /var/lib/docker
Debug Mode: false
Experimental: false
Insecure Registries:
  127.0.0.0/8
Live Restore Enabled: false
 
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

### Additional Info

**What's the issue and root cause:**
Docker uses an nftables NAT rule to implement port forwarding and the rule applies to inbound traffic arriving in Linux.

Docker assumes that 127.0.0.1 traffic is not coming from outside Linux and so the NAT rule won't be applied to this traffic. Docker has a different mechanism to do port forwarding for 127.0.0.1

In mirrored mode 127.0.0.1 traffic can come from outside Linux, when Windows and Linux communicate using 127.0.0.1 (traffic will flow through the Linux loopback0 interface), so the NAT rule will be applied to this traffic, which breaks Docker's assumption.

How does Docker’s NAT solution work today with networkingMode = NAT? Even though Windows and Linux can communicate on 127.0.0.1 using the localhost relay, 127.0.0.1 traffic will arrive in Linux on an hvsocket connection and it won't be considered inbound traffic, so the rule won't be applied to it.

**Proposed fix that can be made by Docker:**
Exclude inbound traffic on interface "loopback0" from being processed by the NAT rule, by modifying the rule as shown below

Original rule (second rule in the chain):

chain DOCKER {
                iifname "docker0" counter packets 0 bytes 0 return
                iifname != "docker0" tcp dport 8080 counter packets 0 bytes 0 dnat to 172.17.0.2:80
        }

New rule (second rule in the chain):

chain DOCKER {
                iifname "docker0" counter packets 0 bytes 0 return
                iifname != "docker0" iifname != "loopback0" tcp dport 8080 counter packets 0 bytes 0 dnat to 172.17.0.2:80
        }

Fix was tested by running "docker run -d -p 8080:80 nginx:alpine" in Linux, then connecting to localhost:8080 in a Windows browser - the scenario did not work before the fix and worked after applying the fix manually.

**Risk assesment:**
Risk of the fix is low

In mirrored mode, loopback0 interface is only used for 127.0.0.1 traffic. 127.0.0.1 traffic is not supposed to be processed by the NAT rule - excluding loopback0 traffic from being processed by the NAT rule should not affect existing functionality.

### PR DESCRIPTION
**Pull request by robmry**
**- What I did**

When running WSL2 with mirrored mode networking, add an iptables rule to skip DNAT for packets arriving on interface loopback0 that are addressed to a localhost address - they're from the Windows host.

- fixes https://github.com/moby/moby/issues/48056
- related to https://github.com/microsoft/WSL/issues/10494

WSL2's mirrored mode networking is [outlined here](https://learn.microsoft.com/en-us/windows/wsl/networking#mirrored-mode-networking).

**- How I did it**

Detect WSL2 mirrored mode by the presence of interface `loopback0`, and (inspired by [this workaround](https://gist.github.com/shigenobuokamoto/b565d468541fc8be7d7d76a0434496a0) linked from the WSL ticket) `/usr/bin/wslinfo --networking-mode` reporting `mirrored`, see [wslinfo release note](https://github.com/microsoft/WSL/releases/tag/2.0.4).

If needed, create a rule in the nat-DOCKER chain to return early for packets arriving on `loopback0` for `127.0.0.0/8`.

There's no IPv6 rule, because WSL2 mirrored mode [doesn't support it](https://learn.microsoft.com/en-us/windows/wsl/networking#mirrored-mode-networking:~:text=IPv6%20localhost%20address%20%3A%3A1%20is%20not%20supported).

**- How to verify it**

As described on the ticket, with docker-ce installed in an instance of Linux (Ubuntu) running under WSL2 with `networkingMode=mirrored`  - run an nginx container with `-p 8080:80`, check that the Windows host can connect to it via `http://localhost:8080`.

Also checked that the new iptables rule is not created unless it's needed.

Access from Linux to a service running on the Windows localhost address worked before and after this change.

(`--userland-proxy=true`, the default, is required for this to work.)

New unit test, just to check the conditions for adding the rule.

**- Description for the changelog**
```markdown changelog
Support WSL2 mirrored-mode networking's use of interface `loopback0` for packets from the Windows host.
```

### CODE REVIEW

File: libnetwork/drivers/bridge/setup_ip_tables_linux.go [hunk 1]
```diff
@@ -502,3 +511,67 @@ func clearConntrackEntries(nlh *netlink.Handle, ep *bridgeEndpoint) {
...
+	return programChainRule(mirroredWSL2Rule(), "WSL2 loopback", mirroredWSL2())
+}
+
+// mirroredWSL2 returns true if the host Linux appears to be running under
+// Windows WSL2 with mirrored mode networking. If a loopback0 device exists, it
+// checks that /usr/bin/wslinfo is executable and reports mirrored networking.
+func mirroredWSL2() bool {
+	if _, err := netlink.LinkByName("loopback0"); err != nil {
+		if !errors.As(err, &netlink.LinkNotFoundError{}) {
+			log.G(context.TODO()).Warnf("Failed to check for WSL interface: %v", err)
```
Comment (thaJeztah) [inline libnetwork/drivers/bridge/setup_ip_tables_linux.go:561]: Minor nit; can you use `WithError()` or perhaps even `WithFields()` in case we want to log the name of the interface we're looking for?



```suggestion
			log.G(context.TODO()).WithError(err).Warn("Failed to check for WSL interface")
```


```suggestion
			log.G(context.TODO()).WithFields(log.Fields{"error": err, "interface": "loopback0"}).Warn("Failed to check for WSL interface")
```

File: libnetwork/drivers/bridge/setup_ip_tables_linux.go [hunk 2]
```diff
@@ -502,3 +511,67 @@ func clearConntrackEntries(nlh *netlink.Handle, ep *bridgeEndpoint) {
...
+		}
+		return false
+	}
+	output, err := exec.Command(wslinfoPath, "--networking-mode", "-n").CombinedOutput()
+	log.G(context.TODO()).Debugf("wslinfo --networking-mode:%s err:%v", string(output), err)
```
Comment (thaJeztah) [inline libnetwork/drivers/bridge/setup_ip_tables_linux.go:566]: Same here, at least for the error, but perhaps output could also be a field.

File: libnetwork/drivers/bridge/setup_ip_tables_linux.go [hunk 3]
```diff
@@ -502,3 +511,67 @@ func clearConntrackEntries(nlh *netlink.Handle, ep *bridgeEndpoint) {
...
+	return err == nil && string(output) == "mirrored"
+}
+
+func mirroredWSL2Rule() iptRule {
+	return iptRule{
+		ipv:   iptables.IPv4,
+		table: iptables.Nat,
+		chain: DockerChain,
+		args:  []string{"-i", "loopback0", "-d", "127.0.0.0/8", "-j", "RETURN"},
```
Comment (thaJeztah) [inline libnetwork/drivers/bridge/setup_ip_tables_linux.go:575]: As (even more with my suggestions), the magic `loopback0` interface will be used more now, I'm wondering it would make sense to define a `const` for it as well; at least it would allow documenting "what's this magic `loopback0`? 


(downside is that it's less grep'able for `loopback0` in the code, although the `const` can still be a good starting point I guess)

So, yeah, not a "strong" opinion one way of another 😅

File: libnetwork/drivers/bridge/setup_ip_tables_linux.go [hunk 4]
```diff
@@ -502,3 +511,67 @@ func clearConntrackEntries(nlh *netlink.Handle, ep *bridgeEndpoint) {
...
+// packet is processed by a per-bridge DNAT rule in that chain, so it is
+// delivered directly to the container (not via docker-proxy) with source address
+// 127.0.0.1, so the container can't respond.
+//
+// DNAT is normally skipped by RETURN rules in the nat-DOCKER chain for packets
+// arriving from any other bridge network. Similarly, this function adds (or
+// removes) a rule to RETURN early for packets delivered via loopback0 with
+// destination 127.0.0.0/8.
+func mirroredWSL2Workaround(ipv iptables.IPVersion) error {
+	// WSL2 does not (currently) support Windows<->Linux communication via ::1.
```
Comment (thaJeztah) [inline libnetwork/drivers/bridge/setup_ip_tables_linux.go:548]: I notice that we don't check if `wslinfoPath` (`/usr/bin/wslinfo`) exists, which (I think) is the way to detect if we're actually running on WSL2?

- Should we have a `detectWSL2()` utility to verify if we're running on WSL2, as this workaround is not for other situations
- Perhaps that check should be a `sync.Once` or `syncOnceValue` if we only need to check if once (but may not be needed if we only run this code once 😂)


For testing, maybe we need something to override the detection 🤔 (not sure?)

**Review by corhere — COMMENTED** [review]
Running `/usr/bin/wslinfo` as root is not ideal, especially on non-WSL environments. Some ideas:
* Run wslinfo as an unprivileged user. But which user?
* Sandbox the wslinfo process in a container
* More sanity checks to limit the exposure to non-WSL users:
  * Test that `/run/WSL` exists and is a directory
  * Test that both `/usr/bin` and `/usr/bin/wslinfo` are owned by root and not world-writable?

File: libnetwork/drivers/bridge/setup_ip_tables_linux.go (hunk 4 above)
Comment (corhere) [reply libnetwork/drivers/bridge/setup_ip_tables_linux.go:548]: > I notice that we don't check if `wslinfoPath` (`/usr/bin/wslinfo`) exists

There's no need to: the `exec.Command` call would fail with `ENOENT` if the path does not exist.

**Comment by robmry** [comment]
> Running `/usr/bin/wslinfo` as root is not ideal, especially on non-WSL environments. Some ideas:
> 
> * Run wslinfo as an unprivileged user. But which user?
> * Sandbox the wslinfo process in a container
> * More sanity checks to limit the exposure to non-WSL users:
>   
>   * Test that `/run/WSL` exists and is a directory
>   * Test that both `/usr/bin` and `/usr/bin/wslinfo` are owned by root and not world-writable?

Yes - I think we could just use the presence of loopback0 and wslinfo to infer that it's wsl2 and mirrored networking.

If we're wrong, which seems unlikely (unless it's deliberate) ... we create the rule to skip DNAT for packets from that interface addressed to 127.0.0.0/8 - there won't be any but, even if there were, they'd only be DNAT'd if they were for a mapped port ... in which case they don't want DNAT either.

**Comment by corhere** [comment]
> If we're wrong, which seems unlikely (unless it's deliberate)

That's what I'm worried about: some attacker tricking dockerd into executing attacker-controlled code as root.

**Comment by robmry** [comment]
> > If we're wrong, which seems unlikely (unless it's deliberate)
> 
> That's what I'm worried about: some attacker tricking dockerd into executing attacker-controlled code as root.

Yes, agreed (that's why I raised the issue on our call). I'm suggesting we don't run it ... just see if it and loopback0 are there. There aren't really any consequences if we infer wrongly.

**Comment by thaJeztah** [comment]
Let me post the `strace` that Tianon posted on slack; does that output mean that there is some API it's using to detect? (I noticed some `AF_UNIX` and `/run/WSL/1_interop`); i.e., is that something that could be used for this purpose as alternative to exec'ing a binary?

```
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC, 0) = 3
connect(3, {sa_family=AF_UNIX, sun_path="/run/WSL/1_interop"}, 110) = 0
```


```
$ strace -ff wslinfo --networking-mode
execve("/usr/bin/wslinfo", ["wslinfo", "--networking-mode"], 0x7fff40ffd070 /* 36 vars */) = 0
arch_prctl(ARCH_SET_FS, 0x40cc60)       = 0
set_tid_address(0x40cc00)               = 6710
gettid()                                = 6710
gettid()                                = 6710
gettid()                                = 6710
gettid()                                = 6710
brk(NULL)                               = 0x1b8e000
brk(0x1b90000)                          = 0x1b90000
mmap(0x1b8e000, 4096, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x1b8e000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f62e9a11000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f62e9a10000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f62e9a0f000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f62e9a0e000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f62e9a0d000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f62e9a0c000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f62e9a0b000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f62e9a0a000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f62e9a09000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f62e9a07000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f62e9a05000
sched_getaffinity(0, 128, [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19]) = 32
getpid()                                = 6710
getpid()                                = 6710
uname({sysname="Linux", nodename="catra", ...}) = 0
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC, 0) = 3
connect(3, {sa_family=AF_UNIX, sun_path="/run/WSL/1_interop"}, 110) = 0
write(3, "\32\0\0\0\10\0\0\0", 8)       = 8
poll([{fd=3, events=POLLIN}], 1, 10000) = 1 ([{fd=3, revents=POLLIN|POLLHUP}])
read(3, "\1\0\0\0", 4)                  = 4
close(3)                                = 0
ioctl(1, TIOCGWINSZ, {ws_row=24, ws_col=80, ws_xpixel=0, ws_ypixel=0}) = 0
writev(1, [{iov_base="nat", iov_len=3}, {iov_base="\n", iov_len=1}], 2nat
) = 4
munmap(0x7f62e9a05000, 8192)            = 0
munmap(0x7f62e9a07000, 8192)            = 0
munmap(0x7f62e9a09000, 4096)            = 0
munmap(0x7f62e9a0b000, 4096)            = 0
munmap(0x7f62e9a0c000, 4096)            = 0
munmap(0x7f62e9a0d000, 4096)            = 0
munmap(0x7f62e9a0e000, 4096)            = 0
munmap(0x7f62e9a0f000, 4096)            = 0
munmap(0x7f62e9a10000, 4096)            = 0
munmap(0x7f62e9a11000, 4096)            = 0
exit_group(0)                           = ?
+++ exited with 0 +++
```

File: libnetwork/drivers/bridge/setup_ip_tables_linux.go (hunk 1 above)
Comment (robmry) [reply libnetwork/drivers/bridge/setup_ip_tables_linux.go]: Oops, yes - I've split out the `err`, thank you.

I didn't feel the need to report the `loopback0` interface name ... it might be in the netlink message anyway, but the idea was just to log a failed netlink call (having ignored `LinkNotFoundError`).

File: libnetwork/drivers/bridge/setup_ip_tables_linux.go (hunk 2 above)
Comment (robmry) [reply libnetwork/drivers/bridge/setup_ip_tables_linux.go]: I've split out `err`.

File: libnetwork/drivers/bridge/setup_ip_tables_linux.go (hunk 3 above)
Comment (robmry) [reply libnetwork/drivers/bridge/setup_ip_tables_linux.go:580]: I tried it with a const name ... but I don't think it made things any clearer, so put it back.

The gigantic comment just above explains what it is.

File: libnetwork/drivers/bridge/setup_ip_tables_linux.go (hunk 4 above)
Comment (robmry) [reply libnetwork/drivers/bridge/setup_ip_tables_linux.go:549]: Indeed - but it's gone now anyway.

File: libnetwork/drivers/bridge/setup_ip_tables_linux_test.go [hunk 5]
```diff
@@ -374,3 +377,68 @@ func TestOutgoingNATRules(t *testing.T) {
 		})
 	}
 }
+
+func TestMirroredWSL2Workaround(t *testing.T) {
+	// Avoid overwriting a real "/usr/bin/wslinfo" (and clashing with a real
+	// loopback0).
+	if _, err := os.Stat(wslinfoPath); err == nil {
+		t.Skip("Skipping test because " + wslinfoPath + " exists")
+	}
```
Comment (corhere) [inline libnetwork/drivers/bridge/setup_ip_tables_linux_test.go:386]: Sounds like a job for namespaces! We don't have to worry about clashing with a real loopback0 because the test cases are invoked in an unshared network namespace thanks to `netnsutils.SetupTestOSContext()`. While we don't have a ready-made test utility for unsharing a mount namespace and setting things up such that parts of the host filesystem can be mutated such that the mutations are only visible to the test, we do have all the building blocks. The general idea is to over-mount a path with an overlayfs with the same path as the lowerdir, and a tmpfs path as the upper:
```console
root@56e9443a7364:~# mkdir /tmp/upper /tmp/work
root@56e9443a7364:~# unshare --mount-proc --propagation slave bash
root@56e9443a7364:~# mount -t overlay -olowerdir=/usr/bin,upperdir=/tmp/upper,workdir=/tmp/work overlay /usr/bin
root@56e9443a7364:~# rm /usr/bin/ls
root@56e9443a7364:~# ls -ld
bash: ls: command not found
root@56e9443a7364:~# exit
exit
root@56e9443a7364:~# ls -ld
drwx------ 1 root root 4096 Jun 28 23:05 .
```

...it may be too much to tack onto this PR, though. Save for a follow-up?

**Review by corhere — APPROVED** [review]

File: libnetwork/drivers/bridge/setup_ip_tables_linux_test.go [hunk 6]
```diff
@@ -374,3 +377,68 @@ func TestOutgoingNATRules(t *testing.T) {
...
+				tmpdir := t.TempDir()
+				wslinfoPath = filepath.Join(tmpdir, "wslinfo")
+				err := os.WriteFile(wslinfoPath, []byte("#!/bin/sh\necho dummy file\n"), tc.wslinfoPerm)
+				assert.NilError(t, err)
+			}
+
+			_, _, _, _, err := setupIPChains(configuration{EnableIPTables: true}, iptables.IPv4)
+			assert.NilError(t, err)
+			assert.Check(t, mirroredWSL2Rule().Exists() == tc.expLoopback0Rule,
+				fmt.Sprintf("Expected exists=%v", tc.expLoopback0Rule))
```
[the remark this answers is not in the document]
Comment (thaJeztah) [reply libnetwork/drivers/bridge/setup_ip_tables_linux_test.go:441]: Ah! I didn't spot it this time; good catch.

Using `is.Equal(mirroredWSL2Rule().Exists(), tc.expLoopback0Rule)` will also do all of that; it prints the variable names in failure, so if those are descriptive, it will be printing something like;

```
    foo_test.go:35: assertion failed: false (bool) != true (tc.expLoopback0Rule bool)
```

[the remark this answers is not in the document]
Comment (robmry) [reply libnetwork/drivers/bridge/setup_ip_tables_linux_test.go]: Swapped for `is.Equal`.

File: libnetwork/drivers/bridge/setup_ip_tables_linux.go [hunk 7]
```diff
@@ -502,3 +512,71 @@ func clearConntrackEntries(nlh *netlink.Handle, ep *bridgeEndpoint) {
...
+	if _, err := netlink.LinkByName("loopback0"); err != nil {
+		if !errors.As(err, &netlink.LinkNotFoundError{}) {
+			log.G(context.TODO()).WithError(err).Warn("Failed to check for WSL interface")
+		}
+		return false
+	}
+	if stat, err := os.Stat(wslinfoPath); err == nil {
+		return stat.Mode().IsRegular() && (stat.Mode().Perm()&0111) != 0
+	}
+	return false
```
[the remark this answers is not in the document]
Comment (robmry) [reply libnetwork/drivers/bridge/setup_ip_tables_linux.go]: Done.

File: libnetwork/drivers/bridge/setup_ip_tables_linux_test.go (hunk 5 above)
Comment (robmry) [reply libnetwork/drivers/bridge/setup_ip_tables_linux_test.go]: I forgot to delete that check when I changed `wslinfoPath` from `const` to `var` so that the test could modify it to avoid the clash that way instead. It's gone now.

**Comment by dannyhpy** [comment]
This PR fixes the issue listed in https://github.com/microsoft/WSL/issues/10494 for the loopback interface only, sadly. Running `docker run -ti --rm -p 192.168.1.100:8080:80 traefik/whoami` and opening `http://192.168.1.100:8080/` in the browser on the host machine still fails with a `ERR_CONNECTION_TIMED_OUT`. On other hosts in the LAN, though, this works.

The `hostAddressLoopback` option is set to `true` in my `%USERPROFILE%\.wslconfig` file as noted in https://learn.microsoft.com/en-us/windows/wsl/wsl-config and running another program such as `python -m http.server` works and is reachable from the Windows host at `http://192.168.1.100:8000/`

**Comment by robmry** [comment]
> This PR fixes the issue listed in [microsoft/WSL#10494](https://github.com/microsoft/WSL/issues/10494) for the loopback interface only, sadly. Running `docker run -ti --rm -p 192.168.1.100:8080:80 traefik/whoami` and opening `http://192.168.1.100:8080/` in the browser on the host machine still fails with a `ERR_CONNECTION_TIMED_OUT`. On other hosts in the LAN, though, this works.

Hi @dannyhpy - this seems to be unrelated to this `loopback0` workaround, please could you raise it as a separate issue?

I took a look, and could repro ...

Packets arrive on the WSL2 guest's `ethN` interface, with the shared host address as the source. So, everything looks normal. They're DNAT'd, arrive at the container, and get a response addressed to the shared host address (`192.168.1.100` in the example). But, the response packets don't get back to the WSL2 `ethN` interface.

That's because the dest MAC address in response packets belongs to the docker network's bridge (the container's default gateway). The WSL2 guest has that IP address itself, on its own `ethN`, it doesn't know anything about the Windows version of that address. So, packets are delivered locally rather than sent back to `ethN` - then dropped because nothing in the Linux guest is listening on that dest port.

I don't have an idea for a workaround right now. Maybe somehow forcing use of `docker-proxy` for these connections would help, but it sounds messy. It'd be good to get some input from Microsoft on how they think this sort of thing could work.

**Comment by dannyhpy** [comment]
Hi @robmry,

Thank you for your very detailled explanations. I originally thought this issue was similar to the loopback0 issue and wrongly assumed it could be solved using the same workaround. My apologies for my off-topic comment.

> please could you raise it as a separate issue?

I'm afraid I won't be as capable as you are to properly describe the issue.

**Comment by robmry** [comment]
Oh, no problem - thank you for raising the issue ... I've created https://github.com/moby/moby/issues/48136.

**Comment by louyongjiu** [comment]
Hope this pull request can be merged promptly, as I have been troubled by this issue for quite some time.

**Comment by shigenobuokamoto** [comment]
will mirroredWSL2Rule() still be called if userland-proxy=false ?
if userland-proxy=false then there is no process to receive the traffic so i would like you to leave DNAT as is.

**Comment by robmry** [comment]
> will mirroredWSL2Rule() still be called if userland-proxy=false ? if userland-proxy=false then there is no process to receive the traffic so i would like you to leave DNAT as is.

Hi @shigenobuokamoto - I think we could do that ... how will it help? Could you describe the use-case?

**Comment by shigenobuokamoto** [comment]
@robmry  thank you so much.

WSL 2.3.11 adds some improvements to communicating with Windows hosts.
this makes it possible to access Docker network from Windows Host using nftables.
however, if DNAT is disabled, this will no longer work.

https://github.com/microsoft/WSL/issues/10494#issuecomment-2234666197

https://gist.github.com/shigenobuokamoto/540c5f09a03eb07149501e99a6c8d82b

**Comment by robmry** [comment]
Ah, excellent - thank you!

File: libnetwork/drivers/bridge/setup_ip_tables_linux.go [hunk 8]
```diff
@@ -502,3 +511,67 @@ func clearConntrackEntries(nlh *netlink.Handle, ep *bridgeEndpoint) {
...
+	if ipv != iptables.IPv4 {
+		return nil
+	}
+	return programChainRule(mirroredWSL2Rule(), "WSL2 loopback", mirroredWSL2())
+}
+
+// mirroredWSL2 returns true if the host Linux appears to be running under
+// Windows WSL2 with mirrored mode networking. If a loopback0 device exists, it
+// checks that /usr/bin/wslinfo is executable and reports mirrored networking.
+func mirroredWSL2() bool {
```
[the remark this answers is not in the document]
Comment (keith-horton) [reply libnetwork/drivers/bridge/setup_ip_tables_linux.go:562]: FWIW: WSL cannot change network modes dynamically - it's set when we start the VM. (as it has impacts beyond just the Linux configuration, but also the host vswitch and tcpip stack configuration).

**Comment by robmry** [comment]
> @robmry thank you so much.
> 
> WSL 2.3.11 adds some improvements to communicating with Windows hosts. this makes it possible to access Docker network from Windows Host using nftables. however, if DNAT is disabled, this will no longer work.
> 
> [microsoft/WSL#10494 (comment)](https://github.com/microsoft/WSL/issues/10494#issuecomment-2234666197)
> 
> https://gist.github.com/shigenobuokamoto/540c5f09a03eb07149501e99a6c8d82b

I've added the exception for running without userland-proxy. In testing it, I found with the latest WSL2 pre-release (2.3.17 but, presumably, anything >2.3.11) no workaround in docker, and no extra `WSLPOSTROUTING` nftables rule, it seemed to work fine with userland-proxy disabled.

**Comment by shigenobuokamoto** [comment]
@robmry, thank you for dealing with this matter.

File: libnetwork/drivers/bridge/setup_ip_tables_linux_test.go [hunk 9]
```diff
@@ -374,3 +377,75 @@ func TestOutgoingNATRules(t *testing.T) {
 		})
 	}
 }
+
+func TestMirroredWSL2Workaround(t *testing.T) {
+	for _, tc := range []struct {
+		desc             string
+		loopback0        bool
+		userlandProxy    bool
+		wslinfoExists    bool
```
Comment (akerouanton) [inline libnetwork/drivers/bridge/setup_ip_tables_linux_test.go:386]:
```suggestion
```

**Review by akerouanton — APPROVED** [review]

**Comment by keith-horton** [comment]
I'm not 100% fluent in GO - but this looks good to me! (from the wsl side)

**Review by keith-horton — APPROVED** [review]
I'm not 100% fluent in GO - but this looks good to me! (from the wsl side)

**Review by CatalinFetoiu — APPROVED** [review]
