### PR TITLE
builder: fix detection of experimental --stream option (deprecated)

### LINKED ISSUE #41647: [20.10] Regression: detection of experimental --stream is incorrect
relates to https://github.com/moby/moby/pull/39983
relates to https://github.com/docker/docker-ce/pull/660#discussion_r510536957
relates to https://github.com/docker/cli/pull/2809

Looks like the report we received about the daemon producing an error about the experimental `--stream` option no longer being supported is not fixed yet (the fix in the CLI https://github.com/docker/cli/pull/2809 is not sufficient, as older CLI's will fail)

I accidentally discovered how to reproduce:

### Daemon (built from v20.10.0-beta1 tag) started without `--experimental`:

```console
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock docker:18.09 sh

echo "FROM scratch" | docker build -

Sending build context to Docker daemon  2.048kB
Step 1/1 : FROM scratch
 --->
No image was generated. Is your Dockerfile empty?
```

Daemon:

```
DEBU[2020-11-06T17:10:57.689685060Z] Calling POST /v1.39/build?buildargs={}&cachefrom=[]&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels={}&memory=0&memswap=0&networkmode=default&pull=1&q=1&rm=1&shmsize=0&target=&ulimits=null&version=1
```

### Daemon, started with `--experimental`

```console
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock docker:18.09 sh

echo "FROM scratch" | docker build -
Sending build context to Docker daemon  2.048kB
Error response from daemon: experimental session with v1 builder is no longer supported, use builder version v2 (BuildKit) instead
```

Daemon:

```
DEBU[2020-11-06T17:06:11.433017409Z] Calling POST /v1.39/build?buildargs={}&cachefrom=[]&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels={}&memory=0&memswap=0&networkmode=default&pull=1&q=1&rm=1&session=btn05f8k6kkk2110fs3djyork&shmsize=0&target=&ulimits=null&version=1
DEBU[2020-11-06T17:06:11.434237792Z] Calling POST /session
INFO[2020-11-06T17:06:11.434395940Z] parsed scheme: ""                             module=grpc
INFO[2020-11-06T17:06:11.434453021Z] scheme "" not registered, fallback to default scheme  module=grpc
INFO[2020-11-06T17:06:11.434470626Z] ccResolverWrapper: sending update to cc: {[{  <nil> 0 <nil>}] <nil> <nil>}  module=grpc
INFO[2020-11-06T17:06:11.434477816Z] ClientConn switching balancer to "pick_first"  module=grpc
DEBU[2020-11-06T17:06:11.486615969Z] FIXME: Got an API for which error does not match any expected type!!!: experimental session with v1 builder is no longer supported, use builder version v2 (BuildKit) instead

(removed stack dump)

ERRO[2020-11-06T17:06:11.486694465Z] Handler for POST /v1.39/build returned error: experimental session with v1 builder is no longer supported, use builder version v2 (BuildKit) instead
DEBU[2020-11-06T17:06:11.486818111Z] FIXME: Got an API for which error does not match any expected type!!!: experimental session with v1 builder is no longer supported, use builder version v2 (BuildKit) instead

(removed stack dump)

WARN[2020-11-06T17:06:11.489208009Z] grpc: addrConn.createTransport failed to connect to {  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing only one connection allowed". Reconnecting...  module=grpc
```

:warning: Notice that the CLI sends `session=btn05f8k6kkk2110fs3djyork`, _even without it having the `--stream` option set_, so for some reason, it looks for the daemon to be experimental, and in that case, sends a session-id

Trying with explicit `--stream`:

```bash
echo "FROM scratch" | docker build --stream -
failed to open Dockerfile: open Dockerfile: no such file or directory

echo "FROM scratch" | docker build --stream=true -
failed to open Dockerfile: open Dockerfile: no such file or directory
```

That looks like another bug, but working around that by using a Dockerfile instead of `stdin`;

```console
echo "FROM scratch" > Dockerfile

docker build --stream .
Error response from daemon: experimental session with v1 builder is no longer supported, use builder version v2 (BuildKit) instead
```

```console
# without --stream
Calling POST /v1.39/build?buildargs={}&cachefrom=[]&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels={}&memory=0&memswap=0&networkmode=default&pull=1&q=1&rm=1&session=btn05f8k6kkk2110fs3djyork&shmsize=0&target=&ulimits=null&version=1

# With --stream
Calling POST /v1.39/build?buildargs={}&cachefrom=[]&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels={}&memory=0&memswap=0&networkmode=default&remote=client-session&rm=1&session=361whphfmy9h8g4u5kd2zjayi&shmsize=0&target=&ulimits=null&version=1
```

:warning: So, with `--stream`, the `remote=client-session` is set: perhaps set should produce an error for that parameter instead?

### PR DESCRIPTION
**Pull request by thaJeztah**
fixes https://github.com/moby/moby/issues/41647

Commit 6ca3ec88ae9e1435abbed665ec598c00058659da deprecated (https://github.com/moby/moby/pull/39983) the experimental `--stream` option for the legacy builder, adding an error message is a client attempted to use this feature.

However, the detection used the session-ID (`session=xxx` query parameter), which happens to be set automatically by the CLI if it detects that the daemon has session support. Because of this, builds fail when trying to perform them on a daemon with the `--experimental` flag set.

This patch changes the detection to look for the `remote` query parameter, which is set to "client-session" when using the `--stream` option with the classic (non-Buildkit) builder.

Before this change, running `docker build` with an older (19.03 or older) cli against a daemon with `--experimental` enabled caused an error:

```console
$ dockerd --experimental &
$ docker pull docker:18.09
$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock docker:18.09 sh -c 'echo "FROM scratch" | docker build -'

Sending build context to Docker daemon  2.048kB
Error response from daemon: experimental session with v1 builder is no longer supported, use builder version v2 (BuildKit) instead

$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -w /foo docker:18.09 sh -c 'echo "FROM scratch" > Dockerfile && docker build --stream .'
Error response from daemon: experimental session with v1 builder is no longer supported, use builder version v2 (BuildKit) instead
```

With this patch, the error only occurs when trying to use the experimental `--stream` option:

```console
$ dockerd --experimental &
$ docker pull docker:18.09
$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock docker:18.09 sh -c 'echo "FROM scratch" | docker build -'

Step 1/1 : FROM scratch
 --->
No image was generated. Is your Dockerfile empty?

$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -w /foo docker:18.09 sh -c 'echo "FROM scratch" > Dockerfile && docker build --stream .'

Error response from daemon: experimental session with v1 builder is no longer supported, use builder version v2 (BuildKit) instead
```

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
@tonistiigi @tiborvass @cpuguy83 PTAL

**Review by tiborvass — APPROVED** [review]

File: builder/remotecontext/detect.go [hunk 1]
```diff
@@ -33,12 +33,7 @@ func Detect(config backend.BuildConfig) (remote builder.Source, dockerfile *pars
 	case remoteURL == "":
 		remote, dockerfile, err = newArchiveRemote(config.Source, dockerfilePath)
 	case remoteURL == ClientSessionRemote:
-		res, err := parser.Parse(config.Source)
```
Comment (thaJeztah) [inline builder/remotecontext/detect.go:36]: FWIW; this function (`remotecontext.Detect()`) was only used by the classic builder, and not used in the CLI, so I thought this would be a good spot to produce the error (initially had it in the old place, but thought this would be cleaner)

**Review by cpuguy83 — APPROVED** [review]
LGTM
