### PR TITLE
c8d/inspect: Fix duplicate RepoDigests

### LINKED ISSUE #48747: c8d: image inspect should not contain duplicate RepoDigests
### Description

Taking the following example;

```bash
echo -e 'FROM alpine:latest\nLABEL foo=bar' | docker build \
    --tag localhost:5000/namespace1/myimage:latest \
    --tag localhost:5000/namespace1/myimage:1.0.0 \
    --tag localhost:5000/namespace2/myimage:latest \
    --tag localhost:5000/namespace2/myimage:1.0.0 \
    -
```

### Without containerd store

We need to push the images to have their digest produced (this is not needed with the containerd image store enabled)

```bash
docker push --all-tags localhost:5000/namespace1/myimage
docker push --all-tags localhost:5000/namespace2/myimage
```

After this, inspecting shows that there's no duplicates in the `RepoDigests`;

```bash
docker image inspect --format '{{json .RepoDigests}}' localhost:5000/namespace1/myimage:latest | jq
[
  "localhost:5000/namespace1/myimage@sha256:098a58165c88f57b276cf9bcb81087c3fc3be14f27320b83f0988829d4e856fc",
  "localhost:5000/namespace2/myimage@sha256:098a58165c88f57b276cf9bcb81087c3fc3be14f27320b83f0988829d4e856fc"
]
```

### With containerd store

With the containerd image store enabled, each tag of the image also produces an entry in the digests;

```bash
docker image inspect --format '{{json .RepoDigests}}' localhost:5000/namespace1/myimage:latest | jq
[
  "localhost:5000/namespace1/myimage@sha256:3b3bdb5db88500448c1588a124645d9d1c0a95c7476351e76b80a663582996fd",
  "localhost:5000/namespace1/myimage@sha256:3b3bdb5db88500448c1588a124645d9d1c0a95c7476351e76b80a663582996fd",
  "localhost:5000/namespace2/myimage@sha256:3b3bdb5db88500448c1588a124645d9d1c0a95c7476351e76b80a663582996fd",
  "localhost:5000/namespace2/myimage@sha256:3b3bdb5db88500448c1588a124645d9d1c0a95c7476351e76b80a663582996fd"
]
```

### Reproduce

see above

### Expected behavior

The list of `RepoDigests` should be unique.  We should remove duplicates from the list.

### docker version

```console
Client:
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:38:18 2024
 OS/Arch:           darwin/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:39:57 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v1.7.22
  GitCommit:        7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc:
  Version:          1.1.14
  GitCommit:        v1.1.14-0-g2c9f560
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

not relevant

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by vvoland**
- fixes: https://github.com/moby/moby/issues/48747

Multiple images with the same repository name but different tag caused the `RepoDigests` to contain duplicated entries for each of the image.

Use a set instead of a slice to store the digested references to avoid the duplicated values.

**- How to verify it**
TestImageInspectUniqueRepoDigests

**- Description for the changelog**

```markdown changelog
containerd image store: Fix `docker image inspect` outputting duplicate references in `RepoDigests`.
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: daemon/containerd/image_inspect.go [hunk 1]
```diff
@@ -14,6 +14,7 @@ import (
 	imagetypes "github.com/docker/docker/api/types/image"
 	"github.com/docker/docker/api/types/storage"
 	ocispec "github.com/opencontainers/image-spec/specs-go/v1"
+	"golang.org/x/exp/maps"
```
Comment (thaJeztah) [inline daemon/containerd/image_inspect.go:17]: I think this is now in stdlib? (we should avoid depending on `golang.org/x/exp`)

Comment (thaJeztah) [reply daemon/containerd/image_inspect.go:17]: oh, but _if_ we use `stdlib`, we likely need to add a `//go:build go1.21` built-tag (but check with https://github.com/moby/moby/pull/46941)

**Comment by thaJeztah** [comment]
@vvoland looks like someone else also just opened a PR for this 😂 

- https://github.com/moby/moby/pull/48780

File: daemon/containerd/image_inspect.go (hunk 1 above)
Comment (vvoland) [reply daemon/containerd/image_inspect.go:17]: `maps.Keys` was added in go 1.23. We're still on 1.22 in our `vendor.mod`.

Comment (vvoland) [reply daemon/containerd/image_inspect.go:17]: Added a TODO comment

Comment (thaJeztah) [reply daemon/containerd/image_inspect.go:17]: Could we implement a minimal helper for this? It feels like a very minimal enhancement for it to introduce that as a direct dependency (I'm pretty sure we have various other places where we have a small utility to get all keys from a map).

File: daemon/containerd/image_inspect.go [hunk 2]
```diff
@@ -101,9 +102,10 @@ func (i *ImageService) ImageInspect(ctx context.Context, refOrID string, _ backe
 	}
 
 	return &imagetypes.InspectResponse{
-		ID:            img.ImageID(),
-		RepoTags:      repoTags,
-		RepoDigests:   repoDigests,
+		ID:       img.ImageID(),
+		RepoTags: repoTags,
+		// TODO: Use maps.Keys from stdlib once we move the module to go >= 1.23
+		RepoDigests:   maps.Keys(repoDigests),
```
Comment (akerouanton) [inline daemon/containerd/image_inspect.go:108]: It seems the goal is to deduplicate `repoDigests`. FWIW, we've `sliceutil.Dedup` for that 😉

File: daemon/containerd/image_inspect.go (hunk 1 above)
Comment (thaJeztah) [reply daemon/containerd/image_inspect.go:17]: Actually, as we're already looping and already keeping track of duplicates, I wonder if we need it at all 🤔. here's a quick attempt without;

- https://github.com/vvoland/moby/pull/14

Comment (vvoland) [reply daemon/containerd/image_inspect.go]: Changed to `sliceutil.Dedup` as suggested by Albin.

Comment (thaJeztah) [reply daemon/containerd/image_inspect.go]: Ah, nice! Yes, that works

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Review by akerouanton — APPROVED** [review]

**Review by laurazard — APPROVED** [review]
