### PR TITLE
 Fix network alias issue with `network connect`

### LINKED ISSUE #33661: Network alias not working under certain steps
**Description**

After created an overlay network, container aliases won't take effect in the network.

**Steps to reproduce the issue:**

```bash
docker network create -d overlay --attachable test
docker create --network test --name ng1 nginx
docker network connect --alias aaa test ng1
docker start ng1
docker create --network test --name ng2 nginx
docker network connect --alias bbb test ng2
docker start ng2
```

**Describe the results you received:**
network aliases (bbb) is missing by docker inspect ng2 after docker start
```
...
"Networks": {
                "test": {
                    "IPAMConfig": {
                        "IPv4Address": "10.0.4.3"
                    },
                    "Links": null,
                    "Aliases": [
                        "0c4a9869d89f"
                    ],
                    "NetworkID": "kz9n6u9fqosjaui1ybc02nw5x",
                    "EndpointID": "c14340bd0e65e40519200d1db12bb76064b0fa2983b76c5c0cfc6f0b7747032c",
                    "Gateway": "",
                    "IPAddress": "10.0.4.3",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:0a:00:04:03"
                }
            }
```

**Describe the results you expected:**
```
...
"Networks": {
                "test": {
                    "IPAMConfig": {
                        "IPv4Address": "10.0.4.3"
                    },
                    "Links": null,
                    "Aliases": [

                        "bbb",  <--------------------- should have this

                        "0c4a9869d89f"
                    ],
                    "NetworkID": "kz9n6u9fqosjaui1ybc02nw5x",
                    "EndpointID": "c14340bd0e65e40519200d1db12bb76064b0fa2983b76c5c0cfc6f0b7747032c",
                    "Gateway": "",
                    "IPAddress": "10.0.4.3",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:0a:00:04:03"
                }
            }
```

**Additional information you deem important (e.g. issue happens only occasionally):**

The problem is that all aliases (bbb ccc ...) added by **docker create + network connect --alias + start** (ng2 ng3 ...) won't take effect after the first one (ng1 is ok).

There are many hacky ways to skip this. By **docker create --network-alias + start** ng2 alias is fine. And by **docker create + network disconnect + network connect --alias + start** ng2 alias is ok as well. Also by **docker create --network default/bridge + network connect --alias + start** it has the proper network aliases in test network but will be added into an extra bridge network which is not good.

Hope the information above can help other people who is facing this issue.

Another observation is by:

```
docker network create -d overlay --attachable test2
docker create --network **none** --name ng1 nginx
docker network connect --alias aaa test2 ng1
docker start ng1
docker create --network **none** --name ng2 nginx
docker network connect --alias bbb test2 ng2
```

only connecting ng2 will report error:
**Error response from daemon: container cannot be connected to multiple networks with one of the networks in private (none) mode**

I guess the first container attached into a network is kinda special. This is also why aliases of ng1 above is working.

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 18
 Running: 16
 Paused: 0
 Stopped: 2
Images: 343
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 322
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: e7gvsxeruiusmkmro82gsx99h
 Is Manager: true
 ClusterID: 1hwq82z13p4oxxx45t2nn63ca
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.99.1
 Manager Addresses:
  192.168.99.1:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.0-79-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 19.48GiB
Name: xihan-ThinkPad-T460s
ID: BLXA:HPCE:AUU4:L2UI:W77D:4ROF:KNBF:ET74:QYZB:V7BB:AEE2:KHSA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Experimental: false
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by yongtang**
**- What I did**

This fix tries to address the issue raised in #33661 where network alias does not work when connect to a network the second time.

This fix address the issue by updating the network settings when `connect`

**- How I did it**

**- How to verify it**

An integration test has been added.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

ayxirim

This fix fixes #33661.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
ooooh, thanks! I had this one on my list to look into, but didn't find the time 🤗

File: daemon/container_operations.go [hunk 1]
```diff
@@ -258,8 +258,7 @@ func (daemon *Daemon) updateNetworkSettings(container *container.Container, n li
 		}
 
 		if sn.Name() == n.Name() {
-			// Avoid duplicate config
```
Comment (thaJeztah) [inline daemon/container_operations.go]: Wondering: should `sn.Name() == n.Name()` also check for `ID`?

**Comment by thaJeztah** [comment]
Failure could be related; https://jenkins.dockerproject.org/job/Docker-PRs-experimental/38674/console

restarting builds to be sure

```
20:02:02 ----------------------------------------------------------------------
20:02:02 FAIL: docker_cli_network_unix_test.go:1625: DockerSuite.TestDockerNetworkConnectFailsNoInspectChange
20:02:02 
20:02:02 docker_cli_network_unix_test.go:1637:
20:02:02     c.Assert(ns1, check.Equals, ns0)
20:02:02 ... obtained string = "{0xc420357940 [] []     0   0  map[]}"
20:02:02 ... expected string = "{<nil> [] [] 0f01c5e68e86c73146cc32eab1b0e052543451cb46a4f41f1297b210c7783e25 b5cf077c3d4f5ab9c6d3746c7ac662dae586a0c1d39d6cbd7dfa48d8ac8814b6 172.18.0.1 172.18.0.2 16   0 02:42:ac:12:00:02 map[]}"
20:02:02 
```

**Comment by yongtang** [comment]
Thanks @thaJeztah, I think the Jenkins failure has been fixed. Please take a look.

**Review by vdemeester — APPROVED** [review]
LGTM 👍

File: api/server/router/network/network_routes.go [hunk 2]
```diff
@@ -275,12 +275,7 @@ func (n *networkRouter) postNetworkConnect(ctx context.Context, w http.ResponseW
 		return err
 	}
 
-	// Always make sure there is no ambiguity with respect to the network ID/name
```
Comment (thaJeztah) [inline api/server/router/network/network_routes.go]: Was this part of the problem? Sorry, having trouble understanding this change 😅 (this was added in https://github.com/moby/moby/commit/cafed80cd019a8b40025eaa5e5b37459362607fb)

Comment (yongtang) [reply api/server/router/network/network_routes.go]: Thanks @thaJeztah for the review. 

I added comments in the code to explain the reason for non-ambiguity check. Basically at the time of `connect` the attachable network may not be available so resolving name to ID will not work. On the other hand, the name collision check will be handled by the daemon in this case anyway so the check has been removed.

The PR has been updated.

File: api/server/router/network/network_routes.go [hunk 3]
```diff
@@ -275,12 +275,11 @@ func (n *networkRouter) postNetworkConnect(ctx context.Context, w http.ResponseW
...
-	nw, err := n.backend.FindNetwork(vars["id"])
-	if err != nil {
-		return err
-	}
-	return n.backend.ConnectContainerToNetwork(connect.Container, nw.ID(), connect.EndpointConfig)
+	// Unlike other operations, we does not check ambiguity of the name/ID here.
```
Comment (thaJeztah) [inline api/server/router/network/network_routes.go]: nit: `s/does/do/` (no need to fix) 😄

File: api/server/router/network/network_routes.go [hunk 4]
```diff
@@ -275,12 +275,11 @@ func (n *networkRouter) postNetworkConnect(ctx context.Context, w http.ResponseW
...
+	// The reason is that, In case of attachable network in swarm scope, the actual local network
+	// may not be available at the time. At the same time, inside daemon `ConnectContainerToNetwork`
```
Comment (thaJeztah) [inline api/server/router/network/network_routes.go]: Won't the problem be the same if looking up the network is done daemon-side? `daemon.ConnectToNetwork()` also looks up the network using `FindNetwork()`, which in itself won't _create_ the network on the node? https://github.com/moby/moby/blob/6feae060033544985e548dcf1b9127f8f634fe2b/daemon/container_operations.go#L995-L1016

Comment (thaJeztah) [reply api/server/router/network/network_routes.go]: Oh, right so, that's for the "stopped container" case, for the "running container", it eventually comes to `findAndAttachNetwork ()`, which looks to be extending the network; https://github.com/moby/moby/blob/6feae060033544985e548dcf1b9127f8f634fe2b/daemon/container_operations.go#L376-L416

There's a lot of "magic" in those functions; perhaps we should consider moving some of that magic out, and explicitly request a network to be extended, idk

**Review by thaJeztah — APPROVED** [review]
LGTM

ping @fcrisciani

**Comment by fcrisciani** [comment]
LGTM
