### PR TITLE
TestApiStatsContainerGetMemoryLimit: Add cgroup memory test

### LINKED ISSUE #22477: s390x: integration-cli: TestApiStatsContainerGetMemoryLimit failing
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.4.2 gccgo (GCC) 5.3.0
 Git commit:   9837ec4
 Built:        Tue May  3 16:28:13 2016
 OS/Arch:      linux/s390x

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.4.2 gccgo (GCC) 5.3.0
 Git commit:   9837ec4
 Built:        Tue May  3 16:28:13 2016
 OS/Arch:      linux/s390x
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 42
Server Version: 1.12.0-dev
Storage Driver: overlay
 Backing Filesystem: xfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null bridge host
Kernel Version: 4.5.0-1-s390x
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: s390x
CPUs: 2
Total Memory: 31.38 GiB
Name: lxdeb06
ID: NMHJ:TTO3:G5HA:AVLO:2OIQ:LSYE:GCXS:BRM7:IEIZ:ZKLS:BRDR:GVP7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
Insecure Registries:
 127.0.0.0/8
```

On s390x currently the following test case of integration-cli is failing:

```
# TESTFLAGS='-check.f DockerSuite.TestApiStatsContainerGetMemoryLimit' \
        DOCKER_GRAPHDRIVER=vfs DOCKER_EXECDRIVER=native TIMEOUT="120m" \
        DOCKER_ENGINE_OSARCH="linux/s390x" \
        hack/make.sh gccgo test-integration-cli
...
FAIL: docker_api_stats_test.go:231: TestApiStatsContainerGetMemoryLimit.pN52_github_com_docker_docker_integration_cli.DockerSuite

docker_api_stats_test.go:256:
    c.Assert(fmt.Sprintf("%d", v.MemoryStats.Limit), checker.Equals, fmt.Sprintf("%d", info.MemTotal))
... obtained string = "0"
... expected string = "33759145984"
```

When starting Docker I get the warning "WARN[0001] Your kernel does not support cgroup memory limit":

```
# docker daemon -s overlay
INFO[0000] New containerd process, pid: 26505           
INFO[0001] Graph migration to content-addressability took 0.00 seconds 
INFO[0001] Firewalld running: false                     
INFO[0001] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address 
WARN[0001] Your kernel does not support cgroup memory limit 
INFO[0001] Loading containers: start.                   
.
INFO[0001] Loading containers: done.                    
INFO[0001] Daemon has completed initialization          
INFO[0001] Docker daemon                                 commit=9837ec4 graphdriver=overlay version=1.12.0-dev
INFO[0001] API listen on /var/run/docker.soc
```

### PR DESCRIPTION
**Pull request by michael-holzheu**
Currently on kernels booted without the "cgroup_enable=memory" kernel
parameter the testcase TestApiStatsContainerGetMemoryLimit fails with:

FAIL: docker_api_stats_test.go:231: TestApiStatsContainerGetMemoryLimit.pN52_github_com_docker_docker_integration_cli.DockerSuite

docker_api_stats_test.go:256:
    c.Assert(fmt.Sprintf("%d", v.MemoryStats.Limit), checker.Equals, fmt.Sprintf("%d", info.MemTotal))
... obtained string = "0"
... expected string = "33759145984"

Fix this and skip the testcase if the kernel does not support cgroup memory
limit. In that case the output would be:

SKIP: docker_api_stats_test.go:231:
TestApiStatsContainerGetMemoryLimit.pN52_github_com_docker_docker_integration_cli.DockerSuite
(kernel does not support cgroup memory limit)

Fixes #22477

Signed-off-by: Michael Holzheu holzheu@linux.vnet.ibm.com

### CODE REVIEW

File: integration-cli/docker_api_stats_test.go [hunk 1]
```diff
@@ -231,6 +231,9 @@ func (s *DockerSuite) TestApiStatsContainerNotFound(c *check.C) {
 func (s *DockerSuite) TestApiStatsContainerGetMemoryLimit(c *check.C) {
 	testRequires(c, DaemonIsLinux)
 
+	if !isCgroupMounted("memory") {
```
Comment (thaJeztah) [inline integration-cli/docker_api_stats_test.go]: Perhaps this should be implemented as a testRequirement, see; https://github.com/docker/docker/blob/fd67c8b2031722dd9255996b84bbfb236ce45cfb/integration-cli/requirements.go#L25-L183

Then the line above can become (for example) `testRequires(c, DaemonIsLinux, MemoryCgroup)`

File: integration-cli/docker_api_stats_test.go [hunk 2]
```diff
@@ -231,6 +231,9 @@ func (s *DockerSuite) TestApiStatsContainerNotFound(c *check.C) {
 func (s *DockerSuite) TestApiStatsContainerGetMemoryLimit(c *check.C) {
 	testRequires(c, DaemonIsLinux)
```
Comment (tophj-ibm) [inline integration-cli/docker_api_stats_test.go]: Check out https://github.com/docker/docker/blob/master/integration-cli/requirements_unix.go , it looks like you can just add one of the memory ones to the testRequires here.

File: integration-cli/utils.go [hunk 3]
```diff
@@ -83,3 +84,26 @@ func parseCgroupPaths(procCgroupData string) map[string]string {
 func runAtDifferentDate(date time.Time, block func()) {
 	integration.RunAtDifferentDate(date, block)
 }
+
+func findCgroupMountpoints() map[string]string {
+	cgMounts, err := cgroups.GetCgroupMounts()
```
Comment (thaJeztah) [inline integration-cli/utils.go]: This won't work on windows;

```
14:58:58 + go test -check.v -check.timeout=120m -test.timeout=360m github.com/docker/docker/integration-cli
14:59:26 # github.com/docker/docker/integration-cli
14:59:26 C:\Users\Jenkins\AppData\Local\Temp\go-build629334114\github.com\docker\docker\integration-cli\_test\_obj_test\utils.go:110: undefined: cgroups.GetCgroupMounts
14:59:26 + ec=1
14:59:26 + set +x
```

File: integration-cli/docker_api_stats_test.go (hunk 1 above)
Comment (thaJeztah) [inline integration-cli/docker_api_stats_test.go]: Hm, thinking of this; this check should be performed on the *daemon*, not on the client (which may be on a different host and platform). This may become more complicated than I anticipated; we cannot use `SameHostDaemon` as a requirement for the test, because we also want this test to be run on (e.g.) a Windows client against a Linux daemon.

@vdemeester do you have any ideas how to solve that?

File: integration-cli/utils.go (hunk 3 above)
Comment (michael-holzheu) [inline integration-cli/utils.go]: So util.c is the wrong place for the code. Where should it be?

Comment (thaJeztah) [inline integration-cli/utils.go]: The utility probably need to be split up to utils, utils_windows and utils_linux, however the problem remains that the test should depend on the *daemon* implementing it, and the test is run on the client, so that makes it tricky (probably the only solution would be to expose this information through the API, but that may be too much it its only used for integration tests

Comment (michael-holzheu) [inline integration-cli/utils.go]: > however the problem remains that the test should depend on the daemon implementing it, and the test is run on the client

Well, isn't that also the case for "UserNamespaceInKernel"  in requirements.go?

```
        UserNamespaceInKernel = testRequirement{
                func() bool {
                        if _, err := os.Stat("/proc/self/uid_map"); os.IsNotExist(err) {
                                /*
                                 * This kernel-provided file only exists if user namespaces are
                                 * supported
                                 */
                                return false
                        }
```

Comment (michael-holzheu) [inline integration-cli/utils.go]: > Well, isn't that also the case for "UserNamespaceInKernel" in requirements.go?

Ah... got it: UserNamespaceInKernel is always specified together with "SameHostDaemon".

File: integration-cli/docker_api_stats_test.go (hunk 2 above)
Comment (michael-holzheu) [inline integration-cli/docker_api_stats_test.go]: > Check out https://github.com/docker/docker/blob/master/integration-cli/requirements_unix.go , it looks like you can just add one of the memory ones to the testRequires here.

Thanks Chris! "memoryLimitSupport" is already defined in requirements_unix.go. So the patch would simply look like the following (seems to work):

```
diff --git a/integration-cli/docker_api_stats_test.go b/integration-cli/docker_api_stats_test.go
index 0e2aa00..a1e4c8b 100644
--- a/integration-cli/docker_api_stats_test.go
+++ b/integration-cli/docker_api_stats_test.go
@@ -229,7 +229,7 @@ func (s *DockerSuite) TestApiStatsContainerNotFound(c *check.C) {
 }
 
 func (s *DockerSuite) TestApiStatsContainerGetMemoryLimit(c *check.C) {
-       testRequires(c, DaemonIsLinux)
+       testRequires(c, DaemonIsLinux, memoryLimitSupport)
 
        resp, body, err := sockRequestRaw("GET", "/info", nil, "application/json")
        c.Assert(err, checker.IsNil)
```

Comment (vdemeester) [inline integration-cli/docker_api_stats_test.go]: Hum if it's defined on a `_unix.go` file then it will fail on windows platform if you use it in this file (there might be/need a `docker_api_stats_unix_test.go` with a build tag then…).

File: integration-cli/docker_api_stats_test.go (hunk 1 above)
Comment (vdemeester) [inline integration-cli/docker_api_stats_test.go]: We should add some daemon requirement on these limits. It seems it could work as the `/info` endpoint returns `"KernelMemory": true` and `"MemoryLimit": true`, so we could check the daemon when/on running tests (but it's gonna be tricky to do – adding this to my TODO).

File: integration-cli/docker_api_stats_test.go (hunk 2 above)
Comment (michael-holzheu) [inline integration-cli/docker_api_stats_test.go]: Obviously you are right: .\docker_api_stats_test.go:232: undefined: memoryLimitSupport

Comment (michael-holzheu) [inline integration-cli/docker_api_stats_test.go]: I updated the PR and moved the test to `docker_api_stats_unix_test.go`.

**Comment by tonistiigi** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐯
