### PR TITLE
pkg: chrootarchive: chroot_linux: fix mount leak

### LINKED ISSUE #23417: Build Mounts in Docker Master
Running docker master after I have done some builds, `make binary` `make test` after stopping the daemon if I run the `mount` command I get this output with a bunch of tmp build mounts still alive.

```
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,relatime,size=3824368k,nr_inodes=956092,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,noexec,relatime,size=768784k,mode=755)
/dev/sda1 on / type ext4 (rw,relatime,errors=remount-ro,data=ordered)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd,nsroot=/)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio,nsroot=/)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer,nsroot=/)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event,nsroot=/)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb,nsroot=/)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices,nsroot=/)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids,nsroot=/)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct,nsroot=/)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio,nsroot=/)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory,nsroot=/)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset,nsroot=/)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=23,pgrp=1,timeout=0,minproto=5,maxproto=5,direct)
mqueue on /dev/mqueue type mqueue (rw,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
sunrpc on /run/rpc_pipefs type rpc_pipefs (rw,relatime)
tracefs on /sys/kernel/debug/tracing type tracefs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
nfsd on /proc/fs/nfsd type nfsd (rw,relatime)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
/dev/sda1 on /var/lib/docker/overlay type ext4 (rw,relatime,errors=remount-ro,data=ordered)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=768784k,mode=700,uid=1000,gid=1000)
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
/dev/sda1 on /var/lib/docker/tmp/docker-builder081278936 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder429897389 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder338705622 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder315924899 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder525955492 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder903628713 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder494042562 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder047208511 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder425351344 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder685650661 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder040860654 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder951310107 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder272127740 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder026812513 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder667016538 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder007390263 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder312302216 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder643337245 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder024182790 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder522281875 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder591585620 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder970362905 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder111831026 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder545122607 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder711340384 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder082185813 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder458614046 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder179275019 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder646734087 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder457831576 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder624099949 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder893832086 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder664878435 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder782271076 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder910333289 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder292096642 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder504297471 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder934851440 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder199315621 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder395919534 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder655585499 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder731823036 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder836236833 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder336770074 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder765449207 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder097552712 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder552945117 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder078938310 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder386985299 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder372663316 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder030500825 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder817485557 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder774527569 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder254418698 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder251810070 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder598964963 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder470602212 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder760633577 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder749044220 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder581491553 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder709048317 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder249559769 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder028089778 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder276371439 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder147792672 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder483076885 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder691219166 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder654332875 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder190197868 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder765089681 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder961571146 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder515223015 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder641763875 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder826086948 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder400018985 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder321226309 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder751904929 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder493144730 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder069002662 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder756344306 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder987365679 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder805567328 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder697206357 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder544996126 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder364024587 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder820574892 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder413570257 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder848258669 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder983171145 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder591855904 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder061487511 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder680913346 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder597507473 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /var/lib/docker/tmp/docker-builder082481204 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
```

### PR DESCRIPTION
**Pull request by runcom**
When pivot_root fails we need to unmount the bind mounted path we
previously mounted in preparation for pivot_root.

Fix #23417

This is hopefully the last leak when pivot_root fails.
Found with:

```
$ docker build -t test - <<EOF
FROM busybox         
EOF
$ sudo systemctl stop docker
$ sudo rm -rf /var/lib/docker 
rm: cannot remove '/var/lib/docker/tmp/docker-builder054675383': Device or resource busy
$ mount
[...]
/dev/mapper/fedora-root on /var/lib/docker/tmp/docker-builder054675383 type ext4 (rw,relatime,seclabel,data=ordered)
```

After this patch the mounts are cleaned up when doing chroot+chdir (so when pivot_root fails)

related to https://github.com/docker/docker/pull/22603

Signed-off-by: Antonio Murdaca runcom@redhat.com

### CODE REVIEW

**Comment by runcom** [comment]
@cpuguy83 @LK4D4

**Comment by runcom** [comment]
I can still this though:

```
/dev/mapper/fedora-root on /var/lib/docker/overlay type ext4 (rw,relatime,seclabel,data=ordered)
```

**Comment by cpuguy83** [comment]
I think the issue is that when we call the reexec we need to set `SysProcAttr.Cloneflags` rather than calling `syscall.Unshare`

**Comment by runcom** [comment]
This patch does fix the issue above - but if you think that's better I'll modify the patch as you said

**Comment by cpuguy83** [comment]
Yeah, we really shouldn't be leaking mounts because it created a new mount namespace first, but there are issues with calling `Unshare` here, it either needs to be done with `LockOSThread` or via the CloneFlags in the reexec command.
@LK4D4 mentioned it would be better to use CloneFlags.

**Comment by runcom** [comment]
alright, that means we should modify `reexec.Command` to take clone flags

**Comment by runcom** [comment]
@cpuguy83 @LK4D4 edited the code to clone with mount ns but the umount call is still needed, otherwise the mount is still leaked to the host

File: pkg/chrootarchive/chroot_linux.go [hunk 1]
```diff
@@ -54,7 +50,10 @@ func chroot(path string) (err error) {
 	}()
 
 	if err := syscall.PivotRoot(path, pivotDir); err != nil {
-		// If pivot fails, fall back to the normal chroot after cleaning up temp dir for pivot_root
+		// If pivot fails, fall back to the normal chroot after cleaning up temp dir and mount for pivot_root
+		if err := syscall.Unmount(path, syscall.MNT_DETACH); err != nil {
```
Comment (LK4D4) [inline pkg/chrootarchive/chroot_linux.go]: Is `DETACH` necessary? I thought it's sorta async and you're going to do something with it right after.

Comment (runcom) [inline pkg/chrootarchive/chroot_linux.go]: it shouldn't be needed, what should I put there? FORCE?

Comment (LK4D4) [inline pkg/chrootarchive/chroot_linux.go]: Maybe just 0, that's what we use in other places.

Comment (runcom) [inline pkg/chrootarchive/chroot_linux.go]: fixed

**Comment by runcom** [comment]
@LK4D4 using 0 in Unmont totally broke my system and I had to reboot

**Comment by LK4D4** [comment]
@runcom hahaha.

**Comment by runcom** [comment]
@LK4D4 not funny :*(

**Comment by runcom** [comment]
this is totally blowing my laptop now

**Comment by mrunalp** [comment]
Is the code handling making the old root rprivate? Else it will leak mounts to the host mount namespace. cc: @rhvgoyal

**Comment by runcom** [comment]
current master code isn't blowing my laptop, I still see leaks though:
```
/dev/mapper/fedora-root on /var/lib/docker/tmp/docker-builder247594755 type ext4 (rw,relatime,seclabel,data=ordered)
/dev/mapper/fedora-root on /var/lib/docker/tmp/docker-builder401369110 type ext4 (rw,relatime,seclabel,data=ordered)
/dev/mapper/fedora-root on /var/lib/docker/tmp/docker-builder480863573 type ext4 (rw,relatime,seclabel,data=ordered)
```

**Comment by LK4D4** [comment]
We need to do something here :/ ping @runcom @rhvgoyal

**Comment by thaJeztah** [comment]
ping @runcom @LK4D4 what's the status here?

**Comment by runcom** [comment]
I'm still working on this - need to figure out the whole mount propagation stuff

**Comment by thaJeztah** [comment]
let me rename it to WIP for now then

**Comment by cpuguy83** [comment]
Any news?

**Comment by runcom** [comment]
I've asked @rhvgoyal to take a look at this also

**Comment by crosbymichael** [comment]
Testing this

**Comment by runcom** [comment]
This is not working atm - needs something along @mrunalp's comment above

**Comment by crosbymichael** [comment]
Ya, i'm testing and will look at a fix

**Comment by crosbymichael** [comment]
Does anyone know why this is doing a pivot root and not a chroot?

**Comment by runcom** [comment]
@crosbymichael it has been introduced here https://github.com/docker/docker/pull/22506

**Comment by crosbymichael** [comment]
I've been looking at this and i'm pretty lost right now.  With your changes it totally destroys the system that it is running on and i cannot seem to see what the problem is right now.  We are being place inside a new mount ns but all the propagation junk is causing the entire systems mounts to be removed when it fails

**Comment by runcom** [comment]
I'm stuck there as well, my system is blowing after a build and I cannot see what's happened. There has to be some propagation step somewhere which makes this blows (probably in overlayfs path)

File: pkg/chrootarchive/archive_unix.go [hunk 2]
```diff
@@ -60,6 +61,7 @@ func invokeUnpack(decompressedArchive io.Reader, dest string, options *archive.T
 	cmd := reexec.Command("docker-untar", dest)
 	cmd.Stdin = decompressedArchive
 
+	cmd.SysProcAttr.Cloneflags |= syscall.CLONE_NEWNS
```
Comment (cpuguy83) [inline pkg/chrootarchive/archive_unix.go]: For some reason this is what's screwing up on my centos box

**Comment by cpuguy83** [comment]
https://gist.github.com/cpuguy83/cf69758a80fcdf7aee9e3e74b6227a43 seems to fix issues when using rshared (ie, when falling back to chroot).
Can you test?

**Comment by runcom** [comment]
@cpuguy83 your patch works for me - just dubious about MNT_DETACH as per @LK4D4 comment above https://github.com/docker/docker/pull/22631#discussion_r62704308

**Comment by runcom** [comment]
tests are also green ping @cpuguy83 @LK4D4 @crosbymichael

**Comment by cpuguy83** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Comment by runcom** [comment]
cool, @crosbymichael does it fix the leaks for you also?
