### PR TITLE
Layerstore refactor rw layer

### LINKED ISSUE #18753: Race between daemon register and mount. Pointed by DockerSuite.TestRunAttachDetach
```
----------------------------------------------------------------------
FAIL: docker_cli_run_unix_test.go:91: DockerSuite.TestRunAttachDetach

docker_cli_run_unix_test.go:101:
    c.Assert(waitRun(name), check.IsNil)
... value *errors.errorString = &errors.errorString{s:"error executing docker inspect: exit status 1\n\nError response from daemon: mount does not exist\n"} ("error executing docker inspect: exit status 1\n\nError response from daemon: mount does not exist\n")
```

### PR DESCRIPTION
**Pull request by dmcgowan**
Updates the layer interface to have a RW layer with a more complete interface. RW layer objects are now more powerful and individually reference counted. This change allows for separating the creation of the RW layer from when it is mounted. Container will now always have a reference to the RW layerr.

Fixes race between creating a writable layer and registering a container.

Fixes #18753 

Additional refactoring should be done the container create process. Currently ordering is ambiguous and there are still periods of time between a container being visible, fully setup, and saved to disk that make the process prone to races.

ping @tonistiigi @LK4D4

### CODE REVIEW

File: layer/layer_store.go [hunk 1]
```diff
@@ -473,17 +410,12 @@ func (ls *layerStore) Mount(name string, parent ChainID, mountLabel string, init
...
-		mountID = stringid.GenerateRandomID()
-	}
-
 	m = &mountedLayer{
 		name:       name,
 		parent:     p,
-		mountID:    mountID,
+		mountID:    ls.mountID(name),
 		layerStore: ls,
+		references: map[RWLayer]*referencedRWLayer{},
```
Comment (tonistiigi) [inline layer/layer_store.go]: That's bit of a strage construction where `key == value`. Maybe a slice would be enough.

File: layer/mounted_layer.go [hunk 2]
```diff
@@ -47,6 +49,96 @@ func (ml *mountedLayer) Parent() Layer {
...
+}
+
+type referencedRWLayer struct {
+	*mountedLayer
+
+	activityL     sync.Mutex
+	activityCount int
+}
+
+func (rl *referencedRWLayer) unretain() error {
```
Comment (tonistiigi) [inline layer/mounted_layer.go]: `release()` ?

File: layer/migration.go [hunk 3]
```diff
@@ -14,30 +14,33 @@ import (
 	"github.com/vbatts/tar-split/tar/storage"
 )
 
-func (ls *layerStore) MountByGraphID(name string, graphID string, parent ChainID) (l RWLayer, err error) {
+// MountByGraphID creates a RWLayer in the layer store using
+// the provided name with the given graphID. To get the RWLayer
+// after migration the layer may be retrieved by the given name.
+func (ls *layerStore) MountByGraphID(name string, graphID string, parent ChainID) (err error) {
```
Comment (tonistiigi) [inline layer/migration.go]: As this doesn't mount any more, maybe we should call it `CreateRWLayerByGraphID`

File: layer/layer_store.go (hunk 1 above)
Comment (dmcgowan) [inline layer/layer_store.go]: It is different enough in that it needs to be looked up by interface reference and I need a reference to the underlying object. I would prefer not to do a type assertion even though it should not error.

File: layer/mounted_layer.go (hunk 2 above)
Comment (dmcgowan) [inline layer/mounted_layer.go]: agreed

File: layer/migration.go (hunk 3 above)
Comment (dmcgowan) [inline layer/migration.go]: I will update this, I did kind of find this terminology weird while updating

**Comment by tonistiigi** [comment]
LGTM

File: layer/layer_unix.go [hunk 4]
```diff
@@ -0,0 +1,9 @@
+// +build linux freebsd darwin
+
+package layer
+
+import "github.com/docker/docker/pkg/stringid"
+
+func (ls *layerStore) mountID(name string) string {
+	return stringid.GenerateRandomID()
```
Comment (cpuguy83) [inline layer/layer_unix.go]: GenerateNonCryptoID?

**Comment by cpuguy83** [comment]
LGTM
