### PR TITLE
Fix the create API when fromSrc has a bad URL

### LINKED ISSUE #30714: Inconsistent API response
**Description**

incorrect images/create API call returns response 200 OK and 2 json messages, one of them is error description

**Steps to reproduce the issue:**
`$ curl -v --unix-socket /var/run/docker.sock -X POST "http:/v1.25/images/create?repo=acme.com%2Ftest&fromSrc=%2Fdata%2Ffile.tar"`
or
```
import docker
d = docker.from_env()
print(d.images.client.api.import_image("/data/file.tar", "acme.com/test"))
```

**Describe the results you received:**
```
*   Trying /var/run/docker.sock...
* Connected to http (/var/run/docker.sock) port 80 (#0)
> POST /v1.25/images/create?repo=acme.com%2Ftest&fromSrc=%2Fdata%2Ffile.tar HTTP/1.1
> Host: http
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Api-Version: 1.25
< Content-Type: application/json
< Docker-Experimental: true
< Server: Docker/1.13.0 (linux)
< Date: Fri, 03 Feb 2017 15:03:38 GMT
< Transfer-Encoding: chunked
<
{"status":"Downloading from http://%2Fdata%2Ffile.tar"}
{"errorDetail":{"message":"parse http://%2Fdata%2Ffile.tar: invalid URL escape \"%2F\""},"error":"parse http://%2Fdata%2Ffile.tar: invalid URL escape \"%2F\""}
* Connection #0 to host http left intact
```
or
```
{"status":"Downloading from http://%2Fdata%2Ffile.tar"}
{"errorDetail":{"message":"parse http://%2Fdata%2Ffile.tar: invalid URL escape \"%2F\""},"error":"parse http://%2Fdata%2Ffile.tar: invalid URL escape \"%2F\""}
```

**Describe the results you expected:**
I would expect non 200 response and single json message, so response could be parsed.

**Additional information you deem important (e.g. issue happens only occasionally):**
I'm using python docker API which does not raise exception on this incorrect request, as response code is 200. Also python API returns response as text and could not parse response if I specify json response type as there are 2 messages in response.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 19
 Running: 14
 Paused: 0
 Stopped: 5
Images: 102
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 110
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-59-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 30
Total Memory: 31.42 GiB
Name: jbuild
ID: TNIU:DAHP:PAIG:EGPV:HVX4:E4P6:KENQ:TOAX:QDEP:A3VD:JSPL:JQME
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 docker.acme.com
 registry-proxy.acme.com
 127.0.0.0/8
Registry Mirrors:
 registry-proxy.acme.com
Live Restore Enabled: true
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker daemon running in Ubuntu 16.04 VM on ESXi 6 host. Client is docker python API 2.0.2 running on physical Windows 10 host.

### PR DESCRIPTION
**Pull request by boaz0**
**- What I did**

When a bad URL is provided in the fromSrc parameter the response status code is set to 200 although the download fails.
This commit fixes this by making sure the resource is available.

Another problem this commit fixes is when sending a URL without specifying the protocol (f.e. google.com/file.tar) the parsed raw URL is encoded and causes the download to fail. 

should close #30714

**- How I did it**

Instead of setting `u.Host` after parsing the raw URL and checking that `u.Scheme` is empty, verify that `src` has a protocol using `strings.Split` and `len` and then `url.Parse` it.
In addition, switched between the "Downloading" message writing and the actual image downloading code lines.

**- How to verify it**

Run the following tests:
`TESTFLAGS='-check.f DockerSuite.TestAPIImagesImport*' make test-integration-cli`

### CODE REVIEW

**Comment by ripcurld0** [comment]
//cc @isanych

File: daemon/import.go [hunk 1]
```diff
@@ -60,15 +62,24 @@ func (daemon *Daemon) ImportImage(src string, repository, tag string, msg string
...
+		// status code 200 to the client although the download process will fail
+		resp, err = http.Head(u.String())
+		if err != nil {
+			return err
+		}
+		if resp.StatusCode >= http.StatusBadRequest {
+			return fmt.Errorf("Unable to read file in %s: %s", u, resp.Status)
 		}
+
 		outStream.Write(sf.FormatStatus("", "Downloading from %s", u))
```
Comment (tonistiigi) [inline daemon/import.go]: I assume this `Write` is causing the 200 statuscode. Moving it after the `httputils.Download` should be enough to get it to return an error code.

Comment (LK4D4) [inline daemon/import.go]: But it would be weird to write "Downloading" after download :)

Comment (ripcurld0) [inline daemon/import.go]: As @LK4D4 reasoned, what if a tar file that its size is >500MB is being downloaded then it takes time till the "Downloading from..." message appears and that's sad.

I do see what you are trying to say here -- I guess both ways make sense to me.
If you insist on using `httputils.Download` over sending a HTTP head request, I will do that. 😄

File: integration-cli/docker_api_images_test.go [hunk 2]
```diff
@@ -115,6 +115,29 @@ func (s *DockerSuite) TestAPIImagesHistory(c *check.C) {
...
 }
 
+func (s *DockerSuite) TestAPIImagesImportBadSrc(c *check.C) {
+	testRequires(c, Network)
+
+	tt := []struct {
+		statusExp int
+		fromSrc   string
+	}{
+		{http.StatusNotFound, "http://google.com/nofile.tar"},
```
Comment (thaJeztah) [inline integration-cli/docker_api_images_test.go]: can we use `example.com` for these?

File: daemon/import.go [hunk 3]
```diff
@@ -60,15 +62,24 @@ func (daemon *Daemon) ImportImage(src string, repository, tag string, msg string
...
-			u.Host = src
-			u.Path = ""
+
+		// Checking the file referenced by the URL exists to avoid sending
+		// status code 200 to the client although the download process will fail
+		resp, err = http.Head(u.String())
+		if err != nil {
+			return err
+		}
+		if resp.StatusCode >= http.StatusBadRequest {
```
Comment (AkihiroSuda) [inline daemon/import.go]: what happens on http 3xx?

Comment (ripcurld0) [inline daemon/import.go]: I assumed it would be redirected but I need to test that.
Thanks for noticing.

Comment (ripcurld0) [inline daemon/import.go]: OK I have tested it. It seems like the `http.Head` automatically check the redirected resource.
For example, I set a HTTP server that returns the following header:
```
HTTP/1.1 301 Moved Permanently
Location: /my_file/file.tar
Content-Length: 0
Content-Type: text/plain; charset=utf-8
```
Which was successfully downloaded.
However, when I removed the `Location` header, I got 500 in the response and the following error message in the body:
```
{"message":"Head http://172.17.0.1:9871/my_image: 301 response missing Location header"}
```

So it seems like 3xx is "covered".

File: integration-cli/docker_api_images_test.go (hunk 2 above)
Comment (ripcurld0) [inline integration-cli/docker_api_images_test.go]: DONE

File: daemon/import.go [hunk 4]
```diff
@@ -59,15 +61,24 @@ func (daemon *Daemon) ImportImage(src string, repository, tag string, msg string
...
 			return err
 		}
-		if u.Scheme == "" {
-			u.Scheme = "http"
-			u.Host = src
-			u.Path = ""
+
+		// Checking the file referenced by the URL exists to avoid sending
+		// status code 200 to the client although the download process will fail
+		resp, err = http.Head(u.String())
```
Comment (cpuguy83) [inline daemon/import.go]: Is this supported everywhere?

File: daemon/import.go (hunk 1 above)
Comment (cpuguy83) [inline daemon/import.go]: It's not really downloading anything until the response is consumed though, right?

File: daemon/import.go (hunk 4 above)
Comment (ripcurld0) [inline daemon/import.go]: what do you mean by that?

File: daemon/import.go (hunk 1 above)
Comment (ripcurld0) [inline daemon/import.go]: In this patch - no it's not.

File: daemon/import.go (hunk 3 above)
Comment (ripcurld0) [inline daemon/import.go]: Note to myself: to check it out when Docker will move to Go 1.8

File: daemon/import.go (hunk 4 above)
Comment (thaJeztah) [inline daemon/import.go]: Although bad practice, `HEAD` requests can be blocked / not supported. In that case, I think standard practice is that the client should fall back to a `GET`. Doing a `GET` here most likely won't make sense though

File: daemon/import.go (hunk 1 above)
Comment (thaJeztah) [inline daemon/import.go]: This sounds like the right approach. @ripcurld0 can you make these changes?

Comment (ripcurld0) [inline daemon/import.go]: 👍

File: daemon/import.go (hunk 4 above)
Comment (ripcurld0) [inline daemon/import.go]: Uh huh I understand.

**Comment by ripcurld0** [comment]
Grrr... powerpc failed (don't think it's because of my changes). 😢

**Comment by ripcurld0** [comment]
Great! Now windows failed 🤣  I can't catch a break.

**Comment by tiborvass** [comment]
Error is

```
03:08:44 ----------------------------------------------------------------------
03:08:44 FAIL: docker_cli_restart_test.go:265: DockerSuite.TestRestartContainerwithRestartPolicy
03:08:44 
03:08:44 docker_cli_restart_test.go:279:
03:08:44     dockerCmd(c, "restart", id2)
03:08:44 docker_utils_test.go:108:
03:08:44     c.Assert(result, icmd.Matches, icmd.Success)
03:08:44 ... result *cmd.Result = &cmd.Result{Cmd:(*exec.Cmd)(0xc04207cf20), ExitCode:1, Error:(*exec.ExitError)(0xc0454a5080), Timeout:false, outBuffer:(*cmd.lockedBuffer)(0xc042347290), errBuffer:(*cmd.lockedBuffer)(0xc042347320)} ("\nCommand:  d:\\CI\\CI-13c5a625f\\binary\\docker.exe restart 2b5e2548f2c55478b7ec99e4870f901098ce10f9feaaf24b4166d968d1292b0a\nExitCode: 1\nError:    exit status 1\nStdout:   \nStderr:   Error response from daemon: Cannot restart container 2b5e2548f2c55478b7ec99e4870f901098ce10f9feaaf24b4166d968d1292b0a: Cannot kill container 2b5e2548f2c55478b7ec99e4870f901098ce10f9feaaf24b4166d968d1292b0a: invalid container: 2b5e2548f2c55478b7ec99e4870f901098ce10f9feaaf24b4166d968d1292b0a\n\n")
03:08:44 ... expected cmd.Expected = cmd.Expected{ExitCode:0, Timeout:false, Error:"", Out:"", Err:""}
```

From https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS1/11863/console

Could be unrelated. Relaunching windows CI

**Comment by ripcurld0** [comment]
Thanks @tiborvass 🌷

**Comment by tiborvass** [comment]
LGTM

**Comment by tiborvass** [comment]
Ping @AkihiroSuda @thaJeztah

**Review by vdemeester — APPROVED** [review]
LGTM 🐸
