### PR TITLE
c8d: The authorizer needs to be set even if AuthConfig is empty

### LINKED ISSUE #45529: containerd-integration: `docker pull hello-world` fails with `pulling from host registry-1.docker.io failed with status code [manifests latest]: 401 Unauthorized.`
### Description

`docker pull hello-world` fails with containerd-integration mode

### Reproduce

1. Stop `dockerd` and `containerd`
2. `rm -rf /var/lib/{docker,containerd} /run/{docker,containerd}`
3. Create `/etc/docker/daemon.json`
```json
{"features":{"containerd-snapshotter":true}}
```
4. Start `dockerd`
5. `docker pull hello-world`
```console
# docker pull hello-world
Using default tag: latest
Error response from daemon: failed to resolve reference "docker.io/library/hello-world:latest": pulling from host registry-1.docker.io failed with status code [manifests latest]: 401 Unauthorized
```

### Expected behavior

`docker pull hello-world` should successfully pull the `hello-world` image

### docker version

```bash
Client: Docker Engine - Community
 Version:           24.0.0-rc.3
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        1d7dd91
 Built:             Thu May 11 19:25:21 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.0-rc.3
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       807e415
  Built:            Thu May 11 19:25:21 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    24.0.0-rc.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.3
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 24.0.0-rc.3
 Storage Driver: overlayfs
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.19.0-38-generic
 Operating System: Ubuntu 22.10
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.825GiB
 Name: lima-default
 ID: d28cb975-f75a-47e1-be32-22d1f7350521
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

The image can be successfully pulled with `"containerd-snapshotter": false`

### PR DESCRIPTION
**Pull request by rumpl**
**- What I did**

Without the authorizer pulling will fail if the user is not logged-in. 

Fixes #45529

Relates to #45517

**- How I did it**

We now only check if the auth config is nil (it actually never is), we don't check if it's empty.

**- How to verify it**

```console
$ docker logout
$ docker pull hello-world
```

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: daemon/containerd/resolver.go [hunk 1]
```diff
@@ -27,10 +27,7 @@ func (i *ImageService) newResolverFromAuthConfig(authConfig *registrytypes.AuthC
 func hostsWrapper(hostsFn docker.RegistryHosts, optAuthConfig *registrytypes.AuthConfig, regService RegistryConfigProvider) docker.RegistryHosts {
 	var authorizer docker.Authorizer
 	if optAuthConfig != nil {
-		auth := *optAuthConfig
-		if auth != (registrytypes.AuthConfig{}) {
-			authorizer = docker.NewDockerAuthorizer(authorizationCredsFromAuthConfig(auth))
-		}
+		authorizer = docker.NewDockerAuthorizer(authorizationCredsFromAuthConfig(*optAuthConfig))
```
Comment (thaJeztah) [inline daemon/containerd/resolver.go:30]: Should we add a comment somewhere to explain that it's always needed?

**Review by thaJeztah — APPROVED** [review]
LGTM (but left a suggestion)

File: daemon/containerd/resolver.go (hunk 1 above)
Comment (rumpl) [reply daemon/containerd/resolver.go:30]: It might confuse people? As is the code read well: "if the auth config is not nil, create the authorizer". 

The old code that also checked if it's empty would have needed a comment I think because it wasn't obvious why we need to check for nil _and_ empty

Comment (vvoland) [reply daemon/containerd/resolver.go:30]: Wouldn't it be more correct to ALWAYS set the authorizer, and decide whether we pass the AuthorizerOpt returned from `authorizationCredsFromAuthConfig` based on the AuthConfig?

Comment (vvoland) [reply daemon/containerd/resolver.go:30]: The current implementation will reintroduce https://github.com/moby/moby/issues/45397

Comment (rumpl) [reply daemon/containerd/resolver.go:30]: We can't if `optAuthConfig` is nil, it doesn't actually look that it's nil anyway:


https://github.com/moby/moby/blob/9e6370819bf61de7583ea00af13fcbedd2bbbfe7/api/types/registry/authconfig.go#L60

https://github.com/moby/moby/blob/9e6370819bf61de7583ea00af13fcbedd2bbbfe7/api/types/registry/authconfig.go#L84

Comment (rumpl) [reply daemon/containerd/resolver.go:30]: @vvoland It doesn't seem like it reintroduces #45397 

Pulling `hello-world` while logged-out shows me these logs:

```
DEBU[2023-05-12T10:02:22.582889639+02:00] Calling HEAD /_ping
DEBU[2023-05-12T10:02:22.583745921+02:00] Calling POST /v1.42/images/create?fromImage=hello-world&tag=latest
DEBU[2023-05-12T10:02:22.608561023+02:00] resolving                                     host=registry-1.docker.io
DEBU[2023-05-12T10:02:22.608632731+02:00] do request                                    host=registry-1.docker.io request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" request.header.user-agent=containerd/1.6.21+unknown request.method=HEAD url="https://registry-1.docker.io/v2/library/hello-world/manifests/latest"
DEBU[2023-05-12T10:02:23.007997174+02:00] fetch response received                       host=registry-1.docker.io response.header.content-length=162 response.header.content-type=application/json response.header.date="Fri, 12 May 2023 08:02:22 GMT" response.header.docker-distribution-api-version=registry/2.0 response.header.docker-ratelimit-source=62.35.48.5 response.header.strict-transport-security="max-age=31536000" response.header.www-authenticate="Bearer realm=\"https://auth.docker.io/token\",service=\"registry.docker.io\",scope=\"repository:library/hello-world:pull\"" response.status="401 Unauthorized" url="https://registry-1.docker.io/v2/library/hello-world/manifests/latest"
DEBU[2023-05-12T10:02:23.008268046+02:00] Unauthorized                                  header="Bearer realm=\"https://auth.docker.io/token\",service=\"registry.docker.io\",scope=\"repository:library/hello-world:pull\"" host=registry-1.docker.io
DEBU[2023-05-12T10:02:23.008418378+02:00] do request                                    host=registry-1.docker.io request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" request.header.user-agent=containerd/1.6.21+unknown request.method=HEAD url="https://registry-1.docker.io/v2/library/hello-world/manifests/latest"
DEBU[2023-05-12T10:02:23.462543719+02:00] fetch response received                       host=registry-1.docker.io response.header.content-length=2561 response.header.content-type=application/vnd.docker.distribution.manifest.list.v2+json response.header.date="Fri, 12 May 2023 08:02:23 GMT" response.header.docker-content-digest="sha256:fc6cf906cbfa013e80938cdf0bb199fbdbb86d6e3e013783e5a766f50f5dbce0" response.header.docker-distribution-api-version=registry/2.0 response.header.docker-ratelimit-source=62.35.48.5 response.header.etag="\"sha256:fc6cf906cbfa013e80938cdf0bb199fbdbb86d6e3e013783e5a766f50f5dbce0\"" response.header.ratelimit-limit="100;w=21600" response.header.ratelimit-remaining="97;w=21600" response.header.strict-transport-security="max-age=31536000" response.status="200 OK" url="https://registry-1.docker.io/v2/library/hello-world/manifests/latest"
DEBU[2023-05-12T10:02:23.462832841+02:00] resolved                                      desc.digest="sha256:fc6cf906cbfa013e80938cdf0bb199fbdbb86d6e3e013783e5a766f50f5dbce0" host=registry-1.docker.io
DEBU[2023-05-12T10:02:23.470770462+02:00] fetch                                         digest="sha256:fc6cf906cbfa013e80938cdf0bb199fbdbb86d6e3e013783e5a766f50f5dbce0" mediatype=application/vnd.docker.distribution.manifest.list.v2+json size=2561
DEBU[2023-05-12T10:02:23.488412934+02:00] do request                                    digest="sha256:fc6cf906cbfa013e80938cdf0bb199fbdbb86d6e3e013783e5a766f50f5dbce0" mediatype=application/vnd.docker.distribution.manifest.list.v2+json request.header.accept="application/vnd.docker.distribution.manifest.list.v2+json, */*" request.header.user-agent=containerd/1.6.21+unknown request.method=GET size=2561 url="https://registry-1.docker.io/v2/library/hello-world/manifests/sha256:fc6cf906cbfa013e80938cdf0bb199fbdbb86d6e3e013783e5a766f50f5dbce0"
DEBU[2023-05-12T10:02:23.815099677+02:00] fetch response received                       digest="sha256:fc6cf906cbfa013e80938cdf0bb199fbdbb86d6e3e013783e5a766f50f5dbce0" mediatype=application/vnd.docker.distribution.manifest.list.v2+json response.header.content-length=2561 response.header.content-type=application/vnd.docker.distribution.manifest.list.v2+json response.header.date="Fri, 12 May 2023 08:02:23 GMT" response.header.docker-content-digest="sha256:fc6cf906cbfa013e80938cdf0bb199fbdbb86d6e3e013783e5a766f50f5dbce0" response.header.docker-distribution-api-version=registry/2.0 response.header.docker-ratelimit-source=62.35.48.5 response.header.etag="\"sha256:fc6cf906cbfa013e80938cdf0bb199fbdbb86d6e3e013783e5a766f50f5dbce0\"" response.header.ratelimit-limit="100;w=21600" response.header.ratelimit-remaining="97;w=21600" response.header.strict-transport-security="max-age=31536000" response.status="200 OK" size=2561 url="https://registry-1.docker.io/v2/library/hello-world/manifests/sha256:fc6cf906cbfa013e80938cdf0bb199fbdbb86d6e3e013783e5a766f50f5dbce0"
DEBU[2023-05-12T10:02:23.846961076+02:00] fetch                                         digest="sha256:efebf0f7aee69450f99deafe11121afa720abed733943e50581a9dc7540689c8" mediatype=application/vnd.docker.distribution.manifest.v2+json size=525
DEBU[2023-05-12T10:02:23.851984188+02:00] do request                                    digest="sha256:efebf0f7aee69450f99deafe11121afa720abed733943e50581a9dc7540689c8" mediatype=application/vnd.docker.distribution.manifest.v2+json request.header.accept="application/vnd.docker.distribution.manifest.v2+json, */*" request.header.user-agent=containerd/1.6.21+unknown request.method=GET size=525 url="https://registry-1.docker.io/v2/library/hello-world/manifests/sha256:efebf0f7aee69450f99deafe11121afa720abed733943e50581a9dc7540689c8"
DEBU[2023-05-12T10:02:23.973383270+02:00] fetch response received                       digest="sha256:efebf0f7aee69450f99deafe11121afa720abed733943e50581a9dc7540689c8" mediatype=application/vnd.docker.distribution.manifest.v2+json response.header.content-length=525 response.header.content-type=application/vnd.docker.distribution.manifest.v2+json response.header.date="Fri, 12 May 2023 08:02:23 GMT" response.header.docker-content-digest="sha256:efebf0f7aee69450f99deafe11121afa720abed733943e50581a9dc7540689c8" response.header.docker-distribution-api-version=registry/2.0 response.header.docker-ratelimit-source=62.35.48.5 response.header.etag="\"sha256:efebf0f7aee69450f99deafe11121afa720abed733943e50581a9dc7540689c8\"" response.header.ratelimit-limit="100;w=21600" response.header.ratelimit-remaining="96;w=21600" response.header.strict-transport-security="max-age=31536000" response.status="200 OK" size=525 url="https://registry-1.docker.io/v2/library/hello-world/manifests/sha256:efebf0f7aee69450f99deafe11121afa720abed733943e50581a9dc7540689c8"
DEBU[2023-05-12T10:02:23.994642120+02:00] fetch                                         digest="sha256:b038788ddb222cb7d6025b411759e4f5abe9910486c8f98534ead97befd77dd7" mediatype=application/vnd.docker.container.image.v1+json size=1485
DEBU[2023-05-12T10:02:23.998171123+02:00] do request                                    digest="sha256:b038788ddb222cb7d6025b411759e4f5abe9910486c8f98534ead97befd77dd7" mediatype=application/vnd.docker.container.image.v1+json request.header.accept="application/vnd.docker.container.image.v1+json, */*" request.header.user-agent=containerd/1.6.21+unknown request.method=GET size=1485 url="https://registry-1.docker.io/v2/library/hello-world/blobs/sha256:b038788ddb222cb7d6025b411759e4f5abe9910486c8f98534ead97befd77dd7"
DEBU[2023-05-12T10:02:24.168963120+02:00] fetch response received                       digest="sha256:b038788ddb222cb7d6025b411759e4f5abe9910486c8f98534ead97befd77dd7" mediatype=application/vnd.docker.container.image.v1+json response.header.accept-ranges=bytes response.header.age=686409 response.header.cache-control="public, max-age=14400" response.header.cf-cache-status=HIT response.header.cf-ray=7c6123a50bf32a6f-CDG response.header.connection=keep-alive response.header.content-length=1485 response.header.content-type=application/octet-stream response.header.date="Fri, 12 May 2023 08:02:24 GMT" response.header.etag="\"4c8c8c3827591cf7643245910181ba11\"" response.header.expires="Fri, 12 May 2023 12:02:24 GMT" response.header.last-modified="Thu, 04 May 2023 08:43:33 GMT" response.header.server=cloudflare response.header.vary=Accept-Encoding response.header.x-amz-id-2="kDNqB7+tawkeCGlaL99CjxxO5LfeAgCKd6Bly8Mo9I/BcaGKRjWZvsUoQjMia0p7w9QE9b6JtF8=" response.header.x-amz-request-id=8X9SW8SYGGJV1RA4 response.header.x-amz-server-side-encryption=AES256 response.header.x-amz-version-id=UbWK6i2XuagOLBKXZZ5a3JY1SIrQleVV response.status="200 OK" size=1485 url="https://registry-1.docker.io/v2/library/hello-world/blobs/sha256:b038788ddb222cb7d6025b411759e4f5abe9910486c8f98534ead97befd77dd7"
DEBU[2023-05-12T10:02:24.201861967+02:00] fetch                                         digest="sha256:70f5ac315c5af948332962ff4678084ebcc215809506e4b8cd9e509660417205" mediatype=application/vnd.docker.image.rootfs.diff.tar.gzip size=3190
DEBU[2023-05-12T10:02:24.204589729+02:00] do request                                    digest="sha256:70f5ac315c5af948332962ff4678084ebcc215809506e4b8cd9e509660417205" mediatype=application/vnd.docker.image.rootfs.diff.tar.gzip request.header.accept="application/vnd.docker.image.rootfs.diff.tar.gzip, */*" request.header.user-agent=containerd/1.6.21+unknown request.method=GET size=3190 url="https://registry-1.docker.io/v2/library/hello-world/blobs/sha256:70f5ac315c5af948332962ff4678084ebcc215809506e4b8cd9e509660417205"
DEBU[2023-05-12T10:02:24.333436895+02:00] fetch response received                       digest="sha256:70f5ac315c5af948332962ff4678084ebcc215809506e4b8cd9e509660417205" mediatype=application/vnd.docker.image.rootfs.diff.tar.gzip response.header.accept-ranges=bytes response.header.age=686409 response.header.cache-control="public, max-age=14400" response.header.cf-cache-status=HIT response.header.cf-ray=7c6123a60cc72a6f-CDG response.header.connection=keep-alive response.header.content-length=3190 response.header.content-type=application/octet-stream response.header.date="Fri, 12 May 2023 08:02:24 GMT" response.header.etag="\"77c5682f99e7f7e214256ec3fec2d80e\"" response.header.expires="Fri, 12 May 2023 12:02:24 GMT" response.header.last-modified="Thu, 04 May 2023 08:43:30 GMT" response.header.server=cloudflare response.header.vary=Accept-Encoding response.header.x-amz-id-2="7oSha/0hqZvM8qYxKdSAcoW/ZJzZf82ZytX8QhF9QtUHS4kkRPUC5qXay5mY23CDJd6dppsHz7Q=" response.header.x-amz-request-id=DT5M7981WMA3MBX1 response.header.x-amz-server-side-encryption=AES256 response.header.x-amz-version-id=90uK7t_hJMfKcra6WhJnrRqgn1IaMC3b response.status="200 OK" size=3190 url="https://registry-1.docker.io/v2/library/hello-world/blobs/sha256:70f5ac315c5af948332962ff4678084ebcc215809506e4b8cd9e509660417205"
DEBU[2023-05-12T10:02:24.365164005+02:00] image unpacked                                chainID="sha256:a7866053acacfefb68912a8916b67d6847c12b51949c6b8a5580c6609c08ae45" config="sha256:b038788ddb222cb7d6025b411759e4f5abe9910486c8f98534ead97befd77dd7"
INFO[2023-05-12T10:02:24.367657603+02:00] image pulled                                  digest="sha256:fc6cf906cbfa013e80938cdf0bb199fbdbb86d6e3e013783e5a766f50f5dbce0" remote="docker.io/library/hello-world:latest"
```

**Review by vvoland — APPROVED** [review]

File: daemon/containerd/resolver.go (hunk 1 above)
Comment (thaJeztah) [reply daemon/containerd/resolver.go:30]: Could you try if it works with cURL? Wondering if there's bits that the cli handles that's not done in other cases

Comment (thaJeztah) [reply daemon/containerd/resolver.go:30]: (I forgot if the other issue was reported with the CLI or another client)

Comment (rumpl) [reply daemon/containerd/resolver.go:30]: With curl:

```
DEBU[2023-05-12T10:16:13.229744346+02:00] resolving                                     host=registry-1.docker.io
DEBU[2023-05-12T10:16:13.229794680+02:00] do request                                    host=registry-1.docker.io request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" request.header.user-agent=containerd/1.6.21+unknown request.method=HEAD url="https://registry-1.docker.io/v2/library/hello-world/manifests/latest"
DEBU[2023-05-12T10:16:13.674409118+02:00] fetch response received                       host=registry-1.docker.io response.header.content-length=162 response.header.content-type=application/json response.header.date="Fri, 12 May 2023 08:16:13 GMT" response.header.docker-distribution-api-version=registry/2.0 response.header.docker-ratelimit-source=62.35.48.5 response.header.strict-transport-security="max-age=31536000" response.header.www-authenticate="Bearer realm=\"https://auth.docker.io/token\",service=\"registry.docker.io\",scope=\"repository:library/hello-world:pull\"" response.status="401 Unauthorized" url="https://registry-1.docker.io/v2/library/hello-world/manifests/latest"
DEBU[2023-05-12T10:16:13.674764702+02:00] Unauthorized                                  header="Bearer realm=\"https://auth.docker.io/token\",service=\"registry.docker.io\",scope=\"repository:library/hello-world:pull\"" host=registry-1.docker.io
DEBU[2023-05-12T10:16:13.674910619+02:00] do request                                    host=registry-1.docker.io request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" request.header.user-agent=containerd/1.6.21+unknown request.method=HEAD url="https://registry-1.docker.io/v2/library/hello-world/manifests/latest"
DEBU[2023-05-12T10:16:14.541149961+02:00] fetch response received                       host=registry-1.docker.io response.header.content-length=2561 response.header.content-type=application/vnd.docker.distribution.manifest.list.v2+json response.header.date="Fri, 12 May 2023 08:16:14 GMT" response.header.docker-content-digest="sha256:fc6cf906cbfa013e80938cdf0bb199fbdbb86d6e3e013783e5a766f50f5dbce0" response.header.docker-distribution-api-version=registry/2.0 response.header.docker-ratelimit-source=62.35.48.5 response.header.etag="\"sha256:fc6cf906cbfa013e80938cdf0bb199fbdbb86d6e3e013783e5a766f50f5dbce0\"" response.header.ratelimit-limit="100;w=21600" response.header.ratelimit-remaining="96;w=21600" response.header.strict-transport-security="max-age=31536000" response.status="200 OK" url="https://registry-1.docker.io/v2/library/hello-world/manifests/latest"
DEBU[2023-05-12T10:16:14.541483211+02:00] resolved                                      desc.digest="sha256:fc6cf906cbfa013e80938cdf0bb199fbdbb86d6e3e013783e5a766f50f5dbce0" host=registry-1.docker.io
DEBU[2023-05-12T10:16:14.553085854+02:00] fetch                                         digest="sha256:fc6cf906cbfa013e80938cdf0bb199fbdbb86d6e3e013783e5a766f50f5dbce0" mediatype=application/vnd.docker.distribution.manifest.list.v2+json size=2561
DEBU[2023-05-12T10:16:14.569229546+02:00] do request                                    digest="sha256:fc6cf906cbfa013e80938cdf0bb199fbdbb86d6e3e013783e5a766f50f5dbce0" mediatype=application/vnd.docker.distribution.manifest.list.v2+json request.header.accept="application/vnd.docker.distribution.manifest.list.v2+json, */*" request.header.user-agent=containerd/1.6.21+unknown request.method=GET size=2561 url="https://registry-1.docker.io/v2/library/hello-world/manifests/sha256:fc6cf906cbfa013e80938cdf0bb199fbdbb86d6e3e013783e5a766f50f5dbce0"
DEBU[2023-05-12T10:16:14.879545235+02:00] fetch response received                       digest="sha256:fc6cf906cbfa013e80938cdf0bb199fbdbb86d6e3e013783e5a766f50f5dbce0" mediatype=application/vnd.docker.distribution.manifest.list.v2+json response.header.content-length=2561 response.header.content-type=application/vnd.docker.distribution.manifest.list.v2+json response.header.date="Fri, 12 May 2023 08:16:14 GMT" response.header.docker-content-digest="sha256:fc6cf906cbfa013e80938cdf0bb199fbdbb86d6e3e013783e5a766f50f5dbce0" response.header.docker-distribution-api-version=registry/2.0 response.header.docker-ratelimit-source=62.35.48.5 response.header.etag="\"sha256:fc6cf906cbfa013e80938cdf0bb199fbdbb86d6e3e013783e5a766f50f5dbce0\"" response.header.ratelimit-limit="100;w=21600" response.header.ratelimit-remaining="96;w=21600" response.header.strict-transport-security="max-age=31536000" response.status="200 OK" size=2561 url="https://registry-1.docker.io/v2/library/hello-world/manifests/sha256:fc6cf906cbfa013e80938cdf0bb199fbdbb86d6e3e013783e5a766f50f5dbce0"
DEBU[2023-05-12T10:16:14.907173278+02:00] fetch                                         digest="sha256:efebf0f7aee69450f99deafe11121afa720abed733943e50581a9dc7540689c8" mediatype=application/vnd.docker.distribution.manifest.v2+json size=525
DEBU[2023-05-12T10:16:14.912665953+02:00] do request                                    digest="sha256:efebf0f7aee69450f99deafe11121afa720abed733943e50581a9dc7540689c8" mediatype=application/vnd.docker.distribution.manifest.v2+json request.header.accept="application/vnd.docker.distribution.manifest.v2+json, */*" request.header.user-agent=containerd/1.6.21+unknown request.method=GET size=525 url="https://registry-1.docker.io/v2/library/hello-world/manifests/sha256:efebf0f7aee69450f99deafe11121afa720abed733943e50581a9dc7540689c8"
DEBU[2023-05-12T10:16:15.166872138+02:00] fetch response received                       digest="sha256:efebf0f7aee69450f99deafe11121afa720abed733943e50581a9dc7540689c8" mediatype=application/vnd.docker.distribution.manifest.v2+json response.header.content-length=525 response.header.content-type=application/vnd.docker.distribution.manifest.v2+json response.header.date="Fri, 12 May 2023 08:16:15 GMT" response.header.docker-content-digest="sha256:efebf0f7aee69450f99deafe11121afa720abed733943e50581a9dc7540689c8" response.header.docker-distribution-api-version=registry/2.0 response.header.docker-ratelimit-source=62.35.48.5 response.header.etag="\"sha256:efebf0f7aee69450f99deafe11121afa720abed733943e50581a9dc7540689c8\"" response.header.ratelimit-limit="100;w=21600" response.header.ratelimit-remaining="95;w=21600" response.header.strict-transport-security="max-age=31536000" response.status="200 OK" size=525 url="https://registry-1.docker.io/v2/library/hello-world/manifests/sha256:efebf0f7aee69450f99deafe11121afa720abed733943e50581a9dc7540689c8"
DEBU[2023-05-12T10:16:15.190582425+02:00] fetch                                         digest="sha256:b038788ddb222cb7d6025b411759e4f5abe9910486c8f98534ead97befd77dd7" mediatype=application/vnd.docker.container.image.v1+json size=1485
DEBU[2023-05-12T10:16:15.195648974+02:00] do request                                    digest="sha256:b038788ddb222cb7d6025b411759e4f5abe9910486c8f98534ead97befd77dd7" mediatype=application/vnd.docker.container.image.v1+json request.header.accept="application/vnd.docker.container.image.v1+json, */*" request.header.user-agent=containerd/1.6.21+unknown request.method=GET size=1485 url="https://registry-1.docker.io/v2/library/hello-world/blobs/sha256:b038788ddb222cb7d6025b411759e4f5abe9910486c8f98534ead97befd77dd7"
DEBU[2023-05-12T10:16:15.593071215+02:00] fetch response received                       digest="sha256:b038788ddb222cb7d6025b411759e4f5abe9910486c8f98534ead97befd77dd7" mediatype=application/vnd.docker.container.image.v1+json response.header.accept-ranges=bytes response.header.age=687240 response.header.cache-control="public, max-age=14400" response.header.cf-cache-status=HIT response.header.cf-ray=7c6137f15d740232-CDG response.header.connection=keep-alive response.header.content-length=1485 response.header.content-type=application/octet-stream response.header.date="Fri, 12 May 2023 08:16:15 GMT" response.header.etag="\"4c8c8c3827591cf7643245910181ba11\"" response.header.expires="Fri, 12 May 2023 12:16:15 GMT" response.header.last-modified="Thu, 04 May 2023 08:43:33 GMT" response.header.server=cloudflare response.header.vary=Accept-Encoding response.header.x-amz-id-2="kDNqB7+tawkeCGlaL99CjxxO5LfeAgCKd6Bly8Mo9I/BcaGKRjWZvsUoQjMia0p7w9QE9b6JtF8=" response.header.x-amz-request-id=8X9SW8SYGGJV1RA4 response.header.x-amz-server-side-encryption=AES256 response.header.x-amz-version-id=UbWK6i2XuagOLBKXZZ5a3JY1SIrQleVV response.status="200 OK" size=1485 url="https://registry-1.docker.io/v2/library/hello-world/blobs/sha256:b038788ddb222cb7d6025b411759e4f5abe9910486c8f98534ead97befd77dd7"
DEBU[2023-05-12T10:16:15.623646762+02:00] fetch                                         digest="sha256:70f5ac315c5af948332962ff4678084ebcc215809506e4b8cd9e509660417205" mediatype=application/vnd.docker.image.rootfs.diff.tar.gzip size=3190
DEBU[2023-05-12T10:16:15.627115851+02:00] do request                                    digest="sha256:70f5ac315c5af948332962ff4678084ebcc215809506e4b8cd9e509660417205" mediatype=application/vnd.docker.image.rootfs.diff.tar.gzip request.header.accept="application/vnd.docker.image.rootfs.diff.tar.gzip, */*" request.header.user-agent=containerd/1.6.21+unknown request.method=GET size=3190 url="https://registry-1.docker.io/v2/library/hello-world/blobs/sha256:70f5ac315c5af948332962ff4678084ebcc215809506e4b8cd9e509660417205"
DEBU[2023-05-12T10:16:15.743734573+02:00] fetch response received                       digest="sha256:70f5ac315c5af948332962ff4678084ebcc215809506e4b8cd9e509660417205" mediatype=application/vnd.docker.image.rootfs.diff.tar.gzip response.header.accept-ranges=bytes response.header.age=687240 response.header.cache-control="public, max-age=14400" response.header.cf-cache-status=HIT response.header.cf-ray=7c6137f26e800232-CDG response.header.connection=keep-alive response.header.content-length=3190 response.header.content-type=application/octet-stream response.header.date="Fri, 12 May 2023 08:16:15 GMT" response.header.etag="\"77c5682f99e7f7e214256ec3fec2d80e\"" response.header.expires="Fri, 12 May 2023 12:16:15 GMT" response.header.last-modified="Thu, 04 May 2023 08:43:30 GMT" response.header.server=cloudflare response.header.vary=Accept-Encoding response.header.x-amz-id-2="7oSha/0hqZvM8qYxKdSAcoW/ZJzZf82ZytX8QhF9QtUHS4kkRPUC5qXay5mY23CDJd6dppsHz7Q=" response.header.x-amz-request-id=DT5M7981WMA3MBX1 response.header.x-amz-server-side-encryption=AES256 response.header.x-amz-version-id=90uK7t_hJMfKcra6WhJnrRqgn1IaMC3b response.status="200 OK" size=3190 url="https://registry-1.docker.io/v2/library/hello-world/blobs/sha256:70f5ac315c5af948332962ff4678084ebcc215809506e4b8cd9e509660417205"
DEBU[2023-05-12T10:16:15.778144252+02:00] image unpacked                                chainID="sha256:a7866053acacfefb68912a8916b67d6847c12b51949c6b8a5580c6609c08ae45" config="sha256:b038788ddb222cb7d6025b411759e4f5abe9910486c8f98534ead97befd77dd7"
INFO[2023-05-12T10:16:15.780714172+02:00] image pulled                                  digest="sha256:fc6cf906cbfa013e80938cdf0bb199fbdbb86d6e3e013783e5a766f50f5dbce0" remote="docker.io/library/hello-world:latest"
```
