### PR TITLE
Suppress errors from gateway re-config when disconnecting a network

### LINKED ISSUE #51578: docker stop-start fails for container with multiple networks in v29
### Description

In v29 I'm unable to execute stop and start of a container which is attached to multiple networks.
This looks like a regression introduced in docker v29, as the same identical setup worked in docker v28.

```
# docker stop oam-0
oam-0

# docker start oam-0
Error response from daemon: failed to set up container networking: endpoint with name oam-0 already exists in network a_intmgmt
failed to start containers: oam-0
```

Just after the stop the docker daemon logs show:

```
Nov 24 08:57:04 dl360-sme2000s dockerd[829470]: time="2025-11-24T08:57:04.193944542+01:00" level=info msg="ignoring event" container=50b591a367
df3548f2af02cce1d60c0d644720decde816953309f349ec8b2353 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Nov 24 08:57:04 dl360-sme2000s dockerd[829470]: time="2025-11-24T08:57:04.200325197+01:00" level=warning msg="ShouldRestart failed, container w
ill not be restarted" container=50b591a367df3548f2af02cce1d60c0d644720decde816953309f349ec8b2353 daemonShuttingDown=false error="restart cancel
ed" execDuration=1m41.973281667s exitStatus="{0 2025-11-24 07:57:04.186841754 +0000 UTC}" hasBeenManuallyStopped=true restartCount=0
Nov 24 08:57:04 dl360-sme2000s dockerd[829470]: time="2025-11-24T08:57:04.253007662+01:00" level=warning msg="Failed detaching sandbox fbc58503
e1cfbba92240a93b26b1718a46d329cb0dc59f46a796eab4ba1f4a1f from endpoint f0c585af33964a81f8e7000f4cd2789eec962f79a020e0f95dc579819cb42a77: updati
ng gateway endpoint: failed to set gateway: route for the gateway 169.254.69.1 could not be found: network is unreachable\n"
Nov 24 08:57:04 dl360-sme2000s dockerd[829470]: time="2025-11-24T08:57:04.253042704+01:00" level=warning msg="Failed deleting endpoint f0c585af
33964a81f8e7000f4cd2789eec962f79a020e0f95dc579819cb42a77: endpoint with name oam-0 id f0c585af33964a81f8e7000f4cd2789eec962f79a020e0f95dc579819
cb42a77 has active containers\n"
```

See docker inspect below:

```
# docker inspect oam-0
[
    {
        "Id": "50b591a367df3548f2af02cce1d60c0d644720decde816953309f349ec8b2353",
        "Created": "2025-11-24T07:55:21.313537521Z",
        "Path": "/bin/sh",
        "Args": [
            "-c",
            "/sbin/init"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 838383,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2025-11-24T07:55:22.227036237Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:a722ff10f81577bca6dc7641c5bc70f3362cb36310ea81038f7d2bdaf0ecb0f9",
        "ResolvConfPath": "/var/lib/docker/containers/50b591a367df3548f2af02cce1d60c0d644720decde816953309f349ec8b2353/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/50b591a367df3548f2af02cce1d60c0d644720decde816953309f349ec8b2353/hostname",
        "HostsPath": "/var/lib/docker/containers/50b591a367df3548f2af02cce1d60c0d644720decde816953309f349ec8b2353/hosts",
        "LogPath": "/var/lib/docker/containers/50b591a367df3548f2af02cce1d60c0d644720decde816953309f349ec8b2353/50b591a367df3548f2af02cce1d60c0d644720decde816953309f349ec8b2353-json.log",
        "Name": "/oam-0",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/sys/fs/cgroup:/sys/fs/cgroup:ro",
                "host-data-disk:/data-disk",
                "/var/run/docker.sock:/var/run/docker.sock:ro",
                "/var/spool/abrt:/var/spool/abrt",
                "/var/lib/systemd/coredump:/var/lib/systemd/coredump"
            ],
            "ContainerIDFile": "/var/lib/italtel/cnf/ids/oam-0.id",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "a_intmgmt",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "ConsoleSize": [
                31,
                143
            ],
            "CapAdd": [
                "CAP_NET_ADMIN",
                "CAP_NET_RAW",
                "CAP_SYS_PTRACE"
            ],
            "CapDrop": null,
            "CgroupnsMode": "host",
            "Dns": null,
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "StorageOpt": {
                "size": "15G"
            },
            "Tmpfs": {
                "/run": "",
                "/run/lock": "",
                "/tmp": "",
                "/var/lib/journal": ""
            },
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 134217728,
            "Sysctls": {
                "net.ipv4.conf.all.accept_redirects": "0",
                "net.ipv4.conf.all.accept_source_route": "0",
                "net.ipv4.conf.all.promote_secondaries": "1",
                "net.ipv4.conf.all.secure_redirects": "0",
                "net.ipv4.conf.all.send_redirects": "0",
                "net.ipv4.conf.default.accept_redirects": "0",
                "net.ipv4.conf.default.accept_source_route": "0",
                "net.ipv4.conf.default.secure_redirects": "0",
                "net.ipv4.conf.default.send_redirects": "0",
                "net.ipv4.ip_forward": "0",
                "net.ipv6.conf.all.accept_redirects": "0",
                "net.ipv6.conf.all.accept_source_route": "0",
                "net.ipv6.conf.default.accept_redirects": "0",
                "net.ipv6.conf.default.accept_source_route": "0"
            },
            "Runtime": "runc",
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 10737418240,
            "NanoCpus": 4000000000,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": [],
            "BlkioDeviceWriteBps": [],
            "BlkioDeviceReadIOps": [],
            "BlkioDeviceWriteIOps": [],
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "0,12,4,16,5,17,6,18,7,19,8,20,9,21,10,22,11,23",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "MemoryReservation": 0,
            "MemorySwap": 10737418240,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": [],
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/acpi",
                "/proc/asound",
                "/proc/interrupts",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/sys/devices/virtual/powercap",
                "/sys/firmware",
                "/sys/devices/system/cpu/cpu0/thermal_throttle",
                "/sys/devices/system/cpu/cpu1/thermal_throttle",
                "/sys/devices/system/cpu/cpu2/thermal_throttle",
                "/sys/devices/system/cpu/cpu3/thermal_throttle",
                "/sys/devices/system/cpu/cpu4/thermal_throttle",
                "/sys/devices/system/cpu/cpu5/thermal_throttle",
                "/sys/devices/system/cpu/cpu6/thermal_throttle",
                "/sys/devices/system/cpu/cpu7/thermal_throttle",
                "/sys/devices/system/cpu/cpu8/thermal_throttle",
                "/sys/devices/system/cpu/cpu9/thermal_throttle",
                "/sys/devices/system/cpu/cpu10/thermal_throttle",
                "/sys/devices/system/cpu/cpu11/thermal_throttle",
                "/sys/devices/system/cpu/cpu12/thermal_throttle",
                "/sys/devices/system/cpu/cpu13/thermal_throttle",
                "/sys/devices/system/cpu/cpu14/thermal_throttle",
                "/sys/devices/system/cpu/cpu15/thermal_throttle",
                "/sys/devices/system/cpu/cpu16/thermal_throttle",
                "/sys/devices/system/cpu/cpu17/thermal_throttle",
                "/sys/devices/system/cpu/cpu18/thermal_throttle",
                "/sys/devices/system/cpu/cpu19/thermal_throttle",
                "/sys/devices/system/cpu/cpu20/thermal_throttle",
                "/sys/devices/system/cpu/cpu21/thermal_throttle",
                "/sys/devices/system/cpu/cpu22/thermal_throttle",
                "/sys/devices/system/cpu/cpu23/thermal_throttle"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "ID": "50b591a367df3548f2af02cce1d60c0d644720decde816953309f349ec8b2353",
                "LowerDir": "/var/lib/docker/overlay2/b206640a0d645804f3e9c0956979d45cb6e738c6f94abb4004957ac5e60e0934-init/diff:/var/lib/docker/overlay2/e7e47f7ef361add1e87a5370b02e8422889963cace0548da7f145df4757693fe/diff:/var/lib/docker/overlay2/cbafaf9b090e01f7a9ca36921b2f385d419b829b606b14edce930ccee442b800/diff",
                "MergedDir": "/var/lib/docker/overlay2/b206640a0d645804f3e9c0956979d45cb6e738c6f94abb4004957ac5e60e0934/merged",
                "UpperDir": "/var/lib/docker/overlay2/b206640a0d645804f3e9c0956979d45cb6e738c6f94abb4004957ac5e60e0934/diff",
                "WorkDir": "/var/lib/docker/overlay2/b206640a0d645804f3e9c0956979d45cb6e738c6f94abb4004957ac5e60e0934/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/var/spool/abrt",
                "Destination": "/var/spool/abrt",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/var/lib/systemd/coredump",
                "Destination": "/var/lib/systemd/coredump",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/sys/fs/cgroup",
                "Destination": "/sys/fs/cgroup",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "volume",
                "Name": "host-data-disk",
                "Source": "/var/lib/docker/volumes/host-data-disk/_data",
                "Destination": "/data-disk",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/var/run/docker.sock",
                "Destination": "/var/run/docker.sock",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "dl360-sme2000-oam-0",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "container=docker",
                "HTTP_PROXY=",
                "HTTPS_PROXY=",
                "http_proxy=",
                "https_proxy="
            ],
            "Cmd": null,
            "Image": "oam",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/bin/sh",
                "-c",
                "/sbin/init"
            ],
            "Labels": {},
            "StopSignal": "SIGRTMIN+3",
            "StopTimeout": 60
        },
        "NetworkSettings": {
            "SandboxID": "fbc58503e1cfbba92240a93b26b1718a46d329cb0dc59f46a796eab4ba1f4a1f",
            "SandboxKey": "/var/run/docker/netns/fbc58503e1cf",
            "Ports": {},
            "Networks": {
                "a_intmgmt": {
                    "IPAMConfig": {
                        "IPv4Address": "169.254.100.8",
                        "IPv6Address": ""
                    },
                    "Links": null,
                    "Aliases": null,
                    "DriverOpts": {
                        "com.docker.network.endpoint.ifname": "eth0"
                    },
                    "GwPriority": 0,
                    "NetworkID": "ca2a19056dea02bb1e31aba84848dbd74871e0f0fcf53df6a0162ab97f322c4f",
                    "EndpointID": "f0c585af33964a81f8e7000f4cd2789eec962f79a020e0f95dc579819cb42a77",
                    "Gateway": "169.254.100.1",
                    "IPAddress": "169.254.100.8",
                    "MacAddress": "4a:34:c3:0c:fd:be",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "DNSNames": [
                        "oam-0",
                        "50b591a367df",
                        "dl360-sme2000-oam-0"
                    ]
                },
                "c_extmgmt": {
                    "IPAMConfig": {
                        "IPv4Address": "",
                        "IPv6Address": ""
                    },
                    "Links": null,
                    "Aliases": [],
                    "DriverOpts": {
                        "com.docker.network.endpoint.ifname": "eth1"
                    },
                    "GwPriority": 0,
                    "NetworkID": "b139166900ce74b8e7d9aa89ca50f0290a3d02d9036dc833fd8474da4e1efba6",
                    "EndpointID": "d09a2f0f2212d1e90aa876270ff501dd6162314d5257e97c6b5dcadd34b350ba",
                    "Gateway": "169.254.69.1",
                    "IPAddress": "169.254.69.2",
                    "MacAddress": "16:9e:8f:2f:9a:58",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "DNSNames": [
                        "oam-0",
                        "50b591a367df",
                        "dl360-sme2000-oam-0"
                    ]
                }
            }
        }
    }
]

```

### Reproduce

1. Create a container like shown in `docker inspect` in previous section
2. `docker stop`
3. `docker start`

### Expected behavior

docker stop/start should work without errors

### docker version

```bash
Client: Docker Engine - Community
 Version:           29.0.2
 API version:       1.52
 Go version:        go1.25.4
 Git commit:        8108357
 Built:             Mon Nov 17 12:35:47 2025
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          29.0.2
  API version:      1.52 (minimum version 1.44)
  Go version:       go1.25.4
  Git commit:       e9ff10b
  Built:            Mon Nov 17 12:33:03 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v2.1.5
  GitCommit:        fcd43222d6b07379a4be9786bda52438f0dd16a1
 runc:
  Version:          1.3.3
  GitCommit:        v1.3.3-0-gd842d771
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    29.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.30.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.40.3
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 5
  Running: 4
  Paused: 0
  Stopped: 1
 Images: 5
 Server Version: 29.0.2
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 CDI spec directories:
  /etc/cdi
  /var/run/cdi
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: fcd43222d6b07379a4be9786bda52438f0dd16a1
 runc version: v1.3.3-0-gd842d771
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 4.18.0-553.83.1.el8_10.x86_64
 Operating System: AlmaLinux 8.10 (Cerulean Leopard)
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 30.83GiB
 Name: dl360-sme2000s
 ID: 63d1e9c3-6da8-416c-9d09-bf984de1d400
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
 Firewall Backend: iptables+firewalld

WARNING: Support for cgroup v1 is deprecated and planned to be removed by no later than May 2029 (https://github.com/moby/moby/issues/51111)
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by robmry**
**- What I did**

- fix https://github.com/moby/moby/issues/51578
- introduced by https://github.com/moby/moby/pull/50945 / https://github.com/moby/moby/commit/53390f85ddf238dea30c899355ef5b2299156f8f

When a network is disconnected from a container, if that network provides the container's default gateway, another gateway is selected from the remaining network endpoints (if there are any). That selection happens after the endpoint has been removed, but there's no proper rollback if the newly selected gateway doesn't work.

**- How I did it**

The first commit skips selection of a new gateway if the container is being deleted. So setup of a new gateway can't fail. This fixes the bug as-reported.

Prior to https://github.com/moby/moby/commit/53390f85ddf238dea30c899355ef5b2299156f8f, an error setting up the new gateway was only logged ... the second commit restores that behaviour for the `network disconnect` case, where the container is not being deleted. The container won't have a working gateway, but the `Network` will not be left with a broken reference to the disconnected `Endpoint`, so it can be reconnected.

**- How to verify it**

New integration test, following the repro steps outlined at https://github.com/moby/moby/issues/51578#issuecomment-3576104329.

Without the fixes, the new test fails with ...
```
=== RUN   TestGatewayErrorOnNetDisconnect
    bridge_linux_test.go:2093: assertion failed: error is not nil: Error response from daemon: container c081ced8f0a5658709ec6cb4571c01eb51d389e5858220c2babedee8eae35261 failed to leave network n1: updating gateway endpoint: failed to set gateway: route for the gateway 172.22.0.1 could not be found: network is unreachable
    bridge_linux_test.go:2097: assertion failed: error is not nil: Error response from daemon: endpoint with name nervous_morse already exists in network n1
    bridge_linux_test.go:2102: assertion failed: error is not nil: Error response from daemon: Cannot restart container c081ced8f0a5658709ec6cb4571c01eb51d389e5858220c2babedee8eae35261: failed to set up container networking: endpoint with name nervous_morse already exists in network n1
    bridge_linux_test.go:2109: assertion failed: error is not nil: Error response from daemon: error while removing network: network n1 has active endpoints (name:"nervous_morse" id:"8f477b1b9e52")
--- FAIL: TestGatewayErrorOnNetDisconnect (5.44s)
FAIL
```

With the fixes:
- restarting a container produces no warning in the log, because there's no attempt to select the new gateway. Release 28.x logged "Failed to clean up network resources on container disconnect".
- if gateway config fails when disconnecting an endpoint, the a warning is logged. For example:
  - `Configuring gateway after network disconnect  cid=5b73d9f67743 eid=f2df6ddb1ac5 ep=c1 error="failed to set gateway: route for the gateway 172.20.0.1 could not be found: network is unreachable" gw4=ce9bf8761a88 gw6= net=n1 nid=1a3331eaf7df sid=c44c4f4d7982`

**- Human readable description for the release notes**
```markdown changelog
- Fix an issue that prevented container restart or network reconnection when gateway configuration failed during container stop or network disconnect.
```

### CODE REVIEW

**Review by vvoland — APPROVED** [review]

File: daemon/libnetwork/endpoint.go [hunk 1]
```diff
@@ -829,7 +831,11 @@ func (ep *Endpoint) sbLeave(ctx context.Context, sb *Sandbox, n *Network, force
 	if needNewGwEp {
 		gwepAfter4, gwepAfter6 = sb.getGatewayEndpoint()
 		if err := sb.updateGateway(gwepAfter4, gwepAfter6); err != nil {
-			return fmt.Errorf("updating gateway endpoint: %w", err)
+			log.G(ctx).WithFields(log.Fields{
```
Comment (akerouanton) [inline daemon/libnetwork/endpoint.go:836]: It's probably worth adding a comment explaining why we're logging instead of returning an error. There's still a bunch of code paths in libnetwork that adopt this error handling strategy, so readers may just think this is one of these injustified instances and not even git blame.

**Review by akerouanton — APPROVED** [review]

File: daemon/libnetwork/endpoint.go (hunk 1 above)
Comment (robmry) [reply daemon/libnetwork/endpoint.go:836]: Done ... although this is one of those paths using the error handling strategy of not handling errors. (As it was in 28.x - I moved this out of `clearNetworkResources`, which returned an error that was only logged.)

The whole network-disconnect operation should have proper error handling.
