### PR TITLE
Docker inspect gave default log options even when the option is emtpy.

### LINKED ISSUE #21956: docker inspect gave default log options when the option is emtpy
The code in https://github.com/docker/docker/blob/master/daemon/inspect.go#L117 show `docker inspect` will override the log config options with default option when you not specify it. But actually docker container still use the empty option

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 12
 Running: 10
 Paused: 0
 Stopped: 2
Images: 27
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-253:0-33760998-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/docker/data
 Metadata file: /dev/docker/metadata
 Data Space Used: 3.025 GB
 Data Space Total: 20 GB
 Data Space Available: 16.97 GB
 Metadata Space Used: 7.463 MB
 Metadata Space Total: 1.053 GB
 Metadata Space Available: 1.045 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: syslog
Plugins:
 Volume: local
 Network: host bridge null calico
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.797 GiB
Name: node1
ID: PLUV:C6FS:SIKS:4EAA:TZZ7:6ZK6:3CLB:A2G7:WQMN:5KR5:3W35:VPF7
Debug mode (server): true
 File Descriptors: 107
 Goroutines: 1184
 System Time: 2016-04-12T08:01:14.366475026Z
 EventsListeners: 1
 Init SHA1: eb0f466d1d125be1d5800e262e0758e1b54ed69a
 Init Path: /usr/libexec/docker/dockerinit
 Docker Root Dir: /data/docker
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Cluster store: etcd://192.168.77.21:4001
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Vagrant with VirtualBox

**Steps to reproduce the issue:**
1. start docker daemon with default log options: --log-driver=syslog --log-opt syslog-address=tcp://127.0.0.1:514
2. start a container only with log driver but empty option: --log-driver=syslog
3. docker inspect the container show it use the daemon log-opt

**Describe the results you received:**
In fact the container use the empty log option not as inspect shows

**Describe the results you expected:**
inspect also show empty option

### PR DESCRIPTION
**Pull request by yongtang**
**\- What I did**

This fix tries to addess the issue in #21956 where `docker inspect` will overwrite the log config options with default option even when the `--log-driver` is not empty and `--log-opt` is empty. In this situation, `docker inspect` and `docker run` is different.

With the introduction of #21153, the `HostConfig` will always have the correct log-driver and log-opt values.

However, the previous processing of `docker inspect` was not updated after the change in #21153. This results in the incorrect behavior.

**\- How I did it**

This fix addresses this issue by updating `docker inspect` to conform to #21153 so the the behavior of `docker inspect` and `docker run` is consistent.

**\- How to verify it**

A integration test has been added to cover this fix.

**\- A picture of a cute animal (not mandatory but encouraged)**

This fix fixes #21956. This fix is related to #21153.

Signed-off-by: Yong Tang yong.tang.github@outlook.com

### CODE REVIEW

**Comment by calavera** [comment]
LGTM

File: integration-cli/docker_cli_daemon_test.go [hunk 1]
```diff
@@ -2190,3 +2190,17 @@ func (s *DockerSuite) TestDaemonDiscoveryBackendConfigReload(c *check.C) {
 	c.Assert(out, checker.Contains, fmt.Sprintf("Cluster Store: consul://consuladdr:consulport/some/path"))
 	c.Assert(out, checker.Contains, fmt.Sprintf("Cluster Advertise: 192.168.56.100:0"))
 }
+
+// Test for #21956
+func (s *DockerDaemonSuite) TestDaemonInspectSyslog(c *check.C) {
```
Comment (vdemeester) [inline integration-cli/docker_cli_daemon_test.go]: I don't think the test should be named `TestDaemonInspectSyslog` but something else :stuck_out_tongue_closed_eyes:

**Comment by vdemeester** [comment]
Small nit, otherwise LGTM

**Comment by thaJeztah** [comment]
So, I was discussing this with @vdemeester, because I'm a bit confused; basically, if the daemon has `--log-driver=x --log-opt=y`, and I specify only `--log-driver=x` on `docker run / docker create`, then `--log-opt` is *reset* for that container, correct?

I think that behavior may make sense (otherwise there's no real way to reset daemon-level `--log-opt`), but we need to describe that behavior in the documentation; it's currently undocumented. Also;

What happens if I add `log-opt` to a `daemon.json` and reload?

- Are existing containers (without `--log-driver` on `docker run`) updated with the new options?
- Are existing containers (**with** `--log-driver` on `docker run`) also updated, or not?

Might be worth checking, just to be sure, and then describe the behavior in the documentation

**Comment by thaJeztah** [comment]
Actually; I think this may relate to https://github.com/docker/docker/pull/21153 I added a "needs attention" label, because we need to decide what the right behavior is; also in combination with https://github.com/docker/docker/pull/21153

**Do not merge until we made that decision**

**Comment by yongtang** [comment]
Thanks @calavera @vdemeester @thaJeztah for the review.

The `docker run` behavior with respect to log options is that:
If the daemon has --log-driver=x --log-opt=y=z, and `docker run/create` with only --log-driver=x, then the remote API POST request is:
```
        "HostConfig": {
            "LogConfig": {
                "Type": "x",
                "Config": {}
            },
            ...
        }
```
That is because `docker run` will parse `--log-opt` (which is an empty map) and assign it to LogConfig directly. See:
https://github.com/docker/docker/blob/master/runconfig/opts/parse.go#L332
https://github.com/docker/docker/blob/master/runconfig/opts/parse.go#L508
https://github.com/docker/docker/blob/master/runconfig/opts/parse.go#L427

At the same time, for `docker inspect`, before this pull request:
If the daemon has --log-driver=x --log-opt=y=z, and `docker run/create` with only --log-driver=x, then the LogConfig will still be `{}` (empty map), (See above). However, `docker inspect` will return the remote API GET response with:
```
        "HostConfig": {
            "LogConfig": {
                "Type": "x",
                "Config": {"y":"z"}
            },
            ...
        }
```
That is because `len(hostConfig.LogConfig.Config) == 0 ` (Ln: 117) so it will copy default daemon value to `Config`. However, `hostConfig.LogConfig.Type == ""` is not true as there is already a value of `"Type": "x"` (Ln: 113). So we are seeing a mismatch.
See
https://github.com/docker/docker/blob/master/daemon/inspect.go#L111-119

So in the above case (before this pull request), the `docker inspect` is not showing the options of `docker run/create` correctly. After this pull request, the behavior of the `docker run/create` remains the same, the behavior of `docker inspect` has been corrected.

I haven't checked the reload case but will take a look and see if there is any impact.

**Comment by yongtang** [comment]
Hi @thaJeztah I took a look at #21153. This pull request will not necessary conflict with #21153 though those two are quite related.

After walk through #21153 I feel like I may have some reservations. It seems like #21153 is essentially doing a "merge" strategy and the options in default settings will be "appended" if the options is not in containers settings. That means you can "add" or "overwrite" the default settings. But unset will be slightly more troublesome.

Maybe it is easier and more straightforward say, default settings will only take place if container setting is not specified at all?

**Comment by thaJeztah** [comment]
> Maybe it is easier and more straightforward say, default settings will only take place if container setting is not specified at all?

Yes, I was thinking of that, perhaps that's the best option - use the defaults from the daemon if no settings are provided on `docker run`, or reset settings if they are set.

File: daemon/inspect.go [hunk 2]
```diff
@@ -112,10 +112,9 @@ func (daemon *Daemon) getInspectData(container *container.Container, size bool)
 	// container will use daemon defaults even if daemon changes them
 	if hostConfig.LogConfig.Type == "" {
 		hostConfig.LogConfig.Type = daemon.defaultLogConfig.Type
-	}
-
-	if len(hostConfig.LogConfig.Config) == 0 {
```
Comment (cpuguy83) [inline daemon/inspect.go]: Shouldn't we keep it like this but add a ` && hostConfig.LogConfig.Type == daemon.defaultLogConfig.Type`

File: integration-cli/docker_cli_daemon_test.go (hunk 1 above)
Comment (cpuguy83) [inline integration-cli/docker_cli_daemon_test.go]: Can you update the test name?

Comment (yongtang) [inline integration-cli/docker_cli_daemon_test.go]: Thanks @vdemeester @cpuguy83 I changed the test name to `TestDaemonLogOptions`. Don't know if this one looks better but let me know if there are better names that could fit this test.

**Comment by yongtang** [comment]
@cpuguy83 Thanks for the review. With the change from #21153, the `HostConfig` will always have the correct `LogConfig` values.

However, the `docker inspect` part was not updated in #21153 so it results in incorrect behaviors again for `docker inspect`.

The following is an example:
```
docker daemon --log-driver=syslog --log-opt=syslog-address=udp://127.0.0.1:514
docker run -d --name=test --log-driver=json-file busybox top

docker inspect test

...
            "LogConfig": {
                "Type": "json-file",
                "Config": {
                    "syslog-address": "udp://127.0.0.1:514"
                }
            },
```

I just updated this pull request to conform to the change in #21153. The commit/comment has also been updated to reflect the new changes.

**Comment by thaJeztah** [comment]
tested this, and in combination with https://github.com/docker/docker/pull/21153 works as expected

LGTM

**Comment by vdemeester** [comment]
LGTM 🐰
