### PR TITLE
Port pkg/system/mknod.go to FreeBSD

### LINKED ISSUE #42849: Can't build github.com/docker/docker/pkg/system on freebsd
**Description**

This is an issue that was reported in fsouza/go-dockerclient#878: when trying to build go-dockerclient on freebsd, users see an error where `github.com/docker/docker/pkg/system` fails to build (it's a transient dependency of go-dockerclient).

Not sure if yall care about it or not, but I figured I could open an issue asking whether you'd take a PR before sending one or simply vendoring & fixing on my side.

Thank you very much!

**Steps to reproduce the issue:**

Clone go-dockerclient and try to build it with `GOOS=freebsd`:

```
% git clone --depth=1 https://github.com/fsouza/go-dockerclient.git
% cd go-dockerclient
% GOOS=freebsd go build 
```

**Describe the results you received:**

Compilation fails with the following error message:

```
# github.com/docker/docker/pkg/system
../../go/pkg/mod/github.com/docker/docker@v20.10.8+incompatible/pkg/system/mknod.go:12:19: cannot use dev (type int) as type uint64 in argument to unix.Mknod
```

**Describe the results you expected:**

Successful build.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by akhramov**
fixes https://github.com/moby/moby/issues/42849

Because FreeBSD uses 64-bit device nodes (see
https://reviews.freebsd.org/rS318736), Linux implementation of
`system.Mknod` & `system.Mkdev` is not sufficient.

This change adds freebsd-specific implementations for `Mknod` and
`Mkdev`.

### CODE REVIEW

File: pkg/system/mknod_freebsd.go [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+// Mknod creates a filesystem node (file, device special file or named pipe) named path
+// with attributes specified by mode and dev.
+func Mknod(path string, mode uint32, dev int) error {
+	return unix.Mknod(path, mode, uint64(dev))
+}
+
+// Mkdev is used to build the value of FreeBSD devices (in /dev/) which specifies major
+// and minor number of the newly created device special file.
+func Mkdev(major int64, minor int64) uint64 {
+	return unix.Mkdev(uint32(major), uint32(minor))
```
Comment (thaJeztah) [inline pkg/system/mknod_freebsd.go:19]: Doing a quick diff between both, to see what the difference is. On Linux we're converting this to return an `uint32`. All places where it's used (currently) cast it to an `int` (as argument for `Mknod`).

Mostly wondering if we should do the same for freebsd so that the signature is the same. (Perhaps we should look at that in a follow-up, and move these utilities into pkg/archive).

@samuelkarp perhaps you have thoughts on this?


```patch
diff --git a/pkg/system/mknod.go b/pkg/system/mknod_freebsd.go
index ccb2e638bb..b1ba8320dd 100644
--- a/pkg/system/mknod.go
+++ b/pkg/system/mknod_freebsd.go
@@ -1,5 +1,5 @@
-//go:build !freebsd && !windows
-// +build !freebsd,!windows
+//go:build freebsd
+// +build freebsd

 package system // import "github.com/docker/docker/pkg/system"

@@ -10,14 +10,11 @@ import (
 // Mknod creates a filesystem node (file, device special file or named pipe) named path
 // with attributes specified by mode and dev.
 func Mknod(path string, mode uint32, dev int) error {
-       return unix.Mknod(path, mode, dev)
+       return unix.Mknod(path, mode, uint64(dev))
 }

-// Mkdev is used to build the value of linux devices (in /dev/) which specifies major
+// Mkdev is used to build the value of FreeBSD devices (in /dev/) which specifies major
 // and minor number of the newly created device special file.
-// Linux device nodes are a bit weird due to backwards compat with 16 bit device nodes.
-// They are, from low to high: the lower 8 bits of the minor, then 12 bits of the major,
-// then the top 12 bits of the minor.
-func Mkdev(major int64, minor int64) uint32 {
-       return uint32(unix.Mkdev(uint32(major), uint32(minor)))
+func Mkdev(major int64, minor int64) uint64 {
+       return unix.Mkdev(uint32(major), uint32(minor))
 }
```

Comment (akhramov) [reply pkg/system/mknod_freebsd.go]: Makes sense, thanks

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Comment by thaJeztah** [comment]
@samuelkarp @AkihiroSuda ptal

**Review by AkihiroSuda — APPROVED** [review]
