### PR TITLE
Fix undead containers

### LINKED ISSUE #12825: `docker rm -f` silently ignores errors and leads to inconsistent state
I've got some broken containers that docker refuses to remove...

````
$ docker ps -aq
3b784fa07fcd
d88aa2757378
2219bb22fe66
vagrant@host1:~$ docker rm 3b784fa07fcd
Error response from daemon: Cannot destroy container 3b784fa07fcd: Driver devicemapper failed to remove root filesystem 3b784fa07fcd4fab5bc8a09ef120f4784d103d8cabd20de5955120b0f94649f6: Device is Busy
FATA[0010] Error: failed to remove one or more containers 
````

So far so good, but now let's try removing that container with `rm -f`...

````
vagrant@host1:~$ docker rm -f 3b784fa07fcd
3b784fa07fcd
vagrant@host1:~$ echo $?
0
vagrant@host1:~$ docker ps -aq
d88aa2757378
2219bb22fe66
````
No error, and the container is gone. Well, that might be ok, except that when we bounce docker...

````
vagrant@host1:~$ sudo service docker restart
docker stop/waiting
docker start/running, process 1326
vagrant@host1:~$ docker ps -aq
3b784fa07fcd
d88aa2757378
2219bb22fe66
````
...the container comes back.

Version info:
````
$ docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64
````

### PR DESCRIPTION
**Pull request by cpuguy83**
Fixes #12825

When a container has errors on removal, it gets flagged as dead.
If you `docker rm -f` a dead container the container is dereffed from
the daemon and doesn't show up on `docker ps` anymore... except that the
container JSON file may still be lingering around and becomes undead
when you restart the daemon.

### CODE REVIEW

File: daemon/delete.go [hunk 1]
```diff
@@ -129,6 +129,9 @@ func (daemon *Daemon) commonRm(container *Container, forceRemove bool) (err erro
 		if err != nil && forceRemove {
 			daemon.idIndex.Delete(container.ID)
 			daemon.containers.Delete(container.ID)
+			if _, err := os.Stat(container.root); err != nil {
```
Comment (LK4D4) [inline daemon/delete.go]: I don't get this change. Can you explain?

**Comment by estesp** [comment]
Hmm..I think a good portion of the reason the original PR was written was because the `err` that gets you into that `defer` block is a lack of ability to `os.RemoveAll` the container rootfs (e.g. devicemapper busy errors, etc.).  That doesn't mean it isn't reasonable to try to remove it, but I think there will be situations where this doesn't actually change the behavior if there is still a "device busy" problem on the rootfs.

File: daemon/delete.go (hunk 1 above)
Comment (cpuguy83) [inline daemon/delete.go]: This is in a defer that for container rm.
If you `docker rm -f` a container and there is an error, this tells docker to de-ref the container so it's not listed anymore... except we didn't remove the actual on disk config so when the daemon restarts the container is back.

**Comment by cpuguy83** [comment]
@estesp This shouldn't be the container rootfs, it should be the config root `/var/lib/docker/containers`

File: daemon/delete.go (hunk 1 above)
Comment (LK4D4) [inline daemon/delete.go]: Okay, what `os.Stat` check means here?

Comment (cpuguy83) [inline daemon/delete.go]: Just checking if it was already removed.

Comment (LK4D4) [inline daemon/delete.go]: So, if it is already removed - remove it one more time?

Comment (cpuguy83) [inline daemon/delete.go]: ah, whoops, thanks!

Comment (cpuguy83) [inline daemon/delete.go]: Fixed.

File: daemon/delete.go [hunk 2]
```diff
@@ -129,6 +129,9 @@ func (daemon *Daemon) commonRm(container *Container, forceRemove bool) (err erro
 		if err != nil && forceRemove {
 			daemon.idIndex.Delete(container.ID)
 			daemon.containers.Delete(container.ID)
+			if _, err := os.Stat(container.root); err == nil {
```
Comment (LK4D4) [inline daemon/delete.go]: I think it is cheaper to call just `os.RemoveAll`.

**Comment by estesp** [comment]
@cpuguy83 yup, you're right.. was sidetracked by the incorrect comment in the string of remove steps below the defer block :)

**Comment by LK4D4** [comment]
LGTM

**Comment by estesp** [comment]
LGTM
