### PR TITLE
Fix awslogs batch size calculation

### LINKED ISSUE #35725: awslogs batch size exceeds service limits
**Description**

awslogs driver improperly batches log messages that are too large for CloudWatch to accept. This is due to incorrect accounting of the total size of the message being logged. The overhead and total byte size calculation is not maintained between the scopes that evaluate the service limit.

I have prepared a patch to fix this issue ~~and will open a pull request~~ [link here](https://github.com/moby/moby/pull/35726).

**Steps to reproduce the issue:**
1. Run docker container with awslogs driver.
2. Log a message larger than the allowed limit (1048576), such as 1048685 bytes from that container.
3. Observe docker log output.

**Describe the results you received:**

Container log messages are not logged to CloudWatch and are instead dropped by the driver due to an "exception" (error). This is error is printed in the Docker log:

```
time="2017-12-06T23:34:21.421389421Z" level=error msg="Failed to put log events" errorCode=InvalidParameterException logGroupName=cbcab4da0300039d1d8e10b40b053ea5 logStreamName="klines/klines/5c8ae105-9de2-40ab-ab8d-7b0bfd46a01a" message="Upload too large: 1048815 bytes exceeds limit of 1048576" origError=<nil> 
time="2017-12-06T23:34:21.421436838Z" level=error msg="InvalidParameterException: Upload too large: 1048815 bytes exceeds limit of 1048576\n\tstatus code: 400, request id: fc4705d1-dadd-11e7-8ef0-21e93a30f134" 
```

**Describe the results you expected:**

I expected the log messages to be split as needed to log the message to CloudWatch Logs.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.4
 Git commit:   3dfb8343b139d6342acfd9975d7f1068b5b1c3d3
 Built:        Fri Nov 10 00:50:37 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.4
 Git commit:   402dd4a/17.06.2-ce
 Built:        Fri Nov 10 00:51:08 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 3
Server Version: 17.06.2-ce
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3kB
 Base Device Size: 10.74GB
 Backing Filesystem: ext4
 Data file: 
 Metadata file: 
 Data Space Used: 1.239GB
 Data Space Total: 23.33GB
 Data Space Available: 22.09GB
 Metadata Space Used: 593.9kB
 Metadata Space Total: 25.17MB
 Metadata Space Available: 24.57MB
 Thin Pool Minimum Free Space: 2.333GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.62-21.56.amzn1.x86_64
Operating System: Amazon Linux AMI 2017.09
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955GiB
Name: ip-172-31-38-65
ID: XNRA:RMA2:5VQ5:NLVZ:WAWS:VJFF:24R7:RZNS:32X4:DRF2:SA2S:WP7C
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS on a t2.small

### PR DESCRIPTION
**Pull request by jahkeup**
Fixes https://github.com/moby/moby/issues/35725

**- What I did**

* Added a type to encapsulate the batch and its associated size counter.
* Cleaned up types and declarations for code cleanliness

**- How I did it**

The added type holds the batching mechanism and the counter used for determining whether or not to submit a batch of log events.

**- How to verify it**

The change can be verified by using the steps from #35725 to reproduce the issue and then comparing it to a build from this changeset. The appropriate test and test mock have been updated to validate this behavior.

**- Description for the changelog**
awslogs: fix batch size calculation for large logs

**- A picture of a cute animal (not mandatory but encouraged)**
https://www.reddit.com/r/aww/comments/7hzq4m

cc @samuelkarp @adnxn

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @anusha-ragunathan PTAL

**Comment by jahkeup** [comment]
I'm investigating these errors now, I didn't have these same errors when running tests locally.

**Comment by jahkeup** [comment]
There's a race condition with the mock and the tests, I'm going to continue to narrow it down and fix it.

**Comment by jahkeup** [comment]
Looks like jenkins failed to get janky and powerpc tests up and running. Can we restart those tests?

**Comment by thaJeztah** [comment]
Restarted :+1:

**Comment by thaJeztah** [comment]
@jahkeup if you need to make additional changes, can you remove the `fixes #xxx` from the commit message, and move it to the PR's description? GitHub can become noisy if such commits are cherry-picked or people fork the repo and do merges etc. (I know, I know) 😅

**Comment by jahkeup** [comment]
@thaJeztah no problem! I've removed the 'fixes' reference and made a mental note to not include that in the future :+1: 

@anusha-ragunathan PTAL, I tested the latest set of changes locally with ~500 rounds to see if the test flaked out - this seems stable now and is passing tests.

File: daemon/logger/awslogs/cloudwatchlogs.go [hunk 1]
```diff
@@ -95,6 +95,52 @@ func init() {
...
+		events: make([]wrappedEvent, 0),
+		bytes:  0,
+	}
+}
+
+// Events returns the sorted slice of wrappedEvents.
+func (b *eventBatch) Events() []wrappedEvent {
+	// events in a batch must be sorted by timestamp
+	// see http://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.html
+	sort.Sort(byTimestamp(b.events))
```
Comment (thaJeztah) [inline daemon/logger/awslogs/cloudwatchlogs.go]: Isn't this undoing https://github.com/moby/moby/commit/443f251cf596006fe4cb621dcab955f7da0a2a00 (https://github.com/moby/moby/pull/24814)? /cc @samuelkarp

Comment (jahkeup) [reply daemon/logger/awslogs/cloudwatchlogs.go]: This is respecting that, the code that stable sorts according to timestamp and then insertion order is implemented in the sort for this type (https://github.com/jahkeup/moby/blob/b0046c3e68579640b5b08a4cb8b754924fbc2a30/daemon/logger/awslogs/cloudwatchlogs.go#L631).

The insertion order is recorded as the wrappedEvent is crafted.

File: daemon/logger/awslogs/cloudwatchlogs.go [hunk 2]
```diff
@@ -83,18 +120,65 @@ type wrappedEvent struct {
...
+	return b.events
+}
+
+// Add adds an event to the batch of events. This adds in the
+// necessary overhead for an event to be logged.
+func (b *eventBatch) Add(event wrappedEvent, size int) {
+	b.bytes = b.bytes + size + perEventBytes
+	b.events = append(b.events, event)
```
Comment (anusha-ragunathan) [inline daemon/logger/awslogs/cloudwatchlogs.go]: Looks unsafe.

Comment (anusha-ragunathan) [reply daemon/logger/awslogs/cloudwatchlogs.go]: Same case with `Count` and `Size`.

File: daemon/logger/awslogs/cloudwatchlogs.go (hunk 1 above)
Comment (thaJeztah) [reply daemon/logger/awslogs/cloudwatchlogs.go]: Ah, thanks! Sorry, it wasn't clear directly 😊 Do you think we need to change `byTimestamp` to something else? Alternatively, move the description of sorting to the GoDoc of the `Events()` method, and describe that it's sorting by timestamp, but preserving `insertOrder` if timestamp is equal

File: daemon/logger/awslogs/cloudwatchlogs.go (hunk 2 above)
Comment (jahkeup) [reply daemon/logger/awslogs/cloudwatchlogs.go]: Indeed. This type isn't intended for concurrently use and isn't accessed concurrently as it stands - hence the unsafe operations. Do you have suggestions to improve this given the current implementation of its consumer? My goal here was to keep the type small and simple for this use case, but I am happy to add some mechanisms for safety.

File: daemon/logger/awslogs/cloudwatchlogs.go [hunk 3]
```diff
@@ -460,37 +411,30 @@ func (l *logStream) processEvent(events []wrappedEvent, unprocessedLine []byte,
 		}
 		line := unprocessedLine[:lineBytes]
 		unprocessedLine = unprocessedLine[lineBytes:]
-		if (len(events) >= maximumLogEventsPerPut) || (bytes+lineBytes+perEventBytes > maximumBytesPerPut) {
+		if (batch.Count() >= maximumLogEventsPerPut) || (batch.Size()+lineBytes+perEventBytes > maximumBytesPerPut) {
```
Comment (thaJeztah) [inline daemon/logger/awslogs/cloudwatchlogs.go]: Just thinking out loud here; wondering if we could make `batch.Add()` reject the event if the Size or Count limit was reached, something like (dummy code);

```go
err := batch.Add(event)

switch err := err.(type) {
case <maximum size reached>, <maximum logs reached>:
   l.publishBatch(batch)
case nil:
   unprocessedLine = unprocessedLine[lineBytes:]
default:
  // something bad happened :D
}
```
     



}

Comment (jahkeup) [reply daemon/logger/awslogs/cloudwatchlogs.go]: That would certainly clean up some of these checked `Add()`s! I like the indication of the error and codification of the limit check in the batch itself, let me whip something up.

File: daemon/logger/awslogs/cloudwatchlogs.go (hunk 2 above)
Comment (thaJeztah) [reply daemon/logger/awslogs/cloudwatchlogs.go]: May need a mention in the function description; also given that it's only use in this file, we should probably un-export these methods

File: daemon/logger/awslogs/cloudwatchlogs.go (hunk 1 above)
Comment (jahkeup) [reply daemon/logger/awslogs/cloudwatchlogs.go]: I'll update the GoDoc for this method to clarify the action and results of retrieving the events from the batch.

The `byTimestamp` type could probably be better named for its usages, however I can't think of a more apt name without stringing together many many words. Do you have any suggestions on a different name? Do you think the GoDoc statement could instead be more clear without needing a name change?

File: daemon/logger/awslogs/cloudwatchlogs.go [hunk 4]
```diff
@@ -460,37 +411,30 @@ func (l *logStream) processEvent(events []wrappedEvent, unprocessedLine []byte,
...
-	return events
 }
 
 // publishBatch calls PutLogEvents for a given set of InputLogEvents,
 // accounting for sequencing requirements (each request must reference the
 // sequence token returned by the previous request).
-func (l *logStream) publishBatch(events []wrappedEvent) {
-	if len(events) == 0 {
+func (l *logStream) publishBatch(batch *eventBatch) {
+	if batch.Count() == 0 {
```
Comment (anusha-ragunathan) [inline daemon/logger/awslogs/cloudwatchlogs.go]: What if  `batch.Count` is 0, but `batch.bytes` is non-zero? Things could get out of whack. Probably better to `Reset` before return anyways.

File: daemon/logger/awslogs/cloudwatchlogs.go (hunk 2 above)
Comment (jahkeup) [reply daemon/logger/awslogs/cloudwatchlogs.go]: Sounds good. This type is only used here so I'll unexport the methods. I'll also include a statement about the thread unsafe nature in each method's GoDoc line to make sure future developers understand this design assumption.

**Comment by samuelkarp** [comment]
I'm not wild about how you've reorganized the code here.  Previously, the code was intended to be ordered such that caller was above callee, or most-abstract to most-concrete.  Now you have concrete implementation details (like the `eventBatch` type) above the parts of the code that are the core logic of the log driver (like the exported methods for `logStream`).  Might be worth breaking things out into separate files at this point.

File: daemon/logger/awslogs/cloudwatchlogs.go [hunk 5]
```diff
@@ -450,47 +443,42 @@ func (l *logStream) collectBatch() {
...
 				Timestamp: aws.Int64(timestamp),
 			},
-			insertOrder: len(events),
-		})
-		bytes += (lineBytes + perEventBytes)
+			insertOrder: batch.count(),
+		}
+
+		switch batch.add(event, lineBytes) {
+		case errBatchCountTooLarge, errBatchSizeTooLarge:
```
Comment (samuelkarp) [inline daemon/logger/awslogs/cloudwatchlogs.go]: Both of these errors result in the exact same code being run.  Why not just return `bool` so you can do

```go
if ok := batch.add(event, lineBytes); ok {
	unprocessedLine = unprocessedLine[lineBytes:]
} else {
	l.publishBatch(batch)
}
```

File: daemon/logger/awslogs/cloudwatchlogs.go [hunk 6]
```diff
@@ -520,6 +508,10 @@ func (l *logStream) publishBatch(events []wrappedEvent) {
 	} else {
 		l.sequenceToken = nextSequenceToken
 	}
+	// Reset occurs regardless of error. The payload itself may be
+	// causing issues and would otherwise prevent more events from being
+	// sent.
+	batch.Reset()
```
Comment (samuelkarp) [inline daemon/logger/awslogs/cloudwatchlogs.go]: Should `batch.Reset()` happen here or in `processEvent` after the call to `publishBatch`?  My vote would probably be for the latter since `processEvent` is what owns the `eventBatch`.

**Comment by anusha-ragunathan** [comment]
`DockerSwarmSuite.TearDownTest` fails to shutdown the daemon.

```
`FAIL: check_test.go:366: DockerSwarmSuite.TearDownTest
00:49:43 
00:49:43 check_test.go:371:
00:49:43     d.Stop(c)
00:49:43 daemon/daemon.go:395:
00:49:43     t.Fatalf("Error while stopping the daemon %s : %v", d.id, err)
00:49:43 ... Error: Error while stopping the daemon d7f3fe1f6d643 : exit status 130
00:49:43 ```

I notice this in the logs:

```
time="2017-12-09T00:49:36.542132074Z" level=error msg="agent failed to clean up assignments" error="context deadline exceeded"
time="2017-12-09T00:49:36.542203730Z" level=error msg="failed to shut down cluster node: context deadline exceeded"
goroutine 1 [running]:
github.com/docker/docker/pkg/signal.DumpStacks(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/pkg/signal/trap.go:83 +0xc5
github.com/docker/docker/daemon/cluster.(*Cluster).Cleanup(0xc420850000)
	/go/src/github.com/docker/docker/daemon/cluster/cluster.go:365 +0x1c2
main.(*DaemonCli).start(0xc4204c4c60, 0xc4204c6a10, 0x0, 0x0)
	/go/src/github.com/docker/docker/cmd/dockerd/daemon.go:314 +0x1b3b
main.runDaemon(0xc4204c6a10, 0xc42033eb40, 0x0)
	/go/src/github.com/docker/docker/cmd/dockerd/docker.go:78 +0x76
main.newDaemonCommand.func1(0xc4204646c0, 0xc420135d00, 0x0, 0x10, 0x0, 0x0)
	/go/src/github.com/docker/docker/cmd/dockerd/docker.go:29 +0x5b
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0xc4204646c0, 0xc420010130, 0x10, 0x11, 0xc4204646c0, 0xc420010130)
	/go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:646 +0x44d
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4204646c0, 0x1accbc0, 0xc420464701, 0xc42047ce80)
	/go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:742 +0x30e
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4204646c0, 0xc42047ce80, 0xc420000260)
	/go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:695 +0x2b
main.main()
	/go/src/github.com/docker/docker/cmd/dockerd/docker.go:105 +0xe1
```



There is a followup panic in `TestAPISwarmServicesUpdateStartFirst`, due to several instances of dockerd running.

```
00:49:43 PANIC: docker_api_swarm_service_test.go:201: DockerSwarmSuite.TestAPISwarmServicesUpdateStartFirst
00:49:43 
00:49:43 [d7f3fe1f6d643] waiting for daemon to start
00:49:43 [d7f3fe1f6d643] daemon started
00:49:43 
00:49:43 [d7f3fe1f6d643] daemon started
00:49:43 Attempt #2: daemon is still running with pid 9963
00:49:43 Attempt #3: daemon is still running with pid 9963
00:49:43 Attempt #4: daemon is still running with pid 9963
00:49:43 [d7f3fe1f6d643] exiting daemon
00:49:43 ... Panic: Fixture has panicked (see related PANIC)
```

**Comment by anusha-ragunathan** [comment]
@jahkeup : Can you look into these test failures? Do they happen when you run integration tests locally?

**Comment by anusha-ragunathan** [comment]
@jahkeup : This patch has code rearrangement that's not necessary, as mentioned in https://github.com/moby/moby/pull/35726#issuecomment-350593702. Can you update the change such that only the code relevant to the fix is updated? We want to keep the code changes minimal, if and when possible. This also becomes important for considerations for backporting/crossporting to other releases.

**Comment by jahkeup** [comment]
@anusha-ragunathan yes I think that's prudent, and what I had in mind also. I will work with @samuelkarp offline to clean up and make some other improvements to this package.

I'm still trying to repro the above failures in the integration tests. I do have some failures, but they're different one tests from the ones observed on jenkins and they seem to be happening irregularly. I'll try rebasing to take in any test fixes to see if it makes a difference.

**Comment by thaJeztah** [comment]
The teardowntest itself sometimes fails, so not nescessarily related (haven't checked the full output)

File: daemon/logger/awslogs/cloudwatchlogs.go (hunk 5 above)
Comment (jahkeup) [reply daemon/logger/awslogs/cloudwatchlogs.go]: There's certainly simplicity in the `bool` approach, but I think that having the result codified is easier to reason about. I prefer to know that the there's a reason behind not adding the event, not just that it was added or not and the overhead to do so is negligible.

File: daemon/logger/awslogs/cloudwatchlogs.go (hunk 6 above)
Comment (jahkeup) [reply daemon/logger/awslogs/cloudwatchlogs.go]: This would make it clearer that we're reusing the object if we lift the call up as you suggest - note that the batch is owned by `collectBatch` where additional call sites would exist. This change would mean that each `publishBatch()` _must_ be followed by `batch.Reset()`, otherwise duplicate batch of events will be put into CloudWatch. It's simpler to leave it in `publishBatch`, but this hides its side effect; I'm going to add the additional calls to `batch.Reset()` unless you think that doesn't make sense or if you had something else in mind.

File: daemon/logger/awslogs/cloudwatchlogs.go (hunk 5 above)
Comment (samuelkarp) [reply daemon/logger/awslogs/cloudwatchlogs.go]: You're not recording that anywhere though.  When I was reading the code, the different errors confused me because I didn't know how they were handled differently.  Since they're in fact handled the same way and we don't ever do anything with the reason it seems like an unnecessary distinction.

File: daemon/logger/awslogs/cloudwatchlogs.go (hunk 6 above)
Comment (samuelkarp) [reply daemon/logger/awslogs/cloudwatchlogs.go]: A different model (though I haven't thought about it enough to know whether I like the idea) is to make a new method `batch.Publish()` that is responsible for both publishing and resetting the internal buffer.

Comment (jahkeup) [reply daemon/logger/awslogs/cloudwatchlogs.go]: I had a similar thought, but I dismissed on the grounds of keeping the submission of the events in the log driver and out of the `eventBatch` container type. I'd rather have the submission responsibility on the log driver for now.

File: daemon/logger/awslogs/cloudwatchlogs.go (hunk 5 above)
Comment (jahkeup) [reply daemon/logger/awslogs/cloudwatchlogs.go]: You're right, either way we'll be handling it and arriving at the same result. This is a YAGNI situation, I'll drop this.

**Comment by jahkeup** [comment]
@anusha-ragunathan PTAL, I've updated the code and the tests are now passing.

**Review by samuelkarp — APPROVED** [review]
LGTM

**Comment by anusha-ragunathan** [comment]
LGTM

File: daemon/logger/awslogs/cloudwatchlogs.go [hunk 7]
```diff
@@ -450,47 +461,41 @@ func (l *logStream) collectBatch() {
...
 				Timestamp: aws.Int64(timestamp),
 			},
-			insertOrder: len(events),
-		})
-		bytes += (lineBytes + perEventBytes)
+			insertOrder: batch.count(),
+		}
+
+		added := batch.add(event, lineBytes)
+		if added {
```
Comment (thaJeztah) [inline daemon/logger/awslogs/cloudwatchlogs.go]: Nit; this could be (no need to change)

```go
if ok := batch.add(event, lineBytes); ok {
```

File: daemon/logger/awslogs/cloudwatchlogs.go [hunk 8]
```diff
@@ -615,3 +620,70 @@ func unwrapEvents(events []wrappedEvent) []*cloudwatchlogs.InputLogEvent {
 	}
 	return cwEvents
 }
+
+func newEventBatch() *eventBatch {
```
Comment (thaJeztah) [inline daemon/logger/awslogs/cloudwatchlogs.go]: Perhaps in a future rewrite we could pass in `maximumLogEventsPerPut` and `maximumBytesPerPut` (they feel like a property of the `eventsBatch`);

```go
func newEventBatch(maxEvents uint, maxBytes uint) *eventBatch { 
```

File: daemon/logger/awslogs/cloudwatchlogs.go [hunk 9]
```diff
@@ -615,3 +620,70 @@ func unwrapEvents(events []wrappedEvent) []*cloudwatchlogs.InputLogEvent {
...
+// size is the total number of bytes that the batch represents.
+//
+// Warning: this method is not threadsafe and must not be used
+// concurrently.
+func (b *eventBatch) size() int {
+	return b.bytes
+}
+
+func (b *eventBatch) isEmpty() bool {
+	zeroEvents := b.count() == 0
```
Comment (thaJeztah) [inline daemon/logger/awslogs/cloudwatchlogs.go]: nit: these variables are a bit redundant;

```go
return b.count() == 0 && b.size() == 0
```

File: daemon/logger/awslogs/cloudwatchlogs.go [hunk 10]
```diff
@@ -450,47 +461,41 @@ func (l *logStream) collectBatch() {
...
-		if (len(events) >= maximumLogEventsPerPut) || (bytes+lineBytes+perEventBytes > maximumBytesPerPut) {
-			// Publish an existing batch if it's already over the maximum number of events or if adding this
-			// event would push it over the maximum number of total bytes.
-			l.publishBatch(events)
-			events = events[:0]
-			bytes = 0
-		}
-		events = append(events, wrappedEvent{
+
+		event := wrappedEvent{
```
Comment (thaJeztah) [inline daemon/logger/awslogs/cloudwatchlogs.go]: Wrapping and Unwrapping could be done in `batch.add()` / `batch.events()` as they're really related to how the batch stores the events (i.e. just for preserving the events order)

**Review by thaJeztah — APPROVED** [review]
LGTM

left some suggestions for a follow up, but no showstoppers
