### PR TITLE
fix parseInfoFile does not handle spaces in filenames

### LINKED ISSUE #38458: parseInfoFile does not handle spaces in filenames
**Description**

When using the ["github.com/docker/docker/pkg/mount"](https://godoc.org/github.com/docker/docker/pkg/mount) package's `Mounted` function, it falsely claims that a certain path is not mounted when in fact it is. It appears that a path containing spaces is not properly unescaped from `/proc/self/mountinfo` before being compared.

**Steps to reproduce the issue:**
1. `mount /dev/sdx /mnt/foo\ bar`
2. call `mount.Mounted("/mnt/foo bar")`

**Describe the results you received:**

`false, nil`

**Describe the results you expected:**

`true, nil`

**Additional information you deem important (e.g. issue happens only occasionally):**

This is probably something to check for on non-Linux platforms too.

### PR DESCRIPTION
**Pull request by thaJeztah**
fixes https://github.com/moby/moby/issues/38458
addresses https://github.com/kubernetes/kubernetes/issues/35062

`/proc/self/mountinfo` uses `\040` for spaces, however, `parseInfoFile()`
did not decode those spaces in paths, therefore attempting to use `\040`
as a literal part of the path.

This patch un-quotes the `root` and `mount point` fields to fix
situations where paths contain spaces.

Note that the `mount source` field is not modified, given that
this field is documented (man `PROC(5)`) as:

    filesystem-specific information or "none"

Which I interpreted as "the format in this field is undefined".

Thanks to @remexre for reporting, and @itizir, @sergei-utinski for suggesting the patch.

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @kolyshkin @cpuguy83 PTAL

File: pkg/mount/mountinfo_linux.go [hunk 1]
```diff
@@ -52,8 +56,17 @@ func parseInfoFile(r io.Reader, filter FilterFunc) ([]*Info, error) {
 		p.Major, _ = strconv.Atoi(mm[0])
 		p.Minor, _ = strconv.Atoi(mm[1])
 
-		p.Root = fields[3]
-		p.Mountpoint = fields[4]
+		r, err := strconv.Unquote(`"` + fields[3] + `"`)
```
Comment (kolyshkin) [inline pkg/mount/mountinfo_linux.go]: According to kernel sources, the only characters replaced by `\nnn` are space, tab, newline, and backslash (`\`).

Initially I was opposed to using `strconv.Unquote()` but it seems if `\` is always escaped, `Unquote` can do no harm.

BTW, note that Linux file paths can indeed contain newlines, tabs, and backslashes :=0

File: pkg/mount/mountinfo_linux.go [hunk 2]
```diff
@@ -52,8 +56,17 @@ func parseInfoFile(r io.Reader, filter FilterFunc) ([]*Info, error) {
...
+		if err != nil {
+			return nil, errors.Wrapf(err, "Parsing '%s' failed: unable to unquote root field", fields[3])
+		}
+		p.Root = r
+
+		mp, err := strconv.Unquote(`"` + fields[4] + `"`)
```
Comment (kolyshkin) [inline pkg/mount/mountinfo_linux.go]: There's no need to have a temp variable here, since you exit on error anyway, so maybe
```go
root.Mountpoint, err := strconv.Unquote(`"` + fields[4] + `"`)
if err != nil {
￼ 			return nil, errors.Wrapf(err, "Can't parse mount point %q", fields[4])
}
```

(I have also made error message smaller, but it's up to you)

**Review by kolyshkin — APPROVED** [review]
Added a few comments, but it's all very minor nitpicks so LGTM

**Comment by kolyshkin** [comment]
BTW this needs to be ported to containerd, too.

(as a side note, I am puzzled why I haven't fixed this as part of https://github.com/moby/moby/pull/36091as I was very much aware of the issue)

File: pkg/mount/mountinfo_linux.go (hunk 2 above)
Comment (thaJeztah) [reply pkg/mount/mountinfo_linux.go]: Yes, I wanted to do a follow up to fix the error messages (also make them lowercase); for this fix, I went for consistency with the existing ones.

**Comment by thaJeztah** [comment]
Updated; removed the intermediate variable (no other changes)
