### PR TITLE
Don't set default platform on container create

### LINKED ISSUE #41552: [20.10 beta] regression / change in behavior when running different architecture images
See https://github.com/moby/moby/pull/40725#issuecomment-709393496

This came up in CI for Docker Desktop;

looks like  https://github.com/moby/moby/pull/40725 introduced a regression / change in behavior; it will now  at all times print an error, even if the platform supports the other architecture (through quemu); 

```
docker run --rm arm32v7/alpine uname -m

Unable to find image 'arm32v7/alpine:latest' locally
latest: Pulling from arm32v7/alpine
52278dd8e579: Pulling fs layer
52278dd8e579: Verifying Checksum
52278dd8e579: Download complete
52278dd8e579: Pull complete
Digest: sha256:c929c5ca1d3f793bfdd2c6d6d9210e2530f1184c0f488f514f1bb8080bb1e82b
Status: Downloaded newer image for arm32v7/alpine:latest
docker: Error response from daemon: image with reference arm32v7/alpine was found but does not match the specified platform cpu architecture: wanted: amd64, actual: arm.
See 'docker run --help
```

The above previously worked, but now requires the `--platform` flag to be set (even though the image is not multi-arch)

/cc @cpuguy83 @tonistiigi

### PR DESCRIPTION
**Pull request by cpuguy83**
- fixes https://github.com/moby/moby/issues/41552

This fixes a regression based on expectations of the runtime:

```
docker pull arm32v7/alpine
docker run arm32v7/alpine
```

Without this change, the `docker run` will fail due to platform
matching on non-arm32v7 systems, even though the image could run
(assuming the system is setup correctly).

This also emits a warning to make sure that the user is aware that a
platform that does not match the default platform of the system is being
run, for the cases like:

```
docker pull --platform armhf busybox
docker run busybox
```

Not typically an issue if the requests are done together like that, but
if the image was already there and someone did `docker run` without an
explicit `--platform`, they may very well be expecting to run a native
version of the image instead of the armhf one.

This warning does add some extra noise in the case of platform specific
images being run, such as `arm32v7/alpine`, but this can be supressed by
explicitly setting the platform.

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

File: daemon/create.go [hunk 1]
```diff
@@ -77,6 +81,30 @@ func (daemon *Daemon) containerCreate(opts createOpts) (containertypes.Container
...
+		var platWarning bool
+		if img.OS != "" && img.OS != p.OS {
+			platWarning = true
+		}
+		if img.Architecture != "" && img.Architecture != p.Architecture {
+			platWarning = true
+		}
+		if img.Variant != "" && img.Variant != p.Variant {
+			platWarning = true
+		}
```
Comment (tianon) [inline daemon/create.go:96]: I'm a little confused why this is matching all these bits directly -- shouldn't it instead just be using `platforms.Only` and asking if the image matches so it'll check the full vector for things like `linux/arm/v7` supporting `v6`, etc?

Essentially:

```go
if !platforms.Only(platforms.DefaultSpec()).Match(imagePlatform) {
// ... warning
}
```

Comment (cpuguy83) [reply daemon/create.go:90]: Fixed, also did this same thing for the image store.

**Comment by cpuguy83** [comment]
Updated with test.

**Review by tianon — APPROVED** [review]
LGTM :+1:

**Comment by cpuguy83** [comment]
Rebased to fix build issue.

**Review by tianon — APPROVED** [review]

**Comment by thaJeztah** [comment]
Looks like there's a compile failure;

```
[2020-10-19T14:42:32.889Z] daemon/images/image.go:55:146: undefined: ref
[2020-10-19T14:42:32.889Z] daemon/images/image.go:55: undefined: ref
```

**Comment by cpuguy83** [comment]
That's what I get for changing an error message.... Should be good now.

**Comment by thaJeztah** [comment]
Arf... failiure on Windows;

```

[2020-10-20T17:11:50.699Z] === FAIL: github.com/docker/docker/integration/container TestCreatePlatformSpecificImageNoPlatform (0.03s)
[2020-10-20T17:11:50.699Z]     create_test.go:528: assertion failed: error is not nil: Error response from daemon: No such image: arm32v7/hello-world:latest
```

**Comment by cpuguy83** [comment]
Fixed 😅

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
ignoring the s390 failures, they're unrelated
