### PR TITLE
Reset restart timeout if execution longer than 10s

### LINKED ISSUE #22113: docker 1.11 restart always policy issue
Up to Docker 1.10.3, exiting docker containers were restarted with policy "always".
Since 1.11.0, our service that exit to get restarted never gets restarted.

**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:38:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:38:59 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 30
 Running: 30
 Paused: 0
 Stopped: 0
Images: 38
Server Version: 1.11.0
Storage Driver: devicemapper
 Pool Name: docker-252:0-525747-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 20.28 GB
 Data Space Total: 107.4 GB
 Data Space Available: 87.1 GB
 Metadata Space Used: 26.96 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.121 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.99 (2015-06-20)
Logging Driver: syslog
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-35-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.67 GiB
Name: djd
ID: MYTR:G2WK:32TJ:UYFZ:5PBY:CXF7:3ZCL:ZR7P:3ICF:Y4DT:ZH7P:LGZG
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
KVM

**Steps to reproduce the issue:**
1. Run containers like before with restart policy set to "always".
2. Some containers' process exit and stay stuck in restarting mode.
3. Doing a `docker restart <container id>` does work though.

**Describe the results you received:**
container are never run again

**Describe the results you expected:**
container are restarted after they exit

**Additional information you deem important (e.g. issue happens only occasionally):**

docker inspect --format '{{ .HostConfig.RestartPolicy.Name }}' crawler_1 :
always

docker ps will show something like this:
66073d74ff57        registry.example.com/crawler          "python2 run_crawler."   20 hours ago        Restarting (0) About an hour ago                                                   crawler_1

The daemon's log also show a bunch of these:
Apr 18 10:06:31 server docker[720]: time="2016-04-18T10:06:31.152210600-04:00" level=error msg="restartmanager canceled"

(Doesn't seem related to #22042)

### LINKED ISSUE #22159: Docker restart delay is not reset as described
**Output of `docker version`:**

```
  root@buildmaster-ubuntu-6:~# docker version
  Client:
   Version:      1.11.0
   API version:  1.23
   Go version:   go1.5.4
   Git commit:   4dc5990
   Built:        Wed Apr 13 18:34:23 2016
   OS/Arch:      linux/amd64

  Server:
   Version:      1.11.0
   API version:  1.23
   Go version:   go1.5.4
   Git commit:   4dc5990
   Built:        Wed Apr 13 18:34:23 2016
   OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
  root@buildmaster-ubuntu-6:~# docker info
  Containers: 0
   Running: 0
   Paused: 0
   Stopped: 0
  Images: 0
  Server Version: 1.11.0
  Storage Driver: aufs
   Root Dir: /var/lib/docker/aufs
   Backing Filesystem: extfs
   Dirs: 10
   Dirperm1 Supported: true
  Logging Driver: json-file
  Cgroup Driver: cgroupfs
  Plugins:
   Volume: local
   Network: host bridge null
  Kernel Version: 4.2.0-27-generic
  Operating System: Ubuntu 14.04.4 LTS
  OSType: linux
  Architecture: x86_64
  CPUs: 8
  Total Memory: 7.696 GiB
  Name: buildmaster-ubuntu-6
  ID: GJXV:3SLH:VQXH:EABF:CH2E:KF2B:STL6:YOJS:J6CC:GVRO:4SUH:MI6H
  Docker Root Dir: /var/lib/docker
  Debug mode (client): false
  Debug mode (server): false
  Registry: https://index.docker.io/v1/
  WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

  Fresh install of ubuntu 14.04 and docker on physical hardware

  root@buildmaster-ubuntu-6:~# lsb_release -a
  No LSB modules are available.
  Distributor ID:          Ubuntu
  Description:     Ubuntu 14.04.4 LTS
  Release:         14.04
  Codename:        trusty

  root@buildmaster-ubuntu-6:~# uname -a
  Linux buildmaster-ubuntu-6 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri
  Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Steps to reproduce the issue:**
1. On machine with docker:

   docker run -d --restart=always -t --privileged -p 2020:2020 \
     --name nc-test ubuntu nc -l 2020

   # then run this to watch timing
   watch docker ps

2. From another window:

   echo foo | nc <docker-host> 2020

3. The docker ps output will show a restart, wait for it to be running
   for at least 10 seconds.

4. Repeat steps 2 and 3 and watch the restart time increase on each
   invocation.

**Describe the results you received:**

I do not observe the delay being reset.

**Describe the results you expected:**

I expected restart delay to always be 100ms after waiting 10+ seconds as per the documentation at:
  https://github.com/docker/docker/blob/master/docs/reference/run.md
which says:

  "If a container is successfully restarted (the container is started and
  runs for at least 10 seconds), the delay is reset to its default value
  of 100 ms."

**Additional information you deem important (e.g. issue happens only occasionally):**

consistently reproducible

### PR DESCRIPTION
**Pull request by crosbymichael**
Restore the 1.10 logic that will reset the restart manager's timeout or
backoff delay if a container executes longer than 10s reguardless of
exit status or policy.

Fixes #22113
Fixes #22159

Signed-off-by: Michael Crosby crosbymichael@gmail.com

### CODE REVIEW

**Comment by tonistiigi** [comment]
Could this be implemented with just a property of restartmanager that keeps the last restart time instead of passing start time in. We don't really need the start time for the first restart, only for the next restarts that use the same restartmanager.

**Comment by crosbymichael** [comment]
@tonistiigi the restart manager does not know when the container was actually started.  Does a call to `ShouldRestart` imply the its going to be started soon?

**Comment by tonistiigi** [comment]
@crosbymichael Successfully returning from `ShouldRestart` implies that container will be started again. Next call could use the previously stored value.

**Comment by crosbymichael** [comment]
@tonistiigi meh, why not be explicit instead of assume things? This method looks like it could be called multiple times and nothing implies that the container will be started anytime just because you call this method.

**Comment by icecrime** [comment]
```14:23:10 Building: bundles/1.12.0-dev/cross/windows/amd64/docker-1.12.0-dev.exe
14:23:50 # github.com/docker/docker/libcontainerd
14:23:50 libcontainerd/container_windows.go:171: not enough arguments in call to ctr.containerCommon.restartManager.ShouldRestart
```

**Comment by thaJeztah** [comment]
Faulty test? https://jenkins.dockerproject.org/job/Docker-PRs/26562/console

```
23:52:05 ----------------------------------------------------------------------
23:52:05 FAIL: docker_cli_run_unix_test.go:997: DockerSuite.TestRunSeccompWithDefaultProfile
23:52:05 
23:52:05 docker_cli_run_unix_test.go:1002:
23:52:05     c.Assert(strings.TrimSpace(out), checker.Equals, "unshare: unshare failed: Operation not permitted")
23:52:05 ... obtained string = "" +
23:52:05 ...     "/go/src/github.com/docker/docker/bundles/1.12.0-dev/test-integration-cli/../binary/docker: Error response from daemon: Untar re-exec error: exit status 1: output: no such file or directory.\n" +
23:52:05 ...     "See '/go/src/github.com/docker/docker/bundles/1.12.0-dev/test-integration-cli/../binary/docker run --help'."
23:52:05 ... expected string = "unshare: unshare failed: Operation not permitted"
```

**Comment by mlaventure** [comment]
@thaJeztah alll :green_heart: now

Otherwise, I tend to agree with @crosbymichael @tonistiigi

File: restartmanager/restartmanager.go [hunk 1]
```diff
@@ -60,7 +61,12 @@ func (rm *restartManager) ShouldRestart(exitCode uint32, hasBeenManuallyStopped
 	if rm.active {
 		return false, nil, fmt.Errorf("invalid call on active restartmanager")
 	}
-
+	logrus.Info(executionDuration.Seconds())
```
Comment (cpuguy83) [inline restartmanager/restartmanager.go]: Can you remove the log?

File: libcontainerd/container_windows.go [hunk 2]
```diff
@@ -168,7 +170,8 @@ func (ctr *container) waitExit(pid uint32, processFriendlyName string, isFirstPr
 		}
 
 		if si.State == StateExit && ctr.restartManager != nil {
-			restart, wait, err := ctr.restartManager.ShouldRestart(uint32(exitCode), false)
+			ctr.exitedAt = time.Now()
```
Comment (tonistiigi) [inline libcontainerd/container_windows.go]: No need to keep this as a property if only used locally. `time.Since()` is shorter and more readable.

**Comment by cpuguy83** [comment]
LGTM

**Comment by tonistiigi** [comment]
LGTM

**Comment by cpuguy83** [comment]
Restart tests are failing on TP5 for some reason.

**Comment by cpuguy83** [comment]
```
23:32:15 FAIL: docker_cli_restart_test.go:108: DockerSuite.TestRestartContainerwithGoodContainer
23:32:15 
23:32:15 docker_cli_restart_test.go:113:
23:32:15     c.Assert(err, checker.IsNil)
23:32:15 ... value *errors.errorString = &errors.errorString{s:"condition \"\"false true\" == \"false false\"\" not true in time"} ("condition \"\"false true\" == \"false false\"\" not true in time")
23:32:15 
23:33:59 
23:33:59 ----------------------------------------------------------------------
23:33:59 PASS: docker_cli_restart_test.go:222: DockerSuite.TestRestartContainerwithRestartPolicy	97.920s
23:34:43 
23:34:43 ----------------------------------------------------------------------
23:34:43 FAIL: docker_cli_restart_test.go:192: DockerSuite.TestRestartPolicyAfterRestart
23:34:43 
23:34:43 docker_cli_restart_test.go:216:
23:34:43     c.Assert(err, check.IsNil)
23:34:43 ... value *errors.errorString = &errors.errorString{s:"condition \"\"0\" == \"1\"\" not true in time"} ("condition \"\"0\" == \"1\"\" not true in time")
```

**Comment by mlaventure** [comment]
@jhowardmsft 

I'd say both TP5 failure are related to https://github.com/docker/docker/pull/21954 , is it safe to merge this  PR then?

**Comment by jhowardmsft** [comment]
@mlaventure hmmm no I don't think so. I would expect both to fail. Restarting to see what happens on another run.

**Comment by crosbymichael** [comment]
all green now, guess it wasn't my pr ;)

**Comment by jhowardmsft** [comment]
More flakey tests to investigate... :)
