### PR TITLE
fileutils: Fix incorrect handling of "**/foo" pattern

### LINKED ISSUE #41433: wildcard directories not implemented correctly in dockerignore
**Description**

wildcard directory matching in dockerignore (the double asterisk **) is not implemented correctly and buggy in some cases

**Steps to reproduce the issue:**
1. Dockerfile:

```
FROM busybox
WORKDIR /src
ADD . .
RUN find .
```

2. .dockerignore:

```
**/c
!a/b/c/include.txt
.git
```

3. Create files "a/b/c/include.txt" and "a/b/c/exclude.txt"

4. Run `docker build --no-cache .`

**Describe the results you received:**

a/b/c/exclude.txt should be ignored

**Describe the results you expected:**

a/b/c/exclude.txt is included in the docker context

**Additional information you deem important (e.g. issue happens only occasionally):**

This repo has a more complete explanation of the bug:

https://github.com/tilt-dev/dockerignore-wildcard-bug

The underlying bug is this code:

https://github.com/moby/moby/blob/v19.03.12/pkg/fileutils/fileutils.go#L83

which assumes that the number of directory separators in the pattern can be used to determine the "directory" length, which is not a correct assumption when wildcards are present.

Interestingly, the exclude pattern is necessary to reproduce this problem. That's because this code:

https://github.com/moby/moby/blob/v19.03.12/pkg/archive/archive.go#L843

skips directories purely as an optimization. Adding an exclusion pattern (!a/b/c/include.txt) makes this code go down the "slow" codepath.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:12:22 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       42e35e61f3
  Built:            Mon Jun  1 09:10:54 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

### PR DESCRIPTION
**Pull request by aaronlehmann**
`(*PatternMatcher).Matches` includes a special case for when the pattern
matches a parent dir, even though it doesn't match the current path.
However, it assumes that the parent dir which would match the pattern
must have the same number of separators as the pattern itself. This
doesn't hold true with a patern like `**/foo`. A file `foo/bar` would have
`len(parentPathDirs) == 1`, which is less than the number of path
`len(pattern.dirs) == 2`... therefore this check would be skipped.

Given that `**/foo` matches `foo`, I think it's a bug that the "parent
subdir matches" check is being skipped in this case.

It seems safer to loop over the parent subdirs and check each against
the pattern. It's possible there is a safe optimization to check only a
certain subset, but the existing logic seems unsafe.

This was found while using the `IncludePatterns` feature of BuildKit's
"copy" op.

- Fixes: #41433
- addresses https://github.com/moby/moby/issues/42788
- related: https://github.com/moby/moby/issues/40319

cc @coryb @tonistiigi

### CODE REVIEW

**Comment by thaJeztah** [comment]
Relates to https://github.com/moby/moby/issues/40319 (I see there's https://github.com/moby/moby/issues/41433 - not sure if this addresses that though)

**Comment by aaronlehmann** [comment]
Yes, this fixes #41433

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@AkihiroSuda @tonistiigi PTAL

**Comment by aaronlehmann** [comment]
Is anyone available to review this one? Thanks!

**Review by tonistiigi — COMMENTED** [review]
I'm not quite sure how the parent check is used in the common cases. Is it ever needed for the walk cases used in dockerignore/buildkit and if it is, can't there be more optimal caching. Asking because this seems to introduce more complexity per single file due to another loop.

**Comment by aaronlehmann** [comment]
> Is it ever needed for the walk cases used in dockerignore/buildkit

Yes, #41433 is a dockerignore issue this PR fixes.

> can't there be more optimal caching

Are you suggesting a cache in `PatternMatcher` to memoize these calls to `match`?

**Comment by aaronlehmann** [comment]
A possible optimization here would be to introduce a new method:

```go
(pm *PatternMatcher) MatchesUsingParentResult(file string, anyParentMatched bool) (bool, error) {
	matched := false
	file = filepath.FromSlash(file)
	parentPath := filepath.Dir(file)
	parentPathDirs := strings.Split(parentPath, string(os.PathSeparator))
	for _, pattern := range pm.patterns {
		negative := false
		if pattern.exclusion {
			negative = true
		}
		match, err := pattern.match(file)
		if err != nil {
			return false, err
		}

		if !match && parentPath != "." {
			// Did the pattern matches one of our parent dirs?
			match = anyParentMatched
		}

		if match {
			matched = !negative
		}
	}
	return matched, nil
}
```

Then callers doing a complete walk which can keep track of whether any parent matched can use this method instead of the slower implementation in `Matches`.

**Comment by tonistiigi** [comment]
That latest suggestion sgtm. Might even make sense to detect if there are any exclusions at all in the matcher and avoid checking children completely if not.

**Comment by aaronlehmann** [comment]
CI failure looks unrelated.

File: pkg/fileutils/fileutils.go [hunk 1]
```diff
@@ -55,19 +55,24 @@ func NewPatternMatcher(patterns []string) (*PatternMatcher, error) {
 	return pm, nil
 }
 
-// Matches matches path against all the patterns. Matches is not safe to be
-// called concurrently
+// Matches returns true if "file" matches any of the patterns
```
Comment (tonistiigi) [inline pkg/fileutils/fileutils.go:58]: Could we rename this and remove the `range`  loop. So all callers need to update and choose if they don't need to match parents or if they track the parents on the caller side.

Comment (aaronlehmann) [reply pkg/fileutils/fileutils.go:58]: What's the use case for not matching parent dirs? I think that would give incorrect behavior with a number of patterns. Are there cases where we know in advance we wouldn't encounter such patterns?

Removing `Matches` would complicate code that isn't doing a walk. For example, `removeDockerfile` currently uses `Matches`, and it would need similar logic to the loop in `Matches`. Even `TarWithOptions`, which I modified to use `MatchesUsingParentResult`, uses `Matches` as a convenience on the first file/dir it encounters matching the current `include` prefix.

Comment (tonistiigi) [reply pkg/fileutils/fileutils.go:58]: I think it is unexpected that this function now has `m*n` complexity and this would make it sure it doesn't go unnoticed. If you think there are cases that need parent matches but would still prefer to use `Matches` (eg. they only call a single file anyway) maybe leave it as is but rename to `MatchesOrAnyParentMatches`.

Comment (aaronlehmann) [reply pkg/fileutils/fileutils.go:58]: Renamed it. I kept the original (buggy) implementation as well because some vendored code calls it. We can remove it as a second step.

**Comment by aaronlehmann** [comment]
@tonistiigi: Do the latest changes look good?

**Review by tonistiigi — APPROVED** [review]

**Comment by aaronlehmann** [comment]
Thanks! Looks like CI failed but I don't think it's related. Can someone please retrigger it?

**Review by Sec32fun32 — APPROVED** [review]
