### PR TITLE
graphdriver/overlay2: usingMetacopy ENOTSUP is non-fatal

### LINKED ISSUE #44911: overlay2 usingMetacopy prevents daemon startup due to ENOTSUP on some filesystems
### Description

After upgrading to Docker v23.0.0 on kernel 6.1.4, the daemon fails to start with `dockerd -D` with the following error:

```
failed to start daemon: error initializing graphdriver: metacopy flag was not set on file in the upperdir: operation not supported
```

I've run check-config.sh to check the kernel config and everything is set properly. Furthermore the previous version of Docker worked fine on this machine.

containerd 1.6.16
runc 1.1.4
go 1.20
libseccomp 2.5.4

### Reproduce

1. Upgrade to Docker 23.0.0 and containerd 1.6.16
2. Run `dockerd -D`

### Expected behavior

_No response_

### docker version

```bash
Client:
 Version:           23.0.0
 API version:       1.42
 Go version:        go1.20
 Git commit:        23.0.0
 Built:             unknown-buildtime
 OS/Arch:           linux/arm
 Context:           default
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

### docker info

```bash
Unable to get because daemon won't start.
```

### Additional Info

Odroid XU4 on Arm with kernel 6.1.4.

### PR DESCRIPTION
**Pull request by neersighted**
- Closes https://github.com/moby/moby/issues/44911

**- What I did**
Change `usesMetacopy` in `overlay2`'s `check.go` to return false/no error on a `ENOTSUP` in lgetxattr(2).

**- How to verify it**
By reading kernel documentation, more or less. ENOTSUP does not indicate that something went wrong, but that either the xattr in question, or xattr as a whole, are not supported by the filesystem.

**- Description for the changelog**
- Fix the `overlay2` storage driver failing in a check for metacopy status instead of backing FS compatibility on incompatible backing filesystems.

**- A picture of a cute animal (not mandatory but encouraged)**
image

### CODE REVIEW

File: daemon/graphdriver/overlay2/check.go [hunk 1]
```diff
@@ -188,6 +188,11 @@ func usingMetacopy(d string) (bool, error) {
 	// ...and check if the pulled-up copy is marked as metadata-only
 	xattr, err := system.Lgetxattr(filepath.Join(l2, "f"), overlayutils.GetOverlayXattr("metacopy"))
 	if err != nil {
+		// ENOTSUP signifies the FS does not support either xattrs or metacopy. In either case,
+		// it is not a fatal error, and we should report metacopy as unused.
+		if errors.Is(err, unix.ENOTSUP) {
+			return false, nil
```
Comment (thaJeztah) [inline daemon/graphdriver/overlay2/check.go:194]: Do you think we need to log this? (I see we do some logging above)

Comment (neersighted) [reply daemon/graphdriver/overlay2/check.go:194]: I don't think so, because the point of this change is it's a "benign failure." Maybe it would be informative to say the check was "not supported" instead of "not used," but ultimately I think of this check as binary: either we're using metacopy, or we're not.

With that in mind, I conceptualize this as handling a way the OS reports "metacopy not in use" that I overlooked in my first iteration.

Comment (thaJeztah) [reply daemon/graphdriver/overlay2/check.go:194]: Yes, was mostly wondering if it would be informative to the user to learn why it's skipping, but I guess we could add in future.

Comment (neersighted) [reply daemon/graphdriver/overlay2/check.go:194]: I don't mind either way, with a slight bias towards not logging given my reasoning above.

**Comment by thaJeztah** [comment]
BuildKit CI failed 3 times in a row 😞 (no idea if related in any way though - haven't dug for the failure yet) https://github.com/moby/moby/actions/runs/4084011973/jobs/7044953937

**Review by cpuguy83 — APPROVED** [review]

**Review by thaJeztah — APPROVED** [review]
Ah! Green now

LGTM

**Comment by crazy-max** [comment]
> BuildKit CI failed 3 times in a row 😞 (no idea if related in any way though - haven't dug for the failure yet) https://github.com/moby/moby/actions/runs/4084011973/jobs/7044953937

Looks like the busybox image issue is back: https://github.com/moby/moby/actions/runs/4084011973/jobs/7044953937#step:9:5952

```
        	Error:      	Received unexpected error:
        	            	process "/bin/sh -c touch /out/bar && cat /dev/urandom | head -c 100 | sha256sum > /unique" did not complete successfully: exit code: 132
...
sandbox.go:263: Illegal instruction (core dumped)
```

Looking at https://github.com/moby/moby/blob/a0e8922d13de8ad5570f54cd863dd5c9bfade581/.github/workflows/buildkit.yml#L76 and https://github.com/tonistiigi/buildkit/commits/v0.11-cni-test-fix, it seems https://github.com/moby/buildkit/pull/3482 has not been backported to 0.11 branch.
