### PR TITLE
integration: Deduplicate TestStopContainerWithTimeout

### LINKED ISSUE #49206: Flaky test: TestStopContainerWithTimeout (integration/container)
### Description

- related: PR to update this test: https://github.com/moby/moby/pull/45365

Seen failing a few times;

```console
=== CONT  TestStopContainerWithTimeout/3
=== CONT  TestStopContainerWithTimeout/1
    stop_linux_test.go:70: assertion failed: 2 (inspect.State.ExitCode int) != 42 (tc.expectedExitCode int)
--- FAIL: TestStopContainerWithTimeout (0.02s)
    --- PASS: TestStopContainerWithTimeout/0 (0.48s)
    --- FAIL: TestStopContainerWithTimeout/-1 (0.51s)
    --- PASS: TestStopContainerWithTimeout/1 (1.45s)
    --- PASS: TestStopContainerWithTimeout/3 (2.31s)
```

### PR DESCRIPTION
**Pull request by vvoland**
- fixes: https://github.com/moby/moby/issues/49206

**- What I did**
Deduplicated almost identical separate implementations and combined them into one test.

Also, increase the the timeout and container run time to reduce flakiness.

**- How I did it**
See commit.

**- How to verify it**
```bash
make TEST_FILTER=TestStopContainerWithTimeout test-integration
```
or watch CI

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: integration/container/stop_windows_test.go [hunk 1]
```diff
@@ -1,68 +0,0 @@
...
-	"gotest.tools/v3/assert"
-	"gotest.tools/v3/poll"
-	"gotest.tools/v3/skip"
-)
-
-// TestStopContainerWithTimeout checks that ContainerStop with
-// a timeout works as documented, i.e. in case of negative timeout
-// waiting is not limited (issue #35311).
-func TestStopContainerWithTimeout(t *testing.T) {
-	skip.If(t, testEnv.OSType == "windows")
```
Comment (thaJeztah) [inline integration/container/stop_windows_test.go:20]: Oh.. hmm.. interesting, so it was in a `windows` test-file, but it's skipped if the daemon is windows 😅

File: integration/container/stop_windows_test.go [hunk 2]
```diff
@@ -1,68 +0,0 @@
...
-	testData := []struct {
-		doc              string
-		timeout          int
-		expectedExitCode int
-	}{
-		// In case container is forcefully killed, 137 is returned,
-		// otherwise the exit code from the above script
-		{
-			"zero timeout: expect forceful container kill",
-			1, 0x40010004,
```
Comment (thaJeztah) [inline integration/container/stop_windows_test.go:35]: Were these exit-codes different between Linux and Windows? (And is that what's causing the tests to fail?).


```
=== FAIL: github.com/docker/docker/integration/container TestStopContainerWithTimeout/zero_timeout:_expect_forceful_container_kill (5.20s)
    stop_test.go:106: assertion failed: 3221225786 (inspect.State.ExitCode int) != 1073807364 (tc.expectedExitCode int)

=== FAIL: github.com/docker/docker/integration/container TestStopContainerWithTimeout/unlimited_timeout:_expect_graceful_container_stop (6.11s)
    stop_test.go:106: assertion failed: 3221225786 (inspect.State.ExitCode int) != 0 (tc.expectedExitCode int)

=== FAIL: github.com/docker/docker/integration/container TestStopContainerWithTimeout/too_small_timeout:_expect_forceful_container_kill (5.15s)
    stop_test.go:106: assertion failed: 3221225786 (inspect.State.ExitCode int) != 1073807364 (tc.expectedExitCode int)

=== FAIL: github.com/docker/docker/integration/container TestStopContainerWithTimeout/big_enough_timeout:_expect_graceful_container_stop (6.27s)
    stop_test.go:106: assertion failed: 3221225786 (inspect.State.ExitCode int) != 0 (tc.expectedExitCode int)

=== FAIL: github.com/docker/docker/integration/container TestStopContainerWithTimeout (0.04s)

```

Comment (thaJeztah) [reply integration/container/stop_windows_test.go:35]: oh, but you created a special case for windows to set a different code. Hm.. no idea then 😂

Comment (vvoland) [reply integration/container/stop_windows_test.go:35]: The exict code is different that the expected code from the previous tests that weren't run. It's possible that the exitcode 3221225786 is the correct one here, but there's still the case of the non-zero exit code when the container was supposed to exit cleanly.
I didn't spend time investigating this deeper yet, because this was just something I encountered randomly and thought it would be a simple fix 😂 
I'll take a second look into it when I have some spare cycles, so keeping it as a draft.
But if anyone wants to pick this up, feel free to do so!

**Review by thaJeztah — APPROVED** [review]
LGTM
