### PR TITLE
Fix issue for `--hostname` when running in "--net=host"

### LINKED ISSUE #29129: "--hostname" not working when running in "--net=host"
Possibly I'm doing something wrong, but https://github.com/docker/docker/pull/20177 added support for changing the container's hostname when running in `--net=host`; according to that PR, the container gets its own UTS namespace, so changing the hostname only affects the container's hostname.

Testing that feature, however, it looks like the hostname is not set at all;

```bash
$ docker run --rm --net=host --hostname foobar alpine sh -c 'echo $HOSTNAME && hostname'
8af04ff88b77
8af04ff88b77
```

(`8af04ff88b77` is the hostname of the "host"; running docker-in-docker)

I tried to reproduce on 1.11.2, 1.12.3, and 1.13.0-rc2 to verify if there was a regression, but none of those versions worked. Trying on docker 1.10 correctly shows an error message (`docker: Error response from daemon: Conflicting options: hostname and the network mode.`), which is expected.

/cc @estesp @jheiss

### PR DESCRIPTION
**Pull request by yongtang**
**- What I did**

This fix tries to address the issue raised in #29129 where "--hostname" not working when running in "--net=host" for `docker run`.

**- How I did it**

The fix fixes the issue by not resetting the `container.Config.Hostname` if the `Hostname` has already been assigned through `--hostname`.

**- How to verify it**

An integration test has been added to cover the changes.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

cats-cute-christmas-cat-animal-hat-santa-kitten-cool-wallpapers-640x360

This fix fixes #29129.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks @yongtang! Gave this a test, and it looks to be fixing the issue :tada:

```
$ docker run --rm --net=host --hostname foobar alpine sh -c 'echo $HOSTNAME && hostname'
foobar
foobar

$  docker run --rm --net=host --hostname foobar --uts=host alpine sh -c 'echo $HOSTNAME && hostname'
docker: Error response from daemon: Conflicting options: hostname and the UTS mode.
See 'docker run --help'.
```

**Review by thaJeztah — DISMISSED** [review]
~~LGTM (if green)~~

**Comment by estesp** [comment]
Hmm..this change seems to affect the test **TestRunModeHostname**:
```
FAIL: docker_cli_run_test.go:1199: DockerSuite.TestRunModeHostname
 
 docker_cli_run_test.go:1216:
     c.Fatalf("expected %q, but says: %q", hostname, actual)
 ... Error: expected "0d096e0f1449", but says: "f53fc8a3c6f8"
```

**Comment by thaJeztah** [comment]
ahm, you're right

```
hostname
9c141091acea

docker run --rm --net=host alpine sh -c 'echo $HOSTNAME && hostname'
b1268a674e1d
b1268a674e1d
```

probably libnetwork sets `container.Config.Hostname`, so it'll be set, even if no `--hostname` is provided by the user

**Comment by yongtang** [comment]
Thanks @estesp @thaJeztah for the review. The reason for failed test was that, when container is created with `docker create` (before `docker start` for `docker run`), container is given a `Config.Hostname` no matter if it is in host mode or non-host mode:
https://github.com/docker/docker/blob/v1.13.0-rc2/daemon/container.go#L105-L112

I updated the PR. Now `Config.Hostname` is assigned with `os.Hostname()` in host mode.
*Alternatively, we could also leave Config.Hostname alone in host mode, if user does not provide a Hostname.* But that alternative approach might cause API compatibility issue so I choose to assign `Config.Hostname` with  `os.Hostname()`.

Please take a look and let me know if there are any issues.

File: daemon/create.go [hunk 1]
```diff
@@ -96,7 +96,7 @@ func (daemon *Daemon) create(params types.ContainerCreateConfig, managed bool) (
 		return nil, err
 	}
 
-	if container, err = daemon.newContainer(params.Name, params.Config, imgID, managed); err != nil {
+	if container, err = daemon.newContainer(params.Name, params.Config, params.HostConfig.NetworkMode.IsHost(), imgID, managed); err != nil {
```
Comment (thaJeztah) [inline daemon/create.go]: Should `params.HostConfig` be passed here, instead of a Boolean? Maybe @estesp has some thoughts on that as well, so don't change yet (just thinking out loud)

**Comment by yongtang** [comment]
Thanks @thaJeztah @estesp. The PR has been updated with `HostConfig` passed. Please take a look.

**Review by estesp — APPROVED** [review]
LGTM if green

**Review by thaJeztah — APPROVED** [review]
LGTM
