### PR TITLE
install dirmngr if needed

### LINKED ISSUE #30601: get.docker.com curl script needs to install dirmngr for yakkety
**Description**

When running the curl script from https://get.docker.com on ubuntu yakkety, install fails because it needs to run `dirmngr` which is now in a [separate package](https://bugs.launchpad.net/ubuntu/+source/apt/+bug/1634464).  Workaround is to manually install with `apt install dirmngr` before running curl script to have successful installation.

**Steps to reproduce the issue:**

I used a docker `ubuntu:yakkety` container to reproduce:

```
$ docker run --rm -it ubuntu:yakkety bash
Unable to find image 'ubuntu:yakkety' locally
yakkety: Pulling from library/ubuntu
...
Digest: sha256:609c1726180221d95a66ce3ed1e898f4a543c5be9ff3dbb1f10180a6cb2a6fdc
Status: Downloaded newer image for ubuntu:yakkety
root@ecb988d82176:/# apt update
Get:1 http://security.ubuntu.com/ubuntu yakkety-security InRelease [102 kB]
Get:2 http://archive.ubuntu.com/ubuntu yakkety InRelease [247 kB]
...
Reading state information... Done
10 packages can be upgraded. Run 'apt list --upgradable' to see them.
root@ecb988d82176:/# apt install curl
...
done.
root@ecb988d82176:/# curl -fsSL https://get.docker.com/ | sh
...
Executing: /tmp/tmp.unEwtRRoAY/gpg.1.sh --keyserver
hkp://keyserver.ubuntu.com:80
--recv-keys
58118E89F3A912897C070ADBF76221572C52609D
gpg: failed to start the dirmngr '/usr/bin/dirmngr': No such file or directory
gpg: connecting dirmngr at '/tmp/tmp.unEwtRRoAY/S.dirmngr' failed: No such file or directory
gpg: keyserver receive failed: No dirmngr
+ sh -c apt-key adv -k 58118E89F3A912897C070ADBF76221572C52609D >/dev/null
Warning: apt-key output should not be parsed (stdout is not a terminal)
gpg: error reading key: No public key
root@ecb988d82176:/# docker
bash: docker: command not found
```

**Describe the results you received:**

No bueno.

**Describe the results you expected:**

Docker goodness.

### PR DESCRIPTION
**Pull request by thaJeztah**
as of Ubuntu Yakkety, dirmngr is now in a separate
package (see https://bugs.launchpad.net/ubuntu/+source/apt/+bug/1634464)

this patch updates the install script to install
the dirmngr package if it's not installed.

fixes https://github.com/docker/docker/issues/30601

... I hope, because DigitalOcean was having issues, so I couldn't spin up a droplet to test :blush:

screen shot 2017-01-31 at 5 00 27 pm

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @andrewhsu @tianon PTAL

**Comment by andrewhsu** [comment]
LGTM

I've verified by using curl and stuff works:
```
root@40d38e9afdc8:/# curl -fsSL https://raw.githubusercontent.com/thaJeztah/docker/612dfba8fc21b91ea632111a387b90d88b9174e3/hack/install.sh | sh
```

**Comment by vieux** [comment]
LGTM

**Comment by tianon** [comment]
I think this needs to be tested on older Debian and Ubuntu releases too
(where dirmngr spent exist)

**Comment by thaJeztah** [comment]
@tianon I was doubting to either explicitly check for `yakkety` and install, or test if `dirmngr` exists; is there something else to test for (what's used on older versions instead of `dirmngr`?)

**Comment by thaJeztah** [comment]
Did a quick test on `jessie` and `ubuntu 14.04` and those seem to work (although they both seem to be installing `dirmngr` - not sure if that's a problem / if it hurts?)

Ubuntu 14.04;

```
Ign http://mirrors.digitalocean.com trusty/universe Translation-en_US
Fetched 6,342 kB in 6s (948 kB/s)
Reading package lists... Done
+ sh -c sleep 3; apt-get install -y -q dirmngr
Reading package lists...
Building dependency tree...
```

Jessie:

```
The following NEW packages will be installed:
  dirmngr
0 upgraded, 1 newly installed, 0 to remove and 3 not upgraded.
Need to get 192 kB of archives.
```

**Comment by tianon** [comment]
Oh, I suppose it did exist previously, it just wasn't used as the default implementation by GnuPG itself until GnuPG 2 (so effectively not until Debian Stretch+ and Ubuntu Yakkety+) -- so installing it on older suites is mostly harmless, and will likely just cause a new (unused) daemon to be running.  The alternative is to do detection of the GnuPG version and only install it when we're GnuPG 2.x+, which is very fiddly and fragile (see https://github.com/neurodebian/dockerfiles/blob/383ae2cf242d4737e813d42c402315c3a8cd4569/dockerfiles/sid/Dockerfile#L12-L17 for how we handled this over in the NeuroDebian `Dockerfile`s).

File: hack/install.sh [hunk 1]
```diff
@@ -467,6 +467,12 @@ do_install() {
 				( set -x; $sh_c 'sleep 3; apt-get install -y -q gnupg2 || apt-get install -y -q gnupg' )
 			fi
 
+			# dirmngr is a separate package in ubuntu yakkety; see https://bugs.launchpad.net/ubuntu/+source/apt/+bug/1634464
+			if [ ! -e /usr/bin/dirmngr ]; then
```
Comment (tianon) [inline hack/install.sh]: Oh, these tests should probably use `if ! command -v dirmngr > /dev/null; then` rather than an explicit file path (same for `gpg` above :disappointed:).

**Review by vdemeester — CHANGES_REQUESTED** [review]
@thaJeztah could you take care of @tianon's comment real quick ? 👼

**Review by tianon — APPROVED** [review]
:heart_eyes:

**Comment by thaJeztah** [comment]
@vdemeester @tianon updated; gonna give it a quick test, but if one of you could check as well, that'd be great

**Comment by thaJeztah** [comment]
tested on Yakkety, and that worked, so looks like this is all ready to go 👍 thanks @tianon !

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by LK4D4** [comment]
OMG, panic on janky

**Comment by thaJeztah** [comment]
Panic on Windows as well, weird stuff

**Comment by vieux** [comment]
@thaJeztah @LK4D4 I restarted both

**Comment by vieux** [comment]
I guess it was flacky
