### PR TITLE
Error out if file in container at volume path

### LINKED ISSUE #4393: VOLUME instruction prevents a container from starting
If you create a volume that is already a file in the image, ``docker build`` happily completes, but you cannot run it.

```
sven:~/src/docker/tmp$ more Dockerfile

FROM    busybox
ADD     Dockerfile /data
VOLUME  ["/data"]
sven:~/src/docker/tmp$ docker build -t test .
Uploading context  2.56 kB
Uploading context
Step 0 : FROM busybox
 ---> 769b9341d937
Step 1 : ADD Dockerfile /data
 ---> 8ac230d38b08
Step 2 : VOLUME ["/data"]
 ---> Running in d9b8056add13
 ---> abc3d9d282e6
Successfully built abc3d9d282e6
sven:~/src/docker/tmp$ docker run -t -i -name -run_test test bash
2014/03/01 08:27:08 Error: start: Cannot start container 7d8242dd731f8ff0cd89e4f2ac59e5c5eb786e4defc589a531cda116d8fa3a55: readdirent: not a directory
```

### PR DESCRIPTION
**Pull request by cpuguy83**
Fixes #4393

### CODE REVIEW

File: integration-cli/docker_cli_build_test.go [hunk 1]
```diff
@@ -4343,3 +4343,18 @@ func TestBuildFromOfficialNames(t *testing.T) {
...
+	buildCmd.Stdin = strings.NewReader(`
+	FROM busybox
+	RUN touch /foo
+	VOLUME /foo
+	`)
+
+	out, _, err := runCommandWithOutput(buildCmd)
+	if err == nil || !strings.Contains(out, "file exists") {
+		t.Fatalf("exected build to fail when file exists in container at requested volume path")
+	}
```
Comment (jfrazelle) [inline integration-cli/docker_cli_build_test.go]: we need a `logDone`

**Comment by jfrazelle** [comment]
small nit, otherwise LGTM

File: integration-cli/docker_cli_build_test.go (hunk 1 above)
Comment (cpuguy83) [inline integration-cli/docker_cli_build_test.go]: logDone done

File: integration-cli/docker_cli_build_test.go [hunk 2]
```diff
@@ -4591,3 +4591,20 @@ func TestBuildFromOfficialNames(t *testing.T) {
...
+	buildCmd := exec.Command(dockerBinary, "build", "-t", "docker-test-errcreatevolumewithfile", "-")
+	buildCmd.Stdin = strings.NewReader(`
+	FROM busybox
+	RUN touch /foo
+	VOLUME /foo
+	`)
+
+	out, _, err := runCommandWithOutput(buildCmd)
+	if err == nil || !strings.Contains(out, "file exists") {
+		t.Fatalf("exected build to fail when file exists in container at requested volume path")
```
Comment (endoze) [inline integration-cli/docker_cli_build_test.go]: Should this read `expected build to fail...` instead of `exected build to fail...`?

**Comment by LK4D4** [comment]
@cpuguy83 need rebase and testing with jenkins :)

File: daemon/volumes.go [hunk 3]
```diff
@@ -184,6 +184,12 @@ func (container *Container) parseVolumeMountConfig() (map[string]*Mount, error)
 			continue
 		}
 
+		if stat, err := os.Stat(filepath.Join(container.basefs, path)); err == nil {
```
Comment (tiborvass) [inline daemon/volumes.go]: @cpuguy83 should this be Lstat? What happens if what would become the volume path, is a symlink to a folder?Should it follow the symlink and then "merge" with the folder? Or should we error out because a symlink is just a file? In case we error out because we consider the symlink being a file, then we should add a test.

I think it makes sense to follow the symlink, but I'd like to hear others' opinion /cc @tianon @jfrazelle

Comment (jfrazelle) [inline daemon/volumes.go]: I would say we should do the same as existing. So I would agree with merge.

**Comment by tiborvass** [comment]
LGTM
