### PR TITLE
daemon/containerd: Extract `createOrReplaceImage`

### LINKED ISSUE #48591: c8d: image load is not atomic, and always overwrites image
### Description

This may be partially "by design" (but possibly worth a discussion). When loading an image from a tar, the loaded image unconditionally replaces existing image(s).

## 1. Failing to load image replaces existing image with empty index

The following example loads a multi-platform image from a tar (not all variants are present in the tar);

```bash
$ docker image load -i image.tar
Loaded image: alpine:latest

$ docker image ls --tree
IMAGE                   ID             DISK USAGE   CONTENT SIZE   USED
alpine:latest           beefdbd8a1da       20.6MB         11.1MB
├─ linux/s390x          2b5b26e09ca2       3.46MB         3.46MB
├─ linux/ppc64le        c7a6800e3dc5       3.57MB         3.57MB
├─ linux/arm64/v8       9cee2b382fe2       13.6MB         4.09MB
├─ linux/amd64          33735bd63cf8           0B             0B
├─ linux/arm/v6         50f635c8b04d           0B             0B
├─ linux/arm/v7         f2f82d424957           0B             0B
├─ linux/386            b3e87f642f5c           0B             0B
└─ linux/riscv64        80cde017a105           0B             0B
```

When trying to load a platform-variant from the tar that's not included, an error is produced, but the image is replaced regardless, so now resulting in an empty image reference;

```bash
$ docker image load -i image-multiple.tar --platform=linux/ppc64le
requested platform (linux/ppc64le) not found: not found

docker image ls --tree
IMAGE           ID             DISK USAGE   CONTENT SIZE   USED
alpine:latest   beefdbd8a1da           0B             0B
```

## 2. Loading different variant of the same manifest-index replaces existing variants

The following loads a single variant from a tar;

```bash
$ docker image load -i image-multiple.tar --platform=linux/amd64
Loaded image: alpine:latest

$ docker image ls --tree
IMAGE                   ID             DISK USAGE   CONTENT SIZE   USED
alpine:latest           beefdbd8a1da       12.1MB         3.63MB
├─ linux/amd64          33735bd63cf8       12.1MB         3.63MB
├─ linux/arm/v6         50f635c8b04d           0B             0B
├─ linux/arm/v7         f2f82d424957           0B             0B
├─ linux/arm64/v8       9cee2b382fe2           0B             0B
├─ linux/386            b3e87f642f5c           0B             0B
├─ linux/ppc64le        c7a6800e3dc5           0B             0B
├─ linux/riscv64        80cde017a105           0B             0B
└─ linux/s390x          2b5b26e09ca2           0B             0B
```

Loading a different variant from the same image _replaces_ the available variants of the multi-platform image with the newly imported variant;

```bash
$ docker image load -i image-multiple.tar --platform=linux/s390x
Loaded image: alpine:latest

$ docker image ls --tree
IMAGE                   ID             DISK USAGE   CONTENT SIZE   USED
alpine:latest           beefdbd8a1da       11.9MB         3.46MB
├─ linux/s390x          2b5b26e09ca2       11.9MB         3.46MB
├─ linux/amd64          33735bd63cf8           0B             0B
├─ linux/arm/v6         50f635c8b04d           0B             0B
├─ linux/arm/v7         f2f82d424957           0B             0B
├─ linux/arm64/v8       9cee2b382fe2           0B             0B
├─ linux/386            b3e87f642f5c           0B             0B
├─ linux/ppc64le        c7a6800e3dc5           0B             0B
└─ linux/riscv64        80cde017a105           0B             0B
```

:question: do we want to have an option to _append_ to the existing image, in situations where the root manifest-index is the same?

### PR DESCRIPTION
**Pull request by vvoland**
- fixes: https://github.com/moby/moby/issues/48591
- addresses: (`build` and `imports`, but not `load`); https://github.com/moby/moby/issues/48907

**- What I did**

Extract a method that creates an image if it doesn't exists and replaces it otherwise. Use it in other places which also tried to do the same thing.

**- How to verify it**
Tests should pass

```markdown changelog
containerd image store: Fix `commit`, `import` and `build` not preserving replaced image as a dangling.
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: daemon/containerd/image_tag.go [hunk 1]
```diff
@@ -42,8 +50,8 @@ func (i *ImageService) TagImage(ctx context.Context, imageID image.ID, newTag re
 
 		// Check if image we would replace already resolves to the same target.
 		// No need to do anything.
-		if replacedImg.Target.Digest == targetImage.Target.Digest {
-			i.LogImageEvent(imageID.String(), reference.FamiliarString(newTag), events.ActionTag)
+		if replacedImg.Target.Digest == newImg.Target.Digest {
+			i.LogImageEvent(newImg.Name, imageFamiliarName(newImg), events.ActionTag)
```
Comment (thaJeztah) [inline daemon/containerd/image_tag.go:54]: This is changing `id` to `name`, correct? Mostly considering here that name could be easier to read, but `ID` may work also in case where there's no name associated. I recall we had some similar discussion around "network" events (I think) at some point, where we could not add a name to all of the related events, which made it more difficult to correlate events.

Comment (vvoland) [reply daemon/containerd/image_tag.go]: Ah yes, good catch, this should be the ID

File: daemon/containerd/image_builder.go [hunk 2]
```diff
@@ -524,18 +524,11 @@ func (i *ImageService) createImageOCI(ctx context.Context, imgToCreate imagespec
 		img.Labels[imageLabelClassicBuilderFromScratch] = "1"
 	}
 
-	createdImage, err := i.images.Update(ctx, img)
```
[the remark this answers is not in the document]
Comment (vvoland) [reply daemon/containerd/image_builder.go:527]: This was calling `Update` specifically to handle the case where the image already exists - if update fails due to non found error, it would do the `Create` instead.

The new function handles the case a bit differently - instead of just updating the image, it will first remove it if it exists (or rename to a dangling reference if it's the last tag to that image).

File: daemon/containerd/image_tag.go [hunk 3]
```diff
@@ -42,8 +56,10 @@ func (i *ImageService) TagImage(ctx context.Context, imageID image.ID, newTag re
 
 		// Check if image we would replace already resolves to the same target.
 		// No need to do anything.
-		if replacedImg.Target.Digest == targetImage.Target.Digest {
-			i.LogImageEvent(imageID.String(), reference.FamiliarString(newTag), events.ActionTag)
+		if replacedImg.Target.Digest == newImg.Target.Digest {
+			if !creatingDangling {
+				i.LogImageEvent(replacedImg.Target.Digest.String(), imageFamiliarName(newImg), events.ActionTag)
```
Comment (thaJeztah) [inline daemon/containerd/image_tag.go:61]: Note to self; this one  will conflict with a PR I had pending (I need to update that one, but it's less important  than this PR);

- https://github.com/moby/moby/pull/49014

File: daemon/containerd/image_import.go [hunk 4]
```diff
@@ -145,8 +145,7 @@ func (i *ImageService) ImportImage(ctx context.Context, ref reference.Named, pla
 		img.Name = danglingImageName(manifestDesc.Digest)
 	}
 
-	err = i.saveImage(ctx, img)
-	if err != nil {
+	if err = i.createOrReplaceImage(ctx, img); err != nil {
```
[the remark this answers is not in the document]
Comment (thaJeztah) [reply daemon/containerd/image_import.go:148]: Discussed briefly on slack, and let's keep it as-is for now.

**Review by thaJeztah — APPROVED** [review]
LGTM

@laurazard ptal 🤗

**Comment by thompson-shaun** [comment]
Can we close https://github.com/moby/moby/issues/48591 since this got in? @thaJeztah @vvoland

**Comment by vvoland** [comment]
No, this one didn't fix `load`.
