### PR TITLE
Fixed relative filepath check

### LINKED ISSUE #10815: Build context and vim backup files (..gitignore.un~)
Hi,

I've noticed a regression with Docker 1.5.0 (*did not notice this issue with Docker <=1.3*).

Error is as follows:

```#!bash
Sending build context to Docker daemon 81.94 MB
Sending build context to Docker daemon 
FATA[0000] Error: Untar exit status 1 "..gitignore.un~" is outside of "/" 
```

Script to reproduce issue:

```#!bash
#!/bin/bash

# Simulate a vim backup file
touch "..gitignore.um~"

cat - > Dockerfile <<EOF
FROM scratch
EOF

docker build -t test .
```

Running this script yields:

```#!bash
$ ./test.sh 
Sending build context to Docker daemon 3.584 kB
Sending build context to Docker daemon 
FATA[0000] Error: Untar exit status 1 "..gitignore.um~" is outside of "/" 
```

Work around is to remote any vim backup files by doing:

```#!bash
find . -type f -name "*~" -delete
```

### PR DESCRIPTION
**Pull request by jsdir**
This fixes the false error for certain filenames described in #10815

Closes #10815

### CODE REVIEW

**Comment by duglin** [comment]
Please add a testcase for this.

**Comment by duglin** [comment]
Also, add:
```
Closes #10815
```
to the first comment so github will close the original issue

File: integration-cli/docker_cli_build_test.go [hunk 1]
```diff
@@ -4284,7 +4284,7 @@ func TestBuildExoticShellInterpolation(t *testing.T) {
 
 	_, err := buildImage(name, `
 		FROM busybox
-
```
Comment (ahmetalpbalkan) [inline integration-cli/docker_cli_build_test.go]: this hunk seems unnecessary?

Comment (jsdir) [inline integration-cli/docker_cli_build_test.go]: Pardon my emacs. I fixed it.

**Comment by ahmetalpbalkan** [comment]
@jsdir can you please squash you commits into one and git push -f to your branch? This makes it easy to revert or integrate the commit atomically.

**Comment by jfrazelle** [comment]
@duglin @ahmetalpbalkan looks like this was updated

reviewing now

**Comment by jfrazelle** [comment]
LGTM

File: pkg/archive/archive.go [hunk 2]
```diff
@@ -525,7 +525,7 @@ loop:
 		if err != nil {
 			return err
 		}
-		if strings.HasPrefix(rel, "..") {
+		if strings.HasPrefix(rel, "../") {
```
Comment (ahmetalpbalkan) [inline pkg/archive/archive.go]: is this guy assuming it's running on Unix?

Comment (duglin) [inline pkg/archive/archive.go]: hmm I wonder if it should have used file instead of filepath.

Comment (tiborvass) [inline pkg/archive/archive.go]: @duglin is there an open PR to fix this?

Comment (ahmetalpbalkan) [inline pkg/archive/archive.go]: @tiborvass I guess not. Since it's unpack, it's daemon-side. We won't hit this yet on windows CI. but as @duglin said, it should use os.PathSeparator.

Comment (tiborvass) [inline pkg/archive/archive.go]: @ahmetalpbalkan I'll open a `white-label` issue for making sure paths use filepath :)

Comment (ahmetalpbalkan) [inline pkg/archive/archive.go]: thanks.
