### PR TITLE
ipams: Re-enable legacy remote plugins support

### LINKED ISSUE #50596: IPAM plugin loading is broken in Windows starting from Docker 27.0.1
### Description

I noticed as part of my [IPAM plugin for Docker with Nomad integration](https://github.com/olljanat/nomad-simplified/tree/main/ipam-plugin) testing that plugin is not correctly loaded anymore.

Seems to be happening in all versions, including latest code in master branch starting from 27.0.1 (didn't found 27.0.0 binaries). 26.1.4 and older versions works fine.

### Reproduce

1. Build plugin `go build`
2. Run plugin `.\ipam-plugin.exe`
3. Try create network:
```powershell
docker network create `
  --driver nat `
  --ipam-driver nomad-ipam `
  --subnet 10.0.0.0/16 `
  --gateway 10.0.0.1 `
  containers
```

Engine debug log contains message `nomad-ipam implements: IpamDriver` but still this logic returns error message:
https://github.com/moby/moby/blob/8c5c253b50c2f3c24a2b810c7fb7c9a6513659dd/daemon/libnetwork/controller.go#L1125-L1129

### Expected behavior

_No response_

### docker version

```bash
-
```

### docker info

```bash
-
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by olljanat**
**- What I did**
https://github.com/moby/moby/commit/3c9718144f22557e7448c70d22129e4602d0984d which was part of big refactoring PR https://github.com/moby/moby/pull/47727 disabled remote IPAM plugins loading in case of plugin getter is nil.

However, in Windows that is always the case so this logic needs to be revisitted.

Closes #50596

**- How I did it**
Removed plugin getter is nil check competely. However, it can be also done just for Windows in case it causes issues like this.

**- How to verify it**
Windows side tested like it is described in linked issue so if CI passes this should be fine.

**- Human readable description for the release notes**

```markdown changelog
- Fix a bug causing IPAM plugins to not be loaded on Windows
```

### CODE REVIEW

File: daemon/libnetwork/ipams/drivers.go [hunk 1]
```diff
@@ -22,10 +22,8 @@ func Register(r ipamapi.Registerer, pg plugingetter.PluginGetter, lAddrPools, gA
 	if err := null.Register(r); err != nil {
 		return err
 	}
-	if pg != nil {
-		if err := remoteIpam.Register(r, pg); err != nil {
-			return err
-		}
+	if err := remoteIpam.Register(r, pg); err != nil {
```
Comment (akerouanton) [inline daemon/libnetwork/ipams/drivers.go:25]: If I get it correctly, pg is nil on Windows because it doesn't support 'managed' plugins, right? Would you mind adding a comment telling that, so we don't reintroduce this issue?

Comment (olljanat) [reply daemon/libnetwork/ipams/drivers.go:25]: @akerouanton Yes, managed plugins are not implemented for Windows at the moment. Comment added.

**Review by akerouanton — APPROVED** [review]

**Review by robmry — APPROVED** [review]
LGTM - thank you.

(Will merge it when the tests finish.)

**Comment by robmry** [comment]
This one flaked again, but it's unrelated ...

```
=== FAIL: amd64.docker.docker.integration.networking TestBridgeICC/IPv6_link-local_address_on_internal_network (4.57s)
    firewall.go:69: Firewalld reload completed at 2025-09-19T13:57:54Z
    bridge_linux_test.go:219: assertion failed: 1 (res.ExitCode int) != 0 (int)
    bridge_linux_test.go:221: assertion failed: string "PING fe80::2%eth0 (fe80::2): 56 data bytes\n\n--- fe80::2%eth0 ping statistics ---\n1 packets transmitted, 0 packets received, 100% packet loss\n" does not contain "1 packets transmitted, 1 packets received"
    --- FAIL: TestBridgeICC/IPv6_link-local_address_on_internal_network (4.57s)
```

**Comment by vvoland** [comment]
@robmry  @akerouanton  @olljanat  should this one have a changelog entry?

**Comment by thaJeztah** [comment]
Oh! I should mention that I marked this for backporting because it was a regression (at least, from what I understood from the conversation above) and it looked like a small enough change to include.
