### PR TITLE
apparmor: allow receiving of signals from 'docker kill'

### LINKED ISSUE #36809: Failing to stop containers, if apparmor enabled.
**Description**
We tested docker-ce 17.12.1 and docker-ce 18.03.0 with apparmor enabled, and docker fails to stop the actual containers.

**Steps to reproduce the issue:**
1. docker run gcr.io/google_containers/pause-amd64:3.0
2. docker stop $container_id_of_step1

**Describe the results you received:**
```sh
docker stop $containerid
Error response from daemon: cannot stop container: $containerid: Cannot kill container $containerid: unknown error after kill: docker-runc did not terminate sucessfully: container_linux.go:393: signaling init process caused "permission denied"
: unknown
```

dmesg output
`[  551.981297] audit: type=1400 audit(1523033503.323:9): apparmor="DENIED" operation="signal" profile="docker-default" pid=7162 comm="docker-runc" requested_mask="receive" denied_mask="receive" signal=stp peer="unconfined"`

**Describe the results you expected:**
container should have been stopped

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
docker version
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.10.1
 Git commit:    0520e24
 Built: Fri Apr  6 16:37:32 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.1
  Git commit:   0520e24
  Built:        Fri Apr  6 16:35:44 2018
  OS/Arch:      linux/amd64
  Experimental: true
```

**Output of `docker info`:**

```
docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd0439 (expected: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c)
runc version: 4fc53a8 (expected: 4fc53a81fb7c994640722ac585fa9ca548971871)
init version: v0.17.0 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.14.32-grsecurity-r1-docker-2
Operating System: Gentoo/Linux
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.841GiB
Name: zip
ID: zip
Docker Root Dir: zip
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### PR DESCRIPTION
**Pull request by cyphar**
In newer kernels, AppArmor will reject attempts to send signals to a
container because the signal originated from outside of that AppArmor
profile. Correct this by allowing all unconfined signals to be received.

Carry #36822
Fixes #36809
Signed-off-by: Goldwyn Rodrigues <rgoldwyn@suse.com>
Signed-off-by: Aleksa Sarai <asarai@suse.de>

### CODE REVIEW

**Comment by vdemeester** [comment]
cc @AkihiroSuda @jessfraz

**Comment by ericchiang** [comment]
I tested this on my affected machine by replacing the docker-default profile with the one suggested here: https://github.com/moby/moby/issues/36809#issuecomment-4204743

It appears to have worked, and the docker daemon can now stop containers.

File: profiles/apparmor/template.go [hunk 1]
```diff
@@ -17,6 +17,12 @@ profile {{.Name}} flags=(attach_disconnected,mediate_deleted) {
   capability,
   file,
   umount,
+{{if ge .Version 208096}}
+{{/* Allow 'docker kill' to actually send signals to container processes. */}}
+  signal (receive) peer=unconfined,
```
Comment (ericchiang) [inline profiles/apparmor/template.go]: Just to note, this is the first time that the daemon assumes it runs as "unconfined". I don't run it as that profile, so I had to tweak it.

Since this is dynamically generated, maybe we could replace this with:

```
signal (receive) peer={{.DaemonProfile}}
```

Then fill that value in with whatever's in `/proc/self/attr/current`

**Comment by jessfraz** [comment]
We need to be careful here because the "peer" keyword is only supported on certain versions iirc

File: profiles/apparmor/template.go (hunk 1 above)
Comment (jessfraz) [reply profiles/apparmor/template.go]: There is a self keyword or something I think

Comment (cyphar) [reply profiles/apparmor/template.go]: I will take a look into whether there's a self keyword or if we'd need to actually read `attr/current`. I completely forgot that we have a daemon profile.

**Comment by ericchiang** [comment]
I've built and tested this. It works when the docker deamon runs as a profile other than unconstrained.

Before:

```
$ sudo docker run -d alpine:latest sleep 600
58a1e1b23e17a740c1a7a0f6d7b8e0fa8337fcab59ae7c949f69ba134eda320e
$ sudo docker kill 58a1e1b23e17a740c1a7a0f6d7b8e0fa8337fcab59ae7c949f69ba134eda320e
Error response from daemon: Cannot kill container: 58a1e1b23e17a740c1a7a0f6d7b8e0fa8337fcab59ae7c949f69ba134eda320e: Cannot kill container 58a1e1b23e17a740c1a7a0f6d7b8e0fa8337fcab59ae7c949f69ba134eda320e: unknown error after kill: docker-runc did not terminate sucessfully: container_linux.go:393: signaling init process caused "permission denied"
: unknown
```

After:

```
$ sudo docker run -d alpine:latest sleep 600                                                                                                                                                                       
798a35422d6d92855e4d561e7ac9498a26858f2664160f671161ad4794b6bbc8                                                                                                                                                                            
$ sudo docker kill 798a35422d6d92855e4d561e7ac9498a26858f2664160f671161ad4794b6bbc8                                                                                                                                    
798a35422d6d92855e4d561e7ac9498a26858f2664160f671161ad4794b6bbc8
```

File: profiles/apparmor/template.go (hunk 1 above)
Comment (jessfraz) [reply profiles/apparmor/template.go]: ah yeah omg that daemon profile is bad but regardless... lgtm :)

**Review by mrueg — APPROVED** [review]
Has fixed the in-container signaling issues I saw.

**Comment by thaJeztah** [comment]
@cyphar sorry for the delay; in the original PR you mentioned that the kernel patch that cause this issue was reverted;

> I have since discovered that the corresponding kernel patch that required this change was actually reverted in the upstream kernel. We still have it in the SUSE kernels, so this is still a problem for us, but we can drop this from being merged in upstream Docker (unless the kernel change gets re-merged upstream). However the reason it was reverted is because it broke userspace -- so in theory if it ever gets merged we still won't need to modify the default profile.

Did that change?

**Comment by thaJeztah** [comment]
Also ping @justincormack PTAL

**Comment by cyphar** [comment]
So I just checked the commit history and it looks like the code was never reverted torvalds/linux@cd1dbf76b23d5ab2cba5e657fe20b1e236a408cc has been in all kernel versions since `4.14` and there is no revert commit (and `git blame` shows that commit as the genesis of the current `aa_may_signal` code). I don't remember who told me it was reverted, but that's clearly not true.

**However** the kernel code currently has a check that should avoid userspace breakage (which is what this patch is attempting to fix):

```
static int profile_signal_perm(struct aa_profile *profile,
			       struct aa_label *peer, u32 request,
			       struct common_audit_data *sa)
{
	/* ... */
	if (profile_unconfined(profile) ||
	    !PROFILE_MEDIATES(profile, AA_CLASS_SIGNAL))
		return 0;
	/* ... */
}
```

Which effectively means that if a profile contains *no* `signal` entries then there are no restrictions on signals. But if a profile contains any `signal` entries then we have to apply this patch so that signals within the same profile and signals from an unconfined profile are allowed.

So why are people seeing this? I think it's because of `abstractions/base`. Some distributions have entries like the following:

```
  # Allow unconfined processes to send us signals by default
  signal (receive) peer=unconfined,

  # Allow us to signal ourselves
  signal peer=@{profile_name},

  # Checking for PID existence is quite common so add it by default for now
  signal (receive, send) set=("exists"),
```

Which will be applied by default in Docker -- so I think it depends strongly on how your distribution is configured whether or not you will hit an issue. If you have `signal` entries but not these ones, then you'll be in trouble. **But** we still should include an entry for `DaemonProfile` because the above doesn't handle that properly...

**Comment by thaJeztah** [comment]
ping @kolyshkin @justincormack PTAL

**Review by justincormack — APPROVED** [review]

**Review by thaJeztah — APPROVED** [review]
LGTM

sorry for the delay, wanted to have a look from @justincormack before going ahead 🤗
