### PR TITLE
api: fix "GET /distribution" endpoint ignoring mirrors

### LINKED ISSUE #47012: Bug in `/distribution/{name}/json` API when Docker engine is configured with registry-mirrors
### Description

The `/distribution/{name}/json` API does not appear to behave properly when Docker engine is configured with registry-mirrors (e.g., `"registry-mirrors": ["http://localhost:5000/"]` in the daemon.json file).

For example, without the `registry-mirrors` config, the following commands work as expected:

```
$ curl -s --unix-socket /var/run/docker.sock http://localhost/v1.43/distribution/docker:latest/json
$ curl -s --unix-socket /var/run/docker.sock http://localhost/v1.43/distribution/docker.io/library/docker:latest/json
$ curl -s --unix-socket /var/run/docker.sock http://localhost/v1.43/distribution/localhost:5000/docker:latest/json
```

(In order for the last command to work, I am running a registry locally using `docker run -d -p 5000:5000 --restart always --name registry registry:2`). 

However, if I add `"registry-mirrors": ["http://localhost:5000/"]` in the `/etc/docker/daemon.json` file, then the first two commands above fail with `manifest unknown` error:

```
$ curl -s --unix-socket /var/run/docker.sock http://localhost/v1.43/distribution/docker.io/library/docker:latest/json
{"message":"manifest unknown: manifest unknown"}

$ curl -s --unix-socket /var/run/docker.sock http://localhost/v1.43/distribution/docker:latest/json
{"message":"manifest unknown: manifest unknown"}
```

This seems incorrect; the commands should have pulled the manifest from `docker.io/library/docker`. 

Only the last command above works in this case:

```
$ curl -s --unix-socket /var/run/docker.sock http://localhost/v1.43/distribution/localhost:5000/docker:latest/json                                                                                                                                                                             
{"Descriptor":{"mediaType":"application/vnd.docker.distribution.manifest.v2+json","digest":"sha256:c5d0ff82239623512a162b011c263ce905f6f3b57a651c8c737ff1aeb7da2450","size":3460},"Platforms":[{"architecture":"amd64","os":"linux"}]}   
```

In short, it seems that the `/distribution/{name}/json` API is restricted to only pulling manifests from the registry mirror whenever Docker engine is configured with `"registry-mirrors": ["http://localhost:5000/"]`, and this does not seem correct.

### Reproduce

1. Add the following in `/etc/docker/daemon.json`, then restart Docker engine:
```
{
  "registry-mirrors": ["http://localhost:5000"]
}
```

2. Query the docker engine's `distribution` API to get the manifest for a well-known docker image: 

```
$ curl -s --unix-socket /var/run/docker.sock http://localhost/v1.43/distribution/docker:latest/json
{"message":"manifest unknown: manifest unknown"}
```

Step 2 should have worked and pulled the manifest from `docker.io/library/docker`. 

### Expected behavior

The docker engine's `distribution` API should be able to pull manifests from the default registry (e.g., `docker.io`) even if docker engine is configured with `"registry-mirrors": ["http://localhost:5000/"]`.

### docker version

```bash
$ docker version
Client: Docker Engine - Community
 Cloud integration: v1.0.35+desktop.6
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:31:44 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:44 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
$ docker info
Client: Docker Engine - Community
 Version:    24.0.6  
 Context:    default
 Debug Mode: false          
 Plugins:              
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.5
    Path:     /home/cesar/.pinata/downloads/docker-plugins/v0.11.2-desktop.5/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.3-desktop.2
    Path:     /usr/lib/docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /usr/lib/docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     /usr/lib/docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /usr/lib/docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.10
    Path:     /usr/lib/docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/lib/docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /usr/lib/docker/cli-plugins/docker-scan
  scout: Docker Scout (Docker Inc.)
    Version:  v1.2.0
    Path:     /usr/lib/docker/cli-plugins/docker-scout
Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 61
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc sysbox-runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.2.0-37-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.06GiB
 Name: lenovo
 ID: 17fb94ad-ce0e-40b5-bbf1-814499d8e30c
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 172.25.0.0/16, Size: 24

```
```


### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by thaJeztah**
- fixes https://github.com/moby/moby/issues/47012

If the daemon is configured to use a mirror for the default (Docker Hub) registry, the endpoint did not fall back to querying the upstream if the mirror did not contain the given reference.

If the daemon is configured to use a mirror for the default (Docker Hub) registry, did not fall back to querying the upstream if the mirror did not contain the given reference.

For pull-through registry-mirrors, this was not a problem, as in that case the registry would forward the request, but for other mirrors, no fallback would happen. This was inconsistent with how "pulling" images handled this situation; when pulling images, both the mirror and upstream would be tried.

This problem was caused by the logic used in GetRepository, which had an optimization to only return the first registry it was successfully able to configure (and connect to), with the assumption that the mirror either contained all images used, or to be configured as a pull-through mirror.

This patch:

- Introduces a GetRepositories method, which returns all candidates (both mirror(s) and upstream).
- Updates the endpoint to try all

Before this patch:

    # the daemon is configured to use a mirror for Docker Hub
    cat /etc/docker/daemon.json
    { "registry-mirrors": ["http://localhost:5000"]}

    # start the mirror (empty registry, not configured as pull-through mirror)
    docker run -d --name registry -p 127.0.0.1:5000:5000 registry:2

    # querying the endpoint fails, because the image-manifest is not found in the mirror:
    curl -s --unix-socket /var/run/docker.sock http://localhost/v1.43/distribution/docker.io/library/hello-world:latest/json
    {
      "message": "manifest unknown: manifest unknown"
    }

With this patch applied:

    # the daemon is configured to use a mirror for Docker Hub
    cat /etc/docker/daemon.json
    { "registry-mirrors": ["http://localhost:5000"]}

    # start the mirror (empty registry, not configured as pull-through mirror)
    docker run -d --name registry -p 127.0.0.1:5000:5000 registry:2

    # querying the endpoint succeeds (manifest is fetched from the upstream Docker Hub registry):
    curl -s --unix-socket /var/run/docker.sock http://localhost/v1.43/distribution/docker.io/library/hello-world:latest/json | jq .
    {
      "Descriptor": {
        "mediaType": "application/vnd.oci.image.index.v1+json",
        "digest": "sha256:1b9844d846ce3a6a6af7013e999a373112c3c0450aca49e155ae444526a2c45e",
        "size": 3849
      },
      "Platforms": [
        {
          "architecture": "amd64",
          "os": "linux"
        }
      ]
    }

**- Description for the changelog**

```
Fix "GET /distribution" endpoint ignoring mirrors when resolving image manifests.
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: api/server/router/distribution/distribution_routes.go [hunk 1]
```diff
@@ -42,24 +43,50 @@ func (s *distributionRouter) getDistributionInfo(ctx context.Context, w http.Res
...
+	// GetRepositories() will attempt to connect to all endpoints (registries),
+	// but we may only need the first one if it contains the manifest we're
+	// looking for, or if the configured mirror is a pull-through mirror.
+	//
+	// Logic for this could be implemented similar to "distribution.Pull()",
+	// which uses the "pullEndpoints" utility to iterate over the list
+	// of endpoints;
+	//
+	// - https://github.com/moby/moby/blob/12c7411b6b7314bef130cd59f1c7384a7db06d0b/distribution/pull.go#L17-L31
+	// - https://github.com/moby/moby/blob/12c7411b6b7314bef130cd59f1c7384a7db06d0b/distribution/pull.go#L76-L152
```
Comment (thaJeztah) [inline api/server/router/distribution/distribution_routes.go:64]: We should consider moving all this logic, except for the conversion to `registry.DistributionInspect` to the distribution package, so that iterating over endpoints can be handled there. I'm leaving that for a follow-up refactor of this code.

File: distribution/repository.go [hunk 2]
```diff
@@ -24,11 +44,23 @@ func GetRepository(ctx context.Context, ref reference.Named, config *ImagePullCo
...
+		lastError    error
+	)
 	for _, endpoint := range endpoints {
-		repository, lastError = newRepository(ctx, repoInfo, endpoint, nil, config.AuthConfig, "pull")
-		if lastError == nil {
-			break
+		repo, err := newRepository(ctx, repoInfo, endpoint, nil, config.AuthConfig, "pull")
+		if err != nil {
+			log.G(ctx).WithFields(log.Fields{"endpoint": endpoint.URL.String(), "error": err}).Info("endpoint")
+			lastError = err
```
Comment (rumpl) [inline distribution/repository.go:55]: Don't we need a `continue` here?

File: daemon/daemon.go [hunk 3]
```diff
@@ -1595,3 +1595,19 @@ func (i *imageBackend) GetRepository(ctx context.Context, ref reference.Named, a
...
 }
+
+// GetRepositories returns a list of repositories configured for the given
+// reference. Multiple repositories can be returned if the reference is for
+// the default (Docker Hub) registry and a mirror is configured, but it omits
+// registries that were not reachable (pinging the /v2/ endpoint failed).
+//
+// It returns an error if it was unable to reach any of the registries for
+// the given reference, or if the provided reference is invalid.
+func (i *imageBackend) GetRepositories(ctx context.Context, ref reference.Named, authConfig *registrytypes.AuthConfig) ([]dist.Repository, error) {
```
Comment (rumpl) [inline daemon/daemon.go:1606]: Just so I understand, this one isn't used anywhere right? I'm not sure what the executor.ImageBackend interface is used for

File: distribution/repository.go (hunk 2 above)
Comment (thaJeztah) [reply distribution/repository.go:55]: Oh! Good catch; looks like I dropped that one here; I originally had it reversed (`err == nil`)

File: daemon/daemon.go (hunk 3 above)
Comment (thaJeztah) [reply daemon/daemon.go:1606]: This one is used in the router (as `backend.GetRepositories()`).

The `executor.ImageBackend` interface is used for swarm services. I have a follow-up to update that one to use this as well (instead of the `GetRepository()` (singular), but it's only used for fallback cases on old < 1.30 API versions. That made it less urgent (if we want to fix it at all!) so I decided to keep that commit separate.

I'll push a draft PR with that follow-up.

File: distribution/repository.go (hunk 2 above)
Comment (thaJeztah) [reply distribution/repository.go:55]: Should be fixed now 👍

File: daemon/daemon.go (hunk 3 above)
Comment (thaJeztah) [reply daemon/daemon.go:1606]: Pushed the follow-up as draft;

- https://github.com/moby/moby/pull/47024

**Review by rumpl — APPROVED** [review]
LGTM!

**Comment by thaJeztah** [comment]
I added cherry-pick labels for consideration in LTS branch(es), but we can hold-off for a bit doing so; see https://github.com/moby/moby/pull/47024#issuecomment-1878502788

> I'll add cherry-pick labels if we consider backporting this fix (and https://github.com/moby/moby/pull/47023) to LTS branches, but we can hold-off doing so (consider the labels a "reminder" so that we don't forget).
