### PR TITLE
c8d: Fix building Dockerfiles that have `FROM scratch`

### LINKED ISSUE #46248: containerd-integration: classic builder fails when building `FROM scratch`
### Description

As reported in https://github.com/docker/for-mac/issues/6853#issuecomment-1680977603

> The above suggests this is resolved, but I've updated to the latest version (4.21.1) and it still fails when building the example here with the containerd beta enabled.
> The error has now changed though, so the above repro now prints:
>
> ```bash
> > DOCKER_BUILDKIT=0 docker build .
> DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
>             BuildKit is currently disabled; enable it by removing the DOCKER_BUILDKIT=0
>             environment-variable.
>
> Sending build context to Docker daemon  2.048kB
> Step 1/2 : FROM scratch
>  --->
> Step 2/2 : ENTRYPOINT ["fail"]
> invalid reference format
> ```
>
> That's as opposed to the `Error response from daemon: Bad response from Docker engine` message printed previously, as above.
>
> The exact same build works fine with the containerd beta disabled.
>
> Any ideas?

I suspect there's an issue with special-casing `scratch`. I suspect it's trying to look up `scratch` as an actual image, and probably failing because of that.

Here's witch `FROM scratch`;

```bash
echo -e 'FROM scratch\nENTRYPOINT ["fail"]' | DOCKER_BUILDKIT=0 docker build -
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM scratch
 --->
Step 2/2 : ENTRYPOINT ["fail"]
invalid reference format
```

And here's `FROM alpine` (or any other image);

```bash
echo -e 'FROM alpine\nENTRYPOINT ["fail"]' | DOCKER_BUILDKIT=0 docker build -
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM alpine
7144f7bab3d4: Already exists
b312e4b0e2c6: Download complete
f6648c04cd6c: Download complete
 ---> 7144f7bab3d4
Step 2/2 : ENTRYPOINT ["fail"]
 ---> Running in d40d15a0a60c
Removing intermediate container d40d15a0a60c
 ---> b185bc886f29
Successfully built b185bc886f29
```

### PR DESCRIPTION
**Pull request by vvoland**
- Fixes: https://github.com/moby/moby/issues/46248
- addresses https://github.com/docker/for-mac/issues/6853#issuecomment-1680977603

**- What I did**
Fix running containers with empty `Image`.

**- How I did it**
See commits.

**- How to verify it**
c8d integration tests (https://github.com/moby/moby/pull/45232) from `TestDockerCLIBuildSuite`:
```diff
- DONE 250 tests, 13 skipped, 58 failures in 352.552s
+ DONE 250 tests, 13 skipped, 42 failures in 406.027s
```

**Before**
```bash
$ printf 'FROM scratch\nLABEL asdf=1' | DOCKER_BUILDKIT=0 docker build -t asdf -
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            BuildKit is currently disabled; enable it by removing the DOCKER_BUILDKIT=0
            environment-variable.

Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM scratch
 --->
Step 2/2 : LABEL asdf=1
invalid reference format
```

**After**
```bash
$ printf 'FROM scratch\nLABEL asdf=1' | DOCKER_BUILDKIT=0 docker build -t asdf -
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            BuildKit is currently disabled; enable it by removing the DOCKER_BUILDKIT=0
            environment-variable.

Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM scratch
 --->
Step 2/2 : LABEL asdf=1
 ---> Running in 08bc1d65adb1
 ---> Removed intermediate container 08bc1d65adb1
 ---> 7072ecaf239f
Successfully built 7072ecaf239f
Successfully tagged asdf:latest
```

**- Description for the changelog**
```release-notes
containerd integration: Fix building Dockerfiles with `FROM scratch` instruction when using the legacy builder (non buildkit).
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
LOL, wondering now if we can somehow skip the `-->` for these.

```
Step 1/2 : FROM scratch
 --->
Step 2/2 : LABEL asdf=1
 ---> Running in 08bc1d65adb1
 ---> Removed intermediate container 08bc1d65adb1
 ---> 7072ecaf239f
Successfully built 7072ecaf239f
Successfully tagged asdf:latest
```

(not something new, so not for this PR; looks like the same is the case without containerd-integration)

File: daemon/containerd/image_commit.go [hunk 1]
```diff
@@ -217,28 +227,46 @@ func writeContentsForImage(ctx context.Context, snName string, cs content.Store,
...
+func createDiff(ctx context.Context, name string, sn snapshots.Snapshotter, cs content.Store, comparer diff.Comparer) (*ocispec.Descriptor, digest.Digest, error) {
 	newDesc, err := rootfs.CreateDiff(ctx, name, sn, comparer)
 	if err != nil {
-		return ocispec.Descriptor{}, "", err
+		return nil, "", err
+	}
+
+	ra, err := cs.ReaderAt(ctx, newDesc)
+	if err != nil {
+		if cerrdefs.IsNotFound(err) {
```
Comment (rumpl) [inline daemon/containerd/image_commit.go:239]: What does it mean if we get a not found error here and why aren't we returning it?

Comment (vvoland) [reply daemon/containerd/image_commit.go:239]: It shouldn't happen now. I was meaning it to turn into a fast-path if `CreateDiff` behavior would change in future so that it doesn't produce an archive when the diff is empty.

Although, maybe it's better to fail loudly in case there's an actual error with `CreateDiff` and somehow it doesn't produce the archive even when it should?

File: daemon/containerd/image_commit.go [hunk 2]
```diff
@@ -217,28 +227,43 @@ func writeContentsForImage(ctx context.Context, snName string, cs content.Store,
...
+func createDiff(ctx context.Context, name string, sn snapshots.Snapshotter, cs content.Store, comparer diff.Comparer) (*ocispec.Descriptor, digest.Digest, error) {
 	newDesc, err := rootfs.CreateDiff(ctx, name, sn, comparer)
 	if err != nil {
-		return ocispec.Descriptor{}, "", err
+		return nil, "", err
+	}
+
+	ra, err := cs.ReaderAt(ctx, newDesc)
+	if err != nil {
+		return nil, "", fmt.Errorf("failed to read diff archive: %v", err)
```
Comment (rumpl) [inline daemon/containerd/image_commit.go:239]: Maybe wrap this error here
```suggestion
		return nil, "", fmt.Errorf("failed to read diff archive: %w", err)
```

Comment (vvoland) [reply daemon/containerd/image_commit.go]: Done, thanks

File: pkg/archive/diff.go [hunk 3]
```diff
@@ -224,6 +224,25 @@ func ApplyUncompressedLayer(dest string, layer io.Reader, options *TarOptions) (
 	return applyLayerHandler(dest, layer, options, false)
 }
 
+// IsEmpty checks if the tar archive is empty (doesn't contain any entries).
+func IsEmpty(rd io.Reader) (bool, error) {
```
Comment (thaJeztah) [inline pkg/archive/diff.go:228]: And now I'm wondering; could we still detect this using "Ye olde sha" of the empty tar? 

https://github.com/moby/moby/pull/8827

> Goodbye '511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158',
> it was nice knowing you.

**Review by rumpl — APPROVED** [review]

File: pkg/archive/diff.go (hunk 3 above)
Comment (vvoland) [reply pkg/archive/diff.go:228]: Added a fast path.

**Review by rumpl — APPROVED** [review]

File: pkg/archive/diff.go (hunk 3 above)
Comment (thaJeztah) [reply pkg/archive/diff.go:228]: ^^ for future reference; this was reverted; it turned out that there was no canonical digest for "empty archive", and the code below was not "too heavy", so it wouldn't gain us much.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
- backport: https://github.com/moby/moby/pull/46302
