### PR TITLE
cifs volume resolves hostname correctly

### LINKED ISSUE #46180: Unable to mount CIFS using FQDN or 'addr' option - Ubuntu 22.10 host
### Description

If I create a volume that references a remote share - e.g. CIFS - by hostname or FQDN, the create step works fine, but when I try to start a container that references the volume, it fails to start, complaining 'no route to host' for the CIFS mount. Referencing the share by IP address works.

If I run the same container without referencing the failing volume, inside the container I can ping the CIFS server by name and by FQDN perfectly well.

I have tried the '--opt o=addr=<fqdn>' method and that returns 'addr: invalid argument'.

The host OS is Ubuntu 22.10 (it's running as a privileged LXC to facilitate sharing an Intel iGPU, not that that should matter!); the host system can mount the same shares just fine.

### Reproduce

Create volume for CIFS share:
```
root@dock:/home/netadmin# docker volume create --driver local --opt type=cifs \
--opt "o=addr=dougal.mydomain.net,username=_backup,password=******" \
--opt device=//dougal/TransferTemp ttt
root@dock:/home/netadmin# docker volume inspect ttt
[
    {
        "CreatedAt": "2023-08-09T14:13:17Z",
        "Driver": "local",
        "Labels": null,
        "Mountpoint": "/var/lib/docker/volumes/ttt/_data",
        "Name": "ttt",
        "Options": {
            "device": "//dougal/TransferTemp",
            "o": "addr=dougal.mydomain.net",
            "type": "cifs"
        },
        "Scope": "local"
    }
]
```
Start container, referencing that volume:
```root@dock:/home/netadmin# docker run -it --rm -v ttt:/test busybox sh
docker: Error response from daemon: error while mounting volume '/var/lib/docker/volumes/ttt/_data': failed to mount local volume: mount //dougal/TransferTemp:/var/lib/docker/volumes/ttt/_data, data: **addr=192.168.11.22: invalid argument**.
```
Further testing:
```root@dock:/home/netadmin# nslookup dougal.mydomain.net
Server:         192.168.11.1
Address:        192.168.11.1#53

Non-authoritative answer:
Name:   dougal.mydomain.net
Address: 192.168.11.22

root@dock:/home/netadmin# smbclient -L dougal.mydomain.net
Password for [WORKGROUP\root]:
Anonymous login successful

        Sharename       Type      Comment
        ---------       ----      -------
        TransferTemp    Disk
        RemoteBackup    Disk
```
If I omit the 'addr' option, the response from the mount command is different: 'no route to host'.

### Expected behavior

Ideally, all that should be needed is the UNC path for the share, no other options; that's all that the OS mount command needs.  The container and the host both have DNS that can resolve the hostname or FQDN.
However, any method that enables mounting CIFS volumes by DNS name will help! ;-)

### docker version

```bash
Client: Docker Engine - Community
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:35:24 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.6
  Git commit:       a61e2b4
  Built:            Fri Jul 21 20:35:24 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.20.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 4
  Running: 3
  Paused: 0
  Stopped: 1
 Images: 6
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.107-2-pve
 Operating System: Ubuntu 22.10
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 16GiB
 Name: dock
 ID: 09e14fad-905a-4027-8cfd-231e4ceb94b0
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

The underlying OS can mount the CIFS shares just fine and needs only the UNC path:
```
root@dock:/home/netadmin# mount -t cifs //dougal.mydomain.net/TransferTemp /tmp/test -o "username=_backup,password=******"
root@dock:/home/netadmin# ls /tmp/test
 Documents.tar
 E18905_PRIME_B560M-A_v2_UM_WEB.pdf
 Map-of-Europe-Political.pdf
 PXL_20211218_100440101.jpg
 PXL_20211218_100445210.jpg
 PXL_20211218_100456081.jpg
```

### PR DESCRIPTION
**Pull request by michaelkebe**
- fixes: https://github.com/moby/moby/issues/46180

**- What I did**
Fixed this issue https://github.com/moby/moby/issues/46180. There is a old PR which claims to fix this #39250, but is hasn't.

The problem is that, the hostname in NFS and CIFS mounts are at different places.

NFS uses the `addr` value in the `MountOpts`.
CIFS uses the hostname part of the `MountDevice` URL.

**- How I did it**

Splitted the switch case statement of #39250 for NFS and CIFS. Used the `net/url` `Parse` function to extract the hostname. And handled the rest in the same way NFS did.

**- How to verify it**
Create a docker volume using a hostname instead of an IP address.
Start a container using that volume.

**- Description for the changelog**

CIFS volumes resolving FQDN correctly.

I am not a go hacker, so maybe it's not "go idiomatic".

### CODE REVIEW

File: volume/local/local_unix.go [hunk 1]
```diff
@@ -112,18 +113,33 @@ func (v *localVolume) mount() error {
...
 				return errors.Wrapf(err, "error resolving passed in network volume address")
 			}
 			mountOpts = strings.Replace(mountOpts, "addr="+addrValue, "addr="+ipAddr.String(), 1)
 		}
+	case "cifs":
+		deviceUrl, err := url.Parse(v.opts.MountDevice)
+		if err != nil {
+			return errors.Wrapf(err, "error parsing mount device url")
+		}
+		if deviceUrl.Host != "" && net.ParseIP(deviceUrl.Host).To4() == nil {
```
Comment (vvoland) [inline volume/local/local_unix.go:134]:
```suggestion
		if deviceUrl.Host != "" && net.ParseIP(deviceUrl.Host) == nil {
```

I know this was just taken from the previous code, but I'm wondering if there is a reason to restrict the lookup to IPv4 addresses only?

File: volume/local/local_unix.go [hunk 2]
```diff
@@ -112,18 +113,33 @@ func (v *localVolume) mount() error {
...
+			ipAddr, err := net.ResolveIPAddr("ip", deviceUrl.Host)
+			if err != nil {
+				return errors.Wrapf(err, "error resolving passed in network volume address")
+			}
+			mountDevice = strings.Replace(mountDevice, "//"+deviceUrl.Host, "//"+ipAddr.String(), 1)
```
Comment (vvoland) [inline volume/local/local_unix.go:139]: Considering that the whole `device` part is expected to be a server address, could we change the `Host` property of the URL instead and use that to generate the new string, instead of doing a plain string replace?

```suggestion
			deviceUrl.Host = ipAddr.String()
			mountDevice = deviceUrl.String()
```

**Review by vvoland — COMMENTED** [review]
Thank you for contributing!
I have a couple of comments.

Could you also amend the commit message and remove the "Fixes #XXX" magic string? We tend to only include these in the PR bodies to avoid Github doing auto-close when commits are merged in forks or other repositories.

**Comment by michaelkebe** [comment]
Adopted your suggestions and it works. @vvoland

File: volume/local/local_unix.go [hunk 3]
```diff
@@ -112,18 +113,34 @@ func (v *localVolume) mount() error {
...
 				return errors.Wrapf(err, "error resolving passed in network volume address")
 			}
 			mountOpts = strings.Replace(mountOpts, "addr="+addrValue, "addr="+ipAddr.String(), 1)
 		}
+	case "cifs":
+		deviceUrl, err := url.Parse(v.opts.MountDevice)
+		if err != nil {
+			return errors.Wrapf(err, "error parsing mount device url")
+		}
+		if deviceUrl.Host != "" && net.ParseIP(deviceUrl.Host) == nil {
```
Comment (vvoland) [inline volume/local/local_unix.go:134]: Ah, one thing I forgot about. `Host` also includes port, so we need to strip it when parsing it as IP:

```suggestion
		if deviceUrl.Host != "" && net.ParseIP(deviceUrl.Hostname()) == nil {
```

File: volume/local/local_unix.go [hunk 4]
```diff
@@ -112,18 +113,34 @@ func (v *localVolume) mount() error {
...
+			ipAddr, err := net.ResolveIPAddr("ip", deviceUrl.Host)
+			if err != nil {
+				return errors.Wrapf(err, "error resolving passed in network volume address")
+			}
+			deviceUrl.Host = ipAddr.String()
```
Comment (vvoland) [inline volume/local/local_unix.go:139]: And we also need to keep the port when we replace the hostname with IP:

```suggestion
			deviceUrl.Host = net.JoinHostPort(ipAddr.String(), ipAddr.Port())
```

**Review by vvoland — CHANGES_REQUESTED** [review]
Good work, thanks! Just 2 more things regarding the `Host` field.

File: volume/local/local_unix.go (hunk 1 above)
Comment (thaJeztah) [reply volume/local/local_unix.go]: Original PR for nfs was https://github.com/moby/moby/pull/27329

I don't see an immediate mention during review about IPv4, but there was a `IsIP()` helper (that was later removed?) https://github.com/moby/moby/pull/27329#discussion_r83203368

And I saw some mention of a complex RegEx that was later removed, so I wonder if the `.To4()` was just use as validation for "is it an IP address?")

We should look if we can use IPv6 addresses without issues (or if they need the bracketed (`[::1]`) notation or escaping)

**Comment by michaelkebe** [comment]
@vvoland 

Incorporated your suggestions.

I never stumpled upon CIFS with different than default port.
Trying to add one with 

    docker create volume ... --opt device="//some.host.name.com:445/some/path" ...

gives me this error, when running a container using this volume:

ERRO[2023-11-29T14:30:53.631287791Z] Handler for POST /v1.43/containers/d1d6043b1890daef2b28dac0ce8053a74dc0c0932a2947bc2ea1da39d7101fe4/start returned error: error while mounting volume '/var/lib/docker/volumes/foo/_data': error resolving passed in network volume address: lookup some.host.name.com:445: no such host
docker: Error response from daemon: error while mounting volume '/var/lib/docker/volumes/foo/_data': error resolving passed in network volume address: lookup some.host.name.com:445: no such host.

I have not enough knowledge about CIFS and its port usage, to comment on this.

With default ports it works fine.

File: volume/local/local_unix.go [hunk 5]
```diff
@@ -112,18 +113,34 @@ func (v *localVolume) mount() error {
...
 			}
 			mountOpts = strings.Replace(mountOpts, "addr="+addrValue, "addr="+ipAddr.String(), 1)
 		}
+	case "cifs":
+		deviceUrl, err := url.Parse(v.opts.MountDevice)
+		if err != nil {
+			return errors.Wrapf(err, "error parsing mount device url")
+		}
+		if deviceUrl.Host != "" && net.ParseIP(deviceUrl.Hostname()) == nil {
+			ipAddr, err := net.ResolveIPAddr("ip", deviceUrl.Host)
```
Comment (vvoland) [inline volume/local/local_unix.go:135]: We also need to strip the port when doing the DNS query:
```suggestion
			ipAddr, err := net.ResolveIPAddr("ip", deviceUrl.Hostname())
```

**Review by vvoland — CHANGES_REQUESTED** [review]

**Review by vvoland — COMMENTED** [review]
Thanks! Looks good to me, just needs a rebase on top of the master and dropping the `hack/dind` commits.

File: volume/local/local_unix.go [hunk 6]
```diff
@@ -112,18 +113,34 @@ func (v *localVolume) mount() error {
...
+	case "nfs":
 		if addrValue := getAddress(v.opts.MountOpts); addrValue != "" && net.ParseIP(addrValue).To4() == nil {
 			ipAddr, err := net.ResolveIPAddr("ip", addrValue)
 			if err != nil {
 				return errors.Wrapf(err, "error resolving passed in network volume address")
 			}
 			mountOpts = strings.Replace(mountOpts, "addr="+addrValue, "addr="+ipAddr.String(), 1)
 		}
+	case "cifs":
+		deviceUrl, err := url.Parse(v.opts.MountDevice)
```
Comment (thaJeztah) [inline volume/local/local_unix.go:130]: minor nit: can you change this to `deviceURL` (all-caps for URL) to use the correct camelcase notation?

File: volume/local/local_unix.go [hunk 7]
```diff
@@ -112,18 +113,34 @@ func (v *localVolume) mount() error {
...
+		if err != nil {
+			return errors.Wrapf(err, "error parsing mount device url")
+		}
+		if deviceUrl.Host != "" && net.ParseIP(deviceUrl.Hostname()) == nil {
+			ipAddr, err := net.ResolveIPAddr("ip", deviceUrl.Hostname())
+			if err != nil {
+				return errors.Wrapf(err, "error resolving passed in network volume address")
+			}
+			deviceUrl.Host = net.JoinHostPort(ipAddr.String(), deviceUrl.Port())
```
Comment (thaJeztah) [inline volume/local/local_unix.go:139]: Was looking at this, and we may need to have a check if `deviceUrl.Port()` is not empty; I did a quick check, and it looks like `net.JoinHostPort` unconditionally adds a colon (`:`), also if there's no port; https://go.dev/play/p/MrZXfaigVRF

```go
package main

import (
	"fmt"
	"net"
)

func main() {
	fmt.Println(net.JoinHostPort("1.2.3.4", ""))
	fmt.Println(net.JoinHostPort("::1", ""))
}
```

Code above prints;

```
1.2.3.4:
[::1]:
```

**Review by vvoland — CHANGES_REQUESTED** [review]
Thanks! Looking good, just needs one last touch.

Can you also apply Sebastiaan's suggestion (check if Port is empty)?
https://github.com/moby/moby/pull/46863#discussion_r1409535576

Also, please make sure that you squash your commits (so the PR has only one commit).

**Review by vvoland — APPROVED** [review]
Thanks, LGTM!

**Comment by thaJeztah** [comment]
Thanks! changes look good; some things we should look at in a follow-up (perhaps you're interested in working on these?)

- perhaps we should apply the same improvements we made for `cifs` to the `nfs` case as well (if it also handles IPv6?), I _think_ nfs expects `port` to be a separate option so we probably don't need the `JoinHostPort` part, but maybe have to deal with formatting duet to `:` being used
- consider extracting parsing of these options, so that we can unit-test them

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by vvoland** [comment]
Yeah, looks like the port is expected to be passed as a separate `port` option, not the address.

```
docker volume create --driver local --opt type=cifs \
--opt o=username=USERNAME,password=PASSWORD,vers=3,sec=ntlmsspi,port=1234 \
--opt device="//some.server.com/SOME/PATH" VOLUME_NAME
```

Considering that the `mount.cifs(8)` also
```bash
$ mount -t cifs //example.xyz:1231/adsd /mnt
mount error: could not resolve address for example.xyz:1231: Unknown error
```
doesn't separate the port, perhaps we should do the same and just use the whole `Host` part. So basically reverting my suggestions from: https://github.com/moby/moby/pull/46863#pullrequestreview-1755178465 (sorry, it didn't occur to me that cifs uses a separate `port` option 😞)

Alternatively, we could error out with an explanation that user should pass the `port` option instead. WDYT? @thaJeztah

**Comment by thaJeztah** [comment]
Yes, perhaps an error would make sense, so that we don't diverge too much from what's expected. If we would do the parsing and conversion (`host:port` -> `port=xxx`), that would also introduce new challenges, such as if the user specifies _BOTH_ `host:port` _AND_ `port=xxx` in options.

**Comment by vvoland** [comment]
I wouldn't be in favor of the `host:port` -> `port=xxx` conversion, I think we want to minimize the translation we do between what user input and what we give to the kernel.

But, providing an extra, more user friendly warning is probably fine, since it also avoids user confusion and blaming the engine for not connecting to the right port.

**Comment by Mist-Hunter** [comment]
Previously, I had been using a CIFS option, `addr=` to mitigate this hostname resolution issue. Did this command get deprecated or removed? All my CIFS volumes and associated containers fail to load now due to 'invalid command' and not until rebuilding the volume with 'addr=' removed, will it start again. ( example of the command in question: https://serverfault.com/a/848166 ) 

I'm guessing this is intended, but thought I'd share this here in case anyone else ran into this issue.
