### PR TITLE
Fix br_netfilter module loading logic

### LINKED ISSUE #48948: br_netfilter module is not loaded by docker
### Description

With `docker-27.3.1` `br_netfilter` module is not loaded by default when docker service is started.

The code was removed in https://github.com/moby/moby/commit/db25b0dcd0461802289e962aa0df3abd323d1994;

- https://github.com/moby/moby/pull/48492

And this seems to be a regression.

### Reproduce

1. `docker swarm init --advertise-addr 127.0.0.1:8090`
2. `docker service create --name my_web --replicas 1 --publish 8090:80 nginx`

When the second command is run, I see the below error in journal.

```
Nov 25 13:55:38 ph5dev dockerd[9682]: time="2024-11-25T13:55:38.866243855Z" level=error msg="fatal task error" error="error creating external connectivity network: cannot restrict inter-container communication: ensure that the br_netfilter kernel module is loaded" module=node/agent/taskmanager node.id=ymvxcf846da1w705604iv6mzd service.id=hbhvrkgmqbs7h4evch9c1q7gh task.id=izaubnqj8cnq02le61okgnlmg
```

cc: @robmry 

### Expected behavior

`br_netfilter` module should be loaded when docker service starts and backward compatibility should be maintained.
This was working as expected till `docker-27.2.1`

### docker version

```bash
Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.21.13
 Git commit:        3ab4256
 Built:             Mon Nov 25 13:35:46 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.21.13
  Git commit:       3ab5c7d
  Built:            Mon Nov 25 13:36:04 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:       ''
 runc:
  Version:          1.1.14
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:        ''
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version:
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.118-1.ph5
 Operating System: VMware Photon OS/Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.916GiB
 Name: ph5dev
 ID: db2af409-5f08-402a-bb47-a57db13191b8
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by sshedi**
Checking for `/proc/sys/net/bridge` directory alone is not enough to decide if bridge, br_netfilter module to be loaded. Check for specific file for each bridge & br_netfilter module and then do modprobe if the file is not found in `/proc/sys/net/bridge`

Fixes: https://github.com/moby/moby/issues/48948

Please provide the following information:
-->

**- What I did**
Fix loading of bridge and br_netfilter kernel modules

**- How I did it**
By check for presence of specific files for each module in procfs

**- How to verify it**
```
systemctl restart docker
lsmod | grep br_netfilter
```

**- Description for the changelog**

```markdown changelog
Fix loading of `bridge` and `br_netfilter` kernel modules.
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by sshedi** [comment]
cc: @robmry

File: libnetwork/drivers/bridge/setup_bridgenetfiltering.go [hunk 1]
```diff
@@ -45,14 +45,31 @@ func setupIPv6BridgeNetFiltering(config *networkConfiguration, _ *bridgeInterfac
 	return nil
 }
 
+func LoadBridgeModules() error {
+	moduleMap := map[string]string {
+		"arp_probe":                "bridge",
```
Comment (robmry) [inline libnetwork/drivers/bridge/setup_bridgenetfiltering.go:50]: With whatever Debian kernel I was using, I found that loading `bridge` doesn't create anything in `/proc/sys/net`. However, creating a bridge loads module `bridge` automatically.

That means the module will always be loaded before `enableBridgeNetFiltering` is called (because at-least `docker0` will have been created). Also, modprobe-ing `br_netfilter` loads `bridge` as a dependency.

So, I think we should drop the check for `arp_probe` and not try to `modprobe bridge` - as it'll happen each time a network is created on hosts where `arp_probe` isn't created (and it'll simplify the code a little).

File: libnetwork/drivers/bridge/setup_bridgenetfiltering.go [hunk 2]
```diff
@@ -45,14 +45,31 @@ func setupIPv6BridgeNetFiltering(config *networkConfiguration, _ *bridgeInterfac
...
+
 // Enable bridge net filtering if not already enabled. See GitHub issue #11404
 func enableBridgeNetFiltering(nfParam string) error {
-	if _, err := os.Stat("/proc/sys/net/bridge"); err != nil {
-		if out, err := exec.Command("modprobe", "-va", "bridge", "br_netfilter").CombinedOutput(); err != nil {
-			log.G(context.TODO()).WithError(err).Errorf("Running modprobe bridge br_netfilter failed with message: %s", out)
-			return fmt.Errorf("cannot restrict inter-container communication: modprobe br_netfilter failed: %w", err)
-		}
+	err := LoadBridgeModules()
+	if err != nil {
```
Comment (robmry) [inline libnetwork/drivers/bridge/setup_bridgenetfiltering.go:69]: To limit the scope of this `err`, and we try to be fussy about such things in new/changed code ... 

```suggestion
	if err := LoadBridgeModules(); err != nil {
```

File: libnetwork/drivers/bridge/setup_bridgenetfiltering.go [hunk 3]
```diff
@@ -45,14 +45,31 @@ func setupIPv6BridgeNetFiltering(config *networkConfiguration, _ *bridgeInterfac
...
 
+func LoadBridgeModules() error {
+	moduleMap := map[string]string {
+		"arp_probe":                "bridge",
+		"bridge-nf-call-iptables":  "br_netfilter",
+	}
+
+	for fPath, modName := range moduleMap {
+		fullPath := "/proc/sys/net/bridge/" + fPath
+		if _, err := os.Stat(fullPath); err != nil {
```
Comment (robmry) [inline libnetwork/drivers/bridge/setup_bridgenetfiltering.go:56]: It might be worth logging here ... then we'll be able to tell if dockerd attempted the load - and we'll be more likely to spot the problem if we come across a host where the test for "bridge-nf-call-iptables" doesn't work as expected, causing us to run unnecessary modprobes.

```suggestion
		log.G(context.TODO()).Info("Loading br_netfilter")
		if _, err := os.Stat(fullPath); err != nil {
```

File: libnetwork/drivers/bridge/setup_bridgenetfiltering.go [hunk 4]
```diff
@@ -45,14 +45,31 @@ func setupIPv6BridgeNetFiltering(config *networkConfiguration, _ *bridgeInterfac
 	return nil
 }
 
+func LoadBridgeModules() error {
```
Comment (robmry) [inline libnetwork/drivers/bridge/setup_bridgenetfiltering.go:48]: This function doesn't need to be exported (as part of the package interface) ...

```suggestion
func loadBridgeModules() error {
```

**Review by robmry — CHANGES_REQUESTED** [review]
Thank you for working on this, much appreciated!

I've made some suggestions ... if they look good to you, please squash commits before pushing updates. Linking to the issue from the PR is good, but it'd be best to remove it from the commit message (so that GitHub doesn't keep adding links everywhere).

**Comment by robmry** [comment]
Tests are failing with ...

```
setup_ip_tables_linux_test.go:394: cannot restrict inter-container communication: modprobe bridge failed: exec: "modprobe": executable file not found in $PATH
```

I guess that's because the directory exists, so `modprobe` wasn't needed before - and now `arp_probe` doesn't exist, so it is called.

I'm wondering if it'd be best to use a `sync.Once` to call `loadBridgeModules` to try the modprobe (without making any checks for files existing), and log the result without returning an error... if `br_netfilter` is already loaded, it's a cheap call so no real loss. If the sysctl files don't exist after that, `getKernelBoolParam` will fail and generate an error (the original error you found in the logs). I think that'd just be a bit less to go wrong, and maintain if we ever modify which sysctls we're setting?

File: libnetwork/drivers/bridge/setup_bridgenetfiltering.go (hunk 1 above)
Comment (sshedi) [reply libnetwork/drivers/bridge/setup_bridgenetfiltering.go:50]: Agree, changed logic to just load `br_netfilter`

**Comment by sshedi** [comment]
> Tests are failing with ...
> 
> ```
> setup_ip_tables_linux_test.go:394: cannot restrict inter-container communication: modprobe bridge failed: exec: "modprobe": executable file not found in $PATH
> ```
> 
> I guess that's because the directory exists, so `modprobe` wasn't needed before - and now `arp_probe` doesn't exist, so it is called.
> 
> I'm wondering if it'd be best to use a `sync.Once` to call `loadBridgeModules` to try the modprobe (without making any checks for files existing), and log the result without returning an error... if `br_netfilter` is already loaded, it's a cheap call so no real loss. If the sysctl files don't exist after that, `getKernelBoolParam` will fail and generate an error (the original error you found in the logs). I think that'd just be a bit less to go wrong, and maintain if we ever modify which sysctls we're setting?

We can but checking for directory existence is a lot cheaper than invoking a binary. I can make this change if you insist.

**Comment by robmry** [comment]
> We can but checking for directory existence is a lot cheaper than invoking a binary. I can make this change if you insist.

Thanks @sshedi - it's looking good. No need to make that change, it was just a thought.

I don't know what's going on with the tests yet, it doesn't look like anything to do with this PR though ...

**Comment by crazy-max** [comment]
Reverted the bump to latest Buildx stable for our actions in https://github.com/docker/actions-toolkit/pull/508.

I triggered a re-run of failed jobs, should work now.

**Review by robmry — APPROVED** [review]

File: libnetwork/drivers/bridge/setup_bridgenetfiltering.go [hunk 5]
```diff
@@ -45,13 +45,24 @@ func setupIPv6BridgeNetFiltering(config *networkConfiguration, _ *bridgeInterfac
 	return nil
 }
 
+func loadBridgeNetFilterModule() error {
+	fullPath := "/proc/sys/net/bridge/bridge-nf-call-iptables"
```
Comment (thaJeztah) [inline libnetwork/drivers/bridge/setup_bridgenetfiltering.go:49]: I notice that `enableBridgeNetFiltering` is called with `nfParam` parameter that.. is the same as this, but has either `iptables` or `ip6table`; 


```bash
git grep 'enableBridgeNetFiltering'
libnetwork/drivers/bridge/setup_bridgenetfiltering.go:          return enableBridgeNetFiltering("/proc/sys/net/bridge/bridge-nf-call-iptables")
libnetwork/drivers/bridge/setup_bridgenetfiltering.go:          return enableBridgeNetFiltering("/proc/sys/net/bridge/bridge-nf-call-ip6tables")
libnetwork/drivers/bridge/setup_bridgenetfiltering.go:func enableBridgeNetFiltering(nfParam string) error {
```


Should this function unconditionally use `/proc/sys/net/bridge/bridge-nf-call-iptables`, or should it take an argument and get called passing through the `nfParam` from `enableBridgeNetFiltering` ?

Comment (sshedi) [reply libnetwork/drivers/bridge/setup_bridgenetfiltering.go:49]: Good point. When `br_netfilter` module gets loaded, both these files will be present under `/proc/sys/net/bridge/`
I will make the adjustments, thanks.

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!
