### PR TITLE
Fix #34953 how volumes are pruned from daemon

### LINKED ISSUE #34953: Prune volume doesn't create an event entry
**Description**

While calling `docker volume prune`, the pruning of a volume doesn't create an event entry.

**Steps to reproduce the issue:**
1. `docker events > events.log &` to listen docker events
2. `docker volume create chazam` to create a test volume
3. `docker volume prune` to delete volumes

**Describe the results you received:**
On the events.log file you should, only, see the creation event:
`2017-09-23T07:10:44.965370986Z volume create chazam (driver=local)`

**Describe the results you expected:**
I should expect to have an event entry on the volume deletion.

**Problem localisation**
The problem is on the `daemon/prune.go` file. More precisely the `VolumesPrune` function, line `143`.
We should call `err = daemon.VolumeRm(v.Name(), false)` instead of the actual `err = daemon.volumes.Remove(v)`.

**Output of `docker version`:**
```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:15:15 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-dev
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   c982ee8
 Built:        Sat Sep 23 07:09:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.06.0-dev
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 1c81e2a794c6e26a4c650142ae8893c47f619764
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.41-moby
Operating System: Debian GNU/Linux 9 (stretch) (containerized)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: 977aaa405be0
ID: K6M2:ALHJ:AVJ5:XVW7:E4X5:W34D:35XQ:K6HK:YVOF:EA2N:U4BO:6QRT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 28
 System Time: 2017-09-23T07:12:39.720242284Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### PR DESCRIPTION
**Pull request by sterchelen**
- Call the function that create an event entry while volumes are pruning.

Signed-off-by: Nicolas Sterchele <sterchele.nicolas@gmail.com>

**- What I did**
From `daemon/prune.go` file, function `VolumesPrune` line `143`, I replaced the following call `daemon.volumes.Remove' by this one `daemon.VolumeRm.

**- How to verify it**
Listen the events by calling `docker events`, then remove volumes with the following command `docker volume prune`. Now you should see an event entry.
**- Description for the changelog**
Replace volumes pruning call by the one that create an event entry.

### CODE REVIEW

File: daemon/prune.go [hunk 1]
```diff
@@ -140,7 +140,7 @@ func (daemon *Daemon) VolumesPrune(ctx context.Context, pruneFilters filters.Arg
 			if err != nil {
 				logrus.Warnf("could not determine size of volume %s: %v", name, err)
 			}
-			err = daemon.volumes.Remove(v)
+			err = daemon.VolumeRm(v.Name(), false)
```
Comment (cpuguy83) [inline daemon/prune.go]: Looks like there's a `VolumeRm` and a `volumeRm` where the former takes care of the bool part and the latter takes care of the rest.
Maybe we can change `volumeRm` to take a `volume.Volume` instead of a name so we don't have to re-lookup the volume and then for `VolumesRm` it can just do it's own lookup.

**Review by cpuguy83 — CHANGES_REQUESTED** [review]

**Comment by sterchelen** [comment]
@cpuguy83 If we want to delete a volume by using --force and the volume does not exists, do we throw an error ? 
If yes, I think that the `TestVolumeCLIRmForceUsage` test on the`integration_cli/docker_cli_volume_test.go` file is wrong. We should assert on error ? 

I'm saying that, because the tests suite don't pass ! This is due to the move of the volume lookup. In fact, if the volume does not exists, we return the error to the caller.

**Comment by cpuguy83** [comment]
I would say let's preserve behavior here and open a separate issue to discuss if this should be changed.

File: daemon/prune.go (hunk 1 above)
Comment (thaJeztah) [reply daemon/prune.go]: @ripcurld0 looks like you updated the function but forgot to update this; should this now be like below?

```go
err = daemon.volumeRM(v)
```

**Review by thaJeztah — CHANGES_REQUESTED** [review]

File: daemon/prune.go (hunk 1 above)
Comment (sterchelen) [reply daemon/prune.go]: @thaJeztah I think you meant `@sterchelen`.
As @cpuguy83 mentioned:

> Maybe we can change **volumeRm** to take a _volume.Volume_ instead of a name so we don't have to re-lookup the volume and then for **VolumesRm** it can just do **it's own lookup**.

So, if I well understood, we just have to change the `volumeRm` function to take a `volume.Volume` instead of the name and let the actual `VolumesRm` function signature.

Comment (ripcurld0) [reply daemon/prune.go]: @thaJeztah I don't remember changing that line. However, `git blame` says it was @mlaventure 😆

**Comment by sterchelen** [comment]
@cpuguy83 Is the PR good for you ?

File: daemon/prune.go [hunk 2]
```diff
@@ -140,7 +140,7 @@ func (daemon *Daemon) VolumesPrune(ctx context.Context, pruneFilters filters.Arg
 			if err != nil {
 				logrus.Warnf("could not determine size of volume %s: %v", name, err)
 			}
-			err = daemon.volumes.Remove(v)
+			err = daemon.VolumeRm(name, false)
```
Comment (cpuguy83) [inline daemon/prune.go]: This should use `daemon.volumeRm` instead.

**Comment by sterchelen** [comment]
@cpuguy83 The modification is done.

**Comment by thaJeztah** [comment]
trying to trigger CI, but GitHub is having issues

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by sterchelen** [comment]
There is a problem with Jenkins... No space left on device: https://jenkins.dockerproject.org/job/Docker-PRs-experimental/37350/console

**Review by thaJeztah — APPROVED** [review]
LGTM if green 

I'm on my phone, can you label this "merge", and start CI once more?

**Comment by thaJeztah** [comment]
Hm, I think there's an issue for this as well; remind me to look that up :smile:

Thanks!

**Comment by thaJeztah** [comment]
Nevermind; it was linked; https://github.com/moby/moby/issues/34953
