### PR TITLE
Use user data path for plugin discovery in rootless mode

### LINKED ISSUE #43111: [BUG] Rootless docker - plugin discovery uses wrong path
**Description**

I'm running the docker engine in rootless mode in parallel with another rootfull engine.
When calling `docker volume ls`, the rootless daemon returns an error message that it failed to read the rootfull daemon's plugins folder.

TL;DR: It seems the rootless daemon's  plugin discovery is using the wrong path.

**Steps to reproduce the issue:**
1. Install rootfull docker ([see here](https://docs.docker.com/engine/install/ubuntu/))
2. Install rootless docker ([see here](https://docs.docker.com/engine/security/rootless/))
3. Rootless cli: `docker volume create test`
2. Rootless cli: `docker volume ls`
3. See daemon response: 
   ```
   Error response from daemon: list: error listing plugins: legacy plugin: error reading dir entries: open /etc/docker/plugins: permission denied
   ```

**Describe the results you received:**
Error response from daemon, that it failed to read the protected rootfull daemon's plugin folder at `/etc/docker/plugins`.

**Describe the results you expected:**
List of volumes (that contains one item named "test").

I would expect that the plugins in the rootless docker directory ("Docker Root Dir") at `/home/rootless/.local/share/docker/plugins` are used.

**Additional information you deem important (e.g. issue happens only occasionally):**

The hard-coded paths are used in rootless mode. 
Shouldn't the plugin path be selected by the mode (rootfull or rootless)? 
Or shouldn't the plugin path depend on the docker root directory?

Location in code:
https://github.com/moby/moby/blob/94e00d09da6a12b32161889e9a15c6c2da7bc0d2/pkg/plugins/discovery_unix.go#L6
https://github.com/moby/moby/blob/94e00d09da6a12b32161889e9a15c6c2da7bc0d2/pkg/plugins/discovery.go#L33

**Output of `docker version`:**

```
$ docker version
Client:
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:40:57 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:46:12 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.1)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  rootless
  cgroupns
 Kernel Version: 5.13.0-22-generic
 Operating System: Ubuntu 21.10
 OSType: linux
 Architecture: x86_64
 CPUs: 3
 Total Memory: 3.74GiB
 Name: ubuntu-8gb-nbg1-dc3-1
 ID: ****
 Docker Root Dir: /home/rootless/.local/share/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpu shares support
WARNING: No cpuset support
WARNING: No io.weight support
WARNING: No io.weight (per device) support
WARNING: No io.max (rbps) support
WARNING: No io.max (wbps) support
WARNING: No io.max (riops) support
WARNING: No io.max (wiops) support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Hosted Ubuntu on a VM machine.

### PR DESCRIPTION
**Pull request by ghost**
Signed-off-by: Jan Garcia <github-public@n-garcia.com>

fixes #43111

**- What I did**

We now dynamically determine the plugins path when running in rootless mode.

**- How I did it**

Introduce a new function, `plugins.SpecsPaths` which returns `$XDG_DATA_HOME/.local/share/docker/plugins`
on Unix in rootless mode and `specsPaths` otherwise.

**- How to verify it**

You can test this by running `dockerd` in rootless mode while `/etc/docker` is not accessible by the user.
Without this patch, creating volumes will fail. With this patch creating volumes works.

**- Description for the changelog**

Use user data path for plugin discovery in rootless mode

### CODE REVIEW

File: pkg/plugins/discovery_unix.go [hunk 1]
```diff
@@ -2,5 +2,21 @@
...
 
 var specsPaths = []string{"/etc/docker/plugins", "/usr/lib/docker/plugins"}
+
+// ConfigureSpecsPaths configures plugins.specsPaths depending on if the daemon
+// is running in rootless mode or not. On Windows, it is a no-op.
+func ConfigureSpecsPaths() {
+	if rootless.RunningWithRootlessKit() {
+		dataHome, err := homedir.GetDataHome()
+		if err == nil {
+			specsPaths = []string{filepath.Join(dataHome, "docker/plugins")}
```
Comment (vvoland) [inline pkg/plugins/discovery_unix.go:19]: Personally I would prefer to avoid functions that mutate global variables and depend on being called in a specific time and place.
I think it would be better to change `specsPaths` into a function returning paths, which would be defined differently in each `discovery_<platform>.go`. This way we don't have any global mutable variable and don't need to worry about calling the `ConfigureSpecsPaths`.
What do you think?

**Review by vvoland — COMMENTED** [review]
Thank you for your contribution! Looks good to me, but I left one comment regarding mutating the global variable.

File: pkg/plugins/discovery_unix.go (hunk 1 above)
Comment (jg-public) [reply pkg/plugins/discovery_unix.go:19]: Sounds good, will do

Comment (thaJeztah) [reply pkg/plugins/discovery_unix.go:19]: Ah, yes, was thinking along the same lines as well; was also wondering; would it do any harm to unconditionally append `homedir.GetDataHome()` to the list of paths to look in? Perhaps needs a `sync.Once` to resolve the path once (if there's nothing like that yet), but then a `specPaths()` function could return the lists of paths to look for.

Comment (thaJeztah) [reply pkg/plugins/discovery_unix.go:19]: ^^ I didn't dig into all code-paths though, so be sure to look if that idea works 😅

Comment (jg-public) [reply pkg/plugins/discovery_unix.go]: I introduced `func SpecsPaths() []string` while keeping `specsPaths` around to avoid a large diff in the Unit-Tests.

> would it do any harm to unconditionally append `homedir.GetDataHome()` to the list of paths to look in? 

Right now the user can use his own plugins without being affected by plugins installed in the host system.
If we add `$XDG_DATA_HOME/.local/share/docker/plugins` to `SpecsPaths` unconditionally, the user no longer has this option

File: pkg/plugins/discovery_unix.go [hunk 2]
```diff
@@ -2,5 +2,25 @@
...
+	"github.com/docker/docker/rootless"
+	"path/filepath"
+)
 
 var specsPaths = []string{"/etc/docker/plugins", "/usr/lib/docker/plugins"}
+
+// SpecsPaths returns
+// { "%programdata%\docker\plugins" } on Windows,
+// { "/etc/docker/plugins", "/usr/lib/docker/plugins" } on Unix in non-rootless mode,
+// { "$XDG_DATA_HOME/.local/share/docker/plugins" } on Unix in rootless mode.
```
Comment (AkihiroSuda) [inline pkg/plugins/discovery_unix.go:16]: Shouldn't this be {`$XDG_CONFIG_HOME/docker/plugins`, `$HOME/.local/lib/docker/plugins`} ?

Comment (jg-public) [reply pkg/plugins/discovery_unix.go]: Yes, I changed the returned paths to your suggestion.
I additionally made the fallback (if the corresponding environment variable is not set) more explicit in the comment.

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Comment by jg-public** [comment]
See https://github.com/moby/moby/actions/runs/3828112441/jobs/6514666086

> These files import internal code: (either directly or indirectly)
> - pkg/plugins/discovery_unix.go imports github.com/docker/docker/rootless

Code in `./pkg/*` is not allowed to reference code not in `./pkg/*`.  
I suggest to move the directory `./rootless` to `./pkg/rootless`.   
What do you think?

**Comment by AkihiroSuda** [comment]
>  ./rootless to ./pkg/rootless

SGTM

File: pkg/plugins/discovery_unix.go [hunk 3]
```diff
@@ -2,5 +2,43 @@
...
+import (
+	"github.com/docker/docker/pkg/homedir"
+	"github.com/docker/docker/rootless"
+	"path/filepath"
+)
 
-var specsPaths = []string{"/etc/docker/plugins", "/usr/lib/docker/plugins"}
+var globalConfigPluginsPath = "/etc/docker/plugins"
+var globalLibPluginsPath = "/usr/lib/docker/plugins"
+var specsPaths = []string{globalConfigPluginsPath, globalLibPluginsPath}
```
Comment (vvoland) [inline pkg/plugins/discovery_unix.go:13]: Could we make those `const` instead of `var`?

**Review by AkihiroSuda — APPROVED** [review]

**Review by neersighted — CHANGES_REQUESTED** [review]
Slightly tangential to this PR, but I wonder if the `homedir` package should fall back to the starting directory from the passwd if `HOME` is not found in the environment. Comparison to other tools (e.g. Git, GnuPG, other well-known Unix software) would be interesting.

**Review by vvoland — APPROVED** [review]

**Comment by jg-public** [comment]
> Slightly tangential to this PR, but I wonder if the `homedir` package should fall back to the starting directory from the passwd if `HOME` is not found in the environment. Comparison to other tools (e.g. Git, GnuPG, other well-known Unix software) would be interesting.

* Git falls back to `pw_dir`: [XX](https://github.com/git/git/blob/319605f8f00e402f3ea758a02c63534ff800a711/path.c#L758)
* GnuPG falls back to `pw_dir`: https://github.com/gpg/gnupg/blob/283ccbc824d8062b86e27818a84ab5a29facd7a5/common/stringhelp.c#L478

Doing so too is a good idea :+1: but I would not change this behavior in this PR

---

Checks fail because checks fail in the `master` too.
Is there anything I can do now to move this PR forward?

**Comment by neersighted** [comment]
The failed check on master is a Jenkins/ARM flake; the failure here is because of a stale branch. Please rebase onto master.

I'm ready to give this a LGTM; I have two slight objections but I believe they can be follow-ups if you are willing:
* I'd like to see the `pw_dir` fallback.
* I'd like to explore dropping the `globalSpecPaths` and instead inject a function that returns paths into the `registry` object.

**Review by neersighted — APPROVED** [review]

**Comment by jg-public** [comment]
Thank you, I rebased the branch as requested.

I'll create two follow-up PRs for
1. the `pw_dir` fallback
2. replace `globalSpecPaths` by a function in `LocalRegistry`

**Comment by neersighted** [comment]
@AkihiroSuda I see you added the cherry-pick label; I'm assuming you think we should include this in the 23.0 branch, but not the 20.10 branch?

**Comment by AkihiroSuda** [comment]
> @AkihiroSuda I see you added the cherry-pick label; I'm assuming you think we should include this in the 23.0 branch, but not the 20.10 branch?

Yes
