### PR TITLE
Windows: Set default directory

### LINKED ISSUE #22105: Windows default WORKDIR and COPY
1. With no WorkingDir defined, the default working dir for bare `windowsservercore` is `c:\windows\system32` (seems reasonable)
2. `COPY`, when given a relative destination should copy into the working dir, but on windows it seems to fall back to using `c:\`

Is this the intended behavior?

**Output of `docker version`:**

```
 docker version
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.11.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   577adcc
 Built:        Mon Apr 11 17:20:50 2016
 OS/Arch:      windows/amd64```
```

**Output of `docker info`:**

```
docker info
Containers: 70
 Running: 1
 Paused: 0
 Stopped: 69
Images: 104
Server Version: 1.11.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null
Kernel Version: 10.0 14316 (14316.1000.amd64fre.rs1_release.160402-2217)
Operating System: Windows Server 2016 Datacenter Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 1.24 GiB
Name: WIN-8F5EG07ROBB
ID: VKYM:E5F7:CMIT:4ZMS:OGUG:W43U:API4:ATWI:3S5X:RO54:DU4Q:YOFD
Docker Root Dir: C:\ProgramData\docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: -1
 Goroutines: 31
 System Time: 2016-04-17T11:32:41.8625223-07:00
 EventsListeners: 0
Username: friism4test
Registry: https://index.docker.io/v1/

```

**Steps to reproduce the issue:**

```
C:\code\repros\build-path-strangeness> ls testfile


    Directory: C:\code\repros\build-path-strangeness


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        4/16/2016   7:05 PM              0 testfile


C:\code\repros\build-path-strangeness> cat .\Dockerfile.experiment
FROM windowsservercore

RUN echo %CD%

COPY testfile .

RUN dir "c:\"

RUN echo hi
C:\code\repros\build-path-strangeness> docker build --no-cache -f .\Dockerfile.experiment -t test .
Sending build context to Docker daemon  2.56 kB
Step 1 : FROM windowsservercore
 ---> e1e5fb4dbc32
Step 2 : RUN echo %CD%
 ---> Running in 2a6611bb705c
C:\Windows\system32
 ---> fa4b5c7def12
Removing intermediate container 2a6611bb705c
Step 3 : COPY testfile .
 ---> 5b3787987373
Removing intermediate container 9b6dba28c47f
Step 4 : RUN dir "c:\"
 ---> Running in 9c86dbd42704
 Volume in drive C has no label.
 Volume Serial Number is 2AFE-D179

 Directory of c:\

04/03/2016  12:31 PM    <DIR>          inetpub
04/03/2016  10:39 AM    <DIR>          PerfLogs
04/17/2016  11:33 AM    <DIR>          Program Files
04/03/2016  10:40 AM    <DIR>          Program Files (x86)
04/16/2016  07:05 PM               (0) testfile
04/17/2016  11:33 AM    <DIR>          Users
04/17/2016  11:33 AM    <DIR>          Windows
               1 File(s)              0 bytes
               6 Dir(s)  21,259,214,848 bytes free
 ---> ed240a061083
Removing intermediate container 9c86dbd42704
Step 5 : RUN echo hi
 ---> Running in c42bc51bbab5
hi
 ---> 4671ab356512
Removing intermediate container c42bc51bbab5
Successfully built 4671ab356512
C:\code\repros\build-path-strangeness> docker inspect test | grep WorkingDir
            "WorkingDir": "",
            "WorkingDir": "",
C:\code\repros\build-path-strangeness>

```

**Describe the results you received:**

File copied to `.` is placed in `c:\`

**Describe the results you expected:**

File is copied to `c:\windows\system32` which appears to be default working dir.

cc @jhowardmsft

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

Fixes #22105.  Sets the default directory to c:\ in a Windows container in the absence of a working directory explicitly specified. This makes Windows consistent with Linux, and makes COPY file . clearer as noted in in 22105. @friism

### CODE REVIEW

**Comment by friism** [comment]
Thanks @jhowardmsft !

File: daemon/oci_windows.go [hunk 1]
```diff
@@ -55,7 +55,18 @@ func (daemon *Daemon) createSpec(c *container.Container) (*libcontainerd.Spec, e
...
+	if c.Config.WorkingDir == "" {
+		// We default to c:\ to workaround the oddity of the case that the
+		// default directory for cmd running as LocalSystem (or
+		// ContainerAdministrator) is c:\windows\system32. Hence docker run
+		// <image> cmd will by default end in c:\windows\system32, rather
+		// than 'root' (/) on Linux. The oddity is that if you have a dockerfile
+		// which has no WORKDIR and has a COPY file ., . will be interpreted
+		// as c:\. Hence, setting it to default of c:\ makes for consistency.
+		s.Process.Cwd = `c:\`
+	} else {
```
Comment (cpuguy83) [inline daemon/oci_windows.go]: Can we avoid the else and instead do:

```go
s.Process.Cwd = c.Config.WorkingDir
if len(s.Process.Cwd) == 0 {
    s.Process.Cwd = `c:\`
}
```

Comment (jhowardmsft) [inline daemon/oci_windows.go]: Sure. Updated.

**Comment by thaJeztah** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM
