### PR TITLE
Removed unnecessary error output from dockerCmd

### LINKED ISSUE #12355: integration-cli dockerCmd function doesn't return error
In `integration-cli/docker_utils.go` is a function used in many many places in the integration-cli tests called `dockerCmd`.

This functions signature is: `func dockerCmd(t *testing.T, args ...string) (string, int, error)`
However, `error` is never returned since it fails out the test with: `t.Fatalf("%q failed with errors: %s, %v", strings.Join(args, " "), out, err)` if there is an error.

Then any code calling this function is also doing a redundant check for this non-existent error.

The error from the return on `dockerCmd` should be removed and all calling code updated to reflect that.

### PR DESCRIPTION
**Pull request by robertabbott**
Changed method declaration. Fixed all calls to dockerCmd
method to reflect the change.

resolves #12355

Signed-off-by: bobby abbott ttobbaybbob@gmail.com

### CODE REVIEW

File: integration-cli/docker_cli_run_unix_test.go [hunk 1]
```diff
@@ -178,26 +178,26 @@ func TestRunContainerWithCgroupParentAbsPath(t *testing.T) {
 func TestRunDeviceDirectory(t *testing.T) {
 	testRequires(t, NativeExecDriver)
 	defer deleteAllContainers()
-	cmd := exec.Command(dockerBinary, "run", "--device", "/dev/snd:/dev/snd", "busybox", "sh", "-c", "ls /dev/snd/")
+	cmd := exec.Command(dockerBinary, "run", "--device", "/dev/:/dev/", "busybox", "sh", "-c", "ls /dev/")
```
Comment (cpuguy83) [inline integration-cli/docker_cli_run_unix_test.go]: How come you changed this one?

**Comment by cpuguy83** [comment]
Not sure why `TestRunDeviceDirectory` was changed, but all else looks good.
Can we get that test reverted?

File: integration-cli/docker_cli_run_unix_test.go (hunk 1 above)
Comment (robertabbott) [inline integration-cli/docker_cli_run_unix_test.go]: Changing dockerCmd broke this test. Even having dockerCmd return err = nil caused the test to stop working. I was getting an error saying /dev/snd did not exist. I couldn't figure out why changing dockerCmd was causing that behavior, so I changed the test. If it is not imperative snd be the mounted device it would be easier to not revert the test (or to use a different device that 'exists').

Comment (cpuguy83) [inline integration-cli/docker_cli_run_unix_test.go]: I think this is testing that a dir of devices are being loaded, which is what is what `/dev/snd` is.

Comment (robertabbott) [inline integration-cli/docker_cli_run_unix_test.go]: So it would acceptable if I found something another dir in /dev and checked if the contents of that dir are mounted properly? Also do you have any idea why /dev/snd stopped showing up?

Comment (cpuguy83) [inline integration-cli/docker_cli_run_unix_test.go]: Does your test env not have a `/dev/snd`?

Comment (robertabbott) [inline integration-cli/docker_cli_run_unix_test.go]: My dev-vm doesn't. However when I checkout master and rerun the tests they worked, so I didn't think it was my environment. If that's the issue I can just revert the test and it should be fine.

**Comment by robertabbott** [comment]
Reverted TestRunDeviceDirectory, apparently it was an issue with my environment. It should be good to go now.

File: integration-cli/docker_cli_cp_test.go [hunk 2]
```diff
@@ -595,27 +561,24 @@ func TestCpToDot(t *testing.T) {
...
+	out, _ = dockerCmd(t, "wait", cID)
+	if strings.TrimSpace(out) != "0" {
+		t.Fatalf("failed to set up container:%s\n", out)
 	}
 
-	out, _, err = runCommandPipelineWithOutput(
+	out, _, err := runCommandPipelineWithOutput(
 		exec.Command(dockerBinary, "cp", cID+":/test", "-"),
 		exec.Command("tar", "-vtf", "-"))
-	if err != nil {
```
Comment (duglin) [inline integration-cli/docker_cli_cp_test.go]: Why did you get rid of this? Don't we want to show the err if its available?

Comment (cpuguy83) [inline integration-cli/docker_cli_cp_test.go]: It's inline with the strings test.

Comment (robertabbott) [inline integration-cli/docker_cli_cp_test.go]: I moved it down a line. It make sense to show the error, I will revert this.

Comment (duglin) [inline integration-cli/docker_cli_cp_test.go]: the check was inline but it wasn't part of the print

**Comment by estesp** [comment]
LGTM

**Comment by icecrime** [comment]
Oh cool, LGTM!

**Comment by thaJeztah** [comment]
sweet! thanks
