### PR TITLE
Don't log EINVAL when unmount IPC

### LINKED ISSUE #33328: WARN[0001] failed to cleanup ipc mounts
**Description**

**Steps to reproduce the issue:**
See #17550
Looks like the patch doesn't fix the problem or we have a regression.

**Describe the results you received:**
```
WARN[0001] failed to cleanup ipc mounts:
failed to umount /var/lib/docker/containers/782bb68ccae1df58c864c6797d0a8a586e4619296326bd31f4a5053061426514/shm: invalid argument 
```
**Describe the results you expected:**
Don't log the warning, since it's not an issue.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
17.06.0-dev
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by wenjianhn**
EINVAL means that the target exists but it is not (yet) a mount point.
See umount2(2).

On freebsd, following errors also lead to EINVAL.
1. The file system ID specified using MNT_BYFSID could not be decoded.
2. the specified file system is the root file system.
We don't need to handle them in UnmountIpcMounts.

Fix #33328

Signed-off-by: Jacob Wen <jian.w.wen@oracle.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: container/container_unix.go [hunk 1]
```diff
@@ -219,7 +219,7 @@ func (container *Container) UnmountIpcMounts(unmount func(pth string) error) {
 			logrus.Error(err)
 			warnings = append(warnings, err.Error())
 		} else if shmPath != "" {
-			if err := unmount(shmPath); err != nil && !os.IsNotExist(err) {
+			if err := unmount(shmPath); err != nil && !os.IsNotExist(err) && err != unix.EINVAL {
```
Comment (cpuguy83) [inline container/container_unix.go]: how about something like:
```go
if err := unmount(shmPath); err != nil && !os.IsNotExist(err) {
    mounted, _ := mount.Mounted(shmPath); mounted {
        // append warning
    }
}
```

Comment (wenjianhn) [inline container/container_unix.go]: On Linux, EINVAL may mean that umount2() was called with an invalid flag value in flags.
We need to use Mounted.

File: container/container_unix.go [hunk 2]
```diff
@@ -220,7 +221,9 @@ func (container *Container) UnmountIpcMounts(unmount func(pth string) error) {
 			warnings = append(warnings, err.Error())
 		} else if shmPath != "" {
 			if err := unmount(shmPath); err != nil && !os.IsNotExist(err) {
-				warnings = append(warnings, fmt.Sprintf("failed to umount %s: %v", shmPath, err))
+				if mounted, _ := mount.Mounted(shmPath); mounted {
```
Comment (cpuguy83) [inline container/container_unix.go]: Sorry we may want to go ahead and read this error like
```go
if mounted, mErr := ...; mounted || mErr != nil {
    // append err
}
```

Comment (thaJeztah) [inline container/container_unix.go]: @wenjianhn can you address this comment?

Comment (wenjianhn) [inline container/container_unix.go]: @cpuguy83 @thaJeztah Done. Thanks.

File: container/container_unix.go [hunk 3]
```diff
@@ -220,7 +221,9 @@ func (container *Container) UnmountIpcMounts(unmount func(pth string) error) {
 			warnings = append(warnings, err.Error())
 		} else if shmPath != "" {
 			if err := unmount(shmPath); err != nil && !os.IsNotExist(err) {
-				warnings = append(warnings, fmt.Sprintf("failed to umount %s: %v", shmPath, err))
+				if mounted, mErr := mount.Mounted(shmPath); mounted || mErr != nil {
```
Comment (thaJeztah) [inline container/container_unix.go]: @cpuguy83 looks like this is now doing the same as [`mount.Unmount()`](https://github.com/moby/moby/blob/54dcbab25ea4771da303fa95e0c26f2d39487b49/pkg/mount/mount.go#L53-L60), only in reverse order (first try `syscall.Unmount()`, then check if it was mounted - I assume that's a performance optimisation) - should we move that optimisation in `mount.Unmount()` and use it here?

It looks like the `unmount` argument for `UnmountIpcMounts()` is not really needed anymore (it looks like it was was added in https://github.com/moby/moby/commit/78bd17e805b7514505455b10f2fd90962505a3ff to allow different unmount methods in different parts of the code)

Comment (cpuguy83) [inline container/container_unix.go]: It's really different since we're only checking if it's mounted if the unmount failed, vs only trying to unmount if it is mounted. Checking if it's mounted first is racey... and I wouldn't be surprised if it's technically slower to do it that way.

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Flaky test on experimental?

```
09:43:09 ----------------------------------------------------------------------
09:43:09 FAIL: docker_cli_stack_test.go:59: DockerSwarmSuite.TestStackDeployComposeFile
09:43:09 
09:43:09 [d35123665fb88] waiting for daemon to start
09:43:09 [d35123665fb88] daemon started
09:43:09 
09:43:09 docker_cli_stack_test.go:76:
09:43:09     c.Assert(err, checker.IsNil)
09:43:09 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc420543b00), Stderr:[]uint8(nil)} ("exit status 1")
09:43:09 
09:43:09 [d35123665fb88] exiting daemon
09:43:11 
```

**Review by thaJeztah — APPROVED** [review]
LGTM - we can discuss / look into the optimisation separate from this PR

**Comment by kolyshkin** [comment]
Instead of parsing the whole `/proc/self/mountinfo` we should just ignore EINVAL (same as pkg/mount's `Unmount()` does). Will send a PR soon.

**Comment by kolyshkin** [comment]
The other reasons for `EINVAL` (in Linux) are bad value for flags. Since flags are hardcoded to be `MNT_DETACH` (which is supported since Linux 2.4.11, i.e. forever), there is zero chance it will happen.

**Comment by thaJeztah** [comment]
Gotcha, thanks!

**Comment by kolyshkin** [comment]
There are many other places (in particular, `Unmount()` implementation in pkg/mount) which do the same. Parsing /proc/self/mountinfo is relatively expensive (more so when you have many containers), so if we are sure we are passing the right flags, it's much better to ignore `EINVAL`, assuming it only means "not mounted".
