### PR TITLE
Recover from default bridge init failure

### LINKED ISSUE #49291: Error initializing Docker network controller: Conflict with existing bridge network docker0
### Description

- re-raised from https://github.com/docker/for-linux/issues/1512
- originally reported by @poqdavid

---

I'm encountering an issue with Docker on my Linux server where the Docker daemon fails to start due to a network conflict involving the default `docker0` bridge network. And I would appreciate it if anyone can help me figure out this problem.
Below are the details from the logs:

```
Dec 18 03:48:16 server dockerd[2720]: failed to start daemon: Error initializing network controller: error creating default "bridge" network: cannot create network e6df46e3462f284f46bb95fe8bdfa5530dfb1451b2859e886896fcecffe0f00a (docker0): conflicts with network 34958e77236c09db2c3cbe6198a3eb085736a648650638a1295480847abcf4b6 (docker0): networks have same bridge name
```

Here is the full log: [docker_log1.log](https://github.com/user-attachments/files/18190994/docker_log1.log)
Also my firewall log: [firewalld_log1.log](https://github.com/user-attachments/files/18191042/firewalld_log1.log)

**Steps to Reproduce:**
1. Start the Docker service on the affected system.
2. Observe that the daemon fails to start and the error above is logged.

**Temporary Fix:**
As a temporary workaround, I can resolve the issue by running the following commands:
```bash
rm -rf /var/lib/docker/network
systemctl restart docker
```
However, this fix is not permanent, and the issue reoccurs after some time.

**System Details:**
- Docker version: `27.4.1, build b9d17ea`
- Linux distribution: `Ubuntu 24.04.1 LTS`
- Kernel version: `6.8.0-51-generic x86_64`
- Firewall: `Firewalld 2.1.1 with nftables v1.0.9 (Old Doc Yak #3)`

**Update 1:**
After testing, a few things I noticed delaying the startup for the service fixes the problem but I am not completely sure if its a proper fix or not
```
[Unit]
PartOf=firewalld.service

[Service]
ExecStartPre=/bin/sleep 3
Restart=no
```

### PR DESCRIPTION
**Pull request by robmry**
**- What I did**

- fix https://github.com/moby/moby/issues/49291

If a bridge network can't be restored from the store on startup, then it's deleted, the daemon and bridge driver get out of step. If that happens to the default bridge, the daemon can't recover, it won't start again.

See the issue for more detailed description/analysis.

_The ipvlan/macvlan/overlay network drivers don't seem to be affected by an equivalent issue._

_This is a very long standing issue, but perhaps provoked by the checks on kernel module loading added in 27.x. (The version label on the PR is arbitrary, just something-old.)_

**- How I did it**

When deleting a network the bridge driver doesn't know about, make sure it's not still lurking in the data store.

**- How to verify it**

New tests.

**- Description for the changelog**
```markdown changelog
- Fixed an issue that could persistently prevent daemon startup after failure to initialize the default bridge.
```

### CODE REVIEW

File: testutil/daemon/daemon.go [hunk 1]
```diff
@@ -842,6 +843,17 @@ func (d *Daemon) ReloadConfig() error {
...
+// SetEnvVar updates the set of extra env variables for the daemon, to take
+// effect on the next start/restart.
+func (d *Daemon) SetEnvVar(name, val string) {
+	prefix := name + "="
+	if idx := slices.IndexFunc(d.extraEnv, func(ev string) bool { return strings.HasPrefix(ev, prefix) }); idx > 0 {
+		d.extraEnv[idx] = prefix + val
+		return
+	}
+	d.extraEnv = append(d.extraEnv, prefix+val)
+}
```
Comment (thaJeztah) [inline testutil/daemon/daemon.go:855]: This looks sane for now, but I went looking "didn't we already  have an options for this?", but that can only be used on `daemon.New()`;

```go
d := daemon.New(t, daemon.WithEnvVars(...)
```


and `daemon.Start()` doesn't take options as argument; perhaps we should consider making it accept Options, so that we can customise (some at least) daemon settings between restarts without having to create a new daemon.

Or perhaps a `StartWithOptions()` if we don't want  to replace the existing one (which takes  command-line arguments only)

**Review by thaJeztah — APPROVED** [review]
LGTM
