### PR TITLE
Docker inspect "AppArmorProfile" field now shows "docker-default" when AppArmor is enabled and no other profile was defined 

### LINKED ISSUE #25935: docker inspect contains no indication of default AppArmor profile
Docker is setting the default AppArmor profile, but `docker inspect` claims otherwise:

```
$ docker inspect container
[
    {
        ...
        "AppArmorProfile": "",
        "SecurityOpt": [],
        "State": {
            "Pid": 14235,
            ...
        }
        ...
    }
]
$ sudo aa-status
...
18 processes are in enforce mode.
     ...
     docker-default (14235)
```

If I explicitly set the default with `--security-opt apparmor:docker-default`, then `docker inspect` is correct.

**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 13
 Running: 10
 Paused: 0
 Stopped: 3
Images: 14
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 127
 Dirperm1 Supported: true
Logging Driver: awslogs
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.795 GiB
Name: moon-04643584d28c0ac31
ID: TWQW:NLZA:6TPG:DWU6:3MJZ:OETI:VE67:D5M4:6JWY:I2HJ:PCYQ:NB7T
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS

**Steps to reproduce the issue:**
1. Run a container on an AppArmor enabled host, without specifying a profile.
2. Run docker inspect and compare to aa-status

**Describe the results you received:**
`docker inspect` does not include information about AppArmor profiles if the default profile is applied by docker.

**Describe the results you expected:**
`docker inspect` should always include the AppArmor profile, even if it's just the default.

**Additional information you deem important (e.g. issue happens only occasionally):**

### PR DESCRIPTION
**Pull request by RobSkye**
This pull request fixes #25935 showing "AppArmorProfile" in docker inspect filled with "docker-default" when AppArmor is enabled and no other profile was defined using --security-opt.

### CODE REVIEW

**Comment by thaJeztah** [comment]
@RobSkye did you close this on purpose, or by accident?

**Comment by RobSkye** [comment]
By Accident...laptops and beds are bad combination....I'm editing the description too.

**Comment by thaJeztah** [comment]
GitHub buttons are also a disaster at times, haha, no worries, thanks!

**Comment by thaJeztah** [comment]
Guess this fixes https://github.com/docker/docker/issues/25935

**Comment by RobSkye** [comment]
Yes.

File: daemon/container_linux.go [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+)
+
+func (daemon *Daemon) setSecurityOptions(container *container.Container, hostConfig *containertypes.HostConfig) error {
+	container.Lock()
+	defer container.Unlock()
+	if err := parseSecurityOpt(container, hostConfig); err != nil {
+		return err
+	}
+	if daemon.apparmorEnabled && container.AppArmorProfile == "" {
+		container.AppArmorProfile = "docker-default"
```
Comment (tonistiigi) [inline daemon/container_linux.go]: Also need to handle `--privileged`. See https://github.com/docker/docker/blob/master/daemon/oci_linux.go#L709-L714

Even with `privileged` fixed this is a slight behavioral change. If apparmor is enabled after container was created this var will not change. I think if this is only called on inspecting single container we can lazy load the value like we do in container startup.

**Review by tonistiigi — COMMENTED** [review]
Please squash the commits as well.

**Comment by thaJeztah** [comment]
@RobSkye can you address @tonistiigi's comments, and squash your commits?

**Comment by RobSkye** [comment]
With the latest push, if you change apparmor configuration and apparmor completely disappear from the dockerhost (I have some comments about this below) the AppArmorProfile is updated with the expected configuration but still there is some issues we have to address:

1. If you do an inspect after an apparmor change and before the start of the container, still shows the old AppArmorProfile.
2. If you create the container with apparmor disabled but with --security-opt apparmor=someprofile, when you enable apparmor in dockerhost, AppArmorProfile will be "docker-default".
3. Apparmor status is checked ONLY checking the existence of /sys/kernel/security/apparmor and is not a good method, you can have apparmor completely shutdown and still that directory exists. see https://github.com/docker/docker/blob/master/pkg/sysinfo/sysinfo_linux.go#L57
4. You can run a container with --security-opt apparmor=someprofile and someprofile will be set in AppArmorProfile whether or not exists as an valid apparmor profile.

I don't know if addressing this issues are in the scope of the main issue. I' have the feeling that implementing a real-time check of the security configuration of containers will require more than a "slight behavioral change". 

I have some ideas of adding security information in the "docker ps" command and a more detailed "docker security" showing all the security settings of a container.

I look forward to your feedback.

File: daemon/container_linux.go [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+	} else {
+		container.AppArmorProfile = "unconfined"
+	}
+	return nil
+}
+
+func (daemon *Daemon) fixSecurityOptions(container *container.Container) {
+	if daemon.apparmorEnabled && !container.HostConfig.Privileged {
+		if container.AppArmorProfile == "unconfined" {
+			container.AppArmorProfile = defaultApparmorProfile
```
Comment (tonistiigi) [inline daemon/container_linux.go]: Don't understand this. Why is unconfined profile switched back to default.

Comment (RobSkye) [inline daemon/container_linux.go]: That is actually an error. I was trying to restore "docker-default" to the unconfined containers if the containers were created after apparmor was enabled but i didn't notice the effect of enabling apparmor to the containers with --security-opt app-armor:unconfined.

I'm gonna think on how manage this correctly.

**Comment by RobSkye** [comment]
I did a little refactor of the patch in the last commit. Now inspect always shows an empty AppArmorProfile when the container is stopped ( maybe empty is not the best value but this can be changed easily to undefined, unconfined or something more clarifying).

The correct value of AppArmorProfile is set at container startup using the actual status of apparmor, the privileged flag and the configured apparmor settings using --security-opt.

**Comment by LK4D4** [comment]
@RobSkye I'm not sure that I like an idea of clearing profile on stopped containers - it's breaking change, and indeed it might be useful for debugging. Otherwise, the patch is ok for me.

**Comment by mlaventure** [comment]
ping @RobSkye , needs a rebase.

I personally don't think showing the previous apparmor profile when inspecting old containers is an issue to be fixed otherwise. It properly reflect how this container was run.

**Comment by RobSkye** [comment]
Ok, i'll delete that part and rebase/commit.

**Comment by thaJeztah** [comment]
ping @tonistiigi @LK4D4 PTAL what's the status on this one?

File: daemon/container_linux.go [hunk 3]
```diff
@@ -0,0 +1,22 @@
+//+build !windows
+
+package daemon
+
+import (
+	"github.com/docker/docker/container"
+)
+
+func (daemon *Daemon) fixSecurityOptions(container *container.Container) error {
```
Comment (tonistiigi) [inline daemon/container_linux.go]: I'd call this `saveApparmorConfig`

File: daemon/container_linux.go [hunk 4]
```diff
@@ -0,0 +1,22 @@
...
+	container.AppArmorProfile = "" //we don't care about the previous value.
+	if err := parseSecurityOpt(container, container.HostConfig); err != nil {
+		return err
+	}
+	if daemon.apparmorEnabled && !container.HostConfig.Privileged {
```
Comment (tonistiigi) [inline daemon/container_linux.go]: This shows `unconfined` when apparmor is disabled.

**Review by tonistiigi — CHANGES_REQUESTED** [review]

File: daemon/container_linux.go (hunk 4 above)
Comment (RobSkye) [inline daemon/container_linux.go]: Yes, do you want to show "Disabled" instead?

Comment (tonistiigi) [inline daemon/container_linux.go]: I think empty would do. `unconfined` implies that special privileged profile was applied(at least to me).

**Comment by LK4D4** [comment]
ping @RobSkye 
Would you mind to fix Tonis' comments? Then we can merge

**Comment by LK4D4** [comment]
LGTM
ping @tonistiigi

**Review by LK4D4 — APPROVED** [review]

**Review by tonistiigi — APPROVED** [review]
LGTM
