### PR TITLE
Fix issues with tailing rotated jsonlog file

### LINKED ISSUE #21220: Streaming logs, json driver "Error streaming logs: unexpected EOF"
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 165
 Running: 147
 Paused: 0
 Stopped: 18
Images: 293
Server Version: 1.10.3
Storage Driver: btrfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.2.0-34-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 31.42 GiB
Name: <edited>
ID: AZNH:RYE6:EPU2:OM3H:RQGL:E6GL:3PCA:BJJP:JVQO:ILYS:G7B4:TWOZ
Username: <edited>
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
 
physical server

**Steps to reproduce the issue:**
1. Container configuration:

```js
            "LogConfig": {
                "Type": "json-file",
                "Config": {
                    "max-file": "1",
                    "max-size": "1m"
                }
            },
```

2. Run a container with a lot of output
3. Wait

**Describe the results you received:**

Docker daemon logs:

```
time="2016-03-15T18:13:29.573092612+01:00" level=error msg="Error streaming logs: unexpected EOF"
```

**Describe the results you expected:**

No error

I assume it's when the 1M buffer is full. But accoding to the docs it's a rolling buffer isn't it ?

### LINKED ISSUE #23913: BUG REPORT: docker logs follow gets stuck when the json-file log driver rotates files
**Output of `docker version`:**

```
Docker version 1.11.2, build b9f10c9
```

**Output of `docker info`:**

```
Containers: 5
 Running: 4
 Paused: 0
 Stopped: 1
Images: 8
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 63
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-24-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.795 GiB
Name: ip-10-47-10-249
ID: VVQ3:QEHD:WM5H:SY6Q:Y43P:MFQ6:BZ5Z:GO2M:YZ5Y:VQ5P:FSXW:JFDE
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Reproduced on Ubuntu 15.10, 16.04 EC2 instances. Reproduced on Ubuntu 14.04 docker-machine VM on my laptop. All tests were performed at a terminal in an SSH session connecting to a local docker daemon.

**Steps to reproduce the issue:**
1. To demonstrate the issue, Configure the Docker daemon to use the `json-file` log driver with a max-size of 10mb.
Mine looks like:
```bash
$ cat /etc/systemd/system/docker.service.d/docker-opts.conf
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon -H fd:// -s aufs --bip=192.168.255.1/24 --log-driver="json-file" --log-opt max-size=10m --log-opt max-file=5
```

1. Attempt to print the numbers 1 to 200000 to the stdout of a container and use `docker logs` to follow the output by running the following command:
```bash
$ docker run -d --name loggen ubuntu:16.04 /bin/bash -c 'for ((i=1; i<=200000; ++i)); do echo $i; done' && docker logs --timestamps --follow loggen > boom.txt
71943ba916fb365fb3178ab9dabd37158d690b49aeaa595420fde4f92b62256a
```

**Describe the results you received:**
I would expect to see the numbers 1 to 200000 along with the time each number was output by the `loggen` container in `boom.txt`

What I actually see:
```bash
$ tail boom.txt
2016-06-17T06:39:55.123832147Z 131491
2016-06-17T06:39:55.123837123Z 131492
2016-06-17T06:39:55.123842067Z 131493
2016-06-17T06:39:55.123846929Z 131494
2016-06-17T06:39:55.123851785Z 131495
2016-06-17T06:39:55.123856759Z 131496
2016-06-17T06:39:55.123861681Z 131497
2016-06-17T06:39:55.123866606Z 131498
2016-06-17T06:39:55.123871552Z 131499
2016-06-17T06:39:55.123876490Z 131500
```

Looking at the files generated by the json-file log driver for this container shows that things have gone wrong when the docker log driver rotates the json files.

```
$ sudo -s
$ ls /var/lib/docker/containers/71943ba916fb365fb3178ab9dabd37158d690b49aeaa595420fde4f92b62256a/*.log*
/var/lib/docker/containers/71943ba916fb365fb3178ab9dabd37158d690b49aeaa595420fde4f92b62256a/71943ba916fb365fb3178ab9dabd37158d690b49aeaa595420fde4f92b62256a-json.log
/var/lib/docker/containers/71943ba916fb365fb3178ab9dabd37158d690b49aeaa595420fde4f92b62256a/71943ba916fb365fb3178ab9dabd37158d690b49aeaa595420fde4f92b62256a-json.log.1
$ tail /var/lib/docker/containers/71943ba916fb365fb3178ab9dabd37158d690b49aeaa595420fde4f92b62256a/71943ba916fb365fb3178ab9dabd37158d690b49aeaa595420fde4f92b62256a-json.log.1
{"log":"131491\n","stream":"stdout","time":"2016-06-17T06:39:55.123832147Z"}
{"log":"131492\n","stream":"stdout","time":"2016-06-17T06:39:55.123837123Z"}
{"log":"131493\n","stream":"stdout","time":"2016-06-17T06:39:55.123842067Z"}
{"log":"131494\n","stream":"stdout","time":"2016-06-17T06:39:55.123846929Z"}
{"log":"131495\n","stream":"stdout","time":"2016-06-17T06:39:55.123851785Z"}
{"log":"131496\n","stream":"stdout","time":"2016-06-17T06:39:55.123856759Z"}
{"log":"131497\n","stream":"stdout","time":"2016-06-17T06:39:55.123861681Z"}
{"log":"131498\n","stream":"stdout","time":"2016-06-17T06:39:55.123866606Z"}
{"log":"131499\n","stream":"stdout","time":"2016-06-17T06:39:55.123871552Z"}
{"log":"131500\n","stream":"stdout","time":"2016-06-17T06:39:55.12387649Z"}
$ head -n 10 /var/lib/docker/containers/71943ba916fb365fb3178ab9dabd37158d690b49aeaa595420fde4f92b62256a/71943ba916fb365fb3178ab9dabd37158d690b49aeaa595420fde4f92b62256a-json.log
{"log":"131501\n","stream":"stdout","time":"2016-06-17T06:39:55.123881404Z"}
{"log":"131502\n","stream":"stdout","time":"2016-06-17T06:39:55.123994259Z"}
{"log":"131503\n","stream":"stdout","time":"2016-06-17T06:39:55.124001593Z"}
{"log":"131504\n","stream":"stdout","time":"2016-06-17T06:39:55.124006555Z"}
{"log":"131505\n","stream":"stdout","time":"2016-06-17T06:39:55.124011382Z"}
{"log":"131506\n","stream":"stdout","time":"2016-06-17T06:39:55.124016163Z"}
{"log":"131507\n","stream":"stdout","time":"2016-06-17T06:39:55.124020854Z"}
{"log":"131508\n","stream":"stdout","time":"2016-06-17T06:39:55.12402562Z"}
{"log":"131509\n","stream":"stdout","time":"2016-06-17T06:39:55.124030396Z"}
{"log":"131510\n","stream":"stdout","time":"2016-06-17T06:39:55.12403511Z"}
```

**Describe the results you expected:**
I would expect to see the numbers 1 to 200000 along with the time each number was output by the `loggen` container in `boom.txt`

**Additional information you deem important (e.g. issue happens only occasionally):**
I did a little more digging and found an upper bound on the `--log-opt max-size` where the `docker logs --follow` was not broken by rotating the json log files.
When max-size is <= 215k, `docker logs --follow` behaves as expected.
When max-size is >= 216k, `docker logs --follow` gets stuck.

### PR DESCRIPTION
**Pull request by cpuguy83**
Fixes a race where the log reader would get events for both an actual
rotation and from fsnotify (`fsnotify.Rename`).
This issue becomes extremely apparent when rotations are fast, for
example:

```
$ docker run -d --name test --log-opt max-size=1 --log-opt max-file=2
busybox sh -c 'while true; do echo hello; usleep 100000; done'
```

With this change the log reader for jsonlogs can handle rotations that
happen as above.

Instead of listening for both fs events AND rotation events
simultaneously, potentially meaning we see 2 rotations for only a single
rotation due to channel buffering, only listen for fs events (like
`Rename`) and then wait to be notified about rotation by the logger.
This makes sure that we don't see 2 rotations for 1, and that we don't
start trying to read until the logger is actually ready for us to.

Fixes #21220
Fixes #23913

### CODE REVIEW

**Comment by paralin** [comment]
+1, fixed the issue for me on ARM64.

**Comment by LK4D4** [comment]
LGTM

**Comment by paralin** [comment]
Can this get merged? :P

**Comment by thaJeztah** [comment]
ping @tonistiigi @aaronlehmann PTAL

File: daemon/logger/jsonfilelog/read.go [hunk 1]
```diff
@@ -44,6 +47,10 @@ func (l *JSONFileLogger) ReadLogs(config logger.ReadConfig) *logger.LogWatcher {
 func (l *JSONFileLogger) readLogs(logWatcher *logger.LogWatcher, config logger.ReadConfig) {
 	defer close(logWatcher.Msg)
 
+	// lock so the read stream doesn't get corrupted do to rotations or other log data written while we read
```
Comment (aaronlehmann) [inline daemon/logger/jsonfilelog/read.go]: "...due to rotations..."

File: daemon/logger/jsonfilelog/read.go [hunk 2]
```diff
@@ -128,92 +136,142 @@ func tailFile(f io.ReadSeeker, logWatcher *logger.LogWatcher, tail int, since ti
...
-					retries++
-					continue
+				return nil
+			}
+			return errRetry
+		case err := <-fileWatcher.Errors():
+			logrus.Debug("logger got error watching file: %v", err)
+			// Something happened, let's try and stay alive and create a new watcher
+			if retries <= 5 {
+				fileWatcher, err = watchFile(name)
```
Comment (aaronlehmann) [inline daemon/logger/jsonfilelog/read.go]: Isn't it necessary to close the old file watcher?

File: daemon/logger/jsonfilelog/read.go [hunk 3]
```diff
@@ -128,92 +136,142 @@ func tailFile(f io.ReadSeeker, logWatcher *logger.LogWatcher, tail int, since ti
...
+	errDone := errors.New("done")
+	waitRead := func() error {
+		select {
+		case e := <-fileWatcher.Events():
+			switch e.Op {
+			case fsnotify.Write:
+				dec = json.NewDecoder(f)
+				return nil
+			case fsnotify.Rename, fsnotify.Remove:
+				<-notifyRotate
```
Comment (aaronlehmann) [inline daemon/logger/jsonfilelog/read.go]: Should this be part of a `select` that also handles `<-logWatcher.WatchClose()` in order to avoid blocking forever if the log watcher is closed at this point?

Though I have to say I don't understand why the handling of `<-logWatcher.WatchClose()` below is immediately followed by `logWatcher.Msg <- msg`. Looking at the code in `ContainerLogs`, it seems like that function will never read from the `Msg` channel after calling `Close`.

Comment (cpuguy83) [inline daemon/logger/jsonfilelog/read.go]: It can't go there because then we run into issues with double notifications.
What I can do is select on `WatchClose()` here as well to make sure we don't block forever.

The reason why it tries to send messages after a close notifications comes down is because the daemon itself will call `Close()` on all registered log readers if the container is stopped. This attempts to deliver any remaining messages to the client.

Comment (aaronlehmann) [inline daemon/logger/jsonfilelog/read.go]: > What I can do is select on `WatchClose()` here as well to make sure we don't block forever.

Yes, this is what I had in mind.

Comment (cpuguy83) [inline daemon/logger/jsonfilelog/read.go]: Updated this. I chose not to handle sending remaining logs the happened from the rotate for now... probably not needed, but if we need it, we'll probably need to refactor this even more.

**Comment by cpuguy83** [comment]
ping @aaronlehmann

**Comment by aaronlehmann** [comment]
LGTM

**Comment by suchisubhra** [comment]
I am  having same problem.. I am  user master tag. is it available in master tag?

**Comment by cpuguy83** [comment]
@suchisubhra Yes, it is in master.
If you are experiencing a problem, please open an new issue with the details.

Thanks!
