### PR TITLE
fix "host-gateway-ip" label not set for builder workers

### LINKED ISSUE #2201: After Update to Docker 25.0.0 (buildx v0.12.1), host-gateway in build does not work anymore
### Description

When building an image with the parameter `--add-host=host.docker.internal:host-gateway`, the build is aborted with the following message:
```
ERROR: unable to derive the IP value for host-gateway: failed to parse host-gateway IP: <nil>
```

### Reproduce

1. `docker build --add-host=host.docker.internal:host-gateway .`

### Expected behavior

The docker build works.

### docker version

```bash
Client: Docker Engine - Community
 Version:           25.0.0
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        e758fe5
 Built:             Thu Jan 18 17:09:59 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.0
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       615dfdf
  Built:            Thu Jan 18 17:09:59 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.27
  GitCommit:        a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc:
  Version:          1.1.11
  GitCommit:        v1.1.11-0-g4bccb38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    25.0.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 3
  Running: 2
  Paused: 0
  Stopped: 1
 Images: 8
 Server Version: 25.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc version: v1.1.11-0-g4bccb38
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.15.133.1-microsoft-standard-WSL2
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 19.54GiB
 Name: w00s71
 ID: 82ae4f4e-4d2a-4ce8-94d9-43c43d29095a
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://localhost:8888
 HTTPS Proxy: http://localhost:8888
 No Proxy: localhost,127.0.0.1,.local
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://redacted/
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

### Additional Info

I rolled back to 24.0.7 and everything works again.
```
VERSION_STRING=5:24.0.7-1~debian.12~bookworm
sudo apt-get install docker-ce=$VERSION_STRING docker-ce-cli=$VERSION_STRING containerd.io docker-buildx-plugin docker-compose-plugin
```

### PR DESCRIPTION
**Pull request by thaJeztah**
- fixes https://github.com/docker/buildx/issues/2201
- relates to https://github.com/moby/moby/pull/45767
- relates to https://github.com/moby/moby/pull/43980

Commit 21e50b89c92666589780eba6f83ad0851d8e9235 added a label on the buildkit worker to advertise the host-gateway-ip. This option can be either set by the user in the daemon config, or otherwise defaults to the gateway-ip.

If no value is set by the user, discovery of the gateway-ip happens when initializing the network-controller (`NewDaemon`, `daemon.restore()`).

However d222bf097cd4c8121900c292f0f6ff243773c3c5 changed how we handle the daemon config. As a result, the `cli.Config` used when initializing the builder only holds configuration information form the daemon config (user-specified or defaults), but is not updated with information set by `NewDaemon`.

This patch adds an accessor on the daemon to get the current daemon config. An alternative could be to return the config by `NewDaemon` (which should likely be a _copy_ of the config).

Before this patch:

    docker buildx inspect default
    Name:   default
    Driver: docker

    Nodes:
    Name:      default
    Endpoint:  default
    Status:    running
    Buildkit:  v0.12.4+3b6880d2a00f
    Platforms: linux/arm64, linux/amd64, linux/amd64/v2, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/mips64le, linux/mips64, linux/arm/v7, linux/arm/v6
    Labels:
     org.mobyproject.buildkit.worker.moby.host-gateway-ip: <nil>

After this patch:

    docker buildx inspect default
    Name:   default
    Driver: docker

    Nodes:
    Name:      default
    Endpoint:  default
    Status:    running
    Buildkit:  v0.12.4+3b6880d2a00f
    Platforms: linux/arm64, linux/amd64, linux/amd64/v2, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/mips64le, linux/mips64, linux/arm/v7, linux/arm/v6
    Labels:
     org.mobyproject.buildkit.worker.moby.host-gateway-ip: 172.18.0.1

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

```
Fix `host-gateway-ip` not working during build when not set through configuration
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: daemon/daemon.go [hunk 1]
```diff
@@ -180,6 +180,11 @@ func (daemon *Daemon) config() *configStore {
 	return cfg
 }
 
+// Config returns daemon's config.
+func (daemon *Daemon) Config() config.Config {
```
Comment (thaJeztah) [inline daemon/daemon.go:184]: FWIW, not "stoke" by this solution, but it should get us going.

**Comment by thaJeztah** [comment]
Failure is unrelated; and tracked in https://github.com/moby/moby/issues/47119

```
=== FAIL: amd64.integration.system TestDiskUsage/empty (0.00s)
    disk_usage_test.go:41: assertion failed: 
        --- du
        +++ →
          types.DiskUsage{
        - 	LayersSize: 4096,
        + 	LayersSize: 0,
          	Images:     {},
          	Containers: {},
          	... // 3 identical fields
          }
        
    --- FAIL: TestDiskUsage/empty (0.00s)
```

**Review by vvoland — APPROVED** [review]

**Review by crazy-max — APPROVED** [review]

**Comment by thaJeztah** [comment]
New failure is also unrelated (other flaky test); https://github.com/moby/moby/issues/46508

```
--- FAIL: TestLiveRestore (0.00s)
    --- SKIP: TestLiveRestore/autoremove (0.00s)
    --- FAIL: TestLiveRestore/volume_references (17.09s)
        --- PASS: TestLiveRestore/volume_references/restartPolicy (10.17s)
            --- PASS: TestLiveRestore/volume_references/restartPolicy/always (2.68s)
            --- PASS: TestLiveRestore/volume_references/restartPolicy/unless-stopped (2.62s)
            --- PASS: TestLiveRestore/volume_references/restartPolicy/on-failure (2.54s)
            --- PASS: TestLiveRestore/volume_references/restartPolicy/no (2.32s)
        --- FAIL: TestLiveRestore/volume_references/local_volume_with_mount_options (2.33s)
            --- SKIP: TestLiveRestore/volume_references/local_volume_with_mount_options/volume_still_mounted (0.00s)
        --- PASS: TestLiveRestore/volume_references/container_with_bind-mounts (2.34s)
```

**Review by laurazard — APPROVED** [review]
LGTM (but yeah, this is a messy area and we should track this somewhere to improve)

**Comment by thaJeztah** [comment]
@laurazard yeah, agreed. I did an ever-so-slightly cleanup after I worked on this here; https://github.com/moby/moby/pull/47188

(nothing for the "global picture" though.
