### PR TITLE
Fix #15659 : filter by label for docker images commited

### LINKED ISSUE #15659: can't filter by label if label is added in a commit
BUG REPORT INFORMATION
========================
Description of problem:
im trying to create a new image by committing a container and add a few labels in the process and then to filter only the images with the given labels.
This doesn't seem to work

`docker version`:
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

`docker info`:
Containers: 1
Images: 114
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 116
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-52-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 7.705 GiB
Name: asgard
ID: VQVB:Y2YF:V43V:27C4:7P3F:GNCA:M6UK:Q2AC:SBNH:I6MK:MYWD:3OTC
WARNING: No swap limit support

`uname -a`:
Linux asgard 3.13.0-52-generic #86-Ubuntu SMP Mon May 4 04:32:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
physical (laptop)

How reproducible:
* Commit a container add add new labels to it using the -c flag
* run `docker images -f` and try to filter the images using the labels you added.

Steps to Reproduce:
```bash
docker run -ti --name bar ubuntu:12.04.5 /bin/bash
root@bar:/# .. do some stuff...
```
now i commit the container to a new image
```bash
docker commit -c "LABEL foo.version=1.0.0-1" -c "LABEL foo.name=bar" -c "LABEL foo.author=starlord" bar bar:1.0.0-1
```
now i try run `docker images` with a filter to find it
```bash
docker images -f label=foo.version=1.0.0-1
# no images found
```

Actual Results:
```bash
docker images -f label=foo.version=1.0.0-1
# no images found
```

Expected Results:
```bash
docker images -f label=foo.version=1.0.0-1
# bar image information
```

Additional info:

here is an example of `docker inspect` of the new image
```json
[
{
    "Id": "e6d5e3183adab1ccc6ce11a8b352a614bf94ac938654496f7873e1587fec65f2",
    "Parent": "9e18ba0255e99e7ab4e06b1b01787c889024aae4f0508f66c3d383edb51fce1f",
    "Comment": "Bar",
    "Created": "2015-08-18T11:21:36.13759834Z",
    "Container": "cb734c639cbc81b2daaadf651d837be8274c904c084c53315e797497a2e96858",
    "ContainerConfig": {
        "Hostname": "bar",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": true,
        "AttachStderr": true,
        "ExposedPorts": null,
        "PublishService": "",
        "Tty": true,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        ],
        "Cmd": [
            "/bootstrap.sh",
        ],
        "Image": "ubuntu-foo-base",
        "Volumes": null,
        "VolumeDriver": "",
        "WorkingDir": "",
        "Entrypoint": null,
        "NetworkDisabled": false,
        "MacAddress": "",
        "OnBuild": null,
        "Labels": {}
    },
    "DockerVersion": "1.8.1",
    "Author": "Foo Team",
    "Config": {
        "Hostname": "",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": {
            "443/tcp": {},
            "80/tcp": {}
        },
        "PublishService": "",
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        ],
        "Cmd": null,
        "Image": "",
        "Volumes": null,
        "VolumeDriver": "",
        "WorkingDir": "",
        "Entrypoint": [
            "/usr/bin/python3",
            "-u",
            "/sbin/my_init",
            "--skip-startup-files"
        ],
        "NetworkDisabled": false,
        "MacAddress": "",
        "OnBuild": null,
        "Labels": {
            "foo.version": "1.0.0-1",
            "foo.name": "bar",
            "foo.author": "starlord",
        }
    },
    "Architecture": "amd64",
    "Os": "linux",
    "Size": 1089856717,
    "VirtualSize": 1349562321,
    "GraphDriver": {
        "Name": "aufs",
        "Data": null
    }
}
]
```
----------END REPORT ---------

#ENEEDMOREINFO

### PR DESCRIPTION
**Pull request by vdemeester**
Fixes #15659.

The filter in `graph/list.go` looks for `image.ContainerConfig.Labels` 🐧.
When building using a `Dockerfile` using `LABEL`, the _inspect_ looks like this :

``` json
[{
    // […]
    "ContainerConfig": {
        "Labels": {
            "foo.version": "1.0.0-1",
            "foo.name": "bar",
            "foo.author": "starlord",
        }
    }
    // […]
    "Config": {
        "Labels": {
            "foo.version": "1.0.0-1",
            "foo.name": "bar",
            "foo.author": "starlord",
        }
     }
}]
```

When it is commited using the `c` flags (like : `docker commit -c "LABEL foo.version=1.0.0-1" -c "LABEL foo.name=bar" -c "LABEL foo.author=starlord" bar bar:1.0.0-1`), the inspect looks like this :

``` json
[{
    // […]
    "ContainerConfig": {
        "Labels": {}
    }
    // […]
    "Config": {
        "Labels": {
            "foo.version": "1.0.0-1",
            "foo.name": "bar",
            "foo.author": "starlord",
        }
     }
}]
```

Something is not coherent between the `commit` and the `build` then. The current state of this PR is fixing it by probably doing a bad thing :sweat:. I think this is might be related to the don't propagate image labels to images but, not sure…
🐸

Signed-off-by: Vincent Demeester vincent@sbr.pm

### CODE REVIEW

**Comment by cpuguy83** [comment]
Yeah, I think this isn't quite right. Can we adjust the graph filter to search just image labels (or both)?

**Comment by vdemeester** [comment]
@cpuguy83 image labels are on `image.Config.Labels` right ? then yeah, that's probably the way we should do then. I'll take a look.

**Comment by vdemeester** [comment]
@cpuguy83 So, I track down why the integration test are failing : There is at least an image that has no `Config` (`image.Config` is nil). From my little search, it's the layer `511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158` of the jess/unshare image used for tests. The image metadata of the image is the following (note the docker version used for this one : `0.4.0` :blush:) :

```json
{
    "Id": "511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158",
    "Parent": "",
    "Comment": "Imported from -",
    "Created": "2013-06-13T14:03:50.821769-07:00",
    "Container": "",
    "ContainerConfig": {
        "Hostname": "",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": null,
        "PublishService": "",
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": null,
        "Cmd": null,
        "Image": "",
        "Volumes": null,
        "VolumeDriver": "",
        "WorkingDir": "",
        "Entrypoint": null,
        "NetworkDisabled": false,
        "MacAddress": "",
        "OnBuild": null,
        "Labels": null
    },
    "DockerVersion": "0.4.0",
    "Author": "",
    "Config": null,
    "Architecture": "x86_64",
    "Os": "",
    "Size": 0,
    "VirtualSize": 0,
    "GraphDriver": {
        "Name": "btrfs",
        "Data": null
    }
}
```

I think `image.Config` is always present, except from very very old images so I'm wondering if I should add a check if `image.Config` is not nil or if it is be unecessary (and we should update the `unshare` image).

I'll add a check for now though :sweat_smile:.

**Comment by thaJeztah** [comment]
cc @jfrazelle ^^ LOL

**Comment by jfrazelle** [comment]
this could be a problem tho wrt old images on hub if other people try to use this as well right?

File: graph/list.go [hunk 1]
```diff
@@ -108,17 +108,15 @@ func (s *TagStore) Images(filterArgs, filter string, all bool) ([]*types.Image,
 			} else {
 				// get the boolean list for if only the untagged images are requested
 				delete(allImages, id)
-				if !imageFilters.MatchKVList("label", image.ContainerConfig.Labels) {
+				if len(imageFilters["label"]) > 0 && image.Config == nil {
```
Comment (vdemeester) [inline graph/list.go]: This check is for "If we are filtering on labels and the image doesn't contains `Config` struct, let's skip it — as it will not have Labels". I don't like this because if we introduce new filters, the check is going to be ugly (or refactor will be needed).

File: integration-cli/docker_cli_images_test.go [hunk 2]
```diff
@@ -100,35 +100,40 @@ func (s *DockerSuite) TestImagesFilterLabel(c *check.C) {
...
+	c.Assert(err, check.IsNil)
 
 	out, _ := dockerCmd(c, "images", "--no-trunc", "-q", "-f", "label=match")
 	out = strings.TrimSpace(out)
-	if (!strings.Contains(out, image1ID) && !strings.Contains(out, image2ID)) || strings.Contains(out, image3ID) {
-		c.Fatalf("Expected ids %s,%s got %s", image1ID, image2ID, out)
-	}
+	c.Assert(out, check.Matches, fmt.Sprintf("[\\s\\w]*%s[\\s\\w]*", image1ID))
+	c.Assert(out, check.Matches, fmt.Sprintf("[\\s\\w]*%s[\\s\\w]*", image2ID))
+	c.Assert(out, check.Not(check.Matches), fmt.Sprintf("[\\s\\w]*%s[\\s\\w]*", image3ID))
```
Comment (vdemeester) [inline integration-cli/docker_cli_images_test.go]: I fooled around a bit with `check` here. I'll probably revert as this make it less readable than before but I think it would be fun to add to `Checker` like a `Contains` one or some even more Docker related.

File: integration-cli/docker_cli_save_load_test.go [hunk 3]
```diff
@@ -104,6 +104,10 @@ func (s *DockerSuite) TestSaveImageId(c *check.C) {
 	out, _ = dockerCmd(c, "images", "-q", repoName)
 	cleanedShortImageID := strings.TrimSpace(out)
 
+	// Make sure IDs are not empty
+	c.Assert(cleanedLongImageID, check.Not(check.Equals), "", check.Commentf("Id should not be empty."))
+	c.Assert(cleanedShortImageID, check.Not(check.Equals), "", check.Commentf("Id should not be empty."))
```
Comment (vdemeester) [inline integration-cli/docker_cli_save_load_test.go]: This is to fail early :sweat_smile:

**Comment by vdemeester** [comment]
Hopefully it's finally green :frog: ; so the fix is here. But there is still the incoherence between image built (using dockerfiles) and image commited with `-c` flags.

**Comment by jfrazelle** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Comment by icecrime** [comment]
LGTM
