### PR TITLE
Fix race in `TestApiSwarmRestartCluster`

### LINKED ISSUE #24590: Flaky test: DockerSwarmSuite.TestApiSwarmRestartCluster
Fails consistently on ARM and Power, and flaky on x86 master.

https://jenkins.dockerproject.org/job/Docker%20Master/label=ubuntu%20&&%20aufs/6107/console

```sh
06:25:05 docker_api_swarm_test.go:876:
06:25:05     checkClusterHealth(c, nodes, mCount, wCount)
06:25:05 github.com/docker/docker/integration-cli/_test/_obj_test/daemon_swarm.go:258:
06:25:05     ...open github.com/docker/docker/integration-cli/_test/_obj_test/daemon_swarm.go: no such file or directory
06:25:05 ... obtained int = 500
06:25:05 ... expected int = 200
06:25:05 ... output: "{\"message\":\"rpc error: code = 4 desc = context deadline exceeded\"}\n"
```

### PR DESCRIPTION
**Pull request by cpuguy83**
In `TestApiSwarmRestartCluster`, it's calling `checkClusterHealth`.
`checkClusterHealth` calls `d.info()`, which will return an error if
there is no cluster leader... problem is `checkClusterHealth` is doing a
nil error assertion w/o giving any time for a leader to be elected.

This moves the `d.info()` call into a `waitAndAssert` using the default
reconciliation timeout.

Fixes #24590

### CODE REVIEW

**Comment by cpuguy83** [comment]
Found a couple of more issues with this test, working on an update.

File: integration-cli/docker_api_swarm_test.go [hunk 1]
```diff
@@ -823,19 +823,49 @@ func setGlobalMode(s *swarm.Service) {
...
+
 		for _, n := range d.listNodes(c) {
-			c.Assert(n.Status.State, checker.Equals, swarm.NodeStateReady, check.Commentf("state of node %s, reported by %s", n.ID, d.Info.NodeID))
-			c.Assert(n.Spec.Availability, checker.Equals, swarm.NodeAvailabilityActive, check.Commentf("availability of node %s, reported by %s", n.ID, d.Info.NodeID))
+			waitReady := func(c *check.C) (interface{}, check.CommentInterface) {
+				if n.Status.State == swarm.NodeStateReady {
+					return true, nil
+				}
+				nn := d.getNode(c, n.ID)
+				n = *nn
```
Comment (dnephin) [inline integration-cli/docker_api_swarm_test.go]: I'm not sure I understand this. Why is state being checked before getting the node?

Comment (cpuguy83) [inline integration-cli/docker_api_swarm_test.go]: because we already have the node, might as well check if its already ok before getting the node again,

**Comment by dnephin** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Comment by tonistiigi** [comment]
Starting a test daemon blocks until the control API becomes available, this should not happen before leader has been elected. If there is a reelection(not sure why it should be in this case) but there is no error the manager calls should block also. Debugging why reelection happened in this test already pointed us to at least one swarmkit bug in https://github.com/docker/swarmkit/issues/1183 .

If we don't do this every user of swarm API endpoints needs to write:

```
for {
  if err := apicall(); err != nil {
    if isNoLeader(err) {
      backoffDelay()
      continue
    }
    return err
  }
}
```

That doesn't seem to be very user-friendly.

I'm fine with patching the test for CI but we need to make sure we are not hiding actual bugs by working around them in our tests.
