### PR TITLE
Limit TestEventsLimit to 4 concurrent containers on Windows

### LINKED ISSUE #28873: Flaky test: TestEventsLimit (on windowsRS1)
https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS1/6924/console (https://github.com/docker/docker/pull/28858)

```
00:36:19.093 FAIL: docker_cli_events_test.go:80: DockerSuite.TestEventsLimit
00:36:19.093 
00:36:19.093 docker_cli_events_test.go:107:
00:36:19.093     c.Assert(err, checker.IsNil, check.Commentf("%q failed with error", strings.Join(args, " ")))
00:36:19.093 ... value *errors.errorString = &errors.errorString{s:"exit status 125: d:\\CI\\CI-d4faec3\\binary\\docker.exe: Error response from daemon: container 8cdad0990777303c9ed781e6aec4d2041ffea862e477c83ce9855eba1993eb45 encountered an error during CreateContainer: failure in a Windows system call: Element not found. (0x490) extra info: {\"SystemType\":\"Container\",\"Name\":\"8cdad0990777303c9ed781e6aec4d2041ffea862e477c83ce9855eba1993eb45\",\"Owner\":\"docker\",\"IsDummy\":false,\"VolumePath\":\"\\\\\\\\?\\\\Volume{df77045f-b416-11e6-a9e3-a3e8dcd2ece8}\",\"IgnoreFlushesDuringBoot\":true,\"LayerFolderPath\":\"D:\\\\CI\\\\CI-d4faec3\\\\daemon\\\\windowsfilter\\\\8cdad0990777303c9ed781e6aec4d2041ffea862e477c83ce9855eba1993eb45\",\"Layers\":[{\"ID\":\"a357e360-20c6-5562-9d3c-5f5601fc2e27\",\"Path\":\"D:\\\\CI\\\\CI-d4faec3\\\\daemon\\\\windowsfilter\\\\0fe06de94e00e662e118471af423d9af4292d2c6fe9cbd3cb8760aa77b4e393e\"},{\"ID\":\"26535a4b-0de5-5265-8093-f1a9f4e9c1c5\",\"Path\":\"D:\\\\CI\\\\CI-d4faec3\\\\daemon\\\\windowsfilter\\\\be0f54e13c670cf1e69a5641969c42c4e1e6319707c5d00f75e76d53ae685cc7\"},{\"ID\":\"c06d1513-628e-55aa-b425-60f60d14d984\",\"Path\":\"D:\\\\CI\\\\CI-d4faec3\\\\daemon\\\\windowsfilter\\\\d17fb0a54a3cca6c3fbd0fd0ee7a71bfc403a5633e59468a80687cb619821188\"},{\"ID\":\"4fc84f0e-7c41-5363-88b6-b940aac79f52\",\"Path\":\"D:\\\\CI\\\\CI-d4faec3\\\\daemon\\\\windowsfilter\\\\266f7b13538ab770f3d871106c4e5b4c0911a73055a2dfce41e8c89298ae6e0b\"},{\"ID\":\"22e55141-3302-5155-9ecc-1968230b885e\",\"Path\":\"D:\\\\CI\\\\CI-d4faec3\\\\daemon\\\\windowsfilter\\\\72956258e6c7ef1dc5a74ff4edf01e1a7964d26a6b62ffd180d692ad631e9c20\"},{\"ID\":\"ae480fe2-5125-5f8e-99cb-9c0fbaf8e400\",\"Path\":\"D:\\\\CI\\\\CI-d4faec3\\\\daemon\\\\windowsfilter\\\\25d759e1b2d1e2b01f5d9d4af91d6597410dbb4857779cfc7415ba8a5563d25e\"}],\"HostName\":\"8cdad0990777\",\"MappedDirectories\":[],\"HvPartition\":false,\"EndpointList\":[\"42886869-2050-404f-841d-9246a171603a\"],\"Servicing\":false,\"AllowUnqualifiedDNSQuery\":true}.\n"} ("exit status 125: d:\\CI\\CI-d4faec3\\binary\\docker.exe: Error response from daemon: container 8cdad0990777303c9ed781e6aec4d2041ffea862e477c83ce9855eba1993eb45 encountered an error during CreateContainer: failure in a Windows system call: Element not found. (0x490) extra info: {\"SystemType\":\"Container\",\"Name\":\"8cdad0990777303c9ed781e6aec4d2041ffea862e477c83ce9855eba1993eb45\",\"Owner\":\"docker\",\"IsDummy\":false,\"VolumePath\":\"\\\\\\\\?\\\\Volume{df77045f-b416-11e6-a9e3-a3e8dcd2ece8}\",\"IgnoreFlushesDuringBoot\":true,\"LayerFolderPath\":\"D:\\\\CI\\\\CI-d4faec3\\\\daemon\\\\windowsfilter\\\\8cdad0990777303c9ed781e6aec4d2041ffea862e477c83ce9855eba1993eb45\",\"Layers\":[{\"ID\":\"a357e360-20c6-5562-9d3c-5f5601fc2e27\",\"Path\":\"D:\\\\CI\\\\CI-d4faec3\\\\daemon\\\\windowsfilter\\\\0fe06de94e00e662e118471af423d9af4292d2c6fe9cbd3cb8760aa77b4e393e\"},{\"ID\":\"26535a4b-0de5-5265-8093-f1a9f4e9c1c5\",\"Path\":\"D:\\\\CI\\\\CI-d4faec3\\\\daemon\\\\windowsfilter\\\\be0f54e13c670cf1e69a5641969c42c4e1e6319707c5d00f75e76d53ae685cc7\"},{\"ID\":\"c06d1513-628e-55aa-b425-60f60d14d984\",\"Path\":\"D:\\\\CI\\\\CI-d4faec3\\\\daemon\\\\windowsfilter\\\\d17fb0a54a3cca6c3fbd0fd0ee7a71bfc403a5633e59468a80687cb619821188\"},{\"ID\":\"4fc84f0e-7c41-5363-88b6-b940aac79f52\",\"Path\":\"D:\\\\CI\\\\CI-d4faec3\\\\daemon\\\\windowsfilter\\\\266f7b13538ab770f3d871106c4e5b4c0911a73055a2dfce41e8c89298ae6e0b\"},{\"ID\":\"22e55141-3302-5155-9ecc-1968230b885e\",\"Path\":\"D:\\\\CI\\\\CI-d4faec3\\\\daemon\\\\windowsfilter\\\\72956258e6c7ef1dc5a74ff4edf01e1a7964d26a6b62ffd180d692ad631e9c20\"},{\"ID\":\"ae480fe2-5125-5f8e-99cb-9c0fbaf8e400\",\"Path\":\"D:\\\\CI\\\\CI-d4faec3\\\\daemon\\\\windowsfilter\\\\25d759e1b2d1e2b01f5d9d4af91d6597410dbb4857779cfc7415ba8a5563d25e\"}],\"HostName\":\"8cdad0990777\",\"MappedDirectories\":[],\"HvPartition\":false,\"EndpointList\":[\"42886869-2050-404f-841d-9246a171603a\"],\"Servicing\":false,\"AllowUnqualifiedDNSQuery\":true}.\n")
00:36:19.108 ... "run --rm busybox true" failed with error
00:36:19.108 
00:36:19.245 
00:36:19.245 ----------------------------------------------------------------------
```

I'm not sure this is a dupe of https://github.com/docker/docker/issues/22601 ,
but the error message seems different (`CreateContainer: failure in a Windows system call: Element not found. (0x490)`)

PTAL @jhowardmsft @darrenstahlmsft

### PR DESCRIPTION
**Pull request by darstahl**
This hopefully fixes the latest TestEventsLimit failures on windowsRS1.

fixes #28873

Signed-off-by: Darren Stahl <darst@microsoft.com>

### CODE REVIEW

**Comment by tonistiigi** [comment]
That seems like a strange fix. If it is a platform bug then can we add a more specific comment about what command fails with what message and if possible a way to check the status of that bug.

**Comment by AkihiroSuda** [comment]
ping @darrenstahlmsft

File: integration-cli/docker_cli_events_test.go [hunk 1]
```diff
@@ -78,9 +78,13 @@ func (s *DockerSuite) TestEventsUntag(c *check.C) {
 }
 
 func (s *DockerSuite) TestEventsLimit(c *check.C) {
-	// Limit to 8 goroutines creating containers in order to prevent timeouts
+	// Limit to 4 goroutines creating containers in order to prevent timeouts
```
Comment (LK4D4) [inline integration-cli/docker_cli_events_test.go]: @darrenstahlmsft this comment looks not true, we still limiting to 8 everywhere apart from Windows.

**Review by LK4D4 — CHANGES_REQUESTED** [review]

**Comment by LK4D4** [comment]
@darrenstahlmsft Is there a particular bug which will be fixed in windows? Or is it by design?

**Comment by darrenstahlmsft** [comment]
@LK4D4 Fixed so Windows is the only platform getting concurrency limits in this test.

@tonistiigi Is the new comment enough for you? Unfortunately there is no way to check the status of internal Windows bugs :( I could add a tracking number for Microsoft employees if that helps, but I don't think that will be useful

**Review by LK4D4 — APPROVED** [review]

**Comment by LK4D4** [comment]
LGTM

**Comment by tonistiigi** [comment]
LGTM
