### PR TITLE
Upon HTTP 302 redirect do not include "Authorization" header on 'untr…

### LINKED ISSUE #13649: Docker 1.7 breaks http redirect authentication for custom registries
The refactoring in https://github.com/docker/docker/commit/a01cc3ca7729c3ce635fef7c1db837b5c6ae1028 adds an "Authorization" header to every http request made to a v1 registry, including http requests issued to follow http 302 redirects. 

This is a change in behavior from Docker 1.6, that breaks redirects for unauthenticated access to cloud storage services such as Amazon S3 and Google Cloud Storage.

I have a patch that I'll be sending out shortly.

# Repro:
`docker pull gcr.io/google-containers/pause:1.0`

# Docker 1.7:
```
Pulling repository gcr.io/google-containers/pause
6c4579af347b: Pulling image (1.0) from gcr.io/google-containers/pause
6c4579af347b: Pulling image (1.0) from gcr.io/google-containers/pause, endpoint: https://gcr.io/v1/
6c4579af347b: Error pulling image (1.0) from gcr.io/google-containers/pause, endpoint: https://gcr.io/v1/, Server error: 403 trying to fetch remote history for 6c4579af347b649857e915521132f15a06186d73faa62145e3eeeb6be0e97c27
6c4579af347b: Error pulling image (1.0) from gcr.io/google-containers/pause, Server error: 403 trying to fetch remote history for 6c4579af347b649857e915521132f15a06186d73faa62145e3eeeb6be0e97c27
Error pulling image (1.0) from gcr.io/google-containers/pause, Server error: 403 trying to fetch remote history for 6c4579af347b649857e915521132f15a06186d73faa62145e3eeeb6be0e97c27
```
# Docker 1.6:
```
Pulling repository gcr.io/google-containers/pause
6c4579af347b: Download complete 
511136ea3c5a: Download complete 
e244e638e26e: Download complete 
Status: Downloaded newer image for gcr.io/google-containers/pause:1.0
```

The main difference between Docker 1.6 and Docker 1.7 is that Docker 1.7 is sending the Authorization header on 302 redirect where Docker 1.6 isn't.

### PR DESCRIPTION
**Pull request by jvgogh**
…usted' registries.

Refactoring in Docker 1.7 changed the behavior to add this header where as Docker <= 1.6 wouldn't emit this Header on a HTTP 302 redirect.

This closes #13649

Signed-off-by: Jeffrey van Gogh jvg@google.com

### CODE REVIEW

**Comment by jfrazelle** [comment]
can you please squash your commits

**Comment by jvgogh** [comment]
commits squashed..

File: registry/session.go [hunk 1]
```diff
@@ -84,7 +84,13 @@ func (tr *authTransport) RoundTrip(orig *http.Request) (*http.Response, error) {
...
 		if req.Header.Get("X-Docker-Token") == "true" && len(tr.Username) > 0 {
 			req.SetBasicAuth(tr.Username, tr.Password)
-		} else if len(tr.token) > 0 {
+		} else if len(tr.token) > 0 &&
+			// Authorization should not be set on 302 redirect for untrusted locations.
+			// This logic mirrors the behavior in AddRequiredHeadersToRedirectedRequests.
+			// As the authorization logic is currently implemented in RoundTrip,
+			// a 302 redirect is detected by looking at the Referer header as go http package adds said header.
+			// This is safe as Docker doesn't set Referer in other scenarios.
+			(req.Header.Get("Referer") == "" || trustedLocation(orig)) {
```
Comment (tiborvass) [inline registry/session.go]: @jvgogh thanks, shouldn't we also check the http code?

Comment (mattmoor) [inline registry/session.go]: I believe at this point the only context available is the subsequent request being issued through the transport (which is what he's inspecting).

Comment (jvgogh) [inline registry/session.go]: Ideally yes, the problem is that the http 302 redirect handling is taken care of by the go http client library (https://golang.org/src/net/http/client.go amusingly enough the function starts on line 302) 

In registry.go, there is a similar piece of code that is able to use CheckRedirects for this, as the headers are set earlier auth.go. This won't work in session.go without significant refactoring as the header is set in RoundTrip which is called for each http request, including the recursive calls from the go client code resolving the 302 redirects.

The only way I found to distinguish in RoundTrip between direct requests and 302 redirect requests is by checking the "Referer" header.

There might be a way to refactor the code in session.go to deal with this like in registry.go, but that seemed like a larger work item, I'd be happy to discuss, but my first priority was to get 1.7 unbroken for the unauthenticated scenario on custom registries..

Comment (tiborvass) [inline registry/session.go]: Fair enough :)

**Comment by tiborvass** [comment]
LGTM

**Comment by tiborvass** [comment]
Ping @dmcgowan

File: registry/session.go (hunk 1 above)
Comment (stevvooe) [inline registry/session.go]: Could we namespace authorization headers to the particular host in the request? Should we have a method `getToken(host string)` to avoid this? Checking "Referer" seems problematic, in that I could make a registry service that purposely doesn't set the referer to force the client to send the authentication token. My understanding of this issue may be way off.

Comment (jvgogh) [inline registry/session.go]: @stevvooe the "Referer" header is a client side header added by the go http library upon 302 (it gets the data from the Location header returned by the server on 302 as per the http spec). This is not something a host implements, but rather the docker client (through the go http library). As such the fix, although not the most elegant is safe regardless of which registry service is used.

Comment (tiborvass) [inline registry/session.go]: @stevvooe It seems like the `Referer` header is set by Go's http client when it receives a 302: https://golang.org/src/net/http/client.go#L352. But feel free to prove me wrong with an example.

**Comment by tiborvass** [comment]
Removed my approval, because I'm not sure this is the right solution, will investigate further, but all clients passed to NewSession should be from `registry.HTTPClient()` which sets `CheckRedirect`, which according to the http package's code should be taken into account before sending the 2nd request to the endpoint specified by the Location header. So maybe somewhere we're not using the HTTPClient() function?

**Comment by jvgogh** [comment]
@tiborvass the Transport for http client is overridden in session.go (https://github.com/docker/docker/blob/master/registry/session.go#L148) which explicitly sets the "Authorization" header on every RoundTrip (https://github.com/docker/docker/blob/master/registry/session.go#L72), which is done after CheckRedirect has been run so the logic in CheckRedirect doesn't solve the problem.

**Comment by tiborvass** [comment]
Oh damn, that's correct, it reintroduces it after CheckRedirect... hmm

**Comment by tiborvass** [comment]
Ok LGTM I don't see any other way of solving this. @dmcgowan @stevvooe we should probably revisit later the design for auth roundtrippers with checkredirect. For now this should be good.

**Comment by dmcgowan** [comment]
LGTM

**Comment by estesp** [comment]
LGTM

**Comment by estesp** [comment]
@jfrazelle I believe this is a cherry-pick candidate for 1.7

**Comment by jvgogh** [comment]
@estesp @jfrazelle yes, it would be great to have this in 1.7. Thanks!

**Comment by jfrazelle** [comment]
cherrypicked
