### PR TITLE
Restore active mount counts on live-restore

### LINKED ISSUE #44422: live-restore in combination with docker compose is broken with docker-ce version 20.10.19 and newer
### Description

Hello,

we are heavily using the live-restore feature in our production environments and facing automatic deployment issues through our ci. In our environment all Operating System Packages are updated automatically. When the docker engine gets updated and someone restarts a container in a running compose stack a docker compose down -v --remove-orphans does not work.

Update:
This happens particularly to named volumes with local driver and binded directory.

docker-compose.yml example
```
version: '2.4'
services:
  app:
    image: appimage
    networks:
      app-network:
        aliases:
          - app
    restart: "unless-stopped"
    volumes:
      - log-app:/log
     
volumes:
  log-app:
    driver: local
    driver_opts:
      type: none
      device: /srv/docker/stack/prod/log/app
      o: bind
```

Operating System: Debian GNU/Linux 11.5 (Bullseye)

### Reproduce

```
root@host:/srv/docker/stack/prod# su - dockerdeploy
dockerdeploy@host:~# cd /srv/docker/stack/prod
dockerdeploy@host:/srv/docker/stack/prod# docker compose up -d
dockerdeploy@host:/srv/docker/stack/prod# exit
root@host:/srv/docker/stack/prod# systemctl restart docker.service
root@host:/srv/docker/stack/prod# su - dockerdeploy
dockerdeploy@host:~# cd /srv/docker/stack/prod
dockerdeploy@host:/srv/docker/stack/prod$ docker compose restart app
[+] Running 1/1
 ⠿ Container app  Started
dockerdeploy@host:/srv/docker/stack/prod$ docker compose down -v --remove-orphans
[+] Running 21/37
.....
Error response from daemon: remove prod_log-app: volume has active mounts
```

### Expected behavior

docker compose down -v --remove-orphans should reliably tear down the stack

### docker version

```bash
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:02:28 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:00:19 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)

Server:
 Containers: 34
  Running: 34
  Paused: 0
  Stopped: 0
 Images: 28
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1c90a442489720eec95342e1789ee8a5e1b9536f
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.0-19-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 60
 Total Memory: 157.2GiB
 Name: prod
 ID: XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true
```

### Additional Info

Docker Compose version v2.12.2

### daemon.json
```
{
  "experimental": true,
  "fixed-cidr-v6": "fd00:dead:beef:c0::/80",
  "ipv6": true,
  "ip6tables": true,
  "live-restore": true,
  "mtu": 1400
}

### PR DESCRIPTION
**Pull request by cpuguy83**
When live-restoring a container the volume driver needs be notified that there is an active mount for the volume.
Before this change the count is zero until the container stops and the uint64 overflows pretty much making it so the volume can never be removed until another daemon restart.

Fixes #44422

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
docker-py failure can be ignored and is unrelated (fixed on master)

**Comment by thaJeztah** [comment]
@corhere @neersighted @vvoland PTAL

File: daemon/mounts.go [hunk 1]
```diff
@@ -8,13 +8,21 @@ import (
...
 )
 
 func (daemon *Daemon) prepareMountPoints(container *container.Container) error {
+	alive := container.IsRunning()
 	for _, config := range container.MountPoints {
 		if err := daemon.lazyInitializeVolume(container.ID, config); err != nil {
 			return err
 		}
+		if alive {
+			logrus.WithField("container", container.ID).WithField("volume", config.Volume.Name()).Debug("Live-restoring volume for alive container")
```
Comment (vvoland) [inline daemon/mounts.go:21]: We probably want to adjust the logging to the new containerd logger first (https://github.com/moby/moby/pull/45799)

**Review by vvoland — COMMENTED** [review]
Overall LGTM, the logs need to be adjusted now though

File: daemon/mounts.go (hunk 1 above)
Comment (thaJeztah) [reply daemon/mounts.go:21]: Yeah, I saw this one; I'm okay with fixing up after this though

Comment (thaJeztah) [reply daemon/mounts.go:21]: ^^ I should add that one reason why doing it later is that we're backporting this fix to other branches (which don't have the new logging) 😅

Comment (vvoland) [reply daemon/mounts.go:21]: Ah, that makes sense!

**Review by vvoland — APPROVED** [review]

File: daemon/mounts.go (hunk 1 above)
Comment (neersighted) [reply daemon/mounts.go:21]: That being said, I'd like this to be a `WithFields(logrus.Fields{})` for all branches before merge, otherwise this looks good.

**Review by neersighted — CHANGES_REQUESTED** [review]
One logging nit, otherwise LGTM.

**Review by neersighted — APPROVED** [review]

**Comment by thaJeztah** [comment]
Looks like we should add a -f in the github actions as well;

```
sudo rm /etc/docker/daemon.json
  sudo service docker restart
  docker version
  docker info
  shell: /usr/bin/bash -e {0}
  env:
    DESTDIR: ./build
    BUILDKIT_REPO: moby/buildkit
    BUILDKIT_TEST_DISABLE_FEATURES: cache_backend_azblob,cache_backend_s3,merge_diff
    BUILDKIT_REF: 798ad6b0ce9f2fe86dfb2b0277e6770d0b545871
rm: cannot remove '/etc/docker/daemon.json': No such file or directory
Error: Process completed with exit code 1.

**Comment by solidgoldbomb** [comment]
Thanks for all of your work on this issue + fix @cpuguy83.

**Comment by cpuguy83** [comment]
Sorry it took so long to recognize where the issue was!
