### PR TITLE
Fix volumes-from re-applying on each start

### LINKED ISSUE #9709: Cannot restart container <id>: Container <another_id> not found. Impossible to mount its volumes
Since Docker 1.4.1

```
$ fig restart loremipsum
Cannot restart container 744b793908b05ca6228fb23e0fde71e6e0e59d80068773a69c97bd8ce5e4bf22: Container 3e9b310d4596b03894cde6bc1e80c98a3f3cf9afcfe848d7746f08c1d26698f8 not found. Impossible to mount its volumes
```
```
$ docker restart loremipsum
Error response from daemon: Cannot restart container CRM_storefront_1: Container cdb322fe4b729b26aa0741433c07ecbedf6877a939cb0d3b13e3271b58039688 not found. Impossible to mount its volumes
FATA[0000] Error: failed to restart one or more containers 

```
```
$ docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
````
````
$ fig --version
fig 1.0.0
````

### PR DESCRIPTION
**Pull request by cpuguy83**
Fixes #9709
In cases where the volumes-from container is removed and the consuming
container is restarted, docker was trying to re-apply volumes from that
now missing container, which is uneccessary since the volumes are
already applied.

Also cleaned up the volumes-from parsing function, which was doing way more than
it should have been.

### CODE REVIEW

**Comment by LK4D4** [comment]
@cpuguy83 need rebase

**Comment by jfrazelle** [comment]
@cpuguy83 your test passes on master

**Comment by cpuguy83** [comment]
Indeed it does... it did not use to...

**Comment by jfrazelle** [comment]
so has the problem been fixed by something else ?

**Comment by cpuguy83** [comment]
I don't think so... it shouldn't be working.  Trying to figure out why test isn't failing.

**Comment by cpuguy83** [comment]
It seems the behavior of "start" has changed?
Changing the test to use "restart" instead it fails.

**Comment by cpuguy83** [comment]
Updated test, this now fails on master.

File: integration-cli/docker_cli_run_test.go [hunk 1]
```diff
@@ -374,6 +374,7 @@ func TestRunVolumesMountedAsReadonly(t *testing.T) {
 }
 
 func TestRunVolumesFromInReadonlyMode(t *testing.T) {
+	defer deleteAllContainers()
```
Comment (jfrazelle) [inline integration-cli/docker_cli_run_test.go]: ty! for all these :)

**Comment by LK4D4** [comment]
@cpuguy83 Need rebase. Sorry :)

**Comment by icecrime** [comment]
I did a first pass of review, and it *seems* good but I'm really not familiar with volumes management :-/ I'll try to test this tomorrow.

**Comment by cpuguy83** [comment]
Rebased

**Comment by cpuguy83** [comment]
rebased

**Comment by icecrime** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM
