### PR TITLE
Fix copy API (`docker cp`, etc) uid/gid handling

### LINKED ISSUE #21651: API PUT archive file ownership root when container running as non-root.
We're having issues using the PUT /containers/(id)/archive endpoint due to file ownership permissions. When a container is running as a non-root user, the ownership is always reset back to root after uploading the file.

```
  > docker version                                                                         
Client:                                                                                    
 Version:      1.10.0                                                                      
 API version:  1.22                                                                        
 Go version:   go1.5.3                                                                     
 Git commit:   590d5108                                                                    
 Built:        Thu Feb  4 18:36:33 2016                                                    
 OS/Arch:      linux/amd64                                                                 

Server:                                                                                    
 Version:      1.10.0                                                                      
 API version:  1.22                                                                        
 Go version:   go1.5.3                                                                     
 Git commit:   590d5108-unsupported                                                        
 Built:        Fri Feb  5 02:32:52 2016                                                    
 OS/Arch:      linux/amd64  
```

Given an image with a directory owned by a different user

```
FROM ubuntu
RUN mkdir /opt/www-data && chown www-data:www-data /opt/www-data
docker build -t secure .
```

And a tar file owned by a non-root user

```
> touch test
> tar -zcvf test.tar.gz test

> ls -lha 
-rw-r--r-- 1 non-root non-root    0 Mar 30 10:19 test  
-rw-r--r-- 1 non-root non-root  114 Mar 30 10:19 test.tar.gz
```

When you launch the container as a non-root user

```
docker run -d -u www-data --name target secure sleep 100000
```

After uploading the tar, the file ownership permissions will be reset to root. The ownership should match either the original file or the user the container is being run as. 

```
curl -s -XPUT  -T test.tar.gz docker:2345/containers/target/archive?path=/opt/www-data
docker exec -it target bash

> /opt/www-data$ ls -lha
drwxr-xr-x 1 www-data www-data 4.0K Mar 30 10:24 .
drwxr-xr-x 1 root     root     4.0K Mar 30 10:22 ..
-rw-r--r-- 1 root     root        0 Mar 30 10:19 test 
```

### PR DESCRIPTION
**Pull request by erikh**
Closes #21651 

**- What I did**

Adjusted the archiving UID/GID maps to not only consider root. Adjusted tests to appropriately measure permissions as well as the metadata it already carried to better enable testing with permissions crossing the border into/out of a container.

**- How I did it**

It's a pretty small patch. :D 

**- How to verify it**

This aughta work:

* docker create --name foo debian
* touch bar && chown nobody:nogroup bar
* docker cp bar foo:/bar

Before, these files would be root. After, they should reflect the UID of the files on the host.

**- Description for the changelog**

Fixed copy protocol and `docker cp` to appropriately transfer UID/GID to files copied into the container.

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
For compatibility, probably it should be an option, e.g. `docker cp --preserve-permission`?
https://github.com/docker/docker/issues/21651#issuecomment-259133127

cc @thaJeztah @estesp

**Comment by AkihiroSuda** [comment]
windowsRS1 failing with many "not supported by windows" errors
```
08:12:47 ----------------------------------------------------------------------
08:12:47 FAIL: docker_cli_cp_to_container_test.go:228: DockerSuite.TestCpToCaseA
08:12:47 
08:12:47 docker_cli_cp_to_container_test.go:236:
08:12:47     makeTestContentInDir(c, tmpDir)
08:12:47 docker_cli_cp_utils.go:107:
08:12:47     c.Assert(os.Chown(path, fd.uid, fd.gid), checker.IsNil)
08:12:47 ... value *os.PathError = &os.PathError{Op:"chown", Path:"d:\\CI\\CI-f2356d4\\test-cp-to-case-a949295019\\file1", Err:0x20000082} ("chown d:\\CI\\CI-f2356d4\\test-cp-to-case-a949295019\\file1: not supported by windows")
08:12:47 
08:12:51 
08:12:51 ----------------------------------------------------------------------
```

**Comment by erikh** [comment]
ah ok. what's the way to gate this test so it only runs on linux?

**Comment by thaJeztah** [comment]
@erikh if it requires a Linux _daemon_;

https://github.com/docker/docker/blob/master/integration-cli/docker_api_stats_test.go#L262

If it requires the daemon and client to be linux, probably  https://github.com/docker/docker/blob/master/integration-cli/docker_api_stats_test.go#L166

However, there are also some test _files_ that are only built/run on Linux/Unix (keep in mind that work is in progress on Solaris support); https://github.com/docker/docker/blob/master/integration-cli/docker_api_stats_unix_test.go#L1

**Comment by erikh** [comment]
Hmm. actually it looks like the chmod is failing in the test setup instead
as well. I will revisit tonight.

**Comment by erikh** [comment]
I'm working on this now, sorry for the delay.

**Comment by erikh** [comment]
The cp tests are passing again on windows. PTAL?

**Comment by estesp** [comment]
@thaJeztah do we have a way to force a `userns` CI run? I know on a recent PR it was mentioned that it wasn't working properly?

**Comment by thaJeztah** [comment]
hm, no doesn't seem to work indeed :cry: not sure

**Comment by estesp** [comment]
FWIW, I ran the full suite myself against a user namespace-enabled daemon and all tests passed, but most importantly:
```
PASS: docker_cli_cp_to_container_test.go:602: DockerSuite.TestCpToHostWithPermissions   24.939s
```
Taking 25sec to run the test seems a bit long given the steps don't seem intensive, but it **is** passing.

Personally I'm fine with design; not sure if this needs more design review or just code review and confirmation on functionality of preserving ownership (which probably was the way it was working before user namespaces were merged in 1.9 experimental)

**Comment by tonistiigi** [comment]
That is a documented behavior in https://github.com/docker/docker/blob/master/docs/reference/commandline/cp.md so I'm not sure we can just flip it.

Even if it makes more sense we should probably keep the cli behavior and change the API only. 

cc @jlhawn

**Comment by jlhawn** [comment]
> That is a [documented behavior](https://github.com/docker/docker/blob/master/docs/reference/commandline/cp.md) so I'm not sure we can just flip it.
> > Ownership is set to the user and primary group at the destination. For example, files copied to a container are created with UID:GID of the root user. Files copied to the local machine are created with the UID:GID of the user which invoked the docker cp command.
>
> Even if it makes more sense we should probably keep the cli behavior and change the API only.

👍 

I'm not sure what the project's official process and policy is if we were to change the default behavior, but I think it would be a good idea to do this (preserve permissions) since the stated goal of `docker container cp ...` is to behave like the utility `cp -a` which does preserve ownership. Here's the relevant section from the manual for the BSD `cp` utility:

```
     -p    Cause cp to preserve the following attributes of each source file
           in the copy: modification time, access time, file flags, file mode,
           user ID, and group ID, as allowed by permissions.  Access Control
           Lists (ACLs) and Extended Attributes (EAs), including resource
           forks, will also be preserved.

           If the user ID and group ID cannot be preserved, no error message
           is displayed and the exit value is not altered.

           If the source file has its set-user-ID bit on and the user ID can-
           not be preserved, the set-user-ID bit is not preserved in the
           copy's permissions.  If the source file has its set-group-ID bit on
           and the group ID cannot be preserved, the set-group-ID bit is not
           preserved in the copy's permissions.  If the source file has both
           its set-user-ID and set-group-ID bits on, and either the user ID or
           group ID cannot be preserved, neither the set-user-ID nor set-
           group-ID bits are preserved in the copy's permissions.
```

If we do not want to change the current behavior, we could provide a `--preserve-ownership, -p` flag to the CLI subcommand which defaults to `false`.

Also, last year, when we added support for extracting an archive into a container, I considered adding a `--chown uid[:gid]` option but it was too much extra work at the time. This option would be used to specify that you want to recursively set user and group ownership of the copied content to the given `uid` and `gid`. You might also argue that `chown` could be its own separate command ... then you get into debating whether we should have an entire remote filesystem API and we probably don't want to go there.

**Comment by thaJeztah** [comment]
Adding `-p` / `--preserve-ownership` doesn't sound too bad; at least it guarantees a non-breaking change

**Comment by erikh** [comment]
This is the less surprising behavior to me (documented or not, broken is
broken). That said, I will do whatever you guys want. Just give me exact
details please.

**Comment by thaJeztah** [comment]
> This is the less surprising behavior to me (documented or not, broken is broken).

Not saying I disagree, but changing behavior like this has bitten us on multiple occasions, because people start to rely on it (even if it's broken). If we _do_ decide to change the default, we should consider adding a flag / option to restore the current behavior.

**Comment by erikh** [comment]
Oh definitely re: flag to restore behavior. I completely agree.

Once you folks decide on something, I will change the PR. Happy to do it
either scenario, just expressing my opinion on the subject.

**Comment by Kronos1776** [comment]
consider linux command: **chmod --reference={reference_file} {target_file}**
this is an established behavior in linux.

**Comment by thaJeztah** [comment]
We were comparing behavior with a regular `cp`;

- `cp source target` uses permissions of `target` if `target` exists, and uses permissions of the current user if the target file doesn't exist
- `cp -a source target` uses permissions of `source` if `target` exists, and *also* uses permissions of the current user if the target file doesn't exist

Suggested;

- use an `--inherit-ownership` flag (but open to suggestions)
- if target does _not_ exist, give the file ownership of the container user (instead of `root`)
- if target file _does_ exist, give the file ownership of the `source` file.
- add another flag (suggestions as well) to force files maintaining ownership of the source files


/cc @cpuguy83

**Comment by erikh** [comment]
interesting. I can patch this in but it seems surprising (at least, I
didn't realize it merged permissions) from a behavior standpoint. Is there
any justification out there I can read? Mostly just curious.

what do you want to do about permission bits (if anything)? preserve host?
Not sure it's relevant, but might be a good time to discuss that while
we're here.

**Comment by cpuguy83** [comment]
> if target file does exist, give the file ownership of the source file.

Wouldn't the new file inherit ownership from the target file?

> Is there any justification out there I can read? Mostly just curious.

Open source fire hose.
Probably something like "we want to add this!", "ok, sounds awesome!", "woohoo docker cp is now a thing!"

**Comment by erikh** [comment]
Maybe I'm misunderstanding something; are those `/bin/cp` (aka POSIX) rules
or something else?

I guess I should just look this up myself haha

**Comment by erikh** [comment]
This is quite clear on what should be done, at least. I'll save the thread
the rest. http://pubs.opengroup.org/onlinepubs/9699919799/utilities/cp.html

**Comment by erikh** [comment]
@thaJeztah were those literal instructions or was there more discussion to be had here?

**Comment by erikh** [comment]
helooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by duglin** [comment]
@erikh this assumes that the UID of the files being copied are mapped/defined in the container, right? And if not then will things default to root or will be assigned a potentially "unknown owning id" ?

**Comment by erikh** [comment]
Nothing in unix requires the user to be in /etc/passwd for items that live
on the filesystem. Why should this?

**Comment by erikh** [comment]
I misunderstood. I'll have to review whether this is tested or not, but
yes, I expect this behavior to be assigned an unregistered UID.

**Comment by duglin** [comment]
yea, but I'm asking for 2 reasons. 1) to make sure I understand what will happen - and it sounds like the result of a "docker cp" could result in files being copied into the container that aren't owned by any existing user.  And 2) is this really what people would expect?  When I do a vanilla 'cp' the resulting files are owned by me, not the original user. 

I believe this PR would require users to check the ownership of the src files to see if they match an existing ID in the container and if not then do a chmod on them to do anything useful with them. Is that correct?

Is it not possible to use the "user" of the container instead? It seems better for users to know for sure what to expect - either 'root' or 'the user that's running the container' instead of (potentially) some random UID.

**Comment by erikh** [comment]
Hmm. Let me double check but I agree, this should at least be a toggle but
default to the user (especially for the builder).

**Comment by erikh** [comment]
I tried to amalgamate rules here, so I've provided a `cp -a` which preserves host uid/gid ownership. In the event that a non-root USER is specified for the container config, it will be used by default to own the files. Otherwise, the existing behavior is preserved.

**Comment by erikh** [comment]
These tests will likely not pass yet, but it'd be good to get some feedback before I put work into them.

You can test this easily by hand in the meantime:

Dockerfile:

```
FROM ubuntu
RUN useradd -m -d /home/erikh -s /bin/bash erikh
USER erikh
```

Commands to verify:

```
$ docker build -t an-user .
$ docker run -itd --name an-user an-user
$ sudo chown nobody:nogroup Dockerfile  
$ docker cp Dockerfile an-user:.
$ docker exec -it an-user ls -l Dockerfile # note it is as 'erikh'
$ docker cp -a Dockerfile an-user:.
$ docker exec -it an-user ls -l Dockerfile # should be nobody:nogroup.
```

**Comment by LK4D4** [comment]
@tonistiigi what do you think about new design?

**Comment by tonistiigi** [comment]
Design LGMT 
@jlhawn

**Comment by jlhawn** [comment]
Just to clarify the design and changed behavior:

- This only affects copying from the local host to a container, not copying from a container to the local host.
- `docker cp source container:destination` will create the files at the destination to be owned by the `uid:gid` of the container process.
- `docker cp -a source container:destination` will create the files at the destination and preserve the `uid:gid` of the source files (respecting remapped `uid:gid` in the container).

👍  SGTM

**Comment by LK4D4** [comment]
@erikh looks like we can proceed with fixing CI :)

**Comment by erikh** [comment]
I'm moving. It'll be a a few days probably.

Thanks!

**Comment by erikh** [comment]
I should be able to do this later today. Please don't close this just yet.

**Comment by anusha-ragunathan** [comment]
@erikh : Any updates on fixing failing CI?

Do you also plan to add preserve permissions while copying from container to host?
Also, what happens to Windows `docker cp -a`? If there's no support for this option on Windows, cli/API should use build tags to scope them.

**Comment by erikh** [comment]
Sorry; I have been terribly busy for a few weeks, and then after that, got
distracted by my own works, and promptly forgot about this. Sorry!

I will do my best to address this tomorrow. I think I can tear through this
fairly quick now that we have settled on something.

**Comment by erikh** [comment]
I think this will pass, but perhaps I'm jumping the gun. I'll try to keep an eye on it.

This is how I propose it be solved, please let me know if it needs any adjustment.

**Comment by erikh** [comment]
OK I really have no idea what these failures are about.

File: integration-cli/docker_cli_cp_to_container_unix_test.go [hunk 1]
```diff
@@ -14,6 +14,29 @@ import (
...
+
+	containerName := "permtest"
+
+	_, exc := dockerCmd(c, "create", "--name", containerName, "debian", "/bin/bash", "-c", "stat -c '%u %g %a' /permdirtest /permdirtest/permtest")
+	c.Assert(exc, checker.Equals, 0)
+	defer dockerCmd(c, "rm", "-f", containerName)
+
+	srcPath := cpPath(tmpDir, "permdirtest")
+	dstPath := containerCpPath(containerName, "/")
+	c.Assert(runDockerCp(c, srcPath, dstPath, nil), checker.IsNil)
```
Comment (anusha-ragunathan) [inline integration-cli/docker_cli_cp_to_container_unix_test.go]: This should be `runcDockerCp(c, srcPath, dstPath, "a")`, yes?

File: integration-cli/docker_cli_cp_to_container_unix_test.go [hunk 2]
```diff
@@ -14,6 +14,29 @@ import (
 	"github.com/go-check/check"
 )
 
+func (s *DockerSuite) TestCpToHostWithPermissions(c *check.C) {
```
Comment (anusha-ragunathan) [inline integration-cli/docker_cli_cp_to_container_unix_test.go]: Better to rename as `TestCpToContainerWithPermissions`

File: integration-cli/docker_cli_cp_utils.go [hunk 3]
```diff
@@ -55,31 +59,33 @@ func mkFilesCommand(fds []fileData) string {
...
+	{ftRegular, "dir4/file3-1", "file4-1", 0, 0, 0666},
+	{ftRegular, "dir4/file3-2", "file4-2", 0, 0, 0666},
+	{ftDir, "dir5", "", 0, 0, 0666},
+	{ftSymlink, "symlinkToFile1", "file1", 0, 0, 0666},
+	{ftSymlink, "symlinkToDir1", "dir1", 0, 0, 0666},
+	{ftSymlink, "brokenSymlinkToFileX", "fileX", 0, 0, 0666},
+	{ftSymlink, "brokenSymlinkToDirX", "dirX", 0, 0, 0666},
+	{ftSymlink, "symlinkToAbsDir", "/root", 0, 0, 0666},
+	{ftDir, "permdirtest", "", 2, 2, 0700},
+	{ftRegular, "permdirtest/permtest", "perm_test", 65534, 65534, 0400},
```
Comment (anusha-ragunathan) [inline integration-cli/docker_cli_cp_utils.go]: This can be loose the parent directory and simplify creating the file directly under `permdirtest`. i.e `ftRegular, "permtest", "perm_test"...`

File: integration-cli/docker_cli_cp_to_container_unix_test.go [hunk 4]
```diff
@@ -14,6 +14,29 @@ import (
...
+	testRequires(c, SameHostDaemon, DaemonIsLinux)
+
+	tmpDir := getTestDir(c, "test-cp-to-host-with-permissions")
+	defer os.RemoveAll(tmpDir)
+
+	makeTestContentInDir(c, tmpDir)
+
+	containerName := "permtest"
+
+	_, exc := dockerCmd(c, "create", "--name", containerName, "debian", "/bin/bash", "-c", "stat -c '%u %g %a' /permdirtest /permdirtest/permtest")
```
Comment (anusha-ragunathan) [inline integration-cli/docker_cli_cp_to_container_unix_test.go]: `stat` check can be simplified to `stat -c '%u %g %a' /permdirtest/permtest` in conjunction with https://github.com/docker/docker/pull/28923/files#r102597103

**Comment by erikh** [comment]
I'll try to get these changes integrated tomorrow. Thanks for the review!

File: daemon/archive.go [hunk 5]
```diff
@@ -257,13 +257,18 @@ func (daemon *Daemon) containerExtractToDir(container *container.Container, path
...
 
-	uid, gid := daemon.GetRemappedUIDGID()
-	options := &archive.TarOptions{
-		NoOverwriteDirNonDir: noOverwriteDirNonDir,
-		ChownOpts: &archive.TarChownOptions{
-			UID: uid, GID: gid, // TODO: should all ownership be set to root (either real or remapped)?
-		},
+	options := daemon.defaultTarCopyOptions(noOverwriteDirNonDir)
+
+	if !copyUIDGID {
```
Comment (anusha-ragunathan) [inline daemon/archive.go]: Shouldnt this be `if copyUIDGID`, given that `tarCopyOptions` does the userID lookup?

**Comment by anusha-ragunathan** [comment]
@erikh : Any updates to review comments?

**Comment by vdemeester** [comment]
ping @erikh 👼

**Comment by erikh** [comment]
Sorry, I keep forgetting about this!

I will address it this weekend.

-Erik

**Comment by erikh** [comment]
Working on this now; sorry for the extreme delay!

**Comment by erikh** [comment]
@anusha-ragunathan hey, sorry for the wait but I hope I have addressed your comments. PTAL.

**Comment by anusha-ragunathan** [comment]
Code LGTM.

One thing I noticed is `TestCpToContainerWithPermissions` takes 10s to run, while a very similar test like `TestCpCheckDestOwnership` takes only 0.651s. Main difference being the latter doesnt start a container to stat files and also the absence of the new `-a` option. Can you explain why the new test takes so long?

Also, I think the janky test failure is unrelated.

**Comment by erikh** [comment]
I'm not sure. I'll look into it tonight.

**Comment by erikh** [comment]
no idea; if you have any suggestions or clues that'd be great.

**Comment by anusha-ragunathan** [comment]
@erikh : Use `debian:jessie` instead of `debian` in https://github.com/erikh/docker/blob/a52ae4b6491afe07c7a09786ca11c224112ec040/integration-cli/docker_cli_cp_to_container_unix_test.go#L27, so that CI uses the frozen images and not pulling from Hub, which is what was causing the extra time.

**Comment by anusha-ragunathan** [comment]
I get `PASS: docker_cli_cp_to_container_unix_test.go:17: DockerSuite.TestCpToContainerWithPermissions  0.943s` once this is done.

**Comment by anusha-ragunathan** [comment]
That's probably why the test fails on powerpc and s390 as well.

**Comment by erikh** [comment]
ah ok! Will update tonight. Thanks.

**Comment by erikh** [comment]
Tests are running now, I'll validate later today.

**Comment by anusha-ragunathan** [comment]
LGTM

**Review by estesp — APPROVED** [review]
LGTM

**Comment by estesp** [comment]
@thaJeztah are there any follow-on doc changes needed for the new `-a` flag? I know it will automatically get into the help output of `docker cp`, but wasn't sure if there are other docs that need an update.

**Comment by anusha-ragunathan** [comment]
Changelog needs update and I've added the label so that it gets tracked.

**Comment by javabrett** [comment]
I'm been doing some work on #34096 and wondered if (other than what is in the updated docs for `docker cp -a`) whether there is any more detail on the intended behaviour.  Something like:

* `docker cp` without `-a`: behaviour should be unchanged - files are copied to the container as `root:root` ownership.
  * need to check what happens when running with `--user`
  * need to check impact of `--userns`
* `docker cp -a` should:
  * copy verbatim the `uid:gid` of the local file into the container.  The remote `uid:gid` might not exist.
  * any special handling for `--user`?
  * any special handling for `--userns`?
