### PR TITLE
overlay2: support "userxattr" option (kernel 5.11)

### LINKED ISSUE #42055: [kernel 5.11 + overlay2 + rootless] : apt-get fails with `Invalid cross-device link`
# Workaround: use fuse-overlayfs
Workaround until https://github.com/moby/moby/pull/42068 gets merged in Docker v20.10.X / v21.X.X:
```console
curl -o $HOME/bin/fuse-overlayfs -fsSL https://github.com/containers/fuse-overlayfs/releases/download/v1.4.0/fuse-overlayfs-$(uname -m)

chmod +x $HOME/bin/fuse-overlayfs

echo '{"storage-driver": "fuse-overlayfs"}' > ~/.config/docker/daemon.json

systemctl --user restart docker
```
- - - 

**Description**

Kernel 5.11 added official support for rootless: https://github.com/torvalds/linux/commit/459c7c565ac36ba09ffbf24231147f408fde4203 

But it does not work with rootless Docker yet.

**Steps to reproduce the issue:**

```console
$ dockerd-rootless-setuptool.sh install
$ export DOCKER_HOST=unix://${XDG_RUNTIME_DIR}/docker.sock
$ docker run --rm ubuntu sh -ec "apt-get update && apt-get install -y sl"
Get:1 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]
Get:2 http://security.ubuntu.com/ubuntu focal-security InRelease [109 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:4 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [670 kB]
Get:5 http://archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]
Get:6 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [11.3 MB]
Get:7 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [621 kB]
Get:8 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [165 kB]
Get:9 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [13.3 kB]
Get:10 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages [1275 kB]
Get:11 http://archive.ubuntu.com/ubuntu focal/restricted amd64 Packages [33.4 kB]
Get:12 http://archive.ubuntu.com/ubuntu focal/multiverse amd64 Packages [177 kB]
Get:13 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [198 kB]
Get:14 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [932 kB]
Get:15 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [1029 kB]
Get:16 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [21.1 kB]
Get:17 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [4301 B]
Fetched 17.1 MB in 6s (3046 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  sl
0 upgraded, 1 newly installed, 0 to remove and 6 not upgraded.
Need to get 12.7 kB of archives.
After this operation, 60.4 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal/universe amd64 sl amd64 5.02-1 [12.7 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 12.7 kB in 1s (14.9 kB/s)
Selecting previously unselected package sl.
(Reading database ... 4121 files and directories currently installed.)
Preparing to unpack .../archives/sl_5.02-1_amd64.deb ...
Unpacking sl (5.02-1) ...
dpkg: error processing archive /var/cache/apt/archives/sl_5.02-1_amd64.deb (--unpack):
 unable to install new version of './usr/share/doc/sl': Invalid cross-device link
Errors were encountered while processing:
 /var/cache/apt/archives/sl_5.02-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Describe the results you received:**
apt-get failed: 
```
...
dpkg: error processing archive /var/cache/apt/archives/sl_5.02-1_amd64.deb (--unpack):
 unable to install new version of './usr/share/doc/sl': Invalid cross-device link
...
```

**Describe the results you expected:**

It should succeed.

**Additional information you deem important (e.g. issue happens only occasionally):**

The issue is only reproducible on mainline kernel 5.11: https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.11/amd64/

The issue does not happen on Canonical's kernel 5.8 (`5.8.0-43-generic #49-Ubuntu`), which supports rootless overlayfs by patching the kernel: https://kernel.ubuntu.com/git/ubuntu/ubuntu-groovy.git/commit/fs/overlayfs?h=Ubuntu-5.8.0-43.49&id=32e59dd0ef5746a61198c1a18d2ab57c83d28599

Rootful mode is unaffected.

**Output of `docker version`:**

```
Client:
 Version:           20.10.0-dev
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        70a00157f
 Built:             Mon Feb 22 05:46:24 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          dev
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       bc6f4cc703
  Built:            Mon Feb 22 05:45:16 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.5.0-beta.1-24-g096e99fe7
  GitCommit:        096e99fe7e3febdc96df26f743d45d18b8087b6d
 runc:
  Version:          1.0.0-rc93+dev
  GitCommit:        f245a1d1edbf545549e5a16106cf1aec356a3c7d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: dev
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 096e99fe7e3febdc96df26f743d45d18b8087b6d
 runc version: f245a1d1edbf545549e5a16106cf1aec356a3c7d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  rootless
  cgroupns
 Kernel Version: 5.11.0-051100-generic
 Operating System: Ubuntu 20.10
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.6GiB
 Name: suda-ws01
 ID: CWVR:KJQU:3CNT:IJF7:FMME:22Y7:GKFW:AFKJ:IVLQ:JOVW:3KZY:S25M
 Docker Root Dir: /home/suda/.local/share/docker
 Debug Mode: false
 Username: akihirosuda
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No kernel memory limit support
WARNING: No oom kill disable support
```

### PR DESCRIPTION
**Pull request by AkihiroSuda**
**- What I did**

Fix  #42055 "[kernel 5.11 + overlay2 + rootless] : apt-get fails with `Invalid cross-device link`"

**- How I did it**

Support "userxattr" option (kernel 5.11).

The "userxattr" option is needed for mounting overlayfs inside a user namespace with kernel >= 5.11.

The "userxattr" option is NOT needed for the initial user namespace (aka "the host").

Also, Ubuntu (since circa 2015) and Debian (since 10) with kernel < 5.11 can mount the overlayfs in a user namespace without the "userxattr" option.

The corresponding kernel commit: torvalds/linux@2d2f2d7322ff43e0fe92bf8cccdc0b09449bf2e1
> **ovl: user xattr**
>
> Optionally allow using "user.overlay." namespace instead of "trusted.overlay."
> ...
> Disable redirect_dir and metacopy options, because these would allow privilege escalation through direct manipulation of the
> "user.overlay.redirect" or "user.overlay.metacopy" xattrs.
    
Related to containerd/containerd#5076

**- How to verify it**
- Install Ubuntu 20.10
- Install mainline kernel 5.11 https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.11/amd64/
- Launch rootless dockerd with `overlay2` storage driver.
- Make sure `docker --context=rootless run -it --rm ubuntu sh -ec "apt-get update && apt-get install -y sl"`  succeeds without an error (#42055).

**- Description for the changelog**

overlay2: support "userxattr" option (kernel 5.11)

**- A picture of a cute animal (not mandatory but encouraged)**
:penguin:

### CODE REVIEW

File: daemon/graphdriver/overlay2/overlay.go [hunk 1]
```diff
@@ -15,6 +15,7 @@ import (
 	"strings"
 	"sync"
 
+	ctdoverlay "github.com/containerd/containerd/snapshots/overlay"
```
Comment (AkihiroSuda) [inline daemon/graphdriver/overlay2/overlay.go:18]: RFC: do we want to import this to reduce code copypasta, or do we want to just copy the code without introducing dependency on gh/c/c/snapshots ?

**Comment by AkihiroSuda** [comment]
Moving out of draft.

@thaJeztah @tiborvass @StefanScherer Can we have a new release with this ASAP, before people begin using kernel 5.11 next month (Ubuntu 21.04 & Fedora 34)?

File: daemon/graphdriver/overlay2/overlay.go (hunk 1 above)
Comment (thaJeztah) [reply daemon/graphdriver/overlay2/overlay.go:18]: Hm... good one; "generally" I'd say "don't duplicate", but in this case; some thoughts;

- the code currently lives in containerd's overlay snapshotter code (which we _don't_ need)
  - _if_ we want to use the containerd code, I'd prefer it to be refactored to be in (e.g.) containerd/containerd/snapshots/overlay/utils` (or `overlayutils`)
  - in that case, we should also check what the overlap is between our "overlayutils" and the "containerd" one; for example, [`supportsMultipleLowerDir()`](https://github.com/containerd/containerd/blob/ddf6594fbeeddf30a55e0d2bcdb85956ec792fd2/snapshots/overlay/check.go#L34-L41) looks to be a fork of our `overlayutils` package
- (this depends a bit on how 'stable' that part of the code is, because the downside of depending on it from containerd means that if we need a fix in that code, we need to update the _whole_ containerd dependency (which could bring a lot of additional / updated dependencies due to how it's structured)

From the above, I'm tempted to say;

1. Start with copying the check to our own `graphdriver/overlayutils` package
2. After that (follow-up), refactor containerd to have it in a `(overlay)utils` package
3. Look at the overlap between our `overlayutils` and containerd's utils, and consider replacing our overlayutils with the one from containerd

Comment (thaJeztah) [reply daemon/graphdriver/overlay2/overlay.go:18]: @cpuguy83 @tonistiigi WDYT?

**Review by thaJeztah — CHANGES_REQUESTED** [review]

File: daemon/graphdriver/overlay2/overlay.go (hunk 1 above)
Comment (AkihiroSuda) [reply daemon/graphdriver/overlay2/overlay.go]: updated

File: daemon/graphdriver/overlayutils/userxattr.go [hunk 2]
```diff
@@ -0,0 +1,116 @@
...
+	// Keep in mind that distro vendors might be going to backport the patch to older kernels.
+	// So we can't completely remove the "slow path".
+	if kernel.CheckKernelVersion(5, 11, 0) {
+		return true, nil
+	}
+
+	tdRoot := filepath.Join(d, "userxattr-check")
+	if err := os.RemoveAll(tdRoot); err != nil {
+		logrus.WithError(err).Warnf("Failed to remove check directory %v", tdRoot)
+	}
```
Comment (thaJeztah) [inline daemon/graphdriver/overlayutils/userxattr.go:71]: Is there a reason we're removing here, but also in the defer? Is this to cleanup the test-dir from a previous daemon start?

(if so; would it be better to create a tempdir, so that we don't reuse the same directory?)

File: daemon/graphdriver/overlay2/overlay.go [hunk 3]
```diff
@@ -204,7 +205,16 @@ func Init(home string, options []string, uidMaps, gidMaps []idtools.IDMap) (grap
...
-	logger.Debugf("backingFs=%s, projectQuotaSupported=%v, indexOff=%q", backingFs, projectQuotaSupported, indexOff)
+	needsUserXattr, err := overlayutils.NeedsUserXAttr(home)
+	if err != nil {
+		logger.Warnf("Unable to detect whether overlay kernel module needs \"userxattr\" parameter: %s", err)
+	}
+	if needsUserXattr {
+		userxattr = "userxattr,"
+	}
+
+	logger.Debugf("backingFs=%s, projectQuotaSupported=%v, indexOff=%q, userxattr=%q",
```
Comment (cpuguy83) [inline daemon/graphdriver/overlay2/overlay.go:216]: Can we remove this from the `init`?

**Review by cpuguy83 — CHANGES_REQUESTED** [review]

File: daemon/graphdriver/overlay2/overlay.go (hunk 3 above)
Comment (AkihiroSuda) [reply daemon/graphdriver/overlay2/overlay.go:216]: This Debugf is not new in this PR.

File: daemon/graphdriver/overlayutils/userxattr.go (hunk 2 above)
Comment (AkihiroSuda) [reply daemon/graphdriver/overlayutils/userxattr.go:71]: Intentionally reusing the same directory to avoid filling up the root directory with unmountable dirs. Discussed in https://github.com/containerd/containerd/pull/5076#discussion_r582147498

Comment (thaJeztah) [reply daemon/graphdriver/overlayutils/userxattr.go:71]: Ah, thanks for explaining, yes, that makes sense.

I think a comment explaining would be useful (perhaps an inline `cleanup()` function that's called both here, and in the `defer`, but ok to leave for a follow-up)

File: daemon/graphdriver/overlayutils/userxattr.go [hunk 4]
```diff
@@ -0,0 +1,116 @@
...
+
+	for _, dir := range []string{"lower1", "lower2", "upper", "work", "merged"} {
+		if err := os.Mkdir(filepath.Join(td, dir), 0755); err != nil {
+			return false, err
+		}
+	}
+
+	opts := []string{
+		fmt.Sprintf("lowerdir=%s:%s,upperdir=%s,workdir=%s", filepath.Join(td, "lower2"), filepath.Join(td, "lower1"), filepath.Join(td, "upper"), filepath.Join(td, "work")),
+		"userxattr",
```
Comment (thaJeztah) [inline daemon/graphdriver/overlayutils/userxattr.go:96]: We can probably combine this check with `SupportsOverlay()` (adding a parameter to check with `userxattr` set); I'll look at that in a follow-up

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by AkihiroSuda** [comment]
@thaJeztah @tonistiigi 

Can we merge this PR as-is without revendoring containerd, or do we need to revendor https://github.com/containerd/containerd/pull/5204 ?

This needs to be cherry-picked into v20.10 (ASAP), so I'm not sure we want to revendor containerd.

**Comment by thaJeztah** [comment]
> Can we merge this PR as-is without revendoring containerd, or do we need to revendor containerd/containerd#5204 ?
> This needs to be cherry-picked into v20.10 (ASAP), so I'm not sure we want to revendor containerd.

yes; we should merge this with the current (copied) code, especially for that reason (we don't want to be updating containerd vendor code in the 20.10 branch, unless there's a really important reason).

After this is merged, we can look at re-vendoring containerd (I'll be opening a PR today probably, to test) for 21.xx

**Comment by thaJeztah** [comment]
@cpuguy83 PTAL

File: daemon/graphdriver/overlay2/overlay.go (hunk 3 above)
Comment (thaJeztah) [reply daemon/graphdriver/overlay2/overlay.go:216]: I'm personally ok with keeping this (for now) as it's not new indeed.

Looking at the code, I also want to do some refactoring after this is merged; the string-concatting code is becoming a  bit messy and, assuming that won't affect performance, I'd like to use a `[]string` for these options, and `strings.Join()` them at the end (I think that will make the code more readable).

Comment (cpuguy83) [reply daemon/graphdriver/overlay2/overlay.go:216]: Oh this was a github UI issue, its not in the init like I thought.

**Review by tonistiigi — APPROVED** [review]

**Review by cpuguy83 — APPROVED** [review]
LGTM
