### PR TITLE
Explicitly set MTU on bridge devices.

### LINKED ISSUE #37937: Changing MTU of default bridge network doesn´t work
**Description:**
docker0 network interface doesn´t change de MTU settings according to /etc/docker/daemon.json file.

**Steps to reproduce the issue:**
1. Create a /etc/docker/daemon.json file with below content:

`
 {
  "bip": "172.17.0.200/24",
  "mtu": 1400
}
`

2. Restart the docker service;
3. Check docker0 interface MTU settings.

**Describe the results you received:**
docker0 interface remains with the default MTU configuration (1500).

> [xxx@yyy ~]$ sudo ifconfig docker0
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.200  netmask 255.255.255.0  broadcast 172.17.0.255
        ether 02:42:1c:cb:b1:be  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Describe the results you expected:**
I expected to update the mtu value of docker0 interface after restarting the service.

**Additional information you deem important (e.g. issue happens only occasionally):**
I´ve change the bip just to make sure that dockerd is reading the /etc/docker/daemon.json file.
I´m running docker on a server over OpenStack. The configuration of MTU is mandatory to work without huge performance impacts.

**Output of docker version:**
[xxx@yyy ~]$ sudo docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:25:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false

**Output of docker info:**

[xxx@yyy ~]$ sudo docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.06.1-ce
Storage Driver: devicemapper
 Pool Name: docker-8:1-50437250-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Udev Sync Supported: true
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 11.73MB
 Data Space Total: 107.4GB
 Data Space Available: 51.7GB
 Metadata Space Used: 581.6kB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.147GB
 Thin Pool Minimum Free Space: 10.74GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.146-RHEL7 (2018-01-22)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.14.4.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.51GiB
Name: ***SUPRESSED BY MYSELF***
ID: UTZ5:7H4Q:I7YK:F43L:B5HQ:Q24M:RJIR:7ZKR:DOAN:Y65M:M4KK:PTDY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.

### PR DESCRIPTION
**Pull request by robmry**
**- What I did**

This is purely cosmetic - if a non-default MTU is configured, the bridge will have the default MTU=1500 until a container's 'veth' is connected and an MTU is set on the veth.

That's a disconcerting, it looks like the config has been ignored - so, set the bridge's MTU explicitly.

Closes #37937

**- How I did it**

When a bridge is created or updated, set its MTU to the configured value.

**- How to verify it**

Updated integration tests.

**- Description for the changelog**

Explicitly set MTU on bridge devices.

### CODE REVIEW

**Comment by thaJeztah** [comment]
Are there any possibly consequences of doing this? I saw your reply on the ticket, and was wondering if there's any reason we took this approach (e.g. "we don't own the bridge, so don't touch it directly"), but looking at existing code, IIUC, we're already modifying things, so guess that's not the case.

Also from your other comment;

> ... but a Linux bridge's MTU is the min MTU of any device connected to it. When a 'veth' device is added to the bridge to connect a container, the MTU is set on that 'veth'.

Does setting the value here limit what range can be set on the veth? Or no effect there either?


(sorry if these are silly questions, just trying to see the scope of this change)

**Comment by robmry** [comment]
Thank you for taking a look - fair questions! ...

> Are there any possibly consequences of doing this? I saw your reply on the ticket, and was wondering if there's any reason we took this approach (e.g. "we don't own the bridge, so don't touch it directly"), but looking at existing code, IIUC, we're already modifying things, so guess that's not the case.

Explicitly setting the bridge's MTU stops it from taking the min value of anything that's hooked up to it - it'll just keep the value it was given.

The MTU config belongs to the bridge, not the container. So, any 'veth' that's set up for a new container will get the same MTU as bridge.

So, I think it's ok. Unless there's any daemon-restart case I'm not aware of?

(I tried changing the config and bouncing the daemon with `live-restore` set ... the new config had no effect on the bridge or veths for new containers until the deamon was non-live-restore restarted - presumably as-expected.)

_I see I've broken a couple of Windows tests by using netlink in an integration test - I'll sort that out._

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@akerouanton @corhere PTAL

**Review by corhere — APPROVED** [review]

**Comment by thaJeztah** [comment]
Let me bring this one in

**Comment by ivasilyev-mxr** [comment]
@robmry Hello, this seems to cause issues setting the MTU above 1500 ? 

Trying to restart the daemon setting a `mtu:  >1500` in the config hits this error https://github.com/moby/moby/pull/46849/files#diff-77245372071f1b23e0b41e6ac4bd8212a33512dce6159146fff873d3da252c75R50 with message `Invalid Argument`.

Tried deleting the `docker0` device manually, deleting out `<docker-root>/network/*` to let docker re-create those fresh on start, and still same issue

**Comment by thaJeztah** [comment]
@ivasilyev-mxr thanks for reporting; could you open a ticket for this with details (and steps to reproduce)? It's easy for comments on merged PRs to get lost 😅

**Comment by ivasilyev-mxr** [comment]
Hi @thaJeztah thanks, I have created an issue: https://github.com/moby/moby/issues/47308

**Comment by thaJeztah** [comment]
Thank you!

File: libnetwork/drivers/bridge/bridge_linux.go [hunk 1]
```diff
@@ -735,6 +735,14 @@ func (d *driver) createNetwork(config *networkConfiguration) (err error) {
 		bridgeSetup.queueStep(setupDefaultSysctl)
 	}
 
+	// Always set the bridge's MTU if specified. This is purely cosmetic; a bridge's
+	// MTU is the min MTU of device connected to it, and MTU will be set on each
+	// 'veth'. But, for a non-default MTU, the bridge's MTU will look wrong until a
+	// container is attached.
```
Comment (corhere) [inline libnetwork/drivers/bridge/bridge_linux.go:741]: This is not purely cosmetic: on Linux 4.17 and newer, manually setting the MTU disables MTU auto tuning. https://github.com/torvalds/linux/commit/804b854d374e39f5f8bff9638fd274b9a9ca7d33

Comment (robmry) [reply libnetwork/drivers/bridge/bridge_linux.go:741]: The MTU is defined for the network, and all the endpoints attached to the bridge get that MTU. So, auto tuning would select the network's MTU ... and, I thought, the only effect of setting it explicitly on the bridge would be to have it report that MTU before an endpoint was attached (so, cosmetic in that sense).

I don't have laptop access at the moment  (won't be properly back online until Tues) - but if this change is shown to be causing problems, we should just revert it.

Comment (corhere) [reply libnetwork/drivers/bridge/bridge_linux.go:741]: Sorry, I'm speaking in a more general sense that setting the MTU on a Linux Ethernet Bridge is sticky on newer kernels, whereas on older kernels it would get clobbered every time a link is attached to it. Since we control all the links and set the MTU on all of them to the bridge MTU, it's a distinction without a difference _to the libnetwork bridge driver_ unless someone manually changes the MTU of host-side veths. I don't think we need to revert [once we patch the bridge driver `setupMTU()` to ignore `-EINVAL`](https://github.com/moby/moby/issues/47308#issuecomment-1924193313).

Comment (ivasilyev-mxr) [reply libnetwork/drivers/bridge/bridge_linux.go:741]: Forgive the potential dumb question as I am not well versed in linux networking internals.

What will be end result behavior on older version of linux after patching that function to ignore the `EINVAL` error response ? Will it be like it was before this MR and the `docker0` interface will switch to the desired MTU > 1500 once a container is attached ?

Comment (corhere) [reply libnetwork/drivers/bridge/bridge_linux.go:741]: > Will it be like it was before this MR and the `docker0` interface will switch to the desired MTU > 1500 once a container is attached ?

Yes, exactly
