### PR TITLE
client: Make version negotiation thread-safe

### LINKED ISSUE #43729: [go client] negotiateAPIVersionPing triggers Go race detector
**Description**

Creating a Moby/Docker client using `client.NewClientWithOpts(client.WithAPIVersionNegotiation())` and then using this client from multiple goroutines (such as indirectly by requesting an event stream) reproducibly triggers go's race detector in https://github.com/moby/moby/blob/74286cba8c2c14d5360caec44d2da74858e9c707/client/client.go#L251

The go Docker client dependency is:

```
github.com/docker/docker v20.10.17+incompatible
```

**Steps to reproduce the issue:**
1. check out the repository https://github.com/thediveo/whalewatcher
2. in the root of the repository run `go test -v -race ./watcher/moby`

**Describe the results you received:**

```
WARNING: DATA RACE
Write at 0x00c0000a0372 by goroutine 24:
  github.com/docker/docker/client.(*Client).negotiateAPIVersionPing()
      /home/.../go/pkg/mod/github.com/docker/docker@v20.10.17+incompatible/client/client.go:244 +0x184
  github.com/docker/docker/client.(*Client).NegotiateAPIVersion()
      /home/.../go/pkg/mod/github.com/docker/docker@v20.10.17+incompatible/client/client.go:208 +0xe4
  github.com/docker/docker/client.(*Client).getAPIPath()
      /home/.../go/pkg/mod/github.com/docker/docker@v20.10.17+incompatible/client/client.go:184 +0x84
  github.com/docker/docker/client.(*Client).sendRequest()
      /home/.../go/pkg/mod/github.com/docker/docker@v20.10.17+incompatible/client/request.go:109 +0x7c
  github.com/docker/docker/client.(*Client).get()
      /home/.../go/pkg/mod/github.com/docker/docker@v20.10.17+incompatible/client/request.go:37 +0x16c
  github.com/docker/docker/client.(*Client).Events.func1()
      /home/.../go/pkg/mod/github.com/docker/docker@v20.10.17+incompatible/client/events.go:35 +0x1dc
Previous write at 0x00c0000a0372 by goroutine 23:
  github.com/docker/docker/client.(*Client).negotiateAPIVersionPing()
      /home/.../go/pkg/mod/github.com/docker/docker@v20.10.17+incompatible/client/client.go:244 +0x184
  github.com/docker/docker/client.(*Client).NegotiateAPIVersion()
      /home/.../go/pkg/mod/github.com/docker/docker@v20.10.17+incompatible/client/client.go:208 +0xe4
  github.com/docker/docker/client.(*Client).getAPIPath()
      /home/.../go/pkg/mod/github.com/docker/docker@v20.10.17+incompatible/client/client.go:184 +0x84
  github.com/docker/docker/client.(*Client).sendRequest()
      /home/.../go/pkg/mod/github.com/docker/docker@v20.10.17+incompatible/client/request.go:109 +0x7c
  github.com/docker/docker/client.(*Client).get()
      /home/.../go/pkg/mod/github.com/docker/docker@v20.10.17+incompatible/client/request.go:37 +0x584
  github.com/docker/docker/client.(*Client).ContainerList()
      /home/.../go/pkg/mod/github.com/docker/docker@v20.10.17+incompatible/client/container_list.go:48 +0x5c8
  github.com/thediveo/whalewatcher/engineclient/moby.(*MobyWatcher).List()
      /home/.../workspaces/namespaces/whalewatcher/engineclient/moby/moby.go:138 +0x9c
  github.com/thediveo/whalewatcher/watcher.(*watcher).list()
      /home/.../workspaces/namespaces/whalewatcher/watcher/watcher.go:424 +0x94
  github.com/thediveo/whalewatcher/watcher.(*watcher).Watch.func1.1()
      /home/.../workspaces/namespaces/whalewatcher/watcher/watcher.go:232 +0x50
```

**Describe the results you expected:**

Go's race detector doesn't get triggered.

**Additional information you deem important (e.g. issue happens only occasionally):**

- reproducible

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:02:36 2022
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true
Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:00 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., v2.6.0)
Server:
 Containers: 6
  Running: 0
  Paused: 0
  Stopped: 6
 Images: 30
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.13.0-1031-raspi
 Operating System: Ubuntu 21.10
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.625GiB
 Name: ****
 ID: ****
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### PR DESCRIPTION
**Pull request by gtomitsuka**
* Fixes #43729
* Closes #42379

**- What I did**
Currently, `*client.Client` is not safe for concurrent use due to a data race in the version negotiator.

This has been a known issue for three years, and there have been multiple attempts to fix this. I have reviewed the relevant PRs and their discussions and attempt to address the issues the reviewers brought up. 
* #42379: stops the Go race detector from triggering, but will still attempt to negotiate API version multiple times (i.e., doesn't solve the logical data race)
* #43738: had a very large blast area and is very hard to test/review

The key differences are that this PR attempts to maintain very minimal footprint and it **ensures that `NegotiateAPIVersion` is called exactly once**, except in two circumstances:
* when the previous attempt failed
* when manually triggered by the user

**- How I did it**
I introduce `cli.negotiateLock`, a `sync.Mutex` to single-flight the version negotiation process. Additionally, `atomic.Bool` is used to protect the `cli.negotiated` field from data races. This approach ensures synchronisation is only required before negotiation completes.

**- How to verify it**
Minimal working example, which fails before this PR and now passes (call with `go run -race main.go`):
```go
package main

import (
  "context"
  "github.com/docker/docker/api/types/container"
  "github.com/docker/docker/client"
  "sync"
)

func main() {
  var wg sync.WaitGroup
  
  ctx := context.Background()
  cli, err := client.NewClientWithOpts(client.FromEnv, client.WithAPIVersionNegotiation())
  if err != nil {
    panic(err)
  }
  
  for i := 0; i < 2; i++ {
    wg.Add(1)
    go func() {
      defer wg.Done()
      _, err := cli.ContainerCreate(
        ctx,
        &container.Config{
	        Image: "hello-world",
        },
        &container.HostConfig{
	        RestartPolicy: container.RestartPolicy{Name: "no"},
      }, nil, nil, "")
      
      if err != nil {
      panic(err)
      }
    }()
  }
  
  wg.Wait()
  println("success")
}
```

**- Description for the changelog**

```markdown changelog
`*client.Client` instances are now always safe for concurrent use by multiple goroutines. Previously, this could lead to data races when the `WithAPIVersionNegotiation()` option is used.
```

**- A picture of a cute animal (not mandatory but encouraged)**

Meet Bailey (in a jacket)!

IMG_3236

**EDIT (2024-06-13):** Update description to match final, approved version of PR; provide stronger concurrency guarantee following review of #43738 + thorough testing

### CODE REVIEW

**Comment by gtomitsuka** [comment]
Keep in mind this doesn't mean it's safe to add ` -race` to TESTFLAGS in `hack/test/unit`; there are data races in the Docker daemon which would also need to be addressed.

File: client/client.go [hunk 1]
```diff
@@ -267,11 +274,35 @@ func (cli *Client) Close() error {
...
+					return err
+				}
+
+				cli.negotiateAPIVersionPing(ping)
+
+				return nil
+			})
+		}
+
+		err := cli.versionNegotiator()
```
Comment (corhere) [inline client/client.go:296]: `cli.versionNegotiator()` is only ever called inside a `cli.negotiateLock` critical section, meaning at most one goroutine can call it at a time. So there is no need for the synchronization behavior of `sync.OnceValue`. And there is no need to remember the error returned by `cli.Ping()` because, if the ping is successful, `cli.negotiated` gets set to `true` by `cli.negotiateAPIVersionPing()`. It looks to me like `sync.OnceValue` is not useful in this situation; adding complexity without providing any benefit in return.

**Review by corhere — CHANGES_REQUESTED** [review]

File: client/client.go [hunk 2]
```diff
@@ -133,6 +134,12 @@ type Client struct {
 	// negotiated indicates that API version negotiation took place
 	negotiated bool
 
+	// apiVersionNegotiator is a function that runs once on calls to checkVersion.
+	// It is protected by the negotiateLock. The user may bypass this mechanism by
+	// calling NegotiateAPIVersion or NegotiateAPIVersionPing
+	negotiateLock     sync.Mutex
```
[the remark this answers is not in the document]
Comment (gtomitsuka) [reply client/client.go:140]: true, it should be something like versionLock. will change

File: client/client.go (hunk 1 above)
Comment (gtomitsuka) [reply client/client.go:296]: I got to this approach due to #42379; if you allow two functions to enter this part, they may "queue up" to perform the same ping twice. However, I see this can be worked around by extending the critical zone to this function in its entirety (this way, cli.negotiated will have already been set by the next time this is reached).

I was trying to avoid impacting the performance characteristics of this function after the first call since it's called by nearly every *Client method, and I do think this is the only way to get around a mutex for the entire function, but I see that wrapping it in a mutex is clearly the cleaner / more maintainable solution

Comment (gtomitsuka) [reply client/client.go:296]: Alternatively, you could check for cli.negotiated again and early return right after entering the critical zone, but this is very confusing

Comment (gtomitsuka) [reply client/client.go:296]: Upon further inspection, `checkVersion` is called in `NewVersionError`, which means it's called 5 times in `ContainerCreate` alone , twice in `ImageBuild`, and some more times in many other places. Entering a critical zone 5 times every time a container is created doesn't seem optimal either

**Review by corhere — COMMENTED** [review]
Very nice! The synchronization cost is only paid if negotiation is incomplete. I believe that this is an optimal solution.

**Comment by gtomitsuka** [comment]
fixed, thanks for the review @corhere!

File: client/client.go [hunk 3]
```diff
@@ -131,7 +133,10 @@ type Client struct {
 	negotiateVersion bool
 
 	// negotiated indicates that API version negotiation took place
-	negotiated bool
+	negotiated atomic.Bool
+
+	// versionLock protects the version and negotiated fields from concurrent writes
+	versionLock sync.Mutex
```
Comment (corhere) [inline client/client.go:139]: This mutex does more than just protect struct fields. (Besides, the `negotiated` field is an atomic; it can be concurrently written to by multiple goroutines without any data races. And since it gets latched to `true`, there would not be a logical race, either.)
It is more accurate to say that this mutex is used to single-flight the version negotiation process. `negotiateLock` was a good name for that; thoughts on renaming it back?

**Review by corhere — APPROVED** [review]
LGTM, thanks!

**Comment by gtomitsuka** [comment]
Just wondering what the next steps are – is this blocked on anything? cc @thaJeztah @vvoland

**Review by vvoland — APPROVED** [review]
LGTM

**Comment by NishantBansal2003** [comment]
I think it would be better to add a godoc comment to the `Client` struct stating that `*client.Client` instances are now always safe for concurrent use by multiple goroutines?
