### PR TITLE
cmd/dockerd: Add workaround for OTEL meter leak

### LINKED ISSUE #48144: Memory Leak in Docker 27.0.3
### Description

After I updated to Docker 27.0.3 (I do not remember what was the older version, sorry, I upgraded my dedicated servers when the RegreSSHion exploit happened, but technically the older version is a version between 10/01/2024 (when the system was installed) and 01/07/2024 (when I upgraded all packages)) the `dockerd` daemon is leaking memory like crazy, in two of my dedicated servers `dockerd` ends up eating so much memory that containers end up getting OOM'd by the system

image

If I restart Docker, the `dockerd` memory usage drops to ~200MB, and then keeps increasing and increasing and increasing...

### Reproduce

*I don't know how to reproduce this yet*

### Expected behavior

That `dockerd` does not eating up so much memory.

### docker version

```bash
Docker version 27.0.3, build 7d4bcd8
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    27.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.15.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.28.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 68
  Running: 68
  Paused: 0
  Stopped: 0
 Images: 41
 Server Version: 27.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: local
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.5.0-41-generic
 Operating System: Ubuntu 22.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 125.7GiB
 Name: saiyan-seeker
 ID: 3ae68731-57aa-49b8-bc88-c007cbcc3059
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 172.16.0.0/12, Size: 20
   Base: 192.168.0.0/16, Size: 24
```

### Additional Info

Yeah, this issue doesn't really help a lot to figure out what is actually the issue... When I was looking at other comments, I found out that there is a way to create a heap dump of the `dockerd` process, but the link on how to do it is unavailable and it a mirror is not available on the Wayback Machine, so I wonder if someone has a working link about how to do it? https://github.com/moby/moby/issues/39916#issuecomment-532156804

### PR DESCRIPTION
**Pull request by vvoland**
- related to: https://github.com/open-telemetry/opentelemetry-go-contrib/issues/5190
- probably fixes: https://github.com/moby/moby/issues/48144

OTEL meter implementation has a memory leak issue which causes each meter counter invocation to create a new instrument when the meter provider is not set.

Also add a test, which will fail once a fixed OTEL is vendored.

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

```markdown changelog
Fix a possible memory leak caused by OTEL meters
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: cmd/dockerd/daemon.go [hunk 1]
```diff
@@ -244,6 +245,13 @@ func (cli *daemonCLI) start(ctx context.Context) (err error) {
 
 	tp := newTracerProvider(ctx)
 	otel.SetTracerProvider(tp)
+
+	// Workaround OTEL memory leak
+	// See: https://github.com/open-telemetry/opentelemetry-go-contrib/issues/5190
+	// The need for this workaround is checked by the TestOtelMeterLeak test
+	// TODO: Remove this workaround after upgrading to v1.30.0
+	otel.SetMeterProvider(noop.MeterProvider{})
+
```
Comment (thaJeztah) [inline cmd/dockerd/daemon.go:254]: Curious if this should be "as early as possible" in the chain (as a default, which can be overridden by "whatever" will override).

Would this fix still work if we'd put it (e.g.) in `newDaemonCommand` (assuming setting it in `main()` wouldn't make it easy to test)

Comment (vvoland) [reply cmd/dockerd/daemon.go:254]: It would work, but I think it's much better to have it in the same place as other OTEL related stuff. If we'd like to actually override it, we can just remove it as it won't be needed anyway.

Comment (thaJeztah) [reply cmd/dockerd/daemon.go:254]: Yeah, it's also that we don't always know where things are overridden (at least I recall some of the ugly bits where BuildKit setup things in an `init()`.

> but I think it's much better to have it in the same place as other OTEL related stuff


Yeah, even wondering if there's bits around that that we should also set up earlier (making sure that we trace as much as possible, starting with `main` ?)

Comment (vvoland) [reply cmd/dockerd/daemon.go:254]: I can move it to main, so at least it stops the leak earlier. Although that shouldn't be the case as AFAIK the only meter counting on our side come from `otelhttp`.

I don't think it's reasonable for us to consider dependencies silently override the meter provider without our deliberate decision though.

Comment (laurazard) [reply cmd/dockerd/daemon.go]: Agreed.

**Review by laurazard — APPROVED** [review]
LGTM! Thanks @vvoland

File: cmd/dockerd/daemon.go [hunk 2]
```diff
@@ -244,6 +244,7 @@ func (cli *daemonCLI) start(ctx context.Context) (err error) {
 
 	tp := newTracerProvider(ctx)
 	otel.SetTracerProvider(tp)
+
```
Comment (thaJeztah) [inline cmd/dockerd/daemon.go:247]: 🙈

**Review by thaJeztah — APPROVED** [review]
LGTM, thank you!

Assuming this fixes the issue, happy to hear from others of course.

(left some minor nits)

File: cmd/dockerd/daemon.go (hunk 2 above)
Comment (vvoland) [reply cmd/dockerd/daemon.go]: Whoops, sorry, fixed!

File: cmd/dockerd/docker.go [hunk 3]
```diff
@@ -96,6 +99,12 @@ func main() {
 		os.Exit(1)
 	}
 
+	// Workaround OTEL memory leak
+	// See: https://github.com/open-telemetry/opentelemetry-go-contrib/issues/5190
+	// The need for this workaround is checked by the TestOtelMeterLeak test
+	// TODO: Remove this workaround after upgrading to v1.30.0
+	otel.SetMeterProvider(noop.MeterProvider{})
+
```
[the remark this answers is not in the document]
Comment (vvoland) [reply cmd/dockerd/docker.go]: Ah good point, done

**Comment by thaJeztah** [comment]
I added cherry-pick labels for older releases as well, but not sure if those need it, so verify if needed before backporting (it's more as a "reminder") @cpuguy83 @austinvazquez @corhere
