### PR TITLE
builder: handle host-gateway with extra hosts

### LINKED ISSUE #44525: docker buildx fails to validate "--add-host=host.docker.internal:host-gateway"
### Description

When building an image with `docker buildx` on Linux and adding the `--add-host=host.docker.internal:host-gateway` option, it fails because the validation of the `host-gateway` is not an IP address, as required by https://github.com/moby/moby/blob/a263241ea16f1b018fc1c8f5c6564d84f1153543/builder/builder-next/builder.go#L562-L564

`docker buildx` output:

```
$ docker build --add-host=host.docker.internal:host-gateway .

[+] Building 0.0s (0/0)
ERROR: invalid host host.docker.internal:host-gateway
```

`docker build` is able to build the image correctly. In fact, it checks for the `host-gateway` special case: https://github.com/moby/moby/blob/f1dd6bf84e28930e1ccd903361f9284fb22d3b8a/opts/hosts.go#L180-L184

`docker build` output:

```
$ docker build --add-host=host.docker.internal:host-gateway --tag whatever . 

Sending build context to Docker daemon  1.38MB
Step 1/1 : FROM ubuntu:22.04
22.04: Pulling from library/ubuntu
e96e057aae67: Pull complete
Digest: sha256:4b1d0c4a2d2aaf63b37111f34eb9fa89fa1bf53dd6e4ca954d47caebca4005c2
Status: Downloaded newer image for ubuntu:22.04
 ---> a8780b506fa4
Successfully built a8780b506fa4
```

### Reproduce

1. Create a `Dockerfile` with the following contents:

```dockerfile
FROM ubuntu:22.04
```

2. Run `docker buildx --add-host=host.docker.internal:host-gateway .`

### Expected behavior

- `docker buildx` should be able to build the image
- The `host.docker.internal` name should point to the address of the machine running the container

### docker version

```bash
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:02:28 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:00:19 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)

Server:
 Containers: 14
  Running: 1
  Paused: 0
  Stopped: 13
 Images: 549
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1c90a442489720eec95342e1789ee8a5e1b9536f
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.18.16-amd64
 Operating System: Debian GNU/Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 48
 Total Memory: 177.1GiB
 Name: [redacted]
 ID: [redacted]
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by crazy-max**
fixes #44525 

**- What I did**

If the IP Address is a string called `host-gateway`, replace this value with the IP address stored in the daemon level `HostGatewayIP` config variable.

This is the current behavior with the classic builder.

~Keeping in draft for now as it's still subject to discussion~.

Need changes in Buildx client: https://github.com/docker/buildx/blob/23cabd67fb1c5e7ba2e3765e91bd5cc0f0311337/build/utils.go#L41-L56 cc @tonistiigi @jedevc

**- How I did it**

**- How to verify it**

**- Description for the changelog**

handle `host-gateway` with extra hosts.

**- A picture of a cute animal (not mandatory but encouraged)**

Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
> Might also need changes in Buildx client: https://github.com/docker/buildx/blob/23cabd67fb1c5e7ba2e3765e91bd5cc0f0311337/build/utils.go#L41-L56

Ah, yes, see https://github.com/docker/cli/pull/2337


Although, I'm wondering if we should perform validation _at all_ on the client side (basically; perhaps it should always be delegated to the API server to consider if options are valid or not)

**Comment by crazy-max** [comment]
> Although, I'm wondering if we should perform validation at all on the client side (basically; perhaps it should always be delegated to the API server to consider if options are valid or not)

Yes I think it would be better, we already validate extra hosts on BuildKit: https://github.com/moby/buildkit/blob/7804e2c7fc09b4a536934f5607698bc3255cf0ed/frontend/dockerfile/builder/build.go#L751-L775

File: builder/builder-next/builder.go [hunk 1]
```diff
@@ -551,17 +554,26 @@ func (j *buildJob) SetUpload(ctx context.Context, rc io.ReadCloser) error {
...
+		// If the IP Address is a string called "host-gateway", replace this
+		// value with the IP address stored in the daemon level HostGatewayIP
+		// config variable
+		if parts[1] == opts.HostGatewayName {
+			gateway := hostGatewayIP.String()
+			if gateway == "" {
+				return "", fmt.Errorf("unable to derive the IP value for host-gateway")
+			}
+			parts[1] = gateway
+		}
```
Comment (thaJeztah) [inline builder/builder-next/builder.go:576]: Oh! Looks like I missed this one in https://github.com/moby/moby/pull/44381 (perhaps we should change it to `strings.Cut()` here as well;

```suggestion
		host, ip, ok := strings.Cut(h, ":")
		if !ok || host == "" || ip == "" {
			return "", errors.Errorf("invalid host %s", h)
		}
		// If the IP Address is a "host-gateway", replace this value with the
		// IP address stored in the daemon level HostGatewayIP config variable.
		if ip == opts.HostGatewayName {
			gateway := hostGatewayIP.String()
			if gateway == "" {
				return "", fmt.Errorf("unable to derive the IP value for host-gateway")
			}
			ip = gateway
		} else if net.ParseIP(ip) == nil {
			return "", fmt.Errorf("invalid host %s: invalid IP value: %s", host, ip)
		}
```

**Review by tiborvass — APPROVED** [review]
lgtm, but didn't test and kind of unfortunate to have two copies of `toBuildkitExtraHosts` (here and in buildx). Not sure if they can factored since there is currently no way for buildx to retrieve the host-gateway-ip setting from the daemon (not even exposed in /info).

**Comment by thaJeztah** [comment]
> Not sure if they can factored since there is currently no way for buildx to retrieve the host-gateway-ip setting from the daemon (not even exposed in /info).

I think this feature would currently only apply to the docker builder, unless BuildKit itself (running as container-builder) would implement a configuration for this, in which case it would (should?) also do the conversion on the daemon side.

As mentioned in an earlier comment, I think we should remove validation from the client side altogether (other than splitting `key/value` where needed), and leave it to the daemon to return an error if the value is valid or not.

File: builder/builder-next/builder.go (hunk 1 above)
Comment (thaJeztah) [reply builder/builder-next/builder.go:576]: @crazy-max could you have a look at my suggestions if they look good to you?

**Comment by crazy-max** [comment]
> As mentioned in an earlier comment, I think we should remove validation from the client side altogether (other than splitting `key/value` where needed), and leave it to the daemon to return an error if the value is valid or not.

I discussed about this with @tonistiigi yesterday and the validation client-side avoid sending extra build request.

**Review by thaJeztah — APPROVED** [review]
LGTM
