### PR TITLE
Re-validate Mounts on container start

### LINKED ISSUE #35821: docker container start creates host-directory for mount, but shouldn't
As reported by @h45rd in https://github.com/moby/moby/issues/13121#issuecomment-352373883;

**Description**

The `--mount type=bind` option requires the host-directory/file to exist, and produce an error if the path is not found.

Docker correctly produces an error on `docker run` and `docker container create`, but when _starting_ the container (`docker container start`), no error is produced, and the host-path is created instead.

**Steps to reproduce the issue:**

Create a container that bind mounts a non-existing host-directory;

```bash
$ mkdir repro-35821 && cd repro-35821
$ docker create --name repro-35821 \
  --mount type=bind,source="$(pwd)"/once-existed,target=/app \
  busybox
Error response from daemon: invalid mount config for type "bind": bind source path does not exist
```

During create, an error is produced (as expected); this is the correct behaviour.

Now, creating the directory to allow `docker create` to succeed, but _don't start_ the container;

```bash
$ mkdir once-existed
$ docker create --name repro-35821 \
   --mount type=bind,source="$(pwd)"/once-existed,target=/app \
   busybox
a7b4d510d1afd3eabea59414b94e9565af2927606f8a79f27aa855f3a8ea2817
```

Now, remove the directory, and verify the directory is gone;

```bash
$ rm -r once-existed
$ ls
(empty)
```

Start the container, and observe that no error is produced, but host directory is being created;

```bash
$ docker start repro-35821
repro-13121
$ ls
once-existed
```

**Describe the results you received:**

`docker start` / `docker container start` does not produce an error, but creates the host directory

**Describe the results you expected:**

`docker start` / `docker container start` to produce an error and refusing to start if the host directory does not exist.

**Output of `docker version`:**

Reproduced on  Docker 17.11.0, but likely to still exist on current master (can update the issue after updating this machine)

### LINKED ISSUE #36634: Bind mount on container start
**Description**

This is about the bind mount behavior: 

> Note: When creating bind mounts, using the long syntax requires the referenced folder to be created beforehand. Using the short syntax creates the folder on the fly if it doesn’t exist. See the bind mounts documentation for more information.

(source [here](https://docs.docker.com/compose/compose-file/compose-file-v2/#long-syntax))

What works:

    When submitting to Swarm a docker-compose.yml with a service with bind mount, docker-compose refuses to run the service if the source directory does not exist.
    If the container is started with the source directory mounted, if I stop the service, and remove the directory, the container cannot start again, complaining about missing directory.

What does not work:

    If I stop the docker daemon, and remove the directory, then restart docker, then the container start and recreates the directori(es)!

**Steps to reproduce the issue:**
1. Creates a given directory in host (I did that with a MooseFs mount)
2. Starts a container with docker-compose up -d command and with a bind mount in the directory in compose V2.3, and with restart policy set to unless_stopped
3. Stops docker daemon.
4. Removes the given directory (MooseFs umount)
5. Starts deamon docker.

**Describe the results you received:**
The container has started and docker has created empty directories by itself. The application of course crashes because of missing files.

**Describe the results you expected:**
The container should be always restarting as long as the directories is not started and should not creates the directories by itself.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
> sudo docker version
Client:
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.9.4
 Git commit:    7390fc6
 Built: Tue Feb 27 22:15:20 2018
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   7390fc6
  Built:        Tue Feb 27 22:17:54 2018
  OS/Arch:      linux/amd64
  Experimental: false

```

**Output of `docker info`:**

```
Containers: 5
 Running: 2
 Paused: 0
 Stopped: 3
Images: 78
Server Version: 17.12.1-ce
Storage Driver: devicemapper
 Pool Name: docker-252:1-305205681-pool
 Pool Blocksize: 65.54kB
 Thin Pool Minimum Free Space: 10.74GB                                                                                                                                                                                           [22/1951]
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.17.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.26GiB
Name: dev-node-005...............
ID: VSBQ:AQU6:WY2U:PJ7Z:BJAS:IVOK:T5KK:KWW4:7UU3:GEAO:6XR4:6QUH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 com.docker.node=processing
Experimental: false
Cluster Store: zk://dev-node-003:2181,dev-node-007:2181,dev-node-008:2181
Cluster Advertise: 10.0.1.25:2375
Insecure Registries:
 [XXXXXXXXXXXX]:5000
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Almost all latest: docker-ce-17.12.1-ce / CentOs 7.4.1708 / docker-compose 1.19.0 / compose ref 2.3 / Swarm classic 1.2.8.

### PR DESCRIPTION
**Pull request by thaJeztah**
- fixes https://github.com/moby/moby/issues/35821
- fixes https://github.com/moby/moby/issues/36634

Validation of Mounts was only performed on container _creation_, not on container _start_. As a result, if the host-path no longer existed when the container was started, a directory was created in the given location.

This is the wrong behavior, because when using the `Mounts` API, host paths should never be created, and an error should be produced instead.

This patch adds a validation step on container start, and produces an error if the host path is not found.

**- How to verify it**

Create a container that bind-mounts a directory that exists;

```bash
$ mkdir once-existed
$ docker create --name repro-35821 \
   --mount type=bind,source="$(pwd)"/once-existed,target=/app \
   busybox
a7b4d510d1afd3eabea59414b94e9565af2927606f8a79f27aa855f3a8ea2817
```

After creating, remove the directory, and verify the directory is gone;

```bash
$ rm -r once-existed
$ ls
(empty)
```

Verify that the container refuses to start because the directory no longer exists;

```bash
$ docker start repro-35821
Error response from daemon: invalid mount config for type "bind": bind source path does not exist
```

**- Description for the changelog**

```Markdown
* Validate Mount-specs on container start to prevent creating missing host-paths [moby/moby#35833](https://github.com/moby/moby/pull/35833)
```

**- A picture of a cute animal (not mandatory but encouraged)**

bird-sparrow

### CODE REVIEW

File: volume/validate_test.go [hunk 1]
```diff
@@ -31,13 +31,9 @@ func TestValidateMount(t *testing.T) {
 
 		{mount.Mount{Type: mount.TypeBind, Source: testDir, Target: testDestinationPath}, nil},
 		{mount.Mount{Type: "invalid", Target: testDestinationPath}, errors.New("mount type unknown")},
+		{mount.Mount{Type: mount.TypeBind, Source: testSourcePath, Target: testDestinationPath}, errBindNotExist},
 	}
-	if runtime.GOOS == "windows" {
```
Comment (thaJeztah) [inline volume/validate_test.go]: Not sure why this was skipped on Linux; this was done as part of https://github.com/moby/moby/commit/e89b6e8c2d2c36c43f22aeaf2a885646c2994051#diff-6f41eadf3d19741b898f4be682e5d670R35 (https://github.com/moby/moby/pull/34258), but that also added this comment; https://github.com/moby/moby/blame/c492e76d13a61b13815475d1a6393ab1da1db5c8/volume/linux_parser.go#L43-L46

/cc @simonferquel

**Comment by thaJeztah** [comment]
ping @vdemeester @cpuguy83 PTAL

**Review by vdemeester — APPROVED** [review]
LGTM :lion:

**Comment by h45rd** [comment]
Wow. That was fast. And thorough.
Thanks a bunch,  @thaJeztah :)

**Comment by thaJeztah** [comment]
Thank you for finding this one @h45rd! - it's easy to miss these things (as it's not a common scenario to have differences happen between "create" and "start")

**Comment by thaJeztah** [comment]
"experimental" failure is being tracked here; https://github.com/moby/moby/issues/35825;

```
12:47:58 ----------------------------------------------------------------------
12:47:58 FAIL: check_test.go:366: DockerSwarmSuite.TearDownTest
12:47:58 
12:47:58 check_test.go:371:
12:47:58     d.Stop(c)
12:47:58 daemon/daemon.go:395:
12:47:58     t.Fatalf("Error while stopping the daemon %s : %v", d.id, err)
12:47:58 ... Error: Error while stopping the daemon dc53b7acb7a27 : exit status 130
12:47:58 
12:47:58 
12:47:58 ----------------------------------------------------------------------
12:47:58 PANIC: docker_api_swarm_service_test.go:201: DockerSwarmSuite.TestAPISwarmServicesUpdateStartFirst
12:47:58 
12:47:58 [dc53b7acb7a27] waiting for daemon to start
12:47:58 [dc53b7acb7a27] daemon started
12:47:58 
12:47:58 [dc53b7acb7a27] daemon started
12:47:58 Attempt #2: daemon is still running with pid 9575
12:47:58 Attempt #3: daemon is still running with pid 9575
12:47:58 Attempt #4: daemon is still running with pid 9575
12:47:58 [dc53b7acb7a27] exiting daemon
12:47:58 ... Panic: Fixture has panicked (see related PANIC)
12:47:58 
```

**Review by boaz0 — APPROVED** [review]
LGTM 👍

**Comment by kolyshkin** [comment]
LGTM (not a maintainer)

**Review by yongtang — APPROVED** [review]
LGTM

**Comment by coolljt0725** [comment]
LGTM

**Comment by cpuguy83** [comment]
This works. I wonder if maybe we should move the validation to on start instead of on create anyway.

**Comment by thaJeztah** [comment]
I was thinking about that, but thought it would be good to have it on both, so that when _creating_ a container, I get direct feedback (as a user) that the path I'm trying to mount doesn't exist

**Comment by antoinetran** [comment]
Hi, if I understand correctly, this fix will prevent a container to start if the host directory does not exist. Will it retry with a restart policy set to always/unless-stopped/on-failure or just stop immediately? I have a use-case where we use a container to mount a distributed FS (like NFS) in host, and then mount the host directory to a second container, and this fix might be help us to make the second container wait for the host directory to be mounted. Thanks!

**Comment by antoinetran** [comment]
I tested it and it does seem this fix work. But I guess I tested wrong: the fix only applies to a special bind mount with "once-existed"? Because I tested it with regular docker volume mount "docker run -v src:dest:rw".

**Comment by thaJeztah** [comment]
@antoinetran no the `once-existed` is just a name I picked for the test, but this fix is only for the `--mount` flag: the `-v` option will automatically create the host-path if it's missing (we have to keep that behaviour for backward compatibility). The `--mount` option on the other hand, will _fail_ if the host-path is not found.

The fix in this PR makes sure that a container created with the `--mount` option will also fail if the path existed when it was created, but no longer exists when (re)starting the container.

**Comment by antoinetran** [comment]
@thaJeztah ok. Do you happen to know if this type of bind can be described in a docker-compose.yml v2? I couldn't find that answer easily, it does not seems like a common option. If yes, I can try that.

**Comment by thaJeztah** [comment]
@antoinetran I think you can do that using the long syntax a [described in the docker compose file reference](https://docs.docker.com/compose/compose-file/compose-file-v2/#long-syntax).

I recommend checking if that does indeed follow the same semantics, as it may be possible that in the 2.x format it may still be auto-creating the host directories (see the discussion on https://github.com/docker/compose/pull/5490#issuecomment-353401551).

**Comment by antoinetran** [comment]
The expected result for me would be: if I restart docker, a container with restart policy set to unless-stopped/always will try starting many times and will effectively start when the bind mounts conditions will be fulfilled.

**Comment by thaJeztah** [comment]
Thanks for testing! Interesting; could you open an issue for that? Wondering if there's still some codepath somewhere that skips the validation (possibly on container restore after daemon start)

**Comment by agoulti** [comment]
I'm seeing a race condition which is likely related to this: if the directory is removed at a certain point while "docker run" is executing, a root-owned directory is created.

The following script more often than not produces a root-owned directory:

```
sudo rm -rf /tmp/try/nnn
mkdir -p /tmp/try/nnn
echo "before start:"  `ls -ld /tmp/try/nnn`
docker run -u 277174:89939 --mount type=bind,src=/tmp/try/nnn,dst=/test debian  sleep 3 &
sleep 0.5
rm -rf /tmp/try/nnn
echo "before sleep:"  `ls -ld /tmp/try/nnn`
sleep 3
echo "after sleep:"  `ls -ld /tmp/try/nnn`

```

My Docker version is 18.03.0-ce

**Comment by thaJeztah** [comment]
@agulti thanks! Could you open a new issue with details so that it can be looked into?
