### PR TITLE
Fix issue where secret ID is masked by name

### LINKED ISSUE #28884: secret name is able to mask ID
The `docker secret` commands treat `id` and `name` in the wrong order; `id` is
not used as the canonical identifier;

```
echo "foo" | docker secret create foo
i60hm2r8njsrt3gwbuf1oyslj

echo "fake foo" | docker secret create i60hm2r8njsrt3gwbuf1oyslj
j6mljgrakyd75j41b100ss3eb
```

"fake foo" now masks "foo" when doing `docker secret rm`;

```
docker secret ls
ID                          NAME                        CREATED              UPDATED
i60hm2r8njsrt3gwbuf1oyslj   foo                         About a minute ago   About a minute ago
j6mljgrakyd75j41b100ss3eb   i60hm2r8njsrt3gwbuf1oyslj   7 seconds ago        7 seconds ago


docker secret rm i60hm2r8njsrt3gwbuf1oyslj
j6mljgrakyd75j41b100ss3eb

docker secret ls
ID                          NAME                CREATED              UPDATED
i60hm2r8njsrt3gwbuf1oyslj   foo                 About a minute ago   About a minute ago
```

The correct order in which to resolve objects should be;

1. full match on `id`
2. full match on `name`
3. match on _partial_ `id` (`id` "prefix")

### PR DESCRIPTION
**Pull request by yongtang**
**- What I did**

This fix tries to address the issue in #28884 where it is possible to mask the secret ID by name.

The reason was that searching a secret is based on name. However, searching a secret should be done based on:
- Full ID
- Full Name
- Partial ID (prefix)

**- How I did it**

This fix addresses the issue by changing related implementation in `getCliRequestedSecretIDs()`, so that search is based on the above mentioned order.

**- How to verify it**

An integration test has been added to cover the changes.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

cute-kitten-saying-hello

This fix fixes #28884

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

File: cli/command/secret/utils.go [hunk 1]
```diff
@@ -1,47 +1,81 @@
...
 
 	if len(secrets) > 0 {
-		ids = []string{}
+		found := make(map[string]struct{})
 
 		for _, s := range secrets {
-			if _, ok := lookup[s.Spec.Annotations.Name]; ok {
-				ids = append(ids, s.ID)
+			// attempt to lookup secret by full ID
+			if v, ok := lookup[s.ID]; ok && !v {
```
Comment (diogomonica) [inline cli/command/secret/utils.go]: Why do we need the `!v` condition?

File: cli/command/secret/utils.go [hunk 2]
```diff
@@ -1,47 +1,81 @@
...
+		}
+
+		// attempt to lookup secret by partial ID (prefix)
+		for term, v := range lookup {
+			// Only perform the check if both full ID and full name above return no match
+			if !v {
+				for _, s := range secrets {
+					if strings.HasPrefix(s.ID, term) {
+						found[s.ID] = struct{}{}
+						lookup[term] = true
```
Comment (diogomonica) [inline cli/command/secret/utils.go]: why do we need to set this to `true` if there is no other loop/interaction with `lookup` later on?

File: cli/command/secret/utils.go [hunk 3]
```diff
@@ -1,47 +1,81 @@
...
+			// attempt to lookup secret by full name
+			if v, ok := lookup[s.Spec.Annotations.Name]; ok && !v {
+				found[s.ID] = struct{}{}
+				lookup[s.Spec.Annotations.Name] = true
+			}
+
+		}
+
+		// attempt to lookup secret by partial ID (prefix)
+		for term, v := range lookup {
```
Comment (diogomonica) [inline cli/command/secret/utils.go]: Couldn't we turn this whole method into one loop of `for term, v := range lookup` with a break on the first match (full ID, full Name or partial ID)?

Feels like this logic can be simplified/

**Comment by yongtang** [comment]
Thanks @diogomonica for the review. The PR has been updated with logic simplified. Please take a look and let me know if there are any issues.

File: cli/command/secret/utils.go [hunk 4]
```diff
@@ -1,47 +1,69 @@
...
-		ids = []string{}
-
-		for _, s := range secrets {
-			if _, ok := lookup[s.Spec.Annotations.Name]; ok {
-				ids = append(ids, s.ID)
+		found := make(map[string]struct{})
+	next:
+		for _, term := range terms {
+			// attempt to lookup secret by full ID
+			for _, s := range secrets {
```
Comment (diogomonica) [inline cli/command/secret/utils.go]: why three `for _, s := range secrets {` loops? why not just one? They are evaluated in order, so the first one to hit continue would jump to the next term, and we would also not need the next.

Comment (yongtang) [inline cli/command/secret/utils.go]: Thanks @diogomonica. But in case we are looking for `BBB` and there are two secrets:
Secret 1: ID: `AAA`, Name: `BBB`
Secret 2: ID: `BBB`, Name: `CCC`
Then if there is only one loop:
```
for _, s := range secrets {
    if s.ID == term 
        ....
    if s.Name == term
        ...
}
```
, we will be hit Secret 1 for full name match. In this case secret 1's full name will actually mask secret 2's full ID?

File: cli/command/secret/utils.go [hunk 5]
```diff
@@ -1,47 +1,69 @@
...
+				if s.ID == term {
+					found[s.ID] = struct{}{}
+					continue next
+				}
+			}
+			// attempt to lookup secret by full name
+			for _, s := range secrets {
```
Comment (thaJeztah) [inline cli/command/secret/utils.go]: For each loop, should we _skip_ if `found[s.ID]` already exists?

Comment (yongtang) [inline cli/command/secret/utils.go]: Thanks @thaJeztah for the review. `found` is a map and we are only storing and retrieving keys . The values of the map are always `found[s.ID] = struct{}{}`. I think both check before write or write without check probably are fine either way.

File: cli/command/secret/utils.go (hunk 4 above)
Comment (diogomonica) [inline cli/command/secret/utils.go]: How would it be Secret 1 for full name match if you have a break after `if s.ID == term`?

Comment (yongtang) [inline cli/command/secret/utils.go]: @diogomonica In the for loop as `for _, s := range secrets` will iterate `s1` cycle first, then `s2` cycle after `s1` cycle is done.

However, in the `s1` cycle, the term will be against `s1.ID == term` then `s1.Name == term`. In this case `s1.Name` will be matched. If we break at this point, we will not hit `s2` cycle (as it already breaks).

So `s1.Name` is returned even though `s2.ID` may have a "better match".

Comment (diogomonica) [inline cli/command/secret/utils.go]: I see, it makes sense now. Thanks for walking me through it.

**Comment by diogomonica** [comment]
LGTM

File: cli/command/secret/utils.go [hunk 6]
```diff
@@ -1,47 +1,69 @@
...
+				if s.Spec.Annotations.Name == term {
+					found[s.ID] = struct{}{}
+					continue next
+				}
+			}
+			// attempt to lookup secret by partial ID (prefix)
+			for _, s := range secrets {
+				if strings.HasPrefix(s.ID, term) {
```
Comment (aaronlehmann) [inline cli/command/secret/utils.go]: This must fail if the truncated ID is ambiguous.

Comment (yongtang) [inline cli/command/secret/utils.go]: Thanks @aaronlehmann. The PR has been updated. Now multiple matches return `"secret %s is ambiguous (%d matches found)`. Please take a look.

**Comment by aaronlehmann** [comment]
LGTM

Eventually, I think it would be a good idea to put together a small library to do this id/name/prefix matching. We tend to duplicate the code in a lot of places and it's easy to make subtle mistakes that make the behavior inconsistent. My thinking is that we can have something like `digest.Set` which works with names and IDs/prefixes instead of just digests and digest prefixes. Its interface could allow populating a set of objects, with associated names and IDs, and then performing queries against that set of objects.

**Review by vdemeester — APPROVED** [review]
LGTM :cow:

**Comment by allencloud** [comment]
Could we support these in the daemon side?
We wrap more in the client side, just hide the weakness of the API.

**Comment by thaJeztah** [comment]
@allencloud yes, I agree, it would probably make this one easier/better as well; https://github.com/docker/docker/issues/29125
