### PR TITLE
Return `[]` instead of `null` in case `filterNetworks` returns empty

### LINKED ISSUE #29946: Get networks API returns null body instead of empty array in some cases
**Description**

When I call networks API with filter type=custom docker API returns response 200 with body null.
It happens when no custom networks exist.

**Steps to reproduce the issue:**
1. Ensure no custom networks exist in a system. E.g. **docker network ls** returns bridge, host, none only.
2. Execute 
```
curl localhost:2375/v1.20/networks?filters=%7B%22type%22:%5B%22custom%22%5D%7D
```

**Describe the results you received:**
Docker returns response 200 with body
```
null\n
```

**Describe the results you expected:**
Docker returns response 200 with body
```
[]
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
Version:      1.12.1
API version:  1.24
Go version:   go1.6.3
Git commit:   23cf638
Built:        
OS/Arch:      linux/amd64

Server:
Version:      1.12.1
API version:  1.24
Go version:   go1.6.3
Git commit:   23cf638
Built:        
OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 6
Running: 3
Paused: 0
Stopped: 3
Images: 9
Server Version: 1.12.1
Storage Driver: devicemapper
Pool Name: docker-253:0-2097431-pool
Pool Blocksize: 65.54 kB
Base Device Size: 10.74 GB
Backing Filesystem: xfs
Data file: /dev/loop0
Metadata file: /dev/loop1
Data Space Used: 2.911 GB
Data Space Total: 107.4 GB
Data Space Available: 85.6 GB
Metadata Space Used: 4.801 MB
Metadata Space Total: 2.147 GB
Metadata Space Available: 2.143 GB
Thin Pool Minimum Free Space: 10.74 GB
Udev Sync Supported: true
Deferred Removal Enabled: false
Deferred Deletion Enabled: false
Deferred Deleted Device Count: 0
Data loop file: /var/lib/docker/devicemapper/devicemapper/data
WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
Library Version: 1.02.122 (2016-04-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.7.6-200.fc24.x86_64
Operating System: Fedora 24 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 31.39 GiB
Name: *******************************************
ID: XZ57:ZSSX:MXN6:OX6H:WM54:BL5T:46ZT:OOFV:2FCP:CWF2:HAQ2:ZBFY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical
Reproduced on several distributions, such as CentOS, Fedora, Ubuntu.
Reproduced on Docker 1.12.1, 1.12.5.

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to address the issue raised in #29946 where listing networks from API will return `null` if the result of network filter is empty.

The reason for the issue was that inside the `filterNetworks()`, the return value was initialized as `nil`:
```
 var typeNet []types.NetworkResource
```

This is inconsistent with other places where return value was initialized with `[]`
```
displayNet := []types.NetworkResource{}
```

This fix addresses the issue by changing `typeNet` to `[]` as well.

This fix fixes #29946.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by justincormack — APPROVED** [review]

**Comment by cpuguy83** [comment]
A unit test making sure this doesn't return a nil slice would be helpful.

**Comment by yongtang** [comment]
Thanks @cpuguy83. The unit test has been added.

File: api/server/router/network/filter_test.go [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+			err:         "",
+		},
+		{
+			filter:      customDriverFilters,
+			resultCount: 2,
+			err:         "",
+		},
+		{
+			filter:      builtinDriverFilters,
+			resultCount: 3,
```
Comment (cpuguy83) [inline api/server/router/network/filter_test.go]: Don't we need a test case for `resultCount: 0`?

Comment (yongtang) [inline api/server/router/network/filter_test.go]: Oh forgot the `0` case. Let me update the PR shortly.

**Comment by yongtang** [comment]
@cpuguy83 The PR has been updated with added test case of `0`. Also adds another test case where error will be returned (in case driver `type` is invalid). Please take a look and let me know if there are any issues.

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by garagatyi** [comment]
Hi. Will this be included in 1.13 GA?

**Comment by cpuguy83** [comment]
@garagatyi No.

**Comment by garagatyi** [comment]
Thanks for response

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
all green, merging
