### PR TITLE
Respond with 401 when there is an unauthorized error from the registry.

### LINKED ISSUE #19523: [1.10] Pulling with wrong credentials doesn't show prompt
`POST image/create` endpoints response previously got `200` on authentication error, in `v1.10` the response code is `500`. Error message is also different.

On the client side this means that error message is shown instead of showing prompt like in `1.9`.

If `500` remains the new response code then probably need versioning for the old clients. Also old daemons should still be supported.

Depending on #19522

### PR DESCRIPTION
**Pull request by calavera**
Fixes #19523
/cc @aaronlehmann, @tonistiigi 

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by runcom** [comment]
can we have a test now that there's a suite with a registry which requires auth?

File: api/server/router/local/image.go [hunk 1]
```diff
@@ -137,6 +137,12 @@ func (s *router) postImagesCreate(ctx context.Context, w http.ResponseWriter, r
 				err = s.daemon.PullImage(ref, metaHeaders, authConfig, output)
 			}
 		}
+		// Check the error from pulling an image to make sure the request
+		// was authorized. Modify the status if the request was
+		// unauthorized to respond with 401 rather than 500.
+		if err != nil && strings.Contains(err.Error(), "unauthorized") {
```
Comment (aaronlehmann) [inline api/server/router/local/image.go]: Does it work to check for `errcode.ErrorCodeUnauthorized` (from `github.com/docker/distribution/registry/api/errcode`) and `registry.errLoginRequired` (needs to be exported) instead of looking in the text?

If we don't want to import vendored distribution code here, `Pull` in `github.com/docker/docker/distribution` could convert these to a single exported error value.

**Comment by calavera** [comment]
@runcom totally

File: api/server/router/local/image.go (hunk 1 above)
Comment (calavera) [inline api/server/router/local/image.go]: I think either of that sounds ideal, I didn't know we already had those constants.

**Comment by tiborvass** [comment]
@aaronlehmann is this okay to you? should we move it to code review?

**Comment by calavera** [comment]
I made some changes to check the expected errors. I'm going to try to write some tests next.

File: errors/image.go [hunk 2]
```diff
@@ -17,4 +17,19 @@ var (
...
+		Description:    "The registry responded with an unauthorized error",
+		HTTPStatusCode: http.StatusUnauthorized,
+	})
+	// ErrorCodeLoginRequired is generated when there is no login
+	// information and the registry requires authorized access.
+	ErrorCodeLoginRequired = errcode.Register(errGroup, errcode.ErrorDescriptor{
+		Value:       "LOGIN_REQUIRED_ERROR",
+		Message:     "Authentication is required",
+		Description: "The registry requires login information",
+	})
```
Comment (aaronlehmann) [inline errors/image.go]: I think `ErrorCodeLoginRequired` basically duplicates `errcode.ErrorCodeUnauthorized`. How about using that one directly?

`ErrorCodeRegistryUnauthorized` could instead be `errcode.ErrorCodeUnauthorized.WithMessage()`, to reuse the existing error code but provide backward-compatible error text.

Comment (calavera) [inline errors/image.go]: sounds great. Fixing.

**Comment by tiborvass** [comment]
@aaronlehmann apart from `s/checker.Nil/checker.IsNil/` in the test, does it seem good to you? /cc @dmcgowan

**Comment by tiborvass** [comment]
Carried in #19756

File: distribution/registry.go [hunk 3]
```diff
@@ -21,6 +21,15 @@ import (
 	"golang.org/x/net/context"
 )
 
+// IsFallbackError returns whether the error is a fallbackError or not.
+// It returns the original error if the receiving error is a fallbackError.
+func IsFallbackError(err error) (error, bool) {
```
Comment (runcom) [inline distribution/registry.go]:
```
17:52:00 ---> Making bundle: validate-lint (in bundles/1.10.0-dev/validate-lint)
17:52:00 Errors from golint:
17:52:00 distribution/registry.go:26:1: error should be the last type when returning multiple items
```

File: api/server/router/local/image.go [hunk 4]
```diff
@@ -373,3 +381,16 @@ func (s *router) getImagesSearch(ctx context.Context, w http.ResponseWriter, r *
 	}
 	return httputils.WriteJSON(w, http.StatusOK, query.Results)
 }
+
+func isAuthorizedError(err error) bool {
+	if fError, ok := distribution.IsFallbackError(err); ok {
+		err = fError
+	}
```
Comment (aaronlehmann) [inline api/server/router/local/image.go]: This doesn't make sense to me. `Pull` should never return a `fallbackError`: https://github.com/docker/docker/blob/master/distribution/pull.go#L136

And I thought we agreed in https://github.com/docker/docker/pull/19756 that the case where fallback is involved is tangential to the regression this PR is trying to fix?

Comment (calavera) [inline api/server/router/local/image.go]: oh, I missed your comment there. I've applied your patch here.

**Comment by calavera** [comment]
> But this still doesn't behave correctly. I get prompted for a username, but not for a password.

That's not a bug, it's how `docker login` behaves.

**Comment by aaronlehmann** [comment]
> @aaronlehmann That's not a bug, it's how docker login behaves.

I'm sure I'm missing something, but when I run `docker login`, I get a prompt for a username, then for a password, then for an email address. When I get a prompt from `docker pull` after appling the fixes I discussed in the comments here, I am only asked for a username. Immediately after I enter the username, the pull fails because of bad creds. I never have a chance to enter a password.

**Comment by calavera** [comment]
@aaronlehmann you're falling into this piece of code:

https://github.com/docker/docker/blob/master/api/client/login.go#L104-L115

**Comment by aaronlehmann** [comment]
Can you explain why this is the correct behavior? I'm really confused about why it's valuable to be prompted for a different username after an auth failure, but not be able to specify a password.

**Comment by calavera** [comment]
> Can you explain why this is the correct behavior?

I didn't say that it's a correct behavior, I said that that's how `docker login` behaves :wink:

**Comment by calavera** [comment]
As @aaronlehmann says, checking `*url.Error` solves the regression:

```
➜  bundles/latest/binary/docker --config /tmp/docker-config -H unix:///tmp/docker.sock pull alpine
Using default tag: latest

Please login prior to pull:
Username (vera): adsf
Password:
Email (david.calavera@gmail.com): asdf
```

I decided to drop the test because I couldn't make it work without a TTY. The error is prompting for user credentials, and that doesn't happen in the integration-cli suite.

**Comment by aaronlehmann** [comment]
Why do you get a password prompt? Not fair.

**Comment by tonistiigi** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

@aaronlehmann If the username isn't changed (on the prompt) it doesn't ask for a password.

**Comment by runcom** [comment]
The behavior fixed here - prompting for credentials if they are incorrect is completely gone in master (1.11) @aaronlehmann
