### PR TITLE
fix #35843 regression on health check workingdir

### LINKED ISSUE #35843: Health check no longer uses the container's working directory
**Description**

Previously if a working directory was defined for a container, health checks would also use that as their working directory. This is no longer the case with v17.12.0-ce-rc3. Health checks now ignore the working directory configuration and just use `/` as their working directory.

**Steps to reproduce the issue:**
1. `docker run -d -w /tmp --name health_check_test --health-cmd pwd --health-interval 5s busybox tail -f /dev/null`
2. `sleep 6 && docker inspect --format '{{ (index (.State.Health.Log) 0).Output }}' health_check_test`

The result is also the same if the working directory and health check are defined at the image level instead of at the container level.

**Describe the results you received:**
Health check uses working directory `/`.

**Describe the results you expected:**
Health check should use working directory `/tmp` as defined in the container configuration.

**Additional information you deem important (e.g. issue happens only occasionally):**
Health check uses the correct working directory at least in v17.11.0-ce.

**Output of `docker version`:**

```
Client:
 Version:	17.12.0-ce-rc3
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	80c8033
 Built:	Thu Dec 14 00:39:46 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce-rc3
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	80c8033
  Built:	Thu Dec 14 00:45:43 2017
  OS/Arch:	linux/amd64
  Experimental:	true
```

**Output of `docker info`:**

```
Containers: 8
 Running: 7
 Paused: 0
 Stopped: 1
Images: 637
Server Version: 17.12.0-ce-rc3
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.855GiB
Name: linuxkit-025000000001
ID: RQDH:HHCP:TGAI:HZ2P:ATR2:KY3M:X3MS:52Y6:FKRB:LBBU:GARN:O4ON
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 43
 Goroutines: 70
 System Time: 2017-12-20T11:35:55.352479601Z
 EventsListeners: 2
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker on Mac

### PR DESCRIPTION
**Pull request by ndeloof**
**- What I did**

Fix for https://github.com/moby/moby/issues/35843

**- How I did it**

Set recently introduced exec.WorkingDir to container's workingdir

**- How to verify it**

see https://github.com/moby/moby/issues/35843 description

**- Description for the changelog**
Fixed https://github.com/moby/moby/issues/35843

**- A picture of a cute animal (not mandatory but encouraged)**

2013_6beb

### CODE REVIEW

**Review by thaJeztah — COMMENTED** [review]
change LGTM; perhaps a small test to catch regressions?

**Comment by thaJeztah** [comment]
Also, thanks for the quick fix 👍

**Review by cpuguy83 — COMMENTED** [review]
Can we get a test for this?

**Comment by ndeloof** [comment]
Sorry, won't have much time before Christmas vacations to investigate a test case (not sure how to wait for container to report Health logs)

**Comment by thaJeztah** [comment]
Something like this should be able to test the behaviour, but yes, we'll need a short timeout / loop to test the result

```bash
docker run -dit \
  --health-interval=0.5s \
  --health-retries=1  \
  --health-cmd="/bin/sh -c 'if [ \"\$PWD\" = \"/foo\" ]; then exit 0; else exit 1; fi;" \
  --workdir=/foo \
  busybox
```

**Comment by thaJeztah** [comment]
Had a quick try, and I have a test; will add it here

**Comment by thaJeztah** [comment]
Pushed a test; ping @dnephin @vdemeester @cpuguy83 PTAL

File: integration/container/health_test.go [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+		},
+		&container.HostConfig{},
+		&network.NetworkingConfig{},
+		"healthtest",
+	)
+	require.NoError(t, err)
+	err = client.ContainerStart(ctx, c.ID, types.ContainerStartOptions{})
+	require.NoError(t, err)
+
+	time.Sleep(1 * time.Second)
```
Comment (dnephin) [inline integration/container/health_test.go]: I'm not sure if an integration test is necessary here. Could this be tested with a unit  test of `run()` instead?

Sleeping in a test case should generally be avoided. If this integration test is really necessary then this should use `poll.WaitOn()` to wait for the state, instead of sleep and inspect.

`poll.WaitOn()` will also make the test more reliable on loaded systems, because the timeout can be longer than 1s.

Comment (thaJeztah) [reply integration/container/health_test.go]: I think an integration test is warranted here, because `run` and `exec` (used for the healthcheck) take different code paths.

Thanks for the `poll.WaitOn()`, I'll check that one out

**Comment by thaJeztah** [comment]
Updated, PTAL 👍

**Review by dnephin — APPROVED** [review]
LGTM

**Comment by tiborvass** [comment]
LGTM
