### PR TITLE
Remove attachable network on swarm leave

### LINKED ISSUE #30084: swarm rejoin causes overlay network to become a "local" network
**Description**

Leaving and joining a swarm while running a container on an attachable network turns the overlay network into a local network.

**Steps to reproduce the issue:**
```
docker swarm init --listen-addr 0.0.0.0 --advertise-addr 127.0.0.1
docker network create -d overlay --attachable overlaytest
# network scope is swarm
docker run -d --net overlaytest alpine sleep 1000000
docker swarm leave --force
# network scope is still swarm
docker swarm init --listen-addr 0.0.0.0 --advertise-addr 127.0.0.1
# network scope is local
```

**Describe the results you received:**
network is a "local" overlay network

**Describe the results you expected:**
Network doesn't exist, is a real overlay network or container is killed. Basically anything else other than what's happening because this behaviour is very confusing.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.4
 Git commit:   bf6eb85
 Built:        Tue Dec 27 22:23:51 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.14.0-dev
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.4
 Git commit:   bf6eb85
 Built:        Tue Dec 27 22:23:51 2016
 OS/Arch:      linux/amd64
 Experimental: false
```
This has always been this way though. I've seen it on 1.12-cs

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 600
Server Version: 1.14.0-dev
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: nhk9xeap351ngic91qdyco86j
 Is Manager: true
 ClusterID: tt3gmr7nh94mhxe8uqasoo4hc
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 127.0.0.1
 Manager Addresses:
  127.0.0.1:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.8.12
Operating System: NixOS 17.03.git.1c50bdd (Gorilla)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.53 GiB
Name: thisisfine
ID: 4XB6:RAOL:2UT7:W3TT:JBSR:ILHC:LREA:HUVU:5U7V:TI7E:WUT2:WQTS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 64
 Goroutines: 182
 System Time: 2017-01-11T17:42:25.480179518-08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Experimental: false
Insecure Registries:
 172.17.0.1
 172.17.0.1:3001
 172.17.0.1:443
 172.17.0.1:444
 172.17.0.1:445
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

### PR DESCRIPTION
**Pull request by aboch**
- When the node leaves the cluster, if any user run
  container(s) is connected to the swarm (attachable) network,
  then daemon needs to detach the container(s) and
  remove the network.

Fixes #30084

**- A picture of a cute animal (not mandatory but encouraged)**

hyena

### CODE REVIEW

**Comment by cpuguy83** [comment]
Seems like it's the right thing to do... what happens to the networking in the container when this happens?

Also, build failure:
```
05:42:45 ./docker_cli_swarm_test.go:380: undefined: strings.TrimSpae
```

**Comment by aboch** [comment]
Thanks @cpuguy83 

> what happens to the networking in the container when this happens?

The network interface which was connecting the container to the attachable network is removed.

File: daemon/network.go [hunk 1]
```diff
@@ -468,3 +468,35 @@ func (daemon *Daemon) deleteNetwork(networkID string, dynamic bool) error {
 func (daemon *Daemon) GetNetworks() []libnetwork.Network {
 	return daemon.getAllNetworks()
 }
+
+// clearAttachableNetworks remove the attachable networks
```
Comment (allencloud) [inline daemon/network.go]: remove -> removes?

Comment (aboch) [inline daemon/network.go]: Thanks, I will fix

**Comment by aboch** [comment]
ping @mavenugo

File: daemon/network.go [hunk 2]
```diff
@@ -468,3 +468,35 @@ func (daemon *Daemon) deleteNetwork(networkID string, dynamic bool) error {
...
+			epInfo := ep.Info()
+			if epInfo == nil {
+				continue
+			}
+			sb := epInfo.Sandbox()
+			if sb == nil {
+				continue
+			}
+			containerID := sb.ContainerID()
+			if err := daemon.DisconnectContainerFromNetwork(containerID, nwName, true); err != nil {
```
Comment (thaJeztah) [inline daemon/network.go]: Should this use network-id instead of network-name?

Comment (aboch) [inline daemon/network.go]: Not necessarily. This API can take either name of ID (it eventually calls `FindNetwork()`), it _was_ in fact the first function which processes a network disconnect POST request.  I am saying "it was" because later with the addition of swarm networks being lazily programmed  `FindNetwork` had to be called before anyway.

In this case the network is known to this node and there is no need to pass the ID.

But I agree it will spare the reader from wondering about this logic when reading the code, I will change it to ID.

Thanks.

**Comment by mavenugo** [comment]
LGTM

@aboch curious to know how this will behave in a case where all the swarm managers leave, while the worker node (with an attachable network and containers) stays ? I guess, it will fix itself when the worker rejoins to new managers I assume. Can you pls confirm ?

File: daemon/network.go (hunk 2 above)
Comment (thaJeztah) [inline daemon/network.go]: I recall a case where both a "bridge" and "overlay" network existed on a node (due to a race?), resulting in the service failing to start. Although "corner case", removing the network by name could potentially result in the wrong network being deleted.

Comment (aboch) [inline daemon/network.go]: Ah, then it makes sense. 
If user created that scenario, it is expected from him to handle things right when calling `docker network rm ...`.
But in this case, being an automatic action taken by the daemon, we must delete the right network, with no user intervention.
So the right thing to do here is to pass the network ID as you suggested. Thanks for your comment.

**Comment by aboch** [comment]
@mavenugo 
Nothing happens. The worker nodes keep trying to reach the manager. When I restart the manager, they reconnect. The network is never removed and the containers never detached.

Not sure if this is the test you wanted to check. 

Is the worker node going into a failed state if we wait long enough and cluster provider be set to nil ? 
If that is the case, then the cleanup logic would kick in.

**Comment by mavenugo** [comment]
@aboch yes. I think that is reasonable and expected behavior. am good.

File: daemon/network.go [hunk 3]
```diff
@@ -468,3 +468,35 @@ func (daemon *Daemon) deleteNetwork(networkID string, dynamic bool) error {
 func (daemon *Daemon) GetNetworks() []libnetwork.Network {
 	return daemon.getAllNetworks()
 }
+
+// clearAttachableNetworks removes the attachable networks
+// after disconnecting any connected container
+func (daemon *Daemon) clearAttachableNetworks() {
+	var networks []libnetwork.Network
+	for _, n := range daemon.GetNetworks() {
```
Comment (thaJeztah) [inline daemon/network.go]: Wondering, should we combine the two loops, and simply

```go
for _, n := range daemon.GetNetworks() {
    if !n.Info().Attachable() {
        continue
    }
```

Or is there a special reason for using the intermediate `networks` variable?

Comment (aboch) [inline daemon/network.go]: Thanks, it in fact looks like `Getnetworks()` returns a new slice of networks.
Then there is no need to create a new slice here. 
Will fix it shortly. Thanks.

**Comment by aboch** [comment]
@thaJeztah Taken care of your comment, thanks. PTAL when you get a chance.

**Comment by tonistiigi** [comment]
@aboch Can `DeleteManagedNetwork` call back to cluster pkg? Want to make sure that there isn't a possibility for a deadlock as that issue is not fixed in `v1.13`.

**Comment by aboch** [comment]
Thanks @tonistiigi Unless I missed it, `DeleteManagedNetwork` and the downstream calls in libnetwork do not call back to the docker cluster pkg.

Also, I do not think this fix will go in 1.13.x

**Comment by tonistiigi** [comment]
LGTM

File: daemon/daemon.go [hunk 4]
```diff
@@ -448,6 +448,11 @@ func (daemon *Daemon) registerLink(parent, child *container.Container, alias str
 
 // SetClusterProvider sets a component for querying the current cluster state.
 func (daemon *Daemon) SetClusterProvider(clusterProvider cluster.Provider) {
+	// Daemon is in charge of removing the attachable networks with
+	// connected containers when the node leaves the swarm
+	if clusterProvider == nil {
+		daemon.clearAttachableNetworks()
+	}
```
Comment (aboch) [inline daemon/daemon.go]: True. But this is the only place in the _daemon_ package where we know the node is leaving the cluster.
And the cleanup has to be performed from the _daemon_.

The other option was to add a specific method to the `backend` interface to be called from the _cluster_ package, but I did not like it because it should be called in several places, while they all converge to eventually call `func (daemon *Daemon) SetClusterProvider(clusterProvider cluster.Provider) `, so to me this was the safest approach.

Comment (aboch) [inline daemon/daemon.go]: The call from the _cluster_ pkg would have to happen in  `newNodeRunner()` and `Leave()`right before the call to
`c.config.Backend.SetClusterProvider(nil)`

Let's say:
```
c.config.Backend.ClearAttachableNetworks()
c.config.Backend.SetClusterProvider(nil)
```

The fact that they would always need to go in couple and based on the fact that `c==nil` and that the clear attachable networks would really have something to do only when there are user run containers (otherwise it already happen automatically on last task shutdown), which is a notion of the _daemon_, it seem actually ok to me for the call to `clearAttachableNetworks()` to happen inside `SetClusterProvider()`

**Comment by mavenugo** [comment]
@dnephin @aboch are we good to go with this PR ? FYI, This is marked for 1.13.1 and @vieux is in the process of cherry-picking the relevant patches to the 1.13.x branch.

File: daemon/daemon.go (hunk 4 above)
Comment (dnephin) [inline daemon/daemon.go]: That may be true now, but what happens when the code changes?

I still think this is extremely misleading behaviour for a function called `SetClusterProvider()`. I would much rather have a few lines duplicated next to each other (clear then set), instead of having a set method perform some kind of clean up on unrelated objects.

Comment (aboch) [inline daemon/daemon.go]: I see your point, and I see a different solution.

Let's me summarize: 

From daemon POV, `SetClusterProvider()` has the current semantic: "The node has joined the swarm/ The node has left the swarm" (based on the value of the passed provider pointer).

The cleaning up the attachable networks which are being kept alive by user run containers is to be done by the daemon when it gets notified the node left the swarm. 

I am proposing we could rename the API from its current technical meaning to one which carries the higher picture context:
`SetClusterProvider(c != nil)` => `DaemonJoinedCluster(c)`
and 
`SetClusterProvider(c == nil)` => `DaemonLeftCluster()`

I think this would make it natural to the reader when he sees `DaemonLeftCluster()` invoke the nw cleanup. WDYT ?

Comment (dnephin) [inline daemon/daemon.go]: SGTM, thanks!

**Comment by aboch** [comment]
@dnephin Addressed your comment, PTAL

(I am having some weird build error, so I just pushed the change to speed up the review)

**Comment by dnephin** [comment]
LGTM

Thank you!

**Comment by aboch** [comment]
CI failures due to #28409. @dnephin is looking into it.
