### PR TITLE
Handle NetworkDettach for the case of network-id

### LINKED ISSUE #28051: Connecting to an overlay network with the network ID causes the network to not get deleted properly
**Description**

If you create an attachable overlay network and then connect a container to it using the network's ID, then deleting the container and then the network results in the network not really getting deleted, but instead somehow getting downgraded to a local network.

**Steps to reproduce the issue:**
```bash
#!/bin/sh

networkid=$(docker network create -d overlay --attachable testnet)
docker create --name testcontainer busybox:latest sleep 24h
docker network connect $networkid testcontainer
docker start testcontainer
docker rm -f testcontainer
docker network rm testnet
docker network ls
```

**Describe the results you received:**
The `testnet` network showed up as a "local" overlay network.

**Describe the results you expected:**
The `testnet` network would be gone.

**Additional information you deem important (e.g. issue happens only occasionally):**
This happens deterministically.

**Output of `docker version`:**
Docker version 1.12.2-cs2

### PR DESCRIPTION
**Pull request by mavenugo**
When a container is attached to an "--attachable" network, it strictly
forms the attacherKey using either the network-id or network-name
because at the time of attachment, the daemon may not have the network
downloaded locally from the manager. Hence, when the NetworkDettach is
called, it should use either network-name or network-id. This fix
addresses the missing network-id based dettachment case.

Fixes #28051

Signed-off-by: Madhu Venugopal <madhu@docker.com>

### CODE REVIEW

**Comment by mavenugo** [comment]
ping @mrjana @aboch

**Comment by mrjana** [comment]
LGTM pending CI green

**Comment by aboch** [comment]
looks good to me

**Review by thaJeztah — APPROVED** [review]
LGTM

File: daemon/container_operations.go [hunk 1]
```diff
@@ -793,7 +793,10 @@ func (daemon *Daemon) disconnectFromNetwork(container *container.Container, n li
 
 	if daemon.clusterProvider != nil && n.Info().Dynamic() && !container.Managed {
 		if err := daemon.clusterProvider.DetachNetwork(n.Name(), container.ID); err != nil {
-			logrus.Warnf("error detaching from network %s: %v", n, err)
+			logrus.Warnf("error detaching from network %s: %v", n.Name(), err)
```
Comment (cpuguy83) [inline daemon/container_operations.go]: Do we need this warning?

**Comment by cpuguy83** [comment]
LGTM
