### PR TITLE
Ensure test graphdriver plugin runs on test host

### LINKED ISSUE #29505: TestGraphdriverPlugin failing on CentOS 7.2 / RHEL 7.2 (master)
Possibly related to the SELinux issues, but I noticed that master is currently failing on CentOS/RHEL

https://jenkins.dockerproject.org/job/Docker%20Master/

https://jenkins.dockerproject.org/job/Docker%20Master/label=centos72%20&&%20devicemapper/lastBuild/console

https://jenkins.dockerproject.org/job/Docker%20Master/label=rhel72%20&&%20overlay/lastBuild/console

```
21:44:12 ----------------------------------------------------------------------
21:44:12 FAIL: docker_cli_daemon_plugins_test.go:238: DockerDaemonSuite.TestGraphdriverPlugin
21:44:12 
21:44:12 docker_cli_daemon_plugins_test.go:249:
21:44:12     // restart the daemon with the plugin set as the storage driver
21:44:12     s.d.Restart(c, "-s", plugin)
21:44:12 daemon/daemon.go:178:
21:44:12     c.Assert(d.StartWithError(args...), checker.IsNil, check.Commentf("Error starting daemon with arguments: %v", args))
21:44:12 ... value *errors.fundamental = [dd8cfba56e482] Daemon exited during startup ("[dd8cfba56e482] Daemon exited during startup")
21:44:12 ... Error starting daemon with arguments: [-s cpuguy83/docker-overlay2-graphdriver-plugin]
21:44:12 
21:44:12 [d51e67f17aaad] waiting for daemon to start
21:44:13 [d51e67f17aaad] daemon started
21:44:13 [d51e67f17aaad] exiting daemon
21:44:13 
21:44:13 ----------------------------------------------------------------------
```

ping @cpuguy83 @andrewhsu

### PR DESCRIPTION
**Pull request by cpuguy83**
Sets a kernel requirement for for `TestGraphdriverPlugin` since the
graphdriver being used is overlay2.. and also makes sure to skip the
kernel check in the actual graphdriver since we may be able to detect
kernels with backported support for overlay2 style mounts a bit more
freely in the test code.

Fixes #29505

### CODE REVIEW

File: integration-cli/requirements_unix.go [hunk 1]
```diff
@@ -124,7 +125,7 @@ var (
 		},
 		"Test cannot be run without a kernel (4.3+) supporting ambient capabilities",
 	}
-	overlaySupported = testRequirement{
+	overlayFSSupported = testRequirement{
```
Comment (thaJeztah) [inline integration-cli/requirements_unix.go]: why the change in name here?

Comment (cpuguy83) [inline integration-cli/requirements_unix.go]: Because it's specifically checking for filesystem support.

Comment (thaJeztah) [inline integration-cli/requirements_unix.go]: Ahm, makes sense :-)

File: integration-cli/requirements_unix.go [hunk 2]
```diff
@@ -135,6 +136,22 @@ var (
 		},
 		"Test cannot be run wihtout suppport for ovelayfs",
```
Comment (thaJeztah) [inline integration-cli/requirements_unix.go]: Oh (no need to change, I'm just seeing them now); `s/wihtout/without/` and `s/ovelayfs/overlayfs/`

**Comment by tonistiigi** [comment]
LGTM

File: integration-cli/requirements_unix.go (hunk 2 above)
Comment (cpuguy83) [inline integration-cli/requirements_unix.go]: It's a typo conspiracy, I tell you.

Fixed it.

**Review by thaJeztah — APPROVED** [review]
LGTM
