### PR TITLE
Fix log readers can block writes indefinitely

### LINKED ISSUE #31373: Container stops after logs are piped to failing command
**Description**

When `docker logs <container>` is piped to a command that fails the container hangs, and docker has to be restarted to recover. 

**Steps to reproduce the issue:**
```
$ docker run -d --name=failure alpine /bin/sh -c "while true; do date; done"
642305b0dc0d36553362b3d48fd6e06919d475e91545625ac4dc47a22d0f9e1f
$ cat /var/lib/docker/containers/642305b0dc0d36553362b3d48fd6e06919d475e91545625ac4dc47a22d0f9e1f/642305b0dc0d36553362b3d48fd6e06919d475e91545625ac4dc47a22d0f9e1f-json.log | wc -l
59247
```
--- wait ?30+ seconds?
```
$ docker logs failure --tail 10
Mon Feb 27 03:27:10 UTC 2017
Mon Feb 27 03:27:10 UTC 2017
Mon Feb 27 03:27:10 UTC 2017
Mon Feb 27 03:27:10 UTC 2017
Mon Feb 27 03:27:10 UTC 2017
Mon Feb 27 03:27:10 UTC 2017
Mon Feb 27 03:27:10 UTC 2017
Mon Feb 27 03:27:10 UTC 2017
Mon Feb 27 03:27:10 UTC 2017

$ docker logs failure |grep -10
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.

$ docker logs failure --tail 10
```
....nothing.... 
ctrl+c
```
$ cat /var/lib/docker/containers/642305b0dc0d36553362b3d48fd6e06919d475e91545625ac4dc47a22d0f9e1f/642305b0dc0d36553362b3d48fd6e06919d475e91545625ac4dc47a22d0f9e1f-json.log | wc -l
165360
$ cat /var/lib/docker/containers/642305b0dc0d36553362b3d48fd6e06919d475e91545625ac4dc47a22d0f9e1f/642305b0dc0d36553362b3d48fd6e06919d475e91545625ac4dc47a22d0f9e1f-json.log | wc -l
165360

$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
642305b0dc0        alpine              "/bin/sh -c 'while..."   52 seconds ago      Up 51 seconds                           failure

$ docker stop failure
failure

$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS               NAMES
642305b0dc0        alpine              "/bin/sh -c 'while..."   About a minute ago   Up About a minute                       failure

$ systemctl restart docker
$ docker ps --all |grep failure
642305b0dc0        alpine                  "/bin/sh -c 'while..."    2 minutes ago       Exited (137) 22 seconds ago                                    failure
```

**Describe the results you received:**
When `docker logs <container>` is piped "|" to a command that fails... the container fails and the docker service must be restarted.

**Describe the results you expected:**
The command should fail, but the container should not be effected. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
docker info
Containers: 19
 Running: 1
 Paused: 0
 Stopped: 18
Images: 39
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 96
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.678 GiB
Name: x1
ID: YY5M:Q3IW:GK7S:C3F2:JGQN:UZ7F:BP2F:MC4T:5U7J:6QAT:VVQC:DCCF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ubuntu 16.04, Physical Host, 8GB Ram, 4CPU

### PR DESCRIPTION
**Pull request by cpuguy83**
Before this patch, a log reader is able to block all log writes
indefinitely (and other operations) by simply opening the log stream and
not consuming all the messages.

The reason for this is we protect the read stream from corruption by
ensuring there are no new writes while the log stream is consumed (and
caught up with the live entries).

We can get around this issue because log files are append only, so we
can limit reads to only the section of the file that was written to when
the log stream was first requested.

Now logs are only blocked until all files are opened, rather than
streamed to the client.

Fixes #31373

### CODE REVIEW

File: daemon/logger/jsonfilelog/read.go [hunk 1]
```diff
@@ -48,36 +48,48 @@ func (l *JSONFileLogger) ReadLogs(config logger.ReadConfig) *logger.LogWatcher {
...
 	if err != nil {
-		logWatcher.Err <- err
-		l.mu.Unlock()
+		logWatcher.Err <- errors.Wrap(err, "error opening latest log file")
+		l.mu.RUnlock()
 		return
 	}
 	defer latestFile.Close()
 
+	latestChunk, err := newSectionReader(latestFile)
```
Comment (mlaventure) [inline daemon/logger/jsonfilelog/read.go]: you need to seek to this value on line 108, otherwise we may miss some data.

**Review by mlaventure — CHANGES_REQUESTED** [review]

File: daemon/logger/jsonfilelog/read.go (hunk 1 above)
Comment (cpuguy83) [inline daemon/logger/jsonfilelog/read.go]: We are seeking in "newSectionReader"

Comment (mlaventure) [inline daemon/logger/jsonfilelog/read.go]: It is initially yes, but then the lock is released on line 84, and if we were asked to tail and follow, then on line 108, we do another `SEEK_END`, shouldn't that one be a `SEEK_SET` to `latestChunk`?

Comment (cpuguy83) [inline daemon/logger/jsonfilelog/read.go]: Ok, I fixed this. You're right, I left an extra seek in there.

**Comment by thaJeztah** [comment]
ping @mlaventure @tonistiigi PTAL

**Review by mlaventure — APPROVED** [review]
LGTM

**Comment by vieux** [comment]
LGTM ping @tonistiigi

File: daemon/logger/jsonfilelog/jsonfilelog.go [hunk 2]
```diff
@@ -90,33 +93,45 @@ func New(info logger.Info) (logger.Logger, error) {
...
+}
+
+func writeMessageBuf(w io.Writer, m *logger.Message, extra json.RawMessage, buf *bytes.Buffer) error {
+	if err := marshalMessage(m, extra, buf); err != nil {
+		logger.PutMessage(m)
+		return err
+	}
+	logger.PutMessage(m)
+	if _, err := w.Write(buf.Bytes()); err != nil {
+		errors.Wrap(err, "error writing log entry")
```
Comment (tonistiigi) [inline daemon/logger/jsonfilelog/jsonfilelog.go]: return

**Review by tonistiigi — COMMENTED** [review]
Not too familiar with this code but apart from one typo SGTM

**Comment by thaJeztah** [comment]
```
18:07:25 INFO: Base image for tests is microsoft/windowsservercore
18:07:25 INFO: Loading windowsservercore .tar from disk into the daemon under test. This may take some time...
18:08:48 re-exec error: exit status 1: output: BackupWrite \\?\D:\CI\CI-bf11b0b0d\daemon\windowsfilter\39a6fda2dfcc44cdb21c59f8d90690bc5798b5b6db5e6c050ae82f80890d27c2\Files\Windows\IME\IMETC\DICTS\IMTCT.IMD: There is not enough space on the disk.
18:08:48 
18:08:48 
```

**Comment by thaJeztah** [comment]
All green! Merging
