### PR TITLE
[1.13.x] Change the way IPAM configuration is handled on stack deploy

### LINKED ISSUE #28528: driver name: if driver is specified name is required
I think there's a 1.13.0-rc1 (client) / 1.12.3 (server) incompatibility.

**Steps to reproduce the issue:**

1. `docker deploy --bundle-file .\iv.dab iv`

**Describe the results you received:**

Loading bundle from .\iv.dab
Creating network iv_back-tier
Error response from daemon: rpc error: code = 3 desc = driver name: if driver is specified name is required

**Describe the results you expected:**

DAB file deployed

**Additional information you deem important (e.g. issue happens only occasionally):**

This works with 1.12.3 client

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc1
 API version:  1.24 (downgraded from 1.25)
 Go version:   go1.7.3
 Git commit:   75fd88b
 Built:        Fri Nov 11 22:32:34 2016
 OS/Arch:      windows/amd64

Server:
 Version:             1.12.3
 API version:         1.24
 Minimum API version:
 Go version:          go1.6.3
 Git commit:          6b644ec
 Built:               Thu Oct 27 00:09:21 2016
 OS/Arch:             linux/amd64
 Experimental:        true
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running Windows client and Docker for AWS.

DAB file below:

```
{
  "services": {
    "db": {
      "Image": "postgres@sha256:f76245b04ddbcebab5bb6c28e76947f49222c99fec4aadb0bb1c24821a9e83ef", 
      "Networks": [
        "back-tier"
      ]
    }, 
    "redis": {
      "Image": "redis@sha256:2e75b1750a11e1bb060b3af6a80f8f5c536a2b16bc85c02e006ffc2f93ec8ba6", 
      "Networks": [
        "back-tier"
      ], 
      "Ports": [
        {
          "Port": 6379, 
          "Protocol": "tcp"
        }
      ]
    }, 
    "result": {
      "Image": "docker4x/demo-result@sha256:9932a45ccc04447430659acb88243ddf3ff207efc8cd28f6cda03da0c9d4a426", 
      "Networks": [
        "front-tier", 
        "back-tier"
      ], 
      "Ports": [
        {
          "Port": 80, 
          "Protocol": "tcp"
        }
      ]
    }, 
    "vote": {
      "Image": "docker4x/demo-vote@sha256:c961faf9a715176f09fe10104fd763b96cf8341d274031cf477b0dfd1fe2af32", 
      "Networks": [
        "front-tier", 
        "back-tier"
      ], 
      "Ports": [
        {
          "Port": 80, 
          "Protocol": "tcp"
        }
      ]
    }, 
    "worker": {
      "Image": "docker4x/demo-worker@sha256:df16d85fba95eef19d2d53f1ee5367c22aa4956fab0977ed9a187d69ec15dab0", 
      "Networks": [
        "back-tier"
      ]
    }
  }, 
  "version": "0.1"
}
```

cc @vieux @mavenugo

### LINKED ISSUE #29809: docker 1.13.0-rc4 (stack)- error: driver name: if driver is specified name is required
I have the same issu like #28528 but with1.13.0-rc4:
Error response from daemon: rpc error: code = 3 desc = driver name: if driver is specified name is required.
I get the error when i'm trying to define a static IP address for a container.
**My version is:**
Client:
Version: 1.13.0-rc4
API version: 1.25
Go version: go1.7.3
Git commit: 88862e7
Built: Fri Dec 16 22:55:47 2016
OS/Arch: linux/amd64

Server:
Version: 1.13.0-rc4
API version: 1.25 (minimum version 1.12)
Go version: go1.7.3
Git commit: 88862e7
Built: Fri Dec 16 22:55:47 2016
OS/Arch: linux/amd64
Experimental: true

**My compose file is (i'm using docker stacks):**
```yaml
networks:
default_network:
driver: overlay
ipam:
config:
- subnet: 10.5.0.0/16
gateway: 10.5.0.1
```

### PR DESCRIPTION
**Pull request by vdemeester**
We use the 'default' driver if none is specified.

Fixes #29809 
Fixes #28528 

This is opened against the 1.13.x branch directly. I'll make a PR for master if this one gets merged 👼.

/cc @dnephin @icecrime @thaJeztah @mavenugo @vieux 

🐸

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Review by dnephin — COMMENTED** [review]
I think this should be set by the server, not the client. Would that work?

**Comment by vieux** [comment]
ping @mavenugo

**Comment by mavenugo** [comment]
@aboch can you PTAL ?

**Comment by aboch** [comment]
code changes per se looks good to me

but wanted to understand why it cannot be done on the server side as @dnephin suggested.

**Comment by vdemeester** [comment]
@aboch it probably could (and might be the right fix too). This is just the *first* fix that came to mind 😄

**Comment by aboch** [comment]
If you want to pursue it, I guess it could be done in

https://github.com/docker/docker/blob/1.13.x/daemon/cluster/convert/network.go#L174

where the nw spec is crafted, given it is specific to a swarmkit input validation.

**Comment by vdemeester** [comment]
Updated to be server side 👼

File: daemon/cluster/convert/network.go [hunk 1]
```diff
@@ -186,9 +186,13 @@ func BasicNetworkCreateToGRPC(create basictypes.NetworkCreateRequest) swarmapi.N
...
+		if driver == "" {
+			driver = "default"
+		}
 		ns.IPAM = &swarmapi.IPAMOptions{
 			Driver: &swarmapi.Driver{
-				Name:    create.IPAM.Driver,
+				Name:    driver,
 				Options: create.IPAM.Options,
 			},
 		}
```
Comment (aboch) [inline daemon/cluster/convert/network.go]: Can we avoid the  extra `driver` variable
Something like:
```
		ns.IPAM = &swarmapi.IPAMOptions{
  			Driver: &swarmapi.Driver{
				Name:    create.IPAM.Driver,
  				Options: create.IPAM.Options,
  			},
  		}
                if ns.IPAM.Driver.Name == "" {
                       ns.IPAM.Driver.Name = "default"
                }            
```

**Comment by aboch** [comment]
Small nit (up to you if you want to fix it)

Changes look good to me.

**Review by dnephin — APPROVED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

ping @vieux for the merge
