### PR TITLE
Fix network attachable option

### LINKED ISSUE #27124: attachable network not attachable after swarm leave + join
**Description**

If you have an attachable network on a one node cluster, then do a swarm leave and join again, the network loses its attachable status.

**Steps to reproduce the issue:**

```
docker swarm init --advertise-addr 172.17.0.1
docker network create -d overlay --attachable testnet
docker network inspect testnet
# the network is reported as attachable
docker run -d --net testnet --name testcontainer alpine sleep 100000
docker network inspect testnet
# the network is reported as not attachable
docker swarm leave --force
docker swarm init --advertise-addr 172.17.0.1
docker network inspect testnet
# the network is reported as not attachable, but has a container attached
docker rm -f testcontainer
docker network inspect testnet
# the network is reported as not attachable and is not attachable
docker run -d --net testnet --name testcontainer alpine sleep 100000
# fails
```

**Describe the results you received:**
The network is no longer attachable.

**Describe the results you expected:**
The network doesn't exist or is attachable. I was actually surprised that overlay networks continued to exist after swarm leave.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.1-cs1-rc2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   24231a4
 Built:        Mon Sep 19 00:55:12 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   94cd7ed
 Built:        Mon Oct  3 20:41:39 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 848
Server Version: 1.13.0-dev
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: active
 NodeID: 5jdfbn45se5wu8hftur9q4ixz
 Is Manager: true
 ClusterID: ajqrjtlshxdab2ptj5cg00xv0
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.17.0.1
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.7.3
Operating System: NixOS 17.03.git.4ed9343 (Gorilla)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.53 GiB
Name: thisisfine
ID: 4XB6:RAOL:2UT7:W3TT:JBSR:ILHC:LREA:HUVU:5U7V:TI7E:WUT2:WQTS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 29
 Goroutines: 122
 System Time: 2016-10-03T14:14:03.801809482-07:00
 EventsListeners: 0
Username: viktorstanchev
Registry: https://index.docker.io/v1/
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 172.17.0.1
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

### PR DESCRIPTION
**Pull request by dongluochen**
Fixes #27124. 

**- What I did**

Fix network `attachable` option. 

**- How I did it**

Pass `attachable` in network resource requests. 

**- How to verify it**

```
#create network with attachable option
docker network create -d overlay --attachable rnet1
#verify attachable option
docker network inspect rnet1 | grep -i attachable
#attach a container to it
docker run -d --network rnet1 --name c1 busybox top
#verify attachable option
docker network inspect rnet1
```

cc @mavenugo @aboch. 

Signed-off-by: Dong Chen <dongluo.chen@docker.com>

### CODE REVIEW

**Comment by vieux** [comment]
ping @mavenugo

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by mavenugo** [comment]
Thanks @dongluochen . can u pls add an IT ?

**Comment by thaJeztah** [comment]
ping @mavenugo - test was added, PTAL

**Comment by mavenugo** [comment]
@dongluochen thanks. is there a reason to create a new file while there are other attachable tests already part of docker_cli_swarm_test.go ?  To bring in consistency, can you pls move the test to docker_cli_swarm_test.go as it is swarm related ?

File: integration-cli/docker_cli_overlaynetwork_test.go [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+	"strings"
+
+	"github.com/docker/docker/pkg/integration/checker"
+	"github.com/go-check/check"
+)
+
+func (s *DockerSwarmSuite) TestOverlayAttachable(c *check.C) {
+	d := s.AddDaemon(c, true, true)
+	s.AddDaemon(c, true, true)
+	s.AddDaemon(c, true, true)
```
Comment (mavenugo) [inline integration-cli/docker_cli_overlaynetwork_test.go]: why do we need to call `AddDaemon` 3 times ?

Comment (vdemeester) [inline integration-cli/docker_cli_overlaynetwork_test.go]: @mavenugo I guess it's to make sure it working with multiple node 👼. This will create 3 manager node though I think, we might want to create some worker node instead (for the 2 additional ones)

Comment (dongluochen) [inline integration-cli/docker_cli_overlaynetwork_test.go]: Yes. The intention is to verify it works with multiple nodes.

Comment (dongluochen) [inline integration-cli/docker_cli_overlaynetwork_test.go]: @vdemeester updated test to 1 manager 2 workers setup.

**Comment by mavenugo** [comment]
@dongluochen can you pls address https://github.com/docker/docker/pull/28721#issuecomment-262999344 ?

Also, maybe I was not clear with my question. Since the test is using just the single manager node for attachable network, what is the purpose of adding other worker nodes since they are not involved in the tests ? am just trying to understand if the presence or absence of the worker node makes any difference to the behaviour.

**Comment by dongluochen** [comment]
@mavenugo Update test to attach containers from manager and worker node, and validate `attachable` on both nodes.

**Comment by mavenugo** [comment]
Thanks @dongluochen for addressing the comments.

LGTM

**Review by mavenugo — APPROVED** [review]
