### PR TITLE
Fixup some issues with plugin refcounting

### LINKED ISSUE #32609: Cannot disable/remove a plugin.
**Description**

I have installed the `rexray/ebs` plugin, and I was having difficultly getting it to work, so I was attempting to upgrade it from `rexray/ebs:latest` to `rexray/ebs:edge`. However, when I try to disable it I get the following error message:

`Error response from daemon: plugin rexray/ebs:latest is in use`

I do not have any volumes that were created with this plugin, so it seems that I should be able to disable/remove the plugin.

**Steps to reproduce the issue:**
1. docker plugin install rexray/ebs
2. docker plugin disable rexray/ebs

**Describe the results you received:**

It gave me an error message: `Error response from daemon: plugin rexray/ebs:latest is in use`

**Describe the results you expected:**

I expected it to disable the plugin so that I could then remove it.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:55:10 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:55:10 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.04.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: pvt2k41nx4v3c98xa6ntm1h8v
 Is Manager: true
 ClusterID: udnrxhgowfyq8xycc685vjg1s
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.100.68
 Manager Addresses:
  192.168.100.68:2377
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.28.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.389GiB
Name: manager01
ID: O7BJ:7Z73:HAWX:TJKE:HTLC:FX7V:F5FN:6LVW:Y4NK:ET3P:46BX:CD7O
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: overlay: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior.
         Reformat the filesystem with ftype=1 to enable d_type support.
         Running without d_type support will not be supported in future releases.
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I am running this on a CentOS 7 AWS EC2 t2.large instance.  I am also running this server as a Swarm mode manager in a 3 node Swarm mode cluster. 1 manager and 2 workers.

### PR DESCRIPTION
**Pull request by cpuguy83**
In some circumstances we were not properly releasing plugin references,
leading to failures in removing a plugin with no way to recover other
than restarting the daemon.

1. If volume create fails (in the driver)
2. If a driver validation fails (should be rare)
3. If trying to get a plugin that does not match the passed in capability

Ideally the test for 1 and 2 would just be a unit test, however the
plugin interfaces are too complicated as `plugingetter` relies on
github.com/pkg/plugin/Client (a concrete type), which will require
spinning up services from within the unit test... it just wouldn't be a
unit test at this point.
I attempted to refactor this a bit, but since both libnetwork and
swarmkit are reliant on `plugingetter` as well, this would not work.
This really requires a re-write of the lower-level plugin management to
decouple these pieces.

Fixes #32609

### CODE REVIEW

**Comment by cpuguy83** [comment]
For some reason tests work fine running manually but when run from the makefile it's not.

**Comment by cpuguy83** [comment]
Good to go now.

File: pkg/plugingetter/getter.go [hunk 1]
```diff
@@ -1,6 +1,8 @@
 package plugingetter
 
-import "github.com/docker/docker/pkg/plugins"
+import (
+	"github.com/docker/docker/pkg/plugins"
```
Comment (ripcurld0) [inline pkg/plugingetter/getter.go]: Any reason for this change?

File: integration/plugin/volume/main_test.go [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+	cmd := exec.Command(goBin, "build", "-o", installPath, "./"+filepath.Join("cmd", name))
+	cmd.Env = append(cmd.Env, "CGO_ENABLED=0")
+	if out, err := cmd.CombinedOutput(); err != nil {
+		t.Fatal(errors.Wrapf(err, "error building basic plugin bin: %s", string(out)))
+	}
+
+	return installPath
+}
+
+func asVolumeDriver(cfg *plugin.Config) {
```
Comment (ripcurld0) [inline integration/plugin/volume/main_test.go]: Love this idea, learned something new! 👍 💯

File: pkg/plugingetter/getter.go (hunk 1 above)
Comment (cpuguy83) [reply pkg/plugingetter/getter.go]: Just that goimports changed it.

**Comment by thaJeztah** [comment]
ping @vieux @tiborvass PTAL :heart:

**Comment by vieux** [comment]
@tiborvass can you take a look at this one ?

**Review by vieux — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐮
