### PR TITLE
Restore deterministic IPv6 from MAC behavior on default bridge network

### LINKED ISSUE #17739: Regression: Specifying an mac address does not create a deterministic IPv6 address
Description of problem:
The [docs](https://docs.docker.com/engine/userguide/networking/default_network/ipv6/) state that:
> Remember the subnet for Docker containers should at least have a size of /80. This way an IPv6 address can end with the container’s MAC address and you prevent NDP neighbor cache invalidation issues in the Docker layer.

This worked fine until Docker 1.9 came along, as of docker 1.9 the IP addresses are not static anymore.

`docker version`:
```
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:29:38 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:29:38 UTC 2015
 OS/Arch:      linux/amd64
```
`docker info`:
```
Containers: 9
Images: 201
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 221
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 8
Total Memory: 31.35 GiB
Name: *redacted*
ID: *redacted*
WARNING: No memory limit support
WARNING: No swap limit support
```
`uname -a`:
```
Linux *redacted* 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u4 (2015-09-19) x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.):
Bare metal Debian Jessie box.

How reproducible: Always.

Steps to Reproduce:
1. Configure a `/80` for use by docker: `ExecStart=/usr/bin/docker -d --icc=false --ipv6 --fixed-cidr-v6="2001:db8:1234:5678:1337::/80" -H fd://`
2. Start a container using a fixed mac address: `docker run -it --rm --mac-address AA:BB:CC:DD:EE:FF debian ip -6 addr`
3. Observe the output

Actual Results:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
102: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 
    inet6 2001:db8:1234:5678:1337::9/80 scope global tentative 
       valid_lft forever preferred_lft forever
    inet6 fe80::a8bb:ccff:fedd:eeff/64 scope link tentative 
       valid_lft forever preferred_lft forever
```

Expected Results:
Taken from another box that still runs on Docker 1.8:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
390: eth0: <NO-CARRIER,BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 
    inet6 2001:db8:1234:5678:1337:aabb:ccdd:eeff/80 scope global tentative 
       valid_lft forever preferred_lft forever
    inet6 fe80::a8bb:ccff:fedd:eeff/64 scope link tentative 
       valid_lft forever preferred_lft forever
```
Note the `2001:db8:1234:5678:1337:aabb:ccdd:eeff/80` containing the container's mac address.

### PR DESCRIPTION
**Pull request by aboch**
Fixes #17739

### CODE REVIEW

**Comment by tiborvass** [comment]
LGTM

**Comment by icecrime** [comment]
Thanks @aboch, do we want it for 1.9.1?

File: daemon/daemon_unix.go [hunk 1]
```diff
@@ -455,12 +455,19 @@ func initBridgeDriver(controller libnetwork.NetworkController, config *Config) e
...
+		deferIPv6Alloc bool
+	)
 	if config.Bridge.FixedCIDRv6 != "" {
 		_, fCIDRv6, err := net.ParseCIDR(config.Bridge.FixedCIDRv6)
 		if err != nil {
 			return err
 		}
+
+		ones, _ := fCIDRv6.Mask.Size()
+		deferIPv6Alloc = ones <= 80
```
Comment (icecrime) [inline daemon/daemon_unix.go]: Just two quick questions:

- What's the meaning of that `ones <= 80`?
- Do we need the `bool` variable or can we just `if ones <= 80 { NetworkOptionDeferIPv6Alloc(true) }`?

Comment (aboch) [inline daemon/daemon_unix.go]: @icecrime 
When IPv6 support was added into docker, the IPv6 address assignment could happen in two ways:
- from MAC address (last 48 bits of the IPv6 address == MAC address)
- or via ip allocator

The first method was the preferred way, always chosen by bridge driver when the IPv6 network had enough host bits to contain the MAC address. That's from where the 80 (128-48) bits comes from.

This logic gave a backdoor access to configure deterministic IPv6 addresses for containers.
In order to restore that behavior (which got broken) only for the default bridge network, I had to bring the 80 bits in here.
Whenever we support the IPAM options for endpoint (container), we can deprecate the above behavior.

Since the `ones` are not visible outside of the if scope, I opted for a bool variable outside.
If I had to initialize the NetworkOption setter function inside the if scope, then I'd need to define anyway an extra variable outside, of type `libnetwork.NetworkOption`. Hence I did not see a difference.

**Comment by aboch** [comment]
@icecrime 
In my opinion this fix should go in 1.9.1 since it fixes a regression.

File: daemon/daemon_unix.go (hunk 1 above)
Comment (icecrime) [inline daemon/daemon_unix.go]: Thanks for the background, I think it's worth a code comment (or people reading this will definitely scratch their heads).

I don't really understand why you would need a variable if you just called `libnetwork.NetworkOptionDeferIPv6Alloc` at that point of the code, but I'll trust you with that :-/

**Comment by icecrime** [comment]
Adding this to 1.9.1 as P0 (regression). Small nits, otherwise LGTM!

**Comment by tiborvass** [comment]
thanks, i can see the comment added, looks good, merging.
