### PR TITLE
Remove string checking in API error handling

### LINKED ISSUE #32144: [RFC] API error handling
Basically https://github.com/docker/docker/blob/master/api/server/httputils/errors.go#L52 has gone on far too long.

To replace this, we've tried a couple of different approaches which were pretty disastrous:

- errcode, which while there's nothing wrong with the errcode package, we used it horribly wrong and for the wrong reasons.
- HTTP errors package - https://github.com/docker/docker/blob/master/api/errors/errors.go#L13

errcode was a neat concept but in practice was misused and made the entire codebase just became absolutely horrible to work on where as before the horribleness was contained to just the API layer.

This lead to the http errors package currently in use for certain cases. This also seems like an "ok" thing, but in practice is also not really used correctly and generally more of a shortcut to correct error handling. We end up with low-level bits worried about HTTP status codes.

We need to standardize on a way to handle errors in the API. This potentially needs to be regardless of how the request came in (HTTP, GRPC, or even a direct function call...e.g. cluster->daemon).

The goal of good error handling is that the caller knows, or at least knows how to find out, the class of error that occurred so that the error can be dealt with appropriately. This is true of function calls and it is true across the "remote" API barrier.

### Goals

- API backends (e.g. `daemon`) should ideally not be concerned with HTTP.
- API clients should be able to read a returned error and be able to know *what* an error is.
- Reduce the cognitive overhead in trying to determine how to return an error
i. Example, what status code? (400, 409, 422, 412)
ii. How do I get the API to produce that status code I expect?
iii. How would non-remote API callers handle my error?
- Ensure status codes don't change because of either a change to the error text, or hopefully even a change to the low-level error type.

The way I see it there are really two ways to deal with this (in no particular order):

### Error class defined in common API package

This means in the API package we define several error classes like so (psuedo-code):

```go
package api

type Error interface {
    error
    NotFound() bool
    // other fn's for conflict, invalid arg, etc
}

type apiError struct { 
    err error
    notFound bool
    conflict bool
    invalidArg bool
}

func (e *apiError) Error() string { return e.err.Error() }
func (e *apiError) NotFound() bool { return e.notFound }

func NewNotFoundError(err error) Error {
    return &apiError{err: err, notFound: true}
}
```

From here the HTTP layer can determine both the error message and the class of error (not found) and the status code to return.

This approach is similar to the current approach we have except it's moving the http handling to the http layer and non-http code can just deal with this error type.

Another slight alternative but generally the same thing to this would be to use the well defined grpc error codes instead of defining our own. This could fit in well since part of the daemon is already using grpc anyway.

### Define error handling interfaces on backends

In this method, backends would be required to define a set of functions for error handling:

Example:

```go
package api

type ErrorInspector interface {
    IsNotFound(error) bool
    IsConflict(error) bool
    IsInvalidArgument(error) bool
}
```

```go
package container // container router

import "github.com/docker/docker/api"

type ContainerBackend interface {
    CreateContainer(...) error
    DeleteContainer(...) error
    api.ErrorInspector
}

func(r *containerRouter) getContainer(w http.ResponseWriter, req *http.Request) error {
    err := r.backend.DeleteContainer(...)
    if err != nil {
        if r.backend.IsNotFound(err) {
           // make an HTTP 404
       }
       // make an HTTP 500 probably
    }

    // normal
}
```

Writing out the above it seems a little risky since it requires the router to know the failure-modes of the backend. Maybe could be cleaned up a bit.

Interested in your thoughts, other alternatives, etc.

ping @docker/core-engine-maintainers

### PR DESCRIPTION
**Pull request by cpuguy83**
Use strongly typed errors to set HTTP status codes.
Error interfaces are defined in the api/errors package and errors
returned from controllers are checked against these interfaces.

Errors can be wrapped in a pkg/errors.Causer, as long as somewhere in the
line of causes one of the interfaces is implemented. The special error
interfaces take precedence over Causer, meaning if both Causer and one
of the new error interfaces are implemented, the Causer is not
traversed.

Fixes #32144

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @duglin PTAL

File: daemon/cluster/helpers.go [hunk 1]
```diff
@@ -15,7 +14,7 @@ func getSwarm(ctx context.Context, c swarmapi.ControlClient) (*swarmapi.Cluster,
 	}
 
 	if len(rl.Clusters) == 0 {
-		return nil, errors.NewRequestNotFoundError(errNoSwarm)
+		return nil, notFoundError{errNoSwarm}
```
Comment (aaronlehmann) [inline daemon/cluster/helpers.go]: I'd prefer to define `errNoSwarm` with the `notFoundError` wrapper. That will make it harder to return an untyped error by mistake.

File: api/server/middleware/version.go [hunk 2]
```diff
@@ -28,6 +27,16 @@ func NewVersionMiddleware(s, d, m string) VersionMiddleware {
 	}
 }
 
+type versionUnsupportedError struct {
+	Err error
+}
+
+func (e versionUnsupportedError) Error() string {
+	return e.Err.Error()
```
Comment (aaronlehmann) [inline api/server/middleware/version.go]: Let's generate the error message here instead of wrapping a generic error.

File: api/server/httputils/form.go [hunk 3]
```diff
@@ -49,6 +49,16 @@ type ArchiveOptions struct {
 	Path string
 }
 
+type validationError struct {
+	Err error
+}
+
+func (e validationError) Error() string {
+	return e.Err.Error()
```
Comment (aaronlehmann) [inline api/server/httputils/form.go]: Let's generate the error message here instead of wrapping a textual message. We could call this `badParameterError`.

File: api/server/router/network/network_routes.go [hunk 4]
```diff
@@ -82,6 +82,16 @@ SKIP:
 	return httputils.WriteJSON(w, http.StatusOK, list)
 }
 
+type invalidRequestError struct {
+	Err error
+}
+
+func (e invalidRequestError) Error() string {
+	return e.Err.Error()
```
Comment (aaronlehmann) [inline api/server/router/network/network_routes.go]: We could call this `invalidParameterError` and generate the error message here.

File: client/session/manager.go [hunk 5]
```diff
@@ -56,23 +56,23 @@ func (sm *Manager) HandleHTTPRequest(ctx context.Context, w http.ResponseWriter,
...
 		sm.mu.Unlock()
-		return errors.Errorf("protocol %s not supported", proto)
+		return invalidRequest{errors.Errorf("protocol %s not supported", proto)}
 	}
 
 	conn, _, err := hijacker.Hijack()
 	if err != nil {
 		sm.mu.Unlock()
-		return errors.Wrap(err, "failed to hijack connection")
+		return errors.Wrap(&sessionFailed{err}, "failed to hijack connection")
```
Comment (aaronlehmann) [inline client/session/manager.go]: Why `&sessionFailed{err}` instead of `sessionFailed{err}`?

File: container/container.go [hunk 6]
```diff
@@ -723,18 +724,18 @@ func (container *Container) BuildCreateEndpointOptions(n libnetwork.Network, epC
 
 			for _, ips := range ipam.LinkLocalIPs {
 				if linkip = net.ParseIP(ips); linkip == nil && ips != "" {
-					return nil, fmt.Errorf("Invalid link-local IP address:%s", ipam.LinkLocalIPs)
+					return nil, errors.Errorf("Invalid link-local IP address:%s", ipam.LinkLocalIPs)
```
Comment (aaronlehmann) [inline container/container.go]: Looks like there's a missing space here.

File: container/container.go [hunk 7]
```diff
@@ -723,18 +724,18 @@ func (container *Container) BuildCreateEndpointOptions(n libnetwork.Network, epC
...
 				}
 				ipList = append(ipList, linkip)
 
 			}
 
 			if ip = net.ParseIP(ipam.IPv4Address); ip == nil && ipam.IPv4Address != "" {
-				return nil, fmt.Errorf("Invalid IPv4 address:%s)", ipam.IPv4Address)
+				return nil, errors.Errorf("Invalid IPv4 address:%s)", ipam.IPv4Address)
```
Comment (aaronlehmann) [inline container/container.go]: Looks like there's a missing space here.

File: container/container.go [hunk 8]
```diff
@@ -723,18 +724,18 @@ func (container *Container) BuildCreateEndpointOptions(n libnetwork.Network, epC
...
 			}
 
 			if ip6 = net.ParseIP(ipam.IPv6Address); ip6 == nil && ipam.IPv6Address != "" {
-				return nil, fmt.Errorf("Invalid IPv6 address:%s)", ipam.IPv6Address)
+				return nil, errors.Errorf("Invalid IPv6 address:%s)", ipam.IPv6Address)
```
Comment (aaronlehmann) [inline container/container.go]: Looks like there's a missing space here.

File: daemon/container.go [hunk 9]
```diff
@@ -30,7 +29,7 @@ import (
 //  If none of these searches succeed, an error is returned
 func (daemon *Daemon) GetContainer(prefixOrName string) (*container.Container, error) {
 	if len(prefixOrName) == 0 {
-		return nil, errors.NewBadRequestError(fmt.Errorf("No container name or ID supplied"))
+		return nil, validationError{fmt.Errorf("No container name or ID supplied")}
```
Comment (aaronlehmann) [inline daemon/container.go]: It might be cleaner to have a specific error type for this case instead of wrapping a message in something.

File: daemon/errors.go [hunk 10]
```diff
@@ -1,53 +1,112 @@
...
-		return errors.NewRequestNotFoundError(dne)
-	}
-	return err
+func errNotRunning(id string) error {
+	return stateConflictError{errors.Errorf("Container %s is not running", id)}
 }
 
-type errNotRunning struct {
-	containerID string
+type notFoundError struct {
```
Comment (aaronlehmann) [inline daemon/errors.go]: If it doesn't add much more code, it might be cleaner to have specific error types for containers, volumes, images, etc. which are not found, with the errors generated in the `Error` method instead of returning text wrapped by the type.

File: daemon/errors.go [hunk 11]
```diff
@@ -1,53 +1,112 @@
...
+func (e notAllowedError) Cause() error {
+	return e.err
+}
+
+type notModifiedError struct {
+	err error
+}
+
+func (e notModifiedError) Error() string {
+	return e.err.Error()
```
Comment (aaronlehmann) [inline daemon/errors.go]: This struct could have a flag indicating whether the container was already started or already stopped, and generate the error message in the `Error` method.

File: daemon/start.go [hunk 12]
```diff
@@ -11,79 +10,95 @@ import (
...
 
 	container, err := daemon.GetContainer(name)
 	if err != nil {
 		return err
 	}
 
-	if container.IsPaused() {
-		return fmt.Errorf("Cannot start a paused container, try unpause instead.")
-	}
+	err = func() error {
```
Comment (aaronlehmann) [inline daemon/start.go]: Having a variable named `err` that is actually a function might be confusing.

File: daemon/start.go [hunk 13]
```diff
@@ -11,79 +10,95 @@ import (
...
+		container.Lock()
```
Comment (aaronlehmann) [inline daemon/start.go]: Was the lack of locking before a bug? Is it necessary even with the "containers in memdb" changes? (I'm not sure offhand whether `GetContainer` returns copies from that store or actual values)

File: distribution/errors.go [hunk 14]
```diff
@@ -60,6 +60,16 @@ func shouldV2Fallback(err errcode.Error) bool {
 	return false
 }
 
+type notFoundError struct {
```
Comment (aaronlehmann) [inline distribution/errors.go]: This is only used in one place. I think we can define it in a more specific way instead of wrapping a string.

File: plugin/errors.go [hunk 15]
```diff
@@ -0,0 +1,55 @@
+package plugin
+
+import "fmt"
+
+type errNotFound string
+
+func (name errNotFound) Error() string { return fmt.Sprintf("plugin %q not found", string(name)) }
```
Comment (aaronlehmann) [inline plugin/errors.go]: Put the function body on its own line for consistency with the rest of the file.

File: volume/local/local.go [hunk 16]
```diff
@@ -148,6 +139,34 @@ func (r *Root) Name() string {
 	return volume.DefaultDriverName
 }
 
+type alreadyExistsError struct {
+	err error
+}
+
+func (e alreadyExistsError) Error() string {
+	return e.err.Error()
```
Comment (aaronlehmann) [inline volume/local/local.go]: This can generate an error string here instead of wrapping one.

**Review by aaronlehmann — COMMENTED** [review]
This looks like a great start. I think it's the best approach. Clearly there's going to be a bit of work in tracking down untyped errors that need to be converted.

My main comment so far is that in several places there are opportunities to make the error types do more than just wrap a string in a type that has an extra method. When it's simple, I think it's cleaner to generate the error string in the `Error` method. This makes the code returning errors simpler because it doesn't have to generate an appropriate string, just create a typed error object with the appropriate fields filled in. Since we are doing some work here to use custom error types instead of `fmt.Errorf` and friends, I think it's a good opportunity to define those error types thoughtfully.

File: daemon/start.go (hunk 13 above)
Comment (cpuguy83) [inline daemon/start.go]: This would have to be the real container object.
Indeed it was a bug.
This started off as, "let me check all the states here instead of some here and some in the next call in the stack... ok need to lock... ok this should be a defer, too many early returns... oh crap this stuff is mutating the container..."

Comment (cpuguy83) [inline daemon/start.go]: Actually, looking again, and it looks like the function calls are locking, so maybe there's a race here, but I'm going to leave those as is.

File: api/errors/errors.go [hunk 17]
```diff
@@ -1,47 +1,57 @@
 package errors
```
Comment (stevvooe) [inline api/errors/errors.go]: This package name is already heavily overloaded. I'd recommend `errdefs`, as we've done in containerd.

File: api/errors/errors.go [hunk 18]
```diff
@@ -1,47 +1,57 @@
...
 
-import "net/http"
+// NotFoundError signals that the requested object doesn't exist
+type NotFoundError interface {
+	error
```
Comment (stevvooe) [inline api/errors/errors.go]: Secondary interface overloading is not required. Just define the single `NotFound` method.

File: daemon/errors.go [hunk 19]
```diff
@@ -1,53 +1,112 @@
...
-	}
-	return err
+func errNotRunning(id string) error {
+	return stateConflictError{errors.Errorf("Container %s is not running", id)}
 }
 
-type errNotRunning struct {
-	containerID string
+type notFoundError struct {
+	err error
```
Comment (stevvooe) [inline daemon/errors.go]: `cause`.

File: api/server/httputils/errors.go [hunk 20]
```diff
@@ -37,49 +33,44 @@ func GetHTTPErrorStatusCode(err error) int {
...
-	errMsg := err.Error()
 
-	switch e := err.(type) {
-	case httpStatusError:
-		statusCode = e.HTTPErrorStatusCode()
-	case inputValidationError:
+	// Stop right there
+	// Are you sure you should be adding a new error class here? Do one of the existing ones work?
+
+	switch err.(type) {
```
Comment (stevvooe) [inline api/server/httputils/errors.go]: This should operate on the cause or members of the cause chain.

File: api/errors/errors.go [hunk 21]
```diff
@@ -1,47 +1,57 @@
...
+	NotFound()
+}
 
-// apiError is an error wrapper that also
-// holds information about response status codes.
-type apiError struct {
+// InvalidParameterError signals that the user input is invalid
+type InvalidParameterError interface {
```
Comment (stevvooe) [inline api/errors/errors.go]: Rather than export these interfaces for doing tests, it might be better to export an `IsInvalidParameter` function. This ensures that causality detection is taken into account and keeps that logic in a single place. Otherwise, users of this package will have to use a combination of `Cause()` detection and recursive detection of this specific interface.

File: api/server/httputils/errors.go (hunk 20 above)
Comment (stevvooe) [inline api/server/httputils/errors.go]: Yes, you have to check members of the cause chain:

```go
func IsSomeErr(err error) bool {
  switch err := err.(type) {
  case SomeErr: return err.SomeErr()
  case causal: return IsSomeErr(err.Cause())
  default: return false
  }
}
```

File: api/errors/errors.go (hunk 21 above)
Comment (cpuguy83) [inline api/errors/errors.go]: I think it might be good to still keep these interfaces exported so it shows up in the package docs. But also +1 to adding the `Is<SomeErr>` methods.

File: daemon/cluster/helpers.go (hunk 1 above)
Comment (cpuguy83) [inline daemon/cluster/helpers.go]: Actually good catch as I think this error was using `StatusServiceUnavailable`

File: daemon/cluster/errors.go [hunk 22]
```diff
@@ -0,0 +1,104 @@
...
+)
+
+// errNoSwarm is returned on leaving a cluster that was never initialized
+var errNoSwarm = errors.New("This node is not part of a swarm")
+
+// errSwarmExists is returned on initialize or join request for a cluster that has already been activated
+var errSwarmExists = errors.New("This node is already part of a swarm. Use \"docker swarm leave\" to leave this swarm and join another one.")
+
+// errSwarmJoinTimeoutReached is returned when cluster join could not complete before timeout was reached.
+var errSwarmJoinTimeoutReached = errors.New("Timeout was reached before node was joined. The attempt to join the swarm will continue in the background. Use the \"docker info\" command to see the current swarm status of your node.")
```
Comment (cpuguy83) [inline daemon/cluster/errors.go]: @aaronlehmann Doesn't look like this error was specifically caught by any error checks. Should this remain a http status 500?

Comment (aaronlehmann) [inline daemon/cluster/errors.go]: Not sure. Maybe it should be 502 or 503?

Also, let's change the message from "... before node was joined" to "...before node joined".

File: api/server/httputils/form.go (hunk 3 above)
Comment (cpuguy83) [inline api/server/httputils/form.go]: This is fine, but we still use this in two other places where it's a different error message.

File: api/server/router/network/network_routes.go (hunk 4 above)
Comment (cpuguy83) [inline api/server/router/network/network_routes.go]: Hmm, I'm not sure on this one. It is legitimately wrapping an error

File: client/session/manager.go [hunk 23]
```diff
@@ -46,7 +46,7 @@ func NewManager() (*Manager, error) {
 func (sm *Manager) HandleHTTPRequest(ctx context.Context, w http.ResponseWriter, r *http.Request) error {
 	hijacker, ok := w.(http.Hijacker)
 	if !ok {
-		return errors.New("handler does not support hijack")
+		return &invalidRequest{errors.New("handler does not support hijack")}
```
Comment (aaronlehmann) [inline client/session/manager.go]: This probably doesn't need to be a pointer.

File: daemon/search.go [hunk 24]
```diff
@@ -38,22 +37,22 @@ func (daemon *Daemon) SearchRegistryForImages(ctx context.Context, filtersArgs s
...
+			return nil, invalidFilter{"is-official", searchFilters.Get("is-official")}
 		}
 	}
 	if searchFilters.Include("stars") {
 		hasStars := searchFilters.Get("stars")
 		for _, hasStar := range hasStars {
 			iHasStar, err := strconv.Atoi(hasStar)
 			if err != nil {
-				return nil, fmt.Errorf("Invalid filter 'stars=%s'", hasStar)
+				return nil, invalidFilter{"Invalid filter 'stars=%s'", []string{hasStar}}
```
Comment (aaronlehmann) [inline daemon/search.go]: This doesn't look right

File: api/server/router/network/filter.go [hunk 25]
```diff
@@ -24,11 +22,19 @@ func filterNetworkByType(nws []types.NetworkResource, netType string) ([]types.N
...
-		return nil, fmt.Errorf("Invalid filter: 'type'='%s'", netType)
+		return nil, invalidFilter(netType)
 	}
 	return retNws, nil
 }
 
+type invalidFilter string
+
+func (e invalidFilter) Error() string {
+	return "Invalid filter: 'type'='" + string(e)
```
Comment (aaronlehmann) [inline api/server/router/network/filter.go]: Looks like there's a missing end quote at the end of the message

File: container/container.go [hunk 26]
```diff
@@ -838,7 +839,7 @@ func (container *Container) BuildCreateEndpointOptions(n libnetwork.Network, epC
 				portStart, portEnd, err = newP.Range()
 			}
 			if err != nil {
-				return nil, fmt.Errorf("Error parsing HostPort value(%s):%v", binding[i].HostPort, err)
+				return nil, errors.Wrapf(err, "Error parsing HostPort value(%s)", binding[i].HostPort)
```
Comment (aaronlehmann) [inline container/container.go]: Add a space between `value` and `(%s)`

File: daemon/list.go [hunk 27]
```diff
@@ -653,7 +653,7 @@ func (daemon *Daemon) filterVolumes(vols []volume.Volume, filter filters.Args) (
 		if filter.ExactMatch("dangling", "true") || filter.ExactMatch("dangling", "1") {
 			danglingOnly = true
 		} else if !filter.ExactMatch("dangling", "false") && !filter.ExactMatch("dangling", "0") {
-			return nil, fmt.Errorf("Invalid filter 'dangling=%s'", filter.Get("dangling"))
+			return nil, invalidFilter{"danglings", filter.Get("dangling")}
```
Comment (aaronlehmann) [inline daemon/list.go]: I think `danglings` should be `dangling`

File: api/errors/errors.go (hunk 21 above)
Comment (stevvooe) [inline api/errors/errors.go]: @cpuguy83 Yes, with some advice like "don't use these directly unless those functions don't work for you".

File: volume/volume.go [hunk 28]
```diff
@@ -366,9 +366,9 @@ func ParseMountSpec(cfg mounttypes.Mount, options ...func(*validateOpts)) (*Moun
 }
 
 func errInvalidMode(mode string) error {
-	return fmt.Errorf("invalid mode: %v", mode)
+	return errors.Errorf("invalid mode: %v", mode)
```
Comment (aaronlehmann) [inline volume/volume.go]: Should this and `errInvalidSpec` return `validationError`s?

**Comment by thaJeztah** [comment]
CI is failing; guess that's expected while it's still WIP?

**Comment by cpuguy83** [comment]
Yes I have it panicking when there's an untyped error that reaches the http layer to make it easier to find the error offenders.

File: api/server/httputils/errors.go [hunk 29]
```diff
@@ -37,49 +33,45 @@ func GetHTTPErrorStatusCode(err error) int {
...
 
-	switch e := err.(type) {
-	case httpStatusError:
-		statusCode = e.HTTPErrorStatusCode()
-	case inputValidationError:
+	// Stop right there
+	// Are you sure you should be adding a new error class here? Do one of the existing ones work?
+
+	// Note that the below functions are already checking the error causal chain for matches.
+	switch {
```
Comment (dnephin) [inline api/server/httputils/errors.go]: I understand this is a massive effort. It's great we're removing the "string contains" -> error mapping. However I don't think we should be encouraging new code to write to these error types. 

It seems like we still have this problem (from #32144):

> We end up with low-level bits worried about HTTP status codes.

A 1:1 mapping from "package error" to "http error" means we still have tight coupling between the "application logic packages" and the HTTP API. The low-level bits are still effectively communicating an HTTP error, just with a different mechanism.

I think the correct long term solution is to move away from this centralized `GetHTTPErrorStatusCode()` function entirely. We shouldn't have every error being translated in a single place.

* each package should return specific error types for each applicable error case. These error types don't need to map to anything, they just need to be distinguishable from other errors.
* the HTTP API layer (or whatever API layer) translates the specific errors for each call to the error code that is appropriate in that case.

This is important because a call could result in different error codes depending on the context in which it is used.

So I'm not sure what that means for this PR. I still think it's an improvement over string contains checking, but I think we should comment that `GetHTTPErrorStatusCode()` is deprecated and suggest the correct solution is to handle domain specific errors.

WDYT?

Comment (cpuguy83) [inline api/server/httputils/errors.go]: > It seems like we still have this problem (from #32144):

I do not agree with this statement. We have pieces of code communicating the class of error that occurred, e.g... "I couldn't find the thing", "You requested something I can't do", "This configuration doesn't make sense", etc.

What's really nice about this is the low-level piece can communicate what it knows the error is, and the higher levels can wrap the error in a different error class if needed, or it can just wrap the error with more context and the correct error class is found using the causal interface.

> A 1:1 mapping from "package error" to "http error"

There is not a 1:1 mapping here. There is certainly a strong correlation of the kinds of errors that can be communicated with http status codes, but this is because that's what the status codes are designed to encapsulate.

Comment (dnephin) [inline api/server/httputils/errors.go]: It looks pretty close to 1:1. Classes of errors is a good strategy, but I think there will always be cases where the request context (url, method, etc) change the response code.

---

How would we support more detailed/structured API errors using this scheme? For example, a `NotFound` on a service  create could mean many different things (container, network, secret, etc not found).

A better api would return something like this as the body, along with the 404 error code:

```json
{
   "resource": "network",
   "id": "something",
   "msg": "Network something not found",
   ...
}
```

That way API consumers have more options to communicate the error to users.

Translating errors in the API handlers/router also makes the code much easier to read. You can identify error cases from a single place instead of digging through the entire call stack.
---

Anyway, this is still a huge improvement.

Comment (cpuguy83) [inline api/server/httputils/errors.go]: The problem with this approach is it's treating errors a bit like exceptions where the caller must know every kind of thing that it could happen from the lower layer.
In both cases untyped cases can escape, but in the case of the scope of these escapes is limited to just the things that the lower layer didn't expect (not sure if that wording makes sense...).

**Comment by cpuguy83** [comment]
Ok, this is all green folks. Taking off the `WIP`.

**Comment by thaJeztah** [comment]
ping @dnephin @stevvooe PTAL

File: api/errdefs/defs.go [hunk 30]
```diff
@@ -0,0 +1,54 @@
+package errdefs
+
+// NotFoundError signals that the requested object doesn't exist
+type NotFoundError interface {
```
Comment (stevvooe) [inline api/errdefs/defs.go]: Style nit: these should be `ErrNotFound`.

**Comment by stevvooe** [comment]
LGTM except for the style nit.

In general, this is a step in the right direction. I am unsure about the the package local error definitions, as I think the boilerplate can turn people off from doing correct error handling. However, this approach is the most extensible in the long term.

File: api/errdefs/is.go [hunk 31]
```diff
@@ -0,0 +1,153 @@
...
+
+	_, ok := err.(NotImplementedError)
+	return ok
+}
+
+// IsUnknown returns if the passed in error is an UnknownError
+func IsUnknown(err error) bool {
+	if !isKnown(err) {
+		if causal, ok := err.(causer); ok {
+			return IsNotImplemented(causal.Cause())
```
Comment (aaronlehmann) [inline api/errdefs/is.go]: This is calling the wrong function.

Really not a fan of this pattern - it's too duplicative. I would rather have a single loop with a type switch, where if the error is not recognized by the switch, the loop checks if the error implements `causer` and then repeats with the cause.

Comment (aaronlehmann) [inline api/errdefs/is.go]: Alternatively, it might be possible to simplify the code using reflection. The `Type` interface has an `Implements` method. There could be a generic function that recurses up the causal chain, and takes a `Type` to check the errors against. I'm not sure if this is worth it.

Comment (cpuguy83) [inline api/errdefs/is.go]: Wasn't a fan of the reflect implementation, so I made a single loop to iterate through the causal chain.

File: api/server/httputils/errors.go [hunk 32]
```diff
@@ -37,49 +33,44 @@ func GetHTTPErrorStatusCode(err error) int {
...
-				break
-			}
+		if e, ok := err.(causer); ok {
+			return GetHTTPErrorStatusCode(e.Cause())
 		}
+
+		logrus.WithFields(logrus.Fields{
+			"module":     "api",
+			"error_type": fmt.Sprintf("%T", err),
+		}).Debugf("FIXME: Got API for which error does not match any expected type!!!: %+v", err)
```
Comment (aaronlehmann) [inline api/server/httputils/errors.go]: "Got API"? is there a word missing?

File: api/server/router/build/build_routes.go [hunk 33]
```diff
@@ -173,8 +190,8 @@ func (br *buildRouter) postBuild(ctx context.Context, w http.ResponseWriter, r *
 	buildOptions.AuthConfigs = getAuthConfigs(r.Header)
 
 	if buildOptions.Squash && !br.daemon.HasExperimental() {
-		return apierrors.NewBadRequestError(
-			errors.New("squash is only supported with experimental mode"))
+		return validationError{
+			errors.New("squash is only supported with experimental mode")}
```
Comment (aaronlehmann) [inline api/server/router/build/build_routes.go]: nit: I'd either put this all, on the same line, or put the closing brace on its own line.

File: api/server/router/container/container_routes.go [hunk 34]
```diff
@@ -122,14 +111,22 @@ func (s *containerRouter) getContainersLogs(ctx context.Context, w http.Response
...
 }
 
 func (s *containerRouter) getContainersExport(ctx context.Context, w http.ResponseWriter, r *http.Request, vars map[string]string) error {
 	return s.backend.ContainerExport(vars["name"], w)
 }
 
+type bodyOnStartError struct{}
+
+func (bodyOnStartError) Error() string {
+	return "starting container with non-empty request body was deprecated since v1.10 and removed in v1.12"
```
Comment (aaronlehmann) [inline api/server/router/container/container_routes.go]: Should this refer to an API version instead? (feel free to ignore since it's tangential to the actual change here)

File: api/server/router/experimental.go [hunk 35]
```diff
@@ -39,8 +38,16 @@ func (r *experimentalRoute) Disable() {
 	r.handler = experimentalHandler
 }
 
+type notImplementedError struct{}
+
+func (notImplementedError) Error() string {
+	return errExperimentalFeature.Error()
```
Comment (aaronlehmann) [inline api/server/router/experimental.go]: If this is the only place `errExperimentalFeature` is used, might as well make it a string.

File: api/server/router/swarm/cluster_routes.go [hunk 36]
```diff
@@ -158,7 +172,7 @@ func (sr *swarmRouter) getService(ctx context.Context, w http.ResponseWriter, r
 		insertDefaults, err = strconv.ParseBool(value)
 		if err != nil {
 			err := fmt.Errorf("invalid value for insertDefaults: %s", value)
-			return errors.NewBadRequestError(err)
+			return errors.Wrapf(invalidRequestError{err}, "invalid value for insertDefaults: ", value)
```
Comment (aaronlehmann) [inline api/server/router/swarm/cluster_routes.go]: Looks like there's a missing printf metacharacter

File: builder/remotecontext/remote.go [hunk 37]
```diff
@@ -68,20 +70,37 @@ func MakeRemoteContext(remoteURL string, contentTypeHandlers map[string]func(io.
...
 	if resp.StatusCode < 400 {
 		return resp, nil
 	}
-	msg := fmt.Sprintf("failed to GET %s with status %s", url, resp.Status)
+	msg := fmt.Sprintf("failed to GET %s with status %s", address, resp.Status)
 	body, err := ioutil.ReadAll(resp.Body)
 	resp.Body.Close()
 	if err != nil {
-		return nil, errors.Wrapf(err, msg+": error reading body")
+		return nil, errors.Wrapf(systemError{err}, msg+": error reading body")
```
Comment (aaronlehmann) [inline builder/remotecontext/remote.go]: can be `errors.Wrap`.

File: daemon/archive.go [hunk 38]
```diff
@@ -297,6 +325,9 @@ func (daemon *Daemon) containerExtractToDir(container *container.Container, path
 }
 
 func (daemon *Daemon) containerCopy(container *container.Container, resource string) (rc io.ReadCloser, err error) {
+	if resource[0] == '/' || resource[0] == '\\' {
+		resource = resource[1:]
+	}
```
Comment (aaronlehmann) [inline daemon/archive.go]: I'm confused about what this has to do with error handling. Is it a rebase artifact?

File: daemon/cluster/controllers/plugin/controller.go [hunk 39]
```diff
@@ -198,7 +198,9 @@ func (p *Controller) Wait(ctx context.Context) error {
 }
 
 func isNotFound(err error) bool {
-	_, ok := errors.Cause(err).(plugin.ErrNotFound)
+	_, ok := errors.Cause(err).(interface {
+		NotFound()
+	})
```
Comment (aaronlehmann) [inline daemon/cluster/controllers/plugin/controller.go]: I guess this can use `IsNotFound` unless there's an import cycle.

File: reference/store.go [hunk 40]
```diff
@@ -155,11 +155,14 @@ func (store *store) addReference(ref reference.Named, id digest.Digest, force bo
 	if exists {
 		// force only works for tags
 		if digested, isDigest := ref.(reference.Canonical); isDigest {
-			return fmt.Errorf("Cannot overwrite digest %s", digested.Digest().String())
+			return errors.WithStack(
+				conflictingTagError("Cannot overwrite digest " + digested.Digest().String()))
```
Comment (aaronlehmann) [inline reference/store.go]: nit: My preference is to balance the `(` and `)`.

File: reference/store.go [hunk 41]
```diff
@@ -155,11 +155,14 @@ func (store *store) addReference(ref reference.Named, id digest.Digest, force bo
...
 		}
 
 		if !force {
-			return fmt.Errorf("Conflict: Tag %s is already set to image %s, if you want to replace it, please use -f option", refStr, oldID.String())
+			return errors.WithStack(
+				conflictingTagError(
+					fmt.Sprintf("Conflict: Tag %s is already set to image %s, if you want to replace it, please use the force option", refStr, oldID.String())))
```
Comment (aaronlehmann) [inline reference/store.go]: nit: My preference is to balance the `(` and `)`.

File: daemon/archive.go (hunk 38 above)
Comment (cpuguy83) [inline daemon/archive.go]: If I recall, this was to do with the error message being weird. This is pulled from `ContainerCopy` into this `containerCopy` which is where the implementation is.

File: api/server/router/container/container_routes.go (hunk 34 above)
Comment (cpuguy83) [inline api/server/router/container/container_routes.go]: Fixed this, and of course it broke an integration test.

**Comment by cpuguy83** [comment]
All green again.

**Review by aaronlehmann — APPROVED** [review]
I'm not going to take the time to read through the whole thing again, but if the earlier comments have been addressed, then LGTM!

**Comment by cpuguy83** [comment]
Rebased again.

Ping-a-ling-a-ling.

**Comment by thaJeztah** [comment]
@cpuguy83 unused import in one file;

```
14:26:52 container/container_unix.go:6: imported and not used: "fmt"
14:27:10 Build step 'Execute shell' marked build as failure
```

File: daemon/errors.go [hunk 42]
```diff
@@ -2,52 +2,217 @@ package daemon
...
+	}
+
+	// attempted to mount a file onto a directory, or a directory onto a file, maybe from user specified bind mounts
+	if contains(errDesc, syscall.ENOTDIR.Error()) {
+		errDesc += ": Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type"
+		setExitCode(127)
+		retErr = startInvalidConfigError(errDesc)
+	}
+
+	// TODO: it would be nice to get some better errors from containerd so we can return better errors here
```
Comment (thaJeztah) [inline daemon/errors.go]: @mlaventure ^^ 😇

File: daemon/list.go [hunk 43]
```diff
@@ -265,7 +265,7 @@ func (daemon *Daemon) foldFilter(view container.View, config *types.ContainerLis
 
 	err = psFilters.WalkValues("status", func(value string) error {
 		if !container.IsValidStateString(value) {
-			return fmt.Errorf("Unrecognised filter value for status: %s", value)
+			return validationError{errors.Errorf("Unrecognised filter value for status: %s", value)}
```
Comment (thaJeztah) [inline daemon/list.go]: Wondering why there's a special type for `invalidFilter`, but `error.Errorf()` here

File: daemon/logger/logger.go [hunk 44]
```diff
@@ -8,16 +8,22 @@
...
 	"time"
 
 	"github.com/docker/docker/api/types/backend"
 	"github.com/docker/docker/pkg/jsonlog"
 )
 
-// ErrReadLogsNotSupported is returned when the logger does not support reading logs.
-var ErrReadLogsNotSupported = errors.New("configured logging driver does not support reading")
+// ErrReadLogsNotSupported is returned when the underlying log driver does not support reading
+type ErrReadLogsNotSupported struct{}
```
Comment (thaJeztah) [inline daemon/logger/logger.go]: Is there a reason for the different approach here than for (e.g.); `cluster.notAvailableError`?


```go
type notAvailableError string

func (e notAvailableError) Error() string {
	return string(e)
}

func (e notAvailableError) Unavailable() {}
```

File: integration-cli/docker_api_containers_test.go [hunk 45]
```diff
@@ -1478,7 +1478,7 @@ func (s *DockerSuite) TestPostContainersCreateWithOomScoreAdjInvalidRange(c *che
 	name = "oomscoreadj-low"
 	status, b, err = request.SockRequest("POST", "/containers/create?name="+name, config, daemonHost())
 	c.Assert(err, check.IsNil)
-	c.Assert(status, check.Equals, http.StatusInternalServerError)
+	c.Assert(status, check.Equals, http.StatusBadRequest)
```
Comment (thaJeztah) [inline integration-cli/docker_api_containers_test.go]: :heart: for all these

File: runconfig/errors.go [hunk 46]
```diff
@@ -1,38 +1,42 @@
 package runconfig
 
-import (
-	"fmt"
-)
-
 var (
```
Comment (thaJeztah) [inline runconfig/errors.go]: same here `var` -> `const` ?

File: volume/store/errors.go [hunk 47]
```diff
@@ -2,21 +2,41 @@ package store
 
 import (
 	"strings"
-
-	"github.com/pkg/errors"
 )
 
 var (
```
Comment (thaJeztah) [inline volume/store/errors.go]: And here (ignore me if it doesn't make sense, or I'm overlooking something 😅 )

File: volume/validate.go [hunk 48]
```diff
@@ -135,18 +135,18 @@ func (e *errMountConfig) Error() string {
 }
 
 func errExtraField(name string) error {
-	return fmt.Errorf("field %s must not be specified", name)
+	return errors.Errorf("field %s must not be specified", name)
 }
 func errMissingField(name string) error {
-	return fmt.Errorf("field %s must not be empty", name)
+	return errors.Errorf("field %s must not be empty", name)
```
Comment (thaJeztah) [inline volume/validate.go]: Would something like this be less DRY?

```go
func errMissingField(mnt *mount.Mount, name string) *errMountConfig {
    return &errMountConfig{mnt, errors.Errorf("field %s must not be empty", name)}
}
```

**Review by thaJeztah — CHANGES_REQUESTED** [review]
very cool 👍  left some thoughts, but as usual, let me know if they make sense 😅

File: daemon/errors.go (hunk 42 above)
Comment (mlaventure) [inline daemon/errors.go]: hopefully for `containerd 1.0` :trollface: :angel:

**Review by dnephin — COMMENTED** [review]
I haven't read over every line of the change, but generally LGTM

File: daemon/logger/logger.go (hunk 44 above)
Comment (cpuguy83) [inline daemon/logger/logger.go]: Mostly just that this is the only error in this class for this package.

File: volume/store/errors.go (hunk 47 above)
Comment (cpuguy83) [inline volume/store/errors.go]: It's good, before these couldn't be consts, but now they can.

File: daemon/logger/logger.go (hunk 44 above)
Comment (thaJeztah) [inline daemon/logger/logger.go]: Makes sense, thanks! Was just wondering :D

File: volume/validate.go (hunk 48 above)
Comment (cpuguy83) [inline volume/validate.go]: I'd have to look at it further, but don't want to keep modifying this.
I only changed this to `errors.Errorf` so that we get the stack with the error.

**Review by thaJeztah — APPROVED** [review]
LGTM (if green)

Thanks @cpuguy83, this is so much better!

**Comment by thaJeztah** [comment]
Looks like image search test is still failing (not related to this PR);

```
20:52:12 ----------------------------------------------------------------------
20:52:12 FAIL: docker_cli_search_test.go:47: DockerSuite.TestSearchCmdOptions
20:52:12 
20:52:12 docker_cli_search_test.go:72:
20:52:12     c.Assert(outSearchCmdOfficialSlice, checker.HasLen, 3) // 1 header, 1 line, 1 carriage return
20:52:12 ... obtained []string = []string{"NAME      DESCRIPTION   STARS     OFFICIAL   AUTOMATED", ""}
20:52:12 ... n int = 3
20:52:12 
```

**Comment by thaJeztah** [comment]
Chatted with the Hub team last night, and for some reason the search index was not up-to-date, causing the `busybox` image to not be listed. They rebuilt the index, and the problem should now be fixed; restarting CI

**Comment by thaJeztah** [comment]
Also moving this to "merge", I think there were no more objections

**Comment by yongtang** [comment]
All Jenkins tests passed (finally). Merging..

**Comment by thaJeztah** [comment]
:tada: great work!

**Comment by cpuguy83** [comment]
Thanks all! I know this wasn't fun to review.
