### PR TITLE
Windows: [TP3] Move netmode validation to server

### LINKED ISSUE #14615: --net=host broken in windows client (starting a linux container)
I noticed some changes committed recently around the windows network code that may have broken this.   Running a container like:
docker run -t -i --net=host ubuntu bash
returns: docker: --net: invalid net mode: invalid --net: host.
in windows
but in linux you get the proper behavior of the container starting.

info:
Client:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   b58565e
 Built:        Sun Jul 12 21:13:50 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   5ca3e7c
 Built:        Tue Jul 14 01:16:14 UTC 2015
 OS/Arch:      linux/amd64

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

@swernli

This PR is part of the proposal described in docker/docker issue 10662 to port the docker daemon to Windows. This PR moves the validation of --netmode to the daemon. As the CLI could be pointing to multiple platforms which support different netmodes, it's impossible for the CLI to be deterministic and validate the supplied value.

Fixes #14615

### CODE REVIEW

**Comment by jhowardmsft** [comment]
I'm sure someone will ask why I changed container_config_1_14.json. I went back to Docker v1.2.0 which is API version 1.14. Docker 1.2 has netmode present in HostConfig, but it wasn't present in the fixture. A an empty networkmode is not valid and it's validated in runconfig rather than the client, the tests on runconfig would otherwise fail.

**Comment by jhowardmsft** [comment]
Added tests to integration-cli (reworked from runconfig); rebased; waiting for Jenkins

**Comment by cpuguy83** [comment]
A few failures.

**Comment by jhowardmsft** [comment]
@cpuguy83 - yes, there were a few lazily written tests with incomplete hostconfigs. And a further fix I had to put into runconfig. All the tests should (famous last words) run successfully now. Worked locally.

**Comment by jhowardmsft** [comment]
Now needs an update to docker-py to fix missing netmode in their integration tests....

**Comment by jhowardmsft** [comment]
This should pass Jenkins. But do not merge in it's current form - it has a hack in Dockerfile to pull docker-py from a GitHub branch which has a change which has not yet been PR'd to docker-py. (Will revert this change once Jenkins validates the fix).

**Comment by jhowardmsft** [comment]
Needs https://github.com/opencontainers/runc/pull/127 vendored/merged into docker/master now.

**Comment by jhowardmsft** [comment]
Needs https://github.com/docker/docker/pull/14628

**Comment by jhowardmsft** [comment]
Requires https://github.com/docker/docker-py/pull/691 to be merged and an update of Dockerfile in this PR to match the commit of the updated docker-py post-merge. Otherwise good I believe :)

**Comment by thaJeztah** [comment]
@jhowardmsft is this for the 1.8 release? Should I add it to the milestone?

**Comment by jhowardmsft** [comment]
@thaJeztah No, not for 1.8 unless the Windows daemon still hits 1.8 (still waiting for that freeze, maybe that happened while I was away for a long weekend?). But is needed for TP3.

**Comment by jhowardmsft** [comment]
Update: Not a dead PR. Still waiting on docker-py PR to be merged before can update this PR. Getting closer.

**Comment by icecrime** [comment]
Ping @mavenugo: this PR has a dependency that is not yet resolved, but are you ok with the overall idea?

File: Dockerfile [hunk 1]
```diff
@@ -147,8 +147,9 @@ RUN set -x \
 	&& rm -rf "$GOPATH"
 
 # Get the "docker-py" source so we can run their integration tests
-ENV DOCKER_PY_COMMIT 8a87001d09852058f08a807ab6e8491d57ca1e88
-RUN git clone https://github.com/docker/docker-py.git /docker-py \
+#ENV DOCKER_PY_COMMIT 8a87001d09852058f08a807ab6e8491d57ca1e88
```
Comment (calavera) [inline Dockerfile]: please, remove the comment

Comment (jhowardmsft) [inline Dockerfile]: Yup, it will go. As I put above, it needs an update here to point to the right docker-py once the changes are available there. Otherwise this PR is reviewable as it stands. Just cannot be merged until that final update.

**Comment by thaJeztah** [comment]
@jhowardmsft should this resolve https://github.com/docker/docker/issues/14615? If it does, could you add a `fixes #14615` to the PR description?

**Comment by mavenugo** [comment]
@jhowardmsft apologies on the delay. am reviewing the changes now. 1 general question on your comment :  `A an empty networkmode is not valid`. That is not entirely accurate, especially after we introduced the concept of Default network driver as part of experimental channel (https://github.com/mavenugo/docker/commit/da5a3e6dee80f1f5d4059851e4762ffb0484f7e9). An empty networkmode defaults to "bridge" in order to maintain the backward compatibility, especially with the APIs.
So, we have to be careful with any such assumption.
Will review the code and give more feedback.

**Comment by jhowardmsft** [comment]
@mavenugo To clarify "An empty networkmode is not valid in the hostConfig structure". Yes, I'm aware of the default network change.

**Comment by icecrime** [comment]
docker/docker-py#698 was just merged.

**Comment by jhowardmsft** [comment]
@icecrime Thanks. And thanks @shin-. Updating this PR now.

**Comment by jhowardmsft** [comment]
Updated dockerfile to point to updated docker-py. Fingers crossed on Jenkins

File: integration-cli/docker_api_containers_test.go [hunk 2]
```diff
@@ -879,11 +879,14 @@ func (s *DockerSuite) TestContainerApiBadPort(c *check.C) {
 	config := map[string]interface{}{
 		"Image": "busybox",
 		"Cmd":   []string{"/bin/sh", "-c", "echo test"},
-		"PortBindings": map[string]interface{}{
-			"8080/tcp": []map[string]interface{}{
-				{
-					"HostIP":   "",
-					"HostPort": "aa80",
+		"HostConfig": map[string]interface{}{
+			"NetworkMode": "default",
```
Comment (mavenugo) [inline integration-cli/docker_api_containers_test.go]: Ideally, this must be a backward compatible change and hence there shouldnt be a need for changes in Integration-CLI tests. Am I missing something here on why we need to pass the networkmode for a few test-cases ?

Comment (jhowardmsft) [inline integration-cli/docker_api_containers_test.go]: Arguably the tests were incorrect before - they were passing an incomplete structure to the daemon as the network mode was validated on the client before. As it's being validated on the server now, it must be present.

Comment (mavenugo) [inline integration-cli/docker_api_containers_test.go]: @jhowardmsft I understand your point. But the question was more open than just the IT test-case. Will it impact existing apps that assume (correctly or incorrectly) that the an empty net-mode will be "bridge" ? and is that broken with this change ?
Also, in https://github.com/docker/docker/blob/master/daemon/container_unix.go#L918, we allow for an empty networkmode (just for such cases of existing application assuming empty networkmode means it is operating in default/bridge mode).
Hence, IMHO, any change that impacts backward compatibility must be clearly highlighted and have a wider understanding.

File: runconfig/parse_unix.go [hunk 3]
```diff
@@ -7,51 +7,53 @@ import (
...
 
-func parseNetMode(netMode string) (NetworkMode, error) {
-	parts := strings.Split(netMode, ":")
+// ValidateNetMode ensures that the various combinations of requested
+// network settings are valid.
+func ValidateNetMode(c *Config, hc *HostConfig) error {
+	// We may not be passed a host config, such as in the case of docker commit
+	if hc == nil {
+		return nil
+	}
```
Comment (mavenugo) [inline runconfig/parse_unix.go]: I was wondering on how other Integration-cli tests were passing without forcing the netmode and this gives the answer :-) . I think it will be cleaner to set the network mode as "default" in the server code if we encounter an empty netmode. instead of returning here.

Comment (jhowardmsft) [inline runconfig/parse_unix.go]: @mavenugo I'm not sure I agree with that statement. As it actually happens, from what I have seen, very few commands do NOT pass in a hostConfig. As it is, this is backwards compatible :) "Default" recall is relatively new, so that would actually break backwards compatibility.

Comment (mavenugo) [inline runconfig/parse_unix.go]: @jhowardmsft "default" was introduced exactly to make sure we dont break older versions when we move towards the new driver functionality and have a ability to provide a pluggable default at the daemon level.
Essentially, we didnt have to change anything on the Application to introduce a new feature in the daemon.

am afraid the current changes in this PR breaks that promise (whether it is "default" or "bridge"). 
I will let @icecrime @tiborvass @cpuguy83 & others to comment on this particular point.

Comment (jhowardmsft) [inline runconfig/parse_unix.go]: I'm still not sure I agree here. I have (some time back now) done downlevel CLI checking and didn't hit a problem that indicated any backwards compatibility issues. Are you simply asking that I include "" in the check for possible valid cases here?

Comment (mavenugo) [inline runconfig/parse_unix.go]: It is not a CLI backward compatibility issue (as the CLI always defaults to `default`). But it will be an API issue if we dont address it appropriately.

My suggestion is quite simple. You can move this fix : https://github.com/docker/docker/blob/master/daemon/container_unix.go#L918 to `DecodeContainerConfig` just before calling validateNetMode and everything should just work fine without the need to modify the integration-cli tests.

**Comment by mavenugo** [comment]
ping @jhowardmsft . Can you please address my final comment so that we can get this moving ?

**Comment by jhowardmsft** [comment]
@mavenugo Working on it :)

**Comment by jhowardmsft** [comment]
@mavenugo Quick update on where I am - after moving that, it doesn't work. I'm hitting many tests failing in docker\libnetwork\error.go with ErrInvalidName where name is blank. Investigating still. Haven't pushed my working branch for v2 to GitHub though yet.

**Comment by jhowardmsft** [comment]
@mavenugo I've been working on this most of the afternoon... Your suggestion doesn't appear to be the correct place. DecodeContainerConfig is called in the create API. I'm not sure where to move this code block to in that case, but still looking

**Comment by jhowardmsft** [comment]
@mavenugo - OK, that's fixed. All tests passing. It needed the check moving but putting in both daemon/container.go::Start() as well as getHostConfig for full backwards API compatibility. getHostConfig (previously incorrectly exported as GetHostConfig) is called from both DecodeHostConfig and DecodeContainerConfig in the runconfig package. The common place to update was getHostConfig. That was an uphill struggle to get to this point!! PTAL again. Thanks :)

File: runconfig/hostconfig.go [hunk 4]
```diff
@@ -260,52 +260,44 @@ func NewCapList(caps []string) *CapList {
...
+	GroupAdd             []string         // List of additional groups that the container process will run as
+	RestartPolicy        RestartPolicy    // Restart policy to be used for the container
+	SecurityOpt          []string         // List of string values to customize labels for MLS systems, such as SELinux.
+	ReadonlyRootfs       bool             // Is the container root filesystem in read-only
+	Ulimits              []*ulimit.Ulimit // List of ulimits to be set in the container
+	LogConfig            LogConfig        // Configuration of the logs for this container
+	CgroupParent         string           // Parent cgroup.
+	ConsoleSize          [2]int           // Initial console size on Windows
+	ExplicitExposedPorts bool             // True if --expose was passed from CLI
+	ExplicitPublishPorts bool             // True if --publish was passed from CLI
```
Comment (mavenugo) [inline runconfig/hostconfig.go]: Please correct me if am wrong. It seems these 2 flags are added to carry the `flExpose.Len()` & `flPublish.Len()` to the server side validation. But we could have derived the same info on the server from `hostConfig.PortBindings` and `config.ExposedPorts`. Is there a reason why we need to add these 2 flags ?

File: runconfig/config_unix.go [hunk 5]
```diff
@@ -0,0 +1,55 @@
...
+	// backwards compatible API behaviour.
+	if hc != nil {
+		if hc.NetworkMode == NetworkMode("") {
+			hc.NetworkMode = NetworkMode("default")
+		}
+	} //else {
+	//		hc = &HostConfig{
+	//			NetworkMode: "default",
+	//		}
+	//	}
```
Comment (mavenugo) [inline runconfig/config_unix.go]: Please remove these commented out code.

Comment (jhowardmsft) [inline runconfig/config_unix.go]: Oops my bad. Hang over from when I was testing the right solution. Removing.

File: runconfig/fixtures/container_config_1_14.json [hunk 6]
```diff
@@ -26,5 +26,8 @@
      "ExposedPorts":{
              "22/tcp": {}
      },
-     "RestartPolicy": { "Name": "always" }
+     "RestartPolicy": { "Name": "always" },
+	 "HostConfig": {
+       "NetworkMode": "default"
+     }
```
Comment (mavenugo) [inline runconfig/fixtures/container_config_1_14.json]: I don't quite understand this change. Can you please help understand what this is about ?
the "default" implicit mode is introduced recently. The default used to be "bridge".
I assume this is required for backward compatibility check. But isnt it true that the current code should work without the need for this particular change ?

File: runconfig/parse.go [hunk 7]
```diff
@@ -350,41 +315,43 @@ func Parse(cmd *flag.FlagSet, args []string) (*Config, *HostConfig, *flag.FlagSe
...
+		CapDrop:              NewCapList(flCapDrop.GetAll()),
+		GroupAdd:             flGroupAdd.GetAll(),
+		RestartPolicy:        restartPolicy,
+		SecurityOpt:          flSecurityOpt.GetAll(),
+		ReadonlyRootfs:       *flReadonlyRootfs,
+		Ulimits:              flUlimits.GetList(),
+		LogConfig:            LogConfig{Type: *flLoggingDriver, Config: loggingOpts},
+		CgroupParent:         *flCgroupParent,
+		ExplicitExposedPorts: flExpose.Len() > 0,
+		ExplicitPublishPorts: flPublish.Len() > 0,
```
Comment (mavenugo) [inline runconfig/parse.go]: Same comment as above.

File: runconfig/hostconfig.go (hunk 4 above)
Comment (jhowardmsft) [inline runconfig/hostconfig.go]: Ah, not quite. What gets passed through is a merging of information rather than explicit knowledge of whether the client provided this information directly.

File: runconfig/fixtures/container_config_1_14.json (hunk 6 above)
Comment (jhowardmsft) [inline runconfig/fixtures/container_config_1_14.json]: You may be right now with the latest updates. Let me check.

Comment (jhowardmsft) [inline runconfig/fixtures/container_config_1_14.json]: Yes, you're right. Reverting.

File: runconfig/parse.go (hunk 7 above)
Comment (jhowardmsft) [inline runconfig/parse.go]: Same thing :)

File: runconfig/hostconfig.go (hunk 4 above)
Comment (mavenugo) [inline runconfig/hostconfig.go]: Yes. I understand & appreciate the intention to have least impact to the existing code and hence you added the flag that will exactly mimic the client validation on the server side :-)
But, if you look at the logic and the intention behind that check, it will make it clear.
`if vals.netMode.IsContainer() && (vals.flPublish.Len() > 0 || *vals.flPublishAll == true) {`
`if vals.netMode.IsContainer() && vals.flExpose.Len() > 0 {`

If the network mode is `container:` which means it shares the network namespace with another container, any additional port-mapping or port-expose is not permitted. 
Hence checking for `config.ExposedPorts` and `hostconfig.PortMappings` will give you the exact same expected behavior. Since we are moving the validation from client to server side, I think it is appropriate to do that without having to introduce 2 additional flags just for a single purpose. Wont you agree ?

**Comment by jhowardmsft** [comment]
@mavenugo Updated. Can you verify that my update for your last comment is correct. Running integration-cli locally, and now waiting on Jenkins.

**Comment by mavenugo** [comment]
@jhowardmsft Thanks for addressing all the comments. :+1: 

LGTM.

**Comment by jhowardmsft** [comment]
Thank you so much, @mavenugo!

File: Dockerfile [hunk 8]
```diff
@@ -148,7 +148,7 @@ RUN set -x \
 	&& rm -rf "$GOPATH"
 
 # Get the "docker-py" source so we can run their integration tests
-ENV DOCKER_PY_COMMIT 8a87001d09852058f08a807ab6e8491d57ca1e88
+ENV DOCKER_PY_COMMIT 139850f3f3b17357bab5ba3edfb745fb14043764
```
Comment (tiborvass) [inline Dockerfile]: @jhowardmsft curious to know why you need to bump docker py commit?

File: integration-cli/docker_api_netmode_test.go [hunk 9]
```diff
@@ -0,0 +1,191 @@
...
+		err    error
+		runCmd *exec.Cmd
+	)
+
+	runCmd = exec.Command(dockerBinary, "run", "-h=name", "busybox", "ps")
+	if out, _, err = runCommandWithOutput(runCmd); err != nil {
+		c.Fatalf(out, err)
+	}
+	if !checkPS(out) {
+		c.Fatalf("Expected PS output, got %s", out)
```
Comment (tiborvass) [inline integration-cli/docker_api_netmode_test.go]: you could pass `c` to `checkPs` and do the fatal there

File: integration-cli/docker_api_netmode_test.go [hunk 10]
```diff
@@ -0,0 +1,191 @@
...
+	}
+
+	runCmd = exec.Command(dockerBinary, "run", "-h=name", "--net=host", "busybox", "ps")
+	if out, _, err = runCommandWithOutput(runCmd); err == nil {
+		c.Fatalf(out, err)
```
Comment (tiborvass) [inline integration-cli/docker_api_netmode_test.go]: this should be `err == nil || !strings.Contains(...) {` so that the Fatal message has information on what's expected. Same for all the other `err == nil` checks below

File: integration-cli/docker_api_netmode_test.go (hunk 9 above)
Comment (jhowardmsft) [inline integration-cli/docker_api_netmode_test.go]: Agreed. That makes it a little cleaner. Updating.

Comment (jhowardmsft) [inline integration-cli/docker_api_netmode_test.go]: Actually, making a single function for all the string checks.

File: runconfig/config_windows.go [hunk 11]
```diff
@@ -0,0 +1,13 @@
+package runconfig
+
+// ContainerConfigWrapper is a Config wrapper that hold the container Config (portable)
+// and the corresponding HostConfig (non-portable).
+type ContainerConfigWrapper struct {
+	*Config
+	HostConfig *HostConfig `json:"HostConfig,omitempty"`
```
Comment (tiborvass) [inline runconfig/config_windows.go]: i assume this is not exported via an API, otherwise Linux would call this InnerHostConfig whereas windows calls it HostConfig.

File: Dockerfile (hunk 8 above)
Comment (tiborvass) [inline Dockerfile]: To answer myself: https://github.com/docker/docker/pull/14530#issuecomment-129550264

File: runconfig/config_windows.go (hunk 11 above)
Comment (jhowardmsft) [inline runconfig/config_windows.go]: Let me check.

File: integration-cli/docker_api_netmode_test.go [hunk 12]
```diff
@@ -0,0 +1,191 @@
...
+
+	runCmd = exec.Command(dockerBinary, "run", "-h=name", "--net=none", "busybox", "ps")
+	if out, _, err = runCommandWithOutput(runCmd); err != nil {
+		c.Fatalf(out, err)
+	}
+	if !checkPS(out) {
+		c.Fatalf("Expected PS output, got %s", out)
+	}
+
+	runCmd = exec.Command(dockerBinary, "run", "-h=name", "--net=host", "busybox", "ps")
```
Comment (tiborvass) [inline integration-cli/docker_api_netmode_test.go]: I believe this is already covered by TestRunNetHostNotAllowedWithLinks, we should remove one or the other

File: integration-cli/docker_api_netmode_test.go [hunk 13]
```diff
@@ -0,0 +1,191 @@
...
+	"github.com/docker/docker/runconfig"
+	"github.com/go-check/check"
+)
+
+// GH14530. Validates combinations of --net= with other options
+func checkPS(out string) bool {
+	return strings.Contains(out, "PID   USER")
+}
+
+func (s *DockerSuite) TestNetHostname(c *check.C) {
```
Comment (tiborvass) [inline integration-cli/docker_api_netmode_test.go]: this file is named `docker_api_netmode_test` but it's adding cli tests instead of api tests, which is inconsistent.

File: integration-cli/docker_api_netmode_test.go [hunk 14]
```diff
@@ -0,0 +1,191 @@
...
+}
+
+func (s *DockerSuite) TestConflictContainerNetworkAndLinks(c *check.C) {
+	var (
+		out    string
+		err    error
+		runCmd *exec.Cmd
+	)
+
+	runCmd = exec.Command(dockerBinary, "run", "--net=container:other", "--link=zip:zap", "busybox", "ps")
```
Comment (tiborvass) [inline integration-cli/docker_api_netmode_test.go]: already covered by TestLinksNetworkHostContainer

File: integration-cli/docker_api_netmode_test.go [hunk 15]
```diff
@@ -0,0 +1,191 @@
...
+	if out, _, err = runCommandWithOutput(runCmd); err == nil {
+		c.Fatalf(out, err)
+	}
+	if !strings.Contains(out, runconfig.ErrConflictContainerNetworkAndLinks.Error()) {
+		c.Fatalf("Expected error containing '%s' got %s", runconfig.ErrConflictContainerNetworkAndLinks.Error(), out)
+	}
+
+	runCmd = exec.Command(dockerBinary, "run", "--net=host", "--link=zip:zap", "busybox", "ps")
```
Comment (tiborvass) [inline integration-cli/docker_api_netmode_test.go]: already covered by TestLinksNetworkHostContainer

File: runconfig/config_windows.go (hunk 11 above)
Comment (jhowardmsft) [inline runconfig/config_windows.go]: You're right. Changing to hostConfig.

File: integration-cli/docker_api_netmode_test.go (hunk 13 above)
Comment (jhowardmsft) [inline integration-cli/docker_api_netmode_test.go]: renaming to docker_cli_netmode_test

File: runconfig/config_windows.go (hunk 11 above)
Comment (tiborvass) [inline runconfig/config_windows.go]: Why not InnerHostConfig since Linux exports it too

Comment (tiborvass) [inline runconfig/config_windows.go]: My bad, there's a json tag that makes it both HostConfig so idk

Comment (tiborvass) [inline runconfig/config_windows.go]: I'd say keep it InnerHostConfig to make it obvious that it's the same one than in Linux even if both are tagged as HostConfig.

File: integration-cli/docker_api_netmode_test.go (hunk 15 above)
Comment (jhowardmsft) [inline integration-cli/docker_api_netmode_test.go]: That's unix specific, no reason it can't run from Windows client to Linux daemon. OK if I just remove TestLinksNetworkHostContainer?

Comment (tiborvass) [inline integration-cli/docker_api_netmode_test.go]: Hmm, let's keep it for now then

File: runconfig/config_windows.go (hunk 11 above)
Comment (jhowardmsft) [inline runconfig/config_windows.go]: The use of innerhostconfig on Linux is really a gross hack for backwards compatibility. It really is a hostconfig in the Windows case, there is no back compat we need to keep there. I figured calling an apple an apple rather than a wrapper hack for a banana masquerading as an apple was cleaner :)

Comment (tiborvass) [inline runconfig/config_windows.go]: lol fine then :)

**Comment by tiborvass** [comment]
The tests fail when I run them in windows against a linux daemon

**Comment by jhowardmsft** [comment]
@tiborvass Verified tests work locally Windows to Linux. Waiting for Jenkins. https://gist.github.com/jhowardmsft/50ba1d79f10b1fb81447

File: runconfig/config_windows.go (hunk 11 above)
Comment (jhowardmsft) [inline runconfig/config_windows.go]: What is interesting, and I really can't explain. If I lowercase it, the tests do not pass locally Windows to Linux. Yet if I upper case it (also causing it to be exported, even though never used), the tests DO pass locally.

**Comment by tiborvass** [comment]
LGTM

**Comment by jhowardmsft** [comment]
I've never been so happy to see status/4-merge on a PR so far!!!!! Thank you all for the reviews and comments :)
