### PR TITLE
c8d: Various images/json API fixes

### LINKED ISSUE #43848: containerd integration: make sure images are sorted, and optimize before/since filters
### Description

- relates to https://github.com/moby/moby/pull/43816

The previous implementation sorted the results by "created" (descending order); https://github.com/moby/moby/blob/7624f8aeb1836cd75a0912d9614930e8a59eaf4e/daemon/images/image_list.go#L241

We can either sort locally, or possibly optimize and have containerd return the result in sorted order.

When sorting the results, we can also optimize the `before` and `since` filters to break the loop if we're reaching a certain "created" date.

### LINKED ISSUE #43852: containerd integration: add labels to image list
### Description

The existing implementation includes `labels` as part of the result; https://github.com/moby/moby/blob/b94f7157cae2b5d8943513e96ddfbaa744606c56/daemon/images/image_list.go#L260-L262

### PR DESCRIPTION
**Pull request by rumpl**
**- What I did**

- Added more tests for the image list filters
- Added the image labels to the image list
- Sort the images by creation date
- Populate `RepoTags` with all the tags pointing to an image instead of having multiple objects of the same image in the array.

Fixes #43848
Fixes #43852
Also partially fix*s #43861, I didn't touch `RepoDigests`

**- How I did it**

...

**- How to verify it**

Run
- `make DOCKER_GRAPHDRIVER=overlayfs TEST_FILTER=TestAPIImagesFilter TEST_INTEGRATION_USE_SNAPSHOTTER=1 test-integration`
- `make DOCKER_GRAPHDRIVER=overlayfs TEST_FILTER=TestImagesFilterMultiReference TEST_INTEGRATION_USE_SNAPSHOTTER=1 test-integration`

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: daemon/containerd/image_list.go [hunk 1]
```diff
@@ -136,10 +150,12 @@ func (i *ImageService) Images(ctx context.Context, opts types.ImageListOptions)
 		}
 	}
 
+	sort.Sort(sort.Reverse(byCreated(summaries)))
```
Comment (thaJeztah) [inline daemon/containerd/image_list.go:159]: This looked scary at first; was wondering if it would be sorting _twice_ to reverse it, but looks like `sort.Reverse` just overrides the underlying `sort.Interface` and flips the values.

Slightly wondering though if we always sort `byCreated` in reverse order, or we should update the order there.

File: daemon/containerd/image_list.go [hunk 2]
```diff
@@ -199,14 +215,30 @@ func (i *ImageService) singlePlatformImage(ctx context.Context, contentStore con
...
-
 		digested, err := reference.WithDigest(reference.TrimNamed(ref), target)
 		if err != nil {
 			logger.WithError(err).Error("failed to create digested reference")
 		} else {
 			repoDigests = append(repoDigests, digested.String())
 		}
+
+		for _, referenceDigest := range references {
+			if isDanglingImage(referenceDigest) {
```
Comment (thaJeztah) [inline daemon/containerd/image_list.go:232]: Haven't fully grasped all the logic yet, but I _think_ filtering by "dangling" is possible, including "only show dangling". Would this line mean that we skip dangling images before checking if there's a "dangling" filter?

File: daemon/containerd/image_list.go [hunk 3]
```diff
@@ -32,9 +34,16 @@ var acceptedImageFilterTags = map[string]bool{
 	"until":     true,
 }
 
+// byCreated is a temporary type used to sort a list of images by creation
+// time.
+type byCreated []*types.ImageSummary
+
+func (r byCreated) Len() int           { return len(r) }
+func (r byCreated) Swap(i, j int)      { r[i], r[j] = r[j], r[i] }
+func (r byCreated) Less(i, j int) bool { return r[i].Created < r[j].Created }
```
Comment (thaJeztah) [inline daemon/containerd/image_list.go:50]: Not a blocker, but starting to wonder if we need to move this somewhere central (I was planning to move the image types from `types` to `types/image`, so perhaps that's a good opportunity).

Also considering that sorting may at some point be something we want on the client side as well

File: daemon/containerd/image_list.go [hunk 4]
```diff
@@ -241,13 +247,23 @@ func (i *ImageService) singlePlatformImage(ctx context.Context, contentStore con
 		}
 	}
 
+	cfgDesc, err := image.Image.Config(ctx)
+	if err != nil {
+		return nil, nil, err
+	}
+	var cfg configLabels
+	if err := readConfig(ctx, contentStore, cfgDesc, &cfg); err != nil {
```
Comment (thaJeztah) [inline daemon/containerd/image_list.go:255]: LOL, very unrelated, but I was curious if we make use of the `Data` field anywhere in our code; https://github.com/opencontainers/image-spec/blob/v1.1.0-rc4/specs-go/v1/descriptor.go#L38-L41

```go
	// Data is an embedding of the targeted content. This is encoded as a base64
	// string when marshalled to JSON (automatically, by encoding/json). If
	// present, Data can be used directly to avoid fetching the targeted content.
	Data []byte `json:"data,omitempty"`
```

**Comment by thaJeztah** [comment]
Some failures on Windows, which look related;

```
=== Failed
=== FAIL: github.com/docker/docker/integration-cli TestDockerAPISuite/TestAPIImagesFilter/all_images (0.01s)
    docker_api_images_test.go:103: assertion failed: 2 (int) != 7 (testcase.expectedImages int)

=== FAIL: github.com/docker/docker/integration-cli TestDockerAPISuite/TestAPIImagesFilter/dangling_images (0.00s)
    docker_api_images_test.go:103: assertion failed: 0 (int) != 1 (testcase.expectedImages int)

=== FAIL: github.com/docker/docker/integration-cli TestDockerAPISuite/TestAPIImagesFilter (0.24s)

=== FAIL: github.com/docker/docker/integration-cli TestDockerAPISuite (1.39s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 78 [running]:
testing.tRunner.func1.2({0x13a12c0, 0xc00090ea38})
	C:/hostedtoolcache/windows/go/1.20.6/x64/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
	C:/hostedtoolcache/windows/go/1.20.6/x64/src/testing/testing.go:1529 +0x39f
panic({0x13a12c0, 0xc00090ea38})
	C:/hostedtoolcache/windows/go/1.20.6/x64/src/runtime/panic.go:884 +0x213
github.com/docker/docker/integration-cli.(*DockerAPISuite).TestAPIImagesFilter.func1(0x0?)
	D:/a/moby/moby/go/src/github.com/docker/docker/integration-cli/docker_api_images_test.go:105 +0x2c5
testing.tRunner(0xc000846ea0, 0xc000909b78)
	C:/hostedtoolcache/windows/go/1.20.6/x64/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.20.6/x64/src/testing/testing.go:1629 +0x3ea

DONE 16 tests, 2 skipped, 4 failures in 99.924s

```

File: integration-cli/docker_api_images_test.go [hunk 5]
```diff
@@ -27,29 +28,96 @@ func (s *DockerAPISuite) TestAPIImagesFilter(c *testing.T) {
...
+		},
 	}
 
-	// incorrect number of matches returned
-	images := getImages("utest*/*")
-	assert.Equal(c, len(images[0].RepoTags), 2)
-
-	images = getImages("utest")
-	assert.Equal(c, len(images[0].RepoTags), 1)
+	for _, testcase := range tests {
```
[the remark this answers is not in the document]
Comment (rumpl) [reply integration-cli/docker_api_images_test.go:100]: I must have stumbled on the wrong test, will fix

File: integration-cli/docker_api_images_test.go [hunk 6]
```diff
@@ -27,29 +28,96 @@ func (s *DockerAPISuite) TestAPIImagesFilter(c *testing.T) {
...
+		})
+	}
+}
 
-	images = getImages("utest*")
-	assert.Equal(c, len(images[0].RepoTags), 1)
+func getImages(c *testing.T, apiClient *client.Client, fltrs filters.Args) []types.ImageSummary {
+	c.Helper()
+	options := types.ImageListOptions{
+		All:     false,
```
[the remark this answers is not in the document]
Comment (rumpl) [reply integration-cli/docker_api_images_test.go:114]: Was there before, can remove

File: daemon/containerd/image_list.go (hunk 1 above)
Comment (rumpl) [reply daemon/containerd/image_list.go:159]: Comes from https://github.com/moby/moby/blob/master/daemon/images/image_list.go#L251

File: daemon/containerd/image_list.go (hunk 4 above)
Comment (rumpl) [reply daemon/containerd/image_list.go:255]: I haven't seen any code using that yet TBH. Let me check, if it can be used that would be great actually

File: integration-cli/docker_api_images_test.go [hunk 7]
```diff
@@ -27,29 +28,96 @@ func (s *DockerAPISuite) TestAPIImagesFilter(c *testing.T) {
...
-	getImages := func(filter string) []types.ImageSummary {
-		options := types.ImageListOptions{
-			All:     false,
-			Filters: filters.NewArgs(filters.Arg("reference", filter)),
-		}
-		images, err := apiClient.ImageList(context.Background(), options)
-		assert.NilError(c, err)
 
-		return images
+	tests := []struct {
```
[the remark this answers is not in the document]
Comment (rumpl) [reply integration-cli/docker_api_images_test.go:32]: I was wandering where to put the new tests, guess I chose wrong... I'm not sure why we have both

File: daemon/containerd/image_list.go (hunk 1 above)
Comment (thaJeztah) [reply daemon/containerd/image_list.go:159]: Yup, found that one! Still double checked if it was ok 😂

File: daemon/containerd/image_list.go (hunk 4 above)
Comment (rumpl) [reply daemon/containerd/image_list.go:255]: It doesn't seem to be set by containerd, we might want to take a note of this and see if it can be used really

Comment (thaJeztah) [reply daemon/containerd/image_list.go:255]: Yup! I could see something along the lines of

```go
if desc.Data != nil {
  // fast path
}
```

That said; I wonder if the Spec is clear enough on verifying `Data` matches the referenced data (would be fun if there's no such check and `Data` would return something very different from the referenced file 😂)

File: daemon/containerd/image_list.go [hunk 8]
```diff
@@ -231,47 +279,50 @@ type imageFilterFunc func(image images.Image) bool
...
-		img, err := i.client.GetImage(ctx, ref.String())
+
 		if img != nil {
-			t := img.Metadata().CreatedAt
-			fltrs = append(fltrs, func(image images.Image) bool {
-				created := image.CreatedAt
-				return created.Equal(t) || created.After(t)
+			t := img.Created
+			fltrs = append(fltrs, func(candidate images.Image) bool {
+				cand, err := i.GetImage(ctx, candidate.Name, image.GetImageOpts{})
```
Comment (vvoland) [inline daemon/containerd/image_list.go:295]: Ugh, calling `GetImage` for every image, constructing a big `image.Image` and getting just one of its properties looks very wasteful.
With pointer being returned, this will probably cause many memory allocations to happen on each list operation.
Could we have a smaller `GetImage` that would only unmarshal one property from the config?

File: daemon/containerd/image_list.go [hunk 9]
```diff
@@ -231,47 +279,50 @@ type imageFilterFunc func(image images.Image) bool
...
+				if err != nil {
+					return false
+				}
+
+				return cand.Created != nil && cand.Created.Before(*t)
```
Comment (vvoland) [inline daemon/containerd/image_list.go:300]: Previous code did `After`. Should it be `!cand.Created.Before(*t)`?

File: daemon/containerd/image_list.go [hunk 10]
```diff
@@ -231,47 +279,50 @@ type imageFilterFunc func(image images.Image) bool
...
 			return err
 		}
-		img, err := i.client.GetImage(ctx, ref.String())
+
 		if img != nil {
-			t := img.Metadata().CreatedAt
-			fltrs = append(fltrs, func(image images.Image) bool {
-				created := image.CreatedAt
-				return created.Equal(t) || created.After(t)
+			t := img.Created
```
Comment (vvoland) [inline daemon/containerd/image_list.go:293]: We need a nil check. Otherwise `cand.Created.Before(*t)` below will panic. The filter would be a noop/always false in this case too, so it doesn't even make sense to append it.

File: integration/image/list_test.go [hunk 11]
```diff
@@ -42,12 +42,12 @@ func TestImagesFilterMultiReference(t *testing.T) {
 	filter.Add("reference", repoTags[1])
 	filter.Add("reference", repoTags[2])
 	options := types.ImageListOptions{
-		All:     false,
 		Filters: filter,
 	}
 	images, err := client.ImageList(ctx, options)
 	assert.NilError(t, err)
 
+	assert.Equal(t, len(images), 1)
```
Comment (vvoland) [inline integration/image/list_test.go:50]:
```suggestion
	assert.Check(t, is.Len(images, 1))
```

File: integration/image/list_test.go [hunk 12]
```diff
@@ -93,3 +93,62 @@ func TestImagesFilterBeforeSince(t *testing.T) {
...
+
+	for _, tc := range testcases {
+		tc := tc
+		t.Run(tc.name, func(t *testing.T) {
+			t.Parallel()
+			images, err := client.ImageList(context.Background(), types.ImageListOptions{
+				Filters: filters.NewArgs(tc.filters...),
+			})
+			assert.NilError(t, err)
+			assert.Equal(t, len(images), tc.expectedImages)
```
Comment (vvoland) [inline integration/image/list_test.go:150]:
```suggestion
			assert.Check(t, is.Len(images, tc.expectedImages))
```

**Review by vvoland — CHANGES_REQUESTED** [review]

File: integration/image/list_test.go (hunk 11 above)
Comment (rumpl) [reply integration/image/list_test.go:50]: I do want `Equal` so that the test ends here, if the len is not 1, if it's 0 for example, the next line will panic

File: daemon/containerd/image_list.go (hunk 8 above)
Comment (rumpl) [reply daemon/containerd/image_list.go:293]: Agreed, `GetImage` does a lot of things and loads a bunch of things we don't necessarily need here or in other places of the code. I would like to make listing work as intended before optimizing

Comment (rumpl) [reply daemon/containerd/image_list.go:293]: [See related comment](https://github.com/moby/moby/pull/46034/files#r1269246645) :)

File: daemon/containerd/image_list.go (hunk 9 above)
Comment (rumpl) [reply daemon/containerd/image_list.go]: Previous code was inverted

File: daemon/containerd/image_list.go [hunk 13]
```diff
@@ -199,14 +221,39 @@ func (i *ImageService) singlePlatformImage(ctx context.Context, contentStore con
...
+
+			ref, err := reference.ParseNormalizedNamed(imageRef.Name)
+			if err != nil {
+				return nil, nil, err
+			}
+
+			if image.RealTarget.Digest.String() == imageRef.Target.Digest.String() {
+				repoTags = append(repoTags, reference.FamiliarString(ref))
+			}
+		}
```
Comment (vvoland) [inline daemon/containerd/image_list.go:247]: performance nit: We can easily avoid iterating over all images filtering them over and over again in every `singlePlatformImage` call.

See: https://github.com/vvoland/moby/commit/d2729875afe1a907cc4a0d90aa7aeda3780be71d

**Review by vvoland — COMMENTED** [review]
Overall LGTM, just have one performance nit.

File: daemon/containerd/image_list.go (hunk 13 above)
Comment (rumpl) [reply daemon/containerd/image_list.go:247]: Nice, doesn't look like it works for dangling images at all?

Comment (rumpl) [reply daemon/containerd/image_list.go:247]: I'll fix it and take your perf nit

File: daemon/containerd/image_list.go (hunk 4 above)
Comment (rumpl) [reply daemon/containerd/image_list.go:250]: Related https://github.com/containerd/containerd/pull/8076

**Review by vvoland — APPROVED** [review]

**Review by laurazard — APPROVED** [review]
LGTM

File: daemon/containerd/image_list.go [hunk 14]
```diff
@@ -357,22 +357,24 @@ func (i *ImageService) setupFilters(ctx context.Context, imageFilters filters.Ar
 		})
 	}
 
-	err = imageFilters.WalkValues("reference", func(value string) error {
+	refs := imageFilters.Get("reference")
+	if len(refs) != 0 {
```
Comment (thaJeztah) [inline daemon/containerd/image_list.go:361]: Nit: 

```suggestion
	if refs := imageFilters.Get("reference"); len(refs) != 0 {
```

File: integration/image/list_test.go [hunk 15]
```diff
@@ -93,3 +93,62 @@ func TestImagesFilterBeforeSince(t *testing.T) {
...
+
+func TestAPIImagesFilters(t *testing.T) {
+	t.Cleanup(setupTest(t))
+	client := testEnv.APIClient()
+	ctx := context.Background()
+
+	name := "utest:tag1"
+	name2 := "utest/docker:tag2"
+	name3 := "utest:5000/docker:tag3"
+	for _, n := range []string{name, name2, name3} {
```
Comment (thaJeztah) [inline integration/image/list_test.go:105]: Nit; looks like these vars are not used elsewhere, so may as well inline them;


```suggestion
	for _, n := range []string{"utest:tag1", "utest/docker:tag2", "utest:5000/docker:tag3"} {
```

File: integration/image/list_test.go [hunk 16]
```diff
@@ -93,3 +93,62 @@ func TestImagesFilterBeforeSince(t *testing.T) {
...
+	}
+
+	for _, tc := range testcases {
+		tc := tc
+		t.Run(tc.name, func(t *testing.T) {
+			t.Parallel()
+			images, err := client.ImageList(context.Background(), types.ImageListOptions{
+				Filters: filters.NewArgs(tc.filters...),
+			})
+			assert.NilError(t, err)
```
Comment (thaJeztah) [inline integration/image/list_test.go:149]: This could be a Check as well (we can still check the len(images) on failure).

```suggestion
			assert.Check(t, err)
```

File: daemon/containerd/image_list.go (hunk 4 above)
Comment (thaJeztah) [reply daemon/containerd/image_list.go:250]: Nice, so yes, looks like we can start looking into using that

**Review by thaJeztah — APPROVED** [review]
LGTM

left some nits (you know me 😂), but not blockers, so up to you if you want to address them ❤️

File: daemon/containerd/image_list.go (hunk 14 above)
Comment (rumpl) [reply daemon/containerd/image_list.go]: Done thanks

File: integration/image/list_test.go (hunk 16 above)
Comment (rumpl) [reply integration/image/list_test.go]: Okay :+1:

**Review by thaJeztah — APPROVED** [review]
LGTM!

**Comment by thaJeztah** [comment]
Aaaaaaaand.... all green
