### PR TITLE
builder: Fix `WORKDIR` with a trailing slash causing a cache miss

### LINKED ISSUE #47627: `WORKDIR` is not cached by legacy builder with trailing slash
### Description

In a Dockerfile, when `WORKDIR` is used with a directory with a trailing slash, the resulting image is not cached if using the legacy builder.

### Reproduce

1. Create the following Dockerfile:
```Dockerfile
FROM alpine:latest
WORKDIR /root/
```

2. Run `DOCKER_BUILDKIT=0 docker build . -t test`:
```
% DOCKER_BUILDKIT=0 docker build . -t test 
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            BuildKit is currently disabled; enable it by removing the DOCKER_BUILDKIT=0
            environment-variable.

Sending build context to Docker daemon   5.12kB
Step 1/2 : FROM alpine:latest
 ---> f6648c04cd6c
Step 2/2 : WORKDIR /root/
 ---> Running in 34a640348602
 ---> Removed intermediate container 34a640348602
 ---> 6224b443d3a9
Successfully built 6224b443d3a9
Successfully tagged test:latest
```

3. Run it again. This creates a new image after the `WORKDIR` instruction:
```
% DOCKER_BUILDKIT=0 docker build . -t test
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            BuildKit is currently disabled; enable it by removing the DOCKER_BUILDKIT=0
            environment-variable.

Sending build context to Docker daemon   5.12kB
Step 1/2 : FROM alpine:latest
 ---> f6648c04cd6c
Step 2/2 : WORKDIR /root/
 ---> Running in fa916b3ccf1c
 ---> Removed intermediate container fa916b3ccf1c
 ---> 9d1efadc4384
Successfully built 9d1efadc4384
Successfully tagged test:latest
```

### Expected behavior

During the second run, `Step 2/2` should use the cached image `6224b443d3a9`.

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.11
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:13:26 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.28.0 (139021)
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:22 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    25.0.3
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     /Users/roy/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.6-desktop.1
    Path:     /Users/roy/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.24
    Path:     /Users/roy/.docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/roy/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.22
    Path:     /Users/roy/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /Users/roy/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.1
    Path:     /Users/roy/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/roy/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.5.0
    Path:     /Users/roy/.docker/cli-plugins/docker-scout
WARNING: Plugin "/Users/roy/.docker/cli-plugins/docker-scan" is not valid: failed to fetch metadata: fork/exec /Users/roy/.docker/cli-plugins/docker-scan: no such file or directory

Server:
 Containers: 9
  Running: 8
  Paused: 0
  Stopped: 1
 Images: 491
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.16-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 10
 Total Memory: 11.67GiB
 Name: docker-desktop
 ID: d5458da4-6539-492c-aa92-1e4b8a63110e
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by vvoland**
- closes: https://github.com/moby/moby/issues/47627

**- What I did**

**- How I did it**
Removed `SetupWorkingDirectory` side effect (mutating the container Config).

**- How to verify it**
`TestBuildWorkdirNoCacheMiss`

**- Description for the changelog**
```markdown changelog
classic builder: Fix cache miss on `WORKDIR <directory>/` build step (workdir with a trailing slash).
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: container/container.go [hunk 1]
```diff
@@ -299,8 +299,8 @@ func (container *Container) SetupWorkingDirectory(rootIdentity idtools.Identity)
 		return nil
 	}
 
-	container.Config.WorkingDir = filepath.Clean(container.Config.WorkingDir)
```
[the remark this answers is not in the document]
Comment (vvoland) [reply container/container.go:302]: Ah yes, I even had a separate commit that did that, but for some reason I didn't cherry-pick it into this branch.

Done.

[the remark this answers is not in the document]
Comment (coolljt0725) [reply container/container.go:302]: Looks like `docker run ` with `--workdir` to specify a not cleand path, with this change, docker inspect see a not cleaned path.

[the remark this answers is not in the document]
Comment (vvoland) [reply container/container.go:302]: Good point, updated.

**Review by coolljt0725 — APPROVED** [review]
LGTM

**Review by laurazard — APPROVED** [review]
LGTM

File: integration/build/build_test.go [hunk 2]
```diff
@@ -689,6 +689,71 @@ func TestBuildPlatformInvalid(t *testing.T) {
 	assert.Check(t, is.ErrorType(err, errdefs.IsInvalidParameter))
 }
 
+// Test for #47627
+func TestBuildWorkdirNoCacheMiss(t *testing.T) {
```
Comment (thaJeztah) [inline integration/build/build_test.go:693]: Really minor nit here, that it can be more convenient to put a full link to the ticket here, and perhaps to describe the original issue (so that it may not be needed at all to refer to github. I guess "technically" this comment should also follow `// TestBuildWorkdirNoCacheMiss ....` GoDoc format (but I don't think we have linters verifying GoDoc on tests)

Not a blocker; just if you still want to adjust before merging.

File: integration/build/build_test.go [hunk 3]
```diff
@@ -689,6 +689,71 @@ func TestBuildPlatformInvalid(t *testing.T) {
...
+	ctx := setupTest(t)
+
+	for _, tc := range []struct {
+		name       string
+		dockerfile string
+	}{
+		{name: "trailing slash", dockerfile: "FROM busybox\nWORKDIR /foo/"},
+		{name: "no trailing slash", dockerfile: "FROM busybox\nWORKDIR /foo"},
```
Comment (thaJeztah) [inline integration/build/build_test.go:701]: Just a comment / thinking out loud; wondering how we do cache-matching on Windows, where directories are case-insensitive 🤔 (not sure if we should care.. it would be a corner-case at most, mostly curious)

File: integration/build/build_test.go [hunk 4]
```diff
@@ -689,6 +689,71 @@ func TestBuildPlatformInvalid(t *testing.T) {
...
+			firstId := buildAndGetID()
+			secondId := buildAndGetID()
+
+			assert.Check(t, is.Equal(firstId, secondId), "expected cache to be used")
+		})
+	}
+}
+
+func readBuildImageIDs(t *testing.T, rd io.Reader) string {
+	decoder := json.NewDecoder(rd)
```
Comment (thaJeztah) [inline integration/build/build_test.go:731]: This should probably be a `t.Helper()` ?

Comment (thaJeztah) [reply integration/build/build_test.go:731]: We should look if we need proper helpers for `build` tests; ISTR there's various implementations for doing these kind of things (and it's admittedly awkward to test these, as you need to handle the progress stream 😞)

I guess also somewhat related to;

- https://github.com/moby/moby/issues/46528

**Review by thaJeztah — APPROVED** [review]
LGTM; left a small comment about `t.Helper()` and a tiny nit (both not hard blockers)

File: integration/build/build_test.go (hunk 3 above)
Comment (vvoland) [reply integration/build/build_test.go:701]: Yeah I think mixing the case sensitivity will produce a cache miss on Windows.
But that's out of scope of this PR, and probably not a too big deal, as we mostly care about caching the same Dockerfile builds.

File: integration/build/build_test.go (hunk 4 above)
Comment (vvoland) [reply integration/build/build_test.go]: Done

Comment (vvoland) [reply integration/build/build_test.go]: Tbh, instead of working on proper helpers, I'd rather just work on a better API.. 😅

File: integration/build/build_test.go (hunk 3 above)
Comment (thaJeztah) [reply integration/build/build_test.go:701]: Yup, for sure! No need to spend time on that, unless it'd be an actual issue (but if we don't support it, it's likely been like that for years already, so .. 🤷)

File: integration/build/build_test.go (hunk 4 above)
Comment (thaJeztah) [reply integration/build/build_test.go]: > Tbh, instead of working on proper helpers, I'd rather just work on a better API.. 😅

Yup, agreed, and I think we may have to start working on that, also in light of improvements in output / progress with multi-arch etc.

That said; we can't change old API versions, so we'd have to outweigh the amount of work needed to provide more decent helpers for the existing bits, or to fully ignore those, and only focus on "next".

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!
