### PR TITLE
Don't sort plugin mounts slice

### LINKED ISSUE #36698: Plugin starts in 17.03, but won't start in 18.03 (no such file or directory)
When installing a plugin the following error occurs on 18.03 but not on 17.03:

```
time="2018-03-26T16:52:32Z" level=info msg="shim docker-containerd-shim started" address="/containerd-shim/plugins.moby/6a559021da6da2c482fa6081427f22aee88a8a9ae32caeafc612ee80c10acde3/shim.sock" debug=false module="containerd/tasks" pid=26746
time="2018-03-26T16:52:32Z" level=info msg="shim reaped" id=6a559021da6da2c482fa6081427f22aee88a8a9ae32caeafc612ee80c10acde3 module="containerd/tasks"
time="2018-03-26T16:52:44.733615877Z" level=error msg="Sending SIGTERM to plugin failed with error: container is not running"
time="2018-03-26T16:52:44.734292213Z" level=error msg="Handler for POST /v1.37/plugins/dateraiodev/docker-driver/enable returned error: dial unix /run/docker/plugins/6a559021da6da2c482fa6081427f22aee88a8a9ae32caeafc612ee80c10acde3/datera.sock: connect: no such file or directory"
```
**Steps to reproduce the issue:**
1.  Install docker-ce 18.03
2. run `docker plugin install dateraiodev/docker-driver` and reply `y` when prompted
3. The command hangs trying to find the plugin then replies that it could not be started due to the above error

Following these same steps on 17.03 does not result in any issue.

No container is generated in `docker-runc list`, so I cannot connect to the container to see why this is occurring.

No other logs are output to `journalctl -u docker.service`

Docker Version
```
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:10:01 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:08:31 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

Docker Info
```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 6
Server Version: 18.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 13
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.953GiB
Name: docker-master-xenial-eac1
ID: DATU:EZHD:7Q3A:W5LE:D4JE:BXYO:UPHE:7FQS:ARRD:GK22:YTJF:2NCE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

I've tried this on both a physical Centos7 box and and multiple clean Ubuntu 16.04 VMs

### PR DESCRIPTION
**Pull request by cpuguy83**
This was added as part of a53930a04fa81b082aa78e66b342ff19cc63cc5f with
the intent to sort the mounts in the plugin config, but this was sorting
*all* the mounts from the default OCI spec which is problematic.

In reality we don't need to sort this because we are only adding a
self-binded mount to flag it as rshared.

We may want to look at sorting the plugin mounts before they are added
to the OCI spec in the future, but for now I think the existing behavior
is fine since the plugin author has control of the order (except for the
propagated mount).

Fixes #36698

### CODE REVIEW

File: integration/plugin/volumes/mounts_test.go [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+	"github.com/docker/docker/integration-cli/daemon"
+	"github.com/docker/docker/integration-cli/fixtures/plugin"
+	"github.com/gotestyourself/gotestyourself/assert"
+	"github.com/gotestyourself/gotestyourself/skip"
+)
+
+// TestPluginWithDevMounts tests very specific regression caused by mounts ordering
+// (sorted in the daemon). See #36698
+func TestPluginWithDevMounts(t *testing.T) {
+	skip.IfCondition(t, testEnv.IsRemoteDaemon(), "cannot run daemon when remote daemon")
```
Comment (anusha-ragunathan) [inline integration/plugin/volumes/mounts_test.go]: Just for my knowledge. How does the new test framework run on specific OSes? For example, how does it achieve the old `DaemonIsLinux` condition?

File: integration/plugin/volumes/mounts_test.go [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+	t.Parallel()
+
+	d := daemon.New(t, "", dockerdBinary, daemon.Config{})
+	d.Start(t, "--iptables=false")
+	defer d.Stop(t)
+
+	client, err := d.NewClient()
+	assert.Check(t, err)
```
Comment (anusha-ragunathan) [inline integration/plugin/volumes/mounts_test.go]: `assert.NilError`

Comment (cpuguy83) [reply integration/plugin/volumes/mounts_test.go]: This is a copy-paste from the logging package... I don't know why it was changed to `assert.Check`... @dnephin ?

Comment (cpuguy83) [reply integration/plugin/volumes/mounts_test.go]: I guess `assert.Check` just returns ok if the passed in value is nil. If it's not nil there's some switch on the type, and error types would fail the test.

File: integration/plugin/volumes/mounts_test.go (hunk 1 above)
Comment (cpuguy83) [reply integration/plugin/volumes/mounts_test.go]: This is handled here: https://github.com/moby/moby/pull/36711/files#diff-ead2a878e85c5d12126b9757bff4cf69R24

And yes I totally added that after you said something :)

Also removed this check (which was a copy/paste from logging) since we don't need it here.

File: integration/plugin/volumes/mounts_test.go (hunk 2 above)
Comment (dnephin) [reply integration/plugin/volumes/mounts_test.go]: Yes, that's right. The automated migration converted `testify/assert.NoError` (which uses `t.Fail()`) to `assert.Check()` (which uses `t.Fail()`) because those have the equivalent behaviour. Checking errors with `t.Fail()` is generally going to be wrong and lead to a panic later in the test when something else is nil. So the original test was wrong to use `assert.NoError`, and should have used `require.NoError`.

`gotestyourself/assert.NilError(t, err)` is correct because it uses `t.FailNow()` and stops execution of the test. 

I didn't fix ever place that was using the wrong assertion, because there were many, but I tried to fix up a few.

File: integration/plugin/volumes/helpers_test.go [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+
+	"github.com/docker/docker/api/types"
+	"github.com/docker/docker/integration-cli/fixtures/plugin"
+	"github.com/docker/docker/pkg/locker"
+	"github.com/pkg/errors"
+)
+
+var pluginBuildLock = locker.New()
+
+func ensurePlugin(t *testing.T, name string) string {
```
Comment (anusha-ragunathan) [inline integration/plugin/volumes/helpers_test.go]: Would be nice to add a function comment about expectations:
"DummyPluginSrc at cmd/dummy
DummyPluginInstallPath at $GOPATH/bin/dummy"

Comment (anusha-ragunathan) [reply integration/plugin/volumes/helpers_test.go]: Not in this PR, but we should have a common set of helpers for all plugins, instead of duplicating code.

File: integration/plugin/volumes/helpers_test.go [hunk 4]
```diff
@@ -0,0 +1,67 @@
...
+	pluginBuildLock.Lock(name)
```
Comment (anusha-ragunathan) [inline integration/plugin/volumes/helpers_test.go]: What is this lock protecting?

File: integration-cli/fixtures/plugin/plugin.go [hunk 5]
```diff
@@ -155,6 +155,30 @@ func makePluginBundle(inPath string, opts ...CreateOpt) (io.ReadCloser, error) {
 	if err := os.MkdirAll(filepath.Join(inPath, "rootfs", filepath.Dir(p.Entrypoint[0])), 0755); err != nil {
 		return nil, errors.Wrap(err, "error creating plugin rootfs dir")
 	}
+
+	// Ensure the mount target paths exist
+	for _, m := range p.Mounts {
+		stat, err := os.Stat(*m.Source)
```
Comment (anusha-ragunathan) [inline integration-cli/fixtures/plugin/plugin.go]: Janky panicked due to test case where `m.Source` is nil.
https://github.com/moby/moby/blob/8aa694c91ac727351ebb1deaacad62149e984fd6/integration-cli/docker_cli_plugins_test.go#L175

Please check for `m.Source != nil`

File: integration/plugin/volumes/helpers_test.go (hunk 4 above)
Comment (cpuguy83) [reply integration/plugin/volumes/helpers_test.go]: It makes sure that tests can run in parallel and that we only build a specific binary once.

File: plugin/v2/plugin_linux.go [hunk 6]
```diff
@@ -138,9 +137,5 @@ func (p *Plugin) InitSpec(execRoot string) (*specs.Spec, error) {
 		p.modifyRuntimeSpec(&s)
 	}
 
-	sort.Slice(s.Mounts, func(i, j int) bool {
```
[the remark this answers is not in the document]
Comment (cpuguy83) [reply plugin/v2/plugin_linux.go]: Because it's adding things like a custom /dev/pts for the plugin, but if the host /dev is mounted in first this causes issues.

**Comment by vdemeester** [comment]
@cpuguy83 validation failures :sweat: 

```
01:46:10 integration/plugin/volumes/helpers_test.go:25:15:warning: GetEnv not declared by package os (gosimple)
01:46:10 integration/plugin/volumes/helpers_test.go:26:3:warning: ineffectual assignment to goPath (ineffassign)
```

**Comment by anusha-ragunathan** [comment]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:
