### PR TITLE
Fix unmarshalling of Command and Entrypoint

### LINKED ISSUE #14170: /containers/create no longer accepts strings for Entrypoint
This appears to be a regression in Docker 1.7.0: if a container's `Entrypoint` is specified as a string and not an array of strings, the Docker API returns an error, regardless of the API version specified. It seems to be adding quotes around the executable name, e.g. so it's searching for `"echo"` instead of `echo`.

Test script using docker-py:

```python
# To run:
#   $ docker pull busybox
#   $ python test.py

from docker.utils import kwargs_from_env
from docker import Client

kwargs = kwargs_from_env()
kwargs['tls'].assert_hostname = False
client = Client(**kwargs)

c = client.create_container('busybox', ['hello', 'world'], entrypoint='echo')
client.start(c)
```

Against Docker 1.6.2, the script runs fine and exits with code 0.

Against Docker 1.7.0, it raises an exception:

```
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    client.start(c)
  File "/Users/aanand/.virtualenvs/docker-bug/lib/python2.7/site-packages/docker/utils/decorators.py", line 15, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/Users/aanand/.virtualenvs/docker-bug/lib/python2.7/site-packages/docker/client.py", line 1076, in start
    self._raise_for_status(res)
  File "/Users/aanand/.virtualenvs/docker-bug/lib/python2.7/site-packages/docker/client.py", line 122, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 404 Client Error: Not Found ("Cannot start container e4a84f4c3f9ad749a0d186e465d5e6a460d2f32d8e816b641972767a9439c05e: [8] System error: exec: "\"echo\"": executable file not found in $PATH")
```

### PR DESCRIPTION
**Pull request by cpuguy83**
Closes #14170

### CODE REVIEW

**Comment by duglin** [comment]
@cpuguy83 do you know what broke this?

**Comment by cpuguy83** [comment]
engine removal.

**Comment by cpuguy83** [comment]
FYI, as is in master, this shows up as a quoted string instead of just a string.

**Comment by duglin** [comment]
LOL yea I figured, but I was just curious if there was a particular change that caused it (like the 'env' stuff') or just the overall churn of the rewrite. No biggie if you don't know - was just wondering.

File: integration-cli/docker_api_containers_test.go [hunk 1]
```diff
@@ -1636,3 +1636,26 @@ func (s *DockerSuite) TestPostContainerStop(c *check.C) {
 		c.Fatal(err)
 	}
 }
+
+// #14170
+func (s *DockerSuite) TestPostContainersCreateWithStringOrSliceEntrypoint(c *check.C) {
+	config := struct {
+		Image      string
+		Entrypoint string
```
Comment (duglin) [inline integration-cli/docker_api_containers_test.go]: Entrypoint is defined as a slice, why are you testing it as just a string? Is this backwards compat?

File: integration-cli/docker_api_containers_test.go [hunk 2]
```diff
@@ -1636,3 +1636,26 @@ func (s *DockerSuite) TestPostContainerStop(c *check.C) {
...
+	}{"busybox", "echo", []string{"hello", "world"}}
+	_, _, err := sockRequest("POST", "/containers/create?name=echotest", config)
+	c.Assert(err, check.IsNil)
+	out, _ := dockerCmd(c, "start", "-a", "echotest")
+	c.Assert(strings.TrimSpace(out), check.Equals, "hello world")
+
+	config2 := struct {
+		Image      string
+		Entrypoint []string
+		Cmd        []string
```
Comment (duglin) [inline integration-cli/docker_api_containers_test.go]: if I'm following this PR, you're making sure people can pass a string or a slice of stings for Entrypoint and Cmd, right? If so, I see you test both for Entrypoint, but shouldn't you also test Cmd as a string too?

**Comment by cpuguy83** [comment]
Before it was just using engine.Env. Custom unmarshallimg (and type) was added as part of that. So it hasn't worked at all since then.

**Comment by cpuguy83** [comment]
*as part of removing that

**Comment by LK4D4** [comment]
LGTM

File: integration-cli/docker_api_containers_test.go (hunk 1 above)
Comment (icecrime) [inline integration-cli/docker_api_containers_test.go]: Tested as a slice below AFAICT.

**Comment by icecrime** [comment]
LGTM: holding on merge given @duglin has open questions.

File: integration-cli/docker_api_containers_test.go (hunk 2 above)
Comment (cpuguy83) [inline integration-cli/docker_api_containers_test.go]: I'd intentionally left off the cmd integration test since the semantics for that are different... However I have this now and will force push when I have a chance.
Unit test for cmd is already in place.

Comment (cpuguy83) [inline integration-cli/docker_api_containers_test.go]: added integration test for cmd.

File: integration-cli/docker_api_containers_test.go (hunk 1 above)
Comment (cpuguy83) [inline integration-cli/docker_api_containers_test.go]: Yes, this is specifically what's broken that we are fixing.

**Comment by duglin** [comment]
thanks!
LGTM

**Comment by calavera** [comment]
cherry picked into 1.7.1
