### PR TITLE
Fix race with TestContainerApiCommit

### LINKED ISSUE #12562: race with TestApiCommit
could be race could be something else

sometimes fails with 
```
-- FAIL: TestContainerApiCommit (1.51s)
	docker_utils.go:624: "run a2c4a10d7dc087e421a9c3c6bdbe09d20b0bbb1b9cf5f308c986bb9b1b8436e1 ls /test" failed with errors: ls: /test: No such file or directory
```

### PR DESCRIPTION
**Pull request by cpuguy83**
fix #12562

### CODE REVIEW

File: integration-cli/docker_api_containers_test.go [hunk 1]
```diff
@@ -650,7 +650,7 @@ func (s *DockerSuite) TestContainerApiCommit(c *check.C) {
 	// sanity check, make sure the image is what we think it is
 	out, err = exec.Command(dockerBinary, "run", img.Id, "ls", "/test").CombinedOutput()
 	if err != nil {
-		c.Fatal(out, err)
+		c.Fatal(string(out), err)
```
Comment (duglin) [inline integration-cli/docker_api_containers_test.go]: Since you're touching this line anyway... perhaps it would be more friendly to someone looking at the output if it were:
```
c.Fatal("run failed. out:%s\nerr:%s", out, err)
```
Not a fan of just printing variables like 'err' w/o some text around it to give context.

Comment (cpuguy83) [inline integration-cli/docker_api_containers_test.go]: Probably don't even need to do the error, since it's only ever going to show the `exit status <N>`

Comment (cpuguy83) [inline integration-cli/docker_api_containers_test.go]: Updated

**Comment by duglin** [comment]
LGTM once janky is done

**Comment by jfrazelle** [comment]
you need to write cloese #12562

**Comment by jfrazelle** [comment]
LGTM
