### PR TITLE
integration-cli: migrate some "info" tests to integration

### LINKED ISSUE #40103: Testing: `TestInfoDebug` is failing when using non-17.06 CLI
Just posting my notes here; we're trying to run more tests with different combinations of CLI and Daemon, which includes tests in the (frozen/deprecated) "integration-cli" suite.

Some of those tests are dependent on CLI behaviour, so it's expected that those may fail, but a good occasion to review/update some of them so that we maintain coverage, without relying on CLI behavior. 

## Debugging TestInfoDebug

https://github.com/moby/moby/blob/23b6b5a9ae0e16bdcf37d0ec9a5a8bee9cb38f97/integration-cli/docker_cli_info_test.go#L177-L193

- Test is failing because output format changed
- Test looks to not be very useful, as it seems to be making some wrong assumptions (see below)
    - Only difference between daemon with debug enabled and debug disabled, is the "debug true/false" in the info output
    - The daemon _always_ sends the debug information (NProc, NFd, NGoroutines, SystemTime, NEventsListener, DockerRootDir)
    - The CLI _hides_ the fields above if it detects that the _daemon_ does not have debug enabled
    - This seems wrong, as showing/hiding is a client-side decision, so it should be
      (if at all) dependent on the _CLI_ running with `--debug` enabled.
    - Note that this does _not_ apply to the `--format='{{ json . }}'` output,
      which always shows all fields that are received from the daemon.
    - Perhaps we should always show the information we received (especially
      `"System Time"` looks to be useful, not just for debugging purposes)
- The `docker info` output itself is already widely covered by unit tests in the
  docker/cli repository, which test that information from a `Info` API response
  is printed (and in the right format), both in JSON and "pretty" formats;
  https://github.com/docker/cli/tree/a8ff7f821017ae3d5347392c82718d6cba221681/cli/command/system/testdata

```bash
mkdir results && cd results
```

### 17.06 client, 17.06 daemon (debug disabled)

```bash
export cid="$(docker run -d --rm --privileged -v $(pwd)/results:/results -v /var/lib/docker docker:17.06-dind dockerd)"

docker exec -it "$cid" sh
apk add --no-cache curl jq
docker         info > /results/17.06_cli_daemon.txt
docker --debug info > /results/17.06_cli_debug_daemon.txt
docker         info --format='{{ json .}}' | jq . > /results/17.06_cli_daemon.json
docker --debug info --format='{{ json .}}' | jq . > /results/17.06_cli_debug_daemon.json
curl  --unix-socket /var/run/docker.sock http://localhost/info | jq . > /results/17.06_curl_info_daemon.json
```

### 17.06 client, 17.06 daemon (debug enabled)

```bash
export cid="$(docker run -d --rm --privileged -v $(pwd)/results:/results -v /var/lib/docker docker:17.06-dind dockerd --debug)"

docker exec -it "$cid" sh

apk add --no-cache curl jq
docker         info > /results/17.06_cli_daemon_debug.txt
docker --debug info > /results/17.06_cli_debug_daemon_debug.txt
docker         info --format='{{ json .}}' | jq . > /results/17.06_cli_daemon_debug.json
docker --debug info --format='{{ json .}}' | jq . > /results/17.06_cli_debug_daemon_debug.json
curl  --unix-socket /var/run/docker.sock http://localhost/info | jq . > /results/17.06_curl_info_daemon_debug.json
```

### 19.03 client, 19.03 daemon (debug disabled)

```bash
export cid="$(docker run -d --rm --privileged -v $(pwd)/results:/results -v /var/lib/docker docker:19.03-dind dockerd)"

docker exec -it "$cid" sh
apk add --no-cache curl jq
docker         info > /results/19.03_cli_daemon.txt
docker --debug info > /results/19.03_cli_debug_daemon.txt
docker         info --format='{{ json .}}' | jq . > /results/19.03_cli_daemon.json
docker --debug info --format='{{ json .}}' | jq . > /results/19.03_cli_debug_daemon.json
curl  --unix-socket /var/run/docker.sock http://localhost/info | jq . > /results/19.03_curl_info_daemon.json
```

### 19.03 client, 19.03 daemon (debug enabled)

```bash
export cid="$(docker run -d --rm --privileged -v $(pwd)/results:/results -v /var/lib/docker docker:19.03-dind dockerd --debug)"

docker exec -it "$cid" sh

apk add --no-cache curl jq
docker         info > /results/19.03_cli_daemon_debug.txt
docker --debug info > /results/19.03_cli_debug_daemon_debug.txt
docker         info --format='{{ json .}}' | jq . > /results/19.03_cli_daemon_debug.json
docker --debug info --format='{{ json .}}' | jq . > /results/19.03_cli_debug_daemon_debug.json
curl  --unix-socket /var/run/docker.sock http://localhost/info | jq . > /results/19.03_curl_info_daemon_debug.json
```

Results are uploaded below (renamed `json` to `json.txt` because GitHub doesn't support uploading JSON):

[17.06_cli_daemon_debug.json.txt](https://github.com/moby/moby/files/3743119/17.06_cli_daemon_debug.json.txt)
[17.06_cli_daemon_debug.txt](https://github.com/moby/moby/files/3743120/17.06_cli_daemon_debug.txt)
[17.06_cli_daemon.json.txt](https://github.com/moby/moby/files/3743121/17.06_cli_daemon.json.txt)
[17.06_cli_daemon.txt](https://github.com/moby/moby/files/3743122/17.06_cli_daemon.txt)
[17.06_cli_debug_daemon_debug.json.txt](https://github.com/moby/moby/files/3743123/17.06_cli_debug_daemon_debug.json.txt)
[17.06_cli_debug_daemon_debug.txt](https://github.com/moby/moby/files/3743124/17.06_cli_debug_daemon_debug.txt)
[17.06_cli_debug_daemon.json.txt](https://github.com/moby/moby/files/3743125/17.06_cli_debug_daemon.json.txt)
[17.06_cli_debug_daemon.txt](https://github.com/moby/moby/files/3743126/17.06_cli_debug_daemon.txt)
[17.06_curl_info_daemon_debug.json.txt](https://github.com/moby/moby/files/3743127/17.06_curl_info_daemon_debug.json.txt)
[17.06_curl_info_daemon.json.txt](https://github.com/moby/moby/files/3743128/17.06_curl_info_daemon.json.txt)
[19.03_cli_daemon_debug.json.txt](https://github.com/moby/moby/files/3743129/19.03_cli_daemon_debug.json.txt)
[19.03_cli_daemon_debug.txt](https://github.com/moby/moby/files/3743130/19.03_cli_daemon_debug.txt)
[19.03_cli_daemon.json.txt](https://github.com/moby/moby/files/3743131/19.03_cli_daemon.json.txt)
[19.03_cli_daemon.txt](https://github.com/moby/moby/files/3743132/19.03_cli_daemon.txt)
[19.03_cli_debug_daemon_debug.json.txt](https://github.com/moby/moby/files/3743133/19.03_cli_debug_daemon_debug.json.txt)
[19.03_cli_debug_daemon_debug.txt](https://github.com/moby/moby/files/3743134/19.03_cli_debug_daemon_debug.txt)
[19.03_cli_debug_daemon.json.txt](https://github.com/moby/moby/files/3743135/19.03_cli_debug_daemon.json.txt)
[19.03_cli_debug_daemon.txt](https://github.com/moby/moby/files/3743136/19.03_cli_debug_daemon.txt)
[19.03_curl_info_daemon_debug.json.txt](https://github.com/moby/moby/files/3743137/19.03_curl_info_daemon_debug.json.txt)
[19.03_curl_info_daemon.json.txt](https://github.com/moby/moby/files/3743138/19.03_curl_info_daemon.json.txt)

### PR DESCRIPTION
**Pull request by thaJeztah**
fixes https://github.com/moby/moby/issues/40103

- Updated TestInfoSecurityOptions to not rely on CLI output. Note that this
  test should be migrated to the integration suite, but that suite does not yet
  have checks for "Seccomp" and "AppArmor"
- TestInfoAPIWarnings: don't start with busybox because we're not running containers in this test
- Migrate TestInfoDebug to integration suite
- Migrate TestInsecureRegistries to integration suite (renamed to TestInfoInsecureRegistries)
- Migrate TestRegistryMirrors to integration suite (renamed to TestInfoRegistryMirrors)
- Migrate TestInfoDiscoveryBackend to integration suite
- Migrate TestInfoDiscoveryInvalidAdvertise to integration suite
- Migrate TestInfoDiscoveryAdvertiseInterfaceName to integration suite
- Remove TestInfoFormat, which is testing the CLI functionality, and there is an
  existing test in docker/cli (TestFormatInfo) covering this. Opened https://github.com/docker/cli/pull/2142 to add a test that was being removed here

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @tiborvass @andrewhsu @kolyshkin ptal

File: integration-cli/docker_cli_info_unix_test.go [hunk 1]
```diff
@@ -3,15 +3,30 @@
...
 
+	"github.com/docker/docker/client"
 	"gotest.tools/assert"
+	is "gotest.tools/assert/cmp"
 )
 
 func (s *DockerSuite) TestInfoSecurityOptions(c *testing.T) {
-	testRequires(c, testEnv.IsLocalDaemon, seccompEnabled, Apparmor, DaemonIsLinux)
+	testRequires(c, testEnv.IsLocalDaemon, DaemonIsLinux)
+	if !seccompEnabled() && !Apparmor() {
```
Comment (thaJeztah) [inline integration-cli/docker_cli_info_unix_test.go]: We need to find a new home for some of these (or perhaps we have something like this somewhere in the new `integration/` suite, or in testutils

**Comment by thaJeztah** [comment]
Hm failure looks related. Guess my local machine didn't have AppArmor enabled, so didn't show that case. Will have to have a look

File: integration-cli/docker_cli_info_unix_test.go [hunk 2]
```diff
@@ -3,15 +3,30 @@
...
-	out, _ := dockerCmd(c, "info")
-	assert.Assert(c, strings.Contains(out, "Security Options:\n apparmor\n seccomp\n  Profile: default\n"))
+	cli, err := client.NewClientWithOpts(client.FromEnv)
+	assert.NilError(c, err)
+	defer cli.Close()
+	info, err := cli.Info(context.Background())
+	assert.NilError(c, err)
+
+	if Apparmor() {
+		assert.Check(c, is.Contains(info.SecurityOptions, "apparmor"))
```
Comment (thaJeztah) [inline integration-cli/docker_cli_info_unix_test.go]: Ah; looks like this needs to be `name=apparmor`

File: integration/system/info_test.go [hunk 3]
```diff
@@ -65,3 +67,59 @@ func TestInfoAPIWarnings(t *testing.T) {
...
+		registryHost = "insecurehost.com:5000"
+	)
+
+	d := daemon.New(t)
+	d.Start(t, "--insecure-registry="+registryCIDR, "--insecure-registry="+registryHost)
+	defer d.Stop(t)
+
+	info := d.Info(t)
+	assert.Equal(t, info.RegistryConfig.InsecureRegistryCIDRs[0].String(), registryCIDR)
+	assert.Equal(t, info.RegistryConfig.InsecureRegistryCIDRs[1].String(), "127.0.0.0/8")
```
Comment (kolyshkin) [inline integration/system/info_test.go]: this could potentially be flaky since `InsecureRegistryCIDRs[0]` and `[1]` can change places (as the order does not matter here I believe). If it's not happening in practice, let it be the way it is.

Comment (kolyshkin) [reply integration/system/info_test.go]: to avoid flakiness, sort is required

Comment (thaJeztah) [reply integration/system/info_test.go]: It's a slice, not a map, so I think they should always have the same place.

I can have a quick look to sort them

File: integration/system/info_linux_test.go [hunk 4]
```diff
@@ -43,3 +47,71 @@ func TestInfoAPIVersioned(t *testing.T) {
...
+	err := d.StartWithError("--cluster-store=consul://consuladdr:consulport/some/path", "--cluster-advertise=invalid")
+	assert.ErrorContains(t, err, "")
+	if err == nil {
+		d.Stop(t)
+	}
+
+	// --cluster-advertise without --cluster-store is also an error
+	err = d.StartWithError("--cluster-advertise=1.1.1.1:2375")
+	assert.ErrorContains(t, err, "")
+	if err == nil {
```
Comment (kolyshkin) [inline integration/system/info_linux_test.go]: It looks like the `if` condition is not needed here, since earlier `assert` will fail the test immediately in case an error is returned.

File: integration/system/info_linux_test.go [hunk 5]
```diff
@@ -43,3 +47,71 @@ func TestInfoAPIVersioned(t *testing.T) {
...
+// TestInfoDiscoveryInvalidAdvertise verifies that a daemon run with
+// an invalid `--cluster-advertise` configuration
+func TestInfoDiscoveryInvalidAdvertise(t *testing.T) {
+	skip.If(t, testEnv.IsRemoteDaemon, "cannot run daemon when remote daemon")
+	d := daemon.New(t)
+
+	// --cluster-advertise with an invalid string is an error
+	err := d.StartWithError("--cluster-store=consul://consuladdr:consulport/some/path", "--cluster-advertise=invalid")
+	assert.ErrorContains(t, err, "")
+	if err == nil {
```
Comment (kolyshkin) [inline integration/system/info_linux_test.go]: It looks like the `if` condition is not needed here, since earlier `assert` will fail the test immediately in case an error is returned.

File: integration/system/info_linux_test.go [hunk 6]
```diff
@@ -43,3 +47,71 @@ func TestInfoAPIVersioned(t *testing.T) {
...
+		d.Stop(t)
+	}
+
+	// --cluster-advertise without --cluster-store is also an error
+	err = d.StartWithError("--cluster-advertise=1.1.1.1:2375")
+	assert.ErrorContains(t, err, "")
```
Comment (kolyshkin) [inline integration/system/info_linux_test.go]: ditto

File: integration/system/info_linux_test.go [hunk 7]
```diff
@@ -43,3 +47,71 @@ func TestInfoAPIVersioned(t *testing.T) {
...
+	skip.If(t, testEnv.IsRemoteDaemon, "cannot run daemon when remote daemon")
+	// TODO should we check for networking availability (integration-cli suite checks for networking through `Network()`)
+
+	d := daemon.New(t)
+	const (
+		discoveryBackend   = "consul://consuladdr:consulport/some/path"
+		discoveryAdvertise = "eth0"
+	)
+
+	d.Start(t, "--cluster-store="+discoveryBackend, fmt.Sprintf("--cluster-advertise=%s:2375", discoveryAdvertise))
```
Comment (kolyshkin) [inline integration/system/info_linux_test.go]: nit: I would 
1. rename `discoveryBackend` to `store`
2. rename `discoveryAdvertise` to `interface'
3. add ':2375' as const port and use it like
```go
d.Start(t, "--cluster-store="+store, "--cluster-advertise="+interface+port))
```

**Review by kolyshkin — APPROVED** [review]
left a couple of nits but in general LGTM

File: integration/system/info_linux_test.go (hunk 5 above)
Comment (thaJeztah) [reply integration/system/info_linux_test.go]: ah! I actually looked at this check, and wanted to reverse them (but forgot), so that we make sure to shutdown the daemon properly if the test fails.

**Comment by thaJeztah** [comment]
@kolyshkin updated; PTAL

File: integration/system/info_linux_test.go (hunk 5 above)
Comment (thaJeztah) [reply integration/system/info_linux_test.go]: ^^ reversed them, but github doesn't show it as "outdated"

File: integration/system/info_linux_test.go [hunk 8]
```diff
@@ -43,3 +47,71 @@ func TestInfoAPIVersioned(t *testing.T) {
...
+func TestInfoDiscoveryBackend(t *testing.T) {
+	skip.If(t, testEnv.IsRemoteDaemon, "cannot run daemon when remote daemon")
+
+	const (
+		discoveryBackend   = "consul://consuladdr:consulport/some/path"
+		discoveryAdvertise = "1.1.1.1:2375"
+	)
+
+	d := daemon.New(t)
+	d.Start(t, "-H=0.0.0.0:23756", "-H="+d.Sock(), "--cluster-store="+discoveryBackend, "--cluster-advertise="+discoveryAdvertise)
```
Comment (tiborvass) [inline integration/system/info_linux_test.go]: Why `-H=0.0.0.0:23756` ?

Comment (thaJeztah) [reply integration/system/info_linux_test.go]: Good catch; copy/pasta; removing

Comment (thaJeztah) [reply integration/system/info_linux_test.go]: It's gone.. let's pretend it was never there 😂

**Review by kolyshkin — APPROVED** [review]
LGTM

**Review by tiborvass — APPROVED** [review]
