### PR TITLE
Treat HEALTHCHECK NONE the same as not setting a healthcheck

### LINKED ISSUE #24903: service task is showing no healthcheck when checks are being run
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 16
 Running: 7
 Paused: 0
 Stopped: 9
Images: 252
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 268
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay host bridge
Swarm: active
 NodeID: 58rx1deuh6s3w3g0xukzowhjg
 IsManager: Yes
 Managers: 1
 Nodes: 1
 CACertHash: sha256:02e17c8e2f8453e682f54c1e6c89f66dbd7bc905997ba281bfb1f7c680638491
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.82 GiB
Name: moby
ID: A3IT:LBGP:P3DK:6LCP:YRHJ:BY44:VHCN:X4BF:PAXO:DTD6:P725:EPJC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 72
 Goroutines: 250
 System Time: 2016-07-21T16:55:48.798100815Z
 EventsListeners: 8
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

docker for mac beta

```
FROM busybox
HEALTHCHECK --interval=5s --timeout=1s --retries=3 CMD ls /foo
CMD top
```

**Steps to reproduce the issue:**
1. `docker build -t test .`
2. `docker service create --replicas 1 --name testing test`
3. `docker ps` every second and around 15 it shows no healthcheck

**Describe the results you received:**

no healthcheck is shown even though the events say there is one being run
```
2016-07-21T12:52:30.037159026-04:00 container exec_start: /bin/sh -c ls /foo 619cb234f4a21a2e41972236a316296563d65bc65123ef1285bb852fb4336c60 (com.docker.swarm.node.id=58rx1deuh6s3w3g0xukzowhjg, com.docker.swarm.service.id=96muwz4luzouciic4nbtnud1c, com.docker.swarm.service.name=testing, com.docker.swarm.task=, com.docker.swarm.task.id=7mmdyhggakvtm7lz253x3pa71, com.docker.swarm.task.name=testing.1, image=testhc:latest, name=testing.1.7mmdyhggakvtm7lz253x3pa71)
```

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                            PORTS               NAMES
619cb234f4a2        testhc:latest       "/bin/sh -c top"         5 seconds ago       Up 4 seconds (health: starting)                       testing.1.7mmdyhggakvtm7lz253x3pa71

$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                           PORTS               NAMES
619cb234f4a2        testhc:latest       "/bin/sh -c top"         26 seconds ago      Up 25 seconds (no healthcheck)                       testing.1.7mmdyhggakvtm7lz253x3pa71
```

**Describe the results you expected:**

It shouldn't say no healthcheck when one is being checked. 

**Additional information you deem important (e.g. issue happens only occasionally):**

Should probably keep the status as `starting` until the healthcheck has been determined. That or create a new possible value for health status.

### PR DESCRIPTION
**Pull request by jhorwit2**
closes #24903

**\- What I did**

Treat `HEALTHCHECK NONE` the same as not setting a healthcheck at all. Removed `no healthcheck` from Health string and means it's not showed in the `docker ps` output either. 

**\- How I did it**

If there is no healthcheck probe then don't create/init health check monitoring. Before this PR docker would init the healthcheck monitor for a `HEALTHCHECK NONE` which resulted in the `State.Health.Status` value always being `starting` since it didn't have a probe to update in monitor goroutine. Now, when you set `HEALTHCHECK NONE` the `Health` struct will be nil just like it is when you don't set a healthcheck at all. 

**\- How to verify it**

Create an image w/o a health check. 

```
echo 'FROM busybox
HEALTHCHECK NONE
CMD top' | docker build -t test_none -

docker run -d test_none
```

Then run `docker ps` and you shouldn't see `(no healthcheck)` in the status column. 

```
CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS                               PORTS               NAMES
9767aa9caf61        test_none:latest    "/bin/sh -c top"    About a minute ago   Up About a minute (no healthcheck)                       test_none.1.04n8jw9670vzy3o5pc41wlqni
```

Create another image with either a passing or failing healthcheck (one below fails). You still should see the transition from `starting` -> `unhealthy`. Before this PR it would show `no healthcheck` during the transition from failing the last check -> killing the container because of how the healthcheck was initialized. Now it will show `unhealthy` since the container is being killed. 

```
echo 'FROM busybox
HEALTHCHECK --interval=5s --timeout=1s --retries=3 CMD ls /foo
CMD top' | docker build -t test -

$ docker service create --replicas 1 --name test test

$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                      PORTS               NAMES
f0d335cd81a2        test:latest         "/bin/sh -c top"    26 seconds ago      Up 25 seconds (unhealthy)                       test.1.axy6yvk16ximd3u6gib2sjb1t
d77e1605440f        test_none           "/bin/sh -c top"    4 minutes ago       Up 4 minutes                                    grave_curran
```

**\- Description for the changelog**

Treat HEALTHCHECK NONE the same as not setting a healthcheck. 

Signed-off-by: Josh Horwitz horwitzja@gmail.com

### CODE REVIEW

**Comment by justincormack** [comment]
cc @talex5

**Comment by vdemeester** [comment]
@jhorwit2 overall looks good, you're gonna need to make a PR in `docker/engine-api` 👼

**Comment by jhorwit2** [comment]
yup :). Just wanted to make sure this was OK before i did that. 

https://github.com/docker/engine-api/pull/330 💥

**Comment by talex5** [comment]
This looks good to me.

However, one minor thing: I think a container with `HEALTHCHECK NONE` should act the same as one without any `HEALTHCHECK`.

The example here shows `Up About a minute (no healthcheck)`. I think it should be just `Up About a minute` in this case.

File: daemon/health.go [hunk 1]
```diff
@@ -253,8 +253,14 @@ func (d *Daemon) initHealthMonitor(c *container.Container) {
 
 	if c.State.Health == nil {
 		h := &container.Health{}
-		h.Status = types.Starting
-		h.FailingStreak = 0
+
+		// Happens when the user specified NONE as the healthcheck.
+		if getProbe(c) == nil {
```
Comment (talex5) [inline daemon/health.go]: I think we should move this check to the start of the function (replacing `if c.Config.Healthcheck == nil`). Containers that don't specify a healthcheck should behave the same as containers that specify no healthcheck. Then the `NoHealthCheck` state can be removed too.

**Comment by jhorwit2** [comment]
@talex5 That sounds good to me. I tried to keep the `(no healthcheck)` output because that's how it is in the RC, so I figured there was some reason. I'm struggling to think of a use case where you'd want to know there was `NONE` set over nothing set. I did it this way just in case there was something like that someone thought of so they could use `c.State.Health.Status`.

**Comment by thaJeztah** [comment]
> I'm struggling to think of a use case where you'd want to know there was NONE set over nothing set.

I agree, I don't see a compelling reason, after all, the *end result* of the image should be the same, so I think `NONE` and `not set` should be exactly the same

**Comment by jhorwit2** [comment]
updated to treat them the same. 

cc @talex5 @vdemeester

**Comment by talex5** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM
