### PR TITLE
Fix empty LogPath with non-blocking logging mode

### LINKED ISSUE #36255: Non-blocking logging causes container LogPath to be an empty string
**Description**

The container `LogPath` is set to an empty string when the non-blocking logging mode is enabled.

I believe the problem can be traced to [this line](https://github.com/moby/moby/blob/master/container/container.go#L978), when non-blocking logging is enabled the cast at the linked line fails since the logger will be a `RingLogger` and not a `JSONFileLogger`. The logger is set to be a `RingLogger` [here](https://github.com/moby/moby/blob/master/container/container.go#L409). When the cast fails the `LogPath` is silently not set on the container.

**Steps to reproduce the issue:**
1.  `docker run --name test-log-path --log-opt mode=non-blocking -d debian sleep 100000`
2. `docker inspect test-log-path | grep LogPath`
3. Observe `LogPath` set to an empty string

**Describe the results you received:**

`docker inspect` shows `LogPath` set to an empty string.

**Describe the results you expected:**

I expected `LogPath` to look something like `/var/lib/docker/containers/a48d04bbad7e3624152a48e99212257dc86d065e8470324d7722003d8427a682/a48d04bbad7e3624152a48e99212257dc86d065e8470324d7722003d8427a682-json.log`.

**Additional info:**

I noticed this issue because Kubernetes relies on the `LogPath` output to make `kubectl logs` work. As it stands `kubectl logs` is incompatible with Docker's non-blocking logging due to this bug. 

**Output of `docker version`:**

```
Client:                                    
 Version:       17.12.0-ce                 
 API version:   1.35                       
 Go version:    go1.9.2                    
 Git commit:    c97c6d6                    
 Built: Wed Dec 27 20:12:56 2017           
 OS/Arch:       linux/amd64                
                                           
Server:                                    
 Engine:                                   
  Version:      17.12.0-ce                 
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2                    
  Git commit:   c97c6d6                    
  Built:        Wed Dec 27 20:11:32 2017   
  OS/Arch:      linux/amd64                
  Experimental: false                      
```

**Output of `docker info`:**

```
Containers: 22
 Running: 3
 Paused: 0
 Stopped: 19
Images: 982
Server Version: 17.12.0-ce
Storage Driver: devicemapper
 Pool Name: docker-202:1-667606-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: ext4
 Udev Sync Supported: true
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 20.82GB
 Data Space Total: 107.4GB
 Data Space Available: 14.44GB
 Metadata Space Used: 44.35MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.103GB
 Thin Pool Minimum Free Space: 10.74GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.90 (2014-09-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.71GiB
Name: mnussbaum
ID: WAMT:RW3C:A65N:HFQU:KJIZ:L3XE:UTG7:CRMO:54QJ:YC56:I7SS:Z7WK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

### PR DESCRIPTION
**Pull request by mnussbaum**
**- What I did**

This fixes #36255, an issue where the container `LogPath` was empty when the non-blocking logging mode was enabled. Prior to this change `docker inspect` returned an empty string for `LogPath`. This caused issues with tools that rely on `docker inspect` output to discover container logs, e.g. Kubernetes.

This PR also removes some `LogPath` methods that I believe are now unnecessary and are never invoked.

This PR was co-authored by @JunzeHe.

**- How I did it**

This change sets the `LogPath` on container structs as soon as the path is generated, instead of setting the `LogPath` on a logger struct and then attempting to pull it off that logger at a later point. That attempt to pull the `LogPath` off the logger was error prone since it assumed that the logger would only ever be a single type.

**- How to verify it**

```
docker run --name test-log-path --log-opt mode=non-blocking -d debian sleep infinity
docker inspect test-log-path | grep LogPath
# Observe the LogPath output of inspect is not an empty string, as it was before this change
```

**- Description for the changelog**

Fix empty LogPath with non-blocking logging mode

### CODE REVIEW

**Comment by mnussbaum** [comment]
It looks like my new test is failing under the Windows build. I've tried to run the test suite under windows, but haven't been able to successfully kick it off. When I follow the [instructions for building with Windows](https://github.com/moby/moby/blob/master/docs/contributing/software-req-win.md) using Docker for Windows I get as far as:

```
docker build -t nativebuildimage -f Dockerfile.windows .
``` 

But it fails with the error  `"windows" cannot be used on this platform`, and it does seem that the Docker server believes it's running under Linux.

Any suggestions for debugging the failing Windows build?

**Comment by mnussbaum** [comment]
I've just managed to get the all the builds passing and I think this PR is ready for review!

File: container/container_unit_test.go [hunk 1]
```diff
@@ -66,3 +69,59 @@ func TestContainerSecretReferenceDestTarget(t *testing.T) {
 		t.Fatalf("expected secret dest %q; received %q", expected, d)
 	}
 }
+
+func TestContainerLogPathSetForFileLoggers(t *testing.T) {
```
Comment (cpuguy83) [inline container/container_unit_test.go]: As much as I'd prefer a unit test, I think this one is more appropriate as an integration test.
@dnephin WDYT?

Comment (dnephin) [reply container/container_unit_test.go]: I think a unit test is appropriate here. I really think we should only be writing integration tests for features, not bug fixes.

File: container/container_unit_test.go [hunk 2]
```diff
@@ -66,3 +69,59 @@ func TestContainerSecretReferenceDestTarget(t *testing.T) {
...
+	expectedLogPath, err := filepath.Abs(filepath.Join(rootPath, fmt.Sprintf("%s-json.log", c.ID)))
+	if err != nil {
+		t.Fatalf("Could not get absolute path: %s", err)
+	}
+
+	if c.LogPath != expectedLogPath {
+		t.Fatalf("Expected LogPath for JSON file logger to be %s, got %s", expectedLogPath, c.LogPath)
+	}
+
+	c = &Container{
```
Comment (dnephin) [inline container/container_unit_test.go]: I would split this into two cases here, one for each logger type.

**Review by dnephin — COMMENTED** [review]
You could use `testify/require`

File: container/container_unit_test.go (hunk 1 above)
Comment (cpuguy83) [reply container/container_unit_test.go]: Works for me.

**Comment by mnussbaum** [comment]
Thanks for the feedback so far! I've amended the commit to use testify and include separate tests for each of the file-based logger types

**Review by dnephin — APPROVED** [review]
LGTM

File: container/container_unit_test.go [hunk 3]
```diff
@@ -66,3 +70,54 @@ func TestContainerSecretReferenceDestTarget(t *testing.T) {
...
+	require.NoError(t, err)
+
+	expectedLogPath, err := filepath.Abs(filepath.Join(rootPath, fmt.Sprintf("%s-json.log", c.ID)))
+	require.NoError(t, err)
+	require.Equal(t, c.LogPath, expectedLogPath)
+}
+
+func TestContainerLogPathSetForRingLogger(t *testing.T) {
+	rootPath := filepath.Join(string(filepath.Separator), "root")
+	os.MkdirAll(filepath.Join(rootPath, "root"), os.ModePerm)
```
Comment (cpuguy83) [inline container/container_unit_test.go]: Why not `ioutil.TempDir()`? This looks like it's creating a test dir in `/root/root`?

**Review by cpuguy83 — CHANGES_REQUESTED** [review]

File: container/container_unit_test.go (hunk 3 above)
Comment (mnussbaum) [reply container/container_unit_test.go]: It looks like the build passed using a `TempDir`, let me know if there's any other changes you'd like here

**Review by cpuguy83 — APPROVED** [review]
LGTM

File: container/container_unit_test.go [hunk 4]
```diff
@@ -66,3 +70,52 @@ func TestContainerSecretReferenceDestTarget(t *testing.T) {
 		t.Fatalf("expected secret dest %q; received %q", expected, d)
 	}
 }
+
+func TestContainerLogPathSetForJSONFileLogger(t *testing.T) {
+	containerRoot, err := ioutil.TempDir("", "TestContainerLogPathSetForJSONFileLogger")
```
Comment (cpuguy83) [inline container/container_unit_test.go]: Oh sorry... premature merge...
This needs to be cleaned up in a defer.
```go
defer os.RemoveAll(containerRoot)
```

Can you open a PR to fix that?
Thanks!

Comment (mnussbaum) [reply container/container_unit_test.go]: Opened a cleanup PR at https://github.com/moby/moby/pull/36429

**Comment by mnussbaum** [comment]
Thanks for merging this!

**Comment by mnussbaum** [comment]
One question, @cpuguy83 or @dnephin, do you know what moby release we can expect to see this change in, and when that might go out?

**Comment by cpuguy83** [comment]
@mnussbaum Moby doesn't have releases. Docker does releases and typically has a monthly release for the edge channel and a quarterly release for the stable channel.

**Comment by mnussbaum** [comment]
Gotcha, thanks. I should expect this work to land in the next Docker edge release then?

**Comment by cpuguy83** [comment]
This would likely land in the April edge release.
