### PR TITLE
Fix race #16924 [panic: runtime error: slice bounds out of range] docker daemon crash of racing

### LINKED ISSUE #16924: [panic: runtime error: slice bounds out of range] docker daemon crash of racing when "ADD tar.xz ..." failed to extract
Description of problem:

docker daemon crash of racing when "ADD tar.xz ..." failed to extract some tarball, in my case it's this [gentoo-stage3.tar.xz](http://mirrors.kernel.org/gentoo/releases/amd64/autobuilds/current-stage3-x32/) which contains xattr it will fail extracting when storage driver is aufs (#6980), but there are other reasons could cause [`"xz -d -c -q"`](https://github.com/docker/docker/blob/master/pkg/archive/archive.go#L119-L123) process fail (like a broken tarball ?) I haven't tested yet,

`docker version`: I can reproduce this on today docker/docker#master build, also the latest release v1.8.2

```console
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`: run docker aufs on Ubuntu Desktop 15.10; I use `docker daemon -s aufs -g /home/lib-docker-v1.8.2-tmp` for a clean place for storage driver; if I switch to `-s overlay` that works fine with xattr not reproducing this race crash, but racing problem is there if "xz" fail and break the io.Pipe

```
Containers: 1
Images: 0
Storage Driver: aufs
 Root Dir: /home/lib-docker-v1.8.2-tmp/aufs
 Backing Filesystem: extfs
 Dirs: 2
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.0-11-generic
Operating System: Ubuntu Wily Werewolf (development branch)
CPUs: 8
Total Memory: 15.58 GiB
Name: ubuntu-gnome
ID: JQME:4RIB:2PP7:SCVA:TQV3:VTTL:IYTO:OBIN:Q6VI:EN7V:OQOQ:HJL3
Debug mode (server): true
File Descriptors: 13
Goroutines: 21
System Time: 2015-10-11T13:44:54.864178816-07:00
EventsListeners: 0
Init SHA1: 
Init Path: /home/drc/bin/docker-v1.8.2
Docker Root Dir: /home/lib-docker-v1.8.2-tmp
WARNING: No swap limit support
```

`uname -a`:

```console
$ uname -a
Linux ubuntu-gnome 4.2.0-11-generic #13-Ubuntu SMP Mon Sep 21 21:33:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.): local desktop physical machine.

How reproducible:

run `docker daemon -D -s aufs -g /home/lib-docker-v1.8.2-tmp` as foreground mode, and try to build this Dockerfile

```
FROM scratch
ADD stage3-x32-20151004.tar.xz /
CMD ["/bin/bash"]
```

Steps to Reproduce:
1.
2.
3.

Actual Results:

docker daemon crashed:

```console
[...]
INFO[0000] Docker daemon                                 commit=0a8c2e3 execdriver=native-0.2 graphdriver=aufs version=1.8.2

DEBU[0006] Calling POST /build                          
INFO[0006] POST /v1.20/build?cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&memory=0&memswap=0&rm=1&t=gentoo-x32&ulimits=null 
DEBU[0008] [BUILDER] Cache miss                         
DEBU[0009] Couldn't untar /home/lib-docker-v1.8.2-tmp/tmp/docker-build316710953/stage3-x32-20151004.tar.xz to /home/lib-docker-v1.8.2-tmp/aufs/mnt/d909abb87150463939c13e8a349b889a72d9b14f0cfcab42a8711979be285537: Untar re-exec error: exit status 1: output: operation not supported 
DEBU[0009] CopyFileWithTar(/home/lib-docker-v1.8.2-tmp/tmp/docker-build316710953/stage3-x32-20151004.tar.xz, /home/lib-docker-v1.8.2-tmp/aufs/mnt/d909abb87150463939c13e8a349b889a72d9b14f0cfcab42a8711979be285537/) 
panic: runtime error: slice bounds out of range

goroutine 42 [running]:
bufio.(*Reader).fill(0xc208187800)
	/usr/local/go/src/bufio/bufio.go:86 +0x2db
bufio.(*Reader).WriteTo(0xc208187800, 0x7ff39602d150, 0xc2083f11a0, 0x508000, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:449 +0x27e
io.Copy(0x7ff39602d150, 0xc2083f11a0, 0x7ff3960261f8, 0xc208187800, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:354 +0xb2
github.com/docker/docker/pkg/archive.func·006()
	/go/src/github.com/docker/docker/pkg/archive/archive.go:817 +0x71
created by github.com/docker/docker/pkg/archive.CmdStream
	/go/src/github.com/docker/docker/pkg/archive/archive.go:819 +0x1ec

goroutine 1 [chan receive]:
main.(*DaemonCli).CmdDaemon(0xc20809da30, 0xc20800a020, 0xd, 0xd, 0x0, 0x0)
	/go/src/github.com/docker/docker/docker/daemon.go:289 +0x1781
reflect.callMethod(0xc208140090, 0xc20828fce0)
	/usr/local/go/src/reflect/value.go:605 +0x179
reflect.methodValueCall(0xc20800a020, 0xd, 0xd, 0x1, 0xc208140090, 0x0, 0x0, 0xc208140090, 0x0, 0x45343f, ...)
	/usr/local/go/src/reflect/asm_amd64.s:29 +0x36
github.com/docker/docker/cli.(*Cli).Run(0xc208129fb0, 0xc20800a010, 0xe, 0xe, 0x0, 0x0)
	/go/src/github.com/docker/docker/cli/cli.go:89 +0x38e
main.main()
	/go/src/github.com/docker/docker/docker/docker.go:69 +0x428

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 10 [chan receive]:
github.com/docker/docker/api/server.(*Server).ServeApi(0xc20810eb00, 0xc20809df80, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/server.go:111 +0x74f
main.func·007()
	/go/src/github.com/docker/docker/docker/daemon.go:239 +0x5b
created by main.(*DaemonCli).CmdDaemon
	/go/src/github.com/docker/docker/docker/daemon.go:245 +0xce9

goroutine 11 [chan receive]:
github.com/docker/docker/daemon.func·025()
	/go/src/github.com/docker/docker/daemon/debugtrap_unix.go:17 +0x5c
created by github.com/docker/docker/daemon.setupDumpStackTrap
	/go/src/github.com/docker/docker/daemon/debugtrap_unix.go:20 +0x18e

goroutine 14 [IO wait]:
net.(*pollDesc).Wait(0xc2081f3170, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2081f3170, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).readMsg(0xc2081f3110, 0xc208188040, 0x10, 0x10, 0xc2082ac020, 0x1000, 0x1000, 0xffffffffffffffff, 0x0, 0x0, ...)
	/usr/local/go/src/net/fd_unix.go:296 +0x54e
net.(*UnixConn).ReadMsgUnix(0xc20803a728, 0xc208188040, 0x10, 0x10, 0xc2082ac020, 0x1000, 0x1000, 0x51, 0xc2081a1ce4, 0x4, ...)
	/usr/local/go/src/net/unixsock_posix.go:147 +0x167
github.com/godbus/dbus.(*oobReader).Read(0xc2082ac000, 0xc208188040, 0x10, 0x10, 0xc2082ac000, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/transport_unix.go:21 +0xc5
io.ReadAtLeast(0x7ff396026450, 0xc2082ac000, 0xc208188040, 0x10, 0x10, 0x10, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:298 +0xf1
io.ReadFull(0x7ff396026450, 0xc2082ac000, 0xc208188040, 0x10, 0x10, 0x51, 0x0, 0x0)
	/usr/local/go/src/io/io.go:316 +0x6d
github.com/godbus/dbus.(*unixTransport).ReadMessage(0xc2081cb3c0, 0xc208281c80, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/transport_unix.go:85 +0x1bf
github.com/godbus/dbus.(*Conn).inWorker(0xc208001320)
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/conn.go:248 +0x58
created by github.com/godbus/dbus.(*Conn).Auth
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/auth.go:118 +0xe84

goroutine 13 [IO wait]:
net.(*pollDesc).Wait(0xc2081f3020, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2081f3020, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2081f2fc0, 0x0, 0x7ff39601d340, 0xc2081dda38)
	/usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20803a708, 0xc2081dda70, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc20803a708, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
github.com/docker/docker/pkg/listenbuffer.(*defaultListener).Accept(0xc208109cc0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/pkg/listenbuffer/buffer.go:71 +0x67
crypto/tls.(*listener).Accept(0xc208109d00, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/tls.go:46 +0x6b
net/http.(*Server).Serve(0xc208104660, 0x7ff3960261c0, 0xc208109d00, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1728 +0x92
github.com/docker/docker/api/server.(*HttpServer).Serve(0xc208109e20, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/server.go:126 +0x4d
github.com/docker/docker/api/server.func·002(0x7ff396026298, 0xc208109e20)
	/go/src/github.com/docker/docker/api/server/server.go:102 +0x40
created by github.com/docker/docker/api/server.(*Server).ServeApi
	/go/src/github.com/docker/docker/api/server/server.go:106 +0x6ac

goroutine 15 [chan receive]:
github.com/godbus/dbus.(*Conn).outWorker(0xc208001320)
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/conn.go:370 +0x58
created by github.com/godbus/dbus.(*Conn).Auth
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/auth.go:119 +0xea1

goroutine 16 [chan receive]:
github.com/docker/libnetwork/iptables.signalHandler()
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/iptables/firewalld.go:92 +0x57
created by github.com/docker/libnetwork/iptables.FirewalldInit
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/iptables/firewalld.go:48 +0x185

goroutine 25 [chan receive]:
database/sql.(*DB).connectionOpener(0xc208192be0)
	/usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:452 +0x31c

goroutine 29 [chan receive]:
github.com/godbus/dbus.(*Conn).outWorker(0xc2082a6b40)
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/conn.go:370 +0x58
created by github.com/godbus/dbus.(*Conn).Auth
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/auth.go:119 +0xea1

goroutine 28 [IO wait]:
net.(*pollDesc).Wait(0xc2081eb1e0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2081eb1e0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).readMsg(0xc2081eb180, 0xc2081dd550, 0x10, 0x10, 0xc208296020, 0x1000, 0x1000, 0xffffffffffffffff, 0x0, 0x0, ...)
	/usr/local/go/src/net/fd_unix.go:296 +0x54e
net.(*UnixConn).ReadMsgUnix(0xc20803a6a0, 0xc2081dd550, 0x10, 0x10, 0xc208296020, 0x1000, 0x1000, 0x50, 0xc2081dd2c4, 0x4, ...)
	/usr/local/go/src/net/unixsock_posix.go:147 +0x167
github.com/godbus/dbus.(*oobReader).Read(0xc208296000, 0xc2081dd550, 0x10, 0x10, 0xc208296000, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/transport_unix.go:21 +0xc5
io.ReadAtLeast(0x7ff396026450, 0xc208296000, 0xc2081dd550, 0x10, 0x10, 0x10, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:298 +0xf1
io.ReadFull(0x7ff396026450, 0xc208296000, 0xc2081dd550, 0x10, 0x10, 0x50, 0x0, 0x0)
	/usr/local/go/src/io/io.go:316 +0x6d
github.com/godbus/dbus.(*unixTransport).ReadMessage(0xc20816b5c0, 0xc2081ff320, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/transport_unix.go:85 +0x1bf
github.com/godbus/dbus.(*Conn).inWorker(0xc2082a6b40)
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/conn.go:248 +0x58
created by github.com/godbus/dbus.(*Conn).Auth
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/auth.go:118 +0xe84

goroutine 30 [chan receive]:
github.com/coreos/go-systemd/dbus.func·001()
	/go/src/github.com/docker/docker/vendor/src/github.com/coreos/go-systemd/dbus/subscription.go:70 +0x64
created by github.com/coreos/go-systemd/dbus.(*Conn).initDispatch
	/go/src/github.com/docker/docker/vendor/src/github.com/coreos/go-systemd/dbus/subscription.go:94 +0x11c

goroutine 31 [chan receive]:
github.com/docker/docker/daemon.(*statsCollector).run(0xc208110270)
	/go/src/github.com/docker/docker/daemon/stats_collector_unix.go:91 +0xb2
created by github.com/docker/docker/daemon.newStatsCollector
	/go/src/github.com/docker/docker/daemon/stats_collector_unix.go:31 +0x116

goroutine 32 [chan receive]:
github.com/docker/docker/daemon.(*Daemon).execCommandGC(0xc2080a4a80)
	/go/src/github.com/docker/docker/daemon/exec.go:256 +0x8c
created by github.com/docker/docker/daemon.NewDaemon
	/go/src/github.com/docker/docker/daemon/daemon.go:742 +0x2518

goroutine 33 [chan receive]:
github.com/docker/docker/pkg/signal.func·002()
	/go/src/github.com/docker/docker/pkg/signal/trap.go:29 +0x8f
created by github.com/docker/docker/pkg/signal.Trap
	/go/src/github.com/docker/docker/pkg/signal/trap.go:55 +0x250

goroutine 36 [syscall]:
syscall.Syscall6(0x3d, 0x56c3, 0xc2082c630c, 0x0, 0xc208288870, 0x0, 0x0, 0xc2081a0c30, 0x7ff396012ef8, 0x1)
	/usr/local/go/src/syscall/asm_linux_amd64.s:46 +0x5
syscall.wait4(0x56c3, 0xc2082c630c, 0x0, 0xc208288870, 0x90, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:124 +0x79
syscall.Wait4(0x56c3, 0xc2082c6354, 0x0, 0xc208288870, 0x8, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_linux.go:224 +0x60
os.(*Process).wait(0xc208224300, 0x589a04, 0x0, 0x0)
	/usr/local/go/src/os/exec_unix.go:22 +0x103
os.(*Process).Wait(0xc208224300, 0xc2082c6428, 0x0, 0x0)
	/usr/local/go/src/os/doc.go:45 +0x3a
os/exec.(*Cmd).Wait(0xc2081e2640, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:364 +0x23c
github.com/docker/docker/pkg/chrootarchive.invokeUnpack(0x7ff396028868, 0xc208224120, 0xc2083ce080, 0x65, 0xc208187c80, 0x0, 0x0)
	/go/src/github.com/docker/docker/pkg/chrootarchive/archive_unix.go:81 +0x810
github.com/docker/docker/pkg/chrootarchive.untarHandler(0x7ff396028a60, 0xc20803a5c8, 0xc2083ce080, 0x65, 0xc208187c80, 0x1, 0x0, 0x0)
	/go/src/github.com/docker/docker/pkg/chrootarchive/archive.go:61 +0x411
github.com/docker/docker/pkg/chrootarchive.Untar(0x7ff396028a60, 0xc20803a5c8, 0xc2083ce080, 0x65, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/pkg/chrootarchive/archive.go:21 +0x67
github.com/docker/docker/pkg/archive.(*Archiver).CopyFileWithTar(0x18ad758, 0xc20810af00, 0x50, 0xc2081b3730, 0x66, 0x0, 0x0)
	/go/src/github.com/docker/docker/pkg/archive/archive.go:791 +0x74e
github.com/docker/docker/pkg/archive.(*Archiver).CopyWithTar(0x18ad758, 0xc20810af00, 0x50, 0xc2081b3730, 0x66, 0x0, 0x0)
	/go/src/github.com/docker/docker/pkg/archive/archive.go:719 +0xf7
github.com/docker/docker/pkg/chrootarchive.CopyWithTar(0xc20810af00, 0x50, 0xc2081b3730, 0x66, 0x0, 0x0)
	/go/src/github.com/docker/docker/pkg/chrootarchive/archive.go:75 +0x64
github.com/docker/docker/builder.(*builder).addContext(0xc20806a600, 0xc2081341e0, 0xc2082b8b40, 0x1a, 0xc2083cc344, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/docker/docker/builder/internals.go:776 +0xa0d
github.com/docker/docker/builder.(*builder).runContextCommand(0xc20806a600, 0xc2082b89e0, 0x2, 0x2, 0xb10000c2081d0101, 0x10ac1e0, 0x3, 0x0, 0x0)
	/go/src/github.com/docker/docker/builder/internals.go:249 +0xf73
github.com/docker/docker/builder.add(0xc20806a600, 0xc2082b89e0, 0x2, 0x2, 0x0, 0xc2082b8320, 0x20, 0x0, 0x0)
	/go/src/github.com/docker/docker/builder/dispatchers.go:163 +0x11f
github.com/docker/docker/builder.(*builder).dispatch(0xc20806a600, 0x1, 0xc2081868a0, 0x0, 0x0)
	/go/src/github.com/docker/docker/builder/evaluator.go:347 +0xdae
github.com/docker/docker/builder.(*builder).Run(0xc20806a600, 0x7ff396028810, 0xc2081f72b0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/builder/evaluator.go:182 +0x4b5
github.com/docker/docker/builder.Build(0xc2080a4a80, 0xc20800a2d0, 0x0, 0x0)
	/go/src/github.com/docker/docker/builder/job.go:219 +0x915
github.com/docker/docker/api/server.(*Server).postBuild(0xc20810eb00, 0xc2080ba4d7, 0x4, 0x7ff396028648, 0xc2082160a0, 0xc20807c000, 0xc2081ffc50, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/server.go:1327 +0x1182
github.com/docker/docker/api/server.*Server.(github.com/docker/docker/api/server.postBuild)·fm(0xc2080ba4d7, 0x4, 0x7ff396028648, 0xc2082160a0, 0xc20807c000, 0xc2081ffc50, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/server.go:1657 +0x7b
github.com/docker/docker/api/server.func·008(0x7ff396028648, 0xc2082160a0, 0xc20807c000)
	/go/src/github.com/docker/docker/api/server/server.go:1614 +0xc8f
net/http.HandlerFunc.ServeHTTP(0xc208107300, 0x7ff396028648, 0xc2082160a0, 0xc20807c000)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc20810b680, 0x7ff396028648, 0xc2082160a0, 0xc20807c000)
	/go/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x297
net/http.serverHandler.ServeHTTP(0xc208104660, 0x7ff396028648, 0xc2082160a0, 0xc20807c000)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208193d60)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e

goroutine 37 [select]:
github.com/docker/docker/api/server.func·007()
	/go/src/github.com/docker/docker/api/server/server.go:1318 +0x141
created by github.com/docker/docker/api/server.(*Server).postBuild
	/go/src/github.com/docker/docker/api/server/server.go:1324 +0x115c

goroutine 38 [IO wait]:
net.(*pollDesc).Wait(0xc2081f2530, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2081f2530, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2081f24d0, 0xc208250000, 0x8000, 0x8000, 0x0, 0x7ff39601d340, 0xc2083c9b98)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20803a7d8, 0xc208250000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc2081113e0, 0x7ff396027f08, 0xc20803a7d8, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc2080a6dc0, 0x17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc2080a6dc0, 0xc208248000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:904 +0x166
io.Copy(0x7ff396028a88, 0xc20803a900, 0x7ff396027e68, 0xc2080a6dc0, 0x9230a4b, 0x0, 0x0)
	/usr/local/go/src/io/io.go:362 +0x1f6
net/http.func·008()
	/usr/local/go/src/net/http/server.go:171 +0x7d
created by net/http.(*conn).closeNotify
	/usr/local/go/src/net/http/server.go:177 +0x2e2

goroutine 43 [syscall]:
syscall.Syscall(0x0, 0x11, 0xc2081d6c00, 0x200, 0x0, 0x412ae4, 0xc208105558)
	/usr/local/go/src/syscall/asm_linux_amd64.s:21 +0x5
syscall.read(0x11, 0xc2081d6c00, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:867 +0x6e
syscall.Read(0x11, 0xc2081d6c00, 0x200, 0x200, 0x412997, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:136 +0x58
os.(*File).read(0xc20803b208, 0xc2081d6c00, 0x200, 0x200, 0x70, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:191 +0x5e
os.(*File).Read(0xc20803b208, 0xc2081d6c00, 0x200, 0x200, 0x7ff396012cf0, 0x0, 0x0)
	/usr/local/go/src/os/file.go:95 +0x91
bytes.(*Buffer).ReadFrom(0xc2081b3a40, 0x7ff39601d2f0, 0xc20803b208, 0x0, 0x0, 0x0)
	/usr/local/go/src/bytes/buffer.go:169 +0x25a
io/ioutil.readAll(0x7ff39601d2f0, 0xc20803b208, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/ioutil/ioutil.go:33 +0x1b0
io/ioutil.ReadAll(0x7ff39601d2f0, 0xc20803b208, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/ioutil/ioutil.go:42 +0x68
github.com/docker/docker/pkg/archive.func·007()
	/go/src/github.com/docker/docker/pkg/archive/archive.go:833 +0x63
created by github.com/docker/docker/pkg/archive.CmdStream
	/go/src/github.com/docker/docker/pkg/archive/archive.go:838 +0x47f

goroutine 44 [chan receive]:
github.com/docker/docker/pkg/archive.func·008()
	/go/src/github.com/docker/docker/pkg/archive/archive.go:845 +0x148
created by github.com/docker/docker/pkg/archive.CmdStream
	/go/src/github.com/docker/docker/pkg/archive/archive.go:851 +0x550

goroutine 47 [semacquire]:
sync.(*Cond).Wait(0xc20813e368)
	/usr/local/go/src/sync/cond.go:62 +0x9e
io.(*pipe).write(0xc20813e300, 0xc2083e0000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:94 +0x244
io.(*PipeWriter).Write(0xc20803a618, 0xc2083e0000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:161 +0x5b
archive/tar.(*Writer).Write(0xc208178480, 0xc2083e0000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/archive/tar/writer.go:366 +0xe5
io.Copy(0x7ff39602d240, 0xc208178480, 0x7ff39601d2f0, 0xc20803a730, 0x10000, 0x0, 0x0)
	/usr/local/go/src/io/io.go:364 +0x278
github.com/docker/docker/pkg/archive.func·004(0x0, 0x0)
	/go/src/github.com/docker/docker/pkg/archive/archive.go:781 +0x37c
github.com/docker/docker/pkg/promise.func·001()
	/go/src/github.com/docker/docker/pkg/promise/promise.go:8 +0x2f
created by github.com/docker/docker/pkg/promise.Go
	/go/src/github.com/docker/docker/pkg/promise/promise.go:9 +0xfb

goroutine 48 [syscall]:
syscall.Syscall(0x1, 0x13, 0xc20822c000, 0x8000, 0x7ff396012ef8, 0xc2083e0000, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:21 +0x5
syscall.write(0x13, 0xc20822c000, 0x8000, 0x8000, 0xc20822c000, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:1263 +0x6e
syscall.Write(0x13, 0xc20822c000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:152 +0x58
os.(*File).write(0xc20803a878, 0xc20822c000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:212 +0xb7
os.(*File).Write(0xc20803a878, 0xc20822c000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
	/usr/local/go/src/os/file.go:139 +0x91
io.Copy(0x7ff39601d218, 0xc20803a878, 0x7ff396028868, 0xc208224120, 0x8200, 0x0, 0x0)
	/usr/local/go/src/io/io.go:364 +0x278
os/exec.func·002(0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:179 +0x93
os/exec.func·004(0xc208224160)
	/usr/local/go/src/os/exec/exec.go:328 +0x2d
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:329 +0xb6d

goroutine 49 [syscall]:
syscall.Syscall(0x0, 0x14, 0xc2081d6600, 0x200, 0xf20760, 0xe0000c2083f0120, 0x30)
	/usr/local/go/src/syscall/asm_linux_amd64.s:21 +0x5
syscall.read(0x14, 0xc2081d6600, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:867 +0x6e
syscall.Read(0x14, 0xc2081d6600, 0x200, 0x200, 0xc20821eda0, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:136 +0x58
os.(*File).read(0xc20803a8a8, 0xc2081d6600, 0x200, 0x200, 0xc2081d6600, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:191 +0x5e
os.(*File).Read(0xc20803a8a8, 0xc2081d6600, 0x200, 0x200, 0xc208178480, 0x0, 0x0)
	/usr/local/go/src/os/file.go:95 +0x91
bytes.(*Buffer).ReadFrom(0xc208204540, 0x7ff39601d2f0, 0xc20803a8a8, 0x0, 0x0, 0x0)
	/usr/local/go/src/bytes/buffer.go:169 +0x25a
io.Copy(0x7ff396025578, 0xc208204540, 0x7ff39601d2f0, 0xc20803a8a8, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:358 +0x13d
os/exec.func·003(0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:221 +0x7d
os/exec.func·004(0xc2082241c0)
	/usr/local/go/src/os/exec/exec.go:328 +0x2d
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:329 +0xb6d
drc@ubuntu-gnome:~ 01:30:53 ➸ 

```

Update: I rebuilt docker with go race detector (`go build -race`) it detected this race and some more, I have code fixed this race can make a PR if you can confirm this crash reproducible.

### PR DESCRIPTION
**Pull request by crquan**
This will fix #16924 while may reveal some more race cases, let it rip and will need to fix them all.

Signed-off-by: Derek Ch denc716@gmail.com

### CODE REVIEW

**Comment by duglin** [comment]
ping @vbatts

**Comment by LK4D4** [comment]
@crquan can you squash commits pls?

**Comment by vbatts** [comment]
can you squash

**Comment by vbatts** [comment]
lol @LK4D4 :-)

**Comment by c0b** [comment]
sure

File: pkg/chrootarchive/archive.go [hunk 1]
```diff
@@ -48,16 +46,20 @@ func untarHandler(tarArchive io.Reader, dest string, options *archive.TarOptions
 		}
 	}
 
-	r := ioutil.NopCloser(tarArchive)
+	r := tarArchive
```
Comment (dmcgowan) [inline pkg/chrootarchive/archive.go]: What is the reasoning behind this change? I see you removed one defer close to ensure that `Close` is not called twice on that code path, but there are multiple paths into this function as well as 2 definitions of `untarHandler`. See also https://github.com/c0b/docker/blob/fix-race-16924/pkg/archive/archive.go#L746. If this is not necessary to fix the race condition I would separate this sort of cleanup into a different PR.

Comment (c0b) [inline pkg/chrootarchive/archive.go]: that is to fix the 2nd race I mentioned in [comment](https://github.com/docker/docker/issues/16924#issuecomment-147250089) on io.File, The root cause is
pkg/archive.(*Archiver).UntarPath() has a defer'ed call to archive.Close(), while exec.Cmd has a goroutine do io.Copy at the same time; although that race didn't cause crash problem.

this change to get rid of ioutil.NopCloser is to move responsiblity to untarHandler to determine a later proper time (or in another goroutine) to call that .Close
https://github.com/docker/docker/blob/master/pkg/archive/archive.go#L785
https://github.com/c0b/docker/blob/fix-race-16924/pkg/archive/archive.go#L803-L804

I agree there are more untarHandler needs to be changed, I only changed the one in chrootarchive/archive.go fixed it on Linux.

File: pkg/chrootarchive/archive_windows.go [hunk 2]
```diff
@@ -12,7 +12,7 @@ func chroot(path string) error {
 	return nil
 }
 
-func invokeUnpack(decompressedArchive io.ReadCloser,
+func invokeUnpack(decompressedArchive io.Reader,
```
Comment (c0b) [inline pkg/chrootarchive/archive_windows.go]: could someone tell why do I have to make this change to pass PR jenkins auto build?
the windows is out of my interest and doesn't belong to this PR.

**Comment by c0b** [comment]
I don't understand what is the failure jenkins build? could someone have a look @LK4D4 @vbatts @dmcgowan 
https://jenkins.dockerproject.org/job/Docker-PRs-experimental/9021/console

```
Started by user Jessie Frazelle
Notifying endpoint 'HTTP:https://leeroy.dockerproject.org/notification/jenkins'
[EnvInject] - Loading node environment variables.
ERROR: SEVERE ERROR occurs
org.jenkinsci.lib.envinject.EnvInjectException: hudson.remoting.ChannelClosedException: channel is already closed
	at org.jenkinsci.plugins.envinject.service.EnvironmentVariablesNodeLoader.gatherEnvironmentVariablesNode(EnvironmentVariablesNodeLoader.java:75)
	at org.jenkinsci.plugins.envinject.EnvInjectListener.loadEnvironmentVariablesNode(EnvInjectListener.java:81)
	at org.jenkinsci.plugins.envinject.EnvInjectListener.setUpEnvironment(EnvInjectListener.java:39)
	at hudson.model.AbstractBuild$AbstractBuildExecution.createLauncher(AbstractBuild.java:574)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:494)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
Caused by: hudson.remoting.ChannelClosedException: channel is already closed
	at hudson.remoting.Channel.send(Channel.java:575)
	at hudson.remoting.Request.call(Request.java:130)
	at hudson.remoting.Channel.call(Channel.java:777)
	at hudson.FilePath.act(FilePath.java:1073)
	at 
```

**Comment by icecrime** [comment]
:see_no_evil:

```
---> Making bundle: validate-lint (in bundles/1.9.0-dev/validate-lint)
Errors from golint:
pkg/archive/archive.go:135:9: if block ends with a return statement, so drop this else and outdent its block
```

**Comment by c0b** [comment]
@icecrime I fixed golint, but why "janky — Jenkins build Docker-PRs 17787 failed" ? this error doesn't look like caused by my changes?

```
----------------------------------------------------------------------
FAIL: docker_cli_pull_test.go:69: DockerHubPullSuite.TestPullFromCentralRegistryImplicitRefParts

docker_cli_pull_test.go:83:
    c.Assert(out, checker.Contains, "Image is up to date for hello-world:latest")
... value string = "" +
...     "Using default tag: latest\n" +
...     "latest: Pulling from library/hello-world\n" +
...     "03818fa0f871: Pulling fs layer\n" +
...     "8889088cb38d: Pulling fs layer\n" +
...     "8889088cb38d: Verifying Checksum\n" +
...     "8889088cb38d: Download complete\n" +
...     "03818fa0f871: Verifying Checksum\n" +
...     "03818fa0f871: Download complete\n" +
...     "03818fa0f871: Pull complete\n" +
...     "8889088cb38d: Pull complete\n" +
...     "Digest: sha256:a68868bfe696c00866942e8f5ca39e3e31b79c1e50feaee4ce5e28df2f051d5c\n" +
...     "Status: Downloaded newer image for hello-world:latest\n"
... substring string = "Image is up to date for hello-world:latest"


----------------------------------------------------------------------
PASS: docker_cli_pull_test.go:46: DockerHubPullSuite.TestPullNonExistingImage	3.925s
PASS: docker_cli_pull_test.go:96: DockerHubPullSuite.TestPullScratchNotAllowed	0.037s
OOPS: 961 passed, 13 skipped, 1 FAILED
--- FAIL: Test (1673.66s)
```

File: pkg/chrootarchive/archive_windows.go (hunk 2 above)
Comment (tiborvass) [inline pkg/chrootarchive/archive_windows.go]: because https://github.com/docker/docker/pull/16932/files#diff-7d8fc0dcb0916621d523276add8210c2R63 you call it with `r` which is now an `io.Reader` not an `io.ReadCloser` (since you removed the nopcloser wrapper). And we build binaries for all platforms, not just linux.

**Comment by thaJeztah** [comment]
@icecrime @vbatts @LK4D4 Looks like this is all green now (experimental is cleaning up), PTAL

File: pkg/chrootarchive/archive.go (hunk 1 above)
Comment (dmcgowan) [inline pkg/chrootarchive/archive.go]: Did you remove the other section that commented out the defer close from the caller?

I really am not a fan of this approach of testing for `io.Closer` and closing if it is. The `http` package does this and it causes havoc trying to figure out why things are getting closed at inopportune times. I agree with fixing the race but it doesn't seem related to your crash nor the correct fix for it.

File: pkg/chrootarchive/archive_windows.go (hunk 2 above)
Comment (c0b) [inline pkg/chrootarchive/archive_windows.go]: ok, that explains~ ; while all other invokeUnpack func are with io.Reader and pass to archive.Unpack only need it to be an io.Reader, even r could be io.ReadCloser that can still work.

I think you can change this line in a separate commit and won't break anything even before merge this.

File: pkg/chrootarchive/archive.go (hunk 1 above)
Comment (c0b) [inline pkg/chrootarchive/archive.go]: Yes, but the comments are still there in [previous commit](https://github.com/c0b/docker/commit/6aa28ae99cc94771bf09dd79d2d4c99c49fcc6c1#diff-45e15b27a574e8c07552aad3688b3142) but I removed comments and the defer statement; do you prefer to keep it in source code?

While, squash everything together doesn't look better; this whole changeset actually fixed two different race described in issue #16924 comment-1 and comment-2; My initial commits kept fixing it separately and look better
1) Change CmdStream to assign cmd.Stdin Stdout Stderr instead of do io.Copy in goroutines, because that's exactly the "os/exec" does; this commit only does simplifying;
2) fixed race-1 in 4223cd9 that's the race caused daemon crash, it's on bufio between defer decompressedArchive.Close() which calls pools.Put(buf) and CmdStream goroutine which is still doing io.Copy
the fix is done by returning a Done() receive only channel (inspired by golang.org/x/net/context) and let the Close code wait on that;
3) fix race-2 in io.File, between pkg/archive.(*Archiver).UntarPath() which has a defer'ed call to archive.Close(), while exec.Cmd has a goroutine doing io.Copy at the same time ;
4) later on I realized that Done() interface is not necessary, removed it and just implement Read / Close on the wrapper type.

I can fixup 4 merge into 2, and make 3 commits will be clear;

Comment (c0b) [inline pkg/chrootarchive/archive.go]: > The http package does this and it causes havoc trying to figure out why things are getting closed at inopportune times.

I am not sure what's that about, if you have some reference; maybe that's something big needs golang.org team to fix?

File: pkg/archive/archive.go [hunk 3]
```diff
@@ -148,12 +170,12 @@ func DecompressStream(archive io.Reader) (io.ReadCloser, error) {
...
 		return readBufWrapper, nil
 	case Xz:
-		xzReader, err := xzDecompress(buf)
+		xzReader, chdone, err := xzDecompress(buf)
 		if err != nil {
 			return nil, err
 		}
 		readBufWrapper := p.NewReadCloserWrapper(buf, xzReader)
-		return readBufWrapper, nil
+		return &wrapper{readBufWrapper, chdone}, nil
```
Comment (cpuguy83) [inline pkg/archive/archive.go]: why not use `ioutils.ReadCloserWrapper` instead of creaping a wrapper type?

File: pkg/archive/archive.go [hunk 4]
```diff
@@ -116,7 +116,29 @@ func DetectCompression(source []byte) Compression {
...
+type wrapper struct {
+	r      io.ReadCloser
+	chdone <-chan struct{}
+}
+
+func (w *wrapper) Read(p []byte) (n int, err error) {
+	return w.r.Read(p)
+}
+
+func (w *wrapper) Close() error {
```
Comment (cpuguy83) [inline pkg/archive/archive.go]: This close function is a little weird, and seems like it would cause problems on multiple calls to close.
From what I can tell in the other code, you are intending to make sure stdin is done before the reader is closed, but return immediately?

File: pkg/archive/archive.go [hunk 5]
```diff
@@ -928,54 +950,35 @@ func CopyFileWithTar(src, dst string) (err error) {
...
-	}
-	stdout, err := cmd.StdoutPipe()
-	if err != nil {
-		return nil, err
-	}
-	stderr, err := cmd.StderrPipe()
-	if err != nil {
-		return nil, err
+		cmd.Stdin = input
+		chdone = make(chan struct{})
```
Comment (cpuguy83) [inline pkg/archive/archive.go]: Why only make this chan when we have input?
This can save us a bunch of nil checks to just always create it

File: pkg/archive/archive.go [hunk 6]
```diff
@@ -928,54 +950,35 @@ func CopyFileWithTar(src, dst string) (err error) {
...
-		}
-		errText := <-errChan
 		if err := cmd.Wait(); err != nil {
-			pipeW.CloseWithError(fmt.Errorf("%s: %s", err, errText))
+			pipeW.CloseWithError(fmt.Errorf("%s: %s", err, errBuf.String()))
 		} else {
 			pipeW.Close()
 		}
+		if chdone != nil {
+			chdone <- struct{}{}
```
Comment (cpuguy83) [inline pkg/archive/archive.go]: This should close the channel so that reads from the channel (as in your close function above) does not block on a 2nd call.

File: pkg/archive/archive.go (hunk 3 above)
Comment (c0b) [inline pkg/archive/archive.go]: ok, I didn't know that, will make the change right away.

File: pkg/archive/archive.go (hunk 6 above)
Comment (c0b) [inline pkg/archive/archive.go]: ok, sure; but reading more on golang.org/x/net/context I also realized to close that channel is required, if Close to be called multiple times.
http://blog.golang.org/pipelines

**Comment by c0b** [comment]
in this issue #16924 the pipe flow on building `ADD the-tarball.tar.xz ..." is like

```
docker-daemon cat the-tarball.xz | xz -d -c -q | docker-untar /path/to/... (aufs )
```

when the tar file contains some xattr file, docker-untar extract to aufs will fail and broke the pipe, there are two races here:

1. docker-untar write pipe Closed if docker-untar fail, it is using a bufio from pools, that bufio is returned too early, while the goroutine in exec.Cmd is still doing io.Copy
2. pkg/archive.(*Archiver).UntarPath() has a defer'ed call to archive.Close(), while exec.Cmd (of "xz -d -c -q") has a goroutine do io.Copy at the same time.

**Comment by LK4D4** [comment]
If I understand correctly this PR fixes two races?

**Comment by LK4D4** [comment]
I think root cause is that all `CmdStream` stuff is extremely weird and we probably trying to make it even more weird.

**Comment by c0b** [comment]
> If I understand correctly this PR fixes two races?

yes

> I think root cause is that all CmdStream stuff is extremely weird and we probably trying to make it even more weird.

yes on the root cause, but I am trying to make it cleaner, look at original CmdStream has 3 goroutines inside, I am reducing it to one goroutine, not sure if there are ways to clean further
https://github.com/c0b/docker/blob/fix-race-16924/pkg/archive/archive.go#L935-L964

**Comment by LK4D4** [comment]
@c0b Yeah, your implementation is like x1000 times better.

File: pkg/archive/archive.go [hunk 7]
```diff
@@ -928,54 +935,31 @@ func CopyFileWithTar(src, dst string) (err error) {
...
-	}
-	stdout, err := cmd.StdoutPipe()
-	if err != nil {
-		return nil, err
-	}
-	stderr, err := cmd.StderrPipe()
-	if err != nil {
-		return nil, err
-	}
+func CmdStream(cmd *exec.Cmd, input io.Reader) (io.ReadCloser, <-chan struct{}, error) {
```
Comment (LK4D4) [inline pkg/archive/archive.go]: Ok, at last I got why I felt so strange. let's make this func private, it used only once in this package.

File: pkg/archive/archive.go [hunk 8]
```diff
@@ -928,54 +935,31 @@ func CopyFileWithTar(src, dst string) (err error) {
...
-			pipeW.CloseWithError(err)
-		}
-		errText := <-errChan
 		if err := cmd.Wait(); err != nil {
-			pipeW.CloseWithError(fmt.Errorf("%s: %s", err, errText))
+			pipeW.CloseWithError(fmt.Errorf("%s: %s", err, errBuf.String()))
 		} else {
 			pipeW.Close()
 		}
+		chdone <- struct{}{}
```
Comment (LK4D4) [inline pkg/archive/archive.go]: I thought `close` should be enough to notify.

File: pkg/chrootarchive/archive.go (hunk 1 above)
Comment (LK4D4) [inline pkg/chrootarchive/archive.go]: @c0b let's split this change to separate PR, so we can just merge your `CmdStream` fix.

File: pkg/archive/archive.go (hunk 7 above)
Comment (c0b) [inline pkg/archive/archive.go]: yes, I searched it the whole docker source tree wide, it's not called anywhere else.
I changed it to lower case.

File: pkg/archive/archive.go (hunk 8 above)
Comment (c0b) [inline pkg/archive/archive.go]: removed.

File: pkg/archive/archive.go [hunk 9]
```diff
@@ -925,57 +932,33 @@ func CopyFileWithTar(src, dst string) (err error) {
...
 	// Copy stdout to the returned pipe
 	go func() {
-		_, err := io.Copy(pipeW, stdout)
-		if err != nil {
-			pipeW.CloseWithError(err)
-		}
-		errText := <-errChan
 		if err := cmd.Wait(); err != nil {
-			pipeW.CloseWithError(fmt.Errorf("%s: %s", err, errText))
+			pipeW.CloseWithError(fmt.Errorf("%s: %s", err, errBuf.String()))
```
Comment (LK4D4) [inline pkg/archive/archive.go]: `%s` will call `String()` for you, but you can leave it if you want. Just for info.

Comment (c0b) [inline pkg/archive/archive.go]: it's because there was an Jenkins build failed check for that, something says %s doesn't match errBuf type...

Comment (LK4D4) [inline pkg/archive/archive.go]: Cool then.

**Comment by LK4D4** [comment]
@c0b let's split race from `untarHandler` to other PR and discuss there. I think `cmdStream` part is good to go.

**Comment by LK4D4** [comment]
LGTM if CI will pass

File: pkg/archive/archive.go [hunk 10]
```diff
@@ -148,12 +149,18 @@ func DecompressStream(archive io.Reader) (io.ReadCloser, error) {
...
 	case Xz:
-		xzReader, err := xzDecompress(buf)
+		xzReader, chdone, err := xzDecompress(buf)
 		if err != nil {
 			return nil, err
 		}
 		readBufWrapper := p.NewReadCloserWrapper(buf, xzReader)
-		return readBufWrapper, nil
+		return ioutils.NewReadCloserWrapper(readBufWrapper, func() error {
+			go func() {
```
Comment (cpuguy83) [inline pkg/archive/archive.go]: Can you explain why this needs to be in a goroutine?
How come we don't want the `Close` caller to wait?

Comment (c0b) [inline pkg/archive/archive.go]: I think above comments already has the root cause clear already:

1. docker-untar write pipe will be closed if docker-untar fail, it is using a bufio from pools, and pools.Put(bufio) be called in p.ReadCloserWrapper too early, while the goroutine in exec.Cmd is still doing io.Copy

because chrootarchive/archive.untarHandler has a `defer decompressedArchive.Close()` that is to be called when untarHandler returns, that Close will call pools.Put(buf) which calls buf.Reset(nil) resets that bufio's internal pointers; while exec.Cmd still has the goroutine doing io.Copy, that is going to crash on L86 of bufio.fill
https://github.com/docker/docker/blob/master/pkg/chrootarchive/archive.go#L52-L59
https://golang.org/src/bufio/bufio.go#L83-89

the solution is to wait cmd.Wait finish, that's the point exec.Cmd internal goroutines has all finished.

Comment (cpuguy83) [inline pkg/archive/archive.go]: But if we are blocking on `<-chdone` w/o a goroutine, this should suffice?
So:
```go
ioutils.NewReadCloserWrapper(readBufWrapper, func() error {
    <-chdone
    readBufWrapper.Close()
})
```

Comment (c0b) [inline pkg/archive/archive.go]: ok, that was necessary when I was doing send a `struct{}` on the channel, but might be not necessary after changed to close() channel, I am doing some local test

Comment (c0b) [inline pkg/archive/archive.go]: I am trying to change it like this, but it ends up a deadlock,

```go
                return ioutils.NewReadCloserWrapper(readBufWrapper, func() error {                                                                            
                        <-chdone                                                                                                                              
                        return readBufWrapper.Close()                                                                                                         
                }), nil
```

race can be detected by `go build -race` but how to debug a deadlock?

Comment (cpuguy83) [inline pkg/archive/archive.go]: Where are you seeing the deadlock? Running the archive tests seems to be ok.

**Comment by c0b** [comment]
I'm not sure what's this failed test case? in the `userns — Jenkins build Docker-PRs-userns 241 has failed` doesn't seem to be related here

```
----------------------------------------------------------------------
FAIL: docker_cli_logs_test.go:226: DockerSuite.TestLogsSinceFutureFollow

docker_cli_logs_test.go:244:
    c.Fatalf("earlier log found. since=%v logdate=%v", since, ts)
... Error: earlier log found. since=1444767586 logdate=1444767585
```

File: pkg/archive/archive.go (hunk 10 above)
Comment (c0b) [inline pkg/archive/archive.go]: first, have you reproduced the issue #16924 the `[panic: runtime error: slice bounds out of range]` crash? if docker-untar something failed, that crash is supposed to happen;

in this fix, I do wait channel and Close in a separate goroutine, that fixed the crash; but if it's not in a separate goroutine, code like this ends up deadlock, docker build on `ADD broken.tar.xz .." never returns

```go
return ioutils.NewReadCloserWrapper(readBufWrapper, func() error {
    <-chdone
    return readBufWrapper.Close()
}), nil
```

**Comment by cpuguy83** [comment]
Indeed, that test can be a little flakey.

File: pkg/archive/archive.go (hunk 10 above)
Comment (cpuguy83) [inline pkg/archive/archive.go]: I don't see why it wouldn't return, however if it's not returning, then it is likely the goroutine version isn't returning either.

Comment (c0b) [inline pkg/archive/archive.go]: right, I'm adding more logrus.Debuf locally and need to figure out why

Comment (c0b) [inline pkg/archive/archive.go]: you're right; the reason for deadlock is xz pending on writing the pipe; the separate goroutine waiting on channel to close didn't actually fix, it moved the logic to a goroutine to waiting on xz,

```
docker-daemon cat the-tarball.xz | xz -d -c -q | docker-untar /path/to/... (aufs )
````

while now I have another fix, the debug log shows it passed `readBufWrapper.Close()`, will cleanup and push the fix again

```
WARN[0017] chdone (chan struct {})(0xc8204cfb60) closed    <= after cmd.Wait and close the channel
DEBU[0017] Couldn't untar to /home/lib-docker-v1.9.0-tmp/0.0/aufs/mnt/4e2714008091e46c345efb67a1948b66b498cd8adea8734afd6dc331d3dfd44a: Untar re-exec error: exit status 1: output: operation not supported 
DEBU[0017] CopyFileWithTar(/home/lib-docker-v1.9.0-tmp/0.0/tmp/docker-builder357741497/stage3-x32-20151004.tar.xz, /home/lib-docker-v1.9.0-tmp/0.0/aufs/mnt/4e2714008091e46c345efb67a1948b66b498cd8adea8734afd6dc331d3dfd44a/stage3-x32-20151004.tar.xz) 
WARN[0017] waiting channel (<-chan struct {})(0xc8204cfb60) then to close &ioutils.readCloserWrapper{Reader:(*io.PipeReader)(0xc820032838), closer:(func() error)(0x976a30)} 
WARN[0017] readBufWrapper (<-chan struct {})(0xc8204cfb60) closed now.
```

File: pkg/chrootarchive/archive_unix.go [hunk 11]
```diff
@@ -79,6 +80,11 @@ func invokeUnpack(decompressedArchive io.Reader, dest string, options *archive.T
 	w.Close()
 
 	if err := cmd.Wait(); err != nil {
+		// when `xz -d -c -q | docker-untar ...` failed on docker-untar side,
+		// we need to exhaust `xz`'s output, otherwise the `xz` side will be
+		// pending on write pipe forever
+		io.Copy(ioutil.Discard, decompressedArchive)
```
Comment (c0b) [inline pkg/chrootarchive/archive_unix.go]: @cpuguy83 here it is, reexec of "docker-untar ..." failure has to exhaust all input, otherwise the underlying xz pending forever

Comment (cpuguy83) [inline pkg/chrootarchive/archive_unix.go]: seems legit.

Comment (cpuguy83) [inline pkg/chrootarchive/archive_unix.go]: I can't make xz hang here (manually), but maybe it's happening due to the reexec?

Comment (cpuguy83) [inline pkg/chrootarchive/archive_unix.go]: yeah, sadly can't repro the xz hang even with reexec.

Comment (c0b) [inline pkg/chrootarchive/archive_unix.go]: first thing, are you able to reproduce issue #16924 crash ?

then, apply the changes here, but without this line of draining decompressedArchive, then docker daemon is hanging on xz, in pstree it shows xz as a child process of docker daemon, is sleeping state, if `strace -p <xz-pid>`, then you see xz is pending on `write(1, "....", 8192)` , that fd 1 is pipe fd connect to docker daemon (and connect to reexec docker-untar)

Comment (c0b) [inline pkg/chrootarchive/archive_unix.go]: better to use the same file `stage3-x32-20151004.tar.xz` as I am testing, is large enough, and will fail extracting xattr if running on aufs
http://mirrors.kernel.org/gentoo/releases/amd64/autobuilds/current-stage3-x32/

Comment (cpuguy83) [inline pkg/chrootarchive/archive_unix.go]: I'm trying to repro with this: https://gist.github.com/cpuguy83/eeb006f9cbc3b80567d7

Where I'm calling `xz -d -c -q foo.tar.xz | crash.go`

Comment (cpuguy83) [inline pkg/chrootarchive/archive_unix.go]: Oh wait, I've got it...

Comment (cpuguy83) [inline pkg/chrootarchive/archive_unix.go]: Ok gist updated, that reproduces, and draining the stream fixes the issue.

**Comment by cpuguy83** [comment]
LGTM

**Comment by vbatts** [comment]
LGTM
