### PR TITLE
copy: avoid using all system memory with authz plugins

### LINKED ISSUE #36576: Memory leak with authorization plugins
**Description**

**Steps to reproduce the issue:**
1. enable any authorization plugin
2. docker cp container:/ /local/root
3. watch the OOM (which causes docker to restart)

- craete a vm with 2G RAM and no swap

use this reproducer:

```
#!/bin/bash
set -xeuo pipefail

docker run --detach --name cnt docker.io/openshift/origin:v3.7.1 sleep infinity || true
for i in $(seq 10); do
  docker cp cnt:/ /tmp/oc-usr
done
```

**Describe the results you received:**

OOM panic

```
github.com/docker/docker/pkg/authorization.(*responseModifier).Write(0xc4229c9000, 0xc422248000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
/builddir/build/BUILD/docker-774336db27bb8931c1705e47781b3842d290c968/_build/src/github.com/docker/docker/pkg/authorization/response.go:124 +0x125 fp=0xc4202c73f0 sp=0xc4202c7388
```

**Describe the results you expected:**

no OOM

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
latest
```

**Output of `docker info`:**

```
latest
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

if you disable the authorization plugin, no oom happening

@cpuguy83

### PR DESCRIPTION
**Pull request by runcom**
Authz plugins proxy the whole response to be later inspected by the
plugin in a byte slice (using append). The code uses io.Copy() directly
causing the whole response to be buffered in the byte slice in the
`responseModifier` of the authz sdk.
I noticed `docker save` doesn't have the same issue even streaming huge
tarballs by using ioutils.WriteFlusher.
This patch changes the copy code to:

- Use ioutils.WriteFlusher
- Use pools.Copy

We cannot reproduce the OOM anymore with this.

@cpuguy83 PTAL

Fix https://github.com/moby/moby/issues/36576

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by cpuguy83** [comment]
Wow, thanks for looking at this.

So is the issue that the write buffer filling up?
`io.Copy` should only have a 32K buffer as is.

Can you think of some way to unit test this?

**Comment by tonistiigi** [comment]
SGTM

**Comment by runcom** [comment]
> Can you think of some way to unit test this?

I've spent yesterday to think of something but couldn't come up with anything lol, do you have ideas?

**Comment by runcom** [comment]
are test failures related? looks like they're not

**Comment by ripcurld** [comment]
It looks like unrelated. `janky` was aborted (probably timeout) and others failed in different tests.
Let's try again. :smiley:

**Comment by cpuguy83** [comment]
@runcom What about something like this: https://play.golang.org/p/G1BWKP9Xvut

**Comment by ripcurld** [comment]
@runcom it seems like this change makes `TestExternalVolumeDriverUnmountOnCp` fail.

```
15:01:07 FAIL: docker_cli_external_volume_driver_unix_test.go:621: DockerExternalVolumeSuite.TestExternalVolumeDriverUnmountOnCp
15:01:07 
15:01:07 [d868eebd8df13] waiting for daemon to start
15:01:07 [d868eebd8df13] daemon started
15:01:07 
15:01:07 docker_cli_external_volume_driver_unix_test.go:630:
15:01:07     c.Assert(s.ec.unmounts, checker.Equals, 1, check.Commentf(out))
15:01:07 ... obtained int = 0
15:01:07 ... expected int = 1
15:01:07 ... 
15:01:07 
15:01:07 [d868eebd8df13] exiting daemon
```

**Comment by kolyshkin** [comment]
CI failure on **experimental** ([logs](https://jenkins.dockerproject.org/job/Docker-PRs-experimental/39822/console)) is unrelated; see https://github.com/moby/moby/issues/36547

CI failure on **powerpc** ([logs](https://jenkins.dockerproject.org/job/Docker-PRs-powerpc/8998/console)) is interesting:

10:17:16 === RUN   TestMountDaemonRoot/private/mount_root
10:17:16 === RUN   TestMountDaemonRoot/private/mount_subpath
10:17:19 panic: Error response from daemon: removal of container 9588fac23c7077479cff76aa7e1785687c2829aacf5067b861ccc7d609bfeaf0 is already in progress [recovered]
10:17:19 	panic: Error response from daemon: removal of container 9588fac23c7077479cff76aa7e1785687c2829aacf5067b861ccc7d609bfeaf0 is already in progress
10:17:19 
10:17:19 goroutine 655 [running]:
10:17:19 testing.tRunner.func1(0xc420509c20)
10:17:19 	/usr/local/go/src/testing/testing.go:711 +0x290
10:17:19 panic(0x103e8b00, 0xc4204f8eb0)
10:17:19 	/usr/local/go/src/runtime/panic.go:491 +0x244
10:17:19 github.com/docker/docker/integration/container.TestMountDaemonRoot.func1.1.1(0x106f4380, 0xc42011ba00, 0x106e9580, 0xc42001a078, 0xc4200147c0, 0x40, 0x0, 0x0, 0x0)
10:17:19 	/go/src/github.com/docker/docker/integration/container/mounts_linux_test.go:261 +0xc4
10:17:19 github.com/docker/docker/integration/container.TestMountDaemonRoot.func1.1(0xc420509c20)
10:17:19 	/go/src/github.com/docker/docker/integration/container/mounts_linux_test.go:277 +0x558
10:17:19 testing.tRunner(0xc420509c20, 0xc4201a3f20)
10:17:19 	/usr/local/go/src/testing/testing.go:746 +0xc0
10:17:19 created by testing.(*T).Run
10:17:19 	/usr/local/go/src/testing/testing.go:789 +0x264

The other two failures (on **janky** and **z**) look like being genuine:

11:49:44 
11:49:44 ----------------------------------------------------------------------
11:49:44 FAIL: docker_cli_external_volume_driver_unix_test.go:621: DockerExternalVolumeSuite.TestExternalVolumeDriverUnmountOnCp
11:49:44 
11:49:44 [ddf1a70450757] waiting for daemon to start
11:49:44 [ddf1a70450757] daemon started
11:49:44 
11:49:44 docker_cli_external_volume_driver_unix_test.go:630:
11:49:44     c.Assert(s.ec.unmounts, checker.Equals, 1, check.Commentf(out))
11:49:44 ... obtained int = 0
11:49:44 ... expected int = 1
11:49:44 ... 
11:49:44 
11:49:44 [ddf1a70450757] exiting daemon

**Comment by kolyshkin** [comment]
Oh the powerpc panic on test seems to be deliberate (see commit 589a0afa8c from PR #36055). @cpuguy83 care to take a look (logs are here: https://jenkins.dockerproject.org/job/Docker-PRs-powerpc/8998/console)?

**Comment by cpuguy83** [comment]
Not sure why I put a panic in there... should just fail the test or something. Also really weird error since we only call remove once.

**Comment by cpuguy83** [comment]
Should we set a max buffer size in the authz buffer?

**Comment by runcom** [comment]
> Should we set a max buffer size in the authz buffer?

yeah, not sure what amount though, hint?

**Comment by cpuguy83** [comment]
How about 1MB?

File: api/server/router/container/copy.go [hunk 1]
```diff
@@ -103,7 +105,9 @@ func writeCompressedResponse(w http.ResponseWriter, r *http.Request, body io.Rea
 	default:
 		cw = w
 	}
-	_, err := io.Copy(cw, body)
+	output := ioutils.NewWriteFlusher(cw)
```
Comment (cpuguy83) [inline api/server/router/container/copy.go]: This doesn't work. The compressed writer is not a flusher.

Comment (runcom) [reply api/server/router/container/copy.go]: :confused:

Comment (cpuguy83) [reply api/server/router/container/copy.go]: I pushed an update that fixes this, adds a test, and a max buffer for authz responses.

**Comment by cpuguy83** [comment]
And the 1MB buffer limit highlighted that `docker export` was also affected (authz integration tests caught it).

Unfortunately triggering the error can be quite difficult without making the buffer smaller. The integration test I added for container copy to/from can't trigger it without making a huge file (10GB worked, 500MB did not, both are really too big to do in CI), but at least it makes sure copy works with authz, and then the separate unit test on the container copy stream writer to make sure there isn't any internal buffering.

**Comment by cpuguy83** [comment]
But now export container, export image, and container copy all seem to be setup correctly.

**Comment by cpuguy83** [comment]
Ouch, before this PR:

> PASS: docker_cli_external_volume_driver_unix_test.go:621: DockerExternalVolumeSuite.TestExternalVolumeDriverUnmountOnCp	1.434s

After this PR:

> PASS: docker_cli_external_volume_driver_unix_test.go:709: DockerExternalVolumeSuite.TestExternalVolumeDriverUnmountOnCp	31.727s

**Comment by cpuguy83** [comment]
Ok, I've updated this (again, sorry...) with a more complete fix.
Now when the authz buffer limit is reached (currently set to a 64K limit) the buffer is flushed.

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Comment by runcom** [comment]
:+1:

**Comment by tonistiigi** [comment]
LGTM
