### PR TITLE
cleanup/fix integration-cli for overlay in overlay

### LINKED ISSUE #11966: racy tests TestRunContainerWithRmFlagExitCodeNotEqualToZero TestRunContainerWithRmFlagCannotStartContainer
```
--- FAIL: TestRunContainerWithRmFlagExitCodeNotEqualToZero (0.65s)
	docker_cli_run_test.go:3414: Expected not to have containers b236c1619dcc
		
--- FAIL: TestRunContainerWithRmFlagCannotStartContainer (0.51s)
	docker_cli_run_test.go:3435: Expected not to have containers b236c1619dcc
```
on overlay specifically 
see https://jenkins.dockerproject.com/job/Docker%20Master%20(overlay%20on%20overlay)/132/console

### PR DESCRIPTION
**Pull request by jessfraz**
closes #11966

### CODE REVIEW

**Comment by jfrazelle** [comment]
changed https://jenkins.dockerproject.com/job/Docker%20Master%20(overlay%20on%20overlay)/290/console to build from my branch as proof

**Comment by jfrazelle** [comment]
dammit, worked on my machine, there is a more annoying problem from these "Dead" containers

**Comment by jfrazelle** [comment]
back to the drawing board

**Comment by jfrazelle** [comment]
oooo i know

File: integration-cli/docker_cli_cp_test.go [hunk 1]
```diff
@@ -466,13 +466,13 @@ func TestCpVolumePath(t *testing.T) {
...
 
-	out, exitCode, err := dockerCmd(t, "run", "-d", "-v", "/foo", "-v", tmpDir+"/test:/test", "-v", tmpDir+":/baz", "busybox", "/bin/sh", "-c", "touch /foo/bar")
+	out, exitCode, err := dockerCmd(t, "run", "-d", "-v", "/foo", "-v", tmpDir+"/test:/test", "-v", tmpDir+":/baz", "busybox", "sh", "-c", "touch /foo/bar")
 	if err != nil || exitCode != 0 {
 		t.Fatal("failed to create a container", out, err)
 	}
 
 	cleanedContainerID := strings.TrimSpace(out)
-	defer deleteContainer(cleanedContainerID)
+	defer dockerCmd(t, "rm", "-f", cleanedContainerID)
```
Comment (jfrazelle) [inline integration-cli/docker_cli_cp_test.go]: this is the test that was creating the "Dead" container, and this is the fix

**Comment by jfrazelle** [comment]
https://jenkins.dockerproject.com/job/Docker%20Master%20(overlay%20on%20overlay)/292/console

File: integration-cli/docker_cli_cp_test.go [hunk 2]
```diff
@@ -472,7 +472,7 @@ func TestCpVolumePath(t *testing.T) {
 	}
 
 	cleanedContainerID := strings.TrimSpace(out)
-	defer deleteContainer(cleanedContainerID)
+	defer dockerCmd(t, "rm", "-fv", cleanedContainerID)
```
Comment (jfrazelle) [inline integration-cli/docker_cli_cp_test.go]: this is the test that was creating the "Dead" container, and this is the fix

**Comment by jfrazelle** [comment]
https://jenkins.dockerproject.com/job/Docker%20Master%20(overlay%20on%20overlay)/293/console

File: integration-cli/docker_cli_cp_test.go (hunk 2 above)
Comment (jfrazelle) [inline integration-cli/docker_cli_cp_test.go]: its gotta be something with creating the volume via vfs in overlay in overlay that makes the container need a SIGTERM and SIGKILL

Comment (cpuguy83) [inline integration-cli/docker_cli_cp_test.go]: but `-f` is always doing a sigkill, and isn't `deleteContainer` doing this exact thing?

Comment (jfrazelle) [inline integration-cli/docker_cli_cp_test.go]: it is the super intricate difference of doing a SIGTERM, then SIGKILL that is different and somehow saves the day

Comment (cpuguy83) [inline integration-cli/docker_cli_cp_test.go]: oh, I know why!
Dead containers happen when `rm` failed, but when you `rm -f` them again it forcibly removes them from docker regardless if there is an issue.

So first time with `rm -f` it had an issue, is marked as dead.  If you just `rm` (no `-f`) it won't remove if the issue isn't resolved. But when you `rm -f` again, it will remove from docker regardless of issues.

Comment (jfrazelle) [inline integration-cli/docker_cli_cp_test.go]: -f calls `container.Stop(3)` which does the TERM & KILL after 3 seconds, deleteContainer does just a SIGKILL

Comment (cpuguy83) [inline integration-cli/docker_cli_cp_test.go]: Yes, but what it is causing the 2nd one to work isn't the TERM vs KILL, it's that `-f` has tells Docker to actually remove a container that is in a `dead` state no matter what.

Comment (jfrazelle) [inline integration-cli/docker_cli_cp_test.go]: oh damn you were better than me, and i went into the depths of the sigs :(

Comment (jfrazelle) [inline integration-cli/docker_cli_cp_test.go]: but i am only calling `rm -f` once not twice

Comment (jfrazelle) [inline integration-cli/docker_cli_cp_test.go]: deleteContainers does just a kill and rm

File: integration-cli/docker_cli_run_test.go [hunk 3]
```diff
@@ -3449,7 +3450,8 @@ func TestRunContainerWithRmFlagExitCodeNotEqualToZero(t *testing.T) {
 func TestRunContainerWithRmFlagCannotStartContainer(t *testing.T) {
 	defer deleteAllContainers()
 
-	runCmd := exec.Command(dockerBinary, "run", "--rm", "busybox", "commandNotFound")
+	name := "sparkles"
```
Comment (LK4D4) [inline integration-cli/docker_cli_run_test.go]: Sunshine! Sparkle!

**Comment by LK4D4** [comment]
LGTM

File: integration-cli/docker_cli_run_test.go (hunk 3 above)
Comment (jfrazelle) [inline integration-cli/docker_cli_run_test.go]: :sunglasses: ya kinda left over from debuigging but i like

**Comment by cpuguy83** [comment]
LGTM
