### PR TITLE
Fixing issue of docker top command failure when dealing with -m option

### LINKED ISSUE #30580: docker top breaks when showing thread information after processes
**Description**

Attempting to show threads after process in `top` command (`m` flag) returns 

`Error response from daemon: Unexpected pid '-': strconv.ParseInt: parsing "-": invalid syntax` 

**Steps to reproduce the issue:**
1. Pull any image
2. Run a new container
3. Run `docker top <container-id> m`

**Describe the results you received:**

`Error response from daemon: Unexpected pid '-': strconv.ParseInt: parsing "-": invalid syntax` 

**Describe the results you expected:**

ps information such as:

```
PID TTY      STAT   TIME COMMAND
  173 ?        -      0:00 /bin/bash
    - -        Ss     0:00 -
  190 ?        -      0:00 ps m
    - -        R+     0:00 -
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Combining `m` flag with any other causes the problem (such as `ps muax`)

This error seems related to ps output parsing function implemented in https://github.com/docker/docker/blob/master/daemon/top_unix.go

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 23
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-59-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.659 GiB
Name: rsilva-note
ID: G3OH:BUGW:Z6RR:6BVO:YSAV:QYEE:6VVL:FJQ4:Q7LW:OXIJ:LUHT:Q2VJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ubuntu 16.10

### PR DESCRIPTION
**Pull request by catinthesky**
Signed-off-by: catinthesky <yaozaiyong@hotmail.com>

**- What I did**
Ignore the "ps m" command's "thread line" that has "-" character as pid which can not be converted into a int. 
**- How I did it**
When detecting pid column is "-", ignore this line and continue forward.
**- How to verify it**
Using command:  "docker top <contianer-id> m" to check if the problem of  "Unexpected pid '-': strconv.ParseInt: parsing "-": invalid synta"   disappeared
**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

Fix #30580

### CODE REVIEW

**Review by LK4D4 — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
While this fixes the error, Looking at the linked issue, the users intent is to show these threads in the output. If these lines are always shown _after_ a line containing the actual PID, should we do something like this instead? (code may have to be cleaned up a bit, it's just a quick write-up);


```go
var (
	p int
	err error
)

for _, line := range lines[1:] {
	if len(line) == 0 {
		p = 0
		continue
	}
	fields := fieldsASCII(line)
	//Fix bug https://github.com/docker/docker/issues/30580
	if fields[pidIndex] == "-" {
		if p == 0 {
			continue
		}
		// this line shows threads for the PID on the previous line
		p = curPID
	} else {
		p, err := strconv.Atoi(fields[pidIndex])
		if err != nil {
			return nil, fmt.Errorf("Unexpected pid '%s': %s", fields[pidIndex], err)
		}
	}

	for _, pid := range pids {
		if pid == p {
			// Make sure number of fields equals number of header titles
			// merging "overhanging" fields
			process := fields[:len(procList.Titles)-1]
			process = append(process, strings.Join(fields[len(procList.Titles)-1:], " "))
			procList.Processes = append(procList.Processes, process)
		}
	}
}
```

@LK4D4 wdyt?

**Review by cpuguy83 — CHANGES_REQUESTED** [review]
Please make sure to use a descriptive commit message/title

**Comment by catinthesky** [comment]
Thanks all for your feedback.
@thaJeztah, I think what you mean is, to show both the container contained process and its sponsored threads information, I tweaked a little following your quick write-up to this end, and pushed code to github. The change now can work with 'm' option.  However, as for the "L" option (which is an exclusive option), whose output doesn't contain PID column, it can not work, for this I'm afraid have to adopt the second strategy as suggested(in #30580):

eg: the output for "m" option now:
_root@7dced85bcbdf:/go/src/github.com/docker/docker# docker top 6a4df69c257a am
PID                 TTY                 STAT                TIME                COMMAND
8818                pts/0               -                   0:00                bash
-                   -                   Ss                  0:00                -
8892                pts/0               -                   0:01                /usr/bin/python /usr/bin/yum install sshd
-                   -                   Sl+                 0:01                -
-                   -                   Sl+                 0:00                -_

@cpuguy83, please check my new commitment concerning commit message and title.

In case, the commitment (https://github.com/catinthesky/docker/commit/a3774a982ac0ea479d3c10c7bf56117a809c4d97) not get linked here,

**Comment by catinthesky** [comment]
As for this error, "janky — Jenkins build Docker-PRs 39000 has failed"

_07:25:22 Error response from daemon: No such container: docker-pr39000
07:25:22 Archiving artifacts_

Not very sure if this has something to do with the commitment,  can somebody help take a look.

**Comment by catinthesky** [comment]
New change committed for the last jenkins build job .go file format checking, now all checks passed.
@cpuguy83 , please have a check with commitment title changed.

**Comment by catinthesky** [comment]
@cpuguy83 , thanks for changing the title, is anything I should do to make it go forward cause it seems still in "Change requested" state.

**Comment by catinthesky** [comment]
@thaJeztah, @LK4D4, in case you didn't notice the new commitment I made for showing both the process and threads when it comes to the "ps"s "m" option,  please have a check if this OK, or any other suggestions ?

**Comment by catinthesky** [comment]
@thaJeztah, @LK4D4, in case you didn't notice the new commitment I made for showing both the process and threads when it comes to the "ps"s "m" option,  please have a check if this OK, or any other suggestions ?

**Comment by thaJeztah** [comment]
Sorry; had a couple of very busy days; i'll try to give it another look, but don't hesitate to ping me again in case I haven't done so soon :blush:

**Comment by catinthesky** [comment]
@thaJeztah, @cpuguy83 , @LK4D4, in case too busy to notice for the commiment review :)

**Comment by catinthesky** [comment]
@thaJeztah, @cpuguy83 , @LK4D4, guys, hoping this message to be paid attention to :) when sitting in front of laptop the new week.

**Comment by catinthesky** [comment]
@thaJeztah,  are you free to take a check at the commitment ?

**Comment by catinthesky** [comment]
@thaJeztah, are you free to take a check at the new commitment ?

File: daemon/top_unix.go [hunk 1]
```diff
@@ -58,25 +58,51 @@ func parsePSOutput(output []byte, pids []int) (*container.ContainerTopOKBody, er
...
+			p   int
+			err error
+		)
+
+		if fields[pidIndex] == "-" {
+			if preContainedPidFlag {
+				addProcess()
+			}
+			continue
+		} else {
```
Comment (cpuguy83) [inline daemon/top_unix.go]: This is a redundant `else`

File: daemon/top_unix.go [hunk 2]
```diff
@@ -58,25 +58,51 @@ func parsePSOutput(output []byte, pids []int) (*container.ContainerTopOKBody, er
 	}
 
 	// loop through the output and extract the PID from each line
+	//Fix bug https://github.com/docker/docker/issues/30580
+	//Flag used to decide if the previous pid being contianter contained
```
Comment (cpuguy83) [inline daemon/top_unix.go]: I'm not sure I understand this comment, can you explain?
Also since we're changing, can you add 1 space after `//` for all comments added?

File: daemon/top_unix.go [hunk 3]
```diff
@@ -58,25 +58,51 @@ func parsePSOutput(output []byte, pids []int) (*container.ContainerTopOKBody, er
...
+			}
+			continue
+		} else {
+			p, err = strconv.Atoi(fields[pidIndex])
+			if err != nil {
+				return nil, fmt.Errorf("Unexpected pid '%s': %s", fields[pidIndex], err)
+			}
 		}
 
 		for _, pid := range pids {
```
Comment (cpuguy83) [inline daemon/top_unix.go]: Maybe we can extract this into a separate function and remove the double loop?

Something like:
```go
if hasPid(pids, pid) {
  preContainedPidFlag = true
  addProcess()
  continue
}
```

File: daemon/top_unix.go [hunk 4]
```diff
@@ -58,25 +58,51 @@ func parsePSOutput(output []byte, pids []int) (*container.ContainerTopOKBody, er
...
-				// merging "overhanging" fields
-				process := fields[:len(procList.Titles)-1]
-				process = append(process, strings.Join(fields[len(procList.Titles)-1:], " "))
-				procList.Processes = append(procList.Processes, process)
+				preContainedPidFlag = true
+				addProcess()
+				continue processNextLine
 			}
 		}
+		preContainedPidFlag = false
```
Comment (cpuguy83) [inline daemon/top_unix.go]: If this gets moved up before looping over pids, there is no need to have the outer loop labeled, just `break` in the inner loop.

File: daemon/top_unix.go [hunk 5]
```diff
@@ -58,25 +58,51 @@ func parsePSOutput(output []byte, pids []int) (*container.ContainerTopOKBody, er
...
 		if len(line) == 0 {
 			continue
 		}
 		fields := fieldsASCII(line)
-		p, err := strconv.Atoi(fields[pidIndex])
-		if err != nil {
-			return nil, fmt.Errorf("Unexpected pid '%s': %s", fields[pidIndex], err)
+
+		//adding up this line of process to procList
+		addProcess := func() {
```
Comment (cpuguy83) [inline daemon/top_unix.go]: I wonder if we can make this so we aren't creating a closure on each loop.

**Review by cpuguy83 — CHANGES_REQUESTED** [review]

**Comment by catinthesky** [comment]
@cpuguy83, sorry for the delayed response, changes made per your review, adding 2 functions, and having the closure and inner loop and jump label removed,  please have a check, thanks.

File: daemon/top_unix.go [hunk 6]
```diff
@@ -58,25 +75,38 @@ func parsePSOutput(output []byte, pids []int) (*container.ContainerTopOKBody, er
...
+			p   int
+			err error
+		)
+
+		if fields[pidIndex] == "-" {
+			if preContainedPidFlag {
+				appendProcess2ProcList(procList, fields)
+			}
+			continue
+		} else {
```
Comment (cpuguy83) [inline daemon/top_unix.go]: This else is not needed since you have the `continue` in the above case

**Review by cpuguy83 — CHANGES_REQUESTED** [review]

File: daemon/top_unix.go (hunk 6 above)
Comment (catinthesky) [inline daemon/top_unix.go]: It is required, without it, going through loop bottom will make this preContainedPidFlag from true set to false, so it can not display multiple thread lines.

Comment (cpuguy83) [inline daemon/top_unix.go]: You have

```go
if thing {
  // doStuff
  continue
} else {
  do other stuff
}
```

This is the same as
```go
if thing {
  // do stuff
  continue
}
// do other stuff
```

Any time it does hit the else it's continuing on to the next iteration, so when it hits this code below, `fields[pidIndex] == "-"` would never be true with or without the else.

Comment (catinthesky) [inline daemon/top_unix.go]: Maybe I'm not quite clear get you.  Let me clear it a little by below example except from my test:

{
    {[]byte(`  PID COMMAND
   42 foo
   43 bar
    - -
    - -
   41 foo
   50 kk
    - -
  100 baz
    - -
`), []int{50, 43, 100}, false}:

be I'm not quite clear get you.  Let me clear it a little by below example except from my test:

{
    {[]byte(`  PID COMMAND
   42 foo
   43 bar
    - -
    - -
   41 foo
   50 kk
    - -
  100 baz
    - -
`), []int{50, 43, 100}, false}:

According to the logic for "docker top" command, only the processes {50,43,100} should be displayed (which are the container contained processes, others not belong to this container, so ignore them):
"42 foo", not in the pids, so ignore,  preContainedPidFlag = false
"43 bar", should display.  preContainedPidFlag = true
 "- -"  , following above,  preContainedPidFlag = true
 "- -" ,  should display,  preContainedPidFlag = true //continer, else it lead to  preContainedPidFlag = true at the bottom 
"41 foo", not in the pids, so ignore,  preContainedPidFlag = false
"100 baz", should display, preContainedPidFlag = true
"- -", should display, preContainedPidFlag = true

As for logic as below:

    if fields[pidIndex] == "-" {
      if preContainedPidFlag {
        appendProcess2ProcList(procList, fields)
      }
      continue
    } else {
      p, err = strconv.Atoi(fields[pidIndex])
      if err != nil {
        return nil, fmt.Errorf("Unexpected pid '%s': %s", fields[pidIndex], err)
      }
    }

it cannot be refactored into:
if (if fields[pidIndex] == "-" ) {
  ...
}
do other stuff, cause if preContainedPidFlag==false, " p, err = strconv.Atoi(fields[pidIndex])" report errror when it encouter "-".

Not sure, if I make it clear. thanks.

Comment (catinthesky) [inline daemon/top_unix.go]: Maybe I'm not quite clear get you.  Let me clear it a little by below example except from my test:
{
    {[]byte(`  PID COMMAND
   42 foo
   43 bar
    - -
    - -
   41 foo
   50 kk
    - -
  100 baz
    - -
`), []int{50, 43, 100}, false}:

According to the logic for "docker top" command, only the processes {50,43,100} should be displayed (which are the container contained processes, others not belong to this container, so ignore them):
"42 foo", not in the pids, so ignore,  preContainedPidFlag = false
"43 bar", should display.  preContainedPidFlag = true
 "- -"  , following above,  preContainedPidFlag = true
 "- -" ,  should display,  preContainedPidFlag = true //continer, else it lead to  preContainedPidFlag = true at the bottom 
"41 foo", not in the pids, so ignore,  preContainedPidFlag = false
"100 baz", should display, preContainedPidFlag = true
"- -", should display, preContainedPidFlag = true

So it works.  

Yes, this can be refactored into below, do you intend to have code this way (much clear :) ), or let it be, thanks. 
if thing {
  // do stuff
  continue
}
// do other stuff

**Comment by catinthesky** [comment]
@cpuguy83 ,   changes committed to git for refactoring as suggested above, but it seems the github doesn't correctly reflect what I had done, changed to below, please have a check, thanks.

		if fields[pidIndex] == "-" {
			if preContainedPidFlag {
				appendProcess2ProcList(procList, fields)
			}
			continue
		}
		p, err = strconv.Atoi(fields[pidIndex])
		if err != nil {
			return nil, fmt.Errorf("Unexpected pid '%s': %s", fields[pidIndex], err)
		}

**Review by cpuguy83 — APPROVED** [review]
It's probably just GH cache, I see it just fine here.

LGTM

**Comment by cpuguy83** [comment]
ping @thaJeztah

**Review by vdemeester — APPROVED** [review]
LGTM 🐯
