### PR TITLE
daemon.ContainerStop(): fix for a negative timeout

### LINKED ISSUE #35311: `docker restart -t` with negative input time return different results after change the backend
**Description**
After the PR #32237, we have changed the Container Wait Backend. However, this pr leads some different behavior to `docker restart -t` 

**Steps to reproduce the issue:**
1. `docker restart -t -100  $containerID` in the early version 1.11.2 
     `docker` will wait utils container to  exit elegantly
2. `docker restart -t -100  $containerID` in the latest version 17.x
      `docker` will stop the containerd immediately.

**Describe the results you expected:**

As the code code annotation before the PR:
```
container/state.go

//WaitStop waits until state is stopped. If state already stopped it returns
//immediately. If you want wait forever you must supply negative timeout.
//Returns exit code, that was passed to SetStopped
```

**Code check:**

The reason why the difference happens lays in the function realization of `wait`

Before the PR, negative timeout is handled by `wait`  func:
```
func wait(waitChan <-chan struct{}, timeout time.Duration) error {
	if timeout < 0 {
		<-waitChan
		return nil
	}
	select {
	case <-time.After(timeout):
		return fmt.Errorf("Timed out: %v", timeout)
	case <-waitChan:
		return nil
	}
}
```
negative restart timeout will be hold on until elegantly exit.

After the PR, we use `context.WithTimeout` to realize the `Wait` func:
```
func WithDeadline(parent Context, deadline time.Time) (Context, CancelFunc) {
	if cur, ok := parent.Deadline(); ok && cur.Before(deadline) {
		// The current deadline is already sooner than the new one.
		return WithCancel(parent)
	}
	c := &timerCtx{
		cancelCtx: newCancelCtx(parent),
		deadline:  deadline,
	}
	propagateCancel(parent, c)
	d := time.Until(deadline)
	if d <= 0 {
		c.cancel(true, DeadlineExceeded) // deadline has already passed
		return c, func() { c.cancel(true, Canceled) }
	}
	c.mu.Lock()
	defer c.mu.Unlock()
	if c.err == nil {
		c.timer = time.AfterFunc(d, func() {
			c.cancel(true, DeadlineExceeded)
		})
	}
	return c, func() { c.cancel(true, Canceled) }
}

```
Negative restart timeout will be returned immediately.

I want to know if this is a bug due to the PR #32237 ? 
AND If this is a bug ,maybe I can fix it.

### PR DESCRIPTION
**Pull request by kolyshkin**
As daemon.ContainerStop() documentation says,

> If a negative number of seconds is given, ContainerStop
> will wait for a graceful termination.

but since commit cfdf84d5d04c8ee (PR #32237) this is no longer the case.
This happens because `context.WithTimeout(ctx, timeout)` is implemented
as `WithDeadline(ctx, time.Now().Add(timeout))`, resulting in a deadline
which is in the past.

To fix, don't use WithDeadline() if the timeout is negative.

A test case is added to validate the correct behavior and as a means
to prevent a similar regression in the future.

This is a replacement of #35418, and should fix #35311.

### CODE REVIEW

**Comment by kolyshkin** [comment]
Created for the sake of CI, will add more later.

**Comment by kolyshkin** [comment]
CI failure on janky ([logs here](https://jenkins.dockerproject.org/job/Docker-PRs/49001/console)) is a flaky TestAPIServiceUpdatePort (https://github.com/moby/moby/issues/36501).

CI failure on z ([logs here](https://jenkins.dockerproject.org/job/Docker-PRs-s390x/9386/console)) is a flaky test TestAPISwarmNodeDrainPause (https://github.com/moby/moby/issues/23516).

CI failure on Windows is weird, the build just timed out without running any tests ([logs here](https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS1/20432/console)); restarted.

File: integration/container/stop_test.go [hunk 1]
```diff
@@ -42,6 +43,47 @@ func TestStopContainerWithRestartPolicyAlways(t *testing.T) {
 	}
 }
 
+// TestStopContainerWithTimeout checks that ContainerStop with
+// a timeout works as documented, i.e. in case of negative timeout
+// waiting is not limited (issue #35311).
+func TestStopContainerWithTimeout(t *testing.T) {
+	t.Parallel()
```
Comment (cpuguy83) [inline integration/container/stop_test.go]: This makes for a flakey test whennused with the main integration daemon.

File: integration/container/stop_test.go [hunk 2]
```diff
@@ -42,6 +43,47 @@ func TestStopContainerWithRestartPolicyAlways(t *testing.T) {
...
+		// In case container is forcefully killed, 137 is returned,
+		// otherwise the exit code from the above script
+		{0, 137}, // zero timeout: sleep won't finish, container is killed
+		{1, 137}, // too small timeout: same as above
+		{3, 42},  // big enough timeout for normal container stop
+		{-1, 42}, // unlimited timeout: same as above
+	}
+
+	for _, d := range testData {
+		name := container.WithName(t.Name() + "_" + strconv.Itoa(d.timeout))
```
Comment (cpuguy83) [inline integration/container/stop_test.go]: Use "t.Run" so the different cases run as separate tests. This makes it easiee to know which case failed (if there is a failure)

**Review by cpuguy83 — CHANGES_REQUESTED** [review]

File: integration/container/stop_test.go (hunk 1 above)
Comment (kolyshkin) [reply integration/container/stop_test.go]: Can you please elaborate why?

Comment (cpuguy83) [reply integration/container/stop_test.go]: Because it is running in the main daemon.
The test setup takes a snapshot of the current state and then at the end of the test cleans up anything that was not in the original state. But if there are multiple tests doing this cleanup they will conflict with each other, clean up stuff they shouldn't be, etc.

**Comment by kolyshkin** [comment]
OK this is no longer WIP. CI failure in experimental is flaky test `DockerSwarmSuite.TestAPIServiceUpdatePort` (#36501).

**Comment by kolyshkin** [comment]
@cpuguy83 can you PTAL? All your comments were acted upon

File: integration/container/stop_test.go [hunk 3]
```diff
@@ -42,6 +43,61 @@ func TestStopContainerWithRestartPolicyAlways(t *testing.T) {
...
+			"unlimited timeout: expect graceful container stop",
+			-1, 42,
+		},
+	}
+
+	for _, d := range testData {
+		d := d
+		name := t.Name() + "_" + strconv.Itoa(d.timeout)
+		t.Run(name, func(t *testing.T) {
+			t.Parallel()
```
Comment (cpuguy83) [inline integration/container/stop_test.go]: I think each one of these is treated as a separate test, so they all get grouped together at the end of the test run with the rest of the parallel tests. So I'm not sure this is any safer than before.

Comment (kolyshkin) [reply integration/container/stop_test.go]: 1. I think this is not so.  According to the [golang pkg/testing documentation](https://golang.org/pkg/testing/#hdr-Subtests_and_Sub_benchmarks), such tests are only run in parallel with each other (emphasize is mine):

<blockquote>
Subtests can also be used to control parallelism. A parent test will only complete once all of its subtests complete. In this example, all tests are run in parallel with each other, and only with each other, regardless of other top-level tests that may be defined:

```go
func TestGroupedParallel(t *testing.T) {
    for _, tc := range tests {
        tc := tc // capture range variable
        t.Run(tc.Name, func(t *testing.T) {
            t.Parallel()
            ...
        })
    }
}
```
</blockquote>

2. I got the idea from similar tests like this one: https://github.com/moby/moby/blob/fe2d3a1551f666465e65ec4337e92b774a5e81f1/integration/container/create_test.go#L41-L46

**Comment by kolyshkin** [comment]
Minor change:
 - don't add test name to subtest name as it's redundant
 - don't set container name

```diff
-               name := t.Name() + "_" + strconv.Itoa(d.timeout)
-               t.Run(name, func(t *testing.T) {
+               t.Run(strconv.Itoa(d.timeout), func(t *testing.T) {
                        t.Parallel()
-                       id := container.Run(t, ctx, client, testCmd, container.WithName(name))
+                       id := container.Run(t, ctx, client, testCmd)
```

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by kolyshkin** [comment]
CI failure in TestAPISwarmLeaderElection is https://github.com/moby/moby/issues/32673

**Comment by kolyshkin** [comment]
not sure why I had it as [WIP] -- it's definitely not )

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Comment by cpuguy83** [comment]
16 days since last CI run... but this is probably fine.
YOLO merge.
