### PR TITLE
Show volume options for `docker volume inspect`

### LINKED ISSUE #25545: docker volume inspect does not show volume options
If you create a volume with options, docker inspect doesn't output any of the information, making it difficult to determine how a volume was created.

Here's the current output:
`[
    {
        "Name": "foo",
        "Driver": "local",
        "Mountpoint": "/var/lib/docker/volumes/foo/_data",
        "Labels": {}
    }
]
`

I would expect another "Options" key which has a value like {"<key>": "<value>", ...} for each of the options specified.

### LINKED ISSUE #27493: volume options is missing in `docker volume inspect xxx`
**Description**
I created a local volume with options, while when I docker volume inspect this volume, I can not see any volume option. I think this is somewhat not so user-friendly.

**Steps to reproduce the issue:**
1. `docker volume create --driver local --opt type=tmpfs --opt device=tmpfs --opt o=size=100m,uid=1000 --name foo`
2.`docker volume inspect foo`

**Describe the results you received:**
```
root@ubuntu:~# docker volume inspect foo
[
    {
        "Name": "foo",
        "Driver": "local",
        "Mountpoint": "/var/lib/docker/volumes/foo/_data",
        "Labels": {},
        "Scope": "local"
    }
]
```

**Describe the results you expected:**
Volume options here in the displaying result.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
root@ubuntu:~# docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
root@ubuntu:~# docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64
root@ubuntu:~# docker info
Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 63
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 457
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: active
 NodeID: 4yghf0i19aa9a65dgsyitqns3
 Is Manager: true
 ClusterID: 7bgsisgkf388rd3fpz5i4k71s
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 10
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.59.103
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: ubuntu
ID: HRBI:EV6M:3NAC:CXZ3:BDS7:UOKL:PD6Y:ZCK4:V3PF:V7MR:CU2Y:3LGG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 41
 Goroutines: 130
 System Time: 2016-10-08T09:47:44.920514649+08:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 a=b
Insecure Registries:
 192.168.1.22:5500
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by yongtang**
**\- What I did**

This fix tries to address the issue raised in #25545 where volume options at the creation time is not showed up in `docker volume inspect`.

**\- How I did it**

This fix adds the field `Options` in `Volume` type and persist the options in volume db so that `volume inspect` could display the options.

**\- How to verify it**

This fix adds a couple of test cases to cover the changes.

**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**

This fix fixes #25545
This fix fixes #27493

Signed-off-by: Yong Tang yong.tang.github@outlook.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks! This will need docs changes once we're past code review.

Also (after this PR), now that we store actual options, we may be able to better detect conflicting options, and address https://github.com/docker/docker/issues/16068

ping @cpuguy83

**Comment by cpuguy83** [comment]
Design OK.

File: volume/store/store.go [hunk 1]
```diff
@@ -21,14 +21,20 @@ const (
...
 	volume.Volume
-	labels map[string]string
-	scope  string
+	labels  map[string]string
+	scope   string
+	options map[string]string
+}
+
+func (v volumeWrapper) Options() map[string]string {
+	return v.options
```
Comment (cpuguy83) [inline volume/store/store.go]: This should return a copy of the map instead of the actual map.

File: volume/volume.go [hunk 2]
```diff
@@ -73,6 +73,12 @@ type LabeledVolume interface {
 	Volume
 }
 
+// OptionedVolume wraps a Volume with driver defined options
+type OptionedVolume interface {
```
Comment (cpuguy83) [inline volume/volume.go]: Maybe we can replace all these 1-off interfaces with a single `VolumeWithDetails`... maybe a better name.
But all volumes will have it since we are wrapping all the volumes.

File: volume/store/store.go [hunk 3]
```diff
@@ -476,7 +490,7 @@ func (s *VolumeStore) FilterByDriver(name string) ([]volume.Volume, error) {
 		return nil, &OpErr{Err: err, Name: name, Op: "list"}
 	}
 	for i, v := range ls {
-		ls[i] = volumeWrapper{v, s.labels[v.Name()], vd.Scope()}
+		ls[i] = volumeWrapper{v, s.labels[v.Name()], vd.Scope(), s.options[v.Name()]}
```
Comment (cpuguy83) [inline volume/store/store.go]: Should be a copy and not the actual map.

**Review by cpuguy83 — CHANGES_REQUESTED** [review]

File: volume/store/store.go (hunk 1 above)
Comment (yongtang) [inline volume/store/store.go]: Done.

File: volume/store/store.go (hunk 3 above)
Comment (yongtang) [inline volume/store/store.go]: Done.

File: volume/volume.go (hunk 2 above)
Comment (yongtang) [inline volume/volume.go]: Thanks @cpuguy83. I updated the PR and use `VolumeWithDetails` for now. Let me know if other names are preferred.

Comment (yongtang) [inline volume/volume.go]: @cpuguy83 The `VolumeWithDetails` has been changed to `DetailedVolume` as otherwise golint will complain.

**Comment by yongtang** [comment]
Thanks @cpuguy83 for the review. The PR has been updated. Please let me know if there are additional issues.

Thanks @thaJeztah for the reminder. I will update the docs once code review is done. Will also take a look at #16068 and see what we could do with it.

**Comment by cpuguy83** [comment]
LGTM

**Comment by yongtang** [comment]
@thaJeztah This PR has been rebased with docs updated. Please take a look and let me know if there are any issues. (Will try to have another PR for #16068 later)

**Comment by yongtang** [comment]
Rebased the PR to fix the merge conflict. Also updated the description to include `fixes #27493` (See #27493).

File: api/types/types.go [hunk 4]
```diff
@@ -447,6 +447,7 @@ type Volume struct {
 	Status     map[string]interface{} `json:",omitempty"` // Status provides low-level status information about the volume
 	Labels     map[string]string      // Labels is metadata specific to the volume
 	Scope      string                 // Scope describes the level at which the volume exists (e.g. `global` for cluster-wide or `local` for machine level)
+	Options    map[string]string      // Options holds the driver specifi options to use for when creating the volume.
```
Comment (allencloud) [inline api/types/types.go]: specifi, Typo?

Comment (yongtang) [inline api/types/types.go]: Thanks. Done.

File: docs/reference/api/docker_remote_api_v1.25.md [hunk 5]
```diff
@@ -3323,7 +3324,11 @@ Return low-level information about the `exec` command `id`.
             "com.example.some-label": "some-value",
             "com.example.some-other-label": "some-other-value"
           },
-          "Scope": "local"
+          "Scope": "local",
+          "Options":{
+            "some-key": "some-value",
+            "some-other-key": "some-other-value"
```
Comment (yongtang) [inline docs/reference/api/docker_remote_api_v1.25.md]: Thanks @allencloud. The PR has been updated with the doc changes.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
ping @vdemeester PTAL

File: volume/store/store.go [hunk 6]
```diff
@@ -23,14 +23,24 @@ const (
...
+	scope   string
+	options map[string]string
+}
+
+func (v volumeWrapper) Options() map[string]string {
+	options := map[string]string{}
+	for key, value := range v.options {
+		options[key] = value
+	}
+	return options
```
Comment (allencloud) [inline volume/store/store.go]: Thanks @yongtang. I know that deep copy is correct. While I still can not follow why options needs a deep copy, while labels does not. @cpuguy83 Can you give me some explaination. Thanks a lot.

Comment (thaJeztah) [inline volume/store/store.go]: It would probably make sense for labels as well, but that's out of scope for this PR

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by vdemeester** [comment]
@yongtang needs a rebase though :angel:

**Comment by yongtang** [comment]
Thanks all for the review! The PR has been rebased and all tests passed. Ping @vdemeester.
