### PR TITLE
Fix installation script for RHEL

### LINKED ISSUE #23787: test.docker.com script does not work (403) for RHEL7 host (attempting to install 1.12.0-rc2)
(this is @nathanleclaire reporting from user's laptop at DockerCon)

`test.docker.com` script does not work for RHEL host.

```console
[ec2-user@ip-192-168-0-215 ~]$ cat /etc/os-release 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.2 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.2 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.2:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.2"

[ec2-user@ip-192-168-0-215 ~]$ curl -fsSL https://test.docker.com/ | sh
+ sudo -E sh -c 'sleep 3; yum -y -q install docker-engine'
https://yum.dockerproject.org/repo/testing/redhat/7/repodata/repomd.xml: [Errno 14] HTTPS Error 403 - Forbidden
Trying other mirror.
To address this issue please refer to the below knowledge base article

https://access.redhat.com/solutions/69319

If above article doesn't help to resolve this issue please open a ticket with Red Hat Support.



 One of the configured repositories failed (Docker testing Repository),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Disable the repository, so yum won't use it by default. Yum will then
        just ignore the repository until you permanently enable it again or use
        --enablerepo for temporary usage:

            yum-config-manager --disable docker-testing-repo

     4. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=docker-testing-repo.skip_if_unavailable=true

failure: repodata/repomd.xml from docker-testing-repo: [Errno 256] No more mirrors to try.
https://yum.dockerproject.org/repo/testing/redhat/7/repodata/repomd.xml: [Errno 14] HTTPS Error 403 - Forbidden
```

@tianon @mikedougherty who maintains these?  Thanks.

### PR DESCRIPTION
**Pull request by thaJeztah**
the previous fix changed the lsb_dist variable too early. We only need to normalize to "centos" for the repository-location, so changing it just before that.

/cc @kencochrane @mlaventure 

fixes https://github.com/docker/docker/issues/23787

### CODE REVIEW

**Comment by kencochrane** [comment]
LGTM, thanks for tracking that down.

**Comment by kencochrane** [comment]
Spoke to soon, saw @Purple90 comment

```
Oh, its because you need brackets around lsb_dist
So change it to this

            if [ "${lsb_dist}" = "redhat" ]; then
                # we the centos repository for both redhat and centos releases
                lsb_dist='centos'
            fi
```

**Comment by thaJeztah** [comment]
thanks @kencochrane @Purple90, updated my PR, PTAL

**Comment by tiborvass** [comment]
I still have the same error as reported in #23787

**Comment by thaJeztah** [comment]
@tiborvass the original error, or the one that I introduced?

**Comment by thaJeztah** [comment]
@tiborvass that's on RHEL? Is there an active subscription?

**Comment by tiborvass** [comment]
@thaJeztah oh that must be why lol

File: hack/install.sh [hunk 1]
```diff
@@ -438,6 +437,10 @@ do_install() {
 			;;
 
 		fedora|centos|redhat|oraclelinux)
+			if [ "${lsb_dist}" = "redhat" ]; then
+				# we use the centos repository for both redhat and centos releases
+				lsb_dist='centos'
+			fi
```
Comment (kencochrane) [inline hack/install.sh]: A little further down (line 452) we do the following.

```
if [ "$lsb_dist" = "fedora" ]
```

Should we keep them consistent? doing ```"${lsb_dist}"``` in one place and ```"$lsb_dist"``` in another makes it a little harder to read. Since they are doing the same thing, we might as well make it consistent. Is one way, better than the other? I personally don't care, which one we use.

Comment (thaJeztah) [inline hack/install.sh]: @kencochrane yes, I noticed that, but didn't want to make unrelated changes in this PR, can do in a follow up if needed

Comment (kencochrane) [inline hack/install.sh]: Makes senses, thanks. Just wanted to point it out before I forgot.

**Comment by anusha-ragunathan** [comment]
I tested an upgrade on RHEL7.2 and things work well.

[ec2-user@ip-172-31-39-24 yum.repos.d]$ curl https://raw.githubusercontent.com/thaJeztah/docker/73d5f0648e430a74cd05ff9fd335611ddc6dd2a1/hack/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14604  100 14604    0     0  22218      0 --:--:-- --:--:-- --:--:-- 22228
Warning: the "docker" command appears to already exist on this system.

If you already have Docker installed, this script can cause trouble, which is
why we're displaying this warning and provide the opportunity to cancel the
installation.

If you installed the current Docker package using this script and are using it
again to update Docker, you can safely ignore this message.

You may press Ctrl+C now to abort this script.
+ sleep 20
+ sudo -E sh -c 'sleep 3; yum -y -q install docker-engine'
Package docker-engine-1.12.0-0.2.rc2.el7.centos.x86_64 already installed and latest version
+ sudo -E sh -c 'docker version'
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker ec2-user

Remember that you will have to log out and back in for this to take effect!

**Comment by tiborvass** [comment]
LGTM

**Comment by nathanleclaire** [comment]
👍
