### PR TITLE
deprecate bind path auto-create

### LINKED ISSUE #12776: Docker container with attached volume won't start after reboot
Hello,

I encounter some problems with volumes after rebooting.
I start a container with
```
sudo docker run -ti \
	-e DISPLAY \
	-v /tmp/.X11-unix:/tmp/.X11-unix:ro \
	-v ~/.Xauthority:/home/wine/.Xauthority \
	-v /dev/snd:/dev/snd --privileged \
	-v /run/user/`id -u`/pulse/native:/run/user/`id -u`/pulse/native \
	--net=host \
	webanck/docker-wine-steam
```
Then I stop the xxxx container and am perfectly able to restart it doing:
```
sudo docker start xxxx && sudo docker attach xxxx
```
But when I reboot my computer and try the same as above to restart my container I always get the same error:
```
Error response from daemon: Cannot start container xxxx: setup mount namespace mounting /run/user/1001/pulse/native into /var/lib/docker/aufs/mnt/9b2641d21b7895bded8b0783d3e69aae75f167412f8a4e6f69308d54590111bc/run/user/1001/pulse/native not a directory
FATA[0000] Error: failed to start one or more containers
```

Any idea of what I am doing wrong? Or is it a problem with docker itself?

PS: for more information on the image I am using, see my repository [docker-wine-steam](https://github.com/webanck/docker-wine-steam).

### LINKED ISSUE #13468: Directories created for volumes on boot initialisation, when the corresponding container is not running, causing issues with host applications writing to the directories
I'm having an issue (well, a number of related issues) with containers and volumes. Some of these issues are mentioned elsewhere, but this particular instance is not.

I am running a container to allow execution of a legacy Wordpress Install. As this is on my development system I didn't want to have a separate mysql container, rather just use the mysql container on my host. Therefore I tried runing docker with the following:

```docker run -d --name php53 -v /home/sites/example.org/www:/var/www -v /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock precise_apache_php53 /usr/sbin/apache2ctl -D FOREGROUND```

The issue is with:

```-v /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock```

The purpose being to expose my host mysql server to the container. This worked beautifully, until my development server was rebooted after a power failure. The mysql stopped working.

It seems on reboot that because ` /var/run/mysqld/mysqld.sock` does not exist it's being created by docker _even though no container is running_ (it's also creating it as a directory, but that's a seperate issue: #13121 ).

So, I decided to change the param to 

```-v /var/run/mysqld:/var/run/mysqld```

As `/var/run/mysqld` is persistent over reboots. However when I do this, having stopped the container before reboot, it appears that mysql still cannot create the socket file in that directory _even though the permissions for the directory are correct_. I have to issue a 

```docker rm php53```

command before I reboot to stop docker from creating (or taking control of) `/var/run/mysqld`

This is problematic as I don't believe docker should be doing anything on my local filesystem until I run a container, and the container is not run automatically at boot. 

*docker version*
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

*docker info*
Containers: 29
Images: 72
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 130
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.16.0-38-generic
Operating System: Ubuntu 14.10
CPUs: 8
Total Memory: 15.64 GiB
Name: tattve
ID: EKU2:ETU7:MEQA:TLLN:ZJEU:IFDP:36QJ:JLXM:AE66:ZRSG:EMCC:3FZU
WARNING: No swap limit support

*uname -a*
Linux tattve 3.16.0-38-generic #52-Ubuntu SMP Thu May 7 10:51:21 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

*Environment*
Physical ubuntu 14.10

*How Reproducible*
I've been able to reproduce the issue with a number of different images running as containers, over numerous reboots. I tracked the issue down to docker by uninstalling it and the issue went away. Upon re-install it started again (presumably because container info was kept through the uninstall)

*Steps to Reproduce*
On Ubuntu 14.10 or 14.04 with mysql installed from distro .deb files,default configuration

1. `docker run --name bugtest x-v /var/run/mysqld/:/var/run/mysqld/ hello_world`
2. `mysql` to access the mysql client, will connect to server (though user/password will be needed)
3. `sudo reboot`
4. Upon reboot mysqld will not have started due to the issues with `/var/run/mysql`
5 `mysql` will return an error could not connect via /var/run/mysqld/mysqld.sock
4. `docker rm bugtest`
5. `reboot`
6. Upon reboot mysqld will have started, `mysql` will be able to connect

*Additional Info*

Whilst I'm reporting this issue with mysql as example, I'm simply using that to illustrate a point. The point being that docker seems to be stopping host applications from properly accessing directories which are mapped as volumes, and creating some connection to those directories even when no container is running. I'm not familar enough with Linux Containers to know, but the problem may well be there, rather than docker itself.

### LINKED ISSUE #16302: enhancement: ability to specify file v folder mount
i have ran into problems in the past attempting to mount a file that is accidentally not present.

docker will assume that i want to mount a folder and it will create a folder (named after the missing file) creating confusion.

for example:

```
docker run -v /path/to/file.txt:/file.txt me/my-image
```

will create a folder named `file.txt` at `/path/to` if `/path/to/file.txt` doesn't exist.

i burned a few hours on this once with a docker-ized node app that was complaining that i was trying to open a folder as a file.

i thought it might be smoother if i could signal to docker that i am going after a file v a folder, and then if i specify `:ro` have it throw an error if it doesn't exist, or if it is `:rw` (default) have it just create the file.

so something like a `-f` option to indicate mounting a file, like so:

```
docker run -f /path/to/file.txt:/file.txt me/my-image
```

### PR DESCRIPTION
**Pull request by cpuguy83**
Fixes #16302
Fixes #12776
Fixes #13468
I'm sure a few more that I could not find again.

ping @calavera

### CODE REVIEW

**Comment by calavera** [comment]
@cpuguy83 I think we should show a warning in the client when this happens.

@docker/maintainers Please, take a look. This is source of much confusion among users and we'd like to deprecate it.

**Comment by tiborvass** [comment]
warning is fine for me

**Comment by tianon** [comment]
Definitely +1 for deprecation, and +1 for a warning :+1: :metal:

**Comment by duglin** [comment]
sgtm

**Comment by calavera** [comment]
Just to clarify, I meant to show a warning saying that we auto-created the directory but it's a deprecated feature and we're going to stop doing it.

**Comment by abronan** [comment]
Agreed for deprecating/removing it, SGTM

**Comment by thaJeztah** [comment]
+1 for removing this "feature", and +1 for outputting a warning now (including a "deprecation" message?)

(If we want a "warning" in 1.9, please add that change to this PR)

The documentation changes in this PR can use a slight touch-up, but I'll wait until it's been agreed on.

**Comment by cpuguy83** [comment]
Presenting the user with a warning is not a small change.
Warning the daemon logs is simple enough.

Not sure about presenting a warning to the user here unless we just do it for all binds.

**Comment by cpuguy83** [comment]
And then it would just be on the client.

**Comment by moxiegirl** [comment]
LGTM @thaJeztah touch up at will it looks ok by me.  Didn't we just have a pr touching on bind mount --- #13776?  Does that language still work in light of this...bit late for me...maybe I'm not clear

**Comment by stevvooe** [comment]
:+1:

**Comment by calavera** [comment]
@cpuguy83 maybe the daemon log is good enough, that's what we did with LXC:

https://github.com/docker/docker/pull/15255/files

Can you add it here?

**Comment by cpuguy83** [comment]
Pushed with daemon log added.

File: daemon/volumes.go [hunk 1]
```diff
@@ -52,6 +52,9 @@ func (m *mountPoint) Setup() (string, error) {
 			if !os.IsNotExist(err) {
 				return "", err
 			}
+			if _, err := os.Stat(m.Source); err != nil && os.IsNotExist(err) {
```
Comment (stevvooe) [inline daemon/volumes.go]: This needs to check for an error that is not a `os.IsNotExist` and handle that appropriately:

```
if fi, err := os.Stat(m.Source); err != nil {
 if !os.IsNotExist(err) {
     //.. handle error 
 }
 logrus.Warnf("Auto-creating non-existant volume host path %s, this is deprecated and will be removed soon", m.Source)
}
```

Comment (cpuguy83) [inline daemon/volumes.go]: I suppose we can, though this would picked up by the subsequent `os.MkdirAll` anyway.
But since we're already adding the stat call, might as well handle earlier.

Comment (cpuguy83) [inline daemon/volumes.go]: hah, the worst part is we were already doing this, and this is already wrapped in a stat call... silly me.

**Comment by LK4D4** [comment]
LGTM

**Comment by calavera** [comment]
LGTM. Merging since #16287 takes care of the deprecation note in the run page mentioned by @moxiegirl .

**Comment by m59peacemaker** [comment]
The way I'm understanding this, if `/foo` doesn't exist on the host and I do:

`docker run -v /foo:/foo etc`

`/foo` shouldn't be created on the host. I'm on `1.11` and the directory is still created.

Am I misreading this?

**Comment by thaJeztah** [comment]
@m59peacemaker this change was later reverted; see https://github.com/docker/docker/pull/19953#issuecomment-198024624, and   https://github.com/docker/docker/pull/21666

**Comment by m59peacemaker** [comment]
@thaJeztah  Well, that's unfortunate.. https://github.com/docker/docker/pull/19953#issuecomment-231603873

Thanks for letting me know.

**Comment by stevvooe** [comment]
@thaJeztah Auto-creation of bind paths is why we can't have nice things. This model is extremely broken.

Any way we can re-deprecate this?

**Comment by thaJeztah** [comment]
@stevvooe I know 😞. To re-deprecate, I think best start would be to open an issue or PR for discussion

**Comment by tiborvass** [comment]
We can't deprecate this, there are scripts relying on this misfeature.

**Comment by cpuguy83** [comment]
I wish we got the new mounts (for containers) API in for 1.12 so that at least services didn't have to propagate this nastiness.

**Comment by m59peacemaker** [comment]
@tiborvass The `nocreate` option you mentioned [here](https://github.com/docker/docker/pull/19953#issuecomment-198024624) is all I need. You said it wouldn't be useful, but I think my situation calls for it. See https://github.com/docker/docker/pull/19953#issuecomment-231603873

**Comment by diego-treitos** [comment]
In my opinion the directory auto-creation and [mounting a host file as a data volume](https://docs.docker.com/engine/tutorials/dockervolumes/#/mount-a-host-file-as-a-data-volume) are incompatible options.
If you can truly mount any type of file (directory, normal file, socket, pipe, etc) then you cannot auto-create in case it does not exist because you dont know what to create and even if you knew you cannot control the permissions it will have on creation so it might create problems too. This feature makes no sense.

If you truly want to have a feature like this you would need options like:

- `create-d`: Auto-create directory if missing. Default option for backwards compatibility.
- `create-p`: Auto-create pipe if missing
- `create-s`: Auto-create socket if missing
- `create-f`: Auto-create regular file if missing
- `create-none`: Disable auto-creation

and also have an option for  `<user_id>:<group_id>:<permissions>` of the file being autocreated. So you could end up with something like:

`$ docker run --rm -it -v '/var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock:rw:create-s:mysql:mysql:777'  ubuntu /bin/bash`

This way you have full control over the result of starting a container. 

For now, just being able to  disable autocreation with `nocreate` would help to fix many systems although I dont think it is a full solution in the long term in case you want a fully functional auto-create feature.

**Comment by thaJeztah** [comment]
Plans are to provide an "advanced" syntax for `docker run`, similar to the `--mount` flag on `docker service create`. When using the advanced syntax, auto-creation will be disabled for bind-mounts, and the user will be responsible for creating the mounted directory, file (or socket) before the container is started. The intent of bind-mounting something from the host is to allow a container access to something that exists on the host, _not_ to have docker create something on the host (i.e. docker manages anything inside `/var/lib/docker`, but outside of that, it should not be managing things).

The current "shorthand" syntax for bind-mounts `-v /foo/bar:/container/path` will likely not be modified (for reasons of backward compatibility).

**Comment by diego-treitos** [comment]
@thaJeztah thanks a lot for the update. That sounds really good and makes a lot of sense. Looking forward to see those changes :)

**Comment by 2erowf** [comment]
wise decision to leave existing syntax's behavior unchanged. some monitoring solutions leverages the auto-create feature to install their software.

**Comment by thaJeztah** [comment]
To update my earlier comment: the `--mount` syntax was implemented in https://github.com/moby/moby/pull/32251, and is included in docker 17.05 and up
