### PR TITLE
Fix for Flaky test TestServiceWithPredefinedNetwork

### LINKED ISSUE #36547: Flaky test TestServiceWithPredefinedNetwork
This test was added recently in https://github.com/moby/moby/pull/36316, but is failing on a lot of PR's with:

```
13:46:02 --- FAIL: TestServiceWithPredefinedNetwork (12.36s)
13:46:02 	daemon.go:283: [d47ab7ceb5568] waiting for daemon to start
13:46:02 	daemon.go:315: [d47ab7ceb5568] daemon started
13:46:02 	service_test.go:52: timeout hit after 10s: task count at 1 waiting for 0
13:46:02 	daemon.go:273: [d47ab7ceb5568] exiting daemon
13:46:02 FAIL
```

Failure is in the teardown of the test; https://github.com/moby/moby/blob/0b0af855ae28698f8e3dc97cdc2a46e714ce6b6a/integration/network/service_test.go#L52

/cc @selansen

### PR DESCRIPTION
**Pull request by selansen**
Fixes https://github.com/moby/moby/issues/36547

	TestServiceWithPredefinedNetwork test case was failing
	at times. To fix the issue, added new API to check
	for services after we clean up all services. Tested
	multiple times and this sould fix flaky issue.

Signed-off-by: selansen <elango.siva@docker.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: integration/network/service_test.go [hunk 1]
```diff
@@ -49,14 +48,12 @@ func TestServiceWithPredefinedNetwork(t *testing.T) {
...
 	poll.WaitOn(t, serviceIsRemoved(client, serviceID), pollSettings)
-	poll.WaitOn(t, noTasks(client), pollSettings)
+	poll.WaitOn(t, noServices(client), pollSettings)
 
 }
 
 func serviceRunningCount(client client.ServiceAPIClient, serviceID string, instances uint64) func(log poll.LogT) poll.Result {
 	return func(log poll.LogT) poll.Result {
-		filter := filters.NewArgs()
-		filter.Add("service", serviceID)
```
Comment (dnephin) [inline integration/network/service_test.go]: Removing this is not the correct fix. It should be used as a filter in `ServiceList`.

**Review by dnephin — COMMENTED** [review]
There seems to be a couple problems with this test.

1. It's not actually checking anything about the service, just that it exists. Shouldn't it be comparing the inspect result to the expected?

2. It shouldn't be doing cleanup. That is handled by `setupTest(t)()`.

What is the purpose of this test? What is the `host` network a special case? That is what needs to be checked.

File: integration/network/service_test.go (hunk 1 above)
Comment (selansen) [reply integration/network/service_test.go]: 1) The actual regression issue was we couldnt create service with host network. Thats what I tried to test it to make sure there is no issue in creating service with host network. 
2) For your clean up comment :  I try to remove service and make sure service is getting cleared. Thats what  I meant by cleanup. I am not doing anything extra. Do you suggest I dont need to do verify the service that I created  whether I am able to remove or not?. Pls let me know your feedback on this.
3)Regarding not adding filter: I am trying to get all the services running. so looked into existing examples of functions calling serviceList API. none of them using filter. Your previous comment on original comment said , I have defined filter but not using it. So i wanted to clean up the code as part of your previous comment. Pls correct me if my understand is wrong.

Comment (dnephin) [reply integration/network/service_test.go]: >  I try to remove service and make sure service is getting cleared. Thats what I meant by cleanup. I am not doing anything extra. Do you suggest I dont need to do verify the service that I created whether I am able to remove or not?. Pls let me know your feedback on this.

That's right. The daemon which runs this service is going to be shutdown when the test exits (`defer d.Stop(t)`) so you don't need to spend time doing cleanup.

> Regarding not adding filter: I am trying to get all the services running.

Ok, I guess this is ok since you're targeting a daemon that was launched for this test.

**Comment by thaJeztah** [comment]
@selansen this needs a minor rebase

**Comment by selansen** [comment]
should I pull latest moby and apply my change on top of it and submit again
?

**Comment by arm64b** [comment]
>should I pull latest moby and apply my change on top of it and submit again
You should fetch the latest code then make your topic branch `rebase` to the master.

**Comment by selansen** [comment]
Thats what I did and committed my changes. Looks like all sanity passed. 
@thaJeztah , pls let me know if I will have to do anything else.

**Comment by arm64b** [comment]
Seems the symptom of `TestServiceWithIngressNetwork` is very similar as this one...

**Comment by selansen** [comment]
Yes. taken care of that too

**Comment by selansen** [comment]
@thaJeztah , Hope this helps flaky issue that we are seeing on selective target.

**Comment by thaJeztah** [comment]
I think for now this looks ok, but we need to implement https://github.com/moby/moby/issues/36581, so that we don't wait for _all_ services to be cleaned up (in case we want the option of running tests in parallel)

File: integration/network/service_test.go [hunk 2]
```diff
@@ -159,3 +149,17 @@ func swarmIngressReady(client client.NetworkAPIClient) func(log poll.LogT) poll.
 		return poll.Success()
 	}
 }
+
+func noServices(client client.ServiceAPIClient) func(log poll.LogT) poll.Result {
```
Comment (thaJeztah) [inline integration/network/service_test.go]: Erm, this function doesn't seem to be called?

File: integration/network/service_test.go [hunk 3]
```diff
@@ -106,9 +101,6 @@ func TestServiceWithIngressNetwork(t *testing.T) {
 	err = client.ServiceRemove(context.Background(), serviceID)
 	require.NoError(t, err)
 
-	poll.WaitOn(t, serviceIsRemoved(client, serviceID), pollSettings)
-	poll.WaitOn(t, noTasks(client), pollSettings)
```
Comment (thaJeztah) [inline integration/network/service_test.go]: If we don't check if the service (plus tasks?) are all removed here, this test may not be testing what it was created for (i.e.: check that the ingress network is not removed when removing services)

**Review by thaJeztah — CHANGES_REQUESTED** [review]
noticed some things; @selansen can you check?

File: integration/network/service_test.go (hunk 2 above)
Comment (selansen) [reply integration/network/service_test.go]: I kept the new API so that TestServiceWithIngressNetwork will call it. Let me update it.

File: integration/network/service_test.go (hunk 3 above)
Comment (selansen) [reply integration/network/service_test.go]: Idea was to check service is removed instead task as we are testing service create/remove. Thats why I added new API. Let me update TestServiceWithIngressNetwork. Thanks for pointing  it out.

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

File: integration/network/service_test.go (hunk 3 above)
Comment (selansen) [reply integration/network/service_test.go]: BTW actual test that was written by Chris Telfer was to verify Ingress network absence after service remove. So test will fail if it is not met.  Daniel mentioned service clean up will happen automatically when we tear down the swarm . so we dont need to check this explicitly.  Anyways I update the with new API that TestServiceWithIngressNetwork with my newly added noServices check to make sure we cover that .

**Comment by arm64b** [comment]
Seems `DockerSuite.TestPostContainersAttach` test case failed is introduced recently, don't know if @thaJeztah concern has been addressed or not, if it's true, we can try to rebuild the 2 failure nodes

**Review by thaJeztah — APPROVED** [review]
LGTM, but needs a rebase (looks like because of the gotestyourself changes)

**Comment by selansen** [comment]
@thaJeztah , I just did a rebase. should be good to go.

**Comment by thaJeztah** [comment]
Thanks! moved it to "status/merge" - fingers crossed if it all goes green 👍

**Comment by thaJeztah** [comment]
Hm, more flakiness?

```
16:53:08 ----------------------------------------------------------------------
16:53:08 FAIL: docker_api_swarm_service_test.go:61: DockerSwarmSuite.TestAPISwarmServicesCreate
16:53:08 
16:53:08 [dee4f3a4df82c] waiting for daemon to start
16:53:08 [dee4f3a4df82c] daemon started
16:53:08 
16:53:08 docker_api_swarm_service_test.go:92:
16:53:08     waitAndAssert(c, defaultReconciliationTimeout, d.CheckActiveContainerCount, checker.Equals, 0)
16:53:08 docker_utils_test.go:452:
16:53:08     c.Assert(v, checker, args...)
16:53:08 ... obtained int = 3
16:53:08 ... expected int = 0
16:53:08 ... output: "dec8242edf45\na6b9f3e67481\nb05bf8c0000a\n"
16:53:08 
16:53:08 [dee4f3a4df82c] exiting daemon
```

**Comment by thaJeztah** [comment]
These tests pass now though;

```
16:17:58 === RUN   TestServiceWithPredefinedNetwork
16:18:00 --- PASS: TestServiceWithPredefinedNetwork (1.91s)
16:18:00 	daemon.go:283: [d081ae40fa771] waiting for daemon to start
16:18:00 	daemon.go:315: [d081ae40fa771] daemon started
16:18:00 	daemon.go:273: [d081ae40fa771] exiting daemon
16:18:00 === RUN   TestServiceWithIngressNetwork
16:18:11 --- PASS: TestServiceWithIngressNetwork (11.51s)
16:18:11 	daemon.go:283: [de1f27941839a] waiting for daemon to start
16:18:11 	daemon.go:315: [de1f27941839a] daemon started
16:18:11 	daemon.go:273: [de1f27941839a] exiting daemon
16:18:11 PASS
````

**Comment by selansen** [comment]
Not sure about docker_api_swarm_service_test. They are not related to the fix I did. May be we need to take it as separate issue.

**Comment by arm64b** [comment]
`docker_api_swarm_service_test.go` failure can be tracked by #36501 and #36386.
