### PR TITLE
builder: deprecate prune filter `unused-for` in favor of `until`

### LINKED ISSUE #38208: docker system prune doesn't accept "until" filter anymore
**Description**

Following worked in 18.06.1-ce but doesn't work in 18.09.0:

```
docker system prune --filter "until=24h" --force
Error response from daemon: failed to prune build cache: Invalid filter 'until'
```

**Output of `docker version`:**

```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:48:57 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.127-mainline-rev1
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.752GiB
Name: gitlab-alpha
ID: KG5Y:N3O2:DSR2:MLGY:S2B7:GWAX:DXHW:CS3Z:TCUS:2MHA:E72H:QGAS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Barebones cloud computer

### PR DESCRIPTION
**Pull request by tiborvass**
Fixes #38208

### CODE REVIEW

**Comment by thaJeztah** [comment]
Guess https://github.com/docker/cli/pull/1522 won't be needed then 😅

File: builder/builder-next/builder.go [hunk 1]
```diff
@@ -32,7 +32,10 @@ import (
 	grpcmetadata "google.golang.org/grpc/metadata"
 )
 
-var errMultipleFilterValues = errors.New("filters expect only one value")
+var (
+	errMultipleFilterValues = errors.New("filters expect only one value")
+	errSynonymFilterValues = errors.New("synonym filters are forbidden")
```
Comment (thaJeztah) [inline builder/builder-next/builder.go]: I think most similar errors, we use `"conflicting ....."` (e.g. https://github.com/moby/moby/blob/8e610b2b55bfd1bfa9436ab110d311f5e8a74dcb/runconfig/errors.go#L13-L17)


Perhaps `conflicting filters: "until" and "unused-for"` ?

File: builder/builder-next/builder.go [hunk 2]
```diff
@@ -511,17 +515,32 @@ func toBuildkitExtraHosts(inp []string) (string, error) {
...
 
 func toBuildkitPruneInfo(opts types.BuildCachePruneOptions) (client.PruneInfo, error) {
-	var unusedFor time.Duration
-	unusedForValues := opts.Filters.Get("unused-for")
+	var until time.Duration
+	untilValues := opts.Filters.Get("until")
+	unusedForValues := opts.Filters.Get("unused-for") // synonym for until
 
-	switch len(unusedForValues) {
+	switch len(untilValues) {
```
Comment (thaJeztah) [inline builder/builder-next/builder.go]: I find this switch a bit hard to grasp, as it's doing two things (validating, and handling of the values).

How about;

```go
func toBuildkitPruneInfo(opts types.BuildCachePruneOptions) (client.PruneInfo, error) {
	var until time.Duration
	untilValues := opts.Filters.Get("until")
	unusedForValues := opts.Filters.Get("unused-for") // synonym for until

	if len(untilValues) > 0 && len(unusedForValues) > 0 {
		return client.PruneInfo{}, errSynonymFilterValues
	}
	untilValues = append(untilValues, unusedForValues...)

	switch len(untilValues) {
	case 0:
		// nothing to do
	case 1:
		var err error
		until, err = time.ParseDuration(untilValues[0])
		if err != nil {
			return client.PruneInfo{}, errors.Wrap(err, "until filter expects a duration (e.g., '24h')")
		}

	default:
		return client.PruneInfo{}, errMultipleFilterValues
	}

	bkFilter := make([]string, 0, opts.Filters.Len())
	for cacheField := range cacheFields {
		if opts.Filters.Include(cacheField) {
			values := opts.Filters.Get(cacheField)
			switch len(values) {
			case 0:
				bkFilter = append(bkFilter, cacheField)
			case 1:
				if cacheField == "id" {
					bkFilter = append(bkFilter, cacheField+"~="+values[0])
				} else {
					bkFilter = append(bkFilter, cacheField+"=="+values[0])
				}
			default:
				return client.PruneInfo{}, errMultipleFilterValues
			}
		}
	}
	return client.PruneInfo{
		All:          opts.All,
		KeepDuration: until,
		KeepBytes:    opts.KeepStorage,
		Filter:       []string{strings.Join(bkFilter, ",")},
	}, nil
}
```

```patch
diff --git a/builder/builder-next/builder.go b/builder/builder-next/builder.go
index f682b88e8f..1bd2a11be1 100644
--- a/builder/builder-next/builder.go
+++ b/builder/builder-next/builder.go
@@ -519,24 +519,15 @@ func toBuildkitPruneInfo(opts types.BuildCachePruneOptions) (client.PruneInfo, e
        untilValues := opts.Filters.Get("until")
        unusedForValues := opts.Filters.Get("unused-for") // synonym for until
 
+       if len(untilValues) > 0 && len(unusedForValues) > 0 {
+               return client.PruneInfo{}, errSynonymFilterValues
+       }
+       untilValues = append(untilValues, unusedForValues...)
+
        switch len(untilValues) {
        case 0:
-               switch len(unusedForValues) {
-               case 0:
-
-               case 1:
-                       var err error
-                       until, err = time.ParseDuration(unusedForValues[0])
-                       if err != nil {
-                               return client.PruneInfo{}, errors.Wrap(err, "unused-for filter expects a duration (e.g., '24h')")
-                       }
-               default:
-                       return client.PruneInfo{}, errMultipleFilterValues
-               }
+               // nothing to do
        case 1:
-               if len(unusedForValues) > 0 {
-                       return client.PruneInfo{}, errSynonymFilterValues
-               }
                var err error
                until, err = time.ParseDuration(untilValues[0])
                if err != nil {
```

File: builder/builder-next/builder.go [hunk 3]
```diff
@@ -32,7 +32,10 @@ import (
 	grpcmetadata "google.golang.org/grpc/metadata"
 )
 
-var errMultipleFilterValues = errors.New("filters expect only one value")
+var (
+	errMultipleFilterValues = errors.New("filters expect only one value")
```
Comment (thaJeztah) [inline builder/builder-next/builder.go]: Both op these should result in a 4xx status to be returned; can you make these errors implement [`ErrInvalidParameter`](https://github.com/moby/moby/blob/d48392a35b157612d28c48eb8e4fad1272fa1442/errdefs/defs.go#L8-L11)?

**Comment by tiborvass** [comment]
@thaJeztah could still be needed for `label` and `label!`. Unless we want to add them here?

**Review by thaJeztah — CHANGES_REQUESTED** [review]
Thanks! Left some comments/suggestions

**Comment by thaJeztah** [comment]
> could still be needed for label and label!. Unless we want to add them here?

Oh, good call, hm, yes for those we may need a warning printed that it's being ignored 😕

File: builder/builder-next/builder.go (hunk 2 above)
Comment (thaJeztah) [reply builder/builder-next/builder.go]: Could actually better use the`Filter.Contains(..` for that;

```go
if opts.Filters.Contains("until") && opts.Filters.Contains("unused-for") {
	return client.PruneInfo{}, errSynonymFilterValues
}
```

```patch
diff --git a/builder/builder-next/builder.go b/builder/builder-next/builder.go
index f682b88e8f..a2dd035e06 100644
--- a/builder/builder-next/builder.go
+++ b/builder/builder-next/builder.go
@@ -515,28 +515,16 @@ func toBuildkitExtraHosts(inp []string) (string, error) {
 }
 
 func toBuildkitPruneInfo(opts types.BuildCachePruneOptions) (client.PruneInfo, error) {
+       if opts.Filters.Contains("until") && opts.Filters.Contains("until") {
+               return client.PruneInfo{}, errSynonymFilterValues
+       }
+
        var until time.Duration
-       untilValues := opts.Filters.Get("until")
-       unusedForValues := opts.Filters.Get("unused-for") // synonym for until
+       untilValues := append(opts.Filters.Get("until"),  opts.Filters.Get("unused-for")...)
 
        switch len(untilValues) {
        case 0:
-               switch len(unusedForValues) {
-               case 0:
-
-               case 1:
-                       var err error
-                       until, err = time.ParseDuration(unusedForValues[0])
-                       if err != nil {
-                               return client.PruneInfo{}, errors.Wrap(err, "unused-for filter expects a duration (e.g., '24h')")
-                       }
-               default:
-                       return client.PruneInfo{}, errMultipleFilterValues
-               }
        case 1:
-               if len(unusedForValues) > 0 {
-                       return client.PruneInfo{}, errSynonymFilterValues
-               }
                var err error
                until, err = time.ParseDuration(untilValues[0])
                if err != nil {
```

**Comment by tiborvass** [comment]
@thaJeztah updated.

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Comment by thaJeztah** [comment]
oh; linting issue; 

```
00:12:27 builder/builder-next/builder.go:1::warning: file is not gofmted with -s (gofmt)
00:12:27 builder/builder-next/builder.go:1::warning: file is not goimported (goimports)
```

File: builder/builder-next/builder.go [hunk 4]
```diff
@@ -130,6 +145,9 @@ func (b *Builder) Prune(ctx context.Context, opts types.BuildCachePruneOptions)
 
 	validFilters := make(map[string]bool, 1+len(cacheFields))
 	validFilters["unused-for"] = true
+	validFilters["until"] = true
+	validFilters["label"] = true  // TODO(tiborvass): handle label
```
Comment (vdemeester) [inline builder/builder-next/builder.go]: Not sure why those two (`label` and `!label`) are here if they are not implemented yet :thinking:

**Review by vdemeester — CHANGES_REQUESTED** [review]

File: builder/builder-next/builder.go (hunk 4 above)
Comment (thaJeztah) [reply builder/builder-next/builder.go]: We could possibly do it on the cli side for now (https://github.com/docker/cli/pull/152)

Comment (tiborvass) [reply builder/builder-next/builder.go]: @vdemeester I should have commented in the code, but the idea is that it prevents from erroring out on `system prune --filter label=foobar`.

**Review by tonistiigi — APPROVED** [review]

File: builder/builder-next/builder.go (hunk 4 above)
Comment (thaJeztah) [reply builder/builder-next/builder.go]: I think having both would actually be best for now (so that a 18.09.0 cli connecting to a 18.09.1 daemon would work without getting errors)

So, I guess this is ok for now

**Comment by thaJeztah** [comment]
@vdemeester I'll merge this one; we can continue discussing https://github.com/moby/moby/pull/38238#discussion_r235280758 if you want 🤗
