### PR TITLE
Run TestPushInterrupt on separate daemon

### LINKED ISSUE #12645: TestPushMultipleTags inconsistent
this is inconsistent on devmapper machines see jenkins (https://jenkins.dockerproject.com/job/Docker%20Master/label=centos-devicemapper/1249/console)

```
FAIL: docker_cli_push_test.go:69: DockerSuite.TestPushMultipleTags

docker_cli_push_test.go:89:
    c.Fatalf("pushing the image to the private registry has failed: %s, %v", out, err)
... Error: pushing the image to the private registry has failed: time="2015-04-22T00:45:16Z" level=fatal msg="Error response from daemon: push 127.0.0.1:5000/dockercli/busybox is already in progress" 
, exit status 1
```

### PR DESCRIPTION
**Pull request by LK4D4**
In main daemon it produced races because push is background daemon
operation.
Fix #12645

### CODE REVIEW

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
closes #12645

**Comment by jfrazelle** [comment]
ping @jlhawn

File: integration-cli/docker_cli_push_test.go [hunk 1]
```diff
@@ -111,9 +115,7 @@ func (s *DockerSuite) TestPushInterrupt(c *check.C) {
 	if err := pushCmd.Process.Kill(); err != nil {
 		c.Fatalf("Failed to kill push process: %v", err)
 	}
-	// Try agin
-	pushCmd = exec.Command(dockerBinary, "push", repoName)
-	if out, err := pushCmd.CombinedOutput(); err == nil {
+	if out, err := d.Cmd("push", repoName); err == nil {
```
Comment (duglin) [inline integration-cli/docker_cli_push_test.go]: I would prefer if we didn't exit this test until the push finished. So rather than starting up a new daemon, let's just wait until this push is done (ie. we don't get back "already in progress" error, after the 1st one) and then let the func exit.

**Comment by LK4D4** [comment]
@duglin I made changes. It appeared much faster.

**Comment by duglin** [comment]
thanks!
LGTM once janky is happy

**Comment by jlhawn** [comment]
:+1:

**Comment by duglin** [comment]
You're allowed to merge your own PRs?  :-)

**Comment by jfrazelle** [comment]
thats when it is the most fun

**Comment by duglin** [comment]
A whole new set of options just opened up!
