### PR TITLE
Don't smoosh hostname and domainname in API

### LINKED ISSUE #14282: Docker doesn't configure UTS namespace or /etc/hostname correctly
Edit: My assertion about setting `domainname` may be suspect; see phemmer's comment and discussion below. The issue of erroneously passing the FQDN to `syscall.Sethostname` remains however.

### Environment
````
vagrant@vagrant-ubuntu-utopic-64:~$ docker --version
Docker version 1.7.0, build 0baf609
````

### Problem
Docker accepts a fully qualified domain name as the argument to `--hostname`, and models separate `Hostname` and `Domainname` fields in `runconfig.Config`; however once inside libcontainer only `Hostname` is modelled, and this erroneously includes the domain name which is then fed into `syscall.Sethostname` with the following results:

````
vagrant@vagrant-ubuntu-utopic-64:~$ docker run --hostname test.example.com -ti ubuntu
root@test:/# hostname
test.example.com
root@test:/# domainname
(none)
````

This is not correct; the value passed to `syscall.Sethostname` should be the unqualified hostname, and the remainder to `syscall.Setdomainname`. This would yield the expected output:
````
vagrant@vagrant-ubuntu-utopic-64:~$ docker run --hostname test.example.com -ti ubuntu
root@test:/# hostname
test
root@test:/# domainname
example.com
````

Currently, libcontainer does not invoke `syscall.Setdomainname` at all, leaving the domain name parameter of the UTS namespace uninitialised.

Docker is also incorrectly generating an `/etc/hostname` file with the fully qualified name - again this should be the unqualified name, and the FQDN set by aliasing in `/etc/hosts`.

It could also be argued that `--hostname` should be renamed to `--fqdn`, or changed so that it admits only an unqualified name and companioned by a new `--domainname` option to set the remainder.

Finally, the error message is uninformative:
````
docker run --hostname 012345678901234567890123456789012345678901234567890123456789.example.com -ti ubuntu
Error response from daemon: Cannot start container c1bb14c2a10b2341c185aed804ab6f625ca7a1164ea90ea4fd37ea56b6e2bed0: [8] System error: invalid argument
````

### Consequences
* UTS namepsace not correctly initialised
* The underlying `sethostname` system call limits the hostname to 64 characters. Because Docker is calling it with the fully qualified name, the entire FQDN is limited to 64 characters (weaveworks/weave#1006)

### PR DESCRIPTION
**Pull request by thockin**
Fixes #14282 

I think this is a better solution than #20196.  Rather than make the CLI split `--hostname`, let it happen at the backend.  This preserve's the user's intentions all the way through.  No API change needed.  No behavioral change from the CLI.  The results of `docker inspect` will be different for `--hostname=foo.bar.com` containers, but the user-visible behavior is the same.  The only behavioral change is for API users that specify both `hostname` and `domainname`, in which case the container's hostname will just be the `hostname` field.  Otherwise it behaves exactly the same.

Tests and docs are not updated yet, pending someone saying they don't hate this.  And yes, it obviously has to go into libnetwork, not here.  I'll do all that if folks say this is OK.

### CODE REVIEW

**Comment by estesp** [comment]
Haven't had a chance to play with this, but it looks like a promising fix to the originally thorny problem of figuring out the intent vs. distro differences that brought up the original bug.

When you say `docker inspect` is changed, I assume you mean it will just show the entire FQDN as `Hostname` with a blank `Domainname` for the CLI usecase of `--host=hostname.domainname`, which would have been shown separately due to the splitting logic being at the "front-end" prior to this PR.

I think the only downside is that for non-API uses with a FQDN in `--host`, this PR doesn't fix the max length problem for the `SetHostname` syscall. I remember one of the difficulties when I worked on the original "fix" is that even though the Docker container config has the concept of a separate hostname/domainname, **libcontainer** [does not](https://github.com/opencontainers/runc/blob/master/libcontainer/configs/config.go#L108-L109), and the passthrough is the somewhat clunky env. variable `HOSTNAME` set into the process config buffer, which the execdriver [then uses](https://github.com/docker/docker/blob/master/daemon/execdriver/driver_unix.go#L140) to set up the libcontainer variant of the container's config. However, at least this allows for proper use via the API and with the libnetwork changes, gives you a more appropriate setup for differentiating hostname and domainname, and more importantly fixes the hostname length max issue for that use case.

**Comment by thockin** [comment]
Yes, your assessment of the This doesn't fix the length issue

**Comment by thockin** [comment]
hmm, fat fingers.

Yes, your assessment of the `docker inspect` difference is right.

This does not fix the length issue - that is inherent to the idea that
`hostname` is an FQDN.  we could add a `--domainname` cli flag, which
would empower CLi users as much as API users, but I didn't want to do
that without deeper consideration and use-cases.  That is an easy
followup, though.

libcontainer doesn't really need to keep hostname and domainname
separate - all libcontainer cares about is what value to pass to
`syscall.Sethostname()` and that value is whatever the user passed as
`hostname` to CLI or API.

**Comment by thaJeztah** [comment]
@thockin can you sign-off your commit? :innocent:

**Comment by estesp** [comment]
Now that the initial overall WIP has been floated for discussion, I would suggest the libnetwork PR can be created for review as well, and those 2 file changes dropped from this PR. Don't know if @mavenugo or others want to weigh in here, or wait for a libnetwork PR. I personally think this is a reasonable fix for a long-standing issue around hostname vs. fqdn.

**Comment by mavenugo** [comment]
thanks @thockin @estesp. yes, we will look into this mainly to make sure it doesn't introduce any serious regression.
ping @sanimej

**Comment by thockin** [comment]
Thanks.

I will prep a "real" patch against libnetwork and sign this and update docs
in the next couple days

**Comment by jhowardmsft** [comment]
Some missing CI jobs here. They need kicking off again. Signing the commit and force pushing should resolve that.

**Comment by sanimej** [comment]
@thockin The change looks ok for fixing the API. But in the current form it breaks the existing behavior for net host. I think we can retain the current behavior by not splitting the os.Hostname() into host and domain name in initializeNetworking

```
        if container.HostConfig.NetworkMode.IsHost() {
                container.Config.Hostname, err = os.Hostname()
                if err != nil {
                        return err
                }

                parts := strings.SplitN(container.Config.Hostname, ".", 2) 
                if len(parts) > 1 {
                        container.Config.Hostname = parts[0]
                        container.Config.Domainname = parts[1]
                }       

        }
```

**Comment by thockin** [comment]
@sanimej  re --net-host : Do you think it is sufficient to set the hostname and not the domainname?  Or should we actually get the domainname (exec `hostname -d`) and set the domainname field?

**Comment by thockin** [comment]
Also - thoughts on what docs need to be updated?

**Comment by sanimej** [comment]
@thockin For --net=host mode its sufficient to set only the hostname. This will cover the case where hostname is an fqdn. When the hostname is not an fqdn, /etc/hosts should typically have the fqdn. Since the /etc/hosts file is copied in the --net=host mode container should get the right dnsdomainname.

**Comment by sanimej** [comment]
@thaJeztah Can you please help in identifying the docs that need to be updated for this change ? I don't see hostname & fqdn being specifically discussed in any of the docs. But probably we have to update the API documentation to clarify the behavior ?

**Comment by thaJeztah** [comment]
@sanimej I'll have a look at the docs; from a design perspective, does this LGTY (the networking team?) if it does, we can move this forward to code review

**Comment by sanimej** [comment]
@thaJeztah Yes, This is a reasonable solution without adding any UI or API changes.

There is one expected change in docker inspect output though; as mentioned earlier by @estesp 

>When you say docker inspect is changed, I assume you mean it will just show the entire FQDN as Hostname with a blank Domainname for the CLI usecase of --host=hostname.domainname, which would have been shown separately due to the splitting logic being at the "front-end" prior to this PR.

**Comment by thaJeztah** [comment]
For the documentation, I think we need;

- A mention in the API changes, because specifying both `hostname` and `domainname` gives a different result; https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api.md#v123-api-changes 
- Possibly update the example output of the inspect response as mentioned above

IIUC, the `--hostname` on the CLI will keep the same behavior?

**Comment by thockin** [comment]
API doc updated.

I did not find any docs that talk about hostname/domainnname in particular - is there one you were thinking about?  

Yes, CLI behavior is unchanged.

rebased and repushed.  Still waiting on the libnetwork change.

File: daemon/container_operations_unix.go [hunk 1]
```diff
@@ -23,9 +23,9 @@ import (
 	"github.com/docker/docker/pkg/mount"
 	"github.com/docker/docker/pkg/stringid"
 	"github.com/docker/docker/runconfig"
+	"github.com/docker/docker/vendor/src/github.com/docker/go-units"
```
Comment (calavera) [inline daemon/container_operations_unix.go]: we should not change this, the old path was correct.

File: runconfig/opts/parse.go [hunk 2]
```diff
@@ -13,11 +13,11 @@ import (
 	flag "github.com/docker/docker/pkg/mflag"
 	"github.com/docker/docker/pkg/mount"
 	"github.com/docker/docker/pkg/signal"
+	"github.com/docker/docker/vendor/src/github.com/docker/go-units"
```
Comment (calavera) [inline runconfig/opts/parse.go]: we should not change this, the old path was correct.

Comment (estesp) [inline runconfig/opts/parse.go]: I've been having trouble with my vim go-plugins setup making this same change; only on `go-units`  Haven't figured out what is special, although one time I got frustrated enough to play with GOPATH and other bits until I got it to not change it for that session :(

File: daemon/container_operations_unix.go (hunk 1 above)
Comment (thockin) [inline daemon/container_operations_unix.go]: ugh, will fix

**Comment by thockin** [comment]
import paths fixed

**Comment by thockin** [comment]
libnetwork change is in.  waiting for it to be vendored

**Comment by cpuguy83** [comment]
@thockin it's vendored now.

**Comment by thockin** [comment]
Rebased and test fixed, I think

**Comment by thaJeztah** [comment]
Thanks @thockin

**Comment by thaJeztah** [comment]
oh cr*p, @thockin looks like it needs another rebase already :cry:

**Comment by thockin** [comment]
rebased

**Comment by thaJeztah** [comment]
ping @estesp @cpuguy83 PTAL

**Comment by estesp** [comment]
LGTM. Thanks @thockin

**Comment by thockin** [comment]
Anything I need to do regarding the failed windows tests?

**Comment by cpuguy83** [comment]
Can we "fix" the inspect output for older clients?

**Comment by thockin** [comment]
@cpuguy83 I think I am out of my depth on that question.

**Comment by calavera** [comment]
LGTM, let's move this forward to docs review.

**Comment by thaJeztah** [comment]
thanks, LGTM - not sure if there's anything else to document :smile:

**Comment by calavera** [comment]
Docs LGTM too.
