### PR TITLE
dockerd: fix rootless detection (alternative to #39024)

### LINKED ISSUE #38702: Rootful-Docker-in-Rootless-Docker doesn't work
**Description**

Rootful docker in Rootless docker does not work

**Steps to reproduce the issue:**
1. Start rootless docker
2. Within rootless docker, start `dockerd` as the root(-in-userns).
3. Run `docker run -it --rm busybox` against Rootful-Docker-in-Rootless-Docker

**Describe the results you received:**
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:275: applying cgroup configuration for process caused \"mkdir /sys/fs/cgroup/cpuset/docker: permission denied\"": unknown.
```

**Describe the results you expected:**
It should work

**Additional information you deem important (e.g. issue happens only occasionally):**

Running Rootful-Docker-in-Rootless-Docker daemon with `--experimental --rootless` doesn't make sense here currently, as it tries to use `$XDG_RUNTIME_DIR` and so on.

Probably we should let `--rootless` disable cgroups but ignore `$XDG_RUNTIME_DIR` when `$USER=="root" || $USER==""`.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           18.09.1-rc1
 API version:       1.39
 Go version:        go1.10.5
 Git commit:        bca0068
 Built:             Fri Dec  7 05:28:04 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          dev
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.11.5
  Git commit:       93d994e29c
  Built:
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.0-243-g6b25c1e4
  GitCommit:        6b25c1e45c2b8246dba17de3b1d574f6720ce79f
 runc:
  Version:          1.0.0-rc6+dev
  GitCommit:        bbb17efcb4c0ab986407812a31ba333a7450064c
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: dev
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6b25c1e45c2b8246dba17de3b1d574f6720ce79f
runc version: bbb17efcb4c0ab986407812a31ba333a7450064c
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.15.0-45-generic
Operating System: Ubuntu 18.04.1 LTS (containerized)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.829GiB
Name: e9a9508c8101
ID: UZUL:JHFE:3567:N2FE:YUZL:XKRW:EKQB:I35U:MTDM:7Y3Z:3EO6:DWL5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### LINKED ISSUE #39009: 19.03.0-beta1: could not get XDG_RUNTIME_DIR (dockerd fails to start)
I _think_ this is related to #38050. There's a minor regression in Docker 19.03.0-beta1 where `dockerd` fails to start sometimes (for example, like in an environment with a crappy init system such as boot2docker :sweat_smile:).

The full `dockerd` daemon log is simply:

```
could not get XDG_RUNTIME_DIR
```

(No other context or decoration.)

What's odd is that if I then do `sudo dockerd` (or `sudo /etc/init.d/docker restart`) from the running system (still no `XDG_RUNTIME_DIR`), the daemon does start up successfully, and I get the following log:

<details>

```console
WARN[2019-04-05T23:43:08.090959172Z] Error while setting daemon root propagation, this is not generally critical but may cause some functionality to not work or fallback to less desirable behavior  dir=/mnt/sda1/var/lib/docker error="error writing file to signal mount cleanup on shutdown: open /var/run/docker/unmount-on-shutdown: no such file or directory"
INFO[2019-04-05T23:43:08.095138264Z] libcontainerd: started new containerd process  pid=2022
INFO[2019-04-05T23:43:08.096216254Z] parsed scheme: "unix"                         module=grpc
INFO[2019-04-05T23:43:08.097255716Z] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2019-04-05T23:43:08.099090111Z] ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}]  module=grpc
INFO[2019-04-05T23:43:08.102403587Z] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2019-04-05T23:43:08.104440977Z] pickfirstBalancer: HandleSubConnStateChange: 0xc000907180, CONNECTING  module=grpc
INFO[2019-04-05T23:43:08.112139160Z] starting containerd                           revision=bb71b10fd8f58240ca47fbb579b9d1028eea7c84 version=v1.2.5
INFO[2019-04-05T23:43:08.113987956Z] loading plugin "io.containerd.content.v1.content"...  type=io.containerd.content.v1
INFO[2019-04-05T23:43:08.115299816Z] loading plugin "io.containerd.snapshotter.v1.btrfs"...  type=io.containerd.snapshotter.v1
WARN[2019-04-05T23:43:08.116726388Z] failed to load plugin io.containerd.snapshotter.v1.btrfs  error="path /mnt/sda1/var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter"
INFO[2019-04-05T23:43:08.119075104Z] loading plugin "io.containerd.snapshotter.v1.aufs"...  type=io.containerd.snapshotter.v1
WARN[2019-04-05T23:43:08.121777265Z] failed to load plugin io.containerd.snapshotter.v1.aufs  error="modprobe aufs failed: "modprobe: module aufs not found in modules.dep\n": exit status 1"
INFO[2019-04-05T23:43:08.123618491Z] loading plugin "io.containerd.snapshotter.v1.native"...  type=io.containerd.snapshotter.v1
INFO[2019-04-05T23:43:08.124999971Z] loading plugin "io.containerd.snapshotter.v1.overlayfs"...  type=io.containerd.snapshotter.v1
INFO[2019-04-05T23:43:08.126379107Z] loading plugin "io.containerd.snapshotter.v1.zfs"...  type=io.containerd.snapshotter.v1
WARN[2019-04-05T23:43:08.127694182Z] failed to load plugin io.containerd.snapshotter.v1.zfs  error="path /mnt/sda1/var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter"
INFO[2019-04-05T23:43:08.130024085Z] loading plugin "io.containerd.metadata.v1.bolt"...  type=io.containerd.metadata.v1
WARN[2019-04-05T23:43:08.131322823Z] could not use snapshotter zfs in metadata plugin  error="path /mnt/sda1/var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter"
WARN[2019-04-05T23:43:08.133547776Z] could not use snapshotter btrfs in metadata plugin  error="path /mnt/sda1/var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter"
WARN[2019-04-05T23:43:08.135778359Z] could not use snapshotter aufs in metadata plugin  error="modprobe aufs failed: "modprobe: module aufs not found in modules.dep\n": exit status 1"
INFO[2019-04-05T23:43:08.144145908Z] loading plugin "io.containerd.differ.v1.walking"...  type=io.containerd.differ.v1
INFO[2019-04-05T23:43:08.145448785Z] loading plugin "io.containerd.gc.v1.scheduler"...  type=io.containerd.gc.v1
INFO[2019-04-05T23:43:08.146558838Z] loading plugin "io.containerd.service.v1.containers-service"...  type=io.containerd.service.v1
INFO[2019-04-05T23:43:08.147918118Z] loading plugin "io.containerd.service.v1.content-service"...  type=io.containerd.service.v1
INFO[2019-04-05T23:43:08.149332607Z] loading plugin "io.containerd.service.v1.diff-service"...  type=io.containerd.service.v1
INFO[2019-04-05T23:43:08.150786735Z] loading plugin "io.containerd.service.v1.images-service"...  type=io.containerd.service.v1
INFO[2019-04-05T23:43:08.152199109Z] loading plugin "io.containerd.service.v1.leases-service"...  type=io.containerd.service.v1
INFO[2019-04-05T23:43:08.153600837Z] loading plugin "io.containerd.service.v1.namespaces-service"...  type=io.containerd.service.v1
INFO[2019-04-05T23:43:08.154949926Z] loading plugin "io.containerd.service.v1.snapshots-service"...  type=io.containerd.service.v1
INFO[2019-04-05T23:43:08.156298463Z] loading plugin "io.containerd.runtime.v1.linux"...  type=io.containerd.runtime.v1
INFO[2019-04-05T23:43:08.157625323Z] loading plugin "io.containerd.runtime.v2.task"...  type=io.containerd.runtime.v2
INFO[2019-04-05T23:43:08.158910070Z] loading plugin "io.containerd.monitor.v1.cgroups"...  type=io.containerd.monitor.v1
INFO[2019-04-05T23:43:08.160393344Z] loading plugin "io.containerd.service.v1.tasks-service"...  type=io.containerd.service.v1
INFO[2019-04-05T23:43:08.161765553Z] loading plugin "io.containerd.internal.v1.restart"...  type=io.containerd.internal.v1
INFO[2019-04-05T23:43:08.163081227Z] loading plugin "io.containerd.grpc.v1.containers"...  type=io.containerd.grpc.v1
INFO[2019-04-05T23:43:08.164348950Z] loading plugin "io.containerd.grpc.v1.content"...  type=io.containerd.grpc.v1
INFO[2019-04-05T23:43:08.165513999Z] loading plugin "io.containerd.grpc.v1.diff"...  type=io.containerd.grpc.v1
INFO[2019-04-05T23:43:08.166576714Z] loading plugin "io.containerd.grpc.v1.events"...  type=io.containerd.grpc.v1
INFO[2019-04-05T23:43:08.167807444Z] loading plugin "io.containerd.grpc.v1.healthcheck"...  type=io.containerd.grpc.v1
INFO[2019-04-05T23:43:08.169117759Z] loading plugin "io.containerd.grpc.v1.images"...  type=io.containerd.grpc.v1
INFO[2019-04-05T23:43:08.170392962Z] loading plugin "io.containerd.grpc.v1.leases"...  type=io.containerd.grpc.v1
INFO[2019-04-05T23:43:08.171652273Z] loading plugin "io.containerd.grpc.v1.namespaces"...  type=io.containerd.grpc.v1
INFO[2019-04-05T23:43:08.173037925Z] loading plugin "io.containerd.internal.v1.opt"...  type=io.containerd.internal.v1
INFO[2019-04-05T23:43:08.174412861Z] loading plugin "io.containerd.grpc.v1.snapshots"...  type=io.containerd.grpc.v1
INFO[2019-04-05T23:43:08.175730582Z] loading plugin "io.containerd.grpc.v1.tasks"...  type=io.containerd.grpc.v1
INFO[2019-04-05T23:43:08.177005749Z] loading plugin "io.containerd.grpc.v1.version"...  type=io.containerd.grpc.v1
INFO[2019-04-05T23:43:08.178286183Z] loading plugin "io.containerd.grpc.v1.introspection"...  type=io.containerd.grpc.v1
INFO[2019-04-05T23:43:08.179525192Z] serving...                                    address="/var/run/docker/containerd/containerd-debug.sock"
INFO[2019-04-05T23:43:08.180787557Z] serving...                                    address="/var/run/docker/containerd/containerd.sock"
INFO[2019-04-05T23:43:08.182128898Z] containerd successfully booted in 0.070259s  
INFO[2019-04-05T23:43:08.183101659Z] pickfirstBalancer: HandleSubConnStateChange: 0xc000907180, READY  module=grpc
INFO[2019-04-05T23:43:18.206935688Z] parsed scheme: "unix"                         module=grpc
INFO[2019-04-05T23:43:18.210937015Z] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2019-04-05T23:43:18.215314493Z] parsed scheme: "unix"                         module=grpc
INFO[2019-04-05T23:43:18.218095290Z] scheme "unix" not registered, fallback to default scheme  module=grpc
WARN[2019-04-05T23:43:18.244684001Z] Your kernel does not support cgroup blkio weight 
WARN[2019-04-05T23:43:18.246043866Z] Your kernel does not support cgroup blkio weight_device 
INFO[2019-04-05T23:43:18.247584742Z] Loading containers: start.                   
INFO[2019-04-05T23:43:18.293411069Z] ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}]  module=grpc
INFO[2019-04-05T23:43:18.295132306Z] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2019-04-05T23:43:18.296176657Z] pickfirstBalancer: HandleSubConnStateChange: 0xc0000d2b00, CONNECTING  module=grpc
INFO[2019-04-05T23:43:18.297622715Z] pickfirstBalancer: HandleSubConnStateChange: 0xc0000d2b00, READY  module=grpc
INFO[2019-04-05T23:43:18.298885226Z] ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}]  module=grpc
INFO[2019-04-05T23:43:18.300519142Z] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2019-04-05T23:43:18.301515716Z] pickfirstBalancer: HandleSubConnStateChange: 0xc0000d2da0, CONNECTING  module=grpc
INFO[2019-04-05T23:43:18.305061025Z] pickfirstBalancer: HandleSubConnStateChange: 0xc0000d2da0, READY  module=grpc
INFO[2019-04-05T23:43:18.325335224Z] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address 
INFO[2019-04-05T23:43:18.352683593Z] Loading containers: done.                    
INFO[2019-04-05T23:43:18.361786810Z] Docker daemon                                 commit=62240a9 graphdriver(s)=overlay2 version=19.03.0-beta1
INFO[2019-04-05T23:43:18.363669299Z] Daemon has completed initialization          
INFO[2019-04-05T23:43:18.398293695Z] API listen on /var/run/docker.sock           
```
</details>

I think that first line is probably the most interesting/worrying although I'm not clear on what it means or if it's even remotely related to the initial failure that's got me filing an issue? (honestly if I hadn't run into the `XDG_RUNTIME_DIR` failure I wouldn't even be looking into this, let alone filing an issue :smile:)

`Error while setting daemon root propagation, this is not generally critical but may cause some functionality to not work or fallback to less desirable behavior  dir=/mnt/sda1/var/lib/docker error="error writing file to signal mount cleanup on shutdown: open /var/run/docker/unmount-on-shutdown: no such file or directory"`

I'm a little bit confused about why it would only look for (and error out on) `XDG_RUNTIME_DIR` _sometimes_, but also about why the error output is entirely undecorated.

To be clear, this is a fully clean environment, kernel version 4.14.111, no pre-existing `/var/lib/docker` contents, and if I swap in 18.09.4 into the ISO instead it works flawlessly.

The init script runs `dockerd --data-root /mnt/sda1/var/lib/docker -H unix:// --pidfile /var/run/docker.pid`, which doesn't seem particularly exotic (`/mnt/sda1` is a freshly-formatted `ext4` partition and `/mnt/sda1/var/lib/docker` is pre-created via `mkdir -p`), and does work if I simply run it again after it fails.

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>

**- What I did**
Fix #38702 #39009

**- How I did it**

The `--rootless` flag had a couple of issues:
* #38702: euid=0, $USER="root" but no access to cgroup ("rootful" Docker in rootless Docker)
* #39009: euid=0 but $USER="docker" (rootful boot2docker)

To fix #38702, XDG dirs are ignored as in rootful Docker, unless the
dockerd is directly running under RootlessKit namespaces.

RootlessKit detection is implemented by checking whether `$ROOTLESSKIT_STATE_DIR` is set.

To fix #39009, the non-robust `$USER` check is now completely removed.

The entire logic can be illustrated as follows:

```go
withRootlessKit := getenv("ROOTLESSKIT_STATE_DIR")
rootlessMode := withRootlessKit || cliFlag("--rootless")
honorXDG := withRootlessKit
useRootlessKitDockerProxy := withRootlessKit
removeCgroupSpec := rootlessMode
adjustOOMScoreAdj := rootlessMode
```

Close #39024
Fix #38702 #39009

**- How to verify it**

* Make sure the regular rootless mode works:

```console
$ dockerd-rootless.sh --experimental
WARN[2019-04-25T17:17:48.240093114+09:00] Running experimental build
WARN[2019-04-25T17:17:48.240656519+09:00] Running in rootless mode. Cgroups, AppArmor, and CRIU are disabled.
INFO[2019-04-25T17:17:48.241104912+09:00] Running with RootlessKit integration
...
INFO[2019-04-25T17:17:48.991132927+09:00] API listen on /run/user/1001/docker.sock
```

* Make sure "rootful" docker in rootless docker works, with the socket listening on `/var/run/docker.sock` in the container, not on `$XDG_RUNTIME_DIR/docker.sock` in the container:
```console
$ export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock
$ docker run -it --rm --name kinda-rootful-in-rootless --privileged -v /usr/local:/usr/local ubuntu
/ # apt update && apt install -y kmod iptables ca-certificates
/ # dockerd --experimental --rootless
WARN[2019-04-25T07:46:48.534752062Z] Running experimental build
WARN[2019-04-25T07:46:48.535769972Z] Running in rootless mode. Cgroups, AppArmor, and CRIU are disabled.
...
INFO[2019-04-25T07:46:48.909046101Z] API listen on /var/run/docker.sock
```

* Make sure setting `$USER` to non-"root" does not break rootful Docker

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**
https://twitter.com/hashtag/WorldPenguinDay?f=image

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
@tonistiigi @tiborvass @cpuguy83 @tianon @thaJeztah 

I'd like to get this merged before DockerCon 🙏

**Comment by tonistiigi** [comment]
Not a functional change and only slightly different but can

```
withRootlessKit := getenv("ROOTLESSKIT_STATE_DIR")
rootlessMode := withRootlessKit || cliFlag("--rootless")
honorXDG := withRootlessKit
useRootlessKitDockerProxy := withRootlessKit
removeCgroupSpec := rootlessMode
adjustOOMScoreAdj := rootlessMode
```

be 


```
withRootlessKit := getenv("ROOTLESSKIT_STATE_DIR")
rootlessMode := cliFlag("--rootless")
honorXDG := withRootlessKit && rootlessMode
useRootlessKitDockerProxy := withRootlessKit && rootlessMode
removeCgroupSpec := rootlessMode
adjustOOMScoreAdj := rootlessMode
```

**Comment by AkihiroSuda** [comment]
That might be hard to implement, because `honorXDG` is used for setting up default config before parsing CLI flags such as `--rootless`.

**Comment by tonistiigi** [comment]
@AkihiroSuda Ok, not that important.

**Review by tonistiigi — APPROVED** [review]

**Comment by AkihiroSuda** [comment]
@tianon @cpuguy83

PTAL?

File: rootless/rootless.go [hunk 1]
```diff
@@ -5,22 +5,21 @@ import (
...
-// even if we are in a user namespace.
-func RunningWithNonRootUsername() bool {
-	runningWithNonRootUsernameOnce.Do(func() {
-		u := os.Getenv("USER")
-		runningWithNonRootUsername = u != "" && u != "root"
+// RunningWithRootlessKit returns true if running under RootlessKit namespaces.
+func RunningWithRootlessKit() bool {
+	runningWithRootlessKitOnce.Do(func() {
+		u := os.Getenv("ROOTLESSKIT_STATE_DIR")
+		runningWithRootlessKit = u != ""
```
Comment (cpuguy83) [inline rootless/rootless.go]: Should we look for a truth value here such as 1 || true ?

Comment (AkihiroSuda) [reply rootless/rootless.go]: This is a directory path, not boolean.

https://github.com/rootless-containers/rootlesskit/blob/master/README.md#environment-variables

Comment (cpuguy83) [reply rootless/rootless.go]: Omg, early morning... don't mind me...

Comment (thaJeztah) [reply rootless/rootless.go]: @cpuguy83 good to go?

**Review by cpuguy83 — APPROVED** [review]
LGTM

File: rootless/rootless.go (hunk 1 above)
Comment (cpuguy83) [reply rootless/rootless.go]: Yes, didn't mark it since I was on a bus on my phone 😺

**Comment by dinvlad** [comment]
Rootful ("child") `docker info` reports `vfs` as storage driver, even on Ubuntu hosts for which rootless `docker info` host reports `overlay2`. Is `overlay`/`overlay2` going to be supported for the child Docker? Thanks!

**Comment by AkihiroSuda** [comment]
Yes, but make sure to create volume for `/home/foo/.local`

**Comment by dinvlad** [comment]
Thanks @AkihiroSuda! We're now running the rootless container as follows:
```
docker run -it --rm --name kinda-rootful-in-rootless --privileged -v $HOME/bin:/opt/docker/bin:ro -v /lib/modules:/lib/modules:ro -v docker:/var/lib/docker ubuntu
```
Not that `-v docker:/var/lib/docker` creates rootless `docker` volume for use by rootful docker as `overlay2`.
Additionally, we mount host `/lib/modules` into the rootless container, so that we get rid of `modprobe` warnings (not sure if this is necessary though).

With these changes, the only "suspicious" warning we still get on startup of rootful `dockerd` is `Not using native diff for overlay2, this may cause degraded performance for building images: failed to set opaque flag on middle layer: operation not permitted  storage-driver=overlay2`
