### PR TITLE
Debugging issue #25511

### LINKED ISSUE #25511: Flaky plugin removal/disable tests
```
21:57:43 
21:57:43 ----------------------------------------------------------------------
21:57:43 FAIL: docker_cli_plugins_test.go:60: DockerSuite.TestPluginForceRemove
21:57:43 
21:57:43 docker_cli_plugins_test.go:69:
21:57:43     c.Assert(err, checker.IsNil)
21:57:43 ... value *errors.errorString = &errors.errorString{s:"exit status 1: Error response from daemon: remove /var/lib/docker/plugins/45f2caec2589a81aabc18b29a817f3092ee0781d991fba6ad4d53766e7b57b19/rootfs/data: device or resource busy\n"} ("exit status 1: Error response from daemon: remove /var/lib/docker/plugins/45f2caec2589a81aabc18b29a817f3092ee0781d991fba6ad4d53766e7b57b19/rootfs/data: device or resource busy\n")
21:57:43 
21:57:45 
21:57:45 ----------------------------------------------------------------------
21:57:45 FAIL: docker_cli_plugins_test.go:73: DockerSuite.TestPluginInstallDisable
21:57:45 
21:57:45 docker_cli_plugins_test.go:92:
21:57:45     c.Assert(err, checker.IsNil)
21:57:45 ... value *errors.errorString = &errors.errorString{s:"exit status 1: Error response from daemon: remove /var/lib/docker/plugins/c2d213881f2a3608b01755a261824f05bf290614f9b5b259ccdc83c793af4737/rootfs/data: device or resource busy\n"} ("exit status 1: Error response from daemon: remove /var/lib/docker/plugins/c2d213881f2a3608b01755a261824f05bf290614f9b5b259ccdc83c793af4737/rootfs/data: device or resource busy\n")
21:57:45 
21:57:46 
21:57:46 ----------------------------------------------------------------------
```

Seen in:

https://jenkins.dockerproject.org/job/Docker-PRs-experimental/22139/console
https://jenkins.dockerproject.org/job/Docker%20Master%20(experimental)/4079/console

cc @anusha-ragunathan @tiborvass

### PR DESCRIPTION
**Pull request by anusha-ragunathan**
Volumes and other content created under a bind mount should be
recursively propagated using rshared, not shared. This could be
the reason for EBUSY during removal. Override options with rbind,
rshared and see if CI errors are fixed.

May fix #25511

Signed-off-by: Anusha Ragunathan anusha@docker.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @tonistiigi @cpuguy83 PTAL!

**Comment by tiborvass** [comment]
LGTM

File: plugin/manager_linux.go [hunk 1]
```diff
@@ -90,7 +90,13 @@ func (pm *Manager) initSpec(p *plugin) (*specs.Spec, error) {
 		if mount.Source != nil {
 			m.Source = *mount.Source
 		}
+
 		if m.Source != "" && m.Type == "bind" {
+			/* Debugging issue #25511: Volumes and other content created under the
```
Comment (vdemeester) [inline plugin/manager_linux.go]: Maybe we should update a bit the comment

Comment (anusha-ragunathan) [inline plugin/manager_linux.go]: What would you update it as?

**Comment by vieux** [comment]
LGTM

**Comment by tonistiigi** [comment]
`TestPluginForceRemove` failure in https://github.com/docker/docker/pull/25778 experimental https://jenkins.dockerproject.org/job/Docker-PRs-experimental/22500/consoleFull after this was merged.

File: plugin/manager_linux.go (hunk 1 above)
Comment (vdemeester) [inline plugin/manager_linux.go]: It was just the *Debugging* that was bugging me but no worries :angel:

**Comment by justincormack** [comment]
And again https://jenkins.dockerproject.org/job/Docker-PRs-experimental/22532/console

```
18:13:41 
18:13:41 ----------------------------------------------------------------------
18:13:41 FAIL: docker_cli_plugins_test.go:60: DockerSuite.TestPluginForceRemove
18:13:41 
18:13:41 docker_cli_plugins_test.go:69:
18:13:41     c.Assert(err, checker.IsNil)
18:13:41 ... value *errors.errorString = &errors.errorString{s:"exit status 1: Error response from daemon: remove /var/lib/docker/plugins/afea8513b8e43d40b92150b2e15c1617543dae5aa73bcc1730eba1738cad043a/rootfs/data: device or resource busy\n"} ("exit status 1: Error response from daemon: remove /var/lib/docker/plugins/afea8513b8e43d40b92150b2e15c1617543dae5aa73bcc1730eba1738cad043a/rootfs/data: device or resource busy\n")
18:13:41 
18:13:43 
18:13:43 ----------------------------------------------------------------------
```
